### ISSUE TITLE
[RFC] Replace `StaticArray(T)#[]=(T)` with `#fill`

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#10024]
[`StaticArray(T)#[]=(value : T)`](https://crystal-lang.org/api/0.35.1/StaticArray.html#[]=(value:T)-instance-method) is the only `#[]=` method in the entire standard library that expects 1 argument instead of 2, and the given example even uses the functional syntax instead of the operator syntax for this:

```crystal
array = StaticArray(Int32, 3).new { |i| i + 1 }
array.[]= 2 # => nil
array       # => StaticArray[2, 2, 2]
```

No other usage of `#[]=` in the standard library assumes that a missing index refers to every element. It is even more confusing when considering a similar syntax for `Array`:

```crystal
array = Array(Int32).new(3) { |i| i + 1 }
array[..] = 2
array # => [2]
```

`Array(T)` defines [`#fill(value : T)`](https://crystal-lang.org/api/0.35.1/Array.html#fill(value:T)-instance-method) for this purpose. We should do the same in `StaticArray` too before 1.0.0:

```crystal
array = StaticArray(Int32, 3).new { |i| i + 1 }
array.fill(2) # => StaticArray[2, 2, 2]
```

That's just one out of 8 overloads for `Array#fill`. Does it make sense to port the remaining 7 to `StaticArray`?

**Comment by asterite** [comment]
Yes, please! I think I copied that behavior from D, but it reads a bit strange.

I think at least renaming it ton`fill` will be good. There's no need for all the variants, though. They can come later if needed but I don't think they will be needed at all.
