### ISSUE TITLE
`File#read_at` limited to Int32

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#10032]
Currently https://github.com/crystal-lang/crystal/blob/master/src/file/preader.cr#L7's ivars are typed as `Int32`, this prevents reading a large enough file at points greater than `Int32::Max`.

Similarly, thoughts on making `bytesize` be nilable?  This would support the use case of "read the remainder of a file starting at offset x" when using https://crystal-lang.org/api/master/File.html#read_at(offset,bytesize,&)-instance-method.

**Comment by asterite** [comment]
Yes for the first thing, I don't know about the second one, maybe it's okay.
