### ISSUE TITLE
No backtraces in release/no-debug mode?

### ISSUE THREAD

**Issue by docelic** [crystal-lang/crystal#10048]
I have a program where I want unhandled exceptions to print the message to screen and exit the program. And this is what happens by default.

But it also tries to print the backtrace, which is both undesired for end users as well as useless since there's no information.

Consider this example:

```sh
crystal build --release --no-debug myprog.cr
strip myprog
./myprog

Unhandled exception: Error opening file with mode 'r': 'gfs': No such file or directory (File::NotFoundError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from __crystal_once
  from __crystal_main
  from ???
  from ???
  from main
  from __libc_start_main
  from _start
  from ???
```

@naqvis on Gitter provided this suggestion to patch the behavior:

```cr
module Crystal::System
  {% if flag?(:release) %}
  def self.print_exception(message, ex)
    print_error "%s: %s (%s)\n", message, ex.message || "(no message)", ex.class.name
  end
 {% end %}
end
```

But (regardless of the specific implementation) could we consider adding this behavior/feature as an official feature?

**Comment by asterite** [comment]
You need to use begin/rescue around your main program. This is what the compiler does, for example.

**Comment by docelic** [comment]
Sure. I just wanted to avoid that because it forces the user to add it to every program, as well as additionally control when the backtrace should be printed and when not (probably involving use of macro code, as the above example showed).

Given that the lack of debug symbols (--no-debug) immediately makes it clear that backtrace is useless, maybe this should be built-in functionality.

**Comment by didactic-drunk** [comment]
Sometimes empty backtraces are useful for tracking down problems.  A generic error 15 levels deep can be distinguished from one 7 levels deep. In ops that's often enough to ignore a known problem that's being worked on or identify a new problem that needs debugging. 

For expected errors that cause the program to exit, would something like [err](https://www.man7.org/linux/man-pages/man3/err.3.html) be useful?

**Comment by straight-shoota** [comment]
I think the current behaviour the best default. If you decide that your program should not print backtraces, you can easily change that. But it's better to require a concious opt-out instead of just failing to print stacktraces. There is some value, even without debug symbols.

**Comment by docelic** [comment]
Ok, thanks for input.
