### ISSUE TITLE
[RFC] Converting constructors for Tuple and NamedTuple

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#10041]
The `Tuple.new` constructor works when the generic type vars are deduced, but if they are explicitly provided, this oddity occurs:

```crystal
typeof(Tuple(Int32 | String).new(1)) # => Tuple(Int32)
```

This is correct behaviour; when `Tuple` is instantiated, its `.new` constructor is the same as writing

```crystal
def self.new(*args : *{Int32 | String})
  args
end
```

which, when splatted manually, is equivalent to

```crystal
def self.new(__args_0 : Int32 | String)
  {__args_0}
end
```

As `Int32 < Union(Int32, String)`, the arguments match the constructor successfully, and a `Tuple(Int32)` is returned. But for such fundamental types as `Tuple` and `NamedTuple` which back every splat and double splat, this behaviour might be undesirable in certain places, especially if #10036 happens, since `Tuple(Int32 | String).new(1).is_a?(Tuple(Int32 | String))` would be `false` after `Tuple` loses covariance. These types provide an alternative, the `.from` constructor:

```crystal
typeof(Tuple(Int32 | String).from([1])) # => Tuple(Int32 | String)
```

The disadvantage is immediate: it requires an allocation of `Array` (`Hash` in the case of `NamedTuple`), even though none is needed. Thus I propose the addition of `.new!`, which performs casts on a splat automatically: (error handling omitted)

```crystal
struct Tuple
  def self.new!(*args : *U) forall U
    {% begin %}
      new(
        {% for i in 0...T.size %}
          args[{{ i }}].as({{ T[i] }}),
        {% end %}
      )
    {% end %}
  end
end

typeof(Tuple(Int32 | String).new!(1)) # => Tuple(Int32 | String)
Tuple.new!(1)                         # undefined constant T
```

Such a constructor cannot overload `.from` as ambiguity would arise if any of the element types is itself an `Array` or `Hash`.

**Comment by jhass** [comment]
Why should we keep `.new` instead of replacing it with your proposal? I'm not sure adding a fourth way to construct a tuple is really helping the issue :)

**Comment by asterite** [comment]
I think the existing new should work as you propose. Feel free to send a PR and we can see if something breaks. To be honest, before you mentioned it I thought it was already working that way.

**Comment by HertzDevil** [comment]
It's because I couldn't figure out how to replace `Tuple.new` directly so that it works with both deduced and explicitly instantiated `*T`:

```crystal
struct Tuple
  # old `.new` removed

  def self.new(*args : *U) forall U
    {% begin %}
      {
        {% for i in 0...T.size %} # Error: undefined constant T
          args[{{ i }}].as({{ T[i] }}),
        {% end %}
      }
    {% end %}
  end
end

Tuple.new(2)
```

Replacing `T` with `@type` doesn't help:

```
In src/tuple.cr:83:31

 83 | {% for i in 0...@type.size %}
                            ^---
Error: undefined method 'size' for TypeNode of type Tuple(T) (must be a tuple or named tuple type)
```

**Comment by Sija** [comment]
Shouldn't `T` in your example be `U` instead?

**Comment by asterite** [comment]
take a look at https://github.com/crystal-lang/crystal/blob/9f190bc3842382b14aa824d380ee944177d5ce47/src/slice.cr#L36

a bit hacky but it works. and we can later improve it
