### ISSUE TITLE
Request: thread/fiber pool (or http request pool) equivalent

### ISSUE THREAD

**Issue by LeXofLeviafan** [crystal-lang/crystal#10043]
I wrote a program recently which downloads a series of webpages (text) for offline reading; and there's more or less only two ways I could implement it – it's either all in the same fiber (thus I have to wait for each download to be completed before the next one starts) or it runs in separate fibers and sends every request at once (or at least a large number of them simultaneously), which causes connection problems with remote server (as it's basically a mini-DDoS attack). It would be nice to have a built-in way to limit the amount of simultaneous worker fibers and/or requests to the same server with some sort of a pool (as of now, I resolved the issue by manually grouping request URLs into a fixed number of queues and processing each queue in order in its own fiber – thus roughly simulating a thread pool functionality).

I've also had an issue with passing around some data (because apparently thread safe/non-modifying methods are not recognised as such by the compiler) but it was much easier to resolve in my case (simply by moving the calculations to before the fiber is spawned).

**Comment by straight-shoota** [comment]
I'd say this is mostly covered by #6468
There's also shards offering a pool implementation, for example https://shardbox.org/shards/fiberpool

**Comment by Blacksmoke16** [comment]
Also related: https://github.com/crystal-lang/crystal-db/pull/131.

**Comment by LeXofLeviafan** [comment]
> I'd say this is mostly covered by #6468

I wouldn't say that low-level functionality to add/cancel threads dynamically (which is what it seems to be about) is particularly helpful with that… It gives a tool to work with, but the amount of effort required to actually implement the functionality of a thread pool on top of it would likely be no less than that of implementing a workaround without dynamic fibers.

> There's also shards offering a pool implementation, for example https://shardbox.org/shards/fiberpool

…Welp. It seems I've spent so much time trying to work around the issue I managed to forget that 3rd party code is a thing %-)
Although, I do believe this should be a feature available in the core language.

> Also related: crystal-lang/crystal-db#131.

I honestly never considered looking for a _generic_ thread pool implementation in the DB subproject.
…And even if I looked, I wouldn't find one, as there's only a `DB::Pool` which doesn't have any indication it can be used for anything else within its documentation. In fact, there seems to be a woeful lack of documentation regarding certain available features in Crystal (even if they're experimental, they should be documented _somehow_ if they're available… I only stumbled upon `-Dpreview_mt` description by complete accident _in a blog_, and I'm certain I haven't seen any mention of the `parallel` macro anywhere until I saw it in that #6468 discussion).

**Comment by Sija** [comment]
> > There's also shards offering a pool implementation, for example https://shardbox.org/shards/fiberpool
> 
> …Welp. It seems I've spent so much time trying to work around the issue I managed to forget that 3rd party code is a thing %-)
> Although, I do believe this should be a feature available in the core language.
> Edit: I've just checked, and this particular shard doesn't work with current implementation of Crystal (it uses `Channel::ReceiveAction` which seems to have been removed since v0.27).

@LeXofLeviafan fwiw, the fix turned out to be simple and it's submitted as https://github.com/akitaonrails/fiberpool/pull/2

**Comment by straight-shoota** [comment]
Closing. There are shards for some of the use cases. Concurrency features in stdlib are tracked in https://github.com/crystal-lang/crystal/issues/6468
