### ISSUE TITLE
Rename `HTTP::Params` to `URI::Params`

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#10052]
`HTTP::Params` is actually a pretty generic implementation of attribute-value pairs as they are used in different URI schemes, not only for HTTP.

It's used as return type of `URI#query_params` which supports the argument that it is not closely connected to HTTP since there's no other direct relation there.

**Comment by asterite** [comment]
Makes sense to me. We can probably make `HTTP::Params` an alias and eventually remove it.
