### ISSUE TITLE
Docs generator doesn't parse Markdown correctly when reading URLS that have parens in them.

### ISSUE THREAD

**Issue by sol-vin** [crystal-lang/crystal#10058]
When making a method definition in Crystal like:
```crystal
# Create a mask object and add it to this `Celestine::Meta::Context`
def filter(&block : Celestine::Filter -> Celestine::Filter)
end
```

`crystal docs` will make a method stub URL that is linked like:
```
https://docs.celestine.dev/Celestine/Meta/Context.html#filter(&block:Celestine::Filter-%3ECelestine::Filter)-instance-method
```

However, linking these in your README file causes the docs generator to not parse the URL correctly.

An Example for Comparison:

Using the following text in the README:

```
 * [Celestine::Filter](https://docs.celestine.dev/Celestine/Filter.html) -> [filter](https://docs.celestine.dev/Celestine/Meta/Context.html#filter(&block:Celestine::Filter-%3ECelestine::Filter)-instance-method)
```
You would expect that the link would be parsed into
```
Celestine::Filter -> filter
```

but instead parses as:
```
Celestine::Filter -> filter-instance-method)
```

A video to better illustrate: https://youtu.be/xD9zna2gJIA

Some Links to see for yourself. Check the `Usage` sections.
https://github.com/celestinecr/celestine (correct)
vs
https://docs.celestine.dev/ (broken)

**Comment by jhass** [comment]
IIRC technically parenthesis are not valid in URIs, you would need to encode them.

Looking at [a comparison](https://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Bfilter%5D(https%3A%2F%2Fdocs.celestine.dev%2FCelestine%2FMeta%2FContext.html%23filter(%26block%3ACelestine%3A%3AFilter-%253ECelestine%3A%3AFilter)-instance-method)) of different markdown implementations, the majority tries to handle this well though.

**Comment by redcodefinal** [comment]
> 
> 
> IIRC technically parenthesis are not valid in URIs, you would need to encode them.
> 
> Looking at [a comparison](https://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Bfilter%5D(https%3A%2F%2Fdocs.celestine.dev%2FCelestine%2FMeta%2FContext.html%23filter(%26block%3ACelestine%3A%3AFilter-%253ECelestine%3A%3AFilter)-instance-method)) of different markdown implementations, the majority tries to handle this well though.

You are probably right, but this is the form you get if you go to the method list at the top of the a docs page, and right click and use `copy link location`. Maybe `crystal docs` should encode these automatically?

**Comment by asterite** [comment]
What happens if you render this with a shard called markd?

**Comment by redcodefinal** [comment]
> 
> 
> What happens if you render this with a shard called markd?

Works as expected. It properly parsed the URL.
![aaaaaa](https://user-images.githubusercontent.com/1298501/101549364-650f1e80-3962-11eb-806b-6889b2e675a5.PNG)

**Comment by asterite** [comment]
Well, ai wanted to use markd inside the compiler until we extract the docs generator to a separator cool.

Please, core team, can we do that? The author of markd was fine with that. A temporary solution that fixes the problem right now is better than a potential solution that who knows when will be done, if ever.

**Comment by redcodefinal** [comment]
I see two acceptable solutions to this:

 1. Ensure all links `crystal docs` generates are HTML escaped
 2. Fix markdown processing to work for parens in the URL.

One is clearly easier than the other IMO.

**Comment by asterite** [comment]
For me the easiest thing is number 2, because complaints about incorrect markdown processing happen and will happen until we fix that.

**Comment by straight-shoota** [comment]
I never understood why we removed `Markdown` from stdlib because it is utterly broken but then just made it a compiler internal and still continue to build API docs with it.

**Comment by asterite** [comment]
Okay, here's what's going to happen. I'm going to send a PR to fix this. I won't include the original git history of markd because we'll eventually move this entire thing into a separate tool. But for 1.0 this will be working fine. Some of you ( @straight-shoota ) will approve it, and I will merge it. Then someone will send a PR to revert it, but nobody will approve it. Sounds like a plan?
