### ISSUE TITLE
[RFC] Move combinations, permutations, etc., from Array to Indexable

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#10063]
Today I was working with a `Deque` and I wanted to use `each_combination(2)` with it... but it doesn't work! It's only defined in Array.

I think this is because these methods predate the introduction of `Indexable`.

It would be great if we move these methods to `Indexable`. Then you could ask all permutations over a Tuple, Deque, Slice, StaticArray, and more!

Of course the question is: what does these methods return? In the case of `Array` they return `Array`. Should they return a `Deque` in the case of `Deque`? Or a `Tuple` in the case of a `Tuple`? Well, the answer to the second question is easy: there's no way to return `Tuple` because the return value's size is "kind of" dynamic: it depends on the number passed to the method, which is a runtime value.

With that in mind, I think they should always return `Array`: `Array` is the default "list-like" collection type.

So, to implement this we would just need to move these methods from `Array` to `Indexable`.

**Comment by asterite** [comment]
While we are at this, we can probably move `sample` too to `Indexable`.

**Comment by asterite** [comment]
Hmmm... this might be harder to implement than what I thought. This relies on a `#[index, count]` method on Array. Maybe that should also be part of `Indexable`, always returning `Array`... I'm not sure.

I won't be tackling this for now, but if you think this is interesting and useful, please go ahead! 🙏

**Comment by straight-shoota** [comment]
Sounds good. `Array` as default is probably fine. It doesn't necessarily make sense to use the same type (when possible) because you would typically use it differently than the original type.
If you want a different type for the results, you can specify that in the `reuse` argument.

**Comment by straight-shoota** [comment]
A default implementation of `#[index, count]` behaviour could rely on `#each(*, start : Int, count : Int, &)` and build an array. It doesn't necessarily need to be exposed as a public method `#[index, count]`, though. Implementing a private helper should be fine for the purpose of those collection methods. We could leave `#[index, count]` for types that can implement it efficiently (like `Array`).

**Comment by HertzDevil** [comment]
`#[](index, count)` is only required on the individual pools returned by `#permutations` and friends, we shouldn't have to do anything with it if by default each element is still an `Array`.

> While we are at this, we can probably move `sample` too to `Indexable`.

That's just #9954.
