### ISSUE TITLE
Overdosing on GC

### ISSUE THREAD

**Issue by mwlang** [crystal-lang/crystal#10079]
My Advent of Code Day 15 runs fine in Ruby (< 5 seconds), but runs forever in Crystal. It's quite literally the Ruby code slightly changed to suit Crystal's data typing restrictions. Initial assessment is GC kicks into overdrive with this implementation and slows the program to absolute crawl (> 1 hour and running...).  

It works for smaller problem space, just not the 300 millionth one. https://github.com/mwlang/advent-of-code/tree/main/2020/15

## Crystal Version

```crystal
def play(starting, turns)
  collection = Hash(Int32,Array(Int32)).new
  numbers = starting.map_with_index{ |v,t| collection[v] = [t + 1]}
  numbers = starting.reverse

  (turns - numbers.size).times do |turn|
    current_turn = starting.size + turn + 1
    current = collection[numbers[0]]

    if current.size == 1
      numbers.unshift(0)
      collection[0] << current_turn
    else
      age = current[-1] - current[-2]
      numbers.unshift(age)
      collection[age] ||= Array(Int32).new
      collection[age] << current_turn
    end
  end
  numbers[0]
end

puts play [0,3,6], 10
puts play [2,20,0,4,1,17], 2020
puts play [2,20,0,4,1,17], 30_000_000
```

## Ruby Version

```Ruby
def play starting, turns
  collection = {}
  numbers = starting.map.with_index{ |v,t| collection[v] = [t + 1]}
  numbers = starting.reverse

  (turns - numbers.size).times do |turn|
    current_turn = starting.size + turn + 1
    current = collection[numbers[0]]

    if current.size == 1
      numbers.unshift(0)
      collection[0] << current_turn
    else
      age = current[-1] - current[-2]
      numbers.unshift(age)
      collection[age] ||= []
      collection[age] << current_turn
    end
  end
  numbers[0]
end

puts play [0,3,6], 10
puts play [2,20,0,4,1,17], 2020
puts play [2,20,0,4,1,17], 30_000_000
```

**Comment by mwlang** [comment]
For what it's worth, I tried disabling GC and pre-allocating max-extent of the arrays needed at the outset:  

https://play.crystal-lang.org/#/r/a468

No change in behavior observed.

**Comment by asterite** [comment]
Do you need to store all numbers? I don't think so.

I think it's slow because of unshift, which had to copy all array elements over an over. Instead, try not reversing numbers and use push.

**Comment by asterite** [comment]
I have an optimization for this but it was rejected because of speculation. I will try again.

**Comment by asterite** [comment]
@mwlang With #10081 (which hopefully will get merged this time) your code runs in 5 seconds for me.

**Comment by mwlang** [comment]
You're right in that all the numbers do not need to be stored for a correct solution.  #10081 looks exactly like it probably solves this and I have encountered this many times in other code where I basically had to work out ways to not be changing the Array, Deque, etc. in ways that caused memory to be copied just as described in #10081.  Very happy to see this fix coming!
