### ISSUE TITLE
Crystal programs doesn't work on Windows 7 due to GetCurrentThreadStackLimits

### ISSUE THREAD

**Issue by konovod** [crystal-lang/crystal#10085]
Right now the programs compiled with Crystal for Windows will only work on Windows 8 and higher.
The only cause (as far as I know) is the usage of function `GetCurrentThreadStackLimits`.
There is a way to get stack lower limit on win7(and lower), that is described here: https://stackoverflow.com/a/52404641
I understand that Windows 7 is outdated, but in this case just a simple patch will really increase availability of crystal programs.

**Comment by kubo** [comment]
> The only cause (as far as I know) is the usage of function `GetCurrentThreadStackLimits`.

[`GetSystemTimePreciseAsFileTime`](https://github.com/crystal-lang/crystal/search?q=GetSystemTimePreciseAsFileTime) also.

**Comment by straight-shoota** [comment]
For reference, this has also come up on the forum recently: https://forum.crystal-lang.org/t/will-there-be-cross-compile-support-for-windows-7/3168

**Comment by straight-shoota** [comment]
Windows 7 has reached end of life in January. It's certainly still in use but not very much in demand. So I'm actually wondering if this really makes much sense.
@konovod I don't expect you have a specific use case for this since you mentioned you didn't even test #11505 on Windows 7?

I think we'd be happy to accept contributions which backport support for Windows 7 APIs, but it needs to be properly implemented and tested (manual tests are fine).

**Comment by konovod** [comment]
> I don't expect you have a specific use case for this

Specific use case is that in some gamedev communities Windows 7 is pretty popular. 
For example, current challenge on gamedev.ru [require](https://gamedev.ru/projects/forum/?id=263782) support of Windows 7 to participate.
Even if it isn't required by challenge rules, lacking of Windows 7 support means no feedback from some experienced folks in such communities.
So: personally, I don't need that compiler runs on Windows 7, but i want that my Crystal programs runs on it. So while i'm not sure when I'll be able to try compiler on Windows 7 (hopefully, soon), the important part for me is to test that compiled programs runs on windows 7.

I understand that PR isn't easy thing, so i'm ready to use a local fork instead if that's not going to happen. I can replace compile-time flag in my PR with `GetProcAddress`, but this will be the first use of this function in codebase, so maybe there is some catch?

**Comment by wrobby493-cell** [comment]
Be strong in any situation you are going through know that many people go through the same problems almost every day. I’m happy to announce my finding of solutions for recovering my money from these crooks. If you’ve been ripped off email recoveryexpert326 at gmail dot com I was in the same shoes also and know how it feels to be ripped off by someone you trusted with your investment They take no upfront payment  Just email this recovery agent and thank me later God bless you and stay safe
