### ISSUE TITLE
Segmentation fault reading backtrace of exception outside main routine

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#10088]
An exception raised outside the main routine should be printed safely directly to STDERR with `print_exception`.
But aquiring the backtrace leads to a segmentation fault:

```cr
module Crystal
  def self.main(&block)
    raise "foo"
  end
end
```
```console
$ crystal run test.cr
Unhandled exception: foo (Exception)
Program exited because of a segmentation fault (11)
```

A quick workaround is to disable backtrace for these errors. With #10086 `print_exception` should be invoked very rarely and when that happens, it is a major runtime failure. A backtrace won't be that much useful.

**Comment by straight-shoota** [comment]
With a compiler built from current master the segmentation fault has disappeared and the error now looks like this:

```
Unhandled exception: foo (Exception)
Error while trying to dump the backtrace: Invalid magic number (Crystal::ELF::Error)
```

But: The magic number is correct (`Bytes[127, 69, 76, 70]`). The problem is that `Crystal::ELF::Magic` is empty, despite being initialized like this:

https://github.com/crystal-lang/crystal/blob/d7e63db70bc257be2952d03dc3b284b5758937ea/src/crystal/elf.cr#L9

This looks really suspicious.

**Comment by straight-shoota** [comment]
Oh wait, does a custom main function inhibit constant initialization?

**Comment by bcardiff** [comment]
Yes, you are missing a call to `LibCrystalMain.__crystal_main` which initialize the constants. I would not complain if that method generated by the compiler is refactored in an `__init_runtime` and `__crystal_main`

**Comment by straight-shoota** [comment]
Yeah, that'd be useful for custom main functions.
That wasn't how I initially hit this issue, though. Maybe a custom main was also involved, but the proper context was handling errors that appeared outside the regular error handler. I suppose an exception during runtime setup may lead to similar situation.
