### ISSUE TITLE
Feature Request: Arrow syntactic sugar for channels

### ISSUE THREAD

**Issue by jecolon** [crystal-lang/crystal#10108]
Instead of 
```
channel.send(x)
x = channel.receive()
```
why not
```
channel <- x
x = <-channel
```
or for receive, maybe even
```
x <- channel
```
I know this is pretty much how it's done in Go, buy hey, it's expressive and fluid, and I think would be a perfect fit for Crystal's already awesome syntax.

**Comment by kostya** [comment]
https://play.crystal-lang.org/#/r/a544, with `<<`

**Comment by jecolon** [comment]
Yes, overloading the left-shift operator would work, but I find it could be a little confusing given it's used often as an append operation. I still find the arrow more indicative of movement of data, which is what channels are all about. But if using the arrow would be impossible for some reason, this alternative is somewhat close to achieving the expressiveness desired.

**Comment by jecolon** [comment]
Giving it some more thought overloaded left-shift could also be confusing if actually needing to left-shift by the received value:
```
x << << channel
```
In such a case parenthesis would probably be necessary to make intentions clear, which I find less expressive or fluid.

**Comment by asterite** [comment]
To be honest, I find Go's syntax pretty confusing and unreadable. Making the arrow be in one side or another doesn't let me read code quickly. send and receive are pretty obvious and simple.

**Comment by jecolon** [comment]
I see. It's definitely a matter of personal preference and coding style. To me, the arrow notation clearly expresses intent, but that's a purely subjective perception on my part. On a more language design level, I ask if it would be a good or bad idea for the language to provide a way (somewhat like macros) for the user to add their own operators, specifying precedence if necessary. I'm totally new to Crystal, but from what I've read in the docs, only the built-in operators are allowed as "special" methods that the compiler allows to break the normal naming rules for methods and processes them differently according to operator precedence rules. At first glance, I think it would be an interesting feature to be able to add operators like macros allow us to add "pseudo" methods that in the end are just syntactic sugar and compile down to normal Crystal code.

**Comment by asterite** [comment]
All of those things exist in other languages, but in my opinion they make the language more complex for very little benefit. If you can do `channel.send(...)`, what benefit do we get by allowing `channel <- x` (I had to lookup how you write that because I already forgot it)? Well, it's maybe a bit shorter. Maybe it's a bit more descriptive? But then we have to add an extra rule to the language. Or maybe we need to introduce custom operators? Then people start introducing operators like `<*>` and `<?>` and `:<|>:` (I'm looking at you, Haskell and Elm) and the code because an unpronounceable mess.

I think the current situation is just fine. No magic, no syntax sugar.

**Comment by straight-shoota** [comment]
Also custom operators would be really tricky with respect to precedence rules. Those rules are hard coded in the parser and tied directly to the literal operator, independent of its behavioural implementation.

**Comment by asterite** [comment]
@straight-shoota in Haskell and Elm you can define the operator precefence

**Comment by straight-shoota** [comment]
Yes, I was refering to Crystal's implementation. If we wanted to support that, it would add a lot of complexity overhead.

**Comment by asterite** [comment]
Oh, yes, definitely.

**Comment by jecolon** [comment]
The point about users taking a customization capability and going wild with it can be applied to pretty much any such facility, including macros, but it's a valid point nonetheless. The performance side would matter more from my point of view; if the feature hinders performance, forget about it. Thanks all for the discussion. Hope to be building something awesome in Crystal soon!
