### ISSUE TITLE
Request for clarification regarding BigInt hashing

### ISSUE THREAD

**Issue by collidedscope** [crystal-lang/crystal#10107]
Hello, Crystal team, and thank you for all that you do.

I recently chanced upon a need to store negative `BigInt`s as `Hash` keys, only to discover that Crystal does not currently support that operation. After scratching my head over the somewhat surprising `OverflowError`, I eventually found my way to [the culprit](https://github.com/crystal-lang/crystal/blob/4c835ff9271f4277327467b73f0eb0091ebebc90/src/big/big_int.cr#L410-L411). Perhaps there's good reason for the unsignedness there, but the following monkey-patch hasn't presented any adverse effects in my limited testing:

```crystal
struct BigInt
  def_hash to_i64
end
```

It'd be nice if that became the default, but I'd understand if it's a little too niche to be worth bothering with.

Much more interesting to me was the callout to find a better way of doing it altogether. I'm not intimately familiar with the codebase, but I understand it to be the case that hash key collision only occurs if the hashes of two objects compare equal as well as the objects themselves. Is there some known situation where simply narrowing the `BigInt` to 64 bits is an insufficiently robust approach to hashing? Under what circumstances could two `BigInt`s pass the equality check despite not representing the same value?

I ask because I'd like to take a crack at pursuing this TODO, but wanted to double-check with those more knowledgeable that the solution isn't to just remove the comment. :sweat_smile:

**Comment by Sija** [comment]
https://github.com/crystal-lang/crystal/blob/4c835ff9271f4277327467b73f0eb0091ebebc90/src/big/big_int.cr#L410-L411

Hmm, why not use `to_s` instead? Should solve this and the rest of the problems with over/underflowing value.

**Comment by asterite** [comment]
Let's use to_s for now. There's mpz_export but we can take a look at that later.

**Comment by collidedscope** [comment]
> There's mpz_export [...]

You were in my head! It does seem like using `#to_s` solves the problem for most intents and purposes, but doing it "correctly" isn't too much more involved due to how fluidly Crystal is able to interact with C libraries:

```crystal
@[Link("gmp")]
lib LibGMP
  fun export = __gmpz_export(rop: Void*, countp: SizeT*, order: Int, size: SizeT,
                             endian: Int, nails: SizeT, op: MPZ*) : Void*
end

struct BigInt
  def export(word_size = sizeof(LibC::Int))
    bytes = LibGMP.export(nil, nil, 1, word_size, 0, 0, self)
    String.new bytes.as(UInt8*)
  end

  def_hash export
end
```

I've no doubt missed some subtleties here, but is this roughly the shape of how we'd want to go about it in the long run?

**Comment by straight-shoota** [comment]
This also relates to #9299 and #10101

**Comment by asterite** [comment]
I wouldn't make the export method public. Big int relies on libgmp but that fact shouldn't be exposed.

Let's use to_s for now.

**Comment by oprypin** [comment]
I think the fix is much simpler, just change `to_u64` to `to_u64!` in the implementation. Doesn't break hash invariants like https://github.com/crystal-lang/crystal/pull/10115#issuecomment-748598951.

I'm guessing this is just a regression from introducing integer overflow checks.

**Comment by straight-shoota** [comment]
Yeah `to_u64!` should work for `BigInt`. But it's not just that. Other big types are more complicated.

**Comment by oprypin** [comment]
Funnily, if we changed even the native types to also be hashed through `to_s`, that would solve all possible hash mismatch problems once and for all. Way too wasteful, though.

**Comment by asterite** [comment]
Oh, yeah, I think to_u64! should be done instead, to_s is too expensive.

**Comment by oprypin** [comment]
But wait @straight-shoota , are you saying that "other big types" can overflow when doing `to_f64` on them? I think it's a solvable problem.

Actually wait, I'm failing to find any overflow.

Why is this not failing on current Crystal, despite what this issue describes?

`require "big"; p BigInt.new("555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555").hash`

**Comment by oprypin** [comment]
Ah nvm, it fails only for negative numbers.

But `BigInt.new("555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555").to_u64` silently overflows, that's just yet another bug.

**Comment by Sija** [comment]
https://github.com/crystal-lang/crystal/blob/1db7d5f3b593aa874fd99a0bf7cbad00da1deef2/src/big/big_int.cr#L529-L536

IIUC `LibGMP::ULong == UInt64` evaluates to true causing this behaviour.

Shouldn't there be `&&` instead?

**Comment by oprypin** [comment]
This code was correct prior to the introduction of overflow exceptions, it just wasn't adapted.

What it's saying here is, if libgmp returns a uint64 (which it doesn't on 32bit systems apparently), don't bother manually truncating the number ourselves.

**Comment by oprypin** [comment]
I'll send an alternate pull request for this bug

**Comment by oprypin** [comment]
Found another bigint bug:

`BigInt.new("-1111111111111111111").to_u64! == 1111111111111111111`
