### ISSUE TITLE
[RFC] Sampling in any Enumerable

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#10118]
Supersedes #9954 and #10103. It came to my realization that reservoir sampling, the current algorithm used for sampling without replacement, only needs to traverse each element exactly once. Thus `Enumerable`'s contract is sufficient for the sampling methods; one should not have to convert every container to an `Array` in order to pick its elements randomly.

Sampling a single element then becomes a special case of reservoir sampling with `n = 1`. The current requirement on `#size` is so that `Indexable` can optimize this to a constant-time operation; outside `Indexable`, the same optimization won't work even if `#size` is defined and finite, because `random.rand(size)` doesn't translate to a useful index.

If sampling methods are defined in `Enumerable`, then it becomes obvious that the multiple-element overload should return an `Array(T)` even for types like `Set` and `Hash`. #10103 tried to return a `Set` by yielding an array of shuffled internal indices, but this intermediate array cannot be avoided anyway, so calling `Enumerable#sample` and then `#to_set` shouldn't make a huge difference.

Likewise the single-element overload should return `T`; particularly for `Hash(K, V)` this is the key-value pair.

**Comment by asterite** [comment]
How do you implement this on enumerables where the size is not know, or potentially infinite enumerables?

**Comment by j8r** [comment]
I guess using `size_hint` from #10075 . When not present, thus potentially infinite, the method can raise.

**Comment by asterite** [comment]
@j8r Do you understand that `size_hint` is a **HINT** and not the actual size?

**Comment by HertzDevil** [comment]
> enumerables where the size is not know

More or less the same as #10103. `n = {size, n}.min` is unnecessary; if there aren't enough elements, iteration simply stops early and the result is equivalent to `map(&.itself).shuffle`. Knowing the size upfront lets us use that optimization, but reservoir sampling doesn't require it. More specifically:

```crystal
module Enumerable(T)
  def sample(n : Int, random = Random::DEFAULT)
    ary = Array(T).new(n)
    return ary if n == 0

    each_with_index do |value, i|
      if i < n
        ary << value
      else
        j = random.rand(i + 1)
        if j <= n
          ary.to_unsafe[j] = value
        end
      end
    end

    ary.shuffle!
  end
end
```

An example of an `Enumerable` with an indeterminate size is `Char::Reader`:

```crystal
require "char/reader"

# string with chars from 1-4 utf-8 bytes
str = "CryĆŕŷＣｒｙ🄒🄡🄨"
Char::Reader.new(str).sample(5, Random.new(1)) # => ['C', '🄡', 'ŷ', 'ŕ', 'Ｃ']
Char::Reader.new(str).sample(15).sort # => ['C', 'r', 'y', 'Ć', 'ŕ', 'ŷ', 'Ｃ', 'ｒ', 'ｙ', '🄒', '🄡', '🄨']
```

Sampling an infinite collection is ill-formed as every element has zero probability of being picked. How to detect infinite collections goes into a separate issue.

**Comment by HertzDevil** [comment]
By the way, this means #9648 will be back, even for non-numeric ranges. Finite, numeric ones can be optimized similar to that PR.

**Comment by oprypin** [comment]
https://github.com/oprypin/nim-random/blob/02ea6b3102ead7db985a36ddabfe1cb31c92e1ce/src/random/common.nim#L181 😌
