### ISSUE TITLE
Openssl::digest missing internal dependency

### ISSUE THREAD

**Issue by viraptor** [crystal-lang/crystal#10114]
When using a openssl/digest, there's a dependency on `OpenSSL::Error`, however it's not included by default:
```
require "openssl/digest"
puts OpenSSL::Digest.new("SHA256").hexdigest()
```
results in:
```
class Error < OpenSSL::Error; end
                   ^
Error: undefined constant OpenSSL::Error
```

However this compiles just fine:
```
require "openssl"
require "openssl/digest"
puts OpenSSL::Digest.new("SHA256").hexdigest()
```

Tested on Crystal 0.35.1

**Comment by wonderix** [comment]
```
require "openssl/digest"
puts OpenSSL::Digest.new("SHA256").hexdigest
```

will not work in general allthough it's documented [here|https://crystal-lang.org/api/0.35.1/OpenSSL/Digest.html].
The `hexdigest` class method only works for classes with a parameter-less `new`.

**Comment by wonderix** [comment]
Using the `digest` module make things easier.

```
require "digest/sha256"
puts Digest::SHA256.hexdigest("test")
```

**Comment by viraptor** [comment]
Hmm... Digest doesn't document having SHA256 at all: https://crystal-lang.org/api/0.35.1/Digest.html

Should I file another issue?

**Comment by Sija** [comment]
@viraptor It is [here](https://crystal-lang.org/api/master/Digest.html) - in the docs for nightlies.
