### ISSUE TITLE
Enumerable#sum only works with Complex, Number and Time::Span

### ISSUE THREAD

**Issue by erdnaxeli** [crystal-lang/crystal#10126]
Hi,

The `Enumerable#sum` methods looks like it goes over the enumerable and sums them with the `+` operator. And actually, that's what [it does](https://github.com/crystal-lang/crystal/blob/5999ae29b/src/enumerable.cr#L1413) **if** you give it an initial value.

A lot of types implement the `+` operator, but if you try to sum up something else than Complex, Number or Time::Span types (without an initial value) you end up with an error like this:
```
a = ["a", "b"]
puts a.sum
```

> In /usr/lib/crystal/enumerable.cr:1360:26
> 
>  1360 | sum Reflect(T).first.zero
>                              ^---
> Error: undefined method 'zero' for String.class

(btw this `Reflect` thing looks cool but is totally not documented :p)

I propose to implement a `.zero` method to every type implementing the `+` operator (if having a zero for the type means something, but I bet it does). If there is nothing against that I missed, I will propose a PR.

**Comment by HertzDevil** [comment]
Related: `Enumerable(Complex)#product(initial)` doesn't work, because `initial` is given a `Number` type restriction in order to distinguish it from `Array#product`.

**Comment by Blacksmoke16** [comment]
IMO this would lead to more confusing semantics.  `#sum` is clear on what it does.  In this case it would clearer, and more proper, to use `#join`.

**Comment by erdnaxeli** [comment]
> IMO this would lead to more confusing semantics. `#sum` is clear on what it does.

I disagree. The doc says:

> Adds all the elements in the collection together.
> 
> Only collections of numbers (objects that can be added via an + method) are supported.

Ok, it says "numbers" (I didn't see that), but it also says "objects that can be added via an + method". If we don't want to implement `zero` for others types, this precision should be removed, because a lot of object can be added via an + method but do not work with `#sum`.

>  In this case it would clearer, and more proper, to use `#join`.

I also disagree with using `#join`. Its docs explicitly says that it returns "a String created by concatenating the elements in the collection" (and its implementation use `#to_s`). Making it doing something else, *that* would be confusing.

I don't really see the point of not doing it. From my point of view, as a dev, not implementing `#sum` for every types just produce the following:
* ok I want to add all those objects (array, set, …), let's use `#sum`
* compilation
* oh, right, it does not works with a cryptic error about some `#zero` method
* let's do a `reduce`

**Comment by asterite** [comment]
Let's add a sum_zero class method, or something like that. For String it's the empty string, and so on.

**Comment by asterite** [comment]
Though to be honest passing an empty string to sum doesn't seem too complex.

Also, summing strings like that is very inefficient. Why not join them?

**Comment by straight-shoota** [comment]
I'd support adding a `.sum_zero` class method to types to deliver an initial value for `Enumerable#sum`. A more generic name would be `.addition_identity` because it returns the identity element for addition.

Same should probably be done for similar values, for example `.multiplication_identity` (useful for `Enumerable#product` which currently has `T.first.zero + 1` as initial value).

> I also disagree with using #join. Its docs explicitly says that it returns "a String created by concatenating the elements in the collection" (and its implementation use #to_s). Making it doing something else, that would be confusing.

I don't follow what you mean. What would be the expected difference between `["foo", "bar"].sum` and `["foo", "bar"].join` except that the latter is more idiomatic (and performant)?

**Comment by straight-shoota** [comment]
Maybe for performance optimization `Enumerable(String).sum` could delegate to `join`.

**Comment by erdnaxeli** [comment]
> I'd support adding a `.sum_zero` class method to types to deliver an initial value for `Enumerable#sum`. A more generic name would be `.addition_identity` because it returns the identity element for addition.

I agree with `.addition_identity` :+1: 

> Same should probably be done for similar values, for example `.multiplication_identity` (useful for `Enumerable#product` which currently has `T.first.zero + 1` as initial value).

We could, but the thing is the multiplication has less meaning. What `Array * Array` means? I don't see when `#product` on other thing than numbers could be useful. Currently implementations of `#*` in the stdlib only support a number as second operand.

> I don't follow what you mean. What would be the expected difference between `["foo", "bar"].sum` and `["foo", "bar"].join` except that the latter is more idiomatic (and performant)?

The difference is that `[[1, 2], [2, 3]].join` produce `"[1 2][2 3]"` (as expected), while `[[1, 2], [2, 3]].sum` would produce `[1, 2, 2, 3]`.

My usecase was not about summing string, but arrays and specifically sets, as the `+` does an intersection.

**Comment by Blacksmoke16** [comment]
> The difference is that `[[1, 2], [2, 3]].join` produce `"[1 2][2 3]"` (as expected), while `[[1, 2], [2, 3]].sum` would produce `[1, 2, 2, 3]`.

You probably just want to do `[[1, 2], [2, 3]].flatten`.  Yet another thing that would be more confusing on what exactly you'd expect `.sum` to do...

https://play.crystal-lang.org/#/r/a5hr

**Comment by erdnaxeli** [comment]
Indeed, for array, but for an array of sets?

> Also, summing strings like that is very inefficient. Why not join them?

The performance point is a good one I didn't think about. I tested, and as expected using `#sum` would be inefficient.
```Crystal
require "benchmark"

a = Array(Array(Int32)).new
1000.times { a << (0...1000).to_a }

s = Array(Set(Int32)).new
1000.times { s << Set(Int32).new((0...1000).to_a) }

Benchmark.ips do |x|
  x.report "array sum" { a.reduce(Array(Int32).new) { |acc, x| acc += x } }
  x.report "array concat" { a.reduce(Array(Int32).new) { |acc, x| acc.concat x } }
end

puts

Benchmark.ips do |x|
  x.report "set sum" { s.reduce(Set(Int32).new) { |acc, x| acc += x } }
  x.report "set concat" { s.reduce(Set(Int32).new) { |acc, x| acc.concat x } }
end
```

```
   array sum   2.79  (357.93ms) (± 9.25%)  1.86GB/op  293.25× slower
array concat 819.30  (  1.22ms) (± 9.50%)  7.99MB/op         fastest

   set sum  28.45  ( 35.15ms) (± 4.25%)  11.8MB/op   2.63× slower
set concat  74.94  ( 13.34ms) (± 2.91%)  24.3kB/op        fastest
```

I am surprised that adding sets is not slower btw.

So seeing that, I am asking if we want to promote an inefficient pattern, probably not.

**Comment by straight-shoota** [comment]
@erdnaxeli It doesn't matter that the only relevant use of `Enumerable#product` *with stdlib types* is for numbers. `Enumerable` is general purpose and should be useful for any value types, including ones outside of stdlib. And it's certainly feasible that custom data types define a multiplication operator and would benefit from having a generic way to define multiplication identity.

**Comment by HertzDevil** [comment]
+1 for `.multiplication_identity`. There are types where `T.zero + 1` isn't the multiplicative identity, or even well-formed (e.g. square matrices where `#*` is defined to be the usual matrix multiplication and no shape broadcasting occurs).

**Comment by asterite** [comment]
I really like those names. They are long, very descriptive, and unlikely to clash with other names. And they make sum and product as reusable as possible.

**Comment by Daniel-Worrall** [comment]
I'm for the methods but would prefer they be called additive identity and multiplicative identity as this is what they are actually called in mathematics
