### ISSUE TITLE
cannot chain methods in "when" clause

### ISSUE THREAD

**Issue by erdnaxeli** [crystal-lang/crystal#10124]
Hi,

This code works, and show "size", as expected:
```
a = [] of String
case a
when .size
  puts "size"
end
```

But this one does not:
```
a = [] of String
case a
when .size.seconds
  puts "size"
end
```

It fails with

>  3 | when .size.seconds
>                ^
> Error: unexpected token: . (expecting ',', ';' or '
> 
> ')

I would have expected it to works and puts "size" too, as `a.size.seconds` does not return `nil`.

**Comment by HertzDevil** [comment]
Duplicate of #6396?

**Comment by asterite** [comment]
Duplicate of #6396
