### ISSUE TITLE
Strange, Ambiguous SIGSEGV Error with Arbitrary Crash Times and Arbitrary Addresses: Possible Dangling Pointer

### ISSUE THREAD

**Issue by AlexCouch** [crystal-lang/crystal#10135]
I got a weird segfault which gives me no information whatsoever. It simply just says
```
Invalid memory access (signal 11) at address 0x0
[0x781ec] ???
[0x46090] __crystal_sigfault_handler +164
```
And I have no idea what I'm supposed to do with this. I've tried gdb and it says that the backtrace is corrupt for some reason. The address is seemingly random and changes every time. The time this happens is seemingly random too. Sometimes it happens after half an hour, sometimes after a few minutes. I'm wondering if it's a gc bug or something. I don't do any kinda of unsafety whatsoever. I work with sockets but that's about it. I don't know what else to do.
`crystal env`
```
alex@DESKTOP-5SBUGL2:~/ping_program$ crystal env
CRYSTAL_CACHE_DIR=/home/alex/.cache/crystal
CRYSTAL_PATH=lib:/usr/bin/../share/crystal/src
CRYSTAL_VERSION=0.35.1
CRYSTAL_LIBRARY_PATH=/usr/bin/../lib/crystal/lib
CRYSTAL_OPTS=''
```
`crystal version`
```
alex@DESKTOP-5SBUGL2:~/ping_program$ crystal version
Crystal 0.35.1 [5999ae29b] (2020-06-19)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```
I'm on WSL Ubuntu, and this also occurs on raspberry pi debian. I don't know how to reproduce it. Is this at all a known issue right now? It's not in the issues on github and haven't found anything similar to this. I'm gonna try an older version of crystal and see if that will fix my problem, but if it does, then we know it's a regressive bug introduced recently.

# Code Background
I can't give my whole code cause it's kinda proprietary and haven't gotten the authority to share our software with others, however, there's nothing unsafe about it.
My code listens for clients on one fiber, and spawns a new fiber to handle their queries. There are other fibers for pinging host targets and reporting their statistics to a server. In my test environment, I only have one ping target, and that's my personal PC. It pings from my raspberry pi, and it segfaults at arbitrary times with arbitrary read access violation addresses. As I've said before, I think it's a GC issue. It seems to me like there's a dangling pointer somewhere.

My dependencies are as follows:
* [icmp.cr](https://github.com/robacarp/icmp.cr)
* stdlib

I'm using the TCPServer and TCPSocket for establishing connections with incoming clients and spawning their fibers so we can process their queries and send a response back as fast as possible (perhaps doesn't need to be a fiber, but that's besides the point). I'm also using JSON for the queries and responses and also external json file for configuring the ping targets. Also, OptionParser, and that's it. Nothing else.

One last hint to this is that it only occurs after a client connects. This is really my only hint. I think it's probably something to do with the compact method on Array(T?). Is it possible that when compacting the array into a non-nil copy of it that there may be a dangling pointer left somewhere in memory? I'm not able to debug this further, but this is all I've got.
My compact code is this:
```crystal
if clients.size > 0
    # puts "Cleaning fibers and clients"
    # puts "Number of clients before cleanup: #{@clients.size}"
    @clients = @clients.map do |client|
        if client.fiber.nil? || client.fiber.as(Fiber).dead?
            client.tcp_client.close
            nil
        else
            client
        end
    end.compact
    # puts "Number of clients after cleanup: #{@clients.size}"
end
```
EDIT: I'll come back with a reproducible program considering the above information. I have to do some work work first and focus on my health so please forgive me if there's a delay with getting it, I will have it soon.

**Comment by naqvis** [comment]
Have you tried running the code with GC disabled? if haven't, then give it a try to rule out GC issue. 2nd question would be is your code compiled in MT mode? if answer is yes, try reducing that to single threaded and see if behavior persists. 

There is no universal answer to such random segfaults, but most proably its related to pointer arithmetic (either inside your custom code or via call to stdlib and/or 3rd party shard).

**Comment by AlexCouch** [comment]
> 
> 
> Have you tried running the code with GC disabled? if haven't, then give it a try to rule out GC issue. 2nd question would be is your code compiled in MT mode? if answer is yes, try reducing that to single threaded and see if behavior persists.
> 
> There is no universal answer to such random segfaults, but most proably its related to pointer arithmetic (either inside your custom code or via call to stdlib and/or 3rd party shard).

Ah yes, thank you. I haven't tried either of those. I'm trying to find the resource that tells me how to do those. Could you link me to them?

**Comment by naqvis** [comment]
To compile code with GC disabled pass the flag `-Dgc_none`. If you are not passing any flags when compiling the code then you are not using the MT mode.

Refer to reference guide [Concurrency](https://crystal-lang.org/reference/guides/concurrency.html) section
For parallelism in Crystal refer to blog post [Parallelism in Crystal](https://crystal-lang.org/2019/09/06/parallelism-in-crystal.html)

**Comment by AlexCouch** [comment]
> 
> 
> To compile code with GC disabled pass the flag `-Dgc_none`. If you are not passing any flags when compiling the code then you are not using the MT mode.
> 
> Refer to reference guide [Concurrency](https://crystal-lang.org/reference/guides/concurrency.html) section
> For parallelism in Crystal refer to blog post [Parallelism in Crystal](https://crystal-lang.org/2019/09/06/parallelism-in-crystal.html)

Thank you. I'm running with gc disabled and I let it run for ~10 minutes before it happened. This is the backtrace I got
```
Invalid memory access (signal 11) at address 0x7f76152e3e88
[0x7f762f7a9986] *Exception::CallStack::print_backtrace:Int32 +118
[0x7f762f798355] __crystal_sigfault_handler +341
```
