### ISSUE TITLE
Add constant Math::TAU

### ISSUE THREAD

**Issue by jzakiya** [crystal-lang/crystal#10165]
This is a simple proposal to add the math constant Math::TAU = 2*Math::PI.

See: https://tauday.com/

TAU has been included in a growing number of languages (D, C#, F#, Nim, Zig, Rust, Python3, Julia, et al), and this would add Crystal to that list, and make it even cooler. :-)

**Comment by j8r** [comment]
This is also useful when dealing with radians.

**Comment by straight-shoota** [comment]
I didn't know this before, but the manifest was a good read for starting the new year =)
Sounds like a good idea. Let's help people use the true circle constant.
