### ISSUE TITLE
Nightly on dist_linux32 failing with invalid memory access

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#10175]
32bit specs have been causing trouble lately with running out of memory, and now the `dist_linux32` job fails. This also prevents nightlies for other platforms to be published.

https://app.circleci.com/pipelines/github/crystal-lang/crystal/4918/workflows/a19a6143-a89f-4979-aaea-f3193d6f257d/jobs/57110

**Comment by j8r** [comment]
Only core members can see the job log 😕 
We could try to move to GitHub Actions, the [VMs have 7GB of RAM](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources) – should be enough?

**Comment by Sija** [comment]
> Only core members can see the job log 😕

Not true, just need to log in.

**Comment by j8r** [comment]
Any Circle CI account can access it? Why they require this or access to our GitHub/Bitbucket account... shame :(
