### ISSUE TITLE
[RFC] Steppable module

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#10210]
With #10209 the method `Number#step` becomes an interface used for `Range#step`.

I'm proposing to extract this interface to a module. It's generically applicable, not just for `Number` types.

It is related to `Comparable`, because stepping from one value implies you can compare it to others.
So, my suggestion would be to name it `Comparable::Step` or `Comparable::Stepable`.

The module would define two methods (one yielding, the other returning an iterator) which correspond to the respective `Number` methods in #10209.

```cr
abstract def step(*, to limit = nil, by step, exclusive : Bool = false, &) : Nil
abstract def step(*, to limit = nil, by step, exclusive : Bool = false) : Iterator
```

The current implementations of `Number#step` are pretty generic and works for any types that define basic algebraic operations `+` and `-` (besides `<=>` for `Comparable` of course). These methods could be made re-usable with this module. We could use a sub-module (for example `Comparable::Step::Algebraic`) for this, or a macro (for example `Comparable::Step.def_step_algebraic`). I'm not sure if another type would be very useful for this, so I'd probably prefer a macro.

Another default implementation could define `#step` methods based on `#succ` and `#pred` as it is used in `Range#step` (see https://github.com/crystal-lang/crystal/issues/6709#issuecomment-750421062).

This module could also add generic methods `#upto`/`#downto`/`#to` (as currently defined on `Int`). They would only work for discrete types which have a default step size, though. And since they're just alternate ways to call `#step`, I don't think they're particularly useful.

**Comment by HertzDevil** [comment]
So if `#upto` / `#downto` / `#to` aren't universally applicable, what _else_ does ~~`Stepable`~~ `Steppable` define? And what other types would consume a `Steppable`?

There is little benefit in adding a module if it has few or no methods that exercise its interface and the presence of said module does not improve any existing overload sets. (Same can be said about `Iterable` actually.) Especially not code like:

```crystal
struct Range(B, E)
  def step(...)
    {% if B < Steppable(...) %}
      # step-based implementation
    {% else %}
      # succ-based implementation
    {% end %}
  end
end
```

If `Steppable` doesn't do anything beyond this, that's just #2549 in disguise.

**Comment by straight-shoota** [comment]
Yeah, we may not need a dediated module for this, but I think it's still useful.

The benefit over #2549 is documentation. How do you document an implicit interface? It's not just useful for `Range#step`. `Number#step` could be referred to as the prototype (that's done in #10209), but with a dedicated module this is more explicit. And implementations can just refer to the generic documentation (which even happens by default if the doc comment is not overridden).

However, most practical relevance has the second part of the proposal. To enable sharing the implemenation of `Number#step` for other compatible types. In stdlib that would be `Char`, `Enum`, `Time` and `Time::Span` I think.

**Comment by asterite** [comment]
If the code is the same for Number, Char, Time, etc., then yes. I would start with a module with code, unrelated to Comparable, and see how that goes. It doesn't need to be super formal.
