### ISSUE TITLE
Define Method not working with Method Missing.

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#10219]
I am trying to define a method on an object that I have a method missing on.  The it looks like the defined method cannot be called.  Here is a simplified example.

https://play.crystal-lang.org/#/r/a8gv
```crystal
class Foo
  macro define_method(name)
    def {{name}}
      puts "defined name"
    end
  end
 
  macro method_missing(call)
    puts "missing {{call.name}}"
  end
end
 
Foo.define_method(bar)
foo = Foo.new
foo.bar
```
output:
```
missing bar
```

**Comment by asterite** [comment]
Macros expand where they are called. Your program is defining a method `bar` at the top-level.

**Comment by wontruefree** [comment]
Should this work then. https://play.crystal-lang.org/#/r/a8gy
I have tried a lot of combinations of this and have not figured it out.  If this is a documentation issue maybe that can be updated.

**Comment by bcardiff** [comment]
This works https://play.crystal-lang.org/#/r/a8h1

```cr
class Foo
  macro define_method(name)
    class Foo
      def {{name}}
        puts "defined name"
      end
    end
  end
 
  macro method_missing(call)
    puts "missing {{call.name}}"
  end
end
 
Foo.define_method(bar)
foo = Foo.new
foo.bar
```

**Comment by wontruefree** [comment]
I am closing this because I found the code solution.  I am not sure how to make this more clear in the docs but I will open something there.
