### ISSUE TITLE
Request: Tab key on crystal playground to use spaces instead of tabs.

### ISSUE THREAD

**Issue by Daniel-Worrall** [crystal-lang/crystal#10213]
I sometimes find myself using a local playground as an editor/test base before entering it into my main code or sharing it with other people. When I'm sharing this, either raw or on carc.in, I find tabs breaking the spacing because I have used the tab key to indent my code. It'd be very nice and clean if pressing tab smartly indented with spaces as an IDE would.

**Comment by potomak** [comment]
I would like to claim this task. I found this issue https://github.com/codemirror/codemirror5/issues/988 with some implementations of the soft tab feature on Codemirror, that should be the editor used by Playground.
