### ISSUE TITLE
Document Array#[] (range : Range) behavior with negative indices 

### ISSUE THREAD

**Issue by WhereIsX** [crystal-lang/crystal#10222]
[current Array#[] docs:](https://crystal-lang.org/api/0.35.1/Array.html#[](range:Range)-instance-method)
```
a = ["a", "b", "c", "d", "e"]
a[1..3]    # => ["b", "c", "d"]
a[4..7]    # => ["e"]
a[6..10]   # raise IndexError
a[5..10]   # => []
a[-2...-1] # => ["d"]
a[2..]     # => ["c", "d", "e"]
```

this doesn't address when the range begins with a negative number and ends at 0: 
`a[-2..0]   # => []`

it also doesn't address when a range begins with a negative number and ends in a positive number:
`a[-2..1]   # => []`

I feel that this should be documented because this wasn't obvious to me.  I'd imagine other new devs might similarly be unaware that the length of the array is first added to the beginning of a range when the range begins with a negative integer.

it also doesn't address when a descending range is given:
`a[2..0]   # => []`

When having such special features such as negative indices to get the last elements, it wouldn't be too far fetched to assume that descending ranges would return the array range in reverse, so I think it should also be documented that it doesn't do that.

-- YANA && her duckies :>

**Comment by cristian-lsdb** [comment]
Arrays have two indexes, a positive (including 0) and a negative:
```Crystal
      0    1    2    3    4 
a = ["a", "b", "c", "d", "e"]
     -5   -4   -3   -2   -1
```

Mixing positive and negative indexes is possible, each range can be written in 4 different ways:
```Crystal
a[1..3]     # => ["b", "c", "d"]
a[-4..-2]   # => ["b", "c", "d"]
a[1..-2]    # => ["b", "c", "d"]
a[-4..3]    # => ["b", "c", "d"]
```

Your two examples `a[-2..0]` and `a[-2..1]` are equivalent to the descending ranges `a[3..0]` and `a[3..1]`.

I don’t know exactly why descending ranges are not allowed but I suppose it’s to avoid confusion. `a[1..-2]` at first glance can be seen as a descending range and some may expect it to return `["b", "a", "e", "d"]` instead of `["b", "c", "d"]`.

**Comment by straight-shoota** [comment]
I suppose the documentation should be more explicit about negative indices are interpreted as counting from the last index (or rather `last_index + 1` i.e. `size`) and that descending ranges are interpreted as empty range (and thus return an empty value).

**Comment by WhereIsX** [comment]
When I originally posted this issue three days ago, I meant "descending range" as ANY Range in which the `begin > end`  I have since learned that ya'll probably mean "descending range" as in a Range whose `begin` is more to the right side (end) of the Array than its `end` 

Now that I understand what everyone else means/thinks when referring to descending ranges, I think @cristian-lsdb has a good point and it would be nice to add the following to the docs example:  
```
a[1..3]     # => ["b", "c", "d"]
a[-4..-2]   # => ["b", "c", "d"]
a[1..-2]    # => ["b", "c", "d"]
a[-4..3]    # => ["b", "c", "d"]
```

ps. I'm not trying to challenge the behavior, I'd just like to document the language in a way that as many people can understand it as possible.
