### ISSUE TITLE
Syntax parser doesn't allow \ to continue on next line, followed by comment

### ISSUE THREAD

**Issue by docelic** [crystal-lang/crystal#10225]
Could by chance this be made to work?

```cr
t = Time.new \
	# Comment here breaks it
	seconds: 2i64,
	nanoseconds: 0,
	location: Time::Location.local
```

https://carc.in/#/r/a8mk

Just as a side check, in Ruby it works, e.g.:

```rb
x = Array.new \
  # Comment
  1
```

**Comment by asterite** [comment]
Try this in Ruby:

```ruby
class Foo
  def initialize(x)
    @x = x
  end
end

x = Foo.new \
  # comment
  1
```

What do you expect to happen?

Hint: you get an error: the 1 is on its own line, not passed to Foo. The reason is that `\` is like the newline doesn't exist. It's similar to this program:

```ruby
x = Foo.new # comment
  1
```

which is not what you want.

I suggest putting the comment after the line.

**Comment by docelic** [comment]
Yes the idea would not be to have a simple comment in there, but to disable some arguments that would otherwise be passed to new.
But sure, fair point, I didn't check whether the argument got passed in Ruby or not, so closing is fine. Thanks!
