### ISSUE TITLE
NamedTuple type does not distinguish between names

### ISSUE THREAD

**Issue by benjaminradio** [crystal-lang/crystal#10238]
I'm new to Crystal and could be missing something, but it appears that overloaded methods are dropped when they have similar NamedTuples. The following code does not compile when my expectation is that it would properly dispatch an overloaded method based on the name within a NamedTuple:

```crystal
#
# Struct Test
#
struct Test
  getter a : Int32 = 0, b : Int32 = 0
  def <<(n : NamedTuple(a: Int32))
      return Test.new
  end
  def <<(n : NamedTuple(b: Int32))
      return Test.new
  end
end

o = Test.new
o <<= {b: 1}
o <<= {a: 1}
```

The error states only the last defined method exists:

```
~$ crystal run --error-trace ./src/test.cr
In src/test.cr:16:3

 16 | o <<= {a: 1}
        ^-
Error: no overload matches 'Test#<<' with type NamedTuple(a: Int32)

Overloads are:
 - Test#<<(n : NamedTuple(b: Int32))
~$
```

This error occurs regardless if the method is an operator or regular method call.

Crystal version:

```
Crystal 0.35.1 [5999ae29b] (2020-06-19)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```

I didn't find a similar issue posted and wanted to determine if this was intended behavior or a bug.

**Comment by Blacksmoke16** [comment]
I'm also surprised using `<<=` doesn't cause an error on its own given there is no method like that defined for `Test`.

**Comment by benjaminradio** [comment]
I the compiler converts `o <<= {a: 1}` to `o = o << {a: 1}`. I've confirmed that separately.

**Comment by benjaminradio** [comment]
I tried to take a look at the compiler code but it was beyond my current knowledge. It did seem to indicate that the compiler should recognize the name within a NamedTuple and the names are Symbol keys.

I also encountered an issue with variable reuse, but after further testing, that's is not what is causing this issue.
