### ISSUE TITLE
Explicit Union does not agree with Class#| inside is_a? on virtual type hierarchy

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#10244]
From https://github.com/crystal-lang/crystal/issues/8864#issuecomment-752653715:

```crystal
class Foo; end

class BarA < Foo; end
class BarB < Foo; end
class BarC < Foo; end

Union(BarB, BarC)              # => Foo
BarB | BarC                    # => Foo

x = BarA.new || BarB.new || BarC.new
typeof(x)                      # => Foo
x.is_a?(BarB) || x.is_a?(BarC) # => false
x.is_a?(BarB | BarC)           # => true
x.is_a?(Union(BarB, BarC))     # => true
x.is_a?(Foo)                   # => true

y = BarA.new
typeof(y)                      # => BarA
y.is_a?(BarB) || x.is_a?(BarC) # => false
y.is_a?(BarB | BarC)           # => false
y.is_a?(Union(BarB, BarC))     # => true
y.is_a?(Foo)                   # => true
```

The intended resolution I believe is to make `is_a?(BarB | BarC)` and `is_a?(Union(BarB, BarC))` both return false; that is, never reduce any kind of unions to their common ancestors inside an `is_a?` call, even if this means these unions refer to different types than in regular code.

Overloads work normally:

```crystal
def f(x : Union(BarB, BarC))
  puts "yes"
end

def f(x)
  puts "no"
end

def g(x : BarB | BarC)
  puts "yes"
end

def g(x)
  puts "no"
end

f(x) # => no
g(x) # => no
f(y) # => no
g(y) # => no
```

**Comment by asterite** [comment]
There's also the question of aliases:

```crystal
alias Some = BarB | BarC
```

In that case the type is resolved to the parent. I don't know how that should be handled...

**Comment by HertzDevil** [comment]
Related: #9665 (which deals with aliases instead of `Union`)

**Comment by HertzDevil** [comment]
Revisiting this I think `x.is_a?(BarB | BarC)` should always be the same as `x.is_a?(Foo)`, since that is closer to the behaviour of other unions in normal code. (Restrictions are not normal code in this sense.) It is okay for this to return `true` but `x.is_a?(BarB) || x.is_a?(BarC)` to return `false`.

The `||` form is more explicit when certain subtypes of a hierarchy are needed, and we got type filtering of 3 or more types sorted out too, so there is little reason for union nodes inside `is_a?` to behave as if each variant is evaluated separately.

Alternatively we could let `is_a?` accept multiple type arguments that don't resolve to their union, such that `x.is_a?(T, U, V)` is equivalent to `x.is_a?(T) || x.is_a?(U) || x.is_a?(V)`. This is somewhat similar to `typeof`.

**Comment by asterite** [comment]
I'll soon send a PR to make `x.is_a?(BarB | Barc)` return `true` only if the actual runtime type of `x` is `BarB` or `BarC`. That is, `BarB | BarC` won't be merged into `Foo`.

The reason I'll do this is because I think it's more correct (the current behavior is very misleading) and I also need this to work like that for the interpreter, given how I implemented multidispatch there.
