### ISSUE TITLE
Compiler does not reset free vars after partially failed overload match

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#10270]
Given

```crystal
def foo(x : T, y : String) forall T
  1
end

def foo(x : Char, y : T) forall T
  2
end

foo('a', 1) # Error: no overload matches 'f' with types Char, Int32
```

Neither overload is more specialized than the other, so overload resolution proceeds in the order they are defined. The first one fails because `y` isn't a `String`, but at this point `T = Char` is a successful match, so the second overload becomes `f(x : Char, y : Char) forall T`, and matching fails again because `y` is an `Int32`, not a `Char`.

If the two defs are swapped, or if one of them uses a different name for the free var, the snippet properly prints 2:

```crystal
def foo(x : Char, y : T) forall T
  2
end

def foo(x : T, y : String) forall T
  1
end

foo('a', 1) # => 2
```

```crystal
def foo(x : T, y : String) forall T
  1
end

def foo(x : Char, y : U) forall U
  2
end

foo('a', 1) # => 2
```

c.f. https://github.com/crystal-lang/crystal/pull/10185#issuecomment-762546171

**Comment by asterite** [comment]
Thank you for taking the time to not only explain these issues in detail, but also fix them ❤️
