### ISSUE TITLE
Tuple with type assertion prevent undefined local variable to be detected

### ISSUE THREAD

**Issue by erdnaxeli** [crystal-lang/crystal#10288]
Hi,

The following code compiles:
```Crystal
def f(t : Tuple)
  pp t
end
  
f({a : String, b : String})
```

It outputs `{nil, nil}`.

I would expect this code to not compiles and to tell me that `a` and `b` are not defined. If we remove the type assertions (so just `{a, b}`) it correctly fails and warns about the undefined variables.

I got this error while using the db module and the `as` parameter. This was intended to be a namedtuple, not a tuple, the spaces before the `:` were a mistake.

Thanks.

**Comment by straight-shoota** [comment]
`a : String` is a variable declaration and its type is `nil`. So this is technically all correct.

**Comment by erdnaxeli** [comment]
You mean a variable declaration is a statement returning `nil`? That's explain it, but it feels weird, I don't see the usage.

**Comment by asterite** [comment]
Yes, because a variable declaration can't have a value, so the value is `nil`. Every expression in Crystal has a value. When there's no meaningful value to return we use `nil`.

**Comment by erdnaxeli** [comment]
I close this issue then.
