### ISSUE TITLE
dist_linux and dist_linux32 broken on nightly

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#10291]
[dist_linux](https://app.circleci.com/pipelines/github/crystal-lang/crystal/5181/workflows/5c06d9b0-fe44-462e-808d-568336d3c558/jobs/57624) and [dist_linux32](https://app.circleci.com/pipelines/github/crystal-lang/crystal/5181/workflows/5c06d9b0-fe44-462e-808d-568336d3c558/jobs/57626) are broken on today's nightly build. 

I've restarted the build to rule out some random glitch, but it repeats for `dist_linux`. The second [dist_linux32](https://app.circleci.com/pipelines/github/crystal-lang/crystal/5181/workflows/ce93bb5e-433b-4684-b0fa-8619de4e18a3/jobs/57627) build succeeds, though.

The only diff between todays and yesterday's nightly (which suceeded) is c2b0e332d51aaa1ddd798891df1efe84808cad78. But that doesn't touch any code involved in a linux/linux32 compiler build, so it's unlikely to be responsible.

```
CRYSTAL_CONFIG_LIBRARY_PATH="" CRYSTAL_CONFIG_BUILD_COMMIT="c2b0e332d" SOURCE_DATE_EPOCH="1611498980" ./bin/crystal build --release --stats --static  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
Parse:                             00:00:00.000053917 (   0.25MB)
Semantic (top level):              00:00:00.819382532 ( 108.50MB)
Semantic (new):                    00:00:00.006466803 ( 108.50MB)
Semantic (type declarations):      00:00:00.063212082 ( 108.50MB)
Semantic (abstract def check):     00:00:00.017166818 ( 124.50MB)
Semantic (ivars initializers):     00:00:11.525761057 ( 880.43MB)
Semantic (cvars initializers):     00:00:00.009470189 ( 880.43MB)
Semantic (main):                   00:00:11.771958447 (1120.43MB)
Semantic (cleanup):                00:00:00.188430743 (1136.43MB)
Semantic (recursive struct check): 00:00:00.004038617 (1136.43MB)
Codegen (crystal):                 00:00:12.661854678 (1252.43MB)
Invalid memory access (signal 11) at address 0x7f684d605968
[0x7f68a2584f96] ???
[0x7f68a24cebeb] ???
[0x7f68a3352831] ???
make: *** [Makefile:122: .build/crystal] Error 11
```

**Comment by bcardiff** [comment]
I've seen those glitches and usually I restart the builds as well. Unfortunately I don't have any consistent repro, and was wondering if the jobs should have a retry policy to reduce the need of manual intervention.

I don't think this is blocking 0.36.

**Comment by straight-shoota** [comment]
So I've restarted the job two more times, and at least that seems to reproduce the error pretty consistently.

**Comment by bcardiff** [comment]
I ran it one more time, and it worked...

**Comment by j8r** [comment]
What's causing the issue, is it possible to be RAM related, like no more of it?

**Comment by straight-shoota** [comment]
This seems no longer to be broken. For whatever reason 🤷
