### ISSUE TITLE
Renaming HTTP::Client::Response to HTTP::Respnose

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#10305]
I dont know why `Response` is nested under `Client` and it seems like for consistency  `HTTP::Client::Response` should be moved to `HTTP::Respnose`.

**Comment by mattrberry** [comment]
What's a Respnose? 😉

**Comment by Blacksmoke16** [comment]
It's a response type specific to the client, similar to how there is `HTTP::Server::Response`, which is the response of the server.

**Comment by asterite** [comment]
These two types operate in a very different way. One lets you read a response, the other one lets you stream one for writing.

There's no way to combine both into a single type.

**Comment by Sija** [comment]
@wontruefree Why don't you use forum when you're not sure about the topic at hand? It's much better place to discuss and clear out ideas than the issue tracker...
