### ISSUE TITLE
Module Name Aliasing

### ISSUE THREAD

**Issue by jessedoyle** [crystal-lang/crystal#1030]
Hi there,

I recently encountered a bug with my code that was very subtle and the error was sending me in the wrong direction:

```crystal
module A
  module String
    def self.foo(a : String, b : Bool)
      puts a if b
    end
  end
end

A::String.foo("Hello, World!", true)
```

generates the error:

```
Error in line 9: no overload matches 'A::String::foo' with types String, Bool
Overloads are:
 - A::String::foo(a : String, b : Bool)
```

I understand that aliasing `String` as a module was probably a bad idea, and I know that I can fix the error by adding `::String` to the type restrictions of `foo`, but I believe the error generated could be much clearer.

For example if the error specified `A::String` instead of `String` as the type that was defined in the method signature, I would have easily seen where the issue lies.

See [here](http://play.crystal-lang.org/#/r/81r).

**Comment by asterite** [comment]
I'll mark this as an enhancement. The compiler should probably use full names in this case.

**Comment by jessedoyle** [comment]
Thanks @asterite!
