### ISSUE TITLE
undefined constant DispatchMode on Crystal 0.36.0

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/crystal#10315]
Trying to run the specs for Lucky's [Dexter](https://github.com/luckyframework/dexter) on Crystal 0.36.0, and getting this error:

```
❯ crystal build --error-trace log.cr
In log.cr:10:16

 10 | StubbedBackend.new
                     ^--
Error: instantiating 'StubbedBackend.class#new()'


In /usr/local/Cellar/crystal/0.36.0/src/log/backend.cr:7:34

 7 | def initialize(dispatch_mode : DispatchMode = :async)
                                    ^-----------
Error: undefined constant DispatchMode
```

I was able to re-create it with this:

```crystal
require "log"

class StubbedBackend < Log::Backend
  getter! entry : Log::Entry?

  def write(@entry) : Log::Entry
  end
end

StubbedBackend.new
```

This compiles fine with no output on 0.35.1

**Comment by straight-shoota** [comment]
Using full path `Log::DispatchMode` in `backend.cr` makes it work. So it's not a general visibility thing.

**Comment by asterite** [comment]
Reduced:

```crystal
module Moo
  enum Color
    Red
  end

  abstract class Foo
    def initialize(color : Color = :red)
    end
  end
end

class Bar < Moo::Foo
end

Bar.new
```

**Comment by bcardiff** [comment]
We were all playing with the same.

Woraround @jwoertink , monkey-patch so you can keep sending feedback regarding 0.36.0

```crystal
abstract class Log::Backend
  def initialize(dispatch_mode : Log::DispatchMode = :async)
    @dispatcher = Dispatcher.for(dispatch_mode)
  end
end
```

**Comment by bcardiff** [comment]
So, the problem is that the base class initializers' type restriction are parsed in the context of that type namespace and not the base class namespace.

TBH the issue was already present in 0.35.1, so it's not a regression.

A workaround is trivial of course, as shown in the previous monkey-patch. Let's see if a proper fix is doable though.

**Comment by asterite** [comment]
I have a fix! 🎉

**Comment by asterite** [comment]
And yes, while looking at the problematic code I thought "Hm, it's strange this didn't happen in 0.35.1". The reduced code doesn't work in 0.35.1, though.

**Comment by jwoertink** [comment]
Sweet! Thanks all! Yeah, my current workaround was just `alias DispatchMode = Log::DispatchMode` 😅
