### ISSUE TITLE
Pending spec causes `module` type to be lost

### ISSUE THREAD

**Issue by billiam105** [crystal-lang/crystal#10317]
If you have a have a type `Sub` which extends another type `Sup`, where `Sup` includes a `module` `Mod`, `Sub#is_a? Mod` inside a `pending` spec causes a compiler bug notice. If the spec is not `pending`, there is no issue.

For example:

```crystal
require "spec"
 
module Mod
end
 
class Sup
  include Mod
end
 
class Sub < Sup
end
 
describe Sub do
  it "could be a Mod" do
    Sub.new.is_a?(Mod).should be_true
  end
end
```
produces the expected `1 examples, 0 failures, 0 errors, 0 pending`. However, changing the spec:
```crystal
require "spec"
 
module Mod
end
 
class Sup
  include Mod
end
 
class Sub < Sup
end
 
describe Sub do
  pending "could be a Mod" do
    Sub.new.is_a?(Mod).should be_true
  end
end
```
results in
```text
BUG: `Mod` at eval:15:19 has no type (Exception)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from __crystal_main
  from main
  from __libc_start_main
  from _start
  from ???
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug
```
(this result is from https://carc.in/#/r/abjc)
I tried several different versions of crystal on carc.in going back to 0.20.5 as well as against the latest master (commit be5de4ac1), and each one exhibited this behavior. I also tried using `struct`s for `Sup` and `Sub`, making `Sup` `abstract`, and making `Mod` generic, and all had the same result.

**Comment by asterite** [comment]
Reduced:

```crystal
def foo(&block)
end

class Sup
end

foo do
  Sup.new.is_a?(Sup)
end
```

This is a compiler bug unrelated to `spec`.

**Comment by RespiteSage** [comment]
Another reduction:
```crystal
def foo(&block)
end

foo do
  Int64.new.is_a? Int32 # => BUG: `Int32` at eval:5:19 has no type (Exception)
end
```
Every version I've tried on carc.in (0.35.1, 0.35.0, 0.30.0, 0.25.0, 0.20.0, 0.15.0, 0.8.0) gives the same error (though the exception is slightly different in the older versions).
