### ISSUE TITLE
`String` methods should be aware of unicode whitespace

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#10312]
`String#strip` is supposed to remove leading and trailing whitespace. But apparently, it is limited to ASCII whitespace.

Unicode whitespace like `U+00A0` is left unaffected:
```cr
"\u00A0".strip # => " "
```

This is very unexpected as the method's documentation mentions no restriction on ASCII whitespace. 
Since Crystal strings are unicode, it would be very strange to not have unicode supported by this method.

Similarly affected are `String#split` and the skip leading whitespace feature of numerical conversion methods. They all are based on `Char#ascii_whitespace?`.

Ruby's `String#strip` only strips ASCII whitespace. There is a [feature request](https://bugs.ruby-lang.org/issues/7845) to support unicode whitespace which has been stalled for years for no obvious reason. Some comments mention concerns about unicode depending on locale, but this is not relevant for whitespace.

There are situations where a limitation to ASCII whitespace is required, for example for protocol parsers. So maybe there should be an option to configure the behaviour. But the default should be unicode whitespace.
And I'm not sure there needs to be an option to limit to ASCII whitespace.

**Comment by Fryguy** [comment]
On a related note, in the Ruby world, active_support's `blank?` method [supports unicode whitespace](https://guides.rubyonrails.org/active_support_core_extensions.html#blank-questionmark-and-present-questionmark). ([source code](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/core_ext/object/blank.rb#L116)).  

The performance penalty and inconsistency with Ruby core led to the creation of the [fast_blank gem](https://github.com/SamSaffron/fast_blank).  See also https://bugs.ruby-lang.org/issues/8206

**Comment by Sija** [comment]
> On a related note, in the Ruby world, active_support's `blank?` method [supports unicode whitespace](https://guides.rubyonrails.org/active_support_core_extensions.html#blank-questionmark-and-present-questionmark). ([source code](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/core_ext/object/blank.rb#L116)).  

@Fryguy and so does Crystal's.

**Comment by straight-shoota** [comment]
Yes, `blank` and `titleize` use `Char#whitespace`, thus they're aware of unicode whitespace.

**Comment by straight-shoota** [comment]
As for performance concerns, I'd expect mostly `split` to be affected because it needs to iterate the entire string. Typical applications of `strip` involve only a couple of white space characters at the front/end of a string which probably doesn't have such a huge impact compared to operating on ASCII characters only.
Of course we can have optimized implementations for ASCII-only strings.

But in general those methods are more convenience utilities. If performance *really* matters like in a parsing situation, you wouldn't use those methods anyways. Such use cases typically operate directly on an IO to avoid unnecessary intermediary allocations.
