### ISSUE TITLE
Very slow formatter in 0.36

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#10322]
After each save in Sublime Text, now i have big delay with 0.36.
```
time crystal tool format src.cr 
real    0m0,546s
```

in 0.35 it was:
```
time ~/downloads/crystal-0.35.1-1/bin/crystal tool format src.cr 
real    0m0,013s
```

Crystal installed from releases page.

Upd: seems not only formatter, every command slow:
```
time crystal --version
Crystal 0.36.0 [1e6f96aef] (2021-01-26)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu

real    0m0,551s
```

**Comment by asterite** [comment]
Is this on a Mac?

**Comment by z64** [comment]
Myself and my coworker can reproduce this on linux, on host and in docker (`crystal-0.36.0-alpine`).

Not sure what the deal is (or if this is actually related) but I noticed running `strace crystal --version` floods the terminal with `read` and `lseek` output, among other scary things, which does not happen on previous compiler versions.

**Comment by z64** [comment]
```
/ # time crystal --version
Crystal 0.36.0 [1e6f96aef] (2021-01-26)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-musl
real    0m 0.98s
user    0m 0.62s
sys     0m 0.47s
```
```
/ # CRYSTAL_LOAD_DWARF=0 time crystal --version
Crystal 0.36.0 [1e6f96aef] (2021-01-26)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-musl
real    0m 0.01s
user    0m 0.00s
sys     0m 0.01s
```

It would it appear something to do with https://github.com/crystal-lang/crystal/pull/10261

**Comment by kostya** [comment]
Ubuntu 20.04, i compile crystal in 0.36 branch no release, also slow:
```
time ./bin/crystal --version
Using compiled compiler at .build/crystal
Crystal 0.36.0 [1e6f96aef] (2021-01-26)

LLVM: 10.0.0
Default target: x86_64-pc-linux-gnu

real    0m1,147s
user    0m1,000s
sys     0m0,251s
```

looks like it compile something every time.

**Comment by asterite** [comment]
I guess loading the dwarf info as soon as the program starts is what causes the slowdown. And it's expected that as the program gets bigger, that gets slower.

@bcardiff Do you remember what's the reason for eager loading this? Why can't this work lazily?

Regardless, we should try to optimize loading this dwarf info. If it's full of `read` and `lseek` we are probably doing something wrong.

**Comment by bcardiff** [comment]
The reason to eager load the dwarf is described in #9792.

While loading the dwarf some reallocations happen. That is one source of slowness.

Workaround for 0.36.0 set `CRYSTAL_LOAD_DWARF=0` env variable, at least in the formatter command.

**Comment by bcardiff** [comment]
An alternative would be to do the eager load only if `CRYSTAL_LOAD_DWARF=1`, so it's an opt-in feature until dwarf module is further optimized.

**Comment by straight-shoota** [comment]
I would rather miss out on better stack traces for now instead of taking a significant performance impact. That would mean to return to the previous behaviour but with the option to enable better traces with `CRYSTAL_LOAD_DWARF=1`.

**Comment by jhass** [comment]
What do you think, would there be benefit to to having the dwarf loading triggered eagerly but in a separate fiber, so it only gets run once the main fiber blocks?

**Comment by bcardiff** [comment]
That could work also, but then we need to track if dwarf is loading and avoid using it or trigger another load if so. 

But also that will trigger harder to reproduce behaviour since it will be a timing issue whether you will see nice backtraces or not. I prefer a more controlled behavior. Opt-in for now, and if the load is improved we can make it opt-out.
