### ISSUE TITLE
dup and clone failing on hash

### ISSUE THREAD

**Issue by stakach** [crystal-lang/crystal#10328]
Struggling to reduce the code on this one, however we have two classes in different projects presenting the issue:

https://github.com/PlaceOS/drivers/blob/master/drivers/cisco/dna_spaces.cr#L89-L92
and
https://github.com/place-labs/clustering/pull/3

the compiler throws an error that looks like

```
In drivers/cisco/dna_spaces.cr:94:41

 94 | @description_lock.synchronize { loc.dup }
                                          ^--
Error: instantiating 'Hash(String, String)+#dup()'


In /usr/local/Cellar/crystal/0.36.0/src/hash.cr:1775:23

 1775 | hash = self.class.new
                          ^--
Error: wrong number of arguments for 'Hash(String, String)#initialize' (given 0, expected 3)
```

This is the code triggering the issue above
![image](https://user-images.githubusercontent.com/368013/106223794-34e34e00-6236-11eb-93ed-49635e3f053b.png)

I tried casting as I assume the issue is caused by generics, `Hash(String, String)+` in the error message.
As you can see though, the type should not be ambiguous

**Comment by asterite** [comment]
Do you have types inheriting from Hash? If so, they must have an argless constructor.

Dup and clone were changed to create the same type.

If that doesn't work I think we should revert that change for 0.36.1. I was against it in the first place too, so...

**Comment by stakach** [comment]
Nothing inheriting from the hash, in both cases a plain String => String class instance variable

Quite strange

**Comment by asterite** [comment]
If the compiler says `Hash(String, String)+` then there must be something inheriting `Hash`. Maybe not by your app but one of the dependencies.

**Comment by asterite** [comment]
In any case, I think we should revert that "`dup`/`clone` preserving types" nonsense.

**Comment by asterite** [comment]
I'm talking about this PR: https://github.com/crystal-lang/crystal/pull/9871

The reason I'd like to revert this is because `dup` and `clone` will not work out of the box if the subtype doesn't define an argless constructor. If someone wants `dup` and `clone` for their subtypes they should define those. What do we do with extra variables that are defined in subclasses? It's not clear.

**Comment by asterite** [comment]
This reproduces the issue:

```crystal
class Foo(K, V) < Hash(K, V)
  def initialize(@foo : Int32)
    super()
  end
end

class MyContainer
  @hash : Hash(String, String) = {"1" => "2"}

  def hash
    @hash
  end
end

Foo(String, String)

MyContainer.new.hash.dup
```

@stakach A workaround until the next release is to add this somewhere in your codebase:

```crystal
class Hash(K, V)
  def dup
    hash = Hash(K, V).new
    hash.initialize_dup(self)
    hash
  end
end
```

Something similar should be done for `clone`, the original code is in that linked PR.

**Comment by straight-shoota** [comment]
For reference, this has also been reported on the forum: https://github.com/crystal-lang/crystal/issues/10328

**Comment by straight-shoota** [comment]
I agree to revert #9871. Inheriting `Hash` should not be encouraged in general. And if you do, it shouldn't break other's code because you missed to define an argless constructor.

**Comment by bcardiff** [comment]
@stakach it's on the dependencies.

```
Searching 156 files for "< Hash"

0 matches

Searching 1872 files for "< Hash"

/private/tmp/drivers/lib/habitat/spec/habitat_spec.cr:
   18  end
   19  
   20: class Generics < Hash(String, String)
   21    Habitat.create do
   22      setting should_work : String = "with generics"

/private/tmp/drivers/lib/http-params-serializable/src/http-params-serializable/errors.cr:
   72          @path = param_path.to_a + nested_path
   73          full_path = @path
   74:         _type = type < Array ? "Array" : type < Hash ? "Hash" : type
   75  
   76          super("Parameter #{build_path(*param_path).inspect} is of type #{_type}, but has nested content at #{build_path(full_path).inspect}")
   ..
   83        def initialize(path : Tuple, type)
   84          @path = path.to_a
   85:         _type = type < Array ? "Array" : type < Hash ? "Hash" : "Object"
   86  
   87          super("Parameter #{build_path(*path).inspect} is of type #{_type}, but set explicitly with #{(build_path(*path) + '=').inspect}")

/private/tmp/drivers/lib/placeos-driver/src/placeos-driver/status.cr:
    1: class PlaceOS::Driver::Status < Hash(String, String)
    2    def set_json(key, value)
    3      key = key.to_s

/private/tmp/drivers/lib/placeos-driver/src/placeos-driver/storage.cr:
    2  
    3  # Abstraction of a redis hset
    4: abstract class PlaceOS::Driver::Storage < Hash(String, String)
    5    DEFAULT_PREFIX = "status"
    6  

5 matches across 4 files
```

And  `EdgeStorage` & `RedisStorage` redefine the constructors dropping the zero-argument overload. (funny, I wouldn't expect that you should be able to declare a abstract class that inherit a non-abstract one...)

```
/private/tmp/drivers/lib/placeos-driver/src/placeos-driver/storage/edge-storage.cr:
    2  require "../protocol"
    3  
    4: class PlaceOS::Driver::EdgeStorage < PlaceOS::Driver::Storage
    5    def initialize(@id : String, @prefix = DEFAULT_PREFIX)
    6      super()

/private/tmp/drivers/lib/placeos-driver/src/placeos-driver/storage/redis-storage.cr:
    3  
    4  # Abstraction of a redis hset
    5: class PlaceOS::Driver::RedisStorage < PlaceOS::Driver::Storage
    6    REDIS_URL = ENV["REDIS_URL"]? || "redis://localhost:6379"
    7  
```

I think #9871 was a good change in the theoretical aspect for every class. In a practical sense, I am fine leaving out the use case for inheriting hash.

**Comment by HertzDevil** [comment]
IMO we should never allow subclassing any of the stdlib containers, similar to how `String` has an `inherited` hook that raises immediately.

**Comment by vlazar** [comment]
Probably close these too then?

#9874
#9753
