### ISSUE TITLE
Add crystal 0.36 to https://dist.crystal-lang.org/rpm/

### ISSUE THREAD

**Issue by fdr** [crystal-lang/crystal#10336]
It still provides 0.35.1-1.

**Comment by straight-shoota** [comment]
The repository at dist.crystal-lang.org is not supported anymore. New releases are available at bintray. See the [announcement blog post](https://crystal-lang.org/2020/08/24/announcing-new-apt-and-rpm-repositories.html).

**Comment by fdr** [comment]
Ah, thanks for the heads up.
