### ISSUE TITLE
llvm_ext.cc:355:17: error: call to non-static member function without an object argument (RISC-V; Clang 12)

### ISSUE THREAD

**Issue by advancedwebdeveloper** [crystal-lang/crystal#10342]
Hello.
Here is what I got:

> $ make CFLAGS=' -I/usr/include/riscv64-linux-gnu ' CXXFLAGS=' -I/usr/include/riscv64-linux-gnu ' CC=clang CXX=clang++ 
> Using /home/ivan/llvm_minsizerel/bin/llvm-config [version=12.0.0git]
> clang++ -c -I/usr/include/riscv64-linux-gnu  -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc -I/home/ivan/llvm_minsizerel/include -std=c++14   -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
> src/llvm/ext/llvm_ext.cc:355:17: error: call to non-static member function without an object argument
>       DebugLoc::get(Line, Col, Scope ? unwrap<MDNode>(Scope) : nullptr,
>       ~~~~~~~~~~^~~
> 1 error generated.
> make: *** [Makefile:125: src/llvm/ext/llvm_ext.o] Error 1
> 
.
I am using 

> $ clang --version
> clang version 12.0.0 (https://github.com/llvm/llvm-project 7af6a134508cd1c7f75c6e3441ce436f220f30a4)
> Target: riscv64-unknown-linux-gnu
> Thread model: posix

on

> $ lscpu
> Architecture:        riscv64
> Byte Order:          Little Endian
> CPU(s):              4
> On-line CPU(s) list: 0-3
> Thread(s) per core:  1
> Core(s) per socket:  1
> Socket(s):           4
> L1i cache:           64 KiB
> 

> $ cat /proc/cpuinfo
> processor	: 0
> hart		: 1
> isa		: rv64imafdc
> mmu		: sv39
> uarch		: sifive,rocket0

> $ uname -a
> Linux test-gdams-debian10-riscv64-1.adoptopenjdk.net 5.0.0-rc1-56210-g0a657e0d72f0 #1 SMP Fri May 15 18:05:26 EDT 2020 riscv64 GNU/Linux
> $ cat /etc/*release*
> PRETTY_NAME="Debian GNU/Linux bullseye/sid"
> NAME="Debian GNU/Linux"

**Comment by straight-shoota** [comment]
Unfortunately, there is currently no support for RISC-V architecture.

Supported platforms can be found [on the Platform Support page](https://github.com/crystal-lang/crystal/wiki/Platform-Support).

AFAIK LLVM has only recently added full support for RISC-V, so now this should at least be possible, if someone want's to work on that. It's not a high priority, there's more demand for improving ARM support.
And I don't think anyone in the core team has even access to RISC-V hardware. Community contributions are welcome, though.

**Comment by straight-shoota** [comment]
Closing this issue. If somebody want's to add RISC-V support, contributions are welcome. But we don't need to keep this issue open for that.
