### ISSUE TITLE
HTTP::WebSocket::Protocol missing local_address and remote_address method

### ISSUE THREAD

**Issue by 636f7374** [crystal-lang/crystal#10349]
# Summary

* HTTP::WebSocket::Protocol miss local_address and remote_address method.
* When using it as wrapper, local_address and remote_address cannot be accessed.

## Example

```text
#<__::Client:0x1122a87e0 
    @wrapped=#<__::Plugin::WebSocket::Stream:0x1122db6c0
      @wrapped=#<HTTP::WebSocket::Protocol:0x11005a7c0 
        @io=#<OpenSSL::SSL::Socket::Client:0x1108eac00 
          @io=#<TCPSocket:fd 31>>
```

## Solution

```crystal
class HTTP::WebSocket::Protocol
  def local_address : ::Socket::Address?
    _io = @io
    _io.responds_to?(:local_address) ? _io.local_address : nil
  end

  def remote_address : ::Socket::Address?
    _io = @io
    _io.responds_to?(:remote_address) ? _io.remote_address : nil
  end
end
```

**Comment by 636f7374** [comment]
# Finally

* If you encounter this problem, you can follow the solution above.

**Comment by j8r** [comment]
If you use [HTTP::WebSocketHandler](https://crystal-lang.org/api/master/HTTP/WebSocketHandler.html), you can get them with [HTTP::Server::Context#request](https://crystal-lang.org/api/master/HTTP/Server/Context.html#request:Request-instance-method) (see https://crystal-lang.org/api/master/HTTP/WebSocketHandler.html#new(&proc:WebSocket,Server::Context-%3E)-class-method).

**Comment by 636f7374** [comment]
@j8r Okay, but when you use it as an IO wrapper, when you don’t need a complicated `HTTP::WebSocketHandler`, You have to do this.

**Comment by j8r** [comment]
What's your use case for as an "IO wrapper"? `HTTP::WebSocketHandler` is not very complicated, and you'll have to replicate a similar logic if you don't use it. You may mean more the `HTTP::Server` overhead.

**Comment by j8r** [comment]
What's your use case for the  "IO wrapper"? `HTTP::WebSocketHandler` is not very complicated, and you'll have to replicate a similar logic if you don't use it. You may mean more the `HTTP::Server` overhead.

**Comment by 636f7374** [comment]
@j8r My use case is SOCKS5, I.e.: `SOCKS5(WebSocket(TLS(TCP)))`, and I use it as `IO.copy`.

**Comment by j8r** [comment]
At a first glance looking at your code, you already have `local_address` and `remote_address` with the returned `Socket`, when the connection is accepted, before the WebSocket logic.

It should be possible to wrap all of this in a way to avoid monkey-patching the stdlib.

Note: in your code, you can use the [delegate macro](https://crystal-lang.org/api/master/Object.html#delegate(*methods,toobject)-macro).

**Comment by 636f7374** [comment]
@j8r Okay, thanks for your suggestion. :)
