### ISSUE TITLE
[BUG] compilator accepts any methods for x after `until x = 1 || nil`

### ISSUE THREAD

**Issue by I3oris** [crystal-lang/crystal#10345]
Hello,
I've got an error since the version 0.36.0, the program badly compile and give an exception at runtime.

For this bug append, we need a recursive function (`foo`) returning a type depending of itself inside a `if`, then this function must be called inside a `until x=foo`, so after that, the compilator gives no type to `x`, and accepts any methods for `x`.
```crystal
def foo(n = 3)

  return 42 if n == 0

  if x = foo(n-1) # always true
    return 42
  end
end

puts "This is a runtime error:"

until x = foo
end

x.this.compile.well!
  .but.fail.at.runtime!
```

### output:
```
This is a runtime error:
Unhandled exception: can't execute `x.this` at /home/rwby/Desktop/bug-recur.cr:15:1: `x` has no type (Exception)
  from bug-recur.cr:15:1 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:110:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:96:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:119:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```

NOTE: the program even fails when a valid method is call on x.

### crystal -v:
```
Crystal 0.36.0 [1e6f96aef] (2021-01-26)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by oprypin** [comment]
I have nothing to add, just... wow.

But I confirm that this bug report is correct and indeed this is a runtime error.

**Comment by j8r** [comment]
I put the above code in a `error.cr` file, then created this file for bisecting:
```sh
#!/bin/sh

make clean
make
./bin/crystal build error.cr || exit 0
exit 1
```
The result is this commit: https://github.com/crystal-lang/crystal/commit/17fc2904c01aa780efbd4a70ffc6f81021f15e93.

**Comment by asterite** [comment]
Reduced:

```crystal
until x = 1 || nil
end

x.this # can't execute `x.this` at ...
```

And this gives a crash:

```crystal
until x = 1 || nil
end

x # Program received and didn't handle signal ILL (4)
```

Also similar, because `until exp` is transformed into `while !exp`:

```crystal
while !(x = 1 || nil)
end

x
```

**Comment by asterite** [comment]
This is most probably related to this change:

https://github.com/crystal-lang/crystal/blob/33c97d419c88b4c6595786597f0ed04c7973b283/src/compiler/crystal/semantic/filters.cr#L322-L343

@HertzDevil Do you know why would that break in this case? I just tried reverting that (using `TypeFilters.and(...)` like it was originally) and that seems to fix the issue... though I didn't run the full spec.

If that change is making something work better, it's probably to revert it but at least keep correct code working.

**Comment by I3oris** [comment]
Happy to see how quickly you handle the problem, realy good job!

**Comment by j8r** [comment]
The fix should definitely land in 0.36.1 (in my opinion).

**Comment by asterite** [comment]
Unless @HertzDevil finds a solution to this I think we'll have to revert #10147 or go with this patch, because I don't think I'll have time to look into these in the next two days. Maybe it's something simple to fix, I don't know. I should have asked when I reviewed that PR, it was the only bit that I didn't fully understand, sorry.

```diff
diff --git a/spec/compiler/semantic/if_spec.cr b/spec/compiler/semantic/if_spec.cr
index ecaff295d..1f5ce67c8 100644
--- a/spec/compiler/semantic/if_spec.cr
+++ b/spec/compiler/semantic/if_spec.cr
@@ -329,7 +329,7 @@ describe "Semantic: if" do
       )) { int32 }
   end
 
-  it "restricts || else in sub || (left)" do
+  pending "restricts || else in sub || (left)" do
     assert_type(%(
       def foo
         a = 1 || nil
@@ -361,7 +361,7 @@ describe "Semantic: if" do
       )) { int32 }
   end
 
-  it "restricts && else in sub && (left)" do
+  pending "restricts && else in sub && (left)" do
     assert_type(%(
       def foo
         a = 1 || nil
@@ -377,7 +377,7 @@ describe "Semantic: if" do
       )) { int32 }
   end
 
-  it "restricts || of more than 2 clauses (#8864)" do
+  pending "restricts || of more than 2 clauses (#8864)" do
     assert_type(%(
       def foo
         a = 1 || 2.0 || 'c' || ""
diff --git a/spec/compiler/semantic/while_spec.cr b/spec/compiler/semantic/while_spec.cr
index 82d4e95a3..388f44240 100644
--- a/spec/compiler/semantic/while_spec.cr
+++ b/spec/compiler/semantic/while_spec.cr
@@ -226,4 +226,13 @@ describe "Semantic: while" do
       foo
       )) { nilable int32 }
   end
+
+  it "types !(x = a) (#10345)" do
+    assert_type(%(
+      a = 1 || nil
+      while !(x = a)
+      end
+      x
+      )) { int32 }
+  end
 end
diff --git a/src/compiler/crystal/semantic/main_visitor.cr b/src/compiler/crystal/semantic/main_visitor.cr
index e9dbd442d..b85709eb8 100644
--- a/src/compiler/crystal/semantic/main_visitor.cr
+++ b/src/compiler/crystal/semantic/main_visitor.cr
@@ -813,7 +813,7 @@ module Crystal
       check_exception_handler_vars var_name, value
 
       if needs_type_filters?
-        @type_filters = TypeFilters.assign_var(value_type_filters, target)
+        @type_filters = TypeFilters.and(TypeFilters.truthy(target), value_type_filters)
       end
 
       if target.special_var?
```

**Comment by asterite** [comment]
Nevermind, I think I found it.

**Comment by asterite** [comment]
Actually, I didn't find it. I think it has to do with `MainVisitor#get_while_cond_assign_target` and all the logic surrounding that (it's not much).

What's worse, I found some code that breaks in 0.35.1 and in 0.36.0:

```crystal
a = true ? 1 : nil
while (true ? (b = 1) : false; x = a)
  a = nil
  b = "hello"
end
p! typeof(b), b
```

**Comment by asterite** [comment]
I'll send a fix just for this. I don't think the other case I found is a regression so that could be considered for after 0.36.1
