### ISSUE TITLE
Abstract class error even after defining method

### ISSUE THREAD

**Issue by ujjwalguptaofficial** [crystal-lang/crystal#10344]
Compiler throwing error for implementing abstract method in child class but i am already defining it. This happened after upgrading to v -0.36.0, earlier version was working fine and had no issue.

![Screenshot from 2021-01-31 09-10-11](https://user-images.githubusercontent.com/10938615/106373905-29ae3080-63a4-11eb-8714-11c8abdb744c.png)

You can check the source code here - https://github.com/ujjwalguptaofficial/shivneri/blob/d95987aedee823d8be7440d504c0dedfda2f4d87/tests/general/src/guards/user_validator.cr#L14

**Comment by Blacksmoke16** [comment]
This is expected.  `def check(value : String, user)` is _NOT_ the same thing as `def check(*args)`.  you'd want to update your abstract def to be more specific, or just remove it.

**Comment by ujjwalguptaofficial** [comment]
Ok i understand the changes in new version, but is there anyway to achieve what i was doing earlier ? 

To make things clear - The abstract function can accept any arguments (different datatypes, different no of arguments) ? 

e.g - 

```
abstract class A{
   def method(*any){

   }
}

class B < A {
    def method(A,b,c ){
    
   }
}
```
So compiler doesn't check for method arguments.

**Comment by Blacksmoke16** [comment]
@ujjwalguptaofficial The easiest solution here is to just not have that as an abstract def if it's not a concrete interface.  I.e. if the API for that method is different for each child, there isn't really a way to represent that via an `abstract def`.  The compiler would still error if that method does not exist, or the user tries to interact with it in a way that isn't supported, i.e. invalid argument type.

**Comment by ujjwalguptaofficial** [comment]
fair point but it restricts my requirement.  I want to force my user to implement this method always  as this is for a framework - framework doesn't have any idea what arguments user want to accept for that method. 

If this is something not supported right now, i will request to implement this can be breaking deal for many people.

Pulling @asterite for more help.

**Comment by asterite** [comment]
What does it mean to force your users to implement that method? What method if it accepts an arbitrary number of arguments?

I agree with the solution proposed by @Blacksmoke16, don't use an abstract method at all.

I'm also not the one to convince abstract methods about, I would happily remove them from the language :-)

**Comment by asterite** [comment]
Also you can try making A be a generic type with a splat and then check use those type arguments.

I think the best way to help us would be to describe your use case and what you are trying to do.

**Comment by straight-shoota** [comment]
I don't understand the use case. The whole point of abstract methods is to define a concrete interface without the implementation. If you strip arguments from the interface and make them interchangeable, the point is gone.

**Comment by ujjwalguptaofficial** [comment]
Sorry to take this in abstract terminology, but its more related to dependency injection in methods.

So by using abstract method ,i was forcing user to implement this method. But in that method let's say user want to inject some dependency since the method is lifecycle of a component so user don't call it but framework does.

By using splat , i was able to inject dependency in previous version but can't do now. 

Here is how code will look like - 

```
class Guard
   abstract def check(*args)
end

class UserValidator < Guard     

    @[Inject("injection ok in guard")]
    def check(value : String) 
       return text_result("okkk")
    end

end
```
Hope this explains better.  Let me know how can i achieve my requirement.

**Comment by Blacksmoke16** [comment]
@ujjwalguptaofficial I think this approach is slightly flawed.  Dependency Injection normally is used when a type depends on another type (service), which could have its own service dependencies and so on.  However, in this case there `UserValidator` doesn't have any "dependencies" per say, but an argument that is entirely dependent on the concrete implementation.  This is not something "interfaces" or abstract methods are intended to solve; but you do have some options.

1. Just don't make `check` an abstract method.  The crystal compiler would still error if when the framework tries to call a method that either the user didn't define, or does not support the expected arguments.

2. Define an actual contract between the `Guard` type and its implementations, e.g.

```cr
abstract struct Context; end

class Guard
  abstract def check(context : Context)
end

class UserValidator < Guard
  def check(context : Context)
    context.value == "foo"
  end
end
```

This way you have an actual contract between the two types.  The user should subclass the `Context` type to customize it based on the validator it'll be used in, which the framework could know about and instantiate/call the method with.

3. Switch to using constructor injection for the dependencies, and have a more concrete `abstract def check(value : String)` where `value` represents that value that should be validated, which would be common to all guard implementations.

4. Prob some other options, depending on exact use case

**Comment by ujjwalguptaofficial** [comment]
thanks @Blacksmoke16 - that makes sense. I was seeing it as more of a feature to user but abstracting it is a bad idea for sure. I will remove injection from abstract method.

Thanks for your help.
