### ISSUE TITLE
Introduce ENV.accessed

### ISSUE THREAD

**Issue by xxkb** [crystal-lang/crystal#10357]
[Until recently](https://github.com/spider-gazelle/secrets-env/pull/5) a useful piece of extended behaviour for the `ENV` module was to add static resolution or accessed keys. This depended on overriding the `[]` and `[]?` methods with macros. Unfortunately as of 0.36.1 this approach is no longer possible due to [usage of `ENV.[]?` in `kernal.cr`](https://github.com/crystal-lang/crystal/blob/63a3c51ebf97a7c461fae6c122fa53619ce96465/src/kernel.cr#L548).

There is one path that exists to re-enable this: add this functionality to the std lib implementation, allowing this macro definition prior to usage in prelude.

Is this something widely usable and inline with what should exist there? Happy to submit a PR, but opening this thread for discussion before spending time on it.

**Comment by straight-shoota** [comment]
Could you please explain the purpose? I don't understand what this is about.

**Comment by xxkb** [comment]
Sorry, poor description on my part. Use case:

```crystal
# Somewhere within a program
ENV.accessed  # => ["FOO", "BAR"]

# ...

# Elsewhere, likely executed at some point in the future.
configurable_item = ENV["FOO"]?
another_item = ENV["BAR"]
```

Runtime tracking of this is trivial to overload. For lookups taking place via a `StringLiteral` rather than an expression it's possible to provide this information _prior_ to the lookup taking place. Implementation of this requires `ENV.[]` and `ENV.[]?` to exist as macros rather than methods. 

Previously this was possible by reopening the `ENV` module, however this is no longer the case due to the [`ENV["CRYSTAL_LOAD_DWARF"]?` access in `kernal.cr`](https://github.com/crystal-lang/crystal/blob/63a3c51ebf97a7c461fae6c122fa53619ce96465/src/kernel.cr#L548) and the compiler enforcing that macro's must be defined prior to usage.

It's worth clarifying that there is no regression, std lib bug or incorrect compiler behaviour; purely a fragile hack which is no longer possible. Implementation of a non-hacky approach _is_ possible by implementation directly in `ENV`, if this is generally useful.

**Comment by asterite** [comment]
But why do you need to know which env vars are accessed with a string literal?

**Comment by xxkb** [comment]
For exposing applicable env vars in docs, CLI output and other bits of UI. Namely this is something that a base application / lib can use, where reads other program components may not be known.

**Comment by asterite** [comment]
Okay, but if you have this:

```crystal
x = ENV["foo"]
```

if someone replaces that with:

```crystal
s = "foo"
x = ENV[s]
```

then the tool won't detect it, right?

I guess a further question is: why is all of this is needed in UI and CLI output? I think we are all missing how an application can use this (or if you are already using it, show an example.)

**Comment by xxkb** [comment]
That's correct. It possible to append to this for anything that cannot be resolved until later ([as implemented here](https://github.com/spider-gazelle/secrets-env/blob/bb4c7d34584bb81b04e41103cb1bb1bc82a5580e/src/secrets-env.cr)), which is useful to see what _has_ been used. The static resolution captures most usage for configuration items read from the environment and is useful for indicating what _will_ be read. [Example in use](https://github.com/PlaceOS/core/blob/2f6c0f612050c108f865cb8e63a2122db204b8ea/src/core-app.cr#L28-L31).

**Comment by asterite** [comment]
Sorry, but redefining a standard library method with a macro is discouraged. Why? Exactly because it's unreliable and it might break.

Also, it seems the implementation relies on `ENV.fetch`. That means that those values aren't tracked... so I fail to see the point of all of this, sorry.

**Comment by bcardiff** [comment]
I agree with @asterite, but other than that, in general, if changing how things are done in the std-lib is enough to allow some other stories I am happy to do so. But they are as-is solution without hard guarantee. In this case, if making the call in a method instead of in the main program is enough we could do that.

But is only a partial solution. It's likely that any shard will use ENV directly as std-lib is doing right now.

**Comment by xxkb** [comment]
Good points all round. The intent was to replace those methods with macros, but due to the number of edge cases this would miss, completely agree that it's likely not std lib material. Thanks for the solid reasoning and discussion as always!
