### ISSUE TITLE
Invalid memory access in test_alpine

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#10366]
The `test_alpine` job is broken on master. Example of a broken build: https://github.com/crystal-lang/crystal/runs/1818349096
The earliest broken nightly build is 33c97d4. So it would seem that the relevant change was introduced between that and dc0a32f. However, PR builds before that already show the same error, for example in 77f7f029d0a44078eb3e90aedc447ca85b75966f
But the following nightly was okay, so the error doesn't reproduce consistently. In CI it appears always very early on in compiler specs after the first couple of examples. But locally I've seen it occur later on after a few dozend examples.

**Comment by bcardiff** [comment]
You mean locally as in local docker or local alpine?

I think it's started to fail more often with the update to alpine:3.13. But it doesn't make much sense either.

We could try to run alpine test with verbose for a while to see if it's always in the same spec.

**Comment by straight-shoota** [comment]
I ran compiler_spec locally in the alpine build container. And it reproduced similar, but not exactly the same spec.

As far as I can see, in CI it always breaks in the third spec or not at all. So verbose output wouldn't be necessary to track that.

**Comment by bcardiff** [comment]
The alpine images based on 3.13 have some issues. The maintenance_release is unable to succeed and also the test_alpine.

I've verified that locally, it fails in the `make crystal compiler_spec` as in the CI.

So for now I am reverting the alpine images to 3.12 as published at https://github.com/crystal-lang/distribution-scripts/commit/80c83b203e1ee2fd54e41398160a67c6a06d34e1 . But I am leaving the 3.13 alpine images just in case

The related docker images are:

```
* crystallang/crystal:0.36.1-alpine = crystallang/crystal:0.36.1-3.12-alpine
* crystallang/crystal:0.36.1-alpine-build = crystallang/crystal:0.36.1-3.12-alpine-build
* crystallang/crystal:0.36.1-3.13-alpine-build
* crystallang/crystal:0.36.1-3.13-alpine
```

Ref from https://github.com/crystal-lang/distribution-scripts/pull/83:

> [..] After https://github.com/crystal-lang/distribution-scripts/pull/79 the crystal binaries end up with some shared libraries linked and the maintenance_release complains https://app.circleci.com/pipelines/github/crystal-lang/crystal/5427/workflows/8f62a04e-4e79-4633-8952-77e7c777dc00 .
