### ISSUE TITLE
Can default instance variable to instance getter result when using <JSON/YAML>::Serializable

### ISSUE THREAD

**Issue by RespiteSage** [crystal-lang/crystal#10376]
# Explanation

Normally, it's impossible to default an instance variable to the result of an instance getter (without using the block version of the macro):

```crystal
class A
  getter thing : String = "B"
  
  @other : String? = thing # => Error: undefined local variable or method 'thing' for A.class
end

a = A.new
```

However, you actually can if you meet these specific requirements:
* Your class includes `JSON::Serializable` or `YAML::Serializable`
* The name of your getter is the same as an instance variable of `Class`
* You instantiate the instance using `Klass.from_<json/yaml>`
* The defaulted instance variable is nilable

For example,
```crystal
require "yaml"

class A
  include YAML::Serializable
  
  getter name : String = "B"
  
  @other : String? = name
  
  def initialize
  end
end

a = A.from_yaml("---\nname: B")

puts a.inspect # => #<A:<hash> @name="B", @other="B">

a_prime = A.new

puts a_prime.inspect # => #<A:<hash> @name="B", @other="A">
```
[run](https://carc.in/#/r/adtd)
[json version](https://carc.in/#/r/adtf)

# Further Evidence/Cases

You can see above that using a different constructor than `A.from_yaml` leads to `@other` being set to the result of `A.class#name` instead of `A#name`.

Obviously, `A.from_yaml` wouldn't work at all without `YAML::Serializable`, so that proves the first point above.

It also doesn't work if the name of your getter isn't an instance variable of `Class`:
```crystal
require "yaml"

class A
  include YAML::Serializable
  
  getter thing : String = "B"
  
  @other : String? = thing # => Error: undefined local variable or method 'thing' for A.class
  
  def initialize
  end
end

a = A.from_yaml("---\nthing: B")
```
[run](https://carc.in/#/r/adto)

It also doesn't work when the defaulted instance variable is non-nilable:
```crystal
require "yaml"

class A
  include YAML::Serializable
  
  getter name : String
  
  @other : String = name
end

a = A.from_yaml("---\nname: B")

puts a.inspect # => #<A:<hash> @name="B", @other="A">
```
[run](https://carc.in/#/r/adtk)

It also works if you re-open `Class` to add the method:
```crystal
require "yaml"

class Class
  def thing
    "C"
  end
end

class A
  include YAML::Serializable
  
  getter thing : String = "B"
  
  @other : String? = thing
  
  def initialize
  end
end

a = A.from_yaml("---\nthing: B")

puts a.inspect # => #<A:<hash> @thing="B", @other="B">
```
[run](https://carc.in/#/r/adtt)

# Desired Solution

I don't care strongly about the exact solution, except that it should be consistent between this exact case and other similar cases.

**Comment by straight-shoota** [comment]
> it's impossible to default an instance variable to the result of an instance getter

That's incorrect. You can assign the return value of any method to an instance variable. But that's only accessible from instance scope and the type declaration is evaluated in type scope.

It totally works in `initialize`:

```cr
class Foo
  getter foo = "foo"
  @other : String

  def initialize
    @other = foo
  end
end

p! Foo.new # => #<Foo:0x7f73d140de80 @other="foo", @foo="foo">
```

I don't follow what this has to do with `Serializable`. There is no apparent connection.

**Comment by bcardiff** [comment]
As @straight-shoota mention, the ivar initializers are interpreted as metaclass level: self is the type itself and not the instance that is created.

```
class A  
  getter name : String = "B"  
  @other : String? = name # <- this name is A.name which is "A"
end
```

The issue with Serialize module, is that it iterates de ivar initializers, grab the expression in the right hand side and use it in the body of the generated initialize method. That is why it seems to work. It compiles becase `name` is both an instance and a class method in the above example.

**Comment by kostya** [comment]
i think after_initialize, hook was added for that case: https://github.com/crystal-lang/crystal/blob/master/spec/std/json/serializable_spec.cr#L330
