### ISSUE TITLE
Memory leak in Log::IOBackend with Crystal 0.36

### ISSUE THREAD

**Issue by mamantoha** [crystal-lang/crystal#10373]
Hello. I have an issue with memory growth after updating to Crystal 0.36.1.

Extracted code:

```crystal
require "log"

loop do
  Log::IOBackend.new
end
```

Causes unbound memory growth on Crystal 0.36. This was not the case in earlier versions of Crystal and works just fine memory-wise.

Minimal code to reproduce:

```crystal
require "log"

loop do
  Log::AsyncDispatcher.new
end
```

```
Unhandled exception: Cannot allocate new fiber stack: Cannot allocate memory (RuntimeError)
```

**Comment by bcardiff** [comment]
The cause is that the async dispatcher spawn a fiber to actually write the logs.
I guess the channel should be closed on finalize of the AsyncDispatcher. That should exit the loop in write_logs and free the fiber.

**Comment by jwoertink** [comment]
Are there any "hacks" for this in the meantime? Something we can pass along to apps going in to production with this to mitigate until the next release...

**Comment by asterite** [comment]
Why are log backends created all the time? I thought a log backend would be created at the start of an app.

**Comment by mamantoha** [comment]
I've been waiting for this question 😄 , but it doesn't negate the presence of a bug.

**Comment by mamantoha** [comment]
@jwoertink as a "hack" you can try `DispatchMode::Sync` so far.

```
class Log::IOBackend < Log::Backend
  def initialize(@io = STDOUT, *, @formatter : Formatter = ShortFormat, dispatcher : Dispatcher::Spec = DispatchMode::Sync)
    super(dispatcher)
  end
end
```

**Comment by asterite** [comment]
True. But I asked this question because of @jwoertink question. If log backends aren't created all the time then this bug is effectively a no-bug because the memory will be "leaked" in any case because the backend will be alive in memory... unless you create backends non-stop for no reason 🤷

**Comment by bcardiff** [comment]
I interpreted the loop as a way to exhibit the leak. The Log.setup creates a single backend. And if deprecated initializer of LogHandler is called many times, that could also be a source of leak. But that should not happen a lot as @asterite points out.

**Comment by Sija** [comment]
@asterite Fiber should exit along with its parent object, if that isn't happening - it's a bug to me.

**Comment by straight-shoota** [comment]
Sure, it's a bug. But the practical effect should be negligent because it's unlikely to cause any issues in a real world use case. Unless @jwoertink has an application that experiences this issue and would need a workaround.
