### ISSUE TITLE
Multithreading performance issues

### ISSUE THREAD

**Issue by wolfgang371** [crystal-lang/crystal#10372]
Yesterday I tried to write a simple (bulk) image analysis program and ran into a strange behaviour. I tried to somehow strip it down into the following code. The method `#x` does the work (ok, it probably could still be cut down a little bit more; nevertheless it calculates some gibberish now).

First thing I learned is that using dynamic object creation/deletion a lot things can get real slow (e.g. running the below program without arguments) - ok, this is probably unavoidable, but the root cause seems to be a coarse-grained GC synchronization, since the number of utilized cores drops substantially. Feels like a problem somehow.

Second thing I learned is that the `--release` version can even get _slower_ than the non-release version - this does not feel right.

```crystal
# crystal 0.36.1 on ubuntu 18.04 with Ryzen 7 2700 eight-core processor × 16

# four ways to run (all yield the same result); timing from "CPU"/"elapsed"
# crystal build -Dpreview_mt src/parallel.cr ; CRYSTAL_WORKERS=16 time ./parallel
#    -> 22s (using roughly 6 cores)
# crystal build -Dpreview_mt src/parallel.cr --release ; CRYSTAL_WORKERS=16 time ./parallel
#    -> 33s (using roughly 3.5 cores)
# crystal build -Dpreview_mt src/parallel.cr ; CRYSTAL_WORKERS=16 time ./parallel fast
#    -> 5s (using all 16 cores),
# crystal build -Dpreview_mt src/parallel.cr --release ; CRYSTAL_WORKERS=16 time ./parallel fast
#    -> 0.4s (using all 16 cores)

CORES = 16
class X
    def initialize
        @channel = Channel(Nil).new
        @mutex = Mutex.new(Mutex::Protection::Reentrant)
        @res = 0
        # dispatch
        CORES.times do |i|
            spawn(name: "#{i}") {x}
        end
        # collect
        CORES.times do
            @channel.receive
        end
        p @res
    end
    def rms(input = [] of Int32) : Float64
        res = 0.0
        input.each {|el| res += el**2}
        res ** 0.5
    end
    def x
        @mutex.synchronize {p [Fiber.current.name, "start"]}
        my_res = 0
        s = [1,2,3]
        xx = [0,0,0]
        10_000_000.times do
            if ARGV.size == 0
                # the "slow" variant, where we probably use the GC a lot
                s = [1,2,3]
                xx = s.map {|el| el+2}
            else
                # the fast variant
                s.size.times {|i| xx[i] = s[i]+2}
            end
            delta = rms(xx)
            my_res += delta.to_i32
        end
        @mutex.synchronize {p [Fiber.current.name, "end"]; @res += my_res}
        @channel.send(nil)
    end
end

X.new
```

**Comment by straight-shoota** [comment]
> dynamic object creation/deletion a lot things can get real slow

Well... the slow code allocates 10 million arrays. Thats *a lot* 🤷 No wonder it's pushes a high load on the GC.

**Comment by wolfgang371** [comment]
yes, I know (probably even 20 mio arrays). But that's not my point.
Point no. 1 is that `--release` can make your program _slower_.
And (minor) point no. 2 is the utilization of the available cores in case of the heavy GC usage is really bad.

**Comment by Fryguy** [comment]
@wolfgang371 If you run the same test over and over do you get consistent results across runs?

e.g. does running the following consistently give 5s?

```
# CRYSTAL_WORKERS=16 crystal build -Dpreview_mt src/parallel.cr ; time ./parallel fast
#    -> 5s (using all 16 cores)
```

**Comment by wolfgang371** [comment]
I tried to rerun and realized that the commands I gave were actually mixed up; I used a global `CRYSTAL_WORKERS=16` last time in addition that shadowed this...
old, wrong command: `CRYSTAL_WORKERS=16 crystal build -Dpreview_mt src/parallel.cr ; time ./parallel`
new, corrected command: `crystal build -Dpreview_mt src/parallel.cr ; CRYSTAL_WORKERS=16 time ./parallel`
I updated my initial post accordingly - sorry for this.

Now to your question: I'd say yes - I rerun all four scenarios five times each and noted the output:
```crystal
# four ways to run (all yield the same result); timing from "CPU"/"elapsed"
# crystal build -Dpreview_mt src/parallel.cr ; CRYSTAL_WORKERS=16 time ./parallel
#    -> 22s (using roughly 6 cores)
#   rerun 10.2.2021: 621%/21.5s, 622%/21.5s, 627%/21.4s, 626%/21.4s, 637%/21.3s
# crystal build -Dpreview_mt src/parallel.cr --release ; CRYSTAL_WORKERS=16 time ./parallel
#    -> 33s (using roughly 3.5 cores)
#   rerun 10.2.2021: 344%/33.3s, 347%/32.6s, 348%/32.7s, 348%/32.7s, 354%/32.9s
# crystal build -Dpreview_mt src/parallel.cr ; CRYSTAL_WORKERS=16 time ./parallel fast
#    -> 5s (using all 16 cores),
#   rerun 10.2.2021: 1264%/5.8s, 1191%/5.6s, 1422%/4.1s, 1298%/6.1s, 1209%/5.6s
# crystal build -Dpreview_mt src/parallel.cr --release ; CRYSTAL_WORKERS=16 time ./parallel fast
#    -> 0.4s (using all 16 cores)
#   rerun 10.2.2021: 981%/0.4s, 1202%/0.4s, 1164%/0.4s, 1195%/0.5s, 1086%/0.5s
```

**Comment by bcardiff** [comment]
It's hard to say without further experiments, but:

1. `--release` will trigger llvm optimizations that can affect a lot the binary. That could impact in performance, but is not something easy to measure. See https://github.com/plasma-umass/coz 
2. bdw-gc has a stop-the-world policy. All threads will be paused. You can tweak some settings or even disable the GC temporarily or completely. In some cases that is feasible.
3. If I read correctly: in some cases --release might run slower than without it. Slightly unexpected but it could happen. I fail to see if you are implying that this is something particularly in multithreading or in general.

---

shameless plug I've used https://github.com/manastech/benchy to run some benchmarks in the past. Maybe you would like it,.

**Comment by wolfgang371** [comment]
@bcardiff:
2. `GC.disable` doesn't work here (I tried just now), since the program quickly eats all the memory.
3. I was somehow assuming that the "performance inversion" applies to multithreading only; I just checked with a stripped-down version to one core and in this case `--release` was faster, so I feel confirmed.
Nevertheless this issue puzzles me; this example gives `--release` a -50% penalty in the heavy-GC-usage case and I have no clue why.

Thanks for your links!

**Comment by straight-shoota** [comment]
The surprising aspect is that in some multithreading contexts, the program compiled with release mode runs actually slower than the non-release build.

@caspiano Did a benchmark series with different thread counts (https://gist.github.com/caspiano/89f9eeb1cc330a50ff66f61c2bf54ced). The runtime speed increase of the release mode varies a lot:
* Single thread: 247%
* 3 threads: 112%
* 5 threads: 99%
* 8 threads: 81%
* 12 threads: 113%

Best performance is observed for the release build in single-threaded mode. The more threads are added, the worse it gets (for the release build).

This suggests that the program is just not very appropriate for multi-threaded use. Multi-threading does not make everything faster magically. It does not fit for every problem. The program should either run in single-threaded mode or it must be refactored to accommodate multi-threading.

I presume the effect that the release build is sometimes even less performant than the non-release build may be caused by optimizations being invalidated and turning into the reverse effect due to problems in the multi-threading context, such as resource contention. An involvement of the GC might be possible.

Either way, I'd see this as a problem of the program's architecture, not the compiler. The program seems to be work in a way that it doesn't run well with multi-threading.
