### ISSUE TITLE
Long calculations with fibres

### ISSUE THREAD

**Issue by pammacdotnet** [crystal-lang/crystal#10392]
Hi, 
I'm trying to use the concurrency model to perform long calculations in Crystal. Let's say I have a big computing function call "interp" that could be called in parallel by varying a specific parameter. This function usually takes several seconds to complete in modern x64 hardware. I want to be able to execute this code in parallel as many times as a I please. How would you do it? I can't seem to spawn several instances of this function and see them being called in a parallel way. 
Maybe I'm understanding the concurrent model in the wrong way and I apologise beforehand.
Thanks for your tips!

**Comment by mattrberry** [comment]
Hi Alberto. Rather than opening an issue on GitHub, this type of question would be best addressed on [gitter](https://gitter.im/crystal-lang/crystal) or [the forum](https://forum.crystal-lang.org/)

**Comment by pammacdotnet** [comment]
Done… thank you!!!
