### ISSUE TITLE
>= and <= considered as setters, allow only one arguments, unlike > and <

### ISSUE THREAD

**Issue by j8r** [crystal-lang/crystal#10397]
`>=` and `<=` ends with `=`  are considered as setters. This comes from https://github.com/crystal-lang/crystal/blob/1c8a41e0341891d8295f589fe29c97e36fa25c56/src/compiler/crystal/syntax/parser.cr#L3519, which is aimed to exclude assigns from having more than one argument.

If there are the only exceptions, they can be added to the condition to exclude them.

**Comment by HertzDevil** [comment]
IMO `<` and `>` and the rest of the binary operators should also only have exactly one ~~argument~~ parameter, and we shouldn't allow different arities just because the function call syntax is available to them.

**Comment by j8r** [comment]
It can be useful in a case where `__FILE__` and/or `__LINE__` are used, for example in a DSL for debug purposes, like:
```cr
def <(other, file = __FILE__, line = __LINE__)
  ...
end
```
There is no disadvantage to allow this. At the end, there are just regular methods like others.

**Comment by asterite** [comment]
I think restricting the language for no reason isn't good. I think we should revert all those PRs

**Comment by straight-shoota** [comment]
I agree that unnecessary restrictions should be avoided. But I think for actual setters this is good because it avoids confusion when you can define a method but not actually call it with the usual syntax.

This is also realted to #7707 which would be a bit weird if a setter accepts multiple arguments.

**Comment by j8r** [comment]
Can this ule be enough in this case? "If the name[-2] char (before `=`) is not a number/letter, it is not a setter".

The method to use will be `Char#alphanumeric?`. Then, the condition with `name != "[]="` could be removed.

**Comment by asterite** [comment]
Nah, you can do `foo.=(a, b, c)`. So why restrict it?

**Comment by straight-shoota** [comment]
That call is actually a syntax error:
```cr
foo.=(a, b, c) # Error: expecting any of these tokens: IDENT, CONST, +, -, *, /, //, %, |, &, ^, ~, !, **, <<, <, <=, ==, !=, =~, !~, >>, >, >=, <=>, ===, [], []=, []?, [, &+, &-, &*, &** (not '=')
```
We *could* probably make that compile and lift the parameter count restriction on setter methods.

But would it really help anything?

I understand the main reason for #6324 (and what caused me to open #5856) is conciseness and user-happiness.

If you define a method `def foo(a, b); end` you would expect to call it like `foo(1, 2)`. Apply the same to `foo=` and it doesn't work. Neither does the even more common setter syntax `foo = 1, 2`.
If it only worked as somewhat obscure `foo.=(1, 2)` I wouldn't expect anyone to think of using that.

A better solution is to directly produce an error when you define a setter method with more than one parameter. It just tells you that it won't work.

**Comment by asterite** [comment]
Oh, sorry, I mean `foo.bar=(a, b, c)`. That's a setter and without trying it I'm pretty sure that compiles just fine.

Whether it's useful or not is subjective. But there's no reason to forbid it.

**Comment by straight-shoota** [comment]
Nope, it triggers an unterminated parenthesized expression because parenthesis in a setter call is parsed as expressions, not as arguments. So this is equivalent to `foo.bar= (a, b, c)`.

I also tried a full example it with 0.25.1 which was the last version before #6324 was merged and it didn't work back then either.

**Comment by asterite** [comment]
Cool! So this is working like in Ruby :-)

Okay... so let's say you define a setter with multiple arguments and that compiles/parses fine. But then you can't call it. So what's the point of defining it in any case?

So the question is: why do we need to proactively forbid it if it's not causing any issues?

Note that `def foo=(a, b, c)` in Ruby is **not** a syntax error... though in Ruby you can then do `send(:foo=, 1, 2, 3)`.

I guess I don't see the point of limiting this in the parser if it's already limited on the call side, that's what I'm saying.
