### ISSUE TITLE
Alpine Linux is missing Crystal 0.36.1

### ISSUE THREAD

**Issue by marghidanu** [crystal-lang/crystal#10418]
The latest version 0.36.1 is not available in the Alpine package manager.  You can check here: https://pkgs.alpinelinux.org/packages

**Comment by asterite** [comment]
I don't think we are the ones maintaining that...

**Comment by straight-shoota** [comment]
The alpine packages are maintained at aports. Please open an issue at https://gitlab.alpinelinux.org/alpine/aports.
