### ISSUE TITLE
Add maximum size to gets() in HTTPServer

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#1043]
In here : https://github.com/manastech/crystal/blob/master/src/http/request.cr#L33

If I would send an endless stream of data (without \n) I can fill up the servers memory in no-time.

We should use `gets("\n", 4096)` or something like that.
For example:
https://github.com/ruby/ruby/blob/c8b3f1b470e343e7408ab5883f046b1056d94ccc/lib/webrick/httprequest.rb#L529

``` ruby
def read_line(io, size=4096)
  _read_data(io, :gets, LF, size)
end
```

**Comment by bararchy** [comment]
So, it seems that I totally misunderstood how the IO.gets(sep, limit) thing works, after reading the documentations here : http://ruby-doc.org/core-2.2.2/IO.html#method-i-gets It seems the "limit" is not a maximum byte size to read, as this is the case and there is no way to specify a maximum read size for "gets" maybe we should use a read_nonblock(4096) and separate the body from the headers.

What do you think ?

**Comment by asterite** [comment]
Yes, we should do something about this. We'll also need an overload for `gets` that accepts a limit

**Comment by bararchy** [comment]
@asterite Looking at a possible way to implement this, I found a Bug in ruby IO.gets :) 
https://bugs.ruby-lang.org/issues/11400

I'll the new implementation after the bug will be fixed, then I'll try to PR a gets() with a limit

**Comment by bararchy** [comment]
Just to hammer in the issue, I did some tests, right now I can crash any HTTPServer based appliance in less then 20 sec

Starting the application:
![screenshot from 2015-08-04 12-22-16](https://cloud.githubusercontent.com/assets/1631073/9057598/dd4095f0-3aa3-11e5-82ae-070455eb1ae7.png)

Running my "endless stream" application against it:
![screenshot from 2015-08-04 12-23-57](https://cloud.githubusercontent.com/assets/1631073/9057620/f6fc5e0c-3aa3-11e5-9edb-0df2b8f57d61.png)

And then, crashed
![screenshot from 2015-08-04 12-23-37](https://cloud.githubusercontent.com/assets/1631073/9057616/f1f78c10-3aa3-11e5-843b-8d6a4434ec62.png)

**Comment by asterite** [comment]
OK, now there's a way to do `gets` with a limit after https://github.com/manastech/crystal/commit/66cc451b0a0444024646f0ff43e702f862b51686

Now we need some answers:
* What limit to use for the status line?
* What limit to use for each of the headers?
* How many headers as a maximum to support? (otherwise you could end up building a huge headers list and fill the server's memory)
* What to do when the limit is reached? Raise something like `HTTP::BadRequest`?

We'll also need to support body streaming in the HTTP server, right now it consumes the whole body, so if you stream an infinite body it will also consume the server's memory (I didn't test this, but it's a guess).

**Comment by bararchy** [comment]
@asterite I know the Ruby handles gets("\n", 4096) like so:

Super pseudo code:
```
while read_data_from_users_socket(user_socket)
  does data == "\n" ? if so finish read and return data
  does data.size > 4096 ? if so finish read and return data
end
```

this meas that now the gets method can read until one of the two requirements are meet
1) reached a read size bigger then 4096 bytes
2) reached an "\n" indicator

I know that usually you wont hit the 4096 limit while reading a header (this is also the hard-coded limit for webrick)

**Comment by bararchy** [comment]
Also, I have a small web server application in Ruby which I developed, I use ```gets("\r\n\r\n", 4096)```
This way I can get the whole Header part of the request then start analyzing it, also, I can then do a loop of the body like ```while read_body < header.content_length; keep reading```

**Comment by gamebusterz** [comment]
Is this bug still present ( seems like it is) ? I'd like to work upon this , can anyone point me to the right file or give any other suggestions please ?

**Comment by bararchy** [comment]
@asterite @gamebusterz 
Is this still relevant ? if so it should be easy to fix no ?

**Comment by gamebusterz** [comment]
@bararchy I'm wondering the same. Do you have an idea about which part of the code should I be looking into for this ?

**Comment by asterite** [comment]
@bararchy Yes, still relevant, and should be easy to fix because we have `gets` with limit :-)

I'll probably tackle this before the next release.

**Comment by bararchy** [comment]
@gamebusterz => https://github.com/crystal-lang/crystal/blob/master/src/http/request.cr#L90

I guess there or something, the other thing is that it seems to read a line-by-line until line = `\n`
This is an issue too, or , test each line the header size as string to see we are not going over the maximum header size limit (can default to 4096 and be configurable)
