### ISSUE TITLE
Built-in is_a? doesn't work for implicit self.

### ISSUE THREAD

**Issue by BrucePerens** [crystal-lang/crystal#10441]
I can't think of any reason that the built-in `is_a?` *shouldn't* work for implicit `self`, I guess this is a feature request.
```crystal
class A
  def bar
    if self.is_a?(B) # This works.
      self.foo
    end
    if is_a?(B) # This does not.
      foo
    end
  end
end

class B < A
  def foo
  end
end

b = A.new
b.bar
```

**Comment by BrucePerens** [comment]
See #5612

**Comment by straight-shoota** [comment]
A reason would be that `foo` can be a call with implict receiver, but it doesn't have to. It could also be a call to a top-level method. Or just a local variable.
I think forcing an explicit receiver on both the protected call and the guard is good to explicitly highlight the dependency.

**Comment by Fryguy** [comment]
I'm not sure what the argument on `foo` has to do with `is_a?`.  In my view, it's just an example of where `foo` doesn't require an explicit receiver, but `is_a?` always does, which appears inconsistent.  From an author's POV, is_a?, respond_to?, nil? appear like normal methods, and so from a "principal of least surprise" view, they also shouldn't need explicit receivers.

**Comment by asterite** [comment]
I remember fixing this already in the past.

**Comment by asterite** [comment]
Oh, wait. It works with the self varíable. It will never work with the implicit self. I agree with @straight-shoota here.

**Comment by straight-shoota** [comment]
@Fryguy `responds_to?` requires a receiver in order to disambiguate wether `foo` means an instance method (`self.foo`) or a top-level method (`::foo`). For this use case it doesn't make sense to mix both like with a normal call.

The same doesn't apply to `is_a?` and `nil?` because the top level scope can't implement either. But for consistency between those intrinsic methods it should work the same way. Plus the argument I already mentioned.

**Comment by BrucePerens** [comment]
@straight-shoota and @asterite, I think you are saying is that this is unambiguous:
```crystal
if is_a?(B)
  self.foo
end
```
And it does actually work.

But when does the compiler know that `foo` *is* a method? Obviously you don't have to provide
`self` to `foo`, so the compiler figures this out at some point.

**Comment by straight-shoota** [comment]
@BrucePerens The compiler should be smart enough to to figure out the missing `self.`. I don't think it's strictly necessary. But IMO requiring it makes the code more explicit.

IMO the related methods `is_a?`, `responds_to?`, `nil?` should have the same receiver semantics. That is, if there's no receiver, it refers to the external scope. That probably doesn't make any sense ever for `is_a?` and `nil?`, hence they should require a receiver.

Related: #5911
