### ISSUE TITLE
Stack backtrace is confused about primitive call

### ISSUE THREAD

**Issue by BrucePerens** [crystal-lang/crystal#10449]
Given this code:
```crystal
x = -> do
  begin
    raise Exception.new
  rescue e : Exception
    e.backtrace.each do |line|
      STDERR.puts line
    end
  end
end
x.call
```
The backtrace emitted for x.call is confused:
```
foo.cr:3:5 in '->'
/usr/share/crystal/src/primitives.cr:255:3 in '__crystal_main' <- should say "call" or should print a line number from __crystal_main.
/usr/share/crystal/src/crystal/main.cr:110:5 in 'main_user_code'
/usr/share/crystal/src/crystal/main.cr:96:7 in 'main'
/usr/share/crystal/src/crystal/main.cr:119:3 in 'main'
__libc_start_main
_start
???
```
The filename and line number printed aren't in `__crystal_main`, they are the primitive stub for `Proc#call`.

**Comment by asterite** [comment]
This is a feature request. Primitive calls are always inlined by the compiler. That's why there's ko backtrace for that. The compiler isn't confused :-)

**Comment by rdp** [comment]
Since it shows up in backtraces a lot (and is a bit confusing, "what's a primitive?") maybe that section could be divided out and named primitive_proc.cr or primitive_call.cr or something similar?

**Comment by BrucePerens** [comment]
The line number has changed since the bug was filed, but really does correspond to the inline.
://github.com/crystal-lang/crystal/blob/170d737a2caeb7acbb1c520b5471109c30dda325/src/primitives.cr#L264
So when solution would be breaking out the primitives to separate files, so that one would see a filename `primitive/call.cr` instead of just `primitives.cr`. 

This is just a little consideration for the user. Crystal is darn hard to debug already due to  macro code that doesn't correspond to the program in the developer's eyes, etc. We should make it easier where we can.
