### ISSUE TITLE
compiler crash due to bad codegen in string.cr

### ISSUE THREAD

**Issue by void-witch** [crystal-lang/crystal#10459]
@hugopl discovered a compiler crash when trying to update crystal-gobject for crystal 0.36

when cloning hugopl's fork at commit https://github.com/hugopl/crystal-gobject/commit/4158b46f993fdf118a137582d90f70b618c985e2 and running the `scripts/ci.sh` script, the compiler crashes with the following output:

```
$ ./script/ci.sh 
Running crout/crout.cr
1
Hello John
Uh...
Hello
TEST
Compiling base_class_container.cr... Module validation failed: Referring to an argument in another function!
  store i32 %argc, i32* @ARGC_UNSAFE
Referring to an argument in another function!
  store i8** %argv, i8*** @ARGV_UNSAFE
 (Exception)
  from /crystal/src/string.cr:5017:14 in 'finish'
  from /crystal/src/compiler/crystal/codegen/codegen.cr:69:7 in 'codegen'
  from /crystal/src/compiler/crystal/compiler.cr:172:16 in 'compile'
  from /crystal/src/compiler/crystal/command.cr:296:3 in 'run'
  from /crystal/src/compiler/crystal.cr:11:1 in '__crystal_main'
  from /crystal/src/crystal/main.cr:110:5 in 'main'
  from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
failed.
```
platform: fedora 33 x86_64
```
$ crystal -v
Crystal 0.36.1 [c3a3c1823] (2021-02-02)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```

the bug also exists with current git head b018f288c0ac336a8297d5c575e062e6bb791902

i'm really not sure what the bug is, but i'll be running a bisect to try and find the commit that introduced it

**Comment by void-witch** [comment]
i can't get a bisect going because i can't get a working compiler build of anything earlier than 0.36.1, it fails with a type error in the gc

**Comment by straight-shoota** [comment]
Can you try to reduce a reproducing example? Best case if it would reproduce without gtk.

**Comment by void-witch** [comment]
@straight-shoota issue is in https://github.com/jhass/crystal-gobject/blob/5bc0cc7481a713b22e332d1bab80c132a819d20e/src/gtk/autorun.cr#L5 

i copied that bit over and modified the import:

```cr
#require "gobject/gtk/autorun"
require "gobject/gtk"

class Container
  getter widget : ::Gtk::Label

  def initialize
    @widget = Gtk::Label.new("Hello")
  end 
end

main_window = Gtk::Window.new(title: "Widget container", border_width: 20) 
container = Container.new
main_window.add(container.widget)
main_window.connect "destroy", &->Gtk.main_quit
main_window.show_all

fun main(argc: Int32, argv : UInt8**) : Int32
  Crystal.main do
    LibGtk.init pointerof(ARGC_UNSAFE), pointerof(ARGV_UNSAFE)

    Crystal.main_user_code(argc, argv)

    LibGtk.main
  end 
end

Signal::INT.trap do
  Gtk.main_quit
  exit
end
```
and it fails, as expected. however, changing `LibGtk.init pointerof(ARGC_UNSAFE), pointerof(ARGV_UNSAFE)` to `LibGtk.init pointerof(argc), pointerof(argv)` compiles, runs, and displays a window perfectly

i have no idea where `LibGtk.init` is defined; i can't find it with github nor grep, and i'm thinking it might be autogenerated. regardless, following minimal code triggers the compiler crash

```cr
fun main(argc: Int32, argv : UInt8**) : Int32
  Crystal.main do
    pointerof(ARGV_UNSAFE)
  end
end
```
```
❯ ./script/ci.sh 
Running crout/crout.cr
1
Hello John
Uh...
Hello
TEST
Compiling base_class_container.cr... Module validation failed: Referring to an argument in another function!
  store i8** %argv, i8*** @ARGV_UNSAFE
 (Exception)
  from /crystal/src/string.cr:5017:14 in 'finish'
  from /crystal/src/compiler/crystal/codegen/codegen.cr:69:7 in 'codegen'
  from /crystal/src/compiler/crystal/compiler.cr:172:16 in 'compile'
  from /crystal/src/compiler/crystal/command.cr:296:3 in 'run'
  from /crystal/src/compiler/crystal.cr:11:1 in '__crystal_main'
  from /crystal/src/crystal/main.cr:110:5 in 'main'
  from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
failed.
```

**Comment by void-witch** [comment]
also, the following code *also* triggers the crash:

```cr
fun main(argc: Int32, argv : UInt8**) : Int32
  Crystal.main do
    pointerof(ARGV_UNSAFE)
  end
end
```
(notice that `ARGV_UNSAFE` has changed to `ARGC_UNSAFE`)

**Comment by asterite** [comment]
Those constants are magical in the compiler, there's no pointer you can take, as far as I remember. Please don't use compiler internas. Thank you!

**Comment by void-witch** [comment]
I didn't write it but ill be sure to keep that in mind haha

would it be worth it to add a bit of a warning if someone does try to use them or take their pointer? i'm assuming not but might as well ask

**Comment by hugopl** [comment]
IMO a warning isn't needed, maybe renaming then to `_ARGV_UNSAFE`, but IMO also not needed, since the rule is:

> If there's no documentation, it's internal, so sorry if it crash.
