### ISSUE TITLE
Compiler: Array#map! fails for a different return type 

### ISSUE THREAD

**Issue by marzhaev** [crystal-lang/crystal#10457]
Compilation fails for a simple line:

``` ["a","b"].map!{ |x| 1 } ```

Basically, it persists whenever map-bang's block yield a type different from original. I tried for 0.35.1, 0.36.1 and master branch - persists.

It originates here [https://github.com/crystal-lang/crystal/blob/master/src/array.cr#L1121](url) where buffer variable is a typed pointer. Once we map over the pointer returning a different type obviously makes no computer sense.

It could be argued map! shall not alter array's type. If so, we should check block's return type and throw a meaningful message.

**Comment by straight-shoota** [comment]
> It could be argued map! shall not alter array's type. 

It's even impossible to alter the array type. Hence the return value of the block must be compatible with the generic argument type.

> we should check block's return type and throw a meaningful message.

Indeed, the error message is not very helpful. Unfortunately, it's not trivial to improve. We can't simply restrict the block return value to `T` because that would be too strict for union types and type hierarchies (you can add `Int32` to `Array(Int32 | String)` for example).

**Comment by Daniel-Worrall** [comment]
If we made the signature
```cr
def bar!(&block : T -> T)
```
we would end up with `Error: expected block to return T, not Int32`, which I'd argue is slightly better than what we have right now of
```cr
Error: instantiating 'Array(String)#map!()'


In usr/share/crystal/src/array.cr:1035:13

 1035 | @buffer.map!(size) { |e| yield e }
                ^---
Error: instantiating 'Pointer(String)#map!(Int32)'


In usr/share/crystal/src/pointer.cr:381:11

 381 | self[i] = yield self[i]
           ^
Error: no overload matches 'Pointer(String)#[]=' with types Int32, Int32

Overloads are:
 - Pointer(T)#[]=(offset, value : T)
 ```

but I feel like this should be improved in a more informative way.

Also worth noting, changing the signature like this would not impact unions or inheritance

**Comment by straight-shoota** [comment]
`def map!(&block : T -> T)` won't work because then `[1, 1.0].map! &.to_i` would be invalid: Expected type is `Int32 | Float64` but the block returns `Int32` (which is completely fine, but can't be expressed with `T`).

**Comment by straight-shoota** [comment]
#3803 would offer a way to express that the block doesn't need to return `T` exactly, but a covariant type.

**Comment by marzhaev** [comment]
Could the following work?

```
  def map!(&block : T -> T) : Array(T)
    @buffer.map!(size) { |e| yield e }
    self
  end

  def map!(&block : T -> U) : Array(U) forall U
    Array(U).new(size) { |i| yield @buffer[i] }
  end
```

I'm still getting acquainted with the compiler's source code. Can it be helped to deduce block's return time? Otherwise, we have to be explicit with return types.

**Comment by Daniel-Worrall** [comment]
No, if you wanted a new array, you would just use `Array#map`

**Comment by straight-shoota** [comment]
It can't work because a) overloads cannot be based on blocks and b) the purpose of `map!` is explicitly *not* to allocate a new array.

**Comment by straight-shoota** [comment]
@asterite IMO this qualifies as a bug because the error message points to a location in stdlib while the error actually happens in user code.

**Comment by straight-shoota** [comment]
@marzhaev If you want to play a bit, this would be a start:

```cr
class Foo(T)
  def initialize(@value : T)
  end
  
  def map!(&)
    TypeSafeMap.new(T, yield @value)
    @value = yield @value
  end
  
  class TypeSafeMap(T, U)
    def initialize(t : T.class, @value : U)
      {{ raise "non matching types #{T} < #{U}" unless U <= T }}
    end
  end
end

# this works, obviously
Foo.new(1).map! &.to_i

# this is valid
Foo(Float64 | Int32).new(1).map! &.to_i

# this is invalid
Foo(Float64 | Int32).new(1).map! &.to_s
```

**Comment by asterite** [comment]
With `--error-trace` I get this:

```crystal
Error: instantiating 'Array(String)#map!()'


In /usr/local/Cellar/crystal/0.36.1_2/src/array.cr:1122:13

 1122 | @buffer.map!(size) { |e| yield e }
                ^---
Error: instantiating 'Pointer(String)#map!(Int32)'


In /usr/local/Cellar/crystal/0.36.1_2/src/pointer.cr:381:11

 381 | self[i] = yield self[i]
           ^
Error: no overload matches 'Pointer(String)#[]=' with types Int32, Int32

Overloads are:
 - Pointer(T)#[]=(offset, value : T)
```

The error points to `map!`.

Maybe the error could be improved. I'm sure that if you put a type restriction somewhere, something will break and we'll have to revert this.

As a side note, maybe it's just me,  but I think it's pretty obvious that `map!` will not be able to change the type of an array.

**Comment by HertzDevil** [comment]
We could do it like `Array#sort` at the moment:

https://github.com/crystal-lang/crystal/blob/b018f288c0ac336a8297d5c575e062e6bb791902/src/array.cr#L1693-L1696

**Comment by marzhaev** [comment]
> 
> As a side note, maybe it's just me, but I think it's pretty obvious that `map!` will not be able to change the type of an array.

@asterite I share your point of view 100%, but may be it's just us. You may be just too high up the learning curve 😄 

Coming from Ruby background, I'm pretty confident most new-coming users view it very differently. My argument is certainly not about arguing. The important part for me is to help make Crystal easy and appealing to them. The vast majority of beginner and intermediate tutorials seem to revolve about being able to code:

```
ary = [1,2,3]
ary.map!{ |x| x > 2 ? "Big" : "Small" }
ary # => ["Small", "Small", "Big"]
```

The way I bumped into was through accidentally adding the bang char at the end.

**Comment by asterite** [comment]
Yes, sorry, I shouldn't have disregarded that point of view. I think we should do what @HertzDevil suggested. Then we'll be able to provide a nice error message explaining why that can't be done.

**Comment by straight-shoota** [comment]
Oh well, `map!(& : T -> T)` actually works perfectly fine 🤦 

```cr
class Array
  def mymap!(& : T -> T) : self
    map!{ |v| yield v }
  end
end

["a","b", 1].mymap!{ |x| 1 }
```

**Comment by straight-shoota** [comment]
So the compiler is smart enough to match compatible block return types.

Using macros to enforce type compatibility is only necessary for restrictions of regular arguments.

**Comment by beta-ziliani** [comment]
To me the `map` function should be generic, returning a new Array of `U`s, as suggested by @marzhaev. Then, the inplace `map!` for the specific case `T -> T` should be something different (`inplace_map`?). Perhaps a change worth doing for 2.0.

**Comment by straight-shoota** [comment]
@beta-ziliani I don't follow. What would be the point of renaming the method?
I don't see much benefit from that, especially in comparison to the migration costs. `#map!` is already a different name than `#map`. Why would we need another different name? The current naming fits perfectly with the scheme that self-modifying methods are suffixed by an exclamation mark `!`.

I don't think there is anything else to do than add the type restriction `T -> T` to the `map!` block. This makes sure that you get a meaningful error message when using the method incorrectly.

**Comment by beta-ziliani** [comment]
Don't mind me, I missread this thread. Sorry for the noise!
