### ISSUE TITLE
Crystal cannot build static binaries in Fedora 33

### ISSUE THREAD

**Issue by renich** [crystal-lang/crystal#10465]
It seems that I cannot build a binary for a simple HTTP client using the `--static` flag. 

The error I get is:

```
[renich@introdesk ~]$ crystal build --release --static trafficante.cr 
/usr/bin/ld: cannot find -lz (this usually means you need to install the development package for libz)
/usr/bin/ld: cannot find -lssl (this usually means you need to install the development package for libssl)
/usr/bin/ld: cannot find -lcrypto (this usually means you need to install the development package for libcrypto)
/usr/bin/ld: cannot find -lpcre (this usually means you need to install the development package for libpcre)
/usr/bin/ld: cannot find -lm (this usually means you need to install the development package for libm)
/usr/bin/ld: cannot find -lgc (this usually means you need to install the development package for libgc)
/usr/bin/ld: cannot find -lpthread (this usually means you need to install the development package for libpthread)
/usr/bin/ld: cannot find -levent (this usually means you need to install the development package for libevent)
/usr/bin/ld: cannot find -lcrypto (this usually means you need to install the development package for libcrypto)
/usr/bin/ld: cannot find -lrt (this usually means you need to install the development package for librt)
/usr/bin/ld: cannot find -ldl (this usually means you need to install the development package for libdl)
/usr/bin/ld: cannot find -lc (this usually means you need to install the development package for libc)
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o /home/renich/trafficante  -rdynamic -static -L/usr/lib64 -L/usr/local/lib64 -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -lpcre -lm -lgc -lpthread /usr/share/crystal/src/ext/libcrystal.a -levent -lcrypto  -lrt -ldl`
```

I've checked in my system by compiling a list of the, supposedly, missing libs and searching for them on my own.

The list file:
```
libc
libcrypto
libdl
libevent
libgc
libm
libpcre
libpthread
librt
libssl
libz
```

The search command: `while read l; do echo "# Looking for $l..."; ldconfig -Nv | grep $l.so; echo; done < list 1> result.txt`

The result file will be attached. 
[result.txt](https://github.com/crystal-lang/crystal/files/6071691/result.txt)

To me, it seems I have all the required libraries. For some reason, crystal isn't able to find them (or, rather, LLVM?)

My OS: Fedora 33
My `crystal -v`: 

```
Crystal 0.36.1 (2021-02-02)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by Blacksmoke16** [comment]
Static builds are only doable via systems that use `musl-libc`, which the most common being Alpine linux.  See:
* https://github.com/crystal-lang/crystal/wiki/Static-Linking
* https://crystal-lang.org/2020/02/02/alpine-based-docker-images.html

**Comment by renich** [comment]
BTW, as a side note, I just noticed I have LLVM 11.0 installed (the default in Fedora 33)

**Comment by renich** [comment]
Ah... OK. Thanks @Blacksmoke16. You seem to be everywhere ;D

**Comment by straight-shoota** [comment]
The response from @Blacksmoke16 is inprecise. Fully static only works with musl. But that's just because linking glibc statically makes troubles. You can statically link other libraries, though. And the issue here is that that doesn't work, when it definitely should (at least in theory).

> To me, it seems I have all the required libraries.

Doesn't look like it. At least they're not discoverable.
Your report shows only *dynamic* libraries. But you need the *static* libraries to link statically. Hence the recomendation to install development versions of those packages, because they often include the static lib. Not sure how this works in Fedora, though.

Anyways, this seems not like an issue for this issue tracker. Please make sure you understand how static linking works and ask questions on the community channels https://forum.crystal-lang.org/ or https://crystal-lang.org/community/#chat

**Comment by renich** [comment]
@straight-shoota well, you shouldn't expect distros to distribute static libs in the devel packages. Fedora clearly doesn't and is against it, as they state in the packaging guidelines: https://docs.fedoraproject.org/en-US/packaging-guidelines/#packaging-static-libraries

"Packages including libraries SHOULD exclude static libs as far as possible (e.g., by configuring with --disable-static). Applications linking against libraries SHOULD link against shared libraries not static versions"

Thank you for the explanation, though.

**Comment by straight-shoota** [comment]
Nobody expects that. The linker just shows a friendly hint where you *might* find it.
