### ISSUE TITLE
Predicate properties

### ISSUE THREAD

**Issue by thoran** [crystal-lang/crystal#10471]
I have a class that I wanted to pull in some values using `from_json()` of which at least one is a boolean. I used an annotation along with a property with a `?` at the end. This didn't work. I didn't expect it to, but a colleague suggested it and thought I'd give it a go.

It is pretty apparent that this would require a language change, since attributes are not typically able to end with a `?`. The following are from `icr`...
```
class A
  property a?
end
```
=>
```
There was a problem expanding macro 'property'

Code in .icr_Dg65vcBY3dlMG4OmdfqD2w.cr:2:1

 2 | property a?
     ^
Called macro defined in macro 'macro_4391172960'

 630 | macro property(*names, &block)

Which expanded to:

 > 6 |             end
 > 7 |
 > 8 |             def a?=(@a?)
                   ^
Error: expecting token ':', not 'def'
```
Adding a type didn't help. (I didn't think it would, but at least I got a different error message.)
```
class A
  property a? : Bool
end
```
=>
```
In .icr_Dg65vcBY3dlMG4OmdfqD2w.cr:2:12

 2 | property a? : Bool = true
                ^
Error: unexpected token: :
```
This also doesn't work in Ruby either and didn't expect it to work there either, so this is not a bug, but rather a new feature.
```irb(main):001:1* class A
irb(main):002:1*   attr_accessor :a?
irb(main):003:1* end
Traceback (most recent call last):
        6: from /Users/thoran/.gem/ruby/3.0.0/bin/irb:23:in `<main>'
        5: from /Users/thoran/.gem/ruby/3.0.0/bin/irb:23:in `load'
        4: from /Users/thoran/.rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/irb-1.3.0/exe/irb:11:in `<top (required)>'
        3: from (irb):1:in `<main>'
        2: from (irb):2:in `<class:A>'
        1: from (irb):2:in `attr_accessor'
NameError (invalid attribute name `a?')
```

Until I write some macros for this, of course I instead had to write something like the following (which is what I had prior to trying out properties with `?`):
```
property a

def a?
  a
end
```

I would imagine that if this change were to occur, then the compiler would know that any property ending in `?` will always be a Bool, making typing optional.

I have a Ruby library which uses this syntax for defining command line switches, such that any switch defined as being named with a `?` at the end is then assumed to be a boolean switch. See https://github.com/thoran/switches.

**Comment by straight-shoota** [comment]
You're looking for the [`property?` macro](https://crystal-lang.org/api/0.36.1/Object.html#property?(*names,&block)-macro). That generates a predicate accessor.

> any property ending in `?` will always be a Bool, making typing optional.

This would be too restrictive, trailing question mark is often used to indicate nilable return values (in contrast to a rasing variant of the same method).
