### ISSUE TITLE
Bug: Undefined symbol `_roundeven`

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#10475]
#10413 introduced `Number#round_even` which binds to the LLVM intrinsic `roundeven` which was only introduced in LLVM 11. For older LLVM versions it falls back to `rint`.
It seems that the intrinsic is not (yet) available on darwin, for some reason.

----

I can't compile the compiler anymore :-(

```
Undefined symbols for architecture x86_64:
  "_roundeven", referenced from:
      _*Float64#round_even:Float64 in F-loat64.o
```

This is on Mac OSX, LLVM 11.1.0

_Originally posted by @asterite in https://github.com/crystal-lang/crystal/issues/10474#issuecomment-792021817_

**Comment by asterite** [comment]
Thank you!

**Comment by straight-shoota** [comment]
The `roundeven` intrinsic should be available since LLVM 11.0. For older LLVM versions it is not even used. So I really can't figure why you get the same error with LLVM 10 which uses `rint` instead.

This might have gone unnoticed because of #10110. But it seems the nightly jobs succeeded to build the compiler ([artifacts]( https://app.circleci.com/pipelines/github/crystal-lang/crystal/5398/workflows/ee9b89b8-8d63-4ce6-bf4c-dcadc7114ac2/jobs/58505/artifacts)). So it might be an individual issue on your end.
Can others with a mac try to reproduce?

I'm currently running a re-activated `test_darwin` on circle-ci.

A quick would obviously be to use `rint` unconditionally (at least on darwin). It's not strictly necessary to use `roundeven`.

```diff
--- i/src/float.cr
+++ w/src/float.cr
@@ -156,7 +156,7 @@ struct Float32
   def round_even : self
     # LLVM 11 introduced llvm.roundeven.* intrinsics which may replace rint in
     # the future.
-    {% if compare_versions(Crystal::LLVM_VERSION, "11.0.0") >= 0 %}
+    {% if compare_versions(Crystal::LLVM_VERSION, "11.0.0") >= 0 && !flag?(:darwin) %}
       LibM.roundeven_f32(self)
     {% else %}
       LibM.rint_f32(self)
@@ -257,7 +257,7 @@ struct Float64
   def round_even : self
     # LLVM 11 introduced llvm.roundeven.* intrinsics which may replace rint in
     # the future.
-    {% if compare_versions(Crystal::LLVM_VERSION, "11.0.0") >= 0 %}
+    {% if compare_versions(Crystal::LLVM_VERSION, "11.0.0") >= 0 && !flag?(:darwin) %}
       LibM.roundeven_f64(self)
     {% else %}
       LibM.rint_f64(self)
```

**Comment by straight-shoota** [comment]
Indeed, the error reproduces on circleci: https://app.circleci.com/pipelines/github/crystal-lang/crystal/5401/workflows/4e3883a7-5f92-4b6c-aa4b-3bf02eb2f086/jobs/58514

I'll try to poke around with SSH on the CI runner. Don't have a mac around.

**Comment by straight-shoota** [comment]
I couldn't install LLVM 10 with brew, so I tested with LLVM 9 and that sure works. So the LLVM 10 failure needs more inspection. Could you verify that it is indeed broken (it seems really unlikely)?

The patch from https://github.com/crystal-lang/crystal/issues/10475#issuecomment-792047565 fixes for LLVM 11 as expected.

Oh and the nightly builds still link against LLVM 6 (I think), that's why the nightly job didn't error.

**Comment by maxfierke** [comment]
Can reproduce on darwin (macOS Big Sur), and also ran into it on one of the BSDs when I was testing #10463. (I believe it was OpenBSD. NetBSD might also be affected.)

**Comment by asterite** [comment]
Given that using `roundeven` may not be supported in some platforms while `rint` seems to be well supported (otherwise we would have known by now), and that the advantages of `roundeven` over `rint` doesn't seem to be clear ("slightly improved semantics" doesn't seem to be a good reason if we can't understand exactly how it's better).

Put another way: let's write a benchmark for `roundeven` and `rint`, and also compare their semantics. If they both behave exactly the same way, I see no reason to choose `roundeven` in any case. If `rint` is removed in the future, then by all means yes, but that's not the case right now.

**Comment by straight-shoota** [comment]
For reference, this is the feature review at LLVM: https://reviews.llvm.org/D75670
There's also a current PR pending to add bindings to Rust: https://github.com/rust-lang/rust/pull/82273

**Comment by asterite** [comment]
Somewhere in the first link it says:
> In terms of LLVM IR, the unconstrained intrinsics llvm.rint, llvm.nearbyint, and llvm.roundeven are semantially identical. Backends should be able to lower them all the same way. If not, that's a bug. For this reason, I'm not sure we need all three.

I think it would be great to use `roundeven` just after we know it's available in platforms where `rint` is already working.

**Comment by straight-shoota** [comment]
Just to fill in: I think what's happening is that if LLVM doesn't have an impl for the intrinsic, it lowers to a call to `roundeven`. That's why we get an "undefined symbol" for an intrinsic. 
It seems that libm on darwin currently doesn't provide `roundeven`. And similar for other BSDs per https://github.com/crystal-lang/crystal/issues/10475#issuecomment-792432357.

So "Backends should be able to lower them all the same way" doesn't seem to be true, unfortunately.

**Comment by asterite** [comment]
Yes, it's the usual unfulfilled promise of "if you use LLVM then you don't need to worry about specific platforms" 😞
