### ISSUE TITLE
ICE: Module validation failed for ivar access in a yielded block inside a proc inside a method

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#10484]
This is a weird nested context:

* The relevant code is inside a method (`method`)
* Inside the method body is a proc literal
* Inside the proc body a method is called which yields an object to the block
* Inside the block an ivar of the yielded object cannot be accessed directly

The error does not trigger in top-level scope directly, or when the ivar is accessed through a getter, etc.

```cr
class Entry
  @ivar = 1
end

def yielding
  yield Entry.new
end

def capture(&block : ->)
  block.call
end

def method
  capture do
    yielding do |e|
      e.@ivar
    end
  end
end

method
```

```
Module validation failed: Stored value type does not match pointer operand type!
  store i32 1521, i1* %self, !dbg !391
 i1 (Exception)
  from /crystal/src/string.cr:5017:14 in 'finish'
  from /crystal/src/compiler/crystal/codegen/codegen.cr:69:7 in 'codegen'
  from /crystal/src/compiler/crystal/compiler.cr:172:16 in 'compile'
  from /crystal/src/compiler/crystal/command.cr:296:3 in 'run'
  from /crystal/src/compiler/crystal.cr:11:1 in '__crystal_main'
  from /crystal/src/crystal/main.cr:110:5 in 'main'
  from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
```

I stumbled over this while fiddling with the `Log` spec helper:
```cr
require "spec"
require "log"
require "log/spec"

def it_helper
  it do
    Log.capture do |logs|
      logs.@entries
    end
  end
end

it_helper
```

---

This could be a reduction of some of the cases described in #4858 (especially https://github.com/crystal-lang/crystal/issues/4858#issuecomment-632894822) or at least related.

**Comment by I3oris** [comment]
Don't reproduce anymore on 1.5.0 :tada:!
https://play.crystal-lang.org/#/r/dpoy
