### ISSUE TITLE
Add `#file_exists?` Top-level Macro Method

### ISSUE THREAD

**Issue by toddsundsted** [crystal-lang/crystal#10493]
## Feature Request

I have a macro that checks for the existence of various template files, which may or may not exist, and renders the first template it finds. Imagine the following:

```crystal
ok "objects/show"
```

The macro "ok" expands to code like the following:

```crystal
if accepts?("application/activity+json", "application/json")
  {% if read_file?("#{basedir.id}/#{message.id}.json.ecr") %}
    halt env, status_code: {{code}}, response: render {{"#{basedir.id}/#{message.id}.json.ecr"}}
  {% end %}
end
if accepts?("text/html")
  {% if read_file?("#{basedir.id}/#{message.id}.html.ecr") %}
    halt env, status_code: {{code}}, response: render {{"#{basedir.id}/#{message.id}.html.ecr"}}, "src/views/layouts/default.html.ecr"
  {% elsif read_file?("#{basedir.id}/#{message.id}.html.slang") %}
    halt env, status_code: {{code}}, response: render {{"#{basedir.id}/#{message.id}.html.slang"}}, "src/views/layouts/default.html.ecr"
  {% end %}
end
if accepts?("text/plain")
  {% if read_file?("#{basedir.id}/#{message.id}.text.ecr") %}
...
```

Ignoring the omitted details of this specific use case, the issue is that, for a given controller action, the template files may not exist, and processing should fall through to more general purpose code later in the macro. Right now, the only way to check for the existence of a file is by trying to read the file.

I'd prefer an explicit check. Something like `exists?` or `file_exists?`. I've created a possible implementation here: https://github.com/crystal-lang/crystal/pull/10489

This should not pose compatibility problems with any existing code because there is currently no means to create new top-level functions available to macros outside of the compiler.

**Comment by straight-shoota** [comment]
Sounds reasonable to add this.

A more straightforward solution would be something like this:
```cr
{% if content = read_file?("file.ecr") %}
  render_content(content)
{% end %}
```

But `ECR.embed` uses the `run` macro to call `ecr/process` which receives the file name, not the contents. So having a dedicated method to check for a file's existens makes sense. It avoids reading the file contents which is unnecessary.

**Comment by straight-shoota** [comment]
There's #7399 for enabling ECR to transform template strings directly. This would allow the more straightforward solution shown above.
I still think this is a good enhancement.
