### ISSUE TITLE
Arithmetic overflow in BigDecimal

### ISSUE THREAD

**Issue by SlayerShadow** [crystal-lang/crystal#10502]
I got these values when represented [Bresenham's algorithm](https://wiki2.org/en/Bresenham%27s_line_algorithm). Reduced as possible.

```crystal
require "big"

a = BigDecimal.new "-0.0000000000000005"
b = BigDecimal.new "0.9999999999999979291832202937938"

p a.div( b )
```

Provides an error:

```
Unhandled exception: Arithmetic overflow (OverflowError)
  from /usr/lib/crystal/core/big/big_decimal.cr:210:20 in 'div'
```

[Carc](https://carc.in/#/r/aj71) (Crystal 0.36.1).

Tested against modern compiler too:

```
# crystal -v
Crystal 1.0.0-dev [2588dc5] (2021-03-10)

LLVM: 11.1.0
Default target: x86_64-unknown-linux-musl
```

**Comment by bcardiff** [comment]
The overflow comes from the fact that at https://github.com/crystal-lang/crystal/blob/master/src/big/big_decimal.cr#L210 , `scale = @scale - other.scale` is an UInt64 operation with:

```
@scale              # => 16
other.scale         # => 31
```

It seems it's a bug that was always present in BigDecimal implementation.

**Comment by kellydanma** [comment]
I was looking into this bug because I also encountered the unhandled exception. I think the underlying problem is beyond the `div` method; [Rust uses a signed integer for the equivalent of `@scale`](https://github.com/akubera/bigdecimal-rs/blob/master/src/lib.rs#L140-L144), not an unsigned one. 

Before anyone picks up this issue, why did we choose `UInt64` for the instance variable type in this class?

**Comment by straight-shoota** [comment]
The data type was already UInt64 in the first commit that brought the BigDecimal implementation to Crystal: https://github.com/crystal-lang/crystal/commit/bc54aa0aedeaeeb50653ef0aa154035504370b79

It even references https://github.com/akubera/bigdecimal-rs as source of inspiration, but for some reason the scale type was changed to unsigned. Probably just a mistake. We should change it to `Int64`.

**Comment by straight-shoota** [comment]
Otoh, `scale` itself can't really be negative, so we could just fix `#div` implementation.

**Comment by kellydanma** [comment]
👆 Fixing `#div` makes more sense to me, thanks!

**Comment by kellydanma** [comment]
I'm a newbie 👋
I started working on this issue, feel free to comment even if the PR is in draft.
