### ISSUE TITLE
Problems with Math.pw2ceil

### ISSUE THREAD

**Issue by ghost** [crystal-lang/crystal#10514]
## Bug Report

```cr
puts Math.pw2ceil((2u64 ** 39) + 1)
# Expected: 1099511627776
# Actual:   1099511627521

puts Math.pw2ceil(0)
# Expected: 1
# Actual:   0 

puts Math.pw2ceil(-1)
# Expected: 1
# Actual:   0
```
In the [comments of the function](https://github.com/crystal-lang/crystal/blob/e79dc41c058a94230ea1c71cb742f7645da756a3/src/math/math.cr#L705), there is a link to a site explaining the implementation of the function. They mention a fix for the second example provided, and the last example can be fixed similarly. It seems that adding the line `v |= v >> 64` after the line `v |= v >> 32` fixes the function for unsigned 64-bit ints.

Ran on `Crystal 0.36.1`,  `OS: Manjaro Linux x86_64`.

**Comment by straight-shoota** [comment]
In fact, this method only works for 32-bit integers. I'd first restrict the argument type to reflect that.

`Math.pw2ceil(0) == 0` is an error and can be fixed as described.

I'm not sure about negative values, though. Should all negative input values return `1`? Or shouldn't it be an error to submit a negative value?

**Comment by HertzDevil** [comment]
That PR actually broke `Math.pw2ceil` for integers smaller than 32 bits, which used to work (albeit with 1 or 2 unnecessary shifts) but now fails with an ambiguous autocast.
