### ISSUE TITLE
`typeof` should create a new scope

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#10521]
Variables declared and assigned inside a `typeof` expression have no effect on code outside, so they shouldn't be accessible from outside at all. The following error:

```crystal
x = typeof(y = 1)
y # Error: read before assignment to local variable 'y'
```

should have been `undefined local variable or method 'y' for top-level`. In particular, the variables shouldn't be accessible from _other_ `typeof` expressions, like:

```crystal
module A; end
module B; end

typeof(begin
  x = uninitialized A
  x.is_a?(B) ? x : raise "" # #2404
end)
typeof(begin
  x = uninitialized B # Error: variable 'x' already declared with type A
  x.is_a?(A) ? x : raise ""
end)
```

**Comment by HertzDevil** [comment]
Should every argument of the same `typeof` start a new scope?

```crystal
x = 1
typeof(x = "", x = [x])
```

Should the above be `(String | Array(String))` or `(String | Array(Int32))`?

**Comment by Sija** [comment]
The most local (to the definition) would be `(String | Array(String))`

**Comment by straight-shoota** [comment]
I think I'd prefer the current behaviour (`(String | Array(String))`).

If you want `(String | Array(Int32))`, you can use `typeof(x = "") | typeof(x = [x])`. There should be no other implications, right?
