### ISSUE TITLE
Make Hashes work with mutable keys

### ISSUE THREAD

**Issue by wolfgang371** [crystal-lang/crystal#10526]
I ran into the problem that Hashes don't work out-of-the box with mutable keys (which is documented in the API).
In my use case I have a recursive data structure as a key, so it will change pretty often, unfortunately. A minimum example you can find here:

```crystal
class Tree
    include Indexable(Tree) # necessary
    def initialize
        @children = [] of Tree
    end
    def add_subtree
        subtree = Tree.new
        @children.push(subtree) # necessary
        subtree
    end
    def size
        @children.size
    end
    def unsafe_fetch(index : Int)
        @children.unsafe_fetch(index)
    end
end

XXX = 9 # with Hash: 9 fails, 8 still succeeds
h = Hash(Tree, String).new # MyHash works
t = r = Tree.new

XXX.times do |i|
    h[t] = "foo-#{i}"
    t = t.add_subtree
end
# h.rehash
puts("h has key r? #{h.has_key?(r)}")
h.each do |k,v|
    if k==r
        p ["h has key r with value v", k.as(Void*), v]
    end
end
```

The output is with `XXX=8` (still fine):
```console
h has key r? true
["h has key r with value v", Pointer(Void)@0x7fc688356e80, "foo-0"]
```

And `XXX=9` (bad):
```console
h has key r? false
["h has key r with value v", Pointer(Void)@0x7fa531f7be80, "foo-0"]
```

I was silently assuming that Crystal takes the pointer as keys, but obviously it doesn't.
By calling `rehash` I can make it work, of course, but if I need to modify my keys frequently, this is not really useful.

If I make a little wrapper class...
```crystal
class MyHash(K, V)
    @hash : Hash(Pointer(Void), V)
    def initialize
        @hash = Hash(Pointer(Void), V).new
    end
    def has_key?(k : K)
        @hash.has_key?(k.as(Void*))
    end
    def each(&block : K,V->)
        @hash.each do |k,v|
            yield(k.as(K), v)
        end
    end
    def [](k : K)
        @hash[k.as(Void*)]
    end
    def []?(k : K)
        @hash[k.as(Void*)]?
    end
    def []=(k : K, v : V)
        @hash[k.as(Void*)] = v
    end
end
```
... and use this instead of the standard `Hash`, all runs well.

Is there any reason why standard `Hash` is not like this?

**Comment by HertzDevil** [comment]
Such a wrapper would require all keys to be `Reference`s, or require all `Value`s to be boxed. It also uses `Pointer(Void)#==` and `#hash` instead of the ones defined in `K`. So it is entirely wrong.

Try `h.compare_by_identity`.

**Comment by wolfgang371** [comment]
`#compare_by_identity` did the trick in case of keys derived from `Reference`, thank you.

And for special non-`Reference` keys (e.g. Tuples over mutable objects (not part of above code)) using manually `#object_id` instead of the mutable variables directly. Still somewhat awkward, but it works.

**Comment by bcardiff** [comment]
One more detail. The `Indexable` module changes the default hash method. That is why adding a subtree changes things.

The default hash for reference is the pointer and if you remove the `include Indexable(Tree)` then the hash works as expected also.
