### ISSUE TITLE
[RFC] Enforce `HTTP::Server` `content-length` RFC compliance

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#10536]
## Discussion

#10353 made it so that `HTTP::Server` does not automatically add the `content-length` header when it shouldn't be present according to https://tools.ietf.org/html/rfc7230#section-3.3.2.

The question is, should `HTTP::Server` also _enforce_ RFC compliance?  I.e. removing the `content-length` header if the response status is a `204` and it's present.

**Comment by straight-shoota** [comment]
I don't think there's much benefit in being overly restrictive.
