### ISSUE TITLE
Add integer square root to stdlib

### ISSUE THREAD

**Issue by jzakiya** [crystal-lang/crystal#10545]
Now that Crystal has hit 1.0.0, I would like to formally request adding an ``integer square root`` method to ``stdlib``.

See discussion below, which contains code for an implementation.

https://forum.crystal-lang.org/t/integer-sqrt-in-stdlib/1839/48

**Comment by straight-shoota** [comment]
Sounds good to me. Are there any better name suggestions than `isqrt`, though?

**Comment by kimburgess** [comment]
@jzakiya I've made a few changes to your proposed implementation on the forum to bump the perf a little.
```
           sqrt 615.40M (  1.62ns) (± 0.26%)  0.0B/op   1.00x slower
jzakiya's isqrt  60.73M ( 16.47ns) (± 8.56%)  0.0B/op  10.13x slower
    isqrt in PR 615.40M (  1.62ns) (± 0.22%)  0.0B/op        fastest
```

@straight-shoota `isqrt` is a relatively common name for this, and seems to fit the terseness of remainder of the current Math lib.

**Comment by jzakiya** [comment]
Thanks @kimburgess.

**Comment by jzakiya** [comment]
FYI, Ruby used the Newton method implementation for it, which I showed an implementation for.
For really large number (>50 decimal digits...) it may be faster in more cases than the bit method.
Testing against very large number, that exceed the capacity for floats to represent accurately, is the
primary reason to include this, because otherwise, many numerical algorithms start to become inaccurate.

**Comment by jzakiya** [comment]
Here is a gist file of  tests/benchmarks I've done for different implementations for integer square and nth roots.
All methods work with all Integer types, including BigInts.
You can just copy/paste/run.  I know it works with 0.35 to 1.0.0.
For my uses cases, I need roots it to work with BigInts, because I do numerical algorithms using numbers > 64-bits.
Tests should be included for very large BigInts, to verify operation, as I show.

Just build with: ``$ crystal build irootstest.cr --release`` and run with: ``$ ./irootstest``

**irootstest.cr**
https://gist.github.com/jzakiya/53403d5ad410ed89a4db346716d1053d

**Comment by kimburgess** [comment]
Nice! That `BigInt` case makes sense. This implementation remains faster for all primitives though. I've added BigInt support to that primitive too via LibGMP. Perf of that (using your `10.to_big_i ** 577` test case).
```
sqrt (f)   4.26M (234.63ns) (±27.40%)  64.0B/op        fastest
newton   147.60k (  6.77µs) (±13.61%)  3.2kB/op  28.88 slower
libgmp     1.58M (631.88ns) (±17.58%)   128B/op   2.69 slower
```
Should give you perf _and_ accuracy.

**Comment by jzakiya** [comment]
I don't see in your test cases where you did all the integer types, and large numbers within them,
like for example ``2u64 ** 64 - 1``, etc

**Comment by didactic-drunk** [comment]
Wouldn't this be more terse and OO as `n.sqrt` instead of `Math.isqrt(n)`?  Shouldn't the `i` be dropped also?  Type prefixes aren't used in crystal anywhere else.

**Comment by jzakiya** [comment]
**First:** 
Integer square root ``isqrt`` is different from ``sqrt`` because it only operates on integers, and not floats.
Numerical square root  always returns a float, even if the number is a perfect square:  
``Math.sqrt(100) = 10.0``, ``Math.sqrt(101) = 10.04987562112089 ``
``Math.isqrt(100) = 10``,   ``Math.isqrt(101) = 10`` 
You can "fake" integer square root with e.g. ``Math.sqrt(n).floor``, but this starts to generate errors around ``10e50`` because of the inherent imprecise structure of base 10 floats representation in base 2 hardware.

In many numerical and algorithmic domains only integer math is used (number theory, cryptography, block chains, etc).
In many (most) of these fields, very large numbers (> 64 bits) are used, and easily start to exceed the accuracy range of floats, so a whole host of integer operations are used (not just square root) to perform this math accurately.  That's why there exists such libraries as ``GMP`` to deal strictly with ``BigInt``s.

**Second:**
See the above gist I provided **irootstest.cr** that creates a module that's included in ``struct Int; include IntRoots end`` to provide the OO syntax, which I also like better.  I guess it was a matter of keeping it consistent with ``Math.sqrt``.

**Comment by didactic-drunk** [comment]
I retract the `i` part and probably shouldn't have hit send while on the phone not reading carefully.
