### ISSUE TITLE
Supporting Crystal on microcontrollers (e.g. the Arduino)

### ISSUE THREAD

**Issue by athix** [crystal-lang/crystal#10552]
With Crystal reaching 1.0 (yay!! :tada:), hopefully there's more time available to look into supporting it on more platforms.

As someone who loves Ruby, but also loves microcontroller projects, it would be amazing if Crystal could be updated to support the memory-limited environment of MCUs. From various other discussions I've read, it sounds like the garbage collection would need to be disabled, stdlib slimmed down to a minimal version, and a new compiler written to support the microcontroller architecture.

Is this something worth pursuing? It would be amazing to use the syntax provided by Crystal on microcontrollers, but I don't know the details of the implementation well enough to know if it would be too restricted on MCUs to be worth the development efforts.

**Comment by straight-shoota** [comment]
This is not really an actionable item for this issue tracker, and would better serve as a discussion starter at https://forum.crystal-lang.org/

**Comment by jzakiya** [comment]
This is one reason Matz created MRuby:  https://mruby.org/

**Comment by leapofazzam123** [comment]
My proposal on this:
- There's a new target called `*-*-elf`, a very minimal version of the normal targets with no libc requirements
- Add a flag that can use other libc like musl, picolibc, and avr-libc
- Add a new options useful for embedded targets like `@LinkSection`

We can look at Zig, which is has a very good support on embedded devices. It's standard library doesn't need libc outside POSIX/UNIX systems.

**Comment by straight-shoota** [comment]
> Add a flag that can use other libc like musl, picolibc, and avr-libc

`musl` libc is already supported on linux. There's no need for a flag, it's part of the target triple. I don't see much point in supporting other libc implementations. It would be a huge undertaking with little benefit for most typical use cases.
If someone contributes the code for that, we might accept it (although there is still ongoing maintenance to consider). But it's most likely not something on our agenda.

Going for a small alternative to stdlib, implemented in Crystal with no dependencies, as mentioned in https://github.com/crystal-lang/crystal/issues/11866#issuecomment-1058010076, seems like more useful path. It might be even more work, but it also provides a lot more benefit.

**Comment by straight-shoota** [comment]
Closing per https://github.com/crystal-lang/crystal/issues/10552#issuecomment-807236647.

Such open discussions are better suited for https://forum.crystal-lang.org/ until there are actionable items we can track as issues.
