### ISSUE TITLE
Mass-adding type restrictions (`def foo() : Bar`)

### ISSUE THREAD

**Issue by oprypin** [crystal-lang/crystal#10575]
I have developed a semi-automatic workflow to insert type restrictions into Crystal code, and I plan to apply it to the Crystal standard library. The main purpose is to make documentation better. It also guards against some accidental incompatible changes.

The first phase will be only adding **method return type** restrictions. It's about 1400 annotations added.

* [x] [Add return type restrictions: explicitly specify Nil](https://github.com/crystal-lang/crystal/pull/10578)
* [x] [Add return type restrictions to number methods / classes](https://github.com/crystal-lang/crystal/pull/10579)
* [x] [Add return type restrictions to I/O methods](https://github.com/crystal-lang/crystal/pull/10580)
* [x] [Add return type restrictions to JSON, YAML, XML](https://github.com/crystal-lang/crystal/pull/10581)
* [x] [Add return type restrictions to methods of container types](https://github.com/crystal-lang/crystal/pull/10582)
* [x] [Add return type restrictions to methods related to String](https://github.com/crystal-lang/crystal/pull/10583)
* [x] [Add return type restrictions to file-related methods and Log](https://github.com/crystal-lang/crystal/pull/10584)
* [x] [Add return type restrictions to crypto-related classes](https://github.com/crystal-lang/crystal/pull/10585)
* [x] [Add return type restrictions to HTTP-related classes](https://github.com/crystal-lang/crystal/pull/10586)
* [x] [Add return type restrictions to various low-level methods](https://github.com/crystal-lang/crystal/pull/10587)
* [x] [Add return type restrictions: uncategorized](https://github.com/crystal-lang/crystal/pull/10588)

Links (I don't guarantee that the links won't break):
* Code (not for merging!!!): <https://github.com/oprypin/crystal/compare/argtohtml...annotator~>
* Type restrictions so far: https://github.com/oprypin/crystal/compare/annot

The implementation just needs to be fed real usages of the code, and it looks at all the methods that the compiler resolves while compiling the code, and if the method resolves to the same type in every situation, it figures that maybe it's good to add that type as a type restriction. It's super hacky and super unreliable so I filter and fix the results myself.

But I hope that the methods that this automation suggests to restrict are also *safe* places to make those changes; I'm not coming up with my own ideas, and if I did, I might miss the fact that I'm changing the actual type (e.g. setting it to Nil but it really isn't Nil and someone relied on that).

Semi-related to https://github.com/crystal-lang/crystal/issues/4864, mainly because the implementation is based on [the patch posted to the issue](https://gist.github.com/asterite/446c17e9bbdba85f0a330763f8ac12e1)

**Comment by oprypin** [comment]
Launched phase 2, adding **Nil return type** restrictions where the methods currently actually don't return nil but weren't meant to have a return value.

* [ ] [Change nonsense return types to Nil in IO-related methods](https://github.com/crystal-lang/crystal/pull/10621)
* [ ] [Change nonsense return types to Nil: JSON and YAML](https://github.com/crystal-lang/crystal/pull/10622)
* [ ] [Change nonsense return types to Nil in formatter classes](https://github.com/crystal-lang/crystal/pull/10623)
* [ ] [Change nonsense return types to Nil in HTTP-related methods and Log](https://github.com/crystal-lang/crystal/pull/10624)
* [ ] [Change nonsense return types to Nil: uncategorized](https://github.com/crystal-lang/crystal/pull/10625)

**Comment by asterite** [comment]
Keep'em coming! ❤️

**Comment by straight-shoota** [comment]
I milestoned the entire first batch of PRs. I think they're ready to be merged.
There hasn't been a lot of discussion entries, which I interpret as no general opposition (it could also be that nobody bothered to take a closer look).

The changes are rather big in terms of affected code. But there are presumably no semantic changes.
I'd leave them in the queue for a couple of days to allow for final reviews, but it we wait for too long, conflicts with other PRs may appear again.

**Comment by oprypin** [comment]
Nice. 5 more conflicts appeared.

**Comment by straight-shoota** [comment]
The entire first batch has been merged.

About the second batch: These are *technically* breaking changes because they alter the return value from something that is not `Nil` to `Nil`. However, that something was never meant to be returned and is probably of no particularly use. I would consider this a bug fix to avoid unintended leakage of implementation details, which requires altering the return type. So I think it's fine to merge in a minor release, but please speak up if someone thinks this should rather wait for 2.0.

**Comment by straight-shoota** [comment]
About the second batch: These are *technically* breaking changes because they alter the return value from something that is not `Nil` to `Nil`. However, that something was never meant to be returned and is probably of no particularly use. I would consider this a bug fix to avoid unintended leakage of implementation details, which requires altering the return type. So I think it's fine to merge in a minor release, but please speak up if someone thinks this should rather wait for 2.0.

**Comment by straight-shoota** [comment]
I'd like to test the incoming changes from the second batch with test-ecosystem before merging them to master.
We could do that for each PR individually, or merge them in a combined feature branch first. I suppose the former makes it easier to identify where issues come from.

Should wait after 1.1.1 is released though, to avoid congestion on test-ecosystem CI.

**Comment by straight-shoota** [comment]
I ran test-ecosystem on all five outstanding PRs and they look good 👍 That doesn't mean it won't break anything else, but it's a encouraging sign. Adding a return type restriction of `Nil` to methods that were not supposed to return a value in the first place is considerably less likely to cause hidden issues. It would only break code that depends on the (undocumented) return value and we can just say that that's not expected use.

So I think we should go on and merge the [*Change nonsense return types to Nil* PRs](https://github.com/crystal-lang/crystal/issues/10575#issuecomment-817397990).

**Comment by sdogruyol** [comment]
Gotta love more return types ❤️  Thanks @oprypin @straight-shoota 🙏

**Comment by straight-shoota** [comment]
The second batch has been merged. Thanks @oprypin

**Comment by straight-shoota** [comment]
I'm not sure if there's anything left here. Can we close this?

**Comment by oprypin** [comment]
It could be used for tracking of something in the future, but right now indeed it's best to close it. Thanks
