### ISSUE TITLE
Please add a [Documentation] label here

### ISSUE THREAD

**Issue by rubyFeedback** [crystal-lang/crystal#10589]
Hey crystal folks,

I tried to look for a template that has [Documentation] here on github. Because my next
question is about something related to documentation, but I could not find such a template.

It would thus be useful if the "new issue" part also gets a "Documentation" entry we could
pick and use. I did not find an appropriate entry for this from the current listing:

Bug Report; Language Improvement Discussion; Feature Request; Report a security vulnerability

**Comment by straight-shoota** [comment]
I'd say if the issue is about incorrect documentation, it's a bug report. If it's about enhancing documentation, it's a feature request.

**Comment by jhass** [comment]
And if it's a pure question it's for the forum :)
