### ISSUE TITLE
puts, newline and documentation

### ISSUE THREAD

**Issue by erdnaxeli** [crystal-lang/crystal#10592]
Hi,

The current doc for [puts](https://crystal-lang.org/api/1.0.0/toplevel.html#puts(*objects):Nil-class-method) says:
> Prints objects to STDOUT, each followed by a newline.
>
> If the string representation of an object ends with a newline, no additional newline is printed for that object.
>
> See also: IO#puts.

I understand it as "if obj.to_s ends with a newline, no additional newline is printed".

The docu for [IO#puts](https://crystal-lang.org/api/1.0.0/IO.html#puts(*objects:_):Nil-instance-method) says
> Writes the given objects, each followed by a newline character.

Here nothing is said about the string representation of an object ending with a newline, I understand that it adds a newline every time, no matter what.

The reality is that both documentations are wrong. What happens is that it adds a newline, except if the object is a string ending with a newline. See:
```Crystal
a = "test"
b = "test\n"
c = Exception.new("test")
d = Exception.new("test\n")
e = c.to_s
f = d.to_s

puts a
puts b
puts c
puts d
puts e
puts f
```

The result is
```
test
test
test
test

test
test
```

And if we look at the code, it is obvious. If the string is an object, [we check the presence of a newline](https://github.com/crystal-lang/crystal/blob/dd40a2442/src/io.cr#L218), else [we add a newline](https://github.com/crystal-lang/crystal/blob/dd40a2442/src/io.cr#L230) every time.

I don't see any easy way to check if the object representation built by `to_s(io)` will end with a newline without impacting performances. But I think the documentation should be updated to reflect what it is actually done in `.puts` and `IO#puts`.

**Comment by asterite** [comment]
Yes, that's the expected behavior, the docs are wrong.

**Comment by vlazar** [comment]
It's also different in Ruby. Ruby does not print extra new line with code provided.

**Comment by asterite** [comment]
@vlazar could you share a snippet where it behaves different than Ruby?

**Comment by yxhuvud** [comment]
@asterite It is the 4th entry that adds the newline, so 
```
d = Exception.new("test\n")
puts d
```
behave differently in the two languages.

**Comment by straight-shoota** [comment]
`puts Exception.new("test\n")` in Ruby does not add an additional newline, while in Crystal it does. I think this different behaviour is acceptable, as said in the OP, it would be hard to check if the last character was a new line character when it's appended by `to_s(io)` of an arbitrary object.

**Comment by asterite** [comment]
Oh, I see. Yeah, I think we should just use `to_s` here, then check if it ends in a newline, then append the object. Performance of converting to a `String` first isn't very important here.

If you don't want this behavior, you can use `print` and then follow it by a newline.

That said, this is impossible to change now for 1.0 because it would be a breaking change.

**Comment by straight-shoota** [comment]
@asterite I disagree. `to_s` can make a big difference for huge string representations. Even just considering the memory required to buffer the string.

**Comment by erdnaxeli** [comment]
> Yeah, I think we should just use to_s here, then check if it ends in a newline, then append the object. Performance of converting to a String first isn't very important here.

That what I though at first. But if we do that I think we we loose all the performance gained by doing `to_s(io)`, don't we?
