### ISSUE TITLE
Simple and idiomatic `crystal build`?

### ISSUE THREAD

**Issue by tkshnwesper** [crystal-lang/crystal#10593]
## Feature Request

The `build` command today takes a file name which to build. It would be great to have a default behavior for this that just works, like `crystal build` (without needing a file name). I see the [shards.yml][shards.yml] already has information on what to build.

On the same lines...
The Rust ecosystem has `cargo build` to build, and `cargo run` to run. It's very simple and idiomatic to use, especially for the new user.

Even the crystal compiler has some defaults that _just_ work without needing to specify any parameters, like `crystal init`, `crystal play` and most notably `crystal spec`.

In a similar fashion would it make sense to have a `crystal build`?

Will it break backwards compatibility? Thankfully, no.

[shards.yml]: https://github.com/crystal-lang/crystal/blob/e7b46c40739902db70a2dceebd09caf1a7c70553/src/compiler/crystal/tools/init/template/shard.yml.ecr#L10

**Comment by asterite** [comment]
That's `shards build`

**Comment by tkshnwesper** [comment]
> That's `shards build`

Thank you!
