### ISSUE TITLE
Make OpenSSL::Digest satisfy IO

### ISSUE THREAD

**Issue by leighmcculloch** [crystal-lang/crystal#10602]
## Feature Request

It is convenient to be able to stream or write to `OpenSSL::Digest` like an `IO`, but it doesn't adhere to the `IO` interface, so it is not possible to do that without wrapping the digest with another type.

As a comparison, in Go programs the digest functions satisfy the Go `io.Writer` interface, and so it is very convenient to wrap a digest function and some destination in an `io.MultiWriter` and to send data to both simultaneously.

This can be achieved rather simply in Crystal with a class like the below example, so maybe this is not really necessary, but coming from other languages like Go this feels like a missing convenience that objects like `OpenSSL::Digest` are not writers.

A reason that this feature might not be desirable is that `IO`s are both readers and writers and not only one in other languages like Java and Go. This doesn't seem to deter their use for things like STDIN and STDOUT though which are clearly only a reader or a writer.

Example:
```crystal
class DigestIO < IO
  def initialize(@digest : OpenSSL::Digest)
  end

  def read(slice : Bytes)
    0
  end

  def write(slice : Bytes) : Nil
    @digest.update(slice)
  end
end
```

**Comment by leighmcculloch** [comment]
I realize after reading https://github.com/crystal-lang/crystal/issues/3489 I realize I'm thinking about solving problems like I would if duck-typing was supported, but not all types can satisfy `IO`, it'd be unrealistic to import a module everywhere, and structural-typing is insufficient I think.

**Comment by asterite** [comment]
Check this out: https://crystal-lang.org/api/1.0.0/IO/Digest.html

**Comment by asterite** [comment]
The name DigestIO is much better in my opinion. Unfortunately we ended up with names like IO::Memory which doesn't make a lot of sense. But they are just names.

**Comment by leighmcculloch** [comment]
Thanks @asterite! I didn't know about `IO::Digest`.
