### ISSUE TITLE
`Float#to_u!` is broken on overflow values

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#10629]
```crystal
5.times { p -1.23.to_u64! }

# 830
# 140732686936831
# 140732686936831
# 140732686936831
# 140732686936831
```

The larger number is different in every run, and seems to be some kind of pointer address. Unlike #10359, this happens even without unions. I am able to reproduce this all the way back to 0.27.1, the first version that introduced `to_u!`, but even before that the silently overflowing variants also returned similar incorrect results. This doesn't happen to `to_i!`.

Are `Float#to_i!` and `to_u!` ever precisely defined? Which rounding mode do they use?

**Comment by asterite** [comment]
> Do I have to reset BigFloat.default_precision after each spec?

No. The idea is that these are dangerous methods. If the value is within range, all is good. Otherwise, the behavior is undefined. So I don't think this is a bug.

**Comment by HertzDevil** [comment]
So `Float#to_i64!` and `#to_u64!` don't require their values to be wrapped, unlike `Int`?

**Comment by HertzDevil** [comment]
Never mind, `to_i!` returns undefined values in the opposite sign. In this case the documentation is wrong.
