### ISSUE TITLE
Unlink default arguments from keyword arguments?

### ISSUE THREAD

**Issue by wconrad** [crystal-lang/crystal#1064]
I would like to discuss the relative merits of having default arguments and keyword arguments joined together in the current (0.7.4) syntax.  By "joined together" I mean:

* You cannot have a keyword argument without it being a positional   argument having a default.

* You cannot have a positional argument with a default without it also being a keyword argument.

I think that the joining of default arguments with keyword arguments could be a source of
headaches for API maintainers.  I will try to show that the API maintainer will benefit from having default arguments not create keyword arguments, and having keyword arguments not create positional arguments.

# Adding a default to a positional argument creates a keyword argument

I'll put the biggest headache first.  Let's say my library exposes this method:

    def foo(a)

In a later version of the library, I add an optional argument to _foo_:

    def foo(a, b = 0)

I am expecting that existing calls to `foo` will still work without change:

    foo(123)

and that programmers wishing to take advantage of the new second argument will pass it in:

    foo(123, 4)

However, since adding a default implicitly enables a keyword argument, the user of my library has the choice of calling _foo_ like this:

    foo(123, b: 4)

During a later refactoring, I come up with a better name for the
second argument:

    def foo(a, better_name_for_b = 0)

But I cannot do this refactoring without it being a breaking API change.  That's because the name of every argument that has a default is part of the API's signature.  A user of my library may have used
the second argument as a keyword argument; renaming that argument will break their code.

The workaround is to use method overloading:

    def foo(a, better_name_for_b = 0)

    def foo(a, b = 0)
      foo(a, better_name_for_b)
    end

I had to supply the same default argument to both method signatures, which doesn't seem ideal, but I guess that's what constants are for.

# Adding a keyword argument creates a positional argument

Since positional arguments are linked to keyword arguments, I can't force the user to call the method using only keyword arguments.  That means that the order of keyword arguments cannot be changed without it being a breaking API change.  In Ruby, the API maintainer can freely reorder keyword arguments without it being a breaking API change (or any API change at all).  Is it feasible to give the Crystal programmer the same freedom?

See also: https://github.com/manastech/crystal/issues/560

Version discussed here: `Crystal 0.7.4 [42efdbf] (Wed Jun 24 01:08:36 UTC 2015)`

**Comment by asterite** [comment]
These are very good arguments. So you are suggesting we separate notations for default arguments and keyword arguments, and to always require keywords in calls when you want to refer to keyword arguments?

There would still be the problem of breaking code if you decide to change a keyword name, right?

My personal opinion is that since Crystal is a compiled language, if you update a library and they changed the API, your code stops compiling. And these fixes should be trivial: change a name, reorder parameters. In Ruby it's harder because unless you have 100% test coverage the issue might happen at runtime.

But I'd like to know your pull proposal. Note that `:` is already used for type restrictions, so we'll have three symbols for method arguments (default: `=`, type restriction: `:`, keword: ?)

**Comment by jhass** [comment]
Note that the syntax to call keyword arguments is `foo(123, b: 4)`/`foo(1, better_name_for_b: 4`, `foo(123, b = 4)` just creates a local variable and passes the result of that expression as a positional argument. Perhaps we should disallow assignments inside calls, this seems to be a common gotcha.

I can see the argument about changing names changing the API, but you can also flip that argument and say it forces the maintainer to think of a good name for all their arguments, which gives better generated documentation for free as well as increasing the readability of the library itself.

**Comment by wconrad** [comment]
Thanks for considering what I wrote, and pointing out its flaws.

@asterite You're right, I hadn't considered that the type checking would come to the rescue in the case of renamed keyword arguments.  It won't help for reordered keyword arguments that are being called positionally... well, it will sometimes help, when the types don't match up correctly, and sometimes not help when the reordered arguments happen to be the same type.

As to a pull proposal... You mean I don't ask for a feature and it magically springs into existence? ;)  Well, I might as well crack open the code and see what I can see.

@jhass I'm bouncing back and forth between Python and Ruby, so it was almost inevitable that I'd get the syntax wrong.  Thanks for pointing that out.  I'll edit the post.

My main reason for renaming keyword arguments is that an argument that was once fine is no longer fine: Perhaps it is called `cache`, but there are now two different kinds of cache that the library deals with.  That said, I agree that the best name I can think of should be used from the start.

**Comment by asterite** [comment]
@wconrad Oh, by "proposal" I don't mean "pull proposal", that would be overkill. I think I was asking for the character to use for keyword arguments (on the declaration side), because I'm always hesitant to add new syntax.

@jhass Yes, maybe assignment inside a call should be disallowed, so we get less cryptic code and we can also suggest "use `arg: ...` for keyword arguments)

**Comment by wconrad** [comment]
@asterite What I'd really like is to get explicit keyword arguments, _and_ get both optional and required keyword arguments at the same time (that's why I referenced #560).

I don't have any truly good ideas, so here comes some bad ones:

# Staying close to how Ruby does it

What about stealing the `:=` assignment operator from Pascal/Agol, and using it for explicit keyword arguments?  I'm hoping that adding a `:=` token to the lexxer wouldn't cause trouble (can a type restriction ever start with an `=`?

    def foo(required, optional=2, required_keyword:=, optional_keyword:=4)

`=` would no longer define a keyword argument, but solely an optional positional argument.

# Using a prefix instead

Another idea would be to use a prefix, a character that means "this is a keyword argument".

    def foo(required, optional=2, !required_keyword, !optional_keyword=4)

I picked bang for the prefix for no good reason.  I don't see any prefix character that would have an obvious meaning... no matter which one is picked, it's going to be a bit of syntactical magic that the reader will just have to learn the meaning of.  That's too bad.

What I _do_ like about the prefix is that it divides the two axes (positional vs. keyword, required vs. default) cleanly in half syntactically.  The prefix decides positional/keyword, the suffix decides required/default.

**Comment by jhass** [comment]
I'm still voting for Python style keyword arguments, like mentioned in https://github.com/manastech/crystal/issues/560#issuecomment-94793013

That is make arguments and keyword arguments a single concept, no changes at the definee side, instead do what we do now but also allow required arguments to be used as keyword arguments on the caller side.

That reduces the amount of concepts you need to learn, the amount of syntax to learn and add (no new syntax from what's there already in fact) and seem to have proved itself in the Python world.

I don't think that it makes all the argument names part of the API is that much of a big deal as you make it, as I wrote before in fact I like that it makes you think twice about which name you choose. And we get it for free with all existing Crystal code already.

**Comment by stugol** [comment]
+1 for being able to flag a keyword argument as not eligible for positional use.

Perhaps use quotes in the declaration? ```def fn(arg1, arg2, "keyword_arg", "other_keyword_arg" = 4)```

Or perhaps the rocket syntax: ```def fn(arg1, arg2, keyword_arg => 7)```

**Comment by BlaXpirit** [comment]
Python has this `*` syntax:

```python
def f(a, b=6, *, c=7, d):
      pass
```

`a` and `b` can be positional or keyword (b is optional).
`c` and `d` are keyword only (d is required!).

I quite like this, but this is not a big deal.

I insist only on allowing any argument to be passed through keyword.

**Comment by stugol** [comment]
I didn't know about that feature. I would prefer a different syntax, personally.

**Comment by ozra** [comment]
+1 also on separation of defaults and keywording.

I find both `:=` and `=>` to be acceptable syntax choices.
As for the call, I feel `key: val` still seems better than forbidding assignments in calls (not because it's a practise I use or think is good, it just looks more confusing in code imo). The colon as key-val connector feels very natural based on common uses today.

**Comment by ozra** [comment]
Throw up variation on the "prefix"-road (considering that `:` begins type annotation after param names):
```crystal
def foo(required, optional = 2, :required_keyword, :optional_keyword = 4)
def typed_foo(required: Bool, optional = 2 : Int32, :required_keyword : Foo, :optional_keyword = 4 : Int64)
```

**Comment by stugol** [comment]
I don't like Ozra's suggestion. Too verbose. It needs a terse symbolic notation.

**Comment by tristil** [comment]
I am working on some code right now that relates to these pain points:

```crystal
class Frame
    def initialize(@window = null, @height = 3)
      self.window = window
      window.render
    end
end
```

This compiles but I don't actually want to have a default value for `window`. `null` is not an acceptable option (I'm a little confused about why it doesn't cause a compiler error) and listing it here seems like misleading method documentation. I just want it be a required keyword argument. In addition I initially wanted the second argument to be `options = {} of Symbol => Int32` and to have `options` work like a remaining keywords splat, like `**options` in Ruby, but that didn't work. Anyway, just some feedback. Combining positional and keyword arguments does seem like an elegant solution, but required/non-defaulted keyword arguments are really important IMO.

**Comment by stugol** [comment]
Agreed.
+1 for non-defaulted keyword arguments.
+1 for `**options`.

I suggest copying the Ruby 2.0 syntax (which I literally only discovered last night!!) for mandatory keyword arguments (`arg:`) and the `**options` hash.

**Comment by jhass** [comment]
Let's close this one due to #2537. Please open more focused issues in case you see something here that you still miss.
