### ISSUE TITLE
TZ and /etc/localtime assumptions

### ISSUE THREAD

**Issue by chaychoong** [crystal-lang/crystal#10651]
Running something in Ubuntu 18.04 docker image 

```
Unhandled exception:  (Time::Location::InvalidTZDataError)
  from /usr/share/crystal/src/time/location/loader.cr:81:5 in 'read_zoneinfo'
  from /usr/share/crystal/src/crystal/system/unix/time.cr:59:9 in 'local'
  from /usr/share/crystal/src/time/location.cr:460:5 in 'new'
  from /usr/share/crystal/src/compress/gzip/reader.cr:57:5 in 'initialize'
  from /usr/share/crystal/src/http/common.cr:54:11 in 'from_io?'
  from /usr/share/crystal/src/http/client.cr:600:5 in 'exec_internal_single'
  from /usr/share/crystal/src/http/client.cr:587:5 in 'exec'
  from /app/lib/crest/src/crest/request.cr:180:23 in 'execute'
```

After some investigation, it turns out that the TZ env variable is not set, nor is `/etc/timezone`. Crystal somehow attempts to read `/usr/share/zoneinfo`, which is a directory.

https://github.com/crystal-lang/crystal/blob/master/src/time/location.cr#L290

**Comment by straight-shoota** [comment]
I installed Crystal in the `ubuntu:18.04` docker image and ran `crystal eval 'p Time::Location.local'`. It worked fine.
Can you give more specific instructions on how to repduce this? And with which Crystal version.

`/usr/share/zoneinfo` is (optionally) expected to be a directory that contains zone info files. Only `/etc/localtime` is accessed as a file. I think the error can really just result from `/etc/localtime` being a directory. It seems the loader only checks that the file exists, but not if it is actually a file.

**Comment by Sija** [comment]
> however, in that case the error message should mention an `IO::Error` as cause

@straight-shoota It does in the linked issue - https://github.com/coverallsapp/coverage-reporter/issues/3

**Comment by chaychoong** [comment]
@straight-shoota after some investigation, it turns out that the base image I was using did some weird thing that softlinked the `/usr/share/zoneinfo/` folder to `/etc/localtime`. My fault for misattributing the root cause.

Like you said, it's probably still a good idea to do a little validation before trying to load the file. Should I rename or close the issue?

**Comment by straight-shoota** [comment]
Just leave it open, I'll push a fix.
