### ISSUE TITLE
Linker error when running/compiling code on OSX

### ISSUE THREAD

**Issue by willdoescode** [crystal-lang/crystal#10653]
## Bug Report
![Screen Shot 2021-04-22 at 23 09 49](https://user-images.githubusercontent.com/53620720/115826473-d6a2b300-a3bf-11eb-967b-dbbdce53dbfc.png)

```
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _*Crystal::Iconv#convert<Pointer(Pointer(UInt8)), Pointer(UInt64), Pointer(Pointer(UInt8)), Pointer(UInt64)>:UInt64 in C-rystal5858I-conv.o
  "_iconv_close", referenced from:
      _*Crystal::Iconv#close:Nil in C-rystal5858I-conv.o
  "_iconv_open", referenced from:
      _*Crystal::Iconv#initialize<String, String, (Symbol | Nil)>:Nil in C-rystal5858I-conv.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc "${@}" -o /Users/willlane/.cache/crystal/crystal-run-main.tmp  -rdynamic -L/usr/local/lib -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -lpcre -lgc -lpthread /usr/local/Cellar/crystal/1.0.0/src/ext/libcrystal.a -L/usr/local/Cellar/libevent/2.1.12/lib -levent -liconv -ldl`
```

**Comment by straight-shoota** [comment]
The error message states that you're missing `libiconv`. It's a required dependency of the standard library.

How did you install Crystal?

**Comment by willdoescode** [comment]
@straight-shoota  I installed crystal through homebrew

**Comment by straight-shoota** [comment]
You can probably install the missing library with `brew install libiconv`.
I would have assumed that it is already a dependency in the brew formula, but apparently it isn't.

**Comment by willdoescode** [comment]
Hmm I made sure it is installed and its still throwing the same errors

![Screen Shot 2021-04-23 at 09 43 27](https://user-images.githubusercontent.com/53620720/115903377-5c524d00-a418-11eb-8ea8-4e6002f096bd.png)

**Comment by jhass** [comment]
Can we see your `brew info libiconv`?

**Comment by willdoescode** [comment]
```
libiconv: stable 1.16 (bottled) [keg-only]
Conversion library
https://www.gnu.org/software/libiconv/
/usr/local/Cellar/libiconv/1.16 (31 files, 2.5MB)
  Poured from bottle on 2021-04-23 at 09:29:10
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libiconv.rb
License: GPL-3.0
==> Caveats
libiconv is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have libiconv first in your PATH, run:
  echo 'set -g fish_user_paths "/usr/local/opt/libiconv/bin" $fish_user_paths' >> ~/.config/fish/config.fish

For compilers to find libiconv you may need to set:
  set -gx LDFLAGS "-L/usr/local/opt/libiconv/lib"
  set -gx CPPFLAGS "-I/usr/local/opt/libiconv/include"

==> Analytics
install: 4,188 (30 days), 13,431 (90 days), 61,801 (365 days)
install-on-request: 2,767 (30 days), 8,912 (90 days), 39,493 (365 days)
build-error: 0 (30 days)
```

**Comment by jwoertink** [comment]
@willdoescode is this a M1 mac? I had someone install from homebrew the other day and it never installed `libevent`. I'm wondering if there's an issue around that..

**Comment by willdoescode** [comment]
I am on an intel mac

**Comment by jwoertink** [comment]
Well, there goes my theory 😆

**Comment by asterite** [comment]
Note that I have a mac and I don't have `libiconv` installed through Homebrew and it still works. I don't know how to figure out where is my libiconv, but... is this a really old Mac?

**Comment by willdoescode** [comment]
This is a 2020 macbook right before the m1 came out.

**Comment by asterite** [comment]
Can you try one of the suggestions given by homebrew in https://github.com/crystal-lang/crystal/issues/10653#issuecomment-825787400

The reason it's not working is that you have libiconv, but it's not in the PATH. Doing the first thing suggested there _should_ make it work.

**Comment by asterite** [comment]
Oh, actually, maybe not... maybe that first thing is for executables. I don't know 🤷

**Comment by willdoescode** [comment]
I tried it after making sure the first libiconv in my path is the one from homebrew and I still got the same error, im guessing its not an issue with the absence of libiconv but the version.

**Comment by straight-shoota** [comment]
It's actually weird that the symbols start with an underscore. They shouldn't.
The names should be `iconv`, `iconv_close` and `iconv_open`: https://github.com/crystal-lang/crystal/blob/master/src/lib_c/x86_64-darwin/c/iconv.cr

**Comment by willdoescode** [comment]
I reinstalled the apple developer tools and I had the same error, I also tried reinstalling with homebrew and I got the same error still.

**Comment by asterite** [comment]
> It's actually weird that the symbols start with an underscore

Leading underscores are always shown on missing symbols.

**Comment by naqvis** [comment]
Seems you have multiple versions of **iconv** installed. Mac OSX comes with version installed under `/usr/lib`, you installed one via HomeBrew and XCode also comes with bundled iconv installed under `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSXNN.N.sdk/usr/lib/` where `NN.N` represents the version of XCode installed on your box.

Library search path is finding the GNU **libiconv** whose function names starts with **libiconv_**, while Crystal output shows its expecting the function names without this prefix and default library that comes with Mac OSX is the right one. This could be due to compiler finding the header files (.h) files of one versio while library search path is finding another version first (so the conflict).

You can try something like:
1. Remove HomeBrew installed version
2. Remove or move to different location some other versions (if installed)

HIH.

**Comment by straight-shoota** [comment]
> This could be due to compiler finding the header files (.h) files of one versio

The compiler doesn't care about header files. The function bindings are defined in https://github.com/crystal-lang/crystal/blob/master/src/lib_c/aarch64-darwin/c/iconv.cr
But yeah, they expect the symbol names without `libiconv_` prefix.

**Comment by jhass** [comment]
Can we also see your `env` and `crystal env`?

**Comment by willdoescode** [comment]
<img width="1436" alt="Screen Shot 2021-04-24 at 15 59 59" src="https://user-images.githubusercontent.com/53620720/115975022-20051680-a516-11eb-83ac-b60f74143c41.png">
<img width="547" alt="Screen Shot 2021-04-24 at 16 00 08" src="https://user-images.githubusercontent.com/53620720/115975024-25626100-a516-11eb-9d1e-ef98d7513fe6.png">

**Comment by willdoescode** [comment]
> Seems you have multiple versions of **iconv** installed. Mac OSX comes with version installed under `/usr/lib`, you installed one via HomeBrew and XCode also comes with bundled iconv installed under `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSXNN.N.sdk/usr/lib/` where `NN.N` represents the version of XCode installed on your box.
> 
> Library search path is finding the GNU **libiconv** whose function names starts with **libiconv_**, while Crystal output shows its expecting the function names without this prefix and default library that comes with Mac OSX is the right one. This could be due to compiler finding the header files (.h) files of one versio while library search path is finding another version first (so the conflict).
> 
> You can try something like:
> 
> 1. Remove HomeBrew installed version
> 2. Remove or move to different location some other versions (if installed)
> 
> HIH.

I tried to do these things and I still get the same error

**Comment by jhass** [comment]
Your `PATH`  looks a little weird, lots of things in there, lots of duplication too. But then I doubt it's really that, might be worth anyhow to try running with a minimal `PATH`.

**Comment by willdoescode** [comment]
I fixed this by adding "-L/usr/lib" to the link flags, im still not sure what changed as crystal used to work fine.

**Comment by willdoescode** [comment]
I know this is not just an issue with crystal as I was having the same issue with haskells ghc so Ill close this issue now.

**Comment by HenkPoley** [comment]
In case you run conda, a python package manager, you can try `conda deactivate`, to hide its iconv from the linker.
