### ISSUE TITLE
Latest docker image is broken

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#10678]
The docker image `crystallang/crystal:latest` uses the deb repository from bintray and thus is broken since bintray shut down. <ins>The repository is no longer accessible and thus `apt update` will fail if you run it.</ins>
I don't know why it uses that repository instead of directly embedding the deb package like the nightly builds.
IMO it would be easier to just do that.

Anyways, first step we're gonna have to push new, working Dockerimages to dockerhub for `nightly` and `nightly-build` tags. I don't know if others are affected, too but I don't think so.

**Comment by straight-shoota** [comment]
Oh and `latest-i386`, `latest-i386-build` are also affected.

**Comment by jwoertink** [comment]
I'm using `crystallang/crystal:0.36.1` in one of my projects which also looks to be broken.

**Comment by straight-shoota** [comment]
Yeah, all older releases are affected, too. But since 1.0 is released, they're not actively supported anymore.
I suppose we could update at least the most recent pre-1.0 releases as well and delete older ones. Main focus is on 1.0 though.

**Comment by jwoertink** [comment]
Yeah, that makes sense. I don't think it's a huge issue to focus on pre 1.0, though, it looks like 1.0 container is also affected. Bintray is the new leftpad 😂

**Comment by bcardiff** [comment]
I think the rationale for tagged docker images was to use the deb packages as they would been used by end users.
As a reminder, docker images of tagged versions are built by https://github.com/crystal-lang/crystal-dist/blob/master/docker/crystal/Dockerfile .

**Comment by straight-shoota** [comment]
I don't see the significance of "as they would been used by end users." Why does it matter? I use the docker image to have crystal installed (and do not care about packaging).
For verifying the package it's not really comprehensive. It justs installs it on a single distro in a single version. The [package tests](https://github.com/crystal-lang/distribution-scripts/tree/master/packages/test) are a better tool for that.

The [alpine dockerfile](https://github.com/crystal-lang/distribution-scripts/blob/master/docker/alpine.Dockerfile) (which seems to be used for release images, too) really just extracts the tarball, it doesn't even manually install an actual package.

I'd really prefer to use just a single set of docker files (https://github.com/crystal-lang/distribution-scripts/tree/master/docker) to build all the docker images, release and non-release. They already exist and don't need any extra setup. We can just easily integrate them into the release process and dump the extras from crystal-dist, reducing duplication.

**Comment by bcardiff** [comment]
It was a way to avoid duplicating the dependency information from the deb package. Package test came later.

I find it a bit odd that the installation would be different from what an end user would do. But that's all. It can be changed as long as the release checklist document is updated to reflect how to do things.

**Comment by straight-shoota** [comment]
For clarification, this is not a complete breakage (thankfully; we'd probably have more reports by now 😅 ):
The images still work if you use them as is. But running `apt update` before installing additional packages will error because the bintray repository is no longer accessible.
This can be mitigated by adding `rm /etc/apt/sources.list.d/crystal.list` before that.

We'll be publishing updated images shortly.

**Comment by bcardiff** [comment]
I pushed new docker images with the `rm /etc/apt/sources.list.d/crystal.list` for the following tags

- crystallang/crystal:0.36.0
- crystallang/crystal:0.36.1
- crystallang/crystal:1.0.0
- crystallang/crystal:latest

**Comment by bcardiff** [comment]
Closing. If there is a need to update older images drop a comment.
