### ISSUE TITLE
Code unexpectedly compiles with missing `,`

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#10694]
Discovered as part of #10693.  The following code unexpectedly compiles:

```cr
 def execute(foo = "foo", bar = "bar")

  pp(foo: foo bar: bar)
end

execute # => {foo: "foo"}
```

I would have expected this not to, note the missing `,` after `foo` in the `pp` call.

**Comment by HertzDevil** [comment]
Reduced:

```crystal
foo = 1
foo bar: adjkgdajkf # `Var.new("foo")`
```

It's a parser error. The compiler could interpret the last line as `pp(foo: foo(bar: bar))`, like in the following example:

```crystal
class A
  def initialize
    x = 1
    x(foo: foo(bar: bar))
    x foo: foo bar: bar # should be identical to the line above
  end
  
  def x(**opts)
    print opts
  end
  
  def foo(**opts)
    print opts
    2
  end
  
  def bar
    1
  end
end

A.new # => {bar: 1}{foo: 2}
```

The same omission of parentheses is a syntax error in Ruby and I don't know if they have a good reason to disallow this.

**Comment by straight-shoota** [comment]
Allowing the syntax is okay and expected. But this should be an error because there is no `foo` method.

**Comment by HertzDevil** [comment]
Duplicate of #9189.

**Comment by Blacksmoke16** [comment]
Duplicate of #9189
