### ISSUE TITLE
`travis.yml` template is no longer working

### ISSUE THREAD

**Issue by tkshnwesper** [crystal-lang/crystal#10690]
## Bug Report

Hello all,

The `travis.yml` template is [not working](https://travis-ci.com/github/tkshnwesper/agyan/builds/225295620). I'm getting the following error:

```
$ crystal --version
No command 'crystal' found, did you mean:
 Command 'gcrystal' from package 'gcrystal' (universe)
crystal: command not found

$ shards --version
shards: command not found

0.08s$ shards install
shards: command not found
The command "shards install" failed and exited with 127 during .
```

**Comment by jhass** [comment]
This will hopefully start working again once https://github.com/travis-ci/travis-build/pull/1987 is merged. 

But we really should drop the template from the generator, in sight of https://blog.travis-ci.com/2021-05-07-orgshutdown if nothing else.

**Comment by tkshnwesper** [comment]
Cool, thank you for the response.

**Comment by j8r** [comment]
Agreed. And according to the poll at https://forum.crystal-lang.org/t/poll-how-do-you-use-crystal-init/2921, now few people are still using Travis CI.

**Comment by straight-shoota** [comment]
Crystal on Travis CI is broken. There seems to be no drive to fix that (https://github.com/travis-ci/travis-build/pull/1987). I have made my peace with it 🙇 
Even if Travis fixes this, I don't think we have enough trust left for having it as the default CI config generated for every Crystal project. See also https://blog.travis-ci.com/2021-05-07-orgshutdown

This means, the Travis CI config file produced by `crystal init` does not work. It irritates users and must be removed.

We can either add a replacement (#8532, #8844) or leave `crystal init` without CI config for now.
Removal of Travis config should definitely go into 1.1.0, adding a replacement is optional.

**Comment by straight-shoota** [comment]
Personally, I tend to use Github Actions these days and many projects do that as well (including this repo). So I would prefer adding Github Actions configuration to `crystal init`.

Regarding configurator options, I'd go with these:
* The init tool knows whether it's generating an app or lib
* I believe Linux support should be sufficient as a default (could consider Mac but it really doesn't make a difference for most projects)
* Probably just test against the latest release
* I would prefer adding an active formatter step (but it could be commented)
