### ISSUE TITLE
IO flushed twice if using JSON.build or YAML.build

### ISSUE THREAD

**Issue by matthewmcgarvey** [crystal-lang/crystal#10709]
### JSON
1. https://github.com/crystal-lang/crystal/blob/3b5bc55db3f9dc91cceabe8fc86683009faaf8b2/src/json/builder.cr#L56
2. https://github.com/crystal-lang/crystal/blob/3b5bc55db3f9dc91cceabe8fc86683009faaf8b2/src/json/builder.cr#L418

### YAML
1. https://github.com/crystal-lang/crystal/blob/3b5bc55db3f9dc91cceabe8fc86683009faaf8b2/src/yaml/builder.cr#L67
2. https://github.com/crystal-lang/crystal/blob/3b5bc55db3f9dc91cceabe8fc86683009faaf8b2/src/yaml/builder.cr#L56

Trying to figure out why calling `{hello: "world"}.to_json(http_response)` is so much slower than `http_response.print({hello: "world"}.to_json)`. This seems like it could be one of the issues since my guess is that the response io would be flushed 3 times per request in the slow version and only once in the quicker. PR updating TechEmpower benchmarks: https://github.com/TechEmpower/FrameworkBenchmarks/pull/6584

I tried referencing other builders but it seems that every one does it differently:
- [csv](https://github.com/crystal-lang/crystal/blob/3b5bc55db3f9dc91cceabe8fc86683009faaf8b2/src/csv.cr#L161)
- [xml](https://github.com/crystal-lang/crystal/blob/3b5bc55db3f9dc91cceabe8fc86683009faaf8b2/src/xml/builder.cr#L380)

**Comment by matthewmcgarvey** [comment]
Looks like the double flushes were added in this PR https://github.com/crystal-lang/crystal/pull/9321 which was made to align the builders flush methods though it didn't remove the old flush calls like it probably should have.

**Comment by straight-shoota** [comment]
Yeah, I suppose I missed in #9321 that the duplicate flushes should be removed.
