### ISSUE TITLE
Random::Secure.urlsafe_base64(X) creates a string larger than X

### ISSUE THREAD

**Issue by rishavs** [crystal-lang/crystal#10708]
My expectation is that the command Random::Secure.urlsafe_base64(X) should create a string which is X bytes in length. However, the created string is much larger. 

Here is some sample code to see this bug.
https://play.crystal-lang.org/#/r/b4mv
```
sessionid1 = Random::Secure.urlsafe_base64(64, padding: true) 
p! sessionid1
p! sessionid1.size
p! sessionid1.bytesize
 
sessionid2 = Random::Secure.urlsafe_base64(64, padding: false) 
p! sessionid2
p! sessionid2.size
p! sessionid2.bytesize
 
sessionid3 = Random::Secure.urlsafe_base64(64) 
p! sessionid3
p! sessionid3.size
p! sessionid3.bytesize
 
sessionid4 = sessionid1.byte_slice(0, 64)
p! sessionid4
p! sessionid4.size
p! sessionid4.bytesize
```
Gives the output;
```
sessionid1 # => "Xj0J-cl82jNdBD_mNj4WXIr18PEFULMWUQaYATb-d_Rs7qWyeY7vWfrkfesmjP1yLts3lnOORDnIkEPLzu95zg=="
sessionid1.size # => 88
sessionid1.bytesize # => 88
sessionid2 # => "o20PaCsRAbhswtNAvbBHT89tlWdnazKas85Iocd30RtOWxegoHAObtzms1GuihlOCrN-dnGuS9n5H19CMqc6Sg"
sessionid2.size # => 86
sessionid2.bytesize # => 86
sessionid3 # => "wMpIMipn7Ln-Iej5pJx427OygFApfIMGJXQWs3quc99i9rjIYQey1v7Vzr9qoLSF7sBUuKkw5pUVyz1nejlv9w"
sessionid3.size # => 86
sessionid3.bytesize # => 86
sessionid4 # => "Xj0J-cl82jNdBD_mNj4WXIr18PEFULMWUQaYATb-d_Rs7qWyeY7vWfrkfesmjP1y"
sessionid4.size # => 64
sessionid4.bytesize # => 64
```

**Comment by jhass** [comment]
Ruby behaves the same:

```
[8] pry(main)> SecureRandom.urlsafe_base64(64).size
=> 86
```

I think this makes sense, the argument is the number of random bytes which then are encoded in base64.

The documentation could be more explicit about this though.

**Comment by straight-shoota** [comment]
In what sense could the documentation be more explicit? I mean, it clearly says the method generates *n* random bytes and encodes them with base64.
The only thing I could think of would be to mention that base64 encoding takes more space than the binary data. But that's a very general statement, and it should be rather obvious, at least that *encoded* data is likely to have a different size than the original.

**Comment by jhass** [comment]
https://github.com/crystal-lang/crystal/blob/d7e0f7009051aa0f1f690d96fee318430fb30471/src/random.cr#L374-L385

could mention this directly and not only implicitly by referring to `base64`, that's easy to miss. Compare Ruby: https://rubyapi.org/3.0/o/random/formatter#method-i-urlsafe_base64
