### ISSUE TITLE
Float string interpolation prints some  null characters

### ISSUE THREAD

**Issue by NIFR91** [crystal-lang/crystal#10714]
Hi
I found that the interpolated string 

```crystal
puts ("%f" % 1e15)  #=> 1000000000000000.00000�
```

contains null characters for numbers `> 1e14`, i think this is not an expected behavior and ruby does print the number, therefore 
i think this is a bug. 

```
Crystal 1.0.0 (2021-03-29)

LLVM: 10.0.1
Default target: x86_64-pc-linux-gnu

5.10.34-1-MANJARO x86_64 GNU/Linux
```

**Comment by HertzDevil** [comment]
This ultimately depends on `String::Formatter(A)#float`, which calls `snprintf`:

https://github.com/crystal-lang/crystal/blob/d7e0f7009051aa0f1f690d96fee318430fb30471/src/string/formatter.cr#L272-L276

If `snprintf` is C99-compliant, we don't need to compute `len` ourselves:

```crystal
len = LibC.snprintf(nil, 0, format_buf, float)
temp_buf = temp_buf(len + 1) # include space for '\0'
LibC.snprintf(temp_buf, len + 1, format_buf, float)

@io.write_utf8 Slice.new(temp_buf, len)
```

**Comment by straight-shoota** [comment]
Yeah, I came to the same conclusion 👍

**Comment by HertzDevil** [comment]
Actually, can we support the formatting flags in `Float::Printer` instead?

**Comment by straight-shoota** [comment]
Maybe. Although that falls back on `snprintf` too if grisu3 can't handle it.

#10719 is a quick fix and should be merged shortly. It can obviously be improved upon that.
