### ISSUE TITLE
Base64 references memory past end of Slice

### ISSUE THREAD

**Issue by didactic-drunk** [crystal-lang/crystal#10751]
## Bug Report

```
require "./src/sodium"
require "base64"

#sbuf = Sodium::SecureBuffer.new 16 # Ok
#sbuf = Sodium::SecureBuffer.new 32 # Ok
sbuf = Sodium::SecureBuffer.new 48 # Fail
#sbuf = Sodium::SecureBuffer.new 64 # Ok
p Base64.encode sbuf
```

```
Invalid memory access (signal 11) at address 0x7f7b8d513000
[0x56174b830a66] *Exception::CallStack::print_backtrace:(Int32 | Nil) +118
[0x56174b8217ec] __crystal_sigfault_handler +316
[0x7f7b8cfcf3c0] ???
[0x56174b8d6b2e] *Base64 +846
[0x56174b80fef1] __crystal_main +1473
[0x56174b8d8d56] *Crystal::main_user_code<Int32, Pointer(Pointer(UInt8))>:Nil +6
[0x56174b8d8bcc] *Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32 +44
[0x56174b81b386] main +6
[0x7f7b8cd760b3] __libc_start_main +243
[0x56174b80f86e] _start +46
[0x0] ???
```

Problem is [here](https://github.com/crystal-lang/crystal/blob/3f99d7d59083acd9ca8e13df4f9a96bc8a0c016c/src/base64.cr#L208).  It's walking past the `Slice` end and hitting a guard page.

```
Crystal 1.0.0 [dd40a2442] (2021-03-22)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by kostya** [comment]
This is crashed:
```crystal
buf = Sodium::LibSodium.sodium_malloc(48)
p Base64.encode(Slice.new(sbuf, 48))
```

but this ok:
```crystal
buf = Pointer(UInt8).malloc(48)
p Base64.encode(Slice.new(sbuf, 48))
```

**Comment by didactic-drunk** [comment]
Sodium uses [guarded heap allocations](https://libsodium.gitbook.io/doc/memory_management#guarded-heap-allocations).  Touching one (even for read) will crash the program.

`mmap` may (depending on options) extend allocated memory on read, so it's safe to read past existing allocated memory as long as the system can allocate more.

I assume `malloc` uses `mmap` or something similar.

Regardless `Base64` is reading past the `Slice` boundary.  It shouldn't do that and may cause very hard to find crashes when interfacing with c libraries, `mmap`, device mapped memory, `setrlimit` or other weird stuff.
