### ISSUE TITLE
Write a (FFI) binding generator

### ISSUE THREAD

**Issue by boghison** [crystal-lang/crystal#1075]
Inspired from [this](https://github.com/crabtw/rust-bindgen). It would be very useful for people who want to create bindings to C(++) libs.

**Comment by jhass** [comment]
I'd say go ahead, though I doubt this needs to be done in the standard library but would rather be only viable in its own repository. If it happens that such a project become very widely used we could think about distributing it with Crystal.

**Comment by boghison** [comment]
@jhass No, it has no place in the std IMHO. Distributions, on the other hand, sounds fun :)

**Comment by jhass** [comment]
Then I'm not sure why it needs to concern this repository :)

**Comment by boghison** [comment]
@jhass Because this will hit more users. I'd take this, but I don't have the time to take on such a project. But whoever stumbles upon this, I am sure rust-bindgen will be very helpful as a starting point :)

**Comment by kirbyfan64** [comment]
Or Python's CFFI.

**Comment by kirbyfan64** [comment]
http://cffi.readthedocs.org/en/latest/

**Comment by asterite** [comment]
We would be more than happy, and everyone would benefit, if we had this.

We started doing it some time ago [here](https://github.com/manastech/crystal_lib) but it's a big task on its own for us (me and @waj) to continue it (because we focus more on the language and standard library). In fact in my machine I continued the project a bit: I added more clang bindings and build a syntax tree so that later it can be traversed and lib code can be generated. But I always get confused with typedefs, I couldn't get that right.

My approach, if anyone wants to do this, is to use libclang (first write bindings to it in Crystal), build an AST from that and later traverse it. Once this is done we could include it as a tool distributed with the compiler, because it's very, very useful.

**Comment by boghison** [comment]
Found [this](https://github.com/neelance/ffi_gen) as well. Given the similarity between writing Crystal and Ruby, this should now be as easy as pie :)

**Comment by BlaXpirit** [comment]
I made this.
https://github.com/BlaXpirit/crystalize.py
Obviously this is not ideal, but I think it's the most complete bindings generator right now.

**Comment by boghison** [comment]
[KINDA OFF-TOPIC] I was experimenting and got a segfault when converting a c char pointer aka UInt8* to a String. Does anyone know why this is happening? (value works fine, prints 116, casting was done through `as String`).

**Comment by asterite** [comment]
@boghison casting `UInt8*` to `String` will always fail, as a String in Crystal has the bytesize and length of the string. Use [String#new(bytes)](http://crystal-lang.org/api/String.html#new%28chars%20%3A%20%3A%3APointer%28UInt8%29%29-class-method)

**Comment by boghison** [comment]
@asterite Hmm, I saw it [here](http://crystal-lang.org/docs/syntax_and_semantics/as.html).

**Comment by asterite** [comment]
@boghison Good catch. We actually use it internally, like in [here](https://github.com/manastech/crystal/blob/master/src/string.cr#L202), but of course we setup the bytes in a way that it actually works. But I agree that's not the best example. I've just updated the example. Let me know if now it's a bit more clear.

**Comment by boghison** [comment]
@asterite IMHO, ideally, the note [here](http://crystal-lang.org/docs/syntax_and_semantics/c_bindings/fun.html) could be expanded to, say, Handling strings. It would be awesome to improve the ffi guide, because writing C bindings in Crystal is already as easy as basically copy-pasting. With the right edits, we could see a lot more people interested in this :)

**Comment by ozra** [comment]
This would indeed be really cool! And a clang parsing lib +1.

**Comment by asterite** [comment]
We now have [crystal_lib](https://github.com/crystal-lang/crystal_lib) which aims to solve this. We also think that eventually the language will have this, or something similar, integrated, though we still don't know how.
