### ISSUE TITLE
Top-level assignment methods

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#10773]
Running the following snippet generates no output, meaning the method `f=` is never called. This seems very surprising to me (I even wrote this example as documentation for setter methods).

```cr
def f=(x)
  p x
end

f=("John")
```

It looks like the method can never be called, even with explicit syntax like the one in the example, or using a `::` prefix to explicitly reference a top-level method (`::x=("John")`). Tha fact that the `::` is simply ignored looks very much like a bug to me.

The question is, should a top-level assignment method be callable? If not, I would suggest that defining such a method should be an error to avoid surprises like the above example compiling, but not working in the way it is most likely intended.

Original discussion: https://github.com/crystal-lang/crystal-book/pull/508#discussion_r642644384

**Comment by asterite** [comment]
```crystal
f=("John")
```

Just to clarify, the above is the same as:

```crystal
f = ("John")
```

which explains why it's not working as you'd expect it.

In my opinion we should never disallow things like this, even if they are not callable. Just my personal preference.

**Comment by HertzDevil** [comment]
IMO `::` should force a method lookup, since that already happens on other valid variable names:

```crystal
::x      # calls top-level method `x`
::x.to_s # calls `to_s` with top-level method `x`'s return value as receiver
```

Then maybe we could allow setter methods and even operators there.

**Comment by straight-shoota** [comment]
@asterite Ah, I got confused about the receiver-less call syntax always being a variable assignment.

For top-level methods that would mean they can only be called with `::` explicit reference. And if that does not work, there is no way they can be called directly (using a proc works, though).

**Comment by straight-shoota** [comment]
I totally missed that I already opened an issue on this a while ago.

Duplicate of #8402
