### ISSUE TITLE
Test coverage with "statements", "branch", "functions" and "lines" report

### ISSUE THREAD

**Issue by paulocoghi** [crystal-lang/crystal#10794]
Hello Crystal community,

I am coming from Node.js, and it's vital to me to be able to not only test my code, but to check the coverage of my tests, both line and branch, to ensure I'm testing every logical possibility.

Is there a way to do this on Crystal currently?

Thanks!

**Comment by lbguilherme** [comment]
I have had some level of success using `gcov` before. It relies on the debugging information that Crystal already provides.

**Comment by Blacksmoke16** [comment]
@paulocoghi This would probably have been a better question for the forums: https://forum.crystal-lang.org/.

**Comment by beta-ziliani** [comment]
Hi @paulocoghi , thanks for your interest in the language. As mentioned by @Blacksmoke16 , this is the kind of questions we expect to be placed first in the forum or chat channels. But I assume this wasn't obvious from the issue tracker's templates. Do you mind sharing your experience, so we can improve it? Which template did you pick? Thanks a lot for your time!

**Comment by paulocoghi** [comment]
First, I apologize to post this question in the wrong place. I tried to enter on Crystal's Gitter, but after login in it using Github, I was not able to post anything since it's became errant, redirecting indefinitely.

About the report template, I use the report generated by Jest, where the coverage considers "statements", "branch", "functions" and "lines", like this one:

 
![jest](https://user-images.githubusercontent.com/378397/121034347-3ce76780-c7ad-11eb-9ca5-eaabdd295db8.png)

**Comment by paulocoghi** [comment]
```
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |                   
 index.js |     100 |      100 |     100 |     100 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 total
Tests:       11 passed, 11 total
Snapshots:   0 total
Time:        3.735 s, estimated 5 s
Ran all test suites.
```

**Comment by HertzDevil** [comment]
Related: #1157

**Comment by paulocoghi** [comment]
Closing in favor of #1157
