### ISSUE TITLE
Passing pointer type * to macro causes unterminated call

### ISSUE THREAD

**Issue by vgramkris** [crystal-lang/crystal#10790]
Passing pointer type with type* to a macro causes unterminated call. It works fine if Pointer(type) is passed to macro.
Tested with Crystal version 1.0.0, Debian Linux x86_64

https://forum.crystal-lang.org/t/sizeof-pointer-type-via-macro/3353

```
macro m(t)
  sizeof({{ t }})
end

print sizeof(Int32*)	# prints 8
print m(Int32)		# prints 4
print m(Int32*)		# ERROR unterminated call
print m(Pointer(Int32)) # prints 8

```

**Comment by asterite** [comment]
Thank you but this is not a bug. Read https://crystal-lang.org/reference/syntax_and_semantics/type_grammar.html specifically the Pointer section.

**Comment by Blacksmoke16** [comment]
@asterite I don't suppose it should make a diff that this is a macro call versus normal method invocation?  Or maybe the error message in this context could be improved tho?

Otherwise that was my bad @vgramkris; wasn't aware of that case.

**Comment by asterite** [comment]
Yes, it makes a difference. It's explained in the link I mention above. If we want to remove that ambiguity we need to remove all shortcuts from the language, so you would never be able to write Int32* to mean a pointer. Maybe for Crystal v2.

**Comment by asterite** [comment]
Maybe we can improve the error message, not sure.

**Comment by Blacksmoke16** [comment]
I don't think we should remove the shortcuts.  Mainly was thinking if it would be possible/worth it see that this usage is part of a macro call and either pass it thru or handle converting it to `Pointer(Int32)`.

**Comment by vgramkris** [comment]
@asterite Thanks this explains. I will keep this in mind for macro calls
