### ISSUE TITLE
Warning admonition

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#10808]
When I wrote #10008 I was unaware that `WARNING` is not one of the docs generator's supported admonitions; it should be relatively harmless to add it. The color should probably be red like `BUG` and `DEPRECATED`.

Apart from `BitArray#to_slice`, there are also docs similar to warnings for `Socket#linger=` and the summaries of the MD5 / SHA1 types.

**Comment by straight-shoota** [comment]
That sounds like a good idea. A warning is a bit stronger than a note.

This is definitely more useful than some of the other admonition keywords.
