### ISSUE TITLE
Is it possible to make .as_a?(Nil) and == nil to act the same?

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#10830]
Checking for `nil` is a common pattern and having the compiler more aware of it would be helpful.  Is is possible to have `.is_a?(Nil)` and `== nil` act the same?

Here is a simple example https://play.crystal-lang.org/#/r/bd4o

```crystal
def foo(foo : Int32 | Nil)
  return foo if foo.is_a? Nil
  100 + foo
end
  
def foo_alt(foo : Int32 | Nil)
  return foo if foo == nil
  100 + foo
end
  
puts foo(1)
puts foo(nil)

puts foo_alt(1)
puts foo_alt(nil)
```

One of these causes a compilation error but I think they accomplish the same thing.  Is there a way to special case this in the compiler and have it not throw a compiler error.

**Comment by Blacksmoke16** [comment]
One main difference is you can override `==`, but you can't override `.nil?` or `.is_a?`.

**Comment by wontruefree** [comment]
That is a really good point.  Even with `.nil?` and `.not_nil?` or something it is just way more common to use `== nil` or `!= nil`.

**Comment by Blacksmoke16** [comment]
@wontruefree `.nil?` is equivalent to `.is_a?(Nil)` if you weren't aware.

**Comment by Fryguy** [comment]
> it is just way more common to use == nil or != nil

In Ruby, in particular if you use rubocop for linting, you are generally encouraged to use `.nil?` over `== nil`, so in Ruby circles I'd wager that it's less common.

https://docs.rubocop.org/rubocop/cops_style.html#stylenilcomparison

**Comment by wontruefree** [comment]
This is mostly a usability request. `.nil?` totally works and I didnt think about the overloading of `==`.

**Comment by HertzDevil** [comment]
Also: you can write `&.nil?` in Crystal and `&:nil?` in Ruby. For equality you must write `&.==(nil)` and no such short option exists in Ruby.

**Comment by straight-shoota** [comment]
This is also covered in the docs, btw.

https://crystal-lang.org/reference/syntax_and_semantics/nil_question.html
