### ISSUE TITLE
Formatting with `decimal_places` breaks with scientific notation

### ISSUE THREAD

**Issue by beta-ziliani** [crystal-lang/crystal#10841]
The code `puts "#{0.00001.format(decimal_places: 7)}"` prints `1.0e-5000`, simply doing a naive padding. In this case, it should avoid scientific notation all together.

Reproducible with 1.0 and 1.1.0-dev (here on an Intel MacOS).

**Comment by straight-shoota** [comment]
I suppose we'd then need to customize the stringifier to show values outside of `1e14..1e-4` (IIRC those are the boundaries for scientific notation?) in decimal notation.
