### ISSUE TITLE
Time + 1.month is not working like expected

### ISSUE THREAD

**Issue by wonderix** [crystal-lang/crystal#10869]
## Bug Report

The following test fails with crystal 1.0.0-dev [89f0f8389] and stdlib 037a1ec96890bef667488cfa07625c9712d228b2 under MacOS in CET timezone.

```crystal
(Time.local(2021, 7, 1) + 1.month).should eq Time.local(2021, 8, 1)
```

it produces `2021-07-31`. The following test succeeds:

```crystal
(Time.local(2021, 6, 1) + 1.month).should eq Time.local(2021, 7, 1)
```

**Comment by asterite** [comment]
Works for me and play.crystal-lang.org:

https://play.crystal-lang.org/#/r/bgo1

**Comment by straight-shoota** [comment]
@asterite The time zone is important. Reproducing example:

```cr
Time.local(2021, 7, 1, location: Time::Location.load("CET")).shift(months: 1) # => 2021-07-31 00:00:00.0 +02:00 CET
```
