### ISSUE TITLE
Regression in docs search

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#10872]
## Bug Report

* Navigate to https://crystal-lang.org/api
* Search for `each_with_index` (or any method really)
* Click on one of the results
* See that you taken to that method's definition
* Now navigate to https://crystal-lang.org/api/master
* Search for something else
* Click on one of the results again
* See that you get taken to that type's page, but the anchor tag is `undefined` and it doesn't take you to the method definition

**Comment by straight-shoota** [comment]
This is caused by #10109 which removed the `id` property on features in the doc generator JSON output.

It seems this was just a duplicate of `html_id`, so we can use that instead in the search implementation.
