### ISSUE TITLE
Error: can't cast ExampleClass(T) to ExampleClass(T)

### ISSUE THREAD

**Issue by didactic-drunk** [crystal-lang/crystal#10882]
Starting with commit `e7b46c40739902db70a2dceebd09caf1a7c70553` [jennifer.cr](https://github.com/imdrasil/jennifer.cr/issues/373) fails to compile.

`crystal spec`
```
In src/jennifer/adapter/base_sql_generator.cr:269:27

 269 | self.select(cte_query.as(QueryBuilder::ModelQuery))
                   ^
Error: can't cast Jennifer::QueryBuilder::ModelQuery(T) to Jennifer::QueryBuilder::ModelQuery(T)
```

**Comment by asterite** [comment]
We should probably revert https://github.com/crystal-lang/crystal/pull/10522 or find a fix for it before releasing 1.1
