### ISSUE TITLE
pp! doesn't works with multi return functions

### ISSUE THREAD

**Issue by rishavs** [crystal-lang/crystal#10893]
using pp! with any multi return function throws an exception.

For eg.
`pp! x  = ... `
works, but
`pp! x, y = ....`
doesn't.

I found this while trying to work with the JWT library which uses the multi returns for JWT.decode method.
```
 32 | pp! payload1, header1 = JWT.decode(id_token, key1, JWT::Algorithm::HS256)
          ^-------
Error: undefined local variable or method 'payload1' for Digglu:Module
```
My setup is
```
Crystal 1.0.0 [dd40a2442] (2021-03-22)
LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```

Even if we do no want to fix the behavior, IMO the error message should be updated to call this out as the error description is not helpful at all.

**Comment by asterite** [comment]
What happens if you use parentheses around the multi assign? If it works, then this works as expected.

**Comment by rishavs** [comment]
It gives an `Error: unexpected token: }` error. 
Here is a quick play i rustled up showing this issue https://play.crystal-lang.org/#/r/bh3h

**Comment by asterite** [comment]
I meant pp!(...)

**Comment by rishavs** [comment]
Sorry, do you mean like this?
`pp! (x,y) = multi()`

It throws
```
syntax error in eval:14
Error: unterminated parenthesized expression
```

**Comment by Blacksmoke16** [comment]
@rishavs He means `pp!(x, y = multi)`.

**Comment by asterite** [comment]
No... pp!(a, b = exp). Though I guess it wont work, those will be considered as a, an argument, the assign, another argument. This cant be fixed because there's nothing to fix.

**Comment by asterite** [comment]
Sorry for the brevity, Phone. But this cant be fixed.

**Comment by rishavs** [comment]
tried
`pp! (x, y = multi())`
It is giving
```
syntax error in eval:14
Error: unterminated parenthesized expression
```

**Comment by rishavs** [comment]
No worries, closing this issue then. Its not a blocker anyway. just a bit of QoL.

**Comment by jhass** [comment]
Fwiw https://play.crystal-lang.org/#/r/bh57

**Comment by HertzDevil** [comment]
Related: https://github.com/crystal-lang/crystal/issues/7707#issuecomment-752991389
