### ISSUE TITLE
`file_spec.cr` fails in Alpine linux

### ISSUE THREAD

**Issue by beta-ziliani** [crystal-lang/crystal#10895]
Two specs of `file_spec.cr` are failing (see below). The setup is the following:

 * Docker image with Alpine [latest](https://hub.docker.com/r/arm64v8/alpine/) for Arm64, emulated with Qemu via Docker Desktop in an x86 box.
 * LLVM 11.1
 * [crystal-dev](https://github.com/crystal-lang/crystal/commit/bf5aea2af543895d2686f8661ea1db82ce78ec77)

The rest of the specs pass (compiler and std).

```
Failures:

  1) File raises when reading a file with no permission
     Failure/Error: expect_raises(File::AccessDeniedError) { File.read(path) }

       Expected File::AccessDeniedError but nothing was raised

     # spec/std/file_spec.cr:862

  2) File .touch raises if file cannot be accessed
     Failure/Error: expect_raises(File::Error, "Error setting time on file: '/bin/ls'") do

       Expected File::Error but nothing was raised

     # spec/std/file_spec.cr:1256
  ```

**Comment by straight-shoota** [comment]
This looks very suspicious. I doubt it's an error on our side. The CI job [musl-test-stdlib on aarch64](https://github.com/crystal-lang/crystal/runs/2993110439) succeeds. It probably doesn't use LLVM 11.1 and Alpine latest but I can't see how that would make a difference for those specs. A random filesystem glitch looks more likely.
Can someone test this on native hardware?

**Comment by jhass** [comment]
Just ping me whenever you want access to the ARM build box :)

**Comment by beta-ziliani** [comment]
this is odd. I will come back to this, but if we have a happy CI that's good enough for now. I'm mostly interested in fixing another bug.

**Comment by beta-ziliani** [comment]
This was a problem of permissions in the filesystem, unrelated to Crystal.
