### ISSUE TITLE
Allow `Enumerable#tally` to accept a block

### ISSUE THREAD

**Issue by caspiano** [crystal-lang/crystal#10921]
## Feature Request

- Is your feature request related to a problem? Please describe clearly and concisely what is it.

It's relatively common to want to tally objects in an `Enumerable` after some form of transformation.

- Describe the feature you would like, optionally illustrated by examples, and how it will solve the above problem.

```crystal
["a", "A", "b", "B"].tally(&.downcase) # => {"a" => 2, "b" => 2}
["a", "A", "b", "B"].tally # => {"a" => 1, "A" => 1, "b" => 1, "B" => 1}
```

- Describe considered alternative solutions, and the reasons why you have not proposed them as a solution here.

It's possible to `map` before `tally`, but this is a bit inefficient

- Does it break backward compatibility, if yes then what's the migration path?

Nope.

**Comment by asterite** [comment]
Just a note that this doesn't exist in Ruby. I'm not sure using the block for mapping the value is the most intuitive behavior. Maybe in this case you can count things manually? I'm just worries that we add this and eventually we realize we could have used the block in a different way.

**Comment by HertzDevil** [comment]
In Elixir these are called `Enum.frequencies/1` and `Enum.frequencies_by/2` respectively. Adding the `_by` might make things read better too.

**Comment by caspiano** [comment]
+1 on `tally_by`
