### ISSUE TITLE
Make `NamedTuple.new.to_h` return `{} of Symbol => NoReturn`

### ISSUE THREAD

**Issue by caspiano** [crystal-lang/crystal#10939]
`NamedTuple.new.to_h` returns `{} of NoReturn => NoReturn`

I believe a more workable result of this would be `{} of Symbol => NoReturn`

Here's a real-world example (yes, I know you're not meant to use `NamedTuple` \</self-flaggelation\>)

```crystal
a = {a: nil, b: "hi", c: :hmm, d: Time.utc}
b = NamedTuple.new

def do_the_thing(h)
  h.to_h.transform_values do |v|
  case v
  when String then v
  when Symbol then v.to_s
  end
  end.compact
end

do_the_thing(a) # {:b => "hi", :c => "hmm"} : Hash(Symbol, String)
do_the_thing(b) # {} of NoReturn => NoReturn

# With the proposed change, the example still yields values of type `NoReturn`
do_the_thing(b) # {} of Symbol => NoReturn
```

### Crystal Version

```shell-session
Crystal 1.0.0 [dd40a2442] (2021-03-22)

LLVM: 6.0.1
Default target: x86_64-apple-macosx
```

- - - -

Edit: changed `{} of Symbol => Nil` to `{} of Symbol => NoReturn`, thanks @lbguilherme

**Comment by Blacksmoke16** [comment]
As you already pointed out, this isn't really the use case for Named Tuples.  I'm not really this would even be worth it.

**Comment by HertzDevil** [comment]
Making it return `{} of Symbol => Nil` will _not_ change the return types as you suggested; `NamedTuple.new.each` will yield nothing to the provided block, so the entire body of `transform_values` will be untyped. Both that and `{} of Symbol => NoReturn` will give `Hash(Symbol, NoReturn)`.

Related: #9923

**Comment by caspiano** [comment]
@Blacksmoke16 People will invariably run into things like this.
I think saving people from a WTF moment is more important in the first place than having a set of implicit language conventions that the user will eventually discover through engagement.

**Comment by HertzDevil** [comment]
Actually `compact` is doing the right thing here:

```crystal
typeof({:a => nil}.compact) # => Hash(Symbol, NoReturn)
typeof([nil].compact)       # => Array(NoReturn)
```

You **cannot** make the value type something other than `NoReturn` by using `Nil` values instead of `NoReturn`.

**Comment by lbguilherme** [comment]
`NamedTuple.new.to_h` would make more sense to return `Hash(Symbol, NoReturn)` instead of `Hash(NoReturn, NoReturn)` as the keys of named tuples are always symbols, even when there are none. Either way, the value type shouldn't be `Nil` and this is a very edgy/unusual use case.

Still, something like this would be a breaking change and is only possible for 2.0.
