### ISSUE TITLE
Strange behavior of Path.relative_to

### ISSUE THREAD

**Issue by webhive** [crystal-lang/crystal#10946]
## Path.relative_to work wrong 

It always add redundant ``../`` to the top of result path

So here is a test code fir simplest trivial case.
This code also work same wrong way if call ``.expand(home: true)`` to both target and base

```
BASE = Path.["~/.profile"]
TARGET = Path.["~/.aliases"]

puts "#{BASE} #{TARGET.relative_to(BASE)}"
```
So my result is:

```
~/.profile ../.aliases
```

According documentation [here](https://crystal-lang.org/api/1.0.0/Path.html#relative_to?(base:Path):Path?-instance-method) ``normalized paths base.join(target.relative_to(base)) is equivalent to target.``

But it's clearly visible what ``~/.aliases`` not equal to ``../.aliases``

Anyway lets check it with test code from documentation

```
BASE = Path.["~/.profile"]
TARGET = Path.["~/.aliases"]

puts "base: #{BASE}\ntarget:#{TARGET}\n#{BASE.join(TARGET.relative_to(BASE))}"
```

Result is 

```
base: ~/.profile
target:~/.aliases
~/.profile/../.aliases
```

So again ``~/.profile/../.aliases`` is not the same as ``~/.aliases``

### My environment 

```
$ crystal -v
Crystal 1.0.0 (2021-03-22)

LLVM: 11.1.0
Default target: x86_64-apple-macosx
```

**Comment by lbguilherme** [comment]
I didn't get it. `~/.profile/../.aliases` is the same as `~/.aliases`.

**Comment by HertzDevil** [comment]
The docs only say "equivalent to", not "same as"; there is `Path#normalize` which should get what you want.

**Comment by straight-shoota** [comment]
The behaviour is correct and intended.

The relative path from `~/.profile` to `~/.aliases` is `../.aliases`. Joining that to the original base results in `~/.profile/../.aliases` which is equivalent to `~/.alisases`. It's not literally the same as the original target on purpose. `.profile/..` may or may not be equivalent to `.`. Removing it could potentially result in a different path if symbolic links are involved. So it's not redundant but essential for correctness.
`Path` values are purely virtual and not connected to any file system, so there's no way to check if that would be the case. If you want a normalized path, just call `Path#normalize` on the result.

**Comment by webhive** [comment]
Here is example why I suppose it it incorrect
May be theoretically it is, but in practice not - it is not the same file. At least existing behavior doing it useless. I expect programming language should resolve real tasks. 

![image](https://user-images.githubusercontent.com/1154997/125601434-5da55b1d-8b25-4e54-b3b1-1eb0d1b62c6b.png)

So may be this ``relative_to`` only work with directories where such behavior is correct?

```
BASE = Path.["~/"]
TARGET = Path.["~/.config/neovim"]

puts "base: #{BASE}\ntarget:#{TARGET}\n#{BASE.join(TARGET.relative_to(BASE))}"
```
Result is correct:

```
base: ~/
target:~/.config/neovim
~/.config/neovim
```

But when used with regular files it work wrong way

**Comment by webhive** [comment]
> `Path` values are purely virtual and not connected to any file system, so there's no way to check if that would be the case. If you want a normalized path, just call `Path#normalize` on the result.

So in this case I expect ``relative_to`` methods should be moved to ``Dir`` module, where it has some meaning, to avoid confusion.

**Comment by webhive** [comment]
> @HertzDevil The docs only say "equivalent to", not "same as"; there is `Path#normalize` which should get what you want.
> @straight-shoota If you want a normalized path, just call `Path#normalize` on the result.

Yes - it work. Thanks!

**Comment by webhive** [comment]
Hmm about ``Path#normalize`` yes - it work well, but normalize not the result i want - I need relative path. Real relative path.
My task was to move file from one folder to another
For example:

```
BASE = Path.["~/.config/neovin/init.vim"]
TARGET = Path.["~/.vim/init.vim"]

puts "#{BASE} -> #{TARGET.relative_to(BASE)}"
```

So I am calculating relative path and this path pointing to place up to one level of desired.

``~/.config/neovin/init.vim -> ../../../.vim/init.vim`` 

Yes -  ``Path#normalize`` resolved it but from point of view of my shell this path is incorrect.

**Comment by webhive** [comment]
> @straight-shoota 
>  Removing it could potentially result in a different path if symbolic links are involved. So it's not redundant but essential for correctness.

Irony of situation is what I got an issue trying to symlink files and found it in wrong place (up to one directory).

**Comment by HertzDevil** [comment]
You probably need to call `Path#expand` on both the base and the target before using `#relative_to`, while paying attention to the working directory.

**Comment by webhive** [comment]
> You probably need to call `Path#expand` on both the base and the target before using `#relative_to`, while paying attention to the working directory.

Tested it with no difference. The only difference is regular file or directory. Last part of path always designated as directory and for such assumption this behavior is correct. But for regular file it is great confusion.

Just checked Ruby equivalent - there relative path calculation work same way as crystal.

**Comment by straight-shoota** [comment]
> So may be this `relative_to` only work with directories where such behavior is correct?

Kind of, yes. When resolving a path relative to another one, it is assumed that the base path is traversable.

I suspect you might actually be looking to build a path relative to the base's parent path when the base is a file.
