### ISSUE TITLE
Install broken (Crystal v1.0.0 not found and Crystal 1.1 is seg fault)

### ISSUE THREAD

**Issue by Nicolab** [crystal-lang/crystal#10949]
## Bug Report

Hello,

On the website https://crystal-lang.org/, the last Crystal version is v1.0.0, but Crystal v1.0.0 is not found http://download.opensuse.org/repositories/devel:/languages:/crystal/xUbuntu_18.04/

The last release is v1.1.0 but this version doesn't work #10948  (Segmentation fault) 

So https://crystal-lang.org/install.sh is broken

**Comment by straight-shoota** [comment]
As a workaround you can install the package from a newer repository. It should work on 18.04 as well.

```shell
wget -O- https://crystal-lang.org/install.sh | DISTRO_REPO=xUbuntu_20.04 bash
```

**Comment by Nicolab** [comment]
Unless I'm mistaken, there is no v1.0.0 in the repo of xUbuntu 20.04 http://download.opensuse.org/repositories/devel:/languages:/crystal/xUbuntu_20.04/all/

**Comment by straight-shoota** [comment]
The simple workaround described in https://github.com/crystal-lang/crystal/issues/10948#issuecomment-881057161 seems to fix this. All packages should be working now.

@Nicolab OBS only serves the latest release, that is 1.1.0 by now.

**Comment by Nicolab** [comment]
Ok thanks
