### ISSUE TITLE
Memory error on any level of macro recursion

### ISSUE THREAD

**Issue by syeopite** [crystal-lang/crystal#10941]
## Bug Report

Recursive macros appears to cause a memory error on any level of macro recursion.

Take this code here.
```crystal
macro recursion_test(finished=false)
  if {{finished}} == true
  else
    recursion_test(true)
  end
end

recursion_test()
```
Theoretically it should call itself once and then exit. However, instead of the expected result it produces a memory error.

[error.txt](https://github.com/crystal-lang/crystal/files/6812868/error.txt)
```
[1/13] Parse                             
Parse:                             00:00:00.000049442 (   0.59MB)
Invalid memory access (signal 11) at address 0x7ffd35fa5ca0
[0x556d7dfbf376] ???
[0x556d7df0e2c2] __crystal_sigfault_handler +514
[0x7fdf5a014870] ???
[0x7fdf5a02d604] ???
[0x7fdf5a02d6b8] ??? (3 times)
[0x7fdf5a04241a] GC_generic_malloc_many +858
[0x7fdf5a0429d3] GC_malloc_kind +307
[0x556d7d926e86] ???
[0x556d7d903b5b] ???
[0x556d7d901729] ???
...
```

I don't really know much about the internals of Crystal but it seems to happen at the parsing stage, invalid syntax that's present anywhere in the code isn't detected whatsoever.

**Comment by HertzDevil** [comment]
The `recursion_test` macro is fully expanded before it is evaluated, so `{{finished}} == true` will never short-circuit.

**Comment by syeopite** [comment]
Oh. That makes sense. Thank you!
