### ISSUE TITLE
Overloaded Slice.new(Int) should not be acceptable for a union of primitive types

### ISSUE THREAD

**Issue by vgramkris** [crystal-lang/crystal#10980]
Slice.new(Int) should not accept union of primitive types

@straight-shoota clarified that this is a bug.

Sample code, exception & clarification is in this forum post https://forum.crystal-lang.org/t/slice-union-type-puts-exception/3542

```
a = Slice(Int32|UInt8).new(4)
a[0] = 1
a[1] = 2
puts a     #=> exception
```

**Comment by straight-shoota** [comment]
I presume this patch should fix this:
```diff
--- c/src/slice.cr
+++ i/src/slice.cr
@@ -83,7 +83,7 @@ struct Slice(T)
   # slice # => Bytes[0, 0, 0]
   # ```
   def self.new(size : Int, *, read_only = false)
-    {% unless T <= Int::Primitive || T <= Float::Primitive %}
+    {% unless (T <= Int::Primitive || T <= Float::Primitive) && ! T.union? %}
       {% raise "Can only use primitive integers and floats with Slice.new(size), not #{T}" %}
     {% end %}
```

However, I'm not sure if `(Int32 | UInt8) <= Int::Primitive # => true` is correct in the first place. At least in this context, it's unexpected.
