### ISSUE TITLE
Add spec flag to fail when `focus: true`

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#10989]
The example/group option `focus: true` is a development helper which allows selecting only specific examples/groups to run. It must not be used when the intention is to run all specs explicitly. This is typically the case in CI for example. If there is any `focus: true` in the spec suite, only that example/group runs and the entire spec run counts as successful if only that selection succeeds. Thus the result can be misleading and incorrect.
It's easy to miss if `focus: true` was unintentionally checked in from development (see #10988).

I'd like to have an option to make tell spec that `focus: true` is not intended and should be disallowed. This configuration could be used for CI or local tests that are not intended to run any selective parts, but the entire suite. If there is any `focus: true`, the entire spec suite would fail with this option.

My proposal would be a CLI flag `--fail-on-focus` and maybe also an environment variable `SPEC_FAIL_ON_FOCUS`.

As an alternative, a git hook or separate CI test that check for literal `focus: true` in the commit diff could also help avoid accidental check-ins. But that probably makes things unnecessarily complicated and won't help for cases where you want to run `make test` locally and make sure there are no example filters active.

**Comment by Sija** [comment]
IMO that's what the linters - like ameba - are for. Adding flag for every dubious practice doesn't seem feasible.

**Comment by straight-shoota** [comment]
`focus: true` is not a dubious practice. But it's clearly a feature that makes only sense in certain development contexts. Since it greatly alters the behaviour of the entire spec program, I think it is of paramount importance to be able to opt-out of that.

**Comment by asterite** [comment]
I think this should be really easy to implement too, compared to a linter rule. And you would never want to have focus on CI, it's not a matter of taste (unlike lint rules)

**Comment by Fryguy** [comment]
Alternatively, what about a `--ci` flag, which indicates that the test suite is running in a CI environment?  In this way, we aren't creating a flag entirely for one purpose, but something more general that could potentially be used for other things.

Taking this idea further, we could avoid the flag entirely and just look for the presence of a CI environment variable, which nearly all public CI systems set to true <sup>[[1](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables)] [[2](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables)] [[3](https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables)]</sup>

**Comment by HertzDevil** [comment]
IMO things like this should be done in the pre-commit hook; just because this repo doesn't need `focus: true` doesn't mean shards cannot, because they can be deliberately added to shorten running times and highlight specific test failures.

**Comment by Fryguy** [comment]
@HertzDevil In those cases that seems like the wrong usage of `focus: true`, which IMO is more meant for development purposes.  I would expect if a shard wanted to highlight tests, and/or exclude them, they could use spec's tag feature instead.

**Comment by straight-shoota** [comment]
I don't think it's a good idea to make this implicitly depend on the environment. A good counter use case for that would be debugging an issue in CI for which I specifically want to run the specs with `focus: true`. Using a dedicated flag or environment variable, this is easy to do. Changing that should not require fiddling with the CI environment and possibly causing other side effects.
For the same reason I don't think this makes sense as a pre-commit hook. 
Another reason for that would be, I often commit WIP changes with focussed specs and even push development branches to the remote repo. I don't want to be prohibited from committing `focus: true` (even though I could override that). I just want to configure specs that it fails when I do that.

**Comment by straight-shoota** [comment]
Another, related use case came to my mind: I'm working on something and have a couple of interesting specs focused. Once those are all green, want to run *all* specs (not just the focussed ones) to make sure there are no unexpected breaks to other specs I didn't have in focus. In case that hits something, I have to iterate again and probably do another round of focus spec runs (now including the broken specs).
So I have to go back to the previously focussed specs while they need to be unfocused in between. I typically do something like `s/focus: true/focus: false/g` for that (and vice versa).
Having a flag to ignore any `focus: true` would be helpful for that. Then I could explicitly run without focus in between, and immediately return to running only the same focussed specs as before.

**Comment by straight-shoota** [comment]
Having it the issue with unintentional `focus: true` again (#12962), I'd like to make sure this doesn't happen again.

Considering my previous comment, I would adjust the original proposal to a config option `--focus` with three values:
* `focus`: Current behaviour, only run specs with `focus: true`. This should be the default.
* `fail`: Fail any spec with `focus: true`. This should be used in CI. Perhaps this could be the default when `CI=true` (still allowing override if you explicitly want a different behaviour).
* `ignore`: Run all specs as if none has `focus: true`. This is useful for development.

**Comment by HertzDevil** [comment]
How about still running the focused specs as usual but exiting with a non-zero status?

**Comment by straight-shoota** [comment]
I suppose that could also be a valid option 🤔 Basically it's about whether `fail` should generally behave like `focus` or `ignore` (apart from obviously exiting with non-zero if there's any `focus: true`). Not sure which one makes more sense...

**Comment by straight-shoota** [comment]
The major use case for `--focus=fail` is in CI. And I think there it makes sense to run all specs. `focus: true` isn't intentional to run only specific ones. It's just a remnant of development work. But in CI it's good to run all specs so that you would be informed about failures in other spec (that are not focused).

**Comment by straight-shoota** [comment]
... or maybe I explicitly want the focused specs to run in CI as I had previously written in https://github.com/crystal-lang/crystal/issues/10989#issuecomment-885792933 🤔 Then I'd like the focus to apply, but the spec run to fail even if all are successful.
