### ISSUE TITLE
Yield broken inside macro yield?

### ISSUE THREAD

**Issue by RX14** [crystal-lang/crystal#10984]
I was writing a `record` which had a custom method which used yield, and hit an error. I suspect it's due to using yield inside macro `{{yield}}`, since both are required to reproduce.

```
macro transparent_macro
  {{yield}}
end

def method(a : Float64, b : Float64)
end

transparent_macro do
  def map(&)
    method(yield(1.0), 1.0)
  end
end

map { |a| a * 2 }
```

**Comment by straight-shoota** [comment]
It appears that somewhere in the macro expansion the parenthesis of `yield` gets lost, thus the method argument becomes `yield 1.0, 1.0`.

```cr
macro transparent_macro
  {{yield}}
end

transparent_macro do
  def map
    p! yield(1.0), 2.0 # => {1.0, 2.0}
  end
end

map { |*a| a }
```

**Comment by RX14** [comment]
ah, a `ToSVisitor` bug... makes sense

**Comment by Blacksmoke16** [comment]
Workaround seems to do like:

```cr
transparent_macro do
  {% begin %}
    # Code goes here
  {% end %}
end
```

**Comment by RX14** [comment]
you can also add () around yield like `(yield foo)`
