### ISSUE TITLE
Char literal with single backslash inside macro def breaks the parser

### ISSUE THREAD

**Issue by lbguilherme** [crystal-lang/crystal#10991]
```
macro borked # Error: unterminated macro
  '\\'
end
```

Very similar to #10745.
Causes https://github.com/Papierkorb/toka/issues/3.

This is a regression, the same code works on Crystal 1.0.0.

**Comment by straight-shoota** [comment]
Yeah, this looks like a regression introduced by #10799. Before that, it was already broken for string literals, though.
