### ISSUE TITLE
{{ @type.id }} changed from "main" to "top_level" with Crystal 1.1.0

### ISSUE THREAD

**Issue by lbguilherme** [crystal-lang/crystal#10992]
This change https://github.com/crystal-lang/crystal/pull/10682/files#diff-bb39a22cb4b0d7bfedfc96429c070ad88e18c7723f65310f0435945a73ef688cR126 made `{{ @type.id }}` change value from `"main"` to `"top_level"`.

This breaks at least one shard that used to work on Crystal 1.0.0: https://github.com/spoved/spoved.cr/blob/master/src/spoved/logger.cr#L26

Repro:

```cr
p {{ @type.id.stringify }}
```

**Comment by beta-ziliani** [comment]
Sorry about that @lbguilherme

**Comment by wontruefree** [comment]
should this name change be planed for something like `2.0`?
