### ISSUE TITLE
`File.match?` does not accept `Path` type as argument

### ISSUE THREAD

**Issue by alexherbo2** [crystal-lang/crystal#11014]
[File]:

```
File.match?(pattern : String, path : Path | String) : Bool
```

[File]: https://crystal-lang.org/api/master/File.html

**Comment by fishnibble** [comment]
@straight-shoota I'm new to the project. I'm interested in picking this up. Would this be a good first fix?

**Comment by straight-shoota** [comment]
Yes, this should be a good one. I suppose it's literally just a simple `to_s` in the match method and adding an appropriate spec.

**Comment by fishnibble** [comment]
@straight-shoota  on it
