### ISSUE TITLE
Docs missing for `v1.1.1`

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#11027]
## Bug Report

https://crystal-lang.org/api/1.1.1/ is returning 404

**Comment by asterite** [comment]
I think it's not been officially released yet?

**Comment by Sija** [comment]
There's a tagged [release](https://github.com/crystal-lang/crystal/releases/tag/1.1.1), homebrew package got [updated](https://github.com/Homebrew/homebrew-core/pull/81932), thus I've got a feeling it is released ;)

**Comment by asterite** [comment]
Where's the blog post announcement? :-)

I just wouldn't rush too much, there are a lot of steps involved here, so this is not a bug, just something pending to be done.

**Comment by Sija** [comment]
Agreed, I just wanted to make sure they're not (gonna be) missing :)

**Comment by beta-ziliani** [comment]
exactly, it takes one or two days to get the full process done (if nothing goes wrong). 🏗️

**Comment by beta-ziliani** [comment]
we will never miss the step of the announcement. so if you find something missing *after* the announcement, then it definitively is a bug
