### ISSUE TITLE
Access namespaces defined explicitly on a given `XML::Node`

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#11037]
The stdlib currently provides a few methods on `XML::Node` to interact with that node's namespaces.  The main two being:

1. `#namespace`
2. `#namespace_scopes` (and `#namespaces`, but that uses the same underlying C method as `#namespace_scopes` under the hood)

However the way these methods work makes it so you can't get _only_ the namespaces explicitly defined on a given node.  `#namespace` only returns a single namespace, and the other two methods will include parent namespaces.  I propose we add new method like `#node_namespaces` or something those lines that would an array of _only_ the namespaces defined on an element.

The implementation of this would prob look something like:

```cr
class ::XML::Node
  def node_namespaces : Array(Namespace)
    namespaces = [] of Namespace

    return namespaces unless (ns = @node.value.ns_def)

    while ns
      namespaces << Namespace.new(document, ns)
      ns = ns.value.next
    end
    namespaces
  end
end
```

Happy to make a PR if this gets the :+1:.

_Originally posted by @Blacksmoke16 in https://github.com/Blacksmoke16/oq/issues/85#issuecomment-888759624_

**Comment by asterite** [comment]
Can you check how this is accomplished in Ruby's nokogiri?

**Comment by Blacksmoke16** [comment]
@asterite https://nokogiri.org/rdoc/Nokogiri/XML/Node.html#namespace_definitions-instance_method.  Looks to be essentially what my implementation looks like.  I do like their name better so I'd probably just go with that.

**Comment by asterite** [comment]
Oh, yes, sorry, I was more referering to "How is this accessible in nokogiri so we can use the same name"
