### ISSUE TITLE
Generated Docs Code Syntax Error

### ISSUE THREAD

**Issue by trollmao** [crystal-lang/crystal#11035]
## Bug Report

- Run: `crystal docs`

- Open: `docs/index.html`

Here is what I see:

![docserror1](https://user-images.githubusercontent.com/88042940/127399390-360bab16-da7d-4970-83f1-71d757e7c92b.png)

It renders fine with GitHub markdown syntax, but I believe whatever markdown syntax Crystal uses thinks code wrapped in back-ticks is code and then ignores triple back-ticks afterwards.

![docserror2](https://user-images.githubusercontent.com/88042940/127399814-16cc4226-ce08-4b22-8e74-eb8e822cd7f3.png)

I've tried to find relative code that causes this to happen, but no results surfaced.

**Comment by asterite** [comment]
Duplicate of https://github.com/crystal-lang/crystal/issues/4613
