### ISSUE TITLE
Improve development experience by featuring a quick-compile mode

### ISSUE THREAD

**Issue by phuongnd08** [crystal-lang/crystal#11036]
## Discussion

- What aspect of the language would you like to see improved?
Developer Experience on large projects

- What are the reasons?
If developers are happy, crystal will be used in more projects

- Include practical examples to illustrate your points.
Given I'm working on large project, I need to modify a part of the project, then run a test to confirm the new behavior. If I wait for 0.3s to see my result, in general I'm happy and not bother very much. But if I need to wait 30s to see my result, then in general I will feel annoyed and I will try to avoid the language in future projects

- Optionally add one (or more) proposals to improve the current situation.
One thing the ruby community did is that they develop a bunch of techniques to keep the feedback loop short. For instance, there was zeus and spring, what they do is they preload a great deal of the app in a background process. When the developer modifies the app, then spring/zeus fork a new process the inherit the preloaded state, and load the delta, and then execute the required command. This way it's pretty fast to see the result during development. If you had to load everything from the scratch, the result will come much much slower

I think what can be improved in crystal is to allow a possibility of such an approach. I mean I don't care if my CI takes 1 hour or 2 hours to build my project. But I certainly can't accept if I do not get feedback on my code change in 2 seconds. Perhaps crystal can feature a quick-compile mode where the code won't be as performant but developers can observe the result of new feature immediately (imagine: simply swap in ruby as an execution engine to test crystal code in development)

**Comment by Blacksmoke16** [comment]
Related: https://github.com/crystal-lang/crystal/issues/10568.

**Comment by asterite** [comment]
Hi!

Yes, we all want that. With interpreted mode this will improve the situation but I don't know by how much.

If there's no concrete proposal here I think we should close this issue because there's nothing actionable.
