### ISSUE TITLE
Comparison operator doesn't statically resolve result type for floats

### ISSUE THREAD

**Issue by wolfgang371** [crystal-lang/crystal#11042]
This is just a minor thing, but anyhow:

```crystal
p typeof(0<=>0) # Int32
p typeof("foo"<=>"bar") # Int32
p typeof(0.0<=>0.0) # (Int32 | Nil)
```

I came across this when using `.sort` on an array of tuples with a weighted sort criteria like `2*(x[0]<=>y[0])`. This works fine for strings and ints as above, but not for floats; you have to manually cast the `nil` away (`.not_nil!`).

I use crystal 1.1.1 on Ubuntu 18.04.

**Comment by Blacksmoke16** [comment]
Float values could be `NaN`, which aren't comparable which is why it could be `nil` in that case.

**Comment by wolfgang371** [comment]
of course, didn't think about that. thanks, that was quick!
