### ISSUE TITLE
Invalid memory access (signal 11) at address XXX / pretty_inspect problem

### ISSUE THREAD

**Issue by petr-fischer** [crystal-lang/crystal#11060]
When I run this Crystal code (it's simplified from our real code base):

```crystal
class My0 
end

{% for n in 1..1000 %}
class My{{n.id}}
    property prop : My{{(n - 1).id}}?
end
{% end %}

def test(entity_class : T.class) : Nil forall T
      result = [] of T
      result.pretty_inspect
end

test My123
```

with `crystal run test.cr`, then this segfault occurs:

```
Invalid memory access (signal 11) at address 0x7ffc21623a18
[0xdb3566] ???
[0xdb3533] ???
[0x1e46ebf] ???
```

The problem is `pretty_inspect` (with `inspect`, compilation is OK).

Environment:
Ubuntu 21.04

Crystal version:
```
Crystal 1.1.1 [6d9a1d583] (2021-07-26)

LLVM: 10.0.1
Default target: x86_64-unknown-linux-gnu
```

**Comment by straight-shoota** [comment]
A compiler with debug information shows more details, it seems to be hitting a very deep recursion / iteration.

Might be related to #9880 (#10890 does not fix it, though).

**Comment by petr-fischer** [comment]
@straight-shoota How about distributing a debug version of the compiler as well in default packages OR prebuild the debug version in some docker container (next to the ones that are already on the docker hub)?

**Comment by straight-shoota** [comment]
You can get a debug version of the compiler by running `make` in the `-build` docker image. Maybe we could publish a separate image for that. But that's just more stuff to keep track of 🙈 And it's really easy to build if you need it. Ideally of course, nobody except compiler developers should need a debug version, but I suppose we're probably many bugs away from that.

**Comment by petr-fischer** [comment]
Update (Interesting fact): the code above still segfaults on the latest Crystal 1.4.1 on the Ubuntu 22.04 LTS, but I tried it on the **FreeBSD**, and it works (no segfaults)!

```
$ uname -a
FreeBSD xxx 12.3-RELEASE-p5 FreeBSD 12.3-RELEASE-p5 GENERIC  amd64

$ crystal --version
Crystal 1.4.1 ()

LLVM: 10.0.1
Default target: x86_64-portbld-freebsd12.3
```

Code update:

```crystal
class My0
end

{% for n in 1..1000 %}
class My{{n.id}}
	property prop : My{{(n - 1).id}}?
end
{% end %}

def test(entity_class : T.class) : Nil forall T
      result = [] of T
      o = My123.new
      o.prop = My122.new
      result << o
      puts result.pretty_inspect
      puts result.size
end

test My123
pp My123
```

**Comment by petr-fischer** [comment]
This problem did not occur on Alpine Linux and FreeBSD.

Since Crystal 1.7.0 (LLVM: 13.0.1) this problem does not occur even on Ubuntu 22.10 (kernel 5.19).

Closing.
