### ISSUE TITLE
weird type side effects of block calling (vs. normal assignment or yielding)

### ISSUE THREAD

**Issue by wolfgang371** [crystal-lang/crystal#11086]
```crystal
x = "foo"
p typeof(x) # prints either String or (Int32 | String | Nil), depending on the very last line in this file
x = 12

exit

x = nil # no impact!
1.times do
    x = nil # no impact
end

def run1
    yield # no impact
end
def run2(&block)
    block.call # impact if called
end
run1 {x = nil} # no impact
run2 {x = nil} # impact if called; comment in or out
```

I'm using crystal 1.1.1 on Ubuntu 18.04.

**Comment by straight-shoota** [comment]
This is completely expected and documented behaviour. If you use a local variable in a captured block, it becomes a closured variable and its type is the union of all possible types that are assigned to it, independent of the location in the program.
See https://crystal-lang.org/reference/syntax_and_semantics/closures.html

**Comment by wolfgang371** [comment]
Thanks for the link, I was searching for this very page yesterday and somehow missed it.

And, obviously, I was wasn't really aware about this big difference between `proc` and `block` and I also find it completely counterintuitive; definitions of `run1` and `run2` above can be in any module; the last and second-to-last line look the very same, nevertheless one has a (potentially) global impact.

**Comment by wolfgang371** [comment]
```crystal
def run3(&block)
    yield # no impact, as run1
end
```

I just understood that also this `run3` has the same meaning as `run1`, but it has the same interface as `run2`. So this also does not match at all - I cannot deduce out of the interface how local variables are impacted.

**Comment by asterite** [comment]
It's when you capture a block by using the `block` variable. In your last snippet `block` is declared but never used. Or, put another way, if you do `yield` then the block is never captured, so there's no closure.

**Comment by beta-ziliani** [comment]
@wolfgang371 if you find suggestions to add/edit in the relevant section, please tell us/add a ticket/add a PR. Thank you! I'm closing this one now.

**Comment by straight-shoota** [comment]
Maybe a named block parameter in a yielding def should be a syntax error (ref #7157). That would make the signature explicit about wether the block is captured or yielded.

**Comment by wolfgang371** [comment]
Again, thanks for all the pointers!

What confused me in the first place that I was assuming (at least with my experience with Ruby) that procs and blocks are the same. Now I understand that (_anonymous_) blocks don't generate a problem in Crystal with compile time types since they cannot be stored and are always executed right during method execution. This is not the case for (_unanonymous_) procs, which do have handles which can be stored and called later.

And as a simplified remedy for the proc closure issue the Crystal compiler just takes the compile-time union of all types of the variables under consideration, whereas some e.g. pairwise combinations might be more accurate.

So I conclude that one should use the (anonymous) blocks wherever possible and use procs only if necessary.

This was not clear to me from the docs...
