### ISSUE TITLE
Calling self in initialize results in strange instance variable types

### ISSUE THREAD

**Issue by wolfgang371** [crystal-lang/crystal#11091]
```crystal
class A1
    def initialize
        self
        @a = 42
        p typeof(@a) # yields (Int32 | Nil)
    end
end

class A2
    def initialize
        # self
        @a = 42
        p typeof(@a) # yields Int32
    end
end

A1.new
A2.new
```

From what I understand one shouldn't call `self` in `initialize` since the object isn't yet created. But it seems it's not forbidden. The result on the other hand also doesn't make much sense to me.

I use crystal 1.1.1 and Ubuntu 18.04

**Comment by asterite** [comment]
Duplicate of https://github.com/crystal-lang/crystal/issues/1687
