### ISSUE TITLE
Initializing project that contains hyphen followed by a number generates invalid module name

### ISSUE THREAD

**Issue by n00p3** [crystal-lang/crystal#11107]
Crystal allows to initialize project with invalid name like this: `crystal init app crystal-proj-1`.
Here's the code that the command generates:

src/crystal-proj-1.cr:
``` crystal
# TODO: Write documentation for `Crystal::Proj::1`
module Crystal::Proj::1
  VERSION = "0.1.0"

  # TODO: Put your code here
end
``` 

spec/crystal-proj-1_spec.cr:
```crystal
require "./spec_helper"

describe Crystal::Proj::1 do
  # TODO: Write tests

  it "works" do
    false.should eq(true)
  end
end
```

``` bash
$ crystal run src/crystal-proj-1.cr
In src/crystal-proj-1.cr:2:23

 2 | module Crystal::Proj::1
                           ^
Error: expecting token 'CONST', not '1'
```

How about modifying [`validate_name`](https://github.com/crystal-lang/crystal/blob/49834c78b991887289e05cf9dc337db27edfaec9/src/compiler/crystal/tools/init.cr#L127) to throw an error in that case?

---
Crystal 1.1.1 [6d9a1d583] (2021-07-26)

LLVM: 10.0.1
Default target: x86_64-unknown-linux-gnu

5.9.16-1-MANJARO

**Comment by n00p3** [comment]
I've created a PR that solves this problem https://github.com/crystal-lang/crystal/pull/11108

**Comment by straight-shoota** [comment]
`crystal-proj-1` seems pretty okay for a project name (only having "crystal" in the name is discouraged for shards).

Maybe a better solution than completely disallowing this name would be to change the derived namespace to a valid name. For example `-` followed by a character that is not a valid first characters could be replaced by the character itself, without a namespace separator.

**Comment by Kanezoh** [comment]
@straight-shoota Hi! It seems there are no updates, so I implemented the way you mention.
please look at #11170.
