### ISSUE TITLE
Conversion from Float32/64 to int sometimes doesn't overflow when it should

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#11105]
Take a look at this code:

```crystal
p 4294967296_f32.to_u32
p 2147483648_f32.to_i32
p 18446744073709551616_f32.to_u64
p 9223372036854775808_f32.to_i64
p 18446744073709551616_f64.to_u64
p 9223372036854775808_f64.to_i64
```

It prints this:

```
853
-310666497
140732882721535
140732882721535
140732882721535
140732882721535
```

In reality each of those lines should throw an OverflowError because the values don't fit the target types.

**Comment by HertzDevil** [comment]
https://github.com/crystal-lang/crystal/blob/b35c8c9ceac1d55033ffdf59a350793012172b5f/src/compiler/crystal/codegen/primitives.cr#L270-273

It seems the `int_to_float` constants here are inexact or are rounded in the wrong directions. They should round towards zero (so the upper bound for `Float32#to_i32` would be exactly `2147483648_f32.prev_float`, or `2147483520_f32`).

**Comment by HertzDevil** [comment]
There is also https://github.com/crystal-lang/crystal/pull/11233#issuecomment-922419797:

```crystal
Float64::INFINITY.to_u128 # OverflowError
Float32::INFINITY.to_u128 # => 0
```
