### ISSUE TITLE
Child Instances Somehow Return Parent Type

### ISSUE THREAD

**Issue by jeremyjaybaker** [crystal-lang/crystal#11118]
I appear to have run into an issue with inheritance/return types. I'm using a factory method to generate new instances of a class, but all instances generated using this method report as their parent class instead of the proper child class. This is causing problems with passing these instances as arguments. Any advice?

All below examples have been tested using the playground in Crystal 1.1.1 [6d9a1d583].

```
abstract class Base; end
class Foo < Base; def do_thing; 1; end; end
class Bar < Base; def do_thing; 2; end; end

def factory(myflag : Bool)
  if myflag
    Foo.new
  else
    Bar.new
  end
end

typeof(factory(false)) 	# returns Base, expected Bar
typeof(factory(true)) 	# returns Base, expected Foo
typeof(Bar.new)		# returns Bar which is expected
typeof(Foo.new)		# returns Foo which is expected
```

On some level, this unexpected return isn't a huge deal since `factory(false).do_thing` returns 2 which is expected. Somehow that object is still understood to be of type `Bar`. However, this becomes a problem when you want to use these generated objects in method calls:

```
class Library
  def self.do_thing(f : Foo, b : Bar)
    puts f; puts b
  end
end

myfoo = factory(true)
mybar = factory(false)
Library.do_thing(myfoo, mybar) # This SHOULD work, but raises exception that no method exists of type (Base,Base)
```

**Comment by jeremyjaybaker** [comment]
Oh, I think I figured it out right after posting this. I think it has to do with the method return type? I'm going to try some things and close this out with my solution if I'm correct.

**Comment by HertzDevil** [comment]
The static return type of `factory` is always `Base` because it has a code path that returns `Foo` and a code path that returns `Bar`, and their union is `Base`. The compiler cannot use any compile-time arguments for `myflag` to infer a stricter type.

`typeof` returns the static type, not dynamic type, of an expression; use `.class` for the latter.

**Comment by jeremyjaybaker** [comment]
Yea, I missed these docs that explain the problem. https://crystal-lang.org/reference/syntax_and_semantics/union_types.html#union-of-classes-and-structs-under-the-same-hierarchy.

At least for my purposes, running `Library.do_thing(myfoo.as(Foo), mybar.as(Bar))` works just fine.
