### ISSUE TITLE
Support resolving a `StringLiteral` into a `TypeNode`

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#11117]
In some cases you may want to reference a dynamic type from within a macro where the related type is "built" based on other information, such as data read off an annotation, or args passed to a macro, etc.

Currently this isn't very well supported, relying upon looping over base types and checking for string equality between the (base)names of each type. This also doesn't allow any information to be obtained from the type as it's not actually a `TypeNode`. 

I propose to add `StringLiteral#resolve` and `StringLiteral#resolve?` that will assume the string's value to be a `FQN` type name and return a `TypeNode` for that type. The implementation is trivial as this logic already exists for the `Path` type, and would be basically just like:

```cr
when "resolve"
  interpret_argless_method(method, args) { interpreter.resolve Path.new @value.split "::" }
when "resolve?"
  interpret_argless_method(method, args) { interpreter.resolve?(Path.new @value.split "::") || NilLiteral.new }
```

Not directly related, but it would also be nice to add a method to get the basename of a `TypeNode` in order to make building the class strings easier. E.g. `Some::Namespace::MyClass.basename # => MyClass`.

A couple examples of how this may be useful:

```cr
# EXAMPLE 1

abstract class Blah::Foo
end

class Bar < Blah::Foo; end

class Baz < Blah::Foo; end

{% begin %}
  {% klass = "Blah::Foo" %}
  {% pp klass.resolve.subclasses %}
{% end %}

# => [Bar, Baz]

# EXAMPLE 2

annotation Assert::NotBlank; end

abstract class Contraint; end

class NotBlank < Contraint; end

class MyObj
  @[Assert::NotBlank]
  getter name : String

  def initialize(@name : String); end

  def self.validate
    {% for ivar in @type.instance_vars %}
      {% for constraint in Contraint.subclasses %}
        {% if ann = ivar.annotation %(Assert::#{constraint.basename.id}).resolve %}
          {% pp ann %}
        {% end %}
      {% end %}
    {% end %}
  end
end

MyObj.validate

# => @[Assert::NotBlank]
```

I'd be happy to make the PR if there are no objections.

**Comment by HertzDevil** [comment]
That implementation will probably fail with global `Path`s. It also does not work with `Generic` or `Union` type names (and as an edge case, `Self`).

**Comment by straight-shoota** [comment]
I second @HertzDevil that `#resolve` should not be a method on `StringLiteral`. There are already methods for that on the respective, dedicated types. Re-using them is more explicit about what is going on.
So there should be a way to transform a `StringLiteral` to a `Path`, `Generic` or `Union`. There could be a generic parse method for that, but I also agree that having a dedicated method for parsing a type name might be a good short term solution and could also be useful long term (if there should be a generic `parse` method) as there is a specific use case and it would take care of the appropriate error handling and type restrictions.

**Comment by Blacksmoke16** [comment]
> So there should be a way to transform a `StringLiteral` to a `Path`, `Generic` or `Union`.

Yea that would be perfect. Definitely not tied to having it on `StringLiteral`, just was easiest way to convey the feature.

In regards to parsing the string, any thoughts on how we want to go about that? The first thing that came to mind was kinda just assuming the string is setup like the related `TypeNode`, for example:

```cr
{{ "Foo".parse_type_name }} # => Path - Foo
{{ "Some::Namespace::Foo".parse_type_name }} # => Path - Some::Namespace::Foo
{{ "Foo|Bar".parse_type_name }} # => Union - Foo | Bar
{{ "Foo(A, B)".parse_type_name }} # => Generic - Foo(A, B)
{{ "Bar|Foo(A, B)".parse_type_name }} # => Union - Bar | Foo(A, B)
```

Where the algorithm is like:

* Split on `|`
  * String represents a `Union` if its size is `>1`
* For each string:
  * Check for `()`
    * String represents a `Generic` if present
      * Check for `:`
        * Represents named arg generics if present
      * Split on `,` and parse each value, repeating this algorithm
    * String represents a `Path` if not present
* New up the related type with the args parsed from the string

**Comment by HertzDevil** [comment]
The method that parses an arbitrary type name is `Crystal::Parser#parse_bare_proc_type`, which actually supports the full type grammar (e.g. `{}` for tuple types, `*`, `[]`, `->`). It is named like that due to operator precedence rules for the type grammar.

**Comment by Blacksmoke16** [comment]
@HertzDevil Do you mean use that in place of `Crystal::Parser#parse`?

**Comment by HertzDevil** [comment]
I don't know if it works out of the box on a newly constructed parser.

**Comment by asterite** [comment]
I think `"string".parse_type_name` reads very strange. I would prefer a global `parse_type` macro method. Then we could also have a global `parse` method for completeness, as @HertzDevil mentions.

For `parse_type` it seems you can instantiate a `Parser` and then call `parse_bare_proc_type` on it, no need to do string manipulation. For `parse` you can use `parse`, of course.

**Comment by straight-shoota** [comment]
I think making it a global method `parse_type` is a good idea.
