### ISSUE TITLE
"Permission denied" when Evaluating Crystal code 

### ISSUE THREAD

**Issue by owen2345** [crystal-lang/crystal#11115]
## Specs:
- Crystal version: Crystal 1.1.1 [6d9a1d583] (2021-07-26)
- OS: Ubuntu

## Bug Report
I am trying to evaluate crystal code using Crystal command eval like the following:
```ruby
# custom_evaluator.cr

require "compiler/crystal/command"
require "compiler/crystal/compiler"
require "compiler/crystal/program"
require "compiler/crystal/command/*"

# Custom file
require 'my_huge_file_name'

puts Crystal::Command.run(["eval", "MyHugeClass.call(10)"])
puts Crystal::Command.run(["eval", "puts \"hello world\""])
# Expected: "hello world"
```
Run: `crystal run custom_evaluator.cr`
Result: `--: 1: : Permission denied`

Is this possible to do it?

Best regards!

**Comment by straight-shoota** [comment]
We'll need more information on this bug report. Can you determine what exactly causes the permission denied error? Or provide a reproducible example?

**Comment by jwoertink** [comment]
I tried to re-create that the best I could. Changing the `'my_huge_file_name'` to `"./my_huge_file_name"` and I get this:

```
In /usr/share/crystal/src/llvm/lib_llvm.cr:13:17

 13 | VERSION = {{`#{LibLLVM::LLVM_CONFIG} --version`.chomp.stringify}}
                  ^
Error: error executing command: "" --version, got exit status 127

```

Not sure if that's helpful or not, but figured I'd chime in.

**Comment by owen2345** [comment]
@jwoertink I had the same error, but I skipped it hardcoding to a static value (just for debugging).
These are the steps:
- Create a file `code_eval.cr` with: 
```
require "json"
require "compiler/crystal/command"
require "compiler/crystal/compiler"
require "compiler/crystal/program"
require "compiler/crystal/command/*"

# In real code this part would include libraries to be used when calling eval.

Crystal::Command.run(["eval", "puts \"Wello world\""])
```
- Run the code`crystal run code_eval.cr`
- Expected `$ => Hello world`
- (Optional) Fix VERSION error in /usr/share/crystal/src/llvm/lib_llvm.cr:13 to "VERSION = 1.0" (just for debugging)

Thanks for reviewing.   
Note: I am new in Crystal, but wanted to create a plugin to sync some Rails apps with new possible apps in Crystal.

**Comment by jwoertink** [comment]
Welcome to Crystal @owen2345! For a little more info, I see you're using Ubuntu, how did you install Crystal? Was it from the deb repo, or did you clone Crystal and build manually?

**Comment by owen2345** [comment]
@jwoertink I use docker. 
In this case I am using Amber framework:
```
FROM crystallang/crystal:latest
RUN apt-get update
RUN apt-get install libreadline-dev libsqlite3-dev libpq-dev libmysqlclient-dev libssl-dev libyaml-dev libpcre3-dev libevent-dev curl -y
RUN curl -L https://github.com/amberframework/amber/archive/stable.tar.gz | tar xz
RUN cd amber-stable/ && shards install --ignore-crystal-version && make install

WORKDIR /app
COPY shard.* /app/
RUN shards install
COPY . /app
CMD amber watch
```

**Comment by HertzDevil** [comment]
The two calls to `Crystal::Command.run` will build two separate temporary executables and run them immediately; any libraries required in the code itself will not affect their results, so you cannot trick Crystal into evaluating code in an outer context like that.

**Comment by BlobCodes** [comment]
> I tried to re-create that the best I could. Changing the `'my_huge_file_name'` to `"./my_huge_file_name"` and I get this:
> 
> ```
> In /usr/share/crystal/src/llvm/lib_llvm.cr:13:17
> 
>  13 | VERSION = {{`#{LibLLVM::LLVM_CONFIG} --version`.chomp.stringify}}
>                   ^
> Error: error executing command: "" --version, got exit status 127
> ```
> 
> Not sure if that's helpful or not, but figured I'd chime in.

You probably don't have LLVM installed (or crystal can't find it). On my distro, I have to use the variable LLVM_CONFIG to set the path.

```
[blobcodes@davids-pc ~]$ LLVM_CONFIG="llvm-config-11-64" crystal eval '
require "compiler/crystal/**"
puts Crystal::Command.run(["eval", "puts \"hello world\""])
'                        
/usr/bin/ld: /usr/share/crystal/src/llvm/ext/llvm_ext.o: in function `LLVMExtDIBuilderCreateCompileUnit':
llvm_ext.cc:(.text+0x2bd): undefined reference to `llvm::DIBuilder::createCompileUnit(unsigned int, llvm::DIFile*, llvm::StringRef, bool, llvm::StringRef, unsigned int, llvm::StringRef, llvm::DICompileUnit::DebugEmissionKind, unsigned long, bool, bool, llvm::DICompileUnit::DebugNameTableKind, bool)'
/usr/bin/ld: /usr/share/crystal/src/llvm/ext/llvm_ext.o: in function `LLVMExtWriteBitcodeWithSummaryToFile':
llvm_ext.cc:(.text+0x1c9e): undefined reference to `llvm::buildModuleSummaryIndex(llvm::Module const&, std::function<llvm::BlockFrequencyInfo* (llvm::Function const&)>, llvm::ProfileSummaryInfo*)'
/usr/bin/ld: /usr/share/crystal/src/llvm/ext/llvm_ext.o: in function `llvm::IRBuilder<llvm::ConstantFolder, llvm::IRBuilderDefaultInserter>::CreateAtomicCmpXchg(llvm::Value*, llvm::Value*, llvm::Value*, llvm::AtomicOrdering, llvm::AtomicOrdering, unsigned char)':
llvm_ext.cc:(.text._ZN4llvm9IRBuilderINS_14ConstantFolderENS_24IRBuilderDefaultInserterEE19CreateAtomicCmpXchgEPNS_5ValueES5_S5_NS_14AtomicOrderingES6_h[_ZN4llvm9IRBuilderINS_14ConstantFolderENS_24IRBuilderDefaultInserterEE19CreateAtomicCmpXchgEPNS_5ValueES5_S5_NS_14AtomicOrderingES6_h]+0x7d): undefined reference to `llvm::AtomicCmpXchgInst::AtomicCmpXchgInst(llvm::Value*, llvm::Value*, llvm::Value*, llvm::AtomicOrdering, llvm::AtomicOrdering, unsigned char, llvm::Instruction*)'
collect2: Fehler: ld gab 1 als Ende-Status zurück
Error: execution of command failed with code: 1: `cc "${@}" -o /home/blobcodes/.cache/crystal/crystal-run-eval.tmp  -rdynamic -L/usr/bin/../lib64/crystal/lib -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` /usr/share/crystal/src/llvm/ext/llvm_ext.o `"llvm-config-11-64" --libs --system-libs --ldflags 2> /dev/null` -lstdc++ -lpcre -lm -lgc -lpthread -levent  -lrt -ldl`
```

---

Anyways, just like HertzDevil said, any libraries required in the code itself won't affect the eval result.
You could use something like this (if the required library is always locally available):
`Crystal::Command.run(["eval", "require \"my_huge_file_name\"; puts \"Wello world\""])`

**Comment by owen2345** [comment]
Thank you so much. I tried recompiling crystal from scratch + adding my huge library (<amber_app/config/application.cr>) but no luck either.
My idea was to have something like `crystal_amber`, to run commands without importing `config/application.cr` each time.
Sample: `crystal_amber run "Article.count"`
Maybe in the future. Thanks again.
