### ISSUE TITLE
Serving files over HTTP using IO.copy results in increasing RAM usage

### ISSUE THREAD

**Issue by acoolstraw** [crystal-lang/crystal#11150]
## Bug Report

I'm working on something that serves files, and I've noticed that with every request, the RAM usage climbs up a bit, but never goes back down. It seems to be constant, as no matter how big the file, the RAM usage increases at the same pace.

Crystal version: 
```
Crystal 1.1.1 [6d9a1d583] (2021-07-26)

LLVM: 10.0.1
Default target: x86_64-unknown-linux-gnu
```
OS: Ubuntu 21.04

Reproducible code:
```cr
require "http/server"

server = HTTP::Server.new do |context|
    File.open("/home/bo/Documents/mira/loosegoose.png", "r") do |file|
        IO.copy(file, context.response)
    end
end

address = server.bind_tcp 8080
puts "Listening on http://#{address}"
server.listen
```
To test that, I went to the address and held Ctrl+R with disabled caching, which looped reloading the page. Compiled it with the `--release` flag. The RAM increase per request is negligible but it could become a problem in high-load environments.

**Comment by acoolstraw** [comment]
it also appears that it doesn't increase memory if you don't send the requests fast enough (holding Ctrl+R does it fast enough to increase RAM like that)

**Comment by grkek** [comment]
That happens because the web-server is running using the fibers, basically each connection is entirely a new world which results in multiple IO operations at the same time, that is the reason of your problem.

What you can do is store that file in the memory from the first place if it doesn't change at all and serve it like that.

**Comment by straight-shoota** [comment]
For how long have you been testing this? Unless you trigger the garbage collecter manually, the request fibers and allocated resources may only be collected at the next scheduled GC run which might take some time. Perhaps you're not seeing the effects yet.

Instead of hitting Ctrl+R in a browser, a dedicated HTTP benchmark tool like wrk or ab would provide more reliable results.

**Comment by kostya** [comment]
try also with such code, before `server.listen`, it helps in some my apis:
```crystal
spawn do
  loop { GC.collect; sleep 10 }
end
```

**Comment by yxhuvud** [comment]
What others have noted are side effects from what I see as the root of the issue - namely that `IO.copy` **copies** data from one fd to another. I don't know how this is solved on other operating systems, but at least on Linux this would be most efficiently solved by using either the `sendfile` or the `splice` syscall [*]. 

Perhaps some peephole optimization is possible to improve the performance of this particular case when the underlying IO types support it?

[*] To do it with splice you need a pipe, and then set up a splice from source_fd to pipe, and a splice from pipe to target_fd. It is more complicated, but `sendfile` only works when the target is a socket whereas `splice` will work with almost any kind of file descriptor.

**Comment by straight-shoota** [comment]
Related: #8919 #8926

**Comment by HertzDevil** [comment]
I don't think `context.response` is a file descriptor.

**Comment by acoolstraw** [comment]
> For how long have you been testing this? Unless you trigger the garbage collecter manually, the request fibers and allocated resources may only be collected at the next scheduled GC run which might take some time. Perhaps you're not seeing the effects yet.
> 
> Instead of hitting Ctrl+R in a browser, a dedicated HTTP benchmark tool like wrk or ab would provide more reliable results.

Indeed, hitting Ctrl+R is not ideal, but it seems like it does cause this

**Comment by rdp** [comment]
If it's a memory leak running it under valgrind might show something...if not it's just a GC and your RAM usage should eventually even out...
