### ISSUE TITLE
CRYSTAL_OPTS messes with positional CLI arguments

### ISSUE THREAD

**Issue by dammer** [crystal-lang/crystal#11164]
## Bug Report

Include reproducible code
```
$ export CRYSTAL_OPTS='print caller'
$ crystal eval
["/eval:1:1 in '__crystal_main'", "/home/damir/.asdf/installs/crystal/1.0.0/share/crystal/src/crystal/main.cr:110:5 in 'main_user_code'", "/home/damir/.asdf/installs/crystal/1.0.0/share/crystal/src/crystal/main.cr:96:7 in 'main'", "/home/damir/.asdf/installs/crystal/1.0.0/share/crystal/src/crystal/main.cr:119:3 in 'main'", "__libc_start_main", "_start", "???"]
```

```
$ crystal -v
Crystal 1.0.0 [dd40a2442] (2021-03-22)
LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```

```
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
```

**Comment by Blacksmoke16** [comment]
Isn't think kinda expected given `CRYSTAL_OPTS='print caller' crystal eval` is equivalent to `crystal eval 'print caller'`?

**Comment by dammer** [comment]
Actually `CRYSTAL_OPTS` used for set additional runtime options for crystal run, something like `export CRYSTAL_OPTS='--threads 2 --verbose'`. 
In that case eval just does not work:
```
$ crystal eval print 123
syntax error in eval:1
Error: postfix decrement is not supported, use `exp -= 1`
```

**Comment by asterite** [comment]
No need to use `CRYSTAL_OPTS`:

```
$ crystal eval --prelude=empty puts 1
syntax error in eval:1
Error: postfix decrement is not supported, use `exp -= 1
```

So it seems to be a bug with `crystal eval`

**Comment by dammer** [comment]
Yeah, but `CRYSTAL_OPTS` is also a bug, which is not quite obvious, I reinstalled the crystal 2 times before I found the reason) 
https://github.com/crystal-lang/crystal/blob/dd40a2442fa186add8a82b74edb14a90aa1dae05/src/compiler/crystal/command.cr#L96

**Comment by Blacksmoke16** [comment]
@dammer I'm still not sure I see what the bug actually is tho? AFAIK that flag is just used to allow providing options to crystal invocations, such as `run` or `eval`. If you make those arguments code to execute and run `crystal eval` I don't see why that shouldn't work or could be prevented, even if it's not the main use case.

At the least it should be documented within https://crystal-lang.org/reference/using_the_compiler/index.html#environment-variables.

**Comment by dammer** [comment]
@Blacksmoke16 `Usage: crystal eval [options] [source]`
The error is that `eval` tries to evaluate the options transmitted to it,(it does not matter through the ENV variable or from the command line) as source code, as pointed [here](https://github.com/crystal-lang/crystal/issues/11164#issuecomment-912599523)
Also BMO `CRYSTAL_OPTS='print caller' crystal eval` should fails with invalid options message
I think we need to rename this issue to more suitable name.

**Comment by straight-shoota** [comment]
Yeah, I suppose `CRYSTAL_OPTS` should only allow option flags. Positional arguments should be prohibited because that messes with the position of *actual* positional arguments from the command invokation.

`crystal env` not understanding option flags is a different issue.
