### ISSUE TITLE
C bindings in interpreted mode

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#11173]
C bindings in interpreted mode works differently than in compiled mode. In short, there is no linker that could be used and the interpreter needs to take care of the linker's responsibilities itself.

The process of actually *calling* a C function is relatively straightforward and works pretty well through `libffi`. But for getting there, we need to load the respective library into memory and retrieve the address of the respective function.

The part about loading libraries and discovering symbols is a bit more tricky. The current implementation works, but it's very limited (see https://github.com/crystal-lang/crystal/issues/11157#issuecomment-911669118).

I think the interpreter should try to replicate the process happening in compiled mode as much as possible in order to minimize differences between interpreted and compiled mode.

We need to be a aware that in compiled mode, there are a linking stage while building a program and at runtime shared libraries are loaded dynamically. There's no such distinction in interpreted mode.

A fundamental difference of the current interpreter implementation is that symbols are looked up directly in the annotated libraries. But there's no such namespacing in compiled mode. The linker is not aware which library is supposed to provide a particular symbol. It just combines a list of symbols with a list of libraries (and a list of paths were it might find those libraries). If it finds a symbol in any library, it's happy.
For Crystal's C bindings that means there is no relation between symbols defined in a lib type and the `Link` annotation associated with that. We can think of all `Link` annotations to be just a global list.

While the current implementation's strict associatations might actually be better, we can't replicate that behaviour in compiled mode. So I don't think we should have it interpreted mode either.

A big issue in compiled mode is loading an object file which has not been processed into a shared library is rather difficult. The same goes for static libraries (which are essentially just object files in an archive format).
This doesn't work out of the box. `dlopen` only works on shared libraries. There are probably ways to load and search object files, but it appears to be pretty much uncharted territory. I could not find a dedicated tool for that. It appears to be possible, though. LLVM JIT seems to be able to load and link object files. However I I have not verified this and I don't know how they do it.
Related issue: https://github.com/root-project/cling/issues/280

We probably have to accept the limitation of being able to only bind to shared libraries in interpreted mode, at least for getting it started. We can look into that later, but it would be too complex trying to solve that right from the start. An idea for a workaround could be to turn an object file into a shared library on the fly. I'd also leave that for a later improvement, though.

**Comment by hugopl** [comment]
I think not supporting static libraries in first versions isn't a release blocker, but this is just my opinion.

The workaround of generating a dynamic library with all  the static library symbols on the fly seems an easier way to go. My first thought was _"hey, this will makes crystal i depends on a C compiler!"_, but I forgot that the library can probably be generated from LLVM IR code.

**Comment by straight-shoota** [comment]
> I forgot that the library can probably be generated from LLVM IR code.

I don't follow what you mean by that. In interpreted mode, there's no LLVM backend for Crystal. And a library would be available as object code in an object file or static library. So also no LLVM IR. But turning an object file into a shared library should work (I think it needs to be compiled with position independent code `-fPIC`, though). Doing that requires a C compiler (or a plain linker, but that's probably more effort).

**Comment by asterite** [comment]
> For Crystal's C bindings that means there is no relation between symbols defined in a lib type and the Link annotation associated with that.

This is partially true. When you use a `@[Link]` on top of a lib, that link is only processed if a C function defined in that lib is called. So there is a relationship! And for example if you bind against sqlite3 you put a link on top of those function. So I don't understand why you say there's no relationship at all. I use that relationship in the interpreter with great success :-)

**Comment by straight-shoota** [comment]
The following program perfectly links in compiled mode:
```cr
@[Link(ldflags: "-lsqlite3")]
lib LibA
  fun sqlite3_errmsg(Void*) : UInt8*
end

lib LibB
  fun sqlite3_errcode(Void*) : Int32
end

LibB.sqlite3_errcode nil
LibA.sqlite3_errmsg nil
```

There's no connection tying `LibB` to `sqlite3`, but that doesn't matter because the linker doesn't care about that.
In interpreted mode, the program fails because the symbol `sqlite3_errcode` can't be resolved when taking only the link information from `LibB` into account.

That's the difference between interpreted and compiled mode I'm talking about. I think we should try to avoid such a difference and try to replicate the linker behaviour of compiled mode.

Note: It works if the calls are switched because then `libsqlite3` will already be loaded into program memory when the interpreter tries to find `sqlite3_errcode` and thus it succeeds.

**Comment by asterite** [comment]
> I think we should try to avoid such a difference and try to replicate the linker behaviour of compiled mode

How?

**Comment by straight-shoota** [comment]
Build a global ordered list of libraries and use the first matching symbol found in any of them. That's how `ld` works.
If you have multiple libraries providing a symbol with the same name, the one from the library higher up in the chain is used.

**Comment by hugopl** [comment]
> I don't follow what you mean by that. In interpreted mode, there's no LLVM backend for Crystal.

My bad, I was with the mindset that C code wrapping the static library functions would be needed to create a shared library from a static library, that isn't true, and even if it was... there's the PIC issue. 

Usually static libraries are compiled without `-fPIC`, so I think static libraries support seems not possible, but as the interpreter mode is meant for development usage I don't think this should be an issue.

Here's when I did hit the wall on the lack of PIC on object files inside a static library, `libpgcommon.a` was just a random library from my system I used to test.

```
$ gcc -shared -o libtest.so -Wl,--whole-archive libpgcommon.a -Wl,--no-whole-archive
/usr/bin/ld: libpgcommon.a(file_perm.o): warning: relocation against `pg_dir_create_mode' in read-only section `.text'
/usr/bin/ld: libpgcommon.a(checksum_helper.o): relocation R_X86_64_PC32 against undefined symbol `pg_comp_crc32c' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
```
