### ISSUE TITLE
32 bit vs 64 bit vs malloc

### ISSUE THREAD

**Issue by ozra** [crystal-lang/crystal#1117]
One expects to be able to _allocate_ and _index_ as much data as the system one is writing code for can handle. Therefore, for a 64 bit system... Problem: Boehm GC seems limited to 32 bit parameters.

I know this will be addressed with a specific GC somewhere in the future, but I thought it would be good to issue, for reference.

**Comment by waj** [comment]
This is actually a bug. The `GC_malloc` can actually receive a `SizeT` argument to allocate memory. It should be a rather easy thing to fix.

**Comment by ozra** [comment]
Hmm, was this fixed @asterite - I have a vague memory of seeing a merge regarding it, but I might have been dreaming ;-)

**Comment by waj** [comment]
Partially...
The GC_malloc was fixed here: https://github.com/manastech/crystal/commit/4d350892#diff-859e2b09d96c61167d13e65208236dd8R9

But still little changes has to be made in `GC.malloc` and `__crystal_malloc`.

**Comment by ozra** [comment]
Ok, just bumped to see if closing was just forgotten :)

**Comment by jhass** [comment]
Took a stab at fixing this but failed, I think. From my understanding the following lines need updates too:

* https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/codegen/codegen.cr#L1830
* https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/codegen/codegen.cr#L1842-L1843
* https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/codegen/codegen.cr#L1865

And I guess https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/codegen/codegen.cr#L1981 is not correct either for 32bit machines? (Nor `memset` or `memcopy` while we're at it).

Anyway, for the first 3/4 I tried changing it to `malloc_fun.params.first.type` and similar, but after actually changing the definitions for `_crystal_malloc` etc to `LibGC::SizeT` (effectively `LibC::SizeT`), I'm getting an error from LLVM that I don't understand at all.

**Comment by asterite** [comment]
Fixed by #4960
