### ISSUE TITLE
Is there a tool to check if class/method is documented ?

### ISSUE THREAD

**Issue by dinko-pehar** [crystal-lang/crystal#11182]
## Feature Request

While using Crystal for closed source project, I noticed that some of the methods are not documented. Is there a tool to force a documentation of methods/classes etc. ? I'm looking something similar to `crystal format` as in our CI as:

- You can use `crystal tool format` to format crystal files in `src/`
- You can use `crystal tool format --check` to check if files are properly formatted (_such as fail in CI if they are not_)

Maybe something like `crystal docs --check` with output as:

```
method 'add' in `src/math.cr` missing documentation
method 'mul' in `src/math.cr` missing documentation
```

Also, check can respect [:nodoc:](https://crystal-lang.org/reference/syntax_and_semantics/documenting_code.html#nodoc) if present. There are some similar errors and warnings when documentation is missing from `flake8` tool which is mostly used in Python projects for defining best practices.

**Comment by straight-shoota** [comment]
The docs generator outputs all information in `docs/index.json`. So you could just consume that and look for features with `"doc":null`. That would be a quick solution for your use case.

I wouldn't mind adding something like this to the docs generator, but I think we'll have to look a more closely at that.

An external script consuming the JSON data could be a helpful input for experimenting with this feature.

**Comment by caspiano** [comment]
This seems like a good addition to [ameba](https://github.com/crystal-ameba/ameba)!

**Comment by dinko-pehar** [comment]
Will be resolved in some future versions of ameba I guess. Thank you for your support.
