### ISSUE TITLE
Missing support for DWARF 5

### ISSUE THREAD

**Issue by RespiteSage** [crystal-lang/crystal#11192]
## Versions

This bug occurs with the following `crystal version`:
```text
Crystal 1.1.1 [6d9a1d583] (2021-07-26)

LLVM: 10.0.1
Default target: x86_64-unknown-linux-gnu
```

It definitely occurs on OpenSUSE Tumbleweed 20210904, and I've not reproduced it on any other OSes or heard of anyone else encountering it. Comparisons with other OSes below.

## Behavior

A Crystal executable that executes a `raise` at runtime will cause an arithmetic overflow, seemingly to do with stack unwinding. So, for example, the code below causes both the expected exception and an arithmetic overflow.

```crystal
raise "Oops!"
```
Output:
```text
Unhandled exception: Oops! (Exception)
Unhandled exception: Arithmetic overflow (OverflowError)
  from Exception::CallStack::unwind:Array(Pointer(Void))
  from Exception::CallStack#initialize:Array(Pointer(Void))
  from Exception::CallStack::new:Exception::CallStack
  from raise<OverflowError>:NoReturn
  from ???
  from Crystal::DWARF::LineNumbers#read_opcodes<Crystal::DWARF::LineNumbers::Sequence>:Nil
  from Crystal::DWARF::LineNumbers#decode_sequences<(UInt32 | UInt64)>:Nil
  from Crystal::DWARF::LineNumbers#initialize<IO::FileDescriptor+, (UInt32 | UInt64), UInt64>:Nil
  from Crystal::DWARF::LineNumbers::new<IO::FileDescriptor+, (UInt32 | UInt64), UInt64>:Crystal::DWARF::LineNumbers
  from Exception::CallStack::read_dwarf_sections<UInt64>:(Array(Tuple(UInt64, UInt64, String)) | Nil)
  from ~procProc(Pointer(LibC::DlPhdrInfo), UInt64, Pointer(Void), Int32)
  from dl_iterate_phdr
  from Exception::CallStack::load_dwarf_impl:Nil
  from Exception::CallStack::load_dwarf:(Int32 | Nil)
  from Exception::CallStack::decode_line_number<UInt64>:Tuple(String, Int32, Int32)
  from Exception::CallStack#decode_backtrace:Array(String)
  from Exception::CallStack#printable_backtrace:Array(String)
  from Exception+
  from Exception+
  from Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32
  from main
  from __libc_start_main
  from _start
  from ???
```

I first ran into this when adding `expect_raises` specs. `expect_raises` will not show the overflow if the exception matches what's expected but will show the overflow if the exception does not match. I think this supports the stack unwinding theory (though the stack trace itself is certainly the most compelling evidence).

## Prior Investigation

The behavior reproduces on a fresh OpenSUSE Tumbleweed docker container as well as with a freshly-built compiler (version `1.2.0-dev [a253018a9] (2021-09-07)`).

However, the code works as expected on [carc.in](carc.in), on a fresh OpenSUSE Leap docker container, and on the machines of a couple other people I was talking to in the Crystal Gitter (I believe they were running Arch and Debian Unstable).

I found that the libevent versions differ between Leap (libevent 2.1.7) and Tumbleweed (libevent 2.1.8), but I didn't think that would affect the stack unwinding. I haven't tried changing the libevent version on Tumbleweed to see if that fixes the issue.

I know that Crystal uses libunwind, but I'm not sure what shared object or package that is part of.

**Comment by straight-shoota** [comment]
FWIW: A couple of weeks ago I noticed some build problems with the RPM package on OpenSUSETumbleweed. But currently, all builds succeed (https://build.opensuse.org/project/show/devel:languages:crystal).

**Comment by RespiteSage** [comment]
Unfortunately, I'm still able to reproduce this issue on Tumbleweed (and not elsewhere) as described above, so whatever fixed the build didn't fix the behavior.

**Comment by MistressRemilia** [comment]
I've been running into this same issue on my machines where any attempt to print a backtrace, either through Exception#backtrace or just letting the exception go unhandled, raises an OverflowError.

This sample program produces this output:
```crystal
def testme
    raise "Hello from testme"
end

testme
```
```
Unhandled exception: Hello from testme (Exception)
Unhandled exception: Arithmetic overflow (OverflowError)
  from Exception::CallStack::unwind:Array(Pointer(Void))
  from Exception::CallStack#initialize:Array(Pointer(Void))
  from Exception::CallStack::new:Exception::CallStack
  from raise<OverflowError>:NoReturn
  from ???
  from Crystal::DWARF::LineNumbers#read_opcodes<Crystal::DWARF::LineNumbers::Sequence>:Nil
  from Crystal::DWARF::LineNumbers#decode_sequences<(UInt32 | UInt64)>:Nil
  from Crystal::DWARF::LineNumbers#initialize<IO::FileDescriptor+, (UInt32 | UInt64), UInt64>:Nil
  from Crystal::DWARF::LineNumbers::new<IO::FileDescriptor+, (UInt32 | UInt64), UInt64>:Crystal::DWARF::LineNumbers
  from Exception::CallStack::read_dwarf_sections<UInt64>:(Array(Tuple(UInt64, UInt64, String)) | Nil)
  from ~procProc(Pointer(LibC::DlPhdrInfo), UInt64, Pointer(Void), Int32)
  from dl_iterate_phdr
  from Exception::CallStack::load_dwarf_impl:Nil
  from Exception::CallStack::load_dwarf:(Int32 | Nil)
  from Exception::CallStack::decode_line_number<UInt64>:Tuple(String, Int32, Int32)
  from Exception::CallStack#decode_backtrace:Array(String)
  from Exception::CallStack#printable_backtrace:Array(String)
  from Exception+
  from Exception+
  from Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32
  from main
  from __libc_start_main
  from _start
  from ???
```
Catching the exception and calling `Exception#backtrace` produces the same uncaught OverflowError.

I tried using `CRYSTAL_LOAD_DWARF=0` as mentioned in [this issue](https://github.com/crystal-lang/crystal/issues/8352), and while this stops the OverflowError, I still don't get any usable backtrace.
```
Unhandled exception: Hello from testme (Exception)
  from Exception::CallStack::unwind:Array(Pointer(Void))
  from Exception::CallStack#initialize:Array(Pointer(Void))
  from Exception::CallStack::new:Exception::CallStack
  from raise<Exception>:NoReturn
  from ???
  from testme:NoReturn
  from __crystal_main
  from Crystal::main_user_code<Int32, Pointer(Pointer(UInt8))>:Nil
  from Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32
  from main
  from __libc_start_main
  from _start
  from ???
```

I've been able to reproduce this with the v1.0.0, v1.1.0, and v1.1.1 .tar.gz builds from the Crystal homepage, as well as when I build from source using git 33f6ded5e9be95f760e71e272555ef44dadd718d (and earlier).

I've also tried using the GOLD linker, as mentioned above.  No luck :(

**Versions and Such**
When I use the .tar.gz from the Crystal homepage:
```
Crystal 1.1.1 [6d9a1d583] (2021-07-26)

LLVM: 10.0.1
Default target: x86_64-unknown-linux-gnu
```
And from source:
```
Crystal 1.2.0-dev [33f6ded5e] (2021-10-07)

LLVM: 12.0.1
Default target: x86_64-unknown-linux-gnu
```
Distro: Slackware 15 RC1
LLVM: 12.0.1
GCC: 11.2.0
GDB: 11.1
Bintutils: 2.37
Libevent: 2.1.12
Libunwind: 1.5.0

**Comment by straight-shoota** [comment]
The reason seems to be that some fields in `DWARF::LineNumbers::Sequence` auch as `opcode_base` and `maximum_operations_per_instruction` are zero, but they are not expected to be that. This causes several arithmetics errors with zero division and overflow (although the latter could be mitigated by using signed integer types for arithmetics).

I'm not sure if those feelds are supposed to be zero and our parser just doesn't handle that correctly, or if them being zero is a bug. Probably the former. We just haven't encountered that before.

My guess is this is caused by the linker (GCC 11.2.0 is relatively recent).

**Comment by deiv** [comment]
Hi,

Same in Debian https://buildd.debian.org/status/fetch.php?pkg=crystal&arch=amd64&ver=1.2.1%2Bdfsg-3&stamp=1635720750&raw=0 :
```
Failures:

  1) Crystal::Command::FormatCommand formats stdin (bug + show-backtrace)

       Arithmetic overflow (OverflowError)
         from ???
         from ???
         from ???
         from ???
         from dl_iterate_phdr
         from ???
         from ???
         from ???
         from ???
         from ???
         from ???
         from ???
         from ???
         from ???
         from main
         from __libc_start_main
         from _start
         from ???

Finished in 19:35 minutes
10245 examples, 0 failures, 1 errors, 14 pending
```
     
The spec https://github.com/crystal-lang/crystal/blob/dd40a2442fa186add8a82b74edb14a90aa1dae05/spec/compiler/crystal/tools/format_spec.cr#L75-L86 fails with GCC11 and not with GCC10.

**Comment by straight-shoota** [comment]
GCC 11 uses the DWARF 5 standard. We need to add support for DWARF 5.

**Comment by straight-shoota** [comment]
DWARF 5 introduced some some backwards-incompatible changes to the data format of the line number program header.

A wokaround should technically be to pass `-gdwarf-4` as a link flag. However, I found that this did not work for me. Line number information may use a different version than the global DWARF version number, so maybe the option only changes the latter.

**Comment by HertzDevil** [comment]
Speaking of DWARF 5, it has Crystal's language ID but LLDB doesn't seem to support it yet: https://github.com/llvm/llvm-project/blob/e7fdff403e849b18d93cd4a5cb760cba66a92c0b/lldb/include/lldb/lldb-enumerations.h#L436
