### ISSUE TITLE
Consecutive underscores in number literals and number parsing methods

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#11203]
Both integer literals and number parsing methods like `String#to_i` (with `underscore: true`) allow and ignore underscores in the number:
```cr
1_1                            # => 11
"1_1".to_i(underscore: true)   # => 11
```

The semantics are very similar but there is a difference: Literals allow multiple consecutive underscores, which is an error in `String#to_i`:

```cr
1__1                          # => 11
"1__1".to_i(underscore: true) # Error: Invalid Int32: 1__1
```

Considering the similarity of both approaches, it should be expected that both underscore semantics are identical and don't differ by such a minor detail.
(It would also help for using parsing methods in the compiler implementation.)

Originally brought up in https://github.com/crystal-lang/crystal/issues/11196#issuecomment-917500462 ff.

**Comment by HertzDevil** [comment]
`1__1` is a syntax error in both Ruby and Python, and in C++ where the separator is `'` instead, `1''1` is also an error there.

**Comment by oprypin** [comment]
I think consecutive underscores should be disallowed.
