### ISSUE TITLE
Explicit return types for `Proc` literals

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#11218]
The return type of a `Proc` literal is always deduced from its body, but sometimes it helps to be explicit and specify it in the literal itself, because:

* If the return type doesn't match the restriction then a type error would be produced at the definition site rather than some call site.
* That return type may be used to trigger explicit casts (`Nil`) and autocasts (#10837):
  ```crystal
  f = ->(x : Int32) : Nil { 1 }
  f.call    # => nil
  typeof(f) # => Proc(Int32, Nil)

  g = -> : Float64 { 1 }
  x = g.call # => 1.0
  typeof(x)  # => Float64
  typeof(g)  # => Proc(Float64)
  ```

The proposed syntax is as shown above; the usual <code>&nbsp;: T</code>, together with the mandatory space after the colon, comes after the parameter list, or immediately after `->` if there are no parameters at all and the parentheses are omitted. These literals currently all report `unexpected token: :`. I don't think there are any syntactic ambiguities arising from this addition.

This does not affect type inference for `Proc` literals without a return type restriction. In particular, it does not suggest that their return types are inferred from their assignments to other places expecting a `Proc` (https://github.com/crystal-lang/crystal/issues/10546#issuecomment-817093118); their bodies still completely determine their return types.

Accordingly, the following macro method should be added for node introspection:

```crystal
class Crystal::Macros::ProcLiteral
  # Returns the return type of this proc, if specified.
  def return_type : ASTNode | Nop
  end
end
```

**Comment by asterite** [comment]
I just want to note that you can already do this, but with a different syntax:

```crystal
f = Proc(Int32, Nil).new { 1 }
f.call    # => nil
typeof(f) # => Proc(Int32, Nil)

g = Proc(Float64).new { 1 }
x = g.call # => 1.0
typeof(x)  # => Float64
typeof(g)  # => Proc(Float64)
```

That said, I think the proposed syntax makes total sense.
