### ISSUE TITLE
Underscores in number literals

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#11214]
The discussion in #11196 has brought up some inconsitencies regarding parsing of underscores in number literals that might be up for discussion.

The following describes the current behaviour as of Crystal 1.1.1.
I've also added Rust and Ruby behaviour as comparison, because their number literals are most influential and similar to Crystal's.

### Decimal point

```cr
1_.1   # => 1.1
1._1   # Error: undefined method '_1' for Int32
```

It is at least inconsistent that an underscore is accepted *before* the decimal point, but not *after*.

There is a good reason for `1._1` being parsed as a call because `Int32#_1` is legally a method.

In Ruby, both are an error. Rust has the same behaviour as Crystal.

### Exponent

```cr
1_e2 # => 100.0
1e_2 # => 100.0
```

This appears to be fine. Consistency with other components of a number literal might be taken into account. There is a high similarity witht the decimal point, which is also an infix notation. But there's no ambiguity.

In Ruby, both are an error. Rust has the same behaviour as Crystal.

### Base Prefix

```cr
0x_2  # => 2
0_x2  # Error: unexpected token: x2
0_12  # 12
```

There is a good argument that the base prefix (e.g. `0x`) should be considered an inseparable unit, just like the type suffix (like `i32`). So this behaviour appears to be fine. Accepting an underscore after this prefix seems reasonable.

<del>Note: `0_12` was originally reported to be valid, but is not. @BlobCodes maybe you mixed this up or is it a typo and you meant a different variant of the literal?</del>
<ins>`0_12` is parsed as decimal number. But stringification of such a number literal breaks:</ins>

```cr
{{ 0_12 }} # Error: octal constants should be prefixed with 0o
```

In Ruby, the former two are an error, but `0_12` is valid (`012` is also valid octal number in Ruby). 
In Rust, `0x_2` is valid. `0_x2` is an error because `x2` is interpreted as a type suffix. `012` is also a valid decimal number literal because Rust allows leading zeros.

### Trailing/Leading

```cr
1_ # => 1
_1 # Error: undefined local variable or method '_1' for top-level
```

This behaviour is somewhat inconsistent. Similar to the decimal point, there's a good reason that the leading underscore is no parsed as a number literal because it's a valid variable name.

In Ruby, `1_` is also an error ("trailing `_' in number"). Rust has the same behaviour as Crystal.

Related: #11203

**Comment by straight-shoota** [comment]
In my opinion, the current behaviour is fine and as expected. The small inconsistencies are unfortunate, but there are good reasons. I don't see a good reason to invalidate the `1_.1` or `1_` just because you can't place the underscore on the opposite site of the decimal point or digit.

**Comment by BlobCodes** [comment]
> Note: 0_12 was originally reported to be valid, but is not. @BlobCodes maybe you mixed this up or is it a typo and you meant a different variant of the literal?

![Screenshot_20210915_120721](https://user-images.githubusercontent.com/14961554/133414508-951b1db1-4a09-4b75-b554-b7b073ca7ad2.png)

**Comment by straight-shoota** [comment]
Oh, that's interesting! I used `p!` to print the value and apparently the stringification breaks.
```cr
p! 0_12 # Error: octal constants should be prefixed with 0o
0_12    # => 12
```

**Comment by straight-shoota** [comment]
I think `0_12` should not be valid because number litterals cannot have leading zeros.

**Comment by HertzDevil** [comment]
A small reminder: `_1` etc. in Ruby are anonymous block parameters since 2.7.

**Comment by BlobCodes** [comment]
I just found more currently allowed interger literals, which I think should be up to discussion.
`0x`, `0b` and `0o` are currently allowed (and interpreted as `0`).

In ruby, they raise the "numeric literal without digits" error.
In rust, they raise the "no valid digits found for number" error.

**Comment by oprypin** [comment]
My opinions

Literal | Now | Should be
--|--|--
1_ | :white_check_mark: | unexpected trailing underscore in "1_"
1_.1 | :white_check_mark: | unexpected trailing underscore in "1_"
1._1 | undefined method '_1' for Int32 | :arrow_left: 
||
1_e2 | :heavy_check_mark: | :arrow_left: 
1e_2 | :heavy_check_mark: | :arrow_left: 
||
0x_2 | :heavy_check_mark: | :arrow_left: 
0_x2 | unexpected token: x2 | :arrow_left: 
||
0b | :white_check_mark: | numeric literal without digits
||
0_12 | :white_check_mark: | octal constants should be prefixed with 0o
||
1__1 | :white_check_mark: | unexpected doubled underscore in "1__1"

Legend:
:heavy_check_mark: OK now and that's good
:white_check_mark: OK now but should be error
:arrow_left: Should stay as is

**Comment by oprypin** [comment]
Of those opinions, Python differs only for `1_e2` `1e_2` - both are errors actually!
But we must also take into account that changing this to an error would very likely break some code, so I am still certain we should keep it -- at the very least keep `1_e2` working.

**Comment by straight-shoota** [comment]
I can agree to that table.
Personally, I wouldn't mind allowing `1_.1` and `1_`. They're edge cases but unambiguous. But I'm fine with them being errors.

**Comment by beta-ziliani** [comment]
The [comment in #11211](https://github.com/crystal-lang/crystal/pull/11211#issuecomment-983071038) made me realize that we aren't mentioning the type suffix: even if we disallow trailing `_`, I would expect them to be valid prior to the type suffix, as in `1_i8`. Is it worth adding it to the table @oprypin ?

**Comment by BlobCodes** [comment]
That's already in the specs and most people use this style.
This cannot be changed, it would break the entire stdlib.
I think it doesn't need to be mentioned.

**Comment by oprypin** [comment]
In https://github.com/crystal-lang/crystal/pull/11211#discussion_r760368531 @BlobCodes seems to have a particular preference regarding these two cases, so let's vote on them:

**Comment by oprypin** [comment]
`1e_2`
:rocket: to keep this syntax valid
:tada: to turn this into an error

**Comment by oprypin** [comment]
`0x_2`
:rocket: to keep this syntax valid
:tada: to turn this into an error

**Comment by oprypin** [comment]
Note that `1_e2` is fully decided to remain valid
and `0_x2` is fully decided to be turned into an error

**Comment by oprypin** [comment]
I have an interesting finding.
In top 270 repositories on GitHub

<details><summary>Obtained as such</summary>

```bash
for i in {1..9}; do
  curl "https://api.github.com/search/repositories?q=language:crystal&sort=stars&order=desc&page=$i" >"repos${i}.json"
done

jq -r '.items | .[] | "https://github.com/\(.full_name)/archive/refs/heads/\(.default_branch).tar.gz"' repos*.json |
while read url; do
  echo "$url" && owner=$(echo "$url" | grep -Po '(?<=^https://github.com/)[^/]+') && 
  mkdir -p "$owner" && curl -L "$url" | tar xz -C "$owner" || break
done
```

</details>

I have the following numbers of occurrences:

* `1e2` &rarr; 176 via `grep -rE '\b[0-9]+e[0-9]+\b' --include='*.cr' | wc -l`
* `1_e2` &rarr; 0 via `grep -rE '\b[0-9]+_e[0-9]+\b' --include='*.cr' | wc -l`
* `1e_2` &rarr; 0 via `grep -rE '\b[0-9]+e_[0-9]+\b' --include='*.cr' | wc -l`



* `0x2` &rarr; 9673 via `grep -rE '\b0[xbo][0-9][0-9_]*\b' --include='*.cr' | wc -l`
* `0x_2` &rarr; 0 via `grep -rE '\b0[xbo]_[0-9_]+\b' --include='*.cr' | wc -l`

**Comment by oprypin** [comment]
Another syntax for discussion
* `2e` → 0 occurrences via `grep -rP '\b[0-9][0-9_]e\b(?![+\-])' --include='*.cr' | wc -l`

---

`2e`
:rocket: to keep this syntax valid
:tada: to turn this into an error

**Comment by oprypin** [comment]
Another syntax we'll just disallow in #11211, that @BlobCodes just found:

* `2e+_2` &rarr; 0 occurrences via `grep -rE '\b[0-9][0-9_]*e[+\-]_' --include='*.cr' | wc -l`
