### ISSUE TITLE
Casting NaN to Int32 should raise an exception

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/crystal#11224]
I was investigating an integer overflow, when I noticed that casting NaN to an integer actually returned a number. In my case I had a `-NaN` being casted as Int32::MIN.

I'm not sure what should actually happen, but since NaN doesn't have any possible integer representation, I think it should raise. I.e. that smells like *undefined behavior*, which seems to be confirmed by this [stackoverflow answer](https://stackoverflow.com/a/10366541).

~~On a larger extent, maybe float numbers that can't be represented by the destination integer should raise, since that's overflowing? Unless the developer accepts overflows with `#to_i!` of course.~~ see #11105

To reproduce:
```crystal
(0/0).to_i # => -2147483648
```

This likely affects other integer casts.

**Comment by asterite** [comment]
> On a larger extent, maybe float numbers that can't be represented by the destination integer should raise, since that's overflowing?

That's already the case. Try this:

```crystal
(Int32::MAX.to_f + 1).to_i
```

Note however that this isn't always the case because of a bug: https://github.com/crystal-lang/crystal/issues/11105

**Comment by HertzDevil** [comment]
Duplicate of #10421.
