### ISSUE TITLE
Support OpenSSL 3.0

### ISSUE THREAD

**Issue by syeopite** [crystal-lang/crystal#11231]
## Feature Request

OpenSSL 3.0 was just released last week https://www.openssl.org/blog/blog/2021/09/07/OpenSSL3.Final/ and some distros, like Alpine, has already migrated to it. https://pkgs.alpinelinux.org/package/edge/main/x86_64/openssl. However, Crystal doesn't support OpenSSL 3.0 so the following: 

```
require "digest/sha1"

Digest::SHA1.hexdigest("Test")
```

Results in a compile time error: 

```
^_/usr/bin/ld: D-igest5858S-H-A-1.o: in function `digest_size':
/usr/lib/crystal/openssl/digest.cr:75: undefined reference to `EVP_MD_size'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o /root/.cache/crystal/crystal-run-test.tmp  -rdynamic `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -lpcre -lm -lgc -lpthread -levent  -lrt -ldl`
```

Would it be possible to add support for OpenSSL 3.0? Thanks.

**Comment by Blacksmoke16** [comment]
Ref: https://www.openssl.org/docs/man3.0/man7/migration_guide.html
