### ISSUE TITLE
Error: undefined constant U

### ISSUE THREAD

**Issue by mamantoha** [crystal-lang/crystal#11244]
Hi team.

I didn't get how to reproduce this error.
But after https://github.com/crystal-lang/crystal/pull/10467 my code start fail.

This is the end to the outputt.

```
In /snap/crystal/874/share/crystal/src/array.cr:208:5

 208 | equals?(other) { |x, y| x == y }
       ^------
Error: instantiating 'equals?((Array(PG::BoolArray) | Array(PG::CharArray) | Array(PG::Float32Array) | Array(PG::Float64Array) | Array(PG::Int16Array) | Array(PG::Int32Array) | Array(PG::Int64Array) | Array(PG::NumericArray) | Array(PG::StringArray) | Array(PG::TimeArray)))'


In /snap/crystal/874/share/crystal/src/indexable.cr:413:33

 413 | def equals?(other : Indexable(U), & : T, U ->) : Bool forall U
                                     ^
Error: undefined constant U
```

Looks like a typo.

Let me know if I need to provide more info.

/cc @straight-shoota

**Comment by straight-shoota** [comment]
There is no obvious error with that def. I have no idea how `U` can be undefined since it's explicitly declared as a free variable.

Stdlib specs are passing.

https://github.com/crystal-lang/crystal/blob/685da9dc0e8128f5fc2c8760d02d0f9fa9351e7d/spec/std/array_spec.cr#L689-L698

We need some code to reproduce the error.

**Comment by mamantoha** [comment]
I will try to extract the code to reproduce this issue.

**Comment by HertzDevil** [comment]
The original error seems to come from here: https://github.com/mamantoha/clear/runs/3681933489

Reduced:

```crystal
alias Foo = Int32 | Array(Foo)
alias Bar = String | Array(Bar)

x = 1.as(Foo | Bar)
x == x # Error: undefined constant U
```

**Comment by rubyFeedback** [comment]
The magic constant U has been discovered!
