### ISSUE TITLE
Add Crystal::Macros::NumberLiteral#chr

### ISSUE THREAD

**Issue by postmodern** [crystal-lang/crystal#11256]
## Discussion

Please add `Crystal::Macros::NumberLiteral#chr`. This would be primarily useful for converting ASCII bytes into chars. I commonly need this when using macros to generate repetitive specs:

### Example

```crystal
{% for byte in 0x20..0x7e %}
context "when given byte {{ byte }}" do
  it "must return a printable character" do
    expect(subject.encode({{ byte }})).to eq({{ byte.chr }})
end
{% end %}
```

**Comment by asterite** [comment]
Note that you don't need to use a macro for this:

```crystal 
(0x20..0x7e).each do |byte|
  context "when given byte #{byte}" do
    it "must return a printable character" do
      expect(subject.encode(byte)).to eq(byte.chr)
  end
end
```

**Comment by postmodern** [comment]
Ah, hmm. Since I'm using [spectator]() it's macro system cannot be called within a enumerable loop for some reason:

```crystal
    (0x20..0x7e).each do |byte|
      context "when given #{byte.to_s(16)}" do
        it "must return ' #{byte.chr}'" do
          expect(subject % byte).to eq(" #{byte.chr}")
        end
      end
    end
```

```
There was a problem expanding macro 'context'

Code in spec/numeric/char_or_int_spec.cr:44:7

 44 | context "when given #{byte.to_s(16)}" do
      ^
Called macro defined in macro 'define_example_group'

 15 | macro context(what, *tags, **metadata, &block)

Which expanded to:

 > 1 |         
 > 2 | 
 > 3 |         class Group__temp_92 < SpectatorTestContext::Group__temp_51::Group__temp_89
                     ^
Error: can't declare class dynamically
```

**Comment by asterite** [comment]
What's the difference if you iterate inside a single spec? After all it's not like you can rerun a single spec in any of those ways.

**Comment by postmodern** [comment]
I could do that as a workaround, but then all of those edge-cases become a single test. If just one of the edge-cases fail, I won't see if any of the remaining edge-cases fail.

**Comment by postmodern** [comment]
I suppose I could rewrite the spec that `select`s/`reject`s the bytes and `expert(bad_chars).to eq([])`, or such.

**Comment by HertzDevil** [comment]
The opposite, `CharLiteral#ord`: #9830

Note however that `NumberLiteral` includes also the floating-point literals.

**Comment by asterite** [comment]
> If just one of the edge-cases fail, I won't see if any of the remaining edge-cases fail.

Won't you have to fix them all in any case?

Also, maybe you could duplicate the specs for edge cases, given they are edge cases. So you have one spec with non edge cases, and a few with edge cases.

Note that I'm proposing this because now you need chr, but given that huge spectator limitation I can imagine you and others will need more and more macro methods over time, and that's not feasible.

**Comment by asterite** [comment]
Actually... can't you do it like this?

```crystal
{% for byte in 0x20..0x7e %}
context "when given byte {{ byte }}" do
  it "must return a printable character" do
    expect(subject.encode({{ byte }})).to eq({{ byte }}.chr)
end
{% end %}
```

That is, move the `chr` call to happen at runtime.

**Comment by postmodern** [comment]
@asterite ah that's clever!

@HertzDevil ah then I might withdraw my proposal given there's no distinction between Integer literals and Float literals.
