### ISSUE TITLE
Add Crystal::Macros::NumberLiteral#to_s(base)

### ISSUE THREAD

**Issue by postmodern** [crystal-lang/crystal#11257]
## Discussion

It would be very useful to allow converting a number literal to an alternate base value when using macros. This would be mostly useful when generating repetitive specs with macros.

### Example

```crystal
{% for byte in (0x7f..0xff) %}
  context "when given the byte 0x{{ byte.to_s(16) }}" do
    ...
  end
{% end %}
```

**Comment by asterite** [comment]
Same as the other issue, you can do it like this:

```crystal
{% for byte in (0x7f..0xff) %}
  context "when given the byte 0x#{ {{ byte}}.to_s(16) }" do
    ...
  end
{% end %}
```

That is, move the `to_s(16)` call to happen at runtime.

**Comment by asterite** [comment]
Nevermind, that probably doesn't work in spectator because it probably needs the spec name to be a string literal...

**Comment by postmodern** [comment]
@asterite that also worked.
