### ISSUE TITLE
Run specs on macOS 11

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#11286]
Our macOS test jobs are pinned to 10.15 (#11282). We should test against macOS 11 as well, as soon as it works with nixpkgs (#11279).

A build matrix could be useful for that (see #11278).

**Comment by HertzDevil** [comment]
Do we still need a matrix after #12570 and #13748? Is 11 even relevant?

**Comment by straight-shoota** [comment]
It's probably okay to test against the latest version only.
