### ISSUE TITLE
Float.significant sometimes isn't accurate due to extra `.0`

### ISSUE THREAD

**Issue by syeopite** [crystal-lang/crystal#11322]
Follow up to what I mentioned in #11319

The standard library's `Number#significant` allows one to preserve X amounts of significant digits, while discarding the rest. The internal logic of which, first converts the results to an float, and then the final result after computation back to the input type.

However, with a float, it can get problematic; because `X.0` numbers have two significant figures. If I want to reduce it to a single significant digit, I'd expect to just get `X`.

But due to the aforementioned logic, you just get the same `X.0`, since the output value is again, a float. 

Examples:

```crystal
1.0.significant(1) # => 1.0
2.0.significant(1) # => 2.0
3.0.significant(1) # => 3.0
4.0.significant(1) # => 4.0
```

Unfortunately, there really isn't a easy way to resolve this due to the nature of floating-point numbers.

**Comment by asterite** [comment]
Could you clarify what's your expected behavior?

**Comment by asterite** [comment]
I guess... What's your use case? Where is this code used in your case?

**Comment by syeopite** [comment]
> Why not call to_i in that case?

If the number fluctuates, it's impossible to actually know whether to call to_i.  

> I guess... What's your use case? Where is this code used in your case?

CLDR number formatting. I know neither what number would be given, nor how many significant digits to preserve; just that it needs to be formatted a certain way depending on the parameters given.

**Comment by syeopite** [comment]
If the minimum/maximum amount of significant figures allows for it yes. For instance these patterns:

| Pattern | Number | Formatted number |
| ----------|------------|---------------------------|
| @@###| 1234.567 |1234.6|
| @@@@| 314.15 |314.2|
| @@@@@ | 314.15 |314.15||

You can find some more examples in the specs of the library I'm working on here:
 https://github.com/syeopite/lens/blob/master/spec/cldr/number-patterns_spec.cr#L282-L331

**Comment by syeopite** [comment]
> Is there any case where a formatted value will end up with ".0" at the end?

Unfortunately yes. 

| Pattern | Number | Formatted number |
| ----------|------------|---------------------------|
| @@| 1 |1.0|
| @@@@@| 1.1 |1.1000 |
| @@@@@ | 314 | 314.00|

> ...but that would be a breaking change and we can't do that.

That's understandable. I guess I'll implement this as part of the library I'm working on then. Thanks for the help!

**Comment by syeopite** [comment]
Yes, to implement this behavior numerically is impossible. You might be able to do some fancy analysis and return an integer instead but that'll have loads of edge cases. The only way to actually have the behavior I talked about above, is to perhaps just convert the entire method to a string operation; which again, is a rather large breaking change. 

The issue should just be closed.
