### ISSUE TITLE
docs: Negative count: -70 (ArgumentError)

### ISSUE THREAD

**Issue by GeopJr** [crystal-lang/crystal#11323]
Using `crystal docs` on https://github.com/GeopJr/libadwaita.cr, exits with the following (and without finishing generating the docs of course):

## Error

```bash
Negative count: -70 (ArgumentError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from __crystal_main
  from main
  from __libc_start_main
  from _start
  from ???
Error: you've found a bug in the Crystal compiler.
```

## Environment

```
Shards 0.16.0 (2021-10-14)
Crystal 1.2.0 (2021-10-14)

LLVM: 12.0.1
Default target: x86_64-pc-linux-gnu
```

## Reproduction

- `git clone https://github.com/GeopJr/libadwaita.cr`
- `cd libadwaita.cr`
- `shards install`
- `crystal docs`

This doesn't happen on version `1.1.1`

**Comment by straight-shoota** [comment]
...and it's already been fixed: https://github.com/icyleaf/markd/pull/43 
Thanks @icyleaf!

I'll pull in the upstream changes.

**Comment by icyleaf** [comment]
markd 0.4.2 was out.
