### ISSUE TITLE
Possible regex bug

### ISSUE THREAD

**Issue by sardaukar** [crystal-lang/crystal#11330]
## Bug Report

I think there's a potential Regex bug. I've tried using this regex:

```
/\s?(?<base_addr>[a-fA-F0-9]+):\s\s(?<byte_array>[a-fA-F0-9\s]{2}*)\s*(?<mnemonic>[A-Z]{2,}\s)\s*(?<label>.*)/
```
That works fine in Ruby (which makes me thing the regex should work in Crystal too) as you can see in https://rubular.com/r/A8u0sWtoXfeW2H, but

```crystal
 /\s?(?<base_addr>[a-fA-F0-9]+):\s\s(?<byte_array>[a-fA-F0-9\s]{2}*)\s*(?<mnemonic>[A-Z]{2,}\s)\s*(?<label>.*)/ =~  " cafd:  54 2e 64 02             ADD             G1e,#64 -> L01"

puts base_addr
```

Crashes with 

```
syntax error in eval:1
Error: invalid regex: nothing to repeat at 64
```

as you can see in https://carc.in/#/r/c2d4. Am I doing something wrong?

**Comment by HertzDevil** [comment]
`/a{2}*/` appears to be valid regex grammar in Ruby, which uses Oniguruma, but invalid in PCRE and most other regex libraries.

**Comment by sardaukar** [comment]
Ok, thanks. Would be cool to have a better error message.
