### ISSUE TITLE
HTTP::Client repeated usage results in compressed response body, but only on server keep alive timeout

### ISSUE THREAD

**Issue by daliborfilus** [crystal-lang/crystal#11354]
## Bug Report

```shell
❯ crystal -v
Crystal 1.2.1 [4e6c0f26e] (2021-10-21)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```

(confimed not working on `1.2.0` too)

**Short version:**

Using `HTTP::Client` instance multiple times with big enough interval between the calls to `exec` against gzip-enabled server causes the response body to be still compressed, but only if the client got disconnected by the server (e.g. because of keepalive timeout).
Repro case at the end of the issue.

**Full story:**

I have a synchronization project which uses two instances of `HTTP::Client` to execute requests to two backend servers.
Sometimes (but not always, only on specific conditions) the program crashes with this:

```
2021-10-24T07:12:19.025065Z  DEBUG - http.client: Performing request -- method: "GET", host: "redacted.local", port: 10443, resource: "/api/redacted"
2021-10-24T07:12:19.109426Z  DEBUG - redacted.api.http_client: got 200, 0 cookies
Unhandled exception: Unexpected char '' at line 1, column 1 (JSON::ParseException)
  from /usr/share/crystal/src/json/lexer.cr:331:7 in 'raise'
  from /usr/share/crystal/src/json/lexer.cr:327:5 in 'unexpected_char'
  from /usr/share/crystal/src/json/lexer.cr:326:11 in 'unexpected_char'
```

The exception is misleading, because the real response.body does contain data, but in what looks like a garbage (`response.body.size` is around 100kB of data in this case).
The issue happened very, VERY randomly, but always in the same place for specific test build. Reorganizing the code caused it to pop up at other places.

After hours of digging and testing various scenarios I found out that the response is still gzip compressed and that it occurs only if I have a long period of time between I talk to the same server again.
(I.e. requests in rapid succession were not a problem. The same URL then crashed 10 seconds later.)

If I disable the compression (using `client.compress = false` or `headers["Accept-Encoding"] = "identity"), everything works normally and survives the disconnect.

So the problem is compression + keep alive timeout = compressed (i.e. garbage) response body is returned.
Don't know if chunked response makes things even worse or not.

I see in the crystal source `src/http/client.cr` that you are attempting to reconnect `io` on server disconnected and you are parsing the request again.
(I cannot see any reason why the server should not decompress the data on the second try, but maybe I'm missing something.)

```cr

  # crystal/src/http/client.cr
  private def exec_internal(request)
    begin
      response = exec_internal_single(request)
    rescue IO::Error
      response = nil
    end
    return handle_response(response) if response

    # Server probably closed the connection, so retry one
    close
    request.body.try &.rewind
    response = exec_internal_single(request)
    return handle_response(response) if response

    raise IO::EOFError.new("Unexpected end of http response")
  end
```

Somehow something gets broken in the second case.

I saw that you remove "Content-Encoding" header from the response once the body is decompressed in `HTTP.parse_headers_and_body`.
But in the second (in my case, crashing) case, the response headers still contain "Content-Encoding: gzip" header.

**The decompression is never called in the case of reconnect.**

Workaround for this is to use single shot requests OR disable compression. (But my program makes thousands of requests (batch sync) and both are a bad solution.)

**Fully reproducible example:**

a) start a web server with small keepalive timeout and gzip compression enabled, like so:

- create file `default.conf` in current directory with contents:

```shell
echo "server { listen 8081 default_server; keepalive_timeout 3; gzip on; gzip_vary on; gzip_types text/plain; gzip_min_length 1; default_type text/plain; location / { return 200 'whatever'; } }" > default.conf
```

- run the server in a docker container (or standalone, as you like):

```shell
docker run --rm -ti -p 8081:8081 -v $PWD/default.conf:/etc/nginx/conf.d/default.conf:ro nginx:alpine
```

b) run this against it:

```cr
require "http"
require "uri"

typeof(HTTP::Headers)

# this monkeypatch watches on deletes
# and confirms that the second time, the delete is not called and the response is not decompressed
struct HTTP::Headers
  def delete(key : String)
    STDERR.puts "HTTP::Headers#delete(#{key}) (value: #{@hash[wrap(key)]?.inspect})"
    values = @hash.delete wrap(key)
    values ? concat(values) : nil
  end
end

def get(client, path) : Nil
  print "New request ", "#" * 50
  puts
  # headers = HTTP::Headers.new
  # headers["Accept"] = "text/plain"
  request = HTTP::Request.new("GET", path)
  # request.headers = headers
  response = client.exec(request)
  puts "Response status: #{response.status.inspect}"
  puts "Response headers: #{response.headers.inspect}"
  puts "Response body: #{response.body.inspect}"
end

uri = URI.parse("http://localhost:8081")
client = HTTP::Client.new(uri)
client.before_request do |request|
  # on the second run, this is run twice - meaning the request got sent again
  puts "Request headers: #{request.headers.inspect}"
end

# response should be okay:
get client, "/"
sleep 5 # this value must be larger than the keepalive_timeout

# response should be garbage:
get client, "/"
sleep 5

# response should be garbage:
get client, "/"
```

If everything goes according to plan, this should be your result:

```
❯ crystal run testing.cr
New request ##################################################
Request headers: HTTP::Headers{"Host" => "localhost:8081", "User-Agent" => "Crystal", "Accept-Encoding" => "gzip, deflate"}
HTTP::Headers#delete(Content-Encoding) (value: "gzip")
HTTP::Headers#delete(Content-Length) (value: nil)
Response status: OK
Response headers: HTTP::Headers{"Server" => "nginx/1.17.1", "Date" => "Sun, 24 Oct 2021 08:06:10 GMT", "Content-Type" => "text/plain", "Transfer-Encoding" => "chunked", "Connection" => "keep-alive", "Vary" => "Accept-Encoding"}
Response body: "whatever"
New request ##################################################
Request headers: HTTP::Headers{"Host" => "localhost:8081", "User-Agent" => "Crystal", "Accept-Encoding" => "gzip, deflate"}
Request headers: HTTP::Headers{"Host" => "localhost:8081", "User-Agent" => "Crystal", "Accept-Encoding" => "gzip, deflate"}
Response status: OK
Response headers: HTTP::Headers{"Server" => "nginx/1.17.1", "Date" => "Sun, 24 Oct 2021 08:06:15 GMT", "Content-Type" => "text/plain", "Transfer-Encoding" => "chunked", "Connection" => "keep-alive", "Vary" => "Accept-Encoding", "Content-Encoding" => "gzip"}
Response body: "\u001F\x8B\b\u0000\u0000\u0000\u0000\u0000\u0000\u0003+\xCFH,I-K-\u0002\u0000\xB3C\u0011N\b\u0000\u0000\u0000"
New request ##################################################
Request headers: HTTP::Headers{"Host" => "localhost:8081", "User-Agent" => "Crystal", "Accept-Encoding" => "gzip, deflate"}
Request headers: HTTP::Headers{"Host" => "localhost:8081", "User-Agent" => "Crystal", "Accept-Encoding" => "gzip, deflate"}
Response status: OK
Response headers: HTTP::Headers{"Server" => "nginx/1.17.1", "Date" => "Sun, 24 Oct 2021 08:06:20 GMT", "Content-Type" => "text/plain", "Transfer-Encoding" => "chunked", "Connection" => "keep-alive", "Vary" => "Accept-Encoding", "Content-Encoding" => "gzip"}
Response body: "\u001F\x8B\b\u0000\u0000\u0000\u0000\u0000\u0000\u0003+\xCFH,I-K-\u0002\u0000\xB3C\u0011N\b\u0000\u0000\u0000"
```

**Comment by BrucePerens** [comment]
Testing yesterday with Crystal 1.5 I get this pretty reliably after a few hundred API calls using `awscr-s3`. I also see it in other frequent API calls. I have kludged various things to check for the gzip magic number and uncompress if they see it. But it would be really nice if you'd get this one fixed.
