### ISSUE TITLE
Require the right-hand side of 1-to-n assignmens to be `Indexable`

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#11414]
Just to make sure again, should we _require_ the value on the right-hand side of 1-to-n assignments to be `Indexable` yet? Do we do anything to these cases?

```crystal
value = {0 => "x", 1 => "y", 2 => "z"}

# existing 1-to-n assignments (in a separate PR)
a, b, c = value

# 1-to-n splat assignments
# ill-formed because of `b = value[1..-2]`
a, *b, c = value

# 1-to-n splat assignments
# raises because of `b = value[-2]` and `c = value[-1]`
*_, b, c = value

# okay???
a, *b, c = Hash(Int32 | Range(Int32, Int32), String).new { |hsh, key| hsh[key] = 0 }
```

Related: https://github.com/crystal-lang/crystal/issues/10937#issuecomment-898461411

_Originally posted by @HertzDevil in https://github.com/crystal-lang/crystal/issues/10410#issuecomment-960486296_

**Comment by straight-shoota** [comment]
I'd say a restriction to `Indexable` would be good. The first case happens to work by chance, but I don't think it's an adequate use case. Multi-assign destruction is based on a collection with sequential items (that's expressed as `Indexable`). The fact that the same API for accessing this data is shared by other data types (such as `Hash`) is rather a coincidence. IMO it makes sense to require `Indexable`. If you want to use a hash as datasource like in the examples, you can just wrap it in a custom `Indexable` (which would just delegate to the hash).

We could consider adding `.as(Indexable)` instead of a dedicated compiler type check. That still adds a dependency on the `Indexable` type to the compiler, but it's not a built-in type.

**Comment by HertzDevil** [comment]
Fixing the splat-less ones (`a, b, c = value`) will introduce a breaking change, so this needs to be guarded.

Do we lump it together with other breaking changes related to multi-assigns? (https://github.com/crystal-lang/crystal/pull/11145#discussion_r748898621)

**Comment by oprypin** [comment]
Yes, I think so. I wouldn't even call it "lumpimg"; to the user it's all very related.

**Comment by oprypin** [comment]
Wait, this issue is about `Indexable`, I didn't notice.
That might be a separate thing entirely, if that's what you mean. I thought this one was meant for before 2.0.

**Comment by oprypin** [comment]
> Fixing the splat-less ones `(a, b, c = value)` will introduce a breaking change, so this needs to be guarded behind a flag.

Hmm, can test-ecosystem give some answer how bad of a breaking change it would be?

Depending on that, I see 2 main options: either simply changing it, or indeed only for the splat-less case guarding the addition of `Indexable` behind `strict_multi_assign`.

**Comment by oprypin** [comment]
Regardless though, we definitely need to add the `Indexable` check to the splat-ful cases now, if we're ever gonna do it. Which is possible to open a PR for already, if you're interested, and if the merge conflicts with #11145 won't be too bad
