### ISSUE TITLE
Missing debug information for constant read

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#11416]
Latest 1.2.1
```
$ crystal --version
Crystal 1.2.1 [4e6c0f26e] (2021-10-21)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```
A simple source
```
$ cat false.cr 
STDERR.puts "false"
exit(1)
```
Another error with `--debug`
```
$ crystal build --debug false.cr
Module validation failed: inlinable function call in a function with debug info must have a !dbg location
  %57 = call %"IO::FileDescriptor"** @"~STDERR:read"()
 (Exception)
  from /crystal/src/int.cr:541:9 in 'finish'
  from /crystal/src/compiler/crystal/codegen/codegen.cr:69:7 in 'codegen'
  from /crystal/src/compiler/crystal/compiler.cr:169:16 in 'compile'
  from /crystal/src/compiler/crystal/command.cr:296:3 in 'run'
  from /crystal/src/compiler/crystal.cr:11:1 in '__crystal_main'
  from /crystal/src/crystal/main.cr:110:5 in 'main'
  from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

And it was the same with `crystal 1.2.0 [9f90efe33] (2021-10-13)`

_Originally posted by @Val in https://github.com/crystal-lang/crystal/issues/11385#issuecomment-962652528_

**Comment by straight-shoota** [comment]
Found another related bug, also introduced by #10934.

```console
$ crystal build --debug samples/llvm/brainfuck.cr
Module validation failed: !dbg attachment points at wrong subprogram for function
!2261 = distinct !DISubprogram(name: "__crystal_main", linkageName: "__crystal_main", scope: !2262, file: !2262, type: !2263, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0, retainedNodes: !2266)
void (i32, i8**)* @__crystal_main
  %56 = load %"Array(String)"*, %"Array(String)"** @ARGV, !dbg !2718
!2718 = !DILocation(line: 5, column: 19, scope: !2719)
!2719 = distinct !DISubprogram(name: "~LLVM::initialized:init", linkageName: "~LLVM::initialized:init", scope: !2720, file: !2720, line: 5, type: !2263, scopeLine: 5, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0, retainedNodes: !2347)
!2719 = distinct !DISubprogram(name: "~LLVM::initialized:init", linkageName: "~LLVM::initialized:init", scope: !2720, file: !2720, line: 5, type: !2263, scopeLine: 5, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0, retainedNodes: !2347)
```

**Comment by straight-shoota** [comment]
Are reading constants and reading class vars the only locations where #10934 could've introduced a bug? I think so, but I'm not sure. Let's not miss something. What about external vars? Or any of the reads inside pointerof?

I'm also wondering why the missing debug locations don't show up more often. Stdlib is full of `STDERR.puts` and similar constant reads. But it appears to be only an issue in the main scope (put the constant read in a method and everything is fine). Recreating `STDERR` with a custom constant doesn't error either:
```cr
FOO = IO::FileDescriptor.from_stdio(2)
FOO.puts "foo"
```

**Comment by HertzDevil** [comment]
The constant needs to be read before it is assigned, otherwise no lazy initialization is done. Presumably something in the prelude uses `STDERR` before kernel.cr is required.

If this indeed happens only at the top-level scope then class variable read calls cannot fail because they are no top-level class variables.

**Comment by straight-shoota** [comment]
No, I mean the constant read happens in main scope. This code doesn't error:

```cr
def foo
  STDOUT.puts "false"
end

foo
```

Adding a read to `STDOUT` *after* the call to `foo` is fine as well. But *before* `foo`, it errors.
