### ISSUE TITLE
Int32 binary representation is different for 0

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#11425]
representing `0` as a binary string is different then every other binary representation of an in.

https://play.crystal-lang.org/#/r/c8am

code:
```crystal
puts 0.to_s(2)
puts Int32::MAX.to_s(2)
```
output:
```
0
1111111111111111111111111111111
```

**Comment by Blacksmoke16** [comment]
What would you expect it to be? It's zero so you only need one bit to represent it?

**Comment by wontruefree** [comment]
I would expect 32 zeros.

**Comment by wontruefree** [comment]
I guess I interpreter this as the binary representation of a 32 bit integer.

**Comment by Blacksmoke16** [comment]
You can get this behavior via `0.to_s 2, precision: 32`.

From the docs:

> precision specifies the minimum number of digits in the written string. If there are fewer digits than this number, the string is left-padded by zeros.

**Comment by wontruefree** [comment]
that works for me.  I can close this based on that.  But should there be a way to show the full base 2 representation of a number.  or the base N representation of any number?

**Comment by oprypin** [comment]
It seems that your base claim is false. You only checked two edge examples, but actually all lengths are different. And everything is consistent.

```crystal
puts 0.to_s(2)
puts 123456.to_s(2)
puts Int32::MAX.to_s(2)
puts
puts 0.to_s
puts 123456.to_s
puts Int32::MAX.to_s
```

```
0
11110001001000000
1111111111111111111111111111111

0
123456
2147483647
```

**Comment by wontruefree** [comment]
would it be beneficial to have a `#binary` and `#hex` method to display the numbers in there string format?  I was using it and think it might be useful.

**Comment by straight-shoota** [comment]
@wontruefree What would be the representation format of these methods? Would it be something like `"0#{to_s(2)}"` and `"0x#{to_s(16)}"`?
