### ISSUE TITLE
Cannot install Crystal with Homebrew

### ISSUE THREAD

**Issue by marekkwiatkowski** [crystal-lang/crystal#11501]
```
brew install crystal     
fatal: Could not resolve HEAD to a revision
Warning: No available formula with the name "crystal".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Comment by Blacksmoke16** [comment]
I'm pretty sure this is more so a brew issue than Crystal. Something from https://stackoverflow.com/questions/65605282/trying-to-install-hugo-via-homebrew-could-not-resolve-head-to-a-revision would probably resolve it as its the same error just for a different package.

**Comment by straight-shoota** [comment]
This is the wrong place to report this issue. It's clearly a homebrew issue.

You may also find help on our community channels https://forum.crystal-lang.org/ and https://crystal-lang.org/community/#chat
