### ISSUE TITLE
Compiler is not resolving which overload to use based on block arity

### ISSUE THREAD

**Issue by postmodern** [crystal-lang/crystal#11518]
## Bug Report

I ran into a weird edge-case where I need to define multiple overloads of `initialize`, but where one overload takes a block that accepts no arguments and another overload takes a block which accepts one argument. Depending on which overload I try calling and the order in which they are defined, the program may or may not compile. Trying to call both overloads fails regardless of order they are defined.

### Example

```crystal
class Sub

  @pattern : String | Regex

  @replace : String | Hash(String,String) | Nil

  @block : Proc(String,String) | Proc(String) | Nil

  def initialize(@pattern : String | Regex, @replace : String | Hash(String,String))
    @block = nil
  end

  def initialize(@pattern : String | Regex, &block : -> String)
    @replace = nil
    @block   = block
  end

  def initialize(@pattern : String | Regex, &block : String -> String)
    @replace = nil
    @block   = block
  end

end

block_with_args = ->(match : String) {
  match + "lol"
}

block_with_no_args = ->() {
  "lol"
}

sub1 = Sub.new("x", &block_with_no_args)
sub2 = Sub.new("x", &block_with_args)

p sub1
p sub2
```

### Error

```
In test.cr:33:12

 33 | sub1 = Sub.new("x", &block_with_no_args)
                 ^--
Error: wrong number of block argument's parameters (given 0, expected 1)
```

**Comment by HertzDevil** [comment]
Block signatures don't overload.

**Comment by straight-shoota** [comment]
This is not a bug but expected and documented behaviour (See [overloading docs](https://crystal-lang.org/reference/syntax_and_semantics/overloading.html)). For overloading, it only matters if a def accepts a block or not. Type restrictions of the block parameter do not have any relevance.

So in your example, the second method definition with a different block type restriction simply overrides the previous one.

**Comment by asterite** [comment]
Slightly more concise, if you want:

```crystal
class Sub
  @pattern : String | Regex

  @replace : String | Hash(String, String) | Nil

  @block : Proc(String, String) | Proc(String) | Nil

  def initialize(@pattern : String | Regex, @replace : String | Hash(String, String))
  end

  def initialize(@pattern : String | Regex, @block : -> String)
  end

  def initialize(@pattern : String | Regex, @block : String -> String)
  end
end

block_with_args = ->(match : String) {
  match + "lol"
}

block_with_no_args = ->{
  "lol"
}

sub1 = Sub.new("x", block_with_no_args)
sub2 = Sub.new("x", block_with_args)

p sub1
p sub2
```
