### ISSUE TITLE
`Regex#name_table` returns `Hash(UInt16, String)`

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#11528]
`Regex#name_table` returns a hash with `UInt16` as key type. That number type is an implementation detail. We should not expose that. Except for very specific situations, stdlib APIs should try to use the standard type (`Int32`).

So I propose to change `Regex#name_table` to return `Hash(Int32, String)`.

This is a breaking change. However, I doubt it has a big impact. I think we could consider it acceptable for a minor release. I would see this as a bug in the API. `UInt16` should've never been exposed there.

**Comment by Sija** [comment]
That was already done as a part of #9760, perhaps it could be revisited?
