### ISSUE TITLE
UTF-8 console I/O on Windows

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#11527]
A Windows console cannot display UTF-8 characters out of the box:

```crystal
puts "×😂" # => ├ù≡ƒÿé
```

From my investigation there are some ways to fix this:

* Use `SetConsoleCP(CP_UTF8)` and `SetConsoleOutputCP(CP_UTF8)`. This appears to be broken to some extent before Windows 10.
* Detect whether a file descriptor represents a terminal, then convert to/from UTF-16 and use `ReadConsoleW` / `WriteConsoleW` if that is the case. [Python does this](https://www.python.org/dev/peps/pep-0528/).
* Use `_setmode(_fileno(...), _O_U16TEXT)` and always convert to/from UTF-16 when interfacing with the standard streams. This causes an [assertion error](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setmode?view=msvc-170#remarks) for non-wide functions.
* Do nothing and direct the users to run `chcp` or configure their terminals themselves.

[This thread](https://github.com/microsoft/terminal/issues/10055) might be useful for consideration. Also note that `cmd.exe` and Windows Powershell will not support anything outside the BMP regardless of how Crystal handles this, because they use UCS-2 internally, not UTF-16 (Windows Terminal will display emojis just fine, and so does Visual Studio Code's integrated terminal, for example).

**Comment by straight-shoota** [comment]
It seems like this does not work correctly for reading from stdin (#13731). We might want to remove setting the console codepage.
