### ISSUE TITLE
GNU optional arguments in `OptionParser`

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#11537]
There should be a way to enable strict GNU-style parsing of optional arguments in `OptionParser`. The only rule is that if an option has an optional parameter, the argument must follow the option flag immediately (with an `=` for long options). This would allow us to implement [`--color[=when]`](https://github.com/crystal-lang/crystal/pull/4499#issuecomment-348306820).

The API would be:

```crystal
class OptionParser
  def initialize(*, @gnu_optional_args : Bool = false)
    # ...
  end

  def self.parse(args = ARGV, *, gnu_optional_args : Bool = false) : self
    parser = OptionParser.new(gnu_optional_args: gnu_optional_args)
    yield parser
    parser.parse(args)
    parser
  end
end
```

This implies that all optional parameters of a single `OptionParser` behave identically; it is impossible to mix the two styles in one `OptionParser`. The new style is disabled by default to avoid a breaking change.

The following is the current behaviour of `OptionParser`:

```crystal
require "option_parser"

def parse_args(args)
  x = nil
  y = nil
  rest = [] of String

  OptionParser.parse(args) do |parser|
    parser.on("-a [x]", "short optional arg") { |x_| x = x_ }
    parser.on("--b [y]", "long optional arg") { |y_| y = y_ }
    parser.unknown_args { |rest_, _| rest = rest_ }
  end

  {x, y, rest}
rescue OptionParser::InvalidOption
  "invalid"
end

parse_args %w(-a)     # => {"", nil, []}
parse_args %w(-a1)    # => {"1", nil, []}
parse_args %w(-a=)    # => {"=", nil, []}
parse_args %w(-a=1)   # => {"=1", nil, []}
parse_args %w(-a 1)   # => {"1", nil, []}
parse_args %w(-a =)   # => {"=", nil, []}
parse_args %w(-a =1)  # => {"=1", nil, []}

parse_args %w(--b)    # => {nil, "", []}
parse_args %w(--b1)   # => "invalid"
parse_args %w(--b=)   # => {nil, "", []}
parse_args %w(--b=1)  # => {nil, "1", []}
parse_args %w(--b 1)  # => {nil, "1", []}
parse_args %w(--b =)  # => {nil, "=", []}
parse_args %w(--b =1) # => {nil, "=1", []}
```

With the new rule the changes shall be as follows:

```crystal
parse_args %w(-a 1)   # => {"", nil, ["1"]}
parse_args %w(-a =)   # => {"", nil, ["="]}
parse_args %w(-a =1)  # => {"", nil, ["=1"]}

parse_args %w(--b 1)  # => {nil, "", ["1"]}
parse_args %w(--b =)  # => {nil, "", ["="]}
parse_args %w(--b =1) # => {nil, "", ["=1"]}
```

If combined with #10981, then this also affects the final option in a single token of multiple short options; if `-a` and `-b[y]` are short options, then `-ab 1` shall yield an empty argument under the new style, and `"1"` under the existing style.

**Comment by straight-shoota** [comment]
This has already been mentioned in #5338. I think it's a good solution and could also help for #11136 if we make compiler and spec arguments follow GNU style.

**Comment by straight-shoota** [comment]
I'm wondering about the `-a [x]`/`--b [y]` syntax for defining arguments with optional values. With GNU style, these notations are invalid. So they surely shouldn't show up in documentation. And I don't think it makes sense to use them in the definition either, because there's a dissonance to the usage pattern.

I'd suggest to use `-a=[x]`/`--b=[y]` instead, and enforce that style when `gnu_optional_args` is true.

**Comment by HertzDevil** [comment]
The calls to `OptionParser#on` are not necessarily close to the placement of `gnu_optional_args: true`, and the `gnu_optional_args` argument might not even be true all the time. Nothing says non-GNU `OptionParser`s cannot use `-a [x]` and `--b [y]`, and there is little utility to raise only when GNU style is used. Everything will be fine as long as we normalize the help text to `-a[x]` and `--b[=y]`; this can be done regardless of the value of `gnu_optional_args`, because those syntaxes are always accepted.

**Comment by straight-shoota** [comment]
Sure, we can transform everything for the usage message. But what's the point, really? Why not use the universal notation in the first place? We can make that mandatory, at least for `gnu_optional_args` because it's a newly introduced feature and thus doesn't break existing code.

**Comment by HertzDevil** [comment]
Because that's imposing a particular code style restriction for the sake of making non-GNU style `OptionParser`s look like GNU style. But `gnu_optional_args` has nothing to do with style; it only deals with argument parsing, and it alone does not even imply that the whole `OptionParser` conforms to GNU conventions. It also adds unnecessary friction when porting option parsers from other programming languages which may not actually support the GNU flag syntax.
