### ISSUE TITLE
Verifying Bcrypt passwords of version '2b' instead of '2a'

### ISSUE THREAD

**Issue by docelic** [crystal-lang/crystal#11584]
Recently I noticed that when I receive Bcrypt hashes from Node.js programs, I can't successfully verify them in Crystal.
Upon closer examination, the issue is that Node.js specified the hash version as `2b`.
This version seems unsupported in Crystal, even though for passwords less than 256 chars in length it is identical to `2a` which *is* supported.

Example:
```crystal
require "crypto/bcrypt"
 
# Version 2a works
pass = Crypto::Bcrypt::Password.new "$2a$10$XERbBh4EeswcvuiiwFMc8OWfrD3w/AIQ308iGMLSOENWSaKEWhsDy"
p pass.verify "test" # ==> true
 
# Version 2b silently doesn't work
# (2b has the same hash for password "test", just the version is `2b`)
pass = Crypto::Bcrypt::Password.new "$2b$10$XERbBh4EeswcvuiiwFMc8OWfrD3w/AIQ308iGMLSOENWSaKEWhsDy"
p pass.verify "test" # ==> false
```

Play: https://play.crystal-lang.org/#/r/cft3

Additional discussion on SO:
https://stackoverflow.com/questions/54135603/why-would-2a-vs-2b-matter

**Comment by naqvis** [comment]
Problem is `Password#verify` method, which performs a complete comparison (version, cost, salt, digest) and that shouldn't be correct. It should only be comparing the digest of provided hash and that of calculated digest of provided password string.

Fix should require changing the https://github.com/crystal-lang/crystal/blob/6529d725a/src/crypto/bcrypt/password.cr#L68 to something like below

```Crystal
  def verify(password : String) : Bool
    hashed_password = Bcrypt.new(password, salt, cost)
    hashed_pwd_digest = Base64.encode(hashed_password.digest,hashed_password.digest.size-1)
    Crypto::Subtle.constant_time_compare(@digest, hashed_pwd_digest)
  end  
```

Play: [https://play.crystal-lang.org/#/r/cfwk](https://play.crystal-lang.org/#/r/cfwk)

**Comment by straight-shoota** [comment]
Apparently, there is currently no validation of the version field in a serialized password. I think we should restrict that to only those versions that we know about and are supported. That means `2a`, with a fix for this also `2b`. I suppose `2` should probably also be supported.
