### ISSUE TITLE
The "new" method doesn't work as expected with pointers and sets?

### ISSUE THREAD

**Issue by adamroyjones** [crystal-lang/crystal#11590]
I'm sorry if this is a foolish question, but I was caught by surprise by this.

In a little toy program, I was trying to lazily get around the size limit for hashes by constructing a smaller hash whose values are pointers to sets. A simple example (for the purposes of illustration) might look like this:

```crystal
hash = Hash(Int32, Pointer(Set(Int32))).new

(0..3).each do |n|
  set = Set(Int32).new
  ptr = pointerof(set)
  hash[n] = ptr
end
```

However, the pointers so constructed all point to the same address. In particular:

```crystal
hash[0].value << 1
hash[1].value.includes?(1) # true
```

The behaviour can be seen in the playground [here](https://play.crystal-lang.org/#/r/cfva). 

This doesn't happen in Go:

```go
package main

import (
	"fmt"
)

type Set = map[int]bool

func main() {
	hash := make(map[int](*Set))

	for i := 0; i <= 3; i++ {
		set := make(Set)
		hash[i] = &set
	}

	(*hash[0])[1] = true
	fmt.Printf("%v\n%v\n", *hash[0], *hash[1])
}
```

The behaviour can be seen in the playground [here](https://play.golang.com/p/l30daJHB8ao).

Is this expected behaviour? I'm feeling a bit lost.

**Comment by oprypin** [comment]
This is the program that achieves what I think you tried to achieve.

```crystal
hash = Hash(Int32, Set(Int32)).new

(0..3).each do |n|
  set = Set(Int32).new
  hash[n] = set
end
```

The fact that Set is a Class already causes it to always be an implicit pointer to data on the heap.

Pointers in Crystal are not to be used in everyday programming, they're only for low-level manipulations.
You're causing undefined behavior by taking a pointer to a value that's on the stack. The undefined behavior just so happens to manifest as re-using the same memory address for the same variable in 3 different iterations of the loop, thus indeed giving the same answer to `pointerof`

**Comment by oprypin** [comment]
I'll further elaborate if you're curious.
Both in Crystal and Go the `map` in question is a pointer to actual data on the heap.
In Go apparently `&x` means get the address that is being pointed to.
In Crystal `pointerof(x)` just means get the address of the variable, so the address *of* the pointer's address.

Despite me mentioning the heap so many times, the pointer's address is still on the stack. Both in Go and in Crystal.  Just that in Crystal getting the address of the heap data of a thing that happens to be a `Class` is not a valid thing to do, there's no language support for understanding whatever is at that address.
But if you do want to get that memory address for whatever reason (this isn't one), the syntax is `x.as(Void*)`, not `pointerof(x)`.

**Comment by adamroyjones** [comment]
> I'll further elaborate if you're curious.

I'm nothing but curious!

Thanks for your patient explanation—this has all helped me a lot. I know the documentation warns that there's undefined behaviour with pointers in Crystal, but I didn't take sufficient heed of that. It's been an indirectly useful lesson to take that kind of warning very seriously.

The change you suggested works beautifully, except now I need more memory... 😓

Thanks again—and sorry for picking a template that marked this as a bug!

**Comment by HertzDevil** [comment]
`Set` is not a `Class`. However it contains a single `Hash` as its member, and that in turn is a `Class`, so the same semantics apply.
