### ISSUE TITLE
Improve type inference for nested expression inside `if`

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#11609]
If you do something like this:

```crystal
if true && a = 1
  p! typeof(a)
end
```

The compiler will know that `a` is an `Int32` inside the `if`.

However if you do this:

```crystal
if true && (a = 1; true)
  p! typeof(a)
end
```

then the type of `a` is `Int32 | NIl` inside the `if`, which isn't quite right.

This isn't a big deal: it's pretty rare to want to write conditions like that.

My main use case was another feature I had in mind. In Ruby you can do this:

```ruby
point = rand < 0.5 ? [1, 2] : nil
if (x, y = point)
  puts x, y
end
```

Note that you can use a multi-assign inside an `if` condition. The meaning of that is: if `point` is truthy, unpack the values. Otherwise that condition is falsey. And I think that's pretty convenient. Sometimes you have code like this:

```crystal
points = [{1, 2}, {3, 4}]

while point = points.shift?
  x, y = point
  puts x, y
end
```

It would be nice to be able to write it like this:

```crystal
points = [{1, 2}, {3, 4}]

while (x, y = points.shift?)
  puts x, y
end
```

To implement that, I was thinking that we could transform the above to this:

```crystal
while (temp = points.shift?) && (x, y = temp; true)
  puts x, y
end
```

But this doesn't work because `x` and `y` will be nilable inside the `while` body.

**Comment by konovod** [comment]
can't we transform it to 
```crystal
while temp = points.shift?
  x, y = temp
  puts x, y
end
```
instead?

**Comment by asterite** [comment]
@konovod How would you transform this:

```crystal
if (x, y = something) && something_else
  puts "Hello!"
end
```

**Comment by HertzDevil** [comment]
It works in Ruby because `nil` is a valid value for multiple assignment:

```ruby
a, *b, c = nil
a # => nil
b # => []
c # => nil
```

And because the multi-assign returns the value being set (see #7707):

```ruby
if (a, b = [nil, nil]) # okay, condition is array which is truthy
  p a # => nil
end
```

**Comment by asterite** [comment]
Makes total sense!

I guess to implement what I want we'll have to hardcode the rule of a multi-assign inside an if, which maybe isn't ideal.

For now I'm going to close this.
