### ISSUE TITLE
Error: undefined method 'to_i32' for Array(String)

### ISSUE THREAD

**Issue by d80ep08th** [crystal-lang/crystal#11618]
Crystal -v : 1.2.2
From the past two weeks I have been working on crystal language. Recently I decided to write a generic blockchain to not only get a better hang on how blockchain works but also to learn crystal language in depth.
This is my repo: https://github.com/d80ep08th/crystal_study_room/tree/blockchain

I was using this link as a guide : https://www.toptal.com/blockchain/crystal-programming-language-tutorial

After many hours of hacking I found an issue in the main crystal lang repo which is why I am posting this issue here.

In /home/linuxbrew/.linuxbrew/Cellar/crystal/1.2.2/src/hash.cr:226:48

 226 | initial_capacity = (initial_capacity || 0).to_i32
                                                  ^-----
Error: undefined method 'to_i32' for Array(String) (compile-time type is (Array(String) | Int32))

**Comment by Sija** [comment]
Without reproduction code such report is meaningless.

**Comment by d80ep08th** [comment]
What if I updated the Readme.md?

**Comment by Blacksmoke16** [comment]
Reduced:

```cr
Hash(String, String).new initial_capacity: (Array(Int32).new || 10)
```
```
In /usr/lib/crystal/hash.cr:226:48

 226 | initial_capacity = (initial_capacity || 0).to_i32
                                                  ^-----
Error: undefined method 'to_i32' for Array(Int32) (compile-time type is (Array(Int32) | Int32))
```

https://play.crystal-lang.org/#/r/cgmq/edit

Is a case of the `Hash` constructor's `initial_capacity` parameter not having a type restriction. I.e. can pass it whatever and since an array is truthy, it tries to convert that to an `Int32`, hence the error.

@d80ep08th I looked and don't see you using a `Hash` at all, so if you could try and reduce the code that produces this, that would be great.

**Comment by d80ep08th** [comment]
Thank you @Blacksmoke16  , that really helped . I pushed new changes yesterday . Everything builds fine but sadly I dont have any output, everything just builds and that is it.  Kemal server doesnt start , I cant tell why. Is there something more versatile than : crystal run src/file.cr -- progress  ?

**Comment by j8r** [comment]
That would be a breaking change, having a type restriction with `initial_capacity : Int32?` (or `Int?`) would yield a better error, with a better documentation.

**Comment by konovod** [comment]
> Thank you @Blacksmoke16 , that really helped . I pushed new changes yesterday . Everything builds fine but sadly I dont have any output, everything just builds and that is it. Kemal server doesnt start , I cant tell why. Is there something more versatile than : crystal run src/file.cr -- progress ?

Your code is stuck in `proof_of_work` because of `Digest::SHA256.hexdigest("(message)")` (instead of `hexdigest(message)`)

**Comment by d80ep08th** [comment]
WOAH WOAH WOAH  @konovod , that totally worked!
