### ISSUE TITLE
`Indexable.each_cartesian` can't be further processed

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#11612]
## Bug Report

This code:

```crystal
it = Indexable.each_cartesian([[1, 2], [3, 4]])
it.select { |pair| true }
```

doesn't compile:

```
In /usr/local/Cellar/crystal/1.2.1/src/iterator.cr:947:32

 947 | Select(typeof(self), T, U).new(self, func)
                                  ^--
Error: no overload matches 'Iterator::Select(Iterator::Singleton(Iterator::Stop), Iterator::Stop, Bool).new' with types Iterator::Singleton(Iterator::Stop), Proc(Array(Int32), Bool)

Overloads are:
 - Iterator::Select(I, T, B).new(iterator : I, func : (T -> B))
```

The reason is this line:

https://github.com/crystal-lang/crystal/blob/fdcbcf4149cda377070f0f1b41583f54bb24b3f0/src/indexable.cr#L388

`Iterator.of(value)` will return an iterator that includes `Iterator(typeof(value))`. But when you have `Iterator(T)`, you never expect `T` to include `Iterator::STOP`. `T` always excludes the stop value. And with this implementation the compiler thinks "stop" could be returned.

The solution is simple: just don't do this optimization. Or maybe we need an `Iterator(T).empty`.

**Comment by HertzDevil** [comment]
We could reject `Iterator::Stop` inside the `typeof`, or we could, as you suggest, have the empty iterator:

```crystal
module Iterator(T)
  private struct Empty(T)
    include Iterator(T)

    def next
      stop
    end
  end

  def self.empty
    {% if @type == Iterator %}
      Empty(NoReturn).new
    {% else %}
      Empty(T).new
    {% end %}
  end
end
```

I think it makes sense to be able to do so, just as we can construct an empty `Tuple` or `Array` or `Hash`.

**Comment by asterite** [comment]
Feel free to send a PR with that. I'm taking some vacations starting tomorrow.

**Comment by asterite** [comment]
Actually, returning a union might be slower in the general case because every call to next will do a dispatch. I think we can at least start with my PR.
