### ISSUE TITLE
--mcpu doesn't work on `crystal spec`

### ISSUE THREAD

**Issue by yxhuvud** [crystal-lang/crystal#11670]
## Bug Report
Reproducer: 
1: Go to any crystal project. 
2: Execute `crystal spec --mcpu znver2`. You may have to change znver2 to something that matches whatever processor you have. Be aware that `native` probably doesn't work due to #11415
3: Get error message: 
`Error: Invalid option: --mcpu`

I find this error strange:
1: If the command is executed in a non crystal directory, no error is emitted
2: It is not great to not be able to run tests with the same set of optimizations as a production build would use, and a production build may very well want to set the mcpu flag - on my system it gives 5-15% extra performance.
3: --mcpu is a flag that is a likely target for a global env setting using `CRYSTAL_OPTS`. Then it should work for everything that looks at `CRYSTAL_OPTS`.

- Include Crystal compiler version (`crystal -v`) and OS. If possible, try to see if the bug still reproduces on master.

Crystal 1.2.2 [6529d725a] (2021-11-10)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu

**Comment by yxhuvud** [comment]
I have reason to believe that the compilation actually work fine, but that the flags are somehow propagated to the execution of the compiled output of the `spec` command. In one of my projects I do some monkeypatching in `prelude` with log output, and some of that output is actually outputted before the error message.

**Comment by yxhuvud** [comment]
Ok, if I forcibly remove `--mcpu` and the following argument from the options variable before `src/compiler/command/spec.cr#105` then things work. That is probably not the right way though, as the `--release` flag has already been removed at that point, and I havn't figured out where yet.

**Comment by yxhuvud** [comment]
Looks like the difference is coming from the difference between `setup_simple_compiler_options` that spec uses, and `create_compiler` that the other build variants use. I guess it would be somewhat simple to copy `--mcpu` from the second to the first, but having identical flags defined in several different methods isn't ideal, and could be error prone. :thinking:

**Comment by yxhuvud** [comment]
So I see 4 paths forward: 
1: Add the options to `setup_simple...` and accept the duplication
2: Try to unify the options accepted for doing the actual compilation so that they are defined in one place. Not certain how easy it will be to structure it in such a way that the error text output remains well structured.
3: Strip the options to avoid it being a problem. This has the effect that the compiler options in question doesn't apply to `spec`, meaning that it may make finding certain kinds of errors a bit harder. 
4: Declare that `mcpu` and similar is not valid in `CRYSTAL_OPTIONS`

Thoughts? I'd prefer 1 or 2.

**Comment by straight-shoota** [comment]
I'd go for 2. It makes sense to have the same set of options for all commands that include codegen for example. If it needs a bigger refactor, that's probably a still a good idea.
It's easy to miss such slight differences in CLI options and we should strive to have the same interface everywhere (when it makes sense).

**Comment by BlobCodes** [comment]
btw `--mcpu` also doesn't work with `crystal eval` - maybe that's the same issue?
```
$ crystal eval 'puts "Hello World"' --mcpu zenv2
syntax error in eval:1
Error: postfix decrement is not supported, use `exp -= 1`
```

**Comment by lbguilherme** [comment]
@BlobCodes for `crystal eval` the options must come before the source code. Either way, `--mcpu` is not supported there.

**Comment by BlobCodes** [comment]
@lbguilherme using `--release` after the source code works.
For `--mcpu`, I think it should be supported in `crystal eval`.
