### ISSUE TITLE
Regression in number literal parser

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#11671]
Parsing number literals starting with the sequence `0_` is broken in master. This only possible with a base prefix, an unprefixed literal can't start with `0`.

```cr
0b0_1 # Error: 0b0_1 doesn't fit in an UInt64.`
```

This regression was introduced in #11211

/cc @BlobCodes

**Comment by BlobCodes** [comment]
This seems to be the underlying issue:
```crystal
"0_1".to_i(base: 2, underscore: true)
# => Unhandled exception: Invalid Int32: 0_1 (ArgumentError)
```

In String#to_unsigned_info the following happens:
- The first digit is a zero and is read here
  https://github.com/crystal-lang/crystal/blob/6529d725a61ed0ff83f9d9efdd18bb7229c9cebc/src/string.cr#L588
- last_is_underscore is unconditionally set to true
  https://github.com/crystal-lang/crystal/blob/6529d725a61ed0ff83f9d9efdd18bb7229c9cebc/src/string.cr#L619
- The first "real digit" read is an underscore, raising the error
  https://github.com/crystal-lang/crystal/blob/6529d725a61ed0ff83f9d9efdd18bb7229c9cebc/src/string.cr#L624-L625

We could probably set `last_is_underscore` to `false` after reading a leading zero.
