### ISSUE TITLE
A modest proposal for Enum.select

### ISSUE THREAD

**Issue by wyhaines** [crystal-lang/crystal#11699]
## Feature Request

I'd like to put forth for discussion the addition of an `Enum.select` class method .

The idea is to be able to iterate through a set of enums, running a block for each, returning an array that contains only those for which the block evaluated to true.

The particular use case that made me think of this was a set of enums that represent bit positions in a flag byte:

For example:

```crystal
enum Flags : UInt8
  EndStream  = 0x01
  EndHeaders = 0x04
  Padded     = 0x08
  Priority   = 0x20
end
```

I have a flag byte declared as an `UInt8`, and I want to get a list of the flags that are set on that byte (an instance variable `@flags`):

```crystal
def flags
  Flags.select do |flag|
    @flags.bits_set?(flag.to_u8)
  end
end
```

Assuming that `@flags` is set to, as an example, 9, this would return:

```crystal
[EndStream, Padded]
```

The test implementation that I built is a variation of the implementation for `each`:

```crystal
abstract struct Enum
  def self.select(& : self -> Bool)
    result = [] of self
    {% for member in @type.constants %}
      {% unless @type.annotation(Flags) && %w(none all).includes?(member.stringify.downcase) %}
        result << new({{ @type.constant(member) }}) if yield new({{@type.constant(member)}}), {{@type.constant(member)}}
      {% end %}
    {% end %}
    result
  end
end
```

One can, of course, build the `#flags` method using the already existing `Enum.each` method, but this just feels like a natural and logical use of `select` to me.

Thoughts?

I am happy to construct this as a full-fledged PR if others see the value.

**Comment by lbguilherme** [comment]
What about using [`Enum.values`](https://crystal-lang.org/api/1.2.2/Enum.html#values%3AArray%28self%29-class-method)?

```cr
def flags
  Flags.values.select do |flag|
    @flags.bits_set?(flag.to_u8)
  end
end
```

**Comment by straight-shoota** [comment]
What's the point of this custom logic anyways?
It would seem you could just make `Flags` an actual flags enum, return `Flags.new(@flags)` and call it a day.

**Comment by wyhaines** [comment]
> What's the point of this custom logic anyways? It would seem you could just make `Flags` an actual flags enum, return `Flags.new(@flags)` and call it a day.

Ah! So.... From the docs:

```
An enum can be marked with the @[Flags] annotation. This changes the default values:

@[Flags]
enum IOMode
  Read  # 1
  Write # 2
  Async # 4
end

Additionally, some methods change their behaviour.
```

However, the behavior changes don't appear to be mentioned, and I didn't do enough spelunking to totally suss them out.

This modest proposal is totally unneeded.  :)  I will close it. Thanks @straight-shoota!
