### ISSUE TITLE
Complex.zero returns unexpeceted #sign

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#11700]
## Bug Report

Some Complex numbers that have zeros return `0` and `0i` but on the default `zero` case it returns `NaN` and `NaNi`.  This was unexpected to me.  After bringing it up on Discord it seems like it might be a bug.

Here is an example of an expected `0` sign. https://play.crystal-lang.org/#/r/cjvt
```crystal
require "complex"

p Complex.new(1, 0).sign
```
output:
```
(1.0 + 0.0i)
```

Here is the case I am not sure if it is correct. https://play.crystal-lang.org/#/r/cjvv
```crystal
require "complex"

p Complex.zero.sign
```
output
```
(-NaN - -NaNi)
```

**Comment by martinhart** [comment]
Forgive me if I'm not fully understanding the problem, but what would we expect the correct output to be here?  #sign is currently implemented using division, and division by 0 is resulting in NaN in this case.

**Comment by asterite** [comment]
I think (0, 0) is expected to be returned.

That said, `sign` for `Complex` is a bit strange, I think we should remove that method.

**Comment by beta-ziliani** [comment]
According to [the wikipedia](https://en.wikipedia.org/wiki/Sign_function)
> For reasons of symmetry, and to keep this a proper generalization of the signum function on the reals, also in the complex domain one usually defines, for z = 0:
    sgn ⁡ ( 0 + 0 i ) = 0
 
So I would classify this as an outright bug. @wontruefree out of curiosity, what brought you to this function?

**Comment by wontruefree** [comment]
@beta-ziliani I have been looking for undocumented and under documented features and trying to understand them and add docs for them

**Comment by beta-ziliani** [comment]
My physicist wife tells me this function is useful to have, so it's better to fix it and document it.
