### ISSUE TITLE
Missing option to determine visibility of `TypeNode`

### ISSUE THREAD

**Issue by Hadeweka** [crystal-lang/crystal#11705]
Currently, there is now direct way to test the visibility of a `TypeNode` in a macro, except for converting it to a `Path` by passing it to other macro methods (which seems rather clunky). 

A quick way to determine the visibility of a `TypeNode` would be helpful for the cases in which a `TypeNode` is directly returned (e.g. `TypeNode#ancestors`).

Pull request #11696 implements the `TypeNode#private?` method, but another approach could be to instead use a `visibility` method, which returns a `SymbolLiteral`. 

However, a class can only be private or public, so a `SymbolLiteral` is not necessary, except maybe for consistency with other `visibility` methods (which on the other hand can also return a `:protected`). 

Changing the PR to a `SymbolLiteral` would be unproblematic, though.

**Comment by straight-shoota** [comment]
I think it would make more sense to copy `#visibility` from `Def` and `Macro`. We don't need another way to express the same thing.

**Comment by vlazar** [comment]
Ruby went with separate methods instead of `visibility` as well https://rubyreferences.github.io/rubychanges/3.1.html#methodunboundmethod-public-private-protected

**Comment by Blacksmoke16** [comment]
So sounds like separate methods is the way to go? @Hadeweka, able to pick this back up?

**Comment by Sija** [comment]
Note that this change was reverted in Ruby 3.2 (perhaps only temporarily): https://rubyreferences.github.io/rubychanges/3.2.html#methodpublic-protected-and-private-are-removed

**Comment by Hadeweka** [comment]
> So sounds like separate methods is the way to go? @Hadeweka, able to pick this back up?

I could change the pull request to also add `TypeNode#public?`, but as protected types don't seem to exist, it would only return the oppositve value of `private?` (and therefore not technically be necessary).

**Comment by straight-shoota** [comment]
I don't think the addition of predicate methods (`#public?`, `#protected`, `#private?`) necessarily means deprecation of `#visibility`. They serve different purposes and there are use cases for both.

**Comment by Blacksmoke16** [comment]
Ah right, one that I can think of it reconstructing the node, which would be a lot easier with `#visibility`. In that case, we should probably add both the predicate methods and `#visibility` to `TypeNode` then yea?

**Comment by Hadeweka** [comment]
So is the consensus to add both `#visibility` and `#public?`/`#private?` to `TypeNode`?

If so, I can update my pull request.

**Comment by Blacksmoke16** [comment]
@Hadeweka I don't suppose this is something still on your radar?

**Comment by Hadeweka** [comment]
Whoops, kind of forgot about this over time, sorry.

I actually managed to circumvent the problem for my projects, but if it's still relevant for someone, I could finally update my pull request 😃

**Comment by Blacksmoke16** [comment]
That would be great yes if you have the time :)

**Comment by Hadeweka** [comment]
I rewrote the pull request (while accidentally force-pushing to the newest Crystal commit to the branch, sorry for that):

https://github.com/crystal-lang/crystal/pull/11696
