### ISSUE TITLE
[RFC] Splat in block arguments

### ISSUE THREAD

**Issue by stugol** [crystal-lang/crystal#1171]
In Ruby, a block can accept a splat argument. In Crystal, I get errors:
```
def fn1
	yield
end
fn1 { |*args| puts "Hi" }
```
Gives ```expecting block argument name, not *```. How can I define a variadic non-captured block?

**Comment by asterite** [comment]
You can't right now. Why do you need this?

**Comment by stugol** [comment]
Well, for the same reason I need variadic methods. If you need one, you need the other, surely?

Specifically, in this case, I was trying to write a forwarder, like this Ruby version I use:
```
	def delegate *method_names, &target_getter
		method_names.each { |m|
			define_singleton_method(m) { |*args| target_getter.().send m, *args }
		}
	end
```
Usage:
```
	class SlidingWindowStream
		attr_reader :window_start_position, :window_end_position
		def initialize(stream, window_size, options = {})
			@stream = stream
			delegate(:read, :readbyte, :readbytes) { @stream }
```
I've written a macro instead, and it seems to work, but my point remains. If variadic methods are needed, then variadic blocks are also needed.

**Comment by stugol** [comment]
Bump for variadic blocks.

**Comment by asterite** [comment]
Please test both this and #392. I think I got it right, considering all border cases, but who knows. It would be nice to have this battle tested before releasing 0.18.0 :-)

I'll try to see if with all of this `Enumerable` can be made `Enumerable(*T)`... of course we can only make this change after 0.18.0.
