### ISSUE TITLE
`OptionParser` doesn't parse anything

### ISSUE THREAD

**Issue by spindlebink** [crystal-lang/crystal#11723]
I just updated to 1.3 from 1.1 and it looks like somewhere in between the `OptionParser` has stopped working entirely. The following code never evaluates the `-t`/`--test` option, but the `Received arguments:` message prints with the expected array of arguments.
```crystal
require "option_parser"

puts "Received arguments: #{ARGV}"

OptionParser.parse(ARGV) do |parser|
  parser.on "-t", "--test", "Test option parser" do
    puts "Got argument `-t`/`--test`."
    exit 0
  end

  puts "No matching argument `-t`/`--test` found."
  exit 1
end
```

On Ubuntu 21.10, Crystal version:
```
Crystal 1.3.0 [a3ee70ca0] (2022-01-06)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by Blacksmoke16** [comment]
I'm pretty sure this is expected. The `.parse` method executes, comes across the `#on` method, which essentially registers it as a callback and does not execute immediately. It then goes past that and prints the `No matching argument` message and subsequently exits. If you remove the `exit 1` you can see it prints all three messages if you provide that option.

It's also the same behavior going back to `1.1.1`: https://play.crystal-lang.org/#/r/ckmg versus https://play.crystal-lang.org/#/r/ckmh. So if your code isn't working, then there must be something else going on.

**Comment by spindlebink** [comment]
Shoot, my mistake. I was a little curious as to how something like this could've gotten past development anyway.
