### ISSUE TITLE
RFC6331: Moving DIGEST-MD5 to Historic

### ISSUE THREAD

**Issue by Neustradamus** [crystal-lang/crystal#11731]
Dear @crystal-lang team,

In first, I wish you a Happy New Year!

20 November 2008: CRAM-MD5 to Historic:
- https://tools.ietf.org/html/draft-ietf-sasl-crammd5-to-historic-00

29 June 2017: CRAM-MD5 to Historic:
- https://tools.ietf.org/html/draft-zeilenga-luis140219-crammd5-to-historic-00

July 2011: RFC6331: Moving DIGEST-MD5 to Historic:
- https://tools.ietf.org/html/rfc6331

I add same about SCRAM-MD5.

There are now:
- July 2010: RFC5802: Salted Challenge Response Authentication Mechanism (SCRAM): SASL and GSS-API Mechanisms: https://tools.ietf.org/html/rfc5802 (SCRAM-SHA-1 and SCRAM-SHA-1-PLUS)
- July 2010: RFC5803: Lightweight Directory Access Protocol (LDAP) Schema for Storing Salted: Challenge Response Authentication Mechanism (SCRAM) Secrets: https://tools.ietf.org/html/rfc5803
- November 2015: RFC7677: SCRAM-SHA-256 and SCRAM-SHA-256-PLUS: Simple Authentication and Security Layer (SASL) Mechanisms: https://tools.ietf.org/html/rfc7677

Soon:
- SCRAM-SHA-512(-PLUS): https://tools.ietf.org/html/draft-melnikov-scram-sha-512
- SCRAM-SHA3-512(-PLUS): https://tools.ietf.org/html/draft-melnikov-scram-sha3-512

**Comment by jhass** [comment]
Sorry, I'm not sure Shay action points you expect here :)

**Comment by Neustradamus** [comment]
@jhass: Thanks for your quickly answer!

Here: https://github.com/crystal-lang/crystal/search?q=md5

It is linked my second ticket, about SCRAM-SHA-* and SCRAM-SHA-*-PLUS.

**Comment by jhass** [comment]
I'm still very unclear on what concrete steps you'd like to see to close this "bug".

**Comment by Neustradamus** [comment]
@jhass: It is easy, you can remove the support of unsecure DIGEST-MD5, and add the support of SCRAM:
- https://github.com/crystal-lang/crystal/issues/11730

**Comment by jhass** [comment]
Just removing such things definitely is not a sane way forward for a language's standard library. 

Also being a standard library we probably should discuss each use separately, I doubt a very generic issue like this will lead to a fruitful discussion :)

**Comment by Neustradamus** [comment]
@jhass: It is to show you the urgency to add SCRAM :)

**Comment by jhass** [comment]
If this is about adding SCRAM, then what did you open #11730 for?

**Comment by Neustradamus** [comment]
Two tickets are linked.

One is for adding SCRAM and this ticket is to disable or remove old MD5.

**Comment by konovod** [comment]
The only usages of MD5 in repository linked with cryptography is, well, explicitly disabling MD5 in TLS by default. Remaining usages are specs, implementation and non-cryptographic usages.

**Comment by straight-shoota** [comment]
RFC6331 is about MD5 as a SASL mechanism. There is no such thing in Crystal's standard library.
I don't see any actionable item here.

**Comment by Neustradamus** [comment]
@konovod, @straight-shoota: It is here: Disable maybe but present in the code:
- https://github.com/crystal-lang/crystal/search?q=md5

We are in 2022, time to add a real security with SCRAM.

Other libs and softwares have already support, there is a list here:
- https://github.com/scram-xmpp/info/issues/1

I will not cited all here...

**Comment by straight-shoota** [comment]
Sorry, can you please tell *exactly* what you want to do? I can't derive any meaning from that link to GitHub search.

**Comment by Neustradamus** [comment]
@straight-shoota: We are in 2022, time to go in the future, I have already said all here and in https://github.com/crystal-lang/crystal/issues/11730 about DIGEST-MD5 and SCRAM.

In more or instead of DIGEST-MD5:
- spec/std/scram/...
- spec/std/crystal/scram/...
- src/scram/...

**Comment by konovod** [comment]
@Neustradamus, I think there is a confusion between `DIGEST-MD5` and `MD5 digest`. Former is an authentification mechanism that isn't and never was part of Crystal library. Latter is a checksum algorithm that is known to be insecure for more than 10 years and still has some valid use cases (such as checking that file was changed in a situations when you don't need to protect against tampering attempts). `DIGEST-MD5` can't be removed as it isn't implemented, `MD5 digest` can't be removed as some users still need md5 checksum and "digest" is just a namespace for checksum algorithms.

**Comment by Neustradamus** [comment]
@konovod: Ok, thanks, we can close it.
But the other ticket about SCRAM is a good point to be added.
