### ISSUE TITLE
[Enhancement] Enable per default a progress-bar counter when "crystal build" is used

### ISSUE THREAD

**Issue by rubyFeedback** [crystal-lang/crystal#11737]
Hey crystal-devs,

I recently used GraalVM and native-image. This is quite awesome - it worked for me on first
try. Perhaps you crystal guys can also add crystal to GraalVM polyglot, but this is not the
issue here, I just wanted to briefly mention it.

native-image shows stuff to the user, e. g. what it is doing. 

I just did the following in crystal:

    crystal build hello_world_greeter.cr  --release

And ... no output at all. So I don't know how much this will take or what is done.

Would it be possible to add more information during the build by default? E. g.
"30% done" or "doing this" and "doing that" - anything that would indicate to
the user what it is done? A bit similar to native-image in GraalVM, so that we
get an idea whether anything is happening or not. Right now we just wait
until ... it's done, but we don't know how long it will take. So perhaps someone
could think of improvements here. That's it for this suggestion, thanks for
reading!

**Comment by vlazar** [comment]
You can see help on `build` command:

```
crystal build --help
```

Try adding these flags:
```
    -s, --stats                      Enable statistics output
    -p, --progress                   Enable progress output
    --verbose                        Display executed commands
```
