### ISSUE TITLE
IO.pipe gets stuck after feeding in 0x10000 bytes

### ISSUE THREAD

**Issue by wolfgang371** [crystal-lang/crystal#11749]
The following code hangs in the `IO.copy`:

```crystal
input = IO::Memory.new("a"*0x10001) # 0x10000 works, 0x10001 doesn't
reader, writer = IO.pipe
IO.copy(input, writer) # doesn't get past this copy in case of 0x10001 above
writer.close
while l=reader.gets
    # puts(l) # optionally clutter the console
end
```

It does work if I decrease by one byte.

What I actually wanted to do is to sandwich the bytes from one stream between some prologue and epilogue. For that I tried piping things together but somehow it didn't work out for larger chunks. (The above code is just the stripped-down version.)

I couldn't find any buffer size limitation - if there's a better way to achieve the goal.

I have crystal 1.3.0 on Ubuntu 18.04

**Comment by Blacksmoke16** [comment]
I'm _pretty_ sure this has something to do with using `IO.pipe`. In that some buffer fills up, and since nothing is reading the data it stays full and blocks waiting for that to happen. Try spawning another fiber for the `IO.copy` and `writer.close` part:

```cr
input = IO::Memory.new("a"*0x10001) # 0x10000 works, 0x10001 doesn't
reader, writer = IO.pipe
spawn do
  IO.copy(input, writer) # doesn't get past this copy in case of 0x10001 above
  writer.close
end
while l = reader.gets
  puts(l) # optionally clutter the console
end
```
this seems to do what you want.

**Comment by wolfgang371** [comment]
yes :) it does!
I also tried fibers upfront with my original code, but it didn't work out - I have to put all of the "producer" logic into the fiber (obviously), then it also works there.
For the example above I somehow forgot to give it a try.
Thanks!

**Comment by straight-shoota** [comment]
I'm wondering if there should be some mention of such gotchas in the API docs.
