### ISSUE TITLE
Crystal interpreter cannot find pthread

### ISSUE THREAD

**Issue by BlobCodes** [crystal-lang/crystal#11792]
## Bug Report

Trying to run `crystal i` fails with the following exception:
<details>
<summary>Exception</summary>

```
cannot find -lpthread
Linker arguments: -L/usr/lib64/crystal -lpthread -levent -lrt -ldl
Search path: /usr/lib64/llvm12/lib:/lib64:/usr/lib64:/lib:/usr/lib:/usr/lib64/crystal (Crystal::Loader::LoadError)
  from src/compiler/crystal/loader.cr:74:31 in 'load_library'
  from src/compiler/crystal/loader.cr:42:7 in 'new'
  from src/compiler/crystal/loader/unix.cr:51:7 in 'parse'
  from src/compiler/crystal/interpreter/context.cr:365:1 in 'loader'
  from src/compiler/crystal/interpreter/context.cr:378:5 in 'c_function'
  from src/compiler/crystal/interpreter/compiler.cr:1860:17 in 'compile_lib_call'
  from src/compiler/crystal/interpreter/compiler.cr:1764:7 in 'visit'
  from src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from src/compiler/crystal/interpreter/compiler.cr:2977:5 in 'accept_with_wants_value'
  from src/compiler/crystal/interpreter/compiler.cr:2967:5 in 'request_value'
  from src/compiler/crystal/interpreter/compiler.cr:578:7 in 'visit'
  from src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from src/compiler/crystal/interpreter/compiler.cr:2977:5 in 'accept_with_wants_value'
  from src/compiler/crystal/interpreter/compiler.cr:2967:5 in 'request_value'
  from src/compiler/crystal/interpreter/compiler.cr:1219:5 in 'visit'
  from src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from src/compiler/crystal/interpreter/compiler.cr:566:7 in 'visit'
  from src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from src/compiler/crystal/interpreter/compiler.cr:234:5 in 'compile_def'
  from src/compiler/crystal/interpreter/compiler.cr:1956:7 in 'create_compiled_def'
  from src/compiler/crystal/interpreter/compiler.cr:1777:22 in 'visit'
  from src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from src/compiler/crystal/interpreter/compiler.cr:234:5 in 'compile_def'
  from src/compiler/crystal/interpreter/compiler.cr:1956:7 in 'create_compiled_def'
  from src/compiler/crystal/interpreter/compiler.cr:1777:22 in 'visit'
  from src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from src/compiler/crystal/interpreter/compiler.cr:447:7 in 'visit'
  from src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from src/compiler/crystal/interpreter/compiler.cr:234:5 in 'compile_def'
  from src/compiler/crystal/interpreter/compiler.cr:1399:5 in 'get_const_index_and_compiled_def'
  from src/compiler/crystal/interpreter/compiler.cr:2463:27 in 'initialize_const_if_needed'
  from src/compiler/crystal/interpreter/compiler.cr:1371:9 in 'visit'
  from src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from src/compiler/crystal/interpreter/compiler.cr:2977:5 in 'accept_with_wants_value'
  from src/compiler/crystal/interpreter/compiler.cr:2967:5 in 'request_value'
  from src/compiler/crystal/interpreter/compiler.cr:2121:9 in 'compile_call_args'
  from src/compiler/crystal/interpreter/compiler.cr:1773:5 in 'visit'
  from src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from src/compiler/crystal/interpreter/compiler.cr:234:5 in 'compile_def'
  from src/compiler/crystal/interpreter/compiler.cr:1399:5 in 'get_const_index_and_compiled_def'
  from src/compiler/crystal/interpreter/compiler.cr:680:31 in 'visit'
  from src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from src/compiler/crystal/interpreter/compiler.cr:2881:5 in 'visit'
  from src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from src/compiler/crystal/interpreter/compiler.cr:566:7 in 'visit'
  from src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from src/compiler/crystal/interpreter/compiler.cr:2977:5 in 'accept_with_wants_value'
  from src/compiler/crystal/interpreter/compiler.cr:2971:5 in 'discard_value'
  from src/compiler/crystal/interpreter/compiler.cr:2829:7 in 'visit'
  from src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from src/compiler/crystal/interpreter/compiler.cr:566:7 in 'visit'
  from src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from src/compiler/crystal/interpreter/compiler.cr:234:5 in 'compile_def:closure_owner'
  from src/compiler/crystal/interpreter/compiler.cr:2929:5 in 'visit'
  from src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from src/compiler/crystal/interpreter/compiler.cr:566:7 in 'visit'
  from src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from src/compiler/crystal/interpreter/compiler.cr:234:5 in 'compile_def:closure_owner'
  from src/compiler/crystal/interpreter/compiler.cr:2929:5 in 'visit'
  from src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from src/compiler/crystal/interpreter/compiler.cr:566:7 in 'visit'
  from src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from src/compiler/crystal/interpreter/compiler.cr:165:5 in 'compile'
  from src/compiler/crystal/interpreter/interpreter.cr:207:5 in 'interpret'
  from src/compiler/crystal/interpreter/repl.cr:146:5 in 'interpret'
  from src/compiler/crystal/interpreter/repl.cr:150:5 in 'interpret_and_exit_on_error'
  from src/compiler/crystal/interpreter/repl.cr:140:5 in 'load_prelude'
  from src/string.cr:278:18 in 'run'
  from src/compiler/crystal/command/repl.cr:10:7 in 'repl'
  from src/compiler/crystal/command.cr:102:7 in 'run'
  from src/compiler/crystal/command.cr:51:5 in 'run'
  from src/compiler/crystal/command.cr:50:3 in 'run'
  from src/compiler/crystal.cr:11:1 in '__crystal_main'
  from src/crystal/main.cr:115:5 in 'main_user_code'
  from src/crystal/main.cr:101:7 in 'main'
  from src/crystal/main.cr:127:3 in 'main'
  from /lib64/libc.so.6 in '??'
  from /lib64/libc.so.6 in '__libc_start_main'
  from /var/mnt/media/Projects/Other/crystal-git/.build/crystal in '_start'
  from ???
```
</details>

Before the new loader was merged, it worked. (1.3.2 works for me)

The pthread library is installed:
```
$ find /usr/lib -name "*pthread*"
/usr/lib/libpthread.so.0
$ find /usr/lib64 -name "*pthread*"
/usr/lib64/libpthread.so.0
/usr/lib64/pkgconfig/libevent_pthreads.pc
/usr/lib64/pkgconfig/pthread-stubs.pc
/usr/lib64/libevent_pthreads.so
/usr/lib64/libpthread.a
/usr/lib64/libpthread_nonshared.a
/usr/lib64/libevent_pthreads-2.1.so.7
/usr/lib64/libevent_pthreads-2.1.so.7.0.1

```

```
$ bin/crystal -v
Crystal 1.4.0-dev [197465c86] (2022-02-03)

LLVM: 13.0.0
Default target: x86_64-redhat-linux-gnu
```

**Comment by straight-shoota** [comment]
This worked before merging #11579 because the original implementation simply swallowed link errors from missing libraries and just used the libs loaded in the compiler itself as fallback. `Crystal::Loader` doesn't do that anymore, it errors when it can't find a shared lib that it's told to load. If a lib is supposed to be missing in interpreted mode, the respective link annotation must be guarded behind a `unless flag?(:interpreted)`.

It looks like the library is technically present on your system, but the loader can't find because there's not symlink from `libpthread.so` (to `libpthread.so.0`).

**Comment by asterite** [comment]
> simply swallowed link errors from missing libraries and just used the libs loaded in the compiler itself as fallback

And that's actually a good thing, right? If the symbol is already present in the compiler, why bother looking it up somewhere else and, worse, failing if we can't find another one?

**Comment by straight-shoota** [comment]
No, it's not good. This means the interpreter would use different libraries than in compiled mode. We can't get 100% same link behaviour for compiled and interpreted programs, but it should be as close as possible.

If the loader fails to find a library, it means there's something wrong. Getting an error for that allows to fix it.
When we ignore the error and the missing library wasn't already loaded in the compiler (or the loaded version misses symbols), you would only get an error that the symbol can't be found, but not that the entire library is missing.

**Comment by acimnotes** [comment]
Sorry if it's a different subject, just installed Crystal on Widows WSL-1 using Ubuntu distro from your official repo. And `crystal i` gives this error: `Crystal was compiled without interpreter support`. I'd love to try the new interpreter mode. Where can I find a repo with the interpreter enabled? Or do I compile it myself from sources?

**Comment by straight-shoota** [comment]
@acimnotes The interpreter is not available in the current release builds, you have to built it yourself. See https://crystal-lang.org/2021/12/29/crystal-i.html for information.

**Comment by asterite** [comment]
I found a few things:
- the call to `load_current_program_handle` happens after the loader tries to load the libraries, at which point it fails and it doesn't even reach the `load_current_program_handle` method
- in my case it fails to load "pthread", but if I change the calls to `load_library` to be `load_library?`, everything works fine

So for now I'm going with those changes locally to be able to use the interpreter, mainly to fix other bugs.

**Comment by straight-shoota** [comment]
Yes, that's all clear to me. Avoiding errors on a missing library makes things work when the library is already loaded in the compiler. But the error is intended. 

The problem with silencing these errors is when the library you want to link against is not already loaded in the compiler.

Take this example:
```cr
@[Link("foobar")]
lib LibFooBar
  fun foobar : Void
end

LibFooBar.foobar
```
If `libfoobar` does not exist, it errors with ``undefined reference to `foobar'``. This suggests `libfoobar` was correctly loaded but didn't provide the requested symbol. That's at least misleading, if not completely wrong. The error message should say that `libfoobar` could not be loaded: `cannot find -lfoobar`.

We should figure out *why* loading that library failed instead of adding another workaround on top of the existing workaround to even lookup symbols loaded in the compiler.

Could you look where your `libpthread.so` - that's supposed to be loaded - is located?

**Comment by asterite** [comment]
In compiled mode, what's the error you get for the above snippet?

**Comment by straight-shoota** [comment]
`cannot find -lfoobar`

**Comment by BlobCodes** [comment]
```
$ echo '               
@[Link("foobar")]
lib LibFooBar
  fun foobar : Void
end

LibFooBar.foobar
' > test.cr

$ crystal run ./test.cr
/usr/bin/ld: cannot find -lfoobar (this usually means you need to install the development package for libfoobar)
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o /var/home/blobcodes/.cache/crystal/crystal-run-test.tmp  -rdynamic -L/usr/lib64/crystal -lfoobar -lpcre -lm -lgc -lpthread -levent  -lrt -ldl`

# Using a random library, renamed to libfoobar.so
$ crystal run ./test.cr --link-flags="-L/home/blobcodes"
/usr/bin/ld: _main.o: in function `__crystal_main':
/var/home/blobcodes/test.cr:7: undefined reference to `foobar'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o /var/home/blobcodes/.cache/crystal/crystal-run-test.tmp -L/home/blobcodes -rdynamic -L/usr/lib64/crystal -lfoobar -lpcre -lm -lgc -lpthread -levent  -lrt -ldl`
```

**Comment by straight-shoota** [comment]
@BlobCodes Any chance you're using glibc 2.34? https://developers.redhat.com/articles/2021/12/17/why-glibc-234-removed-libpthread#performance_considerations
That would explain why there's not symlink for `libpthread.so` on your machine.

In compiled mode, that doesn't matter because there's an empty `libpthread.a` which can be linked at compile time and essentially avoids any errors about a missing library. The interpreter however can't load a static library, it expects to load a dynamic library `libpthread.so`.

**Comment by BlobCodes** [comment]
Yes, I have `glibc-2.34-24.fc35.x86_64` (fedora 35) installed.

**Comment by asterite** [comment]
Huh, I thought the error was going to say "undefined reference to ..." but it actually says the missing library. I probably misremember things.

I guess now I also think it makes sense to have `Crystal::Loader` work the way it works now. We just have to figure out how to find `pthread`, `iconv`, etc., at least on mac, for interpreted mode. I assume it works on unix...
