### ISSUE TITLE
Colorize docs are wrong

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#11828]
Take a look at the docs:

https://crystal-lang.org/api/1.3.2/Colorize.html

For example:

```crystal
require "colorize"

"foo".colorize(0, 255, 255) # => "foo" in aqua

# This is the same as:

"foo".colorize(Colorize::ColorRGB.new(0, 255, 255)) # => "foo" in aqua
```

^ None of the above work

```crystal
require "colorize"

"foo".colorize(Colorize::Color256.new(208)) # => "foo" in orange
```

Doesn't work!

The only thing that did work was:

```crystal
"foo".colorize.fore(Colorize::ColorRGB.new(0, 255, 255))
```

**Comment by HertzDevil** [comment]
`Color256` is doing the right thing:

```crystal
"foo".colorize(Colorize::Color256.new(208)).to_s.chars
# => ['\e', '[', '3', '8', ';', '5', ';', '2', '0', '8', 'm', 'f', 'o', 'o', '\e', '[', '0', 'm']
```

It works on my Visual Studio Code terminal which has `TERM=xterm-256color`.

I think we only need to add the missing RGB overload(s).

**Comment by asterite** [comment]
To compensate that fact that the docs are wrong, I'd like to thanks whoever added this to colorize. I wanted to colorize a text with rainbow colors and after I found out how to do it it was a breeze!
