### ISSUE TITLE
Path Traversal Bug in `HTTP::StaticFileHandler`

### ISSUE THREAD

**Issue by beta-ziliani** [crystal-lang/crystal#11826]
In Windows both `\` and `/` are accepted as path delimiters, but `HTTP::StaticFileHandler` isn't considering `\` as such.

**Comment by straight-shoota** [comment]
I checked what some other static web servers do on windows. I used the default server implementations in Ruby (`httpd`) and Python (`http.server`) and apache with default configuration.

Ruby seems to be entirely disallow backslashes in the request path. It results in a *Bad Request*  error.
Python seems to have some buggy support for file names including backslashes on Windows. If you request `back\slash.txt`, you get a redirect to `back\slash.txt/` and that shows the directory.
Apache seems to treat backslashes as directory separators.

Using the replacement character directly (or rather URI-escaped) seems to always work: `/back%EF%81%9Cslash.txt`.

Also worth noting: Browsers typically convert backslashes into forward slashes in the URL.

**Comment by straight-shoota** [comment]
https://github.com/crystal-lang/crystal/pull/11847 should fix this issue by mapping backslashes in a request path to a replacement character, that Windows also recognizes. Thus requesting a path such as `/foo\bar` will have the same semantics on Unix-like systems as well as Windows.

After that we're just missing specs for this.
