### ISSUE TITLE
Add a compiler message that `WeakRef` doesn't apply to modules

### ISSUE THREAD

**Issue by spindlebink** [crystal-lang/crystal#11833]
I got tripped up this morning because it looks like `WeakRef` can't apply to module references. I assume that's inherent to what modules are, but the error message provided was generic and a while to figure out.
```crystal
require "weak_ref"

module Thing
end

class A
  include Thing
end

class B
  @test : WeakRef(Thing)

  getter test

  def initialize(with_thing)
    @test = WeakRef(Thing).new(with_thing)
  end
end

v = A.new
x = B.new(v)

puts x.test.value # Error: can't cast Pointer(Void) to (Thing | Nil)
```
Once you know why the error's showing up, it makes sense, but I think it'd be helpful to include a *why* here, at least to catch similar mistakes:
```crystal
class B
  @test : WeakRef(Thing) # Error: can't create a weak reference to a module
end
```

**Comment by straight-shoota** [comment]
Casting to and from a pointer type (like `Pointer(Void)`) only works for pointers and references. Or rather reference-like types, that includes unions including only references or `Nil`). See `Type#reference_like?`: https://github.com/crystal-lang/crystal/blob/e3ffc77b0b1124a8a51570ca7143c4b52275f567/src/compiler/crystal/types.cr#L90-L106

Thus there are more cases for types that don't work with `WeakRef`. While at it, we should consider them for improved error messages as well. That includes struct types (except `Pointer`) and unions including struct types or modules.

**Comment by HertzDevil** [comment]
This would be expressed as `T <= Reference?` in normal code, but unfortunately `Union(Reference, Nil)` is not usable.

**Comment by straight-shoota** [comment]
This should be a compile time error anyways, so it can and must use macros.

**Comment by HertzDevil** [comment]
I mean `Union(Reference, Nil)` is not usable within a macro context either.

**Comment by HertzDevil** [comment]
I am thinking if we could allow `x.as(Void*)` when `x` is a module type that is only included by reference types or `Nil`; those casts are only analyzed after all types are fully defined, and code generation will probably still be fine as long as `#remove_indirection` produces a reference-like type. The type constraint would then be relaxed to `T & Reference? >= T`. Not super important, though (intersection is not yet expressible in the macro language or in restrictions).
