### ISSUE TITLE
`if var.nil?` only works with local variable

### ISSUE THREAD

**Issue by TunkShif** [crystal-lang/crystal#11849]
## Bug Report

According to the [doc](https://crystal-lang.org/reference/1.3/syntax_and_semantics/if_var_nil.html), the following example is valid.

```crystal
a : String? = nil

if a.nil?
  puts "a is nil" # here `a` is nil
else
  puts a.upcase # here `a` is not nil
end
```

But the following example won't compile, and the compiler shows the error `Error: undefined method 'upcase' for Nil (compile-time type is (String | Nil))`.

```crystal
class Foo
  @bar : String?

  def initialize(@bar = nil)
  end

  def test
    if @bar.nil?
      puts "@bar is nil"
    else
      puts @bar.upcase # here @bar can't be nil
    end
  end

  def another_test
    return if @bar.nil?
    @bar.upcase # here @bar can't be nil
  end
end

foo = Foo.new("foobar")
puts foo.test
```

If we firstly assign the instance variable to a local variable, then it becomes valid.

```crystal
class Foo
  @bar : String?

  def initialize(@bar = nil)
  end

  def test
    bar = @bar
    if bar.nil?
      puts "@bar is nil"
    else
      puts bar.upcase
    end
  end
end

foo = Foo.new("foobar")
puts foo.test
```

And I'm using the latest crystal compiler.

```crystal
Crystal 1.3.2 (2022-01-19)

LLVM: 13.0.0
Default target: x86_64-pc-linux-gnu
```

Is this a bug or is it designed like this on purpose?

**Comment by asterite** [comment]
It's expected behavior. It's documented here: https://crystal-lang.org/reference/1.3/syntax_and_semantics/if_var.html#limitations

I guess the same limitations should be listed in other places...

**Comment by TunkShif** [comment]
> It's expected behavior. It's documented here: https://crystal-lang.org/reference/1.3/syntax_and_semantics/if_var.html#limitations
> 
> I guess the same limitations should be listed in other places...

OK, I got it. Thanks!

**Comment by Blacksmoke16** [comment]
@TunkShif For questions like this, that you're not sure if its a bug or expected, the forums or one of the chat channels may be a better place to ask while you're learning.

Can find links within https://crystal-lang.org/community/.

**Comment by beta-ziliani** [comment]
I'm closing this. I wonder how can we make a sensible error message for these situations.
