### ISSUE TITLE
Redundant code is generated when shifting integer types by constant

### ISSUE THREAD

**Issue by ssvb** [crystal-lang/crystal#11845]
The following piece of code is [a part of the hash function](https://github.com/crystal-lang/crystal/blob/1.3.2/src/crystal/hasher.cr#L91-L93), which is important for the performance of hash table lookups:
```Crystal
@[NoInline]
def rotl32(v : UInt64)
  (v << 32) | (v >> 32)
end
```
Currently Crystal 1.3.2 with LLVM12 generates the following x86-64 instructions for it:
```
000000000002e7a0 <*rotl32<UInt64>:UInt64>:
   2e7a0:       b0 01                   mov    $0x1,%al
   2e7a2:       84 c0                   test   %al,%al
   2e7a4:       74 08                   je     2e7ae <*rotl32<UInt64>:UInt64+0xe>
   2e7a6:       48 c1 c7 20             rol    $0x20,%rdi
   2e7aa:       48 89 f8                mov    %rdi,%rax
   2e7ad:       c3                      ret    
   2e7ae:       50                      push   %rax
   2e7af:       e8 00 00 00 00          call   2e7b4 <*rotl32<UInt64>:UInt64+0x14>
```

This looks like an unnecessary branch with a condition that is always false. Changing the source code to use `.unsafe_shl` and `.unsafe_shr` improves it:
```Crystal
@[NoInline]
def rotl32_unsafe(v : UInt64)
  (v.unsafe_shl(32)) | (v.unsafe_shr(32))
end
```

```
000000000002e800 <*rotl32_unsafe<UInt64>:UInt64>:
   2e800:       48 89 f8                mov    %rdi,%rax
   2e803:       48 c1 c0 20             rol    $0x20,%rax
   2e807:       c3                      ret    
```

**Comment by HertzDevil** [comment]
If a true rotation is involved, #12307 should take care of that. For other kinds of shifts (e.g. rotations not using all bits of an integer) there is probably nothing we could do that LLVM cannot figure out already.
