### ISSUE TITLE
Freestanding support 

### ISSUE THREAD

**Issue by leapofazzam123** [crystal-lang/crystal#11866]
## Feature Request
I want to use Crystal on embedded devices both with and without libc. I'm writing a stivale2 bindings for Crystal which is designed for basic kernels that uses its own libc. Since I only want to use Crystal with core functionalities, I need a freestanding mode which disables things that extensively needs libc.

**Comment by straight-shoota** [comment]
This is already possible in a way. You can pass `--prelude=empty` to the compiler. That will exclude any dependency on libc. That means you're without all of the standard library, though. The stdlib heavily relies on libc. That's unlikely to change in any kind of reasonable timeframe.

There has been talk about a tiny alternative standard library that would go without garbage collection, libc bindings etc. Maybe getting that started could be an option for your use case.

**Comment by asterite** [comment]
That's exactly what I was going to reply :-)

Should we close this issue? I think these discussions are better for the forums: https://forum.crystal-lang.org/
