### ISSUE TITLE
Regression: Compiler commands fail when `CRYSTAL_OPTS` has unsupported arguments

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#11919]
Compiler commands are failing when `CRYSTAL_OPTS` configures an option the specific command does not understand. This was not an error until now.

```console
$ CRYSTAL_OPTS="--error-on-warnings" bin/crystal env
Error: Invalid option: --error-on-warnings
$ bin/crystal --version
Crystal 1.4.0-dev [4e94a7298] (2022-03-21)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```

The same command works fine on previous compiler releases up to the most recent (1.3.2):

```console
$ CRYSTAL_OPTS="--error-on-warnings" crystal env
CRYSTAL_CACHE_DIR=/home/johannes/.cache/crystal
CRYSTAL_PATH=lib:/home/linuxbrew/.linuxbrew/Cellar/crystal/1.3.2/libexec/../share/crystal/src:/home/linuxbrew/.linuxbrew/Cellar/crystal/1.3.2/src
CRYSTAL_VERSION=1.3.2
CRYSTAL_LIBRARY_PATH=/home/linuxbrew/.linuxbrew/lib
CRYSTAL_OPTS=--error-on-warnings
$ crystal --version
Crystal 1.3.2 (2022-01-18)

LLVM: 13.0.0
Default target: x86_64-unknown-linux-gnu
```

While the new behaviour might be *technically* more correct as it alerts about an incorrectly used CLI option, it breaks existing configurations of global `CRYSTAL_OPTS` env vars. I think it is an inacceptable breaking change.

An example of this can be observed in https://github.com/crystal-lang/test-ecosystem/runs/5651498562. In the ecosystem test environment, we have `CRYSTAL_OPTS=--exclude-warnings none --error-on-warnings --error-trace` to ensure all crystal compiler use this error configuration.

I'm not sure how exactly this behaviour change happens, but it looks like #11780 is the only possible candidate for introducing the change.
/cc @HertzDevil

**Comment by straight-shoota** [comment]
Okay, it's obvious how this happens: https://github.com/crystal-lang/crystal/pull/11780 did not just change how `CRYSTAL_OPTS` is interpreted, it also added `CRYSTAL_OPTS` to commands that previously did not support it, when changing `OptionParser.parse(options)` to `parse_with_crystal_opts`.

**Comment by beta-ziliani** [comment]
I think a reasonable course of action is to revert it partially, just for those commands that do not build

**Comment by HertzDevil** [comment]
This is indeed intended behavior that already happens to commands which support `CRYSTAL_OPTS` before 1.3.2. Indiscriminately applying option flags to every command sounds like a code smell. At the minimum the invalid options should be warned on `STDERR` without affecting the exit status.

**Comment by straight-shoota** [comment]
The intention of `CRYSTAL_OPTS` is really to configure build options across multiple invocations of the compiler (#8900). For that, it specifically applies only to commands that have actual compilation options.

It's not meant to work on *all* compiler commands. I really don't see much point in that. If you want to pass options that are specific to a command then you can just easily use them as CLI options directly. `CRYSTAL_OPTS` is meant for use cases like in `test-ecosystem` where you globally configure compiler behaviour.

**Comment by straight-shoota** [comment]
@beta-ziliani When we hit a regression, it's best to revert first, talk later. It's paramount to get back to a working state, and the easiest way to do that is a simple revert. Afterwards we are free to discuss improvements without pressure.

**Comment by HertzDevil** [comment]
On further thought you are probably right; `crystal play` for example does not forward compiler options to the playground, so `CRYSTAL_OPTS` must be entirely ignored when starting up the server.
