### ISSUE TITLE
Type inference should regard if ! the same as unless

### ISSUE THREAD

**Issue by kirbyfan64** [crystal-lang/crystal#1196]
http://play.crystal-lang.org/#/r/bkb:

```crystal
a = 1 as Int32 | String

unless a.is_a? String
  puts a+1 # ok
end

if !a.is_a? String
  puts a+1 # type error
end
```

gives:

```
Error in line 8: no overload matches 'String#+' with types Int32
Overloads are:
 - String#+(other : self)
 - String#+(char : Char)
```

Shouldn't the two cases be the same?

**Comment by jhass** [comment]
Well, on one hand `!` is a method call, otoh you probably already get strange results if you override `is_a?`.

**Comment by bcardiff** [comment]
You can't override `is_a?` :-) http://play.crystal-lang.org/#/r/byp 
I think this is a won't fix.

There was the idea of allowing the compiler to know that `(T|S) - T = S`, so a `is_not_a?(T)` and more probably the `else` branch of an if can get advantage of it.

But I don't think giving the semantics to `!` is appropriate. Unless, we restrict overriding them for the booleans.

**Comment by asterite** [comment]
I think we discussed about `!` having special semantics and not being redefined, like `is_a?`. We might want to do this. And also do `.nil?`.

On the other hand, without `!` you can still use `unless` and get the same semantics, so maybe it's better to keep things simple.

**Comment by ozra** [comment]
I think it's good to cater to the expectations of the programmer for these things, hard coding `!` would be a simple way of doing that I guess.

**Comment by asterite** [comment]
Yay! Now the language will be much more consistent and intuitive :smile:
