### ISSUE TITLE
Empty external parameter names

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#11970]
It is possible to declare a def parameter with an empty external name:

```crystal
def foo("" x)
  x + 1
end

foo("": 3) # => 4
```

However, the empty name is reserved for the bare splat parameter, and also for anonymous top-level fun parameters:

```crystal
def foo(*, x)
  {% @def.args[0].name.stringify %}          # => ""
  {% @def.args[0].internal_name.stringify %} # => ""
end

fun bar(Int32)
  {% @def.args[0].name.stringify %}          # => ""
  {% @def.args[0].internal_name.stringify %} # => ""
end

foo(x: 3)
bar(1)
```

This has a few unintended consequences. Empty names cannot be used for named parameters, with a rather cryptic error message: (funs cannot have named parameters)

```crystal
def foo(*, "" x); end # Error: duplicated def parameter external name: 
```

An anonymous parameter of a lib or top-level fun can be matched by an empty named argument:

```crystal
lib Foo
  fun foo(Int32)
end

fun bar(Int32); end

Foo.foo("": 1) # okay
bar("": 1)     # okay
```

And if a top-level fun has more than one anonymous parameter, the internal error mentioned in #11967 shows up:

```crystal
fun foo(Int32, Int32); end

foo 1, 2
```

```
Module validation failed: Store operand must be a pointer.
  store i32 %1, i32 %0, !dbg !729
 (Exception)
  from /crystal/src/int.cr:541:9 in 'finish'
  from /crystal/src/compiler/crystal/codegen/codegen.cr:71:7 in 'codegen'
  from /crystal/src/compiler/crystal/compiler.cr:173:16 in 'compile'
  from /crystal/src/compiler/crystal/command.cr:220:5 in 'run_command'
  from /crystal/src/compiler/crystal/command.cr:127:7 in '__crystal_main'
  from /crystal/src/crystal/main.cr:115:5 in 'main'
  from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
```

Should we disallow those empty parameter names? Or should we alter the internal representation so that those special parameters use `nil` instead of the empty name? If we go with the former there would be no need to support empty-named call arguments or perhaps even generic type arguments (a `NamedTuple` with an empty key cannot be double-splatted anywhere).

**Comment by straight-shoota** [comment]
I think disallowing should be fine.

**Comment by straight-shoota** [comment]
https://github.com/crystal-lang/crystal/pull/11971 disallows empty keys for named tuples, which wasn't mentioned here. I'm not sure about that. This might be too big a breaking change without warning. The other use cases are probably not that relevant.

**Comment by HertzDevil** [comment]
With empty keys one could do the following:

```crystal
lib Foo
  fun foo(Int32, x : Int32, y : Int32)
end

Foo.foo **{x: 1, y: 2, "": 3} # okay
```

This should still be disallowed. If we cannot do this in the parser, the next candidate would be `Crystal::Call#lookup_matches_with_splat`.
