### ISSUE TITLE
Can't compile with -Dgc_none since v1.4

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/crystal#11986]
Try to compile a Crystal program with `-Dgc_none` on Linux (e.g. an empty file), and you'll see the following linker error (or another `pthread` symbol):

```console
$ cat /dev/null > bug.cr
$ crystal build -Dgc_none bug.cr
/usr/bin/ld: T-hread5858M-utex.o: référence au symbole non défini « pthread_mutexattr_settype@@GLIBC_2.2.5 »
//lib/x86_64-linux-gnu/libpthread.so.0 : erreur lors de l'ajout de symboles : DSO manquant dans la ligne de commande
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o /home/julien/.cache/crystal/crystal-run-bug.tmp  -rdynamic -L/usr/bin/../lib/crystal -lpcre -lm -levent -lrt -ldl`
```

The linker command is indeed missing `-lpthread`. If I manually specify it, then it will compile:

```console
$ crystal run -Dgc_none --link-flags="-lpthread" bug.cr
```

The regression was introduced in Crystal 1.4. It used to work in previous releases.

**Comment by straight-shoota** [comment]
This was broken by #11563
That change was technically correct though. Linking `pthread` from `gc_none` doesn't make sense. The problem is that the proper link annotations are missing with the `pthread` bindings.

**Comment by asterite** [comment]
See also: https://dev.to/kojix2/create-a-shared-library-symbolic-when-the-crystal-interpreter-does-not-work-in-crystal-140-21fo

**Comment by straight-shoota** [comment]
@asterite That's completely unrelated to this issue.
