### ISSUE TITLE
Undefined method 'x' for top-level when using generics with Proc

### ISSUE THREAD

**Issue by daliborfilus** [crystal-lang/crystal#11982]
## Bug Report

```shell
crystal --version
Crystal 1.4.0 [ef05e26d6] (2022-04-06)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```

I have an issue with generic parameters using forall.
The error message is completely confusing and doesn't make any sense to me.
I tried to find out where I have an error in my type annotations, but couldn't find any.
Then I crafted a "minimal" example which shows the weird behavior.

All these examples work as expected:

```crystal
def main
  result : Int32 = 123
  puts "Printing from main"
  puts result
  result
end

main

def main_generic(fnc : Proc(I, O), input : I) : O forall I, O
  result : O = fnc.call(input)
  puts "Printing from main_generic"
  puts result
  result
end

main_generic(->(i : String) : String { "Mapped #{i}" }, "input")

def main_generic_fnc(fnc : Proc(I, O)) : Proc(I, O) forall I, O
  ->(input : I) : O {
    result : O = fnc.call(input)
    puts "Printing from main_generic_fnc"
    puts result
    result
  }
end

main_generic_fnc(->(i : String) : String { "Mapped #{i}" }).call("input")
```

This one doesn't:

```crystal
struct Wrapper(I, O)
  def initialize(@parser : Proc(I, O))
  end

  def call(*args)
    @parser.call(*args)
  end
end

def main_generic_fnc_wrapper(fnc : Proc(I, O)) : Wrapper(I, O) forall I, O
  Wrapper.new(->(input : I) : O {
    result : O = fnc.call(input)
    puts "Printing from main_generic_fnc_wrapper"
    puts result
    result
  })
end

# Both of these doesn't work. I used the first one in previous examples, so I include it here.
# The second one is used to constraint I to String and O to Int32, so they are not ambiguous in the error messages.
#main_generic_fnc_wrapper(->(i : String) : String { "Mapped #{i}" }).call("input")
main_generic_fnc_wrapper(->(i : String) : Int32 { i.to_i }).call("123")
```

results in:

```
❯ crystal spec --error-trace
error in line 1
Error: while requiring "./spec/parser_spec.cr"


In spec/parser_spec.cr:162:1

 162 | main_generic_fnc_wrapper(->(i : String) : Int32 { i.to_i }).call("123")
       ^-----------------------
Error: instantiating 'main_generic_fnc_wrapper(Proc(String, Int32))'


In spec/parser_spec.cr:157:10

 157 | puts result
            ^-----
Error: undefined method 'result' for top-level

If you declared 'result' in a suffix if, declare it in a regular if for this to work. If the variable was declared in a macro it's not visible outside it)
```

The last example works when you change the `result : O = fnc.call(input)` to `result = fnc.call(input)`.
Then it compiles and works without any issues. Just by removing `: O`.
If you replace the type ` : O` with, for example, ` : I`, the error message correctly shows `Error: type must be String, not Int32`.

Is this a bug? Or a limitation? Am I doing something wrong?

**Comment by asterite** [comment]
Reduced:

```crystal
def foo(x)
end

foo(
  begin
    result : Int32 = 1
    result
  end
)
```

**Comment by asterite** [comment]
@daliborfilus as a workout, if you remove the `: O` from `result : O` then it will work fine.

I now remember why it's not working.

When we have something like this:

```crystal
property x : Int32
puts x
```

we don't want `x` to become a local variable in that scope, because a type restriction passed to a call is most likely because it was passed to a macro. But it seems this is also done for any expression that happens as a call argument, which is probably not right.

I'm not sure how we can fix this entirely, but for now I'll try to only apply the above rule for type declarations that are call arguments, not any type declaration that happens in expressions inside call arguments.

**Comment by daliborfilus** [comment]
Ah, I see how that could be a problem for `property x : Int32`. I also see your work in #11983, after just 12 minutes. Seriously, that's impressive.

**Comment by HertzDevil** [comment]
Can we instead unset all newly created variables in a `Call` the moment it is found to be a macro? Or would that be too expensive?
