### ISSUE TITLE
Error: Value is not a class, it's a struct

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#12028]
```crystal
class Value
end
Value.new
```
Error: Value is not a class, it's a struct
https://play.crystal-lang.org/#/r/d2zj

**Comment by HertzDevil** [comment]
[`Value`](https://crystal-lang.org/api/master/Value.html) is defined in the standard library. What's wrong about this?

**Comment by Blacksmoke16** [comment]
I'm pretty sure this is expected given you're trying to re-define https://crystal-lang.org/api/Value.html.

**Comment by kostya** [comment]
Ok, just unexpected that this name used.
