### ISSUE TITLE
No overload matches StaticArray

### ISSUE THREAD

**Issue by stugol** [crystal-lang/crystal#1203]
The code at http://play.crystal-lang.org/#/r/bm0 causes ```no overload matches 'fn' with types StaticArray(Int32, 10)```

**Comment by jhass** [comment]
Related to #934

**Comment by asterite** [comment]
I think the `N` might not be matching there, but it should.

**Comment by miketheman** [comment]
#triage 

This was reported against Crystal 0.7.6.

Running this code against 0.16.0 produces a Syntax error on the double-colon: https://play.crystal-lang.org/#/r/yfc
The `::` notation was removed circa 0.12.0, notably in 2367653f899889caf0986b48e57ca7f183a46635

Replacing the `::` with a single `:` produces: https://play.crystal-lang.org/#/r/yfd

> declaring the type of a local variable is not yet supported

This message is located in 3 locations:
```
spec/compiler/type_inference/instance_var_spec.cr
3032:      "declaring the type of a local variable is not yet supported"
src/compiler/crystal/semantic/main_visitor.cr
169:        node.raise "declaring the type of a local variable is not yet supported"
src/compiler/crystal/semantic/type_declaration_visitor.cr
107:        node.raise "declaring the type of a local variable is not yet supported"
```
making it a little more difficult in tracing exactly which one is being triggered.

**Comment by jhass** [comment]
This usecase of `::` got replaced with `uninitialized`: https://play.crystal-lang.org/#/r/yfu
