### ISSUE TITLE
Allow annotations on method/macro parameters

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#12039]
## Feature Request

- Is your feature request related to a problem? Please describe clearly and concisely what is it.

Annotations are a great way to, well annotate, portions of code with extra information that can be used at compile time via macros to influence code generation. However there currently isn't a great way to add this extra info to method/macro parameters, requiring them to be added to the method/macro itself and accessed that way.

Relates to #9802, #9322, #8148, and #11483.

- Describe the feature you would like, optionally illustrated by examples, and how it will solve the above problem.

### Proposal

The majority of languages that have annotations/attributes (that i've looked at at least) have the ability to annotate method parameters. Bringing this feature into Crystal seems like it would make sense, and would help fill a gap in the current annotation system. I propose it should be possible to:

```crystal
annotation SomeAnn; end
annotation OtherAnn; end

def foo(@[SomeAnn] id : Int32)
end

def foo(@[SomeAnn(10)] id : Int32)
end

def foo(@[SomeAnn] @[OtherAnn] id : Int32)
end

# ...
```
Then add the standard `.annotation` and `.annotations` methods to `Crystal::Macros::Arg`.

### Use Case

The main use case I have for this is for a refactor of how Athena handles [param converters](https://athenaframework.org/Framework/ParamConverter/). For example instead of:

```crystal
@[ARTA::Get(path: "/multiply/{num}")]
@[ATHA::ParamConverter("num", converter: MultiplyConverter)]
def multiply(num : Int32) : Int32
  num
end
```
You would be able to do:
```crystal
@[ARTA::Get(path: "/multiply/{num}")]
def multiply(@[Multiply] num : Int32) : Int32
  num
end
```
Similarly, you could provide the multiplier directly:
```crystal
@[ARTA::Get(path: "/multiply/{num}")]
def multiply(@[Multiply(by: 2)] num : Int32) : Int32
  num
end
```
Ultimately this makes this more focused and clear since you are able to directly annotate the method parameter instead of needing to also provide the name of the parameter in the method annotation in order to match it up.

#### Readability

Readability is probably the biggest concern as it's pretty easy for things to get quite busy when you have more than one parameter with some having one or more annotation applied to them.

```crystal
def foo(@[Thing] @[Thing2] one : String, two, @[OtherThing] three)
end
```

Tho, it doesn't effect things _that_ much.

```crystal
def foo(
  @[Thing] @[Thing2] one, 
  two, 
  @[OtherThing] three
)
end
```

Breaking the arguments across multiple lines can help with that.

#11483 would also especially help for this context:

```crystal
def foo(@[Thing, Thing2] one : String, two, @[OtherThing] three)
end
```

#### Representation

Given the annotations in this context could be used to contain data that is to be consumed at runtime, this brings up another good example of how #9802 would be beneficial. I.e. a better/more generic way to expose the annotation data at runtime, without resorting to hacks like we currently have to do.

For example, in the previous use case it would be great to just have a like `Array(Annotation)`, that you could just create without having to know the related annotations ahead of time. E.g. #9322.

#### Targeting

#8148 would also be a bit more helpful as this would introduce a third context where you could use annotations.

- Describe considered alternative solutions, and the reasons why you have not proposed them as a solution here.

N/A

- Does it break backward compatibility, if yes then what's the migration path?

It shouldn't no, given it's currently invalid syntax.

**Comment by Blacksmoke16** [comment]
@yxhuvud Sure, a common use case of this feature could be to inject a DB entity directly into the controller action based on the ID in the URL. I.e. something like:

```cr
@[ARTA::Get(path: "/article/{id}")]
def get_article(@[Entity] article : Article) : Article
  article
end
```

Really you could prob do this without the annotation, but having it there can be helpful to make it explicit where the arg's value should come from, or to customize how it's resolved. E.g. maybe you want to custom something about how it's resolved.

Also ofc this isn't the only use case for being able to annotate parameters. I'm sure there are others, but this is just the first that came to mind.

**Comment by yxhuvud** [comment]
This doesn't really make it clear what the actual upside of adding this is. How is this better than calling regular methods in the method body? To me, this just looks like adding magic for no obvious upside. There are clear downsides though, like having extra syntax to learn and making it less clear how failure modes are handled. Or in other words, I *really* don't see how this is better for anyone than 
```
 @[ARTA::Get(path: "/article/{id}")]
def get_article(id : Int32) : Article
  Article.find(id)
end

@[ARTA::Post("/article")]
def post_article(body : RequestBody) : Article
  Article.create(body)
end
```

**Comment by Blacksmoke16** [comment]
To be clear I'm deff not suggesting it be a stdlib feature to be able to `def foo(@[Entity] article : Article)` and have Crystal somehow know what to do with it. This issue is solely specific to being able to annotate method parameters. The examples I've shown would be something i specifically implement within the framework using this feature. However, being able to annotate parameters is just a language feature that unlocks additional use cases like this. I'm sure there are other use cases that will come up if this is something that is an option.

> Or in other words, I _really_ don't see how this is better for anyone than

Tho, to answer your question the main benefit from the framework's POV is that you are able to share complex logic and remove the need to have the same boilerplate in every controller action. I.e. just throw this annotation on the param and you're done. No need to think about how to handle deserializing the data, how to handle malformed data, how to handle validation, etc.

**Comment by HertzDevil** [comment]
In C++17, one can annotate function parameters with the [`[[maybe_unused]]`](https://en.cppreference.com/w/cpp/language/attributes/maybe_unused) attribute in the standard library to suppress relevant implementation-specific warnings:

```cpp
// g++ -Wall -Wextra -std=c++17

// warning: unused parameter 'x' [-Wunused-parameter]
void foo(int x) { }

// okay, no warnings emitted
void bar([[maybe_unused]] int x) { }
```

In Crystal's context, these warnings could come from the compiler itself or a linter library like Ameba. Ameba considers parameters with a leading underscore as potentially unused, but changing the name of a parameter can break named argument passing:

```crystal
# configure with:
#
#     Lint/UnusedArgument:
#       Enabled: true
#       IgnoreDefs: false

# [W] Lint/UnusedArgument: Unused argument `x`. If it's necessary, use `_x` as an argument name to indicate that it won't be used.
def foo(*, x); end
foo(x: 1)
```

```crystal
def foo(*, _x); end
foo(x: 1) # Error: missing argument: _x
```

We could instead tell Ameba to ignore unused parameters annotated with a specific annotation:

```crystal
annotation MaybeUnused; end
def foo(*, @[MaybeUnused] x); end # okay, no warnings emitted
```

Microsoft's C headers are (in)famous for using [SAL Annotations](https://docs.microsoft.com/en-us/cpp/c-runtime-library/sal-annotations) everywhere (C doesn't have attributes until C23). I believe they live entirely in the preprocessor and expand to nothing.

That said, I strongly discourage encoding runtime behaviour using parameter annotations, as a matter of style. Most of the time the same can be achieved by putting the code at the top of the def body.

**Comment by zw963** [comment]
> This doesn't really make it clear what the actual upside of adding this is. How is this better than calling regular methods in the method body? To me, this just looks like adding magic for no obvious upside. There are clear downsides though, like having extra syntax to learn and making it less clear how failure modes are handled. Or in other words, I _really_ don't see how this is better for anyone than
> 
> ```
>  @[ARTA::Get(path: "/article/{id}")]
> def get_article(id : Int32) : Article
>   Article.find(id)
> end
> 
> @[ARTA::Post("/article")]
> def post_article(body : RequestBody) : Article
>   Article.create(body)
> end
> ```

Agree, if same feature can be solved use method annotation, add this may not advisable.

1. this is less common
2. more memory consume, more slow complation speed? don't sure about it.
3. maybe the most import reason, following code is ugly after add arg annoteation anyway.
   should we report those annotation when print error?


```cr
def post_article(@[RequestBody(groups: "create")] article : Article) : Article
  article
end
```

**Comment by Blacksmoke16** [comment]
FWIW I want to again point out that that the _only_ thing this issue does is _allow_ annotations on method parameters. The Athena examples I've shown are 100% custom code that makes use of this feature in a way I want. If you're using any other framework, then yes, just include this code in the method body/block as there is no magical compiler feature now that inserts code into the method just because you annotate a parameter.

Ugly is subjective, but yes there are a few ways to format this, depending on the context:

```cr
def post_article(
  @[RequestBody(groups: "create")] 
  article : Article
) : Article
  article
end
```
at the end of the day, IMO, this more accurately represents the intent as compared to like:

```cr
@[RequestBody("article", groups: "create")]
def post_article(article : Article) : Article
  article
end
```
given the data is actually relates to the parameter it represents instead of arbitrarily to the method; needing to duplicate the name of the parameter again just so you can map it properly.

I'm happy to chat thru _how_ Athena is using this feature exactly, but please let's not :-1: the feature just because of how I'm using it. As again it does nothing on its own other than allowing the syntax and exposing the annotations.

**Comment by zw963** [comment]
> given the data actually relates to the parameter it represents instead of arbitrarily to the method; needing to duplicate the name of the parameter again just so you can map it properly.

Yes, this exactly what i said before, the annotate, let us explain this word, AFAIW, it should outside the object it annotate to.
it just a supplement, hope you know what i means, annotate should never be add into the subject self.

Anyway, you can ignore my thought, because i never use any programming language which use annotate, crystal is the first one,
if not acount for YARD, i just thought it from the dictionary word means, and personal pretty.

I heard python and php support annoate, does those language support usage like this?

**Comment by Blacksmoke16** [comment]
I think it's also worth pointing out annotating a method parameter does not affect the actual passed object in anyway (unless you explicitly add code to do so). Annotations are only available at compile time via macros, so their purpose is primarily used to represent metadata about some specific feature that can be used in the code generation process.

> I heard python and php support annoate, does those language support usage like this?

Yes, which is where my use case comes from for the most part. Ref https://github.com/symfony/symfony/pull/37829, which when implemented allows doing stuff like:

```php
class MyController
{
    public function indexAction(#[CurentUser] MyUser $user)
    {
    }
}
```

Which essentially allows the logic that determines the arguments that should be passed to the function to access the annotation/data within it to influence how (or if) that value is resolved. A simpler example is using `Time`:

 ```cr
class ExampleController
  @[ARTA::Get(path: "/event/{start_time}")]
  def event(start_time : Time) : String
    start_time.to_s
  end
end
```
Athena sees the method param typed as `Time` and [the supported resolver](https://github.com/athena-framework/athena/compare/param-convert-deprecation#diff-794d4dbd92a515ec39027fe18234b2064532e6d2ca3c883dc60065a145ee7564) will attempt to resolve the `start_time` path param into a `Time` instance, assuming it's RFC 3339 formatted. If you want to support a diff format you can do:

 ```cr
class ExampleController
  @[ARTA::Get(path: "/event/{start_time}")]
  def event(@[ATHR::Time::Format("%F")] start_time : Time) : String
    start_time.to_s
  end
end
```
and that'll allow the resolver to be aware of the custom format.

I guess technically i'm using it to generate code that exposes the data at runtime, but i also think it works well for the desired API i want. I.e. centralized way of doing the conversion, less boilerplate for the user as its all keyed off the type of the parameter, and provides a lot of flexibility for more complex resolution logic in a way that's easy to test, document, and is able to store state if needed.

**Comment by zw963** [comment]
Okay, anyway, from my point, the annotate, should be write in a separate line, don't know if i describe my this intention clear before, i means add annotate before arguments looks like strange.

As said by @matz, the author of CRuby, ` add feature is easy, it hard to remove it in the future`, hope this changes not be abuse in the future, especially, at runtime, and finally, cause the compiler hard to optimize something in the future(just guess), or have to do many others workaround for work with this.

i prefer add the feature which most of language happy to add it but we are still missed, we have so many others language standard feature not available for now, check my [post](https://forum.crystal-lang.org/t/why-people-leaving-crystal/4732) there, we don't need add new complexity only because we can do same annotate write less code.

I am okay to add this anyway, only give some advise, please do research to ensure this hack not take effect on others more import things, in the future.

**Comment by asterite** [comment]
@zw963 annotations exist in Java, C# and Go, extremely popular languages

**Comment by straight-shoota** [comment]
I think it's important to point out that allowing annotations on method parameters is not really introducing a new concept. It just extends the already existing annotation feature to allow annotating a new kind of receiver. As such, the change to language semantics is really minimal. I wouldn't expect any significant negative impact in any kind. Worst case scenario is that this feature gets barely used outside of Athena Framework. But it enables other libraries and tools to make use of it as well and develop cool features based on parameter annotations.
