### ISSUE TITLE
Spec files & crystal files in same directory to reduce RSI

### ISSUE THREAD

**Issue by didactic-drunk** [crystal-lang/crystal#12045]
#### `cd` is unavailable.  Unix utilities are hard to use or broken.  Also RSI

Current example:
```
grep ... src/project/subdir` spec/subdir
# repeat both subdirs for every additional command
```
With files in the same dir:
```
cd src/project/subdir
grep ...
...
```

Another example:
```
git add src/project/foo.cr spec/foo_spec.cr
```
Or (assuming `cd src/project` from prior commands/editing):
```
git add foo*
```

#### Repetitive strain injury (RSI)

Splitting `src` and `spec` adds lots of additional typing.

#### Navigating on github or other visual interfaces is cumbersome

How do I use this class?  I often mix reading the class + specs to figure it out as documentation for newer/smaller crystal shards is either incomplete or nonexistent.  Count the number of clicks to navigate to source, then extra clicks to find the correct spec.

## Proposed file structure

```
src/foo.cr
src/foo.crs
spec/* # Backwards compatibility and optional integration tests
```

## Other benefits

* Less typing
* Clarity of which files have specs (they're right next to each other)
* Did I mention less typing?

## Other naming conventions

`*_spec.cr` in the same directory problems:
* `foo_spec.cr`: May end up separated from `foo.cr` (out of order) if similarly named classes exist (`foo_bar.cr`).
* `require "foo/**"` needs to skip '*_spec'.  Unless it's in a `_spec`.  Would it then include only `_spec` or all files?

## Backwards compatibility

Fully compatible unless the `spec` search path is removed.  `spec` could still be useful for integration or non class specific tests.
_

**Comment by straight-shoota** [comment]
What is RSI?

**Comment by asterite** [comment]
Repetitive Strain Injury. It's when you repeat a movement many times in a bad way, injuring that part of the body (usually the hand/wrist)

**Comment by oprypin** [comment]
This post does not have any strong arguments and makes huge leaps in its conclusions. I really didn't get the point about "unix utilities", particularly why that means that Crystal is doing something wrong. There's also no good-faith effort to describe upsides of the *current* approach. Finally, I also don't appreciate the "witty" style of writing, it never helps get the point across. It is *super* unnecessary to directly equate typing with injury.

Moreover, one can already just merge the two trees if they were so inclined, and then write `crystal spec src/**/*_spec.cr`. Indeed, you also have to avoid wildcard imports, but that's good anyway as they are a bad practice. ~~Oh but that just causes more typing, hmm.~~

This discussion cannot possibly lead to an accepted state, so I think it's most productive to just close it.

**Comment by didactic-drunk** [comment]
> really didn't get the point about "unix utilities", particularly why that means that Crystal is doing something wrong. 

Can't use `cd` to focus all further commands on a single dir encompassing both code and unit tests.

Example:
```
cd src/project/foo_module
rg bar # Missing unit test usage
rg bar . ../../../spec/foo_module # Try again
# Now I need to edit the spec **with more typing**
$EDITOR ../../spec/foo_module/bar_spec.cr
```

> There's also no good-faith effort to describe upsides of the _current_ approach.

I don't see any.  Other than familiarity and from that possibly "feeling right".  Or possibly "looks cleaner" at the expense of more work navigating/typing.

I'm not being facetious.  I would never design a system with split unit tests.  To me it's all downsides and no up.

Can you provide some?


> It is _super_ unnecessary to directly equate typing with injury.

1) Use causes wear
2) My hands hurt.  From typing.  The more I type the more they hurt.
3) Many people have similar complaints.  I know of 2 which required surgery **from typing**.


> Moreover, one can already just merge the two trees if they were so inclined, and then write `crystal spec src/**/*_spec.cr`. Indeed, you also have to avoid wildcard imports, but that's good anyway as they are a bad practice. ~Oh but that just causes more typing,

If `crystal spec` doesn't work out of the box it's too complicated for additional developers.  Each shard they develop or contribute to would require a custom workflow.


Here's something you could do with specs that you can't with the current system.

## Faster specs

Use guard/guardian or your favorite file watcher.
Apply this logic on file change
*Incomplete example for illustration only*
```crystal
unit_test_files = modified_files.map { |f|
  f.f.sub(/cr$/, ".crs"}
}.select { |f|
  File.exists?(f)
}

# Skips all unmodified unit tests and runs all integration tests
`crystal spec spec #{unit_test_files.join(" ")}`
```



> This post does not have any strong arguments and makes huge leaps in its conclusions. I I 
> This discussion cannot possibly lead to an accepted state,ing.s so I think it's most productive to just close it.

Now that is a huge leap in conclusion and lacking strong arguments.

The (possibly?) angry response is... surprising.

Rust managed to (I presume) calmly discuss and implement inline unit tests.  I don't understand the hostility when other languages have gone to further extremes.

**Comment by konovod** [comment]
you can do same with current system - just replace `sub(/cr$/, ".crs")` with `"./spec/"+f.sub(/.cr$/, "_spec.cr")

**Comment by didactic-drunk** [comment]
> you can do same with current system - just replace `sub(/cr$/, ".crs")` with `"./spec/"+f.sub(/.cr$/, "_spec.cr")`

How do you run integration tests + one changed spec file?  The unit and integration tests are mixed together.

**Comment by Fryguy** [comment]
> How do you run integration tests + one changed spec file? The unit and integration tests are mixed together.

Move your unit tests into a `spec/units` dir and do `"./spec/unit" + f.sub(/.cr$/, "_spec.cr")`?

**Comment by straight-shoota** [comment]
Just a few observations:

* Using a different file extensions for spec files is bad. Spec files are just Crystal code. Their purpose comes from context, not from the file type. The `_spec` ending expresses purpose in the file name. That's a much more practical solution than a file extension which demands a lot for recognition among developers and tools.
* You are free to place unit tests in `./src` folder or anywhere else you like. `./spec` is just a convention. Run `crystal spec src` and it just works.

**Comment by didactic-drunk** [comment]
> Just a few observations:
> 
>     * Using a different file extensions for spec files is bad. Spec files are just Crystal code. Their purpose comes from context, not from the file type. The `_spec` ending expresses purpose in the file name. That's a much more practical solution than a file extension which demands a lot for recognition among developers and tools.

A file extension was proposed to:
* Sorting correctly (foo.cr foo_bar.cr foo_bar_spec.cr foo_spec.cr)
* Allow wildcard requires to skip specs

But mostly sorting

I'll remove this component from my request as it seems too controversial.

>     * You are free to place unit tests in `./src` folder or anywhere else you like. `./spec` is just a convention. Run `crystal spec src` and it just works. There is no need for the compiler to change for this.

Running `crystal spec` should just work, otherwise special knowledge and procedures are needed for each shard.  Which is why I proposed standardizing.

If `crystal spec` runs specs in `src` and `spec` by default or is configurable my issue is resolved.

**Comment by didactic-drunk** [comment]
> It seemed your primary motivation is RSI, which while admittedly terrible, it is unclear how it actually applies to the request. 

Substitute RSI for:
* More efficient
* Faster to type
* DRY
* Easier/faster to find and see which files have unit tests

Also:
* Standardized placement of unit vs integration tests
* Faster testing when splitting unit/integration tests

When in pain RSI is **the** most compelling reason.

Maybe I should change the title to "Better specs by importing and learning from rust".  Maybe this proposal needs better PR.

> That is, what exactly are you typing extra before and after that would make any significant difference with respect to RSI? Later, you mentioned guard, which is cool and also avoids having to type `crystal spec` over and over, but guard works just fine with the current approach from what I can tell.

```crystal
cd src/project/foo
rg query . ../../../spec/foo
rg refined_query <repeat>
rg more_refined_query <repeat>
g(it) l(og) <repeat>
g blame <repeat>
g a <repeat>
g reset <repeat>
```

That's the daily grind.  There are plenty of less frequent or one off commands.

> One of the tenets of Crystal is to avoid having multiple ways to do the same thing. The project has already chosen the `spec` dir approach. 

What about a modified rust method. Integration tests go in `spec`,  Unit tests stay with the class file.  Everyone using rust will understand immediately.  `crystal new` can create an example unit test and integration test file.

> Adding a second way to do specs seems likely to confuse the community as some projects will have `spec`, some will have inline, and others will end up with both through either conversion or confusion.

I'll address a transition path if all other hurdles pass.
