### ISSUE TITLE
[CI] Windows build is broken

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#12058]
CI builds of `x86_64-windows-job` are broken on master:

https://github.com/crystal-lang/crystal/runs/6423403778?check_suite_focus=true

Linking LLVM fails with some missing symbols.

My guess is a mismatch between LLVM versions in the linux and windows steps. The linux step uses image `crystallang/crystal:1.4.1-build` with LLVM 10 while we link against LLVM 13 in the windows step.

So this is probably prone to cause issues at some point. But it has worked so far. No idea what makes it fail now.

**Comment by HertzDevil** [comment]
One thing I noticed is that the failing runs are built with Visual Studio 19.32.31328 and the previous ones used 19.31.31107. It happened [a few days ago](https://github.com/actions/virtual-environments/pull/5528). Maybe the error will go away if we force a rebuild of LLVM?

**Comment by straight-shoota** [comment]
I tried pinning the VS version in https://github.com/straight-shoota/crystal/runs/6427869694?check_suite_focus=true
Now OpenSSL build step complains about missing `nmake`.

**Comment by straight-shoota** [comment]
Probably. Do you want to give it a try? Or shall I...?
