### ISSUE TITLE
FileUtils - methods like `rm` should have equivalent that does not raise when the file does not exist.

### ISSUE THREAD

**Issue by stellarpower** [crystal-lang/crystal#12093]
## Feature Request

I am using FileUtils to delete a file made by another process. I don't want to care if the file is not found; Much as I would in Ruby, I am using Crystal as a better alternative to scripting here.

Because I am accessing these functions through FileUtils, these are providing a more shell-like wrapper around the underlying `File::delete` implementations. For this reason, I think it will be common for users in some cases not to be bothered if they try to delete a file that does not already exist.

I'd like to propose that methods like `rm` and friends have parallel versions with a question mark appended (i.e. `FileUtils::rm?`), that will not throw an exception if the file does not exist, but instead will silently continue.

A basic implementation I have inserted into my own code to demonstrate is like so:

```Crystal
module FileUtils
	def rm?(path)
		FileUtils.rm(path) if File.exists? path
	end
end
```
I think utilising the question mark is a brief, nice, and idiomatic way of achieving this, that won't e.g. break any previous API compatibility.

**Comment by Blacksmoke16** [comment]
Any reason to not just use `File.delete?`? E.g.

```cr
File.write("foo", "")
File.delete?("./foo") # => true
File.delete?("./bar") # => false
```

Related: https://github.com/crystal-lang/crystal/issues/5231

**Comment by stellarpower** [comment]
Only that I didn't see it documented:
https://crystal-lang.org/api/1.4.1/File.html#delete%3ANil-instance-method
Looks like it's new in the master branch, so my apologies.

It feels odd to me for `rm` and friends to throw an exception (and in my case, terminate the application) when the entries don't exist - it makes more intuitive sense that it comes from `File::delete`, but in any case, I'm happy to leave it open if this is worth adding quickly. 

Also, an aside that ought to be a new FR, but there may be some other utilities that would be nice  to add to FIleUtils. `cat` would be very neat for me - i.e. `FileUtils::cat` as a one-liner to read in the contents of a file as a string. head and tail could also then take lines as usual.

**Comment by Blacksmoke16** [comment]
> Looks like it's new in the master branch, so my apologies.

Ahh, oops. Cons of using `master` API docs all the time :sweat_smile:. My Bad. Was added in https://github.com/crystal-lang/crystal/pull/11887.

> Also, an aside that ought to be a new FR, but there may be some other utilities that would be nice to add to FIleUtils

I'm pretty sure, based on some discussion in that ticket I linked, we don't want to add new things to that module, which is essentially just full of aliases. Like you don't need `cat` when you can just do `File.read "./foo.txt"`.

> I'm happy to leave it open if this is worth adding quickly.

I don't see a reason to keep this open. Going to close it given there is nothing actional left since an equivalent method was already added.
