### ISSUE TITLE
Typecheck error for nillable `Proc`s in classes

### ISSUE THREAD

**Issue by tkshnwesper** [crystal-lang/crystal#12106]
## Bug Report

Hi all,

I've encountered a bug related to `Proc`s which results in typecheck errors.

Getting straight to the point, here's the reproducible code which gives the error:

```crystal
class X
  def initialize(@proc : Proc(String, Nil)? = nil)
  end
  
  def foo
    @proc && @proc.call("")
  end
end

X.new.foo
```

The error message goes like

```txt
Error: instantiating 'X#foo()'
Error: undefined method 'call' for Nil (compile-time type is (Proc(String, Nil) | Nil))
```

That particular error message should not appear because I have added a small guard clause (`@proc && ...`) which ensures that `call` is called on a valid `Proc` object and not `Nil`.

There are a few other things I tried:

```crystal
def f2(p2 : Int32, proc2 : Proc(String, Nil)? = nil)
  proc2 && proc2.call("")
end

f2(1)
```

and

```crystal
proc2 : Proc(String, Nil)? = nil
proc2 && proc2.call("")
```

Both of which compile perfectly fine. So the issue is probably got to do with classes.

```txt
Crystal 1.4.1 (2022-04-22)

LLVM: 13.0.1
Default target: x86_64-apple-macosx
```

**Comment by straight-shoota** [comment]
This is expected behaviour. Type restrictions from conditionals only apply to local variables, not to instance variables.

Reference: https://crystal-lang.org/reference/1.4/syntax_and_semantics/if_var.html#limitations

**Comment by straight-shoota** [comment]
You can use `@proc.try &.call("")` or assign the value of the instance variable to a local variable for the guard: `(proc = @proc) && proc.call("")`.

**Comment by tkshnwesper** [comment]
Thank you for the documentation link and alternatives @straight-shoota!
