### ISSUE TITLE
LLDB crystal formatters not working on windows

### ISSUE THREAD

**Issue by wonderix** [crystal-lang/crystal#12112]
## Bug Report

LLDB crystal formatters `etc/lldb/crystal_formatters.py` not working on windows. It seems that strings on windows are prefixed with a 4 byte integer.

I will provide a PR for this.

**Comment by wonderix** [comment]
It seems that this is related to lldb. Debugging the same executable with Visual Studio shows the correct value of member `c`. In lldb the value of `c` is shown as utf8 equivalent of 12 (the length of the string)

![image](https://user-images.githubusercontent.com/3628459/173197365-d9a137ec-e647-46a5-b105-b687e34c8907.png)

**Comment by HertzDevil** [comment]
I am quite sure Visual Studio uses Natvis, not LLDB's type formatters.
