### ISSUE TITLE
.build/std_spec hanging on freebsd

### ISSUE THREAD

**Issue by InfRandomness** [crystal-lang/crystal#12114]
## Bug Report

Make sure to review these points before submitting issues - thank you!

.build/std_spec seems to be hanging on freebsd,
Attaching a tracer to the process yields results like 
```
kevent(10,{ },0,{ },64,{ 4.999998000 })		 = 0 (0x0)
kevent(10,{ },0,{ },64,{ 4.999999000 })		 = 0 (0x0)
kevent(10,{ },0,{ },64,{ 4.999999000 })		 = 0 (0x0)
kevent(10,{ },0,{ },64,{ 4.999999000 })		 = 0 (0x0)
kevent(10,{ },0,{ },64,{ 5.000000000 })		 = 0 (0x0)
```
After reading the kevent man pages, it seems like the eventlist is empty, which seems like an odd thing because the nevents argument is set to 64

(from the following prototype : 
```c
     int
     kevent(int kq, const struct kevent *changelist, int nchanges,
         struct kevent *eventlist, int nevents,
         const struct timespec *timeout)
```
)

**Comment by straight-shoota** [comment]
Execution hangs at this specs:

https://github.com/crystal-lang/crystal/blob/39efd0ca186e9b953e1c1b78c82880866ece7d5c/spec/std/io/io_spec.cr#L415-L421

**Comment by straight-shoota** [comment]
The reason for this failure is that the test expects `IO.pipe` to create file descriptors that are only open for read or write. But on FreeBSD, file descriptors opened by [`pipe(2)`](https://www.freebsd.org/cgi/man.cgi?sektion=2&query=pipe) are actually bi-directional, thus the spec fails.

**Comment by InfRandomness** [comment]
At this point I don't think this'll get another review; closing.
