### ISSUE TITLE
Instance vars should not be allowed on `Class`, `Tuple`, `NamedTuple`, `Enum`, `Pointer` , `Proc`, `StaticArray` and `Union`.

### ISSUE THREAD

**Issue by I3oris** [crystal-lang/crystal#12159]
Hello

I found a bug playing with random things.

The following make crash the compiler:

```crystal
class Class
  @x = 1
end
# => BUG: Class doesn't implement instance_vars (Exception)
```

Similar occurs with:
```crystal
struct Tuple(*T)
  @x = 1
end
# => BUG: Nil assertion failed (NilAssertionError)

struct NamedTuple(T)
  @x = 1
end
# => BUG: Nil assertion failed (NilAssertionError)
```

For the following, the compiler doesn't crash but produce inconsistent code:
```crystal
struct Enum
  getter x = 1
end

enum Foo;A;end

p Foo::A.x # => undefined behavior



struct Pointer(T)
  getter x = 1
end
p Pointer(Int32).malloc.x # => undefined behavior



struct Proc(*T, R)
  getter x = 1
end

p ->{}.x # => undefined behavior



struct StaticArray(T, N)
  getter x = 1
end

puts StaticArray[1, 2, 3].x  # => undefined behavior 



struct Union(*T)
  getter x = 1
end
# we cannot test calling x on Union, but it should be unhallowed too
```

For other types where ivars should be forbidden, the compiler catch the error. 
```crystal
struct Int32
  @x = 1
end
# => Error: can't declare instance variables in Int32
```

As the fix for that was pretty simple, I send the PR meanwhile :) 

I hope I don't forget types where ivars should be forbidden, but I thinks I check all of them.

**Comment by HertzDevil** [comment]
I think a more concise definition is that instance variables are only allowed on proper subtypes of `Reference` or `Struct`. Not sure which one runs faster though.

**Comment by I3oris** [comment]
Your right [HertzDevil](https://github.com/HertzDevil).
I tested implementing this way. It turned out that some `Number` like `Complex` or `BigInt` allows instance vars although there are not `Struct`.
So `Number`s accept ivars unless the `PrimitiveType`s, and unless `Int` and `Float` (which are not  `PrimitiveType`).

Ivars are also allowed on module of course.

The rule would be so "Instance vars are allowed on module and  on every type deriving `Reference`, `Struct`, or `Number`, except `PrimitiveType`, `Float`, `Int` and except  `Reference`, `Struct`, and `Number` themself".

And the implementation would be:
```crystal
case self
when PrimitiveType, program.float, program.int,
  program.reference,
  program.struct,
  program.number
  false
when .module?,
     .implements?(program.reference),
     .implements?(program.struct),
     .implements?(program.number)
  true
else
  false
end
```
Unless I miss a simpler way ?

Definitely not sure it's going faster (we can probably play on test order also). But this have the advantage to be more robust if ever a new special type comes. 

Do you prefer this implementation and I update the commit? Or we actually keep the previous?, thanks for the answer :)

**Comment by I3oris** [comment]
Sorry for the awkwardness of my previous message, as a simple contributor, I prefer ask on alternative and show pros and cons rather than commit a thing which I would not known all implications.

In above, I wanted meant "What the better between I simpler and faster solution, or a more complex but semantically righter solution ?. Knowing that both are actually exact".
But personally, I thinks the simpler is better here.

**Comment by beta-ziliani** [comment]
I don't see anything awkward in your message :-)

I don't have an answer to your question. In this case, the set is sufficiently small to make the two solutions equally good to my eyes.

**Comment by I3oris** [comment]
yes, let see merging to first solution so :)
