### ISSUE TITLE
(debuger with  Interpreter)Is there a function to restart method (thread) frame after hot code replacement and restart replacement? This is too important for debugging

### ISSUE THREAD

**Issue by acodervic** [crystal-lang/crystal#12157]
Is there a function to restart method (thread) frame after hot code replacement and restart replacement? This is too important for debugging?

like java debug with vsode:

![screenscast_20220625_123246](https://user-images.githubusercontent.com/57204004/175758118-abc2a501-72d8-4130-87f5-9705cfd26cb6.gif)

When I change the java code, I don't need to restart the jvm and replace the code, and come back to the top of the stack of the current method. The java debugger supports this function, which is very useful and important in reality.

A good debugging experience is a necessary condition for the promotion and development of the crystal language, because advantages alone are not enough, it must be efficient and practical. I hope the crystal team can enhance the debugging experience of the crystal language. This is really important, sometimes debugging code Takes up 90% of my work time.

As much as I love crystal, but without these debugging features, I might still use java. So frustrating

**Comment by acodervic** [comment]
A good debugging experience is a necessary condition for the promotion and development of the crystal language, because advantages alone are not enough, it must be efficient and practical. I hope the crystal team can enhance the debugging experience of the crystal language. This is really important, sometimes debugging code Takes up 90% of my work time.

**Comment by acodervic** [comment]
As much as I love crystal, but without these debugging features, I might still use java. So frustrating

**Comment by asterite** [comment]
Hi!

Yes, the debugging experience is is far from ideal right now. And it will never be like Java because Crystal is a compiled language (to native code). There's the interpreter but that also will take some time.

In the meantime, please use Java. It's a pretty good language too. I'd recommend giving Kotlin a try, though.

**Comment by acodervic** [comment]
> Hi!
> 
> Yes, the debugging experience is is far from ideal right now. And it will never be like Java because Crystal is a compiled language (to native code). There's the interpreter but that also will take some time.
> 
> In the meantime, please use Java. It's a pretty good language too. I'd recommend giving Kotlin a try, though.

thanks!
