### ISSUE TITLE
Bug: `r` at eval:10:13 has no type

### ISSUE THREAD

**Issue by sardaukar** [crystal-lang/crystal#1216]
The following triggers it

```crystal
class A
  
  def initialize @ivar
    meth
  end
  
  def meth
    r = self.class.new(5)
    
    puts "#{r.@ivar}"
  end
  
end

a = A.new(6)
```

But this works:

```crystal
class A
  
  def initialize @ivar
  end
  
  def meth
    r = self.class.new(5)
    
    puts "#{r.@ivar}"
  end
  
end

a = A.new(6)
a.meth
```

Is it because the type is only assigned after running the initializer?

**Comment by PragTob** [comment]
I'm not sure, but shouldn't your first example result in an endless loop?

E.g. initialize ----> meth ---> initialize ---> meth ---> initialize ---> meth ---> ....

in which case the error message might be improved but not much else to do imo (Or I have a thinking error regarding the code)

**Comment by sardaukar** [comment]
Yeah, it's mostly about improving the message, I believe. Right? :D

**Comment by sardaukar** [comment]
Contrived better example? No endless loop in this case.

```crystal
class A

  def initialize @ivar
    if @ivar > 2 
      meth
    end
  end

  def meth
    r = self.class.new(1)

    puts "#{r.@ivar}"
  end

end

a = A.new(6)
```

**Comment by asterite** [comment]
Definitely contrived, but still a bug :-)

**Comment by asterite** [comment]
Similar code:

```crystal
class Foo
  def foo
    crash.foo
  end
end

def crash
  x = Foo.allocate
  x.foo
  x
end

crash
```

The recursiveness of this makes the AfterTypeInferenceTransformer doesn't work well (note to ourselves).

**Comment by sardaukar** [comment]
👍
