### ISSUE TITLE
Update darwin images

### ISSUE THREAD

**Issue by beta-ziliani** [crystal-lang/crystal#12215]
CircleCI is deprecating Xcode 12.4.
https://discuss.circleci.com/t/xcode-image-deprecation/44294?mkt_tok=NDg1LVpNSC02MjYAAAGE6MeEggPLUM-i-bTcXMfA2ZTjvhtuQlX3L3UKSpmj0vFOZymLJ6iZjMzElf5CeHTEGAJL99zdsiNX_WDfu7k

**Comment by HertzDevil** [comment]
Resolved by #12264
