### ISSUE TITLE
Bash completion error: `compopt: command not found`

### ISSUE THREAD

**Issue by potomak** [crystal-lang/crystal#12232]
Bash completion doesn't work on OSX because I'm missing the `compopt` command.

Is that a reasonable requirement or can the completion functions be improved to remove the dependency on OSX?

Example:

```
$ crystal spec spe[tab]-bash: compopt: command not found
```

**Comment by potomak** [comment]
The reason is that I'm using a relatively old bash version (3.2)

```
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
```

I tried to comment out the calls to `compopt -o filenames` in the script and completion still works even if it isn't as accurate as with `compopt`.

Do you think it would make sense to execute `compopt` only if `compopt` is present?

```
if command -v compopt &> /dev/null
then
    compopt -o filenames
fi
```

**Comment by straight-shoota** [comment]
Sigh, I wish Apple would update their ancient bash version.

I would probably prefer an inline condition:
```cr
type compopt  &> /dev/null && compopt -o filenames
```
And `type` should be better because it's a shell builtin.

**Comment by potomak** [comment]
Ok, I will do that. I'm not a bash expert. I found `command` here: https://stackoverflow.com/questions/592620/how-can-i-check-if-a-program-exists-from-a-bash-script

`command` is also a builtin function, but I don't have a strong preference.
