### ISSUE TITLE
Interpreter: p! is not working with local var in repl session

### ISSUE THREAD

**Issue by vlazar** [crystal-lang/crystal#12233]
## Bug Report

Code when put in `test.cr` file
```cr
test = 1
p! test
```

and then run in the interpreter mode
```
bin/crystal i test.cr
Using compiled compiler at .build/crystal
test # => 1
```

Same code directly in icr session:

```
bin/crystal i
Using compiled compiler at .build/crystal
icr:1:0> test = 1
=> 1
icr:2:0> p! test
error in line 1
Error: expanding macro


error in line 1
Error: undefined method 'test' for top-level

If you declared 'test' in a suffix if, declare it in a regular if for this to work. If the variable was declared in a macro it's not visible outside it)
```

Doing `p test` works just fine in icr.

I'm using
```
bin/crystal --version
Using compiled compiler at .build/crystal
Crystal 1.5.0 [994c70b10] (2022-07-06)

LLVM: 14.0.6
Default target: x86_64-apple-macosx
```

**Comment by Sija** [comment]
Not relevant here, since the `icr` is an external project, created before `crystal i` came to existence.

**Comment by straight-shoota** [comment]
@vlazar is this about https://github.com/crystal-community/icr or `crystal i`? The example looks like the latter, but you talk about the former (which is an external project).

**Comment by mdwagner** [comment]
I think he's referring to running it inside the repl vs running a file with the interpreter?

**Comment by vlazar** [comment]
Sorry for confusion, all examples are about using interpreter, like CLI command in examples I've posted show `./bin/crystal i`.

I call it ICR, because that what it prints in REPL prompt:
```
icr:1:0>
```

When I run IRB in Ruby it prints:
```
irb(main):001:0>
```

I call it IRB session in Ruby.
Hence I call it ICR in Crystal.
