### ISSUE TITLE
Interpreter: Struct comparison gives incorrect results 

### ISSUE THREAD

**Issue by cyangle** [crystal-lang/crystal#12254]
## Bug Report
Similar to #12228 but for struct:
```crystal
abstract struct P
end

struct A < P
end

puts A.as(P.class) == A # true in compiled mode, false in interpreted mode
```

**Comment by asterite** [comment]
@cyangle Could you check this against master? The PR for #12228 is already merged, and the code in this issue works fine now in the interpreter. The underlying code is the same regardless of whether it's a class or a struct hierarchy. I just checked it against master and it works fine, but maybe I'm doing something wrong. Let me know!

**Comment by cyangle** [comment]
Cool, it's fixed.
