### ISSUE TITLE
Interpreter: incorrect with ... yield

### ISSUE THREAD

**Issue by cyangle** [crystal-lang/crystal#12296]
## Bug Report
I found this bug from Jennifer.cr's tests.

Example code:
```crystal
class A
  @b = B.new("foo")

  def build
    b2 = B.new("bar")
    with b2 yield @b, b2
  end
end

class B
  getter value
  def initialize(@value : String)
  end
end

A.new.build do |t|
  puts value
  puts t.value
end
```
Compiled binary's output:
```
bar
foo
```

Interpreter's output:
```
foo
bar
```

**Comment by cyangle** [comment]
I'm going through Jennifer.cr's tests, there are still a handful of failing tests.
I'll probably file a few more bug tickets when I have time.

**Comment by asterite** [comment]
Reduced:

```crystal
def build
  with 1 yield 2, 1
end

build do |t|
  puts itself
end
```

Prints 1 in compiled mode, 2 in interpreted mode.
