### ISSUE TITLE
`IOT instruction (core dumped)  ./bin/crystal`... when compiling Crystal for arm64

### ISSUE THREAD

**Issue by jtbx** [crystal-lang/crystal#12298]
# Bug report

I'm compiling Crystal for arm64 (for my Raspberry Pi) as per [these instructions](https://stackoverflow.com/a/42796648).

In the repo's root, I ran `make deps`, then I ran `./bin/crystal build src/compiler/crystal.cr --cross-compile --target arm-unknown-linux-gnueabihf --release -s -D without_openssl -D without_zlib`. The output was:

```
Parse:                             00:00:00.000050157 (   0.69MB)
Semantic (top level):              00:00:00.441987920 ( 142.28MB)
Semantic (new):                    00:00:00.003406280 ( 142.28MB)
Semantic (type declarations):      00:00:00.052405017 ( 150.28MB)
Semantic (abstract def check):     00:00:00.064425088 ( 150.28MB)
Semantic (restrictions augmenter): 00:00:00.017584969 ( 158.28MB)
Semantic (ivars initializers):     00:00:20.598774441 (1734.21MB)
Semantic (cvars initializers):     00:00:00.024971885 (1734.21MB)
Semantic (main):                   00:00:39.344143427 (2070.21MB)
Semantic (cleanup):                00:00:00.004213097 (2070.21MB)
Semantic (recursive struct check): 00:00:00.010476639 (2070.21MB)
Codegen (crystal):                 00:00:16.539319306 (2366.21MB)
LLVM ERROR: Cannot generate unaligned atomic store
zsh: IOT instruction (core dumped)  ./bin/crystal build src/compiler/crystal.cr --cross-compile --target   -s -D
```

(I'm using zsh)

I then took away the `-D without_openssl -D without_zlib` from the end, and it produced similar results.

```
Parse:                             00:00:00.000038378 (   0.69MB)
Semantic (top level):              00:00:00.614185670 ( 142.29MB)
Semantic (new):                    00:00:00.003639309 ( 142.29MB)
Semantic (type declarations):      00:00:00.099942765 ( 150.29MB)
Semantic (abstract def check):     00:00:00.029608429 ( 158.29MB)
Semantic (restrictions augmenter): 00:00:00.018643700 ( 158.29MB)
Semantic (ivars initializers):     00:00:09.082725345 (1758.22MB)
Semantic (cvars initializers):     00:00:00.011977501 (1758.22MB)
Semantic (main):                   00:00:06.050483466 (2070.22MB)
Semantic (cleanup):                00:00:00.002086396 (2070.22MB)
Semantic (recursive struct check): 00:00:00.006443688 (2070.22MB)
Codegen (crystal):                 00:00:06.896796299 (2414.22MB)
LLVM ERROR: Cannot generate unaligned atomic store
zsh: IOT instruction (core dumped)  ./bin/crystal build src/compiler/crystal.cr --cross-compile --target   -s
```

`./bin/crystal -v` output:
```
Crystal 1.5.0 (2022-07-10)

LLVM: 14.0.6
Default target: x86_64-pc-linux-gnu
```

`/bin/crystal -v` produces the same output.

OS: Arch Linux July 2022.

I don't know any Crystal at all; I'm only compiling it so I can compile a program written in Crystal.

Thanks in advance!

**Comment by jhass** [comment]
These instructions are very outdated. 

Also note that the target architecture for ARM64 is `aarch64`, `arm` targets 32bit ARM.

If you're running Archlinux ARM on the target there's no need to cross-compile, just install the package: https://archlinuxarm.org/packages/aarch64/crystal.

Otherwise you should have some luck with running the static Alpine builds on the target or cross compiling via an Alpine based docker container.

**Comment by jtbx** [comment]
Thank you very much! After installing the deb package, Crystal works fine. Thank you!
