### ISSUE TITLE
Deprecations output the last seen deprecation

### ISSUE THREAD

**Issue by stakach** [crystal-lang/crystal#12303]
I have an issue where we are getting the following warning:

```
In /usr/share/crystal/src/uri/encoding.cr:123:25

 123 | String.build { |io| encode(string, io, space_to_plus: space_to_plus) }
                           ^-----
Warning: Deprecated URI.encode:space_to_plus. Use `.encode_path` instead.
```

However we really want to know what code called the parent function, which also has a deprecation warning on it.
https://github.com/crystal-lang/crystal/blob/master/src/uri/encoding.cr#L121

So it would be nice if either there was a list of deprecations or only the first is output (versus the last)

**Comment by stakach** [comment]
seems related to #8639

**Comment by HertzDevil** [comment]
Duplicate of #13507?

**Comment by stakach** [comment]
funnily enough we still haven't found where the warning is coming from
so we have one project still outputting that warning - figure once something is actually removed we'll finally find where it's coming from.

I think @straight-shoota 's issue would resolve this so happy to close in favour of that issue
