### ISSUE TITLE
Interpreter: incorrect class after `as` for generic class inheriting from concrete class

### ISSUE THREAD

**Issue by cyangle** [crystal-lang/crystal#12302]
## Bug Report
Example code:
```crystal
class A
end

class B(T) < A
end

b = B(String).new.as(A)

puts b.class # `A` in interpreted mode, `B(String)` in compiled mode
```

**Comment by asterite** [comment]
It turns out this is a bug in the compiler:

```crystal
class A
end

class B(T) < A
end

puts B(String).new.as(A).is_a?(B(String).class)
```

The above prints `false` but it should be `true`.

It doesn't work well in the interpreter because multidispatch is implemented differently...

**Comment by HertzDevil** [comment]
Some of the variants of this example are probably covered in #10394

**Comment by asterite** [comment]
@HertzDevil Thanks!

I think there's one or two missing cases in `Type.common_descendent`, maybe? If you want, feel free to tackle this (it's going to take me a lot more time, I'm sure)
