### ISSUE TITLE
[CI] GitHub Actions is deprecating `macos-10.5`

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#12332]
We're currently using the `macos-10.5` image in GHA which is deprecated and expected to be removed by end of August (https://github.com/actions/virtual-environments/issues/5583).

I have started the infrastructure update at https://github.com/crystal-lang/crystal/compare/master...straight-shoota:crystal:feature/ci-upgrade-macos?expand=1
Besides updating macos, some GHA actions needed an upgrade as well as nixpkgs in order to be compatible with `macos-12`.

But now there are some spec failures, which is really unexpected from an OS update.
https://github.com/straight-shoota/crystal/runs/7558548524?check_suite_focus=true

I don't know what's going on there, but it looks like the executable path has changed somehow...? 

Debugging on GHA is hard and I don't have access to MacOS hardware.
Can someone using MacOS try to recreate the failures and figure out how to fix them?

**Comment by straight-shoota** [comment]
I started an alternative test to upgrade only to `macos-11` for now (https://github.com/straight-shoota/crystal/tree/feature/ci-upgrade-macos-11).

This one only has a single spec failure:
https://github.com/straight-shoota/crystal/runs/7842214765?check_suite_focus=true

```
     1) PROGRAM_NAME works for UTF-8 name
       Failure/Error: File.exists?(executable_file).should be_true
  
         Expected: true
              got: false
  
       # spec/std/spec_helper.cr:86
```

In a [second run to get some diagnostics](https://github.com/straight-shoota/crystal/runs/7842944014?check_suite_focus=true), I got this error message:
```
  ld: can't open output file for writing: $/tmp/cr-spec-376c7bd6/kernel/303227342200275360237230202, errno=2 for architecture x86_64
  clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
  Error: execution of command failed with code: 1: `clang "${@}" -o '/tmp/cr-spec-376c7bd6/kernel/×‽😂'  -rdynamic -lpcre -lgc -L/nix/store/xpc3xb6hb8rnx755y8fhfnb5am35m9yl-libevent-2.1.12/lib -levent -liconv`
```

**Comment by beta-ziliani** [comment]
If you change the spec to use a pure ascii name, does it pass?

**Comment by beta-ziliani** [comment]
My findings so far: I can reproduce the issue on a nix-shell obtained from the `bin/ci` script on my BigSur macOS x86. For instance, the following fails already: `[nix-shell:crystal-path]$ bin/crystal build test.cr -o ×‽😂`.

What is weird is that if I get the llvm-ir code and compile that using the command issue by `crystal`, then it works fine (avoiding unicode on the crystal side):

```bash
 crystal build --emit=llvm-ir test.cr -o test.ll
 clang test.ll -o ×‽😂 .... (parameters for linking the libs)
 ```
 
 However, if I go the cache dir and issue the command that crystal calls to do the linking, then it fails:
 
 ```bash
clang (bunch of .o) -o ×‽😂 ... (parameter for linking the libs)

ld: can't open output file for writing: $/Users/beta/projects/crystal/crystal/×‽360237230202, errno=2 for architecture x86_64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
 ```

**Comment by HertzDevil** [comment]
It looks like stack traces aren't working at all:

```
/private/tmp/cr-spec-ad360638/call_stack/executable_file in 'Exception::CallStack::unwind:Array(Pointer(Void))'
/private/tmp/cr-spec-ad360638/call_stack/executable_file in 'Exception::CallStack#initialize:Array(Pointer(Void))'
/private/tmp/cr-spec-ad360638/call_stack/executable_file in 'Exception::CallStack::new:Exception::CallStack'
/private/tmp/cr-spec-ad360638/call_stack/executable_file in 'caller:Array(String)'
/private/tmp/cr-spec-ad360638/call_stack/executable_file in 'Kls#callee1:Nil'
/private/tmp/cr-spec-ad360638/call_stack/executable_file in 'callee3:Nil'
/private/tmp/cr-spec-ad360638/call_stack/executable_file in '__crystal_main'
/private/tmp/cr-spec-ad360638/call_stack/executable_file in 'Crystal::main_user_code<Int32, Pointer(Pointer(UInt8))>:Nil'
/private/tmp/cr-spec-ad360638/call_stack/executable_file in 'Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32'
/private/tmp/cr-spec-ad360638/call_stack/executable_file in 'main'
```

**Comment by HertzDevil** [comment]
Here:

https://github.com/crystal-lang/crystal/blob/bab729a56d4a212f6d2b32caede2d014c4fb27a0/src/exception/call_stack/mach_o.cr#L93-L113

[`_NSGetExecutablePath`](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/dyld.3.html) may not return a real path, but apparently `_dyld_get_image_name` does. Since `$TMPDIR` is something like `/var/folders/gw/...` where `/var` is a symlink to `/private/var`, the equality on line 107 never happens.

**Comment by beta-ziliani** [comment]
@HertzDevil IIUC this is a platform-specific issue, unrelated to GH Actions, right? We should move it away from here if that's the case.

**Comment by HertzDevil** [comment]
Yeah those spec failures are locally reproducible on a macOS 12.6 M2, they are not exclusive to the CI environment.

The Unicode file name issue seems to happen only within a Nix shell; something as simple as `echo 'int main(void){}' > test.c && clang -o ×‽😂 test.c` also produces an offending filename. But if you take the path from `command -v clang` inside a Nix shell and use it outside a Nix shell, then everything works again.

**Comment by beta-ziliani** [comment]
Oh it didn't occur to me to try plain C 🤦 . OK, then this is not on us. I guess we should disable that spec on nix.

About the M2 issue, I'll let you create the issue and/or the PR :-)

**Comment by straight-shoota** [comment]
I disabled that spec in nix-shell. But now CI is breaking because it can't find  `llvm-config` ???
> /nix/store/ggn696yjnd8vzwiyq5da3lww0wyghs9g-llvm-11.1.0/bin/llvm-config: No such file or directory

https://github.com/straight-shoota/crystal/actions/runs/3077712965/jobs/4973059809

No idea what this is now. It only happens in the *Test Interpreter* step which runs after the *Test*. And that one had already compiled that same file and should've been able to find `llvm-config`.

**Comment by HertzDevil** [comment]
https://github.com/crystal-lang/crystal/blob/d8d3a0f11d8a6c851f7729fd3a78e97131b0744f/shell.nix#L126

This line seems wrong because `llvm-config` alone is placed in `...-llvm-x.y.z-dev/bin` instead of `-llvm-x.y.z/bin`.

**Comment by straight-shoota** [comment]
Apparently nixpkgs changed the location of `llvm-config` into a separate package. That should be easy to fix (waiting for CI to finish: https://github.com/straight-shoota/crystal/tree/feature/ci-upgrade-macos-11).

I suppose the target sys mismatch probably comes from a difference in LLVM versions use b`y the compiler and the spec binary at runtime.

**Comment by beta-ziliani** [comment]
For reference, clang+nixOS is the culprit: https://discourse.nixos.org/t/issues-in-recent-versions-with-unicode-support-clang/21749

**Comment by HertzDevil** [comment]
I could get LLVM 10 to 14 working locally, however LLDB only works for 11 and 12.
