### ISSUE TITLE
Nilable type expansion not overriding existing method

### ISSUE THREAD

**Issue by icy-arctic-fox** [crystal-lang/crystal#12330]
A nilable type and a union of the same type with nil are considered different to some parts of the compiler. For instance, `Path | String?` and `Path | String | Nil` are not always equal. This can be shown with the following code:

```crystal
def foo(arg : Path | String? = nil)
  puts "first"
end

def foo(arg : Path | String | ::Nil = nil)
  puts "second"
end

foo
```

https://carc.in/#/r/dimy

The expected output is "second", but "first" is actually printed.

The use case I have is overriding an existing method with a macro. The macro expansion changes `String?` to `String | ::Nil`. I think the types are being compared as `Union(Path, Union(String, Nil))` and `Union(Path, String, Nil)`. The union should be flattened.

Dumping the methods with this macro:

```crystal
macro finished
  {% puts @top_level.methods.select { |m| m.name == :foo.id } %}
end
```

produces (cleaned up):

```crystal
def foo(arg : Path | String | ::Nil = nil)
  puts("first")
end

def foo(arg : Path | String | ::Nil = nil)
  puts("second")
end
```

The compiler thinks there are two different methods, even though the method signatures are exactly the same when dumped (because it expands `T?` to `T | ::Nil`).

Crystal v1.5.0

[Related issue comment.](https://github.com/icy-arctic-fox/spectator/issues/44#issuecomment-1194949417)

**Comment by HertzDevil** [comment]
It does not seem to be triggered by flattening of unions:

```crystal
def foo(x : Int32 | String)
  1
end

def foo(x : ::Int32 | String)
  2
end

foo "" # => 1
```
