### ISSUE TITLE
Rename share/bash-completion/completions/crystal to share/bash-completion/completions/crystal.bash to make it more general(as does by most of command line library)

### ISSUE THREAD

**Issue by zw963** [crystal-lang/crystal#12336]
We can check the famous find alternative tools [fd](https://github.com/sharkdp/fd), following is it build script.

https://github.com/sharkdp/fd/blob/master/.github/workflows/CICD.yml#L208-L209

We can check those tools differentiate the auto-completion for bash, fish etc with a extension name.

**Comment by asterite** [comment]
Thank you! I would suggest adding some context, links or explanations to avoid everyone having to search what this means.

**Comment by zw963** [comment]
Updated.
