### ISSUE TITLE
Interpreter: BUG: missing interpret assig closured instance var of pass-by-value

### ISSUE THREAD

**Issue by cyangle** [crystal-lang/crystal#12341]
## Bug Report
I found this bug from athena-validator.

It also encounters the bug of `missing mixed union upcast`.

Example code:
```crystal
struct A
  @block : ->

  def initialize(&block)
    @block = block
  end

  def call
    @block.call
  end
end

struct B
  @count = 0

  def bar
    A.new do
      "test".tap { @count = +1; puts @count }
    end.call
  end
end

B.new.bar
```

Interpreter error:
```
In bin/bugs/closure.cr:23:7

 23 | B.new.bar
            ^--



In bin/bugs/closure.cr:23:7

 23 | B.new.bar
            ^--
Error: compiling B.new.bar


In bin/bugs/closure.cr:17:5

 17 | A.new do
      ^
Error: compiling -> do

  "test".tap do
    @count = +1
    puts(@count)
  end
end


In bin/bugs/closure.cr:18:14

 18 | "test".tap { @count = +1; puts @count }
             ^--



In bin/bugs/closure.cr:18:20

 18 | "test".tap { @count = +1; puts @count }
                   ^
Error: BUG: missing interpret assig closured instance var of pass-by-value
```

**Comment by asterite** [comment]
Reduced:

```crystal
def closure(&block)
  block
end

struct Foo
  @count = 0

  def foo
    closure do
      @count = 1
    end
  end
end

Foo.new.foo
```

**Comment by asterite** [comment]
It's interesting because an instance variable of a closured struct is set. But a closured struct's value is always copied: the original value doesn't change.

Look at this:

```crystal
def closure(&block)
  block
end

struct Foo
  @count = 0

  def foo
    closure do
      @count = 1
    end
  end

  def count
    @count
  end
end

foo = Foo.new
foo.foo
puts foo.count
```

With compiled crystal, the output is... zero!

I think this should actually be a compile error, because it doesn't make sense.

In any case, I'll make it at least run fine through the interpreter for now.

**Comment by Sija** [comment]
@asterite Isn't the reason is that the `block` is never called? In `Foo#foo` it's just being passed as an argument and then returned back 🤔

**Comment by asterite** [comment]
Thanks! I just fixed the example. What output do you get now?

**Comment by cyangle** [comment]
I got the correct result.

**Comment by cyangle** [comment]
The example is a bad one. Indeed you can not change the closured struct. It's still a valid use case to closure a struct for read only usages though.
