### ISSUE TITLE
Parsing: recognize literal hashes instead of blocks without () (unexpected token: =>)

### ISSUE THREAD

**Issue by PragTob** [crystal-lang/crystal#1235]
```crystal
hash.should eq({4 => "Anna", 3 => "Ary", 5 => "Alice"}) # works fine

hash.should eq {4 => "Anna", 3 => "Ary", 5 => "Alice"} # breaks
#Syntax error in ./spec/std/enumerable_spec.cr:310: unexpected token: =>
#
#      hash.should eq {4=>"Anna", 3=>"Ary", 5=>"Alice"}
#                      ^

```

I think that if it has a clear `key => value` it should be possible to parse as a hash - would be nice at least :)

PS: Personally I'd also be happy if `{}` style blocks were dropped as I hate it in ruby that 2 immensely important constructs use such a similar literal notation. I do lots of a teaching and it's a nightmare :) But I'm probably the minority here. If others feel the same way, then let's open a new issue :)

**Comment by stugol** [comment]
I agree with the first point. Hash literals should be easier to parse. I disagree strongly, however, with the removal of braced blocks.

**Comment by jhass** [comment]
Related to #891

**Comment by PragTob** [comment]
Thanks for triaging the issues @jhass ! :) :+1:

**Comment by asterite** [comment]
I don't think will do this. It requires a big look-ahead in every `{` in a call. There's also the thing that it can also be confused with a tuple:

```crystal
foo.bar {a, b = c, d} # a block with multiple assignment, or a tuple?
```
And even if we solve that ambiguity, I think making `foo { ... }` always denote a block is visually easier to distinguish from maybe a hash and a tuple, so the programmer doesn't have to stop at every `{` and ask that question.
