### ISSUE TITLE
Feature request: multiple blocks

### ISSUE THREAD

**Issue by stugol** [crystal-lang/crystal#1237]
In the small Ruby-esque language "Fancy", due to the existence of named keywords, it is possible to pass more than one block to a method. See https://github.com/fancy-lang/infancy/blob/master/Chapter01.md#122-control-structures.

I feel that this would be a very nice addition to Crystal, possibly in conjunction with a previously-mentioned feature request, namely the ability to mark specific method arguments as named, disallowing the calling of the method without naming the variables. For example:
```
def fn(a, named b)
end

fn(1, 2)           # error
fn(1, b: 2)   # correct
```
Of course it would make a bit more sense to use some kind of punctuation instead of the keyword ```named```, but the principle is the same.

**Comment by jhass** [comment]
I think I'd prefer to see better type inference for Proc (`->`) literals, so that you can just
```cr
def foo a, b
  a.call("foo")
  b.call(1)
end

foo ->(e) { puts e }, ->(e) { e * 3 }

**Comment by stugol** [comment]
But procs incur a performance hit.

**Comment by asterite** [comment]
Multiple blocks can't be done because `yield` always refers to the only block given. For multiple "blocks" you can use multiple procs. If the proc literal syntax is long one can use macros to clean up things a bit, as in [here](https://play.crystal-lang.org/#/r/wjz).
