### ISSUE TITLE
heredoc does not work if parentheses is on same line

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#12379]
I noticed that when a parentheses is on the same line when calling a function heredoc does not compile correctly.

https://play.crystal-lang.org/#/r/dlry
```crystal
def foo(x)
  puts(x)
end

# CASE(1): succeeds
foo(<<-FOO
crystal
FOO
)

# CASE(2): fail
foo(<<-FOO
crystal
FOO)

# CASE(3): fail
foo(<<-FOO crystal FOO)
```

**Comment by asterite** [comment]
Hi!

That's correct, but it's by design. It's the same in Ruby.

The correct syntax is:

```crystal
foo(<<-FOO) # Note the closing parentheses
crystal
FOO
```

Also check the docs: https://crystal-lang.org/reference/1.5/syntax_and_semantics/literals/string.html#heredoc
