### ISSUE TITLE
Debian + MT + partial static linking

### ISSUE THREAD

**Issue by phil294** [crystal-lang/crystal#12380]
## Bug Report

`Crystal 1.5.0 [994c70b10] (2022-07-06) / LLVM: 10.0.0 Default target: x86_64-unknown-linux-gnu`

I'm trying to link a C library (libxdo) statically, but keep the remaining ones dynamic. Specifying `--static` for this does not work because then the compiler forces static mode on all other C bindings and because I have no static builds for those, it fails. I think this is contrary to what the docs say.

However, I got it to work just fine by distinguishing with `-Bstatic` and `-Bdynamic` as follows, on Arch Linux:
```
CRYSTAL_LIBRARY_PATH="$PWD/static" shards build -Dpreview_mt --link-flags="-Wl,-Bstatic -lxdo -Wl,-Bdynamic -lxkbcommon -lXinerama -lXtst"
```

However, this fails pretty badly on Debian (using Docker):
```
Dependencies are satisfied
Building: ahk_x11
Error target ahk_x11 failed to compile:
/usr/bin/ld: G-C-.o: in function `set_stackbottom':
/usr/share/crystal/src/gc/boehm.cr:274: undefined reference to `GC_set_stackbottom'
/usr/bin/ld: G-C-.o: in function `current_thread_stack_bottom':
/usr/share/crystal/src/gc/boehm.cr:265: undefined reference to `GC_get_my_stackbottom'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o /b/ahk_x11/bin/ahk_x11 -Wl,-Bstatic -lxdo -Wl,-Bdynamic -lxkbcommon -lXinerama -lXtst -lXi -rdynamic -L/b/ahk_x11/static -lxdo -lX11 -lgtk-3 -lglib-2.0 -lgobject-2.0 -lglib-2.0 -lgobject-2.0 -lglib-2.0 -lpcre -lm -lgc -lpthread -levent_pthreads -levent -levent -lrt -lpthread -ldl`
```
Adding those link flags also required me to install `libgc-dev` for some reason.

Am I doing something wrong? This stack trace makes me assume it's not my fault. Thanks!

Edit: Due to the nature of this problem this can't be reproduced in a few seconds. If necessary, I can build a small setup bash script?

**Comment by straight-shoota** [comment]
Looks like you're linking against an older version of libgc that doesn't have `GC_set_stackbottom`. That's a relatively new addition, pushed forward specifically for Crystal's use case. The library in our distribution packages usually includes that function.

In order to link a library statically, you just need to have a static version of the library available and tell the linker to prefer that over the dynamic one. If both are on the same directory, `ld` prefers the dynamic lib.
An easy way to achieve that is to put attic libraries in a dedicated path and prepend that to the library path lookup.
Then the linker should pick the static libraries before even looking at the dynamic ones.

**Comment by phil294** [comment]
Oh that's interesting. Indeed, it works, with a more recent gc version.

Thanks for your help regarding linking, you're right, `-Bstatic` and `-Bdynamic` wasn't actually necessary. `libxdo.a` is in `static`, so it would be enough to run `CRYSTAL_LIBRARY_PATH="$PWD/static" shards build -Dpreview_mt`.

However, as `libxdo` has dependencies too and these should be dynamically linked (xinerama,xkbcommon,xst,xi), I needed to specify them too, by adding the link-flags. And this

```
 CRYSTAL_LIBRARY_PATH="$PWD/static" shards build -Dpreview_mt --link-flags="-lxdo -lXinerama -lxkbcommon -lXtst -lXi"
```
still fails with the `GC_set_stackbottom` error from above, so apparently those link flags mess up the shipped Crystal GC function linking? 🤔

I have been able to work around this by statically linking a custom local build of `libgc.a` as well. Is this the right approach?

**Comment by straight-shoota** [comment]
With overwriting `CRYSTAL_LIBRARY_PATH` the linker can't find the bundled version of libgc. This path is baked into the compiler's default value for that variable (cf `crystal env CRYSTAL_LIBRARY_PATH`).
So now the linker just looks in your regular lib paths and only finds some older version of the library.

In stead of overwriting `CRYSTAL_LIBRARY_PATH` you probably want to just pass another path to the linker with `--link-flags="-L$PWD/static"`.

**Comment by phil294** [comment]
Neat, that works! Should we briefly document the danger of overwriting CRYSTAL_LIBRARY_PATH in guides/static_linking.html? I can send in a short PR if you want.

Either way, thanks again for your help :-)
