### ISSUE TITLE
Add as_nil? to JSON::Any

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/crystal#12413]
JSON::Any has 2 different casting variant methods for each common cast like `as_i` and `as_i?` or `as_s` and `as_s?`. It seems to have this for every one except `as_nil` which doesn't have a `as_nil?`.

This would be used for when you're not sure if a nil will exist or not.

```crystal
require "json"

jsona = JSON::Any.new(nil)

jsonb = JSON::Any.new({} of String => JSON::Any)

# you can do this
jsona.as_nil.nil? #=> true

# but this raises an exception
jsonb.as_nil.nil? #=> Unhandled exception: cast from Hash(String, JSON::Any) to Nil failed
```

~I know that we can technically do `jsona.nil?` which would return true, and `jsonb.nil?` which would return false, but the problem is that both still return a `JSON::Any` object which means you can't pass them as an argument to method overloads like this without some extra work.~

```crystal
def handle_json(data : Nil)
end

def handle_json(data : JSON::Any)
end
```

Edit: actually... scratch that... looks like `jsona.nil?` returns false :stuck_out_tongue_closed_eyes:  which makes more sense because it's not Nil, it's JSON::Any representing `null` :zany_face:

**Comment by Blacksmoke16** [comment]
Could also just do this:

```cr
require "json"

jsona = JSON::Any.new(nil)

jsonb = JSON::Any.new({} of String => JSON::Any)

pp jsona.raw.nil? # => true
pp jsonb.raw.nil? # => false
```

**Comment by straight-shoota** [comment]
I don't quite follow what this is about. There are no such `#to_*` methods on `JSON::Any`, the conversions are all called `#as_*`.
The variants with a question mark such as `as_s?` return `nil` if the raw value doesn't have the requested type. For `Nil` this doesn't seem to make much sense.

If you want to know whether an `Any` wraps nil, `raw.nil?` seems the best solution.

**Comment by jwoertink** [comment]
The `to_` stuff was a typo. I just updated it. 

What I'm saying is we can do `as_s` if we know it'll be a string, and `as_s?` if we think it'll be a string, and we can do `as_nil` if we know it'll be nil, but we can't do `as_nil?` if we think it'll be nil. Yes, we can use `raw.nil?`, but why change up the convention?

**Comment by straight-shoota** [comment]
The result of `as_nil?` would always be `nil`, regardless of the value of `@raw`. So I don't think such a method has much purpose.
