### ISSUE TITLE
crystal-1.5.1-1-darwin-universal.tar.gz is broken

### ISSUE THREAD

**Issue by evgkrsk** [crystal-lang/crystal#12463]
## Bug Report

Seems like tar archive generation for darwin is broken: v1.5.1 archive release is only 118Kb (versus 44Mb for v1.5.0).

As result, some CICD pipeines is broken: https://github.com/evgkrsk/reqs-up/runs/8263698759

**Comment by straight-shoota** [comment]
I uploaded the correct package.

Something must have gone wrong while uploading the package to GitHub. The `crystal-1.5.1-1-darwin-universal.tar.gz` was only 118kb, and the full archive was instead named `crystal-1.5.1-1-darwin-universal.tar.gz.1`.

/cc @beta-ziliani Did you use the automation script https://github.com/crystal-lang/distribution-scripts/blob/master/processes/scripts/publish-crystal-packages-on-github.sh for that? If so, can you retrace what might've gone wrong?

**Comment by evgkrsk** [comment]
Thanks!

**Comment by beta-ziliani** [comment]
@straight-shoota I did. Unfortunately I don't have the history of the session nor the tmp files to track what happened.
