### ISSUE TITLE
can't extend non-abstract struct File::Info with Crystal 1.6

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/crystal#12470]
The [Crystar shard](https://github.com/naqvis/crystar/issues/11) has this error where it won't compile with 1.6.0-dev, but compiles fine on 1.5.1. 

I know it's an issue with the shard, but I figured I would open this up anyway just in case this causes a larger breaking change.

**Comment by straight-shoota** [comment]
This is a result of #12385 (and resolves https://github.com/crystal-lang/crystal/issues/7685).

The fact that `File::Info` was an abstract struct up to Crystal 1.5 was an implementation detail. This API design was wrong in the first place. It was not intended to be inherited by custom types. Thus this change, though it's technically breaking the API, was considered acceptable.

I think the usage in this shard is absurd. The custom type `HeaderFileInfo` works completely fine without inheriting the stdlib type `File::Info`.

```diff
--- i/src/tar/header.cr
+++ w/src/tar/header.cr
@@ -419,8 +419,7 @@ module Crystar
     end
   end

-  # HeaderFileInfo extends File::Info
-  private struct HeaderFileInfo < File::Info
+  private struct HeaderFileInfo
     getter header : Header

     def initialize(@header)
```
