### ISSUE TITLE
Method to bump semantic version

### ISSUE THREAD

**Issue by gabriel-ss** [crystal-lang/crystal#12499]
Recently, I've been using Crystal at work to create some tools for the team and it's been awesome. One of the features of the std lib that has been very useful is the Semantic Version module; having a class with all the arithmetic for versions implemented helped during the development of many tools.

The only feature it currently lacks is a method to evaluate the next semantic version given the current version and the type of bump. Since this is a snippet that I reused in multiple projects, I thought that other people might find it useful enough to have in the std lib.

My implementation, created by extending the std class, can be used as:
```crystal
current_version = SemanticVersion.new 1, 1, 1
next_minor = current_version.bump SemanticVersion::Bump::Minor
next_minor # => SemanticVersion(@build=nil, @major=1, @minor=2, @patch=0, @prerelease=SemanticVersion::Prerelease(@identifiers=[]))
```

Is there any interest in a PR adding something like this to the language?

**Comment by beta-ziliani** [comment]
Nice! Getting ahead of a possible PR, I have a question. I understand that you have something like

```crystal
enum Bump
  Major
  Minor
  Patch
end
```

How do you fancy the name `Part` instead?

**Comment by gabriel-ss** [comment]
Well, the enum is actually
```crystal
  enum Bump
    Major
    Minor
    Patch
    PreMajor
    PreMinor
    PrePatch
    PreRelease
  end
```
So `Part` may be a little misleading of the nature of the operation, given that a single command could operate in a part and in the pre release at the same time. I could change this, though; there are other implementation details that are just conventions.

I used some CLI tools that do version operations (namely npm and poetry) as a base, but even then there are some differences in behavior, so I could make changes to make the implementation a better solution for the community needs.

**Comment by gabriel-ss** [comment]
@beta-ziliani I made a [draft](https://github.com/crystal-lang/crystal/compare/master...gabriel-ss:crystal:feature/semantic-version-bump) with the snippets I've been using so far; any suggestions to make it more suitable for a PR?

**Comment by beta-ziliani** [comment]
We'll look into it after 1.6 is released.

**Comment by beta-ziliani** [comment]
Hi @gabriel-ss thanks for your patience! I checked your proposal. I'd say I prefer to have different methods for each part, as in `bump_major`, `bump_minor`, etc, and to split the pre-release. If you want to go from `1.1.2` to `1.2.0-alpha`, it's perfectly reasonable to do it in two steps (first bump the minor, and then add the pre-release). WDYT?

**Comment by straight-shoota** [comment]
As suggested in https://github.com/crystal-lang/crystal/issues/7637#issuecomment-592221834, I think a method `#copy_with` would also make sense. It would work the same way as the implementation provided by the `record` macro. It allows to easily change individual aspects of a version and could be the basic building block on top of which the `bump_*` methods are implemented.

**Comment by gabriel-ss** [comment]
Hey @beta-ziliani, using a `#copy_with` to build different methods could definitively be a way to go!

The only point is how exactly to handle the pre-releases; since a version with a pre-release is actually lower than the same version without one, doing it in two operations would mean to go backwards in the second one. Not really a problem, just a little quirk, and probably means that there is a part of the version handling logic that the applications will have to implement themselves, but then again maybe the need for this functionality doesn't come very often.

What do you have in mind for an API to manipulate the pre-releases?

**Comment by beta-ziliani** [comment]
I'm not sure about bumping prereleases. It only works for scenarios like "rc", but not in those like "alpha", so in those cases I guess it's simpler to just go with `#copy_with`.

I have three possible implementations, probably the last one is my favorite, but not strongly.

 1. A method for each bump:

```cr
def bump_major(prerelease : String | Prerelease | Nil = nil, build : String? = nil)
def bump_minor(prerelease : String | Prerelease | Nil = nil, build : String? = nil)
def bump_patch(prerelease : String | Prerelease | Nil = nil, build : String? = nil)
def bump_prerelease(build : String? = nil) # precondition: it should have a prerelease! And I'm not sure it should exists
```

 2. One method + Enum:

```cr
# In this scenario Part makes more sense
Enum Part
  Major
  Minor
  Patch
  Prerelease # not sure about this one
end

def bump(part : Part, prerelease : String | Prerelease | Nil = nil, build : String? = nil)
```

 3. `copy_with` augmented with a unit value for triggering a bump in the specific field:

```cr
struct Bump
end

BUMP = Bump.new

def copy_with(major : Int | Bump = @major, minor : Int | Bump = @minor, patch : Int | Bump = @patch, prerelease : String | Prerelease | Nil = @prerealease, build : String? = @build)
```

**Comment by straight-shoota** [comment]
My preference would be this:

4. Generic `#copy_with` sans any special semantics and some bump methods for convenience.

```cr
def copy_with(major : Int32 = @major, minor : Int32 = @minor, patch : Int32 = @patch, prerelease : String | Prerelease | Nil = @prerealease, build : String? = @build)
def bump_major
def bump_minor
def bump_patch
```

**Comment by gabriel-ss** [comment]
I agree with the arguments about the pre-releases; it's really hard to come up with a bump implementation that would work across multiple conventions. Maybe the best here is to just leave it open.

About the methods to bump versions, I find the semantic of
```crystal
version.copy_with(minor: BUMP)
```
very elegant, but at the same time, if copy_with is supposed to be a low-level building block to, say, a package manager, I don't know if the special semantics would be appropriated. I'm divided between 3 and 4 in this case.

In both cases though, I think it would bring a great convenience by handling the edge cases, in special bumping the patch of a pre-release. I would be happy with either one.

**Comment by beta-ziliani** [comment]
let's go with 4. sounds good?
 it's true that a bump is not just a +1 in the part.

**Comment by gabriel-ss** [comment]
Nice! Do you mind if I work on my previous implementation to make a new draft over the weekend? I'll let you guys know as soon as it's ready.

**Comment by gabriel-ss** [comment]
@straight-shoota, @beta-ziliani made a [new draft](https://github.com/crystal-lang/crystal/compare/master...gabriel-ss:crystal:feature/semantic-version-copy-with)! What are your thoughts on this one?

**Comment by straight-shoota** [comment]
Looks good. Why don't you open a PR for it?
