### ISSUE TITLE
[Android] Failed to generate multi-threaded binary with `-Dpreview_mt` on Termux

### ISSUE THREAD

**Issue by anzhi0708** [crystal-lang/crystal#12509]
Since Crystal is not currently available on Termux, I installed Crystal using `proot-distro` (simulated Alpine, Arch & Debian environment).

When tried to compile to binary using `-Dpreview_mt` flag, error occurred saying failed to check if stack was overflowed and stuff.

Works fine on my Mac tho

**Comment by straight-shoota** [comment]
Can you post the entire error message please?

**Comment by anzhi0708** [comment]
> Can you post the entire error message please?

Termux just updated their official packages; now `proot-distro` could not be installed cuz it depends on `ncurses 6.3-2` but only `ncurses 6.3-3` found in Termux repo. I'll try it a few days later after this problem is fixed... sry (btw I think now `rustc` is broken too since they also updated `clang`)

**Comment by anzhi0708** [comment]
@straight-shoota I installed crystal with proot-distro alpine again; this time `-Dpreview_mt` works perfectly :-D closing this issue

**Comment by hotty316** [comment]
>  you post the entire message please 9205779629<

Linux localhost 5.4.0 #1 SMP PREEMPTIVE Tue 19 Sep 16:53:35 CST 2023 aarch64 Linux

**Comment by hotty316** [comment]
``
