### ISSUE TITLE
Flags enums: prevent `All` and `None` keywords

### ISSUE THREAD

**Issue by decioferreira** [crystal-lang/crystal#1251]
Should the compiler prevent the definition of `All` and `None` keywords on flag enums?

``` crystal
@[Flags]
enum IOMode
  None # 1
  All  # 2
end

puts IOMode::None.value #=> 1
puts IOMode::All.value  #=> 2
```

**Comment by asterite** [comment]
Probably. I don't know if there's a use case where you'd want to overwrite those, and in any case it would yield unexpected results. Thanks for noticing this!

**Comment by ervumlens** [comment]
`All` and `None` values would be pretty nice to have in a flag enum, defined to the appropriate values. And as long as I'm dreaming, it would be good to have the option to specify the names as well. :smile:

Borrowing  decioferreira's example:

```ruby
@[Flags(all: :All, none: :Empty)]
enum IOMode
  In # 1
  Out  # 2
end

puts IOMode::Empty.value #=> 0 because the "none" name was set to :Empty
puts IOMode::All.value  #=> 3 because the "all" name was set to :All
puts IOMode::None.value # error: no such constant
```

**Comment by oprypin** [comment]
I think that having `All` in all enums without opt-out is bad, because it's an API contract. You may want to add a flag that makes no sense to have under normal circumstances but people are already using `All`. And being unable to override it (to keep previous behavior) makes it worse.

**Comment by RX14** [comment]
`All` Doesn't seem to be used much in the stdlib, I'd be in favour of removing it for the problems it causes when adding new values.

**Comment by jhass** [comment]
I see the argument OTOH it seems like a handy tool too. Maybe we can come up with some more explicit way of defining it, like `All = {@all}`, which could even allow `All = {All & ~Foo}`?

**Comment by bcardiff** [comment]
I agree that it would be nice for an opt-out for All/None. And if opted out let the user define/use them (just by plain values as other constants).

All/None have special meaning in Enum#to_s, Enum#each, etc. I wouldn't allow All/None to lose their special semantic.
