### ISSUE TITLE
Rename `File.real_path` to `.realpath`

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#12544]
The spelling is almost everywhere without an underscore:

* CLI util: `realpath`
* LibC function: `realpath`
* no other method on `File` with similar name uses an underscore: `basename`, `dirname`, `tempfile` etc. (`expand_path` is a combination of verb and subject)
* even in Ruby (which the file API is based on): `File.realpath`
* and dozens of other file APIs: `realpath`

So it's pretty clear that the spelling `real_path` is an odd incidence. I regularly misspell it.

I'd like to rename the method to `File.realpath` because it just makes most sense.

**Comment by asterite** [comment]
Yeah, I think we tried to "fix" this compared to Ruby, but Ruby was right 😅
