### ISSUE TITLE
C unions of struct in the interpreter

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#12554]
*Summary:*
This issue is tracking the same problem in https://github.com/crystal-lang/crystal/issues/12550 but for interpreter.
But as suggested by @HertzDevil in https://github.com/crystal-lang/crystal/issues/12554#issuecomment-1265678812 that libffi doesn't support passing c unions by value. So I guess there's nothing we can do for this issue until libffi supports c unions.
Ref to libffi issue: https://github.com/libffi/libffi/issues/33

*Original comment by @cyangle in https://github.com/crystal-lang/crystal/issues/12550#issuecomment-1265631354*:

@asterite It seems like the interpreter is able to load .obj files fine.

CC: @straight-shoota

Below code works totally fine with the interpreter on Ubuntu 22.04

sum.c
```c
extern int sum(int x, int y) {
  return x + y;
}
```
test2.cr
```crystal
@[Link(ldflags: "/home/chao/git/personal/stripe/local/c/sum.obj")]
lib SumLib
  fun sum(x : Int32, y : Int32) : Int32
end

x = 1
y = 2
z = SumLib.sum(x, y)
debugger
puts z
```
debug session:
```
$ cr i test2.cr 
Using compiled compiler at /home/chao/git/personal/crystal/.build/crystal
From: test2.cr:10:6 <Program>#test2.cr:

     5: 
     6: x = 1
     7: y = 2
     8: z = SumLib.sum(x, y)
     9: debugger
 => 10: puts z

pry(test2.cr)> z
=> 3
pry(test2.cr)> SumLib.sum(4, 5)
=> 9
pry(test2.cr)> 
```

System Info:
```
$ cr -v
Using compiled compiler at /home/chao/git/personal/crystal/.build/crystal
Crystal 1.6.0-dev [cb50185d8] (2022-10-01)

LLVM: 14.0.6
Default target: x86_64-pc-linux-gnu
OS: Ubuntu 22.04
```

_Originally posted by @cyangle in https://github.com/crystal-lang/crystal/issues/12550#issuecomment-1265631354_

**Comment by straight-shoota** [comment]
@HertzDevil I didn't look any deeper into the issue, mainly focused on exporting this part from the original issue. Feel free to change the title.

**Comment by asterite** [comment]
Is there a difference between `obj` and `o`? I guess `obj` is on Windows? I just tried with an `.o` file on Mac and it doesn't work:

```
cannot load /Users/aryborenszweig/Projects/crystal/cool_lib.o (dlopen(/Users/aryborenszweig/Projects/crystal/cool_lib.o, 0x0009): tried: '/Users/aryborenszweig/Projects/crystal/cool_lib.o' (unloadable mach-o file type 1 '/Users/aryborenszweig/Projects/crystal/cool_lib.o'), '/usr/local/lib/cool_lib.o' (no such file), '/usr/lib/cool_lib.o' (no such file))
```

**Comment by straight-shoota** [comment]
But yes, struct unions are not supported by libffi. Nothing we can do about that really, I suppose.

Regarding the example above: Is `sum.obj` actually an object file? How did you build it? It has an odd extension - it's usually `.o` on linux.
The interpreter loads libraries via `dlopen` which can only open shared libraries. So this really shouldn't work with an object file.

**Comment by cyangle** [comment]
Oh! My bad! I built it with below command and it's indeed a dynamic lib:
```sh
$ gcc -shared -o sum.obj sum.c
```
@straight-shoota

**Comment by cyangle** [comment]
@asterite I built `sum.c` as a dynamic lib and provided absolute file path to the ldflags in test2.cr:
```
@[Link(ldflags: "/home/chao/git/personal/stripe/local/c/sum.obj")]
lib SumLib
  fun sum(x : Int32, y : Int32) : Int32
end
```
I tested it on Ubuntu 22.04.

**Comment by cyangle** [comment]
@asterite @straight-shoota @HertzDevil It also works on my Intel Mac with minor changes to ldflags.

You need to put `sum.c` and `test2.cr` in same folder and run instruction commands from that folder. Instructions for MacOS are in the comments of `test2.cr`. And the ldflags for MacOS is different from Linux version, so it's better to copy and past below code to reproduce it on MacOS.

sum.c
```c
extern int sum(int x, int y) {
  return x + y;
}
```
test2.cr
```crystal
# MacOS instructions:
# mkdir c
# gcc -dynamiclib -o c/libsum.dylib sum.c
# sudo ln -s "${PWD}/c/libsum.dylib" /usr/local/lib/libsum.dylib
# crystal test2.cr
# crystal i test2.cr
@[Link(ldflags: "-lsum")]
lib SumLib
  fun sum(x : Int32, y : Int32) : Int32
end

x = 1
y = 2
z = SumLib.sum(x, y)
# debugger
puts z
```
debug session:
```
$ /Users/chao/git/personal/crystal/bin/crystal i test2.cr 
Using compiled compiler at /Users/chao/git/personal/crystal/.build/crystal
From: test2.cr:17:6 <Program>#test2.cr:

    12: 
    13: x = 1
    14: y = 2
    15: z = SumLib.sum(x, y)
    16: debugger
 => 17: puts z

pry(test2.cr)> z
=> 3
pry(test2.cr)> SumLib.sum(4, 5)
=> 9
pry(test2.cr)> exit
```
System Info:
```
$ /Users/chao/git/personal/crystal/bin/crystal -v
Using compiled compiler at /Users/chao/git/personal/crystal/.build/crystal
Crystal 1.6.0-dev [4ca9f933a] (2022-10-02)

LLVM: 14.0.6
Default target: x86_64-apple-macosx
```

**Comment by cyangle** [comment]
This issue is tracking the same problem in #12550 but for interpreter.
But as suggested by @HertzDevil in https://github.com/crystal-lang/crystal/issues/12554#issuecomment-1265678812 that libffi doesn't support passing c unions by value. So I guess there's nothing we can do for this issue until libffi supports c unions.
Ref to libffi issue: https://github.com/libffi/libffi/issues/33

@straight-shoota You need to update the description of current issue.

**Comment by straight-shoota** [comment]
Thanks for the summary, I've added it to the OP.

I think we can close this.
