### ISSUE TITLE
Regression when formatting macros with \\{%

### ISSUE THREAD

**Issue by lbguilherme** [crystal-lang/crystal#12578]
Regression from Crystal 1.5 to 1.6 probably caused by #12378.

The following code defines the `bar` method as consequence of two nested macro expansions, and this `bar` method should itself contain a macro that will only be evaluated if the method is invoked somewhere in the source code.

```cr
macro foo
  macro finished
    def bar
      \\{%
        puts "Method bar was called."
      %}
    end
  end
end

foo
bar # <= If you remove this, the message isn't shown.
```

This works well on both 1.5 and 1.6.

But when running `crystal tool format`, the `\\{%` is replaced by `\{%`, which changes the semantics.

(My use case for this: https://github.com/lbguilherme/crystal-js/blob/d9247700e7044ce985eee5c1a27c10066a33301a/src/js/bridge.cr#L263)

**Comment by asterite** [comment]
I can't reproduce this with 1.6.

Could you show what the code looks like before and after it's formatted? Here's what I see. The original code is:

```crystal
macro foo
  macro finished
    def bar
      \\{%
        puts "Method bar was called."
      %}
    end
  end
end

foo
bar # <= If you remove this, the message isn't shown.
```

When I run `crystal tool format` on it, I get this:

```crystal
macro foo
  macro finished
    def bar
      \\{%
          puts "Method bar was called."
      %}
    end
  end
end

foo
bar # <= If you remove this, the message isn't shown
```

So the indentation changes a bit, but it doesn't change the semantic of the program.

**Comment by lbguilherme** [comment]
Sorry, this is the correct repro:

```cr
macro foo
  macro finished
    \{% if true %}
      def bar
        \\{%
        puts "Method bar was called."
        %}
      end
    \{% end %}
  end
end

foo
bar # <= If you remove this, the message isn't shown.
```
