### ISSUE TITLE
prefixing an assignment with "p" or "puts" confuses playground

### ISSUE THREAD

**Issue by robacarp** [crystal-lang/crystal#12575]
In the playground (i.e. `crystal play`), this snippet causes an instrumentation bug:

```crystal
p x = 5
x * 2
```

```
Exception:

error in line 4
Error: instantiating 'Crystal::Playground::Agent#i(Int32)'

error in line 4
Error: instantiating 'Crystal::Playground::Agent#i(Int32)'

error in line 5
Error: undefined local variable or method 'x' for top-level

Did you mean 'p'?
```

This syntax works on https://play.crystal-lang.org, however.

Crystal version 1.6 (also present on 1.5.1)

**Comment by straight-shoota** [comment]
This is a known problem and an instrinsic issue with how code instrumentation works in the playground.
It's tracked in #7091. There's also a more detailed explanation of the cause.

At this point, I do not know if the playground even makes much sense to continue. Maybe it can be refitted around the interpreter which would be faster and allow introspection into the running program without having any affects on its execution.

**Comment by asterite** [comment]
What do you think eventually having the playground use the interpreter? It will be faster and more accurate, as we can hook into the interpreter pretty easily to output things on the browser.

**Comment by straight-shoota** [comment]
That's exactly what I suggested in my last comment.

**Comment by asterite** [comment]
Oh 😅
