### ISSUE TITLE
Regression on redefining a method with splat parameter (overload ordering)

### ISSUE THREAD

**Issue by lbguilherme** [crystal-lang/crystal#12579]
```cr
def foo(*nums : UInt32)
  1
end

def foo(*nums : UInt32)
  2
end

p foo(1)
```

This used to print `2` on Crystal 1.5 and now with Crystal 1.6 it prints `1`. It seems to only happen when a splat in involved.

This is breaking my shard where I rely on rewriting and redefining some methods using macros.

**Comment by straight-shoota** [comment]
This regression was introduced in #10711
