### ISSUE TITLE
Should String#titleize convert underscores to spaces?

### ISSUE THREAD

**Issue by robacarp** [crystal-lang/crystal#12573]
Currently:

```crystal
test = "this_is_text".titleize # => "This_is_text"
```

What I was expecting is:

```crystal
test = "this_is_text".titleize # => "This Is Text"
```

Is that a reasonable assumption, or am I expecting too much?

Unfortunately this would be a minor breaking change.

**Comment by Blacksmoke16** [comment]
Looks like it does in Rails: https://apidock.com/rails/String/titleize.

**Comment by oprypin** [comment]
I can't come up with any reasoning that would lead me to the conclusion that it should replace underscores. Could you provide any rationale?

**Comment by asterite** [comment]
I think the reason is "I have this string which comes from code and I want to show it to users". It's a very Rails-like thing.

**Comment by asterite** [comment]
Like, I want to use all these property names for a form label. The property names likely have underscores, because they are code.

**Comment by oprypin** [comment]
Well, guessing what a form label should look like is kind of a specific thing, I don't think it has place in the standard library, and I haven't seen it anywhere. Anyway I wouldn't expect the only available method for title-casing to also do this unrelated action.

In any case, we absolutely can't just change the behavior, it's a nasty breaking change.

Why not just write code as `.replace('_', ' ').titleize`? It's a much clearer intent anyway.

**Comment by asterite** [comment]
What about adding a named boolean to control the behavior?

**Comment by Blacksmoke16** [comment]
I'd like to suggest a more concrete proposal for this, based on the previous comment. We can support this and be backwards compatible by adding a named only argument to `#titleize` say `underscore_to_space` following along with `URI.decode`'s `plus_to_space` parameter. This would default to `false` to not break existing usages.

```cr
"foo_Bar".titleize                            # => "Foo_bar"
"foo_bar".titleize                            # => "Foo_bar"
"foo_bar".titleize(underscore_to_space: true) # => "Foo Bar"
```

Being sure to support both overloads of `#titleize` as well.
