### ISSUE TITLE
Update GHA to macos-12

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#12570]
The most recent release for the macos runner on GitHub Actions is macos-12.

We should update our CI jobs to that version. But last time I tried, there were a couple of errors (https://github.com/crystal-lang/crystal/issues/12332#issue-1320805497) hence we only updated from 10.5 to 11 for now.

**Comment by HertzDevil** [comment]
It looks like we have completely skipped over this since https://github.com/crystal-lang/crystal/pull/13748?

**Comment by HertzDevil** [comment]
Resolved by #13748
