### ISSUE TITLE
/api/1.6.0/ returns 404

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#12576]
## Bug Report

https://crystal-lang.org/api/1.6.0/ • redirects to 404 🔴
https://crystal-lang.org/api/1.6.0/index.html • works fine 🟢
https://crystal-lang.org/api/1.5.0/ • works as well 🟢

**Comment by straight-shoota** [comment]
The URL resolves perfectly fine. Maybe try to refresh your browser cache?
