### ISSUE TITLE
Const generics aren't typechecked

### ISSUE THREAD

**Issue by shinzlet** [crystal-lang/crystal#12619]
To preface, I'm not sure if this is strictly a bug, as I haven't seen any mention of const generics in the crystal docs. However, this seems like an issue to me:

```crystal
class Foo(N)
  # I would expect that this method could only be called when `self` and `other` have the same value of N:
  def bar(other : Foo(N))
  end
end

# But this compiles fine, even though a is Foo(1) and b is Foo(2)
a = Foo(1).new
b = Foo(2).new
a.bar b
```

You can get around this issue using a free type parameter and a macro, but I imagine that this behaviour is unexpected.

```
$ crystal -v
Crystal 1.6.0 (2022-10-06)

LLVM: 14.0.6
Default target: x86_64-apple-macosx
```

**Comment by BlobCodes** [comment]
Duplicate of #11859

**Comment by shinzlet** [comment]
I didn't find that when I searched! Thanks :)
