### ISSUE TITLE
macOS/arm64 lib binding incorrect - function parameters

### ISSUE THREAD

**Issue by ionos-landgraf-vin** [crystal-lang/crystal#12629]
# Bug Report

Issues of pointers and structs when using libs on macOS. Related to issue: https://github.com/crystal-lang/crystal/issues/12407

##  rect.c

```c
#include <stdint.h>
#include <stdio.h>

typedef struct _Rect {
  uint16_t* f;
  uint32_t a;
  uint32_t b;
} Rect;

Rect* sample(Rect *r, uint16_t* f, uint32_t a, uint32_t b) {
  printf("PTR: %p\n", r);
  printf("F: %p\n", f);
  printf("A: %d\n", a);
  printf("B: %d\n", b);
  return r;
}
```

## rect.cr

```cr
@[Link(ldflags: "#{__DIR__}/rect.o")]
lib LibRect
  struct Rect
    f : UInt16*
    a : UInt32
    b : UInt32
  end

  fun sample(Rect, UInt16*, LibC::UInt, LibC::UInt) : Rect
end

r = LibRect::Rect.new
p r
p LibRect.sample(r, nil, 0.to_u32, 0.to_u32)
p LibRect.sample(r, nil, 1.to_u32, 0.to_u32)
p LibRect.sample(r, nil, 0.to_u32, 1.to_u32)

foo = UInt16.new(123)
p LibRect.sample(r, pointerof(foo), 0.to_u32, 0.to_u32)

```

## Environment

MacOS MacBook Pro (14-inch, 2021) Apple M1 Pro

```
$ crystal -v
Crystal 1.6.0 (2022-10-06)

LLVM: 14.0.6
Default target: aarch64-apple-darwin21.6.0
```

## Reproduce

```
$ gcc -c rect.c
$ crystal rect.cr
LibRect::Rect(@f=Pointer(UInt16).null, @a=0, @b=0)
PTR: 0x0
F: 0x0
A: 0
B: 0
LibRect::Rect(@f=Pointer(UInt16).null, @a=0, @b=0)
PTR: 0x0
F: 0x0
A: 0
B: 1
LibRect::Rect(@f=Pointer(UInt16).null, @a=0, @b=0)
PTR: 0x0
F: 0x0
A: 0
B: 0
LibRect::Rect(@f=Pointer(UInt16).null, @a=0, @b=0)
PTR: 0x0
F: 0x0
A: 1866134382
B: 0
LibRect::Rect(@f=Pointer(UInt16).null, @a=0, @b=0)
```

## Attached this for debugging:

`crystal build --emit llvm-ir rect.cr`

[rect.ll.txt](https://github.com/crystal-lang/crystal/files/9823034/rect.ll.txt)

**Comment by threez** [comment]
Good point. The example is derived from the original code. If I change to be a pointer it **works** for the example given here.

This is the line on the original code that doesn’t work. 

https://github.com/threez/hpdf.cr/blob/master/src/hpdf/page.cr#L1001

And this is the backing lib def:

https://github.com/threez/hpdf.cr/blob/master/src/hpdf/libharu.cr#L177

The test are passing on other architectures but noch on the one above. Like in the original ticket there might be a translation error. 

Thanks for your help.

**Comment by ionos-landgraf-vin** [comment]
Okay I found the issue, seems that on mac there is a change on the lib that makes it a 

```
  fun page_set_dash = HPDF_Page_SetDash(Page, Real*, UInt, Real) : Status
```

instead of 

```
  fun page_set_dash = HPDF_Page_SetDash(Page, UInt16*, UInt, UInt) : Status
```
