### ISSUE TITLE
Error after installing Crystal and launching a .cr file

### ISSUE THREAD

**Issue by Bicio2702** [crystal-lang/crystal#12631]
I've got an error after installing Crystal and launching a simple .cr file within a classic "Hello world" to show.
Can you help me?
Thanks

[log.txt](https://github.com/crystal-lang/crystal/files/9823573/log.txt)

**Comment by Blacksmoke16** [comment]
Are you on windows? How did you install Crystal? The error seems to suggest you're missing `libucrt.lib`.

**Comment by Bicio2702** [comment]
Yes, Windows 10 64. I did a classic installation by scoop and with the command "scoop bucket add crystal-preview https://github.com/neatorobito/scoop-crystal" and the command "scoop install crystal" from Power Shell. Everything has been OK without errors

**Comment by straight-shoota** [comment]
@Blacksmoke16 The error is not about `libucrt.lib`. That's just the last argument to the linker command.

The error is that it can't execute the linker command. Apparently because `cl.exe` is missing.
So @Bicio2702 do you have the Visual Studio Build Tools installed? See [scoop package instructions](https://github.com/neatorobito/scoop-crystal#requirements).

**Comment by straight-shoota** [comment]
> For support the [forums](https://forum.crystal-lang.org/) or one of the [chat channels](https://crystal-lang.org/community/#chat) might be better for this kind of thing.

I think it is exactly right to open an issue in the bug tracker. The error message even instructs to do that.

It's definitely a bug in the compiler. The *origin* of that may be outside the compiler (such as missing VS Build Tools maybe). But the compiler should handle that gracefully and give an informative error message.

**Comment by straight-shoota** [comment]
The compiler needs `cl.exe` installed and either in `PATH` or discoverable via `vswhere.exe`. And it looks like this is not fulfilled.

You could try running from the *x86 Native Tools Command Prompt* which is available in the start menu when you have the build tools installed. `cl.exe` should be in `PATH` there (alternatively, you can run `"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat"` to initialize the build tools environment in an existing command prompt).

**Comment by Blacksmoke16** [comment]
Fixed via #12899
