### ISSUE TITLE
Ability to process binary ASCII-8 bytes.

### ISSUE THREAD

**Issue by gh338** [crystal-lang/crystal#12645]
## Ability to process binary ASCII-8 bytes ( 0x00 ... 0xff )

I need to process raw binary data ( ASCII-8 bit ) with crystal.
I also need to to be able to input ( read ) and output ( write ) those to a file or stdin/out.
I could not find a way around UTF-8 byte encoding.
Sending the UTF-8 data via network to another program that is capable of converting those to ASCII-8 bit is not viable as it limits the processing speed.

**Comment by straight-shoota** [comment]
Are you looking for `Bytes`/`Slice(UInt8)`? https://crystal-lang.org/api/1.6.1/Bytes.html

**Comment by BlobCodes** [comment]
- You can create Strings with raw bytes using `\x__` codes: `"\xFF\xAA\x40"`
- You can read/write raw bytes using `IO#read`, `IO#read_bytes`, `IO#write`, `IO#write_bytes`
- There's also `Bytes` (`Slice(UInt8)`) for array-like access to the data

Strings always use the UTF-8 encoding.
For binary data, it's better to use `Bytes` or `IO`.
Actually, only the bytes 0 to 127 (7 bits) are valid ASCII characters. All these are also valid UTF-8 characters. If you want to read binary data, don't refer to "ASCII". If you actually want to read 7-bit ASCII, just use UTF-8.

**Comment by gh338** [comment]
Thank you,
I'm still getting used to crystal as I have a ruby background.
I came up with this solution:

`struct UInt64
  def to_binary
    io = IO::Memory.new
    io.write_bytes(self, IO::ByteFormat::BigEndian)
    return io
  end
end

print 0x0102030405060708_u64.to_binary`

**Comment by gh338** [comment]
``

**Comment by straight-shoota** [comment]
Hm, that really doesn't look like a great solution for your problem.
But this discussion is better suited for the [Help & Support section of the forum](https://forum.crystal-lang.org/c/help-support/11). If you want more help, please open a thread there and explain what exactly you want to do.
