### ISSUE TITLE
Add `Enumerable(T)#to_a(& : T -> U) forall U`

### ISSUE THREAD

**Issue by caspiano** [crystal-lang/crystal#12643]
## Feature Request

**Is your feature request related to a problem? Please describe clearly and concisely what is it.**

It's common to find patterns like this in Crystal codebases

```crystal
# Cases where the `Enumerable` implements a covariant `map`
enumerable.map(&.some_attribute).to_a
# Or...
enumerable.to_a.map(&.some_attribute)
```

The `map` would be a redundant iteration if `to_a` could accept a block transform.

The implementation of a `to_a` that accepts a block has been previously [discussed as a way to get around covariance issues](https://github.com/crystal-lang/crystal/issues/9184#issuecomment-619957462).

**Describe the feature you would like, optionally illustrated by examples, and how it will solve the above problem.**

Add `Enumerable(T)#to_a(& : T -> U) forall U`

**Describe considered alternative solutions, and the reasons why you have not proposed them as a solution here.**

Writing a loop yourself to improve performance.

```crystal
array = [] of U
enumerable.each do |item|
  array << item.some_attribute
end
``` 

**Does it break backward compatibility, if yes then what's the migration path?**

Nope. However, it would be simple to create a correctable [ameba](https://github.com/crystal-ameba/ameba) rule that would pick this pattern up and transform it.

**Comment by straight-shoota** [comment]
There is already a more efficient alternative to combining `map` and `to_a`. It just means writing a loop yourself. 
```cr
ary = [] of U
enumerable.each do |item|
  ary << item.some_attribute
end
```
So this proposal would make it more convenient to use with less code.

**Comment by straight-shoota** [comment]
I just want to note that this only covers `#each`. There are other `#each_*` (`String#each_char`, `Enumerable methods for which some kind of short cut like this could be nice as well. That's more difficult to do though, and should not taint this proposal, just keep it in mind. Related:  #4813

**Comment by asterite** [comment]
But `Enumerable#map` already returns an `Array`, and calling `to_a` afterwards is a no-op 🤔

**Comment by HertzDevil** [comment]
`#map` is overridden by types like `Slice` and `StaticArray` to return containers of their own types.

**Comment by asterite** [comment]
Maybe then this should be called map_to_a?

**Comment by asterite** [comment]
Or maybe map can accept an argument as the container where to put the data in. Either a class or an instance. Not sure.

**Comment by asterite** [comment]
I guess what I'm thinking is that by having a block in to_a it's not immediately clear that the behavior is map. What if you want to select a few items and put them in a Set without going through an intermediate container? That would be possible if select accepted a first argumento as the container.

It also remainds me a bit of Elixir's into function.

**Comment by HertzDevil** [comment]
The motivation I believe is by analogy to `#to_h`.

**Comment by caspiano** [comment]
@asterite I can implement this one if you'd like :)

**Comment by asterite** [comment]
Sounds good to me!

**Comment by asterite** [comment]
I guess we are still talking about to_a with a block, right?

**Comment by caspiano** [comment]
We are essentially introducing a block overload of `Enumerable#to_a`. I  feel that the method name and type-signature point to map-like behaviour, especially given that `to_h` with a block overload exists.

`into` is a good analogy but I think it's a more generic concept that could be like extending something like the below to accept a transformation. Maybe I'm missing the point.

```crystal
tuple = {1, 1, 2, 3, 4}
set = Set{*tuple}
```

Or rather something like this could be more along the lines of what @straight-shoota proposed.
Forgive the pseudocode sketch...

```crystal
module Appendable(T)
  abstract def <<(element : T) : self
  
  def self.from(iterator : Iterator(T), & : T -> U) : Appendable(U)
    ...
  end 
end

struct Set(T)
 include Appendable(T)
end

Set.from("string".each_char, &.downcase)
```

**Comment by HertzDevil** [comment]
`#into` allows the user to provide a pre-allocated container with a non-default capacity. Not sure how common that usage is.
