### ISSUE TITLE
Windows release crystal-1.6.1-windows-x86_64-msvc-unsupported.zip is corrupted

### ISSUE THREAD

**Issue by oprypin** [crystal-lang/crystal#12657]
> crystal-1.6.1-windows-x86_64-msvc-unsupported.zip

> 9 Bytes

> 3 days ago 

https://github.com/crystal-lang/crystal/releases/tag/1.6.1

**Comment by straight-shoota** [comment]
Doh 🤦 I shouldn't use `curl` to download artifacts from GitHub actions. And check file sizes after upload. And be suspicious when down- and upload are both almost instantaneous.

Fixed it.
