### ISSUE TITLE
Spec: Improve UX with order message

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#12660]
When using `crystal spec` with a random order, the spec runner prints the random seed in the spec output in order to allow to reproduce this specific ordering.

I think some aspects of how this is presented need improvement. I've based my suggestions on the behaviour of `rspec` which I think makes a lot of sense.

1. The order message is printed in between the final status and the extended failures and errors list. This makes it easy to miss it because the list can be quite long when there are many errors. It should be printed as last line in the output. If I want to repeat the run with the same seed, I need to know that a seed was used in the first place (and the seed value of course). This needs to be dead obvious.
2. The order message should also be printed at the top, before running any specs. This is to avoid losing the seed value in case the process crashes before reaching the end (I still want to be able to recreate the same order to be able to recreate the crash condition).
3. The order message only needs to show when a seed is implicitly generated. When the seed is already passed in as an argument (`--order=123456`) then it's clear that this seed is used from the program invokation.

The latter point (3.) may be debatable. Omitting the message means there's no positive feedback that the seed was actually used and the specs run in a randomized order based on that seed. Also the exact command arguments may not be easily visible when its invoked from some automated context which omits the command (I think this is mostly a deficiency of the command runner, though). `rspec` hides the message when invoked with a specific seed.

**Comment by asterite** [comment]
> The latter point (3.) may be debatable. Omitting the message means there's no positive feedback that the seed was actually used and the specs run in a randomized order based on that seed

This actually happened to me recently at work. For some reason the `--seed` I was giving to `rspec` wasn't being picked up. I can't remember why it was, but given that scenario, I think it's important to let the user know that the seed being used is the one that was told by them.
