### ISSUE TITLE
Remove octal and binary notation for floating point literals

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#12667]
As discovered in https://github.com/crystal-lang/crystal/issues/12662#issuecomment-1291771682, Crystal supports octal and binary notation for floating point literals. It only works for integer values, a decimal separator is not accepted. Hexadecimal notation is also unsupported because floating point type suffix is interpreted as hex digits (#12662).

```cr
0b11_f32 # => 3.0
0o11_f32 # => 9.0
0x11_f32 # => 73522 (Int32)
```

Notating floating point literals in power-of-two bases doesn't make much sense. For integers it is useful because it corresponds to the byte representation. But that's completely different for floats.

I'm proposing to remove support for that octal and binary notation. It's not even documented: [crystal-lang.org/reference/1.6/syntax_and_semantics/literals/floats.html](https://crystal-lang.org/reference/1.6/syntax_and_semantics/literals/floats.html)

I checked with Rust which uses the same literal syntax and it does not accept octal and binary notation for floating point numbers. 
```rs
println!("{}", 0b11_f32); // error: binary float literal is not supported
println!("{}", 0o11_f32); // error: octal float literal is not supported
```

**Comment by BlobCodes** [comment]
This results in a syntax error in pre-v1.3.0.
Probably a bug introduced in #11211.
