### ISSUE TITLE
Compiler:spec mixed two spec cases for classes with a similar signature

### ISSUE THREAD

**Issue by yamada-masahiro** [crystal-lang/crystal#12666]
### Summary ###

I wrote two spec files and ran them one by one then I got no failures.
However, when I ran them at a time, I got a failure.
The message showed that the test runner set a test to the other.

### How to reproduce the bug ###

I have put reproducible codes on [GutHub](https://github.com/yamada-masahiro/crystal_name_space.git).
You can clone the repo to your PC, and do `crystal spec`.
For a detail, read its [Usage](https://github.com/yamada-masahiro/crystal_name_space#usage).

### Expected result ###

I expected to get no failures when I ran the two independent tests, 'foo' and 'bar', at a time.

### Actual result ###

I got a 'bar' test failure in the 'foo' test.

#### Compiler ####

Crystal 1.6.1 (2022-10-21)
LLVM: 14.0.6
Default target: aarch64-apple-darwin21.6.0

#### OS ####

ProductName:	macOS
ProductVersion:	12.6
BuildVersion:	21G115

## Workaround ##

Don't write `include Foo` nor `include Bar` in your code, and use fully-qualified identifiers like `Foo::Baz`.

**Comment by straight-shoota** [comment]
This is not a bug. You include two modules into a namespace and each of them contains a constant `Baz` which collide when included together. The compiler just chooses one of them.

Reduced:
```cr
module Foo::Baz
end
module Bar::Baz
end

include Foo
include Bar

Baz # => Bar::Baz
```

Including modules into the top-level namespace is a delicate measure. It should be used sparsely and with awareness for avoiding name collisions.

A useful feature for this use case would probably be file-local includes (#11979).

**Comment by straight-shoota** [comment]
To avoid writing fully qualified names, you could put the specs into the respective namespace.
```cr
module Foo::Baz
end
module Bar::Baz
end

module Foo
  describe Baz do
  end
end

module Bar
  describe Baz do
  end
end
```

**Comment by yamada-masahiro** [comment]
@straight-shoota Thank you for your explanation.
Do you mean below:
1. `crystal spec` concatenates all spec files, so plural `include` statements appear at the same level?
2. when plural modules have a class with the same name, they are included at the same level and the method is called without any qualifications, the compiler chooses one of the classes?

You brought #11979 here, but I can't understand the top-level matters.

**Comment by straight-shoota** [comment]
1. Yes, `crystal spec` concatenates all spec files. It's equivalent to building a file with `require "spec/**"`. The top-level namespace is shared between all source files.
2. Exactly. That's what the example in https://github.com/crystal-lang/crystal/issues/12666#issuecomment-1291758173 demonstrates.

**Comment by yamada-masahiro** [comment]
I appreciate your explanations, solutions, and kindness. I hope I understand what you said.
