### ISSUE TITLE
Add `Object#not_in?`

### ISSUE THREAD

**Issue by caspiano** [crystal-lang/crystal#12697]
## Feature Request

**Is your feature request related to a problem? Please describe clearly and concisely what is it**

It is possible to check the membership of an object in a collection via `Object#in?` 

```crystal
# This is neat
if foo.in?(1..100)
   # Do thing
end

# And this neat
unless foo.in?(1..100)
   # Do thing
 end
 
 # This is less so
 if some_condition && !foo.in?(1..100)
   # Do thing
 end
 
 # In this case, having the negation closer to the membership check would subjectively read better
 !Some
  .long_and_complicated
  .multiple_method
  .chained_call
  .in?(some_collection)
 ```

**Describe the feature you would like, optionally illustrated by examples, and how it will solve the above problem.**

Add `Object#not_in?(collection)`
This will make checking for non-membership of a collection read slightly nicer and chain better.

**Describe considered alternative solutions, and the reasons why you have not proposed them as a solution here.**

One can simply negate an `Object#in?(collection)` call.

---
As this is just a syntactic overload and Crystal strives for orthogonality, if there's no clear decision in a few days on this, I'll close out the issue.

**Comment by caspiano** [comment]
Closing due to lack of interest (from me, and others)

**Comment by straight-shoota** [comment]
As a note, it's possible to call `Bool#!` with regular method syntax which would remove the distance between predicate method and negation.
```cr
Some
  .long_and_complicated
  .multiple_method
  .chained_call
  .in?(some_collection)
  .!
```

**Comment by caspiano** [comment]
I've never been a fan of that syntax, and having a hypothetical `Bool#not` doesn't read that much better
