### ISSUE TITLE
Spec Expectations rename start_with to starts_with and end_with  ends_with?

### ISSUE THREAD

**Issue by zw963** [crystal-lang/crystal#12707]
I am not a native English speaker. why not both use same form?

as you see in following document search, only `Spec::Expectations` use `end_with`, all others use `ends_with`.

[#end_with(expected)](file:///home/zw963/Crystal/docs/Spec/Expectations.html#end_with(expected)-instance-method)
Spec::Expectations

----------------------------------

[#ends_with?(other : StringLiteral | CharLiteral) : BoolLiteral](file:///home/zw963/Crystal/docs/Crystal/Macros/MacroId.html#ends_with?(other:StringLiteral|CharLiteral):BoolLiteral-instance-method)
Crystal::Macros::MacroId
Similar to String#ends_with?.

[#ends_with?(other : StringLiteral | CharLiteral) : BoolLiteral](file:///home/zw963/Crystal/docs/Crystal/Macros/StringLiteral.html#ends_with?(other:StringLiteral|CharLiteral):BoolLiteral-instance-method)
Crystal::Macros::StringLiteral
Similar to String#ends_with?.

[#ends_with?(other : StringLiteral | CharLiteral) : BoolLiteral](file:///home/zw963/Crystal/docs/Crystal/Macros/SymbolLiteral.html#ends_with?(other:StringLiteral|CharLiteral):BoolLiteral-instance-method)
Crystal::Macros::SymbolLiteral
Similar to String#ends_with?.

[#ends_with?(str : String) : Bool](file:///home/zw963/Crystal/docs/String.html#ends_with?(str:String):Bool-instance-method)
String
Returns true if this string ends with the given str.

[#ends_with?(char : Char) : Bool](file:///home/zw963/Crystal/docs/String.html#ends_with?(char:Char):Bool-instance-method)
String
Returns true if this string ends with the given char.

[#ends_with?(re : Regex) : Bool](file:///home/zw963/Crystal/docs/String.html#ends_with?(re:Regex):Bool-instance-method)
String
Returns true if the regular expression re matches at the end of this string.

**Comment by straight-shoota** [comment]
The reason for this is that an expectation expression reads like a sentence: `a.should start_with e`.

**Comment by zw963** [comment]
> The reason for this is that an expectation expression reads like a sentence: `a.should start_with e`.

I gave all my English grammar course back to the teacher.

I guess the added `s` is must be intentional, because this changes mention in the `for Rubyist Wiki`.

```
a.should start_with e
a.starts_with e
```

Both of them is expected, right?

Is it really important to make this distinction precisely for a programming language?

**Comment by straight-shoota** [comment]
Yes, it's expected and on purpose. In both cases, the code reads like a sentence.

**Comment by zw963** [comment]
Okay, if this is on purpose, close it.

Though, i really consider this is not good, only because English syntax reason, cause a `s` add or removed in the middle of a method.
