### ISSUE TITLE
Unexpected behavor for compiler transform  $0 = "hello" into a syntax error form

### ISSUE THREAD

**Issue by zw963** [crystal-lang/crystal#12711]
## Bug Report

Following code happen when i transform some code from Ruby to Crystal, auto format feature change code `$0 = "hello"` to new syntax error form. `$~ []= "hello"`

```sh
 ╰─ $ cat 1.cr
"hello" =~ /(hel)lo/

$0 = "hello"

 ╰─ $ cr run 1.cr 
Showing last frame. Use --error-trace for full trace.

In 1.cr:3:1

 3 | $0 = "hello"
     ^
Error: undefined method '[]=' for Regex::MatchData

 ╰─ $ 1  cat 1.cr |cr tool format -
"hello" =~ /(hel)lo/

$~ []= "hello"
```

**Comment by zw963** [comment]
Linking #4776

**Comment by straight-shoota** [comment]
I think this would actually be a parser error. An assignment to numbered variables such as `$0` should not parse.

**Comment by zw963** [comment]
Tested, Fixed, Thanks.
