### ISSUE TITLE
Fiber-aware blocking `flock`

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#12721]
`FileDescriptor#flock_exclusive(blocking: true)` and `FileDescriptor#flock_shared(blocking: true)` are currently implemented on top of `flock(2)` with blocking semantics, i.e. when it doesn't succeed immediately, the function waits until the lock is attained. This blocks the entire thread which is undesired.

Instead, the blocking semantics can be implemented in a way that they are fiber aware, i.e. `flock(2)` is used in non-blocking mode and if it would block, we yield the fiber and try again next time. This repeats until the lock is attained and opens an opportunity for other fibers to execute in the meantime.

A basic implementation could look like this:

```cr
def flock_exclusive(file)
  op = LibC::FlockOp::EX | LibC::FlockOp::NB

  while true
    if 0 == LibC.flock(file.fd, op)
      yield
    else
      errno = Errno.value
      if errno == Errno::EWOULDBLOCK
        Fiber.yield
        next
      else
        raise IO::Error.from_os_error("Error applying or removing file lock", errno)
      end
    end
  end
end
```

This is very similar to the (non-blocking) [implementation of `getrandom`](https://github.com/crystal-lang/crystal/blob/d5e6362174260282c7a16df7dd46a23a8ac8c0ab/src/crystal/system/unix/getrandom.cr#L102-L114).

**Comment by jhass** [comment]
Makes me wonder if there should be support for a timeout in the blocking variants

**Comment by straight-shoota** [comment]
Yeah, I was wondering about this as well. It could be a useful enhancement.
