### ISSUE TITLE
Misleading error message when type is not match

### ISSUE THREAD

**Issue by zw963** [crystal-lang/crystal#12720]
Check following references.

https://forum.crystal-lang.org/t/misleading-error-message-when-type-is-not-match/5075

**Comment by zw963** [comment]
check [this](https://forum.crystal-lang.org/t/misleading-error-message-when-type-is-not-match/5075/18?u=zw963) replied by straight-shoota,  explain what I want exactly.

------------

So we have the def types

    String, Int32
    Int32, _

And the argument types are String, Int32?.

The options for changing the types to match are:

    change #1 from String to Int32
    change #2 from Int32? to Int32

Both can be valid suggestions and they involve the same amount of changes.

I think the suggestion to drop the Nil type from Int32? to Int32 is more likely to catch the intention. Not accounting for a value’s nilability is a common cause of error. Chances are high that that’s exactly the suggestion the user needs.

In general terms, restricting a union to a subset of its members is a smaller change and more likely to be helpful than changing one type into another unrelated type.
So I think the compiler error message could take this into consideration.

**Comment by jwoertink** [comment]
Just ran in to this on a Lucky app this morning on 1.6.0. For Lucky we have method overloads that are designed to raise a compile-time error if you call them to help catch errors and display our own custom error messages. Since those methods show up as potential overloads, Crystal will show the incorrect overload on an argument when a different argument type is wrong.

Example code:
```crystal
class SaveComment < Comment::SaveOperation
  needs title : String
end

title : String? = "Test"
SaveComment.create(params, title) do |_,_|
end

# this is wrong because it's the `title` arg that has the wrong type here, not the `params`
# Error: expected argument #1 to 'SaveComment.create' to be Hash(K, V), not Lucky::Params
```

**Comment by jwoertink** [comment]
@asterite yup! 

```
Error: expected argument 'title' to 'SaveComment.create' to be String, not (String | Nil)
```

**Comment by zw963** [comment]
Tested, it works.

```
 ╰─ $ cr version
Crystal 1.7.0-dev [7a04fdd0f] (2022-11-17)

LLVM: 14.0.6
Default target: x86_64-pc-linux-gnu
```
