### ISSUE TITLE
`Hash#select!(Enumerable)` can skip over elements in the argument

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#12736]
`Hash#select!(Enumerable)` is implemented as:

```crystal
class Hash(K, V)
  def select!(keys : Enumerable) : self
    each { |k, v| delete(k) unless keys.includes?(k) }
    self
  end
end
```

This calls `Enumerable#includes?`, which may consume the entire `Enumerable`, even though the elements of `keys` need to be checked for each element in `self`. The result is that some entries can be missing in the returned value:

```crystal
# finds 1, skipping over 2
# cannot find 2, skipping over 3
# cannot find 3
{1 => 'a', 2 => 'b', 3 => 'c'}.select!([2, 1, 3].each) # => {1 => 'a'}
```

This is inconsistent with `#select`, `#reject`, and `#reject!`.

**Comment by HertzDevil** [comment]
A quick search indicates `Crystal::ASTNode#unbind_from(Enumerable(ASTNode))` also has this issue, but it is internal to the compiler and thus can be easily promoted to `Indexable(ASTNode)`

**Comment by asterite** [comment]
I think the PR that introduced this should be reverted.

**Comment by caspiano** [comment]
This is not efficient at all but prevents the interface from breaking.
I propose we keep the `Enumerable` argument with an internal conversion to a set and keep an overload for `Array | Tuple` that preserves the original implementation.

```crystal
# Removes every element except the given ones.
#
# ```
# h1 = {"a" => 1, "b" => 2, "c" => 3, "d" => 4}.select!({"a", "c"})
# h2 = {"a" => 1, "b" => 2, "c" => 3, "d" => 4}.select!("a", "c")
# h3 = {"a" => 1, "b" => 2, "c" => 3, "d" => 4}.select!(["a", "c"])
# h4 = {"a" => 1, "b" => 2, "c" => 3, "d" => 4}.select!(Set{"a", "c"})
# h1 == h2 == h3 == h4 # => true
# h1                   # => {"a" => 1, "c" => 3}
# ```
def select!(keys : Enumerable) : self
  # Convert enumerable to a set to prevent exhaustion of elements
  key_set = keys.to_set
  each { |k, v| delete(k) unless k.in?(key_set) }
  self
end

# :ditto:
def select!(keys : Array | Tuple) : self
  each { |k, v| delete(k) unless k.in?(keys) }
  self
end
```

This would be a nice case to have a type for finite and stable collections #12092 👀

**Comment by asterite** [comment]
This issue is also interesting because it might be a bit unexpected that the Enumerable is exhausted. In my mind when you iterate an iterator over and over it should be rewinded. There was an issue for that but we never got to do it. If that were the case then we wouldn't need to change this method. But for now we can go with that solution.

**Comment by HertzDevil** [comment]
`Iterator` isn't the only single-pass `Enumerable` and rewinding is not universally possible. I think something like `Enumerable::Stable(T)` might have merits but if a method calls `#each` on an argument exactly once then there is no need to require that argument to be stable.

**Comment by asterite** [comment]
> rewinding is not universally possible

Right, but I don't think that's a good reason not to do it. I think maybe reading stuff from a socket or TTY might not be rewindable, but that's almost it.

**Comment by HertzDevil** [comment]
If `#rewind` exists, does the caller or the consuming method call it? It is a nice to have feature but I don't think that's the solution to `Enumerable` exhaustion. In fact I expect it to be that way when a more specific restriction is absent.

**Comment by asterite** [comment]
This is what I came up with in the past. I would love it if Crystal worked that way: https://github.com/crystal-lang/crystal/issues/8504#issuecomment-600858734

**Comment by asterite** [comment]
Obviously it would work like that for all iterators, without having to call ruby. The idea is that each with block rewind the internal Iterator. Actually it could dup the original Iterator so it could work well too in nested blocks.

**Comment by HertzDevil** [comment]
It only works for `Iterator`, not other `Enumerable` types in general. Also something as simple as `x = 0; Iterator.of { x += 1 }` will not work.

**Comment by asterite** [comment]
Exactly, it uses includes, which rely on each. It would work fine.

I think I have an idea of how to implement this. It doesn't matter that in some cases it doesn't work well, like with Iterator.of

**Comment by HertzDevil** [comment]
It definitely matters, it just replaces one set of surprising behavior with another set. And I would argue this makes things even more confusing because the iterator types we use are private and it is unclear which of them have a working `#rewind` and which do not.

**Comment by asterite** [comment]
It seems I went through this before: https://github.com/crystal-lang/crystal/pull/10089

We were really close to merging that! But we didn't because the generic `dup` implementation was cloning too much. But if we require `Iterator` to provide `clone` and `rewind` (or not require it, but use them when available) then it'll be really intuitive and predictable, like in Ruby.

I really think we should revive that PR in some form.

Then for example the issue here wouldn't be an issue at all, because `includes?` will call `each` which will always iterate from the beginning.

**Comment by HertzDevil** [comment]
The actual implementation of `Enumerator#each(&)` seems to be much simpler; it just calls `#each(&)` of the wrapped object, so if someone does `it = [1, 2, 3].each; it.next; it.each {}` then the `each` goes through all elements without caring `it`'s own state. The exception is if there isn't a wrapped object like `x = 0; Enumerator.produce { x += 1 }`.

IMO that is the opposite of intuitive, even in Ruby. An `Iterator` represents an iteration state. It should be part of its contract that `#each` always yields the same elements as successive calls of `#next`. Anything else violates that contract and defies expectation.

A stable `Enumerable` on the other hand should not maintain iteration state. `Dir#@dir` is being used as an iteration state. To make it stable, what we should do is duplicate that member instead whenever we call `#each(&)` or `#each`. Then we don't need `Dir#read` and `Dir#rewind` either, because they only apply to an iteration state, which there would be none in `Dir` itself anymore.

**Comment by asterite** [comment]
@HertzDevil What would you expect this to output?

```crystal
a = [1, 2, 3].each
b = a.select(&.odd?)

a.each do |x|
  puts x
end

b.each do |x|
  puts x
end
```

My personal opinion: the way I think about composing iterators is that they represent a query to perform. This would be similar to Rails' ActiveRecord queries. For example in Rails you can do this:

```ruby
all_users = User.all
users_with_some_email = all_users.where(email: "...")
above_users_but_adults = users_with_some_email.where(adult: true)
```

Consuming the contents of `all_users` shouldn't affect consuming the contents of `users_with_some_email`. In Rails these aren't iterators, but the concept is the same: a kind of "query" to execute on some data.

Now, there's no `next` in Rails for this. These aren't enumerables. But it's fine! In Crystal `next` is a low-level primitive to implement everything else. Is the single method that makes iterators work. In practice, unless you need to traverse two iterators at the same time (zip) then you will never use `next`. Furthermore, it's very rare to have to combine `next` with any of the other methods (`each`, `to_a`, `select`, etc.)

So in my mind the above Crystal could should work like in Ruby.

**Comment by HertzDevil** [comment]
I would expect `a.each` to print everything and `b.each` to print nothing, because this is what it is: `[1, 2, 3].each` represents a single iteration pass. To request another iteration you call `#each` on the original array again. This is the elegance of `Iterator`.

Types can keep the `Enumerator` kind of guarantees in Crystal if they don't return an `Iterator`. And those enumerators probably wouldn't have `#next`, either.

**Comment by asterite** [comment]
> I would expect a.each to print everything and b.each to print nothing, because this is what it is: [1, 2, 3].each represents a single iteration pass.

It represents a single iteration pass... right now, because we couldn't implement it better.

Imagine `.each` didn't exist in Crystal and we'd like to introduce it. Which behavior you would like to have in Crystal? I would personally like it to behave the same as in Ruby.

**Comment by HertzDevil** [comment]
Thw way we already have right now, rather than Ruby's.

**Comment by asterite** [comment]
> which can be iterated over and over again, but each iteration sequence needs to be self-contained and makes #next weird

Right, well, in Ruby the same object represents the two things at the same time. This is very convenient because if you want to go one by one, you can do it. If you want to sub-filter or consume everything, you can do it too! Ruby for the win!

**Comment by HertzDevil** [comment]
Expect when it doesn't, because there is no way to tell whether a `#rewind` call will succeed.

**Comment by HertzDevil** [comment]
That's within the types we know in the standard library only. Nothing prevents people from writing non-rewindable `Iterator`s outside, and nothing _should_ prevent people.

**Comment by asterite** [comment]
Well, let's compare the situations:
- Now: no iterators can be rewinded, you can't compose iterators without one iterator affecting others, etc.
- A possible future: most iterators can be rewinded (if someone adds a new iterator in a shard and it can be rewinind, I'm sure someone will send a PR to improve that), you can compose most iterators without one affecting others, etc.

Which one do you all prefer?

(I prefer pragmatism over perfection)

**Comment by HertzDevil** [comment]
There is a more primitive operation than `#rewind` that is also worth considering:

```crystal
module Iterator::Bidi(T)
  include Iterator(T)

  abstract def prev : T | Iterator::Stop

  # default impl
  def rewind
    until prev.is_a?(Iterator::Stop)
    end
  end
end
```

If we also add some notion of a "current" element then we arrive at Java-style iterators.

**Comment by caspiano** [comment]
My first thought when I read `Bidi` 😆 

![image](https://user-images.githubusercontent.com/18466497/202238359-ffb443a3-c90c-49f3-bbb3-b491a439c6ba.png)
