### ISSUE TITLE
Can crystal lang implement the APE binary format?

### ISSUE THREAD

**Issue by syalon** [crystal-lang/crystal#12753]
Can crystal lang use https://github.com/jart/cosmopolitan  c lib to achieve static link for cross-platform?

**Comment by straight-shoota** [comment]
Probably yes. Just need bindings for it.

I think this kind of question is better suited for https://forum.crystal-lang.org/
An issue can be created when there is some concrete actionable item.

**Comment by straight-shoota** [comment]
Continuing in https://forum.crystal-lang.org/t/cosmopolitan-libc/5218/2
