### ISSUE TITLE
`break` (inside `while`) accepts a value, but does nothing with it

### ISSUE THREAD

**Issue by oprypin** [crystal-lang/crystal#1277]
``` crystal
x = while true
  break ":)"
end
p x
```

```
$ ruby test.cr
":)"
$ crystal test.cr
nil
```

I'm not a Ruby programmer, but my expectations matched with Ruby's behavior.

If it's decided that the `while` loop shouldn't have a return value in this case, then `break` should not allow arguments.

**Comment by asterite** [comment]
Oh, I had no idea that the `break` inside a `while` gave it it's value. I always though it was `nil`.

I guess we can do this, but unless the condition is `true` and you `break` unconditionally, `x` will also get the type `Nil` (I think)

**Comment by yxhuvud** [comment]
> I guess we can do this, but unless the condition is true and you break unconditionally, x will also get the type Nil (I think)

You could let it return the last statement inside the loop. Does that have any downside?

**Comment by david50407** [comment]
@yxhuvud default behavior with resulting `nil` is good for now, if we want to break with last value we can do

```
while x
  break something
end
```

it's more clearly than 

```
while x
  something
  break # no notice for returning the 'something'
end
```
