### ISSUE TITLE
Ubuntu 22.04 support

### ISSUE THREAD

**Issue by dmamchyts** [crystal-lang/crystal#12793]
# lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

curl -fsSL https://crystal-lang.org/install.sh | bash -s -- --channel=nightly

```
E: The repository 'http://download.opensuse.org/repositories/devel:languages:crystal:nightly/xUbuntu_22.04  Release' does not have a Release file.
```

**Comment by straight-shoota** [comment]
Argh, repositories need to be enabled for `devel:languages:crystal:nightly` separately. So we were missing a couple there (which are available for the stable project `devel:languages:crystal`).

I added the missing repositories and the packages should be available within a couple of minutes.
