### ISSUE TITLE
Interpreter : command literal hangs

### ISSUE THREAD

**Issue by hutou** [crystal-lang/crystal#12821]
Literal commands, either  `%x` or backticks hang in interpreter, for example:
`%x(tput lines)`

**Comment by asterite** [comment]
This is essentially https://github.com/crystal-lang/crystal/issues/12241

**Comment by Blacksmoke16** [comment]
Duplicate of #12241

**Comment by ysbaddaden** [comment]
For anyone wondering, this is caused by the SIGCHLD signal being received and handled by the crystal executable but not being "forwarded" to the interpreted code in the VM, which ends up  waiting forever.
