### ISSUE TITLE
Weird attribute assignment syntax

### ISSUE THREAD

**Issue by FnControlOption** [crystal-lang/crystal#12830]
In Ruby, the following code is invalid:

```rb
a = [:foo] * 3
a[0] = :bar
a.[](1) = :baz # syntax error
```

However, this works fine (by accident?) in Crystal, where `a.[](1) = :baz` is the same as `a.[]=(1, :baz)` (or `a[1] = :baz`)

[`Parser#can_be_assigned?`](https://github.com/crystal-lang/crystal/blob/a37e97d/src/compiler/crystal/syntax/parser.cr#L6065-L6074) probably should check if `Call#has_parentheses` is `false` when `Call#name` is `"[]"`

Here's my `crystal -v`:

> Crystal 1.6.2 (2022-11-03)
> 
> LLVM: 14.0.6
> Default target: x86_64-apple-macosx

**Comment by straight-shoota** [comment]
`a.[](1) = :baz` and `a.[] 1 = :baz` should be invalid. The combination of standard call syntax with an operator method name and assignment is confusing.

Note that `a.[]=(1, :baz)` should continue to work, though.

**Comment by FnControlOption** [comment]
#14527 seems to have made `a.[](1) = :baz` into a syntax error.

All that's left now before this issue can be closed is `a.[] 1 = :baz`
