### ISSUE TITLE
[RFC] named fibers

### ISSUE THREAD

**Issue by technorama** [crystal-lang/crystal#1284]
Debugging Fibre/Scheduler issues is very hard when you only have a hex address to go off.

Proposed API:
```
Fiber.new name: "foo"
spawn(name: "bar") { }
```

name will show up in inspect if provided

**Comment by asterite** [comment]
This was very easy to do with optional named arguments. The name must be passed as a named argument. It works like this:

```cr
spawn(name: "sub") do
  p Fiber.current
end
p Fiber.current
Fiber.yield
```

Output:

```
#<Fiber:0x10d4d9f50: main>
#<Fiber:0x10d4d9e00: sub>
```
