### ISSUE TITLE
Updating the syntax of regex literals

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#12857]
While working on PCRE2 support (#12790), I noticed there's a complexity with the compiler: An upgrade of the regex engine also affects regex literals, which has an effect on the syntax of Crystal.

The syntax for PCRE and PCRE2 is almost identical. The vast majority of regular expressions will just work with either engine. But there are some minor differences (see this SO answer for a compilation of some differences: https://stackoverflow.com/a/73767663/7401689).

Crystal's regex literals are defined to use the PCRE syntax (https://crystal-lang.org/reference/1.6/syntax_and_semantics/literals/regex.html). The compiler even validates that by compiling the expression at compile time. It uses the regex engine that the compiler is linked against for that.

That means, expressions that are valid in PCRE2, but not PCRE, would be considered invalid according to the language specification and the compiler would error when it uses PCRE itself. But a compiler using PCRE2 would not error on the same regex literal.

This is not immediately causing trouble. We don't need to change the language definition and can make sure the compiler is always linked against PCRE. This would prevent any breaking changes in the language.
If you want to use regex syntax that's specific to PCRE2, you can't use a regex literal for that. This shouldn't be much of a problem as there's the `Regex.new` alternative where the expression is not validated by the compiler and only depends on the regex engine used at runtime.

But it's going to be hard to enforce the compiler uses PCRE when support for that library is going away more and more.
So at some point we'll have to do something about it.

**Comment by beta-ziliani** [comment]
PHP when from PCRE to PCRE2 in a [minor](https://php.watch/versions/7.3/pcre2) (from 7.2 to 7.3). I think we should follow suit. I mean, PCRE is at EOL and there's no way around it. I suggest we move fast and make PCRE2 for 1.8 or _at most_ 1.9. The steps should be:
 * Warn users of the change and its impact.
 * Make PCRE2 selected by default instead of opt-in in user code. This will help spot issues in user's regex.
 * Start distributing nightlies with PCRE2 linked. This will help spot issues with program's regex.

**Comment by bcardiff** [comment]
Sounds good to me aim for 1.8 with PCRE2. Maybe keeping for that version a fallback to PCRE, although making the regex literals supported match PCRE2 only.

In 1.9 we can drop PCRE support entirely.

It would be worth making a post (forum or blog) specific about this transition and to recall that PCRE2 can be tested in 1.7 already with `-Duse_pcre2`.

**Comment by straight-shoota** [comment]
> although making the regex literals supported match PCRE2 only.

I think that might be a problem when PCRE2 syntax is more strict than PCRE. So while you could opt into using PCRE at runtime, complex regex literals could be considered invalid by the compiler.

So it might be better to keep PCRE syntax in the compiler for now.

This would be the roadmap:

* 1.8 enable PCRE2 by default at runtime, but allow fallback to PCRE with `-Duse_pcre`
* 1.9 build the compiler with PCRE2, switching regex literal syntax. Still allow fallback to PCRE with `-Duse_pcre` at runtime. If the compiler encounters an invalid regex literal (for PCRE2) it should error and inform about the engine update being a possible cause. With flag `-Duse_pcre`, the compiler could ignore such errors and only print a warning.
* 1.10+ Remove support for PCRE

**Comment by bcardiff** [comment]
I'm happy with your proposed roadmap @straight-shoota. I'm just comfortable enough with merging 1.8 and 1.9 of your proposal and accepting only a subset of the regex we do today, since a workaround is already available.

**Comment by beta-ziliani** [comment]
Some heads up: we are planning to move to PCRE2 before 1.8 ([WIP post](https://github.com/crystal-lang/crystal-website/compare/master...beta-ziliani:crystal-website:post/pcre2)). That is, we will merge the first to items above, making the compiler and stdlib work with PCRE2 by default.

**Comment by straight-shoota** [comment]
With https://github.com/crystal-lang/crystal/pull/13084 we're switching the compiler to use PCRE2 and there's a correspondent PR to update the distribution packages: https://github.com/crystal-lang/distribution-scripts/pull/224

The plan is that from 1.8.0 on the Crystal compiler will link `libpcre2` and thus the regex literal syntax will be only PCRE2 compatible.

Compiler builds of 1.8+ should not be linked against `libpcre` to ensure consistency in the language.

**Comment by straight-shoota** [comment]
Current nightly builds are shipping with PCRE2 for both stdlib and compiler 🚀 

Let's hope for a smooth transition in Crystal projects 🤞

Instructions on the migration process: [crystal-lang.org/2023/03/02/crystal-is-upgrading-its-regex-engine](https://crystal-lang.org/2023/03/02/crystal-is-upgrading-its-regex-engine/)
