### ISSUE TITLE
space required before colon in type restriction false positive

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#12868]
https://github.com/crystal-lang/crystal/pull/12740 introduced a false positive that causes a warning to be produced on untyped yielding methods with `&`:

```cr
def test(&)
end

test do
  puts "hi"
end
```

```sh
$ ccrystal tool format --check test.cr 
Using compiled compiler at .build/crystal
In ./test.cr:1:11

 1 | def test(&)
               ^
Warning: space required before colon in type restriction (run `crystal tool format` to fix this)

A total of 1 warnings were found.
```

No changes are made to the file when running the formatter either.

Discovered in Athena nightly CI within pretty much every component: https://github.com/athena-framework/athena/actions/runs/3769289873/jobs/6408388844

**Comment by straight-shoota** [comment]
Oh, that's odd. This variant should be covered by specs. : thinking:
