### ISSUE TITLE
formatter indentation error when comment on the method args

### ISSUE THREAD

**Issue by zw963** [crystal-lang/crystal#12863]
## Bug Report

Following is a code example, it has two indentation error.

```crystal
      result = ControlClientReplyForStatusCommand.new(
        version: Procodile::VERSION,
        messages: @supervisor.messages,
        root: @supervisor.config.root,
      # app_name: @supervisor.config.app_name,  # 1. this comment line not indent with above line
)                                               # 2. ) not indent correct.
```

Check in following screenshot will more clearly.

![image](https://user-images.githubusercontent.com/549126/208804252-194b17cf-0a9f-4131-8fcd-3e93e45053ae.png)

**Comment by zw963** [comment]
Hi,  @straight-shoota , I found a new formatter issue which involves to comment on the lines, 
maybe can be fix in one PR, please check

Following code format correct.

```crystal
module Test1
  begin
    raise "Error"
  rescue e : Exception
    puts "Error!"
  end
end
```

But, if comment the rescue lines out, `end` indentation error, like this.

```crystal
module Test1
  begin
    raise "Error"
    # rescue e : Exception
    #   puts "Error!"
end
end
```

**Comment by straight-shoota** [comment]
Yeah, that should be a different issue because it's a different bug. I've created #12964 for tracking it.
