### ISSUE TITLE
multithreading might be broken on mac M1

### ISSUE THREAD

**Issue by elbywan** [crystal-lang/crystal#12872]
### Context

I am currently working on a multithreaded CLI tool on my personal computer (intel based macbook), but when trying the tool on my work laptop (apple silicon macbook) I noticed that there were severe issues unless I removed the MT flag.

```
❯ crystal --version
Crystal 1.6.2 (2022-11-03)

LLVM: 14.0.6
Default target: aarch64-apple-darwin21.6.0
```

### Issue

At some point when a program is compiled with `-Dpreview_mt` spawned fibers seem to end up hanging for no reason.

I made a small program to reproduce, it is supposed to decrement a counter in order and print each iteration and exit. 

```crystal
# file: test.cr
struct Decrement
  COUNTER = 2_000
  @@counter : Int32 = COUNTER
  @@mutex = Mutex.new

  def self.run
    COUNTER.times do
      spawn do
        @@mutex.synchronize do
          puts @@counter -= 1
        end
      end
    end
    sleep 5
  end
end

Decrement.run
```

Without `-Dpreview_mt` on an arm mac and with the flag on a non-arm mac, it will always end up printing…

```sh
❯ crystal run ./test.cr | tail -n 10
9
8
7
6
5
4
3
2
1
0
```

…but on my M1 mac the output never goes to the end:

```sh
❯ crystal run -Dpreview_mt ./test.cr | tail -n 10
13
12
11
10
9
8
7
6
5
4
```

I have unfortunately no idea where this issue comes from. I don't know if this is useful but when debugging the CLI program to check why it hangs all the worker threads are stuck somewhere in the kqueue stack:

<img width="905" alt="Screenshot 2022-12-27 at 10 35 13" src="https://user-images.githubusercontent.com/3428394/209645943-79672ccd-e72e-46b5-ad41-efcfdcab6c60.png">

**Comment by HertzDevil** [comment]
Can you confirm if #13050 fixes this? On my M2 I am getting 10 zeros out of 10 tries

**Comment by elbywan** [comment]
> Can you confirm if https://github.com/crystal-lang/crystal/pull/13050 fixes this?

@HertzDevil It does, monkey patching `class Crystal::SpinLock` fixes the issue on my end.

Many thanks! 🙇
