### ISSUE TITLE
Running simplest 'Hello World' program gives errors

### ISSUE THREAD

**Issue by knudvaneeden** [crystal-lang/crystal#12877]
## Bug Report

- Include Crystal compiler version (`crystal -v`) and OS. If possible, try to see if the bug still reproduces on master.
-c:\users\username\scoop\shims Thu 29-12-22 01:47:49>crystal -v
-Crystal 1.6.2 [879691b] (2022-11-03)
-LLVM: 13.0.0
-Default target: x86_64-pc-windows-msvc
-Microsoft Windows 10 Professional
-Microsoft Visual Studio 2022 Professional

-First time installation (never installed Crystal before)

-Followed the instructions here: 
https://crystal-lang.org/install/on_windows/
https://scoop.sh/

Here is the output of the installation:
---
PS C:\Users\username\AppData\Local> Set-ExecutionPolicy RemoteSigned -Scope CurrentUser # Optional: Needed to run a remote script the first time

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
you to the security risks described in the about_Execution_Policies help topic at
https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): y

PS C:\Users\username\AppData\Local> irm get.scoop.sh | iex
Initializing...
Downloading...
Extracting...
Creating shim...
Adding ~\scoop\shims to your path.
Scoop was installed successfully!
Type 'scoop help' for instructions.

PS C:\Users\username\AppData\Local> scoop bucket add crystal-preview https://github.com/neatorobito/scoop-crystal
Checking repo... OK
The crystal-preview bucket was added successfully.

PS C:\Users\username\AppData\Local> scoop install vs_2022_cpp_build_tools
Installing 'vs_2022_cpp_build_tools' (17.0) [64bit] from crystal-preview bucket
vs_BuildTools.exe (2.0 MB) [==================================================================================] 100%
Checking hash of vs_BuildTools.exe ... ok.
Running installer... done.
Linking ~\scoop\apps\vs_2022_cpp_build_tools\current => ~\scoop\apps\vs_2022_cpp_build_tools\17.0
'vs_2022_cpp_build_tools' (17.0) was installed successfully!

PS C:\Users\username\AppData\Local> scoop install crystal
Installing 'vswhere' (3.1.1) [64bit] from main bucket
3.1.1 (257.1 KB) [============================================================================================] 100%
Checking hash of 3.1.1 ... ok.
Extracting vswhere.zip ... done.
Linking ~\scoop\apps\vswhere\current => ~\scoop\apps\vswhere\3.1.1
Creating shim for 'vswhere'.
'vswhere' (3.1.1) was installed successfully!
Installing 'crystal' (1.6.2) [64bit] from crystal-preview bucket
crystal-1.6.2-windows-x86_64-msvc-unsupported.zip (33.9 MB) [=================================================] 100%
Checking hash of crystal-1.6.2-windows-x86_64-msvc-unsupported.zip ... ok.
Extracting crystal-1.6.2-windows-x86_64-msvc-unsupported.zip ... done.
Linking ~\scoop\apps\crystal\current => ~\scoop\apps\crystal\1.6.2
Creating shim for 'crystal'.
Creating shim for 'shards'.
Running post_install script...
'crystal' (1.6.2) was installed successfully!
---

-Then I did create a simplest program:

Puts "Hello World"

and saved it in an arbitrary filename ddd.cr

-Then I did run (in JPSoft tcc.exe and also tried in PowerShell, e.g. with full pathname 'crystal.exe c:\temp\ddd.cr', then copying it into the crystal.exe folder 'crystal.exe ddd.cr', then running it from PowerShell 'crystal ddd.cr', ... . But always the below errors.

crystal.exe ./ddd.cr

-It gave these errors:

PS C:\users\username\scoop\shims> crystal.exe ./ddd.cr

Error executing process: 'cl.exe /nologo _main.obj U-I-nt32.obj E-xception5858C-allS-tack.obj A-rray40S-tring41.obj P-ointer40S-tring41.obj I-nt32.obj F-loat64.obj I-nt64.obj A-rgumentE-rror.obj P-ointer40L-ibC-5858C-O-N-T-E-X-T-41.obj A-rray40P-ointer40V-oid4141.obj P-ointer40P-ointer40V-oid4141.obj E-N-V-.obj C-rystal5858S-ystem5858E-nv.obj S-tring.obj P-ointer40U-I-nt841.obj T-uple40S-tring4432S-tring4432S-tring41.obj E-numerable5858R-eflect40I-nt3241.obj G-C-.obj U-I-nt64.obj S-taticA-rray40U-I-nt16443225641.obj S-lice40T-41.obj S-lice40U-I-nt1641.obj W-inE-rror.obj S-lice40U-I-nt841.obj P-ointer40U-I-nt1641.obj I-ndexE-rror.obj C-har5858R-eader.obj E-xception.obj C-har.obj R-untimeE-rror.obj U-nicode.obj A-rray40T-uple40I-nt324432I-nt324432I-nt324141.obj S-tring5858B-uilder.obj M-ath.obj S-taticA-rray40U-I-nt84432441.obj S-taticA-rray40U-I-nt8443212941.obj D-ivisionB-yZ-eroE-rror.obj P-ointer40T-uple40I-nt324432I-nt324432I-nt324141.obj R-ange40B-4432E-41.obj R-ange40I-nt324432I-nt3241.obj B-ool.obj T-ypeC-astE-rror.obj P-rocess.obj F-ile.obj C-rystal5858S-ystem5858F-ile.obj F-ile5858E-rror.obj U-I-nt8.obj T-uple40S-tring4432S-tring4432S-tring4432S-tring41.obj E-rrno.obj F-ile5858N-otF-oundE-rror.obj F-ile5858A-lreadyE-xistsE-rror.obj F-ile5858A-ccessD-eniedE-rror.obj F-ile5858E-rror43.obj P-ath.obj P-ath5858K-ind.obj T-uple4042T-41.obj T-uple40I-nt3241.obj T-uple40I-nt324432I-nt3241.obj N-il.obj E-numerable5858E-mptyE-rror.obj T-uple40C-har41.obj T-uple40C-har4432C-har41.obj S-taticA-rray40I-nt8443225641.obj P-ointer40I-nt841.obj T-uple40C-har4432-809e6e92b20f8837d04aeb284952aba9.obj R-ange40C-har4432C-har41.obj T-uple40C-har4432-da0bae55c641cf3666f281b8fea01988.obj T-uple40S-tring4432S-tring41.obj C-rystal5858S-ystem.obj S-taticA-rray40U-I-nt8443251241.obj E-xception43.obj P-ointer40L-ibC-5-c47a0e048fdbf37e7b6d1e4778e5f8d3.obj D-ir.obj C-rystal5858S-ystem5858D-ir.obj U-nicode5858C-aseO-ptions.obj H-ash40I-nt324432-c36c7b59ada9577e04b34b7156d26117.obj P-ointer40H-ash58-df002967aa38240c2ffc8370480b96df.obj C-rystal5858H-asher.obj S-taticA-rray40U-I-nt644432241.obj P-ointer40U-I-nt6441.obj I-ntrinsics.obj H-ash5858E-ntry40-ea883736b6a497e8c0f2d29083b2162a.obj P-ointer40U-I-nt3241.obj A-rray40T-uple40I-nt324432I-nt324141.obj P-ointer40T-uple40I-nt324432I-nt324141.obj P-ath5858P-artI-terator.obj I-terator40T-41.obj I-terator5858S-top.obj S-taticA-rray40U-I-nt164432141.obj L-ibC-5858S-T-A-C-K-F-R-A-M-E-64.obj P-ointer40V-oid41.obj E-xception5858C-allS-tack5858R-epeatedF-rame.obj C-rystal5858A-tE-xitH-andlers.obj A-rray40P-roc40I--412183da1a81233e2c20c488cb2e890d.obj P-ointer40P-roc40-6252237c86bac28658266374d639ebc8.obj T-hread5858L-inke-203c55f1c4be503afabe353d210e31e7.obj T-hread5858M-utex.obj F-iber5858S-tackP-ool.obj D-eque40P-ointer40V-oid4141.obj D-eque40C-rystal5858E-vent41.obj P-ointer40C-rystal5858E-vent41.obj T-hread5858L-inkedL-ist40T-hread41.obj T-hread.obj A-tomic40U-I-nt841.obj F-iber.obj A-tomic40T-hread3212432N-il41.obj P-roc40N-il41.obj F-iber5858C-ontext.obj T-hread5858L-inkedL-ist40F-iber41.obj S-lice40U-I-nt6441.obj C-rystal5858S-ystem5858R-andom.obj I-nt128.obj U-I-nt128.obj I-O-5858F-ileD-escriptor.obj C-rystal5858S-ystem5858F-ileD-escriptor.obj A-tomic40T-41.obj A-tomic40I-nt3241.obj I-O-5858E-rror.obj F-ile5858I-nfo.obj L-ibC-5858B-Y-_H--6cfa1b255452e05129f70d8a5abeedfc.obj F-ile5858T-ype.obj N-otI-mplementedE-rror.obj I-O-5858F-ileD-escriptor43.obj T-ime5858S-pan.obj C-rystal5858S-cheduler.obj N-ilA-ssertionE-rror.obj C-rystal5858S-pinL-ock.obj D-eque40F-iber41.obj P-ointer40F-iber41.obj C-rystal5858E-ventL-oop.obj C-rystal5858E-vent.obj T-ime.obj C-rystal5858S-ystem5858T-ime.obj C-rystal5858S-ystem5858P-rocess.obj L-ibG-C-5858S-tackB-ase.obj S-taticA-rray40L--aa9c3495927510a36f0144adf6252906.obj P-ointer40L-ibC-5-a1f86dffb0160510ac15a075aa5b591a.obj B-ox40I-O-5858O-v-2232051b5dbe000225c59a6ca5d8444a.obj I-O-5858O-verlapp-c4a74ab6b0b5a3a9eab30c616cb39de6.obj I-O-5858O-verlapped5858O-verlappedO-peration.obj C-hannel5858T-imeoutA-ction.obj C-hannel5858S-electC-ontext40N-il41.obj C-hannel5858S-electC-ontextS-haredS-tate.obj A-tomic40C-hannel5858S-electS-tate41.obj C-rystal5858S-ystem5858F-iber.obj I-O-5858E-ncoder.obj C-rystal5858I-conv.obj S-taticA-rray40U-I-nt84432102441.obj T-ime5858L-ocatio-c92d7ae948ed8f4d38520c6d460d1469.obj T-ime5858L-ocation5858I-nvalidL-ocationN-ameE-rror.obj T-ime5858L-ocation5858I-nvalidT-Z-D-ataE-rror.obj T-ime5858F-ormat5858E-rror.obj T-ime5858F-loatingT-imeC-onversionE-rror.obj P-ath5858E-rror.obj F-ile5858B-adP-atternE-rror.obj C-hannel5858C-losedE-rror.obj B-ase645858E-rror.obj I-O-5858E-O-F-E-rror.obj I-O-5858T-imeoutE-rror.obj E-numerable5858N-otF-oundE-rror.obj O-verflowE-rror.obj K-eyE-rror.obj I-nvalidB-yteS-equenceE-rror.obj P-roc40F-iber4432-6eb246a0a45118d3c5507cc830b14a70.obj S-taticA-rray40U-I-nt6444321541.obj H-ash40T-uple40U-I-nt644432S-ymbol414432B-ool41.obj P-ointer40H-ash58-60a3eb55c544b99184778abc7dcee256.obj H-ash40U-I-nt644432U-I-nt6441.obj P-ointer40H-ash58-6ca1ab2004fcb02b740a9bf3b468352a.obj H-ash40S-tring443-d0ef6a484ca24b5e9e1cd150630d96a3.obj P-ointer40H-ash58-78e716075e5ec360a5549c235b8e9c11.obj C-rystal5858O-nceS-tate.obj A-rray40P-ointer40B-ool4141.obj P-ointer40P-ointer40B-ool4141.obj P-ointer40B-ool41.obj F-loat32.obj C-rystal.obj /FeC:\\Users\\username\\AppData\\Local\\crystal\\cache\\crystal-run-ddd.tmp.exe /link /DEBUG:FULL /PDBALTPATH:%_PDB% /INCREMENTAL:NO /STACK:0x800000 /LIBPATH:C:\\Users\\username\\scoop\\apps\\crystal\\current\\lib gc.lib /ENTRY:wmainCRTStartup libcmt.lib iconv.lib advapi32.lib Kernel32.lib shell32.lib ole32.lib WS2_32.lib kernel32.lib legacy_stdio_definitions.lib DbgHelp.lib libucrt.lib': The system cannot find the file specified. (File::NotFoundError)
  from C:\Users\username\scoop\apps\crystal\current\crystal.exe +280582 in '??'
  from C:\Users\username\scoop\apps\crystal\current\crystal.exe +280478 in '??'
  from C:\Users\username\scoop\apps\crystal\current\crystal.exe +280442 in '??'
  from C:\Users\username\scoop\apps\crystal\current\crystal.exe +8575 in '??'
  from C:\Users\username\scoop\apps\crystal\current\crystal.exe +2082175 in '??'
  from C:\Users\username\scoop\apps\crystal\current\crystal.exe +1301460 in '??'
  from C:\Users\username\scoop\apps\crystal\current\crystal.exe +1301181 in '??'
  from C:\Users\username\scoop\apps\crystal\current\crystal.exe +16594134 in '??'
  from C:\Users\username\scoop\apps\crystal\current\crystal.exe +16586247 in '??'
  from C:\Users\username\scoop\apps\crystal\current\crystal.exe +16604173 in '??'
  from C:\Users\username\scoop\apps\crystal\current\crystal.exe +19585749 in '??'
  from C:\Users\username\scoop\apps\crystal\current\crystal.exe +19548295 in '??'
  from C:\Users\username\scoop\apps\crystal\current\crystal.exe +19528343 in '??'
  from C:\Users\username\scoop\apps\crystal\current\crystal.exe +19526267 in '??'
  from C:\Users\username\scoop\apps\crystal\current\crystal.exe +19526202 in '??'
  from C:\Users\username\scoop\apps\crystal\current\crystal.exe +6646 in '??'
  from C:\Users\username\scoop\apps\crystal\current\crystal.exe +2174777 in '??'
  from C:\Users\username\scoop\apps\crystal\current\crystal.exe +2174554 in '??'
  from C:\Users\username\scoop\apps\crystal\current\crystal.exe +93817 in '??'
  from C:\Users\username\scoop\apps\crystal\current\crystal.exe +94099 in '??'
  from C:\Users\username\scoop\apps\crystal\current\crystal.exe +48329380 in '??'
  from C:\WINDOWS\System32\KERNEL32.DLL +95764 in 'BaseThreadInitThunk'
  from C:\WINDOWS\SYSTEM32\ntdll.dll +337569 in 'RtlUserThreadStart'

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues\

PS C:\users\username\scoop\shims>

**Comment by BlobCodes** [comment]
Could be a duplicate of #12839 
Please try the steps shown in this comment: https://github.com/crystal-lang/crystal/issues/12839#issuecomment-1350962196

**Comment by knudvaneeden** [comment]
1. checking installation of cl.exe ...

**Comment by BlobCodes** [comment]
If you just execute `cl.exe /help`, what is your output?
I think the linker is missing.

**Comment by knudvaneeden** [comment]
I have no cl.exe in my default Visual Studio 2022 directories. So as a next step now installing Windows 10 SDK 
https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/
I will also check with everything.exe to see which cl.exe are present further.

**Comment by knudvaneeden** [comment]
Note: But if I thus have to install additional programs (e.g. cl.exe) to resolve the issues. then it shows that following only the installation steps here is currently not enough.

-Followed the instructions here:
https://crystal-lang.org/install/on_windows/
https://scoop.sh/

**Comment by BlobCodes** [comment]
https://github.com/crystal-lang/crystal/issues/12839#issuecomment-1351130764

> if anyone has this problem; I installed MSVC v143 - VS 2022, C++ ATL build tools and Windows 10 SDK from Visual Studio.

I think you can try installing these tools, as shown in the comment.

**Comment by knudvaneeden** [comment]
Yes, first that 'Windows 10 SDK', I guess that should include cl.exe and might already be enough...

**Comment by knudvaneeden** [comment]
So the issue is not resolved at this moment.

**Comment by HertzDevil** [comment]
> Uninstalled Windows 10 SDK

Well did you install it back?

Also there should no need to override `%PATH%`; the executable is detected through `vswhere.exe`, and library search doesn't use `%PATH%`.

**Comment by straight-shoota** [comment]
The error is a `File::NotFoundError` which indicates that the executable `cl.exe` was not found.
If you say running `cl.exe` succeeds from the very same command prompt, that's very weird.

However, the fact that the compiler runs `cl.exe` is a hint that it was unable to detect the install location of the MSVC build tools and/or Windows 10 SDK. Otherwise it would look that up and use an absolute path for the linker command (such that it works even outside a developer command prompt).

> 2. checking this (from  the above error output): libucrt.lib': The system cannot find the file specified. (File::NotFoundError)

There is nothing wrong about `libcurt.lib`. That's just the last argument of the linker command.

**Comment by Blacksmoke16** [comment]
Fixed via #12899
