### ISSUE TITLE
Create a man page for 'crystal' binary

### ISSUE THREAD

**Issue by anatol** [crystal-lang/crystal#1291]
man pages is a standard UNIX way to document how tools work. It would be great if `crystal` had a man page as well.

**Comment by asterite** [comment]
Sure! If anyone wants to do it, please send a pull request :-)

**Comment by EvanHahn** [comment]
See PR #2147.

**Comment by jhass** [comment]
Looks like #2147 was abandoned, adoption highly appreciated.

```
git remote add upstream https://github.com/crystal-lang/crystal.git
git fetch upstream master
git fetch upstream refs/pull/2147/head
git checkout -b manpage FETCH_HEAD
git rebase -i upstream/master # Squash stuff together
# Fix issues mentioned in #2147
# Update for things that changed since
```

**Comment by dread-uo** [comment]
Hm... I guess I'll take this. :smiley:

**Comment by asterite** [comment]
Just a small question: what's the benefit of a man page in comparison to `crystal --help`?

**Comment by jhass** [comment]
People look for it to find help and you can be a lot more verbose since `man` calls a pager by default. It's just good practice to have one.

**Comment by ysbaddaden** [comment]
Check this:
- `git --help`: quick usage reference;
- `man git`: full reference with all sub-commands, constants, lots of details for each argument, and more.

**Comment by miketheman** [comment]
#triage Re-tag as `community:in-progress` as there's [an open PR that's waiting](https://github.com/crystal-lang/crystal/pull/2989) for someone to review, provide feedback.

**Comment by straight-shoota** [comment]
The man page is in the repo, but it seems not to be bundled in the Ubuntu package at least as it is not accessible in `/usr/share/man/man1`.

**Comment by Sija** [comment]
Same on Debian:
```
➜ man crystal
No manual entry for crystal
See 'man 7 undocumented' for help when manual pages are not available.
```

**Comment by mverzilli** [comment]
Reopening this because otherwise there are super high chances that we won't go the last mile.

**Comment by faustinoaq** [comment]
Same on Manjaro Linux:

```
>>> man crystal
No manual entry for crystal
>>> crystal -v
Crystal 0.23.0 (2017-07-13) LLVM 4.0.1
```

**Comment by asterite** [comment]
Closed in favor of https://github.com/crystal-lang/omnibus-crystal/issues/21
