### ISSUE TITLE
Crystal Play not working with crystal 1.7 debian package

### ISSUE THREAD

**Issue by stakach** [crystal-lang/crystal#12947]
seeing this error
<img width="639" alt="image" src="https://user-images.githubusercontent.com/368013/212265304-1cd29495-533c-40db-b1e9-ef1c31a81eae.png">

**Comment by straight-shoota** [comment]
Doh. That path is hardcoded at compile time.

This is a regression introduced in https://github.com/crystal-lang/crystal/pull/12686

https://github.com/crystal-lang/crystal/commit/1d431cd33ece2b241eb4180155effe9c834dbb9a#diff-0c7a41885f6191fd6ecbee4c64bc65e65938bfc0caaad43fb19f328941fdd95fR452
