### ISSUE TITLE
Multi-threading regression from 1.6.2 to 1.7.0

### ISSUE THREAD

**Issue by jzakiya** [crystal-lang/crystal#12943]
Using this code as a test app to show the regression:

https://gist.github.com/jzakiya/2b65b609f091dcbb6f792f16c63a8ac4

there's a significant performance decline from 1.6.2 to 1.7.0.

$ CRYSTAL_WORKERS=16 ./twinprimes_ssoz  input

Inputs      |   1.6.2   |   1.7.0
------------|-----------|----------
1000000000  |    12.6   |    15.1
------------|-----------|----------
5000000000  |    70.6   |    80.3
------------|-----------|----------
10000000000 |   162.1   |   180.9
-----------------------------------

However, when using a BitArray in `twins_sieve` here

https://gist.github.com/jzakiya/806cddb0dc5967d567bcb47f89d58e60

I get these results, with 1.7.0 still slower, but much closer.

$ CRYSTAL_WORKERS=16 ./twinprimes_ssozbary input

Inputs n    |   1.6.2   |   1.7.0
------------|-----------|----------
1000000000  |    13.9   |    14.1
------------|-----------|----------
5000000000  |    79.2   |    79.6
------------|-----------|----------
10000000000 |   184.9   |   189.2
-----------------------------------

It seems using different memory models inside the threads lead to very different results.

**Comment by straight-shoota** [comment]
@jzakiya I tried to reproduce the measurements and the absolute numbers are orders of magnitude different from the ones you posted. So just to confirm I'm doing the right steps:

```console
$ curl -L https://gist.githubusercontent.com/jzakiya/2b65b609f091dcbb6f792f16c63a
8ac4/raw/0d09a52b5934d01d3eb5b15bef49edf2876e1317/twinprimes_ssoz.cr > twinprimes_ssoz.cr
$ crystal build twinprimes_ssoz.cr -Dpreview_mt -o twinprimes_ssoz1.7.0mt
$ CRYSTAL_WORKERS=16 ./twinprimes_ssoz1.7.0mt 10000000000
threads = 16
using Prime Generator parameters for P11
segment size = 262144 resgroups for seg bitarray
twinprime candidates = 584415675; resgroups = 4329005
each of 135 threads has nextp[2 x 9587] array
setup time = 0.001414 secs
perform twinprimes ssoz sieve
135 of 135 twinpairs done
sieve time = 8.584426 secs
total time = 8.58584 secs
last segment = 134701 resgroups; segment slices = 17
total twins = 27412679; last twin = 9999999702+/-1
```

I figure the 8.58584 sec would correspond to the 180.9 sec for the biggest input in your table?

The difference could be caused by pure CPU performance but it's a lot (and I'm running an i7-11800H, not a beefy overclocked monster processor). My fear is that I might be missing something.

**Comment by straight-shoota** [comment]
Hah, I forgot `--release` 🤦 Was late last night...

So the numbers in your table... what unit do they represent? Miliseconds?

**Comment by jzakiya** [comment]
All the times are in seconds, as shown.  So 0.162228 secs is 162.228 milisecs, etc.
All the times I show were generated when my cpu was run in turbo mode, i.e. up to 4.6GHz, which was about 4.2GHz per thread.

I've been too busy to write smaller code to isolate just the threading issue from the total source code,.
But the routine `twins_sieve` is the ones `spawned` to perform in parallel.
It uses a regular `mem array` for the segment array `seg` in the routine.  Could that be a `Slice` issues?
The other version uses a `bitarray`.  Other than those differences, the rest of the code is the same.

I've also detected an issue with the `mem array` version, that for inputs > 5_000_000_000_000 it produces wrong results, while the `bitarray` results are correct (though slower).

```
def twins_sieve(r_hi, kmin, kmax, ks, start_num, end_num, modpg, primes, resinvrs)
  # Perform in thread the ssoz for given twinpair residues for kmax resgroups.
  # First create|init 'nextp' array of 1st prime mults for given twinpair,
  # stored consequtively in 'nextp', and init seg array for ks resgroups.
  # For sieve, mark resgroup bits to '1' if either twinpair restrack is nonprime
  # for primes mults resgroups, and update 'nextp' restrack slices acccordingly.
  # Return the last twinprime|sum for the range for this twinpair residues.
  s = 6                                                # shift value for 64 bits
  bmask = (1 << s) - 1                                 # bitmask val for 64 bits
  sum, ki, kn  = 0_u64, kmin-1, ks                     # init these parameters
  hi_tp, k_max = 0_u64, kmax                           # max twinprime|resgroup
  seg = Slice(UInt64).new(((ks - 1) >> s) + 1)         # seg array of ks resgroups
  ki    += 1 if r_hi - 2 < (start_num - 2) % modpg + 2 # ensure lo tp in range
  k_max -= 1 if r_hi > (end_num - 2) % modpg + 2       # ensure hi tp in range
  nextp = nextp_init(r_hi, ki, modpg, primes,resinvrs) # init nextp array
  while ki < k_max                       # for ks size slices upto kmax
    kn = k_max - ki if ks > (k_max - ki) # adjust kn size for last seg
    primes.each_with_index do |prime, j| # for each prime r0..sqrt(N)
                                         # for lower twinpair residue track
      k = nextp.to_unsafe[j * 2]         # starting from this resgroup in seg
      while k < kn                       # mark primenth resgroup bits prime mults
        seg.to_unsafe[k >> s] |= 1_u64 << (k & bmask)
        k += prime  end                  # set resgroup for prime's next multiple
      nextp.to_unsafe[j * 2] = k - kn    # save 1st resgroup in next eligible seg
                                         # for upper twinpair residue track
      k = nextp.to_unsafe[j * 2 | 1]     # starting from this resgroup in seg
      while k < kn                       # mark primenth resgroup bits prime mults
        seg.to_unsafe[k >> s] |= 1_u64 << (k & bmask)
        k += prime  end                  # set resgroup for prime's next multiple
      nextp.to_unsafe[j * 2 | 1]= k - kn # save 1st resgroup in next eligible seg
    end                                  # set as nonprime unused bits in last seg[n]
                                         # so fast, do for every seg[i]
    seg.to_unsafe[(kn - 1) >> s] |= ~1u64 << ((kn - 1) & bmask)
    cnt = 0                              # count the twinprimes in the segment
    seg[0..(kn - 1) >> s].each { |m| cnt += (~m).popcount }
    if cnt > 0                           # if segment has twinprimes
      sum += cnt                         # add segment count to total range count
      upk = kn - 1                       # from end of seg, count back to largest tp
      while seg.to_unsafe[upk >> s] & (1_u64 << (upk & bmask)) != 0; upk -= 1 end
      hi_tp = ki + upk                   # set its full range resgroup value
    end
    ki += ks                             # set 1st resgroup val of next seg slice
    seg.fill(0) if ki < k_max            # set next seg to all primes if in range
  end                                    # when sieve done, numerate largest twin
                                         # for ranges w/o twins set largest to 1
  hi_tp = (r_hi > end_num || sum == 0) ? 1 : hi_tp * modpg + r_hi
  {hi_tp.to_u64, sum.to_u64}             # return largest twinprime|twins count
end

```

**Comment by straight-shoota** [comment]
I mean in the original post: If `15.1`, `80.3`, `180.9` are in seconds and represent the total time as reported by your program, than it executes 1000 times faster in https://github.com/crystal-lang/crystal/issues/12943#issuecomment-1397866229. Or maybe it's not seconds but miliseconds?

Are the runtime values consistent for you?
I ran the program a couple of times for each compiler version and on average, 1.7.0 was pretty similar to 1.6.2 if not a bit faster.

**Comment by jzakiya** [comment]
Yes, all those times are in seconds.
On my AMD Linux laptop the time differences are consistent between versions.
To really see the differences use bigger inputs, e.g. 10_000_000_000 (10^13).

If the performance is different on Intel systems than AMD systems that's still a problem though.
Is the compiled binaries suboptimal for AMD cpus?  Maybe do a source code compilation on an AMD system to check.

Also, in `twins_sieve`  I just changed  `seg = Slice(UInt64)..` to `seg = Array(UInt64)...` and it stopped giving correct (no) results for the number of twinsprimes.

Maybe run the `bitarray`s version and check the different results on your system over a representative range of inputs.

But there's definitely something going on with 1.7.x that's making it slower than 1.6.2, at least on my system.

**Comment by jzakiya** [comment]
I confirmed it has something to do with those compiled binaries in the`..bundled.tar.gz` packages.

I built 1.7.1 from source on my AMD laptop.

```
➜ crystal-projects ~/crystal-1.7.1/bin/crystal -v
Using compiled compiler at /home/jzakiya/crystal-1.7.1/.build/crystal
Crystal 1.7.1 (2023-01-17)

LLVM: 14.0.6
Default target: x86_64-mandriva-linux-gnu
```
Then downloaded the `crystal-1.7.1-1-linux-x86_64-bundled.tar.gz` package
```
➜  crystal-projects ~/crystal-1.7.1-1/bin/crystal -v
Crystal 1.7.1 [643c8e5d8] (2023-01-17)

LLVM: 13.0.1
Default target: x86_64-unknown-linux-gnu
```
and compiled and ran the program on both builds.

The source code build has comparable speeds to 1.6.2 (and the stripped binaries are the smallest),
while the 1.7.1-1 precompiled binary continues to exhibit the same performance regression a seen with 1.7.0-1.

So it seems from this empirical apples-to-apples test on my system there's a definite difference in performance and binary size.
I hope this is helpful.

**Comment by jzakiya** [comment]
This morning (M 2023/1/23) I ran another experiment.
I have an older (2016) System76 laptop with an Intel i7-6700HQ, 4C|8T, cpu.
I copied the binaries compiled on my  (May 2022) Lenovo AMD laptop for 1.6.2-1, 1.7.1-1, and from source for 1.7.1 to the System76.

**Those binaries run on the i7-6700HQ cpu have virtually identical times!**

I think this empirically establishes the binaries provided for the x_86 bundles are suboptimal for (newer) AMD systems, at least for the class of programs represented by my app, which is a highly numerical multi-core program..

**Comment by straight-shoota** [comment]
If I follow correctly, the performance difference correlates with the LLVM version? LLVM 13 is more performant, LLVM 14 less. Can you confirm that?

**Comment by jzakiya** [comment]
No, no, no.

What I've shown is the binaries compiled on my AMD cpu system run with nearly identical times my Intel i7-6700HQ laptop.

When I compiled 1.7.1 from source on my AMD cpy laptop, vs the compiled binary from the installation `..x86_64` bundle, the source binary is comparable to the 1.6.2 bundled binary, while the 1.7.1-1 bundled binary still has the regression.

What I've shown is 1.7.1 compiled from source with LLVM 14.0.6 on my AMD cpu laptop doesn't have the regression.

To experiment further
1. Does 1.7.1 compiled from source with LLVM 13 on an AMD system have the regression on the AMD system?
2. Does 1.7.1 compiled from source with LLVM 14 on an Intel system have the regression on an AMD system?

I don't have LLVM 13 on my system now, so I can't test 1.

But it seems some combination of the LLVM version and the cpu make may cause this particular behavior.

**Comment by jzakiya** [comment]
OK, I did the test 2. scenario.

I compiled the 1.7.1 source code on my Intel i7-6700HQ laptop, then used it to compile the app source code.
This was done with LLVM 14.0.6, as on the AMD laptop, because they both use the same updated OS.

Both versions compiled using 1.7.1 with LLVM 14 have the same (stripped) binary size and same (relative) performance for each laptop  when run on both (compared to times using 1.6.2 on both).

Again, when I compile 1.7.1 source with LLVM 14.0.6 on my Intel laptop, and run it on the Intel and AMD laptop, there are no regressions.  When I compile 1.7.1 source with LLVM 14.0.6 on the AMD laptop, and run on the Intel and AMD,  there are no regressions.

Thus it seems for this program, run on my AMD Ryzen 9 5900HX cpu, the binaries created with LLVM 13 on Intel create suboptimal performance when run on the AMD laptop. So it seems LLVM 13 is a significant part of the problem in this .

But since I don't have LLVM 13 on either laptop I can't do test 1., and compile with LLVM 13 on the AMD lap top and see if that still creates a regression on it that the LLVM 13 binaries created on an Intel system does on my AMD laptop.

**Comment by jzakiya** [comment]
I just downloaded `crystal-1.7.2-1-linux-x86_64-bundled.tar.gz` and used it to compile my program.

This seems to have fixed the problems. Running a few input values show there are no regressions, compared to 1.6.2. :-)

**Comment by straight-shoota** [comment]
That's odd. None of the changes between 1.7.0 and 1.7.2 should affect anything related to this.

The exact circumstances of #12992 are not fully understood, so maybe it could potentially have had some other effect that we don't know about. That's a long shot, though.

**Comment by jzakiya** [comment]
Well, the data don't lie. :-0

Here's some more, showing difference between the `1.7.2 x86_64 bundle` and from the` 1.7.2 source`, on my AMD laptop.
(My OS is PCLinuxOS, not the default target Mandriva)

```
➜  crystal-projects ~/crystal-1.7.2-1/bin/crystal -v
Crystal 1.7.2 [29f9ac503] (2023-01-23)

LLVM: 13.0.1
Default target: x86_64-unknown-linux-gnu

➜  crystal-projects ~/crystal-1.7.2/bin/crystal -v                                                    
Using compiled compiler at /home/jzakiya/crystal-1.7.2/.build/crystal
Crystal 1.7.2 (2023-01-23)

LLVM: 14.0.6
Default target: x86_64-mandriva-linux-gnu
--------------------------------------------------------------------------
Program binary sizes compiled on my AMD laptop

                                 compiled : stripped
1.7.2 w/llVM 13.0.1 x86_64-bund: 1091912  :  487816
1.7.2 w/LLVM 14.0.6 from source: 1056016  :  471432
```
Knowing what I know now, I'll probably compile from source too going forward as a regular sanity check.
