### ISSUE TITLE
SSL_connect: error:02001018:system library:fopen:No file descriptors available (OpenSSL::SSL::Error)

### ISSUE THREAD

**Issue by syalon** [crystal-lang/crystal#12956]
The HTTP library reports this error after running for a long time, and it cannot be recovered. It is guessed that there is a resource leak that has not been recovered.

crystal version：1.2.1 DEBUG mode

**Comment by straight-shoota** [comment]
Can you provide some code that would allow reproducing this problem?
It's hardly possible to track this issue without any way of investigate what might be causing it. Exhaustion of file descriptors can be triggered by anything, completely unrelated to HTTP/SSL.

**Comment by syalon** [comment]
exception backtrace:

<img width="343" alt="image" src="https://user-images.githubusercontent.com/2375337/212603095-4bddc83c-4d84-4fa6-a615-ce8b0abff8e7.png">

**Comment by syalon** [comment]
The code snippet at the call is as follows:
```
      uri = URI.parse(url)

      client = HTTP::Client.new(uri)
      client.dns_timeout = 3.0
      client.connect_timeout = 3.0
      client.read_timeout = 5.0
      client.write_timeout = 5.0

      case request_method
      in .get?
        resp = client.get(uri.request_target, headers: headers)
      in .post?
        resp = client.post(uri.request_target, headers: headers)
      in .put?
        resp = client.put(uri.request_target, headers: headers)
      in .delete?
        resp = client.delete(uri.request_target, headers: headers)
      end
```

**Comment by beta-ziliani** [comment]
It seems that you're not closing the connection (`client.close` in a `ensure` branch), may that be the problem?

From the [documentation](https://crystal-lang.org/api/1.7.0/HTTP/Client.html) when you're calling the instance methods (like in `HTTP::Client.new("www.example.com").get("/")`), you need to close the connection yourself.
