### ISSUE TITLE
Add OpenSSL 3.0.7 support

### ISSUE THREAD

**Issue by stakach** [crystal-lang/crystal#12963]
When building images on Alpine and using TLS with OpenSSL 3.0.7 the logs are spammed with

```
WARNING: Unsupported BIO ctrl call (133)
WARNING: Unsupported BIO ctrl call (128)
```

You can see some example output on our specs
https://github.com/PlaceOS/rest-api/actions/runs/3928647637/jobs/6716500333

Related to: https://github.com/crystal-lang/crystal/issues/12744#issuecomment-1315358356

**Comment by revskill10** [comment]
I got same issue.

**Comment by straight-shoota** [comment]
Hm, can someone create an isolated reproduction? I tried simple examples of both a server with TLS as well as a TLS client request and got no warnings.

**Comment by revskill10** [comment]
Hi @straight-shoota , i got issue when running [this code](https://github.com/place-labs/jwks/blob/master/spec/jwks_spec.cr)

**Comment by straight-shoota** [comment]
Hm, as far as I can see that uses RSA private key signature bindings from https://github.com/spider-gazelle/openssl_ext
Does this warning appear when using any stdlib API?

**Comment by straight-shoota** [comment]
Closing. We can reconsider when there's any indication these errors come form the stdlib bindings.

**Comment by stakach** [comment]
Updated [spider-gazelle/openssl_ext](https://github.com/spider-gazelle/openssl_ext) to handle the `Unsupported BIO ctrl call`s

https://github.com/spider-gazelle/openssl_ext/commit/3ed7a03a735ffc88ceb1e0cafd02bc1081b1993d
