### ISSUE TITLE
compile error: `Error: can't find file 'reply'`

### ISSUE THREAD

**Issue by anatol** [crystal-lang/crystal#12976]
## Bug Report

I am trying to build the official package for Arch Linux and the build instructions that worked for crystal 1.6 fail for crystal 1.7.1:

```
==> Extracting sources...
  -> Extracting crystal-1.7.1.tar.gz with bsdtar
==> Starting build()...
Using /usr/bin/llvm-config-14 [version= 14.0.6]
g++ -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/crystal/src=/usr/src/debug/crystal -flto=auto  -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc -I/usr/lib/llvm14/include -std=c++14   -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
CRYSTAL_CONFIG_BUILD_COMMIT="" CRYSTAL_CONFIG_PATH=lib:/usr/lib/crystal SOURCE_DATE_EPOCH="1674069998"  CRYSTAL_CONFIG_LIBRARY_PATH='$ORIGIN/../lib/crystal' ./bin/crystal build --release --no-debug -D strict_multi_assign -D preview_overload_order --release --link-flags="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto"  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
Showing last frame. Use --error-trace for full trace.

In src/compiler/crystal/interpreter/repl_reader.cr:1:1

 1 | require "reply"
     ^
Error: can't find file 'reply'

If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?
make: *** [Makefile:190: .build/crystal] Error 1
```

The build process complains about `shards`, adding it as a dependency of `crystal` build process does not help here.

Here are the build instructions itself:

```
  make release=1 interpreter=1 \
       FLAGS="--release --no-debug" \
       CRYSTAL_PATH="$srcdir/$pkgname-$pkgver/src" \
       CRYSTAL_CONFIG_VERSION="$pkgver" \
       CRYSTAL_CONFIG_PATH="lib:/usr/lib/crystal" \
       CRYSTAL_CACHE_DIR="/tmp/crystal"
  make docs CRYSTAL_CACHE_DIR="/tmp/crystal"
```

**Comment by straight-shoota** [comment]
`shards` is definitely not required. `reply` is vendored into the repository at `lib/reply`.
`CRYSTAL_PATH` needs to contain `lib` for the compiler to find that. Adding that should fix it.

I'm wondering why this worked before, though. `reply` was only added in 1.7 but `markd` has been used much longer and it's in the same situation. So that should've failed in earlier releases as well 🤔

In general, you shouldn't need to configure `CRYSTAL_PATH` in the Pkgbuild configuration. The make recipes calls `bin/crystal` which sets up the path correctly.

Setting `CRYSTAL_VERSION` is also unnecessary. Make pics up the correct version of the source code from `src/VERSION`.

`PATH=".build:$PATH"` in the check script seems also unnecessary.

**Comment by anatol** [comment]
Thank you @straight-shoota 

After applying your recommendations `crystal` package builds fine. I do not see the above issues anymore.

Thank you for your prompt help!

**Comment by straight-shoota** [comment]
Ah and I realize why this wasn't a problem with `markd` before: It uses a hard-coded relative path to the `lib` directory.

https://github.com/crystal-lang/crystal/blob/84977e48c784811e885f084ae0270c2dd47f14e5/src/compiler/crystal/tools/doc/generator.cr#L1

vs

https://github.com/crystal-lang/crystal/blob/84977e48c784811e885f084ae0270c2dd47f14e5/src/compiler/crystal/interpreter/repl_reader.cr#L1

I think this should standardized. Both dependencies are at the same location and should be referenced the same way.
