### ISSUE TITLE
Make linker configurable on Windows

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#12988]
On POSIX platforms, the linker can be configured via the `CC` environment variable. This does not work on Windows currently, neither does the equivalent of `CL`.
It should be possible to configure the linker on Windows as well.

**Comment by HertzDevil** [comment]
`%CL%` is reserved by MSVC to pass extra command-line options to the compiler, i.e. it is essentially a different `%CFLAGS%`. So we should use `%CC%` even on Windows

**Comment by straight-shoota** [comment]
Related: https://github.com/crystal-lang/crystal/issues/5430#issuecomment-1256240890

**Comment by 3052** [comment]
OK so how does this work? here is still says visual studio is required:

https://crystal-lang.org/install/on_windows/

but if this issue works as advertised, that should no longer be the case

**Comment by 3052** [comment]
https://github.com/crystal-lang/crystal/issues/14236
