### ISSUE TITLE
Add forward_missing_to @object to Colorize

### ISSUE THREAD

**Issue by wyhaines** [crystal-lang/crystal#13007]
## Feature Request

I have submitted a PR:  https://github.com/crystal-lang/crystal/pull/13005

The origin of the PR was an effort to enhance Benchmark::IPS to make more visually engaging reports when there are a lot of items being benchmarked. Sidenote -- I will also be dropping a PR and a discussion issue for this work, once I clean up some of the hacky-bits of what I did.

i.e. it lets one do this:
![image](https://user-images.githubusercontent.com/12992/214887713-05f9f9e9-cafe-40ff-ab04-39f876e2a106.png)

Without any significant changes to the code.

Importing Ary's comment on the PR into this discussion thread:

> In my mind colorize is the last thing you call before moving that object into the output. If you need to do some things with the original string, I would preserve that as a separate variable.
> 
> I think adding forward_missing_to would make things a bit harder to understand.

The impetus for adding this was for places, like the usage with Benchmark::IPS, where a string is being provided as an argument, where it would be nice for a just directly support the use of Colorize.

```
      ips.separator "    Base58 Version #{Base58::VERSION}".colorize.light_yellow
```

Of course, alternatively, one can do this:

```
      ips.separator "    Base58 Version #{Base58::VERSION}".colorize.light_yellow.to_s
```

Which obviates the need for adding forwarding to colorize.

It's definitely a judgement call on which is preferable -- the change to Colorize or the dangling `to_s`.

I'll adjust my patch to Benchmark in accordance with whichever way this goes.

**Comment by straight-shoota** [comment]
What about having `separator` call `to_s` on its argument?

**Comment by wyhaines** [comment]
Right. The key, at least for me when I did this, was that I wanted to alter the code of Benchmark::IPS as little as possible, and adding the forwarding to colorize let me avoid dangling `to_s` in the benchmark script, while modestly reducing the lines that I was touching within Benchmark::IPS; I was trying to make as few changes there as possible.

If adding this forwarding seems like a bad idea, though, I am more than happy to accept that judgement, as the reality is that my additions to Benchmark::IPS, while not materially changing anything, do modestly touch many pieces of the implementation, and dropping a couple `to_s` in the appropriate spots is pretty minor.

**Comment by wyhaines** [comment]
I have gone ahead and yanked the dependence on it from my WIP for Benchmark::IPS. I will close this issue, and also cancel the PR. Thanks for the feedback!
