### ISSUE TITLE
Improve textual representation of `Process::Status`

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#13012]
`Process::Status` currently has very intricate `#to_s` and `#inspect` formats. They're the default implementations inherited from `Reference` and don't convey much relevant information.

I'm proposing to implement a more meaningful representation.

`#to_s` currently returns the type name and object id in the typical format of `Reference#to_s` (e.g. `#<Process::Status:0x7f9fd8a17c40>`). That doesn't make much sense. The object id is pretty much irrelevant.
Instead, it should simply return a textual representation of the exit code or signal:

```cr
process_status(0).to_s           # => "0"
process_status(128).to_s         # => "128"
process_status(Signal::HUP).to_s # => "HUP"
```

(I'm using a ficticious `process_status` helper to represent instances with certain values because `Process::Status` doesn't have a public or easily usable constructor - which should probably be added as well.)

`#inspect` currently enhances the sparse information output of `#to_s` by the names of the instance variables and their values. `@exit_status` is the only ivar and its value is bit encoded, thus not trivial to read. This isn't very useful.
Instead, it should return a textual representation of the exit code or signal, like `#to_s` but enhanced with the type information of `Process::Status` for more expressiveness.
```cr
process_status(0).inspect           # => "Process::Status[0]"
process_status(128).inspect         # => "Process::Status[128]"
process_status(Signal::HUP).inspect # => "Process::Status[Signal::HUP]"
```

**Comment by HertzDevil** [comment]
Shouldn't the second snippet use `#inspect`?

For Windows it might be helpful to have things like `process_status(0xC0000005_u32).to_s # => "STATUS_ACCESS_VIOLATION"`, but this requires us to define an enum for the possible `NTSTATUS` values first; yet not all `NTSTATUS` values really correspond to abnormal exit codes either.

**Comment by straight-shoota** [comment]
> Shouldn't the second snippet use #inspect?

Yeah, fixed 😅

**Comment by HertzDevil** [comment]
`Process::Status[Signal::HUP]` is technically ambiguous because it could also represent the signal that stopped a process (i.e. `exit_status == 0x017F`, like [here](https://github.com/crystal-lang/crystal/issues/8381#issuecomment-612487955)) rather than terminating it. I think it is inevitable to support stop statuses in `Process::Status` too if `#inspect` is involved.

**Comment by straight-shoota** [comment]
But currently there's no way to express a stopped signal, right? So I'm thinking this should be left for an enhancement later.
Now we only need make sure that the inspect syntax and constructor signature are compatible to such an amendment. And I think they are. One option could be to use a named parameter`like this: `Process::Status[stopped: Signal::HUP]`.

**Comment by HertzDevil** [comment]
I think they show up from `Process#wait` with `ptrace`, although I don't know about the details.
