### ISSUE TITLE
Add `static_array` macros to Char and String?

### ISSUE THREAD

**Issue by wyhaines** [crystal-lang/crystal#13019]
## Feature Request

More of a tiny feature discussion. The `static_array` macro only exists for Int types. Is there a particular reason why it doesn't exist for Char and String, as well?

It's a convenience macro, but I had a use case a couple weeks ago, so I whipped up a little patch to add them, and I couldn't see any reason why they are a bad idea.

Is there a reason why they are a bad idea? If not, I'll make a PR.

```
class Foo
  SomeChunkOfKeywords = String.static_array("this", "that", "thensome")
  AlsoCharacters = Char.static_array('1', '2', '3', 'x', 'y', 'z', 'A', 'B', 'C')
end
```

**Comment by straight-shoota** [comment]
I think this macro exists specifically for integer types to avoid duplication of type suffixes in the literal.

For most other types, such as `Char` and `String`, the regular `StaticArray.[]` constructor should be sufficient:

```cr
some_bytes = UInt8.static_array(1, 2, 3, 4, 5)
other_bytes = StaticArray[1_u8, 2_u8, 3_u8, 4_u8, 5_u8]

strings = StaticArray["this", "that", "thensome"]
chars = StaticArray['1', '2', '3', 'x', 'y', 'z', 'A', 'B', 'C']
```

**Comment by wyhaines** [comment]
Perfect. I figured that there was solid reasoning for it, and that does make sense. Thank you.

**Comment by straight-shoota** [comment]
There should definitely be a reference in the API docs.
