### ISSUE TITLE
Wrong endianness when using io.write_bytes in macOS M1

### ISSUE THREAD

**Issue by etra0** [crystal-lang/crystal#13029]
## Bug Report

I was trying the [Tourmaline](https://github.com/protoncr/tourmaline) library when I encountered different behavior depending on the platform.

The following code outputs different results depending on the platform:

```cr
some_text = "this is some raw text"

text = some_text.gsub('\u{0}', "") + ' '
codepoints = text.to_utf16

io = IO::Memory.new
io.set_encoding("UTF-16")

codepoints.each do |codepoint|
  io.write_bytes(codepoint, IO::ByteFormat::LittleEndian)
end

output_string : String = io.rewind.gets_to_end

puts output_string.bytes.to_s
```

## macOS

```bash
 $ crystal -v
Crystal 1.7.2 (2023-01-23)

LLVM: 14.0.6
Default target: aarch64-apple-darwin21.6.0
 $ crystal run something.cr 
[231, 144, 128, 230, 160, 128, 230, 164, 128, 231, 140, 128, 226, 128, 128, 230, 164, 128, 231, 140, 128, 226, 128, 128, 231, 140, 128, 230, 188, 128, 230, 180, 128, 230, 148, 128, 226, 128, 128, 231, 136, 128, 230, 132, 128, 231, 156, 128, 226, 128, 128, 231, 144, 128, 230, 148, 128, 231, 160, 128, 231, 144, 128, 226, 128, 128]
```

## Linux x86_64

https://play.crystal-lang.org/#/r/ehf6
```
[116, 104, 105, 115, 32, 105, 115, 32, 115, 111, 109, 101, 32, 114, 97, 119, 32, 116, 101, 120, 116, 32]
```

The Linux one is the correct one as those bytes correspond to the utf-8 version of the string "this is some raw text", the one in macOS is gibberish.

I noticed when using `IO::ByteFormat::BigEndian` in macOS it does outputs the correct result, but it is incorrect because the platform is little endian as x86_64, so it should work with the other option of the enum.

**Comment by HertzDevil** [comment]
The `UTF-16` encoding does not specify an endianness, try `UTF-16LE` or `UTF-16BE`

**Comment by etra0** [comment]
That's a very good point, but I'd still expect to assume the same on both platforms?

**Comment by oprypin** [comment]
Some notes:

* String.to_utf16 was added just to help with porting to Windows. Not sure why it's public and documented.

To add to the previous comment:

* Rather than manually deciding whether to write 0xFE 0xFF or 0xFF 0xFE, just directly write 0xFEFF as one of the 16-bit codepoints

**Comment by straight-shoota** [comment]
> `String.to_utf16` was added just to help with porting to Windows. Not sure why it's public and documented.

Well it's a useful helper for lib bindings on Windows in user code, not just stdlib. So I think it makes sense to have it exposed.
