### ISSUE TITLE
`Response#reset` leaves the status message untouched

### ISSUE THREAD

**Issue by ya55en** [crystal-lang/crystal#13076]
## Bug Report

It seems `HTTP::Server::Response` are reused and re-set on reuse, however, it seems the status message is left untouched on `#reset`:

```crystal
require "http"

response = HTTP::Server::Response.new(IO::Memory.new)
puts "#{response.status_code} #{response.status_message}"

response.status_message = "Foo Bar"
response.reset
puts "#{response.status_code} #{response.status_message}"
```

This yields:

```
200 OK
200 Foo Bar
```

and I would expect just a "200 OK" twice, because of the `#reset` call. (Or do I miss something?)

Environment:
```
$ crystal --version
Crystal 1.7.2 [29f9ac503] (2023-01-23)

LLVM: 13.0.1
Default target: x86_64-unknown-linux-gnu
```

**Comment by etra0** [comment]
I wonder, this would be a fairly easy thing to fix but yet the Response#reset is hidden from the docs. Any reason for that?

**Comment by Blacksmoke16** [comment]
It's more of an implementation detail than something you should consider calling yourself within an `HTTP::Handler` or something. It's probably still worth fixing, but I'd be curious if you can actually reproduce this bug without calling it directly.
