### ISSUE TITLE
[Feature Request] Support splating on case ... when

### ISSUE THREAD

**Issue by zw963** [crystal-lang/crystal#13093]
HTTP/1.0 200 OK
Server: Emacs/28.2
Date: Mon, 20 Feb 2023 22:49:35 GMT

## Feature Request

I would like support following code in Crystal

```
ary = {"foo", "bar"}

case "bar"
when *ary
  puts "1"
else
  puts "2"
end
```

As following code in ruby.

```ruby
ary = ["foo", "bar"]

case "bar"
whe
n *ary
  puts "1"
else
  puts "2"
end
```

It useful when user want to use variable `var` in another place, and reuse it in case ... when.

It may make code looks better if condition is a long list.

e.g. 

```crystal
a_long_list = {
  "aaaaaaaaaaaaaaaaaaaaaaaaaa",
  "bbbbbbbbbbbbbbbbbbbbbbbbbb",
  "cccccccccccccccccccccccccc",
  "ddddddddddddddddddddddddddd",
  "eeeeeeeeeeeeeeeeeeeeeeeeeee",
  "ffffffffffffffffffffffffffff"
}

case "aaaaaaaaaaaaaaaaaaaaaaaaaa"
when *a_long_list
  puts "1"
else
  puts "2"
end

# it better than

case "aaaaaaaaaaaaaaaaaaaaaaaaaa"
when "aaaaaaaaaaaaaaaaaaaaaaaaaa",
  "bbbbbbbbbbbbbbbbbbbbbbbbbb",
  "cccccccccccccccccccccccccc",
  "ddddddddddddddddddddddddddd",
  "eeeeeeeeeeeeeeeeeeeeeeeeeee",
  "ffffffffffffffffffffffffffff"
  puts "1"
else
  puts "2"
end
```

**Comment by Blacksmoke16** [comment]
I think you can just do like:

```cr
a_long_list = {
  "aaaaaaaaaaaaaaaaaaaaaaaaaa",
  "bbbbbbbbbbbbbbbbbbbbbbbbbb",
  "cccccccccccccccccccccccccc",
  "ddddddddddddddddddddddddddd",
  "eeeeeeeeeeeeeeeeeeeeeeeeeee",
  "ffffffffffffffffffffffffffff",
}

case "aaaaaaaaaaaaaaaaaaaaaaaaaa"
when .in? a_long_list
  puts "1"
else
  puts "2"
end
```

Which is, imo, more readable and doesn't require any new lang features.

**Comment by zw963** [comment]
> Which is, imo, more readable and doesn't require any new lang features.

Cool!  thanks

**Comment by zw963** [comment]
Hi, @Blacksmoke16 , i found splating not work when invoking the macro too.

Check following example

```crystal
class StringWrapper
  def initialize(@string : String)
  end

  methods = {:empty?, :capitalize}

  delegate *methods, to: @string
end

wrapper = StringWrapper.new "HELLO"
wrapper.empty?     # => false
wrapper.capitalize # => "Hello"
```

Will raise error like this:

```
There was a problem expanding macro 'delegate'

Called macro defined in /home/zw963/Crystal/share/crystal/src/object.cr:1284:3

 1284 | macro delegate(*methods, to object)

Which expanded to:

 >  1 |     
 >  2 |       
 >  3 |         def *methods(*args, **options)
 >  4 |           @string.*methods(*args, **options)
 >  5 |         end
 >  6 | 
 >  7 |         
 >  8 |           def *methods(*args, **options)
 >  9 |             @string.*methods(*args, **options) do |*yield_args|
 > 10 |               yield *yield_args
 > 11 |             end
 > 12 |           end
 > 13 |         
 > 14 |       
 > 15 |     
 > 16 |   
Error: unexpected token: "methods" (parentheses are mandatory for def parameters)
```

Do we have plans to add this as a feature request or issue?

**Comment by Blacksmoke16** [comment]
You can deff splat something to a macro, but it of course has to abide by the normal rules of macros. I.e. in this case is known at compile time and expands to valid Crystal code. E.g.

```cr
class StringWrapper
  def initialize(@string : String)
  end

  METHODS = {:empty?, :capitalize}

  {% begin %}
    delegate {{*METHODS}}, to: @string
  {% end %}
end
```

**Comment by straight-shoota** [comment]
For the record: I wouldn't oppose adding this. Splatting is an established concept for locations where the syntax expects a sequence of items. Adding splat support to `when` would just apply an existing concept to a new but very similar use case. Perhaps one could even argue this would be good for completeness.

I don't think it's very important or even necessary. And `.in?` should be a very convenient alternative.

**Comment by zw963** [comment]
> You can deff splat something to a macro, but it of course has to abide by the normal rules of macros. I.e. in this case is known at compile time and expands to valid Crystal code. E.g.
> 
> ```crystal
> class StringWrapper
>   def initialize(@string : String)
>   end
> 
>   METHODS = {:empty?, :capitalize}
> 
>   {% begin %}
>     delegate {{*METHODS}}, to: @string
>   {% end %}
> end
> ```

It works, you are my lifesaver!

In addition, I also noticed that, it seems that splating can also work on arrays, but only in macro, see following code:

```crystal
M = ["foo", "bar"]

{% begin %}
  delegate {{*M}}, to: "hello"
  {% debug %}
{% end %}

def hello(*arg)
end

hello(*M) # => Not work
```

will output:

```
delegate "foo", "bar", to: "hello"
Showing last frame. Use --error-trace for full trace.

In 5.cr:26:7

 26 | hello(*M) # => Not work
            ^
Error: argument to splat must be a tuple, not Array(String)
```

Is this a bug or is it intentional?

**Comment by straight-shoota** [comment]
This is intentional.
