### ISSUE TITLE
Crypto::Bcrypt.digest is slow

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#1309]
As said [here](https://groups.google.com/forum/?fromgroups#!topic/crystal-lang/BWVIyUPJb58).

With a quick glance over the code I can see [Crypto::Blowfish](https://github.com/manastech/crystal/blob/master/src/crypto/blowfish.cr) isn't optimized: it uses arrays instead of static arrays, and, for some reason, uses Int64 when in the [original algorithm](https://en.wikipedia.org/wiki/Blowfish_%28cipher%29#The_algorithm) I can see `uint32_t`.

If anyone wants to do this, let us know and we'll assign them this issue. That is, unless @kostya wants to take the challenge :-)

**Comment by asterite** [comment]
And, as noted [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/crystal-lang/BWVIyUPJb58/Av7wxAY0CAAJ), there's no need to make this fast, but maybe to avoid memory allocations if possible (because right now arrays are cloned where using static arrays would be best).

**Comment by waj** [comment]
Yes, we MUST do this fast, as everything else in Crystal! ;-)
Blowfish is slow by design, but that doesn't mean we cannot try to make the implementation as fast as possible.

**Comment by ysbaddaden** [comment]
BCrypt is slow by nature, but since the Crystal implementation is very slow, one could be tempted to lower the cost to 4 instead of 10 for instance, so it's acceptably fast again (ie. it takes 60ms to hash a password, not 1s)... except that by doing so, we weakened the protection, since a cost of 4 is very fast to generate using another implementation (eg: Ruby's)... oops.

So yeah, Crystals implementation of BCrypt should be made faster!

**Comment by sdogruyol** [comment]
There's no more `Crypto::Bcrypt.digest`. I've tested this using

```crystal
require "crypto/bcrypt/password"
password = Crypto::Bcrypt::Password.create("mysecretpassword")
```

```
time ./bcrypt
./bcrypt  0.19s user 0.00s system 99% cpu 0.197 total
```

It's on par with Ruby version

```ruby
require "bcrypt"
password = BCrypt::Password.create("mysecretpassword")
```

```
time ruby bcrypt.rb
ruby bcrypt.rb  0.14s user 0.02s system 98% cpu 0.156 total
```

Crystal 0.197
Ruby 0.156

I think we can close this issue for now. WDYT @asterite ?

**Comment by RX14** [comment]
`time` isn't a particularly good benchmark, and we're still loosing to a language with a runtime. So I wouldn't say this is fixed at all.

**Comment by sdogruyol** [comment]
@RX14 actually `bcrypt` is a C extension so we're losing to C more than Ruby

**Comment by RX14** [comment]
Ruby:
```rb
require "benchmark/ips"
require "bcrypt"

Benchmark.ips do |x|
  x.report("bcrypt") { BCrypt::Password.create("my password", cost: 10) }
end
```
```
$ ruby bcrypt.rb
Warming up --------------------------------------
              bcrypt     1.000  i/100ms
Calculating -------------------------------------
              bcrypt     18.525  (± 0.0%) i/s -     93.000  in   5.020227s
```

Crystal:
```cr
require "benchmark"
require "crypto/bcrypt"

Benchmark.ips do |x|
  x.report("bcrypt") { Crypto::Bcrypt::Password.create("my password", cost: 10) }
end
```
```
$ ./bcrypt
bcrypt  10.01  (± 0.64%) fastest
```

I really don't think we can close this issue.

**Comment by sdogruyol** [comment]
@RX14 thanks for the benchmark 👍 I agree with you

**Comment by crisward** [comment]
FWIW, I've been reworking an app which was node, to crystal. I'm finding bcrypt to be roughly x2 as slow in crystal vs node's bcrypt, I'm using their c extension.

**Comment by ysbaddaden** [comment]
I vote for removing `Crypto::BCrypt` out of stdlib into it's own `crystal-lang/bcrypt` repository, with a big warning on the README page stating that it's a pure Crystal implementation, but damn too slow compared to the different C implementations available, and thus shouldn't be relied upon. Maybe link to alternatives like [scrypt](https://github.com/ysbaddaden/scrypt-crystal/), or a C implementation too —I never found a well supported BCrypt C library, though.

**Comment by spalladino** [comment]
I wouldn't remove Crystal's BCrypt from the stdlib until we choose a replacement (such as a good C implementation), but I agree that this is something quite important given Crystal's current use cases.

**Comment by sdogruyol** [comment]
Can't we make the pure Crystal version faster?

**Comment by mverzilli** [comment]
Indeed, that's why we added the comunity help wanted label. We want to prioritise this and I'll make an attempt at it, but given it's a security related issue, it would be great if we got several competing implementations.

**Comment by ysbaddaden** [comment]
Let's try.

**Comment by lribeiro** [comment]
The hot path is in encrypt_pair (using instruments on osx)

```
Weight	Self Weight		Symbol Name
7.07 s  100.0%	0 s	 	a (62782)
7.06 s   99.8%	0 s	 	 Main Thread  0x6063ec
7.06 s   99.8%	0 s	 	  start
7.06 s   99.8%	0 s	 	   main
7.05 s   99.7%	1.00 ms	 	    ~procProc(Nil)@a.cr:7
7.05 s   99.6%	3.00 ms	 	     *Crypto::Bcrypt#digest:Slice(UInt8)
6.96 s   98.4%	427.00 ms	 	      *Crypto::Bcrypt::Blowfish@Crypto::Blowfish#expand_key<Slice(UInt8)>:Int32
6.54 s   92.4%	6.54 s	 	       *Crypto::Bcrypt::Blowfish@Crypto::Blowfish#encrypt_pair<Int32, Int32>:Tuple(Int32, Int32)

```

Just changing P and S to static arrays does the following for performance

          blowfish encrypt_pair  15.74M ( 63.55ns) (±11.47%)  3.13× slower
static blowfish encrypt_pair  49.31M ( 20.28ns) (±12.79%)       fastest

**Comment by mverzilli** [comment]
I think finally with Julien's #3880 we're in a good position to close this. @RX14, @crisward wanna give it a try and confirm?

**Comment by ysbaddaden** [comment]
Not exactly, we're still ~15% slower than Ruby's (actually written in C). We got better, but there's still some room for improvement.

**Comment by mverzilli** [comment]
Yeah, actually in mind it was ~15% slower than C. But fair enough, we can leave it open :).

**Comment by kostya** [comment]
i not think this is possible, because slowest function is `encrypt_pair + f`, not imagine any other improves here, unless rewrite it in asm. may be ruby c source compiled with gcc, but crystal with clang, thats why that difference.

**Comment by ysbaddaden** [comment]
I agree, we can't optimize the current implementation. Yet, we're still slower on this security feature. We should still improve, even if it means a complete rewrite.

I don't think the difference lies in GCC vs clang, but in the implementation (Ruby is quite different).

**Comment by crisward** [comment]
Just updated to Crystal v0.2.5 #3880 has made a tangible difference. I have two server apis, one written in node, one in crystal. The bcrypt based login on the node one was noticeably quicker, now the reverse is true. 

The login was taking 180-200ms now takes 115-140ms. It perhaps doesn't sound like much, but 200ms feels like there is something wrong, 115ms feels instant. For reference node is in the middle 140-170ms.

 Big thanks to @ysbaddaden

**Comment by sdogruyol** [comment]
@crisward that's great to hear 👍 🎉

**Comment by ysbaddaden** [comment]
@crisward I'm happy to hear that! Now you can increase the cost :grin: 

I'd like more comparisons of differences between languages / implementations. For example OpenBSD's (C), Java, Go, Python...

**Comment by codenoid** [comment]
is still low ?

**Comment by sdogruyol** [comment]
As @ysbaddaden and https://github.com/crystal-lang/crystal/issues/1309#issuecomment-274738481 stated, this is no longer slow. However there's still some room for improvement :+1: Shall we close this?

**Comment by ysbaddaden** [comment]
Let's close. We'd probably need a rewrite to further optimize, and current speed is somewhat acceptable.
