### ISSUE TITLE
String#split empty values yield inconsistent

### ISSUE THREAD

**Issue by noraj** [crystal-lang/crystal#13117]
## Discussion

I want to discuss the inconsistent behavior of `String#split` depending on the overloading.

```
def split(limit : Int32 | Nil = nil) : Array(String)
def split(limit : Int32 | Nil = nil, &block : String -> _)

def split(separator : Char, limit = nil, *, remove_empty = false) : Array(String)
def split(separator : Char, limit = nil, *, remove_empty = false, &block : String -> _)
def split(separator : String, limit = nil, *, remove_empty = false) : Array(String)
def split(separator : String, limit = nil, *, remove_empty = false, &block : String -> _)
def split(separator : Regex, limit = nil, *, remove_empty = false) : Array(String)
def split(separator : Regex, limit = nil, *, remove_empty = false, &block : String -> _)
```

When no separator is provided, `split` remove (does no yield) all whitespace by default. While, when a separator is provided, `split` does not remove (yield) whitespace.

When no separator is provided, `split` assumes that a whitespace is the separator and so does no yield the separator. While, when a separator is provided, `split` will remove the first occurrence of the separator and yield the others if several are consecutive.

An option `remove_empty` which is false by default has been created to handle that, but the behavior when the separator is provided or not is inconsistent.

Also when no separator is provided, all kind of whitespace are removed U+0020 (SPACE), U+000A (new line), U+0009 (horizontal tab) etc. while when a separator is provided plus the option `remove_empty` only the separator and empty values are removed. Which is expected.

## Example Crystal

Code n°1 (space):

```crystal
test = "0: 3500007F:0035 00000000:0000 0A 00000000:00000000 00:00000000 00000000   980        0 14187 1 0000000021464e0a 99 0 0 10 5"
puts test.split
puts test.split(" ")
puts test.split(" ", remove_empty: true)
```

Output:

```crystal
["0:", "3500007F:0035", "00000000:0000", "0A", "00000000:00000000", "00:00000000", "00000000", "980", "0", "14187", "1", "0000000021464e0a", "99", "0", "0", "10", "5"]
["0:", "3500007F:0035", "00000000:0000", "0A", "00000000:00000000", "00:00000000", "00000000", "", "", "980", "", "", "", "", "", "", "", "0", "14187", "1", "0000000021464e0a", "99", "0", "0", "10", "5"]
["0:", "3500007F:0035", "00000000:0000", "0A", "00000000:00000000", "00:00000000", "00000000", "980", "0", "14187", "1", "0000000021464e0a", "99", "0", "0", "10", "5"]
```

Code n°2 (new line):

```crystal
test = "0:\n3500007F:0035\n00000000:0000\n0A\n00000000:00000000\n00:00000000\n00000000\n\n\n980\n\n\n\n\n\n\n\n0\n14187\n1\n0000000021464e0a\n99\n0\n0\n10\n5"
puts test.split
puts test.split("\n")
puts test.split("\n", remove_empty: true)
```

Output:

```crystal
["0:", "3500007F:0035", "00000000:0000", "0A", "00000000:00000000", "00:00000000", "00000000", "980", "0", "14187", "1", "0000000021464e0a", "99", "0", "0", "10", "5"]
["0:", "3500007F:0035", "00000000:0000", "0A", "00000000:00000000", "00:00000000", "00000000", "", "", "980", "", "", "", "", "", "", "", "0", "14187", "1", "0000000021464e0a", "99", "0", "0", "10", "5"]
["0:", "3500007F:0035", "00000000:0000", "0A", "00000000:00000000", "00:00000000", "00000000", "980", "0", "14187", "1", "0000000021464e0a", "99", "0", "0", "10", "5"]
```

Code n°3 (mixed):

```crystal
test = "a b  c  \nd \n e  \n  f              g"
puts test.split
puts test.split(" ")
puts test.split(" ", remove_empty: true)
puts test.split("\n")
puts test.split("\n", remove_empty: true)
```

Output:

```crystal
["a", "b", "c", "d", "e", "f", "g"]
["a", "b", "", "c", "", "\nd", "\n", "e", "", "\n", "", "f", "", "", "", "", "", "", "", "", "", "", "", "", "", "g"]
["a", "b", "c", "\nd", "\n", "e", "\n", "f", "g"]
["a b  c  ", "d ", " e  ", "  f              g"]
["a b  c  ", "d ", " e  ", "  f              g"]
```

## Example in Ruby

Code n°1 (space):

```ruby
require 'pp'
test = "0: 3500007F:0035 00000000:0000 0A 00000000:00000000 00:00000000 00000000   980        0 14187 1 0000000021464e0a 99 0 0 10 5"
PP.singleline_pp test.split
puts
PP.singleline_pp test.split(" ")
```

Output:

```ruby
["0:", "3500007F:0035", "00000000:0000", "0A", "00000000:00000000", "00:00000000", "00000000", "980", "0", "14187", "1", "0000000021464e0a", "99", "0", "0", "10", "5"]
["0:", "3500007F:0035", "00000000:0000", "0A", "00000000:00000000", "00:00000000", "00000000", "980", "0", "14187", "1", "0000000021464e0a", "99", "0", "0", "10", "5"]
```

Code n°2 (new line):

```ruby
require 'pp'
test = "0:\n3500007F:0035\n00000000:0000\n0A\n00000000:00000000\n00:00000000\n00000000\n\n\n980\n\n\n\n\n\n\n\n0\n14187\n1\n0000000021464e0a\n99\n0\n0\n10\n5"
PP.singleline_pp test.split
puts
PP.singleline_pp test.split("\n")
```

Output:

```ruby
["0:", "3500007F:0035", "00000000:0000", "0A", "00000000:00000000", "00:00000000", "00000000", "980", "0", "14187", "1", "0000000021464e0a", "99", "0", "0", "10", "5"]
["0:", "3500007F:0035", "00000000:0000", "0A", "00000000:00000000", "00:00000000", "00000000", "", "", "980", "", "", "", "", "", "", "", "0", "14187", "1", "0000000021464e0a", "99", "0", "0", "10", "5"]
```

Code n°3 (mixed):

```ruby
require 'pp'
test = "a b  c  \nd \n e  \n  f              g"
PP.singleline_pp test.split
puts
PP.singleline_pp test.split(" ")
puts
PP.singleline_pp test.split("\n")
```

```ruby
["a", "b", "c", "d", "e", "f", "g"]
["a", "b", "c", "d", "e", "f", "g"]
["a b  c  ", "d ", " e  ", "  f              g"]
```

## Suggestion

I suggest defaulting `remove_empty` to `true`. Which is a breaking change.

**Comment by asterite** [comment]
Let's say you have comma separated values. Please provide how it works by default in Crystal and Ruby to get each value between the commas (and show what happens when there are consecutive commas)

**Comment by straight-shoota** [comment]
I see no inconsistency here.

The combined signature `#split(separator : Char | Regex | String, limit = nil, *, remove_empty = false)` represents the general case. It allows to specify an arbitrary separator. `remove_empty` is false by default because that's the more sensible option, and probably what's typically expected.

Now `#split(limit : Int32 | Nil = nil)` is a specialization for the case of splitting a string into words which are separated by any kind of white space. Semantically it's more or less equivalent to `split(/\s+/, remove_empty: true)`. `remove_empty: true` is the most expected behaviour for this use case.

**Comment by noraj** [comment]
> Let's say you have comma separated values. Please provide how it works by default in Crystal and Ruby to get each value between the commas (and show what happens when there are consecutive commas)

Same as space, its just that if you have `a   b` (a space space space b) and `remove_empty: false` the each space is viewed as a separator between empty values.

```crystal
test = "0:,3500007F:0035,00000000:0000,0A,00000000:00000000,00:00000000,00000000,,,980,,,,,,,,0,14187,1,0000000021464e0a,99,0,0,10,5"
puts test.split
puts test.split(",")
puts test.split(",", remove_empty: true)
```

```
["0:,3500007F:0035,00000000:0000,0A,00000000:00000000,00:00000000,00000000,,,980,,,,,,,,0,14187,1,0000000021464e0a,99,0,0,10,5"]
["0:", "3500007F:0035", "00000000:0000", "0A", "00000000:00000000", "00:00000000", "00000000", "", "", "980", "", "", "", "", "", "", "", "0", "14187", "1", "0000000021464e0a", "99", "0", "0", "10", "5"]
["0:", "3500007F:0035", "00000000:0000", "0A", "00000000:00000000", "00:00000000", "00000000", "980", "0", "14187", "1", "0000000021464e0a", "99", "0", "0", "10", "5"]
```

**Comment by asterite** [comment]
With what I asked for comma, can you provide how ir behaves in Ruby too? There you will find Ruby is inconsistent here, not Crystal.

**Comment by noraj** [comment]
> With what I asked for comma, can you provide how it behaves in Ruby too? There you will find Ruby is inconsistent here, not Crystal.

I added Ruby with comma, I see now. Well, it's identical with comma that it was with new lines, in ruby when there two consecutive separators, empty values are removed is the separator is space while the empty values remains for other separators, which is inconsistent. Fair enough.

I'll close the discussion, thanks all for your time and precious explanations.
