### ISSUE TITLE
Allow collectable types to specify how they handle the Array-like Type Literal

### ISSUE THREAD

**Issue by BlobCodes** [crystal-lang/crystal#13112]
# Feature Request

In this issue, I will call the "Array-like Type Literal" the "`{}` operator".

## Problem

Currently, the `Type{}` operator works in a very simple way.
It first creates the Type by initializing it without any arguments and then adds each element using the `<<` operator.

This has multiple issues:
- It only works with resizable collections

  This means that `StaticArray`, `Slice`, `BitArray` and some third-party collections cannot be created this way.
  ..which will cause them to either use the `[]` macro for creation or not support this at all, which are both bad choices.
  `StaticArray` is extra special in this regard as there are helper macros for numbers (`Int32.static_array(el1, el2, ...)`)

- Using this operator is slow because the collections do not know their final sizes beforehand

  By that I mean it is absurdly slow.
  It is faster to create a `Deque` from an `Array` which will never be used again instead of using a literal.
  <details>
  
  Code:
  ```crystal
  require "benchmark"

  Benchmark.ips do |x|
    x.report("Using collection operator") { Deque{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20} }
    x.report("From array") { Deque.new([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]) }
  end
  ```

  Results:
  ```
  Using collection operator   7.49M (133.49ns) (± 0.58%)  336B/op   2.19× slower
                 From array  16.38M ( 61.04ns) (± 0.67%)  256B/op        fastest
  ```

  <summary><b>Click here for a benchmark!</b></summary>
  </details>

- Types cannot apply any other optimizations

  It is possible that a collection could apply advanced optimizations in certain scenarios.
  For example, if I have a collection for storing bytes (`UInt8`), I could improve performance by defining a String with the final data at compile-time and then copying its data to the heap when this collection is created.

All these issues arise because of the simplicity of this operator.

## Proposal

Collections should be able to define a custom handler for the array-like literal.
I think for this, a new macro hook should be perfectly suited.
To ensure this macro is not abused for non-collection-types, the compiler could ensure that the macro always evaluates to the given datatype.
Of course, the default handler for these literals would remain the same to avoid breaking changes.

Using such a macro, `StaticArray` could easily be supported:
```crystal
struct StaticArray(T, N)
  private macro collection_created(elements)
    %ret = uninitialized typeof({{elements.splat}})[{{elements.size}}]
    {% for el, i in elements %}
      {% el.raise "StaticArray{} does not support splats as its size needs to be known at compile-time" if el.is_a?(Splat) %}
      %ret.unsafe_put({{i}}, {{el}})
    {% end %}
    %ret
  end
end
```

And resizable types could be initialized more efficiently:
```crystal
class Deque(T)
  private macro collection_created(elements)
    {% if elements.any?(&.is_a?(Splat)) %}
      Enumerable.collection_created(elements)
    {% else %}
      # Optimized creation
      Deque(typeof({{elements.splat}})).build_unsafe(initial_capacity: {{elements.size}}) do |%ptr|
        {% for el, i in elements %}
          %ptr[{{i}}] = {{el}}
        {% end %}
    {% end %}
  end
end
```

**Comment by HertzDevil** [comment]
There is a discussion on #13060 of how it would be very cumbersome for users to override just part of the literal behavior and keep the rest if the same macro is also responsible for all the splat expansions, generic type inference, initial capacity calculation etc.
