### ISSUE TITLE
Regex::MatchData to string

### ISSUE THREAD

**Issue by noraj** [crystal-lang/crystal#13118]
## Discussion

There is actually no way to cast the matched data to string when you want all matched values (and not only the first one).

Take the following code where the string will be split every two characters.

```crystal
ip = "3500007F"
puts ip.scan(/.{2}/).map{ |x| x }
```

Ruby output:

```
35
00
00
7F
```

Crystal output:

```
[Regex::MatchData("35"), Regex::MatchData("00"), Regex::MatchData("00"), Regex::MatchData("7F")]
```

Scan returns `Regex::MatchData` object and not string like Ruby. So once you know that the natural solution should be to cast the Regex::MatchData object to string.

But `Regex::MatchData.string` returns the original string and not the matched data.

```crystal
ip = "3500007F"
puts ip.scan(/.{2}/).map{ |x| x.string }
```

```
crystal test.cr
["3500007F", "3500007F", "3500007F", "3500007F"]
```

Ok then, so I would expect `to_s` to return the matched data then.

```crystal
ip = "3500007F"
puts ip.scan(/.{2}/).map{ |x| x.to_s }
```

```
["Regex::MatchData(\"35\")", "Regex::MatchData(\"00\")", "Regex::MatchData(\"00\")", "Regex::MatchData(\"7F\")"]
```

But no it stringify the whole object.

I found [a similar question on stackoverflow](https://stackoverflow.com/questions/51391997/how-to-access-the-results-of-match-as-string-value-in-crystal-lang) but it remains unanswered. (The accepted answer works only if you want to return only the 1st match.

```
ip = "3500007F"
puts ip[/.{2}/]?
puts ip.match(/.{2}/).not_nil![0]
```

```
35
35
```

By the way `String#scan` returns a `Regex::MatchData` object if the pattern is a Regexp and returns a `String` if the pattern is a String. Which seems a bit inconsistent.

But on `Regex::MatchData` the method `to_a` returns an array with the string inside.

Meaning that to achieve the researched behavior I can cast each `Regex::MatchData` to an array and obtain an array of array of string that I can flatten to get an array of string. Which is overcomplicated, unnatural and overconsuming resources.

To achieve the same result, here are the compared code in Ruby and in Crystal:

Ruby

```ruby
ip = "3500007F"
puts ip.scan(/.{2}/).map{ |x| x.hex.to_s }.reverse.join('.')
```

Crystal

```
ip = "3500007F"
puts ip.scan(/.{2}/).map{ |x| x.to_a }.flatten.map { |x| x.not_nil!.to_i(16).to_s }.reverse.join(".")
```

Output:

```
127.0.0.53
```

## Suggestion

In the first place I would have expected to `String#scan()` to return Strings and not `Regex::MatchData`. But I guess it's here for technical reasons. In the second place I would have expected `Regex::MatchData.string` or `Regex::MatchData.to_s` to return a string containing the matched result. I would suggest changing on of them but this would be a breaking change. So if you don't want to introduce a breaking change I would suggest to add a new method to cast `Regex::MatchData` to string, for example `Regex::MatchData.match`.

**Comment by oprypin** [comment]
This is the solution - 0th match group returns the matched string

```crystal
ip = "3500007F"
puts ip.scan(/.{2}/).map{ |x| x[0] }
```

Described briefly at the top of https://crystal-lang.org/api/1.7.2/Regex/MatchData.html

**Comment by Blacksmoke16** [comment]
You can simplify the Crystal version to:

```cr
ip = "3500007F"
puts ip.scan(/.{2}/).reverse_each.join '.' { |x| x[0].to_i 16 }
```

To add on the previous post, because your `#scan` call has no capture groups, you can just grab the first capture as it represents the entire match, which in this case would contain your 2 character pair. If you had some explicit capture groups those would also be represented in the match data object.

**Comment by straight-shoota** [comment]
This is correct ☝️

But I figure we can do a couple of things to improve the developer experience:

* Explicitly document this in the API docs.
* It might be good to have a dedicated method for querying the entire matched substring instead of having to rely on the implicit semantics of the 0th capture group. Maybe `MatchData#capture`?
* `MatchData#to_s` is currently identical to `#inspect`, but there could be a better dedicated string representation. I guess returning the matched substring might be most reasonable.

**Comment by noraj** [comment]
> This is the solution - 0th match group returns the matched string

So it behaves like a capture group even if there is no capture group?

**Comment by Sija** [comment]
@noraj `0`-indexed group is somewhat special in this sense, and IIRC it behaves the same in Ruby

**Comment by straight-shoota** [comment]
Yes, this is effectively a characteristic of the regex engine and AFAIK most engines expose the matched substring as capture group 0.

**Comment by apainintheneck** [comment]
I'm guessing that this can probably be closed since https://github.com/crystal-lang/crystal/pull/14115 addressed most of the confusion unless there is a need for further documentation.
