### ISSUE TITLE
Remove `not_nil!` from `Regex::MatchData` docs

### ISSUE THREAD

**Issue by devnote-dev** [crystal-lang/crystal#13120]
The [documentation for `Regex`](https://crystal-lang.org/api/1.7.2/Regex/MatchData.html) uses _a lot_ of `not_nil!` in the code examples, and is one of only 4 pages to do this, but it should not be like this. It is generally recommended to not use this method where possible (or unless absolutely necessary, IMO) and the Regex docs should reflect that.

Most (if not all) of the examples are to do with the `String#match` method which is nilable, so I have created #13119 to address that, but another solution could be to recommend the conditional statement check syntax. For example, take [`Regex::MatchData#[]`](https://crystal-lang.org/api/1.7.2/Regex/MatchData.html#%5B%5D%28group_name%3AString%29%3AString-instance-method) which has the following code example:

```crystal
"Crystal".match(/r(?<ok>ys)/).not_nil!["ok"] # => "ys"
"Crystal".match(/r(?<ok>ys)/).not_nil!["ng"] # raises KeyError
```

This could easily be changed to:

```crystal
if matches = "Crystal".match(/r(?<ok>ys)/)
  matches["ok"] # => "ys"
  matches["ng"] # raises KeyError
end
```

I believe that this is much clearer than the existing example and it effectively avoids using `not_nil!` thanks to the conditional logic.

WDYT?

**Comment by straight-shoota** [comment]
If `#match!` gets implemented, I think that would be the most concise way to get rid of `.not_nil!`.
So let's wait for the resolution of https://github.com/crystal-lang/crystal/issues/13119

**Comment by stufro** [comment]
I was looking at picking this one up but now #13285 has changed all the documentation for `Regex::MatchData`

Can this issue be closed now?
