### ISSUE TITLE
Make `Array#@buffer` a part of the public API

### ISSUE THREAD

**Issue by sanks64** [crystal-lang/crystal#13124]
Currently, the internal `Array` buffer can only be accessed through a hack (`array.@buffer`). Ideally, this should never be used.

However, this potentially allows for much lower memory usage and slighly better performance. Particularly in [Pluto](https://github.com/phenopolis/pluto) ([1](https://github.com/phenopolis/pluto/blob/6c8908ab94ce9193fe2751498772fcc86c35bb19/src/pluto/operation/horizontal_blur.cr#L50), [2](https://github.com/phenopolis/pluto/blob/6c8908ab94ce9193fe2751498772fcc86c35bb19/src/pluto/operation/vertical_blur.cr#L50)).

- With accessing the internal buffer

  ```crystal
  channel.@buffer.copy_from(buffer.to_unsafe, buffer.size)
  ```

  |                      | Time | Memory  |
  | -------------------- | ---- | ------- |
  | gaussian_blur!(10)   | 16ms | 1.75MiB |
  | horizontal_blur!(10) | 2ms  | 300kiB  |
  | vertical_blur!(10)   | 3ms  | 300kiB  |

- Without accessing the internal buffer

  ```crystal
  new_channels = [] of Array(UInt8)

  each_channel do |channel|
    new_channel = Array.new(size) { 0u8 }
    # ...
    new_channels << new_channel
  end

  red = new_channels[0]
  green = new_channels[1]
  blue = new_channels[2]
  alpha = new_channels[3]
  ```

  |                      | Time | Memory  |
  | -------------------- | ---- | ------- |
  | gaussian_blur!(10)   | 18ms | 8.79MiB |
  | horizontal_blur!(10) | 2ms  | 1.47MiB |
  | vertical_blur!(10)   | 3ms  | 1.47MiB |

In addition, this change might work well with #11485 ([1](https://github.com/phenopolis/pluto/blob/main/src/pluto/operation/bilinear_resize.cr#L11), [2](https://github.com/phenopolis/pluto/blob/main/src/pluto/operation/bilinear_resize.cr#L53)).

An alternative solution would be implementing `Array#copy_to` and `Array#copy_from`.

**Comment by sanks64** [comment]
The script used for benchmarks: https://github.com/phenopolis/pluto/blob/main/scripts/benchmark.cr

**Comment by straight-shoota** [comment]
An array's buffer is already exposed via `Array#to_unsafe`. It allows exactly these kind of low level optimizations.
Maybe you just missed it?

**Comment by sanks64** [comment]
Oh, wow. Yes, that's it. Thank you!

**Comment by straight-shoota** [comment]
Looking at your use case, I'm also wondering if `Array` is actually the right data type for image data. I figure you don't need most of the features specific to `Array` for that. `Slice` should probably do and is a bit more lightweight.

**Comment by sanks64** [comment]
The original idea was that `Array` is exposed in the public API, so it's easier for users than interacting with `Slice`. I imagine it would get only better if #11485 gets merged.
