### ISSUE TITLE
Error: undefined fun 'isatty' for LibC on Windows

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#13165]
## Bug Report

Discovered as part of https://github.com/athena-framework/athena/actions/runs/4370118689/jobs/7644691322 within the `framework` tests:
```cr
Creating library C:\Users\runneradmin\AppData\Local\crystal\cache\D-a-_temp-crystal-nightly-true-undefined-src-ecr-process.cr\macro_run.lib and object C:\Users\runneradmin\AppData\Local\crystal\cache\D-a-_temp-crystal-nightly-true-undefined-src-ecr-process.cr\macro_run.exp
Showing last frame. Use --error-trace for full trace.
  
In D:\a\_temp\crystal-nightly-true-undefined\src\crystal\system\win32\socket.cr:338:10
  
 338 | LibC.isatty(fd) == 1

Error: Error: undefined fun 'isatty' for LibC
```
I haven't manually confirmed it, but I'd assume this is a resume of doing like `STDIN.tty?` on windows.

Seems the actual binding for that function was missed in https://github.com/crystal-lang/crystal/pull/10784 and this is first time someone tried using `IO#tty?` on windows?

**Comment by Blacksmoke16** [comment]
Okay no, `STDIN.tty?` works just fine. But it _does_ fail if you actually require `socket`:

```cr
require "socket"

pp STDIN.tty?
```
```
 339 | LibC.isatty(fd) == 1
            ^-----
Error: undefined fun 'isatty' for LibC
```

**Comment by HertzDevil** [comment]
Easiest to just copy `Crystal::System::FileDescriptor#system_tty?`, which uses `LibC._isatty` instead, to `Crystal::System::Socket#system_tty?`

**Comment by straight-shoota** [comment]
I don't think a socket on Windows can ever be a tty. Unlike on POSIX platforms, they're disparate handles. And AFAIK you cannot turn a console handle into a socket handle somehow.

So perhaps the trivial solution is for `Socket#system_tty?` to return `false` on windows?

**Comment by Blacksmoke16** [comment]
Based on what I read that's probably worth a try. It'll at least get things compiling and can always revisit if someone ever comes across a case where it _could_ be `true`. Will see what CI things. I pushed up another commit.
