### ISSUE TITLE
`Time::Location#load` with IANA TZ string

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#13166]
## Bug Report

```sh
$ ~/Downloads/crystal.exe --version
Crystal 1.8.0-dev [bbe28a0] (2023-03-08)

LLVM: 13.0.1
Default target: x86_64-pc-windows-msvc
```

```cr
pp Time::Location.load("Europe/Berlin")
```
```text
$ ~/Downloads/crystal.exe test.cr
   Creating library C:\Users\Georg\AppData\Local\crystal\cache\crystal-run-test.tmp.lib and object C:\Users\Georg\AppData\Local\crystal\cache\crystal-run-test.tmp.exp
Unhandled exception: Invalid location name: Europe/Berlin (Time::Location::InvalidLocationNameError)
  from C:\Users\Georg\Downloads\src\time\location.cr:301 in 'load'
  from test.cr:1 in '__crystal_main'
  from C:\Users\Georg\Downloads\src\crystal\main.cr:115 in 'main_user_code'
  from C:\Users\Georg\Downloads\src\crystal\main.cr:101 in 'main'
  from C:\Users\Georg\Downloads\src\crystal\main.cr:127 in 'main'
  from C:\Users\Georg\Downloads\src\crystal\system\win32\wmain.cr:37 in 'wmain'
  from D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288 in '__scrt_common_main_seh'
  from C:\WINDOWS\System32\KERNEL32.DLL +95764 in 'BaseThreadInitThunk'
  from C:\WINDOWS\SYSTEM32\ntdll.dll +337569 in 'RtlUserThreadStart'
```

This method ultimately seems to be falling back on `Crystal::System::Time.zone_sources` since there is no `ZONEINFO` env var set, which it set to return an empty array: https://github.com/crystal-lang/crystal/blob/bbe28a0e189eccf16f0100b6e0cf8bbdbd99b4ee/src/crystal/system/win32/time.cr#L76-L78

**Comment by straight-shoota** [comment]
Yes, that's expected and not much to do about it, really.

On Windows there is no standardized path for finding a copy of the time zone database. Unlike most Unix systems, Windows doesn't provide that database. Hence `zone_sources` on win32 is empty. It just cannot work out of the box.

Applications using the time zone database on Windows typically ship a copy themselves.

The only direct action I see is to improve the error message. It should say that no copy of the time zone database was found which makes it easier to understand the issue.

A related issue is distribution of CA certificates (ref #12476). Taking this one step further would be to help application developers to ship these databases with Crystal applications on Windows.

**Comment by HertzDevil** [comment]
It seems Windows 10 comes with the ICU library, and that is what .NET 6 uses to map IANA timezones to Windows ones. We could probably bind against libicu on Windows for this

**Comment by straight-shoota** [comment]
That could be some improvement.

But it's important to not that this only makes the time zone information accessible that's available in the Windows registry. Compared to the IANA database, this is much smaller. The Windows registry does not provide historical information. It only has the *current* time zone offset (standard and DST + switch dates). So it will only be accurate within a certain time frame around the current time and not account for changes in the time zone rules that occured in the past.

https://learn.microsoft.com/en-us/windows/win32/api/timezoneapi/ns-timezoneapi-time_zone_information?redirectedfrom=MSDN

For most use cases that's probably sufficient. And it's definitely an improvement.
But it's also a potential problem because it assumes the current time zone configuration has always been in place at any prior time which will inevitably lead to incorrect results. And there's no way to detect that.

IMO shipping a copy of the IANA database is *always* a better option than relying on the Windows registry.

**Comment by HertzDevil** [comment]
What about [`EnumDynamicTimeZoneInformation`](https://learn.microsoft.com/en-us/windows/win32/api/timezoneapi/nf-timezoneapi-enumdynamictimezoneinformation)? It sounds exactly like what you are describing

**Comment by HertzDevil** [comment]
If you call `GetDynamicTimeZoneInformation` that is what you get. The method I mentioned can indeed enumerate over historical DST boundaries in the registry, or you could manually open the `Dynamic DST` keys:

```crystal
lib LibC
  struct DYNAMIC_TIME_ZONE_INFORMATION
    bias : LONG
    standardName : StaticArray(WCHAR, 32)
    standardDate : SYSTEMTIME
    standardBias : LONG
    daylightName : StaticArray(WCHAR, 32)
    daylightDate : SYSTEMTIME
    daylightBias : LONG
    timeZoneKeyName : StaticArray(WCHAR, 128)
    dynamicDaylightTimeDisabled : BYTE # BOOLEAN
  end

  fun EnumDynamicTimeZoneInformation(dwIndex : DWORD, lpTimeZoneInformation : DYNAMIC_TIME_ZONE_INFORMATION*) : DWORD
  fun GetDynamicTimeZoneInformationEffectiveYears(lpTimeZoneInformation : DYNAMIC_TIME_ZONE_INFORMATION*, firstYear : DWORD*, lastYear : DWORD*) : DWORD
  fun GetTimeZoneInformationForYear(wYear : UShort, pdtzi : DYNAMIC_TIME_ZONE_INFORMATION*, ptzi : TIME_ZONE_INFORMATION*) : DWORD
end

i = 0
while LibC.EnumDynamicTimeZoneInformation(i, out tzinfo) == WinError::ERROR_SUCCESS.value
  puts String.from_utf16(tzinfo.standardName.to_unsafe)[0]
  if LibC.GetDynamicTimeZoneInformationEffectiveYears(pointerof(tzinfo), out first_year, out last_year) == WinError::ERROR_SUCCESS.value
    (first_year..last_year).each do |year|
      if LibC.GetTimeZoneInformationForYear(year, pointerof(tzinfo), out year_tzinfo) != 0
        p [year, year_tzinfo]
      end
    end
  end
  i += 1
end
```

![image](https://user-images.githubusercontent.com/1361918/224086369-52f5bec5-b75e-4344-8ffe-a1d9c1193354.png)

Am I missing something?

**Comment by HertzDevil** [comment]
This issue itself is actually rather easy provided ICU exists:

```crystal
@[Link("icu")]
lib LibICU
  alias UChar = UInt16

  enum ErrorCode
    ZERO_ERROR = 0
  end

  fun get_windows_time_zone_id = ucal_getWindowsTimeZoneID(id : UChar*, len : Int32, winid : UChar*, winidCapacity : Int32, status : ErrorCode*) : Int32
end

module ICU
  macro with_err(call)
    %error_code = ::LibICU::ErrorCode::ZERO_ERROR
    %result = {{ call.receiver }}.{{ call.name }}(
      {% for arg in call.args %} {{ arg }}, {% end %}
      pointerof(%error_code)
    )
    ::Tuple.new(%result, %error_code)
  end

  def self.iana_timezone_to_windows(tz : String) : String?
    tz = tz.to_utf16
    len, _ = ICU.with_err LibICU.get_windows_time_zone_id(tz, tz.size, nil, 0)
    if len != 0
      buf = Pointer(UInt16).malloc(len)
      ICU.with_err LibICU.get_windows_time_zone_id(tz, tz.size, buf, len)
      String.from_utf16(buf)[0]
    end
  end
end

ICU.iana_timezone_to_windows("Asia/Hong_Kong") # => "China Standard Time"
ICU.iana_timezone_to_windows("Europe/Berlin")  # => "W. Europe Standard Time"
ICU.iana_timezone_to_windows("Europe/Berli")   # => nil
ICU.iana_timezone_to_windows("")               # => nil
```

**Comment by straight-shoota** [comment]
Great. 👌 

Yeah, `Std` doesn't matter. This value is even localized, so not comparable between Windows installations. In my German copy for example `Std` is `Westjordanland Gaza Normalzeit`.
