### ISSUE TITLE
[RFC] Platform support

### ISSUE THREAD

**Issue by beta-ziliani** [crystal-lang/crystal#13170]
I'm bringing the discussion of which platforms we should support after [this comment](https://github.com/crystal-lang/distribution-scripts/issues/228#issuecomment-1461800910). I think we should do the following changes to the [Platform Support](https://crystal-lang.org/reference/syntax_and_semantics/platform_support.html) document, and act accordingly.

My proposal is to state that in Tier 1 we only support supported platforms. That is, if a platform reached EOL (like [macOS 10.X](https://endoflife.date/macos)), it doesn't make sense to keep it here.

Therefore, the two main Tier 1 platforms should be split according to their own support. macOS 10.X, for instance, can still be considered Tier 2.

In case of Linux, as of today, they should be also split in 3.X vs 2.X.

**Comment by HertzDevil** [comment]
For Windows there is #10085

**Comment by beta-ziliani** [comment]
Fair point. As a person living in a third-world country, I can understand the need to support older systems. But maybe not in Tier 1? In the specific cases of current Tier 1 platforms, we know they still compile in lower systems, we would simply not claim to have binaries ready.

**Comment by bcardiff** [comment]
Seem reasonable to me to demote macOS 10.x to tier 2 at this point.

**Comment by kjarex** [comment]
Just a thought: I think it depends heavily on what is to be supported: building or being able to run a built application. A developer can choose the OS used for building, but very often they have no power over which OS will be used to run the application which was built by crystal. 

I think to remember there was once an issue regarding (runtime) support for Windows 7, where the question, whether OS support should refer to building or running crystal applications already came up

**Comment by straight-shoota** [comment]
@kjarex Yes that's a good point. And in fact, we're mainly talking about another, even less critical level of support: What we provide official packages for.

Specifically https://github.com/crystal-lang/distribution-scripts/issues/228 is only about the packaging, which the way we're building them requires or would be easier to achieve if we drop support for macOS 10.

That would just mean our release builds are expected to work only on macOS 11+. But the compiler and stdlib are still fully compatible with older OS versions. You just won't get a compatible version of `libpcre2` and the compiler from the official distribution packages.

**Comment by HertzDevil** [comment]
#8919 and #10768 are some examples of Linux features requiring relatively recent kernel versions

**Comment by straight-shoota** [comment]
It's worth noting they're completely optional, though. A matching linux kernel is only required if you you use `copy_file_range` or `io_uring` explicitly.

**Comment by straight-shoota** [comment]
Some questions/notes:

* We can probably drop the *Compiler*/*Std* columns. They don't add any real value (at least for the higher tiers) and take up space.
* The interpreter is another platform that's not listed here. It technically doesn't have a specific target triple (it's just the one of the host). Should we use `interpreted` for that?
* For practical reasons, it's not a good idea to duplicate entries for unsupported OS versions in lower tiers. That would just be a lot of noise and hard to understand. Instead, a note that supported versions generally only covers supported OS versions should be enough. We can still give a minimum supported version in the same entry.
