### ISSUE TITLE
Deletion of symbolic link directories is inconsistent across systems

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#13194]
The following will raise only on Windows, not on Unix-like systems:

```crystal
Dir.mkdir("foo")
File.symlink("foo", "bar")
File.delete("bar") # Error deleting file: 'bar': Permission denied (File::AccessDeniedError)
```

Whereas the opposite holds for the following:

```crystal
Dir.mkdir("foo")
File.symlink("foo", "bar")
Dir.delete("bar") # Unable to remove directory: 'bar': Not a directory (File::Error)
```

This might be due to the fact that "is a symbolic link" and "is a directory" are two distinct properties on Windows, rather than two values of a single property in POSIX. This is affecting the following spec since `FileUtils.rm_r` always calls `File.delete` on symlinks:

https://github.com/crystal-lang/crystal/blob/c931553785487e6139213bd4beb688ee9a82562d/spec/std/file_utils_spec.cr#L242-L265

What is the desired behavior here?

**Comment by jhass** [comment]
I think these are basically trying to mirror `rm`/`rmdir`. How does CMD `del`/`rmdir` behave in these situations?

I'd err on the UNIX side of things.

**Comment by straight-shoota** [comment]
I think we should stick with the current semantics, which are obviously inspired by Unix tools, and implement the same behaviour on Windows.

**Comment by HertzDevil** [comment]
That's relatively easy for `FileUtils.rm_r`, but what about `{File,Dir}.delete` themselves?

**Comment by straight-shoota** [comment]
Looks good. The behaviour of works vs. does not work is identical on Windows on POSIX when expanding the `N/A` type into `File` and `Directory`.
