### ISSUE TITLE
`Socket::IPAddress.valid?` does not always work

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#13191]
The following should return `true`, but it returns `false` on some Windows versions:

```crystal
Socket::IPAddress.valid_v6?("::1:2:3:4:5:6:7")
```

Apparently [Windows Server 2022 fixed this](https://github.com/crystal-lang/crystal/pull/11794), but it might be better to port `LibC.inet_pton` to pure Crystal. Some reference implementations: [glibc](https://github.com/lattera/glibc/blob/master/resolv/inet_pton.c), [musl](https://git.musl-libc.org/cgit/musl/tree/src/network/inet_pton.c), [bionic](https://android.googlesource.com/platform/bionic/+/a27d2baa/libc/inet/inet_pton.c)

**Comment by meatball133** [comment]
I tried this on my machine and it returns true as well. I am running windows 11

**Comment by straight-shoota** [comment]
It definitely failed before the CI update to Windows Server 2022, that is on Windows Server 2019. Not sure where that leaves Windows 10 because both server releases are based on that. But it is safe to assume it failed on some earlier version of the desktop OS as well.

**Comment by HertzDevil** [comment]
According to the specs in `spec/std/socket/address_spec.cr`, glibc and Darwin also have their own failing cases
