### ISSUE TITLE
the IP 169.254.169.254 is not recognized as as a Private IP

### ISSUE THREAD

**Issue by weirdbricks** [crystal-lang/crystal#13198]
Hi, 

This is following up from this issue on the forums: https://forum.crystal-lang.org/t/shouldnt-the-ip-address-169-254-169-254-be-a-private-ip/5484

Per @Blacksmoke16, I have created this as an issue.

I have a script that checks whether an IP is public or private. Here are the important bits from `crystal i`:

```
Crystal interpreter 1.7.2 (2023-01-23).
EXPERIMENTAL SOFTWARE: if you find a bug, please consider opening an issue in
https://github.com/crystal-lang/crystal/issues/new/
icr:1> require "socket"
 => nil
icr:2> ip_address = Socket::IPAddress.new("169.254.169.254", 0)
 => Socket::IPAddress(169.254.169.254:0)
icr:3> ip_address.private?
 => false
```

I was expecting that the IP `169.254.169.254` would be recognized as a private IP.

This is reproducible on : 
* Mac OS X (Ventura 13.2.1) using Crystal 1.7.2
* Ubuntu 22.04.2 LTS and Crystal 1.7.3

Please let me know if I can provide any other details.

Thank you!

**Comment by Blacksmoke16** [comment]
Crosspost from the forums:

Looking at the [code](https://github.com/crystal-lang/crystal/blob/c931553/src/socket/address.cr#L244), it seems we're currently only handling the ranges defined in [RFC1918](https://www.rfc-editor.org/rfc/rfc1918#section-3) and are missing those defined in [RFC6890](https://www.rfc-editor.org/rfc/rfc6890.html#section-2.2.2) as `Reserved-by-Protocol`, specifically:

IPV4:

* `0.0.0.0/8`
* `127.0.0.0/8`
* `169.254.0.0/16` (which is the range your IP is in)
* `240.0.0.0/4`

IPV6:

* `::1/128`
* `::/128`
* `::ffff:0:0/96`
* `fe80::/10`

**Comment by GeopJr** [comment]
FWIW, in ruby `169.254.0.0/16` is under [`#link_local?`](https://github.com/ruby/ruby/blob/c65d7b4bea170ffe4811534ab33b231f7f57d69f/lib/ipaddr.rb#L280-L293) which Crystal is missing

```crystal
# Returns `true` if this IP is a link-local address.
#
# IPv4 addresses in `169.254.0.0/16` reserved by [RFC 3927](https://www.rfc-editor.org/rfc/rfc3927) and Link-Local IPv6
# Unicast Addresses in `fe80::/10` reserved by [RFC 4291](https://tools.ietf.org/html/rfc4291) are considered link-local.
def link_local?
  case addr = @addr
  in LibC::InAddr
    addr.s_addr & 0x000000ffff_u32 == 0x0000fea9_u32 # 169.254.0.0/16
  in LibC::In6Addr
    ipv6_addr8(addr)[0] & 0xffc_u16 == 0xfe8_u16
  end
end
```

(I'm pretty sure I messed something up on ipv6 because `fe80::dead:beef:cafe:1234` returns false in Crystal [but true in Ruby](https://github.com/ruby/ruby/blob/c65d7b4bea170ffe4811534ab33b231f7f57d69f/test/test_ipaddr.rb#L445))

**Comment by compumike** [comment]
@GeopJr Yes I think there's a small bug in your IPV6 handling because `ipv6_addr8(addr)[0]` will only be a single byte.

How about this instead:

```crystal
# Returns `true` if this IP is a link-local address.
#
# IPv4 addresses in `169.254.0.0/16` reserved by [RFC 3927](https://www.rfc-editor.org/rfc/rfc3927) and Link-Local IPv6
# Unicast Addresses in `fe80::/10` reserved by [RFC 4291](https://tools.ietf.org/html/rfc4291) are considered link-local.
def link_local?
  case addr = @addr
  in LibC::InAddr
    addr.s_addr & 0x000000ffff_u32 == 0x0000fea9_u32 # 169.254.0.0/16
  in LibC::In6Addr
    ipv6_addr8(addr).unsafe_as(UInt128) & 0xc0ff_u128 == 0x80fe_u128
  end
end
```

Since the UInt128 is parsed least-significant-byte first, then the most significant byte of the IP address interpretation ends up as the least significant byte of the integer interpretation. So this code checks that the first 10 bits of the IP address in network order (bits 0xc0ff of the integer) match `fe80`.

**Comment by straight-shoota** [comment]
I think the categorization of `169.254.*.*` as non-private is correct. It's a link-local address, not a private one. [RFC 6890](https://www.rfc-editor.org/rfc/rfc6890#page-6) makes a distinction between *Private-use* and *Link local* address spaces.
Those are different categories, although there's some overlap in that they both belong to the broader term of private networking. See https://en.wikipedia.org/wiki/Private_network for example: It names both private addresses and link-local addresses as instances of private networking.

This Wikipedia article also claims that loopback addresses as a special case are both private and link-local. Technically, that may be correct, but I'm not sure anyone uses it that way. [RFC 6890](https://www.rfc-editor.org/rfc/rfc6890#page-6) names *Loopback* as another category alongside *Private-use* and *Link local*. Ruby also considers them distinct.

So I think this is not a bug. The behaviour of `IPAddress#private?` is correct.

We may still want to add `IPAddress#link_local?` (https://github.com/crystal-lang/crystal/pull/13204) and consider a method that combines recognition of any special purpose address, regardless of the exact type.

**Comment by weirdbricks** [comment]
thanks @straight-shoota - for my purposes adding a `IPAddress#link_local?` works great! (and thank you to everyone else as well!)

**Comment by weirdbricks** [comment]
Hi! Will this make it into 1.8.0 ? I’m currently using a workaround but it would be great to use this instead :)

**Comment by weirdbricks** [comment]
Hi, 
As far as I’m concerned my issue is resolved. Thank you so much @GeopJr ! 
I’ll go ahead and close this out, feel free to reopen it if you have any reason to.
