### ISSUE TITLE
Inconsistent formatting between empty block and `ProcLiteral` 

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#13232]
The formatter prefers <code>foo&nbsp;{&nbsp;}</code>, but `->{}`; there is no space before and inside the `{}`. I would prefer if the latter is formatted into <code>->&nbsp;{&nbsp;}</code>.

The spaces are added when something else is present:

```crystal
->{}
->{ 1 }
->(x : Int32) {}
->(x : Int32) { 1 }
-> : Int32 {}
-> : Int32 { 1 }
```

Ideally they should be something like this:

```crystal
-> { }
-> { 1 }
->(x : Int32) { }
->(x : Int32) { 1 }
-> : Int32 { }
-> : Int32 { 1 }
```

**Comment by straight-shoota** [comment]
I don't mind the shortened form. But I'm also okay with adding some white space.

**Comment by HertzDevil** [comment]
Same goes for `do`:

```crystal
-> do
end

# gets formatted into:

->do
end
```
