### ISSUE TITLE
Regex may crash when matching invalid UTF-8 string

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#13237]
Crystal strings are supposed to be UTF-8, but that's not enforced and strings can actually contain bytes that are not valid UTF-8.

In bindings for the the regex engine the subject string is declared to be UTF-8 and we're opting out of any validation in the library for (`PCRE_NO_UTF8_CHECK`, `PCRE2_NO_UTF_CHECK`) for performance reasons. The documentation for both library versions clearly state that if you pass that flag and the string is actually invalid UTF-8, the behaviour is undefined and can lead to a crash or infinite loop (https://www.pcre.org/original/doc/html/pcreunicode.html, https://www.pcre.org/current/doc/html/pcre2unicode.html).
In most cases, it appears to be working fine. But there can definitely be crashes.
An example is `/\w/.match("\xFF\xFE")` which results in a segfault with PCRE2. This particular example is fine with PCRE, but there are certainly other cases where it will break in a similar way.

If we do *not* pass the flags to disable UTF checks, the library will validate the input strings. Alternatively, we could also validate them in Crystal (`String#valid_encoding?`), depending on which is faster.
But this also breaks some existing specs which explicitly expect invalid UTF strings to work in some way.

```
crystal spec spec/std/regex_spec.cr:134 # Regex #match_at_byte_index multibyte index
crystal spec spec/std/regex_spec.cr:213 # Regex #matches? unicode invalid codepoint
crystal spec spec/std/regex_spec.cr:257 # Regex #matches_at_byte_index? multibyte index
```

PCRE2 has another option `PCRE2_MATCH_INVALID_UTF` which does not validate the input and makes sure it does not crash when it encounters invalid UTF-8.
This seems to represent pretty well the intention of `Regex` behaviour and most specs pass. The only failure is `/f.o/.matches?("f\x96o").should be_true` because with `PCRE2_MATCH_INVALID_UTF` a non-UTF byte does not match anything at all. The input string is basically split into fragments with invalid bytes as separators.

I think this should be acceptable, though.

One question is what to do about PCRE: It seems to be impossible to achieve a similar behaviour as PCRE2 because there's not equivalent to `PCRE2_MATCH_INVALID_UTF`. We could leave `PCRE_NO_UTF8_CHECK` in place to avoid breaking existing behaviour, or remove it to avoid catastrophic failure.

And another question is whether we should enable UTF validation for the regex pattern as well. The risk of getting invalid UTF is much higher for subject strings, because that's often coming from external sources. But patterns are typically defined in the source code and only a fraction of programs uses patterns given by the user at run time.
Still, it's probably best to be on the safe side and check the pattern in `Regex.new` as well.
We can certainly pass `NO_UTF8_CHECK` to the constructor for literals, and users could also be able to do that if they are sure the pattern is valid. This option member is currently undocumented, but that can change.

I did not do any benchmarks to gauge the performance effects. I think that shouldn't matter much. It's most important to get reasonable semantics.
I would expect `NO_UTF_CHECK` to have some gain over not using this flag, but not sure how much and how much `MATCH_INVALID_UTF` differs.

It's also worth noting that theoretically, the user could pass `Regex::Option::NO_UTF_CHECK` when executing a regex for a performance gain if the subject is known to be valid. 
However, this has no effect when used together with `MATCH_INVALID_UTF` which needs to be already passed when compiling the regex.

**Comment by bararchy** [comment]
@straight-shoota I got an example with standard LibPCRE: https://github.com/crystal-lang/crystal/issues/11669

**Comment by straight-shoota** [comment]
Turns out `PCRE2_MATCH_INVALID_UTF` was only introduced in 10.34 (https://github.com/PCRE2Project/pcre2/blob/512be06078bec9a3a941765900d566060aa5af8b/ChangeLog#L708-L710). So I guess we'll need a version guard for using `PCRE2_MATCH_INVALID_UTF` and the behaviour of invalid UTF-8 will be different between PCRE and PCRE2 < 10.34 on one side and PCRE2 >= 10.34 on the other.😑 (https://github.com/crystal-lang/crystal/pull/13240#issuecomment-1489316704)

In light of this we *could* reconsider if we want to avoid that flag to keep the behaviour consistent across all library versions (i.e. matching against invalid UTF-8 is always an error). 
Another catch is that there's currently no way to explicitly opt out of it because it's hard coded to the option params of `pcre2_compile`. This could be useful for increased performance if the subject is known to be valid UTF-8.
But I believe this option is actually pretty useful and a sensible default (when available). It would be a good idea to provide a means for opting out of it. This would mean to enable this option in the default value for `options` which allows users to pass an instances where it's unset.

**Comment by rdp** [comment]
Another option, maybe could enforce valid UTF-8 on all strings (a la rust?) :)

I ran into a related error message(s) recently, posting it here in case useful, with some comments:

After updating from 1.6 to 1.12, the following used to "just work" by default:
```
$ cat bad.cr
"\xE2\xE3\xCF\xD3".gsub(Regex.new("a"), "b")
$ crystal run bad.cr # with 1.12:
Unhandled exception: Regex match error: UTF-8 error: byte 2 top bits not 0x80 (ArgumentError)
  from /usr/share/crystal/src/regex/pcre2.cr:274:9 in 'match_data'
  from /usr/share/crystal/src/regex/pcre2.cr:206:18 in 'match_impl'
  from /usr/share/crystal/src/regex.cr:614:12 in 'match_at_byte_index'
  from /usr/share/crystal/src/string.cr:2870:13 in 'gsub'
  from bad.cr:1:1 in '__crystal_main'
# or with pcre1
$ crystal run bad.cr -Duse_pcre
Unhandled exception: Regex match error: UTF-8 error (ArgumentError)
  from /usr/share/crystal/src/regex/pcre.cr:196:7 in 'internal_matches?'
  from /usr/share/crystal/src/regex/pcre.cr:174:8 in 'match_impl'
  from /usr/share/crystal/src/regex.cr:614:12 in 'match_at_byte_index'
  from /usr/share/crystal/src/string.cr:2870:13 in 'gsub'
  from bad.cr:1:1 in '__crystal_main'
  ...
```

Based on the conversation, it appears NO_UTF8_CHECK was removed as the match default since it can lead to "undefined" behavior.

This option above works "if your pcre2 is new enough":
```
"\xE2\xE3\xCF\xD3" =~ Regex.new("a", Regex::CompileOptions::MATCH_INVALID_UTF) # no failure with recent pcre2
```
If installed pcre2 isn't new enough it'll raise this at runtime:
```
Unhandled exception: unrecognised compile-time option bit(s) at 0 (ArgumentError)
  from /usr/share/crystal/src/regex/pcre2.cr:27:7 in 'initialize:_source:_options'
  from /usr/share/crystal/src/regex/pcre2.cr:24:3 in 'new:_source:_options'
```
(not sure about the pcre2 version where it exists but doesn't work).

If attempted with pcre1 it'll raise the following:
```
Unhandled exception: Regex::Option::MATCH_INVALID_UTF is not supported with PCRE (ArgumentError)
  from /usr/share/crystal/src/regex/pcre.cr:52:19 in 'pcre_compile_options'
  from /usr/share/crystal/src/regex/pcre.cr:21:36 in 'initialize:_source:_options'
  from /usr/share/crystal/src/regex/pcre.cr:16:11 in 'new:_source:_options'
```

This way works for pcre1 and pcre2, regardless of version (assuming you use gsub or something that takes MatchOptions etc.):
```
"\xE2\xE3\xCF\xD3".gsub(Regex.new("a"), "b", options: Regex::MatchOptions::NO_UTF_CHECK)
```

For some reason specifying it as a Regex compile option doesn't work...
```
"\xE2\xE3\xCF\xD3" =~ Regex.new("a", Regex::CompileOptions::NO_UTF_CHECK) # same "Regex match" errors with pcre1 and pcre2
```
Unrelated: it'd be nice to somehow list the location along with the Regex match error messages, if that's possible, instead of the generic "it's in there somewhere!"

Hopefully this can be useful for followers who may run into the same issue.

Cheers!

**Comment by straight-shoota** [comment]
@rdp RTFM 😝 

The API docs for [`Regex::Options::MATCH_INVALID_UTF`](https://crystal-lang.org/api/1.12.1/Regex/Options.html#MATCH_INVALID_UTF) explain when it can be used (effectively with PCRE2 >= 10.36).
The constant is defined in the Crystal stdlib, so it always "exists" regardless of which pcre version is linked.

The API docs for [`Regex::Options::NO_UTF_CHECK`](https://crystal-lang.org/api/1.12.1/Regex/Options.html#NO_UTF_CHECK) clearly state that it applies to the **pattern**, while [`Regex::MatchOptions::NO_UTF_CHECK`](https://crystal-lang.org/api/1.12.1/Regex/MatchOptions.html#NO_UTF_CHECK) applies to the **subject**. PCRE validates the pattern before compiling it and you can pass the option to skip that.
`String#gsub` implicitly passes `NO_UTF_CHECK` for all but the first match btw.

> Unrelated: it'd be nice to somehow list the location along with the Regex match error messages, if that's possible, instead of the generic "it's in there somewhere!"

Which location do you refer to?

**Comment by rdp** [comment]
Here's an example of what it looks like when it crashes with gsub on a binary string with NO_UTF_CHECK:

```
Invalid memory access (signal 11) at address 0x792ec25e31f6
[0x622b7f26af86] *Exception::CallStack::print_backtrace:Nil +118 in ../executable
[0x622b7f257d06] ~procProc(Int32, Pointer(LibC::SiginfoT), Pointer(Void), Nil) +310 in ../executable
[0x792ec1e42520] ?? +133241728410912 in /lib/x86_64-linux-gnu/libc.so.6
[0x792ec1cf69ed] ???
```
I guess that's expected?  The library just doesn't handle it well and blows up?

If that's the case I'd be in favor of forcing all strings to be valid UTF-8, it puts a pretty decent burden on the developer to assert that "all"incoming data is valid encoded...and if not it's not a simple backtrace to even figure out where it died :) Peace!

**Comment by straight-shoota** [comment]
`NO_UTF_CHECK` comes with a warning that the caller is responsible to ensure the string contains only valid encodings.
If you choose to use `NO_UTF_CHECK` without safety checks, the crash is on you.

**Comment by ysbaddaden** [comment]
The documentation is indeed very explicit: https://crystal-lang.org/api/1.21.0/Regex/MatchOptions.html#NO_UTF_CHECK

**Comment by Sija** [comment]
Perhaps it would make sense to apply it automatically with `valid_encoding?` check?

**Comment by straight-shoota** [comment]
What would be the benefit of that? Whether we check `valid_encoding?` or let PCRE2 check that, shouldn't make a significant difference.

The use case for `NO_UTF_CHECK` is when you already know that a string contains only valid encoding, so we can skip the check in PCRE2.

There could be an argument to move the check into Crystal if we would store `valid_encoding?` so we only need to calculate once per string instance (ref #12020).

**Comment by Sija** [comment]
I thought it might result in performance improvements for valid encodings.
