### ISSUE TITLE
Proposing adding a Trie to the stdlib

### ISSUE THREAD

**Issue by MattAlp** [crystal-lang/crystal#13258]
### Is your feature request related to a problem? Please describe clearly and concisely what is it.

I had to implement a trie in Crystal the other day, and thought it could be useful to design a more advanced version for the stdlib.

### Describe the feature you would like, optionally illustrated by examples, and how it will solve the above problem.

I would be interested in seeing a Trie class that can take on any generic `Enumerable`, `Indexable`, `Iterable` and creating a recursive hash structure for fast lookups on a sequence. I began by writing an example for my use case (domain name parsing, with some custom string manipulation and tokenization), and later made a more [generic, barebones implementation](https://github.com/MattAlp/simple-trie) with only lookup and insertion support.

If this was to be an accepted feature / DS in the stdlib, I would be interested in adding things like block support to insertion, deletion, and lookup, depth checking (i.e. the first n tokens were found), wildcard lookup. Additionally, I would be interested in discussing how to make the trie performant, as my current approach doesn't go beyond using `fetch` for fast nested hash traversal.

### Describe considered alternative solutions, and the reasons why you have not proposed them as a solution here

I found https://github.com/c910335/crie, which is a comptime trie. I am interested in a data structure that can be initialized at runtime and dynamically populated.

### Does it break backward compatibility, if yes then what's the migration path?

As far as I can tell, this only relies on
- `alias` (for the recursive hash)
- `Hash`
- `Iterable`

Backporting may be an issue for some of those features, but I don't believe this should be a breaking change because I'm proposing a brand new class.

**Comment by Blacksmoke16** [comment]
If recursive hash types are going to be involved, that would kind of conflict with https://github.com/crystal-lang/crystal/issues/5155.

**Comment by MattAlp** [comment]
That makes sense. I see that that discussion has been going on since 2017, and proposes a way to introduce similar recursion functionality with structs. If we were to implement the rest of the Trie and introduce it to the stdlib, we could use recursive hash types and refactor into the struct form if/when #5155 is settled?

**Comment by yxhuvud** [comment]
Technical considerations aside, are the problem tries solve really common enough to motivate inclusion in stdlib as opposed to having the implementation in a shard?

**Comment by konovod** [comment]
Speaking about alternatives, there is a [Radix tree](https://github.com/luislavena/radix) implementation. It is used by [Kemal](https://github.com/kemalcr/kemal) and is pretty performant. It is oriented on string lookups, not general Iterables, though.

**Comment by MattAlp** [comment]
@yxhuvud - I'm not sure. It seems like a common-enough data structure, though I asked the same thing. I searched for issues in the repo but found no prior discussion.

**Comment by Sija** [comment]
@MattAlp As you've already noticed there were no issues, nor requests for it until now, i.e. there's no (widespread) interest to include it in the stdlib. Having it as a shard seems good enough.

**Comment by MattAlp** [comment]
Cool. If people want it in the future they can refer back to this issue to voice interest.

**Comment by watzon** [comment]
If you're looking for a trie library cadmium actually has one, it hasn't been looked at in a while so it may need updates, but submitting a PR there would be a much more surefire way to get what you're looking for. https://github.com/cadmiumcr/trie
