### ISSUE TITLE
Inconsistent Iterator::Cycle behavior on 1.7+

### ISSUE THREAD

**Issue by Andriamanitra** [crystal-lang/crystal#13263]
## Bug Report

When using the `Enumerable#zip` method with a cyclical iterator, the cycle gets stuck at the first element after exhausting the array once.

Minimal reproduction:
```crystal
# this returns [1, 2, 3, 1, 2, 3, 1, 2, 3, 1] as expected
p! [1, 2, 3].cycle.first(10).to_a

# however with .zip([1, 2, 3].cycle) we get [1, 2, 3, 1, 1, 1, 1, 1, 1, 1]
p! (1..10).zip([1, 2, 3].cycle).map(&.last)

```

I ran into the issue on Crystal 1.7.3, and it still reproduces on master. I also tried 1.6.2 and 1.0.0, neither of which had the same issue.

**Comment by Andriamanitra** [comment]
After doing some bisecting I figured out the problem is caused by this change to the `Object#not_nil!` method (changing it back fixed the problem on master):

https://github.com/crystal-lang/crystal/commit/649f0614f09be92253afe6110e6e63a116150d75#diff-07f037fc0bf516181a1b483763bdb95c0c959879bac83c1cc7b643e4d258ab4c

I'm not sure *why* that particular change would have such an effect though...

**Comment by HertzDevil** [comment]
Apparently that PR makes `not_nil!` return a copy of the receiver when it is a struct:

```crystal
iter = [1, 2, 3].cycle
iter.not_nil!.next # => 1
iter.not_nil!.next # => 2
iter.not_nil!.next # => 3
iter.not_nil!.next # => 1
iter.not_nil!.next # => 1
iter.not_nil!.next # => 1
```

But technically it would not be wrong either if `iter.not_nil!` returns a copy of `iter`. Note that [`Iterator::CycleIterator` should not be a struct in the first place](https://github.com/crystal-lang/crystal/pull/12975#issuecomment-1387473652).

This is still a possible codegen issue that might affect non-`Iterator` types; [the issue itself exists all the way back to 1.0.0](https://godbolt.org/z/c7cz6h6zE).
