### ISSUE TITLE
Compile-time flag for docs generation

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#13266]
`Signal` contains many enum members that are only defined on certain platforms:

```crystal
enum Signal : Int32
  INT  = LibC::SIGINT
  ILL  = LibC::SIGILL
  FPE  = LibC::SIGFPE
  SEGV = LibC::SIGSEGV
  TERM = LibC::SIGTERM
  ABRT = LibC::SIGABRT

  {% if flag?(:win32) %}
    BREAK = LibC::SIGBREAK
  {% else %}
    HUP    = LibC::SIGHUP
    # ...

    {% if flag?(:linux) %}
      PWR    = LibC::SIGPWR
      STKFLT = LibC::SIGSTKFLT
      UNUSED = LibC::SIGUNUSED
    {% end %}
  {% end %}
end
```

We rely on `Signal`'s summary to indicate which members are available on which platforms, but this is still not ideal because the docs generator always uses the host target platform when scanning the source files; as the [official API docs](https://crystal-lang.org/api/master/Signal.html) are built with an x86_64-pc-linux-gnu compiler (indicated by `Crystal::DESCRIPTION`'s initializer), the Linux-exclusive members are always shown in the docs, and `Signal::BREAK` is always unavailable.

I am thinking if we could have a special compile-time flag that is defined only when building docs. Then we could do:

```crystal
enum Signal : Int32
  {% if flag?(:docs) %}
    # Available on all platforms.
    INT

    # Available only on Windows.
    BREAK

    # Available only on Unix-like platforms.
    HUP

    # Available only on Linux.
    PWR

    # _all_ other members, without initializers
  {% else %}
    # the existing platform-specific members
  {% end %}
end
```

Another possible use case is when a documented method signature differs from the actual one in the source code. For example we could document `Int32#+(other : Int::Primitive)` instead of the 10 distinct overloads over each primitive integer type.

Since `crystal docs` accepts `-D` / `--define`, the above is already possible. However, if we want to adopt this practice then `crystal docs` itself should be responsible for adding `-Ddocs`.

**Comment by straight-shoota** [comment]
This already works exactly like you're proposing here since #6668 and is actually used for pseudo method docs and to avoid parsing the entire compiler source tree for `Crystal::SyntaxHighlighter`.

> Another possible use case is when a documented method signature differs from the actual one in the source code. For example we could document `Int32#+(other : Int::Primitive)` instead of the 10 distinct overloads over each primitive integer type.

I agree that so many overloads are unnecessarily verbose. But I don't think it would be a good idea to suggest a fictional method signature in the docs. A better solution for this problem would be to group these defs (cf. https://github.com/crystal-lang/crystal/issues/1312#issuecomment-135806478).
