### ISSUE TITLE
API docs for `NoReturn` and `Void` are missing

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#13272]
The stdlib API documentation has no entry for `NoReturn` and `Void`.
They are special types defined by the compiler, but we usually document those in the API docs as well for completeness.
The language specification has a section about it: https://crystal-lang.org/reference/1.7/syntax_and_semantics/return_types.html

There's a significant roadblock: `NoReturn` and `Void` are special kinds of types and cannot be reopened in code which would be necessary to attach a doc comment. So we'll probably need to implement some kind of workaround in the doc generator to make it possible. Maybe something similar to #8327.

Edit: Added `Void` (originally, it was only about `NoReturn`).

**Comment by devnote-dev** [comment]
This should also include `Void` which is mentioned in the C Bindings section next to `NoReturn`.

**Comment by HertzDevil** [comment]
#8422 is also a possible solution (you could define class methods on `NoReturn` just fine so there is a use case for that)
