### ISSUE TITLE
Official way to interoperate with Ruby (preferrable as a gem scaffold)

### ISSUE THREAD

**Issue by alexanderadam** [crystal-lang/crystal#13271]
## Feature Request

I guess we all see this popping up every now and then on social media or when chatting with other developers.
People are asking for a working way to interact with Ruby and it would surely bring some developers to make their first steps with Crystal.

There seem to be many half baked solutions and examples, many of them abandoned (i.e. [here](https://github.com/phoffer/crystalized_ruby), [here](https://github.com/manastech/crystal_ruby), [here](https://gist.github.com/notozeki/7159a9d9ab9707a22129), [here](https://github.com/gaar4ica/ruby_ext_in_crystal_math), [here](https://www.akitaonrails.com/2016/07/06/trying-to-match-c-based-fast-blank-with-crystal), [here](https://github.com/ahrushetskyi/polycrystal) or [here](https://c7.se/go-and-ruby-ffi/#bonus-round-binding-directly-from-crystalhttpcrystal-langorg-no-need-for-ffi)).

But I guess having people reinvent a similar thing to achieve the same goal over and over again is not very efficient.
Maybe an official scaffold [like the Rust integration in bundler](https://bundler.io/blog/2023/01/31/rust-gem-skeleton.html) would be nice.

**PS:** I'm sorry in case this issue or discussion already exists but I wasn't able to found it. I just know that I had this topic often on Twitter and in the Fediverse :wink:

**Comment by Blacksmoke16** [comment]
Checkout https://forum.crystal-lang.org/t/embeddable-interoperable-with-ruby/4894 and https://forum.crystal-lang.org/t/ruby-interop/2074.

Quoting my comment from one of those threads:

> This sounds like a noble goal but I don’t see this something the core team would work on. Crystal and Ruby are different languages and a goal of Crystal itself is not being compatible with Ruby. If you or someone else wants to work on a third party compatibility layer or something that could be handy, but I wouldn’t bank on it being an official project. Just my 2 cents.

Feel free to continue the discussion on the forums, but I don't think there's anything really actionable here so I'm going to close.
