### ISSUE TITLE
Unexpected functionality when reopening `Proc`

### ISSUE THREAD

**Issue by devnote-dev** [crystal-lang/crystal#13288]
Reference: https://forum.crystal-lang.org/t/suggest-an-syntactic-suger-for-call/5537

In the process of implementing `Proc#[]` I accidentally wrote `class Proc(*T, R)` which gave the following error message: `Error: Proc is not a class, it's a function`; in actuality, it's a struct. Is this intentional, and if so, why?

Trying to access the generic type parameters in `Proc` is also not consistent. For example, the following code does not compile:
```crystal
struct Proc(*T, R)
  {% begin %}
    def [](
      {% for i in T.size %}
        __arg{{i}} : {{T[i]}},
      {% end %}
    ) : R
      call(
        {% for i in T.size %}
          __arg{{i}},
        {% end %}
      )
    end
  {% end %}
end

echo = ->(text : String) { puts text }
echo["Hello world"]
```
```crystal
In test.cr:4:19

 4 | {% for i in T.size %}
                 ^
Error: undefined constant T
```

However, this does compile:
```crystal
struct Proc(*T, R)
  def return_type : R
    {{R}} # `R.class` works here too
  end
end

echo = ->(text : String) { puts text }
puts echo.return_type # => nil
```

I'm lost as to how to make `Proc#[]` work, or if it's even possible. Thoughts?

**Comment by HertzDevil** [comment]
`T` is never instantiable at the macro scope, unless it is inside an already instantiated def. This is intentional. Just do:

```crystal
struct Proc(*T, R)
  def [](*args : *T) : R
    call(*args)
  end
end
```

**Comment by straight-shoota** [comment]
I also explained why the code does not work as intended in https://forum.crystal-lang.org/t/suggest-an-syntactic-suger-for-call/5537/5

**Comment by straight-shoota** [comment]
Regarding the issue with re-opening, there's #8422

`Proc is not a class, it's a function` seems weird. But yeah that's what `ProcType#type_desc` return's 🤷

**Comment by devnote-dev** [comment]
Sorry, I hadn't looked back at the forum just yet. 😅 Technically the error message isn't wrong, and I don't think that reopening a `Proc` is exactly common practice so I guess it's not really of concern.
