### ISSUE TITLE
Missing typeof for BigInts

### ISSUE THREAD

**Issue by jzakiya** [crystal-lang/crystal#13299]
There is no `typeof` method for BigInts.
This fails if b is a BigInt

```
b = b % m
b = b.typeof(m).new(b)


In powmod-test.cr:20:9

 20 | b = b.typeof(m).new(b)
            ^-----
Error: undefined method 'typeof' for BigInt
```

**Comment by yxhuvud** [comment]
There is no `typeof` method for anything else either. What output do you expect of `b.typeof(m)`. Regular `typeof`, ie `typeof(BigInt.new(4)).new(2)` works,

**Comment by jzakiya** [comment]
Of course their is. This works for all numeric types except `BigInt's
https://crystal-lang.org/api/1.7.3/toplevel.html#typeof(*expression):Class-class-method

**Comment by Blacksmoke16** [comment]
As @yxhuvud `typeof` is a top level method. Not something you call on a specific object.
