### ISSUE TITLE
Heredoc adding additional '\r' before '\r\n' pair for newlines on Windows?

### ISSUE THREAD

**Issue by mdwagner** [crystal-lang/crystal#13304]
## Reproduction

file-a.cr
```crystal
{{ run("./file-b") }}
```

file-b.cr
```crystal
a = <<-TEXT
x = 1
y = 2
puts x + y
TEXT

puts a
```

Compiler message:
```
Error: expected '\n' after '\r'
```

System info:
```
Crystal 1.7.3 [d61a01e] (2023-03-07)

LLVM: 13.0.1
Default target: x86_64-pc-windows-msvc
```

Context:
I first discovered this when calling the `run` macro on a file that outputs pre-compiled crystal code, and it fails to continue because Heredoc newlines are being output as '\r\r\n', and the compiler is only expecting '\r\n'. This only seems to be an issue on Windows at the moment from what I can tell.

**Comment by HertzDevil** [comment]
How was `file-b.cr` generated in the first place?

**Comment by mdwagner** [comment]
In this small reproduction, file-b.cr would have been generated on Windows. But I first discovered this issue from [this file](https://github.com/luckyframework/teeplate/blob/main/src/lib/file_tree/macros/directory.cr) as a part of luckyframework/teeplate, which would have been generated on either Mac or Linux.

**Comment by sdogruyol** [comment]
Hitting this on a newly generated Kemal project using `exception_page` 
https://github.com/crystal-loot/exception_page/issues/36

**Comment by straight-shoota** [comment]
I can someone provide a reduced example? I cannot reproduce the error reported in the OP.

**Comment by jwoertink** [comment]
The exception page code seems to point to

```
<%-
monospace_font = "menlo, consolas, monospace"
-%>
```

So maybe somewhere in ECR land?

**Comment by mdwagner** [comment]
@HertzDevil I tried your suggestions (running the formatter on the files, setting the git config autocrlf, and adding .gitattributes) and I still get this error:
![image](https://user-images.githubusercontent.com/13472976/233100588-bf3586b9-7e42-40bc-96ae-2bf07206bb5b.png)

This is still Crystal 1.7.3, I have not tried with Crystal 1.8.0 yet.

**Comment by HertzDevil** [comment]
This seems to be a general issue with `Process.run`, which backs the macro `run`. The following recreates the same bug on Windows, regardless of the source files' line endings:

```crystal
# file-b.cr
# `LibC.printf "%s"` also reproduces the same thing
puts "x = 1\r\ny = 2\r\nputs x + y"
```

```crystal
# file-a.cr
`file-b.exe` # => "x = 1\r\r\ny = 2\r\r\nputs x + y\r\n"

io = IO::Memory.new
Process.run("file-b.exe", output: io)
io.to_s # => "x = 1\r\r\ny = 2\r\r\nputs x + y\r\n"
```
