### ISSUE TITLE
Windows Process.on_interrupt undefined

### ISSUE THREAD

**Issue by dsisnero** [crystal-lang/crystal#13302]
## Bug Report

f:\programming\source\repos\git\dsisnero\crystal_examples\chatgpt-cli>crystal env
CRYSTAL_CACHE_DIR="C:\Users\Dominic E Sisneros\AppData\Local\crystal\cache"
CRYSTAL_PATH=lib;F:\windows\scoop\apps\crystal\current\src
CRYSTAL_VERSION=1.7.3
CRYSTAL_LIBRARY_PATH=F:\windows\scoop\apps\crystal\current\lib
CRYSTAL_OPTS=""

trying to use Process.on_interrupt but getting undefined method

```
Building: chatgpt
   Creating library C:\Users\Dominic E Sisneros\AppData\Local\crystal\cache\F-windows-scoop-apps-crystal-current-src-ecr-process.cr\macro_run.lib and object C:\Users\Dominic E Sisneros\AppData\Local\crystal\cache\F-windows-scoop-apps-crystal-current-src-ecr-process.cr\macro_run.exp
Error target chatgpt failed to compile:
Showing last frame. Use --error-trace for full trace.

In src\chatgpt\client.cr:60:15

 60 | Process.on_interrupt do |p|
              ^-----------
Error: undefined method 'on_interrupt' for Process.class
```

**Comment by HertzDevil** [comment]
This method is only available on master. You will get it on 1.8.0
