### ISSUE TITLE
Benchmark bugs

### ISSUE THREAD

**Issue by jzakiya** [crystal-lang/crystal#13300]
`Benchmark` produces these errors in the following code, whose methods works outside of the benchmark.

```
require "big"
require "benchmark"

@[Link("gmp")]
lib LibGMP
  fun mpz_powm_sec = __gmpz_powm_sec(rop : MPZ*, base : MPZ*, exp : MPZ*, mod : MPZ*)
end

def powmodgmp(b, e, m)
  y = BigInt.new
  LibGMP.mpz_powm_sec(y, b.to_big_i, e.to_big_i, m.to_big_i)
  y
end

def _powmod(b, e, m)
  r, b = typeof(m).new(1), b % m
  while e > 0
    r = (r &* b) % m if e.odd?
    e >>= 1
    b = (b &* b) % m
  end
  r
end

def powmod(b, e, m)
  b = b % m
  if m.class != "BigInt"
    b = typeof(m).new(b)
    _powmod(b, e, m)
  else
    powmodgmp(b, e, m)
  end
end

def powmodtests(b, e, m)
  Benchmark.ips do |b|
    b.report("powmodgmp") { powmodgmp(b, e, m) }
    b.report("powmod")    { powmod(b, e, m) }
    b.compare!
    puts
  end
end
```
When compiling as is it gives this error.

```
In powmod-test.cr:11:28

 11 | LibGMP.mpz_powm_sec(y, b.to_big_i, e.to_big_i, m.to_big_i)
                               ^-------
Error: undefined method 'to_big_i' for Benchmark::IPS::Job
```

When I comment out the `powmodgmp` line it then give this error.

```
In powmod-test.cr:26:9

 26 | b = b % m
            ^
Error: undefined method '%' for Benchmark::IPS::Job
```

**Comment by Blacksmoke16** [comment]
Is this actually a bug tho? You have `Benchmark.ips do |b|` and you're passing `b` into your `powmodgmp` and `powmod` methods. Seems to me that this is simply an issue of shadowing var names where the `.ips` block's `b` is overriding the `b` parameter to `powmodtests`.

**Comment by jzakiya** [comment]
Yes, that was my oversight. This can be closed.

**Comment by jzakiya** [comment]
After if made the appropriate changes the benchmarks still don't run and now give this error for any input.

```
Program received and didn't handle signal FPE (8)

```

**Comment by Blacksmoke16** [comment]
> Floating point exception. The FPE signal is sent to a process when it executes erroneous arithmetic operations, such as division by zero.

I'd maybe check the inputs to `LibGMP`? Given it's raising that signal it might be coming from there versus the Crystal code itself.

**Comment by jzakiya** [comment]
Yes, that's the problem, but I don't know why.
When I hard code values for it in the benchmark it works.
And when I run the other one by itself it works.
So I don't know why those values aren't assigned to it inside the benchmark.

**Comment by Blacksmoke16** [comment]
What inputs are you using?

**Comment by jzakiya** [comment]
This is minimal code.
If you comment out the test for `powmodgmp` the benchmark runs the test for `powmod` with the inputs.
But for `m` a `BigInt` here, `powmod` uses the branch with `powmodgmp`.
So this seems like a parsing error for `Benchmark`??

```
require "big"
require "benchmark"

@[Link("gmp")]
lib LibGMP
  fun mpz_powm_sec = __gmpz_powm_sec(rop : MPZ*, base : MPZ*, exp : MPZ*, mod : MPZ*)
end

def powmodgmp(b, e, m)
  y = BigInt.new
  LibGMP.mpz_powm_sec(y, b.to_big_i, e.to_big_i, m.to_big_i)
  y
end

def powmodint(b, e, m)
  r = typeof(m).new(1)
  while e > 0
    r = (r &* b) % m if e.odd?
    e >>= 1
    b = (b &* b) % m
  end
  r
end

def powmod(b, e, m)
  b = b % m
  if m.class != "BigInt"
    b = typeof(m).new(b)
    powmodint(b, e, m)
  else
    powmodgmp(b, e, m)
  end
end

def powmodtests(b, e, m)
  Benchmark.ips do |x|
    x.report("powmod")    { powmod(b, e, m) }
    x.report("powmodgmp") { powmodgmp(b, e, m) }
    puts
  end
end

puts
b = "329832983".to_big_i
e = 4843
m = "498422".to_big_i

puts "r = #{r = powmod(b, e, m)} of class #{r.class}"
powmodtests(b, e, m)
puts
```
Running it with 1.8.0 nightly it gives this error about floating point, though all the values are integers.

```
  crystal-projects ~/crystal-1.8.0-dev-1/bin/crystal run --release xxxtest.cr

r = 107323 of class BigInt

Program exited because of a floating-point system exception
```

**Comment by HertzDevil** [comment]
[`m` must be odd for `mpz_powm_sec`](https://gmplib.org/manual/Integer-Exponentiation). This has nothing to do with `Benchmark`

**Comment by jzakiya** [comment]
Yes, I just found that problem.

Using this works.
```
@[Link("gmp")]
lib LibGMP
  fun mpz_powm = __gmpz_powm(rop : MPZ*, base : MPZ*, exp : MPZ*, mod : MPZ*)
end

def powmodgmp(b, e, m)
  y = BigInt.new
  LibGMP.mpz_powm(y, b.to_big_i, e.to_big_i, m.to_big_i)
  y
end
```
Buts this has the problems.
```
@[Link("gmp")]
lib LibGMP
  fun mpz_powm_sec = __gmpz_powm_sec(rop : MPZ*, base : MPZ*, exp : MPZ*, mod : MPZ*)
end

def powmodgmp(b, e, m)
  y = BigInt.new
  LibGMP.mpz_powm_sec(y, b.to_big_i, e.to_big_i, m.to_big_i)
  y
end
```
It that a bug, or is that how its supposed to work?
Either way this needs to be documented (or corrected) because it was a $*##&@ PITA to figure out. :-)

**Comment by HertzDevil** [comment]
What needs to be documented?

**Comment by jzakiya** [comment]
There are a couple of things I was referring to that should be documented.

1) Somewhere, there should be documented a list of the `mpz` functions, e.g. `mpz_powm` that could be available to use.
And also, what the performance, et al, differences are between the `_sec` ones for security and `non _sec` ones.

2) It also should be documented (if it isn't a bug that should be fixed) that you can't use the `_sec` functions inside of `Benchmark` or `print` et al methods, as experienced here using `mpz_powm_sec`, which gave a `floating point` error?

It literally took me a day (a full 24 hours of head banging) before I figured out my benchmark code wasn't the problem but the `mpz_powm_sec` function wasn't usable in it.

You have to appreciate you all work with these things daily as devs, but I as a user don't know the implementation details, and really only (first) know what's available in the documentation. I'm learning allot from asking question here|forums but sometimes it's very painful to go long stretches of frustration when all I needed was one piece of information that wasn't documented.

**Comment by HertzDevil** [comment]
The moment you try to bind against GMP directly and outside the standard library, you are the one responsible for reading, well, GMP's documentation, not the standard library's authors. Don't you think so?

**Comment by jzakiya** [comment]
Of course, but I didn't formally know anything about them (where to get a list of them, how to wrap them for Crystal, etc).

If there's documentation for people who want to experiment (for whatever reasons) for performance, etc, it would be nice to have at least a cursory guide on how to do that and not blowup things.  Even Rust has a guide on how to write `non-safe` code, for those who want|think they need to do so (like wrapping other libraries).

Until you said that `_sec` meant `security`, and thus were slower than the `non _sec` one, I had no idea there was even a different version, or that using the `_sec` was the reason the Crystal code was so much slower than Ruby.

If you don't know, you don't even know you don't know.
