### ISSUE TITLE
Drop `MATCH_INVALID_UTF`

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#13312]
I believe enabling `MATCH_INVALID_UTF` by default was a bad idea (original discussion in #13237).

Most typical use cases deal with valid UTF where it has no meaning. But for these use cases it makes performance optimization more difficult, because `MATCH_INVALID_UTF` is a compile option. Passing it to `pcre2_compile` makes it impossible to skip UTF validation in `pcre2_match`.
If a subject is known to be valid UTF there's no need for validation. Skipping it enables a performance benefit. To do that you can pass `NO_UTF_CHECK` to the match method. But when regex are by default compiled with `MATCH_INVALID_UTF`, this won't have any effect unless you explicitly opt out of that flag at compile time as well.

`MATCH_INVALID_UTF` is only useful for edge cases when the subject string is invalid UTF but you still want *some* regex mechanism to work. But it works a bit quirky and probably quite unexpectedly.
In the previous behaviour, where UTF validation was skipped, invalid bytes were essentially treated as unknown characters and matched some regex expressions (with a risk of exploding). With `MATCH_INVALID_UTF` the subject is split into segments consisting of valid UTF characters. So that's already pretty different. The original intention of using `MATCH_INVALID_UTF` was to try to maintain the established semantics. I don't think it helps much for that. Instead it creates other problems.
And support is also spotty. It doesn't work with PCRE. It was introduced in PCRE 10.34, but it's seriously broken until 10.36 (https://github.com/crystal-lang/crystal/issues/13306#issuecomment-1506584169).

I'm proposing to drop `MATCH_INVALID_UTF` as default argument. We can add it as a member to `Regex::CompileOptions` allowing to opt-in for it if you wish to use it.
This allows an easy path for performance optimizations on subjects that are known to be valid UTF without having to manipulate compile time options for this.

**Comment by HertzDevil** [comment]
The ideal situation is that PCRE2 treats every byte which doesn't start a valid UTF-8 byte sequence as U+FFFD, because that's the behavior of Crystal's `String`. I don't think that is possible just yet.
