### ISSUE TITLE
`Log::Builder` adds `BroadcastBackend` to itself

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#13404]
When appending the same `BroadcastBackend` to a `Log::Builder` multiple times, it get's added to itself, causing infinite recursion.

```cr
require "log"

backend = ::Log::BroadcastBackend.new
backend.append(::Log::IOBackend.new, ::Log::Severity::Trace)

log_levels = {
  "a.*"   => ::Log::Severity::Info,
  "*"     => ::Log::Severity::Trace,
}

::Log.setup do |builder|
  builder.bind("a.*", :info, backend)
  builder.bind("*", :trace, backend)
end

log = ::Log.for("a.test")
backend.same?(backend.@backends.keys[1]) # => true

# Uncomment this line and the log entry dispatches forever (i.e. until the stack runs out)
# log.info { "boom!" }
```

The reason for this behaviour is that `Log::Builder#append_backend` tries to optimize and appends new backends to an existing `BroadcastBackend`.
This goes wrong when a broadcast backend is bound multiple times and thus ends up binding to itself.

https://github.com/crystal-lang/crystal/blob/8c76ff16ed109aff2d06b9a12cf09fda6ef7f542/src/log/builder.cr#L103-L104

That bug is easy to fix, but I'm also irritated by this behaviour in general. It means `Log::Builder` can mutate a user-defined broadcast backend which may cause unintended side effects.
I believe `Log::Builder` should only append to a `BroadcastBackend` that it created itself, not if it was passed in.

A workaround is to bind an empty `BroadcastBackend` to the builder as first backend, before binding any other: `builder.bind("*", :trace, ::Log::BroadcastBackend.new)`.

**Comment by bcardiff** [comment]
> I believe Log::Builder should only append to a BroadcastBackend that it created itself, not if it was passed in.

I agree, let's go that route and avoid mutating user defined broadcast backend.
