### ISSUE TITLE
Official Windows installer

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#13426]
Currently, Windows builds are provided via the "unofficial" zip archives uploaded from the CI jobs, and there are [Scoop](https://github.com/neatorobito/scoop-crystal) and [WinGet](https://github.com/microsoft/winget-pkgs/blob/c09fae64c8c5282e80b0c96ce6989c763dcf85d4/manifests/c/CrystalLang/Crystal/1.7.3/CrystalLang.Crystal.installer.yaml) community packages that fetch those archives. The problem with zip archives is that they do not provide a complete installation experience, especially for Windows users who are not used to the kind of configuration expected on, say, a Linux system. A graphical installer would be the more natural method of distribution for Windows.

There is an [existing attempt to have an installer for Crystal inside WSL](https://github.com/faustinoaq/crystal-windows-installer), written for [Inno Setup](https://jrsoftware.org/isinfo.php). Two alternatives are [NSIS](https://nsis.sourceforge.io/Main_Page) and [WiX](https://wixtoolset.org/).

Here are some things doable in a GUI installer:

* Proper upgrades and removal. When not using an installer, a common pitfall with zip archives is extracting them directly over an old installation, which can break glob requires
* Detecting MSVC build tools and Windows SDK installation. This is **very** important for newcomers who expect the installer to "just" work on a fresh machine; nothing stands in their way for a portable installation
* Detecting and possibly installing Git / Mercurial / Fossil, which is needed by Shards
* Selecting a custom install location
* Enabling `*.cr` file association, so that double-clicking them runs the file with Crystal
* Optionally installing debug symbols for Crystal and/or the third-party libraries?

The actual development of the installer itself will most likely happen in [crystal-lang/distribution-scripts](https://github.com/crystal-lang/distribution-scripts), but it might also depend on whether we want to move the Windows CI job here to somewhere else.

**Comment by devnote-dev** [comment]
Following #13200 I think the official installer should also handle LLVM installs, that would bring us one step closer to solving the find config issue on Windows.

**Comment by HertzDevil** [comment]
The official LLVM Windows installers do not come with `llvm-config.exe`, so `llvm-config.exe` is not expected to be available in `%PATH%` via that way, and the only option is to build LLVM itself. If a user can append to `%PATH%` they can set `%LLVM_CONFIG%` directly. So I don't think we actually need that script on Windows.

**Comment by devnote-dev** [comment]
Right, I don't think building LLVM would be a bad thing, and even if that's not a viable option, couldn't the installer locate and set `%LLVM_CONFIG%` if LLVM is already installed?

**Comment by HertzDevil** [comment]
The only possibility is if someone built LLVM and added its `bin` to `%PATH%` prior to installing Crystal. This is not done automatically, so I believe the Crystal installer shouldn't hardcode `%LLVM_CONFIG%` automatically, either.
