### ISSUE TITLE
Allow an optional `start_day` argument for `Time#at_beginning_of_week`

### ISSUE THREAD

**Issue by DanielGilchrist** [crystal-lang/crystal#13447]
Currently when using `Time#at_beginning_of_week` it assumes the start of the week to be Monday. This works great for many use cases but sometimes we may want to assume the beginning of the week as another day (e.g. Sunday is also commonly considered to be "the beginning of the week")

```cr
Time.local.at_beginning_of_week # => 2023-05-08 00:00:00 +00:00
Time.local.at_beginning_of_week(Time::DayOfWeek::Sunday) # => 2023-05-07 00:00:00 +00:00
Time.local.at_beginning_of_week(:sunday) # => 2023-05-07 00:00:00 +00:00
```

This kind of functionality is provided by Rails which is where I got the inspiration from https://api.rubyonrails.org/classes/DateAndTime/Calculations.html#method-i-beginning_of_week

I prematurely created a pull request here: https://github.com/crystal-lang/crystal/pull/13446 but keen to discuss whether we want this change in the standard library, API specifics and whatever else

**Comment by straight-shoota** [comment]
Sounds good to me👍
The change is reasonable and straightforward to implement.
