### ISSUE TITLE
Automatically build/run a project when no filename is given

### ISSUE THREAD

**Issue by rishavs** [crystal-lang/crystal#1345]
Hi

Currently I can create a project using the init command.

However, there is no command to run a project. A project is just an abstract concept as far as the compiler is considered. There is also no standard project configuration file where a specific entry point for the project can be defined.

I propose that if the user doesnt specifies the target file for build/run commands, then the compiler should look for the project property file and decide the target from there.

For reference, I am very much hoping for something like the package.json used on nodejs projects.

**Comment by jhass** [comment]
I'm not sure I'd really like to see configuration for this, at least not required. I guess we can think about doing the equivalent to `crystal "src/$(dirname $(pwd)).cr"`, but much more than that...

**Comment by asterite** [comment]
@rishavs What you propose is exactly in our [Roadmap](https://github.com/manastech/crystal/wiki/Roadmap#automatic-buildrun). We can keep this issue open until we do it. But first we need to integrate [shards](https://github.com/ysbaddaden/shards) in the compiler.

**Comment by jhass** [comment]
Ugh, I should memorize the roadmap better :P

**Comment by rishavs** [comment]
same goes for me.

Also, maybe this isnt the best place to ask this, but how come Windows support is not in the roadmap. I would have thought that it is the single biggest miss and adding it will make the community far bigger.

**Comment by jhass** [comment]
It's something that would require a lot more effort from the core developers since we are completely unfamiliar with the Windows environment. We hope the community can provide this and will happily provide any support we can give towards the people working on this. Some effort is being made [here](https://github.com/xwanderer/crystal/tree/win32/win32).

**Comment by rishavs** [comment]
thanks.

**Comment by Sdogruyol** [comment]
I really like Rust's Cargo and want to see something like that for Crystal :+1:

**Comment by will** [comment]
I'm often in the situation where (were I using crystal instead of ruby) I'd want several binaries built. One for web, clock, worker_a, worker_b, and so on for each different enough thing in my Procfile.

Perhaps a convention that all top-level files in /src are built?

**Comment by asterite** [comment]
@will I really like your idea.  I'll also add that we might want to generate the output of these in the `bin` directory, maybe inside `bin/debug` and `bin/release` so it's more obvious that default builds are debug builds (I think Rust does the same).

**Comment by will** [comment]
@asterite the build directory idea is also nice because it can be added to .gitingore by default

**Comment by waj** [comment]
Why not just use a Makefile for that purpose? I know many people don't like them, but they are quite flexible.

We could generate a default like this:

```makefile
ifeq ($(RELEASE), 1)
	CRFLAGS += --release
endif

%: src/%.cr
	crystal build $< $(CRFLAGS)
```

**Comment by tristil** [comment]
@waj I agree with generating a Makefile. This is what I've done with every Crystal project that I've started. What might be even better is to have a Crystal-based DSL that is similar to a Makefile, because this would give more flexibility in automatically upgrading project builds from Crystal version to Crystal version.

**Comment by asterite** [comment]
I'm closing this for now. There doesn't seem to be a clear way we agreed to do this, and `Makefile` is good enough for this.
