### ISSUE TITLE
Invalid memory access (signal 11) while trying to run aes.cr

### ISSUE THREAD

**Issue by sdogruyol** [crystal-lang/crystal#13461]
## Bug Report

While trying to run [aes.cr](https://github.com/sam0x17/aes.cr) I got an Invalid Memory Access

Here's the code that causes the error

- Encrypt https://github.com/sam0x17/aes.cr/blob/master/src/aes.cr#L103-L121
- Decrypt https://github.com/sam0x17/aes.cr/blob/master/src/aes.cr#L127-L142

You can clone the repo and run the specs to get the error.

P.S: This error started to happen after Crystal 1.0

**Comment by Blacksmoke16** [comment]
Are the errors related to methods provided by the stdlib? It seems this shard is binding to additional functions so this issue might be better suited to that repo?

**Comment by sdogruyol** [comment]
This shard was working with Crystal 1.0 and it only started breaking after Crystal 1.0. 
Meaning that something must have changed in the stdlib that breaks this shard.

**Comment by HertzDevil** [comment]
This is because [`EVP_CIPHER_CTX` is an opaque type since OpenSSL 1.1.0](https://stackoverflow.com/questions/74646194/i-keep-getting-this-error-of-storage-size-of-ctx-isnt-known-for-evp-cipher-ct). Do this instead:

```crystal
lib LibCrypto
  alias EvpCipherCtx = Void

  fun evp_cipher_ctx_new = EVP_CIPHER_CTX_new : EvpCipherCtx*
  fun evp_cipher_ctx_free = EVP_CIPHER_free(ctx : EvpCipherCtx*)
end

class AES
  getter encrypt_context : LibCrypto::EvpCipherCtx* = LibCrypto.evp_cipher_ctx_new
  getter decrypt_context : LibCrypto::EvpCipherCtx* = LibCrypto.evp_cipher_ctx_new

  def initialize(key : Slice(UInt8), iv : Slice(UInt8), bits : Int32 = 256)
    en = @encrypt_context
    de = @decrypt_context
    # ...
  end

  def encrypt(data : Slice(UInt8))
    # ...
    if LibCrypto.evp_encrypt_init_ex(@encrypt_context, nil, nil, nil, nil) != 1
    # ...
  end
end
```
