### ISSUE TITLE
Add line number to JUnitFormatter

### ISSUE THREAD

**Issue by nobodywasishere** [crystal-lang/crystal#13467]
## Feature Request

I am working on adding the ability to run specs to the Crystal [VSCode extension](https://github.com/crystal-lang-tools/vscode-crystal-lang) and I am using the junit file in order to find/pass/fail testcases. I would like to add a line number parameter to the JUnit XML output. This would make things easier for me so that I don't need to parse the spec files manually to figure out where they are. 

An example of what the output would look like now (with added line parameter):
```xml
<?xml version="1.0"?>
<testsuite tests="1" skipped="0" errors="0" failures="1" time="2.003540435" timestamp="2023-05-13T19:25:33Z" hostname="my-hostname">
  <testcase file="/path/to/project/directory/mlcsim/spec/mlcsim/transcoder_spec.cr" classname="spec.mlcsim.transcoder_spec" 
    name="MLCSim::Transcoder when transcoding encodes a value into cells" time="2.3956e-5" line="5"/>
</testsuite>
```

On another note, I am unsure if two testcases with the same name are allowed. If they are, this would help differentiate them:
```xml
  <testcase file="/path/to/project/directory/mlcsim/spec/mlcsim/distribution_spec.cr" classname="spec.mlcsim.distribution_spec" 
    name="MLCSim::Distribution #normal_midpoint successfully finds the midpoint between 0.4 and 0.8 for different stdevs" time="1.005175956" line="10"/>
  <testcase file="/path/to/project/directory/mlcsim/spec/mlcsim/distribution_spec.cr" classname="spec.mlcsim.distribution_spec" 
    name="MLCSim::Distribution #normal_midpoint successfully finds the midpoint between 0.4 and 0.8 for different stdevs" time="1.003250633" line="20"/>
```

All alternate solutions (parsing the files manually, adding a custom formatter, etc.) were much more complex than adding this parameter. As far as I know, this does not break backwards compatibility.

**Comment by straight-shoota** [comment]
Sounds very reasonable. This was probably just forgotten when JUnit formatter was initially implemented.
