### ISSUE TITLE
ECR on windows - Error: expected '\n' after '\r'  

### ISSUE THREAD

**Issue by dsisnero** [crystal-lang/crystal#13484]
## Bug Report
CRYSTAL_CACHE_DIR="C:\Users\Dominic E Sisneros\AppData\Local\crystal\cache"
CRYSTAL_PATH=lib;F:\windows\scoop\apps\crystal\current\src
CRYSTAL_VERSION=1.7.3
CRYSTAL_LIBRARY_PATH=F:\windows\scoop\apps\crystal\current\lib
CRYSTAL_OPTS=""

when compiling a ECR file - get the following error

Error: expected '\n' after '\r' 

I can correct that by changing it from dos mode to unix mode in vim but should that be required - Erb looks for \r?\n in what is the equivalent of ECR's lexer.cr

**Comment by straight-shoota** [comment]
Closing due to missing information. This is *probably* fixed by https://github.com/crystal-lang/crystal/pull/13397
