### ISSUE TITLE
Timeout action broken on Windows

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#13519]
The following snippet should not print any periods on Windows:

```crystal
ch = Channel(Nil).new

spawn do
  while true
    ch.send nil
    sleep 1
  end
end

spawn do
  while true
    select
    when ch.receive
      print '#'
    when timeout(2.seconds)
      print '.'
    end
  end
end

sleep
```

Instead, the number of dots increases roughly every 2 seconds, and the output looks something like:

```
####..#..#..#...#...#....#....#....#.....#.....#......#......#......#.......#.......
```

Additionally, if `-Dpreview_mt` was used to compile the program, eventually the fiber crashes with `BUG: Fiber was awaken from select but no action was activated`.

**Comment by HertzDevil** [comment]
The problem seems to be that `Crystal::Iocp::Event#add` mutates a struct, but that struct is a copy of `Fiber#@timeout_event`, so `Crystal::Iocp::EventLoop#dequeue` fails to find the original event as `Deque#delete` relies on `#==`.

**Comment by straight-shoota** [comment]
In #13525 you mention turning the `Event` type into a module to allow a `class` implementation as a more intrusive alternative. What is intrusive about it? Changing the structure of these `Crystal::System` internals should not pose a big problem.
For me the most relevant question is whether class or struct semantics make more sense for this type, especially the performance effect.
