### ISSUE TITLE
Cannot compile anything on Windows

### ISSUE THREAD

**Issue by devnote-dev** [crystal-lang/crystal#13528]
A simple `puts "Hello world"` script fails on Windows using the master branch:

```
C:\...\> crystal run hello.cr
LINK : fatal error LNK1104: cannot open file 'OLDNAMES.lib'
Error: execution of command failed with exit status 2: ...
```

I've also tried passing specific linker flags (mentioned in the Discord server) which causes a different error message:
```
C:\...\> crystal run hello.cr --link-flags=/NODEFAULTLIB:OLDNAMES.lib
LINK : fatal error LNK1104: cannot open file 'uuid.lib'
Error: execution of command failed with exit status 2: ...
```

Crystal version:
```
Crystal 1.9.0-dev [df19a1d] (2023-05-27)

The compiler was not built in release mode.

LLVM: 16.0.3
Default target: x86_64-pc-windows-msvc
```

**Comment by HertzDevil** [comment]
Does `uuid.lib` actually exist on your system? Does `build --verbose` show any `/LIBPATH`s?

**Comment by devnote-dev** [comment]
It should as Crystal was able to compile before I updated to master, and I haven't touched any of the lib files. There are no `/LIBPATH`s in the verbose output.
