### ISSUE TITLE
Crystal not finding shared libs in WSL2 Homebrew install

### ISSUE THREAD

**Issue by tedneward** [crystal-lang/crystal#13547]
## Bug Report

Installed Crystal 1.8.2 via Homebrew on a Windows11/WSL2 Ubuntu platform.

```
ted@X1WORKTOP:~/Projects/Presentations.git/Content/Crystal/code$ crystal --version
Crystal 1.8.2 (2023-05-09)

LLVM: 15.0.7
Default target: x86_64-unknown-linux-gnu
ted@X1WORKTOP:~/Projects/Presentations.git/Content/Crystal/code$ crystal env
CRYSTAL_CACHE_DIR=/home/ted/.cache/crystal
CRYSTAL_PATH=lib:/home/linuxbrew/.linuxbrew/Cellar/crystal/1.8.2/libexec/../share/crystal/src
CRYSTAL_VERSION=1.8.2
CRYSTAL_LIBRARY_PATH=/home/linuxbrew/.linuxbrew/Cellar/crystal/1.8.2/libexec/../../../../lib
CRYSTAL_OPTS=''
```

Crystal run of hello world:
```
ted@X1WORKTOP:~/Projects/Presentations.git/Content/Crystal/code$ crystal run hello.cr
/home/ted/.cache/crystal/crystal-run-hello.tmp: error while loading shared libraries: libevent-2.1.so.7: cannot open shared object file: No such file or directory
```

libevent-2.1.so.7 is in Homebrew cellar:

```
ted@X1WORKTOP:~/Projects/Presentations.git/Content/Crystal/code$ ls /home/linuxbrew/.linuxbrew/Cellar/libevent/2.1.12/lib/
libevent-2.1.so.7               libevent_core.so                libevent_openssl.a
libevent-2.1.so.7.0.1           libevent_extra-2.1.so.7         libevent_openssl.so
libevent.a                      libevent_extra-2.1.so.7.0.1     libevent_pthreads-2.1.so.7
libevent.so                     libevent_extra.a                libevent_pthreads-2.1.so.7.0.1
libevent_core-2.1.so.7          libevent_extra.so               libevent_pthreads.a
libevent_core-2.1.so.7.0.1      libevent_openssl-2.1.so.7       libevent_pthreads.so
libevent_core.a                 libevent_openssl-2.1.so.7.0.1   pkgconfig/
```

Not sure how to debug further, and could very well be environmental on my end but can't figure out why Crystal suddenly can't find libevent (and libgc before that, but an apt-get seemed to correct for that). It's almost as if Crystal isn't honoring the CRYSTAL_LIBRARY_PATH somehow?

Note that if I `crystal build --static hello.cr`, it compiles with warnings about get_hostaddr() and a few others, but runs. If I `crystal build` it compiles without warning but fails at runtime with the same missing libevent file above.

Tried removing/reinstalling via brew rm; brew install but no change.

**Comment by straight-shoota** [comment]
This kind of question is best suited for [forum.crystal-lang.org](https://forum.crystal-lang.org/). Please write a post there.

An issue can be created when there is a concrete actionable item.
