### ISSUE TITLE
Handle Pointer.malloc(0)

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#1355]
This should probably raise. Extracted from #1342

**Comment by asterite** [comment]
Or [maybe not](https://github.com/manastech/crystal/issues/1342#issuecomment-137323621)

**Comment by jhass** [comment]
I'd tend to say it should raise, we could have the Slice case handled there by returning a Null object, Slice::Empty(T) or so.

**Comment by alex-fedorov** [comment]
How about:

- `Pointer(T).malloc(0)` raises
- `Pointer(T).malloc_empty` works

?

**Comment by alex-fedorov** [comment]
And :+1: to null object idea for slice too

**Comment by waj** [comment]
I don't think so. Using pointers is an unsafe operation so you must know what are you doing IMO. Returning a null object means now there is always a union and that means slow down on such critical and primitive objects. 

If you malloc 0 then it's probably a corner case after the result of some calculation (or a bug, but then just fix it) and that means the code will never try to use the pointer at all. 

So, for me malloc(0) should return a null pointer.

**Comment by asterite** [comment]
Yes, malloc(0) can result from some math and for me it should be valid. Also, one expects to be able to call GC.free on that pointer because Pointer.malloc asks from the GC. Right now the GC [does allocate some memory](http://play.crystal-lang.org/#/r/dma) for the case of 0, so that memory can be safely freed. Returning `Pointer.null` in this case will break that contract (if we want that obey that contract). So for me the current behaviour is good.

**Comment by jhass** [comment]
But when do you manually allocate memory? If you intend to pass it to an external library. Which library does expect to be given a pointer it can not write anything to or read anything from? Why would it take the pointer in the first place in that case?

**Comment by waj** [comment]
Yes it allocates the minimum which is a word size.
I was thinking an example of where a null pointer would me more efficient. For example, if a class has an array member, which is seldom used, but instead of making it nilable, initialize it with `Array(T).new(0)`. That will avoid to allocate the buffer and only allocated when needed.

**Comment by waj** [comment]
There are two viewpoints here: making the runtime faster, or warning the developer about a bug. I like both, but in this case I'm not sure we're helping the developer too much. 

@jhass many libraries receive an optional buffer. Also, it would crash if you didn't reserve enough memory. You must probably have to specify the buffer size anyway, and the buffer is smaller than the size specified it won't work, even if the size is not zero.

**Comment by ozra** [comment]
Code that calls malloc(0), as already said, has likely calculated it from need, and since the need is zero, no accesses will be made. So whatever is the most efficient way of letting it run, I vote for. Raising would be erroneous behaviour afaic.

**Comment by BlaXpirit** [comment]
Raising or returning nil makes no sense. Performance is paramount.

**Comment by asterite** [comment]
I'm closing this. `Pointer.malloc` should return a pointer that you can later call `realloc` on. Some classes, like `Array`, use an explicit `Pointer.null` for the zero case and later consider this case separately.
