### ISSUE TITLE
LLVM brainfuck example can't compile on Arch Linux:  undefined reference to `llvm_ext.cc.c4a0b00d'

### ISSUE THREAD

**Issue by glyh** [crystal-lang/crystal#13563]
## Bug Report

Code for reproduce: [here](https://github.com/crystal-lang/crystal/blob/97e9b3dfa2c6fe0325c837633a6189be99e79eb9/samples/llvm/brainfuck.cr). 

1. download branfuck.cr and store it as brainfuck.cr
2. `$ crystal brainfuck.cr`
3. got error:
```
/usr/bin/ld: /tmp/cc8FuTGM.ltrans0.ltrans.o:(.debug_info+0x2b): undefined reference to `llvm_ext.cc.c4a0b00d'
/usr/bin/ld: /tmp/cc8FuTGM.ltrans0.ltrans.o:(.debug_info+0x34): undefined reference to `llvm_ext.cc.c4a0b00d'
/usr/bin/ld: /tmp/cc8FuTGM.ltrans0.ltrans.o:(.debug_info+0x4f): undefined reference to `llvm_ext.cc.c4a0b00d'
/usr/bin/ld: /tmp/cc8FuTGM.ltrans0.ltrans.o:(.debug_info+0x56): undefined reference to `llvm_ext.cc.c4a0b00d'
/usr/bin/ld: /tmp/cc8FuTGM.ltrans0.ltrans.o:(.debug_info+0x5e): undefined reference to `llvm_ext.cc.c4a0b00d'
/usr/bin/ld: /tmp/cc8FuTGM.ltrans0.ltrans.o:(.debug_info+0x79): more undefined references to `llvm_ext.cc.c4a0b00d' follow
collect2: error: ld returned 1 exit status
Error: execution of command failed with exit status 1: cc "${@}" -o /home/lyh/.cache/crystal/crystal-run-hello.tmp  -rdynamic -L/usr/bin/../lib/crystal /usr/lib/crystal/llvm/ext/llvm_ext.o `"/usr/bin/llvm-config" --libs --system-libs --ldflags 2> /dev/null` -lstdc++ -lpcre2-8 -lm -lgc -lpthread -levent  -lrt -lpthread -ldl
```

Crystal Version: `Crystal 1.8.2 (2023-05-11) LLVM: 15.0.7 Default target: x86_64-pc-linux-gnu`
Linux Version: `Linux arch 6.3.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 10 Jun 2023 00:35:35 +0000 x86_64 GNU/Linux`
LLVM Version: `15.0.7`

**Comment by straight-shoota** [comment]
This example uses the LLVM bindings and for that needs the `llvm_ext` library available.
You can build this if you check out the entire repository (not just the single example file) and run `make llvm_ext`.

**Comment by glyh** [comment]
Is there a way I can use it without compiling the whole compiler? I bascially want to use it as an external library.

**Comment by HertzDevil** [comment]
I don't think that sample requires any functions from `LibLLVMExt`, in which case linking against the extensions shouldn't be necessary

**Comment by hugopl** [comment]
I have the very same problem, but compiling crystalline on ArchLinux.

**Comment by HertzDevil** [comment]
Crystalline calls methods in `Crystal::Compiler` directly, which will inevitably require all the functionality in `llvm_ext.cc` to be compiled. This one is about requiring only the public `LLVM` APIs

**Comment by kostya** [comment]
@hugopl about crystalline  https://github.com/crystal-lang/crystal/issues/12896#issuecomment-1371482597
