### ISSUE TITLE
Yield `key` in `Hash#transform_values`

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#13581]
`Hash#transform_values` currently only yields the value that is to be transformed. I'm proposing to also yield the key. It can be useful sometimes and there's not much reason to hide it deliberatly.

This is an example where the key would be used for the transformed value:
```cr
people = {
  "alice" => "alice@example.com",
  "bob" => "bob@example.org",
}

record Contact, name : String, email : String

people.transform_values do |email, name|
  Contact.new(name, email)
end # => {"alice" => Contact(@name="alice", @email="alice@example.com"), "bob" => Contact(@name="bob", @email="bob@example.org")}
```

Implementation should be trivial and cheap. For backwards compatibility, the key would be the second block parameter. This should work with existing code because unused parameters can be omitted in block definitions.

The same applies to `#transform_values!` and I figure `#transform_keys` could be adapted similarly to yield the key as well.

**Comment by yxhuvud** [comment]
Can't people use `to_h` if they need it? It is rare enough.

**Comment by straight-shoota** [comment]
Sure, that's a possible alternative. But it's less efficient, more complex code and doesn't communicate the intention as clearly.
