### ISSUE TITLE
MacOS version in LLVM target triple can mismatch the linker version

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#13594]
Builds of the Nix package for Crystal have failed to build on MacOS for a while ().

@will Has written a thorough explanation of what's happening in https://github.com/NixOS/nixpkgs/pull/223901.

> When building the Crystal compiler, it picks a default LLVM target triple by either looking at the env var `CRYSTAL_CONFIG_TARGET` if set, or by calling `LLVMGetDefaultTargetTriple` on the linked LLVM. [crystal-lang/crystal@master/src/compiler/crystal/config.cr#L47](https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/config.cr?rgh-link-date=2023-03-30T11%3A18%3A08Z#L47)
>
> On [...] MacOS, it can cause a mismatch with nix's MacOS stdenv.
>
> `stdenv.targetPlatform.darwinMinVersion` defaults to "11.0" and this makes it's way into all the clang and ld wrapper scripts. However, the default LLVM target can be something such as "aarch64-apple-darwin22.3.0" which would translate to kernel version 13. Then Crystal would build .o files targeting 13, and the wrapped clang/ld would try and link them to be compatible with 11 and generate hundreds of warning messages such as "was built for newer macOS version (13.0) than being linked (11.0)".

The description is accompanied by a patch that fixes this issue for Nix by setting `CRYSTAL_CONFIG_TARGET` explicitly without the version number. That makes everything work.

This doesn't seem to be a problem very specific to Nix. It could happen anytime when using an LLVM build with a newer default target than the system.

So I figure it might warrant a generic solution.
Maybe the compiler should scrub any version information from the LLVM default target triple on darwin?

**Comment by HertzDevil** [comment]
We already do that in `LLVM.default_target_triple` for x86-64 macOS. IMO there is no reason not to on AArch64 as well
