### ISSUE TITLE
Expose a file's inode

### ISSUE THREAD

**Issue by weirdbricks** [crystal-lang/crystal#13634]
## Feature Request

It would be great if we could get the inode of a file directly - currently I use this to get a file's inode: 

```
ic
ic(1.8.0):001> File.info("/tmp/goat").to_s.split("@st_ino=")[1].split(",")[0].to_i
 => 28313375
```

Thanks!

**Comment by weirdbricks** [comment]
... that's beautiful. Thanks @z64 !!

I still think it would be cool to get the same without having to add a method though, so I'll leave this issue open as a feature request.

**Comment by Blacksmoke16** [comment]
Duplicate of #8357
