### ISSUE TITLE
`Mutex` is not thread-safe on ARM processors

### ISSUE THREAD

**Issue by jgaskins** [crystal-lang/crystal#13642]
The following code generates a 1M-element array across multiple fibers and then prints its size, so the output should be `1000000`:

```crystal
mutex = Mutex.new
numbers = Array(Int32).new(initial_capacity: 1_000_000)
done = Channel(Nil).new
concurrency = 20
iterations = 1_000_000 // concurrency
concurrency.times do
  spawn do
    iterations.times { mutex.synchronize { numbers << 0 } }
  ensure
    done.send nil
  end
end

# Wait for all fibers to complete
concurrency.times { done.receive }
sleep 100.milliseconds # Wait just a bit longer to be sure the discrepancy isn't due to a *different* race condition
pp numbers.size
```

On Intel processors on both macOS and Linux, it gives the correct output reliably. On ARM processors on both macOS and Linux, it comes up anywhere from a few dozen to a few thousand short.

If I use `Crystal::SpinLock#sync` instead of `Mutex#synchronize` it displays the correct output, so it seems it's something in between `Mutex` and `SpinLock`. This is good news because it means that `Channel` _should_ still be thread-safe on ARM since it uses `SpinLock` directly.

**Comment by yxhuvud** [comment]
Just to check, is this with or without `-Dpreview_mt` ?

**Comment by jgaskins** [comment]
With.

**Comment by straight-shoota** [comment]
Probably related to/duplicate of #13055

**Comment by jgaskins** [comment]
@straight-shoota Yep, even the repro is almost the same. 👍🏼
