### ISSUE TITLE
Crystal Docs template overwrite

### ISSUE THREAD

**Issue by nobodywasishere** [crystal-lang/crystal#13646]
## Feature Request

I think it could potentially be useful to have the ability to override the templates used by the doc generator at runtime with a `--template` flag that points to a folder. The doc generator would check to see if, for example, there's a `_sidebar.html` in the folder. If there is, it would use that instead of the built-in one. This would be useful for me specifically as I'm developing a shard documentation website and want to have a custom sidebar. The other solutions I had were modifying the templates directly wherever crystal is installed, or adding whatever information i wanted via post processing, both of which aren't ideal and are liable to breaking. This should not break backwards compatibility.

**Comment by straight-shoota** [comment]
This would require a major architectural change because templates, including template expressions, are compiled into the compiler binary. Changes at runtime would not be able to use ECR templates.

**Comment by jansul** [comment]
An alternative option might be to use the JSON output (`crystal docs --format=json`) and plug that into your favourite static site generator, React etc
