### ISSUE TITLE
Indirect branch tracking

### ISSUE THREAD

**Issue by jcs** [crystal-lang/crystal#13665]
OpenBSD [now enforces](https://undeadly.org/cgi?action=article;sid=20230714121907) indirect branch tracking (BTI on arm64, IBT on x86_64) which breaks Crystal on OpenBSD going forward.

I'm not sure whether this would all be handled by llvm and Crystal's compiler just needs to turn it on (in clang it's `-fcf-protection=branch`) or if there is assembly in Crystal that needs to be modified with the new instructions.

**Comment by HertzDevil** [comment]
It says that indirect branch tracking is already on by default unless there is an opt-out linker flag, so do we actually need to do anything?

**Comment by jcs** [comment]
Yes, the opt-out is temporary.

**Comment by GeopJr** [comment]
OpenBSD enforces it now and Crystal has been marked as broken

**Comment by joshturge** [comment]
I'd like to help get Crystal supported on OpenBSD, what work needs to be done in order to get IBT support? I'm not sure where to start.

**Comment by wecing** [comment]
@joshturge maybe check out [QBE's implementation](https://c9x.me/git/qbe.git/commit/?id=5af33410f6faa6c0f7d97af5b802b2608b228bc2)

Note that it was reverted due to tooling reasons, but I am trying to do a roll-forward since the blocker seems gone.

**Comment by ysbaddaden** [comment]
We need to tell LLVM to generate the correct instructions on the x86_64 and aarch64 targets —in gcc/clang this is the `-fcf-protection=branch` option.

I understand we also need to fix the fiber context switch asm for x86_64 and aarch64 to have these too, so we start & resume a fiber?

**Comment by ysbaddaden** [comment]
Searching for examples, I found out that Rust adds the `cf-protection-branch=1` flag when creating a LLVM module when we pass `-Z cf-protection=branch` to rustc.

See the [source code](https://github.com/rust-lang/rust/blob/ffd978b7bf4ccdc74fe6c1b048d253eb3f3aa341/compiler/rustc_codegen_llvm/src/context.rs#L346-L356) and [Rust book](https://doc.rust-lang.org/stable/unstable-book/compiler-flags/cf-protection.html).

**Comment by ysbaddaden** [comment]
The `-fcf-protection=branch` option enables the [control-flow enforcement technology (CET)](https://doc.rust-lang.org/stable/unstable-book/compiler-flags/cf-protection.html) on x86 only. For AArch64 this is the `-mbranch-protection=bti` option to enable the [branch authentication instructions](https://doc.rust-lang.org/stable/unstable-book/compiler-flags/branch-protection.html) :weary: 

Looking at the disassembly of a compiled C program, the x86 option starts all functions with `endbr64` while the aarch64 option starts all functions with `bti c`. We might just need to add these in the ASM of fiber context switches (as the first resume instruction) when the feature is enabled?

There are more specific values to each option, to enable more features. See the links above for details. I don't know about their impact on the ASM of fiber context switches. They're not needed to support OpenBSD; in fact IBT/BTI isn't needed and we could keep it disabled, but it's interesting to follow on the security and see & measure the impact.

**Comment by ysbaddaden** [comment]
Initial attempt: https://github.com/crystal-lang/crystal/compare/master...ysbaddaden:crystal:feature/indirect-branch-tracking?expand=1

It only works with `--single-module` otherwise we fail with incompatible LLVM module / function / context / type, which means I fail to set the values on _every_ LLVM module (I guess). I must have missed something.
