### ISSUE TITLE
Fix any inconsistencies in the language

### ISSUE THREAD

**Issue by Silentdoer** [crystal-lang/crystal#13674]
## Discussion
Fix any inconsistencies in the language, even if it breaks change, because crystal should be beautiful and consistent

- What aspect of the language would you like to see improved?
- What are the reasons?
- Include practical examples to illustrate your points.
- Optionally add one (or more) proposals to improve the current situation.

**Comment by Blacksmoke16** [comment]
The [forums](https://forum.crystal-lang.org/) would be a better location for this kind of discussion.
