### ISSUE TITLE
Local variables should also be able to support a specified type, such as a: String = "aaa"

### ISSUE THREAD

**Issue by Silentdoer** [crystal-lang/crystal#13676]
## Feature Request
this is useful for code review

- Is your feature request related to a problem? Please describe clearly and concisely what is it.
- Describe the feature you would like, optionally illustrated by examples, and how it will solve the above problem.
- Describe considered alternative solutions, and the reasons why you have not proposed them as a solution here.
- Does it break backward compatibility, if yes then what's the migration path?

**Comment by Blacksmoke16** [comment]
You already can:

```cr
a : String = "aaa"
```

Questions like this may be better suited for the [forums](https://forum.crystal-lang.org/c/help-support/11).
