### ISSUE TITLE
Ctrl-C cannot kill the Crystal compiler

### ISSUE THREAD

**Issue by MistressRemilia** [crystal-lang/crystal#13672]
Version 1.9.x of the compiler cannot be killed with Ctrl-C or by doing a `kill -s INT`.  Ctrl-\ still works, and I've confirmed that Ctrl-C worked in 1.8.2.

A few of my own programs also exhibit this behavior, but I haven't been able to reduce it, and I have no idea where to even start with this one.  Doing a `Signal::INT.trap` doesn't work, either.

Crystal -v output:

```
Crystal 1.9.1 [c355a34e5] (2023-07-17)

LLVM: 13.0.0
Default target: x86_64-unknown-linux-gnu
```

I also checked against the pre-built binaries:

```
Crystal 1.9.1 [c355a34e5] (2023-07-17)

LLVM: 15.0.7
Default target: x86_64-unknown-linux-gnu
```

OS: Slackware Linux 15.0, x86-64

**Comment by Sija** [comment]
True, killing spec runner stopped working.

**Comment by straight-shoota** [comment]
This change must come from #13568

I think the interrupt still works, it just doesn't exit *immediately*. This can result in the process exiting normally before the interrupt handler excutes.

And I can see why: Before #13568, the signal was not trapped and thus would lead directly to exit the process without any involvement of the Crystal runtime.
Now we're trapping SIGINT and SIGTRAP for the handlers to call Crystal's exit routine. But the handler execution is decoupled from the trap. When it receives a signal, it writes it to a pipe and that pipe is then read from the `Signal loop` fiber which then executes the handler. During compilation the main fiber is occupied with calculations and offers no chance for the signal loop fiber to run.

It's probably best to revert #13568 and continue the discussion about how to best implement https://github.com/crystal-lang/crystal/issues/8687.

**Comment by hmood501** [comment]
> Version 1.9.x of the compiler cannot be killed with Ctrl-C or by doing a `kill -s INT`.  Ctrl-\ still works, and I've confirmed that Ctrl-C worked in 1.8.2.
> 
> A few of my own programs also exhibit this behavior, but I haven't been able to reduce it, and I have no idea where to even start with this one.  Doing a `Signal::INT.trap` doesn't work, either.
> 
> Crystal -v output:
> 
> ```
> Crystal 1.9.1 [c355a34e5] (2023-07-17)
> 
> LLVM: 13.0.0
> Default target: x86_64-unknown-linux-gnu
> ```
> 
> I also checked against the pre-built binaries:
> 
> ```
> Crystal 1.9.1 [c355a34e5] (2023-07-17)
> 
> LLVM: 15.0.7
> Default target: x86_64-unknown-linux-gnu
> ```
> 
> OS: Slackware Linux 15.0, x86-64
