### ISSUE TITLE
[record] Allow custom initialize

### ISSUE THREAD

**Issue by lost22git** [crystal-lang/crystal#13689]
The following code is not working in v1.9.0 (it should be expected to throw ArgumentError)

```crystal
record A,
name : String,
age : Int32 do
  def initialize(@name,@age)
    raise ArgumentError.new "age must be >0" unless age>0
  end
end

a = A.new "asda",-10
p! a
```

**Comment by Sija** [comment]
It does work in v1.9.1, see https://carc.in/#/r/fhz0

**Comment by Sija** [comment]
It works the same in the older versions, nothing changed in this respect in version 1.9.0.

**Comment by lost22git** [comment]
But it should be expected to throw ArgumentError

**Comment by HertzDevil** [comment]
The `#initialize` generated by `record` attaches type restrictions to all parameters, i.e. `@name : String, @age : Int32`; your custom def is less specific than that overload, so it is never called.

**Comment by lost22git** [comment]
@HertzDevil you are right ;-)
