### ISSUE TITLE
Parsing error?

### ISSUE THREAD

**Issue by jzakiya** [crystal-lang/crystal#13690]
When I write this as shown, the compiler gives this error.

```
prm_r = residues[i%rescnt]

 302 | prm_r = residues[i%rescnt]
                           ^
Error: unknown %r char
```
This fixes it:
```
prm_r = residues[i % rescnt]
```
Is this an error?

**Comment by straight-shoota** [comment]
Yeah this looks like a bug.
`%r` can indicate a regex literal but only if followed by a sepecific delimiter (see https://crystal-lang.org/reference/1.9/syntax_and_semantics/literals/regex.html#percent-regex-literals). I suppose that this special case is responsible for the error and the parser doesn't handle it correctly.
