### ISSUE TITLE
Regression in macro block unpacking

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#13707]
#11597 introduced a regression in that unpacked block arguments in a macro context are no longer seen as valid variables.

Given this code:

```crystal
{%
  data = [{1, 2}, {3, 4}]

  data.each do |(k, v)|
    pp k, v
  end
%}
```

It previously would print:
```cr
1
2
3
4
```
but now prints:
```
In test.cr:5:8

 5 | pp k, v
        ^
Error: undefined macro variable 'k'
```

EDIT: It's a regression on master, not an actual regression from before `1.9.2`.

**Comment by asterite** [comment]
I'll try to fix this today

**Comment by asterite** [comment]
Actually, if someone could take a look at this, it would be great. I don't have the Crystal dev environment set up and I need to install xcode for some reason I don't understand, and it says it's going to take 78 hours to download 🤷

**Comment by asterite** [comment]
Should be easy to fix. Maybe @HertzDevil could pick this up?

**Comment by asterite** [comment]
Nevermind, I got it.
