### ISSUE TITLE
String.build block parameter name improvemnt (change str to io)

### ISSUE THREAD

**Issue by zw963** [crystal-lang/crystal#13722]
## Bug Report

The block parameter name `str` like following is consider as a bad smell.

```crystal
String.build do |str|
  str << "foo"
end
```

Because str is a String::Builder, it is a IO object.

Current, Crystal codebase mixed `|io|` along with `|str|` in many place for String.build, it even more worse.

so, i consider refactor the `|str|` into `|io|` is appropriate.

**Comment by zw963** [comment]
I create #13723 for fix this, spec is passing, and the diff was compared manually very carefully.

**Comment by beta-ziliani** [comment]
I understand the motivation to do it, but to me `str` in this case represents _`str`ing builder_. `str_builder` or `sbuilder` might be more apt names, although they're long. So `str` is good enough. `buff` also makes sense since a builder is, after all, a buffer.

**Comment by zw963** [comment]
> I understand the motivation to do it, but to me `str` in this case represents _`str`ing builder_. `str_builder` or `sbuilder` might be more apt names, although they're long. So `str` is good enough. `buff` also makes sense since a builder is, after all, a buffer.

But, mixed |io| along with |str| in different file (even in save file) consider bad smell?

And new user don't know `str` is `str`_builder too.

**Comment by straight-shoota** [comment]
Closing. This is an opininated/stylistic change that doesn't seem to have a common consensus.

This proposal could potentially be acceptable. But I think it would require a more elaborate debate to establish a clear style recommendation. 

This discussion can continue later at some point. But the benefit of having either variant over the other is pretty negligible, making this a very low priority topic. It's useless to keep an open issue about it.
