### ISSUE TITLE
Octicon licence not compatible with debian

### ISSUE THREAD

**Issue by beta-ziliani** [crystal-lang/crystal#13735]
Have not delve in the details myeself yet, but according to debian package maintainer `@deiv`, the playground is not enabled in debian's package [because of license issues with the octicon package](https://forum.crystal-lang.org/t/whats-up-with-the-debian-packages/5913/9). The obvious solution would be to find an alternative set of fonts that could work with debian's.

EDIT: importing details from the thread here.

> Let me explain:
>
    Files-Excluded: src/compiler/crystal/tools/playground/public/vendor/*
    Comment: removed because there are distributed without the original source code
>
> Only indicates that this files are excluded from the packaging original sources (in debian we look for pristine source code).
>
> In [https://github.com/crystal-lang/crystal/tree/master/src/compiler/crystal/tools/playground/public/vendor](https://github.com/crystal-lang/crystal/tree/master/src/compiler/crystal/tools/playground/public/vendor) directory we have 5 vendored software packages inside the crystal source code. We just remove them as that packages are currently inside Debian (we don’t like to duplicate software inside the archive).
>
> At first, playground was enabled because that five packages were found in the Debian archives, but at some point it was disabled because octicons package was removed from the archive. Look at [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=883107](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=883107) bug, point 2:

        the package is distributed under the MIT license but our users will
        not be able to make use of the freedoms this license is granting
        them (specifically, modify the files we ship) using just the tools
        in Debian main, instead they need tools outside of Debian. It is
        violating the spirit of the DFSG if we are shipping files that our
        users are unable to modify.

> As octicons could not be used as a dependency and our rules are that we do not like to use precompiled or vendored software inside packages, the playground cannot be compiled until octicons will enter again the Debian archive.

**Comment by jzakiya** [comment]
Here are a list of some.

https://github.com/topics/fonts

https://www.creativefabrica.com/promo/5225/FGHIJKLMNO/ref/4269299?utm_medium=cpc&utm_source=bing&utm_campaign=Nonbrand_Competitor_US_EN&utm_content=competitor_dafont&utm_term=dafont&msclkid=4fcde20f40bc12eec3cf86dd30c51a50

**Comment by GeopJr** [comment]
I made a proposal fix on #13738. I don't think octicons' license is the problem but rather that the font files are binary. The proposal uses svg sprites from the latest octicons version
