### ISSUE TITLE
Very bad performance of Array#combinations

### ISSUE THREAD

**Issue by mrjbq7** [crystal-lang/crystal#13761]
I was looking at the relative performance of combinatorics in different languages, and noticed what seems to be quite a speed issue with the current Crystal implementation of ``Array#combinations`` which takes almost **400 seconds** when other languages take less than 30 seconds.

```
icr:0> t0 = Time.utc;
       print((0...200).to_a.combinations(4).to_a.size);
       Time.utc - t0
64684950 => 00:06:30.513019000
```

You can compare to Ruby 3.2.2 which takes **27 seconds**:

```
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]

irb(main):001:0> measure
TIME is added.
=> nil                         
irb(main):002:0> (0...200).to_a.combination(4).to_a.length

processing time: 26.907042s    
=> 64684950
```

And to Python 3.11.4 which takes **3.7 seconds**:

```
Python 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from itertools import combinations
>>> from time import time
>>> t0 = time(); print(len(list(combinations(range(200), 4)))); time() - t0
64684950
3.729408025741577
```

I am using the latest crystal:

```
$ crystal -v
Crystal 1.9.2 (2023-07-19)

LLVM: 15.0.7
Default target: aarch64-apple-darwin22.6.0
```

Normally I wouldn't complain about relative performance but it is 15 to 100 times worse.  All tests were run on the same Apple MacBook Pro running Apple Silicon M2. I have replicated this issue on an Apple Mac mini with Intel.

**Comment by mrjbq7** [comment]
It's possible this is related to the use of ``crystal i``, I've been told the compiled version is much faster, although not the speed of Python.

**Comment by Blacksmoke16** [comment]
It is most definitely due to using the interpreter. It's fairly easy to get it faster than Python by optimizing the logic a bit:
```cr
elapsed = Time.measure { pp (0...200).to_a.each_combination(4).size }
pp elapsed
```

Which outputs:
```txt
64684950
00:00:02.715608165
```

In the end tho, I wouldn't base performance benchmarks like this on the interpreter. Compile a binary with `--release` and use that or the most accuracy.

**Comment by HertzDevil** [comment]
For the record, the Python example is indeed using an `itertools` iterator, so it is expected to be faster than the two other examples in the OP which create the entire array first

**Comment by mrjbq7** [comment]
I attempted to fix that by calling list(itertools.combinations)On Aug 23, 2023, at 4:44 PM, Quinton Miller ***@***.***> wrote:﻿
For the record, the Python example is indeed using an itertools iterator, so it is expected to be faster than the two other examples in the OP which create the entire array first
