### ISSUE TITLE
The return value type of `Slice#copy_to`, etc. should be explicit

### ISSUE THREAD

**Issue by erdian718** [crystal-lang/crystal#13773]
## Discussion

Although the return value of `Slice#copy_to` is not indicated in the documentation, and we should not use its return value, but we may accidentally write the following code:

```
xs = Slice(Int32).new(3)
ys = Slice(Int32).new(5)
zs = xs.copy_to(ys)

# We didn't call `#to_unsafe` explicitly but we inadvertently got an unsafe pointer.
zs[10]
```

Similar problems exist in `Slice#copy_from/Slice#move_to/Slice#move_from`.

I think the return value can be explicitly specified as one of the following ways:

1. `nil`.
2. `self`.
3. the number of elements that were copied/moved.

**Comment by straight-shoota** [comment]
The number of copied elements is just `size`, so it doesn't have too much value to return that.
I don't think this would typically be used in method chaining, but I suppose it wouldn't hurt to return `self`. 
`nil` would be fine as well. I guess we just have to pick one or the other...

**Comment by erdian718** [comment]
I think it's appropriate to mark the return value type as `Nil`, which is also in line with the design of the current standard library (not using the return value of methods such as `Slice#copy_to`).
