### ISSUE TITLE
Integer types are not type checked as expected when deserializing YAML

### ISSUE THREAD

**Issue by MistressRemilia** [crystal-lang/crystal#13770]
It appears that when a class has a field of an integer type, and that class can be deserialized from YAML, that field isn't type checked properly during deserialization.  Specifically, if the YAML data contains an integer outside of that type's range, no error is raised and the value is just masked at the actual expected bit width.

I'd expect this to behave the same way as when the YAML data contains a string (`Expected UInt8, not 2000000 at line 1, column 6`), but maybe it's not supposed to? :sweat_smile: 

```crystal
require "yaml"

class YamlData
  include YAML::Serializable
  property foo : UInt8 = 5u8
end

# Does not type check as expected, the first results in a value of 0,
# the second results in a value of 128.
pp YamlData.from_yaml("foo: 200000000")
pp YamlData.from_yaml("foo: 2000000")

# Works mostly as expected, except the type shows up as Int64
begin
  pp YamlData.from_yaml("foo: s")
rescue err
  puts err
end
```

Output:
```
#<YamlData:0x7f775e8dae70 @foo=0>
#<YamlData:0x7f775e8dae60 @foo=128>
Expected Int64, not "s" at line 1, column 6
```

crystal -v:
```
Crystal 1.9.2 [1908c816f] (2023-07-19)

LLVM: 13.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by straight-shoota** [comment]
`Expected Int64, not "s" at line 1, column 6` when actually parsing `UInt8` is because `Int64` is the internal representation for the YAML parser which is only later converted to smaller types. I suppose `parse_scalar` could receive an additional parameter for the target type to make a better error message.
