### ISSUE TITLE
Optimize the constructors of `Time::Span`

### ISSUE THREAD

**Issue by erdian718** [crystal-lang/crystal#13797]
## Discussion

I think the constructors of `Time::Span` can be optimized from the following points:

1. Avoid arithmetic overflow exception.
`Time::Span.new(seconds: 127_i8, nanoseconds: 1_000_000_000)`
Currently the code will raise `OverflowError`, I think we should handle it right.

2. Remove unnecessary type conversions.
If suggestion 1 is accepted, there is no need to convert the `Int` type parameter to `Int64` type in other constructors explicitly.

3. Remove unnecessary normalization.
`Time::Span.new(*, seconds : Int, nanoseconds : Int)` has already normalized the parameters, so `Time::Span.new(*, nanoseconds : Int)` does not need to normalize the parameters.

4. Add `Time::Span.new(*, seconds : Int)`.
Currently `Time::Span.new(seconds: 123)` will call `Time::Span.new(*, days : Int = 0, hours : Int = 0, minutes : Int = 0, seconds : Int = 0, nanoseconds : Int = 0)`, but I think we should define a logically simpler overloaded method `Time::Span.new(*, seconds : Int)`.

What do you think of the above suggestions?

**Comment by straight-shoota** [comment]
Thanks for raising this up!

1. is definitely an error and should be fixed. 
2. agreed. We could probably even narrow the type restrictions to `Int64` and `Int32`. The unspecific `Int` is from a time before number autocasting.
3. agreed.
4. Not sure about this one. What would be the purpose? Performance?

**Comment by HertzDevil** [comment]
We should leave it as `Int` if we want to accept `BigInt` arguments

**Comment by erdian718** [comment]
> 4\. Not sure about this one. What would be the purpose? Performance?

Yes, the purpose is for performance. Here's a simple benchmark:
```
require "benchmark"

def new_time_span(*, seconds : Int)
  Time::Span.new(seconds: seconds, nanoseconds: 0)
end

arg = 123
res = Time::Span::ZERO

Benchmark.ips do |b|
  b.report("new_time_span") { res = new_time_span(seconds: arg) }
  b.report("Time::Span.new") { res = Time::Span.new(seconds: arg) }
end
```
In theory `new_time_span` it should be faster, but in practice it is not.
I'm not sure I know if I'm using benchmarks correctly, as I asked in the forum: [How to use benchmark correctly?](https://forum.crystal-lang.org/t/how-to-use-benchmark-correctly/6008)

Here is the result:
```
without the `--release` flag
 new_time_span  19.76M ( 50.61ns) (± 2.30%)  0.0B/op        fastest
Time::Span.new  16.29M ( 61.38ns) (± 2.77%)  0.0B/op   1.21× slower
```
```
with the `--release` flag
 new_time_span 514.91M (  1.94ns) (± 2.16%)  0.0B/op        fastest
Time::Span.new 511.72M (  1.95ns) (± 4.16%)  0.0B/op   1.01× slower
```

> We should leave it as Int if we want to accept BigInt arguments

I agree with this.

**Comment by straight-shoota** [comment]
Theory and practice are two different paths =)

I expect these additional operations with `0` values incur no runtime cost because they are optimized out by LLVM (the `0` value is fixed at compile time).

> We should leave it as `Int` if we want to accept `BigInt` arguments

`BigInt`'s scope exceeds that of `Time::Span` by far. I think it should be approriate to require an *explicit* conversion for `BigInt` arguments and utilize autocasting for other types.

**Comment by HertzDevil** [comment]
> `BigInt`'s scope exceeds that of `Time::Span` by far.

Why do you think so?

Besides, turning `Int` into a primitive integer type will never enable autocasting on _all_ primitive integer types, because `IntX` and `UIntX` variables never autocast into each other for any size `X`. So I don't think "we have autocasting now" justifies the move from `Int` parameter restrictions to any primitive integer type.

**Comment by straight-shoota** [comment]
Okay I see we probably won't be able to move on changing the type restrictions without a bigger discussion. =) But that should be a separate one and not part of this issue. 
So let's drop that tangent.

**Comment by erdian718** [comment]
> 4\. Not sure about this one. What would be the purpose? Performance?

I found the compiler's optimization results are not as deterministic as they seem, for example:
```
require "benchmark"

arg = 123
res = Time::Span::ZERO

# Benchmark 1
Benchmark.ips do |b|
  b.report("new seconds A") { res = Time::Span.new(seconds: arg, nanoseconds: 0) }
  b.report("new seconds B") { res = Time::Span.new(seconds: arg) }
  b.report("new seconds C") { res = Time::Span.new(days: 0, seconds: arg) }
end

# Benchmark 2
Benchmark.ips do |b|
  b.report("new nanoseconds A") { res = Time::Span.new(seconds: 0, nanoseconds: arg) }
  b.report("new nanoseconds B") { res = Time::Span.new(nanoseconds: arg) }
  b.report("new nanoseconds C") { res = Time::Span.new(days: 0, nanoseconds: arg) }
end

puts res
```
A/B/C corresponds to the three constructors of `Time::Span`.

I found that the line `puts res` can affect the results of the benchmark, and the order of `Benchmark 1` and `Benchmark 2` also affects the benchmark results.

In general, the compiler may optimize `Time::Span.new(seconds: 123)` well in some scenarios, but the compiler's optimization results are not as deterministic as they seem.

I think that if `method1` is theoretically faster than `method2`, then in practice `method1` may not be faster than `method2`, but at least it won't be worse than `method2`.

So, I don't think it's a bad idea to have a `Time::Span.new(*, seconds: Int)`.

**Comment by straight-shoota** [comment]
I would like to focus on the other changes. They are straightforward and uncontroversial. If we're talking about performance, we should take these changes into account for the baseline.

Please note that benchmark results are quite tricky and may not tell the whole story. Particularly, at the scale of (sub-)nanosecond for a single iteration, measuring accuracy can be quite unreliable.

**Comment by erdian718** [comment]
Ok, let's finish the uncontroversial part, here's a PR: #13807
