### ISSUE TITLE
`Char::Reader#each` can go out of bounds

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#13816]
`Char::Reader#each` misses proper bounds checking when the reader position progresses inside the yielded block.

```cr
reader = Char::Reader.new("Test")

reader.each do |char|
  puts "Outer: #{char.inspect}"
  break if char == `\0` # This is an artificial failure condition to avoid massive gibberish output.
                        # `#each` should never yield `\0` because it's not part of the string
  reader.each do |char|
    puts "Inner: #{char.inspect}"
  end
end
```
Output:
```
Outer: 'T'
Inner: 'T'
Inner: 'e'
Inner: 's'
Inner: 't'
Outer: '\0'
```

`#each` does not validate if the end has been reached after the block executed. It expects the block not to interfere with its internal state. This might be a reasonable expectation, but it's hard to ensure. So I think it's necessary to validate the state when resuming after the block.

**Comment by HertzDevil** [comment]
Other ways are to change the definition of `#has_next?` with `@end = @pos >= @string.bytesize`, or ensure that `@pos <= @string.bytesize` at all times

**Comment by straight-shoota** [comment]
Yeah there is some redundancy between `@end` and `@pos >= @string.bytesize`. `#each` uses `@end` as break condition, so I think it's fine to stay with that. However I amended a commit to improve performance by reducing to a single bounds check per iteration.
