### ISSUE TITLE
`T.from_yaml` scalar deserialization ignores tags

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#13828]
It is possible to pass arbitrary tags to `String.from_yaml`, including those mapped to non-string types in YAML's core and fail-safe schemas:

```crystal
String.from_yaml "!!map abc"                  # => "abc"
String.from_yaml "!!seq def"                  # => "def"
String.from_yaml "!!int 123"                  # => "123"
(Array(Int32) | String).from_yaml "!!int 123" # => "123"
```

Whereas other types will continue to use the core schema rules for plain scalars even if their tags are absent in the core schema:

```crystal
Int32.from_yaml <<-YAML # => 123
%TAG !! tag:example.com,2000:
---
!!int 123
YAML
```

Neither seems to be intended behavior if `T.from_yaml` is indeed using the core schema.

**Comment by straight-shoota** [comment]
I understand `T.from_yaml` as decidedly *not* using a generic schema. The target type is explicitly predetermined by the application specific type `T`.

**Comment by straight-shoota** [comment]
I don't think there is anything actionable here. Everything works exactly as intended.

`T.from_yaml` is supposed to deserialize an instance of `T` from the given YAML. The deserializer is free to use any typing information that YAML provides in the process. But it's not bound to it. This is application-defined parsing, not using any generic schema.
