### ISSUE TITLE
`File.match?` does not support Windows paths with backslash separators

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#13831]
`File.match?` currently only recognizes forward slash (`/`) as path separator in both `pattern` and `path` parameters.
This is acceptable for `pattern`. But `path` should reckognize backslash separator (`\`) as well for proper Windows support.

**Comment by HertzDevil** [comment]
This can be handled in `File::MatchOptions` similar to #13510. In Ruby `File::FNM_NOESCAPE` disables the escape behavior of `\` outside character classes, but I haven't tried if that turns it into a directory separator

**Comment by straight-shoota** [comment]
A clear indicator of intended semantics would be the `kind` attribute when using a `Path` parameter.
When using `String`, some kind of disambiguation is necessary. But I think it should be fine to default to either posix semantics or the platform's native semantics. There is no need to specify alternative semantics for `String` parameter because you can use `Path` instead.

**Comment by HertzDevil** [comment]
So if I pass a Windows `Path` to `File.match?`, are there no escape sequences at all? How do I pass a pattern that matches `foo\[bar].txt` literally?

**Comment by straight-shoota** [comment]
This issue is about recognizing windows paths with backslash separators in the `path` parameter. It does not have any pattern semantics. It's what the pattern compares against.

The `pattern` is always a platform-independent string. The pattern syntax recognizes *only* `/` as directory separator. Backslashes are used for escaping. There's not intention to change this.

**Comment by HertzDevil** [comment]
This makes more sense, I was entirely confused about the two parameters

**Comment by HertzDevil** [comment]
However, after https://github.com/crystal-lang/crystal/pull/13955#issuecomment-1817135277, I wonder if `File.match?` can also accept `Path` patterns and always treat them as POSIX paths
