### ISSUE TITLE
Docs generator hiding class definitions

### ISSUE THREAD

**Issue by nobodywasishere** [crystal-lang/crystal#13832]
## Bug Report

This is a problem I first noticed in the [API docs](https://crystaldoc.info/github/maiha/toml-config.cr/v0.7.0/index.html) for toml-config, and reduced it down to this example. Classes defined in a module that isn't defined in the specific shard aren't included in the docs generator output. Example from a blank project:

```crystal
# doctest.cr
require "other"

class Doctest::Doctest
end

# other.cr
module Doctest
end
```

![image](https://github.com/crystal-lang/crystal/assets/32797552/9fc6cd54-ed75-407e-9a9b-c499d21910ab)

```crystal
# doctest.cr
require "other"

module Doctest
  class Doctest
  end
end

# other.cr
module Doctest
end
```

![image](https://github.com/crystal-lang/crystal/assets/32797552/2aa50a01-bbca-4108-876c-9ad522080e62)

Crystal version 1.9.2

**Comment by nobodywasishere** [comment]
Looking into this, the doc generator works by getting all of the types and filtering them by different things like excluding built-in stuff and excluding stuff that isn't defined in a file in `src/`. As there's no direct `module Doctest` def in `src/`, the type is skipped. One potential workaround I can think of is every time something is included, also include all of it's namespaces in an instance variable. Then at the end, anything in the instance variable has to be included in the docs gen.

I'm still learning about how the internals of the compiler and docs generator work so this is probably very broken but this is my attempt at fixing this. It doesn't fully work but I thought it could give insight into how the problem could potentially be solved.

https://github.com/nobodywasishere/crystal/commit/371a947028acca2fbf51673624562f44cb36acbb

**Comment by straight-shoota** [comment]
Perhaps a different approach could be to iterate through *all* types and their features (methods, constants, macros) and filter by their individual location. If a feature is included in the doc generation, all its parent namespaces will be included as well.

**Comment by nobodywasishere** [comment]
This is a duplicate of #8553
