### ISSUE TITLE
Doc version selector background white in dark mode

### ISSUE THREAD

**Issue by nobodywasishere** [crystal-lang/crystal#13839]
## Bug Report

Doesn't happen on Firefox or GNOME Web. All tested on Arch Linux. Affects Crystal 1.9.0 - 1.9.2.

Edge:
![image](https://github.com/crystal-lang/crystal/assets/32797552/d163a612-6cd9-4479-81b5-11a0eaeb88ce)

Chromium:
![image](https://github.com/crystal-lang/crystal/assets/32797552/25436b4a-9800-4477-8902-4367a56658c2)

**Comment by GeopJr** [comment]
Apparently `.project-versions-nav`'s transparent background also applies to the dropdown on blink browsers which in combination with setting `color-scheme` to dark made it impossible to read :shrug:

**Comment by nobodywasishere** [comment]
Yeah setting the background color to something like `#202020` fixes it, should be done in the dark mode selector though

![image](https://github.com/crystal-lang/crystal/assets/32797552/8bafde00-76c8-483a-bad8-cfc556e9a542)

Also this `content: ""` symbol should probably be updated in an additional PR:
![image](https://github.com/crystal-lang/crystal/assets/32797552/0b8794f1-f2b7-4b2b-89c3-e75f546ef1f6)
![image](https://github.com/crystal-lang/crystal/assets/32797552/c9e04460-fcf4-43df-8f11-6d65cee6e998)

**Comment by nobodywasishere** [comment]
Thank you @GeopJr !
