### ISSUE TITLE
Crystal 2.0? Crystal 2?

### ISSUE THREAD

**Issue by joekohler** [crystal-lang/crystal#13868]
I believe Crystal has a lot of potential to be the as popular as Python in the near future, considering Crystal is at Crystal 1.9, I believe the next version should be called Crystal 2.0, as a new computer science major, Crystal has a special place in my heart.

**Comment by Blacksmoke16** [comment]
This topic would probably be better off for the forums: https://forum.crystal-lang.org/

Closing as there's nothing really actionable here.

**Comment by erdian718** [comment]
Crystal is indeed an excellent language, but the next version will definitely not be 2.0, and it will not even be released in the next two years. 2.0 means incompatibility with 1.x, hasty release of 2.0 can lead to ecological fragmentation.

Of course, there are currently some proposals that are not compatible with 1.x. We may be able to create a 2.0 label to mark issues that will not be resolved in 1.x but may be resolved in 2.0.

**Comment by straight-shoota** [comment]
@erdian718 There is a milestone for that: https://github.com/crystal-lang/crystal/milestone/45
