### ISSUE TITLE
`-f` Parameter for Hierarchy

### ISSUE THREAD

**Issue by keplersj** [crystal-lang/crystal#1387]
I'm going to sound like a broken record here, but being able to parse Class Hierarchy in JSON format will be very helpful for IDE functionality, mainly Autocompletion.

**Comment by asterite** [comment]
Not at all! This parameter should work consistently whenever there's useful compiler output.

**Comment by bcardiff** [comment]
For the class hierarchy and maybe all the related tools that would help for an autocomplete the main issue is that the code needs to be in a compiling status, or you need to cache the last good run. But yes: :+1:

On a side note: there are some ideas around turning the tools towards something as a services that won't need to parse/compile the sources once and again, but that isn't a short term goal.

**Comment by asterite** [comment]
If someone wants to tackle this, code is [here](https://github.com/crystal-lang/crystal/blob/5432eda49637a0c2bad2ae8cd2b161c00206f71e/src/compiler/crystal/tools/print_hierarchy.cr)

**Comment by bmulvihill** [comment]
hey @asterite I would like to take a stab at this, I have a in progress branch I am working on [here](https://github.com/bmulvihill/crystal/commit/68d60843cb294ef12e85d0390b02e09a6ba24be0)

**Comment by asterite** [comment]
@bmulvihill Great! Please, do so. Once you have something ready please send a PR.

One tiny note: I would store a number in the "size" property, maybe even call it "size_in_bytes", instead of a string "8 bytes".

**Comment by bmulvihill** [comment]
@asterite will do, thanks!

**Comment by asterite** [comment]
This is implemented by [#2936](url)
