### ISSUE TITLE
Splatting an empty array in macro language evaluates to an empty `MacroId`

### ISSUE THREAD

**Issue by BlobCodes** [crystal-lang/crystal#13877]
## Bug Report

This code:
```crystal
{%
  array = [] of Nil
  splat = [*array][0]

  puts splat.class_name
  puts splat.symbolize
%}
```

..prints the following output:
```crystal
MacroId
:""
```

This means that splatting an empty array results in an empty `MacroId`, which is strange and hard to debug.

```sh
$ crystal -v
Crystal 1.9.2 [1908c816f] (2023-07-19)

LLVM: 15.0.7
Default target: x86_64-unknown-linux-gnu
```

**Comment by Blacksmoke16** [comment]
What's the alternative? In macro land `#[]` returns `NilLiteral` when an index doesn't exist instead of raising, which its string representation is an empty string.

**Comment by HertzDevil** [comment]
The splat operator in the macro land is exactly equivalent to calling `#splat`. To be honest I don't know why that behavior existed (did the operator come before the AST node method?)

**Comment by BlobCodes** [comment]
> The splat operator in the macro land is exactly equivalent to calling `#splat`

Ah, then this makes sense.

```cr
{%
  array = [1, 2, 3, 4, 5]
  p [*array].size # => 1

  args = [/e/, "oa"]
  "test".gsub(*args)
  # => Error: wrong number of arguments for macro 'StringLiteral#gsub' (given 1, expected 2)
%}
```

It just (correctly) returned all arguments concatenated as a MacroId..

Still, I think this isn't really documented enough - especially since the macro syntax is basically normal crystal syntax, I would have expected different behaviour.

But since this is correct behaviour, I'll close this issue.

**Comment by Sija** [comment]
I believe this should be cleared up one way or the other (implementation or documentation-wise).

**Comment by straight-shoota** [comment]
I don't think it makes much sense to have both the splat operator and `#splat` do exactly the same thing.

Can we change `*ary` to be essentially equivalent to `{{ ary.splat }}`?

**Comment by BlobCodes** [comment]
I don't really see any need for splatting arguments inside the macro language (into macro methods).

I was just looking for bugs inside the macro language - I couldn't think of a real use case for this.

Rather, this would complicate and slow down the macro language.

I think `*var` should just be deprecated inside the macro language, as `var.splat` is more expressive.

**Comment by straight-shoota** [comment]
I'm a bit torn about removing the splat operator. The diffs in https://github.com/crystal-lang/crystal/pull/13939 show some examples where it looks a bit more natural than `.splat`:

```diff
-def_equals {{*fields}}
+def_equals {{fields.splat}}
```

Probably, because the `*` operator would be used in exactly the same way in normal Crystal grammar: `def_equals *foo`.

It's probably still a good change to remove this duplication.
`#splat` is more versatile with the `trailing_string` parameter.

**Comment by HertzDevil** [comment]
IMO the splat operators would only make sense when they are the outermost operators of a macro expression (`{{ *... }}`). Even then, the familiarity argument breaks down rather quickly:

```crystal
macro foo(x, y)
  p({{ *x }}, {{ *y }})
end

foo %w(), [1, 2] # Error: unterminated call
```

As for the history of these operators:

* `#argify`, the original name for `#splat`, was added on Jun 30, 2014 in 15cc021
* `*` was added on Oct 12, 2014 in a3dd467
* `**` was added on Dec 2, 2016 in 81f949d
* `#double_splat` was added and `#argify` renamed to `#splat` on Dec 3, 2016 in d440045
