### ISSUE TITLE
Add an error exit code when `crystal tool unreachable` finds results

### ISSUE THREAD

**Issue by JadeKharats** [crystal-lang/crystal#13880]
I would like to be able to use the `crystal tool unreachable` command in a CI like gitlab-ci or github-actions.

For the jobs to be in error, the command would have to have the same behavior as `crystal tool format --check`

```crystal
#sample.cr
def foo
  1
end
def bar
  2
end
bar
```

On text output 

```shell
crystal tool unreachable sample.cr
```
Expected output : [...]/sample.cr:1:1	top-level foo	3 lines
**Expected exit code** : 1

On Json output

```shell
crystal tool unreachable -f json sample.cr
```
Expected output : [{"name":"top-level foo","location":"[...]/sample.cr:1:1","lines":3}]
**Expected exit code** : 1

**Comment by DanielGilchrist** [comment]
I'd definitely be keen for something like this!

In the meantime I've been doing this which also works (GitHub actions example)
```yml
- name: Check for unreachable code
  run: |
    output=$(crystal tool unreachable sample.cr)
    echo "$output"
    if [ -n "$output" ]; then
      exit 1
    fi
```

**Comment by JadeKharats** [comment]
thank you, I took your code to put it in a gitlab jobs here

`
unreachable:
  stage: component_test
  script:
    - |
       output=$(crystal tool unreachable src/cfp.cr)
       echo "$output"
       if [ -n "$output" ]; then
         exit 1
       fi
`

it unblocks me in the meantime
