### ISSUE TITLE
Hash.new(default) is slower than a manual check

### ISSUE THREAD

**Issue by trans** [crystal-lang/crystal#13897]
Please have a look at this code: https://github.com/jinyus/related_post_gen/blob/main/crystal/src/crystal.cr around line 31.

Note that someone must have discovered the same issue I am bringing up here b/c now the code has initial sizes added to help mitigate the issue, but the code used to read:

```crystal
tag_map = Hash(String, Array(Int32)).new

posts.each_with_index do |post, i|
  post.tags.each do |tag|
    tag_map[tag] = [] of Int32 unless tag_map[tag]?
    tag_map[tag] << i
  end
end
```

I thought for sure it would be at least as fast and probably faster to add a default hash value and get rid of the `unless` condition.

```crystal
tag_map = Hash(String, Array(Int32)).new([] of Int32)

posts.each_with_index do |post, i|
  post.tags.each do |tag|
    tag_map[tag] << i
  end
end
```

But that ran **10x slower**!!!

My gut feeling is that something is going on under the hood that is ripe of optimization. So I just wanted to let you all know about it.

**Comment by straight-shoota** [comment]
Those two examples are critically different. The default value passed to `Hash.new` is never explicitly duplicated and since `Array` is passed by reference, all values will refer to exactly the same array instance.

Example:
```cr
h = Hash(String, Array(Int32)).new([] of Int32)
h["foo"] << 1
h["bar"] << 2 # => [1, 2]
h["foo"].same?(h["bar"]) # => true
```

If you want a different instance every time, you need to use a default block that constructs a new array:
```cr
h = Hash(String, Array(Int32)).new { [] of Int32 }
h["foo"] << 1
h["bar"] << 2 # => [2]
h["foo"].same?(h["bar"]) # => false
```

I'm sure this will also improve performance of your example.

See #12075 for more context on this phenomenon.

**Comment by devnote-dev** [comment]
> If you want a different instance every time, you need to use a default block that constructs a new array:
> ```crystal
> h = Hash(String, Array(Int32)).new { [] of Int32 }
> h["foo"] << 1
> h["bar"] << 2 # => [2]
> h["foo"].same?(h["bar"]) # => false
> ```

I tried this approach for an application I'm building and found out that it doesn't actually work — there is no block overload for just a default value, only one that yields the existing hash:

```crystal
h = Hash(String, Array(Int32)).new { |h, k| h[k] = [] of Int32 }
```

This is useful if you need bigger computations, but for a use-case such as this (and my own) I think there should be a specific block overload that just accepts the default value.

**Comment by straight-shoota** [comment]
Yeah the default value only serves as return value of fetch methods. It's not implicitly added to the hash. That's identical wether it's a single one or generated by the block.
If you want to persist generated default values, you must put them explicitly.

I'm sure this feature is often needed, so it might be nice to have a short cut for that. That would be a separate feature request, though. And honestly, I'm not sure how a decent API for that could look like while still being more concise than an explicit block body.
