### ISSUE TITLE
`Float64::NAN > 0` in the interpreter

### ISSUE THREAD

**Issue by BlobCodes** [crystal-lang/crystal#13909]
## Bug Report

While investigating for #13856 in the interpreter, I was confused by seeing that the comparison `Float64::NAN > 0` returned true.

When trying the same on the normal compiler, I got the result I expected: it returned false.

System: Fedora 38/Fedora Rawhide
```sh
$ crystal -v

Crystal 1.10.1 [c6f3552f5] (2023-10-13)

LLVM: 16.0.6
Default target: x86_64-redhat-linux-gnu
```

**Comment by HertzDevil** [comment]
This happens because for some reason the interpreter primitives do not use `#<=>`:

https://github.com/crystal-lang/crystal/blob/ad7d42cb8ea982ff7e99911f851d43122fde0f6a/src/compiler/crystal/interpreter/instructions.cr#L953-L962
