### ISSUE TITLE
Crystal::System::Process shell invocation broken on Linux with FreeBSD sh

### ISSUE THREAD

**Issue by valpackett** [crystal-lang/crystal#13919]
[Chimera Linux](https://chimera-linux.org/) uses FreeBSD sh, so this condition:

https://github.com/crystal-lang/crystal/blob/7aa02829e5e4097952697acdd530af4237c78ad3/src/crystal/system/unix/process.cr#L215-L217

doesn't match and as a result, the substitution is broken which breaks e.g. the compilation of macros (`ld: error: undefined symbol: main` due to no object files actually getting provided) :/

Is the conditional actually necessary? I'm not sure when the empty arg could break things…

**Comment by nekopsykose** [comment]
a quick test in `yash`, `bash`, `zsh`, `dash`, `mksh`, `busybox ash` reveals that all of them are consistent in printing `1 2 3` for `shell -c "echo \$@" -- "1" "2" "3"` and `-c "echo \$@" -- "" "1" "2" "3"`. the empty `""` is only required for the bsd shells apparently, but it also does not break any other. this should be safe to just remove the if condition and make it universal

**Comment by nekopsykose** [comment]
hm, no, it seems the `--` is being passed as `$0`. so the reason it happens to work 'consistently' is because the shell is actually using `--` as `$0`, and then `$@` is 1-onward. but on the bsd shell, the `--` delimiter is actually parsed, and then the `""` is required to make `$0` something else

**Comment by nekopsykose** [comment]
ah ok, so just replacing `--` with `sh` (any string) should work. `/bin/sh -c 'program "$@"' sh 1 2 3` seems to work with every shell

**Comment by q66** [comment]
basically just replace `--` with `sh` in the original args and then drop the special case for freebsd/dragonfly entirely

**Comment by straight-shoota** [comment]
Oh that's interesting. So I suppose another option to write the same thing would be `["/bin/sh", "-c" "$0 ${@}", command, *args]`?
We can't do that though because it would break use cases where `command` includes `${@}`.
