### ISSUE TITLE
Removing the need for `llvm_ext.cc`

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#13946]
If everything we need is already in LLVM's C API, then our build process will be considerably simpler (see for example #10880), and it'll become possible to build + distribute a Windows compiler that dynamically links against `LLVM-C.dll` without any LLVM static libraries.

The following list is mostly copied from #13177:

* [x] `LLVMExtDIBuilderCreateEnumerator`
  LLVM 9.0.0 added `LLVMDIBuilderCreateEnumerator`. Our function is now conditionally compiled, but we cannot remove it completely as long as LLVM 8 is supported.
* [x] `LLVMExtSetCurrentDebugLocation`
  This can mostly be replaced by `LLVMSetCurrentDebugLocation` in LLVM 8, and `LLVMSetCurrentDebugLocation2` in LLVM 9+. LLVM 8 still needs the part of this function that clears the current debug location.
* [x] `LLVMExtWriteBitcodeWithSummaryToFile`
  This is only needed for the now-removed ThinLTO support, and is now gone after #13488.
* [x] `LLVMExtBuildOperandBundleDef`, `LLVMExtBuildCall2`, `LLVMExtBuildInvoke2`
  These will be available in LLVM 18 due to llvm/llvm-project#73914.
* [x] `LLVMExtTargetMachineEnableGlobalIsel`
  LLVM 18-dev added `LLVMSetTargetMachineGlobalISel` very recently in llvm/llvm-project#70806.
* [x] `LLVMExtCreateMCJITCompilerForModule`
  This is unnecessary since we could call the above function [immediately after JIT compiler creation](https://github.com/crystal-lang/crystal/pull/13966).

**Comment by HertzDevil** [comment]
As a final step, we need a way to tell the Makefile(s) that `llvm_ext.obj` doesn't need to be built at all and that the local compiler doesn't depend on it. This would happen if `LLVM_VERSION` is new enough, or if we explicitly disable it via a flag.

**Comment by straight-shoota** [comment]
With #14357 we can consider this resolved. `llvm_ext` is no longer necessary when linking LLVM 18+
