### ISSUE TITLE
String#strip! missing

### ISSUE THREAD

**Issue by stellarpower** [crystal-lang/crystal#13947]
Is there a reason that the mutating form `strip!` is missing from `String`? Didn't find any references to it using github search.

**Comment by stellarpower** [comment]
Oh yeah. Figures. Out of interest, what's the implementation reason for making them immutable? Re-using buffers internally?

**Comment by stellarpower** [comment]
As an aside, I quite like the idea of a `.=` operator - not necessarily for Crystal, but in general. Then `text .= strip` would parse the same as `text = text.strip`.

**Comment by straight-shoota** [comment]
Having immutable strings is easier to reason about, less surprises. For example, strings are commonly used as keys in a `Hash` and it would be super akward if some unintended side effect changes the value of a string.

**Comment by stellarpower** [comment]
Makes sense - we could apply that logic to any type though right? nushell generally had immutable variables, with any changes shadowing the original for this reason, although it then can make it awkward to use in some situations and they brought mutable ones back in.
