### ISSUE TITLE
Require either pkg-config or pkgconf

### ISSUE THREAD

**Issue by joshcangit** [crystal-lang/crystal#13996]
## Feature Request

When installing this as an Apt package, it requires `pkg-config`.
If it needs this, then why not require either `pkg-config` or `pkgconf`.
They sort of work the same unless Crystal is using this dependency in a way that is only compatible with one of them.
Not sure what or how that is.

**Comment by joshcangit** [comment]
I think this issue might be in the wrong repository.
I wonder where is the one for packaging?

**Comment by HertzDevil** [comment]
The one maintained by us is https://github.com/crystal-lang/distribution-scripts. There are also third-party Linux packages (e.g. Debian has https://packages.debian.org/sid/crystal)

**Comment by joshcangit** [comment]
OK, moved this issue to #275.
