### ISSUE TITLE
Exposing a macro's caller

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#14055]
I'm proposing to give macros access to its caller.

This would be benefitial for several use cases, for example:

* Incorporate doc comment attached to the macro call (#14039)
* Raise macro errors or warnings at the location of the call in user code instead of pointing into library code.

I'm sure there can be other useful applications once this feature is available.

A syntax proposal would be a macro instance method named `@caller` whose value is the `Call` instance which calls the macro.
An implementation of this proposal is available in #14048.

```cr
macro foo
  {{ @caller.line_number }}
end

foo # => 5
```

Theoretically, this mechanism could even provide a chain for nested macro calls. I'm not sure if that would be super useful for anything. But I could see it might be handy for deeply nested macros in library code. However, they could probably also pass references to the entry point callers downwards. So it might not be super important.
We should at least consider making `@caller` an array, though.

Another question is whether there might be a need to access a caller's context, particularly the `@type` and `@def` variables.
Perhaps those could be made generally available on `ASTNode` instances, as ivar reads? i.e. `@caller.@type` would refer to the caller's type scope.
This doesn't need to be part of an initial implementation as I'm not sure about real use cases, but it's good to consider optional enhancements like this in the initial feature discussion.

For reference, a similar mechanism for regular methods is the [`::caller` method](https://crystal-lang.org/api/1.10.1/toplevel.html#caller:Array(String)-class-method) which provides a stack trace at runtime. Unlike macros, method instantiations usually cannot be traced back to a specific call at compile time because they are shared. The actual caller is only available at runtime.

**Comment by HertzDevil** [comment]
One concern I have is whether it will be available in hooks, especially `method_missing` which already has a fictitious `Call` as its argument

**Comment by beta-ziliani** [comment]
But it's different, isn't it? Like in `method_missing` the call is about the missing method. The concern to me is what is the value of `@caller` when the macro is called implicitly by the compiler.

**Comment by straight-shoota** [comment]
@beta-ziliani Does the caller implicitly call any macros that are not hooks? (One could argue that an implicitly called macro is a hook by definition, but let's not go into that rabbit hole).

`inherited`, `included` and `extended` have a clear "caller" location. There are some practical challenges though. `include` and `exclude` are technically not `Call` nodes (although they might with #11868) and `Include` and `Exclude` nodes are currently not exposed in the macro language. For `inherited` the `@caller` could be the path node in the inheritance declaration.
But I'm not sure it's worth it fully implementing this. It should be fine to let `@caller` just be `NilLiteral` in those cases.

**Comment by beta-ziliani** [comment]
> Does the caller implicitly call any macros that are not hooks?

No, that's an explicit call.

**Comment by straight-shoota** [comment]
Sorry, I meant "Does the compiler implicitly call any macros that are not hooks?"

**Comment by beta-ziliani** [comment]
Idk, but I agree with your general comment on start with `NilLiteral` in any undefined case.

**Comment by HertzDevil** [comment]
> For inherited the @caller could be the path node in the inheritance declaration.

There is also #10710 for this, which exposes the type (not path) via `@owner`

**Comment by Blacksmoke16** [comment]
So from what I gather, we're fine with having `NilLiteral` in undefined case to start. But possibly want to make `@caller` an `Array(Call)` such that you can retain the context between nested calls. From an implementation POV, where would that array live? Given from what I can tell a new `MacroInterpreter` is created to interpret each macro call.

We could also consider having separate ivars. E.g. `@caller` for the last one and `@call_stack` for the array of all of them? Or maybe `@caller.last` is easy enough to not worry about it. Throwing an `@[Experimental]` annotation on it would be another option.

**Comment by straight-shoota** [comment]
Yeah, getting a call stack is a bit more complicated.
I'm not entirely sure if it's really that useful. Put differently: Knowing the direct caller is already a great enhancement.
Getting the stack might enable other valueable features, or it might also be useful for other purposes (compiler error messages maybe?), of course. So I wouldn't prevent an extension to incorporate the entire stack, but IMO it doesn't need to be part of an initial implementation.
If we know we'll definitely enhance it later, making `@caller` return `ArrayLiteral` with only a single entry for now doesn't sound too bad.

Implementation wise, I think we could just have a stack of macro calls in `Crystal::Program`. So that might not even be prohibitively complex. We could try to get everything at once and reconsider in case we hit some barriers.

**Comment by Blacksmoke16** [comment]
> If we know we'll definitely enhance it later, making @caller return ArrayLiteral with only a single entry for now doesn't sound too bad.

Feels like a bit of premature optimization in that we're affecting the API for the reason of it might be useful in the future, but without any immediate use cases. But, I think there's also something to be said about it being comparable to its runtime counterpart, so this seems reasonable 👍.
