### ISSUE TITLE
`arm64` versus `aarch64` in `LLVM.default_target_triple`

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#14052]
This spec is still failing on my M2:

https://github.com/crystal-lang/crystal/blob/25d33036f72694537fefc7e9123699d9b165921f/spec/std/llvm/llvm_spec.cr#L15-L18

```
Failures:

  1) LLVM .default_target_triple
     Failure/Error: {% if flag?(:darwin) %}

       Expected: "arm64-apple-darwin23.1.0"
       to match: /-apple-macosx$/

     # spec/std/llvm/llvm_spec.cr:17
```

`LLVM` is supposed to normalize the triple by removing the version number, but this doesn't work because the triple starts with `arm64` rather than `aarch64`:

https://github.com/crystal-lang/crystal/blob/25d33036f72694537fefc7e9123699d9b165921f/src/llvm.cr#L91-L99

This spec passes inside a Nix shell. I don't know what is going on there.

[Rust had this problem too](https://bugzilla.mozilla.org/show_bug.cgi?id=1659066). Apparently `arm64` is preferred over `aarch64` now?

**Comment by miry** [comment]
I found the same thing, that LLVM supports name arm64-apple-darwin, the aarch64-apple-darwin could be replaced. (llvm-config --host-target #=> arm64-apple-darwin23.0.0)

in https://github.com/crystal-lang/distribution-scripts/issues/268
