### ISSUE TITLE
Support `Etc/UTC` timezone location

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#14074]
`Time::Location.load` currently handles the `"UTC"` and `""` special cases that point to the `UTC` timezone. I propose we support `Etc/UTC` as well, mainly to support the most common `UTC` context without having to install a TZ database just for that when not using a more specific TZ.

There could also be an argument for all the other aliases such as `Etc/Zulu`, or `Etc/Universal`, but those are probably a lot less common than the official name and not worth handling.

**Comment by ldtrdev** [comment]
The time zone is [invariably set to UTC](https://crystal-lang.org/api/1.10.1/Time.html). But yeah, supporting multiple time zones could also save a lot of time.

However, a practical workaround could be a custom function that converts UTC to any other desired time zone.

**Comment by ldtrdev** [comment]
The time zone is [invariably set to UTC](https://crystal-lang.org/api/1.10.1/Time.html). But yeah, it could indeed save a lot of time.

However, a practical workaround could be a custom function that converts UTC to any other desired time zone.

**Comment by Blacksmoke16** [comment]
@ldtrdev Not sure I follow. This issue is focused towards the `Time::Location.load` method not the general `Time` API.

**Comment by ldtrdev** [comment]
> @ldtrdev Not sure I follow. This issue is focused towards the `Time::Location.load` method not the general `Time` API.

I know, just trying to say that `Time::Location.load` and the general `Time` API are UTC-Centric, adding support for additional time zones could indeed be useful.

**Comment by straight-shoota** [comment]
This conversation seems to be digressing from the topic of this issue. Please let's keep this focused on the addition of `Etc/UTC` as a built-in time zone label.

@ldtrdev Would you please open a new thread in https://forum.crystal-lang.org/c/crystal-contrib/6 to voice your general concerns about the Time API? It would be nice if you could elaborate a bit more to help others understand the point.
Thanks.
