### ISSUE TITLE
[Enhancement] Provide `responds_to?` in macros

### ISSUE THREAD

**Issue by js-ojus** [crystal-lang/crystal#1409]
Provide a compile-time `responds_to?` for use in macros.  This can help greatly in simplifying conditional code generation.

**Comment by asterite** [comment]
As discussed in IRC, this might be useful.

Would you show an example usage? It's always better if we add features with a use-case in mind. And also that way we can write a spec for that.

**Comment by js-ojus** [comment]
@asterite : What I am really looking for is a generalisation of [C#'s type constraints](https://msdn.microsoft.com/en-us/library/bb384067.aspx) to arbitrary checks on public methods (not just the availability of a parameterless constructor).

And, it must be checked at compile-time!

**Comment by straight-shoota** [comment]
Is this resolved by #4474?

**Comment by akzhan** [comment]
@straight-shoota btw, why has_method? but not responds_to?

**Comment by straight-shoota** [comment]
Because of `has_constant?` and `has_attribute?` and a TypeNode does not *respond to*, but *has* methods.
I'm not sure however if this was the intention of this issue or if it was about having `responds_to?` on ASTNode like this:
```crystal
{% if ast_node.responds_to?(:join) %}
  {{ ast_node.join }}
{% end %}
```

**Comment by akzhan** [comment]
@straight-shoota thanks :)

**Comment by js-ojus** [comment]
A big thanks to all contributors for adding this!  I shall close this, accordingly.

**Comment by js-ojus** [comment]
@straight-shoota As described in my comment of 11 Sep 2015, this issue is limited to enabling a compile-time check for the presence of a specified method in the method set of a given type parameter.
