### ISSUE TITLE
Doc generator excludes implicit flag enum members

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#14117]
Was looking into fixing #13466 with the proposed solution, but noticed that when you have a flag enum, the doc generator does not include the implicit members in the docs. Because of this it would be a bit less than ideal to use an enum member that wouldn't link to anything.

I looked into this and the failure point is that https://github.com/crystal-lang/crystal/blob/667fbf1f8684aa223e0cc6be7c9061a5f5b41f32/src/compiler/crystal/tools/doc/generator.cr#L182 is returning `false` due to `const.locations` being empty for the implicit members. These constants should probably have/inherit some form of location info so that they are no longer skipped. Alternatively, we could handle this within the doc generator itself if there is a reason/it's not possible to set the location on the implicit members themselves.

EDIT: Should also ensure it includes the auto generated methods for the implicit members as well.

**Comment by straight-shoota** [comment]
I think everything that's part of the API should have a location. We can just take the location of the enum def.
