### ISSUE TITLE
Regression: can't resume a running fiber

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#14124]
CI has found a regression bug in current master: https://github.com/crystal-lang/crystal/actions/runs/7277531361/job/19831265764

```
  .build/std_spec --order=random   
  0.2.2
  Randomized with seed: 15487
  ................................................................................................................................................................
  ................................................................................................................................................................
  .................................................................................................................................................
  FATAL: can't resume a running fiber: #<Fiber:0x7f4ca5e859a0>
    from src/crystal/scheduler.cr:155:5 in 'fatal_resume_error'
    from src/crystal/scheduler.cr:149:7 in 'validate_resumable'
    from src/crystal/scheduler.cr:119:5 in 'resume'
    from src/crystal/scheduler.cr:196:3 in 'run_loop'
    from src/crystal/scheduler.cr:196:3 in '->'
    from src/crystal/system/thread.cr:116:13 in 'start'
    from src/crystal/system/unix/pthread.cr:18:58 in '->'
    from .build/std_spec in 'GC_inner_start_routine'
    from .build/std_spec in 'GC_call_with_stack_base'
    from /lib/x86_64-linux-gnu/libc.so.6 in '??'
    from /lib/x86_64-linux-gnu/libc.so.6 in 'clone'
    from ???
```

We recently merged some refactor PRs related to concurrency:

* https://github.com/crystal-lang/crystal/pull/14096
* https://github.com/crystal-lang/crystal/pull/14099
* https://github.com/crystal-lang/crystal/pull/14098

 The CI checks on the PRs were successful, so we didn't notice before merging.
 
The error reproduces locally in 10/10 runs for [#14098](https://github.com/crystal-lang/crystal/pull/14098)
It did not reproduce for #[14099](https://github.com/crystal-lang/crystal/pull/14099) after 10 runs.
So [#14098](https://github.com/crystal-lang/crystal/pull/14098) looks very much like the guilty party here 😁 

It seems innocuous enough, just refactoring some code with no apparent effect on changing any semantics. But it seems like there is something going wrong. We'll need to investigate further.
For now, we should revert #14098.

**Comment by ysbaddaden** [comment]
That error should be impossible to reach since Fibers can only ever be resumed on the same thread. It should only happen with stealing schedulers, where a thread B steals a fiber that thread A just enqueued but didn't yet switch context (race-condition).

It may sound like changing the `fiber.resume` calls to `resume(fiber)` to be the culprit, but in the run loop we should only have fibers attached to the current thread...

I'll try to reproduce, then debug to understand what the heck is happening.

**Comment by ysbaddaden** [comment]
Ooooh, I'm not calling `fiber.set_current_thread` in `Crystal::Scheduler.enqueue` which may result in it being left `nil` and thus sent to another thread on further enqueues.

I messed this up while writing the individual patches. The `fix/mt-issues` branch is fine.
