### ISSUE TITLE
Deterministic & Random Values in Macro Land 

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#14142]
## Discussion

A core function of macros is to be able to generate code. A macro like `record` can accept some arguments and generate an entire struct type. The `getter` macro can accept names/types and generate getter methods and instance variables. In both of these cases the exact name of the type, method, or ivar is provided explicitly. This means there is minimal room for naming conflicts depending on the namespace they're expanded in.

However, if the macro logic is on a "higher level" in that you're generating code based on the values of multiple annotations in conjunction with type information etc., there may not be a place where the user could provide a name to keep things unique. In such a case, being able to generate either a deterministic or random value as a suffix to a method/type name could be useful to ensure uniqueness automatically. Another benefit would be having a more robust way to check for duplicates across macro expansions, versus just letting the last one win.

Each `ASTNode` defines a `#hash` method in the same was `Object#hash` does. Numbers are valid in method and type names so in theory exposing this would do the job. E.g.

```cr
macro test(**args)
  {% {id: args["id"], name: args["name"]}.hash %}
end

test id: 10, name: "foo" # => 1862350431679306068
test id: 10, name: "foo" # => 1862350431679306068
test id: 20, name: "bar" # => 16093986525376310553
```

For randomness, one option would be to add a new top level macro method `hex(n)` that essentially just calls into `Random.hex`. But deff open to other options.

WDYT?

**Comment by straight-shoota** [comment]
I don't think I understand what your use case is. Could you elaborate a bit more?

**Comment by Blacksmoke16** [comment]
@straight-shoota Sure. I will concede the use case is a bit niche and deep within the Athena internals. However I haven't fully thought out the logic yet, so I'll do the best I can pseudo code example wise for what I had in mind for this.

In Athena, there exists a feature that determines the best format for a given request (via `accept` and/or request extension). This is can be configured via a series of rules that will be checked sequentially.

```cr
ATH.configure({
  framework: {
    content_negotiation: {
      rules: [
        {path: "^/", host: "api.%domain%", priorities: ["json", "xml"], fallback_format: json, prefer_extension: false},
        {path: "^/image", priorities: ["jpeg", "gif"], fallback_format: false, prefer_extension: true},
        {path: "^/admin", methods: ["GET", "POST"], priorities: ["xml", "html"], fallback_format: nil, prefer_extension: false},
        {path: "^/api", priorities: ["xml", "json"], fallback_format: "xml", prefer_extension: false},
        {path: "^/", priorities: ["text/html", "*/*"], fallback_format: "html", prefer_extension: true},
      ],
    },
  },
})
```

If the `accept` header of:

> text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8,application/json

And the route is like `/foo.{_format}`, then `/foo.json` will set the format to `json` while calling `/foo` will set the format to `html`.

From an implementation POV, there is a service called `RequestMatcher` whose job is to determine if each rule should be applied to the current HTTP request. I.e. by ensuring the path, host, methods match up. Each unique rule has its own instance of this service, and these are supplied to another service.

In Athena DI land, each service has a unique string used to identify it, most of the time these are generated from the FQN of the type, or specified by the user itself. However for these request matcher services, I would like to auto create/register them with a deterministicly random ID.

Given the ID for these will be internal the name doesnt really matter as long as it's unique. Being deterministic would allow sharing instantiations. E.g. hash a tuple of the path, host, and methods, use that value as part of the service ID, and create a new `RequestMatcher` instance using those arguments. Then when processing the next rule, if the hash is the same we can just re-use that service versus creating an entirely new one that is exactly the same; ultimately creating more services, using more memory, etc.

---

In the past I also thought about using this for some sort of mocking library in which you could say like `mock = Mocker.mock MyClass` in which that could expand to like `class MyClass_SomeRandomString < MyClass; end` and add in the extra mock specific logic, which would make it so each mock is its own instance with truly unique name versus monkey patching things globally on `MyClass` itself.

**Comment by straight-shoota** [comment]
Hm, maybe I still don't understand the use case.

I don't think exposing `ASTNode#hash` is a good idea because it's based on `object_id` and thus would expose an implementation detail of the compiler. If for some reason the implementation changes in a way that a node is cloned and thus both clones have different hashes, it might break some expectations.

But it seems you just want some kind of unique identifier for disambiguation.
Would perhaps a global squence work for that?

```cr
UID_SEQUENCE = [0]

macro unique_id(name)
  {% UID_SEQUENCE[0] += 1 %}
  {{ name.id }}_{{ UID_SEQUENCE[0].stringify.id }}
end

unique_id "foo" # => foo_1
unique_id "foo" # => foo_2
```

An alternative could be to derive an identifier from a node's location or data.

**Comment by oprypin** [comment]
In your first example you could call `.symbolize` instead of `.hash` and it would in fact just work as a globally unique identifier.

In some cases throwing `__FILE__` `__LINE__` into the tuple is relevant for getting actual uniqueness, but for your case seems you want the opposite - deduplication.

Anyway I've used it here
https://forum.crystal-lang.org/t/how-to-collect-all-calls-of-a-macro-over-the-entire-program/2421/10

**Comment by oprypin** [comment]
Randomness is probably too big of a hammer to be allowed, it can cause havoc for any hope for incremental compilation

**Comment by HertzDevil** [comment]
With something like #8835 you could implement your own PRNG entirely in the macro land, whether you could seed it correctly is another question. But the use cases described here seem to me that only uniqueness is necessary, not randomness.

**Comment by Blacksmoke16** [comment]
It doesn't have to be `hash` itself, having something like `md5` or some sha method would work too. But either way, #8835 would deff make all this easier I think as you could share the logic to create an ID versus needing to remember to increment that value in each place you use it.

> In your first example you could call `.symbolize` instead of `.hash` and it would in fact just work as a globally unique identifier.

:exploding_head: This is a great idea. I think I could just do this, have another hash to map between these unique tuple symbols and a globally unique counter as part of the service ID. I think this will be enough for my use case.

I'm going to close this given there are some reasonable solutions for my use case. I'll re-open if I run into an issue when I get to actually implementing this feature.
