### ISSUE TITLE
Enum in string interpolation uses integer value instead of name

### ISSUE THREAD

**Issue by icy-arctic-fox** [crystal-lang/crystal#14150]
## Bug Report

Latest nightly (as of creating this issue) has this issue. Crystal v1.10.1 does not.

The following code:

```crystal
enum Test
  Foo
end

puts "#{Test::Foo}"
puts Test::Foo
```

In the latest nightly produces:

    0
    Foo

and in v1.10.1:

    Foo
    Foo

**Comment by straight-shoota** [comment]
This regression was introduced by #12671
