### ISSUE TITLE
Match options overridden

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#14177]
When resolving merge conflicts within https://github.com/crystal-lang/crystal/pull/13353/commits/a77c516812a85d2855e382995d5ebbb45e7c550b, it was missed that `#split` and `#scan` override the `options` variable to `None` regardless of what the user passed in. I can't imagine this being expected behavior.

This leads to some subtle bugs such as:
```crystal
"Hello, World".rindex(/[ ]+/, options: :anchored) # => 6
```
when it should in fact be `nil`.

**Comment by straight-shoota** [comment]
For reference, this was introduced in #13353.
