### ISSUE TITLE
inconsistent documenation for virtual_and_abstract_types.html 

### ISSUE THREAD

**Issue by femto** [crystal-lang/crystal#14171]
## Bug Report

while reading specification https://crystal-lang.org/reference/1.10/syntax_and_semantics/virtual_and_abstract_types.html
```
abstract class Animal
 
  end

class Dog < Animal
  def talk
    "Woof!"
  end
end

class Cat < Animal
  def talk
    "Miau"
  end
end



if 1
  pet = Dog.new
else
  pet = Cat.new
end
puts typeof(pet)


```
returns  Animal, but documentation says it's "Animal+", so perhaps behaviors changes on different version?

Also a question:
```
class X < Animal 

end
puts pet.talk #undefined method 'talk' for X (compile-time type is Animal+)
```
I add X and then it reports error #undefined method 'talk' for X (compile-time type is Animal+),
does that mean crystal will try find all subclasses of Animal, if any one of them doesn't define talk,
then will report error?

**Comment by Blacksmoke16** [comment]
For reference only https://github.com/crystal-lang/crystal/pull/12734 was the PR that changed this behavior, starting in the `1.7.0` release. Probably something we should just move to `crystal-book` repo assuming this is expected?

And yes, Crystal sees that not all children of `Animal` implement the method you're calling and results in the error you see there.

**Comment by femto** [comment]
the example you provided produces
Error: expected argument #1 to 'test' to be Int32, not Animal
so it's also Animal, not Animal+
```
pet : Animal = Cat.new

puts typeof(pet)
puts pet.class
pet = Dog.new
puts typeof(pet)
puts pet.class

pet = Cat.new
puts typeof(pet)
puts pet.class
```
this produces
```
Animal
Cat
Dog
Dog
Cat
Cat
```
assuming typeof refers to compile type
outputting Dog or Cat for typeof seems wrong

**Comment by Blacksmoke16** [comment]
> so it's also Animal, not Animal+

Right, as I mentioned this behavior changed starting in version `1.7.0`. 

> outputting Dog or Cat for typeof seems wrong

It's not tho. The first `pet` is explicitly typed as `Animal` so that's what it is. However for the next two, you're doing explicit assigns of a specific type (dog or cat) so the compiler can guarantee that type of `pet` at that time is of one of the concrete implementations.

**Comment by femto** [comment]
```
x : Int32 = 1
x = 1_i64

puts x.class
puts typeof(x)
```
outputs
```
Int32
Int32
```
which is different behavior with pet example.
If assuming compiler know I explictly assign x an Int64,
it should output Int64

**Comment by beta-ziliani** [comment]
Here the situation is different: it's downcasting `1_i64` because it knows it fits in an `Int32`. From https://crystal-lang.org/reference/1.10/syntax_and_semantics/autocasting.html#number-autocasting :
> Number literals are always casted when the actual value of the literal fits the target type, despite of its type.

**Comment by beta-ziliani** [comment]
I don't follow. These two cases work as expected, in the previous one I mention there's an expected downcast on number literals going on. What are you missing?

**Comment by femto** [comment]
I guess for x=1_i64 you mean if x has been declared a smaller  ,
I kind of get your meaning.

For the second,it's consistent behavior when used with Animal / String
for Animal example, the reassignment changes both compile/runtime to Dog,
for String example, the reassignment just throws an error

**Comment by Blacksmoke16** [comment]
> for Animal example, the reassignment changes both compile/runtime to Dog,

It doesn't cause an error because both `Dog` and `Cat` are subclasses of `Animal`, so they are compatible with that restriction. You'd get an error if you tried to do like `pet = 10`, just like you do with the string example. So I'd say this is working as expected.

**Comment by Blacksmoke16** [comment]
I took another pass at this and I don't think anything is actually wrong.

1. The original example is somewhat diff than the docs given it has `abstract class Animal` vs `class Animal` which changes things.
2. `typeof`, afaik, never included the `+` in its values.
3. `crystal tool hierarchy` still shows the `+` type.
4. The `john.pet.talk` example still matches what are in the docs

Going to close this as I don't think there's anything that's actionable.
