### ISSUE TITLE
CI failed on my fork

### ISSUE THREAD

**Issue by femto** [crystal-lang/crystal#14175]
## Bug Report

Hello, I try to set up my environment, and my fork sync to crystal,
it fails on lastest commit
(https://github.com/femto/crystal/actions/runs/7428954162)],
is this normal?

**Comment by straight-shoota** [comment]
Yeah, that happens on the main repo sometimes as well. Iterpreter specs are somewhat flaky. It's become pretty rare by now, but sometimes there's an odd failure.
