### ISSUE TITLE
What's the current status of standard library?

### ISSUE THREAD

**Issue by femto** [crystal-lang/crystal#14172]
## Discussion

I see 
`Adding missing bits of the standard library, and/or improving its performance`
in contributing document, What's the current status of standard library?

In ruby there's distinction of corelib and stdlib, basically corelib means `implemented in
c and no need to require`, stdlib means `implemented using ruby and under lib dir
and needs to require`, so does it mean crystal's corelib is already finished? and only what left is stdlib?

**Comment by straight-shoota** [comment]
In Crystal there's not such a clear distinction. The core library is part of the standard library. It's those parts which the prelude implicitly requires (no need to require explicitly). But that's the only difference from other parts of the standard library. Everything's in the same place and everything is implemented in Crystal.

Regarding feature completeness, I think the entire standard library is pretty saturated and in a usable state. It probably doesn't need to expand that much in breadth. Although there are certainly high-level features that we still might want to add at some point.
And there are many places to grow in depth, adding smaller features to existing libraries etc.

**Comment by femto** [comment]
what do you mean by grow in depth, adding smaller features to existing libraries?
what's missing? Maybe I can start contributing to adding standard libraries?

**Comment by Fryguy** [comment]
You can also look at Ruby's standard library and compare to Crystal's standard library to see what methods or classes are missing.  While Crystal is not trying to match Ruby 1-for-1, there may be things that were missed over time that would make good additions.  Be sure to search open issues first, and then open a separate discussion issue if you want to implement something new as the Crystal team may prefer it as a separate shard instead.

**Comment by femto** [comment]
ok, will look into it.

**Comment by straight-shoota** [comment]
Closing. There's nothing actionable here.

For future reference, https://forum.crystal-lang.org/ is a better place to ask these kind of questions. Thank you 🙇
