### ISSUE TITLE
About &.

### ISSUE THREAD

**Issue by femto** [crystal-lang/crystal#14184]
## Discussion

It seemed &.foo is same as &:foo in ruby,
I propose just using &:foo syntax.

which &:foo is not new grammar, but &anyvar in disguise, where now anyvar happens to be a Symbol,
the bar(&foo) in ruby actually does the following thing,
calls to_proc on foo to convert to a proc and then pass to bar.

![image](https://github.com/crystal-lang/crystal/assets/6938/c5c452f8-6a41-4980-a2b7-87e6939d6242)
a search in rails yields this,
since it's framework, framework defined some framework class and let user uses it, user invokes some_method(&framework_instance) and it appears to user it acts like block
(if it's your own project that probably you can accept a little more typing of to_proc)

so I would suggest also supports to_proc protocol as ruby does,
where saves &. as other use (no breaking change now then can use &. as current usage,
if breaking change then can change &. meaning in 2.0 to other meaning,
like safe navigation operator,
https://stackoverflow.com/questions/36812647/what-does-ampersand-dot-mean-in-ruby,
(but this is another discussion)

**Comment by yxhuvud** [comment]
> It seemed &.foo is same as &:foo in ruby,

No, because the `&.` syntax also allows things like `foo.each &.upcase.split.map &.reverse` . Crystal is not Ruby, even if they sometimes look quite like each other.
