### ISSUE TITLE
Is Class superclass correct?

### ISSUE THREAD

**Issue by femto** [crystal-lang/crystal#14182]
## Discussion
```
{% puts Class.ancestors %}
```
outputs
[Value, Object]
Class should be reference, not Value, and I look source code
```
class Class
```
it is class Class, not struct Class.

Is this a mistake?

**Comment by Blacksmoke16** [comment]
I'm sure someone can give a more detailed explanation, but yes this is expected.

**Comment by Sija** [comment]
I'm pretty sure this topic was touched upon multiple times, it's just a matter of doing thorough search.
