### ISSUE TITLE
Crystal 1.11.0 cannot build older Crystal stdlib

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#14194]
The 1.11.0 compiler is unable to build a program with an older version of stdlib. The reason for this is the introduction of `ReferenceStorage(T)` (https://github.com/crystal-lang/crystal/pull/14106). The compiler knows this type and defines it, yet it does not fully implement it. Current stlib does take care of this, but older versions do not, leaving the implementation missing.

This is the error message:
```
Error: abstract `def Object#hash(hasher)` must be implemented by ReferenceStorage(T)
```

**Comment by straight-shoota** [comment]
`ReferenceStorage` is experimental anyways, so the easiest solution would be to revert that commit.

Alternatively, we could implement a backwards-compatible definition. The compiler could only use this type if it's already defined in the program, otherwise skip it. Or we define the proper inheritance in the compiler, I suppose we just need to explicitly declare that it inherits `struct` or something.

**Comment by HertzDevil** [comment]
`ReferenceStorage` does not inherit from `Struct`, which is why the error shows up in the first place.

The solution would probably be having the first definition in code create the underlying class, rather than making it built-in. The definition in code would then be annotated:

```crystal
@[Primitive(:type)]
struct ReferenceStorage(T) < Value
end
```

**Comment by straight-shoota** [comment]
#14204 looks like a great solution 🚀 

I feel this might be a bit much for a patch release though. So perhaps we better just revert https://github.com/crystal-lang/crystal/pull/14106 for now and merge the new implementation later (i.e. for 0.12.0)?
`ReferenceStorage` is completely new and experimental, so it wouldn't be a big issue to postpone it. It's a bit of a bummer that experimenting wouldn't be possible then with 1.11 and it will require a newer compiler build. But nightlies should be fine for experimentation, so I don't think it's a big loss.

**Comment by zw963** [comment]
I meet basically same issue, when build 1.11.0, i meet #14198 and interpreter not work, when i want to build 1.10.1 use new compiler, it failed.

**Comment by straight-shoota** [comment]
Resolved by https://github.com/crystal-lang/crystal/pull/14207
