### ISSUE TITLE
make captured proc type declaration optional

### ISSUE THREAD

**Issue by femto** [crystal-lang/crystal#14202]
## Discussion

after [this]( https://forum.crystal-lang.org/t/is-this-correct/6279/7), I'm still confused
why crystal has to specify type when captured block.
It's mental burden for user to remember there's a difference between captured block and not  captured block,
can we unify this?

Propose: compile proc to prototype bytecode, when real call instantiate it.
just like https://github.com/crystal-lang/crystal/issues/14201 here,
method-->bytecode.

currently I see interpreter has bytecode in it, 
so I want to ask, 
 does the crystal compiler compiles to bytecode/VM(which means crystal has a VM), or does crystal
compiles directly to llvm ir? (because interpreter seems go the bytecode route)

**Comment by straight-shoota** [comment]
This is an issue tracker for *actionable* items. An open discussion about the possibility to change a language feature is *not* an actionable item. It only becomes an actionable item once there is a clear plan about how to implement it and at least some reasonable consensus about that plan.

This kind of discussion belongs in the forum, not the issue tracker. Closing.

**Comment by yxhuvud** [comment]
That said, if someone actually manages to make captured blocks automatically figure out the signature based on how the input and output and how the block is used, then it would be **very** sweet to have as it can sometimes make interfaces a more unwieldy than is desired (especially around generics and the like). 

But the recent stream of issues that basically wish to make crystal into ruby is not great as they don't fit the language and doesn't show that the person filing the issue actually understand that Crystal is not Ruby, and that runtime dynamic features in Ruby just don't fit the language. However, I do not agree the plan of how to implement it needs is the thing that is lacking, really. I'd rather phrase a good issue as being _realistically possible to implement without changing everything about the language_, even if there is no concrete plan of how to implement it.

Also, as the language is clearly very inspired by Ruby, when thinking about features that exist in Ruby and not in Crystal, please assume that there is a reason behind the difference, at least for features that have existed in Ruby for a long time. Smart people that (at least most of them) understand Ruby have implemented Crystal - please don't assume they have been negligent in the choice of features. If it is hard to understand why the difference is there, go to the forum (or discord) and ask about it. And also please at least do a cursory look in the issue tracker if there already have been issues around the question at hand.
