### ISSUE TITLE
`osx` flag

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#14238]
While making sure all flags are properly documented (https://github.com/crystal-lang/crystal-book/pull/734), I found a dubious `osx` compiler flag used in debug codegen:

https://github.com/crystal-lang/crystal/blob/bb96c5398e001f41b31431eea283a1a28198a84b/src/compiler/crystal/codegen/debug.cr#L50

This flag is never implicitly set anywhere by the compiler. For MacOS we're using the flag `darwin`. So this can only work if `-Dosx` is passed to the compiler explicitly via command line argument. This seems a bit odd.

The flag was originally introduced in [#3439](https://github.com/crystal-lang/crystal/pull/3439). At that time the implicit OS flag was also `darwin` so it should've never had any implicit effect.
I'm not sure if the odd naming is intentional, but probably not?

Either way, I don't think it's used anywhere, so it might be fine to remove it?
If still necessary for something, as an explicit flag it should have a more descriptive name.

@ysbaddaden Do you have any recollection on this?

**Comment by ysbaddaden** [comment]
Looking at git blame, this dates from #3439 that added support for LLVM 3.9. It was meant to keep DWARF v2 on macOS for some reason. I was probably following Rust (hence the wrong flag), but it was never limited in practice, so I guess it's safe to drop.

Looking at Rust, they're now using DWARF v4 by default but Android, DragonflyBSD, FreeBSD, NetBSD (v2) and AIX (v3). I found a [reference to clang](https://github.com/llvm/llvm-project/blob/378778a0d10c2f8d5df8ceff81f95b6002984a4b/clang/lib/Driver/ToolChains/Darwin.cpp#L1202-L1208) that says macOS 10.11 and iOS9 started supporting v4 (older versions v2 only).

Searching for `GetDefaultDwarfVersion()` in current clang, they use v4 for Android and a bunch other targets, but v2 for OpenBSD and CUDA, and the rest is by default (I can't find which version).

So we can drop both flags.

**Comment by ysbaddaden** [comment]
Hum, something we don't have in Crystal: a centralized definition per target triple. For example having a `dwarf_version` variable with a default value, and that can be overriden by each .

Each of clang and rust have a `dwarf version` variable that can be overriden by each target or toolchain (darwin, linux, linux+android, risc, ...).
