### ISSUE TITLE
The latest Windows version released so far has an incorrect version of the exe still at version 1.11.0.

### ISSUE THREAD

**Issue by fenginsc** [crystal-lang/crystal#14247]
The latest Windows version released so far has an incorrect version of the exe still at version 1.11.0(https://github.com/crystal-lang/crystal/releases/tag/1.11.1).
When will the windows version get full support, the windows version doesn't seem to be able to use REPL at the moment either.

**Comment by straight-shoota** [comment]
Fixed. Apparently the release got the wrong version of the installer 🙈 
Thanks for reporting.
