### ISSUE TITLE
IO::Error no parameter named 'cause'

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/crystal#14241]
Maybe a regression? This compiles fine in Crystal 1.10.1, but fails to compile in Crystal 1.11.1

```crystal
error = Exception.new("oops")
IO::Error.new("parsing proxy initialization", cause: error)
```

```
In lib/connect-proxy/src/connect-proxy.cr:134:23

 134 | raise IO::Error.new("parsing proxy initialization", cause: error)
                       ^--
Error: no parameter named 'cause'

Overloads are:
 - IO::Error.new(message : String | ::Nil = nil, *, target = nil)
```

I opened an issue here https://github.com/spider-gazelle/connect-proxy/issues/4

**Comment by straight-shoota** [comment]
Yeah, this is caused by #13865 which introduces a new def `IO::Error#initialize`. This removes all inherited `#initialize` defs from `IO::Error`, which means the implementation from `Exception` with `cause` parameter isn't available anymore.

**Comment by straight-shoota** [comment]
Resolved by https://github.com/crystal-lang/crystal/pull/14242
