### ISSUE TITLE
Mise plugin for Crystal

### ISSUE THREAD

**Issue by ylluminate** [crystal-lang/crystal#14253]
## Feature Request
It would be a good marketing opportunity as well as a convenience to support Crystal in Mise:
https://github.com/mise-plugins

**Comment by straight-shoota** [comment]
Sure. Any integration would be nice.
But I don't think this is a natural feature request for the upstream project.
Such integrations are best handled by people who are actually familiar with the tool. The asdf plugin for example is also community maintained.

Feel free to coordinate efforts on https://forum.crystal-lang.org/
