### ISSUE TITLE
Converting '*' to splat results in: Error: undefined macro method 'MacroId#map' 

### ISSUE THREAD

**Issue by Vici37** [crystal-lang/crystal#14283]
## Bug Report

Hello! This code results in expected behavior, but now a warning is issued due to the splat:

```
macro test(*fields)
  puts {{
    *fields.map do |field|
      "#{field}".id
    end
    }}
  {% debug %}
end

hello = "world"
test(hello)
```

Attempting to fix it via: 

```
macro test(*fields)
  puts {{
    fields.splat.map do |field|
      "#{field}".id
    end
    }}
  {% debug %}
end

hello = "world"
test(hello)
```

results in the error `Error: undefined macro method 'MacroId#map' `.

Any suggestions on how to remove the warning but maintain the same behavior? Going directly to `fields.map` causes the results to turn into a tuple wrapped in `{...}` :/

```
> crystal --version
Crystal 1.11.2 [fda656c71] (2024-01-18)

LLVM: 15.0.7
Default target: x86_64-unknown-linux-gnu
```

Thank you for any guidance you can provide!

**Comment by Blacksmoke16** [comment]
Yea, you can literally just do `puts {{ fields.splat }}` and call it a day :P

**Comment by HertzDevil** [comment]
or `join` if you still need a custom transformation

**Comment by Vici37** [comment]
Thank you kindly everyone! In my real code, I have something non-trivial inside the map method itself, so it can't be reduced. Good to know the `splat` method goes at the end of the method call instead, the precedence order was what confused me :)

Thanks!
