### ISSUE TITLE
Static linking mode fails on Arch Linux

### ISSUE THREAD

**Issue by amini-allight** [crystal-lang/crystal#14295]
I have a copy of Crystal installed via the [default Arch Linux package](https://archlinux.org/packages/extra/x86_64/crystal/). This distribution of Crystal is unable to use the static linking feature, for example if you write the following program:

```cr
puts "Hello world!"
```

And try to compile it with the following command:

```
crystal build --static example.cr
```

You will get this error:

```
/usr/bin/ld: cannot find -lgc (this usually means you need to install the development package for libgc): No such file or directory
/usr/bin/ld: cannot find -levent (this usually means you need to install the development package for libevent): No such file or directory
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with exit status 1: clang "${@}" -o /home/amini/test/example  -rdynamic -static -L/usr/bin/../lib/crystal -lpcre2-8 -lgc -lpthread -ldl -lpthread -levent -lrt -lpthread -ldl
```

This error occurs because the Arch Linux packages for [libgc](https://archlinux.org/packages/core/x86_64/gc/) and [libevent](https://archlinux.org/packages/core/x86_64/libevent/) do not include .a object archives, they only contain .so dynamic link libraries, making static linking impossible. If your Crystal program uses other features, for example the YAML portion of the standard library, you can also have issues with other libraries such as [libyaml](https://archlinux.org/packages/extra/x86_64/libyaml/) for the same reason. The advice emitted by Crystal to install development versions of the package seems to be aimed at Debian-based and/or RHEL-based distributions: Arch does not have the concept of development vs. deployment packages. To fix this on Arch you would need to install the bleeding edge versions of these packages from the AUR, modifying the PKGBUILD files to enable the emission of static linkage binaries.

I'm not entirely sure what can be done about this given the limitations imposed by Arch Linux's packaging style but I thought I should report it anyway.

**Comment by Blacksmoke16** [comment]
My understanding is this is kinda expected. Even if you could get `.a` file for `libgc` and `libevent`, you're still going to be limited given arch uses `glibc`, which doesn't play well with static linking. At which point you could have other libs statically linked while dynamically linking `libc`.

Not really sure there's anything actionable here?

Related: https://crystal-lang.org/reference/1.11/guides/static_linking.html

**Comment by amini-allight** [comment]
The problem probably can't be fixed but maybe it could be signposted better? Some ideas:

- The flag could be removed entirely in Arch builds (not great, might be confusing)
- The flag could refuse to execute in Arch builds and instead print a message explaining the situation (better, but still might be annoying for people who want to hack together something that works on Arch)
- The flag could try to execute, fail and then deliver a message that more clearly explains the issue without reference to Debian-specific functionality (probably the best option)
- Crystal could ship with its own copies of these libraries on Arch, enabling the feature to work (don't know how practical this is)

**Comment by Blacksmoke16** [comment]
FWIW the messaging you see isn't from Crystal, but instead from the linker `ld`; so a bit outside of the control of Crystal itself. The Arch build is also a community thing, and not officially maintained by the core team. If the maintainer of it wants to ship additional libraries with it that would be on them. But in the end wouldn't make all that much of a difference since you'd still have to work around `glibc`; but would at least allow only having a single dynamically linked lib vs all three (or four). 

In the end what's your use case for wanting to link statically on Arch directly? Easiest solution is to do what the docs suggest and do that via Docker and Alpine. Could consider proposing some changes on the forums https://forum.crystal-lang.org/ for discussion until something actionable is determined. But don't really think having Arch specific behavior is the way to go.

**Comment by amini-allight** [comment]
My use case is deploying an application written in Crystal to a virtual machine in the cloud. It's quite a predicament.

- My desktop runs Arch Linux.
- The virtual machine cannot be Arch itself because I don't believe Arch builds for AWS are available anymore.
- The virtual machine is too weak to build the application locally. The Crystal compiler consumes far too much memory. It can be made more powerful but that requires going up a full two cost classes with AWS (from t3.nano to t3.small) for an operation that only needs to be performed sporadically.

Compiling locally, copying over the required shared libraries and then running the executable with `LD_LIBRARY_PATH=.` worked for a while until the version sync between Arch and Ubuntu became too bad and `libc` broke. I then tried this static linking approach only to discover it was broken. Now I have a much more powerful Ubuntu virtual machine locally which I use to do a compilation against Ubuntu libraries which will hopefully be a permanent solution to the problem.

The root cause is really the memory consumption of the compiler: there exist relatively roomy environments (0.5 - 1 GiB of memory, potentially larger depending on the size of your program) where the final binary would run great but the compiler necessary to produce that binary cannot run. But there already seems to an issue open for that (#12879) and it sounds extremely difficult to fix.

**Comment by Blacksmoke16** [comment]
But why don't you just use the Official Alpine Docker image to build a fully static binary? This would allow you to just copy the built binary to your VPS and not have to worry about about copying shared libs, or having extra VMs.

**Comment by amini-allight** [comment]
The simple answer is I was unaware of that page in the docs until you linked it :sweat_smile:

**Comment by Blacksmoke16** [comment]
Haha fair enough. That's ultimately your solution. Just works wayyy better for static linking, and can do it within a single command.

**Comment by straight-shoota** [comment]
> - The flag could be removed entirely in Arch builds (not great, might be confusing)
> - The flag could refuse to execute in Arch builds and instead print a message explaining the situation (better, but still might be annoying for people who want to hack together something that works on Arch)

Both wouldn't be good solutions. As a compiler flag, `--static` works completely fine on Arch as on any other system. It's some dependencies that have issues with static linking. But that's not the compiler's fault. You can technically build statically linked programs perfectly fine on Arch as well. Just not when linking against the default C standard library.

> - The flag could try to execute, fail and then deliver a message that more clearly explains the issue without reference to Debian-specific functionality (probably the best option)

Yes, it would probably be helpful to improve the error message related to link failures with `--static`. Especially when building for targets that are known to be problematic in that regard.
What do you mean with "Debian-specific functionality" though?

> - Crystal could ship with its own copies of these libraries on Arch, enabling the feature to work (don't know how practical this is)

That won't work. As @Blacksmoke16 already mentioned, the static versions of *some* libraries (such as `libgc`) could indeed be provided (and we do/did that), but the main issue is with `glibc` which is harder to integrate. This might be an option to explore for downstream package maintainers, but I don't think it's a feasible task for the Crystal project.
