### ISSUE TITLE
Some `IO::FileDescriptor` methods are implemented in `Crystal::System::File`

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#14311]
```mermaid
flowchart BT
File --> IO::FileDescriptor
File --> Crystal::System::File
IO::FileDescriptor --> Crystal::System::FileDescriptor
```

These methods of `IO::FileDescriptor` are implemented in `Crystal::System::File` instead of `Crystal::System::FileDescriptor`:

* `#fsync` -> `#system_fsync`
* `#flock_shared` -> `#system_flock_shared`
* `#flock_exclusive` -> `#system_flock_exclusive`
* `#flock_unlock` -> `#system_flock_unlock`

Thus it is always a compilation error to call them on `IO::FileDescriptor`s that aren't `File`s:

```crystal
STDOUT.fsync            # Error: undefined method 'system_fsync' for IO::FileDescriptor
IO.pipe[0].flock_shared # Error: undefined method 'system_flock_shared' for IO::FileDescriptor
```

Either the methods in `IO::FileDescriptor` should be moved down to `File`, or the `#system_` implementations should be moved to `Crystal::System::FileDescriptor`.

**Comment by straight-shoota** [comment]
IIUC, the only difference between `IO::FileDescriptor` and `File` is that the latter has an associated path, captured in an additional ivar.

So I suppose all methods that operate on a file descriptor make sense for `IO::FileDescriptor` and there's no reason to restrict them to `File` instances.
