### ISSUE TITLE
Can't initialize a struct inside `#pre_initialize`

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/crystal#14325]
The following example fails to compile with a LLVM IR error, because of the struct initialization that ends up in the `#pre_initialize` method. I first notices the issue with an atomic, but any plain struct behaves wrongly.

A workaround is to move the ivar initialization to `#initialize` and it will compile correctly. Changing the struct for an Int32 also fixes compilation and the object will be correctly initialized.

```crystal
struct Bar
  def initialize(@value : Int32)
  end
end

class Foo
  @n = Bar.new(123)

  def self.malloc : self
    ptr = LibC.malloc(sizeof(Foo))
    Foo.pre_initialize(ptr)
    ptr.as(Foo).tap(&.initialize)
  end
end

p Foo.malloc
```

```
Module validation failed: Load operand must be a pointer.
  %4 = load %"Bar", %Nil zeroinitializer, align 4, !dbg !12
```

**Comment by HertzDevil** [comment]
It looks like this only happens if the result of `Foo.pre_initialize` isn't assigned to a variable (which is the correct usage)

**Comment by HertzDevil** [comment]
Actually, this happens to the plain `.allocate` as well even before `.pre_initialize` was introduced: https://play.crystal-lang.org/#/r/giol

**Comment by ysbaddaden** [comment]
Oh, I missed that `#pre_initialize` returned the reference already.

It might be interesting to understand what's happening, but that was my misuse. I'll close.

**Comment by straight-shoota** [comment]
But this is still an error in the compiler. If the code is invalid, the compiler should give a reasonable error description, not an arbitrary codegen error.
