### ISSUE TITLE
'crystal -v' output format

### ISSUE THREAD

**Issue by sdogruyol** [crystal-lang/crystal#1434]
Currently the output of the command 'crystal -v' is not so friendly. It doesn't show the platform and revision like Ruby does

In crystal

```
crystal -v
Crystal 0.7.7 [170f859] (Sat Sep  5 02:46:31 UTC 2015)
```

In Ruby

```
ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
```

I really prefer the latter output. What do you think?

**Comment by jhass** [comment]
So add the platform? The revision is the thing in square brackets. We're using git not SVN.

**Comment by sdogruyol** [comment]
Yeah adding the platform and formatting the time with git hash will be OK and i can make a PR for this.

```
Crystal 0.7.7 (2015-04-13 at commit 170f859) [x86_64-darwin14]
```

What do you think?

**Comment by asterite** [comment]
Sounds good. I don't know why it's useful, though. You can infer that string piece from `uname -a`, but you can't infer the executable version, git commit or the date it was built. But if many find it useful we can add it.

**Comment by marceloboeira** [comment]
@sdogruyol / @asterite what is the status on this? I'm currently searching old issues since we have like 254. Since its a simple issue we could start applying the `easy` label, in order to make it easy for people to identify and create PR's. Let me know what do you think.

**Comment by asterite** [comment]
Is there a **real** need for this? Do you need to do something programatically with that? Why do you need the version to output `x86_64-darwin14` if you most probably already know you are on a mac/linux?

**Comment by sdogruyol** [comment]
@asterite not a ***real*** need for now. Closing.
