### ISSUE TITLE
`Number#humanize` and `Int#humanize_bytes` should separate number and unit by a space

### ISSUE THREAD

**Issue by philipp-kempgen** [crystal-lang/crystal#14349]
## Discussion

`Number#humanize` and `Int#humanize_bytes` should separate the numerical value and unit by a space, according to international standards.

The kind of space should be passed as an argument.

Examples of what you may want to pass as a `space` argument (non-exhaustive):
- `nil` - nothing, for the current behavior
- `'\u0020'` resp. `' '` – a plain space, might be the most compatible space character
- `'\u00A0'` – a non-breaking space
- `'\u2009'` – a thin space
- `'\u202F'` – a thin non-breaking space

### References:

https://en.wikipedia.org/w/index.php?title=Space_(punctuation)&oldid=1211874527#Unit_symbols_and_numbers

> The International System of Units (SI) prescribes inserting a space between a number and a unit of measurement […]

https://en.wikipedia.org/w/index.php?title=ISO_31-0&oldid=1193092792#Expressions

> Numerical value and unit symbol are separated by a space. […]

**Comment by straight-shoota** [comment]
Adding an option to configure a space between value and unit sounds like a good idea.

There are good practical reasons to skip the space in an environment where machine readability matters. Grepping formatted numbers is much easier if you don't have to account for whitespace, for example.
So I'd prefer to leave the current behaviour as default. Also to avoid disruptions.
