### ISSUE TITLE
Regression: Interrupted system call in CI

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#14350]
Looks like we have a regression in master. The build for current HEAD is broken:

https://github.com/crystal-lang/crystal/actions/runs/8178703060/job/22363225395

Error message:

> Error writing file (#<IO::FileDescriptor:0x7ff6dd163e00>): Interrupted system call (IO::Error)

A very similar error had previously appeared in https://github.com/crystal-lang/crystal/pull/14343 ([failed job](https://github.com/crystal-lang/crystal/actions/runs/8157395142/job/22296977691)) but it went through after a retry, so I considered it a fluke.
It's entirely plausible that this PR is causing the error. It does some changes to the IO system interface.
But it could also be something else. We had some PRs that change concurrency lately, for example.

The master CI workflow has another interesting failure in the MT job: https://github.com/crystal-lang/crystal/actions/runs/8178703060/job/22363221791
It seems that the state memory of `Colorize` is compromised because it inserts reset codes (`0;`) even when the last state is default and thus wouldn't require it. Not sure if this is even connected to the interrupted syscall, but it would point towards a concurrency issue.

**Comment by ysbaddaden** [comment]
Reading the [signal(7)](https://www.man7.org/linux/man-pages/man7/signal.7.html) man page, we might just need to add the `SA_RESTART` flag?

**Comment by ysbaddaden** [comment]
From the `signal(2)` man page:

> The situation on Linux is as follows:
> * The kernel's signal() system call provides System V semantics.
> * By default, in glibc 2 and later, the signal() wrapper function does not invoke the kernel system call. Instead, it calls [sigaction(2)](https://www.man7.org/linux/man-pages/man2/sigaction.2.html) using flags that supply BSD semantics.

> The BSD semantics are equivalent to calling [sigaction(2)](https://www.man7.org/linux/man-pages/man2/sigaction.2.html) with the following flags:
>
> `sa.sa_flags = SA_RESTART;`

**Comment by HertzDevil** [comment]
It looks like none of the bindings define `LibC::SA_RESTART`, so maybe it's best to use `sigaction` there only when `{{ flag?(:solaris) }}` is true?

**Comment by ysbaddaden** [comment]
I pushed without checking :facepalm:

Luckily, I have a copy of many `/usr/include` on my computer from when I wrote the [posix](https://github.com/ysbaddaden/posix) shard. They date from many years back, but constants for syscalls are unlikely to ever change.

That being said, I wish I could just say "I want SA_RESTART please figure its actual value".

**Comment by straight-shoota** [comment]
> but constants for syscalls are unlikely to ever change.

Yeah, that would lead to very surprising results 😆
