### ISSUE TITLE
Is an html strip-tags method a worth stdlib addition?

### ISSUE THREAD

**Issue by robacarp** [crystal-lang/crystal#14356]
I'm working on a pure-crystal implementation of an HTML utility function called `striptags`. Would it be a welcome contribution to stdlib, perhaps under [HTML](https://crystal-lang.org/api/1.11.2/HTML.html), which currently provides only escape/unescape?

The implementation I'm working is a little more enhanced than just `XML.parse(dirty).inner_text` (a la [crinja's striptags](https://github.com/straight-shoota/crinja/blob/5d5c190adc9693b9481e5d7a144aebec0f544bad/src/lib/filter/string.cr#L27)) -- I have added the ability to whitelist tags and attributes which can stay in the document, and it filters out the rest.

I was surprised to see a lack of html strip-tags routines in use in the crystal ecosystem. There are some minimal attempts, [in crynja](https://github.com/straight-shoota/crinja/blob/5d5c190adc9693b9481e5d7a144aebec0f544bad/src/lib/filter/string.cr#L27) and in a handcrafted [rust aggregator](https://github.com/wezm/read-rust/blob/master/crystal/src/utils/sanitise.cr) -- the latter seemed promising but eventually I realized it is simply [wrapping a function from a rust crate](https://github.com/wezm/libstriptags/blob/master/src/sanitise.rs).

### NEED
This function is important for user contributed content sites, because it allows a non-regex based way of sanitizing user markup while still allowing user contributed markup. Attempts to sanitize html by way of regexes are notorious for being XSS vectors. 

### Comparison / Community Interest Survey
- Rust [has a crate which provides a striptags implementation](https://docs.rs/sanitize_html/latest/sanitize_html/), and it was ported over to crystal for the above linked project. There is also a Crate called [Ammonia](https://docs.rs/ammonia/latest/ammonia/) which provides whitelist-style sanitation.
- Rails ActiveSupport also provides access to a [well established](https://github.com/flavorjones/loofah) gem for which ActiveSupport wraps into a function called striptags. This includes a whitelist, and also filters html attributes.
- [PHP provides this function](https://www.php.net/manual/en/function.strip-tags.php), and it has a whitelist. It does not filter tag attributes, and it warns that it is insufficient for XSS prevention (likely due to the attribute filter issue).
- Python seems to have a storied history here. A [StackOverflow post](https://stackoverflow.com/questions/753052/strip-html-from-strings-in-python) became canonical, included in Django, and then was found to be vulnerable to XSS. That SO post was viewed 350k times over 15 years. There is now a library called [Bleach](https://bleach.readthedocs.io/en/latest/clean.html) ([provided by Mozilla](https://github.com/mozilla/bleach) - 2.5k stars on github) which provides this feature, including a whitelist. As of about a year ago Bleach is [deprecated](https://github.com/mozilla/bleach/issues/698). There is a new project called [nh3](https://github.com/messense/nh3) which is importing in the Ammonia HTML sanitizer from Rust.

### Risks
- stdlib bloat -- is it worth it to have this ability in stdlib?
- getting it wrong -- if it's wrong, and people depend on it, then it'll be the source of a Crystal core CVE. On the other hand, if it's right, people can reach for it instead of resorting to a regex -- I saw one such `str =~ /^\<\w+\>/` example in my searches.

### Other options
- It could be published as a shard, as has been done in several of the languages I surveyed. I believe that there is enough interest demonstrated that including it could be part of the "batteries included" notion, if that's still a thing.
- It could just be published on my blog or in a random SO article, as Python's was for so long.

Cheers!

**Comment by straight-shoota** [comment]
Sounds like you're looking for https://github.com/straight-shoota/sanitize

I published this as a shard for independent development and because of its complexity. I could see this shard (or a similar implementation) becoming a part of stdlib if we consider the use case to be very common. It's certainly an very important feature when you're dealing with untrusted HTML content.

**Comment by robacarp** [comment]
Absolutely excellent, and I wish I'd been able to come across that in my searches.

**Comment by straight-shoota** [comment]
Yeah, I guess there are quite a lot different terms for this kind of thing. Probably because you can view and resolve the problem from different angles. So that's not ideal for search.

What did you look for and where? Maybe we can improve discoverability a bit.

**Comment by robacarp** [comment]
I was focused on the keyword "striptags". I looked in the [HTML parsing section](https://github.com/veelenga/awesome-crystal?tab=readme-ov-file#htmlxml-parsing) of awesome-crystal, and I search github for `lang:Crystal striptags` -- which is where I came across the inner-text pattern in crinja I referenced.

**Comment by straight-shoota** [comment]
Thanks. [`lang:Crystal striptags`](https://github.com/search?q=lang%3ACrystal%20striptags&type=repositories) works now 😏

https://shardbox.org/categories/HTML_XML_Parsing would've brought you there as well.

**Comment by robacarp** [comment]
I've forgotten about or never heard of shardbox.org, but that makes me realize that I would have found it with https://shards.info/search?query=html too.

**Comment by kostya** [comment]
this example also similar to strip tags: https://github.com/kostya/lexbor/blob/master/examples/texts.cr
