### ISSUE TITLE
Standardizing the type for timeout values

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#14368]
Several stdlib APIs use timeout values, either as type properties or method parameters.

In all internal runtime APIs (`Fiber`, `Channel` etc.), timeouts are exclusively typed as `Time::Span`.
In the networking APIs however, many APIs also accept `Number` values. I suppose this is probably a nostalgic reference to the C socket APIs? 🤷

`Number` overloads typically transform to `Time::Span` via `Int#seconds`.

Plain number values are very impractical and hard to reason about: `connect(timeout: 5)` does not state what unit `5` is. (it's typically seconds). `connect(timeout: 5.seconds)` is much clearer.
So I don't think overloads accepting `Number` are useful and suggest to deprecate them. This will help clean up the stdlib API and code that uses it will be more readable.

This is a list of all occurences I could find:

* `HTTP::Client#connect_timeout`: `Time::Span` (plus setter overload with `Number`)
* `HTTP::Client#dns_timeout`: `Time::Span` (plus setter overload with `Number`)
* `HTTP::Client#read_timeout`: `Time::Span` (plus setter overload with `Number`)
* `HTTP::Client#write_timeout`: `Time::Span` (plus setter overload with `Number`)
* `Socket#read_timeout`:[^1] `Time::Span` (plus setter overload with `Number`)
* `Socket#write_timeout`:[^1] `Time::Span` (plus setter overload with `Number`)
* `IO::FileDescriptor#read_timeout`:[^1] `Time::Span` (plus setter overload with `Number`)
* `IO::FileDescriptor#write_timeout`:[^1] `Time::Span` (plus setter overload with `Number`)
* `OpenSSL::SSL::Socket#read_timeout`: untyped, transparent delegator
* `OpenSSL::SSL::Socket#write_timeout`: untyped, transparent delegator
* `Socket#connect(timeout)`: untyped, transparent delegator; Unix `#system_connect` calls `.seconds` if not `Time::Span`; ignored on Windows
* `Addrinfo.resolve(timeout)`: untyped, unused
* `Addrinfo.tcp(timeout)`: untyped, unused
* `Addrinfo.udp(timeout)`: untyped, unused
* `TCPServer.new(dns_timeout)`: untyped, passed to `Addrinfo.tcp`
* `TCPSocket.new(connect_timeout, dns_timeout)`: untyped, passed to `Addrinfo.tcp` and `Socket#connect`

Strangely, the `HTTP::Client` instance variables are typed `Float64?`. This is super weird because they are usually passed to `Socket` APIs which use `Time::Span` primarily. So `Time::Span` values get transformed to float for storage and then back into `Time::Span`. This seems quite inefficient.
I'd also suggest to change the ivars to `Time::Span`. This should be possible without breaking anything.

[^1]: This is already counting the changes for #14367, mentioning `Socket` and `IO::FileDescriptor` as the public APIs instead of internal event loop modules.

**Comment by ysbaddaden** [comment]
I think it is a Ruby influence where timeouts are a number in seconds —I don't think Ruby has a Time::Span like type?

I think it's fine to expect a Time::Span. Even POSIX has been using `timespec_t` for a while for its timeout values.

**Comment by straight-shoota** [comment]
I think the changes from #14367, #14371 and #14372 addressed every immediate actions in this issue.

**Comment by HertzDevil** [comment]
DNS timeouts are now ultimately passed to `::sleep` on Windows since #14979, which in turn is deprecated due to #14962, so the `Addrinfo` family of methods remain deprecated if the timeout isn't a `Time::Span?`. However there is a chance the `::sleep` could be refactored away, e.g. by using `Crystal::IOCP::Event` (https://github.com/crystal-lang/crystal/pull/14949#issuecomment-2334447917)
