### ISSUE TITLE
Inconsistent `JSON::Serializable` behavior when parsing case-sensitive `Enum`s

### ISSUE THREAD

**Issue by lsndr** [crystal-lang/crystal#14379]
## Bug Report

It looks like`JSON::Serializable` does not properly serialize deserialize case-sensitive enums.

Here is the code:

```crystal
require "json"

enum Bar
  Bar
  BAr
end

struct Foo
  include JSON::Serializable

  getter bar1 : Bar
  getter bar2 : Bar


  def initialize(@bar1 : Bar, @bar2 : Bar)
  end
end

foo = Foo.new(Bar::Bar, Bar::BAr)

puts foo.bar1.to_s # Bar
puts foo.bar2.to_s # BAr
# I expect it to be {"bar1":"Bar","bar2":"BAr"}, but for some reason it lowercased enum value and added underscore
puts foo.to_json # {"bar1":"bar","bar2":"b_ar"}
# Should be the same as previous serialization
puts Foo.from_json(foo.to_json).to_json # {"bar1":"bar","bar2":"bar"}
```

Here is this code in playground: https://play.crystal-lang.org/#/r/glov

**Comment by straight-shoota** [comment]
JSON (de-)serialization of enums is generally based on lower case. That's not ideal for some use cases, but typically it works quite well as it can parse a range of different spelling variants which you might encounter in unknown JSON sources.

The same is true for `Enum.parse`, actually. And this is all documented in [`Enum.parse`](https://crystal-lang.org/api/1.11.2/Enum.html#parse%28string%3AString%29%3Aself-class-method) and [`Enum#to_json`](https://crystal-lang.org/api/1.11.2/Enum.html#to_json%28json%3AJSON%3A%3ABuilder%29-instance-method).

If you want a different behaviour for a particular enum type, you can override its `.parse` and `#to_json` methods.

**Comment by devnote-dev** [comment]
The `@[JSON::Field(key: ...)]` annotation should work here too.

**Comment by lsndr** [comment]
Ok, thanks, that's clear.

But why does serialization, deserialization and again serialization leads to such inconcistent result?

**Comment by Blacksmoke16** [comment]
I think the catch is `foo` knows that `bar1` is `Bar` while `bar2` is `BAr` and is reflected in the serialized result as such. However when you deserialize the serialized representation again, it assumes both `bar` and `b_ar` are `Bar` due to how `Enum.parse` works as called our previously.

I guess the tl;dr is don't use case sensitive enums as they can lead to a lot of confusion like this.
