### ISSUE TITLE
Introduce platform-specific `FileDescriptor::Handle`

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#14389]
In #10706 we extracted all system-specifics out of the generic `Socket` API. Part of that was the introduction of `Socket::Handle` which is an abstract type for representing a socket handle to the respective operating system.

We should do the same thing for `IO::FileDescriptor` and introduce a similar `Handle` type.

On Windows, we're actually using C file descriptors (`LibC::Int`) instead of OS handles (`LibC::HANDLE`). It's possible to gain one from the other via `_open_osfhandle` and `_get_osfhandle`. But that's a lot of extra juggling when the APIs acutally all operate on OS handles.

This was also previously mentioned in #14316:

> Ideally we could replace the type of `fd` on Windows entirely, similar to how `Socket#fd` returns a `LibC::HANDLE`, in which case we could also drop `_close` / `_dup2` / `_get_osfhandle` / `_open_osfhandle`. This isn't possible since `IO::FileDescriptor#fd` is public.

I do think it's actually possible to change this. The return type of `IO::FileDescriptor#fd` is `Int` and the documentation states the return type's size is platform-specific. So we should be good. `LibC::HANDLE` is a void pointer. We can return that (maybe casted to int) without breaking any promises.

I'd be fine with breaking the return type on Windows though (i.e. return `LibC::HANDLE` directly), because it's not a stable supported platform yet. And I'd expect minimal impact from such a change.

**Comment by HertzDevil** [comment]
For the record, https://github.com/microsoft/win32metadata declares `HANDLE` to be an alias for `UIntPtr` rather than `Void*`, so maybe `HANDLE`s are not supposed to be pointers in the first place even if the Windows SDK header says so (this in turn could affect GC behavior, see #14107)

**Comment by straight-shoota** [comment]
Yeah, I was wondering about that as well. It seems the fun bindings are using `HANDLE` in some places where the actual type should be `UIntPtr`.

Also we cannot put `LibC::HANDLE` in an `Atomic` (for `@volatile_fd`), so we actually need to store it as an integer type.

**Comment by straight-shoota** [comment]
@HertzDevil I'm not sure if #14501 fully resolves this.
There are a couple more places in the API where `FileDescriptor::Handle` should (probably) be used:

* `Crystal::System::File.mktemp`
* `Crystal::System::File.fchown`
* `IO::FileDescriptor#initialize`, `.new`

**Comment by HertzDevil** [comment]
I wouldn't worry about `fchown` as it's unlikely to be implemented
