### ISSUE TITLE
Error when requesting administrator privileges on windows with powershell

### ISSUE THREAD

**Issue by azurejoga** [crystal-lang/crystal#14408]
Hi everyone, I have a powershell script that I want to run through crystal and compile to .exe right after.
Yes, I can compile to .exe but, when using the .cr script and trying to check administrator privileges to try to run the crystal program itself or the powershell script as administrator, nothing happens.

Code.
```
def main
  request_admin_privileges
end

def request_admin_privileges
  puts "Running as a non-administrator. Requesting elevation..."
  `powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Start-Process -Verb RunAs '#{__FILE__}'"`
end

main
```

and the code to run the powershell script is:

```
def main
  script = <<-POWERSHELL
    Set-ExecutionPolicy -Scope Process -ExecutionPolicy Unrestricted -Force
    Invoke-Expression ((Invoke-WebRequest -Uri 'https://github.com/azurejoga/Aurora-Windows-Optimizer/raw/aurora/installer.ps1' -UseBasicParsing).Content)
  POWERSHELL

  result = `powershell.exe -NoProfile -Command "#{script}"`
  puts result
end

main
```

The terminal output for both cases is as follows.
```
PS C:\users\azure\documents> crystal testing.cr
Running as a non-administrator. Requestingelevation...
PS C:\users\azure\documents> crystal test.cr Running as a non-administrator. Requestingelevation...
PS C:\users\azure\documents>
```
Well, the prompt appears on the screen but it doesn't change to administrator
I want some way to change the Crystal program to administrator on Windows, is there a native way to do this or not.
The only way I could solve this problem is:
* compile the script.cr
```
crystal build test.cr
```
* run the executable as administrator.
Is there any way to resolve this?

**Comment by Blacksmoke16** [comment]
This would be a better fit for the [forums](https://forum.crystal-lang.org/c/help-support/11), or one of the [chat channels](https://crystal-lang.org/community/#chat).
