### ISSUE TITLE
"Error: can't use variable name 'foo' inside assignment to variable 'foo'" only applies to ternary statement

### ISSUE THREAD

**Issue by Zopolis4** [crystal-lang/crystal#14409]
The error message makes it seem like this isn't allowed, but given that it works fine in an if statement it seems like it should work in a ternary statement?

Working code:
```crystal
if foo = ENV["bar"]?
  foo = foo2.to_i8 * 7
else
  foo = 6
end
puts foo
```

Broken code (should be functionally identical?):
```crystal
foo = (foo = ENV["bar"]?) ? foo.to_i8 * 7 : 6
puts foo
```

``` 
Crystal 1.11.2 (2024-03-24)

LLVM: 17.0.6
Default target: x86_64-pc-linux-gnu
```

`OS: Debian GNU/Linux trixie/sid x86_64`

I was also able to reproduce the bug on `crystallang/crystal:nightly` as follows:
```
Crystal 1.12.0-dev [723f82963] (2024-03-26)

LLVM: 15.0.7
Default target: x86_64-unknown-linux-gnu
```

**Comment by HertzDevil** [comment]
The second snippet is equivalent to:

```crystal
foo = if foo = ENV["bar"]?
        foo.to_i8 * 7
      else
        6
      end
```

So the two are not equivalent.
