### ISSUE TITLE
Formatter changes semantics when call is followed by space and `()`

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#14418]
#11523 removes any whitespace between a call's name and its sole parenthesized argument:

```crystal
# before
foo (1)

# after
foo(1)
```

This changes the AST as the argument is now the `NumberLiteral` itself rather than a one-element `Expressions` containing it, but not the program semantics. However, it is also syntactically valid to use an empty pair of parentheses here, as the body then becomes a `Nop`, which evaluates to `nil`:

```crystal
def foo(x)
  x
end

# before
foo () # => nil

# after
foo() # Error: wrong number of arguments for 'foo' (given 0, expected 1)
```

This changes the argument count from 1 to 0.

**Comment by straight-shoota** [comment]
I'm wondering if the formatter could perhaps even transform `foo ()` into `foo nil`. The former is just weird. Both should be semantically equivalent, so it's just a matter of standardizing on one format to express the same thing.

**Comment by HertzDevil** [comment]
Maybe, but then it wouldn't just be `Expressions` nodes that are arguments to a call. For the record this entire repository doesn't use `()` anywhere. (It also uses parenthesized `Expressions` nodes with more than one child in exactly one place: `Crystal::Repl::Compiler#primitive_convert(node : ASTNode, from_kind : NumberKind, to_kind : NumberKind, checked : Bool)`)

**Comment by straight-shoota** [comment]
Yeah, it's probably not worth it to go for such a tiny adjustment for a largely irrelvant syntax.
