### ISSUE TITLE
It's possible to create a Hash with duplicate keys using missing key block and update method

### ISSUE THREAD

**Issue by robdavid** [crystal-lang/crystal#14416]
Consider the following code

```crystal
result = Hash(String,Int32).new{ |h,k| h[k] = 0 }
result.update("NAME") { |v| v+1 }
pp! result
```

Running this under Crystal 1.9.2 gives the expected result of:
```
result # => {"NAME" => 1}
```

However, from Crystal 1.10.1 up to 1.11.2 (latest) I'm seeing:
```
result # => {"NAME" => 0, "NAME" => 1}
```
with two values for the same key!

Also, 
```crystal
pp! result.size
pp! result["NAME"]
```
Gives
```
result.size # => 2
result["NAME"] # => 0
```

You can see this easily in the crystal playground
![image](https://github.com/crystal-lang/crystal/assets/5861902/37d48079-1295-4c46-b9f4-cbe0d3b8b8a7)
![image](https://github.com/crystal-lang/crystal/assets/5861902/e0f1244d-99ff-41c7-ac76-230515c3e322)

**Comment by HertzDevil** [comment]
Regression of #13590

**Comment by MatthewMerrill** [comment]
It is also possible using Hash#put_if_absent. IMHO, in addition to #14417 the private method insert_new should be removed in favor of upsert in put_if_absent.

![image](https://github.com/crystal-lang/crystal/assets/5248800/4cd3fc5c-7846-420d-8c93-501c281d9a6f)
```crystal
my_hash = Hash(String, Int32).new
my_hash.put_if_absent("a") { |k| my_hash[k] = 1 }
p! my_hash
# my_hash # => {"a" => 1, "a" => 1}
```
