### ISSUE TITLE
Allow space in cookie value for Set-Cookie header

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#14435]
Right now Crystals does not support parsing cookies that has unquoted space in the Set-Cookie header, but, as stated in https://datatracker.ietf.org/doc/html/rfc6265#section-5.2 

```
NOTE: The algorithm below is more permissive than the grammar in
   [Section 4.1](https://datatracker.ietf.org/doc/html/rfc6265#section-4.1).  For example, the algorithm strips leading and trailing
   whitespace from the cookie name and value (but maintains internal
   whitespace), whereas the grammar in [Section 4.1](https://datatracker.ietf.org/doc/html/rfc6265#section-4.1) forbids whitespace in
   these positions.  User agents use this algorithm so as to
   interoperate with servers that do not follow the recommendations in
   [Section 4](https://datatracker.ietf.org/doc/html/rfc6265#section-4).
```

Many servers support this and allows this behavior, which means the HTTP::Client should parse the `cookies` and not avoid them.

A simple example is the following: 
```crystal
require "http"

cookies = HTTP::Cookies.from_server_headers(
  HTTP::Headers{"Set-Cookie" => "Cu=ID=12&Username=bla@bla.com&CustomerID=1&CustomerName=BAR FOO&RoleID=1&EmailAddress=a@a.com&Firstname=doo&Lastname=boo&Warehouse=AA; expires=Fri, 19-Apr-2024 14:35:28 GMT; path=/"}
)

cookies
```
I expect cookies to have 1 cookie, but it doesn't. if I remove the space from `CustomerName=BAR FOO` and instead make it `BARFOO` I see:

```crystal
<HTTP::Cookies:0x729d08a7d8a0
 @cookies=
  {"Cu" =>
    #<HTTP::Cookie:0x729d08a68f20
     @creation_time=2024-04-04 18:52:30.826519756 UTC,
     @domain=nil,
     @expires=2024-04-19 14:35:28.0 UTC,
     @extension=nil,
     @http_only=false,
     @max_age=nil,
     @name="Cu",
     @path="/",
     @samesite=nil,
     @secure=false,
     @value=
      "ID=12&Username=bla@bla.com&CustomerID=1&CustomerName=BARFOO&RoleID=1&EmailAddress=a@a.com&Firstname=doo&Lastname=boo&Warehouse=AA">}>
```

And everything is all good and well.

There is a similar issue that happened in NMAP: https://github.com/nmap/nmap/issues/844 and they also fixed it to support this behavior.

**Comment by bararchy** [comment]
@Blacksmoke16 :smirk: 
![image](https://github.com/crystal-lang/crystal/assets/1631073/692b74a9-c7af-4db2-9ba6-4110c1ceeda8)

I guess my Crystal community counter reset after 10 years of doing Crystal :grin:

**Comment by Blacksmoke16** [comment]
xD. `community:newcomer` is the Crystal repo version of `good-first-issue`, not that the reported is new ;)

**Comment by straight-shoota** [comment]
It might not be a bad idea to rename this tag 😆

**Comment by Blacksmoke16** [comment]
I will say GH provides native integration with some of the default labels. E.g. `help wanted` will call out those tickets when looking at the repos in an org for example:

![image](https://github.com/crystal-lang/crystal/assets/12136995/fb75f43b-2891-4b7a-a46f-1a89ec8a2d71)

Also having an actual `good first issue` includes those ticket on a repo's https://github.com/athena-framework/athena/contribute page.

So, it could definitely be a good idea if we wanted to make use of some of those integrations.

**Comment by bararchy** [comment]
Seems we get a fix at: https://github.com/crystal-lang/crystal/issues/14435 just needs someone to approve it ;)
