### ISSUE TITLE
Macro blocks bleed scope

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#14449]
Normally block arguments are scoped to the block itself. For example:

```cr
v = nil

{1, 2, 3}.each { |v| }

pp v # => nil
```
However macro blocks do not seem to have the same behavior. This can lead to hard to debug bugs if the block param name happens to match a variable outside of the block.
```cr
{%
  v = nil

  {1, 2, 3}.each { |v| }

  v # => 3
%}
```

**Comment by HertzDevil** [comment]
Duplicate of #11140
