### ISSUE TITLE
When use crystal i with `wezterm`(a popular linux terminal), Alt + TAB will output controller character like [O[I  [O[I into terminal.

### ISSUE THREAD

**Issue by zw963** [crystal-lang/crystal#14454]
## Bug Report

Probably a screenshot is better for describe this issue.

![image](https://github.com/crystal-lang/crystal/assets/549126/bccbe7b3-ddbe-4a4c-af09-fe4433619c23)

More detail reproduce: (on arch linux with GNOME  + Wayland)

1.  current active window is wezterm.
2.  Pressing Ctrl + TAB to switch to another app, e.g.  Firefox
3.  A ` [O[I` output to to crystal i REPL
4.  Pressing Ctrl + TAB to switch back.
5.   A new ` [O[I` output to to crystal i REPL

I test on version 1.11.2, and same issue never happen on REPL for others language, e.g.  irb for ruby and iex for Elixir.

This issue not happen on classics console, e.g. konsole

Thanks

**Comment by Blacksmoke16** [comment]
FWIW I use wezterm as well and am unable to reproduce this on both arch+sway and MacOS. `Ctrl+Tab` for me cycles thru the tabs while `Alt+Tab` brings up this and cycles thru keywords:

![image](https://github.com/crystal-lang/crystal/assets/12136995/ae1017dd-ed30-4bb8-9259-7963ef8d1bd3)

**Comment by straight-shoota** [comment]
This looks like the CSI O/CSI I [FocusIn/FocusOut](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-FocusIn_FocusOut) control sequences for xterm. That's basically communication between the terminal and the shell. I don't think they even reach the compiler and suspect the shell prints the directly. There should be no reason for these control sequences to appear in the compiler's stdin unless the shell is misbehaving or you have some configuration error.

Anyway, I don't think there is anything actionable for the Crystal compiler here.

**Comment by zw963** [comment]
Sorry for my fault, after reboot my linux,  this issue is gone.
