### ISSUE TITLE
Audit GH labels

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#14456]
GH provides native integration with some of the default labels. E.g. `help wanted` will call out those tickets when looking at the repos in an org for example:

![image](https://github.com/crystal-lang/crystal/assets/12136995/fb75f43b-2891-4b7a-a46f-1a89ec8a2d71)

Also having an actual `good first issue` label includes those ticket on a repo's https://github.com/athena-framework/athena/contribute page.

So, if we wanted to make use of some of those integrations we should audit our current labels to maybe adjust some of them to fit in. E.g. `community:newcomer` => `good first issue`, etc.

_Originally posted by @Blacksmoke16 in https://github.com/crystal-lang/crystal/issues/14435#issuecomment-2043057403_

**Comment by straight-shoota** [comment]
Using standardized names makes a lot of sense to me. It helps people understand what it means and if it serves the purpose, it's just confusing to use different terms.

We would loose the `community:` namespacing of course, but IMO it's not that important.

**Comment by HertzDevil** [comment]
Looking at https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels it seems `good first issue` is the only special label?

**Comment by Blacksmoke16** [comment]
And `help wanted`. Those are the only two I'm aware of.

**Comment by straight-shoota** [comment]
Okay, let's try this.

I renamed 
* `community:newcomer` to `good first issue`
* `community:help-wanted` to `help wanted`

**Comment by Blacksmoke16** [comment]
Looks good, https://github.com/crystal-lang/crystal/contribute has all the good first issues, and apparently 51 issues have `help wanted`.

![image](https://github.com/crystal-lang/crystal/assets/12136995/e0dddcbd-b500-4cef-8b12-a87cd86ac2fe)

**Comment by straight-shoota** [comment]
I don't think there's anything actionable left to do here.
