### ISSUE TITLE
[RFC] On matters pertaining to reopening and redefining

### ISSUE THREAD

**Issue by js-ojus** [crystal-lang/crystal#1446]
This is a follow-up of a [recent question](https://groups.google.com/forum/#!topic/crystal-lang/GRK506nPTZU) that I posted to the groups.

Redefining existing methods and reopening existing structs, classes and modules offers great flexibility.  Several Ruby programmers (and possibly Crystal programmers) love the said ability.

However, since any struct, class or module can be reopened for modification and extension at any later time, correctness of a library is an amorphous concept!

The costs of scaling that to large teams are high, since every programmer has to factor in potentially unknown effects of almost every library that is used.  Library authors, similarly, have to factor in potentially unknown effects of almost every other library that could be used in conjunction with the one in question.  The cost of maintenance, therefore, is proportional to the number of external dependencies that could redefine existing methods, reopen existing structs, classes and modules.  The situation is exacerbated by the possible independent evolution of such external dependencies.

The following features can help in enabling scalability while retaining reasonable flexibility.

1. Be able to restrict a constant value, method, struct, class or module to the scope in which it is defined.  This option will not be the default.  This is in line with what @asterite has proposed.
1. Be able to declare a method in a struct or class as `final`.  This means that it can neither be overridden nor redefined.  This does not forbid the struct or class getting inherited from.  This option will not be the default.
1. Be able to declare a struct or class as `final`.  This means that it cannot be inherited from.  Nor can its methods be redefined.  This does not forbid extensions; additional methods can be added by reopening the struct or class.  This option will not be the default.

The above are mutually orthogonal, acting at different levels.  The following table tries to capture their effects.

| Feature | `method` | `struct` | `class` | `module` |
|:--:|:--|:--|:--|:--|
| `protected` | Visible only in the scope it is defined, and its sub-scopes. | Visible only in the scope it is defined, and its sub-scopes. | Visible only in the scope it is defined, and its sub-scopes. | Visible only in the scope it is defined, and its sub-scopes. |
| method marked `final` | Can override? : No<hr/>Can redefine? : No | Can inherit from? : Yes<hr/>Can override methods? : Those not marked `final`.<hr/>Can redefine methods? : Those not marked `final`.<hr/>Can extend? Yes | Can subclass? : Yes<hr/>Can override methods? : Those not marked `final`.<hr/>Can redefine methods? : Those not marked `final`.<hr/>Can extend? Yes | Can redefine methods? : Those not marked `final`.<hr/>Can extend? Yes |
| `struct` or `class` marked `final` | Can override? : No<hr/>Can redefine? : No | Can inherit from? : No<hr/>Can override methods? : No<hr/>Can redefine methods? : No<hr/>Can extend? Yes | Can subclass? : No<hr/>Can override methods? : No<hr/>Can redefine methods? : No<hr/>Can extend? Yes | Can redefine methods? : Those not marked `final`.<hr/>Can extend? Yes |

Modules **cannot** be marked as `final`.

<hr/>
Edit: Change "you have" to "@asterite has".

**Comment by jhass** [comment]
I guess the discussion here will quickly arrive at the same point as https://github.com/manastech/crystal/issues/1393#issuecomment-138537675

The other point is whether we need all this complexity if Ruby has pretty much proved itself without it, having huge libraries like Rails frequently combined with countless dependencies (I'm talking hundreds here) in a single project. Quick and easy introspection is what most of these issues solves there.

The other obvious alternative is to look into concepts that can retain the flexibility at any point without affecting the global state, like Ruby's new refinements feature.

**Comment by ysbaddaden** [comment]
I never saw refinements used anywhere myself, despite the feature being available in Ruby for a couple years now (if not more). I guess nobody cares enough to actually use it? Or everybody's careful enough to not reopen/overload blindlessly.

**Comment by jhass** [comment]
It's also that the API has some not so nice gotchas tbf, but then there are interesting things like http://rubyzucker.info/

**Comment by js-ojus** [comment]
@jhass : It is an interesting mix at play.

1. The smaller projects that wish to play well with Rails simply won't fight the big boy!  So, the projects accept everything that Rails does, and do not interfere in anything that Rails chooses to reopen; or they risk not working with Rails.
1. When it comes to redefinitions, even within the Ruby community, the first advice is "Don't!"  Ruby's monkey patches and Scala's `implicit`s can be debugging nightmares!
1. Ruby would not have implemented refinements (or selector namespaces, in an earlier avatar), if clashes weren't a problem at large!  So, no, Ruby has not proved scalability -- that is an incorrect argument; it has, in fact, succumbed, and implemented refinements. :-)
1. Even so, refinements are complex: see [this document](http://ruby-doc.org/core-2.1.1/doc/syntax/refinements_rdoc.html).  Look at how complex method dispatch has become, for instance.  Inheritance and modules multiply the woes.
1. Now, I think that there is a big difference between redefinition and extension.  In what I propose, extensions are always possible.  That should solve the vast majority of scenarios in which a need for monkey patching is felt.
1. Please note that I am not proposing that conflicting definitions should not exist.  Rather, I am proposing that a library author should have an option to choose such possible conflicts to only be in users' extensions, not the original library itself.
1. Finally, unrestricted reopening leads to an inability to reason about the correctness of the library's behaviour.  It passes my tests when I publish it, but may behave differently in your environment.  Every non-trivial library has multiple moving parts.  My proposal allows a library to guard and sanitise inputs and outputs, while working freely within.  Please note that this is optional!

On the other hand, should we conclude that Crystal should not be used for purposes that require some assurances of correctness, the designers are free to do that.  That would be sad, though! :-(

I discovered Ruby in 2000, and used it heavily until about 2008.  The additional costs of ensuring correctness of code are quite high in Ruby (developing and maintaining massive test suites).  Also, see my original point about evolving external dependencies.  I drifted away from Ruby eventually, because of some of these concerns and experiences (and poor performance).

@ysbaddaden : Another example of refinements in practice is [Sequel](http://sequel.jeremyevans.net/rdoc-plugins/classes/Sequel/CoreRefinements.html).

The thread at Ruby's [original refinements proposal issue](https://bugs.ruby-lang.org/issues/4085) is a great read.  A large variety of pertinent issues is discussed there.  For Crystal, we can ignore the parts that deal with `*eval`, _etc_., of course!

I agree with @jhass that now is a good time for Crystal to take a philosophical stance!

**Comment by asterite** [comment]
I'm closing this. If someone reopens one of your classes and it breaks it, the compiler will most probably give an error (for example if someone reopens it and returns an incorrect type).

Even though reopening and redefining classes is used in Ruby and Crystal, I mostly see two main uses for it:

1. Adding more functionality to a type
2. Monkey patch a buggy method with a correct implementation

When the other thing happens, that is, redefining a method without you knowing that you did that, most probably a compiler error will happen, so you won't define a method like that.

If a real issue with the current behaviour happens in your code, please report it or reopen this issue. Thanks!

**Comment by trans** [comment]
FYI, the problem with Ruby's refinements (which I have been trying to tell people since the beginning) is simply the syntax -- it adds new boiler plate. So you can't just re-use your old monkey patch libs via refinement -- you have to rewrite them.

If Crystal ever implements refinements, please don't make this mistake.
