### ISSUE TITLE
Log stores keys (sources) indefinitively

### ISSUE THREAD

**Issue by beta-ziliani** [crystal-lang/crystal#14473]
When `Log.for(source)` is used, a new entry in the [`Log::Builder.@logs`](https://github.com/crystal-lang/crystal/blob/aee9ab69eccdeba472b710b38c96067e7ed60d54/src/log/builder.cr#L16) map is added, containing the key `source` and a weak reference to a `Log` object. This map is only compressed when calling `Builder#bind` or `Builder#clear` via the private method [`each_log`](https://github.com/crystal-lang/crystal/blob/aee9ab69eccdeba472b710b38c96067e7ed60d54/src/log/builder.cr#L88), leading in practice to a leak of the `source`s.

The following example can be easily seen to consume memory (and take time) as the argument grows larger:

```cr
require "log"

(1..ARGV[0].to_i).each do |i|
  Log.for "a#{rand}"

  GC.collect
end
```

While the following runs in a breeze.

```cr
require "log"

class Log::Builder
  def compress
    @logs.reject! { |_, log_ref| log_ref.value.nil? }
  end
end

(1..ARGV[0].to_i).each do |i|
  Log.for "a#{rand}"

  GC.collect

  Log.builder.compress
end
```

**Comment by beta-ziliani** [comment]
I was considering using something akin to a `WeakHashMap`, but [that's not trivial to build](https://forum.crystal-lang.org/t/is-there-a-hash-like-data-structure-thats-not-referencing-its-own-elements/5556).

Alternatively, an option is to use the Log's finalizer to remove itself from the map, perhaps using a little store to avoid calling compression at each log's death.

**Comment by straight-shoota** [comment]
I think log sources are expected to be fairly static (e.g. `Log.for(Foo)`).

What would be a use case for (highly) dynamic log sources where this would lead to a noticable effect?
