### ISSUE TITLE
Crystal update error messages, Part 2

### ISSUE THREAD

**Issue by nilslindemann** [crystal-lang/crystal#14479]
Update of #13979 a few months later.

Some hero in your team fixed this once (I guess), and it worked well for a while. Thanks again for this.

Today I got the error message again:

```
W: Failed to fetch http://download.opensuse.org/repositories/devel:/languages:/crystal/Debian_Unstable/amd64/crystal1.10_1.10.1-1%2b5.55_amd64.deb
  404  Not Found [IP: 2a07:de40:b250:131:10:151:131:30 80]
```

Has maybe someone in your team undone this fix, once applied?

**Comment by straight-shoota** [comment]
Have you tried updating the repo?
According to the package index at https://download.opensuse.org/repositories/devel:/languages:/crystal/Debian_Unstable/Packages, the correct download URL would be http://download.opensuse.org/repositories/devel:/languages:/crystal/Debian_Unstable/amd64/crystal1.10_1.10.1-1%2b5.56_amd64.deb

**Comment by nilslindemann** [comment]
> Have you tried updating the repo?

I do not know what this exactly means. I am installing the updates via the Linux Mint package manager GUI.

Today it was possible to download and update the latest Crystal via this way. Maybe it was just a one time issue. Will report when it happens again.

**Comment by straight-shoota** [comment]
I meant just running `apt update`. Chances are you had an outdated package index which listed a version that's no longer available.

**Comment by nilslindemann** [comment]
Thanks @straight-shoota, will try that next time
