### ISSUE TITLE
Unhandled exception: Invalid Int32: "36-RC1" (ArgumentError)

### ISSUE THREAD

**Issue by Frityet** [crystal-lang/crystal#14477]
## Bug Report

Make sure to review these points before submitting issues - thank you!

- **Include reproducible code**: we should be able to paste it into an editor, compile and run it and get the same error as you. Otherwise it's impossible for us to reproduce the bug.
```ruby
puts "hello"
```

```sh
> crystal main.cr
Unhandled exception: Invalid Int32: "36-RC1" (ArgumentError)
  from /usr/local/Cellar/crystal/1.12.0/share/crystal/src/string.cr:438:83 in 'to_i32'
  from /usr/local/Cellar/crystal/1.12.0/share/crystal/src/string.cr:349:5 in 'to_i'
  from /usr/local/Cellar/crystal/1.12.0/share/crystal/src/regex/pcre2.cr:20:39 in '~Regex::PCRE2::version_number:init'
  from /usr/local/Cellar/crystal/1.12.0/share/crystal/src/regex/pcre2.cr:237:17 in '__crystal_main'
  from /usr/local/Cellar/crystal/1.12.0/share/crystal/src/crystal/main.cr:129:5 in 'main_user_code'
  from /usr/local/Cellar/crystal/1.12.0/share/crystal/src/crystal/main.cr:115:7 in 'main'
  from /usr/local/Cellar/crystal/1.12.0/share/crystal/src/crystal/main.cr:141:3 in 'main'
  from /usr/lib/dyld in 'start'
```
- Include Crystal compiler version (`crystal -v`) and OS. If possible, try to see if the bug still reproduces on master.
```yaml
> crystal -v
Crystal 1.12.0 (2024-04-09)

LLVM: 17.0.6
Default target: x86_64-apple-macosx
```

```yaml
> sw_vers
ProductName:		macOS
ProductVersion:		13.4
BuildVersion:		22F66
```

```sh
> uname -a
Darwin amrit-1587.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64 x86_64
```

**Comment by Frityet** [comment]
When attempting to compile the project:
```sh
❯ make -j
Using /usr/local/opt/llvm/bin/llvm-config [version=17.0.6]
clang++ -c  -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc -I/usr/local/Cellar/llvm/17.0.6_1/include -std=c++17 -stdlib=libc++   -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
CRYSTAL_CONFIG_BUILD_COMMIT="4cea10199" CRYSTAL_CONFIG_PATH='$ORIGIN/../share/crystal/src' SOURCE_DATE_EPOCH="1712838701"  CRYSTAL_CONFIG_LIBRARY_PATH='$ORIGIN/../lib/crystal' ./bin/crystal build -D strict_multi_assign -D preview_overload_order -Dwithout_interpreter  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib -D use_pcre2
Showing last frame. Use --error-trace for full trace.

There was a problem expanding macro 'embed'

Code in macro 'def_to_s'

 2 | ECR.embed "/Users/frityet/Documents/Packages/crystal/src/compiler/crystal/tools/init/template/example_spec.cr.ecr", "__io__"
     ^
Called macro defined in src/ecr/macros.cr:69:3

 69 | macro embed(filename, io_name)

Which expanded to:

 > 1 | {{ run("ecr/process", "/Users/frityet/Documents/Packages/crystal/src/compiler/crystal/tools/init/template/example_spec.cr.ecr", "__io__") }}
          ^--
Error: Error executing run (exit code: 1): ecr/process /Users/frityet/Documents/Packages/crystal/src/compiler/crystal/tools/init/template/example_spec.cr.ecr __io__


stderr:

    Unhandled exception: Invalid Int32: "36-RC1" (ArgumentError)
      from /Users/frityet/.cache/crystal/Users-frityet-Documents-Packages-crystal-src-ecr-process.cr/macro_run in 'raise<ArgumentError>:NoReturn'
      from /Users/frityet/.cache/crystal/Users-frityet-Documents-Packages-crystal-src-ecr-process.cr/macro_run in 'String#to_i32<Int32, Bool, Bool, Bool, Bool, Bool>:Int32'
      from /Users/frityet/.cache/crystal/Users-frityet-Documents-Packages-crystal-src-ecr-process.cr/macro_run in '__crystal_main'
      from /Users/frityet/.cache/crystal/Users-frityet-Documents-Packages-crystal-src-ecr-process.cr/macro_run in 'main'
      from /usr/lib/dyld in 'start'

make: *** [.build/crystal] Error 1
```

**Comment by Blacksmoke16** [comment]
This is failing on https://github.com/crystal-lang/crystal/blob/master/src/regex/pcre2.cr#L20 because it seems the version of PCRE2 you have does not match the normal convention of `XX.YY` but instead is `XX-RC1` format. Probably should handle I'd wager, but until then can probably just work around it by upgrading PCRE2 to a more recent version.

**Comment by Frityet** [comment]
> This is failing on
> 
> https://github.com/crystal-lang/crystal/blob/4cea10199d5006000a129413f6f607697185c83a/src/regex/pcre2.cr#L20
> because it seems the version of PCRE2 you have does not match the normal convention of `XX.YY` but instead is `XX-RC1` format. Probably should handle this I'd wager, but until then can probably just work around it by upgrading PCRE2 to a more recent version.

Is it alright for me to make a patch to accommodate for this? Or is it out of scope

**Comment by Frityet** [comment]
Also, I have the most recent version of pcre2 on brew

**Comment by straight-shoota** [comment]
This patch should fix it:

```diff
--- i/src/regex/pcre2.cr
+++ w/src/regex/pcre2.cr
@@ -17,7 +17,7 @@ module Regex::PCRE2
     version = self.version
     dot = version.index('.') || raise RuntimeError.new("Invalid libpcre2 version")
     space = version.index(' ', dot) || raise RuntimeError.new("Invalid libpcre2 version")
-    {version.byte_slice(0, dot).to_i, version.byte_slice(dot + 1, space - dot - 1).to_i}
+    {version.byte_slice(0, dot).to_i, version.byte_slice(dot + 1, space - dot - 1).to_i(strict: false)}
   end

   # :nodoc:
```

You can monkey patch the getter into your code to test it.

**Comment by Blacksmoke16** [comment]
> Also, I have the most recent version of pcre2 on brew

You most definitely do not. The latest version is `10.43`

https://formulae.brew.sh/formula/pcre2

**Comment by Frityet** [comment]
> This patch should fix it:
> 
> ```diff
> --- i/src/regex/pcre2.cr
> +++ w/src/regex/pcre2.cr
> @@ -17,7 +17,7 @@ module Regex::PCRE2
>      version = self.version
>      dot = version.index('.') || raise RuntimeError.new("Invalid libpcre2 version")
>      space = version.index(' ', dot) || raise RuntimeError.new("Invalid libpcre2 version")
> -    {version.byte_slice(0, dot).to_i, version.byte_slice(dot + 1, space - dot - 1).to_i}
> +    {version.byte_slice(0, dot).to_i, version.byte_slice(dot + 1, space - dot - 1).to_i(strict: false)}
>    end
> 
>    # :nodoc:
> ```
> 
> You can monkey patch the getter into your code to test this.

Alright nice! Im guessing I shouldn't make a PR for this?

**Comment by straight-shoota** [comment]
Feel free to do so if you can verify it actually works.

**Comment by Frityet** [comment]
Verified, works like a charm! I will make the PR now
