### ISSUE TITLE
Formatter error regression

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#14470]
Formatting:
```cr
class SomeClass
  @[SomeAnn(
    requirements: {
      "color" => 1,
    }
  )]
  def get_color
  end
end
```
With Crystal 1.12.0, results in:
```sh
expecting ), not `SPACE,   `, at :6:1 (Exception)
  from /crystal/src/compiler/crystal/tools/formatter.cr:5187:9 in 'finish_args'
  from /crystal/src/compiler/crystal/tools/formatter.cr:3034:7 in 'visit'
  from /crystal/src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from /crystal/src/compiler/crystal/syntax/visitor.cr:20:7 in 'visit'
  from /crystal/src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from /crystal/src/compiler/crystal/tools/formatter.cr:4832:7 in '??'
  from /crystal/src/compiler/crystal/tools/formatter.cr:4681:7 in 'format_nested_with_end'
  from /crystal/src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from /crystal/src/compiler/crystal/tools/formatter.cr:23:7 in 'format_source'
  from /crystal/src/compiler/crystal/command/format.cr:133:7 in 'format_many'
  from /crystal/src/compiler/crystal/command/format.cr:63:5 in 'format'
  from /crystal/src/reference.cr:75:3 in 'tool'
  from /crystal/src/compiler/crystal/command.cr:118:7 in 'run'
  from /crystal/src/compiler/crystal.cr:11:1 in '__crystal_main'
  from /crystal/src/crystal/main.cr:129:5 in 'main'
  from src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'
```

Noticed via https://github.com/athena-framework/athena/actions/runs/8622679938/job/23635100763?pr=395 Maybe I should setup nightly formatter CI :S

EDIT: Reverting https://github.com/crystal-lang/crystal/pull/14354 fixes the error

**Comment by straight-shoota** [comment]
> Maybe I should setup nightly formatter CI :S

Yeah, that's what nightlies are for. If nobody tests them, we won't know about unnoticed issues until after the release 🙈

I suppose we should also run the formatter in test-ecosystem 🤔

**Comment by Blacksmoke16** [comment]
Formatter isn't usually something you think of when mentioning setting up nightly CI. Technically you'd need like nightly CI on all the crystal tools in that case. Formatter just happens to be the most commonly used.

**Comment by straight-shoota** [comment]
Well the other tools are mostly just querying the AST. So they'd only break if there are changes in the AST. That's rare and there are not that many edge cases.

The formatter on the other hand has an entirely different way to consume Crystal source code and it's a huge problem space. We know that specs only cover a small portion of the entire problem space and there's a lot of edge cases which are broken but not yet discovered. So constantly testing the formatter on as much code as possible is really helpful. Much more than any other tools.
