### ISSUE TITLE
Assignment to lib struct field in array fails silently

### ISSUE THREAD

**Issue by BrucePerens** [crystal-lang/crystal#14513]
In the below example, assignment to a lib struct field in an array fails silently. I hit this setting a LibC::Timeval array because IO#utime isn't implemented on IO::FileDescriptor on Linux.

Compiler version: 
```
Crystal 1.12.1 [4cea10199] (2024-04-11)

LLVM: 15.0.7
Default target: x86_64-unknown-linux-gnu
```

```crystal
lib LibX
  struct Struct
    x : Int64
  end
end

zero_struct = LibX::Struct.new
a = Array(LibX::Struct).new(2,zero_struct)
a[0].x = 1
p a[0].x # Output is 0

**Comment by Blacksmoke16** [comment]
Is this not just due to structs being passed by value? I.e. using a normal struct results in the same behavior.

**Comment by BrucePerens** [comment]
Perhaps then this is a documentation bug. While Crystal Struct is documented that way, the documentation on lib doesn't warn that C structs act that way as well.

**Comment by Blacksmoke16** [comment]
Pretty sure it is, at the bottom of https://crystal-lang.org/reference/1.12/syntax_and_semantics/c_bindings/struct.html:

> A C struct is passed by value (as a copy) to functions and methods, and also passed by value when it is returned from a method:

```cr
def change_it(tz)
  tz.minutes_west = 1
end

tz = C::TimeZone.new
change_it tz
tz.minutes_west # => 0
```

**Comment by BrucePerens** [comment]
OK, will close the bug then. This would complicate memory-mapped IO drivers in Crystal, but I guess that's not a language feature.

**Comment by BrucePerens** [comment]
Closed due to my failiure to understand Crystal Struct's implications.

**Comment by Blacksmoke16** [comment]
Related: https://forum.crystal-lang.org/t/built-in-support-for-mmap/6772

**Comment by straight-shoota** [comment]
@BrucePerens You can make this work by taking a pointer to the struct inside the array and assigning directly on that.
```cr
(a.to_unsafe + 0).value.x = 1
```

However I'm wondering if an `Array` is actually an adequatetype for your use case. `Array` has a dynamic size and can reallocate its items when it needs to grow. This might lead to problems if you need to take pointerst to individual items.
If you know the size beforehand (is it always 2 maybe?), `Slice` or even `StaticArray` may be more suitable.

**Comment by ysbaddaden** [comment]
Yes, all structs in crystal are passed by value (they don't inherit from Reference as classes do). You must use pointers (`pointerof`, `Pointer(T)#value`) to pass them by reference.

There's also a limitation in Crystal when dealing with collections of structs such as `Array(MyStruct)` (applies to all Enumerable and Indexable) as we can't _iterate by reference_ to the value. `#each` for example always returns the value, and thus a copy of the struct —classes don't have that issue because an `Array(MyClass)` is really an array of pointers (we copy the pointer).

For example, to iterate by reference:

```crystal
record Point, x: Int32, y: Int32

coll = Array(Point).new(5) { Point.new(0, 0) }

coll.size.times do |i|
  ref = coll.to_unsafe[i]
  ref.value.x = 1
end
```

**Comment by BrucePerens** [comment]
Johannes, thanks very much for that pointer :-) It happens my implentation does already use StaticArray. The means of getting a pointer looks a bit hacky and I think I'll bury it in a macro. And thanks for the additional info, Julien.

I wonder if it's possible to warn about the condition that a datum is modified and then becomes unreachable before any further reference?
