### ISSUE TITLE
Type inference with case or if statement

### ISSUE THREAD

**Issue by noraj** [crystal-lang/crystal#14512]
From an argument parser, any argument could have many type.

So if I'm trying to execute `args["<url>"].join(DEFAULT_DELIMITER)` I got an error when compiling:

```
Error: undefined method 'join' for Bool (compile-time type is (Array(String) | Bool | Int32 | String | Nil))
```

Which is somewhat expected.

So I thought that putting this in a case or if statement to eliminate some kind of types would be enough.

```crystal
case args["<url>"] # (Array(String) | Bool | Int32 | String | Nil)
when Nil, Bool, Int32
  sources = STDIN.gets_to_end
when Array(String)
  sources = args["<url>"].join(DEFAULT_DELIMITER)
when String
  sources = args["<url>"]
end
```

But I still have the same issue even if it can't possibly be of type Bool in this branch.

Same with if

```crystal
if Nil === args["<url>"] || Bool === args["<url>"] || Int32 === args["<url>"]
  sources = STDIN.gets_to_end
elsif Array(String) === args["<url>"]
  sources = args["<url>"].join(DEFAULT_DELIMITER)
elsif String === args["<url>"]
  sources = args["<url>"]
end
```

**Comment by noraj** [comment]
Using Crystal 1.12.1. Is that me or is there a way to improve Crystal?

I can't use `is_a?` either, because it doesn't work on nested types.

Checking `is_a?(Array)`

```crystal
if args["<url>"](Nil) || args["<url>"].is_a?(Bool) || args["<url>"].ia_a?(Int32)
  sources = STDIN.gets_to_end
elsif args["<url>"].is_a?(Array)
  sources = args["<url>"].join(DEFAULT_DELIMITER)
elsif args["<url>"].is_a?(String)
  sources = args["<url>"]
end
```

Results:

```
Error: undefined method 'ia_a?' for Array(String) (compile-time type is (Array(String) | Bool | Int32 | String | Nil))
```

Checking `is_a?(Array(String))`

```crystal
if args["<url>"](Nil) || args["<url>"].is_a?(Bool) || args["<url>"].ia_a?(Int32)
  sources = STDIN.gets_to_end
elsif args["<url>"].is_a?(Array(String))
  sources = args["<url>"].join(DEFAULT_DELIMITER)
elsif args["<url>"].is_a?(String)
  sources = args["<url>"]
end
```

Results:

```
Error: undefined method 'ia_a?' for Array(String) (compile-time type is (Array(String) | Bool | Int32 | String | Nil))
```

**Comment by noraj** [comment]
The only solution I found was to keep either of the 3 approaches and adding an [as](https://crystal-lang.org/reference/1.12/syntax_and_semantics/as.html) each time I have a type compilation issue.

**Comment by HertzDevil** [comment]
You have to assign `args["<url>"]` to a local variable first and then write the `case` expression using that, because `args` might have been modified in-between.

**Comment by noraj** [comment]
You're absolutely right, so that was me.
