### ISSUE TITLE
Regex.match raises exception when certain pattern applied to long subject

### ISSUE THREAD

**Issue by jmdyck** [crystal-lang/crystal#14544]
The pattern in question has to involve a repeated group that contains `|`, and the subject needs to be long enough that the group matches 1024 or more times. 

```crystal
regex = /^(_|X)+/
# regex = /^(_)+/

(1020..1027).each do |i|
    subject = "_" * i
    match_result = regex.match(subject)
    puts "#{i}: #{match_result ? "matches" : "NOMATCH"}"
end
```

I get:
```
1020: matches
1021: matches
1022: matches
1023: matches
Unhandled exception: Regex match error: JIT_STACKLIMIT (Regex::Error)
  from /snap/crystal/2018/share/crystal/src/regex/pcre.cr:197:7 in 'internal_matches?'
  from /snap/crystal/2018/share/crystal/src/regex/pcre.cr:174:8 in 'match_impl'
  from /snap/crystal/2018/share/crystal/src/regex.cr:614:12 in 'match_at_byte_index'
  from /snap/crystal/2018/share/crystal/src/regex.cr:563:12 in 'match'
  from bug_report.cr:7:20 in '__crystal_main'
  from /snap/crystal/2018/share/crystal/src/crystal/main.cr:129:5 in 'main_user_code'
  from /snap/crystal/2018/share/crystal/src/crystal/main.cr:115:7 in 'main'
  from /snap/crystal/2018/share/crystal/src/crystal/main.cr:141:3 in 'main'
  from /lib/x86_64-linux-gnu/libc.so.6 in '??'
  from /lib/x86_64-linux-gnu/libc.so.6 in '__libc_start_main'
  from /home/michael/snap/crystal/common/.cache/crystal/crystal-run-bug_report.tmp in '_start'
  from ???
```
(Note that if I change the regex to `/^(_)+/`, I get "matches" for all lengths.)

crystal -v:
```
Crystal 1.12.1 [4cea10199] (2024-04-11)

LLVM: 15.0.7
Default target: x86_64-unknown-linux-gnu
```
OS is Ubuntu 22.04.4

**Comment by Blacksmoke16** [comment]
Try upgrading to PCRE2, based on the trace you're still on PCRE1. I'm unable to reproduce this myself, so was like fixed or is just no longer a problem on the newer version.

**Comment by jmdyck** [comment]
> Try upgrading to PCRE2, based on the trace you're still on PCRE1.

E.g., invoke `crystal build -Duse_pcre2 bug.cr` ? That gives me an ld error (which I'm trying to figure out).

I thought PCRE2 was the default since crystal 1.8.

**Comment by Blacksmoke16** [comment]
No, I mean actually install PCRE2 via `sudo apt-get install libpcre2-dev`. You currently do not have it installed, hence the `ld` error.

AFAIK PCRE2 is the default if it is available, whereas in your case, it is not, so it falls back on PCRE1. Of which, it's been quite a while since 1.8. Wonder if its time to drop this fallback behavior...

**Comment by jmdyck** [comment]
> No, I mean actually install PCRE2 via `sudo apt-get install libpcre2-dev`. You currently do not have it installed, hence the `ld` error.

Ah, okay. Seems like that should have been mentioned in [the migration steps](https://crystal-lang.org/2023/03/02/crystal-is-upgrading-its-regex-engine/).

Anyway, that fixes this bug for me.
