### ISSUE TITLE
Using `include` with a `module` with a `private macro` exposes it

### ISSUE THREAD

**Issue by sol-vin** [crystal-lang/crystal#14578]
Issue:

Using `include` with a `module` that has a `private macro` exposes the `macro` publicly

Code:

```crystal
module A
  private macro test(t)
    {% puts "HI #{t}" %}
  end
end

A.test(1)

include A

test(2)
```

throws an `Error: private macro 'test' called for A`

```crystal
module A
  private macro test(t)
    {% puts "HI #{t}" %}
  end
end

include A

test(2)
```

Produces:

```
HI 2
```

What it should do:

Throw an `Error: private macro 'test' called for A`

**Comment by straight-shoota** [comment]
This seems to work as expected. `include A` makes all features in `A` available in the parent namespace. A `private` macro is still visible from the same namespace, so it makes sense that you can call it after `include A`.

Note that the visibility of `test` does not change. Calling it from a different namespace is still prohibited.

```cr
module A
  private macro test(t)
    {% puts "HI #{t}" %}
  end
end

module B
  include A
  test(2)
end

B.test(3)
```

**Comment by sol-vin** [comment]
Ah, my bad, closed
