### ISSUE TITLE
Accept string literals in responds_to? (Was: responds_to? throws error)

### ISSUE THREAD

**Issue by andersennl** [crystal-lang/crystal#1460]
Hi, I've got a simple example:

``` ruby
class Bla
  def blubb
  end
end

bla = Bla.new
bla.responds_to? "blubb" # using string or symbol makes no difference
```

This throws the following error:

``` ruby
Syntax error in eval:7: unexpected token: DELIMITER_START (expected name or symbol)
```

It doesn't matter if the object actually has the method in question or not.

My Crystal version:

```
crystal --version
Crystal 0.7.7 [170f859] (Sat Sep  5 02:46:31 UTC 2015)
```

The docs mention that `responds_to?` is supposed to work. Am I doing something wrong or is this currently broken? Thanks!

**Comment by jhass** [comment]
Symbol does work: http://carc.in/#/r/f1g

**Comment by andersennl** [comment]
Thanks, sorry for the wrong issue. Must have missed to save my file.

**Comment by jhass** [comment]
I'd like to discuss allowing string literals too, @asterite what do you think?

**Comment by andersennl** [comment]
One more question, maybe OT but related. I couldn't find `.to_sym` for String objects. Does it exist or is planned to be implemented?

**Comment by jhass** [comment]
No, see http://stackoverflow.com/a/32537106/2199687

**Comment by andersennl** [comment]
Ok thanks.

**Comment by asterite** [comment]
@jhass I actually want it to be `foo.responds_to?(method)`, without symbol or string, just an identifier, because the compiler parses it a special construct. But sure, we could make the three of them parse well (but that would be similar to aliases, maybe there should be just one way).

**Comment by jhass** [comment]
I'd vote for all three.

**Comment by andersennl** [comment]
All three would be nice as it would make the (in Ruby) often used `.to_sym` in combination with `responds_to?` redundant in many cases.

**Comment by jhass** [comment]
Well, OT but Ruby is just fine calling `to_sym` for you:

```rb
[160] pry(main)> "".respond_to? "size"
=> true

**Comment by miketheman** [comment]
#triage 

This is still undetermined as to what behavior _should_ be implemented - whether `.responds_to?` should remain only ` :symbol`, or accept a String or a method name.

To accept a String, String would need to be able to either be coerced into a Symbol (but @jhass pointed out that it's not really possible in the SO answer above) or `responds_to?` needs to accept a String.

**Comment by straight-shoota** [comment]
`responds_to?` doesn't need to accept a string literal. There's a conceptual difference, which makes this perfectly fine. It would just be an encouragement to use several different styles to write the same thing. 

Using a symbol or identifier has the benefit that they have the same lexing rules as a method name. A string could contain characters that make it not even a valid method name. 

Allowing string literals would potentially misguide (especially new) developers into assuming the string could be dynamically altered using interpolation or string manipulation methods (in Ruby: `"".respond_to?("SI#{"ze"}".downcase) # => true`).
