### ISSUE TITLE
Proposal: Allow overloading +=, -=, *=, /=, %=, &=, |=, ^= for structs

### ISSUE THREAD

**Issue by lbguilherme** [crystal-lang/crystal#1462]
My proposal is to allow the following construct:

```crystal
struct SomeStruct
  def +=(obj)
    # does the sum in-place, changing self
  end
end
```

This would allow for better optimization on some numeric classes, specially `BigInt`. Currently this creates a temporary: `big1 += big2`, or even `big1 += 1`. It could be implemented more efficiently. Look:

```crystal
struct BigInt
  def +(other : BigInt) # unchanged
    BigInt.new { |mpz| LibGMP.add(mpz, self, other) }
  end

  def +=(other : BigInt)
    LibGMP.add(self, self, other)
  end

  def +(other : Int) # unchanged
    if other < 0
      self - other.abs
    else
      BigInt.new { |mpz| LibGMP.add_ui(mpz, self, LibC::ULong.cast(other)) }
    end
  end

  def +=(other : Int)
    if other < 0
      self -= other.abs
    else
      LibGMP.add_ui(self, self, LibC::ULong.cast(other))
    end
  end
end
```

I believe this would be a huge optimization for `BigInt` (this is how GMP is meant to be used).

This overload would only be possible on `struct`s, not `class`es, to preserve semantics.

```crystal
a = SomeClass.new
b = a   # 'a' and 'b' refer to the same object
b += 1  # 'a' should not be affected, so calling a method here makes no sense
a == b  # false
```

```crystal
a = SomeStruct.new
b = a   # 'a' and 'b' do not refer to the same object, copy was made
b += 1  # we can call the method overload here, 'a' will not be affected
a == b  # false
```

And they would be callable on `self`, only inside a struct, so the following is possible, but only if the method was defined:

```crystal
self += 3
# If += is defined, this calls it
# Otherwise, this is a syntax sugar for self = self + 3,
#                                      which makes no sense and should error.
```

---

The main point of this is to allow more library optimizations while still maintaining all the semantics and expressiveness we love of Crystal.

**Comment by jhass** [comment]
The issue with this is that it's a huge semantic discrepancy. `a <op>= b` is defined and known to be syntax sugar for `a = a <op> b`. `a <op> b` for `+`, `-`, `/´, `*` is known to create a new object.

Consider this:

```
def add_maybe(a, b)
  a += b if [true, false].sample
  a
end

n = 1
m = 2
s = BigInt.new(1)
t =  BigInt.new(2)

o = add_maybe(n, m)
p = add_maybe(s, t)

n #=> 1
m #=> 2
o #=> 1, 3

s #=> 1, 3
t #=> 2
p #=> 1, 3
```

That's quite subtle and unexpected. But then introducing own operators for BigInt is ugly too, so I'm not sure about the proper way to solve this, but I think this creates more problems than it solves tbh.

**Comment by asterite** [comment]
I also thought about this and came to the same conclusion as jhass.

One solution that's not very nice, but works, it to define `add`, `mult`, etc., methods that change `self`. They can be documented and although they are longer to type, it's not a lot and you generally do these ops in a single line:

```crystal
a += 1
# vs.
a.add(1)

a *= 2
# vs.
a.mult(2)
```

I know the above starts to smell like Java, but this is an intermediate solution that doesn't have big surprises and should work well. Plus the scenarios where this is usually needed is for BigInt and such. For regular structs it doesn't matter if a copy is created because LLVM can optimize that.

**Comment by lbguilherme** [comment]
@jhass This was kind of unexpected to me. Structs are passed by value, so a change in `a` should not affect `s` at all. The problem is that `BigInt` does not "own" its data,  both "a" and "s" will end up having pointers to the same data.

```crystal
require "big_int"

struct BigInt
  def add(other : BigInt)
    LibGMP.add(self, self, other)
  end
end

def sum(a : BigInt, b : BigInt)
  a.add(b)
  a
end

a = BigInt.new(1)
b = BigInt.new(2)
c = sum(a, b)
p a
p b
p c
```

I really believe this should print 1,2,3. But it [doesn't](http://play.crystal-lang.org/#/r/f1n).

This other issue can be fixed by letting `BigInt` know when it is being copied, so that no two BigInts share the same data. This is analogous to C++'s copy constructor. And we could avoid coping BigInts everywhere by implementing copy-on-write on it.

If this copy semantics holds, then it is just a matter of renaming `add` to `+=` and everything should be nice.

Those concepts  aren't really meant for general usage, only for performance critical codes and for library writers. Seems reasonable?

**Comment by asterite** [comment]
If we start adding copy constructors, pass by reference, etc., the language will become really complex and I wouldn't like that.

I don't know why the above example is broken, it probably depends on how libgmp implements its stuff. Maybe changing the pointed data is not good. For example I tried [this program](http://play.crystal-lang.org/#/r/f1z) and it gives a really weird result.

This means that you have to be very careful on how you operate these things. So if you have a tight loop where you need this kind of efficiency, I would do these unsafe things. But I wouldn't add many complex constructs to the language just for this reason.

In the long run we could implement BigInt ourselves, like in other languages, so we could handle these things more efficiently.

**Comment by lbguilherme** [comment]
@asterite I fully agree that the language should not get complex with this kinds of constructions, but:

What ever way we decide to implement BigInt, it will always hold a pointer to heap data, and coping the BigInt will always simply copy the pointer and not the data the pointer points to. This holds for any struct  that hosts pointers and in the end you have some structs that passes by reference and some that passes by value.

```crystal
struct SomeStruct
	def initialize
		@data = Pointer(Int32).malloc(1)
		@data.value = 1
		@value = 1
	end
	def add(v)
		@data.value += v
		@value += v
	end
	def value
		[@data.value, @value]
	end
end

a = SomeStruct.new
b = a

a.add(1)
b.add(1)

p a.value
p b.value
```

What would be the expected behavior here? By knowing that structs copy by value, I would expect `[2, 2]` and `[2, 2]`, and not `[3, 2]` and `[3, 2]` to be printed. And currently there is no way to fix this, and the struct is working just like a plain reference class.

---

I'm not sure why http://play.crystal-lang.org/#/r/f1z gives this wired result, some bug/misuse somewhere else? I'll try to find what is going on here.

**Comment by lbguilherme** [comment]
Maybe we can use `copy` (or `dup`, I never know) for this:

```crystal
a = SomeStruct.new
b = a     # actually does  b = a.clone
```

**Comment by lbguilherme** [comment]
Elaborating more the `clone` proposal: it should implicitly call `clone` when:

1. A variable is set from a named struct value (i.e. from a variable) of type struct

  ```crystal
  a = SomeStruct.new   # do not call clone
  b = a                # do b = a.clone
  ```

2. A non-local variable or self in a struct is returned from a method

  ```crystal
  struct X
    def m1
      @x = SomeStruct.new       # returns @x.clone
    end
    def m2
     self                       # returns self.clone
    end
    def m3
      x = SomeStruct.new        # returning local variable, do not call clone
    end
    def m4
      SomeStruct.new            # returning unnamed, do not call clone
    end
  end
  x = X.new
  a = x.m1     # Assigning to unnamed value, no need to clone here
  b = x.m2     # Ditto
  c = x.m3     # Ditto
  d = x.m4     # Ditto
  ```

3. A method is called with named struct values as parameters (or 'self' if inside a struct)

  ```crystal
  def m(a, b, c)
    return a      # 'a' is a local variable, so it won't clone, even if 'a' is a struct
  end

  struct SomeStruct
    def stuff
      x = BigInt.new("1")
      m(x, BigInt.new("2"), self)    # this does m(x.clone, BigInt.new("2"), self.clone)
    end
  end
  ```

In short: Call `clone` when it is known that the object may out-live the expression.

Note that now the implementation of `Object#clone` cannot be

```crystal
class Object
  def clone
    self      # infinite recursion here!!
  end
end
```

Instead it would have to be something like this:

```crystal
class Object
  def clone
    return self if is_a? Reference
    cloned :: typeof(self)
    # except that you can't cast a struct object to Void* neither do pointerof(self)
    # come on, I just want to read from it :(
    Intrinsics.memcpy((pointerof(cloned) as Void*), (pointerof(self) as Void*), 
                      instance_sizeof(self).to_u32, 0_u32, false)
    return cloned    # returning local variable, won't call cloned.clone
  end
end
```

May seems to be inefficient, but I believe this would be trivially optimized out everywhere. Another way of doing it is providing a magical compiler intrinsic that returns self without cloning, but seems like cheating. 

This kind of customization of the copy behavior is mandatory for any Struct that want to store a pointer to mutable data, just like `BigInt`. What do you guys think? Am I pushing too far?

**Comment by ozra** [comment]
I like the concept of clone() being called on assigns of struct vals. Definitely a must with some hook like that to handle the internal pointer cases.

**Comment by asterite** [comment]
I'm closing this. If we go down this route the language will become too complex, with many implicit methods being called under the hood. And anything implicit, which can't be seen, is hard to debug and understand.

For `BigInt` I think I'll add `add`, `mul`, `div`, `sub` methods that will modify `self` and could be used when you really need that performance (in intensive math computation where you want to avoid allocating many objects). Yes, it'll look a big ugly, but the whole language remains simple.
