### ISSUE TITLE
Remove `Pointer.new(Int)`

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#14669]
`Pointer.new(Int)` is a simple overload that delegates to `.new(UInt64)` after converting the parameter with `.to_u64!`.
That actually does not seem very sane because it assists turning all kinds of things into pointers which better shouldn't. A type that does not even autocast to `UInt64` is likely not meant to *be* a pointer. Maybe sometimes it is, but then you should be explicit about it, i.e. put `to_u64!` (or equivalent) at the call site.

This overload was probably a lot more useful before integer autocasting when untyped integer literals would not match `UInt64`. But that's old times. Nowadays, there's only a single use in stdlib for the libc constant `MAP_FAILED = Pointer(Void).new(-1)` (and technically `RTLD_NEXT` with the same value, but tha constant is unused).

We can change these constant definitions to `Pointer(Void).new(-1.to_u64!)` to be explicit.

And then deprecate `Pointer.new(Int)`.

**Comment by oprypin** [comment]
Interesting to think about. If I understand correctly, `Pointer(Void).new(123)` would keep working if the overload was removed, but before removal it would still show a deprecation message.

**Comment by straight-shoota** [comment]
Ah, that's a good point. I didn't notice that because stdlib on linux apparently makes no other calls to `Pointer.new` where the address is *not* `UInt64`. So after altering the clearly affected call `Pointer(Void).new(-1)`, there are no deprecation messages.

There are more affected calls on Windows, though. And they're like `Pointer(Void).new(123)` which would autocast to `UInt64` if the `Int` overload didn't exist.
So yes that would indeed lead to false deprecation messages and ask for changes that are not strictly necessary. 😢 But at least they're not exactly wrong either.

Would be nice if `Pointer.new(UInt64)` could take precedence somehow... 🤔

**Comment by ysbaddaden** [comment]
Maybe the autocast of untyped literals could try non deprecated methods first?

**Comment by straight-shoota** [comment]
I don't think it would be a good idea that `@[Deprecated]` affects semantics. It should be purely informational.
