### ISSUE TITLE
UTF-16 string literals

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#14670]
When working with Windows APIs, it's common that we need UTF-16 strings (instead of Crystal's `String` which is UTF-8).
[`String#to_utf16`](https://crystal-lang.org/api/1.12.2/String.html#to_utf16:Slice(UInt16)-instance-method) is available for conversion.

But most use cases of this method in stdlib are actually for string literals (e.g. `"Content Type".to_utf16`). This is a bit unnecessary because it means the string transformation happens at runtime, while it could be entirely at compile time, avoding extra computation and allocation.

A particularly intricate use case is in #14659 where we must not allocate at all. So it ends up with such a mechanism to achive compile time conversion: `UInt16.static_array({% for chr in "CRYSTAL_TRACE".chars %}{{chr.ord}}, {% end %} 0)`.

This certainly works, at least for this limited use case. But it fails for code points outside the Basic Multilingual Plane. So it's not a generic solution.

It would be nice if we had an easy tool for creating UTF-16 encoded strings.

Maybe the converstion algorithm from `String#to_utf16` could be implemented as a macro method? It's a bit complex, but not too much. I don't think we can explicitly do math operations on 16-bit integers in the macro language, though.

An alternative would be to expose a compiler primitive for UTF-16 conversion.

Related: #2886

**Comment by straight-shoota** [comment]
> That's certainly not fast, but probably good enough

Yeah, this is mainly for relatively short strings, so performance should not be an issue.

**Comment by straight-shoota** [comment]
In order to make it actually static data, we'd also need a slice literal (#2886).

**Comment by stakach** [comment]
Worth noting that Windows supports UTF8 now and encourages use of those APIs

https://learn.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page#-a-vs--w-apis

So the conversations could be avoided entirely

**Comment by straight-shoota** [comment]
> So the conversations could be avoided entirely

Would be nice. But I believe we're quite a bit away from that. The Windows ecosystem is huge and it has 30 years of wide chars in it.

**Comment by ysbaddaden** [comment]
The macro is nice, but if we want to eventually have the compiler optimize it, maybe we could just expose the `String.to_utf16` to macros? For example `{{ "CRYSTAL_TRACE".to_utf16 }}` would be lovely & fast.

**Comment by straight-shoota** [comment]
Hm, that's an interesting idea. Exposing `StringLiteral#to_utf16` would certainly have the benefit that you have the resulting literal easily available in macro land.
I like that it's exactly identical to the runtime version, but in a macro expansion which makes it clear that this happens at compile time.

FTR: Eventual compiler optimization would also be possible with `String.utf16_literal` as well. We could turn this macro into a primitive later.

_Let's focus on UTF-16 string literals here and continue the discussion about UTF-8 support on Win32 in a different issue. I'm pretty sure we won't lose all use cases for UTF-16 string literals over night, so this will still be useful._

**Comment by ysbaddaden** [comment]
The difficulty to implement `StringLiteral#to_utf16` is that there is no `SliceLiteral` and we should generate a `Slice(UInt16).literal(..., 0)` and I have no idea how to achieve that.

**Comment by stakach** [comment]
> GDI applications won't support it unless the user activates a beta setting.

You can activate the code pages in code, this is how applications like MS Edge browser run.
MS Edge being a react native app (although Microsoft is [removing react](https://thenewstack.io/from-react-to-html-first-microsoft-edge-debuts-webui-2-0/))

**Comment by straight-shoota** [comment]
Do we want to proceed with `StringLiteral#to_utf16` then?
I think it's more elegant than `String#utf16_literal` (https://github.com/crystal-lang/crystal/issues/14670#issuecomment-2154721723). An apparently more performant (https://github.com/crystal-lang/crystal/pull/14676#issuecomment-2156706765).
