### ISSUE TITLE
Package installation fails on Windows due to missing SQLite3 .lib files

### ISSUE THREAD

**Issue by Losses** [crystal-lang/crystal#14701]
I am trying to install Micrate on a Windows machine, but I am encountering an issue related to the SQLite3 library. The error message I receive is as follows:

```
I: Building: micrate
E: Error target micrate failed to compile:
Error: Cannot locate the .lib files for the following libraries: sqlite3
```

**Steps to Reproduce:**
1. Set up a Windows environment with Crystal Lang installed.
2. Attempt to install Micrate using the standard installation instructions.
3. Observe the error message related to the SQLite3 library.

**Expected Behavior:**
Micrate should install successfully on a Windows environment without issues related to locating the SQLite3 library.

**Actual Behavior:**
The installation fails with an error indicating that it cannot locate the .lib files for the SQLite3 library.

**Environment:**
- Operating System: Windows 11
- Crystal Lang Version: Crystal 1.12.1 [4cea101] (2024-04-11) LLVM: 18.1.1 Default target: x86_64-pc-windows-msvc
- Micrate Version: 0.15.1

**Workaround:**
I followed the instructions from [this gist](https://gist.github.com/zeljic/d8b542788b225b1bcb5fce169ee28c55) to compile the `sqlite3.lib` file and placed it in the `lib` directory of the Crystal executable. 

**Suggestion:**
It seems that including the `sqlite3.lib` file in the Crystal Windows release could help avoid this issue for other users. Including precompiled `.lib` files for common libraries like SQLite3 in the Crystal distribution for Windows would simplify the setup process and prevent similar issues in the future.

Thank you for your attention to this matter.

**Comment by straight-shoota** [comment]
The official Windows release package contains libraries required by the standard libraries. But that's as far as we can go for convenience for convenience. Packaging additional dependencies is an additional effort outside the scope of the Crystal project.

This might be considered by downstream package maintainers, of course.

**Comment by beta-ziliani** [comment]
As mentioned, this is not in the scope of the main project, so I'm closing it.
