### ISSUE TITLE
Playground TLS Cert Expired

### ISSUE THREAD

**Issue by foxwyn** [crystal-lang/crystal#14765]
The TLS certificate for https://play.crystal-lang.org/ has expired.

I opened this earlier in jhass/carc.in#36 - but after inspecting the cert, I realized the official playground site and the carc.in site seem to be the same instance. So I figured I'd report it here too.

**Comment by beta-ziliani** [comment]
We are aware, thank you. It's the same problem.

**Comment by foxwyn** [comment]
This has since been resolved in jhass/carc.in#36 :3
