### ISSUE TITLE
Unexpected behavior of the match method with position

### ISSUE THREAD

**Issue by ksg97031** [crystal-lang/crystal#14801]
Is this behavior intended?

### Code
I expected no response or nil to be returned for a match on below abnormal strings.
```cr
question_mark_position = 1
input = "a???????????????????????????bc"
match = input.match(/[a-zA-Z_]+/, question_mark_position)
print(match) # -> no response or nil
```

### Output
but I found that it behaves like a search method.
```
bc
```

**Comment by Blacksmoke16** [comment]
Why would you expect this to return `nil`? `bc` is valid based on the regex of `[a-zA-Z_]+`, and is matched because `question_mark_position` is making it skip the first, which otherwise would have matched.

So to me it seems this is working as designed.

**Comment by ysbaddaden** [comment]
@ksg97031 You're searching for alphanumeric chars _starting from_ index 1, not _exactly at_ index 1, so the regexp skips the question marks in the string and finds `bc`. It matched.

**Comment by ksg97031** [comment]
@Blacksmoke16 @ysbaddaden
Thank you for the answer.

I was confused because I thought the keyword 'match' doesn't mean 'search' or 'find'.
But upon checking, I found that even in Ruby for a long time, 'match' has been used for searching.

So, I substituted the code below to match exactly:

```ruby
input = "a?bc"
match = input[position..].match(/^[a-zA-Z_]+/)
if match
  print(match[0])
end
```
Could you please let me know if there is a better way to perform exact matching?

Thank you!

**Comment by Blacksmoke16** [comment]
@ksg97031 Maybe https://crystal-lang.org/api/String.html#match_full%28regex%3ARegex%29%3ARegex%3A%3AMatchData%7CNil-instance-method ?

**Comment by ksg97031** [comment]
@Blacksmoke16 Thank you for advice!

**Comment by straight-shoota** [comment]
[`String#match`](https://crystal-lang.org/api/1.13.1/String.html#match(regex:Regex,pos=0,*,options:Regex::MatchOptions=Regex::MatchOptions::None):Regex::MatchData|Nil-instance-method) with a position argument *starts* searching for a match from that position. But not *limited* to that position.
If you want the regex match to be *anchored*, please use the appropriate option: `"a????bc".match(/[a-z]+/, 1, options: :anchored) # => nil`

**Comment by ksg97031** [comment]
> [`String#match`](https://crystal-lang.org/api/1.13.1/String.html#match(regex:Regex,pos=0,*,options:Regex::MatchOptions=Regex::MatchOptions::None):Regex::MatchData%7CNil-instance-method) with a position argument _starts_ searching for a match from that position. But not _limited_ to that position. If you want the regex match to be _anchored_, please use the appropriate option: `"a????bc".match(/[a-z]+/, 1, options: :anchored) # => nil`

Previously, it seemed like it wasn't working, but I tried it again and confirmed that it provides the expected response. I must have misunderstood earlier. Thank you for your assistance!
