### ISSUE TITLE
Failed to update crystal with package managers on Windows

### ISSUE THREAD

**Issue by yanecc** [crystal-lang/crystal#14812]
## Bug Report

Failed to update crystal with scoop and other package managers on Windows.

version: 1.13.1

```
+             $bin = (Get-Command $target).Source
+                     ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (crystal.exe:String) [Get-Comman
   d], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Co
   mmands.GetCommandCommand

Can't shim 'crystal.exe': File doesn't exist.
```

The package directory was changed to ./crystal-release/ and the package managers on Windows couldn't find the executables. Is this a mistake or a permanent change? If it is a mistake, please re-upload the 1.13.1 release package.

**Comment by ysbaddaden** [comment]
I downloaded the ZIP packages, and there was indeed a change between 1.12 and 1.13: everything is now inside a `crystal-release` directory, when it used to be at the root of the package. That's the issue.

**Comment by HertzDevil** [comment]
1.13.0 is fine, I believe this is just a human error (we haven't automated the part that uploads the artifacts as release files yet)

**Comment by beta-ziliani** [comment]
I uploaded the zip again, hopefully that should be OK. But I don't know how to process the .exe file, I understand that it has the same issue, right?

**Comment by robmullr** [comment]
@beta-ziliani I installed the exe yesterday with no issue.

**Comment by yanecc** [comment]
@beta-ziliani I'm glad you reuploaded the release file, but the file structure in the current archive is still different from the past.

```
|-crystal-1.13.1-windows-x86_64-msvc-unsupported.zip
  |-__MACOSX
  |-crystal-1.13.1-windows-x86_64-msvc-unsupported
    |...(The files inside this folder are the contents of the past compressed packages.)
```

This means that the package managers on Windows will still not perform the installation correctly.

**Comment by yanecc** [comment]
> @yanecc thanks and sorry for the mess. I think it should be ok now.

No problem now. Thanks for your work.

**Comment by burque505** [comment]
I've opened an issue on the scoop bucket [here](https://github.com/neatorobito/scoop-crystal/issues/34), but perhaps that's not the problem. I just tried scoop again today, 8/8/2024, with the following results.
```
Installing 'crystal' (1.13.1) [64bit] from 'crystal-preview' bucket
Loading crystal-1.13.1-windows-x86_64-msvc-unsupported.zip from cache
Checking hash of crystal-1.13.1-windows-x86_64-msvc-unsupported.zip ... ok.
Extracting crystal-1.13.1-windows-x86_64-msvc-unsupported.zip ... done.
Linking ~\scoop\apps\crystal\current => ~\scoop\apps\crystal\1.13.1
Creating shim for 'crystal'.
Get-Command : The term 'crystal.exe' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\HP6300\scoop\apps\scoop\current\lib\install.ps1:757 char:21
+             $bin = (Get-Command $target).Source
+                     ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (crystal.exe:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand

Can't shim 'crystal.exe': File doesn't exist.
```
@yanecc reported an analogous problem:
```
The package directory was changed to ./crystal-release/ and the package managers on Windows couldn't find the executables. Is this a mistake or a permanent change? If it is a mistake, please re-upload the 1.13.1 release package.
```

**Comment by yanecc** [comment]
> I've opened an issue on the scoop bucket [here](https://github.com/neatorobito/scoop-crystal/issues/34), but perhaps that's not the problem. I just tried scoop again today, 8/8/2024, with the following results.
> 
> ```
> Installing 'crystal' (1.13.1) [64bit] from 'crystal-preview' bucket
> Loading crystal-1.13.1-windows-x86_64-msvc-unsupported.zip from cache
> Checking hash of crystal-1.13.1-windows-x86_64-msvc-unsupported.zip ... ok.
> Extracting crystal-1.13.1-windows-x86_64-msvc-unsupported.zip ... done.
> Linking ~\scoop\apps\crystal\current => ~\scoop\apps\crystal\1.13.1
> Creating shim for 'crystal'.
> Get-Command : The term 'crystal.exe' is not recognized as the name of a cmdlet, function, script file, or operable
> program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At C:\Users\HP6300\scoop\apps\scoop\current\lib\install.ps1:757 char:21
> +             $bin = (Get-Command $target).Source
> +                     ~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (crystal.exe:String) [Get-Command], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand
> 
> Can't shim 'crystal.exe': File doesn't exist.
> ```
> 
> @yanecc reported an analogous problem:
> 
> ```
> The package directory was changed to ./crystal-release/ and the package managers on Windows couldn't find the executables. Is this a mistake or a permanent change? If it is a mistake, please re-upload the 1.13.1 release package.
> ```

Since the scoop-crystal repository was not updated after the package being re-uploaded, you may successfully update it by skipping the hash check.

``` bash
scoop update crystal --skip-hash-check
```

**Comment by burque505** [comment]
@yanecc, thanks, but it didn't work for me as I had already performed 'scoop uninstall crystal'.
