### ISSUE TITLE
Add `has_key?` to `NamedTupleLiteral` and `HashLiteral`

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#14841]
## Feature Request

Currently both named tuple and hash literals implement `#[]` that returns the value as the specified key, or `nil` if it does not exist. However this makes it not really easy to know if the key exists and has a value of `nil`, or if it just doesn't exist at all. Adding in `#has_key?` would make this a lot simpler.

**Comment by Fryguy** [comment]
I thought this already exists for Hashes?

**Comment by Blacksmoke16** [comment]
@Fryguy Yes, but this ticket is for the macro ASTNode equivalents.

**Comment by Fryguy** [comment]
Ohh macros 👍.  I saw literal but didn't interpret that as for macros.

**Comment by kamil-gwozdz** [comment]
hey, i submitted a PR that implements those methods 

https://github.com/crystal-lang/crystal/pull/14890
