### ISSUE TITLE
Docs comments only appear if they are written directly above `getter`

### ISSUE THREAD

**Issue by BigBoyBarney** [crystal-lang/crystal#14848]
## Bug Report

This works as expected
```crystal
Struct Media
  include JSON::Serializable

  @[JSON::Field(key: "idMal")]
  # The mal id of the media
  getter id_mal : Int32?
end
```
![image](https://github.com/user-attachments/assets/0270c8c3-7150-423b-83c5-39791484a368)
![image](https://github.com/user-attachments/assets/7a71b681-cddd-422d-9d24-a9410e100ab3)

This, however, does not
```crystal
Struct Media
  include JSON::Serializable

  # The mal id of the media
  @[JSON::Field(key: "idMal")]
  getter id_mal : Int32?
end
```
![image](https://github.com/user-attachments/assets/9b384d5c-41fa-474a-ae58-dda6a70b5992)
![image](https://github.com/user-attachments/assets/d862e999-432d-4b72-853a-3a30fb0d168c)

**Comment by Blacksmoke16** [comment]
#9332 handled this for other things, but this one is prob special in that it's a macro call vs macro definition.

**Comment by Blacksmoke16** [comment]
Duplicate of #6449
