### ISSUE TITLE
Weird compilation error happening only on CI Github Action

### ISSUE THREAD

**Issue by noraj** [crystal-lang/crystal#14866]
## Bug Report

I have a [small project](https://github.com/noraj/quartz-utils) where I wrote [a script](https://github.com/noraj/quartz-utils/blob/master/compile_x86_64-linux.cr) to compile a static binary. As static compilation works only on Alpine Linux, I wrote that script that is meant to be executed in an [Alpine Linux container on the CI (Github Action)](https://github.com/noraj/quartz-utils/blob/master/.github/workflows/release.yml).

On my Arch Linux machine the script runs as expected (it's normal ldd fails on that platform).

```
➜ crystal -v
Crystal 1.13.0 (2024-07-09)

LLVM: 18.1.8
Default target: x86_64-pc-linux-gnu

➜ crystal run compile_x86_64-linux.cr
[+] url2host-x86_64-linux-gnu
  [+] crystal build src/url2host.cr --release --static --no-debug -o bin/url2host-x86_64-linux-gnu --cross-compile --target x86_64-linux-gnu
  [+] cc bin/url2host-x86_64-linux-gnu.o -o bin/url2host-x86_64-linux-gnu  -rdynamic -static -L/usr/bin/../lib/crystal -lpcre2-8 -lgc -lpthread -ldl -lpthread -levent -lrt -lpthread -ldl
/usr/bin/ld: cannot find -lgc: No such file or directory
/usr/bin/ld: cannot find -levent: No such file or directory
collect2: error: ld returned 1 exit status
[+] url2host-x86_64-linux-musl
…
```

But on the Alpine container ([crystallang/crystal:1.13-alpine#sha256:10490e1a0bf7c8780c8d30c2f3d840f3761ff389a7b9841a30a03aa8a0eb0c82](https://hub.docker.com/layers/crystallang/crystal/1.13-alpine/images/sha256-10490e1a0bf7c8780c8d30c2f3d840f3761ff389a7b9841a30a03aa8a0eb0c82?context=explore)), there is a quite inexplicable error ([CI logs here](https://github.com/noraj/quartz-utils/actions/runs/10240164933/job/28326604376)):

```
➜ Run crystal compile_x86_64-linux.cr
[+] url2host-x86_64-linux-gnu
  [+] crystal build src/url2host.cr --release --static --no-debug -o bin/url2host-x86_64-linux-gnu --cross-compile --target x86_64-linux-gnu
No such file or directory (Exception)
  from /crystal/src/array.cr:114:31 in 'codegen'
  from /crystal/src/compiler/crystal/compiler.cr:211:16 in 'compile'
  from /crystal/src/compiler/crystal/command.cr:357:5 in 'run'
  from /crystal/src/compiler/crystal.cr:11:1 in '__crystal_main'
  from /crystal/src/crystal/main.cr:118:5 in 'main'
  from src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
  [+] 
[+] url2host-x86_64-linux-musl
…
```

```
➜ docker pull crystallang/crystal:1.13-alpine
1.13-alpine: Pulling from crystallang/crystal
Digest: sha256:10490e1a0bf7c8780c8d30c2f3d840f3761ff389a7b9841a30a03aa8a0eb0c82
Status: Downloaded newer image for crystallang/crystal:1.13-alpine
docker.io/crystallang/crystal:1.13-alpine

➜ docker run --rm -it crystallang/crystal:1.13-alpine crystal -v
Crystal 1.13.1 [0cef61e51] (2024-07-12)

LLVM: 18.1.6
Default target: x86_64-unknown-linux-musl
```

Could it be a difference in behavior between glibc and musl?

I know it was previously working with `crystallang/crystal:1.12-alpine` in the CI so I tried to reproduce locally with docker. But on my machine within the exact same versions of the docker image, it works.

```
➜ docker run --rm -it -v $PWD:/workspace -w /workspace crystallang/crystal:1.12.1-alpine crystal compile_x86_64-linux.cr
[+] url2host-x86_64-linux-gnu
  [+] crystal build src/url2host.cr --release --static --no-debug -o bin/url2host-x86_64-linux-gnu --cross-compile --target x86_64-linux-gnu
  [+] cc bin/url2host-x86_64-linux-gnu.o -o bin/url2host-x86_64-linux-gnu  -rdynamic -static -L/usr/bin/../lib/crystal -lpcre2-8 -lgc -lpthread -ldl -lpthread -levent -lrt -lpthread -ldl
[+] url2host-x86_64-linux-musl
  [+] crystal build src/url2host.cr --release --static --no-debug -o bin/url2host-x86_64-linux-musl --cross-compile --target x86_64-linux-musl
  [+] cc bin/url2host-x86_64-linux-musl.o -o bin/url2host-x86_64-linux-musl  -rdynamic -static -L/usr/bin/../lib/crystal -lpcre2-8 -lgc -lpthread -ldl -levent
[+] stripansi-x86_64-linux-gnu
  [+] crystal build src/stripansi.cr --release --static --no-debug -o bin/stripansi-x86_64-linux-gnu --cross-compile --target x86_64-linux-gnu
  [+] cc bin/stripansi-x86_64-linux-gnu.o -o bin/stripansi-x86_64-linux-gnu  -rdynamic -static -L/usr/bin/../lib/crystal -lpcre2-8 -lgc -lpthread -ldl -lpthread -levent -lrt -lpthread -ldl
[+] stripansi-x86_64-linux-musl
  [+] crystal build src/stripansi.cr --release --static --no-debug -o bin/stripansi-x86_64-linux-musl --cross-compile --target x86_64-linux-musl
  [+] cc bin/stripansi-x86_64-linux-musl.o -o bin/stripansi-x86_64-linux-musl  -rdynamic -static -L/usr/bin/../lib/crystal -lpcre2-8 -lgc -lpthread -ldl -levent

➜ docker run --rm -it -v $PWD:/workspace -w /workspace crystallang/crystal:1.13.1-alpine crystal compile_x86_64-linux.cr
[+] url2host-x86_64-linux-gnu
  [+] crystal build src/url2host.cr --release --static --no-debug -o bin/url2host-x86_64-linux-gnu --cross-compile --target x86_64-linux-gnu
  [+] cc bin/url2host-x86_64-linux-gnu.o -o bin/url2host-x86_64-linux-gnu  -rdynamic -static -L/usr/bin/../lib/crystal -lpcre2-8 -lgc -lpthread -ldl -lpthread -levent -lrt -lpthread -ldl
[+] url2host-x86_64-linux-musl
  [+] crystal build src/url2host.cr --release --static --no-debug -o bin/url2host-x86_64-linux-musl --cross-compile --target x86_64-linux-musl
  [+] cc bin/url2host-x86_64-linux-musl.o -o bin/url2host-x86_64-linux-musl  -rdynamic -static -L/usr/bin/../lib/crystal -lpcre2-8 -lgc -lpthread -ldl -levent
[+] stripansi-x86_64-linux-gnu
  [+] crystal build src/stripansi.cr --release --static --no-debug -o bin/stripansi-x86_64-linux-gnu --cross-compile --target x86_64-linux-gnu
  [+] cc bin/stripansi-x86_64-linux-gnu.o -o bin/stripansi-x86_64-linux-gnu  -rdynamic -static -L/usr/bin/../lib/crystal -lpcre2-8 -lgc -lpthread -ldl -lpthread -levent -lrt -lpthread -ldl
[+] stripansi-x86_64-linux-musl
  [+] crystal build src/stripansi.cr --release --static --no-debug -o bin/stripansi-x86_64-linux-musl --cross-compile --target x86_64-linux-musl
  [+] cc bin/stripansi-x86_64-linux-musl.o -o bin/stripansi-x86_64-linux-musl  -rdynamic -static -L/usr/bin/../lib/crystal -lpcre2-8 -lgc -lpthread -ldl -levent
```

So this seems to occur only on Github Action CI.

On my host I use docker 27.1.1 (API version 1.46), the CI use docker API 1.45. Maybe it's docker environment related?

**Comment by Blacksmoke16** [comment]
Why are you cross compiling in this context? If all you want is a static binary that would work with both glibc and musl libc just do like:

```sh
crystal build src/url2host.cr --release --static --no-debug -o bin/url2host-x86_64-linux-gnu
```
And it'll be fine.

**Comment by noraj** [comment]
Thanks for teh CI example.

However, I'm not blocked, I'm not asking for assistance, as running the script on docker directly works, it just the CI that doesn't.

In fact, I was reporting this edge case, as the compiler was asking me to:

> Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues

**Comment by ysbaddaden** [comment]
The cross compilation might be an hint: you can't cross compile and link to glibc from musl-libc, unless you install glibc and specify it as the actual link target, which would defeat the point (just compile on a glibc distro).

You try to codegen an object for glibc and then expect it to be linkable against musl-libc (that won't work). Now, it's failing before it tries to link, and it's only happening on CI which is even weirder 🤨

You want a _single executable_ statically linked against musl-libc only, and then that executable will run on every Linux distribution (musl, glibc, ...) without any dependency (not guaranteed with glibc that will still try to `dlopen`). This can be achieved with a mere `shards build --release --static`

Seeing if removing the glibc cross compilation (that can't work) or using the above shards command fixes the issue will be interesting.

**Comment by noraj** [comment]
I admit I know nothing to compilation and cross-compilation. Ideally I'd like to provide a no dependency static pre-compiled binary for all tier 1 and tier 2 targets, but I guess it's impossible. That's why I focused on x86_64-linux (gnu + musl).

I try to build static binaries from Alpine because the documentation says it's the only way:

> Building fully statically linked executables is currently only supported on Alpine Linux.
>
> [Ref](https://crystal-lang.org/reference/1.12/man/crystal/index.html#creating-a-statically-linked-executable)

> You try to codegen an object for glibc and then expect it to be linkable against musl-libc (that won't work). Now, it's failing before it tries to link, and it's only happening on CI which is even weirder 🤨

As you can see it seems to work from Alpine docker container directly but not on the CI that uses the same docker image.

> Seeing if removing the glibc cross compilation (that can't work) or using the above shards command fixes the issue will be interesting.

So the cross-compilation flag works only for GNU C library targets? Because the [Cross-compilation documentation](https://crystal-lang.org/reference/1.13/syntax_and_semantics/cross-compilation.html) says nothing about glibc vs musl c or limitations about targets or hosts.

Sorry for being a noob about compilation.

**Comment by ysbaddaden** [comment]
The problem of glibc is that even when statically linked it will still try to load some dynamic libraries (🤷), this is why we recommend to compile against musl-libc (e.g. alpine) which is an alternative libc that will create a real static binary that will run on every Linux.

You don't have to bother about glibc or musl or with cross compilation: run `shards build --release --static` in an alpine docker image and you'll get a static executable.

Cross compilation is for targeting another architecture (x86 -> arm) or another operating system (Linux -> Windows) or both which will require a more complex setup (e.g. cross toolchains, building libs, or linking in qemu images, etc).

**Comment by straight-shoota** [comment]
Also note the helper script for static linking / cross-compiling doesn't serve any useful purpose. If you just want to execute the linker command directly on the compiler host, you can simply drop the `--cross-compile` option and the compiler will do that for you directly.
The purpose of `--cross-compile` is to link the compiled object file in a different environment, typically on a different machine.

**Comment by straight-shoota** [comment]
And the reason for "No such file or directory (Exception)" is that the target directory (`bin`) doesn't exist.

This is not at all obvious, though. This error message should be more descriptive.
And ideally, the compiler can probably create the directory if missing.

**Comment by straight-shoota** [comment]
I'm closing this in favour of  #14868

@noraj If you have further questions about compiling, please refer to https://forum.crystal-lang.org or one of the [community chats](https://crystal-lang.org/community/).
