### ISSUE TITLE
`Number#humanize` raises on infinity and NaN

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#14955]
`OverflowError` is raised when calculating the number of digits needed, because of the `log.floor.to_i` line:

https://github.com/crystal-lang/crystal/blob/791b0e451766503e4a8d2b63fd1bc726b9948276/src/humanize.cr#L218-L224

`#format` has special handling to return the strings `(-)Infinity` and `NaN`, so `#humanize` should probably follow suit, without appending any units.

**Comment by rajatkriplani** [comment]
```Number#humanize``` raises an OverflowError when attempting to humanize ```Infinity``` or ```NaN```, because code tries to calculate the number of digits using ```log.floor.to_i```:
```
log = Math.log10(abs)
digits = log.floor.to_i + 1
```
```log10``` of ```Infinity``` or ```NaN``` is undefined, this causes the error.

instead can this be done:
```
Float::INFINITY.humanize  # => "Infinity"
Float::NAN.humanize       # => "NaN"
```
