### ISSUE TITLE
[formatter] correct the whitespace before left parentheses when invoke a method?

### ISSUE THREAD

**Issue by zw963** [crystal-lang/crystal#15015]
```crystal
def foo(a, b)
end

foo (a: 100, b: 200)

foo (
  a: 100,
  b: 200,
)
```

Both cases, get same error:

```
 30 | foo (a: 100, b: 200)
              ^
Error: unexpected token: "100"
```

```
 30 | a: 100,
         ^
Error: unexpected token: "100"
```

I thought formatter can fix above code:

```crystal
def foo(a, b)
end

foo(a: 100, b: 200)

foo(
  a: 100,
  b: 200,
)
```

![image](https://github.com/user-attachments/assets/1cb482d4-4e6c-44bf-93d7-5adeb1606b36)

**Comment by straight-shoota** [comment]
The formatter is based on the parser. If the parser fails to parse something, the formatter can't fix it.
I don't think the formatter should apply a change like this. It might seem obvious in this example, but it may not be so obvious in other cases, when the first argument is not a named argument.

**Comment by zw963** [comment]
I tested, Ruby get syntax error too.

```
 ╰─ $ ruby 1.cr
1.cr: --> 1.cr
syntax error, unexpected labelsyntax error, unexpected label
> 4  foo (a: 100, b: 200)
> 6  foo (
> 7    a: 100,
> 8    b: 200,
> 9  )

1.cr:4: syntax error, unexpected label (SyntaxError)
foo (a: 100, b: 200)
     ^~
1.cr:7: syntax error, unexpected label
  a: 100,
  ^~
```


I thought it is wired that a single space causes an syntax error. although, the only valid syntax form same as non-space version.
