### ISSUE TITLE
Add `Char#==(other : String)`

### ISSUE THREAD

**Issue by nobodywasishere** [crystal-lang/crystal#15014]
Until type-safe equality is implemented, small things like this can be easy to miss and cause confusion.

For example:
```crystal
word = "the lazy dog"

if word[5] == "a"
  # doesnt run, can be hard to debug
end

if word[5] == 'a'
  # runs
end
```

This would probably check the other string length to see if it's one, and then run the normal Char equality with the char at 0.

**Comment by straight-shoota** [comment]
I'm not sure this is a good idea. `String` and `Char` are substantially different types. They can *represent* the same value in different way, which can cause confusion.

If we do this, the inverse (`String#==(Char)`) should implemented as well.

**Comment by soanvig** [comment]
@straight-shoota I just encountered this "bug" by myself. I'm new to Crystal.
Shouldn't compiler reject such comparison?

I mean, at least for the time being, couldn't this typecheck be hardcoded? It doesn't have to be elegant (widely working type-safe equality), if it requires substantial amount of work.

My reasoning for why it's easy to make an error, and probably it happens relatively often:
For the most part most applications operate on strings. Thus, muscle-memory is writing `"<char>"` (double quotes). Sometimes, depending on app quite rarely we work with characters (enumerating strings for example). Then we are in unfamiliar situation (working with chars) mixed with common situation (using strings).

Futhermore, I think that is a reason to have that one particular check hardcoded. It would work as type-aware linter rule, until some proper and more general solution is implemented.

WDYT?

**Comment by nobodywasishere** [comment]
It would be straightforward to add such methods:

```crystal
class String
  @[Deprecated("This equality is type-unsafe and may always evaluate to false.")]
  def ==(other : Char)
    false
  end
end
```

But I would also recommend throwing something like [this file](https://gist.github.com/nobodywasishere/6c1d42eda30d469346b21516b6294710) into your project to give warnings for all type-unsafe equalities

**Comment by soanvig** [comment]
@nobodywasishere I was able to do this and reversed (char to string). Compiler properly throws. Thank you for that "type-safe" suggestion

**Comment by straight-shoota** [comment]
You're right that ideally the comparison should either succeed or fail at compile time. Such semantics would work well for simple types, but with more complexity (unions and generics) there are non-trivial problems.
See https://github.com/crystal-lang/crystal/issues/10277 for a discussion on that.
