### ISSUE TITLE
Add `Iterator(T).empty`

### ISSUE THREAD

**Issue by spuun** [crystal-lang/crystal#15038]
## Feature Request

Sometimes I want to return an empty iterator and I haven't found a way of doing this without allocations. 

I think `Iterator(T).empty` would be a nice addition.

**Comment by straight-shoota** [comment]
`Iterator.of(Iterator.stop)` creates an empty iterator. But it's typed as `Iterator(Iterator::Stop)`, so it does not match any particular `Iterator(T)` interface. I don't think there is currently a way to convince `SingletonIterator` to simulate that.
But adding a constructor overload which unties the type of `@element` from the generic type argument `T`, could do the trick:
```cr
private struct Iterator::SingletonIterator(T)
  def initialize(@element : Stop)
  end
end

def Iterator.empty
  SingletonIterator(T).new(stop)
end

Iterator(String).empty.is_a?(Iterator(String)) # => true
```

**Comment by spuun** [comment]
Right. I tried using `SingletonIterator` but failed. I didn't think about changing it.

Dunno if it matters, but won't  `sizeof(SingletonIterator(T)) == sizeof(T)` while `sizeof(EmptyIterator(T)) == 0` (as done in #15039).

**Comment by straight-shoota** [comment]
Yeah, that's true.

**Comment by spuun** [comment]
Dunno if it's too much, but adding an overload like
```crystal
def self.empty(_not_used : T)
   EmptyIterator(T).empty
end
```
could be nice syntax suger. Then it would be possible to do `return Iterator.empty(@ivar)` and you don't have to deal with the type. If you change the type of the variable you don't have to update the type of the iterator.

And/or 
```crystal
def self.empty(_not_used : T.class)
   EmptyIterator(T).empty
end
```
Is this preferred over the one currently suggested? It would look more like `Iterator.of`.

**Comment by straight-shoota** [comment]
`Iterator.empty(@ivar)` looks weird to me. It's not very self-explanatory why you would pass a value to create an *empty* iterator.

And `Iterator.empty(Foo)` doesn't seem to have any relevant benefit over `Iterator(Foo).empty`.
