### ISSUE TITLE
Allow log events to be emitted with a dynamic log level/severity

### ISSUE THREAD

**Issue by jgaskins** [crystal-lang/crystal#15083]
Some log events can benefit from their log level being set at run time, but there isn't currently a way to do that. All log events are currently emitted at a level known at compile time, defined by [a macro](https://github.com/crystal-lang/crystal/blob/879ec124747c287605e349183a3c9143174659e8/src/log/log.cr#L41-L77). This is _generally_ a good idea, but not universally.

**Comment by straight-shoota** [comment]
There's previous discussion on this topic in #9546.
The state of things there is that we're still looking for legitimate use cases for log level definition at runtime. Could provide some examples how you'd like to use this?

**Comment by jgaskins** [comment]
I read through #9546 last night after @Sija [pointed it out](https://github.com/crystal-lang/crystal/pull/15084#issuecomment-2409514878). This seemed like a harmless refactor to me but y'all seem pretty strongly against it.

**Comment by straight-shoota** [comment]
I don't oppose this change. But it needs justification. That's why I'm asking for use cases.
