### ISSUE TITLE
Provide a default REPL for crystal in bin/ similar to irb/pry

### ISSUE THREAD

**Issue by rubyFeedback** [crystal-lang/crystal#15154]
I just fetched the latest crystal version, 1.14.0.

As it has been a while since I last used crystal, I will go through the tutorial at https://crystal-lang.org/reference/1.14/tutorials/basics/index.html next. To my surprise, though, the
crystal I downloaded does not seem to come with any REPL under bin/. In bin/ I can only
see "crystal" and "shards".

I would like to propose that crystal comes with a default REPL, similar to "python" or
"irb" or "pry". This does not necessarily have to be feature-complete, but just to get the
process going. It is not strictly necessary as one can just use crystal files itself and ask for
user input, but I think for quick testing of crystal in an interactive manner it can be quite
convenient, such as with irb. I quickly use irb to copy/paste or test some ruby code or
behaviour I am unsure of (and also finding useful information in regards to google search
is pretty difficult for a language such as crystal, as there are not that many resources,
so a REPL can be a bit of extra-help too, especially if the help-options are very trivial to
use. See the latest irb + reline as example.)

**Comment by ysbaddaden** [comment]
See `crystal i` but it's not built by default. You'll probably have to compile a crystal binary by yourself.

**Comment by straight-shoota** [comment]
You can read more about the interpreter at https://crystal-lang.org/2021/12/29/crystal-i/
