### ISSUE TITLE
Scope method

### ISSUE THREAD

**Issue by BigBoyBarney** [crystal-lang/crystal#15185]
From a discussion on Discord with StraightShoota about scoped variables. I think it could be useful to be able to limit the scope of a variable in a syntactically sound manner, for example:

```cr
def scope(&)
  yield
end

scope do
  x = 1
end

x # Error: undefined local variable or method 'x' for top-level
```

Current workaround would be something like
```cr
loop do
  x = 1
  break
end

1.times do
  x = 1
end
```

**Comment by straight-shoota** [comment]
We'll need to look at actual use cases.

I have some doubts about general usefulness. Scope limitations are mostly relevant for looping, and all constructs except `while` already implictly create a scope.
So the only use case I can imagine is inside a `while` loop. 

```cr
while condition
  scope do
    body
  end
end
```

But if you need to loop with scoping, there are already plenty of alternatives, like `loop`. And it's even more concise IMO:

```cr
loop do
  break unless condition
  body
end
```

**Comment by BigBoyBarney** [comment]
Intermediate calculations requiring a few variables, but where only the result matters, could be such a use-case IMO, where you wouldn't need to clutter the namespace with variables.
Of course, you could extract the actual logic into a method and have the variable scoped that way, but I think the syntax would fit in very well with the rest of the stdlib. I can't really think of other use-cases off the top of my head, but I also don't see a reason why it wouldn't be useful to have, as it doesn't directly overlap with anything and is very idiomatic.

**Comment by straight-shoota** [comment]
The rationale for adding anything to stdlib must be that it provides reasonably useful value. Unless we can be sure about that, it's not going to happen.

**Comment by BigBoyBarney** [comment]
As I mentioned in my previous comment, scoping variables outside of loops is reasonably useful.

An example from [AnimeGameTools](https://codeberg.org/Sylphrena/AnimeGameTools)
```cr
y = "'y'".colorize(:green)
yes = "'yes'".colorize(:green)
n = "'n'".colorize(:red)
no = "'no'".colorize(:red)
print "Would you like to generate new keys? (#{y}/#{n}): "
choice = gets.try &.strip.downcase
until ["y", "n"].includes? choice
  print "Please enter either #{y} for #{yes}, or #{n} for #{no}: "
  choice = gets
end
```
Scoping this wouldn't clutter the namespace with the variables.

**Comment by straight-shoota** [comment]
I'm not sure I understand the issue with cluttering the namespace.
What is the negative practical effect with that?

And is it not possible to extract isolated portions into private defs? I believe this is usually a preferred solution because it labels the purpose and defines a clear interface of inputs and outputs.

**Comment by ysbaddaden** [comment]
Exactly my thought when reading this thread: **you want to extract private methods**. It will create an explicit scope, improve the readability of the program, and it's zero cost since LLVM will just inline the calls.

**Comment by BigBoyBarney** [comment]
Alright, I see. Thank you for your inputs!

Would LLVM automatically inline the call even without me specifying `@[AlwaysInline]`?

**Comment by ysbaddaden** [comment]
Yes. It can't be 100% certainty, but the threshold for LLVM to inline is _very_ high for `--release` (aka `--single-module -O3`).

Also `@[AlwaysInline]` is a misnomer, it's similar to `inline` in C that is merely a hint to the compiler that we want the function to be inlined, LLVM is still free to not inline (there's some discussion to get Crystal to always do the inlining).

Check the symbols of the executable. You shouldn't be able to find private methods. And anyway, a call only matters in tight-loop algorithms (e.g. PRNG, crypto).

**Comment by BigBoyBarney** [comment]
That makes sense, TIL :D. I'm closing this issue then.

Thank you!
