### ISSUE TITLE
Incorrect `ASTNode#to_s` representation

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#15286]
## Bug Report

While playing with #14880, I noticed that if you had a node like:

```cr
{% verbatim do %}
  {%
    klass = [] of String
    generics = [] of String

    if !klass.empty? && generics.empty?
      klass.raise "oh noes"
    end
  %}
{% end %}
```
that when you `#to_s` it you get is something like:

```cr
{% verbatim do %}
  {% 
     klass = [] of String
     generics = [] of String

     if (!klass.empty?) && generics.empty?
       klass.raise("oh noes")
     end 
  %}
{% end %}
```
Adding `()` around the `#raise` call is expected, but what's with the `(!klass.empty?)`? I feel like that's a set of useless parentheses that shouldn't be getting added in the first place?

Example code:

```cr
macro test(node)
  {%
    puts node
  %}
end

test(
{% verbatim do %}
  {%
    klass = [] of String
    generics = [] of String

    if !klass.empty? && generics.empty?
      klass.raise "oh noes"
    end
  %}
{% end %}
)
```

**Comment by Blacksmoke16** [comment]
Upon second look I think this isn't really a bug but just a by-product if having a `Call` as part of a conditional in the `if`. I.e. having them in cases of like:

```cr
{% verbatim do %}
  {%
    if 1 == 1 || 2 == 2
      klass.raise "oh noes"
    end
  %}
{% end %}
```
makes sense to ensure the condition of the `if` is `(1 == 1) || (2 == 2)`. So doesn't really seem worth it to try and add a bunch of complexity to determine when we need to add them versus not.

**Comment by straight-shoota** [comment]
But `==` is a binary operator, `!` is an unary one, so it has very strong binding. The parethesis shouldn't really be necessary here.

**Comment by Blacksmoke16** [comment]
Fair enough :+1:
