### ISSUE TITLE
Add TypeNode#constant macro method to return the value of a namespaced constant

### ISSUE THREAD

**Issue by jreinert** [crystal-lang/crystal#1586]
the following snippet should roughly explain what i expect:

``` crystal
class Object
  macro foo
    {%if @type.superclass.has_constant?("FOO") %}
      FOO = @type.superclass.some_way_to_get_constant("FOO") + ["bar"]
    {% else %}
      FOO = ["bar"]
    {% end %}
  end
end

class Foo
end

class Bar < Foo
end

Foo::FOO # => ["bar"]
Bar::FOO # => ["bar", "bar"]
```

**Comment by jreinert** [comment]
the main reason for this is to make json_mapping inheritable:

``` crystal
module JSON::Mapping
  macro json_mapping(properties, strict = false)
    JSON_MAPPING = {{properties}}
    # ...
    def initialize(_pull : JSON::PullParser)
      {% if @type.superclass.has_constant?(JSON_MAPPING) %}
        super
      {% end %}
      # ...
    end

    def to_json(io : IO)
      {% if @type.superclass.has_constant?("JSON_MAPPING") %}
        {% properties = @type.superclass::JSON_MAPPING.merge(properties) %}
      {% end %}
      # ...
    end
  end
end
```

**Comment by asterite** [comment]
Can you show an example of a class and a child class that use json mapping? Because when consuming a JSON object you'd have to check for the keys, and a call to `super` will "consume" all of that.

I guess this is motivated by a real use case when there are inherited entities. What is this case?

**Comment by asterite** [comment]
In any case, I think something like `type.constant("Foo")` could work: it will return a constant's value if it's a value, or a TypeNode if it's a type (or nil/error if the constant isn't defined). And the `type.has_constant?("Foo")` sounds good too.

**Comment by jreinert** [comment]
has_constant? i already have opened a pull request for. For the example see the updated comment.

**Comment by sdogruyol** [comment]
Since https://github.com/crystal-lang/crystal/pull/1585 is merged, can we close this?

**Comment by jreinert** [comment]
@sdogruyol that only implements has_constant? but doesn't return the value of it.
