### ISSUE TITLE
Additional alternative literal for strings

### ISSUE THREAD

**Issue by Spaceghost** [crystal-lang/crystal#1598]
I really enjoy using pipes | for surrounding string literals and other kinds of literals in ruby. Would it be possible to support that too?

**Comment by asterite** [comment]
Is there a case you remember where using one of `( [ <` wasn't enough?

**Comment by Spaceghost** [comment]
Mostly code examples, docs. That kind of thing. I use pipe because the
others are more commonly used and pipe isn't nearly as common except when
showing shell code.

I like to use one literal rather consistently. In Ruby, I use it for every
literal that I can.

**Comment by asterite** [comment]
I'm closing this. This adds more syntax variations that are not very needed. I mostly see the delimiters I mentioned above when I write/browse Ruby code. In other cases heredoc can be used. The less syntax variation there is and users have to learn, the better.

**Comment by Spaceghost** [comment]
That works for me, I'll just write ruby like I write ruby and write crystal
some other way.
