### ISSUE TITLE
more advanced ranges?

### ISSUE THREAD

**Issue by will** [crystal-lang/crystal#1599]
### background
I started a few months ago adding range support to crystal-pg, but set it aside and only now got back to it.

[Postgres ranges](http://www.postgresql.org/docs/current/static/rangetypes.html) are more advanced than crystal. On either or both the start and end of the range you can have either exclusive or inclusive ends.

Also discrete ranges are canonicalized to inclusive start, exclusive end. This is kind of nice, but not necessary.

They also support infinite ends, but I think that might be doable with what's in crystal today now that range is (B,E) again. I haven't verified this yet though.

My spike on this a few months ago adds the ability to have the 4 different ends, which would be necessary to represent the full set of ranges from postgres.

### question
I'm not sure if this is something that we want in stdlib, or should it just be a `PG::Range` or somesuch in my library?

**Comment by will** [comment]
### example

I went through a few different prototypes. Originally with `:"[]"` or `:"(]" but settled on what follows. 

``` crystal
    (1 .. 5).includes?(1).should be_true
    (1 .. 5).includes?(5).should be_true

    (1 ... 5).includes?(1).should be_true
    (1 ... 5).includes?(5).should be_false

    Range.new(1,5,:ExEx).includes?(1).should be_false
    Range.new(1,5,:ExEx).includes?(5).should be_false

    Range.new(1,5,:ExIn).includes?(1).should be_false
    Range.new(1,5,:ExIn).includes?(5).should be_true

    Range.new(1,5,:InEx).includes?(1).should be_true
    Range.new(1,5,:InEx).includes?(5).should be_false

    Range.new(1,5,:InIn).includes?(1).should be_true
    Range.new(1,5,:InIn).includes?(5).should be_true
```

**Comment by Nakilon** [comment]
I doubt, adding the third, symbolical argument is better than `-1` or `+1.
Note: Ruby uses [`new(begin, end, exclude_end=false) → rng`](http://ruby-doc.org/core-2.2.0/Range.html#method-c-new)

**Comment by jhass** [comment]
I don't think one needs that level of complexity in practice, `PG::Range` sounds good to me.

**Comment by asterite** [comment]
I agree, this is somewhat similar to #1391 . It's better to keep `Range` simple, specially because of the use cases it has right now (like `a[0..-1]`). Should we close this?

**Comment by jhass** [comment]
If @will won't get mad over it, I'm +1 on closing :P

**Comment by will** [comment]
Oh no worries, I'm not at a computer, go ahead and close.
