### ISSUE TITLE
Improve  API docs search result tree (expanding/collapsing)

### ISSUE THREAD

**Issue by lakshgupta** [crystal-lang/crystal#1621]
While reading the API docs the state of the tree remains exact when you simply scroll up/down and click on the hyperlinks; which is fine. But when you make a search using the search bar  and click any item in the tree, it resets the page again. It would be good to be able to search for, say Int, and then read the pages for Int32/Int64 etc., without the need to search for Int again.

**Comment by wontruefree** [comment]
@lakshgupta I think this has been fixed can I close this?

**Comment by RX14** [comment]
Fixed.
