### ISSUE TITLE
Bug in Compiler: `# primitive: pointer_set` at  has no type

### ISSUE THREAD

**Issue by jreinert** [crystal-lang/crystal#1622]
see https://p.jreinert.com/YBn for trace. Was too long for issue body.

**Comment by jreinert** [comment]
i can't reproduce btw. this happend once only without changing any of the sources.

**Comment by jhass** [comment]
Until there's a reliable way to reproduce there's usually not much anyone can do about these.

**Comment by jreinert** [comment]
yeah. i thought i'd still open this issue. maybe someone can find ways to reproduce the error from the trace.

**Comment by OttoRobba** [comment]
Not sure if it is related but when using the Crystal tools in Atom, I have this error whenever I try to get the context of a function that is not used anywhere.

```ruby
def add (a, b)
    a + b
end
```

Getting the context for add results in (sorry for the image, can't copy the text apparently) 
![bug_crystal](https://cloud.githubusercontent.com/assets/597287/11948273/32645440-a859-11e5-860a-ae90650c8405.png)

**Comment by asterite** [comment]
I'm closing this. Please reopen if you can provide code that we can use to reproduce the error.
