### ISSUE TITLE
[RFC] Error on incorrect closure usage.

### ISSUE THREAD

**Issue by technorama** [crystal-lang/crystal#1626]
Closures may bind to variables that change between between calls.  Is there a valid use case?  If not make it a compiler error to use them in a loop/callable under the following conditions:
* The closure is created in a loop or invoked from a callable.
* The name is bound outside of the loop/callable.

Fails:
```
i = 1 # name is bound outside of a loop
array.each do |e|
  i += 1
  spawn { puts i.to_s } # compiler error
end
```

Ok:
```
i = 1
array.each do |e|
  i += 1
  j = i # name is bound inside of a loop
  spawn { puts j.to_s }
end
```

Ok:
```
array.each_with_index do |e, i| # name is bound inside of a loop
  spawn { puts i.to_s }
end
```

**Comment by ozra** [comment]
Assuming spawn is completely async, none of the above produces the expected result, am I missing something?

Anyway: In JS, closured vars has to be explicitly bound as copies (in a sync wrapping closure), which is no good help, but in C++11, there's a nifty way of describing whether you want a reference or a copy for the closure (lambda in C++ lingua):
(below in pseudo C++ to highlight the syntax)
```C++
void foo() {
    int i = 1; // name is bound outside of a loop
    for(auto e: array) {
      i += 1;
      // '=' -> closured are by value - will do what's expected in this case
      spawn([=]() { puts(i.toS()) });
      // '&' -> closured are reference - 'i' may have changed when the closure executes
      spawn([&]() { puts(i.toS()) });
      // instead of autmatic closuring, a list can be specified, with 'byval' being default and 'byref' chosen with '&'
      spawn([i, &e]() { puts(i.toS()); puts(e.toS()) });
    }
}
```

So something akin to the closuring-list before the lambda def in C++ would be veeery neat, if a suitable syntax could be made.

For reference:
```C++
auto foo = 47;
auto a_lambda_closure = [&foo](int some_param) { return do_stuff(some_param, foo); } -> int;
```

**Comment by ysbaddaden** [comment]
@ozra the last 2 examples are correct because blocks will run in a closure, and any variable declared in the closure will be correctly accessible. Just like in JS (i in for loop will be wrong, but forEach is unaffected).

**Comment by ozra** [comment]
@ysbaddaden - thanks for clearing that up, I must admit I'm still in a bit of denial regarding blocks - I must read up on them so I can leverage the full potential of Crystal.

**Comment by asterite** [comment]
There are many valid use cases. For example:

```crystal
# This creates a fibonacci iterator.
# a and b are closured and change.
a, b = 0, 1
iter = Iterator.of do
  a, b = b, a + b
  b
end
p iter.first(20).to_a # => [1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946]
```

You can do `spawn puts(i)` to pass a copy of the variable, as explained in the [concurrency guide]([1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946]), so I'm closing this.
