### ISSUE TITLE
enforce unsigned int return type for IO.read and write

### ISSUE THREAD

**Issue by jreinert** [crystal-lang/crystal#1643]
see also #1642

**Comment by asterite** [comment]
Unsigned integers are bug prone. I use them only for C compatibility. I'd enforce Int32 in any case (but there really isn't a way right now to enforce a return type on implementors).

**Comment by asterite** [comment]
I'm closing this for the reason above. It would be maybe nice to have a way to enforce a type to always be returned in implementors/subclasses, but that's a different issue.
