### ISSUE TITLE
Make case sensitive methods Unicode aware

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#1648]
Currently methods like `upcase`, `downcase` and the new `compare` only respect ASCII case sensitivity. We should add normalization and comparison methods respecting [Unicode equivalence](https://en.wikipedia.org/wiki/Unicode_equivalence) and other case sensitivity  related parts of the Unicode standard.

**Comment by asterite** [comment]
I think this should really go into a `Unicode` module of some sort. Imagine comparing a string or checking the presence of a string in a hash, and doing the normalization process all the time. It will slow down everything.

**Comment by bcardiff** [comment]
Couldn't we mark string as ASCII or MaybeUnicode to use optimized algorithms in each case?
Playing nice with unicode as default is a good thing IMO.

Also case insensitivity should be used only by demand, so I would expect that checking string in a hash to be CS.

**Comment by jhass** [comment]
Well UTF-8 is fully ASCII compatible and I don't believe there are any normalizations done for the codepoints betwee 128 and 255, so we could just reuse the single byte optmizable flag.

**Comment by asterite** [comment]
Ah, right, we already have a fast path for ASCII in many places, so you are right.

However, the unicode equivalence article says:

> For example, the code point U+006E (the Latin lowercase "n") followed by U+0303 (the combining tilde "◌̃") is defined by Unicode to be canonically equivalent to the single code point U+00F1 (the lowercase letter "ñ" of the Spanish alphabet).

So let's see what Ruby does: http://carc.in/#/r/he5

It considers the strings different, but they are equal for unicode. So should their `#hash` be equal? Should they be `true` when compared with `==`? And if you insert one in a Hash, should it be there when you get it using the other one?

**Comment by jhass** [comment]
I think people can understand that they're different, I'm not aware of any language that does implicit normalization, Rubyists are used to it not happening anyway. So the answer is no, they're not equal, they're different byte sequences after all. I'm asking for explicit normalization here and implicit normalization only where it makes sense like in `downcase` etc..

**Comment by jhass** [comment]
As some data point, the just released Ruby 2.4 preview does this now on the regular String methods: https://bugs.ruby-lang.org/issues/10085

**Comment by asterite** [comment]
We can do this. What's the algorithm?

**Comment by jhass** [comment]
I'm not sure, it looks like it's just based upon existing capabilities of oniguruma, so a bit hard to track down https://github.com/ruby/ruby/commit/be897c2507a9d7710f218ccf377e6ea67d6d47bf

**Comment by jhass** [comment]
https://github.com/ruby/ruby/blob/trunk/enc/unicode/case-folding.rb

**Comment by asterite** [comment]
Yeah, I think most of Ruby's unicode support comes from oniguruma... which is a regex engine... weird :-P

**Comment by dimparf** [comment]
What progress on this issue?

**Comment by asterite** [comment]
@dimparf No progress, this is super hard, and probably low priority right now. But if someone wants to tackle this, go ahead :-)
