### ISSUE TITLE
Can't pass an argument constrained by `if x.is_a?` to a matching, statically-typed parameter.

### ISSUE THREAD

**Issue by Perelandric** [crystal-lang/crystal#1692]
I don't know if this is a bug or just my lack of understanding, but I thought the `if x.is_a? Subset` would allow me to pass `x` to `def test_2(x : Subset)`. Instead I get the compile-time error noted below.

If I change `x` to be a definite `Sub1` or `Sub2` instance, it compiles.

```
class Parent
end
class Sub1 < Parent
end
class Sub2 < Parent
end

alias Subset = (Sub1 | Sub2) # In actual code, this is a subset of the sub-classes of Parent

def test_2(x : Subset)
  puts "test"
end

def test()
  x = true ? Sub1.new() : Sub2.new()

  if x.is_a? Subset
    test_2(x)
  end
end

test()
```

>Error in ./tester.cr:22: instantiating 'test()'

>test()
>^~~~

>in ./parser.cr:18: no overload matches 'test_2' with types Parent+
>Overloads are:
> \- test_2(x : Subset)

>    test_2(x)
>    ^~~~~~

---

>Crystal 0.8.0 [e363b63] (Sat Sep 19 12:00:17 UTC 2015)

**Comment by jhass** [comment]
Yes, IMO that should compile, even without the `is_a?`

**Comment by ozra** [comment]
I think the compiler infers to the nearest common parent when several types are used - not any "parallell" sumtypes / type unions. Sub1+Sub2 is inferred to their parent, and thus do not match the signature which is another type.
If x was declared as `x :: Subset` it should work.
It would be nice though if the compiler could take the target restriction in to account and see if the types fit it.

**Comment by Perelandric** [comment]
I hope it will work. This example is very simplified. In reality, there are several `ChildN` sub-classes and the variable assignment is actually coming from a  function call that may return any one of those `ChildN` objects.

Whatever object I get, I need to be able to narrow it down to one of multiple subsets. In this case, I'm actually using  a `when` instead of an `if`. I guess I could create intermediate parent-classes for each object, but if there's any overlap, I'd think that would be an issue.

**Comment by ozra** [comment]
As workarounds - try specifying "Subset" (the specific one) for the functions returning them. Or `test_2(x as Subset)`

**Comment by asterite** [comment]
Yes, this is a known issue (at least for me ;-)). Right now you'll have to do something like:

```crystal
case x
when Sub1
  test_2(x)
when Sub2
  test_2(x)
end
```

The main issue is what @ozra says: when two types are combined the compiler tries to find a common superclass. It's hard to fix but we'll eventually think of something.

**Comment by asterite** [comment]
Alternatively, define a module and include it in the types you want. Then check `.is_a?(Mod)` and use the `Mod` as a type restriction.

**Comment by Perelandric** [comment]
@ozra Thanks for the info. In this case, the function is generic and will be returning any possible child, which then needs to be sub-categorized in certain situations. I tried `as` too but it gave the same result.

@asterite Thanks much for the suggestions. I'll keep them in mind.

**Comment by asterite** [comment]
This seems to be working in 0.15.0 and above. I also remember improving a bit the type restriction handling regarding modules and aliases, so that must have fixed it.

**Comment by Perelandric** [comment]
@asterite: Thank you, looks great.

However I'd note that the `test_2` function accepts arguments that inherit from `Parent` (or `Parent` itself), which are not in the the `Subset` type defined on the parameter. It seems as though the compiler ought to be rejecting those. What do you think?

https://play.crystal-lang.org/#/r/wl8

``` crystal
class Parent
end

class Sub1 < Parent
end
class Sub2 < Parent
end

class Sub3 < Parent
end


alias Subset = (Sub1 | Sub2) # Two of the 3 subclasses


def test_2(x : Subset)
  puts "test_2 received: #{typeof(x)}"
end

def test()
  x = true ? Sub1.new() : Sub2.new() # Members of `Subset`
  test_2(x)
  
  
  y = Sub3.new() # Not a member of `Subset`.
  test_2(y) # Still allows the call.
  
  z = Parent.new() # Not a member of `Subset`.
  test_2(z) # Still allows the call.
end

test()
```

**Comment by asterite** [comment]
Oh, that's because when you do `Sub1 | Sub2` it actually resolves to `Parent`, in the same way that when you do `cond ? Sub1.new : Sub2.new` it returns something of type `Parent`. This will change in the future to remain `Sub1 | Sub2` in both cases, and only go to `Parent` if such type is assigned to a variable of type `Parent` (which can now happen because there are explicit/guessed types for instance variables). I'll reopen this issue until we change that behaviour.

**Comment by Perelandric** [comment]
Sounds good. Thanks @asterite.

**Comment by asterite** [comment]
Closing in favor of #2661
