### ISSUE TITLE
Make Nil the base type of all Crystal objects

### ISSUE THREAD

**Issue by cyril** [crystal-lang/crystal#1695]
I'm wondering if it wouldn't be a good idea to move `Nil` at the top of all Crystal objects hierarchy.
Thus, `Object` could be a subclass of `Nil`...

Thinking of that, I think it would make sense, to have nothing at the beginning.

A naive implementation could be:

```crystal
class Nil
  def nil?
    true
  end
end

def Object < Nil
  def nil?
    false
  end
end
```

I'd be curious to hear your opinion on this design.

**Comment by jhass** [comment]
Honestly, I don't get this at all.

The point of `nil` is that it actually is something. It's an object that represents the absence of another object. Contrary to the `null` concept of for example Java, which is not an object and on contrary to even primitives, doesn't have a type. So `nil` is not just a marker, it's a placeholder, a piece you put in place of something else.

**Comment by cyril** [comment]
Yes, I see.

The purpose of this issue would be to try to solve...

> The problem with object-oriented languages is they’ve got all this implicit environment that they carry around with them. You wanted a banana but what you got was a gorilla holding the banana and the entire jungle. — Joe Armstrong

...using an explicit blank class, such as a `Nil` class (of the singleton object `nil`).

Like probably some other rubists, I wonder if it'd be feasible.

**Comment by kumpelblase2** [comment]
It would pretty much destroy the advantages that we get from the current typechecking mechanism. You have to explicitly check what type it is, to make sure you're not getting a runtime exception because you somehow ended up with `nil`. If every type would be a subclass of `Nil`, you'd only really know something blew up at runtime, like it is for ruby right now and as far as I'm concerned, that is desired at all.

**Comment by lbguilherme** [comment]
It would effectively make all and every type nilable for the compiler, which means we will have to check for nils eeverywhere and will lose the compile time checking for them. This is exactly what Java does, and is kind of similar to C pointers too.

When I get a `String` as parameter I can really expect it to be a real living and usable string object, which is very nice. I fail to see the advantage or usecase of your proposal. Could you show some code example on where it would be better?

**Comment by cyril** [comment]
Supposing we need a pet class which doesn't need all Object's methods such as `#to_json`, `#to_s`, etc. One could write this piece of code inheriting from `Nil`:

```crystal
class Pet < Nil
  def initialize(name)
    @name = name
  end

  getter :name
end
```

Thus, we could create a new class with a small and well focused APIs.

Much like Ruby's `BasicObject` and Python's `object`, such nil-like root could be used for creating object hierarchies independent of Crystal's object hierarchy, proxy objects like the Delegator class, or other uses where namespace pollution from Crystal's methods and classes should be avoided.

**Comment by ozra** [comment]
Even though `Nil` has a value (`nil`), it's really more like the _bottom type_. At least it has absolutely nothing to do with being a bare bones _top type_.

Would be better in that case to introduce a specific top like `Any`, `BasicObject`, `Root` or whatever.

I guess then we'd have (some examples): `Any >> Reference >> Class >> YourClass`, `Any >> Value >> Struct >> YourStruct`, `Any >> Reference >> YourBareBonesClassish`

Mmm, or something.

**Comment by waj** [comment]
Designing a good type hierarchy is not always a trivial task but as a rule of thumb you can ask yourself if an instance of the subclass "is a" kind of the parent class (a Cat is an Animal). Only `nil` is a Nil, so making it the very base class is a really bad type hierarchy design. 

And no... we are not going to make every type nilable. We're happy with the current type system. Please check out our blog for examples of where this is actually useful.

**Comment by waj** [comment]
Nil cannot be a bottom type because there is a possible value: nil. Actually there is a bottom type in Crystal: NoReturn. 

I don't see why we need to have another type on top of Object. It has minimal memory representation if it has no fields and there isn't any overhead if you don't call the methods that it defines.

**Comment by jhass** [comment]
The use of a `BasicObject` is not about memory footprint, it's mainly about proxies, a wrapper that would delegate all method but the explicitly defined ones to another object.

**Comment by waj** [comment]
Ok, @jhass, that's a very good point (and also I think what @cyril was trying to say but I misread his comment, sorry about that). So in any case I'd either rename this RFC or open another one not involving the Nil type.

**Comment by ozra** [comment]
@waj - good catch - NoReturn it is.

I think you're right @waj - probably better to open a new issue for RFC regarding possible "BasicObject" to not confuse the issue with the moot Nil - just my 2 mBTC.

**Comment by cyril** [comment]
Actually I would call such basic object nil because nothing is more empty than itself, semantically speaking.

But anyway, whatever the name, this discussion sounds good from my rubist perspective :+1:

**Comment by nekron** [comment]
I agree with @jhass, having a BasicObject is a nice feature, that or the ability to define a class without a superclass (with that I'm not saying Nil, I'm saying nil, of course).

An object may not have a superclass, which doesn't mean that its superclass is Nil. ;-)

**Comment by asterite** [comment]
@cyril Please provide a concrete use case of this (I mean code, not just saying "for proxies or delegates").

**Comment by cyril** [comment]
Here's a concrete (and generic) use case:

Considering a `foo` object whose behavior is defined by only 2 methods, one can say that all the methods provided by `Object` are useless.

Although we can keep them, by removing these useless methods we avoid _fat objects_, which would be a great innovation in the world of object oriented language, IMO.

***

Also, I would like to reformulate the idea of the empty object. As by definition the void has no behavior, we could imagine that any object with no method is empty. And thus, given a keyword such as `nil` which could become a stuff without any method, we could then use it to make a class inherit from nothing, explicitly.

Once again, it's just an idea. And I do not know exactly but this kind of change can take several years of development, while Crystal looks already nice!

**Comment by asterite** [comment]
Other than the philosophical worry about objects being "fat", did you encounter a real issue with the 10 methods Object defines?

Second, BasicObject/nil would be a reference or a struct?

**Comment by cyril** [comment]
If I had met such issue, I would open a specific one.

As to whether it should be a reference or a struct... Honestly I don't care. It's up to you, guys.

**Comment by asterite** [comment]
I'm closing this. We could maybe add `BasicReference` and `BasicValue` in the future, but if there's no real use case for this then there's no point doing this.
