### ISSUE TITLE
Better Labeling For Issues

### ISSUE THREAD

**Issue by sdogruyol** [crystal-lang/crystal#1699]
I've been looking through the open issues and found it hard to categorize. Especially the level required for the issue is unknown from the title.

I'd really like the style of https://github.com/elixir-lang/elixir/issues which makes it really easy for starters and newcomers to pick an issue and get going.

What do you guys think?

**Comment by ozra** [comment]
I'd like to see `#shallow-know` or something (for where no deep knowledge of crystal code base is required) and an additional `#easy` tag for issues that are easy and requires little knowledge of code base (planned name refactorings, doc updates, what not).

It would make it easier for more of us to contribute and slowly building up deeper knowledge, so it's kind of grade school for becoming crystal hackers.

**Comment by bararchy** [comment]
Good ideas, but who will create the tags ? those who open the issues ? if so, how do they know what level is needed to fix it ?

**Comment by ozra** [comment]
The admins I presume, that has knowledge of the code base, and of course only when they can tell immediately that it fits the tags. It doesn't have to be foolproof, just a helpful indicator.

**Comment by multiplegeorges** [comment]
Please do this, I'd love to participate and it's not clear where to start.

**Comment by marceloboeira** [comment]
👍🏻

**Comment by jhass** [comment]
I suggested something like this in the past, @asterite's argument was that easy fixes shouldn't remain unfixed for too long just to pull in contributors. We need more opinions here from @crystal-lang/crystallers

**Comment by bcardiff** [comment]
@asterite codes too fast :-P. I would 👍  a #easy to allow tiny/easy contributions, but that won't prevent  the core team to jump and fix them. The challenge is that triage/tag them is enough time to fix them sometimes. But I think is better to gain more contributors.

**Comment by asterite** [comment]
I sometimes find missing bits in the standard library and I'm lazy to implement them. In those cases I (or anyone with something to add to the standard library, first discussing if it should be added) could create an issue, mark it as task and set the difficulty level (though that depends on each person). One example I can think of right now is `BitArray#toggle` a range of numbers. Would that help?

**Comment by jhass** [comment]
We decided to add a newcomer label to tasks which should be suitable for a first time contribution. They're not necessary easy, simple or quick to do, rather the level of controversy and scope (how many parts of the standard library and/or compiler are affected) is kept low.

**Comment by sdogruyol** [comment]
@jhass thanks a lot 👍
