### ISSUE TITLE
Spec failure: TCPSocket fails when host doesn't exist

### ISSUE THREAD

**Issue by jbaum98** [crystal-lang/crystal#1740]
Running the specs on a Macbook Pro with El Capitan I got a failure

       expected Socket::Error, got #<Errno: Error connecting to 'localhostttttt:12345': Operation timed out> with backtrace:
         # [4352311650] *CallStack::unwind:Array(Pointer(Void)) +82
         # [4352311553] *CallStack#initialize<CallStack>:Array(Pointer(Void)) +17
         # [4352311512] *CallStack::new:CallStack +40
         # [4352745265] *Exception@Exception#initialize<Errno, String>:CallStack +33
         # [4352745207] *Errno#initialize<Errno, String>:CallStack +119
         # [4352745060] *Errno::new<String>:Errno +100
         # [4364319067] *TCPSocket@Socket#nonblocking_connect<TCPSocket, String, Int32, struct.LibC::Addrinfo, Nil>:(Nil | Exception+) +331
         # [4364318169] *TCPSocket#initialize<TCPSocket, String, Int32, Nil, Nil>:Nil +937
         # [4364317206] *TCPSocket::new<String, Int32, Nil, Nil>:TCPSocket +118
         # [4364317067] *TCPSocket::new<String, Int32>:TCPSocket +27
         # [4351322344] ~fun_literal_5184 +40
         # [4349024663] *it<String, String, Int32, &( -> Void)>:(Nil | Bool | Array(Spec::Result)) +359
         # [4351317376] ~fun_literal_5180 +192
         # [4363972659] *Spec::RootContext::describe<String, String, Int32, &( -> Void)>:Spec::Context+ +195
         # [4349024131] *describe<String, String, Int32, &( -> Void)>:Spec::Context+ +51
         # [4348951247] __crystal_main +55279
         # [4349022592] main +32

     # expanded macro: expect_raises:32

**Comment by miketheman** [comment]
#triage 
Tried to repro on multiple versions of Crystal, El Capitan:
```bash
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.11.4 (15E65)
      Kernel Version: Darwin 15.4.0
...
```

I also added a PR for automated build of the latest OSX/XCode in #2595, which passes.

Recommend closure, reopen if more repro details can be provided.
