### ISSUE TITLE
Support aliases in YAML.mapping

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#1745]
http://play.crystal-lang.org/#/r/j24

**Comment by asterite** [comment]
Yes, aliases are not currently supported.

**Comment by straight-shoota** [comment]
To implement this, the parser provided to `from_yaml` needs to be context-aware like `YAML::Parser` which keeps track of anchors. So I guess the anchors list should be moved to `YAML::PullParser` or are there other suggestions?
