### ISSUE TITLE
json mapping serialize

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#1763]
How to do something like this?:

```ruby
require "json"

class A
  JSON.mapping({
    a: Int32,
    b: String,
    c: Time
  })
end

a = A.new
a.a = 1
a.b = "bla"
a.c = Time.now
p a.to_json
```

**Comment by asterite** [comment]
1. The Time field needs to specify a converter (the time format)
2. JSON.mapping defines an initialize from a JSON::PullParser, but doesn't define how a user would initialize A in other ways (mainly for nilable fields).

You can do this:

```crystal
require "json"

class A
  JSON.mapping({
    a: Int32,
    b: String,
    c: {type: Time, converter: Time::Format::ISO_8601_DATE},
  })

  def initialize
  end
end

a   = A.new
a.a = 1
a.b = "bla"
a.c = Time.now

puts a.to_json

# Ouptut:
# {"a":1,"b":"bla","c":"2015-10-17"}
```

**Comment by jhass** [comment]
Once we have keyword arguments for required arguments, generating a proper initialize would be nice.

**Comment by asterite** [comment]
@kostya Is there something else needed for this issue?

**Comment by kostya** [comment]
would be nice to have default time converter(with seconds and time zone)?

**Comment by asterite** [comment]
I'd like the conversion format to be explicit, because `Time` could also be just a date, and could come in many different formats. I don't know if there's a standard format (well, there is, but then you don't know if it's date with hour or just date)

**Comment by asterite** [comment]
I'm closing this. Please reopen with a suggestion on how to create a default `initialize` in this case (the types should probably be nilable).

**Comment by kostya** [comment]
default initializer now is :default mapping option.
