### ISSUE TITLE
Callback support

### ISSUE THREAD

**Issue by benoist** [crystal-lang/crystal#1777]
I'm trying to add callback support in a web framework, but I'm running into the following

http://carc.in/#/r/jaj

If I put the callback registration to the bottom of the file it works

http://carc.in/#/r/jak

Perhaps there could be a macro that gets compiled at the end of the file. Which could allow for the following

http://carc.in/#/r/jal

Further abstractions can be implemented outside the stdlib to fit the required DSL.

**Comment by benoist** [comment]
I did manage to create a workaround.

http://carc.in/#/r/jhi

**Comment by jhass** [comment]
Closing this, please create a concrete proposal if you want a change in the language.

**Comment by asterite** [comment]
I think this should be fixed now because types are resolved after a previous pass that declares them (I think the issue was more related to needing forward-declarations)
