### ISSUE TITLE
WebSocket receive should be blocking

### ISSUE THREAD

**Issue by jreinert** [crystal-lang/crystal#1784]
IMHO WebSocket#receive should be blocking or at least have an option for this. What do you think?

**Comment by nowucca** [comment]
I think it goes against the spirit of asynchronicity implicit in socket programming.  If you wanted to simulate a blocking receive you can always do so by waiting on a  future that completes in the non blocking receive handler.

**Comment by asterite** [comment]
@jreinert Why do you need this?

**Comment by waj** [comment]
@jreinert Can you give an example? WebSocket#receive IS blocking right now: when you invoke it, the current fiber is blocked until a message is received.

**Comment by miketheman** [comment]
#codetriage 
This is an oldie.

It doesn't appear that WebSocket#receive is meant to be called directly (anymore?), rather as part of the [WebSocket#run loop](https://github.com/crystal-lang/crystal/blob/e747c3dc218a6d718c9383ac17cff86c3c8090fa/src/http/web_socket.cr#L97).

The [implementation of #receive](https://github.com/crystal-lang/crystal/blob/e747c3dc218a6d718c9383ac17cff86c3c8090fa/src/http/web_socket/protocol.cr#L106-L116) appears to my untrained eye to block for more data.

Recommending closure, at least until the originator comes back with some more details as to the use case.
