### ISSUE TITLE
Websocket frames are fragmented

### ISSUE THREAD

**Issue by jreinert** [crystal-lang/crystal#1788]
i already opened an issue for nodejs which is the server receiving these fragmented frames but i'll open one here since I believe this fragmenting is weird and shouldn't be happening in crystal.

https://github.com/nodejs/node/issues/3445

**Comment by jreinert** [comment]
Probably not an issue with crystal but on the receiving side. Will close when confirmed.

**Comment by javajax** [comment]
I don't understand you question entirely.
I noticed this is closed in the node project for the reason that the underlying protocol allows this type of behavior.

Does that satisfy your question with the crystal project?

**Comment by jhass** [comment]
Ping.

**Comment by jreinert** [comment]
oh. hm i haven't followed this any further. Feel free to close. I'll reopen it if needed.
