### ISSUE TITLE
Permission to use Crystal logo in a presentation

### ISSUE THREAD

**Issue by kanaka** [crystal-lang/crystal#1822]
I'm going to be doing a presentation about mal (https://github.com/kanaka/mal) at midwest.io. Crystal is one of the implementations (by @rhysd) and I would like to use a Crystal logo in the presentation (e.g. this logo:https://github.com/manastech/crystal/blob/gh-pages/images/crystal-v.svg). I searched for guidelines related to use of the logos but didn't find anything obvious. Can I get permission to use the Crystal logo in my presentation (and the subsequent published video/materials from the conference)?

**Comment by jhass** [comment]
Yes, @asterite  & @waj  should publish some basic guidelines on branding usage. Maybe just a wiki page?

**Comment by asterite** [comment]
Yes, you can use them. And thank you for doing a presentation about
Crystal! :-)

A wiki page sounds good, but I have no experience in guidelines for
branding usage. Maybe we can reuse an existing guideline?

On Sun, Oct 25, 2015 at 4:43 PM, Jonne Haß <notifications@github.com> wrote:

> Yes, @asterite <https://github.com/asterite> & @waj
> <https://github.com/waj> should publish some basic guidelines on branding
> usage. Maybe just a wiki page?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/manastech/crystal/issues/1822#issuecomment-150962507>.
>



-- 
Ary Borenszweig         Manas Technology Solutions
[ar.phone]                      5258.5240       #ARY(279)
[us.phone]                      312.612.1050    #ARY(279)
[email]                         aborenszweig@manas.com.ar
[web]                           www.manas.com.ar

**Comment by kanaka** [comment]
@asterite @jhass Thanks!

FYI, since I've been doing a lot of searching for logo usage guidelines (mal has 41 implementations now), I think the guidelines I like the most are for python: https://www.python.org/community/logos/ They are clear, concise, and link to preferred image sources for people to use.

**Comment by jhass** [comment]
@asterite I think if you just write up which usages you want to allow in a fairly informal tone and a generic "All usages not explicitly granted here need explicit permission from [...]" it's fine for now. Better have *something* now and change it to something more correct later if issues arise than to delay it any longer. Maybe also consider explicitly licensing it under a CreativeCommons license.

**Comment by ozra** [comment]
I second @jhass: add a license for the graphics - Ccreative Commons ones for instance. 
- It's easy to find one that match your requirements
- They're juridically sound - no need to start writing your own license text full with legal loop holes

**Comment by miketheman** [comment]
#triage 
This seems to have ended with a single-case permission for use of the logo.
The project is currently licensed under Apache-2.0. I'm no lawyer, but maybe the logo is covered by this license already?

**Comment by sdogruyol** [comment]
@asterite i think we should put this on wiki and close this issue. WDYT?

**Comment by bcardiff** [comment]
This is now answered in https://crystal-lang.org/media/
