### ISSUE TITLE
Better udp socket support

### ISSUE THREAD

**Issue by ydnax** [crystal-lang/crystal#1858]
The current udp implementation is IO based which doesn't make much sense as udp is stateless. There is currently no way to send a package to different hosts from the same source port without closing and opening new socket objects. a udp "server" has no access to single packages and can't get the senders remote address or port.

edit: i think #1820 fixes these issues

**Comment by asterite** [comment]
#1820 did fix this issue :-)

UDPSocket is still an IO but one can also use `send` and `receive`.
