### ISSUE TITLE
File write error when stressing HTTP::Server

### ISSUE THREAD

**Issue by sdogruyol** [crystal-lang/crystal#1865]
This happened when i try to do some benchmarking. Got an unhandled exception like below:

```
Unhandled exception:
Error writing file: Protocol wrong type for socket (Errno)
[4339348904] *Errno::new<String>:Errno +392
[4339398893] *TCPSocket+@IO::FileDescriptor#unbuffered_write<TCPSocket+, Slice(UInt8)>:Int32 +861
[4339441497] *TCPSocket+@IO::Buffered#write<TCPSocket+, Slice(UInt8)>:(Nil | Int32) +329
[4339397629] ~fun_literal_29 +5741
[4339349338] ~fun_literal_4 +42
[4340001070] co_runner +43
```

Here's the sample code that i use for this case.

```crystal
require "kemal"
require "json"
require "active_record"
require "postgres_adapter"

ENV["PG_URL"] = "postgres://serdardogruyol@localhost:5432/test_db"

class MenuItem < ActiveRecord::Model
  adapter postgres

  primary(id :: Int)
  field(seq :: Int)
  field(name :: String)
end

get "/" do |env|
  env.content_type = "application/json"
  menu_items = MenuItem.all.map do |mi|
    {id: mi.id, seq: mi.seq, name: mi.name}
  end
  multiplied = menu_items * 50
  multiplied.to_json
end
```

Multiplied contains around ```12000``` objects and i stress test this endpoint with wrk like below

```
wrk -c 10 -d 10 http://localhost:3000
```

The average and max response times are great but i start to get these exceptions at the end of each benchmark.

**Comment by sdogruyol** [comment]
For later info this is pretty much OS X kernel bug. I need to test this on Linux though 

Here's a blog post with nearly the same error http://erickt.github.io/blog/2014/11/19/adventures-in-debugging-a-potential-osx-kernel-bug/

**Comment by asterite** [comment]
@sdogruyol is this a kernel bug or do we need to fix something in crystal?

**Comment by sdogruyol** [comment]
@asterite this is probably a kernel bug which is related to default `ulimit -n` in OS X. Closing!
