### ISSUE TITLE
popcount operation?

### ISSUE THREAD

**Issue by rmosolgo** [crystal-lang/crystal#1927]
Hi again, 

I'm interested in a `popcount` operation (as part of implementing a hash array mapped trie), which counts the `1` bits in an integer, eg 

```crystal 
popcount(4) #=> 1 
popcount(5) #=> 2 
popcount(6) #=> 2 
popcount(7) #=> 3
```

I couldn't find it in Crystal, so I made this very sad implementation:

```crystal
def popcount(int)
  int.to_s(2).count('1') # 😢
end
```

Is there a better way to do that with Crystal now? Or would you consider adding it to Crystal? 

I don't really understand what I'm reading, but it seems like LLVM has some built-in support for popcount: https://github.com/bcardosolopes/llvm-vpopcount

Thanks!

**Comment by jhass** [comment]
We probably could just expose the intrinsic and then add it to `struct Int`. Not sure I'd call it `popcount` though, `high_bit_count` or something might e little more explicit.

**Comment by asterite** [comment]
:+1: for this. If you want to implement it take a look at the [LLVM reference](http://llvm.org/docs/LangRef.html#llvm-ctpop-intrinsic) and the [Intrinsics lib](https://github.com/manastech/crystal/blob/master/src/intrinsics.cr). We just need to define a name for this, so checking other languages should be a good source of inspiration :-)

**Comment by rmosolgo** [comment]
Ok, thanks! I'd like to try it, maybe I can take a look this week.

**Comment by asterite** [comment]
I think I would name it `popcount`. `bitcount` sounds like the count of bits, so Int32 has 32 bits, right? And `popcount` seems somehow well-known.

I don't know if I'd use a macro for this, the method is just a call to an LLVM intrinsic.

**Comment by kirbyfan64** [comment]
`onebits`?

**Comment by jhass** [comment]
`highbits` rather then.

**Comment by Olathe** [comment]
Can you please not call it high bits? The high bit is traditionally the most-significant bit, which would mean the high bits would be the half that are most-significant.

**Comment by omninonsense** [comment]
I like @kirbyfan64's suggestion to call them `onebits` best, or keep the traditional name `popcount`&hellip; *Or* be radical with naming and call it `hamming_weight` (just kidding)!

**Comment by ysbaddaden** [comment]
Same here, let's just use popcount.

**Comment by EvanHahn** [comment]
Has this been completed? I see [`Int#popcount`](http://crystal-lang.org/api/Int.html#popcount-instance-method)...

**Comment by rmosolgo** [comment]
oops, my bad, :wave:
