### ISSUE TITLE
Strange alias types in LibC

### ISSUE THREAD

**Issue by Virviil** [crystal-lang/crystal#1937]
https://github.com/manastech/crystal/blob/0f4e5866db1d559fdb3c833e8de8a1f96ab7c957/src/libc.cr#L10

Why Char and SChar instead of UChar and Char?
From background "u" prefix means "unsigned", while "s" prefix is not obvious. For more, it's out of logical sequance of Short->UShort and so on.

For more, FFI in Ruby has :uchar and :char types.

I have a suggestion to make this aliases as UChar an Char.

**Comment by waj** [comment]
Because although not strictly specified by C standards, and opposite from numeric types, for most C compilers `char` means unsigned. I think that makes the translation of some API to Crystal more simple.

**Comment by jhass** [comment]
Explanation given and no discussion happened afterwards, closing.
