### ISSUE TITLE
Dynamic string interpolation in macros

### ISSUE THREAD

**Issue by ilatif** [crystal-lang/crystal#1942]
Is there a way I can have dynamic string interpolation kind of thing in macros. For example, [here](https://github.com/sdogruyol/kemal/blob/master/src/kemal/view.cr#L10-L14) is the code which is using `embed_ecr` macro to execute an `.ecr` file. If we pass string literal like `"hello.ecr"`, `"new.ecr"` then `embed_ecr` macro works fine but if we assign template/view name in some variable and pass that variable then `embed_ecr` uses that variable as is instead of using it's string contents.

Is there a way to achieve string interpolation kind of thing in this scenario?

**Comment by asterite** [comment]
No, because the contents of that variable are only known at compile time.

I believe that ECR won't be very useful for web frameworks that need this kind of dynamism. In those cases I'd develop a template language that's more dynamic, but obviously less powerful and a bit slower.

**Comment by asterite** [comment]
(and definitely not type-safe... well, you could get runtime exceptions, just like in other dynamic templates, like in Ruby)

**Comment by sdogruyol** [comment]
Is it possible to make `ecr` a bit more flexible (e.g yields)

**Comment by asterite** [comment]
Maybe, I think someone (maybe @ysbaddaden) has a working version of that, but I'm not sure.

**Comment by kostya** [comment]
yield with sub_templates?

1.ecr
```
<html>
<%= @sub_template.to_s %>
</html>
```

2.ecr
```
Hello World
```

test.cr
```crystal
require "ecr/macros"

record T, sub_template do
  ecr_file "1.ecr"
end

class SubT
  ecr_file "2.ecr"
end

puts T.new(SubT.new).to_s
```

```
<html>
Hello World
</html>
```

**Comment by ilatif** [comment]
@asterite: Thanks for your prompt reply. The reason you mentioned for not having string interpolation in macros is quite acceptable keeping in mind that Crystal is essentially a statically compiled language.

I looked at `embed_ecr` code and it looks like it is using `run` macro behind the scenes which is executing `ECR.process_file(ARGV[0], ARGV[1])` to process template. Is there anyone we can dynamically execute a code string just like `ECR.process_file` returns in current context. If there is some thing like that then I think `embed_ecr` can be removed completely from our code.

**Comment by sdogruyol** [comment]
@kostya we actually achieve this with a macro for `Kemal`.But this is not `yield`

```
# # Usage
# get '/' do
#   render 'hello.ecr'
# end

require "ecr/macros"

macro render(filename)
  String.build do |__view__|
    embed_ecr {{filename}}, "__view__"
  end
end
```

**Comment by sdogruyol** [comment]
Also we can embed this in a `view` like 

```
<%= render "libs/kamber-theme-dark/views/types/video.ecr" %>
```

**Comment by ilatif** [comment]
@sdogruyol: I think the example that @kostya has shown is quite identical to rendering a template within another template. No?

**Comment by sdogruyol** [comment]
@ilatif yes it is

**Comment by ilatif** [comment]
BTW, what is `record` which @kostya has used? I didn't find any documentation on that.

**Comment by f** [comment]
Hi all!

@kostya We do not have issues with subtemplating. We have problems with `yield`ing. Kemal already does subtemplating with macros as @sdogruyol said.

If we can support parameter for `render` macro in Kemal, we'd achieve this feature.

```ruby
get "/" do
  subview = "index.ecr"
  layout = "layout.ecr"
  render layout
end

get "/post" do
  subview = "post.ecr"
  layout = "layout.ecr"
  render layout
end
```

Also we can use global variables for layouts.

```
$layout = "layout.ecr"

get "/" do
  subview = "index.ecr"
  render $layout
end
```

And the content of layout would be:

```erb
<html>
  <%= render subview %>
</html>
```

**Comment by ilatif** [comment]
@f: I' am afraid that we cannot use global variables because global variables are shared among all requests and it is possible that some other route changes that global variable which might result in inconsistent rendering for some requests :-).

**Comment by ilatif** [comment]
I think we have to use some more dynamic template language just like ERB.

**Comment by kostya** [comment]
```
$layout = T.new

get "/" do
  render "index.ecr"
end

macro render(filename)
  $layout.sub_template = String.build do |__view__|
    embed_ecr {{filename}}, "__view__"
  end
  $layout.to_s
end
```

**Comment by ysbaddaden** [comment]
There is no solution that will work just like ERB (same old runtime vs compile time problem). If you need such flexibility and dynamism, you're better off implementing a logic-safe templating solution (eg: [Liquid Markup](http://liquidmarkup.org/) with [Drops](https://github.com/Shopify/liquid/wiki/Introduction-to-Drops)) that runs at runtime. I'd love that myself!

Yet, ECR merely outputs Crystal source code, so you _can_ `yield` from the ECR template, as long as `embed_ecr` is called within a method that takes a block. For example:

```erb
<!-- layout.ecr -->
<div><%= yield %></div>

<!-- view.ecr -->
hello world
```

```crystal
def render_layout(&block)
  embed_ecr "layout.ecr"
end

render_layout { embed_ecr "view.ecr" }
# => <div>hello world</div>
```

Maybe this could be improved using a `render name` macro that would check for the presence of a block and generate/call the `render_name_template` methods. Alternatively, the `render_name_template` methods can be generated from the `run` macro, and a render macro would merely dispatch to the correct method (I chose this solution myself).

**Comment by f** [comment]
Running `embed_ecr` in a `def` would break accessing the scope variables in a route in `Kemal`

My solution is actually easier and more functional I think:

```crystal
require "ecr/macros"

macro render(filename)
  String.build do |__view__|
    embed_ecr({{filename}}, "__view__")
  end
end

macro render(filename, layout)
  content = render {{filename}} # It will be accessible from layout
  render {{layout}}
end
```

And you can write your layout as

```erb
<html>
  <body>
    <%= content %>
  </body>
</html>
```

**Comment by ilatif** [comment]
@ysbaddaden: Thanks for your reply and showing example related to `yield` which was certainly helpful. I think @sdogruyol was asking about `yield` w.r.t Rails/Sinatra. Just like in Rails/Sinatra, `yield` is used as a placeholder to render current template. But since Crystal is quite different than Ruby, I think we can handle such situation by replacing `yield` with some expressive statement like `render $current_template` kind of thing in layout.

Regards

**Comment by ilatif** [comment]
@f: You said:

> The only problem with this logic is I cannot use variables as macro parameters.

The current github issue in which we are commenting is related to exactly this thing and as you seen it's not possible :-).

**Comment by jhass** [comment]
This issue has gone a bit wild, so closing. Please open a separate issue if you want a change or feature in the compiler or standard library, ideally motivated by clear usecases.

Using runtime values in macro calls is impossible and won't happen.
