### ISSUE TITLE
Complex alias with Tuple is not accepted as argument

### ISSUE THREAD

**Issue by aladagemre** [crystal-lang/crystal#1961]
When I try to create a complex type called Pair

Code:

    alias Data = Int32 | String | Int64
    alias Pair = Tuple(Data, Data)

    def test(a : Pair)
        puts a
    end
    
    test({"a", "b"})

Result:

    Error in Line 8: no overload matches 'test' with types {String, String}
    Overloads are:
     - test(a : Pair)

Although {"a", "b"} is the same type as Pair, the argument is seen as {String, String} but not Pair. The same thing does not happen with Hash.

Tuple: https://carc.in/#/r/okb
Hash: https://carc.in/#/r/okc

**Comment by asterite** [comment]
I guess this should work, because it's at least inconsistent with how it works without an alias.

```crystal
alias T = {Int32 | String | Float64}

def foo(x : {Int32 | String | Float64})
end

def bar(x : T)
end

foo({1}) # works
bar({1}) # doesn't work
```

**Comment by aladagemre** [comment]
Yes, like you said, foo method works but bar method doesn't work. It's still present in 0.13.0.

**Comment by asterite** [comment]
This works in 0.17.3 because we improved this in tuples.
