### ISSUE TITLE
HTTP::Handler::Deflate doesn't send cookies

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/crystal#1986]
The Deflate HTTP handler creates a whole new HTTP::Response object, but there is no way to actually access the cookies, and those are only injected into the headers when calling `to_io`. Since this is never called on the original HTTP::Response object, the Deflate handler always skips any cookie that has been set.

There are 2 ways to fix that: either changing HTTP::Deflate to dup the whole HTTP::Response, or use or change HTTP::Response#cookies to udpate the Set-Cookie header immediately, whenever we set a cookie.

**Comment by asterite** [comment]
Can we maybe make `HTTP::Response` be mutable, so the deflate handler would modify it's body/body_io and headers?

**Comment by ysbaddaden** [comment]
I did that in Frost (see [here](https://github.com/ysbaddaden/frost/blob/master/src/support/core_ext/http/response.cr) and [here](https://github.com/ysbaddaden/frost/blob/master/src/server/handlers/deflate_handler.cr#L13). Being a handler, no code is expected to change the response object... unless its a websockets, maybe, and you write to `response.body_io` but it was changed to be a deflate of the original body_io? i'm not sure, I didn't play with websockets in Crystal, yet.

Still, I'm wondering if manipulating cookies in requests and responses shouldn't update the headers immediately.

**Comment by asterite** [comment]
Hm, I don't know why the Set-Cookie header is [deleted](https://github.com/manastech/crystal/blob/master/src/http/cookie.cr#L132) when getting the cookies. Isn't that wrong? (same for the other branch).

Another alternative is to tie cookies with request/response, but I'm not sure that's good (complicates things).

In any case, I think the HTTP modules needs a redesign, there are many things to improve and fix.

**Comment by asterite** [comment]
@ysbaddaden I think this predates the whole HTTP server redesign. Can you confirm that this is fixed now?

**Comment by ysbaddaden** [comment]
Let's close.
