### ISSUE TITLE
HTTP::Request multipart/form-data handling

### ISSUE THREAD

**Issue by sdogruyol** [crystal-lang/crystal#1989]
Currently we don't handle multipart forms and need to implement this for dealing with file uploads.

I'll try to do this according to Rack implementation https://github.com/rack/rack/tree/028438ffffd95ce1f6197d38c04fa5ea6a034a85/lib/rack/multipart

What do you think?

**Comment by sdogruyol** [comment]
I checked a lot of implementations and i think that this should be handled outside of `std`. I'm going to create a `shard` soon.

**Comment by RX14** [comment]
I would tend to disagree, if the standard library has room for websockets, it surely has room for multipart/form-data, which is arguably more fundamental to the web.

**Comment by RX14** [comment]
Will be fixed by #2967, once complete.

**Comment by sdogruyol** [comment]
This is living in a shard (https://github.com/RX14/multipart.cr) now thanks to @RX14 👍
