### ISSUE TITLE
is_a?(Class) misses runtime check

### ISSUE THREAD

**Issue by Exilor** [crystal-lang/crystal#2014]
https://play.crystal-lang.org/#/r/ptj

After the case statement ```my_type``` is ```(Nil | String | Foo:Class)```.
I expected the if/elsif/else to print "nil" instead of "class", given that ```my_type``` is nil and that ```nil.is_a?(Class) # => false```.

**Comment by bcardiff** [comment]
https://play.crystal-lang.org/#/r/ptw

Since some of the union elements might be a class, then the `my_type.is_a?(Class)` seems to return true.

**Comment by jhass** [comment]
I'd say this is a compiler bug, while it should consider the branch possible as far as any resulting unions are concerned, it shouldn't decide at compile time to always take it.

**Comment by Veedrac** [comment]
This doesn't seem to be a problem on Crystal 0.12 and up.

**Comment by asterite** [comment]
@Veedrac Indeed! Thanks, I'm closing this :-)
