### ISSUE TITLE
typeof() in block parameter

### ISSUE THREAD

**Issue by stugol** [crystal-lang/crystal#2032]
I'm trying to make a function accept a block parameter with a signature determined by the type of the arguments passed to the function.

How can I make the code at https://play.crystal-lang.org/#/r/q5v compile?

**Comment by asterite** [comment]
There's no way to do that right now

**Comment by sdogruyol** [comment]
@asterite will it be possible?

**Comment by asterite** [comment]
I don't know, `typeof(args)` is a tuple, you'd have to splat that somehow in the type definition.

If you can find a use case for this, we might be able to implement it, but it'll be really low priority.

**Comment by stugol** [comment]
In which case, is there a way to do this instead?
```
spawn(1, 2, 3) do |a, b, c|
  puts a, b, c
end
```
I don't want to abstract the block into a function, but can't think of another way to avoid variable collisions. Consider the following code:
```
server = TCPServer.new bind_address, port
begin
	loop {
		conn = server.accept
		spawn do				# connection fiber
			[do something with conn]
		end
	}
ensure
	server.close
end
```
When the second connection comes in, ```conn``` will be overwritten, which presumably will break the code dealing with the first connection?

**Comment by asterite** [comment]
You need to abstract the block into a function, and you can use the `spawn` macro which accepts a call. [We do this in HTTP::Server](https://github.com/manastech/crystal/blob/master/src/http/server/server.cr#L129).

**Comment by stugol** [comment]
Don't you think there is a use case for a version of ```spawn``` that passes arguments to its block, though?

Would it be hard to implement?

**Comment by jhass** [comment]
Please open a clear proposal, ideally motivated with usecases, if you want a feature in the language or standard library, closing this for now.
