### ISSUE TITLE
Convert Enumerable(T) to Slice(T)?

### ISSUE THREAD

**Issue by stugol** [crystal-lang/crystal#2037]
What is the idiomatic way to produce a `Slice(T)` from an `Enumerable(T)`? (Alternatively, the best way to clear a `Slice(T)` and then copy the values from an `Enumerable(T)` to it.)

**Comment by asterite** [comment]
The idiomatic way is to use `Array` and `Enumerable#to_a`. `Slice` is closer to being low-level.

If you need a Slice, you can do:

```crystal
enumerable = 1..10
ary = enumerable.to_a
slice = Slice.new(ary.to_unsafe, ary.size)
```

**Comment by stugol** [comment]
Isn't that a little inefficient though? You're creating a new array and copying the elements into it; then you're creating a slice and copying them into that.

Unless the slice simply indexes into the array, without copying?

**Comment by asterite** [comment]
How would you implement it? You can't know the size of the enumerable in advance. Well, you could ask it first, the allocate a Slice and assign to it, but you'll be iterating the enumerable twice (in the general case). So yes, that's another thing you can do, but it could be slower than the above answer.

**Comment by bcardiff** [comment]
The slice is a continuous portion of memory. An Enumerable is not required to be even stored in memory, since it could be generated on the fly. So you need to dump the enumerable in order to have a slice, unless, instead of any enumerable you have other kind of data structure.

**Comment by stugol** [comment]
Yes, but does the slice actually copy the array, in your example, or merely index into it? Are we performing one copy, or two?

**Comment by asterite** [comment]
The Slice is built from the array's buffer's pointer and it's size, no memory is allocated: http://crystal-lang.org/api/Slice.html#new%28pointer%3APointer%28T%29%2Csize%3AInt%29-class-method

**Comment by stugol** [comment]
So...a slice is essentially a pointer with bounds checking?

**Comment by asterite** [comment]
@stugol Exactly

**Comment by gavinmcgimpsey** [comment]
Just triaging – can this be closed?

**Comment by asterite** [comment]
I'm closing this as https://github.com/crystal-lang/crystal/issues/2037#issuecomment-173290181 is the way to do it, but it's not very useful (array should be used instead).
