### ISSUE TITLE
Crystal Tool Format can't handle annotated blocks

### ISSUE THREAD

**Issue by sdogruyol** [crystal-lang/crystal#2038]
Here's the source https://github.com/sdogruyol/cryload/blob/aafe763079367ce0de1d7a820ab352c0626dd00d/src/cryload/stats.cr

And i think this causes the bug.

```crystal
REQUESTS.map(&.time_taken as Float64).min
```

**Comment by asterite** [comment]
Thanks for reporting.

I don't know whether to fix the formatter for this case, or disallow this in the syntax. It's kind of confusing to read.

**Comment by sdogruyol** [comment]
I didn't do this on purpose. Dunno why but the compiler can't infer the return type of this blocks!

**Comment by asterite** [comment]
I mean, you can also write it like this:

```crystal
REQUESTS.map { |x| x.time_taken as Float64 }.min
```

These casts won't be needed once we require some more type annotations.

**Comment by sdogruyol** [comment]
I also don't prefer that ugly syntax but I think i got the reason.

```crystal
Signal::INT.trap {
  Cryload::Logger.log_final
  exit
}

Cryload::Cli.new
```

This tries to setup the trap before the actual execution that's why the compiler can't infer the types :cry: 

I'm OK to have more annotations to make compiler smarter :+1:

**Comment by kirbyfan64** [comment]
...am I the only person here who doesn't mind the syntax?
