### ISSUE TITLE
Request: labelled tuples

### ISSUE THREAD

**Issue by stugol** [crystal-lang/crystal#2042]
In Ruby, you can use a `Hash` to store labelled values of different types:
```
person = {
   name: "Fred Pillockson",
   age: 7,
   status: :dead
}
puts person[:name] + " is " + person[:status]
```
In Crystal, we must use a Tuple instead:
```
person = {"Fred Pillockson", 7, :dead}
puts person[0] + " is " + person[2]
```
This is barely readable, and makes it difficult to spot errors. So I tried to implement a macro to generate an anonymous class:
```
macro declare_anon_struct(name, fields)
	class %theclass
		attr_reader {{fields.keys}}
		def initialize
			{% for f in fields %}
				@{{f.key}} :: {{f.value}}
			{% end %}
		end
	end
        {{name.id}} = %theclass.new
end
declare_anon_struct person, {name: String, age: Int, status: Symbol}
```
But it simply cannot be done. For starters, it won't compile unless I add `*` before `fields` in the macro signature - I have no idea why. Secondly, and more importantly, it is not permitted to declare a `class` inside a `def`, so this macro simply cannot be used, period!

So what we need is language support for a labelled tuple:
```
person = Tuple.new(name: String, age: Int, status: Symbol)
puts person.name
```
We also need support for nested classes, IMO.

**Comment by stugol** [comment]
Hmm... Would `struct` help me here?

**Comment by rmosolgo** [comment]
That's what I was thinking, something like this: https://carc.in/#/r/q80

Probably would want some `nil?` checks on the inputs for a "real-life" use case

**Comment by asterite** [comment]
We already have this, it's the [record macro](http://crystal-lang.org/api/toplevel.html#record%28name%2C%2Aproperties%29-macro). But you must use it outside a def.

**Comment by stugol** [comment]
Unfortunately, I kinda need to use it _inside_ a def. I also want it to be anonymous, like in my example.

Also, the record macro doesn't seem to have any support for type annotation.

**Comment by jhass** [comment]
I believe the new `NamedTuple`s fulfill this usecase.
