### ISSUE TITLE
'undefined local variable or method' when using typeof()

### ISSUE THREAD

**Issue by stugol** [crystal-lang/crystal#2052]
The following code works:

``` cr
def _Type
    Int32
end
def test(&callback : typeof(_Type)->)
end
test do |a|
end
```

However, when the code is inside a class, we get an error. See https://play.crystal-lang.org/#/r/qdc

**Comment by asterite** [comment]
Yes, that should probably work

**Comment by ayazhafiz** [comment]
Interestingly, this works if `_Type` is explicitly called from the object:
``` crystal
class TCPBase
  def _Type
    Int32
  end
  
  def test(&callback : typeof(self._Type) -> Nil)
  end
end
TCPBase.new.test { |a| } # compiles
```

My inclination is that this has to do with the scope of the arguments to `typeof`, though I can't deduce much from the source code and may be totally wrong.
