### ISSUE TITLE
Error accepting socket: Socket operation on non-socket (Errno)

### ISSUE THREAD

**Issue by stugol** [crystal-lang/crystal#2055]
I have the following code:
```cr
server = TCPServer.new bind_address, port
begin
	loop { spawn_connection_fiber(server.accept) }
ensure
	server.close
end
```
I also have the following function:
```cr
def stop!
	if svr = @server; svr.close; end
	@server = nil
end
```
Upon calling `stop!`, I get either "Error accepting socket: Socket operation on non-socket (Errno)" or "Error accepting socket: Bad file descriptor (Errno)". However, given that `server.accept` is a blocking call, there is literally _no way_ to interrupt the accept loop and prevent it from trying to accept connections from the now defunct socket.

How can I solve this?

Additionally, in the absence of a usable `IO.select` call, there seems to be no way to determine if data is available on a socket without calling the blocking `read` method. This is a problem.

**Comment by asterite** [comment]
We'll need more info to solve this, and a way to reproduce it. Otherwise I'll close this in a few days.
