### ISSUE TITLE
raise error in parent process if execve in Process.run fails

### ISSUE THREAD

**Issue by stugol** [crystal-lang/crystal#2088]
The code at line 132 in `run.cr` ignores the return code of `LibC.execvp`. If I call `Process.run` with a non-existent executable filename, no error is raised.

**Comment by stugol** [comment]
I've tried to fix this - for example, using a pipe to pass the error to the main process - and have achieved precisely nothing.

**Comment by straight-shoota** [comment]
I'm not entirely sure what this issue refers to, but I might be fixed by #6501

**Comment by ysbaddaden** [comment]
Yes, fixed.
