### ISSUE TITLE
Allow to call methods on heredoc literals like Ruby does 

### ISSUE THREAD

**Issue by stugol** [crystal-lang/crystal#2089]
A heredoc in Ruby can be used like this:
```cr 
puts <<-END.downcase
SOME TEXT
END
```
A heredoc in Crystal cannot. This should be changed.

**Comment by asterite** [comment]
Wow, I didn't know you could do that in Ruby.

You can also do this:

```crystal
puts(<<-END
SOME TEXT
END
.downcase)
```

to get the same effect, so I don't think it's worth implementing that Ruby feature. Let's keep the language simple.

**Comment by stugol** [comment]
Except that it won't work if you omit the redundant line break after `END`.

@asterite thanks for closing this perfectly reasonable request without discussion or explanation.

**Comment by kirbyfan64** [comment]
It's...it's one line break...why the big deal?

**Comment by stugol** [comment]
The whole point of a heredoc is to _avoid_ having to wrap it all in parens and split calls over lines. If you're going to do that, just remove heredocs from the language completely, and use `%{ ... }` instead.

Heredocs are useful. They provide a clear and uncluttered way to embed arbitrary paragraphs of text into a code file; but it becomes far less useful when you have to wrap it in parens and line breaks.

**Comment by DmitryBochkarev** [comment]
+1 for stugol
i have code in ruby something like this :)

```ruby
items = Item.find_by_sql(<<SQL, item_id)
   select * from items where id = ?
SQL
```

**Comment by lbguilherme** [comment]
Ruby also allows pretty complex expressions using more than one heredoc on the same line:

```ruby
puts <<-TITLE.downcase + "Name: #{<<-NAME}"
	Something
TITLE
	John Doe
NAME
```

And my favorite Ruby Quine, doesn't work on Crystal:

```ruby
puts <<2*2,2
puts <<2*2,2
2
```

I don't know how hard it is to parse, given that it doesn't quite work like a string expression that has a start, a middle content and a terminator. But it is indeed useful for using heredocs into any non trivial expression. Putting chained method calls after the heredoc terminator makes reading harder if the heredoc is not very small.

**Comment by veelenga** [comment]
-1 As for me, this is not readable at all. The only thing i have seen in production code is something like this:

```ruby
p <<-END_SQL.gsub(/\s+/, " ").strip
SELECT * FROM     users
         ORDER BY users.id DESC
END_SQL
# >> "SELECT * FROM users ORDER BY users.id DESC"
```

which is well handled by current Crystal's implementation.

**Comment by david50407** [comment]
We can write the ruby code:

```ruby
puts <<-HERE.gsub /[aeiou]/, "*"
apple
banana
HERE
```

Into Crystal like this:

```crystal
puts (<<-HERE
apple
banana
HERE
).gsub /[aeiou]/, "*"
```

Or: 

```crystal
tmp = <<-HERE
apple
banana
HERE
puts tmp.gsub /[aeiou]/, "*"
```

I want to keep my code pretty, but the first case is too ugly.
And also keep my code clean and simple that I don't want to create the tmp var in the second case.

**Comment by zackperdue** [comment]
> +1 for stugol
> i have code in ruby something like this :)
> 
> ```ruby
> items = Item.find_by_sql(<<-SQL, item_id)
>    select * from items where id = ?
> SQL
> ```

🤯
