### ISSUE TITLE
Cannot compile Crystal on 32-bit

### ISSUE THREAD

**Issue by stugol** [crystal-lang/crystal#2099]
It would appear that Crystal cannot be compiled on a 32-bit system. Which is odd, seeing as a 32-bit Crystal exists in the repo.

```
> make
<inline asm>:2:15: error: register %rdi is only available in 64-bit mode
        pushq %rdi
              ^~~~
<inline asm>:3:15: error: register %rbx is only available in 64-bit mode
        pushq %rbx
              ^~~~
<inline asm>:4:15: error: register %rbp is only available in 64-bit mode
        pushq %rbp
              ^~~~
<inline asm>:5:15: error: register %r12 is only available in 64-bit mode
        pushq %r12
```
(etc)

**Comment by waj** [comment]
It's probably not detecting your CPU correctly. Can you post the output of `uname -a`? Is it a VM or a real 32 bit hardware?

**Comment by stugol** [comment]
Hm, that's odd. `uname -a` prints `Linux 84e180add30e 4.2.2-1-pve #1 SMP Mon Oct 5 18:23:31 CEST 2015 x86_64 GNU/Linux`. I'm using the "32bit/debian:jessie" docker image.

Is the docker image just garbage, do you think?

**Comment by waterlink** [comment]
Linux containers have all one small problem - they will use the same Linux kernel that the host have. So the container itself and it's processes and libraries will be in 386 mode, but `uname` will report host's kernel, which in your case is probably x86_64.

So here is the question: maybe Crystal can rely on something else to detect mode? 

What does the `arch` command returns from the inside of container?

**Comment by jhass** [comment]
As a workaround you can change among other things what `uname` reports by invoking the compiler through the `linux32` command, which is a shortcut for the `setarch` command.

**Comment by stugol** [comment]
```
# arch
x86_64
```
```
# linux32
# arch
i686
# uname -a
Linux c522937b6b17 4.2.2-1-pve #1 SMP Mon Oct 5 18:23:31 CEST 2015 i686 GNU/Linux
#
```
Looks like that might be a decent solution.

Is it Crystal's job to detect architecture correctly inside a docker container? Or is it the user's job to run it inside a `linux32` shell?

**Comment by stugol** [comment]
Will Linux32 simulate a 32-bit system even inside a normal 64-bit linux OS? By which I mean, can I use that to compile a Crystal program into a 32-bit executable on a 64-bit system; or do I _need_ to run a 32-bit docker image?

**Comment by bcardiff** [comment]
@stugol , you want to build your own crystal for 32-bits or you need to run something in the docker image?

If you only need to run in the 32-bits image, you can use the compiler in other machine with a cross compile process: http://crystal-lang.org/docs/syntax_and_semantics/cross-compilation.html

As for the responsibilty of `linux32`, I would say is on behalf the user.

**Comment by stugol** [comment]
I want to use Crystal to compile my code into a 32-bit executable, that I can then run on other systems without having Crystal installed. I'm using the docker image as a build environment.

So I should run a cross-compile process on the 64-bit system, then copy the `.o` file to the 32-bit environment and run `cc` there to produce the executable? Alternatively, build Crystal in the 32-bit environment and do the entire compilation there. Is there a reason to pick one over the other?

I guess it's better to only need to keep Crystal current in one environment, rather than two.

**Comment by kirbyfan64** [comment]
Just install a Ubuntu VM into VirtualBox or something.

**Comment by stugol** [comment]
Yes, that's what I'm doing now ;)

**Comment by ysbaddaden** [comment]
@jhass `linux32` did the trick. I just built a 32 bits binary in a LXC container!

**Comment by stugol** [comment]
linux32 won't help on a 64-bit system though. Only in a 32-bit docker image.

**Comment by jhass** [comment]
We can't link a 32bit binary if the 32bit versions of the necessary libraries aren't available. `linux32` and a chroot provides the easiest way to do this, but I expect `linux32` with proper `LD_LIBRARY_PATH` setup to 32bit versions of the libraries to work as well. Nothing to be done from Crystal's side here.
