### ISSUE TITLE
Really weird bug: proc not being called

### ISSUE THREAD

**Issue by stugol** [crystal-lang/crystal#2120]
Please consider the code [here](https://play.crystal-lang.org/#/r/rqe). If run on a real computer, rather than the online repl, it runs but we get strange behaviour. **_The callback is never called, even though we are calling it!!_**

If, however, we move the `raise FileNotFoundException` command (on line 25) to _above_ the pipes (line 22), the callback gets called without any problems.

Also, if the dummy call on line 88 is removed, the problem does not occur.

I don't understand what is going on. I've tried to provide the smallest possible test code, by removing things until the problem goes away.

Feel free to change the `deluser` command to any other command that you can guarantee will output text on stderr. The original command I was trying to use when I noticed this bug was a call to `./configure` - which, needless to say, outputted errors.

**Comment by stugol** [comment]
Any movement on this issue?

**Comment by ysbaddaden** [comment]
You're using Fiber which is internal API in Crystal. Don't use it or be prepared to have unexpected behavior, just like you have.

You should also use `Process.new` or `Process.run` instead or reimplementing your own.

**Comment by stugol** [comment]
......!? You are _NOT_ serious!

I thought fibers _worked?_ Isn't that what I was told to use, rather than threads? I distinctly remember being _told_ to use `spawn`.

You're _seriously_ telling me I'm not supposed to use fibers? Seriously? So I can't use operating system threads, and I can't use Crystal fibers.....so what _can_ I use? You're basically telling me that I get one linear thread of execution and no concurrency of any sort. What use is that?

If threads don't work in Crystal, and fibers don't work in Crystal, then I'm sorry but Crystal is useless. Period.

Again, yes, I know Crystal is free and nobody owes me anything. But c'mon guys! I've spent considerable time learning Crystal and reporting bugs to you - if concurrency is broken, this time and effort is completely wasted. You can't get anything worthwhile done without concurrency. How am I supposed to read from or write to a stream? `IO.select` is broken, so my only options are [a] blocking IO or [b] fibers.

Someone please tell me @ysbaddaden is wrong.

And I _am_ using `Process.run`. Did you not spot it?

**Comment by stugol** [comment]
Besides, what kind of response to a helpful bug report is "don't use it"? Why bother reporting them then?

**Comment by asterite** [comment]
Could you try to reduce the code? It's long and involves many IOs, system calls and other things. If there's a bug with the code generated by the compiler, or in the standard library, you should try to isolate it and report only that. For example, replace `does_command_exist?` with just `true` and see if the error happens. If it does, remove that method call and put `true` instead. Rinse and repeat until the bug disappears, and then we'll have a better clue of why it happens.

**Comment by jhass** [comment]
Needs separate report with minimal code, closing for now.
