### ISSUE TITLE
Can Instance variables from generic classes be inherited? 

### ISSUE THREAD

**Issue by luislavena** [crystal-lang/crystal#2128]
Hello,

I found that automatic initialization of instance variables on classes and inherited classes works as expected:

```crystal
class Result
  @errors = [] of String
end

a = Result.new
pp a.@errors # => []


class OtherResult < Result
end

b = OtherResult.new
pp b.@errors # => []
```

This also works when dealing with a generic class, as expected:

```crystal
class GenericResult(T)
  @errors = [] of String
end

c = GenericResult(Int32).new
pp c.@errors # => []


class Specific
end

d = GenericResult(Specific).new
pp d.@errors # => []
```

However seems to fail the moment the generic class is used as parent of a new specialized class:

```crystal
class SpecificResult < GenericResult(Specific)
end

e = SpecificResult.new
pp e.@errors # ERROR: doesn't have an instance var named '@errors'
```

I was hoping this scenario be consistent with the general inheritance, but perhaps is a limitation?

Thank you in advance for your time :heart: :heart: :heart:

**Comment by asterite** [comment]
This should work. We'll need to redesign how types are represented because right now generic inheritance is kind of a mess internally.

As a workaround you can set `@errors = [] of String` inside an initialize.

**Comment by luislavena** [comment]
Thank you @asterite, that is precisely the approach I'm taking to workaround the issue.

Saw #846 might be similar, but wasn't 100% sure.

Cheers.

**Comment by luislavena** [comment]
Thank you @asterite!!!  😘

**Comment by ozra** [comment]
:+1: @asterite codes fast as an asteroid! :-)
