### ISSUE TITLE
if x.is_a(Proc(...)) not working as expected

### ISSUE THREAD

**Issue by stugol** [crystal-lang/crystal#2131]
Please consider the code [here](https://play.crystal-lang.org/#/r/ruw).

Why is the compiler complaining about line 6, given that `ka` can only be of types `Proc(Tuple(ActionResult, String?))` and `Proc(String, Tuple(ActionResult, String?))`, the former of which has already been excluded by the `if` at this point?

From [the documentation](http://crystal-lang.org/docs/syntax_and_semantics/if_varis_a.html):
> in the **else** branch the type of the variable is guaranteed to not be restricted by that type

**Comment by kirbyfan64** [comment]
This is because the `ka.call` is in another proc. Theoretically, anything could happen to the variable between when the proc is created and when it's called. See https://play.crystal-lang.org/#/r/rv9

Workaround: https://play.crystal-lang.org/#/r/rv8

**Comment by stugol** [comment]
Hm. I'm not happy about using a proxy function. What about creating a temporary variable? Sadly, [that crashes the compiler](https://play.crystal-lang.org/#/r/rva) at the moment though.

**Comment by jhass** [comment]
Please open clear separate issues for bugs you find. The question seems answered.
