### ISSUE TITLE
Error when using a local variable defined in the same statement (Was: Why not calling `a=` in a class instance but creating a new variable?)

### ISSUE THREAD

**Issue by david50407** [crystal-lang/crystal#2142]
```cr
class Foo
  property a
  def initialize
    @a = 1
  end
  def bar
    a = a + 1
  end
end

f = Foo.new
f.bar #=> 2
f.a #=> 1
```

It creates a new local variable `a` in the `bar` method while the assignment, so `f.a` isn't changed.
Code: https://github.com/manastech/crystal/blob/master/src/compiler/crystal/syntax/parser.cr#L292

I know this can be avoid by changing `a = a + 1` to `self.a = a + 1`, but why we create a new variable instead of calling `a=` method?

And running the code below:
```cr
class Foo
  property a
  def initialize
    @a = 1
  end
  def bar
    a += 1
  end
end

Foo.new.bar #=> Syntax error in eval:21: '+=' before definition of 'a'
```

If `a += b` is rewritten as `a = a + b`, it should be the same act as the first example, right?
(https://github.com/manastech/crystal/blob/master/src/compiler/crystal/syntax/parser.cr#L329)
But it didn't create a new variable `a` and call the `a` method to get current value of `@a`, just throw a exception that `a` isn't defined.

**Comment by david50407** [comment]
```
class Foo
  property a
  def initialize
    @a = 1
  end
  def bar
    a=(a + 1)
  end
end

f = Foo.new
f.bar #=> 2
f.a #=> 1
```

And `a=` is not calling the method `a=` but creating a new local variable.
The only way to call `a=` is using `self.a=` (or `[any instance].a=`)

**Comment by asterite** [comment]
Yes, this is normal behaviour. `a = ...` is always a local variable assignment, never a method call. To invoke the method on self use `self.a = ...`.

However, I think the parser should give an error on `a = a + 1` since the variable `a` is being defined right there and currently the parser makes the second `a` be a method invocation (`a()`). I'll fix this.

**Comment by asterite** [comment]
Moved to a bug because I think this should be fixed (Ruby gives an error too, it makes the second `a` be a variable, in Crystal we can give an error saying "used before declared" or similar)
