### ISSUE TITLE
Document recommended approach for require statements and project structure

### ISSUE THREAD

**Issue by Fusion** [crystal-lang/crystal#2151]
Hi, me again with something seemingly incomprehensible that you will no doubt easily explain away(!)

Silly example: two files, `PackUnpackDefs.cr` and `Pacj.cr` (names are intentional)

Pacj.cr content:

```
class Sorei
  include PackUnpackDefs

  def pack(format_str)
    each_index do |source_idx|
    end
  end
end
```

Trying to build will yield:

`Error in ./src/crystal-pack/Pacj.cr:2: undefined constant PackUnpackDefs`

Now, rename `Pacj.cr` to `Pacl.cr`, so that its name now comes alphabetically after `PackUnPackDefs.cr`

I can now build!

Weird limitation?

**Comment by jhass** [comment]
you probably have a `require "./something/*"` somewhere, which loads the files in filesystem order, which just happens to appear alphabetical on your system. 

Crystal makes no demands on the correlation of filenames and constants they may or may not define whatsoever, there's no autoloading system at all. `require` reads files and those may define some constants. 

So to resolve your issue properly declare the dependency on the file level, `Pacl.cr` depends on `PackUnpackDefs.cr`, so it should do a `require "./PackUnpackDefs" at the top.

**Comment by Fusion** [comment]
I see. So, it appears that I should have posted this @ stackoverflow. Sorry about that.

I simply used `crystal build ` and it generates a top-level file starting with this line:

    require "./crystal-pack/*"

So, in effect, a good practice would be for me to either remove this line or put my helpers classes in sub-sub directories and only leave under crystal-pack/ files that do not have same-level dependencies?

**Comment by Fusion** [comment]
Side note: would it be possible to add to the documentation that Crystal does not support forward declarations?

**Comment by ysbaddaden** [comment]
Loading a batch of file isn't a bad practice, it just happens that sometimes one of the loaded file has a dependency on another file that must be loaded before, so its better to specifically require it.

**Comment by jhass** [comment]
Simply add the explicit requires as needed, don't invent silly folder structures.

**Comment by Fusion** [comment]
Jonne, they are not necessarily silly. In fact, quite often a module can be broken down in files contained in a directory named after that module ( cf. Crystal's source code ;) )

Anyway, I was merely pointing out that the proper approach ought to be exposed in Crystal's documentation. Newbies like me are easily startled!

**Comment by jhass** [comment]
To be honest we probably didn't really settle on a "proper" approach yet. Personally I don't do any `*` requires at all in my projects, but merely require what's needed in each file.

**Comment by asterite** [comment]
I think the solution is: if you get an error about an unknown type, add a require. Is there anything concrete we need to do?

**Comment by Fusion** [comment]
I, of course, learnt that lesson and have since been explicitly including actual file names rather than wildcard.

Nothing more to do other than maybe document that 'gotcha'

**Comment by monouser7dig** [comment]
>> To be honest we probably didn't really settle on a "proper" approach yet. Personally I don't do any * requires at all in my projects, but merely require what's needed in each file.

I think I ran into the same issue, when doing `crystal init lib foo` the `foo/src/foor.cr` contains
```cr
require "./foo/*"
```

so it may not actually uncommon for new people to run into that issue 

I would have definitely appreciated some `workflow` recommendations more than just how to crystal init, but also how to structure a crystal project so maybe when some "proper" way is defined this will be low hanging fruit 

(I am not sure I actually had that exact issue but chances are)

**Comment by asterite** [comment]
I think StackOverflow and eternal questions and answers on the internet solves this issue. If someone runs into this they will find this and have a solution.

There's simply no way to document everything. For example Ruby has no official documentation of the language :-O

(and if we someday have time to do this, we'll do it)

**Comment by monouser7dig** [comment]
What I wanted to say is, that the default should probably be changed if it leads to errors easily (the default require with the *)

Some more examples next to the method documentations could maybe be added over time, node has this figured out quite nicely IMO 

Stackoverflow will probably be the biggest help in some time when there are more people (beginners) using it, right
