### ISSUE TITLE
Request: terse proc#call syntax

### ISSUE THREAD

**Issue by stugol** [crystal-lang/crystal#2162]
Please implement the Ruby-style syntax for calling a proc:
```
fn = ->(name : String){ puts "Hello" + name }
fn.("Fred")
```

**Comment by MakeNowJust** [comment]
Cool :+1: I implemented it just now #2163

**Comment by stugol** [comment]
@MakeNowJust Awesome, thanks. Hopefully @asterite doesn't disapprove and take it out again...

**Comment by ysbaddaden** [comment]
Why is `x.()`, which _requires_ parens, any better than `x.call`?

This is an (obscure) alias for `.call` and it requires a bunch of code to maintain. It must have a _real_ benefit to consider a merge.

**Comment by ozra** [comment]
Why not let it be called like a normal method? I've implemented it as so in Onyx and I've found no problems with it yet. Anything I've missed?

**Comment by asterite** [comment]
Like @ysbaddaden , I don't see the benefit of `x.()` other than users having to learn a new syntax, the parser and the formatter having to understand that syntax, etc.

And the problem with making `foo(...)` invoke `foo` if it's a proc is that when the parser finds `foo(...)` it means it's a method call to `foo`. It never checks whether `foo` is a variable first.

I think procs are used much less than in Ruby and other languages, specially because we have blocks (well, Ruby too, but Ruby is more dynamic), so I don't think having to type `.call` instead of `.(...)` from time to time is a big deal.

**Comment by kirbyfan64** [comment]
I'm personally kind of -1 on this. I mean, I see the benefit, but I've rarely ever had to use procs, and `x.()` looks really weird.

**Comment by stugol** [comment]
Do none of you ever cringe when you have to add `call` to a proc? It's inelegant.

It *should* work as @ozra said. But if that's too much like hard work, the Ruby syntax is better than nothing.

**Comment by rmosolgo** [comment]
> Do none of you ever cringe when you have to add `call` to a proc?

Not me, coming from Ruby, it's just an object that responds to methods, that's ok with me!

**Comment by asterite** [comment]
It's only discouraged in one of the most popular Ruby style guides: https://github.com/bbatsov/ruby-style-guide#proc-call:

> Prefer proc.call() over proc[] or proc.() for both lambdas and procs.

**Comment by MakeNowJust** [comment]
By the way, I have a question: why do you talk only about `Proc`? This syntax effects all objects having `#call` method.

I think this sentence has no meaning.

> I think procs are used much less than in Ruby and other languages, specially because we have blocks (well, Ruby too, but Ruby is more dynamic), so I don't think having to type .call instead of .(...) from time to time is a big deal.

For instance, [egison-ruby] used this syntax and it worked well. If ruby didn't have this syntax, it might be rather ugly. Especilly, Ruby can define `ConstantName` method, but Crystal cannot. So, the number of situations this syntax is useful in Crystal  is more than Ruby's.

[egison-ruby]: https://github.com/egison/egison-ruby

**Comment by stugol** [comment]
A proc should be callable using normal function syntax, ideally.
```
a = ->(n:Int){ n+1 }
puts a(2)
```

**Comment by asterite** [comment]
I'm closing this. `call` is more explicit, works well, and is also recommended in Ruby (`.()` is discouraged).
