### ISSUE TITLE
Random for Range of Float

### ISSUE THREAD

**Issue by AlexWayfer** [crystal-lang/crystal#2166]
Hi!
I need some thing, that were used in Ruby: `rand(3.0..7.0)`
This gives random `Float64` (not `Int32`) in specific Range.
Do I can try to implement it for stdlib?
And what about `3.0...7.0`? `Random#rand` gives random `Float64` between 0 and 1 including 1 or not?
Thanks.

**Comment by asterite** [comment]
Sure! Sounds something useful to have in the standard library. I guess `..` vs. `...` should be taken into account.

**Comment by AlexWayfer** [comment]
But I don't know: `next_u32 * (1.0/4294967295.0)` (from `next_float`) can return 1.0? I think, yes, because UInt32 has `MAX = 4294967295_u32`...
And what about `3.0...7.0` then? I must write `next_u32 * (1.0/4294967296.0)`, right?

**Comment by ozra** [comment]
Good shit! Use TheRandType.MAX -so that if reconfs Rand for u64 or whatever it still works :)

**Comment by AlexWayfer** [comment]
Okay, @ozra, thanks! I'll try to implement it soon.
And... If I want to change `next_float` method to `next_u32 * (1.0/UInt32::MAX)`, for example, I need to do another PR?

**Comment by AlexWayfer** [comment]
[rand](https://github.com/manastech/crystal/blob/90eaec10cef83941628409cf4e064acaba140fdb/src/random.cr#L75) (see [next_float](https://github.com/manastech/crystal/blob/90eaec10cef83941628409cf4e064acaba140fdb/src/random.cr#L63)) returning Float64 in `0..1.0` (including `1.0`, because `4294967295 == UInt32::MAX`)
[rand(max : Int)](https://github.com/manastech/crystal/blob/90eaec10cef83941628409cf4e064acaba140fdb/src/random.cr#L85) returning Int32 in `0...max` (excluding `max`, because `next_u32 % max` never equal `max`)
Which `rand(max : Float)` I must implement: excluding `max` or including?
Or may be `rand(max : Int)` needed for fix?

**Comment by asterite** [comment]
I think `rand(max : Float)` should return a value less than `max`. I just tried it in Ruby and it always returns an integer, very strange, maybe a bug, maybe intentional.

**Comment by AlexWayfer** [comment]
Yep, `rand(max)` in Ruby returning only Integer. `rand(range)` can return Float. But I think, `rand(max : Float)` which returning Float in Crystal - it's good.
Thanks, @asterite

**Comment by AlexWayfer** [comment]
@asterite 
`rand(max : Int) : Int32`

> Returns a random `Int32` which is greater than 0 and less than *max*.

but...
`(next_u32 % max).to_i32`
can return 0, can't it?

**Comment by asterite** [comment]
Yes, [but it's surrounded with a check](https://github.com/crystal-lang/crystal/blob/master/src/random.cr#L86-L90).

**Comment by AlexWayfer** [comment]
@asterite Yes, but **returns** not greater than 0, but greater or equal 0.

I read Ruby-docs, it's right:

> When max is a Float, rand returns a random floating point number between 0.0 and max, including 0.0 and excluding max.

But then error in code-comment (before method), I suppose :)

**Comment by asterite** [comment]
You are right, the docs are wrong. It should say "greater than or equal to 0, and less than max".
