### ISSUE TITLE
External library conflict with stdlib implementation

### ISSUE THREAD

**Issue by plukevdh** [crystal-lang/crystal#2168]
A couple of questions posed by this dummy lib:

https://github.com/plukevdh/crystal-lib-conflicts

The [openssl.cr](https://github.com/datanoise/openssl.cr) lib provides a more up-to-date OpenSSL library than the current stdlib implementation, but in doing so, it causes conflicts with some stdlib OpenSSL constants. I am trying to use `require "http/request"` and can't find where it pulls in `openssl`, but either way, when I include both it and a reference to `openssl.cr`, I get the following: 

```
Error in /usr/local/Cellar/crystal-lang/0.12.0/src/openssl/lib_crypto.cr:28: already initialized constant LibCrypto::PKCS5_SALT_LEN

  PKCS5_SALT_LEN     =  8
  ^~~~~~~~~~~~~~
```

The project linked above gives an executable example demonstrating the issue. Is there any way to "replace" a stdlib library with an external lib without causing a conflict like this?

**Comment by ozra** [comment]
This is a thing I've stumbled upon from another perspective before:
Methods can be monkey patched and overridden. But not constants!

There shouldn't really be n artificial limitation to not allow monkey patch overriding of constants.

(Which would solve above mentioned problem then)

**Comment by bcardiff** [comment]
What would be better?

a) undefine a constant
b) rename a constant
c) stub a file

option c) is maybe is the safest way to avoid issues around indirect dependencies. If you stub the file at the very beginning you will be all set.

but it is too drastic maybe.

option b) will allow you to reuse explicitly the old code (similar to alias_method_chain).

option a and b) have the drawback of not dealing with indirect dependencies that could reference later the method.

But maybe some internals had changed and some ordering issues do not matter now (?) cc: @asterite

**Comment by asterite** [comment]
I think redefining constants should be possible. Not sure it would be a good idea, though.

**Comment by kirbyfan64** [comment]
What if it's made possible to redefine lib constants IF both definitions have the same value?

**Comment by bcardiff** [comment]
Maybe we can define a `@[Override]` just for libs now that will throw away current definition of the lib explicitly. And we don't mess right now with *any constant*

**Comment by plukevdh** [comment]
I like the idea of explicit override as it at least indicates potential danger. Ruby allows you to override with a warning message which isn't as desirable. I do like the idea of errors as the default behavior, I just wish we could also have a way around when it causes a failure where we are explicitly deviating from the norm.

**Comment by plukevdh** [comment]
Ultimately, this isn't an issue if we aren't defining multiple identical versions of things that already exist in stdlib, but on occasion, I'm sure people will still want to build things against C libs in different ways that might conflict.

**Comment by ozra** [comment]
The reason I was thinking about is that currently you can use a 3rd party-lib, monkey patch methods you want different, but you can't monkey patch a constant that might be a path, lucky number or whatever that don't suit your use.

The reason to redefine a constant is the same as redefining a method imo, well almost then.

Of course the rational path to take is mod the lib to use a variable instead of the offending constant and PR, but... just a thought.

**Comment by jhass** [comment]
Anyone wants to write a proposal out of this issue so we can close this one? Or should we just close it?

Issues like these with no clear proposal just stall and pollute the issue tracker.

**Comment by asterite** [comment]
Let's close this. Instead of forking openssl, which is defined in the standard library, send PRs against openssl. We just have to find someone who can take care of it. I personally don't know much about OpenSSL, and I know @waj doesn't either, but we'll eventually improve this.
