### ISSUE TITLE
%s bug in macros

### ISSUE THREAD

**Issue by stugol** [crystal-lang/crystal#2178]
This [code](https://play.crystal-lang.org/#/r/slf) exhibits odd behaviour. It creates a temporary variable for `%s` for no apparent reason:
```
macro requires(command)
  puts "Require command %s." % {{command}}
  {{ debug() }}
end
requires "crystal"
```

**Comment by bcardiff** [comment]
As a workaround:

```crystal
macro requires(command)
  puts {{"Require command %s."}} % {{command}}
end
requires "crystal"
```
https://play.crystal-lang.org/#/r/w8o

**Comment by stugol** [comment]
Or, y'know....fix it. Just sayin' ;)
