### ISSUE TITLE
Nil exception when accessing $~

### ISSUE THREAD

**Issue by stugol** [crystal-lang/crystal#2194]
The following code throws a Nil exception on the second line:
```
puts [""].any? &.=~(//)
puts $~
```

**Comment by ysbaddaden** [comment]
`$~` and other `$1` magic variables are local variables and thus only valid for the duration of the block. The variables also will raise when nil, in order to not have to deal with nils whenever everytime we access `$1` or `$2`.

**Comment by stugol** [comment]
I see. The block-local characteristic is a bit awkward when trying to do this:
```
value = $~[1] if values.any? { |v| v =~ /^ID=(.*)$/ }
```
I hoped to use this line as an elegant and terse way to pull the ID value from a document, matching it line-by-line. I have since rewritten it due to this limitation, but it's sad that the original way doesn't work.

**Comment by waterlink** [comment]
@stugol It sounds like you want something like this: https://carc.in/#/r/sql ?

**Comment by waterlink** [comment]
Or even terser: https://carc.in/#/r/sqn

**Comment by waterlink** [comment]
Ah, you actually want to get the matched group. Here you go: https://carc.in/#/r/sqt

**Comment by stugol** [comment]
Yeah, I know I can use `map` and `compact`. It's not as elegant though.

**Comment by asterite** [comment]
I think the first snippet should work, the magic variables are method local, not block local.

**Comment by stugol** [comment]
Should this work?
```
value = $~[1] if values.any? { |v| v =~ /^ID=(.*)$/ }
```

**Comment by waterlink** [comment]
Doesn't look like it is block-scoped: https://carc.in/#/r/src

**Comment by waterlink** [comment]
This is the closest I can get: https://carc.in/#/r/srg

**Comment by asterite** [comment]
Now all snippets work as expected \o/
