### ISSUE TITLE
Another compiler crash

### ISSUE THREAD

**Issue by stugol** [crystal-lang/crystal#2196]
[This](https://play.crystal-lang.org/#/r/sqd) code crashes the compiler.

**Comment by Perelandric** [comment]
*Posting data provided from the link, so that the information is available to people searching for similar issues.*

```
enum ActionResult; Success; end
def test(ka, arg)
  if ka.is_a?(Proc(Tuple(ActionResult, String?)))
    ka
  else
    ka2 = ka
    ->(){ ka2.call(arg) }
  end
end

test ->() { {ActionResult::Success, "" as String?} }, nil
test ->(arg : String) { {ActionResult::Success, "" as String?} }, "blah"
```


> **Error output**
> 
> Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/manastech/crystal/issues
> 
> **Output**
> 
> Bug: `ka2` at  has no type
> [135843038] ???
> [137585190] ???
> [139222719] ???
> [139356340] ???
> [139347145] ???
> [139386236] ???
> [139279968] ???
> [139129508] ???
> [139114291] ???
> [138163330] ???
> [142311345] ???
> [142289144] main +23992
> [3072713879] __libc_start_main +247
> [135841378] ???

**Comment by javajax** [comment]
I am just trying to understand the code.
What type did you expect `ka2` to be?

**Comment by asterite** [comment]
Reduced:

```crystal
ka = 1
unless ka.is_a?(Int32)
  ka2 = ka
  ->{ ka2 }
end
```

**Comment by asterite** [comment]
@javajax It ends up with no type, that's probably the reason for the crash.
