### ISSUE TITLE
Compiler error message

### ISSUE THREAD

**Issue by jmoriau** [crystal-lang/crystal#2210]
Today I made a silly mistake:

```ruby
class TestException < Exception
	def initialize
	  raise "test"	# <== Here I stupidly typed `raise` instead of `super`
  	end
end
```

But as you can see: https://carc.in/#/r/sxm
The error message is super cryptic, took me a few minutes to find out what happened :smile: 
Is this normal ?

**Comment by asterite** [comment]
I don't know if it can be improved. You are extending Exception and in it's constructor invoking `raise`, which creates an Exception. So it basically turns nilable every instance variable that must be initialized in Exception... or put another way, breaking the Exception class, a fundamental one, so there isn't a nice error message that we could show.

**Comment by jmoriau** [comment]
Just thought I'd mention it, maybe it could at least mention the file with the error :smile: ?

**Comment by asterite** [comment]
Now the compiler will give you this error:

```
Error in ./foo.cr:2: this 'initialize' doesn't initialize instance variable '@callstack' of Exception, with TestException < Exception, rendering it nilable

  def initialize
      ^~~~~~~~~~
```
