### ISSUE TITLE
Move Matrix to the crystal-lang organization?

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#2221]
I don't feel it belongs in the standard library, mostly because I believe a project like [mverzilli/crystalla](https://github.com/mverzilli/crystalla) would be much more useful and efficient in the long run.

So we can either:
* move it to the organization, though I don't know who would use it, if there would be an alternative blas/lapack implementation in the future, and I woudln't want to have non-recommended projects in the organization
* move it to another place, though somebody would have to take care of it (maybe you would like to take care of it, @Exilor ?)
* delete it

The same thing applies to [html_builder](https://github.com/crystal-lang/html_builder), I don't feel it's a good-enough project to have in the organization.

**Comment by Exilor** [comment]
If a better implementation is on the way you can nuke it, I won't be offended :wink:

**Comment by asterite** [comment]
I actually like the current implementation. The problem is that blas/lapack exist for a long time now and they are super optimized, so we better reuse that code in some way.

However, matrix feels too math oriented, and will probably not be used by most projects, only those that need to do complex math stuff. That's why I believe it doesn't belong in the standard library. If we extract it somewhere else users can choose to use it if it fits their use case, or choose crystalla if they need more performance (but will have to link against blas/lapack).

@Exilor If you are OK with it, you can create a shard for matrix inside your github account, and then I'll delete the code from crystal.

**Comment by Exilor** [comment]
I've never done anything with shards before but I'll give it a go.

**Comment by ysbaddaden** [comment]
Either run `crystal init matrix` for a full blown library structure, or create a directory, put source files under `src`, then run `crystal deps init` to generate a `shard.yml` ready to be customized :)

**Comment by Exilor** [comment]
@ysbaddaden Like this? https://github.com/Exilor/matrix

**Comment by waterlink** [comment]
@Exilor looks good. Don't forget to add an open source license file and provide usage instructions in readme. 

Without the first one, nobody legally is allowed to use this code.

Without the second one, nobody will know how to use it. 

Additionally would be nice to setup Travis: `language: crystal` in `.travis.yml` should be enough. And enable this repository on travis-ci.org

**Comment by ysbaddaden** [comment]
Yes, it looks good. As said above a LICENSE file and a license: entry in shard would be great. A short introduction with a few examples in README would be nice too. You may add a link to docrystal for more documentation.

**Comment by Exilor** [comment]
I think this issue can now be closed. Thank you all for your tips, really helpful.
