### ISSUE TITLE
How create a new array based on a given pointer?

### ISSUE THREAD

**Issue by greyblake** [crystal-lang/crystal#2222]
I have an pointer `Pointer(Float64)` that points to some already allocated memory.
I want to create an array of given size using this pointer, e.g.:

```crystal
Array(Float64).new(pointer, 10)
```

As far as I can see it is not possible currently.
I can open pull request with updates in Array class, if you are OK with this?

Thanks)

**Comment by asterite** [comment]
The main issue with this is that if the array grows, it will call `realloc` on the pointer. If the pointer came from, say, a C library, that will crash the program. So one would have to be very careful when using this.

Where did you get that pointer from? In some cases you can use [Array.build](http://crystal-lang.org/api/Array.html#build%28capacity%3AInt%2C%26block%29-class-method) to avoid extra memory allocations.

**Comment by greyblake** [comment]
Ah, yea, I see what you mean. As far as I see `build` does not allow to say to array "use existing memory". 
I allocate memory myself, so there are plenty other solutions for the task I am trying to solve.
However what I wanted to do is: allocate a big array, and then based on its memory create small arrays that I can use and access the memory without calculating indexes each time.

**Comment by asterite** [comment]
If the array you are going to use isn't resizable, just indexable, and you want to create subranges of it, [Slice](http://crystal-lang.org/api/Slice.html) is probably the best type for the job.

Otherwise, we would either need an `ArrayView` or somehow have read-only `Array`s, but it's not very simple.

**Comment by greyblake** [comment]
Majose! Tio estas ekzakte, kion mi bezonas! Koran dankon, samideano!:)

**Comment by asterite** [comment]
Bonege! Mi timis ke vi eble bezonus Array-n kaj la alian aferon
