### ISSUE TITLE
What's the official docs sources' LICENSE?

### ISSUE THREAD

**Issue by ethe** [crystal-lang/crystal#2227]
Hi, I want to translate ofiicial docs into Chinesse (in fact I have been doing this for several days look [Crystal-docs-zhCN](https://github.com/ethe/Crystal-docs-zhCN)). But I didn't see the  docs sources' LICENSE yet, should I attach a LICENSE file on it? What's official's suggestion?

**Comment by jhass** [comment]
Yes, we probably should explicitly set one. Maybe just CC0 it?

**Comment by ethe** [comment]
@jhass I think that's a good idea.

**Comment by asterite** [comment]
Got this on triage. Can't it be assumed that the docs are also Apache 2?

Or, mmm... do we even need a license? Docs translations are nothing but welcome.

**Comment by jhass** [comment]
Not it can't "be assumed", it needs to be somewhat obviously declared. While putting them under Apache 2 would probably work, I would still suggest a CreativeCommons license and be it the CC0 "do whatever you want with them" type. Simple commit a `LICENSE` file to the `_gitbook` folder in the `gh-pages` branches and it should be all good.

**Comment by asterite** [comment]
@jhass could you do that please? :-) CC0 sounds good to me.
