### ISSUE TITLE
`from_json` with block returning EOF

### ISSUE THREAD

**Issue by plukevdh** [crystal-lang/crystal#2236]
See the following example:

```crystal
require "json"

test = [
  {one: 1},
  {one: 2},
  {one: 3},
].to_json

class Demo
  JSON.mapping({one: Int32})
  property! rawr
end

res = Array(Demo).from_json(test) do |ob|
  ob.rawr = "test"
end
```

At the end of this execution, `res` == `EOF`

https://play.crystal-lang.org/#/r/t82

Would expect it to return the new array rather than an `EOF` symbol.

**Comment by asterite** [comment]
@plukevdh It doesn't return an Array on purpose, to avoid allocating memory for it. I just added some docs. Use the block-less version and then iterate the Array elements.
