### ISSUE TITLE
Add compilation options

### ISSUE THREAD

**Issue by waghanza** [crystal-lang/crystal#2244]
Hi,

I'm try to build an crystal library https://github.com/datanoise/mongo.cr.

I have compilation trouble => https://github.com/datanoise/mongo.cr/issues/7

I've found that adding an options will fix my issue.

How can I do that with the `crystal`, **0.12** compiler ?

Regards,

**Comment by jhass** [comment]
`crystal build --link-flags "-shared" ..." should do it.

**Comment by ysbaddaden** [comment]
I'm wondering why you need to specify it, thought. Maybe your system has a CC variable or alias with `-static`?

**Comment by waghanza** [comment]
that a good question, I'm new in compiled language

**Comment by waghanza** [comment]
In fact it's not a matter of flags but a GCC version problem
with **GCC** `4.9` compils but not with **GCC** `5.3`

**Comment by jhass** [comment]
Crystal libraries are used in source and installed into your Crystal project via the shards tool. You don't invoke `crystal build` on them to install them or anything like that, they're compiled as you compile your project using them.

**Comment by waghanza** [comment]
no, in fact I mean that I try to use https://github.com/datanoise/mongo.cr (via **`shards`**) but I can't.

on `ubuntu`, `debian` I can since I have **GCC** `4.9`
but on `fedora` I can't since I have a *GG `5.3` compilation error ;-)

PS : I have the same problem for other `crystal` libraries

**Comment by jhass** [comment]
Then I don't follow why you want to specify a linker flag when installing some source files into your project. You would specify it when building your project.

**Comment by waghanza** [comment]
it was a wrong idea, I admit
