### ISSUE TITLE
Unexpected behavior of `protected`

### ISSUE THREAD

**Issue by waterlink** [crystal-lang/crystal#2251]
Maybe it is just me, but I have found this unexpected: https://carc.in/#/r/tff

```crystal
module X
  class A
    protected def hello
      "world"
    end
  end

  class B
    def a_hello
      A.new.hello
    end
  end

  pp B.new.a_hello
end
```

My expectation is that `protected` allows the call between instances (or descendants) of the same class.

Here, it allows the call inside of a module.

Was it a decision to change meaning of `protected` like this? Or is that a bug?

PS: I don't have anything against this behavior, and, most probably, I like it more.

**Comment by ozra** [comment]
For private it could be ok, but protected?
Futher, perhaps there should be `public`, `commune`, `private`, `public`. Hmm, a little overkill I guess.

**Comment by luislavena** [comment]
@waterlink would you mind putting the code inside the issue? I'm not sure how long the short URLs `carc.in` live for. Thank you.

**Comment by asterite** [comment]
@waterlink It's correct (Crystal) behaviour. I need to update [the docs](http://crystal-lang.org/docs/syntax_and_semantics/visibility.html).

It's #1743, and it was introduced in 0.9.

Do you think it's a good/bad idea?

**Comment by waterlink** [comment]
@asterite 

> PS: I don't have anything against this behavior, and, most probably, I like it more.

"I like it more". So, it is good behavior.

**Comment by waterlink** [comment]
> @waterlink would you mind putting the code inside the issue? I'm not sure how long the short URLs carc.in live for. Thank you.

@luislavena Done.

**Comment by waterlink** [comment]
I'm closing the issue, since it looks resolved.
