### ISSUE TITLE
allocation of very large block when I run crystal build

### ISSUE THREAD

**Issue by chenkovsky** [crystal-lang/crystal#2257]
I want to port docopt to crystal.
I run crystal build to compile my file.
compiler gives me some warnings:

GC Warning: Repeated allocation of very large block (appr. size 134221824):
	May lead to memory leak and poor performance.

the attachment is my program.

[docopt.txt](https://github.com/crystal-lang/crystal/files/153987/docopt.txt)

**Comment by chenkovsky** [comment]
my crystal version is Crystal 0.11.1, i install it on mac via brew.

**Comment by chenkovsky** [comment]
look at line 240 of this attachment. if I comment it, file is compiled correctly. otherwise, GC complains.

[docopt.txt](https://github.com/crystal-lang/crystal/files/154722/docopt.txt)

**Comment by asterite** [comment]
@chenkovsky Thanks, I was able to reduce it to this:

```crystal
class Bar
  def initialize(@value)
  end

  def value
    @value
  end
end

foo = [Bar.new(nil).value]
Bar.new(foo)
```

If you try to infer the type of Bar@value, you will end up in an endless loop:

```
Bar@vaule: Nil 
foo: Array(Bar)
Bar@value: Nil | Array(Bar)
foo : Array(Nil | Array(Bar))
Bar@value: Array(Bar) | Array(Nil | Array(Bar))
etc.
```

If a generic type grows too much (100 nestings) we are raising an error, but in this case the generic type has unions inside it and so it also grows horizontally, so reaching 100 is hard without reaching out of memory. I guess I'll reduce the limit to 15, which is something like `Array(Array(Array(Array(Array(Array(Array(Array(Array(Array(Array(Array(Array(Array(Array(Array(...)))))))))))))))`, which is probably impossible to happen in a real program.

As for the solution, you have some `[match._value]` that trigger this problem (the next version will point it out for you). You need to specify the type of the array to fix this, something like `[match._value] of T` (I don't know what's T in your case).
