### ISSUE TITLE
Minor problem converting from BigInt to u64

### ISSUE THREAD

**Issue by dkhofer** [crystal-lang/crystal#2264]
This is fairly obscure, not super high priority, but hopefully easy to fix.

The following code raises the exception given:

`require "big_int"`
`x = BigInt.new(1.to_u64 << 63)`
`raise "problem" if x != x.to_u64`

Should BigInt.to_u64 maybe call libgmp's get_ui instead of indirectly calling get_si (via to_i64)?

**Comment by asterite** [comment]
Good catch, thanks! (and thanks for hinting the solution)

**Comment by dkhofer** [comment]
Sweet, thanks for the quick response!
