### ISSUE TITLE
Does initialize arguments should match between parent and subclasses?

### ISSUE THREAD

**Issue by umurgdk** [crystal-lang/crystal#2271]
I have a strange compile issue with generic classes which extends an abstract generic base class. My generic base class don't have any initialize method defined. But when i try to create an instance from it compiler says: 

```
Error in ./samples/simple_parser.cr:6: wrong number of arguments for 'Parsec::Many(Char)#new' (1 for 0)

many_char = Parsec::Many(Char).new(any_char)
```

here my **abstract base class**
```crystal
abstract class Parsec::Parser(T)
    getter error_message

    @is_satisfied  = false
    @is_failed     = false
    @cargo         = ""

    @error_message = ""

    def satisfied?
        @is_satisfied
    end

    def failed?
        @is_failed
    end

    protected def reset
        @is_satisfied = false
        @is_failed    = false
        @cargo        = ""
    end

    protected def success
        @is_satisfied = true
    end

    protected def fail
        @is_failed = true
    end

    abstract def produce : T
    abstract def step(char : Char)
end
```

And here **subclass**:
```crystal
class Parsec::Many(T) < Parsec::Parser(Array(T))
    def intialize(@parser : Parsec::Parser(T))
        @error_message = "At least one #{parser.error_message}"
        @parsed_count = 0
        @products = [] of T
    end

    def step(char : Char)
        if @parser.failed? && @parsed_count == 0
            fail
        elsif @parser.failed?
            success
        elsif @parser.satisfied?
            @products << @parser.produce
            @parser.reset
        end

        @cargo += char
    end

    def produce : Array(T)
        @products
    end
end
```

```
crystal version: Crystal 0.12.0 (Tue Feb 16 15:18:18 UTC 2016) (also tested with master branch)
OS: OSX 10.11.2 (15C50)
```

**Comment by asterite** [comment]
I plan to fix this soon, maybe today, but making the compiler say:

```
No overload matches...

You have a `intialize` method, do you maybe have a typo?
```

**Comment by jhass** [comment]
I suggested about the same on IRC, so that would be awesome.

**Comment by umurgdk** [comment]
That would be awesome :+1:

**Comment by asterite** [comment]
In the next version that error you would get is this:

```
Error in ./foo.cr:115: wrong number of arguments for 'Parsec::Many(Char)#initialize' (given 1, expected 0)
Overloads are:
 - Parsec::Parser(T)#initialize()

many_char = Parsec::Many(Char).new(any_char)
                               ^~~

in ./foo.cr:65: do you maybe have a typo in this 'intialize' method?

  def intialize(@parser : Parsec::Parser(T))
      ^~~~~~~~~
```

:-)

**Comment by bcardiff** [comment]
Hey @umurgdk are you porting Haskell's parsec package?

**Comment by umurgdk** [comment]
@asterite wohoooo :tada: 
@bcardiff yes writing a parser combinator trying to achive same semantics with haskell's parsec. you can look at https://github.com/umurgdk/crystal-multipart src/parsec directory. I will create its own package when I get basic stuff working :)

**Comment by bcardiff** [comment]
Awesome :heart: 

Just some basic things I saw around.

* Something like Maybe you would prefer to be a Struct rather than a class. It will have less overhead in performance. But actually in crystal you already have `Maybe(T)`. It is just `T | Nil`. If you block how to translate something just comment or PM. Probably you just want to match Haskell as much as possible, but I just needed to point it out just in case. 
* If you want to [build a String char by char](https://github.com/umurgdk/crystal-multipart/blob/master/src/parsec/char_parser.cr#L7), use [StringBuilder](http://crystal-lang.org/api/String/Builder.html)
* There are a bunch of .swp files around.

**Comment by umurgdk** [comment]
@bcardiff thanks for comments, yeah just noticed .swp files -.- struct is a good idea. but when i have T | Nil then i have to use not_nil! it feels unsafe. Or there is a better way to handle?

StringBuilder! Noted :) I will deal with performance a bit later

**Comment by bcardiff** [comment]
Maybe(T) | T?
-------|------
`expr.is_a?(Maybe::Just(T))` | `expr.is_a?(T)`
`Maybe.just(expr)` | `expr`
`expr.from_maybe` | `expr`
`Maybe(T).nothing` | `nil`

You can see [Object#try](http://crystal-lang.org/api/Object.html#try%28%26block%29-instance-method) and [Nil#try](http://crystal-lang.org/api/Nil.html#try%28%26block%29-instance-method) somehow as `:: (a -> b) -> (Maybe a) -> (Maybe b)`

`not_nil!` will cause a runtime exception, if you know what to do in and `#try` is not enough, you can use [case/when](https://play.crystal-lang.org/#/r/tns)

**Comment by umurgdk** [comment]
@bcardiff oh try trick make sense. thanks :)
