### ISSUE TITLE
Add a method: when Nil yield block passed / when Object noop

### ISSUE THREAD

**Issue by MaloJaffre** [crystal-lang/crystal#2272]
This will allow to do this:
```crystal
obj = nillable_get #=> Object?
p obj.or "error"
p obj.or do
  #fallback
end
```
I will submit a PR soon, but I need to do specs and docs before.

**Comment by bcardiff** [comment]
That applies to any object not only strings.

**you can already do that**

`str.if_nil_replace_by! "error"`
would be
`str || "error"`

Crystal make the math for with expression the type is :-)
`||` even has [short circuit evaluation](https://en.wikipedia.org/wiki/Short-circuit_evaluation) so it works on the scenarios where you would want a block for lazy evaluation.

If you built your own function for fallback values, you would need to support a block alternative for lazy evaluation.

Something like,

```crystal
struct Nil
  def or(fallback)
    fallback
  end

  def or
    yield
  end
end

class Object
  def or(fallback)
    self
  end

  def or(&block)
    self
  end
end
```

**Comment by MaloJaffre** [comment]
Thanks for the review!
I updated the description.

**Comment by bcardiff** [comment]
I don't see a need for another way to do this. We already have the `||` alternative that cover all the scenarios. Together with `begin/end` you can build a multi statement fallback code.

```crystal
s = nil || begin
  puts "fallback"
  a = 1 + 1
  a
end

pp s
```

**Comment by MaloJaffre** [comment]
Ok, i didn't know that we can pass a statement to ```||```.
Sorry for the inconvenience caused.

**Comment by bcardiff** [comment]
No inconvenience at all! :smile_cat: 

Maybe we are in lack of a nillable suggestions in the docs for these common patterns. Maybe even including #2271.

**Comment by jhass** [comment]
As a style advice, if your fallback needs more than one line of code, it probably is better extracted into a method anyway.

**Comment by asterite** [comment]
There's plenty of info here: http://crystal-lang.org/api/Nil.html

**Comment by waterlink** [comment]
Additional case for having such method: 

```
false || "fallback" # => "fallback"
false.not_nil_or "fallback" # => false
```

**Comment by bcardiff** [comment]
Ah, yes, I forgot about the `false`... 
@asterite are we missing some other idiomatic way of doing it or we should consider adding it to the std?

suggested names for the method: fallback, otherwise, if_nil, default. 
I would not use `or` since is ambiguous w.r.t. `||`

**Comment by asterite** [comment]
It's just:

```crystal
obj.is_a?(Nil) ? value1 : value2
```

I don't think `Bool | T` is a common type. Maybe `Bool | Nil` might happen, but it's not that frequent. I don't think we need a method for this.
