### ISSUE TITLE
Embedding Crystal into a C/C++ program

### ISSUE THREAD

**Issue by define-private-public** [crystal-lang/crystal#2278]
I was wondering how feasible it would be to embed Crystal into a C/C++ program to have it act as a scripting language.  Is this possible?

**Comment by kumpelblase2** [comment]
Well, crystal is getting compiled, just like your c/c++ code, so having it as a "scripting" language doesn't really work.

**Comment by jhass** [comment]
See http://stackoverflow.com/questions/32916684/can-a-crystal-library-be-statically-linked-to-from-c

In general StackOverflow is a great place for such questions ;)
