### ISSUE TITLE
Proc -> NoReturn with controlled recursion

### ISSUE THREAD

**Issue by umurgdk** [crystal-lang/crystal#2284]
Hi im working on a parser combinator library and i have small issues with proc return types. To be able to handle recursion for parsers i have to make it lazy, to be able to do it I have a ParserClosure class which accepts a proc to be ran when it is needed. You can see see the codes below.

In case of you want to see all the codes please check https://github.com/umurgdk/haydari

```
Error in ./samples/parser_new.cr:677: no overload matches 'ParserClosure(T)#initialize' with type ( -> NoReturn)
Overloads are:
 - ParserClosure(T)#initialize(generator : Proc(Parser(T)))
```

```crystal
class ParserClosure(T) < Parser(T)
    def initialize(generator : Proc(Parser(T)))
        @generator = generator
        @output = [] of T
    end

    def reset
        @output = [] of T
    end

    def output
        @output[0]
    end

    def parse(input)
        if generator = @generator
            parser = generator.call()

            if parser.parse(input)
                @output << parser.output.not_nil!
                true
            end

            false
        end

        false
    end
end
```

```crystal
class BrainfuckParser
    include Haydari

    def parse_command
        parser = one_of("><+-.,")
        return parser.select { |t| BrainfuckTokens.from_string(t) }
    end

    def parse_program : Parser(BrainfuckProgram)
        start_t = string("[")
        
        commands_1   = parse_command.many
        sub_programs = ParserClosure.new ->self.parse_program
        commands_2   = parse_command.many

        program      = commands_1 + sub_programs + commands_2
        program      = program.select { |p| BrainfuckProgram.new p.concat }

        end_t = string("]")

        (start_t > program < end_t)
    end

    def parse(input : String)
        parser = parse_program
        if parser.run(input)
            parser.output
        end
    end
end
```

This code doesn't work also for another issue about  ```parse_program```'s return type. Please see https://github.com/crystal-lang/crystal/issues/2283

**Comment by umurgdk** [comment]
Or any better idea how to handle this recursion/lazyness? :dancer:

**Comment by asterite** [comment]
Hi,

Just like in #2283, if you don't provide code that we can copy and paste to immediately reproduce the problem you are having, so we can debug and fix the bug, there's not much we can do.

**Comment by asterite** [comment]
Oh, sorry, I see you provided a link to the github repo. That's good. In any case, it's better if you try to reduce the code to the minimum that exhibits the problem.

**Comment by asterite** [comment]
Hmmm... Just ran `crystal spec` on your project and everything's green. I don't know what else to do.

**Comment by umurgdk** [comment]
@asterite I just created another sample which uses recursive parser. could you please try to run it.

https://github.com/umurgdk/haydari/blob/master/samples/brainfuck_recursive.cr#L85

```recurse``` macro defined in here:
https://github.com/umurgdk/haydari/blob/master/src/haydari.cr#L77

**Comment by jhass** [comment]
Ping.

**Comment by asterite** [comment]
Please also try to provide reduced code that reproduces this. The problem with links to repos is that they eventually change and then the issue becomes harder to reproduce.

**Comment by asterite** [comment]
Two weeks afterwards, I'm closing this. Please reopen if you have reproducible code for this. Thanks!
