### ISSUE TITLE
What happened to REMOTE_ADDR ?

### ISSUE THREAD

**Issue by jmoriau** [crystal-lang/crystal#2288]
Hello,

Making the remote address available to the handlers was discussed here #453 and a few PR tried to add it #1721 #1720, but all 3 are closed.

Is there any plan to add it, was it simply forgotten or is it never going to happen ?

Best regards

**Comment by jhass** [comment]
#453 is still open, as is #1722 and #1947. #1721 and #1720 are closed by the author due to git issues.

**Comment by jmoriau** [comment]
Oops sorry I read `closed` at the end thought #453 was closed, and I didn't find #1722 so sorry.
