### ISSUE TITLE
Serialise enums to integers in JSON/YAML

### ISSUE THREAD

**Issue by Arcovion** [crystal-lang/crystal#2291]
I wanted to use an Enum in `JSON#mapping` &mdash; just had to define a couple of methods like so:
```crystal
require "json"

enum Example
  Zero
end

struct Enum
  def to_json(io : IO)
    value.to_json(io)
  end
end

def Example.new(pull : JSON::PullParser)
  from_value(pull.read_int)
end

Example::Zero.to_json
# => "0"
Example.from_json("0")
# => Zero
```
I didn't know how to make it work implicitly for all Enums, so I explicitly defined `Example.new` here.

Serialising to an integer should be the canonical format; if the user wants to use a string instead they can override it themselves:
```crystal
@[Flags]
enum Example2
  One
  Two

  def to_json(io : IO)
    to_s.to_json(io)
  end

  def self.new(pull : JSON::PullParser)
    parse(pull.read_string)
  end
end

Example2.flags(One, Two).to_json
# => "\"One, Two\""
Example2.from_json("\"One, Two\"")
# => Unknown enum Example2 value: One, Two (Exception)
```
This case using flags fails to convert... clearly serialising to a string by default would inevitably be more complicated and take up more space.

Thoughts? It would just save me having to write the methods out, that's all. :smile:

**Comment by asterite** [comment]
Hi! Nice ideas here. I agree with you, I think we can make the default be an integer and then the user can override, or we can provide a converter for this.

I tried to define `def Enum.new(pull : JSON::PullParser)` but the compiler can't see the overload, so it's a bug. I'll try to fix it and then I'll add it to the JSON/YAML serialization logic :-)

**Comment by asterite** [comment]
With #2489 now this can be implemented in `Enum`. What I did is in `from_json`/`from_yaml` to check for both cases, integer and string. `to_json`/`to_yaml` will always use the number representation.

This will work starting from the next release, it won't work with the current compiler.
