### ISSUE TITLE
BigInt.new(x) fails when typeof(x) is itself BigInt

### ISSUE THREAD

**Issue by dkhofer** [crystal-lang/crystal#2292]
Hi, the following code fails with the error below:

`require "big_int"`
`b = BigInt.new(0)`
`c = BigInt.new(b)`

`Error in ./src/test.cr:3: no overload matches 'BigInt#initialize' with type BigInt`
`Overloads are:`
` - BigInt#initialize(str : String, base = 10)`
` - BigInt#initialize(num : Int::Signed)`
` - BigInt#initialize(num : Int::Unsigned)`
` - BigInt#initialize(num : Float)`
` - BigInt#initialize(mpz : LibGMP::MPZ)`
` - BigInt#initialize()`

I'm guessing you just need to add the appropriate initializer?  Let me know if you have any questions, thanks!

**Comment by asterite** [comment]
Why do you want to create a BigInt with another BigInt?

**Comment by dkhofer** [comment]
I'm using the matrix shard with a matrix of BigInts and this line seems to be causing a compilation error similar to the one I posted:

https://github.com/Exilor/matrix/blob/master/src/matrix.cr#L224

eg the following code triggers it:

`require "big_int"`
`require "matrix"`
`zero = 0.to_big_i`
`one = 1.to_big_i`
`m = Matrix.rows([[one, one], [one, zero]])`
`m ** 2`

I should have just posted that but I had something more complicated originally.  :-)

**Comment by asterite** [comment]
Oh, I see. I think it then makes sense to have that constructor, similar to how you can do `Int32.new(1)`.

However, I guess that using BigInt with Matrix isn't quite good because for operations that end up with a float value you will loose precision?

**Comment by dkhofer** [comment]
This is a project that's just for fun, but I'm trying to use Matrix to compute really big Fibonacci numbers efficiently.  So I just care about large integers, not floats.  (Basic idea is methods 4 and 5 here: http://www.geeksforgeeks.org/program-for-nth-fibonacci-number/ )

I had written a custom matrix implementation here: https://github.com/dkhofer/algorithms/blob/master/src/fibonacci.cr#L21  I'm trying to replace it with Matrix.

**Comment by ozra** [comment]
"new'ing" values from arbitrary sources is also good in macros and generic functions. Personally I think it's reasonable that all std-types should be able to new with Self-typed val as arg (effectively making a clone).

**Comment by dkhofer** [comment]
Sweet, thanks Ary!
