### ISSUE TITLE
typeof(2 ** 2) => Float64

### ISSUE THREAD

**Issue by Arcovion** [crystal-lang/crystal#2299]
Whenever I use `**` I have to cast the result back to `Int32`.

**Comment by asterite** [comment]
That's right, because in general Int32 ** Int32 is not always an Int32.

```crystal
puts (2 ** -1) # => 0.5
```

**Comment by Arcovion** [comment]
Hmm, I guess I am just too used to the Ruby/Python behaviour.

**Comment by Arcovion** [comment]
Can it check either side to see if they are both positive integers, then always return `Int32`?

**Comment by asterite** [comment]
It's hard. It would have to be kind of built in in the compiler. The definition of `**` is something like this:

```crystal
def **(other : Int)
  # do the math
end
```

If we change it to this:

```crystal
def **(other : Int)
  if other > 0
    # do the math, return Int32
  else
    # do the math, return Float64
  end
end
```

I don't know what a good solution for this. Do you have many `**` in your code? Or else, do you absolutely need to work with ints instead of floats?

**Comment by Arcovion** [comment]
It's just to do with bitmasking, raising to a power of two and doing a bitwise AND which requires an integer.

**Comment by Arcovion** [comment]
Ok I can actually avoid the casting completely by changing (2 ** N) to (1 << N). Problem solved!

**Comment by asterite** [comment]
@Arcovion I was going to suggest the same :smile_cat:

**Comment by Arcovion** [comment]
Yea I realised it while I was writing that comment, sorry for the noise :panda_face:

**Comment by Arcovion** [comment]
Actually, this is still pretty annoying. For example if you want to work in other bases than base 2...

**Comment by Arcovion** [comment]
Ruby actually returns a rational: 
```ruby
5 ** -1
# => (1/5)
5 ** 1
# => 5
5 ** 1.0
# => 5.0
```

**Comment by waj** [comment]
I think it might make sense to have a `Int ** UInt` overload that always returns integers. Specially to avoid floating point rounding errors during conversion. Now to make this work the exponent must be explicitly suffixed with `_uXX`. Or... add a special case to the compiler to force the conversion when the exponent is a literal, but I'm not a big fan of hardcoding special cases unless is something tremendously convenient. 

Still, returning different types is not as useful in Crystal because that would result in a union type, forcing to convert anyway sometimes or degrading performance. Also, we don't have rationals in Crystal 😉

**Comment by Arcovion** [comment]
It wouldn't necessarily have to return a union&mdash; simply checking if the second argument is positive as @asterite suggested above should work, right?

I just took a look at the Ruby [Fixnum#**](http://ruby-doc.org/core-2.3.0/Fixnum.html#method-i-2A-2A) source code. The gist of it is:
```
fix_pow(x, y)
  if fixnum_positive(y)
    if (x == 1) return 1
    if (y < 0) return Rational (Crystal would return Float)
    if (y == 0) return 1
    if (y == 1) return x
    // More special cases
    return int_pow(x, y) // Return integer
  else if typeof(y) == Bignum
    // Handle Bignums
  else if typeof(y) == Float 
    // Special cases
    {
       LibM.pow(x, y) // Return float
    }
```
So it looks like Ruby does just that, it'd be great if Crystal did the same.
Then if you really want to keep the current behaviour you can move it to `Math#pow` or something... having this as the default is much cleaner as you never have to cast anything, like Ruby.

**Comment by waj** [comment]
Returning different types from a method builds a union type. At compile time the type of the expression will be `Int32 | Double` and if you need it as integer it has to be cast no matter if the arguments are constants. That's a difference between Crystal and Ruby, in order to raise errors in compile time.

**Comment by asterite** [comment]
I wouldn't mind hardcoding a special rule for pragmatism. The problem is that even an innocent-looking expression like `x ** 5` might not be correct if done just with integers. For example:

```crystal
a = 100
puts a ** 5 # => 1e+10
puts (a ** 5).to_i # => -2147483648
```

So for now (and for ever?) manually invoking `to_i` is necessary.

**Comment by Arcovion** [comment]
Thanks for the thorough explanations, regarding an overload for `UInt` I guess `a ** b.to_u` would be nicer than `(a ** b).to_i`. 
How about reopening this issue and implementing overloads such that `typeof(5 ** 2u32) => Int32` and `typeof(5u32 ** 2u32) => UInt32`?

**Comment by asterite** [comment]
@Arcovion Could you share some of your code? Do you need to do a lot of `**`?

**Comment by Arcovion** [comment]
Honestly it's just used twice in my code, it's not worth adding this feature... my thinking was just to make it as similar to Ruby as possible, and that all other operators except for `**` return a `UInt` when both args are `UInt`. Still, the vast majority of times `**` is used you want to return a `Float`, so the current behaviour makes perfect sense considering you don't want to return union types.

**Comment by asterite** [comment]
I'm reopening this.

Yesterday with @waj we revisited this and had an idea. We *could* make `Int#**(Int)` return an int, and raise if the argument is negative.

With this change, we'd have:

```crystal
2 ** 4 # => 16 (Int32)
2 ** 0 # => 1 (Int32)
2 ** -1 # => runtime error

# If I know the exponent could be negative, I can always
# use a float as the receiver
2.0 ** -1 # => 0.5 (Float64)

# Same for a var
x = ...
y = ...

# This could raise if both x and y are integers, and y is negative
x ** y 

# Doing any of this I can make sure it won't raise, and get a double
# back, and always cast to int if I want to
x.to_f ** y 
x ** y.to_f
```

This also plays nicely with `BigInt`, which right now supports `**` but only for positive integers.

What do you think?

**Comment by Arcovion** [comment]
That's a pretty cool idea, I just had a look to see if any other languages do that and Julia does:
```julia
julia> 8000 ^ -1                                                                                                                                                                                                                  
ERROR: DomainError
Cannot raise an integer x to a negative power -n. Make x a float by adding
a zero decimal (e.g. 2.0^-n instead of 2^-n), or write 1/x^n, float(x)^-n, or (x//1)^-n
 in power_by_squaring at intfuncs.jl:60
 in ^ at intfuncs.jl:84
```
And then of course if you ever wanted Ruby behaviour:
```ruby
2.3.0 :001 > 8000 ** -1
 => (1/8000)
```
The user would just have to use a rational number for the base instead of a float/int. Not that there needs to be rationals, just that this idea would still theoretically work with them.

So it seems to work for all cases. LGTM!

**Comment by asterite** [comment]
@Arcovion It's good to know that Julia does that. And since Julia is math-oriented, I think they might know what they are doing :-) (and I really like Julia, btw)

So it's decided, I'll change the behaviour of `Int#**(Int)`.

**Comment by rdp** [comment]
BigRational was added recently, FWIW.
