### ISSUE TITLE
Cannot output stderr?

### ISSUE THREAD

**Issue by chenkovsky** [crystal-lang/crystal#2308]
when I execute:
crystal eval "STDERR.puts \"haha\""

nothing happens

but I execute:
crystal eval "STDOUT.puts \"haha\""  
it runs correctly.

**Comment by asterite** [comment]
I think we should make STDERR `sync`ed. Related to #2290

**Comment by luislavena** [comment]
@asterite tried to find where STDOUT is `sync`ed in order to send a pull request but couldn't find it :cry:

**Comment by bcardiff** [comment]
I believe the changes from STDOUT were made in https://github.com/crystal-lang/crystal/commit/744720060703079746a7033f1bd460d0dcb8101e

**Comment by asterite** [comment]
STDOUT is not synced, but the top-level [print](https://github.com/crystal-lang/crystal/blob/master/src/kernel.cr#L41) flushes, and STDOUT has [flush_on_newline](https://github.com/crystal-lang/crystal/blob/master/src/kernel.cr#L2) set to true.

**Comment by luislavena** [comment]
@asterite thank you, will send a pull request.
