### ISSUE TITLE
`===` vs. `=~`

### ISSUE THREAD

**Issue by ozra** [crystal-lang/crystal#2312]
In a discussion regarding Onyx I came to the conclusion to rename `===` to `=~` and ditching the latter completely.
Regarding Crystal the question is, are both really necessary? If an alias to `=~` is added for String then `===` covers all grounds, and `=~` is completely moot.
And then the natural step (imo) is to rename `===` to `=~`.

The tri-eq gives the impression of meaning "even more equal" (and means that in for instance JS). It seems `=~` is the suitable operator for this meaning all around.

Am I missing something?

**Comment by kirbyfan64** [comment]
But `=~` is hardly "even more equal"...

**Comment by ozra** [comment]
No, neither is `===`. That's the point, it should reflect the "comparatively the same"-nature...

**Comment by kirbyfan64** [comment]
Ah, I misread the original post. Oops...

**Comment by ozra** [comment]
In light of the crystal motto of "don't have unnecessary things that are one more thing to learn" this redundancy really should be reduced imo.

**Comment by asterite** [comment]
`===` means "is in the category of" while `=~` is more like "pattern maches". For example `String === "hello"` means "hello" is in the category of strings, but I don't know if "hello" pattern matches the String class.

Now, Regex defines `===` to do `=~`, which maybe makes sense: a string is in the category of all regexes that matches it. But yes, the definition is a bit blurry.

For now I wouldn't modify this.

**Comment by ozra** [comment]
Of course that comparison with String.class method does differentiate it from "is equal by definition", since, as you remind me, the categorization aspect is added on top of that definition.
Hmm. I leave this open for a while, unless you want to close it @asterite ? Maybe some ideas for good definitions that make it all click come up?

**Comment by ozra** [comment]
And also, the fact that one is for checking truthiness of comparability and the other works with matches. Closes.
