### ISSUE TITLE
Local variable type gets mixed with block argument's type

### ISSUE THREAD

**Issue by dkhofer** [crystal-lang/crystal#2314]
Hi, I think I found a compiler bug.  I think I've stripped down the code as much as I can (to the point where it doesn't make any sense :-), but let me know if you have any questions.

The first few error lines:

`Bug: trying to downcast (Array(Int32) | Set(Int32)) <- Set(Int32)
[4523484171] *raise<String>:NoReturn +139
[4527082713] *Crystal::CodeGenVisitor#downcast<Crystal::CodeGenVisitor, LLVM::Value, Crystal::Type+, Crystal::Type+, Bool>:LLVM::Value +3081`

The code is below.

```crystal
NUMBERS = (1..10).to_a
pair_combos = Set(Set(Int32)).new
NUMBERS.each_combination(2) { |pair| pair_combos.add(Set.new(pair)) }
triple_combos = Set(Set(Int32)).new
NUMBERS.each_combination(3) { |triple| triple_combos.add(Set.new(triple)) }

pair_combos.each do |pair|
  triple_combos.each do |triple|
    combo = pair.to_a + triple.to_a
    combo.each_combination(2) do |pair|
      break if true
    end
  end
end
```

**Comment by asterite** [comment]
@dkhofer I fixed your indentation. Did you know you can do `crystal tool format` to indent it for you?

Also, you can surround  the code with "```crystal" (newline) and "```" (newline) to get syntax highlighting.

I'll investigate

**Comment by dkhofer** [comment]
Thanks!  The code is formatted just fine on my laptop, I just didn't know how to paste it in to github and maintain the spacing.  :-)

**Comment by asterite** [comment]
Reduced:

```crystal
def foo
  yield 1
end

x = true
foo do
  pp typeof(x)
  foo do |x|
    pp typeof(x)
    break
  end
end
```

Seems the compiler gets confused with the block argument being named the same as the local variable. It also happens with multiple block variables.

Workaround for you now, until I fix this: use another name for the block argument variable (pair, pair2 will work).

Thanks for reporting this! :-)

**Comment by dkhofer** [comment]
Oh jeez, I'm a little embarrassed that was the cause.  Well anyway, I had to rewrite the code for other reasons, so I'm all set, thanks!
