### ISSUE TITLE
Should '+' be translated as space in x-www-form-urlencoded params?

### ISSUE THREAD

**Issue by mverzilli** [crystal-lang/crystal#2339]
I'm not sure whether this is a bug or correct behaviour, thus the question mark at the end of the issue title :).

Consider the following Crystal snippet:

``` crystal
require "http/server"

server = HTTP::Server.new(8080) do |context|
  params = HTTP::Params.parse context.request.body.not_nil!
  context.response.content_type = "text/plain"
  context.response.print params["foo"]
end

puts "Listening on http://0.0.0.0:8080"
server.listen
```

Then consider the following curl command:

```
curl localhost:8080 -d "foo=bar+baz"
```

When you compile with Crystal 0.12.0, the command above returns:

`bar baz`

Whereas if you compile the same code with Crystal 0.13.0, the same command returns:

`bar+baz`

So the question is: which version is right? 

According to https://www.w3.org/Addressing/URL/uri-spec.html:

```
Within the query string, the plus sign is reserved as shorthand notation for a space. Therefore, real plus signs must be encoded. This method was used to make query URIs easier to pass in systems which did not allow spaces.
```

Which makes me think Crystal 0.12.0 had the right behaviour. But I always have trouble correctly interpreting W3's specs... they feel more for lawyers than for engineers :D.

PS: I can take care of fixing this once I'm sure whether it needs to be fixed.

**Comment by kirbyfan64** [comment]
FYI, this was from #2140. (Also, I think #2285?)

**Comment by mverzilli** [comment]
@kirbyfan64 good catch, thanks! This is almost a twin of #2285. It makes no sense to keep this open.
