### ISSUE TITLE
Format tool: couldn't format minitest/reporter.cr

### ISSUE THREAD

**Issue by splattael** [crystal-lang/crystal#2344]
Hi,

running `crystal tool format` in a project I got this error:

```
Syntax Error: the syntax for an argument with a default value V and type T is `arg : T = V` at ./libs/minitest/minitest/assertions.cr:5:33
Error:, couldn't format './libs/minitest/minitest/reporter.cr', please report a bug including the contents of it: https://github.com/crystal-lang/crystal/issues
```

Indeed `crystal tool format` is not able to format:
https://github.com/ysbaddaden/minitest.cr/blob/f2014c2175064e0b41bdfdc4b64f8a69b25da075/src/minitest/reporter.cr

Do you need more information?

Kind regards,
  Peter

**Comment by ysbaddaden** [comment]
The culprit seems to be `getter :symbol` where the colon is understood as a type separator.

**Comment by asterite** [comment]
Actually, seems that this reproduces it:

```crystal
foo &.bar.is_a?(Baz)
```

I'll fix it soon. @splattael Thanks for reporting this.
