### ISSUE TITLE
Use a stable sort algorithm (Was: Sort order of Array#sort(&block))

### ISSUE THREAD

**Issue by splattael** [crystal-lang/crystal#2350]
Hi,

today I've stumbled across the sort order of arrays using a block.

I would expected that `[1, 2] == [1, 2].sort { 0 }` to be `true`.
It is `true` for at least Ruby and Java. In Crystal it's `false`.

Is it a bug or just an undefined behaviour of quicksort?

Kind regards,
  Peter

**Comment by BlaXpirit** [comment]
I inquired about this a few days ago. Ultimately this is not a bug, but should perhaps be reconsidered.

The term you're looking for is [stable sort](https://www.google.com.ua/search?q=stable+sort). Indeed, many languages' built-in sorting algorithms are stable, even though this property slightly limits the performance of sorting. C++, on the other hand, made a separate [`stable_sort`](http://en.cppreference.com/w/cpp/algorithm/stable_sort).

I think the most popular sorting method is [Timsort](https://en.wikipedia.org/wiki/Timsort), used in Java and Python, and it is stable. [Quicksort](https://en.wikipedia.org/wiki/Quicksort) does not have this property.

**Comment by BlaXpirit** [comment]
**bcardiff** shared this example code https://gist.github.com/5395bfaef35ac1d14a1a

This adds the original indices of the items to the key tuples to keep the original order.

**Comment by asterite** [comment]
We just have a hand-made quicksort to be able to sort stuff, but we didn't actually though a lot about which algorithm to use and if we want it to be stable. So asking this here is a good chance to start the discussion :smile_cat:

**Comment by asterite** [comment]
(that is, because we wanted to bootstrap the compiler and it uses sort...)

**Comment by splattael** [comment]
It seems that after 53be65dee36a8dbcdb2d3dc1fde17202bd024acb sorting Array is stable:

## Before

```
$ crystal -v
Crystal 0.19.4 [7f82f79] (2016-10-07)
$ crystal eval "p [1, 2] == [1, 2].sort { 0 }"
false
```

## After

```
$.build/crystal -v
Crystal ci (2016-11-19)
$ .build/crystal eval "p [1, 2] == [1, 2].sort { 0 }"
true
```

I suspect this issue is resolved then and we can close it?
/cc @c910335

**Comment by BlaXpirit** [comment]
Maybe it's worth checking more thoroughly, seeing as 2 different algorithms are used...

**Comment by splattael** [comment]
@BlaXpirit Of course, good point! %)

**Comment by splattael** [comment]
@BlaXpirit You are right. It's stable until a size of 16:

```
$ .build/crystal eval "a = (1..16).to_a; p a == a.sort { 0 }"
true

$ .build/crystal eval "a = (1..17).to_a; p a == a.sort { 0 }" 
false
```

So, it's not stable enough ;)

**Comment by c910335** [comment]
@splattael 
Actually, sort in Ruby is not guaranteed to be stable.
https://docs.ruby-lang.org/en/trunk/Array.html#method-i-sort

    $ ruby --version
    ruby 2.3.2p217 (2016-11-15 revision 56796) [x86_64-darwin16]
    $ ruby -e "puts (0...7).to_a.sort { 0 }.to_s"
    [3, 1, 2, 0, 4, 5, 6]

**Comment by splattael** [comment]
@c910335 So, Ruby's behaviour has changed in a patch level :scream:

In Ruby 2.3.1 it is stable:

```
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
$ ruby -e 'p (0...7).to_a.sort { 0 }'
[0, 1, 2, 3, 4, 5, 6]
```

The sentence `The result is not guaranteed as stable. When comparison of two elements returns 0, the order of the elements is unpredictable.` is new in 2.3.2.
It wasn't there in 2.3.0 https://docs.ruby-lang.org/en/2.3.0/Array.html#method-i-sort.

TBH:
¯\\_(ツ)_/¯

I wish it was stable ;)

**Comment by splattael** [comment]
On my machine it Ruby 2.3.2 is still stable :open_mouth: 

```
$ ruby -v
ruby 2.3.2p217 (2016-11-15 revision 56796) [x86_64-linux]
$ ruby -e 'p (0...7).to_a.sort { 0 }'
[0, 1, 2, 3, 4, 5, 6]
```

(╯°□°）╯︵ ┻━┻

Computering is hard. Let's go shopping.

**Comment by splattael** [comment]
I did some research which I have should done before submitting this issue.

Ruby's sort is not stable. It never was. (Maybe it was stable by accident).
Some references:
* https://bugs.ruby-lang.org/issues/11907
* https://bugs.ruby-lang.org/issues/11379
* https://bugs.ruby-lang.org/issues/1089

I am closing this issue.

Sorry for the repetitive noise :-(

**Comment by sdogruyol** [comment]
@splattael nice work 👍

**Comment by asterite** [comment]
Go for example provides two `sort` functions, one stable and one unstable. We could do the same, so if you really need a stable sort you can do it.

https://golang.org/pkg/sort/#Sort
https://golang.org/pkg/sort/#Stable

**Comment by rdp** [comment]
Whoa, I always assumed ruby's sort was stable.

Just tried it:
```
$ ruby -ve "puts (0...7000).to_a.sort { 0 } == (0...7000).to_a"
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]
true
$ crystal eval "puts (0...7000).to_a.sort { 0 } == (0...7000).to_a"
false
```
ruby's algorithm is "mostly stable" huh?  That's almost more dangerous than being consistently unstable, to end users, in my mind LOL.  Wonder what they're doing...

It does seem to cause confusion to users (ex: sorts being different on different OS's) https://bugs.ruby-lang.org/projects/ruby-trunk/search?utf8=%E2%9C%93&scope=&issues=1&q=stable+sort

I think java avoids the confusion by sorting "natives" (like ints) using quicksort, and class objects using timsort, so everything "looks" stable.

Also wonder if Timsort is faster than the workarounds that people propose on ruby-core (#with_index etc.) which aren't very fast at all...
