### ISSUE TITLE
Doubly nested classes don't work

### ISSUE THREAD

**Issue by RX14** [crystal-lang/crystal#2352]
Reproduction: https://carc.in/#/r/uv4

Seems to work when the class is only 1 level deep.
Crystal version: 0.14.1

**Comment by waterlink** [comment]
This is probably because `Class` is used there. If I change `Class` => `Klass` it works like a charm: 

```crystal
class Nested::Klass::Test
  def self.foo
    "bar"
  end
end

pp Nested::Klass::Test.foo
# => Nested::Klass::Test.foo = "bar"
```

see: https://carc.in/#/r/uvd

**Comment by RX14** [comment]
Still seems like a bug to me. Here's a workaround:

https://carc.in/#/r/uvi
```crystal
class Nested::Class
end

class Nested::Class::Test
  def self.foo
  end
end

Nested::Class::Test.foo
```

**Comment by asterite** [comment]
This also triggers the bug:

```crystal
class Baz
end

class A::Baz::B
  def self.foo
    1
  end
end

A::Baz::B.foo
```
