### ISSUE TITLE
Unable to create a constant of type Int64

### ISSUE THREAD

**Issue by waterlink** [crystal-lang/crystal#2353]
```crystal
BIGCONSTANT = 2786237783246234632

class Hello(A)
end

Hello(BIGCONSTANT).new
```

This snippet fails with "Invalid constant on line 1" error.

**Comment by waterlink** [comment]
Additionally, I've got `<big number here>_i64 is not a valid Int32 constant`, but I can't reproduce it now.

**Comment by asterite** [comment]
Yes, I was going to say the same. I tried it locally and in carc.in and it works: https://play.crystal-lang.org/#/r/uzg

**Comment by waterlink** [comment]
Ok, I was getting this error in the `crystal playground` somehow.

**Comment by asterite** [comment]
Yeah, seems to be an issue in the playground only.

**Comment by waterlink** [comment]
I found another similar issue just now:

```crystal
BIGCONSTANT = -2786237783246234632

module Mod(T)
  def t
    T
  end
end

class Hello(A)
  include Mod(A)
end

pp Hello(BIGCONSTANT).new.t
```

https://play.crystal-lang.org/#/r/uzo

**Comment by waterlink** [comment]
Yes. I was able to reproduce the original error:

```crystal
MIN_RANGE = -2374623294237463578
MAX_RANGE = -MIN_RANGE

class Hello(T)
end

pp Hello(MAX_RANGE).new
```

https://play.crystal-lang.org/#/r/uzr

This happens, only if I try to compute `MAX_RANGE` through `MIN_RANGE` and happens only for `Int64`, not for `Int32`

**Comment by bcardiff** [comment]
I've just fixed the playground issue. Constants declaration were instrumented and they should not.

As pointed by https://play.crystal-lang.org/#/r/uzr seems to be a compiler issue regarding Int64 arguments in generics. That could be handled in another issue if it's not a quick fix.
