### ISSUE TITLE
Invalid memory access (signal 11)

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/crystal#2354]
If I run the whole Frost test suite it will pass, but if I run only Frost::Record tests, they will segfault with `Invalid memory access (signal 11) at address 0x8`.

The segfault happens when building a query like `Post.find(1)`; more specifically when `dup` tries to access the `@selects` instance variable of [Frost::Query::Data](https://github.com/ysbaddaden/frost/blob/master/src/query/data.cr#L5). The `@selects` variable is actually `nil`. I suspect the compiler to expect it to be Array(String) instead.

Since the whole test suite passes, I tried to annotate the properties of the Data class (as determined by crystal tool hierarchy), but to no avail. I thought maybe the compiler got confused because of `selects = self.selects` and renamed the local variable, but still no luck.

A git bisect identified the following commit as the culprit: https://github.com/crystal-lang/crystal/commit/e613ce0a9e1ecdf3e9d03d6fc1d13724dd08ddeb which looks rather harmless to me...

**Comment by ysbaddaden** [comment]
I found the problem: in the following example Builder#initialize is never called, but the compiler believes that it did. In my case, Builder#initialize sets an ivar which is never properly set; trying to access its values thus segfaults.

```crystal
class Builder
  getter data

  def initialize(@data = nil)
  end
end

class Executor(T) < Builder
  def initialize
    super(1)
  end
end

class Obj
end

p Executor(Obj).new.data   # => 0
```

**Comment by asterite** [comment]
@ysbaddaden Thank you for taking the time to reduce the problem!!

**Comment by asterite** [comment]
@ysbaddaden Fixed! Could you test frost with this change and see if it works now? I ask because frost is pretty big so it's a good test suit for the compiler :-)

**Comment by oltmannsdaniel** [comment]
@asterite @yegortimoshenko DO you know how we can solve it it : https://github.com/datanoise/mongo.cr
