### ISSUE TITLE
"invalid memory access" segfault using at_exit and $global variables

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/crystal#2357]
I couldn't reduce, but this now fails (not sure since when, but 0.14.2 is affected): https://github.com/ysbaddaden/selenium-webdriver-crystal/blob/d4179a8eb78420c699227c357cf67209ec55a82d/test/test_helper.cr

This is what happens:
1. the `$driver` and `$session` variables are initialized (they are accessible);
2. minitest executes in an `at_exit` block (Test instances are then created);
3. accessing `@driver` results in segfault.

I suspect that the global variables are collected at some point.

Note: I fixed it by using class variables instead of global variables, which was a bad design anyway.

**Comment by asterite** [comment]
@ysbaddaden I can try to reduce it.

I checkout out that branch but with 0.14.2 I can't compile it, lots of syntax errors regarding method arguments, and then when I fix that I get some semantic errors. If you point me to a version that compiles but fails I will take a look at it. Thanks!

**Comment by ysbaddaden** [comment]
It should compile with 0.14.2 at this commit: https://github.com/ysbaddaden/selenium-webdriver-crystal/commits/fe09386bc1c02176339ab63a5cce92c60bbbdb4f

**Comment by sdogruyol** [comment]
Now that global variables are removed from Crystal. Can we close this issue?
