### ISSUE TITLE
Pointer(Void).null is not falsey in specs

### ISSUE THREAD

**Issue by jessedoyle** [crystal-lang/crystal#2361]
Hi there,

I _think_ I've encountered a bug in the latest release of Crystal:

```crystal
it "returns a falsey result" do
  Pointer(Void).null.should be_falsey # => failing test
end
```

It appears at first glance that null pointers still act falsey, but that the issue lies with the `be_falsey` matcher because the following code won't produce output:

```crystal
if Pointer(Void).null
  puts "hello!"
end
```

It's definitely possible that I'm missing something, but this was a test in some of my code that started failing after updating to the latest release.

Thanks! (Also awesome work on the `crystal play` command :smile:)

**Comment by kumpelblase2** [comment]
I think you meant `!Pointer(Void).null` right?

Btw, this works fine:
```crystal
unless Pointer(Void).null
    puts "output"
end

# => output
```

Yet this one does not:

```crystal
if !Pointer(Void).null
    puts "false"
end

# => <no output>
```

Shouldn't the first one imply that the second one works the same?

**Comment by asterite** [comment]
I think Pointer is missing defining the ! method, though in general I think the meaning of bang should be hard-coded in the compiler and it shouldn't be definable

**Comment by asterite** [comment]
I added `Pointer#!`. In the long run I think I'd like to implement #1196 and make `!` non overridable (hardcode the rule in the language).
