### ISSUE TITLE
Playground issue with visibility keywords

### ISSUE THREAD

**Issue by stevegeek** [crystal-lang/crystal#2362]
When using the new playground with crystal 0.14.2 (awesome feature :+1:) I am getting the following error when using the `private` modifier on a method definition, `Exception Syntax error in play:2: unexpected token: def` 

for example using the following snippet from the crystal documentation:

    class Person
      private def say(message)
        puts message
      end

      def say_hello
        say "hello" # OK, no receiver
        self.say "hello" # Error, self is a receiver

        other = Person.new "Other"
        other.say "hello" # Error, other is a receiver
      end
    end

**Comment by bcardiff** [comment]
Thanks @stevegeek for the report (and the kind words :+1:). The issue is now fixed on master.
