### ISSUE TITLE
Class that breaks playground

### ISSUE THREAD

**Issue by puppetpies** [crystal-lang/crystal#2364]
# Error from playground

Exception
Error in macro 'getter?' /opt/crystal/src/object.cr:355, line 7:

  1.     
  2.       
  3.         @firstname : String
  4.         
  5.       
  6. 
  7.       def firstname?
  8.         @firstname
  9.       end
 10.     
 11.   

      def firstname?
          ^~~~~~~~~~

can't declare def dynamically

# This works in crystal run when from a file,

class Names

  property? firstname : String
  property? lastname : String
  
  setter firstname
  setter lastname
  getter firstname
  getter lastname
  
  def initialize
    @firstname = ""
    @lastname = ""
  end
  
	def firstname(name)
  	@firstname = name
	end
  
  def lastname(name)
    @lastname = name
  end

end

name = Names.new
name.firstname = "John"
name.lastname = "Smith"

print name.firstname
print name.lastname

**Comment by luislavena** [comment]
Hello @puppetpies, can you confirm if this is not similar to #2355?

Thank you.

**Comment by puppetpies** [comment]
Yes i believe this is the same issue.

**Comment by bcardiff** [comment]
Yes, it's a duplicate and fixed in master already. Thanks @puppetpies for the report though.
