### ISSUE TITLE
Bulding crsytal with  ssl and zlib compression

### ISSUE THREAD

**Issue by waghanza** [crystal-lang/crystal#2365]
Hi,

I'm bulding `crystal`. The command is use is 
~~~sh
make
~~~
but this is a **wrapper** around
~~~sh
./bin/crystal build $(FLAGS) -o $@ src/compiler/crystal.cr -D without_openssl -D without_zlib
~~~

How can I build crystal with `openssl` and `zlib` ?

**Comment by bcardiff** [comment]
Those flags affects only the binary of the compiler itself. If your program uses zlib or openssl they will be included in your program.

You can read more about it in https://github.com/crystal-lang/crystal/pull/2306

The playground tool in the compiler starts and http server with websocket. The http server depends on zlib for compression and websockets requires by default openssl SHA1 implementation. The flags allows the compiler to build an http server without compression support and with a SHA1 crystal implementation. Leaving the compiler free of dependencies.
