### ISSUE TITLE
Memoize and type inference differences when early return

### ISSUE THREAD

**Issue by luislavena** [crystal-lang/crystal#2373]
Hello,

While writing some code detected that certain styles of memoization produce different return types for the methods:

``` crystal
class Foo
  def foo
    @foo ||= begin
      "awesome"
    end
  end

  def bar
    return @bar if @bar

    @bar = "awesome"
  end

  def baz
    @bar ||= "awesome"
  end
end

pp typeof(Foo.new.foo) # => String
pp typeof(Foo.new.bar) # => String?
pp typeof(Foo.new.baz) # => String
```

As you can see, `Foo#bar` will never return `nil`, but seems that early `return` is being detected as such possibility.

The `begin...end` approach works good for multi-line methods, but it nest things a bit further so might be confusing (this also happen for Rubyst, and multi-line return methods)

Wondering if this is a bug or is the expected behavior.

Thank you.
:heart: :heart: :heart:

**Comment by luislavena** [comment]
I think the other alternative is use `if local = @instance` approach:

```crystal
class Foo
  def bar2
    if bar2 = @bar2
      bar2
    else
      @bar2 = "awesome
    end
  end
end
```

**Comment by bcardiff** [comment]
```
  def meh
    var = @bar
    return var if var

    @bar = "awesome"
  end
```

**Comment by bcardiff** [comment]
You could also do

```crystal
class Foo
  def meh
    var = @bar
    return var if var

    @bar = "awesome"
  end
end
```

although is not something so idiomatic.
The behavior you see en `Foo#bar` is detailed in http://crystal-lang.org/docs/syntax_and_semantics/if_var.html .

In `#foo` and `#baz` works because the return type is gather from the expression and not form the instance variable.

**Comment by luislavena** [comment]
Thank you @bcardiff, I read that section of the doc but since it doesn't particularly mention about method's signature, was wondering if was worth asking.

Definitely the `local = @instance` and `return local if local` reads better than nested `if`s, but again, is not very idiomatic :smile: 

Once again, thank you for the response, if there is interest, I will send a pull request to improve the docs section with this *detail*.

Cheers.

**Comment by asterite** [comment]
If you desugar ||= you will find that || assigns the left hand side to a temporary local variable, according to the docs. From there it's more clear why it works that way.

But yes, anything we can add/change to improve the docs is welcome :-)

**Comment by asterite** [comment]
http://crystal-lang.org/docs/syntax_and_semantics/or.html and http://crystal-lang.org/docs/syntax_and_semantics/assignment.html

**Comment by asterite** [comment]
@luislavena if you want you can send a PR to improve the docs on this. Otherwise, I think we can close this.

**Comment by sdogruyol** [comment]
Can we close this @luislavena @asterite ?

**Comment by asterite** [comment]
Sounds good
