### ISSUE TITLE
[Macros] yield outputs syntactically invalid method call inside block using two-character operators

### ISSUE THREAD

**Issue by Ragmaanir** [crystal-lang/crystal#2374]
hi,

```crystal
macro a(block)
  puts "{{block}}"
end

a(arr.each{ |n| n == 0 }) #=> arr.each(&.= = 0)
```

There is an extra space. I think this might be a bug and got introduced in 0.14.

More examples: https://carc.in/#/r/vb2

**Comment by waterlink** [comment]
I have got this too, recently, I believe it has appeared from 0.14.

**Comment by BlaXpirit** [comment]
Actually, [according to carc.in](https://carc.in/#/r/vfj), this is a very old bug.
