### ISSUE TITLE
Errors during crystal build

### ISSUE THREAD

**Issue by dsounded** [crystal-lang/crystal#2379]
My Crystal version is 0.14.2 and I can't build anything with it, got errors with old syntax, I've installed it with http://crystal-lang.org/docs/installation/on_debian_and_ubuntu.html this. But here is a lot of errors in sources during new changes(brackets in def, `arg : T = V` etc). However works good on my Mac, but doesn't work on Linux. Any ideas ?

**Comment by asterite** [comment]
Did you git pull? Whats your revision? And please show output of bin/crystal --version. Or maybe you have a cached .build/crystal ? Make sure to do make clean crystal

**Comment by dsounded** [comment]
I didn't install it from sources, just with aptitude
Crystal 0.14.2 [e1af3d5] (Wed Mar 23 00:13:58 UTC 2016)

**Comment by dsounded** [comment]
Right now I've got this 
`Syntax error in /opt/crystal/src/io/string_io.cr:212: the syntax for an argument with a default value V and type T is `arg : T = V``

**Comment by luislavena** [comment]
@dsounded I recommend you remove (`apt-get remove --purge crystal`) and install again. For some reason the `src` code of your installation seems haven't updated to latest `0.14.2`

This happened to be a few times with `apt` in the past, but not recently. Perhaps that helps.

Cheers.

**Comment by dsounded** [comment]
@luislavena I've tried it a couple of times, haven't helped, I've written this, https://github.com/crystal-lang/crystal/issues/2287

what version of llvm version I need ?

**Comment by luislavena** [comment]
@dsounded please join us on IRC (`#crystal-lang` room) for real time assistance.

I have LLVM 3.6 installed (`apt-get install llvm-3.6`)

I cannot find `/opt/crystal/src/io/string_io.cr` in my local installation of crystal:

```
$ dpkg -l | grep crystal
ii  crystal                                     0.14.2-1                                   amd64        The full stack of crystal

$ crystal --version
Crystal 0.14.2 [e1af3d5] (Wed Mar 23 00:13:58 UTC 2016)

$ crystal env 
CRYSTAL_PATH="libs:/opt/crystal/bin/../src"
CRYSTAL_VERSION="0.14.2-0-ge1af3d5"

$ cat /opt/crystal/src/io/string_io.cr
cat: /opt/crystal/src/io/string_io.cr: No such file or directory
```

Looking closely, `string_io.cr` was the old name of what now is known as MemoryIO (inside `memory_io.cr` which might validate my comment: seems `/opt/crystal` directory contains something that is not up-to-date with the newer package.

I recommend nuking it (`rm -rf /opt/crystal`) after you've removed the package with apt.

Cheers.

**Comment by dsounded** [comment]
Didn't help so far. still the same

Error while requiring "prelude": stat: Not a directory

**Comment by dsounded** [comment]
Hmmm, was some trouble with the packages, have done with them with autoremove, anyway, thanks a lot guys.
