### ISSUE TITLE
Can't match type variables in case statement

### ISSUE THREAD

**Issue by BlaXpirit** [crystal-lang/crystal#2383]
```crystal
a = Bool
case a
  when Bool; ":)"
  else; ":("
end
#=> ":("
```

I know [the reason](http://crystal-lang.org/docs/syntax_and_semantics/case.html) for this is to allow matching a variable for its type, but I don't think this should be hardcoded to prevent the obvious behavior which is equality checking (without a possibility to override it). Yes, this can be "fixed" with `when Bool.class` but that's no fun.

**Comment by asterite** [comment]
Interestingly, we had a discussion about case/=== internally. Note that if you try that in Ruby it will behave the same way. Basically === is not equality. Bool is not a Bool, it does not belong to the category of bools. But I will write more about this later (kind of slow with a mobile phone)

**Comment by asterite** [comment]
Since a few versions you can do:

```crystal
a = Bool
case a
  when Bool.class; ":)"
  else; ":("
end
```

so this should solve the problem.
