### ISSUE TITLE
Concurrency issue on specs build

### ISSUE THREAD

**Issue by fearenales** [crystal-lang/crystal#2384]
I'm trying to work with [crystal-i18n](https://github.com/whity/crystal-i18n) lib but I'm facing a strange error.

The original lib has broken dependencies and deprecated API calls, so, in order to make it easy to reproduce this issue, @nuxlli has created a fork and a new branch.

You can reproduce it by running the following commands:

```sh
$ git clone https://github.com/nuxlli/crystal-i18n && cd crystal-i18n
$ git checkout feature/updating_crystal
$ crystal spec
Error in ./spec/i18n_spec.cr:27: instantiating 'I18n::I18n#currency(String)'

    obj.currency(123.123.to_s).should(eq("€123,123"))
        ^~~~~~~~

in ./src/i18n/i18n.cr:111: Bug: already had input observer

      value = self.number(value, locale)
                   ^~~~~~
```

If I comment [other `number` tests](https://github.com/nuxlli/crystal-i18n/blob/master/spec/i18n_spec.cr#L18-L24), leaving only the `currency` one to be run, it passes.

I'm not quite sure, but this sounds like a concurrency issue on specs build (i.e. a bug on Crystal language -- that's why I'm submitting this issue here)

**Comment by asterite** [comment]
Reduced:

```crystal
def foo(x : String = "")
  /#{1}/
end

foo
foo("")
```

**Comment by asterite** [comment]
Fixed!

@fearenales As a workaround, until the next version that will contain this fix, you can replace this:

```crystal
/(\d+)#{dec_separator}?(\d+)?/i
```

with this:

```crystal
Regex.new("(\\d+)#{dec_separator}?(\\d+)?", Regex::Options::IGNORE_CASE)
```

**Comment by fearenales** [comment]
Thank you @asterite ! That workaround worked like a charm! :)
