### ISSUE TITLE
parser (?) block issue

### ISSUE THREAD

**Issue by schmurfy** [crystal-lang/crystal#2389]
I tried to search but it's hard to be sure this is not a duplicate since I am not really sure what to look for :s
The problem is with this code:

```crystal
class Runner
  def it(msg, &block);  block.call; end
  
  def run
    with self yield
  end
end

def run(&block)
  Runner.new.run(&block)
end

# This one works fine
Runner.new.run do
  it("rains") do
    p [:ok]
  end
end

# This one does not
# run do
#   it("rains") do
#     p [:ok]
#     
#   end
# end
```

If you run this as is it works fine but if you uncomment the last part it will fail and as far as I can say it will do so before executing anything, for me the last two examples are stricly identical, is that a bug or a limitation of the parser/language ?

Edit: I forgot to say I tested this with crystal 0.14.2

**Comment by waterlink** [comment]
`with self yield` works only with non-captured blocks. Whenever you pass a block and store it or re-pass to another method it promotes to a captured block.

As far as I know it is an intended behavior.

And it looks like you are trying to implement something like this: github.com/waterlink/spec2.cr

**Comment by schmurfy** [comment]
you are right I was ^^
But it also served as a playground to see what crystal is capable of, I thought it was an intended behavior but could not figured out why, is there a way to evaluate a block on a specific object ? (instance_eval/instance_exec in Ruby)

I had no idea this was possible:
```crystal
macro describe(&block)
  Runner.run() {{block}}
end
```
it looks like a good substitute.
Thanks for pointing your spec project, it will definitely help !

Also I don't think i could write `with obj yield` the last time I checked crystal but it is nice to be able to do it.
I am closing the issue but if anyone want the finale result, here is what works:

```crystal
class Runner
  def it(msg, &block);  block.call; end
  
  def self.run
    with new yield
  end
end

macro describe(&block)
  Runner.run() {{block}}
end

describe do
  it("rains") do
    p [:ok]
  end
end

```
