### ISSUE TITLE
Error when running bin/crystal from expanded tar gz in 0.15.0

### ISSUE THREAD

**Issue by spalladino** [crystal-lang/crystal#2412]
Downloading the tar.gz for version [0.15.0](https://github.com/crystal-lang/crystal/releases/) for Linux x86_64 and running `bin/crystal foo.cr` from the expanded directory, the compiler fails with the following error:

```
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "/opt/crystal/.crystal/crystal-run-foo.tmp" "${@}"  -rdynamic  /opt/crystal/src/ext/libcrystal.a -levent -lrt -lpcre -lgc -lpthread -ldl`
```

On OSX, it does not fail but does yield a warning:
```
ld: warning: directory not found for option '-Lbin/../embedded/lib'
```

This does not happen on 0.13.0. My guess is this is related to this commit: https://github.com/crystal-lang/crystal/commit/51f63e816151b3fa8a3f5842b539586a41fb5e1c#diff-972234d62deb68357909cbb87cb8e7e7R232

Note that specifying an absolute path for `LIBRARY_PATH` solves the issue. I'll be sending a PR for `https://github.com/crystal-lang/omnibus-crystal` with a possible fix later today.

**Comment by asterite** [comment]
Might also be related to #2393
