### ISSUE TITLE
Packaging crystal

### ISSUE THREAD

**Issue by waghanza** [crystal-lang/crystal#2416]
Hi,

I'm tryning to create a **deb** package for `crystal` (`0.15.0`)

I have, in an isolated environment (**Docker), compiled crystal (with the last version of `boehm gc`).

In my package I have
* /usr/local/lib/libgc.so.1.0.3
* /usr/local/bin/crystal
* /usr/share/crystal

When trying to compile crystal source code
`CRYSTAL_PATH=/usr/share/crystal crystal eval 'p 1 + 2'`
I have
~~~crystal
/usr/bin/ld: cannot find -lgc
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "/tmp/t/.crystal/crystal-run-eval.tmp" "${@}"  -rdynamic  /usr/share/crystal/ext/libcrystal.a -levent -lrt -lpcre -lgc -lpthread -ldl`
~~~

However, I have installed **libgc** (previously compiled) 
`strings -n5 /etc/ld.so.cache  | grep 'gc.so'`
give me
~~~
libgc.so.1
/usr/local/lib/libgc.so.1
~~~

Which gc file is required by `crystal` **compiler** ?

**Comment by asterite** [comment]
Maybe related to #2412 ?

**Comment by ysbaddaden** [comment]
Do you have the `libgc.so` -> `libgc.so.1.0.3` link?

**Comment by waghanza** [comment]
I have `libgc.so.1 -> libgc.so.1.0.3`

should it be **libgc.so** ?

**Comment by ysbaddaden** [comment]
In order for `ld` to find it, then for the OS to find it afterwards, I believe there should be both links. On my system I have:

```
/usr/lib/x86_64-linux-gnu/libgc.so -> libgc.so.1.0.3
/usr/lib/x86_64-linux-gnu/libgc.so.1 -> libgc.so.1.0.3
/usr/lib/x86_64-linux-gnu/libgc.so.1.0.3
```

**Comment by waghanza** [comment]
:+1:
