### ISSUE TITLE
Nil vs Index out of bounds in Array.

### ISSUE THREAD

**Issue by isaacsloan** [crystal-lang/crystal#2419]
array = [1, 3]
   Why does array.index(20) return nil but array[20] returns "Index out of bounds"?

**Comment by kumpelblase2** [comment]
Because they do different things. `array[20]` gets the value at index 20 (and thus raises if this index does not exist). `array.index(20)` returns the index of the value 20. `array.at(20)` would again raise an "Index out of bounds", just like `array[20]` would.

**Comment by isaacsloan** [comment]
Doh. Thanks.

Isaac Sloan - isaacsloan.com
Artisan Rails Architect
1391 S Slate Canyon Dr.
Provo, Ut 84606
Cell: (435)-669-5005
