### ISSUE TITLE
Is docker compiled version suitable for debian ?

### ISSUE THREAD

**Issue by waghanza** [crystal-lang/crystal#2420]
Hi,

I want to package `crystal` for **debian** `8`

I am using the `docker` image

~~~dockerfile
FROM crystallang/crystal
~~~

This image is based on :

* Ubuntu 14.04.3 LTS
* gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4

The latest `debian` use `gcc (Debian 4.9.2-10) 4.9.2`.

I think I **COULD** make a debian package, but I will not be a pure **debian** package since the compiler version is not the same, no ?

I there a way to compile with gcc 4.9 on ubuntu ?

Regards,

**Comment by waghanza** [comment]
I have find a way to use  

~~~
gcc (Ubuntu 4.9.3-8ubuntu2~14.04) 4.9.3
~~~

instead of 

~~~
gcc (Debian 4.9.2-10) 4.9.2
~~~

At least, it's **4.9** (not so sure there are **huge** differences between `4.9.2` and `4.9.3`)

**Comment by waghanza** [comment]
If somebody is interested by testing this, the package is here ==> https://www.dropbox.com/s/j30i8jfa9cac9om/crystal_0.15.0_amd64.deb

**Comment by jhass** [comment]
Why is this is a issue? What can the Crystal project do here? If you're looking for testers the mailing list or Subreddit seems like a better place.

**Comment by waghanza** [comment]
subreddit ?

**Comment by jhass** [comment]
https://www.reddit.com/r/crystal_programming/

**Comment by waghanza** [comment]
I'll check.

I close this **issue**
