### ISSUE TITLE
Windows10 Compile Error

### ISSUE THREAD

**Issue by umurgdk** [crystal-lang/crystal#2431]
As many of you know new Window10 preview comes with Ubuntu sub system. Good news is precompiled Ubuntu deb packages are already working. But I tried to compile crystal from its source. I'm getting this strange error which doesn't say much. Does anybody faced this kind of error on Ubuntu before?

```
root@localhost:~/crystal# make
CRYSTAL_CONFIG_PATH=`pwd`/src ./bin/crystal build  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
Invalid memory access (signal 11) at address 0x7ff5ffeefab8
[12638893] __crystal_sigfault_handler +61
[24690684] sigfault_handler +40
[140694532326208] ???
[12131580] ???
[12114430] ???
...
... thousands of questions marks just like the line above
[12646872] main +40
[140694515424965] __libc_start_main +245
[5629425] ???
make: *** [.build/crystal] Error 11
```

**Comment by kirbyfan64** [comment]
Try building with `make FLAGS=--debug`.

**Comment by umurgdk** [comment]
@kirbyfan64 same. Btw I just tried to run one of my crystal server apps, and it works. But whenever an error occurs it shows question marks instead of descriptive messages

**Comment by asterite** [comment]
As in IRC, someone suggested that this might be an out of memory error. How much memory does the subsystem have?

**Comment by umurgdk** [comment]
ok I'm sorry. I just forget I have Linux commands are working :D anyway I checked memory via "free -m" and It shows 1G of memory as total. it seems there is a memory limitation on the subsystem.

**Comment by kirbyfan64** [comment]
Well, MS *did* say it was in beta...

**Comment by umurgdk** [comment]
well at least precompiled packages are working hehe :)

**Comment by jhass** [comment]
So nothing we can do anything about, closing for now.
