### ISSUE TITLE
Recognize UTF-8 whitespace characters as whitespace.

### ISSUE THREAD

**Issue by skunkworker** [crystal-lang/crystal#2439]
Currently crystal only recognizes ASCII whitespace characters as whitespace.
characters like \u205f,\u3000,\u0085,\u00a0,\u2007 aren't recognized. 
Looking through the source for char#whitespace? it seems like only ASCII is currently supported. Is this a design decision or is this an area that needs more work?

**Comment by skunkworker** [comment]
In just thinking about it we could leave the current ASCII priority and append a check on the end. It's not going to check UTF-8 if it doesn't have too.

```Crystal
  def whitespace?
    self == ' ' || 9 <= ord <= 13 || utf8_whitespace?(self)
  end
```

In this issue https://github.com/crystal-lang/crystal/issues/1648 it's put forward to add Unicode support with it's own module. Which could look something like this in `char.cr`

```Crystal
  def whitespace?
    self == ' ' || 9 <= ord <= 13 || Unicode::char_is_utf8_whitespace?(self)
  end
```

**Comment by skunkworker** [comment]
Though if we use a Hash we could achieve (theoretically) near O(1) speeds as we won't have collisions and the comparison should take the same amout of time every time.
```Crystal
whitespace_characters = {
  ' '      => :whitespace,
  '\u205f' => :whitespace, 
  '\u3000' => :whitespace,
  '\u0085' => :whitespace,
  '\u00a0' => :whitespace,
  '\u2007' => :whitespace
  } of Char => Symbol


char = ' '
puts whitespace_characters[char]? == :whitespace
```

**Comment by kostya** [comment]
https://github.com/crystal-lang/crystal/pull/1299

**Comment by EvanHahn** [comment]
#1299 was closed. Should this be closed too?

**Comment by olbat** [comment]
You can maybe consider [Unicode character properties](https://en.wikipedia.org/wiki/Unicode_character_property) (there is a property for [whitespaces](http://www.unicode.org/reports/tr44/#White_Space)) ?

Just in case since Crystal's PCRE comes with [unicode support](http://www.pcre.org/original/doc/html/pcreunicode.html), it's possible to use character properties in a regular expression (using the `\p{}` notation) but it would be a lot slower that using a list ...

**Comment by bcardiff** [comment]
FYI: #2662 `\p` is not yet supported

**Comment by jhass** [comment]
"not yet supported" is not quite right, it depends on the PCRE you link to.
