### ISSUE TITLE
Inline Assembly in Crystal

### ISSUE THREAD

**Issue by nabeelomer** [crystal-lang/crystal#2440]
Are you guys planning on supporting inline Assembly in Crystal?

**Comment by sdogruyol** [comment]
It's already possible to use inline assembly in Crystal.

Check this for example https://github.com/kubo39/tinycr/blob/master/hello.cr

**Comment by asterite** [comment]
@nabeelomer As @sdogruyol says, it's already supported. It's not documented because it's long to document, but it's mostly like in C/LLVM/Rust.

**Comment by ysbaddaden** [comment]
There are examples right into Crystal, too:
- https://github.com/crystal-lang/crystal/blob/master/src/fiber/fiber.cr#L125
- https://github.com/crystal-lang/crystal/blob/5bcf6d51dfffec4f8acc62e6e7af7e029e55de37/spec/compiler/codegen/asm_spec.cr

Along with the LLVM implementation:
- https://github.com/crystal-lang/crystal/blob/5bcf6d51dfffec4f8acc62e6e7af7e029e55de37/src/compiler/crystal/codegen/asm.cr
