### ISSUE TITLE
Benchmark odd results

### ISSUE THREAD

**Issue by marceloboeira** [crystal-lang/crystal#2444]
Since @asterite commented on a reddit post about string concatenation,  I've been trying to decide between string concatenation or string builder in order to create a reliable string render output. (marceloboeira/srt.cr#2) 

Code example:

```crystal
require "benchmark"

example = ["foo"]

100.times do
 example << "bar"
end

Benchmark.ips do |x|
  x.report("string concat") do
    buffer = ""

    example.each do |a|
      buffer += a
    end

    buffer
  end

  x.report("string builder") do
    buffer = String::Builder.new

    example.each do |a|
      buffer << a
    end

    buffer.to_s
  end
end
```

Running the same example 3 times, produced odd results:

```bash
$ crystal run bench.cr  --release
string  concat   8.21M (± 7.84%)       fastest
string builder   4.06M (± 6.13%)  2.02× slower

$ crystal run bench.cr  --release
string  concat  59.44k (± 7.07%)  8.74× slower
string builder 519.71k (± 5.38%)       fastest

$ crystal run bench.cr  --release
string  concat   57.6k (± 4.42%)  8.31× slower
string builder 478.42k (± 8.68%)       fastest
```

Which one is the best?

**Comment by sdogruyol** [comment]
Why don't you build an executable with `crystal build --release bench.cr` and then run it?

**Comment by marceloboeira** [comment]
@sdogruyol will do!

**Comment by marceloboeira** [comment]
Adding `MemoryIO` sample:

```crystal
require "benchmark"

example = ["foo"]

100.times do
 example << "bar"
end

Benchmark.ips do |x|
  x.report("memory concat") do
    buffer = MemoryIO.new

    example.each do |a|
      buffer << a
    end

    buffer
  end

  x.report("string concat") do
    buffer = ""

    example.each do |a|
      buffer += a
    end

    buffer
  end

  x.report("string builder") do
    buffer = String::Builder.new

    example.each do |a|
      buffer << a
    end

    buffer.to_s
  end
end
```

```bash
$ crystal run bench.cr  --release
 memory concat 438.76k (± 7.57%)  1.03× slower
 string concat     52k (± 4.67%)  8.68× slower
string builder 451.53k (± 8.21%)       fastest

$ crystal run bench.cr  --release
 memory concat  452.7k (± 2.70%)       fastest
 string concat  51.49k (± 5.30%)  8.79× slower
string builder 450.34k (± 8.26%)  1.01× slower
```

**Comment by marceloboeira** [comment]
Compiled with `crystal build bench.cr --release`, running several times `./bench`:

```shell
memory concat 443.62k (± 5.99%)  1.13× slower
 string concat  52.22k (± 4.30%)  9.63× slower
string builder 503.02k (± 7.25%)       fastest

 memory concat 415.87k (± 9.61%)  1.11× slower
 string concat  53.07k (± 1.96%)  8.74× slower
string builder 463.58k (± 5.69%)       fastest

 memory concat 447.44k (± 4.06%)  1.06× slower
 string concat  54.36k (±15.77%)  8.71× slower
string builder 473.73k (± 4.06%)       fastest
```


@sdogruyol now it seems correct! Why does this happens?

**Comment by lbguilherme** [comment]
I don't understand, what is the issue here? String builder is indeed an order of magnitude faster than string concat because it doesn't need to create temporary strings all the way. Benchmark results are as expected.

**Comment by marceloboeira** [comment]
@lbguilherme look at the issue description, running the same benchmark I got different results, so I want to understand why. 

After @sdogruyol comment I believe the compiler must be doing different tweaks each time I compile.

**Comment by lbguilherme** [comment]
@marceloboeira Running the compiler twice won't generate a different output. It is probably because of cold cache. The first run of a benchmark might be compromised because of that and is usually ignored. Did you get any discrepant results after the first run?

**Comment by marceloboeira** [comment]
@lbguilherme if I compile then run the binary several times I don't get the odd results, yet if I run with:
`crystal run ... --release` I get different result each time.

**Comment by asterite** [comment]
@marceloboeira I'm getting consistent results every time I run it, with `crystal run ... --release`. What's your OS?

**Comment by marceloboeira** [comment]
@asterite OSX 10.11.2

**Comment by asterite** [comment]
Strange, I'm on OSX 10.11.1, but there shouldn't be a difference.

**Comment by marceloboeira** [comment]
@asterite weird!

**Comment by kirbyfan64** [comment]
@marceloboeira Do you have antivirus on your Mac? Or some sort of file scanner? That could be a culprit.

**Comment by marceloboeira** [comment]
@kirbyfan64 nope, nothing like it.
