### ISSUE TITLE
IniFile should be called INIFile

### ISSUE THREAD

**Issue by EvanHahn** [crystal-lang/crystal#2450]
Per [the coding style document](http://crystal-lang.org/docs/conventions/coding_style.html):

> In class names, acronyms are _all-uppercase_. For example, `HTTP`, and `LibXML`.

By that logic, should `IniFile` be renamed to `INIFile`?

If so, I'm happy to submit a pull request.

**Comment by ozra** [comment]
This is not the right place for me to begin a discussion on it: but I think it would be more readable to have all acronyms simply PascalCased. Everyone knows what Http, Xml, Ini stands for, they're so common they've basically become words - code would be much more readable imo, which is the priority in programming.

**Comment by ozra** [comment]
I opened an issue (#2543) regarding it instead, keeping discussions on point. Sorry about the noise.
