### ISSUE TITLE
Reintroduce, replace or drop comparator for Hash

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#2451]
Extracted from #2443 so we don't forget about it and have a dedicated place to discuss.
#2443 removed the comparator functionality from Hash. Let's decide whether
- we want to change the compiler to make it possible (and fast?) again.
- replace it by a functionally equivalent construct (separate Hash type,  different implementation, different, less problematic interface, ...)
- or conclude that we don't actually need it ever again.

**Comment by asterite** [comment]
Thanks for adding this.

I personally never used Hash's comparator, I don't know if somebody else did. There's also the thing that you can easily achieve the same behaviour by using a struct wrapper as keys, providing custom `==` and `hash` methods (this is what we originally did in `HTTP::Headers`):

```crystal
struct Wrapper
  getter value

  def initialize(@value : String)
  end

  def ==(other : Wrapper)
    value.compare(other.value, case_insensitive: true) == 0
  end

  def hash
    value.downcase.hash
  end
end

a = {} of Wrapper => Int32
a[Wrapper.new("FOO")] = 1
a[Wrapper.new("foo")] = 2

puts a[Wrapper.new("fOo")]
```

More code is involved, but I don't know how frequently you need this feature. Alternatively, a separate Hash type could be added.

**Comment by straight-shoota** [comment]
4 years without any supporting comments might qualify as number 3: "conclude that we don't actually need it ever again."
