### ISSUE TITLE
Capitalization of Acronyms In Types

### ISSUE THREAD

**Issue by ozra** [crystal-lang/crystal#2453]
This is something I've been thinking about for some time, and was reminded by issue #2450.

I think it would be more readable to have all acronyms simply PascalCased. Everyone knows what `Http`, `Xml`, `Ini` stands for. They're so common they've basically become words and have a lot of mind share. Code would be much more readable imo, which is the priority in programming: `AstNode` vs `ASTNode`, etc.

**Comment by jhass** [comment]
Well, this is essentially a duplicate of #279.

**Comment by ozra** [comment]
Ah, I didn't do my homework, thanks @jhass.
