### ISSUE TITLE
Inherit class variable types from ancestor

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/crystal#2458]
As explained in https://github.com/crystal-lang/crystal/pull/2443#issuecomment-209008322 the class variable types aren't inherited by descendants. Here is an example use case from Frost:

```crystal
class Frost::Record
  @@table_name : String

  def self.table_name
    @@table_name ||= name.tableize
  end
end

class User < Frost::Record
end

puts User.table_name # => undefined class variable '@@table_name' of User
```

A workaround is to use macro inherited:

```crystal
class Frost::Record
  macro inherited
    @@table_name : String
  end

  def self.table_name
    @@table_name ||= name.tableize
  end
end
```

**Comment by ruivieira** [comment]
Is this behaviour going to change (i.e. class variables will be inherited)?

**Comment by asterite** [comment]
@ruivieira Class variables defined in a superclass will also be defined in a subclass. Their value won't be shared. This is similar to instance variables.
