### ISSUE TITLE
Observation: confused by code in compiler/crystal/macros/macros.cr

### ISSUE THREAD

**Issue by ozra** [crystal-lang/crystal#2463]
Since I might have misunderstood the workings, I simply report my observation. It might just be the comments confusing me because I consider args with no splat to be "pre-splat", which of course isn't a truth by definition.

According to comment the following should process pre-splat args, but is never run if no splat:

https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/macros/macros.cr#L165

It of course works, because the loop that should do post-splat args will run through the args:

https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/macros/macros.cr#L191

The only difference in practice I guess, is that args ends up in vars after named_args etc. which doesn't change the workings in any way.

Well, better report when confused then not :-)

**Comment by asterite** [comment]
Is there a simpler way to express this logic?

**Comment by asterite** [comment]
I mean, I don't understand what's the problem. A loop for pre-splat args, a loop for splat-args and a loop for post-splat args.

**Comment by ozra** [comment]
No, I got a bit confused about the intentions of the code, so I thought it was better with a checkup than not. I simply expected the first loop to iterate all the args when there was not splat instead of the "post splat args"-loop. Closing.
