### ISSUE TITLE
Compiler crash if redefining c-external function with different signature

### ISSUE THREAD

**Issue by lbguilherme** [crystal-lang/crystal#2468]
```crystal
fun foo(): Int32
  1
end

fun foo(): Int32
  2
end

p foo()
```

This code compiles fine and outputs `2`. (I think it should error, but that's not the problem here).

```crystal
fun foo()
end

fun foo(x : Int32)
end
```

This crashes the compiler.

**Comment by asterite** [comment]
I think the first snippet is OK, it's just like method redefinition.

The second one... should probably error, as C functions can't overload so you are basically breaking (hiding) the previous one. Right?

**Comment by lbguilherme** [comment]
Actually I forgot I had previously defined a function with the same name and was trying to define it to mean something unrelated. So, overloading wasn't the intention.

The problem with silently hiding the previous definition is that it may hide an error such as mine. But, as there is no other way to explicitly replace a previous definition and this behaviour might be useful for some, better to stay with it. With this in mind, maybe in the second example, the function should simply replace the previous definition as if it had never existed.
