### ISSUE TITLE
Undefined local variable or method, when re-using variable from outer module

### ISSUE THREAD

**Issue by waterlink** [crystal-lang/crystal#2472]
Reduced example:

```crystal
module A
  @@value : Int32
  @@value = 41
  
  a_value = @@value
  module B
    @@value : Int32
    @@value = a_value + 1
  end
end
```

In my case `a_value` is actually a temporary variable, that is generated from macro. And I can generate next `@@value` only knowing such a value of outer context.

Crystal version is HEAD, from commit crystal-lang/crystal@49271c355e9eaf750e0b994f5be79d52eea61079

**Comment by asterite** [comment]
Since a few commits a class variable can't be initialized with a local variable. The reason is that class variables are now initialized at the beginning of the program, and "main code" runs later. The `a_value = @@value` bit is considered main code.

I guess you'll have to provide accessor for `A.@@value` and get it when assigning `B.@@value`

**Comment by waterlink** [comment]
But I can't seem to get a hold of `A` class from inside of `B`..

**Comment by waterlink** [comment]
I think I can do that, but with quite a bit of duplication. Will see what I can do.

**Comment by waterlink** [comment]
OK, I've provided a class accessor for each of the module in hierarchy (`context` from `spec2` library).

Duplication reduced by `include ::Spec2::DSL::HasActiveContext` and `macro included` from there.

**Comment by waterlink** [comment]
@asterite Thanks!

**Comment by waterlink** [comment]
@asterite BTW, that is the diff, that I had to do so far for `spec2` to keep up with compiler: https://github.com/waterlink/spec2.cr/compare/issues-with-new-compiler

Now I am investigating, why after this update elapsed time always show `1:00:00 hours`.. If I run the same code with `0.15.0`, it shows correct elapsed time..

**Comment by waterlink** [comment]
@asterite 

Taking the assignment of `@@started_at = Time.now` out of `module` body into a function `def self.record_started_at` and calling it from the global scope (`main`?) fixes the problem.

Sounds like crystal `HEAD` introduces some weird difference to how `main` code inside of module/class body and outside of them is treated, that makes `@@started_at = Time.now` consistently one hour before, what it should be..

**Comment by waterlink** [comment]
That is the part that fixed it: https://github.com/waterlink/spec2.cr/commit/9c83576e997c99a99783d3b878fe65b3617fc535#diff-cac1c89cdcd8d47aa94eab6ae60b5cbdL30

**Comment by asterite** [comment]
Hmmm... the time for `@@started_at` shouldn't change, at least not that much. Do you have a small code to reproduce the problem? I tried this:

```crystal
class Foo
  @@started_at : Time
  @@started_at = Time.now

  def self.started_at
    @@started_at
  end
end

pp Time.now
pp Foo.started_at
```

And I get the same value in both cases.

**Comment by asterite** [comment]
I will document the changes regarding class variables for the next release, as well as the new type inference rules. The idea is that class variables assignments at the class level are executed at the beginning of the program, just like any other statically typed languages like Java, C#, Rust, Go, etc. Running them only when the compiler reaches that point, as if it were main code, is a behaviour we aren't sure we want to keep from Ruby, specially when we'll make class variables also be present in subclasses.

**Comment by waterlink** [comment]
@asterite I can reproduce that. Seems like `at_exit` is a culprit:

```crystal
class Foo
  @@started_at : Time
  @@started_at = Time.now

  def self.started_at
    @@started_at
  end
end

pp Time.now
pp Foo.started_at

at_exit do
  pp Time.now
  pp Foo.started_at
end
```

Output on `0.15.0`:

```
Time.now = 2016-04-17 22:50:10 +0100
Foo.started_at = 2016-04-17 22:50:10 +0100
Time.now = 2016-04-17 22:50:10 +0100
Foo.started_at = 2016-04-17 22:50:10 +0100
```

Output on `HEAD`:

```
Time.now = 2016-04-17 22:50:07 +0100
Foo.started_at = 2016-04-17 21:50:07 +0100
Time.now = 2016-04-17 22:50:07 +0100
Foo.started_at = 2016-04-17 21:50:07 +0100
```

Last case have this one hour difference between `Foo.started_at` and `Time.now`.

**Comment by waterlink** [comment]
And something is weird. My clock shows `23:51` at the moment. Why Crystal claims it is `22:51 +0100` ? Do I misunderstand something?

**Comment by waterlink** [comment]
System timezone is correct (Europe/Berlin).

**Comment by asterite** [comment]
Strange, I can't reproduce it, and I tried changing my timezone too. Maybe it's related to #858, though it's strange that it works well in 0.15.0.

**Comment by ysbaddaden** [comment]
Yes, the one hour difference is due to DST (daylight saving time) not being applied,
