### ISSUE TITLE
Handler pointers with "inheritance"

### ISSUE THREAD

**Issue by jreinert** [crystal-lang/crystal#2475]
I bumped into this problem working with gobject generated c bindings from c++. I have functions returning a handle `LibFoo::Foo*` and others returning a handle `LibFoo::Bar*`. `LibFoo::Bar` represents a subclass of `LibFoo::Foo`. To map this in crystal i define the classes `Foo` and `Bar` that call the lib functions to set an instance variable `@handle` to the returned handle. The classes define the method `to_unsafe` so that `@handle` is cast to the correct pointer type. This fails with crystal 0.15.0 as well as latest HEAD for different reasons:

0.15.0:
```
foo.to_unsafe
    ^~~~~~~~~

in ./pointer_cast.cr:15: can't cast (Pointer(LibFoo::Bar) | Pointer(LibFoo::Foo)) to Pointer(LibFoo::Foo)

    @handle as LibFoo::Foo*
    ^
```

HEAD:
```
Error in ./pointer_cast.cr:30: instantiating 'Bar:Class#new()'

bar = Bar.new
          ^

instantiating 'Bar#initialize()'

in ./pointer_cast.cr:21: instance variable '@handle' of Foo must be Pointer(LibFoo::Foo), not Pointer(LibFoo::Bar)

    @handle = LibFoo.bar(nil, 1)
              ^
```

@jhass and @BlaXpirit already pointed out that using `alias` instead of `type` fixes the errors but IMHO it doesn't feel right and violates the liskov substitution principle. Would be cool to have somekind of one-way alias maybe that would address this kind of problem.

Here's a minimal example demonstrating the Problem:

```crystal
lib LibFoo
  type Foo = Void
  type Bar = Void
                           
  fun foo = malloc(size : Int32) : Foo*
  fun bar = realloc(foo : Foo*, size : Int32) : Bar*
end
                                               
class Foo
  def initialize                                   
    @handle = LibFoo.foo(1)                        
  end                                              
                                                   
  def to_unsafe                                    
    @handle as LibFoo::Foo*                        
  end                                              
end                                                
                                                   
class Bar < Foo                                    
  def initialize                                   
    @handle = LibFoo.bar(nil, 1)                   
  end                                              
                                                   
  def to_unsafe                                    
    @handle as LibFoo::Bar*                        
  end                                              
end                                                
                                                   
foo = Foo.new                                      
bar = Bar.new                                      
                                                   
foo.to_unsafe                                      
bar.to_unsafe                                 
```

**Comment by asterite** [comment]
This is the same as #2460, so a duplicate. `Bar` should have a `LibFoo::Foo*` for `@handle`, so the same instance variable, and you would cast it to `LibFoo::Bar*` when needed.

Basically, change Bar's initialize to:

```crystal
def initialize
  @handle = LibFoo.bar(nil, 1) as LibFoo::Foo*
end
```

In C there's no such thing as pointer inheritance. I'd like to see the real C code behind this, and how you are translating it to Crystal. There are also no pointer unions in C.

**Comment by asterite** [comment]
Oh, and `Bar#to_unsafe` should return `LibFoo::Foo*`. Basically, always work with the most general pointer type, and only cast to the more specific pointer type when passing it to C. Keeping that type info on Crystal's side isn't of much use.
