### ISSUE TITLE
private method cant be called recursively

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#2484]
```crystal
struct Int32
  private def bla
    if self == 0
      0
    else
      (self - 1).bla + self
    end
  end

  def blah
    bla
  end
end

p 10.blah
```

```
in ./1.cr:6: private method 'bla' called for Int32

      (self - 1).bla + self

```

**Comment by asterite** [comment]
`private` methods can only be invoked without an explicit receiver (for example doing `bla`). If you do `exp.bla` and `bla` is a private method you'll get an error. You can use `protected` for that.

See http://crystal-lang.org/docs/syntax_and_semantics/visibility.html
