### ISSUE TITLE
Unexpected invalid memory access error

### ISSUE THREAD

**Issue by ethe** [crystal-lang/crystal#2493]
See https://play.crystal-lang.org/#/r/xbf
On my computer I got below error
```
 ➜  crystal untitled.cr
Invalid memory access (signal 11) at address 0x0
[4358469] *CallStack::print_backtrace:Int32 +117
[4346696] __crystal_sigfault_handler +56
[4475304] sigfault_handler +40
[139778937277712] ???
[4465951] *Env +383
[4466401] *Closure +145
[4466246] *Closure +6
[4437894] *IO::FileDescriptor +22
[4437848] *IO::FileDescriptor +24
[4348496] *puts<Closure>:Nil +80
[4340600] ???
[4348233] main +41
[139778929064512] __libc_start_main +240
[4337337] _start +41
[0] ???

 ➜  uname --all 
Linux go 3.19.0-30-generic #34-Ubuntu SMP Fri Oct 2 22:08:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

 ➜  crystal -v
Crystal 0.15.0 [0f62400] (Fri Apr  1 17:22:17 UTC 2016)


```

**Comment by ozra** [comment]
Might add that crystal 0.15 segfaulted compiling a project of mine, but when using master HEAD it worked fine.

**Comment by jhass** [comment]
I reproduced this one on HEAD (albeit with a shorter stacktrace for some reason).

**Comment by asterite** [comment]
This is because the size of `Closure` can't be computed... or maybe yes, I'm not sure. I'll investigate. As a workaround, making `Closure` a class works.

**Comment by ethe** [comment]
@asterite In this case, if do not assign instance of Closure to a variable, just `puts Closure.new([] of Exp, Env.new([] of EnvPair))`, everthing works well.

**Comment by asterite** [comment]
I managed to reduce it even further:

```cr
struct Closure
  @env : Env?
end

class Env
  @env : Pointer(Int32 | Closure)?
end

Closure.new
```

It can be compiled with `--prelude=empty`. But the strange this is that it fails randomly:

```
$ crystal c bar.cr --prelude=empty 
$ ./bar 
$ crystal c bar.cr --prelude=empty 
$ ./bar 
$ crystal c bar.cr --prelude=empty 
$ ./bar 
Illegal instruction: 4
```

I have no idea what's going on, it could be an LLVM bug.
