### ISSUE TITLE
Force to declare types in methods definitions and return types

### ISSUE THREAD

**Issue by mrkaspa** [crystal-lang/crystal#2497]
I think types in methods helps to document and understand better the code and will make the compiler to be faster, duck typing is hard to mantain an for implementing this it can be used the GoLang approach of interfaces.

```crystal
class Array(A)
  def map(f : A -> B) : Array(B)
  end
end
```

It's easier to understand and will avoid the compiler slow performance problems

**Comment by kirbyfan64** [comment]
Pretty sure this violates this goal:

> Statically type-checked but without having to specify the type of variables or **method arguments**.

**Comment by mrkaspa** [comment]
I read another thread to force to declare the type of the instance variables to make the compiler faster so that goal is gonna be violated.

**Comment by kirbyfan64** [comment]
Not really. That's a comparatively minor change compared to this.

**Comment by ozra** [comment]
Ooops, I added a thumbs up a bit to quickly, clarification:
I think this is _good practice_ for all methods in stdlib.
I think this is _bad baaad_ as a requirement in the language!

**Comment by lbguilherme** [comment]
> It's easier to understand and will avoid the compiler slow performance problems

This is not actually true. With the change to force typing global/class/instance vars, the compilation time is now basically linear on the number of methods and allows for caching of type inferences. I don't think there is an advantage performance-wise to force types on arguments and returns.

And most importantly: this is one of the nicest characteristics of Crystal, the global type inference.
Although I agree it is good *for the stdlib*, and the only reason is for documentation (and better errors).

**Comment by mrkaspa** [comment]
Well it'll be good to leave it as optional if there is no performance problems, personally I'll use types, it is a matter of taste. It'll be good to suggest use types for third party libraries and use it in the stdlib

**Comment by asterite** [comment]
Forcing types on methods will actually slow down things and will necessarily make the language mrore complex. Check for example this:

```crystal
def max(x, y)
  x > y ? x : y
end
```

First, what are the types of `x` and `y`? You will need to do `x : T` and then introduce the idea of interfaces/protocols and have types implement them, etc. When invoking such method that compile will have to check that all of that is satisfied. Now it's just about searching the `>` method in `x` and if that succeeds the method can be typed.

So although adding type annotations is probably good for documentation and cleaner errors, we will never make them mandatory.
