### ISSUE TITLE
Modules and calling external methods

### ISSUE THREAD

**Issue by mrkaspa** [crystal-lang/crystal#2498]
Calling this

```crystal
module XD
  abstract def xd

  def xd1
    xd0 #looks this method
    xd
  end
end

class XX
  include XD

  def xd
    puts "demo"
  end
end
```

I think it's better and typesafe doing something like this

```crystal
module XXD
  abstract def xd0
end

module XD
  include XXD
  abstract def xd

  def xd1
    xd0
    xd
  end
end

class XX
  include XD

  def xd
    puts "demo"
  end

  def xd0
  end
end
```

**Comment by jhass** [comment]
I for one don't follow at all what you're proposing.

**Comment by mrkaspa** [comment]
I mean in the first code the compiler has to look if the class of the object in the hierarchy has implemented the xd0 method, this has to be expensive in a bigger project. Instead the module XD needs to use a method (xd0) required in another module(XXD) so the module includes the other module that way the class that includes it should implement both. Actually both codes works, but I think the second one is easier to compile and more typesafe.

**Comment by jhass** [comment]
Did you mean to implement `xd0` in `XX` in the first example too?

**Comment by mrkaspa** [comment]
@jhass to force to implement it, have you checked Scala traits?, it's a good approach to implement typesafe mixins.

**Comment by ozra** [comment]
Eh? Why not just `abstract def xd0` in XD?

**Comment by asterite** [comment]
Forcing declaring abstract methods goes against quick prototyping. As for type safety and errors, they are the same if we force defining abstract methods that if we don't.

**Comment by asterite** [comment]
And it's also not true that it will be faster to compile. If you have a module as a restriction you just have to check that the given type includes it, without having to check what methods it has. The method is only searched when needed, which you are going to do anyway once that method is invoked.
