### ISSUE TITLE
Distribution of crystal in Debian (/Ubuntu ?) official releases

### ISSUE THREAD

**Issue by olbat** [crystal-lang/crystal#2499]
Hello,

For the moment crystal can be installed on Debian based systems using the package available on 
[crystal-lang APT repository](http://crystal-lang.org/docs/installation/on_debian_and_ubuntu.html).
I think that someday, the software will [be integrated](https://www.debian.org/doc/manuals/distribute-deb/distribute-deb.html#adding-packages-to-debian) distribution's [official package management systems](https://www.debian.org/distrib/packages) so I took some time to check the current .deb packaging and tried to improve it a little bit.

For the moment, the archive -that seems to be generated using [Omnibus](https://github.com/chef/omnibus-chef)- is working properly and allow to install and use the crystal tools. On the other hand, regarding to [official packaging policies](https://www.debian.org/doc/debian-policy/), I don't think it's "clean enough" to be integrated in the Debian -or [Ubuntu](http://people.canonical.com/~cjwatson/ubuntu-policy/policy.html/)- distribution.

So, I've built a new crystal package from scratch trying to respect Debian's packaging policy.
What I worked on is available in this repository: https://github.com/olbat/debian-crystal/ .

It allows to build Crystal 0.15.0 from a Debian/stretch (testing) machine (stable does not have libgc >= 7.4). All the build-dependencies have been set in the [control file](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-sourcecontrolfiles), do you think you can find the time to check them ?

I also opened a [Request For Package](https://www.debian.org/devel/wnpp/) on Debian's bugtracker to initiate the work -and also since finding a maintainer can take time: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822275 .
_I don't know that much about Ubuntu, but if you find the idea interesting, someone may open a RFP  (or similar) on their tracker's too ?_

I'm currently working on writing a Dockerfile to automate the building task, don't hesitate to give me your feedbacks !

**Comment by lbguilherme** [comment]
Noobie question ahead:

As Ubuntu uses Debian as a base distribution, doesn't being accepted in Debian's package repository implies being available in ubuntu too (in a future release)?

**Comment by jhass** [comment]
Another consideration is that the language and thus its community is still moving very fast. Being accepted into Debian and getting into a stable Debian release subsequently, will mean Debian users using the official repository will be stuck on an old Crystal version that's incompatible with the rest of the ecosystem very quickly. Same basically applies to Ubuntu.

I appreciate your effort but I feel like it might come a bit too early still.

**Comment by jhass** [comment]
That said maintaining a Ubuntu PPA that doesn't has to comply to Debian's stability policy, using non Omnibus but hand-crafted packages can be a worthwhile effort, exploring things packaging best practices for Crystal (see for example the route we took in the Archlinux packages) or  compatibility considerations for Crystal (see for example #1614), so that we catch these things early on and don't head into a direction that'll later makes it impossible to include Crystal into mainstream distributions, once it stabilizes.

**Comment by olbat** [comment]
I understand, in fact I do not really know the state of the project yet, it's probably a bit too early :)

BTW the you'll want the project to be distributed into Debian or Ubuntu, do not hesitate to look into [the repository](https://github.com/olbat/debian-crystal/) I worked on to have something to start with.

_Another thing that you may want take in consideration: some distributions have long release cycles and no new packages are added to stable releases so you have to wait for the next one.
For example the next [Debian/stable](https://wiki.debian.org/DebianStretch
) is planed for Q1 2017, the one after this one will probably be in 2019._

**Comment by olbat** [comment]
I'm done working on the [docker image](https://hub.docker.com/r/olbat/debian-crystal/) that allow to build crystal and it's Debian package (see [Dockerfile](https://github.com/olbat/debian-crystal/blob/master/Dockerfile.debian-build)). [As you can see since build dependencies are given in the package (the _debian/control_) file, it's much easier to install them using _mk-build-deps_ or _apt-get build-dep_]

You can build the .deb archive using the docker image by doing `docker run --rm -v ${PWD}:/src/crystal olbat/debian-crystal` (generated files will be copied into the repository's directory).

I tried to rebuild a new crystal package using the version of crystal that I compiled, it worked like a charm.

One last thing, during the build I got some warnings about program's linking with shared libraries that you may find interesting:
```
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/crystal/usr/bin/crystal was not linked against libedit.so.2 (it uses none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/crystal/usr/bin/crystal was not linked against libffi.so.6 (it uses none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/crystal/usr/bin/crystal was not linked against librt.so.1 (it uses none of the library's symbols)
```

**Comment by asterite** [comment]
I'd prefer to wait until we start distributing official packages for some distros. For now, I think it's better to move this discussion to a place like Google Groups, because there's nothing we'll do about this right now.
