### ISSUE TITLE
cannot init a global var inside a method

### ISSUE THREAD

**Issue by alainravet** [crystal-lang/crystal#2500]
contrived example:
```
def foo
  $a = 1
  b  = $a -1 # undefined method '-' for Nil (compile-time type is Int32?)
end

foo
```

**Comment by asterite** [comment]
Between `$a = 1` and the next line, the code could jump to a different thread and reset `$a` to `nil` (it's typed as nil because `foo` could be called conditionally and we don't know if `$a` will ever be assigned a value). You'll have to use a local variable:

```crystal
def foo
  $a = a = 1
  b  = a -1
end

foo
```

**Comment by alainravet** [comment]
> Between $a = 1 and the next line, the code could jump to a different thread and reset $a to nil

@asterite The same reasoning could be applied to the following code, but it doesn't trigger an error this time:

```
$a = 10
def foo
  b  = $a - 1
end

puts foo # => 9
```

**Comment by waterlink** [comment]
Since `$a = 1` is at global scope, it will force `$a` to have type `Int32`, not `Int32|Nil` as in original case. Therefore it works correctly. Still value of `$a` can be changed by other Fiber, but it can't be `Nil` anymore.

**Comment by alainravet** [comment]
@waterlink in the original example, `$a` is also initialized with `1` (it didn't exist before that point), so it should set/restrict its type to Int32 too, shouldn't it!?

**Comment by alainravet** [comment]
```
def foo
  $a = a = 1
  b  = a -1
end

def bar
  $a = "0"
end

foo; puts $a.inspect  # 0
bar; puts $a.inspect  # "0" 
```

**Comment by ssvb** [comment]
@alainravet Try to ``puts typeof($a)`` to see what kind of type is assigned to it. In your last example it is a union of ``(Int32 | String | Nil)``.

**Comment by waterlink** [comment]
> $a is also initialized with 1 (it didn't exist before that point

Every global variable, that is referenced from anywhere in the program, always exists. If it is assigned value at global scope => it can't be nil; if it is not assigned at global scope => it can be nil.

**Comment by alainravet** [comment]
@ssvb I'm not sure it makes the most sense in all cases.
I know the doc says it is the expected behaviour, but 'm a little confused by this :
```
$a = 2
$a = "0"
puts "$a = #{typeof($a)}" # (Int32 | String)

def foo
  a = 1
  a = "1"
  puts "a  = #{typeof(a)}" # String
end

class Bar
  def bar
    @a = 1
    @a = "1"
    puts "@a = #{typeof(@a)}" # (Int32 | String | Nil)
  end
end

foo
Bar.new.bar

# =>
#   $a = (Int32 | String)
#   a  = String
#   @a = (Int32 | String | Nil)
```

**Comment by waterlink** [comment]
Local variables inside one function can not be used or mutated by some other Fiber (kind of like lightweight threads). Instance variables, class variables and global variables can be accessed and mutated from other Fiber (concurrently).

Therefore, compiler can figure out the type of local variable precisely. It has to make a union out of global and instance variables.

**Comment by waterlink** [comment]
Example:

```crystal
spawn { $a = 3 }
spawn { $a = "hello world" }
spawn { $a = 37.55 }

typeof($a) # => Int32|Float64|String|Nil
```

**Comment by alainravet** [comment]
@waterlink the fact that global variables collect all the possible types, including Nil, is annoying in cases like this : 
(2 binaries are compiled from `a`+`common` and `b`+`common`; `a` and `b` are exclusive)

```
# file a.cr
require "logger"
$logger = Logger.new(STDOUT)

require "./common"
Foo.new.foo
```

```
# file b.cr
require "./common"
Foo.new.foo
```

```
# file common.cr
require "logger"
$logger ||= Logger.new(STDOUT)

class Foo
  def foo
    $logger.info("in foo") # ERROR : undefined method 'info' for Nil (compile-time type is Logger?)
  end
end
```


More confusingly, this workaround fails too
```
    ...
    if $logger
      $logger.info("in foo") # ERROR : undefined method 'info' for Nil (compile-time type is Logger?)
    end
```

**Comment by ssvb** [comment]
Your workaround should use a local variable because of the reasons explained by @waterlink (your ``if`` expression is racy and does not prevent some other fiber from unexpectedly modifying $logger before you try to use it). Check the bottom of http://crystal-lang.org/docs/syntax_and_semantics/if_varis_a.html for some explanations.

**Comment by alainravet** [comment]
@ssvb I get it now; I should have written 
```
    if l = $logger
      l.info("in foo") 
    end
```

**Comment by ssvb** [comment]
In general, relying on global variables too much is a bad idea. Even if we only look at the performance alone, they are slower than local variables in compiled languages: http://stackoverflow.com/questions/15216279/global-variables-slow-down-code

The Crystal compiler being anal about global variables is not necessarily a bad thing because this discourages the use of inefficient and error prone code. And if you don't care about the performance too much, then you can always use Ruby.

**Comment by alainravet** [comment]
@ssvb no difference measured in the code below : 

```
require "logger"
$log = Logger.new(File.new(File.expand_path("debug1.log"), "w"))


log = Logger.new(File.new(File.expand_path("debug2.log"), "w"))


require "benchmark"
Benchmark.ips do |x|
  x.report("local var" ) {  log.debug "1" }
  x.report("global var") { $log.debug "1" }
end

# local var 289.79M (± 8.65%)       fastest
# global var 288.82M (± 8.62%)  1.00× slower

```

**Comment by asterite** [comment]
We'll probably remove global vars from the language anyway, so don't use them too much.
