### ISSUE TITLE
global var error when `||=` is used

### ISSUE THREAD

**Issue by alainravet** [crystal-lang/crystal#2501]
example:
```
require "logger"

$log ||= Logger.new(STDOUT) 
$log.debug "xx"  # ERROR: undefined method 'debug' for Nil
```

probably related to #2500, #2487

**Comment by asterite** [comment]
Invalid because of the same reason as #2500 (well, similar, here $log is initialized conditionally so it's type includes nil and we don't know when it's nil or not). Use a local varaible too here.
