### ISSUE TITLE
Playground reports "Index out of bounds" at wrong location

### ISSUE THREAD

**Issue by gerrywastaken** [crystal-lang/crystal#2504]
Given the following code, the playground reports an "Index out of bounds" at the
`names = names(full_name)` line, when the out of bounds issue is actually at the 
`firstname, lastname = full_name.split` line.

```
names = [
  "john smith",
  "jane"
]

names.each do |name|
  parse(name)
end

def parse(full_name)
  names = names(full_name)
  if names[:lastname]
    puts "#{names[:lastname]}, #{names[:firstname]}"
  else
    puts names[:firstname]
  end
end

def names(full_name)
  firstname, lastname = full_name.split
  {
    firstname: firstname,
    lastname: lastname
  }
end
```

Also I was wondering, with the stack trace...:
```
smith, john
Index out of bounds (IndexError)
[4525268386] *CallStack::unwind:Array(Pointer(Void)) +82
[4525268289] *CallStack#initialize<CallStack>:Array(Pointer(Void)) +17
[4525268248] *CallStack::new:CallStack +40
[4525283593] *Exception@Exception#initialize<IndexError, String>:CallStack +41
[4525283517] *IndexError#initialize<IndexError, String>:CallStack +29
[4525283460] *IndexError::new<String>:IndexError +100
[4525283340] *IndexError::new:IndexError +28
[4525360689] *Array(String)@Array(T)#at<Array(String), Int32>:String +97
[4525360585] *Array(String)@Array(T)#[]<Array(String), Int32>:String +9
[4525241711] *names<String>:Hash(Symbol, String) +1215
[4525236659] *parse<String>:Nil +51
[4525219662] __crystal_main +39550
[4525231880] main +40

exit status: 1
```
This does list the `names` method, but I have no idea what the +1215 represents as it isn't a line number. I couldn't spot a docs page for the call stacks. Is there anywhere I can read up more on this format?

**Comment by asterite** [comment]
The line:

```crystal
firstname, lastname = full_name.split
```

is eventually transformed by the compiler to:

```crystal
tmp = full_name.split
firstname, lastname = tmp[0], tmp[1]
```

The playground instruments the original code by transforming it to this:

```crystal
firstname, lastname = instrument(full_name.split)
```

The compiler then transforms it to:

```crystal
tmp = instrument(full_name.split)
firstname, lastname = tmp[0], tmp[1] # the failure happens at this line, not instrumented
```

I don't think there's a way to improve this right now without having a way to hook into the compiler's transformation code... I'm also not sure it's very important, the playground shows more information that the real code (line numbers for exceptions), while real code lacks this for now (see #1270).

In a way, that the exception is shown at a "near-correct" location in the playground but not in "real life" is an anti-feature, because it makes you think that real code will also be that nice (your expectations)... but it's a nice feature indeed.

**Comment by gerrywastaken** [comment]
So if I understand correctly. The instrumentation knows there was an issue inside the names method, but doesn't know where, so instead reports the issue at the point where the call to that method is made.

If this is the case, then I think error should reflect that.

Currently you can end up with very confusing results. In the example here you see an array of two elements being passed back from split_names, but the playground tells you you have an index issue when trying to destruct into two variables. I've made this example deliberately trivial, but in a more complex scenario this could lead to many hours of searching for a bug in the wrong place.

![screen shot 2016-04-24 at 2 49 06 pm](https://cloud.githubusercontent.com/assets/71481/14765595/e64940d6-0a2b-11e6-8ce3-723c9bd583d0.png)

Is it possible for the error to read  `"Index out of bounds" found within call to split_names` as this would be far less misleading.
