### ISSUE TITLE
Peculiar error with master HEAD : "CSV is not a class..."

### ISSUE THREAD

**Issue by ozra** [crystal-lang/crystal#2507]
```
$ bin/crystal docs
Using compiled compiler at .build/crystal
Error in ./src/csv/csv.cr:58: CSV is not a class, it's a module

class CSV
      ^
```

**Comment by asterite** [comment]
Yes, `crystal docs` just requires everything from "src", but for the standard library that's not good. In this case "csv/lexer/io_based.cr" will be required first and declare CSV as a dmoule.

Running "make doc" works as expected.
