### ISSUE TITLE
Build flags to specify extra import paths

### ISSUE THREAD

**Issue by teodor-pripoae** [crystal-lang/crystal#2516]
Hi,

I'm using the `crystal-linter` plugin for atom. When I'm editing a file with imports only from standard library it works fine but it seems it does not work when I'm importing something from a shard.

I think the compiler is looking for `.shards` directory in the current workdir. Is this correct ?

Are there any build flags to specify extra import paths ? Something like:

```
crystal build --import-path=/path/to/my-project/.shards file.cr
```

**Comment by asterite** [comment]
The default search path (env variable CRYSTAL_PATH) is set to `src`, `libs` and the standard library. I guess crystal-linter should invoke `crystal build` with a similar CRYSTAL_PATH. I guess this is an issue to report to crystal-linter.

**Comment by teodor-pripoae** [comment]
Thank you @asterite 

I [asked](https://github.com/atom-crystal/linter-crystal/issues/19) on the crystal-linter issue tracker and the author does not have a proper solution, as well. I asked here about the compile flags so I can point it here in the original issue.

I think we can close this issue now.
