### ISSUE TITLE
multiline expressions with backslash don't support eol comments

### ISSUE THREAD

**Issue by alainravet** [crystal-lang/crystal#2517]
You can write this

```
a = 1000 \
     + 2 \
     - 3
```

but not this  (`"unknown token ' '"`)

```
a = 1000 \  # base price
     + 2 \  # supplement for dog
     - 3    # discount for cat
```

**Comment by asterite** [comment]
No, the backslash must immediately be followed by a newline and that means it's a line continuation. The above is pretty confusing and no other language does that (neither C, nor Ruby nor Elixir)

You can write:

```crystal
a = 1000 + # base price
     2 -   # supplement for dog
     3     # discount for cat
```

And there's no need to use backslash there.
