### ISSUE TITLE
HEAD crystal can't handle inference for itself after...

### ISSUE THREAD

**Issue by ozra** [crystal-lang/crystal#2519]
@channel seems to be wrongly inferred to Channel

Suspect it's after 007e8d5004b9dc4da3137378d7fd069c6efcfcb0

```
[...cut out trace...]

instantiating 'Process#initialize(String, Nil, Nil, Bool, Bool, Bool, Bool, Bool, Nil)'

in ./src/process/run.cr:89: instantiating 'channel()'

        spawn { copy_io(input, process_input, channel, close_dst: true) }
                                              ^~~~~~~

in ./src/process/run.cr:182: instance variable '@channel' of Process must be Channel(Exception+?)?, not Channel::Unbuffered(Exception+?)

    @channel ||= Channel(Exception?).new
    ^~~~~~~~
```

**Comment by kirbyfan64** [comment]
@ozra You should probably surround `@channel` with backticks, since you just accidentally pinged the corresponding GitHub user....

**Comment by asterite** [comment]
@ozra I'm always very careful to avoid the situation where an old compiler can't compile a new one. I'm doing `make clean crystal spec` and it works fine, and travis is also successful, so travis can build HEAD. What command are you invoking to get to this situation?

**Comment by ozra** [comment]
This is my bad, too quick to issue, I'll close, it's likely only when using a _slightly older_ HEAD-compiler I didn't compile with the released one.
