### ISSUE TITLE
Compiler crash with "Index out of bounds" when passing out of scope var with multiple splat args

### ISSUE THREAD

**Issue by Perelandric** [crystal-lang/crystal#2521]
When the `test_func` is invoked with a variable that is defined in a nested scope, and with 2 or more args passed to a splat parameter, the compiler crashes.

>Index out of bounds
[141067459] ???
[141065452] ???
...
[135872487] ???
[142594772] main +52
[3072046375] __libc_start_main +247
[135848434] ???

https://play.crystal-lang.org/#/r/xlm

``` crystal
class Test
  def start()
    if true
 	  val = ""
    end
    
    test_func(val, 1, 2)
  end
  
  def test_func(a : String, *b)
  end
end

Test.new.start()
```

 - If the `val` is defined in the same scope, there is no crash or error.

 - If only one arg is passed to the splat param, or if the splat param and args are removed, the compiler does not crash, but gives an error that an overload couldn't be found.

>Crystal 0.15.0 [0f62400] (Fri Apr  1 17:22:17 UTC 2016)

---

*EDIT: Simplified the example a little.*

---

*Additional note:* It doesn't crash if the explicit `: String` is removed from the `a` param.

**Comment by asterite** [comment]
Good catch. Thank you for reducing this :-)

**Comment by Perelandric** [comment]
Thanks @asterite... you're quick!
