### ISSUE TITLE
Why mandatory arguments can not be passed as named arguments?

### ISSUE THREAD

**Issue by greyblake** [crystal-lang/crystal#2528]
Hi! According to the [doc](http://crystal-lang.org/docs/syntax_and_semantics/default_and_named_arguments.html)
Crystal supports named arguments, but only for named arguments. It looks a bit inconsistent to me. Why mandatory 
arguments can not be passed as named arguments as well? Is there a special reason for this? Unless it is, would be 
really cool to be able to pass all arguments as named arguments (like currently in Ruby)

Here is an example that illustrates the situation:

```crystal
def sum(a, b = 1)
  a + b
end

# default b
sum(5)        # => 6

# b is passed
sum(5, 2)     # => 7

# b is passed as a named argument
sum(5, b: 3) # => 8

# a can not be passed as a named argument
sum(a: 5, b: 3)
# =>
#   wrong number of arguments for 'sum' (given 0, expected 1..2)
#   Overloads are:
#    - sum(a, b = 1)
```

Thanks!

**Comment by kumpelblase2** [comment]
See #560 and #1064 .

**Comment by greyblake** [comment]
@kumpelblase2 Thanks!  I was looking for those issues, but haven't found them. I'll close this one then)
