### ISSUE TITLE
No overload matches with subtype

### ISSUE THREAD

**Issue by teodor-pripoae** [crystal-lang/crystal#2532]
Hi

I have the following code:

```crystal
require "json"

def test_method(ids : Array(String), options : Hash(String, JSON::Type))
  options.merge({"ids": ids})
end

puts test_method(["123", "456"], {"asdf": "foo", "data": {"a": "b"}})
```

Since `Hash(String, Hash(String, String) | String)` is a subtype permitted by `JSON::Type`, it should work.

I'm getting this error:

```
Error in ./test.cr:7: no overload matches 'test_method' with types Array(String), Hash(String, Hash(String, String) | String)
Overloads are:
 - test_method(ids : Array(String), options : Hash(String, JSON::Type))

puts test_method(["123", "456"], {"asdf": "foo", "data": {"a": "b"}})
```

**Comment by asterite** [comment]
The answer is: it depends.

Consider this:

```crystal
def foo(x : Array(String | Int32))
end

a = Array(Int32).new
foo(a)
```

Should it compile? Well, if we only read from `x` then the answer is yes. If we write to `x` then probably no (we wouldn't want to insert a string inside an array of ints). 

There's a tracking issue for covariance and contravariance, #1297. I'll close this in favor of that one. Until we resolve what to do with this no sane behaviour can be expected from this. Your best option right now is to either don't use a type annotation, or type the hash as the property type:

1.

```crystal
require "json"

def test_method(ids, options)
  options.merge({"ids": ids})
end

puts test_method(["123", "456"], {"asdf": "foo", "data": {"a": "b"}})
```

2.

```crystal
require "json"

def test_method(ids : Array(JSON::Type), options : Hash(String, JSON::Type))
  options.merge({"ids": ids} of String => JSON::Type)
end

puts test_method(
  ["123", "456"] of JSON::Type,
  {
    "asdf": "foo" as JSON::Type,
    "data": {"a": "b"} of String => JSON::Type,
  } of String => JSON::Type)
```
