### ISSUE TITLE
Add `Time#iso_year_and_week`

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#2533]
We need a `Time#iso_year_and_week : {Int32, Int32}` method that returns a tuple with the [iso week and date](https://en.wikipedia.org/wiki/ISO_week_date). Then, we can also have `Time#iso_week` and `Time#iso_year` that would return each component of that tuple. Then use the same time format flags as [Ruby's strftime](http://ruby-doc.org/core-2.2.0/Time.html#method-i-strftime) for iso week: 

```
%G - The week-based year
%g - The last 2 digits of the week-based year (00..99)
%V - Week number of the week-based year (01..53)
```

The problem is I can't find an official definition of algorithm for this. I _could_ copy [Go's source code](https://golang.org/src/time/time.go?s=10978:11018#L319) for this, which is pretty clear, or some other language's soruce code, but I don't know if we'll be violating some copyright. The thing is, the algorithm is an ISO standard and so I'm not sure if copying such code would be infringing something.

**Comment by lbguilherme** [comment]
How would `time.iso_year_and_week` be better than explicitly `{time.iso_year, time.iso_week}`?

**Comment by asterite** [comment]
@lbguilherme When you compute one you get the other one for free (they are related). And when you need one you usually need the other.

**Comment by skunkworker** [comment]
@asterite would you want this in `formatter.cr` or `time.cr`? Looking at ruby's implementation it looks like `formatter.cr` would be the one, is this correct?

**Comment by asterite** [comment]
@skunkworker In Time first, then formatter would use it

**Comment by luislavena** [comment]
In relation to the copyright note, Wikipedia includes now the calculations necessary (with examples) to obtain the ISO values: https://en.wikipedia.org/wiki/ISO_week_date#Calculation
