### ISSUE TITLE
Change `to_s` of Slice and StaticArray to show the type

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#2540]
Right now `Slice#to_s` and `StaticArray#to_s` behave like `Array#to_s` so it's hard to distinguish what's the type behind the output. For other types, the class name is included:

https://play.crystal-lang.org/#/r/xsb

Should we change `Slice#to_s` and `StaticArray#to_s` to include the class name? I'd like to do it, but I'd like to know your opinion too.

The idea would be to generate strings like:

```crystal
Slice[0, 0, 0]
StaticArray[0, 0, 0]
```

**Comment by bcardiff** [comment]
It would be great if it would be valid crystal code, whatever syntax is chosen,

**Comment by lbguilherme** [comment]
Isn't it more like a task for `inspect`? To produce an unambiguous description of the object, if possible with valid Crystal syntax.

By the way, `Slice{0, 0, 0}` and `StaticArray{0, 0, 0}` are almost valid syntaxes. Slice needs a constructor taking a size, which will be used in Pointer.malloc. And for StaticArray, it could be interesting if the syntax sugar could detect that it has two generic arguments, and assume the second one is the size.

**Comment by bcardiff** [comment]
Yes @lbguilherme it is more a `inspect` thing to be crystal code. But I would only differentiate `to_s` from `inspect` if needed or if human representation is a bit too far from crystal code. 

In collections, I would _maybe_  add ellipsis  if there are way to many elements, otherwise I would use the same format as inspect.

**Comment by asterite** [comment]
I made this change. Now the standard library also allows you to do this:

```crystal
Slice[1, 2, 3]
StaticArray[1, 2, 3]
```

so the `to_s` generates something that is valid crystal code :-)
