### ISSUE TITLE
responds_to? errors the playground

### ISSUE THREAD

**Issue by Fryguy** [crystal-lang/crystal#2545]
Example script:

```crystal
x = "1"
puts "Hi" if x.responds_to?(:gsub)
```

showing the following in the console in verbose mode:

```text
$ crystal play -v
Listening on http://localhost:8080
I, [2016-05-02 14:46:10 -0500 #53681]  INFO -- : /client WebSocket connected as session=1
I, [2016-05-02 14:46:10 -0500 #53681]  INFO -- : Request to run code (session=1, tag=1).
x = "1"
puts "Hi" if x.responds_to?(:gsub)
I, [2016-05-02 14:46:10 -0500 #53681]  INFO -- : Code instrumentation (session=1, tag=1).
x = $p.i(1) do
  "1"
end
if x.responds_to?(gsub)
  puts($p.i(2) do
    "Hi"
  end)
end

I, [2016-05-02 14:46:10 -0500 #53681]  INFO -- : Instrumented code compilation started (session=1, tag=1).
I, [2016-05-02 14:46:10 -0500 #53681]  INFO -- : Instrumented code compilation failed (session=1, tag=1).
I, [2016-05-02 14:46:10 -0500 #53681]  INFO -- : Original code compilation started (session=1, tag=1).
E, [2016-05-02 14:46:10 -0500 #53681] ERROR -- : Instrumention bug found (session=1, tag=1).
```

**Comment by Fryguy** [comment]
![crystal playground 2016-05-02 15-50-04](https://cloud.githubusercontent.com/assets/52120/14965850/90a5744e-107d-11e6-8e03-ec89aa660383.png)

**Comment by lbguilherme** [comment]
I believe this was fixed in #2526 and will be in the next release.

**Comment by Fryguy** [comment]
I saw that issue, but since it was a fix in the parser, I didn't think it was related.  My thought was this was from the playground instrumentor, but perhaps I'm wrong.  I'll double check and if it is fixed by that I'll close.

**Comment by bcardiff** [comment]
@Fryguy that should fix it, but thanks for reporting it either way. The instrumentation in the playground use the to_s to write again the code.
A less sensible approach for instrumentation would be to inject transformation in the compiler itself, but right now that can't be done. So yes, the playground is sensible to the to_s of the AST nodes.

**Comment by Fryguy** [comment]
Thanks all.  I verified with master 9c7f351 and it works!
