### ISSUE TITLE
Attribute to force return value to be used

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#2546]
We could add a method attribute to force a method's value to be used, a possible name can be `@[MustUseResult]`. Consider this:

``` crystal
a = [4, 3, 2]
a.sort
puts a # => what do you think?
```

Can you find the bug? With this new attribute in place:

``` crystal
class Array
  @[MustUseResult]
  def sort
    # return a sorted copy of this array
  end
end

a = [4, 5, 6]
a.sort # Error: result of `a.sort` must be used
puts a
```

This could be applied to a lot of methods that return a copy and have no external effect, and don't modify the receiver. For example, `Array#map`, `Enumerable#select`, all `String` methods that return a copy, and probably many others. This will reduce a lot of silly mistakes like doing `sort` instead of `sort!`.

A result is used when it's passed to a method, assigned to a variable or returned from a method or from a block.

We could even make `MustUseResult` receive an optional argument, the name of a suggested alternative method. In the example above it could say "did you mean `sort!`?".

What do you think?

**Comment by jhass** [comment]
I don't like this too much, it's too easy to introduce a wanted (by the caller) side effect and then the caller has to workaround a misplaced annotation. It also adds more rules and thus complexity to the language.

I would also question it actually eliminates that class of bugs, among newcomers code such as
```cr
a = [2, 3, 1]
b = a.sort
puts a
```

isn't too uncommon.

**Comment by asterite** [comment]
It's true that without the compiler checking that `@[MustUseResult]` is correctly used (checking that no side effects take place) it could be misused.

**Comment by ozra** [comment]
The idea is good, if seen more like "MustHandleResult", and that `discard` keyword or similar (like in Nim) is available, and not requiring purity.

What imo would be better is instead to turn it around to have `@[Pure]` and validate purity and automatically require that the result must be used then (and else suggest alternative method if there is one matching with final `!` in error message).
There could also be "conceptual purity". For caching/lazy initing functions that don't really change the state of an object. These aren't technically pure, so might harm optimizability, but are still considered pure from a usage perspective, `@[StatePure]`. This would have to be validated in a different way, that the instvar isn't used in a way that could cause different behaviour depending on if the state-pure method has been called or not. 
```crystal
class Foo
   @[Pure]
   def foo(a)
      a.some_thing + 1   # a.some_thing must also be pure, naturally
   end
   @[StatePure]
   def bar()
      @bar ||= SomeThing.new()  # `@bar` must not be read directly anywhere else in class
   end
end
```

@jhass, I can't imagine the a->b bug being within miles as common as the a.sort != a.sort! bug.

**Comment by ysbaddaden** [comment]
Your example is a naming ambiguity: `sort` is an action and it's only natural to expect it to act on the array itself, not return a `sorted` duplicate. I'm not sure this is worth adding a decorator.

@ozra this purity thing would taint the language everywhere, and everything would end up requiring to be pure, ie. a completely different language.

**Comment by kirbyfan64** [comment]
What if you add something to explicitly ignore a `MustUseResult` value?

**Comment by ozra** [comment]
@ysbaddaden - no, you can use pure funcs in un-pure funcs - it doesn't taint everything.
