### ISSUE TITLE
Installing crystal from Ubuntu 16.04 - weak key

### ISSUE THREAD

**Issue by hestad** [crystal-lang/crystal#2553]
Command: curl http://dist.crystal-lang.org/apt/setup.sh | sudo bash

std. out:
Get:19 http://dist.crystal-lang.org/apt crystal/main amd64 Packages [373 B]  
Get:20 http://dist.crystal-lang.org/apt crystal/main i386 Packages [372 B]
Fetched 380 kB in 1s (310 kB/s)  
Reading package lists... Done
W: http://dist.crystal-lang.org/apt/dists/crystal/InRelease: Signature by key 5995C83CD754BE448164192909617FD37CC06B54 uses weak digest algorithm (SHA1)

**Comment by vjdhama** [comment]
For more context : https://wiki.debian.org/Teams/Apt/Sha1Removal

**Comment by marcusklaas** [comment]
Is there any workaround available for this?

**Comment by jhass** [comment]
It's just a warning, it shouldn't break the install.

**Comment by marcusklaas** [comment]
Oh, right! Thanks!

**Comment by will** [comment]
I think you can use https instead of http, which would solve this warning in a different way.

**Comment by shaicoleman** [comment]
According to https://wiki.debian.org/Teams/Apt/Sha1Removal
"Please note that we intend to shut off SHA1 completely on January 1, 2017"

**Comment by Sija** [comment]
@crystal-lang bump! Only 1 week left before complete SHA1 removal.

**Comment by matiasgarciaisaia** [comment]
It _seems_ we've just fixed this - if someone else can test & confirm, that'd be great :)

**Comment by matiasgarciaisaia** [comment]
Jan 2nd and I am able to install Crystal in a fully upgraded Ubuntu 16.04.2 VM - closing this as fixed.

Please comment otherwise.
