### ISSUE TITLE
You've reached a bug in the playground.

### ISSUE THREAD

**Issue by miketheman** [crystal-lang/crystal#2561]
> E, [2016-05-06 09:24:25 -0400 #64357] ERROR -- : Instrumention bug found (session=1, tag=1).

```
Bug

You've reached a bug in the playground. Please let us know about it.

Code

module Statsd
  struct MetricMessage
    def initialize(
      @name : String,
      @metric_type : String,
      @tags : Array(String)? = nil,
    )
    end
  end
end
  
name = "somemetric"
value = 1
metric_type = "c"
tags = nil

message = Statsd::MetricMessage.new(
  name,
  metric_type,
  tags,
)
Exception

Error in line 28: instantiating 'Crystal::Playground::Agent#i(Int32)'

in line 28: instantiating 'Crystal::Playground::Agent#i(Int32)'

in line 29: instantiating 'Statsd::MetricMessage:Class#new(String, String, Nil)'

instantiating 'Statsd::MetricMessage#initialize(String, String, Nil)'

in line 4: Can't infer the type of instance variable '@name' of Statsd::MetricMessage

The type of a instance variable, if not declared explicitly with
`@name : Type`, is inferred from assignments to it across
the whole program.

The assignments must look like this:

  1. `@name = 1` (or other literals), inferred to the literal's type
  2. `@name = Type.new`, type is inferred to be Type
  3. `@name = Type.method`, where `method` has a return type
     annotation, type is inferred from it
  4. `@name = arg`, with 'arg' being a method argument with a
     type restriction 'Type', type is inferred to be Type
  5. `@name = arg`, with 'arg' being a method argument with a
     default value, type is inferred using rules 1, 2 and 3 from it
  6. `@name = uninitialized Type`, type is inferred to be Type
  7. `@name = LibSome.func`, and `LibSome` is a `lib`, type
     is inferred from that fun.
  8. `LibSome.func(out @name)`, and `LibSome` is a `lib`, type
     is inferred from that fun argument.

Other assignments have no effect on its type.

Can't infer the type of instance variable '@name' of Statsd::MetricMessage
```

**Comment by asterite** [comment]
Reduced:

```crystal
class Foo
  def initialize(x : Int32)
    @x = x
  end
  
  def x
    @x
  end
end

Foo.new(1)
```
The problem happens because the instrumentor transforms the code into this:

```crystal
class Foo
  def initialize(x : Int32)
    @x = $p.i(3) do
      x
    end
  end
  def x
    $p.i(7) do
      @x
    end
  end
end
$p.i(11) do
  Foo.new(1)
end
```

and now it can't infer the type of `@x`.

I guess one solution to this would be to stop instrumenting assignments to global, class and instance variables.

**Comment by bcardiff** [comment]
@asterite , will the inference work if the instrumented call is appended an
`.as(typeof(<orig expr>))` ?

Another alternative would be to insert on each ivar, global, cvar
assignmente a assignmente with `= uninitialized typeof(<original expr>)`

Or maybe refactor the instrumentation agent to a singleton and see if the
block return type can be used as return type of the i class method.

The first option should be the simplest one, but on my side will need to
wait a week or so to finish my trip :-)
On vie, 6 de may de 2016 at 09:34 Ary Borenszweig <notifications@github.com>
wrote:

> Reduced:
>
> class Foo
>   def initialize(x : Int32)
>     @x = x
>   end
>
>   def x
>     @x
>   endend
> Foo.new(1)
>
> The problem happens because the instrumentor transforms the code into this:
>
> class Foo
>   def initialize(x : Int32)
>     @x = $p.i(3) do
>       x
>     end
>   end
>   def x
>     $p.i(7) do
>       @x
>     end
>   endend$p.i(11) do
>   Foo.new(1)end
>
> and now it can't infer the type of @x.
>
> I guess one solution to this would be to stop instrumenting assignments to
> global, class and instance variables.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/crystal-lang/crystal/issues/2561#issuecomment-217442114>
>
-- 
Brian J. Cardiff - Manas Technology Solutions
[ar.phone] 4796.0232 #BCR(227)
[us.phone] 312.612.1050  #BCR(227)
[email] bcardiff@manas.com.ar
[web] www.manas.com.ar
[weblog] http://weblogs.manas.com.ar/bcardiff/

**Comment by asterite** [comment]
No, because the type guesser can't use `typeof(...)`, because it might involve doing a method lookup, etc. 

And the type guesser doesn't use return type annotations on instance methods.

I'm sure there must be an "elegant" solution to this, I don't know what is it yet.
