### ISSUE TITLE
$a = 1.to_i => "Can't infer the type of global variable

### ISSUE THREAD

**Issue by alainravet** [crystal-lang/crystal#2563]
```

puts 1     .class   # Int32
puts 1.to_i.class   # Int32

$a = 1              # OK
$b = 1.to_i         # FAIL : Can't infer the type of global variable '$b'


```

**Comment by asterite** [comment]
Hi,

What you want doesn't fall into one of the [rules](http://crystal-lang.org/docs/syntax_and_semantics/type_inference.html) for the new global type inference algorithm. You will need to add a type annotation:

```
$b : Int32 = 1.to_i
```

And since I don't think it's very simple or clear to add such rule, I'll close this for now.

**Comment by alainravet** [comment]
@asterite 
   > And since I don't think it's very simple or clear to add such rule, I'll close this for now.

  _"(not) simple to add",_
I trust you 100% when you say it's hard to improve the compiler in this direction, but
  _"(not) clear"_
, on the contrary:
  1 == 1.to_i 
is obvious for humans; why not for compilers?

There's a workaround, so it's OK I guess, but that's too bad nonetheless: the compiler should be able to figure out that `1 == 1.to_i`, and not force us to add this unnecessary verbose typing code.

**Comment by asterite** [comment]
But in your real code do you have `1.to_i`? Why not simply write `1`? What's the real code behind this?

**Comment by alainravet** [comment]
@asterite 
The real code was
```
$test_table_size = (2**20).to_i
```
because in crystal 0.15 :
```
# Crystal 0.15
# (2**20)      # 1.04858e+06 Float64  <==
# (2**20).to_i # 1048576 Int32
```

but I now understand why it started failing with 0.16. (, and I can simply remove the `to_i`in this very case) : 

```
# Crystal 0.16
(2**20)      # 1048576 Int32   <== changed in 0.16
(2**20).to_i # 1048576 Int32
```
