### ISSUE TITLE
Changes in 0.16.0 Types throwing errors

### ISSUE THREAD

**Issue by javajax** [crystal-lang/crystal#2566]
There are some initializers I have that are throwing errors now.
I think I understand the Type changes but is this example no longer a valid way to initialize a class?

```crystal
  def initialize
    @debud = false
    @file_name = ""
  end
```

**Comment by asterite** [comment]
It should be valid. What's the code you are having issues with?

**Comment by javajax** [comment]
here is a link to the build output.
https://gist.github.com/javajax/1b5778e41422522caf1f0b2776d8e572

**Comment by javajax** [comment]
I am using option_parser inside my base class.
and in a method run I am changing if the value of debug to true or false based on a flag.

I think this is the root of the problem.

```
      parser.on("-d", "--debug", "Upcases the sallute") {
        self.debug = true                                                                                                                              
      }
```

**Comment by asterite** [comment]
Note that you have a typo in the first snippet (it says "debu**d**" but should probably be "debug")

**Comment by asterite** [comment]
In fact the error says "(did you mean @debud?)" :-)

**Comment by javajax** [comment]
That makes so much sense.
never mind :)
