### ISSUE TITLE
When initializing a Hash, the initial_capacity value seems to be ignored sometimes

### ISSUE THREAD

**Issue by dkhofer** [crystal-lang/crystal#2586]
Some examples: https://play.crystal-lang.org/#/r/yaj

Seems like initial_capacity is only used when it's the only parameter to the initializer.  But let me know if I'm doing it wrong.  :-)

**Comment by asterite** [comment]
Seems like the argument is not being forwarded: https://github.com/crystal-lang/crystal/blob/master/src/hash.cr#L21-L23

**Comment by GrahamGoudeau** [comment]
I'd like to try to tackle this one, if no one else is working on it

**Comment by GrahamGoudeau** [comment]
See #2588

**Comment by dkhofer** [comment]
Thanks for the fix, Ary!
