### ISSUE TITLE
must be Hash(String, Int32 | String), not Hash(String, Int32)

### ISSUE THREAD

**Issue by Nephos** [crystal-lang/crystal#2587]
Hello world !

In the following code:

```crystal
class A
  alias Special = Int32 | String

  @a : Hash(String, Special)
  @b : Hash(String, Special)

  def initialize(k : String, v : Special)
    @a = { k => v, k => v.to_s }
    @b = { k => v }
  end

end

A.new("toto", 1)
```

I've an error on ``@b = { k => v }`` because
```text
must be Hash(String, Int32 | String), not Hash(String, Int32)
```

https://play.crystal-lang.org/#/r/ybs

Do I have to use 
```crystal
    @b = { k => v } of String => Special
```
or is there a better way to avoid these kind of redondance ?

**Comment by asterite** [comment]
The compiler infer's the hash type only from the keys and values you put in it. If you need it to be of another type use `of`:

```crystal
class A
  alias Special = Int32 | String

  @a : Hash(String, Special)
  @b : Hash(String, Special)

  def initialize(k : String, v : Special)
    @a = {k => v, k => v.to_s} of String => Special
    @b = {k => v} of String => Special
  end
end

A.new("toto", 1)
```

In play: https://play.crystal-lang.org/#/r/ydy

**Comment by asterite** [comment]
You can also use an alias, if that hash type is going to be used a lot in your code, together with the custom hash literal:

```crystal
class A
  alias Special = Int32 | String
  alias SpecialHash = Hash(String, Special)

  @a : SpecialHash
  @b : SpecialHash

  def initialize(k : String, v : Special)
    @a = SpecialHash{k => v, k => v.to_s}
    @b = SpecialHash{k => v}
  end
end

A.new("toto", 1)
```

See also: http://crystal-lang.org/docs/syntax_and_semantics/literals/hash.html

**Comment by Nephos** [comment]
yeah thanks I didn't saw the "Hash-like types" part :)

**Comment by danielpclark** [comment]
Can the documentation for Hash-like types be updated?  I wasn't able to deduce how to do it from the docs:  Fore example : https://play.crystal-lang.org/#/r/1stg

**Comment by daliborfilus** [comment]
Sorry to comment on closed issue, but the syntax `SpecialHash{k => v}` works only for non-empty hashes. `SpecialHash{}` throws compile error and must be replaced with `{} of Hash(String, Special)`. Which is (imho) ugly and I would very much like to use `SpecialHash` if I have it already defined :/

**Comment by Blacksmoke16** [comment]
@daliborfilus You can also just do `SpecialHash.new`.

**Comment by daliborfilus** [comment]
@Blacksmoke16 Ah, right. Thanks.
