### ISSUE TITLE
Expose condition variable's timed_wait

### ISSUE THREAD

**Issue by mperham** [crystal-lang/crystal#2599]
ConditionVariables have a wait method but don't yet expose the similar timed_wait.

https://github.com/crystal-lang/crystal/blob/master/src/thread/condition_variable.cr#L25
https://github.com/crystal-lang/crystal/blob/869b306b1966a737c9b62c6fdf5b0eabd315f633/src/thread/lib_pthread.cr#L40

Could we get timed_wait exposed too?  I'd do it myself but I'm not yet confident enough in my crystal skills.  This method is necessary to implement a resource pool shared between fibers.

**Comment by asterite** [comment]
Hi,

`Thread` and `ConditionVariable` are marked as `:nodoc:` because they are not public APIs. Do not use them, your program will crash.

So any addition to Thread and ConditionVariable, at least for now, are not needed.

**Comment by mperham** [comment]
How are we to share a pool of connections between Fibers?  Use a dedicated Fiber "manager" and a channel that other Fibers can pull and push a resource from?

**Comment by mperham** [comment]
I'm not clear how we can use channels to share a lazy resource.  If I call `chan.receive`, there's no way to instantiate an instance and return it.  Also, there's no way to time limit a channel receive; if the resource pool is overtaxed, I'd like it to raise "resource exhausted" error, not wait forever.

I know Go has channels but it also has public sync APIs for ["low-level library" usage](https://golang.org/pkg/sync/) because not everything can be done via channels.

Ideas?

**Comment by asterite** [comment]
@mperham We are missing all of those sync primitives. We are still alpha. But in the next month we'll probably start dedicating a lot more time to finishing all pending issues regarding concurrency.

**Comment by mperham** [comment]
:metal: Sounds good.

I just want to say that Crystal is starting to look awesome.  I looked at it nine months ago and it didn't have any of the concurrency stuff so it wasn't usable to me.  Now it is **so close** to usable.  Keep up the good work!

**Comment by luislavena** [comment]
BTW there is some sort of connection pool implementation done by @ysbaddaden using Channel and IO pipes that *kinda* workaround the limitation described: https://github.com/ysbaddaden/pool

**Comment by mperham** [comment]
@luislavena That's exactly what I'm looking for, thank you!
