### ISSUE TITLE
Cannot sleep for a fraction of a second

### ISSUE THREAD

**Issue by sferik** [crystal-lang/crystal#261]
The following Crystal program sleeps for approximately 1 second:

``` crystal
sleep(1)
```

I would expect the following program to have nearly identical behavior, however it does not sleep at all:

``` crystal
sleep(0.5)
sleep(0.5)
```

**Comment by rdp** [comment]
Also the docu for sleep is a bit confusing (says "Blocks the current fiber for the specified number of seconds.") might be nice to say ("Blocks the current fiber for the specified number of seconds.  Can be fractions of a second.") or something like that...
