### ISSUE TITLE
type inference error

### ISSUE THREAD

**Issue by chenkovsky** [crystal-lang/crystal#2611]
```crystal
def x(a : Hash(Symbol, Bool))
end

b = x({b: false})

```

no overload matches 'Overloads are:
 - x(a : Hash(Symbol, Bool))

b = x({b: false})
    ^

**Comment by asterite** [comment]
Hi,

If you are using Crystal 0.17.0, `{b: false}` is not a Hash, it's a NamedTuple: http://crystal-lang.org/docs/syntax_and_semantics/literals/named_tuple.html

**Comment by asterite** [comment]
Use `{:b => false}`
