### ISSUE TITLE
Invalid memory access (signal 11) at address 0x0

### ISSUE THREAD

**Issue by chenkovsky** [crystal-lang/crystal#2612]
after upgrading to 0.17, I recompile my library, and rerun crystal spec.
I get Invalid memory access (signal 11) at address 0x0. I have never met this exception.
is it compiler's bug?

my library is https://github.com/chenkovsky/docopt.cr

**Comment by jhass** [comment]
Can't reproduce on HEAD, most likely fixed either by a4aabe29e230a4fb8dba1b133bacc17b22496114 or d4084158068d86545057722bdfc03cfb5e64bc04

**Comment by asterite** [comment]
@jhass Thanks! I made a few more fixes in the release/0.17 branch and I also can confirm that I don't get a segfault anymore. 0.17.1 should be out soon, maybe later today or tomorrow.
