### ISSUE TITLE
Macro errors in 0.17

### ISSUE THREAD

**Issue by ozra** [crystal-lang/crystal#2613]
Might be me having worked to little with crystal-macros, but this (the dbg_output... is just boolean - just remove to test):
```crystal
macro _dbg(*objs)
  ifdef !release
    if DebuggingData.dbg_output_on?
      STDERR.puts {{objs}}.join ", "
    end
  end
end
```
Worked before, but fails after install 0.17, I assume because of parsing priorities regarding `{` or that the tuple-splat -> join mucks up?

**Comment by asterite** [comment]
`objs` is now a tuple literal, previously it was an array literal. So `{{objs}}` probably expands to something that begins with curly brace. Better put parentheses there. I didn't think this change was going to be a breaking change, that's why I didn't put it in the changelog.

**Comment by asterite** [comment]
(it being a tuple literal is more consistent with the type that's being passed in regular methods)

**Comment by ozra** [comment]
Yes parens around works (to avoid being seen as block), and of course, in this case, simply splatting is the right way.
