### ISSUE TITLE
Array#flatten: Incorrect type is inferred when using generics

### ISSUE THREAD

**Issue by Ragmaanir** [crystal-lang/crystal#2621]
https://carc.in/#/r/yws

```crystal
class X
end

class Y(T) < X
end

p typeof([Y(Int32).new] of X) # Array(X+)
p typeof([[Y(Int32).new] of X].flatten) # Array(X+ | Y(Int32))
```
I think the last line should return the same as the previous one.

**Comment by Ragmaanir** [comment]
Maybe this does not really have to do with flatten but with the unification of the two types. It does not look like the compiler recognizes that Y is a subtype of X.

**Comment by asterite** [comment]
As always, subclassing generic types is buggy in the compiler. Any bug you find related to this will always have the same answer. I'm expecting to fix all of this in maybe a month or two.

**Comment by Ragmaanir** [comment]
I see, thanks. Ill close this issue then.
