### ISSUE TITLE
GC.stats broken

### ISSUE THREAD

**Issue by mperham** [crystal-lang/crystal#2628]
```
in macro 'record' /usr/local/Cellar/crystal-lang/0.17.1/src/macros.cr:32, line 4:

  1.   struct Stats
  2.     getter collections, bytes_found
  3. 
  4.     def initialize(@collections, @bytes_found)
  5.     end
  6. 
  7.     
  8. 
  9.     def clone
 10.       Stats.new(@collections.clone, @bytes_found.clone)
 11.     end
 12.   end

    def initialize(@collections, @bytes_found)
                   ^~~~~~~~~~~~

Can't infer the type of instance variable '@collections' of GC::Stats
```

**Comment by asterite** [comment]
Thanks for reporting!

I added the missing types, this will be working int he next version.

Note however that GC.stats will be removed in a future version, it's kind of internal and very tied to boehm. In fact I don't recall adding that method, it seems it was added together with other stuff when we accepted a PR. But I guess it can be useful to get some stats for short scripts.
