### ISSUE TITLE
Make `{"foo": 1}` also be a named tuple

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#2631]
I would like `{"foo": 1}` to denote a NamedTuple, and not a Hash with a string key. The reasons are:

1. It makes the language more consistent, because the colon `:` inside curly braces will always mean "named tuple". And because named tuples are related to named arguments, which are also passed with a colon, it's more consistent. And hashes will always be written with the "rocket" syntax, `{exp => exp}`
1. Even though named tuples are usually used to be passed as arguments to a method, and so they should probably have keys that are valid language identifiers, there are many other cases where this artificial restriction imposes limits on APIs. One example is [html_builder](https://github.com/crystal-lang/html_builder), which lets you write a tag and pass named arguments for the the tag attributes. But we can't pass an attribute named "data-foo", because it's not allowed as a named argument/tuple key.  We are then forced to use a Hash, which is slower and involves heap memory and GC pressure. This is just one small example, but I'm sure other examples will eventually arise.

With this change we should of course allow passing named arguments like this:

```crystal
# method call
method foo: 1, "key with spaces": 2, "data-foo": 3

# named tuple
tup = {
  foo: 1,
  "key with space": 2,
  "data-foo": 3,
}
```

The only downside is that this will break code that uses `{"foo": "bar"}` for a hash with string keys. But since we are not 1.0 yet, we can do that.

Other stuff that will break, that is similar, is `HTTP::Headers{"Content-Type": "text/plain"}`. It would have to be rewritten to `HTTP::Headers{"Content-Type" => "text/plain"}`. We *could* stick with `:` here, because `HTTP::Headers{...}` clearly isn't a named tuple, but I'd like to avoid having exceptions and special rules in the language.

**Comment by Gangwolf** [comment]
@asterite I think I have an alternative proposal for Tuple and NamedTuple syntax that might address this case #2629, I'll appreciate any thoughts on it.

**Comment by ozra** [comment]
For the love of mankind I can't remember which: but I did work with a JSON-API once which had spaces in basically all API-keys (!), so there's at least one case where this would also be a practical usage plus. :-)

**Comment by bcardiff** [comment]
The named tuple with dashes or spaces would only be accessible by `#[](index : Symbol | String)` method right? There won't be available with double splat. Or the external name could be helpful here?

Regarding the headers example, I see no problem that the `HTTP::Headers{"Content-Type": "text/plain"}` will call `HTTP::Header#[]=` with a symbol as key and a value. Right now no hash is created on that initialization.

**Comment by asterite** [comment]
@bcardiff It can be accessed with `tup[:"key with spaces"]`, so with a symbol literal (not a string literal)

We could add external names with spaces, but I'm not sure it's something that's going to be used. The idea is to capture any name with `**options`, like for example in the `html_builder` shard.

**Comment by asterite** [comment]
About `HTTP::Headers{"Content-Type": "text/plain"}`, the point is to avoid confusion: `:` should mean "named something", never a "Hash-like something". That's why I'd like to remove that syntax too.

**Comment by bcardiff** [comment]
Ok, my thumbs up was already there :-).

**Comment by BlaXpirit** [comment]
I hate having to write `=>` but there's no point holding on to this special case syntax.
