### ISSUE TITLE
Possible to bypass type restriction with a named method argument

### ISSUE THREAD

**Issue by BlaXpirit** [crystal-lang/crystal#2640]
```crystal
def f(a : Int32)
  p a
end

if "a" == "b"
  a = 6
end
f(a: a) #=> nil
```
https://carc.in/#/r/zg8

**Comment by asterite** [comment]
@BlaXpirit Thank you! The compiler wasn't taking named arguments into account in one part of it (cover check, where we figure out if overloads cover all possible type combinations).

Later this week I'll probably release 0.17.4 with this and other fixes.
