### ISSUE TITLE
Request: Specify root element when parsing JSON

### ISSUE THREAD

**Issue by barisbalic** [crystal-lang/crystal#2642]
I've been writing a small API client, and enjoying the `JSON#mapping` macro immensely, however this API (like several I've encountered in the past) uses both plural and singular keys for envelopes, e.g. `{ transactions: [] }` and `{ transaction: {}}`.  Some APIs do much worse, especially legacy/internal APIs.

Given that this is fairly common, and that crystal angles itself toward being a convenient language, is there any chance the core team would reconsider allowing users to specify the root node/element when parsing JSON?

I saw that #789 was closed, with a suggestion posted in the playground.  While clever, it suits only the plural/singular case, and seems a bit overkill for something that could be reduced to passing an option.

Thanks very much for all your good work!

**Comment by jhass** [comment]
```
<jhass> I could also imagine something like Transaction.from_json(json, root: "transaction") for the API
<jhass> Array(Transaction).from_json(json, root: "transactions")
<jhass> transactions: {Array(Transaction), root: "transactions"}
<jhass> all these would pass it on to new which accepts it optionally and assumes a hash with that key present in that case
<jhass> I think that should cover most cases fairly elegantly
```

**Comment by asterite** [comment]
Yeah, I guess JSON like that is pretty common in many APIs.

Let's do it 😸 

I guess we'd need to do two things:
1. Add a `root` option in `JSON.mapping`'s entries
2. Add an overload to `Object.from_json` with a second argument specfying the root. Right there we can skip the root with the pull parser and the materialize the object from its value.

`JSON.mapping` now supports default values and converters, so having more common cases covered is always good (less boilerplate).

@jhass I don't think we can revive your PR. Want to write another one? Otherwise I will probably do it tomorrow or past tomorrow.

**Comment by asterite** [comment]
And I guess the `root` property should also be used in the generated `to_json` in `JSON.mapping`

**Comment by barisbalic** [comment]
Wow.  This is slick.  Thanks for the instant response.

**Comment by asterite** [comment]
@jhass @barisbalic I have a PR ready for this, but when documenting an example in `JSON.mapping` I realized I'm not sure this belongs to the mapping. I can imagine:

```crystal
transaction = %({"transaction": {...}})
transactions = %({"transactions": [...]})

Transaction.from_json(transaction, root: "transaction")
Array(Transaction).from_json(transactions, root: "transactions")
```

are useful, but is there any case where this nesting happens **inside** other objects?

If not, if the only case is the root, then we just need to add a simple overload to `Object.from_json`, but there won't be a need to change `JSON.mapping`.

**Comment by jhass** [comment]
While I don't have an example at hand, I wouldn't be surprised at all to find it exists somewhere, and not even all that infrequently.

Is it adding that much complexity to the macro?

**Comment by asterite** [comment]
@jhass You are right, it's just a simple addition to the macro and doesn't hurt. I'll send the PR :-)

**Comment by barisbalic** [comment]
To set your minds at ease @asterite @jhass I can tell you that the nesting (and worse) definitely occurs in some APIs.

Most recently I have been frustrated by some internal Xbox Live APIs, the activity feed endpoint specifically returns a list of items that are one of five different structures, and I have to rely on an `activityItemType` field to decide how to parse the item.  I realise this PR won't solve that problem, just saying that a large company, using what you'd expect to be good tooling, still produce things like this.
