### ISSUE TITLE
Ubuntu 16.04 compatibility?

### ISSUE THREAD

**Issue by nik736** [crystal-lang/crystal#2652]
Hi guys,

does crystal work on Ubuntu 16.04? 

For me nothing works and I always get:

"Error: you've found a bug in the Crystal compiler."

It doesn't matter how my lib or cr file looks like.

Is this a known issue (should I provide more details) or is crystal just not yet compatible with 16.04?

**Comment by jhass** [comment]
How exactly did you install and what's the full output?

**Comment by pkorotkov** [comment]
Crystal perfectly works on Ubuntu (16.04 x86-64). It might be useful to take a look at how a working environment is set up in my [home-brew script](https://github.com/pkorotkov/crystalball/blob/master/cryball.bash) for Crystal snapshots management.
PS: Not tested on 32 bit platforms.

**Comment by jhass** [comment]
Will reopen with more info provided.
