### ISSUE TITLE
Would Shellwords be welcome in the standard library?

### ISSUE THREAD

**Issue by glaucocustodio** [crystal-lang/crystal#2657]
Shall we include Shellwords module like the Ruby one (http://ruby-doc.org/stdlib-2.0.0/libdoc/shellwords/rdoc/Shellwords.html) in the standard library?

**Comment by jhass** [comment]
I feel like the valid usecases are extremely rare, what's yours?

**Comment by lbguilherme** [comment]
It would have use inside the compiler with the macro run: `https://github.com/crystal-lang/crystal/blob/6b926e6cb5f35c9d05a014b9b947c2d8122f0d38/src/compiler/crystal/macros/macros.cr#L64`

Currently the string is shell-escaped by simply calling `inspect`. I don't know a specific case where it fails, but it isn't right anyway and would be fixed at some moment.

**Comment by jhass** [comment]
Why should we shell escape it instead of even avoiding the shell and passing each argument to `Process.run` directly?

**Comment by lbguilherme** [comment]
@jhass You are right. I don't know why `Process.run` isn't used there

**Comment by glaucocustodio** [comment]
Ok, so we can live without it for now. Thank you guys for the great work ;)

**Comment by alexherbo2** [comment]
I’d like this feature to write commands to a file or construct a shell command.

**Example** – A snippet for configurable batch actions:

``` crystal
options.command = "mv %{1} %{2}"
shell_command = options.command % { "1" => in.shell_escape, "2" => out.shell_escape }
system(shell_command)
```
