### ISSUE TITLE
type check issue on class initializer

### ISSUE THREAD

**Issue by TPei** [crystal-lang/crystal#2658]
Hey, I got some confusion around tapesafety.

Given two slightly different ways to hand in a variable into the initialize method:
```cr
class MyClass
  @errors : Array(Exception)
  
  def initialize(errors = [] of Exception)
    @errors = errors
    puts "this does not work"
  end

  def initialize(errors = [] of Exception)
    @errors = [] of Exception
    @errors += errors
    puts "this does work"
  end
end

class MyException < Exception
end

MyClass.new(errors: [MyException.new])
```

For the immediately setting initialize version I get `instance variable '@errors' of MyClass must be Array(Exception+), not Array(MyException)`, the one that sets the [] of Exception and then uses `+=` works just fine.

Is this an issue with my brain or the language? ;)

**Comment by jhass** [comment]
This is the same as #1297

Workaround:
```cr
class MyClass
  def initialize(@errors = [] of Exception)
  end
end

class MyException < Exception
end

MyClass.new(errors: [MyException.new] of Exception)
```
