### ISSUE TITLE
Allow specs to dynamically skip

### ISSUE THREAD

**Issue by mperham** [crystal-lang/crystal#2664]
Right now, you can change "it" to "pending" to avoid running a spec but this is static - it will always skip the test.  I want to get the same semantics dynamically:

```ruby
it "tests using redis feature, new in 3.2.0" do
  skip("Redis too old") if redis_version < "3.2.0"
  ...
end
```

So if someone has an old version of Redis on their laptop, that test won't blow up with an error but let the user know that it couldn't run that test.  Ruby's minitest has [this exact feature](https://github.com/seattlerb/minitest/blob/0b8bbc7026498fedd7d61bd782325bbe0333a698/lib/minitest/assertions.rb#L663).

**Comment by asterite** [comment]
You can declare a spec conditionally:

```crystal
unless redis_version < "3.2.0"
  it "tests using redis feature, new in 3.2.0" do
    ...
  end
end
```

Does this solve your issue?

**Comment by mperham** [comment]
Sort of, it doesn't hint to the user that their dependency is too old and it wouldn't be built into the nice spec output summary.  Your call if that's reason enough to add it.

```ruby
unless ...
  it "..." do
    ...
  end
else
  puts "Upgrade Redis, dude"
end
```

**Comment by asterite** [comment]
Well, we do have `pending` (though it's missing the non-block form), but you could do:

```crystal
if condition
  it "spec ... " do
  end
else
  pending "specs that only run with redis >= 3.2.0"
end
```

We could still add a `skip` method that raises a specific exception that is handled in the spec runner, but I'm still not sure it's worth it.

**Comment by mperham** [comment]
I went with [this](https://github.com/mperham/sidekiq.cr/commit/caaecbab9140617a075dd532552dff8372365231), it works ok.
