### ISSUE TITLE
Merging a proc returning void with a proc returning non-void should be a proc returning void

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#2672]
This should work:

```crystal
class Foo
  @action : ->
  def initialize
    @action = -> { }
  end
end

Foo.new
```

Extracted from: https://github.com/crystal-lang/crystal/issues/2666#issuecomment-222317868

**Comment by jhass** [comment]
Since `Void` accepts every value, `Void?` or generally `Void|Foo` should either degrade into just `Void` or be disallowed, WDYT?

**Comment by asterite** [comment]
On second though, I'm not sure about this. For example:

```crystal
proc1 = ->{ 1 }
proc2 = Proc(Void).new { ... }

proc = rand < 0.5 > proc1 : proc2
value = proc.call
# value should be Void | Int32, not Void
```

I wouldn't like to mess with types there, and loose some type information. So to solve the snippet in the original comment one can do:

```crystal
class Foo
  @action : ->
  def initialize
    @action = Proc(Void).new { ... }
  end
end

Foo.new
```

I'll mark it as a draft RFC because this needs more thought.

**Comment by asterite** [comment]
Actually, that should work, but right now the compiler doesn't distinguish between "assigning something to a variable" and "merging types": when it assigns something to a variable it first merges its type with the type of the right-hand side, and then sets that final type as the instance variable type. I'll try to improve this first.

**Comment by jhass** [comment]
If we do follow https://github.com/crystal-lang/crystal/issues/2666#issuecomment-222318426 this issue basically vanishes, no?

**Comment by asterite** [comment]
It vanishes if one explicitly puts `nil` at the end of the proc. Maybe this should work:

```crystal
class Foo
  @action : -> # Now this would be the same as `-> Nil`
  def initialize
    @action = -> { 1 } # this is -> Int32, but we said we don't care about the return value,
                       # so maybe it should work
  end
end

Foo.new
```

**Comment by jhass** [comment]
I'd say plan forward would to get rid of `Void` and then tackle this issue for `Nil`
