### ISSUE TITLE
Splatting evaluates the expression multiple times

### ISSUE THREAD

**Issue by BlaXpirit** [crystal-lang/crystal#2677]
```crystal
$a = 0

def data
  $a += 1
  {$a, $a, $a}
end

def test(x, y, z)
  pp x, y, z
end

test(*data)
```

```
x = 1
y = 2
z = 3
```

https://carc.in/#/r/105p

**Comment by BlaXpirit** [comment]
...or zero times:

```crystal
$a = 0

def nothing
  $a += 1
  Tuple.new
end

p(*nothing())

p $a
```

```
0
```

https://carc.in/#/r/1064

**Comment by asterite** [comment]
@BlaXpirit Good catch! The original implementation just replaced this (right before codegen):

```crystal
test(*data)
```

with this:

```crystal
test(data[0], data[1], data[2])
```

which explains why it was evaluated many times, or never. I fixed it by first assigning `data` to a temporary variable, and then accessing that.
