### ISSUE TITLE
SSL is dead, long live TLS

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#2683]
AKA let's rename our APIs.

SSL is dead, the current standard is called TLS. SSLv1 was never a thing, SSLv2 is broken,  SSLv3 is considered broken and more and more throughoutly disabled in both, servers and clients. SSL is simply the legacy name, TLS is what it's called today. "New" protocols call it TLS, for example `STARTTLS`.

I propose to rename SSL to TLS in our APIs, that is mainly `HTTP`. Exceptions are:
* `OpenSSL` should stay as is, as it's the name of the library
* `OpenSSL::SSL` should stay as is, as it maps better to the library functions.
* `LibSSL` and methods defined therein should stay as is, as they map library functions with `SSL` in their names.

**Comment by luislavena** [comment]
Just for clarification, the proposal is to adjust `HTTP::Server#ssl` to be `tls` instead? or `HTTP::Client.new`, correct?

**Comment by jhass** [comment]
Yes, well all I can find but the ones listed above.

**Comment by asterite** [comment]
What if then they rename it again? Could we maybe use a different generic name for this? "secure" comes to my mind.

**Comment by jhass** [comment]
It is _very_ unlikely to be renamed again, TLS is an open IETF standard, SSL was initially proprietary and developed by Netscape, the rename happened at due to silly issues.

* https://en.wikipedia.org/wiki/Transport_Layer_Security#History_and_development
* http://tim.dierks.org/2014/05/security-standards-and-name-changes-in.html

**Comment by ysbaddaden** [comment]
Basically it's the same than for JavaScript vs ECMAScript. It's unlikely the name will change —or the technology would change drastically too. Introducing a third name would just make things even more confusing than they already are.

Changing to `tls` is a nice touch, but it may be confusing too, because we expect to receive an `OpenSSL::SSL::Context`...

**Comment by jhass** [comment]
Well, the primary usecase will be `tls: true`, at least for the clients. For the server case we should perhaps call it `tls_context`?

While unlikely It's not out of question that we'll change OpenSSL for (or additionally support) something like `GnuTLS` or some fancy new library that properly uses TLS in their names. I think calling the attributes after the protocol rather than its implementing library makes more sense.

**Comment by jhass** [comment]
@asterite / @ysbaddaden so could I convince you?

**Comment by ysbaddaden** [comment]
I have nothing against either ssl or tls naming. So this is a draw for me.

**Comment by asterite** [comment]
I also have nothing against tls. Since we'll still need a few days until preparing the next release I'd like to ask @waj when he comes back.
