### ISSUE TITLE
JSON fails to parse "1000000000000000000.0" (1e20)

### ISSUE THREAD

**Issue by lbguilherme** [crystal-lang/crystal#2686]
```crystal
require "json"
p "100000000000000000000.0".to_f64        # 1e+20
p JSON.parse("100000000000000000000.0")   # 3.8758200196842125e+17
```

Actually this prints `3.8758200196842125e+1` to screen, but that's another unrelated bug on `float.to_s`: The buffer size is too small and we lose one digit.

The problem is that until the parser sees the `.`, it stores the number as an integer, and this thing overflows. I'm not sure what's the best way to fix this.

**Comment by asterite** [comment]
Do these big numbers happen in real life? I mean, why isn't it encoded as "1e+20" in the JSON string in the first place?

This can be fixed, we just need to detect overflow and then parse it in a different way (`String#to_f` uses a C call that handles this). Of course, for integers the problem will remain.

**Comment by lbguilherme** [comment]
I'm writing a driver for RethinkDB (https://github.com/lbguilherme/rethinkdb-crystal) and it did happen as a response for the query `r(1e20).run(conn)`. (This particular query and its expected output is part of their test suite, this is how I found out).

For this query I send: `[1, 1e20, {}]`,
and the server replies: `{"t":1,"r":[100000000000000000000.0]}`.
Real life is cruel.

**Comment by lbguilherme** [comment]
Thanks!!
