### ISSUE TITLE
Bad file descriptor doing sleep after HTTP::Server was closed (using Signal trap)

### ISSUE THREAD

**Issue by luislavena** [crystal-lang/crystal#2692]
Hello,

Issue summary might not be the best description, but encountered this when attempting to perform cleanup when `SIGINT` is received.

Reduced the issue to the following:

```crystal
require "http/server"

server = HTTP::Server.new("0.0.0.0", 8080) do |context|
  if context.request.path == "/"
    context.response.content_type = "text/plain"
    context.response.print "Hello world!"
  else
    context.response.status_code = 404
    context.response.print "Not Found"
  end
end

Signal::INT.trap {
  puts "Shutting down server..."
  server.close
  sleep 1 # BOOM
  exit
}

puts "Listening on http://0.0.0.0:8080"
server.listen
```

It doesn't require any request to be performed, simply fire the application and press Ctrl+C:

```
$ ccr run hello.cr 
Using compiled compiler at .build/crystal
Listening on http://0.0.0.0:8080
^CShutting down server...
Error accepting socket: Bad file descriptor (Errno)
[4675639] *CallStack::unwind:Array(Pointer(Void)) +87
[4675530] *CallStack#initialize<CallStack>:Array(Pointer(Void)) +10
[4675482] *CallStack::new:CallStack +42
[4607160] *raise<Errno>:NoReturn +24
[5110851] *TCPServer#accept<TCPServer>:TCPSocket +195
[5094091] *HTTP::Server#listen<HTTP::Server>:Nil +123
[4566989] ???
[4616073] main +41
[140554324978368] __libc_start_main +240
[4564809] _start +41
[0] ???
```

This only happens when a socket is involved, as the following works:

```crystal
Signal::INT.trap {
  puts "Bye!"
  sleep 1
  exit
}

puts "Bye?"
loop do
  sleep 1
end
```

I think has to do with spawned and `TCPServer#accept`, but by understanding ends there.

I've tried on Linux both released versions and latest build from master, both with same results.

Let me know if any other detail is required.

Thank you.

:heart: :heart: :heart:

**Comment by asterite** [comment]
The error seems to happen because the TCPServer is closed, so `accept` returns with an error. I think the solution to this would be to rescue this exception in HTTP::Server and silently ignore it (maybe?).

I tried this in Ruby:

```ruby
require 'socket'

server = TCPServer.new 2000 # Server bind to port 2000

Thread.new do
  sleep 1
  server.close
end

loop do
  client = server.accept    # Wait for a client to connect
  client.puts "Hello !"
  client.puts "Time is #{Time.now}"
  client.close
end
```

and I get:

```
bar.rb:11:in `accept': Bad file descriptor (Errno::EBADF)
	from bar.rb:11:in `block in <main>'
	from bar.rb:10:in `loop'
	from bar.rb:10:in `<main>'
```

which might suggest that it's OK for `accept` to raise an exception, and we should handle it in HTTP::Server.

Additionally, we could add an `accept?` method that returns `nil` when the socket is closed (we can detect this), so no exception is involved and it's easier to handle (maybe this should be the behaviour of `accept`?)

**Comment by jhass** [comment]
We should track that `close` was called (`server.closed?`?) and only then ignore it, please don't ignore it otherwise.
