### ISSUE TITLE
Recent 17.x release breaks SDL sample

### ISSUE THREAD

**Issue by jamgard** [crystal-lang/crystal#2695]
Just getting into this language, but recently the 17.0 update caused the SDL program in the samples directory to stop running.

The compiler claims it cannot resolve reference to SDL_main.

It _was_ working with the 15.x and 16.x branches.

I'm on Ubuntu Wily and no update to SDL has occurred recently.

**Comment by jhass** [comment]
Mmmh, it works for me if I just
```diff
diff --git a/samples/sdl/sdl/lib_sdl.cr b/samples/sdl/sdl/lib_sdl.cr
index b49d54c..c1827d8 100644
--- a/samples/sdl/sdl/lib_sdl.cr
+++ b/samples/sdl/sdl/lib_sdl.cr
@@ -149,16 +149,9 @@ lib LibSDL
   fun get_ticks = SDL_GetTicks : UInt32
   fun flip = SDL_Flip(screen : Surface*) : Int32
 
-  ifdef linux
-    fun main = SDL_main(argc : Int32, argv : UInt8**) : Int32
-  end
 end
 
-ifdef linux
-  fun main(argc : Int32, argv : UInt8**) : Int32
-    return LibSDL.main(argc, argv)
-  end
-elsif darwin
+ifdef darwin
   redefine_main(SDL_main) do |main|
     {{main}}
   end
```

**Comment by asterite** [comment]
If that works in linux then let's change it. SDL is a bit complex, it requires SDL_main to replace main, somehow. At least in darwin. I never tested in linux because I couldn't test it (I have VMs but without UI).

**Comment by jhass** [comment]
Well, the windows have no  borders, I don't remember whether it was supposed to be like that but I don't think so.

**Comment by asterite** [comment]
Hmmm... maybe we should investigate how it's done in linux then.

It's strange though, nothing have changed much in this file.

**Comment by sdogruyol** [comment]
This works in Crystal 0.23.1 on Arch :+1:

**Comment by asterite** [comment]
I think #4734 fixed it.

Please reopen otherwise.
