### ISSUE TITLE
Any Type

### ISSUE THREAD

**Issue by trans** [crystal-lang/crystal#27]
In the introduction it says:

<blockquote>
Why not make every new instantiation of a class have their instance variables types be inferred as the program is written?

The answer is that if every new instantiation of a class was different from every other instantiation, the type inference phase becomes exponential. You would have to wait a very, very, veeeeeeery long time for the program to compile (and believe us: we tried hard to make it fast).
</blockquote>

I am trying to understand this better. 

One thing that confuses me is that it seems to me that I could write a wrapper class (a bit simplified for example sake):

```ruby
    class Any(T)
      def initialize(value : T)
        @value = value
      end
      def method_missing(s, *a, &b)
        @value.send(s, *a, &b)
      end
    end
```

And then write Box as:

```ruby
    class Box
      def initialize(contents : Any)
        @contents = contents
      end
```

As long as I convert objects to Any objects when passing them to Box, it's going to act as if it is generic even though its not.

So in thinking about this, why can't Crystal do the same thing? If it can't guarantee an inferred type (or a compatible union) the just treat it like an Any.

**Comment by asterite** [comment]
Closed in favor of #2733
