### ISSUE TITLE
Test Coverage Reporting

### ISSUE THREAD

**Issue by keplersj** [crystal-lang/crystal#2704]
So... Now that we have JUnit reporting (#2455) could we get Test Coverage reporting for services like [Coveralls](https://coveralls.io/).

It seems that the main standard to represent the coverage data is called GCOV. From there tools like LCOV and Coveralls can be used to visualize the data.

**Comment by bcardiff** [comment]
I don't get why JUnit reporting will facilitate GCOV.
I would suggest first try something related to LLVM (http://llvm.org/docs/CoverageMappingFormat.html maybe).
If that fails, some instrumentation on crystal land should be doable, but more robust than in playground for sure.

**Comment by keplersj** [comment]
I just noticed that there is already an issue open for this. Closing in favor of #1157
