### ISSUE TITLE
can't yield from function literal

### ISSUE THREAD

**Issue by mperham** [crystal-lang/crystal#2711]
I've gotten this error several times while porting Ruby code and I don't understand it.  Can someone shed a little more light on what it means?

```ruby
  class Workers
    include Enumerable({process_key: String, thread_key: String, work: Hash(String, JSON::Type)})

    def each
      Sidekiq.redis do |conn|
        procs = conn.smembers("processes").as(Array(String))
        procs.sort.each do |key|
          valid, workers = conn.pipelined do |ppp|
            ppp.exists(key)
            ppp.hgetall("#{key}:workers")
          end
          next unless valid == 1
          workers.as(Array(String)).in_groups_of(2) do |tid, json|
            yield key, tid, JSON.parse(json).as(Hash(String, JSON::Type)) # <===========
          end
        end
      end
    end
```

**Comment by kostya** [comment]
i think you should yield this:
```
yield({process_key: key, thread_key: tid, work: JSON.parse(json).as(Hash(String, JSON::Type))})
```

**Comment by kirbyfan64** [comment]
Is `Sidekiq.redis` a macro?

**Comment by mperham** [comment]
Nope, it is a class method on the Sidekiq module.

**Comment by kirbyfan64** [comment]
(Wait, nevermind, I'm an idiot. Forgot Sidekiq.cr was open source...)

The error you mentioned is thrown when you have something like:

```crystal
-> { yield }
```

Because you can't yield from within a function/proc literal (surprise, surprise). Weird part is, I don't see any proc literals in your code...

**Comment by asterite** [comment]
`Sidekiq.redis` captures the block?

@mperham Make sure to read [this](http://crystal-lang.org/docs/syntax_and_semantics/block_forwarding.html), blocks and procs are not the same in Crystal, and forwarding with `&block` will always create a capture block. 

Basically change [this](https://github.com/mperham/sidekiq.cr/blob/master/src/sidekiq/pool.cr#L64-L66) to this:

```crystal
def redis
  @pool.connection do |conn|
    yield conn
  end
end
```

**Comment by asterite** [comment]
This *might* improve in the future, but right now it's not easy for the compiler to know if a proc should or shouldn't materialize into a Proc.

By the way, if you use `&block` instead of `yield` in Ruby, it's slower (and the same is true in Crystal).

**Comment by asterite** [comment]
Oh, sure, the error message needs an improvement. "function literal" is an old name, now it's `Proc`, but yes, the error message should explain more what's going on. I'll do it :-)

The rule is simple: if you use `yield`, the method gets inlined. If you use `&block`, and mention `block` (use it, call it, pass it), then a Proc object is created. You can't use `yield` then. This is different than Ruby, but could change in the future (I hope!)

**Comment by asterite** [comment]
I've improved the error message a bit, adding a link to the docs. I can't find the words right now to improve it further.

**Comment by asterite** [comment]
Please close if you think this is enough. Since this error will probably be gone in the future I wouldn't like to spend a lot of time in this right now.

**Comment by mperham** [comment]
Looks great, thanks!
