### ISSUE TITLE
Formatter shouldn't indent or-ed multiline expression

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#2712]
Given
```cr
foo(
  BAR |
  BAZ |
  FOO
)
```
the formatter  turns it into
```cr
foo(
  BAR |
    BAZ |
    FOO
)
```

**Comment by asterite** [comment]
I think the current output is correct. Basically, you are splitting the expression `BAR | BAZ | FOO` into multiple lines, and when you do that, the formatter always indents the lines after the first one.

I also tried this in Go (from which I took a lot of inspiration). This:

```go
foo(A |
    B |
    C)
```

is formatted as:

```go
foo(A |
  B |
  C)
```

and this:

```go
foo(
  A |
  B |
  C)
```

is formatted as:

```go
foo(
  A |
    B |
    C)
```

which is exactly what Crystal does.

**Comment by ysbaddaden** [comment]
It makes sense. It just makes long enum flags less nice to read:

```crystal
ctx.add_options(
  LibSSL::Options::ALL |
    LibSSL::Options::NO_COMPRESSION |
    LibSSL::Options::NO_SSLV2
)
```

**Comment by luislavena** [comment]
@ysbaddaden what about using `flags` macro for shorter expression?

**Comment by ozra** [comment]
@jhass formatting no doubt looks much better than the go-inspired. That's how I would've written it too.

**Comment by asterite** [comment]
Moving this to an RFC. I don't close it because it might make sense to do it.
