### ISSUE TITLE
CRL verification for OpenSSL < 1.0.2

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#2718]
#2708 added API to optionally enable CRL verification for OpenSSL >= 1.0.2. There exists older API that is deprecated for 1.0.2+, but we should expose it in case the linked OpenSSL is older.

We shouldn't turn this on by default however, see #2709

**Comment by straight-shoota** [comment]
I think we don't have to worry about OpenSSL < 1.0.2 any more.
