### ISSUE TITLE
Fails to parse Hashes as keys for Hashes

### ISSUE THREAD

**Issue by lbguilherme** [crystal-lang/crystal#2719]
This fails to parse:

```crystal
x = {{:a => 4, :b => 5} => [1, 2], {:a => 9, :b => 2} => [6, 5]}
```

But this works: (notice the extra space)

```crystal
x = { {:a => 4, :b => 5} => [1, 2], {:a => 9, :b => 2} => [6, 5]}
```

**Comment by MaloJaffre** [comment]
This certainly conflict with `{{` (beginning of a macro.

**Comment by lbguilherme** [comment]
@MaloJaffre Didn't notice that, thanks. I believe this is not fixable then (without backtracking on the parser, which can get slow)

**Comment by jhass** [comment]
Yes not sure we want to allow it, I'll let Ary decide.

**Comment by asterite** [comment]
Yes, this is correct behaviour, and [the formatter even has a check to output that space](https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/tools/formatter.cr#L677).

**Comment by jhass** [comment]
To elaborate why it's not worth the complexity: You shouldn't use hashes, or generally mutable or likely to mutate datastructures as hash keys anyway. Chances are you're not going to look up your values by these keys, so for example a `Array({K, V})` or `Array(Array(K|V))` would be more correct and efficient anyway.
