### ISSUE TITLE
Is there any sort of checklist for compatibility with ruby?

### ISSUE THREAD

**Issue by NullVoxPopuli** [crystal-lang/crystal#2720]
maybe a list of ruby features supported / not supported / different from ruby?

**Comment by jhass** [comment]
See https://github.com/crystal-lang/crystal/wiki/Crystal-for-Rubyists

**Comment by NullVoxPopuli** [comment]
cool thanks! 
I think it would be cool to eventually run rails on crystal :-)

**Comment by asterite** [comment]
@NullVoxPopuli note that Rails will **never** run on crystal, as crystal is not a Ruby implementation and there are now a lot of incompatibilities with it. Also, it was never a goal.
