### ISSUE TITLE
Allow using `Object` and similar types as instance variable types

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#2733]
`Object`, `Reference`, `Enum`, `Enumerable` and many other types that are currently disallowed should be able to be used as the type of instance, class and global variables.

This is a current limitation of the language but it's doable. It will come with time.

**Comment by lbguilherme** [comment]
```crystal
struct Foo
  @thing : Object
end
```

`Object` is a superclass of any struct. That mean `@thing` can contain any struct or the program. So `sizeof(@thing)` is the size of the largest struct known plus 4 bytes for the type id. Does that mean `@thing` can contain `Foo` itself? It gets cyclic.

**Comment by asterite** [comment]
Objects larger than 64 bits will be boxed in heap memory.

**Comment by asterite** [comment]
Mmm... but for that case, I'm not sure. `Object` wlll be represented as a 64 bits raw pointer... I guess that can be codegen'd, not sure. Maybe it'll be an error.

**Comment by lbguilherme** [comment]
I can be unexpected that some times it is copied by value and some others it is copied by reference (boxed). Maybe it could be always boxed when the type is `Object`.

**Comment by KCreate** [comment]
Hello

What priority does this issue have right now?

**Comment by zatherz** [comment]
Bump. IMO the value should always be boxed when passed as `Object`, so that there's less magic and unpredictability.

**Comment by HertzDevil** [comment]
I just had this idea:

```crystal
module ValueM; end
module ReferenceM; end

struct Value
  include ValueM
end

class Reference
  include ReferenceM
end

alias Any = ValueM | ReferenceM
```

Of course, doing it this way means `Any` must be bigger than the biggest `Value` type ever instantiated, which is `UInt8[4096]` for the standard library.

For `Reference` and `Class` this should be doable. (You can in fact already do `Reference.new`, you just can't cast to it explicitly.) For uninstantiated generics this is more tricky; what should the type below be?

```crystal
typeof([1].as(Indexable)[0])
```
