### ISSUE TITLE
HTTP::Client and HTTP::Server on Unix Socket

### ISSUE THREAD

**Issue by sdogruyol** [crystal-lang/crystal#2735]
Currently HTTP::Server only listens on TCP.  

It'd be really great to listen on a Unix socket like Unicorn, Thin, Puma e.g

An API like this 

``` crystal
server = HTTP::Server.new("/tmp/server.sock") do |context|
  context.response.content_type = "text/plain"
  context.response.print "Hello world!"
end

server.listen
```

**Comment by sdogruyol** [comment]
Preferably i'd like to tackle this issue but seems like https://github.com/crystal-lang/crystal/blob/master/src/socket/unix_server.cr needs to be improved. 

I've already managed to make bind https://github.com/crystal-lang/crystal/blob/master/src/http/server/server.cr#L135-L137 to accept UNIXServer but then `handle_client` needs to be updated.

Any tips and leads are welcome 😄

**Comment by asterite** [comment]
My only comment is that I wouldn't accept a string for this, in HTTP::Server constructor, as it's confusing with a host String parameter. Maybe use a required named argument, or a UnixServer instance.

**Comment by sdogruyol** [comment]
@asterite how about?

```crystal
HTTP::Server.new(socket: "/tmp/server.sock") {|context|}
```

**Comment by jhass** [comment]
How about dropping both `host` and `port` and requiring an `URI` instead?

```cr
HTTP::Server.new("localhost")
HTTP::Server.new("localhost:443")
HTTP::Server.new("tcp://localhost:443")
HTTP::Server.new("unix://server.sock") # relative
HTTP::Server.new("unix:////run/server.sock") # absolute

**Comment by sdogruyol** [comment]
@jhass it sounds like a good idea but i guess it's not common to create a server that way (or is it?) 🤔

**Comment by jhass** [comment]
I've seen it in various places, one popular example is [unicorn](http://www.rubydoc.info/gems/unicorn/Unicorn/Configurator#listen-instance_method)

**Comment by ysbaddaden** [comment]
In puma you add listeners to a single server:

```crystal
server = Puma::Server.new
server.add_tcp_listener(host, port)
server.add_ssl_listener(host, port, ctx)
server.add_unix_listener(path)
```

**Comment by ozra** [comment]
Having multiple listeners, both unix-socket and tcp, ssl seems like something one very well might want to do for a service (if not using nanomsg, ZMQ, etc.)!

**Comment by sdogruyol** [comment]
If there's a final decision for the API, i'd like to tackle this //cc @asterite

**Comment by RX14** [comment]
I'm in favour of the `HTTP::Server.new(*, socket : String)` API for this. It's simple to use, and a minimal API change.

**Comment by elorest** [comment]
Is there any active work on this issue?

**Comment by mverzilli** [comment]
No, there isn't. I think it got stuck at the design phase with so many variants and no clear winner way forward. I'm with @jhass on this. Sounds like adding more listeners would be a topic for a separate issue, wouldn't it?

**Comment by straight-shoota** [comment]
I think it'd be great to accept a single argument with an URI (either as `String` or `URI`). This way it's easy to let binding to a port/host or unix socket be configured by an external config setting (command line argument, config file etc.). It does not require an application to interpret such a config value to call different constructors. This is quite useful as it makes life easy and encourages to use a standardized format instead of individual implementations.
This does not change the API, since every signature accepting a String currently also requires an integer for the port - and the port is required in any case.
There could also be a way to directly assign a unix socket (as is the case for port/host) via a named parameter.

**Comment by straight-shoota** [comment]
To get this moved on, I would propose the following API (with simplified bodies):

```crystal
# existing overloads for TCP server with port/port+host:
def self.new(host : String, port : Int32)
  TCPServer.new(host, port)
end
def self.new(port : Int32)
  new("127.0.0.1", port)
end
# new socket overload:
def self.new(*, socket : String)
  UNIXServer.new(socket)
end
# URI overloads:
def self.new(uri : URI)
  if port = uri.port
    if host = uri.host
      new(host, port)
    else
      new(port)
    end
  elsif path = uri.path
    new(socket: path)
  else
    raise "URI requires either port or path"
  end
end
def self.new(uri : String)
  new(URI.parse(uri))
end
```

However, with 4 variants for each (`handlers : Array(HTTP::Handler), &handler : Context ->`, `&handler : Context ->`, `handlers : Array(HTTP::Handler)`, `handler : HTTP::Handler | HTTP::Handler::Proc`) this would result in a total of 20 overloads for `HTTP::Server.new`. 🤔 The code could probably be neatly organized using macros, but I fear the API doc might become overwhelming...

**Comment by bcardiff** [comment]
Note: this is almost covered by https://github.com/crystal-lang/crystal/pull/9543
