### ISSUE TITLE
Replace MD5 with Blake2b

### ISSUE THREAD

**Issue by DemiMarie** [crystal-lang/crystal#2743]
MD5 is broken.  It is _easy_ to generate collisions &ndash; that includes chosen-prefix chosen-suffix collisions.

Blake2b is the best answer.  It provides maximum possible security for the size of its hash, has builtin support for keying, personalization, and tree hashing, and is even faster than MD5.

**Comment by ysbaddaden** [comment]
There is no need to replace MD5 (or SHA1). Actually we can't replace them, because outside of security, there still are legitimate uses (eg. UUID v3 and v4). Furthermore BLAKE2 is designed for 64bits, while we support 32bits  arch's too.

Also, you should already be capable to use BLAKE2b:

```crystal
hash = OpenSSL::Digest.new("blake2b")
hash << message
```

But isn't BLAKE2b outputting 512 bits digests, and BLAKE2s a 256bits digest? This is still 4x and 2x as big as MD5.

**Comment by drbo** [comment]
Still, MD5 is obsolete and the Crystal developers should not be encouraging
its use.  Perhaps place it in crypto/obsolete?

**Comment by ysbaddaden** [comment]
Errata: BLAKE2 support is only expected for the next OpenSSL release (v1.1.0).

We're not encouraging anything. Neither MD5 nor SHA1 shall be use for cryptographic purposes. One should use SHA2, SHA3 or BLAKE2, or a higher level cryptography algorithm that makes good use of those lower level algorithm (eg: ARGON2, that leverages BLAKE2). Still, being broken for cryptography and security doesn't prevent other, non cryptographic, uses of MD5 and SHA1, like UUID v3 and v5.

**Comment by jhass** [comment]
Yes, I'd like to see the place in our documentation where we encourage usage of it. Please don't mistake acknowledging widespread use for encouragement.

**Comment by ysbaddaden** [comment]
We could highlight in the documentation that MD5 is broken for cryptographic purposes and musn't be used for anything related to security. We could do the same for SHA1, with the slight difference that it's almost broken, and that one is encouraged to use SHA2, SHA3 or BLAKE2 instead, or just not deal with cryptography and use strong and proven algorithms only, or just: use [libsodium](https://libsodium.org) :D

Those statements wouldn't hurt, quite the opposite.

**Comment by kirbyfan64** [comment]
FWIW the Crystal Docker image doesn't seem to have an OpenSSL version that supports...anything other than MD5 and SHA1.
