### ISSUE TITLE
HTTP.parse_time should preserve/respect timezone

### ISSUE THREAD

**Issue by beanieboi** [crystal-lang/crystal#2744]
hey everybody!

i'm diving into crystal and i _really_ like it. i'm trying to port URL signing for AWS services from Ruby to Crystal and i run into a problem with HMAC.

crystal
```crystal
k_date = hmac("AWS4" + config.secret_key, date[0, 8])
k_region = hmac(k_date, config.region)
k_service = hmac(k_region, service)
k_credentials = hmac(k_service, "aws4_request")
signature = hexhmac(k_credentials, string_to_sign)

def self.hmac(key, value)
  OpenSSL::HMAC.digest(:sha256, key, value)
end

def self.hexhmac(key, value)
  OpenSSL::HMAC.hexdigest(:sha256, key, value)
end
```

```"k_date Slice[131, 133, 185, 75, 106, 107, 107, 45, 219, 107, 188, 171, 108, 58, 27, 199, 236, 239, 55, 188, 111, 1, 7, 231, 100, 1, 225, 104, 11, 39, 239, 26]"```

ruby
```ruby
k_date = hmac("AWS4" + config.secret_key, date[0, 8])
k_region = hmac(k_date, region)
k_service = hmac(k_region, service)
k_credentials = hmac(k_service, "aws4_request")
signature  = hexhmac(k_credentials, string_to_sign)

def hmac(key, value)
  OpenSSL::HMAC.digest(OpenSSL::Digest.new('sha256'), key, value)
end

def hexhmac(key, value)
  OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha256'), key, value)
end
```
```
"k_date \xA8>\xD1\x88\xBE_K\aM\x7Ff4\x9FPw\xFB\xCD\xF7\x97\xBF4q\xFB\x9D_2s\x0F\x93mA\xA5"
```

since this is a long chain of HMAC, i started debugging the first value (k_date) that is used as input for the 2. HMAC. i checked that config.secret_key and date[0, 8] are the same.

just by looking at k_date in ruby and crystal, i don't think they are the same.
i pretty sure that i'm missing something here. could anyone help me to see what i'm missing?

thank you for crystal! it's really amazing!

best,
ben

**Comment by jhass** [comment]
Ruby's `.bytes` output compares better:
```
Ruby:    [168, 62, 209, 136, 190, 95, 75, 7, 77, 127, 102, 52, 159, 80, 119, 251, 205, 247, 151, 191, 52, 113, 251, 157, 95, 50, 115, 15, 147, 109, 65, 165]
Crystal: [131, 133, 185, 75, 106, 107, 107, 45, 219, 107, 188, 171, 108, 58, 27, 199, 236, 239, 55, 188, 111, 1, 7, 231, 100, 1, 225, 104, 11, 39, 239, 26]
```
So yeah, indeed completely different. However I can not reproduce with some simple stub values:

```
Ruby:
OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha256'), "foo", "bar")
=> "f9320baf0249169e73850cd6156ded0106e2bb6ad8cab01b7bbbebe6d1065317"
Crystal:
OpenSSL::HMAC.hexdigest(:sha256, "foo", "bar")
=> "f9320baf0249169e73850cd6156ded0106e2bb6ad8cab01b7bbbebe6d1065317"
```

Could you try to create a minimal self contained example that reproduces your issue?

**Comment by beanieboi** [comment]
@jhass 
thanks for the `.bytes` hint. i will do some further debugging with that. at least i know that i use the Crystal API correctly, which i wasn't sure about.

**Comment by beanieboi** [comment]
@jhass we can close this. HMAC is fine. sorry for the false alert. my problem is that `HTTP.parse_time` is not preserving the timezone.
should i open another issue for that or is this something known already?

```crystal
date = "Mon, 09 Sep 2011 23:36:00 GMT"
parsed_date = HTTP.parse_time(date).as(Time)

p parsed_date => 2011-09-09 23:36:00
p parsed_date.to_utc => 2011-09-10 03:36:00 UTC
```

both dates should be the same, as there is no difference in  GMT and UTC right now.

**Comment by asterite** [comment]
It's a bug, I'll fix it.

**Comment by asterite** [comment]
@beanieboi I just fixed it. Can you try again see if it works well now? To have `crystal` use the standard library you must use `bin/crystal` from the repo, as explained [here](https://github.com/crystal-lang/crystal/blob/master/Contributing.md#contributing-to-the-standard-library)
