### ISSUE TITLE
Parenthesisless method call with (named) tuple arg does not work 

### ISSUE THREAD

**Issue by pkorotkov** [crystal-lang/crystal#2746]
This code does not work as expected (a similar error is thrown in case of named tuples):
```crystal
def f(t : Tuple(Int32)) : Nil
end

f({7}) # <- Works OK.
f {7}  # <- Error.
```
[#link](https://play.crystal-lang.org/#/r/10rd)

**Comment by jhass** [comment]
That's quite intentional, the latter case is parsed as a block, here you have add parens to disambiguate. Our only other possibility would be to demand empty parens for when you do want to pass a block, say `5.times() { 1 }`, which arguably a lot more ugly.

**Comment by pkorotkov** [comment]
Isn't it obvious to the compiler that this method doesn't receive a block?

**Comment by jhass** [comment]
To the compiler yes, to the parser, which makes the distinction here, not. The parser doesn't have any information about what methods are available.

**Comment by asterite** [comment]
Consider this:

```crystal
# parser sees this, it says: let's try and see if it's a tuple or a hash
foo {
  # parser sees "x, ", says "hm... looks like we've got a tuple here!
  # continues a bit more... oh, no, it's not a tuple, it's a block. I have to go back
  x, y = 1, 2
 puts x, y
}
```

Basically yes, some cases are more obvious than other, but we can't have the parser work well in simple cases and work bad in complex cases. It's better to just require a parentheses in this case.

**Comment by pkorotkov** [comment]
OK, fair enough. Probably it requires more wordy error message to avoid racking one's brain what's wrong in this n-th line of code :)

**Comment by asterite** [comment]
Closing this, the error is expected.
