### ISSUE TITLE
Natural / Nat32, Nat... type

### ISSUE THREAD

**Issue by ozra** [crystal-lang/crystal#2747]
It could be nice with a Natural type. It would differ from unsigned in that it has half the range as the corresponding Int of the same bitwidth (that is, the complement bit is simply not used). So it is "compatible" with a same size int.

For all cases where indeces, row, col, counters etc. are used, Natural is a good choice. Since none of them should be less than 0.

Some ideas:
- Types are here to help us signify what values are possible. It does that.
- def [](x : Natural) overloads can do away with check if -1 in code (it can't be)
- LLVM can be passed info about the types range, which helps it optimize even further (use shifts freely when needed _and_ common int compat in overflow evaluations)
- In a low-level optimizing future `Nat|Nil` could be handled specially in compiler implementation, utilizing the MSB to flag that it's a Nil (like 0 flags a Ref|Nil being a Nil)

Con: it "has" to be bounds checked (no more or less true than for any Int-type really though). This is, in that case, (which is a re-occurring theme for me) something I think should be done in dev-compiles only, alternatively add two release modes: `release` and `no-belt` to run wild and free (and fast).

**Comment by straight-shoota** [comment]
There doesn't seem to be particular interest in this idea, so closing.
