### ISSUE TITLE
`each` should supply index in args (instead of having to use `each_with_index`)

### ISSUE THREAD

**Issue by ozra** [crystal-lang/crystal#2748]
I think using index is so commonly used and ditched, back and forth in some situations, and in any event, feels like obvious that it should always be available from `each`.

I benchmarked using `each_with_index` and `each`, without using the index, and as expected LLVM optimizes away the unused code, so there's no slowdown in release compile.

Any reason why not?

**Comment by jhass** [comment]
I think `each_with_index` makes it a lot more obvious what the additional parameter means. Also my experience in Ruby is quite the opposite, you very rarely need the index.

**Comment by kostya** [comment]
each used in enumerable, iterator, and all user classes, would be needed to implement index also.

**Comment by jhass** [comment]
Yes that's another point, `each_with_index` uses `each`, requiring `each` to yield the index makes for a lot more redundant code.

**Comment by ysbaddaden** [comment]
The point is about dropping the `_with_index` variants and have the normal methods yield the index already. This is a legitimate call: less duplication; more enumerable methods could yield the index without adding many methods too.

**Comment by jhass** [comment]
`each` is not implemented by `Enumerable`, it's implemented by the consumer of `Enumerable`, so this means more work for all consumers of it.

**Comment by ozra** [comment]
Some statistics using crystal stdlib src + crystal src, _excluding specs and samples_ (may not be idiomatic code because of contrived code or direct conversions from python etc.):
- 1307 uses of `each` (did not separate `each block` from `each()`)
- 282 uses of `each_with_index`
- That's ~22% - enough to warrant thinking about this
- Briefly looking through the implementations of `each`, `each_index` (and in occurring cases special `each_with_index`) it looks like there will be _less_ code reduction with the change, but this could need some more investigation.

**Comment by jhass** [comment]
I don't think language standard library code is representative for `each_with_index` usage within general user code.

I don't follow how you come to the last point at all.

**Comment by ozra** [comment]
You're probably right on the first one, I'll look into some shards just for some perspective.

I thought it was clear, I'll re-iterate: Just by looking through the different implementations (Array, Hash, Deque, etc. etc.) "mentally refactoring" it _seems to me_ that all in all, there would be less code and duplication if "merging" `each` and `each_with_index`, then keeping them separate. Of course it would require a rewrite _now_, but would be less to maintain and implement in the future.

That however is not even the primary reason I think it should be unified, it would just be a bonus. I simply think index goes as a natural arg available for use at will with `each`.

**Comment by jhass** [comment]
The issue here is rather that we can't yet reuse the implementation from `Enumerable` in types that yield more than one argument in their `each`, yet. Now with all the tuple splatting support and better macro support for them, that might be something to look into again (`Enumerable(*T)`).

Also comparing `each` with `each_with_index` directly is sort of a straw man, I would count indirect usages of `each` that don't require an index too, such as `map`, `reduce`, the whole of `Enumerable` really.

**Comment by ozra** [comment]
I wouldn't go as far as straw man, but I see what you mean - I'll look into those aspects a bit more, just for the meat of it, and see if it gives me some new perspective.

**Comment by asterite** [comment]
I don't think always yielding the index is good. It means forcing implementors to track a counter in every `each` method, while `each_with_index` already does that for you.

For example, [Hash#each](https://github.com/crystal-lang/crystal/blob/0f172aba732520e287eed835763213b40b4df8fd/src/hash.cr#L271-L278) doesn't use a counter, it follows a linked list. And for a Hash consumer, the index is usually not needed. Or for example when traversing a `Set` the index isn't usually important.

Another reason is that when you do `map` or `select` or any other `Enumerable` method you usually don't use the index. Still, `map` would invoke `each` and discard the giving index, generating more code and making things slower in non-release builds (it'll still be more work for the optimizer).

I actually thought about doing this before, but the reasons against it are too many, so I'm closing this.

**Comment by ozra** [comment]
Retro-revisit:

- In another issue (which I can't find atm :-/ ) overloading on block args (_count_) is suggested - that's the ultimate solution, but I know that is far from the ruby way of blocks and would not be accepted - unfortunately.
- Regarding maps (and tagged tuples) I find it most natural to get the _value_ in `each |v|`, _not the key-val pair_ in the argument. The key would be in the additional arg, mirroring index for numerically keyed containers (key and index serve _pretty much_ the same role [there's two sides to which is _more commonly used_ in that story though]: identifying the wanted value in the container), that is: `{"x": 47}.map({|k, v| k == "x" && v == 47 }) => [true]`. There's a reason tuple destructuring was made first class sugar of block-args, no?
- For a container like Set, I agree - an index would be artificial at best. That's why overloaded `each` would be _"the solution"_ imo (that is: "def each(block : (V) -> U) != def each(block : (K, V) -> U)").
