### ISSUE TITLE
[RFC] Add macro method to read a file at compile time

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#2751]
Wanting to embed resources in an executable is probably so common and useful that a special macro method for this would be nice.

**Comment by jhass** [comment]
Related to #2639 and #1649

**Comment by zatherz** [comment]
Bump

**Comment by Sija** [comment]
There's [baked_file_system](https://github.com/schovi/baked_file_system) shard, but admittedly having that in stdlib would be nice - partial impl. of `File` class would come handy too.

**Comment by AlexWayfer** [comment]
@asterite Why closed? Is there a PR / reason for this?

**Comment by NoICE** [comment]
Seems like it's closed because it was implemented already, see crystal/pull/2791

**Comment by Sija** [comment]
@NoICE Actually no, it was closed for other reasons and finally got merged in #6967, sometime later. nvm, it's an ancient history now.
