### ISSUE TITLE
array#delete_at error when index is result of method call

### ISSUE THREAD

**Issue by britt-orville** [crystal-lang/crystal#2762]
`Crystal 0.17.4 [032ab91] (2016-05-26)`

it seems like the following should work, but i get an error

```
arr = ['a', 'b', 'c', 'd', 'e', 'f']
wor = ['b', 'd', 'e']
wor.each {|c| arr.delete_at(arr.index(c)) }
```

```
in ./testword.cr.rb:16: no overload matches 'Array(Char)#delete_at' with type Int32?
Overloads are:
 - Array(T)#delete_at(index : Int, count : Int)
 - Array(T)#delete_at(index : Int)
 - Array(T)#delete_at(range : Range(Int, Int))
Couldn't find overloads for these types:
 - Array(Char)#delete_at(Nil)

wor.each {|c| arr.delete_at(arr.index(c)) }
```

this looks like a bug to me, so i hope this helps.

**Comment by ysbaddaden** [comment]
Array#index returns `nil` if the value can't be found. But Array#delete_at` expects a value of the type contained by the array (Int32 in your example). This can't compile.

**Comment by jhass** [comment]
To clarify, to make your example work, you have to handle the `nil` case:

```cr
arr = ['a', 'b', 'c', 'd', 'e', 'f']
words = ['b', 'd', 'e']
words.each do |word|
  i = arr.index(word)
  arr.delete_at(i)
end
```

If the elements in `arr` are unique or you actually do want to remove all occurrences, there are the following alternatives:

```cr 
arr = arr - words # makes a copy of arr though

words.each do |word|
  word.delete(word)
end

arr.reject! {|word| words.includes? word }
```

**Comment by asterite** [comment]
Speaking of this, should we make `index` raise, and introduce `index?`. Maybe this is more consistent with the rest of the language.

**Comment by jhass** [comment]
Yeah I guess that make sense, though `index?` is the more common usage.
