### ISSUE TITLE
Crash with NoReturn inside while

### ISSUE THREAD

**Issue by yxhuvud** [crystal-lang/crystal#2767]
Hopefully the example is small enough. I cut out some 300 lines or more..

Repro: Check out https://github.com/yxhuvud/hdrhistogram/tree/bug (notice that it should be the bug branch)

run 

crystal build src/hdrhistogram.cr

Bug: trying to downcast (Int32 | Int64) <- Int32
[5670214] ???
[13730548] ???
[13869237] ???
[13779939] ???
[13782435] ???
[13848263] ???
[13855989] ???
[13888320] ???
[13781141] ???
[13782435] ???
[13779874] ???
[13618877] ???
[6570628] ???
[5806717] ???
[5668224] ???
[5804792] main +40
[140107231823920] __libc_start_main +240
[5643793] ???

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues

**Comment by jhass** [comment]
Reduced a bit, I'll let Ary get rid of the array :P

```cr
struct HdrHistogram::Histogram
  def initialize(min : Int64, max : Int64, sigfigs : Int32)
     @counts = Array(Int64).new(10) { 0i64 }
  end

  def value_at_quantile(q)
    ret = 0
    while step!
      if true
        ret = highest_equivalent_value(0i64)
      end
    end
    ret
  end

  def step!
    true
  end

  def highest_equivalent_value(value)
    raise ""
    @counts[1]
  end
end

HdrHistogram::Histogram.new(1i64, 1000i64, 3).value_at_quantile(50)
```

**Comment by kirbyfan64** [comment]
Here's a somewhat smaller test case:

```crystal
struct H
  def initialize
     @c = uninitialized Array(Int64)
  end

  def v
    r = 0
    while s
      if true
        r = h
      end
    end
    r
  end

  def s
    true
  end

  def h
    @c[0]
  end
end

H.new.v
```

**Comment by jhass** [comment]
@kirbyfan64 that no longer reproduces on head for me :/

**Comment by jhass** [comment]
But this does
```cr
class Foo(T)
  def bar : T
    0i64
  end
end

struct H
  def initialize
     @c = Foo(Int64).new
  end

  def v
    r = 0
    while s
      if true
        r = h
      end
    end
    r
  end

  def s
    true
  end

  def h
    raise ""
    @c.bar
  end
end

H.new.v
```

**Comment by asterite** [comment]
Reduced a lot more, crashes with `--prelude=empty`:

```crystal
lib LibC
  fun exit(Int32) : NoReturn
end

x = 'x'
while 1 == 2
  if true
    x = (LibC.exit(0); 1)
  end
end
x
```
