### ISSUE TITLE
Bug: as? crashes the compiler if the cast is invalid

### ISSUE THREAD

**Issue by lbguilherme** [crystal-lang/crystal#2775]
```crystal
1.as String
```

Output: `Error in line 1: can't cast Int32 to String` as expected.

```crystal
1.as? String
```

Crashes the compiler with `Bug: trying to downcast String <- Int32`

**Comment by lbguilherme** [comment]
Would the correct behaviour be always returning nil or raising the same error at compile time? I think the error is saner.

**Comment by lbguilherme** [comment]
But perhaps if it happens inside a lot of macros and the types are "user-provided", a nil could be more useful.

**Comment by jhass** [comment]
The difference between `as` and `as?` is that the former raises and the latter returns `nil`. That should hold in each and any case, everything else is inconsistent.

**Comment by mverzilli** [comment]
Doesn't it feel a bit funny that 

```crystal
123.as? Foo
```
results in a `Foo?` value?

What do you think about deprecating 

```crystal
123.as? Foo
```
In favour of:
```crystal
123.as Foo?
```

**Comment by jhass** [comment]
What if I want to cast a `A|B?` to `B?` wouldn't getting `B?` instead of an exception make me think the original value was `nil` while in fact it was an `A`?

**Comment by mverzilli** [comment]
You're right, we'd be losing information :/.
