### ISSUE TITLE
Request for adding CNAME as tw.crystal-lang.org

### ISSUE THREAD

**Issue by david50407** [crystal-lang/crystal#2794]
Hello,

We (Crystal-TW) are the community that spread the Crystal in Taiwan.

And we are also translating official Crystal document into Chinese Traditional (Taiwan) (a.k.a. zh-TW) now. (And planing for translating the Crystal blog.)

There are informations in Chinese Trad. (Taiwan):

* Web: http://crystal-tw.github.io/
* GitHub: https://github.com/crystal-tw/crystal-tw.github.io

Then we noticed that crystal-jp are also contributing for Japanese document and published to the subdomain, ja.crystal-lang.org [#1719], so we would like to ask for publishing the translated document as subdomain in tw.crystal-lang.org.

We'll maintenance and keep syncing for the document in zh-TW.

If it is okay, the DNS record will be:

```
tw.crystal-lang.org. IN CNAME crystal-tw.github.io.
```

Thank you.

cc @waj @asterite

**Comment by nditada** [comment]
done! can you confirm?

**Comment by david50407** [comment]
@nditada Thank you! And yes, we can see the page on http://tw.crystal-lang.org now! :tada:

**Comment by bcardiff** [comment]
Thanks @david50407 for helping crystal reach taiwan readers!
