### ISSUE TITLE
Block argument unpacking overwrites local variable

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#2796]
```crystal
def foo
  yield({2, 3})
end

x = 1
foo do |(x, y)|
end
puts x # => 2 (expected: 1)
``` 

This is because the above code is syntax sugar for:

```crystal
x = 1
foo do |tmp|
  x, y = tmp
end
```

Regular block arguments have a different behaviour, they don't overwrite local variables.

The fix is to do something smarter than just syntax sugar.

**Comment by jhass** [comment]
Can't we just reuse the code for macro variables here?
