### ISSUE TITLE
Crystal playground error

### ISSUE THREAD

**Issue by ruza-net** [crystal-lang/crystal#2799]
When I start `crystal play` on OS X installed by Homebrew, after opening `localhost:...` it says:
```
ld: library not found for -levent
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc -o "/Users/honzik/.cache/crystal/crystal-run-play-1-1.tmp" "${@}"  -rdynamic  -lssl -lcrypto -lz /usr/local/Cellar/crystal-lang/0.17.4/src/ext/libcrystal.a -levent -lpcre -lgc -lpthread -liconv -ldl`
```

**Comment by jhass** [comment]
You should be able to get around this by manually installing libevent2 via homebrew. Not sure what the package is called there.

**Comment by ysbaddaden** [comment]
This is a common OSX issue with Xcode (it affects many versions, not just El Capitan). Please refer to the documentation:
http://crystal-lang.org/docs/installation/on_mac_osx_using_homebrew.html

**Comment by jhass** [comment]
@ruza-net did the above comment solve your issue?

**Comment by ruza-net** [comment]
Yes. (sorry for long time to respond)

**Comment by Foadsf** [comment]
I already had the latest version of command line tools installed:
> xcode-select: error: command line tools are already installed, use "Software Update" to install updates

but running the `xcode-select --switch /Library/Developer/CommandLineTools` did not solve my problem.
