### ISSUE TITLE
`Dir.current` failing to cross compile

### ISSUE THREAD

**Issue by foca** [crystal-lang/crystal#2806]
Running a program that calls `Dir.current` from OS X 10.11 works fine, but trying to cross compile it blows up in a weird way. I reduced it to this test case (just `puts Dir.current`):

https://gist.github.com/foca/3d48c0e21e46735e63e45742b8c00cd3

* Crystal 0.17.4 (2016-05-26) via Homebrew
* OS X 10.11.5 (15F34)
* clang 7.3.0 (clang-703.0.31)

**Comment by jhass** [comment]
Try ` crystal build test.cr --cross-compile="linux x86_64" --target "x86_64-unknown-linux-gnu"`

**Comment by jhass** [comment]
Should we drop the mandatory parameters to `--cross-compile` and read them from `--target`? /cc @ysbaddaden @asterite

**Comment by ysbaddaden** [comment]
We already read from `--target` now, and no longer use `uname` which, if I understand correctly is what the args for `--cross-compile` used to force. If I'm not mistaken, then we don't need the args anymore.

**Comment by jhass** [comment]
So #2807 would make the command `crystal build current.cr --cross-compile --target "x86_64-unknown-linux-gnu"`, `crystal build current.cr --cross-compile` would "cross" compile for the host target.

**Comment by foca** [comment]
Ah, I feel dumb now. I misread the docs, sorry for the trouble.

**Comment by jhass** [comment]
No worries, you prompted us to improve it! ;)
