### ISSUE TITLE
Matching a captured block with Proc(...) doesn't work

### ISSUE THREAD

**Issue by ozra** [crystal-lang/crystal#2808]
Either I've missed something obvious (capture vs proc?), or this is just another part of the "generics are a bit shaky still"?

``` crystal
def lambdaify1(&blk : Int32 -> U) forall U
  puts U
  blk
end

lamb = lambdaify1 {|x| 1 + x }
puts lamb.call 46


def lambdaify2(&blk : Proc(Int32, Int32))
  blk
end

lamb = lambdaify2 {|x| 1 + x }
puts lamb.call 46

# # Cannot do this:
#
# def lambdaify3(&blk : Proc(Int32, U))
#   puts U
#   blk
# end
#
# lamb = lambdaify3 {|x| 1 + x }
# puts lamb.call 46
```

**Comment by asterite** [comment]
It should work, it's just that the compiler understands what to do for captured blocks when you use the `->` syntax, but not the `Proc` syntax.

**Comment by asterite** [comment]
It seems this is working well in Crystal 0.23.1, so I'm closing this.
