### ISSUE TITLE
Missing error message

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#2819]
Using this branch: https://github.com/jhass/crystal/tree/better_index_error

Running `make`, `make std_spec`,  `make compiler_spec` or `make all_spec` gives a trace but no error message.

I could probably find what change is causing the error with some time, but I'll keep that branch as is until this bug is fixed.

**Comment by asterite** [comment]
I get:

```
in ./src/string.cr:700: wrong number of arguments for 'IndexError.new' (given 2, expected 0, 1, 3)
Overloads are:
 - IndexError.new(index, max, min = -max, *, name = nil)
 - IndexError.new(message = "Index out of bounds")

      raise IndexError.new(user_start, size)
                       ^~~

```

**Comment by asterite** [comment]
The error is wrong, but it's because of #2766 . You'll have to design it differently for now.

You don't get that error when doing `bin/crystal spec/std_spec.cr` ?

**Comment by jhass** [comment]
No, with a HEAD compiler for that I get:

```
Using compiled compiler at .build/crystal
Error in ./spec/std/array_spec.cr:83: instantiating '{}#to_a()'

    ([1, 2] + Tuple.new.to_a).should eq([1, 2])
                        ^~~~

in ./src/enumerable.cr:982: instantiating '{}#[](Int32)'

    ary = [] of T
                ^

```

and variations thereof with the other commands.
```
bin/crystal --version
Using compiled compiler at .build/crystal
Crystal 0.17.4 [ce2f6e2] (2016-06-13)
```
```

**Comment by asterite** [comment]
But how do you generate a HEAD compiler if that doesn't compile in the first place?

**Comment by asterite** [comment]
I'm not sure it's valid to compile a compiler in `master`, then try it on a branch... well, maybe it's valid, but maybe it's simpler to just have it compile in this branch in the first place.

**Comment by jhass** [comment]
I did `git checkout master; git pull; make clean; make; git checkout -; git rebase master`. Clearly this is no different than compiling a third party project with the latest compiler.

**Comment by asterite** [comment]
The problem is that if it compiles in HEAD, it doesn't mean the current compiler (0.17.4) will be able to compile it

**Comment by jhass** [comment]
Sure but entirely irrelevant to the bug report. HEAD is the compiler that's having the issue of the missing error message.

**Comment by asterite** [comment]
@jhass You are totally right. Can you try now and see if you get a complete trace?

**Comment by jhass** [comment]
Yup that worked, thanks!
