### ISSUE TITLE
Implement ptrdiff_t type in C bindings

### ISSUE THREAD

**Issue by papamarkou** [crystal-lang/crystal#282]
At the moment we don't support function input arguments of type ptrdiff_t in bindings to C libraries. The size of ptrdiff_t is chosen so that it can store the maximum size of a theoretically possible array of any type. On a 32-bit system ptrdiff_t will take 32 bits, while on a 64-bit one 64 bits. See [here](http://www.viva64.com/en/a/0050/#ID0E4NAE) for more details. The definition of ptrdiff_t can be found in stddef.h. This is rather fundamental and we should support it in my opinion :)

Normally I would suggest that ptrdiff_t corresponds to an `Int` Crystal type, but this name is already reserved in Crystal, so we may choose another name.

**Comment by lugia-kun** [comment]
Where has `C::PtrDiffT` gone?

At least it does not exist under `LibC` in the current version:
```
> bin/crystal eval 'LibC::PtrDiffT'
Using compiled compiler at .build/crystal
Showing last frame. Use --error-trace for full trace.

error in line 1
Error: undefined constant LibC::PtrDiffT
> bin/crystal version
Using compiled compiler at .build/crystal
Crystal 1.0.0-dev [7d2b41c9a] (2020-08-13)

LLVM: 10.0.1
Default target: x86_64-unknown-linux-gnu
```
