### ISSUE TITLE
Stdlib: Non raising method alternatives where the usage is such that it's an expected error, not an "exception"

### ISSUE THREAD

**Issue by ozra** [crystal-lang/crystal#2826]
(Expected) Failures and (Exceptional) Errors are different things.

There are many methods in stdlib that raise upon failure, where failure in many cases is expected, and thus, in my view, _not_ an exception. The exception then cause a lot of CPU-bloat when the (often) underlying libc-function returns a specific value for failure that could be used instead, also with clearer user code for these expected cases.

## Proposition
I propose that for these cases (I don't identify them specifically here, to allow general discussion on the topic) the core method is implemented as `the_method_ee` (as in "expect errors") that _returns_ either ResultTypes or something like `Exception+` or `Error+` instance - _whichever would be most appropriate overall for Crystal_, and that `the_method` uses the former to decide if to raise or return as usual.

**So:**
- "method_name_ee" returns failure | result
- "method_name" raises on failure else returns result

The `_ee` suffix is just a off-the-top-of-the-head suggestion. Alternatively some Crystal idiomatic way like "method_name?" perhaps, or reversed entirely in favour of explicit failure handling: "method_name!" for the raising counterpart.

**Comment by jhass** [comment]
> I don't identify them specifically here, to allow general discussion on the topic

I think you shoot into your own foot with that. As it stands I find your proposal a terrible idea and that's because I can't think of a case from the top of my head where I agree with

> There are many methods in stdlib that raise upon failure, where failure in many cases is expected

**Comment by ozra** [comment]
@jhass, yes, you're right, specific examples makes it easier to counter with better ways of approaching it, or establish that it might in fact be completely moot because other overheads far outweigh the exceptions.

The obvious candidates are:
- file-ops: in that case the io and syscalls will most likely outweigh, so - _moot_.
- sockets: same here, so - _moot_.

For enumerables etc. where it really would count, we already have `[]?`.

My thinking was regarding someone using it as an attack-vector via a DDOS-attack for instance, but once, say file-open (if relying on exception and not pre-checking) has raised once, the exception tables should be hot in cache, or at least RAM, and thus not be that much of a problem, according to benches made on C++ for comparison.

If profiling some app should show a problem area, it would be simple enough to attack that specific part especially.

So, thanks to you I answered my concerns ;-)

I'm closing.

**Comment by asterite** [comment]
@ozra Actually, your concern makes perfect sense. For example if a server expects JSON input, raising on invalid input allocates unnecessary memory and makes the GC work harder. It would be nice to have a `JSON.parse?` of some sort. However, I think that these conventions already exist: methods ending with `?` return the object or nil, methods without it (with the same name) raise. Otherwise, one can create these "conventions" on each project or library.
