### ISSUE TITLE
Please allow "uninitializing instance variable outside method"

### ISSUE THREAD

**Issue by BlaXpirit** [crystal-lang/crystal#2828]
```crystal
class C
  @a = uninitialized Int32
end
```

`can't uninitialize instance variable outside method` - why?

This is useful when developing bindings to libraries, when you store some low-level object or buffer that will be initialized for sure but it can be hard to prove to the compiler, especially when inheritance is involved.

It could also be a good way in general of telling the compiler "I know what I'm doing, don't make my type nilable", because in my experience the detection of what has been initialized is not ideal (can't see through method calls, has to be right inside `initialize`) and sometimes leads to boilerplate.

**Comment by ozra** [comment]
Yes, some way of saying "I know what I'm doing, it won't be Nil when used, promise! m'kay?" would be helpful. I usually solve it by having dummy class-vars/globals that I point to (in the case of pointers) which is far from a pretty solution :-/ (this just for the small parts of black-arts-low-level-perf-stuff in an app of course)

**Comment by asterite** [comment]
Known workaround:

```crystal
class C
  def initialize
    @a = uninitialized Int32
  end
end
```

But yeah, it should work outside `initialize` too.
