### ISSUE TITLE
Longshot request: follow same-types-methods called from initialize in inference to help DRYness.

### ISSUE THREAD

**Issue by ozra** [crystal-lang/crystal#2831]
A pattern that has re-occured a couple of times for me (sometimes because of pooling, sometimes because of slightly varying initializers, with still lots in common) is the wish to be able to call methods from initialize, and have them verified that they actually does not access uninitialized ivars and are bona-fide parts of init.

The following example is extremely contrived, but to show the "flow" with as little as possible.

```crystal
class Foo
   @a : Int32
   @b : String
   @c : Int32

   def initialize(a : Int32)
      reset a, "Blargh"
      @c = 47
   end

   def initialize(a : Int32, b : String)
      reset a, b
      @c = 42
   end

   def reset(a, @b)
      @a = a + 1
   end
end

a = Foo.new 1
b = Foo.new 1, "Qwo"
```

By going into `reset` (which must be a method on the type) when inferring it would be seen that it's A-OK.

**Comment by asterite** [comment]
This is super hard to do. I'm not sure we'll ever do that. For example Swift has an algorithm that's even dumber/simpler than ours. And I'm afraid we'll maybe have to make ours simpler if we'll want to support incremental compilation.

Initializers are often a few in a method, repeating a bit of code there isn't that terrible (in my opinion).

**Comment by ozra** [comment]
Yeah :-/ Crystal is no doubt in the pole position regarding inference _in my opinion_ (among imperative langs) - so this could be seen as a luxury-problem.

Trade-offs enabling incremental compile will be worth it in the long run.

I'll simply close, and I'll let the cogs work in the back of my head, should I come up with something helpful.
