### ISSUE TITLE
too many block arguments (given 1, expected maximum 0)

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#2837]
minimized example from msgpack-crystal:
```crystal
def bla(x = 1)
  if x == 1
    x + yield 10
  else
    x + yield
  end
end

p bla(1) { |y| 11 }
p bla(2) { 5 }
```
```
too many block arguments (given 1, expected maximum 0)
```

but this works in 0.17.4

**Comment by asterite** [comment]
Yes, this is a breaking change, it's listed in the changelog. you must do `yield nil` to fix this. Now all `yield` must yield exactly the same number of elements. We decided that slipping hidden nils isn't good.
