### ISSUE TITLE
Make `Process.run` be smarter about spaces

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#2845]
Given this program:

```crystal
output = MemoryIO.new
Process.run("echo hola", output: output)
output.close
output.to_s # => ""
```

the output is empty. Maybe that's unexpected.

To fix it, we either have to do:

```cr
output = MemoryIO.new
Process.run("echo", args: {"hola"}, output: output)
output.close
output.to_s # => "hola\n"
```

or:

```crystal
output = MemoryIO.new
Process.run("echo hola", shell: true, output: output)
output.close
output.to_s # => "hola\n"
```

However, `Process.run` could be smarter here: if no explicit arguments are provided, and the `cmd` argument has a space, assume shell is true.

What do you think?

**Comment by jhass** [comment]
I think that I prefer explicitness here, the actual issue is that it doesn't raise with a no such file or directory error. If my executable name comes from a variable, I might not be aware that it has spaces in it (totally valid to have a filename with spaces in it) and suddenly runs with a shell where I didn't expect one.

**Comment by asterite** [comment]
Hm, good point. The process status is an error in the first case, but maybe it should raise indeed, not sure.

**Comment by jhass** [comment]
Yes we should raise if `execve` fails, the process status should solely represent the success or failure state if the process was actually executed, it's not the place for file access errors while trying to load the executable.

**Comment by asterite** [comment]
This is #2088 ?

**Comment by jhass** [comment]
Yes, I had a hunch we have an issue for this but didn't look it up yet :) Removed the newcomer label there, didn't realize it happens inside the fork when I added it, which complicates matters a lot.

**Comment by asterite** [comment]
Let's close this then :-)
