### ISSUE TITLE
Crystal 0.18.0 - Bug: Unhandled exception while parsing request

### ISSUE THREAD

**Issue by costajob** [crystal-lang/crystal#2853]
Hi,

i've updated [my benchmarks](https://github.com/costajob/app-servers) by using Crystal version 0.18.0. I've noticed the console are now logging the following error multiple times when stressed with many requests:

```
Bug: Unhandled exception while parsing request
Error reading file: Connection reset by peer (Errno)
[4310637201] *raise<Errno>:NoReturn +81
[4310903709] *TCPSocket+@IO::FileDescriptor#unbuffered_read<TCPSocket+, Slice(UInt8)>:Int64 +1101
[4310897706] *TCPSocket+@IO#gets<TCPSocket+>:String? +682
[4310878632] *HTTP::Server#handle_client<HTTP::Server, TCPSocket+?>:IO::FileDescriptor? +1160
[4310644534] ~proc(Fiber -> Int64?)@/usr/local/Cellar/crystal-lang/0.18.0/src/fiber.cr:27 +54
...
```

Performance seem slightly better than version 0.17.3, that does not log this error anyway.

**Comment by jhass** [comment]
It probably happened on `0.17.3` already, we just improved logging unhandled errors with `0.18.0`.

**Comment by costajob** [comment]
Thanks, good to know ;)

**Comment by jhass** [comment]
Also not sure what causes it, seems like a normal error, perhaps the benchmark client actually is overdoing itself?

**Comment by costajob** [comment]
That's possible, i'll try limiting wrk requests and let you know asap.

**Comment by costajob** [comment]
Good shot! By limiting request i get no warnings from the console, with the same throughput. 
Never happened before the language i'm testing overwhelmed the stress tool ;)

**Comment by jhass** [comment]
It might also be possible that we're slowly touching OS/kernel limits/territory here.  https://blog.cloudflare.com/how-to-receive-a-million-packets/ should be an interesting read (even though it focuses on UDP opposed to TCP connections).

**Comment by costajob** [comment]
Thanks for sharing, interesting read!
