### ISSUE TITLE
enumerator proposal

### ISSUE THREAD

**Issue by stakach** [crystal-lang/crystal#2864]
I've always found ruby's each method underwhelming. It would be way better if it returned more information:
`['some', 'array'].each { |value, index| ... }`
and
`{:some => 'hash'}.each { |value, key| ... }`

Seems verbose to have to use `each_index` for arrays and then have to look up the value if it is required.

It's a breaking update which is probably why ruby never implemented this change, however I feel it makes a lot of sense and is used widely in JavaScript land.

**Comment by asterite** [comment]
Curious, it was proposed 12 days ago: #2748

See the comments there to know why we chose not to do that.

**Comment by asterite** [comment]
Note that you can use `each_with_index` to get the value and the index at the same time (I mention this because of your comment [here](http://crystal-lang.org//2016/06/14/crystal-0.18.0-released.html#comment-2735316832))

**Comment by stakach** [comment]
Thanks for the quick response! Also loving the progress on the language - great work!
