### ISSUE TITLE
Fetching HTTPs urls using fibers lead to segfault

### ISSUE THREAD

**Issue by Agiley** [crystal-lang/crystal#2869]
Crystal version: **Crystal 0.18.2 (2016-06-17)**
Installed using: `brew install crystal-lang`

While porting a crawler written in Ruby over to Crystal I stumbled upon an issue with fibers and HTTP::Client.

Fetching HTTPs urls using fibers result in Crystal segfaulting. I've managed to replicate this using [Sidekiq.cr](https://github.com/mperham/sidekiq.cr) as well as using [fiberpool](https://github.com/akitaonrails/fiberpool).

I've created a basic app that reproduces the segfault over here: [https://github.com/Agiley/fiber-http-segfault](https://github.com/Agiley/fiber-http-segfault). See the readme for details on how to reproduce the segfault.

Here are also stacktraces from using fiberpool as well as Sidekiq.cr: [https://gist.github.com/Agiley/8890cba116d3f9162163afe810c21c6d](https://gist.github.com/Agiley/8890cba116d3f9162163afe810c21c6d)

Looking through Crystal's source code I saw that there's a conditional macro, LibSSL::OPENSSL_102, so I also tried to uninstall Crystal, install OpenSSL 1.0.2 and reinstalling Crystal again, but to no avail. The macro LibSSL::OPENSSL_102 still evaluates to false, so the code is run the same way as if OpenSSL 0.9.8zh was installed. I'm guessing `brew install crystal-lang` just installs a pre-compiled version of Crystal?

Let me know if you need any more details.

**Comment by jhass** [comment]
Which OpenSSL version (currently none btw) the compiler binary links to is irrelevant. To use a newer OpenSSL on OS X run `brew install pkg-config` and `brew install openssl`.

**Comment by ysbaddaden** [comment]
Wrongly detecting the OpenSSL version is an issue, or maybe it's correctly detected but links to the wrong libssl?

**Comment by jhass** [comment]
I don't see evidence that it's wrongly detected yet, but that's easy to get: @Agiley if you didn't do the two `brew install`s I advised yet, please run `crystal compile` on your program and share the output of `otool -L your_program`.

**Comment by asterite** [comment]
If you run it with `GC_DONT_GC=1` it works fine. Seems to be some variable that gets GC'ed. I see some `Box` in the openssl code and sometimes the reference is not saved somewhere else, like in [here](https://github.com/crystal-lang/crystal/blob/3e798968e23b4fa87036b0bebc38c113eb61429f/src/openssl/ssl/context.cr#L86-L95), though I'm not sure that's the problem (I tried saving the hostname inside a global array but it still crashes).

**Comment by jhass** [comment]
Yes, I can't reproduce with the OpenSSL 1.0.2 codepath active.

**Comment by Agiley** [comment]
@jhass:
`$ brew install pkg-config`
`Warning: pkg-config-0.29.1 already installed`
`$ brew install openssl`
`Warning: openssl-1.0.2h_1 already installed`
`$ brew link --force openssl`
`Linking /usr/local/Cellar/openssl/1.0.2h_1... 1601 symlinks created`
`$ which openssl`
`/usr/local/bin/openssl`
`$ openssl version`
`OpenSSL 1.0.2h  3 May 2016`

[https://github.com/crystal-lang/crystal/blob/master/src/openssl/lib_ssl.cr#L169](https://github.com/crystal-lang/crystal/blob/master/src/openssl/lib_ssl.cr#L169):
`$ (pkg-config --atleast-version=1.0.2 libssl && echo -n true) || echo -n false`
`true`

Compiling / otool:
`$ crystal compile src/fiber_http_segfault.cr`
`$ otool -L fiber_http_segfault `
fiber_http_segfault:
	/usr/lib/libssl.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/usr/lib/libcrypto.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/usr/lib/libpcre.0.dylib (compatibility version 1.0.0, current version 1.1.0)
	/usr/local/opt/bdw-gc/lib/libgc.1.dylib (compatibility version 2.0.0, current version 2.3.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/local/opt/libevent/lib/libevent-2.0.5.dylib (compatibility version 7.0.0, current version 7.9.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)

Same result with compiled Crystal from source:
`$ ~/Programming/crystal/crystal/bin/crystal compile src/fiber_http_segfault.cr`
`Using compiled compiler at .build/crystal`
fiber_http_segfault:
	/usr/lib/libssl.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/usr/lib/libcrypto.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/usr/lib/libpcre.0.dylib (compatibility version 1.0.0, current version 1.1.0)
	/usr/local/opt/bdw-gc/lib/libgc.1.dylib (compatibility version 2.0.0, current version 2.3.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/local/opt/libevent/lib/libevent-2.0.5.dylib (compatibility version 7.0.0, current version 7.9.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)

So it seems to be linked to 0.9.8 somehow.

**Comment by asterite** [comment]
Easier to reproduce:

```cr
require "http/client"

200.times do
  spawn do
    HTTP::Client.get("https://www.google.com")
  end
end

sleep 100
```

**Comment by jhass** [comment]
Okay one issue is that I forgot to update to printf there too, but since this then can't possible get `true` and you're linking to OpenSSL 0.9.8 too, the correct codepath for OpenSSL 0.9.8 should be chosen and thus that is not your issue, it just prevents OS X users from successfully using OpenSSL 1.0.2 for the moment.

However I'm a bit clueless as to why your homebrew installed crystal apparently can't pick up `pkg-config`, I simply don't know enough about `homebrew` to help with that.

**Comment by asterite** [comment]
The problem seems to be that `set_cert_verify_callback` function. If I don't invoke it, everything works fine. If I change it to this:

```cr
    protected def set_cert_verify_callback(hostname : String)
      pp hostname.to_unsafe
      LibSSL.ssl_ctx_set_cert_verify_callback(@handle, ->(x509_ctx, arg) {
        string = Box(String).unbox(arg)
        pp string.to_unsafe
        if LibCrypto.x509_verify_cert(x509_ctx) != 0
          cert = LibCrypto.x509_store_ctx_get_current_cert(x509_ctx)
          HostnameValidation.validate_hostname(string, cert) == HostnameValidation::Result::MatchFound ? 1 : 0
        else
          0
        end
      }, Box.box(hostname))
    end
```

eventually I get this in the console:

```
string.to_unsafe # => Pointer(UInt8)@0x111e33fac
string.to_unsafe # => Pointer(UInt8)@0x111e33e2c
string.to_unsafe # => Pointer(UInt8)@0x111e33eac
string.to_unsafe # => Pointer(UInt8)@0x111e33f2c
string.to_unsafe # => Pointer(UInt8)@0x111e33d2c
string.to_unsafe # => Pointer(UInt8)@0x111e33cac
string.to_unsafe # => Pointer(UInt8)@0x40000000d
Invalid memory access (signal 11) at address 0x400000005
```

So effectively that `hostname` reference is lost... still don't know why.

**Comment by asterite** [comment]
Side note: the `Box` is not needed there, as a `String` is just a reference, we can pass `.as(Void*)` and then `.as(String)` on the callback. In fact... that seems to fix the issue.

Oh, I understand now. `Box.box(...)` allocates memory but nobody retains a reference to it!

**Comment by asterite** [comment]
I'd fix it like that, but I'd also store the `hostname` in a `@hostname` instance variable to make sure a reference to it is not lost. We can probably release 0.18.3 with this fix, but we can wait until tuesday for that in case some other bugs appear.

**Comment by asterite** [comment]
Another side note: `Box.box(...)` should probably return the object itself if it's a reference, instead of allocating more memory, though at the time we wrote `Box` we didn't know how to do that. Maybe somehow checking that `T < Reference` at compile time, not sure that's possible right now. But it's a separate issue.
