### ISSUE TITLE
Sending a block to Regex#match gots error

### ISSUE THREAD

**Issue by david50407** [crystal-lang/crystal#2879]
In [API docs](http://crystal-lang.org/api/Regex.html):

```
/a(sd)f/.match("_asdf_")                          # => #<Regex::MatchData "asdf" 1:"sd">
/a(sd)f/.match("_asdf_") { |md| md[1] }           # => "sd"
```

But now (0.18.2) is doesn't support for block and will get the error:

```
Regex#match' is not expected to be invoked with a block, but a block was given
```

**Comment by jhass** [comment]
I think this is a doc bug and the second call is meant to be a `sub` or `gsub`.

**Comment by david50407** [comment]
@jhass but `match` is not for `replace` right? 
IMO, the second call means "if it's matched, do something", and it will promise that will pass a MatchData to the block or just return `nil` from `#match` (not calling the block)

**Comment by jhass** [comment]
If it would then the `#=> "sd"` is entirely wrong too.

**Comment by david50407** [comment]
I think `#match(..., &block)` returns nil or what the block returned.

**Comment by david50407** [comment]
@jhass If that means to replace something, the return value will be `_sd_` not `sd`, I think

**Comment by jhass** [comment]
No it would replace the entire match. The `match` overload you describe would be redundant to `match(..).try { ... }`

**Comment by david50407** [comment]
Ruby [implements](http://ruby-doc.org/core-2.1.1/Regexp.html#method-i-match) as the same to `match(...).try {...}`.

I think we can just remove these words from api docs is fine.

**Comment by asterite** [comment]
I think it's `String#match` what should be used in those examples, which does have an overload that accepts a block.

**Comment by jhass** [comment]
Oh, if we do have a `String#match` overload that does then we should have one for `Regex` too, out of consistency. I wouldn't mind dropping the `String#match` overload though...

**Comment by asterite** [comment]
The only reason the block version in Ruby exists, according to the docs, is so you can do this:

```cr
str.match(pat) {|m| ...}
```

instead of this:

```cr
if m = str.match(pat)
  ...
end
```

But since the second form is more or less an idiom in Crystal, I think dropping the block form should be fine.

**Comment by jhass** [comment]
And as I pointed out you can still do `.match(pat).try {|m| ... }`.

**Comment by BlaXpirit** [comment]
The problem I have with this change is now there is no way to do matching without overwriting `$~`. A bit of a weird way to do things, but still...

```crystal
if "a" =~ /a/
  "b".match /b/ do |m|
    p m[0]
  end
end
p $~[0]

puts "--------"

if "a" =~ /a/
  if m = "b".match /b/
    p m[0]
  end
end
p $~[0]
```
```
"b"
"a"
--------
"b"
"b"
```
https://carc.in/#/r/13le

Also an interesting moment: `match` is basically an alias to `=~`.

I would prefer `match` not to overwrite `$~`.

**Comment by asterite** [comment]
I don't think `$~` should be used when nesting matches, I'd only use it in simple cases like:

```cr
if foo =~ bar
  # use $~
end
```

or in a case expression. For more complex things I'd use match and keep the match in a variable.
