### ISSUE TITLE
Require'd file issues when using compiler stand-alone

### ISSUE THREAD

**Issue by feifanzhou** [crystal-lang/crystal#2880]
I wanted to use the compiler as a library of sorts to play around with ASTs — for example:

``` crystal
require "./compiler/crystal/syntax/parser"
require "./compiler/crystal/syntax/ast"

input = File.read("input.cr")  # any Crystal source file
res = Crystal::Parser.parse(input) as Crystal::Expressions
p res.expressions
```

I simply copied the `compiler` directory from the `crystal` repo to my project folder. While trying to get this to run, I ran into two build issues:

* It couldn't find `VirtualFile` in [`location.cr`](https://github.com/crystal-lang/crystal/blob/d4550f626e32692b9a9150128afcb4bc3404abcd/src/compiler/crystal/syntax/location.cr#L9). This was "fixed" by adding `require "./virtual_file"`
* It couldn't find `Crystal::SyntaxException` in [`lexer.cr`](https://github.com/crystal-lang/crystal/blob/d4550f626e32692b9a9150128afcb4bc3404abcd/src/compiler/crystal/syntax/lexer.cr#L2566). This was "fixed" by adding `require "./exception"`. I noticed that `require "../exception"` was already there, but that file doesn't define `Crystal::SyntaxException`.

Are these issues a side-effect of trying to run the compiler independently? Or should they actually be fixed (in which case I'd be happy to PR the changes)?

**Comment by ysbaddaden** [comment]
Don't copy the compiler source code, it's available right in the stdlib! Simply `require "compiler"` or a subpart.

**Comment by feifanzhou** [comment]
That would be awesome! Unfortunately it doesn't seem to be that simple …

`Error in ./run.cr:4: while requiring "compiler": can't find file 'compiler' relative to '/Users/Feifan/Developer/crystal-playground'`

I'm on 0.18.2 (Homebrew). It also doesn't look like the Compiler is documented in the [API ref](http://crystal-lang.org/api/).

**Comment by keplersj** [comment]
https://carc.in/#/r/122z

**Comment by jhass** [comment]
@asterite does the homebrew package skip copying the compiler source or something?

**Comment by asterite** [comment]
There's no src/compiler.cr file, you must require a file that exists. Check the samples directory

**Comment by asterite** [comment]
The API isn't documented be caused it's not stable, and no docs, but it's usable. There are a few examples in the samples directory

**Comment by jhass** [comment]
> https://carc.in/#/r/122z

worked though.

**Comment by asterite** [comment]
@feifanzhou The samples are doing the relative require because otherwise they would be using the current compiler, not the next one. Doing this, for instance, works fine:

```cr
require "compiler/crystal/formatter"

source = "[ 1 , 2 , 3].map { | x |  x.to_s  }"
result = Crystal.format(source)
puts result
```

@jhass I don't know why it works, I tried it on my machine and I get an error saying it can't find "compiler". So it must be an issue that only happens on play, maybe there there's a `compiler.cr` file on the path?

**Comment by asterite** [comment]
Strange: https://carc.in/#/r/123n

**Comment by asterite** [comment]
And also: https://carc.in/#/r/123p

Now gives a correct error. Maybe a hicup of play?

**Comment by feifanzhou** [comment]
Ok — updated the `require`:

``` crystal
require "compiler/crystal/syntax/parser"
require "compiler/crystal/syntax/ast"

input = File.read("input.cr")
res = Crystal::Parser.parse(input) as Crystal::Expressions
p res.expressions
```

Now getting the original issues again:

``` crystal
$ crystal run.cr
Error in /usr/local/Cellar/crystal-lang/0.18.2/src/compiler/crystal/syntax/location.cr:9: expanding macro

    getter filename : String | VirtualFile | Nil
    ^~~~~~

in macro 'getter' /usr/local/Cellar/crystal-lang/0.18.2/src/object.cr:254, line 3:

  1.
  2.
  3.         @filename : String | VirtualFile | Nil
  4.
  5.         def filename : String | VirtualFile | Nil
  6.           @filename
  7.         end
  8.
  9.
 10.

        @filename : String | VirtualFile | Nil
                             ^~~~~~~~~~~

undefined constant VirtualFile
```

**Comment by asterite** [comment]
It works if you require "syntax":

```cr
require "compiler/crystal/syntax"

input = File.read("input.cr")
res = Crystal::Parser.parse(input).as(Crystal::Expressions)
p res.expressions
```

You must require "syntax" because it requires all other files. "ast" or "parser" doesn't require all other files.

**Comment by feifanzhou** [comment]
@asterite indeed it does — thank you!
