### ISSUE TITLE
Aliasing descendant class types allow to use class which is not aliased.

### ISSUE THREAD

**Issue by schovi** [crystal-lang/crystal#2881]
Hi,

I am new to Crystal and I am still in phase of playing against documentation. I (maybe) found following bug.

Having this code. One class with 3 descendants:

```crystal
class Animal;end

class Dog < Animal;end
class Cat < Animal;end
class Bird < Animal;end
```

When I want to check type for Dog or Cat:

```crystal
def check_animal(animal : Dog | Cat)
end

check_dog_or_cat(Dog.new)
check_dog_or_cat(Cat.new)
check_dog_or_cat(Bird.new)
```

Error is expected:

```
Error in ./src/main.cr:14: no overload matches 'check_animal' with type Bird
Overloads are:
 - check_dog_or_cat(animal : Dog | Cat)

check_dog_or_cat(Bird.new)
^~~~~~~~~~~~
```

But with aliasing `Dog | Cat` it allows to pass Bird too :S

```crystal
alias DogOrCat = Dog | Cat

def check_alias(animal : DogOrCat)
end

check_alias(Dog.new)
check_alias(Cat.new)
check_alias(Bird.new)
```

EDIT: Version Crystal 0.18.2 (2016-06-17)

**Comment by jhass** [comment]
This is because it currently simplifies the union to the base class in this situation: https://carc.in/#/r/1230

Afaik the plan is to stop doing that, not sure if we already have a tracking issue for that, possibly #2665 or #2733

**Comment by asterite** [comment]
#2661
