### ISSUE TITLE
Missing symbols when linking against OpenSSL

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#2882]
It seems that after https://github.com/crystal-lang/crystal/pull/2560 was merged `-L/usr/lib -L/usr/local/lib` is now always prefixed in the link command. I have OpenSSL installed there, and also in homebrew, but I'd like to use the one in homebrew and I can't because of this. This was working before.

I'm not sure what's the fix. Reverting that change is one way. The PR's concern was FreeBSD, but this change affects all systems. I'm also not sure why we need it, we would need some code that showed that #2560 was needed in the first place.

Extracted from comments [here](https://github.com/crystal-lang/crystal/commit/2b947350ed165d279644fb11aaade0af2d2b4174#commitcomment-17940718) so it doesn't get lost.

@ysbaddaden or @myfreeweb please let us know what you think and how can this be solved. Thank you!

**Comment by jhass** [comment]
Just for reference so we have it clear at the start of the discussion, please provide the output of `pkg-config --libs libssl` on your system (make sure it's run as if called by the compiler, in case that makes any difference).

**Comment by asterite** [comment]
On my machine it's:

```
-L/usr/local/Cellar/openssl/1.0.2h_1/lib -lssl
```

So homebrew is picked up.

**Comment by Agiley** [comment]
This happens for me as well, using the exact same setup as @asterite:
`$ pkg-config --libs libssl`
`-L/usr/local/Cellar/openssl/1.0.2h_1/lib -lssl`

Fixed it by adding ifdef freebsd (not sure if that's the proper way though): [https://github.com/Agiley/crystal/commit/3cf749b6adb62af9d5622c040c77814a3af93028](https://github.com/Agiley/crystal/commit/3cf749b6adb62af9d5622c040c77814a3af93028l)

**Comment by ysbaddaden** [comment]
The initial problem is that on FreeBSD `/usr/local/lib` isn't accessible to the linker unless the default paths (sic) are manually declared to the linker, and most libraries (eg: libevent, libyaml) are installed there.

Can we append the default paths to the linker command so they'd appear after the custom ones?

**Comment by jhass** [comment]
From `ld(1)`: "All -L options apply to all -l options, regardless of the order in which the options appear." Looks like a misremembered, @asterite so pushing to the end looks good to me.
