### ISSUE TITLE
Accessing properties of an abstract struct fails

### ISSUE THREAD

**Issue by splattael** [crystal-lang/crystal#2885]
Hi,

Accessing properties of an abstract struct seems to be failing:

```crystal
abstract struct Entry
  getter uid : String
  getter country : String

  def initialize(@uid, @country)
  end
end

struct MyEntry < Entry
end

entry = MyEntry.new("1", "GER")

p entry.uid # => "1"  CORRECT
p entry.as(Entry).uid # => "GER"  WRONG?
```

@jhass thinks that it might be "codegen fail".

See also: https://carc.in/#/r/125g

Kind regards,
  Peter

**Comment by asterite** [comment]
Seems to happen only if there's one subclass for the abstract class.

**Comment by splattael** [comment]
@asterite That's right! A workaround right now is just to define a second subclass. It works, thanks :-)

**Comment by splattael** [comment]
@asterite :flushed: wow, that was fast. It works like charm.

Thanks a lot :+1:
