### ISSUE TITLE
`self` in inheritance resolves incorrectly

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#2890]
```cr
class Foo
  class Bar < Array(self)
  end
end

Foo::Bar.new << Foo.new # Error
```

`self` incorrectly resolves to `Bar` instead of `Foo`

**Comment by TechMagister** [comment]
**self** refers to the current class definition ( Bar in this case )
```crystal
class Bar < Array(self)
end
```

You can try this way : 
```crystal
class Foo
  class Bar < Array(Foo)
  end
end

Foo::Bar.new << Foo.new # => [#<Foo:0x12adf50>] Foo::Bar
```

**Comment by RX14** [comment]
If I saw the above code snippet, I would be unsure which class `self` refers to, and probably assume it did refer to `Bar`, so I think this is too ambiguous to be allowed.

**Comment by bcardiff** [comment]
Since inheritance with generics is not yet complete, and the sample is a corner case of that I would not care about this yet.

```crystal
class Foo
  class Bar < self
  end
end
```

leads to a parse error, so the usage of `self` is not even clear it should be allowed.

**Comment by asterite** [comment]
I think maybe it should be allowed. In any case in `Array(self)` it resolves incorrectly. For example in Ruby:

```
 $ irb
irb(main):001:0> class Foo
irb(main):002:1>   class Bar < self
irb(main):003:2>   end
irb(main):004:1> end
=> nil
irb(main):005:0> Foo::Bar.ancestors
=> [Foo::Bar, Foo, Object, Kernel, BasicObject]
```

So `self` resolves to `Foo`, not to `Bar`, as this issue suggests.

**Comment by RX14** [comment]
I don't think `Array(self)` is readable at all, whats so bad about specifying which class you mean?

**Comment by asterite** [comment]
@waj needed this in macro generated code, to automatically refer to the containing type. `self` is the only way to do this

**Comment by MakeNowJust** [comment]
@asterite Please reopen it. We can discuss about this more.

`self` type on Crystal is special and Crystal have generics, so there may be `self` or defining type as generics parameter in base class. It makes possible to apply [the idiom called CRTP in C++](https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern). But current implementation does not allow it. We are losing a big possibility.

At least, current implementation lacks coherence against `self` type. I think it don't need to be same as Ruby.

> @waj needed this in macro generated code, to automatically refer to the containing type. self is the only way to do this

We can use `{{@type}}` macro in this case, don't you?

Ref: #3972
