### ISSUE TITLE
Codegen bug with module restriction in in struct

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#2895]
.... or so, I didn't really manage to reduce it any further:

```cr
struct Sized
  include IO

  def initialize(@io : IO)
  end

  def read(slice : Slice(UInt8))
  end

  def write(slice : Slice(UInt8))
  end
end

io = MemoryIO.new
Sized.new(io)
```

produces a segfaulting binary, which I see no reason for.

**Comment by asterite** [comment]
Yeah, I have to think or find the algorithm to detect these recursive definitions and give a proper error.

To understand why it's an error, think of what's the memory representation of that struct, being that is has a member of type IO, and IO contains that struct itself as one of its types.

**Comment by jhass** [comment]
Uh, so it has to be a class? Bummer :/

**Comment by asterite** [comment]
Yes, it has to be a class, there's no other way around it. `IO` is a union of all `IO` types. Because `Sized` is an `IO`, `IO` will be represented as a pair: a type id and the real value (if all `IO`s were reference types we could represent it as a single pointer). The real value has a size that's the maximum value of all the types in the union. But `Sized` is in the union, so we need to compute its type. But `Sized` has an `IO`, which needs its size computed, and so on. It's an infinite recursion.

But by telling this I think I know now how to detect it and give a proper error, I was missing checking modules whose representation is a union.

**Comment by jhass** [comment]
I feel like there's a crazy possible solution to this, like doubling the structs size if a self reference is detected, generating a pointer field for the self reference and have that pointer point to an offset within the now doubled struct that contains the second instance, something like
```
+--------------------------------+
|      Container (64 bytes)      |
+--------------------------------+
|     Sized (32 bytes)           |
+--------------------------------+
| @a : A (8 bytes)               |
| @b : B (8 bytes)               |
| @c : C (8 bytes)               |
| @io : IO<Pointer(IO)> =  +----------+
|                                |    |
+--------------------------------+    |
|           IO (32 bytes)        <----+
+--------------------------------+
| @a : A (8 bytes)               |
| @b : B (8 bytes)               |
| @c : C (8 bytes)               |
| @io : IO<Pointer(IO)> = 0      |
|                                |
+--------------------------------+
```

But probably not worth the effort.

**Comment by asterite** [comment]
Nice ascii! :-)

I'm not sure I understand it, mostly because of the `@a`, `@b` and `@c` which weren't in the original `Sized` struct.

Could this work for any struct? For example:

```crystal
struct Foo
  @x : Int32
  @y : Foo
end
```

How would it be represented then?

**Comment by jhass** [comment]
Ah I didn't really meant the real case, so those are just placeholders. It cannot work for a true self reference, your example you can't even create because You can't create a `Foo` without having a `Foo` (how would it's `initialize` look like in the first place. However in this case we have an ancestry chain, where the parent has no semantical access to the self reference field. If I modify your example accordingly:

```cr
struct Foo
  @x : Int32
end

struct Bar < Foo
  @y : Int32
  @z : Foo
end
```
```
+--------------------------------------------+
|      Container (64 bytes)                  |
+--------------------------------------------+
|               Bar (16 bytes)               |
+--------------------------------------------+
| @x : Int32 (4 bytes)                       |
| @y : Int32 (4 bytes)                       |
| @z : Foo<Pointer> (8 bytes) =  +-----------------+
|                                            |     |
|                                            |     |
+--------------------------------------------+     |
|               Foo (16 bytes)               <-----+
+--------------------------------------------+
| @x : Int32 (4 bytes)                       |
| @  : Int32 (4 bytes) (uninitialized)       |
| @z : Foo<Pointer> (8 bytes)(uninitialized) |
|                                            |
|                                            |
+--------------------------------------------+

```

**Comment by jhass** [comment]
Ah I see now what I was missing. `Bar.new(z: Bar.new(z: Foo.new).as(Foo))` is impossible too model. would need to track the number of nestings and expand the container to the maximum.

Nevermind then.

**Comment by jhass** [comment]
Next idea: automatically box the self reference into heap memory. But that would introduce unexpected/hard to track down heap allocations.

**Comment by asterite** [comment]
@jhass Yes, boxing is one way to solve it, but hidden allocations aren't good, as you say. Modelling it as a class makes this explicit. Alternatively you could have a `Box(IO)` as an instance variable, but there's an allocation there too.

I think for `IO::Sized` it's not that problematic if it's a class because it's a small class, just 16~24 bytes or so.

**Comment by asterite** [comment]
This case is now detected and gives a proper error instead of crashing.

We could later open a separate issue discussing how (and if we want to) implement this, via boxing or another mechanisms. Maybe the safest and fastest thing to do is just keep it an error.
