### ISSUE TITLE
installing ubuntu dual boot with win 10 on HP 850qe

### ISSUE THREAD

**Issue by pom4pom** [crystal-lang/crystal#2907]
I just got a brand new HP Envy Phoenix 850qe desktop preinstalled with Win 10 (no other option), 
I created a bootable Ubuntu 16.04 LTS on to a DVD, this DVD work just fine allowed me to run from the DVD to check this out on my win 7 Dell desktop but this DVD does not seem to work on my new win 10 PC, DVD just keep accessing but nothing happens.

I am about to call HP support to replace this wIn 10 with win 7, thought I ask around first.

Appreciate any comments.

thanks

**Comment by pom4pom** [comment]
Sorry if my question is not appropriate for this blog.

**Comment by jhass** [comment]
This is not a blog. It's also not a support forum. This is a Github repository where people collaborate on developing the Crystal programming language. I have no idea how you ended up here.

**Comment by pom4pom** [comment]
sorry.

On Fri, Jun 24, 2016 at 7:33 AM, Jonne Haß <notifications@github.com> wrote:

> Closed #2907 <https://github.com/crystal-lang/crystal/issues/2907>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/crystal-lang/crystal/issues/2907#event-703476657>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACqwN0U1LTpnxaf_NlTUt1BU5I7nVY8Nks5qPBT8gaJpZM4I994A>
> .
>



-- 
Pom
