### ISSUE TITLE
HTTP::Server bug on keep alive request

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#2908]
The problem is in these lines: https://github.com/crystal-lang/crystal/blob/fd9bd6fc571ebc42c311fb54890946930f43cb0a/src/http/server.cr#L171-L176

On the `rescue` branch `request` must be set to `nil`, otherwise on an exception it will keep the value of the previous iteration, which is wrong.

The fix is easy, but I'd like to add a spec to prevent regressions... but I don't know how to easily do it.

Originally discovered by @mverzilli and @waj

**Comment by jhass** [comment]
We probably should allow injecting the server socket instead of forcing it to be build by `HTTP::Server` itself. Then the tests can just inject a fake backed by `MemoryIO` or similar. That would also solve #2735

**Comment by asterite** [comment]
There's another issue: when the IO is closed the server tries to response with an error, many times, but the IO is closed. This ends up bubbling an exception to main.
