### ISSUE TITLE
Variable set to nil if not tested

### ISSUE THREAD

**Issue by TechMagister** [crystal-lang/crystal#2915]
I found this strange bug looking the XML library example : 
```crystal
require "xml"

xml = <<-XML
 <person id="1"/>
XML

document = XML.parse(xml)             # : XML::Node
person = document.first_element_child # : XML::Node?

puts person["id"] # "1" : String?
```
It raise this exception : 
```
Error in line 10: undefined method '[]' for Nil (compile-time type is (XML::Node | Nil))
```

But by surrounding the last line with a if statement ```if person ... end``` ... it works and print "1"

Something I missed ?

Not working : https://play.crystal-lang.org/#/r/12hg
Working : https://play.crystal-lang.org/#/r/12hf

Crystal 0.18.4 (2016-06-22)

**Comment by jhass** [comment]
` XML::Node?` means ` XML::Node|Nil`, so ` XML::Node` or `Nil`. `nil` is falsey so the compiler knows it won't pass `if person` and the type reduces to ` XML::Node`.

See http://crystal-lang.org/docs/syntax_and_semantics/union_types.html and http://crystal-lang.org/docs/syntax_and_semantics/if_var.html

**Comment by TechMagister** [comment]
Ok, it wasn't obvious at first but now I better understand why it works like this.
Sorry about that, I'll read carefully the doc from now ^^"
