### ISSUE TITLE
Calling response.cookies mutates response.headers

### ISSUE THREAD

**Issue by mperham** [crystal-lang/crystal#2920]
When I get an HTTP::Client::Response with a Set-Cookies header, calling `response.cookies` actually [destroys the Set-Cookies header](https://github.com/crystal-lang/crystal/blob/9bb0ada8cf0d77d6b3dd17c99ff92bea32083325/src/http/cookie.cr#L155), meaning I cannot resend the headers in the next request:

```ruby
    # make first request without cookies
    request = HTTP::Request.new("GET", "/")
    response = call_request_on_app(request)
    cookie = response.headers["Set-Cookie"]?
    cookie.should_not be_nil
    # this destroys the Set-Cookie header due to https://github.com/crystal-lang/crystal/blob/9bb0ada8cf0d77d6b3dd17c99ff92bea32083325/src/http/cookie.cr#L155
    response.cookies[Kemal::Session::NAME].value.should eq(sid)
    lastsid = sid
    existing.should be_nil

    # make second request with the cookies that were set in response
    request = HTTP::Request.new("GET", "/", response.headers)
    response = call_request_on_app(request)
    cookie2 = response.headers["Set-Cookie"]?
    cookie2.should_not be_nil
    cookie2.should eq(cookie)
    response.cookies[Kemal::Session::NAME].value.should eq(lastsid)
    existing.should eq("abc")
```

**Comment by asterite** [comment]
Good point. I don't know why there's code for deleting the header value at that point.

**Comment by jhass** [comment]
IIRC it's for https://github.com/crystal-lang/crystal/blob/9bb0ada8cf0d77d6b3dd17c99ff92bea32083325/spec/std/http/request_spec.cr#L43

**Comment by asterite** [comment]
@jhass I mean, why the header has to be deleted when creating the Cookies object.

If I remove those two lines, the only failing spec is [this one](https://github.com/crystal-lang/crystal/blob/9bb0ada8cf0d77d6b3dd17c99ff92bea32083325/spec/std/http/request_spec.cr#L105-L111), failing on line 110. I wouldn't modify the headers object in that method and simply expect headers to remain the same.
