### ISSUE TITLE
Dynamic array type

### ISSUE THREAD

**Issue by martinandert** [crystal-lang/crystal#2926]
Shouldn't this be possible:

```crystal
t = Int32
x = Array(t).new # => expecting token 'CONST', not 't'
```

I also tried

```crystal
t = Int32
x = [] of t
```

resulting in the same error being raised.

Since I'm relatively new to Crystal, I might be missing something really obvious here.

**Comment by asterite** [comment]
You can't do it exactly like that, but it's still possible: https://play.crystal-lang.org/#/r/12oi

```cr
def array_of(x : T.class)
  [] of T
end

t = Int32
ary = array_of(t)
p ary
p ary.class

t = String
ary = array_of(t)
p ary
p ary.class
```

**Comment by asterite** [comment]
But of course, whatever the solution... what do you need this for?

**Comment by martinandert** [comment]
Wow that was quick. Thanks!

> But of course, whatever the solution... what do you need this for?

I was studying https://github.com/graphql/graphql-js/blob/1ed070fed63767e82470ca39d036539b99693c4c/src/language/parser.js#L1138-L1150 and wondered how these lines would translate to Crystal.

**Comment by asterite** [comment]
You would do something like this:

```cr
def any(parser, open_kind, parse_fn, close_kind)
  nodes = [] of typeof(parse_fn.call(parser))
  until skip(parser, close_kind)
    nodes.push parse_fn.call(parser)
  end
  nodes
end
```

Or:

```cr
def any(parser, open_kind, parse_fn : Parser -> U, close_kind)
  nodes = [] of U
  until skip(parser, close_kind)
    nodes.push parse_fn.call(parser)
  end
  nodes
end
```

But maybe instead of using a callback function one would use a block?

```cr
def any(parser, open_kind, close_kind)
  nodes = [] of typeof(yield parser)
  until skip(parser, close_kind)
    nodes.push(yield parser)
  end
  nodes
end
```

**Comment by martinandert** [comment]
Thanks, @asterite! I think I'd go with your second suggestion since it looks the cleanest and most intelligible to me.

PS. I love the syntax of turning a method into a Proc with `->method`. This would become useful here.
