### ISSUE TITLE
formatter should rewrite single quote strings

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#2931]
when copy most code from ruby not easy to replace all places with `'` to `"`, may be formatter can do it automatically for strings size > 1

or we need a tool to first convert from ruby to crystal.

**Comment by rmosolgo** [comment]
:hand: for my part, I _like_ that Crystal requires `"`, it puts and end to one silly style question from Ruby! (And using it to distinguish between Char and String is a good reason for it)

**Comment by rmosolgo** [comment]
Oh, I understand now that this is for the formatter, not the compiler, so only `"` would be valid for compilation :ok_hand: either way

**Comment by bcardiff** [comment]
👎 next thing will be to replace attr_accessor with property.
Maybe is more appropriate for a migration tool that will point/suggest some changes.
Like `&:` to `&.`, and type annotations for `[]`
Or tips like checking if a hash could become a named tuple.

welcome to _how to crystallize a ruby_ :-P
