### ISSUE TITLE
Visibility modifiers

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#2934]
Hi,

Is there any reason not to include block visibility modifiers?
Many languages have it as it's a convenient way to set visibility scope for the whole block of methods.

See:
```ruby
class MyClass
 
  def the_public_method
    # ...
  end
 
  private
 
  def first_private_method
    # ...
  end
 
  def second_private_method
    # ...
  end
 
  protected
 
  def the_protected_method
    # ...
  end
 
end
```

**Comment by bcardiff** [comment]
See https://github.com/crystal-lang/crystal/pull/1705#issuecomment-146066667 and the following comments.

**Comment by Sija** [comment]
@bcardiff Thanks!
