### ISSUE TITLE
Crystal compiler error OSX (El Captain)

### ISSUE THREAD

**Issue by EnesTanriover** [crystal-lang/crystal#2937]
Hi,

I'm trying to compile my first helloworld project, but compiler give to me an error; I'd searched on these 'crystal-lang' issues and stackoverflow none of post doesn't help to me...

```
sh-3.2# crystal build --release src/helloworld.cr
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _*IO::Encoder#write<String::Builder, Slice(UInt8)>:Nil in _main.o
      _*IO::FileDescriptor@IO#write_utf8<Slice(UInt8)>:Nil in _main.o
  "_iconv_close", referenced from:
      _~procProc(Pointer(Void), Pointer(Void), (Int32 | Nil))@/usr/local/Cellar/crystal-lang/0.18.6/src/gc/boehm.cr:94 in _main.o
  "_iconv_open", referenced from:
      _*IO::Encoder::new<IO::EncodingOptions>:IO::Encoder in _main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc -o "/Users/enes/Documents/crystal/helloworld/helloworld" "${@}"  -rdynamic  `pkg-config --libs libssl || printf %s '-lssl -lcrypto'` `pkg-config --libs libcrypto || printf %s '-lcrypto'` -lpcre -lgc -lpthread /usr/local/Cellar/crystal-lang/0.18.6/src/ext/libcrystal.a -levent -liconv -ldl -L/usr/lib -L/usr/local/lib`

```

My GCC Version : 

`Apple LLVM version 7.3.0 (clang-703.0.31)`

**Comment by benoist** [comment]
May I ask how did you installed crystal?

**Comment by EnesTanriover** [comment]
I followed [crystal-lang.org/docs/...](https://crystal-lang.org/docs/installation/on_mac_osx_using_homebrew.html) this link

**Comment by benoist** [comment]
Did you have MacPorts installed?

**Comment by EnesTanriover** [comment]
No, Now I've installed but the problem continues...

**Comment by benoist** [comment]
The reason I asked is because Homebrew and macports don't really work well together. I stopped using macports in favor of homebrew and never required it again.

Ok next question: Which version of XCode have you got installed? Did you also install the developer tools from xcode by using xcode-select --install?
I've had it sometimes where xcode was a bit screwed after upgrade and I had to remove xcode completely and reinstall it via the app store.

**Comment by EnesTanriover** [comment]
Xcode version is : 7.3.1 and yes I did use these option "xcode-select --install", Now I will delete Xcode and reinstall from appstore.

**Comment by EnesTanriover** [comment]
Thank you! Reinstalling Xcode is solved my problem

**Comment by fibric** [comment]
Have you tried installing [those libraries](https://github.com/crystal-lang/crystal/wiki/All-required-libraries#mac-osx-with-homebrew)?
