### ISSUE TITLE
bug with time::span milliseconds?

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#2938]
```
crystal eval 't = Time.now; sleep 1; p (Time.now - t).milliseconds'
```
print 1
but expected 1000

**Comment by asterite** [comment]
`milliseconds` returns the milliseconds **component** of the timespan.

```cr
t = Time.now
sleep 1
diff = Time.now - t
pp diff, diff.milliseconds, diff.total_milliseconds
```

Output:

```
diff                    # => 00:00:01.0045740
diff.milliseconds       # => 4
diff.total_milliseconds # => 1004.574
```

Note that the `4` matches the 4 in `00:00:01.0045740`

This is only confusing because Time and Time::Span lack documentation.

**Comment by kostya** [comment]
i think methods for convertations should exists, like: `as_milliseconds`.

**Comment by asterite** [comment]
@kostya aren't those `total_seconds`, `total_milliseconds`, etc?

**Comment by kostya** [comment]
wow, not see them :)
