### ISSUE TITLE
Where is the API documentation for macro nodes?

### ISSUE THREAD

**Issue by mosop** [crystal-lang/crystal#2944]
As I remember, I could find API documentation for macro nodes under Crystal namespace. Is it deleted or moved? Thank you.

**Comment by asterite** [comment]
Oooh... you found it :-(

It's a bug in the docs generator and/or the builtin module. The Crystal module is predefined and has its location hardcoded. It worked when I manually built the docs, but now that there's an automatic process it somehow fails. I have to review this.

**Comment by mosop** [comment]
@asterite Thank you!!! Because I can still read source code, it's almost OK now.

**Comment by bcardiff** [comment]
@asterite either we update the build acripts from master to releas-0.18 branch or upon 0.18.7 we will need to build and upload the docs. Either way we could upload a new docs of 0.18.6 with macro nodes tomorrow

**Comment by asterite** [comment]
@bcardiff Don't worry, I'll release 0.18.7 today and this is fixed there

**Comment by bcardiff** [comment]
./bin/ci in release-0.18 is not up to date to sync the docs with s3. Those chances are in master (i should have done in other branch and merge the to master and release-0.18)

**Comment by asterite** [comment]
@bcardiff Do you want to cherry pick those changes into `release/0.18`? I didn't put that tag yet.

**Comment by asterite** [comment]
@bcardiff I'll just add a commit that updates those files in 0.18, I guess that should fix it

**Comment by bcardiff** [comment]
cherry-pick 18 commits :-( or squashed them in one (which would be the same as cp /bin/ci and .travis.yml from master). Whatever you prefer.

**Comment by asterite** [comment]
@bcardiff Yes, I'll copy them, I thought there would be differences but I don't think so :-)
