### ISSUE TITLE
crystal should optimize unmodified variables

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#2956]
example:

```crystal
def bla
  rand < 0.5 ? {"error" => "some error"} : {"result" => "ok"}
end

NO  = {"error" => "some error"}
YES = {"result" => "ok"}
def bla2
  rand < 0.5 ? NO : YES
end

t = Time.now
s = 0
1000000.times do
  s += bla["result"]? ? 0 : 1
end
p s
p Time.now - t

t = Time.now
s = 0
1000000.times do
    s += bla2["result"]? ? 0 : 1
end
p s
p Time.now - t
```

```
499713
00:00:00.3150560
500048
00:00:00.0218500
```

**Comment by rmosolgo** [comment]
:cry: you have to know whether the object is mutated on the outside, right? 

for example, the two are different in this case:

```crystal 
some_hash = bla2
some_hash["bogus_key"] = "bogus_value"
puts bla2
# => {"result" => "ok", "bogus_key" => "bogus_value" }

some_hash = bla
some_hash["bogus_key"] = "bogus_value"
puts bla
# => {"result" => "ok"}
```

**Comment by rmosolgo** [comment]
Since the built-in data types are mutable, you'd have to track: 

- returned values 
- yielded values 
- values passed to other methods 
- values assigned to instance variables, class variables or constants 

😢  again, seems prohibitively difficult!

**Comment by rmosolgo** [comment]
Actually, @asterite can do anything, so I shouldn't have said "prohibitively difficult" !

**Comment by kostya** [comment]
yes this should be difficult, my problem solved by, there time is equal

```crystal
def bla
  rand < 0.5 ? {error: "some error"} : {result: "ok"}
end

NO  = {error: "some error"}
YES = {result: "ok"}
def bla2
  rand < 0.5 ? NO : YES
end
```

i used hashes to return it json.

**Comment by asterite** [comment]
This is explained here: https://crystal-lang.org/docs/guides/performance.html

(avoid creating temporary objects over and over)

I think adding this logic in the compiler is **very** hard.
