### ISSUE TITLE
Improved GC?

### ISSUE THREAD

**Issue by mperham** [crystal-lang/crystal#2958]
Any plans to work on an improved GC?  Rubinius has an old GC here implemented mostly in Ruby which could be reworked into native Crystal:

https://github.com/rubinius/rubinius/tree/3adc277cb1ac964ffb1d72226555b34a5d803cc0/lib

@evanphx is the author of all that code and is fine relicensing it if Crystal wants to use it.

**Comment by sdogruyol** [comment]
Is this a single threaded mark and sweep GC?

**Comment by asterite** [comment]
I think writing a GC for a VM-based language and a compiled language are two very different things. In a compiled language you have to scan the stacks, and in Crystal one would have to scan threads and fibers, so the GC is bound to a totally different runtime organization.

I think with time we'll write our own GC. I really hope we can have a super good GC, close or like Go's GC or Java's GC, but of course that will require a huge amount of time and effort.

**Comment by mperham** [comment]
@sdogruyol I don't know the particulars of that impl, I'm not really much of a GC expert.

@asterite I know that Golang is moving toward a [transactional GC](https://docs.google.com/document/d/1gCsFxXamW8RRvOe5hECz98Ftk-tcRRJcDFANj2VwCB0/edit) which would be perfect for app servers and job servers like Sidekiq where a daemon is processing Units of Work.  Thanks for the info.
