### ISSUE TITLE
Peculiar Invalid Memory Access errors on previously working code (0.18.7)

### ISSUE THREAD

**Issue by ozra** [crystal-lang/crystal#2969]
A heads up post, I'll add to it later when/if I can find a minimalistic reduction that reproduces.

1. One class `Foo`, has dozens and dozens of subclasses, `BarA`, `BarB`... All work as expected, except one of them, when accessing an inherited ivar (instances of all types are iterated and the ivar in question set, if I skip the action on that specific class, it works. So it's like one ivar from Foo has been corrupted in compilation in only one of all subclasses!!?
2. Another case is a variable that isn't set in every branch. When tested subsequently, it is truthy (but has in fact not been set) and crashes upon inspection. If I explicitly set it to nil in the branch where it's not touched, it works as expected.

Once again, I know, _this is a lousy bug-report_ - I'll keep trying to get a good reproduction and follow up with.

**Comment by jhass** [comment]
Would you mind if we close this and you open new issues with reproduction cases for each?

**Comment by ozra** [comment]
Good idea @jhass, I made this issue as a "reminder", but it's less helpful than a todo on my private actions list, so I'll simply open new when/if I can make a concise report.
