### ISSUE TITLE
Hash#key? 

### ISSUE THREAD

**Issue by greyblake** [crystal-lang/crystal#2970]
I am little bit confused with `Hash#key?` method. I expect it to check present of a given a key in a hash (like it works in Ruby), but actually it does different thing.

From the doc:
> Returns the first key with the given value, else nil.

```crystal
hash = {"foo": "bar", "baz": "qux"}
hash.key?("bar")    # => "foo"
hash.key?("qux")    # => "baz"
hash.key?("foobar") # => nil
```

What I would expect instead:
```crystal
hash = {"foo": "bar", "baz": "qux"}
hash.key?("bar") # => false
hash.key?("baz") # => true
```

Is this method done this way on purpose?

**Comment by sdogruyol** [comment]
Well Crystal has `has_key?("key")` for that.

**Comment by greyblake** [comment]
Ahh.. Cool! Thanks, @sdogruyol !
