### ISSUE TITLE
Reason for weird annotation methodology preference over normal method annotations?

### ISSUE THREAD

**Issue by sardaukar** [crystal-lang/crystal#2976]
Hey, if this has been debated already on some other issue, please excuse me (I did try to search for it) and just refer me to the issue number.

I'm kinda confused as to why this works:
```crystal
class B; end

class A
  @var : B

  def initialize
    @var = init_a
  end

  def init_a
    B.new
  end
end

a = A.new
```

but not the (IMHO) more intuitive:
```crystal
class B; end

class A
  def initialize
    @var = init_a
  end

  def init_a : B
    B.new
  end
end

a = A.new
```

I don't see the value in adding a weird new kind of annotation, instead of relying on an existing mechanism in the language already in the form of method annotations. Kinda raises the barrier for Ruby crossover skills, doesn't it? :)

Will this change with the new compiler codebase? If not, I'd love to know the reason for it.

Thanks!

**Comment by asterite** [comment]
The main issue is that it needs type and method resolution. `init_a` could be defined there, on in the top-level namespace. The method could have arguments so we'd need to resolve their types, but their types might be in local variables, etc.

So yes, for these simple cases it *could* be done, but in the general case it's harder, so we prefer to keep things consistent for now: it doesn't work in either case.

**Comment by asterite** [comment]
And no, this will probably never change.

**Comment by sardaukar** [comment]
Thanks for the explanation. I'll add this to the list of things I'd do differently like not requiring parenthesis for method arguments, and not needing commas at the end of multiline hash or array definitions :D

**Comment by asterite** [comment]
@sardaukar The commas are not needed, this compiles fine for me:

```cr
a = [
  1,
  2
]

h = {
  1 => 2,
  3 => 4
}
```

However, the formatter does add a trailing comma, because in my opinion it's so much easier to add elements and to rearrange them this way.

**Comment by sardaukar** [comment]
I meant back in Crystal 0.6 I think when you could do 
```crystal
a = [
  1
  2
]
```

**Comment by asterite** [comment]
@sardaukar That was a bug, it was never intended to be that way. Is there another language that allows that?

**Comment by sardaukar** [comment]
Don't think so. But can't really see why a newline can't replace a comma token for this case. Again, matter of taste I guess

**Comment by kirbyfan64** [comment]
@asterite CoffeeScript and MoonScript both allow newlines to replace commas. I swear there was another one, too, but I can't recall...

**Comment by phase** [comment]
Newlines does look a lot cleaner. I hate looking at Rust or Java code that has a bunch of trailing commas.

```java
public enum Direction {
    NORTH,
    EAST,
    SOUTH,
    WEST,
}
```

This looks ugly. The last comma is their to fit with the other ones which shouldn't be there in the first place.

```java
public enum Direction {
    NORTH
    EAST
    SOUTH
    WEST
}
```

This looks clean compared.

```rust
enum Opcode {
    Move,      // Copy a value between registers
    LoadK,     // Load a constant into a register
    LoadBool,  // Load a boolean into a register
    LoadNil,   // Load nil values into a range of registers
    GetUpVal,  // Read an upvalue into a register
    GetGlobal, // Read a global variable into a register
    GetTable,  // Read a table element into a register
    SetGlobal, // Write a register value into a global variable
    SetUpVal,  // Write a register value into an upvalue
    SetTable,  // Write a register value into a table element
    NewTable,  // Create a new table
}
```

Again, commas for the sake of it. If there's a newline, it should act as a comma in this context.

**Comment by ozra** [comment]
In Onyx commas are optional in multi line structural literals, also in LiveScript (where I stole the idea from), and it seems to work fine. If you have ideas for why it's bad, that could help me out also, removing it before I depend on it ;-)

**Comment by waterlink** [comment]
In LISP comas are not used at all ;)
Oscar Campbell <notifications@github.com> schrieb am Di., 12. Juli 2016 um
2:04 AM:

**Comment by ysbaddaden** [comment]
@phaze enums are a bad example, there are no commas for them in Crystal:

```crystal
enum Direction
  North
  East
  South
  West
end
```

Only literals need commas (Array, Tuple, Hash, NamedTuple), so there is only one representation for them, whatever if they're on a single line or on multiple ones.
