### ISSUE TITLE
String-based Enums types

### ISSUE THREAD

**Issue by chendo** [crystal-lang/crystal#2978]
I'd like to have the ability to have `String` based `Enum`s. My current use case is I'm using `JSON.mapping` to turn JSON output into typed classes, but I'd like the ability to do something like this:

```
enum EventType : String
  Pending = "PENDING"
  InProgress = "IN_PROGRESS"
  Complete = "COMPLETE"
end

struct Event
  JSON.mapping({
     name: String,
     event_type: EventType
  })
end
```

I'm not sure how a `event_type` value that doesn't match should work, maybe some sort of catch all `EventType::Other` like how there's `All` and `None` for the integer ones?

Thoughts?

**Comment by bcardiff** [comment]
I would suggest using a formatter for converting the string to symbols.

**Comment by chendo** [comment]
I'd like to be able use types to mitigate errors so I can catch typos easily.

For example:


`Event.create(name: "Foo", type: Pending)`

The other option is to write my own struct that I can subclass and do that, but `Enum` seems like a better fit for this.

**Comment by ysbaddaden** [comment]
`Enum#new(JSON::PullParser)` accepts both an Integer (the enum value) or a String (the enum key), so you may just override the `to_json(io)` method to output the key instead of the value and you'll have it working as you expect; you'll just have upcased keys:

```crystal
require "json"

enum EventType
  PENDING = 1
  IN_PROGRESS = 2
  COMPLETE = 3

  def to_json(io)
    io << '"'
    to_s(io)
    io << '"'
  end
end

struct MyEvent
  JSON.mapping({
    name: String,
    event_type: EventType,
  })
end

p event = MyEvent.from_json("{ \"name\": \"blabla\", \"event_type\": \"PENDING\" }")
# => MyEvent(@name="blabla", @event_type=PENDING)

puts event.to_json
# => {"name":"blabla","event_type":"PENDING"}
```

**Comment by david50407** [comment]
enum is `Value` type but String is a `Reference` so I think that is hard to enum a String?

BTW, if we can provide the convert rules in `JSON.mapping` (like giving a NamedTuple?) will be better.

**Comment by akzhan** [comment]
I believe that this issue should be closed as "status:wantfix".

**Comment by straight-shoota** [comment]
The example from @ysbaddaden shows, that the intended result can already be achieved in a different way.

BTW `to_json` is even simple nowadays: `builder.string self`

**Comment by asterite** [comment]
Let's close this. Enums need an integer value. For a string representation the solutions above are good enough.

**Comment by Qard** [comment]
I disagree those solutions are good enough. Right now I'm dealing with DWARF section names and need something like:

```crystal
enum SectionType
  DEBUG_INFO
  DEBUG_ABBREV
  # ...

  def to_s(io)
    io << case self
    when DEBUG_INFO     then ".debug_info"
    when DEBUG_ABBREV   then ".debug_abbrev"
    # ...
    else
      raise "Unknown section: #{self}"
    end
  end
end
```

rather than a much simpler:

```crystal
enum StandardSection
  DEBUG_INFO = ".debug_info"
  DEBUG_ABBREV = ".debug_abbrev"
  # ...
end
```

Directly encoding the key would be incorrect, I need the correctly formatted string, which can't be expressed with the identifier-valid character set. I want the type-safety of being able to select only from the list while also being able to get the correct string. The syntax as it is presently is quite clumsy for this sort of use case.

**Comment by straight-shoota** [comment]
Related discussion:
* https://github.com/crystal-lang/crystal/issues/14228
