### ISSUE TITLE
Request: allow custom indent in `to_pretty_json`

### ISSUE THREAD

**Issue by silverweed** [crystal-lang/crystal#2979]
Currently, the indent string for `JSON::PrettyWriter` is hardcoded as `"  "` (https://github.com/crystal-lang/crystal/blob/68783f1ebdd5b9bbefc8892ddbc200fe1f13bbea/src/json/to_json.cr#L132)

It's be nice if `to_pretty_json` and related methods accepted an optional `indent_string` parameter allowing the user to specify a custom indent string (e.g. tabs).
If this were to excessively bloat the methods, perhaps one could define a module variable (or an `Object`'s class variable) `indent_string` to be used for every serialized object instead of the default one.

**Comment by david50407** [comment]
In [JSON standard](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) :

> Insignificant whitespace is allowed before or after any token. The whitespace characters are: character tabulation (U+0009), line feed (U+000A), carriage return (U+000D), and space (U+0020). Whitespace is not allowed within any token, except that space is allowed in strings.

That means TAB (\t) is not a valid indent char in JSON, maybe we can only provide `indent_size : Int` for the option when calling `#to_pretty_json`?

**Comment by jhass** [comment]
Uhm, `\t` is U+0009

**Comment by david50407** [comment]
Oh oops, my fault, I missed it

**Comment by david50407** [comment]
I think providing a string as indentation is not a good idea, maybe we can provide `indent_size` and `indent_type` (this can only be **space** and **tab** , maybe symbol or enum?)

**Comment by silverweed** [comment]
I was taking Go's [MarshalIndent](https://golang.org/pkg/encoding/json/#MarshalIndent) as an example, which allows an 'indent' string parameter

**Comment by asterite** [comment]
I think a string is good because then one can choose spaces or tabs very easily

**Comment by silverweed** [comment]
Thank you @asterite :)
