### ISSUE TITLE
ECR doend't support silent (<%- %>) tags?

### ISSUE THREAD

**Issue by beno** [crystal-lang/crystal#2980]
I am trying to generate some Javascript output from a Crystal template, so I need precise control over the output. But with the current ECR I get newlines all over the place, which makes ECR unsuitable for my use case.

Am I missing anything? Thoughts?

**Comment by jhass** [comment]
ECR definitely should support byte precise control over the output, contributions into that directions are welcome!

**Comment by beno** [comment]
So am I correct in stating the following list (found [here](https://docs.puppet.com/puppet/latest/reference/lang_template_erb.html)) is (un)supported by ECR as stated? I will be happy to investigate fixing the unsupported ones, if we agree this is indeed the objective.

    <%= EXPRESSION %> — Inserts the value of an expression.   supported
      With -%> — Trims the following line break.              not supported
    <% CODE %> — Executes code, but does not insert a value.  supported
      With <%- — Trims the preceding indentation.             not supported
      With -%> — Trims the following line break.              not supported
    <%# COMMENT %> — Removed from the final output.           supported
      With -%> — Trims the following line break.              not supported
    <%% or %%> — A literal <% or %>, respectively.            ~supported

**Comment by jhass** [comment]
Well, the official ERb list is a bit different, at least the documented one: https://github.com/ruby/ruby/blob/trunk/lib/erb.rb#L41-L53

**Comment by beno** [comment]
But it works in ERB.  Also I see a lot of references to 'trim_mode' and 'trim_line' etc inside that file, so my guess is the documentation is out of sync here. In any case, without the ability to suppress gratuitous newlines I don't really see the point of using such a templating language. In fact, I would move to suppress newlines by default for non-inserting lines, as I can't think of any use case where an empty line would be needed in the output.

I'll try to come up with a PR (no promises though, as my Crystal fu is still maturing).

**Comment by jhass** [comment]
I can follow that it can make sense to strip lines that consist of nothing but whitespace *and* a non-outputting tag. But lines with just whitespace should be preserved as is.
