### ISSUE TITLE
format tool creates syntax error in a specific case

### ISSUE THREAD

**Issue by konovod** [crystal-lang/crystal#3005]
`crystal tool format` turns this

    (1..10).each do |i|
      next unless i.responds_to? :abs
      next unless i > 5
      i.tap() do |i|
        p i
      end
    end
into

    (1..10).each do |i|
      next unless i.responds_to? :abs  next unless i > 5
      i.tap() do |i|
        p i
      end
    end

removing one line feed and turning compilable code into syntactically wrong.
 If () after 'tap' is omitted, bug does not happen.

**Comment by asterite** [comment]
@konovod Thank you for reporting this! :-)
