### ISSUE TITLE
Garbage values with ptr of self in Number

### ISSUE THREAD

**Issue by Exilor** [crystal-lang/crystal#3006]
I expected [this code](https://play.crystal-lang.org/#/r/1421) to return  `Slice[210, 2, 150, 73]`.

Interestingly, in my computer it returns `Slice[0, 0, 0, 0]`.
However, with [this small change](https://play.crystal-lang.org/#/r/1425) it returns what I expected in my computer while in play.crystal-lang it returns different garbage.

**Comment by jhass** [comment]
It's all just luck and garbage. `n` is a local variable, so it lives on the stack. Once `bytes` returns its stackframe is free to be overwritten again. You have to copy the slice to the heap before returning it.

**Comment by Exilor** [comment]
And here I was thinking that I could cheat and not have to touch the heap :grin: this is the kind of thing that happens when you go from Ruby to Crystal without learning C. Thanks & closing.

**Comment by asterite** [comment]
@Exilor One way to avoid the heap is to use a static array: https://play.crystal-lang.org/#/r/143z

```cr
struct Number
  def bytes
    n = self
    pointerof(n).as(UInt8[sizeof(self)]*).value
  end
end

p 0x01020304.bytes
p 0x01_u8.bytes
```

**Comment by Exilor** [comment]
Yesssss that's what I wanted!
```
StaticArray bytes 454.36M (±11.03%)       fastest
      Slice bytes  57.77M (±14.88%)  7.86× slower
```
Thanks Ary :)
