### ISSUE TITLE
Why will char.to_f and string.to_i not work?

### ISSUE THREAD

**Issue by ndac-todoroki** [crystal-lang/crystal#3024]
for example:

```crystal
p "".to_f
    # => 0.0

p "".to_i
    # => invalid Int32: 
    #         (ArgumentError)
    #       [4414839] *CallStack::unwind:Array(Pointer(Void)) +87
    #       [4414730] *CallStack#initialize:Array(Pointer(Void)) +10
    #       [4414682] *CallStack::new:CallStack +42
    #       [4385272] *raise<ArgumentError>:NoReturn +24
    #       [4427685] *String#to_i32<Int32, Bool, Bool, Bool, Bool>:Int32 +245
    #       [4427420] *String#to_i:Int32 +92
    #       [4343443] ???
    #       [4396201] main +41
    #       [139629950453808] __libc_start_main +240
    #       [4341433] _start +41
    #       [0] ???


p ''.to_i
    # => 0

p ''.to_f
    # => Error in ./sample.cr:1: undefined method 'to_f' for Char (did you mean 'to_i'?)
```
and these don't show up at compiling but only when executing.

1. Why are the errors different? (Is the former not handled inside crystal?)
2. Why can't they be like this?

  ```crystal
  ''.to_f  #=> 0.0
  "".to_i  #=> 0
  ```

**Comment by david50407** [comment]
`String#to_i` seems to be a bug, it happens with a runtime exception raising.

`Char#to_f` is undefined, it throwed by the compiler, I think that a character is hard to represent a float number.

**Comment by jhass** [comment]
`''.to_i` should raise too.

We don't necessarily know the value of `self` in `Char` nor `String` at compile time, so we can only give runtime errors, this has to stay.

There are the `to_i?` and `to_f?` variants that return `nil` instead of raising, so you can do `"".to_i? || 0` etc.

**Comment by ndac-todoroki** [comment]
> There are the to_i? and to_f? variants that return nil instead of raising, so you can do "".to_i? || 0 etc.

wow, this is useful. Thank you!
