### ISSUE TITLE
StringScanner Strange behavior..

### ISSUE THREAD

**Issue by song9446** [crystal-lang/crystal#3026]
I've not lived in English culture, so Please forgive my awkward English. 

StringScanner::scan doesn't scan over the new line.

example : 

```cr
s = "crystal\nlang"
scanner = StringScanner.new(s)
scanner.scan(/g/) # = Nil
puts scanner.offset # = 0
```

do I wrong way to use the scanner?

**Comment by asterite** [comment]
`scan` expects the regex to match exactly where the scanner is positioned.

I think you are looking for `scan_until`:

```cr
s = "crystal\nlang"
scanner = StringScanner.new(s)
scanner.scan_until(/g/) # = "crystal\nlang"
puts scanner.offset # = 12
```

**Comment by song9446** [comment]
Sorry for foolish question, and Thank's for answer...
