### ISSUE TITLE
request: sorted includes?

### ISSUE THREAD

**Issue by aeosynth** [crystal-lang/crystal#3027]
i'd like a combination of `Array#bsearch` and `Enumerable#includes?`, which would essentially be this:

```crystal
def sorted_includes?(arr, obj)
  obj == arr.bsearch { |x| >= obj }
end
```

this is purely for convenience

**Comment by jhass** [comment]
I feel like the usecases are rather rare. How about you create a shard that monkey patches it into the standard library and then we'll see how often that'll get used?

**Comment by aeosynth** [comment]
for now i'll just write the code inline
