### ISSUE TITLE
Document pseudo methods in the API documentation

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#3041]
Namely, the following "methods" are missing in the API docs:
- `Object#is_a?`
- `Object#as`
- `Object#as?`
- `Object#responds_to`
- `Object#nil?`

They appear to be methods and not syntax, so people expect and should be able to find them documented in the API docs.

Just adding stub definitions to `src/object.cr` doesn't work, because redefinition is disallowed. So we either have to
- Add a special case in the documentation generator, detecting that it's generating for Crystal itself and injecting the definitions.
- Allow redefinitions of them in `Object` only. Subclasses would still get the error message, when somebody reopens `Object` to redefine them, just nothing happens.
- Allow redefinitions of them in the documentation generator only. That would allow to add a special file with stub definitions like we do for macro methods and types.

**Comment by asterite** [comment]
I like this idea. I think the easiest thing to do is to add these methods in the doc generator, only for the standard library (the code already has a check to detect this). I don't think the docs for these methods will change often (or never?) so they can be hardcoded in the docs. I'd rather not modify the language to allow parsing these methods in some cases. Right now the check for the disallowed names is at the parser level so it's kind of hard to allow it for `Object` (the parser would have to gain semantic understanding)
