### ISSUE TITLE
Compiler crash when declaring same library function as Int and Bool

### ISSUE THREAD

**Issue by konovod** [crystal-lang/crystal#3045]
Finally reproduced it in carc.in:
https://carc.in#/r/14t3

    lib Terminal
      fun f_int = some_fun() : Int32
      fun f_bool = some_fun() : Bool
    end
    
    Terminal.f_bool()
    Terminal.f_int() != 0

On my computer (ArchLinux, x86_64 ) it crashes the compiler too.

**Comment by asterite** [comment]
Good catch!

This will eventually give a compile error saying you can't declare a function twice.

**Comment by konovod** [comment]
Huh, so a Bool helper has to be moved to another module.
Maybe it is slightly off-topic, but is there some way to merge external lib functions and their helpers into one namespace?
Of cource I can create a Module, wrap every function from a lib there and then add helpers to this module, but the process of wrapping everything doesn't seem right, as Lib already wrapped it with a nice syntax. 
Or lib functions usage together with their helpers isn't idiomatic at all?

**Comment by jhass** [comment]
Actually I can see this making sense as a feature:

```cr
lib LibPlatformSpecificWeirdness
  {% if flag?(:darwin) %}
    fun do_a = does_a_and_b(decides_on_this : Foo) : Foo
    fun do_b = does_a_and_b(decides_on_this : Foo) : Foo
  {% else %}
    fun do_a = does_a(does_not_decide_on_this : Foo) : Foo
    fun do_b = does_b(does_not_decide_on_this : Foo) : Foo
  {% end %}
end
```

No, I don't have a real world example of that at hand, but I find it very imaginable. Of course defining the same external symbol twice with different signatures should still error, across all `lib`s.

**Comment by asterite** [comment]
@konovod What lib are you binding to?

**Comment by konovod** [comment]
Right now - (BearLibTerminal)http://foo.wyrd.name/en:bearlibterminal
But i think it can be useful for many libraries with not very complex API.

**Comment by asterite** [comment]
I see a Crystal `lib` as saying "This is what I import from the C library". Then one writes a nice wrapper around that.

We could maybe mix both, but I think it's maybe cleaner this way, as the two "worlds" are separate.

In this case your library seems very simple, where most (or all) functions can be called with integers and strings. In most cases libraries are more complex and provide structs and other types that need to be passed around.

One idea @waj had, and I kind of like it (but I'm not sure), is to allow adding `fun` to types. For example:

```cr
module Terminal
  @[Extern]
  fun delay = terminal_delay(period : Int32); end
end
```

But then we'd need to allow adding `@[Link]` attributes to modules and maybe classes.

Eventually I think we'll also allow marking structs as `@[Extern]` so you don't need to write too many wrappers, so adding these small conveniences is maybe good, though we'd have to write a full RFC detailing all of the aspects.

**Comment by konovod** [comment]
> I see a Crystal lib as saying "This is what I import from the C library". Then one writes a nice wrapper around that.

Well, perhaps it is a right way, especially if libs will be generated automatically. But such nice syntax, enums and `#to_unsafe` made me think that lib itself can be a nice wrapper, at least for "lightweight" libraries. It just needs something like `extends Lib` in a `Module` or something like this.
On the other hand `@[Extern]` would solve the problem, even though i understand it is a big change.
