### ISSUE TITLE
Compiler bug block with |_, _| args

### ISSUE THREAD

**Issue by jmoriau** [crystal-lang/crystal#3054]
Hello,

I stumbled upon this bug a few hours ago, I'm sorry it's still a medium sized example but I didn't know how to reduce it more.
It needs the shards 'pool' (https://github.com/ysbaddaden/pool) and 'redis' (https://github.com/stefanwille/crystal-redis).

(Well I'm sure you won't need them and will be able to make an even smaller example of the bug but that's how I encountered it and I failed to reduce it more).

```ruby
require "pool/connection"
require "redis"

class A
  def initialize(@pool : ConnectionPool(Redis))
  end

  def another_method
    puts "another_method"
  end

  def setup_callbacks
    spawn do
      puts "Now listening to first callback..."
      @pool.connection do |redis|
        redis.subscribe("first") do |on|
          on.message do |_, _| # <====== Works fine if at least one of them is named
            another_method
          end
        end
      end
    end
    spawn do
      puts "Now listening to second callback..."
      @pool.connection do |redis|
        redis.subscribe("second") do |on|
          on.message do |_, message|
            puts "second"
          end
        end
      end
    end

    sleep(2)
  end
end

pool = ConnectionPool(Redis).new(capacity: 25, timeout: 0.01) { Redis.new(unixsocket: "/tmp/redis.sock") }
a = A.new(pool)
a.setup_callbacks
```

It works fine if I provide at least one name for the block params in the first callback.

The compiler error is:

```
Module validation failed: Stored value type does not match pointer operand type!
  store %String* %_1, %String* %_
 %String = type { i32, i32, i32, i8 }
[5496142] ???
[15953253] ???
[15525432] ???
[6870918] ???
[16400279] ???
[5730483] ???
[5589208] main +18872
[140689306171440] __libc_start_main +240
[5485329] ???

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

**Comment by asterite** [comment]
Thank you for reporting!

Reduced:

```cr
def foo(&block : Int32, Int32 ->)
  block.call(1, 2)
end

foo { |x, x| } # or using underscores
```

The above should be a compile error, and should work with underscores.

**Comment by asterite** [comment]
Regardless of the bug, I don't know why you wrote the two underscores, but in this case you can just omit the entire `|...|` from the block if you don't need its arguments.

**Comment by jmoriau** [comment]
@asterite I pasted the block a few times and used a regex to mass-replace the `subscribe` arg and the block params depending on the context around them.

Then I wanted to try the first block (with correctly replaced block params) so I left the others with |_, _| and tried to compile. :smile:
