### ISSUE TITLE
Bytes constructor with wrong type

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3055]
crystal eval 'p typeof(Bytes[1,2,3])'
Slice(Int32)

expected Slice(UInt8)

**Comment by asterite** [comment]
You can do:

```cr
UInt8.slice(1, 2, 3)
```

The reason is that Bytes is just `Slice(UInt8)` and invoking `Slice(UInt8)[...]` can't "cast" every type. But with `UInt8.slice(...)` (and other numeric types) the "cast" is done.

**Comment by asterite** [comment]
I reopened because maybe the first case can be implemented too (would be nice)
