### ISSUE TITLE
creating string 5 times slower than slice

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3056]
```crystal
io = MemoryIO.new
SIZE = 200_000
str = "a" * SIZE
io << str

t = Time.now
s = 0
10000.times do
  bytes = Bytes.new(SIZE)
  io.rewind
  io.read_fully(bytes)
  s += bytes[SIZE-10]
end
p s
p Time.now - t

t = Time.now
s = 0
10000.times do
  io.rewind
  str = String.new(SIZE) do |buffer|
    io.read_fully(Slice.new(buffer, SIZE))
    {SIZE, 0}
  end
  s += str[SIZE-10].ord
end
p s
p Time.now - t
```

```
970000
00:00:00.4536135
970000
00:00:02.2081078
```

**Comment by kostya** [comment]
seems this is not about creation, but about [] operator

**Comment by RX14** [comment]
The `[]` operator operates on UTF-8 codepoints, which means `String#[]` has to handle multi-byte codepoints. This makes it much slower because it can't simply calculate the memory address and perform a load, it has to iterate the string.

**Comment by ozra** [comment]
UTF-8 data (String) can't be offset indexed - it has to be parsed to reach the intended position. One character might take up one byte, another three bytes, etc.

**Comment by asterite** [comment]
Yes, that's the reason. You can use `String#byte_slice` to create a substring where the indices are bytes, and this will be much more efficient but will only work on ASCII strings. If you know your strings are always ASCII you can use this.

(by the way, we might need to rethink some String method names, I'm not sure `byte_slice` is ideal)

**Comment by ysbaddaden** [comment]
Yup, maybe just `bytes` as in Ruby?
