### ISSUE TITLE
better variables mass assigment

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3059]
right now this is raised:
```crystal
a, b = "bla\n".chomp.split("|||")
```

would be nice if it work like this:
```crystal
a, b? = "bla\n".chomp.split("|||")
a # => "bla"
b # => nil
```

**Comment by asterite** [comment]
@kostya It seems we had the same idea and the same syntax :-) #2617

So I guess that a 👍  to my proposal :-D
