### ISSUE TITLE
strange memory leak in 0.18.6

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3061]
this is not really a bug, because not reproduced in 0.18.7

but funny to know what the fix was, for this:

``` crystal
t = Time.now
1000000.times do |i|
  ch = Channel(Int32).new
  spawn do
    ch.send(0)
  end
  ch.receive
end
p Time.now - t
p `ps -p #{Process.pid} -o rss`
```

```
/opt/crystal-0.18.6-1/bin/crystal 1.cr --release
00:00:00.8545111
"  RSS\n309416\n"
```

```
 /opt/crystal-0.18.7-1/bin/crystal 1.cr --release
00:00:00.3313136
"  RSS\n 1820\n"
```

ubuntu 14.04

**Comment by kostya** [comment]
git bisect show that fixed by c94adf04a6261ada2cfb66dbe1b9a38f557d4485

**Comment by jhass** [comment]
This is probably a codegen bug that will resurface sooner or later, hopefully with a lot less code involved. As it stands this probably just too much code to debug it, shall we close this until then?

**Comment by kostya** [comment]
if i add `sleep 0` after `ch.receive`, no memory leak

**Comment by sdogruyol** [comment]
This doesn't leak on Crystal master. Can we close this in favor of #3333 ?
