### ISSUE TITLE
Question: How to specify block arguments

### ISSUE THREAD

**Issue by jwaldrip** [crystal-lang/crystal#3062]
I posted this question in chat, but got no response.

> How do you specify multiple proc argument types? The following does not work:

```crystal
def initialize(&block : (Proc(T, Nil), Proc(Exception, Nil)) -> _)
  # ...
end
```

**Comment by RX14** [comment]
You want to pass two procs to a block?
[This](https://carc.in/#/r/150v) would be correct, although it doesn't look like vert idiomatic crystal, what are you trying to accomplish?

**Comment by asterite** [comment]
Or is it a proc that has two procs as inputs?

It's probably better if you tell us what are you trying to do, generally (what API), so we don't deal with the XY problem

**Comment by jhass** [comment]
@jwaldrip hey, does this already answer your question? Note that we also have an active community on StackOverflow, which might be a better venue than our issue tracker. If you still have open questions I suggest to open one there, probably going into your actual problem like @asterite suggested.

For now I'll close this.

**Comment by jwaldrip** [comment]
@jhass I was able to answer my own question. It was a proc that took procs, which was a little difficult but I did end up figuring it out.

```crystal
def initialize(&block : (T -> Nil), (String -> Nil) -> _)
  # ...
end
```
