### ISSUE TITLE
homebrew recipe lacking pcre dependency

### ISSUE THREAD

**Issue by masukomi** [crystal-lang/crystal#3063]
background: 
I'd `brew install`ed crystal-lang v0.17 (not sure if i ever used this version on this machine)
then i `brew upgrade`ed to 0.18.7 had issues with `dyld`  

then brew uninstalled, then `brew install crystal-lang --with-llvm` 

now, if i try and do anything with the `crystal` command  I get

```
dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /usr/local/bin/crystal
  Reason: image not found
```

I have done `brew install dyld-headers` but that didn't help.

I'm running OS X 10.11.5 (El Capitan)

Something else needs installing but it isn't clear what.

**Comment by keplersj** [comment]
pcre?

**Comment by fibric** [comment]
LLVM will be automatically installed. Because in the current brew formula, LLVM is defined as a [dependency](https://github.com/crystal-lang/homebrew-crystal/blob/master/crystal-lang.rb#L24). Calling `--with-llvm` has no effect; at least it hadn't on my machine.

What Xcode version and command line tools have you installed?

**Comment by RX14** [comment]
You need to install libpcre, a simple google search says a command that might help is `brew unlink pcre && brew link pcre`, although I have never used OSX before.

**Comment by masukomi** [comment]
@RX14 I didn't have pcre installed so `brew install pcre` was the correct operation. And yes, it fixed it. Thank you.

It seems that the correct fix here is to add 

`depends_on "pcre"` to  [the crystal-lang homebrew formula](https://github.com/crystal-lang/homebrew-crystal/blob/master/crystal-lang.rb)


In case it matters @fibric the xcode & related info...
```
xcode version 7.3.1  
xcode-select version 2343.
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by asterite** [comment]
I don't know what happens, but suddenly travis is failing with the same reason. Maybe something broke in homebrew? We didn't change anything...

**Comment by fibric** [comment]
This has changed in homebrew -> https://github.com/Homebrew/homebrew-core/issues/2869

I'Am puzzled right now...
`brew info crystal-lang` shows it's requiring `pcre`. But it's not explicitly named in formula.rb file. Am I blind?

```
brew info crystal-lang
crystal-lang: stable 0.18.7, HEAD
Fast and statically typed, compiled language with Ruby-like syntax
https://crystal-lang.org/
/usr/local/Cellar/crystal-lang/0.18.7 (631 files, 34.3M) *
  Built from source on 2016-07-28 at 07:14:48
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/crystal-lang.rb
==> Dependencies
Build: pkg-config ✔
Required: libevent ✔, bdw-gc ✔, llvm ✔, pcre ✔, libyaml ✔
==> Options
--without-release
	Do not build the compiler in release mode
--without-shards
	Do not include `shards` dependency manager
--HEAD
	Install HEAD version
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
```

Even more suspicious, `deps` doesn't list `pcre`.
```
$ brew deps crystal-lang
bdw-gc
doxygen
libevent
libffi
libyaml
llvm
openssl
```

Neither does `leaves` list `pcre`.
```
$ brew leaves crystal-lang
antigen
automake
crystal-lang
curl
git
git-extras
git-flow
go
libtool
most
nvm
ocaml
thefuck
zsh
zsh-completions
```

Rendering the dependency tree shows... no `pcre`.
```
$ brew deps --tree --include-build --include-optional crystal-lang
crystal-lang (required dependencies)
├── pkg-config
├── libevent
│   ├── doxygen
│   │   └── cmake
│   │       └── sphinx-doc
│   ├── pkg-config
│   ├── openssl
│   │   └── makedepend
│   │       └── pkg-config
│   └── doxygen
│       └── cmake
│           └── sphinx-doc
├── bdw-gc
│   ├── pkg-config
│   └── libatomic_ops
├── llvm
│   └── :python
│   ├── xz
│   ├── xz
│   ├── xz
│   ├── xz
│   ├── xz
│   ├── xz
│   ├── xz
│   ├── xz
│   ├── xz
│   ├── xz
│   ├── xz
│   ├── cmake
│   │   └── sphinx-doc
│   └── libffi
└── libyaml
```

**Comment by steakknife** [comment]
It looks like both a dependency leak while building `crystal` **and** `shards` is using the system PCRE instead of the Homebrew one.  Note also that both of these are legacy PCRE versions.

```
0 ~ git:master ❯❯❯ otool -L `which crystal`
/usr/local/bin/crystal:
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/local/opt/llvm/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/pcre/lib/libpcre.1.dylib (compatibility version 4.0.0, current version 4.7.0)
	/usr/local/opt/bdw-gc/lib/libgc.1.dylib (compatibility version 2.0.0, current version 2.3.0)
	/usr/local/opt/libevent/lib/libevent-2.0.5.dylib (compatibility version 7.0.0, current version 7.9.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
0 ~ git:master ❯❯❯ otool -L `which shards`
/usr/local/bin/shards:
	/usr/local/opt/libyaml/lib/libyaml-0.2.dylib (compatibility version 3.0.0, current version 3.4.0)
	/usr/lib/libpcre.0.dylib (compatibility version 1.0.0, current version 1.1.0)
	/usr/local/opt/bdw-gc/lib/libgc.1.dylib (compatibility version 2.0.0, current version 2.3.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/local/opt/libevent/lib/libevent-2.0.5.dylib (compatibility version 7.0.0, current version 7.9.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
0 ~ git:master ❯❯❯
```

**Comment by steakknife** [comment]
#### Upgrade: `brew upgrade crystal-lang && brew cleanup crystal-lang`

crystal PCRE dep appears fixed in Homebrew formula `0.18.7_1`, but shards is still leaking into system PCRE.

**Comment by sdogruyol** [comment]
Crystal is fixed, can you confirm `shards` @ysbaddaden so that we can close this issue :+1:

**Comment by wontruefree** [comment]
It seems like we can close this issue right?

**Comment by RX14** [comment]
Closing, will reopen if this isn't fixed.

**Comment by diguage** [comment]
`brew link pcre2` can solve the problem.
