### ISSUE TITLE
"unexpected token" when regex starts with equal sign

### ISSUE THREAD

**Issue by kainjow** [crystal-lang/crystal#3066]
I believe I discovered a bug when a regex starts with an equal sign:

    /=/

Generates:

> Syntax error in ./test.cr:1: unexpected token: /=
> 
> /=/
> ^

I am using `Crystal 0.18.7 (2016-07-27)` from Homebrew.

**Comment by asterite** [comment]
Interesting!

It seems to be confusing this with `/=`, for example in `a /= 2`. I'll fix this, though in some cases (like in Ruby) you'll need to disambiguate using parentheses, for example.

For now you can use `%r(=)`

**Comment by kainjow** [comment]
Cool, thanks for the quick fix! I was playing around with attempting to compile [Liquid](https://github.com/Shopify/liquid) (first time with Crystal) and this was the first snag I came cross :)
