### ISSUE TITLE
Request: default values in Time::Span.new

### ISSUE THREAD

**Issue by silverweed** [crystal-lang/crystal#3069]
I've noticed that all `new` methods in `Time::Span` allow no default arguments (https://github.com/crystal-lang/crystal/blob/68783f1ebdd5b9bbefc8892ddbc200fe1f13bbea/src/time/span.cr#L60-L75)

Wouldn't it be convenient if all the values were defaulted to `0`, so one can use named arguments to write something like:

``` crystal
one_hour = Time::Span.new(hours: 1)
half_an_hour = Time::Span.new(minutes: 30)
```

and so on? It seems more natural to me than having to write `Time::Span.new(0, 30, 0)` etc, and it looks more readable too.

**Comment by RX14** [comment]
You can use `1.hour` or `30.minutes` as shorthand instead.

**Comment by silverweed** [comment]
Thank you, I totally missed those in the docs :D

**Comment by asterite** [comment]
Closing this because the above suggestion is the recommended way to create time spans in a readable way.
