### ISSUE TITLE
Unexpected "invalid memory address" error

### ISSUE THREAD

**Issue by martinandert** [crystal-lang/crystal#3071]
When I run this code with the latest Crystal

```crystal
abstract struct X
end

struct A < X
  getter value : String

  def initialize(@value)
  end
end

struct B < X
  getter inner : X

  def initialize(@inner)
  end
end

struct C < X
  getter inner : A | B

  def initialize(@inner)
  end
end

C.new(B.new(A.new("foo")))
```

it errors with

```
Invalid memory access (signal 11) at address 0x13e
[4352549] *CallStack::print_backtrace:Int32 +117
[4345048] __crystal_sigfault_handler +56
[4511336] sigfault_handler +40
[140088497677264] ???
[4582256] ???
```

which I do not expect to happen.

Update: I found out that it works when running it with the `--release` flag.

**Comment by asterite** [comment]
The compiler should detect this and give a compile error.

You can't have a struct with a field whose type is that struct itself, either directly or recursively, because there's no way to represent that in memory.

Use classes in this case.
