### ISSUE TITLE
Documentation generator produces broken links to lib definitions

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#3072]
All types (like constants, structs or enums) provided by lib are linked by the generator but no documentation pages are generated.

``` crystal
lib LibFoo
  FOO_BAR = "BAZ"
  FOO_BAZ = "BAR"

  enum FooType
    Bar
    Baz
  end
end
```

``` crystal
abstract class Foo
  abstract def foo? : LibFoo::FooType
end
```

**Comment by asterite** [comment]
Yes, lib types are not supposed to be public APIs, they are an implementation detail for the library/shard you are writing. Using a lib directly is like programming in C.

**Comment by jhass** [comment]
We shouldn't link them while we don't generate pages for them.

**Comment by Sija** [comment]
In such case shouldn't doc generator simply printout type instead of linking them to nonexistent pages?

**Comment by asterite** [comment]
Oh, right, I read the above too quickly and had to go. This should be fixed.

**Comment by Sija** [comment]
Actually, having docs for lib definitions would be nice... Sometimes they're returned from API functions and without docs there's no context you can refer to.

**Comment by Sija** [comment]
@asterite WDYT about documenting libs?

**Comment by asterite** [comment]
@Sija I think libs are a library implementation detail and not something users should use directly

**Comment by Sija** [comment]
@asterite Maybe, but it happens sometimes that Crystal API-s return Lib enum members (wrapping them wouldn't be DRY) so then users are left on ice, though I agree that it might not be the best practice. In any case leaving them as it is, linked to non-existent page is confusing.

**Comment by asterite** [comment]
lib enum members can be defined outside a lib and used inside it

**Comment by asterite** [comment]
Ah, definitely, the link shouldn't be there
