### ISSUE TITLE
Doing a Process.kill(0, ...)

### ISSUE THREAD

**Issue by drosehn** [crystal-lang/crystal#3077]
Apologies if this is a dumb question.

I want to do a:    `Process.kill(0, somePID)`
as a quick way to see if the process exists, but I can't use an integer value as the signal-parameter to kill() as I can in Ruby or other languages.  src/signal.cr defines enum Signal with many of the standard values, but nothing is defined for zero.

Am I missing something simple?

**Comment by jhass** [comment]
Additionally it always returns `nil`.

I never was much of a fan of sending `0` as a high level feature. Maybe we can add something like

```cr
class Process
    def self.exists?(pid : Int)
    ret = LibC.kill(pid, 0)
    raise Errno.new(ret) if ret < 0
    ret == 0
  end
end
```
