### ISSUE TITLE
Splitting HTTP::Request into Server and Client

### ISSUE THREAD

**Issue by RX14** [crystal-lang/crystal#3080]
I think we should split `HTTP::Request` into `HTTP::Client::Request` and `HTTP::Server::Request` to be consistent with the client and server response classes. Doing this also allows us to more easilly implement Request being an IO, which is essential for large file uploads, and technically `String` isn't meant to contain binary data so it's already a bit iffy.

Any comments on this before I start putting together a pull request?

**Comment by asterite** [comment]
This was kind of solved when we changed Request's body to be an IO.
