### ISSUE TITLE
Crash when doing exit/NoReturn in ensure

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#3082]
```cr
begin
  raise "OOPS"
rescue
  puts 1
ensure
  puts 2
  exit
end
```

Output:

```
1
Invalid memory access (signal 10) at address 0x102cf17bc
[4341338363] *CallStack::print_backtrace:Int32 +107
[4341328823] __crystal_sigfault_handler +55
[4341393555] sigfault_handler +35
[140735700915498] _sigtramp +26
```

Probably a codegen bug, but I don't know.

**Comment by Sija** [comment]
I've just encountered behaviour which seems related to this bug, that is: using `return` inside of `ensure` block (https://carc.in/#/r/15e2). Is it the same bug indeed?

**Comment by asterite** [comment]
@Sija No, it's not related, and I don't know if it's a bug. Try this in Ruby:

```rb
def foo
  begin
    raise "OH NO!"
  ensure
    return
  end
end

foo
```

The exception is swallowed too.

**Comment by Sija** [comment]
@asterite thanks for the clarification, it works the same in Ruby—true, although I'd say it's at least unexpected behavior...

**Comment by asterite** [comment]
We just checked it, it works the same in Ruby, Python and Java too. C# disallows `return` inside a `finally`.

I think the semantic is OK: I want to be sure (ensure) to return (or return this value) from the method, whatever happens in the `begin` block.

**Comment by Sija** [comment]
Fair enough, thanks for digging into this!
