### ISSUE TITLE
Document Variadic Generics

### ISSUE THREAD

**Issue by thedrow** [crystal-lang/crystal#3085]
As far as I can see variadic generics <s>do not exist</s> are not documented.
<s>For some data structures it is very useful to declare them.</s>

**Comment by asterite** [comment]
We already have this, they are just not documented because it's pretty recent. Tuple, Union and Proc are all variadic generics.

https://play.crystal-lang.org/#/r/15ck

**Comment by thedrow** [comment]
Pretty cool.

**Comment by HertzDevil** [comment]
I created a corresponding issue for the reference book here: crystal-lang/crystal-book#525

The variadic generic types in the standard library should already be documented.

**Comment by thedrow** [comment]
Should we close this issue, in that case?
