### ISSUE TITLE
Docs: Please provide OS X install instructions without HomeBrew

### ISSUE THREAD

**Issue by boazsegev** [crystal-lang/crystal#3090]
I, like some others, decided to shun HomeBrew since the (questionable) decision to add google analytics with an opt-out option (rather then opt-in, if at all).

Could you provide OS X install instructions that aren't HomeBrew based?

I tried installing from code, but couldn't find the list of libraries I'll need to install (I only got a list of HomeBrew recipes.

I thank you for your time and hope to try Crystal out soon.

**Comment by jhass** [comment]
You can download the prebuilt binaris for OS X and use them, for example for 0.18.7: https://github.com/crystal-lang/crystal/releases/download/0.18.7/crystal-0.18.7-1.pkg

**Comment by boazsegev** [comment]
Thanks @jhass .

I started playing crystal and am quite impressed so far :-)

**Comment by keplersj** [comment]
Like this https://github.com/crystal-lang/crystal/wiki/All-required-libraries?

**Comment by boazsegev** [comment]
Yap, this is where I think it should be placed  👍

I'm assuming the libraries are similar to the Ubuntu libraries, but it would be nice if there was a section titled `Mac OS X` without the HomeBrew.

**Comment by jhass** [comment]
Note that list is only what's neccessary to compile the compiler, other Crystal programs will only require a subset at most.

**Comment by boazsegev** [comment]
@jhass , thanks for the info... does this mean the executable I compile with Crystal will link against these libraries dynamically, or are they staticky linked? In other words, does it mean I have client side requirements when using these libraries?

Which makes me wonder... would there be a stripped down version of crystal (a compiler without any external libraries) that's suitable for embedded systems? Not that I don't love my C, but some things could be so much easier.

**Comment by boazsegev** [comment]
Good to know, thanks!

**Comment by steakknife** [comment]
Doing `brew link llvm --force` is inadvisable.

Xcode CLT provides an Apple fork of clang/llvm which absolutely cannot be overridden unless you enjoy strange, difficult-to-debug errors in other programs and reinstalling everything from scratch.

```
LLVM executables are installed in /usr/local/opt/llvm/bin.
Extra tools are installed in /usr/local/opt/llvm/share/llvm.
To use the bundled libc++ please add the following LDFLAGS:
  LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"

This formula is keg-only, which means it was not symlinked into /usr/local.

OS X [Xcode CLT, actually] already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/llvm/lib
    CPPFLAGS: -I/usr/local/opt/llvm/include


If you need Python to find bindings for this keg-only formula, run:
  echo /usr/local/opt/llvm/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/llvm.pth
```

The crystal-lang Homebrew formula needs to be improved to bring in runtime and build deps correctly without requiring dangerous, system-wide modifications.

**Comment by steakknife** [comment]
I've [fixed](https://gist.github.com/steakknife/20861a5884a66ca26e6600768be3e252) a copy of Homebrew formula, and it should no longer require `brew link --force llvm`.

Test it out first before going through the Homebrew PR process:

## Stable, bottled

    brew uninstall crystal-lang; brew install https://gist.githubusercontent.com/steakknife/20861a5884a66ca26e6600768be3e252/raw/97e831985352bb13efba30135065eaa1732fbff8/crystal-lang.cr

## Stable, built-from source

    brew uninstall crystal-lang; brew install -s https://gist.githubusercontent.com/steakknife/20861a5884a66ca26e6600768be3e252/raw/97e831985352bb13efba30135065eaa1732fbff8/crystal-lang.cr


## HEAD
    brew uninstall crystal-lang; brew install --HEAD https://gist.githubusercontent.com/steakknife/20861a5884a66ca26e6600768be3e252/raw/97e831985352bb13efba30135065eaa1732fbff8/crystal-lang.cr

**Comment by asterite** [comment]
These are documented in https://crystal-lang.org/docs/installation/from_a_targz.html and https://crystal-lang.org/docs/installation/from_source_repository.html

Please reopen if those didn't work for you.
