### ISSUE TITLE
File Watch

### ISSUE THREAD

**Issue by crisward** [crystal-lang/crystal#3097]
Just read about crystal on Hacker News and thought I'd give it a whirl. Seems like a really cool new language. The one thing I can't find though is a 'watch' process, kind of like [node-dev](https://github.com/fgnass/node-dev), which rebuilds on code change. 

Does one exist? If not, this would be a really cool addition.

Keep up the excellent work, look forward to seeing v1.0.

**Comment by crisward** [comment]
Just to answer my own question - found this

## A list of crystal modules
https://github.com/veelenga/awesome-crystal

## A file watcher
https://github.com/f/guardian

**Comment by jhass** [comment]
So question answered? Any reason to keep this open? :)

**Comment by crisward** [comment]
Thanks... I'm sure people can search closed issues if they have a similar question.

**Comment by samueleaton** [comment]
I too was looking for something like node-dev or nodemon so I made a small project that watches files and restarts a running process on file changes, called [Sentry](https://github.com/samueleaton/sentry).
