### ISSUE TITLE
Plans for the language independent types in YAML

### ISSUE THREAD

**Issue by mosop** [crystal-lang/crystal#3101]
Hi. Do you have any plans to implement the full YAML 1.2 specification in the standard library?

**Comment by jhass** [comment]
We currently bind `libyaml`, what features does that miss in particular?

**Comment by mosop** [comment]
Oh, I've never known that the YAML specification doesn't expect its applications to implement the language-independent types, shown in http://yaml.org/type/. I simply want to map those !!binary, !!bool, !!float, !!int and !!timestamp to/from the corresponding types in Crystal. Because I can easily migrate my old YAML resources into my Crystal application. However, I don't think the standard library has to support those types. Because those are optional. How is the crystal team is thinking about supporting the types?

**Comment by mosop** [comment]
I overlooked the similar issue #2235.

**Comment by mosop** [comment]
Oh! Already referenced in #2235. Thanks.

**Comment by asterite** [comment]
I think out YAML API is missing the concept of a schema. The default should be the default (bools, numbers, times) but one should be able to choose another one. It's just that the fail-safe schema was easier to implement at first, because everything is a string, and then you can parse the string in the way that you need it.

**Comment by mosop** [comment]
Thank you for letting me hear your thoughts! I think the capability to switch between sets of schemas is a great concept. So far, you think that those types should be supported:

* booleans
* numbers (integers and floats)
* timestamps

OK?

**Comment by ysbaddaden** [comment]
As explained in #4771 this boils down to support the YAML [Core Schema](http://yaml.org/spec/1.2/spec.html#id2804923) instead of the [Failsafe Schema](http://yaml.org/spec/1.2/spec.html#id2802346) as supported by `libyaml`.

**Comment by straight-shoota** [comment]
No, this is a different issue and only related to supporting Core Schema. If we can access the datatypes from JSON Schema it will bring us closer to supporting Core Schema. But there are some more language-independent types which are not required for Core Schema, so it must be considered which of these additional ones should be available in Crystal.
