### ISSUE TITLE
Syntax error in play:<line>: unexpected token: DELIMITER_START

### ISSUE THREAD

**Issue by Byron** [crystal-lang/crystal#3102]
## How to reproduce

```bash
crystal play
```

In the playpen code area, paste the following:
```crystal
h = {hi: 42, foo: "hello"}
h = {:hi => 42, :foo => "hello"}

foo_or_bar = /foo|bar/x
foo_or_bar =~ "foo"
```

The culprit seems to be the `x` character in the `/foo|bar/` regex literal.

## Meta

```bash
➜  hello git:(master) ✗ crystal --version
Crystal 0.18.7 (2016-07-27)
➜  hello git:(master) ✗ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G31
```

![screen shot 2016-08-06 at 15 23 05](https://cloud.githubusercontent.com/assets/63622/17456986/bcb101e0-5be9-11e6-91a7-dd01c73a158c.png)

**Comment by asterite** [comment]
Thank you!

It's always a good idea to reduce the problem as much as possible. This reproduces it:

```cr
/a/x
```

**Comment by asterite** [comment]
Also this fails outside the playground:

```cr
macro foo(x)
  {{x}}
end

foo(/a/x)
```

**Comment by Byron** [comment]
@asterite Thanks for the hint ! I will try to consider it next time.
