### ISSUE TITLE
Property macro does not allow initialization of Int64 to 0

### ISSUE THREAD

**Issue by abduct** [crystal-lang/crystal#3105]
https://play.crystal-lang.org/#/r/16aa

When defining a property inside a class as Int64 and attempting to initialize the value to 0 the compiler throws an error saying "instance variable '@bar' of Foo must be Int64, not Int32" as seen in the play link.

On the other hand defining a property as Int32 and initializing it to 0 works as seen here: https://play.crystal-lang.org/#/r/16am

Is there a specific reason as to why property instance variables are being forced to be only Int32? Without the initialization the compiler throws the error "instance variable '@bar' of Foo was not initialized in all of the 'initialize' methods, rendering it nilable" as seen here: https://play.crystal-lang.org/#/r/16ai

**Comment by jhass** [comment]
This works https://play.crystal-lang.org/#/r/16at

I believe there's already an issue for automatically casting literals already somewhere, but can't find it atm.

**Comment by abduct** [comment]
I see, there was no documentation on those literals on the property macro page I don't think. Thanks, if you can find the other issue someone can close this.

**Comment by asterite** [comment]
It's #2995

**Comment by bar** [comment]
@abduct me what?

**Comment by kirbyfan64** [comment]
This is why I always tell people to use backticks around anything containing the `@` symbol...

**Comment by Sija** [comment]
I wonder how many notifications @foo gets daily... :P
