### ISSUE TITLE
Object#to_json(io) definition missing

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#3106]
Hi, I've just encountered below error and noticed there's no `Object#to_json(io)` counterpart, is it intentional or just an omission?

```
wrong number of arguments for 'Time#to_json' (given 1, expected 0)
Overloads are:
 - Object#to_json()
```

https://carc.in/#/r/16d8

**Comment by asterite** [comment]
The problem is that `Time` doesn't define a `to_json(io)` (there's no standard way to serialize a Time to JSON). But `Object#to_json` is defined, and it invokes `to_json(io)`. That's why the error is confusing.

**Comment by Sija** [comment]
Maybe sth along the lines of:
```cr
def to_json(io)
  io << to_s.to_json
end
```

**Comment by jhass** [comment]
I think ISO8601 would be a fair default value for `Time#to_json`. If somebody needs something else they can specify a converter.

JS seems to default to that too:
```js
JSON.stringify({"foo": (new Date())})
"{"foo":"2016-08-07T07:19:39.733Z"}"

**Comment by ysbaddaden** [comment]
I'm with @jhass, there isnt any defined format for Time in JSON but there are acceptable ones. ISO8601 looks perfect to me.

**Comment by sdogruyol** [comment]
I agree that ISO8601 should be a good default for `JSON`.

**Comment by sdogruyol** [comment]
Why don't we handle this already? @asterite i think this should be trivial to implement.

**Comment by sdogruyol** [comment]
@asterite 🎉
