### ISSUE TITLE
HTML.unescape is missing

### ISSUE THREAD

**Issue by thedrow** [crystal-lang/crystal#3107]
HTML unescape doesn't exist yet in Crystal.
Can we please add it?

**Comment by jhass** [comment]
There's `HTML.escape` https://crystal-lang.org/api/0.18.7/HTML.html

**Comment by thedrow** [comment]
But unescape is missing.

**Comment by asterite** [comment]
Mmm... what are the use cases for `unescape`? The only use case I can imagine is if you are writing a browser. And in that case I think it should be browser logic, not standard library logic.

**Comment by Sija** [comment]
@asterite that applies for servers too: sometimes you need to unescape return URL passed to the backend as a query parameter.

**Comment by asterite** [comment]
@Sija Yes, but there's `URI.unescape` for that. This issue seems to be about `HTML.unescape`, for example tuning `&amp;` into "&" and so on... which I think only a browser needs to do.

**Comment by Sija** [comment]
@asterite I see, and what about things like web-scrapers? :) I admit it's not one of the most often used functions out there, yet IMHO having it even for parity with `HTML.escape` and Ruby would be already a Good Thing (tm)

**Comment by kostya** [comment]
when parsing pages, often needed HTML.unescape

**Comment by RX14** [comment]
I think that this should be included if only for symmetry reasons. If `HTML.escape` is in scope for the stdlib, then `HTML.unescape` is too.

**Comment by asterite** [comment]
If someone wants to implement this, please submit a PR. Thank you!

**Comment by amedeiros** [comment]
I made a pull request for this here https://github.com/crystal-lang/crystal/pull/3226.

**Comment by rdp** [comment]
Thanks for this, I needed and used it successfully  just now (useful for the case of "unescaping before re-escaping"  for incoming input that was previously already escaped.

**Comment by rdp** [comment]
Hmm wonder what it should do with &nbsp; ... I guess convert it into whatever the test description   it "escapes nonbreakable space but not normal space" uses for its char... :|
