### ISSUE TITLE
heredocs fail to honor tabs as whitespace

### ISSUE THREAD

**Issue by masukomi** [crystal-lang/crystal#3109]
According to [the documentation](https://crystal-lang.org/docs/syntax_and_semantics/literals/string.html) 

> The "heredoc" finishes in the line that starts with IDENT, ignoring leading whitespace.

Unfortunately, this is not true. If you indent with tabs, then it gives you a syntax error.
The heredoc in the following example is indented with 1 tab.

```
text =<<-EOL
	line 1
	line 2
	EOL

puts text
```

results in `Syntax error in ./tester.cr:7: unterminated heredoc`

**Comment by asterite** [comment]
I fixed this, but note that according to our [coding style guide](https://crystal-lang.org/docs/conventions/coding_style.html) you should be using two spaces instead of tabs.

**Comment by masukomi** [comment]
a) thanks. b) yup. but the thing is, coding style is ...style, and style is inherently subjective, and thus debatable. Personally, I think this whole "two spaces indentation" sucks, because it's not enough of a visual distinction, so if i'm not working on a project with others, I don't use it. I'm not suggesting we change it. It's the standard for Ruby, and most folks coming to crystal are coming from Ruby. 

I would suggest that we keep in mind that stylistic things WILL be ignored / bent / sidestepped / etc, and the compiler should never rely on them.  We could take a page from Go-lang and suggest that everyone use a tool that automatically corrects any stylistic mistakes on save, but again, you can't count on everyone using it.
