### ISSUE TITLE
`puts *{1}` causes instrumentation bug in playground

### ISSUE THREAD

**Issue by Byron** [crystal-lang/crystal#3110]
### How to reproduce

Using `crystal play`, the bug occurs when the following code is entered:
```crystal
puts *{1}
```

The error details as displayed in-app:
![screen shot 2016-08-07 at 17 59 59](https://cloud.githubusercontent.com/assets/63622/17463574/d82c1af6-5cc8-11e6-9d72-d8c2282092ef.png)

This is the output of `crystal play`
```
E, [2016-08-07 17:57:55 +0200 #49601] ERROR -- : Instrumention bug found (session=19, tag=101)
```

### Meta

```bash
../crystal-lang/crystal/bin/crystal --version && sw_vers
Using compiled compiler at .build/crystal
Crystal 0.18.7+310 [671ecb3] (2016-08-07)
ProductName:   	Mac OS X
ProductVersion:	10.11.6
BuildVersion:  	15G31
```

**Comment by bcardiff** [comment]
@Byron, Thanks for having fun with the playground.

**Comment by Byron** [comment]
@bcardiff Thanks for showing how magical playgrounds for statically compiled languages can be, you are setting that bar there ! (*Says me, who also spent a few hours getting a [docker-based Rust](https://github.com/integer32llc/rust-playground) playground up and running locally. Actually, you should remove the `play` option, as it spoils people ;) *)
