### ISSUE TITLE
Disallow single letter names for types to keep them free for free vars

### ISSUE THREAD

**Issue by Byron** [crystal-lang/crystal#3112]
### How to reproduce

In the playground started with `crystal play`, run the following code

```crystal
lib U
end
```

Please note that the `U` is particularly important, neither `lib LibU` nor `lib S` trigger the following exception:

<details>
```
Error in line 3: instantiating 'Crystal::Playground::Agent:Class#new(String, Int32)'

instantiating 'Crystal::Playground::Agent#initialize(String, Int32)'

in /Users/byron/dev/cr/crystal-lang/crystal/src/compiler/crystal/tools/playground/agent.cr:8: instantiating 'HTTP::WebSocket:Class#new(URI)'

    @ws = HTTP::WebSocket.new(URI.parse(url))
                          ^~~

in /Users/byron/dev/cr/crystal-lang/crystal/src/http/web_socket.cr:26: instantiating 'HTTP::WebSocket::Protocol:Class#new(URI)'

    new(Protocol.new(uri))
                 ^~~

in /Users/byron/dev/cr/crystal-lang/crystal/src/http/web_socket/protocol.cr:269: instantiating 'new(String, String, (Int32 | Nil), Bool)'

      return new(host, path, uri.port, tls)
             ^~~

in macro 'macro_4953252736' /Users/byron/dev/cr/crystal-lang/crystal/src/http/web_socket/protocol.cr:235, line 8:

  1. 
  2.       if tls
  3.         if tls.is_a?(Bool) # true, but we want to get rid of the union
  4.           context = OpenSSL::SSL::Context::Client.new
  5.         else
  6.           context = tls
  7.         end
  8.         socket = OpenSSL::SSL::Socket::Client.new(socket, context: context, sync_close: true)
  9.       end
 10.     

instantiating 'OpenSSL::SSL::Socket::Client:Class#new(TCPSocket)'
instantiating 'OpenSSL::SSL::Socket::Client#initialize(TCPSocket)'

in /Users/byron/dev/cr/crystal-lang/crystal/src/openssl/ssl/socket.cr:4: instantiating 'super(TCPSocket, OpenSSL::SSL::Context::Client, Bool)'

      super(io, context, sync_close)
      ^~~~~

in /Users/byron/dev/cr/crystal-lang/crystal/src/openssl/ssl/socket.cr:85: instantiating 'OpenSSL::BIO:Class#new(TCPSocket)'

    @bio = BIO.new(io)
               ^~~

instantiating 'OpenSSL::BIO#initialize(TCPSocket)'

in /Users/byron/dev/cr/crystal-lang/crystal/src/openssl/bio.cr:18: instantiating 'IO#read(Slice(UInt8))'

      io.read(Slice.new(buffer, len)).to_i
         ^~~~

in /Users/byron/dev/cr/crystal-lang/crystal/src/http/content.cr:55: instantiating 'IO#read(Slice(UInt8))'

      bytes_read = @io.read slice[0, to_read]
                       ^~~~

in /Users/byron/dev/cr/crystal-lang/crystal/src/io/sized.cr:34: instantiating 'Tuple(UInt64, UInt64)#min()'

      count = {slice.size.to_u64, @read_remaining}.min
                                                   ^~~

in /Users/byron/dev/cr/crystal-lang/crystal/src/enumerable.cr:572: instantiating 'min_by()'

    min_by &.itself
    ^~~~~~

in /Users/byron/dev/cr/crystal-lang/crystal/src/enumerable.cr:588: instantiating 'min_by_internal()'

    found, value = min_by_internal { |value| yield value }
                   ^~~~~~~~~~~~~~~

in /Users/byron/dev/cr/crystal-lang/crystal/src/enumerable.cr:604: instantiating 'each_with_index()'

    each_with_index do |elem, i|
    ^~~~~~~~~~~~~~~

in /Users/byron/dev/cr/crystal-lang/crystal/src/enumerable.cr:197: instantiating 'each()'

    each do |elem|
    ^~~~

in /Users/byron/dev/cr/crystal-lang/crystal/src/enumerable.cr:197: instantiating 'each()'

    each do |elem|
    ^~~~

in /Users/byron/dev/cr/crystal-lang/crystal/src/enumerable.cr:604: instantiating 'each_with_index()'

    each_with_index do |elem, i|
    ^~~~~~~~~~~~~~~

in /Users/byron/dev/cr/crystal-lang/crystal/src/enumerable.cr:606: no overload matches 'UInt64#<' with type U
Overloads are:
 - UInt64#<(other : Int8)
 - UInt64#<(other : Int16)
 - UInt64#<(other : Int32)
 - UInt64#<(other : Int64)
 - UInt64#<(other : UInt8)
 - UInt64#<(other : UInt16)
 - UInt64#<(other : UInt32)
 - UInt64#<(other : UInt64)
 - UInt64#<(other : Float32)
 - UInt64#<(other : Float64)
 - Comparable(T)#<(other : T)

      if i == 0 || value < min
                         ^
```
</details>

### Meta

```bash
 ../crystal-lang/crystal/bin/crystal --version && sw_vers
Using compiled compiler at .build/crystal
Crystal 0.18.7+310 [671ecb3] (2016-08-07)
ProductName:   	Mac OS X
ProductVersion:	10.11.6
BuildVersion:  	15G31
```

**Comment by kirbyfan64** [comment]
I vote this as the `#1` weirdest bug of the year.

**Comment by asterite** [comment]
Reduced:

```cr
class U
end

[1].map(&.to_s)
```

Note that `Array#map` is defined like this:

```cr
def map(&block : T -> U)
  Array(U).new(size) { |i| yield @buffer[i] }
end
```

That is, `U` is set to a free variable. However, because you are defining a type named `U`, now it's not a free variable anymore, it expects it to be that `U`.

So this is not a bug. Don't use single-letter classes in your projects, these are reserves for free variables and generic type arguments.

We could maybe disallow such types, though they are sometimes used in spec code in the compiler, but I could live with longer names.

**Comment by jhass** [comment]
I think disallowing them make sense, we could still allow them in namespaces, `Foo::U`, but disable same-module lookup for them in restrictions.

**Comment by kirbyfan64** [comment]
I would say this should be disallowed then. I mean, the error makes pretty much no sense...

**Comment by bcardiff** [comment]
I was afraid the playground had something to do ;-). 

If we disallow single letters type names we should disallow also single letters followed by numbers: `T1, T2` are also used as type variables.

**Comment by sdogruyol** [comment]
👍 for disallowing single letter type names.

**Comment by Byron** [comment]
Are generic type names, like `T` or `T1` allowed to be longer as well, such as `ListLike` ? If so, restricting type names to not match `[A-Z]\d*` wouldn't be enough. Maybe there is a way to adjust the compiler error message to hint at another possible cause of error, to help people change their type names into something else, without restricting anything.
(*please note that I have no clue what I am talking about, if needed, just ignore*)

**Comment by bcardiff** [comment]
@Byron , no prob, FYI type variables can only be single letters optionally followed by a digit: So `[A-Z]\d?` is enough as a check. But crystal is not avoiding them as actual type names.

**Comment by ozra** [comment]
Exactly. As we've discussed way before about the free-vars, and such they where given, the ability to enumerate. And they were kept allowed as type-names based on the grounds that _it would be convenient for examples_. If I may put another bet on such; let's make it official that _duck-lexing really is da shit_, and '[A-Z]\d' shall be only a generic identifier and _not allowed_ for type identification (where in an example 'Foo', 'Bar', etc. are our favourites, right!? :-) )

**Comment by david50407** [comment]
Disagree for this, I think disallowing these doesn't make sense.
Why you have to use single character (and with numbers) to naming your classes/libs/modules (or even const vars)?
They usually cannot represent what they meaning.
I think give a warning for this is better than disallowing all situations.

**Comment by bcardiff** [comment]
@david50407 let say you have a method `foo(t : T) : T` does this means a type called `T` or is a type variable? Right now means the second. To achieve this the grammar of types variables and types need to be disjoint, the criteria is `[A-Z]\d?` (it could be other, but the main issue is how to differentiate if something is a type or a type variable).

Other languages solve this problem by a lexical scope of the type variables.

In C#
```
class Bar<T> {
   // T is a type variable. 
   // If you want the T type you will need to fully qualified name 
   // or just peek some other name for the type variable to avoid the clashing  
}

static T foo<T>(t : T)
{
   // ...
}
```

So `<T>` declaras the type variable.

We do declare type variables in generic types: `Array(T)`. They serve for specialization of the concrete type you want, with actual types for ivars for `Array(Int32)`

Splitting the grammar by convention allows a simpler grammar in method declaration. Otherwise we would need something like `foo[T](t : T) : T` for declaring the `foo(t : T) : T`, or something similar that might interfere with the available method names, or add other grammar constructs for the method.

The whole issue right now is that the grammar of types variables and types are not properly disjoint.

**Comment by ysbaddaden** [comment]
> Don't use single-letter classes in your projects, these are reserves for free variables and generic type arguments.

If we can't use them in some context, let's prohibit these cases with a compile time error. User experience is more important than the documentation examples argument.

**Comment by david50407** [comment]
@bcardiff oh, you're right. I was thought this is discussing generic types, sorry.
I think disallowing these `[A-Z]\d?` is fine for reserving free vars and generic types.

> Don't use single-letter classes in your projects, these are reserves for free variables and generic type arguments.

@ysbaddaden +1, and we need more description to tell users why they cannot be used and why we shouldn't use only one char as classes/modules/libs name (more readability ).

**Comment by bcardiff** [comment]
There is another alternative, but I am not sure I will suit the taste of the crystallers :-)

We could go the Haskell does with type variables and make them share the grammar with normal variables.

```
class Array(t)
   # any mention of t is the type var, unless in is hidden by lexical scope.
   def foo(a : t) : t
   end

   def bar(t)
     # here t is the param
   end
end

def repeat(n, b : t) : Array(t)
   res = [] of t
   # ...
end
```

That will allow us to use long type variable names: `element_type`, `result`. It has no ambiguity since we have lexical scope. But it will be less clear at a first glance if `t` is a variable or a type variable.

We need to be sure that things like `foo(t : a, b: t)` don't compile since we are introducing the same variable twice with different meaning.

**Comment by david50407** [comment]
How about add a symbol in front of the free var? like this: (take `&` as example)

```crystal
class T
end

def (t : T) # <<< this means the calss T
  # blablabla
end

def (t : &T) # <<< with &, we can know this is a free var
  # blablabla
end
```
