### ISSUE TITLE
Constants in Errno:: have wrong description

### ISSUE THREAD

**Issue by paddor** [crystal-lang/crystal#3114]
This seems to be an error in the API doc parser. For example, `ENOENT` is [documented](https://crystal-lang.org/api/0.18.7/Errno.html) as `Operation not permitted`. It's probably because the descriptions are on the same line as the [constant definitions](https://github.com/crystal-lang/crystal/blob/bd01fb2a3b41f2762ee131938d3f18349bdb327e/src/errno.cr#L22) (not preceeding them).

I'd say it's the parser that has to be fixed, not the code in errno.cr, as it's a pretty common notation.

**Comment by asterite** [comment]
Ah, docs should be above the enum members, not to the right. This is the only way to document things in Crystal, there's no "after" doc comments.

And I'm not sure I'd like to have two ways to document things.

**Comment by paddor** [comment]
Cool! I can file a PR later.
