### ISSUE TITLE
Object.setter macro iterates over names twice

### ISSUE THREAD

**Issue by paddor** [crystal-lang/crystal#3115]
See the macro definition [here](https://github.com/crystal-lang/crystal/blob/93edf52a4172b3493dedbaf0ce720f5e36f4139e/src/object.cr#L586-L587). There seem to be two (nested) iterations over the `names`.

I guess there's no real purpose, or am I missing something? The `getter`/`getter!`/`getter?` macros don't do this.

**Comment by asterite** [comment]
I... I just wanted to be sure the generated setters were truly generated 😊 

Thanks for the catch! This was probably a copy-paste bug.

**Comment by paddor** [comment]
Hehe, it happens :)
