### ISSUE TITLE
Trouble running Crystal's specs

### ISSUE THREAD

**Issue by paddor** [crystal-lang/crystal#3122]
Just wanted to give #3121 a hypothetic improvement and implemented it, but I can't run Crystal's specs.

```
$ pwd
/Users/paddor/dev/crystal/crystal
$ crystal spec
Error in line 1: while requiring "./spec/all_spec.cr"

in ./spec/all_spec.cr:3: while requiring "./std_spec"

require "./std_spec"
^

in ./spec/std_spec.cr:2: while requiring "./std/**"

require "./std/**"
^

in ./spec/std/io/hexdump_spec.cr:2: while requiring "io/hexdump": can't find file 'io/hexdump' relative to '/Users/paddor/dev/crystal/crystal/spec/std/io'

require "io/hexdump"
^
```

I see that the file `src/io/hexdump.cr` exists, but it seems like it looks for that file under `spec/std/io` instead. Any ideas?

**Comment by jhass** [comment]
For working on the compiler you have to use the wrapper at `bin/crystal`. Additionally a plain `spec` won't work, run the standard library specs with `make std_spec`. Feel free to make suggestions on how we can document this better.

**Comment by asterite** [comment]
@jhass A plain `spec` does work. I almost never use the makefile except before commiting, to simplify that: `make clean crystal spec`. But I always do `bin/crystal spec/std_spec.cr` or `bin/crystal spec/compiler_spec.cr` or run any spec in that directory, like `bin/crystal spec/std/int_spec.cr`.

My ideal Crystal behaviour is one where a Makefile is not needed. In fact we are now very close to that, and the compiler can be simply compiled with `bin/crystal build src/compiler/crystal.cr` without using the Makefile.

**Comment by jhass** [comment]
```
bin/crystal spec
Using compiled compiler at .build/crystal
Error in line 165: while requiring "./spec/std/crypto/bcrypt/password_spec.cr"

in ./spec/std/crypto/bcrypt/password_spec.cr:2: while requiring "crypto/bcrypt/password"

require "crypto/bcrypt/password"
^

in ./src/crypto/bcrypt/password.cr:1: while requiring "../bcrypt"

require "../bcrypt"
^

in ./src/crypto/bcrypt.cr:27: Bcrypt is not a class, it's a module

class Crypto::Bcrypt
      ^

```

**Comment by asterite** [comment]
Strange. My guess is that it has to do with the other of the filenames in the filesystem, or how they are listed. I don't know why it works for me (mac osx).

Can you try fixing the requires? The error is probably because `module Crypto::Bcrypt::Base64` is required before other files (or Blowsifh, or Password, for that matter). If that fixes it, then we should fix it at the compiler level by ensuring the same order everywhere... though I though we were already [doing that](https://github.com/crystal-lang/crystal/blob/b464df61799953cf945b116a13fcb9e753053feb/src/compiler/crystal/crystal_path.cr#L110-L111).

**Comment by jhass** [comment]
If you intend that to work, perhaps we should switch `make all_spec` to calling it?

**Comment by asterite** [comment]
@jhass Good idea, but we should probably do that after we fix the problem.

**Comment by jhass** [comment]
I guess one issue is that it doesn't take any of the `crystal build` flags.

**Comment by asterite** [comment]
What flags?

**Comment by jhass** [comment]
```
FLAGS := $(if $(release),--release )$(if $(stats),--stats )$(if $(threads),--threads $(threads) )$(if $(debug),-d )
```

**Comment by asterite** [comment]
But those can be passed like `--release`, etc.

**Comment by jhass** [comment]
They can? Not erroring on invalid flags and nothing on `--help` threw me off I guess.

**Comment by asterite** [comment]
I mean, you can do `bin/crystal spec/all_spec.cr --release`. Not sure it works with `bin/crystal spec --release` though.

**Comment by jhass** [comment]
Well yes, of course. But the point was that we want to put `bin/crystal spec` under test, not `bin/crystal foo.cr`.

**Comment by asterite** [comment]
Oh... I see `crystal spec` also lists the files on its own. Maybe they are not sorted there.

If you do `bin/crystal spec/all_spec.cr`, does it work?

**Comment by jhass** [comment]
Yes sure, that's not so different from `build` after all.

**Comment by asterite** [comment]
Ah, good. I thought the problem was in CrystalPath, but it seems to be in `spec`

**Comment by paddor** [comment]
@jhass Thanks, using the wrapper `bin/crystal` it looks better. But it fails like this after a few seconds:

```
$ bin/crystal  spec
Using compiled compiler at .build/crystal
Warning: benchmarking without the `--release` flag won't yield useful results
Assertion failed: (CastInst::castIsValid(opc, C, Ty) && "Invalid constantexpr cast!"), function getCast, file Constants.cpp, line 1497.
[5]    23841 abort      bin/crystal spec
bin/crystal spec  27.30s user 1.09s system 121% cpu 23.378 total
```

**Comment by jhass** [comment]
What's your LLVM version?

**Comment by paddor** [comment]
```
$ llvm-config  --version
3.8.1
$ llvm-config-3.5  --version
3.5.1
```

Both are in /usr/local/bin, which is a bit confusing. First one is from the `llvm` Homebrew formula, second one is from the `llvm35`.

I guess Crystal will use the `llvm-...` commands?

Not sure if this is relevant, but:
```
$ which clang
/usr/bin/clang
$ /usr/bin/clang -v
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
(same for `clang++`)

**Comment by asterite** [comment]
@paddor Your [first output](https://github.com/crystal-lang/crystal/issues/3122#issuecomment-238582247) says "Using compiled compiler at .build/crystal". Did you make changes to the compiler?

**Comment by paddor** [comment]
Nope. Even `git stashed` my tiny change to `String#tr` (and specs) and ran `make clean; make`.

**Comment by paddor** [comment]
Uninstalling `llvm35` and rebuilding (`make clean; make`) helped. Damn there are many specs.
