### ISSUE TITLE
#printf docs missing

### ISSUE THREAD

**Issue by paddor** [crystal-lang/crystal#3124]
The API doc of both `Kernel#printf` and `#sprintf` refer to `IO#printf` for documentation. But the two overloads there are actually [undocumented](https://github.com/crystal-lang/crystal/blob/68783f1ebdd5b9bbefc8892ddbc200fe1f13bbea/src/io.cr#L350-L358) (first being empty, second saying `ditto` 😆).

(Maybe unrelated, but in the source I see that `String::Formatter` is used, but for some reason that class is hidden from the API doc. Maybe that could be a good place to put the documentation?)

**Comment by miketheman** [comment]
#triage
This issue has languished, and it appears that attempts were made to resolve, but eventually got closed with no true resolution.

The methods remain undocumented:
https://crystal-lang.org/api/0.21.0/IO.html#printf%28format_string%2Cargs%3AArray%7CTuple%29%3ANil-instance-method
https://github.com/crystal-lang/crystal/blob/c2c2276ec667171af5c2347490f49acdbdc4a3ca/src/io.cr#L352-L360

What can we do to push this forward? [This discussion](https://github.com/crystal-lang/crystal/pull/3126#r74061994) appears to point at the Ruby docs for sprintf.

Should/can we copy the style (tables, formatting) and get that in here? @asterite You seemed to have the stronger opinion here.

**Comment by ysbaddaden** [comment]
I would document the `IO#printf` method, not the private formatter class (it's an implementation detail). I would document what is actually supported as a simple list of codes and expected types, with a few examples. Something very basic at first. Maybe see the Ruby docs and the `printf` man page for reference.

**Comment by WazzaSoft** [comment]
What's the status on this? I would like to contribute and this seems like a good starting place if nobody is taking this on. Let me know if you all would like me to start working on it.

**Comment by straight-shoota** [comment]
@WazzaSoft Still up for this?

**Comment by WazzaSoft** [comment]
@straight-shoota Yes, I am.

**Comment by RX14** [comment]
@WazzaSoft go right ahead, no need to ask before making a PR.

**Comment by CaDs** [comment]
I did not see any PR regarding this issue so I have created one.
https://github.com/crystal-lang/crystal/pull/5762

It follows both @ysbaddaden and @asterite suggestions about how to document this method.

Please take a look when you have the time and let me know if there is anything else you would me to change.
