### ISSUE TITLE
Instance var loses its type in generic abstract inheritance

### ISSUE THREAD

**Issue by Exilor** [crystal-lang/crystal#3133]
[abstract -> abstract -> concrete](https://play.crystal-lang.org/#/r/16sk) works
[abstract(T) -> abstract(T) -> concrete(T)](https://play.crystal-lang.org/#/r/16sp) works
[abstract -> abstract -> concrete(T)](https://play.crystal-lang.org/#/r/16sm) works
[abstract -> abstract(T) -> concrete(T)](https://play.crystal-lang.org/#/r/16sl) fails
In the examples I used structs but the same happens with classes.
Is this by design?

**Comment by asterite** [comment]
Duplicate of https://github.com/crystal-lang/crystal/issues/2665

Generic inheritance is currently broken. I'm working on it :-)
