### ISSUE TITLE
Inconsistent override for non-typed splats

### ISSUE THREAD

**Issue by cjgajard** [crystal-lang/crystal#3134]
A method with non-typed splat arguments get overridden by the next overload:
https://carc.in/#/r/16uk

And overrides all previous typed-splats:
https://carc.in/#/r/16ul

Double-splats have this behaviour too.

This is inconsistent with the behaviour of single arguments:
https://carc.in/#/r/16um

**Comment by asterite** [comment]
@cjgajard Nice find, thank you!
