### ISSUE TITLE
Error: global variable '$foo' must be Nil, not T

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#3136]
What the foo...? https://carc.in/#/r/16wb

**Comment by asterite** [comment]
The type of global variables is inferred from all assignments to it, where the type can be inferred. In this case the only case here is the `$foo = nil`, it can't infer it from the other assignment. You'll have to annotate it (or avoid using global variables altogether, because they will be removed in a future version of the language)

**Comment by Sija** [comment]
I see, too bad they'll be gone since it's pretty common to use globals in ad-hoc scripting where OOP is not rly that suitable.

**Comment by jhass** [comment]
I never had to, a constant was just fine in these cases for me.

**Comment by Sija** [comment]
@jhass constants cannot be reassigned.

**Comment by jhass** [comment]
I am and was well aware of that.

**Comment by Sija** [comment]
@jhass Could you please show how would you handle the case from carc.in example—considering that `$foo.empty?` and `$foo.nil?` would have different semantics in code - empty vs not-assigned?

**Comment by asterite** [comment]
```cr
class MyFoo
  @@foo : Array(Int32)?

  def self.foo
    @@foo ||= [1, 2, 3].map &.*(3)
  end
end

puts MyFoo.foo
```

**Comment by Sija** [comment]
@asterite That's what I reckoned... but is there any way to do achieve it without `class` or `module`?

**Comment by asterite** [comment]
@Sija No, but that's the reason why we want to remove global variables: class variables must be accessed through a method, so it'll be easier to synchronize access to them. It also gives them a clear owner, avoiding name clashes. Then it's easier to define their type and an initializer, which is run lazily when the value is needed.

With global variables tracking all of this is much harder, as it's harder to distinguish between a global variable initialization and a random assignment to it.

**Comment by Sija** [comment]
Fair 'nuff, thanks for taking time in digging into this :)
