### ISSUE TITLE
File stream pointer of FD

### ISSUE THREAD

**Issue by paddor** [crystal-lang/crystal#3151]
Some functions of a C-library I'm writing a binding for take a `*FILE` argument pointing to a file stream. Crystal's `File` class has `#fd` which can be associated with a file stream using `fdopen()`. I checked the LibC binding in Crystal but couldn't find this function.

The following line would be enough, I suppose:

``` crystal
  fun fdopen(fd : Int, mode : Char*) : Void*
```

As to where to put it, there are six `stdio.cr` files for different platforms. According to the Open Group [standard](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fdopen.html) it has been standardized since _Issue 1_, so should be well supported on various platforms. So where's the best place to put this? Or are there any opinions against having this function binding in Crystal's LibC?

**Comment by jhass** [comment]
If we want to support this, I think it should be `File#to_libc_file` or something like that, hiding the `fdopen` call.

**Comment by RX14** [comment]
I'd rather not have it in the stdlib at all if at all possible.

**Comment by paddor** [comment]
No hurries. That project is on ice.
