### ISSUE TITLE
Test raises error but doesn't fail

### ISSUE THREAD

**Issue by iostreamer-X** [crystal-lang/crystal#3152]
I have this function which accepts a string and a Proc, it then does something like this
```crystal
spawn do
  proc.call string
end
```

And in my _-spec.cr I call the function like this
```crystal
thatFunction "coookie", ->(user_id : String){
      puts user_id
      user_id.should eq "8283"
}
```

Since the user_id I get is "82833", this test is bound to fail, but it doesn't.

Output
```crystal
.82833
Unhandled exception:
expected: "8283"
     got: "82833" (Spec::AssertionFailed)
[4764727] *CallStack::unwind:Array(Pointer(Void)) +87
[4764618] *CallStack#initialize:Array(Pointer(Void)) +10
[4764570] *CallStack::new:CallStack +42
[4722920] *raise<Spec::AssertionFailed>:NoReturn +24
[4722894] ???
[4808356] *String +84
[4722834] ~procProc(String, Nil) +98
[4723131] ~procProc(Nil) +59
[4761780] *Fiber#run:(Int64 | Nil) +180
[4694753] ~proc2Proc(Fiber, (Int64 | Nil)) +17
[0] ???
.

Finished in 6.75 seconds
2 examples, 0 failures, 0 errors, 0 pending

```

Is this expected behavior?

Note, `thatFunction` is created through a macro

**Comment by jhass** [comment]
Yes, the exception is raised in the new fiber, it's not magically propagated to the fiber next switched to.

**Comment by iostreamer-X** [comment]
Got it, thank you. 
Any way to make it fail?

**Comment by jhass** [comment]
https://carc.in/#/r/1726

**Comment by iostreamer-X** [comment]
Thanks a lot! I was thinking too much in terms of Fibers that such a simple solution didn't strike :smile:

**Comment by jhass** [comment]
The other solution is to channel out the value: https://carc.in/#/r/1727
