### ISSUE TITLE
Wrong line in compilation error message in macro expansions

### ISSUE THREAD

**Issue by bcardiff** [crystal-lang/crystal#3154]
When declaring many properties in `Object#property` macro, if there is a compilation issue triggered by the expanded code the location pointed by the exception is misleading.

**file: foo.cr**

```crystal
class Foo
  property x, y : Int32
end

Foo.new
```

The following error shows there is an issue with **line 12**, yet the file is 5 lines long.

```
$ crystal build foo.cr 
Error in macro 'property' /usr/local/Cellar/crystal-lang/0.18.7_1/src/object.cr:667, line 12:

  1.     
  2.       
  3.         def x
  4.           @x
  5.         end
  6. 
  7.         def x=(@x)
  8.         end
  9.       
 10.     
 11.       
 12.         @y : Int32
 13. 
 14.         def y : Int32
 15.           @y
 16.         end
 17. 
 18.         def y=(@y : Int32)
 19.         end
 20.       
 21.     
 22.   

        @y : Int32
        ^~

instance variable '@y' of Foo was not initialized in all of the 'initialize' methods, rendering it nilable
```

https://play.crystal-lang.org/#/r/172u

**Comment by RX14** [comment]
The "line 12" bit is showing what line of the expanded macro snippet the exception is in, not the place in the original file.
