### ISSUE TITLE
Allow generic module to set types in classes

### ISSUE THREAD

**Issue by KCreate** [crystal-lang/crystal#3159]
Currently, the following code is not supported
```crystal
module Foo(T)

  class Qux(H)
    property bar : T
    property baz : H

    def initialize(@bar, @baz)
    end
  end
end
```

Produces:
```
undefined constant T
```

What's the thought behind not supporting this?

**Comment by asterite** [comment]
The class `Qux(H)` is nested inside `Foo`, but has nothing to do with it. `Foo` just acts as a namespace.

You can do:

```cr
Foo::Qux(Int32)
```

and you **can't** do:

```cr
Foo(Int32)::Qux(Char) # syntax error
```

That is, nested classes in Crystal are not like nested classes in Java (and I think C#) where the nested instance has a pointer to the parent instance.

**Comment by jhass** [comment]
See also #1920

**Comment by KCreate** [comment]
Thanks for the fast response. I see that a module acts like a namespace for classes and such, but it behaves differently for methods. Methods can only be accessed by either including them or via extending the module with a class.

It would be nice if a class can also depend on these type variables (e.g `T`). Such a class would then be invisible to the outside (just like a method definition).

Any thoughts?

**Comment by asterite** [comment]
Make `Qux` be `Qux(T, H)`. We won't inherit type parameters to nested types. Check for example how [Hash](https://github.com/crystal-lang/crystal/blob/master/src/hash.cr) and `Hash::Entry` are implemented.
