### ISSUE TITLE
abstract `def Spider#spiderInit()` must be implemented by Spider:Module

### ISSUE THREAD

**Issue by ssaatya** [crystal-lang/crystal#3165]
Compiler says module should implement abstract method if it extends self

```
module Spider
   extend self
   @client = nil

   def request(action,type="text",method="GET")
        response = HTTP::Client.get action 
        puts response.body()
   end

   abstract def spiderInit()
end
```

**Comment by jhass** [comment]
Well, yes, you do `extend self` and there's no `Spider.spiderInit` defined. Why do you `extend self`?

**Comment by ssaatya** [comment]
So i can create also use namespace

**Comment by jhass** [comment]
No, that's not necessary in order to use a module as a namespace for other modules, classes, structs, enums, constants or aliases.

**Comment by ssaatya** [comment]
Ok. So it is not a bug

**Comment by jhass** [comment]
Perhaps it's a documentation bug, what make you think `extend self` was necessary?

**Comment by ssaatya** [comment]
No.
