### ISSUE TITLE
How to reinitialize a variable with multiple initialize methods

### ISSUE THREAD

**Issue by ssaatya** [crystal-lang/crystal#3166]
when reinitializing in different method compiler asks me to make function argument nilable

```
require "http/client"

module Spider

   def initialize(@host : String, options : (Tuple)? )
        @@client = HTTP::Client.new @host
   end
   
   def request(action, type="text", method="GET")
        response = @client.exec method action 
        puts response.body()
   end

   def reuse(@host)
        @@client = HTTP::Client.new @host
   end

   
   
end
```

**Comment by jhass** [comment]
`@client` and `@@client` are entirely different variables. Also you can't make an instance of a `module`, so I'm not quite following why you define an `initialize` method there. My recommendation would be to make `Spider` a `class` and use an instance variable for `@client`.

**Comment by ssaatya** [comment]
no it is for the host variable

**Comment by jhass** [comment]
Can you show how you use this?

**Comment by ssaatya** [comment]
I didnt get you

**Comment by jhass** [comment]
The code you provided doesn't produce any error: https://carc.in/#/r/17a9

**Comment by ssaatya** [comment]
I use this in another class

```
class AUR
    include Spider

    def initialize() 
        Spider.new "https://aur.archlinux.org"
    end
	    
    def searchPackage(package, by : String = "name-desc")
       request "/", method="GET"
    end   

end
```

**Comment by jhass** [comment]
So, that classes `initialize` does not set `@host`, which means if you call `AUR.new`, there's no value for `@host`, it's `nil` but your forbid it to be `nil`.

**Comment by ssaatya** [comment]
host has a value "aur.archlinux.org"

**Comment by jhass** [comment]
No, the instance of `AUR` you make has no variable `@host` set to `"https://aur.archlinux.org"`. If you add `@host = "dummy"` to your `def initialize` in `AUR`, you'll get the next error of `Spider` not having a `new` method, `Spider.new` is not how you can call the initialize method of an included module.

**Comment by ssaatya** [comment]
I have changed it and i still get same error

**Comment by jhass** [comment]
Changed it to what?

**Comment by ssaatya** [comment]
making @host makes it instance variable of AUR not an argument

**Comment by jhass** [comment]
https://carc.in/#/r/17ab those are your options.

**Comment by ssaatya** [comment]
I have edited https://carc.in/#/r/17ad it . So it is only error if namespace is used

**Comment by ssaatya** [comment]
How do you run compiler in verbose

**Comment by jhass** [comment]
There's no such thing, I find it quite verbose already.

`in line 32: undefined local variable or method 'allocate'` is because you can't make an instance of a `module` like you try on, well, line 32.

**Comment by ssaatya** [comment]
OK thanks
