### ISSUE TITLE
Add option for playground editor font-family

### ISSUE THREAD

**Issue by b00401062** [crystal-lang/crystal#3167]
Anyone hopes to have an option for changing playground editor font-family in setting? I can create a branch to add this feature which I am using locally.

**Comment by jhass** [comment]
If we do something like this it probably should be a whole custom stylesheet or os.

**Comment by luo820802** [comment]
I agree to add a whole custom stylesheet which is what I expect the playground to have. Let's leave this feature as an enhancement for the future :)

**Comment by bcardiff** [comment]
Maybe a easy way to do this is to use the `./playground` directory for holding additional css/js files. It might come handy for presentations. Maybe all `./playground/resources` could be statically served in `/resources`.

**Comment by bcardiff** [comment]
Since 0.19.2 you can override the playground stylesheets, but only in the workbooks.

```
$ tree
.
└── playground
    ├── resources
    │   └── font.css
    └── sample.cr

2 directories, 2 files

$ cat playground/resources/font.css 
.editor, .sidebar, .output, .inspect-values, .CodeMirror {
  font-family: 'Courier New', monospace;
  font-size: 22px;
  line-height: 1.46em;
}

$ cat playground/sample.cr 
puts "foo"

$ crystal play
```

open http://localhost:8080/workbook/playground/sample

**Comment by straight-shoota** [comment]
There has been no interest in this for a long time, so it's fair to assume that the feature added in 0.19.2 should suffice.
