### ISSUE TITLE
IO.select not blocking

### ISSUE THREAD

**Issue by Exilor** [crystal-lang/crystal#3169]
[https://play.crystal-lang.org/#/r/17bt](https://play.crystal-lang.org/#/r/17bt)
I'm far from an expert on IO but shouldn't this code block or something after the first #times iteration? 
The example is a simplification of code involving TCPSocket which exhibits the same behavior.

**Comment by Exilor** [comment]
The linked example has been deleted for some reason.
The code:
```crystal
IO.pipe do |read, write|
  write.write Slice[134_u8]
  write.close
  5.times do
    result = IO.select({read})
    buf = Slice[0_u8]
    result[0].read buf
    p buf
  end
end
```
The output:
```crystal
Slice[134]
Slice[0]
Slice[0]
Slice[0]
Slice[0]
```

**Comment by asterite** [comment]
`IO.pipe` has `read_blocking` and `write_blocking` arguments, which are `false` by default.

Apart from that, I don't think `IO.select` is usable after we made the switch to non-blocking IO, so I wouldn't use it (I'd probably use channels and spawn if possible)

**Comment by jazzonmymind** [comment]
if it's not usable why keep it in the language?

**Comment by Exilor** [comment]
@asterite I was under the impression that ```select``` was precisely part and parcel of non-blocking IO :confused: which is the part of the code that I expected to block indefinitely (timeout = nil), not the #read calls themselves. 
As for the arguments to IO.pipe:
```crystal
IO.pipe(true, true) do |read, write|
  write.write Slice[134_u8]
  write.close
  5.times do
    result = IO.select({read})
    buf = Slice[0_u8]
    result[0].read buf
    p buf
  end
end
```
Doesn't block at any point either.

**Comment by asterite** [comment]
Maybe there's something I'm not understanding, but this in Ruby:

```cr
IO.pipe do |read, write|
  write.write "a"
  write.close
  5.times do
    result = IO.select([read])
    p result[0][0].read 1
  end
end
```

Prints:

```
"a"
nil
nil
nil
nil
```

So similar behaviour to Crystal.

**Comment by ysbaddaden** [comment]
I guess we don't need `select` anymore since the language is now evented and uses the polling solutions that are more efficient than the old `select`. Keeping it is confusing, and fibers and channels should take over.

**Comment by Exilor** [comment]
It turns out that the simplified example reproduces my issue only in appearance and by coincidence so I'm closing this. And from the comments I gather that this is not the way we will do these kind of things so I won't go further in this direction.
