### ISSUE TITLE
Error when trying to build documentation offline

### ISSUE THREAD

**Issue by KCreate** [crystal-lang/crystal#3175]
I cloned the `crystal-lang/crystal` repo and ran `crystal docs` in it.
I hoped this would give me an offline version of the docs displayed at `https://crystal-lang.org/api/0.18.7/`.

```
Error in line 1: while requiring "./src/**"

in ./src/prelude.cr:18: while requiring "indexable": can't find file 'indexable' relative to '/Users/leonardschuetz/Documents/GitHub/crystal-lang/crystal/src'

require "indexable"
```

**Comment by jhass** [comment]
Try `make doc`.

**Comment by jhass** [comment]
@KCreate did that work for you? Please reopen with how `make doc` failed if not.

**Comment by KCreate** [comment]
I don't have any llvm-config or similar in my PATH

`Makefile:19: *** Could not locate llvm-config, make sure it is installed and in your PATH.  Stop.`

**Comment by KCreate** [comment]
Also I can't reopen the issue.

**Comment by jhass** [comment]
Oh, if you don't have LLVM installed you can try `bin/crystal doc src/docs_main.cr`.

**Comment by KCreate** [comment]
Gives me the following error

```
$ bin/crystal doc src/docs_main.cr
Error in /Users/leonardschuetz/Documents/Github/crystal-lang/crystal/src/big/lib_gmp.cr:3: alias Int is already defined

  alias Int = LibC::Int
  ^
```

**Comment by asterite** [comment]
This might happen if you have an old version of crenv, not sure. Please reopen if it still happens to you.
