### ISSUE TITLE
Is it possible to get values from an array by multiple indices?

### ISSUE THREAD

**Issue by luo820802** [crystal-lang/crystal#3179]
To get values from an array by multiple indices is something like this:
```
a = [1, 2, 3, 1, 2, 3]
a[[-1, -5, 3, 1]] #=> [3, 2, 1, 2]
```
I will appreciate if anyone knows any function doing the same thing.
If there is no such method for Array, is it possible for Crystal team to implement one?

**Comment by Sija** [comment]
You're most likely looking for [`Array#values_at`](https://crystal-lang.org/api/0.18.7/Array.html#values_at%28%2Aindexes%3AInt%29-instance-method) method.

**Comment by luo820802** [comment]
Thanks =) This solves my problem. Please close this silly issue...

**Comment by Sija** [comment]
You're welcome! You can easily close this issue yourself btw :)
