### ISSUE TITLE
Array splicing error ???

### ISSUE THREAD

**Issue by b00401062** [crystal-lang/crystal#3180]
Is this a bug or I am missing something?
The result of `a[1, 3] = [6, 7, 8]` seems wrong.

![screen shot 2016-08-20 at 8 48 10 am](https://cloud.githubusercontent.com/assets/10905163/17827647/2789ffc0-66b3-11e6-897f-19069e22044b.png)

**Comment by Sija** [comment]
Ruby reports the same:
```ruby
a = [1, 2, 3, 4, 5]
a[1, 3] = [6, 7, 8]
a # => [1, 6, 7, 8, 5]
```

**Comment by luo820802** [comment]
But Crystal gives me `[1, 3, 3, 4, 5]`. Please check the output panel.

**Comment by Sija** [comment]
Weird indeed... `icr` returns correct `[1, 6, 7, 8, 5]` but `crystal play` shows `[1, 3, 3, 4, 5]`.
Line#6 seems off since it should return `[6, 7, 8]`.

**Comment by Sija** [comment]
Yup, doing `pp a[1, 3] = [6, 7, 8]` shows `a[1] = 3 # => 3` in output console, so it might be more a `crystal play` bug.

**Comment by Maroo-b** [comment]
This issue is not reproducible with 0.27.2. Should we close it?

**Comment by straight-shoota** [comment]
Yes, seems to be fixed in the playground (was reported a long time ago^^).
