### ISSUE TITLE
Implement Kernel#raise/0

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#3181]
From Ruby docs:
> With no arguments, raises the exception in $! or raises a RuntimeError if $! is nil.

It's worth noting that it allows for easy re-raising exceptions within `begin ... end` blocks.
I can take a stab at PR if you want.

**Comment by asterite** [comment]
We don't have `$!`, and for this we'd need a global variable, so it's a no-no.

I don't think it's so bad to do:

```cr
begin
  # ...
rescue ex
  raise ex
end
```

It's 4 chars more.

**Comment by Sija** [comment]
@asterite There's `$?` and `$~` pseudo-global variables, so why not add `$!` to the mix? Again, that would bring Crystal syntax 6 chars (4 + spaces) closer to Ruby in this case.

**Comment by asterite** [comment]
@Sija Because they are called `pseudo-global` variables in Ruby, but they are actually thread-local in Ruby, and method-local in Crystal, so having `global` in their name has little sense. But `$!` is global in Ruby, and we'd really like to avoid having too much global state around.

**Comment by yxhuvud** [comment]
Theoretically, you could keep most usages of how raise is used in ruby by using a local variable though. It would disallow reraising without arguments from methods that is called from the exception handler, but have anyone actually seen anyone use that in practice?
