### ISSUE TITLE
Spec profile: present slow examples duration in human friendly

### ISSUE THREAD

**Issue by luislavena** [crystal-lang/crystal#3186]
Hello,

Before I send a pull request on this subject, I wanted to check if the current behavior was desired or not.

Right now (as `master`), when run `crystal spec --profile`, will present slow examples duration _in seconds_, which can be a problem for fast-running examples, like [Radix](https://github.com/luislavena/radix):

```
$ ccr --version
Using compiled compiler at .build/crystal
Crystal 0.18.7+355 [5b3c9dc] (2016-08-19)

$ ccr spec --profile
Using compiled compiler at .build/crystal
..............................................

Top 10 slowest examples (0.0004548 seconds, 44.74% of total time):
  0.3.1 matches version defined in shard.yml
    0.0002726 seconds ./spec/radix/version_spec.cr:6
  Radix::Tree(T) #add dealing with duplicates does not allow same path be defined twice
    4.68e-05 seconds ./spec/radix/tree_spec.cr:176
  Radix::Tree(T) #add dealing with catch all and named parameters prioritizes nodes correctly
    2.06e-05 seconds ./spec/radix/tree_spec.cr:190
  Radix::Tree(T) #add shared root inserts multiple nodes with mixed parents
    2.0e-05 seconds ./spec/radix/tree_spec.cr:112
...
Finished in 1.02 milliseconds
46 examples, 0 failures, 0 errors, 0 pending
```

Want to confirm if will be better the examples duration leverage on `Spec.to_human` (like other places).

Perhaps is a presentation issue and requesting _n_ number of decimals will correct it instead.

Please let me know and will send the appropriate pull request.

Thank you.

:heart: :heart: :heart:

**Comment by jhass** [comment]
IMO a presentation issue, as I argued in #2875 I think choosing the same scale for all examples depending on the slowest one makes comparing them a whole lot easier.

**Comment by luislavena** [comment]
Indeed just a presentation issue (is not that things are broken), but having a more human friendly version presented to the end user have value too.

Just checking, will be something I can spend a bit of time improving and would love to.

Thank you for your quick response. If nobody objects until the end of the day, will get that sorted out tomorrow.

Cheers.

**Comment by faustinoaq** [comment]
Wow, I just realize `--profile` is an available flag, is this documented somewhere?

`crystal spec --help` shows me this:

```
➜  ~ crystal spec --help
Usage: crystal spec [options] [files]

Options:
    -d, --debug                      Add full symbolic debug info
    --no-debug                       Skip any symbolic debug info
    -D FLAG, --define FLAG           Define a compile-time flag
    --error-trace                    Show full error trace
    --release                        Compile in release mode
    -s, --stats                      Enable statistics output
    -p, --progress                   Enable progress output
    -t, --time                       Enable execution time output
    -h, --help                       Show this message
    --no-color                       Disable colored output
➜  ~ crystal -v
Crystal 0.24.2 (2018-03-19)

LLVM: 6.0.0
Default target: x86_64-pc-linux-gnu
```

**Comment by RX14** [comment]
@faustinoaq `crystal spec -- --help`

**Comment by straight-shoota** [comment]
@RX14 Yeah, that's very commonly misunderstood. For starters, adding a note about checking the runtime help to the compiler help output would be an improvement.
