### ISSUE TITLE
bug assignment in if

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3187]
```crystal
if x = 1 && (y = 2)
  p(x, y)
end
```

```
2
2
```

**Comment by rmosolgo** [comment]
woah, it's parsing it as 

```crystal
if x = (1 && (y = 2))
  p(x, y)
end
``` 
?

**Comment by kostya** [comment]
actually ruby print the same in this code;

**Comment by david50407** [comment]
BTW, in Ruby, you can use `if x = 1 and (y = 2)`, but Crystal seems not having these low-priority operators.
