### ISSUE TITLE
merge for named_tuple

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3188]
would be nice if this works

```crystal

res = {a: 1, b: "bla"}

if (x = rand) && (x > 0.5)
  res = res.merge(c: x)
end

p res.to_json

```

**Comment by david50407** [comment]
`Tuple` and `NamedTuple` are immutable because they was created on compile-time.

Use `Hash` for merge.

**Comment by RX14** [comment]
In this case merge would return a new copy, it might need a different name but the idea is solid. I'm reminded of the `copyWith` method on groovy immutable objects.

**Comment by lbguilherme** [comment]
This can be easily implemented:

```cr
struct NamedTuple(T)
  def merge(**other)
    NamedTuple.new(**self, **other)
  end
end
```

But I'm not sure where it would be good. Something like this wouldn't work, for example:

```cr
def foo(a, b, c)
  p [a, b, c]
end

foo(**res)
```

    Error in line 21: double splatting a union
    (NamedTuple(a: Int32, b: String) | NamedTuple(a: Int32, b: String, c: Float64))
    is not yet supported

**Comment by kostya** [comment]
@lbguilherme thanks, i think last error is correct, i just needed type independent hash, which converted to_json in the end. with hash this would not work, because Float64 not a type of first hash, but with named tuple this works.

**Comment by kostya** [comment]
@asterite may be add @lbguilherme version?

**Comment by asterite** [comment]
I still think Hash should be used if dynamic content is needed...

**Comment by asterite** [comment]
I'm not discarding this yet, I just need to think it a bit more

**Comment by kostya** [comment]
hm, but this work with hash also:
```crystal
res = {"a" => 1, "b" => "bla"}

if (x = rand) && (x > 0.5)
  res = res.merge({"c" => x})
end

p res

```

seems, earlier was a problem to merge different types, but now ok.
