### ISSUE TITLE
Create IDE plugins to ease development in crystal-lang

### ISSUE THREAD

**Issue by kumaranvpl** [crystal-lang/crystal#3189]
Create plugins for IDEs like jetbrains, atom, etc to ease development in crystal-lang

**Comment by veelenga** [comment]
@kumaranvpl I don't think this is a responsibility of crystal core team. Nevertheless you can find some links to Editor/IDE plugins here [awesome-crystal#editor-plugins](https://github.com/veelenga/awesome-crystal#editor-plugins).

**Comment by bcardiff** [comment]
@kumaranvpl I don't expect plugin development in the near future. We did some tooling in the compiler. Check https://crystal-lang.org/2015/09/05/tools.html . Those are able to be used from atom and vi (thanks https://github.com/rhysd/vim-crystal). There could be more tools like, with the compiler, or at least, editor independent. 

Is there any particular tool you wish to have?

**Comment by faustinoaq** [comment]
@bcardiff https://github.com/kofno/scry this project seems very good.

**Comment by bcardiff** [comment]
Yeap @faustinoaq it seems promising. I haven't try VS Code yet but is a sweet spot and maybe is ahead plain atom for developing a IDE-like environment. I can't judge from readme if there is any user story covered yet by [kofno/scry](https://github.com/kofno/scry) or [kofno/crystal-ide](https://github.com/kofno/crystal-ide), but I will check them eventually.

**Comment by raydf** [comment]
I'm usng scry with crystal-ide and the performance is amazing and i'm prefering the syntax highlighting  over Atom. There's a lot to improve but is a great first version by @kofno.

**Comment by asterite** [comment]
Closing this issue as question was answered. Check the [wiki](https://github.com/crystal-lang/crystal/wiki#editor-support) for editor support.

**Comment by bararchy** [comment]
@asterite Can we add https://youtrack.jetbrains.com/issue/RUBY-17225 as "In progress" or "please vote for it" etc.. ? 
If we get an official intelij plugin it would be so awesome !
