### ISSUE TITLE
can't define method in generic instance Slice(UInt8):Class

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3190]
this ok compile in 0.18.7
but in master error:

```crystal
in ./src/message_pack/from_msgpack.cr:73: can't define method in generic instance Slice(UInt8):Class

def Bytes.new(pull : MessagePack::Unpacker)
    ^~~~~

```

**Comment by bcardiff** [comment]
You would need to define it for `Slice(T)` since `Bytes` is just an alias.

Something like C++ template method specialization is not available (yet?)

**Comment by ozra** [comment]
Specializations would be awesome.

**Comment by asterite** [comment]
This used to compile but the behaviour was that the method was added to `Slice`. There's no way to add methods to a particular instantiation, and I think it can actually be pretty confusing to do so (for starters, where in the docs all these overloads appear?)

Now the compiler correctly fails to parse this code. Just define the method on `Slice` and it'll be OK.
