### ISSUE TITLE
IO::ByteFormat::SystemEndian is inconsistent inside macros

### ISSUE THREAD

**Issue by Exilor** [crystal-lang/crystal#3191]
[Example](https://play.crystal-lang.org/#/r/17gg). It exits with an error there, but on my computer the output is:
```
1 IO::ByteFormat::LittleEndian
2 IO::ByteFormat::LittleEndian
3 IO::ByteFormat::BigEndian
```
The same code outside of macro context always returns LittleEndian.

Edit: the code
```crystal
{% if true %}
  class Foo
    @order : IO::ByteFormat = IO::ByteFormat::SystemEndian
    puts "1 #{IO::ByteFormat::SystemEndian}"
  end
  puts "2 #{IO::ByteFormat::SystemEndian}"
{% end %}

puts "3 #{Foo.new.@order}"
```

**Comment by asterite** [comment]
Please don't use `carc.in` or `play.crystal-lang.org`, as their contents could be lost (like in this case). Please reopen and include reproducible code pasted in the issue itself.

**Comment by Exilor** [comment]
Done, but I can't reopen issues.

**Comment by asterite** [comment]
@Exilor I was actually getting a segfault for that code. Aren't you too?

I fixed that, and now I get `LittleEndian` for the three cases.

**Comment by Exilor** [comment]
Nope, and I ran it in linux and osx. I got the output I wrote.

**Comment by Exilor** [comment]
Aha! It segfaults when *not* using `--release`, and I always run everything in release.
