### ISSUE TITLE
Regression: subclassing something that is defined later

### ISSUE THREAD

**Issue by BlaXpirit** [crystal-lang/crystal#3193]
```crystal
class Z < X
end

class X
end
```

```
Error in ./test.cr:1: undefined constant X

class Z < X
          ^
```

773eecab1d5cf8325a75afefe791fd9bbf565cce is the first bad commit

**Comment by Sija** [comment]
Possibly related to #3190?

**Comment by RX14** [comment]
@Sija no, it's not. #3190 isn't a bug it's a feature request.

**Comment by Sija** [comment]
@RX14 from what I understand it's rather a regression report—which btw seems to correct *(erroneous?)* behavior​ of being able to instantiate an alias:

```cr
Bytes.new(3) # => Slice[0, 0, 0]
```

**Comment by BlaXpirit** [comment]
@Sija `Bytes.new(3)` still works. You missed a `def`. I'm not sure what's going on there.

**Comment by Sija** [comment]
Yup, my bad. I got carried away by the fact you can instantiate an alias which could be an union... Sorry for the noise.

**Comment by asterite** [comment]
This **never** worked like this. A parent class must be defined before the subclass.

**Comment by BlaXpirit** [comment]
Alright, I oversimplified the example.

This used to work, but not anymore:

```crystal
class CC < Array(C)
end

class C
end
```

https://carc.in/#/r/186v

It does break existing code ([power_assert](https://github.com/rosylilly/power_assert.cr/blob/7f2d946078a5a678f12bc46c36f71f98ad10a153/src/power_assert.cr#L51) in particular) so maybe it should be noted somewhere.

**Comment by asterite** [comment]
Yes, generic type arguments, both for superclasses and included modules, are now solved the moment they are found.

On the good side, subclassing generics didn't work well before, but now it does.
