### ISSUE TITLE
Assignment to variables inside array literals causes "read before definition of"

### ISSUE THREAD

**Issue by oprypin** [crystal-lang/crystal#3195]
``` crystal
def fa
  {a = 1}
  p a  # works
end; fa

def fb
  {2 => b = 2}
  p b  # works
end; fb

def fc
  [c = 3]
  p c
end; fc
```

```
Error in line 14: instantiating 'fc()'

in line 13: read before definition of 'c'
```

**Comment by asterite** [comment]
I'm not sure how to fix it, and I'd probably prefer to give an error if an assignment is used inside a literal (it's confusing)

**Comment by BlaXpirit** [comment]
I don't see why literals should be special cased like this. I'd hate to see this error out.

Nothing wrong with this:
```crystal
objs = [(a = Obj.new("a")), (b = Obj.new("b"))]
```

**Comment by mverzilli** [comment]
That looks quite ugly. Disclaimer: I'm biased against embedding assignments in other expressions unless *extremely* necessary. 

```cr
a, b = objs = [1, 2]
pp a # => 1
pp b # => 2
pp objs # => [1, 2]
```

Isn't this much more clear? (And it works! :))
