### ISSUE TITLE
defining class methods in a block to have normal def + private ?

### ISSUE THREAD

**Issue by grosser** [crystal-lang/crystal#3201]
I'm looking for a nice way to define class methods ... does that exist ?

something like:

```
class Foo
  class << self
    def xyz
    end

    private

    def hidden
    end
  end
end
```

**Comment by Exilor** [comment]
Class methods to my knowledge can only be defined with `def self.xyz` or `def Foo.xyz`.
This is the closest I got to the behaviour that you want:
```crystal
class Foo
  def self.xyz
    Foo.hidden
  end

  protected def self.hidden
    "hidden!"
  end
end

Foo.xyz # => "hidden!"
Foo.hidden # => protected method 'hidden' called for Foo:Class
```
Maybe someone else can think of a better way to do it.

**Comment by RX14** [comment]
I personally think that the `self.foo` notation is good, in that it's immediately clear whether it's a class method or not. Honestly, I don't even like modules being able to extend self.

**Comment by grosser** [comment]
Good point ... it's definitely more obvious ... I like the cleanliness when
I do classes that only have static methods though ... making `class <<
self` work might not be simple and this is just a cosmetic feature, so I
get if it's low priority :)

**Comment by RX14** [comment]
@grosser if it's a class with only static methods, you could use a module instead and use `extend self` ([see docs](https://crystal-lang.org/docs/syntax_and_semantics/modules.html)). This means that every method on the module is static.

**Comment by jhass** [comment]
:-1: from me too, a bit repetition is fine in order to keep redundant language features down. Additionally the proposed syntax of `class << self` would be rather misleading if you're coming from Ruby and understand what "class methods" actually are over there and what that syntax there does (opening up an objects singleton class, which is not something Crystal has).

**Comment by grosser** [comment]
the `extend self` is a neat workaround ... and does not need any crazy rework ... maybe close this then ...
