### ISSUE TITLE
OptionParser: avoid having to define the argument twice

### ISSUE THREAD

**Issue by grosser** [crystal-lang/crystal#3204]
In ruby I can do this and get argument support for both `-c` and `--count`

`opts.on("-p", "--parallel COUNT", "Run in parallel") { |c| ... }`

in crystal using `-c 1`  does not pass an argument and has to be defined as `opts.on("-p COUNT", "--parallel COUNT", "Run in parallel") { |c| ... }` would be nice to avoid this redundancy

**Comment by asterite** [comment]
If someone wants to implement this, please go ahead :-)

**Comment by asterite** [comment]
Fixed by #3246
