### ISSUE TITLE
OptionParser: support casting

### ISSUE THREAD

**Issue by grosser** [crystal-lang/crystal#3205]
being able to do: `opts.on("-p", "--parallel COUNT", Int32, "Run in parallel") { |c| ... }` and have the argument automatically cast would be a nice addition and inline documentation for the program at the same time

atm

```
wrong number of arguments for 'OptionParser#on' (given 4, expected 2..3)
```

**Comment by asterite** [comment]
This is impossible to do, the yielded block argument is currently a String. If we do casting, it will become `String | Int32` and then you'll have to check this somehow. I don't think it's so hard to write `c.to_i` in the block, or `c.to_i? || raise "expected integer"`.

**Comment by asterite** [comment]
@RX14 In this:

```cr
foo do |x|

end
```

`x` will have a single type: the union of all the types that were yielded. It's not like each `yield` invokes a different instantiation of the block, there's only one block and all yields go through it.

**Comment by RX14** [comment]
@asterite like this: https://carc.in/#/r/187p

**Comment by asterite** [comment]
@RX14 I see. But OptionParser captures the block, and then it has to have a type defined. It works with non-captured blocks, though.

**Comment by straight-shoota** [comment]
Closing stale discussion. There has been no active interest in the last 4+ years.

It shure would be possible to implement, but I don't think it's that useful. Error handling is an imporant factor, but it's hard to configure for implicit parsing.

That being said, a proper feature proposal wouldn't necessarily be denied, but it doesn't make sense to keep this issue around unless there's some renewed and concrete interest.
