### ISSUE TITLE
crystal RPM package should declare dependency on "gcc"

### ISSUE THREAD

**Issue by amitsaha** [crystal-lang/crystal#3207]
As per title. For example, with no `gcc` installed:

```
$ crystal hello.cr 
--: cc: command not found
Error: execution of command failed with code: 127: `cc -o "/home/amit/.cache/crystal/crystal-run-hello.tmp" "${@}"  -rdynamic  -lpcre -lgc -lpthread /opt/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
```

I would be happy to contribute the fix, if someone points me to where the build scripts exist.

**Comment by ysbaddaden** [comment]
We depend on a linker but not necessarily gcc. It can be clang for example.

**Comment by jhass** [comment]
On Debian we could depend on build-essentials I guess, but there's no such thing for RPM based distros. Does anybody have a way to depend on "some linker/C compiler"? If not, I'd vote won't fix.

**Comment by ysbaddaden** [comment]
Debian provides the `c-compiler` virtual package.

**Comment by amitsaha** [comment]
@jhass I can try and find an equivalent package for RPM based distros. The output I pasted above seems to be invoking `cc`. But you say, depends on "some linker/C compiler" - could you explain a bit more?

**Comment by jhass** [comment]
`cc` is by convention "some C compiler", you (or your system) may either symlink it to `gcc`, `clang` or something else even. Additionally we do respect the `CC` environment variable.

**Comment by amitsaha** [comment]
What if we default to`gcc` and let the user overwride it by using `CC` to some other compiler?

**Comment by matiasgarciaisaia** [comment]
This should be followed up on crystal-lang/omnibus-crystal#14

**Comment by ysbaddaden** [comment]
Closing. This is a distribution issue, as per above message.
