### ISSUE TITLE
crystallang/crystal > 0.17.4 fails to load "spec"

### ISSUE THREAD

**Issue by grosser** [crystal-lang/crystal#3208]
works fine on image 0.17.4 and fails with xml2 error on latest

... found it while building https://github.com/grosser/ping_watcher ... 
but also fail nicely with the only thing being `xyz_spec.rb` with `require "spec"`

```
crystal spec
/usr/bin/ld: cannot find -lxml2
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "/root/.cache/crystal/crystal-run-spec.tmp" "${@}"  -rdynamic  -lxml2 -lpcre -lm -lgc -lpthread /opt/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
```

**Comment by RX14** [comment]
Crystal spec needs libxml2 installed (and linkable: use `libxml2-devel` on debian) to compile because it is now able to generate XML-formatted spec reports, which it needs libxml2 to generate.

**Comment by ysbaddaden** [comment]
It would be great to autodetect the presence of libraries are compile time, and only enable certain features when they're available.

**Comment by grosser** [comment]
Installing libxml2-dev fixes it!

That sounds good ... xml reports are not really a commonly used feature ...
alternatively ship it with the base crystal image ...

Additionally: could it print something helpful like "provided by the
libxml2-dev package on debian" to make it easier to fix ?

**Comment by asterite** [comment]
The latest dockerfile has libxml2 in it, so this should be fixed
