### ISSUE TITLE
Use `lib` instead of `libs` for require path

### ISSUE THREAD

**Issue by trans** [crystal-lang/crystal#321]
It would be better to use `lib` (singular) rather than `libs` (plural) for a few reasons.

1. The Unix standard name for such directory is `lib`. Probably every developer knows this.
2. The plural is superfluous, it doesn't really provide any addition semantic information. 
3. Plurals tend to be used inconsistently in projects, e.g. `doc` or `docs`, `tests` or `test`.

For these reasons it would be better to stick with more abbreviated singular `lib`.

**Comment by miketheman** [comment]
#triage 
This issue has moved from `draft` to `accepted` recently. The implementation appears to be underway in related issues.

**Comment by asterite** [comment]
Yes, this depends on #2788, which in turns depends on shards adopting this new logic
