### ISSUE TITLE
Cannot require socket/unix_socket only

### ISSUE THREAD

**Issue by Bew78LesellB** [crystal-lang/crystal#3211]
Hi, I tried this : 
```crystal
require "socket/unix_socket"

UNIXSocket.open "/my/path" do
  # do stuff
end
```
but I get : 
```
Error in /usr/lib/crystal/socket/unix_socket.cr:1: undefined constant Socket

class UNIXSocket < Socket
                   ^~~~~~
```
Of course, if I change the require to `require "socket"` it works..

I know the compiler doesn't include things that are not used, but I don't want to include everything each time I need only one thing..

Is it intentionnal ?

**Comment by ozra** [comment]
Perhaps dependencies should be specified better in some stdlib-files. "unix_socket.cr" should require "socket.cr" for instance, since it _does_ require it to work. But then "socket.cr" would be better off _in_ the "socket/"-directory. (I prefer such structuring of the files, amongst others because of here mentioned reason).

**Comment by Bew78LesellB** [comment]
I agree with you about the file structure..
Something like : 
```
socket.cr   # just a wrapper to require "socket/*"
socket/
 - socket.cr # The actual socket.cr file
 - unix_socket.cr
 - other socket files...
```
To protect against people that just wants to `require "socket"` and get everything..

**Comment by ysbaddaden** [comment]
> Is it intentional?

Yes. Sockets are so intertwined in C that it doesn't make much sense to only require the UNIX part over the IP part. Most of the logic is already in `socket.cr` anyway, and pulling a few more files has little to no impact (and won't be compiled in the resulting binary).

Ruby does the same by-the-way: you may only `require "socket"` which always pull in everything.

**Comment by Bew78LesellB** [comment]
Ok, it makes sense, thanks
