### ISSUE TITLE
Array#unshift with Module type

### ISSUE THREAD

**Issue by AlexWayfer** [crystal-lang/crystal#3217]
Hello!

If you are using `Array#unshift` with Integers, or Strings, everything is OK:

```crystal
arr = [] of String
arr << "Cat"
arr << "Dog"
arr.unshift "Bird"
```

But if you are using unshift with `Module`:

```crystal
module Animal
end

module Cat
  extend Animal
end

module Dog
  extend Animal
end

module Bird
  extend Animal
end

arr = [] of Animal
arr << Cat
arr << Dog
arr.unshift Bird
```

then…

```
in /usr/lib/crystal/array.cr:1088: no overload matches 'Pointer(Animal)#move_from' with types Pointer(Animal), Int32
Overloads are:
 - Pointer(T)#move_from(source : Pointer(NoReturn), count : Int)
 - Pointer(T)#move_from(source : Pointer(T), count : Int)

    (@buffer + index + 1).move_from(@buffer + index, size - index)
                          ^~~~~~~~~
```

I think it's because `Union` types, but not sure:

```crystal
arr = [Cat, Dog]
arr.unshift Bird
```

```
Error in ./test.cr:17: no overload matches 'Array(Cat:Module | Dog:Module)#unshift' with type Bird:Module
Overloads are:
 - Array(T)#unshift(obj : T)
 - Array(T)#unshift(*values : T)

arr.unshift Bird
    ^~~~~~~
```

**Comment by ozra** [comment]
You can a bit cumbersomely do it like this atm.

```crystal
module Animal
end

module Cat
  extend Animal
end

module Dog
  extend Animal
end

module Bird
  extend Animal
end

alias Animals = (Cat.class | Dog.class | Bird.class)

arr = [] of Animals
arr << Cat
arr << Dog
arr.unshift Bird
```
Since the modules are used as _values_ in the array, the array has to be typed with the type _of_ the modules - not the modules _as_ types.

**Comment by AlexWayfer** [comment]
@ozra Unfortunately, I can't: list of modules is dynamic and I don't want to list it manually (N files with modules).

**Comment by ozra** [comment]
Yes, I thought so, was worth a shot though :)

What do you really want to accomplish? There might be a better "idiomatic Crystal way".

**Comment by AlexWayfer** [comment]
@ozra I have set of files with one module per file («providers»), every module extended by `Provider` module (parent).

And I want to use `unshift` specifically now for some tests (how to move element in array to the first position?)

**Comment by ozra** [comment]
You kind of skipped describing the actual problem your trying to solve with your solution ;-)
Why aren't you using classes and nominal inheritance?

**Comment by AlexWayfer** [comment]
@ozra Oh, okay, modules from there: https://github.com/keplersj/update
I want to be sure that `brew` module will be first for some tests.
I think, Class is overhead for this project.

**Comment by ozra** [comment]
Just looking quickly. Considering what it does, a few bytes of possible overhead is to be considered non-existant. You could sneeze and create more overhead.

If using classes, the nominal inheritance will help with the list of types, and you just use class-methods. Since there's no ivars in the classes, and, well, you don't even have to instantiate them, it would be pretty much the same.

```crystal
class Animal
  def self.eat_and_shit
  end
end

class Cat < Animal
  def self.eat_and_shit
      p "Nom nom - Miau - Poop"
  end
end

class Dog < Animal
  def self.eat_and_shit
      p "Nom nom - Woof - Poop"
  end
end

class Bird < Animal
  def self.eat_and_shit
      p "Nom nom - Chirp - Poop"
  end
end

arr = [] of Animal.class
arr << Cat
arr << Dog
arr.unshift Bird

arr.each do |beast|
  beast.eat_and_shit
end
```
=> 
```
"Nom nom - Chirp - Poop"
"Nom nom - Miau - Poop"
"Nom nom - Woof - Poop"
```
Feels like a rather weird way of doing things though; wouldn't they be better off as instances anyway?

**Comment by AlexWayfer** [comment]
@ozra I don't think there is a need in Classes, because there will not be more than one instance on a single class for all runtime. I thought about this, and I'll think, thanks.

But the problem with array of Modules is still relevant

**Comment by asterite** [comment]
This works on master

**Comment by AlexWayfer** [comment]
@asterite Oh, sorry to bother you, I didn't check the master. Looking forward to the next version!
