### ISSUE TITLE
Nil assertion failed on grep

### ISSUE THREAD

**Issue by yann-stepienik-cko** [crystal-lang/crystal#3220]
array.grep /^value/ will crash compilator if value is not found

     if m["responses"].to_a.grep /^3/
       puts "lol"
     end

![screen shot 2016-08-31 at 18 15 39](https://cloud.githubusercontent.com/assets/17568523/18138922/f03207fa-6fa6-11e6-89dc-4659b500a01e.png)

**Comment by luislavena** [comment]
Hello @yann-stepienik-cko, can you provide a self-contained example code? We don't know what `m` or `responses` keys inside of it is.

Thank you.

**Comment by asterite** [comment]
@yann-stepienik-cko Unless you include reproducible code there's no way we can help you.

Please open another issue: there will be some steps you need to follow in order to submit a bug report. Thank you!
