### ISSUE TITLE
Concat array

### ISSUE THREAD

**Issue by yann-stepienik-cko** [crystal-lang/crystal#3221]
["200"].concat (m["responses"].to_a)

Will give this error : 

![screen shot 2016-08-31 at 18 23 21](https://cloud.githubusercontent.com/assets/17568523/18139141/042a3556-6fa8-11e6-84e2-56d321884451.png)

**Comment by RX14** [comment]
You want `YAML::Any#as_a` instead of `YAML::Any#to_a`.

`to_a` returns an array of `YAML::Any` results, so you can continue querying your nested datastructures. `as_a` returns the raw array, not wrapped with `YAML::Any`, so you can pass it to other things.

**Comment by yann-stepienik-cko** [comment]
Hello @RX14 !
AFAIK using to_a on on YAML::Any create an Array with the keys (YAML::Any is a hashmap not an array). 

![screen shot 2016-09-01 at 09 40 32](https://cloud.githubusercontent.com/assets/17568523/18161057/2db8209c-7028-11e6-99e5-ba81ac5450be.png)

![screen shot 2016-09-01 at 09 40 39](https://cloud.githubusercontent.com/assets/17568523/18161062/31dc7376-7028-11e6-89c4-47a1d6f12012.png)


And this is the inteded behavior. I was basically trying to grep the responses to test the existence of a /^2/ response

**Comment by RX14** [comment]
@yann-stepienik-cko you probably want `m["responses"].as_h.keys.map &.as(String)` then.

See https://carc.in/#/r/185k, the type of item in the array is different. (`YAML::Type` is a union type of all the different things YAML.parse can parse)

**Comment by yann-stepienik-cko** [comment]
It works ! Perfect thanks a lot !
