### ISSUE TITLE
Question: could anyone please explain the bsearch output?

### ISSUE THREAD

**Issue by luo820802** [crystal-lang/crystal#3222]
I try to `bsearch` an array:
```crystal
puts [1, 2, 3, 4, 5].bsearch { |x| x == 1 } # => Nil
puts [1, 2, 3, 4, 5].bsearch { |x| x == 2 } # => Nil
puts [1, 2, 3, 4, 5].bsearch { |x| x == 3 } # => 3
puts [1, 2, 3, 4, 5].bsearch { |x| x == 4 } # => Nil
puts [1, 2, 3, 4, 5].bsearch { |x| x == 5 } # => 5
```
But should the result be expected to be 1, 2, 3, 4, 5 respectively?

**Comment by asterite** [comment]
You can check the docs: https://crystal-lang.org/api/0.18.7/Array.html#bsearch%28%26block%29-instance-method

Basically you must use `x >= ...`.

Also check Ruby docs, section "find-minimum" mode: https://ruby-doc.org/core-2.2.0/Array.html#method-i-bsearch
