### ISSUE TITLE
NamedTuple.to_json isn't valid

### ISSUE THREAD

**Issue by tophe** [crystal-lang/crystal#3228]
hello,

NameTuple are not serialized to valid json.

`require "json"`
`nt = {score: 5, id: 2}`
`puts nt.to_json => "{score: 5, id: 2}"`

should be "{"score" : 5, "id" : 2}"

 ruby code
`require "json"`
`nt_ser =  "{score: 5, id: 2}"`
`JSON::parse(nt_ser)`

/home/Tophe/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/json/common.rb:155:in `parse': 757: unexpected token at '{score: 5, id: 2}' (JSON::ParserError)
	from /home/Tophe/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/json/common.rb:155:in `parse'
	from nx.rb:4:in `<main>'

correct :
`require "json"`
`nt_ser = '{"score" : 5, "id" : 2}'`
`p JSON::parse(nt_ser)`

**Comment by kostya** [comment]
https://play.crystal-lang.org/#/r/189s

**Comment by tophe** [comment]
sorry.
I made a mistake, with NamedTuple.inspect!
I close the issue
