### ISSUE TITLE
Possible bug with initialize method in records

### ISSUE THREAD

**Issue by puppetpies** [crystal-lang/crystal#3231]
If you define an initialize method in a record the compiler seems to want you to define your local variables as instance variables this was kind of unexpected behaviour.

```cr
record Person, first_name : String, last_name : String do

  def initialize

  end

  def full_name
    "#{first_name} #{last_name}"
  end
  
end

a = Person.new("Mike", "Nog")
```

Regards,

Brian Hood

**Comment by asterite** [comment]
Hi Brian,

The error I get from compiling that code is:

```
Error in ./foo.cr:2: this 'initialize' doesn't explicitly initialize instance variable '@first_name' of Person, rendering it nilable

The instance variable '@first_name' is initialized in other 'initialize' methods,
and by not initializing it here it's not clear if the variable is supposed
to be nilable or if this is a mistake.

To fix this error, either assign nil to it here:

  @first_name = nil

Or declare it as nilable outside at the type level:

  @first_name : (String)?

  def initialize
      ^~~~~~~~~~
```

Is there something not clear in the error message, something that we can improve?

You basically have an empty `initialize` method. Remove it and it works well:

```cr
record Person, first_name : String, last_name : String do
  def full_name
    "#{first_name} #{last_name}"
  end
end

a = Person.new("Mike", "Nog")
```

**Comment by puppetpies** [comment]
The question i would ask is why after creating an initiallize method i have then declare my local variables as instance variables this isn't the same for a class.

Is it because record Person is struct.

icr(0.18.6) > class Test
icr(0.18.6) >     def initialize
icr(0.18.6) >     
icr(0.18.6) >     end
icr(0.18.6) >     
icr(0.18.6) >     def t1
icr(0.18.6) >       a = 1
icr(0.18.6) >     end
icr(0.18.6) >     
icr(0.18.6) >     def t2
icr(0.18.6) >       a = 2
icr(0.18.6) >     end
icr(0.18.6) >     
icr(0.18.6) >   end
 => ok
icr(0.18.6) > a = Test.new
 => #<Test:0x13d1fd0>
icr(0.18.6) > a.t1
 => 1

**Comment by puppetpies** [comment]
I would like to understand the differences in this aspect as i am not sure what documentation to look at !

**Comment by asterite** [comment]
@puppetpies Your `record` defines a struct with two instance variables, and an `initialize` method that initializes them to the passed arguments. Your `Test` class has no instance vars, so there's nothing to initialize. Defining an extra `initialize` method on the record makes the compiler yell because you add a new possibility to create the object without initializing the variables.

**Comment by puppetpies** [comment]
Makes a lot of sense thank you !
