### ISSUE TITLE
Can't infer Nil instance variable

### ISSUE THREAD

**Issue by Exilor** [crystal-lang/crystal#3232]
Using 0.19
```crystal
class Foo
  def initialize(@bar : Nil)
  end
end

Foo.new(nil)
```
---
```crystal
class Foo
  def initialize(@bar = nil)
  end
end

Foo.new(nil)
```
---
```crystal
class Foo
  def initialize(@bar : Nil = nil)
  end
end

Foo.new(nil)
```
All these examples fail with `Can't infer the type of instance variable '@bar' of Foo`.

**Comment by asterite** [comment]
Yes, because just `nil` is of no use, so the compiler rejects it

**Comment by Exilor** [comment]
It's a useless instance variable to have on a class, sure, but I don't think the error is consistent with the type inference rules.
