### ISSUE TITLE
Apparent regression with generic types

### ISSUE THREAD

**Issue by Exilor** [crystal-lang/crystal#3235]
This used to work in 0.18.7 [(https://play.crystal-lang.org/#/r/18c6)](https://play.crystal-lang.org/#/r/18c6)
```crystal
abstract class Packet(T)
end

abstract class OutgoingPacket(T) < Packet(T)
end

class Client
end

class Connection(T)
  def initialize
    @packets = Array(OutgoingPacket(T)).new
  end
end

Connection(Client).new
```
With 0.19 it returns this error:
```
instance variable '@packets' of Connection(Client) must be 
Array(OutgoingPacket(T)), not Array(OutgoingPacket(Client))

     @packets = Array(OutgoingPacket(T)).new
     ^~~~~~~~
```
If it's of any help, the error doesn't happen in any of these scenarios:
- If OutgoingPacket is not abstract
- If Packet and OutgoingPacket are not generic
- If Packet and OutgoingPacket are structs

**Comment by asterite** [comment]
@Exilor Thanks!

We'll probably make next releases be 0.19.1, 0.19.2, etc., maybe each a week apart, mostly fixing regressions and improving things.
