### ISSUE TITLE
LLVM 3.9 support

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#3237]
[LLVM 3.9](http://lists.llvm.org/pipermail/llvm-announce/2016-September/000070.html) was released the other day, we should look into supporting it and not falling too much behind again.

**Comment by sdogruyol** [comment]
Is there any specific advantage that Crystal can utilize?

**Comment by RX14** [comment]
@sdogruyol being able to build on systems which only have that LLVM version installed.

**Comment by sdogruyol** [comment]
@RX14 anything else?

**Comment by jhass** [comment]
LLVM always includes improvements to the optimizer in new versions.

**Comment by asterite** [comment]
LLVM is also slower and slower each release. And we could manage to use LLVM 3.8 on omnibus, and I personally didn't notice any performance improvements over previous LLVM versions (I think they are mostly focusing on clang, maybe swift), so I wouldn't rush much about supporting newer LLVM versions for now.

**Comment by ysbaddaden** [comment]
From the release notes, it seems LLVM 3.9 notably improved and fixed the AARCH64, ARM and MIPS targets.

Supporting newer LLVM versions doesn't mean we have to rush and use it, but it greatly simplifies compiling Crystal on some platforms (eg. rolling linux releases) and avoids to have to compile LLVM manually, which is a painful experience...

**Comment by ozra** [comment]
There _might_ be LLVM-optimization steps that has no real benefit to Crystal programs and thus can be omitted in the codegen-chain, to keep compile time down. "Pure wishful thinking".

**Comment by ilovezfs** [comment]
What's the status here? We're looking to do the llvm 3.9 upgrade in homebrew/core and that will mean crystal-lang will cease to compile. At this point, crystal-lang is the only llvm dependent that does not have 3.9 compatibility in at least HEAD. I'd prefer not to have to boneyard it :(

**Comment by waj** [comment]
Thanks for the heads up @ilovezfs!
The problem with LLVM is that they seem not to follow the usual semantic versioning, specially regarding breaking changes. I guess this has been probably discussed already with other projects in Homebrew, right? Can you point me to one of those conversations so I don't start from scratch?

Some Linux distros comes with two or three versions of some packages like llvm. I think that would simplify things for Homebrew too. Is there any reason that couldn't be an option?

**Comment by ilovezfs** [comment]
We've discussed supporting multiple versions but currently core will only support the latest, which soon will be 3.9. It looks like you'll be grappling with LLVMAddTargetData and LLVMGetTargetMachineData being removed. Not sure if there any other problems.

**Comment by ysbaddaden** [comment]
> LLVMAddTargetData

This call has been doing nothing for a while. The data layout is now set once on `LLVMModule`.

I think we should get rid of the custom data layout definitions by-the-way, and retrieve the defaults from LLVM instead. Rust did that when they moved to LLVM 3.7 for example https://github.com/rust-lang/rust/pull/27076/commits/958d5638254958ea42652de7444b63f2e67e7fe3

> LLVMGetTargetMachineData

It's `LLVMGetDataLayoutStr` now (since LLVMGetDataLayout is deprecated).

> `LLVMAttribute` API (optional, but will break eventually):

It's deprecated in favor of `LLVMAttributeRef`.

**Comment by ysbaddaden** [comment]
Note that thee LLVM 3.9 features are appealing to the ARM port (not even speaking of AArch64):

- A large number of codegen fixes around ARMv8, DSP, correct sub-target support, relocations, EABI, EHABI, Windows on ARM, atomics.
- Initial support for MUSL (libc) on ARM.
- Support for Thumb1 targets in libunwind.
