### ISSUE TITLE
Using instance variables in class methods affects initialization

### ISSUE THREAD

**Issue by BlaXpirit** [crystal-lang/crystal#3239]
```crystal
class A
  def self.initialize
    @d = 5 
  end
  def test
    p @d
  end
end

A.new.test
```
```
0
```

What's wrong here:
- This compiles although it contains code that makes no sense (compilation error happens only if the method is being used anywhere)
- Setting this fake variable in a class method (which is never used) affects instances and allows `@d` to be uninitialized.
- Seems like `def self.initialize` has a slightly different effect than `self.anything_else`, which indicates that maybe somewhere in the compiler there has to be a check not only for the `initialize` name but also that it's not a class method.

Found by *puppetpies* in IRC.

**Comment by asterite** [comment]
Good catch, the compiler checks `initialize` methods to see if instance vars are initialized, but a check was missing to not do that on class methods (or basically methods that have a receiver)
