### ISSUE TITLE
Array.new(Json::PullParser) defined twice

### ISSUE THREAD

**Issue by Papierkorb** [crystal-lang/crystal#3242]
Hello,

`src/json/from_json.cr` defines `Array.new(Json::PullParser)` twice: https://github.com/crystal-lang/crystal/blob/master/src/json/from_json.cr#L101-L113

They differ in implementation, looks like the second one was slipped in by mistake as it does not return the new Array, but something else instead.

**Comment by Papierkorb** [comment]
Ah don't mind me, one yields the other doesn't.

**Comment by RX14** [comment]
It's still an incorrect definition, no `.new` method should return something which doesn't cast to the object it's defined on.

**Comment by asterite** [comment]
@RX14 that's mostly a convention, `new` can return anything, but I agree that maybe it should have another name.

**Comment by RX14** [comment]
@asterite yes, it's a convention - in my opinion a very important one - which this method breaks. That's why I said it's "incorrect".
