### ISSUE TITLE
Unable to run crystals spec/std/option_parser_spec.cr

### ISSUE THREAD

**Issue by grosser** [crystal-lang/crystal#3244]
using https://hub.docker.com/r/crystallang/crystal latest

```
crystal spec spec/std/option_parser_spec.cr
Error in ./spec/std/option_parser_spec.cr:188: instantiating 'OptionParser:Class#parse(Array(String))'

    OptionParser.parse(["-f", "-j"]) do |opts|
                 ^~~~~

in ./spec/std/option_parser_spec.cr:188: instantiating 'OptionParser:Class#parse(Array(String))'

    OptionParser.parse(["-f", "-j"]) do |opts|
                 ^~~~~

in ./spec/std/option_parser_spec.cr:190: undefined method 'invalid_option' for OptionParser

      opts.invalid_option do |flag|
           ^~~~~~~~~~~~~~
```

**Comment by grosser** [comment]
using `require "../../src/option_parser"` worked ... how about changing requires to make running the tests easier / intuitive ? ... alternatively prepend "../../src" to the load path ?

**Comment by RX14** [comment]
You need to use the `bin/crystal` script instead of crystal when working on the compiler.

**Comment by ysbaddaden** [comment]
Crystal is self hosted. When you simply run `crystal` this will use the globally installed crystal and thus it's own `src` folder for finding the core/stdlib files.

The `bin/crystal` script in the source code will change that by always using the `src` folder of the source code, despite using the global compiler; it also makes sure to use the compiled crystal binary when it's present; plus some more things.

Thus one must always use the `bin/crystal` script when working with the source code.

**Comment by grosser** [comment]
That makes sense ... not having the latest version would always break the build ...
... I was hoping there would be an easy way to make this more obvious ... like the first require being `require './spec/helper'` and then this has some checker logic to see if the crystal version is correct ... but not a big issue / I knew I did something wrong ... just not exactly what :)

**Comment by grosser** [comment]
let me close this, I don't think there is a nice/clean solution ... only solution I could think of is doing a require 'spec_helper' and check everything there, but even that could fail to compile and we'd end up in a similar spot ...
