### ISSUE TITLE
bug in the crystal compiler.

### ISSUE THREAD

**Issue by pleasuredroids** [crystal-lang/crystal#3249]
When I run crystal build --release, I get the following output.

fork: Cannot allocate memory
[5619870] ???
[7015189] ???
[20215748] ???
[20213860] ???
[19781354] ???
[5888247] ???
[5693571] main +19635
[139989332658224] __libc_start_main +240
[5593793] ???

With an error telling me I've found a bug in the compiler.
Here is the offending code:

``` crystal
require "./voidhawk/*"
require "kemal"

module Voidhawk

        get "/" do
                "all is well."
        end

        Kemal.config.port = 7026
        Kemal.run

end
```

I am running Crystal 0.19.0 [dcfb2b6](2016-09-02) on ubuntu 16.04 LTS.
Processor: AMD Phenom 8450 Triple-Core
OS type: 64 bit

I can run it with the command crystal run without any problems.
I hope this is enough information. Cheers.

**Comment by lbguilherme** [comment]
How much free RAM do you have on your machine and is swap enabled? Compiling in release mode do require more memory due to LLVM optimizations/linking.

**Comment by etemelkuran** [comment]
You should have at least 1 Gb of Free Ram.
Try LLVM 3.6 or later.

**Comment by asterite** [comment]
Closing. Please reopen and provide more info.
