### ISSUE TITLE
Guy's We are Taking Over Crystal

### ISSUE THREAD

**Issue by etemelkuran** [crystal-lang/crystal#3257]
I am decided to _fire_ Ary as known as asterite(green apple in fighting stance).

So, we decided to completely finish this lang as final version until **7 September**.

Thank you

Manas Founder and CEO and Head of Everything Biggest

**Comment by etemelkuran** [comment]
Also he won't be present anything at _any_ Ruby conferences.

**Comment by keplersj** [comment]
wtf? @bcardiff, what's up?
