### ISSUE TITLE
undefined symbol: event_new

### ISSUE THREAD

**Issue by jefurry** [crystal-lang/crystal#3264]
**hello.cr:**

    require "http/server"

    server = HTTP::Server.new(8080) do |context|
      context.response.content_type = "text/plain"
      context.response.print "Hello world! The time is #{Time.now}"
    end

    puts "Listening on http://0.0.0.0:8080"
    server.listen

**run command:**
> $ crystal run hello.cr

**output:**
> Listening on http://0.0.0.0:8080
/root/.cache/crystal/crystal-run-hello.tmp: symbol lookup error: /root/.cache/crystal/crystal-run-hello.tmp: undefined symbol: event_new

**os platform:**
> CentOS 6.5 (Final)

**Comment by asterite** [comment]
@jefurry How did you install Crystal?

**Comment by jefurry** [comment]
@asterite yes, has installed Crystal. needs upgrade libevent and make soft link under /lib64/
