### ISSUE TITLE
can't use N as a top-level type name: it's reserved for type arguments and free variables

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3269]
WHY?

```crystal
N = (ARGV[0]? || 10).to_i

N.times do
end
```

this code is pretty common for me

```
can't use N as a top-level type name: it's reserved for type arguments and free variables
```

**Comment by asterite** [comment]
https://github.com/crystal-lang/crystal/issues/3112

It's either that, or we let everything stop compiling when someone declares a type named `T` or `U`. Maybe the later is OK...

**Comment by kostya** [comment]
hm, maybe allow to constants? but not class names?

**Comment by asterite** [comment]
It's the same, when looking up `Foo`, `Foo` can be a class or a constant, there's no distinction and any will match.

**Comment by asterite** [comment]
I mean, if I define a constant `U` instead of `lib U` in the original issue, it breaks too.

**Comment by kostya** [comment]
actually this is also bad for examples, when i just want to create many: class A, class B

**Comment by asterite** [comment]
Yes, I know... the other solution is to change the language to this:

```cr
module Enumerable(T)
  def map(&block : T -> 'U)
  end
end
```

so that `'U` will be a free variable. Maybe we should do that...

**Comment by asterite** [comment]
@kostya I created https://github.com/crystal-lang/crystal/issues/3288 because, like you, I'm starting to strongly dislike this situation :-)
