### ISSUE TITLE
[macOS] kq_init: detected broken kqueue on macOS 10.12 Beta (16A313a)

### ISSUE THREAD

**Issue by david50407** [crystal-lang/crystal#3278]
Crystal 0.19.0 on macOS 10.12 Beta (16A313a) always warns `[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0` (tested with `crystal file.cr`, `crystal play`)

Crystal: `0.19.0 (installed from brew, with --with-llvm flag)`
LLVM: `3.8.1 (installed from brew)`
macOS: `10.12 Beta (16A313a)`

```
~ > 2.3.0p0 > 5.10.1 > $ > crystal play
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
Listening on http://localhost:8080
^C
~ > 2.3.0p0 > 5.10.1 > $ > crystal -v
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
Crystal 0.19.0 (2016-09-08)
~ > 2.3.0p0 > 5.10.1 > $ >
```

**Comment by asterite** [comment]
I don't think there's much we can do, might be a bug in kqueue in the next mac osx...

**Comment by RX14** [comment]
See Homebrew/homebrew-core#2869 which has a solution.

**Comment by DougEverly** [comment]
From the above-mentioned solution, this worked on 10.12 GM. llvm takes some time to compile.
```
brew uninstall llvm libevent crystal-lang
brew install libevent && brew install crystal-lang -v
```

**Comment by david50407** [comment]
@DougEverly Thanks!!! It works!
