### ISSUE TITLE
initialize/new methods don't show up in docs anymore

### ISSUE THREAD

**Issue by BlaXpirit** [crystal-lang/crystal#3281]
```crystal
class CC
  # asdf
  def initialize(a : Int32)
  end
end
```

This method used to be shown in generated API documentation, but not anymore.

**Comment by BlaXpirit** [comment]
The first bad commit could be any of:
b01fc5396d17b4a781f2c01db16c45977cecaa33
a49aef7f45268be005a045f4aec2233114e68686

**Comment by asterite** [comment]
@BlaXpirit Thanks! I didn't notice this at all...
