### ISSUE TITLE
Time.parse can't handle microseconds

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#3283]
We have `%L` for specifying milliseconds, but we can't handle microseconds. `%L` should support more digits and truncate the result for now, since we only have microsecond precision.

Seen [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/crystal-lang/2CEpIjw7diU/ip6UgxNUBQAJ)

**Comment by sdogruyol** [comment]
@asterite wow, i was just reading the issue and you already closed, so fast 😄
