### ISSUE TITLE
incomplete multibyte sequence (ArgumentError)

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3285]
```crystal
require "base64"
str = Base64.decode_string("w+Xt5fDg9uj/IPHq8Ojv8uAgMC4wMTI2IPHl6vPt5Ao=")
m = MemoryIO.new(str)
m.set_encoding("UTF-8", invalid: :skip)
p m.gets_to_end
```

crashed on OS X, in crystal Crystal 0.19.1 (2016-09-09) (but here it works: https://play.crystal-lang.org/#/r/192u)
```
incomplete multibyte sequence (ArgumentError)
[4424733042] *CallStack::unwind:Array(Pointer(Void)) +82
[4424732945] *CallStack#initialize:Array(Pointer(Void)) +17
[4424732904] *CallStack::new:CallStack +40
[4424705641] *raise<ArgumentError>:NoReturn +25
[4424806739] *IO::Decoder#read<MemoryIO>:(Int32 | Nil) +947
[4424799925] *MemoryIO@IO#gets_to_end:String +133
[4424799677] *MemoryIO#gets_to_end:String +45
[4424684099] __crystal_main +1203
[4424717832] main +40
```

**Comment by asterite** [comment]
Hmm, it's strange that `iconv` returns different values depending on the platform...

Who am I kidding? This is probably the norm when it's about supporting multiple platforms :-P

**Comment by kostya** [comment]
this fix actually add another bug, but on linux only, in the end of buffer lost 1 character

**Comment by kostya** [comment]
https://play.crystal-lang.org/#/r/19b3
on master this gives 4275

`дарил им игрушки` vs `дари им игрушки`

**Comment by kostya** [comment]
on osx bug also

**Comment by asterite** [comment]
Is there any way you can reduce it? With 4275 bytes I have no idea what I have to test...

**Comment by kostya** [comment]
ill try

**Comment by kostya** [comment]
```crystal
require "base64"
str = Base64.decode_string "77u/CgkJCgkJItCw0LHQstCz0LQi"
m = MemoryIO.new(str)
m.set_encoding("UTF-8", invalid: :skip)
res = m.gets_to_end
puts res.bytesize
```

also need change buffer size:
```
  # :nodoc:
  class Decoder
    BUFFER_SIZE     = 15
    OUT_BUFFER_SIZE = 15
```

output is: 19

if i change it back
```crystal
  when Errno::EILSEQ # , Errno::EINVAL
```

output is: 21

btw why i cannot change constants like in ruby?
```crystal
module IO
  # :nodoc:
  class Decoder
    BUFFER_SIZE     = 15
    OUT_BUFFER_SIZE = 15
  end
end
```

**Comment by kirbyfan64** [comment]
> change constants

Isn't that kind of an oxymoron? I mean, you're *changing* a *constant*...

**Comment by kostya** [comment]
ruby allow that, and it nice when need to hack some code like this

**Comment by ozra** [comment]
Dynamically changing and overriding, two different things.

**Comment by asterite** [comment]
@kostya I tried to understand what was wrong with the current code and *I think* this time I got it right. But of course if you find more incorrect cases let me know. At least now there are two specs with the cases that failed with the old fix and without the old fix :-)

**Comment by kostya** [comment]
hm, bug is still there :), but another, trying to reproduce

**Comment by kostya** [comment]
now bug with content size 2*buffer
https://play.crystal-lang.org/#/r/19m5
in master return 8974

**Comment by kostya** [comment]
small example
```crystal
require "base64"
str = Base64.decode_string "77u/CgkJCgkJItCw0LHQstCz0LQi77u/CgkJCgkJItCw0LHQstCz0LQi"
m = MemoryIO.new(str)
m.set_encoding("UTF-8", invalid: :skip)
res = m.gets_to_end
p res
puts res.bytesize
```

```
  # :nodoc:
  class Decoder
    BUFFER_SIZE     = 15
    OUT_BUFFER_SIZE = 15
```

```
crystal 10.cr
"﻿\n\t\t\n\t\t\"абвгд\"﻿\n\t\t\n\t\t\"абвгд\""
42

./bin/crystal 10.cr
"﻿\n\t\t\n\t\t\"абгд\"\n\t\t\n\t\t\"абвгд\""
37
```

**Comment by asterite** [comment]
@kostya I think I found the bug in my previous commit. Can you try again? :-)

**Comment by kostya** [comment]
thanks, seems all fixed.
