### ISSUE TITLE
Single Slash [/\//] RegExp broken inside macros

### ISSUE THREAD

**Issue by ziprandom** [crystal-lang/crystal#3286]
the latest release ```Crystal 0.19.1 [798b2e2] (2016-09-09)``` doesn't compile the Regexp 

```crystal
/\//
```

anymore. ```%r(/)``` works fine, as does ```/\/something/```: 

```crystal
pp /\//.match "/hallo"
```

leads to  

```
Error in line 1: macro didn't expand to a valid program, it expanded to:

================================================================================
--------------------------------------------------------------------------------
   1.   
   2.     
   3.     ::puts "#{ "(/\\\\//).match(\"/hallo\")" } # => #{ ((/\\//).match("/hallo")).inspect }"
   4.   
--------------------------------------------------------------------------------
Syntax error in expanded macro: pp:3: unexpected token: DELIMITER_START

    ::puts "#{ "(/\\\\//).match(\"/hallo\")" } # => #{ ((/\\//).match("/hallo")).inspect }"
```

Seems the regexp mutates to ```/\\//``` somewhere in the macro template expansion process.

**Comment by kirbyfan64** [comment]
Related to #3260?

**Comment by asterite** [comment]
Yes, seems a regression. They are only broken inside macros, though (`pp` is a macro)

**Comment by asterite** [comment]
Actually it seems the parsing of `/\\//` is wrong, and was wrong the whole time: https://play.crystal-lang.org/#/r/193c and https://play.crystal-lang.org/#/r/193d (compare that to [Ruby](https://carc.in/#/r/193e)). Also `Regex#to_s` and `Regex#inspect` seem to be wrong.
