### ISSUE TITLE
Incorrect Float64#to_s for 0.99999999...

### ISSUE THREAD

**Issue by luo820802** [crystal-lang/crystal#3292]
As title. Examples are as follows
```crystal
puts 1 - 1 * Complex.new(0, -1) # => 1.0 + 1.0i
puts 1 - 1 * Complex.new(6.123233995736766e-17, -1) # => 0.0 + 1.0i
```
The result of the second line should also be `1.0 + 1.0i`.

**Comment by asterite** [comment]
Seems to be a bug in `Float64#to_s`:

```cr
a = 1.0
b = 6.123233995736766e-17
c = a - b
puts c # => 0.0
```

**Comment by asterite** [comment]
Shorter:

```cr
0.99999999999999989.to_s # => "0.0"
```

**Comment by asterite** [comment]
I fixed this and according to the heuristic we use it prints "1.0". I guess this is acceptable as it's very close to 1.0. Ruby prints 1.0 for 0.99999999999999999, so it's debatable which one is "correct".
