### ISSUE TITLE
Instance assigned to constant inside class definition not initialized until/unless accessed

### ISSUE THREAD

**Issue by Exilor** [crystal-lang/crystal#3293]
Code
```crystal
class Foo
  FOOS = {} of Int32 => self

  def initialize(@id : Int32)
    FOOS[@id] = self
  end

  FOO_1 = Foo.new(1)
  FOO_2 = Foo.new(2)
end
```
Example 1
```crystal
Foo::FOOS # => {}
```
Example 2
```crystal
Foo::FOO_1 #=> #<Foo:0xfc6fd0 @id=1>
Foo::FOOS # => {1 => #<Foo:0xfc6fd0 @id=1>}
```
Example 3
```crystal
Foo::FOOS # => {1 => #<Foo:0xfc6fd0 @id=1>}
Foo::FOO_1 #=> #<Foo:0xfc6fd0 @id=1>
```

**Comment by asterite** [comment]
This is, at least now, expected behaviour. Constants are only initialized if they are used.

This for example lets us avoid initializing ARFG, STDIN, STDERR, and basically any constant if it's not used.

Is this something that we want to continue having? I don't know, maybe it's confusing. At least it's not similar to Ruby... On the other hand, Swift works like that too, so it means that at least another language thinks this is good.

**Comment by Exilor** [comment]
My use case is something like this:
```crystal
class Foo
  FOOS = {} of Int32 => self

  private def initialize(@id : Int32)
    FOOS[@id] = self
  end

  FOO_1 = Foo.new(1)
  FOO_2 = Foo.new(2)

  def self.[](id : Int32)
    FOOS[id]
  end
end

Foo[1] # missing hash key
```
If it's set in stone I'll leave a dirty workaround here in case somebody else encounters this issue.
```crystal
class Foo
  FOOS = {} of Int32 => self

  def initialize(@id : Int32)
    FOOS[@id] = self
  end

  FOO_1 = Foo.new(1)
  FOO_2 = Foo.new(2)

  def self.[](id : Int32)
    FOOS[id]
  end

  {% for constant in @type.constants %}
    {{constant}}
  {% end %}
end

Foo[1] # works
```

**Comment by Sija** [comment]
@Exilor If I'm not mistaken you could also use @@class variable for that.

**Comment by Exilor** [comment]
@Sija I also need access to Foo_1, Foo_2... directly by name (Foo::Foo_1), that's why they are constants :stuck_out_tongue_winking_eye:

**Comment by Sija** [comment]
@Exilor I don't understand exactly your use case - that is, why do you have to use constants for that? why not use for instance `Foo[:FOO1]`?

**Comment by Exilor** [comment]
@Sija I'm porting Java code that uses Java's enums (which can be of any type unlike Crystal's) and also has a class method to retrieve a specific enum instance by one of its fields. I have to use constants to access the instances by their name and that's surely faster than doing a hash lookup.

I have already circumvented this issue and my use case is solved, but if you're that interested... :smile:  here's the [Java original](https://bitbucket.org/l2jserver/l2j_server/src/2b3d5ecd30e8c60667cc6c79bcc8c3432f68503a/src/main/java/com/l2jserver/gameserver/model/base/ClassId.java?at=master&fileviewer=file-view-default) and my [Crystal port](https://gist.github.com/Exilor/20920c0ffaa0baafac766325249e1475).

**Comment by Sija** [comment]
@Exilor since you've found the solution I go find some grandma next to pedestrian crossing :P thanks for explanation tho', your Crystal port looks so much cleaner (Java is good as a coffee...)
