### ISSUE TITLE
running spec in release mode

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3296]
`crystal spec -p --release`
```
Invalid option: --release (OptionParser::InvalidOption)
```

**Comment by RX14** [comment]
All options to `crystal spec` are passed to the executable, not the compiler.

**Comment by kostya** [comment]
may be any way to solve this? because i find this is needed often

**Comment by asterite** [comment]
You can create a file `spec/all_spec.cr` that does `require "./**"` and then:

`crystal spec/all_spec.cr --release`

At least until we maybe fix this.

**Comment by kostya** [comment]
yes, but i want to run it with -p, or with -l in release, just as micro benchmark

**Comment by asterite** [comment]
Done!

To be honest, I also wanted this for some time :-)
