### ISSUE TITLE
from_json cannot find nested JSON objects

### ISSUE THREAD

**Issue by piedoom** [crystal-lang/crystal#3313]
I have the following string of JSON that I'm fetching from an API - 

```cr
json_string = %({
"response": {
  "user": {
    "name": "doomy",
    "likes": 37358,
    "following": 205,
    "default_post_format": "html"}
}})
```

My model looks like this - 

```cr
class Blog
  JSON.mapping({
    name: {type: String},
    likes: {type: Int32},
    following: {type: Int32},
    default_post_format: {type: String}
  })
end
```

The data I'm trying to extract lives in the `user` object.  However, when I try to create an object from the `.to_json` method, I get an error that "user" key does not exist.

```cr
Blog.from_json(json_string, root: "user")
# fails :(
```

However, when I do the same operation with the `response` JSON object, it can find the key properly (although still errors because the JSON mapping is incorrect.)

```cr
Blog.from_json(json_string, root: "response")
# works, but isn't really useful :(
```

I've been able to extract the data I want with the PullParser, like so - 

```cr
pull = JSON::PullParser.new(json_string)
pull.on_key("response") do
  pull.on_key("user") do
    return Tumblr::User.new(pull)
  end
end
```

However, this a rather large and un-DRY way of doing things.  

I'm not entirely sure if this behavior was intentional.  If it is, I'd like to ask the reasoning, as using a nested root object is very useful especially for websites with mediocre API design.

**Comment by kostya** [comment]
```crystal
class User
  JSON.mapping({
    name: {type: String},
    likes: {type: Int32},
    following: {type: Int32},
    default_post_format: {type: String}
  })
end
class Blog
  JSON.mapping({
    user: User
  })
end
```

**Comment by piedoom** [comment]
I thought that might work at first, but every single request in the API I'm using has a different type of object in the `response` JSON, so I'm not sure that could work (as crystal won't accept a generic object type in the mapping IIRC)

**Comment by asterite** [comment]
Maybe something like this:

```cr
require "json"

module Response
  def self.from_json(string_or_io, klass, field)
    pull = JSON::PullParser.new(string_or_io)
    pull.on_key("response") do
      pull.on_key(field) do
        return klass.new(pull)
      end
    end

    raise "Not found"
  end
end

class User
  JSON.mapping({
    name:                {type: String},
    likes:               {type: Int32},
    following:           {type: Int32},
    default_post_format: {type: String},
  })
end

json_string = %({
  "response": {
    "user": {
      "name": "doomy",
      "likes": 37358,
      "following": 205,
      "default_post_format": "html"}
  }})

p Response.from_json(json_string, User, "user")
```

The standard library can't provide a built-in solution for all the badly designed APIs out there (I mean, in an HTTP response, why would someone include a "response" field? 😕), but with a bit of code you can have some code that operates on an entire website's API.

I guess a single root is more common, at least that's what they use in ember, Rails and some other frameworks I know.

(Ideally the code above should use `on_key!`, but it seems to break the compiler, I'll investigate...)

**Comment by piedoom** [comment]
Thanks!  And yeah, it's not the best API design.  (Not only does it give a response object, but a meta object with the response status which seems pretty redundant).
