### ISSUE TITLE
Float64 literal without decimal loses suffix as macro arg

### ISSUE THREAD

**Issue by Exilor** [crystal-lang/crystal#3315]
It's a very minor issue but here it is:
```crystal
macro foo(arg)
  "{{arg}}"
end
foo 1.0_f32 # => "1.0_f32"
foo 1.0_f64 # => "1.0"
foo 1_f32 # => "1_f32"
foo 1_f64 # => "1"
```
I suppose it's because a float literal is Float64 by default and therefore the suffix should not normally be needed. But in this particular case it is needed, otherwise the compiler will think it's an int.

More concrete example:
```crystal
class Foo
  JSON.mapping(
    float: {type: Float64, default: 1_f64}
  )
end
Foo.from_json("{}") # => instance variable '@float' of Foo must be Float64, not (Float64 | Int32)
```

**Comment by asterite** [comment]
@Exilor Nice catch, thank you!
