### ISSUE TITLE
unable to get JSON representation of class

### ISSUE THREAD

**Issue by zolamk** [crystal-lang/crystal#3318]
i have this class and i was trying to get a JSON representation of the class

    require "json"

    class Person
      def initialize(name : String, age : Int32)
        @name = name
        @age = age
      end 
      def name
        @name
      end
      def age
        @age
      end
  
    end

    john = Person.new("John Doe", 18)

    puts john.to_json

**but this gives me the following error**

Error in line 19: instantiating 'Person#to_json()'

in /opt/crystal/src/json/to_json.cr:3: instantiating 'String:Class#build()'

    String.build do |str|
           ^~~~~

in /opt/crystal/src/string.cr:234: instantiating 'String::Builder:Class#build(Int32)'

    String::Builder.build(capacity) do |builder|
                    ^~~~~

in /opt/crystal/src/string.cr:234: instantiating 'String::Builder:Class#build(Int32)'

    String::Builder.build(capacity) do |builder|
                    ^~~~~

in /opt/crystal/src/json/to_json.cr:3: instantiating 'String:Class#build()'

    String.build do |str|
           ^~~~~

in /opt/crystal/src/json/to_json.cr:4: wrong number of arguments for 'Person#to_json' (given 1, expected 0)
Overloads are:
 - Object#to_json()

      to_json str
      ^~~~~~~

**Comment by RX14** [comment]
You need to use [`JSON.mapping`](https://crystal-lang.org/api/0.19.1/JSON.html#mapping%28properties%2Cstrict%3Dfalse%29-macro) in your `Person` class to use `to_json`.
