### ISSUE TITLE
Can't compile with --debug when IO::ByteFormat is memoized

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/crystal#3320]
I'm trying to add a `IO#byte_format` to change the endianness of an IO stream, in order to avoid repeating it all time when calling `IO#read_bytes`. This is working nicely... until I want to compile with `--debug` where LLVM fails with the following message:

```
Bug: called llvm_struct_type for (IO::ByteFormat::BigEndian:Module | IO::ByteFormat::LittleEndian:Module)
```

This is failing because `@byte_format` is an union of modules, for which we fail to generate a debug type (at least I guess).

To reproduce:

```crystal
class Foo
  def initialize(@byte_format : IO::ByteFormat)
  end
end
Foo.new(IO::ByteFormat::BigEndian)
```

Then run with `crystal run --debug foo.cr`

**Comment by ysbaddaden** [comment]
I can't even build Shards in debug mode too. I get the same kind of error, this time about IO:

> Bug: called llvm_struct_type for (IO::ARGF | IO::Buffered | IO::Delimited | IO::Hexdump | IO::Sized | MemoryIO | PointerIO | String::Builder)

I'm running Crystal 0.19.2 (official deb). Is this related to changes introduced in #2993 ?

**Comment by ysbaddaden** [comment]
After some digging, the issue is that `create_llvm_struct_type(MixedUnionType)` is unsupported, and it happens when trying to have an instance var that is a `NonGenericModuleType` (e.g., IO). By extension I would say that we can't generate debug information for `NonGenericModuleType`.

Yet, it includes `InstanceVarContainer`, so the `create_debug_type(InstanceVarContainer)` overload matches, when it shouldn't. Adding the following to `src/compiler/crystal/codegen/debug.cr` fixes the issue:

```crystal
    def create_debug_type(type : NonGenericModuleType)               
      puts "Unsupported type for debugging: #{type} (#{type.class})" 
    end                                                              
```

@asterite is my assumption correct?

**Comment by asterite** [comment]
@ysbaddaden Correct!

I initially though the bug report was that a "puts" was issued for this type, but because of your last comment I understood that it prevented compilation.

I also commented those `puts` there because they added nothing.

**Comment by ysbaddaden** [comment]
Oh no, there are so many unsupported types, that I wouldn't bother :D
