### ISSUE TITLE
Int64 and Int32 addition yields bug

### ISSUE THREAD

**Issue by luo820802** [crystal-lang/crystal#3322]
```crystal
x = -99999563583
y =   1215314725
puts x + y # => -98784248858
puts y + x # => -1050
```

**Comment by RX14** [comment]
This is not a bug, addition's result always takes the type of the left variable.

```cr
x = -99999563583
y =   1215314725
puts typeof(x) # => Int64
puts typeof(y) # => Int32
puts typeof(x + y) # => Int64
puts typeof(y + x) # => Int32
puts x + y # => -98784248858
puts y + x # => -1050
```

**Comment by luo820802** [comment]
Ruby gives the correct result. I know this is not a fair comparison. But that `x + y` and `y + x` yield the same result would be more favorable, as least for me.
Another point is that if `Int32 + Int64` is causing possible overflow and unexpected errors anyway, why not raise an error or inhibit the overloading of `Int32#+(Int64)`? Discrepant results of `x + y` and `y + x` make developing codes heavy on arithmetics error-prone.

**Comment by asterite** [comment]
@luo820802 You can find a long discussion about this in #567 , please continue the discussion there.

We can probably disallow an operation `x op y` if the size of `y` is bigger than that of `x`. Something like https://github.com/crystal-lang/crystal/issues/567#issuecomment-223764176
