### ISSUE TITLE
Variable scoping broken with block and begin/end with rescue clause

### ISSUE THREAD

**Issue by RX14** [crystal-lang/crystal#3324]
```cr
def foo
  yield
end

var = nil
begin
  foo do
    var = "foo"
    var, typeof(var) # => "foo", String
  end
rescue
end

var, typeof(var) # => nil, Nil (should be "foo", Union(String, Nil))
```
https://carc.in/#/r/1a2j

Removing the `rescue` from the top block makes it work. Removing the block (i.e. no `foo do`) fixes this.

**Comment by RX14** [comment]
Not sure of a workaround for this one... It's breaking my specs of a `File.open(&block)` style method where I test raising in it.

**Comment by asterite** [comment]
@RX14 Hey, thank for reporting this! At this rate we might squash all remaining hidden bugs before the next release :-P
