### ISSUE TITLE
TypeNode#instance_vars returning empty array

### ISSUE THREAD

**Issue by feifanzhou** [crystal-lang/crystal#3330]
``` crystal
class Foo
  macro inherited
    def self.fields
      {{ @type.instance_vars.map(&.name.stringify) }} of String
    end
  end
end

class Bar < Foo
  @field1 = "field1"
  @field2 = 5
end

p Bar.fields
```

I'd expect the print to output `["field1", "field2"]`, but instead it's an empty array … is this a bug or am I misunderstanding something about how macros work?

**Comment by Exilor** [comment]
You need to escape the macro:
```crystal
class Foo
  macro inherited
    def self.fields
      \{% if @type.instance.instance_vars.size > 0 %}
        \{{ @type.instance_vars.map(&.name.stringify) }}
      \{% else %}
        [] of String
      \{% end %}
    end
  end
end

class Bar < Foo
  @field1 = "field1"
  @field2 = 5
end

p Bar.fields # ["field1", "field2"]
```

**Comment by asterite** [comment]
@Exilor answer's is correct

The main "issue" here is that the `inherited` hook is executed as soon as the line `class Bar < Foo` is processed, and that happens before instance variables are defined and processed for `Bar`. Escaping with `\{{...}}` delays that bit of the macro execution until the method is invoked, and when that happens the type and all its instance vars are already defined.

**Comment by feifanzhou** [comment]
Ah, that makes sense. However, it looks like escaping doesn't fix (at least not in the playground, Crystal 0.19.2):

![screen shot 2016-09-20 at 07 55 12](https://cloud.githubusercontent.com/assets/3407996/18675582/abd6cfd0-7f07-11e6-85ae-5411bc3a7847.png)

**Comment by feifanzhou** [comment]
Ah, that makes sense. On Crystal 0.19.2, it works when I run via Terminal. However, it's still empty when I use the playground:

![screen shot 2016-09-20 at 08 01 41](https://cloud.githubusercontent.com/assets/3407996/18675842/8d977802-7f08-11e6-964d-86241dc46422.png)

Is this a playground bug or expected behavior?

**Comment by bcardiff** [comment]
It's a bug in the to_s of the escaped macros.

```
$ crystal play -v
Listening on http://localhost:8080
I, [2016-09-20 12:41:35 -0300 #37598]  INFO -- : /client WebSocket connected as session=1
I, [2016-09-20 12:41:35 -0300 #37598]  INFO -- : Request to run code (session=1, tag=1).
class Foo
  macro inherited
    def self.fields
      \{% if @type.instance.instance_vars.size > 0 %}
        \{{ @type.instance_vars.map(&.name.stringify) }}
      \{% else %}
        [] of String
      \{% end %}
    end
  end
end

class Bar < Foo
  @field1 = "field1"
  @field2 = 5
end

p Bar.fields
I, [2016-09-20 12:41:35 -0300 #37598]  INFO -- : Code instrumentation (session=1, tag=1).
class Foo
  macro inherited
    def self.fields
      {% if @type.instance.instance_vars.size > 0 %}
        {{ @type.instance_vars.map(&.name.stringify) }}
      {% else %}
        [] of String
      {% end %}
    end
    end
end
class Bar < Foo
  @field1 = "field1"
  @field2 = 5
end
_p.i(18) do
  p(Bar.fields)
end
```
