### ISSUE TITLE
crystal spec on unexpected file

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3336]
`crystal spec ffffffff3f43f24f`
crystal spec on unexisted file, still running all specs, may be should be error

**Comment by luislavena** [comment]
@kostya does `ffffffff3f43f24f` exists? Can you tell us a bit about the directory structure/files you used when invoked that file?

I've tried that command on an existing project and it worked without issues:

```
✔  ~/code/luislavena/radix [master|… 13] 
13:28 $ cat ffffffff3f43f24f
cat: ffffffff3f43f24f: No such file or directory
✘-1 ~/code/luislavena/radix [master|… 13] 
13:29 $ ccr spec ffffffff3f43f24f
Using compiled compiler at .build/crystal
..............................................

Finished in 897 microseconds
46 examples, 0 failures, 0 errors, 0 pending
✔  ~/code/luislavena/radix [master|… 13] 
13:29 $
```

**Comment by kostya** [comment]
ffffffff3f43f24f not exists, but run it in crystal dir

**Comment by RX14** [comment]
@kostya What exactly does `ffffffff3f43f24f` refer to then?

**Comment by kostya** [comment]
should crystal just write that path not exists?

**Comment by RX14** [comment]
@kostya Does crystal spec work if you remove that argument?

**Comment by luislavena** [comment]
> ffffffff3f43f24f not exists, but run it in crystal dir

Ok, so the issue is running `crystal spec` inside Crystal's source directory, correct?

From what I showed above, `crystal spec` will run the specs of the directory you're in, so basically is running Crystal's specs in your case.

I was not able to reproduce that (specs did compile and are running now).

Can you provide more context?

Thank you.

**Comment by asterite** [comment]
Yes, this is a known problem (at least to me), I started writing the reasons for this bad behaviour and realized how to solve it now (I didn't know how to solve it before)

**Comment by asterite** [comment]
Hm, actually, I don't know how to properly solve this.

The main issue is that if you run `crystal spec -x foo`, this should forward `-x foo` to the spec runner. The built-in spec runner is in `src/spec.cr`, but we also have minitest or spec2, and I'd like it to be possible to forward arguments.

But then we also have `crystal spec foo.cr` which ends up executing `crystal run foo.cr`. And we have `crystal spec foo.cr:2` which ends up executing `crystal run foo.cr --location foo.cr:2`.

So the problem with `crystal spec unknown` is that `unknown` doesn't look like a file and so it's forwarded to the spec runner, and the spec runner does nothing with that... Hmmm... maybe the spec runner should check that ARGV ends up empty after parsing options...

**Comment by asterite** [comment]
I fixed it by checking extra arguments in the spec runner (the built-in one). The only "problem" is that in the case of `crystal spec unknown` this will be equivalent to `crystal run spec/** unkonwn` and after compiling all of that you'll get the error, so it's not immediate. But at least now we get an error.
