### ISSUE TITLE
Comparing different types with Value#== can lead to logic errors in Runtime

### ISSUE THREAD

**Issue by ujifgc** [crystal-lang/crystal#3340]
Consider having [this code](https://play.crystal-lang.org/#/r/1aj4):

```ruby
chars = "ab cd"
puts chars[2] == 0x20 # => false, unexpected result
puts chars[2].ord == 0x20 # => true
```

I would expect compile-time error on this code as Crystal claims to be statically type-checked language.

Does the compiler have a mode to point out logic errors of this kind or do you consider removing `Value#==` from standard library?

I think comparable types should explicitly define comparison methods, and should not rely on `Value`, and should not silently return false on undefined extra-type comparison.

I know about slices and consider them an excellent tool for working with memory, the example just shows how essentially the same value can be wrongfully compared.

**Comment by asterite** [comment]
But we don't want this to stop compiling:

```cr
[1, 2, "hello"].find(2) # Error: can't compare Int32 with String
```

`==` should be able to compare any object against any object

In the case of Byte vs. Char you can use `===`

**Comment by asterite** [comment]
And in other statically typed languages it's the same (Java, C#)

**Comment by ujifgc** [comment]
I'm sorry, `[1, 2, "hello"].find(2)` does not compile in current Crystal. Can you provide another example?

**Comment by asterite** [comment]
Oh, sorry, I meant `index`:

```cr
[1, 2, "hello"].index(2) # => 1
```

**Comment by asterite** [comment]
@ujifgc To add a bit more: we'd really like to prevent these kind of bugs... but we'd also like to support the above scenario, so there's a tension. Maybe in the future we'll find a way to deal with both things in a better way.
