### ISSUE TITLE
Surprising error with generic abstract base class

### ISSUE THREAD

**Issue by rf-** [crystal-lang/crystal#3349]
When I try to compile the following code:

```
abstract class Base(Options)
  abstract def run(opts : Options)
end

class SpecificOptions
end

class Derived < Base(SpecificOptions)
  def run(opts : SpecificOptions)
  end
end

Derived.new.run(SpecificOptions.new)
```

I get this error:

```
Error in line 2: abstract `def Base(Options)#run(opts : Options)` must be implemented by Derived
```

I would have expected this to work, but maybe I'm misunderstanding something about the syntax?

**Comment by rf-** [comment]
@raydf pointed out on Gitter that removing the `abstract` keyword fixes the problem. I made a more fleshed-out example to prove to myself that polymorphism actually works correctly with the non-abstract version: https://play.crystal-lang.org/#/r/1aqj

**Comment by asterite** [comment]
Yes, right now the abstract check is pretty simple, it doesn't resolve generic type arguments, but the above should probably work. Workaround to make it work for now: remove the abstract method definition.

**Comment by Qwerp-Derp** [comment]
Bump to this issue: has there been any attempt to fix this so far?

**Comment by asterite** [comment]
@Qwerp-Derp No, and it won't happen anytime soon.

**Comment by straight-shoota** [comment]
Fixed. The original example compiles with 0.35.1.
