### ISSUE TITLE
Raise when rand() will overflow

### ISSUE THREAD

**Issue by RX14** [crystal-lang/crystal#3350]
The `rand()` function accepts any `Int` or `Int` range, yet it works with `Int32`s, this means that `rand()` can silently overflow and return well outside the requested range. This should be detected and raise.

**Comment by asterite** [comment]
@RX14 I tried to see which cases can overflow and they currently raise, so we'll need some concrete cases to tackle this.

**Comment by RX14** [comment]
@asterite A simple `rand(Int64::MAX)` produces a negative number: https://carc.in/#/r/1axk

**Comment by RX14** [comment]
Same issue with ranges. I encountered this while trying to create random time values in a timespan using `rand()`. I eventually had to convert the ticks value to `Float64` because `Int32::MAX` ticks is only about three and a half minutes!

**Comment by asterite** [comment]
Ah, interesting. I think that `rand(Int64::MAX)` should actually work and give a random Int64. In general, `rand(T)` should produce something of type `T`. It's a bit trickier with ranges, but we should do something similar.

**Comment by BlaXpirit** [comment]
I am working on improving the `Random` module. If I succeed, this will fix the mentioned errors.
