### ISSUE TITLE
Bug in round tripping YAML with "*"?

### ISSUE THREAD

**Issue by trans** [crystal-lang/crystal#3353]
```ruby
    require "yaml"

    class S
      YAML.mapping(
          foo: String
      )
    end

    s = "--- \nfoo: \"*\""
    y = YAML.parse(s)
    r = y.to_yaml
    puts r
    S.from_yaml(r)
```

**Comment by asterite** [comment]
Reduced:

```cr
require "yaml"

p "*".to_yaml # => "--- *"
```

This is a problem because we aren't using a YAML generator, it's manually written... we should probably start using one (I don't know if libyaml has one that we can use, or we could check the spec and if the rules are simple then do it ourselves)
