### ISSUE TITLE
WebSocket#run doesn't catch errors other than EOF

### ISSUE THREAD

**Issue by RX14** [crystal-lang/crystal#3355]
`WebSocket#run` currently catches an `IO::EOFError`, and calls the on_close handler. Should this happen with other exceptions where the socket is closed, for example connection reset by peer?

**Comment by asterite** [comment]
I'm not sure, I think we are missing an exception handler above that and an `on_error` or something like that. The websocket code is pretty young and misses a lot of things, probably also a way to use it without callbacks.

**Comment by RX14** [comment]
Maybe `on_close` should only be called when the "close" message type is received. This keeps it's function specific and well-defined. Other errors should propagate up and be handled by the `#run` caller.

**Comment by straight-shoota** [comment]
Resolved by #8975 et al
