### ISSUE TITLE
Heads up on probably unintentional code L2483

### ISSUE THREAD

**Issue by ozra** [crystal-lang/crystal#3363]
Reading through the code I stumbled upon:

https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/semantic/main_visitor.cr#L2371
https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/semantic/main_visitor.cr#L2483

I'll leave it to your expertise.

**Comment by drosehn** [comment]
It does seem like the second one should be:

``@exception_handler_vars = old_exception_handler_vars``

**Comment by asterite** [comment]
Good catch! Probably nothing bad was triggered so far because it's very uncommon to have nested exception handlers... I'll fix it any way.

**Comment by ozra** [comment]
Yeah, I figured the unlikelyness of it happening was why it sneaked away from being caught earlier, I just stumbled on it by random chance XD.
