### ISSUE TITLE
Format tool errors out in 0.19.2

### ISSUE THREAD

**Issue by ggiraldez** [crystal-lang/crystal#3365]
```sh
$ crystal version
Crystal 0.19.2 (2016-09-16)
```

Given the file `foo.cr`:

```crystal
# foo.cr
a = [1 as Int32]
```

Running `crystal tool format foo.cr` outputs:

Error:, couldn't format '/Users/ggiraldez/tmp/foo.cr', please report a bug including the contents of it: https://github.com/crystal-lang/crystal/issues

I'm aware that the `as` operator is deprecated, but I was expecting a syntax error instead.

Running the same command with version 0.18.6 changes the file to:

```crystal
# foo.cr
a = [1.as(Int32)]
```

**Comment by asterite** [comment]
@ggiraldez Good catch!

I actually bumped into this a few days ago and [fixed it](https://github.com/crystal-lang/crystal/commit/cef67da9bdaf86758e52f8cbf33079c77c605937), though I forgot to open an issue for it 😊

**Comment by asterite** [comment]
I'll use this bug report to track it as fixed 😄
