### ISSUE TITLE
Undefined Consonant YAML::Generator

### ISSUE THREAD

**Issue by jaitaiwan** [crystal-lang/crystal#3384]
Hey Guys

In 19.3 macOS sierra the following gives an undefined consonant error:

```crystal
require "yaml"
pp YAML::Generator
```

This previously worked in 19.1

**Comment by chaniks** [comment]
It seems the name has been changed to `YAML::Emitter` (20aa5d3 / #3353)
(And also some APIs.)

**Comment by jaitaiwan** [comment]
I'll close this as I was looking at the 18.7 documentation.
