### ISSUE TITLE
compiler fails to detect initialization of instance variables during scope of initializer

### ISSUE THREAD

**Issue by masukomi** [crystal-lang/crystal#3387]
## Problem
Incorrect claim of "instance variable .... not initialized in all of the 'initialize' methods, rendering it nilable"

Compiler is failing to recognize that one of the functions called in the initializer is guaranteed to set it.

## Expected behavior

The compiler should be able to figure out that the variable is being set within the _scope_ of the initializer, and not require us to _literally_ set the variable between the beginning and end lines of the `initialize` method.

## Actual Behavior

Error in ./lift.cr:3: instance variable '@speed' of Lift was not initialized in all of the 'initialize' methods, rendering it nilable

```
require "./building"
class Lift
	@speed : Int32

	getter :speed
	setter :speed

	def initialize()
		set_speed()
	end

	def set_speed
		@speed = 0
	end
end

```

**Comment by kirbyfan64** [comment]
Not a bug, and this has been "reported" like a zillion times already.

**Comment by kirbyfan64** [comment]
https://github.com/crystal-lang/crystal/pull/2443#issuecomment-216839163
https://github.com/crystal-lang/crystal/issues/3176
https://github.com/crystal-lang/crystal/issues/3334#issuecomment-248876364

**Comment by masukomi** [comment]
alas,  my search for a subset of the error didn't bring up the second one, which it really should have

That being said if it's "been 'reported' like a zillion times already" it suggests that Crystal is failing the principle of least surprise.

At the very least the compiler message can / should be changed to indicate that it is intentionally not bothering to check for initialization outside of the method.

**Comment by luislavena** [comment]
> At the very least the compiler message can / should be changed to indicate that it is intentionally not bothering to check for initialization outside of the method.

Do you have a suggestion about the wording for such message that will reduce these miscommunication issues?

Here is the error defined:

https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/semantic/type_declaration_processor.cr#L632-L638

Perhaps it can be expanded with more details or better wording.

Thank you.

**Comment by ozra** [comment]
Yes, a more informative message would be nice. If the compiler did a _post_-error look in to called methods to get a heuristic idea on what mistake or wrong assumption the coder might have done/had, to reduce the message to essentials - that would be incredibly nice.
