### ISSUE TITLE
how to convert string to byte 

### ISSUE THREAD

**Issue by etemelkuran** [crystal-lang/crystal#3393]
i read something with gets_to_end , i need to convert it back again after reading

**Comment by raydf** [comment]
Hi @etemelkuran:

This kind of questions should be asked in the crystal-lang group, stack-overflow or irc/gitter channel.

Responses from the API:

To bytes:
https://crystal-lang.org/api/master/String.html#bytes-instance-method

New string from bytes:
https://crystal-lang.org/api/master/String.html#new%28bytes%3ASlice%28UInt8%29%2Cencoding%3AString%2Cinvalid%3ASymbol%7CNil%3Dnil%29%3AString-class-method

**Comment by RX14** [comment]
@raydf is correct that this question is better for IRC, gitter or the mailing list.

You either want `String#bytes`, `String#to_slice`, or `MemoryIO.new(String)` to get it back to an `IO`, which is what you called `#gets_to_end` on.

**Comment by etemelkuran** [comment]
Ary said open every question to github.

**Comment by asterite** [comment]
I think it's OK to ask questions here, but other places are preferred.

To answer your question we'd need to know why you need to read the whole thing as an array of bytes. What will you do with those bytes?

**Comment by etemelkuran** [comment]
If Ary say so it's %100 right.

**Comment by raydf** [comment]
@etemelkuran, sorry if my opinion sounded harsh, it was not the intention, the other channels are more suitable for asking general question about the language usage and the std lib, and normally has a faster response time :).

**Comment by etemelkuran** [comment]
You still couldn't understand me.

**Comment by asterite** [comment]
Please don't feed the troll. Thank you :-)
