### ISSUE TITLE
`File#read` does not read files located in `/proc` Linux Virtual FileSystem

### ISSUE THREAD

**Issue by Val** [crystal-lang/crystal#3410]
From **TLDP** [Linux Filesystem Hierarchy: /proc](http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/proc.html)
> The most distinctive thing about files in this directory is the fact that all of them have a file size of 0, with the exception of kcore, mtrr and self.

With **Ruby**
```Ruby
puts File.read("/proc/self/cmdline").empty? # => false
````

With **Crystal**
```Crystal
if File.directory?("/proc/self")
  path = "/proc/self/cmdline"

  puts <<-EOF
  Given #{path.inspect} file path
  File#read empty?        # => #{File.read(path).size == 0}
  File.gets_to_end empty? # => #{File.open(path, &.gets_to_end).size == 0}
  EOF
end
```

Output:
```:
Given "/proc/self/cmdline" file path
File#read empty?        # => true
File.gets_to_end empty? # => false
```

**Comment by asterite** [comment]
@Val @RX14 I finally decided to fix it myself because it required a few extra changes. I use `String.build` with an initial capacity. For most cases this will work and avoid memory reallocations, though it's still just a bit slower than writing directly to a string's memory, but it's safer. The problem isn't just zero-sized files, but (I think) the file might change in the middle of the reading, so assuming a size isn't safe.

For a 110MB file, it previously took 0.0614590s to read it, now 0.0774090s, so I think it's acceptable (but there's still room for improvement)

**Comment by asterite** [comment]
For example one optimization that we always wanted to do with @waj is to improve `IO.copy`. Right now it allocates an intermediate buffer (on the stack), reads from an IO and writes to the other. But this could be optimized by avoiding this intermediate write. I just did a quick test and I could match the old performance, which is also Ruby's performance (this code is written in C so it's fast).

**Comment by RX14** [comment]
@asterite I'm confused, how can you avoid the intermediate buffer? Do you mean detecting if they're two file descriptors and using `sendfile`?

**Comment by asterite** [comment]
In this particular case, we could do:

```cr
String.build(size) do |io|
  io.read_from(file)
end
```

This will invoke `String::Builder#read_from`. `String::Builder` has a buffer where it reads, so it could read as much as possible from the `io` directly into its buffer. If there's more data it will resize the internal buffer and continue doing this until EOF. So no intermediate buffer is needed. This is the optimization I tried and it improved the performance.

Similarly, when copying data between buffered IOs, an implementation of `read_from` or `write_to` could directly write the internal buffer's content.

**Comment by RX14** [comment]
@asterite ah yes, that would make sense. Doing the most efficient IO copy between two generic IOs is difficult unless there's some sort of interface to discover if the receiver has an internal buffer, and if the slice you pass into `#read` is smaller than 8192 bytes, you're going to have another copy into `IO::Buffered`'s buffer, which slows it down more. Unfortunately I think this is going to have to be optimised on a case-by-case basis.
