### ISSUE TITLE
Unexpected problem with aliased NamedTuples with superclasses

### ISSUE THREAD

**Issue by zmalltalker** [crystal-lang/crystal#3433]
I'm having some problems which seem to indicate a bug in Crystal, but might just as well be due to my limited knowledge of Crystal. I haven't found any other issues reported, but at the same time there might be concepts in Crystal I don't yet fully understand. Please bear with me.

I'm using `NamedTuple`s to build a data structure inside my class, and one of the objects in the tuple is either `nil` or an `Array` of any instance of a subclass with a given superclass. Since this `NamedTuple` is used more than once, I've aliased it to my own type, like so:

```crystal
alias PetType = NamedTuple(name: String, pets: Array(Animal)|Nil)
```

Where `Animal` is the text book example of `Dog < Animal`, `Cat < Animal` just to make my point here.

Sending `pets: nil` works, as expected. But passing any instance of a subclass of `Animal` causes an error:

```
no overload matches 'add_pet' with type NamedTuple(name: String, pets: Array(Cat))
```

While passing an instance of `Animal` works. I tried making `Animal` abstract, but that doesn't make any difference.

A failing example of the problem:
```crystal
class Animal
end

class Dog < Animal
end

class Cat < Animal
end

alias PetType = NamedTuple(name: String, pets: Array(Animal)|Nil)

def add_pet(pets : PetType)
  p pets
end

add_pet({name: "Lassie", pets: [Cat.new]})
end
```

And by the way, thanks for Crystal. It's amazing!

**Comment by asterite** [comment]
`[Cat.new]` is an `Array(Cat)`, not an `Array(Animal)`. You can use: `[Cat.new] of Animal` to solve this. Please read [this](https://github.com/crystal-lang/crystal/issues/1297)

I'm **seriously** considering now to make the `of` part of an array/hash literal mandatory to prevent this kind of surprises...

**Comment by asterite** [comment]
@zmalltalker Actually, [this comment](https://github.com/crystal-lang/crystal/issues/2758#issuecomment-223835195) seems shorter and easier to understand why `[Cat.new]` doesn't work.

**Comment by zmalltalker** [comment]
Thanks a million, @asterite. I understand this a lot better now, and for me it would definitely helped me understand better if `of Animal` had been mandatory.

**Comment by asterite** [comment]
@zmalltalker I've been thinking about it and it might not solve all problems. For example:

```cr
names = ["Garfield", "Tom"]
some_call(names.map { |name| Cat.new(name) }) # Array(Cat)
```

The compiler infers the Array returned by `map` to be `Array(Cat)`, because all elements are `Cat`, and then you'll have the same problem as before. For this to work one has to "upcast" each value to `Animal`:

```cr
names = ["Garfield", "Tom"]
some_call(names.map { |name| Cat.new(name).as(Animal) }) # Array(Animal)
```

And here there aren't any array literals and there's still this problem/confusion, so forcing `of` on array literals won't solve much.
