### ISSUE TITLE
But when printing enum without members

### ISSUE THREAD

**Issue by azah** [crystal-lang/crystal#3447]
Crystal -v: Crystal 0.19.4 (2016-10-07)
### Playground Code

``` crystal
enum DiscordEnum : Int8 # happens regardless of member count
end

num = 1180678
numi8 = 1180678.to_i8
numi64 = 1180678.to_i64
numU64 = 1180678.to_u64
DiscordEnum.new(numi8)
```
### Bug

Syntax error in play:1: unexpected token: <

**Comment by asterite** [comment]
Reduced (outside the playground):

```cr
enum Foo
end

p Foo.new(1)
```

The problem is that `Enum#to_s` generates a `case` expression but it ends up being empty if the enum has no members. This is a minor bug because an enum without members isn't very useful :-)

**Comment by asterite** [comment]
In fact, maybe an `enum` without members should be a compile error, so for now I won't directly fix this but wait to take a decision on that.

**Comment by azah** [comment]
The original issue happens with members as well

**Comment by asterite** [comment]
@azah True, seems to happen with this:

```cr
enum Foo : Int8
  A
end

Foo.new(1_i8)
```

**Comment by sdogruyol** [comment]
Is this fixed? Can we close this @asterite ?

**Comment by asterite** [comment]
Not yet, there's still a bug that you can create an enum without members. This should be a compile error, I think.
