### ISSUE TITLE
Possibly incorrect error with from_value on Flags enums

### ISSUE THREAD

**Issue by RX14** [crystal-lang/crystal#3448]
Using a flags enum, every number smaller than the value of the largest member in the enum could have a value even if not explicitly listed. This works great with `.new`:

``` cr
@[Flags]
enum Foo
  A
  B
  C
end

Foo.new(3) # => A, B
```

However when using `.from_value`:

``` cr
Foo.from_value(3) # Unknown enum Foo value: 3 (Exception)
```

This could or could not be the correct behaviour depending on your reading of the docs, but it's a problem because `.from_json` uses this method. This makes decoding flags from JSON a bit harder because you have to define your own converter and validate that the flags are valid manually.

I propose that either `.from_value` is changed to handle flags enums better, or `.to_json` is changed to handle flags enums better.

**Comment by asterite** [comment]
Good catch!

`Foo.from_value(3)` should work, so this should be fixed.

**Comment by bmulvihill** [comment]
@asterite I was going to take a stab at this, should Foo.from_value(3) return the same as Foo.new(3)?

**Comment by asterite** [comment]
@bmulvihill Yes
