### ISSUE TITLE
Add checkbox support to markdown

### ISSUE THREAD

**Issue by watzon** [crystal-lang/crystal#3458]
It would be nice to have github style checkbox support in Crystal's markdown implementation. Has this been talked about?

**Comment by bcardiff** [comment]
Yes #2217 :-)

**Comment by ysbaddaden** [comment]
This was previously closed as not being Markdown, but a GitHub extension. See #2217.

**Comment by RX14** [comment]
This issue seems like a duplicate, and should be closed.
