### ISSUE TITLE
Add parsing to documentation for TODO statements

### ISSUE THREAD

**Issue by samueleaton** [crystal-lang/crystal#3460]
I would argue that if there is something still needed to be implemented in the class/method, then highlighting that in the docs would be a useful feature.

I propose to parse `TODO:` in any class or method documentation. 

This would turn, this: `<p>TODO: todo instructions here</p>`

...into this: `<p><span class="todo">TODO</span> todo instructions here</p>`.

The doc parser would also need to make sure that each TODO line is in its own paragraph.

**Example class**

``` ruby
# one of our beloved customers
#
# TODO: create methods for this class
#
class Customer

  # fetchs a customer from the database by id
  #
  # TODO: query db for customer  
  # TODO: return nil if customer not found with id  
  # TODO: return an instance of `Customer` if customer exists  
  def self.fetch(customer_id : String)
  end
end
```

**Before**

<img width="1280" alt="screen shot 2016-10-23 at 8 38 31 am" src="https://cloud.githubusercontent.com/assets/9119269/19627070/30f1984a-98fc-11e6-8de0-66345c58ffab.png">

**After**

<img width="1280" alt="screen shot 2016-10-23 at 10 18 17 am" src="https://cloud.githubusercontent.com/assets/9119269/19627693/2dcc5624-990a-11e6-893c-00aea40e0760.png">

It would makes TODOs standout without being too in-your-face. And as a bonus, it would let other developers know ways that they could contribute to your project.

If this feature enhances documentation and is worth pursuing, I would be fine doing the work to add this to the doc parser.

**Comment by BlaXpirit** [comment]
This is resolved/merged. Probably should be closed.
