### ISSUE TITLE
File.rename across different filesystems

### ISSUE THREAD

**Issue by International** [crystal-lang/crystal#3461]
- Make sure a similar issue doesn't exist yet: could not find an existing issue related to `File.rename` and different filesystems.
- **Include reproducible code**: I have an external harddrive, which has a FAT32 filesystem. My OS is El Capitan 10.11.6. I'm doing a `File.rename(old_filename, new_filename)`, and it raises the following error:
```
Error renaming file '/Volumes/NEW VOLUME/Backup/Windows Installation/Downloads/q.mpl' to 'q.srt': Cross-device link (Errno)
[4299772722] *CallStack::unwind:Array(Pointer(Void)) +82
[4299772625] *CallStack#initialize:Array(Pointer(Void)) +17
[4299772584] *CallStack::new:CallStack +40
[4299753337] *raise<Errno>:NoReturn +25
[4299854086] *File::rename<String, String>:Int32 +182
[4299750576] __crystal_main +1168
[4299764136] main +40

```
- Include Crystal compiler version (`crystal -v`) and OS: `Crystal 0.19.4 (2016-10-07)`, os: El Capitan 10.11.6

- I've noticed in the implementation of `File.rename` that it delegates to LibC, haven't worked with it before, so I'm not sure if there's something that could be done about it. Maybe we could specify in the docs, that the renaming might fail across different filesystems?

Thank you for the great work you're doing on Crystal!

**Comment by kirbyfan64** [comment]
Try passing the full path for the new file name.

**Comment by Sija** [comment]
@kirbyfan64 It's an OS issue which happens independently of languages/libraries (see https://github.com/andrewrk/node-mv for instance).

**Comment by International** [comment]
@kirbyfan64 @Sija passing a full path seems to work though ...

**Comment by kirbyfan64** [comment]
This is a side effect of how Unix systems handle moving/renaming. A move is synonymous to a rename. When you do `File.rename(a, b)`, it actually moves the file from `a` to `b`. In your case, it was trying to move the file to the current directory. However, Unix doesn't support moving files across hard drives.

**Comment by International** [comment]
should we close this bug then?
