### ISSUE TITLE
Add more symbols for bounds of %Q, and others

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3467]
in ruby this is ok:

``` ruby
%Q|a|
```

in crystal not compiled.

this is usefull when want for example write json as string: this is not readable `%Q[{"a":[1,2,3]}]` and `%Q{{"a":[1,2,3]}}`, but this ok: `%Q|{"a":[1,2,3]}|`

**Comment by asterite** [comment]
This was discussed in #1598

You could use `%Q<{"a":[1,2,3]}>`, though now I might have changed my mind about this subject and probably `|` looks/reads good for us to add it to the language.

**Comment by kostya** [comment]
also about inspecting strings. 
in specs for example it outputted like this, not readable:
```crystal
       expected: "{\"result\":0,\"something\":2}"
       got: "{\"result\":0,\"something\":1}"
```

this is better, imho:
```crystal
       expected: %q|{"result":0,"something":2}|
       got: %q|{"result":0,"something":1}|
```
