### ISSUE TITLE
Playground indents incorrectly with else clause

### ISSUE THREAD

**Issue by RX14** [crystal-lang/crystal#3470]
Using the code:
```cr
if true
else|
end
```

pressing return yields
```cr
if true
else
|
end
```
instead of
```cr
if true
else
  |
end
```

This happens no matter what is in the if or else clause, and also breaks indenting for everything below. I also experience this problem on `case` expressions with an `else`.

Crystal 0.19.4.

**Comment by asterite** [comment]
Indeed, this could be improved, but I'd open an issue in CodeMirror: https://codemirror.net/mode/crystal/index.html and https://github.com/codemirror/CodeMirror/blob/master/mode/crystal/crystal.js
