### ISSUE TITLE
Documentation empty line rule is a pain

### ISSUE THREAD

**Issue by trans** [crystal-lang/crystal#3479]
Reading about best practices for documenting code, I find:

```
# A unicorn is a **legendary animal** (see the `Legendary` module) that has been
# described since antiquity as a beast with a large, spiraling horn projecting
# from its forehead.
class Unicorn
end

# Bad: This is not attached to any class.

class Legendary
end
```

Problem is, I am porting a bunch of Ruby code for a particular project, and it really sucks to have go through it all just to make sure there are no empty lines there, and on all the methods too. Moreover, some people actually just prefer that style. In fact in my experience, people who do, tend to write cleaner code. I don't know why, but it often seems to be the case. Myself I am a bit of a waffler. On some projects I have and some I haven't. In any case, it's just a waste of programmer's time to make such a restriction.

Can the rule be changed so if there are _two empty lines_ then it won't apply?

**Comment by asterite** [comment]
But what if you want to put some comment between two declarations without that comment appearing in the docs? That's why the rule exists.

**Comment by trans** [comment]
Option 1: Extra line (very easy)

```ruby
# No show.


class Foo
   ...
end
```

Option 2: Add actual comment. It can be empty, but it probably shouldn't be anyway.

```ruby
# No show. 

#
class Foo
  ...
end
```

Option 3: Doc tool should have some type of hiding marker. What does Crystal doc support in this regard? Example might be,

```ruby
#/
# No show.
#\
class Foo
  ...
end
```

Another possibility in the future, if Crystal's doc tool supports tags, something like `@internal` might be of use too.

```ruby
# @internal No show. 

class Foo
  ...
end
```

[1]https://groups.google.com/forum/#!topic/yardoc/xOIfLTzLbB8

**Comment by RX14** [comment]
I think the current rule makes more visual and syntactic sense than either of the proposed alternatives. Parity with ruby isn't a good enough rule to change this, especially considering you're likely to have to rewrite all the doc formatting anyway because thats not particularly compatible either.

**Comment by samueleaton** [comment]
I think, even better, would be support for multiline comments, which would make things nicer for documenting.

```ruby
#=
Foo is a really cool guy.

You gotta be careful with Foo. If you're not careful, he'll get ya'.

I can put as much space in this comment as I dang feel like.


see?

=#
class Foo
  ...
end
```

**Comment by trans** [comment]
@RX14 If there wasn't an aspect of personal preference involved in this I would say you are right. But there is. So why should there be such a huge limitation for something that hardly ever happens -- how often do you really add comments that you don't want to show up in a place where they would otherwise show up?

**Comment by trans** [comment]
@samueleaton So you think Crystal should have a block comment form? Ironically even languages that do (e.g. `/* ... */`) tend to run `*`s all the way down. So maybe there is a reason not too do this -- i.e. a large code example, might get mistaken for actual code? I guess that was the original reason for it.

**Comment by samueleaton** [comment]
@trans Documentation is only only area where I'm really missing multiline comments. Its *super* convenient to not have to think about doing comments and just be able to do markdown. And if I've learned anything from studying UX  `convenience = more documentation` (n this case).

I see what you're saying about about mistaking something for code, but for 99.9% of users an editor should be graying that out.

**Comment by RX14** [comment]
@trans I've made misc implementation comments in the root of classes that shouldn't be in the API docs many time. For example: https://github.com/RX14/multipart.cr/blob/master/src/http/multipart/generator.cr#L27

**Comment by trans** [comment]
@RX14 But that wouldn't have caused a problem b/c `content_type` is documented.

**Comment by asterite** [comment]
Closing. Doc comments must be attached to declarations.
