### ISSUE TITLE
Can't make class method `new` private on parmetric class 

### ISSUE THREAD

**Issue by trans** [crystal-lang/crystal#3485]
This works:

```ruby
class Foo
  private def self.new
    super
  end
end
Foo.new  # error: private method
```

But not this:

```ruby
class Foo(T)
  private def self.new
    super
  end
end
Foo(String).new  # hmm... still works
```

Crystal's behavior here is odd. On one hand `new` seems to get used (non-parametric), on the other it seems to be by-passed (parametric) -- I can define subclasses on it and they don't go through the superclasses' new at all. 

On this topic, is there a way to make `new` private without redefining? 

Note, if you are wondering why I want to do this, it is because I want the superclass not to be instantiable, but it's subclasses' to be. Is there a better way to do this besides making `new` private, or am I doing the right thing?

**Comment by cjgajard** [comment]
From https://crystal-lang.org/docs/syntax_and_semantics/virtual_and_abstract_types.html
> Marking a class as abstract will also prevent us from creating an instance of it:
> ```
> Animal.new # Error: can't instantiate abstract class Animal
> ```

example:
```cr
abstract class Foo(T)
end

Foo(String).new
```
```
Error in ./file.cr:4: can't instantiate abstract generic class Foo(String)
```

**Comment by luislavena** [comment]
If you want to avoid a generic class to be instantiated, simply use `abstract` instead:

```crystal
abstract class Foo(T)
end

Foo(Int32).new # compile error: can't instantiate abstract generic class Foo(Int32)
```

And this works:

```crystal
abstract class Foo(T)
end

class Bar < Foo(Int32)
end

pp Bar.new
```

Docs:

- [Generics](https://crystal-lang.org/docs/syntax_and_semantics/generics.html)
- [Virtual and abstract types](https://crystal-lang.org/docs/syntax_and_semantics/virtual_and_abstract_types.html)

**Comment by asterite** [comment]
It was a bug, though for your particular use case I'd recommend to use an abstract class as a base type, as @luislavena suggested.

**Comment by trans** [comment]
Nice. Thanks.
