### ISSUE TITLE
Go Language like interfaces?

### ISSUE THREAD

**Issue by bjorndm** [crystal-lang/crystal#3489]
I'm currently in the process of trying to transforming an existing Ruby program into Crystal. It's going rather slowly, at one hand because Crystal does make me realize that I have some latent bugs in there, for example, values that could be nil where I thought they couldn't, but on the other hand because I have to add type annotations, more than I had expected to. 

One thing that irked me that I was forced to use abstract classes to specify a certain "interface", because I didn't want to have to use "responds_to?" with many methods. This made me think that Crystal currently seems to miss something important, and that is Go language style interfaces. Now, with abstract classes I have to disturb or introduce inheritance where I don't like it and I have to be explicit about it. With Go language style interfaces this wouldn't be necessary.

So I am wondering if something like Go language style interfaces is planned for Crystal or not and if the implementors of Crystal think such language feature would be desirable.

**Comment by samueleaton** [comment]
Can you leave a little snippet of an example in Go?

**Comment by bjorndm** [comment]
Well, what I do now in Crystal is something like: 

```
class Protocol
  abstract class Client
    abstract def protocol_send_data(data : Bytes)
    abstract def protocol_read_data(data : Bytes)
  end
  
  @client : Client
  def initialize(client)
    @client = client 
  end
end

class Client < Protocol::Client
  def protocol_send_data(data : Bytes)
  # ommitted 
  end 
  def protocol_read_data(data: Bytes)
  # omitted
  end 
end
```

In Go language  the inheritance wouldn't be needed:

```
interface Client {
    protocolSendData(data []byte)
    protocolReadData(data []byte)
}

struct Protocol {
  client Client
}

 
 fun (protocol Protocol) initialize(client Client) {
    protocol.client = client 
 }


struct Client {
}

func (client Client) protocolSendData(data : []byte) {
  // ommitted 
}


func (client Client) protocolReadData() (data : []byte) {
  // ommitted 
}

```
As you can see no inheritance or even indication that I am implementing it. Structural subtyping at it's finest. Arguably in this case I should use channels but I feel they're still a bit undercooked in Crystal, and secondly, I feel that abstract classes are the wrong solution or perhaps even the wrong language feature for this kind of problem.

**Comment by asterite** [comment]
You can use a module as an interface. It must be included explicitly, though. I like Go interfaces but I'm still not sure how would that work in Crystal (Go interfaces specify types, and they are invariant).

**Comment by luislavena** [comment]
@bjorndm as mentioned by @asterite, you can use modules as interfaces:

```crystal
class Protocol
  module ClientInterface
    abstract def protocol_send_data(data : Bytes)
    abstract def protocol_read_data(data : Bytes)
  end

  def initialize(@client : ClientInterface)
  end
end

class MyClient
  include Protocol::ClientInterface

  def protocol_send_data(data)
    # omitted
  end

  def protocol_read_data(data)
    # omitted
  end
end

Protocol.new(MyClient.new)
```

By using `abstract def` in the module, it forces the implementation but does not force you to use inheritance, see compile error of not implementing `protocol_read_data`:

```
Error in ./issue-3489.cr:4: abstract `def Protocol::ClientInterface#protocol_read_data(data : Bytes)` must be implemented by MyClient

    abstract def protocol_read_data(data : Bytes)
                 ^~~~~~~~~~~~~~~~~~
```

Hope that helps.

**Comment by bjorndm** [comment]
Hmm, OK I'll try it with a Module then, which is already better than a class for my purposes. 

As for interfaces in Crytal, could the type inferrer not see that a certain type has all the methods of a class or module, and treat it as compatible with it? Perhaps something like `Type~` to mean "anything that has the same methods as `Type` ?

However, to me, it seems that the core problem is that Crystal's type system is class based, not method signature based. However, to make duck typing possible and to achieve Smalltalk like or Ruby like OOP, the latter approach is necessary. Class based type systems only yields Simula-like or C++ like OOP which is a lot less less flexible. Of course, I admit that it would require a great deal of thought to

**Comment by cjgajard** [comment]
I like nominal typing more just because Ruby is nominal (I would like Crystal to stay as close as Ruby as possible) and I've never needed this because I end up using generics or modules ([see more](https://gist.github.com/cjgajard/863c382f0d3d968152a240efc3e35a66))

But if at last, generics will stop incremental compilation and structural typing solves that, I give +999999 to structural typing and interfaces (I hope that never happens tho)

**Comment by bjorndm** [comment]
Hmm, Yes, I see that I could also use generics. However, Ruby is nominally
typed in how you implement classes or modules, but structurally typed or
duck typed in how you use objects due to late binding. I haven't used
Crystal very long but to me it feels the latter is missing...

**Comment by kirbyfan64** [comment]
> As for interfaces in Crystal, could the type inferrer not see that a certain type has all the methods of a class or module

As great of an idea as that is, this would be extremely difficult to implement in type inference without having either an extremely slow compiler or an extremely memory-hungry compiler.

**Comment by citizen428** [comment]
@bjorndm I've coded up a little collection of macros for this purpose: https://github.com/citizen428/protocols 

Let me know if this is generally what you're looking for and if I can improve it in any way.

**Comment by bjorndm** [comment]
Well, it's not quite what I had in mind but I think now maybe I can get
what I want using a clever macro. Thanks for the link.

**Comment by bcardiff** [comment]
Let's assume that something like `#responds_to` but for modules: `#acts_as` is added and all methods of the module are allowed to be called in that section. The devil is in the details... the type of methods defined in crystal depends on it's usage.

For example there is no clear method type for the following:
```
def m(a)
  a.foo
end
```

It just depends on `typeof(a)` and `typeof(a.foo)`. Why does this matter? because when a module has no type restrictions in it's methods the intention of the author is unclear, so any deduction could be misleading."

If a module declares something like:

```
module M
  abstract def m(a)
end
```

1. when an `obj` could act as a `M`? Maybe when it has an instance method named `m` with a single argument
2. So what should the compiler do when with the result? Which type can be assigned to it?

```
def may_invoke_m(obj, a)
  if obj.acts_as?(M)
    res = obj.m(a) # which type is res? 
  end
end
```

Also, allowing behavior-like restrictions (`Type~`) might slow the compiler. I think that is the other main issue in this story as pointed out by @kirbyfan64 . 

If a duck-typing like program is wanted I think it should be enough to just code without type restrictions and let the compiler expand all the methods as needed. If it does not compile some cases are not handled. If you want so ensure certain kind of interface as a design of the system you will need structural typing.

**Comment by andrewhamon** [comment]
> If a duck-typing like program is wanted I think it should be enough to just code without type restrictions and let the compiler expand all the methods as needed.

@bcardiff This doesn't really work in the very common case where I want to inject a dependency and assign that to an instance variable, since type inference for instance variables has been severely limited (I think in an effort to reduce compile times). At some point I have to have an explicit dependency.

This breaks down when I wan't to mix objects I do control with objects I don't, since I can't just mix in or inherit from a common ancestor when I get a result back from the standard lib or from another library.

In the following example, all I really want is an object that responds to `publish`, but this code is invalid. I must add `@publisher : Redis | FakeRedis` to my class, and changing implementations or accepting other types becomes tedious.

```crystal
require "redis"

class FakeRedis
  def publish(channel, data)
    true
  end
end

class MyClass
  # Compiler error, @publisher won't be inferred
  def initialize(publisher)
    @publisher = publisher
  end

  def do_something(channel, data)
    @publisher.publish(channel, data)
  end
end

redis = Redis.new
fake_redis = FakeRedis.new

MyClass.new(redis).do_something("foo", "bar") # In Production
MyClass.new(fake_redis).do_something("foo", "bar") # In test
```

**Comment by Sija** [comment]
@andrewhamon You could create `RedisProtocol` module which would act as an interface, like below:
```cr
module RedisProtocol
  abstract def publish(channel, data)
end

class Redis
  include RedisProtocol
  # ...
end

class FakeRedis
  include RedisProtocol
  # ...
end

class MyClass
  @publisher : RedisProtocol
  # ...
end
```

**Comment by andrewhamon** [comment]
@Sija the problem with that is when I don't control some of the classes. In my case, Redis comes from a library. I really shouldn't have to reopen a class and include a module, I feel.

Fortunately, I found a workaround, making a generic class and using type parameter inference:

```crystal
require "redis"

class FakeRedis
  def publish(channel, data)
    true
  end
end

class MyClass(RedisT)
  # Compiler error, @publisher won't be inferred
  def initialize(publisher : RedisT)
    @publisher = publisher
  end

  def do_something(channel, data)
    @publisher.publish(channel, data)
  end
end

redis = Redis.new
fake_redis = FakeRedis.new

MyClass.new(redis).do_something("foo", "bar") # In Production
MyClass.new(fake_redis).do_something("foo", "bar") # In test
```

But this means that the types of those instances of `MyClass` are no longer a match, and this doesn't work:

```crystal
my_class_type_1 = MyClass.new(redis).do_something("foo", "bar") # In Production
my_class_type_2 = MyClass.new(fake_redis).do_something("foo", "bar") # In test

arr = Array(MyClass).new # Doesn't work, must use a more specific form of MyClass as the type param
```

**Comment by asterite** [comment]
@andrewhamon @Sija 's solution is perfectly fine, and that's the recommended way to define "interfaces" in Crystal: a module with abstract methods (and even defining these abstract methods is not strictly necessary). 

You say "I shouldn't have to reopen a class", but that's one thing that you can do in Crystal, and including an empty module to an existing type won't break anything in your code, and let you use that module as an interface. There's nothing dangerous or wrong about it.

Using generic is super complicated, please use a module :-)

**Comment by asterite** [comment]
I'm closing this, because the above works well.

**Comment by andrewhamon** [comment]
So while agree that including an empty interface in to a reopened class isn't dangerous, it encourages dangerous behavior (reopening a class).

You can monkey patch in Ruby as well, but it's usually discouraged.

Furthermore, I think the fact that the module workaround works means that an implementation of structural interfaces is possible. If **i** can always just reopen a class and include the right module before I use it, and the compiler still has to do the work of making sure the methods I use are defined, it seems like that could be mostly automated, in an almost macro like fashion.

**Comment by samueleaton** [comment]
I am able to use a module as an interface unless I'm trying to do an "array of interfaces".

For example, the following compiles just fine:

```ruby
class MyProtocol
  module MyInterface
  end

  def initialize(@client : MyInterface)
  end
end

class MyClient
  include MyProtocol::MyInterface
end

client = MyClient.new
protocol = MyProtocol.new client
```

But when I try to have an array of Interfaces/clients, it does NOT compile:

```ruby
class MyProtocol
  module MyInterface
  end

  def initialize(@clients : Array(MyInterface))
  end
end

class MyClient
  include MyProtocol::MyInterface
end

clients = [MyClient.new, MyClient.new]
protocol = MyProtocol.new clients

# Error:
# instance variable '@clients' of MyProtocol must be Array(MyProtocol::MyInterface), not Array(MyClient)
```

Is this a bug?

**Comment by luislavena** [comment]
> Is this a bug or is there a better way?

@samueleaton that seems to be the variance/covariance reported in several issues (quite common issue with the Type Inference)

Thing is that `typeof(clients)` is `Array(MyClient)` and not the expected `Array(MyProtocol::MyInterface)`.

Until now there is no better way :disappointed:

**Comment by asterite** [comment]
I might add this in the FAQ section.

Note that this is not an issue with the type inference algorithm, it's not something that can be improved or changed (maybe the error message can be improved). This same thing happens in many (every?) other languages with generic types, like [Java](http://stackoverflow.com/questions/28679658/java-passing-arraylist-of-object-to-function-that-uses-arraylist-of-interface) and [C#](http://stackoverflow.com/questions/2033912/c-sharp-variance-problem-assigning-listderived-as-listbase). It's a problem that appears when you add generics to a language, and either have interfaces or inheritance. I think that once you stumble upon this problem and understand it then there won't be many more type-related issues you'll face with Crystal (unless you also deal with recursive aliases, which are a bit hard to understand too)

**Comment by luislavena** [comment]
> Note that this is not an issue with the type inference algorithm

I meant is quite common issue that users bump while writing code that makes them wonder if this is a bug :smile:
