### ISSUE TITLE
Segmentation fault with is_a? and modules

### ISSUE THREAD

**Issue by zatherz** [crystal-lang/crystal#3490]
The following code crashes with a segmentation fault (signal 11):  
```crystal
class Super
end
module Mixin
end
class A < Super
  include Mixin
end
class B < Super
  include Mixin
end

a = A.new.as(Super)
if a.is_a? Mixin
  puts a.class
end
```

It is worth noting that this only happens inside `if is_a? Mixin`. If it's not inside that, it'll print the expected value (`A`).

Tested on Crystal 0.19.4+90 [7e1afdb] (2016-10-31).

**Comment by asterite** [comment]
@zatherz Hey, thank you for reducing this! I'm sure the original code was much bigger :-)

**Comment by zatherz** [comment]
Yeah, it happened in a basic Discord bot. I reduced it to a small size and then @RX14 helped me reduce it even further.
