### ISSUE TITLE
Compiler crashes infering type of generic ivar

### ISSUE THREAD

**Issue by cjgajard** [crystal-lang/crystal#3502]
"jokke" (from IRC) posted https://p.jreinert.com/m-Z4eWbH/ asking for help.

reduced to:
```cr
class Watchdog
  def initialize
    @channel = Channel.new(Float64)
  end
end

watchdog = Watchdog.new
```

That should raise `can't infer the type parameter T for the generic class Channel(T). Please provide it explicitly` error (as it does when is assign to a local var) instead of crashing.

**Comment by asterite** [comment]
Other codes that reproduce this:

```crystal
class A(T)
  alias B = C(T) 
  
  class C(T)
    @c : B = C.new
  end
end
```

and

```crystal
class A(T)
  alias B = A(T)

  class C
    @c : B
  end
end
```
