### ISSUE TITLE
`case var when Type end` does not restrict `var` to `Type`

### ISSUE THREAD

**Issue by Byron** [crystal-lang/crystal#3506]
### How to reproduce

```Crystal
class Any
  def initialize(@a : Array(String)|Nil = nil)
  end
  
  def do()
    case @a
    when Array(String)
      x = @a.as(Array(String)) # This works!
      x[0]
      @a[0] # Error - type of @a is still a union
    when Nil
      "nil"
    end
  end
end


a = Any.new ["hi"]
a.do
```

#### Expected

Within the `when Array(string)` case,`@a` is restricted to `Array(String)`. It should behave as advertised in [the documentation](https://crystal-lang.org/docs/syntax_and_semantics/case.html).

#### Observed
<img width="530" alt="screen shot 2016-11-06 at 08 11 35" src="https://cloud.githubusercontent.com/assets/63622/20035942/c9d82248-a3f8-11e6-9c61-6bf329b2a1c4.png">

### Meta

```
.crystal/bin/crystal --version
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
Crystal 0.19.4 [7f82f79] (2016-10-07)
```

**Comment by ysbaddaden** [comment]
As demonstrated in your example, type restriction only applies to local variables, not instance variables, because instance variables may be changed concurrently by another part of the code.

The following works, because we assign to a local variable first, which the compiler knows for sure wont be changed.

```crystal
case a = @a
when Array(String)
  a[0]
else
  nil
end
```

**Comment by Byron** [comment]
@ysbaddaden Thanks a lot for your swift support ! Do you think there is a way to make this clearer ? Maybe adding the example posted here to the docs would already help.

**Comment by Byron** [comment]
@ysbaddaden There seems to be a side-effect in closures. It appears that the compiler will 'loose' the previously assured type-information.

```Crystal
      case expected = @expected_content
      when Array(String)
        begin
          Zip.read path do |zf|
            paths = zf.entries.map {|e| e.path}
            # res = (paths - expected).empty?
          end
        rescue
          res = false
          @issue = Issue::FailedToParseZipFile
        end
```
I believe I can workaround this issue in a similar fashion though, it's just a bit intuitive - maybe the compiler error could be improved as well.

**Comment by Byron** [comment]
I am closing the issue as it is not an actual problem - it would just be good if I could be pointed at the documentation to learn about these cases.
