### ISSUE TITLE
Module validation failed: Stored value type does not match pointer operand type!

### ISSUE THREAD

**Issue by fridgerator** [crystal-lang/crystal#3512]
Sorry Im not able to minimize the problem and provide a smaller sample code to reproduce, I'm not entirely sure what the issue is.

The spec's aren't passing anymore in my repo [google_maps_api](https://github.com/fridgerator/google_maps_api).  The tests were all previously passing, I just updated `spec2` to use the master branch and now i'm getting an error that I'm unable to debug.

```
Module validation failed: Stored value type does not match pointer operand type!
  store %"GoogleMapsApi::Distance"* %187, i32** %198
 i32*
[4402562305] *raise<Exception>:NoReturn +81
[4402562092] *raise<String>:NoReturn +92
[4412022754] *LLVM::Module#verify:Nil +690
[4412018614] *Crystal::CodeGenVisitor#finish:Hash(String, LLVM::Module) +806
[4411264254] *Crystal::Compiler#codegen<Crystal::Program, Crystal::ASTNode+, Array(Crystal::Compiler::Source), String>:(Array(String) | Nil) +1246
[4416069925] *Crystal::Command#run_command<Bool>:Nil +277
[4403088229] *Crystal::Command#run:(Array(Crystal::ImplementationTrace) | Array(Crystal::Init::View+:Class) | Array(String) | Bool | Crystal::Compiler::Result | Hash(String, String) | IO::FileDescriptor | Nil) +4005
[4402691350] main +24278

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

This can be reproduced by checking out the repo and running `crystal spec`

**Comment by cjgajard** [comment]
The error happens at [this line]( https://github.com/fridgerator/google_maps_api/blob/master/src/google_maps_api/models/duration.cr#L2) trying to reuse the `JSON.mapping` of `Distance` by inheritance. Using `JSON.mapping` in `Duration` directly makes the project work:
```crystal
class Duration
  JSON.mapping({
    text:  String,
    value: Int32,
  })
end
```
I haven't found a reduced example that reproduces the crash though :disappointed:

**Comment by fridgerator** [comment]
Thanks @cjgajard  !

I have updated master with this fix.  I created a branch if anyone else would like to reproduce the error here - [crash branch](https://github.com/fridgerator/google_maps_api/tree/crash)

**Comment by asterite** [comment]
@fridgerator Thank you! I'll use that branch later to reproduce and fix the problem :-)

**Comment by asterite** [comment]
Reduced:

```cr
class Foo
end

class Bar < Foo
end

foo = 1 == 2 ? nil : Foo.new
x = foo.as(Foo)
```

**Comment by fridgerator** [comment]
👍

**Comment by silverweed** [comment]
Not sure if this change is already effective, but I'm using what I suppose it's the latest compiler release:

```
$ crystal version
Crystal 0.20.4 [d1f8c42] (2017-01-06)
```

and this code still crashes the compiler:

```crystal
struct Time
end

dict = {} of Symbol => { Time, ->Void }

dict.each { |x|
	x = { Time.new, x[1] }
}
```

Result:
```
Module validation failed: Stored value type does not match pointer operand type!
  store %"Tuple(Time, Proc(Nil))"* %113, %"Tuple(Time, Proc(Nil))"* %112
 %"Tuple(Time, Proc(Nil))" = type { %Time, %"->" }
0x55690e: ??? at ??
0x1349a7b: ??? at ??
0x12a3ddd: ??? at ??
0x5a74e3: ??? at ??
0x57b8cd: main at ??
0x7f172b4222b1: __libc_start_main at ??
0x556231: ??? at ??

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

**Comment by asterite** [comment]
@silverweed Thank for reporting this. When the compiler says "Module validation failed" it means there's something wrong in the codegen, but not necessarily that it is related to an existing bug. In fact, since this issue is closed it probably means there issue is something else. I reported it as #3907

**Comment by silverweed** [comment]
Yeah, I should've thought about opening a new issue rather than bumping this one, pardon me. 
Thing is, that was a fragment of code I had commented out several months ago with the note "uncomment when #3512 is fixed", so I posted here without thinking twice...but I honestly cannot remember why I had related this bug to that code in the first place.
