### ISSUE TITLE
Incorrect results of `Sting#index` and `String#rindex`.

### ISSUE THREAD

**Issue by arcage** [crystal-lang/crystal#3513]
Hi,

It seem the `Sting#index` and `String#rindex` return incorrect results, in case that searches an ascii `Char` in the string that includes multibyte letters.

My environment:
- Crystal 0.19.4 (2016-10-21)
- macOS sierra 10.12.1

Code:
```Crystal
# the both of the following results should be 3.
p "あいう_えお".index('_')
#=> nil
p "あいう_えお".rindex('_')
#=> nil
```

When `String#index` or `String#rindex` is called with the `search` argument that is an ascii Char, it delegates the process to `#to_slice`.

But, index of string is not equal with it of `string.to_slice` when that string includes multibyte letters.

This causes the incorrect results of `File.basename` and `File.extname`.

Those methods are calling `String#rindex` with `'.'` or `File::SEPARETOR`(`/` or `'\\'`).

```crystal
File.basename("日本語/日本語ファイル.txt")
#=> "ル.txt"　(it shoud be "日本語ファイル.txt")

File.extname("日本語/日本語ファイル.txt")
#=> "" (it should be ".txt")
```

**Comment by asterite** [comment]
@arcage Thank you, you are totally correct! I applied this optimization recently but it was wrong, I was missing checking that the string is also made of ascii characters.
