### ISSUE TITLE
Handling YAML tags

### ISSUE THREAD

**Issue by trans** [crystal-lang/crystal#3516]
Using YAML.parse and parse_all one has no access to the tags of a node. e.g.

```ruby
yaml = <<-HERE

---
- !foo This
- !bar That
HERE

rep = YAML.parse(yaml)
rep[0].yaml_tag #=> "!foo" ?
```

I was playing around with this and made a modified parser to store the tags using dedicated classes (`Scalar`, `Sequence` and `Mapping`), and that works fine if one doesn't need to go the final step and construct the native data types (at which point the tags are lost again). 

Today, I was also thinking maybe an `{object_id => tag}` table could be kept, which might suffice, but tags won't transfer when objects are copied. Maybe that's not a big deal though. I suppose to do this right, one would need a `Document` class to store the table and through which parsing would be done. e.g.

```ruby
doc = YAML::Document.new(yaml)
doc.data  #=> native data
doc.tag(doc.data[0])  #=> "!foo"
```

**Comment by kirbyfan64** [comment]
??
