### ISSUE TITLE
Process.new with error: true raises an uncatchable exception

### ISSUE THREAD

**Issue by kirbyfan64** [crystal-lang/crystal#3517]
```crystal
begin
  Process.run "nonexistent", error: true
rescue err
  puts 123
end
```

This won't actually catch the exception:

```
ryan@DevPC-LX ~/ptime $ crystal x.cr
execvp: No such file or directory (Errno)
[4367671] *CallStack::unwind:Array(Pointer(Void)) +87
[4367562] *CallStack#initialize:Array(Pointer(Void)) +10
[4367514] *CallStack::new:CallStack +42
[4340040] *raise<Errno>:NoReturn +24
[4513305] *Process::exec_internal<String, Array(Pointer(UInt8)), Nil, Bool, (Bool | IO::FileDescriptor), (Bool | IO::FileDescriptor), (Bool | IO::FileDescriptor), Nil>:Nil +281
[4510702] *Process#initialize<String, Nil, Nil, Bool, Bool, Bool, Bool, Bool, Nil>:Nil +1886
[4508801] *Process::new<String, Nil, Nil, Bool, Bool, Bool, Bool, Bool, Nil>:Process +209
[4508542] *Process::run:error<String, Bool>:Process::Status +110
[4336839] ???
[4350777] main +41
[140421849268037] __libc_start_main +245
[4335305] ???
[0] ???
ryan@DevPC-LX ~/ptime $ 
```

Just using something like `raise Errno.new 123` will work correctly.

**Comment by lbguilherme** [comment]
`Process.run` forks the current process. One side of the fork returns and the other side executes the give program. If this execution fails, there is currently no way to send this information to the other side of the process.

```cr
Process.run "nonexistent", error: true
puts "Hello"
```

This will print "Hello" just fine, because that stack trace printed there is about an exception that was never ever raised **in this process**. Here is the code that dominates it:

```cr
    @pid = Process.fork_internal(run_hooks: false) do
      begin
        Process.exec_internal(
          command,
          argv,
          env,
          clear_env,
          fork_input || input,
          fork_output || output,
          fork_error || error,
          chdir
        )
      rescue ex
        ex.inspect_with_backtrace STDERR
      ensure
        LibC._exit 127
      end
    end
```

**Comment by lbguilherme** [comment]
There is a nice solution to this:

> This is a classic problem with a very elegant solution. Before forking, create a `pipe` in the parent. After `fork`, the parent should close the writing end of the pipe, and block attempting to `read` from the reading end. The child should close the reading end and set the close-on-exec flag, using `fcntl`, for the writing end.

> Now, if the child calls `execvp` successfully, the writing end of the pipe will be closed with no data, and  `read` in the parent will return 0. If `execvp` fails in the child, `write` the error code to the pipe, and `read` in the parent will return nonzero, having read the error code for the parent to handle.

(http://stackoverflow.com/a/13710144/517503)

I'll try to implement it later.

**Comment by ysbaddaden** [comment]
A process returning a non zero status code wont generate an exception. The `error` arg means to collect the STDERR output of the process.

You thus have to check the status of run process. Out of memory is say it's something like:

```crystal
status = Process.run("foo")
if status.success?
  ...
else
  ...
end
```
