### ISSUE TITLE
Emitting YAML with tags

### ISSUE THREAD

**Issue by trans** [crystal-lang/crystal#3522]
I decided to see if I could add tag support to the emitter myself. Turns out that it wasn't too difficult. Simply had to add an optional argument for the tag in the right places. But finishing up I ran into an API design question that needs address, and I am not sure the best answer.

When someone creates their own class and wants it to support `#to_yaml`, they can define their own method, e.g.

```ruby
class MyClass
  def initialize(@value : String)
  end
  def to_yaml
     @value.to_yaml
  end
end
```

Now how does one add tags? This way:

```ruby
class MyClass
  def initialize(@value : String)
  end
  def to_yaml
     @value.to_yaml("!myclass")
  end
end
```

That's what my changes allow. But notice there is a subtle issue. If another class wants to use `MyClass` as instance data and use it to emit YAML they'd have a problem.

```ruby
class YourClass
  @value : MyClass
  def initialize(value : String)
     @value = MyClass.new(value)
  end
  def to_yaml
     @value.to_yaml("!yourclass")  # argument error!
  end
end
```

To fix this, in order to provide proper support, all `#to_yaml` methods **must** handle an optional tag argument:

```ruby
def to_yaml(tag : String? = nil)
  @value.to_yaml(tag || "!custom")
end
```

Perhaps it's not a big deal, but having to know to do that kind of sucks. 

The alternative is to support two additional methods, `#yaml_tag` and `#as_yaml` (not sure about the name of this later one).

```ruby
class Object
  def to_yaml
    as_yaml.to_yaml(yaml_tag)
  end
  def yaml_tag
    nil  # default tag is nil
  end
end
```

Then the original example can simply be:

```ruby
class MyClass
  def initialize(@value : String)
  end
  def as_yaml
     @value
  end
  def yaml_tag
    "!myclass"
  end
end
```

Which is better? Or is there a better third alternative?

**Comment by asterite** [comment]
We should probably rethink how `#to_yaml` works. Right now you have to define `#to_yaml`, but we probably need it to be something like `#to_yaml(emitter)` so you can add tags and so on.

**Comment by trans** [comment]
Maybe there doesn't need to be `#to_yaml` at all. Instead something like `YAML::Writer.new(object).to_s`. That's basically how Java does it, and then you can adjust it with custom tags and so on.

Also, have you considered generic serialization methods for classes? Basically, instead of the `as_yaml` I mention, use a generic name like `#serialization`, or something like that, and there would be a class method `from_serialization`. Then any serialization format could use those methods, JSON, YAML, Marshall, etc.

**Comment by trans** [comment]
> but we probably need it to be something like #to_yaml(emitter) so you can add tags and so on. 

There are already methods for `to_yaml(emitter)`, that's how it works, so are you suggesting we'd have to create our own Emitter subclasses to adjust the tags?

**Comment by asterite** [comment]
Oh, sorry, I forgot about that. It means that it's designed well, then :-)

Just override `#to_yaml(emitter)` then, but know that there are some missing methods/parameters in the YAML::Emitter type (for example, the tag is hardcoded to be nil right now)
