### ISSUE TITLE
Cannot resolved requirements with a compiler compiled by myself

### ISSUE THREAD

**Issue by tbrand** [crystal-lang/crystal#3535]
Hi all,

I've compiled crystal by myself as usual way.
When I used it in a basic way like as follows, the compiler cannot resolve requirements.
```
$ ../crystal/.build/crystal deps
$ ../crystal/.build/crystal build ./src/web-sample.cr
=> Error in ./src/web-sample.cr:2: while requiring "redis": can't find file 'redis' relative to 'somepath/web-sample/src'
```
'web-sample' is a project that using a 'redis' shard.
When I used original crystal command installed by Homebrew, no problem was occured.
```
$ crystal build ./src/web-sample.cr
=> Success
```

Is this a bug or my problem?
I just through a PATH to llvm and make it to compile.

Best

**Comment by asterite** [comment]
You need to use the bin/crystal wrapper, not .build/crystal

**Comment by tbrand** [comment]
Understood, thanks for it.
