### ISSUE TITLE
Running into some kind of limit using JSON.mapping() and from_json()

### ISSUE THREAD

**Issue by drosehn** [crystal-lang/crystal#3545]
I use a program which has an option to print out all of its internal data as JSON objects, and I thought I'd use crystal to process that output.  I took advantage of the `JSON.mapping()` macro and the `.from_json` method.  This worked quite well, and I made progress much faster than I expected to.  I can **almost** process the entire tree of JSON objects, and then I run into some sort of bug when adding the very last field I need to define.

The data is sensitive info, so I can't post that.  I wouldn't even want to post all of the code that I wrote, because it might be giving away some information that I'd rather keep private.  I know I could trim the full example down to a nice small safe program, but that would take more time.

I expect that I'm just running into some limit somewhere, and the issue will be obvious even without all the details.  So here is bits-and-pieces of a bug report.  If this is not enough information, I will continue to shrink the program and obfuscate the data, and provide a complete program which has no sensitive information in it.  So here's a few excerpts:

```cr
# uname -a
Darwin ...hostname... 14.5.0 Darwin Kernel Version 14.5.0: Sun Sep 25 22:07:15 PDT 2016; root:xnu-2782.50.9~1/RELEASE_X86_64 x86_64
# crystal --version
Crystal 0.19.4 (2016-10-24)
```

**Incomplete** program:
```cr
require "json"

PRINT_JSONerr_CALLBACKs = true
PRINT_JSONerr_INSPECT = false

# -------+---------+---------+-------- +
class JSON_Level_3a
    JSON.mapping({
        a: JSON_Level_4a | Nil,
        k: String,
        n: String,
        t: String,
        #   Runnning into a problem with the "v" field.  It *should*
        #   be defined as 'String | Nil', but that runs into a weird
        #   run-time exception when processing JSON objects which do
        #   not have the field.
        #   And if it is defined as 'String', we get an error on those
        #   same JSON objects (and that error makes perfect sense).
        #
        #   So we must comment out the entry for "v", and that in turn
        #   means that 'strict' must have the value 'false' for this
        #   'JSON_Level_3a' class.
        v: String | Nil,
     }, strict: true 
    )
end

# ... Several classes which define multiple levels
# ... of JSON objects, not included here.
#... They are all setup as:
#
#   JSON.mapping({
#       ...fields...
#    }, strict: true
#   )


# -------+---------+---------+-------- +
#   My simple main program.
#
linecnt_l = 0

bad_recs = [
   #  ... three records, not included here...
]

bad_recs.each { |aline|
    linecnt_l += 1
    begin
        pentry = JSON_Level0.from_json(aline)
    rescue js_err : JSON::ParseException
        printf  "#|%4d| Error: %s\n", linecnt_l, js_err.message
        printf "#|----|    on: len=%d ", aline.size
        if PRINT_JSONerr_INSPECT
            printf "\n      %s\n", aline.inspect
        else
            printf "%s\n", aline
        end
        if PRINT_JSONerr_CALLBACKs
            STDERR.printf "#|%s|\n", "-" * 64
            js_err.inspect_with_backtrace(STDERR)
            STDERR.printf "#|%s|\n", "-" * 64
        end
        next
    end
}

exit 0
```

My program prints out backtraces such as:
```cr
#|----------------------------------------------------------------|
#|   3| Error: couldn't parse (String | Nil) from 1359608400 at 0:0
#|----|    on: len=1769   {...data not included here...}
#|----------------------------------------------------------------|
couldn't parse (String | Nil) from 1359608400 at 0:0 (JSON::ParseException)
[4533233506] *CallStack::unwind:Array(Pointer(Void)) +82
[4533233409] *CallStack#initialize:Array(Pointer(Void)) +17
[4533233368] *CallStack::new:CallStack +40
[4533213385] *raise<JSON::ParseException>:NoReturn +25
[4533422637] *(String | Nil)@Union(T)::new<JSON::PullParser>:(String | Nil) +301
[4533440775] *JSON_Level_3a#initialize<JSON::PullParser>:(String | Nil) +503
[4533440249] *JSON_Level_3a::new<JSON::PullParser>:JSON_Level_3a +105
[4533439369] *Array(JSON_Level_3a)@Array(T)::new<JSON::PullParser>:Array(JSON_Level_3a) +73
[4533439288] *(Array(JSON_Level_3a) | Nil)@Union(T)::new<JSON::PullParser>:(Array(JSON_Level_3a) | Nil) +56
[4533438056] *JSON_Level_2c#initialize<JSON::PullParser>:String +264
[4533437769] *JSON_Level_2c::new<JSON::PullParser>:JSON_Level_2c +89
[4533436905] *Array(JSON_Level_2c)@Array(T)::new<JSON::PullParser>:Array(JSON_Level_2c) +73
[4533436824] *(Array(JSON_Level_2c) | Nil)@Union(T)::new<JSON::PullParser>:(Array(JSON_Level_2c) | Nil) +56
[4533426633] *JSON_Level_1b#initialize<JSON::PullParser>:(String | Nil) +2313
[4533424292] *JSON_Level_1b::new<JSON::PullParser>:JSON_Level_1b +116
[4533340838] *JSON_Level0#initialize<JSON::PullParser>:String +1430
[4533339380] *JSON_Level0::new<JSON::PullParser>:JSON_Level0 +116
[4533339250] *JSON_Level0@Object::from_json<String>:JSON_Level0 +34
[4533157221] __crystal_main +1461
[4533212472] main +40
```

**Comment by drosehn** [comment]
My program is already processing much more of the JSON object than I actually care about.  So for my purposes I'm quite happy to simply comment out the line for `v: String | Nil,`, and then set `strict: false` instead of `strict: true`.  It's just that I'm **so** close to handling absolutely everything, and I don't see anything which I've done wrong with how I defined that last field.

**Comment by trans** [comment]
You can use a named tuple to specify options:

* type: (required) the single type described above (you can use JSON::Any too)
* key: the property name in the JSON document (as opposed to the property name in the Crystal code)
* nilable: if true, the property can be Nil. Passing T | Nil as a type has the same effect.
* default: value to use if the property is missing in the JSON document, or if it's null and nilable was not set to true. If the default value creates a new instance of an object (for example [1, 2, 3] or SomeObject.new), a different instance will be used each time a JSON document is parsed.
* emit_null: if true, emits a null value for nilable properties (by default nulls are not emitted)
* converter: specify an alternate type for parsing and generation. The converter must define from_json(JSON::PullParser) and to_json(value, IO) as class methods. Examples of converters are Time::Format and Time::EpochConverter for Time.
* root: assume the value is inside a JSON object with a given key (see Object.from_json(string_or_io, root))

So in your case I think you want something like:

```
    v: { type: String?, default: nil }
```

**Comment by drosehn** [comment]
I would expect that to work the same, but it was certainly worth trying.  The result is that my program still dies in the same place.

It sounds like this is not an obvious well-known issue.  I'll work on making a complete program which demonstrates the error.

**Comment by drosehn** [comment]
Perhaps another clue is that when I change the definition of `v` to be `v: String,` (i.e. dropping the `| Nil`) then `from_json` throws the exception:
```cr
missing json attribute: v at 0:0 (JSON::ParseException)
```
as compared to:
```cr
couldn't parse (String | Nil) from 1359608400 at 0:0 (JSON::ParseException)
```
when I do include `| Nil`.  And also that my full tree of JSON objects does include other fields which are defined as `String | Nil`, and all the other ones work.  In fact, at one point I wondered if I had some unprintable character on the line which defines `v:`, so I deleted that line, copy&pasted one of the working lines, and then changed the variable name from `something:` to `v:`.  And I still ran into the exception.

**Comment by asterite** [comment]
Please provide reproducible code, otherwise there's not much we can do except guessing. I tried to guess a program from what you said:

```cr
require "json"

class Person
  JSON.mapping({
    v: String | Nil,
  }, strict: true)
end

person = Person.from_json("{}")
p person
```

Also in [play](https://play.crystal-lang.org/#/r/1e3t).

It works just fine, so that must not be the problem you are running into.

**Comment by drosehn** [comment]
Okay, thanks for the reply!  I'll trim down my program some more, and post that.

**Comment by drosehn** [comment]
Well, I'm glad I was not comfortable with posting the full example.  My source code had over 300 lines of just the JSON.mapping variables, four levels deep.  The data files had over 600 lines of data.  The object I called `JSON_Level_3a` was a repeated field, which appeared as many as 6 times **per JSON_Level_2a** object, and there were multiple `JSON_Level_2a` objects per  `JSON_Level_1a` object, and one to three  `JSON_Level_1a` objects per data line.  So there were several thousands of the `JSON_Level_3a` objects.

For three of those `JSON_Level_3a` objects, the values were integers instead of a strings.  Oops!  So I wasn't seeing a bug in crystal or in `JSON_mapping`.  But it would be nice if the exception-message returned to the user could be more descriptive.

Here's a simple example which generates the "problem":

```cr
equire "json"

class Person
  JSON.mapping({
    v: String | Nil,           # key line, done wrong
  }, strict: true)
end

person = Person.from_json("{\"v\":\"val-v\"}")
p person

person = Person.from_json("{\"v\":139}")    # <--- unexpected data
p person
```

And this example works fine:

```cr
equire "json"

class Person
  JSON.mapping({
    v: String | Int32 | Nil,   # key line, done right.
  }, strict: true)
end

person = Person.from_json("{\"v\":\"val-v\"}")
p person

person = Person.from_json("{\"v\":139}")    # <--- unexpected data
p person
```
The traceback from the problematic version is:

```cr
couldn't parse (String | Nil) from 139 at 0:0 (JSON::ParseException)
[4431043522] *CallStack::unwind:Array(Pointer(Void)) +82
[4431043425] *CallStack#initialize:Array(Pointer(Void)) +17
[4431043384] *CallStack::new:CallStack +40
[4431029689] *raise<JSON::ParseException>:NoReturn +25
[4431207709] *(String | Nil)@Union(T)::new<JSON::PullParser>:(String | Nil) +301
[4431134359] *Person#initialize<JSON::PullParser>:(String | Nil) +151
[4431134185] *Person::new<JSON::PullParser>:Person +73
[4431134098] *Person@Object::from_json<String>:Person +34
[4430994600] __crystal_main +1080
[4431028776] main +40
```
I don't know what the `from 139 at 0:0 (JSON::ParseException)` refers to, and in my program I was seeing messages like `from 1400990400 at 0:0`, which seemed like a dramatic large number.

**Comment by drosehn** [comment]
Btw, I went back to my original program and original data files, and added the ` | Int32`, and it worked fine.  So that one mistake really was the only thing wrong.

**Comment by drosehn** [comment]
If the definition of `v` was missing the `| Nil`) then `from_json` throws the exception:
```cr
missing json attribute: v at 0:0 (JSON::ParseException)
```
it'd be nice if the error when missing `| Int32` was something like:
```cr
invalid value for json attribute: v at 0:0 (JSON::ParseException)
```

**Comment by kirbyfan64** [comment]
> I don't know what the `from 139 at 0:0 (JSON::ParseException)` refers to, and in my program I was seeing messages like `from 1400990400 at 0:0`, which seemed like a dramatic large number.

I think the `from X` part is the invalid data portion. The 139 was the data that was invalid.

**Comment by drosehn** [comment]
That's pretty obvious, now that you mention it!

**Comment by drosehn** [comment]
Another thing which confused me on this is that all the `JSON_Level0` objects which had numeric values for v: in a  `JSON_Level_3a` object, also had a `JSON_Level_3a` which did not include v: at all.  So I thought it was the missing value which triggered the problem, not the numeric value elsewhere in the same data line.

**Comment by Sija** [comment]
@drosehn is anything else left to do here? if not please close it :)

**Comment by asterite** [comment]
Yes, I'm not sure I understand the problem, so I'm closing this. Please reopen with reproducible code (preferably short code).

**Comment by drosehn** [comment]
@asterite : 
Well, I should have changed the title once I understood what was going on.  The initial problem was a programming error on my part.  My code claimed:
```cr
    v: String | Nil,           # key line, done wrong
```
However, there were three JSON objects (out of thousands) which needed that declaration to be:
```cr
    v: String | Int32 | Nil,   # key line, done right.
```
And when `from_json()` tried to process those objects, it raised an error message of:
```cr
couldn't parse (String | Nil) from 1359608400 at 0:0 (JSON::ParseException)
```
The difficulty for me was that this was in a program of several hundred lines.  And the errors happened on only one data file, and that file was several hundred lines long, with some of the lines being thousands of characters long.

So I knew it'd take me some time to trim this big mess down to a reasonable-sized example.  So I made my initial post hoping that:
> the issue will be obvious even without all the details. So here is bits-and-pieces of a bug report. If this is not enough information, I will continue to shrink the program and obfuscate the data.

But no one who looked at my initial post thought the error was "obvious".  So I went off and spent a few hours trimming down the program and the data, until I found out what the problem was.  And once anyone knows what the problem **is**, then the error message does make complete sense.

I really am glad that no one spent time to track down this error.  I would have felt awful if anyone who **can** work on improving the compiler had wasted their time on trimming down the big mess I was working with.

But I think that initial error message could be more helpful.  The fact remains that if someone had looked at that error and said *'Try scanning your datafile for the string "1359608400".'* , then that would have found the problem with much less work.

I didn't close this issue earlier because I thought I might look at the code and come up with some specific suggestion for a better error message.  (I also had some ideas for other improvements that I wanted to look into).  But I also do not mind if this remains closed.  Now that I do understand the message, I doubt I'll be confused if something like it comes up again in my own code.

**Comment by drosehn** [comment]
Let me add that I thought the `JSON.mapping()` macro and the `.from_json` method worked quite well for me.  When I started to write my program I expected to pull just a few JSON-objects per line out of the data, but I found it was pretty easy to import all of the JSON objects into variables in crystal.  That was pretty nice!
