### ISSUE TITLE
Type Narrowing

### ISSUE THREAD

**Issue by trans** [crystal-lang/crystal#3549]
I would like to see an enhancement to the language to allow narrowing of types.

Take this (stupid) example:

```
   def foo(b : Bool)
     b ? "hundred" : 100
   end

    t = foo(true)
    f = foo(false)

    typeof(t)  #=> (String | Int32)
    typeof(f)  #=> (String | Int32)
```

But the actual values are only one or the other, so can we have a means to manually reduce it? Either,

```
  t.type_reduce!
  f.type_reduce!

  typeof(t)  #=> String
  typeof(f)  #=> Int32
```

Or if it can't be in-place.

```
  s = t.type_reduce
  i = f.type_reduce
  typeof(s)  #=> String
  typeof(i)  #=> Int32
```

Note, I tried to figure out a way to do it using `typeof` and/or `as`, but couldn't figure out a way. I think it would be equivalent to `t.as(t.class)` but that not legal in Crystal b/c `as` accepts only a constant.

**Comment by RX14** [comment]
Please remember that variables are typed at compile time not runtime. The type of a variable is all the types the compiler thinks it could possibly have, so there is no way to reduce the possibilities at compile time without manual intervention (i.e. `as`)

**Comment by trans** [comment]
Okay. I see. So it's not really possible. Still it seems like something is missing. We can say `not_nil!` for instance, or `as(Foo)`. Maybe it would help, at least a little, if we could also say `not(Foo)`.

**Comment by RX14** [comment]
```cr
unless foo.is_a?(Foo)
  # Here foo can't be `Foo`
end
```

`not_nil!` is so ugly to attempt to force you to handle the conditions when types are certain things. For example your `YAML` example on the mailing list, think "if `@value` *is* `nil`, then what do we do?". In a library, that answer is usually "make the user deal with it". It's really a design decision, based on how likely it is that `@value` is `nil`.

**Comment by trans** [comment]
Just came across the code that made me think of this in the first place, and I realized it wasn't `typeof` that was creating it, but `.class`. 

```
Failure/Error: doc.class.should eq(Hash(String, String))

expected: Hash(String, String)
            got: Hash(Array(YAML::ConfigSchema::Type) | Bool | Float64 | Hash(YAML::ConfigSchema::Type, YAML::ConfigSchema::Type) | Int64 | String | Nil, Array(YAML::ConfigSchema::Type) | Bool | Float64 | Hash(YAML::ConfigSchema::Type, YAML::ConfigSchema::Type) | Int64 | String | Nil)
```

Putting aside `YAML::ConfigSchema::Type` (that's another issue b/c it should be YAML::CoreSchema::Type, and I don't know why it's getting that wrong here), but anyway, if this is coming from `doc.class`, isn't that the type at *runtime*?

Note the test that *passes* right before this is:

```
doc.should eq({"foo" => "oof", "bar" => "rab"})
```

Per you previous explanation, I understand if this were the signature from `typeof()` (compile time type), but why such complex type from `.class`? -- That's what led me to ask about type narrowing, it's just that I got side-tracked by `typeof` when I was investigating it.

---

As for your last comment. I understand what you are saying, but the frustration comes from less simple cases where we programmers know the value won't ever be `nil` in a particular place, but the compiler can't. Or I suppose more technically, it will not be `nil` *in practice* -- since I imagine in some cases one could force inject a `nil`, say in a test. So far I think much of my time coding Crystal revolves around making that *design decision* for the best way to handle nils. Hopefully I'll get better at it. Some design guidelines on this might be nice. But I wonder why this never seems to be much of a problem for other union types, just with Nil?

**Comment by RX14** [comment]
If it can never be nil, the best way to deal with that is before the constructor. If that's impossible, use a raise on nil getter with `getter!` (or `property!`). I was asking the question because I wasn't sure if value could be nil when you're parsing valid yaml. If that was the case then I would say that your getter should just return nillable.

**Comment by asterite** [comment]
There's no way to do this. Sorry, this is how statically typed languages work.

**Comment by trans** [comment]
@asterite What about my follow up about `.class`?

**Comment by asterite** [comment]
@trans I don't understand the problem, if you have something of type `A | B`, at runtime `.class` will either say `A` or `B`. But if you have something of type `G(A | B)`, at runtime the type will be `G(A | B)`. This applies to Hash because it's a generic type.

**Comment by trans** [comment]
@asterite Okay, I see. So then for *generic types* would it be possible to "reduce" the type?

**Comment by asterite** [comment]
No. It's impossible to reduce a compile-time type from runtime information...

**Comment by RX14** [comment]
The type of a variable at any given place in a program is all the union of all the types that the compiler believes the variable could possibly be at that place and no more. There is no way to "reduce" that union further, or the compiler would have already done it.

**Comment by trans** [comment]
I thought you just said "at runtime the type will be"? I don't want to reduce the compile time type. 

Perhaps if I explain where the problem arises... When converting YAML to native data types, then end result has this huge type signature, per the example I gave above.

```
Hash(Array(YAML::ConfigSchema::Type) | Bool | Float64 | Hash(YAML::ConfigSchema::Type, YAML::ConfigSchema::Type) | Int64 | String | Nil, Array(YAML::ConfigSchema::Type) | Bool | Float64 | Hash(YAML::ConfigSchema::Type, YAML::ConfigSchema::Type) | Int64 | String | Nil)
```

But the data itself is just `{"foo"=>"oof", "bar"=>"rab"}`, for example. Surely there must be a way to reduce that *runtime type* to the current concrete types of the data, `Hash(String,String)`.

**Comment by RX14** [comment]
@trans Sorry I forgot about the followup.

`.class` will return `Array(Union(A, B, C))` regardless of what types are inside the union. This is because union types have a size. `sizeof(A | B | C)` *will* be different from `sizeof(A)`. This means the code of `Array(A | B | C)` will be different from `Array(A)` because it has a different binary representation. So calling `.type` will not determine the type of the *contents* of `Array` because they are represented the same regardless of whether only a single type fills the hash.

Currently this doesn't seem to be possible to implement because you can't use `Class` as a generic argument. However [this code](https://carc.in/#/r/1e7q) should work once (if) that is implemented.

**Comment by trans** [comment]
@RX14 Thanks. So maybe it will be possible in the future. As I point out, it would provide a marked improvement to loading YAML as native data.

Actually, this has me wondering if YAML sequences might come out better as Tuple instead of Array, and likewise for mappings as NamedTuple instead of Hash (although that would limit key types.)
