### ISSUE TITLE
Minor Inconsistency String#bytes vs Bytes type

### ISSUE THREAD

**Issue by lribeiro** [crystal-lang/crystal#3551]
```
typeof("324".bytes) -> Array(UInt8)
typeof(Bytes) -> Slice(UInt8)
```

Shouldn't the `String#bytes` method, return a `Slice(UInt8)` instead of an `Array(UInt8)` ?

**Comment by asterite** [comment]
An array is usually more useful as it's mutable and it's a copy of the underlying string bytes. If you want the bytes as a slice for performance reasons you can use `to_slice` or `to_unsafe`.

**Comment by asterite** [comment]
I mean, if somebody eventually introduces, say, a `Downcase` type, we then have `String#downcase` and it would be inconsistent because it returns a String? I don't think so. 

Also the docs say: "Returns this string's bytes as an Array(UInt8)"

**Comment by Sija** [comment]
@asterite There's also `Slice#to_a` to easily do the opposite :)

**Comment by asterite** [comment]
I don't understand, we also have `#chars` and `#codepoints`. Should this return Slice instead of Array? Array is the preferred data type to return because it's the most flexible and useful, and it's the one that is commonly returned in API methods.

**Comment by lribeiro** [comment]
When working with `Bytes` it mentally trips me to use `String#bytes` because of the name similarity.

@asterite Ruby for instance does return an `Array`. But it as no `Slice` equivalent on std lib (to my best knowledge, didn't check). 

Why is `Bytes` an alias for `Slice(UInt8)` and not `Array(UInt8)`?

I don't have a strong preference either way, I just think it would be better if they are consistent.
It's not a big deal :)

**Comment by asterite** [comment]
I was kind of against the `Bytes` alias... maybe this explains why :-)

`Slice(UInt8)` is the most common slice type and it's all over the place, so we thought `Bytes` would be a good alias for it. `Array(UInt8)` it not a very common type at all. In fact, maybe we could remove `String#bytes` for that matter...

**Comment by lribeiro** [comment]
I found `Bytes` by accident reading the source code and started using it on my code, I thought it was kind of cool and it does sound better than `Slice(UInt8)`.

If it is renamed to `String#to_a` that would open up space for `String#bytes` returning `Bytes` :)

**Comment by kostya** [comment]
thats why i vote for name Binary :)

**Comment by lbguilherme** [comment]
A better name for this could be `"aaa".utf8`. The idea is that while all you have is a String, the fact that it is stored as an UTF8 sequence of bytes is just an implementation detail that is not disclosed. But this is the method that exposes this binary representation.

**Comment by asterite** [comment]
I'm closing this, this is a minor consistency, and I'm sure there are many more bigger inconsistencies throughout the language. It's really impossible for a language to be 100% consistent. `Bytes` (or `Slice(UInt8)` is mostly used in low-level code to read/write from an IO. `Array` is the preferred container type, so it's OK for `String#bytes` to return `Array(UInt8)`.

**Comment by j8r** [comment]
To clarify the method, it could be `String#bytes_array : Array(UInt8)`.
