### ISSUE TITLE
inherit struct

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3556]
why i can't do this?

```crystal
record Bla, a : Int32 do
  def some
    a
  end
end

struct Bla2 < Bla
  def some
    a + 1
  end
end
```

```
can't extend non-abstract struct Bla
```

**Comment by ysbaddaden** [comment]
See https://github.com/crystal-lang/crystal/issues/2529

**Comment by kostya** [comment]
why not allow inheritance, and disallow only define initialize method?

**Comment by asterite** [comment]
@kostya The reasons are explained in #2529

As a separate issue, I'd something like to have `record` that generates a class, and then you'd be able to extend it, but I don't know what a nice syntax for that could be.

**Comment by al6x** [comment]
Just found out that I can't do this because `Error: can't extend non-abstract struct Time`

```Crystal
struct Date < Time
  def self.parse(yyyy_mm_dd : String)
    parse_utc yyyy_mm_dd, "%F"
  end

  def to_s(io : IO); to_s io, "%F" end
end
```

How cases like that should be handled?

**Comment by Blacksmoke16** [comment]
Define another type that decorates another `Time` instance:

```cr
struct Date
  forward_missing_to @time

  def initialize(@time : Time); end

  def to_s(io : IO)
    @time.to_s io, "%F"
  end
end
```

**Comment by al6x** [comment]
Thanks, looks reasonably good!
