### ISSUE TITLE
bug with inline rescue

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3565]
```crystal
p 1/0 rescue 1 # no output
p(1/0 rescue 1) # Syntax error in eval:1: expecting token ')', not 'rescue'
```

**Comment by Sija** [comment]
first example doesn't print anything due to exception but correctly returns `1`. second one lacks space in between method name and its arguments (correct version would be `p (1/0 rescue 1)`, which works)

**Comment by kostya** [comment]
actually ruby behave the same

**Comment by lbguilherme** [comment]
Why isn't this allowed, I wonder?

I've always assumed `rescue` worked just like a normal binary operator, with very low precedence.
