### ISSUE TITLE
Failing specs in macOS from master branch for OpenSSL

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/crystal#3605]
Using the latest build from master `Crystal 0.20.0+37 [4439f2d] (2016-11-28)` when I run `.build/crystal spec/` I get the following errors:

```text
Failures:

  1) OpenSSL::SSL::Context has sane client defaults shouldn't connect to incomplete-chain.badssl.com

       expected OpenSSL::SSL::Error but nothing was raised

     # expanded macro: expect_raises:1

  2) OpenSSL::SSL::Context has sane client defaults shouldn't connect to dh480.badssl.com

       expected OpenSSL::SSL::Error but nothing was raised

     # expanded macro: expect_raises:1

  3) OpenSSL::SSL::Context has sane client defaults shouldn't connect to dh480.badssl.com with verification disabled

       expected OpenSSL::SSL::Error but nothing was raised

     # expanded macro: expect_raises:1

  4) OpenSSL::SSL::Context has sane client defaults should connect to mozilla-modern.badssl.com successfully

       SSL_connect: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
       0x10da01b12: *CallStack::unwind:Array(Pointer(Void)) at ??
       0x10da01ab1: *CallStack#initialize:Array(Pointer(Void)) at ??
       0x10da01a88: *CallStack::new:CallStack at ??
       0x10d5f1071: *raise<OpenSSL::SSL::Error>:NoReturn at ??
       0x10ea9182a: *OpenSSL::SSL::Socket::Client#initialize:context:hostname<TCPSocket, OpenSSL::SSL::Context::Client, String>:Nil at ??
       0x10ea91749: *OpenSSL::SSL::Socket::Client::new:context:hostname<TCPSocket, OpenSSL::SSL::Context::Client, String>:OpenSSL::SSL::Socket::Client at ??
       0x10d9fad48: *connect_to<String, OpenSSL::SSL::Context::Client>:Bool at ??
       0x10eae3231: */Users/jeremywoertink/Development/crystal/lang/spec/manual/badssl_spec.cr#connect_to<String>:Bool at ??
       0x10d9fdee8: ~proc14Proc(Nil)@spec/manual/badssl_spec.cr:84 at ??
       0x10d5fb08a: *it<String, String, Int32, Int32, &Proc(Nil)>:(Array(Spec::Result) | Nil) at ??
       0x10d9fa51c: ~procProc(Nil)@spec/manual/badssl_spec.cr:16 at ??
       0x10db3af52: *Spec::RootContext::describe<String, String, Int32, &Proc(Nil)>:Spec::Context+ at ??
       0x10d5fae09: *describe<String, String, Int32, &Proc(Nil)>:Spec::Context+ at ??
       0x10d5d7baa: __crystal_main at ??
       0x10d5ef8c8: main at ??

Finished in 9:26 minutes
11527 examples, 3 failures, 1 errors, 11 pending

Failed examples:

crystal spec spec/manual/badssl_spec.cr:27 # OpenSSL::SSL::Context has sane client defaults shouldn't connect to incomplete-chain.badssl.com
crystal spec spec/manual/badssl_spec.cr:45 # OpenSSL::SSL::Context has sane client defaults shouldn't connect to dh480.badssl.com
crystal spec spec/manual/badssl_spec.cr:51 # OpenSSL::SSL::Context has sane client defaults shouldn't connect to dh480.badssl.com with verification disabled
crystal spec spec/manual/badssl_spec.cr:84 # OpenSSL::SSL::Context has sane client defaults should connect to mozilla-modern.badssl.com successfully
```

Running on macOS 10.12.1

**Comment by luislavena** [comment]
Hello,

I think when running specs of the compiler, two things needs to be used:

- The special `bin/crystal` wrapper instead of direct invocation of `.build/crystal`
- The usage of `make` instead of the invocation directly.

Perhaps the later can be ignored, but if not mistaken, the usage of the wrapper is required so paths are correctly used.

In relation to OpenSSL and OSX, perhaps the issue is the linked version of OpenSSL?

If I'm not mistaken, it will rely on `pkg-config` to determine the version. I'm not sure if brew forced the new version of OpenSSL be linked, so perhaps special flags are required, as AFAIK OSX ships with an old version of OpenSSL.

Hope that helps.

**Comment by RX14** [comment]
Using the wrong compile command usually bombs out at the compile stage, howrver its probably worth seeing if using `make spec` makes a difference.

**Comment by jwoertink** [comment]
Ah, ok. So running `make spec` has all of them pass. I must have missed the docs that say to use `make spec` over `crystal spec` somewhere. Maybe we can get a line on [this page](https://crystal-lang.org/docs/installation/from_source_repository.html) that says something like "Once built, run make spec to ensure everything was installed correctly"?. Thanks for the help!

**Comment by bcardiff** [comment]
Maybe we should rearrange in [that page](https://crystal-lang.org/docs/installation/from_source_repository.html)
> (..) The new compiler will be placed at .build/crystal

and

> (..) Inside the repository you will also find a wrapper script at bin/crystal

The former isn't that useful and might lead to this problems. `bin/crystal` should be the only one that appears or at least appear before (leaving `.build/crystal` as a footnote). 

I agree with a note for running specs using `bin/crystal` for your shard/app and `make spec` for the compiler specs.

**Comment by jwoertink** [comment]
Yeah, that would be awesome. It was a little confusing when reading it. As if using the `bin/crystal` was just an option if you wanted, and not a requirement.

**Comment by bcardiff** [comment]
If someone is inspired the file to change would be: https://github.com/crystal-lang/crystal-book/blob/master/installation/from_source_repository.md

**Comment by jwoertink** [comment]
Ok, I've submitted a PR for those docs. Since this isn't really an issue, but more clarification, I'll close this out. Thanks!
