### ISSUE TITLE
can crystal language compiler target emscripten or  javascript

### ISSUE THREAD

**Issue by catmando** [crystal-lang/crystal#3618]
I apologize in advance for using an issue - SO would not allow this type of question.

Is there a version / repo / branch of crystal targeting browser JS?

If not are there known barriers to doing this, or WIP in this direction?

I would be very interested in supporting this activity with time and possibly $$

Thanks (and if there is a better way to ask this question, let me know...)

**Comment by kirbyfan64** [comment]
TL;DR: **No**.

You could try compiling just to LLVM bitcode and then run that through emscripten, or try LLVM's WIP WebAssembly backend (which doesn't actually work ATM), but I don't know if it'd work.

Also, questions like this are usually better suited to the mailing list!

**Comment by bcardiff** [comment]
duplicate of #535 

But maybe since that moment crystal got support for other platforms maybe things can move forward.

**Comment by catmando** [comment]
I apologize... I somehow missed the very obvious mailing list / gitter instructions.  My bad... Im going to close this.
