### ISSUE TITLE
When slices are converted to array, code is not always executed

### ISSUE THREAD

**Issue by benoist** [crystal-lang/crystal#3624]
The following shows code not being executed at all when using slices of a union type.

```crystal
slice = Slice(Int32).new(1)
puts slice.to_a[0] == 1

slice = Slice(Float32).new(1)
puts slice.to_a[0] == 1

slice = Slice(Int32 | Float32).new(1)
if slice.to_a[0] == 1
  puts "true"
else
  puts "false"
end
puts "finished"

## Output
# false
# false
# finished
```
https://play.crystal-lang.org/#/r/1fcr

It also stops printing the contents.

```crystal
slice = Slice(Int32).new(1)
puts slice.to_a

slice = Slice(Float32).new(1)
puts slice.to_a

slice = Slice(Int32 | Float32).new(1)
puts slice.to_a

## Output
# [0]
# [0]
# [
```

**Comment by asterite** [comment]
`Slice.new(size)` allocates memory of that size initialized to zeros. Not zero (not 0_i32 or 0_f32), but memory zero. However, memory zero doesn't denote any value of a union of `Int32 | Float32`. So it's unsafe, and you get undefined behaviour.

We should probably note this in the method docs, saying that unless you are using a primitive type like an integer or float, chances are that you are using the wrong method.

`Slice(T).new(size)` is usually used when T is UInt8, so for `Bytes.new(3)` (ask 3 bytes of memory heap and get a slice to it)

**Comment by RX14** [comment]
@asterite Maybe things like this are a valid use case for an `unsafe` attribute which makes sure people at least know what they're getting into. I probably wouldn't have clocked this error at first because in my mind `Slice` is a "safe" type.

**Comment by ysbaddaden** [comment]
Is it really meaningful to have slices of unions?

**Comment by asterite** [comment]
@ysbaddaden I don't know, but a slice is a generic type. Maybe we can limit `Slice.new(size)` to primitive types such as integers and floats and error in another case. That will make the method (and the whole type) safe, because that's the only unsafe method.
