### ISSUE TITLE
HTTP::Headers is case-sensitive

### ISSUE THREAD

**Issue by sdogruyol** [crystal-lang/crystal#3626]
Someone using Kemal came with an issue that he can't use the WebSockets behind Nginx. However he could use Node.js with similar setup.

Looking at the nginx.conf 

```
  location    / {
    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://{{ .APP }};
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
    proxy_pass_request_headers on; # I added this as an attempt to forward everything
  }
```

i found that it's `proxy_set_header Connection "upgrade";` which makes Crystal `HTTP::Headers` to fail. Changing to `Upgrade` works but IMHO this is a bug.

Here's also a reproducible sample code

https://play.crystal-lang.org/#/r/1feh

**Comment by Sija** [comment]
`context.request.headers.includes_word?("Connection", "Upgrade")` check in https://github.com/crystal-lang/crystal/blob/master/src/http/server/handlers/websocket_handler.cr#L15 might be responsible for the fail.

**Comment by sdogruyol** [comment]
@Sija it looks like the easy culprit but here's the actual one https://github.com/crystal-lang/crystal/blob/84b0c6d6749803cd8784990e0bd3e59a4f918909/src/http/headers.cr#L81

**Comment by Sija** [comment]
@sdogruyol yep, https://github.com/crystal-lang/crystal/blob/master/src/http/headers.cr#L84 could be changed to `start = value.downcase.index(word.downcase)` to avoid this issue by performing case-insensitive comparison.

**Comment by sdogruyol** [comment]
Yeah, i thought so but waiting for confirmation before sending a PR 👍

**Comment by asterite** [comment]
Yes, it's a bug :-)

I think @Sija 's solution is correct, though I'd move `word.downcase` outside the loop... I also think the implementation isn't quite correct because maybe a submatch is found but is not the full match, and the string isn't scanned past the first occurrence. I'll probably fix it soon, don't worry.

**Comment by asterite** [comment]
Fixed, though I'm not very happy with the solution. I'd like to find a good RFC on how values are separated in header fields. There's [this](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2), so maybe splitting by comma and then checking by case-insensitive equality could work, but then there's [this](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.3), where a header value can be `gzip;q=1.0, identity; q=0.5, *;q=0` so splitting by comma wouldn't work.
