### ISSUE TITLE
Missing LLVM inline assembly options

### ISSUE THREAD

**Issue by zatherz** [crystal-lang/crystal#3636]
[LLVM supports three options for the inline assembly syntax](http://llvm.org/docs/LangRef.html#inline-assembler-expressions):

Inline asms with side effects not visible in the constraint list must be marked as having side effects. This is done through the use of the ‘sideeffect‘ keyword, like so:  
```llvm
call void asm sideeffect "eieio", ""()
```

In some cases inline asms will contain code that will not work unless the stack is aligned in some way, such as calls or SSE instructions on x86, yet will not contain code that does that alignment within the asm. The compiler should make conservative assumptions about what the asm might contain and should generate its usual stack alignment code in the prologue if the ‘alignstack‘ keyword is present:  
```llvm
call void asm alignstack "eieio", ""()
```

Inline asms also support using non-standard assembly dialects. The assumed dialect is ATT. When the ‘inteldialect‘ keyword is present, the inline asm is using the Intel dialect. Currently, ATT and Intel are the only supported dialects. An example is:  
```llvm
call void asm inteldialect "eieio", ""()
```

There is currently no way to make use of these from Crystal.

**Comment by asterite** [comment]
You can use "volatile" instead of "sideeffect" and "alignstack" for "alignstack". LLVM C bindings don't provide a way to pass the "inteldialect" flag, though, so even though it's parsed by Crystal it's not passed along.

Check [this](https://github.com/crystal-lang/crystal/blob/79be7730b418199050e3ba091a5a57d35b531558/spec/compiler/parser/parser_spec.cr#L1192-L1202)

**Comment by asterite** [comment]
I think we copied "volatile" from how you specify inline asm in c or c++, can't remember now. I think Rust uses that too.

**Comment by asterite** [comment]
I'm closing this because you can do this right now as I explained above
