### ISSUE TITLE
formatter not formatting macros

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3638]
```crystal
class Bla
  macro bla(some1, some2)
          value = {{some1}} + {{some2}}
        end
end
```

expected
```crystal
class Bla
  macro bla(some1, some2)
    value = {{some1}} + {{some2}}
  end
end
```

**Comment by asterite** [comment]
Macros are text content without a format, there's no way to format them right now. This is also something I'd like to improve, maybe macros shouldn't just be text content but be parsed by an almost regular parser. The problem is that some things will stop working. For example this:

```cr
macro foo(x)
  var_{{x.id}} = 1 # This isn't a valid program without knowing what x resolves to
end
```

**Comment by asterite** [comment]
To explain this a bit more, imagine this:

```cr
macro foo(x, y)
  {{x.id}}s 1 {{y.id}}
end

foo "put", " + 2 + 3"
```

The above is totally ridiculous, but it works. This is because the macro content is like a template language, it has no semantic. Just after putting everything together it is parsed. And you can see that there's no reasonable way to format the above.
