### ISSUE TITLE
Formatter failing on file for no apparent reason.

### ISSUE THREAD

**Issue by timuckun** [crystal-lang/crystal#3639]
The error message:

crystal tool format src/lmdb/cursor.cr
Error:, couldn't format 'src/lmdb/cursor.cr', please report a bug including the contents of it: https://github.com/crystal-lang/crystal/issues

The file https://github.com/timuckun/crystal-liblmdb/blob/master/src/lmdb/cursor.cr

**Comment by cjgajard** [comment]
syntax error at line 175
https://github.com/timuckun/crystal-liblmdb/blob/master/src/lmdb/cursor.cr#L175

**Comment by timuckun** [comment]
Just out of curiosity did the format tell you that? I never got an error and the file compiled correctly.

**Comment by cjgajard** [comment]
no, it even runs "correctly" :confounded:
```cr
def foo(x)
  x ? : x : "top kek"
end

puts foo(true) #=> true
puts foo(false) #=> top kek
```

**Comment by timuckun** [comment]
I know the specs ran without issue so I presumed there were no errors in the file.

How odd that the compiler didn't catch that. 

BTW I never liked the ? operator.  In the old days of VB we had iif as in iif(x, x, "top kek")

**Comment by petehuang** [comment]
Seems like we've resolved this and can close this issue? 😃

**Comment by RX14** [comment]
If it compiles, it should format, if only to remove the redundant syntax. I still think this is a bug.

**Comment by asterite** [comment]
@timuckun Please copy and paste the failing file here, otherwise I don't know how to reproduce this issue

**Comment by timuckun** [comment]
@asterite I already fixed y code and pushed my changes but the affected line is currently at line 170 of https://github.com/timuckun/crystal-liblmdb/blob/master/src/lmdb/cursor.cr 

 It read  

```crystal 
@success ? : {@success, key, data} : {@success, nil, nil} 
```
