### ISSUE TITLE
`var = uninitialized T` returns Nil instead of type T

### ISSUE THREAD

**Issue by bcardiff** [crystal-lang/crystal#3641]
The following code is not working as expected:

```crystal
g = h = uninitialized Int32
puts typeof(h) # => Int32
puts typeof(g) # => Nil
```

It should be

```crystal
g = h = uninitialized Int32
puts typeof(h) # => Int32
puts typeof(g) # => Int32
```

I reach this reducing from

```crystal
a = if rand() > 0.5
  1
else
  b = uninitialized Int32
  b
end
typeof(a) # => Int32

c = if rand() > 0.5
  1
else
  d = uninitialized Int32
end
typeof(c) # => Int32 | Nil
```

It seems `var = uninitialized T` is not returning the garbage value of type `T`.

crystal: 0.20.0

**Comment by asterite** [comment]
Yes, `uninitialized` doesn't return anything, it's more like a statement than an expression. Doing `a = b = uninitialized Int32` will not mark `a` as uninitialized. I'm not sure I'd like to change this.
