### ISSUE TITLE
Segfault when trying to print a HTTP request body

### ISSUE THREAD

**Issue by meew0** [crystal-lang/crystal#3647]
I'm getting a segfault under a specific set of circumstances when trying to print the body of a `HTTP::Request` I received on the server. I'm aware that I should be reading it to a string first if I want the actual content, but it shouldn't cause a segfault either way. Code example (that never fails to cause the bug for me):
```cr
require "http/server"
require "http/client"

server = HTTP::Server.new(8080) do |env|
  puts "a", env.request.body
end

spawn { server.listen }
sleep 1 # wait some time for the server to start up
HTTP::Client.post("http://127.0.0.1:8080/test", HTTP::Headers.new, "some content")
```

The output I get:
```
a
Invalid memory access (signal 11) at address 0xffffffb2
[94383834920517] *CallStack::print_backtrace:Int32 +117
[94383834884408] __crystal_sigfault_handler +56
[94383835685350] sigfault_handler +57
[140173091455104] ???
[94383835059005] *Scheduler::create_fd_read_event<IO::FileDescriptor, Bool>:Event::Event +93
Program exited because of a segmentation fault (11)
```

From my testing it seems that to cause the problem the `puts` line has to be in that format (string first, then the request body) to cause the error. I've tried the following alternatives and none of them causes a segfault:

- `puts env.request.body`
- `puts({"a", env.request.body})`
- `puts "a", "b"`
- `puts env.request.body, env.request.body`
- `puts env.request.body, "a"` (this line actually produces no output at all apart from a newline, which could be related, not sure)

The contents of the string `"a"` don't seem to matter, and it doesn't even have to be a literal: `Time.now.to_s` caused the problem too.

I'm on Arch Linux (4.8.10-1, x64) using LLVM 3.9. The bug occurred both with 0.20.0 and git master, which in my case was `Crystal 0.20.1+6 [284f7d6] (2016-12-06)`. It also seems to only occur in debug mode - I haven't tested the alternative lines in release mode but if I compile the snippet above in release mode there's no segfault.

**Comment by asterite** [comment]
Reduced:

```cr
require "http/server"

puts "a", HTTP::FixedLengthContent.new(IO::Memory.new, 0).as(IO)
```

Seems to happen only when passing multiple arguments to `puts`. I'll need to investigate this further to understand what's going on.
