### ISSUE TITLE
Spec::before_each could not instanciate in block given

### ISSUE THREAD

**Issue by madeindjs** [crystal-lang/crystal#3659]
Like with Rspec in Ruby, I want to implement a **"before each"** method to avoid repeat myself between units tests

In Ruby is simple like this:

```ruby
describe Thing do
  before(:each) do
    @thing = Thing.new "Beep Bop"
  end

  it "should instanciate" do
    assert @thing
  end
end
```

But I can't do it in Crystal

```crystal
require "./spec_helper"
    
describe Thing do
  Spec.before_each do
    @r = Thing.new "Beep Bop"
  end

  it "Should instanciate" do
    @r.should_not be nil
  end
end

#=> can't use instance variables at the top level
```

**Comment by madeindjs** [comment]
I will use [minitest.cr](https://github.com/ysbaddaden/minitest.cr)

**Comment by ysbaddaden** [comment]
2 notes:

- I don't think using spec's exceptions with minitest.cr's test runner will behave correctly; for example you'll get errors instead of failures. That may be changed, thought.
- you should call `r` instead of accessing `@r`, since `let` creates a method.

**Comment by RX14** [comment]
I think that there should be a common "Assertion Failure" exception shared between all spec libraries to allow mixing and matching assertion libraries with spec runners.
