### ISSUE TITLE
Nil assertion failure for String[Regex]

### ISSUE THREAD

**Issue by chocolateboy** [crystal-lang/crystal#3668]
**Crystal**: Crystal 0.20.1 (2016-12-06)
**OS**: Linux (Arch)

My original test case for [this issue](https://github.com/crystal-lang/crystal/issues/3667) was:

```crystal
ARGF.each_line do |line|
  puts line if line.chomp[/^9+$/]
end
```

But I had to change the second line to:

```crystal
puts line if line.chomp =~ /^9+$/
```

\- because the [`String#[](Regex)`](https://crystal-lang.org/api/0.19.4/String.html#%5B%5D%28regex%3ARegex%29-instance-method) call causes Crystal to crash with the following error:

    Nil assertion failed (Exception)
    0x4024e0: ??? at ??
    0x40260a: ??? at ??
    0x403ded: ??? at ??
    0x411de8: main at ??
    0x7f7de45ab291: __libc_start_main at ??
    0x401fca: _start at ??
    0x0: ??? at ??

**Comment by chocolateboy** [comment]
Incidentally, I realise changing it to:

```crystal
puts line if line.chomp[/^9+$/]?
```

\- fixes it, but I'm assuming that the error is meant to be caught by the compiler rather than at runtime?

**Comment by chocolateboy** [comment]
Duplicate of #3648.

**Comment by kostya** [comment]
but backtrace look strange, i also get such `??? at ??`, seems after 0.20 version
