### ISSUE TITLE
Crystal breaks stdin

### ISSUE THREAD

**Issue by chocolateboy** [crystal-lang/crystal#3674]
**Crystal**: 0.20.1 (2016-12-06)
**OS**: Linux (Arch)
**Shell**: GNU bash 4.4.5

#### stdin-test.sh

```bash
read answer
echo $answer
```

### Steps to reproduce

1) Run `stdin-test.sh`; enter some text and hit return. The text should be echoed to the terminal.
2) Run `crystal eval 'puts "Hello, world!"'` or `crystal run` a file.
3) Run `stdin-test.sh`.

### Output

    sh ./stdin-test.sh: line 1: read: read error: 0: Resource temporarily unavailable

For the past couple of months I've had a problem with stdin in my terminal where interactive commands cease to be interactive. I usually notice this when I run a package manager or `rm -i` a file. The program attempts to ask me for confirmation, but stdin has somehow become detached from the tty and the program exits immediately with an error e.g.:

    $ rm -i ./temp.cr
    rm: remove regular file 'temp.cr'? rm: error closing file

The problem goes away (until the next time I run crystal) if I run `exec $SHELL -l` or the `reset-nonblock` program in [this post](https://stackoverflow.com/a/16402813).

I assume this is a conflict with something on my system, since I can't find any other references to it, but I don't have any Crystal-related environment variables or aliases set.

Is Crystal setting `O_NONBLOCK` on stdin and [failing to reset it](https://stackoverflow.com/a/16402813)?

**Comment by chocolateboy** [comment]
Possible related: https://github.com/crystal-lang/crystal/issues/2713#issuecomment-250975971

**Comment by chocolateboy** [comment]
As per [this comment](https://github.com/crystal-lang/crystal/issues/2065#issuecomment-240149102), the problem goes away if the script includes:

```crystal
 STDIN.blocking = true
```

**Comment by drosehn** [comment]
Hmm.  Looks like I run into this too, but I didn't realize that crystal was triggering it.  In my case I'd notice it when typing 'mail', and the mail command would immediately exit.

I can reproduce this, and it happens even though the crystal program does not read from STDIN.  And the problem does go away if I add `STDIN.blocking = true`.

**Comment by asterite** [comment]
To fix #2713 we'll have to stop changing the blocking status to std io descriptors, and then this issue will be fixed. Can I mark this as a duplicate of #2713 ?

**Comment by chocolateboy** [comment]
Sure.
