### ISSUE TITLE
Rich Channel API

### ISSUE THREAD

**Issue by andrewhamon** [crystal-lang/crystal#3682]
Channels are awesome! And since channels are a class, I think theres a huge opportunity to make using channels super ergonomic.

## Each
```crystal

# Blocks fiber until channel closes
channel.each do |value|
  process(value)
end
```

## Pipelining with map

```crystal

# Doesn't block, returns a channel immediately
half_done = chan.map do |item|
  some_work(item)
end

all_done = half_done.map do |item|
  more_work(item)
end

# Collect results as they come in and do something with them
all_done.each do |result|
  log_result(result)
end
```

## Easy fan outs

```crystal
# Spawn 10 worker fibers and collect results in a single channel
results_chan = chan.fan_out(10) do |item|
  process(item)
end

results_chan.each do |result|
  # Use results as they come in
end
```

## Filtering to multiple channels
```crystal
only_foos = chan.filter do |item|
  item.foo?
end

only_bars = chan.filter do |item|
  item.bar?
end

food_and_bars = chan.filter do |item|
  item.foo? || item.bar?
end
```

What do you think? Are there any other languages we could draw inspiration from? I've not seen anything like this for Go.

**Comment by andrewhamon** [comment]
Some of this could be achieved simply by including [Iterator](https://crystal-lang.org/api/0.20.1/Iterator.html) in Channel

**Comment by asterite** [comment]
Something like this will eventually come, once we support parallelism. I'll close this because there's nothing actionable we can do here. You can discuss this in Google Groups.

**Comment by andrewhamon** [comment]
@asterite I'm a little confused... these things would work fine without parallelism, no? They would just be suited toward IO intensive workloads rather than compute.
