### ISSUE TITLE
Last line returns value difference between Crystal & Ruby

### ISSUE THREAD

**Issue by puppetpies** [crystal-lang/crystal#3688]
Hi Guys,

I kind of curious whether this is a bug or not with Crystal as in Ruby the last line is always the returned object.

[brian@orville shards-git]$ icr
icr(0.19.2) > module Test
icr(0.19.2) >   V = 1
icr(0.19.2) >   end
 => ok
icr(0.19.2) > p Test
Test
 => Test
icr(0.19.2) > quit

IRB returns 1 the value of V

[brian@orville shards-git]$ irb
irb(main):001:0> module Test
irb(main):002:1> V = 1
irb(main):003:1> end
=> 1
irb(main):004:0> p Test
Test
=> Test
irb(main):005:0> quit

Regards,

Brian Hood

**Comment by RX14** [comment]
It doesn't make sense for modules to return a value in crystal as modules or classes aren't created at runtime. They are purely compile-time constructs.

**Comment by asterite** [comment]
Hi,

This should be reported to the icr project (it's not an official project). Note that in Crystal class and module definitions have no value, so they are always `nil` (you can't assign them, for example, which is also something different than Ruby, so...)
