### ISSUE TITLE
Nilable class type grammar

### ISSUE THREAD

**Issue by Exilor** [crystal-lang/crystal#3696]
This is a veeeeeery minor issue but nevertheless:

```crystal
def test(arg : Object.class?) # expecting identifier 'class', not 'class?'
end
```
I think it would be more consistent and nicer to write than:
```crystal
def test(arg : Object.class | Nil)
end
```

**Comment by MakeNowJust** [comment]
You can write:

```crystal
def test(arg : (Object.class)?)
end
```

**Comment by Exilor** [comment]
It's an acceptable solution 😄 . The devs can reopen this if they'd rather have it working without the parentheses.
