### ISSUE TITLE
Type inference seems to fail with Array(Int32?) instance variable

### ISSUE THREAD

**Issue by dkhofer** [crystal-lang/crystal#3738]
Hi,

I have a class with an instance variable that's an `Array(Int32?)`, but the compiler doesn't like it when I try to set it to an array initialized to contain only `Int32`s.

```
class Foo
  property x : Array(Int32?)
  
  def initialize(y)
    @x = y
  end
  
  def run
    puts @x
  end
end

input = (0..3).to_a
Foo.new(input).run
```

Using crystal 0.20.1 this produces an error: 

```
Error in line 14: instantiating 'Foo:Class#new(Array(Int32))'

in line 5: instance variable '@x' of Foo must be Array(Int32 | Nil), not Array(Int32)
```

I'd expect the compiler to notice that `input` has a compatible type and convert it to that of the instance variable `@x`.  Am I missing something?  Is there some other way to accomplish what I'm trying to do?  Thanks for any help you can provide.

**Comment by kirbyfan64** [comment]
The problem here is that, if these were converted automatically, you'd end up being able to do this:

```crystal
foo = Foo.new(input)
foo.x.push nil
puts input  # Now input contains a nil value, but it's type isn't nillable!!!
```

See here for more info: https://en.m.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)#Covariant_arrays_in_Java_and_C.23

**Comment by asterite** [comment]
The reason @kirbyfan64 is correct, you can't pass `Array(Int32)` to a variable of type `Array(Int32 | Nil)`.

**Comment by lbguilherme** [comment]
Addendum:

The correct way would be doing: `Foo.new(input.map(&.as(Int32?))).run`

**Comment by dkhofer** [comment]
I see.  Thank you for the explanation!
