### ISSUE TITLE
puts 5 - 10.1/0

### ISSUE THREAD

**Issue by simon1tan** [crystal-lang/crystal#3755]
This simple code produces "-Infinity". I think this should be a "Divide by 0" error. Yah?

**Comment by RX14** [comment]
Dividing an integer by zero will raise, but dividing an IEEE floating point number by zero will give infinity, as the standard defines every floating point operation to always give a well defined result.

**Comment by hugoabonizio** [comment]
Ruby returns the same: https://carc.in/#/r/1hl1

**Comment by asterite** [comment]
Yes, dividing a float by zero gives infinity.
