### ISSUE TITLE
Formatter fails on inline assembly if extra keywords are used

### ISSUE THREAD

**Issue by SplittyDev** [crystal-lang/crystal#3756]
The `format` tool (`crystal tool format`) formats some special cases of inline assembly in a way that's almost certainly unintended.

**Steps to reproduce**
Write some inline assembly that makes use of a keyword like `volatile`, `alignstack`, etc.:
```crystal
asm("inl %dx, %eax" : "={eax}"(result) : "{dx}"(port) :: "volatile")
```
Run `crystal tool format`.

**Description of the bug**
The `format` tool reformats the inline assembly and removes the space between the arguments and the keyword. To highlight the difference, here's some more code:
```crystal
asm("foo" : bar : baz :: "volatile") # before reformat
asm("foo" : bar : baz:: "volatile")  # after reformat

asm("foo" :: bar, baz :: "volatile") # before reformat
asm("foo" :: bar, baz:: "volatile")  # after reformat
```

**Additional information**
Crystal compiler version: `Crystal 0.20.1 [18e7617] (2016-12-05)`
Operating System: `Ubuntu 14.04.5 LTS`

I'm running Crystal within WSL on Windows 10 64-bit, but that shouldn't matter.

**Comment by asterite** [comment]
@SplittyDev Thank you for reporting this! 😊
