### ISSUE TITLE
Type inference in objects different from global?

### ISSUE THREAD

**Issue by Thyra** [crystal-lang/crystal#3761]
I took this example from a Crystal presentation video in Prague in 2015 ([YouTube](https://www.youtube.com/watch?v=xbdVs4FhZac)):
```crystal
str = "Hello"
idx = str.index('z') # type is Int32?

if idx
  str[idx]
end
```
It still works fine: The compiler knows that idx can't be nil inside the if and doesn't complain. But if I try to use the same logic with object properties I get an error:
```crystal
class Something
  @index : Int32?

  def method
    str = "Hello"
    if @index
      puts str[@index]
    end
  end
end

a = Something.new
a.method
```
Error message:
```
no overload matches 'String#[]' with type (Int32 | Nil)
Overloads are:
 - String#[](start : Int, count : Int)
 - String#[](regex : Regex, group)
 - String#[](index : Int)
 - String#[](range : Range(Int, Int))
 - String#[](str : String)
 - String#[](regex : Regex)
Couldn't find overloads for these types:
 - String#[](Nil)

      puts str[@index]
```
Why is that? The compiler could be absolutely sure that `@index` isn't nil inside the if.

**Comment by RX14** [comment]
@Thyra In a multi-threaded program, the type of @index could change between the type check and usage. The fix to this is to use a local variable. A common pattern is assigning inside the if:
```cr
if index = @index
  puts str[index]
end
```

**Comment by Thyra** [comment]
@RX14 That, makes sense, thank you! :-)

**Comment by asterite** [comment]
Just for reference, it's also explained in the [docs](https://crystal-lang.org/docs/syntax_and_semantics/if_var.html)
