### ISSUE TITLE
[critical] UNIXServer delete important file if it cannot bind to it

### ISSUE THREAD

**Issue by Bew78LesellB** [crystal-lang/crystal#3764]
While writing the test for #3763 I realized there is another critical bug : 

```crystal
require "socket"

def check_file(prefix, file)
  if File.exists? file
    puts "#{prefix} File exists"
  else
    puts "#{prefix} No file"
  end
end

path = "/tmp/important_file"

# create an important file
File.write path, "important content"

check_file "Touch/", path

# try to bind
begin
  UNIXServer.new path
rescue err
  puts "Error raised !"
  puts
  check_file "Server/", path
  puts "Error was: #{err.message}"
end
```
Output for master, Crystal 0.20.3 : 
```
Using compiled compiler at .build/crystal
Touch/ File exists
Error raised !

Server/ No file
Error was: bind: Address already in use
```
It is caused by the `close` in [UNIXServer#new L32](https://github.com/crystal-lang/crystal/blob/0.20.3/src/socket/unix_server.cr#L32)  
Which will delete the file if you cannot bind to it

**Comment by asterite** [comment]
Yes, I think this is a bug. The file should only be deleted on close if it's successfully bound.

I also tried it in Ruby (`rescue => err` instead of `rescue err`) and it doesn't delete the file.

**Comment by ysbaddaden** [comment]
Yes. I'll fix that.

**Comment by ysbaddaden** [comment]
@Bew78LesellB thanks for detecting this issue!
