### ISSUE TITLE
#subclasses method

### ISSUE THREAD

**Issue by jasonl99** [crystal-lang/crystal#3768]
I'm trying to write a method that returns an array of subclasses (the actual class, not the string).  I have it working, but I think this is a bit of a hack.

The class variable @@subclasses gets typed properly when I instantiate it with the Animal class, and works as you can see by the output.  But I also have to shift the array to remove the abstract class.  It seems I should be able to do something like `@@subclasses = [] of Animal` though this would just be an array of instances, not classes.  Is there a special grammar for types of this sort?

```crystal
abstract class Animal
  @@subclasses = [Animal]  # specified manually!
  @@subclasses.shift       # drop the class leaving the array properly typed and empty

  def self.subclasses
    @@subclasses
  end
  
  macro inherited
    Animal.subclasses << {{@type.name}}
  end

end
  
class Dog < Animal
end

class Cat < Animal
end

class Terrier < Dog
end

Animal.subclasses               # [Dog, Cat, Terrier] : Array(Animal)
Animal.subclasses[0].new 	# <Dog:0x1387f40>	Animal

**Comment by Sija** [comment]
Yeah, there's [`Crystal::Macros::TypeNode#subclasses`](https://crystal-lang.org/api/0.20.3/Crystal/Macros/TypeNode.html#subclasses%3ACrystal%3A%3AMacros%3A%3AArrayLiteral%28TypeNode%29-instance-method).

```cr
abstract class Animal; end

class Dog < Animal; end
class Cat < Animal; end

class Terrier < Dog; end

# print all subclasses
pp {{ Animal.all_subclasses }}
# print only direct subclasses
pp {{ Animal.subclasses }}
```

**Comment by jasonl99** [comment]
Thank you!
