### ISSUE TITLE
NamedTuple.from should cast?

### ISSUE THREAD

**Issue by maiha** [crystal-lang/crystal#3792]
It seems casting doesn't work.

Document says: `casted to the given types`
- https://github.com/crystal-lang/crystal/blob/0.20.3/src/named_tuple.cr#L41-L44

But following simple code fails, and found no specs for the casting feature.

```crystal
NamedTuple(bar: Int64).from({:bar => 2})
```

```
Error in test.cr:1: instantiating 'NamedTuple(bar: Int64):Class#from(Hash(Symbol, Int32))'

NamedTuple(bar: Int64).from({:bar => 2})
...
   1.
   2.       NamedTuple.new(
   3.
>  4.         "bar": self[:bar].cast(hash.fetch(:bar) { hash["bar"] }),
   5.
   6.       )
   7.

instantiating 'Int64:Class#cast(Int32)'
in /home/maiha/.crenv/versions/0.20.3/src/class.cr:40: can't cast Int32 to Int64

    other.as(self)
```
- using `Crystal 0.20.3 [b1416e2] (2016-12-23)`

FYI: I don't need the feature. I'm just compiling examples  :)

Thanks.

**Comment by asterite** [comment]
Cast in crystal means `as`. Converting from Int32 to Int64 is a different thing.

**Comment by maiha** [comment]
@asterite:
Oh, I see the difference, thanks.

Well, in other words, does `NamedTuple.from` have converting feature?
Or, is the example wrong?

#### example code in `named_tuple.cr`
```crystal
NamedTuple(foo: String, bar: Int64).from({:foo => "world", :bar => 2})       # => {foo: "world", bar: 2}
```
This doesn't work.

#### @Sija commented `Int64` is intended before
https://github.com/crystal-lang/crystal/pull/3730#discussion_r92952154
```
Changing Int64 to Int32 for bar disables casting feature which this example is about
```

Is it a just problem of example? And, should we correct the example like this?
```diff
-:bar => 2
+:bar => 2_i64
```

**Comment by asterite** [comment]
I think the example is wrong. At least in the code I see a `cast` call, which eventually calls `as` in `Class#cast`. I'm not sure, maybe @jhass has a better idea?

**Comment by jhass** [comment]
Yes, the example is wrong, sorry. But we should find something that shows casting.
