### ISSUE TITLE
Problem with finalize

### ISSUE THREAD

**Issue by blocknotes** [crystal-lang/crystal#3793]
Crystal: **0.20.3**

I have a problem with finalize / destructor method...

    class Foo
      def initialize
        puts "Init !"
      end
      def finalize
        puts "Bye bye from #{self}!"
      end
    end
    Foo.new

But finalize is not called (I tried also build / build --release).
Am I doing something wrong?

**Comment by ysbaddaden** [comment]
You're not doing anything wrong.

Finalize is only called by the Garbage Collector when it eventually collects the memory. It's not called immediately when the object becomes unreachable nor when the program exits, since the OS will already collect the memory.

**Comment by blocknotes** [comment]
Is it guaranteed that it will be called?
I made some tests, and currently it seems ignored here.

- Test1: I'm trying to create a file in finalize (replacing the puts line)... but no file is created
- Test2: using C bindings, with a wrapper class, deinit function called in finalize... and I get a warning line in stdout (or stderr) _"QThreadStorage: Thread 0x7fe8afc8d1e0 exited after QThreadStorage 7 destroyed"_; instead if I call manually deinit function all seems ok.

**Comment by RX14** [comment]
@blocknotes it is guaranteed to be called if the memory is collected, however is is not guaranteed that your memory will ever be collected. It gets increasingly likely as your program running times get to be 1h or more (depending on how much allocation it does), but especially for small scripts finalizers are never likely to be run. Your object may also still be stored somewhere in your program which would predent collection.

**Comment by drhuffman12** [comment]
Such a `#finalize` method would be nice to have.

Until that is added, would something like the following suffice as a work-around?
```
class Foo
  ..
  def main # run, etc
    begin
    ..
    rescue ..
    ..
    ensure
      # do finalize stuff here
    ..
    end
  end
end
```

**Comment by RX14** [comment]
@drhuffman12 The common pattern for this is to have a `.open` method which yields. For example
```cr
File.open(filename) do |file|
  # do stuff
end
# The file is *guaranteed* to be closed here or if an exception is raised
```

**Comment by drhuffman12** [comment]
@RX14, that looks good too.

**Comment by blocknotes** [comment]
Thank you for your suggestions @RX14 and @drhuffman12 
In my situation the "block" way should be ok; but something like Ruby `ObjectSpace.define_finalizer(self, proc { puts "Bye bye" })` would be very useful IMO.

It would be easier to make something like:
```ruby
class MyClass
  def initialize
    MyLibC.init
  end
  def main
    MyLibC.fun1
    # ...
  end
  def finalize
    MyLibC.deinit
  end  
end
```

**Comment by RX14** [comment]
@blocknotes That's what `finalize` is.

**Comment by blocknotes** [comment]
@RX14 I mean that it would be nice to have a "classic" destructor which can be used to dispose / deinitialize / clean up

**Comment by RX14** [comment]
@blocknotes What exactly is lacking in the current destructor behaviour?

**Comment by blocknotes** [comment]
A method of the object which is automatically and always invoked when the object is destroyed / the program ends (like the proc of define_finalizer does)

**Comment by RX14** [comment]
@blocknotes it is always invoked when the object is collected, but not when the program ends. The reason why finalizers are not run when the program ends is that if the program ends we expect the OS to do the job of the finalizer, which is to clean up memory, file descriptors or other handles.

**Comment by ysbaddaden** [comment]
@blocknotes there is no automated solution, and GC has a limited action on destructors (as explained above), but that are idiomatic solutions to your problem.

You may have a method to do the cleanup (as explained above), then call it in `finalize` and add a constructor that will yield the resource, and ensure the cleanup when the block exits. This method works best for short-lived resources (e.g. opening a file).

```crystal
class Foo
  def self.open
    foo = new
    begin
      yield foo
    ensure
      foo.close
    end
  end

  def initialize
    @closed = false
  end

  def finalize
    close
  end

  def close
    # ensure we don't call the method twice
    return if @closed
    @closed = true

    # do your cleanup here
  end
end
```

Alternatively, you may create your resource and use an `at_exit` block to make sure to cleanup when program exits. This solution works best for long-lived resources (e.g. a database connection, or a library initialization).

```crystal
SDL.init
at_exit { SDL.quit }
```
