### ISSUE TITLE
[question] Is there a way to create a private instance variable?

### ISSUE THREAD

**Issue by andyfleming** [crystal-lang/crystal#3800]
I'm aware of instance and class variables, but is there a way to create a private instance variable?

```crystal
class Person
  def initialize()
    @example_one = "instance variable"
    @@example_two = "static/class variable"
    # No way to create a private instance variable
  end
end
```

**Comment by RX14** [comment]
Instance variables are always private. The only way to "expose" an instance variable is through getetrs/setters, either manually created or using the `getter`, `setter` or `property` macros.

**Comment by andyfleming** [comment]
I see that now. Sorry about that.

For anyone else that comes across this, here's the snippet from the docs that shows creating a getter/setter for an instance variable.

```
class Person
  def initialize(name : String)
    @name = name
    @age = 0
  end

  def name
    @name
  end

  def age
    @age
  end
end
```

From https://crystal-lang.org/docs/syntax_and_semantics/new,_initialize_and_allocate.html

**Comment by mgarciaisaia** [comment]
Don't get confused - that code defines getters, but there are no setters there.

A setter looks like this:

```crystal
def instvar=(value)
  @instvar = value
end
```

But the best way to deal with this is using the macros for defining getters, setters or accesors (both getter AND setter).

**Comment by andyfleming** [comment]
Thanks! Someone else explained the concepts a bit more clearly for me.

I opened an issue to improve the documentation here: https://github.com/crystal-lang/crystal-book/issues/62
