### ISSUE TITLE
[OpenSSL] Add a server and client usage example 

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#3810]
I see allot of confusion as to how properly use the OpenSSL lib, the spec doesn't have a full example and neither the docs or api.

I created the most basic example for server\client 

some problematic pointers in the examples: 
* No Exception handling (we can add some)  
* Using `verify none`, it's a bad example, but it's the only one that will work without a real certificate  
* comments ?   

### Server  
```crystal
require "socket"
require "openssl"

# Generate keys to /tmp/
# openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout /tmp/private.key -out /tmp/certificate.crt

def server
  socket = TCPServer.new(5555)
  context = OpenSSL::SSL::Context::Server.new
  context.ciphers = "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"
  context.private_key = "/tmp/private.key"
  context.certificate_chain = "/tmp/certificate.crt"
  context.add_options(OpenSSL::SSL::Options::NO_SSLV2 | OpenSSL::SSL::Options::NO_SSLV3)
  puts "server is up"
  socket.accept do |client|
    puts "got client"
    ssl_socket = OpenSSL::SSL::Socket::Server.new(client, context)
    slice = Slice(UInt8).new(20)
    ssl_socket.read(slice)
    puts String.new(slice)
  end
end

server
```

### Client  
```crystal
require "socket"
require "openssl"

def client
  socket = TCPSocket.new("127.0.0.1", 5555)
  context = OpenSSL::SSL::Context::Client.new
  context.ciphers = "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"
  context.add_options(OpenSSL::SSL::Options::NO_SSLV2 | OpenSSL::SSL::Options::NO_SSLV3)
  context.verify_mode = OpenSSL::SSL::VerifyMode::NONE
  ssl_socket = OpenSSL::SSL::Socket::Client.new(socket, context)
  ssl_socket.write("Testing".to_slice)
end

client
```

**Comment by spalladino** [comment]
Good idea. Could you send a PR with these examples to the OpenSSL API documentation, so we discuss it there? Thanks!

**Comment by bararchy** [comment]
@spalladino Where is the repo with the API ? find only the one which holds the docs.

**Comment by bararchy** [comment]
@spalladino Ok, I saw from other libs that the API is dynamically created from the header comments inside the file.

Should I create my PR for the openssl.cr file ? or for the docs repo ?

**Comment by spalladino** [comment]
@bararchy in `openssl.cr` directly. Thanks!

**Comment by bararchy** [comment]
@spalladino https://github.com/crystal-lang/crystal/pull/3865
