### ISSUE TITLE
Add size (amount of bytes) to read in File.read

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#3817]
Currently File does not support an Integer to specify how much to read from it (all or nothing).
Would it be a good idea to add `File.read("file", size: 50)` to read 50 bytes from the file ?

**Comment by kostya** [comment]
File.read works with encodings, so read bytes should be bad? may be chars?

**Comment by luislavena** [comment]
Considering `File.read` returns a string, `size` doesn't communicate properly. Does it represents *bytes*? What if the encoding used is a multi-byte one, does it represents *characters* instead?

Perhaps will be a good addition to introduce `File.binread` similar to Ruby which allows you read the entire *binary* contents of a file (disregard of the encoding) and using that method, be able to specify how many bytes should be read from the indicated file.

Just some thoughts :smile:

**Comment by asterite** [comment]
Even though Ruby supports this, I wonder what's the use case for that. When do you need to read exactly N bytes/chars from a File? Ruby also has an offset argument, which makes me wonder more what's a use case for that.

In any case, you can do:

```cr
# Read 50 bytes, as a String, from the File
File.open "filename.txt", &.gets(50)
```

It's a one-liner, just like `File.read` would be. So I'm not sure it's worth adding a specialized method or argument for that.

**Comment by bararchy** [comment]
@asterite
 I usually use it when sampling files or lets say

```ruby
# read 1024 bit of random data
rand = File.read("/dev/urandom", 1024)
```

for example.

But as Crystal has it's own IO logic (no `socket.read(Int32)`, etc...) I get why it might not be relevant

**Comment by bcardiff** [comment]
@bararchy `IO#read_fully` is also available at might be convenient for sampling files:

```crystal
slice = Bytes.new(10) # => Bytes[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
File.open("/dev/urandom") do |f|
  f.read_fully(slice)
end
slice                 # => Bytes[245, 101, 232, 231, 197, 44, 38, 39, 140, 75]
```
