### ISSUE TITLE
Support for UDP Multicasting

### ISSUE THREAD

**Issue by jaitaiwan** [crystal-lang/crystal#3825]
I spent a bit of time trying to get UDP multicasting happening with Crystal. What I learned is that it is theoretically possible to do with Crystal, but you need to understand the underlying system calls to make that happen.

So my request is for wrappers around the UDP socket to allow for easily joining multicast groups and sending broadcasts similar to Go's `net.ListenMulticastUDP` function and associated functionality so that one does not have to play with `setsockopts`.

Thanks!

**Comment by ysbaddaden** [comment]
This is already supported. Just set `sock.broadcast = true` then connect the UDP socket. See [this spec](https://github.com/crystal-lang/crystal/blob/b1416e2b4e53e08bcc6769b6908f2eacff8b5e0a/spec/std/socket_spec.cr#L503) for example.

```crystal
sock = UDPSocket.new(Socket::Family::INET)
sock.broadcast = true
sock.connect("255.255.255.255", 1234)
sock.send("my broadcasted message")
```

Some documentation seems to be lacking, though.

**Comment by jaitaiwan** [comment]
Are you on IRC @ysbaddaden?

I saw that broadcasts were supported which is fantastic but unless my knowledge is mistaken, to listen to a multicast address like say `239.255.60.60` you need to bind to `0.0.0.0` and then do something funky with `setsockopts` to join that multicast group?

**Comment by ysbaddaden** [comment]
Then no, we don't provide a helper for the `IP_ADD_MEMBERSHIP` socket option.
