### ISSUE TITLE
Proposal: Rename File::Stat to FileInfo

### ISSUE THREAD

**Issue by lbguilherme** [crystal-lang/crystal#3828]
Crystal is moving to be supported in non posix plataforms (#3582). But some of the standard library api have posixisms in place, and my proposal is to remove some of them. 

`File::Stat` represents information about a file and I think it would be best if it was designed to represent this concept and not simply be a direct copy of posix names. Today you do: `File.lstat("foo").mtime` and it could be: `File.info("foo", follow_links: false).modification_time`. Qt does a similar thing: [`QFileInfo`](http://doc.qt.io/qt-5/qfileinfo.html).

(Probably there will be more proposals like this)

**Comment by luislavena** [comment]
Perhaps `File::Info` suits better? (following the idea of avoid repeating the parent namespace word).

In the case of `modification_time`, perhaps `modified_time` fits better, since is a bit shorter :wink:

**Comment by sevk** [comment]
```ruby

include File::Info
File.new("foo").mtime

```

I think this is better     😄

**Comment by bcardiff** [comment]
I think is solved in #5584
