### ISSUE TITLE
Create array of module type

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#3836]
This should work:

```cr
module Moo
end

class Foo
  include Moo
end

class Bar
  include Moo
end

a = [] of Moo.class
a << Foo
a << Bar
```

**Comment by yxhuvud** [comment]
While I really like the expressibility this adds, "[] of Moo.class" looks a quite weird at first glance, as I'd assume that returns Module, meaning that a would be a  Array of arbitrary modules.

Speaking of which, I can find no api docs for modules.

**Comment by luislavena** [comment]
@yxhuvud you can interpret `Moo.class` to be *a class that implements Moo interface*, similar to what you do with `Moo` by itself:

```crystal
ary = [] of Moo
```

Is interpreted as *an array of Moo instances (or any object instance that implements Moo interface)*.

**Comment by luislavena** [comment]
@yxhuvud re: api docs for Module: the only docs shown for class are due included/injected methods (serialization, comparison, etc).

You can find Module and Class documentation in the docs:

- https://crystal-lang.org/docs/syntax_and_semantics/modules.html
- https://crystal-lang.org/docs/syntax_and_semantics/classes_and_methods.html

**Comment by yxhuvud** [comment]
@luislavena But then #class for modules would do something utterly different compared to #class everywhere else. I object to the naming in the API, there is no question about functionality of it. Moo.includer is probably what I'd would have choosen, as that also gives an obvious Moo.extender for the classes that has been extended by the module. 

As for interpretations of implementing interfaces, would this allow for duck typed classes that have methods that match the API without including it which is what your suggested interpretation boils down to? I assumed that it didn't, but if it does, then I'd instead suggest ```a = [] of Moo.interface```

As for Class documentation, that exist at https://crystal-lang.org/api/0.20.3/Class.html. I guess the question can be boiled down into: Are modules first class objects that can be passed around, the way classes are? Sure, you can't include them dynamically the way you can instantiate classes, but they start getting methods and used for instantiating stuff like generics, then they probably should be.

**Comment by asterite** [comment]
@yxhuvud It already works like that, check [the docs, section "Classes as restrictions"](https://crystal-lang.org/docs/syntax_and_semantics/type_restrictions.html)

**Comment by yxhuvud** [comment]
@asterite: how about the extend case:

```
module Moo
end

class Foo
  extend Moo
end

class Bar
  extend Moo
end

a = [] of Moo.???
a << Foo
a << Bar
```

**Comment by asterite** [comment]
@yxhuvud That already works, if you do `[] of Moo`, because when you extend, you make the "metaclass" inherit the module.

I admit it's a bit confusing, but classes and metaclass are confusing.

**Comment by yxhuvud** [comment]
I think I just got more confused, because for classes ```[] of Moo``` would mean [] is an array of instances of Moo, and I'd have expected both a and b to work:

```
module Moo
end

class Foo
  include Moo
end

a = [] of Foo
a << Foo.new
b = [] of Moo
b << Foo.new
```

That is, the elements of the array have the instance methods of the class/module.

**Comment by asterite** [comment]
(btw, you can use triple backticks followed by "cr" to get syntax coloring for crystal)

Yes, the above snippet works :-)

When you `include Moo` in `Foo`, **instances** of `Foo` are "instances" of `Moo`. So it works.

When you `extend Moo` in `Foo`, the **class** `Foo` is an "instance" of `Moo`.

When you do `[] of Foo.class` it means "array of class Foo or subclasses of Foo" (but not instances, just classes). What's missing is the same concept for "array of types (not instances) that include a module".

**Comment by yxhuvud** [comment]
@asterite: Glad to hear that. Then I wasn't as confused as I though. Then I repeat my question about the extend case, ie array of types that extend from a module to use your phrasing.

**Comment by asterite** [comment]
What question? :-)

**Comment by yxhuvud** [comment]
The comment including '???'

**Comment by asterite** [comment]
It works:

```cr
module Moo
end

class Foo
  extend Moo
end

class Bar
  extend Moo
end

a = [] of Moo
a << Foo
a << Bar
```

But the use case is this:

```cr
module Action
  abstract def exec
end

class Jump
  include Action

  def exec
    puts "Jumping!"
  end
end

class Run
  include Action

  def exec
    puts "Running!"
  end
end
```

Now if you want an array of **types** that include `Action`, I can't do it. I might want to do that because I will create different instances, maybe pass them something in the constructor.

**Comment by yxhuvud** [comment]
Ok, confusion gone after trying around examples. The case of arrays of instances from classes that extends from a module *is* missing, but perhaps that is a lot less necessary to have as it usually is the api of the generic content and not the api of the class of the generic argument that is relevant.

**Comment by pyrsmk** [comment]
In the same regard, this currently does not work:

```crystal
module TestInterface
end

class Test
  include TestInterface
  
  def build_tests : Array(TestInterface)
    [Test.new]
  end
end
```

It fails at compile time with `Error: method must return Array(TestInterface) but it is returning Array(Test)`.

**Comment by Blacksmoke16** [comment]
@pyrsmk `[Test.new] of TestInterface`

See https://github.com/crystal-lang/crystal/issues/3803.

**Comment by asterite** [comment]
Return types are checks, they don't give types to expressions.

**Comment by pyrsmk** [comment]
So bad, this is a strong limitation with the interface paradigm. But I can understand this is a tricky subject.

**Comment by asterite** [comment]
Well, actually, in this case one would expect `[Test.new]` to kind of match `Array(TestInterface)` but then there's the covariance stuff so it's not clear what should be done here.

**Comment by pyrsmk** [comment]
@asterite Maybe a workaround would be to add a way to say `that value must be an Array of descendants of Type`. By explicitly define what we want, it can do the trick (maybe?).

**Comment by asterite** [comment]
Yes, that's essentially what covariance and conteavariance annotation are for. See for example C# who has them (I think kotlin too). However, implementing something like that in Crystal is not only a huge task, it might also be impossible to do because type annotations are optional.

**Comment by pyrsmk** [comment]
I understand. So a better approach would be to rethink how I'm handling my return types with arrays and interfaces. For example, having a `SomethingCollection` class/struct that accepts any `SomethingInterface` would do the job.

**Comment by asterite** [comment]
What you want to do is already possible. Maybe show us some code that's not working?

Note that this issue is about arrays of module types, not module instances. Your case should work. That the return type doesn't match the array type is a separate issue.

**Comment by pyrsmk** [comment]
> Note that this issue is about arrays of module types, not module instances.

Yes, I noticed the difference from my case afterward 😅

> That the return type doesn't match the array type is a separate issue.

I agree, but it's strongly linked to my case anyway IMHO. Take this `NodeCollection` example:

```crystal
module NodeInterface
end

struct Node
  include NodeInterface
end

module NodeCollectionInterface
  include Enumerable(NodeInterface)
  abstract def with(node : NodeInterface) : NodeCollectionInterface
end

struct NodeCollection
  include NodeCollectionInterface

  @nodes = [] of NodeInterface

  def initialize(@nodes : Array(NodeInterface)); end

  def each
    @nodes.each { |node| yield node }
  end

  def with(node : NodeInterface) : self
    self.class.new(@nodes.concat([node]))
  end
end

NodeCollection.new([Node.new, Node.new]).with(Node.new)
```

As expected, the compile fails on the initialize. And I can't see a way of handling the input otherwise.

**Comment by asterite** [comment]
@pyrsmk Replace your last line with this:

```crystal
NodeCollection.new([Node.new, Node.new] of NodeInterface).with(Node.new)
```

**Comment by asterite** [comment]
I'm actually not sure this issue is valid, the original snippet doesn't make sense, now that I look back at it.

**Comment by pyrsmk** [comment]
Woh! I wasn't aware that I could do that...  So it seems there wasn't really no issue at all... 😅 Thanks! 

What doesn't make sense in my snippet?

**Comment by asterite** [comment]
The type of an array is deduced from its elements. When you write `[Node.new]` the type becomes `Array(Node)`. That's not compatible with `Array(NodeInterface)` because you can only add `Node` to that array, not any kind of `NodeInterface`. When you write `[Node.new] of NodeInterface` you are saying that the array is of NodeInterface, not just Node.

This is the one thing that bites Crystal developers the most. I don't know how we can improve the situation.

**Comment by pyrsmk** [comment]
That completely makes sense now that you explained it, and to be honest this is one thing I didn't remember after reading the guide.

But the explanation is right here, at the bottom of the inheritance chapter... So I feel silly. 

Maybe it needs more visibility in the summary, directly at the top with other edge cases.

**Comment by docelic** [comment]
> This is the one thing that bites Crystal developers the most. I don't know how we can improve the situation.

Interesting, I always thought this was very clear.
(I mean, it is only expected that if a person writes `Smth.new`, Crystal can't auto-detect this as being anything other than type `Smth`. If a user wants to change or extend that, they need to be specify it manually like with that `of NodeInterface`)

**Comment by HertzDevil** [comment]
This actually should not work; `Foo.class` and `Bar.class` are not subtypes of `Moo.class` (see https://github.com/crystal-lang/crystal/issues/11119#issuecomment-906818264 in particular), because class methods defined in `Moo` are inaccessible in `Foo` and `Bar`:

```crystal
module Moo
  def self.foo; end
end

class Foo
  include Moo
end

Moo.foo # okay
Foo.foo # Error: undefined method 'f' for Foo.class
```

It follows that `Moo.class` is a leaf type and the only possible element of an `Array(Moo.class)` is the value `Moo`.

If we adapt the subtyping rules to make this work then modules would behave like an unwieldy alternative to multiple inheritance rather than mixins.
