### ISSUE TITLE
JSON: Add Object.from_json(any : JSON::Any)

### ISSUE THREAD

**Issue by DougEverly** [crystal-lang/crystal#3842]
If I already have a `JSON::Any` object from a prior `JSON.parse()`, I would like to use that JSON::Any to initialize any `JSON.mapping()` class or struct. Currently only accepts `String` or `IO`.

Use case would be if I need to inspect a `JSON::Any` object to determine what `JSON.mapping()` object I want to instantiate.

I made some partial progress [here](https://github.com/DougEverly/crystal/tree/map_json_any2) but got stuck in a chicken/egg scenario with regard to macro code generation.

**Comment by kostya** [comment]
https://github.com/crystal-lang/crystal/issues/3743

**Comment by DougEverly** [comment]
Following up in #3743 with example case for using JSON::Any.
