### ISSUE TITLE
Infrastructure: Hook up Travis' docker images to repository tags

### ISSUE THREAD

**Issue by luislavena** [crystal-lang/crystal#3853]
Builds performed on Travis (the current CI used by Crystal) have been a bit behind from releases.

It appears this process requires manual build of such images (per comment [here](https://github.com/crystal-lang/crystal/pull/3848#issuecomment-270915390))

This also affects builds of submitted PRs.

Perhaps will be possible to:

- Move the `Dockerfile` used to produce these Linux targets (32 and 64bits) into Crystal repository
- Check if the build of those images can be automated via Docker hooks on tags (not every commit)
- If previous cannot be done, document steps/instructions or script required to run after each release.

Thank you
:heart: :heart: :heart: 

/cc @jhass @asterite

**Comment by splattael** [comment]
Yes, automatic docker builds would be great!

Currently, `0.20.4` is missing on https://hub.docker.com/r/crystallang/crystal/ :disappointed:

**Comment by splattael** [comment]
As a temporary workaround one might use the `lastest` tag:

**Comment by splattael** [comment]
The tag `0.20.4` magically appeared on https://hub.docker.com/r/crystallang/crystal/tags/ :smile_cat: 

Thank you! :green_heart:

**Comment by spalladino** [comment]
See if this could be integrated with #3721

**Comment by RX14** [comment]
@spalladino I think docker builds are best done on docker hub itself, but release builds + packaging is definitely a goal for the CI I have in mind. Then the Dockerfile then would just download a package and install it. Providing an officially-supported alpine package and docker container would also be something I would be willing to spend time doing.

**Comment by david50407** [comment]
Agree with @RX14, I think the final build should be built once, but can be delivered in many methods, like: Docker image, Ubuntu package, Homebrew formula, etc.

But I don't know if this is possible because Crystal depends on the host environment (like LLVM version, in some distro may provide different versions LLVM package)

**Comment by drujensen** [comment]
Bumping this issue:

Can we setup the automatic build of docker images using tags on Docker Hub?  https://hub.docker.com/r/crystallang/crystal/tags/

0.24.1 is out but the image still doesn't exist. 

It's fairly easy to configure automated builds now.  You can setup the master branch to create the latest image and tags to create released versions.

Branch: master -> crystallang/crystal:latest
Tag: * -> crystallang/crystal:*

**Comment by straight-shoota** [comment]
Automatic docker builds from CI have been working for quite some time now. Closing.
