### ISSUE TITLE
Error target failed to compile

### ISSUE THREAD

**Issue by zolamk** [crystal-lang/crystal#3857]
i am trying to build a crystal cartridge for OpenShift located [here](https://github.com/zolamk/openshift-crystal) but the template program i have included fails to compile with the error given below even though it builds fine on my local machine, i think OpenShift uses RHEL, i use Ubuntu on my local machine

	Error target template failed to compile:
	/usr/bin/ld: skipping incompatible /usr/lib/libpthread.so when searching for
	-lpthread
	/usr/bin/ld: skipping incompatible /usr/lib/librt.so when searching for -lrt
	/usr/bin/ld: skipping incompatible /usr/lib/libdl.so when searching for -ldl
	/usr/bin/ld: skipping incompatible /usr/lib/libc.so when searching for -lc
	_main.o: In function `*IO::FileDescriptor#initialize<Int32, Bool, Bool>:(Event::Event
	| Nil)':
	main_module:(.text+0x3c79): undefined reference to `event_new'
	main_module:(.text+0x3ce0): undefined reference to `event_new'
	_main.o: In function `*IO::FileDescriptor+@IO::Buffered#close:Nil':
	main_module:(.text+0x400e): undefined reference to `event_free'
	main_module:(.text+0x404d): undefined reference to `event_free'
	_main.o: In function
	`*IO::FileDescriptor+@IO::FileDescriptor#add_write_event<(Float64 | Nil)>:Nil':
	main_module:(.text+0x454a): undefined reference to `event_new'
	_main.o: In function `*Fiber#run:(IO::FileDescriptor | Nil)':
	main_module:(.text+0x4c70): undefined reference to `event_free'
	main_module:(.text+0x5441): undefined reference to `event_free'
	_main.o: In function `*IO::FileDescriptor#add_write_event<(Float64 | Nil)>:Nil':
	main_module:(.text+0x600a): undefined reference to `event_new'
	_main.o: In function `*File@IO::Buffered#close:Nil':
	main_module:(.text+0xd591): undefined reference to `event_free'
	main_module:(.text+0xd5d9): undefined reference to `event_free'
	_main.o: In function `*File@IO::FileDescriptor#add_write_event<(Float64 | Nil)>:Nil':
	main_module:(.text+0xd88a): undefined reference to `event_new'
	_main.o: In function `*IO::FileDescriptor+@IO::FileDescriptor#add_read_event:Nil':
	main_module:(.text+0xdf34): undefined reference to `event_new'
	_main.o: In function
	`~procProc(Nil)@/var/lib/openshift/5870d2977628e1bab2000059/crystal/cache/crystal-0.20.3-1/src/kernel.cr:175':
	main_module:(.text+0x13b02): undefined reference to `event_new'
	_main.o: In function `*File@IO::FileDescriptor#add_read_event:Nil':
	main_module:(.text+0x19074): undefined reference to `event_new'
	collect2: ld returned 1 exit status
	Error: execution of command failed with code: 1: `cc -o
	"/var/lib/openshift/5870d2977628e1bab2000059/app-root/runtime/repo/.crystal/var-lib-openshift-5870d2977628e1bab2000059-app-root-runtime-repo-src-template.cr/macro-run-_var_lib_openshift_____d_______e_bab________crystal_cache_crystal-_.__._-__src_ecr_process.cr"
	"${@}"  -rdynamic  -lpcre -lgc -lpthread
	/var/lib/openshift/5870d2977628e1bab2000059/crystal/cache/crystal-0.20.3-1/src/ext/libcrystal.a
	-levent -lrt -ldl -L/usr/lib -L/usr/local/lib`

**Comment by RX14** [comment]
Looks like you don't have libevent installed, libraries required are listed here: https://github.com/crystal-lang/crystal/wiki/All-required-libraries.

**Comment by spalladino** [comment]
Closing. Let us know if the issue persists!
