### ISSUE TITLE
Old Mac OS

### ISSUE THREAD

**Issue by denovez** [crystal-lang/crystal#3859]
Crystal lang posible to install ini old Mac OS?
I'm using mac OS 10.6.8 32bit
Tying with homebrew cant found the source.
Please help

**Comment by ysbaddaden** [comment]
We only have support for 64bits on macOS. I suppose we could have 32bits support (mostly C bindings). Alternatively you may use Crystal in a Linux VM, for which we have 32bits support.

**Comment by spalladino** [comment]
We are not planning on adding support for Mac OS 32 bit. We do welcome a PR if you are interested in adding support for it.

**Comment by ysbaddaden** [comment]
Most of the work should be to generate the LibC bindings, then fix a few bugs that may arise from the different architecture.

**Comment by denovez** [comment]
thanks for information about that. 
i will try with another machine.
i wish next period already support 32bit MacOS 👍

**Comment by akzhan** [comment]
Who wants to, will do
