### ISSUE TITLE
Improve error message when trying to instantiate module

### ISSUE THREAD

**Issue by hinrik** [crystal-lang/crystal#3885]
Ruby has a slightly more helpful error message when you try to instantiate a module which has an `initialize` method (got this after an incomplete conversion of a module to a class).

```crystal
module Foo
  def initialize
  end
end

Foo.new

# crystal foo.cr
# Error in foo.cr:6: undefined local variable or method 'allocate'
#
# Foo.new
#     ^~~

# ruby foo.cr
# foo.cr:6:in `<main>': undefined method `new' for Foo:Module (NoMethodError)
```

**Comment by david50407** [comment]
@mverzilli btw, I think this is about compiler, not macros

**Comment by mverzilli** [comment]
Fair enough :).

**Comment by RX14** [comment]
bump, should be low-hanging fruit :)
