### ISSUE TITLE
open crystal-lang.org  hardly in China

### ISSUE THREAD

**Issue by lgphp** [crystal-lang/crystal#3886]
mybe build a mirror in China, i curl install crystal on ubuntu by curl show `" Unknown SSL protocol error in connection to dist.crystal-lang.org:443"`  some days. why?

**Comment by mverzilli** [comment]
Please provide further details about your system (Ubuntu version, architecture) and the paste the exact `curl` command you ran. I'll close this until you provide that info.

**Comment by lgphp** [comment]
i  use command: curl https://dist.crystal-lang.org/apt/setup.sh | sudo bash
system info:Linux version 3.13.0-95-generic (buildd@lgw01-10) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) ) #142-Ubuntu SMP Fri Aug 12 17:05:16 UTC 2016

**Comment by lgphp** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty

**Comment by lgphp** [comment]
Linux lgphp 3.13.0-95-generic #142-Ubuntu SMP Fri Aug 12 17:05:16 UTC 2016 i686 i686 i686 GNU/Linux

**Comment by david50407** [comment]
@lgphp run `curl -vv https://dist.crystal-lang.org/apt/setup.sh` and post the result?

**Comment by lgphp** [comment]
curl: (35) Unknown SSL protocol error in connection to dist.crystal-lang.org:443  ,yes the result too. mybe is 
GW  i think. try it  tomorrow

**Comment by inpothet** [comment]
@lgphp 
If you want i can try to mirror the setup.sh on my server so you can try ?

**Comment by inpothet** [comment]
@lgphp I mirrored it to my site https://haazen.xyz/setup.sh lets hope it works this way

**Comment by asterite** [comment]
Hi @inpothet , did it work?

**Comment by inpothet** [comment]
The script was working when i uploaded it but i uploaded it for @lgphp so we need to ask him if it worked

**Comment by sdogruyol** [comment]
Can we close this?
