### ISSUE TITLE
Error During Compiling

### ISSUE THREAD

**Issue by inpothet** [crystal-lang/crystal#3891]
Everytime i try to run my crystal project i get the following error
 
    _main.o: In function `__crystal_main':
    main_module:(.text+0x7b2): undefined reference to `SSL_library_init'
    main_module:(.text+0x7b7): undefined reference to `SSL_load_error_strings'
    main_module:(.text+0x7bc): undefined reference to `OPENSSL_add_all_algorithms_noconf'
    main_module:(.text+0x7c1): undefined reference to `ERR_load_crypto_strings'
    O-penS-S-L-5858S-S-L-5858C-ontext5858S-erver.o: In function     `*OpenSSL::SSL::Context::Server#initialize:Nil':
    OpenSSL::SSL::Context::Server:(.text+0x6a): undefined reference to `SSLv23_method'
    collect2: error: ld returned 1 exit status
    Error: execution of command failed with code: 1: `cc -o "/home/marcel/.cache/crystal/crystal-run-    website.tmp" "${@}"  
    -rdynamic  -lz `command -v pkg-config > /dev/null && pkg-config --libs
     libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs
     libcrypto || printf %s '-lcrypto'` -lpcre -lm -lgc -lpthread /opt/crystal/src/ext/libcrystal.a
     -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`

My distro is a debian based distro named Deepin
and my crystal version is Crystal 0.20.4 [d1f8c42] (2017-01-06)
all code of this project is viewable in my [Repo](https://github.com/inpothet/Crystal-website) that im using to sync with my desktop and laptop
Command used to run is `crystal run src/website.cr`

What could be the problem?

I tried reinstalling crystal and all the required Libaries

**Comment by RX14** [comment]
Looks like an old version of openssl. Could you find out what openssl version your distribution has?

**Comment by inpothet** [comment]
@RX14 My version of openssl is `OpenSSL 1.1.0b  26 Sep 2016`
Wierd thing is earlier this week it was working

**Comment by rdp** [comment]
is it linking against the correct openssl libs I wonder?

**Comment by inpothet** [comment]
What I could see it was but sadly the OS died about 3 weeks later

**Comment by inpothet** [comment]
What I could see it was but sadly the OS died about 3 weeks later

**Comment by inpothet** [comment]
I will check if I can get the laptop booted and will run some test

**Comment by mrkaspa** [comment]
I got a similar problem in OSX

```
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc -o "/Users/michelperez/.cache/crystal/crystal-run-dbadminser.tmp" "${@}"  -rdynamic  -lz `command -v pkg-config > /dev/null && pkg-config --libs libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs libcrypto || printf %s '-lcrypto'` -lpcre -lgc -lpthread /usr/local/Cellar/crystal-lang/0.20.5_2/src/ext/libcrystal.a -levent -liconv -ldl -L/usr/lib -L/usr/local/lib`
```

**Comment by rdp** [comment]
you should have some kind of file like

lib/libssl.a

on your system, that's what provides `SSL_library_init` at least.  If you don't have that file then make sure you have openssl "dev" libraries installed...

**Comment by mrkaspa** [comment]
That worked for me

**Comment by zatherz** [comment]
https://mta.openssl.org/pipermail/openssl-dev/2016-February/005494.html
`SSL_library_init` was removed (in favor of `OPENSSL_init_ssl`).

**Comment by akiicat** [comment]
I had the same error on `require http/client`, so I updated openssl and ensured the correct path had been linked like [this](http://stackoverflow.com/questions/15185661/update-openssl-on-os-x-with-homebrew)

```bash
export PATH=/usr/local/bin:$PATH
brew link --force openssl
```

and it's worked!!!

**Comment by asterite** [comment]
Closing because too old and needs more info. Reopen if it's still a problem.
