### ISSUE TITLE
Error while requiring "" can't find file '' relative to ''

### ISSUE THREAD

**Issue by abduct** [crystal-lang/crystal#3897]
Using Crystal 0.20.4 and Shards 0.7.1, I am unable to build a project when shards (or crystal using deps) because they add shards to the 'lib' directory and crystal still searches for the legacy 'libs` directory.

Reproducible code is to simply install the dependency and try to require it.

```
 ~/project $ crystal build project.cr
Error in project.cr:1: while requiring "text": can't find file 'text' relative to '/home/user/project'

require "text"
^

 ~/project $ mv lib libs
 ~/project $ crystal build project.cr
 ~/project $ shards --version
Shards 0.7.1 (2017-01-12)
 ~/project $ crystal --version
Crystal 0.20.4 (2017-01-12)
```

The dependency I was testing with was:

```
dependencies:
  text:
    github: johnjansen/text
    branch: master
```

Although I would imagine this would effect other dependencies as well. I am able to correct the issue by manually renaming the 'lib' directory to 'libs' and everything works as intended. Although each time I add a new dependency or update I would get this:

```
~/project $ crystal deps
Updating https://github.com/johnjansen/text.git
Shards now installs dependencies into the 'lib' folder. You may delete the legacy 'libs' folder.
Installing text (3576745e52f67ee25026db08657289810fa04bb4)
```

I am not sure if this should be considered a Shards bug since they made the move from 'libs' to 'lib' or a crystal bug for not searching directories properly for code to include.

**Comment by ysbaddaden** [comment]
Both Shards 0.7+ and Crystal 0.20+ now use the `lib` directory.

What OS are you using, how did you install Crystal?

**Comment by abduct** [comment]
Gentoo 4.7.10-hardened, and I used emerge (emerge -a dev-lang/crystal) to pull in the latest crystal version.

https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-lang/crystal/crystal-0.20.4.ebuild

**Comment by RX14** [comment]
@abduct well that ebuild is incorrect. `CRYSTAL_CONFIG_PATH` needs a `s/libs/lib/`.

**Comment by abduct** [comment]
@RX14 Thanks, modified the ebuild and currently recompiling. Will update this issue if it works as well as notify the ebuild maintainer of the issue so that this can be fixed.

**Comment by abduct** [comment]
Changing the CRYSTAL_CONFIG_PATH inside the ebuild resolves this issue. This may be closed. I will also send a email to the ebuild maintainer to notify them of this issue.

**Comment by ktaragorn** [comment]
For posterity I faced this issue with an old crystal project (using libs) which I then updated the crystal version to 0.22.0 and I faced the cannot require problem.

Fixed with a simple `mv libs lib`
