### ISSUE TITLE
Slice#hexdump fails with negative capacity (ArgumentError) for empty Slice

### ISSUE THREAD

**Issue by mjago** [crystal-lang/crystal#3906]
```crystal
empty = Slice(UInt8).empty
pp empty.size
pp empty.hexdump
```
Crystal 0.20.4 (2017-01-17)
Why is zero capacity => negative capacity?

I came across this trying to find a use for empty Slices.

**Comment by bcardiff** [comment]
The offending lines are in [src/slice.cr](https://github.com/crystal-lang/crystal/blob/master/src/slice.cr#L332-L341). If someone submit a PR please add a spec 💚 .
