### ISSUE TITLE
Add API documentation for Spec module

### ISSUE THREAD

**Issue by spalladino** [crystal-lang/crystal#3909]
Expectations, Methods and ObjectExtensions have little to no documentation in [API](https://crystal-lang.org/api/0.20.4/Spec/Expectations.html) docs.

**Comment by GloverDonovan** [comment]
What's the status of this? I wouldn't mind taking on the job. I actually like Crystal's spec (reminds me of Jasmine) and it would be great if I could learn more about it while getting better at documenting code at the same time.

**Comment by bew** [comment]
There has been some work done to document expectations on #5092 already (this will be available in the official API docs on next full release).

**Comment by GloverDonovan** [comment]
Thanks for showing me this! Is there any reason why [the API documentation](https://crystal-lang.org/api/Spec/Expectations.html) hasn't been updated yet?

I built the docs locally and it shows the new changes, so I'll be using this version for now.

**Comment by Sija** [comment]
@GloverDonovan They are, just in the [master branch](https://crystal-lang.org/api/master/Spec/Expectations.html) of api docs.

**Comment by GloverDonovan** [comment]
Didn't know about this. Thanks!

**Comment by straight-shoota** [comment]
@GloverDonovan The regular API docs will be updated as soon as 0.24.1 is relased. That should be anytime now.

**Comment by RX14** [comment]
The docs not being updated is actually a CI bug. It should have been done when `0.24.1` tag was pushed.

**Comment by asterite** [comment]
I think this can be closed:

https://crystal-lang.org/api/0.25.0/Spec/Expectations.html
