### ISSUE TITLE
Formatter: names tuple bug

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3915]
all this examples add extra spaces:

```crystal
x = {bbbbbbb: 10,
  aaaaaa:  20}

x = {haha: 10,
  a:    20}

x = {a:     10,
  bbbbb: 20}

```

**Comment by bcardiff** [comment]
The extra spaces is because of a buggy implementation while trying to align labels and the indentation.

What will be better?

a)

```crystal
x = {bbbbbbb: 10,
     aaaaaa:  20}

x = {haha: 10,
     a:    20}

x = {a:     10,
     bbbbb: 20}
```

b)

```crystal
x = {bbbbbbb: 10,
      aaaaaa: 20}

x = {haha: 10,
        a: 20}

x = {    a: 10,
     bbbbb: 20}
```

other?

**Comment by kostya** [comment]
when it newlined it formatted like this:
```crystal
x = {
  a:     10,
  bbbbb: 20,
}
```

so may be add auto newline, or a)

**Comment by RX14** [comment]
a is most consistent with what the formatter already does

**Comment by bcardiff** [comment]
This also happens with:

```
x = {:a       => 10,
  :bbbbbbb => 20}

x = {10,
  20}
```

In case someone wants to have fun with it, the fix will probably be in https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/tools/formatter.cr#L682

and the spec around
https://github.com/crystal-lang/crystal/blob/master/spec/compiler/formatter/formatter_spec.cr#L80 and
https://github.com/crystal-lang/crystal/blob/master/spec/compiler/formatter/formatter_spec.cr#L751
