### ISSUE TITLE
Keyword arguments in [] operators

### ISSUE THREAD

**Issue by ezrast** [crystal-lang/crystal#3918]
Keyword arguments can be defined for the [] operator but not used:
```cr
class Foo
  def [](**kwargs)
    puts "kwargs: #{kwargs}"
  end
end

Foo.new[]            # Works as expected; prints "kwargs: {}"
Foo.new[a: 1, b: 2]  # Syntax error: expecting token 'CONST', not '1'
```
This syntax works in Ruby.

**Comment by asterite** [comment]
Good catch, thank you! To parse those arguments the parser was using some old logic that didn't take named args into account.

**Comment by ezrast** [comment]
Appreciate the fix, but the nodes aren't getting passed into macros properly:
```crystal
macro say(arg)
    puts "{{arg}}"
end

say(foo[])           # => foo[]
say(foo[:bar])       # => foo[:bar]
say(foo[bar: :baz])  # => foo[]
```

**Comment by luislavena** [comment]
@ezrast looks to me a separate issue, macros behave differently. Please report a new one for this specific case.

Thank you.

**Comment by ezrast** [comment]
Aye aye, created https://github.com/crystal-lang/crystal/issues/4004 for this.
