### ISSUE TITLE
Custom `assert` messaging

### ISSUE THREAD

**Issue by TheLonelyGhost** [crystal-lang/crystal#3921]
---

For triage:
- `kind:feature`
- `topic:stdlib`

---

In other languages and test frameworks, running `assert` on an expression can immediately raise an `AssertionError` (or equivalent for the language) if the expression evaluates to false. Those languages also often provide an under-used option to give a failure message. See [JUnit][junit-assert], [TestNG][testng-assert], and [MIniTest][minitest-assert] for examples.

My ideal situation is as such:

```crystal
describe SomeClass do
  it "does things" do
    a = SomeClass.new
    assert !a.nil?, "it is nil"
    assert a.thing1, "cannot do thing1"
    assert a.thing2.empty?, "thing2 is not empty"
  end
end
```

Let's say the test fails. It gives me a file location and line number, but it would be infinitely easier if I could get a message in the failing test's output telling me exactly what's wrong instead of fishing through the test source code.

It appears we already have support for `assert do ... end`, but the [arguments for `def assert`][def-assert] call for the file, line, and so on. I'm concerned about the potential breaking change if a `msg` parameter is just tacked on at the beginning, even if it is set with a default value.

Can someone speak to the original intent in why `assert do ... end` instead of `assert [expression]`?

[def-assert]: https://github.com/crystal-lang/crystal/blob/ccf46c095a7e10cb120d4d04c96333858be4aaa2/src/spec/methods.cr#L39
[junit-assert]: http://junit.org/junit4/javadoc/latest/org/junit/Assert.html#assertEquals(java.lang.String,%20long,%20long)
[testng-assert]: http://testng.org/javadocs/org/testng/Assert.html#assertEquals-boolean-boolean-java.lang.String-
[minitest-assert]: http://www.rubydoc.info/stdlib/minitest/MiniTest/Assertions#assert-instance_method

**Comment by asterite** [comment]
To define a single test case you do:

```cr
it "does something" do
  # here goes your test
end
```

But in many cases you just need to assert something and don't want to bother thinking about a name for the test. In that cases you can simply do:

```cr
assert do
  # here comes your test code
end
```

Now, I originally added this to the spec framework but at this point I don't know how useful or correct it is, so I'm not against removing it. Note that the current `assert` method has nothing to do with the behaviour of the proposed `assert` in this issue.

Right now for the code you used you can do:

```cr
describe SomeClass do
  it "does things" do
    a = SomeClass.new
    a.should_not be_nil
    a.thing1.should be_truthy
    a.thing2.empty?.should be_false
  end
end
```

Whenever one of those checks fail, the spec runner will point you to the line where the assertion failed. For example when I run this code:

```cr
require "spec"

it "foo" do
  [1].empty?.should be_true
end
```

I get:

```
F

Failures:

  1) foo
     Failure/Error: [1].empty?.should be_true

       expected: true
            got: false

     # foo.cr:4

Finished in 594 microseconds
1 examples, 1 failures, 0 errors, 0 pending

Failed examples:

crystal spec foo.cr:3 # foo
```

which in my opinion is pretty useful.

**Comment by TheLonelyGhost** [comment]
> But in many cases you just need to assert something and don't want to bother thinking about a name for the test.

Ah, that makes a little more sense. In that case, wouldn't it make more sense to adopt the Rspec/Minitest approach with a bare `it do ... end` instead of `assert do ... end`? In its current form, I (as a user) make certain assumptions with a method named `assert` which apparently are very different than its intended use.

Do you have any problem with removing `assert` from the standard library if `it` can completely replace it?

**Comment by asterite** [comment]
No, not at all :-)

I didn't know RSpec allowed argless `it`, we could probably do the same and remove `assert` (maybe *eventually* adding it back but with another meaning, more similar to, say, Elixir's `assert`, if possible (but currently it's very hard))

**Comment by TheLonelyGhost** [comment]
`it` without arguments in RSpec ends up trying to infer a message from the contents of the block. I'm currently drafting a pull request which would just default it to "assert" instead of that (at this point) needless complication of parsing the AST to derive a default message.

Will open a PR as soon as I have passing tests.

**Comment by TheLonelyGhost** [comment]
#3922 is merged and I'm satisfied with the discussion with @asterite.

Only remaining preference might be showing evaluated values in failure messages, similar to how Elixir handles LHS (left-hand side) and RHS (right-hand side) evaluations, but that should probably merit its own discussion, planning, and pull request in a separate issue.

:+1:
