### ISSUE TITLE
Status code 500 in doc page API - 0.20.5 - Reflect

### ISSUE THREAD

**Issue by blocknotes** [crystal-lang/crystal#3928]
URL: [https://crystal-lang.org/api/0.20.5/Reflect.html](https://crystal-lang.org/api/0.20.5/Reflect.html)

In 0.20.4 it works.

**Comment by RX14** [comment]
I don't get a 500 error, but `Reflect(X)` is supposed to be `:nodoc:`. Cherry-picking [this commit](https://github.com/crystal-lang/crystal/pull/3595/commits/ed97701223c4a9a32c9327c04e0642a433709906) would fix that.

**Comment by blocknotes** [comment]
You are right. It works now. I don't know, but I close this
