### ISSUE TITLE
Problem with Hash's hash codes truncation

### ISSUE THREAD

**Issue by MaxLap** [crystal-lang/crystal#3932]
When a hash is looking for a bucket, it does the following:
`key.hash.to_u32.remainder(@buckets_size).to_i`

The to_u32 means that a large portion of the key may be ignored! A very clear example of this problem is with floats of whole numbers:
```
(0..9).each do |i|
  puts "#{i.to_f}: #{i.to_f.hash.to_u32} | #{i.to_f.hash.to_s(2)}"# if i.to_f.hash.to_u64.to_u32 != 0
end
```

The result shows that all of those floats' effective hash code is 0 (The problem continues in the thousands and above):
```
# float: effective hash code | binary of the original hash code
0.0: 0 | 0
1.0: 0 | 11111111110000000000000000000000000000000000000000000000000000
2.0: 0 | 100000000000000000000000000000000000000000000000000000000000000
3.0: 0 | 100000000001000000000000000000000000000000000000000000000000000
4.0: 0 | 100000000010000000000000000000000000000000000000000000000000000
5.0: 0 | 100000000010100000000000000000000000000000000000000000000000000
6.0: 0 | 100000000011000000000000000000000000000000000000000000000000000
7.0: 0 | 100000000011100000000000000000000000000000000000000000000000000
8.0: 0 | 100000000100000000000000000000000000000000000000000000000000000
9.0: 0 | 100000000100010000000000000000000000000000000000000000000000000
```

As a result of those keys' hash codes being effectively 0, they all land in the same bucket of the hash. This means a hash of integer floats like this one has the performances of a linked list.

**Comment by akzhan** [comment]
Good points to start:

https://hg.python.org/cpython/file/1eee26b74e4b/Python/pyhash.c#l86

**Comment by straight-shoota** [comment]
Can this be closed?

**Comment by akzhan** [comment]
No, while Hash is not replaced with new one.

**Comment by asterite** [comment]
This can be closed, there's no `to_u32` call anymore in the source code.
