### ISSUE TITLE
Partial static compile

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#3933]
I'm trying to static compile OpenSSL into my project.

Makefile is at: https://github.com/bararchy/sslscanner/blob/master/Makefile

It crashes with:
```bash
make[1]: Entering directory '/home/unshadow/Desktop/git-projects/sslscanner'
crystal build bin/scan.cr --release	--link-flags "-static -L/home/unshadow/Desktop/git-projects/sslscanner/openssl/ -I/home/unshadow/Desktop/git-projects/sslscanner/openssl/include/ -I/home/unshadow/Desktop/git-projects/sslscanner/openssl/  -DVERSION=\"a52ddef-wip-static\" -lssl -lcrypto -lz -ldl -I/usr/lib/ -lpcre -levent"
/home/unshadow/Desktop/git-projects/sslscanner/openssl//libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x20): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: cannot find -lpcre
/usr/bin/ld: cannot find -levent
/usr/bin/ld: cannot find -lpcre
/usr/bin/ld: cannot find -levent
_main.o: In function `~procProc(Nil)@src/sslscanner.cr:23':
main_module:(.text+0x1bd79): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status

```

I'm not really sure where to go from here :\ 
Any help would be appreciated  :)

**Comment by kirbyfan64** [comment]
Looks like your system doesn't have the static libraries for PCRE and libevent, so you'll probably have to build them yourself.

Static linking on Linux is basically a can of decaying worms. You might have better luck trying something like [AppImage](http://appimage.org).

**Comment by bararchy** [comment]
Can't I use only what I have statically for the static linking and libevent and libpcre as dynamic linking ?

**Comment by ysbaddaden** [comment]
You must specify a full path to the static libraries to include at link time. Passing them with `--link-flags` won't work, because the `-lcrypto` and `-lssl` are still specified, and the linker will search for shared libraries by default, and only use the specified static libraries if shared libraries can't be found.

**Comment by bararchy** [comment]
@ysbaddaden If I can't use --link-flags to link them , where and how should I specify full path ?

**Comment by bararchy** [comment]
So, I compiled all the needed libs staticlly and moved the `.a` files to the needed path 

```
make sslscanner STATIC_BUILD=TRUE
make[1]: Entering directory '/home/unshadow/Desktop/git-projects/sslscanner'
crystal build bin/scan.cr --release --link-flags "-static -L/home/unshadow/Desktop/git-projects/sslscanner/openssl/ -I/home/unshadow/Desktop/git-projects/sslscanner/openssl/include/ -I/home/unshadow/Desktop/git-projects/sslscanner/openssl/ -I/home/unshadow/Desktop/git-projects/sslscanner/openssl/pcre/  -DVERSION=\"bff04da-wip-static\" -lssl -lcrypto -lz -lpcre -levent -ldl -I/usr/lib/"
/home/unshadow/Desktop/git-projects/sslscanner/openssl//libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x20): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
_main.o: In function `~procProc(Nil)@src/sslscanner.cr:23':
main_module:(.text+0x1bd79): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/home/unshadow/Desktop/git-projects/sslscanner/openssl//libevent.a(evutil.c.o): In function `evutil_getaddrinfo_common_':
evutil.c:(.text+0x2521): warning: Using 'getprotobynumber' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
evutil.c:(.text+0x2350): warning: Using 'getservbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

```

The good thing is, it seems that it worked :) , when using ldd on the file it says "not a dynamic executable" and the file size is big, 4mb big.

The bad thing is, the program it self now crashes with: 

```
Usage: ./scan [host] [port]
Invalid memory access (signal 11) at address 0x0
[4338694] ???
[4269518] ???
[6298832] ???
[0] ???
```

**Comment by kirbyfan64** [comment]
See, I told you static linking on Linux was a can of worms!! ;)

What if you try using the nightly version of Crystal with `-g`?

**Comment by bararchy** [comment]
@kirbyfan64 lol you did say that XD 

What does `-g` does ? I'll pull Crystal head now.

**Comment by bararchy** [comment]
@kirbyfan64 Git HEAD installed, not seeing a `-g` option anywhere

**Comment by kirbyfan64** [comment]
Oops, I'm an idiot. I meant `-d`. It puts debugging symbols in the program so it'll tell you where it crashed.

**Comment by bararchy** [comment]
@kirbyfan64 No worries :) 

With `-d` the build crashes without even completing the compile process :

```
Invalid memory access (signal 11) at address 0x1c
[94918406654550] ???
[94918397372782] __crystal_sigfault_handler +30
[139702843957376] ???
[139702865736583] _ZNK4llvm3DIE13getUnitOrNullEv +23
[139702865843452] _ZN4llvm10DwarfDebug25finishVariableDefinitionsEv +108
[139702865843720] _ZN4llvm10DwarfDebug18finalizeModuleInfoEv +72
[139702865881014] _ZN4llvm10DwarfDebug9endModuleEv +38
[139702865682656] _ZN4llvm10AsmPrinter14doFinalizationERNS_6ModuleE +512
[139702860814617] _ZN4llvm13FPPassManager14doFinalizationERNS_6ModuleE +73
[139702860865237] _ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE +869
[139702874707399] ???
[139702874708052] LLVMTargetMachineEmitToFile +228
[94918403628025] ???
[94918403173871] ???
[94918397505666] ???
[94918397370116] main +11348
[139702821446289] __libc_start_main +241
[94918397271258] _start +42
[0] ???

```

**Comment by kirbyfan64** [comment]
Well, looks like you accidentally found a bug in Crystal... :/

What do you get when you run `ls -al $(which ld)`?

**Comment by bararchy** [comment]
@kirbyfan64 

```
-rwxr-xr-x 4 root root 553 Aug  2  2015 /usr/lib/hardening-wrapper/bin/ld

```

Btw, I found out that the issue when static compiling (not using `--debug`) is the resolve function (getaddressinfo) , when using IP for the sockets I can make the program work.

**Comment by kirbyfan64** [comment]
@bararchy Ah, ok. I had thought you might be using the gold linker, which can have bugs with static linking, but you aren't...

You must have fallen victim to [this](https://sourceware.org/bugzilla/show_bug.cgi?id=10652) glibc. Unfortunately, there is no known fix for the bug, which has been open for over three years.

Only other idea I have is to try to build a copy of musl (a glibc alternative) and use that instead, since it tends to be tamer when static linking...but you'll have to also rebuild libevent, libgc, and all the rest of Crystal's dependencies in order for that to work properly.

I'm dead serious when I say that you really should try AppImage...

**Comment by r-obert** [comment]
@kirbyfan64 with AppImage, are the shared libraries bundled within the app?

**Comment by kirbyfan64** [comment]
@r-obert Yes.

**Comment by r-obert** [comment]
@kirbyfan64 wow. that's a huge step for commercial software on linux besides just being generally awesome for distributing OSX-style "apps" on linux. great link, thank you.

**Comment by bararchy** [comment]
Closing as it seems to be an issue with general static compiling and not Crystal specific.
