### ISSUE TITLE
'crystal play' vs some kinds of user errors.

### ISSUE THREAD

**Issue by drosehn** [crystal-lang/crystal#3935]
Running:
```cr
# crystal version
Crystal 0.20.4 (2017-01-07)
```

I wanted to use 'crystal play' to make a quick test of something.  What I typed in included the line:
```cr
aa = Hash.new
```
Obviously my brain was still in RubyMode.  The window spun around a bit, and then stopped without telling me anything (not even for the lines which were before this line).  I then remembered "oh, yeah, in crystal I need to specify the type to use for the key"), so I went:
```cr
aa = Hash(Float).new
```
... and again the page spun around, and stopped without showing me anything.  So I slap my head again, and said "Oh, right, and I need to specify the type for the value too!".  Which got me to:
```cr
aa = Hash(Float, Int).new
```
... and again there was no feedback in the web browser window.  So this time I typed the lines into a file and had crystal compile it at the command line.  And this time I got the full error message, and realized the line should be:
```cr
aa = Hash(Float64, Int32).new
```
I put that back into the web-browser window, and everything else worked fine.

In addition to proving that I should have stayed home today, I wonder if something is wrong such that error messages do not show up when using `crystal play`.  Or maybe the problem is just for some types of errors.

**Comment by bcardiff** [comment]
This should be a duplicate of #3884 . Crystal 0.20.5 was released and you should be able to see nice errors in the appropriate line for this

**Comment by drosehn** [comment]
In other news, I'm having trouble installing 0.20.5 using `brew` on my Mac (as I mentioned on gitter just before posting this...).

**Comment by drosehn** [comment]
Once I upgraded to version 0.20.5, all of these examples displayed helpful error messages.  Thanks!
