### ISSUE TITLE
Capitalizing Exception messages

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#3944]
When using Crystal I've noticed that `Exception` messages have mixed casing throughout the code. In certain places they're being written lowercased (see `EOFError#initialize`), while at others being capitalized (see `Hash#fetch`).

If there's a will to standarize it I can send a PR changing all of them to one specified form - for example capitalizing all of them (which seems to me as more elegant since error messages, longer ones at least, tend use sentence-casing anyway).

**Comment by matiasgarciaisaia** [comment]
I think this should be a convention to follow rather than some code we should write. Writing logic for handling this cases doesn't seem wise. Maybe linting, but not more than that.

That PR to fix the current codebase would be great, though :)

**Comment by Sija** [comment]
Closed by #3956
