### ISSUE TITLE
mybe is a bug?

### ISSUE THREAD

**Issue by lgphp** [crystal-lang/crystal#3951]
```crystal
macro http_get(param, fn)
   #  puts {{fn}}   #here show error message : wrong number of arguments for 'index' (given 0, expected 2)
   #  puts {{param}} #=> “/”
      res,req = return_httpcontext  #return httpcontext exp:request,response...
      fn = -> {{fn}} (String,String)
      fn.call(res, req)
end

def return_httpcontext
  {"response", "request"}
end

def index(res, req)
  puts res, req # here can use : req.body["var1"] or req.query["id"] or res.setxxx
end

# i think make a  way like express's route(node's webframework) that pass a function to macro
# example: http_get "/news/:id" , show_news

http_get "/", index     # the "index" has not defined ,but it can passed to macro? why?

# i wonder the program can be run....

```

if this way is avaliable,then just can pass any function name to macro. can realize follow...

http_get "/login" , middware1,middware2... , action

**Comment by bmmcginty** [comment]
(I'll be glad to delete the following if it's unhelpful, misleading, etc. If a dev wants to do so, please feel free.)
You want to read (if you haven't already):
https://github.com/crystal-lang/crystal-book/blob/master/syntax_and_semantics/macros.md
Also check (in the crystal repo):
src/compiler/crystal/macros.cr

Macros are a tad complicated. The below is my explanation, not necessarily the best one.
You are writing in a macro.
That means that your line:
```puts {{fn}}   #here show error message : wrong number of arguments for 'index' (given 0, expected 2)```
is turned into:
```puts index   #here show error message : wrong number of arguments for 'index' (given 0, expected 2)```
Index gets called with zero arguments.
When you put {{fn}} into your macro, it's really doing ```index```.

When you call http_get with index, the compiler sees that index refers to a function, and gives the macro a node of type Call.
If you called it with say the number 3, like http_get(3), the macro would get fn passed to it, as a NumberLiteral type.
In a macro, when you're doing {{something}}, whatever you've passed into the node with the name something replaces the {{something}}.

You can look up NumberLiteral and Call in the macros.cr file above.

As to your last line, you could change your macro to:
```
macro http_get(param, *fns)
      res,req = return_httpcontext
{% for fn in fns %}
fn = -> {{fn}} (String,String)
res,req=fn.call(res, req)
#you could check ret to see if it's nil, or catch exceptions here
{% end %}
{res,req}
end
```
This will let you pass any number of methods to http_get.
I'm assuming here that each handler will return the {res,req} passed to it.

**Comment by r-obert** [comment]
@lgphp no one can make sense of this issue now because you edited the original description to just be "g". please don't do that.
