### ISSUE TITLE
instance variable was not initialized in all of the 'initialize' methods, rendering it nilable

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3964]
https://play.crystal-lang.org/#/r/1le9

this is seems related to finished macro

**Comment by ysbaddaden** [comment]
Please copy-paste the failing example in the issue:

```crystal
class A1
  macro finished
    @x : String
    def initialize(@x)
    end
  end
end

class A2
  macro finished
    @y : Int32
    def initialize(@y)
    end
  end
end

p A1.new ""
p A2.new 10
```

**Comment by asterite** [comment]
@kostya What was your use case here, do you remember?

**Comment by kostya** [comment]
no

**Comment by kostya** [comment]
now i remember why this needed, for auto_constructor and auto_json shards, which generate instance variables from array. I not use this shards anymore, because many problems with them.
