### ISSUE TITLE
Using `/` in a case/when 

### ISSUE THREAD

**Issue by manveru** [crystal-lang/crystal#3965]
This simple example fails to compile with `Syntax error in :3: unexpected token: DELIMITER_START
CLOSE`.

```crystal
case a
  when b
    1 / 1
end
```

Version: `Crystal 0.20.5 (2017-01-27)`
OS: NixOS

**Comment by dylandrop** [comment]
https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/syntax/parser.cr#L2314 and the related `slash_is_regex!` calls appear to be the offender. Seems like this might require somewhat of a larger change to the `parse_case` method.
