### ISSUE TITLE
correct way in macro, to check that type is nilable?

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3966]
i need to check that type nilable or not to generate better code, how better do it:
this looks ugly and not working: https://play.crystal-lang.org/#/r/1lec
is there any other way?

**Comment by Sija** [comment]
There's `Class/Union.nilable?` and AFAIK you could use it just like `({{x}}).nilable?` - see https://play.crystal-lang.org/#/r/1leg

**Comment by kostya** [comment]
this is runtime check, i need macro check

**Comment by Sija** [comment]
huh, that complicate things... ;) Since `(Int32 | Nil)` is of type `Call` I'm not sure how would be possible to get resulting type at that stage... only thing I've managed to come up with is a slight modification to your hack in form of `x.stringify =~ /Nil/`...

**Comment by kostya** [comment]
but it can be Array(Nil), which is not nil able

**Comment by Sija** [comment]
```cr
x.stringify =~ /(\s\|\s|^|Union.+?)\(?(::)?Nil\)?/
```
almost works... see https://play.crystal-lang.org/#/r/1lfz :)
real solution of course would to have a compile-time check for this.

**Comment by asterite** [comment]
@kostya What is "generate better code or not"?

**Comment by kostya** [comment]
if type nilable i want to generate line
`def initialize(bla : Int32? = nil)`, if not nilable i want to generate line: `def initialize(bla : Int32)`

**Comment by asterite** [comment]
@kostya ?

**Comment by kostya** [comment]
i solve it in another way
