### ISSUE TITLE
Iconv does not work on alpine linux

### ISSUE THREAD

**Issue by mosop** [crystal-lang/crystal#3974]
I'm not familiar with it, but, probably, musl libc does not support //IGNORE suffix.

my patch:

```diff
diff --git a/src/iconv.cr b/src/iconv.cr
index d1a824e..acd7bcb 100644
--- a/src/iconv.cr
+++ b/src/iconv.cr
@@ -8,7 +8,7 @@ struct Iconv
     original_from, original_to = from, to
 
     @skip_invalid = invalid == :skip
-    {% unless flag?(:freebsd) %}
+    {% unless flag?(:freebsd) || flag?(:musl) %}
     if @skip_invalid
       from = "#{from}//IGNORE"
       to = "#{to}//IGNORE"
```

alpine linux: 3.5
crystal: 0.20.5

**Comment by ysbaddaden** [comment]
I know musl-libc doesn't support `//TRANSLIT` but there is nothing said about `//IGNORE`.

**Comment by ysbaddaden** [comment]
Looking at the implementation, there is no support for the `//IGNORE` nor `//TRANSLIT` extenstions:
http://git.musl-libc.org/cgit/musl/tree/src/locale/iconv.c

**Comment by mosop** [comment]
thank you!
