### ISSUE TITLE
Compiler can't find implementation of abstract method if there is a yield with params

### ISSUE THREAD

**Issue by baltavay** [crystal-lang/crystal#3975]
Compiler can't find implementation of abstract method if there is a yield with params

error message:
```crystal
Error in test.cr:2: abstract `def Transport#each_passenger(&block)` must be implemented by Car

 abstract def each_passenger(&block)

```
code:
```crystal
abstract class Transport
  abstract def each_passenger(&block)
end

class Car < Transport

  def initialize(@passengers : Array(String))
  end

  def each_passenger(&block)
    @passengers.each do |passenger|
      yield passenger
    end
  end
end

car = Car.new(["Adam", "Jack", "Rose"])

car.each_passenger do |passenger|
  puts passenger
end

```

**Comment by ezrast** [comment]
As I understand it, the `&block` taken by `Car#each_passanger` is implicitly a `&block : String -> Nil`. You need to define `Transport#each_passenger` to match:
```crystal
abstract def each_passenger(&block : String -> Nil)
```
Otherwise the methods really do have different signatures, which the compiler should probably do a better job of pointing out.

**Comment by asterite** [comment]
@ezrast Is correct here, you need to specify the full signature, because `&block` when used as a type specifier means a block that doesn't yield anything, and whose return type doesn't matter.

**Comment by baltavay** [comment]
@ezrast, @asterite  thanks. I didn't properly lookup in docs.
