### ISSUE TITLE
Better error message for missing optional-groups access in Regex

### ISSUE THREAD

**Issue by spalladino** [crystal-lang/crystal#3978]
The following code fails with a `Nil assertion failed`:
```crystal
/(A)?B/ =~ "B"
p $1
```

Full stack trace being:
```
Nil assertion failed (Exception)
0x10f4205a2: *CallStack::unwind:Array(Pointer(Void)) at ??
0x10f420541: *CallStack#initialize:Array(Pointer(Void)) at ??
0x10f420518: *CallStack::new:CallStack at ??
0x10f41c521: *raise<Exception>:NoReturn at ??
0x10f41c501: *raise<String>:NoReturn at ??
0x10f4331f3: *Nil#not_nil!:NoReturn at ??
0x10f44d34e: *Regex::MatchData#[]<Int32>:String at ??
0x10f41c0d0: __crystal_main at ??
0x10f41f958: main at ??
```

This happens because the first capturing group was optional, and not present in the current match, so when tried to be cast to `String` it fails. Note that using `String?` works.

However, the error message should be more descriptive (similar to the `Missing hash key` when accessing a hash) to avoid confusion. See #3971 for example.

**Comment by akzhan** [comment]
I believe that this issue should be closed.

**Comment by asterite** [comment]
Indeed, this seems to be fixed. @akzhan Thank you!
