### ISSUE TITLE
Document usage of `$1?` syntax for accessing optional capture groups in a Regex match

### ISSUE THREAD

**Issue by spalladino** [crystal-lang/crystal#3979]
The `$1?` syntax for accessing a capture group as a `String?` is not documented in the API. Add a note on it in https://crystal-lang.org/api/0.20.5/Regex.html.

See #3978 for more info.

**Comment by drosehn** [comment]
Do you have the **output** of an example program which uses the `$1?` syntax to handle the optional-capture-group from a regex?  If you were to rewrite the section of code in #3971 , what should it look like?

**Comment by spalladino** [comment]
Fixed in https://github.com/crystal-lang/crystal/pull/4023
