### ISSUE TITLE
process_spec fails because of missing /usr/bin/touch

### ISSUE THREAD

**Issue by mosop** [crystal-lang/crystal#3980]
tested on alpine linux: 3.5, crystal: 0.20.5

my patch:

```diff
diff --git a/spec/std/process_spec.cr b/spec/std/process_spec.cr
index 31b530f..4ee1e8f 100644
--- a/spec/std/process_spec.cr
+++ b/spec/std/process_spec.cr
@@ -178,7 +178,7 @@ describe Process do
     File.exists?(tmpfile.path).should be_false

     fork = Process.fork do
-      Process.exec("/usr/bin/touch", {tmpfile.path})
+      Process.exec("/usr/bin/env", {"touch", tmpfile.path})
     end
     fork.wait
```

**Comment by drosehn** [comment]
Where is the `touch` utility located on alpine linux?  (I'm just curious).
Is in `/bin/touch`?

**Comment by mosop** [comment]
exactly!

**Comment by Bew78LesellB** [comment]
Instead of using the `touch` binary, shouldn't we use direct syscall to replicate the same  effect?

**Comment by RX14** [comment]
@Bew78LesellB because the spec is trying to test running binaries...

**Comment by Bew78LesellB** [comment]
Oh my bad...  Sorry about that.. 
I'm make sure to read the contexte next time!

**Comment by rdp** [comment]
does crystal have a built-in "touch" method anywhere? Sorry to ask here, google just sent me straight here when googling "crystal lang touch" :)

**Comment by Sija** [comment]
@rdp nope, not yet ;)

**Comment by luislavena** [comment]
@Sija @rdp now with `File.utime` it could be possible to implement, pull requests are welcome :wink:

**Comment by Sija** [comment]
@luislavena with pleasure, see #4069 😉
