### ISSUE TITLE
Gzip / Deflate initialize with a block

### ISSUE THREAD

**Issue by sdogruyol** [crystal-lang/crystal#3981]
I'm trying to update Kemal to support Crystal next but unfortunely `Gzip::Writer` / `Flate::Writer` can't be initialized with a block which prohibits me from using `IO.copy` without creating an intermediate `IO::Memory` thus leading to performance penalty

Before

```crystal
Zlib::Deflate.gzip(context.response) do |deflate|
   IO.copy(file, deflate)
end
```

Now

```crystal
io = IO::Memory.new
deflate = Gzip::Writer.new(io)
deflate.print(context.response)
io.rewind
IO.copy(file, deflate)
```

**Comment by asterite** [comment]
https://github.com/crystal-lang/crystal/blob/master/src/gzip/writer.cr#L18-L20

**Comment by asterite** [comment]
In case the code goes old, the way to do it is using `open`:

```crystal
Gzip::Writer.open(...) do |gzip|
end
```
