### ISSUE TITLE
Cannot call #[] methods with block

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#3994]
```cr
class Foo
  INSTANCE = new

  def []?(option)
    yield
  end

  def [](option)
    yield
  end
end

Foo::INSTANCE[:foo] { puts :foo }
Foo::INSTANCE[:foo]? { puts :bar }
```

Above code fails to compile with SyntaxError:
```
unexpected token: {
```

**Comment by asterite** [comment]
This was never intended to work. By the way, it also gives a syntax error in Ruby too. The `#[]` method is a hash/array accessor, it's not like a regular block. In any case I'll discuss it with the team, but I don't think we'll want to add this to the language. You can, however do `Foo::INSTANCE.[](:foo} { ... }`

**Comment by asterite** [comment]
Let's not implement this.
