### ISSUE TITLE
OptionParser fail to match for non-dashed flags

### ISSUE THREAD

**Issue by chyzwar** [crystal-lang/crystal#4001]
According to docs dash is optional `Flags can (but don't have to) start with a dash. `
In my case I want to have create flag that would behave as sub-command. 

Minimal case to reproduce:  https://play.crystal-lang.org/#/r/1lvk
```crystal
require "option_parser"

parser = OptionParser.new do |p|
  p.on("-c NAME", "--create NAME", "build something") do |name|
    puts "creating #{name}"
  end
  
   p.on("create NAME", "build something") do |name|
    puts "creating #{name}"
  end
end

 
#Output should be the same by second case fail to match
parser.parse %w(--create awesome)
parser.parse %w(create awesome)
```

I would expect that that dash is optional in all forms of flag. 
@luislavena  thanks for help on code example.

**Comment by Bew78LesellB** [comment]
Related to #3357

**Comment by asterite** [comment]
The docs are wrong, arguments must have dashes
