### ISSUE TITLE
Missing type LibC::UIntptrT

### ISSUE THREAD

**Issue by Rinkana** [crystal-lang/crystal#4016]
```crystal
lib FooLib
  fun bar(baz: UIntptrT*) : Void
end
```
The LibC library does not have a mapping for the C type `uintptr_t`. I came across it when mapping OpenGL types.

**Comment by straight-shoota** [comment]
`LibC` bindings in stdlib are not a complete representation of all libc features. It only includes what's used in stdlib. The entire `LibC` bindings are also undocumented, so not part of the public API.

If you want to libc bindings you should declare them yourself.
