### ISSUE TITLE
TCPSocket with blocking = false still blocks

### ISSUE THREAD

**Issue by shelvacu** [crystal-lang/crystal#4018]
```crystal
require "socket"

PORT = 1234

spawn do
  serv = TCPServer.new(PORT)
  serv.accept
end

sleep(1)

sock = TCPSocket.new("127.0.0.1", PORT)
sock.blocking = false
buff = Bytes.new(100)
sock.read(buff) # This blocks forever, despite blocking = false

puts "This is never printed"
```

As long as I'm understanding the functionality of `#blocking=` correctly, I believe this is a bug.

Crystal 0.20.5+69 [a78d44da3] (2017-02-11), Arch Linux x86_64

**Comment by asterite** [comment]
The `blocking` property (which is not documented, and in the future will probably be hidden) controls whether the file descriptor (socket here) is non-blocking or not. If blocking is false it means it's non blocking, meaning that when there's no incoming data the runtime scheduler will put the current fiber in a queue and then continue with another fiber, and resume the other one when data arrives.

I think you want something like `read_partial` from Ruby, like "don't put the fiber on a queue if there's no data". Unless I'm mistaken (@waj can correct me here) there's no such functionality in Crystal. And I'm not sure it's really needed.

What program are you trying to build?

**Comment by shelvacu** [comment]
Trying to build a simple server, like

```
loop do
  begin 
    client.read_nonblock
    process_data
  rescue EWOULDBLOCK
  end
  do_other_tasks
end
```

There are certainly better ways of writing such a program, so I doubt it's worth accommodating for.

**Comment by asterite** [comment]
Yes, you want to different independent paths of execution, that's what `spawn` is for:

```crystal
# Here we process the socket
spawn do
  loop do
    line = client.gets
    process_data
  end
end

# Here we do some other tasks
spawn do
  loop do
    do_other_tasks
  end
end
```
