### ISSUE TITLE
Move Crypto::MD5 to Digest and consolidate its API 

### ISSUE THREAD

**Issue by Papierkorb** [crystal-lang/crystal#4021]
Hello,

Right now `MD5` lives in the `Crypto` module, while `SHA1` lives in the `Digest` module.
I think the latter would be a better fit for `MD5`. Further, I'd love to see the `MD5` API to mirror the one of `SHA1`:

| Digest::SHA1 | Crypto::MD5 |
|---------|--------|
| Is a **module** | Is a **class** |
| `Context` is **private** | `Context` is **public** |
| `.digest(String | Bytes)` | *Doesn't exist* |
| `.hexdigest(String | Bytes)` *No underscore* | `.hex_digest(String | Bytes)` *Has underscore* |
| *Doesn't exist* | `.hex_digest()` **with yield** |
| `.base64digest(String | Bytes)` | *Doesn't exist* |

I'd thus like to do:

1. Move `MD5` to `Digest`
1. Make both a module OR a class
2. Rename `hex_digest` to `hexdigest`
3. Add missing methods (from above) to both of them

I could work on this, though I'd like to get community feedback first before wasting everyones time :)

Cheers!

**Comment by r-obert** [comment]
great analysis and breakdown of the differences between the two! 
fwiw in Ruby it's Digest::MD5 and Digest::SHA1.

**Comment by RX14** [comment]
I'm always hesitant to use crystal implementations of crypto functions, mainly because of the possibility of timing attacks. AFAIK openssl uses mostly hand-written assembly to help ensure this constant-time.

**Comment by ysbaddaden** [comment]
MD5 has nothing to do in Crypto land. Digest is a better place.

**Comment by Papierkorb** [comment]
Thanks y'all for the positive feedback.  I'll work on it tomorrow (Tuesday) then.

**Comment by Papierkorb** [comment]
As #4037 was merged (Thanks), I'll close this.
