### ISSUE TITLE
Clearing out ~/.cache/crystal

### ISSUE THREAD

**Issue by drosehn** [crystal-lang/crystal#4032]
In the crystal channel on Gitter, the following observation was made:
> Not very scientific, but how long should p "hello world" take to return in crystal play? Mine takes around 20 seconds. Not sure if it's related to crystal-lang/crystal#4022 but it's slow in 0.20.4 as well. Tried changing the port, incase I was getting some network issues, but it didn't help.

Followed a few minutes later by:
> Just deleted my ~/.cache/crystal files. Seems to have fixed it. Now taking < 3 seconds
> The cache took an age to delete, must have been very big.

That got me wondering about the `~/.cache/crystal` directory under my own userid.  If I start up a `crystal play` session right now, I have 8 lines in it (although three of those lines are in a loop which gets executed six times).  And my  `~/.cache/crystal/playground` directory has 993 files in it, with last-change dates going back to Jul 23  2016.  Does anything ever clear out that directory?

Also, the  `~/.cache/crystal` directory has 5300 files (right in that directory, not counting any subdirectories), but the oldest file there is from Jan 23 2017.  That seems like a lot of files, given the largest crystal program that I've written is 1200 lines!  And it looks like all of my crystal programs put together amount to under 4000 lines.

Should I be doing a `rm -rf ~/.cache/crystal` every week or so?

**Comment by drosehn** [comment]
Given that I have upgraded crystal several times in the last two months, I'd think that any cached file which is more than a few weeks old couldn't be of any use anyway...

**Comment by asterite** [comment]
This should be fixed in master, but besides that, what happens to you if you don't delete the cache directory for months?

**Comment by drosehn** [comment]
My question was based on the original comment I quoted:  A "Hello world" program in `crystal play` takes 20 seconds to compile instead of 3.  That might be specific to the playground, and not the cached files from normal `crystal build` runs, but it seemed noteworthy.

**Comment by asterite** [comment]
Yes, the cache generated lots of `macroNNN` files, maybe that caused a slowdown? I can't imagine why having more files in a directory would result in slower compilations... in any case, this should be fixed in master :-)

**Comment by drosehn** [comment]
If the compile works by creating random filenames, and then it checks that filename and finds that it already exists, then you can get into a loop just trying to find an unused random name.  I've run into this on some of our remote-access unix machines.  We have many users logging in to those machines, and there was a bug where krb-ticket files were not being removed when people logged out.  It was pretty amazing how much of a delay that caused for logins after a few months!  But that's just a guess on my part.

Thanks for the quick fix!
