### ISSUE TITLE
Add non-allocating method to SecureRandom

### ISSUE THREAD

**Issue by konovod** [crystal-lang/crystal#4049]
Right now, all variants of `SecureRandom.random_bytes` include `Bytes.new(n)` call, so it should be easy to make a non-allocating version that fill existant `Bytes` with random bytes and just call it with Bytes.new in old function.
   It is useful e.g. for a server that use SecureRandom nonce for every request and can generate a lot of garbage now.
   I think i can create PR (to don't bother anyone else with implementation), but i'm not familiar with git so it will take some time.

**Comment by RX14** [comment]
See https://github.com/crystal-lang/crystal/pull/3434#discussion_r83747954

**Comment by ysbaddaden** [comment]
Yes, `SecureRandom.random_bytes` should accept a `Bytes` of any size, that other overloads would rely on. It would allow to reuse an existing allocation or to allocate on the stack, and speed things up.
