### ISSUE TITLE
Implement required method from module in another included module

### ISSUE THREAD

**Issue by Nephos** [crystal-lang/crystal#4052]
Hello,

This code produce the error 
``Error in a.cr:2: abstract `def B#x()` must be implemented by A``

Is it the expected behavior ?

I think it is relative to https://github.com/crystal-lang/crystal/issues/418 in some way.

```crystal
# B requires to define x
module B
  abstract def x
end

# C defines x
module C
  def x
    :x
  end
end

# A includes C (which defines x) and C (which requires x)
class A
  include C
  include B
end

A.new
```

**Comment by luislavena** [comment]
Hello @Nephos, have you tried altering the order in which modules are included?

```crystal
class A
  include B # requirement
  include C # fulfill requirement
end
```

But that is the only scenario that doesn't work, since both `include` + `def` and `def` + `include` works.

Considering that you can include a module that hasn't yet be defined, perhaps the check should be deferred?
