### ISSUE TITLE
Unexpected uninformative error when using IGNORE_CASE with a complex Regex

### ISSUE THREAD

**Issue by ujifgc** [crystal-lang/crystal#4053]
Here is a use case:

https://play.crystal-lang.org/#/r/1np6

```ruby
SRC_ANY = "[\0-\uD7FF\uE000-\uFFFF]"
SRC_CC  = "[\0-\u001F\u007F-\u009F]"
SRC_Z   = "[ \u00A0\u1680\u2000-\u200A\u2028\u2029\u202F\u205F\u3000]"
SRC_P = "[!\"#%&'()*,\\-\\./:;?@\\[\\\\\\]_{}]"
SRC_Z_P_CC = [ SRC_Z, SRC_P, SRC_CC ].join('|')
SRC_Z_CC = [ SRC_Z, SRC_CC ].join('|')
SRC_PSEUDO_LETTER       = "(?:(?!" + SRC_Z_P_CC + ")" + SRC_ANY + ")"
SRC_PSEUDO_LETTER_NON_D = "(?:(?![0-9]|" + SRC_Z_P_CC + ")" + SRC_ANY + ")"
SRC_IP4   = "(?:(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"
SRC_AUTH  = "(?:(?:(?!" + SRC_Z_CC + ").)+@)?"
SRC_PORT  = "(?::(?:6(?:[0-4]\\d{3}|5(?:[0-4]\\d{2}|5(?:[0-2]\\d|3[0-5])))|[1-5]?\\d{1,4}))?"
SRC_HOST_TERMINATOR = "(?=$|" + SRC_Z_P_CC + ")(?!-|_|:\\d|\\.-|\\.(?!$|" + SRC_Z_P_CC + "))"

SRC_PATH = 
  "(?:" +
    "[/?#]" +
      "(?:" +
        "(?!" + SRC_Z_CC + "|[()\\[\\]{}.,\"'?!\\-]).|" +
        "\\[(?:(?!" + SRC_Z_CC + "|\\]).)*\\]|" +
        "\\((?:(?!" + SRC_Z_CC + "|[)]).)*\\)|" +
        "\\{(?:(?!" + SRC_Z_CC + "|[}]).)*\\}|" +
       %{\\"(?:(?!} + SRC_Z_CC + %{|["]).)+\\"|} +
        "\\'(?:(?!" + SRC_Z_CC + "|[']).)+\\'|" +
        "\\'(?=" + SRC_PSEUDO_LETTER + ").|" +
        "\\.{2,3}[a-zA-Z0-9%/]|" +
        "\\.(?!" + SRC_Z_CC + "|[.]).|" +
        "\\-(?!--(?:[^-]|$))(?:-*)|" +
        "\\,(?!" + SRC_Z_CC + ").|" +
        "\\!(?!" + SRC_Z_CC + "|[!]).|" +
        "\\?(?!" + SRC_Z_CC + "|[?])." +
      ")+" +
    "|\\/" +
  ")?"

SRC_XN          = "xn--[a-z0-9\\-]{1,59}"

SRC_DOMAIN_ROOT = 
  "(?:" +
    SRC_XN +
    "|" +
    SRC_PSEUDO_LETTER_NON_D + "{1,63}" +
  ")"

SRC_DOMAIN = 
  "(?:" +
    SRC_XN +
    "|" +
    "(?:" + SRC_PSEUDO_LETTER + ")" +
    "|" +
    "(?:" + SRC_PSEUDO_LETTER + "(?:-(?!-)|" + SRC_PSEUDO_LETTER + "){0,61}" + SRC_PSEUDO_LETTER + ")" +
  ")"

SRC_HOST = 
  "(?:" +
    SRC_IP4 +
  "|" +
    "(?:(?:(?:" + SRC_DOMAIN + ")\\.)*" + SRC_DOMAIN_ROOT + ")" +
  ")"

SRC_HOST_STRICT            = SRC_HOST + SRC_HOST_TERMINATOR
SRC_HOST_PORT_STRICT       = SRC_HOST + SRC_PORT + SRC_HOST_TERMINATOR

RE_HTTP = Regex.new("^\/\/" + SRC_AUTH + SRC_HOST_PORT_STRICT + SRC_PATH)
puts RE_HTTP.inspect

RE_HTTP_CI = Regex.new("^\/\/" + SRC_AUTH + SRC_HOST_PORT_STRICT + SRC_PATH, Regex::Options::IGNORE_CASE)
puts RE_HTTP_CI.inspect
```

When using without `Regex::Options::IGNORE_CASE` option the regex is successfully compiled.

When adding `Regex::Options::IGNORE_CASE` option error `regular expression is too large at 1716 (ArgumentError)` is raised though the source is well within limits (length 1716).

**Comment by nanobowers** [comment]
@ujifgc 

Some additional investigation using crystal 1.0.0:

### Using the original code now produces:
```
$ crystal orig1.cr 
/^\/\/(?:(?:(?![    -     　]|[\0--✘-1 ~/Dev/cr_4053
```
### Commenting out the first puts: `# puts RE_HTTP.inspect`
```
$ crystal orig2.cr 
Unhandled exception: regular expression is too large at 1716 (ArgumentError)
  from /usr/share/crystal/src/regex.cr:257:5 in 'initialize'
  from /usr/share/crystal/src/regex.cr:251:3 in 'new'
  from /usr/share/crystal/src/signal.cr:348:3 in '~RE_HTTP_CI:init'
  from orig2.cr:66:1 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:110:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:96:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:119:3 in 'main'
  from __libc_start_main
  from _start
  from ???
✘-1 ~/Dev/cr_4053 
```
### unicode ctrl-chars:
Based on some investigation, i've found that trying to print the `SRC_CC` variable which contains:
`"[\0-\u001F\u007F-\u009F]"` causes my terminal to stop printing anything after the \u009F control code.  I believe this may be preventing exception messages from being output to the terminal as you see above.

### Smaller failing testcase
Changing the `RE_HTTP_CI =` line to:
```
RE_HTTP_CI = Regex.new(SRC_HOST, Regex::Options::IGNORE_CASE)
```
gives:

```
$ crystal orig3.cr 
Unhandled exception: regular expression is too large at 668 (ArgumentError)
```

playing around with the sub-expressions, it seems that this has something to do with the size of SRC_ANY which is a rather large character class (the majority of the 2^16 space):
```
SRC_ANY = "[\0-\uD7FF\uE000-\uFFFF]"
```

and that by increasing the lower range i can get it to compile.  
```
SRC_ANY = "[\u03B3-\uD7FF\uE000-\uFFFF]"
```
## Thoughts / Guesses
- Using a huge unicode character class range with IGNORE_CASE is too much to handle in libpcre
- Guessing that this regex is incompatible with libpcre.
- crystal can only give back as good of error messages as underlying libpcre can provide

**Comment by straight-shoota** [comment]
I suppose this can be closed. It appears to be not a Crystal issue, but libpcre. Maybe something can be done to improve this, but keeping this issue open out of hope seems unnecessary.

**Comment by Blacksmoke16** [comment]
Yea, this is a `libpcre` issue in that there are some limits with the maximum size of a pattern. Symfony handles this by continuing to retry creating the pattern until it no longer errors, with each error resulting in a smaller chunk size. Doubtful we should do that in the stdlib tho.

Refs:
  * https://www.pcre.org/original/doc/html/pcrelimits.html
  * https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Routing/Matcher/Dumper/CompiledUrlMatcherDumper.php#L92-L105
