### ISSUE TITLE
"is not a type, it's a constant" error

### ISSUE THREAD

**Issue by Exilor** [crystal-lang/crystal#4054]
Code:
```crystal
class Foo
  BAR = 5
  def initialize
    @baz = BAR + 5
  end
end

Foo.new # Foo::BAR is not a type, it's a constant
```
If I remove the ```+ 5``` or declare the type (```@baz : Int32```) it works.

The same thing happens in this case:
```crystal
class Foo
  BAR = 5
  @@baz = BAR + 5
end
```

It appears to only happen with instance and class variables.

**Comment by asterite** [comment]
The problem goes away if you write `@baz : Int32`
