### ISSUE TITLE
Allow uninitialized instance variables in protected constructors

### ISSUE THREAD

**Issue by Bew78LesellB** [crystal-lang/crystal#4055]
I want to make a `protected` constructor that does not initialize all instance variables, so the derived classes can initialize those instance variables as needed.

Here is the minimal code that still makes sense:
```crystal
class Base
  @is_init = false
  @some_var : Int32

  def initialize(@some_var = 42)
    @is_init = true
  end

  protected def initialize
    @is_init = true
    # here I don't know how to init @some_var variable
    # => it must be initialized in derived classes
  end

  def do_something
    puts "init: #{@is_init}"
    p @some_var
  end

end

class Derived < Base

  def initialize
    @some_var = 21
    super # call the protected Base#initialize
  end

end

d = Derived.new # call the public Derived#initialize
d.do_something
```
And I get:
`
Error: instance variable '@some_var' of Base was not initialized in all of the 'initialize' methods, rendering it nilable
`

On Crystal 0.20.5

**Comment by ysbaddaden** [comment]
You define `@some_var` to be of type `Int32` in `base`, but you don't initialize the value, in `Base#initialize`, so its type is actually `Int32 | Nil`; this is a mismatch from what you told the compiler, hence compilation fails.

You must either:
- initialize `@some_var` in `Base#initialize`;
- or change the type of `@some_var` in `Base` to be a nilable (i.e. `Int32?`);
- or declare `@some_var` in `Derived` only.

**Comment by Bew78LesellB** [comment]
But in my logic, I DON'T want `@some_var` to be Nillable: I don't see the point of making a variable Nilable, just to fulfill the compiler expectations, even when the logic points that the variable should never be Nilable....

And in addition, I want my variable to be accessible from `Base` class..

.. okay I see, I can initialize `@some_var` in `Base#initialize` and pass the value from `Derived#initialize` to `Base`

---

Aside from that, as a protected constructor it to be called from another constructor in Derived classes, why not detect this usage, and allow  Base protected constructor not to initialize every fields, and allow initialization from the derived classes directly ?

**Comment by ysbaddaden** [comment]
Because this is guessing, and it breaks assumptions and what you actually declare. You actually want a nilable (can't initialize a value), and you may either pass the computed value from the derived class, or declare a nilable (and deal with it) or declare a `getter?` which will move the check to runtime with `getter!`.

**Comment by Bew78LesellB** [comment]
Ok I understand now, thanks for the explanation!
