### ISSUE TITLE
Problem with overloading method based on named arguments

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#4072]
I'd expect that below snippet would work and print `{foo: true}` and `nil` respectively.

```cr
class Foo
  def bar(name, **options)
    options
  end

  def bar(name)
    nil
  end
end

puts Foo.new.bar(:foo, foo: true)
puts Foo.new.bar(:foo)
```

However, it fails with error:

```
Error in line 12: no argument named 'foo'
Matches are:
 - Foo#bar(name)
```

If I swap the method declarations it prints `{foo: true}` and `{}` respectively, which at least compiles but still ignores the optionless overload.

**Comment by asterite** [comment]
This is expected. The correct way is to add an `Object` restriction:

```crystal
class Foo
  def bar(name, **options : Object)
    options
  end

  def bar(name)
    nil
  end
end

puts Foo.new.bar(:foo, foo: true)
puts Foo.new.bar(:foo)
```

This works the same as with single splats, [which is documented](https://crystal-lang.org/docs/syntax_and_semantics/type_restrictions.html), it's just that it's not documented for double splats.

**Comment by Sija** [comment]
Thanks for explanation, totally forgot about `Object` being usable as a type.
