### ISSUE TITLE
Compiling VERY slow.

### ISSUE THREAD

**Issue by jwaldrip** [crystal-lang/crystal#4077]
A simple `puts "hello world"` takes more than 15 seconds to compile on my system. Is this a known issue? When did the compiler get so slow?

```
$ echo 'puts "hello world"' > ./hello.cr
$ time crystal build ./hello.cr
crystal build ./hello.cr  0.84s user 18.61s system 77% cpu 25.093 total
$ crystal version
Crystal 0.21.0 (2017-02-21)
```

**Comment by asterite** [comment]
Try `rm -rf ~/.cache/crystal`. The previous compiler version generated lots of files inside `~/.cache/crystal` which might affect compile times.

**Comment by jwaldrip** [comment]
Much better! Thank you.
