### ISSUE TITLE
crystal doc doesn't produce correct results

### ISSUE THREAD

**Issue by sdogruyol** [crystal-lang/crystal#4085]
Generating API doc with `crystal doc` is not working for [Kemal](https://github.com/kemalcr/kemal). 

I expected to see https://github.com/kemalcr/kemal/blob/master/src/kemal/route.cr and others but unfortunetaly there's only `Top level namespace` included in the generated doc.

Here's a screenshot

![screen shot 2017-02-27 at 21 33 53](https://cloud.githubusercontent.com/assets/990485/23374378/1697ff50-fd35-11e6-8439-160d9250e99f.png)

**Comment by spalladino** [comment]
Hey @bcardiff I recall you had been working with docs recently for https://github.com/bcardiff/ghshard, could you take a look at this one?

**Comment by bcardiff** [comment]
fixed in the kemal PR ;-)
