### ISSUE TITLE
XML::Builder can write invalid XML characters

### ISSUE THREAD

**Issue by RX14** [crystal-lang/crystal#4089]
On crystal `0.21.0`

```crystal
# example.cr
require "xml"

xml = XML.build(indent: 2) do |xml|
  xml.element("example", number: "1") do
    xml.text "foo\0bar"
  end
  xml.element("example", number: "2") do
    xml.text "foo\u{08}bar"
  end
end

puts xml
```

```
$ crystal example.cr
<?xml version="1.0"?>
<example number="1">foo</example>
<example number="2">fobar</example>
```

I expect to see `XML::Builder` raise, because NUL and DEL cannot be represented in XML. [(ref)](https://www.w3.org/TR/xml/#charsets)

**Comment by asterite** [comment]
Good finding! We should use [xmlEncodeSpecialChars](http://xmlsoft.org/html/libxml-entities.html#xmlEncodeSpecialChars), both for texts and attributes, I guess. Nokogiri seems to use that function too.
