### ISSUE TITLE
Docs: Include documentation in crystal for offline use

### ISSUE THREAD

**Issue by spinscale** [crystal-lang/crystal#4092]
Apologies if this has already been submitted, but I could not find anything when searching for `offline`.

I think it would be useful to include the [API docs](https://crystal-lang.org/api/0.21.0/) as part of `crystal play` (maybe in its own tab), so that users have offline access to the docs, instead of being forced to have internet access.

**Comment by marcosdsanchez** [comment]
What platform are you using?

In archlinux at least, API docs can be found in `/usr/share/doc/crystal/api` .

Examples are in `/usr/share/doc/crystal/samples`

**Comment by bcardiff** [comment]
In OSX the docs are not bundled. 
Maybe on a release we could make an archive file the doc content to download. 
BTW, building docs in crystal repo is a `$ make docs`.

The idea of making them available in `crystal play` is mentioned / proposed at #3530

**Comment by drosehn** [comment]
Perhaps maybe a `crystal savedocs location`, where crystal would get the archive of the docs which matches that version of crystal, and expands the archive on the local machine into `location`.  (I'm thinking that the person who wants the docs might not have write-access to some standard global directory for them.)

**Comment by straight-shoota** [comment]
The docs for stdlib are currently under 7 mb gzipped. I don't think it would be to much to include that into every distribution package.
For the purpose of displaying docs in `crystal play` it would even be sufficient to strip layout frame and navigation list from the HTML files, the contents can be embedded by the HTTP server.

**Comment by erdnaxeli** [comment]
> What platform are you using?
> 
> In archlinux at least, API docs can be found in `/usr/share/doc/crystal/api` .
> 
> Examples are in `/usr/share/doc/crystal/samples`

In the APT package (0.35.1), the examples are here but the doc is not.

How could we help this issue to progress?

**Comment by straight-shoota** [comment]
It's up to the package maintainers whether they include the API docs or not. An archive containing the API docs ready for use is available for every release (for example https://github.com/crystal-lang/crystal/releases/download/0.35.1/crystal-0.35.1-docs.tar.gz). Alternatively, they can be built locally using `make docs` in the crystal repository.

I don't think there is anything to do here from our side.

**Comment by straight-shoota** [comment]
Or, actually, APT packages are provided by the Crystal team. So we should consider providing the API docs in the APT package (or as an additional `crystal-docs` package).

**Comment by spinscale** [comment]
the brew package also does not include the docs in `/usr/local/Cellar/crystal`

**Comment by erdnaxeli** [comment]
> How could we help this issue to progress?

My question what about how to help *this* issue, to get the doc in crystal play. But if it can be added to the apt package, that would be great too.

**Comment by bcardiff** [comment]
We could include the docs in the package, or create one individually. But they can be generated by the installed compiler directly.

If the more convenient way to access the offline docs is to have them in the crystal play I would prefer to design a bigger story that would involve generating docs on the fly for the referenced shards and the std-lib.

My first doubt is if they should be separate docs per shard, or if they should be combined as a single one to simplify a search across all of them.

**Comment by straight-shoota** [comment]
In the new [repositories on OBS](https://software.opensuse.org//download.html?project=devel%3Alanguages%3Acrystal&package=crystal) there are now `crystal-docs` packages for both deb and rpm available.

I think this can be closed. Building docs for shards is a far bigger story than this.
