### ISSUE TITLE
Ability to require files by absolute path

### ISSUE THREAD

**Issue by unn4m3d** [crystal-lang/crystal#4105]
Compiler does not `require` files by absolute path. For example,
```
$ crystal run Extfile -- ... some params ...
Error in Extfile:1: while requiring "/home/unn4m3d/extbuilder/src/extbuilder/extb_ext.cr": can't find file '/home/unn4m3d/extbuilder/src/extbuilder/extb_ext.cr' relative to '/home/unn4m3d/extbuilder/spec/extsrc'

require "/home/unn4m3d/extbuilder/src/extbuilder/extb_ext.cr" 
```
or
```
$ crystal run Extfile --prelude "/home/unn4m3d/extbuilder/src/extbuilder/extb_ext.cr" -- ... some params ...
Error in Extfile:1: while requiring "/home/unn4m3d/extbuilder/src/extbuilder/extb_ext.cr": can't find file '/home/unn4m3d/extbuilder/src/extbuilder/extb_ext.cr' relative to '/home/unn4m3d/extbuilder/spec/extsrc'
```
Although `/home/unn4m3d/extbuilder/src/extbuilder/extb_ext.cr` exists. Same thing happens if I try to require, for example, `/opt/crystal/src/xml`

I've found [a check](https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/crystal_path.cr#L152) in the code, but it doesn't seem to work

I have `Crystal 0.21.0 [c2c2276] (2017-02-21)` on Linux Mint 17. This happens on 0.20.5 and master too.

**UPD**

This works:
```crystal
CRYSTAL_PATH = `crystal env CRYSTAL_PATH`
system "CRYSTAL_PATH=/home/unn4m3d/extbuilder/src/extbuilder:#{CRYSTAL_PATH} crystal run Extfile --prelude extb_ext -- ... some params ..."
```

**Comment by asterite** [comment]
This is a feature of the language, not a bug. All files should be relative to a project. Program's code goes into `src`. Dependencies go in `lib`.
