### ISSUE TITLE
Allow module/class constants access in macro controls

### ISSUE THREAD

**Issue by Bew78LesellB** [crystal-lang/crystal#4107]
```crystal
module Module
  CONSTANT = 42
end

macro use_constant
  {% if Module.CONSTANT == 42 %}
    true
  {% else %}
    false
  {% end %}
end

p use_constant  # should print `true`
```
Error: `Syntax error in eval:6: expecting any of these tokens: IDENT, +, -, *, /, %, |, &, ^, **, <<, <, <=, ==, !=, =~, !~, >>, >, >=, <=>, ===, [], []=, []?, [ (not 'CONST')`

Using Crystal 0.21.0: https://carc.in/#/r/1otp

**Comment by RX14** [comment]
This does work, its just the syntax for accessing constants is `Type::CONSTANT`.

**Comment by kostya** [comment]
https://carc.in/#/r/1otz

**Comment by Bew78LesellB** [comment]
Oh yes of course, too tired maybe... Thanks
