### ISSUE TITLE
`if (conditional) then` doesn't work

### ISSUE THREAD

**Issue by Laaas** [crystal-lang/crystal#4117]
```crystal
if true then
end
```
```
Syntax error in x.cr:2: unexpected token: then

if true then
```

```crystal
then = 2
```

```
Syntax error in x.cr:2: expecting token 'EOF', not 'then'

then = 2
```

Thought it was weird that `then` after an `if` isn't supported, even though the keyword is reserved.

**Comment by RX14** [comment]
From looking at the source, `then` is a keyword to support shorthand `case` as shown below. We won't support `if` syntax with `when` as it is redundant.

```cr
case expr
when "something" then "foo"
when :something_else then "bar"
end
```

**Comment by luislavena** [comment]
As stated by @RX14, `if ... end`, `if ... else ... end` and `if ... elsif ... end` control expressions do not support `then`. `then` is a reserved keyword of `case ... when`.

If compared with Ruby, `then` is non-mandatory for `if` and also optional in `case`.

Here are links to Crystal documentation on these two control expressions:

- https://crystal-lang.org/docs/syntax_and_semantics/if.html
- https://crystal-lang.org/docs/syntax_and_semantics/case.html

Hope that helps.

**Comment by plainas** [comment]
@luislavena In the first link, the documents do mention the ''then'' branch and the text is formated with the same style as the ''if'' keyword.

**Comment by luislavena** [comment]
But it says *the then branch* and *the else branch*, so is not talking about `then` as keyword.

**Comment by luislavena** [comment]
Definitely the decision to use backticks might have caused the confusion, but `then` is only supported in the context of `case ... when` and not `if`.

Will send a PR for docs to change the usage of backticks.

**Comment by bcardiff** [comment]
And an example of the `when / then` syntax should be added to https://crystal-lang.org/docs/syntax_and_semantics/case.html .

But I must confess that I wouldn't care, for consistency, removing the `when / then` support.

**Comment by luislavena** [comment]
@bcardiff `when ... then` is being used in many places in the codebase and definitely useful for short case scenarios.

**Comment by Sija** [comment]
@bcardiff Hmm, I'd rather vote for **adding** `if ... then` support, since it's being useful at times when using ternary operator looks odd, like below:

```cr
obj.foo? ? "foo" : "bar"
```
vs

```cr
if obj.foo? then "foo" else "bar"
```

**Comment by luislavena** [comment]
I personally dislike one-liner `if`, it makes hard to grasp quickly the branches and the outcome, forcing you to scan for the magic keyword to figure it out.

**Comment by Sija** [comment]
@luislavena ternary operator with double `?` next to each other reads badly too IMHO, though I agree that  one-liner `if ... then` is often hard to read with longer expressions.

**Comment by asterite** [comment]
For what it's worth, `then` in `if` was explicitly not added in Crystal to simplify the language. `then` in `when` is so much more common in Ruby so it was added. It also reads nice:

```crystal
case something
when foo then bar
when baz then qux
end
```

For if there's no need to inline the value with `then` because there's suffix `if`:

```crystal
# Ruby
if foo then bar end

# Better:
bar if foo
```

In the case of `else` one can use the ternary operator or simply a newline:

```crystal
if foo
  bar
else
  baz
end

foo ? bar : baz

# Ruby
if foo then # This then is redundant
  bar
else
  baz
end
```

`then` in `if` is also discouraged in the most popular Ruby style guide: https://github.com/bbatsov/ruby-style-guide#no-then and https://github.com/bbatsov/ruby-style-guide#ternary-operator

**Comment by plainas** [comment]
Ternary operator is rather ubiquitous in other languages. Personally this feels like bike shedding. Just rephrase the first paragraph in [here](https://github.com/crystal-lang/crystal-book/blob/master/syntax_and_semantics/if.md) for something less ambiguous. Preferably without the word ''then'', or at least not with the same formatting as keywords.

**Comment by Laaas** [comment]
1: I don't mean that `if` and `when` should somehow be mixable.


2: I mean that it should be optional to put a `then` after the `if`, since
it is currently required that you do **not** put a `then` after the `if`,
which is fine, but supporting it optionally wouldn't hurt anyone.

Den 05/03/2017 19.09 skrev "Luis Lavena" <notifications@github.com>:

**Comment by Laaas** [comment]
Oh wow it seems my client hadn't updated properly and I only saw the first
two replies.

Den 07/03/2017 09.03 skrev "Las" <lasssafin@gmail.com>:

**Comment by ysbaddaden** [comment]
Closing. It was a design decision to avoid an optional syntax that will be told to not be used, as explained by @asterite above.
