### ISSUE TITLE
http/client results in "OPENSSL_1.0.2 not found" running binary on another machine 

### ISSUE THREAD

**Issue by jasonl99** [crystal-lang/crystal#4120]
I am running an app on a very inexpensive VPS server running Debian 8.  The app is built on a laptop running Linux Mint. 

The server's `uname -a` returns this:
```
Linux debian 4.8.6-x86_64-linode78 #1 SMP Tue Nov 1 14:51:21 EDT 2016 x86_64 GNU/Linux
```

This worked fine up until I added `http/client` to grab some json data from external sources.   Now when I try to run the app, I get this output:

```
/usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: version `OPENSSL_1.0.2' not found
/usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found
```
I've searched the issues, and couldn't really find anything similar.

**Comment by luislavena** [comment]
@jasonl99 binaries produced on one system are expected to be run on similar system. They contain information about linked shared libraries which will differ across versions and specially across distributions.

While Mint is based on Ubuntu, and Ubuntu on Debian, they are not the same version and the provided system libraries (like OpenSSL) differ, which is what you're experiencing.

If your target system is Debian 8, perhaps will be good to setup a VM in your dev machine that uses the compiler to target that particular version.

Ideally will be possible to generate an static binary that contains all the required elements to run standalone without dependencies on the target system, but that requires considerable effort in produce such toolchain.

While doesn't solve directly your problem, hope it adds some clarification and that the suggestions are useful.

Cheers.

**Comment by jasonl99** [comment]
@luislavena thanks for your answer, and I guess that's what I was afraid of.  But I like your suggesting of setting up a VM and compiling on that.
