### ISSUE TITLE
Can't use variable foo inside assignment to variable foo

### ISSUE THREAD

**Issue by KCreate** [crystal-lang/crystal#4121]
Basically, I'm having a super specific use case where the following macro is used

```crystal
macro foo(name, *types)

  def {{name.id}}(arguments : Array(Int32))
    {% for type, index in types %}
      {{type.var}} : {{type.type}}
      {{type.var}} = arguments[{{index}}]
    {% end %}

    {{yield}}
  end

end

foo "myFunc", first : Int32 do
  first = first + 1
  puts first
end

myFunc [1]
```

The above code is a reduced example of code which worked until version `0.21.0`. Release `0.21.1` somehow broke this.

Below is the console output of testing the code with both versions.

Crystal 0.21.0
```
$ crystal foo.cr
2
```

Crystal 0.21.1
```
$ crystal foo.cr
Syntax error in foo.cr:15: can't use variable name 'first' inside assignment to variable 'first'

  first = first + 1
          ^
```

I have absolutely no idea what would cause something like this. I've looked through the changelog of release `0.21.1` and found nothing related to my issue.

I'm testing on `macOS 10.12.3`.

**Comment by KCreate** [comment]
More reduced example

```crystal
macro foo(type)
  {{type.var}} = 25
  {{yield}}
end

foo arg do
  arg = arg + 1
  puts arg
end
```

**Comment by KCreate** [comment]
Also on `0.21.1`

```crystal
macro foo(type)
  {{type}} = 25
  {{yield}}
end

foo arg do
  puts typeof(arg) # => Int32
  puts arg # => 25
end

```

**Comment by asterite** [comment]
The fix in #4114 made this stop working. But that's OK, it was never supposed to work. Don't use macros to declare local variables. Macros should not (and if they do, it's a bug) declare local variables that can be used after their expansion.

**Comment by kirbyfan64** [comment]
> Macros should not (and if they do, it's a bug) declare local variables that can be used after their expansion.

Why not?

**Comment by asterite** [comment]
Crystal knows that a local variables is a local variable because there's an assignment to it. That's also how Ruby works:

```crystal
def foo
  "method"
end

puts foo # this is a method call, there's no `foo = ...` before this line

foo = "variable"
puts foo # now this is a local variable
```

Macros are expanded after parsing, so there's no way the parser will know that something is suddenly a local variable instead of a method:

```crystal
macro declare_foo
  foo = "variable"
end

declare_foo

# This line is parsed as a call to the method "foo" because there's
# no `foo = ...` before this line, and macros are expanded after parsing
puts foo
```

That's the reason :-)

If you was able to somehow make that work it was a bug.

**Comment by KCreate** [comment]
What would be the use for `{{yield}}` be then, if there's no way for that block to make assumptions about the macros content?

**Comment by KCreate** [comment]
Nevermind, found [this issue](https://github.com/crystal-lang/crystal/issues/1338).

There's a workaround which allows macros to declare local variables.

```crystal
macro foo(&block)
  def bar(baz)
    foo = 25
    {{block.body}}
  end
end

foo do
  puts foo
  puts baz
end

bar("Hi")
```

Removing this too would seem a little overly-cautious to me. If one want's to write code like that, one should be able to keep track of what variables and methods he declared.

**Comment by KCreate** [comment]
One can also get around the parsing issue by doing something like the following:

```crystal
macro foo(name, *types, &block)

  def {{name.id}}(arguments : Array(Int32))
    {% for type, index in types %}
      {{block.args[index].id}} = arguments[{{index}}]
    {% end %}

    {{block.body}}
  end

end

foo "myFunc", Int32, Int32 do |first, second|
  puts first
  puts second
end

myFunc [1, 2]
```

**Comment by RX14** [comment]
Im confused as to how the example code given in #2923 differs from the original code example in this issue. Both define a new method in macro code containing `{{yield}}`. The only difference I can see is that one defines variables in call args and one in the macro body.

**Comment by KCreate** [comment]
That is indeed the only difference. However, the parser doesn't understand that these nodes are supposed to be variable declarations, which causes the `can't use variable 'foo' inside assign to `foo`` error message.

In my last code example, the variables are declared in the block arguments and thus are registered as variables.

**Comment by RX14** [comment]
@KCreate Note that this works:
```cr
macro foo(name, *types)

  def {{name.id}}(arguments : Array(Int32))
    {% for type, index in types %}
      {{type.var}} : {{type.type}}
      {{type.var}} = arguments[{{index}}]
    {% end %}

    {{yield}}
  end

end

foo "myFunc", first : Int32 do |first|
  first = first + 1
  puts first
end

myFunc [1]
```

The only diff is
```diff
- foo "myFunc", first : Int32 do
+ foo "myFunc", first : Int32 do |first|
```

This makes sense, because the error comes from parsing the block, before the macro is even evaluated. The true difference to #2923 is that that only uses `puts bar`, a variable read, whereas this example does `first += 1` which fails to parse.

Therefore this is a bug, as this works:
```cr
macro foo
  def bar(baz)
    {{yield}}
  end
end

foo do
  bar = baz + "!"
end

bar("Hi")
```

However this doesn't:
```diff
-   bar = baz + "!"
+   baz = baz + "!"
```

**Comment by asterite** [comment]
It works because macro expansions work like this:
- a string is built from the expanded macro
- this is parsed
- this is injected into the program

If we ever implement macros using quote/unquote then this will of course stop working. I wouldn't rely on this behaviour.

(though if we implemement macros using quote/unquote most of the existing macros will break, so it's not a big deal)

**Comment by RX14** [comment]
@asterite so is this a bug or not? #2923 seems to suggest so, I'd really dislike for this kind of functionality to be unsupported, and I'd hate even *more* for it to be half-supported (works, apart from this bug).

**Comment by asterite** [comment]
It's not a bug, but it might break in the future.
