### ISSUE TITLE
Formatter: rescues keywords not aligned when variable is missing

### ISSUE THREAD

**Issue by bcardiff** [crystal-lang/crystal#4124]
The following code

```crystal
begin
rescue e : A
rescue : B
end
```

is currently formatted as:

```crystal
begin
rescue e : A
  rescue : B
end
```

it should probably be left as

```crystal
begin
rescue e : A
rescue : B
end
```

It also happens if the `rescue : B` is the sole rescue.

---

```
$ crystal --version
Crystal 0.21.1 (2017-03-07) LLVM 3.9.1
```

**Comment by asterite** [comment]
`rescue : B` declares a local variable named "rescue" with type `B` (of course there's no way to use that local variable afterwards)

`rescue` can be:
- `rescue Type`
- `rescue var`
- `rescue var : Type`

`rescue : Type` is not a rescue clause

**Comment by bcardiff** [comment]
Right, this code highlighter... 

```crystal
  class Rescue < ASTNode
    property types : Array(ASTNode)?
    property name : String?
    #...
```

Since the ASTNode is declared as I jump into the wrong assumption.

**Comment by RX14** [comment]
Shouldn't `rescue : Type` fail to parse then?

**Comment by asterite** [comment]
Keywords are allowed to appear in type declarations because of this:

```crystal
class Foo
  property rescue : Bool
end

Foo.new.rescue
```
