### ISSUE TITLE
Segfault while raising on linux

### ISSUE THREAD

**Issue by RX14** [crystal-lang/crystal#4127]
Steps to reproduce:
1. `mkdir /tmp/foo; cd /tmp/foo` (yes, it has to be in `/tmp`)
2. Copy below source code into a file *inside* `/tmp/foo`.
3. `crystal run foo.cr`

```cr
require "file_utils"
require "json"

FOO = __DIR__ + "/foo"
BAR = __DIR__ + "/bar"

`git clone https://github.com/crystal-lang/crystal #{FOO}` unless Dir.exists?(FOO)

base_clone_path = FOO
temp_clone_path = BAR

begin
  FileUtils.cp_r(base_clone_path, temp_clone_path)
  JSON.parse("fffooo")
ensure
  FileUtils.rm_r(temp_clone_path)
end
```

I see the code segfault and spew random memory all over the console. The failures are random so you might have to run it a few times to see some of the more interesting failure modes.

Crystal versions I tried:
```
Crystal 0.21.1+6 [8a437e67b] (2017-03-10) LLVM 3.9.1
```
```
Crystal 0.21.1 [3c6c75e] (2017-03-06) LLVM 3.5.0
```

Honestly I think this is the strangest, most specific bug i've ever encountered.

**Comment by kirbyfan64** [comment]
Would you happen to be using a `tmpfs`?

**Comment by RX14** [comment]
@kirbyfan64 Indeed, and I have *no* idea why that's required in the reproduction.

**Comment by kirbyfan64** [comment]
@RX14 Could it be that the clone and/or cp_r is sometimes maxing out the `tmpfs`, causing the process to crash? Try re-running it, but leaving another terminal open and continuously running `du -h`.

**Comment by RX14** [comment]
@kirbyfan64 Default tempfs size is half of RAM, and I have 16gb ram. I'm very sure it's not running out of space. Regardless, running out of file space shouldn't cause a segfault.

**Comment by nick-andren** [comment]
This doesn't just happen in {{/tmp}}, but it seems to be the most frequent there. I managed to trigger it a couple of times in a location within my {{/home}} directory. Here's an instance of one of these:
```
~/junk/foo crystal run foo.cr 
Cloning into '/home/user/junk/foo/foo'...
remote: Counting objects: 87295, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 87295 (delta 3), reused 0 (delta 0), pack-reused 87279
Receiving objects: 100% (87295/87295), 32.31 MiB | 3.75 MiB/s, done.
Resolving deltas: 100% (59670/59670), done.
Checking connectivity... done.
union.cr (JSON::ParseException)
0x200000000: ??? at ??
0x30c00000026: ??? at ??
0x6d6f680000000009: ??? at ??
0x46b1eb: *Char#to_s<IO::FileDescriptor>:(IO::FileDescriptor | Int32 | Nil) at /opt/crystal/src/char.cr 781:9
0x200000000: ??? at ??
0x30d00000026: ??? at ??
0x706d6f0000000009: ??? at ??
0x46b1f9: *Char#to_s<IO::FileDescriptor>:(IO::FileDescriptor | Int32 | Nil) at /opt/crystal/src/char.cr 695:23
0x200000000: ??? at ??
0x2b700000026: ??? at ??
0x17: ??? at ??
0x46b224: *Char#to_s<IO::FileDescriptor>:(IO::FileDescriptor | Int32 | Nil) at /opt/crystal/src/char.cr 780:9
0x200000000: ??? at ??
0x30c00000026: ??? at ??
0x662f6b0000000009: ??? at ??
0x46b246: *Char#to_s<IO::FileDescriptor>:(IO::FileDescriptor | Int32 | Nil) at /opt/crystal/src/char.cr 781:9
0x200000000: ??? at ??
0x30d00000026: ??? at ??
```

It's odd that random filenames are being displayed when running this program, regardless of whether or not the {{foo}} directory exists. I'm wondering if the `FileUtils` operations are interfering with the stack trace lookup when the JSON parse operation inevitably fails.

This is on Linux Mint 18 (Sarah/xenial) with `Crystal 0.21.1 [3c6c75e] (2017-03-06) LLVM 3.5.0`

**Comment by RX14** [comment]
Still broke on 0.24.1 :)

**Comment by straight-shoota** [comment]
Can't reproduce on 0.35.1, probably fixed somewhere in between.
