### ISSUE TITLE
HTTP::Params [] and fetch returns only first element

### ISSUE THREAD

**Issue by sdogruyol** [crystal-lang/crystal#4128]
Snippet

```crystal
require "http"

body = "sld=kemal&tlds[]=com&tlds[]=net&tlds[]=io"
params = HTTP::Params.parse body

pp params["tlds[]"] # => "com"
```

Normally i'd expect `tlds[]`to be `["com", "net", "io"]` as it's being parsed correctly. However `
[]` and `fetch` returns only first element as seen in https://github.com/crystal-lang/crystal/blob/master/src/http/params.cr#L122

Accessing the array as `"tlds[]"` also feels a bit unconventional and one would expect to access it via `"tlds"` but that's a topic for another issue

**Comment by RX14** [comment]
From the docs:

![](https://aww.moe/6vok9r.png)
![](https://aww.moe/773l7z.png)

If you call the key `tlds[]`, why should it be accessed under any key except `tlds[]`? You could just as easilly send `sld=kemal&tlds=com&tlds=net&tlds=io` and then how would you access that?

**Comment by sdogruyol** [comment]
Thank you @RX14. I didn't know that `fetch_all` existed for this purpose 👍 

About accessing `sld=kemal&tlds[]=com&tlds[]=net&tlds[]=io` most of the popular web frameworks Sinatra, Rails e.g will allow you to use it like `params['tlds']` but i'm not sure if it's coming from Rack.

**Comment by RX14** [comment]
The `[]` suffix for query params/urlencoded seems to be very inconsistent between languages: http://stackoverflow.com/a/9547490/2035962

The spec doesn't seem to mention it, so I would say that Ruby and PHP are wrong here and Crystal should stick to the less magic way of doing things.

**Comment by bcardiff** [comment]
Notice that Rails also propose a syntax for sending hash/array in params. jQuery adopted the same encoding which was pretty handy. I would say that any serialization beyond the standard should be implemented by a shard / framework.

**Comment by sdogruyol** [comment]
Thank you all for your insights 💯

**Comment by bcardiff** [comment]
NB: I would probably use it ;-).

It's just that there is no a clear winner option for this, since impacts on the client side of the http app.

Welcome to kemalcr/deep-params (?)

**Comment by sdogruyol** [comment]
Hehe, this is pretty common and it's already supported in Crystal `sld=kemal&tlds[]=com&tlds[]=net&tlds[]=io`.

I agree with @RX14 accessing it like `fetch_all("tlds[]")` is explicit and fine.
