### ISSUE TITLE
Macro didn't print `String` object value

### ISSUE THREAD

**Issue by oltmannsdaniel** [crystal-lang/crystal#4137]
My Macro code to change object values:
```Crystal
macro change_self(key, value)
    self.{{key}} = {{value}}
end
```

Where are the values from? https://github.com/datanoise/mongo.cr/blob/master/src/bson.cr#L262

Error:
```Bash
self.key = val.value

undefined method 'key=' for User:Class
```

But it should equal `self.{{the_give_key_from_macro}} = {{the_given_value}}`

**Comment by bew** [comment]
Can you explain a bit more what you want to do, and the minimal code that uses your macro ?

**Comment by oltmannsdaniel** [comment]
I want to pass a String to the macro, the class variable name that needs to change, and a Value of any variable Type.Just a macro to change the class variable by a stringAm 12.03.2017 15:28 schrieb Benoit de Chezelles <notifications@github.com>:Can you explain a bit more what you want to do, and the minimal code that uses your macro ?

**Comment by bew** [comment]
You mean something like that ?
```crystal
macro change_self(key, value)
  @@{{key.id}} = {{value}}
end

class A
  @@what = "world"

  def self.change_what
    change_self what, "new world"
  end

  def self.say_hello
    puts "Hello #{@@what}"
  end

end

A.change_what
A.say_hello # => Hello new world
```

**Comment by oltmannsdaniel** [comment]
Yes, exactlyAm 12.03.2017 15:58 schrieb Benoit de Chezelles <notifications@github.com>:You mean something like that ?
macro change_self(key, value)
  @@{{key.id}} = {{value}}
end

class A
  @@what = "world"

  def self.change_what
    change_self what, "new world"
  end

  def self.say_hello
    puts "Hello #{@@what}"
  end

end

A.change_what
A.say_hello # => Hello new world

**Comment by bew** [comment]
@oltmannsdaniel what you want is not doable in crystal, because macro are expanded at compile-time. If I understand well, your `what` is a variable, which contains a string. The content of this variable is only known at run-time (after compilation), and thus this content cannot be used as a macro value.

A workaround would be to use a `Hash` to store the different class variables names & values:
```crystal
class A
  @@vars = {
    "var1" => nil,
    "var2" => "Default value",
  } of String => String?

  def self.change(key, value)
    @@vars[key] = value
  end

  def self.get(key)
    @@vars[key].not_nil!
  end
end

key = "var1"

A.change key, "new value"
puts A.get key    # => new value
puts A.get "var2" # => Default value
```

**Comment by oltmannsdaniel** [comment]
I also took a look at that option, but I use JSON mapping. (github.com/hoursplatz/mongodb.cr > src > mongodb > model.cr)

**Comment by bew** [comment]
@oltmannsdaniel I don't see where you need this, can you be more specific?

**Comment by oltmannsdaniel** [comment]
@bew I create a Class, extended by the MongoDB::Model one. I want to add model attributes, what I do with JSON mapping.

For an example take a look at the example.cr in https://github.com/hoursplatz/mongodb.cr

But now I need to put that to a nee function that chabges the values in an @ variable.

**Comment by bew** [comment]
> But now I need to put that to a **nee** function that changes the values in an @ variable.

I'm sorry but I don't see.. maybe put some code or pseudo code of what you want to achieve, here, so we can directly see and test things
