### ISSUE TITLE
`Deprecated` modifier/keyword/annotation revisited

### ISSUE THREAD

**Issue by ozra** [crystal-lang/crystal#4138]
I think this has been discussed before, but I couldn't find an issue when searching.

**Proposition**
- An "official" part-of-the-language way of marking deprecated methods, etc., and where applicable their replacement
   - `def deprecated foo(x, y, z) => bar(x, y, z)` - _or something_

**Motivation**
- I don't think I'm alone in regex-replacing renamed methods etc. - and that is a less than safe practise, but when the alternative is `recompile`, `edit a line`, `recompile`... temptation wins ;-)
- Would therefore be super-helpful for refactorization tools
   - use compiler to get all locations in code which are deprecated uses
   - automatically replace with new name where possible (simple renamings)
   - otherwise: add comment with easily distinctly grep'able message where not automatically possible, making grep'ing a more straight forward job - hints about what to do / change are available at each specific edit spot.

**Comment by bew** [comment]
I would rather use flags, so it does not interfere with the language:
```crystal
@[Deprecated(new_name: bar)]
def foo(x, y, z)
end
```

**Comment by ozra** [comment]
Yes, however, I think now in alpha, and during beta, stage - having such a tool could be very beneficial for also the core developers. It might make reasoning about possible API changers (and even language constructs) "more honest", since it can be easy to _unconsciously_ resist otherwise very good changes, without basis in merit, but rather in feeling of burden of changing a lot of code (for everyone) (it's good to consider how our wetware process things, just like the hardware we execute algos on :-) ). Just a thought.

**Comment by ysbaddaden** [comment]
I'm all in for introducing a `@[Deprecated]` annotation, but... what should happen? Just annotate the documentation? Or shall the compiler spit out warnings when a deprecated method/accessor/type is accessed —keeping in mind we don't like warnings, but theae warnibgs can only be avoided for a limited time.

I'd personnally like the annotation to merely accept a message, for example `@[Deprecated("foo is deprecated in favor to bar and will be removed in v2.0.0")]`.

**Comment by asterite** [comment]
```
def foo
  {{ puts "Warning: this method is deprecated, use something else" }}
end
```

We've used this technique in the past with success. I don't think it's worth adding new features/syntax for this (you'll get the error every time you compile your program)

**Comment by Sija** [comment]
@asterite this technique is sufficient perhaps for cli related rapid development, in the long run tho' having specific annotation would enhance docs and imo provide more predictable path of sunsetting obsolete API-s.

**Comment by ysbaddaden** [comment]
If the documentation states `deprecated` then I won't even try to use it. Without the annotation, I must *duplicate* the message (docs + warning), or find out when trying out the method that it's actually deprecated. Either ain't nice.

**Comment by ozra** [comment]
Also, on a side note, as @ysbaddaden said earlier: there's only so long we can put off having warnings in the compiler. The "errors or nothing" mentality is not inherently the most helpful path to help a coder getting the job done. But having to request them specifically could be a good thing (of course I always go with `-Wall`).
