### ISSUE TITLE
Using JSON.mapping with additional values

### ISSUE THREAD

**Issue by RX14** [crystal-lang/crystal#4140]
Sometimes when writing a class which uses JSON.mapping, additional values need to be provided when constructing the object which do not appear in the JSON. For example, an object representing an installation of crystal:

```cr
class CrystalVersion
  getter base_dir : String
  getter version : String
  getter install_method : InstallMethod

  def initialize(@base_dir, @version, @install_method)
  end

  JSON.mapping({
    version:        {type: String, getter: false, setter: false},
    install_method: {type: InstallMethod, getter: false, setter: false},
  })
end
```

When we serialise this object, we want to save the version and install_method, however we don't want to save the `base_dir` because that is discovered independently through configuration. When serialising, this works great, however when serializing we hit a problem: we can't provide `base_dir`.

As `JSON.mapping` provides a constructor, it would be ideal if you could define a constructor like so, which initializes the variable then calls the other constructor like so:
```cr
def initialize(@base_dir, json : JSON::PullParser)
  initialize(json)
end
```
Unfortunately I recall that calling initialize from another constructor is illegal (although I can't find evidence of that in the documentation or by searching the issue tracker, so maybe I'm going loopy). Still, there would still exist a constructor which didn't initialise all the instance variables, causing a compile error. However, a general solution which allowed defining a custom constructor like this would also solve the problem of computed variables or other miscellaneous construction logic when constructing classes using `JSON.mapping`, which comes up a lot.

Here are some other proposed solutions:
1. Extend `JSON.mapping` to allow defining additional named arguments to the `initialize` method, which would be assigned to class vars.
2. Somehow be able to undefine/remove the constructor defined by `JSON.mapping`, and replace it with a custom constructor which calls the original definition at will. Again, this is the most general solution which covers a large range of problems, but it also the hardest to design and implement.
3. Leave `JSON.mapping` as it is and document that it can't be used this way. Proposed solution: deserialise json using `JSON.mapping` in another class or another method, then inject the values into the constructor. The problem with this is that it's more code (and another class if you use `JSON.mapping`).
4. Leave `JSON.mapping` as it is and define `base_dir` as being nillable, with `getter!`. After using `from_json`, set `base_dir`. This solution is a little ugly though, and has some of the same problems as (3).

Thoughts?

**Comment by kostya** [comment]
with auto_json: https://github.com/kostya/auto_json

```crystal
require "auto_json"

enum InstallMethod
  Bla
end

class CrystalVersion
  include AutoJson
  field :base_dir, String, json: false, setter: false
  field :version, String, setter: false
  field :install_method, InstallMethod, setter: false
end

c = CrystalVersion.new("/", "1", InstallMethod::Bla)
p c
p c.to_json
```

```
#<CrystalVersion:0x106ccdf00 @base_dir="/", @install_method=Bla, @version="1">
"{\"version\":\"1\",\"install_method\":0}"
```

**Comment by drosehn** [comment]
> Unfortunately I recall that calling initialize from another constructor is illegal (although I can't find evidence of that in the documentation or by searching the issue tracker...

In an issue unrelated to json, I suggested a solution where one `initialize` method calls a second "common" `initialize` method, and asterite said that tactic was fine.  In fact, he suggested a better way to define the "common" `initialize` method.

**Comment by kostya** [comment]
https://github.com/crystal-lang/crystal/issues/3202

**Comment by RX14** [comment]
@kostya That's not quite what I meant. What you say is perfectly possible using only `JSON.mapping`. If it helps you understand my complete code is here: https://gist.github.com/RX14/3fe595878a13ce2bfad0adaf43957a5e. I ended up implementing solution (3).

**Comment by RX14** [comment]
@drosehn Even so, you still get a compile error as the generated initialize doesn't initialize all class vars. Otherwise, I would have tested it.

**Comment by bew** [comment]
I got this to (almost) work, which is much nicer to the eyes without the `getter: false`, ... :
```crystal
enum InstallMethod
  Something,
  Whatever,
end

class CrystalVersion
  getter base_dir : String
  getter version : String
  getter install_method : InstallMethod

  def initialize(@base_dir, @version, @install_method)
  end

  JSON.mapping(decl: false, props: {
    version:        String,
    install_method: InstallMethod,
  })
end
```

On the `initialize` issue, I don't understand how you see the practical usage of an `initialize` like:
```crystal
def initialize(@base_dir, json : JSON::PullParser)
  # ...
end
```
@ozra 

For example, if I want to embed a CrystalVersion into another json mapping:
```crystal
class A
  JSON.mapping({
    version: CrystalVersion,
  })
end
```
How should this work/be used ? When and how do we pass the value to `@base_dir` ?

**Comment by bew** [comment]
I finally got this to work:
```crystal
require "json"
require "./json_mapper"

enum InstallMethod
  Local,
  System,
  SomethingElse,
  Whatever,
end

class CrystalVersion
  getter base_dir : String
  getter version : String
  getter install_method : InstallMethod

  def initialize(@base_dir, @version, @install_method)
  end

  JSON.mapper(decl: false, more_init: {:base_dir}, props: {
    version:        String,
    install_method: InstallMethod,
  })
end

json = %({
  "version": "v1",
  "install_method": "whatever"
})

parser = JSON::PullParser.new json

p CrystalVersion.new parser, base_dir: "/bla"
# => #<CrystalVersion:0x243ef00 @base_dir="/bla", @install_method=Whatever, @version="v1">
```
I just used `JSON.mapper` to not replace `JSON.mapping` in my tests..

You can find the `json_mapper` file here: https://gist.github.com/bew/2af1c4c4bd8e03a5247fba9eeb83a6a9

----
Of course, the `decl` and `more_init` params name can change, I don't have much inspiration at night

Hope this will help

**Comment by bew** [comment]
bump, any thoughts ? should I open a PR ?

**Comment by asterite** [comment]
So the basic issue is that you want `base_dir` not to be nilable.

I'm fine with the composition solution: it's a bit more code, but it's type safe and requires no changes.

```crystal
require "json"

class CrystalVersion
  getter base_dir : String
  getter version : String
  getter install_method : String

  def initialize(@base_dir, @version, @install_method)
  end

  def self.from_json(base_dir, json)
    dummy = Dummy.from_json(json)
    new(base_dir, dummy.version, dummy.install_method)
  end

  def to_json(json : JSON::Builder)
    Dummy.new(version, install_method).to_json(json)
  end

  private struct Dummy
    JSON.mapping({
      version:        String,
      install_method: String,
    })

    def initialize(@version, @install_method)
    end
  end
end

p CrystalVersion.new("a", "b", "c")
p CrystalVersion.new("a", "b", "c").to_json
p CrystalVersion.from_json("a", %<{"version": "b", "install_method": "c"}>)
```

**Comment by mverzilli** [comment]
It looks like option 3 isn't terrible at all. @RX14 may we close this, or do you want to make a stronger case for the other options?

**Comment by RX14** [comment]
Option 3 seems like a bit of unnecessary boilerplate to me, for a large class with many fields manually copying the values to the constructor is a huge pain. Allowing additional arguments, or behaviour to be added when constructing JSON would be a flexible solution.

**Comment by asterite** [comment]
The problem is that right now we do:

```crystal
Type.from_json(string_or_io)
```

That method is defined generically in `Object`. So you'll have boilerplate in any case, because you'll need to add a `Type.from_json(base_dir, string_or_io)` overload that creates the pull parser.

I have this:

```crystal
require "json"

class CrystalVersion
  getter! base_dir : String

  def initialize(@base_dir, @version, @install_method)
  end

  def initialize(@base_dir, json : JSON::PullParser)
    initialize(json)
  end

  JSON.mapping({
    version:        String,
    install_method: String,
  })
end

p CrystalVersion.new("base_dir", JSON::PullParser.new(%<{"version": "a", "install_method": "b"}>))
```

It's very little boilerplate. The only "ugly" thing is the "getter! base_dir`, but I don't think it's better to keep the JSON module simple.

**Comment by RX14** [comment]
@asterite You could define it as `Object.from_json(string_or_io, *args, **nargs)`.

But I think you're right. Option 4 is minimally ugly and requires no changes.
