### ISSUE TITLE
[Suggestion] Include jobs section in the Crystal site

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#4144]
It would be great to have a Crystal jobs board, and I think a good place to have it is under the `crystal-lang.org` domain. (maybe https://jobs.crystal-lang.org/ ?) 
It could be a place where companies looking for Crystal devs can post a request, and because the Language is so new it would make sense to have this in the language home page (which will assure that anyone who uses Crystal can see it)

I know my company is looking for something like that, maybe others as well ?

**Comment by sdogruyol** [comment]
@bararchy it would be great to see companies like that :

**Comment by bew** [comment]
It would be great :)

**Comment by spalladino** [comment]
@bararchy how about a page on the Crystal's [wiki](https://github.com/crystal-lang/crystal/wiki/), editable by anyone, similar to the _Used in production_ one? We'll be happy to share the job offers in some community channels as well.

**Comment by bararchy** [comment]
Could also be cool :) I guess that's a solution , just need to moderate it and maybe create a template for people to use ? I can try to make one if you want

**Comment by mverzilli** [comment]
@bararchy go ahead! We can see how that works and maybe eventually add that to the website :)
