### ISSUE TITLE
[feature request] add values_at method for CSV::Row

### ISSUE THREAD

**Issue by need47** [crystal-lang/crystal#4148]
This can be very handy where a CSV has many columns and you just need a few of them.

require "csv"

csv = CSV.new("Name, Age\nJohn, 20\nPeter, 30", headers: true)
csv.each do |row|
  p row["Name"], row["Age"]
  # p row.values_at("Name", "Age") # feature needed here
end

Thanks

**Comment by bcardiff** [comment]
@need47 you can use `to_h.values_at` meanwhile.

```crystal
csv.each do |row|
  row.to_h.values_at("Name", "Age")  # => {"John", "20"}
                                     # => {"Peter", "30"}
end
```

Since hash exposes `values_at`, it could make sense to allow values_at at CSV::Row without creating an intermediate hash.

PR with specs are welcome.

PS: Please use \`\`\`crystal  to format code (more formatting options are available [here](https://guides.github.com/features/mastering-markdown/))

**Comment by need47** [comment]
Thanks a lot. I have no experience with PR before, but I will take a look.

**Comment by need47** [comment]
FYI, CSV.each [take a block and yield self](https://github.com/crystal-lang/crystal/blob/3c6c75e68f326bb91be35f71ae30672fd454776e/src/csv.cr#L192), you have to call CSV.row first to use the to_h method. Maybe we should yield CSV.row directly.

```
require "csv"

csv = CSV.new("Name, Age\nJohn, 20\nPeter, 30", headers: true)
csv.each do |s|
  p s.row.to_h.values_at("Name", "Age") # note the row
end
```

**Comment by bcardiff** [comment]
You are right, it yields self. Yielding a row directly will mean to call `CSV#row`, which needs to duplicate the current row in memory. I would let the user to make the explicit as it is today and not penalize everybody with this extra allocation.
