### ISSUE TITLE
rand() and divide

### ISSUE THREAD

**Issue by need47** [crystal-lang/crystal#4155]
Is the following expected?

rand(3) / 3 # ok
rand(3)/ 3  # ok
rand(3) /3  # Syntax error in eval:3: unexpected token: DELIMITER_START
rand(3)/3   # Syntax error in eval:3: unexpected token: DELIMITER_START

**Comment by hugoabonizio** [comment]
It seems to happen after every method call ending with ```)```

```
3.to_f() /3
# Syntax error in eval:1: unexpected token: DELIMITER_START
```

https://carc.in/#/r/1q0i

**Comment by bcardiff** [comment]
I don't think it's expected. It's probably a bug in the parser due to regex literals.

Yet I do prefer a space after the `/` either way.

Note:
* `//` operator might come in the future
* `#/` could be defined for any object.

**Comment by need47** [comment]
thanks @asterite for the quick fix.
