### ISSUE TITLE
Blocks can't be captured in macros (using the macro keyword)

### ISSUE THREAD

**Issue by exts** [crystal-lang/crystal#4159]
The most bare example that produces this error is below.

#### Error

> Error in test2.cr:25: macro didn't expand to a valid program, it expanded to:
> 
> --------------------------------------------------------------------------------
>   1.   do
>    2.   puts("hi")
>    3. end
> --------------------------------------------------------------------------------
> Syntax error in expanded macro: example:1: expecting token 'EOF', not 'do'
> 
>   do
>   ^
> 
> test = example do

#### Example

```crystal
macro example(&block)
  {{block}}
end

test = example do
  puts "hi"
end
```

#### What I'm trying to achieve

```crystal
class Demo
  property blocks = {} of String => Proc(Nil)

  macro capture(name, &block)
    @blocks[{{name}}] = {{block}}
  end
end

class Demo2 < Demo
  capture "example" do
    puts "this should be captured"
  end
end
```

**Comment by jasonl99** [comment]
No need for macros to accomplish what you need.  You do have a problem though with the `blocks` property - that needs to be a `class_property` and the methods class methods.

Here's what I came up with, but instead of using "puts" I just saved the strings and output them at the end.

```crystal
class Demo
  class_property blocks = {} of String=>Proc(Nil)

  def self.capture(name, &blk)
    blocks[name] = blk
  end
  
  def self.run_all_blocks
		blocks.map do |name, block|
      "Calling block #{name}: #{block.call}"
    end
  end

  def self.run_block(name)
    "Calling block #{name}: #{blocks[name].call}" if blocks[name]?
  end

end

class Demo2 < Demo
  capture "example" do
    "this should be captured"
  end
  capture "example 2" do
    "this should also be captured"
  end

end

Demo2.run_all_blocks         # ["Calling block example: ", "Calling block example 2: "]	
Demo2.run_block "example 2"  # "Calling block example 2: "
```

**Comment by exts** [comment]
@jasonl99 thanks for that, is this documented the self.name() syntax?
