### ISSUE TITLE
crystal init assumes Git

### ISSUE THREAD

**Issue by rkeene** [crystal-lang/crystal#4165]
crystal init creates a Git repo, even if some other version control system would be more preferable to the user

**Comment by kirbyfan64** [comment]
...like what? Shards only supports Git right now, and IMO Crystal shouldn't pretend to support others unless they're fully supported in the ecosystem.

If you want to use something else, just do `rm -rf .git`.

**Comment by bcardiff** [comment]
The git command is used to also grab author and email when expanding templates.
If there is no git in the system it should expand even so.

I pretty much agree with @kirbyfan64.

I wouldn't be against of a `--skip-git` option in crystal init that would skip invoking git related commands (.gitignore/git init/git config). But that is as much as we should consider today.

**Comment by ozra** [comment]
`init` etc. commands would be very well off in their own binaries, called from the `crystal` binary. Like git calls external helper utils.

Then it's piece of cake switching out functionality like sniffing user name, and initializing repo in `ag silver-nugget-vcs` format (_obviously made up_) or whatever.

- configure your preferred settings in a user conf that crystal looks at (`vcs: ag`), to avoid flag every time
- crystal calls `crystal-vcs-hook-ag sniff-user-info`, `crystal-vcs-hook-ag init`, etc.

Code is not dependant on compiler libs, nor is the compiler dependant on util code like this - so it should bring down unnecessary compilation time also, separate concerns.

Not that I find this urgent at all. I'm completely fine with git, it does everything better than anything I used _before_ - and there is nothing that I miss really.

**Comment by drosehn** [comment]
FWIW, I do prefer `subversion` for my own personal projects.  And just to show how really odd I am, I do keep meaning to try `mercurial` too.  (I keep installing it on all my systems, but haven't gotten around to using it yet).  However, I don't feel it's urgent for crystal to do anything about that.  The ideas that ozra described seem pretty reasonable to me.  And for now, supporting `git` is better than **not** supporting `git`!

**Comment by ysbaddaden** [comment]
Shards is meant, and capable, to support any VCS. Missing support for SVN and Mercurial is just because I don't use them. Pull requests are welcome :-)

Then, we could allow to configure the VCS with `crystal init --svn` for example, but still defaulting to `git`.

**Comment by j8r** [comment]
I think this can be closed in favor of https://github.com/crystal-lang/crystal/issues/8844 and the forum (https://forum.crystal-lang.org/t/poll-how-do-you-use-crystal-init/2921), to avoid one issue per wanted `crystal init` feature. Lots of people would like to have more features in this tools.

**Comment by straight-shoota** [comment]
Yes I think this can be closed. Not necessarily because the discussion should continue in #8844 but because there's a strong preference on using git as default VCS for Crystal projects. Even if shards is on the path to support [mercurial](crystal-lang/shards#458) soon, I don't think there's any doubt about keeping git as default, especially for new users.

And sure, a configurable init tool could allow other options.
