### ISSUE TITLE
Tight Loops, IO & Fibers

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#4173]
I got this small test (IO Tester) in Ruby:
```ruby
f_test = File.open("/tmp/test.data.rb", "w")
f_rand = File.open("/dev/urandom", "r")
stop = false
Thread.new do
  a = 0
  until stop
    a += 1
    read_b = f_rand.read(1024)
    f_test.write(read_b)
    print "\rDone #{a} loops"
  end
end
puts "Going to sleep"
sleep 5
puts "After sleep"
stop = true
f_test.close
f_rand.close
```

And I wanted to created a similar test in Crystal:
```crystal
f_test = File.open("/tmp/test.data", "w")
f_rand = File.open("/dev/urandom", "r")
stop = false
spawn do
  a = 0
  until stop
    a += 1
    bytes = Bytes.new(1024)
    read_b = f_rand.read(bytes)
    f_test.write(bytes[0,read_b])
    print "\rDone #{a} loops"
  end
end
puts "Going to sleep"
sleep 5
puts "After sleep"
stop = true
f_test.close
f_rand.close

```

My issue is that it seems the Fiber will never "return" to the Main program so it can continue, it just seems to copy data forever, In the Ruby example, after 5~ sec, the process will stop.

Is this a bug ? or just a difference in Fibers v.s Ruby's green threads ?

**Comment by RX14** [comment]
On linux, file descriptors which point to files on the file system will never block, so the fiber will never be rescheduled and the event loop will never run. It's an annoying fact, but you'll have to do something like reschedule every 10 write calls using `Fiber.yield`.

**Comment by bararchy** [comment]
@RX14 Indeed adding `Fiber.yield`, I can get it to behave as expected, Thanks :)
