### ISSUE TITLE
Socket class does not support arbitrary protocols

### ISSUE THREAD

**Issue by evilrich** [crystal-lang/crystal#4180]
The Socket class supports these protocols:

```
enum Protocol
    IP   = LibC::IPPROTO_IP
    TCP  = LibC::IPPROTO_TCP
    UDP  = LibC::IPPROTO_UDP
    RAW  = LibC::IPPROTO_RAW
    ICMP = LibC::IPPROTO_ICMP
  end
```

I'm sure that this supports 99.9% of most users needs. However, if you want to support some other protocol, some other type of IP packet (for instance, for fun I was trying to use Crystal to implement a VRRP client), then the standard socket class won't allow you to do this. I can't re-open the Protocol enum and add a new value to it, since that is disallowed by Crystal, so this fixed list is all that is supported.

You could add an additional overload of the ``Socket.new`` method to support protocol as an int.

Maybe you don't want to do that, though. Maybe the answer is, if you're using sockets at this low a level, you have to roll your own support for it via libc.

**Comment by bcardiff** [comment]
Hi @evilrich, it's not just a `Socket.new` issue, but a representation of the `Socket`. Should `@protocol` be `Protocol | UInt8`? That doesn't sound right.

In case you want to implement another protocol I think you should use `Protocol::RAW` that AFAIK allows you to define the header to be sent. 

If the protocol to implement is supported by `netinet/in.h` the right thing would be to update that enum.

**Comment by ysbaddaden** [comment]
The Linux kernel supports a bunch more protocols, that we could add to the Enum, though it depends on the actual OS (that we should check for what they support).

```
26:  IPPROTO_IP = 0,            /* Dummy protocol for TCP               */
28:  IPPROTO_ICMP = 1,          /* Internet Control Message Protocol    */
30:  IPPROTO_IGMP = 2,          /* Internet Group Management Protocol   */
32:  IPPROTO_IPIP = 4,          /* IPIP tunnels (older KA9Q tunnels use 94) */
34:  IPPROTO_TCP = 6,           /* Transmission Control Protocol        */
36:  IPPROTO_EGP = 8,           /* Exterior Gateway Protocol            */
38:  IPPROTO_PUP = 12,          /* PUP protocol                         */
40:  IPPROTO_UDP = 17,          /* User Datagram Protocol               */
42:  IPPROTO_IDP = 22,          /* XNS IDP protocol                     */
44:  IPPROTO_TP = 29,           /* SO Transport Protocol Class 4        */
46:  IPPROTO_DCCP = 33,         /* Datagram Congestion Control Protocol */
48:  IPPROTO_IPV6 = 41,         /* IPv6-in-IPv4 tunnelling              */
50:  IPPROTO_RSVP = 46,         /* RSVP Protocol                        */
52:  IPPROTO_GRE = 47,          /* Cisco GRE tunnels (rfc 1701,1702)    */
54:  IPPROTO_ESP = 50,          /* Encapsulation Security Payload protocol */
56:  IPPROTO_AH = 51,           /* Authentication Header protocol       */
58:  IPPROTO_MTP = 92,          /* Multicast Transport Protocol         */
60:  IPPROTO_BEETPH = 94,               /* IP option pseudo header for BEET     */
62:  IPPROTO_ENCAP = 98,                /* Encapsulation Header                 */
64:  IPPROTO_PIM = 103,         /* Protocol Independent Multicast       */
66:  IPPROTO_COMP = 108,                /* Compression Header Protocol          */
68:  IPPROTO_SCTP = 132,                /* Stream Control Transport Protocol    */
70:  IPPROTO_UDPLITE = 136,     /* UDP-Lite (RFC 3828)                  */
72:  IPPROTO_RAW = 255,         /* Raw IP packets                       */
```

**Comment by ysbaddaden** [comment]
Oh, and this works:

```crystal
ipproto = Socket::Protocol.new(123)
```

**Comment by evilrich** [comment]
Sorry for the slow reply.

@bcardiff said:
> it's not just a Socket.new issue, but a representation of the Socket. Should @protocol be Protocol | UInt8? That doesn't sound right.

@ysbaddaden said:
> The Linux kernel supports a bunch more protocols, that we could add to the Enum, though it depends on the actual OS...

Because in principal anybody could decide to add some new protocol that is not defined in the enum – however complete we might think it is – I'm leaning towards the type union of {{Protocol | UInt8}}. 

However...

@ysbaddaden said:
{{Oh, and this works (just create the enum with an arbitrary number):}}

Ah. I didn't realize that was supported. I'm still getting my feet wet with Crystal. Let me try that.

**Comment by evilrich** [comment]
@ysbaddaden said:
> Oh, and this works (just create the enum with an arbitrary number):
``ipproto = Socket::Protocol.new(123)``

Yes. This works. Thank you.

Maybe we can close this. I think the type union on the protocol parameter might be more obvious to the user, but this workaround is most definitely sufficient.

**Comment by ozra** [comment]
I see that as the "correct solution" and the union as a workaround. It's an enum. It's the Protocol it signifies. Enum can take on numbers that haven't got a named label. Then a value of 123 as Protocol type is what it should be. No? :)

**Comment by ysbaddaden** [comment]
Closing since the initial issue is fixed. Maybe we'd like to have some more standard protocols defined in `Socket::Type` but that may come later, in a pull request.

**Comment by RX14** [comment]
@ysbaddaden did you mean to close this issue?

**Comment by ysbaddaden** [comment]
Yes, wrong button :)

**Comment by evilrich** [comment]
@ozra said:
{quote}Enum can take on numbers that haven't got a named label.{quote}
Yes. That's the point it took me a while to grok. The part of my brain that is still a Java programmer was resisting. :-(

**Comment by ozra** [comment]
@evilrich - hahaha, Java!!! Poor bastard! Well — welcome back from hell! Now you're in _a pretty slightly bunch more rational_ paradise X-D - Java requires you to type everything humptyeleven times and still _not_ be type _safe_. Crystal let's you almost not type types and still be typically cozy safe for realz. Long live the good shit :-) (I'm an old Asm + C++ dude, so I've got my scars too, haha)
