### ISSUE TITLE
Need HTTP::Client.put_form

### ISSUE THREAD

**Issue by huacnlee** [crystal-lang/crystal#4181]
I saw that HTTP::Client has `post_form` method.

Why is there not have `put_form` method?

https://crystal-lang.org/api/0.21.1/HTTP/Client.html#post_form%28path%2Cform%3AHash%2Cheaders%3AHTTP%3A%3AHeaders%3F%3Dnil%2C%26block%29-instance-method

**Comment by molovo** [comment]
This was fixed in #4190 and could be closed.

**Comment by sporgj** [comment]
Is this solved?
