### ISSUE TITLE
Generic method type arguments

### ISSUE THREAD

**Issue by dhruvrajvanshi** [crystal-lang/crystal#4184]
Languages with generic types usually allow generic type arguments for methods. These arguments are separate from class type arguments. These allow methods like map to be typed correctly for container types like Option(T)
```crystal
class Option(A)
  ...
end

class None(A) < Option(A)
  def initialize()
  end
  def map<B>(&block : A -> B) : Option(B) # notice the type argument B here can be instantiated to any type
    None(B).new
  end
end
```
Type argument can be manually specified in case it can't be inferred
```crystal
a.map<Int32> do |x|
  x + 1
end
```
Are there any plans for adding this functionality? Is this even within the scope of the language?

**Comment by RX14** [comment]
This exists in the form of `forall` syntax. 

```cr
def map(&block : A -> B) forall B
  # impl
end
```

**Comment by dhruvrajvanshi** [comment]
Sorry, I didn't read the docs properly. Closing this.

**Comment by dhruvrajvanshi** [comment]
There's some problem with forall bindings
https://carc.in/#/r/1r2h
```crystal
class None(A)
  def initialize
  end

  def bind(&block : A -> None(B)) : None(B) forall B
    None(B).new
  end
end

a = None(Int32).new
b = a.bind do |x|
  x + 1
end
pp b
```
This throws compile time error 
```
Error in line 11: couldn't match Int32 to None(B)

in line 11: instantiating 'None(Int32)#bind()'

in line 5: undefined constant B
```
But B should have been bound by the forall.
Am I doing something wrong?

**Comment by asterite** [comment]
@dhruvrajvanshi The block returns `B`, not `Node(B)`. I think @RX14 was correct. Here's a full working code:

```crystal
class Option(A)
end

class None(A) < Option(A)
  def map(&block : A -> B) forall B
    None(B).new
  end
end

none = None(Int32).new
none2 = none.map { |x| x.to_s }
p typeof(none2)
```

**Comment by dhruvrajvanshi** [comment]
@asterite 
It is working fine with the map method. However, if I try to implement the bind method (see the example in my second comment https://carc.in/#/r/1r2h), it throws "undefined constant B" error.
Here's the second example
```crystal
class None(A)
  def initialize
  end

  def bind(&block : A -> None(B)) : None(B) forall B
    None(B).new
  end
end

a = None(Int32).new
b = a.bind do |x|
  x + 1
end
pp b
```

**Comment by asterite** [comment]
@dhruvrajvanshi It's because:

1. You say `block : A -> None(B)`
2. `a` is of type `None(Int32)` so `A` is `Int32`
3. So, the block is expected to return `None(B)`, but the compiler has no clue about what `B` is here, hence the error

In the block you do `x + 1`. `x` is of type `Int32` (`A`), so `x + 1` is of type `Int32`, it can't be `None(B)`, and there's no way to know what `B` is here.

Here goes the code again, this time I annotate the return type (which is not really needed):

```crystal
class None(A)
  def initialize
  end

  def bind(&block : A -> B) : None(B) forall B
    None(B).new
  end
end

a = None(Int32).new
b = a.bind do |x|
  x + 1
end
pp b
```

**Comment by dhruvrajvanshi** [comment]
@asterite Oh. My bad. I treated bind like map. It's been a long day :(
