### ISSUE TITLE
Building app in Vagrant

### ISSUE THREAD

**Issue by crismotinha** [crystal-lang/crystal#4187]
Hi!

I created a new app inside a Vagrant Machine. Installed Kamel using shards, did some code (below) and when I tried to ```crystal build src/GettingStarted.cr``` I got this: https://gist.github.com/crismotinha/a3fe5aa9cdc08912dcd48e9a322db20d (it's very big). Then, I tried to run the command again, and got the "error second time" gist (in the link above). 

Here's my GettingStarted.cr code:
```
require "./GettingStarted/*"
require "kemal"

module GettingStarted
	get "/" do 
		"oier"
	end

	Kemal.run
end
```

And my vagrant file:
```
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder "data", "/home/vagrant/docs"
  config.ssh.forward_agent = true
end
```

And that's it! As I received the message ```Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues```, I'm oppening this issue. Hope you can see it soon so I can start coding again!

**Comment by crismotinha** [comment]
Now I tried to run ```crystal build --release src/GettingStart ed.cr``` and got:
* in the first time:
```
vagrant@vagrant-ubuntu-trusty-64:~/docs/GettingStarted$ crystal build --release src/GettingStart ed.cr
/usr/bin/crystal: line 102:  4079 Killed                  "$INSTALL_DIR/embedded/bin/crystal" "$@"
```
* in the second time (just ran the same thing again):
```
vagrant@vagrant-ubuntu-trusty-64:~/docs/GettingStarted$ crystal build --release src/GettingStart ed.cr
fork: Cannot allocate memory
0x55b54e: ??? at ??
0x110ecb5: ??? at ??
0x1440b74: ??? at ??
0x1cc6fa5: ??? at ??
0x5b26c9: ??? at ??
0x57e19d: main at ??
0x7fcc7642af45: __libc_start_main at ??
0x556281: ??? at ??

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

**Comment by bew** [comment]
the error is `cannot allocate memory`, how much ram did you configured for your Vagrant ?

**Comment by crismotinha** [comment]
I didn't configured memory, and I don't know the default... I'm looking for how to allocate more memory right now

**Comment by crismotinha** [comment]
Ok, I followed this instructions: https://thewebfellas.com/blog/modifying-vagrant-box-memory-settings and still got the same error. Trying now to allocate more

**Comment by crismotinha** [comment]
With 2048, I got some package errors, after I installed those, I finally build it!
Here's a note for anyone trying to run Crystal on Vagrant / Ubuntu : you need at least 2048mb of memory. :) 
Thank you and I'm closing this issue :)
