### ISSUE TITLE
ECR render at runtime

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang/crystal#4194]
Hi i'm using Kemal and I have to recompile files each time html change in ecr files.

Would be posible that ECR return a string with html changes rendered without recompile?

Actually ECR do this:

```crystal
# greeting.ecr
# Greeting, <%= name %>!

require "ecr/macros"

name = "World"

io = IO::Memory.new
ECR.embed "greeting.ecr", io
io.to_s # => "Hello World!"

# Output:
# io << "Hello "
# io << name
# io << "!"
```

Would be possible do something like this:

```crystal
# greeting.ecr
# Greeting, <%= name %>!

require "ecr/render"

name = "World"
puts ECR.render "greeting.ecr", name

# Output
# Greeting, World!
```

An useful use-case would be `render` in Kemal (see: kemalcr/kemal/issues/335)

**Comment by bew** [comment]
To follow your idea, I think `ECR.render` should render at runtime, and  `ECR.render!` should render at compile time

**Comment by ysbaddaden** [comment]
You want a safe templating language, one where the logic is interpreted at runtime, thus reloadable, since you can reload, reparse and reinterpret (at least in non release mode).

But ECR allows any Crystal code, which must be compiled, and it can't reload templates at runtime.

**Comment by faustinoaq** [comment]
@ysbaddaden ok, Mustache(Crustache) and Liquid shards are templating languages like you said.
Maybe, could be good a shard for a template language based on ECR syntax :sweat_smile:
