### ISSUE TITLE
Union type not always correctly reduces in && shorthand

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#4209]
Unfortunately I don't have a small example at hand, but while porting crystal-gobject to the latest release (0.21.1) or master, I encountered the following error:
```
in lib/gobject/src/generated/g_object/value.cr:267: argument 'v_string' of 'LibGObject#value_set_string' must be Pointer(UInt8), not (Pointer(UInt8) | String)

      __return_value = LibGObject.value_set_string(to_unsafe.as(LibGObject::Value*), v_string && v_string.to_unsafe)
```

Writing it as
```crystal
tmp = v_string.to_unsafe if v_string
LibGObject.value_set_string(to_unsafe.as(LibGObject::Value*), tmp)
```

works, however reusing the same variable name there does not.

**Comment by jhass** [comment]
Seems fixed in latest 0.29.0, possibly by #7785

**Comment by jhass** [comment]
Oh well, actually it seems to just not reproduce on OS X...  actually happend to check this yesterday on  linux with 0.28.0 where it still was broken. Gonna dig more on the  weekend  and try to reduce.

**Comment by jhass** [comment]
Reduced:
``` 
lib LibFoo
  fun foo(foo : UInt8*)
end

string = "foo"
LibFoo.foo(string && string.to_unsafe)
```

**Comment by asterite** [comment]
I'm not sure about this.

The type of `string && string.to_unsafe` is `String | Pointer(UInt8)` and we currently only call `to_unsafe` on non-union stuff, so you can either pass a `String` or a `Pointer(Uint8)` to something that expects `Pointer(UInt8)` but not both.

I'd rather not make the C bindings logic more complex then that. My advice is to do:

```crystal
LibFoo.foo(string ? string.to_unsafe : Pointer(UInt8).null)
```

But maybe we can leave this open and eventually improve this, I don't know.

**Comment by jhass** [comment]
Well, the weird thing is that it used to work before  0.21, if I can trust past me  :D

**Comment by straight-shoota** [comment]
Closing, per https://github.com/crystal-lang/crystal/issues/4209#issuecomment-493958436. The current behaviour seems fine as is and the issue can be easily worked around.
