### ISSUE TITLE
undefined method 'merge!' for Set

### ISSUE THREAD

**Issue by need47** [crystal-lang/crystal#4211]
No Set#merge! defined in source, though there is an example of demonstrating Set#merge! at [api doc](https://crystal-lang.org/api/0.21.1/Set.html). The closest one is Set#concat

**Comment by kirbyfan64** [comment]
Looks like it was renamed, but the docs were never updated:

https://github.com/crystal-lang/crystal/commit/db04539eaa416b1286eee4d5948d50801381999e
