### ISSUE TITLE
Support headers and query strings in HTTP::WebSocket

### ISSUE THREAD

**Issue by adamtrilling** [crystal-lang/crystal#4222]
`HTTP::WebSocket` doesn't support query strings or headers. I need it to do so for a project that I'd like to use Crystal for, so I'd like to take a crack at making it work. For query strings, the solution in #3234 should work. For headers, I'm envisioning adding a `headers` parameter to `HTTP::WebSocket.new()`, like:

```
def self.new(uri : URI | String, headers : HTTP::Headers? = nil)
```

and

```
def self.new(host : String, path : String, port = nil, tls = false, headers : HTTP::Headers? = nil)
```

Then I will handle the parameter in the constructors for `HTTP::WebSocket::Protocol`. What do y'all think?

**Comment by sdogruyol** [comment]
Now that we have #4227 merged, can we close this?
