### ISSUE TITLE
Missing gamma method in LibM

### ISSUE THREAD

**Issue by KCreate** [crystal-lang/crystal#4223]
When calling `Math.gamma` with an argument that's not `Float32` or `Float64`, crystal tries to call `LibM.tgamma`. This method doesn't exist.

A fix for this would be to replace the `gamma` method at [src/math/math.cr#L64](https://github.com/crystal-lang/crystal/blob/a36e2b48bb51b84576e2aad5f55b26eeac009cd6/src/math/math.cr#L64) with the following method:

```crystal
def gamma(value)
  LibM.tgamma_f64(value.to_f)
end
```

**Comment by bcardiff** [comment]
I would follow the same pattern as in line 25.
The issue you highlight with `gamma` is also present in `lgamma`.

Do you want to send a PR with a spec for both?

**Comment by KCreate** [comment]
Yes! I'll send in a PR later.
