### ISSUE TITLE
Defining method definitions within spec describe blocks

### ISSUE THREAD

**Issue by danielpclark** [crystal-lang/crystal#4228]
Within a describe block trying to def a method returns `can't declare def dynamically`.  I searched the source code for spec testing on defining methods in rspec style with `let` and it doesn't exist.

What's the rule, or standardized way to do this in spec tests?

**Comment by bcardiff** [comment]
The current approach is to have `private def` in the `_spec.cr` file. So they don't collide with other defs in other files. But they are global in the `_spec.cr` without contextual information. That is a current limitation of the built in spec.

**Comment by asterite** [comment]
Closing. Using `private def` is the way to go for now (and I think forever)
