### ISSUE TITLE
Return default value for method?

### ISSUE THREAD

**Issue by MrSorcus** [crystal-lang/crystal#4233]
What about something like this?
```
def test(value) : Int32(5)
  something_here_with_value
end
```
If `something_here_with_value` doesn't return `Int32`, return default value `5`
I don't find any info about this...

**Comment by kostya** [comment]
```crystal
def test(value) : Int32
  something_here_with_value || 5
end
```

**Comment by MrSorcus** [comment]
Offtop.
А можно с тобой как-то контактировать? Почта? Токс? Жаббер?

**Comment by MrSorcus** [comment]
Offtop.
@kostya Хоть бы какой-нибудь ответ написал... :-(

**Comment by RX14** [comment]
Can you keep it English please.

**Comment by MrSorcus** [comment]
@RX14 ok, no problems.
@kostya How can i contact with you? Mail? Tox? Jabber? Thanks.
