### ISSUE TITLE
IO.gets and handling of ctrl-d on the unix command-line

### ISSUE THREAD

**Issue by drosehn** [crystal-lang/crystal#4240]
This is on:
```cr
# crystal --version
Crystal 0.21.1 (2017-03-18) LLVM 4.0.0
# uname -a
Darwin my.host 14.5.0 Darwin Kernel Version 14.5.0: Sun Sep 25 22:07:15 PDT 2016; root:xnu-2782.50.9~1/RELEASE_X86_64 x86_64
# # aka macOS 10.10.5 (Yosemite)
```
Given the program:
```cr
STDIN.blocking = true

printf "Enter string or EOF:\n"

ustr = STDIN.gets
if ustr.nil?
  STDERR.printf "\n <-- EOF! -->\n"
  exit 1
end
printf "Got:  '%s' len=%d\n", ustr, ustr.size
exit 0
```

When I compile and run this program at the unix command-line, and if I want to type `ctrl-d` to generate EOF on the `gets` read, it seems that I have to hit `ctrl-d` three times for my program to see the EOF.  I can type `ctrl-d` once, and the program waits for more input.  If I then hit the `return` key, `gets` returns a zero-byte string.  The same happens if I hit two `ctrl-d`s and the `return` key.  But if I hit three `ctrl-d`s in a row, then `gets` returns without waiting for the `return` key, and returns EOF.

I included the `STDIN.blocking = true` line because my original program had that (and I do add that to many of my crystal programs), so I thought that might have been what caused this behavior.  However, the sample program behaves the same if `STDIN.blocking` is set to `false` instead of `true`.

**Comment by asterite** [comment]
It's a bug because of a refactor I did where IO#peek is used.

**Comment by asterite** [comment]
Thank you for reporting this!
