### ISSUE TITLE
Method override logic may force superfluous cast to compile

### ISSUE THREAD

**Issue by bcardiff** [crystal-lang/crystal#4247]
The following code fails to compile as is.
If the comment 

```crystal
abstract class Foo
  abstract def read

  def read(type : T.class) : T forall T
    read.as(T)
  end
end

class Bar < Foo
  @next : String | Int32 = 0

  def read
    @next # .as(String | Int32 | Float32) # uncomment cast to compile
  end

  def read(t : Float32.class) : Float32
    read(Int32).to_f32
  end
end

b = Bar.new.as(Foo)
b.read(Float32)
```

```
Error in foo.cr:22: instantiating 'Foo+#read(Float32:Class)'

b.read(Float32)
  ^~~~

in foo.cr:5: can't cast (Int32 | String) to Float32

    read.as(T)
    ^
```

It is important that the `Bar` is casted to `Foo` to reproduce this.
Since the cast is a workaround to this is probably a corner case about identifying coverage over a method overloads.

The following is another sample that shows the issue, unless uncommented or `read(type)/read(t)` are swapped.

```crystal
class Bar
  @next : String | Int32 = 0

  def read
    @next # .as(String | Int32 | Float32) # uncomment cast to compile
  end

  def read(type : T.class) : T forall T
    read.as(T)
  end

  def read(t : Float32.class) : Float32
    read(Int32).to_f32
  end
end

b = Bar.new
b.read(Float32)
```

--- 

```
$ crystal --version
Crystal 0.21.1 (2017-03-07) LLVM 3.9.1
```

**Comment by asterite** [comment]
The problem seems to be that the other overload is considered:

```crystal
def read(type : T.class) forall T
  {{ puts "HERE!" }}
end

def read(t : Float32.class)
end

read(Float32)
```

This prints "HERE!" at compile time, but that method should probably not be considered for typing.

**Comment by bcardiff** [comment]
When the snippets i showed compile the result is the expected one. So at least in non top level methods the issue is not which overload is chosen.

**Comment by asterite** [comment]
Oh, actually, I think this is not a bug. In the first snippet you have `Foo+#read(Float32)` so both `Foo#read(Float32)` and `Bar#read(Float32)` will be analyzed. To analyze `Foo#read(Float32)` `Foo#read` is analyzed, which is `Bar#read`, which returns either String or Int32, and that can't be cast to Float32.

**Comment by asterite** [comment]
In any case I think it boils down to sitting down and defining the formal semantic for method resolution.

I think that snippet is from crystal-db. We should probably model it in another way (maybe doing `read.as?(T) || raise "don't know how to handle T"`)

**Comment by bcardiff** [comment]
But there is no way to call `Foo`'s `#read(Float32)` that won't en up calling Bar's override.

If there would be a `Qux` class whose `#read()` returns `String | Int32` (and does not provide a `read(Float32)` override) I would get it that a `Foo+` could end up calling a cast that does not make sence and the compiler error would is the right thing to do.

So I think is a issue regarding how cases are analyzed.

**Comment by bcardiff** [comment]
Closing this as duplicate of #4176.

@asterite the challenge is that in `read.as?(T)` T might be a nillable type. 

For now crystal-sqlite3 might need to have an additional cast in the read.

**Comment by asterite** [comment]
Maybe:

```crystal
value = read
if value.is_a?(T)
  value
else
  raise
end
```

**Comment by bcardiff** [comment]
🤦‍♂️ I've been coding too much

**Comment by asterite** [comment]
😃 

In any case that moves the error from compile time to runtime, so it's something that we definitely want to rethink and tackle.
