### ISSUE TITLE
XML#parse not working for response.body_io

### ISSUE THREAD

**Issue by need47** [crystal-lang/crystal#4248]
The [XML#parse(io : IO)](https://crystal-lang.org/api/0.21.1/XML.html#parse%28io%3AIO%2Coptions%3AParserOptions%3DParserOptions.default%29%3ANode-class-method) method seems not working correctly on response.body_io.
```crystal
require "http/client"
require "xml"

url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi"
form = {
  "db" => "gene",
  "id" => "1956"
}

HTTP::Client.post_form(url, form) do |response|
  if response.status_code == 200
    # xml = XML.parse(response.body_io.gets_to_end) # this is ok
    xml = XML.parse(response.body_io) # not working
    p xml.to_xml
  end
end
```

Btw, the same example on [play](https://play.crystal-lang.org/#/r/1to6) gave the following error:

> Program received and didn't handle signal SYS (31)

**Comment by asterite** [comment]
@need47 When you say "seems not working correctly", what do you mean? I ran the snippet and it worked fine (outside of the playground)

**Comment by need47** [comment]
@asterite the snippet compiled and ran fine, while the output is not right. Basically I'm getting an empty xml now. But I'm expecting this: [https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=gene&id=1956](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=gene&id=1956)

**Comment by asterite** [comment]
Hmm... for some reason xml doesn't like to be fed small chunks of bytes. This happens because the current ssl socket is not buffered. If I change it to buffer it starts working well. I guess that's a solution though I don't know why libxml works wrong otherwise.

**Comment by need47** [comment]
@asterite thanks for the quick fix.
