### ISSUE TITLE
Want: "capturing" in `when` predicate

### ISSUE THREAD

**Issue by RomanHargrave** [crystal-lang/crystal#4251]
Example (from scala)

```scala
// where `that()` is a function that returns AnyRef
that() match {
   case asString: String =>
      asString
   case asXWithType: X[T] =>
      asXWithType
   default => 
}
```

How it would look in crystal:

```crystal
case that()
when asIO : IO
   # do something
when Nil
   # do something
end
```

My reason for suggesting this behavior is that understandably, when using `case` as a a type matcher with a getter (or, as some folks say, a synthetic property), the compiler will not restrict the return type of further calls within a `when` block to the previously matched type since it may not know if the method will return that value again, to explain in code:

```crystal
case that() # that() : IO?
when IO
   function_wants_io(that()) # Compiler error - no overload matches '#function_wants_io' with type (IO | Nil)
end
```
The solution to the above, as far as I can currently see, would be to assign that() to a local variable, within the parent scope of the `case` block, and match against it, as well as using it futher calls:

```crystal
localThat = that()
case localThat
when IO
   function_wants_io(localThat) # No compiler error, since IO, not Nil, type is implicit
end
```

For reasons evident, this is not as elegant as it could be.

This behaviour could also be extended regular expression capture groups as a sort of "extractor". If I recall, ruby has something to this effect, as does scala.

Currently, the compiler accepts statements like `when localvar : Type`, however I am unsure if this is reserved for, or already used by, a feature I am unaware of. If that is not the case, I think that it would be a welcome feature.

**Comment by RomanHargrave** [comment]
(Note) I hope this doesn't seem redundant, but the manual doesn't seem to suggest this is possible

**Comment by bcardiff** [comment]
The following works as expected:

```crystal
def foo
  rand > 0.5 ? 1 : "a"
end

case v = foo
when Int32
  v + 1
when String
  v.upcase
end
```

You can assign the variable in the same call in the `case`. Pretty much as in if/while. Using `asIO : IO` in the when is a variable declaration so if you try to use it you will get "read before assignment to local variable"

When you assign a variable in the case, it's type get restricted as in https://crystal-lang.org/docs/syntax_and_semantics/if_varis_a.html

There are some additional use cases of case in https://crystal-lang.org/docs/syntax_and_semantics/case.html

**Comment by RomanHargrave** [comment]
WRT `x : T` being a variable declaration, that is what I was wanting (but with implicit assignment as in some other languages). But if it has, to some extent, already been implemented by assigning at the beginning of the case block, I suppose that solves _my_ problem.

I don't think that the current behaviour would satisfy newcomers wants such as named group extraction from positive regex matches inline with the predicate, e.g. scala:

```scala
val string = "1 2 3"
val expr = "(\d) (\d) (\d)".r
string match {
   case expr(d1, d2, d3) => // d1 = 1, d2 = 2, d3 = 3
}
```

Granted, something like that is far out of scope, but is in the same vein.

**Comment by bcardiff** [comment]
Having predicates to match and deconstruct data is a nice idiom, but we don't have it.
I don't think there will be any efforts in supporting them in the language any time soon. 
(There are some experiments to use some functional idioms like `dhruvrajvanshi/crz`. In case you prefer to code in that way.)

For the case you mention there are some alternatives. Some are particular for regex matching (`$1`) but others work the same way for any data structure.

```crystal
string = "1 2 3"

case m = string.match /(\d) (\d) (\d)/
when Regex::MatchData
  { m[1], m[2], m[3] }
when Nil
  "no match"
end

case m = string.match /(\d) (\d) (\d)/
when Nil
  "no match"
else
  { m[1], m[2], m[3] }
end

case string.match /(\d) (\d) (\d)/
when Nil
  "no match"
else
  { $1, $2, $3 }
end

if m = string.match /(\d) (\d) (\d)/
  { m[1], m[2], m[3] }
end

if string =~ /(\d) (\d) (\d)/
  { $1, $2, $3 }
end
```

**Comment by RomanHargrave** [comment]
Thanks for pointing me to crz and your other responses.

**Comment by asterite** [comment]
Just use `case` with variable assignment at the top. It works well.
