### ISSUE TITLE
Suggestion: A built-in way to make a block be run every X amount of time

### ISSUE THREAD

**Issue by meew0** [crystal-lang/crystal#4255]
I'm looking for something like this:

```cr
every(5.seconds) do
  print "This will be run every five seconds."
end
```

Obviously it's fairly easy to implement this yourself by using a loop with `sleep`. However, there are some caveats: if the code in the block runs for a non-negligible amount of time, then that time has to be measured to ensure accuracy, and if an uncaught exception crashes the block, then, depending on the exact implementation, the loop might stop entirely without that being apparent to the underlying program.

Furthermore, I find myself needing this feature quite often when developing various projects. This is, of course, highly dependent on the kind of projects one writes code for, but I feel like I can't be the only one. Making a shard for this is an option, but it's a really small thing to make an entire shard for, and there would probably end up being a slew of competing ones with no clear advantages to others.

Therefore I propose for something like this to be built into to the language or standard library. It could be tightly integrated with and a useful addition to the existing asynchronous programming features. By making it unnecessary for projects to use their own custom solution, it would also help standardise Crystal code as a whole.

Some more problems I've considered, with my own thoughts on them:

- What would the method be called? In the above code example, I've used `every`, which is more Ruby-like in that it feels more like English, but something like `schedule` would be more descriptive.
- Would the method block code execution? In the context of the language it seems to me like it should be non-blocking, but a blocking method allows for greater flexibility in that it can be made to be non-blocking if one desires.
- How should exceptions be handled – should they terminate the loop as a whole or just the current block? There's no clear answer to this for me; in my own code I've usually needed it to keep the loop alive and just terminate the block, but use cases where terminating the whole loop is more useful are imaginable.

**Comment by kostya** [comment]
https://github.com/kostya/cron_scheduler

**Comment by meew0** [comment]
Something like that would solve the problem, but it's a bit overkill: I don't need crontab-like functionality, I just need something that runs something every, say, two minutes. Regardless of that, I still think it should be in the standard library, because as a whole the language is focused on asynchronous programming and something like this comes up quite often with that (for me, at least).

**Comment by hugoabonizio** [comment]
Hi @meew0! I've been working on this lib to achieve this behavior: https://github.com/hugoabonizio/schedule.cr

**Comment by asterite** [comment]
I'm not sure this is generally useful, so it might be better to put it in a shard (there are maybe too many decisions to make about such functions, about what happens when an exception happens, logging, etc.), and it's small enough that it's better to keep it outside the std.

**Comment by RX14** [comment]
@asterite Surely a simple (<10 line method) solution with no exception handling and no logging would be simple to add to the stdlib. It's a pretty useful tool for simple concurrent programs.

**Comment by asterite** [comment]
The problem is that this might not be enough for some, and so endless discussions about the subject will spawn.

Is there some other programming language where such function/method is in the standard library?

**Comment by kirbyfan64** [comment]
Python: https://docs.python.org/3/library/sched.html
JavaScript: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval

**Comment by asterite** [comment]
This can be defined in a shard.
