### ISSUE TITLE
Macro `dump` breaks compilation 

### ISSUE THREAD

**Issue by bew** [crystal-lang/crystal#4257]
This fails to compile: https://carc.in/#/r/1tx8
```crystal
macro dump
  anything
end
```
Gives:
```
# ... a lot of error trace ... 

in /usr/lib/crystal/char.cr:704: expanding macro

      raise InvalidByteSequenceError.new("Invalid char value #{dump}")
                                                               ^

in macro 'dump' eval:1, line 1:

>  1.   anything

undefined local variable or method 'anything'
```
The issue lies at [src/char.cr L704](https://github.com/crystal-lang/crystal/blob/e276338875e54d18c05a6194703ea46b52f083e9/src/char.cr#L704) where it expects to call `Char#dump` but instead calls the top level macro `dump` defined above, because macro lookup appends before method lookup. 

Even tough the `dump` macro name is not that good for a top level macro, it could be a common issue easily reproducible with minimal code:
```crystal
macro call
  anything
end

class A
  def call
    puts "method call"
  end
  
  def initialize
    call
  end
end

A.new
```
https://carc.in/#/r/1u15 (same error) 

I don't think this can be simply resolved... 

Note: if someone can find a better name for this issue... Ty

**Comment by Sija** [comment]
See #236.

**Comment by bew** [comment]
I see I'm not the first one with this issue ^^
Thanks I'll close this one
