### ISSUE TITLE
HTTP requests hanging

### ISSUE THREAD

**Issue by RX14** [crystal-lang/crystal#4261]
```cr
require "json"
require "http"

struct Body
  JSON.mapping(
    content: String
  )
end

server = HTTP::Server.new(8080) do |context|
  context.request.body.try do |body|
    body = Body.from_json(body)
    puts body.content
  end
end

server.listen
```

Test using `curl -v -d '{"content": "foo"}' http://localhost:8080/`.

Expected result: `foo` printed to server console, HTTP request returns response.

Actual result: CURL hangs after sending data, `foo` not printed to server stdout. Manually quitting curl with `^C` will print `foo` to the console and complete the HTTP request.

I think something weird is happening with `IO::Sized`, but I'm not entirely sure whether the blame lies there or in the JSON parsing.

```
crystal -v
Crystal 0.21.1 [3c6c75e] (2017-03-06) LLVM 3.5.0
```

**Comment by asterite** [comment]
Ugh, another issue because of `IO#peek`. I think we'll need to revert those changes, it's a mess and it's probably a bad design. I was the only one who though about how to deal with that, so it's better if we revert all of that and think it all over again. Sorry...

**Comment by asterite** [comment]
Or maybe it was just a small bug :-)
