### ISSUE TITLE
Invalid docs for Slice#copy_from and Slice#move_from

### ISSUE THREAD

**Issue by KCreate** [crystal-lang/crystal#4262]
The docs specify that `Slice#copy_from` and `Slice#move_from` truncate the source if it doesn't fit into the target. They are raising an `IndexError` exception however.

Code to reproduce:
```crystal
source = Bytes.new 10 { |i| i.to_u8 }
target = Bytes.new 5 { 0_u8 }
target.move_from source
```

There is even a spec for the (wrong?) behaviour: [spec/std/slice_spec.cr#L202](https://github.com/crystal-lang/crystal/blob/d3ae522061292aa646ef916b8bcf4ec33d1b012c/spec/std/slice_spec.cr#L202)

I'd suggest giving `Slice#copy_from` and `Slice#move_from` the behaviour specified in the docs, making this a breaking change.

Any thoughts?

**Comment by RX14** [comment]
This isn't incorrect behavior, just incorrect documentation (ref https://github.com/crystal-lang/crystal/pull/2973#r70282666).

We should consider adding truncating versions though.
