### ISSUE TITLE
Add a '-x'-like option for 'crystal build', 'crystal run', and 'crystal tool format'

### ISSUE THREAD

**Issue by drosehn** [crystal-lang/crystal#4266]
Both perl and ruby have a '-x' option to the interpreter.  What it does is it instructs the interpreter to ignore all lines on the input file until it reads a line matching `/^#!.*perl/` (*for perl*) or `/^#!.*ruby/` (*for ruby*).  Here is a simple sample:
```cr
#!/bin/sh
exec ruby -x -S $0 ${1+"$@"}
exit 1  #  in case the 'exec' fails

# Thanks to -x, ruby ignores everything before the following line:
#! ruby
  printf "       Ruby says Hello World!       ARGS='%s'\n", ARGV.join("' '")
```
produces:
```cr
# ./ruby-x.rb aa 'b b'
       Ruby says Hello World!       ARGS='aa' 'b b'
```
There are some crazy programmers (like me) who sometimes would like to write a single self-contained source file which works in both ruby and crystal.  Often we find that there's some tiny difference between ruby and crystal which frustrates us -- **especially** when it is a **tiny** difference.  But many of these smaller differences could be easily addressed (by the crazy programmer) if crystal supported a feature similar to `-x`.  It doesn't have to be called `-x`, but an option which works the same way, and could be used on `build`, `run`, and maybe `tool format` (the `format` tool would simply copy all lines before the '#! crystal` line, with no attempt to parse them or format them).

If this option was available, then requests like #4256 would be trivial for the crazy programmer to implement, without asking for any changes to the crystal language.

**Comment by drosehn** [comment]
This skipping-ability can be faked right now, but it'd be convenient if the `crystal` command supported it directly.  When it comes to #4256, consider:
```cr
#!/bin/sh

ruby -x -S $0 ${1+"$@"}

echo "# - - - -"
# fakery:
CRSRC="/tmp/$(basename $0 .crrb)-$$.cr"
awk 'BEGIN { p = 0; } \
    /^#!.*crystal/ { p = 1 } \
    /^__END__$/    { if (p) exit (0); } \
    { if (p) { print $0; } }' do_all.crrbpl >| "$CRSRC" || exit 1

crystal run "$CRSRC" -- ${1+"$@"}

exit 0

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Thanks to -x, ruby ignores everything before the following line:
#! ruby
  class Object
    alias responds_to? respond_to?
  end
  printf "       Ruby says Hello World!       ARGS='%s'\n", ARGV.join("' '")

# Ruby will continue to process the rest of the file, stopping
# only if it comes across a line of '__END__' or '__DATA__'.

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# I'm using 'awk' fakery to get crystal "ignore" all lines before:
#! crystal
  #   This odd-looking statement is needed only for crystal, but
  #   'STDIN.blocking = true' would be a run-time error in ruby.
  STDIN.blocking = true if STDIN.responds_to?(:blocking)

  printf "    Crystal says Hello World!       ARGS='%s'\n", ARGV.join("' '")
  exit 0
__END__

... garbage lines which should be ignored by both...
```
This produces:
```cr
# ./responds_to.crrb aa 'b b' 'c* >c'
       Ruby says Hello World!       ARGS='aa' 'b b' 'c* >c'
    Crystal says Hello World!       ARGS='aa' 'b b' 'c* >c'
# - - - -
    Crystal says Hello World!       ARGS='aa' 'b b' 'c* >c'
```
Ruby prints both "hello world" messages, because it's executing the code for crystal.  Note that this is a **lot** more flexible than simply adding `respond_to?` to address the wishes of one crazy programmer.  Also note that the programmer could have "crystal-specific" code start before the code which would be executed by both ruby and crystal, depending on which tiny difference they're trying to address.

IMO, it would be find if this `-x`-like feature would only work with a single input file.  If someone has a project with multiple source files in it, then there are other ways to address ruby-vs-crystal issues.  IMO.

**Comment by drosehn** [comment]
Actually, for this example it's nicer to have a crystal-specific part before the common part:
```cr
#!/bin/sh

ruby -x -S "$0" ${1+"$@"}

echo "# - - - -"
# fakery:
CRSRC="/tmp/$(basename "$0" .crrb)-$$.cr"
awk 'BEGIN { p = 0; } \
    /^#!.*crystal/ { p = 1 } \
    /^__END__$/    { if (p) exit (0); } \
    { if (p) { print $0; } }' "$0" >| "$CRSRC" || exit 1
crystal run "$CRSRC" -- ${1+"$@"}

exit 0

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# I'm using 'awk' fakery to get crystal "ignore" all lines before:
#! crystal
  #   This odd-looking statement is needed only for crystal
  STDIN.blocking = true
  printf "     Crystal says Hello World!       ARGS='%s'\n", ARGV.join("' '")

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Thanks to -x, ruby ignores everything before the following line:
#! ruby

  printf "Crystal+ruby says Hello World!       ARGS='%s'\n", ARGV.join("' '")
  exit 0
```
produces:
```cr
# ./add-block.crrb aa 'b b' 'c* >c'
Crystal+ruby says Hello World!       ARGS='aa' 'b b' 'c* >c'
# - - - -
     Crystal says Hello World!       ARGS='aa' 'b b' 'c* >c'
Crystal+ruby says Hello World!       ARGS='aa' 'b b' 'c* >c'
```

**Comment by asterite** [comment]
Sorry, I find this too cryptic. Also, crystal is not an interpreted language.
