### ISSUE TITLE
Instance variable must be BaseService not BaseServiceImpl

### ISSUE THREAD

**Issue by teodor-pripoae** [crystal-lang/crystal#4273]
Hi,

It looks like generic arguments cannot allow subtypes. First example works, second fails with this error message (crystal 0.21.1 OSX) :

```
Error in foo.cr:14: instantiating 'Server:Class#new(Array(MyImpl))'

x = Server.new([MyImpl.new])
           ^~~

in foo.cr:10: instance variable '@services' of Server must be Array(BaseService), not Array(MyImpl)

  def initialize(@services : Array(BaseService))
```

```crystal
class BaseService
end

class MyImpl < BaseService
end

class Server
  property service : BaseService

  def initialize(@service : BaseService)
  end
end

x = Server.new(MyImpl.new)
```

```crystal
class BaseService

end

class MyImpl < BaseService

end

class Server
  property services : Array(BaseService)

  def initialize(@services : Array(BaseService))
  end
end

x = Server.new([MyImpl.new])
```

**Comment by asterite** [comment]
`[MyImpl.new] of BaseService`

Sorry for the brevity, this issue is reported every week :-(

**Comment by RX14** [comment]
@asterite Maybe we should compile a "stock response" to this with links to the issues with good examples and discussion of reasoning. This means a quick low-overhead issue response while giving the user some understanding on this issue.

**Comment by asterite** [comment]
@RX14 We can probably put an answer in the FAQ section of the wikipedia, but I'm lazy to write an answer :-(
