### ISSUE TITLE
Strange output of String#underscore with strings of uppercased letters and numbers

### ISSUE THREAD

**Issue by olbat** [crystal-lang/crystal#4278]
I'm not really sure what the output of `String#underscore` should be with uppercased strings containing numbers, but I think that the current behavior is wrong:
```bash
$ crystal eval 'p "ABC123".underscore'
"ab_c123"

$ crystal --version
Crystal 0.21.1 [3c6c75e] (2017-03-06) LLVM 3.5.0
```

Here is how Rails [String#underscore](http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-underscore) behaves:
```bash
$ ruby -rrails -e 'p "ABC123".underscore'
"abc123"

$ ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
$ ruby -rrails -e 'puts Rails.version'
5.0.1
```

**Comment by bew** [comment]
Short version:
```cr
puts "AB1".underscore
```
Gives `a_b1` (https://carc.in/#/r/1uq9)

**Comment by olbat** [comment]
Oops, sorry for the second PR, I worked offline and didn't check before pushing my PR 😳
