### ISSUE TITLE
'require' vs fully-qualified pathnames

### ISSUE THREAD

**Issue by drosehn** [crystal-lang/crystal#4286]
This is on:
```cr
# crystal --version
Crystal 0.21.1 (2017-03-18) LLVM 4.0.0
# uname -a
Darwin my.host 14.5.0 Darwin Kernel Version 14.5.0: Sun Sep 25 22:07:15 PDT 2016; root:xnu-2782.50.9~1/RELEASE_X86_64 x86_64
# # aka macOS 10.10.5 (Yosemite)
```
Given the program:
```cr
require "/tmp/some-code"

puts "Hi from #{File.basename(__FILE__)}"
```
crystal produces a compile-time error:
```cr
# ls -l /tmp/some-code*
-rw-------  1 gad  staff  42 Apr 13 14:47 /tmp/some-code
-rw-------  1 gad  staff  42 Apr 13 14:47 /tmp/some-code.cr
# crystal run PR_fq-require.cr 
Error in PR_fq-require.cr:2: while requiring "/tmp/some-code": can't find file '/tmp/some-code' relative to '...current-directory...'

require "/tmp/some-code"
^
```
A simple work-around is to change the program to use `require "some-code"` and then add `/tmp` to the `CRYSTAL_PATH` environment variable.

**Comment by asterite** [comment]
Not being able to require absolute paths is a feature, so that you can share your project and it will work when someone checks it out.

You can use shards and specify a dependency with [path](https://github.com/crystal-lang/shards/blob/master/SPEC.md#path)
