### ISSUE TITLE
cannot alocate memory ,,

### ISSUE THREAD

**Issue by codenoid** [crystal-lang/crystal#4288]
hi, my os is Ubuntu 16.04 (Xenial), and i just installing Crystal on my computer, and i try to use kemalcr (crystal web framework), then,, i got some error 
say : Cannot Alocate Memory
https://s27.postimg.org/s5vdlu56b/kemalb.png

**Comment by bew** [comment]
How many ram do you have on your computer? 
Try building without the release option, it might take less memory. 

You can check the available memory with `free -h`

**Comment by codenoid** [comment]
hmm, just 283MB,,, but can i run in 5GB free  memory (on my desktop) ?

**Comment by bew** [comment]
> just 283MB...

This is too low I think, you'll get into trouble (and slow-ness) soon if you don't add more ram.

> but can i run in 5GB free memory (on my desktop) ?

Is it a question? What do you mean?

**Comment by RX14** [comment]
I would say at least 2gb of *available* memory (please see http://www.linuxatemyram.com, you're reading `free` wrong) is required to compile most crystal programs. Maybe close a few applications of you have 5gb of total memory.

**Comment by kirbyfan64** [comment]
To expand on what @RX14 said, in particular, try closing any Chromium-/Electron-based applications (e.g. Chrome/Chromium, Atom, VS Code, Slack, Spotify, etc.).

**Comment by codenoid** [comment]
ok kirby,

**Comment by codenoid** [comment]
"Is it a question? What do you mean?" i askin that question before start working in desktop :D, if you say yes, then i'll start, and RX14 just say yes :D

**Comment by codenoid** [comment]
after closing atom, my free memori is 400MB > ( < 500MB ), and its work to run crystal compiler, thanks kirby

**Comment by kirbyfan64** [comment]
FWIW if you like Atom, you might like VS Code, which is similar but IIRC  a bit more lightweight.

Also *cough* *shameless plug* http://howl.io *cough*

**Comment by codenoid** [comment]
i just change to sublime text

**Comment by rdp** [comment]
if you build without "--release" then it doesn't take as much RAM to compile, FWIW.

**Comment by asterite** [comment]
Closing, seems the issue was solved
