### ISSUE TITLE
Playground dislikes implicit-object syntax in case expressions

### ISSUE THREAD

**Issue by jbomanson** [crystal-lang/crystal#4289]
In crystal play, the code
````crystal
case 0
when .even?
  :e
else
  :o
end
````
raises the error `Error in line 2: undefined method 'even?' for Nil`.

My crystal --version is `Crystal 0.21.1 [3c6c75e] (2017-03-06) LLVM 3.5.0`.

**Comment by RX14** [comment]
Just to clarify, does this code work outside of the playground?

**Comment by jbomanson** [comment]
Yes it works outside the playground.
