### ISSUE TITLE
Module, is_a?, yield, as, and a BUG: trying to assign Nil

### ISSUE THREAD

**Issue by jbomanson** [crystal-lang/crystal#4290]
The code
````crystal
module MM
  def if_BB
    if is_a? BB
      yield self
    end
  end
end

class AA
  include MM
end

class BB
  include MM
end

m = AA.new.as(MM)
m.if_BB { |x| :y }
````
leads to the following compiler error when running crystal build:
````
BUG: trying to assign Nil <- BB
0x556b5e: ??? at ??
0x1482cf8: ??? at ??
0x149e6da: ??? at ??
0x14988f7: ??? at ??
0x14cfa8f: ??? at ??
0x14cd3a3: ??? at ??
0x1497fb0: ??? at ??
0x1498358: ??? at ??
0x143d83d: ??? at ??
0x1cc6fa5: ??? at ??
0x5b26c9: ??? at ??
0x57e19d: main at ??
0x7fd996666830: __libc_start_main at ??
0x556281: ??? at ??
````
My crystal --version is `Crystal 0.21.1 [3c6c75e] (2017-03-06) LLVM 3.5.0` and OS is ubuntu 16.04 LTS.

The error also comes up in crystal play, play.crystal-lang.org, and carc.in.
In play.crystal-lang.org I tried the crystal versions 0.21.1, 0.21.0, 0.20.5, 0.20.0, 0.19.0, 0.18.0 with the same result.

**Comment by straight-shoota** [comment]
This is still failing with `0.23.1`.
It compiles when `self` is explicitly casted as `BB`: `yield self.as(BB)`

**Comment by vlazar** [comment]
Seems to be fixed. Verified in Crystal 0.31.1 on MacOS. Also in https://carc.in/#/r/7snv
