### ISSUE TITLE
cast Void* to IO

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#4294]
this is needed to pass io to c function, is it even possible?

```crystal
io = IO::Memory.new
x = io.as(Void*)

x.as(IO) << "bla"

io.rewind
p io.gets_to_end
```

**Comment by jhass** [comment]
What kind of C function, what does it try to do with the passed pointer?

**Comment by kostya** [comment]
c function with callback, it return to crystal void* pointer of io, and i want to write to it.

**Comment by kostya** [comment]
i realize this is not possible, crystal should know type
this is works: `x.as(IO::Memory) << "bla"`

**Comment by kostya** [comment]
i solve this by boxing callback with method, quite hacky but works:
```crystal
io = IO::Memory.new
cbk = ->(s : String) do
  io << s
end

x = Box.box(cbk)

Box(String->).unbox(x).call("bla")

io.rewind
p io.gets_to_end
```
