### ISSUE TITLE
What does === mean?

### ISSUE THREAD

**Issue by davidgiven** [crystal-lang/crystal#4295]
The docs describe the `==` and `===` operators as 'equality' and 'case equality'. Unfortunately, the last time isn't defined anywhere --- does it mean it's case *sensitive* or case *insensitive*?

This came up after seeing that `case` uses `===` for testing its values. It doesn't really make a lot of sense for `case` to use case insensitive comparisons, which makes me wonder whether `==` is actually case sensitive --- but that's kinda weird as well, because `==` is used to compare non-string values.

Could we have this explicitly called out and clarified in the (otherwise pretty good) docs, please?

**Comment by jhass** [comment]
"case-equality" is hinting at that the primary usecase of this operator is "to be used by the case statement". It means "equality as defined by the case statement", it does not refer to case sensitivity.

**Comment by kirbyfan64** [comment]
Also, this is mentioned in the [docs for the case statement](https://crystal-lang.org/docs/syntax_and_semantics/case.html). (I have to admit I chuckled a bit at the whole "case insensitive thing...)

**Comment by davidgiven** [comment]
Ah, you mean `Note that === is used for comparing an expression against a case's value.`? That doesn't say what `===` _does_, it only says it's used by `case`; it could do anything...

Okay, this bit of the docs totally needs work --- sorry. I'd probably lose the 'case-equality' term completely. As you might gather, I think it's confusing. I'd suggest renaming it to the identity operator, which matches other languages, and its relationship with `case` could do with expansion.

**Comment by jhass** [comment]
It's not identity however, it's actually looser than `==`. For example `Class#===` is true for instances of the class: https://carc.in/#/r/1v5l

**Comment by asterite** [comment]
It's documented [here](https://crystal-lang.org/api/0.22.0/Object.html#%3D%3D%3D%28other%29-instance-method)

**Comment by straight-shoota** [comment]
The documentation for [Object#===](https://crystal-lang.org/api/Object.html#%3D%3D%3D%28other%29-instance-method) states nearly the same as [`case`](https://crystal-lang.org/docs/syntax_and_semantics/case.html) in the book. It does not actually explain the concept of *case equality*, which is unknown to most programmers without a Ruby background. Hence one should not laugh about @davidgiven's assumption about case insensitivity. What else would you make of the sparse explanation in the docs if you have never heard about this?

**Comment by asterite** [comment]
But `===` is defined by every type with a custom meaning. In the case of a type, case equality means an object is an instance of that type. In the case of a Regex, it means a string matches it,iIn the case of a Range, that a number is included in that range, and so on. So there's no single definition of case equality...

**Comment by davidgiven** [comment]
It certainly needs to be more clearly documented --- asterite's link is only clear if you know what case equality actually is. If you don't know it's a thing in Crystal, then it's completely not obvious what this is for, particular as case has a quite different meaning in other languages. The explanation above is good; can we have that added to the docs for `===`?

(Also needs adding to the docs for the `case` statement.)

**Comment by straight-shoota** [comment]
I'm already working on it right now ;)

**Comment by davidgiven** [comment]
Awesome, thanks!
