### ISSUE TITLE
No way to use alias of NamedTuple in macros

### ISSUE THREAD

**Issue by relonger** [crystal-lang/crystal#4301]
crystal -v
Crystal 0.21.1 (2017-03-14) LLVM 4.0.0

```crystal
alias TT = {a: Int32, b: String}

{% for k in TT.keys %}
  puts "{{k.name}}"
{% end %}
```

Generate errors: 
```
undefined method 'keys' for TypeNode of type TT (must be a named tuple type)

{% for k in TT.keys %}
               ^~~~
```

But TT is *exactly* the NamedTuple (the alias of it). Tried a lot of combinations but nothing works - I can't access info about NamedTuple type after its declaration.

**Comment by asterite** [comment]
`TT` is an alias type, not a NamedTuple type.

The question is whether we want to remove the alias automatically here, or with an explicit operation.

**Comment by bew** [comment]
```cr
alias TT = {a: Int32, b: Char}
{% puts TT.class_name %}
```
Says it's a `TypeNode`, maybe we could add a macro method to `TypeNode` like `TypeNode#alias?` that would return the alias'd `TypeNode` if it's an alias type, and nil otherwise, so we could do something like:
```cr
alias TT = {a: Int32, b: Char}
{% puts TT.alias?.keys %} # => a, b
```

**Comment by relonger** [comment]
> The question is whether we want to remove the alias automatically here, or with an explicit operation.

Either methods are suitable, but neither work now. There is now Alias type in Macro module.

**Comment by bew** [comment]
> The question is whether we want to remove the alias automatically here, or with an explicit operation.

I'd say remove the alias automatically so `TypeNode` manipulations is transparent, but allow to check if it's an alias with `.alias?`:
```cr
alias TT = {a: Int32, b: Char}

# type manipulation
{% puts TT.class_name %} # => NamedTuple
{% puts TT.keys %} # => [a, b]

# alias?
{% puts TT.alias? %} # => AliasType (or something similar)
{% puts TT.alias?.name %} # => TT
```

**Comment by veelenga** [comment]
Another case is union types:

```crystal
alias TT = Int32 | String

{% puts TT.union? %} #=> false
{% puts TT.union_types %}  #=> undefined method 'union_types' for TypeNode of type TT (must be a union type)
```

**Comment by ozra** [comment]
I'm in favour of explicit operation; `TT` _is_ an `Alias`-node. It shouldn't disappear in thin air!? Just a method to get the "target-node"/"aliased node" from the alias-node and then get down to business.
