### ISSUE TITLE
Uncaught exceptions in a spec don't cause the test to fail

### ISSUE THREAD

**Issue by davidgiven** [crystal-lang/crystal#4302]
If a test in a spec throws an exception, then the test just crashes rather than being treated as a failure. The run still exits with an error code, so it's not a false positive, but the failed test doesn't get counted and we don't get a description of which test failed (other than the stack trace).

Example:

    require "spec"
    describe "test" do
    	raise "this is an exception"
    end

...produces the following output; note that zero failures are reported (and in green, too).

    $ crystal spec spec/test_spec.cr 
    Finished in 65 microseconds
    0 examples, 0 failures, 0 errors, 0 pending
    this is an exception (Exception)
    0x563fc5f0ffb0: ~procProc(Nil) at /opt/crystal/src/spec/methods.cr 2:0
    0x563fc5f50617: *Spec::RootContext::describe<String, String, Int32, &Proc(Nil)>:Spec::Context+ at /opt/crystal/src/spec/context.cr 152:30
    0x563fc5f0ffb6: *describe<String, String, Int32, &Proc(Nil)>:Spec::Context+ at /opt/crystal/src/spec/methods.cr 4:5
    0x563fc5efdbe6: ??? at /.pool/@big/nonshared/gmh/spec/test_spec.cr 3:1
    0x563fc5f0dc59: main at /opt/crystal/src/main.cr 12:15
    0x7fbf4c65c2b1: __libc_start_main at ??
    0x563fc5efcb7a: _start at ??
    0x0: ??? at ??

**Comment by bew** [comment]
you need to put it in a `it` block:
```cr
require "spec"

describe "test" do
  it "doesn't crash" do
    raise "this is an exception"
    # fail
  end
end
```

**Comment by asterite** [comment]
Right, `describe` just groups tests, `it` is for proper tests.

**Comment by davidgiven** [comment]
Ah --- that's not obvious. Is there documentation for this? All the methods in the spec module are undocumented:

https://crystal-lang.org/api/0.21.1/Spec/Methods.html

**Comment by asterite** [comment]
The doc comments are there, but after some refactors from some merged PRs they seem to got unattached from the Spec module :-(
