### ISSUE TITLE
XML#parse(io)

### ISSUE THREAD

**Issue by need47** [crystal-lang/crystal#4307]
Maybe I used XML#parse(io) in the wrong way:
[https://play.crystal-lang.org/#/r/1vov](https://play.crystal-lang.org/#/r/1vov)

```crystal
require "xml"

io = IO::Memory.new
io << "<person>"
io << "<firstname>Jane</firstname>"
io << "<lastname>Doe</lastname>"
io << "</person>"

xml = XML.parse(io) # Document is empty (XML::Error)
#xml = XML.parse(io.to_s) # this is OK

puts xml.to_xml
```

**Comment by asterite** [comment]
You need to invoke `io.rewind`. As you write to `IO::Memory` the "pointer" inside it moves along.

**Comment by need47** [comment]
@asterite Thanks a lot.
