### ISSUE TITLE
More liberal default arguments

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#431]
Ruby allows default arguments anywhere in the method definition, as long as they're consecutive. So the following examples are valid in Ruby:

```ruby
def foo b=nil, c
end

def foo a, b=nil, c
end

def foo a, b, c=nil, d
end

def foo a, b=nil, c, d
end

def foo a, b=nil, c=nil, d
end

def a=nil, b=nil, c
end
```

Reference: http://ruby-doc.org/core-2.2.0/doc/syntax/methods_rdoc.html#label-Default+Values

I think that's a nice feature, especially when to comes to writing wrappers for C functions that allow to pass NULL for a middle argument, like the ones in https://developer.gnome.org/gi/stable/GIRepository.html

**Comment by asterite** [comment]
After #2590 we are pretty much done with how arguments are used in a method, so I'm closing this.
