### ISSUE TITLE
Request: Option to add a main application file when initiating a crystal app project

### ISSUE THREAD

**Issue by exts** [crystal-lang/crystal#4310]
So I was wondering what exactly was the difference between `crystal init lib Name` and `crystal init app Name` and at least with the version I currently have installed they don't share any differences. Same project structure and files.

So i was wondering maybe the application version could create an `app.cr` file automatically in the root folder which adds some comments from the compiler (generated by crystal) and require's the applications base project file?

`filename: app.cr`
```Crystal
# Generated By Crystal v.0.21.1
require "./ProjectName.cr"


```

**Comment by kirbyfan64** [comment]
The contents of `shards.yml` should be different.

**Comment by asterite** [comment]
Two things differ:

1. The `shards.yml` file contains a `target` section for an `app` (and not for a `lib`). You can try it, run `shards build` and it will build that file.
2. The `.gitignore` adds `shards.lock` for a `lib`

@exts Do you think something else is missing?

**Comment by exts** [comment]
@asterite I never knew the shards command existed. Thanks. Yeah I guess I can close this as I didn't notice the target before or the `shards` command. I somehow overlooked that.
