### ISSUE TITLE
Allow access and reseed of `Random::DEFAULT` from macros

### ISSUE THREAD

**Issue by splattael** [crystal-lang/crystal#4312]
Hi,

in order to [set a random seed in minitest.cr](https://github.com/ysbaddaden/minitest.cr/issues/14) we need support from the compile to access and reseed `Random::DEFAULT` from macros.

@ysbaddaden [kindly asked](https://github.com/ysbaddaden/minitest.cr/issues/14#issuecomment-295239328) me to create an issue so we can discuss :smile: 

So, here we are.

WDYT?

Kind regards,
  Peter

**Comment by asterite** [comment]
Can't tests be shuffled at runtime?

**Comment by splattael** [comment]
The "runnables" can and [are shuffled](https://github.com/ysbaddaden/minitest.cr/blob/f0989f73b7725268e98b62360ee215f87d6f708c/src/minitest.cr#L72) at runtime.
Test methods [are shuffled](https://github.com/ysbaddaden/minitest.cr/blob/f0989f73b7725268e98b62360ee215f87d6f708c/src/test.cr#L32,L35) at compile time and probably have to.

**Comment by asterite** [comment]
I don't think these macros issues will be solved by adding more and more macro methods. Probably the whole language should be executable in macros, or at least a big subset, like how D, Nim and Elixir work, but that's of course a huge task and we still don't know yet how to tackle it.

You could build a list of procs with the method calls, shuffle that and then execute them.

**Comment by ysbaddaden** [comment]
I'll try that. Thanks!
