### ISSUE TITLE
Request: Add Testing/Spec info to the docs?

### ISSUE THREAD

**Issue by exts** [crystal-lang/crystal#4313]
Right now, the only way I've learned about spec is by this article I read [here](http://ruby-journal.com/crystal/testing-whirlwind-tour-in-crystal-lang/) and it's a very good article on the subject, but I think we should have a quick reference to this information on the doc's directly.

Just something I felt was missing from the docs personally.

**Comment by asterite** [comment]
It's fixed in master. The last release moved some code around and the docs were left unattached to the `Spec` module.
