### ISSUE TITLE
Breaking change of crystal 0.22.0 from 0.21.1: '\"'

### ISSUE THREAD

**Issue by lbguilherme** [crystal-lang/crystal#4321]
This is a small breaking change I hit when upgrading to Crystal 0.22.0 from 0.21.1:

```
p '\"'   # Syntax error in /tmp/foo.cr:1: invalid char escape sequence
```

This is correct and work in both versions:

```
p '"'  # There is no reason to escape
```

I'm opening this just to get it listed as a breaking change on the release notes.

**Comment by lbguilherme** [comment]
#4309

**Comment by asterite** [comment]
I'll add it, though I consider it a bugfix :-)

**Comment by asterite** [comment]
Done! Thank you :-)

**Comment by franklinyu** [comment]
Why should this be an error? In Ruby `'\"'` is interpreted as a string of two characters, which looks good to me.

**Comment by RX14** [comment]
@franklinyu Strings always use `"` and chars use `'` in crystal. See [char](https://crystal-lang.org/docs/syntax_and_semantics/literals/char.html) and [string](https://crystal-lang.org/docs/syntax_and_semantics/literals/string.html) in the language reference.
