### ISSUE TITLE
No way to set an attribute from a block called via `with self yield`

### ISSUE THREAD

**Issue by bew** [crystal-lang/crystal#4323]
```cr
class A
  property attr = 0
  
  def config
    with self yield
    self
  end
  
  # other methods
end

a = A.new.config do
  
  # How do I set A#attr from here ?
  #----------------------------------
  # attr = 42           will create a local variable
  # self.attr = 42      errors with: there's no self in this scope
  
end

puts a.attr # I want 42!
```
https://carc.in/#/r/1wta

**Comment by MakeNowJust** [comment]
No *no way*. You can use `itself` instead of `self`.

```crystal
class A
  property attr = 0
  
  def config
    with self yield
    self
  end
  
  # other methods
end

a = A.new.config do
  itself.attr = 42
end

puts a.attr # I want 42!
```

(`itself` is `Object` method to return `self`. doc is [here](https://crystal-lang.org/api/0.22.0/Object.html#itself-instance-method).)

https://carc.in/#/r/1wun

**Comment by konovod** [comment]
If you use `@attr = 42` there, compiler will eat infinite memory, looks like a bug.

**Comment by bararchy** [comment]
Well , 42 is the ultimate question to life , the universe and everything else , so it might take a lot of ram to calculate ;)

**Comment by MakeNowJust** [comment]
@bararchy Wow! 

I think this problem is not related in this issue because it can be simplified to:

```crystal
def foo
  yield
end

foo do
  @foo = 1
end
```

It is quite a bug.

**Comment by bew** [comment]
@MakeNowJust didn't know the `itself` trick, thanks! And nice bugfix 😄
