### ISSUE TITLE
Compiler crash while parsing of generic in method (forall)

### ISSUE THREAD

**Issue by anykeyh** [crystal-lang/crystal#4326]
```crystal
class SmartWhere
  abstract class Expr
    class Elm < Expr
      def initialize(@name : String)
      end

      def >(any)
        Expr::GreaterThan.new(self, any)
      end

      def resolve
        @name
      end
    end

    class Literal(T) < Expr
      def initialize(@lit : T)
      end

      def resolve
        "#{@lit}"
      end
    end

    class GreaterThan < Expr
      def initialize(@a : Expr, @b : Expr); end

      def initialize(@a : Expr, literal : T) forall T
        @b = Literal(T).new(literal)
      end

      def resolve
        "(#{@a.resolve} > #{@b.resolve})"
      end
    end

    class And < Expr
      def initialize(@a : Expr, @b : Expr)
      end

      def resolve
        "(#{@a.resolve} AND #{@b.resolve})"
      end
    end

    def &(other_expr : Expr)
      And.new(self, other)
    end

    abstract def resolve
  end

  def self.yield_into(&block)
    puts(with SmartWhere.new yield)
  end

  macro method_missing(call)
    return Expr::Elm.new({{call.name.id.stringify}})
  end
end

SmartWhere.yield_into { a > 5 & b > 5 }
```

This code throw the compiler away. I'm pretty sure it's my fault (meaning the code is incorrectly written somewhere), but can't find out. 

This simpler version doesn't throw me away tho...

```crystal
abstract class Expr
  abstract def resolve : String
end

class Literal(T) < Expr
  def initialize(@lit : T)
  end

  def resolve
    "#{@lit.to_s}"
  end
end

class Test
  @literal : Expr

  def initialize(literal : T) forall T
    @literal = Literal(T).new(literal)
  end

  def resolve
    @literal.resolve
  end
end

x = Test.new(1)
pp x.resolve
```

Version : `Crystal 0.22.0 (2017-04-20) LLVM 4.0.0`

**Comment by anykeyh** [comment]
Okay, after looking forward, I noticed there's *nothing related* to the generic method, but it's related to this code:

 ` a > 5 & b > 5 `

Obviously the simple `&` is prioritary on the operator `greater than`. and the compiler is try to do:

`a > ( 5 & b ) > 5`

Plus my code was buggy beside of that, but still the compiler crashed
The good output should have been no 'overloading method & for Int32 / SmartWhere::Elm'

**Comment by kirbyfan64** [comment]
Reduced test case:

```crystal
class Cls
  macro method_missing(call)
    # you can put whatever here, e.g. `return 1` or something
  end
end

def f(&block)
  with Cls.new yield
end

f { a + b }
```

https://carc.in/#/r/1ww9

**Comment by bew** [comment]
@anykeyh you should close this issue, and open a new one with the information from your comment: https://github.com/crystal-lang/crystal/issues/4326#issuecomment-296384892 , so people reading issues are not confused with the title and the (big) original post.

**Comment by bew** [comment]
@anykeyh I thought your issue was on `a > ( 5 & b ) > 5` and operator precedances, but you copy/pasted the comment of @kirbyfan64 which does not seams to cover this operator issue...

**Comment by anykeyh** [comment]
@bew 

Well, for some reason in my code above once I've setup the correct operator precedances and the compiler can "catch" the method overriding ( the "+" ), and once I've fixed others things, the code was running well... 

But the version of @kirbyfan64 is legit and throw exactly the same error code  ( BUG: trying to downcast Cls <- Nil ). 
Actually it would change from Cls to anything else, but always "cast from Nil" related.
