### ISSUE TITLE
Invalid memory access (signal 11) at address 0x20 crystal mongodb

### ISSUE THREAD

**Issue by codenoid** [crystal-lang/crystal#4330]
hi, i have crystal installation and c mongo crystal connection ( https://github.com/datanoise/mongo.cr ),
but when i starting to compile the programe, i gont a error, `Invalid memory access (signal 11) at address 0x20` in the first line.
screenshot > https://s2.postimg.org/cyzcaimq1/mongo2.png 
thanks

**Comment by kirbyfan64** [comment]
Show us your code please!

**Comment by RX14** [comment]
The segfault here looks like it happens inside C code, so maybe it'd be best to report the issue on the `mongo.cr`. As a matter of fact, it looks like this issue: https://github.com/datanoise/mongo.cr/issues/12
