### ISSUE TITLE
fork: Cannot allocate memory

### ISSUE THREAD

**Issue by kazzkiq** [crystal-lang/crystal#4343]
When trying to run the HTTP server example (`crystal server.cr`) from the website, I get the following error:

```bash
fork: Cannot allocate memory
0x55b5be: ??? at ??
0x11184c5: ??? at ??
0x144c154: ??? at ??
0x1cd10b5: ??? at ??
0x1d754a9: ??? at ??
0x5c19bd: ??? at ??
0x5892dd: main at ??
0x7f2199bb1830: __libc_start_main at ??
0x5562e1: ??? at ??

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

This is the code I ran:

<details>

```crystal
require "http/server"

server = HTTP::Server.new(8080) do |context|
  context.response.content_type = "text/plain"
  context.response.print "Hello world, got #{context.request.path}!"
end

puts "Listening on http://127.0.0.1:8080"
server.listen
```
</details>

<br>

The code is theoretically super small and a VM with 512 RAM should be able to compile it without further problems, right? Is this a bug or I really do need more memory for compiling in Crystal?

----

Crystal version:
**Crystal 0.22.0 [3c71228] (2017-04-20) LLVM 3.5.0**

OS version:
**Ubuntu 16.04.2 LTS x86_64** ($5 Digital Ocean Droplet)
**512MB RAM**

**Comment by mverzilli** [comment]
It is a bit difficult to forecast how much memory it'll need, but yes, 512mb could be too little. If you want to use that machine as your "live" server, the best thing to do is compile on a machine with more memory and then just drop the executable to the 512mb RAM server.

**Comment by kazzkiq** [comment]
I resized my droplet to a 2GB RAM and managed to compile it properly. Again, thanks.
