### ISSUE TITLE
Process communication and parallelism

### ISSUE THREAD

**Issue by oltmannsdaniel** [crystal-lang/crystal#4350]
Currently I try to figure out, how I can run my script on multiple processes. Sure, there is the `Process` Class (https://crystal-lang.org/api/0.22.0/Process.html), but the communication between processes is missing. My question is now:

**How can I send a String from one child process, to the master/main one?**

What I already tried:

- _Get the process output_ = Not working that good, and where can I actually hide the output from the user??
- _Save result to a file_ = Complicated to convert that to an variable in my master process.

## My idea:
A cluster libary with the ability to send messages from the child process to the master one and the other way around. Inspiration [here](https://nodejs.org/api/process.html#process_event_message).

**Comment by ysbaddaden** [comment]
Use an UNIXSocket? Or use `IO.pipe` to read/write through stdin/stdout of the child process?

Or just don't and wait for parallelism in crystal to be a reality :-)

**Comment by oltmannsdaniel** [comment]
@ysbaddaden Ok then I will wait for some awesome improvements that will make this awesome Language even more fantastic.

**Comment by oltmannsdaniel** [comment]
@ysbaddaden Any idea how to send data from a `Process.fork` to a Channel or IO.pipe ?

**Comment by ysbaddaden** [comment]
You can't use a Channel across processes, but a pipe is fine:

```crystal
read, write = IO.pipe

fork do
  read.close
  write.puts "message"
end

write.close
read.gets # => "message\n"
```

**Comment by asterite** [comment]
The above reply probably closed the issue again.
