### ISSUE TITLE
Suggestion: Improvements to initialize (rename to `init` and/or allow one line def)

### ISSUE THREAD

**Issue by paulcsmith** [crystal-lang/crystal#4372]
Initialize is fairly easy to misspell and it's a pain to type, I wonder if before 1.0 this could be changed/aliased to just `init`?

The second suggestion is to make it possible to have one line initialize methods. I realize it is a special case, but then again initialize is already a special case because it allows setting instance variables from the method signature (which I LOVE by the way!). This also works similarly to how abstract method def are just one line

```crystal
def init(@name : String)

# Rather than, which looks a little strange to me with an empty body
def initialize(@name : String)
end
```

**Comment by jhass** [comment]
Yes, initialize has many special cases, but instance var from parameter assignment is none of them: https://carc.in/#/r/1yxq

**Comment by RX14** [comment]
The compiler does already give you a hint that you may have spelled initialize wrong if you hit an error relating to it.

**Comment by paulcsmith** [comment]
@jhass Cool. I didn't realize that could be done! @RX14 yeah the compiler makes it pretty easy to tell what's up, but it is a small, but daily annoyance. Maybe just me though

Thoughts on making it possible to do it as one-line?

**Comment by RX14** [comment]
@paulcsmith If it's a daily annoyance you should train your hands better :)

**Comment by bew** [comment]
@paulcsmith you can mae it oneline with:
```cr
class A
  def hello(@who); end
end
```

**Comment by paulcsmith** [comment]
@bew that is better, but I like the aesthetics of `def initialize` a bit more. I realize it's a small thing, but I think it looks nice and it's easy to add a body with an end later if needed

**Comment by paulcsmith** [comment]
@RX14 that is definitely one way, or it could be `init` which everyone agrees takes less typing, reading and is harder to mess up.

**Comment by bew** [comment]
I think `init` is too short for a method that you never call directly (it's called by the generated associated `new`)

**Comment by RX14** [comment]
Crystal in general doesn't use abbreviation, most `String` methods and `elsif` being obvious exceptions. But I'd dislike to add more.

**Comment by kirbyfan64** [comment]
FWIW:

- Changing `initialize` to `init` would literally break pretty much every Crystal program every written that's more than 5 lines long, yet it wouldn't really give that much gain.
- IMO omitting the `end` makes it look downright weird...

**Comment by ozra** [comment]
I'm biased towards `init`, that's what it's called in my pet-peeve (along with `deinit`).

It would be a one-time search n replace job ;-) (and some minor fiddling afterwards if initialize was used as identifier for anything else (less likely).

**Comment by bew** [comment]
> Changing initialize to init would literally break pretty much every Crystal program every written that's more than 5 lines long

Note: This is not an argument, people writing libs/apps are aware that the language/the syntax/the stdlib is not stable and may change...

**Comment by mverzilli** [comment]
Thank you for the suggestion @paulcsmith :). I'm afraid we have to close this: it's one of those discussions that won't ever end (like the famous "do-end" vs "indentation based" blocks). There are "arguments" for both sides and none of them are decisive. 

Probably the most relevant argument is what @RX14 mentioned: Crystal tries not to (ab)use abbreviations.

But at the end of the day it's a matter of taste, and in those cases we believe the best way to go is to keep things as they are. Let's put energy on other more significative aspects of the design of the language :).

As regards one line defs, maybe that's a more interesting discussion. Feel free to open an issue exclusively for that (it wouldn't be an enhancement for `initialize`, but a general feature for every method of the language).

**Comment by paulcsmith** [comment]
@mverzilli That is totally fair and I respect your points. I'll open an issue for the one-lim defs as a separate topic! Thank you for addressing the issue in such a kind way, and I you are right that there are better ways to spend time than debating this. Thanks!
