### ISSUE TITLE
tcp_server and tcp_client sample code not working properly

### ISSUE THREAD

**Issue by wjmacfarland** [crystal-lang/crystal#4378]
When I run the sample programs "crystal tcp_server.cr" and then "crystal tcp_client.cr" The server receives the first message from the client, but the client hangs when attempting to read the response from the server. I've modified the tcp_server.cr so that the programs operate as what I believe should be expected, however there probably is a better way to do it than I have as I've just begun learning Crystal and have only limited Ruby experience. [Here](https://gist.github.com/wjmacfarland/3a9c93989ec203a970bd96aadfd08f9a) is the modified file. I am using Crystal 0.22 with Ubuntu 16.04.2 LTS.

**Comment by bcardiff** [comment]
@wjmacfarland thanks for reporting, I fixed by using `IO#puts` so the newline character is added and the tcp_client will read until it when doing the `IO#gets`.

**Comment by straight-shoota** [comment]
Shouldn't `IO#read_line` (i.e. `IO#gets`) return the message with the terminating newline character included?

**Comment by Sija** [comment]
@straight-shoota Nope, it was changed in `0.20.3`, see #3704.

**Comment by straight-shoota** [comment]
Oh, thanks! Seems like I missed that change...
