### ISSUE TITLE
Nested macros, comments, and macro variable lookup

### ISSUE THREAD

**Issue by bew** [crystal-lang/crystal#4380]
https://carc.in/#/r/1zai
```cr
{% for verb in {:get, :post, :put} %}
  macro {{verb.id}}(arg)
    puts "not commented" \{{arg}}
    # puts "commented" \{{arg}}          # => undefined macro variable 'arg'
  end
{% end %}
```
The escaped macro variable lookup isn't respected when the line is commented.

**Comment by bew** [comment]
Now that I re-think about it, whether the line is commented or not doesn't make sense for macro code, but all I wanted was to comment a line in the macro, just to check something.

I think there is currently no way to comment stuff in a macro without breaking like in OP.

As we already have `{% %}` for macro statement, `{{ }}` for printed macro statement, we could have `{# #}` for commenting stuff in macros?

Maybe it's not a good idea to allow multiline commenting, as this could be abused to comment multiple lines in normal code, we could have `{#}` to comment to the end of the line?

**Comment by bew** [comment]
I just realized I can comment macro stuff with:
```cr
{% # this is a comment
 %}

# or (cleaner?)

{%
 # this is a comment
 %}
```
I would still prefer a dedicated syntax like `{#}` as it would be easier to use, but it's good enough for now

**Comment by jwoertink** [comment]
I just ran in to this using 1.4.1

```crystal
class Base
  macro inherited
    macro foo(name)
      # some comments \{{ name.id }}
      def foo
        puts "\{{ name.id }}"
      end
    end
  end
end
 
class Foo < Base
  foo bar
end

Foo.new.foo
```

```
Showing last frame. Use --error-trace for full trace.

error in line 4
Error: undefined macro variable 'name'
```

To get around this, it looks like you can use `verbatim`

```crystal
class Base
  macro inherited
    {% verbatim do %}
      macro foo(name)
        # some comments {{name}}
        def foo
          puts "{{name.id}}"
        end
      end
    {% end %}
  end
end
 
class Foo < Base
  foo bar
end
 
Foo.new.foo
```
