### ISSUE TITLE
YAML serializes numeric strings incorrectly

### ISSUE THREAD

**Issue by rf-** [crystal-lang/crystal#4384]
In YAML, a string containing only a number has to be represented with quotes to avoid being interpreted as a numeric value. The Crystal YAML library currently doesn't do this.

Example code:

```
require "yaml"

puts({ "n" => "2" }.to_yaml)
```

This yields `n: 2`, which would correctly be deserialized (e.g., by Ruby) as `2` instead of `"2"`.

This issue is related to #4175, #3101, etc., but it seems a little bit narrower in scope since it's not about supporting a larger subset of YAML than Crystal currently does, just about supporting the current subset in a more correct way.

**Comment by z64** [comment]
I think Asterite more or less directly addressed this in [his comment on that issue:](https://github.com/crystal-lang/crystal/issues/3101#issuecomment-238031480)

> It's just that the fail-safe schema was easier to implement at first, because everything is a string, and then you can parse the string in the way that you need it.

If you like, I wrote a macro lib that generates a bunch of converters for numeric types for ease of use in JSON and YAML mappings. It's very much tailored to my own needs at the moment and I would like to improve it, but maybe they would be of use to you: [z64/string_converter](https://github.com/z64/string_converter)

**Comment by rf-** [comment]
Sorry, I might not have been clear in my description of the problem. The issue I'm having only involves string data, not numeric data—specifically, string data that consists of numeric characters. The way Crystal currently serializes a string like `"2"` (without quotes) round-trips correctly in Crystal, but other languages parse it incorrectly.

I'm not familiar enough with the YAML spec to know if it's a _requirement_ for an implementation of the fail-safe schema to quote these strings, but it seems like a good idea for Crystal to implement the subset of YAML that it supports in a way that interops with other parsers.

BTW, this monkey patch fixes my immediate problem, although I'm guessing there's a better way to get LibYAML to do the right thing:

```
class YAML::Builder
  def scalar(value)
    if value.is_a?(String)
      string = value
      style = value =~ /^\d+$/ ? LibYAML::ScalarStyle::DOUBLE_QUOTED : LibYAML::ScalarStyle::ANY
    else
      string = value.to_s
      style = LibYAML::ScalarStyle::ANY
    end

    emit scalar, nil, nil, string, string.bytesize, 1, 1, style
  end
end
```

**Comment by straight-shoota** [comment]
[#codetrieage](https://www.codetriage.com/crystal-lang/crystal): 
YAML supports a [plain style](http://yaml.org/spec/1.2/spec.html#id2788859) to write values without delimiters, which is good readable but has its limitations.
One such limitation is that a plain style value wich matches a number format can be interpreted as a number. Therefore, emitting a string which would produce such a value needs to wrap it in delimiters to avoid misinterpretation as wrong datataype. This is relevant for all formats described for [Integer](http://yaml.org/spec/1.2/spec.html#id2803828) and [Floating Point](http://yaml.org/spec/1.2/spec.html#id2804092) but also [Boolean](http://yaml.org/spec/1.2/spec.html#id2803629) and [`null`](http://yaml.org/spec/1.2/spec.html#id2803362).

The core problem is, that Crystals YAML API currently only supports [Failsafe Schema](http://yaml.org/spec/1.2/spec.html#id2802346) which has the datatypes mapping, sequence and string. It should be enhanced to support the [Core Schema](http://yaml.org/spec/1.2/spec.html#id2804923). So this is not actually a bug, when you're parsing the output with Ruby for example, you're just using the wrong JSON schema... but of course Crystal should be compatible to the full spec for parsing and formatting. I have created #4771 as a meta-issue.

All these string values should be wrapped in delimiters ([carc.in](https://carc.in/#/r/2giw)):
``` crystal
require "yaml"

string = YAML.build do |yaml|
  yaml.sequence do
    yaml.scalar "1"
    yaml.scalar "1.2"
    yaml.scalar "-1.2"
    yaml.scalar "-1"
    yaml.scalar ".inf"
    yaml.scalar "-.inf"
    yaml.scalar ".nan"
    yaml.scalar "null"
    yaml.scalar "true"
    yaml.scalar "false"
  end
end
puts string
```
