### ISSUE TITLE
MetaVar doesn't expose default value, only name & type

### ISSUE THREAD

**Issue by bew** [crystal-lang/crystal#4387]
The macro method `TypeNode#instance_vars` returns an array of `MetaVar`, which holds the var **name** & **type**. I think it should be possible to access the **default value** (like in a `TypeDeclaration` type)
```cr
class Object
  macro def debug_vars
    {% p "Type: #{@type}" %}
    {% p "Instance vars: #{@type.instance_vars}" %}
    {% for var in @type.instance_vars %}
      {% p "   - #{var.name} : #{var.type}" %}    # No way to get the default value if any..
    {% end %}
  end
end

class MyClass
  @explicit_var = true
  property a : Int32 = 0
  property b : Array(String)?

  debug_vars
end
```
https://carc.in/#/r/1zrr

By looking at the code, a [`MetaVar`](https://github.com/crystal-lang/crystal/blob/238e207d58bdd7ad78f2aa042d9bc7ff2732afd4/src/compiler/crystal/semantic/ast.cr#L402) doesn't have access to that default value. (I'm not sure I understand what a metavar is..).

From my perspective, using `TypeNode#instance_vars` should return an array of `Something`, and I should be able to get the **name**, **type** & **default_value** if any for this `Something`.

I think the way to go would be to create a proxy type that has all informations, so we can query them.
What do you think?

**Comment by asterite** [comment]
@bew I thought about this a bit. Why do you need to know the default value? Is it enough for you to know whether it has a default value or not?

The default value could be something simple like an integer literal, or a complex expression. I don't think one would like to paste that expression somewhere else in the program.

However, I think it might be useful to know whether an instance variable has a default value. If so, it doesn't need to be initialized. I'm thinking about JSON/YAML serialization by inspecting a class' instance vars. You'd want to know whether there's a default value so you don't raise an exception "missing property foo" if there's no value in the document.

What's your use case?

**Comment by bew** [comment]
If I remember correctly I was trying to make an experimental automatic JSON mapping macro (pretty much what you're trying now), and I wanted to stress test what informations I could extract from `@type` regarding the instance vars.
Honestly I don't remember what I had in my mind 8 months ago about the design of that macro.. :smile: I believe I wanted to paste the `default_value` myself in the `initialize(pull_parser)` in case the parser couldn't get me a specific field. But as you explained maybe the compiler can figure it out, and we would just need a `has_default_value` instead.
