### ISSUE TITLE
Macro runs do not use link flags

### ISSUE THREAD

**Issue by RX14** [crystal-lang/crystal#4393]
See https://github.com/crystal-lang/crystal/issues/3721#issuecomment-297548078.

`bin/crystal build --link-flags="-m32"  spec/app_spec.cr` will not pass `-m32` to the linker when linking macro runs. I suspect this is as a new compiler instance is created without passing `link_flags` from the parent compiler.

**Comment by bcardiff** [comment]
I don't think the flags (at least the -m32) should be forwarded, because the macro run will execute the compiled program in the original environment so, in this case, the compiler used for macro run should be setup for 64bits.

**Comment by RX14** [comment]
The correct workaround here is just to set `CC="cc -m32"` I think. Should this be closed?
