### ISSUE TITLE
Configuration option to serve static files in a specific path

### ISSUE THREAD

**Issue by joaodiogocosta** [crystal-lang/crystal#4398]
At this time, using [HTTP::StaticFileHandler](https://github.com/crystal-lang/crystal/blob/dd1dca4d17e15a098b917e0bad9299f144b3986b/src/http/server/handlers/static_file_handler.cr) I can configure which directory to serve static files from by passing its path to the constructor:

```crystal
HTTP::StaticFileHandler.new("public/")
```

This will serve files from `public/` in the root path `/` and there is no way to change it. If there's a file with the path `public/about.html`, it will be served as `/about.html`. If this handler is mounted before the main handler, it will always capture the root path `/` and show a list of files under the given directory.

It would be useful to have an option in the constructor to pass the path in which the files will be served to. Something like:

```crystal
HTTP::StaticFileHandler.new("public/", path: "assets/")
```

This might be relevant to people who are building web frameworks, like me.

I would be happy to submit a PR with this change if you find it useful as well.

**Comment by joaodiogocosta** [comment]
There might be another ways around this. One of them might be to add an option to disable directory listing. I wouldn't want users to be able to list all files under my public directory.

Something like the following would do:

```crystal
HTTP::StaticFileHandler.new("public/", directory_listing: false)
```

**Comment by bew** [comment]
I agree, the directory listing should never happen (be false by default at least)

**Comment by bcardiff** [comment]
In the playground there is a PathStaticFileHandler that extends the StaticFileHandler for this scenario: https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/tools/playground/server.cr#L353-L369 .

Maybe this discussion goes beyond the StaticFileHandler. There is no unified way to "mount" an http handler to a path. For example with WebSocketHandler, the same limitation appear. In the playground and in Kemal WebSocketHandler are mounted with a path prefix.

As for the directory_listing, I prefer it on by default. But I agree it would be good to be able to turn it off.

**Comment by joaodiogocosta** [comment]
@bcardiff thanks, that playground reference helps. I've done it differently [here](https://github.com/joaodiogocosta/soil/blob/master/src/soil/http/handlers/static_file_handler.cr) but that one is preferable. I haven't realised that I could've just override `def request_path`.

I agree with keeping handlers away from any kind of routing. It does make sense.

I'll make a PR enabling optional turn off of directory listing anyway so we can discuss further on this.

Thanks

**Comment by joaodiogocosta** [comment]
I'll close this down since there's a workaround and we now have an option to disable directory listing #4403.
