### ISSUE TITLE
`a.field=(expr)...` and `a.field = (expr)...` are parsed differently

### ISSUE THREAD

**Issue by konovod** [crystal-lang/crystal#4399]
`a.field=(expr).to_i` is parsed as a call to `a.field=(expr)` that is converted to int. I'm not sure if this is a bug (as it looks pretty logical, there is a `field=` method after all), but ruby behaves differently and the fact that space added by a formatter can change behaviour of code seems wrong.
Crystal example:
https://carc.in/#/r/20cq
```crystal
class A
  property int = 0.0
end

a = A.new
a.int=(1000.0/3).to_i
p a.int
```
prints 333.33333333333331
Ruby example
https://carc.in/#/r/20cs
```ruby
class A
  attr_accessor :int
end

a = A.new
a.int=(1000.0/3).to_i
p a.int
```
prints 333

**Comment by bcardiff** [comment]
I agree.  `a.m=expr` should lead to the same AST as `a.m= expr` and `a.m = expr`.

Maybe also the formatter is missing a rule to transform all variants to `a.m = expr`

**Comment by ozra** [comment]
Just rewriting might be dangerous! Declaring _space as significant_ in the syntax docs is the only easy way I can see. After all the method call and the operator translating to the method call (which, duh, differ only by whitespace) _do_ have different precedences.

The method-style calling _is_ used on purpose in "auto-paramed" blocks after all?

- for `idfr=`, the `=` should be considered part of the identifier.
- for `idfr =`, `=` is an operator: spacing should be demanded by syntax rules.

Unfortunate out of a crystal syntax perspective, but I don't know: I haven't exhausted the possibilities - so consider this just a rant to consider before nailing any _potentially_ breaking simplification transforms, should unit-tests not cover the cases.

**Comment by bcardiff** [comment]
(I usually prefer space to not be significant)

@ozra the following example works currently, regarding mixin `&.foo` with ` = `. 

```crystal
class Foo
  property foo = 0
end

c = [Foo.new, Foo.new]
c.each &.foo = 1 + 1
pp c # => [#<Foo:0x106df9ff0 @foo=2>, #<Foo:0x106df9fe0 @foo=2>]
```

But maybe I didn't understand your point.

The formatter already add spaces around the `=`. For sure the semantics should not be changed after the formatter is run, that could signal a bug in the formatter. But in this case I think there is parser bug. 

I am open to see examples where those expression should be interpreted different.

**Comment by konovod** [comment]
I hate significant spaces and i think that parsing `a.foo=(2)+2`as `a.foo=(2+2)` is a best solution. 

The only problem i see is that now method with `=` behaves like any other method:
```crystal
pp a.method 2 + 2  # becomes a.method(2 + 2)
pp a.method(2) + 2 # becomes (a.method(2)) + 2
pp a.field= 2 + 2  # becomes a.field=(2 + 2)
pp a.field=(2) + 2 # becomes (a.field=(2)) + 2
```
so if the issue will be fixed, precedence of a method call will depends whether a method name ends with `=` or not. Not a big problem imho, but should be documented somewhere i there will be sort of formal grammar or at least a documentation of operator precedences.

**Comment by ozra** [comment]
@bcardiff @konovod your comments together sums up everything I'd think important to high-light to consider.

**Comment by akzhan** [comment]
This behavior should be documented at least (because it's unexpected from Rubyist side).
