### ISSUE TITLE
Fails building head on ARCH

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#4401]
Machine:
CPU - `Intel Xeon CPU E3-1505M v5 @ 3.7GHz`
RAM - 16GB

Building with: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=crystal-git

Error:
```
Using /usr/bin/llvm-config [version=4.0.0]
g++ -c -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc `/usr/bin/llvm-config --cxxflags`
cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC  -D_FORTIFY_SOURCE=2  -c -o src/ext/sigfault.o src/ext/sigfault.c
ar -rcs src/ext/libcrystal.a src/ext/sigfault.o
./bin/crystal build --release  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
fork: Cannot allocate memory
0x540b4e: ??? at ??
0x10fda55: ??? at ??
0x14fffc7: ??? at ??
0x14fef65: ??? at ??
0x1436cc4: ??? at ??
0x1cb6645: ??? at ??
0x5a23f9: ??? at ??
0x56e86d: main at ??
0x7fa2a89dd511: __libc_start_main at ??
0x53b871: ??? at ??

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
make: *** [Makefile:114: .build/crystal] Error 1

```

**Comment by RX14** [comment]
That PKGBUILD downloads compiler omnibus version 0.22.0, which is still packaged using LLVM 3.5, so this is a known issue. Still not sure it ever got opened as an issue on the issue tracker though. So the solution here is https://github.com/crystal-lang/omnibus-crystal/pull/17. Compiling a non-release build doesn't hang IIRC. You can then use that build to build a release compiler.

**Comment by bararchy** [comment]
@RX14 I managed to build, just closed everything that was running XD 
it took around 8GB RAM

**Comment by RX14** [comment]
Oh, it seems that bug was fixed. For a while, LLVM 3.5 couldn't compile the compiler in release mode at all, it just hung.

**Comment by drhuffman12** [comment]
Just wondering... is there any way to split parts of the compile process into smaller chunks .. and would that help with the memory usage? It seems like I read somewhere that something like that has been discussed. Maybe move some code into their own shards?

**Comment by RX14** [comment]
@drhuffman12 The problem with that currently is that type inference is global, and I don't think there will be a way to make it not-global without sacrificing crystal's expressiveness.

**Comment by dmitryrck** [comment]
I got into this exactly problem while building a docker image.

As soon as I started to use make like this `make threads=1` it fixed.
