### ISSUE TITLE
GPG key missing @ keys.gnupg.net ?

### ISSUE THREAD

**Issue by joaumg** [crystal-lang/crystal#4417]
Hello, just tried to install crystal on Debian, however:

> Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux

λ joaumg [~] → sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 09617FD37CC06B54
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.xq1VKtYL23 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyring /etc/apt/trusted.gpg.d/gnome3-team-gnome3-staging.gpg --keyring /etc/apt/trusted.gpg.d/gnome3-team-gnome3.gpg --keyring /etc/apt/trusted.gpg.d/neovim-ppa-unstable.gpg --keyring /etc/apt/trusted.gpg.d/ravefinity-project-ppa.gpg --keyring /etc/apt/trusted.gpg.d/snwh-pulp.gpg --keyring /etc/apt/trusted.gpg.d/spotify-2015-05-28-D2C19886.gpg --keyring /etc/apt/trusted.gpg.d/ubuntu-lxc-lxd-stable.gpg --keyring /etc/apt/trusted.gpg.d/webupd8team-java.gpg --keyserver keys.gnupg.net --recv-keys 09617FD37CC06B54
gpg: requesting key 7CC06B54 from hkp server keys.gnupg.net
?: keys.gnupg.net: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Success
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0

Also doing a manual search resulted in nothing:

http://keys.gnupg.net/pks/lookup?search=09617FD37CC06B54&op=vindex

> No results found
> No results found: No keys found

Could some maintainer publish the gpg key again ? Or at least some avid contributor export it ?

**Comment by RX14** [comment]
@joaumg The key is published, you need to add `0x` before the hex ID to find the entry: [0x09617fd37cc06b54](http://keys.gnupg.net/pks/lookup?search=0x09617FD37CC06B54&op=vindex).

The error you get on the commandline states `keys.gnupg.net: Host not found`, which suggests a DNS or connection error of some sort. Maybe the site had a breif issue with DNS which is still affecting your server.

**Comment by joaumg** [comment]
@RX14 thanks, I forgot the `0x`...

Weird that I can connect to the site to perform a normal query however gpg doesn't find the host, but that I'll leave to later since it's a env problem.

Thanks (;

**Comment by joaumg** [comment]
@RX14 ok, internal error from them:

> http://keys.gnupg.net/pks/lookup?op=get&search=0x09617FD37CC06B54

> Not Found
> The requested URL /pks/lookup was not found on this server.

Could you export the public key for now while they fix it ? (;

**Comment by joaumg** [comment]
nvm. odd caches I guess.

**Comment by RX14** [comment]
@joaumg No, the error is intermittent. You can get the pubkey here: https://keybase.io/crystal/pgp_keys.asc

**Comment by straight-shoota** [comment]
The documentation references https://keybase.io/crystal/pgp_keys.asc, but the setup script at https://dist.crystal-lang.org/apt/setup.sh still uses keys.gnupg.net

I'm not sure if it's more reliable in the mean time, but I think it would be better to use the same key source for both.

**Comment by straight-shoota** [comment]
#7265 reports an issue with verifying with key verification while using the setup script. Not sure if it's related to key.gnupg.net hosting though.
