### ISSUE TITLE
Cannot use parents version of method using `super`

### ISSUE THREAD

**Issue by bew** [crystal-lang/crystal#4425]
```cr
class VeryBase
  getter msg : String

  def initialize(@msg)
  end
end

class Base < VeryBase
  def initialize
    super "base message"
  end
end

class Derived < Base
  def initialize
    super "derived message"
  end
end

def func(ex : Base)
  puts ex.msg
end

func Base.new # => base message

func Derived.new
```
https://carc.in/#/r/21bi (My use case is with exceptions: https://carc.in/#/r/21bg)

Errors with:
```
Error in line 26: instantiating 'Derived:Class#new()'

in line 16: wrong number of arguments for 'Base#initialize' (given 1, expected 0)
Overloads are:
 - Base#initialize()
```

It seems that from `Derived#initialize`, I can only use `super` to access `Base#initialize` but not `VeryBase#initialize(msg)`

**Comment by drosehn** [comment]
It strikes me that it makes sense for crystal to treat `initialize` methods in this manner.  If `Derived` is a subclass of `Base`, then it's prudent to say that `super` in an `initialize` method will only match an initialize method of `Base`.  For the case of `initialize`, you really don't want a mistake in specifying parameters to cause all the initialization of `VeryBase` to occur without any of the initialization expected for `Base`.

If the writer of `Derived` really needs to call the alternate version of `initialize`, then they could first re-open `Base` to add an `initialize` method to that class which matches the `initialize` they need to reach in the `VeryBase` class.

For instance, before the line `class Derived < Base `, put:
```cr
class Base
  def initialize(msg)
    super msg
  end
end
```

**Comment by drosehn** [comment]
... or at least that's my gut feeling after only a few minutes of thinking about it.  It could also be that the tactic I suggested is a bad idea.

**Comment by konovod** [comment]
In pascal, there is a syntax `VeryBase.initialize("derived message")` for it. Not sure if it worths adding, but it's imho clearer then reopening base class for adding methods.

**Comment by bew** [comment]
> For the case of initialize, you really don't want a mistake in specifying parameters to cause all the initialization of VeryBase to occur without any of the initialization expected for Base.

Yeah I missed that case, and it seems logical, but I think it's redundant to reopen the Base just for this.. (but I can't see any other way though)

**Comment by jwoertink** [comment]
Just my 2¢ but when I use super, I see it as calling the parent of that method, but in this case, you're not calling the parent of `initialize`, you're calling `initialize(msg : String)`. So in this case, I would just use

```ruby
def initialize
  initialize("derived message")
end
```

**Comment by akzhan** [comment]
Looks like you should do

```crystal
class Base < VeryBase
  def initialize(msg = "base message")
    super(msg)
  end
end
```

**Comment by bew** [comment]
Thanks all for your answers, I resolved my issue, I think this can be closed now
