### ISSUE TITLE
Uknown key in access token json: id_token

### ISSUE THREAD

**Issue by msa7** [crystal-lang/crystal#4437]
I try to use OAuth2 with Google 

```
    oauth2_client = OAuth2::Client.new(
      "www.googleapis.com",
      client_id,
      client_secret,
      token_uri: "/oauth2/v4/token",
      redirect_uri: redirect_uri
    )

    oauth2_client.get_access_token_using_authorization_code(authorization_code)
```

Regarding this [page, section Exchange authorization code for refresh and access tokens](https://developers.google.com/identity/protocols/OAuth2WebServer#exchange-authorization-code)

> Note: Your application should ignore any unrecognized fields included in the response.

here

```
Uknown key in access token json: id_token (Exception)
0x69c7a7: new at /opt/crystal/src/oauth2/access_token/access_token.cr 24:9
```

**Comment by msa7** [comment]
I will try to remove raise of exception and send PR if it works with google

**Comment by asterite** [comment]
@msa7 Don't worry, I'll fix it in some minutes

**Comment by msa7** [comment]
ah... I want my first commit to Crystal :-)
Thanks

**Comment by RX14** [comment]
@msa7 There's an [issue label](https://github.com/crystal-lang/crystal/issues?q=is%3Aopen+is%3Aissue+label%3Acommunity%3Anewcomer) for some simple low-hanging issues to get started contributing to crystal.
