### ISSUE TITLE
Add a way to supress the warnings from the GC

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#4441]
Long story short, the code is fine, the GC still complains, is there a way to suppress the warnings from the GC ?

**Comment by akzhan** [comment]
Please show an examples of warnings to be suppressed.

**Comment by bararchy** [comment]
@akzhan  `GC Warning: Repeated allocation of very large block` This error

**Comment by bew** [comment]
I don't think you can disable them, they are written from the GC code, not from crystal code. So unless there is a way to tell the GC crystal to disable warning, there is no way to hide them..

**Comment by ysbaddaden** [comment]
Boehm GC does allow to handle/ignore warnings. See https://github.com/ivmai/bdwgc/blob/master/include/gc.h#L1262-L1277

That being said, if GC complains you will eventually run into memory issues.

**Comment by bararchy** [comment]
That's cool , thanks kostya 

Can those be used too ?
```
unmapping threshold is 1.

 

GC_FIND_LEAK - Turns on GC_find_leak and thus leak detection. Forces a

collection at program termination to detect leaks that would

otherwise occur after the last GC.

 

GC_FINDLEAK_DELAY_FREE - Turns on deferred freeing of objects in the

leak-finding mode (see the corresponding macro

description for more information).

 

GC_ABORT_ON_LEAK - Causes the application to be terminated once leaked or

smashed objects are found.

 


```

It could be useful to try and debug the warnings

**Comment by akzhan** [comment]
Looks like issue should be closed, because functionality already provided by BWGC

**Comment by sdogruyol** [comment]
Can we close this?

**Comment by RX14** [comment]
I think `GC_LARGE_ALLOC_WARN_INTERVAL` is the solution here.
