### ISSUE TITLE
Compile ARM build

### ISSUE THREAD

**Issue by oltmannsdaniel** [crystal-lang/crystal#4443]
Error:
```
ERROR: LLVM was built without ARM target
0x556bde: ??? at ??
0x111731d: ??? at ??
0x119082f: ??? at ??
0x117b782: ??? at ??
0x1cd105e: ??? at ??
0x5bce69: ??? at ??
0x5892dd: main at ??
0x7f424692f830: __libc_start_main at ??
0x5562e1: ??? at ??

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

My question now: **How can I build LLVM with an ARM architecture?**

By the way, when there will be a release for Crystal under the ARM architecture? Crystal on a Raspberry PI would be awesome.

**Comment by RX14** [comment]
There's a raspbian repository here: http://public.portalier.com/raspbian.

There's a guide to compiling llvm here: http://llvm.org/docs/GettingStarted.html

**Comment by oltmannsdaniel** [comment]
Awesome. Thanks for the quick answer.
