### ISSUE TITLE
HTTP::Client connect to Unix Socket

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#4447]
There is a proposal to add support for Unix sockets to `HTTP::Server` (#2735). Similarly, I'd like `HTTP::Client` to connect to Unix sockets as well.
This would be useful for using HTTP APIs for example in a microservice architecture, building proxy applications (maybe mount an external HTTP server into Kemal via Unix socket...?) or testing HTTP applications without exposing a port.

**Comment by straight-shoota** [comment]
In contrast to `HTTP::Server` the client already supports `URI` as an argument for `.new`, so there is no API change required to support Unix sockets. It would probably be nice to have a way to directly provide a path  to a Unix socket as string `new(*, path : String)`.

**Comment by asterite** [comment]
Closed in favor of #2735 (tracks both)
