### ISSUE TITLE
Compiler failures don't write to STDERR

### ISSUE THREAD

**Issue by danielpclark** [crystal-lang/crystal#4451]
crystal version

    Crystal 0.22.0 [3c71228] (2017-04-20) LLVM 3.5.0

Example bad code:

```crystal
ARGF.each
```
Build:

```bash
crystal build doesnt_compile.cr
```

STDOUT:

```
Error in doesnt_compile.cr:1: undefined method 'each' for IO::ARGF

ARGF.each
     ^~~~

Rerun with --error-trace to show a complete error trace.
```

STDERR is empty.

Exit status is 1

Same results with added flag `--error-trace`

**Comment by asterite** [comment]
I think this is fixed in master. Reopen if not (after the next release).
