### ISSUE TITLE
Can't comile on Alpine Linux Version 3.6.0 (Released May 24, 2017)

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#4480]
Trying to compile the compiler for more then 5+ hours.  
-  From git sources using the `bin/crystal` binary  
- machine has 4 Cores and 4Gb RAM.  

 I got a few pointers

1) It seems that RAM is not even going above 50Mb while compiling (good ? bad ?)  
2) The compiler wont use more then one core while working:  

![screenshot at 13-35-49](https://cloud.githubusercontent.com/assets/1631073/26528088/3a4f6b38-43ab-11e7-9062-2a4f3a206fde.png)

**Comment by bararchy** [comment]
@ysbaddaden Maybe you can shed some light on that ?

**Comment by RX14** [comment]
Can you show `--stats` output and the compiler version of the compiler used to compile the co compiler.

**Comment by bararchy** [comment]
@RX14 Seems it's an issue with the installation ? Can't get any compiler to emit any output 
@ysbaddaden , do you have a package I can use in Alpine ?

**Comment by ysbaddaden** [comment]
Yes, I have a repository at:
http://public.portalier.com/alpine 

How did you get a compiler for alpine in the first place?

**Comment by bararchy** [comment]
Hm... I just thought I can use the Generic Linux 64bit tar.gz package

**Comment by bararchy** [comment]
@ysbaddaden Seems like I can't solve deps with latest Alpine and your repo as you ask libevent 2.0 while the offical repo has 2.1.8

**Comment by ysbaddaden** [comment]
The Linux tarball is meant for glibc and libs must be compiled against glibc too. That's probably the issue.

Argh. I thought compiling on an older release (3.4) would avoid such issues. I guess I should build packages for a few versions (or at least the latest) instead...

**Comment by bararchy** [comment]
@ysbaddaden Latest sounds great :) as anyone can just `apk upgrade` to latest any time

**Comment by ysbaddaden** [comment]
Not really, you must specify the version in `/etc/apk/repositories` then run `apk upgrade`, otherwise you're stuck on `v3.4` for example. Also, versions are supported for ~2 years. I'm not motivated to build 3 or 4 Alpine packages.

BTW I just upgraded my VM to v3.6 and my crystal package installed and is running correctly...

**Comment by bararchy** [comment]
I'm pretty new to Alpine , just let me know on what version I should build and I'll jump to that :)

**Comment by weirdbricks** [comment]
@ysbaddaden one note - when I tried the wget command from http://public.portalier.com/alpine/ I got an error:

```
wget "http://public.portalier.com//alpine/julien%40portalier.com-56dab02e.rsa.pub" \
>   -O /etc/apk/keys/julien@portalier.com-56dab02e.rsa.pub
--2017-09-08 23:30:29--  http://public.portalier.com//alpine/julien%40portalier.com-56dab02e.rsa.pub
Resolving public.portalier.com... 137.74.127.78
Connecting to public.portalier.com|137.74.127.78|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-09-08 23:30:29 ERROR 404: Not Found.
```

Looks like there's a typo there: `http://public.portalier.com//alpine/julien` - the double `/` - please take a look if you have a second :) many thanks for your work on this!

**Comment by bararchy** [comment]
Not an issue for me anymore
