### ISSUE TITLE
Hash and Array auto conversion to bigger union type

### ISSUE THREAD

**Issue by relonger** [crystal-lang/crystal#4483]
_Crystal 0.22.0 (2017-04-20)_

We have auto conversion for variables:
```crystal
a = 6
b : Int32|String = a
```

but not for Arrays:
```crystal
c = [1,2,3] of Int32
d : Array(Int32|String) = c
```
*Error: type must be Array(Int32 | String), not Array(Int32)*

neither for Hashes
```crystal
x : Hash(Int32, Int32) = {5 => 6}
y : Hash(Int32, Int32|String) = x
```
*Error: type must be Hash(Int32, Int32 | String), not Hash(Int32, Int32)*

Why?

**Comment by konovod** [comment]
`Array` is a `Reference`, so assignment doesn't copy array `c` to `d`, it makes `d` point to the same array:
```crystal
c = [1,2,3] of Int32
d = c
d.clear!
p c
```
So conversion during assignment is impossible. But you can copy one array to another, I'm not sure what is most idiomatic\performant way to do it, e.g.
```crystal
c = [1,2,3] of Int32
d = Array(Int32|String).new(c.size){|i| c[i]}
```

**Comment by RX14** [comment]
An `Array(Int32 | String)` Has a different binary layout to a `Array(Int32)` because the union for each element has to be tagged:
```cr
sizeof(Int32) # => 4
sizeof(Int32 | String) # => 16
```

This means that any automatic conversion would require copying the whole array. This has a huge performance overhead and changes semantics: it's a different array so modifications to one don't show up in another (unlike how references should behave). It also wouldn't be possible to generalise auto conversions of generics to all different generic types.

The solution is to use map: `c.map(&.as(Int32 | String))` which explicitly does conversion and explicitly copies the array.

**Comment by jpsouzasilva** [comment]
@RX14 If you're converting an array type from one to another, in which cases you imagine someone would expect it to behave as a mirrored reference?

I prefer to think that it's universally more intuitive to assume you're always copying the references to a new, separate, disjointed instance when you're "converting" something; you're not mirroring the copied structure's state, but as the referenced elements are still shared by both, modifications in those references should reflect on both, obviously.  This is the case for C#'s [ToList(Type)](https://stackoverflow.com/a/2774116) method.

In my opinion automatic "magic" conversion for arrays are not needed as the effect's behavior is not clear enough through the syntax. For that reason, the programmer should always explicitly convert if he intends to do so.

**Comment by relonger** [comment]
> An Array(Int32 | String) Has a different binary layout to a Array(Int32) because the union for each element has to be tagged:

Yes, that's reasonable. Auto conversion with such types should be forbidden. But we have the same error with:
```crystal
c = [1,2,3] of Int32|Nil
d : Array(Int32|String|Nil) = c
```
Error: *type must be Array(Int32 | String | Nil), not Array(Int32 | Nil)*

```crystal
sizeof(Int32 | Nil) # => 16
sizeof(Int32 | String | Nil) # => 16
```

So `Array(Int32|String|Nil)` and `Array(Int32|Nil)` have the same binary format and can be used without changing binary structure - type controlling is made during compilation, not in runtime. So I think in that case auto conversion is still good idea.

**Comment by kirbyfan64** [comment]
@relonger That's still unsafe, though:

```crystal
c = [] of Int32|Nil
d : Array(Int32|String|Nil) = c

d.push "abc"
n = c[0]
if n
  puts n+1   # EXPLOSION: n is really a String.
end
```

**Comment by kirbyfan64** [comment]
Maybe there could be some sort of `copycast`:

```
puts c.copycast(Int32|String|Nil)
```

**Comment by RX14** [comment]
@kirbyfan64 a shortcut for `.map(&.as(Type))` could be added i'm sure.

**Comment by asterite** [comment]
In most cases if you need such conversion it's better to start off with an array that already has that type. Plus, there's no such thing as "autoconversion" in Crystal. I don't think there's much more, this issue appeared in the past several times and it was closed for the same reasons.
