### ISSUE TITLE
This seems like a weird performance profile

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#4484]
So I was looking at some performance stuff. 
Seems like these should have the same performance profile but they are really different.

```crystal
puts Benchmark.measure { Math.max(key_field, value_field) }
puts Benchmark.measure { (key_field > value_field) ? key_field : value_field }
```
Output:
```bash
  0.000000   0.000000   0.000000 (  0.000486)
  0.000000   0.000000   0.000000 (  0.000002)
```

**Comment by bew** [comment]
On my machine, I get:
```cr
require "benchmark"

key_field = 3
value_field = 5

Benchmark.ips do |x|
  x.report("Math.max") { Math.max(key_field, value_field) }
  x.report("ternary") { (key_field > value_field) ? key_field : value_field }
end
```
Gives:
```
Math.max  535.4M (  1.87ns) (± 4.99%)       fastest
 ternary 417.38M (   2.4ns) (± 9.15%)  1.28× slower
```

**Comment by wontruefree** [comment]
I am running against the brew version.
I should run from source to confirm.

**Comment by konovod** [comment]
with `ips` my results are similar to @bew, with `measure` results are similar to @wontruefree (not x100, but still x10 difference). And if you swap first and second line, second one become x10 faster.
 So benchmarking is hard and it is easy to measure something irrelevant, use ips etc etc.

**Comment by wontruefree** [comment]
I have a way smaller margin then you on my computer.
Math.max is still slower under ips.
```bash
Math.max 377.62M (  2.65ns) (± 9.57%)  1.00× slower
 ternary 378.84M (  2.64ns) (± 9.40%)       fastest
```

also under benchmark it is still really bad.
```bash
               user     system      total        real
Math.max   0.000000   0.000000   0.000000 (  0.000586)
ternary    0.000000   0.000000   0.000000 (  0.000002)
```

**Comment by wontruefree** [comment]
I get the same thing if I switch them.
Is this a benchmarking issue or a performance issue.
Seems like the benchmarking tool is doing some setup after setting the time or something.

**Comment by asterite** [comment]
Duplicate of https://github.com/crystal-lang/crystal/issues/4383

Not a bug. Read this: https://github.com/crystal-lang/crystal/issues/4383#issuecomment-299459954

**Comment by wontruefree** [comment]
I think I understand the IPS part.
But what about the straight up measurement part?
The difference seems like a decent chunk like 0.000586 vs 0.000002?

**Comment by faultyserver** [comment]
From the comment on #4383:

> That's because the time difference is so minimal (should tend to zero) that it's impossible to measure accurately.

Testing a single iteration with no warm-up is never going to give an accurate result; there are too many variables external to the code being tested that _will_ throw off the result. As another comment there says:

> This is probably something related to power management with your processor or some wacky environmental stuff. You're essentially measuring doing nothing, so environmental noise dominates.

Try testing with 1 billion iterations of each with a decent warmup period and compare the results:

```crystal
key_field = 3
value_field = 5

1_000_000.times{ (key_field > value_field) ? key_field : value_field }
1_000_000.times{ Math.max(key_field, value_field) }

puts Benchmark.measure { 1_000_000_000.times{ Math.max(key_field, value_field) } }
puts Benchmark.measure { 1_000_000_000.times{ (key_field > value_field) ? key_field : value_field } }



# =>
#  2.840000   0.000000   2.840000 (  2.855913)
#  2.420000   0.010000   2.430000 (  2.429247)
```

1 billion iterations in under 3 seconds means each one is doing an incredibly small amount of work. The performance difference likely comes from having to go through call conventions for `Math.max`. I don't know if LLVM automatically optimizes those out.

**Comment by asterite** [comment]
You can always use `fun` and `--emit llvm-ir`.

Write this:

```crystal
fun func1(x : Int32, y : Int32) : Int32
  Math.max(x, y)
end

fun func2(x : Int32, y : Int32) : Int32
  x >= y ? x : y
end
```

Compile with `--release --emit llvm-ir`.

Check the resulting `.ll` file for the definitions of `func1` and `func2`:

```llvm
; Function Attrs: norecurse nounwind readnone uwtable
define i32 @func1(i32 %x, i32 %y) local_unnamed_addr #6 !dbg !17873 {
entry:
  %0 = icmp slt i32 %x, %y, !dbg !17875
  %value2.value1.i = select i1 %0, i32 %y, i32 %x, !dbg !17875
  ret i32 %value2.value1.i, !dbg !17878
}

; Function Attrs: norecurse nounwind readnone uwtable
define i32 @func2(i32 %x, i32 %y) local_unnamed_addr #6 !dbg !17879 {
entry:
  %0 = icmp slt i32 %x, %y, !dbg !17880
  %y.x = select i1 %0, i32 %y, i32 %x, !dbg !17880
  ret i32 %y.x, !dbg !17881
}
```

Same code. So the difference in nanoseconds is understandable (it's a very low time).

As a side note, your code uses `>` in the ternay while `Math.max` uses `>=`, but still that difference should be negligible, if there's any.

**Comment by wontruefree** [comment]
Thanks. 
Totally get it now.
