### ISSUE TITLE
Add more PRNGs to stdlib

### ISSUE THREAD

**Issue by konovod** [crystal-lang/crystal#4493]
Mersenne Twister is a good PRNG, but it have some minor issues (easily predictable, large state-space, fails some statistical tests). There are relatively new algorithms that don't have such issues and are also several times faster.
As far as i know, there are two most popular modern families of algortithms, each claiming itself the best one - PCG family (http://www.pcg-random.org) created by Melissa O'Neill and Xorshift family created by Sebastiano Vigna and David Blackman(http://xoroshiro.di.unimi.it). There are some comparison tables on both sites and more information about issues with Mersenne Twister and other PRNGs. I'm definitely not qualified to say which one is better, but looks like currently xorshift algorithms have more adoption - they are used as a default PRNG implementation in JavaScript, Erlang, Nim, also are a part of Rust's stdlib (Rust is using ISAAC by default though). 

I've implemented in Crystal one algorithm from PCG family (PCG32-XSH-RR, aka pcg_basic) and currently recommended algorithms from xorshift family (xoroshiro128+ and xorshift1024*) here: https://github.com/konovod/prngs
General PRNGs characteristics:
 - PCG32-XSH-RR: 32-bit output, 16 bytes state, 2^64 period
 - xoroshiro128+: 64-bit output, 8 bytes state, 2^128 period
 - xorshift1024*: 64-bit output, 1028 bytes state, 2^1024 period
 - MT19937: 32-bit output, 2493 bytes state, 2^19937 period
 - ISAAC: 32-bit output, 2064 bytes state, around 2^8295 period(in average. Can be 2^40 for some seeds)

According to benchmarks, on my machine Xoroshiro128plus is 7.5 faster than currently used MT19937:
```
         Random::MT19937  28.05M ( 35.65ns) (± 2.21%)  7.63× slower
           Random::ISAAC  39.69M ( 25.19ns) (± 2.72%)  5.39× slower
Random::XorShift1024Star  94.46M ( 10.59ns) (± 3.99%)  2.26× slower
Random::Xoroshiro128plus  213.9M (  4.67ns) (± 4.99%)       fastest
           Random::PCG32 181.28M (  5.52ns) (± 4.66%)  1.18× slower
```

I understand that these PRNGs can be fine as a separate shard but I think asking worth it.
So, pros (vs MT19937 and ISAAC):
- much faster 
- use less memory for state
- not so predictable (vs MT19937 only)
- according to their authors, behave better in statistical tests (vs MT19937 only)

cons:
- relatively new, so it's possible some problems will be discovered in the future.
- isn't one used in Ruby
- lesser period (2^128 and 2^1024 vs 2^19937), still enough for most practical usages.

Question: should I make a PR to include them in std lib, and if yes - which one should be prefferred (pcg, xorshift, both).

**Comment by sdogruyol** [comment]
Wow amazing benchmarks 👍 Didn't know that there were so many good PRNGs. Thanks @konovod

**Comment by ysbaddaden** [comment]
I believe we kept MT19937 as default because it was faster and somewhat correct. It looks dated, and there are better and faster solutions, so we may reconsider changing the default.

I like ISAAC myself; I'm sure we could squeeze more performance out of it. We may not need a cryptographically secure RNG by default, but that wouldn't hurt.

WELL512 looks interesting. It's the successor to MT19937 and fixes some flaws (simpler, smaller period, ...). I'd love to see a benchmark.

The xorshift family looks incredibly fast. I couldn't find much information about its quality (except for the official website). The 128bits period may be a little short for a default RNG, which may be called a lot concurrently.

**Comment by konovod** [comment]
@sdogruyol I didn't know that too several days ago :smile: I thought PCG is just best one.
@ysbaddaden ISAAC is about 1.1 slower than MT in debug mode, so perhaps yes, it's llvm optimizations. 
WELL512 (implementation from http://lomont.org/Math/Papers/2008/Lomont_PRNG_2008.pdf) have almost same speed as ISAAC.
I've added sum of generated numbers to ensure that optimizations won't drop any operations, now results looks like:
```
        Random::MT19937  22.31M ( 44.83ns) (± 4.18%)  3.76× slower
           Random::ISAAC  33.05M ( 30.26ns) (± 5.11%)  2.54× slower
Random::Xorshift1024star  64.84M ( 15.42ns) (± 5.84%)  1.29× slower
Random::Xoroshiro128plus  83.87M ( 11.92ns) (± 4.84%)       fastest
           Random::PCG32   70.6M ( 14.16ns) (± 7.43%)  1.19× slower
         Random::WELL512  31.87M ( 31.38ns) (± 4.79%)  2.63× slower
```
As for 32-bit CPUs, I have a pretty old 32-bit Pentium 4, can try installing crystal there, but this will take some time and not sure its results will be useful.

As for quality, well, pcg site also says that statistical quality is "excellent", except for equidistribution (in xorshift1024 chances to get 0_u64 are twice lower, so it isn't equidistributional, but in practice chances to get one exact number are pretty low so it isn't very important).
I'll try setting up stat benchmark suites to test generators myself later.

**Comment by ysbaddaden** [comment]
I got sightly different results on my laptop (Intel Core i7-4712HQ, LLVM 3.9), where PCG32, xorshift1024* and xoroshiro128+ are just about the same speed.

```
         Random::MT19937  39.27M ( 25.46ns) (± 1.56%)  3.37× slower
           Random::ISAAC  60.22M ( 16.61ns) (± 0.66%)  2.20× slower
Random::Xorshift1024star 126.15M (  7.93ns) (± 0.88%)  1.05× slower
Random::Xoroshiro128plus 126.12M (  7.93ns) (± 1.03%)  1.05× slower
           Random::PCG32 132.43M (  7.55ns) (± 1.94%)       fastest
         Random::WELL512  64.45M ( 15.52ns) (± 1.16%)  2.05× slower
```

I have similar results in a Qemu ARMv6 virtual machine (LLVM 3.9), and as predicted, dealing with 64bits integers on a 32bits CPU kills performance:

```
         Random::MT19937    1.8M (554.64ns) (± 7.54%)  1.51× slower
           Random::ISAAC   2.11M (474.82ns) (± 9.67%)  1.30× slower
Random::Xorshift1024star   2.48M (403.14ns) (± 9.40%)  1.10× slower
Random::Xoroshiro128plus   2.59M (386.43ns) (±10.10%)  1.05× slower
           Random::PCG32   2.73M (366.44ns) (± 8.84%)       fastest
         Random::WELL512   2.05M (488.84ns) (± 8.54%)  1.33× slower
```

Conclusion: PCG32 performs well and is [statistically correct](https://www.researchgate.net/publication/305780776_FPGA_Implementation_of_F2-Linear_Pseudorandom_Number_Generators_based_on_Zynq_MPSoC_A_Chaotic_Iterations_Post_Processing_Case_Study).

**Comment by ysbaddaden** [comment]
I would like PCG32 to enter the corelib. I would even like if it replaced MT19937 as the default random implementation, because:

- it's faster (2.5 times in release, 3 times in non-release);
- it uses less memory (128bits vs 20000bits);
- it behaves equally well on both 32 and 64bit archs and in release/non-release modes;
- it's statistically correct (good distribution of numbers).

I think you can open a pull request :-)

**Comment by RX14** [comment]
@ysbaddaden Not knowing about RNGs, PCG32 seems to have a low period, how does that affect it's suitability for general use?

**Comment by konovod** [comment]
Period 2^64 is enough to generate thousand of numbers every microsecond for 500 years. Not overhelmingly much, but imho is enough for most uses. There is also a birthday paradox, but it uses 128 bits for seeding, so it shouldn't be a problem too.

There is a PCG64 variation, but it requires UInt128 (PCG64 = LCG128+64-bit output function, PCG32 = LCG64+32-bit output function).

**Comment by RX14** [comment]
Why do the other PRNGs have much higher period when 2^64 is already excessive?

**Comment by konovod** [comment]
Well, if you will generate a million of numbers per microsecond, it will take only half of the year to roll over, so a number isn't very excessive and can be not enough for some applications. For these cases stdlib should provide RNG with higher period. Mersenne Twister have very high period, but still fails some statistical tests and easily predictable after seeing 600 values, so high period doesn't guarantee high quality.

**Comment by funny-falcon** [comment]
Larger period is suitable for card games (poker), where number of variants is much larger than 2^64 .
And for any other gambling games, where lower period could be used for statistic cracking.

On other hand, gambling game authors should be qualified enough to not rely on RNG from standard library.
