### ISSUE TITLE
Easier use of Benchmark.measure

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#4497]
When using `Benchmark.measure` it is not easy to assign benchmarked values to variables outside the block scope. Say, I want to benchmark a method that returns a value and I want to use that value later. One way to do achieve this is to declare the variable beforehand and make in uninitialized:

```crystal
foo = uninitialized Foo
time_spent = Benchmark.measure do
  foo = create_foo
end
foo.do_something
```

While this block provided to `Benchmark.measure` should always be executed, the usage of `uninitialized` is still unsafe. Maybe some refactoring may shuffle things around and it might no longer be guaranteed that `foo` will be initialized. The compiler won't complain.
An alternative would be to initialize the variable with `nil` and use `not_nil!` afterwards, but it makes no real difference and is just a bit more complicated.
Both ways require do declare variable(s) beforehand, which is tedious and the great power of type inference is not used.

My first intention was to solve this with macros, but a macro with block would still require the variable to be at least declared outside the block (though it would be guaranteed to be initialized by the inlined block scope), and the benchmarking code as argument for the macro is not sufficient if there are multiple statements involved. As discussed in Gitter yesterday, the minimal benefit would probably not be worth the macro overhead.

But there is an easy way to make this better: Extract the code before and after the yield in `Benchmark.measure` into two methods `Benchmark.start` and `Benchmark.stop`. Then these two methods can be used anywhere and the code to be benchmarked can be in the same lexical scope as the rest (measures could also be overlapping each other).

The above example would look this way:
```crystal
benchmark = Benchmark.start
foo = create_foo
time = Benchmark.stop(benchmark)
foo.do_something
```
The stop line could also be `time = benchmark.stop` but I see little benefit from this, `start` and `stop` are nice and easy to remember.

Any ideas on this proposal?

**Comment by faultyserver** [comment]
Would this mean that multiple `Benchmark`s could be active at the same time? For example:

```crystal
benchmark1 = Benchmark.start
# do something
benchmark2 = Benchmark.start
# do more things
time1 = Benchmark.stop(benchmark1)
time2 = Benchmarl.stop(benchmark2)
```

Also, would it make more sense for `Benchmark.start` to return an instance that has a `stop` method instead of having to pass the returned value back to `Benchmark.stop`? More like this:

```crystal
benchmark1 = Benchmark.start
# do something
benchmark2 = Benchmark.start
# do more things
time1 = benchmark1.stop
time2 = benchmark2.stop
```

**Comment by straight-shoota** [comment]
Yes that would be possible. Start time is stored in local variables, and they can be used overlapping or even conditional. You can use it freely.

I've also considered your second example, but I think the other approach makes more sense, because start/stop are equivalent methods on `Benchmark` and the scope of operation keeps the same. But I would be fine with this, too.

Another nice treat: You can use the same starting point for multiple measurements:

```crystal
benchmark = Benchmark.start
# do something
time1 = benchmark.stop benchmark, "done something"
# do something else
time2 = benchmark.stop benchmark, "done something and something else"
```

**Comment by straight-shoota** [comment]
Closing since there has been no further interest in this matter.
