### ISSUE TITLE
File reading seek with UInt64 number crash

### ISSUE THREAD

**Issue by oltmannsdaniel** [crystal-lang/crystal#4498]
Error:
```
#<Errno:0x9c7640 @message="Unable to seek: Invalid argument", @cause=nil, @callstack=CallStack(@callstack=[Pointer(Void)@0x471d47, Pointer(Void)@0x471cda, Pointer(Void)@0x471caa, Pointer(Void)@0x462cbe, Pointer(Void)@0x4a56d3, Pointer(Void)@0x4da54a, Pointer(Void)@0x469179, Pointer(Void)@0x4859e4, Pointer(Void)@0x4684d6, Pointer(Void).null], @backtrace=nil), @errno=22>
```

Code for crash:
```crystal
file = File.new "./data/20gb.txt"
file.seek 18446744073709551615_u64

slice = Bytes.new 50000
file.read slice

puts String.new slice
```

How can I fix that?

**Comment by Sija** [comment]
Related to #3209

**Comment by asterite** [comment]
But...

```crystal
# 20 gb
21474836480 == 20 * 1024 * 1024 * 1024

# you are passing
18446744073709551615
```

The number `18446744073709551615` is huge and it's way more than 20 gb so I think it's natural that the seek will fail. Or am I missing something?

**Comment by ysbaddaden** [comment]
The offset is passed as is to `lseek`, so it's unrelated to the size overflow. Errno is EINVAL which means that the resulting offset (depending on whence) is negative or beyond the file size, which appears to the case, here.

**Comment by oltmannsdaniel** [comment]
@asterite @ysbaddaden Right. Thanks for the work. Really need to calculate more the next time.
