### ISSUE TITLE
vk.com ouath2 empty token_type

### ISSUE THREAD

**Issue by msa7** [crystal-lang/crystal#4503]
I try to use VK.com via OAuth2, but VK does not send `token_type`.
They use `Bearer` algorithm.

VK response:

```
{
\"access_token\":\"3453453453\",
\"expires_in\":86400,
\"user_id\":1856549,
\"email\":\"my_email@gmail.com\"
}
```

Crystal failed here [access_token.cr#L42](https://github.com/crystal-lang/crystal/blob/master/src/oauth2/access_token/access_token.cr#L42)

**Comment by asterite** [comment]
I'll fix this by assuming Bearer if not specified, because that's the most common type.
