### ISSUE TITLE
Random::System should be a module

### ISSUE THREAD

**Issue by oprypin** [crystal-lang/crystal#4505]
Followup to #4450

The recently added `Random::System` takes bytes from some source provided by the system. I [suggested](https://github.com/crystal-lang/crystal/pull/4450#discussion_r118019544) [previously](https://github.com/crystal-lang/crystal/pull/3434/files#diff-eac01542bbae5a5bc3e85cae61bc5109R28) that it should be a module, not a [struct without members](https://github.com/crystal-lang/crystal/pull/4450/files#diff-7228d011591bde19e79bed9633ead94dR8).

I think this emphasizes the fact that by definition `Random::System` cannot have state associated with it, makes it more convenient to use and showcases Crystal's powerful type system. `Random::System` would be possible to use as if it's an instance of `Random` in all cases (you really just drop the `.new` part), without needing to create these fake instances -- makes no sense to keep one and makes no sense to create one every time.

```crystal
module Random::System
  extend Random
...

Random::System.is_a? Random
Random::DEFAULT.is_a? Random
```

I feel that this suggestion has been drowned out by [unrelated discussion](https://github.com/crystal-lang/crystal/pull/4450#issuecomment-303436771) so I want to make a dedicated issue for it.

**Comment by ysbaddaden** [comment]
You're right. Another argument I could add is that on some UNIX each instance will open `dev/urandom` and thus consume a file descriptor. We could use a class var instead of an instance var, but using `Random::System` directly seems a better solution.
