### ISSUE TITLE
"Invalid memory access" in tuple members in Crystal 0.22

### ISSUE THREAD

**Issue by konovod** [crystal-lang/crystal#4520]
https://carc.in/#/r/251y
```crystal
class Node
  getter leaves : {Node, Node}?
  
  def grow
    n1 = Node.new
    @leaves = {n1, Node.new }
  end
  
  def process
    if l = @leaves
      p l[0].leaves #works ok, prints nil
      p l[1].leaves #fails with "Invalid memory access (signal 11) at address 0x0"
    end
  end
end

a = Node.new
a.grow
a.process
```
In the example, field with type `Tuple(Node, Node)` is initialized with two Node objects. First is initialized using local variable, and it works as expected (it has `@leaves=nil` ). But second is initialized without it and this leads to wrong initialization (it has broken `@leaves`).
The code works fine in Crystal 0.21 and before, so i think it is related to `malloc_atomic`, but there is no `abstract structs` like in #4492.

**Comment by MakeNowJust** [comment]
Is this related?

```
class Foo
  @foo : {Foo, Foo}?
end

t = {Foo.new, Foo.new}
pp t           # => {#<Foo:0x106560f00 @foo=nil>, #<Foo:0x106560ee0 @foo=nil>}
pp [nil, t][1] # => {#<Foo:0x106560f00 @foo=nil>, #<Foo:0x7fff59accff0 @foo=>}
```

When `nil` of `[nil, t]` is replaced to another value typed no `{Foo, Foo}` (like `[42, t]` or `["foo", t]`), it causes same strange behavior. If `@foo : {Foo, Foo}` is changed to `@foo :
 {Foo, Foo, Foo}`, it doesn't cause a strange, but on `t = {Foo.new, Foo.new, Foo.new}` it causes a strange. My observation found the rule: when `@foo.not_nil!.size == t.size` is `true`, it causes a strange.

Below doesn't cause a strange, so I think it is a problem about union type with tuple. (I'm not sure union type with tuple is abstract struct.)

```
class Foo
  @foo : {Foo, Foo}?
end

t = {Foo.new, Foo.new}
pp t
pp({nil, t}[1])
```
