### ISSUE TITLE
Some slight doubts about crystal language

### ISSUE THREAD

**Issue by guhenrique007** [crystal-lang/crystal#4523]
1)Objects can be representer by literal?

2)Which differentiates a common (weakly typed) variable of a union type, in this code how can i determine if it's union? I begin to think that all unrestricted type variables are unions, but I may be very much mistaken.
Exemple: 

if 1 + 2 == 3
  a = 1
else
  a = "hello"
end

**Comment by drosehn** [comment]
For your first question:

There are some classes where you can create a new object of that class by using a literal.  There is a list of them described at:
https://crystal-lang.org/docs/syntax_and_semantics/literals.html

You can click on a class-name listed under "Literals" in the column on the left-side.

**Comment by drosehn** [comment]
Your second question is a simple one, but I am not sure that I know a good answer for it.  😄   That probably means someone else will have a better answer than mine.

You could find out how the crystal compiler treats a variable by asking the compiler to do something that generates an error message.  For instance, this example prints out the class of variables `a` and `b` as they exist at run time:

```cr
if 1 + 2 == 3
  a = 1
else
  a = "Hello"
end
pp a.class

if 7 + 2 == 3
  b = 2
else
  b = "Greetings"
end
pp b.class
```
When I `run` that example, it prints out:
```cr
# crystal run check-const.cr
a.class # => Int32
b.class # => String
```
But if I add a third section to that simple program:
```cr
if 1 + 2 == 3
  a = 1
else
  a = "Hello"
end
pp a.class

if 7 + 2 == 3
  b = 2
else
  b = "Greetings"
end
pp b.class

if b.size > 10 
  c = 3
else
  c = "Goodbye"
end
pp c.class
```
then I get a compile-time error which shows that the variable `b` is considered a union-type at compile-time, even though we know it will be a `String` at runtime:
```cr
# crystal run check-const.cr
Error in check-const.cr:16: undefined method 'size' for Int32 (compile-time type is (Int32 | String))

if b.size > 10
     ^~~~

Rerun with --error-trace to show a complete error trace.

```

**Comment by drosehn** [comment]
I hope those answers will give you some help.

**Comment by konovod** [comment]
you can check the compile-time type with `typeof(a)` and actual class at runtime with `a.class`
https://crystal-lang.org/docs/syntax_and_semantics/typeof.html
So in first example the type is union.
```crystal
if 1 + 2 == 3
a = 1
else
a = "hello"
end
pp typeof(a), a.class
```
https://carc.in/#/r/259b

**Comment by asterite** [comment]
This is answered in the [docs](https://crystal-lang.org/docs/syntax_and_semantics/if.html)
