### ISSUE TITLE
Expectation for value included in collection

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#4532]
There is an expectation `contain` to check if a value includes a specific item, but not the other way round, if a value is included in a collection. I'd suggest to call it `be_in` - it's short and descriptive. `be_included` would also be possible, but is longer and to be grammatically precise it would be `be_included_in` which is even more characters.

For example, in stlib, the spec for `Array#sample` uses:
```crystal
x = [1, 2, 3].sample
[1, 2, 3].includes?(x).should be_true
# this reads better:
[1, 2, 3].sample.should be_in [1, 2, 3]
```

I've already implemented this as a custom expectation (https://github.com/straight-shoota/crinja/blob/e9b65286a10ef5981efe48ce363b5f9210450271/spec/spec_helper.cr#L45) and I'd be ready to create a PR if this idea is appreciated.

**Comment by asterite** [comment]
You can write:

```crystal
[1, 2, 3].should contain([1, 2, 3].sample)
```

Adding another way to do the same thing is redundant (we avoid aliases, and I'd also like to avoid multiple ways to do the same thing). So 👎  for me. I don't know what other core team members think about this.

**Comment by straight-shoota** [comment]
Usually the code to be tested is on the left side and `.should` receives an expectation about the result. Your example has the static reference value tested against the return value of the spec target code. It's twisted around.
This is of course possible but the change in semantics makes it difficult to understand the goal of the expectation: is it speccing `[1, 2, 3]` or `[1, 2, 3].sample`?

Before using this, I'd rather stick with the style in my first example: `[1, 2, 3].includes?(x).should be_true`.

**Comment by straight-shoota** [comment]
This idea doesn't seem to be appreciated.

Nowadays you can do `[1, 2, 3].sample.in?.should be_true` as a concise alternative.
