### ISSUE TITLE
Formatter removes line-break preceded by a backslash

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#4533]
The formatter tool removes the line-break from this code:

```crystal
puts \
  "foo"
```
Becomes:
```crystal
puts "foo"
```

While it might not be to disturbing in this case, imagine a longer expression instead of `puts`. The backslash codifies the line-break is there on purpose to keep the code better readable, thus it should not be removed by the formatter.

If there is a string in the first line the backslash plus newline is preserved:
```crystal
puts "foo" \
  "bar"
```

**Comment by bew** [comment]
Duplicate of #3383
