### ISSUE TITLE
`/usr/bin/ld: cannot find -lclang` error after executing

### ISSUE THREAD

**Issue by oltmannsdaniel** [crystal-lang/crystal#4541]
My code:
I cloned the [`crystal-lang/crystal_lib`](https://github.com/crystal-lang/crystal_lib), create a file to generate a ZLib Libary (Only for testing) with following code:
```crystal
@[Include("zlib.h", prefix: %w(zlib_ ZLIB_ ZLib))]
@[Link("zlib")]
lib ZLib
end
```

Then I ran `crystal run src/main.cr -- examples/lib_z.cr ` and it crashed.

My error:
```
daniel@daniel-desktop:~/code/crystal_lib$ crystal run src/main.cr -- examples/lib_z.cr 
/usr/bin/ld: cannot find -lclang
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "/home/daniel/.cache/crystal/crystal-run-main.tmp" "${@}"  -rdynamic  `llvm-config-3.6 --ldflags 2>/dev/null || llvm-config-3.5 --ldflags 2>/dev/null || llvm-config --ldflags 2>/dev/null` -lclang -lpcre -lgc -lpthread /opt/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
```

I followed the installation introduction and installed everything from the docs. But it still crashed, even after an update. What should I do to fix it?

My specs:
Crystal: `Crystal 0.22.0 [3c71228] (2017-04-20) LLVM 3.5.0`
Ubuntu: `Ubuntu 16.04.2 LTS`

**Comment by Sija** [comment]
I think [crystal-lang/crystal_lib](https://github.com/crystal-lang/crystal_lib) issues are more suitable for this.

**Comment by oltmannsdaniel** [comment]
@Sija No one is active on there, and the issues will be ignored.

**Comment by Sija** [comment]
@oltmannsdaniel I'm not sure what do you mean by "no one is active"... Last commit is from 2 days ago and the repo is maintained by the same Crystal core developers.

I could understand if you'd say it's **less active** than this one, but nevertheless your issue is strictly related to before-mentioned repo and not the Crystal itself.

**Comment by oltmannsdaniel** [comment]
Ok @Sija . But the last issue I opened a month ago didn't get any comment. So I just wanted to try it I've here.

**Comment by Sija** [comment]
@oltmannsdaniel Probably because you've opened it without using search first - which would tell you there's another such issue (https://github.com/crystal-lang/crystal_lib/issues/25) open, making yours a duplicate...

**Comment by asterite** [comment]
You just need to install libclang (or libclang-dev, can't remember). Any `/usr/bin/ld: cannot find -lxxx` error means you need to install `libxxx`

**Comment by oltmannsdaniel** [comment]
@asterite After installing `libclang-dev` I ran into a new error:

```
daniel@daniel-desktop:~/code/sandbox/crystal_lib$ crystal run src/main.cr -- examples/lib_git2.cr 
/usr/bin/ld: /opt/crystal/embedded/lib/../lib/libgc.a(os_dep.o): undefined reference to symbol '_end'
//usr/lib/x86_64-linux-gnu/libffi.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "/home/daniel/.cache/crystal/crystal-run-main.tmp" "${@}"  -rdynamic  `llvm-config-3.6 --ldflags 2>/dev/null || llvm-config-3.5 --ldflags 2>/dev/null || llvm-config --ldflags 2>/dev/null` -lclang -lpcre -lgc -lpthread /opt/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
```

What I tried:
- [x] Run `sudo ldconfig`
- [x] Added `/usr/local/lib` to the libary path

**Comment by asterite** [comment]
Oh, I don't know about that :-(

**Comment by Sija** [comment]
@oltmannsdaniel Do you have `libffi-dev` package installed?

**Comment by oltmannsdaniel** [comment]
@Sija Will try that later this day.

**Comment by oltmannsdaniel** [comment]
@Sija It is installed.

**Comment by ysbaddaden** [comment]
@oltmannsdaniel you hit #1269 for some reason, does `crystal build --link-flags="-lffi" ...` help?

Basically the error messages seems to say that the linker would link against `libffi` but refuses to, because `-lffi` isn't in the link command...

**Comment by RX14** [comment]
@ysbaddaden I _think_ the libffi error is misleading and it's just plain #1269 somehow.

The solution would be to compile your own native crystal and ditch the omnibus entirely.

**Comment by oltmannsdaniel** [comment]
@ysbaddaden @RX14 The link flag isn't working as well. The output was:

```
daniel@daniel-desktop:~/code/sandbox/crystal_lib$ crystal build --link-flags="-lffi" src/main.cr
/usr/bin/ld: /opt/crystal/embedded/lib/../lib/libgc.a(os_dep.o): undefined reference to symbol '_end'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libffi.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "/home/daniel/code/sandbox/crystal_lib/main" "${@}" -lffi -rdynamic  `llvm-config-3.6 --ldflags 2>/dev/null || llvm-config-3.5 --ldflags 2>/dev/null || llvm-config --ldflags 2>/dev/null` -lclang -lpcre -lgc -lpthread /opt/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
```

**Comment by sdogruyol** [comment]
Any update on this?

**Comment by oldaniel** [comment]
@sdogruyol As @RX14 said, compiling my own crystal worked to that point of time. I currently moved from Crystal to Golang. But I will use Crystal as my Playground again.

**Comment by sdogruyol** [comment]
Thanks for the update @oldaniel :+1:
