### ISSUE TITLE
A block that returns the wrong type can sometimes give a misleading error

### ISSUE THREAD

**Issue by shelvacu** [crystal-lang/crystal#4543]
```crystal
def foo(&block : -> Int32)
  res : Int32 = yield
  return res
end

foo{0u64}
```

This gives the somewhat confusing error:

```
Error in /home/shelvacu/crystal-test.cr:6: instantiating 'foo()'

foo{0u64}
^~~

in /home/shelvacu/crystal-test.cr:2: type must be Int32, not UInt64

  res : Int32 = yield
  ^~~
```

Instead of the real problem, the block given does not return the correct type. A slightly simpler version:

```crystal
def foo(&block : -> Int32)
  return yield
end

foo{0u64}
```

Gives the correct error message:

```
Error in /home/shelvacu/crystal-test.cr:5: expected block to return Int32, not UInt64

foo{0u64}
^~~
```

Tested against both `Crystal 0.22.0 (2017-04-22) LLVM 4.0.0` (stable release) and `Crystal 0.22.0+117 [4a9b86775] (2017-06-09) LLVM 4.0.0` (master branch) on Arch Linux x86_64

**Comment by asterite** [comment]
Marking as enhancement. The `yield` type check is verified at a later phase, so the other error (trying to assign UInt64 to Int32) triggers first.

This is super low priority, because using variable declarations like `res : Int32` is an anti-pattern in Crystal. Please don't use it.

**Comment by shelvacu** [comment]
This can also happen with somewhat more sane code, that was simply for the smallest test case. For example:

```
def some_library_bar(arg : Int32)
  #pretend this does something useful
  return arg + 1
end

def foo(&block : -> Int32)
  return some_library_bar(yield)
end

foo{0u64}
```

which results in

```Error in /home/shelvacu/crystal-test.cr:10: instantiating 'foo()'

foo{0u64}
^~~

in /home/shelvacu/crystal-test.cr:7: no overload matches 'some_library_bar' with type UInt64
Overloads are:
 - some_library_bar(arg : Int32)

  return some_library_bar(yield)
         ^~~~~~~~~~~~~~~~
```

**Comment by straight-shoota** [comment]
If you replace `yield` with `block.call`, it works as expected. So I guess, yield should be the same...

**Comment by MakeNowJust** [comment]
@asterite This is super high priority, because same unexpected happen by assignment to instance variable:

```crystal
class Foo
  @foo : Int32
  def initialize(&block : -> Int32)
    @foo = yield
  end
end

Foo.new { 42u32 }
# expected error message is:
#   expected block to return Int32, not UInt32
# but real error message is:
#   instance variable '@foo' of Foo must be Int32, not UInt32
```
