### ISSUE TITLE
Add an AMQP Client to the standard library

### ISSUE THREAD

**Issue by thedrow** [crystal-lang/crystal#4545]
I've always wondered why language libraries don't include the AMQP protocol.
Since AMQP is used everywhere and the specification is finalized both for 0.9.1 and 1.0 I see no reason why an AMQP client shouldn't be included in the standard library and an OAuth implementation should.

https://github.com/datanoise/amqp.cr implements AMQP 0.9.1, although it doesn't ship with many specs.
What do you think about merging it into the standard library when amqp.cr stabilizes?
cc @datanoise

**Comment by asterite** [comment]
Mmm... I don't think so. It seems to be a pretty new standard. The [AMQP website](https://www.amqp.org) looks very "enterprisey", speaking about a Product, Business cases, etc. Plus the [spec](http://www.amqp.org/sites/amqp.org/files/amqp.pdf) is a 133 pages PDF. No way we are going to maintain that 😸  Compare it to the [JSON spec](http://json.org/) which fits in a single HTML page, plus it's used all over the place.

I'm pretty sure this deserves to be in a third-party shard.
