### ISSUE TITLE
Unable to call the default constructor when there's a defined one

### ISSUE THREAD

**Issue by bew** [crystal-lang/crystal#4546]
```cr
class A
  @title = "This is a title"
  @content : String?

  def initialize(something : Array(String))
    @content = something.first
  end
end

# Use A.new(Array(String))
A.new ["a"]

# Use A.new    (with default values)
A.new # => wrong number of arguments for 'A.new' (given 0, expected 1)
```
https://carc.in/#/r/2663
gives:
```
Error in line 14: wrong number of arguments for 'A.new' (given 0, expected 1)
Overloads are:
 - A.new(something : Array(String))
```

All instance variables have a default value (`nil` for `@content` and `"This is a title"` for `@title`).

I expected `A.new` to call the default constructor, setting all instance vars to their default values.

**Comment by asterite** [comment]
That's not how it works. If you want a default initializer, define one that does nothing. And initializers are not inherited from a superclass if you define at least one.

**Comment by bew** [comment]
But:
```cr
class A
  @var = 2
end

pp A.new # => #<A:0x2633fe0 @var=2>
```
works by using an implicit initializer or something like that?

"The way it works" would need to do:
```cr
class A
  @var = 2
  
  def initializer
  end
end

pp A.new # => #<A:0x823c9e0 @var=2>
```

Also, I didn't found any documentation about this implicit initializer in the docs https://crystal-lang.org/docs/syntax_and_semantics/new,_initialize_and_allocate.html

**Comment by RX14** [comment]
If you class defines no constructors, it will get a default one, or inherit it's parents constructors if it has a parent. Otherwise the only constructors are the ones defined by you.

**Comment by bew** [comment]
> If your class defines no constructors, it will get a default one, or inherit it's parents constructors if it has a parent. Otherwise the only constructors are the ones defined by you.

Perfect, I think this should be in the in the documentation
Do you mind if I make a PR in [crystal-book](https://github.com/crystal-lang/crystal-book) with your message?
