### ISSUE TITLE
Syntax error in play:2: unexpected token: /

### ISSUE THREAD

**Issue by Daniel-Worrall** [crystal-lang/crystal#4547]
# Reproduction
The code: `%r()` in `crystal play`
v0.22.0
OS: Bash on Ubuntu for Windows (W10 Pro 64bit)
## Result
Exception of `Syntax error in play:2: unexpected token: /`

This was found from following the book online on the Regex section.

## Meta
```
$ crystal --version
Crystal 0.22.0 [3c71228] (2017-04-20) LLVM 3.5.0
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

**Comment by bew** [comment]
For the record, the generated (failing) code is:
```cr
_p.i(1) do
  //
end
```
