### ISSUE TITLE
Proposal: Explicit return type for methods returning self (update stdlib defs).

### ISSUE THREAD

**Issue by akzhan** [crystal-lang/crystal#4550]
What do you think about explicit return type that returns self?

 It's very useful for chained methods. It should be worked like https://play.crystal-lang.org/#/r/26ai

**Comment by ysbaddaden** [comment]
It can't infer this, because it would have to decipher what type the each chained method call returns, thus requiring a complete type analysis, which ain't available at this stage.

**Comment by asterite** [comment]
Yes, there's no way to do this. There have been a couple of issues that asked exactly this and we closed them.
