### ISSUE TITLE
Compile source from STDIN

### ISSUE THREAD

**Issue by TheLonelyGhost** [crystal-lang/crystal#4561]
---
**Suggested tags:** `compiler` `feature`

---

Given how [vim-crystal](https://github.com/rhysd/vim-crystal) and [ale](https://github.com/w0rp/ale) are built for vim, there is a syntax checker for crystal that is built by using the compiler. The problem I've faced with both of these plugins for vim/neovim are that the compiler cannot run against a file that does not exist.

I've begun hacking on _ale_ in order to improve the Crystal support for it, but it appears to be an issue that the compiler itself could help with. I'd like to:

```
$ echo 'puts "hello world!"' | crystal build --no-codegen --no-color -o /dev/null -f json -
```

The problem is that it tries to interpret the file named `-` as an actual file instead of reading the file contents from STDIN.

I understand this is a unix convention and we're focusing a lot more on cross-platform compatibility with even Windows support, but I feel like solidifying editor support would be a good way of doing that. Thoughts?

**Comment by asterite** [comment]
```
echo 'puts "hello"' | crystal eval
```

**Comment by TheLonelyGhost** [comment]
The problem is I'm looking for the build process without actually executing the code. I don't want to evaluate the file I'm editing, I just want to build it to find compile-time errors.

**Comment by drosehn** [comment]
How does *ale* work?  If *ale* is editing a file, then couldn't it just tell crystal to build the file that it is editing?  Or if it needs extra info, then create a copy of the file which has extra-info-lines in it, and then have crystal build that copy?  That's more work than writing to STDOUT and having crystal read STDIN, but I suspect it wouldn't be much work compared to what the compiler will have to do to compile the source.

Given the nature of compiling crystal code, I doubt you can get away with copying just a few lines to crystal at a time.  The compiler is going to need the whole source file if it's going to compile any of it.

**Comment by faustinoaq** [comment]
Use case for VSCode extension too, [L54](https://github.com/faustinoaq/vscode-crystal-lang/blob/master/src/linter.ts#L54).

Also in VSCode exists Language Server Support as alternative, so projects like [Scry](https://github.com/kofno/scry) by @kofno are very useful.

@TheLonelyGhost  Other way to implement a basic linter is using `crystal tool format --check -f json -`

**Comment by RX14** [comment]
Crystal should be able to accept source code input from stdin, it seems like a legitimate request. Interestingly using `/dev/stdin` as the file says "File /dev/stdin does not exist" which is incorrect.

**Comment by drosehn** [comment]
Well, this is what I started to type as my earlier response:

Another tactic might be using `/dev/stdin`:
```cr
$ echo 'puts "hello world!"' | crystal build --no-codegen --no-color -o /dev/null -f json /dev/stdin
```
(at least on macOS, freebsd, and linux), except that the `gather_sources(filenames)` method in [command.cr](https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/command.cr) has a check of:
```cr
      unless File.file?(filename)
        error "File #{filename} does not exist"
      end
```
(using `file?` instead of `exists?`)  However, it might be that several places in the compiler expect to be working with a file (and not an I/O stream) for input.  There might be a lot of other work needed before the compiler could work with a Source of which was an I/O stream.

but if someone wants to try it...

**Comment by luislavena** [comment]
@RX14 `/dev/stdin` is not a file, as @drosehn pointed out, current code is checking if the provided filename is a real file.

The other issue is that using STDIN, no filename will be possible to reference in the errors, so the compiler will need to fake one (say `stdin.cr`) when using the special `-` filename (per UNIX conventions).

Definitely having something that can check a buffer for errors instead of a saved file might help any linter process.

Cheers.

**Comment by drosehn** [comment]
> but if someone wants to try it...

Well, in a very brief test, if you change `file?` to `exists?`, it seems to work.

```cr
# cat /tmp/check-stdin.cr | ./bin/crystal build --no-codegen --no-color -o /dev/null -f json /dev/stdin
Using compiled compiler at `.build/crystal'
[{"file":"/dev/stdin","line":7,"column":16,"size":5,"message":"undefined constant Freed"}]
```

**Comment by drosehn** [comment]
... that was a file which compiled fine and produced no output, and then I added the line `openthing = Freed.new` and repeated the compile step.

**Comment by akzhan** [comment]
It works with no relative requires only, it should be handled too. thanks @drosehn for first step.

```
cat src/math/math.cr | ./bin/crystal build --no-codegen --no-color -o /dev/null -f json /dev/stdin
Using compiled compiler at .build/crystal
[{"file":"/dev/stdin","line":1,"column":1,"size":0,"message":"while requiring \"./libm\": can't find file './libm' relative to '/dev'"}]
```

**Comment by w0rp** [comment]
`--fake-source` is a good way to go. That's roughly how it works for `flake8` and `eslint`. The intention is to check the buffer in your editor for errors before you've saved your changes back to disk. Accepting stdin input and telling the program where your file will be on disk is about as good as it gets for checking for problems.
