### ISSUE TITLE
XML::Node attributes are read only

### ISSUE THREAD

**Issue by pedantic-git** [crystal-lang/crystal#4562]
The XML::Node has a documented `[]=` function that is meant to set attributes, but all this does is construct a fresh read-only XML::Attributes object and then try to call the non-existent `[]=` method on that.

Reproduce with:

```crystal
require "xml"
doc = XML.parse(%{<foo bar="baz"></foo>})
doc.root["bar"] = "qux"
```

produces:

```
Error in src/example.cr:3: instantiating '(XML::Node | Nil)#[]=(String, String)'

doc.root["bar"] = "qux"
        ^

in /opt/crystal/src/xml/node.cr:39: undefined method '[]=' for XML::Attributes

    attributes[name] = value
              ^
```

Let me know if there's anything I can do to help!

**Comment by pedantic-git** [comment]
Amazing! Thank you so much for the speedy fix!

**Comment by Sija** [comment]
@asterite Damn, you're fast today! I was goin' to tackle it, but it was too l8! :D
