### ISSUE TITLE
Formatter error with lambda initializer

### ISSUE THREAD

**Issue by konovod** [crystal-lang/crystal#4563]
```crystal
class Heap(K, V)
  @comparator : Proc(K, K, Bool)

  def initialize(@comparator = ->(x : K, y : K) { (x <=> y) == -1 })
  end
end
```
this file compiles and runs, but when trying to `tool format` it formatter says
`Error:, couldn't format 'zzz.cr', please report a bug including the contents of it: https://github.com/crystal-lang/crystal/issues`

was discovered during fixing https://github.com/jtomschroeder/crystalline

**Comment by RX14** [comment]
Wow, 6 minutes from reported to fixed. Nice job @asterite!
