### ISSUE TITLE
Confusing Regex::MatchData#size naming

### ISSUE THREAD

**Issue by MakeNowJust** [crystal-lang/crystal#4565]
`Regex::MatchData#size` returns **the number of capture group**, in other words `m.size` (`m` is `Regex::MatchData` instance) is difference from `m.to_a.size` always (`m.size + 1 == m.to_a.size`). `size` is very very popular method name on Crystal and `Regex::MatchData` looks like `Array`, so it makes me confusing.

I think `group_size` is better name for this method, and `size` should return same value of `m.to_a.size`. How do you think?

NOTE: Ruby's `MatchData#size` returns same value of `m.to_a.size`.

**Comment by straight-shoota** [comment]
Yes, it should be that `m[m.size - 1]` is the last element in the match data.

**Comment by asterite** [comment]
@MakeNowJust I agree with you
