### ISSUE TITLE
Class doesn't implement instance_vars

### ISSUE THREAD

**Issue by z64** [crystal-lang/crystal#4576]
Crystal 0.22.0
```cr
module M
  @attribute : String
end

# Will throw same exception as struct and module
class E
  extend M
end
```
```
BUG: Class doesn't implement instance_vars
0x40a0ce: ??? at ??
0xa5d6f1: ??? at ??
0xa5d115: ??? at ??
0xa5cc14: ??? at ??
0xa5cc14: ??? at ??
0xa5cc14: ??? at ??
0x11d02bf: ??? at ??
0x11d1389: ??? at ??
0x119eeed: ??? at ??
0x1068431: ??? at ??
0x106504b: ??? at ??
0x1b92f53: ??? at ??
0x47589e: ??? at ??
0x43c7ed: main at ??
0x7fead5e03511: __libc_start_main at ??
0x4097da: _start at ??
0x0: ??? at ??
```
https://carc.in/#/r/26zl

**Comment by akzhan** [comment]
Looks like a bug. 

M module introduce methods which later pass as class methods to E. So status of `@attribute` is unknown (looks like you should use `@@ attribute`). Anyway it's compiler bug to provide correct info.

**Comment by RX14** [comment]
Duplicate of https://github.com/crystal-lang/crystal/issues/4065

Please search before creating issues.

**Comment by z64** [comment]
Ah, I did, but the Open filter was on. Woops :D
