### ISSUE TITLE
Discussion: Hashing namespace with Hasher classes

### ISSUE THREAD

**Issue by akzhan** [crystal-lang/crystal#4578]
Currently Crystal ignores existence of HashFlood: hash function for base types is trivial "identity", and for strings it is very simple and easy to forge, and no any seeding performed.

Hash functions should be at least not-trivially forged when random seed used.

Design with separated hasher allows switch between different hash algorithms: default "safer" for public facing applications, and "faster" for non-tainted data.

As proposed by @RX14 

```crystal
class Object
  def hash
    Hashing::StdHasher.build do |hasher|
      hash(hasher)
    end
  end

  def hash(hasher)
    hasher << object_id
  end
end

class MyClass
  property foo : Foo
  property bar : Bar

  def hash(hasher)
    hasher << @foo << @bar
  end
end
```

Extracted from #4557 discussion because it may be discussed and implemented before.

/cc @RX14, @funny-falcon

**Comment by akzhan** [comment]
Looks like we need

```crystal
module Hashing
  alias Type = UInt32
  alias Sequence = Enumerable(UInt8)

  module Default
    def self.build
      accumulator = new
      yield accumulator
      accumulator.finalize
    end

    def <<( value : Sequence) : Type
      ...
    end

  struct StdHasher
    include Default
    ...
  end
end
```

**Comment by funny-falcon** [comment]
Looks a lot like I thought about.

There is also need for random seed. I understood how to generate it with SecureRandom, but I'm in doubdt how to share it between StdHasher and Int32Hasher (special case for Hash(Int32, V)). Can you give me an advice?

**Comment by akzhan** [comment]
Implement seed in another module like a Build. Extend classes with it and do `self.class.seed`.

By the way - hashers are reference classes in example above now.

**Comment by funny-falcon** [comment]
Here is draft of Hashing::StdHasher https://gist.github.com/funny-falcon/52eb622d689a2eae3e2d7b4e4a77d5ac

I strongly miss #1517 for convenience. Had to do wrapper struct holding pointer to implementation to achieve stack allocation + pass-by-pointer + convenient method calling. Compiler is not smart enough to allocate class-object on a stack.

**Comment by akzhan** [comment]
why not

```crystal
class String
  def hash(hasher)
    hasher << to_slice
  end
end
```
also looks like `Object.hash()` with build already does *.hash with build, so need no duplicated code. 
```

**Comment by funny-falcon** [comment]
> why not

Ah, you are right.

> also looks like Object.hash() with build already does *.hash with build, so need no duplicated code.

Sorry, I doesn't understand what you mean :-( This were example that compiles with unmodified master.
Of course I will modify original `Object#hash()` in pull request, if you mean that.
But still `Hash` may initiate builder by itself (for example, if per-hash-table seed will be accepted).

**Comment by akzhan** [comment]
Yes, I mean that.

Please feel free to clone crystal repo, `make crystal` and use `bin/crystal`.

It allows to do anything.

btw, I can do a lot with standard Crystal: https://play.crystal-lang.org/#/r/27bo

**Comment by funny-falcon** [comment]
Yes, I use `bin/crystal`.

**Comment by ysbaddaden** [comment]
Opening issues with code and no further explanations is only asking volonteers and search and seek for what the hell you are trying to solve. Please at least **explain** the issue, or nobody from the core team will care to take a look.

**Comment by funny-falcon** [comment]
Explanation:
Currently Crystal ignores existence of HashFlood: hash function for base types is trivial "identity", and for strings it is very simple and easy to forge, and no any seeding performed.

Hash functions should be at least not-trivially forged when random seed used.

Design with `def hash(hasher); hasher << @a << @b; end` allows switch between different hash algorithms: default "safer" for public facing applications, and "faster" for non-tainted data.

I'm working on an issue, and will do pull request next week, if no one complains against.

**Comment by ysbaddaden** [comment]
Thanks for taking the time to explain. I agree hash codes as currently implemented are simple but basic and problematic (leading to attack vectors).

> allows switch between different hash algorithms, one safer, one faster.

No. There should be a single hash solution, good for all use cases (safety first, then the fastest), implemented just like today: a generic `Object#hash` implementation, which can be overriden to better fits each struct/class data.

**Comment by funny-falcon** [comment]
After all, `hash(hasher)` is very reusable : one may use even SHA3 without changing a line, just supplying other hasher.

Though, there is a one pity point: `Hash#hash` currently key/insertion/iteration order agnostic. It will be quite difficult to preserve this property with `hash(hasher)`. Either one have to sort by keys before hashing, or declare that hashes with different iteration order are different.

**Comment by ysbaddaden** [comment]
`#hash` is something *nobody* should have to care about, even less deal with: the stdlib must do all the job, and do it so well that nobody else than stdlib maintainers have to worry about it. Overiding is for stdlib structs like Float64 or Time may provide specific solutions, if need be.

**Comment by RX14** [comment]
@funny-falcon while that might be useful, I think it's a bad idea to overly abstract this and implement some kind of class hierarchy so that you can use multiple hashing algorithms. You should just implement a single `Hasher` class which implements one good generic hash. If people want to use multiple hashing algorithms they can do so through duck typing.

**Comment by RX14** [comment]
@ysbaddaden everyone who defines custom equality also has to define a custom hash. We even have a macro `def_equals_and_hash` to make it simple for people to override the equality.

**Comment by funny-falcon** [comment]
@RX14,
>  I think it's a bad idea to overly abstract this and implement some kind of class hierarchy so that you can use multiple hashing algorithms.

No one talks about class hierarchy.

> If people want to use multiple hashing algorithms they can do so through duck typing.

With `def hash(h); h << @a << @b ; end` it is quite easy to pass non-default hasher with duck-typing.
Non-default hasher just have to implement following contract:
```crystal
class NonDefaultHasher
   def <<(v : Nil)
   end
   def <<(v : Int::Primitive)
   end
   def <<(v : Bytes)
   end
   def <<(v)
     v.hash(self)
   end
   # initialize and finish are omited
end
```
Without such contract use of duck-typing it is quite hard.

**Comment by RX14** [comment]
@funny-falcon yes you're exactly correct. I thought someone had proposed something complex but I was wrong. My bad.
