### ISSUE TITLE
Using a combination of included and inherited macros breaks when Reopening superclass

### ISSUE THREAD

**Issue by ziprandom** [crystal-lang/crystal#4580]
when I reopen a parent class and include a module that runs the ```inherited``` macro inside of the ```included``` like this: 

```crystal
module ANiftyModule
  macro included
    macro inherited
      def test
        "test"
      end
    end
  end
end

class Test; end

class TestChild < Test; end

class Test
  include ANiftyModule
end

pp TestChild.new.test
``` 

I get an error: 
```
undefined method 'test' for TestChild
```

Including the module on the first class declaration works however. I know this example is unrealistic and I could omit the ```included``` and ```inherited``` macros allthogether to get the expected behaviour, however in my real world scenario I'm not defining a method rather than yet another macro newly on every class that inherites directly or indirectly from the parent class. I want to define an api that is based on monkey-patching existing classes (and class hierarchies) to enhance their functionality.

**Comment by asterite** [comment]
Hey @ziprandom !

This is not a bug. Order of inclusion and definition of macros matter. In this case when the `ANiftyModule` is included, right then the `inherited` macro is defined and subsequent subclasses will invoke the hook, but previous subclasses won't. BTW, this is exactly the same as in Ruby, hooks begin to act after defining them. There's no way we can implement this without making it super confusing to understand.

**Comment by ziprandom** [comment]
@asterite I see. Anyway I'm having this situation in graphql-crystal where I want to enhance a given domain model by including the GraphQL::ObjectType and defining some fields to enable the GraphQL library to handle these objects in its resolution chain. 

So due to this behaviour I have to include the module here: https://github.com/ziprandom/graphql-crystal/blob/master/example/simple_blog_example.cr#L29

whereas I would like to be able to include the module just here: 
https://github.com/ziprandom/graphql-crystal/blob/master/example/simple_blog_example.cr#L200

I'm anticipating a situation in which the programmer wants to serve a given set of objects (that might have been included from a third party library) through the graphql system and cannot go back to the original place of definition. Do you have any suggestion for how to achieve this comfort?
