### ISSUE TITLE
Mutex: implement #try_lock and #sleep

### ISSUE THREAD

**Issue by docelic** [crystal-lang/crystal#4585]
Hello,

If possible, it would be useful to implement Mutex#try_lock and Mutex#sleep in a similar way to the Ruby interface:

 try_lock → true or false
Attempts to obtain the lock and returns immediately. Returns true if the lock was granted.

 sleep(timeout = nil) → number
Releases the lock and sleeps timeout seconds if it is given and non-nil or forever.

Thanks

**Comment by MakeNowJust** [comment]
@docelic Could you show us use cases of those methods?

**Comment by ysbaddaden** [comment]
I'm interested in use cases, too. I can fathom the need for trying to lock or doing something else, but I can't find actual any use case.

Though, it can help to avoid deadlocks when more than 1 mutex can be locked.

**Comment by docelic** [comment]
Hey, the specific use case I have here is that multiple threads (or in the case of Crystal, fibers currently) are reading/writing data on a single TCP connection, properly guarded by a Mutex.

Each of these fibers may encounter/detect a broken connection during execution. If that happens, they attempt to re-establish the connection. The one fiber that succeeds calling #try_lock will actually go ahead and run the connection re-establishment loop. Others who don't succeed on #try_lock go do something else until the connection is re-established and they can re-attempt their initial task.

Also somewhat related to this is the Mutex#owned? method, and the Ruby's interface is documented on e.g. http://ruby-doc.org/core-2.4.1/Thread/Mutex.html

Thanks!
