### ISSUE TITLE
tyepof caught Exception always returns "Exception"

### ISSUE THREAD

**Issue by TPei** [crystal-lang/crystal#4597]
I was expecting that `typeof(...)` would give me the exact class, but when rescuing an Exception `typeof(MyCustomException)` just returns `Exception`

```
class A < Exception; end
class B < A; end
    
begin
  raise B.new
rescue e
  puts typeof(e) # => Exception
end
```

Whereas `puts typeof(B.new)` returns B as expected.

**Comment by TPei** [comment]
this was on play.crystal-lang.org. I will check it out locally to verify in a minute

**Comment by TPei** [comment]
yep, same behaviour locally:
Crystal 0.22.0 (2017-04-20) LLVM 4.0.0

**Comment by bararchy** [comment]
I think that typeof is indeed Exception , but .class will give you what you want , I could be mistaken but I think that is intended

**Comment by TPei** [comment]
true, my bad!
