### ISSUE TITLE
Could not create union instance variable

### ISSUE THREAD

**Issue by funny-falcon** [crystal-lang/crystal#4602]
```crystal
class HastTbl(K, V)
  @entries : EntriesArray(K, V) = EntriesArray(K, V).new

  struct EntriesArray(K, V)
    struct Entry(K, V)
    end

    alias Chunk = Pointer(Entry(K, V))
    alias Chunks = Pointer(Chunk)
    alias Arr = Chunks | Chunk

    def initialize
      @arr = Chunk.new(0).as(Arr)
    end
  end
end
```
```
$ ../crystal/bin/crystal build hatest.cr
Using compiled compiler at `.build/crystal'
Error in hatest.cr:2: instantiating 'HastTbl::EntriesArray(K, V):Class#new()'

  @entries : EntriesArray(K, V) = EntriesArray(K, V).new
                                                     ^~~

in hatest.cr:13: instance variable '@arr' of HastTbl::EntriesArray(K, V) must be (Pointer(HastTbl::EntriesArray::Entry(K, V)) | Pointer(Pointer(HastTbl::EntriesArray::Entry(K, V)))), not (Pointer(HastTbl::EntriesArray::Entry(K, V)) | Pointer(Pointer(HastTbl::EntriesArray::Entry(K, V))))

      @arr = Chunk.new(0).as(Arr)
      ^~~~
```

other try

```crystal
class HastTbl(K, V)
  @entries : EntriesArray(K, V) = EntriesArray(K, V).new

  struct EntriesArray(K, V)
    struct Entry(K, V)
    end

    alias Chunk = Pointer(Entry(K, V))
    alias Arr = Int32 | Chunk

    def initialize
      @arr = Chunk.new(0)
    end
  end
end
```
```
$ ../crystal/bin/crystal build hatest.cr
Using compiled compiler at `.build/crystal'
Error in hatest.cr:2: instantiating 'HastTbl::EntriesArray(K, V):Class#new()'

  @entries : EntriesArray(K, V) = EntriesArray(K, V).new
                                                     ^~~

in hatest.cr:12: instance variable '@arr' of HastTbl::EntriesArray(K, V) must be Pointer(HastTbl::EntriesArray::Entry(K, V)), not Pointer(HastTbl::EntriesArray::Entry(K, V))

      @arr = Chunk.new(0)
      ^~~~
```
What should I do?
```crystal
class HastTbl(K, V)
  @entries : EntriesArray(K, V) = EntriesArray(K, V).new

  struct EntriesArray(K, V)
    struct Entry(K, V)
    end

    alias Chunk = Pointer(Entry(K, V))
    alias Arr = Int32 | Chunk

    def initialize
      @arr = Pointer(Entry(K, V)).new(0)
    end
  end
end
```
IT WORKS? WTF?

**Comment by kirbyfan64** [comment]
I think this is because the `K, V` in `HastTbl` and the `K, V` in `EntriesArray` are actually two different types; you'd probably have to drop the `K, V` in `EntriesArray`.

**Comment by asterite** [comment]
There's no way to reference generic type arguments in an alias. It should give a compile error.

**Comment by faustinoaq** [comment]
Hi people!

Using an abstract struct would help something:

```crystal
class HastTbl(K, V)
  @entries : EntriesArray(K, V) = EntriesArray(K, V).new

  struct EntriesArray(K, V)
    abstract struct Entry(K, V)
    end

    struct EntryC < Entry(K, V)
    end
    alias Chunk = Pointer(EntryC)
    alias Chunks = Pointer(Chunk)
    alias Arr = Chunks | Chunk

    @arr : Arr
    def initialize
      @arr = Chunk.new(0)
      pp typeof(@arr)
    end
  end
end

HastTbl(Int32, Int32).new
```

See: https://carc.in/#/r/28cw

Bye :smile:

**Comment by funny-falcon** [comment]
> There's no way to reference generic type arguments in an alias. It should give a compile error.

It should be fixed. Or other clear way should be given.

> Using an abstract struct would help something

Why it helps? Cause alias doesnt refer generic arguments? But it would be hard to understand.

Why `abstract struct Entry`? Will it work without `abstract`? Did you try to add `@k : K ; @v : V` to either struct?

**Comment by faustinoaq** [comment]
@funny-falcon No, struct doesn't help :sweat_smile: 

> Will it work without abstract?

No, I got error `can't extend non-abstract struct`

> Did you try to add @k : K ; @v : V to either struct?

Yes, I did and... I got a bug `ast from Nil to Crystal::GenericInstanceType+ failed`

**Comment by konovod** [comment]
Maybe not related, but generics+inheritance is currently pretty fragile combination imho. I've met bugs several times with it, now i prefer to just avoid it. I'm sure inheritance won't help here, there should be another way. 
If you don't need recursive aliases, only one level of nesting, I would try to (horrible) `@arr :  Pointer(Entry(K, V)) | Pointer(Pointer(Entry(K, V)))` and then use macros or private methods to minimize occurencies of a type in code.

**Comment by HertzDevil** [comment]
These examples now give `undefined constant K`, so I think this issue can be closed.
