### ISSUE TITLE
undefined method 'json_object' for String::Builder

### ISSUE THREAD

**Issue by amiceli** [crystal-lang/crystal#4606]
When I run JSON::builder example code : 

    require "json"

    result = String.build do |io|
      io.json_object do |object|
        object.field "address", "Crystal Road 1234"
        object.field "location" do
          io.json_array do |array|
            array << 12.3
           array << 34.5
         end
        end
      end
    end
    result

I've tollowing error : 

**'undefined method 'json_object' for String::Builder**

Did I miss something ?

**Comment by bew** [comment]
Where did you find that example?

**Comment by amiceli** [comment]
Here https://crystal-lang.org/api/0.19.4/JSON/Builder.html

**Comment by Sija** [comment]
@amiceli Since you've found solution, please close the issue.
