### ISSUE TITLE
using finalize()

### ISSUE THREAD

**Issue by need47** [crystal-lang/crystal#4615]
I want to create a class to maintain a http connection and try to close it in the finalize() method. But it seems this method will never be invoked.
 
```crystal
require "http/client"

class Foo
  def initialize
    puts "opening client"
    @client = HTTP::Client.new("www.google.com")
  end

  def finalize
    puts "closing client"
    @client.close if @client
  end
end

Foo.new 
```

**Comment by konovod** [comment]
`finalize` is called when GC is going to gather your object. This can happen at any time or never happen at all (especially if program don't eat much memory). You should close the client manually.

**Comment by need47** [comment]
Thanks for the info. I thought finalize() was like a destructor in c++ so one can do some clean up.

**Comment by RX14** [comment]
A typical pattern in crystal would be something like this:

```cr
require "http/client"

class Foo
  def initialize
    puts "opening client"
    @client = HTTP::Client.new("www.google.com")
  end

  def self.open
    foo = self.new
    begin
      yield foo
    ensure
      foo.close
    end
  end

  def close
    puts "closing client"
    @client.close if @client
  end
end

Foo.open do |foo|
  # use foo
end
```

**Comment by need47** [comment]
Thanks for the note. That's really helpful.
