### ISSUE TITLE
Playground bug "undefined method '<<' for Tuple(Int32, Int32, Int32)"

### ISSUE THREAD

**Issue by decademoon** [crystal-lang/crystal#4616]
## Crystal version

Crystal 0.22.0 (2017-04-20) LLVM 4.0.0
macOS 10.12.5
Installed with homebrew

## Code

```
a = 0, 1, 2
a << 5
```

## Exception

An modal is displayed: "You've reached a bug in the playground".

```
Error in line 4: instantiating 'Crystal::Playground::Agent#i(Int32)'
in line 4: instantiating 'Crystal::Playground::Agent#i(Int32)'
in line 5: undefined method '<<' for Tuple(Int32, Int32, Int32)
```

Shouldn't `a` be an `Array(Int32)` and not a tuple? Outside the playground it is an array and it works.

**Comment by bcardiff** [comment]
😕 I thought the `a = 0, 1, 2` would create a tuple, not an array...

Probably
https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/tools/playground/agent_instrumentor_transformer.cr#L101 should change to `rhs = ArrayLiteral.new(node.values)` and the specs would need to be adapted.

**Comment by jhass** [comment]
`a = 0, 1, 2` is no longer valid, `a = {0, 1, 2}` properly shows the error message and `a = [0, 1, 2]` works as expected.
