### ISSUE TITLE
[RFC] Allow * in array literals

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#462]
Some days ago someone [asked in IRC](http://irclog.whitequark.org/crystal-lang/2015-03-01#11979736;): `can you not [*1..10]?` (I like what he says next: "my mind is stamped in ruby ")

Ruby:

``` ruby
[*1..10] #=> [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```

In Crystal that doesn't even parse. But I think that could work.

Now, right now splats in Crystal only work on tuples. Let's say we allow splatting on any Enumerable:

``` crystal
def foo(x, y)
end

foo *ARGV
```

The compiler doesn't know how many arguments has ARGV. In this case it could transform the call to something like:

``` crystal
if ARGV.length == 2
  foo ARGV[0], ARGV[1]
else
  raise "wrong number of arguments..."
end
```

But I don't like that at all, because now we've got a hidden runtime error waiting to blow in our face.

With a tuple this isn't a problem at all because the compiler knows its length and types. So, this proposal isn't about changing semantics about splats in method calls.

However, there's nothing dangerous or wrong in splatting any enumerable inside an array literal. For example the compiler will translate this:

``` crystal
a = 1..5
b = [*a] 
```

To something like this:

``` crystal
a = 1..5
b = Array(typeof(...)).new
a.each do |elem|
  b << elem
end
```

The only problem that remains is determining the type of the array. For a regular array literal the compiler does this:

``` crystal
# this
a = [1, 2, 3]

# is translated to something like this
# (typeof gets the type of the arguments and merges them into, possibly, a union)
a = Array(typeof(1, 2, 3)).new
a << 1
a << 2
a << 3
```

The problem is that we don't know the type of the elements in the enumerable. Well, if we assume it includes Enumerable (and that would be a requirement for a splat inside an array to work) we could get the type from the first element:

``` crystal
# This currently works!
a = 1..5
b = Array(typeof(a.first)).new
a.each do |elem|
  b << elem
end
```

Similarly, if there are many arguments/splats inside the array we would use typeof on all of them.

Splatting would also work on custom array-like types, so you would be able to do:

``` crystal
Set { *1..9 }
```

Pros:
- Creating arrays out of many values which are possibly enumerable becomes super easy and readable.

Cons:
- Spaltting becomes a bit inconsistent: for method calls only tuples are allowed; for array literals any enumerable is allowed.

But if this is well documented I can't see a reason why we shouldn't add this to the language.

What do you think?

**Comment by Exilor** [comment]
I don't think it's such a bad idea to allow splatting enumerables in method calls if the fact that the compiler can't check their length for you is well documented.
I'd leave it up to the programmer to use such power responsibly.

**Comment by jhass** [comment]
I'm not 100% certain about many valid usecases, after all `[*1..10].each` is better written as `1.to(10)` and so on and I never needed an array initialized to those values actually, but I think the introduced inconsistency is tolerable.

**Comment by Exilor** [comment]
```ruby
a = 1..5
b = [*a] 
```
instead of your proposed change:
```ruby
a = 1..5
b = Array(typeof(...)).new
a.each do |elem|
  b << elem
end
```
it would be simpler turn it into
```ruby
a = 1..5
b = a.to_a
```
because all enumerables have ```#to_a``` at their disposal.

**Comment by bcardiff** [comment]
@asterite that inconsistency is not that bad. :+1: 
 
Another thought: for building arrays in a more flexible manner it might be enough to have some way to collect a enumerable into an array. Not just for ranges, but all enumerables.

**Comment by asterite** [comment]
Maybe my examples were not good enough :-)

Sometimes I need to create a new array from the elements of another array and then some other elements. Here's [one case](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/program.cr#L222). Here's [another one](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/semantic/call.cr#L314).

Basically, instead of doing this:

```crystal
a = [1, 2, 3]
e = 5
b = a.dup
b.insert 0, e
```

I will be able to do this:

```crystal
a = [1, 2, 3]
e = 5
b = [e, *a]
```

Which, in my opinion, is much readable and clear then the previous code. Sometimes I need to push one element in the front, sometimes in the end, sometimes more than one element.

Don't worry about the performance. Eventually the compiler can generate optimal code if it knows that `a` is an Array, and can allocate such Array with the precise number of elements needed, and assign to those position directly without bounds checking. The compiler knows everything. Let's worry about the semantics first :-)

I honestly **never** used a splat inside an array in Ruby code, but only because I didn't know about it. I sometimes ended up doing `foo + bar` or `foo + [1, 2, 3]` for compact code, which is less readable and less efficient too.

**Comment by ozra** [comment]
I don't know how common this use case is, but instead of new syntax, if it indeed is uncommon - can't it be solved with a macro or the like? Something along the lines of:
```crystal
b = make_array e, a
```
Of course with a more suitable name - just a thought of the top of my head...

**Comment by jhass** [comment]
@ozra I think we already have that. It's called `Enumerable#to_a`: `(1..10).to_a`

**Comment by kirbyfan64** [comment]
I like this idea. Python just got this with [PEP 448](https://www.python.org/dev/peps/pep-0448/), and I was super excited. Compare this:

```ruby
a.to_a + b.to_a + c.to_a
```

which creates 3 different arrays, only
