### ISSUE TITLE
Can't create a method with the name being a result of a macro

### ISSUE THREAD

**Issue by zatherz** [crystal-lang/crystal#4623]
https://carc.in/#/r/296b

```
def {{"abc".id}}
  puts "hi"
end

abc
```

Result: `expecting any of these tokens: IDENT, CONST, <<, <, <=, ==, ===, !=, =~, !~, >>, >, >=, +, -, *, /, !, ~, %, &, |, ^, **, [], []=, <=>, []? (not '{{')`

**Comment by Sija** [comment]
You're missing `begin/end` macro keywords, like:
```cr
{% begin %}
  def {{"abc".id}}
    puts "hi"
  end
{% end }

abc
```

**Comment by zatherz** [comment]
Wow, I had no idea that was a thing. I don't think it's mentioned in the docs either.
