### ISSUE TITLE
Format: failed to format regex after some comments

### ISSUE THREAD

**Issue by MakeNowJust** [crystal-lang/crystal#4626]
`crystal tool format` against this code is failed:

```crystal
1 # foo
/ /
```

I think this reason is `Crystal::Formatter#skip_space` skips comments and **following newlines**, thus the formatter reads `/` before calling `slash_is_regex!`. I tried to fix it yesterday. However, formatter implementation depends this strange behavior deeply. I'm looking for a way to fix it.

**Comment by sdogruyol** [comment]
Can we label this with `formatter`?
