### ISSUE TITLE
Command line tool to list doc comment flags

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#4629]
I think it would be nice to have a tool like [bin/rails notes](http://guides.rubyonrails.org/command_line.html#notes) which lists all doc annotations like `TODO` or `FIXME` in a crystal project. They are already highlighted in the docs (#3519) but there currently is no simple way to list all of them (except for grepping).

A very basic solution would be something like:
```crystal
Dir["src/**/*.cr"].each do |filename|
  File.each_line(filename).each_with_index do |line, lino|
    if matchdata = /\s*#\s*(TODO|FIXME|BUG|DEPRECATED|INFO|OPTIMIZE)[:\s]\s*([^\n]+)/.match(line)
      flags << {filename, lino + 1, matchdata[1], matchdata[2]}
    end
  end
end
```

A more complete implementation could hook into the docs generator and extract the flags from there. This could also respect multiline annotations and would be context aware, for example to distinguish a comment from a heredoc string.

**Comment by bew** [comment]
There are already very good code search tools, I'm not sure we need another one for this.

I use [`ack`](https://beyondgrep.com/) with this shell alias: `alias todo="ack -i 'todo|fixme'"`, it's easy and very powerful.

You can make one with `todo|fixme|bug|deprecated|info|optimize` if you need that kind of search.

**Comment by straight-shoota** [comment]
Yes, there are already possibilities out there. But they lack semantic understanding and are always individual solutions.
It think this is commonly usable enough and easy to solve in a general way as an additional compiler tool. There's no need to rush this, though, there are certainly more urging matters, but I just wanted to note this idea.

**Comment by luislavena** [comment]
There is room for a lot of these things @straight-shoota, other things like documentation analysis and such. The only issue, as always, is time availability 😄 

Personal opinion: if someone implements this as a shard/tool and works, perhaps there is room to integrate within the language (since the compiler source code is also part of the installation, you can access it at any time).

Looking forward what things others can build based on current parser 😃

**Comment by MakeNowJust** [comment]
I think this feature should be integrated to `shards` command, because it is not related to language, but it is related to project management.

Bonus: this is my private task of Makefile for this project to show note comments:

```makefile
notes: ## Show note comments like TODO, FIXME, BUG and etc...
	@grep -onE '# (TODO|FIXME|BUG|DEPRECATED|INFO|OPTIMIZE):.*' $(SOURCES) $(SPEC_SOURCES) |\
		grep -vE 'spec/compiler/crystal/tools/init_spec.cr' |\
		sort |\
		awk -F: '\
		{\
			if (current_file != $$1) {\
				printf("\n\033[1;4m%s\033[0m\n", $$1);\
				current_file = $$1;\
			}\
	\
			type = substr($$3, 3);\
			match($$0, /#.*: */);\
			text = substr($$0, RSTART + RLENGTH);\
			printf("  \033[1;30mline %-4d \033[0;32m%-6s\033[0;33m %s\033[0m\n", $$2, type, text);\
	\
			count += 1;\
		}\
	\
		END { printf("\n\033[31m×\033[0;1m %d note comments found\n", count); }\
	'
```

It shows very pretty output:

![2017-06-28 11 57 29](https://user-images.githubusercontent.com/6679325/27618727-fda85ca6-5bf8-11e7-84f3-a695cbac5295.png)

I'm welcome to use it by copy-and-pasting to `Makefile`.

**Comment by sevk** [comment]
suggest use crystal code to support other platform .

**Comment by straight-shoota** [comment]
@MakeNowJust Your example looks really nice, but why should this be a thing every developer has to configure on his own? And it is not context aware, I think this would be better handled by the compiler.
Since the docs generator supports these annotations I think it could be considered a part of the language... and it would be practical to have this directly in the compiler.
Besides, shards is for dependency management, not project management.

**Comment by MakeNowJust** [comment]
@straight-shoota You seem to want to integrate note comment listing tool with `crystal` compiler. But note comments can appear in not only `.cr` files but also `.c`, `.js` and other files when project uses other languages (e.g. this project has `.c` and `.cc` files, or web projects have often `.js` or `.css` files.) I don't think such a tool should be integrated with the compiler. And for this reason, project does not provide note comment listing tool in many case.

**Comment by straight-shoota** [comment]
Hm, this is a valid point.

Though I don't think it would hurt to have this vor Crystal source files only...
