### ISSUE TITLE
RFC: Flate Reader/Writer API inconsistency compared with Gzip

### ISSUE THREAD

**Issue by luislavena** [crystal-lang/crystal#4630]
When comparing the API provided by `Gzip::Writer` and `Gzip::Reader` on the `open` class method:

- [`Gzip::Reader.open`](https://crystal-lang.org/api/0.23.0/Gzip/Reader.html#open%28io%3AIO%2Csync_close%3Dfalse%2C%26block%29-class-method)
- [`Gzip::Wrtier.open`](https://crystal-lang.org/api/0.23.0/Gzip/Writer.html#open%28io%3AIO%2Clevel%3DGzip%3A%3ADEFAULT_COMPRESSION%2Csync_close%3Dfalse%2C%26block%29-class-method)

Noticed that `Flate::Reader` and `Flate::Writer` provide this auto-closing functionality on `.new` instead, without providing a matching `.open` method:

- [`Flate::Reader.new`](https://crystal-lang.org/api/0.23.0/Flate/Reader.html#new%28input%3AIO%2Csync_close%3ABool%3Dfalse%2Cdict%3ABytes%3F%3Dnil%2C%26block%29-class-method)
- [`Flate::Writer.new`](https://crystal-lang.org/api/0.23.0/Flate/Writer.html#new%28output%3AIO%2Clevel%3AInt32%3DFlate%3A%3ADEFAULT_COMPRESSION%2Cstrategy%3AFlate%3A%3AStrategy%3DFlate%3A%3AStrategy%3A%3ADEFAULT%2Csync_close%3ABool%3Dfalse%2Cdict%3ABytes%3F%3Dnil%2C%26block%29-class-method)

Considering Flate and Gzip compression/decompression interfaces, a parity between the two, at least from the top level, will be much appreciated.

Looking at the current usage in the codebase, the `&block` version of either `Flate::Reader` or `Flate::Writer` is ever used, making a case to perhaps introduce the consistency change.

Thank you in advance for your time and looking forward your comments. :heart: :heart: :heart:

**Comment by luislavena** [comment]
@mverzilli @bcardiff @RX14 thoughts?

**Comment by mverzilli** [comment]
@luislavena I think it makes sense, do you want to take a stab at it?

**Comment by luislavena** [comment]
@mverzilli yeah, was thinking on unify the API using `.new` for all the cases. Don't have the time this week but will invest some hours early next one.

Cheers.

**Comment by mverzilli** [comment]
Actually, for the auto-closing behavior I'd use `.open` instead of `.new`. Just because it feels a bit weird to create and close from the constructor. What do you think?

**Comment by RX14** [comment]
`.open` is the standard for constructors which call `#close`. Anything with a `.open` should also have a `.new` with the same args.

**Comment by mverzilli** [comment]
Yes, I think we're on the same page. So 👍 to unifying the APIs, 👎 to just using `.new`

**Comment by luislavena** [comment]
> Actually, for the auto-closing behavior I'd use .open instead of .new. Just because it feels a bit weird to create and close from the constructor.

That means remove the block constructor? Right now `.new` with block performs `#close`.

---

If I understand correctly:

- `Flate::Reader.new` changes to `Flate::Reader.open`
- `Flate::Writer.new` changes to `Flate::Writer.open`

In both cases, there is no longer a `.new` constructor that accepts a block and performs the `#close` action.

Thank you for your feedback.

**Comment by luislavena** [comment]
> `.open` is the standard for constructors which call `#close`. Anything with a `.open` should also have a `.new` with the same args.

Will love to have those conventions of the stdlib listed somewhere 😉

**Comment by mverzilli** [comment]
Good idea! Would the repo's wiki be a good place to start that?

**Comment by luislavena** [comment]
> Good idea! Would the repo's wiki be a good place to start that?

If not mistaken, part of the standard library *style* is already documented:

https://crystal-lang.org/docs/conventions/coding_style.html

So I think makes sense to add the stdlib conventions there too.

Cheers.

**Comment by RX14** [comment]
Sounds good to me.
