### ISSUE TITLE
crystal 0.23 reports old version number

### ISSUE THREAD

**Issue by need47** [crystal-lang/crystal#4642]
I installed crystal 0.23 from source. I've the following requirements:

- pre-compiled crystal-0.21.1-1-linux_x86-64
- gc 7.6
- llvm 3.9.1

In the source dir, I ran command 'make' and 'make spec'. All passed. But it seems crystal 0.23 is reporting 0.21.1 for me. See below.

$ ./crystal-0.21.1-1/bin/crystal -v
Crystal 0.21.1 [3c6c75e] (2017-03-06) LLVM 3.5.0

$ ./crystal-0.23.0-1/bin/crystal -v  
Using compiled compiler at `.build/crystal'
Crystal 0.21.1 (2017-06-29) LLVM 3.9.1

**Comment by MakeNowJust** [comment]
Crystal grabs version number from git or environment variable on compile time. I guess @need47 builds crystal from tar ball source.

**Comment by need47** [comment]
@MakeNowJust  Indeed, I used tar.gz

**Comment by matiasgarciaisaia** [comment]
Moving out of 0.23.1 release since its not a regression - was happening from before.

It would be nice to fix it, anyway 👍

**Comment by straight-shoota** [comment]
@MakeNowJust And it just took the 0.21.1 from the original compiler?

**Comment by matiasgarciaisaia** [comment]
It seems so - I've downloaded the 0.22.0 zip, built it with 0.23.0, and got it to report 0.23.0
