### ISSUE TITLE
String.split on empty string

### ISSUE THREAD

**Issue by Nephos** [crystal-lang/crystal#4644]
Hello,

I'm surprised to see that this result:

```
"".split("\n") # => [""]
```

Shouldn't the result of the split an empty array ? (cf: Ruby's behaviour)

**Comment by MakeNowJust** [comment]
But JavaScript is:

```javascript
console.log(''.split('')) // => []
console.log(''.split('\n')) // => ['']
```

**Comment by MakeNowJust** [comment]
On Crystal, `"".split` (without argument) returns `[]`, so I think it is a bug.

**Comment by MakeNowJust** [comment]
Related issue: #1070

**Comment by MakeNowJust** [comment]
No, I don't think it is not a bug. For example, `" foo  ".split` returns `["foo"]`, in other words `String#split` without argument ignores leading and trailing spaces, so this behavior is natural. However, the name `String#split` does not make sense. I think `String#words` is better for this behavior.

**Comment by MakeNowJust** [comment]
I think no argument version`String#split` behavior is corresponding to `%w` syntax.

**Comment by asterite** [comment]
The behavior is correct. When you split, you text existing pieces and try to find a delimiter. If no delimiter is found, the original string is returned in the result.

Ruby removes blank results and it's a bit confusing. In #1070 there was a discussion about it.

`split` without arguments splits on whitespace (any amount of it) and removes empty strings, so `"".split` will return an empty array. And I don't think we should rename it to `words`. We just need to document it better, that's it.

**Comment by MakeNowJust** [comment]
@asterite Thank you for answer. I'll close #4646.

**Comment by MakeNowJust** [comment]
@asterite Could you explain why you don't think we should rename `String#split` to `words`? (I guess it is breaking-change.) If possible, I abandon #4646 perfectly.

**Comment by asterite** [comment]
I actually think `words` is better than split. But I'm a bit tired of taking these micro-decisions, doing breaking changes, etc.

In fact, I will have very little time to dedicate to Crystal from now on, so I shouldn't have commented anything. It's better to target other core team members. Sorry...

**Comment by kirbyfan64** [comment]
> In fact, I will have very little time to dedicate to Crystal from now on

:O

**Comment by asterite** [comment]
After re-reading this, we can probably:

1. Leave `String#split` as it is now (`String#works` isn't good, because a piece might end up being something like "::%" which isn't a word, like, a word in a language)
2. We can probably add an option to `String#split(...)` to remove empty results.

**Comment by SoldierCoder** [comment]
> The behavior is correct. When you split, you text existing pieces and try to find a delimiter. If no >delimiter is found, the original string is returned in the result.
 
That is crappy behavior and not Ruby-like.  For example "1234".split('') in Ruby returns nice ['1','2','3','4'] why doesn't Crystal??

**Comment by Blacksmoke16** [comment]
Because this isn't Ruby and you can just do `"1234".chars` to get the same result.

**Comment by steakknife** [comment]
This is an unwelcome and unexpected surprise. This shouldn't happen. That we're talking about it is proof enough.
