### ISSUE TITLE
Hash literals doesn't show anything on Playground

### ISSUE THREAD

**Issue by matiasgarciaisaia** [crystal-lang/crystal#4670]
1. Run `crystal play` and visit http://localhost:8080/ in a browser
2. Change the code to `{} of String => Int32` or `{"this" => 13}` (or any hash literal?)

**Expected**: Playground should show something like `{} Hash(String, Int32)` in the right pane.
**Actual**: Playground doesn't show anything on the right pane.

Assigning the value to a variable (ie, `a = {} of String => Int32`) works like expected.

**Comment by marcosdsanchez** [comment]
This doesn't seem to be a bug specific to the playground

```
➜  ~ cat crystal.cr
p {1 => 2, 3 => 4}
➜  ~ crystal crystal.cr
Syntax error in crystal.cr:1: unexpected token: =>

p {1 => 2, 3 => 4}
     ^
```

Btw, this works:

```
p({1 => 2, 3 => 4})
```

it shows:

```
{1 => 2, 3 => 4}
```

**Comment by straight-shoota** [comment]
@marcosdsanchez In your code, the curly braces are interpreted as block delimiters instead of hash or named tuple literal. You always need to wrap those literals in parenthesis when using them as arguments to a call.
