### ISSUE TITLE
Can't define getter / setter / property with type (Nil | JSON::Any)

### ISSUE THREAD

**Issue by TPei** [crystal-lang/crystal#4671]
I can't seem to define a getter / setter / property with a Union of Nil and JSON::Any (or JSON::Type for that matter). 

```
class MyClass
  getter my_thing : (Nil | JSON::Any)
  
  def initialize(@my_thing = nil)
  end
end
```

throws the following error:
```
Error in line 2: expanding macro

in line 2: expanding macro

in macro 'getter' expanded macro: macro_47193264:113, line 4:

   1.       
   2.         
   3.           
>  4.             @my_thing : Nil | JSON::Any
   5. 
   6.             def my_thing : Nil | JSON::Any
   7.               @my_thing
   8.             end
   9.           
  10.         
  11.       
  12.     

undefined constant JSON::Any
```

(Nil | String) works fine though: https://play.crystal-lang.org/#/r/2ayi

Crystal 0.22.0 (2017-04-20) LLVM 4.0.0

**Comment by TPei** [comment]
Ok, turns out defining a getter etc for just `JSON::Any` is not possible either: https://play.crystal-lang.org/#/r/2ayn

**Comment by bew** [comment]
You need to `require "json"` in order to use JSON stuff:
```cr
require "json"

class MyClass
  getter le_json : JSON::Any
  
  def initialize(@le_json)
  end
end
```
https://play.crystal-lang.org/#/r/2ayq

**Comment by TPei** [comment]
omg, I am so sorry for that fail
