### ISSUE TITLE
shards update doesn't really update the shard

### ISSUE THREAD

**Issue by mixflame** [crystal-lang/crystal#4679]
We just fixed a bug in Amber that allows us to use 0.23.0

However, running ```shards update``` or ```shards install``` in my Amber app didn't get the new code.

Furthermore, when I forked it and updated both versions to 0.1.4 and pointed my shard.yml at this fork... It still claimed to be using 0.1.3.

Am I just yet again missing some piece of how to use shards properly? From my perspective this is still a bug. It points to a git repo, claims to be updating and then I get old code?

Can anyone help? Nothing worked except for directly hotpatching /lib/ folder with the new code.

Thanks

**Comment by RX14** [comment]
Please direct your issue to [crystal-lang/shards](https://github.com/crystal-lang/shards/issues) if it's about shards

**Comment by mixflame** [comment]
Ok np https://github.com/crystal-lang/shards/issues/160
