### ISSUE TITLE
Type not inferred on method that sets a class/instance variable

### ISSUE THREAD

**Issue by Fryguy** [crystal-lang/crystal#4681]
The following snippet will not compile:

```crystal
module Blah
  def self.blah
    @@blah ||= "blah/blah".split("/")[0]
  end
end
```

Giving

```
Can't infer the type of class variable '@@blah' of Blah

The type of a class variable, if not declared explicitly with
`@@blah : Type`, is inferred from assignments to it across
the whole program.

The assignments must look like this:

  1. `@@blah = 1` (or other literals), inferred to the literal's type
  2. `@@blah = Type.new`, type is inferred to be Type
  3. `@@blah = Type.method`, where `method` has a return type
     annotation, type is inferred from it
  4. `@@blah = arg`, with 'arg' being a method argument with a
     type restriction 'Type', type is inferred to be Type
  5. `@@blah = arg`, with 'arg' being a method argument with a
     default value, type is inferred using rules 1, 2 and 3 from it
  6. `@@blah = uninitialized Type`, type is inferred to be Type
  7. `@@blah = LibSome.func`, and `LibSome` is a `lib`, type
     is inferred from that fun.
  8. `LibSome.func(out @@blah)`, and `LibSome` is a `lib`, type
     is inferred from that fun argument.

Other assignments have no effect on its type.

Can't infer the type of class variable '@@blah' of Blah
```

The only workaround I've found is to directly interpolate it (though, interestingly, `.to_s` doesn't work):
`@@blah ||= "blah/blah".split("/")[0].to_s` - error
`@@blah ||= "#{"blah/blah".split("/")[0]}"` - no error

---

Similarly, this happens with just regular assignment, i.e. without memoization (though I've left memoization in the snippets because it makes no sense to *not* have it there), and it happens on instance methods as well.  The following is an example of an instance method that fails:

```crystal
class Blah
  def blah
    @blah ||= "blah/blah".split("/")[0]
  end
end

Blah.new.blah
```

**Comment by Sija** [comment]
You should annotate the class/instance variable, since it cannot be inferred.
See https://play.crystal-lang.org/#/r/2b4p

**Comment by konovod** [comment]
It is explained in docs: https://crystal-lang.org/docs/syntax_and_semantics/type_inference.html

**Comment by bew** [comment]
Actually, the error message explains it pretty well

**Comment by Fryguy** [comment]
Thank you!  I did not realize you could annotate instance variables directly at the class scope without using the `getter`/`setter` (which I didn't want).

Is there a reason this type of thing can't be inferred in the future?

**Comment by asterite** [comment]
@Fryguy There's a reason: you need the full type-inference algorithm to determine the type of instance variables, but for that you might need the type of other instance variables. It's a loop that must be avoided.
