### ISSUE TITLE
Ability to find out #step from an Iterator

### ISSUE THREAD

**Issue by docelic** [crystal-lang/crystal#4695]
With a code like:

v= (1..10).step(2)

It seems it is currently not possible to ask for the step of v.

In both Iterator.cr and in range.cr (in the private StepIterator) the getter for N does not exist.

It would be useful to have it.

My immediate use case:

I am serializing a Range with step defined, and instead of e.g. serializing (1..10).step(2) as "1,3,5,7,9", I would prefer to be able to serialize it as "1..10/2".

**Comment by straight-shoota** [comment]
This would require making `StepIterator` a public and documented class and it should also give access to  `@range`. You'd need this too if you want to serialize it.

**Comment by docelic** [comment]
Right, for the moment as a workaround, for just the @range part, I am using range.to_s which produces "x..y" or "x...y".

**Comment by asterite** [comment]
Step iterator is an implementation detail. It's not meant to be serializable. Just pass `x, y, step` to your serialized stuff. I don't think we'll change this.
