### ISSUE TITLE
Formatter does not indicate if it applied a change in single-file mode

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#4717]
When `crystal tool format` is used without any arguments or with multiple files/directories as arguments, it prints `Format: <filename>` for every file with a change.
If exactly one file is given as argument, there is no such output so a user can't know if the file was affected by the formatter or not.

I can't think of a reasonable explanation for why there should be no output for s single file.

**Comment by asterite** [comment]
Why do you need this output?

**Comment by straight-shoota** [comment]
I think it's logical to have it behave the same way regardless of whether the tool runs on one file or many.
A practical example: I'm working on a source file and stage the changes in the git index. Now I run the formatter but it doesn't give any output if it did anything or not. I'll need to check the return code or run `git status` to see if I have to add formatter changes to the index as well.
I could of course run the formatter anyway before staging, but I like to review the code changes produced by the formatter - to learn about my mistakes and to spot possible mistakes by the formatter.
