### ISSUE TITLE
Compiler don't detect recursive structs in case of generic modules

### ISSUE THREAD

**Issue by konovod** [crystal-lang/crystal#4720]
Related #1056
Maybe related? #4455

In a code 
```crystal
module A
end

struct B
  include A
  def initialize(@base : A)
  end
end
```
Compiler properly detects that B can contain instance of itself and it will cause problems.  https://carc.in/#/r/2dkn
But if we make them generics:
```crystal
module A(T)
end

struct B(T)
  include A(T)
  def initialize(@base : A(T))
  end
end
```
no message is issued.
This seems trivial in an example, but `module A` can be something pretty abstract, like `Enumerable`. And the problem is that in this situation it is difficult to find a bug - struct will work most times, but sometimes crash at runtime in a bad way. Somewhat minified example of such crash: https://carc.in/#/r/2dk1
It causes memory corruption in a runtime. On my machine it crash the X Window. So don't run it.
```crystal
module Matrix(T)
  def clone
    GeneralMatrix(T).new(data)
  end

  def inspect(io)
    io << data 
  end
end

class GeneralMatrix(T)
  include Matrix(T)
  property data 
  def initialize (@data : Int32)
  end
end

struct SubMatrix(T)
  include Matrix(T)
  property data = 0
  def initialize(@base : Matrix(T))
  end
end

m = GeneralMatrix(Float64).new(3)
m1 = SubMatrix(Float64).new(m)
pp m1, m1.clone
```

**Comment by sdogruyol** [comment]
Since #5099 is merged, can we update this? @asterite
