### ISSUE TITLE
Calling `GC.enable` actually disables the garbage collector

### ISSUE THREAD

**Issue by pglombardo** [crystal-lang/crystal#4721]
While investigating `GC.stats` values I found that calling `GC.enable` in my test app actually disables the garbage collector, `GC.stats` values never reduce/reset and the process memory size will continually grow.

![screen shot 2017-07-17 at 14 41 31](https://user-images.githubusercontent.com/395132/28268985-a3a48dda-6b00-11e7-8124-ab94aab34d49.png)

When `GC.enable` is called, `GC::stats.bytes_since_gc` will continually increase in value because the garbage collector is never run.  This is also true even if you manually call `GC.collect`.

To reproduce:
* Call `GC.enable` 1 or more times in any Crystal application
* Watch process memory size grow continually
* Watch values of `GC::stat.bytes_since_gc`

I've confirmed this on Crystal versions 0.23 && 0.23.1.

oprypin [suspects](https://gitter.im/crystal-lang/crystal?at=596cbc581c8697534a319a36):
> <oprypin> it could be crashing the GC thread or something https://github.com/ivmai/bdwgc/blob/1505f150c66ead87c275ddcef59f41d3eee80310/misc.c#L1811

The [original report](https://gitter.im/crystal-lang/crystal?at=596caf730de4d2545e36bcb9) on gitter.

**Comment by Groogy** [comment]
GC_dont_gc global variable will become non-zero which makes it evaluate to true and disable the GC. There's an assert guarding against it but if the library is compiled with NDEBUG that assert won't be present which I am guessing is the case here.

**Comment by RX14** [comment]
Essentially, `GC.disable` increments `GC_dont_gc` and `GC.enable` decrements `GC_dont_gc`. GC only runs if it's zero. This is done to enable nesting, and in debug mode there's an assertion to ensure the counter is never negative. This is disabled in release builds. There's also a call `GC_is_disabled()` which we could use in `GC.enable` to make it a no-op if it's already enabled.
