### ISSUE TITLE
clearing compile-time cache via crystal

### ISSUE THREAD

**Issue by drosehn** [crystal-lang/crystal#4730]
```cr
# crystal --version
Crystal 0.23.1 (2017-07-16) LLVM 4.0.1
# uname -a
Darwin gilead-qc124.netel.rpi.edu 14.5.0 Darwin Kernel Version 14.5.0: Tue Apr 11 16:12:42 PDT 2017; root:xnu-2782.50.9.2.3~1/RELEASE_X86_64 x86_64
```

I was compiling a program with `crystal build -release myprog.cr`, when I realized that there was an important change which I had forgotten to make.  So I did a `ctrl-c` to interrupt the compile, and made the necessary change to my source code.

When I then redid the `crystal build -release myprog.cr`, crystal hit an error and generated a long error output.  I did not save the output and do not remember what it said, but in glancing at it I was confident that the error was not caused by the changes I had just made.  So I removed crystal's compile-time cache for that program (under `~/.cache/crystal/full_path_to_myprog.cr`), redid the build command, and this time it compiled without any errors.

But then it occurred to me, what if I had not known about that cache directory?  The error message didn't say anything about the compile-time cache or where it was.  Is there some option to `crystal` or `crystal build` or `crystal tool` which would clear that directory for the user?  What if someone wanted to have a `make clean` target, and as part of that they wanted to remove that compile-time cache directory?

**Comment by crisward** [comment]
I've also had this issue, and I also knew about the cache. It also happens when you update crystal, the old cache often needs to be deleted. Crystal play can break between versions for the same reason.

It reminds me of the issue with node, when the only way to get something to work is delete the node_modules folder and re-install. It's not an obvious fix but one you kind of learn as part of the eco-system. 

The obvious solutions are 
* Store crystal version in cache, if it differs from current version delete cache
* Add a `crystal clean` command to clear the cache on demand

or just document the issue and tell everyone to user `rm -rf ~/.cache/crystal`

**Comment by asterite** [comment]
You can do:

```
rm -rf `crystal env CRYSTAL_CACHE_DIR`
```

**Comment by RX14** [comment]
It might be nice having a shortuct of that in the compiler executable, however.

I have to admit though, i've very rarely had to clean up the cache dir recently.

**Comment by crisward** [comment]
I've found I have to do it when I upgrade crystal. Perhaps the installer should reset the cache? Not sure if this is possible in the various package managers (brew apt etc..)

**Comment by RX14** [comment]
I've never had to clear my cache between versions?

**Comment by Sija** [comment]
@RX14 Occasionally I had to do it as well.

**Comment by drosehn** [comment]
I have had to clear the cache recently.  I'd guess two times in the last eight or nine weeks.  Once was after I had installed a new version of crystal, and once was when I had interrupted the compiler while it was compiling something I knew was going to generate errors.  I had started the compile, glanced at the source code and realized that I had not finished a change I was working on.  I had to clear the cache after fixing my source code, or the compiler would error out with some very weird error every time I tried to compile it.

**Comment by drosehn** [comment]
I don't think the installer should try to reset the cache, because that assumes the only person using crystal is the person who installs it.  I install crystal on my mac, but there are three separate userids which might use it.  The userid which installs crystal might not even have access to all userids which run crystal on that same machine.

Each cache is tied to a single userid.  So maybe have the cache include a marker of what version of crystal was used for the last compile.  If crystal starts up and sees that the cache has previously used by a different version of crystal, then it could auto-clear the cache.

**Comment by RX14** [comment]
Here's a quick idea which might make the compiler more robust: write the files to a tempdir inside the cache dir, and move them to their final place atomically once we know they're valid.

We shouldn't need to clear after a version change though, is there not a crystal version built in to the cache?

**Comment by SamantazFox** [comment]
Bump! It would be really nice to have such an option.

The most immediate example I can give is when a user tries to compile your code, and has weird errors because of version jumps. There should be a simple to start over, from a fresh state, without having to try to explain them which folder has to be deleted.

**Comment by HertzDevil** [comment]
I think this is a better shortcut than telling the user to run a certain shell command because a compiler command doesn't assume a particular shell.
