### ISSUE TITLE
URI.parse doesn't parse host correctly

### ISSUE THREAD

**Issue by watzon** [crystal-lang/crystal#4743]
**Expected behavior:**

When running `URI.parse("api.twitter.com")` the result should be `#<URI:0x5637ba188d20 @scheme=nil, @host="api.twitter.com", @port=nil, @path=nil, @query=nil, ...>`.

**Actual behavior:**

`URI.parse('api.twitter.com')` gives me `#<URI:0x5637ba188d20 @scheme=nil, @host=nil, @port=nil, @path="api.twitter.com", @query=nil, ...>`

What should be parsed as the host instead get's parsed as the path. Not sure if there's anything we can do about it, as I know URI parsing is tricky, but maybe we could have host parsing take priority over path parsing?

**Comment by kostya** [comment]
this is how in ruby works too. i have advanced parser for this cases, but it not a shard still.

**Comment by watzon** [comment]
@kostya maybe you could take a look at the built in URI parser and try to help fix it? Let’s be superior to Ruby!

**Comment by straight-shoota** [comment]
This behavior is expected and fully compliant to the [URI specification](https://tools.ietf.org/html/rfc3986). If you parse an URI without explicit scheme or authority component, it is interpreted as a relative URI. Therefore the string `api.twitter.com` is correctly parsed as `path`. To make it parse as a host, you should use `//api.twitter.com`.

If you wan't user-generated URI's parsed in a way similar to what modern browsers to (if you enter `api.twitter.com` it loads `http://api.twitter.com`) you'd need to handle this special case in your application code. This should apply to the case when the result from `URI.parse` does not have a `host` but the `path` *looks* like a domain name.

**Comment by RX14** [comment]
From reading the spec, `URI.parse`'s behaviour seems correct.
