### ISSUE TITLE
Missing docker image for 0.23.1 on https://hub.docker.com/r/crystallang/crystal/

### ISSUE THREAD

**Issue by splattael** [crystal-lang/crystal#4750]
Hi,

according to the [docker hub](https://hub.docker.com/r/crystallang/crystal/tags/) no docker image of the current Crystal version `0.23.1` has been pushed.

Is this on purpose?

Kind regards,
  Peter

**Comment by matiasgarciaisaia** [comment]
Hi @splattael! Sorry about that.

I've done the 0.23.1 release, focused too much on the distros, and completely forgot about the Docker image.

I'll try to slip this into my day today or tomorrow, and certainly will add this to the backlog of Things To Improve On The Release Process™.

Let you know whenever I got any news 👍

**Comment by matiasgarciaisaia** [comment]
@splattael - I've just pushed the 0.23.1 tag.

If you can check if it's working OK, please share the feedback so I update the `latest` tag too. Never done this before, so not sure if I'm doing anything wrong, he.

Thanks for the heads up!

**Comment by splattael** [comment]
@matiasgarciaisaia Thanks for pushing :+1: Look great so far!

During `crystal build --release` I get the following error:

```
/usr/bin/crystal build --release /builds/scoreboard/scoreboard.cr/spec/integration/server.cr --link-flags "-static" -o /builds/scoreboard/scoreboard.cr/bin/test-server
crystal: /var/cache/omnibus/src/llvm/llvm-3.8.1.src/lib/CodeGen/LexicalScopes.cpp:160: llvm::LexicalScope* llvm::LexicalScopes::getOrCreateRegularScope(const llvm::DILocalScope*): Assertion `cast<DISubprogram>(Scope)->describes(MF->getFunction())' failed.
/usr/bin/crystal: line 102:   172 Aborted                 (core dumped) "$INSTALL_DIR/embedded/bin/crystal" "$@"
make: *** [test-release] Error 134
```

I think it's related to #4719.

Using `crystal --release --no-debug` ([as suggested](https://github.com/crystal-lang/crystal/issues/4719#issuecomment-315711797)) works well though.

**Comment by matiasgarciaisaia** [comment]
Yeah - that's a 0.23.1 issue.

I've pushed 0.23.1 as `latest` - closing the issue now!
