### ISSUE TITLE
System::Random when using `/dev/urandom` doesn't seem to do any sanity checking

### ISSUE THREAD

**Issue by euantorano** [crystal-lang/crystal#4752]
The current [code for `System::Random`](https://github.com/crystal-lang/crystal/blob/master/src/crystal/system/unix/urandom.cr) doesn't seem to do any sanity checking when using `/dev/urandom` as the source for random data.

It's entirely possible for this file to be deleted or modified by a bad actor - at the least it should be checked that the file is a chaarcter device. It's also usually a good idea to set the `FD_CLOEXEC` on the file descriptor.

For some example code, you can always check out how libsodium do things: https://github.com/jedisct1/libsodium/blob/master/src/libsodium/randombytes/sysrandom/randombytes_sysrandom.c#L168

Also note that any changes made here need to be duplicated here: https://github.com/crystal-lang/crystal/blob/master/src/crystal/system/unix/getrandom.cr - it may be best to simply have one module for reading from `/dev/urandom`.

**Comment by ysbaddaden** [comment]
Thank you, I totally overlooked that part. There should indeed be some checks. Would you mind opening a PR, at least for the generic implementation?

As far as I know, `FD_CLOEXEC` should be already set, but we should made sure if it.

**Comment by euantorano** [comment]
I'll see what I can do, but I've never written any Crystal before. I just happened to notice this whilst checking the language out.
