### ISSUE TITLE
Improper resolving inherited constructors

### ISSUE THREAD

**Issue by imdrasil** [crystal-lang/crystal#4762]
# Submitting bugs
This one works well:
```crystal
class Parent
  property a : Int32

  def initialize(@a)
  end

  def initialize
    @a = 1
  end
end

class Child < Parent
end

puts Child.new.a
```

But if we define any constructor under child
```crystal
class Child < Parent
  def initialize(a)
    @a = a
  end
end

puts Child.new.a
```

We will get 
```
Error in line **: wrong number of arguments for 'Child.new' (given 0, expected 1)
Overloads are:
 - Child.new(a)
```

Affected  versions: 19.0, 20.0, 21.0, 22.0, 23.1.

Local machine configurations:
- Crystal 0.23.1 [e2a1389]  (2017-07-13) LLVM 3.8.1
- Ubuntu 16.01

**Comment by konovod** [comment]
According to https://github.com/crystal-lang/crystal/issues/4546#issuecomment-307631479 this is not a bug - if you define at least one constructor, no constructors from superclass can be used.

**Comment by straight-shoota** [comment]
In Crystal it is good practice to overload `self.new` instead of `initialize`.

**Comment by RX14** [comment]
In addition, you can also use `super` from the child constructor so you don't have to duplicate code.
