### ISSUE TITLE
super inside initialize

### ISSUE THREAD

**Issue by petoem** [crystal-lang/crystal#4764]
In #4762 @RX14 said its possible to use `super` from the child constructor.
Using the same example code as in the other issue, but adding a constructor that only calls `super` doesn't work.
https://play.crystal-lang.org/#/r/2gb3
```crystal
class Parent
  property a : Int32

  def initialize(@a)
  end

  def initialize
    @a = 1
  end
end

class Child < Parent
  def initialize
    super
  end
  def initialize(a)
    @a = a
  end
end

puts Child.new.a
```
Outputs: 
```
Error in line 13: this 'initialize' doesn't initialize instance variable '@a' of Parent, with Child < Parent, rendering it nilable
```

But the fun part starts now. If I remove the second constructor from the class `Child` it magically works.
https://play.crystal-lang.org/#/r/2gb4
```crystal
class Parent
  property a : Int32

  def initialize(@a)
  end

  def initialize
    @a = 1
  end
end

class Child < Parent
  def initialize
    super
  end
end

puts Child.new.a
```
Now crystal detects that the `Child` classes `initialize` method calls super which calls `Parent` classes `initialize` method that initializes instance variable `@a` of Parent.

**Comment by faustinoaq** [comment]
If you use `super(a)` instead of `initialize(@a)` the code works:

```crystal
class Parent
  property a : Int32

  def initialize(@a)
  end

  def initialize
    @a = 1
  end
end

class Child < Parent
  def initialize
    super
  end
  def initialize(a)
    super(a)
  end
end

puts Child.new.a # => 1
```

Minimal code with this issue:

```crystal
class A
  def initialize(@a = 1)
  end
end

class B < A
  def initialize
    super
  end
  def initialize(@a)
  end
end

B.new
```

Outputs:

```
Error in line 7: this 'initialize' doesn't initialize instance variable '@a' of A, with B < A, rendering it nilable
```

**Comment by RX14** [comment]
This looks like a genuine bug to me. `super` calls should count for variable initialization, and i can't see a way which this could be abused to break initialization.
