### ISSUE TITLE
Allow to find macros using tool implementations.

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang/crystal#4766]
Currently `crystal tool implementations` works for methods and functions, but not for macros.

I know `crystal tool expand` but it doesn't show enough information:

```crystal
macro imprime(texto)
  puts "{{texto}}"
end

imprime hola
```

Using tool expand with the code above:

```
>>> crystal tool expand -c /home/user/sample.cr:5:1 /home/user/sample.cr
1 expansion found
expansion 1:
   imprime(hola)

~> puts("hola")
```

It doesn't show information about location or position.

It's very useful for editor support and tooling, see: https://github.com/faustinoaq/vscode-crystal-lang/issues/4

I think would be useful to add location info to `crystal tool expand` or allow to find macros using `crystal tool implementations`.

**Comment by MakeNowJust** [comment]
Okay, I try to implement this. But current compiler does not keep the information wanted by you (Thus `crystal tool expand` and `crystal tool implementations` can't show this.), so I should modify the compiler a bit. Sorry, I needs some days to implement this. Please wait.

**Comment by MakeNowJust** [comment]
Implementing this on `crystall tool implementations` is very difficult because `crystal tool implementations` treats AST nodes after macro expansion.

**Comment by faustinoaq** [comment]
So, adding location info to `tool expand` is the right way.

**Comment by MakeNowJust** [comment]
Implement done. I'll write spec, then open a new pull request tomorrow. I am in bed now. Good night.

**Comment by faustinoaq** [comment]
@MakeNowJust Thanks you so much! Good Night :smile:

**Comment by MakeNowJust** [comment]
Screen shot:

![2017-08-01 19 18 04](https://user-images.githubusercontent.com/6679325/28820868-300a03a6-76ee-11e7-9542-63168c6d4830.png)

Interesting point is the line `# expand the macro 'imprime' (/Users/makenowjust/Projects/labo/crystal/a.cr:1:1)`.

@faustinoaq This is what you want, okay?

**Comment by straight-shoota** [comment]
Wow, @MakeNowJust you say you need some days to implement and an hour later you're done? Crazy guy  🥇
But what's wrong with your colors? There is so little contrast in your screenshot...

**Comment by MakeNowJust** [comment]
@straight-shoota I like little contrast color, but I should have taken care it when show to others. Sorry 🙇

**Comment by faustinoaq** [comment]
Yeah, your solution solve this issue. <3 <3 <3

A basic macro location is enough.

Does it show in json output too?

**Comment by MakeNowJust** [comment]
@faustinoaq Of course, yes. And this JSON structure is same as `crystal tool implementations` output, so I think it is easy to fix editor extension for this.
