### ISSUE TITLE
Unexpected newline after end in macro

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#4769]
The following code should compile but it fails with `Syntax error in eval:5: unexpected token: NEWLINE`:
```crystal
{% begin %}
  {% if true %}
    if true
  {% end %}
  {% if true %}
    end
  {% end %}
{% end %}
```
[carc.in](https://carc.in/#/r/2gj0)

That is a simplified version, a more complex use case is for example in [json/mapping.cr](https://github.com/crystal-lang/crystal/blob/master/src/json/mapping.cr#L154). Somehow this works but my code does not.

**Comment by straight-shoota** [comment]
A workaround:
```crystal
{%begin%}
  {% if true %}
    if true
  {% end %}
  {% if true %}
    {{"end".id}}
  {% end %}
{%end%}
```

**Comment by RX14** [comment]
This shouldn't compile. A macro should always contain an entire AST node. The top "macro" is actually 2 macros which expand to something invalid, the bottom macro is the correct way to write this.

**Comment by konovod** [comment]
I don't understand `{{"end".id}}` part. With `end` second macros looks correct (it is an entire node), but parser still shows an error. Isn't it a bug?

**Comment by RX14** [comment]
Ah yeah I didn't spot that, that may indeed be a bug.

**Comment by straight-shoota** [comment]
@RX14 I added `{% begin %}` and `{% end %}` to the original example, to make it more clear.

**Comment by straight-shoota** [comment]
By the way, if you try to remove the insubordinate newline: `Syntax error in eval:6: unexpected token: {%`
```crystal
{% begin %}
  {% if true %}
    if true
  {% end %}
  {% if true %}
    end{% end %}
{% begin %}
```
[carc.in](https://carc.in/#/r/2gj1)
