### ISSUE TITLE
Even never-called overloaded methods in child classes are still referenced by the compiler

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#4775]
https://play.crystal-lang.org/#/r/2ny6
```crystal
abstract class Dog
  def initialize(@color : String)
  end
end

class SpecialDog < Dog
  # This dog is unusual, it has size
  def initialize(color : String, @size : Int32)
    super(color)
  end
end

class B < Dog
end
class C < Dog
end

(rand < 0.5 ? B : C).new("test")

# => Error in line 18: wrong number of arguments for 'SpecialDog#initialize' (given 1, expected 2)
```
Note that `SpecialDog#initialize` is never called.

**UPD:** Minified the issue.

**Comment by ysbaddaden** [comment]
Please try to reduce further to a minimal reproducible example, then copy-paste it here. Thanks!

Maybe related: #4764

**Comment by vladfaust** [comment]
@ysbaddaden I have updated the issue

**Comment by vladfaust** [comment]
Interesting - if change this `select_animal.new("Rainbow").noise` to this `select_animal.new(color: "Rainbow").noise`, it will normally compile with first case, but fail with the second with **another error**: `wrong number of arguments for 'Abstract::Dog#initialize' (given 0, expected 1)`

**Comment by konovod** [comment]
Reduced: 
```crystal
abstract class Dog
  def initialize(@color : String)
  end
end

class SpecialDog < Dog
  # This dog is unusual, it has size
  def initialize(color : String, @size : Int32)
    super(color)
  end
end

class B < Dog
end
class C < Dog
end

(rand < 0.5 ? B : C).new("test")
```
https://carc.in/#/r/2gp2
The problem is that `(B | C)` is unified to `Dog+` class, that include `Special` dog.
That is described in docs https://crystal-lang.org/docs/syntax_and_semantics/virtual_and_abstract_types.html so is not a bug, but there is an issue about removing this behaviour: #2661

**Comment by vladfaust** [comment]
@konovod if a developer thinks of that behavior as a bug, that means that this behaviour is very unwanted for him; so maybe it worths removing.

**Comment by RX14** [comment]
@vladfaust We can't "simply remove" this behaviour. It's been done for performance and code size reasons.

**Comment by vladfaust** [comment]
@RX14 not a big deal for my project, there are some possible ugly workarounds like defining additional methods to set additional variables; we should keep an eye on this issue, maybe there will be more developers which will consider this issue significant :+1:

**Comment by straight-shoota** [comment]
A workaround is to declare `SpecialDog.new(String)` and throw an exception if it is called.

**Comment by asterite** [comment]
This is not a bug. `B | C` as a type is `Dog+`, and there's no constructor for Dog that accepts a size.

Super simple way to accomplish what you want:

```crystal
rand < 0.5 ? B.new("test") : C.new("test")
```

**Comment by vladfaust** [comment]
@asterite what if there are lots of children and not `rand` but a `case` with many branches and the payload isn't a simple "test"? Code duplication!

**Comment by vladfaust** [comment]
Crystal flow for me is constant "find a workaround". I'd like the language to follow my expectations :cry:

**Comment by asterite** [comment]
You can define `ColorlessDog` and have `B` and `C` extend from it. Then `B | C` will become `ColorlessDog` and it will work:

```crystal
abstract class Dog
  def initialize(@color : String)
  end
end

abstract class ColorlessDog < Dog
end

class SpecialDog < Dog
  # This dog is unusual, it has size
  def initialize(color : String, @size : Int32)
    super(color)
  end
end

class B < ColorlessDog
end

class C < ColorlessDog
end

(rand < 0.5 ? B : C).new("test")
```

The language really sucks regarding its type system, unions, and unifying to a base class type, but that's what we have and that's what we have to stick with.
