### ISSUE TITLE
Formatter bug

### ISSUE THREAD

**Issue by benoist** [crystal-lang/crystal#4782]
This code:

```crystal
object[foo: "foo",
  bar: "bar"
]
```

After first format, gets formatted to: (note the extra comma after "bar")

```crystal
object[foo: "foo",
  bar: "bar",
]
```

After second format:
`Syntax Error: expected named argument, not ]`

Crystal version:
Crystal 0.23.1 (2017-07-13) LLVM 4.0.1

**Comment by MakeNowJust** [comment]
This is a bug about the parser because trailing comma in index notation should be parsed also. I fixed this in #4784. Thank you for reporting 👍
