### ISSUE TITLE
Floating point numbers constants

### ISSUE THREAD

**Issue by rumenzu** [crystal-lang/crystal#4785]
Currently, `Float32` and `Float64` data types both provide `NAN`, `INFINITY`, `MIN`, and `MAX` constants, with `MIN = -INFINITY` and `MAX = INFINITY`.

In order to provide meaningful values for floating-point arithmetics, I suggest: 
1. To change `MIN`and `MAX` respectively to the smallest finite value and the largest finite value that can be represented.
2. To add extra constant values, such as:
    - `EPSILON`: the machine epsilon (difference between `1.0` and the next representable value).
    - `DIG` : the number of decimal digits that can be represented without losing precision.
    - `RADIX`: the radix or integer base used by the internal representation.
    - `MANT_DIG`: the number of digits that can be represented without losing precision (in base `RADIX`).
    - `MIN_EXP`: the minimum possible normal power of 2 exponent.
    - `MAX_EXP`: the maximum possible normal power of 2 exponent.
    - `MIN_10_EXP`: the minimum possible power of 10 exponent (such that `10**MIN_10_EXP` is representable).
    - `MAX_10_EXP`: the maximum possible power of 10 exponent (such that `10**MAX_10_EXP` is representable).
    - `MIN_NORMAL` or `MIN_POSITIVE`: smallest representable normal value that is not 0.

**Comment by konovod** [comment]
+1 to `EPSILON`. I don't know about usefulness of other constants, but EPS is needed, would be nice to have it in stdlib.

**Comment by straight-shoota** [comment]
This actually just means to expose the according [constants from libc](https://www.gnu.org/software/libc/manual/html_node/Floating-Point-Parameters.html), or am I missing something?

That's how Ruby is doing it: [numeric.c](https://github.com/ruby/ruby/blob/9f5a468cf95779493ba6277083e59aa0c028c449/numeric.c#L5463) ([docs](https://ruby-doc.org/core-2.4.0/Float.html))

Additionally there is also `ROUNDS`: Represents the rounding mode for floating point addition.

**Comment by RX14** [comment]
I'm confused, what's the point of `RADIX` and `MANT_DIG`? Won't `RADIX` always be 2? Do we define Float32/Float64 to always be IEEE single and double precision floats?

**Comment by konovod** [comment]
@straight-shoota As ruby is written in C, it is easy for it to expose it - just include "float.h". For a Crystal i think there should be directly written values of these constants, like in [Rust](https://github.com/rust-lang/rust/blob/master/src/libcore/num/f64.rs)

**Comment by rumenzu** [comment]
Unfortunately I don't have a use-case for all of them, but a lot of languages exposes those constants (Rust, Ruby, Vala, Java, C, C++, ...).

Some of them are used for comparison purposes, it is the case for `EPSILON`, `MIN_NORMAL` or `MAX` (see [here](https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/) and [there](http://floating-point-gui.de/errors/comparison/)).
[Rubinius](https://github.com/rubinius/rubinius/blob/master/core/float.rb#L69) uses `MANT_DIG` to rationalize floats.
I guess they also could be useful when it comes to format numbers.

@RX14, I don't know if `RADIX` is relevant or not, but it seems the IEEE 754-2008 standard defines base 2 or base 10 as a possible radix. So even if the constant is always 2 in Crystal, it may be useful for someone looking this information?

As for it is best to expose those constants from libc or to assign values directly as suggested by @konovod, since the size of the data types is known, I guess they can be assigned. On the other hand, [Vala](https://github.com/GNOME/vala/blob/3591ebadadd5255a1e4b8aed643635fb174eed54/vapi/glib-2.0.vapi#L767) seems to use libc, in contrast to Rust. Maybe using libc would be less error prone?

**Comment by konovod** [comment]
Vala is (afaik) compiled to C, so it has no problems with using C stdlib headers. 
I don't see a way how can Crystal use constants declared in C header "float.h". They aren't exported from some system .so, right? And adding a c-file to compiler sources just for these constants seems wrong.

**Comment by rumenzu** [comment]
True, I forgot they are defined as macros in `float.h`
