### ISSUE TITLE
`crystal docs` fails

### ISSUE THREAD

**Issue by miketheman** [crystal-lang/crystal#4786]
```shellsession
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29

$ make clean crystal
Using /usr/local/opt/llvm/bin/llvm-config [version=4.0.1]
rm -rf .build
rm -rf ./doc
rm -rf src/llvm/ext/llvm_ext.o
rm -rf src/ext/sigfault.o src/ext/libcrystal.a
c++ -c  -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc `/usr/local/opt/llvm/bin/llvm-config --cxxflags`
cc -fPIC    -c -o src/ext/sigfault.o src/ext/sigfault.c
ar -rcs src/ext/libcrystal.a src/ext/sigfault.o
CRYSTAL_CONFIG_PATH=`pwd`/src ./bin/crystal build  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib

$ bin/crystal --version
Using compiled compiler at `.build/crystal'
Crystal 0.23.0+35 [890ab45bf] (2017-08-04) LLVM 4.0.1


$ bin/crystal docs
Using compiled compiler at `.build/crystal'
Error in line 1: while requiring "./src/**"

in src/lib_c/aarch64-linux-gnu/c/dirent.cr:1: while requiring "./sys/types"

require "./sys/types"
^

in src/lib_c/aarch64-linux-gnu/c/sys/types.cr:1: while requiring "../stddef"

require "../stddef"
^

in src/lib_c/aarch64-linux-gnu/c/stddef.cr:2: alias SizeT is already defined

  alias SizeT = ULongLong
  ^
```

I tried to go back in time and figure out when it was last working, but had issues with changing my LLVM setup.

**Comment by straight-shoota** [comment]
Seems odd that files from `aarch64-linux-gnu` are included on Mac OS.
What does `llvm-config --host-target` say?

**Comment by miketheman** [comment]
```
$ llvm-config --host-target
x86_64-apple-darwin16.6.0
```

**Comment by RX14** [comment]
You can't use `bin/crystal docs` to build the docs, use `make doc`.

**Comment by miketheman** [comment]
Then there is another bug here, since the crystal command returns an option
of docs, making the user experience fail.

**Comment by RX14** [comment]
Just because the compiler presents the option of "build" doesn't means it's always going to work. But I see your point. However, this is very unlikely to be a problem outside the stdlib, so hardly worth the effort. Perhaps we could find a way to duplicate the error in [`src/compiler.crystal.cr`](https://github.com/crystal-lang/crystal/blob/890ab45bfe171f4b279d5f1607fdb14fb8026d99/src/compiler/crystal.cr#L4).

**Comment by miketheman** [comment]
@RX14 While that's true, the interface presented to the user is what we expect a user to use.

`crystal build x.cr` is what we expect a user to run.

I believe that anything in the output of `crystal --help` is meant to be user-facing, and invoked with `crystal <command>`.

If that intent is incorrect, then we should be discussing the behavior of command line utilities as a larger concept. :)
