### ISSUE TITLE
Feature: Allow redefining main with a different name exposed in Crystal

### ISSUE THREAD

**Issue by Fryguy** [crystal-lang/crystal#4793]
I'm writing a binding to [Allegro](http://liballeg.org/), and running into a crash.  I've created a slim down reproducible script:

```crystal
@[Link("allegro")]
lib LibAllegro
  fun al_run_main(argc : LibC::Int, argv : LibC::Char**, user_main : (LibC::Int, LibC::Char** -> LibC::Int)) : LibC::Int
end

module CrystalAllegro
  @@main : Proc(Nil)?

  def self.run_main(&@@main)
    LibAllegro.al_run_main(0, nil, ->run_main_callback)
  end

  private def self.run_main_callback(_argc : LibC::Int, _argv : LibC::Char**) : LibC::Int
    @@main.not_nil!.call
    0
  rescue ex
    STDERR.puts ex.inspect_with_backtrace
    1
  end
end

module Example
  def self.main
    5000.times { |i| puts i }
  end
end

CrystalAllegro.run_main { Example.main }
```

The result is one of the following

```
...
892
893
[0x10d4624eb] *CallStack::print_backtrace:Int32 +107
[0x10d44de8c] __crystal_sigfault_handler +60
[0x7fffa0d1eb3a] _sigtramp +26
[0x10d46633c] *Fiber::switch_stacks<Pointer(Pointer(Void)), Pointer(Pointer(Void))>:Nil +12
```
```
# Same as above but with the extra line about signal 11
...
1132
1133
Invalid memory access (signal 11) at address 0x28
[0x10978b4eb] *CallStack::print_backtrace:Int32 +107
[0x109776e8c] __crystal_sigfault_handler +60
[0x7fffa0d1eb3a] _sigtramp +26
[0x10978f33c] *Fiber::switch_stacks<Pointer(Pointer(Void)), Pointer(Pointer(Void))>:Nil +12
```
```
...
601
602
# and then it just stops...nothing else
```
```
# If I use a slightly more complicated main function (although it doesn't seem to happen with this particular example)
Collecting from unknown thread
Program received and didn't handle signal IOT (6)
```

Some notes:
- Crystal 0.23.1 (2017-07-13) LLVM 4.0.1
- macOS Sierra 10.12.6
- The numbers above seem random.  It usually fails in the 500-1200 range.
- Here's reference information on the `al_run_main` method: [[source]](https://github.com/liballeg/allegro5/blob/8d8a6130d0dc7fd5b7b8750137701e31511808b5/src/allegro.c#L36-L43) [[details]](https://github.com/liballeg/allegro5/blob/8d8a6130d0dc7fd5b7b8750137701e31511808b5/docs/src/refman/misc.txt#L14-L23) [[docs]](http://liballeg.org/a5docs/trunk/getting_started.html#the-main-function).  Allegro requires that you pass your "main" function to theirs as a callback.
- What's really strange is that I have done much more complicated main functions in other examples [[1]](https://github.com/Fryguy/crystal_allegro/blob/master/examples/ex_bitmap.cr) [[2]](https://github.com/Fryguy/crystal_allegro/blob/master/examples/ex_bitmap_flip.cr), and they all work fine.  I was trying to create [this example](https://github.com/Fryguy/crystal_allegro/commit/135db3d870986389dd7a544829583ffff0396e24), and have distilled the problem to the script above.

I'm kind of stuck at this point, and not really sure what else to look for.

**Comment by lbguilherme** [comment]
Looks like Allegro might invoke this callback in another thread. Crystal's runtime is not thread safe right now, specially Fiber switches (using any IO might cause a Fiber switch)

**Comment by ysbaddaden** [comment]
Maybe the Crystal main (that will initialize crystal land, like constants, global variables, event loop, ...) should run *later*, that is from the Allegro main callback, so Crystal won't be initialized in the main thread, but the thread that Allegro created —Crystal will consider it as its main thread.

Even if Crystal is made thread safe, running Crystal code from an arbitrary thread (unknown to Crystal) may still be problematic.

You'll may have to replace the main fun to init Allegro, set the callback, and call another main, main that will init Crystal, and run your application. See `src/main.cr`.

**Comment by Fryguy** [comment]
Yeah, I was thinking something similar, so I'll give that a shot and see how it goes.

I'm still surprised that other examples work fine with this current setup, but this seemingly trivial one doesn't work.

**Comment by RX14** [comment]
@Fryguy none of the other examples seem to do IO, and this segfault seems to come from `Fiber#switch_stacks` so it's likely that the other examples never try and reschedule.

**Comment by Fryguy** [comment]
@RX14 I had thought IO might be affecting it as well, but I've injected puts/print statements into the other examples, even in the tighter loops, and those examples don't crash at all.  Also, note that the original code from which I distilled the sample doesn't have puts/print ([it fails around here](https://github.com/Fryguy/crystal_allegro/commit/135db3d870986389dd7a544829583ffff0396e24?diff=unified#diff-5cac3b83639b37b8000e520252264f36R72)), however that code *does* do some unsafe pointer manipulations.  When I was trying to distill it down, I found the pointers weren't necessary if I keep the puts in there.  Does unsafe code also cause fiber switches?

**Comment by Fryguy** [comment]
@ysbaddaden The idea worked!

```crystal
@[Link("allegro")]
lib LibAllegro
  fun al_run_main(argc : LibC::Int, argv : LibC::Char**, user_main : (LibC::Int, LibC::Char** -> LibC::Int)) : LibC::Int
end

module CrystalAllegro
  class_property! user_main : Proc(Nil)?
end

fun _alternate_main(argc : Int32, argv : UInt8**) : Int32
  ex = nil
  status = begin
    GC.init
    LibCrystalMain.__crystal_main(argc, argv)
    CrystalAllegro.user_main.call
    0
  rescue e
    ex = e
    1
  end

  AtExitHandlers.run status
  ex.inspect_with_backtrace STDERR if ex
  STDOUT.flush
  STDERR.flush
  status
end

fun main(argc : Int32, argv : UInt8**) : Int32
  LibAllegro.al_run_main(argc, argv, ->_alternate_main)
end

module Example
  def self.main
    5000.times { |i| puts i }
  end
end

CrystalAllegro.user_main = ->Example.main
```

I also jammed this into the full example that caused this problem in the first place, and it worked great!

One downside to the above is that I had to copy-paste almost the entirety of the `redefine_main` macro because the definition names it `main` [here](https://github.com/crystal-lang/crystal/blob/b5dd948dfb74e883e64156a121f3f1d871cd2c3e/src/main.cr#L8).  I'm considering making a PR to extract the definition to a standalone macro, which can be used independently.

**Comment by Fryguy** [comment]
Opened #4798 to modify redefine_main so one can avoid the `main =` alias.

**Comment by Fryguy** [comment]
With #4798, the working solution simplifies to the following

```crystal
@[Link("allegro")]
lib LibAllegro
  fun al_run_main(argc : LibC::Int, argv : LibC::Char**, user_main : (LibC::Int, LibC::Char** -> LibC::Int)) : LibC::Int
end

redefine_main(crystal_main, crystal_main) do |main|
  {{main}}
end

fun main(argc : Int32, argv : UInt8**) : Int32
  LibAllegro.al_run_main(argc, argv, ->crystal_main)
end

module Example
  def self.main
    5000.times { |i| puts i }
  end
end

Example.main
```

**Comment by ysbaddaden** [comment]
The problem is Allegro running this callback from another thread than the main thread. Other examples probably keep running on the main thread.
