### ISSUE TITLE
Money raised on Bountysource

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang/crystal#4794]
Hi Crystal community! :smile: 

This question is mainly for @mgarciaisaia, @waj, @bcardiff, @mverzilli and other core developers.

Why on crystal repo bountysource badge only shows $ 7879 raised?

![Bountysource](https://api.bountysource.com/badge/team?team_id=89730&style=raised)

But, in bountysource Supporters tab, exists people donating since 2015, I did my math and got $ 18,250.

```
2000 + 500 + 1725 + 975 + ... + 24 + 22 + 14 + 11 + 10 + 9 + 8 + 6 = 18250
```

I didn't include Anonymous contributor with 12,000 donated, (Who would be the awesome Anon person :smirk:)

I know Bountysouce has a fee, and core developers works hard to become Crystal 1.0 stable. But [We want](https://github.com/crystal-lang/crystal/issues/4757#issuecomment-318843692) to know who is getting paid or Perhaps a better administration of donations. How are donation used?, I give some ideas:

### July month, by example

```
$   500.00 - Hosting server
$    80.00 - Domain crystal-lang.org
$    62.00 - Github services
$   100.00 - Bountysource fee
$ 1 502.00 - Paid to core developers
--------------------------------------------
$ 2 242.00 - Total
```

Maybe a montly issue or blog post talking about donations. :moneybag: 

Thanks for create Crystal :stuck_out_tongue_winking_eye:

**Comment by faustinoaq** [comment]
Maybe somebody with financial or administration knowledge can manage this :sweat_smile:

**Comment by ysbaddaden** [comment]
Same: mailing list or email discussion, not bugtrack.

**Comment by faustinoaq** [comment]
@ysbaddaden my bad,  Sometimes I feel more confortable writing on Github issues :stuck_out_tongue_winking_eye:, I will repost on Google forum :+1:
