### ISSUE TITLE
Professional Consulting for companies using Crystal.

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang/crystal#4795]
Hi, I'm a Crystal enthusiast.

I will want to recommend Crystal 1.0 to some companies but I ask me if they would need dedicated support.

Then, I read some [Elixir stories](http://blog.plataformatec.com.br/2015/06/companies-using-elixir-in-production/) and I thought, Could Manas offer professional consulting for Crystal 1.0? 

I can see Manas already has a nav entry for Crystal:

![screenshot_20170805_095554](https://user-images.githubusercontent.com/3067335/28996340-4a0587e8-79c4-11e7-8d01-c2d98f0e1494.png)

But, I know Manas is for unconventional projects. Perhaps another company around the world or maybe Manas itself could have something like Plataformatec

![screenshot_20170805_095737](https://user-images.githubusercontent.com/3067335/28996357-83dd5e0a-79c4-11e7-825e-5ef9cc7a320d.png)

Other ideas based on [Elixir interviews](http://blog.plataformatec.com.br/tag/elixir-in-production/) can be blog posts about people using Crystal in production. Titles like `"Crystal in production interview: Fulanito de Tal"`

Thanks for create Crystal :stuck_out_tongue_winking_eye:

**Comment by faustinoaq** [comment]
In the future something like `Companies using Crystal in production (teaser)` would be awesome 
:point_right:  [Elixir sample](https://www.youtube.com/watch?v=ls97Fbc4z3A)

**Comment by matiasgarciaisaia** [comment]
Hey @faustinoaq, thanks for the tips (here, and a couple other issues)! :)

We have a nice & shiny Crystal page for our website designed, but still haven't implemented it.

We're working on making a couple of nice things happen. We'll let you know soon-ish - and it'll be _niiiice_.

Just in case - we **do** offer Crystal consulting services, if anyone's wondering. We just haven't published a page stating it, yet - but if anyone's interested, drop a line to us and let's talk 👍

Thanks for the heads up!

**Comment by ysbaddaden** [comment]
This discussion would fit better in the mailing list than the compiler/stdlib bugtrack.

**Comment by faustinoaq** [comment]
@ysbaddaden Ok :sweat_smile: , my bad,  I will repost on Google forum :+1:
