### ISSUE TITLE
Update Vagrantfile to support latest FreeBSD release (11.1)

### ISSUE THREAD

**Issue by tosmi** [crystal-lang/crystal#4802]
The current Vagrantfile uses FreeBSD 10.2 and has a number of problems

- the FreeBSD base box does not set base_mac so you have to run vagrant up twice
- the package list is outdated
- the shell for vagrant is set to csh, FreeBSD comes with /bin/sh which avoids some warnings
- folder sharing is based on NFS, IMHO this is not necessary for just building crystal. For example I'm not running NFSD on my workstation and starting one just for building crystal is overkill. I would propose just cloning the the upstream crystal repository to the homedir of the vagrant user.

I'm going to use the updated box for creating a FreeBSD port/package for crystal

I'm working on a PR for fixing these issues, just let me know if there is a chance of getting this merged.

thanks

**Comment by straight-shoota** [comment]
It doesn't seem the Vagrantfile is used at all anymore.
