### ISSUE TITLE
Dir.entries() returns both "." and ".." in its results

### ISSUE THREAD

**Issue by docelic** [crystal-lang/crystal#4807]
Calling Dir.entries() returns both "." and ".." in the result set, and there is no sort order defined.

This essentially makes one have to call:

```
result= Dir.entries( "/some/dir")
result.delete "."
result.delete ".."
```
Before the results become usable.

Is this intended behavior and/or there's room for improvement?

**Comment by MakeNowJust** [comment]
`Dir.entries` uses C's `readdir` function internally, and `readdir` yields both "."  and ".." also, so `Dir.entries` result contains them. In addition, this behavior is same as Ruby's 'Dir.entries'. I think this is intended behavior.

**Comment by straight-shoota** [comment]
Ruby has also [`Dir.children`](https://ruby-doc.org/core-2.4.1/Dir.html#method-c-children) for exactly this purpose. It would make sense to have this in Crystal too.
