### ISSUE TITLE
Multi-line ternary syntax?

### ISSUE THREAD

**Issue by Qwerp-Derp** [crystal-lang/crystal#4810]
I know that changes to the syntax is frowned upon at this stage of Crystal, but is it possible to have multi-line ternary operators?

I have a condition here:

```crystal
@locked.includes?({tile_x, tile_y}) ? @locked.reject! { |a| a == {tile_x, tile_y} } : @locked.push({tile_x, tile_y})
```

It looks unwieldy, but if I change it into an `if/else` statement:

```crystal
if @locked.includes?({tile_x, tile_y})
  @locked.reject! { |a| a == {tile_x, tile_y} }
else
  @locked.push({tile_x, tile_y})
end
```

It seems unnecessarily "bulky".

What I would prefer is to do something like this:

```crystal
@locked.includes?({tile_x, tile_y})
  ? @locked.reject! { |a| a == {tile_x, tile_y} }
  : @locked.push({tile_x, tile_y})
```

I'm not sure if there's a valid usecase for this syntax, though.

**Comment by david50407** [comment]
You can use like this: 

```
condition ?
  true : 
  false
```

example https://play.crystal-lang.org/#/r/2hlu

**Comment by RX14** [comment]
Please just use the if statement. It's so much more readable.

**Comment by ysbaddaden** [comment]
Closing, as @RX14 said, an if else statement is the most readable version of the examples.

**Comment by Sija** [comment]
@Qwerp-Derp For the time being you can use `\` symbol, like:

```cr
true \
  ? pp({ i_am: :weasel })
  : pp({ i_am: :baboon })
```
