### ISSUE TITLE
Behavior of obj.prop!= value

### ISSUE THREAD

**Issue by docelic** [crystal-lang/crystal#4815]
I had the following code:

```
if( obj.prop!= 1)
```

This resulted in the error "undefined method 'prop!=' for ObjClass".

The error happened because there is no space between "prop" and "!=".
It appears that without a space inserted, Crystal parses the syntax as invoking the method "prop!=" on object "obj".

I am wondering if there was a purpose behind it? One would generally expect the != to be a negation of ==, not to be treated as part of method name.

In Ruby, "obj.prop!= value" is parsed as "obj.prop not-equal value" as expected.

Example on Play: https://play.crystal-lang.org/#/r/2i55

**Comment by Fryguy** [comment]
Interesting...in Ruby you just can't create a `prop!=` method.

```
SyntaxError: unexpected !=, expecting ';' or '\n'
  def prop!=(val)
```

**Comment by oprypin** [comment]
Heh, this actually works

```crystal
class C
  def f!=(x)
    x+1
  end
end

p(C.new.f!=5)
```

Clearly a parser bug, which probably checks like "if ! is at the end it's OK; if = is at the end it's OK" but it happens to let both through

**Comment by oprypin** [comment]
Well, this is not as simple as I made it seem
`def f!=` is parsed as `def` `SPACE` `f!` `=`
https://carc.in/#/r/2jav
And the lexer can't afford to be a backtracking one - the `=` would be modifying the outcome of the previous token in the case of `obj.prop!= 1`.
So it might have to be a hack in the parser? If `=` follows an identifier with `!`, abort operation?

BTW this also works
```crystal
class C
  def f?=(x)
    x+1
  end
end

p(C.new.f? = 5)
```

**Comment by RX14** [comment]
We don't need to backtrack, we just need to be able to peek the next token. And we can do that.

**Comment by oprypin** [comment]
I will make a pull request
