### ISSUE TITLE
mix class and instance variables in module

### ISSUE THREAD

**Issue by TPei** [crystal-lang/crystal#4820]
Hey, I was just wondering if it is possible to mix class and instance variables in a module like in ruby, by using the `self.included(base)` hook or something similar. Is there any construct that supports this or is anything planned for the future?

To clarify:
In ruby it is possible to define a module (MyFirstModule) and then in another module (MySecondModule) do
```ruby
def self.included(base)
  base.extend(MyFirstModule)
end
```

This then causes the methods in `MyFirstModule` to become class methods in `MySecondModule`, thus enabling me to add both class and instance methods when a user includes MySecondModule

**Comment by straight-shoota** [comment]
This can be accomplished with the `inherited` macro hook: [reference](https://crystal-lang.org/docs/syntax_and_semantics/macros/hooks.html)

```crystal
macro included
  extend MyFirstModule
end
```

**Comment by ysbaddaden** [comment]
Closing: this is a question suited for stackoverflow, and it was answered.

**Comment by faustinoaq** [comment]
Hi 😄 I didn't find it on stackoverflow, so I published it 👉 https://stackoverflow.com/questions/45620355/mix-class-and-instance-variables-in-module
