### ISSUE TITLE
Missing doc for Channel

### ISSUE THREAD

**Issue by Escapingbug** [crystal-lang/crystal#4822]
Thanks for this great project. I really love this language, and try to use it everywhere as much as I can. :)

But, I found there is doc missing in std, especially something about Channel. And I'm really confused about usage of this object.

Hope you guys can fix this soon. :)

**Comment by Escapingbug** [comment]
Thanks for that. But what I really need is the doc about select, and sadly, I can't find anything about that. :(  

In fact, I'm trying to do non-blocking interact between threads(coroutines or fibers), in go, I can just use select to get away with not useful message sent by channels. Since there is a "select" method in `Channel` API, I wonder if I can do the same?

**Comment by bew** [comment]
`Channel.select` seems to be something that shouldn't be used directly: I think you're looking for the `select` keyword, that allows you to wait for any channel.

The only documentation is the PR that introduced it (https://github.com/crystal-lang/crystal/pull/3130) and the sample (see below, taken from: [samples/channel_select.cr](https://github.com/crystal-lang/crystal/blob/4f71e6ebff111b3c17dba90d63a9ac571df973ba/samples/channel_select.cr))

```cr
def generator(n : T) forall T
  channel = Channel(T).new
  spawn do
    loop do
      sleep n
      channel.send n
    end
  end
  channel
end

ch1 = generator(1)
ch2 = generator(1.5)
ch3 = generator(5)

loop do
  select
  when int = ch1.receive
    puts "Int: #{int}"
  when float = ch2.receive
    puts "Float: #{float}"
  when ch3.receive
    break
  end
end
```

**Comment by Escapingbug** [comment]
Thanks a lot. That should be what I'm searching for. Still hope you can fix the doc problem soon. :)

**Comment by asterite** [comment]
There's a lot of missing docs. The solution here is to send a PR with the docs. I don't think we'd like to track an issue for each missing piece of doc.
