### ISSUE TITLE
Tuple: bug when calling a function that takes another tuple in parameter without parentheses 

### ISSUE THREAD

**Issue by Nephos** [crystal-lang/crystal#4826]
Hello,

I found out that I cannot write `{...}.method {...}`, it is required to write `{...}.method({...})`. I think it's a bug right ?

Two examples:
```crystal
{:id, :author}.zip({1, "me"})
{:id, :author}.zip {1, "me"}
```

produces ( https://play.crystal-lang.org/#/r/2ipu ):

    Syntax error in eval:3: unexpected token: ,

and

```crystal
{:id}.zip({ 1 })
{:id}.zip { 1 }
```

produces ( https://play.crystal-lang.org/#/r/2ipv ):

    Error in line 3: wrong number of arguments for 'Tuple(Symbol)#zip' (given 0, expected 1)
    Overloads are:
     - Indexable(T)#zip(other : Indexable, &block)
     - Indexable(T)#zip(other : Indexable(U))

**Comment by RX14** [comment]
This is correct behaviour, there's no way to disambiguate between a tuple and a block here.

**Comment by Nephos** [comment]
Ok, that makes sense ^^.
Thanks!
