### ISSUE TITLE
Cannot compile the compiler on Debian sid (using gcc)

### ISSUE THREAD

**Issue by vegai** [crystal-lang/crystal#4829]
Debian sid
crystal-0.23.1 from the deb package in dist.crystal-lang.org

```
vegai@host ~/git/pub/crystal ±bigdecimal⚡ » make
Using /usr/bin/llvm-config-4.0 [version=4.0.1]
CRYSTAL_CONFIG_PATH=`pwd`/src ./bin/crystal build  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
/usr/bin/ld: /opt/crystal/embedded/lib/../lib/libgc.a(os_dep.o): undefined reference to symbol '_end'
//usr/lib/x86_64-linux-gnu/libffi.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/vegai/git/pub/crystal/.build/crystal'  -rdynamic  /home/vegai/git/pub/crystal/src/llvm/ext/llvm_ext.o `/usr/bin/llvm-config-4.0 --libs --system-libs --ldflags 2> /dev/null` -lstdc++ -lpcre -lm -lgc -lpthread /home/vegai/git/pub/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
Makefile:116: recipe for target '.build/crystal' failed
make: *** [.build/crystal] Error 1
```

Bit similar to issue #4825 

I think I saw the same issue on a recent Fedora 26 too.

**Comment by vegai** [comment]
https://jenkins.crystal-lang.org/job/crystal-nightly/52/console -- the last non-stuck Jenkins build has the same error.

**Comment by RX14** [comment]
Yeah this is a weird problem and I still don't have a clue what causes it.

**Comment by vegai** [comment]
I found at least one way to work around this: by using clang-4.0 instead of gcc.

**Comment by vegai** [comment]
Not sure if this has to be even thought of as a workaround. It might be easier to support just clang when building the compiler and forget about gcc? That's what Mac OS uses too by default.

**Comment by packetzero** [comment]
FYI, this affects the [crystal-lang docker image](https://hub.docker.com/r/crystallang/crystal/).  I just tried the crystal-lang docker image to run a simple app and ran into this same problem.  The Dockerfile is based on Ubuntu 16.04 (xenial).
```
/usr/bin/ld: /opt/crystal/embedded/lib/../lib/libgc.a(os_dep.o): undefined reference to symbol '_end'
//usr/lib/x86_64-linux-gnu/libyajl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by drhuffman12** [comment]
Maybe someone should cancel out the stuck Jenkins jobs on https://jenkins.crystal-lang.org/job/crystal-nightly/ and then restart the latest (or some newer build)?

**Comment by shevegen** [comment]
This is strange ... why does clang work there but gcc does not?

vegal wrote:

> Not sure if this has to be even thought of as a workaround. It might be easier to support
> just clang when building the compiler and forget about gcc? That's what Mac OS uses
> too by default.

But GCC works very well on my linux system here; llvm+clang work too. I even got crystal to work on win10 via a self-compiled llvm. GCC should work too ...

**Comment by vegai** [comment]
@shevegen Yeah, I agree. I'm also able to use gcc just fine on NixOS. It's specific to some combination of the configurations rather than GCC itself, I suppose.

**Comment by drhuffman12** [comment]
I was wanting to build Crystal from source in my host OS (Linux Mint) but was having some issues, so I figured I _should_ be able to use the Dockerfile.

However, it is set to build Crystal w/ LLVM 3.5 and is erroring out. The error log is longer than my shell history length (I can change that it if is helpful.) The tail of it is:

```
/opt/llvm-3.5.0-1/include/llvm/Support/CBindingWrapping.h:20:14: note:   no known conversion for argument 1 from 'LLVMOpaqueMetadata**' to 'LLVMUseRef {aka LLVMOpaqueUse*}'
   inline ty *unwrap(ref P) {                            \
              ^
/opt/llvm-3.5.0-1/include/llvm/IR/Use.h:169:1: note: in expansion of macro 'DEFINE_SIMPLE_CONVERSION_FUNCTIONS'
 DEFINE_SIMPLE_CONVERSION_FUNCTIONS(Use, LLVMUseRef)
 ^
Makefile:119: recipe for target 'src/llvm/ext/llvm_ext.o' failed
make: *** [src/llvm/ext/llvm_ext.o] Error 1
The command '/bin/sh -c make clean crystal release=1' returned a non-zero code: 2
```

Since we're leaving 3.5 behind, in case anyone is interested, I was able to get the Dockerfile to work for LLVM 4.0 and figured it might be handy to have this parameterized and wrapped w/ a `docker-compose.yml`.

If interested, I can make a pull request from my branch I have at https://github.com/drhuffman12/crystal/tree/drhuffman12/build_dockerfile_llvm. It uses an environment variable called `LLVM_TARGET_VER`, which can be renamed it desired.

It worked fine for `3.8`, `3.9`, `4.0` for `LLVM_TARGET_VER`. I get something like:


```
root@5d256b74287a:/opt/crystal-head# .build/crystal -v
Crystal HEAD (2017-09-20)

LLVM: 4.0.0
Default target: x86_64-pc-linux-gnu
```

However, I'll have to dig some more to get it to work for `5.0`; I'm getting the following errors during the docker build process:

```
Reading state information...
E: Unable to locate package llvm-5.0
E: Couldn't find any package by glob 'llvm-5.0'
E: Couldn't find any package by regex 'llvm-5.0'
E: Unable to locate package llvm-5.0-dev
E: Couldn't find any package by glob 'llvm-5.0-dev'
E: Couldn't find any package by regex 'llvm-5.0-dev'
E: Unable to locate package clang-5.0
E: Couldn't find any package by glob 'clang-5.0'
E: Couldn't find any package by regex 'clang-5.0'
ERROR: Service 'crystal_lang' failed to build: The command '/bin/sh -c wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key| apt-key add - &&     apt-get update &&     apt-get install -y --no-install-recommends llvm-${LLVM_TARGET_VER} llvm-${LLVM_TARGET_VER}-dev clang-${LLVM_TARGET_VER} &&     apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 100
```

**Comment by akzhan** [comment]
@drhuffman12 unrelated to your problem, please don't use LLVM < 3.8 to build Crystal (LLVM was buggy).

I prefer to use latest LLVM (5.0) with master, or LLVM 4.x for 0.23.x.

**Comment by rdp** [comment]
Do you still get this?

**Comment by j8r** [comment]
This is old, this issue can be closed. Feel free to reopen if you encounter an issue again with a recent version of Crystal.
