### ISSUE TITLE
Instance variable incorrectly assumed as nilable in overloaded initialisers

### ISSUE THREAD

**Issue by meew0** [crystal-lang/crystal#4830]
I'm not sure why exactly this happens, but in the following code the `@foo` instance variable is incorrectly assumed to be nilable (thanks @RX14 for helping with reducing):

```cr
struct Container
  getter foo : String
  getter bar : String
  
  def initialize(other : Container, override_foo : String)
    initialize(other)
    @foo = override_foo
  end

  def initialize(other : Container)
    @foo = other.foo
    @bar = other.bar
  end
  
  def initialize(@foo : String, @bar : String)
  end
end

# Works
container = Container.new("foo", "bar")
p container

# Works
copy1 = Container.new(container)
p copy1

# Doesn't work
copy2 = Container.new(container, "foo2")
p copy2
```

```
Error in line 28: instantiating 'Container:Class#new(Container, String)'

instance variable '@foo' of Container must be String, not Nil

Error: instance variable '@foo' was used before it was initialized in one of the 'initialize' methods, rendering it nilable
```

(https://carc.in/#/r/2j6r)

A workaround is to set `@foo` in the first initialiser before calling the overloaded one:

```cr
  def initialize(other : Container, override_foo : String)
    @foo = other.foo
    initialize(other)
    @foo = override_foo
  end
```

(https://carc.in/#/r/2j72)

I reproduced this on 0.23.1 and on master from yesterday or so (but it doesn't seem like there were any relevant commits in the meantime)

**Comment by RX14** [comment]
Looks to me (i haven't checked in any way, I may well be wrong) like the compiler doesn't differentiate on the reciever when checking for ivar accesses. The call to `other.foo` is recognised as an access to `@foo`, which is is, but it's not `self.@foo`, it's `other.@foo`. I'm not sure how easy this is to fix though.

**Comment by bew** [comment]
@RX14 seems to be something else:
```cr
class C
  getter foo : String

  def initialize(other : self)
    @foo = other.foo
  end
  
  def initialize(@foo)
  end
end

other = C.new "hello"
pp C.new other # => #<C:0x560bda368ee0 @foo="hello">
```
https://carc.in/#/r/2j7e

**Comment by bew** [comment]
@RX14 looks like you're right: I changed the line `@foo = other.foo` to `@foo = "foo"` and the error's gone.
