### ISSUE TITLE
Installation on Centos provides no crystal executable

### ISSUE THREAD

**Issue by andy-twosticks** [crystal-lang/crystal#4836]
Centos 7

I've followed the instructions from the installation page, and successfully installed Crystal.  The problem is that this does not get me the crystal executable on my $PATH.

Using `repoquery -l crystal` I can see that everything has installed into /opt/crystal and typing `/opt/crystal/bin/crystal -v` appears to show that the installation went okay. *Presumably* I can just add /opt/crystal/bin to my $PATH and carry on.  (If I get any further problems I will comment the issue.)

But clearly something is not quite right with the .rpm package. I don't have this problem on Debian.

**Comment by ysbaddaden** [comment]
The package didn't create a `/usr/bin/crystal` link to `/opt/crystal/bin/crystal` as it does in Debian. This is an [omnibus](https://github.com/crystal-lang/omnibus-crystal) issue.

**Comment by andy-twosticks** [comment]
Good to know that that's all that is wrong. Thanks.

**Comment by matiasgarciaisaia** [comment]
Sorry about the inconvenience!

I was about to open the issue on crystal-lang/omnibus-crystal, but couldn't repro it - installing via yum on Centos7 installs the symlink on `/usr/bin/crystal`.

@andy-twosticks if you can provide any more info about this, please do so by [opening an issue on that other repo](https://github.com/crystal-lang/omnibus-crystal/issues/new) :)
