### ISSUE TITLE
Power pc cross compilation error.

### ISSUE THREAD

**Issue by fapfip** [crystal-lang/crystal#4842]
When I'm trying crosscompile very simple format for power pc then I got this error message. Message from compiler says it is compiler bug...  Can I do something about this? Thanks for advices!

my setup: Ubuntu 16.04.3 LTS, Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1

Message from compilation:

crystal build hello.cr --cross-compile --target "ppc-unknown-linux-gnu"
Unsupported arch for target triple: ppc-unknown-linux-gnu
0x5bb9fe: ??? at ??
0xb4f851: ??? at ??
0xbabff2: ??? at ??
0xb9cc1e: ??? at ??
0x102b08e: ??? at ??
0x60b056: ??? at ??
0x5e1dac: main at ??
0x7f6b3980d830: __libc_start_main at ??
0x5bb20d: ??? at ??

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues

**Comment by straight-shoota** [comment]
Power PC is currently not supported as a target architecture, as the first line in the error message points out.

But the stacktrace and note about a compiler bug should probably not be there. It's not a but it's just a missing feature.

**Comment by fapfip** [comment]
Thank you for help :)
