### ISSUE TITLE
Cannot overload methods with same amount of required named arguments

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#4844]
I think this is self-explanatory:
```
in lib/tele/src/tele/client.cr:79: no argument named 'file_path'
Matches are:
 - Tele::Client#download_file(file : Types::File)
 - Tele::Client#download_file(*, file_path : String)
 - Tele::Client#download_file(*, file_id : String) (trying this one)

      download_file(file_path: file.file_path)
      ^~~~~~~~~~~~~
```
Is this an expected behaviour?

**Comment by straight-shoota** [comment]
Could you please provide a reproducable example? It seems like there is some missing context.
This code compiles fine:
```crystal
class Client
  def download_file(file : Bool)
  end
  def download_file(*, file_path : String)
  end
  def download_file(*, file_id : String)
  end
end

Client.new.download_file(file_path: "file_path")
```
[carc.in](https://carc.in/#/r/2k2p)

**Comment by RX14** [comment]
Perhaps `file.file_path` is the wrong type, and the error messages have gone wonky? I've had weird error messages around calls when types don't match before.

**Comment by vladfaust** [comment]
Magically resolved the issue, think it was my bad. Closing for now.
