### ISSUE TITLE
Windows and platform specific class Dir (as an example)

### ISSUE THREAD

**Issue by txe** [crystal-lang/crystal#4848]
Currently, I have dir.cr(which just requires relevant file), dir.posix.cr and dir.windows.cr in my branch. I took https://github.com/crystal-lang/crystal/pull/4770 as an example and, apparently, I just need to move platform specific things into its own namespace, but it's not clear for me how to do it for platform specific **instance variables**. For example, if there are
```
class Dir
    @dir : LibC::Dir*
    def initialize(@path)
        @dir = LibC.opendir(...)
    end
end
``` 

```
class Dir
    @handle : LibC::Handle
    def initialize(@path)
        @handle = LibC::INVALID_HANDLE_VALUE
    end
end
```
so how things are going to look? Can someone explain it to me?

**Comment by RX14** [comment]
The way I implemented it when I abstracted `IO::FileDescriptor` is likely helpful to you. The commit is [here](https://github.com/crystal-lang/crystal/commit/cb2b80af519ae29688ea321efd27429e56626833). What I did was I extracted the minimum platform-specific functionality to another class, called `Crystal::System::FileHandle` (you should create a `Crystal::System::DirHandle`). Surely though, you say, that's just recreating the `IO::FileDescriptor` class in `Crystal::System` and forwarding all methods? Well, there are two differences between `Crystal::System::FileHandle` and `IO::FileDescriptor`: `IO::FileDescriptor` is buffered, and `Crystal::System::FileHandle` doesn't include any helper methods which don't include platform specifics in themselves. Yes, `IO::FileDescriptor` forwards a lot of it's methods directly to the handle but it does add quite a bit of platform-agnostic functionality.

So, I suggest you create a `Crystal::System::DirHandle` and implement `Dir` in terms of that. You should be able to make `DirHandle` a struct here, so in the end there will actually be pretty much 0 overhead.
