### ISSUE TITLE
Possible removal of GC?

### ISSUE THREAD

**Issue by sumproxy** [crystal-lang/crystal#4865]
As a point for discussion: Do you consider adding the concept of lifetimes to crystal (as in rust) to remove garbage collector from runtime entirely? If the answer is yes (of course I don't expect that) can this be done ergonomically without extra complications to the syntax?

The issue was first raised [here](https://groups.google.com/forum/#!msg/crystal-lang/1jdCm8KbbmU/PrGWAZJiCgAJ).

**Comment by vegai** [comment]
I would think that the issues shouldn't be used a discussion forum.

As for the question, complecting Crystal with Rust concepts is not something I'd like to see. Rust exists already and has good momentum.

**Comment by sumproxy** [comment]
@vegai after some thought I decided that you're probably right. Thanks for sharing your thoughts.

The reason why I created the issue was because I received no feedback in google groups.

**Comment by konovod** [comment]
btw impossibility of GC removal is mentioned in FAQ:
https://github.com/crystal-lang/crystal/wiki/FAQ#language-x-has-feature-y-why-dont-you-have-such-feature

**Comment by sumproxy** [comment]
@konovod will read the FAQ, thank you.
