### ISSUE TITLE
context.response.print doesnt print the output

### ISSUE THREAD

**Issue by codenoid** [crystal-lang/crystal#4881]
Hi, :smile_cat:
```
res.headers.each { |k, v| context.response.headers[k] = v }
context.response.print res.body # doesnt give me output, but when i give a comment to the first line, this line (second line) give me a output
```
my full code : https://github.com/codenoid/lemmehand/blob/master/server.cr 
thanks ^^

**Comment by jpsouzasilva** [comment]
It looks like an exception is being raised before your `context.response.print` method is called, so the page isn't properly rendered at the end when the line before this call is uncommented. This is very basic stuff; you should be able to figure what's going on by debugging the code.

**Comment by codenoid** [comment]
^ why there is a exception ?, I'm basically noob

**Comment by bew** [comment]
Note: I think that this is a 'help-needed' question that should go to StackOverflow, with the `#crystal-lang` tag.

**Comment by asterite** [comment]
You are copying all headers like content encoding or chunked transfer, that's wrong

**Comment by codenoid** [comment]
@asterite So how can I be able to equalize the web header response with the client header response ? 😕

**Comment by akzhan** [comment]
What are you want to do? You got compressed stream that automatically decompressed and send it as without updating of encoding headers.

minimal working example:

```crystal
server = HTTP::Server.new(port.to_i) do |context|
  params = {} of String => String
  context.request.query_params.each do |k, v|
    params[k] = v
  end
  if params.has_key?("get")
    HTTP::Client.get(params["get"]) do |res|
      context.response.content_type = res.content_type.to_s
      context.response.status_code = res.status_code
      res.headers.each do |k, v|
        next if k == "Content-Encoding"
        next if k == "Content-Length"
        context.response.headers[k] = v
      end
      context.response.print res.body_io.gets_to_end
    end
  else
    context.response.content_type = "text/plain"
    context.response.print "you must use GET method,ex.  yourserver.com/?get=http://yoururl.com/"
  end
end
```

**Comment by codenoid** [comment]
nice, thanks @akzhan
