### ISSUE TITLE
Iterate through array and return itself

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#4883]
Origin: https://stackoverflow.com/questions/45870562/iterate-through-array-and-return-itself/45871034#45871034

I think a standard method should exist for this

**Comment by bcardiff** [comment]
In https://github.com/crystal-lang/crystal/pull/3815#issuecomment-269978574 you can find an explanation about why it is preferred to return `nil` instead of `self` for `#each`.

**Comment by vladfaust** [comment]
@bcardiff I don't mind having nil `#each`, my propose is to add another method like `each_and_self`, so one doesn't `tap &.each` every time or even writes his own method.

BTW, now I see that `tap &.each` is short enough :thinking:

**Comment by bcardiff** [comment]
@vladfaust ok, I didn't understand that you were proposing and addition. I agree that `tap &.each` is short enough.

Maybe the actionable here is to add an iteration section in https://github.com/crystal-lang/crystal/wiki/Crystal-for-Rubyists .

**Comment by akzhan** [comment]
I believe that this issue should be closed, `tap` is OK.

**Comment by Fryguy** [comment]
I added a section to Crystal for Rubyists: https://github.com/crystal-lang/crystal/wiki/Crystal-for-Rubyists#each-returns-nil

**Comment by bcardiff** [comment]
thx @Fryguy
