### ISSUE TITLE
Recursive alias, cast

### ISSUE THREAD

**Issue by Nephos** [crystal-lang/crystal#4885]
Hello,

cf: https://github.com/crystal-lang/crystal/issues/3803 , https://github.com/crystal-lang/crystal/issues/2665

Is there a way to cast something using a recursive type ?

```crystal
alias Type = Int32 | Array(Type)
[1].as(Type)
```

Error:

    can't cast Array(Int32) to Type

Note: my aim is no to be able to cast it, it is to have a defined return type (`def XXX : Type`)

**Comment by RX14** [comment]
`[1].map(&.as(Type))`.

**Comment by lbguilherme** [comment]
Actually you should do `[1].map(&.as(Type))` to first go from `Array(Int32)` to `Array(Type)`. Then do `[1].map(&.as(Type)).as(Type)` to get a `Type` on the end. A little bit verbose, but makes sense.

**Comment by Nephos** [comment]
Thank you, I see what you mean, but if the problem was to cast a simple Array, I would not have open an issue. The `[1]` is a simple example, but it should work with any valid Type.
Let me give you a complete example (I should have done that in the first place):

```crystal
alias Type = Int32 | Array(Type)

def foo(a : Type) : Type
  a.as(Type)
end

foo 1
foo [1]
foo [1, [2]]
```

    can't cast Array(Int32) to Type

Of course, you can remove the cast, but the problem becomes `type must be Type, not Array(Int32)`

The context is the following:

"I want to choose some functions to call at runtime. These functions can return several types of objects (its very generic)."

```crystal
def foo
  "foo"
end

def bar
  0xba5
end

runtime = Hash(String, Proc(String | Int32)).new
runtime["foo"] = -> foo
runtime["bar"] = -> bar
```

But foo returns a String and bar a Int32, and they don't match (String | Int32).

So I could just cast the result of my functions.

```crystal
alias Type = Int32 | String | Array(Int32)

def foo
  "foo".as(Type)
end

def bar
  0xba5.as(Type)
end

runtime = Hash(String, Proc(Type)).new
runtime["foo"] = -> foo
runtime["bar"] = -> bar
```

It works also with Generics but if there are recursive generics...

```crystal
alias Type = Int32 | Array(Type)

def foo
  [0xf00].as(Type)
end

def bar
  0xba5.as(Type)
end

runtime = Hash(String, Proc(Type)).new
runtime["foo"] = -> foo
runtime["bar"] = -> bar
```

    can't cast Array(Int32) to Type

**Comment by asterite** [comment]
```crystal
[1] of Type
```

**Comment by Nephos** [comment]
That's nice!
But the return of the function is not always as simple.

```crystal
def foo(param1, param2) : Type
  param1.operate(param2) # well... can't define the type of "operate".
end
```

**Comment by lbguilherme** [comment]
I usually do this with a helper function:

```
alias Type = String | Int32 | Array(Type) | Hash(String, Type)

def cast_to_type(x :  Array) : Type
  return x.map { |e| cast_to_type(e).as(Type) }.as(Type)
end

def cast_to_type(x : Hash)
  h = Hash(String, Type).new
  x.each do |(k, v)|
    h[k] = cast_to_type(v).as(Type)
  end
  h.as(Type)
end

def cast_to_type(x)
  x.as(Type)
end

p cast_to_type(10)
p cast_to_type([10])
p cast_to_type({"hm" => [10, ["", 2, {"a" => "b"}]]})
```

**Comment by Nephos** [comment]
That would work yes! But isn't it expensive to reallocate every Array/Hash just to do a cast ?

**Comment by lbguilherme** [comment]
You have to. Because the memory layout of a `Array(Int32)` is different than `Array(Type)`. The first always store elements of 4 bytes, while the later uses more space. Whatever you do, the whole array must be reallocated to the new format. This is why this process is not automatic, but explicit.

**Comment by Nephos** [comment]
Yes, I should have learned my lessons :) Sometimes I forget that we care about memory in this langage.
Thanks for your time, you teach me something!
