### ISSUE TITLE
Formatter leaves leading space on first line of file

### ISSUE THREAD

**Issue by bew** [crystal-lang/crystal#4896]
The following code, with leading spaces on first line of file remains unchanged after formatter pass:
```cr
    1 # One or more leading space(s)
```

**Comment by sdogruyol** [comment]
Let's ping @MakeNowJust :+1:

**Comment by MakeNowJust** [comment]
I tried this, but I did't reproduce this. I need more information.

**Comment by sdogruyol** [comment]
@bew I also couldn't reproduced this on 0.23.1

**Comment by bew** [comment]
Indeed, I can only reproduce in vim (using vim-crystal's `:CrystalFormat` command). I'll close here, and re-open in the proper repo.
