### ISSUE TITLE
Macros in cases

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#4899]
```crystal
case 42
{% for klass in %w(Int32 String) %}
  when {{klass.id}}
    p "is {{klass}}"
{% end %}
end
```
This doesn't work, although expected: `Error at line 2, column 1: unexpected token: {% (expecting when, else or end)`

**Comment by Sija** [comment]
You're missing `{% begin %} ... {% end %}` blocks.

Also, your code wouldn't work anyway since `p "is {{klass}}"` line should read `p "is {{klass.id}}"` (notice the `.id` part).

See https://play.crystal-lang.org/#/r/2mj8

Please close this issue and be more careful in the future, thanks!

**Comment by asterite** [comment]
https://crystal-lang.org/docs/syntax_and_semantics/macros.html

**Comment by RX14** [comment]
The reason behind this is that a `case` statement is a single AST node. Macros have to return something which the compiler can parse on it's own. Without `{% begin %} ... {% end %}` all the compiler sees is `when Foo; p "is Foo"` which isn't valid crystal without a `case`. The `{% begin %} ... {% end %}` fixes this by expanding the macro to encompass the entire case statement.

**Comment by vladfaust** [comment]
@Sija how does one know about `{% begin %}` and `{% end %}`? It's not mentioned in docs :thinking: 

*Consider `{{klass}}` as inessential typo.*
