### ISSUE TITLE
[Not an issue but simply confirmation that crystal on bash-on-windows works for me as well] Crystal works on windows bash subsystem

### ISSUE THREAD

**Issue by shevegen** [crystal-lang/crystal#4902]
Hello.

I lately noticed:

https://crystal-lang.org/docs/installation/on_bash_on_ubuntu_on_windows.html

I assume that it is a fairly recent addition?

Anyway. About 2 months ago I bought a new laptop and win10 is there, for several reasons. (That investment had to be done either way and I could use linux there; but due to some other reasons, I also have to be able to use windows, e. g. at different work places. At home I use linux exclusively.)

Since then I continued to experiment and am also "partaking", more or less, in the "windows insider builder", which allows for faster updates.

Now to make a long story short, what did I do:

- I started to compile stuff from source on my win10 laptop, after setting up ubuntu (the first one in WSL but now there is opensuse too and another one).

- After having a build-chain that, surprisingly, worked (using the default from ubuntu as base, but lateron replacing it with source-compiled stuff... binutils, make, sed grep etc...) , yesterday I built **LLVM** with shared library support. (I followed mostly the LFS/BLFS instructions from https://crystal-lang.org/docs/installation/on_bash_on_ubuntu_on_windows.html; only difference was that I used the prefix /Programs/Llvm/4.0.1 - other than that, I think I sticked to the BLFS way)

- Today, I downloaded the crystal binary:

This URL specifically:

https://github.com/crystal-lang/crystal/releases/download/0.23.1/crystal-0.23.1-3-linux-x86_64.tar.gz

Extracted it, moved it about a bit, then looked if the hell world and the class example from the
official docu works. And it does!

I had to use "crystal build foo.cr" to get the executable, which also ran.

Of course this was not on a "windows" host machine per se but rather within the bash-on-windows subsystem which is ... mostly ubuntu. At the least in my case.

But the important thing, why I wanted to keep you guys informed, is that it:

a) indeed works, just as written down at https://crystal-lang.org/docs/installation/on_bash_on_ubuntu_on_windows.html - while it says it is highly experimental, it works quite fine, at the least for basic stuff (I haven't yet tested anything more complicated)

and even more importantly,

b) it worked for me without the "apt-get" way, so compiling from source works too!

Feel free to expand the docu if you want to, or not which is also fine - I only wanted to notify
you. And close this whenever you feel like it - though perhaps one or another one could
also give this a try too; I haven't yet tested to compile a new crystal with crystal yet, for
instance; and I have not yet tested a self-compiled gcc yet either (compiling on bash-on-windows
unfortunately takes quite a bit longer than on linux, from my experience - I assume it may be
because there may have to be some indirect file calls... such as whenever you modify files
and such, which I guess is more costly than natively on linux) 

This is of course not full "crystal on windows", but for the time being, I think it may suffice
for a few people who also use windows a lot, for one reason or the other but want to use
crystal as well. I am sure that eventually native windows support will be 100%.

 Either way, thanks for reading!

**Comment by RX14** [comment]
I think this post would have been better on the mailing list than on the issue tracker...
