### ISSUE TITLE
can't use A(T) as generic type argument yet, use a more specific type

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#4913]
Sorry for my "silly-from-side" questions, but

https://play.crystal-lang.org/#/r/2neg

```crystal
abstract class A(T)
  def foo
    puts T.to_s
  end
end

class B < A(Int32)
end

a = [] of A
a << B.new
a.each { |e| p e.foo }

# => Error in line 10: can't use A(T) as generic type argument yet, use a more specific type
```

It's weird, because `A` is abstract. Any workarounds?

**Comment by hugoabonizio** [comment]
You are not defining generic type on line 10:

```crystal
abstract class A(T)
  def foo
    puts T.to_s
  end
end

class B < A(Int32)
end

a = [] of A(Int32) # <<<
a << B.new
a.each { |e| p e.foo }
```

https://carc.in/#/r/2nf6

**Comment by vladfaust** [comment]
@hugoabonizio the whole point of `Generics` is that there might be `class C < A(String)`. There might be any amount of other classes.

**Comment by asterite** [comment]
@vladfaust But in `[] of A`, `T` is not specified. It could be anything. And that's not supported by the compiler... basically `T` would be `Object` here, but that's not supported...

**Comment by vladfaust** [comment]
@asterite will supporting `Object` be implemented some day?

**Comment by asterite** [comment]
https://www.youtube.com/watch?v=EkPy18xW1j8
