### ISSUE TITLE
Shouldn't IO.read_line return "String" rather than "String?"

### ISSUE THREAD

**Issue by kyku** [crystal-lang/crystal#4920]
The function either returns string read from input or throws, so most probably the result cannot contain nil.

Current implementation from Crystal 0.23.1:
```
  def read_line(*args, **options) : String?
    gets(*args, **options) || raise EOFError.new
  end

```

**Comment by bararchy** [comment]
Seems so, as it can only be `String` or `raise`, as gets returns a `String?`
