### ISSUE TITLE
Compiler fails to find overload for function when there is a mix of default arguments and yielding version

### ISSUE THREAD

**Issue by konovod** [crystal-lang/crystal#4928]
Example:
```crystal
def method(foo, optional = 0)
end

def method(foo, values, optional = 0)
end

def method(foo, optional = 0, &block)
  yield
end

method(1)
# Error in line 11: 'method' is expected to be invoked with a block, but no block was given
```
https://carc.in/#/r/2o6h
Expected behaviour - first variant must be called. 
Now if I change an order of definitions:
```crystal
def method(foo, values, optional = 0)
end

def method(foo, optional = 0)
end

def method(foo, optional = 0, &block)
  yield
end

method(1)
```
https://carc.in/#/r/2o6j
Everything works as expected.

So in my case a workaround is just to play with order of definitions, but this can be difficult when methods are located in different files or generated by macro.
Another workaround is to make `values` param typed. This also solves a problem, so untyped param somehow hides non-yielding overload.

**Comment by asterite** [comment]
But with:

```crystal
def method(foo, optional = 0)
end

def method(foo, values, optional = 0)
end
```

If you write:

```crystal
method(1, 2)
```

**both** overloads match. The second one erases the first when you define it like that.

I do agree it's very confusing. I think it's a mistake to have overloads in the language, it should be like in Ruby, one method for everything, so much simpler and consistent.

**Comment by asterite** [comment]
Why not just:

```crystal
def method(foo, values = 0, optional = 0)
end

def method(foo, optional = 0, &block)
  yield
end
```

I personally don't know what should the compiler do in the first snippet.

**Comment by konovod** [comment]
Huh, my bad. I've somehow missed this ambiguity. :bowing_man: 
I think overloading is a very nice feature, maybe compiler should complain instead of silently erasing in such cases, but current behavior is consistent (as erasing is useful for monkeypatching), so issue can perhaps be closed.

**Comment by RX14** [comment]
Perhaps cases like this are a good argument for an explicit `@[Override]` annotation or similar.

Another option is forcing overrides to have the exact same signature as what they're overriding.

**Comment by straight-shoota** [comment]
@RX14 Technically, it's only an override if the signatures are identical.

**Comment by RX14** [comment]
@straight-shoota no, with optional arguments and `*args` one method signature can override multiple other methods.

**Comment by asterite** [comment]
Right now the compiler tries to arrange overloads according to which one is more restrictive. The logic is very complex. In the case of:

```crystal
def method(foo, optional = 0)
end

def method(foo, values, optional = 0)
end
```

the second one should be more restrictive. With one argument the first one will match, with more arguments the second will match, so it should be the same as:

```crystal
def method(foo, )
end

def method(foo, values, optional = 0)
end
```
