### ISSUE TITLE
LibC::ESHUTDOWN is not defined

### ISSUE THREAD

**Issue by oprypin** [crystal-lang/crystal#4943]
https://github.com/crystal-lang/crystal/search?q=ESHUTDOWN shows it being used but not defined

https://github.com/crystal-lang/crystal/commit/27b790f380fc3bc12882840d06fe0c55b99b1757#diff-b67ae37b7956e573f1a5e19006b2615aR78 changed by @ysbaddaden 

Possibly related: https://github.com/python/cpython/blob/2ebc5ce42a8a9e047e790aefbf9a94811569b2b6/Objects/exceptions.c#L2653

**Comment by oprypin** [comment]
Same for:

- ENOTBLK
- ESOCKTNOSUPPORT
- EPFNOSUPPORT
- ESHUTDOWN
- ETOOMANYREFS

**Comment by straight-shoota** [comment]
Is this still relevant after #8885?

**Comment by oprypin** [comment]
Fixed by https://github.com/crystal-lang/crystal/commit/4164afe5d9844c419e59c6fdb01998a2ceea81e2#diff-84f879f7cc7be3862a99405ba54b77eb26a54d5a7f96ddfafe00f166416ac87dL137
Thanks
