### ISSUE TITLE
array - `.each_with_index` ignores some items

### ISSUE THREAD

**Issue by oldaniel** [crystal-lang/crystal#4959]
So my code is a follows:
```crystal
  # Pretty converter for the analyzed datasets
  def self.pretty_convert(dir : String)
    # Get json files we need to combine
    files = Dir.entries dir

    puts "Found: #{files}"

    # Add path to files
    files.each_with_index do |e, i|
      puts "Checking: #{e}"

      # Check if file isn't a json
      if File.extname(e) != ".json"
        # Remove non json file from array
        files.delete_at i

        puts "Removed: #{e}"
      else
        # Append dir before filename
        puts "Converting: #{e}"
        files[i] = "#{dir}/#{e}"
        puts "Converted: #{files[i]}"
      end
    end

    puts "Final results: #{files}"

    Tool.combine_json files, "results.json"
  end
```

**Here are some debug results**:
- I have 84 Strings in my array, the debugging finally showed, that we enumerate trough every item, by doing a count
- The output of the code above is [this](https://pastebin.com/CmUL2yTR), but instead of finding `2015-04` five times (1: Dir entries, 2: Checking file, 3: Converting file, 4: Converted message, 5: Final array), I find it only 2 times.

**What happend?**

**Comment by mgarciaisaia** [comment]
You're deleting elements from the same array you're iterating. That may be the source of the issue.

Haven't thought if that counts as a bug or not - but try to test that hypothesis to see if that's the case or not.

**Comment by asterite** [comment]
What @mgarciaisaia says is correct. I don't know if it's a bug, but it's known (at least for me :-P). In Crystal and Ruby this prints the same:

```ruby
a = [1, 2, 3]
a.each_with_index do |elem, index|
  p elem
  if elem == 2
    a.delete_at(index)
  end
end
```

Output:

```
1
2
```

On the other hand, this in Ruby raises:

```ruby
h = {1 => 2, 3 => 4}
h.each do |k, v|
  h[4] = 5
end
```

But not if you do `h.delete(...)`.

So, a bit inconsistent in Ruby.

We could maybe have a counter in both Array and Hash that's incremented when the iteration stars and decremented when the iteration ends, and check if it's modified and raised (like Java's "concurrent modification exception"), but I think that might make things pretty slow (you have to `ensure` that the counter gets decremented)

**Comment by oldaniel** [comment]
@mgarciaisaia As you may see in the output log, no element has been removed. They sometimes just ignored the change of the element.

**Comment by oldaniel** [comment]
@asterite So thanks for showing that I need to count from 0 up, forgot that again. And yeah, deleting an array element while enumerating trough it is actually a bad idea. Thanks a lot for the quick response, and sorry for the stupid mistake.
