### ISSUE TITLE
A bug trying to downcast a tuple given as a named argument

### ISSUE THREAD

**Issue by jbomanson** [crystal-lang/crystal#4965]
When compiled, the following code brings up a 'BUG: trying to downcast Tuple(Int32) <- Int32':

```crystal
def bar(**options, many) : Nil
end

def foo(**options, many) : Nil
  bar(**options, many)
end

foo(one: 0, many: {0})
```

One may notice that the code should not compile in the first place because the call to `bar` should be written as `bar(**options, many: many)`.

The bug happens with and without release mode.

I am running `Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1`.

The versions 0.23.1, 0.20, 0.18 at play.crystal-lang.org also failed.

**Comment by asterite** [comment]
Reduced:

```crystal
def foo(**a, b)
end

foo(**{x: 0}, {1})
```

**Comment by asterite** [comment]
Actually, this shouldn't compile:

- Def arguments past `**` shouldn't be allowed
- Call arguments past `**` shouldn't be allowed

**Comment by asterite** [comment]
Workaround until this is fixed:

```crystal
def bar(many, **options) : Nil
end

def foo(many, **options) : Nil
  bar(many, **options)
end

foo(one: 0, many: {0})
```

**Comment by asterite** [comment]
(oops, just noticed your comment, hehe, should read more carefully)
