### ISSUE TITLE
It's not validating the abstract methods implementation types

### ISSUE THREAD

**Issue by mrkaspa** [crystal-lang/crystal#4966]
This code

```crystal
abstract class Ord(A)
  abstract def cmp(a : A, b : A) : String
end

class IntOrd < Ord(Int32)
  def cmp(a, b)
    a > b
  end
end
```

or this 

```crystal
module Ord(A)
  abstract def cmp(a : A, b : A) : String
end

class IntOrd
  include Ord(Int32)

  def cmp(a, b)
    a > b
  end
end
```

Are valid for the compiler but it does not validate the right types in the implementation side

**Comment by asterite** [comment]
You are defining a new method `cmp(a, b)` without restrictions. This trivially matches the more restrictive abstract method.

Same as this:

```crystal
abstract class Foo
  abstract def foo(x : Int32)
end

class Bar < Foo
  # this doesn't have a restriction, so it accepts Int32 (and more types)
  def foo(x)
  end
end
```

**Comment by mrkaspa** [comment]
@asterite how can I validate it accomplishes the interface?

**Comment by asterite** [comment]
Just to be clear, it accomplishes the "interface" (and more). There's no way to do that. Why do you need it?

**Comment by mrkaspa** [comment]
@asterite just dabbling with the language, if the abstract keyword can't ensure that, what is the purpose of that? does crystal handles a compiled ducktyping?

**Comment by asterite** [comment]
@mrkaspa If you leave the `def` out, Crystal does complain. 

We *could* change that and require that, if an abstract method has restrictions in the arguments, force them to be too in the implementors. It's just not the philosophy of the language. The language tries not to force types on users.

**Comment by asterite** [comment]
We can leave this issue open, though. It's something to discuss. But Crystal's type system is very hippie, so if you like, write types all the time and everywhere you will find Crystal lacking in formalism.

**Comment by asterite** [comment]
Similar issue: https://github.com/crystal-lang/crystal/issues/160

**Comment by mrkaspa** [comment]
@asterite got your point, so what is the idea of the abstract methods if their implementation is not forced?

**Comment by mrkaspa** [comment]
@asterite how should I say I expect a type that has a method implemented? because in constructors the type is mandatory

**Comment by RX14** [comment]
@mrkaspa the implementation *is* forced. `def foo(x)` can take *any* type as `x`, so it would implement `abstract def foo(x)`, `abstract def foo(x : Foo)` and `abstract def foo(x : Bar)`.

**Comment by mrkaspa** [comment]
@RX14 got it, what's left is to force the types

**Comment by RX14** [comment]
@mrkaspa It's not as clear that changing this is actually what we want to do, especially because of overloads. If you for example have
```cr
class A
end

class B < A
end

abstract class Abstract
  abstract def foo(foo : B)
end

class Impl < Abstract
  def foo(foo : A)
   # something
  end
end
```

Does that compile? Common sense says it should. But isn't that the same as not specifying a type restriction which you want to change: all we're doing is specifying a more general type.

If we make it so that you "force" the types this happens:
```cr
class A
end

class B < A
end

abstract class Abstract
  abstract def foo(foo : B)
end

class Impl < Abstract
  def foo(foo : A)
   # something
  end

  # to satisfy the abstract
  def foo(foo : B)
   # there's no way to call the more abstract foo(A) here.
  end
end
```

We can't call `Impl#foo(A)` because we'd always end up calling our own method, as `Impl#foo(B)` is more specific than `Impl#foo(A)`.

I hope you understand why this isn't as easy to reason about as one might think.

**Comment by mrkaspa** [comment]
Got it

**Comment by RX14** [comment]
@asterite should we close?

**Comment by asterite** [comment]
I think we can close, yes. The type system has many things to improve, document or re-think, and #160 is more or less the same issue (about a child's types not caring much about a parent's types)
