### ISSUE TITLE
Feature Request: NTLM support for HTTP::Client

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#4970]
Right now HTTP::Client supports basic authentication, addition for NTLM (maybe even Kerberos?) could be really helpful to those working against Microsoft based products.

**Comment by bew** [comment]
I think it could be done in a shard first, and if it's really necessary for a lot of people, add it to the stdlib but I doubt it a little.

**Comment by bararchy** [comment]
@bew I really think that is we have `basic_auth` we should have NTLM support too, Ruby has it (I know it's not a good reason) and we can take most of the implementation details from there

**Comment by RX14** [comment]
Basic auth is a *lot* simpler than these other auth types and way more common. I doubt this will ever be in the stdlib.

**Comment by asterite** [comment]
@bararchy Are you sure Ruby has it built-in? I can only find gems about it.

**Comment by bararchy** [comment]
My bad, I though Net::NTLM was in STD, apparently it was a gem.

http://www.rubydoc.info/gems/rubyntlm/0.5.0/Net/NTLM

So, I guess same logic should be in Crystal, I'll close the issue.
