### ISSUE TITLE
'self' was used before initializing instance variable, except it wasn't?

### ISSUE THREAD

**Issue by decademoon** [crystal-lang/crystal#4981]
```cr
def f(x)
end

class A
  def initialize
    @a = 0
    f(self)
    @a = 0 # error
  end
end

A.new
```

```
Error in foo.cr:12: instantiating 'A:Class#new()'

A.new
  ^~~

instance variable '@a' of A must be Int32, not Nil

Error: 'self' was used before initializing instance variable '@a', rendering it nilable
```

Crystal version 0.23.1
https://play.crystal-lang.org/#/r/2qcv

This seems like an issue that was likely raised before, but I couldn't find anything specific to it (except maybe #4147 or #1687). In my example `@a` is clearly initialized and always will be in every possible situation, won't it?

**Comment by decademoon** [comment]
I "fixed it" by doing this in the meantime:

```cr
def f(x)
end

class A
  def initialize
    @a = 0
    f(self)
    ->{ @a = 0 }.call
  end
end

A.new
```

**Comment by asterite** [comment]
You are right, `@a` is clearly initialized in your example.
