### ISSUE TITLE
Is it possible to pass a query via the querystring?

### ISSUE THREAD

**Issue by opensas** [crystal-lang/crystal#4999]
This is more a question than an issue.

I was thinking about something like:
`http://devdocs.io/crystal/q={{{s}}}`
To get automatically to the search box with the text in s
Is it possible?

**Comment by decademoon** [comment]
Is this question specifically about devdocs.io or Crystal? Perhaps stackoverflow would be a better place to ask how-to questions since this isn't an issue relating to Crystal.

Try http://devdocs.io/crystal/#q=foobar

**Comment by opensas** [comment]
oops, sorry, I though I was asking at devdocs's github, thanks!
