### ISSUE TITLE
Crystal and WebAssembly?

### ISSUE THREAD

**Issue by shevegen** [crystal-lang/crystal#5001]
Please feel free to just close the issue whenever it fits.

I had a look at this website lately:

https://developer.mozilla.org/en-US/docs/WebAssembly/C_to_wasm

Now - it's C/C++ to WebAssembly but I was thinking ... why not with
Crystal? Would this be possible, in theory? (I really have absolutely
no idea).

Perhaps it could be put into a crystal FAQ or so. It probably is a 
very, very, very low priority but ... anything else but JavaScript on
the www sounds like a win to me.

**Comment by akzhan** [comment]
Duplicate of #829
