### ISSUE TITLE
SSL_connect: Unexpected EOF (OpenSSL::SSL::Error)

### ISSUE THREAD

**Issue by codenoid** [crystal-lang/crystal#5010]
my code

```
CAT = File.read("somefile.txt")

loop do
  category = CAT.split("\n")
  category.each do |v|
    is_f = v.split("|")
    is_f == "c" ? fork { get(v) } : get(v)
  end
end

def get()
  # http client
  # n = number from http get
  (0...n).each do |i|
    # http client get
    # json parsing
    # http client post
  end
end
```

my app has been running for 1 hours, thanks ^^
error

```
SSL_connect: Unexpected EOF (OpenSSL::SSL::Error)
0x437105: ??? at ??
0x46e2f2: ??? at ??
0x46a779: ??? at ??
0x4695f7: ??? at ??
0x464e64: ??? at ??
0x4636a4: ??? at ??
0x4102c8: ??? at ??
0x430c6b: main at ??
0x7f3bad1ed830: __libc_start_main at ??
0x40e889: _start at ??
0x0: ??? at ??
```

**Comment by codenoid** [comment]
https://github.com/crystal-lang/crystal/blob/3c6c75e68f326bb91be35f71ae30672fd454776e/src/openssl.cr#L110

**Comment by RX14** [comment]
Please reopen this with some reproducible code.

**Comment by codenoid** [comment]
@RX14 I guess I can not give it all, and this error comes after 1 hour running, so I'm not sure where exactly the problem

**Comment by RX14** [comment]
We can't investigate anything without a working code sample. You can either give the whole code + instructions, or preferably you can remove the bits of code that are unneccesary to reproduce.

It appears to me that your code requests multiple URLs, perhaps it's the same URL which causes the error every time?
