### ISSUE TITLE
crystal for rubyists error index array

### ISSUE THREAD

**Issue by monouser7dig** [crystal-lang/crystal#5026]
https://github.com/crystal-lang/crystal/wiki/Crystal-for-Rubyists
says 

``` Crystal 
a = [1, 2, 3]
a[0] + a[1] #=> Error: undefined method `+` for Nil
```
you probably meant to say something like `a[0] + a[4]`

**Comment by Sija** [comment]
You missed the most important part:

>The reason behind this change is that it would be very annoying to program in this way if every Array or Hash access could return nil as a potential value. This wouldn't work:

**Comment by monouser7dig** [comment]
makes some sense, agreed
