### ISSUE TITLE
Possible typo in src/string.cr

### ISSUE THREAD

**Issue by da99** [crystal-lang/crystal#5030]
On line 124: [https://github.com/crystal-lang/crystal/blob/master/src/string.cr#L124](https://github.com/crystal-lang/crystal/blob/master/src/string.cr#L124)

```crystal


# Hexadecimal escape sequences
"\x45" # # => "A"
````
But this is what I get in the Crystal playground: https://play.crystal-lang.org/#/r/2sep
"\x45" prints "E", not "A":
![screenshot from 2017-09-24 12-21-04](https://user-images.githubusercontent.com/1551848/30784847-9b5e63e6-a122-11e7-9870-9e23b7d6fc97.png)

**Comment by faustinoaq** [comment]
Good catch!

![screenshot_20170924_132748](https://user-images.githubusercontent.com/3067335/30785420-2a2f2cdc-a12c-11e7-833c-31649929c940.png)

**Comment by da99** [comment]
@faustinoaq "\xNN" only handles ASCII codes in hexadecimal, right? No other encodings?

**Comment by faustinoaq** [comment]
I think so :sweat_smile:
