### ISSUE TITLE
Unclear documentation related to Top Level Namespace

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#5051]
- [ ] In [Top Level Namespace](https://crystal-lang.org/api/0.23.1/toplevel.html) `Fiber#get` and `Fiber#cancel` are mentioned, but I couldn't find any information about these methods neither on [Fiber docs](https://crystal-lang.org/api/0.23.1/Fiber.html) nor in [Fiber source code](https://github.com/crystal-lang/crystal/blob/e2a1389e8165fb097c785524337d7bb7b550a086/src/fiber.cr)
- [ ] [#lazy](https://crystal-lang.org/api/0.23.1/toplevel.html#lazy%28%26block%3A-%3E_%29-class-method) mentions `Fiber#get` method, but it's not stated in the example code (counter [#future](https://crystal-lang.org/api/0.23.1/toplevel.html#future%28%26exp%3A-%3E_%29-class-method) example)
- [ ] [#fork](https://crystal-lang.org/api/0.23.1/toplevel.html#fork-class-method) doesn't have link generated to `Process.fork`
- [ ] There is no documentation for [parallel](https://crystal-lang.org/api/0.23.1/toplevel.html#parallel%28%2Ajobs%29-macro) macro and I feel that's it quite interesting but I couldn't understand its source code

**Comment by asterite** [comment]
All of those are unstable/changing, that's why they are not documented

**Comment by vladfaust** [comment]
However, could someone briefly explain these to us?

**Comment by vladfaust** [comment]
Also, how about `STABLE` or `UNSTABLE` flag keywords? These could be useful in docs.

**Comment by RX14** [comment]
They're largely internal parts of crystal which only the stdlib should use. That's why they're not documented.

**Comment by vladfaust** [comment]
So one better doesn’t use #future? 🙁

**Comment by vladfaust** [comment]
`#fork` is documented is it *stable*? `#lazy` and `#future` **do** have documentation, are they stable?

**Comment by RX14** [comment]
I recall a general desire to remove `#fork` once we get concurrency. `#lazy` and `#future` will probably be rewritten which may or may not be breaking. They're *very* uncommonly used anyway. Parallel should probably be documented though.

**Comment by vladfaust** [comment]
@RX14 i find `#future` *very* useful in terms of making http requests... Are there ways to do concurrent requests besides of complex `Channel` system?

**Comment by vladfaust** [comment]
So I got no response, therefore these promising methods would not be used by anyone, hence closing :cry:
