### ISSUE TITLE
Unix domain socket crashes program

### ISSUE THREAD

**Issue by stefanwille** [crystal-lang/crystal#506]
I get a program crash while using Unix domain sockets.

I am still working on a Redis client. While adding Unix domain support, I found that Crystal crashes my program for larger messages.

This program shows the issue (requires a Redis server with a Unix domain socket at /tmp/redis.sock):

```Crystal
require "socket"

io = UNIXSocket.new("/tmp/redis.sock")
6.times do |i|
  io << "*3\r\n"
  io << "$3\r\n"
  io << "SET"
  io << "$#{i.to_s.length}\r\n"
  io << "foo\r\n"
  io << "#{i.to_s}\r\n"
end
io.flush
```

I get 3 different behaviours, completely random.

First, a simple crash:
```
$ crystal run experiments/unixsocket-hanging.cr
Using compiled compiler at .build/crystal
Program terminated abnormally with error code: 13
```

Second, a crash with stacktrace:
```
$ crystal run experiments/unixsocket-hanging.cr
Using compiled compiler at .build/crystal
Error writing file: Socket is not connected (Errno)
*Exception@Exception#initialize<Errno, String>:Array(String) +46 [4461984222]
*Errno#initialize<Errno, String>:Array(String) +128 [4461984160]
*Errno::new<String>:Errno +119 [4461984007]
*UNIXSocket@FileDescriptorIO#write<UNIXSocket, Slice(UInt8), Int32>:Nil +247 [4461983495]
*UNIXSocket@IO#write<UNIXSocket, Slice(UInt8)>:Nil +61 [4461983229]
*String#to_s<String, UNIXSocket>:Nil +90 [4461971946]
*UNIXSocket@IO#<<<UNIXSocket, String>:UNIXSocket +22 [4461983142]
__crystal_main +864 [4461961392]
main +32 [4461963264]
Program terminated abnormally with error code: 256
```

Third, the program terminates seemingly successfully:
```
$ crystal run experiments/unixsocket-hanging.cr
Using compiled compiler at .build/crystal
```

**Comment by jhass** [comment]
Since we got major changes to IO in current head, could you please note which version you tested against?

**Comment by stefanwille** [comment]
Ups... I should have included this information right away. 
I compiled my Crystal from master branch. Latest commit is 315aaf2.

**Comment by stefanwille** [comment]
With TCPSocket, the program works just fine.

**Comment by stefanwille** [comment]
Here is a simpler program that triggers the same crash:

```Crystal
require "socket"

io = UNIXSocket.new("/tmp/redis.sock")
6000.times do
  io << "SET foo 100"
end
io.flush
```

**Comment by asterite** [comment]
I'm trying to reproduce this but I get `Error connecting to '/tmp/redis.sock': No such file or directory (Errno)`.

I start `redis-server` but no luck. It seems it doesn't write `/tmp/redis.sock`. I also try specifying a config file with that location for the unixsocket but nothing happens.

@stefanwille How can I tell redis-server to use that file? This is on a Mac.

**Comment by stefanwille** [comment]
Hi @asterite, I am working on a Mac too. 

Please edit redis.conf (mine is at /usr/local//etc/redis.conf, created through Homebrew) and uncomment these two lines:

```
#unixsocket /tmp/redis.sock
#unixsocketperm 755
````

Then restart Redis.

**Comment by asterite** [comment]
Well, I debugged it but I can't find what's wrong. One thing we are not doing is setting sockaddr_un's member "sun_len". But I tried that and I also get a failure. I even tried a C program and it fails. But Ruby "works": I get a `write: Broken pipe (Errno::EPIPE)` after about 5960 writes.

I don't know if this fails in linux too, somebody with linux will have to try it. Might only be failing in darwin...

**Comment by stefanwille** [comment]
I also tried this with a C program and for me too it failed with a 'Broken pipe'. I think this is Redis closing the connection, as it expects `"\r\n"` and doesn't receive it in the simpler program. I have added the CR/LF and now it works in C. The Crystal program with CR/LF hangs though, most of the time.

```crystal
require "socket"

io = UNIXSocket.new("/tmp/redis.sock")
6000.times do
  io << "SET foo 100\r\n"
end
```

I removed the call to `io.flush` btw.

I assumed that Crystal might hang because a lot of data piles up to be received. So when I add a call to `io.gets`, it works in Crystal too:

```crystal
require "socket"

io = UNIXSocket.new("/tmp/redis.sock")
6000.times do
  io << "SET foo 100\r\n"
  io.gets
end
```

The call to `io.gets` should not be necessary though, and it isn't in the C version.

Also, the more complex program from above still crashes with the added `io.gets`:

```crystal
require "socket"

io = UNIXSocket.new("/tmp/redis.sock")
6.times do |i|
  io << "*3\r\n"
  io << "$3\r\n"
  io << "SET"
  io << "$#{i.to_s.length}\r\n"
  io << "foo\r\n"
  io << "#{i.to_s}\r\n"
  io.gets
end
```

**Comment by miketheman** [comment]
#triage Attempt to recreate on 0.16.0

redis-server startup command, simplified:
```bash
$ redis-server --unixsocket /tmp/redis.sock --unixsocketperm 755
# 2nd terminal
$ redis-cli
127.0.0.1:6379> monitor
OK
# 3rd terminal, try sending a payload to the unix socket
$ echo "SET foo 1" | nc -U /tmp/redis.sock
+OK
# 2nd terminal (monitor) displays:
1463236492.868717 [0 unix:/tmp/redis.sock] "SET" "foo" "1"
```

Running this example produces no error, and updates the value of `foo` in redis to the number of the iteration looped:
```crystal
io = UNIXSocket.new("/tmp/redis.sock")
6000.times do |iter|
  io << "SET foo #{iter}\r\n"
end
```
MONITOR output:
```bash
...
1463236857.620739 [0 unix:/tmp/redis.sock] "SET" "foo" "5998"
1463236857.620750 [0 unix:/tmp/redis.sock] "SET" "foo" "5999"
```

So the simple example uses a line ending, no `.flush` or `.gets`.

Taking the more complex example, I was able to also produce valid Redis messages, with some modifications:
```crystal
io = UNIXSocket.new("/tmp/redis.sock")
600.times do |iter|
  key = "foo"

  io << "*3\r\n"
  io << "$3\r\n"
  io << "SET\r\n"
  io << "$#{key.size}\r\n"
  io << "#{key}\r\n"
  io << "$#{iter.to_s.size}\r\n"
  io << "#{iter}\r\n"
  # io.gets - does not change behavior, responds with "+OK\r\n"
end
```

- String no longer has `.length` so I used `.size`
- I added the `iter` modifier for some noise to see the value change
- Didn't require use of `io.flush` or `io.gets` to see the values appear in redis db

The Redis protocol requires enumerating each element's size, something that was missing from the original example.
This leads me to believe that this is not a bug in the UnixSocket library, rather incorrect implementation of the wire protocol.

Recommend review for closure.

**Comment by stefanwille** [comment]
I will retest once I get my hands on my computer, which will be in 2 weeks.

**Comment by stefanwille** [comment]
I retested and I don't see the issue anymore. Thanks @miketheman 😄
