### ISSUE TITLE
Remove recursion with method_added

### ISSUE THREAD

**Issue by bew** [crystal-lang/crystal#5066]
This code used to work (I don't remember the version and I didn't managed to bisect that properly with versions before 0.21.0):
```cr
module ModuleName
  macro method_added(meth)
    {% puts "Method #{meth.name} added" %}
    {{meth}}
  end

  # triggers the hook
  def normal_method
  end
end
```
It used to be called once, display the proper message, and defines the method.
_(In fact this is a bad example, see https://github.com/crystal-lang/crystal/issues/5066#issuecomment-333406459 for a better one!)_

Now I get:
```
"Method normal_method added"
"Method normal_method added"
"Method normal_method added"
"Method normal_method added"
...
```
Followed by a stackoverflow error...

This is because the macro is expanded to:
```cr
 
def normal_method
end
```
and during the interpretation of the macro expansion, the macro `method_added` is called (again) for the generated method.

I think that methods defined by a `method_added` expansion should not trigger `method_added` again, but methods defined in other places (normal code or other macros) should trigger it.

**Comment by oprypin** [comment]
have you tried different versions on https://carc.in ?

**Comment by bew** [comment]
@oprypin good idea! And the result is weird:

For 0.18.0 -> 0.21.1: it recurses, the compiler crash, and the output is visible on carc.in.
For 0.22.0 -> 0.23.1: it surely recurses then crash, but carc.in crashes too (error 504), and the view is back to the editor (not showing the result).

I keep a repository with cool crystal snippets, and I added this one 5 weeks ago (29 aug. 2017). The thing is I'm almost sure it worked when I added it, as I _almost_ never add non-working snippets to the repo..

Either way, I think it should not recurse like this for methods defined by the expansion of the `method_added` macro. WDYT?

**Comment by Sija** [comment]
Isn't the `{{meth}}` at the end of the macro causing the recursion?

```cr
def foo; end # => method_added # => def foo; end # => method_added # ...
```

**Comment by bew** [comment]
@Sija yes it is. The (small) purpose of this snippet is to write a message, and then actually define the method, so it can be called later.

**Comment by straight-shoota** [comment]
Wow I didn't know about `method_added`... there are to many awesome but undocumented features in Crystal =)

But why would you define the method again inside the macro? As far as I understand the code and examples, `method_added` is invoked after the method has been defined. So your `{{ meth }}` just defines the method again (and again and again ...) and I doubt this has ever worked without recursion judging by the introductory code of this feature from #1090.

**Comment by Sija** [comment]
@straight-shoota yep, that was exactly my point ;) TIL the same 🎉

**Comment by bew** [comment]
yeah I know this example is dumb as hell, maybe a more useful feature would be:
```cr
module Tracer
  macro included
    macro method_added(def_node)
      def \{{def_node.name}}(\{{def_node.args.splat}})
        puts "Entering method \{{def_node.name}}"

        \{{def_node.body}}

        puts "Leaving method \{{def_node.name}}"
      end
    end
  end
end

class MyClass
  include Tracer

  def foo
    puts "Hello from foo"
  end

  def bar(*args)
    puts "There are #{args.size} args!"
  end
end


MyClass.new.foo
puts
MyClass.new.bar 1, 2, 3
```

Here, each method definition in `MyClass` will call the `method_added` hook (coming from the inclusion of `Tracer`, and after the hook ran, the generated def will also call `method_added` hook (which is clearly not needed!).

**Comment by straight-shoota** [comment]
Yes, I figured there would be a more reasonable example.
Just a note: You could probably use `previous_def` instead of expanding the body in the macro.

I think it's safe to assume that the `method_added` macro should never be triggered from a method defined in this hook.

**Comment by bew** [comment]
> You could probably use `previous_def` instead of expanding the body in the macro.

Oh yes, you're right!! I always thought the method wasn't defined and it was the role of the macro to define it... (weird thinking, I know..) silly me, I should have read the specs for once!

**Comment by straight-shoota** [comment]
Well, the specs actually don't show nor test that. At least it's not obvious to me. They seem to just spec that the macro is invoked, not that the method has been defined at that point.

**Comment by bew** [comment]
The specs probably don't test it because it was obvious IMO. Nevermind, now I know 😄

**Comment by MakeNowJust** [comment]
@straight-shoota Sorry I missed to write document for this feature.

@bew

When I implement this feature, I thought recursion with `method_added` is no problem because we can mutate some values on compile-time, for example:

```crystal
module Tracer
  macro included
    WRAPPED = [] of String

    macro method_added(def_node)
      \{% if !WRAPPED.includes? def_node.name %}
        \{% WRAPPED.push def_node.name %}

        def \{{def_node.name}}(\{{def_node.args.splat}})
          puts "Entering method \{{def_node.name}}"

          previous_def

          puts "Leaving method \{{def_node.name}}"
        end
      \{% end %}
    end
  end
end

class MyClass
  include Tracer

  def foo
    puts "Hello from foo"
  end

  def bar(*args)
    puts "There are #{args.size} args!"
  end
end


MyClass.new.foo
puts
MyClass.new.bar 1, 2, 3
```

Above example works intentionally. However, I think now this recursion has no usage, so I'd fix not to invoke `method_added` when method is defined inside `method_added`.

**Comment by bew** [comment]
> When I implement this feature, I thought recursion with method_added is no problem because we can mutate some values on compile-time

Yes I figured this out while trying to make it work! (I just pushed the whole node into the array, not just its name ˆˆ)

Thank you for looking into that @MakeNowJust!

**Comment by straight-shoota** [comment]
@MakeNowJust don't feel sorry. It after all was (and probably still is?) an experimental feature. And your PR got accepted without a proper documentation or spec, so not your fault if it is anyones ;)

**Comment by asterite** [comment]
But in Ruby:

```ruby
class Foo
  def self.method_added(method_name)
    p method_name

    define_method :bar do
    end
  end

  def foo
  end
end
```

Output:

```
...
:bar
:bar
foo.cr:3:in `p': stack level too deep (SystemStackError)
```

So why does it have to work in a different way in Crystal?

**Comment by MakeNowJust** [comment]
> So why does it have to work in a different way in Crystal?

Because there is this issue. I can't found use case of current behavior.

**Comment by MakeNowJust** [comment]
Another point, Ruby's `method_added` is just a method, so it is invoked on run-time, we can use `Hash` or `Array` to prevent recursion of `method_added` simply. However, Crystal's one is a macro, so it is invoked on compile-time. It is not easy to use `Hash` or `Array` simply.
