### ISSUE TITLE
Is it possible to get all instance methods in macros?

### ISSUE THREAD

**Issue by maiha** [crystal-lang/crystal#5067]
`@type.methods` returns methods defined in **only current class**.
Is there any way to get **all instance** methods in macros?

```crystal
class Base
  def a
  end
end

class Sub
  def b
  end

  {% p @type.methods.map(&.name) %}
end
```

For example, this produces `[b]` in crystal-0.23.1.
I'd like to get `[a, b]`.

Thanks.

**Comment by Sija** [comment]
Isn't `class Sub` meant to inherit from `Base`? Btw, there's `TypeNode#ancestors` method if that helps.

**Comment by maiha** [comment]
@Sija 
Yup, you're completely right! That is `Sub < Base`.
And thank you for `ancestors`. Gotcha!

```crystal
  {% p ([@type] + @type.ancestors).map(&.methods.map(&.name)) %}
```

```
[[b], [a], [object_id, ==, ...
```

Thanks!
