### ISSUE TITLE
(homebrew --HEAD) build error 

### ISSUE THREAD

**Issue by monouser7dig** [crystal-lang/crystal#5068]
```bash
==> Cloning https://github.com/crystal-lang/crystal.git
Updating ~/Library/Caches/Homebrew/crystal-lang--git
==> Checking out branch master
==> Downloading https://github.com/crystal-lang/crystal/releases/download/0.23.0/crystal-0.23.0-1-da
Already downloaded: ~/Library/Caches/Homebrew/crystal-lang--boot-0.23.0.tar.gz
==> make crystal release=true
==> Downloading https://github.com/crystal-lang/shards/archive/v0.7.1.tar.gz
Already downloaded: ~/Library/Caches/Homebrew/crystal-lang--shards-0.7.1.tar.gz
==> /private/tmp/crystal-lang-20171002-67016-108lnqf/bin/crystal build -o /private/tmp/crystal-lang-
Last 15 lines from ~/Library/Logs/Homebrew/crystal-lang/02.crystal:
Error in src/shards.cr:5: while requiring "./cli"

require "./cli"
^

in src/cli.cr:2: while requiring "./commands/*"

require "./commands/*"
^

in src/commands/prune.cr:2: while requiring "./file_utils": can't find file './file_utils' relative to '/private/tmp/crystal-lang--shards-20171002-67016-1prngkl/shards-0.7.1/src/commands'

require "./file_utils"
```

to me reads like it is rather crystal related and not homebrew (or I just screwed something)

if any further information/ trial is required please just ask

thanks

**Comment by bew** [comment]
Can you give us the content of the file `~/Library/Logs/Homebrew/crystal-lang/02.crystal` ?

**Comment by monouser7dig** [comment]
sure
[log](https://gist.github.com/monouser7dig/829a398181e40b5f16a438084ba70e88)

**Comment by bew** [comment]
Ok so the error is:
```
in src/commands/prune.cr:2: while requiring "./file_utils": can't find file './file_utils' relative to '/private/tmp/crystal-lang--shards-20171002-67016-1prngkl/shards-0.7.1/src/commands'

require "./file_utils"
^
```
Meaning that a file can't be found. The thing is, this error (in `shards` project) has been fixed the 5 august by https://github.com/crystal-lang/shards/commit/5ebec014b1a86b931342d3d5f7dca34639917f3c, maybe your homebrew isn't uptodate (=> don't get the correct package?).
Maybe try something like `brew update` and try to re-install `crystal`?

**Comment by monouser7dig** [comment]
I am actually pretty sure my hb is up to date
fetching the source should anyway probably be handled by git and thus an old hb should not be an issue?

`brew reinstall crystal-lang --build-from-source` works btw.

**Comment by bew** [comment]
> fetching the source should anyway probably be handled by git and thus an old hb should not be an issue?

I agree! I never touched homebrew myself, so I'm just emitting some speculation 😄

If your issue is resolved, can you close this issue?

**Comment by monouser7dig** [comment]
the `--build from source` works, ``--HEAD` however does not

to me this seems as if the latest version of crystal has a flaw which the last tagged release does not

**Comment by monouser7dig** [comment]
maybe it is because they hardcore the [shards as](https://github.com/crystal-lang/homebrew-crystal/blob/master/crystal-lang.rb)
```
resource "shards" do
    url "https://github.com/crystal-lang/shards/archive/v0.7.1.tar.gz"
    sha256 "31de819c66518479682ec781a39ef42c157a1a8e6e865544194534e2567cb110"
  end
```
so this needs to be updated?

**Comment by monouser7dig** [comment]
> It's common for crystal (master) to break compatibility which is fixed in shards (master). I won't release a Shards version that may require crystal (master).

The homebrew formula should be fixed to use Shards master instead of the Shards release when --HEAD is passed.

sounds reasonable if the homebrew formula could do that

**Comment by RX14** [comment]
Closing, this isn't a crystal issue.

**Comment by monouser7dig** [comment]
one of the maintainers did just resolve the `outdated shards` issue by modifying the formula however the formula does still not build

it would be good to know if the issue is just one with the current crystal master branch 
[issue](https://github.com/Homebrew/homebrew-core/pull/18968#issuecomment-334122380)
```
==> Checking out branch master
==> /private/tmp/crystal-lang-20171004-42284-lx4ezs/bin/crystal build -o /private/tmp/crystal-lang-20
Last 15 lines from /Users/joe/Library/Logs/Homebrew/crystal-lang/02.crystal:

      read_mapping(pull) do
      ^~~~~~~~~~~~

in src/spec.cr:73: instantiating 'read_mapping(YAML::PullParser)'

      read_mapping(pull) do
      ^~~~~~~~~~~~

in src/spec.cr:117: undefined method 'line_number' for YAML::PullParser

            raise YAML::ParseException.new("unknown attribute: #{ key }", pull.line_number, pull.column_number)
                                                                               ^~~~~~~~~~~
```
thanks

**Comment by monouser7dig** [comment]
same issue after the latest merges, how can CI pass but building locally not?

**Comment by Sija** [comment]
@monouser7dig I've created an issue for it, see https://github.com/crystal-lang/shards/issues/175.

**Comment by monouser7dig** [comment]
ok nice, would still be really interesting to know why CI considers this a passing build? :)

**Comment by Sija** [comment]
'cause CI does **not** consider building _shards_ as a part of the testing :)

**Comment by monouser7dig** [comment]
hm ok interesting decision but maybe worth it if shards have their own CI (but apparently they do not :o)

**Comment by RX14** [comment]
shards has it's own CI, it just tests based on the last crystal version, not master. Which is fine.

The correct way to package shards is to build *the latest shards release* with *the latest crystal release* and then build a crystal compiler from HEAD if you wish. Compiling crystal head requires the latest compiler release anyway, so it shouldn't be too hard.

**Comment by monouser7dig** [comment]
the issue was that the latest shards release does not work with the crystal HEAD (that was the first issue)

maybe this has to be taken further by someone who knows the deps better than me and still likes homebrew

**Comment by RX14** [comment]
@monouser7dig my entire answer was that you shouldn't compile the latest shards release with crystal HEAD, you should compile it with the latest release of crystal. And the latest shards release is all you need for using crystal HEAD, not shards HEAD.
