### ISSUE TITLE
Bug: union of Int32 and BigRational leads to Number

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#5073]
https://carc.in/#/r/2uh7

```crystal
require "big_rational"

class Foo
  @foo = Hash(Symbol, Int32 | BigRational).new
end

Error in temp2.cr:4: instance variable '@foo' of Foo must be Hash(Symbol, Number), not (Hash(Symbol, BigRational | Int32) | Hash(Symbol, Number))

  @foo = Hash(Symbol, Int32 | BigRational).new
  ^~~~
```

```
$ crystal -v
Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1
```

The hash is defined in macro as seen [here](https://github.com/vladfaust/core.cr/blob/50a1c5dcce5e8983c72dddb73cc40f317d0e4fdd/src/core/model/schema.cr#L441), so I'm unable to unify types in one `Number`.

Related: https://github.com/vladfaust/core.cr/issues/8

**Comment by RX14** [comment]
We typically add the PRs instead of the closed issues to the Next milestone @asterite. That way we track what code was actually merged instead of just the issues, when one PR might close multiple or introduce it's own side effect.

**Comment by asterite** [comment]
@RX14 Mmm... But when you browse the milestone you have no idea then what bugs were fixed.

**Comment by RX14** [comment]
@asterite PRs almost always have some mention or link of the issue they're related to. At the very least if they don't, the PR contains a description of the bug. We wouldn't know how to review a PR ourselves if we didn't know what it fixed.
