### ISSUE TITLE
Documentation -- Class code bug?

### ISSUE THREAD

**Issue by Wulfklaue** [crystal-lang/crystal#5077]
Just tried Crystal under windows 10 -- WSL with a basic sample of the documentation. Maybe its my lack of understanding the code but running it results into this:

----------------------

crystal test.cr

stat: Invalid argument
0x5c0015: ??? at ??
0xb6a840: ??? at ??
0x611146: ??? at ??
0x5e1dac: main at ??
0x7f55859d1f45: __libc_start_main at ??
0x5bb20d: ??? at ??

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https:/
/github.com/crystal-lang/crystal/issues

----------------------

```
class Person
  @age = 0

  # Increases age by one
  def become_older
    @age += 1
  end

  # Increases age by the given number of years
  def become_older(years : Int32)
    @age += years
  end

  # Increases age by the given number of years, as a String
  def become_older(years : String)
    @age += years.to_i
  end

  # Yields the current age of this person and increases
  # its age by the value returned by the block
  def become_older
    @age += yield @age
  end
end

person = Person.new "John"

person.become_older
person.age #=> 1

person.become_older 5
person.age #=> 6

person.become_older "12"
person.age #=> 18

person.become_older do |current_age|
  current_age < 20 ? 10 : 30
end
person.age #=> 28
```

------------------------------

https://crystal-lang.org/docs/syntax_and_semantics/methods_and_instance_variables.html

------------------------------

Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1

**Comment by Wulfklaue** [comment]
Update:

Rebooting solved the above mentioned issue.

But several of  the examples on the page have issues

-----------------------

crystal test.cr
Error in test.cr:26: wrong number of arguments for 'Person.new' (given 1, expected 0)
Overloads are:
 - Reference.new()

  person = Person.new "John"

--------------------------

https://crystal-lang.org/docs/syntax_and_semantics/methods_and_instance_variables.html

Several examples have no initialize with name but still use the name in the Person.new.

Second issue is that the state of the  instance variable as:

person.age #=> 1

but anybody running the code will get a error result as

--------------------

crystal test.cr
Error in test.cr:29: undefined method 'age' for Person

 puts person.age #=> 1
             ^~~

Rerun with --error-trace to show a complete error trace.

--------------

**Comment by monouser7dig** [comment]
if you can take a quick look [here](https://guides.github.com/features/mastering-markdown/) and update the code with 

` ``` `
code goes here
` ``` `


this would make it much more pleasant to read

**Comment by Wulfklaue** [comment]
Fixed.

Sorry about that. The editor here only used double `` when inserting code, instead of the six needed.

**Comment by monouser7dig** [comment]
as far as I understand you points you've got two issues

1. you call `person.age` but `@age` does not have a `getter` or `property` and thus is not accessible and gives an error

2. 
```crystal 
def initialize(@name : String)
end

#is equivalent to

@name : String = "not yet initialized, just dummy"
def initialize(name : String)
   @name = name
end

```

**Comment by Wulfklaue** [comment]
Those are not really my issues but the site documentation showing errors:

Using the incorrect Person.new "name" when it needed to be without the name ( to match the example code ). 

The second issue being  that the @age property is showing on each line of the documentation ( so people know the value ) but its dead code that will result in a compile error. It will confuse new users (like me). Technically it needed to be shown as a pure comment, not a exposed function>

Example:

# person.age is now 1

I will fix them in a week or two and make put a pull request when i am back from vacation (currently trying things on a tablet and its slow and frustrating).

**Comment by Sija** [comment]
@Wulfklaue that's incorrect, 1st [example](https://crystal-lang.org/docs/syntax_and_semantics/methods_and_instance_variables.html) shows `@age` getter, see below:

```cr
class Person
  def initialize(@name : String)
    @age = 0
  end

  def age
    @age
  end
end
```

**Comment by Wulfklaue** [comment]
https://crystal-lang.org/docs/syntax_and_semantics/overloading.html

Sorry, had the wrong page linked. See the above link. This issue was in the Overloading section.

**Comment by asterite** [comment]
The examples aren't always self-contained. You should be able to make the code compile by combining code from other examples.

In any case, this should be reported in https://github.com/crystal-lang/crystal-book
