### ISSUE TITLE
Bash on Windows -- Webserver example -- Include solution

### ISSUE THREAD

**Issue by Wulfklaue** [crystal-lang/crystal#5078]
Basic Windows 10 WSL installation has issue when trying out the WebServer demo from the website

-------------------
```
crystal webserver.cr
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
/usr/bin/ld: cannot find -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc "${@}" -o '/root/.cache/crystal/crystal-run-webserver.tmp'  -rdynamic  -lz `command -v pkg
-config > /dev/null && pkg-config --libs libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs libcrypt
o || printf %s '-lcrypto'` -lpcre -lm -lgc -lpthread /opt/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
```
-------------------------

```
# A very basic HTTP server
require "http/server"

server = HTTP::Server.new(8080) do |context|
  context.response.content_type = "text/plain"
  context.response.print "Hello world, got #{context.request.path}!"
end

puts "Listening on http://127.0.0.1:8080"
server.listen
```

------------------------------

https://crystal-lang.org/docs/installation/on_bash_on_ubuntu_on_windows.html

------------------------------

Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1

-------------------

**Solution:**

Ensure that people also install the  libssl-dev package and not only the clang binutils packages.

sudo apt-get install libssl-dev

**Comment by monouser7dig** [comment]
[can you maybe make a pull request here?](https://github.com/crystal-lang/crystal-book/blob/master/installation/on_bash_on_ubuntu_on_windows.md)

I think this will be appreciated

**Comment by Wulfklaue** [comment]
No problem. I'll fix and make pull requests for this issue ( Found a bunch more when trying the examples from the documentation ) and others in 2 weeks when i am at  proper computer.

**Comment by Sija** [comment]
@Wulfklaue please, use triple bakcticks (```) when inserting output from the terminal, otherwise you're making life harder for anyone trying to read it (and help you).

**Comment by RX14** [comment]
Closing this, because it's related to crystal-book (wrong repo)
