### ISSUE TITLE
tooling: --help option for crystal docs

### ISSUE THREAD

**Issue by scriptnull** [crystal-lang/crystal#5087]
I am very new to crystal and have been playing around with the tools.

Almost all the crystal commands have a `--help` option to help the user to understand its purpose better. But the `crystal docs` command does not seem to have one. 

![image](https://user-images.githubusercontent.com/4211715/31310527-4f332070-abb7-11e7-9d26-b6ca065491d4.png)

I think it would be better to have some help for it like below.
```
$ crystal docs
Usage: crystal docs [Options] [file]

Options:
    -h, --help      Show this message
```

In this way, it would be easy for adding new options and documenting them in future. (Right now `crystal docs` has no options, I suppose)

**Comment by straight-shoota** [comment]
#4937 includes a `--help` option.
But we should keep this issue open until it gets merged.

**Comment by asterite** [comment]
#4937 got merged so this is fixed now
