### ISSUE TITLE
tooling: --dest option for crystal docs

### ISSUE THREAD

**Issue by scriptnull** [crystal-lang/crystal#5088]
Currently `crystal docs` command generates all the documentation in a folder called `doc`

But, a user might want the docs to be generated at any location. In my case, I am using github pages to host my docs. So, I would typically want the docs to be under a `docs` folder instead of `doc`. Because github has an option to use `docs` folder in `master` branch to be hosted in the project page.

![image](https://user-images.githubusercontent.com/4211715/31310867-7539aa18-abbd-11e7-92c7-644cd7b06bd4.png)

In order to get generate docs everytime and move it to the docs folder, I am using a `Makefile` as a work around here.

```Makefile
.PHONY: docs


docs:
	@crystal docs
	@mv doc/ docs/
```

So, I propose a `--dest` option to be added in `crystal docs` which will be an option for mentioning the destination of the docs.

```bash
$ crystal docs --dest docs/
```

- [ ] Both relative and absolute paths should be allowed in --dest option.
- [ ] usage of --dest option should be showed via --help option after the implementation of https://github.com/crystal-lang/crystal/issues/5087

**Comment by bew** [comment]
Duplicate of #4918

**Comment by scriptnull** [comment]
Oops. I didn't notice the issue 😅 

Thanks, @bew for notifying! I am closing this thread since an active effort for getting this implemented is going on.

**Comment by xfbs** [comment]
In case someone finds this thread via search: this feature is already implemented:

```bash
crystal docs --output=/some/other/folder
```
