### ISSUE TITLE
No gmp linkage in Homebrew

### ISSUE THREAD

**Issue by ilovezfs** [crystal-lang/crystal#5089]
I noticed that the `crystal-lang` formula in Homebrew depends on `gmp`, but that nothing it installs ends up linked to `gmp`. Is this a bug? Should we drop the `gmp` dependency? Or is there something that needs to be done to get it to use `gmp`?

CC @asterite 

Here is the linkage situation in detail:
```
iMac-TMP:homebrew-core joe$ brew linkage crystal-lang
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libc++abi.dylib
  /usr/lib/libiconv.2.dylib
  /usr/lib/libncurses.5.4.dylib
  /usr/lib/libpcre.0.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/bdw-gc/lib/libgc.1.dylib (bdw-gc)
  /usr/local/opt/libevent/lib/libevent-2.1.6.dylib (libevent)
  /usr/local/opt/libyaml/lib/libyaml-0.2.dylib (libyaml)
  /usr/local/opt/llvm@4/lib/libc++.1.dylib (llvm@4)
  /usr/local/opt/pcre/lib/libpcre.1.dylib (pcre)
Dependencies with no linkage:
  gmp
iMac-TMP:homebrew-core joe$ brew linkage --reverse crystal-lang
/usr/lib/libSystem.B.dylib
  bin/crystal
  bin/shards

/usr/lib/libc++abi.dylib
  bin/crystal

/usr/lib/libiconv.2.dylib
  bin/crystal
  bin/shards

/usr/lib/libncurses.5.4.dylib
  bin/crystal

/usr/lib/libpcre.0.dylib
  bin/shards

/usr/lib/libz.1.dylib
  bin/crystal

/usr/local/opt/bdw-gc/lib/libgc.1.dylib
  bin/crystal
  bin/shards

/usr/local/opt/libevent/lib/libevent-2.1.6.dylib
  bin/crystal
  bin/shards

/usr/local/opt/libyaml/lib/libyaml-0.2.dylib
  bin/shards

/usr/local/opt/llvm@4/lib/libc++.1.dylib
  bin/crystal

/usr/local/opt/pcre/lib/libpcre.1.dylib
  bin/crystal
iMac-TMP:homebrew-core joe$
```

**Comment by Sija** [comment]
As far as I understand GMP is needed for big number family (`BigInt`, `BigFloat`, `BigRational`) to work.

**Comment by ilovezfs** [comment]
OK then we need to figure out why it's not getting linked at all.

**Comment by kostya** [comment]
because compiler itself not use big math, but can compile program that would use it.

**Comment by ilovezfs** [comment]
How will it know where to find it? In a non-default prefix (i.e. /usr/local) it will have no idea where to look.

**Comment by ilovezfs** [comment]
Going to remove the dependency. Anyone who needs gmp can install it themselves.

**Comment by ysbaddaden** [comment]
@ilovezfs you broke our CI :'(

**Comment by bcardiff** [comment]
@ilovezfs could that change be reverted? 

It would be better for users of the crystal-lang formula to be able to use the whole std without trouble.

Supporting non default prefix would be good. But to solve that we should search for an alternative that does not reduce the existing supported scenarios. I'm not sure if that means just improving docs or if there is some artifact we can rely on.

**Comment by waj** [comment]
> How will it know where to find it? In a non-default prefix (i.e. not /usr/local) it will have no idea where to look.

I don't truly understand how it works, but in my machine when I link with `-lgmp` it perfectly finds the library in `/usr/local/opt/gmp/lib/`. Maybe I have set some environment variable I don't remember? @ilovezfs can you help me understand why it links with the library without any extra information?

**Comment by RX14** [comment]
There's plenty of things in the stdlib which require external libraries: XML, yaml, openssl. How do we decide which ones we want to depend on, and which ones we don't want to bundle.

**Comment by ilovezfs** [comment]
@waj it's because /usr/local/lib is part of the default search path. If you `brew unlink gmp` or if you use any HOMEBREW_PREFIX other than /usr/local, then it won't be able to find gmp.

**Comment by ilovezfs** [comment]
>@ilovezfs could that change be reverted?

@bcardiff Sure. https://github.com/Homebrew/homebrew-core/pull/19370

**Comment by ilovezfs** [comment]
@bcardiff @ysbaddaden your CI should be working again now.

**Comment by bcardiff** [comment]
Thanks @ilovezfs . I am sorry you went back and forth on this. Hopefully we should improve how the formula states / uses the dependencies.

**Comment by ilovezfs** [comment]
>Thanks @ilovezfs.

You're welcome!

>I am sorry you went back and forth on this.

No worries.

>Hopefully we should improve how the formula states / uses the dependencies.

Given what @RX14 said above, should we also be adding dependencies for XML/yaml/openssl/etc.? I'm still not clear why gmp is different from any of the rest.

>Supporting non default prefix would be good. But to solve that we should search for an alternative that does not reduce the existing supported scenarios. I'm not sure if that means just improving docs or if there is some artifact we can rely on.

How do you tell crystal about the location of libraries not in the default search path?

**Comment by RX14** [comment]
@ilovezfs we use the stadard system linker `cc`, so the normal way using `LD_LIBRARY_PATH`, probably set in some kind of wrapper script.

**Comment by ilovezfs** [comment]
@RX14 due to SIP `DYLD_LIBRARY_PATH` is a thing of the distant past on macOS, so that isn't an answer.

**Comment by asterite** [comment]
My thought is that if someone wants to use a non-default prefix, then it should use a non-default installer. It's fine for me if Crystal from homebrew just works for those who don't mess with the default configuration.

Another idea would be to remove all code from the standard library that depends on C libraries like `libxml2` and `libyaml`, and move them to shards. Then we can remove that from homebrew too.

**Comment by ilovezfs** [comment]
>My thought is that if someone wants to use a non-default prefix, then it should use a non-default installer.

It's usually a question of not having write access to /usr/local as opposed to something the user "wants."

**Comment by ilovezfs** [comment]
(Also, depending on the default search path to always include /usr/local/lib forevermore leaves crystal pretty vulnerable to breaking at Apple's whim.)

**Comment by asterite** [comment]
There's no way to tell Crystal about libraries not in the default search path, so I wouldn't worry about this for now.

**Comment by ilovezfs** [comment]
That also means no keg_only libraries are available to crystal, and it will always have to work with the latest versions because it will not be able to resort to any keg_only versioned formulae.
