### ISSUE TITLE
Allow method overloading via block type

### ISSUE THREAD

**Issue by Brusalk** [crystal-lang/crystal#5090]
It appears that when creating method overloads, you cannot solely use the type of a block as the differentiation for the block. This seems very strange to me, as the type of the block being used is either explicitly specified in the method definition's arguments, or inferred from usage of yield within the method. (CC: https://stackoverflow.com/questions/46617453/capturing-blocks-with-multiple-allowed-types-signatures)

It seems to me that the type of the block should be able to be used as the _sole_ differentiator when defining method overloads.

As an example, consider the following reduced example:
```crystal
alias IoBlockFormatter = Severity, Time, String, String, IO -> Nil
alias StringBlockFormatter = Severity, Time, String, String -> String

class Formatter
  def initialize(@io : IO, &@formatter : IoBlockFormatter)
  end

  def initialize(@io : IO, &@formatter : StringBlockFormatter)
  end

  def format(severity, time, progname, message)
    case @formatter
    when IoBlockFormatter
      @formatter.call(severity, time, progname, message, @io)
    when StringBlockFormatter
      @io << @formatter.call(severity, time, progname, message)
    end
  end
end
```

The intention here is to allow the `Formatter` class to accept either type of formatting block, and it'll handle the specifics of formatting the message. While this example is somewhat contrived, I think it illustrates my feelings that this behavior is unexpected and counter-intuitive.

I assumed that the type restriction behavior for blocks and arguments (which are both a part of the signature of a method) would behave the same when it comes to overloading.

This proposal is to allow blocks to be the sole differentiating type restriction for method overloading.

**Comment by faustinoaq** [comment]
Hui @Brusalk try this:

```crystal
alias Severity = String
alias IoBlockFormatter = Severity, Time, String, String, IO -> Nil
alias StringBlockFormatter = Severity, Time, String, String -> String

class Formatter
  def initialize(@io : IO, @formatter : IoBlockFormatter)
  end

  def initialize(@io : IO, @formatter : StringBlockFormatter)
  end

  def format(severity, time, progname, message)
    case formatter = @formatter
    when IoBlockFormatter
      formatter.call(severity, time, progname, message, @io)
    when StringBlockFormatter
      @io << formatter.call(severity, time, progname, message)
    end
  end
end

io = IO::Memory.new

f1 = Formatter.new io, -> (s : Severity, t : Time, a : String, b : String, i : IO) do
  puts "I'm IoBlockFormatter"
end

f2 = Formatter.new io, -> (s : Severity, t : Time, a : String, b : String) do
  puts "I'm StringBlockFormatter"
  return "StringBlockFormatter"
end

f1.format("error", Time.new, "foo", "bar")
f2.format("error", Time.new, "foo", "bar")
```

https://carc.in/#/r/2vg3

**Comment by RX14** [comment]
This isn't possible. Because block arguments are typed by the method that uses `yield`, you need to find the method before you look at the block, which means block arguments cannot be used to find the method. It would be technically possible to determine the method based on the *number* of block arguments, but that'd require removing the ability to skip block arguments (currently `yield 1, 2, 3` with a block `{ |x, y| puts "#{x}, #{y}" }` works and prints `1, 2`). It'd also be quite confusing, since overloading currently works with both args length and args type, whereas this overloading would only work with length.

**Comment by Brusalk** [comment]
@RX14 Thanks for the explanation! That makes sense :)

Could we add explicit typing to blocks as an option, to allow this syntax then?
## Long Form
### Type restrict arguments
```crystal
f1 = Formatter.new(io) do | s : Severity, t : Time, a : String, b : String, i : IO | : String
  "#{s} #{a} | #{b}"
end
```
### Type the block itself
```crystal
f1 = Formatter.new(io) do | s, t, a, b, i | : Severity, Time, String, String, IO -> String
  "#{s} #{a} | #{b}"
end
```

## Short Form
### Type restrict arguments
```crystal
f1 = Formatter.new(io) { | s : Severity, t : Time, a : String, b : String, i : IO | : String "#{s} #{a} | #{b}" }
```
or 
### Type the block itself
```crystal
f1 = Formatter.new(io) { | s, t, a, b, i | : Severity, Time, String, String, IO -> String "#{s} #{a} | #{b}" }
```

This would tell the compiler the exact argument types that the block expects, and would allow it to be used with method overloading as it doesn't have to determine types from usage, similar to how we can either let the compiler infer types or explicitly set them for other things like function arguments and variables.

## With Aliased Proc Type
```crystal
alias IOBlockFormatter = Severity, Time, String, String, IO -> String
f1 = Formatter.new(io) do | s, t, a, b, i | : IOBlockFormatter
  "#{s} #{a} | #{b}"
end
f2 = Formatter.new(io) { | s, t, a, b, i | : IOBlockFormatter "#{s} #{a} | #{b}" }
```

## Inferred Block Return Type
Additionally, I'd naively think it'd be possible to infer the return type of the block by inferring it from the block itself, since all variables would be typed at declaration time (or inferrable). This'd make the syntax a lot nicer looking
### Type restrict arguments
```crystal
f1 = Formatter.new(io) do | s : Severity, t : Time, a : String, b : String, i : IO |
  "#{s} #{a} | #{b}"
end
```
```crystal
f1 = Formatter.new(io) { | s : Severity, t : Time, a : String, b : String, i : IO | "#{s} #{a} | #{b}" }
```
### Type the block itself
```crystal
f1 = Formatter.new(io) do | s, t, a, b, i | : Severity, Time, String, String, IO
  "#{s} #{a} | #{b}"
end
```
```crystal
f1 = Formatter.new(io) { | s, t, a, b, i | : Severity, Time, String, String, IO  "#{s} #{a} | #{b}" }
```

Thoughts?

**Comment by Brusalk** [comment]
I mean.. yes, that'll work, but that's kind of besides the point. 

The issue here isn't that it's _impossible_ to handle multiple block-types in one class, but that it's impossible to handle multiple block types with _one_ method (which you'd have to do via overloading).

I totally understand if adding new syntax is a big step, but it's the only way I can see forward on this particular issue, unless someone smarter than me has better ideas :)

I opened this issue, because it seems wrong to me (from a very basic level) that type restrictions in a method's argument list should be overloadable. The fact that blocks can't is understandable from a technical PoV, but weird from a 1000 ft perspective.

**Comment by RX14** [comment]
I don't think we *need* to move forward on this particular issue. Maybe the other core team members have some input but i'd vote to close this.

**Comment by ysbaddaden** [comment]
Block arguments are defined by the method that yields, not by how the method is called; the caller may skip some arguments that it doesn't need; but the yielding method can't behave differently depending on the block.

I believe lambdas already cover this, and your suggestions already apply to them. Since you are capturing the block for later use, in your initial example, I believe using a lambda is a better solution than trying to type block arguments. See https://github.com/crystal-lang/crystal/blob/master/src/logger.cr#L93 for example.

I don't think we'll ever change this.

**Comment by asterite** [comment]
Blocks and procs are a mess in the language, let's not make them every more messier.
