### ISSUE TITLE
A compiler bug with typeof(nil.not_nil!.foo)

### ISSUE THREAD

**Issue by jbomanson** [crystal-lang/crystal#5105]
The code

```crystal
typeof(nil.not_nil!.foo)
```

gives a compiler error of the form

```
BUG: `typeof(nil.not_nil!
)` at play:1:1 has no type
```

The method name `foo` does not seem to matter.
I am running `Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1`.

**Comment by straight-shoota** [comment]
Well it makes sense that it complains about calling `not_nil!` on a value that can't be anything else than `nil`.
However this shouldn't be labeled as a compiler bug because it is simply a invalid code.

**Comment by RX14** [comment]
Yes, this is *absolutely* a compiler bug because we get an internal compiler exception instead of a nice error message.

**Comment by asterite** [comment]
This is actually working well in master (not crashing the compiler)

**Comment by asterite** [comment]
Ah, no, doing `p typeof(...)` doesn't crash it.
