### ISSUE TITLE
TCPSocket.new doesn't keep connection open

### ISSUE THREAD

**Issue by martinos** [crystal-lang/crystal#5128]
If I run a `netcat` server on my computer:

```bash
nc -l 1234
```

And I start a tcp socket in `icr`

```crystal
require "socket"
client = TCPSocket.new("localhost", 1234)
#  => #<TCPSocket:fd 8>
```
The `netcat` programs exits right after I instanciate the client. 

If I relaunch the `netcat` server and I send a message to it using the same socket in `icr` the message gets printed on the server but it exits.

```
icr(0.23.1) > client.puts "1"
 => nil
```

```
$ nc -l 1234
1
```

If I rerun the netcat server and I send a message from the client. The previous message and the new one get printed on the server's STDOUT.

```
icr(0.23.1) > client.puts "2"
 
```

```bash
$ nc -l 1234
1
2
```

Maybe this is the intended behaviour but it behaves differently that Ruby's library.

If this is the intended behaviour, what should I do to keep the connection alive?

I am on OS X 10.12.6

```
Darwin MacBook-Pro-4 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

And my crystal version is:
```
Crystal 0.23.1 (2017-10-12) LLVM 4.0.1
```

**Comment by martinos** [comment]
I just realized that the issue is only on `icr`. Anyone knows might have an idea why `icr` is breaking the connection?

**Comment by petoem** [comment]
This is because of how `icr` works. 
> * Every time you press `Enter` it adds new instruction, generates new crystal program and executes it.
> * The output is split into 2 parts: regular program output (e.g. output from `puts 10`) and value returned by the last command
> * The regular output is saved, and when you type a new instruction, new program is generated. The saved output is subtracted from the new output, and the difference is printed out. It makes an illusion that only new instructions are executed :)

> Source: https://github.com/crystal-community/icr#how-does-it-work

**Comment by martinos** [comment]
Thanks a a lot, this is much appreciated. I think I can close this issue

**Comment by RX14** [comment]
This is why i strongly dislike suggesting icr to users, sometimes they don't realise that icr isn't a real repl, it's a hack. And perhaps they get a bad impression of crystal being buggy because someone wanted to hack together a repl.

**Comment by martinos** [comment]
Completely agree, i think that lots of people that are trying icr for the
first time are losing tons of time (like me) and also people that are
helping newbies.  I think that this program should display a big warning at
start time.  I have lost at least 5hrs on that problem.

Le dim. 15 oct. 2017 à 13:55, Chris Hobbs <notifications@github.com> a
écrit :
