### ISSUE TITLE
Unable to compare named tuple union type

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#5131]
Comparing a NamedTuple with a UnionType of NamedTuple types fails because the union type seems to match NamedTuple in `NamedTuple#==(other : NamedTuple)`, but does not respond to `keys` method used in the macro code of `NamedTuple#compare_with_other_named_tuple`.

Example:
```crystal
[{bar: nil}, {foo: nil}] == [{bar: nil}, {foo: nil}]
```
[carc.in](https://carc.in/#/r/2wy8)

The above code fails with
```
in /usr/lib/crystal/named_tuple.cr:459: undefined method 'keys' for TypeNode of type (NamedTuple(bar: Nil) | NamedTuple(foo: Nil)) (must be a named tuple type)

    {% if T.keys.sort == U.keys.sort %}
```

Same result for 0.23.1 and master.

**Comment by asterite** [comment]
How did you get a union of named tuples? What's the use case?

**Comment by straight-shoota** [comment]
Thanks for the quick fix =)

My use case was actually experimenting with a way to use named tuples instead of `Tuple(Symbol, X)` for a list of parser tokens.
