### ISSUE TITLE
[RFC] HTTP::Client: post/put/etc. form using required named argument

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#5136]
Right now for posting a form using HTTP::Client we have to do:

```crystal
require "http/client"

HTTP::Client.post_form("http://...", "x=1&y=2")
```

The second parameter, the form, can be a string, an IO or a Hash. Variants for an HTTP::Client instance also exist.

Since we have required named arguments, why don't we change that to be:

```crystal
require "http/client"

HTTP::Client.post("http://...", form: "x=1&y=2")
```

It's practically the same to type, but maybe nicer. And we could also just have this required `form` arguments for all variants of the HTTP method (get, delete, etc.), because the HTTP protocol does support that (even though it's probably not recommended or common).

Thoughts?

**Comment by straight-shoota** [comment]
There is also the `body:` parameter (for all methods), which is used in the same way.
So they are nearly the same with the only difference between
```crystal
HTTP::Client.post("http://...", body: "x=1&y=2")
```
and
```crystal
HTTP::Client.post("http://...", form: "x=1&y=2")
```
that the latter sets `Content-type: application/x-www-form-urlencoded`.
Allowed type are (currently)
* for `body`: `IO | Byte | String | Nil` 
* for `form`: `String | IO | Hash(String, _)`
