### ISSUE TITLE
Question: How is the right way to use bitwise and operator &

### ISSUE THREAD

**Issue by thnery** [crystal-lang/crystal#5140]
Can you help me with this?
I have this piece of code

```crystal
BITS   = [0x10, 0x08, 0x04, 0x02, 0x01]
BASE32 = "0123456789bcdefghjkmnpqrstuvwxyz"

"c216ne".scan(/./) do |c|
    BITS.each do |mask|
        puts "#{BASE32.index(c[0]) & mask}"
    end
end
```
When I run the code I get this exception:
```
undefined method '&' for Nil (compile-time type is (Int32 | Nil))

        puts "#{BASE32.index(c[0]) & mask}"
```

If I try to compare with `&&` instead of `&` it will work, but will not provide the result I want.
I don't really know if it's a but or I am doing something wrong.
Obs: I run the same piece of code in Ruby and it's ok.

**Comment by asterite** [comment]
`String#index` returns Int32 or Nil.  Please read this: https://crystal-lang.org/api/0.23.1/Nil.html

And please don't ask these questions here, use StackOverflow. Thank you!

**Comment by thnery** [comment]
All right, sorry for that!
