### ISSUE TITLE
A Working Raspbian Repository Would be Nice

### ISSUE THREAD

**Issue by HCLarsen** [crystal-lang/crystal#5141]
Everything I find when looking for installing Crystal on my Pi turns to this website: http://public.portalier.com/raspbian/, where the instructions turn up the following errors:

W: GPG error: http://public.portalier.com raspbian/ Release: The following signatures were invalid: BADSIG D5581943005FAF9E Portalier Julien (Debian Packages Sign Key) <julien@portalier.com>
W: The repository 'http://public.portalier.com raspbian/ Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Conflicting distribution: http://public.portalier.com raspbian/ Release (expected raspbian/ but got )

I'm sure I'm not the only Crystalite who'd like to use this on their Pi, so can we work on getting a working repository for Raspbian?

**Comment by ysbaddaden** [comment]
I re-signed the repository again, just in case, but everything is okay in my raspbian (jessie) qemu box.

**Comment by HCLarsen** [comment]
Thank you. Just tried it again, and it works in Stretch too.

Although I did get an odd warning during the update phase:

W: Conflicting distribution: http://public.portalier.com raspbian/ Release (expected raspbian/ but got )
