### ISSUE TITLE
RFC: Make Indexable writeable

### ISSUE THREAD

**Issue by lbguilherme** [crystal-lang/crystal#5142]
Just exposing something that was on my mind: Currently `Indexable` requires `size` and `unsafe_at` to implement several reading operations on the container. Those are the classes that use `Indexable` now:

    Array(T)   BitArray   Deque(T)   Slice(T)   StaticArray(T, N)   Tuple(*T)

From those, Array, BitArray and Deque are always writeable, Slice and StaticArray are some times writeable (unsafe), Tuple is always read-only. So, Indexable assumes a read-only container and each one of them is responsible for the write operations they want.

Some operations are implementable on all writable indexable: sort, fill, shuffle, update, swap. It would be nice to either offer those operations directly in Indexable itself (bad for Tuple), or create another module for WritableIndexable (maybe with better name), so that all containers can benefit from these functions. This way Array would have less specific things.

Btw, with this change there would be almost no reason to keep Array at all, Deque could be renamed to "Array" as it is at most as fast as Array, and is sometimes faster.

**Comment by lbguilherme** [comment]
Ooops, just noted @asterite's comment on https://github.com/crystal-lang/crystal/issues/5126#issuecomment-337566280

**Comment by monouser7dig** [comment]
related [from iRC](https://gitter.im/crystal-lang/crystal?at=59d94a2ab59d55b8238562f9)

> <oprypin> it is true that sort! and rotate! can be implemented on Indexable and that needs to be brought up

**Comment by Papierkorb** [comment]
Crystal touts itself to be type-safe. This also means that checks are done as early as possible (Best case: Compile-time).  If something can't be writable, it shouldn't expose the methods for it.  This is one of the many things that simply suck in dynamic languages.  That `Slice` is using a run-time check is already a defect.

Overall, exposing methods that don't yell at you *at compile time* is simply bad design, and nothing else.

What we could do, and this would actually be a nice thing, would be to have `ReadOnlyIndexable` and `Indexable` (for read/write).  `Indexable` would then simply `include ReadOnlyIndexable(T)`.  I'd choose it this way around to make it easier to read, as a read/write container *is* more common than a read-only one.

**Comment by lbguilherme** [comment]
Just to be clear, I don't think anymore that it would be a good idea to merge Deque and Array. But that doesn't change the core of this issue, about Indexable.

I like having `ReadOnlyIndexable` and `Indexable` as @Papierkorb suggested. If there is nothing against it, I'll follow up with a PR.

**Comment by straight-shoota** [comment]
Considering that the current collection modules `Enumerable` and `Indexable` provide a read-only interface, it might be favourable to keep it that way and introduce new mutable modules, maybe `Enumerable::Mutable` and `Indexable::Mutable`?

**Comment by HertzDevil** [comment]
The minimal interface is:

```crystal
module Indexable::Mutable(T)
  # this means there are no write-only but unreadable `Indexable`s
  include Indexable(T)

  # mutating dual of `#unsafe_fetch`
  # not a true setter, so this isn't required to return *value*
  abstract def unsafe_put(index : Int, value : T)

  def put(index : Int, value : T) : T
    index += size if index < 0
    raise IndexError.new unless 0 <= index < size
    unsafe_put(index, value)
  end
end
```

This is probably sufficient for all the mutating methods included in the OP, including `#sort!` and its variants.

Resizable containers are a different story; for that matter, there are no standard library containers whose size can be increased arbitrarily.
