### ISSUE TITLE
Tail call optimisation fails

### ISSUE THREAD

**Issue by Sag0Sag0** [crystal-lang/crystal#5143]
```
def test(i)
  puts i
  test(i + 1)
end

test(0)
```

This code exits just after it prints 65517 with the error `Invalid memory access (signal 11) at address 0x7fff534cbfd8`

`crystal -v` outputs `Crystal 0.23.1 (2017-10-12) LLVM 4.0.1`.
I compiled it using the command `crystal run --release test.cr` on MacOS.

Any ideas?

**Comment by RX14** [comment]
I doubt llvm will perform tco outside of release mode, and even then I wouldn't rely on it. So effectively crystal has no tco because the tco is meant for saving cycles (and therefore based on heuristics), not for avoiding busting the stack.

**Comment by asterite** [comment]
Right, tail call optimization is not guaranteed. I can't remember where this was answered already. I also found https://github.com/crystal-lang/crystal/issues/2021

**Comment by RX14** [comment]
I think eventually we'll end up giving harder guarantees that tco always happens so people can write recursive algorithms without fear, but for now it doesn't happen. And I wouldn't put it high on the todo list to research or implement.

**Comment by asterite** [comment]
Closing, as tail call optimization is not a priority right now, and it's not needed for correct behavior.
