### ISSUE TITLE
Time#days_in_year in the time.cr

### ISSUE THREAD

**Issue by coderhs** [crystal-lang/crystal#5157]
I was looking through the code and found that the core time library has a method for `days_in_month`, I would like to propose we add `days_in_year` as well so as to make the system complete. I feel it would be useful, as it is there in the active support in rails, which would now also be in the ruby core from 2.5

If everyone is fine with this suggestion, then I would love to send the PR for it.

**Comment by asterite** [comment]
@coderhs Sounds like something useful! If you send a PR we'll surely accept it after review.

**Comment by coderhs** [comment]
Thank you. I will send a PR for it. I was writing the spec for that method, when i find that there is no spec for `days_in_month` method as well.

Do you mind if I add a spec for that as well, in this PR? Just to keep it tested, but I other functions are calling this method and its indirectly being tested.

**Comment by coderhs** [comment]
@asterite let me know if adding unit test for `Time#days_in_month` is welcomed? I couldn't find any unit test for it in the spec. But `at_end_of_month` is being tested which uses `days_in_month` to get the result so indirectly we are testing that method.

**Comment by RX14** [comment]
I think it's fine to add those extra specs as a seperate commit in this or

**Comment by coderhs** [comment]
@RX14 I have included the test for `days_in_month` along in the same pr. #5163 Also code example for that method.

**Comment by asterite** [comment]
Fixed by #5163
