### ISSUE TITLE
Parameters argument in HTTP get requests

### ISSUE THREAD

**Issue by HCLarsen** [crystal-lang/crystal#5160]
Originally suggested by @RX14 in a separate PR.

Currently, parameters need to be added to an HTTP::Client#get call with the HTTP::Params#encode method. A much more user-friendly option would be something like this:

```
HTTP::Client.get("http://www.example.com", query_params: {"foo" => "bar"})
```

**Comment by asterite** [comment]
Please, lets not create an issue for every idea anyone has in comments.

Can we start using Google Groups to discuss these things? There's no point in cluttering the repo with issues like these, specially when they are not a problem (one can achieve **the same thing** with different code).

**Comment by HCLarsen** [comment]
I don't use Google Groups, so that's not an option. Where should I bring it up to discuss it with the core team?

**Comment by asterite** [comment]
Create a Google Groups account? One could also say "I don't use GitHub, where can I submit issues?"

**Comment by HCLarsen** [comment]
I have no desire to use Google Groups, or any other Google product.

**Comment by HCLarsen** [comment]
There's the Gitter chat, is that an ok place to talk about suggestions for the library?

**Comment by RX14** [comment]
@asterite the counter-argument is that it's sensible to keep all suggestions in the same place, where they're easy to manage. Google groups isn't an issue tracker, and it's fairly easy to just keep these kind of issues around on github.
