### ISSUE TITLE
implement  '<=>' for Bool

### ISSUE THREAD

**Issue by rdp** [crystal-lang/crystal#5162]
I sometimes wish to sort by boolean, simplified example:

a = [1,2,3]
a.sort_by{|n| n == 3}

today it yields:  undefined method '<=>' for Bool

Consider this a feature request.  Thanks!

**Comment by mvlootman** [comment]
Just wondering what the use case for this would be?
Would the [partition](https://crystal-lang.org/api/0.23.1/Enumerable.html#partition%28%26block%29-instance-method) method be a way to separate the items based on the boolean expression?

**Comment by Sija** [comment]
@rdp you can monkey-patch `Bool` urself:

```cr
struct Bool
  def <=>(other)
    self == other ? 0 : -1
  end
end
```

**Comment by rdp** [comment]
Nice! Yeah partition would work, in my case I just want to send elements with a certain attribute to the "end" or "beginning" of an array.  @Sija thanks, yeah having it in core would be kind... :)

**Comment by RX14** [comment]
Boolean doesn't have a natural ordering... Is true less than false? No, it's not. I think this is a terrible idea.

You're using sort_by anyway, you can just use `sort_by { |n| n == 3 ? -1 : 1 }` or the other way around if you want the other sort direction.

**Comment by rdp** [comment]
It's not hard to imagine "some arbitrary order" (true == 1, false == 1) by default and just let that (thus avoiding the ternary's) but if it's too contentious hopefully people will be able to find this and just use Sija's work around now.  Thanks all!

**Comment by rdp** [comment]
OK I had some difficulty getting the snippet above to work, but this seems to do the trick, instead of just clumping "trues and falses together" regardless of which one is which:

```
struct Bool
  def <=>(other : Bool)
    if self == other
      return 0
    elsif self
      return 1
    else
      return -1
    end
  end
end

```
