### ISSUE TITLE
Discuss: Determines monospace(unicode) display width of a string

### ISSUE THREAD

**Issue by icyleaf** [crystal-lang/crystal#5164]
Crystal was built-in size and byte size in String, why not add monospace(unicode) display width, it's better in terminal and other usage.

Examples:

```
hello | size: 5, bytesize: 5, display width: 5
你好 | size: 2, bytesize: 6, display width: 4
ｈｅｌｌｏ | size: 5, bytesize: 15, display width: 10
здравствуйте | size: 12, bytesize: 24, display width: 12
namasté | size: 7, bytesize: 8, display width: 7
márħaban | size: 8, bytesize: 10, display width: 8
여보세요 | size: 4, bytesize: 12, display width: 8
おはよう | size: 4, bytesize: 12, display width: 8
مرحبًا | size: 6, bytesize: 12, display width: 5
здравствуйте | size: 12, bytesize: 24, display width: 12
```

terminal display width:

```
+-----+
|hello|
+-----+
+----+
|你好|
+----+
+----------+
|ｈｅｌｌｏ|
+----------+
+------------+
|здравствуйте|
+------------+
+-------+
|namasté|
+-------+
+--------+
|márħaban|
+--------+
+--------+
|여보세요|
+--------+
+--------+
|おはよう|
+--------+
+-----+
|مرحبًا|
+-----+
+------------+
|здравствуйте|
+------------+
```

Ruby implementations:

- [unicode-display_width](https://github.com/janlelis/unicode-display_width)
- [unicode-emoji](https://github.com/janlelis/unicode-emoji)

**Comment by RX14** [comment]
Sounds like a shard idea to me. Perhaps a bit heavy for the stdlib.

**Comment by MakeNowJust** [comment]
However this causes real problem, in `crystal tool context` for example:

![2017-10-23 18 19 38](https://user-images.githubusercontent.com/6679325/31881560-e5946312-b81e-11e7-9d6c-3bd71c275e50.png)

Japanese (`bytes != display_width`) named variable breaks table column.

**Comment by icyleaf** [comment]
It was affect all CJK languages.

**Comment by Sija** [comment]
Couldn't we use libc's [wcswidth()](http://man7.org/linux/man-pages/man3/wcswidth.3.html) function for that?

**Comment by asterite** [comment]
I'm also not sure this belongs to the standard library, despite that fact that some tools won't work well (well, they work well, you just get a display that's not nice, but it's still easy to understand). But if `wcswidth` is portable we could use it (I don't know if that works well, though, there doesn't seem to be a standard way to know the width of a char).

**Comment by icyleaf** [comment]
Golang has a text library, and support width: https://github.com/golang/text/blob/master/width/width.go#L139

**Comment by asterite** [comment]
Yes, a library. It's not in the standard library.

**Comment by icyleaf** [comment]
You are right. Maybe make a shard is best choice.

**Comment by RX14** [comment]
We can always import it later from a shard if required.
