### ISSUE TITLE
Map with union Issue (compilation failed)

### ISSUE THREAD

**Issue by anykeyh** [crystal-lang/crystal#5165]
This code fail to compile:

```crystal
require "db"
require "big_int"
require "big_float"

class Test
  alias Values = DB::Any | BigInt | BigFloat | Time
  alias ArrayItem = Hash(String, Values) | String

  @values : Array(ArrayItem) = [] of ArrayItem

  def set(item : ArrayItem)
    @values << item
    self
  end

  def print_values : String
    @values.map { |x| "Bug occurs here" }.join(" ")
  end
end

pp Test.new.set({"b" => 2}).print_values
```

The error says:

`argument #1 of yield expected to be (Hash(String, BigFloat | BigInt | Bool | Float32 | Float64 | Int32 | Int64 | Slice(UInt8) | String | Time | Nil) | String), not (Hash(String, BigFloat | BigInt | Bool | Float32 | Float64 | Int32 | Int64 | Slice(UInt8) | String | Time | Nil) | Hash(String, Int32) | String)`

The problem is I add in the array a `Hash(String, Int32)`, but on the `map` time, it fail to understand that this type of Hash is a subset of the `Hash(String, Values)`.

It's not blocking, as I can do `Hash(String, Values).new.merge(item)` in `set` method, but I think it's not a normal behavior, as it's inconsistent between the `Array#<<` (working, should not?) and `Array#map` (not working, should it?).

**Comment by RX14** [comment]
`@values << item` shouldn't be working here since you're trying to add a `Hash(String, Int32)` to an array of `Hash(String, Values)`. These two types have different binary formats so we can't automatically convert between them.

Typically this would fail, what's your `crystal --version` ?

**Comment by anykeyh** [comment]
`Crystal 0.23.1 (2017-10-12) LLVM 4.0.1`

Installed via `brew` on mac.

**Comment by HertzDevil** [comment]
On 1.0.0:

```crystal
require "big"

module DB
  alias Any = Nil | Int32
end

class Test
  alias Values = DB::Any | BigInt | BigFloat | Time
  alias ArrayItem = Hash(String, Values) | String

  @values : Array(ArrayItem) = [] of ArrayItem

  def set(item : ArrayItem)
    @values << item
    self
  end
end

Test.new.set({"b" => 2})
```

```
In /home/quinton/crystal/bug.cr:19:10

 19 | Test.new.set({"b" => 2})
               ^--
Error: instantiating 'Test#set(Hash(String, Int32))'


In /home/quinton/crystal/bug.cr:14:13

 14 | @values << item
              ^-
Error: instantiating 'Array(Hash(String, BigFloat | BigInt | Int32 | Time | Nil) | String)#<<(Hash(String, Int32))'


In src/array.cr:409:5

 409 | push(value)
       ^---
Error: instantiating 'push(Hash(String, Int32))'


In src/array.cr:1451:12

 1451 | @buffer[@size] = value
               ^
Error: instantiating 'Pointer(Hash(String, BigFloat | BigInt | Int32 | Time | Nil) | String)#[]=(Int32, Hash(String, Int32))'


In src/pointer.cr:130:29

 130 | (self + offset).value = value
                               ^----
Error: type must be (Hash(String, BigFloat | BigInt | Int32 | Time | Nil) | String), not Hash(String, Int32)
```

**Comment by asterite** [comment]
I think this can be closed then. Thank you @HertzDevil !
