### ISSUE TITLE
Centos 7 - Compile issues

### ISSUE THREAD

**Issue by puppetpies** [crystal-lang/crystal#5169]
Hi All,

I'm using CentOS 7 and running this version i have noticed this is an EL6 package which raises questions but i used the documentation from here.

https://crystallang.org/docs/installation/on_redhat_and_centos.html

[brian@eggbox crystal-monetdb-libmapi]$ rpm -qi crystal
Name        : crystal
Version     : 0.23.1
Release     : 3.el6
Architecture: x86_64
Install Date: Sat 16 Sep 2017 05:37:52 PM BST
Group       : default
Size        : 62248014
License     : Unspecified
Signature   : RSA/SHA512, Fri 14 Jul 2017 06:43:46 PM BST, Key ID 09617fd37cc06b54
Source RPM  : crystal-0.23.1-3.el6.src.rpm
Build Date  : Thu 13 Jul 2017 07:18:33 PM BST
Build Host  : localhost
Relocations : / 
Packager    : Juan Wajnerman
Vendor      : Omnibus <omnibus@getchef.com>
URL         : http://crystal-lang.org/
Summary     : The full stack of crystal
Description :
The full stack of crystal

So when i try to compile my project crystal-monetdb-libmapi i get this.

crystal build --release quick.cr -o bin/quick
crystal: /var/cache/omnibus/src/llvm/llvm-3.8.1.src/lib/CodeGen/LexicalScopes.cpp:160: llvm::LexicalScope* llvm::LexicalScopes::getOrCreateRegularScope(const llvm::DILocalScope*): Assertion `cast<DISubprogram>(Scope)->describes(MF->getFunction())' failed.
/usr/bin/crystal: line 102: 19983 Aborted                 (core dumped) "$INSTALL_DIR/embedded/bin/crystal" "$@"
make: *** [quick-release] Error 134

Hope i have provided enough information.

Regards,

Brian Hood

**Comment by matiasgarciaisaia** [comment]
Hi @puppetpies!

This is a known issue of Crystal 0.23.1 - we're tracking it on #4719.

As a workaround, adding `--no-debug` as a compilation flag will allow you to compile.

**Comment by puppetpies** [comment]
Cheers man !
