### ISSUE TITLE
Between Method for Comparable Module

### ISSUE THREAD

**Issue by HCLarsen** [crystal-lang/crystal#5171]
Forgive me if this exists, but I looked for it in the documentation and couldn't find anything.

Essentially, something akin to Ruby's between? method for the Comparable module. Shouldn't be hard to implement.

```
def between?(min, max) 
  min <= self && self <= max 
end
```

**Comment by MakeNowJust** [comment]
You could write this as:

```crystal
def between?(min, max) 
  min <= self <= max 
end
```

**Comment by RX14** [comment]
@makenowjust just described exactly why we don't have `between?`. We already have the `min <= obj <= max` syntax, which is more readable and powerful because it can control inclusivity at both ends. I think it's also more beautiful.

**Comment by straight-shoota** [comment]
An alternative is `(min..max).includes?(value)` which means exactly the same as `between?` just with reversed operands.

**Comment by HCLarsen** [comment]
I think it's less readable and less beautiful that way @RX14 , but it's your call.

**Comment by konovod** [comment]
`min` and `max` expressions can be pretty long, `between?` allows to see what value we actually check immediately, other variants somewhat hides it.

**Comment by straight-shoota** [comment]
Using the`<=` operator is much more expressive, easier to understand (inclusive or exclusive range?) and actually shorter:
```crystal
value.between?(min, max)
min <= value <= max
```

**Comment by HCLarsen** [comment]
@straight-shoota I tend to think that using an English word like "between" is  easier to understand than symbols. If we just want to use symbols, why not just write everything in C?

**Comment by konovod** [comment]
@straight-shoota i agree, in most cases. But considering something like
`{0, j - @upper_band}.max <= i <= {nrows - 1, j + @lower_band}.min`
vs
`i.between?({0, j - @upper_band}.max, {nrows - 1, j + @lower_band}.min)`
yes, first case is perhaps cleaner. But in a second case i see `i.between? something something`, and can skip the rest of expression if i'm not checking a limit values but just trying to understand code. In a first case i have to look through expression to find what i actually check. Yes, this is a minor inconvenience and i'm not sure `between?` should be in stdlib as Crystal discourage aliases and this one is, well, an alias.
