### ISSUE TITLE
Formatter error with flat rescue/ensure/else block

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#5175]
#5114 introduced new possibilities to use `rescue`, `ensure` and `else` with blocks but the formatter does not respect all cases correctly.

Example:
```crystal
loop do
  loop do
  ensure
  end
end
```

Gets formatted as:
```crystal
loop do
  loop do

ensure
  end
end
```

/cc @MakeNowJust

**Comment by MakeNowJust** [comment]
No indent for `ensure` may be introduced by me, but empty line between `do` and `ensure` is not by me, for example:

```crystal
class Foo
  def foo
  ensure
  end
end
```

is formatted to:

```crystal
class Foo
  def foo

  ensure
  end
end
```

I'll try to fix this. Thank you @straight-shoota.
