### ISSUE TITLE
Migrate to CircleCI 2.0

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#5182]
https://circleci.com/docs/2.0/migrating-from-1-2/

I think we could benefit from at least Workflow.

**Comment by Sija** [comment]
I think PR should be done by someone at @crystal-lang, yet I'm willing to take a stab at it if needed.

**Comment by asterite** [comment]
What would be the benefit of using Workflow?

**Comment by Sija** [comment]
@asterite testing `shards` along with Crystal `master` for instance.

**Comment by Sija** [comment]
Just FYI: https://circleci.com/blog/sunsetting-1-0/

**Comment by Sija** [comment]
Seems fixed as of Crystal 0.24.2 (#5642).
