### ISSUE TITLE
[RFC] Run specs separately

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#5187]
In a nutshell, modifying global state in some single `_spec.cr` file affects all other specs. It's because the code is loaded once from all files under the `/spec` dir.

### I.e.

I use [mocks.cr](https://github.com/waterlink/mocks.cr) for testing purposes, and I test `HTTP::Server::Response` for receiving a `respond_with_error` call:

```crystal
# some_spec.cr

Mocks.create_mock HTTP::Server::Response do
  mock respond_with_error(message, code)
end
```

I don't want this to have an effect in other specs . 

### RFC

I bet there are other situations when a developer needs to modify global state without touching other specs. An option would be to run each `_spec.cr` file separately one after another or maybe in parallel. Any suggestions?

*Update:* this is how I run tests ATM - `find spec/ -name '*_spec.cr' -exec crystal spec {} \;`

**Comment by RX14** [comment]
Why not just not have global state, or make your global state a thin wrapper over something which *doesn't* have global state so you can test it? Running each spec in a seperate process would be unbearably slow.

**Comment by vladfaust** [comment]
@RX14 please, if you can tell me another way to test if a `HTTP::Server::Response` have received a `#respond_with_error` call, it would be great!

**Comment by RX14** [comment]
@vladfaust by testing the actual response data, instead of a method call. Surely what you care about is the response data generated by the `respond_with_error` call, instead of that method being called in itself.

**Comment by RX14** [comment]
This is veering off into a question instead of a bug/rfc/feature request. I'll close this but let the discussion continue.

**Comment by vladfaust** [comment]
I've found a way (stole from Kemal repo :sweat_smile:):

```crystal
def handle_request(handler, request = Req.new("GET", "/"))
  io = IO::Memory.new
  response = HTTP::Server::Response.new(io)
  context = HTTP::Server::Context.new(request, response)
  handler.call(context)
  response.close
  io.rewind
  HTTP::Client::Response.from_io(io, decompress: false)
end

response = handle_request(callable)
response.body.should eq "ok"
```

But IMO there are still cases where specs should be isolated.
