### ISSUE TITLE
Unexpected behavior of `typeof(self)` restriction

### ISSUE THREAD

**Issue by MakeNowJust** [crystal-lang/crystal#5189]
This example works for now:

```crystal
class Foo
  def self.foo(foo : typeof(self))
    pp typeof(self) # => Class
  end
end

Foo.foo Foo.new
```

It's unexpected behavior because `typeof(self)` inside method body yields `Class` but `typeof(self)` inside argument restriction seems `Foo`.

And also, this doesn't work:

```crystal
class Foo
  def self.foo(foo : typeof(self))
    pp typeof(self) # => Class
  end
end

Foo.foo Foo
# no overload matches 'Foo.foo' with type Foo:Class
# Overloads are:
#   - Foo.foo(foo : typeof(self))
```

This behavior make no sense.

Additionaly, this behavior made me confused in such case:

```crystal
class Foo
  def self.foo(foo : typeof(self.bar))
    pp foo
  end

  def self.bar
    1
  end

  def bar
    :bar
  end
end

Foo.foo 1
# no overload matches 'Foo.foo' with type Int32
# Overloads are:
#  - Foo.foo(foo : typeof(self.bar))
```

In this case, restriction `typeof(self.bar)` is `Int32` beacause `self` in instance of `Foo` and so `self.bar` calls `def bar` not `def self.bar`.

- - -

I guess this behavior comes from `self` type restriction:

```crystal
class Foo
  def self.foo(foo : self)
    pp typeof(self) # => Class
  end
end

Foo.foo Foo.new
```

I think this behavior is right because `self` type restriction is special case of using `self`, we should know about this. However, I expect an expression inside `typeof` evaluate as normal, even if restriction.

**Comment by MakeNowJust** [comment]
Note that this behavior is expected in spec.

https://github.com/crystal-lang/crystal/blob/6d1a6a71880bf596ad37484e323b3f87f7817967/spec/compiler/semantic/restrictions_spec.cr#L89-L99

**Comment by asterite** [comment]
`typeof` won't work in the future in method signatures. I'll send a PR to remove this soon.

**Comment by bew** [comment]
@asterite please open an issue first so we can discuss it!
