### ISSUE TITLE
downcast bug

### ISSUE THREAD

**Issue by chenkovsky** [crystal-lang/crystal#5190]
BUG: trying to downcast A(String) <- B(String)
0x108f652f3: *raise<String>:NoReturn at ??
0x1096cd591: *Crystal::CodeGenVisitor#downcast<LLVM::Value, Crystal::Type+, Crystal::Type+, Bool>:LLVM::Value at ??
0x109720d65: *Crystal::CodeGenVisitor#visit<Crystal::Var+>:(LLVM::Value | Nil) at ??
0x1096e638d: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10970b9c6: *Crystal::CodeGenVisitor#prepare_call_args_non_external<Crystal::Call, Crystal::Def+, Crystal::Type+>:Tuple(Array(LLVM::Value), Bool) at ??
0x1097060df: *Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool at ??
0x109705fc5: *Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool at ??
0x1096e9cd8: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10970bd24: *Crystal::CodeGenVisitor#prepare_call_args_non_external<Crystal::Call, Crystal::Def+, Crystal::Type+>:Tuple(Array(LLVM::Value), Bool) at ??
0x1097060df: *Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool at ??
0x1096e9cd8: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096f94f9: *Crystal::CodeGenVisitor#codegen_fun<String, Crystal::Def+, Crystal::Type+, Bool, Crystal::CodeGenVisitor::ModuleInfo, Bool, Bool>:LLVM::Function at ??
0x1096fd2d6: *Crystal::CodeGenVisitor#target_def_fun<Crystal::Def+, Crystal::Type+>:LLVM::Function at ??
0x109706983: *Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool at ??
0x1096e9cd8: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096e8703: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1097221a8: *Crystal::CodeGenVisitor#codegen_cond<Crystal::ASTNode+>:LLVM::Value at ??
0x1096e7b2c: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096e6489: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096e8703: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096e876b: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096e876b: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096e876b: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096eb06c: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096eb06c: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096e6f30: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096e7bb5: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096e6489: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1097068c9: *Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool at ??
0x1096e9cd8: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1097068c9: *Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool at ??
0x1096e9cd8: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096e6489: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096f94f9: *Crystal::CodeGenVisitor#codegen_fun<String, Crystal::Def+, Crystal::Type+, Bool, Crystal::CodeGenVisitor::ModuleInfo, Bool, Bool>:LLVM::Function at ??
0x1096fd2d6: *Crystal::CodeGenVisitor#target_def_fun<Crystal::Def+, Crystal::Type+>:LLVM::Function at ??
0x109706983: *Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool at ??
0x1096e9cd8: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096ff595: *Crystal::CodeGenVisitor#visit<Crystal::Assign>:(Bool | Nil) at ??
0x1096e69d6: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096e6489: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096f94f9: *Crystal::CodeGenVisitor#codegen_fun<String, Crystal::Def+, Crystal::Type+, Bool, Crystal::CodeGenVisitor::ModuleInfo, Bool, Bool>:LLVM::Function at ??
0x1096fd2d6: *Crystal::CodeGenVisitor#target_def_fun<Crystal::Def+, Crystal::Type+>:LLVM::Function at ??
0x109706983: *Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool at ??
0x1096e9cd8: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096e6489: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096f94f9: *Crystal::CodeGenVisitor#codegen_fun<String, Crystal::Def+, Crystal::Type+, Bool, Crystal::CodeGenVisitor::ModuleInfo, Bool, Bool>:LLVM::Function at ??
0x1096fd2d6: *Crystal::CodeGenVisitor#target_def_fun<Crystal::Def+, Crystal::Type+>:LLVM::Function at ??
0x109706177: *Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool at ??
0x1096e9cd8: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096f94f9: *Crystal::CodeGenVisitor#codegen_fun<String, Crystal::Def+, Crystal::Type+, Bool, Crystal::CodeGenVisitor::ModuleInfo, Bool, Bool>:LLVM::Function at ??
0x1096fd2d6: *Crystal::CodeGenVisitor#target_def_fun<Crystal::Def+, Crystal::Type+>:LLVM::Function at ??
0x109706983: *Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool at ??
0x1096e9cd8: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096ff595: *Crystal::CodeGenVisitor#visit<Crystal::Assign>:(Bool | Nil) at ??
0x1096e69d6: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096e6489: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096f94f9: *Crystal::CodeGenVisitor#codegen_fun<String, Crystal::Def+, Crystal::Type+, Bool, Crystal::CodeGenVisitor::ModuleInfo, Bool, Bool>:LLVM::Function at ??
0x1096e6cb0: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10970614d: *Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool at ??
0x1096e9cd8: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096e6489: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096f94f9: *Crystal::CodeGenVisitor#codegen_fun<String, Crystal::Def+, Crystal::Type+, Bool, Crystal::CodeGenVisitor::ModuleInfo, Bool, Bool>:LLVM::Function at ??
0x1096e6cb0: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10970614d: *Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool at ??
0x1096e9cd8: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096f94f9: *Crystal::CodeGenVisitor#codegen_fun<String, Crystal::Def+, Crystal::Type+, Bool, Crystal::CodeGenVisitor::ModuleInfo, Bool, Bool>:LLVM::Function at ??
0x1096e6cb0: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10970614d: *Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool at ??
0x1096e9cd8: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096e6f30: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096e62cb: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096e6489: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x1096a2b00: *Crystal::Compiler#codegen<Crystal::Program, Crystal::ASTNode+, Array(Crystal::Compiler::Source), String>:(Tuple(Array(Crystal::Compiler::CompilationUnit), Array(String)) | Nil) at ??
0x109a05074: *Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result at ??
0x108fc1808: *Crystal::Command#run:(Bool | Crystal::Compiler::Result | IO::FileDescriptor | Nil) at ??
0x108f94a86: main at ??

**Comment by bew** [comment]
Can you provide a short example that triggers this error?

**Comment by chenkovsky** [comment]
@bew I'm trying to simplify the example.

**Comment by Sija** [comment]
Is it with Crystal's `master`?

**Comment by chenkovsky** [comment]
@Sija Crystal 0.23.1 (2017-10-12) LLVM 4.0.1

**Comment by Sija** [comment]
@chenkovsky I'd suggest to see does it happen with `master`.

**Comment by chenkovsky** [comment]
@Sija it happens in master

**Comment by RX14** [comment]
Even if your example isn't simple, it'd still be great if you could upload whatever you have to a gist or git repo.

**Comment by chenkovsky** [comment]
I uploaded my code to https://github.com/chenkovsky/tmp_debug

**Comment by asterite** [comment]
You are using generics inheritance. This is broken. Please don't use that.

**Comment by asterite** [comment]
Reduced:

```crystal
abstract class Foo(E)
  abstract def foo
end

abstract class Bar(E) < Foo(E)
end

class Baz(E) < Bar(E)
  def foo
  end
end

ptr = Pointer(Foo(String)).malloc(1_u64)

Baz(String).new

x = ptr.value
if x.is_a?(Bar)
  x.foo
end
```

**Comment by marksiemers** [comment]
I have another example of this issue, in case it is helpful: https://github.com/marksiemers/test_app

Steps to reproduce:
1. `git clone git@github.com:marksiemers/test_app.git`
2. `cd test_app`
3. `shards install`
4. `crystal spec`

An example of the output:
```
BUG: trying to downcast ApplicationController <- PostCommentController
0x10ceaf2f3: *raise<String>:NoReturn at ??
0x10d617591: *Crystal::CodeGenVisitor#downcast<LLVM::Value, Crystal::Type+, Crystal::Type+, Bool>:LLVM::Value at ??
0x10d655bcb: *Crystal::CodeGenVisitor#prepare_call_args_non_external<Crystal::Call, Crystal::Def+, Crystal::Type+>:Tuple(Array(LLVM::Value), Bool) at ??
0x10d6500df: *Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool at ??
0x10d633cd8: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d6559c6: *Crystal::CodeGenVisitor#prepare_call_args_non_external<Crystal::Call, Crystal::Def+, Crystal::Type+>:Tuple(Array(LLVM::Value), Bool) at ??
0x10d6500df: *Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool at ??
0x10d633cd8: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d6653d4: *Crystal::CodeGenVisitor#run_instance_vars_initializers<Crystal::Type+, (Crystal::ClassType+ | Crystal::GenericClassType+), LLVM::Value>:Nil at ??
0x10d6650a4: *Crystal::CodeGenVisitor#run_instance_vars_initializers<Crystal::Type+, (Crystal::ClassType+ | Crystal::GenericClassType+), LLVM::Value>:Nil at ??
0x10d66473d: *Crystal::CodeGenVisitor#allocate_aggregate<Crystal::Type+>:LLVM::Value at ??
0x10d65a9c0: *Crystal::CodeGenVisitor#codegen_primitive<Crystal::Call, Crystal::Primitive+, Crystal::Def+, Array(LLVM::Value)>:LLVM::Value at ??
0x10d650966: *Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool at ??
0x10d633cd8: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d649595: *Crystal::CodeGenVisitor#visit<Crystal::Assign>:(Bool | Nil) at ??
0x10d6309d6: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d630489: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d6434f9: *Crystal::CodeGenVisitor#codegen_fun<String, Crystal::Def+, Crystal::Type+, Bool, Crystal::CodeGenVisitor::ModuleInfo, Bool, Bool>:LLVM::Function at ??
0x10d6472d6: *Crystal::CodeGenVisitor#target_def_fun<Crystal::Def+, Crystal::Type+>:LLVM::Function at ??
0x10d650983: *Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool at ??
0x10d633cd8: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d649595: *Crystal::CodeGenVisitor#visit<Crystal::Assign>:(Bool | Nil) at ??
0x10d6309d6: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d630489: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d6434f9: *Crystal::CodeGenVisitor#codegen_fun<String, Crystal::Def+, Crystal::Type+, Bool, Crystal::CodeGenVisitor::ModuleInfo, Bool, Bool>:LLVM::Function at ??
0x10d630cb0: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d649595: *Crystal::CodeGenVisitor#visit<Crystal::Assign>:(Bool | Nil) at ??
0x10d6309d6: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d630489: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d63506c: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d6508c9: *Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool at ??
0x10d633cd8: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d630489: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d63506c: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d6508c9: *Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool at ??
0x10d633cd8: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d6302cb: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d630f30: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d6302cb: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d630f30: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d6302cb: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d630f30: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d6302cb: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d630489: *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil at ??
0x10d5ecb00: *Crystal::Compiler#codegen<Crystal::Program, Crystal::ASTNode+, Array(Crystal::Compiler::Source), String>:(Tuple(Array(Crystal::Compiler::CompilationUnit), Array(String)) | Nil) at ??
0x10d94f074: *Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result at ??
0x10cf0b808: *Crystal::Command#run:(Bool | Crystal::Compiler::Result | IO::FileDescriptor | Nil) at ??
0x10cedea86: main at ??

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```
