### ISSUE TITLE
Format tool fails when backslash is used

### ISSUE THREAD

**Issue by gokmen** [crystal-lang/crystal#5191]
```bash
$ crystal -v
Crystal 0.23.1 (2017-09-18) LLVM 4.0.1

$ cat test.cr
def test
  print "hello", \
    "world"
end

test()

$ crystal run test.cr
helloworld%                                                                   

$ crystal tool format --check test.cr
Error:, couldn't format 'test.cr', please report a bug including the contents of it: 
https://github.com/crystal-lang/crystal/issues
```

https://play.crystal-lang.org/#/r/2z2d

Not tested on current `master` only with the latest stable version, `0.23.1` on macOS and Ubuntu respectively.

Here is the piece of code alone for reference;

```crystal
def test
  print "hello", \
    "world"
end

test()
```

I could find a related issue https://github.com/crystal-lang/crystal/issues/3383 but current one is a bug since it's failing without an error which probably introduced while taking care #3383 

It would be better to add `--verbose` option to `formatter` as well since there is no way to see where it's failing now, at least exception can be printed out to the output with `--verbose` option in such cases https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/command/format.cr#L178-L184

**Comment by straight-shoota** [comment]
You don't need a backslash here.

This is totally fine:
```crystal
def test
  print "hello",
    "world"
end

test()
```

But of course, the compiler should either accept it or provide a meaningful error message.

**Comment by MakeNowJust** [comment]
#4631

**Comment by asterite** [comment]
I repeat: printing a stack trace will help **us** fix the bug. It won't help a user at all.

**Comment by Sija** [comment]
@asterite Isn't true that printing backtrace will help user help **us** to fix the bug? ;)

**Comment by asterite** [comment]
Not much. In this case they can just submit the code and we can see where it fails. In other compiler bugs we have to try to understand what's wrong, here it's just syntax.
