### ISSUE TITLE
formatter: bad indentation of comment after a call in begin/rescue/else block

### ISSUE THREAD

**Issue by bew** [crystal-lang/crystal#5196]
```cr
begin
  call
rescue ex
  call
  # comment
else
  call
  # comment
end
```
I think it should not change, but it gets formatted to:
```cr
begin
  call
rescue ex
  call
# comment
else
  call
# comment
end
```
It doesn't happen when the `call` is not there.

**Comment by MakeNowJust** [comment]
I'm not sure it should not change, but formatter keeps this, so I think it is a bug:

```crystal
if true
  call
  # comment
else
  call
  # comment
end
```

**Comment by bew** [comment]
> I'm not sure it should not change

What do you mean? What else could it be?

**Comment by MakeNowJust** [comment]
I considered such a case:

```
if foo

# comment for `cond`
elsif cond
end

case foo
when bar

# comment for `cond`
when cond
end

begin
  call

# comment for `ex`
rescue ex
  call
end
```

`elsif` and `when` comment are indented by formatter, and only `rescue` comment is kept.
