### ISSUE TITLE
Array#take

### ISSUE THREAD

**Issue by coderhs** [crystal-lang/crystal#5205]
We presently have a `Enumerable#take_while` to get methods from an enumerator (an array) which satisfy a condition. In ruby we have a `.take` method which would return the first x elements, I feel that is a good feature to have for an enumerator. 

Helpful while working with an infinite series. If this is a welcomed addition I would love to work on the PR.

**Comment by jhass** [comment]
Crystal provides this as [`Enumerable#first`](https://crystal-lang.org/api/0.23.1/Enumerable.html#first%28count%3AInt%29-instance-method), which Ruby also provides as an alias to first.
