### ISSUE TITLE
Can't use generic type arguments in alias.

### ISSUE THREAD

**Issue by shelvacu** [crystal-lang/crystal#5223]
```crystal
class Foo(T)
  alias Bar = Array(T)

  def initialize
    @baz = Hash(Symbol, Bar).new
  end
end

p Foo(Int32).new
```

On master (`Crystal 0.24.0+9 [2e00b8f7a] (2017-10-31)`) this errors with `undefined constant T` on line 2.

Previously, in version 0.23.1, it would error with `instance variable '@baz' of Foo(Int32) must be Hash(Symbol, Array(Int32)), not Hash(Symbol, Array(T))` on line 5.

**Comment by jhass** [comment]
That's intentional for now, see #1920, #2803 and the referenced issues.
