### ISSUE TITLE
Example for HTTP::FormData::Builder is passing the wrong variable

### ISSUE THREAD

**Issue by exts** [crystal-lang/crystal#5246]
In the api docs for [`HTTP::FormData::Builder`](https://crystal-lang.org/api/0.23.1/HTTP/FormData/Builder.html) there's an example not actually passing the correct memory buffer to the file method.

`builder.file("upload", io, FileMetadata.new(filename: "test.txt"))`

Should be

`builder.file("upload", file, FileMetadata.new(filename: "test.txt"))`

**Comment by Sija** [comment]
Duplicate of #4898.
