### ISSUE TITLE
Release Log consistency is broken by site/repo etc. 

### ISSUE THREAD

**Issue by akzhan** [crystal-lang/crystal#5251]
Please take a look: https://crystal-lang.org/
 - nobody updates it's changelog.

Please see a repo - again.

Changelog propagation failed.

**Comment by asterite** [comment]
Sorry, I don't understand what you mean.

**Comment by akzhan** [comment]
Please see actual list: https://github.com/crystal-lang/crystal/milestone/22?closed=1

Now see RELEASE NOTES at https://crystal-lang.org/

And now see at https://github.com/crystal-lang/crystal/blob/master/CHANGELOG.md

**Comment by asterite** [comment]
There are no release notes for 0.24.0. Nobody wrote that and maybe nobody will. The changelog is in the 0.24.0 branch, not merged to master yet. I see no problem here.

**Comment by Wulfklaue** [comment]
I think he means that the Crystal Website is not updated with the release for Crystal version 0.20+. As crystal is already at 0.23.1, it looks like Crystal has not had a official update in over a year ( See bottom of the page ).

```RELEASE NOTES
Crystal 0.20.0 released!	22 Nov 2016
Crystal 0.18.0 released!	14 Jun 2016```

**Comment by asterite** [comment]
Those are just blog posts associated with some releases. Not every release gets a blog post.

The website is probably misleading in that sense.

**Comment by Sija** [comment]
IMHO lack of complete release notes/changelog on the website (even just pointing to GH releases) and sparse activity on the blog gives misleading impression of project's inactivity and might undermine _wow effect_ given by the first impression on the website (slick syntax + speed).

**Comment by jwoertink** [comment]
I'll update it 😄  Just show me where, and give me access to deploy!

**Comment by hugoabonizio** [comment]
@jwoertink https://github.com/crystal-lang/crystal-website
