### ISSUE TITLE
StringPool loses strings when growing

### ISSUE THREAD

**Issue by hinrik** [crystal-lang/crystal#5252]
This can be reproduced on 0.23.1 and master.

```crystal
require "string_pool"

pool = StringPool.new
pool.get("foo")

(0..500).each do |i|
  # add random stuff to grow the pool
  random_str = (1..8).map{ ((rand(2)==1?65:97) + rand(25)).chr }.join
  pool.get(random_str)

  # id for "foo" is not always the same, lost when resizing/rehashing?
  puts "%3d %d" % {pool.size, pool.get("foo").object_id}
end
```

On my machine the id for "foo" always changes after the pool size reaches 55, and again at 335.

**Comment by asterite** [comment]
I can't reproduce this in master

**Comment by hinrik** [comment]
Example: https://carc.in/#/r/31k4

**Comment by funny-falcon** [comment]
This was true before new StringPool implementation. Old StringPool recreated strings on resize.
New StringPool preserves strings, so it is not reproducible on master.

**Comment by hinrik** [comment]
I must have compiled an older version than I previously thought. Recompiled master now and I can't reproduce it. Thanks.

**Comment by akzhan** [comment]
Use 0.24 and you'll get expectable behavior.

**Comment by asterite** [comment]
For further reference, there's no need to recompile the compiler for this. Just use bin/crystal or set CRYSTAL_PATH to the src directory in this repo
