### ISSUE TITLE
Syntax error with `&&`, `||` on separate line

### ISSUE THREAD

**Issue by Qwerp-Derp** [crystal-lang/crystal#5270]
## Issue:

Crystal has a syntax error when an `&&` statement is on another line - it's the same with `||`. It seems as if the parser parses the `&& false` as one separate instruction as opposed to part of `val`. I'm not sure whether this is a valid issue or not, but it's best to get everyone's thoughts.

## Minified example:

```crystal
val = true
  && false

puts val
```

**Comment by bew** [comment]
Use:
```cr
val = true &&
  false
```

As to why it is a syntax error, this is because `val = true` is a valid expression, and `&& false` on a new line is taken as a new expression, which is not valid.
Using `&&` at the end of the line makes `val = true &&` an expression that is not terminated, and the end of that expression is looked on the next line so this works.

**Comment by faultyserver** [comment]
This is a consequence of the language not requiring a semi-colon at the end of every statement. You'll get the same result in any language that works this way (Python, Ruby, Elixir, etc.).

When the parser requires a semi-colon to end the statement, it can freely skip newlines and interpret your example as you would expect. But, as bew said, without the semi-colon, the newline is important in indicating the end of the statement.

**Comment by ysbaddaden** [comment]
Closing. Line feeds are significant and terminate an expression. The operator must appear on the previous line so the linefeed becomes insignificant.

**Comment by drosehn** [comment]
FWIW, if you feel you really want to have the `&&` start on a new line, then you can escape the newline on the previous line using the `\` character.  Eg:

```cr
val = true \
  && false

puts val
```
Note that the `\` **must** be the final character before the newline which ends that line.  There must not be any spaces or tabs after the `\`.  Usually it makes much more sense to just move the operator you're using  (`&&`, `||`, `+`, etc) up to the previous line, as everyone has described.
