### ISSUE TITLE
Time::Span#*, Time::Span#/ and Float

### ISSUE THREAD

**Issue by nome** [crystal-lang/crystal#5272]
Trying to calculate an estimate of remaining time for a task based on elapsed time and percentage done, using the following code:

```.ruby
done = 0.75 # 75% of work done
elapsed = Time::Span.new(0,1,0)
total = elapsed / done
```

I see the following error:

    Error in line 3: instantiating 'Time::Span#/(Float64)'

    in /scr/hallasan/crystal-0.24.0-2/src/time/span.cr:303: no overload matches 'Int64#tdiv' with type Float64
    Overloads are:
     - Int#tdiv(other : Int)

        seconds = to_i.tdiv(number)
                       ^~~~

Alternatively:

```.ruby
done = 0.75 # 75% of work done
elapsed = Time::Span.new(0,1,0)
total = elapsed * (1.0/done)
```

results in

    Error in line 3: instantiating 'Time::Span#*(Float64)'

    in /scr/hallasan/crystal-0.24.0-2/src/time/span.cr:296: no argument named 'seconds'
    Matches are:
     - Time::Span.new(days : Int, hours : Int, minutes : Int, seconds : Int, nanoseconds : Int = 0)
     - Time::Span.new(hours : Int, minutes : Int, seconds : Int)
     - Time::Span.new(*, seconds : Int, nanoseconds : Int)
     - Time::Span.new(*, nanoseconds : Int) (trying this one)

        Span.new(
             ^~~

So, neither `Time::Span#/` nor `Time::Span#*` appear to accept floats. However, the API documentation gives their types as `#*(number : Number)` and `#/(number : Number)`, and `0.75.is_a? Number # => true`.

Am I missing something or is this a bug?

```
$ crystal -v
Crystal 0.23.0+313 [ea4187c57] (2017-10-27)

LLVM: 3.9.1
Default target: x86_64-unknown-linux-gnu
```

**Comment by petoem** [comment]
@nome you are using crystal compiler version `0.23.0+313` with `crystal-0.24.0-2` stdlib. 
Anyway I don't think this is an issue here.

Both `Time::Span#/` and `Time::Span#*` are bugged.
`Time::Span#/` accepts a type `Number` but tries to use `Int#tdiv` which only accepts `Int` not `Number` and certainly not `Float64`.

In `Time::Span#*` on line https://github.com/crystal-lang/crystal/blob/master/src/time/span.cr#L297
it does `Int64 * Float64` which results in `Float64`, hence `Time::Span.new` fails because there is no named argument called `seconds` with type `Float64`.

**Comment by petoem** [comment]
@nome As a workaround you can use the `total_seconds` of the `elapsed` timespan to calculate and then create a new `Time::Span` from the `total` with `#seconds` method.
```crystal
done = 0.75 # 75% of work done
elapsed = Time::Span.new(0,1,0)
total = elapsed.total_seconds / done
pp total.seconds # => 00:01:20
```

**Comment by nome** [comment]
@petoem Thanks, the workaround does help.

(incidentally, I've been using compiler and stdlib from the [0.24.0 pre-release tarball](https://github.com/crystal-lang/crystal/releases/download/0.24.0/crystal-0.24.0-2-linux-x86_64.tar.gz), so I disavow responsibility for any version mismatches ;-))
