### ISSUE TITLE
Unknown error with WebSocket.

### ISSUE THREAD

**Issue by MrSorcus** [crystal-lang/crystal#5279]
# Submitting bugs
Can't compile code 
```Crystal
HTTP::Server.new("::", 3030,
	HTTP::WebSocketHandler.new do |test|
		ws = HTTP::WebSocket.new("::", "/")
		spawn do
			ws.run
		end
	end
).listen
```
Logs - https://gist.github.com/MrSorcus/8235111bf53e283388c3d6013804f08e

Crystal 0.23.1 (2017-11-07) LLVM 4.0.1

**Comment by RX14** [comment]
Not much we can go on there, looks like the ecr executable filed to run properly. Does this happen outside of nixos?

**Comment by MrSorcus** [comment]
https://play.crystal-lang.org/#/r/32t6
I don't have other OS now. But play.crystal-lang.org doesn't compile that code too.

**Comment by RX14** [comment]
@MrSorcus yes but for a different and unrelated reason.

**Comment by MrSorcus** [comment]
Works with CentOS 7.

**Comment by RX14** [comment]
Looks to me as if it's only going to be reproducible on nixos. Please could you try the same thing again on crystal master, it has some improvements to the logging when macro runs fail, so we should be able to get some more information on the error at least.

**Comment by MrSorcus** [comment]
```
[nix-shell:/nix/store/0ks0jiih2ximvpp7phn3vlsw39bjj8py-source]$ .build/crystal --version
Crystal 0.23.1 (2017-11-13)

LLVM: 5.0.0
Default target: x86_64-unknown-linux-gnu
```
Look like that problem with nix derivation, not with crystal, because example code compiling fine.
Sorry for disturb.
Close issue?

**Comment by RX14** [comment]
We'll close for now, and reopen if it turns out to be our issue.
