### ISSUE TITLE
Generics inheritance & initialization

### ISSUE THREAD

**Issue by anykeyh** [crystal-lang/crystal#5281]
This snippet fail to compile; note than without generic on `B(T)` it will works as expected

```crystal
module A
  @x : String

  def initialize(@x = "")
  end
end

class B(T)
  include A

  @y = {} of String => String
end

class C < B(String); end

C.new
```

Link to play the snippet:

https://play.crystal-lang.org/#/r/32r9

**Comment by Sija** [comment]
Related to #5120?

**Comment by anykeyh** [comment]
I don't think so, because it works correctly if `B` is not a generic, so it must be related to generics 😄
