### ISSUE TITLE
How to cast (efficiently) an array to inherited class when you know all the elements belongs to this class?

### ISSUE THREAD

**Issue by anykeyh** [crystal-lang/crystal#5289]
# The case

Let's have an array declared like this:

```crystal

x = [] of ParentClass

```

which is filled by child class (child inherit or include parent):

```crystal
10.times{ x << ChildClass.new }
```

now how to cast `x` to be an `Array(ChildClass)`?

## What's won't work

Obviously, this won't work otherwise this opened issue would be pointless:

```crystal
x.as(Array(ChildClass))
```

## What works but isn't effective

```crystal
x.map(&.as(ChildClass)) #Yeah !
```
However, as far as I know, map copy the array to another one, not super effective...

## What seems to work, but is evil (unless you tell me it's lgtm!)

```crystal
# A bit of evil !
def unsafe_cast(x : T, to : U.class) forall T, U
  ptr2 = Pointer(U).new(pointerof(x).address).value
end

unsafe_cast(x, ChildClass) # It remind me c++ 9x :')
```

## My questions

- Is there any more performant but legitimate method to cast an Array than copying with `map/as`?
- Is my `unsafe_cast` evil so evil? It seems to work on my test case, but I'm not confident enough about the implementation of array and memory footprint. Doesn't Array(ParentClass) and Array(ChildClass) share exactly the same memory content?

## Additional test case

Here a simple look of what I'm trying to do :

```crystal
module A
end

class B
  include A
  @x : Bool = false
end

class C
  include A

  @y : String = "helloworld"
  @z : Float64 = 1.0
end

def unsafe_cast(x : T, to : U.class) forall T, U
  ptr2 = Pointer(U).new(pointerof(x).address).value
end

class X
  getter hash : Hash(String, Array(A)) = {} of String => Array(A)

  def add(x : T) forall T
    arr = @hash.fetch(T.name) { [] of A }
    arr << x
    @hash[T.name] = arr
  end

  def get(x : T.class) : Array(T) forall T
    # Main question is here: I need to copy to a new array
    # and check at compile time the type using `as`...
    # is there any way to cast the Array(A) to Array(B)?
    arr = @hash[x.name]

    unsafe_cast(arr, Array(T)) # This evil is working, for real? :-|
    # arr.map(&.as(T)) # << Safe method, but array copy
  end
end

x = X.new

10.times { x.add(B.new) }
10.times { x.add(C.new) }

pp x.get(B)
pp x.get(C)
```
I'm curious about what the guru and project dev would say about this.

Anyway it would be awesome if we can - in some cases - tell the compiler we want to cast an Array of Fruit to Apple because we know all Fruits are Apple!

I guess the problem however comes from structures & union

## Here an example of implementation

```crystal
class Array(T)
  # Allow unsafe casting of this array to another array
  # Useful when you know what to do
  def unsafe_cast(klazz : U.class) : Array(U) forall U
    raise "The cast is not possible" if sizeof(T) != sizeof(U)
    x = self
    Pointer(Array(U)).new(pointerof(x).address).value
  end
end

arr = [0x123, 0x292, 0x3fe]
pp arr.unsafe_cast(Float32) #Int32 and Float32 are same sized so it works.
```

**Comment by jhass** [comment]
> Doesn't Array(ParentClass) and Array(ChildClass) share exactly the same memory content?

Here probably is your understandable confusion! They don't!

Imagine having two child classes, one slightly bigger (more instance variables essentially) than the other. `Array(ParentClass)` needs to be be able to hold both, but `Array(SmallerChildClass)` doesn't, so it can use less memory. 

There's also a semantic issue, say you add one of either of your two subclasses to your `Array(ParentClass)`, now you cast it to `Array(ChildClassOne)`, suddenly you have a `ChildClassTwo` in an `Array(ChildClassOne)`! That's clearly invalid.

So yes, for now conversion (creating a new array) is your only sane choice. In theory we can support turning an `Array(ChildClass)` into an `Array(ParentClass)`, but never the other way around.

**Comment by anykeyh** [comment]
I understand that, and it's true it won't work with `Union` nor `Struct`. In my code above, I wrote `raise "The cast is not possible" if sizeof(T) != sizeof(U)` for this reason.

For the case of Array of Class however, each class are passed by references, therefore the size won't change (a pointer), and two array `Array(Apple)` and `Array(Fruit)` with the same content would have byte-to-byte roughly the same content .

The real problem is: In the case above, I cannot find an elegant way to store in my hash array of different items sharing the same parent, for each key, then offer to retrieve the basket with proper identification of the object into it.
The only way I'm thinking is to delegate Array method (each, map...) to my basket-manager (the `X` class above)
There's no way in my case than any elements fit the wrong array and you start to have `Apple` with `Peach`, since the compiler select the good basket automatically.

My opinion on this subject is that since we have `unsafe_at` in array to fast to access the items, I'm thinking an `unsafe_cast` would works to.

In Java, with generics you can cast to Array(Parent) to Array(Child) ( but it will throw exception, if Array(Child) wasn't instantiated as Array(Child) )

**Comment by lbguilherme** [comment]
For the very particular case of References, the current implementation happens to share the same code and memory representation. Thus `Array(ParentClass)` happens to be exactly equal in implementation to `Array(ChildClass)`. This means you can use `unsafe_at`:

```cr
class ParentClass; end
class ChildClass < ParentClass; end

ary = Array(ParentClass).new
3.times { ary << ChildClass.new }

pp ary
pp typeof(ary)

ary2 = ary.unsafe_as(Array(ChildClass))

pp ary2
pp typeof(ary2)
```

But please, please, please, don't do that. `unsafe_at` is unsafe. This means that in this particular case it happens to work, but there are no guarantees. An implementation change in Crystal may break this, and it wont be a breaking change, because this is already unsafe.

The correct thing to do is `ary2 = ary1.map(&.as(ChildClass))`.

**Comment by anykeyh** [comment]
I understand, I can see issues coming with include of modules or language changes...

So maybe in my case the best would be to handle `Hash(String, Pointer(Void))` with pointer to the Array, and keep track of what is the Array type to cast back later. It's unsafe storage, but as long as I cast from X to X, and ensure my code behave correctly, it's not less unsafe than playing with pointer in C/C++.

Thank you 👍

**Comment by RX14** [comment]
@anykeyh but why do you need to cast between arrays of different types? Why not just make it an array of the most general type you have to store?

**Comment by anykeyh** [comment]
@RX14 The real-world code is here: https://github.com/anykeyh/clear/blob/master/src/clear/model/cache.cr

The goal is to make an unified cache for N+1 query in an ORM.

Each item in the cache is an `Array(? extend Model)`, and if I'm sure than each array contains only this type of Model, since the model class is a discriminant into the cache key: `CacheKey.new(relation_name, relation_value, T.name)`.

In this case, it's not possible to copy the array, as performances impact can be high (array can be big in some case).

So here the trick I use is as discussed `unsafe_as`, and I "cheat" Crystal to store my array in a type which is not the right one. Then of course I cast it back to the real type before doing anything.

**Comment by RX14** [comment]
Honestly in this case of wanting an arbitrary cache with many-typed keys, i'd store `Hash(K, {Class, Void*})` and then check that the class was the same as the passed-in T in the `get` method, then `unsafe_as` the pointer. You'll have to check for `Value` types so that you can place them on the heap before converting to `Void*`.

**Comment by anykeyh** [comment]
@RX14 Thank you for the tips, indeed it would be a great things, but 

`can't use Class as generic type argument yet, use a more specific type`

Last question on the subject: if I cast an object as void `v = x.unsafe_as(Void)`, doesn't it can face problem with garbage collector? Do void pointer still keep the reference alive for the GC?

Thank you :)

**Comment by jhass** [comment]
Yes, all memory we allocate we allocate through the GC, so it has a list of pointers to memory we allocated. It then checks that memory and the stack for pointers in that list and frees those that are not found, basically.

**Comment by RX14** [comment]
@jhass that's currently true, not sure if we'll want to document that before 1.0 such that we have the option of a precise GC. I think the only way to make sure that switching to a precise GC is painless in the future is to actually use precise GC semantics. Hmm.

**Comment by jhass** [comment]
Not sure I follow why a precise GC would loose track of the pointer once it's casted to a void pointer

**Comment by anykeyh** [comment]
@jhass  Nothing to follow, I just want to clarify since I'm not an expert of GC core, I guess it was no problem but still ask 😉.

Well, tbh, it's kind of issue I had faced with SmartPtr long time ago in cpp

**Comment by RX14** [comment]
@jhass I meant if a pointer was stored or manipulated as an integer, sorry.
