### ISSUE TITLE
Why BigFloat.to_s is not precise enough?

### ISSUE THREAD

**Issue by iSarCasm** [crystal-lang/crystal#5301]
First I though that BigFloat requires to change  BigFloat.default_precision to work with bigger number. But from this code it looks like it only matters when trying to output #to_s value, because converting BigFloat to BigInt gives different result from BigFloat.to_s
https://carc.in/#/r/2w96

**Code**
```crystal
require "big"

x = BigInt.new(1<<30) * (1<<30) * (1<<30)
puts "BigInt: #{x}"

x = BigFloat.new(1<<30) * (1<<30) * (1<<30) 
puts "BigFloat: #{x}"
puts "BigInt from BigFloat: #{x.to_big_i}"
```
**Output**
```
BigInt: 1237940039285380274899124224
BigFloat: 1237940039285380274900000000
BigInt from BigFloat: 1237940039285380274899124224
```

Same with precision of BigFloat set to 1024 (https://carc.in/#/r/2w98):
**Output**
```
BigInt: 1237940039285380274899124224
BigFloat: 1237940039285380274899124224
BigInt from BigFloat: 1237940039285380274899124224
```

BigFloat.to_s uses LibGMP.mpf_get_str(nil, out expptr, 10, 0, self). Where GMP is saying:

> **mpf_get_str (char \*str, mp_exp_t \*expptr, int base, size_t n_digits, const mpf_t op)**
> Convert op to a string of digits in base base. The base argument may vary from 2 to 62 or from -2 to -36. Up to n_digits digits will be generated. Trailing zeros are not returned. No more digits than can be accurately represented by op are ever generated. If n_digits is 0 then that accurate maximum number of digits are generated.

*(This is related to https://stackoverflow.com/questions/46711149/why-bigfloat-to-s-is-not-precise-enough)*

Thanks.

**Comment by j8r** [comment]
In StackOverflow, the issue was fixed by increasing the default precision. @asterite raised the question if the precision of BigFloat can be increased.

Can it be considered as solved?

**Comment by bcardiff** [comment]
I think we can, `BigFloat.default_precision` is there to change the default, although I am not sure what is the initial value from GMP.

There is a bit of a leak abstraction I guess if the user needs to worry about this instead of using Big* as an arbitrary precision library. Or maybe is my lack of use of these libraries.

Closing since there is a workaround, but we can open later if there is something concrete to change.
