### ISSUE TITLE
Time::Format.parse doesn't exist for some reason

### ISSUE THREAD

**Issue by StormFire-Technologies** [crystal-lang/crystal#5302]
I am trying to use the Time::Format.parse method so I can parse a string into time so that it can be used in the rest of my application. But for some reason when I attempt to use the parse method it keeps giving me the error `undefined method 'parse' for Time::Format:Class`
and my code looks like this: `end_time = Time::Format.parse(data["endTime"], Time::Kind::Utc)`

**Comment by bew** [comment]
It's `parse` not a class method but an instance method, to use it you need to create a time format object and use it to parse the given time, according to a specific pattern:
```cr
given_time = "23:42"

# create a format object, with a pattern: <hour>:<minute>
format = Time::Format.new("%H:%M")

# use it to parse a string following this pattern
parsed_time = format.parse(given_time)

puts "Hours = #{parsed_time.hour}"
puts "Minutes = #{parsed_time.minute}"
```
With give:
```
Hours = 23
Minutes = 42
```

**Comment by StormFire-Technologies** [comment]
Ahhhh ok, that makes so much more sense. Thank you for your help!

I will close this now
