### ISSUE TITLE
realtime-todo-app (Postgres problem)

### ISSUE THREAD

**Issue by extremety1989** [crystal-lang/crystal#5304]
Hi everyone i just download realtime-todo-app repo,
as i tried to launch the application, i got those errors

crystal run src/db/init_db.cr

Error in src/db/init_db.cr:9: undefined method 'to_hash' for DB::ExecResult
database_exists? = conn.exec(%{
              ^~~~~~~
Rerun with --error-trace to show a complete error trace.

crystal run src/app.cr
Error in src/app.cr:4: while requiring "./app/models/*"
require "./app/models/*"
^
in src/app/models/note.cr:6: undefined constant PG::Result
  alias DBResult     = PG::Result
                       ^~~~~~~~~~

if i remove the PG::Result

can you please help me with that!
i already reinstalled PG packed  but does not resolved my problem.

**Comment by Sija** [comment]
I think this issue belongs to the [proper repo](https://github.com/Angarsk8/realtime-todo-app/issues/2).

**Comment by extremety1989** [comment]
yes, but here are more people

**Comment by ysbaddaden** [comment]
This issue tracker is meant to track issues and features to the Crystal compiler. Please direct such questions to the actual repository or a place where the community can help:
https://crystal-lang.org/community/

Hint: the repository is long outdated and duly broken.
