### ISSUE TITLE
The compiler accepts {{yield}} outside macros

### ISSUE THREAD

**Issue by jbomanson** [crystal-lang/crystal#5305]
I was experimenting with macros and came up with the following code that I think suspect should not compile. However, it does compile and prints nothing when run. Also, the call to `nothing` returns nil.
```crystal
def nothing
  {{yield}}
end

nothing do
  puts "Hello"
end
```

**Comment by MakeNowJust** [comment]
In fact, it can be compiled:

```crystal
p {{yield}}
```

It seems like a bug to me.
