### ISSUE TITLE
Error:, couldn't format from crystal tool format

### ISSUE THREAD

**Issue by actsasflinn** [crystal-lang/crystal#5310]
I am getting an error when running:

    $ crystal tool format
    Error:, couldn't format './src/lucky_support/inflector/methods.cr', please report a bug including the contents of it: https://github.com/crystal-lang/crystal/issues

The code in questions is here: https://github.com/actsasflinn/support/blob/8e2dd288cba9d797d029d28953a242155565f423/src/lucky_support/inflector/methods.cr

I'm on El Capitain 10.11.6, crystal installed via homebrew.

    $ crystal -v
    Crystal 0.23.1 (2017-10-12) LLVM 4.0.1

    $ uname -a
    Darwin mnet.private 15.6.0 Darwin Kernel Version 15.6.0: Mon Oct  2 22:20:08 PDT 2017; root:xnu-3248.71.4~1/RELEASE_X86_64 x86_64

    $ brew -v
    Homebrew 1.3.6
    Homebrew/homebrew-core (git revision cf537; last commit 2017-11-11)

**Comment by MakeNowJust** [comment]
The reason why this error is caused is `crystal tool format` did not support `$1?`. It is a bug and fixed in #5313. Thank you.
