### ISSUE TITLE
Test for and then call method on an arbitrary object

### ISSUE THREAD

**Issue by sam0x17** [crystal-lang/crystal#5311]
Note that `Document` objects have a defined `to_bson` method.

```crystal
item : Document | String | Int32 | Int64 | Nil (could be any of these types based on context)
if item && item.not_nil!.responds_to?(:to_bson)
  item.to_bson # compiler error for all types that do not support `to_bson`
end
```

Alternate version that also doesn't work:

```crystal
item : Document | String | Int32 | Int64 | Nil (could be any of these types based on context)
if item && item.not_nil!.is_a?(Document)
  item.to_bson # compiler error for all types that do not support `to_bson`
end
```

Why doesn't this work? Once I'm inside the if statement, doesn't the compiler know that it should be impossible for `to_bson` not to be defined on `item`?

**Comment by oprypin** [comment]
`not_nil!` is a normal method and whatever it returns does not affect the compiler's further decisions. So a check whether the result of some random expression responds to a method does not affect the variable that the method was called on.

**Comment by RX14** [comment]
if `item` is a method, instance variable, or anything but a local variable, this won't work. Using `item.not_nil!.responds_to(:to_bson)` is redundant (use `item.responds_to(:to_bson)`) and will break the type checker. You shouldn't have needed that `not_nil!` if `item` is a local variable (and I kinda suspect it isn't)

**Comment by sam0x17** [comment]
I just had `not_nil!` in there as a superstition. `item` is a local variable. Is there a way I can avoid this compiler error?

**Comment by sam0x17** [comment]
Here is the real code:

```crystal
      def to_bson
        bson = BSON.new
        bson["_id"] = self._id  if self._id != nil
        \{% for name, type in FIELDS %}
          if \{{name.id}} && \{{name.id}}.responds_to?(:to_bson)
            bson["\{{name}}"] = \{{name.id}}.to_bson
          else
            bson["\{{name}}"] = \{{name.id}}.as(Union(\{{type.id}} | Nil))
          end
        \{% end %}
        \{% if SETTINGS[:timestamps] %}
          bson["created_at"] = created_at.as(Union(Time | Nil))
          bson["updated_at"] = updated_at.as(Union(Time | Nil))
        \{% end %}
        bson
      end
    end
```

**Comment by Sija** [comment]
I suppose `\{{name.id}}` is a call to instance method, not a local variable, thus invoking compiler error.

Try assigning return value to a local variable first, like:

```cr
if (%value = \{{name.id}}) && %value.responds_to?(:to_bson)
```

**Comment by Sija** [comment]
Also, instead of `Union(SomeType | Nil)` you an write `SomeType?`

**Comment by sam0x17** [comment]
@Sija probably -- this code is copied almost exactly from Granite ORM, so I've tried to change as little as possible

Thanks -- that worked -- though I found an easier solution was to simply extend BSON:

```
class BSON
  def []=(key, value : Mongo::ORM::EmbeddedDocument)
    self[key] = value.to_bson
  end
end
```
