### ISSUE TITLE
Problem with parsing WebSocket IPv6.

### ISSUE THREAD

**Issue by MrSorcus** [crystal-lang/crystal#5326]
```
[root@server]/tmp# python --version
Python 2.7.5
```
```
[root@server]/tmp# /tmp/crystal-0.24.0-2/bin/crystal --version
Crystal 0.23.0+313 [ea4187c57] (2017-10-27)

LLVM: 3.9.1
Default target: x86_64-unknown-linux-gnu
```
```
Chromium
Version 62.0.3202.94 (Developer Build) (64-bit)
```
```
Firefox
57.0 (64-bit)
```

First problem. Crystal can't connect to IPv6 address. From client to server.
 
Server:
```Crystal
require "http"

module Network
	class WebSocket < HTTP::WebSocketHandler
		HANDLERS = [] of HTTP::Handler
		def initialize (@path : String, &@proc : HTTP::WebSocket, HTTP::Server::Context -> Nil)
			HANDLERS << self
		end

		def self.run (host : String = "::", port : Int32 = 3030)
			puts "Run server on ws://[#{host}]:#{port}"
			HTTP::Server.new(host, port, HANDLERS).listen
		end
	end
end

Network::WebSocket.new "/" do |socket|
	socket.send("Hello World!")
	socket.close
end

Network::WebSocket.run
```
Client:
```Crystal
require "http"

ws = HTTP::WebSocket.new(URI.parse("ws://[::]:3030"))

ws.close
```
Error - https://gist.github.com/MrSorcus/d84c2a048aa629f251df08ad2662d7b9
Without URI.parse doesn't work too.

~~Second error. (But i don't know where is the problem)~~. (**resolved**)

Server:
```Crystal
require "http"

module Network
	class WebSocket < HTTP::WebSocketHandler
		HANDLERS = [] of HTTP::Handler
		def initialize (@path : String, &@proc : HTTP::WebSocket, HTTP::Server::Context -> Nil)
			HANDLERS << self
		end

		def self.run (host : String = "::", port : Int32 = 3030)
			puts "Run server on ws://[#{host}]:#{port}"
			HTTP::Server.new(host, port, HANDLERS).listen
		end
	end
end

Network::WebSocket.new "/" do |socket|
		socket.send("Hello From Binary!".to_slice)
end

Network::WebSocket.run
```
```JavaScript
ws = new WebSocket("ws://[2a01:4f8:xx:xx::xx]:3030/")
ws.onmessage = (message) => {
	console.log(message.data)
}
```
~~Console.log show me ArrayBuffer(13) with byte length and without any payload~~.

~~But! Python client (https://github.com/websocket-client/websocket-client) works fine~~.
```Python
from websocket import create_connection
ws = create_connection("ws://[::]:3030")
print("Receiving...")
result =  ws.recv()
print("Received '%s'" % result)
ws.close()
```

~~Binary receiving doesn't work in chromium & firefox~~.

**UPD**: Problem with JS-client resolved. Look at here - https://stackoverflow.com/questions/47531467/why-js-client-doesnt-receive-binary-from-server/47532253#47532253

**Comment by faustinoaq** [comment]
I can reproduce this, We use some kind of different format for IPv6?

**Comment by MrSorcus** [comment]
Usually IPv6 address must be a string in square brackets, no?

**Comment by ysbaddaden** [comment]
The bug is that eventually `Socket::Addrinfo` is told to resolve `[2a01:4f8::]` *with* the square brackets, which obviously can't be resolved; they must be removed at some point.

**Comment by MrSorcus** [comment]
Ok. But what about problem with js-client?

**Comment by straight-shoota** [comment]
What about that? You mentioned Javascript in the headline but there is no description about that...

**Comment by RX14** [comment]
@straight-shoota yes there is, at the bottom of the issue description.

Regardless, seperate issues should be seperate github issues. Your second issue seems like something to investigate on gitter/irc/mailinglists though, instead of a concrete issue for the issue tracker.

**Comment by straight-shoota** [comment]
That last example is python...?

**Comment by MrSorcus** [comment]
> That last example is python...?

Yes. After first problem look at line "Second error. (But i don't know where is the problem).". Create separate issue?

> Regardless, seperate issues should be seperate github issues. Your second issue seems like something to investigate on gitter/irc/mailinglists though, instead of a concrete issue for the issue tracker.

No answer in gitter.  But ok, i will try again later.
