### ISSUE TITLE
Crypto::Bcrypt PASSWORD_RANGE hard-coded to an input-length-max of 51

### ISSUE THREAD

**Issue by vectorselector** [crystal-lang/crystal#5353]
I'm porting an app from Meteor, and wish to use the same user login data:
an email address, and a password. Meteor does this silly SHA256 hash of the plain-text password on the client before sending it to the server, where it uses node bcrypt (native or js) to process this 64bit digest with 10 rounds of bcrypt. 

The issue is that node bcrypt (and possibly others?) accepts a password input length of up to 71 (72?) per the blowfish algorithm internals of bcrypt 
while Crystal native Crypto::Bcrypt has a PASSWORD_RANGE of 1 to 51, which may be fine for a normal password, but not a 64bit pre-hashed password.

Is there a particular reason to limit it to 51?

https://github.com/crystal-lang/crystal/blob/3c712288ba8f8138cb734e673cc622658300c229/src/crypto/bcrypt.cr

**Comment by straight-shoota** [comment]
See [this anwswer](https://security.stackexchange.com/questions/39849/does-bcrypt-have-a-maximum-password-length#answer-39851) on stack exchange.

**Comment by ysbaddaden** [comment]
Looking at the history, I introduced this limitation. I probably copied it from some place (but which one?). Looking at the discussion on stack exchange, it appears the theoretic limit is 56 bytes (not 51) and as it happens to be, it would seem the actual limit would be 72 bytes (including the leading null byte).

**Comment by vectorselector** [comment]
I'm not 100% about Crypto::Blowfish, but (most?) blowfish implementations take up to 72.
https://github.com/B-Con/crypto-algorithms/blob/master/blowfish.c   

In terms of Crypto::Bcrypt
I only see the PASSWORD_RANGE limitation on the initializer Error instantiation.

**Comment by vectorselector** [comment]
awesome. thank you
