### ISSUE TITLE
Crytpo::Bcrypt not handling invalid hash strings nicely

### ISSUE THREAD

**Issue by crisward** [crystal-lang/crystal#5357]
https://play.crystal-lang.org/#/r/37f7

```crystal
require "crypto/bcrypt.cr"

hash = "blarp"
password = "bloop"

Crypto::Bcrypt::Password.new(hash) == password
```
Results in an `index out of bounds` error, as the string passed in isn't a valid bcrypt hash. I'd expect an exception. Or in the case of the password compare method, just to return false.

Seems to be coming from here - https://github.com/crystal-lang/crystal/blob/4f97a5345b661e25b68fe43d6ce64aa1dfc28c3b/src/crypto/bcrypt/password.cr#L41

Perhaps some kind of sanity check, at the top of the initialize method. ie
```
parts = @raw_hash.split("$")
raise Error.new("Invalid hash string") unless parts.size > 3
```

**Comment by straight-shoota** [comment]
it should be `unless parts.size == 3`
