### ISSUE TITLE
Object.def_clone is missing GC.add_finalizer

### ISSUE THREAD

**Issue by alexbatalov** [crystal-lang/crystal#5362]
Hi,

There is a minor bug in `Object.def_clone` macro, the clones does not call `finalize` even if it is defined.

The same bug reappears in `OpenSSL::SSL::Context.insecure` - because of the missing `GC.add_finalizer` the `finalize` is never called, causing memory leak.

https://carc.in/#/r/37kr
```crystal
require "spec"

class State
  class_property count = 0

  def self.reset
    self.count = 0
  end

  def self.inc
    self.count += 1
  end
end

class Foo
  def_clone

  def finalize
    State.inc
  end
end

describe Foo do
  it "should finalize cloned objects" do
    State.reset

    State.count.should eq(0)

    foo = Foo.new
    10.times do
      foo.clone
    end

    GC.collect

    State.count.should be > 0
  end
end
```

```
Crystal 0.23.1 (2017-10-12) LLVM 4.0.1
```

**Comment by ysbaddaden** [comment]
Also affects `Object#dup` and anything that calls `#allocate` and manually instead of `#new`.

**Comment by RX14** [comment]
Should adding the finalizer be codegened into `initialize` or `allocate` or is the only sane way to do this to have `add_finalizer` be a seperate step from those two methods?

**Comment by ysbaddaden** [comment]
Well, `initialize` is somewhat "just a method", and `allocate` isn't supposed to be public... maybe add the missing finalizers to the 2 identified places (`Object#clone` and `Reference#dup`)? Also the manual calls to `allocate` then `initialize` in OpenSSL should be changed to proper calls to `new`.

**Comment by alexbatalov** [comment]
One more place discovered - objects instantiated with `Object.from_yaml`. Added missing calls. Just a thought: OpenSSL's `Context` might get rid of `_initialize_insecure` with `initialize` param:

```crystal
def initialize(method : LibSSL::SSLMethod = Context.default_method, insecure = false)
  super(method, insecure)

  return if insecure
  
  # ...
end
```
