### ISSUE TITLE
Base64 Slow?

### ISSUE THREAD

**Issue by Wulfklaue** [crystal-lang/crystal#5371]
Today i was trying some PHP vs Crystal tests. And there was something that did not add up.

System: Debian, Ryzen 1600, 8GB ECC

PHP 7.0:
encode: 1333333600, 0.82
decode: 1000000000, 2.94 

Crystal 23.1
encode: 1333333600, 00:00:13.5935260 
decode: 1000000000, 00:00:26.8058000

Yes, the results ended up being 13 times slower then PHP. 

Both Crystal Run and Build && run ended up being slow.

One core running 100% during the both tests ...

```
require "base64"

STR_SIZE = 10_000_000
TRIES    =        100

str = "a" * STR_SIZE
str2 = ""

print "encode: "
t, s = Time.now, 0
TRIES.times do |i|
  str2 = Base64.strict_encode(str)
  s += str2.bytesize
end
puts "#{s}, #{Time.now - t}"

print "decode: "
t, s = Time.now, 0
TRIES.times do |i|
  s += Base64.decode(str2).bytesize
end
puts "#{s}, #{Time.now - t}"
```

```
<?php
$STR_SIZE = 10000000;
$TRIES = 100;
$str = "";
for ($i = 0; $i < $STR_SIZE; $i++) $str .= "a";
$str2 = "";
$s = 0;
$start = microtime(true);
for ($i = 0; $i < $TRIES; $i++) {
    $str2 = base64_encode($str);
    $s += strlen($str2);
}
printf("encode: %d, %.2f\n", $s, microtime(true) - $start);
$s = 0;
$start = microtime(true);
for ($i = 0; $i < $TRIES; $i++) {
    $str3 = base64_decode($str2);
    $s += strlen($str3);
}
printf("decode: %d, %.2f\n", $s, microtime(true) - $start);
```

Done the benchmarks several times and each time the results ended up being the same.

When checking the original site where i got the code from:

https://github.com/kostya/benchmarks

PHP is supposed to be 3 times slower then Crystal... Are we looking at a issue with Crystal and Ryzen CPUs? Other tests show Crystal winning against PHP or on equal level ( when PHP is accessing C based extentions ).

**Comment by kostya** [comment]
run it with --release option:
```
php test.php
encode: 1333333600, 1.52
decode: 1000000000, 9.28
crystal test.cr
encode: 1333333600, 00:00:20.4281690
decode: 1000000000, 00:00:30.6223340
crystal test.cr --release
encode: 1333333600, 00:00:01.1803430
decode: 1000000000, 00:00:02.7188520
```

**Comment by Wulfklaue** [comment]
Good to know but running with the --release results in the following error

crystal build base64.cr --release

```
crystal: /var/cache/omnibus/src/llvm/llvm-3.8.1.src/lib/CodeGen/LexicalScopes.cpp:160: llvm::LexicalScope* llvm::LexicalScopes::getOrCreateRegularScope(const llvm::DILocalScope*): Assertion `cast<DISubprogram>(Scope)->describes(MF->getFunction())' failed.
/usr/bin/crystal: line 102: 26729 Aborted                 "$INSTALL_DIR/embedded/bin/crystal" "$@"
```

**Comment by Wulfklaue** [comment]
PHP 7:
encode: 1333333600, 0.82 
decode: 1000000000, 3.25  

Crystal:
encode: 1333333600, 00:00:12.8882330
decode: 1000000000, 00:00:26.9714920 

Crystal ( --release --no-debug ):
encode: 1333333600, 00:00:00.7490210 
decode: 1000000000, 00:00:01.1458920 

Those results are much better. Thanks ;)

**Comment by bcardiff** [comment]
Duplicate of #4719 

FYI, @Wulfklaue if you get to use a newer llvm, the bug should go away.
