### ISSUE TITLE
Bug in {{ compare_versions }} / Crystal's VERSION string

### ISSUE THREAD

**Issue by docelic** [crystal-lang/crystal#5373]
The 0.24.0 prerelease which is available for download on:
https://github.com/crystal-lang/crystal/releases
Reports crystal -v ==> "0.23.0+313".

Crystal 0.23 reports "0.23.1".

So, {{ compare_versions("0.23.1", "0.23.0+313") }}
Mistakenly reports that version 0.23.1 is higher than 0.24.0 (which is identified as 0.23.0+313).

**Comment by RX14** [comment]
0.23.0+313 is not higher than 0.23.1 according to semver. Everything after the `+` is actually ignored when comparing versions. This is simply a bug in the version string.

But assuming you were comparing `0.23.0` and `0.23.0+313`, the part after the `+` is called the "build metadata".

From the semver spec:
> Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence.

According to the spec, we should probably use `0.23.0-git.313` for the git versions instead. Not that that would change how those two versions compare.

**Comment by RX14** [comment]
But I don't think the build of 0.24.0 is going to get fixed, since we're probably goinf to release 0.24.1 in the next week.

**Comment by docelic** [comment]
Hey, maybe you've misunderstood my comment.

Your comment:
"0.23.0+313 is not higher than 0.23.1 according to semver."

Is true. But I am telling you that the 0.24.0 pre-release packages which are provided for download identify their version as "0.23.0+313".

Which means that it is impossible to use macros to properly distinguish between 0.23.1 and 0.24.0, because 0.24.0 contains wrong version in its VERSION.

**Comment by RX14** [comment]
@docelic yes I understood. My answer to that was
>I don't think the build of 0.24.0 is going to get fixed, since we're probably going to release 0.24.1 in the next week.
