### ISSUE TITLE
Add some code only if the given lib is used

### ISSUE THREAD

**Issue by bew** [crystal-lang/crystal#5379]
I don't think there is an issue for this, so here it is!

This is the followup of the comments from @ysbaddaden & @asterite at https://github.com/crystal-lang/crystal/pull/3572#discussion_r89370775:

> @ysbaddaden: about the following lines: https://github.com/crystal-lang/crystal/blob/a4ffe5bd739ff678d1b7fde77f19788cde8b7b04/src/regex/lib_pcre.cr#L27-L28
> These two lines are the ones responsible for always linking apps against PCRE into the built binary, whatever if the application uses PCRE or not. It may be interesting to have a special macro for lib that would be called whenever that lib is actually used @asterite 
> [...]

> @asterite:
> The macro idea is good, we sometimes need to run code but only if the lib is actually used. The "problem" is that the compiler finds out if a lib is used when a lib fun is invoked, and at that point the macro would need to be expanded and typed... and then the codegen should put that code right where the macro definition exists. I'll try to think how to implement this, maybe it's not that hard. I'm thinking about something like `macro initialize`, but another (better) name should be good too.

**Comment by kojix2** [comment]
This issue may have already been resolved ?
