### ISSUE TITLE
Bug with multiple assignments of tuple types to a variable

### ISSUE THREAD

**Issue by jbomanson** [crystal-lang/crystal#5384]
Building the code

```crystal
x = typeof({1})
x = typeof({"b"})
```

brings up the message

```
BUG: trying to assign Tuple(Int32 | String):Class <- Tuple(Int32):Class
```

This happens both with Crystal 0.23.1 and Crystal 0.24.0-2 on Ubuntu 16.04 LTS.

**Comment by straight-shoota** [comment]
`typeof` is not the issue here. Minimal example:
```crystal
x = Tuple(Int32)
x = Tuple(String)
```
Probably something about generics, though I'm not sure.
This works:
``` crystal
x = Int32
x = String
```
