### ISSUE TITLE
Deque#rotate! divide by zero error

### ISSUE THREAD

**Issue by willcosgrove** [crystal-lang/crystal#5393]
`Deque#rotate!` has a divide by zero error for Deques with a size of 0.

https://play.crystal-lang.org/#/r/394r

**Comment by bew** [comment]
Good catch!
Should be an easy fix of you want to do it :) (early return if size == 0)

**Comment by willcosgrove** [comment]
I’d be happy to!  I’ll try to submit something tonight.
