### ISSUE TITLE
Release binary prebuilds at the same time as sources

### ISSUE THREAD

**Issue by anatol** [crystal-lang/crystal#5402]
Release 0.24.1 has been tagged in the repo 5 days ago. But there is still no binary prebuilds available at https://github.com/crystal-lang/crystal/releases Building packages at distros are blocked because of it.

Please consider source releases and required prebuilts available synchronously.

**Comment by RX14** [comment]
Two things:
- Firstly, we ensure that any tag can be built by the previous one. You can build 0.24.1 just fine with the 0.23.1 compiler. Our CI runs the previous release until we release a new version, to ensure we keep this promise. You don't need to wait for the binaries.
- Secondly, we consider a "tag" and a "release" to happen at different times. A tag on the git repo means just "we promise to release soon using this commit", and a release consists of a full release with binaries, docker container, and an announcement.

**Comment by anatol** [comment]
> we ensure that any tag can be built by the previous one.

Awesome! Is it an official statement that going to be supported with future releases? If yes it makes our packaging procedure even easier.

**Comment by bew** [comment]
Yes @anatol :smiley:

**Comment by RX14** [comment]
@anatol yup, it's official policy and something we actively work to make happen and have been working to that guarantee for some time. We regularly leave `TODO`s and make extra work for ourselves to make this guarantee.
