### ISSUE TITLE
Literal/Raw string support 

### ISSUE THREAD

**Issue by jeff-hykin** [crystal-lang/crystal#5404]
Trying to type a short string that needs several special characters, ex: `(P<prob_num>\d{1,3})\) +Section [A-F] \d+.\d+` is currently difficult using the `%q(), %q[], %q{}, %q<> and %q||` notation.

This `%q( \) )` will not run since the current literal quote doesn't allow ) to be escaped.

Heredocs work:
expected_result = <<-'LITERAL'
(P<prob_num>\d{1,3})\) +Section [A-F] \d+.\d+
LITERAL

But heredocs can be unwieldy for common use. 
Ruby: `replace( '([\dA-Z\)])', with:'Problem \g<1>')`
Crystal: 
```
pattern = <<-'HERE'
([\dA-Z\)])
HERE
replacement = pattern = <<-'HERE'
Problem \g<1>
HERE
replace( pattern, with: replacement)
```

**Comment by larubujo** [comment]
not seem difficult to me:

```
"(P<prob_num>\\d{1,3})) +Section [A-F] \\d+.\\d+"
```

just 3 letters more vs. 605
