### ISSUE TITLE
Some parts of crystal still use "doc" instead of "docs"

### ISSUE THREAD

**Issue by GloverDonovan** [crystal-lang/crystal#5405]
Hello,

I've been experimenting with the many features of crystal and absolutely love the idea behind `crystal docs`; however, I came across some parts of crystal where `doc` was still being used instead of `docs` (I actually thought it was `doc` at first, see crystal-lang/crystal-book#158).

I did some ag work and the only issues I found were in `Makefile`, `gitignore.ecr` (used in `crystal init`), and `man/crystal.1`. I plan to submit a pull request for these files. Hope this helps!

For reference, see #5217 and #4937.

**Comment by straight-shoota** [comment]
Awesome! 

I don't know how I did miss all these places... For #5217 I did actually grep for all occurences of `doc` in the repo to see if it needs to be updated. 🤷‍♂️

**Comment by straight-shoota** [comment]
I've double checked again and found the following:
* In `src/compiler/crystal/command/docs.cr` there is reference (in a comment) to `src/compiler/crystal/tools/doc.cr` which does not exist any more (even before the renaming of #4937).
* But we might consider renaming `src/compiler/crystal/tools/doc/` to `src/crystal/tools/docs/` to match the tool name.

**Comment by GloverDonovan** [comment]
Should I remove the comment from `src/compiler/crystal/tools/doc.cr`in the pull request?

About renaming, would the module name still be `Crystal::Doc`? I'm not sure if renaming the directory would require a lot of other things to be changed as well.

**Comment by straight-shoota** [comment]
I guess you could change the comment to the real location `crystal/tools/doc/`.

The other part should not be in this PR. And it's probably not worth the effort. I don't think it matters really. The internal compiler module can be called `Crystal::Doc` while the external command is `docs`, that' schouldn't be a big deal.

**Comment by GloverDonovan** [comment]
I agree with you and fixed the comment, should be ready to be merged now.
