### ISSUE TITLE
[Formatter] Fails to format a few files

### ISSUE THREAD

**Issue by paulcsmith** [crystal-lang/crystal#5416]
Hi there!

 There were a few files that fail to form. I've left permalinks to them:

* [DONE] this was actually a syntax issue (see #5417) https://github.com/luckyframework/lucky_record/blob/2368ca92efbc01db78a2f7e1d8c4fc99cde6ab12/src/lucky_record/associations.cr
* https://github.com/luckyframework/lucky/blob/1158f15a6f29bdeedb5b25ee09f4d4ff9eff4dca/src/lucky/flash.cr The problem line is: https://github.com/crystal-lang/crystal/issues/5416#issuecomment-352920676

If you'd prefer I opened separate issues for each of these, I can do that.

Thanks so much!

### The first file had a syntax error

I opened an issue for it because it actually works, but probably shouldn't

https://github.com/crystal-lang/crystal/issues/5417

**Comment by bew** [comment]
With a quick look I spotted a missing `%` (`}` => `%}`) at https://github.com/luckyframework/lucky_record/blob/2368ca92efbc01db78a2f7e1d8c4fc99cde6ab12/src/lucky_record/associations.cr#L3

**Comment by paulcsmith** [comment]
Thanks @bew! Strange that it compiles and seems to work just fine w/o it :S

I think the flash one doesn't have any obvious syntax issues though

**Comment by bew** [comment]
For the flash one, it looks like this line [flash#L109](https://github.com/luckyframework/lucky/blob/1158f15a6f29bdeedb5b25ee09f4d4ff9eff4dca/src/lucky/flash.cr#L109) is giving a hard time to the formatter.. maybe a bug? Removing the dot after `self` fix it.

**Comment by paulcsmith** [comment]
@bew how can you tell which line the formatter is having issues with. And yeah it seems like that is the problem. I'm guessing it should work though since it is valid syntax. For now I'll remove it though so I can format it :D

**Comment by bew** [comment]
@paulcsmith the formatter gave me this ___weird___ exception:
```
expecting ,, not `], `, at :109:23 (Exception)
```
and `:109:23` gave me the `:line:column` of the error

**Comment by paulcsmith** [comment]
@bew Hmm, when I ran it, the formatter said it failed, but I didn't see an exception. Is there some kind of verbose option? I tried running --help but I don't see anything like that

**Comment by bew** [comment]
Which version are you using? I'm using crystal 0.24.1, not sure if it was already available in 0.24.0

**Comment by paulcsmith** [comment]
Oh that must be why. I'm on 0.23.1 👍 

I'll be sure to look out for that when 0.24.1 is realeased

**Comment by bew** [comment]
We're all waiting for that release :smiley:
