### ISSUE TITLE
Incomplete implementation of percent array literals

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#5418]
The percent array literals `%i` (array of symbols) and `%w` (array of words) currently do not support nested delimiters. All other percent literals like `%q`, `%x`, `%r` do.

```crystal
%q((foo)) # => "(foo)"
%i((foo)) # =>unexpected token: )
%w((foo)) # =>unexpected token: )
```

Individual array entries are separated by a space character which means, they need to be escaped to be used inside a string/symbol. Escaped spaces are not recognized by the compiler, instead the backslash used to denot the escape sequence is added to the string/symbol.

```crystal
%w(foo\ bar) # => ["foo\\", "bar"]
%i(foo\ bar) # => [:"foo\\", :bar]
```

All examples work as expected in Ruby, but not in Crystal.

**Comment by RX14** [comment]
I think we should actually discuss the second case, and if we want to be the same as ruby there. Or provide an option.

**Comment by straight-shoota** [comment]
Yes, backslash escapes generally work in percent literals.
In Crystal you can escape any character with a backslash. If it has no special meaning, it evaluates to the blank character. So, `\ ` should always denote a space characte. It can be argued if the space should be treated as literal space (word separator resulting in `[:"foo bar"]`) or as escaped space (not a word separator: `[:foo, :bar]`), but certainly not as a backslash plus literal space (`[:"foo\\", :bar]`) which is the case here.

I think it makes very much sense to treat it as an escaped space which does not separate words.
