### ISSUE TITLE
Allow inheriting from primitives (was: Unable to inherit Int32)

### ISSUE THREAD

**Issue by alex-fedorov** [crystal-lang/crystal#543]
```crystal
struct Int
  struct Null < Int32
  end
end
```

renders:

```
Error in ./src/active_record.cr:4: Int32 is not a class, it's a struct

  struct Null < Int32
                ^~~~~
```

**Comment by asterite** [comment]
I don't think we'd like to inherit primitive types. There's also the question about how to create an instance of them, because right now the only way it through literals...

**Comment by jhass** [comment]
I turned this into a RFC, however I agree that we should most likely reject it and favour composition instead. We can look into something like `BasicStruct` analogous to Ruby's `BasicObject` that would allow to build an essentially no cost wrapper, similar to what i did for #1459

**Comment by asterite** [comment]
Since primitives are structs and inheriting non-abstract structs is now disallowed, there's no way to inherit primitives (and I think that's something good). I'm closing this.
