### ISSUE TITLE
Production problems

### ISSUE THREAD

**Issue by thiamsantos** [crystal-lang/crystal#5443]
What are the major problems that would be faced if I choose to use crystal in a production project?

**Comment by shevegen** [comment]
A bit generic question that depends on other points as well, such as whether your production project depends on, say, windows.

Can you give an example for what kind of production project you would, independent of the programming language, envision?

**Comment by thiamsantos** [comment]
Sorry for being too generic. My app consists basically of a REST API that uses PostgreSQL as main database and Redis for cache. It will be deployed on heroku or other similar service. Windows support is not a issue.

**Comment by RX14** [comment]
This is better off asked in gitter, irc, or the mailing lists. This is an issue tracker, questions are better off asked elsewhere in the future.

I'm closing this, but feel free to continue discussion.

**Comment by kostya** [comment]
Crystal don't have child problems already for some years, we used it in production in some projects, and all just works (no memory leaks, no unexpected crushes, ...). All problems that you can have is lack of libraries (just as we luck of ActiveRecord, and it analogs just too limited), and sometimes luck of parallelism, but this is needed for really specific tasks. So all common tasks, like highload web applications solves by running many daemons(workers) and proxing (like nginx, haproxy)
