### ISSUE TITLE
Type deduction complains about missing Enumerable#each of unrelated class instance

### ISSUE THREAD

**Issue by Papierkorb** [crystal-lang/crystal#5445]
Hi,

In my code, I do a globbing lookup akin to `Dir[*some_usergiven_patterns]`.  The method this Dir returns is restricted to `Array(String)` as result type, which works great with being `Dir.[] : Array(String)` too.

Now, I have a class further down which accepts and stores an `Enumerable(String)` in an instance variable.  This enumerable happens to be generated by said method above.  For some reason, the Crystal compiler complains that `abstract 'def Enumerable(T)#each(&block)' must be implemented by Dir`.

This worked fine in Crystal versions before `0.24.x`.  Also, the compiler is correct: `Dir#each(&blk)` is indeed missing, and this should be fixed.  Maybe by `Dir` not being an `Enumerable(String)` itself.  However, the compiler shouldn't complain in any case, as I never pass around an instance of `Dir`.

## Example snippet

```cr
class Foo
  def initialize(@f : Enumerable(String))
    @f.each{ } # ERROR
    # f.each{ } # This is fine.
  end

  def bar; @f.each{ }; end # Same ERROR
end

Foo.new(Dir["*"])
```

Thanks

**Comment by bcardiff** [comment]
Note that although this occur in Dir, the underlying limitation of the compiler is that the compiler is not enforcing that abstract methods of generic modules are implemented.

The compiler does check for the implementation of abstract method of non generic modules though.

**Comment by Papierkorb** [comment]
A trip-wire in bindgen just notified me indirectly that this issue is now fixed: https://github.com/Papierkorb/qt5.cr/issues/9 per https://github.com/Papierkorb/bindgen/commit/a3c4376eebf0303962e613e5072d735837c24f1a

Thanks
