### ISSUE TITLE
Naming of the directory containing prebuilt binary

### ISSUE THREAD

**Issue by sifmelcara** [crystal-lang/crystal#5446]
Hello,
I noticed that the naming convention of directory containing prebuilt binary have been changed:
```
$ tar -tf v0.24.1.tar.gz | head -n1
crystal-0.24.1/
$ tar -tf crystal-0.24.0-2-linux-x86_64.tar.gz | head -n1
crystal-0.24.0-2/
$ tar -tf crystal-0.24.1-2-linux-x86_64.tar.gz | head -n1
crystal-0.24.1/
```
I think the top directory inside `crystal-0.24.1-2-linux-x86_64.tar.gz` should be `crystal-0.24.1-2`.

Is this an intended change?

It confused me when I trying to bootstrap `0.24.1` compiler using `0.24.1` prebuilt binary, I extract them using `tar -zxf` under the same directory, then they both extracted to the same directory and their content messed up together...

cc @RX14 who released the binary on Github. Thanks!

**Comment by RX14** [comment]
Good catch.

A robust workaround is to use the `--strip-components=1` tar option, and then an explicit `-C dirname` option to extract everything into `dirname` directly though.

**Comment by sifmelcara** [comment]
Thanks for the quick reply!
