### ISSUE TITLE
Tool format failure regarding multiple assignment. 

### ISSUE THREAD

**Issue by yxhuvud** [crystal-lang/crystal#5451]
The following code fails `crystal tool format` in crystal 0.24.1:

```
positions[0], positions[15] =
                 positions[0], positions[15]
```

Reduced from my actual example in my code that was long enough to warrant line breaking.

**Comment by sdogruyol** [comment]
I'm pretty sure @MakeNowJust can handle this :+1:

**Comment by MakeNowJust** [comment]
I'm here. Is the expected result this?

```crystal
positions[0], positions[15] =
  positions[0], positions[15]
```

In fact single assignment with newline after equal is formatted to:

```crystal
positions =
  positions
```

So I think the above is expected.

**Comment by yxhuvud** [comment]
That is certainly what I'd expect to happen yes.
