### ISSUE TITLE
Add documentation for Readline API

### ISSUE THREAD

**Issue by GloverDonovan** [crystal-lang/crystal#5455]
Not sure if there's already an issue for this. I tried searching but couldn't find anything.

The [Readline API](https://crystal-lang.org/api/master/Readline.html) is missing documentation. Would it help to have one central issue for all incomplete documentation?

**Comment by larubujo** [comment]
readline should be shard imo

**Comment by RX14** [comment]
@larubujo I agree but I think that's a separate issue.

**Comment by Jens0512** [comment]
Shard or not, I also came here to request docs.

**Comment by RX14** [comment]
Please reopen at https://github.com/crystal-lang/crystal-readline, see #8364.
