### ISSUE TITLE
Version reporting feature

### ISSUE THREAD

**Issue by lebogan** [crystal-lang/crystal#5459]
As someone new to Crystal, I have to say this language is awesome. As a hobbyist I like to play with language features. I also like to keep app or lib versions in one place so I don't forget to update them.

With version 0.24.1 and shards 0.7.2 I am now able to put this in my versions.cr file
```
VERSION = {{ `shards version #{__DIR__}`.chomp.stringify }}
```
In my app, I can refer to the app version using:
```
puts "app v#{App::VERSION}"
```
When I build a new app, if I want that feature, I have to remember how to do that or have a snippet stashed somewhere. Would it make any sense to have the init command write that initially in the version.cr file? Will that break something down the line?

Thanks to all for this awesome (repeat) language. I really look forward to version 1.0.0!

Lewis

**Comment by RX14** [comment]
#5428 :)

**Comment by noraj** [comment]
Is that normal that `crystal docs` doesn't resolve it but just the `__DIR__`?

![image](https://user-images.githubusercontent.com/16578570/224575710-416d50e2-a928-447b-9d42-29eed379d03c.png)
