### ISSUE TITLE
Compiler bug in non-sense line of code using NamedTuple

### ISSUE THREAD

**Issue by amoeba** [crystal-lang/crystal#5464]
Thanks for an awesome language, compiler, etc. I'm really enjoying playing around. 

I encountered a compile-time bug, which the compiler helpfully asked me to submit a bug report for:

> Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues

I've isolated the offending line of code which, when removed, removes the compiler bug/error and, when re-added, re-introduces the compiler bug/error. The offending line of code is this non-sense I mistakenly wrote:

```crystal
nt = NamedTuple.from_json(parsed)
```

An MRE for this bug is:

```crystal
require "json"

NamedTuple.from_json("{}")
```

While the MRE is sufficient, the full source tree is available at  https://github.com/amoeba/treestats-lucky/tree/c2b2b0abc0474f00117bfdb22da9095ca276ee45 and the compiler log is available at https://gist.github.com/amoeba/4057404c4f66c37251225088dd40dcc7. One (maybe important) note for reading the log is that I was running Lucky's `lucky dev' server which was doing the compiling for me.

Other notes:

```
> crystal --version
Crystal 0.23.1 (2017-10-12) LLVM 4.0.1
```

OS: MacOS 10.13.2

If this Issue isn't useful, please feel free to close, or ask me to provide any more info to help reproduce it.

**Comment by Papierkorb** [comment]
@amoeba  That's a bug in Crystal, but this syntax will never work. See #5504

**Comment by amoeba** [comment]
Thanks @Papierkorb. That matches my understanding. I've since fixed the non-sense line of code in my codebase. Should I close this issue as a dup of #5504 or leave it open?

**Comment by Papierkorb** [comment]
As the other bug report has more traction, I'd say close this one.

**Comment by amoeba** [comment]
Thanks @Papierkorb
