### ISSUE TITLE
EventSource client

### ISSUE THREAD

**Issue by jackbit** [crystal-lang/crystal#5469]
How to handle EventSource like javascript in crystal?
https://developer.mozilla.org/en-US/docs/Web/API/EventSource

example:

```
event_source = new EventSource(url)
event_source.on_message do |message|
  puts message
end
```

The idea is similar to websocket, but i tried HTTP::Websocket, it did not work. Thanks.

**Comment by oprypin** [comment]
Please close this, as it's not an issue, but a question.
Check https://crystal-lang.org/community/ for places to ask a question.

Long story short, there's definitely no implementation in Crystal standard library but it looks like just a keep-alive HTTP connection with a simple format https://html.spec.whatwg.org/multipage/server-sent-events.html#parsing-an-event-stream

**Comment by ysbaddaden** [comment]
Why? It's simpler than websockets, plain text rather than binary, and unidirectional. Perfect for pushing events.

There is no implementation in Crystal. It can be implemented rather simply, but usage ain't as ubiquitous as websockets, so I don't think stdlib will provide support this this.

**Comment by d-Pixie** [comment]
Belated other considerations between Server Sent Events/EventSource and Websockets:
* EventSource has automatic reconnect
* EventSource supports catching up to a message stream
* EventSource is HTTP, so it is supported by every HTTP tool, proxy etc on the planet, Websockets is a completely new protocol
* EventSource has better browser support and can be polyfilled using JS, Websockets can't
