### ISSUE TITLE
Wrong line-number in run-time error when using $0 in crystal v0.24.1

### ISSUE THREAD

**Issue by drosehn** [crystal-lang/crystal#5470]
I used homebrew to compile the new version of crystal on MacOS 10.10.5 (Yosemite):

```cr
# crystal version
Crystal 0.24.1 (2017-12-27)

LLVM: 5.0.1
Default target: x86_64-apple-macosx
# uname -a
Darwin garance.host.name 14.5.0 Darwin Kernel Version 14.5.0: Sun Jun  4 21:40:08 PDT 2017; root:xnu-2782.70.3~1/RELEASE_X86_64 x86_64

```
*(the following also happened on a different Mac running `10.11.<latest> (El Capitan)`, but I don't have the uname info for that).*

I have a program where very early in the main routine it does:
```cr
exec_fullpath = File.expand_path($0)
if "-" == $0[0..0]
    #	Stupid Terminal.app in Yosemite will start this program
    #	in such a way that PROGRAM_NAME == "-sessmenu".  Ugh!
    if SessGBLS.exec_path != nil
      exec_fullpath = "#{SessGBLS.exec_path}/#{$0[1..-1]}"
    end
end
```
When I compile and run the program, I get:
```cr
Nil assertion failed (Exception)
  from /opt/homebrew/Cellar/crystal-lang/0.24.1_1/src/nil.cr:106:5 in 'not_nil!'
  from sessmenu.cr:1349:8 in '__crystal_main'
  from /opt/homebrew/Cellar/crystal-lang/0.24.1_1/src/crystal/main.cr:11:3 in '_crystal_main'
  from /opt/homebrew/Cellar/crystal-lang/0.24.1_1/src/crystal/main.cr:112:5 in 'main_user_code'
  from /opt/homebrew/Cellar/crystal-lang/0.24.1_1/src/crystal/main.cr:101:7 in 'main'
  from /opt/homebrew/Cellar/crystal-lang/0.24.1_1/src/crystal/main.cr:135:3 in 'main'
```
In my program, `sessmenu.cr:1349:8 in '__crystal_main'` matches the line:
```cr
    if SessGBLS.exec_path != nil
```
I'm not sure if it's clear here, but `SessGBLS.exec_path` is at character ":8".

Now I can't imagine how there could be anything wrong with that line, but I make a variety of changes trying to fix it, including changing the logic of the program so that I use `""` (null string) instead of `nil` when the variable is not set.  I still get an error message about `Nil assertion failed (Exception)` which is pointing at that `if`-statement.

It did not take much time before I noticed that this program uses the older `$0` global variable instead of the correct crystal constant of `PROGRAM_NAME`, and I did know that support for `$0` was removed in version 0.24.  So I change all the `$0`s to `PROGRAM_NAME`s, and now the program is working fine.

I have a number of other crystal applications I need to recompile for 0.24.1, and about 10 other very important things which must be done by Friday *(such as taxes...)*.  So I can't spend a lot of time trying to come up with the minimal perfect example of this error.  But I thought I'd at least mention that if some program uses `$0` with the new version of crystal, then the error message it generates might point at the wrong line.  I don't know if this is a problem that's unique to MacOS.

So if you see a `nil`-related error which doesn't make any sense, check to see if the program is using `$0`!

Congrats on getting 0.24.1 released.  Thanks!

**Comment by larubujo** [comment]
more or less dup of #4776

**Comment by drosehn** [comment]
Hmm.  This seems different to me.

My point is that the traceback claims the error is at `sessmenu.cr:1349:8`, but that line does not have any error in it.  The real error is four lines earlier.

Although I see that I misunderstood the change with `$0`.  I thought it had been removed, but I see it's now a value set by regex matches, same as `$1`, etc.  That change makes sense, of course.

**Comment by drosehn** [comment]
To add a little info:  Also, when I changed `File.expand_path($0)` to be `File.expand_path(PROGRAM_NAME)`, then I got the same error message except that it pointed at line 1350.  But at that point the error was really on the `if "-" == $0[0..0]` line, which was line 1346.

**Comment by drosehn** [comment]
This comes up in a program of mine which is over 1000 lines, so I'd hate to post it as an example here.  There's a real coding error in the program, it's just that the error message points to the wrong line.

I've tried to reduce that program to a minimal example, but sometimes after I remove lines the error message includes the correct line number.  In fact I have tried removing large sections of code **after* the line with the runtime error (so it is code which cannot possibly be executed), and removing that code causes the runtime error to print the correct line number.

I'll keep trying to come up with a better example, but that will have to wait a few days.

**Comment by drosehn** [comment]
Okay.  I've spent the last 10 hours of today trimming down a 1600-line program into a 100-line program which will show various weird things depending on what edits you make to it.  I'm sure everyone would like a much shorter example program, but 10 hours is about all the patience I have for trying to isolate this.  I do hope this will be helpful to anyone who wants to pursue the weirdness in the error message.

Here's the program:

**Comment by drosehn** [comment]
```cr
#
# -------+---------+---------+-------- + --------+---------+---------+---------+
# Copyright (c) 2016-2018    - Garance Alistair Drosehn <gad@FreeBSD.org>.

#   The real error(s) in this program is using $0 instead of PROGRAM_NAME
#   in some places.  But the compiler-related issue is that the run-time
#   error message points to the wrong line&column number.  What's worse,
#   making changes (*) to this program may cause the line&column numbers
#   as displayed by the error message to move around quite a lot.
#   (* -> making changes which are unrelated to fixing the real error)

#	    To compile and run this program:
RUNME_CMD = %(
  crystal build err_LNUMs.cr -o /tmp/err_LNUMs && /tmp/err_LNUMs --version 2>&1 | grep err_LNUMs
)

#   ANSI color info
CLR_BOLD = "\033[0;1m"
CLR_NONE = "\033[0m"

# -------+---------+---------+-------- + --------+---------+---------+---------+
class SessionMenu
    property user_modifier

    def initialize(@user_modifier : String)
    end
end

# -------+---------+---------+-------- + --------+---------+---------+---------+
class PgmGBLS
    CRYS_VERSION = "crystal #{Crystal::VERSION} [#{Crystal::LLVM_VERSION}]"

    @@print_version = false

    @@exec_path : Nil | String = nil
    @@smenu : Nil | SessionMenu = nil

    def PgmGBLS.exec_path
	return @@exec_path
    end
    def PgmGBLS.smenu
	return @@smenu
    end

    def PgmGBLS.userargs_OK?
	opterr = false
	ARGV.each { |thisarg|
	    case thisarg
	    when "--version"
		@@print_version = true

	    when /^--vers_rx$/
		@@print_version = true

	    else
		STDERR.printf "# Invalid argument:  %s\n", thisarg
		opterr = true
	    end
	}

	return !opterr
    end
end

# -------+---------+---------+-------- + --------+---------+---------+---------+
#   Main program.
#

unless PgmGBLS.userargs_OK?
    STDERR.printf "# Aborted...\n"
    sleep 3
    exit 1
end
printf "#dbg:  PgmGBLS.exec_path=%s\n", PgmGBLS.exec_path.inspect

printf "# ---- %s%s:%d:34%s   <---  real error should be at\n",
    CLR_BOLD, File.basename(__FILE__), __LINE__ + 1, CLR_NONE
exec_fullpath = File.expand_path($0)			# Real error #1
if "-" == $0[0..0]					# Real error #2
    #	Just some comment
    #	lines to put space
    #	between 'exec_fullpath ='
    #	And 'if PgmGBLS.exec_path.
    #	Often the error shows up on 'if PgmGBLS.exec_path'
    #   even though the real error is referencing $0, above.
    #printf "#dbg:  inside the 'if \"-\" == $0[0..0]'\n"
    if PgmGBLS.exec_path != nil
      exec_fullpath = "#{PgmGBLS.exec_path}/#{$0[1..-1]}" # Real error #3
    end
end

printf "%s compiled by %s\n", File.basename(PROGRAM_NAME), PgmGBLS::CRYS_VERSION
exit 0

#   All the code after this is compiled but never executed.

lcl_menu = PgmGBLS.smenu
if lcl_menu && false
    keep_looping = true
    while keep_looping
	user_ans = "stop"

	case user_ans
	when /^@(\w+)\s*$/
	    lcl_menu.user_modifier = user_ans

	when "exit", "quit", "stop"
	    #	okay, we'll exit!
	    STDERR.printf "\n"
	    keep_looping = false
	    break
	end

    end
end

exit 0
```

**Comment by drosehn** [comment]
Okay.  So there are three lines in here which are the real error.  If you modify:
```cr
exec_fullpath = File.expand_path($0)			# Real error #1
if "-" == $0[0..0]					# Real error #2
      exec_fullpath = "#{PgmGBLS.exec_path}/#{$0[1..-1]}" # Real error #3
```
to use PROGRAM_NAME instead of $0, this program will run without any errors (but ignore the line that the program itself prints out claiming that there will be an error):
```cr
#dbg:  PgmGBLS.exec_path=nil
# ---- err_LNUMs.cr:71:34   <---  real error should be at
err_LNUMs compiled by crystal 0.24.1 [5.0.1]
```

**Comment by drosehn** [comment]
But run the program as it is (including the `| grep err_LNUMs` command on the pipeline of commands), and you'll get:
```cr
# ---- err_LNUMs.cr:78:34   <---  real error should be at
  from err_LNUMs.cr:87:8 in '__crystal_main'
```

**Comment by drosehn** [comment]
Notice the `exit 0` line.  My understanding is that nothing should be executed after that line, and in any case you don't even get to that line when the program is using `$0`.  However, if you go down to the `case user_ans` and comment out the lines:
```cr
#	when /^@(\w+)\s*$/
#	    lcl_menu.user_modifier = user_ans
```
and then run the program (with the `|| grep`), you'll get:
```cr
# ---- err_LNUMs.cr:78:34   <---  real error should be at
  from err_LNUMs.cr:74:41 in '__crystal_main'
```
Instead of reporting the problem as being 9 lines after the real error, the runtime message now claims there's a problem 4 lines before the real error.

**Comment by drosehn** [comment]
Uncomment those lines, and then decide that you're curious as to whether we're getting inside of the `if "-" == $0[0..0]`.  Change this line:
```cr
    #printf "#dbg:  inside the 'if \"-\" == $0[0..0]'\n"
```
to remove the comment character.  That's just a plain print statement, which will let us know if we're inside the `if`.  This time you'll see:
```cr
# ---- err_LNUMs.cr:78:34   <---  real error should be at
  from err_LNUMs.cr:0:34 in '__crystal_main'
```
So now we're told that the problem is on line zero.  Great.

**Comment by drosehn** [comment]
For a long time while I was trying to reduce the size of this program, if you went to the `case thisarg` inside of `def PgmGBLS.userargs_OK?`, and if you commented out the lines:

```cr
	    when /^--vers_rx$/
		@@print_version = true
```
(which was the only regex in that `case` statement), you'd get a different line number in the error message.  But apparently I lost that behavior by the time I trimmed the program to what you see now.  I know I still had it happening an hour ago, but I must have lost it.

**Comment by drosehn** [comment]
And back when the program was still 200-300 lines long, there were a **lot** of changes I could make which would cause the output to be:
```cr
# ---- err_LNUMs.cr:343:34   <---  real error should be at
  from err_LNUMs.cr:343:34 in '__crystal_main'
```
... which is to say, the run-time error message pointed to the correct spot.  There were so many different changes which seemed to "correct" the error message, that I stopped checking for it.  And now I can't seem to trigger it.

**Comment by drosehn** [comment]
Going back to the program as I posted it, comment out the lines:
```cr
    if PgmGBLS.exec_path != nil
      exec_fullpath = "#{PgmGBLS.exec_path}/#{$0[1..-1]}" # Real error #3
    end
```
And you'll see a result of:
```cr
# ---- err_LNUMs.cr:78:34   <---  real error should be at
  from err_LNUMs.cr:79:4 in '__crystal_main'
```
Which is yet another difference in relative line&column numbers than the other examples.  In this case it's claiming the error is in the line `if "-" == $0[0..0]`, at the start of the character string `"-"`.

**Comment by drosehn** [comment]
I expect all these examples are just different results of a single bug somewhere.  But the fact that the behavior kept changing almost every time I tried to make the program smaller (and that most of those changes would trigger the **correct** error message...), it has been very frustrating to shrink the original 1600-line program down to more reasonable size.

**Comment by drosehn** [comment]
At one point I also tried doing something clever with `rescue`-ing the exception, and then having the rescue clause look through the backtrace to see if the error message had the correct line & column numbers.  As near as I could determine at that time, if you `rescue` the exception then the error message will always correctly point to the real error.

**Comment by drosehn** [comment]
The error message would point at other lines while I was attempting to trim it down.  But it's interesting to note that whenever I checked it, the message was always pointing at something appropriate to point to (like the first character of some variable, method call, or constant).  It never pointed to a letter in the middle of a variable name, or at a keyword of the language.

(except for the times it would point at line 0)

**Comment by drosehn** [comment]
asterite's comment #5567 reminded me about this PR, so I thought I'd go back and see if the program behaves differently when compiled by `crystal 0.25.1 [5.0.2]` (on MacOS).

All of the edits described above cause the `line-number:char-number` to change in about the same way as described above.

**Comment by drosehn** [comment]
It also occurred to me that **as far as the compiler is concerned**, the error is that `$0` has a value of `nil`.  Now **I** know that the real problem is that the code shouldn't be referencing `$0` in the first place, but the compiler doesn't care about that.

So if I add the lines:
```cr
if PROGRAM_NAME =~ /er.*NUMs/
   printf "#dbg: yes, PROGRAM_NAME matches the pattern '/er.*NUMs/'.\n"
   printf "#dbg:      and now $0=%s\n", $0.inspect
end
```
before the line:
```cr
printf "# ---- %s%s:%d:34%s   <---  real error should be at\n",
```
then the error goes away.  I guess that's pretty obvious, but I thought it might be of interest to mention it.  Whatever the problem is, it might not be tied to `$0` at all.  Maybe it just happens that `$0` was the variable referenced which had the value of `nil` when it was referenced.

**Comment by jhass** [comment]
Output with master (0.30.0-dev [8b3dba72b]):

```
bin/crystal build err_LNUMs.cr -o /tmp/err_LNUMs && /tmp/err_LNUMs --version 2>&1 | grep err_LNUMs
Using compiled compiler at `.build/crystal'
  from err_LNUMs.cr:78:34 in '__crystal_main'
# ---- err_LNUMs.cr:78:34   <---  real error should be at
```

I guess this can be closed then :)
