### ISSUE TITLE
Update docker image crystallang/crystal to the latest version

### ISSUE THREAD

**Issue by lbguilherme** [crystal-lang/crystal#5471]
The docker image _crystallang/crystal_ at https://hub.docker.com/r/crystallang/crystal/tags/ was last updated to 0.23.1, that was 5 months ago.

Please update it for 0.24.1 and following releases.

**Comment by josephcopenhaver** [comment]
I also noticed the Dockerfile in the project root does not use an immutable base-tag, it uses the latest of the project's docker image which could vary greatly between local cache and the remote docker repository. This makes docker builds much less reliable as cache creep occurs over time.

The ["release" dockerfile](https://github.com/crystal-lang/crystal/blob/5e17dd5e72e6cdd6ede4169191971df2c101db15/Dockerfile.release) uses an ubuntu base image which is not as problematic, but in my mind the [canonical project Dockerfile](https://github.com/crystal-lang/crystal/blob/5e17dd5e72e6cdd6ede4169191971df2c101db15/Dockerfile) and the people who use it will suffer from cache creep over time.

For example the docker build fails right now when attempting to build on a clean system with:

```bash
git clone https://github.com/crystal-lang/crystal
cd crystal
git checkout 0.24.1
docker build -t crystallang/crystal:0.24.1 .
```

in the project root.

In the past I greatly reduced this problem by publishing versioned base images to the project's docker repository or ensuring the project's base image was a version-pinned OS image. It also helps to have the CI build artifacts and run tests using docker and to repeat that process at least once daily even when there is no code-change to master. That would allow for incompatible 3rd party library creep to be detected earlier.

**Comment by matiasgarciaisaia** [comment]
Hi there!

Thanks for the reminder. I've just pushed a `0.24.1` tag, and updated the `latest` one to that.

If you can confirm it's working, we'll close the issue :)

Sorry about the delay!

**Comment by lbguilherme** [comment]
It's working. Thanks!
