### ISSUE TITLE
Instantiate HTTP::Headers with Hash or NamedTuple

### ISSUE THREAD

**Issue by vtambourine** [crystal-lang/crystal#5476]
Please correct me if I'm wrong, but so far the only way to create a meaningful `HTTP::Headers` object is to instantiate headers first and assign fields later:
```
headers = HTTP::Headers.new
headers["Content-Type"] = "application/json"
```

I suggest `HTTP::Headers.new` method can be overloaded to support creating headers collection from `Hash` or `NamedTuple`, like:

```
headers = HTTP::Headers.new("Content-Type": "application/json")
```

**Comment by straight-shoota** [comment]
You can use the hash-like literal syntax ([reference](https://crystal-lang.org/docs/syntax_and_semantics/literals/hash.html)):
```
HTTP::Headers{"Content-Type" => "application/json"}
```

**Comment by vtambourine** [comment]
Thank you, @straight-shoota, didn't know that about object.
