### ISSUE TITLE
0.24 missing pcre,event on linux-x86_64

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#5477]
crystal installed from releases page:

```
crystal eval 'p 1'
/usr/bin/ld: cannot find -lpcre
/usr/bin/ld: cannot find -levent
```

fixed after: `aptitude install libpcre3-dev libevent-dev`
is this bug or not, because previous versions installed without it.
This may be bug because crystal might use special compile flags for this libs (i not sure).

**Comment by RX14** [comment]
Not a bug, this is simply a change from the old packaging. We no longer bundle any prebuilt static libraries along with the compiler. Please use the APT repository, the package depends on all the things required to run basic crystal programs.
