### ISSUE TITLE
Missing API documentation for UUID 

### ISSUE THREAD

**Issue by NIFR91** [crystal-lang/crystal#5478]
On release v0.24.1 the struct UUID was created and SecureRandom.uuid was removed, but I cant find 
the API documentation on [master](https://crystal-lang.org/api/master/) nor [v0.24.1](https://crystal-lang.org/api/0.24.1/).

The only reference for the change is the section  [new features](https://github.com/crystal-lang/crystal/releases/tag/v0.24.1) on the release change log or reading the [source code](https://github.com/crystal-lang/crystal/blob/master/src/uuid.cr).

**Comment by bcardiff** [comment]
There is a missing reference to uuid in https://github.com/crystal-lang/crystal/blob/release/0.24/src/docs_main.cr
