### ISSUE TITLE
Local variable in `case` doesn't capture type in `when` (v0.24.1)

### ISSUE THREAD

**Issue by Qwerp-Derp** [crystal-lang/crystal#5482]
In 0.24.1, local variables declared in a `case` block are not automatically cast into a type when that type is in a `when` block's pattern. See the below code for an example.

This error does not occur with 0.23.1 (see [here](https://carc.in/#/r/3b8o) for a carc.in link to the result in 0.23.1).

## Code:

```crystal
alias Foo = Int32 | String

arr : Array(Foo) = [1, "2", 3]

case (foo = arr[0])
when Int32
  puts foo + 2
  # Error: no overload matches 'String#+' with type Int32
  # Overloads are:
  #  - String#+(other : self)
  #  - String#+(char : Char)

  # puts foo + 2
when String
  puts foo + "2"
end
```

**Comment by straight-shoota** [comment]
Minimal example:
```crystal
case (foo = 3.as(String | Int32))
when Int32
  foo + 3
end
```

It works if the assignment is put before the `case` but fails if it is inlined.
`pp typeof(foo)` inside the `when` fails with `undefined method 'foo'` which seems really off.

**Comment by MakeNowJust** [comment]
This code works and I am not sure that it should be fixed:

```crystal
case foo = 3.as(String | Int32)
when Int32
  foo + 3
end
```

**Comment by MakeNowJust** [comment]
A patch is [here](https://github.com/MakeNowJust/crystal/tree/fix/crystal/5482).

**Comment by bcardiff** [comment]
@MakeNowJust yes please 👍 . I recall you refactor some treatment of the ast regarding parens and expression. This issue is a regression of that refactor right? Did you bisect when it was introduced?

**Comment by asterite** [comment]
The code should work with parentheses. It seems it worked in previous versions, and I think it should work. It's just very common to write `(var = ...)` inside `if`, `case`, etc., to make it clear that it's an assignment.
