### ISSUE TITLE
bug: inheriting `self` twice produces `Person+ is not a class, it's a Person+`

### ISSUE THREAD

**Issue by thefliik** [crystal-lang/crystal#5495]
# Bug
Using https://play.crystal-lang.org/#/r/3bhz v0.24.1, the following code produces an error:

```
class Person
  class Current < self
  end

  class Destroyed < self
  end  
end
```

Error: `Person+ is not a class, it's a Person+`

After [posting about it on StackOverflow](https://stackoverflow.com/q/48045502/5490505), it was suggested that the behavior is a bug.

### Additional info
If I do:
```
class Person
  class Current < Person
  end

  class Destroyed < Person
  end
end
```
Then everything works fine.

If I do:
```
class Person
  class Current < self
  end
end
```
Then everything works fine.

**Comment by asterite** [comment]
Probably a `devirtualize` call is missing somewhere (if someone wants to fix this, until I eventually fix this (sounds easy)).

**Comment by asterite** [comment]
As a side note, `self` here looks pretty cryptic. I'm now more inclined to remove `self` type restriction and resolution from the language.

**Comment by thefliik** [comment]
@asterite by
>  remove self type restriction and resolution from the language

Do you mean: remove the ability to
```
class Person
  class Current < self
  end

  class Destroyed < self
  end  
end
```
?

**Comment by asterite** [comment]
Yes:

```crystal
class Person
  class Current < Person
  end

  class Destroyed < Person
  end  
end
```

**Comment by asterite** [comment]
(but it's just a thought, might not happen after all)

**Comment by thefliik** [comment]
Well I can certainly appreciate an argument to remove it from a maintainability / development standpoint -- I can't speak to such an argument. From a readability / usability standpoint however, I like the current functionality (though that may reflect my background as a Ruby developer).

I ran into the issue in the first place when I was playing around porting some of my Ruby code over to Crystal. I was creating a macro that would add `Current` & `Destroyed` classes to a class. Being able to inherit self made it easy.

```
macro define_states
  class Current < self
  end

  class Destroyed < self
  end
end

class Person
  define_states
end
```

In Ruby I accomplish this with a module, but it's even _easier_ to do in Crystal with a macro. I imagine I could add an argument to the macro to use it like `define_states(Person)`, but using `self` feels more elegant to me :). And, frankly, it's meaning just seems obvious to me ("oh yeah, this class inherits from whatever class this is defined in"). But again, this could just be because of my Ruby background.

I find the Crystal version of the code to be a _lot_ more readable then the ruby version:

```
const_set("Current", Class.new(self) {})
```

**Comment by thefliik** [comment]
And, given that I'd be using this particular macro all over the place, needing to add in the appropriate argument would be mildly annoying.
```
class Person
  define_states(Person)
end

class Job
  define_states(Job)
end

class Company
  define_states(Company)
end
```

**Comment by thefliik** [comment]
On a somewhat unrelated note, I think the coolest thing about Crystal is how _accessible_ it is. I taught myself Ruby as part of a volunteer project to build an app for a nonprofit. Because of the great syntax and relative flexibility I was able to go from zero to Rails app in a matter of months. I had initially thought about building the app in Javascript, before deciding Ruby & Rails would be a better choice. I've since delved into Javascript and Typescript, as well as some C++, and they are nowhere _near_ as easy to pick up (affirming, for me, my original decision to pick Ruby).

By its very nature as a statically typed, compiled language, I'm not sure if Crystal can every be _quite_ as easy as Ruby to learn (though then again, maybe Types (and everything they open up in IDEs) will make Crystal _easier_ to learn), but hands down I'm excited about Crystal because of just how approachable it is. I could imagine a future in which Crystal is a great language for someone to learn first.

**Comment by jhass** [comment]
Here's a technical reason to keep the self restriction:

```cr
module Foo
  def add(other : self)
  end
end

class A
  include Foo
end

class B
  include Foo
end

A.new.add(B.new)
```
https://carc.in/#/r/3c7u

But we diverge from the issue...

**Comment by MakeNowJust** [comment]
@jhass We can get same result with macro:

```crystal
module Foo
  macro included
    def add(other : {{@type}})
    end
  end
end

class A
  include Foo
end

class B
  include Foo
end

A.new.add(B.new)
```

However I'm not sure it is right way.

**Comment by jhass** [comment]
Me neither, it seems difficult to explain and reason to newcomers

**Comment by asterite** [comment]
The problem is what `self` means. Is it equal to the type that defines it, or to the effective type that's executing the method?

For example, should this compile?

```crystal
class Foo
  def foo(other : self)
  end
end

class Bar < Foo
end

class Baz < Foo
end

bar = Bar.new
baz = Baz.new
bar.foo(baz)
```

**Comment by jhass** [comment]
Maybe it needs to become more explicit, something akin to Java's wildcard type restrictions (`? extends Foo`, `? is self`), just brainstorming...

**Comment by asterite** [comment]
The above is the cause for [this bug](https://github.com/crystal-lang/crystal/issues/5249#issuecomment-342099888). Also with macro methods. Because the method ends up in the deepest class, comparing against `self` doesn't work. But in this case I don't know what the solution is. There's no type that you can compare against. Removing `self` means the only way you can do it is by checking it at runtime (the solution we ended up with).

That's why I'd like to remove `self` as a type restriction: it doesn't work as one would expect.

**Comment by thefliik** [comment]
Hmm, before this conversation I interpreted `self` like so

```
class Person
  this = self
  class Current < this
  end
end

class Foo
  this = self
  def foo(other : this)
  end
end
```

Now I'm wondering if the second example should be interpreted as

```
class Foo
  def foo(other : this)
    this = self
  end
end
```
?

I hadn't really thought about it before, but now I'm realizing I'm not sure if the type of `Foo` is equal to the type of `Foo.new`. 

Whichever is the correct interpretation though, it might not be what someone expects the first time they view the language, but once told the right way of looking at it I think it'll be readily understandable.

Indeed, I can see arguments for either interpretation of the `def foo` method. On the one hand, `def foo` is executing in the context of the `Foo` class, on the other hand, the contents of methods refer to the instance calling them, so maybe method arguments are part of the instance context. I feel like, so long as things are consistent, I can find either explanation understandable.
