### ISSUE TITLE
build issue with --release flag - Assertion failed: getOrCreateRegularScope

### ISSUE THREAD

**Issue by S-YOU** [crystal-lang/crystal#5497]
I am not sure this is LLVM issue or related to amber.
When I tried to build with --release flag, I got following error.
It is ok without --release flag though. Any idea what could be the issue?

```
% crystal build --release src/hello.cr
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
Assertion failed: (cast<DISubprogram>(Scope)->describes(MF->getFunction())), function getOrCreateRegularScope, file /var/cache/omnibus/src/llvm/llvm-3.9.1.src/lib/CodeGen/LexicalScopes.cpp, line 159.
/opt/crystal/bin/crystal: line 102: 63272 Abort trap: 6           "$INSTALL_DIR/embedded/bin/crystal" "$@"

% crystal -v
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
Crystal 0.24.1 [80a975c] (2017-12-22)

LLVM: 3.9.1
Default target: x86_64-apple-macosx
% amber -v
Amber CLI (amberframework.org) - v0.6.0
```

**Comment by straight-shoota** [comment]
Looks similar to #4719 though the LLVM error is slightly different.

The broken kqueue warning seems unrelated (but maybe a different issue?)

**Comment by RX14** [comment]
Looks like #4719 to me. Please install with home brew, its using llvm 5 there and the problem is fixed.

**Comment by S-YOU** [comment]
Thank you. looks like linked LLVM was old when I compiled it. And sorry, I can't find a duplicate.
