### ISSUE TITLE
`skip` is still in API docs

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#5509]
See [api/0.24.1/Crystal/Macros.html#skip](https://crystal-lang.org/api/0.24.1/Crystal/Macros.html#skip%3ANop-instance-method) but https://github.com/crystal-lang/crystal/pull/4709

**Comment by RX14** [comment]
Please search for existing issues before opening an issue.

Duplicate of https://github.com/crystal-lang/crystal/pull/5488.
