### ISSUE TITLE
Remove `crystal deps`

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#5510]
I believe `crystal deps` adds only confusion. When you get an error from it, you get (just an example):

```
Missing shard.yml. Please run 'shards init'
```

At this point `shard` is **the** package manager for Crystal, and it's well known. I don't think we should keep `crystal deps` around.

**Comment by RX14** [comment]
Very much 👍 . I've also had this at the back of my mind, never got around to making an issue...
