### ISSUE TITLE
C callback example on docs causes compile errors

### ISSUE THREAD

**Issue by tomjw64** [crystal-lang/crystal#5528]
**System:**
OS: WSL running Ubuntu 16.04
Crystal Version Info:
```
Crystal 0.24.1 (2017-12-22)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```
**Issue:**
Thought I'd try my hand at passing a closure to a C function using the [example on the crystal-lang docs](https://crystal-lang.org/docs/syntax_and_semantics/c_bindings/callbacks.html#passing-a-closure-to-a-c-function) as a learning exercise. I ran into a couple issues trying to make the example work.

An exact copy (aside from an `@Link` I added) of the example code yields the following error:
```
Error in ticker.cr:7: class variable '@@box' of Ticker is not nilable (it's Box(Proc(Int32, Nil))) so it must have an initializer

  @@box : Box(Int32 ->)
```

I thought I'd just initialize it as an empty Array to just get past that line, given that there's probably some obvious solution that I missed. I changed lines in the example from:
`@@box : Box(Int32 ->)` and `@@box = boxed_data`
to
`@@box : Array(Box(Int32 ->)) = [] of Box(Int32 ->)` and `@@box << boxed_data`, respectively. I then get the following error:
```
Error in ticker.cr:29: instantiating 'Ticker:Module#on_tick()'

Ticker.on_tick do |tick|
       ^~~~~~~

in ticker.cr:16: no overload matches 'Array(Box(Proc(Int32, Nil)))#<<' with type Pointer(Void)
Overloads are:
 - Array(T)#<<(value : T)

    @@box << boxed_data
```
which sort of makes sense because Box is supposed to give us a `Pointer(Void)`, but why do the types not match?

So it seems that either the syntax or the the types used in the module-level variable are causing problems. Are the docs out of date or have I done something wrong myself? I can't really find any alternative examples of this process.

**Comment by straight-shoota** [comment]
It seems like the documentation is just wrong here.

This should be a somewhat working example, only on carc.in it doesn't link: https://carc.in/#/r/3c7j

**Comment by tomjw64** [comment]
Even the linking is not the problem, however.
`@[Link(ldflags: "#{__DIR__}/ticker.o")]` will be sufficient if you have some compiled C, ticker.o, with the correct function declaration.
The original issue assumes a correct link statement. I've updated some wording to indicate this.

**Comment by tomjw64** [comment]
Ah! The example differs on the [official language reference](https://crystal-lang.org/docs/syntax_and_semantics/c_bindings/callbacks.html#passing-a-closure-to-a-c-function) and the "Passing a Proc to a C Function" section in the [API Docs](https://crystal-lang.org/api/0.21.0/Proc.html). The API Docs for Proc contain a correct example using `@@box : Pointer(Void)?` thus the language reference should be updated.

**Comment by asterite** [comment]
Closed in favor of https://github.com/crystal-lang/crystal-book/issues/186
