### ISSUE TITLE
Add JSON support to UUID

### ISSUE THREAD

**Issue by lachlan** [crystal-lang/crystal#5548]
To support `UUID`s being used directly in JSON mappings, I'd like to add the following methods to the standard library:

* `UUID.new(JSON::PullParser)`
* `UUID#to_json(JSON::Builder)`

I was thinking we'd add these to a new source file `uuid/json.cr`, and so you'd have to `require "uuid/json"` to opt in to the JSON support, similar to `big/json.cr`.

If this approach and feature is acceptable, I'd like to create a pull request for it.

**Comment by Sija** [comment]
Since #5551 has been merged, this can be closed now.
