### ISSUE TITLE
UUID is missing `inspect`

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#5552]
```crystal
require "uuid"

p UUID.random
```

Output:

```
UUID(
 @bytes=
  StaticArray[125_u8,
   0_u8,
   40_u8,
   32_u8,
   185_u8,
   211_u8,
   76_u8,
   209_u8,
   161_u8,
   25_u8,
   95_u8,
   109_u8,
   156_u8,
   180_u8,
   191_u8,
   12_u8])
```

**Comment by asterite** [comment]
As a side note:

```
require "uuid"

puts UUID.random
```

Output:

```
6acf74c9-e325-4e75-8efb-33be77b404e3
```

Maybe it's a bit strange that it doesn't come inside double quotes, I don't know.

**Comment by bew** [comment]
@asterite why would it be inside double quotes?

**Comment by asterite** [comment]
Because that's the string representation of the uuid. The uuid is just a chunk of bytes. But I don't mind that format (that much), in Cassandra they also don't have double quotes.

**Comment by RX14** [comment]
@asterite but `UUID` isn't a string so having it in quotes would be actively confusing. Would make you think it's just a UUID inside a `String` which is perfectly possible.
