### ISSUE TITLE
Update man page with new options

### ISSUE THREAD

**Issue by GloverDonovan** [crystal-lang/crystal#5554]
I don't believe this is a high priority issue, but it should be resolved before reaching 1.0.

Some build options such as `--no-debug` and `--time` are not mentioned in the man page.

I haven't looked for all the missing options, but I'm sure that a trivial script could check to make sure that each possible shell completion also exists in the man page. This would be a great way to ensure that the man page isn't missing any options for 1.0.

**Comment by r00ster91** [comment]
This can be closed since #6259 is merged.
