### ISSUE TITLE
Infered type of instance variables

### ISSUE THREAD

**Issue by ThomasSevestre** [crystal-lang/crystal#5586]
With this code

    class A
      @a : String?

      def a
        @a ||= "a"
        puts @a.upcase
      end
    end

    A.new.a

The compiler do not infer `@a` type automatically and I have this error :

    undefined method 'upcase' for Nil (compile-time type is (String | Nil))

If I try to mimic this code with a local variable, `a` type is automatically infered to a String :

    a : String?
    a = nil
    a ||= "a"
    puts a.upcase

**Comment by asterite** [comment]
Hi!

Please read https://crystal-lang.org/docs/syntax_and_semantics/if_var.html

In this case it can happen that between these two lines:

```
@a ||= "a"
# here
puts @a.upcase
```

another thread comes and changes `@a` to be nil, so in general you can't rely on `@a` being not `nil` in the `puts` line.

Read https://crystal-lang.org/api/0.24.1/Nil.html for the many ways to deal with `nil`.

(threads aren't currently supported, but in the future they will, and this already takes care of that possible race condition)

**Comment by asterite** [comment]
By the way, someone should write an entry https://github.com/crystal-lang/crystal/wiki/FAQ here about this. This is one of the most common questions asked here. Simply sharing that FAQ link will save us a lot of time.

**Comment by ThomasSevestre** [comment]
Sorry for the duplicate question and thanks for your quick answer
