### ISSUE TITLE
additional parameters for Logger#new

### ISSUE THREAD

**Issue by pynixwang** [crystal-lang/crystal#5588]
https://blog.bigbinary.com/2017/04/10/ruby-2-4-has-added-additional-parameters-for-logger-new.html

```
require "logger"

log = Logger.new(STDOUT, level = Logger::WARN, formatter = Logger::DEFAULT_FORMATTER, progname = "")
```

**Comment by RX14** [comment]
I actually have wanted to redesign `Logger` for a while to cover usecases of library logging. For example, a library should just be able to create a logger and log whatever it wants in whatever detail it wants, then there's a centralized place for the application to configure logging level and formatter per-library. Somewhat like the java logging frameworks but not so... bloated.

**Comment by ysbaddaden** [comment]
Sounds bloated, yeah (and an idea for an experimentation shard), and has nothing to do with configuring the logger with kwargs, in addition to getters/setters.
