### ISSUE TITLE
`if` + var does not properly restrict type when used in closure

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#5596]
```crystal
def foo(&block : -> )
  block.call
end

base = nil
foo do
  if base
    base.upcase # Error: undefined method 'upcase' for Nil
  end
end
```

The same code works if `base` is assigned to a fresh variable inside the block or the block is inlined (`yield` instead of `block.call`).

**Comment by asterite** [comment]
Duplicate https://github.com/crystal-lang/crystal/issues/3093
