### ISSUE TITLE
Incorrect behaviour when capturing var and changing it in a loop

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#5609]
Crystal 0.24.1

```crystal
def capture(&block)
  block
end

x = 1
3.times do
  p x
  capture do
    x = "hello"
  end.call
end
```

Output:

```
1
194613232
194613232
```

The problem is that we only bind the variable to the metavariable if it's a closured var on a first pass, but the first read of `x` happens before we determine it's a closure.

I found this while thinking about how to fix https://github.com/crystal-lang/crystal/issues/4359

**Comment by SlayerShadow** [comment]
This works correctly with
```crystal
def capture
  yield
end
```
And doesn't work with `block.call`...
Crystal version: `0.28.0-dev [d1cdab2]`

**Comment by straight-shoota** [comment]
@SlayerShadow Yes, that's to be expected because `yield` essentially inclines the block directly. With capturing + `block.call` it's indirected through a Proc and that seems to have a bug somewhere, probably in code generation.

**Comment by asterite** [comment]
The problem is actually in the semantic phase.

**Comment by miketheman** [comment]
#CodeTriage 
The behavior today emits the following output:
```
1
-1334769312
-1334769312
```
So it's still incorrect. The referenced linked PR #8588 appears to try and get this working, however that has yet to be merged, and there's further discussion that can be followed over there.
