### ISSUE TITLE
Crystal Play crash when the string "\x90" is used

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#5613]
This example crashes Crystal Play 0.24.1

```crystal
require "random"
b = "/\x90#{String.new(Random::Secure.random_bytes(1024))}"
puts b
```

Error: file 'play' is not a valid Crystal source file: Unexpected byte 0x90 at position 36, malformed UTF-8

**Comment by bararchy** [comment]
@asterite what say you regarding this? :)

**Comment by asterite** [comment]
@bararchy It seems to be working in master. Can you try it?

**Comment by asterite** [comment]
Though then it says "Connection lost, refresh". I personally don't care about `crystal play`, I never use it, so...

**Comment by asterite** [comment]
The reason is that it's a nice toy, but it's not Crystal (it's **almost** Crystal, but the instrumentation added to it makes it another language).

**Comment by jhass** [comment]
Doesn't seem to reproduce anymore. Can anybody still?

**Comment by asterite** [comment]
Seems to be fixed. Thanks @jhass !
