### ISSUE TITLE
typeof returns incorrect type of variables inside closure

### ISSUE THREAD

**Issue by z64** [crystal-lang/crystal#5614]
Came across this while debugging something:
```cr
foo = true ? "foo" : nil

raise "foo is nil" unless foo

pp typeof(foo) # => String
pp foo.upcase # => "FOO"

def capture(&block)
  block
end

capture do
  pp typeof(foo) #=> String
  # Won't compile:
  # undefined method 'upcase' for Nil (compile-time type is (String | Nil))
  # pp foo.upcase
end
```
https://carc.in/#/r/3f09

@RX14 explained that:
> `typeof(foo)` doesn't count as "using" foo, so it doesn't get closured and the type doesn't change

It seems solving #3093 would inherently fix this, but this appears to be an issue with `typeof` itself.

**Comment by straight-shoota** [comment]
Resolved by #9986
