### ISSUE TITLE
HTTP::Client raise OOB error for certain responses

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#5621]
The below call will produce index out of bounds error for the `HTTP::Client` call

```crystal
require "http"

client = HTTP::Client.get("https://neuralegionsite.wixsite.com/siteBackHtml/\n\n5")
```

**Comment by straight-shoota** [comment]
Interestingly the error happens when parsing the response:
```
Index out of bounds (IndexError)
  from /usr/share/crystal/src/indexable.cr:0:17 in 'at'
  from /usr/share/crystal/src/indexable.cr:73:5 in '[]'
  from /usr/share/crystal/src/http/client/response.cr:124:19 in 'from_io?'
  from /usr/share/crystal/src/http/client.cr:502:5 in 'exec_internal_single'
  from /usr/share/crystal/src/http/client.cr:486:5 in 'exec_internal'
  from /usr/share/crystal/src/http/client.cr:482:5 in 'exec'
  from /usr/share/crystal/src/http/client.cr:585:5 in 'exec'
  from /usr/share/crystal/src/http/client.cr:612:7 in 'exec'
  from /usr/share/crystal/src/http/client.cr:329:3 in 'get'
```
The first line of the response is actually `<html>`, not the expected HTTP header.

**Comment by asterite** [comment]
`URI.parse` seems to be the culprit:

```crystal
require "uri"

uri = URI.parse("http://foo.com\nhello-world")
p uri
```

That shouldn't work. In Ruby that raises.

**Comment by straight-shoota** [comment]
Yes, but still there is also an error in `Response.from_io`.

It seems the server neuralegionsite.wixsite.com returns the response body without any HTTP headers when it receives an invalid request consisting of `GET /siteBackHtml/` (body is ignored).
`Response.from_io` should handle such an invalid response gracefully instead of crashing.

**Comment by straight-shoota** [comment]
@asterite It seems the URI parser could need a refactoring anyway.

Is there a reason it traverses through the string using a pointer instead of `Char::Reader`?

**Comment by asterite** [comment]
I don't know, I didn't write that code.

**Comment by straight-shoota** [comment]
Yeah, I wasn't asking anyone in particular.

But it seems you actually answered this in [#2016 (issue comment)](https://github.com/crystal-lang/crystal/pull/2016#issuecomment-172645768):
> `Char::Reader` decodes UTF-8, and unless I'm mistaken there's no need to do that.

This seems legit. URI special characters are all ASCII and UTF-8 characters will just be copied as bytes. Though I still wonder if it wouldn't be better to use a Char::Reader... the logic compares bytes with chars all the time anyway.

The entire parser needs more specs and I guess there are quite a few edge cases not properly covered by the current implementation.

**Comment by bararchy** [comment]
@straight-shoota I'm working on fuzzing most of the standard network based parts of the stdlib, so I'll try and report any finding I can catch for "weird edge cases"

**Comment by bararchy** [comment]
Waiting to merge of #5630 and will close this.
