### ISSUE TITLE
Crystal compile-time error in an `if` when `|| false` is part of the condition.

### ISSUE THREAD

**Issue by drosehn** [crystal-lang/crystal#5631]
```cr
# crystal --version
Crystal 0.24.1 (2017-12-27)

LLVM: 5.0.1
Default target: x86_64-apple-macosx
# uname -a
Darwin garance.mac.host 14.5.0 Darwin Kernel Version 14.5.0: Sun Jun  4 21:40:08 PDT 2017; root:xnu-2782.70.3~1/RELEASE_X86_64 x86_64
```
This is an issue of crystal acting less-than-ideal to an `if` statement, although I'll admit the `if` statement itself is pretty stupid.  Consider:
```cr
class StringThing
    getter strval

    def initialize(@strval : String)
    end
end

the_thing = nil

ARGV.each { |thisarg|
    if thisarg =~ /^--thing=/
	the_thing = StringThing.new($~.post_match)
    end
}

if the_thing     # --this "if"--
      printf " - I see you wanted a --thing of '%s'.\n", the_thing.strval
else
      printf " - No --thing for you!\n"
end
```
Here are two sample runs:
```cr
# /tmp/weird-err --ignore
 - No --thing for you!
# /tmp/weird-err --thing=blah-blah
 - I see you wanted a --thing of 'blah-blah'.
```
In my case I'm working with a much larger program, with a much larger `if` statement.  While testing something else, I wanted the quickest way to neutralize the entire `if` statement.  What I **meant** to do was to change the `if` to `if the_thing && false`.  The `if` could never be true, so crystal would always execute the `else` part and I'd be happy.  In fact, I was hoping it skips over the `if`-part during compile time, and generates object-code for only the `else`-part.  But instead of making that change, I had the brain-error of changing the line to:
```cr
if the_thing || false
    printf " - I see you wanted a --thing of '%s'.\n", the_thing.strval
else
    printf " - No --thing for you!\n"
end
```
And with that dumb mistake on my part, I got the **compile-time** error of:
```cr
# crystal build weird-err.cr -o /tmp/weird-err
Error in weird-err.cr:18: undefined method 'strval' for Nil (compile-time type is (StringThing | Nil))

    printf " - I see you wanted a --thing of '%s'.\n", the_thing.strval
                                                                 ^~~~~~

Rerun with --error-trace to show a complete error trace.
```
In my case that error was in the middle of 50-lines of statements inside the `if` clause, and at first I didn't notice that the error with `the_thing.strval` was referencing the same object as `the_thing` on the condition for the `if`.  And of course, I'm also thinking that I wrote `&&` instead of `||`.

Now that I reduced my code to this minimal example, I see what is probably happening.  When crystal is looking at references to `the_thing` inside the if-clause, it's probably treating:
`  if the_thing || false `
as if it was
` if the_thing || some_variable`

where the `some_variable` **might** be a `true` value, even though in fact it's a compile-time constant which is always `false`.  And if `some_variable` were true, **then** it would be possible to execute
` printf " - I see you wanted a --thing of '%s'.\n", the_thing.strval`

while `the_thing` could be a nil object, and that is worthy of a compile-time error.

I realize this is situation was brought on by my own dumb mistake, but I wanted to write it up just in case it might be significant in some other context.  I have no objection if people read this, say _"My that's dumb!"_, and close the issue.  It's just that I hate it when I'm trying to pin down one issue, and then I get sidetracked by a completely unrelated issue such as this one.

**Comment by RX14** [comment]
I think the more interesting question to ask there is how could we have improved the error message? Does `--error-trace` help you here at all?

**Comment by drosehn** [comment]
Hmm.  Well I've seen this kind of error in enough situations that I knew what it was complaining about.  I just couldn't see how I could get there after adding `false` to the `if` condition when I wasn't getting there before adding it.  I'm familiar enough with the error message that I didn't even try running `--error-trace`, but in trying it right now I'd say that doesn't really help:

```cr
Error in weird-err.cr:18: undefined method 'strval' for Nil (compile-time type is (StringThing | Nil))

    printf " - I see you wanted a --thing of '%s'.\n", the_thing.strval
                                                                 ^~~~~~

================================================================================

Nil trace:

  weird-err.cr:9

    the_thing = nil
    ^~~~~~~~~

  weird-err.cr:9

    the_thing = nil
                ^
```
Even in the context of the original larger program, that trace wouldn't really help me.  It's the kind of trace which **does** help in other situations where I trigger `undefined method '...' for Nil`, but not in this one.  In this specific case it might have helped to point out the line `if the_thing || false`, but I don't see that working in other situations.

**Comment by asterite** [comment]
The main issue is that Crystal applies type flow implicitly. And as with all implicit things, it's hard to understand and track down.

I don't think there's much we can do here. Maybe rewrite `if x || false` to `if x`, and `if x && false` to `false`, which means more hidden rules...

**Comment by drosehn** [comment]
My gut feeling is that the error message and the error trace are fine as they are, and that this was just a very weird case.

After a good night's sleep and thinking about this more, I was actually fortunate that this error popped up, because it forced me to look at that `if`.  Let's say that there had been no reference to `the_thing` inside the `if`-clause.  I would have thought I **had** done the `&& false`, and that the `if`-clause would never be executed.  Any conclusions I drew from that change would have been incorrect.

Would it make any sense to have a warning something like:
```cr
   Note:  Adding '|| false` to a condition will never change the result of that condition.
```
Part of me hates that idea, but I can't think of any other way the compiler could have helped me out with this particular mistake.  The real error is on that `if`, and not on what the compiler decided to do with the `if`-clause.

**Comment by drosehn** [comment]
Note: just a warning message.  Not an error which stops the compile.

**Comment by caspiano** [comment]
I think this comes down to a lint... luckily we have the brilliant [ameba linter](https://github.com/crystal-ameba/ameba) which has a rule to detect literals in a conditional!
