### ISSUE TITLE
rand(num) won't work with big_ints

### ISSUE THREAD

**Issue by jzakiya** [crystal-lang/crystal#5647]
crystal 0.24.1

translating code from Ruby and hit this bug when doing

```
rand(self-4)  
```

when self is big_int

**Comment by oprypin** [comment]
Hi,
I'll try to explain the lack of response:
This is a valid feature request but probably very low priority.

In most cases you can work around this by getting a random Int64 or Float64 first

**Comment by jzakiya** [comment]
The hack below at least got the code to compile, but it's sooooo ugly, and probably doesn't have the statistical properties of a real random distribution.

```
b = 2 + ((self-4).to_f * Random.rand).to_big_i
```

**Comment by iSarCasm** [comment]
Hello. What is the best way to implement random for BigInts @ysbaddaden ? There is some random inside GMP or should I just dance with `Random::Secure.next_u`?
https://github.com/crystal-lang/crystal/blob/master/src/random.cr
https://github.com/crystal-lang/crystal/blob/master/src/random/secure.cr
Thanks

**Comment by oprypin** [comment]
If covering all possible values is not critical, you can work around this with [`rand(range : Range(Float, Float)) : Float`](https://github.com/crystal-lang/crystal/blob/1cbafcbb50d475a49137068c4a0dd47116ed62b1/src/random.cr#L281) and rounding.

**Comment by oprypin** [comment]
And the proper solution would be extending [the algorithm](https://github.com/crystal-lang/crystal/blob/1cbafcbb50d475a49137068c4a0dd47116ed62b1/src/random.cr#L118) to support BigInt (shouldn't be too hard)

**Comment by iSarCasm** [comment]
@oprypin Yes, I need the whole range for the cryptographic algorithm. Thanks, I will try to extend this alg.
