### ISSUE TITLE
Kernel_security_check_failed update 2

### ISSUE THREAD

**Issue by Wulfklaue** [crystal-lang/crystal#5649]
A while ago i posted about the "Kernel_security_check_failed" blue-screen of dead crashing under WSL ( Windows 10 - Ryzen ). #5569

Today after getting another system but now with a Intel CPU, tracing the issue kept going. As somewhat expected this same problem still happened. But after some more investigation, it seems to backtrace to the Slang shard.

Whenever this shard ( https://github.com/jeromegn/slang ) was not activated in the code, the crash did not happen.

```
require "kilt/slang"

#res = String.build do |__slang__|
#  Slang.embed("/mnt/c/Programming/Crystal/temp/src/resources/template.slang", "__slang__")
#end

#puts res
```

Disable this code and no more BSOD. Compile other code ( "baked_file_system" ) in the same file a dozen times, perfect compilation. Run this code and ... say hello Mr BSOD.

The complete code:

```
require "./temp/*"

require "kilt/slang"

require "baked_file_system"

class FileStorage
  BakedFileSystem.load("/mnt/c/Programming/Crystal/temp/src/resources")
end

path = "template.slang"
file_string = ""
file = nil
begin
  file = FileStorage.get(path)
rescue BakedFileSystem::NoSuchFileError
  puts "File #{path} is missing"
end

some_var2 = ARGV[0]

if some_var2 = "1"
    some_var2 = "000001"
end

strings = ["ah", "oh"]

file = FileStorage.get(path)
file_string = file.read

#res = String.build do |__slang__|
  #Slang.embed("/mnt/c/Programming/Crystal/temp/src/resources/template.slang", "__slang__")
#end

#puts res
```

Shard.yml
```
name: temp
version: 0.1.0

authors:
  -  <>

crystal: 0.24.1

license: MIT

dependencies:
  slang:
    github: jeromegn/slang
  kilt:
    github: jeromegn/kilt
  baked_file_system:
    github: schovi/baked_file_system    
```

The template.slang
```
doctype html
html
  head
    meta name="viewport" content="width=device-width,initial-scale=1.0"
    title This is a title
    css:
      h1 {color: red;} 
      p {color: green;}
    style h2 {color: blue;}
  body
    / Multi-line comment
      span this is wrapped in a comment
    /[if IE]
      p Dat browser is old.
    h1 This is a slang file
    h2 This is blue
    span#some-id.classname.more
      #hello.world.world2
        - some_var = "hello world haha"
        span
          span data-some-var=some_var2 two-attr="fun" and a #{p("hello")}
          span data-some-var=some_var two-attr="fun" and a #{p("hello")}
          span
            span.deep_nested
              p
                | text inside of <p>
              = Process.pid
              | text node
              ' other text node
        span.alongside pid=Process.pid
          custom-tag#with-id pid="#{Process.pid}"
            - ["ah", "oh"].each do |s|
              span = s
    / This is an invisible comment
    #amazing-div some-attr="hello"
    /! This is a visible comment
    script var num1 = 8*4;

    javascript:
      var num2 = 8*3;
      alert("8 * 3 + 8 * 4 = " + (num1 + num2));
```

I am suspecting that the whole issue is related how the code runs. Backtracing the authors code, there is some interesting trickery going on to make the system work.

Still not 100% sure its a pure Windows issue or the Crystal compiler is trying to access something WSL does not like.

Maybe somebody else with a:

Windows 10 ( 64 bit ). Intel or Ryzen CPU both act the same. Fresh installations with recent patches.
Ubuntu WSL + Visual Studio Code
The above mentioned Slang shard and code
If somebody can try out the code and see if there system also BSODs on it. Please close all other applications before trying, you will thank me...

---

Now do not ask me how this code was still able to activate sometimes ( #5569  )when putting the whole ''' inside. Its a very strange bug / issue. Its almost like the compiler still read the whole code including that ''', i assume that this was  the cause but after some attempts it did not crash. Never put 1 + 1 together that it might actually read code past the deliberate ``` code. The author relies on a few macro tricks for Slang. Not a compiler guy so its pure speculation but it feels it might be something to do in that direction. I hate debugging issues like this but we are one step closer then pure in the dark 👍

**Comment by DemiMarie** [comment]
This is a Windows kernel bug, not a Crystal bug.  That is true of **any** BSOD/kernel panic/etc: it simply should not be possible for a program without administrative privileges to crash the OS, and if it *is* possible, that is a security vulnerability.

**Comment by RX14** [comment]
Duplicate of 5569
