### ISSUE TITLE
What did I do wrong to deserve this?

### ISSUE THREAD

**Issue by PretendPark** [crystal-lang/crystal#5652]
Why treat me like I did something wrong / victimize me over asking questions?

All  I wanted to know  was how to de-allocate memory. Not fair that now I am **being used as an example** to "show good information" in the community.

My problem is not fake, it's a real question and I am NOT ignoring or trying to repeat myself. I am TRYING to learn. To learn, you need to ask questions. It's human nature, and I'm sorry if I'm not smart enough to learn as fast as others.

Hosting a VPS with nginx, mysql, and other services that cannot access ram that Crystal allocates is just something NEW to me. It's not me putting down the language at all, it's not me trying to debate / argue at all. It's me just TRYING TO TALK and express human emotion so I can understand what is going on more clearly. There is absolutely NOTHING wrong with that.    I think it's a fair question to ask about how to de-allocate memory, how is that abnormal?

Other apps I use, Godot Engine, Atomic Engine, Game Maker, etc. If you allocate a lot of values in an array, and look at task manager = **you see that memory usage increase**. If you `erase` that array, the memory usages goes down.  (Memory get's freed, restored to OS, (from what I learned earlier) -- That is _what is NORMAL to me_, ok? **That's me. That's my life, and my upbringing**.  To see memory usage NOT disappear and become "free", but stay the same is **something different**. To me, it seems like a red flag. So I am asking questions about WHY it's happening.  Since I don't know. You expect me to know everything?

**This doesn't inherently mean I am trying say something is bad with the engine**. This doesn't mean I am not listening or trying to start trouble. That just means it's something NEW TO ME. I am learning. Please respect this, not everyone is as smart as you guys. And to me, what I experienced is reminiscent of high school bullying all over again. It's not nice...

 I resort to programming as a scapegoat mechanism to help. Especially from Ruby's quote ("programmer's best friend"). All I am trying to do is converse and engage in discussion. I don't have many friends in real life, and too nervous to engage in social discussion. So communicating online is all I have, please just stop.

**Comment by RX14** [comment]
I'm incredibly sorry that someone was rude to you on reddit, but I don't think that this issue tracker is the correct place to discuss this. Please believe that a single person does not represent the whole crystal community.
