### ISSUE TITLE
problems with 'nil?' in the playground

### ISSUE THREAD

**Issue by FunkyQChicken** [crystal-lang/crystal#5665]
this code

```ruby
a = 5
b = nil
  
if !b.nil?
  a + b
end
```
raises the 'You've reached a bug in the playground' window,  
compiling and running the code outside the playground works perfectly though.  
other boolean expressions in place of !b.nil? work fine as well,  
here is the exception section of the bug window: 
```
Exception
Error in line 8: instantiating 'Crystal::Playground::Agent#i(Int32)'

in line 8: instantiating 'Crystal::Playground::Agent#i(Int32)'

in line 9: no overload matches 'Int32#+' with type Nil
Overloads are:
 - Int32#+(other : Int8)
 - Int32#+(other : Int16)
 - Int32#+(other : Int32)
 - Int32#+(other : Int64)
 - Int32#+(other : Int128)
 - Int32#+(other : UInt8)
 - Int32#+(other : UInt16)
 - Int32#+(other : UInt32)
 - Int32#+(other : UInt64)
 - Int32#+(other : UInt128)
 - Int32#+(other : Float32)
 - Int32#+(other : Float64)
 - Number#+()

Rerun with --error-trace to show a complete error trace.
```  
  
running the playground with -v shows that the code is translated to: 
```ruby
a = _p.i(1) do
  5
end
b = _p.i(2) do
  nil
end
if !(b.nil?)
  _p.i(5) do
    a + b
  end
end
```
but as i said, other boolean expressions work fine,  
so if i run
```ruby
a = 5
b = nil

if false == b.nil?
  a + b
end
```
it is translated to
```ruby
a = _p.i(1) do
  5
end
b = _p.i(2) do
  nil
end
if false == (b.nil?)
  _p.i(5) do
    a + b
  end
end
```
and instead of a popup saying i've encountered a bug i get the usual  
red box beneath my 'a + b' line saying 'no method for 'Int32 + nil'  
  
Probably just a try catch not catching the right exception in the Playground class?

**Comment by chorankates** [comment]
this looks to have been fixed in 0.15: https://play.crystal-lang.org/#/r/49ps

**Comment by RX14** [comment]
@chorankates this isn't about `play.crystal-lang.org`, this is about `crystal play` which is different.

Besides, `0.15` is many years old at this point. I'm not sure why you bring it up.

**Comment by rdp** [comment]
Seems working here... 0.31.1 OS X FWIW :)
