### ISSUE TITLE
C function pointers in struct

### ISSUE THREAD

**Issue by S-YOU** [crystal-lang/crystal#5673]
I have some struct like this from Intel DPDK Library.

```
struct RteEthDev
    rx_pkt_burst : EthRxBurstT
    tx_pkt_burst : EthTxBurstT
    tx_pkt_prepare : EthTxPrepT
    data : RteEthDevData*
    ...
end
```

`EthRxBurstT, EthTxBurstT and EthTxPrepT` are C function pointer defined like this

```
alias EthRxBurstT = (Void*, RteMbuf**, Uint16T -> Uint16T)
```

In C, those are 8 bytes, but in crystal those are 16 bytes.
And `.data` is point to the invalid address, I am getting segfaults.

And I cannot change `EthRxBurstT as Void*` , because I need to call those functions later on.

Is there any way to work around this?

**Comment by asterite** [comment]
Just `data : RteEthDevData` should work.

**Comment by S-YOU** [comment]
Hmm, I am not sure how that can work. Still failing. 
What is the concept behind removing pointer, which actually is a C struct pointer?
Also that content of that memory area will be filled by C function.

Original struct is something like this
```
struct rte_eth_dev {
	eth_rx_burst_t rx_pkt_burst; /**< Pointer to PMD receive function. */
	eth_tx_burst_t tx_pkt_burst; /**< Pointer to PMD transmit function. */
	eth_tx_prep_t tx_pkt_prepare; /**< Pointer to PMD transmit prepare function. */
	struct rte_eth_dev_data *data;  /**< Pointer to device data */
	const struct eth_dev_ops *dev_ops; /**< Functions exported by PMD */
	struct rte_device *device; /**< Backing device */
	struct rte_intr_handle *intr_handle; /**< Device interrupt handle */
        ....
```

Ported crystal struct is something like this
```
struct RteEthDev
    rx_pkt_burst : EthRxBurstT
    tx_pkt_burst : EthTxBurstT
    tx_pkt_prepare : EthTxPrepT
    data : RteEthDevData*
    dev_ops : EthDevOps*
    device : RteDevice*
    intr_handle : RteIntrHandle*
    ...
```

And I need to called rx_pkt_burst C function with data as arguments like this
```
nb_rx = dev.value.rx_pkt_burst.call(dev.value.data.value.rx_queues[queue_id], rx_pkts, nb_pkts)
```

**Comment by asterite** [comment]
Oh, sorry, I read too quickly the first time.

I just tried this:

```crystal
lib LibFoo
  alias Foo = Void* -> Int32

  struct Bar
    x : Foo
  end
end

puts sizeof(LibFoo::Bar)
```

I get 8. I don't understand why you say a function pointer in Crystal is 16 bytes. It's 8.

Or am I doing something wrong?

**Comment by S-YOU** [comment]
If there is multiple argument in alias it become 16 bytes?

```
lib LibFoo
  alias Foo = Void* -> Int32
  alias EthRxBurstT = Void*, Void*, Void* -> Int32

  struct Bar
    x : Foo
  end
end

puts sizeof(LibFoo::Bar)
puts sizeof(LibFoo::EthRxBurstT)

```

8
16

**Comment by asterite** [comment]
The size of a "function pointer" in Crystal is 16 bytes, because it could be a closure. So 8 bytes for the function pointer, and 8 bytes for a pointer to the closure data.

When you embed a function pointer inside a lib struct that's going to be interfacing C, that takes up 8 bytes because it's just a regular function pointer: no closure data is allowed. And if you try to set a "function pointer" to a Proc, the compiler will check, if possible at compile-time, that the Proc has no closure data associated with it.

That's why you get 16 when the "function pointer" is taken out of context. But inside the context of a C struct it will always be 8 bytes.

**Comment by S-YOU** [comment]
I see. I didn't realize embedding 16 bytes Proc inside become 8 byte in struct. So, looks like the real issue I am getting is somewhere else.

Thanks for the help and information. Closing.
