### ISSUE TITLE
Exception#backtrace? raises an IndexError on macOS

### ISSUE THREAD

**Issue by marksiemers** [crystal-lang/crystal#5678]
I have not yet been able to successfully reduce the code. The relevant code is:
```crystal
      begin
        message = @ex.inspect_with_backtrace
      rescue ex : IndexError
        # ERROR: Any of these will cause another IndexError (at least on macOS)
        # ex.inspect_with_backtrace # or @ex.inspect_with_backtrace
        # ex.backtrace? # or @ex.backtrace?
        message = @ex.message
      end
```

To reproduce, using macOS, you can follow these steps:
1. `git clone git@github.com:amberframework/amber.git`
1. `git fetch && git checkout ms/fix-internal_server_error-error`
1. Uncomment the line at `src/amber/controller/error.cr:35` (or line 36): https://github.com/amberframework/amber/pull/625/files#diff-fefe72c37ea251ccaec8417bffb49e8cR35
1. Run `crystal spec spec/amber/router/pipe/error_spec.cr:15`

With the line commented out, the tests pass:
```
$ crystal spec spec/amber/router/pipe/error_spec.cr:15
.....

Finished in 128.61 milliseconds
5 examples, 0 failures, 0 errors, 0 pending
```

With the line uncommented, we get the `Index out of bounds` error.
```
$ crystal spec spec/amber/router/pipe/error_spec.cr:15
....E

Failures:

  1) Amber::Pipe::Error returns status code 500 for all other exceptions

       Index out of bounds
```

```
$ crystal -v
Crystal 0.24.1 (2018-01-27)
LLVM: 5.0.1
Default target: x86_64-apple-macosx

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D47
```

From what I've looked at in the crystal code base, it may have to do with `CallStack`. There is a difference in `darwin` vs `linux` in that file:
https://github.com/crystal-lang/crystal/blob/351596855d635141deb204f7c572ed615f415ce5/src/callstack.cr#L8

What led me there is:
https://github.com/crystal-lang/crystal/blob/v0.24.1/src/exception.cr#L35

And then here:
https://github.com/crystal-lang/crystal/blob/351596855d635141deb204f7c572ed615f415ce5/src/callstack.cr#L157

**Comment by ysbaddaden** [comment]
Does it still happen with crystal master? I fixed a *very* similar issue recently.

**Comment by marksiemers** [comment]
I'm checking now. Is this the relevant commit: https://github.com/crystal-lang/crystal/commit/048f77e7a389cb85875b88fd0839183229866f66

**Comment by asterite** [comment]
Probably duplicate of #5224

**Comment by marksiemers** [comment]
I'm running into an unrelated issue when trying to test against master, may just need to update some dependencies (`pg`).

It is a `JSON::Type` error - that was updated to `JSON::Any`, correct?

**Comment by marksiemers** [comment]
This is fixed in master.

Sorry it took me a while to get setup - there are a handful of breaking changes that affect crystal-pg and amber that I had to work through.
