### ISSUE TITLE
Class reopening across multiple files yields different runtime result

### ISSUE THREAD

**Issue by Svenskunganka** [crystal-lang/crystal#5681]
I have a weird issue with class reopening across multiple files that when required, yields a different runtime result. I might have abused the type system a bit... but here goes.

I can't reproduce this in a small implementation, so to reproduce you'll have to clone the code I'm actually working on. It's not super large and mostly repetetive.  
To clone the gist:  
```
git clone https://gist.github.com/4e18d9d8183d2b68ba3b140ceaa5e93f.git class-reopening-bug && cd $_
```
Direct link: https://gist.github.com/Svenskunganka/4e18d9d8183d2b68ba3b140ceaa5e93f

The files of most importance is `1.cr` and `2.cr`, and here's the diff between them:
```diff
diff --git a/1.cr b/2.cr
index 55da586..6b94d9c 100644
--- a/1.cr
+++ b/2.cr
@@ -1,4 +1,5 @@
 require "./audio"
+require "./archive"

 class Filetype
   def self.match(slice : Bytes) : (self.class | Nil)
```

I only require another file in `2.cr`, but the runtime result is different:

`crystal run 1.cr` yields `is an audio` while `crystal run 2.cr` yields `other`. Two different code paths is depending on if I require a secondary file or not:

`1.cr` runs this code path:
```crystal
case filetype
when Filetype::Audio.class
  puts "is an audio" # <-- this code path is run
else
  puts "other"
end
```
while `2.cr` runs this code path:

```crystal
case filetype
when Filetype::Audio.class
  puts "is an audio"
else
  puts "other" # <-- this code path is run
end
```

**Comment by caspiano** [comment]
This is no longer reproducible in Crystal 1.6.1

```shell-session
$ crystal run 1.cr
Filetype::Audio::Midi returned Filetype::Audio::Midi
Filetype::Audio returned Filetype::Audio::Midi
is an audio
$ crystal run 2.cr
Filetype::Audio::Midi returned Filetype::Audio::Midi
Filetype::Audio returned Filetype::Audio::Midi
is an audio
```

[Run for `1.cr`](https://carc.in/#/r/dzzh)
[Run for `2.cr`](https://carc.in/#/r/dzzi)
