### ISSUE TITLE
Support parsing Content-Disposition: file headers

### ISSUE THREAD

**Issue by stakach** [crystal-lang/crystal#5686]
In a multi-file upload the files can be uploaded in a subpart with `Content-Disposition: file; filename="file1.txt"`

Currently one must detect `multipart/mixed` form data and parse the sub-multipart data outside of the standard library.

For example post data see https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.2
References: https://tools.ietf.org/html/rfc2388
```
   either of the "content-disposition: form-data"
   header or, in the case of multiple files, in a "content-disposition:
   file" header of the subpart.
```

**Comment by bew** [comment]
Note: Relevant previous discussion about this in #5683.

**Comment by straight-shoota** [comment]
I have a more or less ready implementation for this. It's just waiting for #5765
