### ISSUE TITLE
Suggestion: Compiler Warnings

### ISSUE THREAD

**Issue by Vikaton** [crystal-lang/crystal#569]
Compiler Warnings could be useful for possible holes in the code that may not produce compile time errors, but possible run-time errors and/or tips/help on the area of the code that is detected, I can't really think of an example right now granted my knowledge of Crystal as a whole is not so great, any thoughts?

**Comment by jhass** [comment]
See https://github.com/manastech/crystal/issues/432#issuecomment-75266658

**Comment by asterite** [comment]
As @jhass mentions, my personal opinion is that warnings are often ignored and/or annoying.

However, I'm thinking that one warning might make sense, and that's when you assign a value to a variable that's never read. That often means a mistake, maybe you have a typo and assigned to a new variable instead of updating a new one:

```crystal
somelongname = 1
somelognname = 2   # warning: variable assigned but never read
puts somelongname #=> 1
```

I think that's not so hard to do. Is it worth it?

**Comment by Ap0ph1s** [comment]
I think so, It would help a lot :P

**Comment by asb** [comment]
Other cases warnings would be useful:
* Warning that a certain feature or syntax is deprecated and due to be removed
* Use of unsafe features, e.g. in most code I'd argue it's pretty useful to get a warning if you do something unsafe like:
      str :: String
      puts str

This could be overridden with an attribute.

**Comment by kirbyfan64** [comment]
@asb Those would probably be very useful, especially the latter.

**Comment by asterite** [comment]
The problem with warnings is that they can quickly become annoying. When that happens, but you are sure that the code works as you expect, you want to turn the warning off. So you start ignoring the warnings or you turn them off, or we'd need to add some kind of pragma.

So for now, I'd like to not have warnings in the compiler.

**Comment by faustinoaq** [comment]
3 years after, Here we have [Ameba](https://github.com/veelenga/ameba/) Thanks to @veelenga!!! :tada:
