### ISSUE TITLE
Invalid memory access - instance variable changes memory address

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#5694]
While refactoring [crinja](https://github.com/straight-shoota/crinja) to replace recursive aliases with a struct I encountered a strange segfault.

The issue is connected to assigning a wrapped iterator to an instance variable in a constructor. Printing it's value right before the constructor and right after the ivar is assigned, shows that the address and value of the wrapped RangeIterator has changed.

This is right before calling `new`:
```
raw        # => #<Crinja::Value::Iterator(Range::ItemIterator(Int32, Int32)):0x24e5b00
                 @iterator=
                  #<Range::ItemIterator(Int32, Int32):0x24ed860
                   @current=0,
                   @range=0..4,
                   @reached_end=false>>
```
This is the value in the constructor:
```
@iterator # => #<Crinja::Value::Iterator(Range::ItemIterator(Int32, Int32)):0x7fff6173a938
                @iterator=
                 #<Range::ItemIterator(Int32, Int32):0x24e5b00
                  @current=0,
                  @range=0..38721632,
                  @reached_end=false>>
```

When iterating over the (outer) iterator, it changes again:
```
@iterator # => #<Range::ItemIterator(Int32, Int32):0x2501000
                @current=1869898098,
                @range=538976288..538976288,
                @reached_end=true>
```

and then the segfault:
```
Invalid memory access (signal 11) at address 0x0
[0x591d46] *CallStack::print_backtrace:Int32 +118
[0x4e6a3b] __crystal_sigfault_handler +75
[0x7f7226ec3390] ???
[0x5af086] *Slice(T)::new:read_only<Pointer(UInt8), Int32, Bool>:Slice(UInt8) +22
[0x595ad5] *String#to_slice:Slice(UInt8) +37
[0x595a78] *String#to_s<String::Builder>:Nil +24
[0x5aa8d1] *String::Builder +17
[0x59cf5b] *String#inspect<String::Builder>:String::Builder +59
[0x59cf0a] *String +74
[0x5a1768] *String#pretty_print<PrettyPrint>:(Int32 | Nil) +24
[0x6df0e5] *PrettyPrint::format<String, IO::FileDescriptor, Int32, String, Int32>:IO::FileDescriptor +117
Program exited because of a segmentation fault (11)
```

Unfortunately, I was not able to reproduce the error in a reduced example (https://carc.in/#/r/3jag).

I have pushed a branch which reproduces this error ([wip/invalid-memory-access-iterator](https://github.com/straight-shoota/crinja/tree/wip/invalid-memory-access-iterator)).

Most important locations:
* [Crinja::Tag::For::ForLoop](https://github.com/straight-shoota/crinja/blob/wip/invalid-memory-access-iterator/src/lib/util/for_loop.cr)
* [Crinja::Value](https://github.com/straight-shoota/crinja/blob/wip/invalid-memory-access-iterator/src/runtime/value.cr)
* [Crinja::Value::Iterator](https://github.com/straight-shoota/crinja/blob/wip/invalid-memory-access-iterator/src/runtime/value.cr#L191)

Using this branch, the following code will trigger the error:
```crystal
require "./src/crinja.cr"
Crinja::Tag::For::ForLoop.new(Crinja::Value.new((0..4).each)).each { |value| }
```
Alternatively, you can run the spec for this: `crystal spec spec/tags/for_spec.cr:60`

This is quite difficult to debug... so if anyone has a suggestion on what I might try to do...

Crystal version: 0.24.1

**Comment by straight-shoota** [comment]
The original code doesn't reproduce anymore. I've updated the failing branch to work with Crystal 0.28.0 and the code example to trigger it is changed to this:

```cr
require "./src/crinja.cr"
Crinja::Tag::For::ForLoop.new(Crinja::Value.new((0..4).each.as(Iterator(Crinja::Type)))).each { |value| }
```

It's a slightly different error, so maybe it's a different reason as well, but I'm not sure.
```
Invalid memory access (signal 11) at address 0xffffff89
[0x515826] *CallStack::print_backtrace:Int32 +118
[0x4ddb50] __crystal_sigfault_handler +192
[0x7f53832b1390] ???
[0x595021] *Crinja::Value#size:Int32 +17
[0x7f5383f07000] ???
```

**Comment by baelter** [comment]
I think I encountered this as well. Unfortunately I could not pin point it and make a small example. But it seems related to redeclaring instance variables in mixin modules.

**Comment by straight-shoota** [comment]
Closing. There's no point in keeping this open whithout an isolated reproduction.
