### ISSUE TITLE
Can't parse Float64 starting with zero on YAML files?

### ISSUE THREAD

**Issue by potz** [crystal-lang/crystal#5698]
Crystal version: 

`Crystal 0.24.1 (2017-12-26) LLVM: 5.0.1 Default target: x86_64-apple-macosx`

This works:

```crystal
require "yaml"

class Config
  YAML.mapping(x: Int32, y: Float64)
end

str = <<-YAML
dev:
  x: 12464  
  y: 3.5
YAML
 
dev = Hash(String, Config).from_yaml(str)["dev"]
dev.y  # => 3.5
```

This doesn't:

```crystal
require "yaml"

class Config
  YAML.mapping(x: Int32, y: Float64)
end

str = <<-YAML
dev:
  x: 12464  
  y: 0.5
YAML
 
dev = Hash(String, Config).from_yaml(str)["dev"] 
#=> Expected Float64, not 0.5 at line 3, column 6
```

I'm using scientific notation (`5e-2`) as a workaround at the moment, which also works.

**Comment by straight-shoota** [comment]
Seems like the yaml core parser treats any plain value starting with a zero as an octal integer.

**Comment by potz** [comment]
Yeah... `.5` also doesn't work

**Comment by straight-shoota** [comment]
But that's according to the spec http://yaml.org/type/float.html

**Comment by straight-shoota** [comment]
I have a patch for this but also discovered some other issues with parsing YAML floats :/
