### ISSUE TITLE
File.basename should support '.*' suffix

### ISSUE THREAD

**Issue by sudo-nice** [crystal-lang/crystal#5706]
After several cases of files loss it became evident to me that [`File.basename`](https://github.com/crystal-lang/crystal/blob/80a975cf0a98a4ce8464d0069145131667becd70/src/file.cr#L256) is not supporting `'.*'` suffix currently. Please, consider adding this feature, because:

- It's handy.
- Ruby-backgrounded newcomers could suffer the lack of it.

**Possible implementation:**
```
def self.basename(path, suffix) : String
  suffix.check_no_null_byte
  return basename(path, self.extname(path)) if suffix == ".*"
  basename(path).chomp(suffix)
end
```

**Possible specs:**
```
it "gets basename removing suffix" do
  File.basename("/foo/bar/baz.cr", ".*").should eq("baz")
  File.basename("/foo/bar/baz.tar.gz", ".*").should eq("baz.tar")
end
```

**EDITED:** Should act consistently with `File.extname`.

**Comment by oprypin** [comment]
You mean,

> File.basename should **not** support '.*' suffix and instead do something completely unexpected for it

I don't feel the same way. The function then becomes a time bomb when used with a variable 2nd argument.

**Comment by straight-shoota** [comment]
Yeah but it's completely different behaviour. I'm not sure it makes sense to slessentially support glob patterns in arbitrary path handling methods.

The same goal can actually be achieved with `File.basename(file, File.extname(file))`.

Maybe there could be a special method do access the name /wo extension directly. Python's pathlib for example has [`path.stem`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.stem) for this.

**Comment by sudo-nice** [comment]
@straight-shoota 

**Currently:**

    filename = "foo.tar.gz"
    File.basename(filename, File.extname(filename)) # foo.tar

**Implemented:**

    filename = "foo.tar.gz"
    File.basename(filename, ".*") # foo

**Comment by RX14** [comment]
I'm actually surprised we don't have an existing way to get the filename without extension. Isn't this included in the new path PR?

**Comment by straight-shoota** [comment]
Not yet. I only copied the existing `basename` methods for now. We'd have to find a name (just copy `stem`?) and decide what to do with `basename(String)` which essentially returns the basename without a specific extention.
