### ISSUE TITLE
pointerof on struct members

### ISSUE THREAD

**Issue by S-YOU** [crystal-lang/crystal#5709]
Lets say I have, struct of interface statistics like following.

```
struct PortStatistics
    tx : LibC::UInt64T
    rx : LibC::UInt64T
    dropped : LibC::UInt64T
end

port_statistics = uninitialized PortStatistics

```

Native counter functions want to have access directly on fields to update values like `&dropped` in C.

I could work around this by not using struct or by casting and hardcoding offsets, but I hope I could use like 

```
pointerof(port_statistics.dropped)
```

**Comment by asterite** [comment]
pointerof(port_statistics.@dropped)

**Comment by S-YOU** [comment]
wow, really. thank you very much.
