### ISSUE TITLE
Spec file with name t_if_spec.cr not run

### ISSUE THREAD

**Issue by gummybears** [crystal-lang/crystal#5711]
Crystal 0.24.1 (2017-12-22)
LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
Linux Mint 18.2 64 bits

Creating a spec file with name 't_if_spec.cr' or 't_if_else_spec.cr' is not picked up by 
$ crystal spec
It seems spec files with reserved keywords in them are NOT run.

Renaming the spec file will run the test spec

**Comment by bew** [comment]
In which directory is the file?

**Comment by gummybears** [comment]
Yes the spec file is located in the spec/ directory. I just renamed the spec file, so I can continue testing/developing. If more information is needed, let me know.

**Comment by sdogruyol** [comment]
This can't be reproduced on Crystal `master`. Here's what I've done to reproduce.

```
➜  ccrystal init app t_if     
Using compiled compiler at `.build/crystal'
    create  t_if/.gitignore
    create  t_if/.editorconfig
    create  t_if/LICENSE
    create  t_if/README.md
    create  t_if/.travis.yml
    create  t_if/shard.yml
    create  t_if/src/t_if.cr
    create  t_if/src/t_if/version.cr
    create  t_if/spec/spec_helper.cr
    create  t_if/spec/t_if_spec.cr
Initialized empty Git repository in /home/sdogruyol/playground/crystal/t_if/.git/
➜  cd t_if 
➜  ccrystal spec
Using compiled compiler at `.build/crystal'
F

Failures:

  1) TIf works
     Failure/Error: false.should eq(true)

       Expected: true
            got: false

     # spec/t_if_spec.cr:7

Finished in 105 microseconds
1 examples, 1 failures, 0 errors, 0 pending

Failed examples:

crystal spec spec/t_if_spec.cr:6 # TIf works
```

**Comment by gummybears** [comment]
As being a Crystal novice, it seems the spec file was skipped as a previous test silently 'exited'. I did not noticed this, as there are lots of tests. Now that I fixed the problem the spec file t_if_spec.cr is ran, as it should. Sorry for wasting everbody's time. Closing this issue.

**Comment by RX14** [comment]
Perhaps we should discuss having a message "exit called in spec!" if exit is called inside a spec accidentally. Since the summary is inside an `at_exit` handler, it's very easy to mistake an early exit for a successful run. This bug may also have been caught by randomizing spec execution order but that's a lot harder.

**Comment by gummybears** [comment]
Sorry for not being clear, the exit was called in my codebase (large), and I did not see it.

**Comment by bew** [comment]
@RX14 I like your idea about telling the user that `exit` was called from the specs, maybe this could be done by writing an overload of `exit` that take the caller's position, to be able to tell the user exactly what exited?

**Comment by RX14** [comment]
@gummybears yeah that's what I was suggesting to catch.

@bew just override exit to raise an exception if it's "inside" a spec. It can tell if it's inside a spec by checking some class variable inside `Spec`.

**Comment by bew** [comment]
yes that's another way to do it
