### ISSUE TITLE
Implement rounding modes for BigDecimal

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#5714]
In the spirit of Ruby's [`BigDecimal#round(n, mode)`](http://devdocs.io/ruby~2.5/bigdecimal#method-i-round).

"[Bankers rounding](https://en.wikipedia.org/wiki/Rounding#Round_half_to_even)" example:

ruby:
```ruby
"1.5".to_d.round(0, :half_even) # => 2.0
"2.5".to_d.round(0, :half_even) # => 2.0
```

crystal:
```crystal
# no such thing atm :(

"1.5".to_big_d.round(0) # => 2.0
"2.5".to_big_d.round(0) # => 3.0
```

**Comment by greenbigfrog** [comment]
Is there a reason why there has been no progress/comment on this?

**Comment by mathijsclaassen** [comment]
I think https://github.com/crystal-lang/crystal/issues/10228 fixed this

**Comment by straight-shoota** [comment]
No, #10413 only implemented rounding modes for primitive number types. #7126 is still pending.
