### ISSUE TITLE
Docker performance is dramatically bad

### ISSUE THREAD

**Issue by ababich** [crystal-lang/crystal#5725]
Hi! I created a small hello-world test on like empty Kemal app

Kemal app is twice slower than naked crystal but it is ok

I compile it on my mac and inside docker image (official, from Dockerfile in this repo) both with logging enabled and in `--release` mode

I ran `wrk --threads 2 --duration 10`

What I have - for standalone on my machine:

```
Running 10s test @ http://localhost:3001/
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   321.88us  160.57us   3.01ms   81.95%
    Req/Sec    15.69k     1.80k   19.59k    70.30%
  315303 requests in 10.10s, 36.38MB read
Requests/sec:  31217.64
Transfer/sec:      3.60MB
```

from docker
```
Running 10s test @ http://localhost:3000/
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.25ms    1.67ms  22.29ms   96.04%
    Req/Sec     2.41k   593.89     4.40k    77.00%
  47897 requests in 10.00s, 5.53MB read
Requests/sec:   4787.75
Transfer/sec:    565.74KB
```

The difference is HUGE  **6.5 times on average**

Can you please hint me how to make docker performance comparable?

**Comment by RX14** [comment]
You're using docker on OSX, and docker only runs natively on linux. Installing docker on OSX means that docker is actually being installed inside a hidden linux VM. The overhead of that VM is very likely to be the cause of your issue.

**Comment by ababich** [comment]
Thanks for a good point. Just retested in Linode Ubuntu  VM
results are `38656.31` vs `12309.90` which is **3.1x** on average

if I disable logging, results are very close

and this is much worse than docker images for ruby, for exmaple
`ruby:2.5` image with roda app with logging gives me **> 9K requests/sec** on same machine

which makes crystal performance advantage not very significant when in containers

May be there are other ways to improve dockerization for crystal? 

Thanks

**Comment by RX14** [comment]
@ababich at 12000 requests per second you really don't want logs on. If the results are close without logging, the bottleneck is likely disk IO. I suspect logging to a network service (which is the only realistic solution for logging at ~8mbps) will perform the same inside and outside docker.

Alternatively, put your logfile on a docker volume that's mounted on the host. That will remove any IO overhead on overlay, and any IO overhead with the docker daemon if you log to stdout.

**Comment by lbguilherme** [comment]
Also keep in mind that printing to stdout on docker will actually write data to disk, on the container logfile.

**Comment by ababich** [comment]
@lbguilherme thanks for IO note, that totally supports @RX14 comment and my experiments

**Comment by RX14** [comment]
Also keep in mind that latency, not throughput, will be the visible performance metric to your users and logging and disk io won't affect latency until you're close to max throughput. So as long as you're below 10k requests per second your users are likely going to say the page loads faster in crystal.

**Comment by ababich** [comment]
Such an extreme metric are under investigation for IOT device who are going to DDOS my services at ~100K/s rate, so that I'm investigating how to load-balance and scale while I have flexibility in implementation right now

Thanks for your help!
