### ISSUE TITLE
Array#shift is too slow

### ISSUE THREAD

**Issue by ssvb** [crystal-lang/crystal#573]
The standard library in Crystal implements the Array "shift" method as a move of the whole buffer in memory, which is very slow for large arrays.

**Comment by asterite** [comment]
@ssvb Any other way to implement this with better performance?

I think that if `shift is your bottleneck you should use another datastructure, maybe a linked list, circular buffer, etc. (all of which don't exist yet, but could)

**Comment by kirbyfan64** [comment]
@asterite There are a few good ones [here](http://stackoverflow.com/questions/876293/fastest-algorithm-for-circle-shift-n-sized-array-for-m-position), but they're still all O(n). Main thing I'm seeing is that [this is probably O(n\*2)](https://github.com/manastech/crystal/blob/master/src/array.cr#L816).

**Comment by asterite** [comment]
@kirbyfan64 Why? I think that line should be O(n), with "n" being "n".

**Comment by kirbyfan64** [comment]
@asterite How I understood the code is:

- Create a new array. O(1).
- For each element up to `n`, initialize `ary`. O(n).
- Move the buffer via `move_from`. This is usually O(n) (`memmove` is O(n), and [this is definitely O(n)](https://github.com/manastech/crystal/blob/master/src/pointer.cr#L183); not sure about `copy_to`).

O(n) + O(n) = O(n\*2). Each byte in the array is accessed twice: once for initializing `ary`, and once when being copied by `move_from`.

Sorry. X64 nerd...

**Comment by asterite** [comment]
@kirbyfan64 Oh, sorry, I read it as `O(n^2)`, my mistake.

**Comment by waj** [comment]
O(n) and O(n*2) are the same thing (https://en.wikipedia.org/wiki/Big_O_notation)

The current implementation is actually O(n) where n is the length of the array (not the argument) because it always have to copy `n` values to the new array and move the remaining `length - n` elements in place.

Performance improvements probably can be made using low level functions to move many elements at once, but I don't think the order of the function can be any lower than O(n).

**Comment by kirbyfan64** [comment]
I have created a marginally faster version:

```crystal
def shift(n)
  if n < 0
    raise ArgumentError.new("can't shift negative count")
  end

  n = Math.min(n, @length)
  ary = Array(T).new(n)
  ary.length = n

  @buffer.move_from(@buffer + n, @length - n)
  ary.buffer.move_from(@buffer, n)
  @length -= n
  (@buffer + @length).clear(n)

  ary
end
```

Instead of initializing `ary` with the elements, looping over each one individually, this version can call `memmove` with some data types. Using this test program:

```crystal
x = Array(Int32).new 9999999, 0
x.shift(9999)
x.shift(9999)
x.shift(9999)
x.shift(9999)
puts x[2] # make sure this won't get optimized out
```

my version is about 0.05-0.1s faster. Seems marginal, but it's something.

Here's a diff:

```diff
diff --git a/src/array.cr b/src/array.cr
index 39fca1a..dd89ed5 100644
--- a/src/array.cr
+++ b/src/array.cr
@@ -813,9 +813,11 @@ class Array(T)
     end
 
     n = Math.min(n, @length)
-    ary = Array(T).new(n) { |i| @buffer[i] }
+    ary = Array(T).new(n)
+    ary.length = n
 
     @buffer.move_from(@buffer + n, @length - n)
+    ary.buffer.move_from(@buffer, n)
     @length -= n
     (@buffer + @length).clear(n)
```

**Comment by waj** [comment]
Don't you have to populate `ary` before moving the `@buffer` contents? Please, make sure the specs are still passing and then send a pull request ;-)

**Comment by kirbyfan64** [comment]
> Don't you have to populate `ary` before moving the `@buffer` contents?

Whoops. Fixed. Still slightly faster!

> Please, make sure the specs are still passing and then send a pull request ;-)

Will do!

**Comment by asterite** [comment]
We now have `Deque`, thanks to @BlaXpirit . If you need to shift, push, pop, and unshift a lot, a deque is probably the data structure you need. So I'm closing this.
