### ISSUE TITLE
Can't use `AModule::AConst = 1` to declare a constant

### ISSUE THREAD

**Issue by bew** [crystal-lang/crystal#5742]
```cr
ModuleFoo::Bar = 1

{% puts ModuleFoo.class_name %} # => NumberLiteral

puts ModuleFoo::Bar  # undefined constant ModuleFoo::Bar
```
https://carc.in/#/r/3mjb

I would expect it to create a module named `ModuleFoo` with a constant `Bar` inside it.
Instead, `ModuleFoo::Bar = 1` creates a constant `ModuleFoo` with value `1`, discarding `Bar` completely.

Apart from the fact that the current behavior is a bug, as we already have a few other places where we can use a module name in front of something, I think it would be consistent to allow this for constants too.

**Comment by RX14** [comment]
Yeah the current behaviour is a bug but I'd also be fine with this being a compile error.
