### ISSUE TITLE
Additional options for Socket Constants

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#5748]
I'm working on adding native Bluetooth sockets to Crystal.

I'll do it in stages, for now I added relevant constants at #5746, I'll work next on adding socketaddr for Bluetooth sockets.

**Comment by bew** [comment]
Not sure this should go in the stdlib, (so as a PR here), why not create a shard first?

**Comment by bararchy** [comment]
@bew it seems you can't open enums later on, so I can't "monkey patch" the socket part outside of the stdlib

**Comment by bararchy** [comment]
If we really want those things extended, then maybe we should change the way Socket constants are handled etc..

**Comment by bew** [comment]
No idea, @ysbaddaden did most (all?) of the work for sockets, maybe he has an idea about this?

**Comment by ysbaddaden** [comment]
If we can't reopen enum definitions, then monkey-patching is impossible, because all Socket functions rely on those enums.

**Comment by bararchy** [comment]
@ysbaddaden @bew 
So my current PR stands as this is the only way in Crystal to add support for more abilities, unless, we allow passing numbers and not objects into the Socket.new() method.
UInt8, Int32, Int32 .
Etc..

**Comment by ysbaddaden** [comment]
Well, you broke all targets but linux-gnu and darwin :(

I think bluetooth sockets and filling C constants are too much for the crystal stdlib. They're unavailable by default; you must install a package for C headers to be installed.

You shouldn't use `Socket` but `socket(2)` and other C functions directly for the time being —unless or until we change Socket low level wrappers to rely on integers instead of enums, *or* we allow reopening enums to add new values, which sounds like a better idea to me, but I don't know its feasibility.

**Comment by bararchy** [comment]
@ysbaddaden Can I just add this as a 2nd initialize instead? 

```crystal
def initialize(@family : UInt8, @type : Int32, @protocol = Int32, blocking = false)
    @closed = false
    fd = LibC.socket(family, type, protocol)
    raise Errno.new("failed to create socket:") if fd == -1
    init_close_on_exec(fd)
    @fd = fd

    self.sync = true
    unless blocking
      self.blocking = false
    end
end
```

**Comment by ysbaddaden** [comment]
Actually, you can create enums from whatever values, so you may:

```crystal
require "./lib_bluetooth"

class BluetoothSocket < Socket
  enum Protocol
    RFCOMM = LibC::BTPROTO_RFCOMM
  end

  def initialize(type = Socket::Type::STREAM, protocol = Protocol::RFCOMM, blocking = false)
    super(
      Socket::Family.new(LibC::AF_BLUETOOTH),
      type,
      Protocol.new(protocol.value),
      blocking)
  end
end
```

**Comment by bararchy** [comment]
@ysbaddaden Looks good. 
Thanks
