### ISSUE TITLE
Signed integer division overflow

### ISSUE THREAD

**Issue by ssvb** [crystal-lang/crystal#575]
Other than division by zero, there is one more special case. Dividing the lowest negative number by -1 also triggers the hardware exception. For example, for the Int32 type the lowest negative number is -0x80000000 and the largest possible representable positive number is 0x7FFFFFFF. Because (-0x80000000 / -1) == 0x80000000, it does not fit into Int32. The following test program demonstrates the problem:
```ruby
begin
  p Int32::MIN / 0
rescue
  puts "Division by zero handled"
end

begin
  p Int32::MIN / -1
rescue
  puts "Division overflow handled"
end

puts "Successfully finished"
```
The current result:
```
Division by zero handled
Program terminated abnormally with error code: 8
```

**Comment by jhass** [comment]
> \<ssvb> jhass: the sanity check in https://github.com/manastech/crystal/blob/36d468bcdbfe69e42ea372dba6189fd61c6ab30d/src/int.cr#L63 can be also extended to handle this special case
\<jhass> ah, kay that's actually easy
\<ssvb> at the expense of having a bit higher runtime overhead
\<waj> yes but also is that the only case?
\<ssvb> waj: yes, one can check the Intel manual about the division instruction
\<ssvb> it describes these special cases, where hardware exception can be raised by the CPU when handling this instruction
\<ssvb> also ruby code can be probably used as a reference, it should handle these cases too (I have not checked this yet)
\<waj> yup, makes sense. So for signed integer division, MIN_VALUE / -1 should raise an overflow exception

**Comment by waj** [comment]
I just found that it might be possible to raise exceptions from signal handlers. Not easy, but possible.

Just trapping the SIGFPE signal and raising from the signal handler works while compiling in non-release mode (at least in my Mac) but crashes in release mode. Of course this would need more understanding of signal handling and it probably requires specific and different work for Linux and OSX.

I was digging into [Julia](http://julialang.org/) source code, and found they do this as well: https://github.com/JuliaLang/julia/blob/master/src/signals-unix.c#L4-L13. I hope @JeffBezanson don't mind if we copy some ideas :-)

**Comment by waj** [comment]
BTW, in Linux, it's possible to pass a flag (-fnon-call-exceptions) to GCC to allow exceptions to be thrown in these situations.
