### ISSUE TITLE
method_missing variant for constants like constant_missing?

### ISSUE THREAD

**Issue by S-YOU** [crystal-lang/crystal#5751]
Use case, I have C library with 300+ structs.
Whenever I use structs from that C library, I have to use `LibName::ConstantName`.
It will be much cleaner If I can forward constant_missing to that Lib.
Of course I can generate alias for that 300+ structs, but it is still look too much codes.
Correct me If I am wrong.

**Comment by bew** [comment]
Note: When #5244 is done, you would be able to generate the aliases with a macro.

**Comment by shevegen** [comment]
**constant_missing** seems simpler/easier than macro but that is just my personal opinion.
