### ISSUE TITLE
Inherit documentation from abstract types

### ISSUE THREAD

**Issue by ryankshah** [crystal-lang/crystal#5759]
I don't think this is possible as of yet from what I've looked through so far, but it seems like a potentially useful feature to make it that little bit easier writing documentation.

For example in Java, you can use the following code to inherit documentation from that of the class' super:

```
/**
 * {@inheritDoc}
 */
```

**Comment by dscottboggs** [comment]
I've seen special `# :something: ` syntax in those docstrings, but I haven't yet seen any documentation on some source, e.g. `# :nodoc: ` to have it not show up in the documentation.

We could have a similar `# :inherit:` syntax that would have this functionality.

**Comment by dscottboggs** [comment]
#6989 will solve this in an even better way :grin:

**Comment by Blacksmoke16** [comment]
This can prob be closed now that https://github.com/crystal-lang/crystal/pull/6989  is merged.

**Comment by asterite** [comment]
@Blacksmoke16 Good point.

We are missing document this new behavior in https://crystal-lang.org/reference/conventions/documenting_code.html . Someone wants to tackle that?
