### ISSUE TITLE
Cannot create an enum flag instance from value 0

### ISSUE THREAD

**Issue by bew** [crystal-lang/crystal#5768]
```cr
@[Flags]
enum A
  A
  B
  C
end

pp A::None.value

puts A.from_value 0 # => Unknown enum A value: 0 (Exception)
```
https://carc.in/#/r/3o46

I think this should give `A::None`, not an exception.

**Comment by bew** [comment]
It's even spec'd this way:
https://github.com/crystal-lang/crystal/blob/3f99c77cb07435db87b02c3e59f3448c7f4a2c07/spec/std/enum_spec.cr#L119-L120

What is the reasoning behind this behavior?

To me an Enum flag with value 0 is a valid enum flag (None).

**Comment by RX14** [comment]
Yeah I'd expect that to work.
