### ISSUE TITLE
Array of NamedTuple

### ISSUE THREAD

**Issue by gummybears** [crystal-lang/crystal#5770]
Not a bug, beginners question on how to build an array consisting of NamedTuple
Example

x = Array({name: String, year: Int32})
named_tuple = {name: "Crystal", year: 2011}
x << named_tuple
puts x[0]
$ crystal tuple.cr
Error in tuple.cr:4: undefined method '[]' for Array(NamedTuple(name: String, year: Int32)):Class

**Comment by straight-shoota** [comment]
This issue tracker is not the right place for beginner questions, please ask such questions on [SO](https://stackoverflow.com/questions/tagged/crystal-lang) or in the [Gitter chat](https://gitter.im/crystal-lang/crystal).

----

The error message you quoted is incorrect, it should be `Error in line 3: undefined method '<<' for Array(NamedTuple(name: String, year: Int32)):Class` (see [carc.in](https://carc.in/#/r/3o87)).

As the error message says, `x` is not an `Array` but the class of `Array` (`Array:Class`). You need to initialize an instance of that class:
```crystal
x = Array({name: String, year: Int32}).new
```


Tip: You can activate code highlighting by putting the example code in code fences:
````
```crystal
x = Array({name: String, year: Int32})
named_tuple = {name: "Crystal", year: 2011}
x << named_tuple
puts x[0]
```
```` 
And it looks like this:
```crystal
x = Array({name: String, year: Int32})
named_tuple = {name: "Crystal", year: 2011}
x << named_tuple
puts x[0]
```

**Comment by gummybears** [comment]
Thanks for the help, sorry for asking here, next time I will use SO.
