### ISSUE TITLE
YAML unable to parse constant 0

### ISSUE THREAD

**Issue by Sevis666** [crystal-lang/crystal#5771]
I think there is an issue with YAML parsing, because reading the constant 0 raises an error **YAML::ParseException**. Other constants are read properly.

Minimal working code to trigger the error:
```crystal
require "yaml"
a = [ 0_i64, 1_i64 ]
Array(Int64).from_yaml YAML.dump(a)
```

I guess this is code is not expected to fail, it's just a basic conversion.

Executing this yields the following stack trace:
```
Expected Int64, not 0 at line 2, column 3 (YAML::ParseException)
  from /usr/lib/crystal/yaml/nodes/nodes.cr:30:9 in 'raise'
  from /from_yaml.cr:34:7 in 'parse_scalar'
  from /usr/lib/crystal/yaml/from_yaml.cr:49:1 in 'new'
  from /usr/lib/crystal/yaml/from_yaml.cr:88:11 in 'new'
  from /usr/lib/crystal/yaml/from_yaml.cr:2:3 in 'from_yaml'
  from minimal.cr:3:1 in '__crystal_main'
  from /usr/lib/crystal/crystal/main.cr:11:3 in '_crystal_main'
  from /usr/lib/crystal/crystal/main.cr:112:5 in 'main_user_code'
  from /usr/lib/crystal/crystal/main.cr:101:7 in 'main'
  from /usr/lib/crystal/crystal/main.cr:135:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```

I managed to fix it by calling **Int64.new(s : String)** in case *parse_scalar* fails, because *Int64.new* knows how to handle 0:

The following method is located in **crystal/yaml/from_yaml.cr** at **line 49**
```diff
 {% for type in %w(Int8 Int16 Int32 Int64 UInt8 UInt16 UInt32 UInt64) %}
   def {{type.id}}.new(ctx : YAML::ParseContext, node : YAML::Nodes::Node)
     {{type.id}}.new parse_scalar(ctx, node, Int64)
+  rescue e
+    begin
+      {{type.id}}.new parse_scalar(ctx, node, String)
+    rescue
+      raise e
+    end
   end
 {% end %}
```

This "patch" seems rather naive to me, but it fixes the bug for all test cases I could think of.

If this isn't the proper way to fix it, how may I help you in patching this ?
If it is already an acceptable patch, may I open a pull request for it ?

**Comment by straight-shoota** [comment]
Your patch is merely a workaround treating the symptoms. I created a PR wich fixes the problem in `YAML::Schema::Core#parse_scalar`.

**Comment by Sevis666** [comment]
Nice ! Thank's for fixing it

**Comment by RX14** [comment]
This hasn't been fixed yet.

**Comment by straight-shoota** [comment]
You just merged #5774?

**Comment by RX14** [comment]
Yes, I thought github would have closed this issue...

**Comment by straight-shoota** [comment]
According to the timestamps, reopen was 10 minutes after merge. That's why it didn't autoclose.

**Comment by RX14** [comment]
Huh, guess i'm going crazy after all.
