### ISSUE TITLE
File.extname considers the whole path as a filename

### ISSUE THREAD

**Issue by sudo-nice** [crystal-lang/crystal#5780]
`puts File.extname("/foo.bar/baz")`
Expected output: `""`
Actual output: `".bar/baz"`

Crystal 0.24.1

**Comment by straight-shoota** [comment]
It's really disturbing this hasn't been noticed before...

Judging from the documentation it seems like this method is supposed to receive only a filename, not an entire path. So you'd be expected to use it as `File.extname(File.basename("/foo.bar/baz"))`.
But that's not very intuitive and I don't think it makes sense this way.

**Comment by Sija** [comment]
In Ruby it returns `nil. Just FYI.

**Comment by straight-shoota** [comment]
@Sija That's a different thing, please open a new issue if you want to change that. `File.extname` always returns empty string if there is no extension.

**Comment by sudo-nice** [comment]
@Sija In Ruby `File.extname("/foo.bar/baz")` will return an empty string. But `puts` will return `nil`, yes.

**Comment by shevegen** [comment]
> So you'd be expected to use it as File.extname(File.basename("/foo.bar/baz")).
> But that's not very intuitive and I don't think it makes sense this way.

Agreed - it must be a behaviour bug then. 

The output ".bar/baz" can quite logically never be an "extension name". I don't
even know how "/" could ever be part of any extname so it sounds like a bug.
