### ISSUE TITLE
Multiple assignment count mismatch

### ISSUE THREAD

**Issue by benjis** [crystal-lang/crystal#5793]
According to: https://crystal-lang.org/docs/syntax_and_semantics/multiple_assignment.html

> If the left-hand side contains just one variable, the right-hand side is considered an array:
>names = "John", "Peter", "Jack"
># The above is the same as:
>names = ["John", "Peter", "Jack"]

However, above code throws "Multiple assignment count mismatch" syntax error.
```
➜  ~ crystal test.cr
Syntax error in test.cr:1: Multiple assignment count mismatch

names = "John", "Peter", "Jack"
^
```

Is this intended behaviour in Crystal or the doc needs a update?

- Crystal 0.24.1 (2018-01-27) 
- LLVM: 5.0.1 
- Default target: x86_64-apple-macosx

**Comment by codyjb** [comment]
It looks as though the spec doesn't allow for this behavior, suspect the docs are wrong at this point 
https://github.com/crystal-lang/crystal/blob/322d1c477f0dff6c166efeb66fb4378370fcaf90/spec/compiler/parser/parser_spec.cr#L145

**Comment by straight-shoota** [comment]
Bare array creation was removed in 0.24.0 (see #4824). The language reference has not yet been updated.
