### ISSUE TITLE
No docs for Channel

### ISSUE THREAD

**Issue by Jens0512** [crystal-lang/crystal#5801]
[The 0.24.1 (and current) api-docs](https://crystal-lang.org/api/0.24.1/Channel.html) has no documentation whatsoever for the `Channel` class .

This is currently quite a central piece in Crystal's concurrency, so I feel that this is important and should be documented for next release.

**Comment by straight-shoota** [comment]
There is a [guide on concurrency](https://crystal-lang.org/docs/guides/concurrency.html) in the language reference which also includes some information about `Channel`. This could be used as a starting ground for improving API docs.
