### ISSUE TITLE
Int32 shift left with String throws an Error

### ISSUE THREAD

**Issue by ryankshah** [crystal-lang/crystal#5825]
When performing the following code:

```crystal
require "openssl"
digest = OpenSSL::Digest.new("SHA256")
hash = digest.hexdigest
puts 1 << hash
```

It throws the following error:

```crystal
no overload matches 'Int32#<<' with type String
Overloads are:
 - Int#<<(count : Int)

 puts 1 << hash
```

I am trying to achieve a similar effect to the following Python code, but can't wrap my head around this:

```python
import mmh3
1L << mmh3.hash128(...)
```

**Comment by RX14** [comment]
This is an issue tracker, not a help forum. You're much more likely to get help if you ask in gitter or the mailing list. See: https://github.com/crystal-lang/crystal#community
