### ISSUE TITLE
Crystal-compiled binaries depend on libgc on linux?

### ISSUE THREAD

**Issue by sam0x17** [crystal-lang/crystal#5827]
On linux I have found that with recent versions of crystal (0.24.1+) any binaries produced by crystal depend on libgc to be able to run. This is a big problem for me as I have been using crystal 0.23.1 in production in Google Cloud Functions (google equivalent of AWS Lambda) by invoking crystal-compiled binaries from Node.js. Until 0.24.0, this worked fine without issue so I assume the dependency was introduced there. It seems the image Google runs their cloud functions in does not have libgc (and there is no way for me to install packages without asking Google directly which is never going to work out).

```
Error: function crashed.Details:
Command failed: ./hello_world
./hello_world: error while loading shared libraries: libgc.so.1: cannot open shared object file: No such file or directory
```

What I'm hoping for is at least a way to statically link libgc when crystal compiles a binary. Is this something that can be done?

My fallback will be to simply include a copy of libgc.so.1 in my deploy, but I'd rather not do that.

**Comment by sam0x17** [comment]
update: unfortunately still get the same error even when I include libgc.so.1 in the same directory

**Comment by ysbaddaden** [comment]
Unless you installed a shared version of the `libgc` library on your system, all builds should statically link the embedded `libgc.a` library.

**Comment by sam0x17** [comment]
Interesting, maybe this is an Ubuntu 17.10 specific issue then? I'll investigate

**Comment by matiasgarciaisaia** [comment]
@sam0x17 do you have a `ldd ./hello_world` to share? Have you installed Crystal through the Debian repo?

I've just booted a fresh Ubuntu 16.04, installed Crystal [following the instructions](https://crystal-lang.org/docs/installation/on_debian_and_ubuntu.html). `ldd /usr/lib/crystal/bin/crystal` says it's statically compiled.

I've created a `hello.cr` with just a `puts "Hello, world!"`, `crystal build`ed it, and `ldd hello` says it depends on linux-vdso, libpcre, libpthread, libevent, libdl, libgcc_s, libc and ld-linux-x86-64 - but nothing related to libgc.

**Comment by straight-shoota** [comment]
It seems like the build system (Ubuntu) probably has the shared libgc.so installed, so it will link dynamically. But the target system (Google Cloud Functions) does not have the shared library, so it can't load it.

**Comment by sam0x17** [comment]
Any idea how to change that? I'm not sure what to uninstall

**Comment by RX14** [comment]
If you install libgc on the system it'll use it preferentially over the static version. Some other packages can depend on libgc, and you need it to develop the crystal compiler anyway. I'd say that you are either static linking or not and we don't really support static linking yet, unfortunately. There's not much I would recommend doing on our side.

**Comment by straight-shoota** [comment]
Uninstalling `libgc-dev` should do it. Or do the build in a VM or whatever where this package is not installed.

**Comment by sam0x17** [comment]
@straight-shoota when I uninstall it, I can no longer compile:

```
$ crystal build hello_world.cr
Using compiled compiler at `.build/crystal'
/usr/bin/ld: cannot find -lgc (this usually means you need to install the development package for libgc)
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/sam/Desktop/workspace/crystal-microservice-hello-world/hello_world'  -rdynamic  -lpcre -lgc -lpthread /home/sam/Desktop/workspace/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
```

**Comment by straight-shoota** [comment]
This seems odd. Maybe set `LIBRARY_PATH=/usr/lib/crystal/lib/` helps?
Does it work with `--static`?
And why are you using a self-compiled compiler?

**Comment by sam0x17** [comment]
@straight-shoota I need to use master because I need https://github.com/crystal-lang/crystal/pull/5802 for crystal to be functional on my system. I'll try with 0.24.1 and see if it works, and I'll try --static.

**Comment by sam0x17** [comment]
@straight-shoota interesting. Using 0.24.2 fixes my compilation issue, however now when I execute the cloud function I get a libevent dependency issue:

```

Error: function crashed.Details:
Command failed: ./hello_world
./hello_world: error while loading shared libraries: libevent-2.1.so.6: cannot open shared object file: No such file or directory
```

**Comment by sam0x17** [comment]
update: using `--static` with 0.24.2 worked. Thanks @straight-shoota !!!!
