### ISSUE TITLE
Type inference in if statement is easy to break using OptionParser

### ISSUE THREAD

**Issue by obskyr** [crystal-lang/crystal#5834]
In Crystal 0.24.2, the following works just fine:

```crystal
out_path = nil

if out_path
    File.open out_path, "r"
end
```

However, this doesn't:

```crystal
require "option_parser"

out_path = nil

OptionParser.parse! do |parser|
    parser.on("-o", "Output file.") { |o| out_path = o }
end

if out_path
    File.open out_path, "r"
end
```

Instead, it fails with the following compiler error:

```
no overload matches 'File.new' with types (String | Nil), String, Int32, Nil, Nil
```

This despite the fact that `out_path` cannot possibly be `nil` in the body of that if statement. Given how easy this is to run into, I feel like this *must* have been reported before, but I couldn't find anything.

**Comment by bcardiff** [comment]
The block `{ |o| out_path = o }` is creating a closure over `out_path`, so it's value could potentially change at any time, like between the `if` and it's body. You know that that wont happen, but the compiler has no clue. Note that the `parser.on` blocks are evaluated after all the `parse!` block, and not sequentially.

A workaround is

```crystal
if path = out_path
  File.open path, "r"
end
```

The value of `path` can't be changed.

**Comment by straight-shoota** [comment]
This is essentially the same as with instance and class variables, see https://crystal-lang.org/docs/syntax_and_semantics/if_var.html
The docs should probably also mention this case of local variables involved in a closure.

**Comment by RX14** [comment]
It can be nil, if `parser.on` spawned a new fiber and kept calling the block with `o = nil` in a loop. Then between the `if out_path` check and the variable being used, the block could have been called to set `o = nil`, causing a segfault.

Hence, assigning to a value in a proc (or captured block) will disable flow typing on the variable - just like ivars.

**Comment by obskyr** [comment]
Thanks for the explanation! I'd recommend adding it to the docs page @straight-shoota mentioned, to avoid future confusion.

**Comment by straight-shoota** [comment]
Already on it!
