### ISSUE TITLE
Using nightly builds on Travis CI is broken

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#5836]
Using nightly builds on Travis CI has been advertised in [docs for Crystal language](https://docs.travis-ci.com/user/languages/crystal) for some time now, yet ATM it doesn't work.

Refs: https://github.com/travis-ci/travis-build/blob/b2a89dad8e7020c4c28b396639b36d87e5b1d4f6/lib/travis/build/script/crystal.rb#L80

---

Without nightly releases users caring about having their codebase tested on Travis CI against current Crystal are left with 3 less-than-optimal-options:

1. Wait for next Crystal release—which might happen... who knows when?
2. Use docker with nightly tag—~~but! `nightly` is 11 days old as of now, and new builds are tagged with `nightly-YYYYMMDD` scheme, making it hard to point at just that last release~~—fixed in #5837
3. Build it manually—ouch

Since nightly releases are being build as of #5182, the only thing missing would be hooking this up to apt package index, which is used by Travis CI.

With that in place we'd be able to use nice'n'simple `.travis.yml`:

```yml
language: crystal
crystal:
  - latest
  - nightly
```

Howgh! Thanks for reading!

**Comment by Sija** [comment]
@matiasgarciaisaia @bcardiff 1 week l8r... ping?

**Comment by Sija** [comment]
Ping again... 🕦 🌙  💤

**Comment by Sija** [comment]
@bcardiff 🏓

**Comment by bcardiff** [comment]
It's fine, so the nightly.crystal-lang.org domain should be redirected something else, right @jhass? The packages there were unsigned or it was using some key?

**Comment by jhass** [comment]
Yeah.

They were signed by a subkey of the one used for the main APT repo. I can check later this evening if I can still find it, if needed.

**Comment by Sija** [comment]
Regarding hosting debian packages on S3, I've found some resources which could help with that:
- https://github.com/krobertson/deb-s3
- https://github.com/aptly-dev/aptly

**Comment by RX14** [comment]
We already host debian packages on s3 for the releases. We should just ask travis to change how the `crystal: nightly` option works, and publish packages in the existing repo.

**Comment by jhass** [comment]
That is ask Travis just means sending a pull request to travis-build

**Comment by Sija** [comment]
Yes, and to do that we need to have an `apt` repo with nightlies.

See https://github.com/travis-ci/travis-build/blob/271a31325b6ad383d690ed81149554495eda08e9/lib/travis/build/script/crystal.rb#L80-L85

**Comment by Sija** [comment]
Actually if you'd keep the same domain and gpg key, the PR to `travis-build` is needless, it would Just Work™

**Comment by bcardiff** [comment]
@jhass if you had chance to find the certificate for nightly send it to me / follow up by email.

I was waiting for news from https://bintray.com/ for OSS projects and use nightlies there and see if it could be used to automate publishing of all releases. @Sija the options you send only support .deb packages.

**Comment by bcardiff** [comment]
For travis nothing else. But if we aim for nightlies in the same platforms as the official packages then, they are not enough as a complete solution. Worst case we host them in S3 but we want to check if a services may come handy.

**Comment by Sija** [comment]
@bcardiff my personal grief is stated in the original post, that is, using nightlies **on travis**, I also believe that would cover majority of use-cases. On my local machine I have no problem with compiling crystal myself, I don't need packaged nightlies for that. Of course that would be neat and all, but is it worth the hassle?

**Comment by straight-shoota** [comment]
Just a note: For the time being, you can also use this script to install Crystal nightly from circle ci artifacts: https://gist.github.com/straight-shoota/a2f4b29203936c04c578d6f6a1ad5f9b

**Comment by Sija** [comment]
@bcardiff Anything going on with this?

**Comment by bcardiff** [comment]
@Sija Not yet. The workaround for now is to use docker nightly images or the script, but in travis would be easier to use docker nightly

**Comment by vladfaust** [comment]
Any guide on how to run a *shard* build with crystal nightly docker image? Should I include a `Dockerfile` in the *shard*'s repository?

**Comment by vladfaust** [comment]
https://bintray.com supports OSS now, as seen on their website

**Comment by straight-shoota** [comment]
@vladfaust Just follow the guides to using docker images in your build: https://docs.travis-ci.com/user/docker/ and use image `crystallang/crystal:nightly`.

**Comment by vladfaust** [comment]
There are difficulties if need to test against databases with docker approach. I wonder why `nightly` doesn't work now? It's clearly a bug because Travis says `nightly` should work...

**Comment by Sija** [comment]
Bintray looks promising, especially with free OSS package... Perhaps it's the time to re-evaluate the situation? 🏓 @bcardiff

**Comment by Blacksmoke16** [comment]
Any update on this?
