### ISSUE TITLE
Inconsistency (or bug) in the subclasses macro, when only one subclass of a given class is defined

### ISSUE THREAD

**Issue by lipanski** [crystal-lang/crystal#5838]
```crystal
class Foo
end

class Bar < Foo
end

class Baz < Foo
end

# This works
foo_klasses : Array(Foo.class) = {{Foo.subclasses}}

class LonelyFoo
end

class LonelyBar < LonelyFoo
end

# This breaks with `type must be Array(LonelyFoo:Class), not Array(LonelyBar:Class)`
lonely_foo_klassess : Array(LonelyFoo.class) = {{LonelyFoo.subclasses}}
```

this is all about the type restrictions. the issue affects also the `all_subclasses` macro.

there's a spec that sounds like this is partially intended - https://github.com/crystal-lang/crystal/blob/master/spec/compiler/semantic/virtual_spec.cr#L16 - but I'm not sure what to make of it.

---

as pointed out by @faustinoaq and @unn4m3d (thanks!) there are some workarounds to this problem:

```crystal
lonely_foo_klassess : Array(LonelyFoo.class) = {{LonelyFoo.subclasses}}.map(&.as(LonelyFoo.class))
```

...or...

```crystal
{% begin %}
lonely_foo_klassess : Array(LonelyFoo.class) = {{LonelyFoo.subclasses}} of LonelyFoo.class
{% end %}
```

**Comment by asterite** [comment]
An array of a single subclass is inferred to be of that subclass, and that's not compatible with an array of a superclass (search covariance in this repo, the issue has been discussed a thousand times now). This is not a bug, use one of the workarounds, or some other way (maybe explain why you need all subclasses in the first place).
