### ISSUE TITLE
a Generics improvement suggestion

### ISSUE THREAD

**Issue by chenkovsky** [crystal-lang/crystal#5847]
```crystal
module A
  struct C
  end
  struct D
  end
end

class B(E)
  @v : E::C # currently this is invalid
  @v2 E::D
end

B(A)
```

this is very useful to reduce the number of type parameter.

**Comment by asterite** [comment]
This can't be implemented. At the time of compilation we need to know what type is `@v`, and we can't know it because `E::C` might not exist for a given `E`. Sorry, that's not how the language works.

Also, an explanation about why this reduces the number of type parameters is needed.

**Comment by asterite** [comment]
I guess it can be done but I don't want to do it because it will make the compiler's code even uglier.

**Comment by RX14** [comment]
My mind, untainted by the compiler internals, perceives this as a "simple" feature with very few knock-on effects (is the ivar type RHS -> look up the type). Why is that not the case?

**Comment by asterite** [comment]
There's a type for TypeParameter, there's no type for something relative to a type parameter.

**Comment by asterite** [comment]
Plus no concrete use case was provided
