### ISSUE TITLE
Formatter: Trailing comma bug

### ISSUE THREAD

**Issue by GloverDonovan** [crystal-lang/crystal#5853]
Found here: [shards/test/integration/update_test.cr](https://github.com/crystal-lang/shards/blob/c365c5b83680d07df86f0372917b5496965bd355/test/integration/update_test.cr#L63-L67)

With 0.24.2:

```shell
$ crystal tool format ./test/integration/update_test.cr --check
Error: couldn't format './test/integration/update_test.cr', please report a bug...
```

Reproducible  code:

```crystal
def with_shard(metadata, &block)
  yield
end

with_shard("hello", ) do
  puts "world"
end
```

With master (2d93603d4):

```shell
$ ./bin/crystal tool format a.cr --check
Using compiled compiler at `.build/crystal'
Error: couldn't format 'a.cr', please report a bug...
```

**Comment by Sija** [comment]
This is not a formatter bug, above example shouldn't compile in the first place.

**Comment by straight-shoota** [comment]
It compiles, and I think that is okay. It doesn't do any harm and array and hash literals accept trailing commas as well.
But the formatter should probably remove it (and obviously not fall over it).

**Comment by straight-shoota** [comment]
Just to clarify: A comma after a block argument (`foo(&block, )`) neither compiles nor formats because it is a syntax error. And that sound right.
