### ISSUE TITLE
Setter method receiving multiple arguments

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#5856]
A setter method (ending in `=`) can be defined having multiple arguments:

```cr
def foo=(a, b)
  pp a, b
end
```

But such a method can't be called. Obviously `foo = 1, 2` won't work because it is interpreted as two expressions. Adding parenthesis around the arguments `foo=(1, 2)` raises a syntax error: `unterminated parenthesized expression` probably because `(` after `=` is not recognized as parenthesis of a call.

I'm not sure if it should be supported that setter methods can receive multiple arguments. It seems like this is too complicated and unnecessary.
But if you can't call such a method with more than one argument, it would make sense to raise a syntax error for the method definition with multiple arguments as well.

**Comment by asterite** [comment]
Yeah, it should probably be disallowed. PRs are welcome :-)

**Comment by wontruefree** [comment]
I think in ruby there is something called greedy matches.  This means that it will turn the args into an array.  This does not get around arity but it does make things like this work.
Ruby: https://eval.in/1035570
```ruby
def setter=(a)
  puts a
end
setter = 1, 2
```

Also because of method sending this works which I dont know if we want in Crystal but it would be awesome.
Ruby: https://eval.in/1035572
```ruby
def setter=(a)
  puts a
end
setter, a = 1, 2
```

**Comment by RX14** [comment]
...how is that in any way awesome?

**Comment by asterite** [comment]
And the second snippet, using self.setter, already works in Crystal

**Comment by RX14** [comment]
Oh yeah, I see what the syntax is doing now, yeah that works (and should) in crystal. The first one used to work, but I removed implicit arrays in https://github.com/crystal-lang/crystal/pull/4824.

**Comment by wontruefree** [comment]
Yeah I was more just pointing it out first example.  I don't really have any opinion on the implicit array but I do like the second example.
