### ISSUE TITLE
What is the purpose of the end keyword?

### ISSUE THREAD

**Issue by fzzle** [crystal-lang/crystal#5865]
Does it have any pratical use or is it just syntactic fluff?

**Comment by konovod** [comment]
If you are speaking about indentation basing instead, there is an answer in FAQ for it - https://github.com/crystal-lang/crystal/wiki/FAQ#why-isnt-the-language-indentation-based

**Comment by jhass** [comment]
Since crystal applies no semantic to indentation it's quite needed.

**Comment by phil294** [comment]
I created a tiny wrapper around the Crystal compiler called Prystal which respects your indentation and allows you to omit the `end` keyword altogether: https://github.com/phil294/prystal

In one of my projects, this allowed me to delete 16% of my LOC without any further changes.

(Sorry. Still love Crystal :)

**Comment by straight-shoota** [comment]
If 16% if lines are just `end`, it seems like the codebase has a lot of boilerplate already.

Have you considered hiding lines with only `env` in your editor? Would perhaps be an easier way to remove visual noise 🤷

**Comment by phil294** [comment]
> Have you considered hiding lines with only `env` in your editor? Would perhaps be an easier way to remove visual noise 🤷

welp that would surely remove the noise while reading code, but seems to me like a highly impractical foot gun when *writing* it.
