### ISSUE TITLE
#zip should be available in Iterable, not just in Indexable and Iterator

### ISSUE THREAD

**Issue by obskyr** [crystal-lang/crystal#5868]
At the moment, using `#zip` on `Indexable`s of course works just fine (although it's barely documented, which is a bit annoying). The following, for example, is no problem: 

```crystal
# In this case, [1, 2, 3].zip([4, 5, 6]) returns a new array.
[1, 2, 3].zip([4, 5, 6]) do |x, y|
  puts "#{x} #{y}"
end
```

You can also use `#zip` on iterators, in which case it returns a new iterator instead of constructing an array:

```crystal
(1..3).each.zip((4..6).each).each do |x, y|
  puts "#{x} #{y}"
end
```

However... isn't that a bit verbose? 3 `each`es for one iterable zip? Wouldn't it be nice to be able to do the following on any `Iterable`?

```crystal
(1..3).zip(4..6) do |x, y|
  puts "#{x} #{y}"
end
```

I know I've missed it a few times now - it'd probably be a very welcome feature for others too.

**Comment by konovod** [comment]
There is a similar issue - #2977
It was mostly solved when `Indexable` was introduced, but explanation of @bcardiff and @asterite of why there isn't `zip` for two `Iterable`s is still valid.
Solution proposed there is to create Iterator implicitly, so you will have to write
```
((1..3).zip(4..6)).each do |x, y|
  puts "#{x} #{y}"
end
```
I'm not sure if it is good - still 1 `each` instead of 0 and some "magic" (allocating of Iterator) inside.

**Comment by RX14** [comment]
The only thing you can't zip is two enumerables - iterators and iterables can be zipped with anything. We should expose that in the API.

**Comment by asterite** [comment]
This can't be implemented. Closing.

**Comment by RX14** [comment]
ranges are iterable, so this is possible to implement

**Comment by asterite** [comment]
@RX14 You are right, this can be implemented with this patch:

```diff
diff --git a/src/iterable.cr b/src/iterable.cr
index 765eb0aeb..0d1463e9e 100644
--- a/src/iterable.cr
+++ b/src/iterable.cr
@@ -45,4 +45,14 @@ module Iterable(T)
   def each_with_object(obj)
     each.with_object(obj)
   end
+
+  def zip(other : Iterable)
+    each.zip(other.each)
+  end
+
+  def zip(other : Iterable, &block)
+    each.zip(other.each).each do |value|
+      yield value
+    end
+  end
 end
```

However, given this code:

```crystal
p (1..3).zip(4..6)
p [1, 2, 3].zip([4, 5, 6])
```

The output is:

```crystal
Iterator::Zip(Range::ItemIterator(Int32, Int32), Range::ItemIterator(Int32, Int32), Int32, Int32)(
 @iterator1=
  #<Range::ItemIterator(Int32, Int32):0x103612fe0
   @current=1,
   @range=1..3,
   @reached_end=false>,
 @iterator2=
  #<Range::ItemIterator(Int32, Int32):0x103612fc0
   @current=4,
   @range=4..6,
   @reached_end=false>)
[{1, 4}, {2, 5}, {3, 6}]
```

That is, for Array is naturally returns an Array (because it's an Iterable, but the method is overwritten) but for other Iterables it will return an Iterator. I think that's not intuitive, and that's why I'm not sure about adding such feature.

In fact, I'm not totally convinced about the `Iterable` module. Maybe we should just remove it, it just saves you from typing `each` just a very few times, and it adds to the confusion of `Iterator`, `Iterable`, `Indexable` and `Enumerable`.

**Comment by asterite** [comment]
(I'll close it in the meantime, unless we solve the confusing issue above)

**Comment by obskyr** [comment]
Sounds like it might be a good idea to just switch over to iterators everywhere, letting people convert to arrays if they need it.

**Comment by asterite** [comment]
@obskyr that would force everyone to write `to_a` at the end, which is much worse than writing `each` a few times here and there.

**Comment by asterite** [comment]
(and it's also not how Ruby works, and here I'd like to keep compatibility with Ruby because it's one of the nicest thing it has, as you usually never deal with iterators)

**Comment by obskyr** [comment]
I can't say I agree! For one, you'd only have to write `to_a` once whereas you now need to write a forest of `each`es. More importantly, though: as far as I know, iterating is a much more common use case for `zip` than having it in array form.

**Comment by Sija** [comment]
@obskyr not true, there are many cases where you'd expect the **result** (an `Array`) of an `Iterator`, not the one itself. Also, `zip` alone is used relatively rarely.

**Comment by obskyr** [comment]
Isn't it fine, then, to have `zip` return an array for arrays, but an iterator for iterables?

**Comment by RX14** [comment]
i think i share the concerns about iterable. methods should return an iterator, and only methods on iterators should compose iterators.

**Comment by asterite** [comment]
There's also this:

```crystal
require "benchmark"

Benchmark.ips do |x|
  x.report("map") do
    [1, 2, 3].map { |x| x + 1 }
  end

  x.report("each.map.to_a") do
    [1, 2, 3].each.map { |x| x + 1 }.to_a
  end
end
```

Output:

```
          map   6.64M ( 150.6ns) (± 9.29%)       fastest
each.map.to_a   4.93M (203.04ns) (± 5.91%)  1.35× slower
```

Immediate methods are much faster, specially `map`. And, in my experience, I usually use `map` alone, most of the time, not necessarily chaining it with more methods.

If performance is a concern in those cases where I have `map { ... }.select { ... }.and_more { ... }`, I can stick an `each` in the front and a `to_a` at the end. But that's usually not the case, as programs **usually** deal with small arrays, and these pieces don't end up being a program's bottleneck.

**Comment by straight-shoota** [comment]
For reference, this was implemented it #7453

**Comment by obskyr** [comment]
Oh, beautiful! How was that issue @asterite mentioned solved in the end? Does `(1..3).zip(4..6) { |x, y| puts x, y }` construct an array?

**Comment by asterite** [comment]
What issue?

**Comment by obskyr** [comment]
@asterite [This one!](https://github.com/crystal-lang/crystal/issues/5868#issuecomment-385172906) The one about returning inconsistent types.

**Comment by asterite** [comment]
if zip starts with an Iterator then it returns an Iterator, otherwise it returns an Array (as far as I remember)

**Comment by obskyr** [comment]
I see! Thanks for the info, and for the patch itself!
