### ISSUE TITLE
Channel#close doesn't invoke senders

### ISSUE THREAD

**Issue by carlhoerberg** [crystal-lang/crystal#5875]
```
ch = Channel(Nil).new
spawn(name: "Sender") do
  loop do
    ch.send nil
  end
rescue Channel::ClosedError
  puts "Sender closed"
end

spawn(name: "Receiver") do
  loop do
    ch.receive
    Fiber.yield
  end
rescue Channel::ClosedError
  puts "Receiver closed"
end

spawn(name: "Closer") do
  sleep 0.1
  puts "Closing channel"
  ch.close
end

sleep
```

Produces: 

```
$ crystal run test/close_channel.cr 
Closing channel
Receiver closed
```
Notably doesn't output `Sender closed` as I would've expected. 

I wild guess is that Channel#close (https://github.com/crystal-lang/crystal/blob/80a975cf0a98a4ce8464d0069145131667becd70/src/concurrent/channel.cr#L31L36) has to include

```
Scheduler.enqueue @senders
@senders.clear
```

```
$ crystal -v
Crystal 0.24.2 (2018-03-10)
LLVM: 5.0.1
Default target: x86_64-apple-macosx
```

**Comment by carlhoerberg** [comment]
overriding `Channel#close` in `Channel::Unbuffered` as this 
```
  def close
    super
    Scheduler.enqueue @sender.not_nil! if @sender
  end
```
solved it for unbuffered channels. 

I've experienced this in real apps with buffered channels to. Will try to make a reproduceable example.

**Comment by Sija** [comment]
@carlhoerberg It's always better to assign ivar to local var before usage, like:

```cr
def close
  super
  if sender = @sender
    Scheduler.enqueue sender
  end
end
```

**Comment by carlhoerberg** [comment]
Reproduable for buffered channel: 

```
ch = Channel(Nil).new(1)
spawn(name: "Sender") do
  ch.send nil
  ch.send nil
rescue Channel::ClosedError
  puts "Sender closed"
end

spawn(name: "Receiver") do
  loop do
    ch.receive
    Fiber.yield
  end
rescue Channel::ClosedError
  puts "Receiver closed"
  ch.close
end

spawn(name: "Closer") do
  sleep 0.1
  puts "Closing channel"
  ch.close
end

sleep
```

output: 

```
Closing channel
Receiver closed
```

No `Sender closed`

**Comment by carlhoerberg** [comment]
Haven't been able to create a short reproducable example with `Channel::Buffered`, but in an larger app we're working on we could. In it we could see that the "sender" fiber got stuck at: 
https://github.com/crystal-lang/crystal/blob/9f28c778d83ee0a753a0ea6ff958c56dc4f7688c/src/concurrent/channel.cr#L183

But modifying `Channel#close` as such: 

```
  def close
    @closed = true
    Scheduler.enqueue @receivers
    @receivers.clear
    Scheduler.enqueue @senders
    @senders.clear
    nil
  end
```

solved it.

Should I submit a PR for the two fixes or do you think there are more elegant ways to solve it?

**Comment by RX14** [comment]
Yeah these look like good fixes. I wish @waj was still around to check these PRs though...

**Comment by ysbaddaden** [comment]
You fix is good. `Scheduler.reschedule` will put the current fiber in pending mode, so we must reenqueue it again manually, otherwise it will be pending forever, even if just to let it crash. Receivers are resumed, senders should too.

By the way, this may explain a hangup I experienced in my actor library recently.
