### ISSUE TITLE
spec profile not working with option -p

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#5888]
```
crystal spec spec/some_spec.cr -p
```

not print 10 slowest specs:

in spec code:
```crystal
  opts.on("-p", "--profile", "Print the 10 slowest specs") do
    Spec.slowest = 10
  end
```

i think because option `-p` processed by compiler and need to rename it.

**Comment by bew** [comment]
You can do `crystal spec/some_spec.cr -- -p`

The `--` will tell the compiler to stop handling arguments, and the rest will go to the executed program

**Comment by kostya** [comment]
so this is ok?
