### ISSUE TITLE
@type.all_subclasses does not behave correctly

### ISSUE THREAD

**Issue by colonlc** [crystal-lang/crystal#5889]
Crystal 0.24.2 (2018-03-19)

LLVM: 6.0.0
Default target: x86_64-pc-linux-gnu

My intention was to have a type alias declared which  contains all the subclasses of my class.
However, if I use `@type.all_subclasses` or `@type.subclasses` inside a macro or inside `{%begin%}` and `{%end%}`, both are empty.

Example:
```Crystal
class A
  {%begin%}
    @@subclasses = {{@type.all_subclasses}}
  {%end%}
end

class B < A; end
class C < A; end
```
This generates to `@@subclasses = []` instead of `@@subclasses = [B, C]` and raises a  syntax error.

If I use it inside a `def`, it behaves correctly:
```Crystal
class A
  def self.subclasses
    {{@type.all_subclasses}}
  end
end

class B < A; end
class C < A; end

puts A.subclasses # => [B, C]
```

Am I misunderstanding the documentation or is this faulty behaviour?

**Comment by RX14** [comment]
Macros are a bit subtle in that it matters in which phase of complication they are run, and IIRC, `@
type` only really works when inside a method. I think we should give an error instead of an incorrect result here though.

**Comment by bew** [comment]
RX14 I don't think that's the problem, because moving B and C before works: https://carc.in/#/r/3ssy

OP's issue is that when the macro runs, the subclasses doesn't exists yet

**Comment by colonlc** [comment]
Ok, I can understand that. Sorry for the how to question, but is there any way i can get the macro to run after all subclassing even in external files?

**Comment by bew** [comment]
Yes, you can put your code in a macro called `finished`, that will be executed after all other macros, and after the initial pass on the code that defines all the types

**Comment by colonlc** [comment]
Thank very much. But I cannot find any documentation about that.. But that belongs to crystal-book.
