### ISSUE TITLE
unterminated tuple error with non-tuple literal case using implicit object methods

### ISSUE THREAD

**Issue by lego** [crystal-lang/crystal#5898]
```bash
$ crystal -v
Crystal 0.24.2 (2018-03-10)

LLVM: 5.0.1
Default target: x86_64-apple-macosx
```

The following code causes a compiler error that isn't clear what is incorrect.
```crystal
case {1, "hi"}
  when {1, .empty?} then "OK"
end

t = {1, "hi"}
case t
  when {1, "h"} then "OK"
end

case t # causes "unterminated tuple literal" on the line below
  when {1, .empty?} then "Welp, this line throws an error"
end
```
https://gist.github.com/lego/3c620476e718585661ea7952206e252e

As you can see, if a tuple type is provided in a `case` statement but is not an inlined literal then `"unterminated tuple literal"` is thrown, which does not clearly indicate what is happening. This only occurs when implicit-object method calls are used.

**Comment by lego** [comment]
I'd guess this is a parser error. I might take a stab at investigating how this could be fixed. (great coincidence, since this error happened while building a compiler :P)

**Comment by Sija** [comment]
Duplicate of #4953

**Comment by lego** [comment]
Thank you! Closing this. In the other issue, I mentioned the error message that is raised so hopefully anyone with the problem finds that issue (or even this one).
