### ISSUE TITLE
Proposal: Support true color in Colorize

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#5900]
Many terminals today support true color with ANSI escape sequences.

Here's an example:
```Crystal
puts "\e[38;2;100;255;100mI'm green\e[0m"
```
This would colour the text in a nice bright green color:
![I'm green](https://i.imgur.com/lqzjmJH.png)

Another example:
```Crystal
puts "\e[48;2;100;50;30mMy background is brown like wood\e[0m"
```
This would colour the background brown:

![My background is brown like wood](https://i.imgur.com/CdRWQIp.png)

We can colour our texts in exactly _16777216_ colors!

Heres a rainbow:
```Crystal
loop do
  print "\r\e[38;2;#{rand(0..255)};#{rand(0..255)};#{rand(0..255)}mI am a rainbow\e[0m"
  sleep 0.1
end
```

![Rainbow](https://media.giphy.com/media/2uw3xo22RlXUoId2ko/giphy.gif)

Right now [Colorize](https://crystal-lang.org/api/0.24.2/Colorize.html) doesn't supports any other colors than these:
```
black
red
green
yellow
blue
magenta
cyan
light_gray
dark_gray
light_red
light_green
light_yellow
light_blue
light_magenta
light_cyan
white
```
Having _16777200_ more colors than this would be a good feature I think.

**Comment by MakeNowJust** [comment]
#3925 implements true color for `Colorize` also.

**Comment by r00ster91** [comment]
But this PR doesnt seems to be really active anymore. Are you still working on it?

**Comment by MakeNowJust** [comment]
Yes if @asterite rethink. I actually love #3925.
