### ISSUE TITLE
Defining instance variables shouldn't be required in an abstract class

### ISSUE THREAD

**Issue by obskyr** [crystal-lang/crystal#5924]
Consider a case where you're defining an `abstract` base class with instance variables you want all subclasses to initialize in different ways. You might consider doing something like this:

```crystal
abstract class Base
  @x : Int32
  @y : Int32

  def print_x
    puts @x
  end
end

class Thing < Base
  @x = 123

  def initialize(@y : Int32)
  end
end
```

Sadly, this doesn't work - instead you get the following error:

```
Error in line 2: instance variable '@x' of Base was not initialized directly in all of 
the 'initialize' methods, rendering it nilable. Indirect initialization is not supported.
```

What you currently have to do is instead something like this:

```crystal
abstract class Base
  @x : Int32
  @y : Int32

  def initialize
    @x = 0
    @y = 0
    # Or similar - NotImplementedError isn't in 0.24.2, of course
    raise NotImplementedError.new
  end

  def print_x
    puts @x
  end
end

class Thing < Base
  @x = 123

  def initialize(@y : Int32)
  end
end
```

Having to add boilerplate like that is undesirable, of course - especially seeing as an `abstract` class can't be initialized anyway, so `@x` and `@y` won't actually be nilable. Instead, the onus of initializing `Base`'s unassigned instance variables should here be shifted to `Thing` and any other classes subclasses `Base` might have.

**Comment by straight-shoota** [comment]
Duplicate of #2827

**Comment by obskyr** [comment]
Thanks!
