### ISSUE TITLE
segfault when using one parameter as default from another one in initialize

### ISSUE THREAD

**Issue by johndescs** [crystal-lang/crystal#5926]
Hi,

It seems to segfault when referencing another parameter as default from one parameter in the initialize method.
This is kind of strange usage, I agree, but I think it should either not compile or work, but runtime segmentation fault is ugly.

```
class Foo
  def initialize(@name : String, @id : String = @name)
  end
end

p Foo.new name: "hello"
```

leads to

```
$ crystal run test.cr 
Invalid memory access (signal 11) at address 0x4
[0x559470c77b76] *CallStack::print_backtrace:Int32 +118
[…]
```

Crystal 0.24.2 [4f9ed8d03] (2018-03-08)
LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
Linux Debian Stretch, Arch, online playground.

**Comment by asterite** [comment]
Duplicate (or similar, same cause) of https://github.com/crystal-lang/crystal/issues/3413
