### ISSUE TITLE
Improve interface of Tempfile methods

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#5938]
`Tempfile` has two different methods for generating a temporary file/path which work differently:

* `Tempfile.new` (and `.open`) uses a platform-specific implementation (based on `LibC.mkstemps`) to create a temporary file.
* `Tempfile.tempname` is implemented entirely in Crystal and basically just builds a path from a randomized string. It does not actually create a file. That's useful if your code does not interact with the file as `IO`, and especially for creating temporary directories.

`.new` and `.open` take arguments `name`/`filename` and `extension` while `.tempname` only accepts `extension`. It would make sense if all methods had the same arguments (apart from other, purpose-specific methods such as `encoding`). And I think `.tempname` should also have a parameter for specifying a prefix to the path as it is equally purposeful for use cases where a file is not directly created.

`extension` (in all cases) is essentially a suffix, `name` and `filename` a prefix. All of them could even contain additional path components. As such, the names might be misleading. But I like `extension` because that's the most probable use case for it anyway.

`name` could perhaps be renamed to `prefix`... but then you might assume `suffix` as well? But it's still better than `name` IMO.
I don't think it should be a required argument (as with `new` and `open` currently). You might just need a temporary file/path and don't care about anything in the name. I see no need to enforce a prefix.

As for the argument ordering, I propose to stick to the natural sequence `prefix, suffix` and make both optional in all methods. That would lead to the following signatures:

* `Tempfile.new(prefix = nil, extension = nil, encoding = nil, invalid = nil)`
* `Tempfile.open(prefix = nil, extension = nil)` (shouldn't this have encoding and invalid as well?)
* `Tempfile.tempname(prefix = nil, extension = nil)`

This also affects #5937 and #4096

**Comment by asterite** [comment]
Probably can be closed if we go with #5939

**Comment by straight-shoota** [comment]
Both issues are related but discuss individual topics. This could still affect the implementation of #5939, even if the methods will have a different scope then. At least I'd prefer to change everything in one go. 

So it would be great to get some feedback on this issue here! 👍

**Comment by straight-shoota** [comment]
Fixed by #6485
