### ISSUE TITLE
Release schedule/roadmap

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#5942]
Last full release (v0.24.1) was [published](https://github.com/crystal-lang/crystal/releases/tag/v0.24.1) on _Dec 23, 2017_, that is 4 months ago.

There are tons of new features added since, and without ability to test things with crystal nightly (refs #5836), many shards are left without proper support from upstream.

Having a release schedule/roadmap would at least give some estimate on when to expect upcoming changes...

**Comment by RX14** [comment]
I'm sure we'll have a release schedule for 1.0, but before that i'm not so sure. I think a goal of "about 3 months unless we want to wait for xyz feature" is a good idea though.

**Comment by asterite** [comment]
Everyone wants a release schedule/roadmap, for a long time now, but opening an issue asking it won't make it happen. I don't think anyone has time right now to work on this, so releases will have to happen "when someone has the time to do it", as it has always been.
