### ISSUE TITLE
Macros: ending comma incorrectly required in multi-line arguments

### ISSUE THREAD

**Issue by j8r** [crystal-lang/crystal#5966]
This following code fails without a comma after `a = 0`.
When we add the missing comma, running the formatter `crystal tool format` removes it (tested in master):

```crystal
macro test(
  a = 0
)
end
```
`Syntax error in test.cr:2: unexpected token: NEWLINE (expected ',' or ')')`

No problems when not setting defaut values for arguments, or all arguments is in one line.

There are two options:
1. keep a similar behavior as `def` - make `macro` works without an ending comma.
2. enforce an ending comma

**Comment by Sija** [comment]
IMO only option no. 1 seems legit.
