### ISSUE TITLE
Macro interpreter coerces to Int32 in arithmetic operations

### ISSUE THREAD

**Issue by joatca** [crystal-lang/crystal#5971]
In the following code which attempts to do 64-bit unsigned arithmetic in a macro, values get coerced to Int32 resulting in:

in bug.cr:7: Invalid Int32: 4294967299

    macro add
      {% x = 4294967297_u64 %}
      puts "{{ x }}: {{ x.kind }}"
      {% y = x + 2_u64 %}
      puts "{{ y }}: {{ y.kind }}"
      {% z = y + 2_u64 %}
     puts "{{ z }}: {{ z.kind }}"
    end
    
    add

Version:
Crystal 0.24.2 (2018-03-19)

LLVM: 6.0.0
Default target: x86_64-pc-linux-gnu

**Comment by straight-shoota** [comment]
Reduced example:

```crystal
{{ (1_u64 + 2_u64).kind }} # => :i32
```

The reason for this is that `NumberLiteral#kind` is `:int32` by default and not appropriately set in the macro operation.
