### ISSUE TITLE
FileUtils.cp_r possible bug when dest_path exists

### ISSUE THREAD

**Issue by tghaleb** [crystal-lang/crystal#5983]
FileUtils.cp_r fails with,
 `Unable to create directory '.': File exists (Errno)`  
when dest_path exists. By looking at the code in *file_utils.cr*, I think what is needed is a test before attempting to create dest_path

```crystal
 Dir.mkdir(dest_path) unless Dir.exists?(dest_path)
```

instead of,

```crystal
 Dir.mkdir(dest_path)
```

Crystal 0.24.2 [4f9ed8d03] (2018-03-08)

**Comment by straight-shoota** [comment]
Resolved by #9175
