### ISSUE TITLE
previous_def doesn't account for default argument values

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#5984]
I'd assume that below code would compile **and** use default value of `location = Location.local`:

```cr
struct Time
  def self.now
    previous_def
  end
end

Time.now
```

Instead it gives (weird btw) compiler error:

```
Error in bug.cr:7: instantiating 'Time:Class#now()'

Time.now
     ^~~

in bug.cr:3: instantiating 'previous_def()'

    previous_def
    ^~~~~~~~~~~~

in .../crystal/src/time.cr:325: wrong number of arguments for 'Time.now' (given 1, expected 0)
Overloads are:
 - Time.now()

  def self.now(location = Location.local) : Time
  ^
```

**Comment by straight-shoota** [comment]
In case somebody is wondering: This has nothing to do with `Time`. It's also the same behaviour with instance methods:

```cr
class Foo
  def foo(foo = nil)
  end
  def foo
    previous_def
  end
end
Foo.new.foo
```

**Comment by Sija** [comment]
@asterite 🏓

**Comment by asterite** [comment]
@Sija No idea why it happens, I started debugging it but got bored, I don't have time. Someone else will have to fix this.

**Comment by Sija** [comment]
@asterite Could you point at least to place(s) in code where to look for potential cause?

**Comment by asterite** [comment]
semantic/call and method_lookup

**Comment by asterite** [comment]
Oh, actually, this is not a bug. previous_def knows the previous def if it's an exact overload. If you use the same signature, it works.

**Comment by Sija** [comment]
@RX14 why did you close it?
