### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/bdw-gc/lib/libgc.2.dylib when launching binary

### ISSUE THREAD

**Issue by Qwerp-Derp** [crystal-lang/crystal#5985]
I installed the newest version of `crystal`, `0.24.2_2`, via Homebrew on Mac OS X High Sierra. This bug will trigger with any binary program as soon as you launch the program:

Program:

```
puts 1
```

Terminal commands:

```
crystal build program.cr
./program
```

Error:

```
dyld: Library not loaded: /usr/local/opt/bdw-gc/lib/libgc.2.dylib
  Referenced from: {location of file}/./program
  Reason: image not found
Abort trap: 6
```

The problem is that the `dylib` file is called `libgc.1.dylib` instead of `libgc.2.dylib`, but I'm not sure how to fix that, and simply renaming the dylib file doesn't seem like a good option.

**Comment by Qwerp-Derp** [comment]
@Sija The solution you gave works, but I think I should still keep the issue open so that a more permanent solution arises.

**Comment by RX14** [comment]
have you made an issue for the homebrew guys? It seems like a packaging issue to me.

**Comment by kirbyfan64** [comment]
Did you intend to close this yet?
