### ISSUE TITLE
Cannot deserialize generic Arrays with JSON/YAML

### ISSUE THREAD

**Issue by colonlc** [crystal-lang/crystal#5986]
Crystal 0.24.2 (2018-03-19)

LLVM: 6.0.0
Default target: x86_64-pc-linux-gnu

It is not possible to deserialize a generic type with the stdlib JSON/YAML mappings.
This is due to missing type information/labeling in the serialized form. If I try to deserialize a class with a generic array property for instance, this happens:

(similar error with yaml instead of json)
[Playground](https://play.crystal-lang.org/#/r/3x48)
```crystal
require "json"
class A
  def initialize(@arr : Array(B)); end
  JSON.mapping({arr: Array(B)})
end

abstract class B; end

class C < B
  def initialize(@x : Int32); end
  JSON.mapping({x: Int32})
end

class D < B
  def initialize(@x : String); end
  JSON.mapping({x: String})
end

a = A.new([C.new(2), D.new("foo")])
puts A.from_json(a.to_json).to_json
```
Error:
```
Error in line 21: instantiating 'A:Class#from_json(String)'

in /usr/lib/crystal/json/from_json.cr:13: instantiating 'new(JSON::PullParser)'

  new parser
  ^~~

in line 4: expanding macro

in macro 'mapping' /usr/lib/crystal/json/mapping.cr:63, line 45:

   1.     
   2.       
   3.     
   4. 
   5.     
   6.       @arr : Array(B) 
   7. 
   8.       
   9.         def arr=(_arr : Array(B) )
  10.           @arr = _arr
  11.         end
  12.       
  13. 
  14.       
  15.         def arr
  16.           @arr
  17.         end
  18.       
  19. 
  20.       
  21.     
  22. 
  23.     def initialize(__temp_23 : ::JSON::PullParser)
  24.       
  25.         __temp_24 = nil
  26.         __temp_25 = false
  27.       
  28. 
  29.       __temp_26 = __temp_23.location
  30.       __temp_23.read_begin_object
  31.       while __temp_23.kind != :end_object
  32.         __temp_27 = __temp_23.location
  33.         key = __temp_23.read_object_key
  34.         case key
  35.         
  36.           when "arr"
  37.             __temp_25 = true
  38. 
  39.             __temp_24 =
  40.               
  41. 
  42.               
  43. 
  44.               
> 45.                 Array(B).new(__temp_23)
  46.               
  47. 
  48.               
  49. 
  50.             
  51. 
  52.         
  53.         else
  54.           
  55.             __temp_23.skip
  56.           
  57.         end
  58.       end
  59.       __temp_23.read_next
  60. 
  61.       
  62.         
  63.           if __temp_24.nil? && !__temp_25 && !::Union(Array(B)).nilable?
  64.             raise ::JSON::ParseException.new("Missing json attribute: arr", *__temp_26)
  65.           end
  66.         
  67.       
  68. 
  69.       
  70.         
  71.           @arr = (__temp_24).as(Array(B))
  72.         
  73.       
  74. 
  75.       
  76.         
  77.       
  78.     end
  79. 
  80.     def to_json(json : ::JSON::Builder)
  81.       json.object do
  82.         
  83.           _arr = @arr
  84. 
  85.           
  86.             unless _arr.nil?
  87.           
  88. 
  89.             json.field("arr") do
  90.               
  91. 
  92.               
  93.                 _arr.to_json(json)
  94.               
  95. 
  96.               
  97.             end
  98. 
  99.           
 100.             end
 101.           
 102.         
 103.       end
 104.     end
 105.   

instantiating 'Array(B):Class#new(JSON::PullParser)'
in /usr/lib/crystal/json/from_json.cr:103: instantiating 'new(JSON::PullParser)'

  new(pull) do |element|
  ^~~

in /usr/lib/crystal/json/from_json.cr:110: instantiating 'JSON::PullParser#read_array()'

  pull.read_array do
       ^~~~~~~~~~

in /usr/lib/crystal/json/from_json.cr:110: instantiating 'JSON::PullParser#read_array()'

  pull.read_array do
       ^~~~~~~~~~

in /usr/lib/crystal/json/from_json.cr:111: wrong number of arguments for 'B.new' (given 1, expected 0)
Overloads are:
 - Reference.new()

    yield T.new(pull)
            ^~~
```

I consider this behaviour wrong. It tries to instantiate B, which is not even possible due to its abstractness even though it should instantiate a C and a D from the serialized data.
This could only be worked around with a custom written deserialization method which then checks the properties and according to that chooses the correct subclasses to be instantiated.

My suggestion: Include type information in JSON/YAML mappings!

**Comment by kostya** [comment]
this would not work like this: may be you should try union type:
https://play.crystal-lang.org/#/r/3x5c

**Comment by straight-shoota** [comment]
Adding type information could maybe help in this case, but it's no general solution because JSON and YAML mappings because they're supposed to be independent of the producer/consumer language. JSON code produced by `JSON.mapping` should also be usable by a JSON parser in Python for example (and the other way around).

This issue is not about `JSON.mapping` in particular but rather the deserialization method `Array(T).new(PullParser)`. It expects `T.new(PullParser)` to be defiined. If `T` is a module or abstract class, this constructor might only exist in subclasses. In that case it would be reasonable to try to call `.new` on the union of all subtypes of `T`. However, this can't be done always because `T` might actually define `.new(PullParser)` with some custom parsing logic for it's subtypes.

A workaround for your issue is to just manually define `B.new(PullParser)`:
```cr
abstract class B
  def self.new(pull : JSON::PullParser)
    string = pull.read_raw
    begin
      return C.from_json(string)
    rescue JSON::ParseException
    end
    
    D.from_json(string)
  end
end
```

(This is essentially the same implementation as `Union(C, D).new(PullParser)` which doesn't work unfortunately, because the compiler combines the union of `C` and `D` as `B` which leads us nowhere.)

A more general solution would be to determine if there could be a default implementation of `.new(PullParser)` for non-instantiable types.

**Comment by colonlc** [comment]
@straight-shoota Your workaround works in the case one knows all types that should be deserialized. But in a library one cannot know what subtypes the users may create. So one would need a more universal approach.

**Comment by colonlc** [comment]
@kostya This does not solve my problem as I need to be able to deserialize arbitrary complex subtypes made by users of my library.

**Comment by straight-shoota** [comment]
To make this universal, you can easily loop through `@type.subclasses` in a macro:
```cr
abstract class B
  def self.new(pull : JSON::PullParser)
    location = pull.location
    string = pull.read_raw
    
    {% for klass in @type.subclasses %}
    begin
      return {{ klass }}.from_json(string)
    rescue JSON::ParseException
    end
    {% end %}
    
    raise JSON::ParseException.new("Couldn't parse #{self} from #{string}", *location)
  end
end
```

**Comment by colonlc** [comment]
Ok, but what if two classes have the same mapping but differ in implementation? Then one could not create the same object as before through serialization and then deserialization.

**Comment by RX14** [comment]
> Ok, but what if two classes have the same mapping but differ in implementation? Then one could not create the same object as before through serialization and then deserialization.

Exactly, which is why *you* have to include the type information when serializing. The standard library will not and should not do that for you because json does not have a standard way of specifying type information.
