### ISSUE TITLE
Abstract methods with &block can not be implemented

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#5989]
```crystal
abstract class Foo
  abstract def wrap(foo, &block)
end

class Bar < Foo
  def wrap(foo, &block)
    yield foo
  end
end
```

```
Error in test.cr:2: abstract `def Foo#wrap(foo, &block)` must be implemented by Bar

  abstract def wrap(foo, &block)
               ^~~~
```

I'm not sure if that's intended...

**Comment by Sija** [comment]
```cr
abstract class Foo
  abstract def wrap(foo, &block)
end

class Bar < Foo
  def wrap(foo, &block)
    block.call(foo)
  end
end
```

works

**Comment by straight-shoota** [comment]
It's because `Bar#wrap` does not actually catch an untyped `&block` but yields `foo` to a block which therefore needs to accept an argument and has a different signature than the abstract method.

With added explicit type annotations your example code is about equal to:
```cr
abstract class Foo
  abstract def wrap(foo : T, &block : -> _) forall T
end

class Bar < Foo
  def wrap(foo : T, &block : T -> _) forall T
    yield foo
  end
end
```
Do you see the difference?

**Comment by straight-shoota** [comment]
It's not a real expansion but an illustration to show how these block arguments are typed.

Yes, a block argument definition in an abstract def needs to be fully typed.

**Comment by Sija** [comment]
@vladfaust you forgot `forall T`

**Comment by vladfaust** [comment]
@Sija it compiled without `forall T` unless I tried `Bar.new.wrap("baz"){ |foo| puts foo }`, so you're right. Updated my comment. 

Still think "fully typing" thing is not needed here for the sake of simplicity. If contributors think it's okay, then close this issue.
