### ISSUE TITLE
Hardcoded path to libyaml-0.2.dylib in embedded/bin/shards

### ISSUE THREAD

**Issue by nehaljwani** [crystal-lang/crystal#5994]
crystal-0.24.2-1 release binary for macOS has a hardcoded path to libyaml-0.2.dylib:

```
(base) ➜  1524496023 otool -L /private/tmp/scratch.nwani/1524496023/crystal-0.24.2-1/embedded/bin/shards
/private/tmp/scratch.nwani/1524496023/crystal-0.24.2-1/embedded/bin/shards:
	/usr/local/opt/libyaml/lib/libyaml-0.2.dylib (compatibility version 3.0.0, current version 3.5.0)
	/usr/lib/libpcre.0.dylib (compatibility version 1.0.0, current version 1.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
```

To make it work, I had to tweak the binary with install_name_tool

**Comment by asterite** [comment]
Is that with homebrew? If not, can't you use homebrew?

**Comment by RX14** [comment]
looks like a packaging error, was crystal installed using homebrew or by downloading from the website.

**Comment by nehaljwani** [comment]
I do not use homebrew, so I downloaded the release binary.

**Comment by asterite** [comment]
Please use homebrew. I think nobody really tries the raw releases for mac as homebrew is so convenient...

**Comment by imbsky** [comment]
Version managers such as asdf-crystal also have this problem. I think we can get path from `CRYSTAL_LIBRARY_PATH`. Is there a reason not to fix this?

**Comment by RX14** [comment]
@imbsky nobody's had the time to look into it unfortunately :(

**Comment by imbsky** [comment]
Will the Crystal core team fix this?

**Comment by kevinsjoberg** [comment]
This really should be fixed. We can't assume everyone is running Homebrew. I'd be happy to take a look at it as I'm a user of [asdf](https://asdf-vm.com/#/) myself and rely on [asdf-crystal](https://github.com/asdf-community/asdf-crystal) for managing my Crystal versions.

For anyone ending up here. The easiest way of getting past this error (without installing Crystal via Homebrew) right now, is to just install `libyaml` via Homebrew.

```console
$ brew install libyaml
```

That should solve the issue you're seeing.

**Comment by straight-shoota** [comment]
If that helps as a workaround, that's fine. But it would be better not to depend on homebrew for installing dependencies.

Can't we just link libyaml statically like on Linux? (I know it can't be *fully* static because libc, but libyaml can be static)

I don't use macOS, so how does this work with the compiler binary? Does it have dynlib dependencies, too?

**Comment by straight-shoota** [comment]
Yeah, the compiler doesn't use libyaml. But it uses other libraries and those are all statically linked. 
I was confused how the compiler's dependencies managed to link statically. But the answer is actually simple: `libyaml` is the only dependency with a dynamic library in `embedded/lib`. All others are static only.

So the solution is easy: Just don't build a shared library for libyaml.

The binary in this artifact should have libyaml statically linked: https://60379-6887813-gh.circle-artifacts.com/0/build/crystal-ci-darwin-static-dev-1-darwin-x86_64.tar.gz

**Comment by kevinsjoberg** [comment]
@straight-shoota that's great. Thanks for that! 🙂
