### ISSUE TITLE
Catch conditionals that test always-truthy or always-falsey types and constant values, warn about code that can never be executed.

### ISSUE THREAD

**Issue by BrucePerens** [crystal-lang/crystal#6000]
The Crystal compiler doesn't catch conditionals where the type tested is _fully-specified_ and always truthy or always falsey. It also doesn't catch when the constant value is always truthy or falsey. Code that can never be executed is met with silence rather than a warning. Such code is useful in macros and generic classes, but is likely to be an error elsewhere.

Type is always truthy, tested for falsey:
```
if !(s = String.new())
  p "This is impossible"
end
```
Constant value is always falsey, tested for truthy:
```
if false
  p "This is impossible"
end
```

**Comment by BrucePerens** [comment]
I really see it as the sort of type-safety issue that Crystal is advertised
to catch: Types that shouldn't be passed to conditional operators at all,
unless they are in a type union. I suppose that catching it in a linter is
adequate, or I could make a package that overloaded the conditional
operators so that they would report this issue.

**Comment by straight-shoota** [comment]
What is the connection to type safety? The compiler still parses and validates all code, even in dead branches. You don't get any more safe code if the compiler warns/removes them.

**Comment by asterite** [comment]
That will never work. If you have a method that accepts a union as an argument, say int or string, and inside it you have a check "if is an int", but then you pass just an int to the method, the method is instantiated with an int and the comparison is trivially true, but it shouldn't error.

You should focus on improving the standard library, as I think that's the only feasible thing that can be changed from now on.

**Comment by RX14** [comment]
I think this is extremely hard to do technically, as all operators can be overloaded. Added to that, we don't want to have any compiler warnings (code should compile or not).

> You should focus on improving the standard library, as I think that's the only feasible thing that can be changed from now on.

That's not really relevant to this issue...

**Comment by straight-shoota** [comment]
This is similar to #6002 by the way: It would be certainly be quite easy to detect and warn about trivial cases like `if false`. But more complex conditions are quite difficult to impossible to determine. In the end, you can't really catch every dead code. And it doesn't really matter, either.

If you want to detect it, use a style linter or even static analysis. The compiler doesn't need to handle this.

**Comment by jgaskins** [comment]
> I think this is extremely hard to do technically, as all operators can be overloaded.

I was under the impression that, even though we can overload operators, the compiler can determine the possible types of any given expression. If the expression can never be `Nil` or `Boolean`, we know it's definitely truthy, right? And if it can only be `Nil`, we know it's definitely falsy. That second one is probably not a useful case realistically, but `Boolean` is the only ambiguous type here.

> Added to that, we don't want to have any compiler warnings (code should compile or not).

Do you have a link handy that explains the reasoning behind this?

It seems like this is the same class of bugs that static typing is intended to eliminate — specifically, it indicates that there's something I don't understand about my code if I'm checking whether an expression that can never evaluate to falsy evaluates to falsy.

> In the end, you can't really catch every dead code.

It's never about catching all possibilities. As long as it can catch more than zero, it's useful. Feasible? Now that's a different story. :-) Static typing can't catch all problems, for example, but it catches enough to be feasible for some people.

**Comment by asterite** [comment]
Here's an example:

```crystal
def foo(x)
  if x.is_a?(String)
    puts 1
  end

  puts 2
end

foo 1
```

The code above is essentially instantiated like this:

```crystal
def foo(x : Int32)
  if x.is_a?(String)
    puts 1
  end

  puts 2
end
```

But `x.is_a?(String)` can never happen in that scenario... so according to this proposal it should give an error. But it shouldn't!

Maybe we could change the compiler to determine when `x` can only be of one type... but that's a no no, the compiler's code is already too complex.
