### ISSUE TITLE
Formatter incorrectly indents arguments when using a backslash

### ISSUE THREAD

**Issue by paulcsmith** [crystal-lang/crystal#6010]
> Similar to https://github.com/crystal-lang/crystal/issues/3383

```crystal
# Before formatting
User.new \
  name: "Paul",
  age: 28,
  location: "Boston, MA"

# After formatting
User.new \
  name: "Paul",
    age: 28,
    location: "Boston, MA"
```

## Alternative syntaxes work

This is *not* a deal-breaker since other syntaxes can be used and the formatter works fine, but I'd love to use the `\` in cases like this:

```crystal
class User
  def initialize(@name : String, @age : Int32, @location : String)
  end
end

# I think this reads very nicely
User.new \
  name: "Paul",
    age: 28,
    location: "Boston, MA"

# Not a huge fan of these latter syntaxes
User.new(
  name: "Paul",
  age: 28,
  location: "Boston, MA"
)

User.new name: "Paul",
  age: 28,
  location: "Boston, MA"
```

**Comment by ysbaddaden** [comment]
Can't we just drop support for escaping linefeeds?

**Comment by RX14** [comment]
I think we had a discussion about doing that before somewhere... I think we decided that it wasn't as easy as we thought.

**Comment by paulcsmith** [comment]
I believe I linked to it at the top of the issue. I don’t think anyone posted this particular use case but I could be wrong
