### ISSUE TITLE
Unintended nested macro behaviour

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#6016]
Works OK (https://play.crystal-lang.org/#/r/3yfm):

```crystal
FOO = {} of Object => Object

macro foo
  {{yield}}
  debug
end

macro bar(&block)
  {{yield}}
end

macro bar
  {% FOO[:a] = 42 %}
end

macro debug
  {% pp FOO %}
end

foo do
  bar do
    bar
  end
end

# FOO # => {:a => 42} of Object => Object
```

But if switch two `bar` definitions, something strange happens (https://play.crystal-lang.org/#/r/3yfq):

```crystal
FOO = {} of Object => Object

macro foo
  {{yield}}
  debug
end

macro bar
  {% FOO[:a] = 42 %}
end

macro bar(&block)
  {{yield}}
end

macro debug
  {% pp FOO %}
end

foo do
  bar do
    bar
  end
end

# FOO # => {} of Object => Object
```

This made me hysterically laugh after an hour of debugging :grin: 

Could someone please explain why is that happening?

*1.0 is far-far away...*

**Comment by straight-shoota** [comment]
Reduced:
```crystal
macro bar(&block)
  puts "bar with block"
  {{yield}}
end

macro bar
  puts "plain bar"
end

bar do
  puts "bar body"
end
# => plain bar
```

Seems like the second macro definition overwrites the first one.

This works as well:
```cr
macro bar(&block)
  puts "bar with block"
  {{yield}}
end

bar
# => bar with block
```

**Comment by vladfaust** [comment]
Hm. Shouldn't macro overloading be a feature?

**Comment by asterite** [comment]
Macros don't overload based on block.

**Comment by vladfaust** [comment]
Okay, they don't, I get it. I want this structure possible in my web framework with typecasted params:

```crystal
params do
  param :user do
    param :email
    param :password
  end
end
```

**Comment by vladfaust** [comment]
Okay, let's leave overloading. I currently stuck here and it complies with issue name:

```crystal
FOO = {} of Object => Object

macro foo
  {{yield}}

  debug
end

macro nested_bar(&block)
  {% FOO[:a] = 43 %}
  {{yield}}
  {% FOO[:a] = 44 %}
end

macro bar
  {% FOO[:a] = 42 %}
end

macro debug
  {% pp FOO %}
end

foo do
  nested_bar do
    bar
  end
end

# FOO # => {:a => 42} of Object => Object
```
`a` expected to equal `44`. What's wrong here?

**Comment by vladfaust** [comment]
This behavior is unintended as well (`"bar"` supposed to be in the middle). Any help?

```crystal
macro foo
  {{ yield }}
end

macro nested_bar(&block)
  {% puts "nested_bar before" %}
  {{ yield }}
  {% puts "nested_bar after" %}
end

macro bar
  {% puts "bar" %}
end

foo do
  nested_bar do
    bar
  end
end

# "nested_bar before"
# "nested_bar after"
# "bar"
```

**Comment by hugoabonizio** [comment]
@vladfaust

```crystal
macro foo
  {{ yield }}
end

macro bar(&block)
  puts "bar before"
  {{ yield }}
  puts "bar after"
end

macro baz
  puts "baz"
end

foo do
  bar do
    baz
  end
end

# bar before
# baz
# bar after
```

**Comment by asterite** [comment]
if block

**Comment by vladfaust** [comment]
@asterite omg, that is so obvious. You're right, `if block` solves the block issue!

However, the order issue is still actual. Should I create a new issue if that's a bug? @asterite you're *the only one who knows the compiler*, so I hope you can help me with this...

**Comment by straight-shoota** [comment]
@vladfaust Just escape the outer wrapper macros.

```cr
macro bar(&block)
  \{% puts "bar before" %}
  {{ yield }}
  \{% puts "bar after" %}
end
```

Don't need to know the compiler for that :smirk:

**Comment by vladfaust** [comment]
@straight-shoota you're a magician! Thank you :sparkles:
