### ISSUE TITLE
Feature request: ArrayLiteral#pop & #shift

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#6023]
`ArrayLiteral#push` works (although not documented), so I suppose it's possible to add `#pop` and `#shift` etc.

*Upd*
Nice place to start: https://github.com/crystal-lang/crystal/pull/5265

**Comment by benglewis** [comment]
I don't quite understand the request, this appears to exist already:
https://crystal-lang.org/api/0.25.1/Array.html#pop-instance-method

**Comment by RX14** [comment]
@benglewis This is about macro array literals https://crystal-lang.org/api/master/Crystal/Macros/ArrayLiteral.html

**Comment by bcardiff** [comment]
Closing as for https://github.com/crystal-lang/crystal/pull/7109#issuecomment-441625418
