### ISSUE TITLE
Indexable mixin in String class

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#6025]
Is there a reason why https://crystal-lang.org/api/0.24.2/Indexable.html isn't included in String.cr?

It seems that all of those methods could be used on a string, since a string could be thought of an array of characters.

if `"foo"[0]` works why shouldn't `"foo".first`?

WDYT?

**Comment by asterite** [comment]
Even though indexing a string is possible, if it's not an ASCII string than it's going to be very slow. If you really have to work with a string as an array of chars, just use `string.chars` (and keep that somewhere).
