### ISSUE TITLE
initialize LogHandler(log : Logger)

### ISSUE THREAD

**Issue by baelter** [crystal-lang/crystal#6059]
Nice to have feature. I can submit. What do you think?

**Comment by straight-shoota** [comment]
There is currently a discussion about changes to the logging system in #5874. I'd suggest to wait for what comes out of there before making changes to that component.

**Comment by microlith57** [comment]
I have made a workaround for this for the time being [(gist)](https://gist.github.com/microlith57/9bd0981b6df37fa18f79b3631afadb34).
