### ISSUE TITLE
Pointer(Void).new(-1) points to address 18446744073709551615

### ISSUE THREAD

**Issue by petoem** [crystal-lang/crystal#6065]
While working on my overflow [shard](https://github.com/petoem/overflow), I discovered that the stdlib uses `Pointer(Void).new(-1)`. 
See petoem/overflow#1 
e.g. https://github.com/crystal-lang/crystal/blob/5e518f97349fe0cc3fba6455b5173cb02900b287/src/lib_c/x86_64-linux-gnu/c/sys/mman.cr#L13

https://github.com/crystal-lang/crystal/blob/5e518f97349fe0cc3fba6455b5173cb02900b287/src/pointer.cr#L411-L413
`#to_u64` causes an overflow and the pointer will point to address `0xffffffffffffffff` not `-1`.

**Comment by RX14** [comment]
Yes, this is expected behaviour.

**Comment by RX14** [comment]
Redefining overflow to raise in a shard will be incompatible with many shards, and definitely the stdlib for now.

If we want overflow to raise thats a decision we need to make as a language, not in a shard.

**Comment by petoem** [comment]
Ok, `-1` and the `#to_u64` confused me for a moment. 

My initial idea was to implement a `checked {}` block.
Global raise on overflow worked when I only had `Int32` implemented at first, but after `UInt` it stopped working (it did always raise because of the stdlib code). 
I will go back to my initial idea, this way it won't conflict with most parts of the stdlib and it might be useful for other people. If not it will remain as an experiment.
