### ISSUE TITLE
Avoid ivars to be read on objects without getter

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang/crystal#6066]
Hi!

Crystal allows access to instances variables using `instance.@var`? Shouldn't this be avoided?

I think a `getter` should be required to do that

```crystal
class Foo
  @foo = 1
end

f = Foo.new
puts f.@foo # => 1
```

https://carc.in/#/r/40an Why?

**Comment by RX14** [comment]
It's actually neccesary for some parts of the stdlib, and I find it useful for debugging.

Keep quiet about it though, it's meant to be a secret.

**Comment by asterite** [comment]
Struct equalty

**Comment by jhass** [comment]
Kinda destroys the debugging use case, but I guess a sane semantic for this would be to restrict it to methods of the same type, that is inside and only inside `Foo` one can do `other.@bar` if `other` is a `Foo` too. Subclasses should probably be able to access parents this way but not the other way around.

**Comment by oprypin** [comment]
Could be an interesting project for someone trying to learn the compiler

**Comment by straight-shoota** [comment]
For reference, this has come up on SA: https://stackoverflow.com/questions/51225175/direct-reading-of-an-instance-variable/51232121

It seems to be confusing. Let's remove/reduce this "feature" as @jhass suggested :+1:

**Comment by asterite** [comment]
Sure. Please send a PR, it might not be difficult to implement. Maybe the compiler or std is using it for something, like taking a pointer to an instance variable, but I think it can be workarounded.

**Comment by RX14** [comment]
Let's just remove it and implement struct equality via `protected def %macro_var_name` accessors or similar.

**Comment by asterite** [comment]
No...

**Comment by asterite** [comment]
Or, well, if you think it's possible, go ahead

**Comment by ysbaddaden** [comment]
AFAIK it's required in [`Fiber#resume`](https://github.com/crystal-lang/crystal/blob/master/src/fiber.cr#L262) where we take a `void**` pointer of `fiber.@stack_top` so the ASM can change the `void*` pointer in place (thus at the ivar location). Using a getter would return a local var and the ASM would change that local var, not the ivar, and we can't update the ivar from the local var *after* the ASM call, because the ASM switched the execution context... :bomb: 

The feature could be limited to `protected` visibility, thought, but removing could prove tedious —if not impossible.

**Comment by straight-shoota** [comment]
Making ivars `protected` is totally fine 👍

**Comment by asterite** [comment]
It can be done with a method that returns the pointer:

```crystal
def stack_top_pointer
  pointerof(@stack_top)
end
```

Of course, you'd have to create a method each time you need something like this.

Then the only other missing thing is struct equality. But maybe we can remove that and require users to override == (it's a bit strange because a struct won't be equal to itself by default because structs don't have an address, unlike classes).

So the other option is to restrict reading ivars to the same type as the current type, or, well, the same rules that apply to protected.

**Comment by RX14** [comment]
no, you're right @asterite. You're talking a pointer of something that's on the heap and returning it. That's totally legal.

**Comment by asterite** [comment]
@RX14 Ah, yes, my bad.

In any case... https://github.com/crystal-lang/crystal/pull/6358 :-P

**Comment by oprypin** [comment]
#6358 describes that accessing instance variables should work almost like `protected`.

But then, why not just replace all accessed ivars with protected properties?

**Comment by asterite** [comment]
@oprypin How do you implement [this](https://github.com/crystal-lang/crystal/blob/master/src/struct.cr#L66-L76)?

**Comment by asterite** [comment]
Removing this feature will only mean people writing boring protected methods to access them, and a less powerful struct equality.

**Comment by bcardiff** [comment]
Given that classes and struct are not sealed, they can always be reopened and ivars values extracted (or changed). So there is no real way to avoid someone accessing the ivars.

I fail to see real value gained from not allowing the syntax. It did also disturb me in the beginning, but keeping them does not make any harm AFAIK. Even for tooling/analysis, it could be detectable which ivars for which types are been directly accessed with this syntax.

**Comment by RX14** [comment]
@asterite it's far easier to grep for your class being reopened than an access to an ivar.

**Comment by j8r** [comment]
A syntax could indiquate if the instance variable is public or protected, like methods and classes, but here the default would be private.

I think they are quite similar on this issue – private classes and methods can also be accessed from the outside via public/protected methods, like instance variables.

This will also add documentation about the scope of the instance variable; where it may be used.

**Comment by RX14** [comment]
I really really don't want to go the route of java and C++ of having "properties" and "methods". The very core of ruby's OO is that everything is just messages between objects, including getting and setting "properties". I don't want to legitimize this syntax my making it easy or safe to use, because then people *will* use it. And people should absolutely not be using it because it flies against the core ideas of encapsulation in OO.

**Comment by straight-shoota** [comment]
@RX14 Encapsulation is great, but IMHO it doesn't need to be over strictly enforced. I tend to agree with @bcardiff here.

In some cases you need to access an ivar from outside the type. There are ways to achieve this differently, but looking at the diff of #6358 I fail to see the benefit of adding extra methods to directly access the ivars. It's just clutter. If we keep everything as it is, the code is easier to read and understand.

I suppose it really doesn't hurt to have ivars accessible from anywhere. As long as we make sure to properly document this feature, I'd say it's fine to leave it as is. It can be a useful tool to interact with the internals of an object only for specific use-cases such as testing internals, but it is not recommended for anything else and should generally be avoided.

**Comment by j8r** [comment]
For me accessing ivars from everywhere is the same story as accessing classes and methods from everywhere - what's the purpose of private and protected in the first place thus?

Having to access an ivar from the outside is not common - it could be good to have something that indiquates this particularity and explaining why it's needed.

**Comment by ysbaddaden** [comment]
> I suppose it really doesn't hurt to have ivars accessible from anywhere

I agree. It goes into the 'sharp knife' features IMHO. It should be considered a smell. Yet, sometimes useful in obscure scenarios (or debug), as demonstrated in stdlib.

Note that this is ever a getter, you can't change the ivar with `foo.@var = value` (compile error). So it's even less harmful than reopening a class with a method that could *change* the ivar.

**Comment by RX14** [comment]
If adding extra methods to access ivars is just clutter, then let's remove `property` and `getter` and use `foo.@ivar` everywhere.

**Comment by asterite** [comment]
lol

Let's remove `pointerof` too, it's way too dangerous. If people want to do it, they can use inline assembly for that.

By the way, if you have a chain of structs, you can get a pointer to any instance variable in the chain with `pointerof(foo.@bar.@baz)`. There's no way to do that if we remove that feature. And given that you should be able to do low-level stuff in Crystal, I'd say the feature should stay.

**Comment by wontruefree** [comment]
I didn't know this was something you could do.  I had some code that was opening up classes to make methods to expose ivars for metrics gathering.  After learning about this I am starting to use it and like it a lot more then what I was doing.  I know it is a sharp tool but I like it and would not mind leaving it in.
