### ISSUE TITLE
Confusing errors when calling a method in the wrong way with `with`

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#6080]
When i'm for example doing this:
```Crystal
module MyModule
  def self.hi(arg)
    puts arg
  end
end
def method
  with MyModule yield
end
method do
  hi
end
```
then i'm getting this error:
```
Error in line 11: instantiating 'method()'

in line 11: instantiating 'method()'

in line 12: undefined local variable or method 'hi'
```
But now when i'm **not** forgetting the argument at the `hi` method then it works:
```
hello
```

So I think this error when you are forgetting an argument at a method called with `with` should be rather:
```
Error in line 10: wrong number of arguments for 'MyModule.hi' (given 0, expected 1)
Overloads are:
 - MyModule.hi(arg)
```

I'm also getting this confusing error when i'm for example passing the wrong type:
```Crystal
module MyModule
  def self.hi(arg : String)
    puts arg
  end
end
def method
  with MyModule yield
end
method do
  hi 12
end
```
```
Error in line 9: instantiating 'method()'

in line 9: instantiating 'method()'

in line 10: undefined method 'hi'
```
The method is definitely defined there so it doesn't makes sense.

**Comment by r00ster91** [comment]
Here: https://crystal-lang.org/docs/syntax_and_semantics/blocks_and_procs.html#with--yield.
It's good for when you for example make a library and have a long library name. Then it's maybe annoying for the user to type `TheLongLibraryName.` before every single method call again.
So you can just do this:
```Crystal
module TheLongLibraryName
  extend self
  def hi
    puts "hi"
  end
  def hello
    print "hello"
  end
  def run
    with TheLongLibraryName yield
  end
end

TheLongLibraryName.run do # And here in this block you don't need the prefix then.
  hi
  hi
  hello
end
```
When you by "drop it" mean removing it then please don't. It's really a nice feature which is surely sometimes useful. And I will use it now in my library. And i'm sure it also have other usecases.

**Comment by asterite** [comment]
Yeah, we should remove this feature already. You can achieve the same by passing a block argument and using that argument.

**Comment by RX14** [comment]
Eh, I like `with`. It's a small thing but it makes a big difference for DSLs.

**Comment by r00ster91** [comment]
Oh noo please don't remove it :(

I find it really innovative and it's definitely nice for DSLs. And if you pass a block argument then the user who is using the library has to think about even more names for some things. I think you are already spending enough time on naming things.

**Comment by MakeNowJust** [comment]
`with` is too buggy but it is not so wrong part of language. For example Kotlin's extension function behaves like `with`, however the big different between extension function and `with` is the receiver of extension function is typed, but `with` is not. It seems good if Crystal gets such a feature.

**Comment by RX14** [comment]
> the receiver of extension function is typed, but with is not

can you explain a little more about what that means?

**Comment by RX14** [comment]
Ah yes, I understand now. Since we type blocks using proc syntax, should procs gain `with` functionality?

**Comment by asterite** [comment]
We should simply fix `with ... yield` to only be able to receive a single type, never a union. I think this will fix the issue.

Are there any other issues with this?

**Comment by MakeNowJust** [comment]
Repeat my comment:

> I think this code shouldn't be compiled **in most of the time**

Sorry it is my mistake. I think we cannot decide this example should or shouldn't be compiled entirely.

@asterite 

> We should simply fix with ... yield to only be able to receive a single type, never a union. I think this will fix the issue.

Why disallow all union as receiver? Do you think this code shouldn't be compiled?

```crystal
def each_with(ary : Array)
  ary.each do |item|
    with item yield
  end
end

each_with([42, "foo"]) do
  p itself
end
```

**Comment by asterite** [comment]
Actually, I'm not sure. I don't know what's the use case, though. What's a use case other than `itself`? Can you show a real example you would write?

**Comment by asterite** [comment]
I now think it can be implemented. The current implementation is not very good, but it should be relatively easy to fix. I'll try to do that later.

**Comment by asterite** [comment]
What should happen in this case?

```crystal
struct Int32
  def foo
    10
  end
end

def foo
  20
end

def bar
  with 1 yield
  with 'a' yield
end

bar do
  p foo
end
```

My point is, `with ... yield` is very confusing. It's not obvious what a method resolves to just by looking at the code. You must check to see if that method is in the `with` scope or in the outer scope. With a union it gets more complex. Do some part of the union resolves to a place and some part to another? I'd say it's an error if the whole union doesn't resolve in this case to the "same" method (all in the union, or all outside it).

But this is just a small syntax sugar. What's so bad about explicitly passing a block argument?

I don't dislike the feature because it's hard to implement. I dislike it because it's confusing to understand code that uses it.

**Comment by RX14** [comment]
@asterite the thing is that the point of DSLs is to create an entirely new language with it's own rules for understanding it. So you're right, it's hard to understand that crystal code. But if you place the usage of `with` in the larger context of a DSL, is it hard to understand any more? Well that's up to the DSL writer.

In this case, I think we should provide the tools and not worry too much about if it's understandable. I haven't seen anybody using `with` when they're not writing DSLs so I think it's fine.

**Comment by jhass** [comment]
This gives the proper error messages now:

```
error in line 10
Error: wrong number of arguments for 'hi' (given 0, expected 1)

Overloads are:
 - MyModule.hi(arg)
```
and 
```
error in line 10
Error: no overload matches 'hi' with type Int32

Overloads are:
 - MyModule.hi(arg : String)
```
respectively.
