### ISSUE TITLE
New Feature: Allow passing TypeDeclarations to regular methods at runtime

### ISSUE THREAD

**Issue by paulcsmith** [crystal-lang/crystal#6081]
Right now you can pass TypeDeclarations to macros:

https://play.crystal-lang.org/#/r/41a7
```crystal
macro what_am_i?(declaration)
  {{ p declaration.type }}
end

what_am_i? thing : String # Prints: String
```

It would be wonderful to also be able to use a `TypeDeclaration` class at *runtime*:

```crystal
def what_am_i?(declaration)
  p declaration.type
end

what_am_i? thing : String # Prints: String
```

## Example use case:

https://luckyframework.org/guides/database-migrations/#creating-and-altering-tables
```crystal
# created_at, updated_at, and id are added automatically
create :users do
  add name : String # will set the column to NULL FALSE
  add age : Int32? # will allow NULL values because of the nilable type
end
```

Right now I have to make `add` a macro even though it could easily be done as a method if it were possible to pass a type declaration around at runtime. I imagine it would be a simple struct with the exact same methods as the TypeDeclaration(T) available at compile-time (where T is the type, makes it so you can only allow TypeDeclarations of a certain type, used in this case so that only types that are allowed in the database can be passed to the method)

```crystal
def add(declaration : TypeDeclaration(String))
  # add string column using declaration.type, declaration.var and declaration.default
end
```

I admit I do not know how this is implemented so maybe this is extremely difficult, but my hope is that it is not. I think this will open up APIs that feel wonderful because you're using familiar syntax instead of something like: `add :age, Int32?, default = 1`

**Comment by paulcsmith** [comment]
I didn't know you could do that and I still don't understand it. Could you provide an example?

**Comment by paulcsmith** [comment]
And one important reason is that macros tend to have awful error messages. I like to avoid them when possible, but maybe what you suggest will not suffer from that same flaw

**Comment by straight-shoota** [comment]
```cr
macro add(typedec)
  add {{ typedec.var.symbolize }}, {{ typedec.type }}, {% if typedec.value %} default: {{ typedec.value }}{% end %}
end
```
[carc.in](https://carc.in/#/r/41bg)

**Comment by RX14** [comment]
```cr
macro add(declaration)
  add_impl({{declaration.var.stringify}}, {{declaration.value}}, {{declaration.type}})
end
```

then define `add_impl(var : String, value, type)`. You can even use `forall T` to generify on the type!

**Comment by paulcsmith** [comment]
Oh, I see. So the macro just translates the type declaration into a regular method call. I think that may still result in some harder to trace error messages but aren't nearly as bad as what they look like now with my current implementation!

Thanks for the tips. I'd still prefer having access at runtime, but this gets me pretty close 👍 

Also, what do you mean I can use `forall T` to generify on type? I don't understand `forall T` well enough to understand how that could be used.

**Comment by paulcsmith** [comment]
Ohh, I see. That makes sense. Thanks @RX14
