### ISSUE TITLE
Get an error: "ld: library not found for -lgc"

### ISSUE THREAD

**Issue by lfwelove** [crystal-lang/crystal#6086]
MacOS High Sierra 10.13.4

I tried two ways to install Crystal-lang on Mac
1. $brew install crystal-lang
2. $brew install crystal-lang --with-llvm

my test.cr content:
puts "hello"

type "$ crystal test.cr "
(then get an error)
ld: library not found for -lgc
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc "${@}" -o '/Users/chenxi/.cache/crystal/crystal-run-test.tmp'  -rdynamic  -lpcre -lgc -lpthread /usr/local/Cellar/crystal-lang/0.24.2_1/src/ext/libcrystal.a -levent -liconv -ldl -L/usr/lib -L/usr/local/lib`

**Comment by Elfryskai** [comment]
Try this:

```
$ xcode-select --install  
$ xcode-select --switch /Library/Developer/CommandLineTools
```

**Comment by lfwelove** [comment]
@Elfryskai I have installed Xcode and command line tools, I don't want to try your suggestion. There are important projects in my computer, I don't want to screw Xcode up. It's not cool at all.

Never mind, let me just close this issue.

**Comment by Sija** [comment]
`brew install bdw-gc`?

**Comment by lfwelove** [comment]
@Sija Yup, I installed all dependents, such as:
bdw-gc 
libevent
llvm@5
pcre
gmp
libyaml
openssl

**Comment by Sija** [comment]
@lfwelove hmm, then try running `brew unlink bdw-gc && brew link bdw-gc`

**Comment by lfwelove** [comment]
@Sija well, it works

**Comment by Sija** [comment]
@lfwelove cool, have fun with Crystal then and welcome to the Community :)
