### ISSUE TITLE
tcp stream hiccup when reading data inside a loop

### ISSUE THREAD

**Issue by girng** [crystal-lang/crystal#6090]
### crystal version:
Crystal 0.24.1, LLVM: 4.0.0, Windows 10 WSL
Default target: x86_64-unknown-linux-gnu

hello my friends. i'll try to reduce this as much as possible,  
server.cr: https://paste.ee/p/p1zzs
socket.cr: https://paste.ee/p/fzul4

### How To Replicate
 - run crystal server.cr
 - run crystal socket.cr

## Hiccup In Action
![](https://i.gyazo.com/87bb1f8e3827eace766297714f606a75.gif)

the *right* terminal is the **server.cr**. basically, there is a small "delay" or "hiccup" every other XXms, and i'm not sure what is causing it. if it's too hard to see, you can run the code above in your own terminal. much more clearer.

if i am doing something wrong with my code, i apologise. but i've been using this code for my master game server development for over a month and everything has been working fine until i started to do the tickrate (for the game server). thank you in advance

**Comment by petoem** [comment]
@girng I think it's buffering writes. In socket.cr, after line 16 `socket.send new_message`, try to add `socket.flush`. This will send all buffered writes out immediately.
You should be able to turn off Buffering completely with [`server.sync = true`](https://crystal-lang.org/api/0.24.2/IO/Buffered.html#sync%3D%28sync%29-instance-method).

**Comment by girng** [comment]
@petoem hello there, thank you. just tried that, but the hiccup is still there (saw your post come in right when i was about to reply)

 i did some more testing, for what it's worth:

in socket.cr, use `socket.send new_message + "\n"`
in server.cr's loop, use:  
```
    loop do
        raw_message = socket.read_line
        puts raw_message
    end
```

and hiccup is gone.  i'm trying to reduce, and think its related to `write_bytes`

**Comment by petoem** [comment]
@girng Sadly, I can't test your solution because I don't have hiccups at all. Maybe because of different OS, configuration etc.

What happens if you add `server.sync = true` to both server.cr and socket.cr paste?

**Comment by petoem** [comment]
No hiccups, I don't get `0`'s. btw, OS is Arch Linux. 

@girng Another question, what is in `payload_size` when `difference` is `0`?

**Comment by girng** [comment]
@petoem thx again. i did `puts payload_size if difference == 0`
it shows: `37`

**Comment by girng** [comment]
https://github.com/Microsoft/WSL/issues/3186#issuecomment-388696474

sorry, hiccup doesn't happen if nagle algorithm is disabled. (has to be set on server and client). totally my fault.
