### ISSUE TITLE
Time parse error in master

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#6093]
this works in 0.24.2 and not work in master:
```crystal
p Time.parse("2011-08-15 12:00", "%Y-%m-%d %H:%M")
```

```
Unhandled exception: Time format did not include time zone and no default location provided (Time::Format::Error)
  from src/time/format/parser.cr:362:9 in 'raise'
  from src/time/format/parser.cr:30:9 in 'time'
  from src/time/format.cr:77:5 in 'parse'
  from src/time/format.cr:74:3 in 'parse'
  from src/time.cr:542:5 in 'parse'
  from src/time.cr:541:3 in 'parse'
  from 1.cr:3:3 in '__crystal_main'
  from src/crystal/main.cr:104:5 in 'main_user_code'
  from src/crystal/main.cr:93:7 in 'main'
  from src/crystal/main.cr:133:3 in 'main'
```

**Comment by kostya** [comment]
i find that now need to set location:
```
Time.parse("2011-08-15 12:00", "%Y-%m-%d %H:%M", Time::Location.local)
```

why not set it by default?

**Comment by RX14** [comment]
Because the correct default massively depends on usecase.

**Comment by w-A-L-L-e** [comment]
Well the local default seems easier for most cases.
Also doing Time.new just gives local time in this case.
Example how it is now:
```
puts Time.parse("2012-11-01 22:08:12", "%F %T", Time::Location.local)
puts Time.parse("Fri Oct 31 23:00:24 2014", "%c", Time::Location.local)
puts Time.parse("Fri Oct 31 23:00:24 2014", "%c", Time::Location::UTC)
puts Time.parse("20150624", "%Y%m%d", Time::Location.local)
puts Time.new
```

with output:
```
2012-11-01 22:08:12 +01:00
2014-10-31 23:00:24 +01:00
2014-10-31 23:00:24 UTC
2015-06-24 00:00:00 +02:00
2018-08-22 21:00:05 +02:00
```

With the default suggested the code would be:
```
puts Time.parse("2012-11-01 22:08:12", "%F %T")
puts Time.parse("Fri Oct 31 23:00:24 2014", "%c")
puts Time.parse("Fri Oct 31 23:00:24 2014", "%c", Time::Location::UTC)
puts Time.parse("20150624", "%Y%m%d")
puts Time.new
```

So for me also +1 for the defaulting to local time. If you want UTC or something else you can always give it.

**Comment by Sija** [comment]
There's also `Time.parse!` accepting `%z`

**Comment by straight-shoota** [comment]
@w-A-L-L-e Seems you've been looking at outdated docs from 0.20.0 judging by the links you posted. The most recent API documentation is here: https://crystal-lang.org/api/latest/Time.html

There is now `Time#parse_local` which behaves like you described, see #6369 for details on this topic.

**Comment by w-A-L-L-e** [comment]
ah yes parse_local and parse_utc work now... great ;).  anyway it does break some older examples I found around the net, they could have also made parse work like parse_local if you omit the parameter. But I guess crystal is still young enough to do this kind of api changing ;)
