### ISSUE TITLE
Empty multi-line array literal of unspecified type 'Nil assertion failed'

### ISSUE THREAD

**Issue by tomjw64** [crystal-lang/crystal#6102]
✔️ This produces the expected error:
```crystal
[]
```

✔️ This produces no error:
```crystal
[
] of Int32
```

❌ But this produces a less than pleasant error:
```crystal
[
]
```

Error message:
```
Nil assertion failed
??? (x16)
Error: you've found a bug in the Crystal compiler.
```

System info (using WSL):
```
$ crystal -v
Crystal 0.24.2 [4f9ed8d03] (2018-03-08)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by bew** [comment]
Thank you for reporting this, this has been fixed and will be available in next release :smiley:
