### ISSUE TITLE
Formatter bug

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#6114]
Code below:

```cr
return false unless some_very_long_variable_name = %w(foo bar baz).any? do |item|
  item =~ /foo/
end
```

gets wrongly formatted to:

```cr
return false unless some_very_long_variable_name = %w(foo bar baz).any? do |item|
                      item =~ /foo/
                    end
```

**Comment by straight-shoota** [comment]
> The "wrong format" looks better.

I'm not criticizing, but that's a highly opinionated statement 😏 It was decided that the formatter should print it that way because it was considered better readable. Not everyone agrees, obviously.
