### ISSUE TITLE
Top-Level should have a module interface.

### ISSUE THREAD

**Issue by BrucePerens** [crystal-lang/crystal#6115]
Top-level should have a Module interface, with a defined name used to access it, and should respond to the entire Module API and of course `self`, `include` and `extend`. As it is now, top-level is a singularity, with rules that apply only to it. Providing a Module interface to top-level would make it possible for programmers to easily solve some of the nested name-space problems that exist today, by including or extending top-level.

**Comment by asterite** [comment]
You can already include and extend the top level...

**Comment by bew** [comment]
What does that mean to you to include toplevel? 

Can you show some example for your suggestion?

**Comment by BrucePerens** [comment]
Um. I'm afraid I'm still in the hand-waving stage of this idea and maybe I should have thought harder before I initiated the feature request :-) I'm trying to think of how a security model would be implemented around top-level. And what I am getting so far is that you would instantiate a top-level object (rather than module) within another, where the containing object would provide foreign libraries (for system calls, etc.) and intercept calls to load foreign libraries in the contained object.

**Comment by asterite** [comment]
Unless you provide some code, there's not much we can do can do, and we'll close this issue.
