### ISSUE TITLE
.Error report in crystal.

### ISSUE THREAD

**Issue by LWFlouisa** [crystal-lang/crystal#6116]
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/sarah/.cache/crystal/usr-share-crystal-src-ecr-process.cr/macro_run'  -rdynamic  -lpcre -lgc -lpthread /usr/share/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`

I seem to keep getting this error report no matter which program I run.

**Comment by r00ster91** [comment]
Did you installed a C compiler (`cc`) and a linker (`ld`)? And what is your `crystal -v` output?

**Comment by straight-shoota** [comment]
Is this the entire output of the compiler?
You're likely missing a dynamic library and the linker should tell you which.

**Comment by LWFlouisa** [comment]
Would linker be something I'd need to install?

**Comment by straight-shoota** [comment]
No. If you installed crystal using a OS package, the linker should've been installed as a dependency. And since the linker command returns code 1, the executable seems to exist but fails during execution.

In order for us to provide any help, you should answer what we already asked you: Is there any other output when you run the Crystal compiler? What's your crystal version and operating system (inkl. version)?

**Comment by RX14** [comment]
Indeed, we need the full compiler output instead of just one line of the error here.

**Comment by LWFlouisa** [comment]
Since apparently it's not being conveyed here since some cant get the obvious, I thought it was obvious I'm not being told what the compiler issue is.

**Comment by bew** [comment]
It's not a compiler issue, just some missing l8bs on your computer :smiley:

The important errors are here:
```
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lpcre
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lgc
```
You need to install the `pcre` and `gc` libraries

**Comment by Sija** [comment]
> I can assure you, this is all that gets printed out. Now how about answering my question?

> Since apparently it's not being conveyed here since some cant get the obvious, I thought it was obvious I'm not being told what the compiler issue is.

Since we ain't reading tea leaves here, how about chilling out?

**Comment by RX14** [comment]
> Now how about answering my question?

We needed the extra output you gave us to answer your question: you need to install the development packages for libpcre and libgc.
