### ISSUE TITLE
Add end_(line|column)_number to loc pragma

### ISSUE THREAD

**Issue by bew** [crystal-lang/crystal#6126]
Currently the loc pragma allows to set the `filename`, `line_number` and `column_number` of the next token to be read by the lexer.
Its format is: `#<loc:some_filename,line_number,column_number>some_token` surrounded by `#<loc:push>` and `#<loc:pop>`.
So for example: `#<loc:push>#<loc:"/tmp/loc.cr",22,7>SomeConst#<loc:pop>`.

The lack of end numbers makes error reporting only show a `^` under the token, instead of a nice `^~~~~~~~` for the whole token.

My suggestion is to add 2 (optional?) numbers to the loc pragma to also have `end_line_number` and `end_column_number`.

I think this would be useful for #6125.

**Comment by bew** [comment]
Nevermind, when I remove `#<loc:push>` and `#<loc:pop>` it works as I expected..

I don't understand what these are for.. @asterite any hint?

**Comment by Sija** [comment]
> Now I don't understand what these are for.. @asterite any hint?

@bew `git blame` it

**Comment by bew** [comment]
@Sija Good idea, thank you!
For those interested, here is the commit: https://github.com/crystal-lang/crystal/commit/d1bd2a71ab23d1a59a7af4f351aeb0127d86844a (note: `save` & `reset` will later be renamed to `push` & `pop`)
