### ISSUE TITLE
Colorize output not outputting as expected

### ISSUE THREAD

**Issue by naltun** [crystal-lang/crystal#6130]
Here's what I am working with on my system:
```
Crystal Setup:
Crystal 0.24.2 (2018-03-19)

LLVM: 6.0.0
Default target: x86_64-pc-linux-gnu

OS:
Antergos Linux x86_64
```
I am using the Colorize package, and the output is not outputting as expected. Here's my code:

```
require "system"
require "colorize"

# Method chaining for brevity
cpu_count = System.cpu_count.colorize.underline
hostname = System.hostname.colorize.underline

msg = "My CPU count is #{cpu_count} and my system hostname is #{hostname}."
msg = msg.colorize.fore(:black).back(:yellow)

puts msg
```
The output is:
![image](https://user-images.githubusercontent.com/7507990/40561261-92e8c8a6-602a-11e8-8ff1-291ce229ed61.png)

I can even use `crystal eval` with

`crystal eval 'require "colorize"; require "system"; cpu_count=System.cpu_count; host=System.hostname; puts "My CPU count is #{cpu_count.colorize.underline} and my system hostname is #{host.colorize.underline}.".colorize.fore(:black).back(:yellow)'`

and it produces the same output (notice how I change where I use `colorize`, to show it's tested in different circumstances).

I expect the entire output to have a yellow background with black font. I think this is potentially a bug.

**Comment by straight-shoota** [comment]
That's how ANSI sequences codes work. They're just characters in a string and scopes don't stack. If one is closed (in this case the underline), all are closed. Colorize simply translates into ANSI codes.

Maybe it could follow the intent of nesting scopes and insert the start sequence into the string multiple times if it finds a reset code. But I'm not sure if that can work with more complicated examples.

**Comment by asterite** [comment]
You can't nest colorize. Each colorize instance will set terminal attributes and then reset them at the end. So if you nest them inside another color, you'll reset the first one in the middle.

I don't think there's any sane way to fix this. You are interpolating a colorized instance inside of a string, and at that point there's no way to know if you are going to put that inside another color.

You'll have to specify all attributes for every piece of text you want.

**Comment by naltun** [comment]
@straight-shoota @asterite Thanks to you both for the swift response. I'll keep this in mind when using Colorize.

I'll go ahead and close this issue. Thanks again!

**Comment by straight-shoota** [comment]
Just to clarify: It *might* be possible to make Colorize smart enough to recognize and handle nested escape sequences. If somebody's interested in looking into that, it might prove fruitful.

**Comment by naltun** [comment]
@straight-shoota If you want, I can reopen this issue and we can add an 'enhancement/help wanted' label and see where it goes. It's up to you guys.
