### ISSUE TITLE
Can only use named types with NamedTuple

### ISSUE THREAD

**Issue by QueCaudroit** [crystal-lang/crystal#6135]
I'm trying to implement DataFrames, so i want a class to be able to receive any number of types.

Basicaly, it should be allowed to do the following:
```
class DataFrame(**T)
  def initialize(@data : Array(NamedTuple(**T)))
  end
end

data = [{x: 1, y: "yay"}, {x: 3, y: "Coucou"}]
dt = DataFrame(x: Int32, y: String).new data
```
right now this gives the following compile time error:
```
Syntax error in test.cr:1: expecting token 'CONST', not '**'

class DataFrame(**T)
```

crystal -v outputs this:
```
Crystal 0.24.2 [4f9ed8d03] (2018-03-08)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by asterite** [comment]
That's not how it works.

Named tuples are useless except for named arguments. Please everyone stop (an)using them so much.

Please describe your use case and someone might help you.

**Comment by QueCaudroit** [comment]
Dataframes are arrays used to represent data with heterogeneous types of data. It is a common structure used in languages such as python or R for data science.

Dataframes can be represented with arrays of hashes, with the value of hashes being union types (so only one generic argument is needed), but it would be great to be able to enforce the types of each value 

In the example above, the class used to store the data could have 2 generic arguments,
but the aim is to allow any number of values.

**Comment by asterite** [comment]
You can't do that in this language. This is not a dynamic language and there's no runtime reflection.

**Comment by QueCaudroit** [comment]
I think I explained myself badly.
The goal is to have the type of the data set at compilation, not at runtime.

**Comment by asterite** [comment]
I think I understand.

But that "feature" is only supported for named tuple.

You can do this:

```crystal
class DataFrame(T)
  def initialize(@data : Array(T))
  end
end

data = [{x: 1, y: "yay"}, {x: 3, y: "Coucou"}]
dt = DataFrame.new data
```

**Comment by asterite** [comment]
Or even:

```crystal
class DataFrame(T)
  def initialize(@data : T)
  end
end

data = [{x: 1, y: "yay"}, {x: 3, y: "Coucou"}]
dt = DataFrame.new data
```

**Comment by asterite** [comment]
(and because it's just a wrapper around a `T`, I don't understand what's the purpose of that type)

**Comment by QueCaudroit** [comment]
yes i could!
But (considering your first approach) it would be necesary to enforce the type of T to be NamedTuple(something), and the type of my object would be DataFrame(NamedTuple(x: Int32, y: String))

The purpose of that type is to offer the basic tools to transform your data (like grouping entries by a set of keys, sorting by a set of keys, filtering...) and more complex transformations would be allowed by yielding.

> But that "feature" is only supported for named tuple.
Appart from my use case, isn't it weird that this is only supported for named tuples?
Are there any technical limitations ?

**Comment by asterite** [comment]
You can do what you want. If you always use that DataFrame type with named tuples, the compiler will check it. If not, you'll get an error. In that sense, generic types are a joke in Crystal (there's no where clause).

I didn't implement because I can't find a good use case, and I'm lazy. This probably means it will never be implemented.

**Comment by QueCaudroit** [comment]
Thank you, that answers my question.

**Comment by RX14** [comment]
@QueCaudroit for now you can do something similar to [this](https://github.com/crystal-lang/crystal/blob/3c887de16f96cd01e4937dfe5b03d51d729dd69d/src/atomic.cr#L8) for restricting `T` to types you want. It's ugly but it's a good workaround until we can have something a bit better in the language.
