### ISSUE TITLE
Defining new after initialization crashes the compiler

### ISSUE THREAD

**Issue by spejamchr** [crystal-lang/crystal#6139]
I only just started playing with Crystal, so I normally assume all errors are just me doing stuff wrong, but these ones asked me to submit an issue. So here you go. :)

This might be related to #718 or #867, but from what I could tell both of those are already fixed.

I was trying to implement a singleton and accidentally crashed the compiler.

```crystal
# one.cr
class Singleton
  INSTANCE = new
end

p Singleton::INSTANCE

class Singleton
  def self.new
    raise "There can be only one!"
  end
end
```
Running it I get the error:

```
$ crystal run one.cr
Module validation failed: loading unsized types is not allowed
  load void, void* %74
Call parameter type does not match function signature!
  load void, void* %74
 %Singleton*  %75 = call %Singleton* @"*p<Singleton>:Singleton"(void <badref>), !dbg !68

Crystal::CodeGenVisitor#finish:Nil
Crystal::Compiler#codegen<Crystal::Program, Crystal::ASTNode+, Array(Crystal::Compiler::Source), String>:(Tuple(Array(Crystal::Compiler::CompilationUnit), Array(String)) | Nil)
Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result
Crystal::Command#run_command<Bool>:Nil
Crystal::Command#run:(Bool | Crystal::Compiler::Result | IO::FileDescriptor | Nil)
main

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

I refactored it to this and got a similar error:

```crystal
# one.cr
class Singleton
  INSTANCE = new
  puts INSTANCE

  def self.new
    return INSTANCE
  end
end
```

```
$ crystal run one.cr
Module validation failed: loading unsized types is not allowed
  load void, void* %74

Crystal::CodeGenVisitor#finish:Nil
Crystal::Compiler#codegen<Crystal::Program, Crystal::ASTNode+, Array(Crystal::Compiler::Source), String>:(Tuple(Array(Crystal::Compiler::CompilationUnit), Array(String)) | Nil)
Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result
Crystal::Command#run_command<Bool>:Nil
Crystal::Command#run:(Bool | Crystal::Compiler::Result | IO::FileDescriptor | Nil)
main

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

Finally, I specified the type of new using `as`, which ran without errors, but the singleton unexpectedly has an object id of 0. But like I said, that's probably just me doing stuff wrong.

```crystal
class Singleton
  INSTANCE = new.as(Singleton)
  puts INSTANCE #=> #<Singleton:0x0>

  def self.new
    return INSTANCE
  end
end

puts Singleton::INSTANCE #=> #<Singleton:0x0>
puts Singleton::INSTANCE.object_id #=> 0
puts Singleton.new.object_id #=> 0
```

```
$ crystal -v
Crystal 0.24.2 (2018-03-10)

LLVM: 5.0.1
Default target: x86_64-apple-macosx
```

**Comment by ysbaddaden** [comment]
I think you assume that `INSTANCE` will use the default `self.new`, then you overwrite `self.new` to raise / return default `INSTANCE`, but Crystal is a compiled language, your source code won't be processed sequentially as in Ruby for instance, but all functions will first be generated then executed. This means that `INSTANCE = new` will always call the overwritten `self.new` even it's definition happens *later on* in the source code.

To create a singleton, instead of overwriting `new` declare `initialize` as private:
```crystal
class Foo
  INSTANCE = new

  private def initialize
  end
end

Foo::INSTANCE # => #<Foo:0x24f8fe0>
Foo.new       # => private method 'new' called for Foo:Class
```

For some reason the compiler doesn't catch these issues (maybe hard to detect or overlooked), and this causes it to generate invalid LLVM IR, so compilation fails.

**Comment by spejamchr** [comment]
Thanks for the explanation!

**Comment by straight-shoota** [comment]
Please reopen this issue. Even though the immediate problem is solved, the compiler should not generate invalid LLVM IR but produce a meaningful error.
