### ISSUE TITLE
Bug in Intrinsics#memset/memmove/memcpy

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#6151]
When you give a value at the `align` argument of [Intrinsics#memset/memmove/memcpy](https://github.com/crystal-lang/crystal/blob/master/src/intrinsics.cr) which is outside of the range `0..2` then it gives you a bug.

Example of [Intrinsics#memset](https://github.com/crystal-lang/crystal/blob/master/src/intrinsics.cr):
```Crystal
String.new(1) do |buffer|
  Intrinsics.memset(buffer, 1, 1, 10, false)
  {1, 1}
end
```
gives
```
Module validation failed: alignment argument of memory intrinsics must be a power of 2
  call void @llvm.memset.p0i8.i64(i8* %89, i8 1, i64 1, i32 10, i1 false), !dbg !26

???
???
???
???
???
???
???
???

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```
Example of [Intrinsics#memmove](https://github.com/crystal-lang/crystal/blob/master/src/intrinsics.cr):
```Crystal
String.new(1) do |buffer|
  u8 = 1u8
  Intrinsics.memmove(buffer, pointerof(u8), 1, 50, false)
  {1, 1}
end
```
gives
```
Module validation failed: alignment argument of memory intrinsics must be a power of 2
  call void @llvm.memmove.p0i8.p0i8.i64(i8* %89, i8* %u8, i64 1, i32 50, i1 false), !dbg !26

???
???
???
???
???
???
???
???

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```
But this for example works:
```Crystal
String.new(1) do |buffer|
  u8 = 1u8
  Intrinsics.memcpy(buffer, pointerof(u8), 1, 2, false)
  {1, 1}
end
```

**Comment by RX14** [comment]
Read the nice error message you got?

**Comment by r00ster91** [comment]
Yea but after this theres this:
```
???
???
???
???
???
???
???
???

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```
and I don't think that should ever happen.

**Comment by asterite** [comment]
Don't use Intrinsics directly. The module is just there for the standard library. Use Pointer. Plus you shouldn't be fiddling with alignment, that's the job of the compiler.

**Comment by RX14** [comment]
@r00ster91 that's because you're using an LLVM intrinsic, so the error will naturally come from LLVM. As @asterite said, these methods are unstable, just like `LibC`. They're exposed stably and nicely under `Pointer`. For these reasons, the error isn't "clean". But thats relatively fine, since the code is unsafe anyway.

**Comment by r00ster91** [comment]
I found this 'bug' while I tried to add an efficient `Char#*` because I often need it and always when I write something like `"a"*5` then I think that this could be more efficient. My results are this so far:
```Crystal
struct Char
  def *(times : Int)
    raise ArgumentError.new "Negative argument" if times < 0

    return "" if times == 0

    String.new(times) do |buffer|
      Intrinsics.memset(buffer.as(Void*), self.ord.to_u8, times, 0, false)
      {times, 1}
    end
  end
end

require "benchmark"

Benchmark.ips do |x|
  x.report "String#*" do
   "0"*5
  end

  x.report "Char#*" do
    '0'*5
  end
end
```
```
String#*  25.64M ( 39.01ns) (±12.20%)  1.10× slower
  Char#*  28.21M ( 35.45ns) (± 4.89%)       fastest
```
But `String#*` is faster at for example `'0'*100`

**Comment by RX14** [comment]
Lets add a proper memset binding for pointer
