### ISSUE TITLE
question on terms of use

### ISSUE THREAD

**Issue by brandonmp** [crystal-lang/crystal#6171]
Your [Media page](https://crystal-lang.org/media/) has the following constraint:

> [Don't] Sell training programs, courses or educational material without permission.

Does this mean one needs explicit permission from the Crystal team before releasing training material on sites like Udemy, egghead.io, etc?

Most just curious because I've never seen a clause like this on an OSS language / lib before--though maybe I just haven't noticed?

**Comment by bararchy** [comment]
Maybe that's an artifact from older times? 
Currently I know of several Crystal programming books being published for profit, not sure if they got official constant.

**Comment by RX14** [comment]
This is under the banner

> Don’t do these things with the Crystal logos and brand

So I would assume that all these limitations would relate to selling training programs, courses or educational material *while attempting to make the material look official*. Putting a big crystal logo, using the crystal font and colour scheme on the cover of a book - when the book isn't official or endorsed by the core team - isn't okay. Maybe we can get clarification on that and better wording to clarify the aims of these restrictions.

I'd personally interpret the logo stuff as saying that you can't change the logo colours or add your own text then use it to represent crystal. Amber made a derivative of our logo then used it to represent *another project* which is okay in my book.

Please not this is my *personal* interpretation, *not* an official statement.

**Comment by brandonmp** [comment]
@RX14  this is sort of why I thought as well, but the general language of the bullet makes it sound like it applies more broadly than just use of branding & assets.

if your interp is correct, imo it should read something like 

> [Don't] Use the Crystal logo in non-free training programs, courses or educational material without permission.

**Comment by bcardiff** [comment]
@brandonmp we are going to rephrase that last item to be more clear about our expectation.

> [Don't] Use the logo in a way that could suggest sponsorship or endorsement by Crystal

It's not the intention that authors would need explicit permission from the Crystal team before releasing training material on sites like Udemy, egghead.io. More voices and perspective will better for the community.
