### ISSUE TITLE
Crystal bug while compiling

### ISSUE THREAD

**Issue by Polands-in-the-sky** [crystal-lang/crystal#6183]
I was using the Crystal compiler the first time on Windows Subsystem for Linux(Ubuntu) and got the following error. How can I fix that?

`Poland@Poland:/mnt/e/kurwa/руст$ crystal hello.cr
String contains null byte
???
???
???
???
???
???
???
???

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues`
```

**Comment by straight-shoota** [comment]
We'll need to see the source code you try to compile in order to help you.

**Comment by straight-shoota** [comment]
I can't reproduce this error.

What Crystal version are you using and which operating system version?

Tip: Use triple backticks and put them on a separte line for block code format. Add `crystal` after the opening backticks to get syntax highlighting.

**Comment by ZaWertun** [comment]
It's duplicate of #5348 (see also #5799). It's not fixed in 0.25 yet.

**Comment by bcardiff** [comment]
@ZaWertun #5350 which is referenced for those issues is included in 0.25.0

**Comment by ZaWertun** [comment]
@bcardiff Sorry, it's really fixed, looks like I'm using version older then 0.25 for tests.

**Comment by bcardiff** [comment]
It's great to confirm it works for you in 0.25. I'm wanted to double check.
