### ISSUE TITLE
required libraries for compilation on arch?

### ISSUE THREAD

**Issue by sam0x17** [crystal-lang/crystal#6189]
This page https://github.com/crystal-lang/crystal/wiki/All-required-libraries has directions for Ubuntu, Fedora, and OSX. Does anyone know what is required for Arch? I'm having some issues compiling with `--static` and I suspect there might be some libraries I need that I don't have.

```
$ crystal build src/hello_world.cr --release --static
/usr/bin/ld: cannot find -lpcre
/usr/bin/ld: cannot find -lgc
/usr/bin/ld: cannot find -levent
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/sam/Desktop/workspace/crystal-gcf-concept/hello_world'  -rdynamic -static  -lpcre -lgc -lpthread /usr/lib/crystal/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
```

**Comment by sam0x17** [comment]
Ok so I have no idea why pcre, gc, and libevent are giving me problems as I have all of them. I installed crystal via pacman so I have 0.24.2. :thinking:

**Comment by j8r** [comment]
@sam0x17 the `.a` archives required for static compilation aren't provided.

The best is to use a musl-based distribution like alpine. You can use this [docker image](https://store.docker.com/community/images/jrei/crystal-alpine) (maybe I can add an entry in the wiki though).

**Comment by j8r** [comment]
There are lots of issues related to [static compilation](https://github.com/crystal-lang/crystal/search?utf8=%E2%9C%93&q=static+linking&type=Issues). Problems related to the distribution packages, their versions, or the meaning of the linking error.

What about suggesting an "official" solution for static linking like a Docker image to solve this when `--static` fails (lile we are going [to do with macOS](https://github.com/crystal-lang/crystal/pull/6110)?

**Comment by RX14** [comment]
static compilation isn't supported by archlinux, either for C or Crystal. You'll have to compile static libraries yourself if you want them. The only sane environment for static linking is musl, the rest of linux is broken.

**Comment by sam0x17** [comment]
thanks a bunch guys -- a docker image is perfect for my needs

**Comment by sam0x17** [comment]
@kirbyfan64 thanks for the tip -- in my case I am limited by what Google has pre-installed on their cloud functions VM, which definitely not include flatpack or snap, but I might be able to do this another way using a disposable docker image
