### ISSUE TITLE
Installing from source on Mac OS X - docs are not correct

### ISSUE THREAD

**Issue by yyyc514** [crystal-lang/crystal#619]
Can up-to-date steps be provided for MAC OS X?  I have seen and read: http://crystal-lang.org/docs/installation/from_source_repository.html but I've been told LLVM 3.5.1 is no longer correct.  The Makefile seems to want LLVM 3.6, but then I've also been told a custom patch is required.  The homebrew recipe for 0.7.1 will install LLVM 3.5.1 if you use --with-llvm.

Can I get some authoritative answers here and I can contribute pull-requests to update the docs and home-brew recipe?

**Comment by yyyc514** [comment]
Related: https://github.com/manastech/homebrew-crystal/pull/2

3.5.1 with patch seems to work great. (all specs pass)

**Comment by Arcnor** [comment]
You can also use the package `llvm36` and Crystal will woth with it without having to patch anything

**Comment by yyyc514** [comment]
@asterite says there have been some issues with `llvm36` - that's why I'm just trying to get this stuff more official and more documented - so we don't have to guess at these things.

**Comment by Arcnor** [comment]
Where did you see that? I thought there were problems with `llvm35` but not `llvm36`... I'm using 3.6 without issue, unless it's something very specific...

**Comment by yyyc514** [comment]
I recall him mentioning it directly on IRC, hence my pinging him here.

**Comment by asterite** [comment]
I'm closing this. Please add a PR or another issue mentioning specific issue in [Contributing.md](https://github.com/crystal-lang/crystal/blob/master/Contributing.md#contributing-to-the-compiler-itself).
