### ISSUE TITLE
delegation is broken in 0.25

### ISSUE THREAD

**Issue by robacarp** [crystal-lang/crystal#6204]
I believe I've stumbled onto a bug in 0.25.

```crystal
class Klass
  @hsh={} of String => String
  delegate :[]=, to: @hsh
  getter hsh
end

# works:
Klass.new.hsh["test"] = "hi"

# doesnt work in Crystal 0.25:
Klass.new["test"] = "hi"
```

The error is:

```text
Error in line 18: wrong number of arguments for 'Klass#[]=' (given 2, expected 1)
Overloads are:
 - Klass#[]=(arg)
```

> crystal -v
Crystal 0.25.0 (2018-06-15)
LLVM: 5.0.1
Default target: x86_64-apple-macosx

**Comment by z64** [comment]
I believe this is already reported/fixed

https://github.com/crystal-lang/crystal/issues/6177
https://github.com/crystal-lang/crystal/pull/6178

**Comment by robacarp** [comment]
Good to hear, sorry I missed that on search.
