### ISSUE TITLE
Documentation for Time::Format missing

### ISSUE THREAD

**Issue by z64** [crystal-lang/crystal#6206]
https://crystal-lang.org/api/0.24.2/Time/Format.html

https://crystal-lang.org/api/0.25.0/Time/Format.html (404)

**Comment by HCLarsen** [comment]
It also appears that some of the formatting options have changed from the previous version, so this is quite urgently needed.

**Comment by straight-shoota** [comment]
`Time::Format` is documented but was marked as `nodoc` in `yaml_date.cr`. Easy fix.

There where no big changes to the formatter options, though. Only `Time::Location` instead of `Time::Kind`. And the ISO formats now use a sophisticated, custom parser.
