### ISSUE TITLE
Question on nested arrays iterations

### ISSUE THREAD

**Issue by lucatrv** [crystal-lang/crystal#6210]
I'm new to Crystal, and am not a Rubyist either, so forgive me if the question is trivial.

Lets consider two nested arrays initialized as:

```
m1 = m2 = Array.new(10) { Array.new(10, 0.0) }
```

I would like to change their elements, for instance as follows:

1. Assign each `m1` "row" subarray element equal to `j**2`, where `j` is the subarray index. I tried with `m1.each { |row| row.fill { |j| j**2 } }` but it does not work.
2. Assign each `m1` element equal to `i*j`, where `i` and `j` are respectively the "row" (external array) and the "column" (internal array) indexes.
3. Assign each `m2` element equal to the corresponding `m1` element squared.
4. Assign each `m2` element equal to the sum of the corresponding `m1` and `m2` elements.

Can you please provide some examples or references?

Thanks

**Comment by ysbaddaden** [comment]
This is the issue tracker for Crystal. Please ask language questions on stackoverflow, using the #crystal-lang tag. Thanks!

**Comment by asterite** [comment]
>  I tried with m1.each { |row| row.fill { |j| j**2 } } but it does not work

Did you read the error message? I'm pretty sure it says the block expects a Float64 but the block's type is Int32...

As for the other points, you should provide some code you tried. But, yeah, this is not a forum, this is for tracking bugs and suggestions.

**Comment by lucatrv** [comment]
Sorry I wrote here because I did not understand the error message and I actually thought that what I wrote at point 1 was an issue...

I add below the solutions to my questions, hopefully they can be useful for some other Crystal beginner.

1. Assign each `m1` "row" subarray element equal to `j**2`, where `j` is the subarray index:
```
m1.each { |row| row.fill { |j| j.to_f / s } }
```
2. Assign each `m1` element equal to `i*j`, where `i` and `j` are respectively the "row" (external array) and the "column" (internal array) indexes:
```
m1.each_with_index { |row, i| row.fill { |j| i.to_f * j } }
```
3. Assign each `m2` element equal to the corresponding `m1` element squared:
```
m1.zip(m2).each { |m1_row, m2_row| m2_row.fill { |j| m1_row[j] ** 2 } }
```
4. Assign each `m2` element equal to the sum of the corresponding `m1` and `m2` elements:
```
m1.zip(m2).each { |m1_row, m2_row| m2_row.fill { |j| m1_row[j] + m2_row[j] } }
```

Point 4 above works when compiled with `crystal build`, but triggers an error in `crystal play`... maybe I actually found a bug :) please try it yourself with the following code:
```
m1 = m2 = Array.new(3) { Array.new(3, 0.0) }
m1.zip(m2).each { |m1_row, m2_row| m2_row.fill { |j| m1_row[j] + m2_row[j] } }
```

**Comment by bcardiff** [comment]
Question addressed, playground bug reduced and reported in a separate issue.
Thanks!
