### ISSUE TITLE
Error instantiating 'Socket#accept()'

### ISSUE THREAD

**Issue by BarelyMalicious** [crystal-lang/crystal#6212]
```crystal
require "socket"

server = Socket.new(Socket::Family::INET, Socket::Type::STREAM)
server.reuse_address = true

server.bind(1234)
server.listen

while true
  client = server.accept
end
```
This code gives -
```
Error in s.cr:10: instantiating 'Socket#accept()'

  client = server.accept
                  ^~~~~~

in /usr/share/crystal/src/socket.cr:212: instantiating 'accept?()'

    accept? || raise IO::Error.new("Closed stream")
    ^~~~~~~

in /usr/share/crystal/src/socket.cr:231: wrong number of arguments for 'Socket.new' (given 1, expected 2..5)Overloads are:
 - Socket.new(fd : Int32, family, type, protocol = Protocol::IP, blocking = false)
 - Socket.new(family, type, protocol = Protocol::IP, blocking = false)

      sock = Socket.new(client_fd)
                    ^~~
```

**Comment by straight-shoota** [comment]
`Socket#accept` does not work. You need to use a `Socket::Server` which implements a custom `#accept?` method. In this case you could use `[TCPServer](https://crystal-lang.org/api/latest/TCPServer.html)`.

The Socket API is a real mess, unfortunately. But there is already an issue for refactoring that (#5778).

**Comment by Daniel-Worrall** [comment]
Can't we instance the new socket with the family and type of the server using the existing overloads?

**Comment by RX14** [comment]
`getsockopt` can query the `SO_PROTOCOL` and `SO_TYPE`, so a `.new(fd)` could be implemented.

However, it's not clear that we don't just want to copy the values from the socket you called `accept` from. I don't know the minutia of the socket API.
