### ISSUE TITLE
Unable to get extension with File.extname of filenames with length=1

### ISSUE THREAD

**Issue by bcardiff** [crystal-lang/crystal#6215]
Regression introduced at #5790

In crystal 0.25.0

```crystal
File.extname("a.cr") => ""
```

But the expected result is
 
```crystal
File.extname("a.cr") => ".cr"
```

**Comment by aisrael** [comment]
(So yeah I was about to file the following)

### Background

In Crystal 0.24.x

```
File.extname("a.yml")
```

Returns `".yml"`

### Expected Behavior

In Crystal 0.25.0

```
File.extname("a.yml").should eq(".yml")
```

### Actual Behavior

```
File.extname("a.yml") # => ""
```

**Comment by straight-shoota** [comment]
The log says *@RX14 modified the milestone: 0.25.1 5 days ago*, but the PR has no milestone now (and it doesn't seem there was one before).
