### ISSUE TITLE
NamedTuple is recognized as block in some cases?

### ISSUE THREAD

**Issue by tbrand** [crystal-lang/crystal#6224]
I think the below is not a bug but specification currently.
But hopefully will be fixed.

I frequently use NamedTuple in my codes.
Sometimes I face such a syntax error.
```crystal
p { hoge: "ok" }
# => Syntax error in hoge.cr:1: expecting token 'CONST', not 'DELIMITER_START'
```

I can avoid it by replacing the tuple to variable like
```crystal
hoge = { hoge: "ok" }
p hoge
```

Crystal version is 0.25.0.

**Comment by z64** [comment]
It's because you're using `p` which, expands into code internally that will parse it like a block

use parens to avoid this https://carc.in/#/r/4bzx

**Comment by tbrand** [comment]
Make sense:+1: Thanks.

**Comment by asterite** [comment]
@z64 That's not the reason. The reason is that `p` is just a method call, and if you have **anything** that looks like this:

```crystal
some_word { ... }
```

then it's always a block, never a hash, tuple or named tuple.

This is **exactly** like in Ruby. You have to use parentheses in this case.
