### ISSUE TITLE
Update shards to 0.8.1

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#6227]
shards 0.8.1 fixed critical issue.
i see that OS X version (from brew) already use 0.8.1, but linux release in https://github.com/crystal-lang/crystal/releases, still use 0.8.0

**Comment by bcardiff** [comment]
We will solve a couple of regressions in the next few days and release 0.25.1 with an updated shards probably during next week.

As a quick workaround shards can be checked out and built from source.

Given that there are some regressions present and it’s not just the shards issue I think is the best alternative regarding timing for everybody.

**Comment by ysbaddaden** [comment]
Closing. This is related to distribution. Next release will have it, and should arrive quickly.
