### ISSUE TITLE
crystal spec doesn't support --link-flags

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang/crystal#6231]
Hi, I'm trying to run specs for Amber on macOS (https://github.com/amberframework/amber/pull/879) and looks like brew openssl needs to be linked directly in the compiler, so I tried this: (suggested by @bcardiff )

```
crystal spec --link-flags -L/usr/local/opt/openssl/lib
```

And I got this:

```
Unhandled exception: Invalid option: --link-flags (OptionParser::InvalidOption)
  from /usr/local/Cellar/crystal-lang/0.25.0_1/src/option_parser.cr:79:45 in '->'
  from /usr/local/Cellar/crystal-lang/0.25.0_1/src/option_parser.cr:255:3 in 'check_invalid_options'
  from /usr/local/Cellar/crystal-lang/0.25.0_1/src/option_parser.cr:228:7 in 'parse'
  from /usr/local/Cellar/crystal-lang/0.25.0_1/src/option_parser.cr:184:5 in 'parse'
  from /usr/local/Cellar/crystal-lang/0.25.0_1/src/spec.cr:109:1 in '__crystal_main'
  from /usr/local/Cellar/crystal-lang/0.25.0_1/src/crystal/main.cr:104:5 in 'main_user_code'
  from /usr/local/Cellar/crystal-lang/0.25.0_1/src/crystal/main.cr:93:7 in 'main'
  from /usr/local/Cellar/crystal-lang/0.25.0_1/src/crystal/main.cr:133:3 in 'main'
```

I looked into the compiler source code and I found that `crystal spec` is using `setup_simple_compiler_options`, so, it doesn't support all flags.

https://github.com/crystal-lang/crystal/blob/9da2831aa12827601ff414b4685dcf0327ddc69b/src/compiler/crystal/command.cr#L484

https://github.com/crystal-lang/crystal/blob/430fea3aaf3e9b7d6d84e4ebb5f5e20415e2c226/src/compiler/crystal/command/spec.cr#L14-L17

**Comment by felixbuenemann** [comment]
@faustinoaq You should be able to work around the issue using `PKG_CONFIG_PATH`, eg.:

```
PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig crystal spec
```

I'm using the same trick with `shards build` in a project that requires openssl.
