### ISSUE TITLE
Invalid memory access in spec in 0.25.0

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#6235]
one spec in my big app just crash the spec runner, i try to reduce it, but still no luck (it complex project). and if i just compile its ok. is there any way to debug it?

```
crystal spec my_spec.cr
Invalid memory access (signal 11) at address 0x22b2ae0
[0x4f1776] *CallStack::print_backtrace:Int32 +118
[0x4d8c7b] __crystal_sigfault_handler +75
[0x7fe04086b330] ???
[0x22b2ae0] ???
```

```
crystal build my_spec.cr && ./my_spec
.

Finished in 3.66 milliseconds
1 examples, 0 failures, 0 errors, 0 pending
```

**Comment by bcardiff** [comment]
@kostya are you in osx or linux? The problem might be in the stacktrace code. Try with `--no-debug` as see what happens.

**Comment by kostya** [comment]
this is fixed it:
```
CRYSTAL_CACHE_DIR=/tmp/bla/ crystal spec my_spec.cr --no-debug
.

Finished in 22.46 milliseconds
1 examples, 0 failures, 0 errors, 0 pending
```

**Comment by RX14** [comment]
This is weird. The current cache mechanism should be robust.

**Comment by RX14** [comment]
Do you remember when the last time you compiled specifically `my_spec.cr` was? Was it with an older version of crystal?

**Comment by kostya** [comment]
i not run one spec, i run all specs in previous crystal version, and then run all in new crystal, and got crash, then find in which spec this happens.

**Comment by RX14** [comment]
Can you reproduce this by clearing cache, downgrading, compiling, upgrading again? What are the LLVM versions of both compilers?

**Comment by kostya** [comment]
not reproduces, may be this was my bad hard drive problem.
