### ISSUE TITLE
Push updated Docker image for 0.25.0 with shards 0.8.1?

### ISSUE THREAD

**Issue by hmans** [crystal-lang/crystal#6247]
As of now, the currently available docker image for 0.25.0 still comes with shards 0.8.0, which had a [significant bug](https://github.com/crystal-lang/shards/pull/212) that was [fixed in shards 0.8.1](https://github.com/crystal-lang/shards/commit/0147a560f0cc8b9ecc68ed79e242b68598c41fce).

This leaves projects that build using the docker image stuck with the broken version of shards, unless you patch together your own image, or outright switch to Crystal nightly.

Similar to how the [Crystal formula for Homebrew has since been updated](https://github.com/Homebrew/homebrew-core/blob/master/Formula/crystal-lang.rb) with a new revision including the fixed shards, can we also get a fixed/new Docker image before 0.25.1 is released?

**Comment by bcardiff** [comment]
I am not sure about overwriting docker images with tag once the are released (except latest and nightly for sure).

Also, I think the cache issue in shards 0.8.0  should not affect in docker images. Unless you are mounting a shard cache path, that should be empty. I haven't tested and maybe I am missing something.

0.25.1 has been released for now with an updated shards.

So I think there is nothing blocked here, but feel free to argue about immutability of docker tags and if there is something else been blocked.

**Comment by hmans** [comment]
No worries; with the release of 0.25.1, this issue is obsolete. Just a quick note about the Docker version tags: would it have been an option to create a `crystal:0.25.0-1` tag (similar to how it was done with the updated Homebrew formula)?
