### ISSUE TITLE
BigInt doesn't require its dependency on LibGMP

### ISSUE THREAD

**Issue by JoshCheek** [crystal-lang/crystal#6257]
### Synopsis

`BigInt` depends on `LibGMP`, but does not require it. It seems to be expecting `big.cr` to have been required instead of `big/big_int.cr`. Thought it was going to be something like in C how you have to pass the a `-lm` flag in order for it to include math.h 😜 But nah, just a missing require (note that I didn't audit the file to check if it used any of the other requires from `big.cr`)

### Version

```sh
$ crystal --version
Crystal 0.25.0 (2018-06-20)

LLVM: 5.0.1
Default target: x86_64-apple-macosx
```

### Works if I require "big/lib_gmp.cr"

```sh
$ crystal eval 'require "big/lib_gmp"; require "big/big_int"; p 0.to_big_i'
0_big_i
```

### Breaks if I don't 

```sh
$ crystal eval 'require "big/big_int"; p 0.to_big_i'
Error in line 1: instantiating 'Int32#to_big_i()'

in /usr/local/Cellar/crystal-lang/0.25.0_1/src/big/big_int.cr:525: instantiating 'BigInt:Class#new(Int32)'

    BigInt.new(self)
           ^~~

in /usr/local/Cellar/crystal-lang/0.25.0_1/src/big/big_int.cr:42: undefined constant LibGMP (did you mean 'LibGC')

      LibGMP.init_set_si(out @mpz, num)
      ^~~~~~
```

**Comment by bcardiff** [comment]
Hi @JoshCheek the intention is for the user to do `require "big"` that will end up doing

```
require "./big/lib_gmp"
require "./big/big_int"
require "./big/big_float"
require "./big/big_rational"
require "./big/big_decimal"
```

If you want to _only_ include big_int, yes yo need to do that.

There are many files that does not require all their dependencies because they are not intended to be used as requirement files (although they can).

**Comment by JoshCheek** [comment]
I'll advocate against this approach. The reasoning is expressed in [this](https://zeuxcg.org/2010/11/15/include-rules/) blog, but here's an excerpt:

> For this reasons, it’s important for all headers to be self-contained - anybody should be able to include any header in any cpp file without compilation errors. Which brings us to the second important rule - **each file should include all dependent headers,** i.e. for each declaration that’s required by the compiler there should be a corresponding include. This rule helps ensure that the programmers stay sane.

Learned about it from... I think neovim, which adopted it because the vim codebase had become incredibly difficult to work with. Google apparently made [this](https://github.com/include-what-you-use/include-what-you-use) tool because they suffered the same difficulty. In this case, it seems it would be as easy as adding `require "./lib_gmp"` to `big/big_int.cr`, or if not, then it seems that file should be treated as an implementation detail and I shouldn't be able to require it and the docs shouldn't point me to it:

![screen shot 2018-06-25 at 8 11 48 am](https://user-images.githubusercontent.com/77495/41852010-7af2dc68-784f-11e8-9d16-cc7d84b99d4c.png)

**Comment by RX14** [comment]
I don't think "defined in" means "you can require this", but I think there's definitely a discussion to be had about the "require surface" of the stdlib. How do we communicate to the user which files are stable to require, and which files aren't considered API and may break? Do we need to enforce that in the compiler?

**Comment by straight-shoota** [comment]
Some classes have a long list where they're "defined in" because of reopening. So obviously, this is not exactly what you should depend on to require something.
