### ISSUE TITLE
[Proposal] Add Code of Conduct

### ISSUE THREAD

**Issue by conradwt** [crystal-lang/crystal#6263]
## Proposal

Please add link on the `README.md` to the `Code of Conduct` which applies to `crystal` repository and all of its subprojects' repositories (i.e. crystal-lang author).

## Examples

- [Rails](https://rubyonrails.org/conduct/)

- [Golang](https://golang.org/conduct)

**Comment by Sija** [comment]
Why would we need one? I'm closer to [NCoC](https://github.com/domgetter/NCoC) in this regard.

**Comment by asterite** [comment]
Ummm...

https://github.com/crystal-lang/crystal/blob/master/CODE_OF_CONDUCT.md

**Comment by kirbyfan64** [comment]
IME a lot of people see a CoC as the universal solution for equality, but:

- It's only as good as it's enforced. All a CoC ultimately ends up being is a moderator's guidebook. 
- People have a tendency to go a little crazy with CoC invocations. It has a tendency to make them cry foul at the slightest offense, followed by a heated debate about what exactly the CoC enforces. 
- Related to the above: it's filled with fluffy words, but it's also very vague. The discretion is ultimately the moderators, which leads back to the first point. 
- Ultimately, in my experience, **it does nothing**. If someone wants to be a moron, they'll still be a moron. If someone wants to be racist, they'll still be racist. A vague, abstract document is hardly going to deter them any more than moderators already would.

**Comment by Sija** [comment]
Well, actually **there is** one already. I had to look for it because no-one used it as an "argument" even in the hottest of arguments I remember. Maybe it's because there's still very lil' politicking goin' on in here... and personally, I'd like this to continue, whether there is a CoC or not.
