### ISSUE TITLE
[Proposal] Add link to license

### ISSUE THREAD

**Issue by conradwt** [crystal-lang/crystal#6264]
## Proposal

Add link to the license file on the `README.md`

## Examples

- [Rails](https://github.com/rails/rails)

**Comment by asterite** [comment]
There's a [LICENSE](https://github.com/crystal-lang/crystal/blob/master/LICENSE) file at the top of the repository. You see it in the files when you enter the repository: https://github.com/crystal-lang/crystal

I don't think it's worth linking it in the `README.md`. Or, well, it's not that important, really.

**Comment by conradwt** [comment]
@RX14 Thanks for closing this for me.
