### ISSUE TITLE
Bug in Crystal, can't assign instance var?

### ISSUE THREAD

**Issue by trans** [crystal-lang/crystal#6281]
I hope I am just being daft in some way, but I can't make sense of this. Please see:

https://groups.google.com/forum/#!topic/crystal-lang/Qf9aYUbygDE

Basically I can change an instance variable in place, but I can't reassign it. Worse, when I do reassign it, the method in which it is reassigned clearly shows that it has been reassigned. But then when I access the same instance variable from another method, it is as if hasn't been been.

**Comment by asterite** [comment]
The `cli` macro passes `args`, but it's in a loop that's constantly shifting from `args`. So replace works because it copies the data from the array, but reassigning does not because it uses the same array reference.

**Comment by trans** [comment]
Oh, I'm passing a reference. Just need to dup it. Thank you!!!
