### ISSUE TITLE
libyaml 0.2.1 breaks YAML builder

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#6283]
The new release libyaml 0.2.1 seems to change some behaviour which breaks a few of our yaml specs.
An example can be seen on any of the last spec runs on CircleCI OSX since the homebrew formula was [updated](https://github.com/Homebrew/homebrew-core/commit/49465bdabcbe8acc2103116cfab1386a2c92a150) a few hours ago (e.g. https://circleci.com/gh/crystal-lang/crystal/8409).

It seems like libyaml has removed writing the document end marker (`...`) and is more consistent now. It was already only added in a few places. So I guess the only thing to do here is to remove the expected `\n...` from the affected specs.

I'm not sure what exactly causes this as I didn't find any information about this in the libyaml [release announcement](https://github.com/yaml/libyaml/blob/master/announcement.msg) or the commit history. But I have checked that these specs pass with libyaml 0.1.6 but fail with 0.2.1 on linux as well.
I didn't check 0.1.7 but that had been working in the homebrew formula until recently.

**Comment by bcardiff** [comment]
Thanks for investigating. Due to the nature of the change I think that the best thing is to change the assert_built in yaml specs to allow optionally the `...\n` suffix.

**Comment by asterite** [comment]
I can tackle this

**Comment by straight-shoota** [comment]
This is caused by yaml/libyaml#18 which removes the erroneously inserted document end marker after a scalar in root context.
