### ISSUE TITLE
typeof(1_64) returns Int32

### ISSUE THREAD

**Issue by xqyww123** [crystal-lang/crystal#6290]
``` crystal
p typeof(1_64) # => Int32
p typeof(1_64) == Int64 # => false
p typeof(1_64) == Int32 # => true
```

I'm not sure if it occurs by optimaztion or it can produce any actual bug in production, but it's really abnormal.

``` sh
$ crystal -v
Crystal 0.24.2 [4f9ed8d03] (2018-03-08)

LLVM: 4.0.0
$ uname -a
Linux localhost 4.15.17-200.fc26.x86_64 #1 SMP Thu Apr 12 18:28:26 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

self compiled crystal :
``` sh
Using compiled compiler at `.build/crystal'
Crystal 0.24.2+1 [ef29deb29] (2018-06-20)

LLVM: 4.0.1
Default target: x86_64-unknown-linux-gnu
```
Bug still exists.

Updated to newest
``` sh
$ sudo dnf update
$ crystal -v
Crystal 0.25.0 [7fb783f7a] (2018-06-11)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```
Bug still exists.

------------- and more --------------

`1_u8, 1_u16, ... 1_u128` are correct, but `1_8, ... 1_128` are always `Int32`.

**Comment by z64** [comment]
`1_64` is not an `Int64` literal; it's the number `164`. Underscores are used to optionally separate place value, as in `1,000,000` can be represented as `1_000_000` for better visual grepping.

For other literal types, you write `iN`, as in `1i64`, etc:
```cr
p typeof(1i64) # => Int64
p typeof(1i64) == Int64 # => true
p typeof(1i64) == Int32 # => false
```
https://carc.in/#/r/4f6v

Some people may chose to stylize with `_` to separate the literal type descriptor.
