### ISSUE TITLE
Allow empty `case` without `when`

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#6318]
An empty `case` without `when` is currently a syntax error:

```cr
case "foo"
end # unexpected token: end (expecting when or else)

case "foo"
else # unexpected token: else (expecting when)
end
```
(the first syntax error even says `expecting when or else`, which would mean the second example should work. But it actually expects a `when`)

In regular code it certainly doesn't make much sense and is about as meaningful as `if true`. But it also doesn't do any harm to have a `case` without any `when` branch.

On the other hand, it comes in handy when the code for `when` branches is automatically generated (for example in a macro):

```cr
case foo
{% for case in cases %}
when {{ case.stringify }}
  # ...
{% end %}
end
```
If `cases` is empty, this macro will produce invalid code. It would require extra effort to handle this - and  it's ugly and hard to read. If more logic is involved, it might not be as simple as wrapping the entire `case` in `{% unless cases.empty? %}`.

**Comment by kostya** [comment]
example: https://github.com/crystal-lang/crystal/blob/master/src/json/serialization.cr#L170

**Comment by asterite** [comment]
Sounds good. If anyone wants to implement this, please go ahead.

I think `case exp` without anything inside it should be normalized to just `exp`. If it has an `else` (but no `when`s) then it should be normalized to `exp; else_exp` using an `Expressions` node.

**Comment by mjago** [comment]
Case without when is and should be nonsensical - and doing it for macros sake is stupid
