### ISSUE TITLE
CylancePROTECT terminates crystal processes

### ISSUE THREAD

**Issue by Wanderfalke** [crystal-lang/crystal#6327]
Hi all,

I tried using crystal on my work MacBook Pro which has CylancePROTECT (enterprise endpoint security) installed. And it does not like crystal at all, always terminating due to `StackPivot` violation, e.g.:

```
Violation: StackPivot; 
PID: 20218; 
Application: /usr/local/Cellar/crystal/0.25.1/bin/crystal

```

Does anybody have an idea on how to resolve this issue (besides removing Cylance, obviously).

**Comment by bararchy** [comment]
Maybe it happened because of Fiber context switching? Does "Go" also raise this issue?

Also, can you show a code sample? Maybe its just a false positive and we should notify the AV vendor

**Comment by RX14** [comment]
Your options are to remove cylance or whitelist every crystal executable. It's not really sensible for us to work out and maintain compatibility with every antivirus program out there. Yes, crystal does change stacks and manage it's own stacks, but no there's no way around that. I suggest opening a bug with cylance.

**Comment by Wanderfalke** [comment]
@RX14 Thank you for your answer. I totally understand that there is nothing you can do about it. I guess I should have asked that question in google group instead of opening an issue.
