### ISSUE TITLE
API proposal Int32.from_str

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#6345]
A new API `from_str` on the Struct Int that would take a String and return an Int parsed from that String.
example: https://play.crystal-lang.org/#/r/4gp4

Reasons:
- This would be easier than having to do IO management yourself.
- 3rd party APIs and internal APIs often return strings that need to be converted.
- It seems more intuitive to call a method on the Struct `Int` then calling `to_i` on a variable.

**Comment by Exilor** [comment]
> It seems more intuitive to call a method on the Struct Int then calling to_i on a variable.

https://play.crystal-lang.org/#/r/4gpd

**Comment by wontruefree** [comment]
I missed this in the api docs. That is way better then what I thought
