### ISSUE TITLE
HTTP response with content-type `text/html; charset="utf-8"` breaks HTTP::Client

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#6353]
It seems Facebook's response has:

```
text/html; charset="utf-8"
```

as the content-type header. We are not removing the quotes, which seem to be valid (there are tons of RFCs for this, but they do appear in https://tools.ietf.org/html/rfc7231

Let's fix this by checking if there are quotes.

**Comment by BenDietze** [comment]
@asterite this is:

https://tools.ietf.org/html/rfc7231#section-3.1.1

...
   A parameter value that matches the token production can be
   transmitted either as a token or within a quoted-string.  The quoted
   and unquoted values are equivalent.  For example, the following
   examples are all equivalent, but the first is preferred for
   consistency:

     text/html;charset=utf-8
     text/html;charset=UTF-8
     Text/HTML;Charset="utf-8"
     text/html; charset="utf-8"

   Internet media types ought to be registered with IANA according to
   the procedures defined in [BCP13].

      Note: Unlike some similar constructs in other header fields, media
      type parameters do not allow whitespace (even "bad" whitespace)
      around the "=" character.

**Comment by straight-shoota** [comment]
We need a proper implementation of MIME media type parser. It's not just quoted values but a lot of other aspects that are currently not handled correctly.

I have a local branch with a sophisticated parser and a ton of specs just waiting for #5765 to be merged.
