### ISSUE TITLE
Spec compilation failure (read before assignment to local variable 'base')

### ISSUE THREAD

**Issue by myfreeweb** [crystal-lang/crystal#6372]
Weird compile error is happening when running specs with a Crystal that was built with LLVM **6.0.1** on FreeBSD:

```
in macro 'macro_1343766128' /usr/home/greg/crystal/spec/std/file_spec.cr:587, line 8:

   1.
   2.       it "converts a pathname to an absolute pathname, using ~ (home) as base (trailing /)" do                                                                                  
   3.         prev_home = home
   4.         begin
   5.           ENV["HOME"] = File.expand_path(datapath)
   6.           File.expand_path("~/").should eq(home)
   7.           File.expand_path("~/..badfilename").should eq(File.join(home, "..badfilename"))                                                                                       
>  8.           File.expand_path("..").should eq("/#{base.split('/')[0...-1].join('/')}".gsub(/\A\/\//, "/"))                                                                         
          
read before assignment to local variable 'base'
```

(`base` is a private function in the file, not a local variable)

/cc #5556

**Comment by felixbuenemann** [comment]
I'm also running into this on llvm 6.0.1 from Homebrew on macOS 10.13.5, will have to check with crystal compiled against llvm@5 (5.0.2).

I'll see if a full `make clean` helps, I only forced recompile of `llvm_ext.o` after switching from LLVM 5 to 6 because of patches required for 6.0.1.

**Comment by asterite** [comment]
The error message happens at the semantic stage, which has nothing to do with LLVM, so I really doubt it has anything to do with the LLVM version.

**Comment by felixbuenemann** [comment]
Yeah you are right, I'm also running into it when compiling with 5.0.2.

I also tried `make clean` and clearing out `.crystal` and `~/.cache/crystal` as well as using the precompiled 0.25.1 binaries for compilation and the error persisted.

**Comment by felixbuenemann** [comment]
The error goes away if I remove the wrapping `{% unless flag?(:win32) %}` macro.

**Comment by felixbuenemann** [comment]
Oh and compiling the file_spec standalone also works, but all_spec fails (make spec).

**Comment by straight-shoota** [comment]
I presume this has been resolved.
