### ISSUE TITLE
HTTP::Handler override Proc

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/crystal#6386]
While working on [this commit](https://github.com/luckyframework/lucky/pull/541), I noticed that [Proc](https://github.com/crystal-lang/crystal/blob/master/src/http/server/handler.cr#L32) is alias in HTTP::Handler. This caused an issue when I included this module in to a custom handler class, and I wanted to make a property of type `Proc`.

Using `property whatever : Proc(Other, Stuff, Here)` throws the error `Proc(Other, Nil) is not a generic type, it's a function`. To fix this, I have to add `::Proc(Other, Stuff, Here)`. The other thing was that the code led to [crashing](https://github.com/crystal-lang/crystal/issues/5656) the compiler.

My thought was that maybe if this alias is necessary, it could have a custom name like `HandlerProc` or something. If not, then I guess it could just be removed?

**Comment by asterite** [comment]
Yeah, maybe it can be renamed to something else.

**Comment by RX14** [comment]
@jwoertink just use `property whatever : Other, Stuff -> Here`.
