### ISSUE TITLE
Allow setting ssl context in WebSocket.new

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#6395]
Currently `WebSocket.new` only allows `Bool` for `tls:`, it should support setting a context like the HTTP::Client does.

**Comment by bararchy** [comment]
So... I know this might be an esoteric issue, but I'm sure I'm not the only one who needs to set specific TLS context for a WebSocket right? it should be quite easy to add I believe

@asterite maybe you can add it "on the way" while working on  #5600

**Comment by straight-shoota** [comment]
#5600 is an entirely different issue. Also, I don't think @asterite is working on that.

But PR's for adding this are welcome :+1:

**Comment by bararchy** [comment]
@straight-shoota I know it's different, it's just "if someone is already in this code section" ;) 
Anyhow, I'll see if I can use one of our devs to add this in :+1:

**Comment by asterite** [comment]
I'm not working on #5600 and I also fail to see the point of that.

**Comment by bararchy** [comment]
The point in having context passed to WebSocket?

**Comment by asterite** [comment]
No, the point of #5600

**Comment by bararchy** [comment]
Oh, I guess it's the same as TCPSocket, it "can" be async, but it doesn't have to be :man_shrugging:

**Comment by j8r** [comment]
We can already use a custom `OpenSSL::SSL::Context::Client`, but the typing isn't as explicit as the methods in `HTTP::Client`.
I tested it, can be closed.

**Comment by bararchy** [comment]
@j8r what's the API for doing that?

**Comment by Sija** [comment]
@bararchy I guess you can just pass `OpenSSL::SSL::Context::Client` instance to the `WebSocket.new` constructor.

**Comment by j8r** [comment]
@bararchy I was also trapped like you, I created an issue about the `tls` argument typing.
We can do `HTTP::WebSocket.new(host: "::1", path: "/", tls: OpenSSL::SSL::Context::Client.new)`

**Comment by bararchy** [comment]
@j8r Saw it, thanks :heart: I guess following the API examples got me confused.
