### ISSUE TITLE
Takes ages before function returns

### ISSUE THREAD

**Issue by pcoenen** [crystal-lang/crystal#6399]
Hello,

I got the following issue.

When my code is finished it takes ages before the method returns the result, although the result is already calculated. I checked this using print statements in the console.

I assume it has something to do with the size of the file I'm downloading, since the method returns fast for little files.

See my code in the zip file

[testing.zip](https://github.com/crystal-lang/crystal/files/2201156/testing.zip)

```
Crystal 0.24.2 [4f9ed8d03] (2018-03-08)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by jhass** [comment]
Hi!

We encourage the usage of StackOverflow for help with the language or programming problems in general and would like to keep this issue tracker for issues and specific feature requests related to the compiler and standard library. So please start a question over there :) Tipp: you'll get better help if people don't have to download anything ;)

Feel free to open a new issue if you could isolate a reproducible problem with the language, the code to reproduce should be as self contained and minimal as possible.
