### ISSUE TITLE
Feature request: Array.has_product?(val)

### ISSUE THREAD

**Issue by BlobCodes** [crystal-lang/crystal#6400]
I think it would be useful to have something like .has? / .has_value? / .has_product? for arrays.

**Comment by straight-shoota** [comment]
I'm not sure what `#has?` and `#has_product?`  are supposed to return, but `#has_value?` is available as [`Enumerable#includes?`](https://crystal-lang.org/api/0.25.1/Enumerable.html#includes%3F%28obj%29-instance-method).

**Comment by BlobCodes** [comment]
`#has_product?` should be the same as `#has_value?`, because there´s also `#each_product`

**Comment by konovod** [comment]
`#each_product` iterates over cartesian product of several arrays, it's not an alias for `#each`. So `has_product` doesn't make sense. 
Also, [aliases are discouraged in Crystal](https://github.com/crystal-lang/crystal/wiki/FAQ#why-are-aliases-discouraged), so if `#includes?` exists there is no need to add `has?` or `has_value?` if they have the same meaning.

**Comment by jhass** [comment]
What @konovod said, so closing. Feel free to continue the discussion if you feel misunderstood!
