### ISSUE TITLE
[Feature Request] Expand JSON::Field functionality

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#6406]
Currently when using `@[JSON::Field(ignore: true)]`, any property with that gets completely ignored when going to/from JSON.

I propose expanding the binary true/false values to (names are just examples):
* true - Ignore on both to/from JSON
* false - Allow on both to/from JSON
* deserialize - Only ignore property on deserializing from JSON
* serialize - Only ignore property on serializing to JSON

There are a few use cases I can think of for this.  For example:
* Use `ignore: "serialize"` on password field so it can still be consumed from front end API request but not returned.
* Use `ignore: "deserialize"` on when you want to use your own value vs one supplied in the JSON object.  

The other thought i had was when using `@[JSON::Field(key: "keyName")]`, that will completely override the key name on both serializing and deserializing.

My thought was to have a `value_key` or something, that will use that key to get the data from the JSON object, but maintain the object's property name when serializing to JSON. 

The use case for this could be, for example, consuming a third party JSON API into an object, while also transforming key names from their format to the format used internally all seamlessly in one step.

**Comment by jhass** [comment]
I can vaguely see the ignore usecase, but given the second one is better solved with separate mapping structs that can be converted to each other, I wonder whether that's not true for that case too, whether we should make it easier to have such conversions between two structs with a similar field set and whether the actually nice feature would be able to disallow either serialization or deserialization  for a specific mapping altogether.

**Comment by straight-shoota** [comment]
> consuming a third party JSON API into an object, while also transforming key names from their format to the format used internally all seamlessly in one step.

These are two completely different procedures and likely require more customization than just different property names. This makes no sense and as @jhass pointed out, keeping the API simple should be the highest priority. Additional complexity only increases itself over time.

**Comment by Blacksmoke16** [comment]
Yea, point taken.  The second case would only solve very simple cases.

The ignore case wouldn't be too difficult to implement from what i can tell.   Would just be adding one more logic statement to https://github.com/crystal-lang/crystal/blob/b782738fffb1b9fba98f7aa44f9da11c3da259a1/src/json/serialization.cr#L140 and similarly for the to_json one as well.

**Comment by Blacksmoke16** [comment]
I made a shard for this.  https://github.com/Blacksmoke16/CrSerializer
