### ISSUE TITLE
[Feature Request] Macro to check that type match to type

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#6409]
When you call method with some args it detect which method to call and match this argument to type or not (including direct type, unions types, aliases, and subclasses). Can we have macro to do this check manually?

example:
```crystal
def bla(a : T, b : U) forall T, U
  {% if T.match?(U) || U.match?(T) %}
    true
  {% else %}
    false
  {% end %}
end

bla 10, 10 # => true
bla "bla", :bla # => false
bla (10 || "bla"), (10 || :bla) # => true
...
```

**Comment by asterite** [comment]
Is it <?

**Comment by kostya** [comment]
yeah, this seems works nice.
