### ISSUE TITLE
Macro for class properties

### ISSUE THREAD

**Issue by reitzig** [crystal-lang/crystal#6430]
The `property` macro is useful but doesn't apply to class properties.

Please add a similar macro for class properties:

```crystal
macro class_property(name)
    @@{{name}} = false

    def self.{{name}}
        @@{{name}}
    end
  
    def self.{{name}}=(@@{{name}})
    end
end
```

And similar for `class_getter` and `class_setter`, I guess.

**Comment by bew** [comment]
Huh it's already there

**Comment by reitzig** [comment]
Uh... guess I should have tried it first? That's what you get for trusting the docs, which don't mention it.

**Comment by asterite** [comment]
This of a programming language as a language like English or Spanish. The book explains the grammar (how the language works), the API explains the vocabulary (classes and methods). It just makes no sense to document a big part of the API in the language docs.

**Comment by bew** [comment]
@reitzig you can also come to [Gitter](https://gitter.im/crystal-lang/crystal) or on IRC if you prefer.
