### ISSUE TITLE
Splatting a tuple in a macro argument

### ISSUE THREAD

**Issue by KCErb** [crystal-lang/crystal#6434]
play.crystal-lang.org:

https://play.crystal-lang.org/#/r/4kzn

Input

```crystal
enum Color
  Red
  Green
  Blue
end

Color.flags(*{Color::Red, Color::Blue})
```

Output

```
Error in line 7: macro didn't expand to a valid program, it expanded to:

================================================================================
--------------------------------------------------------------------------------
   1.     Color::*{Color::Red, Color::Blue}
--------------------------------------------------------------------------------
Syntax error in expanded macro: flags:1: expecting token 'CONST', not '*'

    Color::*{Color::Red, Color::Blue}
           ^

================================================================================
```

Am I missing something or is this unexpected behavior? The docs show variadic arguments used directly, not as a splatted tuple:

https://crystal-lang.org/docs/syntax_and_semantics/macros.html

**Comment by straight-shoota** [comment]
What's your usecase? Why not just write `Color::Red | Color::Blue` instead of a complicated macro expansion to get an argument for `Enum.flags`?

The reason why this does not work as you might expect is because macro arguments are passed verbatim as AST nodes. Splat arguments will not be deconstructed at call site, they're passed as `value` to the macro and then result in an invalid expression.

This can only work if the macro argument is expanded first, for example like this:

```cr
{% begin %}
Color.flags({{"Red, Blue".id}})
{% end %}
```

Also note that  `Enum.flags` expects the plain names of the constants without any namespace.

**Comment by KCErb** [comment]
I've got a property of my object (lets say Foo) which stores an array of other objects (lets say Bar). Each Bar has a "kind" enum (which is a flag enum for the purposes of this join).

With that setup, I can assign a flag to Foo by joining the flags on its Bars.

```crystal
bar_kinds = Foo.bars.map(&.kind) # array of Kind enum, like Kind::A, Kind::B etc
Foo.kind = Kind.flags(*bar_kinds)
```

(I know that I'd need to convert that map to return a tuple for the splat above to work, but I didn't get that far in my thinking since I wanted to test the syntax in the playground before I put it into my actual code.)

btw the answer I'm going with for now is to use `reduce` and the `|` operator and that's just fine by me. But perhaps there's a right place in the docs to explain that macros can take variadic arguments but can't splat for the reasons discussed here.

**Comment by straight-shoota** [comment]
You can't use runtime variables as macro arguments, either. So your example code with `Kind.flags(*bar_kinds)` can't work, ever.

Using `reduce` with `|` is probably the best solution.

**Comment by KCErb** [comment]
I see, good point. Well, I'll go ahead and close this then. I see the cohesive sense of not supporting splat when it's explained like this. Thank you!
