### ISSUE TITLE
Forcing use of UInt32 in simple formula gives compiler error

### ISSUE THREAD

**Issue by cfsamson** [crystal-lang/crystal#6443]
Let me start off by saying i just love Crystal, I have read all documentation and feel I understand the basics. But then this happened. I try to use unsigned integer in a simple fibonacchi calculation like this

```
def fibonacchi(n : UInt32) : UInt32
  if n == 0
  elsif n == 1
    return 0
  elsif n == 2
    return 1
  else
    return fibonacchi(n - 1).as(UInt32) + fibonacchi(n - 2).as(UInt32)
  end
  return 0
end

n = 45_u32
res = fibonacchi(n)
puts res
```

I have also tried:

```
n = 45.as(UInt32)
```

If i `puts typeof(n)` it shows the type as "UInt32"

However, when i compile I get this error:
<img width="383" alt="skjermbilde 2018-07-25 kl 14 15 08" src="https://user-images.githubusercontent.com/8337848/43201333-7b0eb448-9018-11e8-9546-88c8491ed2fd.png">

I know i have a lot of unnecessary type-declarations, but I put them on to try localize where the error came from.

OS: macOS 10.13.6
Compiler version: crystal 0.25.1 LLVM: 5.0.2

**Comment by asterite** [comment]
return 0_u32
return 1_u32

**Comment by ysbaddaden** [comment]
**This is a question for stackoverflow, not a language bug.**

Your issue is that you return 0 and 1 that are Int32 by default, you must specify them as UInt32:
```crystal
def fib(n : UInt32) : UInt32
  case n
  when 0, 1
    0_u32
  when 2
    1_u32
  else
    fib(n - 1) + fib(n - 2)
  end
end

p fib(45)
```

**Comment by straight-shoota** [comment]
And `#as(UInt32)` won't convert from Int32 to UInt32. It will just treat the value as if it was a `UInt32` which is highly unsafe. A proper type conversion is performed by `#to_u32`.

**Comment by cfsamson** [comment]
Thanks guys, I know maybe in retrospect this should have gone to SO, sorry for that. But thanks for the quick reply. That was indeed the fault in my code.

**Comment by RX14** [comment]
@straight-shoota actually `Int32#as(UInt32)` won't even compile.
