### ISSUE TITLE
Union.nilable? doesn't work correctly for alias

### ISSUE THREAD

**Issue by delef** [crystal-lang/crystal#6447]
```crystal
alias SomeType = Array(SomeType)?

p SomeType.nilable? # => false
p Array(SomeType)?.nilable? # => true
```
https://carc.in/#/r/4moq

```
Crystal 0.25.1 (2018-06-30)

LLVM: 5.0.2
Default target: x86_64-apple-macosx
```

**Comment by straight-shoota** [comment]
So it's an issue with recursive aliases again :/

**Comment by yxhuvud** [comment]
@straight-shoota Yes, there is a missing example of just a alias to a generic, but that actually works (which surprised me a little, as I've had some nasty issues with generic aliases)

```
alias B = Array(Int32)?
puts B.nilable? # => true
```

**Comment by HertzDevil** [comment]
A correct definition of `#nilable?` would simply be:

```crystal
class Class
  def nilable? : Bool
    {{ @type >= ::Nil }}
  end
end

# definition in Union not needed

alias Foo = Array(Foo)?

Nil.nilable?         # => true
Int32.nilable?       # => false
Int32?.nilable?      # => true
NoReturn.nilable?    # => false
Foo.nilable?         # => true
Array(Foo)?.nilable? # => true
```

Under this new definition we would also have:

```crystal
Value.nilable?  # => true
Object.nilable? # => true
```

Currently they aren't nilable, but since `nil` is indeed a `Value`, it makes sense that they should be considered nilable. The impact of such a change would be very small because `Value` and `Object` cannot be used as types of a variable or as generic type arguments yet (not even forming the union type `Value?`).

**Comment by straight-shoota** [comment]
Yeah this should represent the nil type hierarchy correctly (`nil.is_a?(Value) # => true`).

However I'd like to mention that while `Object` and `Value` being implicitly nilable is technically correct, it does not seem very intuitive. The fact that `Nil` inherits from `Value` is an implementation detail. So maybe we should reconsider this at some point. As long as `Object` and `Value` can't be used in unions, it doesn't have any practical significance though.

**Comment by HertzDevil** [comment]
I don't think `Nil < Value` is a mere implementation detail, and we should normatively define it as such. I don't see any compelling reasons to give it a different or no superclass yet (like `Void`).

**Comment by HertzDevil** [comment]
Actually, the recursive union is already nilable if the macro method `TypeNode#nilable?` is used instead:

```crystal
alias SomeType = Array(SomeType)?
{{ SomeType.nilable? }} # => true
```
