### ISSUE TITLE
Wrong type error

### ISSUE THREAD

**Issue by pcoenen** [crystal-lang/crystal#6456]
Hello,

Can it be that there is an error in the crystal compiler error messages?

![image](https://user-images.githubusercontent.com/17742895/43317959-428a451e-919f-11e8-9fd4-25d2475eb5dc.png)

It has to be (String | Nil) and not the other way arround

**Comment by pcoenen** [comment]
It has to be (String | Nil) and not the other way arround

**Comment by j8r** [comment]
No, you have `return nil` and `return "hello"`, so the return type is `String | Nil`
The issue can be closed.

**Comment by pcoenen** [comment]
Yes, thats true, but thé error message of thé compiler is wrong, the compiler says that it has to be String instead of String | Nil

**Comment by j8r** [comment]
The compiler is correct here, the return type of the method `hello` is specially enforced to `String`. The code **must** return the same return type, else a message like this will raise. This annotation is made for humans.
You can remove it if you don't want to enforce it.

**Comment by pcoenen** [comment]
The compiler says 

> type must be String, not (String | Nil) 

But we all know that the type has to be `(String | Nil) ` instead of `String`

**Comment by j8r** [comment]
The message suggest you may have done wrong on you code to have a different return type.
Changing it the other way around will mean you have put a wrong annotation, which has no sense because it's optional.

**Comment by pcoenen** [comment]
Oh okay, I thought that the message meant that I had to change the return type of the function, but it means I have to change the return value

**Comment by j8r** [comment]
The purpose of it is mainly for API documentation about the return types (because there is already a type inference). Just code and add the return type if you want, to help you and others, and ensure the return type will don't change in case of a mistake :smile:
