### ISSUE TITLE
Fiber local / Thread local ?

### ISSUE THREAD

**Issue by xqyww123** [crystal-lang/crystal#6472]
Ruby have [`thread_local`](https://ruby-doc.org/core-2.5.1/Thread.html#method-i-thread_variable_get), as well as C, Java, Rust, Python and many others but Go and maybe some others.

Here is a situation require `fiber_local`:

```
class MyContext
#...
end
fiber_local current_context
def do_something_with_context(&block)
    current_context = # ...
    yield
    current_context = nil
end
```

Of course `with ... yield` is a way to do this, but for more complicated case:
``` crystal
do_something_with_context do
    a = MyClass.new
    a.do_some_require_contenxt
end
```
Here, `do_some_require_contenxt` can not get the context instance but send as an argument. It makes hundreds of methods must have a verbose argument `context`, at least in my code.

Just like global variable, I think `fiber local` have the same significance.

And just a hash in the `Fiber` and related instance methods could implenment this. For the consideration of the performance, compilation-time defined `NamedTuple` may be better. But `thread local` is always slow in most of lanugage, no mater how it's implenmented -- even in C it's a performance problem -- so if it cannot be fast but have a necessary reason to exist, we could never solve the performance. In fact, I think it should only be used in performance-non-sensitive case, where a Hash is enough, and even a SortedArray for less memoy usage.

I would be willing to contribute code if the feature were accepted.

**Comment by RX14** [comment]
@xqyww123 fork unshares all the memory so *everything* will be independent after a fork.

**Comment by xqyww123** [comment]
@RX14 but fiber. I mean create a new thread or fiber but process.

**Comment by asterite** [comment]
@xqyww123 You can reopen Fiber and add instance variables to it, to get fiber-local variables.

**Comment by ysbaddaden** [comment]
I'm interested in fiber locals sometimes, but either a `Hash(Fiber, T)` (only some fibers need a value) or reopening `Fiber` (if most fibers will need it) has been enough.

**Comment by xqyww123** [comment]
Maybe, it's another `def_delegators`.
Yes, `Hash(Fiber, T)` in module could also prevent name confliction.
