### ISSUE TITLE
Compilation error when using generic

### ISSUE THREAD

**Issue by TsumiNa** [crystal-lang/crystal#6478]
I tried to run  *channel_select.cr* which is in the crystal/sample directory. Code like this:
```crystal
def generator(n : T) forall T
  channel = Channel(T).new
  spawn do
    loop do
      sleep n
      channel.send n
    end
  end
  channel
end

ch1 = generator(1)
ch2 = generator(1.5)
ch3 = generator(5)

loop do
  select
  when int = ch1.receive
    puts "Int: #{int}"
  when float = ch2.receive
    puts "Float: #{float}"
  when ch3.receive
    break
  end
end
```

When compile, got this error
```
Error in src/test.cr:16: instantiating 'generator(Int32)'

ch1 = generator(1)
      ^~~~~~~~~

in src/test.cr:5: undefined constant T

def generator(n : T)
```

So is this a error or just the syntax changed.

**Comment by asterite** [comment]
@TsumiNa Please provide the output of `crystal version`

**Comment by TsumiNa** [comment]
@asterite Here is it
```
Crystal 0.25.1 (2018-06-30)

LLVM: 5.0.2
Default target: x86_64-apple-macosx
```

**Comment by asterite** [comment]
Well, that code compiles for me. And from the error you get, it seems you changed the code from:

```crystal
def generator(n : T) forall T
```

to:

```crystal
def generator(n : T)
```

(note that `forall T` doesn't appear in the line where the error message is pointed)

So you probably modified that line and you got the error. Put back the `forall` and it will compile. Or just compile the plain sample without changes.

**Comment by TsumiNa** [comment]
@asterite  Thanks! Work like a charm. I will close this issue.
