### ISSUE TITLE
Object#puts

### ISSUE THREAD

**Issue by Willamin** [crystal-lang/crystal#6479]
A little background: I'm a big fan of Elixir's pipe operator and would love to see it in Crystal, but I totally understand that it's been decided against in favor of method chaining. However, I think the standard library is a little lacking in terms of method chain-ability. For example, I find myself wanting to reopen the `String` class to add a chain-able `puts` method; something like this:
```crystal
class String
  def puts
    puts(self)
  end
end
```

Because `puts` is in the top-level namespace, maybe it makes more sense to add a `puts` method to the `Object` class. I'd be more than happy to write up a Pull Request for this, but I thought it might warrant some discussion from other members of the community.

**Comment by straight-shoota** [comment]
Why would `foo.puts` be any improvement over `puts foo`?

`puts` is also a common method on any IO type and `foo.puts` would mean printing an empty line to the IO. So this proposal would add unnecessary ambiguity.

**Comment by Willamin** [comment]
> Why would foo.puts be any improvement over puts foo?

Adding a `puts` method (or some other name) to all objects would make method chains more readable. Here's a trivial example:
```crystal
# This way doesn't preserve the flow of data. 
puts "hello"
  .upcase
  .reverse

# This way does preserve the flow
"hello"
  .upcase
  .reverse
  .puts

# This can currently be accomplished with tap, but it's extra cumbersome
"hello"
  .upcase
  .reverse
  .tap { |x| puts x }
```


> `puts` is also a common method on any IO type

Oh! You're totally right. That slipped my mind. I suppose naming it something else wouldn't make much sense. What if instead of being on `Object`, it was just on `String`? That way the method chaining can still happen, it would just require a `to_s` to be in between.

>  along the lines of refinements

Whoa, I didn't know refinements existed! That's a pretty neat way to handle monkey patching without breaking things. Has there been any consideration for Crystal to have refinement capabilities?

>  that implementation wouldn't be chainable anyway 

Right! In my real world usage of this that I've found, I end up not needing to chain past outputting the string, so I never end up returning `self`. If this was going to end up in the standard library, I think returning `self` like in your sample would be a good idea.

**Comment by asterite** [comment]
puts makes no sense for chaining purposes because it's always the last element in the chain.

You can of course continue discussing this specific topic for years, but it's not going to happen.

**Comment by Willamin** [comment]
> we try to avoid multiple ways of doing things in Crystal

That makes a lot of sense. I'll go ahead and close this issue.

> You can always monkey patch it in your projects

The main reason I wouldn't want to do this is because it affects the global namespace that other shards might use. If we had something like Ruby's refinements, that wouldn't be a problem. (That's a totally different issue though :smile: )
