### ISSUE TITLE
Error in initializing a class variable with a StaticArray

### ISSUE THREAD

**Issue by 0x10001** [crystal-lang/crystal#6486]
The following code produces an error: 
```crystal
class Test
  @@sa = StaticArray[1_u8, 2_u8, 3_u8]
end
# can't use StaticArray(T, N) as the type of class variable @@sa of Test, use a more specific type
```

And then I tried to add a type declaration after the class variable:
```crystal
class Test
  @@sa : StaticArray(UInt8, 3) = StaticArray[1_u8, 2_u8, 3_u8]
end
# macro '[]' must be defined before this point but is defined later
```

I had to write this, which looks good to the compiler:
```crystal
class Test
  @@sa : StaticArray(UInt8, 3) = init_sa
  private def self.init_sa
    StaticArray[1_u8, 2_u8, 3_u8]
  end
end
```

Perhaps this is not a bug. I'm not sure about this.
Wishing for explanation. Thanks. :)

**Comment by littlefisher** [comment]
I was running the codes with Crystal 0.25.1

**Comment by straight-shoota** [comment]
Reduced the second sample:
```cr
typeof(StaticArray[1_u8, 2_u8, 3_u8]) # macro '[]' must be defined before this point but is defined later
```

**Comment by asterite** [comment]
The initializers and the `typeof` example are all different bugs (which are related)

**Comment by jhass** [comment]
The first example now errors with being unable to infer the type of the instance variable, which is a bit inconvenient but makes sense since it's a method call.

The second and third example pass now.

The fourth example still gives the same error but maybe makes sense to track in its own issue and close this one?
