### ISSUE TITLE
Cannot annotate some methods returning constant-dependant objects?

### ISSUE THREAD

**Issue by dawkot** [crystal-lang/crystal#6502]
```crystal
struct MyStaticArray(T, N)
    def initialize(@arr : StaticArray(T, N))
    end

    def myFunc#: MyStaticArray(T, N) <- "private constant 3 referenced" error when uncommented
        self
    end
end

x = MyStaticArray.new(StaticArray [1, 2, 3])
puts x.myFunc()
```

**Comment by straight-shoota** [comment]
This is likely an issue with the special generic argument for `StaticArray` being numeric.

You can use `def myFunc : self` as a workaround.

**Comment by asterite** [comment]
This got broken by https://github.com/crystal-lang/crystal/pull/3972

I don't know why but some code I wrote got commented in that commit, probably an accident.
