### ISSUE TITLE
Allow logical AND for calls on implicit objects inside case branches

### ISSUE THREAD

**Issue by dawkot** [crystal-lang/crystal#6520]
It's a little weird that logical OR is allowed but AND isn't
```crystal
case 0
when .zero? && .even? then nil # not supported
when .zero?, .even? then nil # supported
end
```

**Comment by asterite** [comment]
It was actually a mistake to have the implicit call notation, because it's not composable.

**Comment by straight-shoota** [comment]
It's still useful, isn't it?

**Comment by asterite** [comment]
I prefer to remove half baked features that can never be complete.

In Ruby this doesn't exist for a good reason: that's not a complete expression. In Ruby you can compose things so nice, for example allowing splat in when, or in rescue. And it works because everything is an expression.

**Comment by asterite** [comment]
Actually, it's fine like that. If you want to use AND you can use an `if`, it's not a big deal, really. Even in the example above `.zero? && .even?` doesn't make much sense.

**Comment by asterite** [comment]
There's no real need for this, one can use `&&`. If one notation can't be used all over the place but there are alternatives, you can use the alternatives.
