### ISSUE TITLE
Compiler fails to catch invalid case statement that causes sigfault

### ISSUE THREAD

**Issue by cfsamson** [crystal-lang/crystal#6526]
By accident I typed an invalid case statement while showing Crystal to someone, and i feel the compiler should catch this error since it resulted in invalid memory access (and the example code snippet is one of the most used example snippets). Honestly I cant even understand exactly why it gives an invalid access either, there might be some obvious point I'm missing but the pattern is not that uncommon since using the case in the when statement is allowed in other languages like c# if my memory serves me right:
<img width="453" alt="skjermbilde 2018-08-12 kl 00 28 57" src="https://user-images.githubusercontent.com/8337848/43996661-b62c6180-9dc7-11e8-831c-4b3597e091e1.png">

**Comment by cfsamson** [comment]
I'll add it as text as well:

```
def fib(n)
  case n
  when n < 2; 0
  when 2; 1
  else
    fib(n - 1) + fib(n - 2)
  end
end

p fib(45)

```
$crystal --version
Using compiled compiler at `.build/crystal'
Crystal 0.26.0 [eeb53c506] (2018-08-10)

LLVM: 6.0.1
Default target: x86_64-apple-macosx
$crystal build fibonacchi.cr --release --no-debug
Using compiled compiler at `.build/crystal'
$./fibonacchi
Invalid memory access (signal 11) at address 0x7ffee5ceaff8
[0x109731f57] *CallStack::print_backtrace:Int32 +39
[0x109731dbe] __crystal_sigfault_handler +46
[0x109732073] sigfault_handler +35
[0x7fff72b39f5a] _sigtramp +26
[0x109731df3] *fib<Int32>:Int32 +35
[0x109731df7] *fib<Int32>:Int32 +39 (262051 times)
[0x1097176ec] __crystal_main +4316
[0x10971a3aa] main +202
$

**Comment by cfsamson** [comment]
I'll check it out, but I think the main cause of error is in both using "n" in the "case" statement AND referring to it in the "when" statement, let me explain the reasoning with some examples (watch the "n" in the case statement):

**This works as espected**
```
def fib(n)
  case n
  when 0; 0
  when 1; 0
  when 2; 1
  else
    fib(n - 1) + fib(n - 2)
  end
end

p fib(45)
```

**This also works as expected**

```
def fib(n)
  
  case 
  when n == 0; 0
  when n == 1; 0
  when n == 2; 1
  else
    fib(n - 1) + fib(n - 2)
  end
end

p fib(45)
```

**This ends up with sigfault**

```
def fib(n)
  
  case n
  when n == 0; 0
  when n == 1; 0
  when n == 2; 1
  else
    fib(n - 1) + fib(n - 2)
  end
end

p fib(45)
```

There is probably a reason for this, but if having "n" both in the _case_ statement and in the _when_ statement gives unexpected behavior I think the compiler should catch it or it shouldn't work differently like above...

**Comment by asterite** [comment]
The reason is `case` doesn't work as you expect it to. Curiously I explained it yesterday in another iasue: https://github.com/crystal-lang/crystal/issues/6519#issuecomment-412136752

**Comment by asterite** [comment]
Basically, `(n == 0) === n`, which is what the case is rewritten to, is always false.

**Comment by cfsamson** [comment]
Aha, ok, ok, I understand now. This makes sense now, it's just that I expected a compiler error. 

When I do the same in C# the compiler says: _Cannot implicitly convert type 'bool' to 'int'_ , but I guess Crystal case statement gives a bit more freedom in what to match so I like that, just not used to it 👍

**Comment by cfsamson** [comment]
I'll close this then .
