### ISSUE TITLE
Compiler not smart enough to infer a type variable

### ISSUE THREAD

**Issue by dawkot** [crystal-lang/crystal#6543]
```crystal
class Matrix(N, M)
  
  def initialize
  end
  
  def *(other : Matrix(M, P)) : Matrix(N, P)
    Matrix(N, P).new
  end

end

m = Matrix(2, 2).new
m * m
```
>undefined constant P

I'd expect compiler to figure out that both P's are supposed to be of the same value

**Comment by asterite** [comment]
try adding `forall M, P` at the end of the method definition:

```
  def *(other : Matrix(M, P)) : Matrix(N, P) forall M, P
```

**Comment by dawkot** [comment]
Same error 🤔

**Comment by asterite** [comment]
It actually works with `forall` if you omit the return type. That's maybe a bug, not sure.

**Comment by asterite** [comment]
https://play.crystal-lang.org/#/r/4qy0

**Comment by straight-shoota** [comment]
Yeah, it looks that way. And it should only be `forall P` because `M` is already a generic argument.

**Comment by hugoabonizio** [comment]
And you're using `2` as type, you should use a type for N, M and P.

```crystal
class Matrix(N, M)
  
  def initialize
  end
  
  def *(other : Matrix(M, P)) : Matrix(N, P) forall M, N, P
    Matrix(N, P).new
  end

end

m = Matrix(Int32, Int32).new
m * m
```

https://carc.in/#/r/4qxv

**Comment by dawkot** [comment]
If you omit the return type it works without forall as well.

**Comment by hugoabonizio** [comment]
However, I suspect you are not using generics properly (though I don't know your use case).

```crystal
class Matrix(T)
  def initialize(@n : Int32, @m : Int32)
  end

  def *(other : Matrix(T))
    Matrix(T).new(@n, @m)
  end
end

m = Matrix(Int32).new(2, 2)
m * m
```

https://carc.in/#/r/4qz9

**Comment by straight-shoota** [comment]
@hugoabonizio `M` and `N` are not free variables, they're already specified in the generic type arguments and should properly resolve. Only `P` should be declared explicitly.

I suppose this is just another edge case where the specific implementation for generic type arg as integer is incomplete.

**Comment by straight-shoota** [comment]
Using integers as generic type arguments to define the dimensions of a matrix is completely legitimate. That's what they're made for.

**Comment by dawkot** [comment]
@hugoabonizio These are just compile-time variables. The main reason I'm using them is to prevent invalid operations at runtime.

**Comment by RX14** [comment]
A bug in error messages, this should error that the type variable could not be inferred:

```cr
def foo(in : Array(A)) : Array(P) forall A, P
  in
end

foo(Array(Int32).new)
```
https://carc.in/#/r/4rgo

A bug in numerical generics, this should infer `P`:
```cr
class Foo(A)
end

def foo(in : Foo(P)) : Foo(P) forall P
  in
end

# works
# foo(Foo(Int32).new)

# broken
foo(Foo(1).new)
```
https://carc.in/#/r/4rgp

**Comment by hugoabonizio** [comment]
> Using integers as generic type arguments to define the dimensions of a matrix is completely legitimate.

Really nice to know! We learn something new everyday :smile: 

```crystal
class Foo(A)
  def sum
    A + A
  end
end
puts Foo(1).new.sum
```
https://carc.in/#/r/4rgz

**Comment by straight-shoota** [comment]
The first example from https://github.com/crystal-lang/crystal/issues/6543#issuecomment-413845179 now errors correctly in 0.35.1:
```cr
def foo(a : Array(A)) : Array(P) forall A, P # Error: undefined constant P
  a
end

foo(Array(Int32).new)
```

The second one still doesn't infer P.

NOTE: The variable names in the examples need to be changed because `in` is interpreted as a keyword.

**Comment by asterite** [comment]
Could you specify which one is the second example?

**Comment by straight-shoota** [comment]
```cr
class Foo(A)
end

def foo(a : Foo(P)) : Foo(P) forall P # Error: undefined constant P
  a
end

foo(Foo(1).new)
```

It works with `Foo(Int32).new` in the last line.
