### ISSUE TITLE
Ruby or Crystal - which language should I learn first? 

### ISSUE THREAD

**Issue by AngeloChecked** [crystal-lang/crystal#6544]
Hello everyone!

I'm a student and i'm very curious about Ruby and Cristal!

I have a question:
Do you advise me to learn Crystall right away or to start with ruby?

**Comment by straight-shoota** [comment]
This is an issue tracker for developing the Crystal compiler and stdlib. Please ask other questions on the mailing list or in chat. See https://crystal-lang.org/community/

**Comment by AngeloChecked** [comment]
i'm sorry, thank you.
