### ISSUE TITLE
Inconsistent type inferring for block arguments

### ISSUE THREAD

**Issue by dawkot** [crystal-lang/crystal#6546]
```crystal
xs = [] of Symbol
[{:a, :b}].each { |(a, b)| xs << a } # no error
[{:a, :b}].tap { |(a, b)| xs << a } # error
```

> Error in line 3: instantiating 'Array(Tuple(Symbol, Symbol))#tap()'
> 
> in line 3: instantiating 'Array(Tuple(Symbol, Symbol))#tap()'
> 
> in line 3: no overload matches 'Array(Symbol)#<<' with type Tuple(Symbol, Symbol)
> Overloads are:
>  - Array(T)#<<(value : T)

So, `|(a, b)|` seems to be interpreted as either tuple or array deconstruction depending on block argument's type (or the return type).

**Comment by asterite** [comment]
`tap` yields `self`, which is an array, not a tuple. The compiler is correct here.

**Comment by dawkot** [comment]
I don't get it. The only difference between the two is the returned value's type, both blocks are supposed to  accept arguments of the same types.
Isn't `tap` just a lazy `eager`?

**Comment by asterite** [comment]
No. each yields elements of an array. tap yields the entire object, in this case an array. Decomposition ends up calling array[0] and array[1]

**Comment by dawkot** [comment]
Ok, I see.

**Comment by Sija** [comment]
@dawkot It would be better If you spend some time with docs before opening a ton of invalid non-issues here... Thanks!

**Comment by asterite** [comment]
I also suggest asking questions on our IRC channel instead, and only report here if you are almost sure it's a bug
