### ISSUE TITLE
Compiler may not assume correct integer literal type from enclosing context

### ISSUE THREAD

**Issue by RomanHargrave** [crystal-lang/crystal#6558]
*Tested with Crystal 0.25.1 (the currently available version from the official debian repository)*

There exist situations where the compiler will not correctly determine the appropriate integer type to use for ambiguously specified integer literals (e.g. lacking the integer type suffix).

Take, for example, the following extension to `Slice`

```crystal
struct Slice(T)
   def zero!
      self.map! do |x|
         0
      end
   end
end
```

Because the compiler appears to assume ambiguous integers to be `Int32` when the type is unspecified (or in this case when it gets confused), `zero!` will compile (and therefore run) as expected when called on `Slice[1, 2, 3]` (since `Int32` is the default type); however, attempting to do the same with `Slice[1_u8, 2_u8, 3_u8]` will result in some rather misleading compiler errors regarding argument type compatibility for `Pointer#[]=` called within `Slice#map!`.

While this could supposedly be all good and well if there existed a means to 'blindly' _convert_ integer types at _compile time_, no such manner exists. While `0.cast(T)` may appear acceptable, it prohibits nearly any conversion - presumably on the basis that `Int32` and some other `Int` have different sizes. These leads me to believe that, In order to support each possible member type for `Slice(T)` one would have to specialize - by hand - `zero!` for each possible `T`, which seems absurd.

I assume that this misbehavior is brought about by inability to constrain the return type of a block, which would explain the compilers unwavering choice of `Int32`; however, I am not entirely privy to the existence, or lack thereof, of such an inability - and therefore may be entirely wrong in my diagnosis of the problem.

As an aside, I observed that the compiler refuses to allow casts between `Int32` and `UInt32` which, while I have no use for, i find amusing solely because the types should be compatible at memory level. Yes, I do realize that the sign bit would be treated as part of the value in the event that it were set, but one has to assume that if `#to(T)` is being used that the developer acknowledges it is now their responsibility to ensure the integrity of the resulting outcome.

**Comment by Sija** [comment]
> Yes, I do realize that the sign bit would be treated as part of the value in the event that it were set, but one has to assume that if #to(T) is being used that the developer acknowledges it is now their responsibility to ensure the integrity of the resulting outcome.

There is `Object#unsafe_as` existing specifically to cover such cases.

```cr
10.unsafe_as(UInt32) # => 10_u32
```

**Comment by asterite** [comment]
@Sija unsafe is the last resort. In fact, I'd like to say it's never a solution. In fact, it won't work well, I think, when trying to covert between types of different bit size. 

In this case there's a `new` method too: one can do `T.new(0)` where T is a numeric type. Of course `T. zero` works too, and it's implemented using that `new` method.

**Comment by RomanHargrave** [comment]
Thanks @Sija, though that brings up another question - does there exist manual type hinting?
