### ISSUE TITLE
Obscure error when using named argument with reserved name

### ISSUE THREAD

**Issue by oprypin** [crystal-lang/crystal#6559]
This used to work before Crystal 0.26

```crystal
class C
  def initialize(@abstract : Bool = false, *args, **kwargs)
  end
end

func = C.new(abstract: true)
```

But now it gives an error

```
Error in line 6: read before assignment to local variable '__temp_270'
```

https://carc.in/#/r/4ro0

Maybe it shouldn't have worked but this kind of error message will not suffice.

**Comment by oprypin** [comment]
This should work though

```crystal
def f(abstract fake : Bool = false, *args, **kwargs)
end

f(abstract: true)
```
```
Error in line 4: read before assignment to local variable '__temp_269'
```
https://carc.in/#/r/4ro1

**Comment by Sija** [comment]
Seems like a bug to me, IMO it should possible to use reserved keywords as ivar/property names.
