### ISSUE TITLE
Specs not outputting dots while running

### ISSUE THREAD

**Issue by bmulvihill** [crystal-lang/crystal#6561]
Looks like after updating to `0.26.0` the specs are no longer outputting dots while running (Only after completion).   I bisected and it looks like 6fc15ba47eb8b0c63087a21721a0556e52bbb3a3 caused this to break.  It was confirmed in Gitter that others are experiencing the same issue.

It appears https://github.com/crystal-lang/crystal/pull/6286/files#diff-1743af63147895659bc0e1ccdc6a7b75R29 this line is the root cause, since previously we used the top level `print` method which flushes the IO.

**Comment by asterite** [comment]
@bmulvihill Thanks for the research and the precise bug report 🙇
