### ISSUE TITLE
Extend Hash-like and Array-like literals to constructors other than `initialize`

### ISSUE THREAD

**Issue by dawkot** [crystal-lang/crystal#6563]
Such that this code would be valid:
```crystal
class MyClass
  def self.my_constructor
  end
  
  def []=(a, b)
  end
end

MyClass.my_constructor{:a => :a}
```

**Comment by asterite** [comment]
Use case?

By the way, this is almost possible to do with macros, except that for a hash you would need to add parentheses.

**Comment by asterite** [comment]
You could always define `Heap::Min.new` to just call that `Heap.min`, and then you could do `Heap::Min{...}`.

**Comment by straight-shoota** [comment]
> this is almost possible to do with macros

It's even possible without macros. A class method should also work (depending on use case).

**Comment by straight-shoota** [comment]
Related to #5703

**Comment by RX14** [comment]
I don't think we need this feature, with the workaround ary said above

**Comment by asterite** [comment]
Closing because this is not essential to the language, and the way provided above works fine.
