### ISSUE TITLE
Formatter add newlines after comments following a `when then` including a semicolon

### ISSUE THREAD

**Issue by j8r** [crystal-lang/crystal#6566]
The formatter adds one line and then another one line after comments following a `when then` that includes a semicolon.
```crystal
case 0
when 0 then 1; 2
# Comments
end
```
will format firstly to
```crystal
case 0
when 0 then 1; 2
# Comments

end
```
and then reformat again to
```crystal
case 0
when 0 then 1; 2
# Comments


end
```

**Comment by RX14** [comment]
Should that even compile?
```cr
case x
when 0 then 1
  2
end
```

doesn't make sense to me.

**Comment by j8r** [comment]
It doesn't have less sense than #6367 . I have put here integers to reduce the problem, but it can be anything else. I use a big `case` with quite a lot of `when`s, that have small operations to do for each.
```crystal
case var
# This do things
when "a" then dosome; puts "done"
# This do other
when "test" then other; puts "also done"
# to continue...
end
```

**Comment by j8r** [comment]
I don't get @Sija, what's incomprehensible? Each `when` do 2 operations.

**Comment by j8r** [comment]
The actual code is https://github.com/DFabric/dppm/blob/master/src/dppm/cmd.cr . Its clearer on a single line, because they are similar, and also most in term of size (so we can see "columns")

**Comment by straight-shoota** [comment]
It doesn't matter if there is a real use case and if that is better than it's alternatives.

A semicolon should always be usable to delimit an expression, as an alternative for a line break. This should just work an the same line as `when ... then`. It would be inconsistent and very awkward if this was a syntax error. 

This just needs a fix in the formatter.

**Comment by asterite** [comment]
What about `begin`? Do you forbid it? I think restricting this is unnecessary complexity in the compiler.
