### ISSUE TITLE
puts, p! methods raise compile error when  omit the parenthesis

### ISSUE THREAD

**Issue by TsumiNa** [crystal-lang/crystal#6573]
Do something like this will get a compile error. https://play.crystal-lang.org/#/r/4s6z
```crystal
p {1, 2}

#=> Syntax error in eval:1: unexpected token: ,Syntax error
```
Use parenthesis can fix it
```crystal
p ({1, 2})

#=> {1, 2}
```

I'm not sure, but seems like a bug.

**Comment by asterite** [comment]
No, this is how the language works. `{` after an identifier means passing a block to a method.

Duplicate of https://github.com/crystal-lang/crystal/issues/4826 (and probably of many others).

**Comment by asterite** [comment]
Duplicate of https://github.com/crystal-lang/crystal/issues/2746
Duplicate of https://github.com/crystal-lang/crystal/issues/1051

**Comment by TsumiNa** [comment]
@asterite Clear enough! Thanks.
