### ISSUE TITLE
Resolve Generics in macros

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#6576]
Original question: https://stackoverflow.com/questions/51903596/how-to-resolve-generics-in-macros

My usecase is getting full paths of reference properties to use it outside of the scope, e.g:

```crystal
class MyProject::Models::Post
  propery user : User
end

class MyProject::Models::User
  property posts : Array(Post) # This
end
```

The property `posts` could be used later outside `MyProject::Models` namespace (e.g., to use in Query builders in ORMs), therefore, a full path is needed to be known at the compile time. Despite of `user : User` resolving normally, `posts : Array(Post)` cannot be resolved because it's a `Generic`. It's not a consistent behavior IMO.

I currently use such monster in [core](https://github.com/vladfaust/core):

```crystal
type: (if _type.is_a?(Generic)
   if ("#{_type.name.resolve}" == "Array(T)")
     _type.name.resolve.stringify.gsub(/\([\w, ]+\)/, "(" + _type.type_vars.map do |v|
       v.resolve.stringify
     end.join(", ") + ")").id
   else
     _type
   end
 else
   _type.resolve # Why not just using .resolve on Generics? :(
 end)
```

But it could only resolve one level arrays and it's awful.

**Comment by asterite** [comment]
Why do you need to resolve it?

**Comment by vladfaust** [comment]
Okay, I haven't commented yet because I wanted to start rewriting Core, which needs custom resolve hacks for `Core::Query` to work properly at the moment, but may not need after the rewrite. However, I haven't started it yet, so the issue isn't relevant right now.

But. Even if there is no hurry in `Generic.resolve` for now for me, it feels like an unconsistent behaviour. I, as a developer, expect any type to be resolvable. If a type isn't resolvable, which means a full path to it cannot be found, that's weird.
