### ISSUE TITLE
Error running spec

### ISSUE THREAD

**Issue by max-codeware** [crystal-lang/crystal#6579]
I got this error message running `crystal spec` on my project:

    execvp: No such file or directory (Errno)
         from /usr/share/crystal/src/process.cr:276:7 in 'initialize'
         from /usr/share/crystal/src/process.cr:209:3 in 'new'
         from /usr/share/crystal/src/process.cr:153:14 in 'run'
         from spec/LinCAS_spec.cr:5:9 in '->'
         from /usr/share/crystal/src/spec/methods.cr:255:3 in 'it'
         from spec/LinCAS_spec.cr:4:5 in '->'
         from /usr/share/crystal/src/spec/context.cr:255:3 in 'describe'
         from /usr/share/crystal/src/spec/methods.cr:16:5 in 'describe'
         from spec/LinCAS_spec.cr:3:1 in '__crystal_main'
         from /usr/share/crystal/src/crystal/main.cr:104:5 in 'main_user_code'
         from /usr/share/crystal/src/crystal/main.cr:93:7 in 'main'
         from /usr/share/crystal/src/crystal/main.cr:133:3 in 'main'
         from __libc_start_main
         from _start
         from ???

It seems a bug in the standard lib of crystal 0.26.0 (with 0.24.2 it worked), in particular in class `Process`.
Here is my code if necessary (cannot reduce it): https://github.com/LinCAS-lang/LinCAS/tree/feature/Python

**Comment by straight-shoota** [comment]
This looks like the command you're trying to execute does not exist. Are you sure `bin/lincas` exists relative to the current working directory?

If this doesn't solve the problem, please try to provide a minimized and reproducible example.

**Comment by max-codeware** [comment]
There was the executable, but probably it was corrupted. Rebuilding it the problem seemed to be resolved.
