### ISSUE TITLE
A bug with initialization and abstract classes, YAML.mapping and "include"

### ISSUE THREAD

**Issue by docelic** [crystal-lang/crystal#6580]
With @RX14's help, I put together the following minimal reproducible example using abstract classes, YAML.mapping and "include" which doesn't work, giving error:

"Error in line 20: this 'initialize' doesn't initialize instance variable '@foo' of Foo, with Bar < Foo, rendering it nilable"

Please note that this is not related to the way how abstract class variables are initialized (this example does it properly), but it has something to do with both YAML.mapping and "include" found in a subclass. (If either the YAML.mapping or "include" are removed, it works).

It is partly related to https://github.com/crystal-lang/crystal/issues/2827, but probably deserves a separate issue like I've done now.

Here's the code to reproduce:

https://carc.in/#/r/4rhr

```
require "yaml"

abstract struct Foo
  getter foo : String
  def initialize(@foo)
  end
end

module Baz
end

struct Bar < Foo
  YAML.mapping(
    foo: String
  )
 include Baz
  
 def initialize
  foo = ""
  super(foo)
 end
end

Bar.new 
```

What's at play here? (It happens with Crystal 0.26.0 as well.)

Thanks!

**Comment by kostya** [comment]
https://carc.in/#/r/4saz

**Comment by docelic** [comment]
Looks like @kostya provided a working example, and YAML.mapping is deprecated anyway. Closing this issue, thanks.
