### ISSUE TITLE
String::Builder#chomp! does not work

### ISSUE THREAD

**Issue by pkorotkov** [crystal-lang/crystal#6582]
* Just tried to use `String::Builder#chomp!` and observed an unexpected behavior.

Input:
```crystal
b = String::Builder.new
b << "a,b,c,"
puts b.chomp!(44).to_s
```
Expected Output:
```
a,b,c
```
Actual Output:
```
```
* Link to the [crystal play](https://play.crystal-lang.org/#/r/4seo)
* Crystal Version: 0.26.0

**Comment by asterite** [comment]
Not really a bug, `chomp!` doesn't return `self`. This works:

```crystal
b = String::Builder.new
b << "a,b,c,"
b.chomp!(44)
p b.to_s
```

By the way, you shouldn't use `String::Builder`, you should use `String.build`. And also, `String::Builder` is mostly an internal class, `chomp!` and `back` are secret methods, we should mark the entire class as `:nodoc`: and just document that `String.build` yields an `IO` to the block. `String::Builder` is **unsafe**`.

**Comment by asterite** [comment]
Oh, actually, I just checked it and it's not unsafe. It used to be unsafe but not anymore.

We could "fix" `chomp!` to return `self`, or just make it return `nil`.

**Comment by pkorotkov** [comment]
@asterite Thanks for a quick reply. Your "fix" fully matches my attitude.
Happy to make Crystal better!
