### ISSUE TITLE
Compiler tries wrong method when overloading with splatted enum

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#6623]
### https://carc.in/#/r/4upo

```crystal
enum Foo
  Bar
  Baz
end

def foo(*values : Foo)
  pp "one"
end

def foo(value : Foo, as _as : String)
  pp "two"
end

foo(:bar)
foo(:bar, :baz)
foo(:bar, as: "baz")
```

```
Error in line 16: no argument named 'as'
Matches are:
 - foo(value : Foo, as _as : String)
 - foo(*values : Foo) (trying this one)
```

However, if replace `Foo` with any other scalar type, say `Symbol`, output is OK:

```
"one"
"one"
"two"
```

**Comment by vladfaust** [comment]
The bug is serious: https://carc.in/#/r/50pl, https://carc.in/#/r/50pm

**Comment by asterite** [comment]
It seems #7747 fixes this (though in `master` I don't get the error saying "no argument named 'as'", as reported).

Please try it out with `master` or in the next release and reopen if it wasn't solved.
