### ISSUE TITLE
Playground: Array inference

### ISSUE THREAD

**Issue by HCLarsen** [crystal-lang/crystal#6625]
I was running this code in the playground, and it told me that I found a bug in the playground.

```
class Test
  property foo = [] of Int32
  
  def initialize(bar : Int32?)
    @foo = [bar] if bar
    puts @foo
  end
end

test = Test.new(nil)
test = Test.new(1)
```

The error was this:

> Exception
> 
> BUG: `typeof([bar])` at play:13:15 has no type
> 

I found this while researching a similar issue in a shard I'm writing, where I declared an instance variable with a default value of an empty array of Int32, and the compiler was treating the compile-time type as Array(Int32) | Nil.

**Comment by Sija** [comment]
What version of Crystal are you using?

**Comment by HCLarsen** [comment]
0.26.0.

**Comment by vlazar** [comment]
Checked all snippets in this issue. Gives no error in playground for me.

<details>
  <summary>Crystal 0.31.1 on MacOS</summary>

```
$ crystal --version
Crystal 0.31.1 (2019-10-02)

LLVM: 8.0.1
Default target: x86_64-apple-macosx
```
</details>

**Comment by asterite** [comment]
Indeed, seems to be working now. Maybe some fix to typeof.
