### ISSUE TITLE
No docs for constant if there's no method defined on the Top Level Namespace

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#6637]
When I generate docs for this:
```crystal
Constant = 123
```
and enter "Constant" in the search bar of the generated docs then I can find the constant and click on it:

![index.html](https://user-images.githubusercontent.com/35064754/44948237-5bf58580-ae1a-11e8-962a-1904b346e851.png)

but it leads me to an file not found error page.

I can also search for "Top Level Namespace" and click on it. But it also leads me to an file not found error page.

But when I now define a method in the `Top Level Namespace`:
```crystal
Constant = 123

def method
end
```
then it works and `Constant` and `Top Level Namespace` lead to the correct page instead of the file not found error page.

**Comment by asterite** [comment]
All of that works for me. I'm using Crystal 0.26.1 on a mac.

**Comment by asterite** [comment]
It even works in the current docs: https://crystal-lang.org/api . Try searching `STDOUT`, which is a constant, or `Top level namespace`, and clicking on those.

**Comment by r00ster91** [comment]
@asterite When you only define one constant, nothing else and generate the docs for it, is this what you see then?
![index.html](https://user-images.githubusercontent.com/35064754/44948993-a0881d80-ae28-11e8-9fb3-49b5d05d54a9.png)
and when you search for the constant and click on it, it leads you to the correct spot instead of file not found error page? At me it leads to file not found page.
Is it maybe because I'm doing this locally? With a "file:///" URL.

I'm using 0.26.1.

**Comment by asterite** [comment]
Ah, yes, it seems to not work well if the project is not the standard library for some reason...

**Comment by RX14** [comment]
@asterite in the stdlib, the top-level-namespace page is generated already

**Comment by straight-shoota** [comment]
A single constant at top level is included in `index.json` but no `toplevel.html` is generated. It seems to be an error in the generator that treats it as an empty top level.

**Comment by r00ster91** [comment]
There are also no docs for `macro`s defined on the Top-level unless there's at least one method on the Top-level.

**Comment by Blacksmoke16** [comment]
Also requires the method to be public, private or protected methods also cause it to not be created.
