### ISSUE TITLE
Increase Bitarray index from UInt32 to UInt64

### ISSUE THREAD

**Issue by jzakiya** [crystal-lang/crystal#6640]
This sorta|kinda ties in with https://github.com/crystal-lang/crystal/issues/6626.

I had been using ``Int8`` size byte arrays in my  Crystal ``primes-utils`` translation to use memory more efficiently than in Ruby.  I just replaced them using ``BitArrays``s, which turn out to be faster all around, and since they are more memory efficient, they let me process larger numbers.

However, they limit the size of numbers I can process (which didn't occur with ``Int8`` size arrays) to ``UInt32``s.  In other words, when I create the bitarrays like ``array = BitArray.new(limit)`` in my code, the variable ``limit`` has to be an ``Int32 | UInt32``, when before it was a ``Int64 | UInt64``.

This ties in with ``6626`` because ``UInt32`` allows only an index up to ``2^32 - 1 = 4,294,967,295`` bits.  But that's only a max of ``4,294,967,295 / 8 + 1 = 536,870,912`` bytes, or ~536MB, which is an extremely small memory limit when systems now start at 4|8 GB of memory (my current laptop has 16GB).

Upping the allowable index to a type ``UInt64`` provides a much more useful max memory limit.
``bits_max = 2^64 - 1 = 18,446,744,073,709,551,615``, which is
``bytes_max = bits_max / 8 + 1 = 2,305,843,009,213,693,952`` which is ~2,300,00 GB

Of course, I'm not going to ever create a bitarray this large, but I certainly want to be able to use more of my 16GB of memory for my bitarrays.

**Comment by asterite** [comment]
My advise here would be to create your own `BitArray` type, maybe `BitArray64`, and use that. It's not much code. I'm suggesting this because it does relates to #6626 and I doubt that's going to be solved soon.

**Comment by RX14** [comment]
I don't think this should relate to #6626. I don't think that array/string/bitarray/etc using `UInt64` for the size should relate to #6626. The sizes should just be 64bit on 32bit systems.

**Comment by j8r** [comment]
> BitArray is an array data structure that compactly stores bits

Is it possible to make it generic, a bit like `Array(T)`? I see `UInt32`s in the `initialize` but `size` is `Int32`.
(Note that an annotation is missing for `@size` in the `initialize`)

**Comment by straight-shoota** [comment]
> I'm not going to ever create a bitarray this large

Then why would it need a 64 bit size?

**Comment by jzakiya** [comment]
> Then why would it need a 64 bit size?

**The UInt32 index size is a severe restriction on the point of having bitarrays, which is to compactly use memory** (which most people probably use for primarily boolean operations). In my current application (translating my ``primes-utils`` gem from Ruby), as I pointed out, UInt32 limits bitarrays to using ~538MB of data to a bitarray.  I want to process numbers that can use 10-20 billion size bitarrays.  So the issue is not using the full 64-bit range, it's allowing me/users to access much larger arrays than currently allowed.  

A bitarray of  20B (20,000,000,000) bits takes up only 2.5 GB of memory, compared to 20 GB of memory using the next smallest array size, a UInt8.  I can go past the 32-bit limit now using UInt8 arrays, but I'm not efficiently using that memory, which is why I switched to using bitarrays.  And using bitarrays can allow my data to reside in cache memory, which increases performance too. Lot's of pluses here.

Currently I have 16GB of memory in my laptop.  In my next  laptop I'll probably have 32GB of memory (which I can have now if I spend the money to get). Remember when Bill Gates said 640KB was enough memory?

**Comment by straight-shoota** [comment]
Yeah, I'm completely with you that limitations of memory size should be beyond the 32-bit limit. I was just confused because you said you wouldn't use bit arrays that large but want them anyway.

However, I'm not sure there is a need for stdlib's `BitArray` to support a size of more than 32 bits. That's clearly a very specific use case and, as @asterite pointed out, you can easily write a custom implementation. It's not a primitive and completely self-contained. Stdlib's `BitArray` is only used in the compiler, so it shouldn't matter if your application uses the stdlib implementation or a custom one.

**Comment by jzakiya** [comment]
>  as @asterite pointed out, you can easily write a custom implementation.

I could use this now.  Can you explain how to do this?

**Comment by straight-shoota** [comment]
Essentially just copy `bit_array.cr` to your codebase, rename the type to `BitArray64` or put it in your namespace. Then just change all 32 bit types and constants to 64 bit. That should essentially do it. Maybe `[](start, end)` might need some further adjustments.

**Comment by miketheman** [comment]
#codetriage 
Trying to summarize the concept here.

There appears to be resistance to adding the concept of a 64-bit BitArray to the codebase.

Creating a custom BitArray type to support 64-bits in the short term is relatively simple, and has been expressed here.

I'm guessing that if there are other compelling use cases that can be brought to light that should drive the need for a larger BitArray space, then they should be expressed and discussed.

Currently, recommending issue to be closed. It can definitely be re-opened if more details are brought to light.

**Comment by asterite** [comment]
Let's go with closing. The 64 bits thing is more general than this, and copying this file is simple.

**Comment by marghidanu** [comment]
Could really use a UInt64 based BitArray right now...
