### ISSUE TITLE
Enums aren't resolved from Symbol arguments on delegation

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#6645]
```crystal
struct Foo
  enum Bar
    Baz
  end

  def foo(bar : Bar)
    pp! bar
  end
end

struct Qux
  def foo(*args, **nargs)
    Foo.new.foo(*args, **nargs)
  end
end

Qux.new.foo(:baz)
```

Results in:

```
Error in temp.cr:17: instantiating 'Qux#foo(Symbol)'

Qux.new.foo(:baz)
        ^~~

in temp.cr:13: no overload matches 'Foo#foo' with type Symbol
Overloads are:
 - Foo#foo(bar : Bar)

    Foo.new.foo(*args, **nargs)
            ^~~
```

I guess that's because multi-step compilation, however, I assume it's an unexpected behavior.

**Comment by asterite** [comment]
Not a bug. There's no type restriction on the method that delegates for that to work.

**Comment by vladfaust** [comment]
I totally understand that. However, I'm looking from a perspective or a developer who doesn't dig too much into the compiler and doesn't know what we know. 

He expects `:bar` to be treated as `Foo::Bar` and it usually works; `delegate` is understood as "just pass the method to".

And it would confusing for him when `:bar` is treated as `Symbol` in this case.

I suggest either to somehow make it work or to improve the error message to be less confusing. To close the issue if it's not such, of course.

**Comment by RX14** [comment]
I think `delegate` is especially an anti-pattern since it doesn't copy or add documentation, and the args don't show up nicely in the docs.

**Comment by Sija** [comment]
Impl. is lacking things you mentioned, that's annoying - especially considering the docs - true, but the concept I find useful, what are other/better solutions to delegation you see?

**Comment by RX14** [comment]
@Sija try to avoid it if possible, else just manually forward the arguments.

**Comment by Sija** [comment]
@RX14 avoidance is not a solution and manually forwarding arguments is tedious, especially for big amount of methods. [Delegation](https://en.wikipedia.org/wiki/Delegation_pattern) is known pattern in OOP, present in other languages too, so it seems to me your objections are more of a personal nature.

**Comment by vladfaust** [comment]
This issue can be closed, because in my case it will be fixed by https://github.com/crystal-lang/crystal/issues/6655. However, I'd like to open a separate issue to discuss type restriction forwarding.
