### ISSUE TITLE
HTTP::Cookie::Parser not parsing headers properly

### ISSUE THREAD

**Issue by edwardloveall** [crystal-lang/crystal#6647]
```
Crystal 0.26.1 (2018-08-27)
LLVM: 6.0.1
Default target: x86_64-apple-macosx
```

It seems that the Cookie parser isn't parsing the `Set-Cookie` header correctly. Here's a minimal example

```crystal
cookie = HTTP::Cookie.new(name: "cookie", value: "value", expires: 1.year.from_now)
header = cookie.to_set_cookie_header
HTTP::Cookie::Parser.parse_cookies(header)
```

The result of line 3 should produce the same cookie as created in line 1. Instead the parser creates 3 cookies:
* One with the original name and value
* One with the name of "path"
* One with the name of "expires" and the value of the abbreviated weekday (`Mon`, `Fri`, etc)

**Comment by Sija** [comment]
@edwardloveall That's not a bug. I think there's bit of a confusion between what's `Set-Cookie` header and a `Cookie` header.

`to_set_cookie_header` as the name implies returns a string valid for (outgoing) `Set-Cookie` header, `parse_cookies` OTOH tries to parse what's in (incoming) `Cookie` header.

**Comment by edwardloveall** [comment]
Ah ha! Thank you so much for taking the time to explain this. I wasn't aware that they were different. I'll close this now. For posterity, here's my example but fixed with your suggestions:

```crystal
cookie = HTTP::Cookie.new(name: "cookie", value: "value", expires: 1.year.from_now)
header = cookie.to_set_cookie_header
HTTP::Cookie::Parser.parse_set_cookie(header)
```
