### ISSUE TITLE
Enum#parse argument restriction

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#6651]
Currently `Enum#parse` doesn't have argument restriction, and it calls `.camelcase` on the argument. If it's called with a type other than `String`, a error like `undefined method 'camelcase' for SomeType` would be raised. In my opinion, raising `no overload` error would make more sense.

https://github.com/crystal-lang/crystal/blob/391785249f66aaf5929b787b29810aeb4af0e1e8/src/enum.cr#L409-L420

**Comment by asterite** [comment]
Please send a PR to improve this :-)

**Comment by vladfaust** [comment]
Would this require to change specs? If so, I'd have to dig into them for such a small feature. IMO it would be better if handled by ones who know the project structure.

**Comment by asterite** [comment]
@vladfaust No, it's just adding ` : String` in that line.
