### ISSUE TITLE
Abstract enum constant

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#6652]
Consider this example:

```crystal
module Model
  abstract enum SelectableAttribute
end

class User
  include Model

  enum SelectableAttribute
    Id
    Name
  end
end

class Query(Model)
  def select(*attributes : Model::SelectableAttribute)
    "SELECT " + attributes.join(", ") { |a| a.to_s.underscore }
  end
end

Query(User).new.select(:id)
Query(User).new.select(:unknown_attribute) # Compile-time error
```

Such a DRY and type-safe code is not possible ATM without fat and ugly macros. Also enums aren't redefineable.

It's somehow related to #6645 I think.

**Comment by asterite** [comment]
Remove this line:

```crystal
  abstract enum SelectableAttribute
```

and it works fine.

And you should replace `Query(Model)` with `Query(T)`, otherwise it's confusing.

**Comment by vladfaust** [comment]
Hm, yes, you're right, it works with Generics. How about this:

```crystal
class User
  include Model

  def self.table
    "users"
  end

  enum SelectableAttribute
    Id
    Name
  end
end

class Repository
  def query(klass : Model.class, *selects : Model::SelectableAttribute)
    "SELECT " + klass.table + selects.join(", ") { |a| a.to_s.underscore }
  end
end

Repository.new.query(User, :id)
# undefined constant Model::SelectableAttribute
```

Yep, I know that the Repository could also be a Generic. However, it would increase code amount, as soon as a developer would need to create a Repository instance for each Model, which may be many.

**Comment by asterite** [comment]
You should be able to do something like:

```crystal
  def query(klass : T.class, *selects : T::SelectableAttribute) forall T
```

except that it doesn't work, there's probably a bug.

**Comment by vladfaust** [comment]
I can confirm that it doesn't work.

**Comment by vladfaust** [comment]
```crystal
class Dog
  Bar = "baz"
end

def foo(x : T::Bar) forall T
  pp! x
end

foo(Dog) # undefined constant T::Bar
```

Is that a bug?

**Comment by asterite** [comment]
The above code shouldn't compile (you `Dog::Bar` is a constant, not a type). But this should work:

```crystal
class Foo
  class Bar
  end
end

def foo(x : T.class, y : T::Bar) forall T
end

foo(Foo, Foo::Bar.new)
```

The bug is that a free variable (`T`) isn't looked up well when it's in the beginning of a path (`T::Bar`) in type restrictions.

**Comment by vladfaust** [comment]
Nice. It would help me a lot if this bug is fixed so I can restrict in outer types. You've narrowed the bug, so you should open a separate issue, right? This one can be closed, I guess.

**Comment by asterite** [comment]
Yes, please open a separate bug and close this one. I won't have time to fix this bug.
