### ISSUE TITLE
Abstract Enum

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#6653]
That would be useful:

```crystal
struct CustomEnum < Enum
  def custom_value
    value * 2
  end
end

enum Foo < CustomEnum
  Bar
end

Foo::Bar.custom_value

abstract struct AnotherCustomEnum < Enum
  abstract def qux
end

enum Quux < AnotherCustomEnum
  Baz

  def qux
    puts "#{value} qux"
  end
end
```

I'm aware of https://github.com/crystal-lang/crystal/issues/3592 and https://github.com/crystal-lang/crystal/issues/2787.

**Comment by RX14** [comment]
What's the usecase?

**Comment by miketheman** [comment]
#codetriage 
@vladfaust Can you add some details as to why this is useful?

**Comment by vladfaust** [comment]
@miketheman no, I don't think so :confused: It's just an idea, have no usecase ATM.

**Comment by j8r** [comment]
We need something concrete @vladfaust , your idea is too abstract for us 😄

**Comment by asterite** [comment]
If there's no use case I think we can close this.
