### ISSUE TITLE
Type restrictions forwarding

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#6656]
Extracted from https://github.com/crystal-lang/crystal/issues/6645

[Automatic casts](https://github.com/crystal-lang/crystal/pull/6074) is a very nice feature, it makes things much easier! However, it doesn't work when forwarding non-restricted arguments to a restricted method:

```crystal
def x(foo : Int64)
  pp! x
end

def y(foo)
  x(foo)
end

y(42)
```

```
no overload matches 'x' with type Int32
Overloads are:
 - x(foo : Int64)

  x(foo)
  ^
```

I'd like to see that forwarding working. WDYT?

**Comment by asterite** [comment]
To be clear, I don't think this will **ever** get fixed. It's simply not possible because of how the compiler and language works. So I'd like to close this issue.

**Comment by vladfaust** [comment]
Let's wait for others' opinions. I want to believe you're not the single one understanding what's going on such deep levels, and there is another magician knowing the way to fix this :100: :+1:

**Comment by bew** [comment]
I second @asterite on that, at least it probably won't ever get fixed to work the way you described it.
But maybe we can find some other ways to make it work?

Could we add a _method annotation_ like `@[ForwardArgs(foo)]`, and the compiler would know that foo's type has to be resolved to where it's used.

I'm just throwing an idea, I didn't put much thoughts about it, but maybe there's something good in it :smiley:

**Comment by straight-shoota** [comment]
Whats wrong with using `42_i64`?

**Comment by RX14** [comment]
Ary's right, this isn't how the feature is intended to work. In fact, I wouldn't want it to work this way because it would be too magic and have too many corner cases.
