### ISSUE TITLE
Proposal: add Channel.receive_first_with_index and Channel.send_first_index

### ISSUE THREAD

**Issue by joatca** [crystal-lang/crystal#6657]
`Channel.receive_first` and `Channel.send_first` discard the index returned by the underlying `Channel.select`. To handle cases where the channel that performed an operation is significant, I propose `Channel.receive_first_with_index` for receiving and either a new method `Channel.send_first_index` or returning the index directly from `Channel.send_first` and allowing using code to discard it. The discussion at https://github.com/crystal-lang/crystal-book/pull/279#pullrequestreview-151779970 suggests that `Channel.select` is intended as a low-level interface and that the `*_first` methods are considered the high-level interface.

Implementation of this should be trivial so I'm willing to submit a PR if everyone is agreeable.

**Comment by straight-shoota** [comment]
Duplicate of #10411
