### ISSUE TITLE
stale coroutine issue with Channels

### ISSUE THREAD

**Issue by PuerkitoBio** [crystal-lang/crystal#666]
I have an issue in a situation where I have a producer (main thread), n consumers (coroutines), and the n consumers are also producers for a separate consumer (other coroutine). They communicate via Channels.

The code looks like this:

```cr
    def run()
        # start the workers
        ch = Channel(String).new
        stop = Channel(Bool).new
        stop_matches = Channel(Bool).new
        matches = Channel(Match).new

        spawn process_matches(matches, stop_matches)
        WORKERS.times do |i|
            # those coroutines are also producers for process_matches
            spawn process_files(ch, stop, matches)
        end

        # producer for process_files
        process_dir(@dir, ch)

        WORKERS.times do |i|
            stop.send true
        end
        # different stop channel for process_matches, so it stops only
        # once all process_files workers are done.
        stop_matches.send true
    end
```

When `matches` is unbuffered (as it is in this code), and WORKERS is big enough (I had it fail with 3), I get "stale coroutine called" error from PCL. However, if `matches` is buffered to the number of WORKERS, it works fine (minus potentially missing queued messages when stop_matches is signaled).

It looks to me as a possible scheduler error, as whether or not the channel is buffered should not cause a stale coroutine issue. Spawned coroutines exit immediately once a stop signal is received, so those should not be re-scheduled after exit (which is apparently the reason for getting that error message):

```cr
        # the body of both process_matches and process_files is conceptually like this
        loop do
            case Channel.select(incoming, stop)
            when incoming
                m = incoming.receive
                # do stuff
            when stop
                stop.receive
                break
            end
        end
```

You can see the full code in https://github.com/PuerkitoBio/trouve (commit 5884edf82fd983639aa12923b162138ab277d116, file src/job.cr).

**Comment by jhass** [comment]
I ported your project to Crystal 0.17 and cannot reproduce your issue using it. Are there any changes with which you can reproduce still?

https://github.com/PuerkitoBio/trouve/pull/1

**Comment by PuerkitoBio** [comment]
Hello Jonne,

Thanks for the port, I haven't played much with it since then to be honest, so if you can't reproduce feel free to close the issue.

Thanks,
Martin
