### ISSUE TITLE
got "exec format error" when i  use --static

### ISSUE THREAD

**Issue by haoxuelou** [crystal-lang/crystal#6673]
In the Alpine Linux Docker container
```
$ crystal -v
Crystal 0.26.1 (2018-08-30)

LLVM: 5.0.1
Default target: x86_64-alpine-linux-musl

$ uname -a
Linux 93c8d84ac774 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 Linux

$ echo 'puts "hello world!"' > hello_world.cr

$ crystal build --static -o hello_world hello_world.cr 
```
Then, I had get a binary file "hello_world". 

In the mac pro
```
$ crystal -v
Crystal 0.26.0 (2018-08-17)

LLVM: 6.0.1
Default target: x86_64-apple-macosx

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.1
BuildVersion:	17B1003

$ uname -a
Darwin localhost 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64

$ ./hello_world #this file is that build in the docker container
exec format error: ./hello_world
```

can you tell me how let it work, thx

**Comment by j8r** [comment]
macOS doesn't support static linking: https://github.com/crystal-lang/crystal/wiki/Static-Linking

**Comment by straight-shoota** [comment]
This has nothing to do with static linking. MacOS simply can't run a Linux binary.

You need to compile your binary for MacOS either directly on that OS or using [cross compilation](https://crystal-lang.org/docs/syntax_and_semantics/cross-compilation.html).
But then, yes static linking won't work either.

**Comment by ysbaddaden** [comment]
Closing. 1. Please build a binary on macOS and 2. you can't compile a static binary on macOS anyway, just try to get static libraries linked instead of shared ones —but system libraries will *always* be linked dynamically.
