### ISSUE TITLE
Read buffering bug

### ISSUE THREAD

**Issue by carlhoerberg** [crystal-lang/crystal#6674]
If you read some bytes, so it fills up the buffer, and then do a read that is larger than `BUFFER_SIZE`, you won't get the data after the buffer. 

```
o = ("a" * 8192).to_slice
i = Bytes.new(8192)
File.open("/tmp/a", "w") { |f| f.write_byte 0; f.write o }
File.open("/tmp/a", "r") { |f| f.read_byte; f.read i }
puts o == i
```

Output: `false`

```
$ crystal -v
Crystal 0.26.0 (2018-08-17)

LLVM: 6.0.1
Default target: x86_64-apple-macosx
```

**Comment by asterite** [comment]
You need to use `read_fully`. `read` doesn't guarantee that it will read the entire slice.

**Comment by asterite** [comment]
`read` will only perform one unbuffered read, while `read_fully` is allowed to do many such calls.

**Comment by carlhoerberg** [comment]
ah, of course...
