### ISSUE TITLE
Need a big improvement to Crystal website

### ISSUE THREAD

**Issue by jamesfuture** [crystal-lang/crystal#6675]
I know there is a Crystal website repo but here get more attention.

My first impress on Crystal Lang website (https://crystal-lang.org) feels dry, boring and too many code examples in a page which can do more harm or scared away newbie or non-IT savvy when they visit the site for the first time, in contrast to RubyOnRails, Laravel, Vapor, etc.

If we want to grow community from all walk of life, we’ll need to revamp with friendly introductions and what made Crystal so special from other languages, this way the community will adopt without feeling difficulty or less motivated to pick up 2nd language after Ruby.

The current code examples feels lifeless, we need to highlight colours.

What do you guys think?

**Comment by z64** [comment]
This issue is probably best for https://github.com/crystal-lang/crystal-website

**Comment by ysbaddaden** [comment]
Not an issue. Please reopen on https://github.com/crystal-lang/crystal-website or create a thread on the mailing list. Thanks :)
