### ISSUE TITLE
doesntexist.example.org resolves on Verizon FIOS network

### ISSUE THREAD

**Issue by gmarcais** [crystal-lang/crystal#6676]
This is a rather strange problem. The unit tests use the address "doesnotexist.example.org." as a none existent address to check for resolution failure of the TCP socket (see spec/std/socket_spec.cr:505 for example). Unfortunately, this address does resolve on the FIOS network:

```Shell
> dig @71.252.0.12 doesnotexist.example.org
; <<>> DiG 9.13.2 <<>> @71.252.0.12 doesnotexist.example.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33796
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;doesnotexist.example.org.	IN	A

;; ANSWER SECTION:
doesnotexist.example.org. 0	IN	A	92.242.140.21

;; Query time: 87 msec
;; SERVER: 71.252.0.12#53(71.252.0.12)
;; WHEN: Fri Sep 07 13:26:49 EDT 2018
;; MSG SIZE  rcvd: 69
```

(71.252.0.12 is the default Verizon FIOS DNS server). The Google public DNS server 8.8.8.8 on the other hand does not resolve the address. Hence, by default, unit tests fail on the Verizon network because the error reported is timeout, and not a failure of resolution.

That's rather unfortunate. Although this is not really a bug of Crystal, should we generate a random address string instead of a static one? Something like:

```Crystal
a = ('a'..'z').to_a
url = (0..16).map { a[rand(26)] }.join("")  + "." + (0..16).map { a[rand(26)] }.join("") + ".org"
```

This would have a very low probability of ever reaching a real host.

**Comment by RX14** [comment]
@gmarcais try resolving a random host, I'm going to reckon that it resolves too. It's a horrible anti-feature of certain unsavoury ISPs called nxdomain hijacking which never return an error from their DNS servers, instead redirecting you to a custom error page generated by your ISP. 

So there's really nothing to fix here, please use google DNS if your ISP is shit.

**Comment by gmarcais** [comment]
Well, I spoke too fast. Verizon DNS is just plain annoying. It resolves any URL!

```Shell
> dig @71.252.0.12 iqusbnvnmdmtlqvsd.gspteoqinwdvawkne.org
; <<>> DiG 9.13.2 <<>> @71.252.0.12 iqusbnvnmdmtlqvsd.gspteoqinwdvawkne.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58395
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;iqusbnvnmdmtlqvsd.gspteoqinwdvawkne.org. IN A

;; ANSWER SECTION:
iqusbnvnmdmtlqvsd.gspteoqinwdvawkne.org. 0 IN A	92.242.140.21

;; Query time: 25 msec
;; SERVER: 71.252.0.12#53(71.252.0.12)
;; WHEN: Fri Sep 07 13:55:47 EDT 2018
;; MSG SIZE  rcvd: 84
```

Annoying. My ISP is shit indeed.

**Comment by RX14** [comment]
If you look up the AS of 92.242.140.21 you get AS45028 owned by http://www.barefruit.com/ which explains all the moneygrabbing reasons your ISP broke DNS
