### ISSUE TITLE
Annotations aren't allowed for enum methods

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#6690]
### https://carc.in/#/r/4xb0

```crystal
enum ModelReference
  Author
  Editor

  @[AlwaysInline]
  def key
    case value
    when 0 then "author_id"
    when 1 then "editor_id"
    else        raise "Bug: unhandled value #{value}"
    end
  end
end

# unexpected token: @[
```

**Comment by RX14** [comment]
@vladfaust no, enum is not a struct, it's a `Value`, `Enum < Value` and `Struct < Value` but not `Enum < Struct`.

Enums are just numbers with methods.

**Comment by vladfaust** [comment]
Ah, alright. So, no extended functionality for enums?

**Comment by straight-shoota** [comment]
They are no structs, but annotations should work.

**Comment by vladfaust** [comment]
Why you say that enums aren't structs when

https://github.com/crystal-lang/crystal/blob/391785249f66aaf5929b787b29810aeb4af0e1e8/src/enum.cr#L89

**Comment by RX14** [comment]
@vladfaust well `Struct < Value < Object` and we have `class Object`. These are overridden by the compiler, it's declared as a struct even though it's not a struct.

**Comment by straight-shoota** [comment]
The `Enum` base type is described as a struct, but in fact, it does not inherit from `Struct` but directly from `Value`.
