### ISSUE TITLE
Invalid memory access with channel.wait_for_receive

### ISSUE THREAD

**Issue by spinscale** [crystal-lang/crystal#6691]
The following piece of code crashes when running under crystal. Note this is not the code I wanted to run, but it happened while playing around with channels, so I might be doing something stupid. Yet I think, a proper error message might make sense. If you dont think so, feel free to close.

```
crystal --version
Crystal 0.26.1 (2018-08-27)

LLVM: 6.0.1
Default target: x86_64-apple-macosx
```

```
channel = Channel(Int32).new(1)

def add(val : Int32, channel : Channel(Int32))
  puts "Adding #{val}"
  channel.send(val)
  puts "Added #{val}"
end

spawn do
  channel.wait_for_receive
end

add(1, channel)

spawn do
  add(2, channel)
end

sleep 1

puts channel.receive
puts channel.receive
```

This reliably exits with the following

```
Invalid memory access (signal 10) at address 0x10c28bff0
[0x10a6e3abb] *CallStack::print_backtrace:Int32 +107
[0x10a6cb0dc] __crystal_sigfault_handler +60
[0x7fff7faf8f5a] _sigtramp +26
```

**Comment by kostya** [comment]
may be related https://github.com/crystal-lang/crystal/issues/3900

**Comment by asterite** [comment]
`wait_for_receive` is internal API, you shouldn't be calling this.

**Comment by RX14** [comment]
The bug is that these methods aren't nodoc or protected.
