### ISSUE TITLE
Generic#resolve ?

### ISSUE THREAD

**Issue by anykeyh** [crystal-lang/crystal#6695]
## Case

I'm willing to use the macro system to resolve types to string at compile time, but face some issues.

My main problem is that the macro AST `Generic#resolve` method doesn't exists, leading to difficulty to implement resolution of any type. Let's see this example:

## Sample

```crystal
macro get_type(t)
  "{{t.resolve}}"
end

module A
  module B
  end

  class C(X)
  end

  def self.main
    puts get_type(B) #OK, resolve to "A::B"
    puts get_type(C(B)) #Should resolve to "A::C(A::B)" but resolve doesn't exists over Generic
  end
end
```

## Work-around (spoil: not working):

1. using `{{t.name.resolve}}` will return the resolved generic, but with `(X)`: `A::C(X)`
2. using `{% for v in t.type_vars %}{{v}}{% end %}` will return the generic type list, but since the type can be a generic themselves, it cannot be resolved too (plus it's recursive, without functions in macro this is harsh).

## Resolutions

1. I guess implementing `resolve` method over generics would fix the problem
2. If you have any work-around, I would like to know it to [fix this](https://github.com/anykeyh/clear/issues/38)

**Comment by bew** [comment]
It's been already done in #6617, it'll be available in next release :smiley:
