### ISSUE TITLE
Allow def Type.method

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#6697]
I'm sorry if it's a duplicate or already implemented.

I'd like to see this possible:

```crystal
def String.foo
  self + ", foo"
end

"bar".foo
# => "bar, foo"
```

My usecase is defining `to_db` methods for an array of types in macros:

```crystal
class URI
  def to_db
    to_s
  end
end

{% for type in DB::TYPES %} # [Nil, String, Bool, Int32, Int64, Float32, Float64, Time, Bytes]
  def {{type}}.to_db
    self
  end
{% end %}
```

`DB::TYPES` contain `String`, which is a class, and other types are structs. Without `def {{type}}.to_db`, I'd need to write separate def for `String` and for other methods. Also some types inherit, other don't. As a result, I'd have to write `to_db` for each type manually.

**Comment by RX14** [comment]
`def String.foo` already defines a method on `String:Class`. This won't change.

**Comment by RX14** [comment]
https://carc.in/#/r/4xwp

**Comment by vladfaust** [comment]
@RX14 what about defining class methods as `def String.class.foo` and instance as `def String.foo`? Or instance as `def String.instance.foo`?

**Comment by asterite** [comment]
Ah, yes, there's no way to generically reopen a type... maybe a `reopen` keyword would be nice. I guess for now you'll have to code your app in a different way.

**Comment by RX14** [comment]
https://carc.in/#/r/4xws is far closer

**Comment by vladfaust** [comment]
@RX14 that definitely makes sense. The issue can be solved anyway, just throwing a low-priority idea 🙂
