### ISSUE TITLE
Free variable method takes precedence even if defined earlier

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#6701]
### https://carc.in/#/r/4xxl

```crystal
def foo(x : T) forall T
  puts "1"
end

def foo(x : Int32)
  puts "2"
end

foo(42)
```

Outputs `2`. It's expected for me, because I'm narrowing arguments. However,

### https://carc.in/#/r/4xxk

```crystal
def foo(x : Array(T).class) forall T
  puts "1"
end

def foo(x : Array(Int32).class)
  puts "2"
end

foo(Array(Int32))
```

Outputs `1`. And this behavior is not consistent. I expect `2` in both cases.

---

My use-case is redefining https://github.com/will/crystal-pg/blob/master/src/pg/result_set.cr#L92 to work with certain array types, e.g. `def read(Array(Enum).class)`.

**Comment by vladfaust** [comment]
My use-case is redefining https://github.com/will/crystal-pg/blob/master/src/pg/result_set.cr#L92 to work with certain array types, e.g. `def read(Array(Enum).class)`.

**Comment by vladfaust** [comment]
Also https://carc.in/#/r/672e:

```crystal
def foo(x : T.class) forall T
  puts "1"
end

def foo(x : Int32.class)
  puts "2"
end

foo(Int32)
```

Puts `1` as well.

**Comment by bew** [comment]
Btw your last example is tracked by #6446

**Comment by asterite** [comment]
All of these seem to be fixed now, but please reopen if this isn't the case.
