### ISSUE TITLE
Compiler version detection

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#6715]
When the compiler is built, it stores the version of the compiler source code in the executable which can later be printed with `crystal --version`.

There is some rather complicated logic in [`crystal/compiler/config.cr`](https://github.com/crystal-lang/crystal/blob/8154c2d1894e3e82a28284701cd5841bf749af31/src/compiler/crystal/config.cr#L32) (#2856) to determine the current version.

Essentially, it reads the current git tag and uses that if available. Otherwise, the version of the compiling compiler is used, either bare or with `+?` appended depending on whether it's inside a git repository. All this can be overriden by setting the env var `CRYSTAL_CONFIG_VERSION`.
The version is also accompanied by the SHA hash of the current commit. This is only available when building in a git repository and always uses HEAD.

There are a few issues with this approach, some have already been mentioned in #4642 and #4687.

The compiler provided as FreeBSD port tells it is `0.24.0+?+?+?+?`. This does not only hide the fact that it is actually a 0.25.1 compiler but also results in a `Crystal::VERSION` that can't be handled by `SemanticVersion`. This compiler currently fails to build `int_spec.cr` because it contains the `compare_versions` macro. It can be fixed by setting `CRYSTAL_CONFIG_VERSION` in the build process, but the compiler should not produce such invalid versions.
In general, when building from a tarball, the compiler has no information whatsoever on the current source version. Proper version reporting (including SHA) depends on using a git clone. This is not very practical for many use cases where a tarball would suffice.

Builds can be categorized in two different types:

* A *development* build compiles a shallow version somewhere in between releases. It is used for development and testing purposes (locally, in CI, etc.). The version should be based on the latest release version (which is NOT necessarily the compiling compiler's version) with some kind of suffix like `-dev` or an offset with the number of commits since the release. And it should of course include a commit hash if available. These are typically built in a git repository, but not necessarily.
* A *release* build compiles the compiler at a specific released version (this includes official binaries, pre-releases, OS packages etc.). The source code might live in a git clone, but can as well be from a tarball. These builds a typically automated in some kind of build script. Version and commit hash are fixed and should be configured in the build process.

I think it would be a good idea to make *release* builds always require explicit configuration to use the appropriate version information. Since it's mostly automated and the build systems already have the information, this shouldn't be a big deal.
Every other build without explicit configuration is automatically a development build and won't have a release version.  But the reported version of a development build should accurately describe the state of the source code.

Using the version of the current compiler (`Crystal::VERSION`) is not an option. A newer compiler might also compile an older source, or a recent source could be compiled by a compiler that is older than the last release.

When git is available, the currently used `git describe --tags --long --always 2>/dev/null` would return something like `0.26.1-60-g1337b09` for current master. This is really nice, especially because it shows the number of commits. But it is also pretty unreliable because git tags are not automatically synchronized. You can have the latest master branch, but unless you also have the `0.26.1` tag, it will report as being based on an older release (for example: `0.25.1-218-g1337b09`). To update the tags you need to run something like `git fetch --tags upstream`.

I think the only way to get this straight is to document the latest release in the source code. Then it will be available everywhere (not depend on git) and reliably correspond to the code.
This is already available in CHANGELOG and could be implemented similar to  #4687. But I would not rely on the git version at all. Maybe the git data could be to enhance the version info by the number of commits since the latest release tag (if it matches the latest release in the changelog) and the commit hash.
For builds without git it should be an issue to loose some information about the number of commits and the commit hash.

Regarding implementation, it might be preferable to decouple the logic and move it out of the compiler source. Then the compiler just needs to read `CRYSTAL_CONFIG_VERSION` and `CRYSTAL_CONFIG_COMMIT`.

Unless specified (for a release build) the Makefile would populate them with `$(grep -oEi '(^|\n)# ([0-9]+\.[0-9]+\.[0-9]\w*)' CHANGELOG.md | head -n1 | awk '{print $2}')-dev` and the commit hash of HEAD. Maybe some additional logic could validate the base version of `git describe --tags --long --always 2>/dev/null` and use the offset. But that's an advanced feature and I'd suggest to focus on getting the basics right first.

**Comment by straight-shoota** [comment]
CI on travisci fails because it uses a compiler with an invalid version `0.26.1+?` (see https://travis-ci.org/crystal-lang/crystal/jobs/429570057).

**Comment by RX14** [comment]
If anyone can actually work out what changed between the failing build and the previous they get a gold star

**Comment by bcardiff** [comment]
TravisCI fix at #6739
