### ISSUE TITLE
Add reduce method

### ISSUE THREAD

**Issue by ttowncompiled** [crystal-lang/crystal#6726]
Hey everyone! I'm overjoyed to see how much time and effort is being put in Crystal. I'm a huge fan of Ruby, but I've always wanted more and it seems to me that Crystal is providing just that. I would love to help contribute when and if I can. I read over the contributor's guide, looked for newcomer tags, but only found issues from over 2 years ago, so I decided to start looking at the codebase to see if there was anything that I could add or polish. I found a number of things, but I'll start with this: the reduce method.

Ruby didn't have a reduce method for Enumerable classes such as the Range and the Array, but reduce is an extremely useful method to have. The most useful aspect of a reduce is that it allows someone to combine three operations into one: map, select, and a squash (squash being a transform from an array to a single element). More importantly, without supporting reduce, to actually squash an Enumerable, one either has to use an implemented method such as sum (which may not be implemented), has to write verbose code, or has to employ multiple iterations over the Enumerable such as:

``` ruby
z = 1
(1..10).map{ |d| 2*d }.each{ |d | z *= d }
```

This also has the downside of requiring that we introduce z into scope. However, with a reduce, we could combine these two iterations into one as so:

```ruby
# a is the current reduction result
(0..10).reduce{ |a, b| a + 2*b }
```

We can combine maps and filters:

``` ruby
# compute the sum of the even squares of the first 10 numbers
(0..10).reduce{ |a, b| b % 2 == 0 ? a + b**2 : a }
```

This can also be used to compute the product of all of the elements of an Enumerable which is great for implementing factorials.

``` ruby
[ 1, 2, 3, 4, 5 ].reduce{ |a, b| a * b }
(1..5).reduce{ |a, b| a * b} # factorial
```

And with an array of strings, you can use reduce to easily join with separators

``` ruby
[ "home", "username", "workspace", "crystal" ].reduce{ |a, b| a + "/" + b }
```

I can see being most helpful on the Array, Range, and Tuple classes, and I wouldn't mind working on this myself to get my feet wet.

Warmest regards.

**Comment by asterite** [comment]
Hi!
https://crystal-lang.org/api/0.26.1/Enumerable.html#reduce%28%26block%29-instance-method
https://crystal-lang.org/api/0.26.1/Enumerable.html#reduce%28memo%2C%26block%29-instance-method

**Comment by ttowncompiled** [comment]
Sweet! Thanks. I don't know how I missed that in the docs. I must have been clumsily typing.
