### ISSUE TITLE
Using uri.path instead of String brakes HTTP::Client#get

### ISSUE THREAD

**Issue by sudo-nice** [crystal-lang/crystal#6729]
# Submitting bugs

This code works as expected:

```crystal
require "http/client"

uri = URI.parse "https://example.com/help"
client = HTTP::Client.new uri
client.get("/help") { |_| puts "hello" }
```

But with this change it fails:

```diff
 uri = URI.parse "https://example.com/help"
 client = HTTP::Client.new uri
+client.get(uri.path) { |_| puts "hello" }
-client.get("/help") { |_| puts "hello" }
```

I expect `uri.path` should work, because it holds the same string as `"/help"`:

```crystal
uri.path == "/help" # => true
```

[carc.in]
[long error log]

[carc.in]: https://carc.in/#/r/509i
[long error log]: http://ix.io/1mLd

---
Crystal 0.26.1 [391785249] (2018-08-27)
  LLVM: 4.0.0
  Default target: x86_64-unknown-linux-gnu

**Comment by r00ster91** [comment]
The error happens because `uri.path` can return `nil`. (The union type is `(String | Nil)`).
A way to handle this is:
```crystal
require "http/client"

uri = URI.parse "https://example.com/help"
client = HTTP::Client.new uri
if path = uri.path
  client.get(path) { |_| puts "hello" }
end
```
The `if path = uri.path` check ensures that `path` is not `nil`.

**Comment by straight-shoota** [comment]
Note: #6323 would change the return type of `URI#path` to `String` and this would have worked as expected from the beginning.
