### ISSUE TITLE
Instance variable not updatting when using property macro

### ISSUE THREAD

**Issue by epergo** [crystal-lang/crystal#6734]
First of all, I don't know how to describe this issue in the title so forgive me :sweat_smile: 

I have the following issue, when creating a method that receives a block, updates an instance variable and then inside the block it uses the instance variable, it still has the old value.

Because a snippet of code is worth more than a thousand words:

https://carc.in/#/r/50oj

```crystal
class Example
  property my_property : String = "default"
  property my_property_2 : String = "default"
  
  def foo
    @my_property = "pepito"
    my_property_2 = "pepito"
    
    yield
  end
end

example = Example.new
example.foo do
  puts "#{example.my_property}, #{example.my_property_2}"
end
```

```bash
# => pepito, default
```

As you can see, if the instance variable is updated without the setter method, it works as ¿expected?

**Comment by asterite** [comment]
This:

```
my_property_2 = "pepito"
```

assigns to a local variable, **always**.

To make it a method call you have to do:

```
self.my_property_2 = "pepito"
```

**Comment by epergo** [comment]
Oh god, that explains a lot of things.

Thanks!
