### ISSUE TITLE
Enable `File.join` in Macro

### ISSUE THREAD

**Issue by xqyww123** [crystal-lang/crystal#6746]
Macro may require to safely join the paths to generate shell commands or others, when the path may be determined by variables. Like this:

``` crystal
macro mark_down(what)
{{ run("cat res/#{what}.md").stringify }} # not cross-platform safe!
# cross-platform safe:
{{ run("cat " + join_path("res", "#{what}.md")).stringify }}
end

puts mark_down book
```

**Comment by asterite** [comment]
Just do:

```crystal
{% if flag?(:windows) %}
...
{% else %}
{% end %}
```

because I think you will have problems with `cat` working on Windows to start with...

**Comment by Sija** [comment]
Once there was #2791, which would solve this issue.

**Comment by asterite** [comment]
Well, nobody liked my idea of the `read_file` macro method. If you want it now, go for it :-)
