### ISSUE TITLE
crystal api scrolling jitterness and distortion

### ISSUE THREAD

**Issue by girng** [crystal-lang/crystal#6751]
windows 10, 64-bit. Firefox Quantum 62.0 (latest), 144hz display

### Issue
When visiting any page on https://crystal-lang.org/api/master/, and when you scroll, there is a small distortion and jitterness (most annoying thing ever!). 
It was not like this 5-6 months ago, something was changed i think

Might be hard to show for a gif example, but you can definitely notice it yourself.
Distorted scrolling:
![](https://i.gyazo.com/e1cf5faab3df0eac83d8cc921e30a8fd.gif)

Smooth:
![](https://i.gyazo.com/caef3f77e36e0f5468328ea42cda8e9d.gif)

**Comment by girng** [comment]
I also noticed, the sidebar w/ all the class names scrolls just fine

**Comment by straight-shoota** [comment]
I don't exactly follow your description of incorrect behaviour. But scrolling is generally implemented by the browser. The webpage itself has little to no influence over that.

**Comment by r00ster91** [comment]
I use the latest Firefox Quantum too and I don't really notice jitteriness or distortion. Maybe it's because you didn't enable smooth scrolling in the settings?

**Comment by girng** [comment]
Hi @r00ster91 and @straight-shoota. Yeah, it's enabled in the settings. Every single page on the internet I've been to so far scrolls smoothly except those doc pages :P. The sidemenu scrolls smooth, but not the right side. I can't be the only one experiencing this :(

**Comment by z64** [comment]
> It was not like this 5-6 months ago

Well, one easy way to check - you can indeed view the docs of any past version, as they were generated with the docs tool as it was written at the time of release:

https://crystal-lang.org/api/0.20.0/

If you think its an issue with the docs tool introduced with a specific release, you can walk through each version since 0.20 by changing the URL until you notice the behavior again to "bisect" the issue.

**Comment by girng** [comment]
> https://crystal-lang.org/api/0.20.0/

Smooth as better! My lord, what happened to the docs lol

**Comment by girng** [comment]
BOOM. Got it.
https://crystal-lang.org/api/0.24.0/Benchmark.html SMOOTH
https://crystal-lang.org/api/0.25.0/Benchmark.html LAG

this is where it changes

**Comment by jwoertink** [comment]
Interesting. I actually see it too using latest firefox on MacOS. You have to scroll somewhat slow and consistent to see it. Maybe the JS is trying to calculate something during the scroll event? 

In any case, it doesn't really bother me much, but I did happen to see on line 33 of the generated source for channel `<div class="search-results" class="hidden">` view-source:https://crystal-lang.org/api/0.26.1/Channel.html. 2 different class attribute if anyone wants to fix that one 😅

**Comment by girng** [comment]
@jwoertink Just curious what monitor rate do you have? I'm on 144hz so I think that makes it really visible for me. Glad to know i'm not the only one though haha.

**Comment by girng** [comment]
Found it
.types-list, .main-content {

    filter: blur(0);
    transition: filter 200ms;

}

please remove transition

**Comment by jwoertink** [comment]
60hz on both my displays laptop and external monitor. hahah 😂

**Comment by j8r** [comment]
This is even more obvious on Firefox mobile.

**Comment by j8r** [comment]
A PR @girng :)?

**Comment by girng** [comment]
> A PR @girng :)?

![](https://media.giphy.com/media/O5NyCibf93upy/giphy.gif)

**Comment by girng** [comment]
> A PR @girng :)?

![](https://1.bp.blogspot.com/-tws-xnWatKU/TWAWm3rLGJI/AAAAAAAALaw/QkUkktMcz4c/s1600/FGGirlSports.jpg)
