### ISSUE TITLE
connect_timeout doesn't trigger with local addresses

### ISSUE THREAD

**Issue by girng** [crystal-lang/crystal#6752]
### Issue
When using the [connect_timeout](https://crystal-lang.org/api/master/TCPSocket.html#new%28host%2Cport%2Cdns_timeout%3Dnil%2Cconnect_timeout%3Dnil%29-class-method) parameter for TCPSocket.new, it doesn't trigger if it's a local address. It does work if you are using "fakeurl.com", but `0.0.0.0`, or `localhost` it won't.

```
require "socket"
begin
  check = TCPSocket.new("0.0.0.0", 1000, 0, 2)
  check.tcp_nodelay = true
rescue e
  puts e # connect timeout error will never get called
end
```

Windows 10 64-bit (WSL), **Crystal 0.26.0 [eeb53c506] (2018-08-09)**

**Comment by jasdeepsingh** [comment]
I can confirm this behaviour is reproducible on Mac OS X as well:

```
✔︎ crystal connect.cr
Error connecting to 'localhost:1234': Connection refused
✔︎ crystal connect.cr
Error connecting to '127.0.0.1:1234': Connection refused
✔︎ crystal connect.cr
connect timed out
```

The last run uses a random DNS.

**Comment by girng** [comment]
@jasdeepsingh If you got time, can you please test 6759# for me. Just use the code in my first post.  Tell me if you are experiencing the same thing

**Comment by proyb6** [comment]
@girng I can help to test on macOS Mojava - Crystal 0.26.1 with build release.

If these are the code to be tested.
```
require "socket"

def handle_connection(socket)
  begin
    loop do
      payload_size = socket.read_bytes(Int32)
      puts payload_size
      raw_message = socket.read_string(payload_size)
      puts raw_message
    end
  rescue e
    puts "Disconnected from the Master Server"
    puts e
  end
end

def gogo
  begin
    puts "Waiting for the server to become connectable.."
    check = TCPSocket.new("0.0.0.0", 9300)
    check.tcp_nodelay = true
    puts "Successfully connected to the Master Server"
    spawn handle_connection(check)
    loop do
      sleep 1
    end
  rescue e
    puts e
  end
end

gogo()
```

```
Waiting for the server to become connectable..
Error connecting to '0.0.0.0:9300': Connection refused
	Command being timed: "./gogo"
	User time (seconds): 0.00
	System time (seconds): 0.00
	Percent of CPU this job got: 69%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.01
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 1620
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 533
	Voluntary context switches: 0
	Involuntary context switches: 33
	Swaps: 0
	File system inputs: 0
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

Perhaps, testing on a VPS server with Linux distro if you can.

**Comment by RX14** [comment]
The connect timeout is for when the server doesn't respond to the connection request. After a certain time it will raise an error.

If there *is* a server there it can reply "connection refused" to the connection request immediately and it will raise "connection refused". This isn't a bug.

Servers without a firewall will respond "connection refused". Servers with a firewall will time out.

**Comment by RX14** [comment]
Also, I strongly suggest you ask for a second opinion on a bug report, perhaps on gitter, before you submit it to the issue tracker.

**Comment by girng** [comment]
@proyb6  Thanks, so it does get triggered

@RX14 I think this is a WSL only bug too. Because @jasdeepsingh's error does get rescued, but on WSL, it just hangs. The error never gets thrown. Regardless if it's firewalled or whatever.
