### ISSUE TITLE
0.26 macro fails to accept keyword arguments with empty regex

### ISSUE THREAD

**Issue by maiha** [crystal-lang/crystal#6761]
The following code works with `0.24` and `0.25`, but not with `0.26.1` and `master`.
- master: Crystal 0.26.1+67 [421497e] (2018-09-21)

```crystal
macro foo(regex)
end

foo(regex: //)
```

```
Syntax error in /tmp/test.cr:4: unterminated call

foo(regex: //)
   ^
```

It works with `foo(regex: /.*/)` or `foo(//)` in `0.26.1`.

### versions

| version   | code             | result            |
|-----------|------------------|-------------------|
| 0.24.x    | foo(regex: //)   | OK                |
| 0.25.x    | foo(regex: //)   | OK                |
| 0.26.1    | foo(regex: //)   | unterminated call |
|           | foo(regex: /.*/) | OK                |
|           | foo(//)          | OK                |
| 0.26.1+67 | foo(regex: //)   | unterminated call |

### real codes
- https://github.com/maiha/comment-spec.cr/blob/master/src/comment-spec/regex_parser.cr#L158-L161

Best regards,

**Comment by Sija** [comment]
That's (unfortunately) correct, it was one of the breaking changes of `0.26` (see #6470).
