### ISSUE TITLE
Defining abstract methods with generics fails

### ISSUE THREAD

**Issue by spinscale** [crystal-lang/crystal#6762]
I have an issue with abstract methods and generics (note, java developer speaking here, so this might be just an misunderstanding).

When defining the following abstract class

```crystal
abstract class Foo(T)
  abstract def set(copy : Array(T)) 
end
```

I expected the implementation to be 

```crystal
class Bar < Foo(String)
  def set(copy : Array(String))
  end
end
```

This however gives a compile time error, where as using `def set(copy : Array)` works.

**Comment by vladfaust** [comment]
Looks like a bug for me, because this code raises no error:

```crystal
class Foo(T)
  def foo(x : T)
    {% raise NotImplementedError %}
  end
end

class Bar < Foo(String)
  def foo(x : String)
    puts x
  end
end

Bar.new.foo("foo")
```

**Comment by RX14** [comment]
Definitely a bug, workaround is just to loosen the type restriction.

**Comment by vladfaust** [comment]
Got this bug again while creating an abstract rescue HTTP handler (https://carc.in/#/r/5tcy):

```crystal
abstract class Rescuer(T)
  def call(context)
    call_next(context)
  rescue ex : T
    handle(ex)
  end

  abstract def handle(ex : T)
end

class BasicRescuer < Rescuer(Exception)
  def handle(ex : Exception)
    puts ex.inspect_with_backtrace
  end
end

BasicRescuer.new
```

```console
Error in line 8: abstract `def Rescuer(T)#handle(ex : T)` must be implemented by BasicRescuer
```

**Comment by asterite** [comment]
Workaround: don't define the abstract method at all.

**Comment by vladfaust** [comment]
As mentioned above in https://github.com/crystal-lang/crystal/issues/6762#issuecomment-423481570, defining with `T` and then overriding with `Type` works (https://carc.in/#/r/5tex). But it doesn' work in this particular case (https://carc.in/#/r/5tey):

_The example could be simplified, sorry about that_

```crystal
require "http/server"

abstract class Rescuer(T)
  include HTTP::Handler

  def call(context)
    call_next(context)
  rescue error : T
    handle(error)
  end

  def handle(error : T)
    {% raise "Must be implemented" %}
  end
end

class BasicRescuer < Rescuer(Exception)
  def handle(error : Exception)
    puts error.inspect_with_backtrace
  end
end

server = HTTP::Server.new([BasicRescuer.new]) do |context|
  context.response.print("Hello\n")
end

server.bind_tcp(5000)
puts "Listening"
server.listen
```

```console
in line 9: Must be implemented
```

As @asterite mentioned in #7200, there might be a problem with module inclusion.

It also seems to be related to https://github.com/crystal-lang/crystal/issues/6701.

**Comment by asterite** [comment]
Just to clarify, the abstract method check doesn't work well with generic inheritance.

Please try to avoid inheriting from generic types right now.
