### ISSUE TITLE
Is this some kind of sick joke?

### ISSUE THREAD

**Issue by NaamanIskowitch** [crystal-lang/crystal#6765]
https://github.com/crystal-lang/crystal/blob/421497e07ff51d0cb05b7e1bbd7e6f25ab33f69e/spec/std/big/big_rational_spec.cr#L99

Ableist terms are **NOT** OK, you sickos! Who thought it was a good idea to write _"Sanity check"_? Who wrote this? Ableism is against the code of conduct. Replace it with a more neutral term, like "non-specific-normal change detect" or something, _please_.

**Comment by benixlinux** [comment]
Agreed. This kind of speech is hateful and unwarranted. Devs please correct this.

**Comment by galvertez** [comment]
both @NaamanIskowitch and @benixlinux joined github today.
http://niceme.me/

**Comment by Sija** [comment]
That's one weird way to spam 😕

**Comment by galvertez** [comment]
@NaamanIskowitch @benixlinux it gets worse! look at line 100! 😮
it has the word `[l, e, g]` in it! sickos!

**Comment by vladfaust** [comment]
With recent Redis and Pythin stuff I beg Crystal team to ignore such things.

**Comment by NIFR91** [comment]
Yes, just close this and lock it, don't give any room to spam

**Comment by Sija** [comment]
> With recent Redis and Pythin stuff

@vladfaust That is...?

**Comment by NaamanIskowitch** [comment]
> both @NaamanIskowitch and @benixlinux joined github today.
> http://niceme.me/

"people who have just joined the community should be shunned"
Yep, this is a fash community

**Comment by galvertez** [comment]
@Sija @vladfaust both @benixlinux and @NaamanIskowitch are the same guy. it's just a troll.

when the trolls arrive, you know you've made it big 👍
