### ISSUE TITLE
Cleaning problematic ableist/saneist terms

### ISSUE THREAD

**Issue by benixlinux** [crystal-lang/crystal#6767]
It has come to my attention that crystal's source code contains problematic ableist/saneist terms and/or pejoratives, namely

> crystal/spec/std/big/big_rational_spec.cr
> 
> Line 99 in 421497e
> # sanity check things aren't swapped 

Some of this slipped into the documentation. In an attempt to make crystal's community more inclusive and welcoming, we should clean up these usages and replace them with something neutral (where applicable). Unfortunately, to this day many developers deem such efforts as "trolling", so please note that the precedent has already been set by many major projects. Here're just a few:

unpkg/unpkg.com#81
reduxjs/redux#2335
rtfd/readthedocs.org#3752
krzysztofzablocki/Sourcery#2
xi-editor/xi-editor#126

Other resources:

https://english.stackexchange.com/q/282282
http://isthisableism.tumblr.com/sluralternatives

The goal of this issue is not to stir up arguments, but to figure out the alternatives and ways to replace those problematic terms.

Assistance is greatly appreciated, thank you.

**Comment by bcardiff** [comment]
The highlighted phrase and other are already changed in master.

If others are found please report them so the situation can be improved.

Thanks

**Comment by benixlinux** [comment]
Thank you so much, it's so much more inclusive now. My rabbi will be pleased

**Comment by Darkenetor** [comment]
@bcardiff https://boards.4chan.org/pol/thread/186604776
