### ISSUE TITLE
Remove racist maintainer

### ISSUE THREAD

**Issue by M-BoloDyebambewe** [crystal-lang/crystal#6772]
A fellow opened up an issue concerning a _white power_ sign in the source code, and @asterite closed it immediately. Could it be his frail privilege showing? It's against the code of conduct, so I suggest he be ejected from the project before he makes ethnic minorities like me take our skills and leave.

**Comment by slammerhammer** [comment]
its absolutey disgusting how they could have a maintainer who is a nazi white supremacist

**Comment by socqse** [comment]
I am appaled by this to be quite honest with you. I hope it gets fixed.

**Comment by M-BoloDyebambewe** [comment]
> I am appaled by this to be quite honest with you. I hope it gets fixed.

> its absolutey disgusting how they could have a maintainer who is a nazi white supremacist

THANK YOU for the support brothers. Maybe the good guys will see this before the fascist closes it yet again

**Comment by ysbaddaden** [comment]
Closing. Bad behavior as per Code of Conduct. Act and behave correctly.

**Comment by M-BoloDyebambewe** [comment]
Ironic. White man shuts down minority criticism, citing code of conduct which would get him banned for this. GO BACK TO THE CAVES WHITE DEVIL
