### ISSUE TITLE
White power symbol.

### ISSUE THREAD

**Issue by socqse** [crystal-lang/crystal#6775]
Issues keep getting blocked, how come?

**Comment by slammerhammer** [comment]
the facist nazis will close this too

**Comment by slammerhammer** [comment]
> the facist nazis will close this too

im betting on it

**Comment by M-BoloDyebambewe** [comment]
The nazi will close this one too. Probably covering his tracks. BUT WE WILL FIGHT
Posting this to twitter as I speak
