### ISSUE TITLE
Calling a referenced proc, in a macro contained within a namespaced class

### ISSUE THREAD

**Issue by rickychilcott** [crystal-lang/crystal#6779]
I was able to find an issue that crops up when you are building a macro that references a method, as a proc, and tries to call in that context. When it's wrapped in a module it's broken, but when it's not wrapped in a module it's fine.

```crystal
module TestMod
  class TestClass
    def self.test_method
      puts "Do something"
    end

    macro build_proc_method(name)
      def self.{{name}}_as_proc
        ->self.{{name}}.call
      end
    end

    build_proc_method(test_method)
  end
end

TestMod::TestClass.test_method_as_proc
```

I get the following error message:
```
Syntax error in expanded macro: build_proc_method:2: unexpected token: .

        ->self.test_method.call
```

When it's not wrapped in a module, everything works as expected. For instance:

```crystal
class TestClass
  def self.test_method
    puts "Do something"
  end

  macro build_proc_method(name)
    def self.{{name}}_as_proc
      ->self.{{name}}.call
    end
  end

  build_proc_method(test_method)
end

TestClass.test_method_as_proc
```

Crystal 0.26.1 (2018-08-27)
LLVM: 6.0.1
Default target: x86_64-apple-macosx

**Comment by rickychilcott** [comment]
Will close rickychilcott/crystal#1

**Comment by asterite** [comment]
The syntax is `->obj.name`, you can't have two dots there.

Just do:

```crystal
v = self.{{name}}
->v.call
```

(by the way, non of your snippets actually compile)

**Comment by asterite** [comment]
`->foo` converts a method to a `Proc` that you can later call with `call`

With that said, there's never a need to write `(->test_method).call` because that's simply `test_method()`.

Then, `->test_method.call` will take a Proc to that object's method. For example:

```crystal
class Foo
  def initialize(@x : Int32)
  end

  def bar
    puts "My number is #{@x}"
  end
end

foo = Foo.new(1)
proc = ->foo.bar
proc.call # prints "My number is 1"
```

**Comment by rickychilcott** [comment]
You're right `(->test_method).call` doesn't make sense in real code, but in the context of a macro (which is how I stumbled onto this surprise), the parenthesis appears to be needed.

Do this compile for you? Or would you expect it to?

```crystal
def test_method
  puts "Blah"
end

->test_method.call
```

I get

```
Syntax error in examples/test.cr:5: undefined variable 'test_method'

->test_method.call
```

**Comment by asterite** [comment]
That means taking the call method of the test_method variable as a proc. But test_method is not a variable, hence the error.
