### ISSUE TITLE
Remove the code, "firstNonWhite"

### ISSUE THREAD

**Issue by Laura-Mauria** [crystal-lang/crystal#6782]
My PR got locked.

I suggest the removal of
https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/tools/playground/public/session.js#L518

```
      var firstNonWhite = 0;
      while (str[firstNonWhite] == ' ') {
        firstNonWhite++;
      }
      var rendered = "\u00a0".repeat(firstNonWhite) + str.substring(firstNonWhite);
      dom.append(document.createTextNode(rendered));
```

Or,  at least change the variable names. `firstNonWhite` can be conveyed as being very racist, and this kind of terminology should not exist in code. It has no place for it.

If you continue to delete my posts, I will continue to spam. Leave one open for discussion please.

**Comment by Laura-Mauria** [comment]
@jhass Please help.

**Comment by asterite** [comment]
@bcardiff Please ban this user. Thank you.
