### ISSUE TITLE
Compiler say: Proc(Int32, Socket) is not Proc(Int32, Socket) ?!

### ISSUE THREAD

**Issue by xqyww123** [crystal-lang/crystal#6789]
Following code is failed to compile with the message `'@func' of ... must be Proc(Int32, Socket), not Proc(Int32, Socket)`.

``` crystal
require "socket"
servers = 10.times.map do |i|
  Socket.new Socket::Family::UNIX, Socket::Type::STREAM, Socket::Protocol::IP
end
```

Error message:
```
Error in line 2: instantiating 'Int::TimesIterator(Int32)#map()'

in /usr/lib/crystal/iterator.cr:658: instantiating 'Iterator::Map(Int::TimesIterator(Int32), Int32, Socket).class#new(Int::TimesIterator(Int32), Proc(Int32, Socket))'

    Map(typeof(self), T, U).new(self, func)
                            ^~~

in /usr/lib/crystal/iterator.cr:665: instance variable '@func' of Iterator::Map(Int::TimesIterator(Int32), Int32, Socket) must be Proc(Int32, Socket), not Proc(Int32, Socket)

    def initialize(@iterator : I, @func : T -> U)
```

It happens on both `0.26.1` and `0.25.1`, see [play.crystal](https://play.crystal-lang.org/#/r/52uv).

**Comment by xqyww123** [comment]
BTW, I also find `Socket#accept` in Fiber doesn't be handled with `epoll` but a direct `accept` syscall so make entire program stuck (even cannot be interrupted by sig-int). Just replacing `Socket` with `UNIXSocket` and leaving other code intact resolves the problem. So I really doubt the `Socket` class.

**Comment by RX14** [comment]
@xqyww123 `Socket#accept` uses epoll, unless you set `Socket#blocking = true`. `UNIXSocket` uses the exact same accept method as `Socket`.

**Comment by LesterCano** [comment]
Hello,

I modified some instances of the `firstNonWhite` variable, as it could possible have a racist undertone. "First non white person of whom?"

Also changed it to be more expressive for what that variable is actually doing (and less oppressive).

Since @mverzilli thinks it's okay to close my PR without any justification. You will get spammed. Enjoy!

**Comment by straight-shoota** [comment]
Reduced example:
```cr
class Foo
end

class Bar < Foo
end

10.times.map do |i|
  Foo.new
end
```

`Bar.new` instead of `Foo.new` works. It seems that the issue is triggered because the return type has also child types. `Foo.new` doesn't error when `Bar` is not defined.

**Comment by asterite** [comment]
Reduced:

```crystal
class Foo
end

class Bar < Foo
end

class Capture(T)
  def initialize(@block : -> T)
  end
end

def capture(&block : -> T) forall T
  Capture.new(block)
end

capture do
  Foo.new
end
```

**Comment by jwoertink** [comment]
It looks like this is the same thing I'm running in to. Interesting thing though is with my example, I'm using:

```crystal
Concurrent::Future.new { fetch_site_latest }

def fetch_site_latest
  some_big_query.map {|result| DiscJockey::Burns::Decorator.new(result) }
end
```

```
In /usr/local/Cellar/crystal/0.30.1/src/concurrent/future.cr:15:56

 15 | def initialize(run_immediately = true, delay = 0.0, &@block : -> R)
                                                           ^-----
Error: instance variable '@block' of Concurrent::Future(Array(DiscJockey::Burns::Decorator)) must be Proc(Array(DiscJockey::Burns::Decorator)), not Proc(Array(DiscJockey::Burns::Decorator))
```

If I move the `map` part outside of the Future block, then the app compiles for me.

```crystal
# this compiles fine
Concurrent::Future.new { fetch_site_latest }.get.map {|result| DiscJockey::Burns::Decorator.new(result) }

def fetch_site_latest
  some_big_query
end
```
