### ISSUE TITLE
Support regex backreferences (Was: How does regex backreferencing work?)

### ISSUE THREAD

**Issue by phortx** [crystal-lang/crystal#684]
I had a gsub call, which I copy pasted from ruby and containted a backreference, which worked very well in ruby. In crystal the backreference doesn't work neither with `\` nor with `$`. I've read the api doc and the general doc and some parts of the crystal source code but couldn't find any advice.

Here's my gsub call: `.gsub(/^-*(.+)-*$/, "\\1")`. It returns in an empty string.

Any idea?

**Comment by asterite** [comment]
This is not implemented yet.

**Comment by kirbyfan64** [comment]
I thought Crystal used PCRE?

**Comment by phortx** [comment]
That explains it ... Thank you.

**Comment by asterite** [comment]
@kirbyfan64 is there a PCRE function for doing gsub? I can't find it. We are doing gsub by ourselves, finding matches and replacing them. That means a "\\1" will be part of the final string unless we explicitly find those markers.

**Comment by asterite** [comment]
@kirbyfan64 Totally offtopic, do you know [this game](http://en.wikipedia.org/wiki/Kirby_64:_The_Crystal_Shards)? The coincidence is huge :-P

**Comment by phortx** [comment]
@kirbyfan64 @asterite Oh yes the coincidence in strong in this one :D

**Comment by kirbyfan64** [comment]
@asterite Yes. Where do you think I got my user name from? ;)

**Comment by asterite** [comment]
Do we need this? You can always use the block version of `gsub`: http://play.crystal-lang.org/#/r/3fd

Supporting backreferences will make every gsub with a string call slower because these will have to be scanned.

**Comment by ysbaddaden** [comment]
I got hit with missing backreferences in gsub today. It's an habit and I think it's easier to read for simple replacements. Also, the block form isn't available in macros, yet.

I guess it depends on how much slower it would be.

**Comment by kirbyfan64** [comment]
Why not used a named argument? That way, the normal case won't really be slowed down any, but passing `true` to the argument would cause the string to be scanned for backrefs.
