### ISSUE TITLE
[RFC] How to implement channel select correctly?

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#688]
Right now, it's like this:

```crystal
ch1 = ...
ch2 = ...

case Channel.select(ch1, ch2)
when ch1
  ch1.receive
when ch2
  ch2.receive
end
```

`Channel.select` returns the first available channel, that's why it works in the `case` expression.

However, once we spread coroutines in many threads, it might happen that between the `select` call and the `receive` call another thread receives a channel's value.

There's also the problem that you can avoid calling `receive` afterwards. And also, there's no way to select a channel for *sending* a value instead of receiving.

In Go this can't happen because a [select statement](https://golang.org/ref/spec#Select_statements) is part of the language and the syntax forces you to either send or receive a value.

Anyone has a solution for this? :-)

One solution is to introduce new syntax for a select expression, similar to Go, but we'd like to leave that as the last option so we can brainstorm this.

**Comment by kostya** [comment]
let Channel.select return tuple `{ch, value}`

**Comment by asterite** [comment]
But `value` will then be the union of all the types of the channels :-(

**Comment by will** [comment]
It could be a tuple of `{Channel, Union, Class}`, and if [`as_cast`](https://github.com/will/crystal-pg/blob/master/src/core_ext/class.cr) was a proper part of the language, you could pop it out of the union type. 

That's a little ugly though, and new syntax for this wouldn't be all that too bad.

**Comment by nate** [comment]
[I did this for ruby](https://github.com/igrigorik/agent). `select` is the big wrench in the works, at least when you can't control thread scheduling. It really adds a lot of complication. To make it work I had to enqueue attempted operations (push/pop) on all channels (and when an operation comes in I resolve any enqueued operations waiting on a channel) and only allow one to succeed using a [Once](https://github.com/igrigorik/agent/blob/master/lib/agent/once.rb) inside `select` and then de-queue operations related to the `select` when one of the operations succeeds.

**Comment by ozra** [comment]
No strong opinion here, but it wouldn't be terrible with specific language constructs to handle it. Would possibly also be easier for wilder eventual future behind the scenes implementations without worries of affecting the flow in user code based on regular sequential imperative constructs - pure speculation.
