### ISSUE TITLE
Range#sum appears to not be working

### ISSUE THREAD

**Issue by dscottboggs** [crystal-lang/crystal#6892]
Code:    `[0..100].sum`
Expected output: 101 I think, or perhaps 5050?
Output received: (compiler error)
```
Error in /home/scott/Documents/code/range_sum.cr:1: instantiating 'Array(Range(Int32, Int32))#sum()'

[0..100].sum
         ^~~

in /usr/lib/crystal/enumerable.cr:1112: undefined method 'zero' for Range(Int32, Int32).class

    sum Reflect(T).first.zero
                         ^~~~

================================================================================

Range(Int32, Int32).class trace:

  /usr/lib/crystal/reflect.cr:7

      def self.first
               ^~~~~

  /usr/lib/crystal/reflect.cr:8

        {% if X.union? %}
        ^

  macro macro_94193891566464 (in /usr/lib/crystal/reflect.cr:8):2

          X
          ^

```
Crystal: 
```
Crystal 0.26.1 (2018-09-06)

LLVM: 6.0.1
Default target: x86_64-pc-linux-gnu
```

The documentation says this works for `Int`, and that applying it to other types will use `Enumerable#sum`, but using `Int` gives an error about not being able to use it, and not specifying gives the above error.

Is this me or is this broken?

**Comment by Sija** [comment]
Range is denoted by `()`, so you'd need to use `(0..100).sum` - which works.

**Comment by ysbaddaden** [comment]
Yes, `[0..100]` is the literal for an Array(Range) not a Range. You can use parenthesis instead, for example `(0..100)`, for the expression to be a Range and be capable to call methods on it.

**Comment by dscottboggs** [comment]
Actually what the problem was in my real code was that I was trying to use Range.class by accident instead of an instance. But in this case, yeah, I double messed up by typing the wrong thing into the playground
