### ISSUE TITLE
JSON mapping - key parameter: "expecting token 'CONST', not 'DELIMITER_START"

### ISSUE THREAD

**Issue by marco-fp** [crystal-lang/crystal#6893]
When I try to specify the key name in the JSON file for the mapping I receive the following error:
` "expecting token 'CONST', not 'DELIMITER_START"`

I've searched the documentation and couldn't find any specification to do this differently:
[Docs](https://crystal-lang.org/api/0.21.0/JSON.html#mapping-macro)
[JSON.mapping code](https://github.com/crystal-lang/crystal/blob/c2c2276ec667171af5c2347490f49acdbdc4a3ca/src/json/mapping.cr#L62)

- Crystal version: 0.26.1
- OS: Ubuntu 18.04

- Code: [play.crystal-lang](https://play.crystal-lang.org/#/r/54ic)
```Crystal
  struct SomeStruct
    JSON.mapping(
      someAttribute : {type: String, key: "e"},
    )
  end
```

Thanks :)

**Comment by ysbaddaden** [comment]
This is `someAttribute:` (symbol). Don't put a space before the colon.

**Comment by marco-fp** [comment]
Thanks for the fast reply! (and sorry for the inconvenience)
