### ISSUE TITLE
FreeBSD can't make crystal source with gmake

### ISSUE THREAD

**Issue by lifesheep** [crystal-lang/crystal#6898]
gmake isn't compiling. 
I get the error: related to crystal of: You need to have a crystal executable in your path!

As following the instructions for "Other sources"
ln -s [scrap/crystal] /usr/local/bin/crystal

`[mookie@foxden /.srv./scrap/crystal-0.26.1 ] gmake
Using /usr/local/bin/llvm-config40 [version=4.0.1]
c++ -c  -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc -I/usr/local/llvm40/include -O2 -pipe -fstack-protector -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -Werror=date-time -std=c++11 -fcolor-diagnostics -ffunction-sections -fdata-sections -O2 -pipe -fstack-protector -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include  -fno-exceptions -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
cc -fPIC    -c -o src/ext/sigfault.o src/ext/sigfault.c
ar -rcs src/ext/libcrystal.a src/ext/sigfault.o
CRYSTAL_CONFIG_PATH="/.srv./crystal-0.26.1/src" ./bin/crystal build  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
You need to have a crystal executable in your path!
gmake: *** [Makefile:122: .build/crystal] Error 1

**Comment by ysbaddaden** [comment]
Crystal is written in Crystal and thus requires a Crystal binary to bootstrap itself —either cross compiled from another system or using a FreeBSD binary.

AFAIK crystal is available in official FreeBSD ports. See https://www.freebsd.org/ports/lang.html

**Comment by lifesheep** [comment]
thxs. ill give this another go after some sleep.

**Comment by straight-shoota** [comment]
Installation instructions on FreeBSD can be found in crystal-lang/crystal-book#283
