### ISSUE TITLE
parsing error on numerical expression

### ISSUE THREAD

**Issue by jzakiya** [crystal-lang/crystal#6902]
I don't know if this is related to something else, but here it is. Using Crystal 0.26.1

The code that uses this expression compiles (using ``--release``) without errors but when run it hangs.
```
( d >>= ( 1 + ((d>>1) & 1)^1) ) if d.even?
```
However, both of these compile AND operate correctly when run.

```
( d >>= (((d>>1) & 1)^1) + 1 ) if d.even?

or

x = ((d>>1) & 1)^1; d >>= (1 + x) if d.even?
```

It seems the problem is correctly parsing the expression ``((d >> 1) & 1)^1``.

Here is what the correct output should be (trailing '0's are stripped off last two bits.):

```
     d in  | d out
-----------|-------
 7 = xx111 |   7 = xx111
 6 = xx110 |   3 = xxx11
 5 = xx101 |   5 = xx101 
 4 = xx100 |   1 = xxxx1
 3 = xx011 |   3 = xx011
 2 = xx010 |   1 = xxx01
 1 = xx001 |   1 = xx001
```

**Comment by jzakiya** [comment]
I found what the problem was (though kind of subtle).

The original code that hung was this (minus the unnecessary outside parenthesis).
```
d >>= (1 + ((d>>1) & 1)^1) if d.even?
```
Taking away the outside parenthesis also causes the same problem.
```
d >>= 1 + ((d>>1) & 1)^1 if d.even?
```
Adding a left parenthesis solved the problem.
```
d >>= 1 + (((d>>1) & 1)^1) if d.even?
```
It seems that: ``1 + ((d>>1) & 1)^1`` parses to this: ``[1 + ((d>>1) & 1)] ^ 1``. 
This also hangs: ``((d>>1) & 1)^1 + 1``, and probably parses to this: ``((d>>1) & 1) ^ [1 + 1]``.
This behavior is also consistent in Ruby.

So it was my misunderstanding|forgetting about operator precedence.
Maybe in the docs examples like this can be highlighted more to emphasize this type of gotcha.

So it wasn't a parsing error it was me, and you can close this now.
Thanks.

**Comment by asterite** [comment]
What do you mean "hangs"?

**Comment by RX14** [comment]
@asterite presumably never reaching the termination condition of a loop, with the loop code not shown.
