### ISSUE TITLE
Document Hash initializers

### ISSUE THREAD

**Issue by KCErb** [crystal-lang/crystal#6918]
I'd like to add some in-line docs for the hash constructors. The contribution guide recommends opening an issue, so here it is.

It seems to me that I can reuse some of what ruby already has documentation-wise (https://docs.ruby-lang.org/en/2.0.0/Hash.html). My main goal is to document the "initialized with a block" feature, so I'd probably leave the "from YAML" and "from JSON" stuff alone to avoid talking about something I don't understand properly.

That said, if folks would prefer an "all or none" approach, I'd be happy to study up / play with those as well to produce full docs.

**Comment by RX14** [comment]
For docs you're better off just opening a PR. I think the "if you want to add a new feature" bit of "Please always open a new issue before sending a pull request if you want to add a new feature to Crystal" should be in bold too...

**Comment by KCErb** [comment]
Fair enough, will do.

thanks :)
