### ISSUE TITLE
Lazier automatic casts when used in macros

### ISSUE THREAD

**Issue by ezrast** [crystal-lang/crystal#6922]
It would be nice to be able to do this ([carc.in](https://carc.in/#/r/5705)):
```crystal
enum Foo
  One
  Two
end

class HashWrapper
  property hash = {} of String => Foo
  
  forward_missing_to @hash
end

hw = HashWrapper.new
hw.hash["x"] = :One # This works
hw["y"] = :Two      # This doesn't
```
In the second line, `:Two` doesn't get cast because it's passed to a macro, not directly to a method that takes a `Foo`. Would it be possible and wise to defer automatic casts until after macros are expanded? The downside I can think of is that macro authors can no longer trust their type checks when they look for `SymbolLiteral`s, but that doesn't seem too common.

**Comment by straight-shoota** [comment]
This doesn't have anything specific with to do with calling the macro `forward_missing_to`. It's just another quirk of `method_missing` hook (which also happens to be a macro).
I don't this can be solved.

I'd recommend explicitly declaring the forwarded methods anyway. This clearly describes the exposed API and works with `responds_to?`.

**Comment by ezrast** [comment]
Thanks, you're right. The thing I'm asking for is already the current behavior. My bad.
