### ISSUE TITLE
skip_to_end in HTTP::Content#close: Useful or problematic?

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#6924]
`HTTP::Content` provides a single method, `#close` that delegates to super (`IO#close`) but ensures the IO is completely consumed before closing via `skip_to_end`. 

I can't see how that is actually useful, and at least, it is confusing to the user. It doesn't just close the IO in it's current state but completely consumes it until the sender is done (a request from `curl -T /dev/urandom example.com`  would never actually close...).

This feature seems to be the only reason for the `HTTP::Content` type in the first place and was introduced in 5adc780f. Unfortunately, I can't find an explanation for the reasons behind that and there are no specs documenting a change in behaviour.

At the point of that commit, there was only a single `HTTP::Response` class and not yet separated between server and client. Not sure if that matters in any way.

I could only think of a possible explanation in the context of reusing a connection (HTTP keep-alive), where you would obviously need to completely consume the previously sent content before you could read the next request or response from the IO.
But that actually only matters in `RequestProcessor` and as far as I can see, wouldn't demand for an override of the close method. This would be it (and the special behaviour is even mentioned here):

```diff
--- i/src/http/server/request_processor.cr
+++ w/src/http/server/request_processor.cr
@@ -57,6 +57,7 @@ class HTTP::Server::RequestProcessor

         # Skip request body in case the handler
         # didn't read it all, for the next request
+        request.body.try &.skip_to_end
         request.body.try &.close
       end
     rescue ex : Errno
```
Without that, only `spec/std/http/server/server_spec.cr:579` would fail.

With this change, we could remove `HTTP::Content#closet`. However, it would still provide a point of attack when a client just keeps writing to the socket.

Some light improvement could be to provide a means for the handler to force closing the connectio (by checking the response has `Connection: keep-alive` and `Content-Length` headers or closing the request IO in the handler directly). There could also be some limit to the amount of bytes that will be read to avoid never-closing connections.

But all in all, I think it might perhaps be best to simply close the entire connection when there is still content on the input stream after the handler has completed. The handler should make sure to consume the body if there should be one.
The consequence is only that you can't reuse the connection if the client sent a body that the server didn't expect. I don't think that's too much to worry about.

/cc @waj

Initially mentioned in https://github.com/crystal-lang/crystal/pull/6912#issuecomment-428293598

**Comment by asterite** [comment]
> I could only think of a possible explanation in the context of reusing a connection (HTTP keep-alive), where you would obviously need to completely consume the previously sent content before you could read the next request or response from the IO.

That's the reason it was implemented. But alternative ways are probably fine too (I don't have much time to read all this issue now).

**Comment by RX14** [comment]
It doesn make me notice that you can totally break `keep-alive` by using `ctx.request.body = ` though.

**Comment by straight-shoota** [comment]
@RX14 What?
