### ISSUE TITLE
Add a interpreter, to compete against NodeJS

### ISSUE THREAD

**Issue by jefer94** [crystal-lang/crystal#6938]
I know, that Crystal is a low level language, and is it very difficult do a fast compiling, or a hot reload like Webpack does

I think that a interpreter for de development enviroment, i should be atractive to the NodeJS programmers, because it'll improve how fast of a development and in the slow machines, it's will not use 1GB of RAM while compile it

I think that, it's the only that Crystal need, to be more atractive

If also you do a equal asignation like this `<-/\*$#%:=`, for the Go programmers, it'll look great (it's a joke)

And... why Crystal ain't much popular?

**Comment by kirbyfan64** [comment]
> why Crystal ain't much popular?

Considering it's relative youngness and the fact that it's still in beta, I'd say it's doing quite well. 

I'm pretty sure this would take an enormous amount of effort and wouldn't quite play nicely with Crystal's type inference.

**Comment by jefer94** [comment]
It's true, Crystal is a promising language

Is that, sentry is great, but while it's compiling, my RAM is used at 100% (2GB), and I'll is used Kernal, GraphQL, RocksDB and Dotenv, and with it my RAM almost overflows

Maybe if I add a new dependency, my RAM simply is overflow

I don't know, I think that maybe improve the development enviroment can be great for some peoples

**Comment by j8r** [comment]
In the case of Crystal, incremental compilation is a good solution – it would reduce time between compilation.

Writing another interprered pseudo-Crystal isn't a solution at all. This needs lots of effort and you won't be sure the code will behave the same because the implementation will be different.

**Comment by jefer94** [comment]
Other way could be that, Crystal will make `.o` files, and it'll be saved in the temp folder, it could improve the performance, and save a copy of original source to do a diff, and could know which file compile

Only before of open the browser, I'd compile the project and it could be more faster after it

**Comment by ysbaddaden** [comment]
Please open discussions on other community services (mailing list, ...). Not rh bugtracker.

There already are issues about speeding up the compiler, incremental compilation, ...

**Comment by jefer94** [comment]
In other community they are going to write the code in the Crystal compiler?

I just have to say that, you should be kinder, usually the issue is linked to the duplicate issue, and then the duplicate issue closes

If I Write this issue in StackOverflow, never be implemented it, the suggestion in conclution is wrong

The links can be utils in this cases

**Comment by asterite** [comment]
Also, in general, any tasks that is huge won't be done because right now there's lack of time/people to work on the existing code, so adding an interpreter on top of that is not feasible.

That said, if you want to write an interpreter for Crystal you are free to do so, and eventually you can send a PR in this repo.

**Comment by jefer94** [comment]
I understand, but the `.o` can be implemented? or already exists? and thanks

**Comment by asterite** [comment]
The `.o` thing is more or less done right now, but it's not perfect. In general, there's no way to do incremental/modular compilation in Crystal without making huge changes to the language.

**Comment by jefer94** [comment]
Well, thanks
