### ISSUE TITLE
Channel::Unbuffered#send doesn't raise when resumed from close

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/crystal#6948]
I noticed that closing a `Channel::Unbuffered` with a pending send merely resumes the sender fiber instead of raising an exception. This is surprising, because the value wasn't delivered, and further attempts to send a value will raise a Channel::Closed exception.

Is the behavior correct? or is it a bug, and we should raise when the value wasn't delivered? but maybe we can't be sure that the value was actually delivered?

To reproduce:

```crystal
ch = Channel::Unbuffered(Nil).new

spawn do
  ch.send(nil)   # will simply return
  # ch.send(nil) # will raise Channel::ClosedError
end

spawn { ch.close }
sleep(0)
```

**Comment by bcardiff** [comment]
I think we can't be sure it is delivered unless there is a timeout. The unbuffered channel can hold one long living value waiting to be received, sometime in the future.

If the channel is closed at the moment of sending, then yes, an exception can and must be raised.

**Comment by straight-shoota** [comment]
This has been fixed at some point:
```cr
ch = Channel(Nil).new

spawn do
  ch.send(nil) # raises Channel::ClosedError
end 

spawn { ch.close }
sleep(0)
```
