### ISSUE TITLE
Syntax highlighting for annotation

### ISSUE THREAD

**Issue by Heaven31415** [crystal-lang/crystal#6949]
I'm not sure if it is the right place, but right now there is no support for syntax highlighting for annotations:

```crystal
annotation Foo
end
```
How do we fix that?

**Comment by j8r** [comment]
This is up to GitHub. It may have a repo for.

**Comment by straight-shoota** [comment]
For syntax highlighting on Github, the language specification needs to be updated in https://github.com/highlightjs/highlight.js

**Comment by bew** [comment]
https://github.com/highlightjs/highlight.js/pull/1875 :smiley:

**Comment by straight-shoota** [comment]
So it's actually https://github.com/crystal-lang-tools/language-crystal for Github highlighting 🤷‍♂️ 

I opened an issue there: https://github.com/crystal-lang-tools/language-crystal/issues/26
