### ISSUE TITLE
Upcasting bug in compiler (0.26.1)

### ISSUE THREAD

**Issue by ljuti** [crystal-lang/crystal#6974]
Possible compiler bug in Crystal 0.26.1 while upcasting an abstract struct into a struct. May be similar to the issues #6760, #5496, #1346.

## Code to Reproduce

https://gist.github.com/ljuti/d719507523f6c9fc8725672b893b0951

The gist includes console output from a development machine running OSX High Sierra 10.13.6. 

## Environment

```
$ crystal -v
Crystal 0.26.1 (2018-09-26)

LLVM: 6.0.1
Default target: x86_64-apple-macosx
```

**Comment by straight-shoota** [comment]
Reduced: 
```cr
abstract struct BaseFactory
end
struct DummyFactory < BaseFactory
end

struct Config
  alias AcceptedFactories = BaseFactory.class | DummyFactory.class

  def initialize(@given_factory : AcceptedFactories)
    @given_factory.new
  end
end

Config.new(DummyFactory)
```

Please always try to minimize examples by removing everything that's not necessary to reproduce the error.

**Comment by straight-shoota** [comment]
It could be an issue that the ivar has type `BaseFactory.class` and an abstract struct can't be instantiated.

**Comment by jhass** [comment]
This no longer reproduces in Crystal 0.34.
