### ISSUE TITLE
unexpected ',' in type

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#6980]
```Crystal
module Test
  class Foo; end
  class Bar; end
  
  TYPES = {
    Foo => [] of Symbol,
    Bar => [] of Symbol
  }
end
```

https://play.crystal-lang.org/#/r/5avh

```
Syntax error in eval:6: unexpected ',' in type (use parentheses to disambiguate)
```

Only happens when having the comma on an empty array of T

**Comment by asterite** [comment]
You have to do what the error message tells you :-)

```crystal
module Test
  class Foo; end
  class Bar; end

  TYPES = {
    Foo => ([] of Symbol),
    Bar => ([] of Symbol),
  }
end
```

The reason of the error is that `Symbol, Bar` could be the start of a Proc type.

**Comment by Blacksmoke16** [comment]
@asterite @j8r Well now the new problem is i get:
```crystal
undefined macro method 'Generic#map'

    CrSerializer::Assertions::NotNil => Array(Symbol),
```
and
```crystal
undefined macro method 'Expressions#map'

    CrSerializer::Assertions::NotNil => ([] of Symbol),
```

Since im iterating over the key/values.  
```crystal
        {% for ivar in @type.instance_vars %}
          {% for t, v in CrSerializer::Assertions::TYPES %}
            {% ann = ivar.annotation(t.resolve) %}
              {% if ann %}
                {{v.map { |f| ann[f] }.join(',').id}}
              {% end %}
          {% end %}
        {% end %}
```
Ideally this would be a lot cleaner if you could iterate over all the annotations on an ivar, and iterate on keys of the annotation, but that would prob be best for another issue.

**Comment by Blacksmoke16** [comment]
For now i guess i'll just add a dummy var to the array and just do nothing with it in the initializer.

**Comment by Blacksmoke16** [comment]
For future reference, solution was to do `{% v = v.expressions[0] if v.is_a?(Expressions) %}` to get the actual value of the expression if it was one.
