### ISSUE TITLE
Iterate over ivar's annotations/annotation keys

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#6984]
Currently an ivar's annotation can only be accessed manually, one by one, where the name has to be known.  Being able get an array of annotations on an ivar would dramatically simplify this.

On a similar note the only way to get a value from an annotation is knowing the name of the key.  Having a method to return an array of keys on the annotation would further simply things.  

Could look something like:
```crystal
{% for ivar in @type.instance_vars %}
  {% for annotation in ivar.annotations %}
    {{annotation.keys.map { |k| annotation[k] }.join(',').id}}
  {% end %}
{% end %}
```

Based on https://github.com/crystal-lang/crystal/issues/6980#issuecomment-432220673

**Comment by bew** [comment]
Whats your usecase?

**Comment by Blacksmoke16** [comment]
@bew I would be using this for https://github.com/Blacksmoke16/CrSerializer.

I'm working on changing the syntax to like:
```crystal
@[Serialize::Assertions::NotBlank(message: "Password should not be blank")]
@[Serialize::Assertions::Size(range: 0..50, min_message: "Password is too short", max_message: "Password is too long")]
property password : String
```

Currently i'm having to define a hash that contains the annotation name and fields. like:
```crystal
TYPES = {
    NotBlank => [] of Symbol,
    Size => [:range, :min_message, :max_message]
  }

{% for ivar in @type.instance_vars %}
  {% for t, v in TYPES %}
    {% ann = ivar.annotation(t.resolve) %}
      {{t.id}}Assertion.new({{v.map { |f| ann[f]}.join(',').id}}) # new up assertion class
  {% end %}
{% end %}
```

**Comment by asterite** [comment]
That won't work because you are assuming the only annotations an ivar will have are the ones you are interested in.

**Comment by Blacksmoke16** [comment]
Would have to have some logic to make sure the current annotation is of a given name or something yea.  I don't think there is a name property on an annotation, so yea, that wouldn't be doable atm.

**Comment by RX14** [comment]
@Blacksmoke16 why not the other way around: iterate the list of annotations you're interested in? Surely it'd have approximately the same code length.

**Comment by RX14** [comment]
@Blacksmoke16 By the time you add in the required `{% if TYPES.includes? annotation %}` to your ideal solution they're about the same complexity and code.
