### ISSUE TITLE
Standard error handling without stack unwinding

### ISSUE THREAD

**Issue by j8r** [crystal-lang/crystal#6987]
For now we can construct our own [Exception](https://crystal-lang.org/api/master/Exception.html) and set `#callstack = nil` to avoid having a backtrace. (needs more docs through).

## Performance

`raise` unwind the stack by default, which is expensive, about 10x/20x than a `return`.
Raising an error without the callstack will be comparable to a `return` statement.

## Cases

There are cases where the backtrace is useful, like `Index Out Of Bounds`, `Invalid Memory Access`, but other cases that aren't.
For example `File not found`, or `Invalid command option`, or parsing errors already explains what some where the problem is.

## Proposition

We may have a new method name like `raise!` to have two alternatives for raising exceptions - one with and one without a backtrace. Backward compatibility can be kept.

## In other Languages

[Rust](https://doc.rust-lang.org/book/second-edition/ch09-00-error-handling.html) has [Result<T, E>](https://doc.rust-lang.org/book/second-edition/ch02-00-guessing-game-tutorial.html#handling-potential-failure-with-the-result-type) which doesn't unwind the stack. This is an enum which has two variant: `Ok` and `Err` to handle both success and failure cases. `panic!` is for unrecoverable errors and unwinds the stack.

[Swift](https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html) uses the `Error` protocol. Error handling is done with `try`/`catch`, but unlike other languages the call stack isn't unwinded. Swift also interoperates with Cocoa's `NSError`.

**Comment by jhass** [comment]
I'm fuzzy on how your proposal would look like on the call side. Could you expand?

**Comment by straight-shoota** [comment]
I think an important detail is what semantic meaning an exception has. If it is an unexpected error, there should always be a strack trace to help debugging.

When exceptions are used to communicate results of subroutines (=expected logical failures), they are typically completely handled by the calling environment and a call stack has no value. It would never be inspected anyway.

The methods `#[]` and `#[]?` on `Enumerable` demonstrate the different approaches:

```cr
# with exception:
begin
  array[0]
rescue IndexError
  do_something_else
end

# without exception:
array[0]? || do_something_else
```

Now, obviously it's not always as simple as that. Sometimes, such failure messages need to be passed through many stack levels. So it's more difficult to enable communication of failure return values.
In this cases, it might make sense to use exceptions and avoiding a call stack would speed that up a lot. Maybe there the compiler could enforce that such exceptions need to be handled, similar to Java's checked exceptions...

**Comment by j8r** [comment]
@straight-shoota With `Nil` you don't know why the methods had failed, only if it does or not. This also leads to error handling à la Go with `if` nil checks, which are far to be the most ergonomic.
For now I have to return a custom type that wrap the error message.
Please not `Java` for exception handling, IMO Rust and Swift approaches are a lot better.

**Comment by j8r** [comment]
@jhass I haven't the knowledge to propose a proper solution. I just know it may be possible to have an empty backtrace with https://github.com/crystal-lang/crystal/pull/6945 (I may be unrelated, because maybe the stack is still unwinded but not shown?).
I posted this issue because I'm liking how Rust and Swift handle exceptions, I was wondering if/how Crystal  could take from their approaches.

**Comment by ysbaddaden** [comment]
`Result<T, E>` is a convention in Rust, similar to `Option<T>` which is what we refer to as the `T?` nilable in Crystal. You can have a `Result(T, E)` that would mimic the Rust API if you want:

```crystal
struct Result(T, E)
  getter value : T?
  getter error : E?

  def initialize(@value : T?, @error : E?)
  end
end
```

But that's pushing an exceptional/abnormal case handling from "let the exception bubble up the stack" to "the developer must check/handle/bubble the error object up the stack", which is both painful & noisy.

**Comment by j8r** [comment]
@ysbaddaden good point. Swift's approach to throw exceptions whithout call stack unwinding, that are try/catchable may be the best bet.

**Comment by asterite** [comment]
@j8r So how do you get the callstack in case an exception happens in Swift?

**Comment by j8r** [comment]
@asterite you can print the callstack at anytime with `print(Thread.callStackSymbols)`

At the end, its about having a standard alternative to the `?` methods returning `Nil`, but returning an Object having an error message. The difference is, the effect can be like a `return`, but rescuable.

**Comment by jhass** [comment]
I feel like the whole proposal is way too vague and up in the air to be the basis of a useful discussion at this point in the language. I'd vote to close this until somebody bothers with a more throughout and specifc proposal.

**Comment by ysbaddaden** [comment]
So, Swift trades implicit unwind on raise (to build the backtrace) to explicit unwind (similar to `#caller`) on-demand. Why not.

It will still unwind the stack, to bubble the exception up the stack, but can spare the unwind to build the callstack.

**Comment by j8r** [comment]
I was thinking if something in this flavor:
```crystal
struct Error
  getter message : String
  def initialize(@message)
  end
end

def throw(message : String = "Error during execution")
  Error.new message
end

macro try(method)
  if (__result = {{ method }}).is_a? Error
    return __result
  else
    __result
  end
end

def failing_method(fails : Bool) : String | Error
  return Error.new "This method always fails" if fails
  "Succeed"
end

def operations : String | Error
  try failing_method false
  try failing_method true
  "Operations succeed"
end

x = operations
pp!({x, x.class, typeof(x)})

if x.is_a? Error
  puts "lets rescue"
  puts x.message
else
  puts "all is fine"
end
```

**Comment by RX14** [comment]
I would tend to treat this as a request for better performance with raise. There are plenty of techniques which the crystal compiler could apply later to improve raise performance without a breaking change. The compiler can heuristically optimize returning up a single level to not unwind at all. You can also run unwind handlers in a seperate stack (windows seh already does this) so that accessing the backtrace becomes an on-demand unwind. 

I don't think we neecesarily need new api or features to do what you want.

**Comment by Proximyst** [comment]
Although RX14 has practically thrown out the idea for new features, I'd love to just throw in my thoughts on this as a Rust developer.

As shown in the OP, Rust has `Result<T, E>`, and I believe that Crystal could quite easily have something close if not identical to this. `begin`/`rescue` could handle return types like these behind the scenes to remove the entire rewind, but also have other supertypes, like Java has `Error` and Rust has `panic!`, for unrecoverable errors which would be the same behaviour as right now.

This would make this code:
```crystal
def attempt_bool : Bool
    raise Exception.new "no bool! fooled 'ya!"
end

# Error is unrecoverable, and rewinds stack
class CustomError < Error; end
def panic_me
    raise CustomError.new
end

# Exceptions could also be possible to coerce into `false` for the proposed `||`
# but that would become messy quickly
begin
    attempt_bool
rescue ex : Exception
    # handle ex
    # no stack rewind!
end

begin
    panic_me
rescue err : CustomError
    # handle err
    # stack rewinded, oh noes!
end
```

Be this on compile-time, as partially shown by j8r:
```crystal
def attempt_bool : Bool | Exception # or Result(Bool, Exception) maybe?
    Exception.new "no bool! fooled 'ya!"
end

# Error is unrecoverable, and rewinds stack
class CustomError < Error; end
def panic_me
    raise CustomError.new
end

returned = attempt_bool
if returned.is_a?(Exception)
    # rescue block; returned is now Exception
    # the stack wasn't rewinded, cause it didn't have to be rescued
else
    # rest of begin block
end

begin
     panic_me
rescue err : CustomError
    # handle err
    # stack rewinded!
end
```

What this would also allow, though, is this:
```crystal
def attempt_bool : Bool
    raise Exception.new "no bool! fooled 'ya!"
end

attempt_bool().typeof
# => Result(Bool, Exception | OtherPossibleExceptionTypes)
# or
# => Bool | Exception | OtherPossibleExceptionTypes
#
# either or will properly enforce exception safety, but the Result(T, E) could allow
# for Result(T, E).unwrap : T or unrecoverable error, as in Rust
# 
# it would also allow for the possibility of Result(T, E).map(Proc(T, R))
# which could allow for quick succession methods/functions allowing for easier to handle
# return types, due to them only handling the result if it's not an error
```

Anyone who is any familiar with Rust will know I'm collecting a lot of my thoughts about this from it, but that's simply because *I* find it to be a wonderful system, although it's a tad too verbose (which I hoped to have removed a bit of here).

**Comment by RX14** [comment]
I don't want `raise` to magically change the return type of the method, it's too hard to reason about and would break a lot of existing code. I'm not sure copying rust translates well to crystal here.

**Comment by kirbyfan64** [comment]
What about something kind of like [Swift does](https://www.mikeash.com/pyblog/friday-qa-2017-08-25-swift-error-handling-implementation.html)? It seems to instead return errors in a special register, and the only function-level requirement is that it's labeled as `throws` (Swift itself infers the errors, so it's less fragile than e.g. Java's exceptions while still being fully checked). 

I also have and [old idea for implicitly converting raises into returns](https://refi64.com/posts/an-idea-for-concise-checked-error-handling-in-imperative-languages.html), a bit like the above mentioned syntax but more concise. However, I think Swift's approach is probably the better one.

**Comment by j8r** [comment]
I don't think too that having a new way to handle errors has its place in the stdlib, not yet.
I've created https://github.com/j8r/error.cr 
```cr
module Test
  def self.it_throws
    Error.throw "Oops!"
  end
end

p Test.it_throws
```
result: 
```
Oops! (Error)
   from src/app.cr:3 in 'Test.it_throws'
```

**Comment by sudo-nice** [comment]
It feels like sort of Ruby's `throw/catch` could help here.
