### ISSUE TITLE
Undefined method with empty array of abstract class T

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#6996]
https://play.crystal-lang.org/#/r/5cxo

```Crystal
abstract class Assertion
  abstract def valid? : Bool
end

class MyAssertion(T) < Assertion 
  def valid? : Bool
    false
  end
end

class Validator
  getter assertions : Array(Assertion) = [] of Assertion
  
  def validate
    @assertions.reject(&.valid?)
  end
end

pp Validator.new.validate
```

The example above gives an error saying `undefined method 'Assertion#valid?()'`

However if you replace the `getter assertions` with `getter assertions : Array(Assertion) = [MyAssertion(String).new] of Assertion` It'll work fine.  It'll also work fine when replacing the `abstract def valid? : Bool` with an actual method that returns a bool, even with the empty array.

It looks like when the array is empty the type of each value is inferred to be `Assertion`. Which doesn't implement the `valid?` method itself.

**Comment by straight-shoota** [comment]
It shouldn't matter if `Assertion` actually implements the method or just defines it as abstract.

**Comment by Blacksmoke16** [comment]
Right, so it should know that the method is going to be implemented.  Whereas now that doesn't seem to be the case.

**Comment by straight-shoota** [comment]
Actually, it shouldn't even matter at all if `Assertion` defines this method - whether it's abstract or implemented. 
That class itself is abstract and can't be instantiated. Hence `MyAssertion(T)` is the only subtype that can be instantiated and it implements `#valid?`.

**Comment by Blacksmoke16** [comment]
So this is the expected behavior, not a bug?

**Comment by straight-shoota** [comment]
No, it seems to be a bug.

**Comment by Blacksmoke16** [comment]
Reproduced another way:

```crystal
module Service; end

private abstract struct AbstractServiceDefinition; end

private record ServiceDefinition(ServiceKlass, ServiceArgs, AnnotationArgs) < AbstractServiceDefinition do
  def resolved?(services : Hash(String, Athena::DI::Service)) : Bool
    annotation_args.all? { |a| a.is_a?(String) && a.starts_with?('@') ? services.has_key? a.lchop('@') : true }
  end
end

struct ServiceContainer
  def initialize
    service_definitions = {} of String => AbstractServiceDefinition

    service_definitions.each do |name, service_definition|
      service_definition.resolved? ({} of String => Service)
    end
  end
end

ServiceContainer.new
```

```
Error in line 21: instantiating 'ServiceContainer.class#new()'

in line 15: instantiating 'Hash(String, AbstractServiceDefinition)#each()'

in line 15: instantiating 'Hash(String, AbstractServiceDefinition)#each()'

in line 16: undefined method 'resolved?' for AbstractServiceDefinition+

Rerun with --error-trace to show a complete error trace.
```

**Comment by Blacksmoke16** [comment]
Workaround for this seems to make the abstract class a module and just include that instead.

```crystal
module Assertion
  abstract def valid? : Bool
end

class MyAssertion(T)
  include Assertion
  
  def valid? : Bool
    false
  end
end

class Validator
  getter assertions : Array(Assertion) = [] of Assertion
  
  def validate
    @assertions.reject(&.valid?)
  end
end

pp Validator.new.validate # => []
```

**Comment by Blacksmoke16** [comment]
The workaround doesn't work if you want to also access the children in a macro :cry:.

**Comment by RX14** [comment]
You should just be able to put `DummyAssertion.new` anywhere in the program to fix it.
