### ISSUE TITLE
Rework annotations

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#7000]
Disclaimer: there are some issues offering removing or reworking existing features, e.g. macros. It's overall a good idea to discuss things, which may lead to a better language.

What I don't like about annotations is that in any moment I can't be sure where to place `@` symbol - before or after the brackets? So I have to look at examples. It really bothers me.

Combination of `@` and `[]` isn't aesthetic in my opinion and the language's beauty is a big matter for me.

My suggestion is to use `@` exclusively for annotations:

```crystal
@JSON::Field(ignore: true)
property foo

@Override
def foo
```

What do you think?

**Comment by Sija** [comment]
I'd say that's bikeshedding. Personally I don't see any problem or confusion with current syntax. With no delimiters they seem "naked" to me. Also, breaking BC just to loose two brackets ain't seem worth it.

**Comment by asterite** [comment]
That syntax conflicts with the existing syntax for instance variables.

**Comment by vladfaust** [comment]
@asterite for some reason I thought that instance variables aren't allowed to begin with capital letter. But seems like they are: https://carc.in/#/r/5ddw

Instance variables beginning with capital letter - is that okay? Is that expected for a developer?

**Comment by vladfaust** [comment]
I have a feeling of some contributors being somewhat biased. I call them to be more open and assess the language from different points. **Beauty** and **ease** in this case.

* **Beauty**: I love Crystal and Ruby because of a small amount of special symbols, which makes them more natural - more _human_. And those brackets with at symbol - they're very _nerdy_ in my point of view.

* **Ease**: as mentioned above, it's not easy to remember which is right: `@[Foo]` or `[@Foo]`. I'm not joking. And also minus two symbols to type :smiley:

**Comment by asterite** [comment]
In any case, the @ is taken by instance vars, the case (upper, lower) doesn't matter and if we go that way it'll be more confusing

**Comment by Sija** [comment]
@vladfaust Please, keep personal tones out of that discussion.

All your points are subjective, especially beauty and ease so let's stop treating those as sth objective please.

Changing syntax based on your opinion about "beauty" and "ease" to introduce changes which are confusing for others doesn't seem like a good attitude.

**Comment by vladfaust** [comment]
Surprisingly, that hurts me so much. The feeling is like when you find out your loved one cheats, seriously.

I've spent past two years on Crystal and I love it and it means a lot for me when it comes to beauty and ease. If not them, Crystal would be just another meh-language like Go or Rust, which are efficient but not beautiful at all. Crystal is *slick as Ruby* and Ruby states:

> A dynamic, open source programming language with a focus on simplicity and productivity. It has an elegant syntax that is natural to read and easy to write.

> A programmer's best friend

So if the community supports what @Sija says, then Crystal has no right to collate itself with Ruby.

Yes, it may see over-dramatic, but I really feel pain, physically. I cannot stay silent on that, sorry.

**Comment by vladfaust** [comment]
This issue is open to alternative annotation syntax ideas, if you have one, re-open it!

**Comment by Sija** [comment]
Yes, it does seem over-dramatic indeed ;) I'd be last person to reduce "slickness" of Crystal and its beautiful syntax, what I'm just saying is that your proposal brings more confusion than benefits of shaving two brackets in the name of "cleanliness" - which is not objective and personally, I prefer having those delimiters in place so I explicitly know where the body of this annotation begins and ends. In case where there's clarity vs "beauty" I choose clarity (go code these edge cases in syntax highlighting rules as an example).

**Comment by vladfaust** [comment]
Thanks for elaboration, @Sija, I appreciate that. Sometimes I overreact to internet messages because I misunderstand a commentator's attitude and emotions; their picture in my head differs from the reality. I'm sorry in front of the community for that.

**Comment by Sija** [comment]
I guess we all here strive for the most "clean" and "programmer friendly" syntax possible, it's just I believe we also need to account for other factors - like clarity - which play an important role in learning and getting accustomed to the language. More edge cases = more confusion = steeper learning curve.

**Comment by Blacksmoke16** [comment]
```crystal
# @JSON::Field(ignore: true)
# @Assert::NotBlank
# The user's current password
property password : String
```
Something like this would be similar to how PHP handles annotations.  Blends the annotations in the doc blocks.
