### ISSUE TITLE
Autocast NamedTuple argument to Object instance

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#7002]
Currently this code doesn't compile:

```crystal
struct Foo
  property x : Int32, y : Int32

  def initialize(@x, @y)
  end
end

def bar(foo : Foo)
  pp foo
end

bar(foo: {x: 1, y: 2})
```

It would be great if `foo: {x: 1, y: 2}` automatically casted to `foo: Foo.new(x: 1, y: 2)`.

## Use-case

Please see https://github.com/crystal-lang/crystal/issues/7001 for Stripe use-case. This issue is an alternative approach. So I could do this:

```crystal
class Stripe::Client
  record CreateCardToken::Card,
    exp_month : Int32,
    exp_year : Int32,
    number : String,
    currency : String? = nil,
    cvc : Int32? = nil,
    name : String? = nil,
    address_line1 : String? = nil,
    address_line2 : String? = nil,
    address_city : String? = nil,
    address_state : String? = nil,
    address_zip : String? = nil,
    address_country : String? = nil

  def create_card_token(
    card : CreateCardToken::Card? = nil,
    customer : String? = nil
  )
  end
end

client.create_card_token(card: {
  number:    "4242424242424242",
  exp_month: 12,
  exp_year:  2019,
  cvc:       123,
})
```

**Comment by vladfaust** [comment]
Another use-case: [Sendgrid API](https://github.com/vladfaust/sendgrid.cr).

Could reduce this code:

```crystal
mail = Sendgrid::Mail.new(
  personalizations: [Sendgrid::Mail::Personalization.new(
    to: [Sendgrid::Mail::Personalization::To.new(
      email: "user@example.com"
    )]
  )],
  from: Sendgrid::Mail::From.new(
    email: "noreply@example.com",
    name: "Test Robot"
  ),
  subject: "Test",
  content: [Sendgrid::Mail::Content.new(
    type: "text/plain",
    value: "Hello World!"
  )],
  mail_settings: Sendgrid::Mail::MailSettings.new(
    sandbox_mode: Sendgrid::Mail::MailSettings::SandboxMode.new(
      enable: true
    )
  )
)
```

To this:

```crystal
mail = Sendgrid::Mail.new(
  personalizations: [{
    to: [{
      email: "user@example.com"
    }]
  }],
  from: {
    email: "noreply@example.com",
    name: "Test Robot"
  },
  subject: "Test",
  content: [{
    type: "text/plain",
    value: "Hello World!"
  }],
  mail_settings: {
    sandbox_mode: {
      enable: true
    }
  }
)
```

I understand that this one is some naive fantasy and likely to never be implemented, but who knows...

**Comment by asterite** [comment]
Why do you need to pass all properties in the constructor? Just make them nilable and create properties for them. That's what most other languages do.

**Comment by vladfaust** [comment]
Nice question, @asterite. I have several arguments:

1. _"What most others do"_ is not necessarily the right thing. Have you heard of Five Monkeys Experiment?
2. It's a proposal for a feature which would generally improve a developer's quality of life by:
  a. Reducing the amount of code written (no long `Sendgrid::Mail::Personalization::To` things)
  b. Keeping initialization things in one place without a need to split into multiple assignments
  c. Avoiding the requirement to declare `properties`. What if you need getters only?
3. Speaking about my use-cases - wrapping an API - a user wants a result, say, to send an e-mail. They go to [Sendgrid API](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html#-Request-Body-Parameters) website and expect `Sendgrid.cr` API to be almost the same. And there are no cumbersome `Sendgrid::Mail::Personalization` objects in the API specification. However, if following your advice, even creating an itermediate `Mail` object (which will not be used anywhere else) may be frustrating. A user expects to do a single `client.send_mail` call, they don't care about _objects_.

Currently I see no downsides for this, and I _may_ be wrong.

**Comment by j8r** [comment]
@vladfaust what if the user want to send the same content for X people? Or sending X mail for the same people? The objects can't be reused/modified. We have to use a custom namedtuple for each new sending.

**Comment by RX14** [comment]
Hopefully this is also solved by the example code posted in #7001

**Comment by vladfaust** [comment]
@j8r nice point! I agree on that `Mail` object could be reused and that's good. However, `Mail`'s internals are not likely to be reused (as seen at https://github.com/crystal-lang/crystal/issues/7002#issuecomment-433986180), so that there this could be useful.

**Comment by vladfaust** [comment]
Why closing? It's a nice autocast feature to have, isn't it?
