### ISSUE TITLE
Runtime class seems to be Crystal::Expressions, but crashes because it's Crystal::Nop

### ISSUE THREAD

**Issue by zlotnleo** [crystal-lang/crystal#7013]
Here's the code:

```
require "compiler/crystal/syntax"

    s = "a = 5; puts a + 3"

    nodes = Crystal::Parser.parse(s)
    puts nodes.class # => Crystal::Expressions
    puts nodes.is_a? Crystal::Expressions # => true
    puts nodes.is_a? Crystal::Nop # => false

    puts nodes.expressions
```

The last line causes

```
undefined method 'expressions' for Crystal::Nop (compile-time type is Crystal::ASTNode+)
```

OS: MacOS 10.14
Compiler version: 0.26.1 (reproducible on all versions from 0.25.0 to 0.26.1 and on master)

**Comment by asterite** [comment]
> undefined method 'expressions' for Crystal::Nop (compile-time type is Crystal::ASTNode+)

The message could be improved. Right now it tells you the first type that doesn't have the method, but in reality many of them don't have it... but I guess the message would be too complex to understand.
