### ISSUE TITLE
u128 issue

### ISSUE THREAD

**Issue by pbrumm** [crystal-lang/crystal#7015]
having a script with just the following

     1329227995784915872904088535257055232_u128

will result in a crash

```
Invalid UInt64: 1329227995784915872904088535257055232 (ArgumentError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from __crystal_main
  from main
  from __libc_start_main
  from _start
  from ???
```

**Comment by z64** [comment]
I believe this is expected right now as UInt128 is not fully implemented

See https://github.com/crystal-lang/crystal/issues/5818#issuecomment-372504991, https://github.com/crystal-lang/crystal/issues/6144, PR: https://github.com/crystal-lang/crystal/pull/5564

**Comment by pbrumm** [comment]
yep. look like the same issue.
