### ISSUE TITLE
flush_on_newline is delayed by one line for SSL sockets

### ISSUE THREAD

**Issue by oprypin** [crystal-lang/crystal#7021]
When writing a line into an SSL socket (which has `flush_on_newline`), the socket is not actually flushed, and the flushing happens only when something more is written to it.

Preparation:
```console
$ openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365 -nodes -subj '/CN=localhost'
```
Code to reproduce the problem:
```crystal
require "socket"
require "openssl"

counter = 0  # Messages sent minus messages received
bad = false  # Whether counter ever was > 1

server_ctx = OpenSSL::SSL::Context::Server.new
server_ctx.private_key = "key.pem"
server_ctx.certificate_chain = "cert.pem"

server = TCPServer.new("localhost", 1234)

spawn do
  server.accept do |socket|
    ssl_socket = OpenSSL::SSL::Socket::Server.new(socket, server_ctx)

    while (line = ssl_socket.gets(chomp: false))
      puts "Received #{line.inspect}"
      if counter > 1
        bad = true
      end
      counter -= 1
    end
  end
end


client_ctx = OpenSSL::SSL::Context::Client.new
client_ctx.verify_mode = :none

socket = TCPSocket.new("localhost", 1234)
socket.flush_on_newline = true
ssl_socket = OpenSSL::SSL::Socket::Client.new(socket, client_ctx)
ssl_socket.flush_on_newline = true

3.times do
  ssl_socket << p "message\n"
  # ssl_socket.flush
  counter += 1
  sleep 0.1
end
ssl_socket.close


abort "Multiple pending messages" if bad
```

Expected output (also output when adding the explicit `flush`):
```
"message\n"
Received "message\n"
"message\n"
Received "message\n"
"message\n"
Received "message\n"
```
Actual output:
```
"message\n"
"message\n"
Received "message\n"
"message\n"
Received "message\n"
Received "message\n"
Multiple pending messages
```

This used to work in the past but is broken at least in 0.26.1 and 0.27.0. I cannot pinpoint the exact moment because when I try it on 0.25.1 now, it outright fails with an **unrelated** error: `SSL_accept: error:20078079:BIO routines:bio_read_intern:unsupported method (OpenSSL::SSL::Error)`.

**Comment by asterite** [comment]
Suggestion: remove flush on newline from the language, make STDOUT sync by default, and also sockets. Should fix the problem.

**Comment by asterite** [comment]
(reason: I introduced that feature for some reason I can't remember, I think it was because Stdout isn't or wasn't sync so it was a bit odd to puts and not see the output. The solution of making it sync by default is simpler, and still allows you to turn that behavior off if you want a bit more control and performance)

Of course in your case you'll want your ssl socket to be sync too, or just to flush as soon as you get data.

**Comment by oprypin** [comment]
FWIW, Python has quite a nice situation with line buffering

**Comment by oprypin** [comment]
FWIW, Python has quite a nice situation with line buffering
https://docs.python.org/3/library/functions.html#open

**Comment by RX14** [comment]
I'm fine with removing flush on newline, STDOUT being sync by default is fine with me. Sockets are already sync by default. The problem is that `SSL::Socket` is itself buffered and not sync by default. Buffering in crystal has a huge layering problem regarding wrapped IOs and we need to sort out the behaviour once and for all.

**Comment by obskyr** [comment]
So `flush_on_newline` is gone in 0.28.0, and that's all well and good, *but* STDOUT isn't sync by default. In Crystal 0.28.0:

```crystal
puts STDOUT.sync?
puts STDERR.sync?
```

Prints:

```
false
false
```

This makes exactly the problem @asterite was talking about appear – on 0.28.0, output isn't flushed until `#flush` is explicitly called or the program terminates. Let's fix that for the next version!

**Comment by obskyr** [comment]
Oh, actually, it's even weirder. `#sync?` returns `false` initially, but it *is* synced. I guess `#sync?` is just broken. Here, have some examples:

```crystal
puts STDOUT.sync?
Process.run "sleep", ["5"]
# ==> Flushes "false"(!?) immediately, and then sleeps for 5 seconds.
```

```
STDOUT.sync = false
puts STDOUT.sync?
Process.run "sleep", ["5"]
# ==> Sleeps for 5 seconds, then flushes "false".
```

**Comment by rdp** [comment]
I get this now:
`Error: undefined method 'flush_on_newline=' for TCPSocket`
is there still a problem?  New snippet possible if so?

**Comment by rdp** [comment]
Recommend close, outdated.  Cheers!
