### ISSUE TITLE
Memory consumption compared to D and Go

### ISSUE THREAD

**Issue by ggl** [crystal-lang/crystal#7025]
Hello

I wanted to try out crystal with the 0.27 release and I implemented my prime number benchmark in it. I also have it in D and Go to be able to compare with something. It's a somewhat rough implementation and if you run it up to 100k I'm sure it has integer overflow. I couldn't quite figure out how to use UInt64 ranges. Surprisingly, it runs faster than both D and Go up to 10k if compiled with the --release tag, otherwise it's a bit slower than D. The problem is that once I try to run it up to 100k it will fill up all my computer's memory (8GB) and start swapping. The D and Go implementations run fine and find all the primes in 15 and 4 seconds, respectively. I am using crystal 0.27 on Ubuntu 16.04 LTS on the amd64 architecture. Here is the code:

    # sundaram.cr
     
    sieve_sundaram(n : Int32)
      a = Hash(Int32, Bool).new
      s = Array(Int32).new
      m = (n/2.0).round
      (1..n).each do |i|
        (i..n).each do |j| 
          p = i + j + 2*i*j 
          if p <= n
            a[p] = true; 
          end   
        end 
      end
      (1..m).each do |k|
        if !a.has_key?(k)
          q = 2*k + 1
          s.push(q)
        end 
      end
     
      return s 
    end
     
    sieve_sundaram(1000)

The other implementations are part of this public gist:

https://gist.github.com/ggl/18e3a6d2ac7cf22120891b7460553775

All of these use a Hash or map or associative array type to store non-primes because not all the languages tested have a Set type. Also they don't use anything wich is not in the standard library.

**Comment by asterite** [comment]
I don't have a computer right now to try it out, but Hash in Crystal preserves insertion order and that requires some more memory compared to D and Go. The algorithm may be the same but I'm pretty sure the underlying data structures for Hash and Array are different in all of these languages. That's where the difference comes from. But I'll benchmark it later to see what's going on.

**Comment by RX14** [comment]
There's an overflow going on in the `2*i*j` when `n` is above approximately `Math.sqrt(Int32::MAX / 2)`

**Comment by asterite** [comment]
Ah, yes. I was going to say "But in Go it works" but `int` is used and it's probably 64 bits in this case.

**Comment by RX14** [comment]
(we should probably copy `Int` and `UInt` from go, as long as they're seperate types like go which always need explicit conversion)
