### ISSUE TITLE
Proposal of addition of TestUnit syntax

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#7042]
I want to propose adding a TestUnit style syntax to the stdlib.

I have looked for a proposal for adding TestUnit syntax and I didn't see one open.
I like using the minitest.cr shard but having support for this syntax in the stdlib would be preferable for support and a standard API for expansion.

I don't think the specs for repo should change I only propose adding an implementation of TestUnit.

**Comment by RX14** [comment]
Given crystal's position on method aliases and having one (and preferably only one) way to do things, I doubt this proposal will go ahead.

**Comment by wontruefree** [comment]
looks like this is not going to happen so I am going to close this.
