### ISSUE TITLE
Is this a silly spawn bug?

### ISSUE THREAD

**Issue by howesteve** [crystal-lang/crystal#7045]
Hello,

Just starting with the language. Can anyone please tell me why this runs ok:

```crystal
i = 0
spawn do
  loop do
    i += 1
    puts "#{i}!"
  end
end
sleep 1.second
puts "\nDone."
```

Output: 
```
343585!
343586!
343587!
343588!

Done.
```
... while this won't stop (infinite loop)?

```crystal
i = 0
spawn do
  loop do
    i += 1
    #puts "#{i}!"
  end
end
sleep 1.second
puts "\nDone."```

? It doesn't seem to make any sense for me...

Thanks,
Howe

**Comment by straight-shoota** [comment]
In the second example, the code in the second fiber runs in a tight loop. The main fiber will never be reached and thus can't reach the "Done" line and exit the program.
`puts "#{i}!"` allows switching fibers when the main fiber is supposed to be resumed.

**Comment by howesteve** [comment]
Hey @straight-shoota,

Is that by design? That's the the first language I ever saw with such a behavior. I found that very confusing.

Thanks.
Howe

**Comment by asterite** [comment]
Go works like that, or so it seems: https://github.com/golang/go/issues/10958

(though I thought at this point it was fully preemptive)

**Comment by RX14** [comment]
In the future we'll probably have to think about how to add more preemption points  to programs but for now this is expected behaviour.
