### ISSUE TITLE
Initializing a namedtuple from double splat

### ISSUE THREAD

**Issue by dscottboggs** [crystal-lang/crystal#7049]
If you try to declare a class/struct with a NamedTuple property and a double-splat intitializer, you get this compiler error:

```crystal
struct Demo(T)
  @data : NamedTuple(T)
  def initialize(**@data)
  end
end

# Error in line 2: can only instantiate NamedTuple with named arguments
```

the same error happens if I try doing the initialize like

```crystal
def intitialize(**data)
  @data = data
end
```
etc.

**Comment by stepanvanzuriak** [comment]
You should denote a named tuple. Like this: 

```crystal
struct Demo(T)
  @data : NamedTuple(x: Int32)
  def initialize(**@data)
  end
end
```

**Comment by RX14** [comment]
@straight-shoota is correct, you need to make `T` the named tuple type itself.
