### ISSUE TITLE
Hash(...)#from_json; NULL results in empty-hash.

### ISSUE THREAD

**Issue by angryrabbit** [crystal-lang/crystal#7052]
Environment:

```
$ crystal -v
Crystal 0.27.0 (2018-11-04)

LLVM: 6.0.1
Default target: x86_64-apple-macosx
```

Bug:

```crystal
require "json"

hash = Hash(String, String | Nil).from_json %({"a":null})

puts hash # => {}
```

Bug-in-action:

https://play.crystal-lang.org/#/r/5gw4

**Comment by MakeNowJust** [comment]
@asterite Four years ago you implemented skipping `null` in Hash values (5312eed). However I think it is too implicit behavior and makes users confused (like this issue). Could you remember the reason?

**Comment by straight-shoota** [comment]
I'm the spec example, the value type is `Nil`, so you can't add `nil` to the hash. I'd suppose it's okay for this use case to remove JSON nulls when the hash value is non-nilable.
But it should add `nil` if the value type includes `Nil`.

**Comment by asterite** [comment]
@MakeNowJust good finding! You can revert to this that commit. If V is a union it will now work fine. My change was before we could do union from json.

**Comment by MakeNowJust** [comment]
> My change was before we could do union from json.

It is clear. Thank you!
