### ISSUE TITLE
Socket specs failing on musl

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#7057]
See https://github.com/alpinelinux/aports/pull/5560#issuecomment-437120481

The first errors are just that musl seems to have different error messages than glibc. We already account for differences between linux and bsd/darwin, so it's just adding another set of messages.

The last failure comes from OpenSSL error handling (with OpenSSL 1.1) where initializing an `OpenSSL::SSL::Error` actually raises `Errno`. This seems wrong, at this point it should always raise an SSL error, even if the cause is an IO error (which can be wrapped).

**Comment by RX14** [comment]
The latter error is https://github.com/crystal-lang/crystal/issues/6979.

The former errors are a simple PR.

**Comment by straight-shoota** [comment]
It's actually not exactly #6979. The error is `Errno: SSL_connect: No error information`, not `Errno: SSL_connect: Success`.

**Comment by RX14** [comment]
@straight-shoota since it's an Errno not an openssl error type, that's also just a glibc/alpine difference.
