### ISSUE TITLE
inconsistency date value

### ISSUE THREAD

**Issue by codenoid** [crystal-lang/crystal#7058]
```
icr(0.27.0) > (Time.now.to_local - 10.minutes.ago).abs
 => 00:09:59.999998000
icr(0.27.0) > (Time.now.to_local - 10.minutes.ago).abs
 => 00:10:00
icr(0.27.0) > (Time.now.to_local - 10.minutes.ago).abs
 => 00:09:59.999999000
icr(0.27.0) > (Time.now.to_local - 10.minutes.ago).abs
 => 00:09:59.999999000
icr(0.27.0) > (Time.now.to_local - 10.minutes.ago).abs
 => 00:09:59.999999000
icr(0.27.0) > (Time.now.to_local - 10.minutes.ago).abs
 => 00:09:59.999999000
icr(0.27.0) > (Time.now.to_local - 10.minutes.ago).abs
 => 00:09:59.999999000
icr(0.27.0) > (Time.now.to_local - 10.minutes.ago).abs
 => 00:09:59.999999000
icr(0.27.0) > (Time.now.to_local - 10.minutes.ago).abs
 => 00:10:00
icr(0.27.0) > (Time.now.to_local - 10.minutes.ago).abs
 => 00:10:00
```

**Comment by MakeNowJust** [comment]
The following code is the same as your examples:

```
left = Time.now.to_local
right = Time.now - 10.minutes # It is expansion of `Time::Span#ago`.
left - right
```

If the second line `Time.now` returns the same value of the first line `Time.now` **every time**, then it shows consistent results as you said. But, `Time.now` result is current real time, so it changes when a time greater than your CPU clock is spent between `left` and `right` assignments. It is the reason of this inconsistency.

If you want consistent result really, you can use [faketime command](http://manpages.ubuntu.com/manpages/trusty/man1/faketime.1.html) with freeze time format.

**Comment by straight-shoota** [comment]
`Time.now.to_local - 10.minutes.ago` doesn't make any sense in itself. It's semantically equivalent to `10.minutes.abs`.
