### ISSUE TITLE
toplevel.html not being created with only macro

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#7061]
The `toplevel.html` file is not being created when running `crystal docs` when the top level namespace only includes a macro.

# Steps to reproduce
1. Create a new library using `crystal init lib test`
2. Add a macro to toplevel namespace
```crystal
# test.cr
macro test(name)
  {{name.stringify}}
end

# TODO: Write documentation for `Test`
module Test
  VERSION = "0.1.0"

  # TODO: Put your code here
end
```
3. Run `crystal docs` and notice there is no `Top Level Namespace` on the navbar on `index.html`
4. Search for `test`, and notice it appears in the list, but clicking on it 404s
5. Add a method to top loplevel namespace and rerun `crystal docs`
6. Notice it now exists with both macro and method definitions. 

EDIT: Doesn't generate when including a macro and constant either.  Must require a method.

**Comment by r00ster91** [comment]
I noticed this as well: #6637.

**Comment by Blacksmoke16** [comment]
Oop didnt' see that one, ill close this in favor of #6637
