### ISSUE TITLE
`#[](...)` is not rendered correctly in docs

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#7065]
When this:
```
`#[](...)`
```
(or without anything in the parentheses)
is in the documentation of for example a method then in the docs it's not rendered correctly and results in `#`.

Example: [`Indexable#unsafe_fetch`](https://crystal-lang.org/api/0.27.0/Indexable.html#unsafe_fetch%28index%3AInt%29-instance-method):
> Clients never invoke this method directly. Instead, they access elements with `#` and [`#[]?(index)`](https://crystal-lang.org/api/0.27.0/Indexable.html#%5B%5D%3F%28index%3AInt%29-instance-method).

Source:
```cr
  # Clients never invoke this method directly. Instead, they access
  # elements with `#[](index)` and `#[]?(index)`.
```

**Comment by Sija** [comment]
Seems related to #4613, i.e. buggy markdown renderer.
