### ISSUE TITLE
Updating Crystal on OpenSUSE using Zypper

### ISSUE THREAD

**Issue by kinxer** [crystal-lang/crystal#7069]
After adding the Crystal repo to Zypper on OpenSUSE Tumbleweed (using the instructions reproduced below from [here](https://github.com/crystal-lang/crystal-book/blob/597dd3a9b39d305ef8cc8bb0218df3f3e76144fd/installation/on_opensuse.html)), retrieving repository metadata gives the following error:
```
Permission to access 'https://dist.crystal-lang.org/rpm/media.1/media' denied.
```

This error prevents me from using Zypper to update my Crystal version, which is obviously desirable.

I was previously able to set up Crystal repository access using Zypper by doing almost exactly the instructions below and received no errors then (as I recall, I didn't have quite the same flags on the archive configuration command), but for the past few weeks I've received the above error; during this time, I tried re-adding the repository using exactly the linked instructions, but it didn't improve my situation at all. I seem to recall as well that navigating to the [Crystal dist site](dist.crystal-lang.org) in-browser would previously allow access, but it now gives me a similar "access denied" error.

Just in case the link above dies for some reason, here are the instructions:

> # On OpenSUSE
>
>In OpenSUSE, you can use the official Crystal repository.
>
>## Setup repository
>
>First you have to add the signing key:
>
>```
>rpm --import https://dist.crystal-lang.org/rpm/RPM-GPG-KEY
>```
>
>Next you have to configure the repository in Zypper. You can do this with the following command:
>

> ```
> sudo zypper ar -e -f -t rpm-md https://dist.crystal-lang.org/rpm/ Crystal```
> ```

>
> 
> ## Install
> Once the repository is configured you're ready to install Crystal:
> 
> ```
> sudo zypper install crystal
> ```
> 
> ## Upgrade
> 
> When a new Crystal version is released you can upgrade your system using:
> 
> ```
> sudo zypper update crystal
> ```

**Comment by bcardiff** [comment]
@kinxer there is no `rpm/media.1/media` and never has been.
zypper is able to install but not to update the package (tested on opensuse/openSUSE-42.3-x86_64 vagrant box)

Although there is a description of [must exist files](https://en.opensuse.org/openSUSE:Standards_YaST2_Repository_Metadata_media) for yast. I've found that others complain that is a zypper issue:
* https://superuser.com/questions/1336101/cannot-update-opensuse-repos
* https://sourceforge.net/p/xcat/bugs/911/

I kind of agree it's a zypper limitation given that a fresh installation is able to be done.

Workaround:

* remove crystal
* remove crystal repo
* add crystal repo
* install crystal

```
$ sudo zypper remove crystal
$ zypper lr -d
Repository priorities are without effect. All enabled repositories share the same priority.

# | Alias                 | Name      
--+-----------------------+---------- ...
1 | Crystal               | Crystal 
...
$ sudo zypper rr 1
$ sudo zypper ar -e -f -t rpm-md https://dist.crystal-lang.org/rpm/ Crystal
$ sudo zypper install crystal
```

**Comment by kinxer** [comment]
In case someone else has this issue and stumbles across this issue:

In trying to figure out how to bypass this myself (or what bug to submit for Zypper), I found [this discussion](https://github.com/keybase/keybase-issues/issues/3118), which leads me to believe that there's some weirdness happening with Zypper and interpreting 403 responses. I also found [here](https://forums.insynchq.com/t/repository-for-opensuse/954/55) that it's possible to bypass this issue with `zypper refresh --force`, which is nice.

Another interesting obstacle with using Zypper to update Crystal is that since 0.24.1 every Crystal release has had a different vendor. Zypper responds to this by not automatically updating Crystal to the newest version because the vendors differ. [This page](https://en.opensuse.org/SDB:Vendor_change_update) provides the options that you have to overcome that behavior.

**Comment by bcardiff** [comment]
> since 0.24.1 every Crystal release has had a different vendor

Since that version we are building the packages using fpm. Maybe some option is missing to fix that. cc: @RX14 any clue?

**Comment by RX14** [comment]
I don't know anything about zypper or RPM or that side of linux distros, sorry.

**Comment by j8r** [comment]
In https://github.com/jordansissel/fpm/wiki , when searching `vendor`: ` --vendor VENDOR               (optional) vendor name for this package`

In https://github.com/crystal-lang/distribution-scripts/blob/master/linux/Makefile:
- add a `--vendor "Unknown <unknown@unknown.unknown>"` or a true one
- use a shared FPM_FLAGS variable to reuse it for each fpm command invocation
- a `--license LICENSE             (optional) license name for this package` can also be added.

I can send a PR to https://github.com/crystal-lang/distribution-scripts this week-end, and test if this vendor flag solve the issue.

**Comment by kinxer** [comment]
I've confirmed with this most recent update (0.28.0) that with the addition of vendor and license distribution flags and the use of `zypper refresh --force`, zypper will automatically retrieve the latest version of Crystal.
