### ISSUE TITLE
Properly handle ambiguous annotation names

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#7070]
## https://carc.in/#/r/5i4e

```crystal
module Foo
  annotation Field
  end

  def initialize(foo : String)
    {% puts "Foo" %}
    {% for ivar in @type.instance_vars %}
      {% pp! ivar.annotation(Foo::Field) %}
    {% end %}
  end
end

module Bar
  annotation Field
  end

  def initialize(bar : Int32)
    {% puts "Bar" %}
    {% for ivar in @type.instance_vars %}
      {% pp! ivar.annotation(Bar::Field) %}
    {% end %}
  end
end

class X
  include Foo
  include Bar

  @[Field]
  property y : Int32?
end

X.new("foo")
X.new(42)
```

```
"Foo"
ivar.annotation(Foo::Field) # => nil
"Bar"
ivar.annotation(Bar::Field) # => @[Field]
```

It's a bug for me, should either raise on ambiguity or restrict "short" annotation names, requiring full paths.

**Comment by vladfaust** [comment]
Thank you, captain Ary 😀 Still, such a situation can appear if multiple modules are included in different places and have the same annotation level. Could you imagine the level of confusion for a developer? I mean, we have a static language here, not A Ruby...

**Comment by straight-shoota** [comment]
If you properly namespace the annotations, everything's fine. I don't think this should be any different from general path resolution.

**Comment by RX14** [comment]
Not a bug, it's existing behaviour: https://carc.in/#/r/5kgk
