### ISSUE TITLE
Move `HTTP::Multipart` and `HTTP::Formdata` to `MIME` namespace

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#7078]
The multipart message format is part of the MIME standard and used by a variaty of applications, not just HTTP. I suggest to rename the `HTTP::Multipart` type to `MIME::Multipart` (the `MIME` namespace has been added in #5765).

Similarly, `HTTP::Formdata` as an implementation of `multipart/formdata` should also be renamed to `MIME::Formdata`.

**Comment by RX14** [comment]
formdata is an HTTP spec, multipart is a MIME (originally used in email) spec.

**Comment by straight-shoota** [comment]
More recent RFCs for multipart/formdata are https://tools.ietf.org/html/rfc2388 and https://tools.ietf.org/html/rfc7578 and they specifically state that it "can be used by a wide variety of applications and transported by a wide variety of protocols". It's not specific to HTTP (although it started with HTTP/HTML and that's the most prominent use case).

**Comment by RX14** [comment]
It should stay in http.

**Comment by straight-shoota** [comment]
So `MIME::Multipart` and `HTTP::Formdata`?

**Comment by RX14** [comment]
Yep.

**Comment by Indribell** [comment]
This can be closed. See #7085
