### ISSUE TITLE
specs not working with u128

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#7088]
Am I doing something wrong?

https://play.crystal-lang.org/#/r/5iwx
```crystal
221360928888809586640_u128 == 221360928888809586640_u128
```
This seems to throw and error

https://play.crystal-lang.org/#/r/5iwr
```crystal
require "spec"
221360928888809586640_u128.should eq 221360928888809586640_u128
```
This seems to also throw an erro

**Comment by Sija** [comment]
See #5564

**Comment by RX14** [comment]
Duplicate of #5564

**Comment by wontruefree** [comment]
@RX14 I am reopening this to finish it.  It seems like @omotorin has stopped working on it
