### ISSUE TITLE
Would Ravenbrrok MPS system work with Crystal?

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#7092]
I came across a talk with someone using boehm GC and added MPs to get compression and incremental collection.  Would a memory management system like MPS work with crystal and crystals C API?

Here is a link to the project. https://www.ravenbrook.com/project/mps/master/manual/html/guide/overview.html

**Comment by proyb6** [comment]
I curious, which talk was that if you have a link?

**Comment by wontruefree** [comment]
https://youtu.be/8X69_42Mj-g

**Comment by wontruefree** [comment]
I think this project would be cool to implement but I imagine more GC work will be done post 1.0
