### ISSUE TITLE
App template not work, when I run crystal init app spa-boilerplate/

### ISSUE THREAD

**Issue by jefer94** [crystal-lang/crystal#7100]
Hi, this is the problem

```bash
crystal init app spa-boilerplate/
cd spa-boilerplate
sentry
```

> Syntax error in src/spa-boilerplate/.cr:2: unexpected token: /
>
> module Spa::Boilerplate/

# Soluction

Do a regular expresion that, remove the last / character

**Comment by j8r** [comment]
That's expected on a UNIX filesystem, the `/` is reserved - you have to escape it.
Same with `touch spa-boilerplate/`: `touch: setting times of 'touch spa-boilerplate/': No such file or directory`

Having a slash in an application name isn't recommended.

**Comment by j8r** [comment]
The error isn't related to the filesystem, but there is a `.cr` file created here.
The error can be improved: checking if the name is valid, or else raising an error.

**Comment by bcardiff** [comment]
The trailing `/` was probably added by a terminal autocomplete due to an existing directory. I think that removing the last `/` make sense to support this use case.

**Comment by bew** [comment]
Looks like #5980 (issue: #4817)

**Comment by bcardiff** [comment]
Duplicate #4817.

Thanks @bew

**Comment by jefer94** [comment]
The problem is that

* The Crystal CLI is not validating the entry
* Then the CLI of Crystal, generated an erroneous code, because it is not well implemented
* In conclusion it is not compiled

If the entry is bad, it should throw an error
