### ISSUE TITLE
Installing an older version

### ISSUE THREAD

**Issue by PlinioRasch** [crystal-lang/crystal#7102]
Hi, may I please know how I can install 0.24.1 on Centos 7? I don't wanna install the latest version but that version, please.

**Comment by proyb6** [comment]
Could you download the older release in source code and compile?

**Comment by PlinioRasch** [comment]
I can't seem to find a download in here https://github.com/crystal-lang/crystal/pull/5358/commits/c875fb6ad502bf777799821663ef0e4706ba66d2
or may I'm just stupid

**Comment by PlinioRasch** [comment]
Wow nevermind, I found it... I'm sorry for the trouble
