### ISSUE TITLE
Allow underscores when initlalising BigInt

### ISSUE THREAD

**Issue by alex-kampa** [crystal-lang/crystal#7106]
In order to be consistent with how integers are handled, it will be good to allow BigInt initialisations with underscore like this:

BigInt.new("FFFFFFFF_FFFFFFFF_FFFFFFFF_FFFFFFFF_FFFFFFFE_FFFFEE37", base: 16),

**Comment by Exilor** [comment]
Perhaps it would be more consistent to change `String#to_big_i` so that it has the same interface as `String#to_i`, including the arguments `underscore`, `strict`, etc.

**Comment by bcardiff** [comment]
Having at least the `_` handled would be good for consistency with respect how numbers literals are supported.

Ignoring whitespaces is already allowed by default in LibGMP and can't be turned off, so having exactly the same behavior would require manual validation. That could makes sense in `String#to_big_i`, but I would say to make `BigInt.new` consistent with the built in numbers parsing rules (ie: handle `_`)
