### ISSUE TITLE
Is it possible to create a Windows DLL from Crystal code and export functions?

### ISSUE THREAD

**Issue by malte-v** [crystal-lang/crystal#7115]
It is already possible to create a Linux shared library from Crystal code and export functions using the `fun` instead of the `def` keyword. I had success with [this](https://gist.github.com/malte-v/3623a21e1977f562baf6dcf44df2ef08) code, at least on Linux.
It is also possible to cross-compile Crystal code on a Linux/macOS machine and run it as a windows executable. So can we theoretically create a windows DLL from crystal code and export functions? My approach was the following:

1. Cross-compile library for Windows (`crystal build logger.cr --single-module --cross-compile --target x86_64-pc-windows-msvc`)
2. Write a simple export definition file (see [logger.def](https://gist.github.com/malte-v/3623a21e1977f562baf6dcf44df2ef08))
3. Create an import library using `lib /def:logger.def /machine:x64`
4. Create DLL using `cl logger.o /Felogger /LD /implib:logger.lib pcre.lib gc.lib advapi32.lib libcmt.lib`
5. Compile main program using `cl main.c /link logger.lib`

When executing main.exe, I get error 0xc000007b. Google says that this happens if an executable and its dependencies have different machine types. I've checked main.exe and logger.dll through Dependency Walker and they both are x64. What's interesting is that Dependency Walker marks `crystal_init` and `crystal_log` as unresolved external functions in the executable.

Am I doing something wrong here or can't I export functions using `fun` on Windows? In the latter case, I can understand that this isn't your priority at least for now.

**Comment by ysbaddaden** [comment]
No. Search for shared libraries in another issue. It's for POSIX systems, but the same applies to windows and other platforms. It can be hacked in, but really not a goal of the language.

**Comment by RX14** [comment]
What you're trying to do isn't supported (`fun` isn't meant for creating shared libraries in crystal) so I'm not going to get around to looking into this.

See #921 for why we won't support this. It's not quite a dupe because this is a specific issue but i'll close it anyway.

**Comment by maltevoos** [comment]
I found a solution: https://github.com/maltevoos/crystal-dll-demo
It's a bit complicated but does **not** require hacking the compiler.
