### ISSUE TITLE
Readline.bind_key doesn't work

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang/crystal#7117]
By example:

```crystal
require "readline"

Readline.bind_key('a') do
  puts "Hi!"
end

sleep
```

Shows:

```
Error in keysignal.cr:3: expected block to return Int32, not Nil

Readline.bind_key('a') do
```

So, I tried this:

```cr
require "readline"

Readline.bind_key('a') do
  puts "Hi!"
  0
end

sleep
```

and it compiles, but it doesn't detect `a` keyword

Ref: https://github.com/crystal-lang/crystal/pull/1290#issuecomment-135134592

Version:

```
[main@pc ~]$ crystal -v
Crystal 0.27.0 (2018-11-02)

LLVM: 6.0.1
Default target: x86_64-pc-linux-gnu
```

**Comment by RX14** [comment]
`Readline` is going to go. I just need to get around to pulling it out.

**Comment by RX14** [comment]
Not relevant any more, see https://github.com/crystal-lang/crystal/pull/8364
