### ISSUE TITLE
T.instance_vars returns empty array even in methods

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#7119]
I'm experimenting with annotations in an ORM.

```crystal
struct Query(T)
  def where(**values : **U) : self forall U
    {% pp! T.instance_vars %} # => []
    self
  end
end

class User
  property id
end

Query(User).new.where(id: 42)
```

**Of course**, this prints empty array. **But:**

```crystal
{% pp! T.methods %}
```

```
[def id
  @id
end, def id=(id)
  @id = id
end]
```

So there is an example of inconsistent behavior. Shouldn't `.instance_vars` actually return instance variables at this point?

/cc @asterite

**Comment by asterite** [comment]
No, `@id` doesn't have a type. Try `property id = 0` for example, then it works.

**Comment by vladfaust** [comment]
My bad. Happy that it works though!
