### ISSUE TITLE
Formatter: Missing end indentation on macros

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang/crystal#7129]
This code:

```cr
  macro greeting
    puts "Hi!"
    # something else...
  end
```

is formatted to: 
```cr
macro greeting
    puts "Hi!"
    # something else...
  end
```

Duplicate?: https://github.com/crystal-lang/crystal/issues/2030

This issue is related to this comment: https://github.com/crystal-lang/crystal/issues/2030#issuecomment-172914882

Also https://github.com/crystal-lang/crystal/issues/2030#issuecomment-172917533 explains that macros can't be formatted and I'm ok with that, but would be possible to remember previous `macro` keyword indentation and use same indentation on the `end` keywork finishing a macro code block?

At least to get something like this:

```cr
macro greeting
    puts "Hi!"
    # something else...
end
```

(notice aligned `end` keyword and macro body without changes)

WDYT?

**Comment by asterite** [comment]
This is not a bug. The `macro` keyword should be aligned to the left by the normal rules of the formatter, and then the formatter preserves spaces in macros, and there are two spaces before `end`.
