### ISSUE TITLE
Crystal chat on Spectrum 

### ISSUE THREAD

**Issue by jamesfuture** [crystal-lang/crystal#7132]
Recently, I have registered "Crystal" with the intention for Crystal community to consider if it's worth migrating to new communication platform? Let me know your thoughts.

https://spectrum.chat/crystal

Spectrum’s Repo
https://github.com/withspectrum

Open Source
https://github.com/withspectrum/spectrum

Roadmap
https://github.com/withspectrum/spectrum/projects/19

**Comment by RX14** [comment]
Are there any issues with gitter as-is?

There are large amount of costs associated with moving itself, and spectrum would have to be *very* good to be worth migrating.

This discussion is probably better for the mailing list though. (or the official forums, coming soon™)
