### ISSUE TITLE
Revert: Change Crystal color on GH to black

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#7141]
See https://github.com/github/linguist/pull/4290 for details.

@vladfaust opened above mentioned PR and got it merged with neither consultation, nor discussion in the proper community channels ("chatting" on Gitter channel ain't count for me).

Thus, in the vein of open decision making process, I'd like to vote whether new color (black) should stay or to be reverted (to purple).

Please, vote with:
👍 to go back to original purple
👎 to stay with black

**Comment by j8r** [comment]
I create a new vote:
:confused: - don't mind the color

**Comment by Sija** [comment]
@j8r If you don't mind the color, just ignore this issue, there's nothing actionable for people with no preference either way...

**Comment by j8r** [comment]
@Sija consider it as a [Protest vote](https://en.wikipedia.org/wiki/Protest_vote) :smiley:

**Comment by bew** [comment]
Good idea for the issue, let's wait a few days now, see how it goes

**Comment by bcardiff** [comment]
FYI https://github.com/github/linguist/pull/4290#issuecomment-443752421

> @bcardiff said:
>
> Dear linguist community, please accept our apologies for the noise in this thread. At crystal we are really happy to be listed and have a color assigned. The current black color is fine. It's even aligned with the current branding scheme. We do believe that at the end of the day linguist gets to pick each color it however it dims appropriate, and if anything we're grateful for the recognition.
> 
> Further discussions about this belong in Crystal community spaces, so please feel free to lock this conversation.

**Comment by bararchy** [comment]
As @bcardiff already communicated out that black is fine, I think that we can close this issue, I don't see much relevancy for it anymore, TBH the black color is good, crystal is black and white branding wise, it was a good idea but done a bit rush, anyway, I think we are wasting to much "power" over this and should move on to working on actual language :)

**Comment by Sija** [comment]
> As @bcardiff already communicated out that black is fine, I think that we can close this issue [...]

I don't think that a word of one person is enough to merit closing this issue.

> I don't see much relevancy for it anymore

You're entitled to your opinion.

> TBH the black color is good

That's an opinion, I don't agree and so other ppl, as you can tell by the voters ratio.

> I think we are wasting to much "power" over this and should move on to working on actual language :)

Perhaps, if you believe so, why do you waste it yourself arguing for sth that doesn't matter (for you)? I don't see how this issue might stop you from contributing to the language.

**Comment by j8r** [comment]
You don't understand @bararchy , the color is **crucial** : the whole future of the language depends on this little colored circles/bars representing Crystal on GitHub.
As @Sija said, it'll stop me to contribute if the color isn't Barf Green :smile:

**Comment by TeddyDD** [comment]
Honestly I thought B&W branding is „final” and I'm kinda disappointed to hear it supposed to be changed in the future. I'm probably biased (as you can see from my avatar :laughing:) but I believe current branding looks classy af :)

**Comment by Sija** [comment]
@j8r You seem to have missed "psychology of color" (especially in marketing/branding), I suggest to read it before you'll paint your walls to black/red ;)

**Comment by bararchy** [comment]
lol sorry @Sija I wasn't aware that this was such a deep and emotional issue.
Please accept my apologies and I'll let you all great graphic designers choose the best for Crystal's github little line lang indicator.

**Comment by Sija** [comment]
Two weeks passed, which I'd say it's enough for a poll.
As for the results: **black** wins. Thank you all for participation!
