### ISSUE TITLE
More Iterator methods: slice_before, slice_after, slice_when, chunk_while

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#7142]
While coding this year's [Advent of Code](https://adventofcode.com/2018) it would have been nice to have these `Iterator` methods. They exist in Ruby but are missing in Crystal. They are sometimes useful in this type of problems, where using Crystal is more fun :-P

Is there interest in these? I can submit a PR with a commit for each of these.

I guess the names can remain the same as in Ruby.

**Comment by mamantoha** [comment]
While coding the fifth day of Advent of Code it would have been nice to have `String#swapcase` and `Char.swapcase` methods. Yeah 🙂

**Comment by asterite** [comment]
@mamantoha Hehe, indeed. At this point, given that `swpacase`'s implementation is trivial, I'd say we could add it just fine.

**Comment by yxhuvud** [comment]
`to_h(&:block)` from Ruby 2.6 could be nice to have too, if we are window shopping ruby methods :)

**Comment by straight-shoota** [comment]
Please keep in mind though that a time travelling Santa solving elves puzzles is not entirely representing *real world* use cases.

Just to put some restraints on the shopping spree ;)

**Comment by asterite** [comment]
This is all done now :-)

(open a separate issue if you'd like `swapcase`, I'm still not sure it's that useful)
