### ISSUE TITLE
Annotation[] should accept StringLiteral

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#7149]
We have `def [](index : NumberLiteral)` and `def [](name : SymbolLiteral)`, but a `StringLiteral` should be allowed as well as we're going to get rid of symbols in the future (I'm already using strings as NamedTuple keys everywhere).

**Comment by MakeNowJust** [comment]
If follows `NamedTupleLiteral#[]` behavior, `Annotation#[]` should accept every `ASTNode` and should handle `StringLiteral` and `MacroId`. IMHO it is more consistent than extending `Annotation#[]` to accept `StringLiteral` simply.

**Comment by vladfaust** [comment]
Don't know about NamedTupleLiteral, but accepting `ASTNode` doesn't make sense for me. It's cleary should be a compilation error.

**Comment by MakeNowJust** [comment]
I don't know why `NamedTupleLiteral#[]` accepts `ASTNode`. And it doesn't make a sense really. One reason I guess is backward compatibility for `HashLiteral`.

@asterite Could you remember about this?

**Comment by vladfaust** [comment]
Are there any plans on removing annotations? I'm starting to love them, they bring many opportunities and I'm already rewriting an ORM and https://github.com/vladfaust/params.cr to annotations

**Comment by asterite** [comment]
@vladfaust No plans yet. Just that because they weren't thoroughly planned, I personally (and I say this from my point of view) wouldn't touch them until a good design is cooked.

**Comment by vladfaust** [comment]
@asterite but the whole idea of storing data on objects in compilation time would remain the same, right?

**Comment by asterite** [comment]
@vladfaust I don't know. I'm currently not thinking about the design of Crystal, I just know that we shouldn't continue changing stuff without thinking them well.
