### ISSUE TITLE
Filename too long (Errno)

### ISSUE THREAD

**Issue by threeid** [crystal-lang/crystal#7151]
```
Crystal 0.27.0 [c9d1eef8f] (2018-11-01)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
OS: Ubuntu 18.04.1
Editor: VSCode
Extensions: Crystal Language (with Scry)
```
Screenshot:

![screenshot from 2018-12-06 16-22-04](https://user-images.githubusercontent.com/37827220/49574539-40e36600-f973-11e8-89e8-d1303086473d.png)

Code:
[rest.zip](https://github.com/crystal-lang/crystal/files/2652460/rest.zip)

**Comment by j8r** [comment]
Not directly related to the Crystal compiler itself.
A library you use, seems it's scry, want to create a file superior to the 255 bytes limit (https://serverfault.com/questions/9546/filename-length-limits-on-linux#9548)

**Comment by threeid** [comment]
I think so, but not sure where to post.

**Comment by j8r** [comment]
You can post to https://github.com/crystal-lang-tools/scry/issues
