### ISSUE TITLE
Signature of yielding methods

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#7157]
There are a few problems with signatures of yielding methods, which matter especially for API documentation.

<ins>Please ignore the following statements, they were not accurate (see https://github.com/crystal-lang/crystal/issues/7157#issuecomment-444962071)</ins>

<del>Two methods with the same name and arguments can still be different if one of them yields and thus requires to be called with a block:</del>
```cr
def foo(bar : Bar)
end

def foo(bar : Bar)
  yield
end
```
<del>However, both methods would appear in the API docs as `#foo(bar : Bar)`. There is no distinction whether a block is expected.
Details can obviously be stated in the description, but that's less prominent and not always available.

**The fact whether a method yields is part of it's signature and should be represented in the API docs.**</del>

To make the yielding nature visible, such methods are often declared with a block argument:

<ins>(The compiler actually adds this automatically if not declared.)</ins>
```cr
def foo(bar : Bar, &block)
  yield
end
```

This is already an improvement over no distinction in the method signature. But this creates a new issue: The block argument is really just a dummy and not actually used by the method. This make it impossible to distinguish a yielding method (inlining a block with `yield`) from a method receiving an *actual* block argument (calling `block.call` on a proc/captured block). These are not interchangeable and thus need to be distinguishable.

<del>Because it's just a dummy, the compiler doesn't even validate the type of the block argument, so you could declare `&block : (Foo, Bar) -> Baz` and it wouldn't even complain if the types don't fit. This could easily result in incorrect documentation in a place where you would expect the compiler to notify of any errors.</del>

In order to solve this, we need a designation for yielding methods which distinguishes it from a block argument. It should be automatically applied by the docs generator but allow for manual specification to allow defining expected types.

My suggestion for this would be a single ampersand `&`. Alternatively, it could be followed by an underscore `&_` which represents "a block argument bound to an unused variable".

A type declaration could follow just as with a regular block argument and would look like this:
```cr
def foo(bar : Bar, & : Bar -> Foo) : Foo
  yield bar
end
```
This uses a `Proc` type declaration while there is no actual `Proc` involved in a yielding method, but I think that's acceptable as long as it is explicitly distinguished from a block argument.

It would be a great enhancement if the compiler could verify that the declared types match the applied block signatures. But I guess that might be a little bit tricky.

If no types are declared, the docs generator would add a single `&` to the end of the method signature.
The arity (number of block arguments) could also be expressed as a number directly following the `&`, such that the method from the first example would be formatted as `#foo(bar : Bar, &1)`.

Declaring a real block argument (`&block`) on a yielding method should be a syntax error.

**Comment by asterite** [comment]
> However, both methods would appear in the API docs as #foo(bar : Bar)

This is false. The doc generator adds a `&block` argument in the docs. Check for example [this method](https://crystal-lang.org/api/0.27.0/Array.html#each_combination(size:Int=self.size,reuse=false,&block):Nil-instance-method) and [its source code](https://github.com/crystal-lang/crystal/blob/c9d1eef8fde5c7a03a029d64c8483ed7b4f2fe86/src/array.cr#L1068).

> This make it impossible to distinguish a yielding method (inlining a block with yield) from a method receiving an actual block argument (calling block.call on a proc/captured block). These are not interchangeable and thus need to be distinguishable.

This is actually the same as in Ruby, I see no problem with this (other than one might create a closure and the other doesn't, and that it's a PITA to implement this without a syntax distinction).

> Because it's just a dummy, the compiler doesn't even validate the type of the block argument, so you could declare &block : (Foo, Bar) -> Baz and it wouldn't even complain if the types don't fit.

Again, this is false. Even if you don't explicitly use the `block` argument, the compiler will check the types.

Proofs:
- https://play.crystal-lang.org/#/r/5pkw
- https://play.crystal-lang.org/#/r/5pkx

> A type declaration could follow just as with a regular block argument and would look like this:

I don't think that's a bad idea.

**Comment by straight-shoota** [comment]
Oh, I'm sorry. I didn't explicitly confirm every statement. I've dwelled on the idea for some time and I was under the impression that I acurrately described how the compiler/doc generator behaves. 
And I'm sure I've seen yielding methods without a block argument in the API docs signature, just can't find it. Maybe there is some kind of edge case? Or I might just be mis-remembering.

Anyway, I'll retract the incorrect statements.

The main issue remains distinguishing yielding methods from block arguments.

**Comment by asterite** [comment]
The logic is here:

https://github.com/crystal-lang/crystal/blob/30212064383ca791d8c70dc4daac2b655cafb326/src/compiler/crystal/tools/doc/method.cr#L145-L152

If there's an explicit block arg then it's printed. If not, but the method yields (this is the case you care about) a `&block` is appended.

**Comment by asterite** [comment]
From an implementation side, the main pain point is not being able to know at the call site whether a method will capture a block or just yield. If you knew that you could compute closured variables syntactically, but now it needs semantic.

Checking whether a method yields or captures a block at the method definition is very easy and it's already done: if the `block` argument is mentioned. However, it has one existing bug: if you mention it inside a macro the compiler doesn't notice it.

So... I'd say it's a good idea to have nameless block mean the block isn't captured and it's always going to use `yield`, and named block means it's captured. If we want to give an error if you specify a block argument but don't use it we have kind of the same problem: it could be mentioned in a macro. But this is easy to solve: the check could be done while the method is typed.

**Comment by straight-shoota** [comment]
Just to clarify: Specifying a block argument and not using it is fine. You just can't use `yield` then.

**Comment by asterite** [comment]
Oh, that makes sense. And it's also doable.

**Comment by oprypin** [comment]
Seems like this is fixed, e.g. https://crystal-lang.org/api/0.35.0/Enumerable.html#each_with_index(offset=0,&)-instance-method
