### ISSUE TITLE
[RFC] Enumerable methods with a pattern

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#7169]
It seems Ruby 2.5 added a few overloads to some `Enumerable` methods. Mainly, you can pass a `pattern` to some existing methods. For example:

```ruby
["foo", "bar", "baz"].all?(/a|o/) # => true
[1, 2, 3].all?(Numeric) # => true
[1, 2, 3].all?(0..10) # => true

[1, "foo", 3].any?(String) # => true
[false, ""].any?(Numeric) # => false
```

The `pattern` passed is compared against elements using `===`, similar to `case` and `=~`.

Would those overloads be useful to have in Crystal?

Their implementation is really simple, it's just a one-liner in most cases, but it could lead to very succinct code, specially when using `Regex` and ranges.

For some reason this `pattern` argument isn't present for `select` and `reject` (if anyone knows the real reason please let me know). However, there's `grep` and `grep_v` in Ruby (in Crystal too, except we don't have `grep_v` yet). Maybe this is the reason the `pattern` argument isn't present there.

I'm thinking, we could also support the `pattern` argument in `select` and `reject`:

```crystal
[1, 2, 3, 4, 5, 6].select(2..4) # => [2, 3, 4]
[1, "foo", 3].select(Int32) # => [1, 3]
```

For the last case, we could provide specific code for passing a type as an argument so that the resulting array has the correct type:

```crystal
typeof([1, "foo", 3].select(Int32)) # => Array(Int32)
```

Same goes for `reject` (it's a bit trickier to implement, but totally possible).

And with that we could remove `grep` altogether, if we really want to, to avoid aliases.

Thoughts?

**Comment by bcardiff** [comment]
Closing since it has been implemented and merged already 🚀
