### ISSUE TITLE
require for prelude: "can't find file" error depending on the working directory

### ISSUE THREAD

**Issue by zlotnleo** [crystal-lang/crystal#7181]
I want to run the Crystal compiler from crystal using a custom prelude, so I'm doing this:

    # src/main.cr
    require "compiler/crystal/**"
    ENV["CRYSTAL_PATH"]=`crystal env CRYSTAL_PATH`
    class MyCompiler < Crystal::Compiler
      @no_codegen = true
      @prelude = "./crs_prelude"
      def compile(sources, output_filename)
        node = super.node
        puts node # or do smth else with node
      end
    end

and

    # src/crs_prelude.cr
    require "empty" # minimal prelude

However, this depends on where `.` is in `./crs_prelude`, so it either works as intended or crashes with the following error depending on the current working directory.

    Unhandled exception: while requiring "./crs_prelude": can't find file './crs_prelude' relative to '.' (Crystal::TypeException)

Using absolute paths in `require` is not supported (#4105), so using `__DIR__` when setting `@prelude` is not an option.

Is there a way to specify the path relative to `src` folder or the project folder? If not, is it worth modifying the default `$CRYSTAL_PATH` based on `__DIR__` or is there a better way to do it? Also, would adding some way of requiring files relative to the project directory to the language be useful?

**Comment by asterite** [comment]
Hi!

What are you trying to do?

You can pass `--prelude {filename}` to use a custom prelude. If that's relative to your current project you can pass for example `--prelude ./my_file`.

However, note that `--prelude` exists mainly for the compiler developers to reproduce crashes on bare-bone programs (we use `--prelude=empty`). There's currently no other use for that, and if you want to use all what Crystal offers you probably don't want to use a prelude that's not the default one.

**Comment by zlotnleo** [comment]
I don't want to use a command-line argument for that because the `compile` method itself will have more stuff in it, namely processing of the AST. Unfortunately, there seems to be no way to completely avoid requiring prelude, and none of the "prelude" or "empty" would work for me, so I thought I'd write my own to address both these issues.

**Comment by asterite** [comment]
You want a fork of the compiler? If you change the compiler's source code you can do anything.

**Comment by zlotnleo** [comment]
In theory I could do that, but I'd rather use the compiler that I can require from any crystal code so that it can be kept up to date with the language.

**Comment by asterite** [comment]
Should `@prelude` be `"./src/crs_prelude"`?

**Comment by zlotnleo** [comment]
The issue is that I can't get it to work reliably regardless of where I'm running `crystal run` or `crystal build` from.

**Comment by RX14** [comment]
You need to put the prelude in a location which is on CRYSTAL_PATH then require it without using relative requires

**Comment by straight-shoota** [comment]
I don't think there is anything actionable here. Closing.
