### ISSUE TITLE
BUG: (Something::Entry | Nil) is not an InstanceVarContainer

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#7187]
I just did some internal exploring of `Hash`:
```cr
{"zero" => 0}.@buckets[0].@key
```
and got this!
```
Error in line 1: BUG: (Hash::Entry(String, Int32) | Nil) is not an InstanceVarContainer
```

Reduced without the hash:
```cr
class Something
  def initialize
    @buckets = Pointer(Entry?).malloc(0)
  end

  class Entry
  end
end

Something.new.@buckets[0].@doesnt_exist
```
```
Error in line 10: BUG: (Something::Entry | Nil) is not an InstanceVarContainer
```

**Comment by RX14** [comment]
```
class Foo
  @var = "const"
end

bar = Foo.new.as(Foo?).@var
```

It's just an ugly error, the real error is that `nil` doesn't have a `.@key`.

**Comment by asterite** [comment]
That, but also:

```crystal
class Foo
  @x = 1
end

class Bar
  @x = 1
end

z = Foo.new || Bar.new
p z.@x
```

Gives:

```
Error in foo.cr:10: BUG: (Bar | Foo) is not an InstanceVarContainer

p z.@x
  ^
```

Accessing an instance variable of a union type is not allowed right now and results in that.

I will first improve the error message. Then we can consider whether that makes sense (it would perform a kind of multiple dispatch, but for that you could use a method, it feels too hacky at this point).

**Comment by asterite** [comment]
Reopening because this will start working on 1.1.0

**Comment by HertzDevil** [comment]
What would happen afterwards? Allowing union types doesn't mean all variant types can store instance variables, like `Nil` in this case.

**Comment by asterite** [comment]
> What would happen afterwards? Allowing union types doesn't mean all variant types can store instance variables, like Nil in this case.

Good point. I forgot to clarify this: it would still be an error if any type in the union can't contain instance vars, or doesn't have that specific instance var.
