### ISSUE TITLE
case when with types does not constrain to valid types

### ISSUE THREAD

**Issue by leighmcculloch** [crystal-lang/crystal#7190]
I am using crystal version: 
```
Crystal 0.27.0 [c9d1eef8f] (2018-11-01)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```

I'm really new to Crystal. I've been writing some code that results in a variable being a union type or `String` or `Nil`. I spent a bit of time away from the code and came back to it and mistakenly thought my type would be a `Int32` or `Nil`. I'd forgotten it was `String` or `Nil`. I wrote a `case` `when` block that handled when the variable was an `Int32` and ran the program and it ran fine. To my surprise the program didn't do what I expected, in fact it didn't do anything, and this was because the variable is never an `Int32` and so that code path was not triggered.

Because the compiler doesn't let me call functions on union types that don't exist on both I mistakenly thought the compiler would prevent me from writing code that expected a variable could be a type that it couldn't be. I assumed the compiler to point out to me that I'd written a `when` statement with a type that the variable never is. The only types the variable can be is `String` or `Nil`, and not `Int32`.

The below case statement is a short example of what I did. `v` is never an `Int32` so it surprised me the compiler let me compile and run this code.

```crystal
v = "1" || Nil
case v 
when Int32
  puts "int: #{v}"
when Nil
  puts "nil"
end
```

If this is a bug or an area of the compiler that the designers of the language agree could be improved, I'd like to take a stab at contributing a change if it would be a good first contribution.

**Comment by vlazar** [comment]
@leighmcculloch In first line of your example you do `v = "1" || Nil` and `puts typeof(v)` would give you `(Nil.class | String)`, not `(Nil | String)`.

Sso `when Nil` in case statement does not match, which is correct since you need `v = "1" || nil` and not `v = "1" || Nil`. But in any case the result would be `String`, so no match in your case statement where you only have branches for `Int32` and `Nil`.

It looks like you want to declare a type as `String | Nil` here, you can do it with `v : String | Nil` or just `v : String?`.

So this would match on `when Nil`:
```crystal
v : String | Nil

v = nil

case v 
when String
  puts "string: #{v}"
when Nil
  puts "nil"
end
```

Or you can try some randomenes :)
```crystal
v = rand(1) > 0.5 ? "1" : nil

case v 
when String
  puts "string: #{v}"
when Nil
  puts "nil"
end
```

**Comment by asterite** [comment]
@leighmcculloch It works as expected and we'll never change it.

Consider this code:

```crystal
def foo(v)
  case v 
  when Int32
    puts "int: #{v}"
  when Nil
    puts "nil"
  end
end

foo(1)
```

Because methods in Crystal are instantiated based on the type you pass to them, the above is instantiated with `v : Int32`. Then `v` can never be `Nil` and you would get a compile error. But the code above is valid, you can pass int, nil, or anything you want and it should compile.

In your case it was probably just a bug. It's similar to having a typo, they are also hard to find.

Also, what @vlazar said about `Nil` vs `nil` is true.

**Comment by leighmcculloch** [comment]
Thanks for cleaning up my code @vlazar. Indeed it has many problems! I'm very new to Crystal.

@asterite If `v` is declared in a way that it can be anything as given by your example where `v` is not constrained to a specific type, then I agree. But that wasn't the case in my code I shared in the issue, `v` was very much constrained to `String` and `Nil`. Adapting your example to demonstrate you can see `v` is constrained to two types, but the case supports a type that `v` is incompatible with.

```crystal
def foo(v : String|Nil)
  case v               
  when Int32           
    puts "int: #{v}"   
  when Nil             
    puts "nil"         
  end                  
end
```

**Comment by RX14** [comment]
@leighmcculloch *despite* the type restriction of `v : String | Nil`, `typeof(v)` in `foo` will still be `Int`. This is a fundamental issue in the compiler and would take some serious serious thinking, a major breaking change and many weeks of effort to "fix". And doing so would fix compile times too...

**Comment by leighmcculloch** [comment]
I stumbled on a similar situation with a `case` statement that will compile and run when the type of value being cased on is different to the types in the when. I spent a while debugging some code because it was compiling and running but no whens were triggered. I've written a simplified version of the code below. This seems like the type of bug that a statically typed language would protect against. In other statically typed languages like Go this causes a compile error.

---

The crystal solution below will compile and print `0`. If you change the `"R"` and `"L"` to `'R'` and `'L'` the solution will compile and print `12`. I wouldn't have thought the crystal compiler would allow for comparing the character with a string if its type is known and it is never going to match.

```crystal
x = 0
instruction = "R12"
direction = instruction[0]
value = instruction[1..].to_i
case direction
when "R"
  x += value
when "L"
  x -= value
end
puts x
```
https://play.crystal-lang.org/#/r/84n6

---

The Go solution below will not compile. If you change the `"R"` and `"L"` to `'R'` and `'L'` the solution will compile and print `12`.
```go
x := 0
instruction := "R12"
direction := instruction[0]
value, _ := strconv.Atoi(instruction[1:])
switch direction {
case "R":
	x += value
case "L":
	x -= value
}
fmt.Println(x)
```
https://play.golang.org/p/zBJHTR4CVup

**Comment by caspiano** [comment]
As of Crystal 0.35.0, there is the `case ... in` construct to build exhaustive case statements that will not compile until all possible types of the value are matched. This is the construct to reach for when complete coverage of a value's possible types is required.

An interesting evolution of this issue could be producing a _warning_ when a branch in the exhaustive case is _not_ a member of value's type union.

I'm going to close this issue as not planned as producing a compiler error, in this case, is outside the semantics of the `case ... when` statement.
