### ISSUE TITLE
pending test causes incorrect test count and malformed output

### ISSUE THREAD

**Issue by leighmcculloch** [crystal-lang/crystal#7192]
Version of crystal:
```
Crystal 0.27.0 [c9d1eef8f] (2018-11-01)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```

When I mark a test as pending the count of tests and test output are malformed.

I wrote the following test.
```crystal
describe "my tests" do
  it "1 equals 1.0" do
    1.should eq 1.0
  end
end
```

Running the test correctly outputs one green test displays the expected output.
<img width="481" alt="screen shot 2018-12-16 at 8 24 31 am" src="https://user-images.githubusercontent.com/351529/50056073-06fd2700-010c-11e9-9541-2fd4496990d6.png">

When I mark the test as pending, things will get interesting.
```crystal
describe "my tests" do
  it "1 equals 1.0" do
    pending "something"
    1.should eq 1.0
  end
end
```

The output shows two examples and the verbose output is malformed with the word `something` showing up twice on the first example listed and only `1.0` from the test name is shown, not the full name `1 equals 1.0`.
<img width="482" alt="screen shot 2018-12-16 at 8 23 49 am" src="https://user-images.githubusercontent.com/351529/50056068-edf47600-010b-11e9-8a7b-9d2342e0ea42.png">

The non-verbose spec output also shows two examples, although is not malformed.
<img width="482" alt="screen shot 2018-12-16 at 8 25 30 am" src="https://user-images.githubusercontent.com/351529/50056082-301db780-010c-11e9-81ee-f7ff5fcec452.png">

**Comment by asterite** [comment]
You should replace `it` with pending, not nest `pending` inside `it`.

**Comment by leighmcculloch** [comment]
@RX14 Could we make `it`/`pending` undefined inside an `it`?

**Comment by asterite** [comment]
@RX14 Definitely! That, and also disallowing `it` outside of `describe`, and also `.should` outside `it`. I think it's possible and it would be a great addition (I've been bitten by some of those in the past).

Let's keep this open to improve this situation.
