### ISSUE TITLE
Error in line 11: instantiating 'Crystal::Playground::Agent#i(Int32)'

### ISSUE THREAD

**Issue by burpsuite** [crystal-lang/crystal#7203]
## Description
This bug will only be triggered in [Crystal Playground].

## Problem Code
```crystal
text = "abcdefghijklmn"
(split = text.split("")).size.times do
  1
end

puts split
```

## Exception
```text
Bug
You've reached a bug in the playground. Please let us know about it.

Code
text = "abcdefghijklmn"
(split = text.split("")).size.times do
  1
end

puts split
Exception
Error in line 11: instantiating 'Crystal::Playground::Agent#i(Int32)'
in line 11: instantiating 'Crystal::Playground::Agent#i(Int32)'
in line 12: undefined local variable or method 'split'
```

## Version
```text
Crystal 0.27.0 (2018-11-04)
LLVM: 6.0.1
Default target: x86_64-apple-macosx
```

## Screenshot
<img width="1440" alt="2018-12-20 02 50 00" src="https://user-images.githubusercontent.com/14309190/50241567-c0a51200-0402-11e9-94d5-28155572f28d.png">
<img width="1440" alt="2018-12-20 02 49 44" src="https://user-images.githubusercontent.com/14309190/50241561-bd118b00-0402-11e9-8318-90126a79cc59.png">
<img width="1440" alt="2018-12-20 02 50 52" src="https://user-images.githubusercontent.com/14309190/50241570-c3a00280-0402-11e9-931c-ffc52594b283.png">

**Comment by bcardiff** [comment]
For a workaround I would suggest simpler code like:

```crystal
text = "abcdefghijklmn"
split = text.split("")

split.size.times do
  1
end

puts split
```

for the record, the instrumentation that breaks this example is:

```crystal
text = _p.i(1) do
  "abcdefghijklmn"
end
_p.i(2) do
  (split = text.split("")).size.times do
    _p.i(3) do
      1
    end
  end
end
puts(_p.i(6) do
  split
end)
```

NB: running `crystal play -v` will show the instrumentation used.

**Comment by bcardiff** [comment]
@burpsuite I meant that running `$ crystal play -v` (in verbose) will show some more info that could help to know what is the problem with the code transformation. For example the `split` variable is defined inside a block `_p.i(2) do` and that is why the expression at the end is not able to see it.

Thanks & keep experimenting with crystal :-)

**Comment by burpsuite** [comment]
Okay, Thanks :)

**Comment by burpsuite** [comment]
Duplicate of #7091
