### ISSUE TITLE
It is possible to destructuring assign like js?

### ISSUE THREAD

**Issue by excosy** [crystal-lang/crystal#7215]
Since `a, b = 1, 2`, array destructuring, has been achieved, it is possible to parse object destructuring, like this:
```
s = {a: 1, b: 2}
{a, b} = s
```
can set `a = 1` and `b = 2`, and also, able to assign new variable names
```
s = {p: 1, q: 2}
{p: a, q: b} = s
```
can set `a = 1` and `b = 2`
and set default values, etc.

**Comment by asterite** [comment]
No, it's not possible. And it wouldn't be very useful either because named tuples are not that common in Crystal (their main usage is being able to represent their type in double splats). And instead of `{a, b} = ...` you can just write `a, b = ...` which is shorter.

**Comment by asterite** [comment]
And please, ask this questions in the [forum](https://forum.crystal-lang.org/c/help-support). Thank you!
