### ISSUE TITLE
print array of struct override of to_s

### ISSUE THREAD

**Issue by MohamedLEGH** [crystal-lang/crystal#7216]
I'm a newbie in Crystal so I'm sorry if my question is obvious.
I want to override to `to_s(io)` method to be able to print a struct/class the way I want.
Unfortunately it doesn't work for array of struct, as you can see.

```crystal
struct Test
  def to_s(io)
    io << "hello world"
  end
end
a = Test.new
b = Test.new
c = [a,b]
puts a
puts c[0]
puts c
```
output:
```
hello world
hello world
[Test(), Test()]
```
https://play.crystal-lang.org/#/r/5upo

I would have expected the output of `puts c` to be `[hello world, hello world]` .
Why isn't it the case?

**Comment by asterite** [comment]
`Array`, `Hash` and other data types call `inspect` on the elements. You must override `inspect(io)` for what you want.

**Comment by asterite** [comment]
The reason why this is like it is is long, but the tl;dr is that `inspect` shows the object in a clearly delimited way (string will have quotes around them) while with `to_s` this is not guaranteed.

**Comment by MohamedLEGH** [comment]
Ok thanks,
so maybe the api documentation should be updated,
because in https://crystal-lang.org/api/0.27.0/Struct.html#to_s%28io%29-instance-method
`to_s` is defined as 

> Same as #inspect(io).

**Comment by asterite** [comment]
@MohamedLEGH The docs are correct: the default implementation of `to_s` is to call `inspect`. If you override `to_s` then you are changing that behavior.
