### ISSUE TITLE
Over careful compiler?

### ISSUE THREAD

**Issue by Indribell** [crystal-lang/crystal#7217]
The following class create a interesting error

```
    class Service

        def initialize( @version : String )
        end

        def initialize( @version : String, database_uri : String )
                @db = DB.open database_uri
        end

    end
```

```
Error in /home/xxx/Crystal/Shared/Service.cr:8: this 'initialize' doesn't initialize instance variable '@db', rendering it nilable

        def initialize( @version : String )

```

From my understanding it is possible to override functions with different behavior. As this service can be run with or without a database ( depending on the parent class its usage or none usage of a database ).

So this error seems a bit over greedy?

**Comment by z64** [comment]
Whether you actually want to allow `@db` to be nilable can't be left ambiguous:

```cr
class Service
  def initialize( @version : String )
    @db = nil
  end

  def initialize( @version : String, database_uri : String )
    @db = database_uri
  end
end

p Service.new("version") # #<Service:0x56190b693f20 @version="version", @db=nil>
p Service.new("version", "db") #<Service:0x56190b693f20 @version="version", @db="db">
```

Or alternatively:

```cr
class Service
  @db : DB::Database?

  def initialize( @version : String )
  end

  def initialize( @version : String, database_uri : String )
    @db = DB.open database_uri
  end
end
```

If defining the other constructor "silently" changed `@db` to `Database | Nil`, that may cause unintended or other confusing compiler errors elsewhere in the code where `@db` is used later.

Now with `@db : DB::Database?`, you can actually check if a database is available:
```cr
def some_action
  if db = @db 
    # use db here
  else
    # db-less logic
  end
end
```
or similar

**Comment by Indribell** [comment]
The first solution works:

```
  def initialize( @version : String )
    @db = nil
  end
```

> If defining the other constructor "silently" changed @db to Database | Nil, that may cause unintended or other confusing compiler errors elsewhere in the code where @db is used later.

Indeed. When using @db : DB::Database? it introduces other issues.

```

instantiating 'get_db(HTTP::Server::Response, HTTP::Request)'
in src/Proxy.cr:55: undefined method 'query_all' for Nil (compile-time type is (DB::Database | Nil))

    episodes2 = @db.query_all "SELECT id, title FROM episodes", as: {id: Int64, title: String}
                    ^~~~~~~~~

Rerun with --error-trace to show a complete error trace.
```

Thanks for the help Closing the topic.
