### ISSUE TITLE
LLVM error on building crystal from source.

### ISSUE THREAD

**Issue by hanare** [crystal-lang/crystal#7219]
$ make 
Using /usr/local/bin/llvm-config [version=7.0.1]
g++ -c  -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc -I/usr/local/include  -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wno-class-memaccess -Wdelete-non-virtual-dtor -Wno-comment -g  -fno-exceptions -fno-rtti -D_GNU_SOURCE -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
src/llvm/ext/llvm_ext.cc:89:17: error: conflicting declaration of C function ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateFunction(DIBuilderRef, LLVMMetadataRef, const char*, const char*, LLVMMetadataRef, unsigned int, LLVMMetadataRef, bool, bool, unsigned int, llvm::DINode::DIFlags, bool, LLVMValueRef)’
 LLVMMetadataRef LLVMDIBuilderCreateFunction(
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/llvm/ext/llvm_ext.cc:24:
/usr/local/include/llvm-c/DebugInfo.h:277:17: note: previous declaration ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateFunction(LLVMDIBuilderRef, LLVMMetadataRef, const char*, size_t, const char*, size_t, LLVMMetadataRef, unsigned int, LLVMMetadataRef, LLVMBool, LLVMBool, unsigned int, LLVMDIFlags, LLVMBool)’
 LLVMMetadataRef LLVMDIBuilderCreateFunction(
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/llvm/ext/llvm_ext.cc:109:17: error: conflicting declaration of C function ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateLexicalBlock(DIBuilderRef, LLVMMetadataRef, LLVMMetadataRef, unsigned int, unsigned int)’
 LLVMMetadataRef LLVMDIBuilderCreateLexicalBlock(DIBuilderRef Dref,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/llvm/ext/llvm_ext.cc:24:
/usr/local/include/llvm-c/DebugInfo.h:292:17: note: previous declaration ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateLexicalBlock(LLVMDIBuilderRef, LLVMMetadataRef, LLVMMetadataRef, unsigned int, unsigned int)’
 LLVMMetadataRef LLVMDIBuilderCreateLexicalBlock(
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/llvm/ext/llvm_ext.cc:118:17: error: conflicting declaration of C function ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateBasicType(DIBuilderRef, const char*, uint64_t, uint64_t, unsigned int)’
 LLVMMetadataRef LLVMDIBuilderCreateBasicType(DIBuilderRef Dref,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/llvm/ext/llvm_ext.cc:24:
/usr/local/include/llvm-c/DebugInfo.h:536:1: note: previous declaration ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateBasicType(LLVMDIBuilderRef, const char*, size_t, uint64_t, LLVMDWARFTypeEncoding)’
 LLVMDIBuilderCreateBasicType(LLVMDIBuilderRef Builder, const char *Name,
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/llvm/ext/llvm_ext.cc:130:17: error: conflicting declaration of C function ‘LLVMOpaqueMetadata* LLVMDIBuilderGetOrCreateTypeArray(DIBuilderRef, LLVMOpaqueMetadata**, unsigned int)’
 LLVMMetadataRef LLVMDIBuilderGetOrCreateTypeArray(DIBuilderRef Dref,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/llvm/ext/llvm_ext.cc:24:
/usr/local/include/llvm-c/DebugInfo.h:420:17: note: previous declaration ‘LLVMOpaqueMetadata* LLVMDIBuilderGetOrCreateTypeArray(LLVMDIBuilderRef, LLVMOpaqueMetadata**, size_t)’
 LLVMMetadataRef LLVMDIBuilderGetOrCreateTypeArray(LLVMDIBuilderRef Builder,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/llvm/ext/llvm_ext.cc:139:17: error: conflicting declaration of C function ‘LLVMOpaqueMetadata* LLVMDIBuilderGetOrCreateArray(DIBuilderRef, LLVMOpaqueMetadata**, unsigned int)’
 LLVMMetadataRef LLVMDIBuilderGetOrCreateArray(DIBuilderRef Dref,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/llvm/ext/llvm_ext.cc:24:
/usr/local/include/llvm-c/DebugInfo.h:929:17: note: previous declaration ‘LLVMOpaqueMetadata* LLVMDIBuilderGetOrCreateArray(LLVMDIBuilderRef, LLVMOpaqueMetadata**, size_t)’
 LLVMMetadataRef LLVMDIBuilderGetOrCreateArray(LLVMDIBuilderRef Builder,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/llvm/ext/llvm_ext.cc:148:1: error: conflicting declaration of C function ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateSubroutineType(DIBuilderRef, LLVMMetadataRef, LLVMMetadataRef)’
 LLVMDIBuilderCreateSubroutineType(DIBuilderRef Dref, LLVMMetadataRef File,
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/llvm/ext/llvm_ext.cc:24:
/usr/local/include/llvm-c/DebugInfo.h:435:1: note: previous declaration ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateSubroutineType(LLVMDIBuilderRef, LLVMMetadataRef, LLVMOpaqueMetadata**, unsigned int, LLVMDIFlags)’
 LLVMDIBuilderCreateSubroutineType(LLVMDIBuilderRef Builder,
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/llvm/ext/llvm_ext.cc:154:17: error: conflicting declaration of C function ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateAutoVariable(DIBuilderRef, LLVMMetadataRef, const char*, LLVMMetadataRef, unsigned int, LLVMMetadataRef, int, llvm::DINode::DIFlags, uint32_t)’
 LLVMMetadataRef LLVMDIBuilderCreateAutoVariable(
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/llvm/ext/llvm_ext.cc:24:
/usr/local/include/llvm-c/DebugInfo.h:1115:17: note: previous declaration ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateAutoVariable(LLVMDIBuilderRef, LLVMMetadataRef, const char*, size_t, LLVMMetadataRef, unsigned int, LLVMMetadataRef, LLVMBool, LLVMDIFlags, uint32_t)’
 LLVMMetadataRef LLVMDIBuilderCreateAutoVariable(
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/llvm/ext/llvm_ext.cc:176:17: error: conflicting declaration of C function ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateParameterVariable(DIBuilderRef, LLVMMetadataRef, const char*, unsigned int, LLVMMetadataRef, unsigned int, LLVMMetadataRef, int, llvm::DINode::DIFlags)’
 LLVMMetadataRef LLVMDIBuilderCreateParameterVariable(
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/llvm/ext/llvm_ext.cc:24:
/usr/local/include/llvm-c/DebugInfo.h:1133:17: note: previous declaration ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateParameterVariable(LLVMDIBuilderRef, LLVMMetadataRef, const char*, size_t, unsigned int, LLVMMetadataRef, unsigned int, LLVMMetadataRef, LLVMBool, LLVMDIFlags)’
 LLVMMetadataRef LLVMDIBuilderCreateParameterVariable(
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/llvm/ext/llvm_ext.cc:192:14: error: conflicting declaration of C function ‘LLVMOpaqueValue* LLVMDIBuilderInsertDeclareAtEnd(DIBuilderRef, LLVMValueRef, LLVMMetadataRef, LLVMMetadataRef, LLVMValueRef, LLVMBasicBlockRef)’
 LLVMValueRef LLVMDIBuilderInsertDeclareAtEnd(DIBuilderRef Dref,
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/llvm/ext/llvm_ext.cc:24:
/usr/local/include/llvm-c/DebugInfo.h:1064:14: note: previous declaration ‘LLVMOpaqueValue* LLVMDIBuilderInsertDeclareAtEnd(LLVMDIBuilderRef, LLVMValueRef, LLVMMetadataRef, LLVMMetadataRef, LLVMMetadataRef, LLVMBasicBlockRef)’
 LLVMValueRef LLVMDIBuilderInsertDeclareAtEnd(
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/llvm/ext/llvm_ext.cc:206:17: error: conflicting declaration of C function ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateExpression(DIBuilderRef, int64_t*, size_t)’
 LLVMMetadataRef LLVMDIBuilderCreateExpression(DIBuilderRef Dref, int64_t *Addr,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/llvm/ext/llvm_ext.cc:24:
/usr/local/include/llvm-c/DebugInfo.h:940:17: note: previous declaration ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateExpression(LLVMDIBuilderRef, int64_t*, size_t)’
 LLVMMetadataRef LLVMDIBuilderCreateExpression(LLVMDIBuilderRef Builder,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/llvm/ext/llvm_ext.cc:211:17: error: conflicting declaration of C function ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateEnumerationType(DIBuilderRef, LLVMMetadataRef, const char*, LLVMMetadataRef, unsigned int, uint64_t, uint64_t, LLVMMetadataRef, LLVMMetadataRef)’
 LLVMMetadataRef LLVMDIBuilderCreateEnumerationType(
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/llvm/ext/llvm_ext.cc:24:
/usr/local/include/llvm-c/DebugInfo.h:455:17: note: previous declaration ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateEnumerationType(LLVMDIBuilderRef, LLVMMetadataRef, const char*, size_t, LLVMMetadataRef, unsigned int, uint64_t, uint32_t, LLVMOpaqueMetadata**, unsigned int, LLVMMetadataRef)’
 LLVMMetadataRef LLVMDIBuilderCreateEnumerationType(
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/llvm/ext/llvm_ext.cc:230:1: error: conflicting declaration of C function ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateStructType(DIBuilderRef, LLVMMetadataRef, const char*, LLVMMetadataRef, unsigned int, uint64_t, uint64_t, llvm::DINode::DIFlags, LLVMMetadataRef, LLVMMetadataRef)’
 LLVMDIBuilderCreateStructType(DIBuilderRef Dref,
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/llvm/ext/llvm_ext.cc:24:
/usr/local/include/llvm-c/DebugInfo.h:573:17: note: previous declaration ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateStructType(LLVMDIBuilderRef, LLVMMetadataRef, const char*, size_t, LLVMMetadataRef, unsigned int, uint64_t, uint32_t, LLVMDIFlags, LLVMMetadataRef, LLVMOpaqueMetadata**, unsigned int, unsigned int, LLVMMetadataRef, const char*, size_t)’
 LLVMMetadataRef LLVMDIBuilderCreateStructType(
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/llvm/ext/llvm_ext.cc:252:1: error: conflicting declaration of C function ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateReplaceableCompositeType(DIBuilderRef, LLVMMetadataRef, const char*, LLVMMetadataRef, unsigned int)’
 LLVMDIBuilderCreateReplaceableCompositeType(DIBuilderRef Dref,
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/llvm/ext/llvm_ext.cc:24:
/usr/local/include/llvm-c/DebugInfo.h:793:1: note: previous declaration ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateReplaceableCompositeType(LLVMDIBuilderRef, unsigned int, const char*, size_t, LLVMMetadataRef, LLVMMetadataRef, unsigned int, unsigned int, uint64_t, uint32_t, LLVMDIFlags, const char*, size_t)’
 LLVMDIBuilderCreateReplaceableCompositeType(
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/llvm/ext/llvm_ext.cc:279:1: error: conflicting declaration of C function ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateMemberType(DIBuilderRef, LLVMMetadataRef, const char*, LLVMMetadataRef, unsigned int, uint64_t, uint64_t, uint64_t, llvm::DINode::DIFlags, LLVMMetadataRef)’
 LLVMDIBuilderCreateMemberType(DIBuilderRef Dref, LLVMMetadataRef Scope,
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/llvm/ext/llvm_ext.cc:24:
/usr/local/include/llvm-c/DebugInfo.h:595:17: note: previous declaration ‘LLVMOpaqueMetadata* LLVMDIBuilderCreateMemberType(LLVMDIBuilderRef, LLVMMetadataRef, const char*, size_t, LLVMMetadataRef, unsigned int, uint64_t, uint32_t, uint64_t, LLVMDIFlags, LLVMMetadataRef)’
 LLVMMetadataRef LLVMDIBuilderCreateMemberType(
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/llvm/ext/llvm_ext.cc:295:17: error: conflicting declaration of C function ‘LLVMOpaqueMetadata* LLVMDIBuilderCreatePointerType(DIBuilderRef, LLVMMetadataRef, uint64_t, uint64_t, const char*)’
 LLVMMetadataRef LLVMDIBuilderCreatePointerType(DIBuilderRef Dref,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/llvm/ext/llvm_ext.cc:24:
/usr/local/include/llvm-c/DebugInfo.h:550:17: note: previous declaration ‘LLVMOpaqueMetadata* LLVMDIBuilderCreatePointerType(LLVMDIBuilderRef, LLVMMetadataRef, uint64_t, uint32_t, unsigned int, const char*, size_t)’
 LLVMMetadataRef LLVMDIBuilderCreatePointerType(
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/llvm/ext/llvm_ext.cc:309:17: error: conflicting declaration of C function ‘LLVMOpaqueMetadata* LLVMTemporaryMDNode(LLVMContextRef, LLVMOpaqueMetadata**, unsigned int)’
 LLVMMetadataRef LLVMTemporaryMDNode(LLVMContextRef C, LLVMMetadataRef *MDs,
                 ^~~~~~~~~~~~~~~~~~~
In file included from src/llvm/ext/llvm_ext.cc:24:
/usr/local/include/llvm-c/DebugInfo.h:991:17: note: previous declaration ‘LLVMOpaqueMetadata* LLVMTemporaryMDNode(LLVMContextRef, LLVMOpaqueMetadata**, size_t)’
 LLVMMetadataRef LLVMTemporaryMDNode(LLVMContextRef Ctx, LLVMMetadataRef *Data,
                 ^~~~~~~~~~~~~~~~~~~
src/llvm/ext/llvm_ext.cc: In function ‘void LLVMWriteBitcodeWithSummaryToFile(LLVMModuleRef, const char*)’:
src/llvm/ext/llvm_ext.cc:443:28: error: invalid initialization of reference of type ‘const llvm::Module&’ from expression of type ‘llvm::Module*’
   llvm::WriteBitcodeToFile(m, OS, true, &moduleSummaryIndex, true);
                            ^
In file included from src/llvm/ext/llvm_ext.cc:28:
/usr/local/include/llvm/Bitcode/BitcodeWriter.h:129:8: note: in passing argument 1 of ‘void llvm::WriteBitcodeToFile(const llvm::Module&, llvm::raw_ostream&, bool, const llvm::ModuleSummaryIndex*, bool, llvm::ModuleHash*)’
   void WriteBitcodeToFile(const Module &M, raw_ostream &Out,
        ^~~~~~~~~~~~~~~~~~
make: *** [Makefile:126: src/llvm/ext/llvm_ext.o] Error 1

OS : FEDORA 29,
 llvm-config version = 7.0.1 
g++ --version g++ (GCC) 8.2.1 20181215 (Red Hat 8.2.1-6)
llvm built from source.

**Comment by hanare** [comment]
So what is the work around, the issue #6754 is still open . Do I have to downgrade my llvm ?

**Comment by bcardiff** [comment]
@hanare yes you need llvm 6 or lower for now
