### ISSUE TITLE
Add TypeNode#docs method

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#7273]
It would be nice to be able to extract docs related to a node just like `TypeNode#annotation` does with annotations:

```crystal
# It's the `Foo` class
class Foo
  # It's the `@bar` variable
  @bar : String

  # It's the `#foo` method
  def foo
  end
end

{% pp Foo.docs %}
{% for ivar in Foo.instance_vars %}
  {% pp ivar.docs %}
{% end %}
{% for method in Foo.methods %}
  {% pp method.docs %}
{% end %}
```

```console
"It's the `Foo` class"
"It's the `@bar` variable"
"It's the `#foo` method"
```
 
A possible (and actual) use-case is generating REST API docs with ease:

```crystal
# Return user by its ID
class Users::Get < Action
  # The User's ID
  @id : Int32
end
```

```console
crystal src/generate-docs
```

```json
{
  "actions": [
    {
      "Users::Get": {
        "description": "Return user by its ID",
        "params": {
          "id": {
            "type": "Int32"
          }
        }
      }
    }
  ]
}
```

Of course, it could be achieved with annotations, but `.docs` methods will make code documentation serve multiple purposes. I'm sure that there are tons of other use-cases where extracting the docs could be useful.

**Comment by straight-shoota** [comment]
What's the use case for having a `#docs` methods available in Crystal code?
The example usage of `crystal src/generate-docs` can probably already be implemented with `crystal docs`.

**Comment by vladfaust** [comment]
@straight-shoota, here you go:

A possible (and actual) use-case is generating REST API docs with ease:

```crystal
# Return user by its ID
class Users::Get < Action
  # The User's ID
  @id : Int32
end
```

```console
crystal src/generate-docs
```

```json
{
  "actions": [
    {
      "Users::Get": {
        "description": "Return user by its ID",
        "params": {
          "id": {
            "type": "Int32"
          }
        }
      }
    }
  ]
}
```

That JSON could be served in a handler, say `Handlers::APISchema`.

**Comment by straight-shoota** [comment]
But the schema doesn't change at runtime. You can easily embed it at compile time (simplified: ``{{ run `crystal docs --format json` }}``).

**Comment by vladfaust** [comment]
Plus it would be not an "easy embedding" if I want to extract REST Actions docs explicitly, because macros don't have that much tools to work with JSON strings. It would be easier to actually put docs one-by-one into JSON instead.

**Comment by straight-shoota** [comment]
The `--format` option is available in master and will be included in `0.27.1`.

**Comment by vladfaust** [comment]
@straight-shoota still requires to dive into the JSON in macros, which ain't easy at all.

**Comment by Sija** [comment]
@vladfaust you could write a helper script for that, use `jq` or other means.

**Comment by vladfaust** [comment]
@Sija true. Still, calling `crystal docs` will build docs for the whole program, while what I want is certain namespace. It would be much slower than extracting docs for a limited set of types. And it's a common scenario to require these generated docs in development, i.e. to have fresh REST API schema on every development server start.

**Comment by buckle2000** [comment]
Something like pydoc will be great

**Comment by Sija** [comment]
@buckle2000 isn't it like `ri` in ruby-land?

**Comment by buckle2000** [comment]
> @buckle2000 isn't it like `ri` in ruby-land?

I don't use ruby. It's like `ri` but non-interactive.

**Comment by matthewmcgarvey** [comment]
Another use case is for a language-server-protocol like Scry to be able to load the documentation for a module/class/method on hover.  I think this should be a crystal tool

**Comment by Blacksmoke16** [comment]
Also had a plan to use this to auto fill out the `description` field of [OAS 3.0 Schema Object](https://swagger.io/specification/#schemaObject) to the docs applied to an ivar/property.  Would also allow for setting the `title` to like the first line/sentence etc.

**Comment by asterite** [comment]
Note that for performance reasons documentation on top of AST nodes is not stored unless the compiler operates on doc mode. That means docs can't be available using reflection, unless we are willing to increase the memory occupied at runtime... (for me it's a "no").

**Comment by Blacksmoke16** [comment]
Fair enough, I'll go to plan B then.
