### ISSUE TITLE
Confusing and incorrect compiler error tracing

### ISSUE THREAD

**Issue by Indribell** [crystal-lang/crystal#7281]
Crystal provides a confusing error reporting in the following situation.

Take the following example.  Port being a Int64 is wrong, as it needs to be a Int32 for server.listen.

```
require "http/server"

def start( ip : String, port : Int64 )

    server = HTTP::Server.new( [ HTTP::ErrorHandler.new, HTTP::LogHandler.new]  ) do |context|
        context.response.status_code = 200
    end
    server.listen(ip, port, reuse_port: true)
end

start("0.0.0.0", 25666)
```

You expect Crystal to point out that "port" is the wrong type for the listen function. But we get the following error reporting:

```
Error in test2.cr:11: instantiating 'start(String, Int32)'

start("0.0.0.0", 25666)
^~~~~

in test2.cr:8: argument 'reuse_port' already specified

    server.listen(ip, port, reuse_port: true)
```

It shows the actual function start as being (String, Int32), when its defined as a (String, Int64). But it also mangles up the server.listen error explanation, pointing to reuse_port, when that is the correct syntax and order. 

This type of error reporting can send users down a rabbit hole of hours debugging the server.listen function, when its actually in a different location. Even worse is that the way  start is being portrayed as (String, Int32), makes it easy to overlook because it matches what server.listen expects to be provided.

I am sure this type of bad error reporting can be created in any crystal functions.

**Comment by bew** [comment]
@Indribell thanks for reporting this, it should now be fixed in master
