### ISSUE TITLE
Method to determine if logger's io is nil

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#7283]
Add a method to `logger.cr` that returns true if `@io` is nil.  

Use case for this would be determining if an app should even try to log messages based on an app wide logger.  This would allow for a simple, something like, `log statement unless App.settings.logger.silenced?`

I can make a PR if this would be something that would be needed.

**Comment by bcardiff** [comment]
The logger will probably change a lot not far in the future. Ref: #6901.

The notion of silenced is a bit narrow regarding log levels IMO.

I would prefer to focus on handling efficiently the scenario where the event should not be logged due to the level and other logger of the configuration.

**Comment by RX14** [comment]
the correct design is for logging messages to take a block which is only executed when the message is known to be used. This moves all the becks to the logging library. But this needs to wait until `Logger` is refactored.

**Comment by RX14** [comment]
I just checked `Logger`. This already exists: Just use `log { statement }`

**Comment by Blacksmoke16** [comment]
@Rx14 yes but say you run the statement through a method to colorize it, but you don't want to colorize it in the first place if the logger will just ignore it when it goes to print.
