### ISSUE TITLE
`do` binding

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#7286]
Code sample (https://carc.in/#/r/5y09):

```crystal
spawn loop do
  puts "Hello"
  sleep(1)
end

sleep
```

```console
'loop' is expected to be invoked with a block, but no block was given
```

Fixed with `spawn do; loop do`. May be a bug, though.

**Comment by RX14** [comment]
This could be changed to have the same parsing rules as `{`, I tried ages ago and it didn't work, I think because I was enforcing brackets around block args, but then that makes DSLs ugly (like spec) so I ditched it.

Making `do` bind like `{` on it's own I think could work well.

**Comment by Sija** [comment]
FWIW judging by the amount of issues on GH, that's not really a popular issue and putting an extra parentheses in those few cases is not that a big deal. Is it really worth investing time in changing whole language semantics based on few edge cases?

**Comment by RX14** [comment]
I'm not going to work on it, I can't see anyone else core team working on it, but I wouldn't reject a working PR if it was submitted. That's why this is open.

**Comment by straight-shoota** [comment]
> I wouldn't reject a working PR if it was submitted.

I think we'd have to decide first *what* a working PR is actually supposed to implement.

The situation is confusing, and it's not just a few edge cases. I guess most Crystal developers have already fallen into that trap: When you want to print the result of a call, usually you simply insert `p` before it. When the call has a `do` block that doesn't work and it's annoying.

Still, there is no obvious solution that would fix all angle of this problem. At least it hasn't been presented yet.

**Comment by RX14** [comment]
Actually, changing it would be confusing because:
```cr

it "spec name" do
end
```

and
```cr
foo = "spec name"
it foo do
end

suddenly mean different things.

I think this is probably fine as-is/

**Comment by vladfaust** [comment]
Okay, the `it` example is quite strong. But what if leaving the logic as-is, but make exceptions for special keywords like `loop`, `while`, `until` etc?

**Comment by RX14** [comment]
Exceptions just create more problems, crystal has enough rules and complexity as-is.

**Comment by bcardiff** [comment]
@vladfaust as a reminder, loop is not a keyword, hence its needs for a `do`. Control structures don’t need it.

Having block and curly braces y good in different situations like chaining and avoiding parenthesis around arguments.

I vote closing here.

Ref: https://stackoverflow.com/a/5587403
