### ISSUE TITLE
Bug: called 'range' for non-integer literal

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#7287]
```crystal
def foo(i : Int::Unsigned)
  pp! i
end

foo(-1)
```

```console
Bug: called 'range' for non-integer literal (Exception)
```

---

Originally:

It would be handy to restrict a def argument to be positive:

Expected:

```crystal
def foo(i : UInt)
end

foo(-1) # Compile-time error ✔
```

Got:

```console
undefined constant UInt (did you mean 'Int')
```

We have `Int` for unknown-size integers, but don't have `UInt` for unknown-size *positive* integers.

**Comment by Sija** [comment]
There's `Int::Unsigned` alias.

**Comment by vladfaust** [comment]
:thinking: 

> https://carc.in/#/r/5y1z

```crystal
def foo(i : Int::Unsigned)
  pp! i
end

foo(-1)
```

```console
Bug: called 'range' for non-integer literal (Exception)
```

**Comment by Sija** [comment]
Ouch. It seems broken since `0.25`. Auto casting again?

**Comment by vladfaust** [comment]
@RX14 any reasons not to see `UInt` in 1.0?

**Comment by RX14** [comment]
@vladfaust what do you want the differences between `UInt` and `Int::Unsigned` to be???

**Comment by vladfaust** [comment]
It confusing to have `IntN` and `Int`, but `UIntN` without `UInt`.

**Comment by straight-shoota** [comment]
@vladfaust The counterpart to `IntX` is `Int::Signed`. `Int` is the parent type for all integer types, including `UIntX`.

**Comment by asterite** [comment]
This is already fixed in master, the bug happens because automatic casting wasn't supported for `UInt128` and `Int128`, but @bcardiff recently sent a PR that fixes that.
