### ISSUE TITLE
Move out the formatter to its own repo

### ISSUE THREAD

**Issue by j8r** [crystal-lang/crystal#7290]
This suggestion doesn't necessarily mean to remove `crystal tool format`. Probably other elements like the playground depend of it, so it could be integrated via Git subtree/submodule. I don't even talk technically if easy/hard/impossible to do. On the principle, the points are:
- this allows to more easily fork the formatter and customize it, instead of doing so for the whole language
- IMHO, that's not up to me of course, seeing [all the contributions done in the formatter](https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/tools/formatter.cr), @MakeNowJust could even be a maintainer of the repo (Thanks to him for his work ❤️ )
- it can ease the reorganization of [formatter.cr](https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/tools/formatter.cr), which is a big file. The tree will be much less deep than from `crystal-lang/src/compiler/...`

A good formatter is important of course, but it's not critical to the language. That's also a reason why I think it can be splitted out from the monorepo.

Precedents: https://github.com/rust-lang/rustfmt , numerous nodejs formatters

**Comment by RX14** [comment]
> * this allows to more easily fork the formatter and customize it, instead of doing so for the whole language
> 

There's little difference between forking the crystal repo and the formatter

> * IMHO, that's not up to me of course, seeing [all the contributions done in the formatter](https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/tools/formatter.cr), @MakeNowJust could even be a maintainer of the repo (Thanks to him for his work :heart: )
> 

I'd strongly support having a maintainership system which allowed having many more maintainers with smaller responsibilities.

> * it can ease the reorganization of [formatter.cr](https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/tools/formatter.cr), which is a big file. The tree will be much less deep than from `crystal-lang/src/compiler/...`

That could be done now, but won't, because there's no benefit to splitting the file up.

**Comment by j8r** [comment]
@RX14 I don't see how it's easily possible, now, to have multiple formatters without ending up with multiple Crystal compilers in a same machine. If I want to fork the repo containing the formatter, it's `crystal-lang/crystal` – or did I miss something?

**Comment by Sija** [comment]
@j8r _multiple formatters_? what...?

**Comment by j8r** [comment]
Yes @Sija , the official one (inside the `crystal tool format` command) and the new custom one (which has unfortunately a compiler, a playground... :confused: )

**Comment by Sija** [comment]
what _custom one_? besides, what's the point? one of the main points of having the formatter is that it comes from the language authors and thus is in a way "blessed", unlike any other option from 3rd party.

**Comment by j8r** [comment]
That's quite common on the open-source world: forking, experimenting, developing, eventually contributing back (look at https://github.com/crystal-lang/crystal/network/members)

The main point of this is to ease contributions and maintenance:
- having other maintainers than only core members
- ease contributions by avoiding to setup all compiler's prerequisites
- better experience by having faster compilation and CI
- separate formatter RFCs with compiler/stdlibs RFCs (like https://github.com/rust-dev-tools/fmt-rfcs)

**Comment by RX14** [comment]
this is just the monorepo vs polyrepo debate, and monorepo always wins. It's not reasonable to move the formatter out of the crystal repo, because then all new PRs adding syntax need to go to two repos! It's a nightmare. It's never going to happen.

**Comment by j8r** [comment]
There is no mono/poly repo debate by including multiple repos inside one  – we have both.
Why will it be a nightmare? Formatting & a new language feature should be 2 separate PRs anyway.

**Comment by bcardiff** [comment]
Encouraging more contributors in the formatter can be done with a bit of documentation of the process needed and the formatter design.

An entry in the wiki sounds like a good starting point.
