### ISSUE TITLE
Crystal documentation master vs release

### ISSUE THREAD

**Issue by Indribell** [crystal-lang/crystal#7303]
When searching for "crystal mime", you end up on the page:

```
https://crystal-lang.org/api/master/MIME.html
```

Yet, when trying out:

```
require "mime"

MIME.from_extension(".html")         # => "text/html; charset=utf-8"
MIME.from_filename("path/file.html") # => "text/html; charset=utf-8"
```

You are presented with a error as:

```
in /home/Crystal/Shared/Service.cr:6: while requiring "mime": can't find file 'mime'

If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?

require "mime"
```

The issue is, that the https://crystal-lang.org/api/master/ direct to the latest development version of the documentation. And thus includes changes for Crystal 0.27.x or 0.28. As such, this can create confusion because new changes do not match with the stable released version ( namely 0.27.0 at this moment ).

This is the result of exposing the master branch onto Google and other search engines. This is a issue that needs to be addressed with some kind of information popup or a better way to deal with search engine redirects.

**Comment by straight-shoota** [comment]
I don't think it's a bad thing to publish the documentation from master and have it visible in search engine. We especially want this to be available, for example to read up on upcoming features.

The major problem is, that it is not labeled appropriately. So this is essentially #4754. The master docs should simply have a big sign that says something like "This is the documentation for nightly release (0.27.1-dev.2019-01-12)".

**Comment by ceckin6** [comment]
I am new, will I learn?
![s1466415465_4458](https://user-images.githubusercontent.com/50209992/57108784-716dd700-6d3c-11e9-8cb1-e1d40e1a3423.jpg)

**Comment by straight-shoota** [comment]
This issue can be closed. Searching for `crystal mime` points to https://crystal-lang.org/api/0.32.1/MIME.html which is latest atm, not master. The rest is tracked in #4754 and #7011
