### ISSUE TITLE
Proc return type expects exact signature

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#7306]
I'd expect that code below would work (since it matches one of the types from the union):

```cr
foo : Proc(String?) = -> { "foo" }
foo.call
```

but instead it fails with compiler error:

```
Error in line 1: type must be Proc((String | Nil)), not Proc(String)
```

**Comment by asterite** [comment]
Generally, this will never work. Imagine this case:

```crystal
foo : Proc(Int32 | String)
foo = some_proc
```

Let's say `some_proc` is a Proc that returns `Int32`. To make it work, the compiler has to cast the return value of the function to the union type, essentially putting it into something that's `{type_id, value}`. And for that the compiler will need to create a wrapper function, passing all the arguments, including the optional closure context, invoking it, and finally casting the value to the union type. It's possible, but it feels a bit hacky. And one can always do the same thing:

```crystal
foo : Proc(String?) = ->{ ->{ "foo" }.call.as(String?) }
foo.call
```

Now, if it's just allowing a proc **literal** to be assigned like that, maybe it can be done, but so far the compiler never uses the type you assign something to to infer other types.

**Comment by Sija** [comment]
@asterite thanks for the wrapper `Proc` idea, for the time being I'm using it as follows:

```cr
class Foo
  getter bar : Proc(String?)?

  # split block return types union into separate `Proc` signatures
  def bar=(block : Proc(String) | Proc(Nil))
    @bar = -> {
      block.call.as(String?)
    }
  end

  # define additional setter to allow clearing the ivar
  def bar=(block : Nil)
    @bar = nil
  end
end

foo = Foo.new
foo.bar = -> { "foobar" }
foo.bar = -> { nil }
foo.bar = nil
```

**Comment by jhass** [comment]
Sounds like this will be a won't fix. Closing?

**Comment by asterite** [comment]
Yeah, I don't think there's an easy way to make it work.
