### ISSUE TITLE
Type inference: returning based on #responds_to?(:some_method) does not allow calling obj.some_method later

### ISSUE THREAD

**Issue by maxfierke** [crystal-lang/crystal#7307]
I'm probably misunderstanding how type inference is supposed to work or can work, but it seems there _may_ be a bug or deficiency with inferring types based on method calls made.

## Code

```crystal
abstract class Project
  getter :hostname, :path

  def initialize(@hostname : String, @path : String)
  end
end

class ProjectWithUpstream < Project
  def nginx_upstream
    "hello"
  end
end

class AnotherProject < Project
end

class ProjectBootstrapper
  getter :project

  def initialize(project : Project)
    @project = project
  end

  def bootstrap
    setup_nginx_conf
  end

  private def setup_nginx_conf
    return unless project.responds_to?(:nginx_upstream)

    cmd(
      "brew",
      "setup-nginx-conf",
      "--extra-val=upstream=#{project.nginx_upstream}",
      project.hostname,
      project.path,
      "nginx.conf.erb"
    )
  end

  private def cmd(*args)
    pp! *args
  end
end


ProjectBootstrapper.new(ProjectWithUpstream.new("hello", "/path/to/thing")).bootstrap
```

# Expected

What I'm attempting to do is a provide a class that accepts all sub-classes of an abstract class `Project`, with some special handling if one of the classes responds to a particular method, `nginx_upstream`. I'm expecting that it will compile fine and do the right thing based on the particular instance of `project` and whether it implements the method.

# Actual

It throws a compile error when the method is called _after_ it has been checked and confirmed that the object responds to the method.

```
Error in line 47: instantiating 'ProjectBootstrapper#bootstrap()'

in line 25: instantiating 'setup_nginx_conf()'

in line 34: undefined method 'nginx_upstream' for AnotherProject (compile-time type is Project+)
```

## Playground Link

* https://play.crystal-lang.org/#/r/5zje

I may try to take a look at this once I find a suitable workaround for my app, but it seems like we could be checking the type inferred for object `project`, then typing `project` for the remainder of the method as the union of all the subclasses of `Project` that implement an `nginx_upstream` method?

**Comment by asterite** [comment]
`responds_to?` only restricts the type of **local variables**: https://crystal-lang.org/reference/syntax_and_semantics/if_varresponds_to.html

You must do something like:

```crystal
project = @project # or project = self.project
return unless project.responds_to?(...)
```

**Comment by maxfierke** [comment]
🤦‍♂️  whoops. Thanks!

That does seem to fix it for the playground code, though I'm still having the same problem with my actual code. Both are on Crystal 0.27.0. I'll do some more digging.

**Comment by asterite** [comment]
You mean, the code you posted above?

**Comment by maxfierke** [comment]
That's an example I simplified for brevity. The actual code is pretty close, but is split across several files. I'll see if I can produce another example that hits the problem on the playground.

**Comment by maxfierke** [comment]
I'm going to close this, because I haven't able to get a re-producible test case working, and managed to workaround the problem.
