### ISSUE TITLE
Lazy getter macros doesn't work with Bool

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#7312]
Since `||=` operator invokes rhs on `nil` **and** `false`, using it inside `getter` macro with `Bool` type will execute lazy block whenever the value is `false` - which I'd say is incorrect behavior since lazy initialization should happen only for `nil` values.

```cr
class Foo
  getter(bar : Bool) { puts "Foo#bar executed"; false }
end

foo = Foo.new
foo.bar # prints "Foo#bar executed"
foo.bar # prints "Foo#bar executed" again
```

Should the implementation be changed to check for `.nil?` instead of using `||=`?

**Comment by asterite** [comment]
Yes
