### ISSUE TITLE
Suggestion: implicit Symbol -> String cast

### ISSUE THREAD

**Issue by stronny** [crystal-lang/crystal#7315]
I find symbols very useful, but I have to constantly overload all my functions just to `.to_s` a parameter or use union types which are more verbose and less clear both for the user and the compiler. Would it be possible to call `Symbol#to_s` implicitely and pass it as a String if no other overloads match?

```
def a(x : String) : Nil; p x end
a "test"
a :test
### REAL OUTPUT
Error in line 3: no overload matches 'a' with type Symbol
Overloads are:
 - a(x : String)
### PROPOSED OUTPUT
"test"
"test"
```

**Comment by bew** [comment]
Why use a symbol instead of a string?

**Comment by stronny** [comment]
Why wouldn't I? Strings represent data in general, symbols represent names in particular. They use a nifty syntax, highlighted differently, however they are immutable strings. If I get a free-from JSON, where all keys are strings, why wouldn't I use symbols?

```
drake disapproves | universe["milky_way"]["sol"]["earth"]
drake    approves | universe[:milky_way][:sol][:earth]
```

**Comment by RX14** [comment]
strings are also immutable, and are more general than symbols.

Anyway, this isn't going to be implemented, because it's too implicit for very little gain.

**Comment by stronny** [comment]
I accept your judgement, however let me say a few things.

* Mutability is irrelevant here, take the word "immutable" away and nothing changes.
* The fact that strings are more general is precisely my point. The whole idea of types is that you specify them further and further to lose generality, but keep an interface to safely up- and downcast as appropriate. An unstructured heap is the most general "type", but I don't think this is a wise argument for anything.
* Why do you even have symbols in Crystal? Just because Ruby has them too?
* Once you release 1.0 it would be impossible to do in a backwords compatible way.
* "explicit > implicit" is the Python mantra, Ruby traditions are more like "convention > configuration" afaiu.
* C++ abuses implicit decisions to a ridiculous extent, but that's not a good reason to avoid some that make sense.
* As for the gain, I understand that I only represent my own opinion (which goes against the consensus here apparently), but I will continue to use symbols for strings that are names, I'll just have to type more boilerplate code. Um, the gain would be less boilerplate code is what I'm saying.
* Finally, I fail to see how that would break anything or impact anyone in a negative way. Symbols are strings. If one needs to make a distinction, an overload or an `is_a?` check would solve this just like it does now.

**Comment by asterite** [comment]
Well, comparing symbols is just comparing an integer, while comparing strings first checks for reference equality (I think?) and then content, which isn't as fast. So there's that. But enums can be used instead of symbols and they are also type-safe.

**Comment by stronny** [comment]
Right. Well, thanks for your time.
