### ISSUE TITLE
Add a purpose for block variants of  (class_)getter? macros

### ISSUE THREAD

**Issue by j8r** [crystal-lang/crystal#7321]
Block variants of `(class_)getter?` macros aren't useful as is, because the block is never executed. I was thinking of using this macros to run the block once on the first method call. Then, this method will return the value of the internal variable, which is nillable.
Something like:
```cr
struct A
  @@var : String? = nil
  @@var_initialized : Bool = false

  def self.var : String?
    if !@@var_initialized
      @@var = puts "initializing variable"
      @@var_initialized = true
    end
    @@var  
  end
end
A.var    # initializing variable
p! A.var # A.var # => nil

```
The idea is the same with `getter? {}`. The `var_initialized` boolean can be a `__temp` variable generated by the macro.

**Comment by Sija** [comment]
Well, they need to support blocks in the same way as `(class_)getter` macro does.

**Comment by Sija** [comment]
I vote to close, use cases for such behavior are extremely rare, if any (never seen a single one), so anyone with a real need can write such macro, or more likely, code it explicitly inside the method.

@j8r FYI, using nilable types for block variants of `getter/property` macros is not supported ATM, whether `?` suffixed or not. `?` in this case refers to _query-ing_ behaviour (returning `Bool`), **not** nilable (returning `T | Nil`).

**Comment by j8r** [comment]
Ok. It remains a convention @Sija. Would it be wise to enforce it?

**Comment by Sija** [comment]
You could raise in case of `TypeDeclaration` but I'm not sure how would you sensibly enforce it for block, `.as()`? meh... Also, I don't think it's worth the hassle.
