### ISSUE TITLE
Confusing error when assigning variable to constant

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#7324]
```cr
variable = 1

CONSTANT = variable

CONSTANT
```
```
Error in line 3: undefined local variable or method 'variable'
```
This error is quite confusing. The `variable` is defined before line 3. I feel like this error can be improved.

**Comment by RX14** [comment]
The error message might be able to be improved if there's a top-level local variable in scope but it might be difficult, @asterite would know.
