### ISSUE TITLE
Not possible to add another key & value after heredoc in named tuple

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#7327]
This:
```cr
{
  key1: 123,
  key2: <<-HERE
        here
        HERE
}
```
compiles.

---

But now what if I want to add another key and value?
I will try this:
```cr
{
  key1: 123,
  key2: <<-HERE
        here
        HERE,
  key3: 123
}
```
But it gives:
```
Syntax error in cr.cr:7: Unterminated heredoc: can't find "HERE" anywhere before the end of file
```
Unfortunately it is somehow not possible to put a comma after `HERE`. I really think it should be made possible.

---

And this doesn't work either:
```cr
{
  key1: 123,
  key2: <<-HERE
        here
        HERE
  ,key3: 123
}
```
```
Syntax error in cr.cr:6: expecting token '}', not ','
```

I honestly don't see any way here to add anything else after the heredoc. Am I missing something? 

Hash has the same problem.

For now I will use `%()` and normal strings but the code looks *very* ugly.

**Comment by asterite** [comment]
You have to put the comma after the first HERE

**Comment by r00ster91** [comment]
Oh... that looks a bit confusing. For me, putting it after the last `HERE` would look much more logical. Just like how I would put the comma at the end of:
```cr
"
here
"
```
I think this should be documented at least then in https://crystal-lang.org/reference/syntax_and_semantics/literals/string.html#heredoc.

**Comment by asterite** [comment]
I think it was like that before, but that's not how it works in Ruby so we eventually did it like Ruby. Ruby's way is a bit more flexible and consistent.

**Comment by ysbaddaden** [comment]
Just saying: I like Swift's `"""` syntax for multiline strings, which is more intuitive than heredoc:
https://github.com/apple/swift-evolution/blob/master/proposals/0168-multi-line-string-literals.md

**Comment by r00ster91** [comment]
I think GitHub's ` ``` ` which we use all the time to highlight code would also be an option.
