### ISSUE TITLE
Array.from_json fails to parse int and float in the same object

### ISSUE THREAD

**Issue by ArtLinkov** [crystal-lang/crystal#7333]
If the JSON string includes an Array with both Int and Float, the parser converts all the numbers to Float.
```Crystal
require "json"
str = "[1, 2.0, \"a\"]"
p Array(Int32 | Float64 | String).from_json(str)

>> Output: [1.0, 2.0, "a"]
```
##
Side note: The from_yaml methods works fine
```Crystal
require "yaml"
str = "[1, 2.0, \"a\"]"
p Array(Int32 | Float64 | String).from_yaml(str)

>> Output: [1, 2.0, "a"]

**Comment by asterite** [comment]
The current implementation traverses all types in the union and returns the first value that could be parsed. The types are always sorted alphabetically, so `Float64` comes before `Int32` and that succeeds.

The solution is to special case this: if there's an `Int` and `Float`, try `Int` first.

That said, in the general case where using two conflicting types it's not guaranteed which one will be parsed.

**Comment by sevk** [comment]
```
In JSON, values must be one of the following data types:

a string
a number
an object (JSON object)
an array
a boolean
null
```
[https://www.w3schools.com/js/js_json_datatypes.asp](url)

**Comment by straight-shoota** [comment]
That's because `1` is not a valid float in YAML, thus it falls through to parse as `Int32`.

**Comment by straight-shoota** [comment]
Or, well, that's actually not entirely true.

The YAML 1.1 [float type](https://yaml.org/type/float.html) expects values to include a decimal point or be `0` (or infinity, NaN or in radians).
According to the YAML 1.2 JSON Schema, [floating point values](https://yaml.org/spec/1.2/spec.html#id2804092) *can* be plain integers without a decimal point.
*But* unless explicitly tagged as `float`, scalars that represent an integer number should be typed as `int` (see [Tag Resolution](https://yaml.org/spec/1.2/spec.html#id2804356)).

The YAML parser works accordingly:
```cr
Float64.from_yaml("!!float 1") # => 1.0
Float64.from_yaml("1") # raises YAML::ParseException: Expected Float64, not 1
```

**Comment by straight-shoota** [comment]
JSON on the other hand has only a single number type which does not distinguish between int and float. Thus `1` in JSON parses as a number which can be represented in Crystal as both `Int32` or `Float64` and the latter wins because of lexical ordering.

**Comment by KimBurgess** [comment]
It worth noting that this applies to any values parsed into a union type. The forced lexical ordering results in [this iteration](https://github.com/crystal-lang/crystal/blob/41bd18fbea4aec50aad33aa3beb7a0bf30544186/src/json/from_json.cr#L234-L247) preferencing primitive types in alphabetic order.

If using `JSON::Serializable` a custom converter can be specified that overrides this, but as a more general solution is there ability to preserve the order of types that form a union? This would enable this preference to be encoded as part of the type declaration.

```crystal
alias U = Float64 | Int64
alias V = Int64 | Float64

U.from_json "1"
# => 1.0

V.from_json "1"
# => 1
```

**Comment by straight-shoota** [comment]
> is there ability to preserve the order of types that form a union?

No. A union is an unordered set. In the type grammar, `Foo | Bar` is identical to `Bar | Foo`.

Using `Union.from_json` is a convenience method that should work in many simple use cases, but if you need something else, I'm afraid you'll have to write a custom converter. We could consider adding some kind of helper method for this where you just need to specify the types in order and the implementation is automatically provided. But I'm not sure it's an important enough use case. Sometimes you might need some very specific logic anyway, which means a custom implementation is unavoidable.

**Comment by KimBurgess** [comment]
I've popped together an implementation for this under #8675. This should assist with this scenario when using `JSON.mapping` or the `JSON::Serializable` module and associated annotations. If it's not a common enough issue for inclusion here, please feel free to close and I can spin it out into a shard for inclusion as required.

**Comment by asterite** [comment]
@ArtLinkov What's the use case here? Can you point us to an API where ints and floats are mixed and you'd like to parse them while making such distinction?

**Comment by ArtLinkov** [comment]
Hmm... I can't think of anything specific off the top of my head. I was just playing around with the JSON parser when I stumbled upon this behavior.
