### ISSUE TITLE
Named arguments do not create an additional overload

### ISSUE THREAD

**Issue by dscottboggs** [crystal-lang/crystal#7337]
I was under the impression this was a design decision until @bew pointed out in the chat that this is actually a bug:

```crystal
require "spec"

describe Klass do
  it "responds to named argument" do
    Klass.new.method(named: "value").should eq "value"
  end
  it "responds to other_named argument" do
    Klass.new.method(other_named: "value").should eq "value"
  end
end

class Klass
  def method(named arg)
    arg
  end
  def method(other_named arg)
    arg
  end
end
```
([playground](https://carc.in/#/r/63e1))

After experimenting a bit, I discovered this also happens with *any* named arguments, not just ones with an external name, regardless of whether or not they have a type restriction. So this fails to compile as well (given the above specs):

```crystal
class Klass
  def method(named : String)
    named
  end
  def method(other_named : String)
    other_named
  end
end
```
([playground](https://carc.in/#/r/63e2))

**Comment by asterite** [comment]
This works as expected. In your examples you are using positional arguments. They can be passed as named arguments, but the second signature overrides the previous one.

If you want to have something like that you must use required named arguments. These come after a `*`:

```crystal
require "spec"

describe Klass do
  it "responds to named argument" do
    Klass.new.method(named: "value").should eq "value"
  end
  it "responds to other_named argument" do
    Klass.new.method(other_named: "value").should eq "value"
  end
end

class Klass
  def method(*, named arg)
    arg
  end
  def method(*, other_named arg)
    arg
  end
end
```

[Playground link](https://carc.in/#/r/63fh)

**Comment by bew** [comment]
Was about to reply that, looks like I should not respond to gitter when sleeping :zzz:

**Comment by dscottboggs** [comment]
Oh that makes perfect sense, idk why I didn't think of that. Thanks for your help @asterite
