### ISSUE TITLE
Undefined method `new` for Klass // undefined local variable or method 'new'

### ISSUE THREAD

**Issue by dscottboggs** [crystal-lang/crystal#7349]
Using a class with an initializer defined results in the above errors:

```crystal
class Klass
  def initialize;end
  def clone
    new
  end
end
# Error in line 9: instantiating 'Klass#clone()'
# 
# in line 4: undefined local variable or method 'new'


# OR

class Klass
  def initialize;end
  def clone
    self.new
  end
end

# Error in line 9: instantiating 'Klass#clone()'
# 
# in line 4: undefined method 'new' for Klass
```

But those methods are defined by `#initialize`, no?

In fact, even if you define `new` manually, [the same error](https://play.crystal-lang.org/#/r/64s5) still occurs!

```crystal
class Klass
  def self.new
    instance = allocate
    instance.initialize
    instance
  end
  def initialize;end
  def clone
    self.new
  end
end
```

**Comment by dscottboggs** [comment]
Crystal 0.27.0 fwiw

**Comment by ysbaddaden** [comment]
There is no Klass#new instance method but a Klass.new class method. You must either call Klass.new or self.class.new to refer to the class.

`self` is the current instance in methods, but the current class inside the class body, so `def self.new` creates a class methods.

Please ask support questions on the forum, thanks :)

**Comment by dscottboggs** [comment]
Ok, sorry to bother.
