### ISSUE TITLE
GPG failure on fedora

### ISSUE THREAD

**Issue by waghanza** [crystal-lang/crystal#7360]
Hi,

I'm trying to install `crystal` on a newly installed `fedora`.

-  LSB Version:    :core-4.1-amd64:core-4.1-noarch
-  Distributor ID: Fedora
-  Description:    Fedora release 28 (Twenty Eight)
-  Release:        28
-  Codename:       TwentyEight

I've done `curl https://dist.crystal-lang.org/rpm/setup.sh | bash`

While installing with `dnf install crystal`, I've :

~~~
warning: /var/cache/dnf/crystal-3bd2d0b9f4c02d18/packages/crystal-0.27.1-1.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 67697dd2: NOKEY
Public key for crystal-0.27.1-1.x86_64.rpm is not installed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
~~~

Regards,

**Comment by bcardiff** [comment]
Hi @waghanza , thanks for reporting and apologies for the inconvenience.
You should be able to install latest crystal now. You might need to clean the cache (and I am not sure how to clean the minimum part).
 
```
$ sudo dnf clean all
$ sudo dnf install crystal
```
