### ISSUE TITLE
Crystal 0.27.1 built with --release crashes immediately with OverflowError

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/crystal#7368]
If I compile 0.27.1 (or master) with `--release -Dpreview_overflow`, then I can't compile anything anymore, not even Crystal itself. The compiler crashes *immediately*:

```
$ make -B
CRYSTAL_CONFIG_BUILD_COMMIT="0ef090a" ./bin/crystal build -D preview_overflow -D compiler_rt --release  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
Using compiled compiler at `.build/crystal'
Unhandled exception: Overflow (OverflowError)
Failed to raise an exception: END_OF_STACK
[0xd30ca6] ???
[0x417cfb] __crystal_raise +43
[0x429963] ???
[0x422979] ???
[0x41f388] ???
[0x4522bd] ???
[0x41bdbd] main +45
[0x2acaf91c0f45] __libc_start_main +245
[0x41416f] ???
[0x0] ???
make: *** [.build/crystal] Erreur 5
```

Note that I can build a working compiler with `-Dpreview_overflow` only (without `--release`).

All my Travis jobs are currently broken, since the Linux packages of 0.27.1 have been built with these options.

OS: Ubuntu 14.04
Target: x86_64-linux-gnu

**Comment by ysbaddaden** [comment]
When I say "immediately" I mean it: if I pass `--stats` then I don't get anything printed.

**Comment by ysbaddaden** [comment]
@oprypin this should be fixed by #7373.

**Comment by ysbaddaden** [comment]
This is an unfortunate course of events. An unexpected bogus value with RLIMIT_STACK on Linux when run inside `make` led to an integer overflow in Fiber.new (main thread's main fiber). In addition, the Crystal Makefile already turns on the integer overflow checks.

Weirdly, it affects a simple hello world program, but doesn't affect the compiler built in non-release mode. It only affects the compiler when built with `make release=1`, which cause the compiler to crash immediately, also leading to the `END_OF_STACK` —maybe because the crystal runtime isn't fully initialized.

That could have been found out sooner, but compiling crystal in release mode takes a long time, so I usually only use a manually built compiler in non-release mode —I guess nightly does the same?

**Comment by bcardiff** [comment]
@oprypin catching before release today is only available as docker images which none of those projects use unfortunately.

As @ysbaddaden pointed, checks in nightly can be be improved. The compiler used during the specs is not built in release mode, and the distributable which is compiled in release mode is not actually used.

**Comment by bcardiff** [comment]
Using the compiled packages to run specs would have caught #7289 also.
