### ISSUE TITLE
"Unhandled exception in spawn: Error writing to socket: Broken pipe (Errno)" in socket client specs

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#7401]
If you put a `1000.times do` around all socket client specs this is easy to reproduce. I won't have time these days to find out why it happens, but if somebody has the time, please investigate it.

With that and my other researches we should be reaching a point where no specs will fail on CI.

**Comment by straight-shoota** [comment]
This should probably be fixed by #7197
