### ISSUE TITLE
Error parsing cookies

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#7404]
```crystal
require "http"

require "http/server"

server = HTTP::Server.new do |context|
  context.response.content_type = "text/plain"
  context.response.print "Hello world!"
  context.response.headers["Set-Cookie"] = "my_cookie=; expires=Tue, 12-Oct-1999 07:00:00 GMT; path=/; secure; HttpOnly"
end

address = server.bind_tcp 5050
puts "Listening on http://#{address}"
spawn server.listen

response = HTTP::Client.get "http://localhost:5050/"

response.cookies

server.close
```

Cookie will show no `secure` or `http_only` (both false)
Also, example by @Blacksmoke16 : https://play.crystal-lang.org/#/r/67na

This is a standard set-cookie header coming from IIS.

**Comment by Sija** [comment]
It’s because of incorrect date format passed for _expires_ key (`12-Oct-1999` should be `12 Oct 1999`) as per https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Date.

Perhaps cookie regex parser could be changed to accept it, yet it’s clearly not a standard compliant format.

**Comment by Sija** [comment]
M$ of course has a different opinion on the subject, see https://docs.microsoft.com/en-us/windows/desktop/wininet/http-cookies#set-cookie-header
