### ISSUE TITLE
`next`'s return value ignored for block without input and output types specified

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#7410]
```crystal
def method(&block)
  block.call
end

one = method do
  next 1
end

one # => nil
```
Why doesn't this return `1`? The `next` itself does work and exits the block but the parameter (`1`) is ignored and not returned.

But now when doing this (specifying the input and output types):
```crystal
def method(&block : Int32 -> Int32)
  block.call(1)
end

one = method do |one|
  next one
end

one # => 1
```
It returns `1`.

And this works too:
```crystal
def method
  yield
end

one = method do
  next 1
end

one # => 1
```

**Comment by asterite** [comment]
Because `&block` for captured blocks means no arguments and nil return type.

**Comment by r00ster91** [comment]
Oh I thought the input and output types would maybe be inferenced by the compiler so in the first example `&block` automatically gets changed to `&block : Int32 -> Int32`.
