### ISSUE TITLE
Crystal version in Alpine Linux edge not up to date

### ISSUE THREAD

**Issue by carlhoerberg** [crystal-lang/crystal#7411]
@jirutka can I help provide latest version of Crystal to the Alpine package repository somehow: 

https://pkgs.alpinelinux.org/package/edge/community/x86_64/crystal

Current package versions is 0.27.0 while latest crystal as of writing is 0.27.2

**Comment by straight-shoota** [comment]
This is not strictly a Crystal issue because Alpine packages are provided by the community. But I'd really like to give Alpine more love, given that it's the only platform to build static Crystal binaries. Maybe we could provide official releases for Alpine like we provide apt and rpm packages?

**Comment by j8r** [comment]
I don't think it's worth it to package it, Alpine Edge is usually up to date relatively fast.
However, having an Alpine CI will help a lot to ship the latest Crystal release to edge without having to create patches.
Related to https://github.com/crystal-lang/crystal/issues/6943

**Comment by carlhoerberg** [comment]
@j8r Well, it's edge that is at 0.27.0. 0.27.1 has been out over a month and 0.27.2 over a week. Edge doesn't seem to be updated that fast after all. I'm not here to complain though, just wonder how I can help to get it up to date; where and how to update the package. As yes, we use Alpine to build static builds.

**Comment by ysbaddaden** [comment]
Please flag the package on https://pkgs.alpinelinux.org or ping package maintainer or send alpine a patch to update the version.

We don't have any control over it ourselves.
