### ISSUE TITLE
Installation/update of 0.27.2 fails on CentOS7

### ISSUE THREAD

**Issue by lebogan** [crystal-lang/crystal#7421]
Installing .27.0 from a local .rpm works. Fresh install or upgrade of .27.1 and .27.2 fails with the following:
...
Marking ./crystal-0.27.2-1.x86_64.rpm to be installed
Resolving Dependencies
Dependencies Resolved
Installing:
 crystal       x86_64       0.27.2-1       /crystal-0.27.2-1.x86_64       175 M
...
Transaction Summary
...
Running transaction
  Installing : crystal-0.27.2-1.x86_64                                      1/1 
error: unpacking of archive failed on file /usr/share/crystal/src/lib_c/amd64-unknown-openbsd: cpio: rename
...
Failed:
  crystal.x86_64 0:0.27.2-1  
                                                   
Platform:
CentOS Linux release 7.6.1810 (core)
LLVM 4.0.0

**Comment by forksaber** [comment]
I also encountered this issue. The reason why upgrade fails is that uninstalling `crystal-0.27.*` rpm doesn't clean up a lot of directories in `/usr/share/crystal/src`. 
A temporary workaround is to manually remove `/usr/share/crystal/src` dir after uninstalling `crystal`.

**Comment by lebogan** [comment]
Thanks @forksaber .

**Comment by cvoltz** [comment]
The issue is marked closed but the issue still occurs with 0.28.0-1 so I think it should be reopened. I don't see the .spec file in the repository so I can't provide a patch but, as with any RPM, any files installed by the RPM should be removed when it is removed.

**Comment by bcardiff** [comment]
Tracked in https://github.com/crystal-lang/distribution-scripts/issues/34 if someone can double check if the options mentioned there solves the issue it would be great.
