### ISSUE TITLE
TcpServer specs failure on Ubuntu 18.10

### ISSUE THREAD

**Issue by yxhuvud** [crystal-lang/crystal#7422]
On clean master branch: 

Running 
`make clean && make && make spec`
consistently fails (for both ipv4 and ipv6), at 
`spec/std/socket/tcp_server_spec.cr:51` with the following error:

```
  1) TCPServer .new using IPv4 reuse_port raises when not binding with reuse_port
     Failure/Error: expect_raises_errno(Errno::EADDRINUSE, {% if flag?(:linux) %}"listen: "{% else %}"bind: "{% end %}) do

       Expected Errno with "listen: ", got #<Errno: bind: Address already in use> with backtrace:
         # /usr/share/crystal/src/socket/tcp_server.cr:73:15 in 'initialize:reuse_port'
         # /usr/share/crystal/src/socket/tcp_server.cr:32:3 in 'new:reuse_port'

```

Versions: 
System Crystal: Crystal 0.27.2 [60760a546] (2019-02-05)
Ubuntu 18.10
LLVM: 4.0.0
libc: 2.28-0ubuntu1

Looking at the spec, it would pass if not checking for `listen`, but for `bind` instead, but the code special cases linux to look for `listen`, and the spec changed somewhat recently, so the behaviour is probably intentional (though failing, which it obviously shouldn't).

**Comment by Sija** [comment]
I'm curious why it needs to check for exception message at all, shouldn't `Errno::EADDRINUSE` be enough?

**Comment by straight-shoota** [comment]
`EADDRINUSE` is not very precise. It still makes a difference if bind or listen fails. I'm not sure if that's worth keeping at all costs, but until now it didn't show any issues. Eventually, we want to move away from generic `Errno` exceptions anyway towards more specific exception classes, at which point this distinction vanishes anyway.

That aside, it's weird that Ubuntu 18.10 would already fail at `bind`. I'm pretty sure that this spec passed up to 18.10.

**Comment by yxhuvud** [comment]
Could there be anything else that is triggering the issue?

**Comment by straight-shoota** [comment]
This spec already fails in bionic 18.04. I did not yet check atomic 17.10.

I guess we should expect either `bind` or `listen` - at least for `gnu`.

**Comment by asterite** [comment]
Can't we just check the exception type and not bother about the message, which is out of our control? (we don't generate it)

**Comment by straight-shoota** [comment]
Yeah, I suppose we can simply remove the message validation, despite what I wrote in https://github.com/crystal-lang/crystal/pull/7484#issue-256473500 It probably doesn't really matter whether it fails at `bind` or `listen`.

I'm still curious why and when glibc changed its behaviour, though. It seems they're now doing the same as everyone else.

**Comment by renich** [comment]
BTW, it fails on Fedora 31 as well.
