### ISSUE TITLE
Hash#bucket_index fails because hash returns nil

### ISSUE THREAD

**Issue by masukomi** [crystal-lang/crystal#7430]
error 

```
in /usr/local/Cellar/crystal/0.27.2/src/hash.cr:1047: undefined method 'remainder' for Nil (compile-time type is (String | Nil))

    key.hash.remainder(@buckets_size).to_i

```

i think that `hash` method is defined as this in `Object`

```
  def hash
    crystal_type_id
  end
```

and `crystal_type_id` returns an Int32

```
src/primitives.cr
32:  def crystal_type_id : Int32
```

i feel like 
a) the expected compile type is probably wrong and 
b) hash should never return `nil` so this this shouldn't happen in the first place.

Encountered under this crystal: 

```
Crystal 0.27.2 (2019-02-05)

LLVM: 6.0.1
Default target: x86_64-apple-macosx
```

**Comment by Sija** [comment]
Could you please post the offending code?

**Comment by asterite** [comment]
Closing because there's no code that reproduces this.

@masukomi Please reopen if you have that code. Thank you!
