### ISSUE TITLE
keyword as string name allowed or not ?

### ISSUE THREAD

**Issue by jt500** [crystal-lang/crystal#7432]
This code with keyword "union" compiles fine :

text = "Hello"
union = "#{text} world"
puts union

but with "select" keyword this code :

select = "#{text} world"
puts select

gives "Syntax error in eval:5: unexpected token: = (expecting when, else or end)"

(Crystal 0.27.2)

**Comment by asterite** [comment]
union can only appear in lib, so here there's no conflict. select can appear anywhere. Please use the forum for questions. Thank you!
