### ISSUE TITLE
Missing Regex::Options::UNGREEDY

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#7437]
Is it intentional omission or sth that just wasn't implemented?
If so, I'd like to take a stab at it.

**Comment by Sija** [comment]
@asterite 🏓

**Comment by asterite** [comment]
Sorry, I have no idea what that means.

**Comment by Sija** [comment]
@asterite `UNGREEDY` is one of the options provided by PCRE library used by Crystal's `Regex` class:

> PCRE_UNGREEDY
>
>        This  option  inverts  the "greediness" of the quantifiers so that they
>        are not greedy by default, but become greedy if followed by "?". It  is
>        not  compatible  with Perl. It can also be set by a (?U) option setting
>        within the pattern.

**Comment by asterite** [comment]
Why is this needed/useful? Can't the regex you need be written with the appropriate greediness instead of writing it in the opposite one and then inverting it?

I can't see this exists in Ruby so it's a sign that it's probably not needed.

**Comment by Sija** [comment]
It's just easier to set a flag instead of doin' that for every quantifier but I guess it's acceptable as-is, fair 'nuff.
