### ISSUE TITLE
Unify Time::Span and Time::MonthSpan

### ISSUE THREAD

**Issue by anykeyh** [crystal-lang/crystal#7451]
This Issue is related to:
https://forum.crystal-lang.org/t/time-span-and-time-monthspan/430

# Current implementation

Crystal offers method à-la active-support for dealing with advance an rewind in time, for example:

```crystal
tomorrow = Time.now + 1.day
last_month = 1.month.ago
```

Theses methods rely on `Time::Span` and `Time::MonthSpan`. The current implementation is not unified, therefore:

```crystal
time_span = 1.month + 1.day # Throw compile time error because we can't add Time::MonthSpan with Time::Span 
```

# The problem

It has been done like this because months and days are treated differently, therefore, add a month THEN a day is not the same than add a day THEN a month:

```crystal
puts Time.new(2018,1,28) + 1.month + 1.day
# > 2018-03-01 00:00:00 +07:00
puts Time.new(2018,1,28) + 1.day + 1.month
# > 2018-02-28 00:00:00 +07:00
```

# Unification

In Active Support, the type is unified by stacking the parts of the transformations in an Array like this:

```ruby
(1.day + 1.month + 1.day).parts
# => [[:days, 1], [:months, 1], [:days, 1]]
```

The goal here would be to rewrite the Time::Span and Time::MonthSpan to handle it like Active Support, and allow to store and combine directly months and days.

After the rewriting, it would be possible to do:

```crystal
struct MyStruct
  @duration : Time::Span

  def initialize(@duration)
  end
end

MyStruct.new(1.month + 1.day) #< Currently impossible.
```

## Caveats

Current Time::Span offers methods which doesn't exists in Time::MonthSpan.

### Like PG's Intervals

I let you discuss about the best way to do it. In PostgreSQL, the type interval apply the month followed by the days as example below:

```sql
SELECT DATE('2018-01-28') + INTERVAL '1 day 1 month';
-- 2018-03-01 00:00:00

SELECT DATE('2018-01-28') + INTERVAL '1 month 1 day';
-- 2018-03-01 00:00:00
```

Pro:
Performance-wise, it stores only the month, day and microseconds in a fixed-length structure (16 bytes)

Cons:
- Some methods of Time::Span are non-sensical in the new implementation and should be removed (?) (total_days etc...)
- This would cause a problem when applying transformation from left to right:

```crystal
Time.new(2018,1,28) + (1.day + 1.month) != Time.new(2018,1,28) + 1.day + 1.month
```

### Like ActiveSupport

Pro:
Apply the transformation in the proper order. Can be tweaked to be optimized slightly (e.g. 1.day + 1.month + 1.month become 1.day + 2.month transformation).

Cons:
It stores the data in an array of transformations, so the `Time::Span` become a non-fixed size class. Applying transformation is also slower and passing by reference cannot be used.

### 3 Classes (The one I prefer)
Keep `Time::Span` and `Time::MonthSpan`, but offer another 3rd object type when combining `Time::Span` with `Time::MonthSpan`, which act like ActiveSupport (array under the hood).

Pro:
Keep the pro of the previous implementations ideas but should perform slightly better.

Cons:
More error-prone, more complex. 

If the core team agree with the feature, I would be glad to deal with my first PR :+1:  ^^

**Comment by straight-shoota** [comment]
This is essentially already tracked in #6522.
