### ISSUE TITLE
Double buffering in OpenSSL::SSL::Socket

### ISSUE THREAD

**Issue by carlhoerberg** [crystal-lang/crystal#7458]
This seems like a contradiction: 

https://github.com/crystal-lang/crystal/blob/c9d1eef8fde5c7a03a029d64c8483ed7b4f2fe86/src/openssl/ssl/socket.cr#L87-L92

I suspect it should be `io.sync = true`?

**Comment by straight-shoota** [comment]
Looking at the git blame shows that this code was introduced relatively recently in #6590 and that PR adds some background information.

**Comment by carlhoerberg** [comment]
I don't see how it explains that there's a contradictory comment above a statement, `io.sync = true` enables write buffering, we should want to disable it. 

If OpenSSL::SSL::Socket does buffering, or if OpenSSL it self does buffering, or neither, the underlying TCP socket should not have any buffering either way.

I'm pretty convinced that #6590 introduced a mistake and that line 90 should read `io.sync = true`. 

It also solves #7456

**Comment by asterite** [comment]
We should probably rename `sync` to `write_buffering`. It would be so much more obvious to understand what's going on.

**Comment by carlhoerberg** [comment]
@asterite i agree
