### ISSUE TITLE
Cannot create explicitly `public` property

### ISSUE THREAD

**Issue by anicholson** [crystal-lang/crystal#7459]
Given this code:

```crystal
class Example
  public property foo : String?
end

e = Example.new
e.foo = "bar"

```

Expected: code compiles and runs with no errors
Actual:

```
Error in example.cr:2: expanding macro

  public property foo : String?
         ^

in macro 'property' expanded macro: macro_94363156575440:567, line 6:

   1.       
   2.         
   3.           
   4.             @foo : String | ::Nil
   5. 
>  6.             def foo : String | ::Nil
   7.               @foo
   8.             end
   9. 
  10.             def foo=(@foo : String | ::Nil)
  11.             end
  12.           
  13.         
  14.       
  15.     

can't declare def dynamically

```

I found this quite surprising, as I expected `public` to work with `property` the same way `private` does. If explicitly tagging things as `public` is not considered idiomatic, then a compiler warning would be good. But it shouldn't break cryptically like this.

## Meta
```
$ crystal --version
Crystal 0.27.0 (2018-11-02)

LLVM: 6.0.1
Default target: x86_64-pc-linux-gnu

```

**Comment by asterite** [comment]
Things are public by default. I'm not sure this is needed, specially because you can't do `private` and let all the following declarations take that visibility.

**Comment by anicholson** [comment]
@asterite:

What about this scenario, where the author wishes to open up visibility?

```crystal
class Example
  private property foo : String?
end

class Derived < Example
  public property foo : String?
end

e = Derived.new

e.foo = "Foo"
```

As I said in the initial post, I'm happy for the Crystal team to declare that unidiomatic, but if the `public` keyword exists, then it should be supported properly by core language macros (even if that support includes a "don't do this" warning). Otherwise, why is the `public` keyword even needed?

**Comment by asterite** [comment]
The above example works fine if you remove the `public` call from there (the property becomes public).

Also, `public` is not a keyword.

**Comment by anicholson** [comment]
> The above example works fine if you remove the `public` call.

I know it does :)

> Also, `public` is not a keyword.

The docs say it is, though: https://crystal-lang.org/reference/syntax_and_semantics/visibility.html

> Methods are public by default: the compiler will always let you invoke them, even if there is no `public` keyword.

My question isn't about whether one should use it or not. If it has no purpose, why is it there? And if I want to use it to make my code more explicit, why should I be forbidden?

**Comment by z64** [comment]
I'm pretty sure those docs are meant to say "even if there is no public keyword" to mean that there *is no public keyword in the language*. This can probably be improved.

You get this same compiler error with this code:

```cr
foo def test
end
```
https://carc.in/#/r/6b4p

This is because the compiler sees `foo` as some kind of method call, and thinks you want to define `test` inside of a call to `foo`, which may or may not be defined yet (the compiler doesn't know, but either way it isn't possible)

**Comment by asterite** [comment]
Yes, the docs say "even if there is no `public` keyword" because there's no `public` keyword. It looks like a keyword, but every call/macro can be seen as a keyword in Crystal and Ruby (this is one of the main beauties about Ruby). 

Also, you can implement the `public` macro yourself if you really want to:

```crystal
# This just returns whatever you give it
macro public(obj)
  {{obj}}
end

class Example
  private property foo : String?
end

class Derived < Example
  public property foo : String?
end

e = Derived.new

e.foo = "Foo"
```

To clarify a bit more, when you have this:

```crystal
foo bar baz qux
```

it's actually parsed as:

```crystal
foo(bar(baz(qux))
```

That's why it looks like a keyword, but it's just a regular method/macro call.

**Comment by asterite** [comment]
(except that `protected` and `private` **are** keywords, but they could be implemented as macros just fine, and in fact I considered this a few times to simplify the language and make these macros appear in public docs (and even be redefined in other scopes if you really wanted to). I might do that one day (also for `include`, `extend`, `require` and maybe a few others)).

**Comment by anicholson** [comment]
Okay, I understand the confusion now. Apologies if my tone was strident :)

Thanks for the very prompt replies.

Happy to close :)

**Comment by anicholson** [comment]
I've made a PR with what I hope is clearer language for the docs: https://github.com/crystal-lang/crystal-book/pull/323
