### ISSUE TITLE
Markdown escapes HTML

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#7463]
Which is obviously incorrect, since Markdown is [allowed](https://daringfireball.net/projects/markdown/syntax#html) to contain HTML tags.

For an example of such erroneous behavior see
https://hanneskaeufler.github.io/crytic/api/ generated by `crystal doc` out of https://raw.githubusercontent.com/hanneskaeufler/crytic/eb13b67362fc6646f9278120ebe5ba0c9526e772/README.md

Refs #4613

**Comment by straight-shoota** [comment]
For this specific case, a simple workaround would be to avoid using HTML, it's not really necessary anyway.

But in general, I think we should find a way to use a proper Markdown library (like Makrd) in the docs generator.

**Comment by Sija** [comment]
@straight-shoota Can't do, some things can't be done with Markdown alone.

**Comment by asterite** [comment]
I still think we should split everything (std, compiler tools, etc.). Things would be so much simpler and will advance much smoother and in a more decentralized way.

**Comment by asterite** [comment]
And we should probably close this as a duplicate.

**Comment by Sija** [comment]
@asterite Duplicate of what? I haven't seen any issue regarding this explicit problem.

**Comment by asterite** [comment]
Of #4613. Std Markdown is not feature complete. Not supporting HTML is just one more missing feature.

**Comment by Sija** [comment]
IMO it's not a duplicate, rather a related issue.
For the time being there's still no decision anyway, after over a year from the last comment... :/

**Comment by straight-shoota** [comment]
The main issue is that our Markdown implementation is very limited. But everyone should expect it to support Markdown reasonably well. I don't think this can be achieved by improving the current implementation. It needs to be replaced either by a complete rewrite or an existing library.

I don't see us fixing this issue without #4613. So this should be a duplicate.
