### ISSUE TITLE
The error given when trying to send a macro as a proc could be more helpful

### ISSUE THREAD

**Issue by dscottboggs** [crystal-lang/crystal#7465]
Sample code: 

```crystal
def accepts_block(arg, &block)
  if arg
    return yield
  else
    return "not yielded"
  end
end

macro some_action
  puts "doing a thing"
	"thing done"
end

accepts_block "argument", &->some_action

```

( [playground link](https://carc.in/#/r/6bnw) )

I recognize that you can't take a proc from a macro like that but the resulting error message `wrong number of arguments for macro 'some_action' (given 0, expected 0)` could be more helpful.

**Comment by straight-shoota** [comment]
@j8r That's incorrect. As the error message shows, the error seems to be identified. If `some_action` was expanded independent of its context, the error would be something about not being able to apply the `&->` proc conversion to the expanded macro.

**Comment by asterite** [comment]
What's happening is that the compiler tries to solve `some_action` to a method and it can't find it, then it triggers the regular error displaying when a call fails, and that considers macros. The logic should be fixed to say something like "can't use macro as proc pointer". But I checked the code and it's not a one line diff change.
