### ISSUE TITLE
Time format default constants

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/crystal#7472]
## Enhancement
Working with time in crystal can be a little difficult as [shown here](https://play.crystal-lang.org/#/r/6bwk). Sometimes it's hard to remember the exact format that was used, and how to actually write that out. 

For those familiar with using rails, there's a [neat date method](https://apidock.com/rails/Date/to_s) that allows you to specify a default format. You don't have to remember how to write `%Y-%m-%d %H:%M %p` and know what that means if all you really want is something like `:db`. Since crystal has an awesome way of converting symbols in to enums, this would be a great way to have something like

```crystal
t = Time.now.to_s(:db)
Time.parse_utct(t, :db)

t = Time.now.to_s(Time::Format::DB)
Time.parse_utc(t, Time::Format::DB)
```

There could be a set of the most commonly used formats setup, along with a way to extend that list for libraries that want to add in their own additional formats that may be useful but less common.

**Comment by asterite** [comment]
What's the `:db` format? And does it depend on the database used?

**Comment by jwoertink** [comment]
That's just an arbitrary format. I'm not necessarily saying that we need a `:db` specifically, but just the concept of having some defaults that are quick uses. I think `%Y-%m-%d` is pretty common, and could be `Time.now.to_s(:date)`. But the actual list could be something we(the community) consider to be most common formats.

**Comment by asterite** [comment]
There's `%F` which expands to `%Y-%m-%d`. But I agree, we can have more common formats.

**Comment by jwoertink** [comment]
ah! I didn't know about that one. That's good to know.

**Comment by straight-shoota** [comment]
There are already a number of predefined formats available in `Time::Format`:

* HTTP_DATE (formats according to RFC 1123 and parses RFC 1123, RFC 850, IIS date, asctime)
* ISO8601_DATE
* ISO8601_DATE_TIME
* ISO8601_TIME
* RFC_2822
* RFC_3339
* YAML_DATE

They can be used like this:

```cr
format = Time::Format::ISO_8601_DATE_TIME.format(time)
time = Time::Format::ISO_8601_DATE_TIME.parse(format)
```

The formatter and parser logic are implemented directly in Crystal code instead and thus more flexible (and performant) than formatter patterns. They could be better documented though, to better explain the actual formatter rules.

For the most common formats there are also short cut methods directly on `Time``:
```cr
time.to_rfc3339
time.to_rfc2822
Time.parse_rfc3339(format)
Time.parse_rfc2822(format)
Time.parse_iso8601(format)
```

I'm not convinced that we need a name-based selection of time format for `Time#format`. But we could consider that.

However, the Rails approach is actually meant to be configurable at runtime, allowing to define default formats from configuration. That obviously won't be possible while keeping the compile-time type safety in Crystal.
I think a more customziable solution would fit better in a localization library.

**Comment by straight-shoota** [comment]
Closing. I don't think there is anything actionable to do here. Feel free to re-open if I missed something.

**Comment by jwoertink** [comment]
The only thing I'd say, which is more docs related, it would be cool if the docs for each of those formats showed what they were. Like for example https://crystal-lang.org/api/1.1.1/Time/Format/ISO_8601_DATE.html Unless I go digging through code, I have no clue what a 8601 date actually looks like... 

Aside from that, this can be closed out
