### ISSUE TITLE
Strange Proc return type behavior

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#7473]
https://play.crystal-lang.org/#/r/6bxj

```crystal
require "json"

class Base
end

module Foo
  def to_json(val : Int32)
    1
  end
end

class Model1 < Base
  include Foo  
end

class Model2 < Base
  include Foo  
end

proc = ->(key : String) do
  if key == "1"
    Model1.new
  else
    Model2.new
  end
end

r = proc.call "1"

pp r.to_json 8
```
```
Error in line 30: no overload matches 'Base#to_json' with type Int32
Overloads are:
 - Object#to_json(io : IO)
 - Object#to_json()
```

Few thing going on here.  
1.  Making class `Base` abstract fixes the problem.
2. Removing the `require "json"` changes the error, but should still work.
3. Having the proc only return one type fixes the problem.

**Comment by asterite** [comment]
Yes, this is expected behavior. Please read [this](https://crystal-lang.org/reference/syntax_and_semantics/virtual_and_abstract_types.html).

**Comment by Blacksmoke16** [comment]
Oh fair enough.
