### ISSUE TITLE
Cost too much time to run .cr file

### ISSUE THREAD

**Issue by Freakwill** [crystal-lang/crystal#7485]
It cost too much time to run a crystal file
I write a crystal file to compare with other languages in finding primes
It show that it only costed 04.03ms, but I wait several seconds to see the ouput.

```
[~] crystal run --release Programming/Benchmarks/prime.cr             20:12:44
primes   9.61  (104.03ms) (± 2.92%)  66292569 B/op  fastest
```

**Comment by j8r** [comment]
Crystal is a compiled language, compile once, then run this binary how many times you want. That's what `crystal run` does.

**Comment by Freakwill** [comment]
> Crystal is a compiled language, compile once, then run this binary how many times you want. That's what `crystal run` does.

Yes, I know, but It is slower then I thought. It spent several seconds to show the report.

```
[~] crystal build --release Programming/Benchmarks/prime.cr 
[~] ./prime
primes   9.61  (104.04ms) (± 5.91%)  66292494 B/op  fastest
```

**Comment by jhass** [comment]
This looks like the `benchmark/ips` output. The 104ms is the average runtime, the library runs it until it gets a somewhat stable value, including a couple of times before even measuring to warm up any caches.

**Comment by vladfaust** [comment]
To be exact, [`Benchmark#ips`](https://crystal-lang.org/api/0.27.2/Benchmark.html#ips%28calculation%3D5%2Cwarmup%3D2%2Cinteractive%3DSTDOUT.tty%3F%2C%26block%29-instance-method) does 2 seconds warmup + 5 seconds calculation by default.

**Comment by asterite** [comment]
It would also help if you provide some code that we can run, and what times you expect.

**Comment by Freakwill** [comment]
> It would also help if you provide some code that we can run, and what times you expect.

@asterite Thank you. I would be pleased that you can review https://github.com/Freakwill/benchmarks

**Comment by asterite** [comment]
@Freakwill Replace the last 3 lines of `primes` with this (translated from the Go code):

```crystal
  p = [2]

  i = 0
  while i < (n - 1) / 2
    x = 3 + 2 * i
    p << x if f[x] == 1
    i += 1
  end

  p
```

In my case it goes from 113.37ms per call to 98.22ms per call.

But yeah, you get a slow execution because `Benchmark.ips` will run your code many times to benchmark it, as others said. If you don't want to do that, just do:

```crystal
n = 10000000

time = Time.measure do
  primes(n)
end

puts time
```

(instead of using `benchmark`)
