### ISSUE TITLE
Document all stdlib features that need a require statement

### ISSUE THREAD

**Issue by dscottboggs** [crystal-lang/crystal#7487]
I think it's really important to note at the top of each feature in the docs that needs to be `require`d. For example, I just submitted [a PR](https://github.com/crystal-lang/crystal/pull/7486) which adds this documentation to the Big... structs, but I want to make an issue to note that all of these cases should be documented.

**Comment by straight-shoota** [comment]
That would certainly be very helpful. Examples should ideally work by copy and paste (except maybe a little custom setup might be required sometimes).
Including the necessary `require`s for the example to work is a no-brainer and already present in some API docs.

PRs are welcome.

**Comment by Maroo-b** [comment]
@straight-shoota should we close this issue as the PR was already merged?
