### ISSUE TITLE
[Non tech] Can we add the bountysource Github plugin to this project?

### ISSUE THREAD

**Issue by rishavs** [crystal-lang/crystal#7488]
Hi

This is the plugin that I am talking about.
https://www.bountysource.com/tools

This will enable us to to put bounties on specific issues. For example, I want to specifically support Windows porting work. It will ensure that the development on much wanted features moves faster.

The downside is that there is a chance that we develop an expectation of working only on items which have a bounty on it. I haven't seen it happen so far in any community driven project, but there's a chance of it.

**Comment by jhass** [comment]
IME in doing this for diaspora/diaspora, these don't really incentivize anybody, it's more a nice thank you to people that planned to work on this anyway. Also given these rarely amount to anything higher than a couple hundred dollars, it's nothing that serves as a salary for most tech workers. For Crystal your money is better put into Manas pot for paying developers, really. 

Anyway, this is probably a topic for the discourse at https://forum.crystal-lang.org

**Comment by rishavs** [comment]
Thanks. I will take it there.
