### ISSUE TITLE
Default serialization of Time in JSON  not RFC2822 nor ISO8601 compliant

### ISSUE THREAD

**Issue by anykeyh** [crystal-lang/crystal#7489]
I'm playing with crystal and moment.js; when I serialize the date into a json, it returns this string:

```crystal
{
  x: Time.now
}.to_json # => {"x": "2019-02-28T14:48:12+07:00:00"}
```

However, moment.js tell me the date format is invalid and should be RFC2822 compliant.

Basically, the seconds in the time zone stamp are not accepted. `2019-02-28T14:48:12+07:00` is accepted however.

I don't know if the time format outputted by crystal is RFC2822 compliant or not - if so, it could be a problem on moment.js library -; it seems any way overkill to have seconds in timezone, no?

**Comment by bararchy** [comment]
@anykeyh => https://crystal-lang.org/api/master/Time.html#to_rfc2822%28io%3AIO%29-instance-method

**Comment by bararchy** [comment]
All in all keep an eye over the API docs, they usually have the  answers :)

**Comment by anykeyh** [comment]
Thank you, I reformulate my issue then :smile: 

Why date serialized to JSON are not by default RFC2822 or [ISO compliant](https://www.w3.org/TR/NOTE-datetime)?

**Comment by jhass** [comment]
See https://crystal-lang.org/api/master/Time.html#to_json%28json%3AJSON%3A%3ABuilder%29-instance-method and https://github.com/crystal-lang/crystal/pull/5123#discussion_r193022243

**Comment by ysbaddaden** [comment]
Sure, but why are there *seconds in the offset*? Looking at RFC 3339 the offset is either `+00:00` or `Z`. A `+00:00:00` offset is invalid.

**Comment by asterite** [comment]
I think this is a mistake, might be a recent one. This wasn't always like that.

**Comment by straight-shoota** [comment]
Yes, this was changed in #5123 and the new `RFC_3339` formatter simply incorrectly outputs offset seconds which are not defined in RFC 3339 (they're however in ISO 8601).

RFC 2822 is an entirely different format.
