### ISSUE TITLE
Able to access protected initialize method outside of module

### ISSUE THREAD

**Issue by Frederik-Baetens** [crystal-lang/crystal#7501]
```
module Db
  class Row
    getter cells : Array(String)
    
    protected def initialize(array : Array(String))
      @cells = array.clone
    end
  end
end

array = ["hi", "hello", "howdy"]
row = Db::Row.new array
puts row.cells
```

This code works and prints the array, but I expect an error because the initialize method is protected.

**Comment by ysbaddaden** [comment]
@asterite said this is actually redundant because initialize always have the protected visibility by default; only the generated `new` constructor has a visibility, and it doesn't copy the one from `initialize`.

Maybe it should.

**Comment by Frederik-Baetens** [comment]
Yea that would be helpful, because as it is, the protected on initialize does nothing, and keywords that do nothing, and behave inconsistently are very confusing, if not dangerous for the programmer.
