### ISSUE TITLE
Compile a Crystal project in OSX to a Windows executable?

### ISSUE THREAD

**Issue by sergiotapia** [crystal-lang/crystal#7503]
Hi guys,

I'm currently exploring either Crystal or Nim for a project of mine and I can't seem to figure out from the docs how to build a .exe for Windows.

In Nim, in my OSX, I can go:

```
# This builds a static binary that runs on Linux.
nim c --cpu:arm --os:linux hello_world.nim
```

To build for Windows, I can easily go:

```
brew install mingw-w64
nim c -d:mingw hello_world.nim

# Now I have a hello_world.exe file (500KB) I can just run.
```

Does Crystal have similar commands I can run to build for Windows and Linux?

**Comment by ysbaddaden** [comment]
Hi, this is a question for the [forum](https://crystal-lang.org/crystal).

What you're looking for is `--cross-compile` and `--target`. Yet, Win32 support is far from complete.
