### ISSUE TITLE
Missing 'count the number of leading/trailing zeroes' on Int and BigInt

### ISSUE THREAD

**Issue by jzakiya** [crystal-lang/crystal#7517]
Modern compilers have a set of **builtin compiler functions** that can be availed of to optimize code (speed and code size).

Nim does a good job of this for some of them, as shown at the following links.

https://github.com/nim-lang/Nim/blob/devel/lib/pure/bitops.nim
https://github.com/nim-lang/Nim/blob/master/lib/pure/math.nim#L103

It would nice for Crystal to provide these same type of optimizations for standard methods that use them.

I have an immediate use for **countOfTrailingZeroes** and **popcount**.

**Comment by konovod** [comment]
`popcount` is present already:
https://crystal-lang.org/api/0.27.2/Int.html#popcount-instance-method

count of trailing \ leading zeros intrinsics aren't present though and doesn't work even when called as intrinsics: https://carc.in/#/r/6fps

**Comment by asterite** [comment]
@konovod It works if you use the correct signatures: https://carc.in/#/r/6fqi

Be sure to check the signature in LLVM's Reference Docs: https://llvm.org/docs/LangRef.html#llvm-ctlz-intrinsic

**Comment by jzakiya** [comment]
Interesting! I didn't know anything about an **intrinsics** lib (I found no docs on them).
But the code given from the site only works for 32 or 64 bit integers (I tried them on bitint values too).

What is desirable for me (as an application programmer, and not language developer) is having in the API method names to perform these functions which will work with any integer type (including arbitrary size). This probably means, like in the Nim code, having different implementations that are applicable to the appropriate use case.

**Comment by konovod** [comment]
@asterite my bad! I was looking at docs but somehow missed a parameter. 😄 

@jzakiya `#popcount` is already implemented for all Int and BigInt too. 
Looks like the only thing missing is a countTrailingZeroes - perhaps issue could be renamed to reflect it.
LibGMP have  `mpz_scan1` that implements it, so if you really need it you can import it directly.
https://carc.in/#/r/6fvk

But adding it to standard library can be discussed.

**Comment by ysbaddaden** [comment]
I renamed the issue.

We won't expose LLVM intrinsics publicly. Proper methods should be created on the (big) integer types to implement the feature, if accepted. It's a simple addition, given the two available carc.in examples above.

**Comment by asterite** [comment]
I marked this with the `community:newcomer` issue.

For trailing zeros we can probably use the names `trailing_zeros_count` and `leading_zeros_count`, unless someone has a better idea.

**Comment by Sija** [comment]
@asterite Should they be defined on `Number` as `abstract`, similarly to `Number#popcount`?

**Comment by asterite** [comment]
I'm not sure. Maybe that `abstract` thing was a mistake because I don't know if these can be implemented for all numeric types (isn't it just in `Int`?)

**Comment by Sija** [comment]
> (isn't it just in `Int`?)

My bad, it is! I dunno why but for some reason I thought I've seen it in inside `Number`.

**Comment by asterite** [comment]
I think it's fine then. The only subclass of `Int` we have is `BigInt` and I doubt others extend it. That's why I'm not sure those `abstract` methods serve any real purpose (we can later remove it).

**Comment by jzakiya** [comment]
Thanks to all for these new methods. :-)

**Comment by Sija** [comment]
@konovod Any idea how to return *leading_zeros_count* for `BigInt`? I haven't found any function for that in GMP.
