### ISSUE TITLE
API docs in distribution packages

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#7519]
Most of the [distribution packages](https://github.com/crystal-lang/crystal/releases) include a copy of the generated API docs in HTML format.

What's already odd: Why do we provide the API docs with every linux package, but not with the darwin/macOS packages?

I don't think having a local copy of the generated API docs is particularly useful. Most people probably don't even know they're there. And those who do, also know how to get them. The source code is included and it's fairly simple to generate the API docs locally. There is also a separate targz download available.

At ~10 MB zipped (90 MB on disk) the API docs are fairly large and account for a quarter of the linux packages' download size.

**Comment by asterite** [comment]
Probably also true for the samples.

**Comment by bcardiff** [comment]
Samples coulds be removed, sure.

But i like that offline docs are distributed. If the html doc generator is split/extracted and the compiler is left only with a non human output I would feel even more in need to ship the docs.

It’s true but that docs can be easily downloaded from github, so maybe we just need to give more visibility of that in the homepage.

**Comment by j8r** [comment]
Samples doesn't really hurt. It would be great to be able to generate the API docs offiline with `crystal docs`! For now `crystal docs /usr/lib/crystal/docs_main.cr` doesn't work.

**Comment by ysbaddaden** [comment]
My opinion: tarballs don't need the docs, a common tarball of downloadable docs is enough. Same for deb/rpm packages, there could be a distinct `crystal-doc` package instead.
