### ISSUE TITLE
Class is not a class, it's a class

### ISSUE THREAD

**Issue by stronny** [crystal-lang/crystal#7526]
```
$ cat a.cr
class Test < Class; end
$ crystal build a.cr
Error in a.cr:1: Class is not a class, it's a class

class Test < Class; end
             ^~~~~
```

What do you think, is this a helpful error message?

For the context, I was making a custom error, and somehow typed `Class` instead of `Exception`.

**Comment by straight-shoota** [comment]
This was resolved by #11378
