### ISSUE TITLE
Should forall be resolvable from methods?

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#7533]
```crystal
class Foo
  def foo
    puts "foo"
  end
end

class Bar
  def bar
    puts "bar"
  end
end

def from_x
  case x
  when 1 then Foo
  when 2 then Bar
  else
    raise "BUG"
  end
end

def method(x : Int32, y : T.class = from_x(x), &block : T ->) forall T
  yield T.new
end

method(1) do |arg|
  arg.foo
end
```

In this code, we know that `from_x` can return either `Foo` or `Bar`. Shouldn't `T` resolve two times in this case? Currently we get `undefined constant T` (https://carc.in/#/r/6ghu).

**Comment by asterite** [comment]
Arguments are solved first. The compiler doesn't know what T is in the restriction for y.

**Comment by vladfaust** [comment]
Thanks for fast reply, @asterite
