### ISSUE TITLE
Congestion of test_darwin build queue on circleci

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#7539]
Circleci currently provides us with limited build resources on macOS at 1x concurrency. Builds are triggered for every commit in a pull request. If there are lots of commits, the build queue gets congested (and will eventually reach the monthly limit in execution time). Generally, we want every commit to be tested, but sometimes new commits are pushed to a branch and we don't necessarily need to run ci on the previous ones.

This is relevant for example in #7528 which received [20 commits within a few minutes](https://github.com/crystal-lang/crystal/pull/7528#commits-pushed-0ead273) which really shouldn't be individual commits and certainly they don't need all to be tested on CI (I suppose this high number of commits is related to applying githubs patch suggestion feature).
These many commits have clogged the macOS build queue for hours which means we have to wait long to get results for relevant CI builds.

The solution to this problem is to cancel builds of outdated commits when a new one is pushed to the same branch. Circleci provides an [auto-cancelling feature](https://circleci.com/docs/2.0/skip-build/) for this, and it's activated in the repo settings. But it doesn't work as expected. From the docs it seems we also need to enable [build processing](https://circleci.com/docs/2.0/build-processing/). `Enabling Build Processing (preview)` is currently off, `Auto-cancel redundant builds` is on.

**Comment by wontruefree** [comment]
@straight-shoota you are right about the suggest feature.  These should not have been individual commits but because of github permissions, I was unable to batch them :(  Also, thank you to the people who post suggestions on PRs.

**Comment by bcardiff** [comment]
@straight-shoota good catch! I've just enabled `Enabling Build Processing`. Let's see if helps to reduce the load a bit.

**Comment by j8r** [comment]
Now I've to find other PRs to propose dozen of patch suggestions to test if this works... :smile:

**Comment by wontruefree** [comment]
code review for the win :)

**Comment by straight-shoota** [comment]
@wontruefree In the diff view there is a button `Add suggestion to batch` which allows applying several suggestions in a single commit.

**Comment by wontruefree** [comment]
that button works for other projects on github including my work but it was greyed out and un-clickable on the PR.  I don't know why.

**Comment by straight-shoota** [comment]
It seems the most severe congestion has stopped. The darwin queue still has a long wait time, but that's another story.
