### ISSUE TITLE
&. when block method has arguments

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#7549]
```crystal
["a", "b"].join(",") &.upcase
# Syntax error in eval:1: unexpected token: .
```

However, this code works as expected:

```crystal
["a", "b"].join(",") { |s| s.upcase }
```

Hm......... :thinking: Maybe we need to **revisit** the `&` syntax? :wink: 

_Or, this is just a small bug which is easy to fix._

**Comment by Sija** [comment]
Proper syntax is:

```cr
["a", "b"].join(",", &.upcase)
```

**Comment by vladfaust** [comment]
TIL. Should be added to https://crystal-lang.org/reference/syntax_and_semantics/blocks_and_procs.html.

**Comment by straight-shoota** [comment]
The short syntax is already explained on this page. What are you missing?

**Comment by asterite** [comment]
I think the form with arguments and a block is missing.

**Comment by ysbaddaden** [comment]
Closing. Not a bug.
