### ISSUE TITLE
Cant instantiate a struct with *::Serializable

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#7557]
https://play.crystal-lang.org/#/r/6ibw

```crystal
require "json"

struct Config
  include JSON::Serializable
end

pp Config.new
```
Same thing happens with the yaml version.

```
Error in line 8: wrong number of arguments for 'Config.new' (given 0, expected 1)
Overloads are:
 - Config.new(pull : ::JSON::PullParser)
```

Workaround is to define an empty initializer `def initialize; end`

**Comment by bew** [comment]
Weird that for a class it works...

**Comment by Blacksmoke16** [comment]
Looks to be because `self.struct` is included in https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/semantic/new.cr#L36

**Comment by asterite** [comment]
That it works for a class is a bug. It's already reported: https://github.com/crystal-lang/crystal/issues/7007

It's the other way around: it's working fine for `struct`.

**Comment by Blacksmoke16** [comment]
Oh, ok.  Is there a reason this is considered working as intended?  Shouldn't there be a default construct on these in addition to the `JSON::PullParser` one?

**Comment by Blacksmoke16** [comment]
@asterite And I assume the fix to #7007 isn't as easy as _adding_ `self.class` to that list in `new.cr`?

**Comment by asterite** [comment]
To be honest, I have no idea what's going on in #7007 that it's broken. It has to do with a rule in the compiler that allows an `initialize` to omit checking which instance variables are initialized if you use `{{ @type }}` inside a def. And that hack exists to support `JSON::Serializable`. I'd like to remove that hack, remove `JSON::Serializable` and do it in another way, but nobody seem to like that idea... so for now I wouldn't worry about all of this. It needs to settle down.

**Comment by vladfaust** [comment]
What another way would you propose, @asterite, besides of sticking with `.mapping`?

**Comment by kostya** [comment]
https://github.com/kostya/auto_initialize?

**Comment by ysbaddaden** [comment]
Maybe it could be achieved with an `@[unsafe]` annotation? Mark the `initialize` method as unsafe, so the compiler won't check for uninitialized variable; calling `new` directly will fail to compile, because the `initialize` method is unsafe and must be wrapped in an unsafe block (or called from an unsafe method), which Serializable can do. This assumes that Serializable is correct, but that's exactly what's assumed now.
