### ISSUE TITLE
Invalid memory access with --release and --debug

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#7558]
Steps to reproduce:
1. Clear Crystal's cache using `sudo rm -rf ~/.cache/crystal/`.
2. Compile a program (can be empty) with `--release` and `--debug`.

Output should be:
```
Invalid memory access (signal 11) at address 0x1c
[0x7f6f114a3836] ???
[0x7f6f10a18f00] ???
[0x7f6f128ea445] ???
```

I first encountered this without my cache cleared. It always happened when I changed my program. When I compiled with the same program again, I did not get an Invalid memory access (however doing the above *always* results in an Invalid memory access. My old cache was probably at a specific glitchy state at this point).

But that's not all. There's also something else to reproduce:
1. Clear Crystal's cache again using `sudo rm -rf ~/.cache/crystal/`.
2. Compile a program (can be empty) **without** any flags.
3. Compile this program:
    ```crystal
    {% flag?(:release) && flag?(:debug) %}
    ```
    with `--release` and `--debug`.

Output should be:
```
Invalid memory access (signal 11) at address 0x1c
[0x7f52fcaa3836] ???
[0x7f52fc018f00] ???
[0x7f52fdeea445] ???
```
And now compile this program *again* with `--release` and `--debug` and the output should be much longer: [**GitHub**Gist](https://gist.githubusercontent.com/r00ster91/389ebe0f91fef4e5dd354a855382c689/raw/c69e606a8a11de29b5f8e40ea69f28db43870bd8/gistfile1.txt).
After that the output no longer changes.
I'm very sure this is a bug in the cache.

**Comment by jreinert** [comment]
Seeing this too. Are you saying the invalid memory access is _supposed_ to happen?

**Comment by r00ster91** [comment]
No, it's not supposed to happen of course. But it would be strange if someone doesn't happen to someone with the same version.

**Comment by jreinert** [comment]
Right. It's a bit annoying since I can't build anything for production that would output usable stacktraces on uncaught exceptions. Have you found any way around it?

**Comment by jreinert** [comment]
I'm glad that it's so easily reproducable at least. `echo | crystal eval --release --debug`

**Comment by r00ster91** [comment]
No I haven't found any workaround so far :/
My usecase would be to allow debug features in production builds.

**Comment by jreinert** [comment]
Exactly my usecase too. We use sentry in production and it's pretty much useless without a readable trace.

**Comment by asterite** [comment]
--debug is not needed for good traces

**Comment by jreinert** [comment]
@asterite care to elaborate?

**Comment by ysbaddaden** [comment]
Debug line numbers are always emitted unless you pass `--no-debug`, so you don't need `--debug` for file:line:column in backtraces. The purpose of `--debug` is to add type debug information for actual debug in gdb or lldb.

**Comment by jreinert** [comment]
Hm maybe this is unrelated but all i see is `???` in my backtraces, regardless if i use `--no-debug` or not. I'm building with `shards build --production --release`.

**Comment by ysbaddaden** [comment]
The stack is corrupted so the stack unwinding reported bogus adresses, an we can't decode it to a nice file:line backtrace.

**Comment by jreinert** [comment]
does the `--static` flag have something to do with this? I just added a Dockerfile to the same project and get the following output when i run the image:

```
Raising...
Invalid memory access (signal 11) at address 0x0
```

Here's the Dockerfile:

``` Dockerfile
FROM jreinert/crystal-alpine AS build

WORKDIR /project
ADD . /project

RUN shards build --production --static --release

FROM scratch
COPY --from=build /project/bin/test /bin/test

CMD ["/bin/test"]
```
and the source:

``` crystal
def one
  raise "something went wrong"
end

def two
  one
end

def three
  two
end

puts "Raising..."
three
```

**Comment by ysbaddaden** [comment]
@jreinert this is #4276

**Comment by Daniel-Worrall** [comment]
I'm getting similar results from `crystal spec -d` on an app skeleton. Unsure if it's the same/related.

```
Invalid memory access (signal 11) at address 0x7fca826f6f08
[0x488536] *CallStack::print_backtrace:Int32 +118
[0x476140] __crystal_sigfault_handler +192
[0x7fca81591390] ???
[0x7fca826f6f08] ???```

**Comment by leonklingele** [comment]
This happened multiple times already on my end, finally got a crash inside Travis CI:
https://travis-ci.com/omarroth/invidious/jobs/224122920#L280-L287

**Comment by asterite** [comment]
First step is to check unsafe calls. I'm seeing a bunch of unsafe calls in indivious.

**Comment by leonklingele** [comment]
@asterite please excuse my lack of knowledge but what are unsafe calls? Are you referring to https://crystal-lang.org/reference/syntax_and_semantics/unsafe.html?

**Comment by asterite** [comment]
Yes, but also searching "unsafe" in the repo I found a few to_unsafe calls. Might be the issue, might be not.

**Comment by rdp** [comment]
Wasn't able to repro in ubuntu 19.10 or OS X FWIW...

**Comment by BlobCodes** [comment]
`echo | crystal eval --release --debug` doesn't give me an error.
Seems to have been fixed. Can this be closed?

**Comment by r00ster91** [comment]
Yup, it seems to be fixed.
> I'm getting similar results from `crystal spec -d` on an app skeleton. Unsure if it's the same/related.
> 
> ```
> Invalid memory access (signal 11) at address 0x7fca826f6f08
> [0x488536] *CallStack::print_backtrace:Int32 +118
> [0x476140] __crystal_sigfault_handler +192
> [0x7fca81591390] ???
> [0x7fca826f6f08] ???```
> ```
I can't reproduce this either.
