### ISSUE TITLE
Iterator doesn't seem to be matching type aliases

### ISSUE THREAD

**Issue by jgaskins** [crystal-lang/crystal#7567]
Trying to use an `Iterator` to reduce memory consumption of a large result pulled back from a database (the nodes go through a few transformations before being serialized as JSON) and getting this error:

```crystal
instantiating 'Iterator::Map(Indexable::ItemIterator(Array(Neo4j::Type), Neo4j::Type), Neo4j::Type, DatabaseMetric)#next()'
in /usr/local/Cellar/crystal/0.27.2/src/iterator.cr:722: type must be Neo4j::Type, not (Array(Neo4j::Type) | Bool | Float64 | Hash(String, Neo4j::Type) | Int16 | Int32 | Int64 | Int8 | Neo4j::Failure | Neo4j::Ignored | Neo4j::LatLng | Neo4j::Node | Neo4j::Path | Neo4j::Point2D | Neo4j::Point3D | Neo4j::Relationship | Neo4j::Success | Neo4j::UnboundRelationship | String | Time | Nil)
```

In this case, `Neo4j::Type` is an [alias for all of those types](https://github.com/jgaskins/neo4j.cr/blob/0038216f0984b84417c09edb12e61032caf2edae/src/neo4j/type.cr#L111-L131), including `Nil`.

I unfortunately don't have a reduced example for this yet. I'll see if I can find one soon.

**Comment by asterite** [comment]
My advice is to avoid using recursive aliases. They are slightly broken. You can use wrapper structs to achieve more or less the same result. That will probably make it work (I don't know if you control the Neo4j library).

**Comment by asterite** [comment]
@jgaskins can you try doing `exp.as(Neo4j::Type)` with the return value of the iterator?

Otherwise, without some reproducible code we can't help.

**Comment by asterite** [comment]
Actually, it's super easy to reproduce:

```crystal
alias Rec = Int32 | Array(Rec)

a = [] of Rec
a << a

p a.each.map(&.itself).to_a
```

**Comment by asterite** [comment]
And simpler:

```crystal
alias Rec = Int32 | Array(Rec)

a = uninitialized Rec

f = ->(x : Rec) {}
f.call(a.itself)
```

I think this can be fixed, it seems to be a problem with Proc type matching and recursive aliases.

**Comment by asterite** [comment]
@jgaskins Sorry for all the above noise, it was a really simple bug to fix. It'll probably be available in the next release.

**Comment by jgaskins** [comment]
Nice work! I was going to try to get a reduced example after work today but you beat me to it! :joy: Thanks!
