### ISSUE TITLE
Cannot expand a macro call

### ISSUE THREAD

**Issue by dscottboggs** [crystal-lang/crystal#7573]
The issue is that whenever I try to run `crystal tool expand` on certain macros, I receive an error message: `no expansion found`. For example, using [this macro call](https://github.com/dscottboggs/kemal-jwt-auth/blob/355d16dec06e3949ea003cdb8a7810bd61d16009/src/handler.cr#L58):

```sh
$ crystal tool expand -c src/handler.cr:58:4 src/handler.cr
no expansion found
```

I apologize that I am unable to create a more minimal example. I've tried, but the tooling works on all of my more minimal examples. For example, the following works:

```crystal
module TMod
  class TClass
    @ivar = true

    def tmeth
      something = "something"
      return tester({some: ["data"]})
    rescue e
      puts "an exception"
      access @ivar
      raise e
    end

    private def access(ivar); end

    private macro tester(v)
      pp! something, {{v}}
    end
  end
end

puts TMod::TClass.new.tmeth.inspect

```

The above example expands to a macro, but the example in the github link I posted does not.

**Comment by z64** [comment]
The macro is never expanded because your class isn't used. In your minimal example, if you comment-out the `puts` line, you'll see `no expansion found`.

If you fix your return type just so your code compiles
```diff
   # and return to the user a JWT if they succeed the authentication challenge.
-  private def sign_in(with context : HTTP::Server::Context) : HTTP::Server::Context
+  private def sign_in(with context : HTTP::Server::Context) : HTTP::Server::Context?
     if (body = context.request.body) && (user_info = @users.find_and_authenticate! body)
```
and then run `$ crystal tool expand -c src/handler.cr:58:5 spec/handler_spec.cr` instead, since your specs actually make use of the class, you will get what you are looking for:
```
1 expansion found
expansion 1:
   send_json({errors: ["Unauthorized."]})

# expand macro 'send_json' (/root/kemal-jwt-auth/src/handler.cr:88:11)
~> context.response.content_type = "application/json"
   context.response.print({errors: ["Unauthorized."]}.to_json)
   context.response.flush
   context
```

**Comment by straight-shoota** [comment]
I don't think there is anything actionable here. Closing.
