### ISSUE TITLE
Instance Variables in the generated docs

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#7576]
Currently the generated docs do not display the actual instance variables that are apart of that class, only the getter/setters (if using getter/setter/property).

For example: 
```crystal
class Foo
  property name : String = "Jim"
end
```
![image](https://user-images.githubusercontent.com/12136995/54848831-bf60db00-4cb8-11e9-9bcb-97bc5d1bf326.png)

In this example there is no representation of the default value of `name`.

I propose adding a new section for instance variables.  This would only include instance variables created with `getter/setter/property` that are not `private`.  `private` instance vars and those created by `@name` syntax probably should be excluded.

I'd imagine this section being similar to the constants section, just showing the name, type, and default value (if any) of each public instance vars.

EDIT:  Also probably a bug that `Defined In` is displayed if the class was never used?

**Comment by asterite** [comment]
Instance variables are always private. They aren't documented in any language out there (Ruby, Java, C#, Go, etc.), just like anything private isn't documented at all anywhere.

Why do you need this? If you need to say that something starts with a default value, just document it.

**Comment by Blacksmoke16** [comment]
Oh don't really need it just something I noticed.  But yea in that case prob not needed.
