### ISSUE TITLE
possible issue with Slice#clone

### ISSUE THREAD

**Issue by Maroo-b** [crystal-lang/crystal#7590]
Code source:
https://carc.in/#/r/6l2p
```
slice = Slice["abc", "a"]

slice.clone
```
```
Error in line 3: instantiating 'Slice(String)#clone()'

in /usr/lib/crystal/slice.cr:125: Can only use primitive integers and floats with Slice.new(size), not String

    copy = self.class.new(size)
```

It's strange how Slice was created with String elements but it fails to clone the instance.
Is this an intended behavior?

**Comment by straight-shoota** [comment]
Yeah, that's a bug. When #3624 was fixed, `Slice#clone` was not adapted. Should be easy to fix.

**Comment by Maroo-b** [comment]
I'm closing this issue since the fix was merged.
