### ISSUE TITLE
Bad formatting for comma enum with comments

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#7600]
```cr
enum E
  A, # hello
  B, # hello
  C, # hello
end
```
gets formatted to:
```cr
enum E
  A,  # hello
B,    # hello
C,    # hello
end
```
But I expect nothing to happen.

**Comment by Maroo-b** [comment]
@straight-shoota I was checking the docs for [Enum](https://crystal-lang.org/api/0.24.0/Enum.html) at seems the recommended format doesn't have any commas and doesn't have any issues with the current formatter exp:
```
enum Color
  Red   # 0
  Green # 1
  Blue  # 2
end
```

It seems that Enum accepts both formats but which one should be returned by the formatter?

**Comment by r00ster91** [comment]
> It seems that Enum accepts both formats but which one should be returned by the formatter?

The one that has been input to the formatter. It wouldn't make much sense to have comma enums when the formatter converts it to a non-comma enum.

**Comment by straight-shoota** [comment]
@Maroo-b Yes, but it's an error either way. If it is valid code, the formatter should format it correctly. If it is not valid, the formatter should complain.

**Comment by j8r** [comment]
Being not space/new-line sensitive, Crystal also supports this syntax:
```cr
enum E
  A B C
end
```
The comma can be dropped. Therefore there is no point of supporting both syntax.

**Comment by Maroo-b** [comment]
Is formatter expected to behave like Rubocop? which means it formats the code based on the recommended style or its role is only about managing indentations and white space?
If this an issue, I'll submit a PR for it.

**Comment by asterite** [comment]
> or its role is only about managing indentations and white space?

Mostly this. It also removes unneeded semicolons, parentheses and sometimes commas.

In this case it's just a formatter bug and I think I know the fix.

**Comment by Maroo-b** [comment]
@asterite no worries I can work on it, I already had in mind to tackle opened formatter issues :muscle: .
