### ISSUE TITLE
Can't require installed compiler

### ISSUE THREAD

**Issue by bew** [crystal-lang/crystal#7602]
So I've been trying to play with the compiler on `Crystal 0.27.2`:
```cr
# file foo.cr
require "compiler/crystal"

Crystal::Compiler.new
```
Compile with:
```cr
crystal foo.cr -Di_know_what_im_doing
```
And I'm _gently_ welcomed with the following error:
```
cat: /usr/lib/crystal/compiler/crystal/../../../VERSION: No such file or directory
```
(for fun, here is [the full trace](https://gist.github.com/bew/fa20b049d2e67d3a268394739a29287a))

**Comment by straight-shoota** [comment]
Yeah we should probably include the `VERSION` file in the source folder provided by the Crystal package or make reading it optional.

**Comment by j8r** [comment]
How can we simply get the Crystal version, build commit, LLVM version etc. inside Crystal code?

I've tried this, but that's really messy to have to require the whole compiler:
```cr
require "compiler/crystal/**"

Crystal::Config.version
Crystal::Config.build_commit
Crystal::Config.llvm_version
Crystal::Config.default_target
Crystal::Config.date
```

**Comment by asterite** [comment]
https://crystal-lang.org/api/0.28.0/Crystal.html

No need to require anything.

**Comment by j8r** [comment]
That does the job, only missing the `default_target`

**Comment by asterite** [comment]
Yes, because the target is something specific to the compiler, not something you want to use outside of it.
