### ISSUE TITLE
from_json nullifies the performance advantage of using a struct

### ISSUE THREAD

**Issue by girng** [crystal-lang/crystal#7609]
**System:** Windows 10 WSL (Ubuntu 16.04.5 LTS), Crystal 0.27, i7 2600

### Example Benchmark Code:
```
require "json"
require "benchmark"

TimesToLoop = 2500

struct Message
  include JSON::Serializable
  property cmd : String
  property extra : Int32
  property message : Hash(String, String)

  # JSON.mapping(
  #   cmd: String,
  #   message: Hash(String, String),
  #   extra: Int32
  # )
end

JSON_DATA = %({"cmd": "LOGIN", "extra": 123, "message": {"hi": "[1, 2, 3]", "username": "george", "password": "muffin"}})

Benchmark.ips do |x|
  x.report("JSON.parse with JSON::Any") {
    TimesToLoop.times do
      message = JSON.parse(JSON_DATA)
      # We usually have to invoke type checking.. so let's add some
      if message["extra"].as_i == 123
      end
    end
  }
  x.report("from_json with struct & JSON.mapping") {
    TimesToLoop.times do
      message = Message.from_json(JSON_DATA)

      # statically typed as Int32?
      if message.extra == 123
      end
    end
  }
end
```

#### Results:
```
           JSON.parse with JSON::Any 145.27  (  6.88ms) (± 1.12%)  5562650 B/op   1.02× slower
from_json with struct & JSON.mapping  147.6  (  6.78ms) (± 1.82%)  4962646 B/op        fastest
```

`JSON.parse` ranges between **1.02** and **1.06** slower over several tests.

However, `from_json` has an extreme performance bottleneck. Move `TimesToLoop.times do` below `JSON_DATA`.

#### New Results:
```
           JSON.parse with JSON::Any  21.95k ( 45.56µs) (± 2.09%)  1649 B/op  24.22× slower
from_json with struct & JSON.mapping 531.65k (  1.88µs) (± 2.69%)  1409 B/op        fastest
```

`JSON.parse` now ranges from **24.22** to **26.22** slower over several tests. 

 The advantage of using a `struct` is **huge**. Statically typed! But when `from_json` is used, that advantage is nullified.

**Comment by asterite** [comment]
I don't understand. It seems you are saying from_json is more performant, and that's expected. So what's the problem?

**Comment by girng** [comment]
@asterite Using `from_json` outside of the `TimesToLoop` loop is **24.22x** faster than `JSON.parse` 

If `from_json` is inside the loop, it's only 0.01 to 0.06 faster (negligible, compared to 24.22x)

**Comment by lbguilherme** [comment]
Probably the simple fact of parsing a JSON is so much more performance intensive than accessing fields (dynamically vs statically) that it takes 99% of the benchmark time and using a struct or not doesn't make a real difference anyway. (I didn't test that to be sure)

**Comment by asterite** [comment]
Yes, JSON parsing will take most of the time. The idea of using from_json is that it uses less memory (as you can see in your benchmark), it's type safe and you don't need to do hash lookups to access fields. It doesn't mean its like 100 times faster.

**Comment by girng** [comment]
The performance using a `struct` instead of `JSON.parse` is  **monumental**.  When the performance of a `struct` is hindered by `from_json`,  it seems unfair to the developer.   I also think it goes against crystal's "statically type-checked" description. Because the developer can  just use `JSON.parse` and achieve similar performance, but now, their code will be littered with  type checking methods  and `JSON::Any`.  

 
I hope you guys can see where I'm coming from. If you have time, please take a deeper look into this issue, it will be appreciated.

**Comment by konovod** [comment]
@girng, simply put, JSON (JavaScript Object Notation) is a "dynamically-typed", slow thing. You can convert it to a statically-typed struct using `from_json` and then access the fields fast, but `from_json` is still slow because JSON must be parsed. If you need speed - use binary format. For example - [cannon](https://github.com/Papierkorb/cannon). It will be many times faster than json.

**Comment by girng** [comment]
> @girng, simply put, JSON (JavaScript Object Notation) is a "dynamically-typed", slow thing. You can convert it to a statically-typed struct using `from_json` **and then access the fields fast** 

See bold. Unfortunately this is not the case. Because you have to use `from_json` first, thus, "accessing the fields fast" is not true.  It's dependent on `from_json`, which acts as a bottleneck and deteriorates the speed that a `struct` offers!

**Comment by asterite** [comment]
I still don't know what you want. You want to access a field without the cost of parsing JSON? Could you state the problem as "this is the current behavior, this is what I'd like it to happen"

**Comment by girng** [comment]
@asterite The benchmark code in my original post should output something similar to:
```
           JSON.parse with JSON::Any  21.95k ( 45.56µs) (± 2.09%)  1649 B/op  24.22× slower
from_json with struct & JSON.mapping 531.65k (  1.88µs) (± 2.69%)  1409 B/op        fastest
```
Because it's using a statically typed `struct`. The developer is explicitly defining **the types and structure**.
 
But instead, that speed is  hindered because the `struct`  relies on `from_json`.

**Comment by ysbaddaden** [comment]
`from_json` is already doing what you say.

The problem is the JSON format. It using string representations (not raw binary, like msgpack) which require to transform all values to an actual type (e.g. String to Int64). There isn't a schema, fields appear in random order, which requires to parse all keys in addition to values, ...

All that is expensive, and is the performance issue you're trying to raise. Nothing we can do, I think. But please prove me wrong with some code! Everybody loves free performance improvements.

**Comment by girng** [comment]
@ysbaddaden Interesting

Is there a way for the language to use a struct as a schema for JSON data, so it doesn't have to "transform all values to their type and/or parse keys and values"? I thought that is what  JSON serializable/mapping is doing by explicitly writing out the types?

It just feels weird because using a struct has a performance vibe to it, then, when you use it.. that performance is gone because of parsing JSON.  I thought the JSON mapping and whatnot was a solution to that.
