### ISSUE TITLE
Add "digits" method to Int

### ISSUE THREAD

**Issue by jzakiya** [crystal-lang/crystal#7611]
In translating some Ruby-to-Crystal code on Rosetta code, the Ruby snippet was this:

```
n.digts.sum
```
Crystal doesn't have a ``digits`` method, so I ended up doing this:

```
n.to_s.char.sum(&.to_i)
```

So ``.to_s.char`` is almost equivalent to ``.digits`` except the digits are reversed, and strings.

A ``digits`` method would be very useful, and native version wouldn't create an array of chars first.

**Comment by straight-shoota** [comment]
Thank you for reporting this feature request. There is already a PR for that: #5598 But it's unclear whether it will be merged due to limited usefulness. Maybe you could describe your use case more concrete than porting Ruby code?
