### ISSUE TITLE
Documentation of program constants in `Crystal` namespace missing

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#7613]
Since 0.27.1 the constants in `Crystal` namespace (like `Crystal::VERSION`) are missing from the API docs.

* present in 0.27.0: https://crystal-lang.org/api/0.27.0/Crystal.html
* missing in 0.27.1: https://crystal-lang.org/api/0.27.1/Crystal.html

I'm not sure what might be the source of this regression.

**Comment by asterite** [comment]
Might be [this commit](https://github.com/crystal-lang/crystal/commit/2d4e955).

The commit is fine, it excludes constants that don't have a location or that are not part of the project. The thing is, `Crystal::VERSION` and others are created inside the compiler, they don't have a location. I'm not exactly sure how to fix it.

**Comment by straight-shoota** [comment]
Yeah, that seems to be it.

I guess we have two possible paths of action:

We could add locations to these constants or add some special rule to `must_include?` to let them pass (`return true if const.namespace == "Crystal"`).
Locations could simply be fake, or some kind of special location ("compiler-generated"), or the actual location in the compiler source (`src/compiler/crystal/program.cr`). The latter mixes compiler source paths with program source paths, though.

**Comment by bcardiff** [comment]
We could add a call to `crystal_builtin?` from the `must_include?` I think
