### ISSUE TITLE
Trouble getting Crystal to build

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#7615]
I am having trouble building crystal when I try building Crystal the build never finishes.  I have been trying to debug what could be hanging the build, but I have not been able to figure it out. 
 This is on a MacOS machine with the compiler used to build Crystal being from Homebrew.

What is crazy is I also have zsh on this machine and I can build Crystal normally with zsh.  Because I can build with zsh, I have exported the `PATH` and `PKG_CONFIG_PATH` in bash, and I still cannot get Crystal to build.

Has anyone experienced crystal hanging before? And do you know a good way to debug this?

sample output:
```bash
(cafe:crystal)$ make clean
Using /usr/local/opt/llvm@6/bin/llvm-config [version=6.0.1]
rm -rf .build
rm -rf ./docs
rm -rf src/llvm/ext/llvm_ext.o
rm -rf src/ext/sigfault.o src/ext/libcrystal.a
(cafe:crystal)$ make
Using /usr/local/opt/llvm@6/bin/llvm-config [version=6.0.1]
c++ -c  -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc -I/usr/local/Cellar/llvm@6/6.0.1_1/include  -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -DNDEBUG   -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
cc -fPIC    -c -o src/ext/sigfault.o src/ext/sigfault.c
ar -rcs src/ext/libcrystal.a src/ext/sigfault.o
CRYSTAL_CONFIG_PATH="/Users/jack/source_code/open_source/crystal/src" CRYSTAL_CONFIG_BUILD_COMMIT="4f1e8a540" ./bin/crystal build -D preview_overflow -D compiler_rt  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
```

**Comment by asterite** [comment]
Maybe at least run `make crystal stats=1` so we know in which phase it's stuck?

**Comment by wontruefree** [comment]
I am running it but it looks like it is either getting stuck before `stats` produces output.

**Comment by asterite** [comment]
Maybe go to Activity Monitor, find the process, click the cog and select "sample process" to see where it's stuck

**Comment by wontruefree** [comment]
Here is a sample from the Activity Monitor
https://gist.github.com/wontruefree/c7608e5b29c036e01cf751cf21158383.js

**Comment by bcardiff** [comment]
Did you try clearing the `~/.cache/crystal/` directory? just in case...

**Comment by wontruefree** [comment]
It looks like that did not fix it.  But I will remember that for future debugging.
So there is no really good way to debug the build besides the `stats` or `progress` flag?

**Comment by straight-shoota** [comment]
You could trace system calls. I guess thats `dtruss` on MacOS.
This might tell you where it hangs.

**Comment by wontruefree** [comment]
Getting `dtruss` to work correctly on this mac is a hard.  From reading using `dtruss` on anything under `/usr/bin` has a lot of caveats.  I was not able to figure anything out there are a lot of errors.  But I will work on it more.

**Comment by asterite** [comment]
> What is crazy is I also have zsh on this machine and I can build Crystal normally with zsh

Then it's probably a configuration issue in your machine?

**Comment by wontruefree** [comment]
@asterite I agree it is a configuration issue but I was seeing if there was a good way to debug it.  It is using the same path so I dont know what else it could be.

I was mostly seeing if there are any tools to debug building the compiler.

I am going to close this for now.  Thank you for all the help.
