### ISSUE TITLE
Server inside vm can't be reached on the host

### ISSUE THREAD

**Issue by jakeactually** [crystal-lang/crystal#7621]
I tried to make a simple tcp server on linux on virtualbox on windows. I tested it on firefox inside the vm and it worked, but it didn't work on the host neither with port forwarding nor bridged router.

I also tried the crystal http api, and hyper-v. Nothing worked.

I tried serving things to the host with nginx, js (node) and c and all of that worked. I also tried crystal on wsl and it worked.

My intention was to have a crystal virtualbox vm but I couldn't because I couldn't reach the server on the host.

Thanks for listening!

**Comment by j8r** [comment]
Take sure that the server is listening on all network interfaces (`0.0.0.0` or `::`).
On what address/port is listening the server?

**Comment by ysbaddaden** [comment]
This is a question for the [forum](https://forum.crystal-lang.org/)
