### ISSUE TITLE
Documentation / Tutorial: From ruby to crystal

### ISSUE THREAD

**Issue by rubyFeedback** [crystal-lang/crystal#7625]
I would like to suggest a short document, a mini-tutorial, for people who already know ruby but may consider crystal for whatever the reason.

It may be a quite common use case to see ruby users come start with crystal; I assume many current crystal users came from ruby.

Now you may say that working through the official tutorial is what people should go through, which is fine; but people are lazy too. My idea would be just to distill the core things, the core differences, to get people going. Perhaps a bit like a wiki, but an official link from the tutorial to that wiki may be useful.

What should this tutorial include?

- Syntax differences, ideally with examples; starting with the biggest differences, e. g. type system.

- Minor differences elsewhere in the language.

I am not sure if this may be considered worthwhile to have but it may help people transition into crystal, e. g. get started with it. Right now there is quite a lot of documentation but people don't always have time to read it all - right now I have only 30 minutes left before I have to leave here for ~4 hours, then I come home, have ~2 more hours, then sleep, early wake up, things to do ... during the week it is very hard to find enough time to learn crystal. Over the weekend it is a bit better but I'd be much happier to look sort of just at a "distilled version" for crystal.

(One advantage of a wiki may be that it is easier for people to add/contribute to it, and github has a wiki integrated as far as I know on a per project basis.)

**Comment by straight-shoota** [comment]
There is already a pretty extensive article on our wiki: https://github.com/crystal-lang/crystal/wiki/Crystal-for-Rubyists Maybe it just needs more exposure?

**Comment by ysbaddaden** [comment]
Could you reopen this discussion on the [forum](https://forum.crystal-lang.org), please? Thank you :heart:

**Comment by j8r** [comment]
I think it will better to have its own repo rather than the wiki, like https://github.com/crystal-lang/crystal-for-rubyists and have a link pointing to it in https://github.com/crystal-lang/crystal-book

**Comment by asterite** [comment]
Regardless of this specific issue, Crystal is missing a tutorial that guides you through the language while maybe building some small programs, either assuming Ruby knowledge or not. I'd love to have something like this... but it requires time and effort.

**Comment by bew** [comment]
I've been reading https://doc.rust-lang.org/book/ch02-00-guessing-game-tutorial.html lately, I thought it was very well explained even for a simple example like this! We can start shorter of course!

**Comment by straight-shoota** [comment]
@asterite #4462

I've started with very short first steps. Maybe I should already publish it to continue working on it together?

**Comment by asterite** [comment]
@straight-shoota Definitely!
