### ISSUE TITLE
Shifting a `Deque(Nil)` more times than its initial capacity crashes the program

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#7644]
I'm having a `Deque` with initial capacity of `N` and try to push `N + 1` values to read and then read them one-by-one.

This simple program works as expected (https://carc.in/#/r/6obc):

```crystal
deque = Deque(Bool).new(1)

2.times do
  deque << true
end

2.times do
  deque.shift
end

puts "ok"
```

Howerver, if using `Nil` as the deque's type, it crashes (https://carc.in/#/r/6obd):

```crystal
deque = Deque(Nil).new(1)

2.times do
  deque << nil
end

2.times do
  deque.shift
end

puts "ok"
```

```
Invalid memory access (signal 11) at address 0x0
```

The last offending line I've found is [this](https://github.com/crystal-lang/crystal/blob/60760a5460aa13a1f80c5a1a7410782dc4076b77/src/deque.cr#L531) — `Pointer(Nil).realloc` may lead to the bug. The issue happens with `Nil` only. Other types, as well as custom structs and classes, work as expected.

**Comment by konovod** [comment]
Fails with empty struct too:
```crystal
record A

deque = Deque(A).new(1)

2.times do
  deque << A.new
end

2.times do
  deque.shift
end

puts "ok"
```
https://carc.in/#/r/6oci

**Comment by konovod** [comment]
Also fails if you replace `Deque` with `Array`

**Comment by r00ster91** [comment]
This is fixed when adding `check_needs_resize` to `Array`'s `shift` and `increase_capacity if @size >= @capacity` to `Deque`'s `shift` however it's strange that it happens only with `Nil` and an empty struct.

**Comment by r00ster91** [comment]
The problem seems to be that `Nil` or an empty struct is a null pointer internally: https://carc.in/#/r/6of0.

**Comment by konovod** [comment]
@r00ster91 yes, the problem is that they have zero size, so array needs buffer of size 0 and that's ok. 
Allocating of 0 bytes returns `null` pointer, and that's ok too (we aren't going to write anything to a buffer). 
But all remaining code have to take this case into account (explicitly or implicitly).

**Comment by refi64** [comment]
Not sure if Crystal handles this explicitly, but it's worth noting that
from a malloc standpoint, allocating 0 bytes doesn't *have* to return a
null value; it's valid to return e.g. a special memory address signifying a
0 byte allocation.

--
Ryan (ライアン)
Yoko Shimomura, ryo (supercell/EGOIST), Hiroyuki Sawano >> everyone else
https://refi64.com/
