### ISSUE TITLE
[Docker] Provide a higher base image version

### ISSUE THREAD

**Issue by Hentioe** [crystal-lang/crystal#7647]
The current Docker images are built on top of `buildpack-deps:xenial` (yes, right?). But the Ubuntu `xenial` (16.04) is a bit old and often causes problems.

For example, in different versions of Ubuntu, the version of `rocksdb` varies greatly: https://packages.ubuntu.com/search?searchon=sourcenames&keywords=rocksdb

![image](https://user-images.githubusercontent.com/13946976/55686589-98cbc100-5995-11e9-9979-e5bbc672348b.png)

The `rocksdb` under Xenial is the `4.1` version, which was last updated 4 years ago (But actually my development environment uses version 5.x). There are many similar phenomena.
Overly old software packages often cause deployment problems and are likely to be incompatible or even a security risk.

Perhaps, consider providing some newer image. For example `cyrstallang/crystal:0.27.2-bionic-build` or even `cyrstallang/crystal:0.27.2-disco-build`

**Comment by j8r** [comment]
Thanks for opening this issue @Hentioe. Can you create one in https://github.com/crystal-lang/distribution-scripts, which hosts this Dockerfile?

**Comment by Hentioe** [comment]
@j8r The content here (<https://github.com/crystal-lang/distribution-scripts>) depends on the CI service. Maybe I can only build a brand new, pure Dockefile myself, is that the case?
