### ISSUE TITLE
Use Array's initial capacity argument

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#7658]
I think `Array`'s `ìnitial_capacity` argument should be used more often. I've found some cases in for example `Enumerable` where `[] of T`s could be replaced by `Array(T).new(initial_capacity)`s.
Doing this would allocate memory for the array only once and would avoid repeately reallocating the internal buffer of the array because the size changed.

I wonder, would it be worth to do this?

**Comment by asterite** [comment]
An Enumerable doesn't know its size, it's not required from the interface. Rust has a size_hint getter that returns nil if the size is unknown, otherwise an integer. We could do the same but I'm not sure.

**Comment by r00ster91** [comment]
Hmm but there is `Enumerable#size` which computes the size by iterating through the elements. And almost all the types that include `Enumerable` override `Enumerable#size` with their own implementation (they are mostly `getter`s so nothing is computed). Wouldn't it be possible to use this method?

**Comment by wontruefree** [comment]
I like the idea of a size hint but I feel like it would not be commonly used so we should measure if there is any overhead to adding it.

**Comment by r00ster91** [comment]
>I like the idea of a size hint but I feel like it would not be commonly used

The size hint at the `Array.new` in the method will be used when the method is used.

> so we should measure if there is any overhead to adding it.

There's no overhead of doing this, it's in fact faster because it avoids reallocating the array's buffer.

```cr
require "benchmark"

Benchmark.ips do |bm|
  bm.report "no initial capacity" do
    a = [] of Int32
    100.times do |i|
      a << i
    end
  end

  bm.report "initial capacity" do
    a = Array(Int32).new(100)
    100.times do |i|
      a << i
    end
  end
end
```
```
no initial capacity 568.94k (  1.76µs) (±12.35%)  1.67kB/op   1.72× slower
initial capacity    979.33k (  1.02µs) (±12.01%)    480B/op        fastest
```

**Comment by wontruefree** [comment]
Would adding a hint cause a bigger memory footprint for every array even those that do not use a hint?

**Comment by r00ster91** [comment]
No, passing a size hint to an array does not affect other arrays, only the array the size hint has been passed to. But I mean when the array the size hint has been passed to is first created then it will of course have a higher memory footprint. But it's probably better to do one big allocation rather than stretching the memory allocations over time since that's slower.

**Comment by wontruefree** [comment]
Sorry I looked into it a little more I misunderstood.

**Comment by jhass** [comment]
I think pull requests for using it where it makes sense are welcome and pretty much no-brainers, so I see no reason to have an issue tracking this.

Please send a pull-request per change so we can discuss any side-effects and merits separately without blocking other changes.
