### ISSUE TITLE
Upload large file `Content-Length` Int32 overflow

### ISSUE THREAD

**Issue by 73616c74** [crystal-lang/crystal#7659]
# Summary
I am trying to upload a 5 GibiBytes(`5515055111 Bytes`) file but this problem occurs.

If the full upload is completed, you will get: 
`Content-Length header is 5515055111 but body had 1220087815 bytes (ArgumentError)`

When uploaded to `2521.792672 MegaBytes ≈ 2521792672 Bytes`, you will get: 
`Content-Length header is 5515055111 but body had -1773174624 bytes (ArgumentError)`

Maybe it's Int32 overflow? (I guess).
Update: Yes, I confirm that it is caused by Int32 overflow.

### Crystal - ICR
```text
icr(0.27.2) > 2521792672.to_i32
 => -1773174624
```

# Position
Source of this error: [common.cr#L141](https://github.com/crystal-lang/crystal/blob/60760a5460aa13a1f80c5a1a7410782dc4076b77/src/http/common.cr#L141)

# Problem
```text
Unhandled exception on HTTP::Handler
Content-Length header is 5515055111 but body had -1773174624 bytes (ArgumentError)
  from HTTP::Client#send_request<HTTP::Request>:Bool
  from ~procProc(HTTP::Server::Context, Nil)@src/toucan/relay/server.cr:40
  from HTTP::Server::RequestProcessor#process<IO+, IO+, IO::FileDescriptor>:Nil
  from ~procProc(Nil)@/usr/local/Cellar/crystal/0.27.2/src/http/server.cr:380
  from Fiber#run:(IO::FileDescriptor | Nil)
```

# Screenshot
![螢幕截圖 2019-04-10 01 01 42](https://user-images.githubusercontent.com/46258870/55881578-7d4ef900-5bd5-11e9-9c4e-bc6dc42d35dd.jpg)

**Comment by bcardiff** [comment]
Related to #3209

Once integer overflows are on by default the exception won't be silent at least. (you can compiler with `-D preview_overflow` in 0.27.1)

**Comment by 73616c74** [comment]
@bcardiff Okay.

**Comment by 73616c74** [comment]
@bcardiff Very strange, I am using stream upload, 
but I am experiencing this problem, I found another "temporary" solution.

change [common.cr#L141](https://github.com/crystal-lang/crystal/blob/60760a5460aa13a1f80c5a1a7410782dc4076b77/src/http/common.cr#L140) `if copied != content_length` to `if copied != content_length.to_i32`

Thank you very much, I am looking forward to #3209 problem being solved.

**Comment by asterite** [comment]
I think it's related to the issue about File size but it's not exactly the same. We should probably change `IO.copy` to return `Uint64` too.

**Comment by asterite** [comment]
@73616c74 What happens if you add this?

```crystal
module IO
  def self.copy(src, dst)
    buffer = uninitialized UInt8[4096]
    count = 0_u64
    while (len = src.read(buffer.to_slice).to_i32) > 0
      dst.write buffer.to_slice[0, len]
      count += len
    end
    len < 0 ? len : count
  end
end
```

**Comment by 73616c74** [comment]
No, it prompts: `IO is not a module, it's a class`
I changed it to `abstract class IO` and it worked.
@asterite Okay, the code you provided it worked. 👍

**Comment by asterite** [comment]
Oops, sorry, yeah, it's a `class`.

Cool, I'll send a fix for that soon. I think it's correct.

**Comment by 73616c74** [comment]
@asterite Okay.

**Comment by ChinaHDJ** [comment]
where the icr ???

**Comment by 73616c74** [comment]
@ChinaHDJ Crystal - ICR
```text
$ icr -v
icr version 0.6.0
Author: Potapov Sergey
Homepage: https://github.com/crystal-community/icr
```

**Comment by ChinaHDJ** [comment]
> https://github.com/crystal-community/icr

谢了老哥，
