### ISSUE TITLE
Expose HTTP::Params#to_s encode %20 or +

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#7662]
There is already logic in HTTP::Params to encode back the values with either `%20` or `+` for spaces because of urlencode v.s uri encode standards, but this can't be controlled by the user (unless monky-patching).

The use case is that given a string `a=15&b=a b`, there is only one way to parse it and it's with HTTP::Params regardless of the origin of the string (URI doesn't have a #parse_query method), and because HTTP::Params is used for both forms and queries it makes sense to have some way of doing 
`HTTP::Params.to_s(space_to_plus: true)` (like in URI)

**Comment by petr-fischer** [comment]
I have this problem too.

My main question is, why to have `URI::Params` as a struct - subclassing is disabled now and it's generally a pain in the end. It doesn't make sense to me.

Discussion here: https://forum.crystal-lang.org/t/uri-params-is-a-struct-why/4344
