### ISSUE TITLE
Conditional access to instance variables

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#7677]
_Note: I believe that it's different from #7671._

Currently this code compiles (https://carc.in/#/r/6qcr):

```crystal
module Foo
  def foo
    if self.is_a?(Bar)
      self.@bar
    end
  end
end

class Bar
  include Foo

  def initialize(@bar : String)
  end
end

class Baz
  include Foo
end

pp Bar.new("qux").foo
pp Baz.new.foo
```

But changing `self.@bar` to just `@bar` (https://carc.in/#/r/6qcs) raises:

```
in line 4: Can't infer the type of instance variable '@bar' of Baz
```

What's the "right" behavior in this case?

In my opinion, the example should work without `self`. If so, it's a bug then.

**Comment by bcardiff** [comment]
I don't think `self` is restricted as other variables so far, not 100% sure.

I would go as var as to disallow `self.is_a?` actually. It's a construct that will more likely lead to complex designs.

It's odd that a module to be included in arbitrary classes has knowledge of some of them.

**Comment by vladfaust** [comment]
> It's odd that a module to be included in arbitrary classes has knowledge of some of them.

I agree with you on that. However, it allows to write simpler code when the amount of classes it would be included in is known and limited.

**Comment by asterite** [comment]
> I don't think self is restricted as other variables so far, not 100% sure

Yes, it is. `self` is just a regular variable that can be restricted. But omitting `self` isn't equivalent to calling it explicitly, that's why `self.@bar` works while `@bar` doesn't.

I don't think we need to fix this.
