### ISSUE TITLE
BigDecimal missing ** method

### ISSUE THREAD

**Issue by jzakiya** [crystal-lang/crystal#7680]
Converting this snippet from Ruby to Crystal.

```
require "bigdecimal"
 
LN2 = BigMath::log(2,16) 

def xx(n)
     ...
     2 * LN2  ** (n + 1)
end
```

Because Crystal has no ``**`` and ``log`` methods, I had to do this, which has less precision.

```
require "big"
include Math

LN2 = Math.log(2)

def xx(n)
     ...
     2 * LN2.to_big_d  ** (n + 1)     # can't do, no ** method for BigDecimal
     2 * LN2.to_big_f  ** (n + 1)     # not as much precision (digits) as Ruby
end
```
BigInt and BigFloat have ``**`` while BigDecimal and BigRational don't.

**Comment by Maroo-b** [comment]
Is it possible to possible to add this change using func `pow_ui` from `LibGMP` https://github.com/crystal-lang/crystal/blob/master/src/big/lib_gmp.cr#L81? I saw it's used for `BigInt`

**Comment by jzakiya** [comment]
Commented on correctness of https://github.com/crystal-lang/crystal/pull/7696

**Comment by jwbuiter** [comment]
I'll try my hand at this for my first contribution
