### ISSUE TITLE
Bugs with `protected` and `private` on top-level methods

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#7681]
File `a.cr`:
```cr
{% begin %}
private def method
  "hello"
end
{% end %}
```
File `b.cr`:
```cr
require "./a"

method # => "hello"
```
Expected behavior: a compile error.
This raises an error when the method is not defined in the macro `begin`.
For protected methods it doesn't matter whether it's in a macro `begin` or not, no compile error is raised.

**Comment by j8r** [comment]
Hum, that was @asterite expected, but Crystal doesn't mind files, they aren't creating namespaces like Python's - or this isn't wanted?

**Comment by konovod** [comment]
Doesn't reproduce for me:
```
Error in b.cr:3: undefined local variable or method 'method'

method # => "hello"
```
Crystal 0.27.2

**Comment by r00ster91** [comment]
@konovod Oh apparently it only happens when the method is defined in a macro `begin` for example. I edited the issue.
