### ISSUE TITLE
Crystal can't measure time below 1100 nanoseconds

### ISSUE THREAD

**Issue by TheOnlyArtz** [crystal-lang/crystal#7687]
Hey, I've done a little experiment with a friend where we tried to iterate the biggest number possible and check the time it takes, we go to `UInt128`, it went like:
```cr
iter : UInt128 = 0_u128

start = Time.monotonic
        UInt128::MAX.times {iter += 1}
elapsed = Time.monotonic - start


puts "Time took to iterate #{iter} times => #{elapsed.nanoseconds}"
```
The run took 1100 nanoseconds, I was pretty impressed, I thought it was pretty good, but then a friend ran in on Rust and it took 89 nanoseconds, I thought it's impossible and tried to run the crystal binary again (compiled using --release), I've got 1100 again.. and again, and again.

until eventually, I went down to UInt32 in order to be even "faster" and I still got the same result, 1100 nanoseconds, this must be an issue with Crystal, I tried the `Time.measure` method too and it gave me 1100 at the minimum too!

Runs:
UInt128:
![image](https://user-images.githubusercontent.com/30025874/56323723-74ca6580-6175-11e9-90eb-35e6fd29d5b7.png)

UInt32:
![image](https://user-images.githubusercontent.com/30025874/56323756-86ac0880-6175-11e9-8f6d-d1041d3fe2f2.png)

**Comment by TheOnlyArtz** [comment]
Crystal `0.27.0` btw.

**Comment by asterite** [comment]
What's your OS? And what does running `puts Time.measure { }` with `--release` mode give you? I get times like 54 nanoseconds and 80 nanoseconds.

**Comment by TheOnlyArtz** [comment]
I ran it on a WSL, every time compiled with `--release`, it's Debian.

**Comment by Blacksmoke16** [comment]
Might be something to do with WSL then.  On `Debian` proper, it's around 40-60 ns.

**Comment by straight-shoota** [comment]
This is probably #7377 and already fixed. Please try with 0.28.0

**Comment by TheOnlyArtz** [comment]
> This is probably #7377 and already fixed. Please try with 0.28.0
Yep, it is fixed, thank you :)
