### ISSUE TITLE
Extra Annotation methods

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#7692]
While writing https://github.com/crystal-lang/crystal-book/pull/335, I came across some places that annotations fall a bit short, mainly around positional values.  The `Annotation` macro class could do with some extra methods.

Currently positional arguments can only be accessed if the user knows how many there will be at compile time.  I.e. accessing each one with a `NumberLiteral`.  However this makes it not very useful IMO.

I was thinking of adding:
* size - Would return the total number of arguments on the annotation (positional + named).
  * Would allow for dynamic access of positional args.
    * `{% for idx in 0...Type.annotation(MyAnnotation).size %}`.
    * `idx` could then be used to access the positional value on the annotation.
    * If named arguments were used as well, accessing them would just return `nil`.
* keys - Would return the keys of all named arguments on the annotation.
  * Would allow for reading values off of an annotation in a loop.
* values - Would return all positional values (and maybe named arg values?)
  * Would allow looping over the values themselves, without directly having to read them off the annotation.  Most useful for positional values.

My main concerns are if an annotation has both positional AND named arguments, what should the `values` method return?  Or, how should iterating using `size` work if you have a named argument with the same key as the index?

Possibly could have separate methods for `values`/`size`?  One for positional and another for `named` arguments?

Thoughts?

**Comment by bew** [comment]
A quick thought would be to have a system similar to regular method that accept arbitrary number of pos/named args: with (named)tuple.

For annotation it could look like: `ann.pos_args` & `ann.named_args`, so for:
```cr
@[Foo(1, '2', extra: "three")

# you can do (in macros):
ann = ... get the annotation
ann.pos_args # => {1, '2'}
ann.named_args # => {extra: "three"}
```
The size would simply be `ann.pos_args.size + ann.named_args.size`, etc...

This way you can reuse existing data structure usable from macros! (and that's a big +++)

**Comment by Blacksmoke16** [comment]
I like that, and be returning a namedTuple, you inherently get keys/values/size.  I can make a PR for this later today.

:100:

**Comment by asterite** [comment]
@Blacksmoke16 Why is this useful? (I can see why it's useful, but what use cases do you have in mind?)

**Comment by Blacksmoke16** [comment]
@asterite My initial idea was https://github.com/Blacksmoke16/CrSerializer/issues/8, but it wasn't until I was writing up the annotation docs that I realized that it wouldn't be possible as there was no way to know how many positional arguments there are, or a way to iterate over each one.  

I don't really have any other "omg this would be perfect for x" use cases; it was more so something I just felt was missing and felt like it should be possible.  

However, after trying out having nested annotations within an annotation, that would require work as the compiler thinks they are `GenericType`.  But that can be another PR.

```crystal
annotation Any; end
annotation Foo; end

@[Any(Foo(0), Foo(1))]
class Klass
end

{% for ann in Klass.annotation(Any).pos_args %}
  pp {{ann[0]}}
{% end %}
```
```
Error in test.cr:8: expanding macro

{% for ann in Klass.annotation(Any).pos_args %}
^

in test.cr:9: undefined macro method 'Generic#[]'

  pp {{ann[0]}}
          ^

in test.cr:4: undefined macro method 'Generic#[]'

@[Any(Foo(0), Foo(1))]
```
