### ISSUE TITLE
Ruby's `extend` / `include` is (slightly) different from Crystal's

### ISSUE THREAD

**Issue by asoffa** [crystal-lang/crystal#7693]
In Ruby, `extend` and `include` for modules behave like `require` for files: once a module is extended / included in a module / class, it is not subsequently re-extended / re-included, *even if it is included in another module subsequently included / extended by that module / class*. This is not the case in Crystal, as the example below illustrates. (Note the difference in output for Ruby vs. Crystal.) This difference may be intentional, but I am creating this issue to confirm.

```ruby
module A
  def check
    'A'
  end
end

module B
  def check
    'B'
  end
end

module C
  include A
end

module D
  extend A
  extend B
  extend C
end

x = D.check #=> 'B' (Ruby) vs. 'A' (Crystal)
puts x
```

**Comment by asterite** [comment]
I don't know if it's intentional or not, Crystal just searches from last to first, recursively (C -> A, B, A)

My only comment is that relying on that behavior might not be a good idea. This small example is already pretty confusing!

**Comment by asoffa** [comment]
I agree this sort of design would be a code smell in most cases, and I personally would never write code like this without a good reason for doing so. However, note that the order is *not* last -> first if there is a repeat that occurs that is *not* through recursion, e.g.
```
module A
  def check
    'A'
  end
end

module B
  def check
    'B'
  end
end

module C
  extend A
  extend B
  extend A
end

puts C.check #=> 'B' (both Ruby and Crystal)
```

**Comment by asterite** [comment]
Right, but `A` was already in `C`'s parents so it's not included again. I guess Ruby does the same but for `ancestors` instead of parents. But I have no idea how that algorithm is. Do you happen to know?

(in any case for now I don't think anyone will change this)

**Comment by asterite** [comment]
Also, is there a way to see the path Ruby traverses when searching for methods?

**Comment by asoffa** [comment]
For Ruby's order of method lookup, see
https://makandracards.com/makandra/23171-how-ruby-method-lookup-works
(Note the `prepend` that was added to Ruby 2.0+.)

To see the method search path in Ruby, you can use `#ancestors` method, which returns the list of ancestors.

**Comment by asoffa** [comment]
For Ruby's order of method lookup, see
https://makandracards.com/makandra/23171-how-ruby-method-lookup-works
(Note the `prepend` that was added to Ruby 2.0+.)

To see the method search path in Ruby, you can use the `#ancestors` method, which returns the list of ancestors (though this isn't recursive). You can use the `#included_modules` method to see the list of included modules and `#singleton_class.included_modules` to see the list of extended modules.

**Comment by asterite** [comment]
Another question: is there a benefit to do it the way Ruby does it? Is it more intuitive or is there a specific purpose to it?

**Comment by asoffa** [comment]
I think consistency is the main factor, though this will depend on personal preference. The current behavior isn't a bug *per se*, just a notable difference from how Ruby uses `extend` / `include`. Perhaps a brief (or not so brief if anyone has any major objections) community discussion to gather more input on which behavior is the best option for Crystal? This discussion can be moved into the forums (and this issue can be closed) if the current behavior isn't a "bug."

**Comment by asterite** [comment]
I think Ruby's behavior is pretty confusing.

Consider these two examples:

```ruby
module A
  def check
    'A'
  end
end

module B
  def check
    'B'
  end
end

module Z
  def check
    'Z'
  end
end

module C
  include A
  
  # Here we include Z before doing D.extend C
  include Z
end

module D
  extend A
  extend B
  extend C
end

p D.singleton_class.ancestors
puts D.check
```

Output:

```
[#<Class:D>, C, Z, B, A, Module, Object, Kernel, BasicObject]
Z
```

Now if we extend C first but later reopen C to include Z:

```ruby
module A
  def check
    'A'
  end
end

module B
  def check
    'B'
  end
end

module Z
  def check
    'Z'
  end
end

module C
  include A
end

module D
  extend A
  extend B
  extend C
end

module C
  # Here we include Z *after* doing D.extend C
  include Z
end

p D.singleton_class.ancestors
puts D.check
```

Output:

```
[#<Class:D>, C, B, A, Module, Object, Kernel, BasicObject]
B
```

Proof:
- https://carc.in/#/r/6r56
- https://carc.in/#/r/6r57

So it seems when Ruby finds `extend C` it will go ahead and add C's ancestors to `D`, unless those ancestors already exist in `D`. In the first case it finds `A` but it was already in `D`'s ancestors so it doesn't re-add it.

But Ruby doesn't do anything when you reopen a module that was included/extended somewhere. It misses that now we inserted `Z` in `C`, and that `Z` wasn't in `D` already. 

Ruby probably does this to speed up lookup: if the `ancestors` list is already built and ready, there's no need to do a tree-like lookup, checking each module in order, recursively, to find a method.

Maybe it's something we could do in Crystal too (though I don't know how much of a speed up that will be, probably insignificant).

I think changing behavior depending on the order of which you include extend things, despite the fact that in the end the resulting hierarchy ends up being the same, is something I personally dislike about Ruby's behavior (which I learned thanks to you).

What do you think? Do you like it? Do you think it's intuitive?

**Comment by asterite** [comment]
(Another reason Ruby might be doing this is to avoid including a module, for which you know the hierarchy when you are including it, and later prevent someone to keep including things in that type and have it affect your "main" type... maybe we can ask Matz or nobu? ^_^)

**Comment by asoffa** [comment]
Interesting, so modifying an included module after the fact in Ruby does *not* in fact change it globally (in a manner similar to `require` for files) if the modification is via `include`. Especially after seeing that last example above, I find this unintuitive and would prefer (for consistency) a global update with module 'C' being the same module everywhere. That aspect is something Crystal (unlike Ruby) gets right.

As you mention, Crystal's current module lookup is by paths, e.g. D -> C -> A is distinct from D -> A, even though both paths end at the same module A. This is in contrast to `require` for files, where `require`d code gets "flattened" (so that there is no lookup by paths). This is reasonable if you view `include` as "giving" methods a module (though with the included module still having a handle on them), so I think the current behavior is fine as long the understanding of `include` is such that D -> C -> A means D -> (C -> A) with (C -> A) being thought of as just C.

**Comment by asoffa** [comment]
Closing, as Crystal's current `extend` / `include` are consistent (even more so than Ruby's).

**Comment by asoffa** [comment]
It turns out there is a discussion about making Ruby's `extend` / `include` behave as in Crystal: https://bugs.ruby-lang.org/issues/9112. Matz / Nobu mention that the current behavior in Ruby is indeed for performance reasons, though this may eventually be fixed now that Ruby has subclass trees.

**Comment by asoffa** [comment]
See also: https://www.ruby-forum.com/t/include-is-not-working-when-re-opening-the-module/239794
