### ISSUE TITLE
Scrolling API docs works very poorly on iPad/iOS

### ISSUE THREAD

**Issue by willhbr** [crystal-lang/crystal#7729]
I do most of my Crystal tinkering on an iPad, which means I'm reading API docs in Safari on iOS a lot. I very frequently find that when I scroll down the page, the whole document body moves upwards rather than the content panel, which means I can't read more of the documentation (which means I have to guess how things work ;) ).

Hopefully this screenshot helps somewhat, this is what it looks like while I'm scrolling up (in the direction of the arrow). It snaps back to the original position when I let go.

![IMG_0189](https://user-images.githubusercontent.com/710254/57017068-c0ded500-6c60-11e9-8386-0dd10e5411b2.jpeg)

This obviously doesn't happen when using a trackpad/mouse. I don't have another touch-enabled non-iOS device to verify this on, if it also happens in Windows with a touchscreen that's probably the easiest OS to debug this on as you've got a real browser.

If someone can fix this, being able to read docs on my iPad would make me very happy :)

**Comment by wontruefree** [comment]
I don't really see this on my iPhone.  I only see this when I scroll beyond the bottom of the screen.  Do you have any steps to reproduce?

**Comment by straight-shoota** [comment]
Might be interesting to know the exact iOS and Safari versions.

**Comment by willhbr** [comment]
@wontruefree Just tried it on my phone, it only has this behaviour when you request the desktop site via the share sheet. On an iPad I am able to reproduce by going to any page longer than one screen (like the [`Array` docs](https://crystal-lang.org/api/0.28.0/Array.html)) and trying to scroll down.

@straight-shoota FWIW I have had this problem for a while but never got around to filing a bug. Currently seeing this on a 2018 13" iPad Pro running the latest stable version of iOS & Safari (I'll get exact version numbers this evening). I've also had the problem on the 2015 13" iPad Pro, running iOS 11 beta through to iOS 12.

**Comment by willhbr** [comment]
This seems to have been fixed (either by iOS updates or some other change to the doc generator) - I've been happily scrolling docs on my iPad for a while.
