### ISSUE TITLE
Automatic casting of symbols to enums broken within blocks

### ISSUE THREAD

**Issue by epoch** [crystal-lang/crystal#7736]
There is a bug with automatic casting of symbols to enum values when using with self yield in a block. 

Reproducible example:
```crystal
enum BorderSide
  Top
  Bottom
end

class Table
 
  def config
    with self yield
  end

  def row(border : BorderSide)
    "bar"
  end
end

Table.new.config do
  row(border: :top)
end
```

with this error
`undefined method 'row' for Table (with ... yield) and top-level (current scope)`

its works fine when `BorderSide::Top` is used
```crystal
Table.new.config do
  row(border: BorderSide::Top)
end
```

**Comment by straight-shoota** [comment]
This is most likely related to `with ... yield`, not blocks in general.
