### ISSUE TITLE
memset intrinsics signature is wrong

### ISSUE THREAD

**Issue by bew** [crystal-lang/crystal#7740]
https://github.com/crystal-lang/crystal/blob/0ed60acfad6df5ce441b752f35f5a2a3b1139857/src/intrinsics.cr#L6
https://github.com/crystal-lang/crystal/blob/0ed60acfad6df5ce441b752f35f5a2a3b1139857/src/intrinsics.cr#L10

VS

https://llvm.org/docs/LangRef.html#llvm-memset-intrinsics

```llvm
declare void @llvm.memset.p0i8.i32(i8* <dest>, i8 <val>, i32 <len>, i1 <isvolatile>)
declare void @llvm.memset.p0i8.i64(i8* <dest>, i8 <val>, i64 <len>, i1 <isvolatile>)
```

The signature we have has an additional `align` param.

(LLVM docs says that the alignment can be specified with parameter attributes (if needed?))

(could maybe fix #7293 ?)

**Comment by RX14** [comment]
This was a change in signature made in LLVM7, which we don't support. See #6754.

**Comment by bew** [comment]
Oh right, didn't remember that :/
