### ISSUE TITLE
Elements of two-dimensional StaticArray are immutable

### ISSUE THREAD

**Issue by malte-v** [crystal-lang/crystal#7749]
`$ crystal --version`
```
Crystal 0.28.0 (2019-04-17)

LLVM: 6.0.1
Default target: x86_64-pc-linux-gnu
```

Consider the following program:
```cr
a = StaticArray["hello", "world"]
b = StaticArray[a, a]

puts "one-dimensional:"
puts "before: #{a}"
a[0] = "bye"
puts "after: #{a}"

puts

puts "two-dimensional:"
puts "before: #{b}"
b[0][0] = "bye"
puts "after: #{b}"
```

Output:
```
one-dimensional:
before: StaticArray["hello", "world"]
after: StaticArray["bye", "world"]

two-dimensional:
before: StaticArray[StaticArray["hello", "world"], StaticArray["hello", "world"]]
after: StaticArray[StaticArray["hello", "world"], StaticArray["hello", "world"]]
```

As you can see, everything works as expected in the first example. However, if we use a two-dimensional array, we are unable to change the data once it has been initialized. This is the case regardless of the data type.

Any idea what could cause this?

**Comment by asterite** [comment]
`StaticArray` is a struct, and so it's passed by value. When you do `b[0]` you get a **copy** of the static array, which you then modify.

**Comment by malte-v** [comment]
I already thought I was missing something obvious. Thanks for helping me out.

**Comment by malte-v** [comment]
Sorry for reopening but I can't find a good way to solve my problem. I have a `Mat4` type which is defined as follows:
```cr
alias Vec4 = Float32[4]
alias Mat4 = Vec4[4]
```
Now I want to negate the element at row 2, column 2. In C I just do
```c
mat[1][1] *= -1;
```
which works because arrays are basically glorified pointers.
In Crystal this doesn't work for the reason @asterite explained above. My first approch was
```cr
mat_1 = mat[1]
mat_1[1] *= -1
mat[1] = mat_1
```
This worked but I found it too complicated and inefficient.
The "if it works, it works"-style solution is:
```
Pointer(Float32).new(mat.to_unsafe.address + 1*sizeof(Float32[4]) + 1*sizeof(Float32)).value *= -1
```
This certainly is efficient, but it's unreadable, ugly and unsafe. What's the correct way to do this in Crystal?

**Comment by asterite** [comment]
Can't you not use `StaticArray`? That type mostly exists to represent byte buffers but it's super inconvenient in almost every other case.

**Comment by malte-v** [comment]
I'm using these types with a vector math library called CGlm (which uses arrays rather than structs) so I'm forced to use `StaticArray` or pointers.

**Comment by straight-shoota** [comment]
You could make `Mat4` not be an alias but a distinct type which implements abstractions for manipulating data in the static array.

**Comment by asterite** [comment]
Well, an `Array` uses pointers internally, you can call `to_unsafe` to get a pointer that points to the array's buffer.

My suggestion is to implement `Vec4` and `Mat4` as separate types:
- `Vec4` can still be `StaticArray(Float32, 4)` if you really need that, or it can be a struct backed by that
- `Mat4` can be a struct wrapping `StaticArray(Flaot32, 16)` and you would provide methods for reading/writing stuff at position x, y, like `mat[x, y]` and `max[x, y] = z`.

**Comment by asterite** [comment]
(then to pass that to the C library you call `to_unsafe` on the underlying static arrays)

**Comment by malte-v** [comment]
I like the idea of having structs wrap the `StaticArray`s so they are still pass-by-value. Thanks for your suggestions!
