### ISSUE TITLE
Crystal Playground Share As GitLab Snippet

### ISSUE THREAD

**Issue by irlcatgirl** [crystal-lang/crystal#7751]
The Crystal Playground allows you to provide a GitHub Access token and share your code as a GitHub Gist. This is great for collaboration in open source circles.  In some enterprise environments, particularly when working with company code / company data it may be desirable to keep snippets on the company's GitLab Instance to keep access restricted. This feature would allow a user to provide a GitLab Instance URL and an Access Token to create a snippet with the shared code. Thoughts?

**Comment by straight-shoota** [comment]
Closing for lack of responses. I think the playground isn't really used that much, and its code sharing feature even less so.

It may still be a valuable enhancement, it just doesn't make sense to track this if nobody's interested. This issue can be re-opened if someone wants to take a stab at this.
