### ISSUE TITLE
Crypto::Bcrypt::Password#== is not commutative

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#7753]
As discussed [in the forums](https://forum.crystal-lang.org/t/using-crypto-password-for-authentication/743?u=asterite), it's a bit unintuitive that given `password : Crypto::Bcrypt::Password` and `string : String`, `password == string` will work but `string == password` won't.

Two solutions:
1. Add an overload `String==#(other : Crypto::Bcrypt::Password)` so it's commutative
2. Use a different method name. Ruby's BCrypt uses `is_password?` as an alias, but `verify`, `check` or `matches?` might be equally good.

I'm not sure which approach is better. I think the second one is better because it's also more type-safe. You can do `password == 1.23` and it will still compile, but it's obviously incorrect. You can even do `password == password` and it will return true, but it makes little sense.

Thoughts?

**Comment by Sija** [comment]
`Crypto::Bcrypt::Password#matches?(string)` reads pretty good.

**Comment by RX14** [comment]
I don't mind the overridden `==`, I'd just make it commutative

**Comment by asterite** [comment]
The problem with `==` is that you can basically pass anything, an int, a float, a bool, to `==` and it will compile, but it won't give the correct result. That makes it not type safe. And here we aren't really comparing stuff, we want to know if a password matches an encoded version of it, which isn't exactly "equality".

**Comment by oprypin** [comment]
Could just apply the {% raise %} to the current state. Doesn't remove the confusion but adds type safety.
https://github.com/crystal-lang/crystal/issues/7753#issuecomment-490471772

**Comment by straight-shoota** [comment]
The concept of a password matching an encoded version would probably be better encoded in the `=~` operator. But it's not type safe either and commutativity isn't really necessary anyway.

So, using a dedicated method is IMO the best solution.
And I'd go with `#verify` for that.

@Sija The `?` suffix is not used to indicate a `Bool` return type, but specifically a predicate method. `#verify` is more an action than a predicate. If we wanted to use a predicate, it would be `#verifies?`. But I think an action term fits better here.

**Comment by ysbaddaden** [comment]
Let's go with `#verify?` with or without the question mark.
