### ISSUE TITLE
Using a dot in the title when creating a new project

### ISSUE THREAD

**Issue by oruruby** [crystal-lang/crystal#7763]
I'll creating new project with
`crystal init app foo.bar`,

This will generate file with name _foo.bar.cr_ with the following contents
_module Foo.bar
end_

compiler sends
`unexpected token: .`

I think it would be more correct to choose one of the following variants of generations:

`Foo::Bar`
`Foobar`
`Foo`
etc

**Comment by ysbaddaden** [comment]
Or refuse anything that isn't a sound shard name, as per the [spec](https://github.com/crystal-lang/shards/blob/master/SPEC.md#name)? which... doesn't actually specifies that the name must be alphanumeric —it's only implicit.

**Comment by oruruby** [comment]
Thanks for the tip

**Comment by ysbaddaden** [comment]
No, thanks for reporting, that's something I didn't think of.

It could be helpful to validate the naming and properly report a problem, since we use it for the folder but also as namespace, which led to the issue you met.
