### ISSUE TITLE
Initialization failure when in {% begin %} {% end %}

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#7767]
Instance variables initialized within `{% begin %} {% end %}` does not compile.  

https://play.crystal-lang.org/#/r/6wbt

```cr 
struct Foo
  @value : Int32
  
  def initialize
    {% begin %}
      @value = 5
    {% end %}
  end
end
```

```
Error in line 2: instance variable '@value' of Foo was not initialized directly in all of the 'initialize' methods, rendering it nilable. Indirect initialization is not supported.
```

**Comment by asterite** [comment]
Not a bug, macros are analyzed on method instantiation. There's a similar bug report (which is not a bug to me) if you search something like initialize macro.

**Comment by ayazhafiz** [comment]
It looks like initialization in a macro is [not possible without `{{@type}}`](https://github.com/crystal-lang/crystal/issues/2731#issuecomment-405552915). So this will work:

```crystal
struct Foo
  @value : Int32
  
  def initialize
    {{@type}}
    {% if true %}
      @value = 5
    {% end %}
  end
end
```

[Playground](https://play.crystal-lang.org/#/r/6wc6)
