### ISSUE TITLE
Dir.glob doesn't hide hidden files in non-recursive directories

### ISSUE THREAD

**Issue by ayazhafiz** [crystal-lang/crystal#7769]
As per [this reddit thread](https://www.reddit.com/r/crystal_programming/comments/bn8ij8/dirglob_with_match_hidden_somehow_not_working/), calling `Dir.glob` on a non-recursive directory matches hidden files even if `match_hidden` is set to false.

```crystal
# both have the same output
Dir.glob("*", match_hidden: true)
Dir.glob("*", match_hidden: false)
```

[Playground](https://play.crystal-lang.org/#/r/6w66)

Crystal version:

```bash
Crystal 0.28.0 (2019-04-24)

LLVM: 6.0.1
Default target: x86_64-apple-macosx
```

---

It looks like this is caused by not checking if the `match_hidden` option is false in the EntryMatch case of Glob.run:

https://github.com/crystal-lang/crystal/blob/639e4765f3f4137f90c5b7da24d8ccb5b0bfec35/src/dir/glob.cr#L166-L170

Adding the line that skips hidden matches in the RecursiveDirectory case before `yield` seems to resolve this issue:

https://github.com/crystal-lang/crystal/blob/639e4765f3f4137f90c5b7da24d8ccb5b0bfec35/src/dir/glob.cr#L222

**Comment by bcardiff** [comment]
Thanks @ayazhafiz! Would you be willing to send a PR with a spec since you already have a fix?

**Comment by ayazhafiz** [comment]
For sure.
