### ISSUE TITLE
Rename File::DEVNULL to File::NULL

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#7772]
The current name of [`File::DEVNULL`](https://crystal-lang.org/api/0.28.0/File.html#DEVNULL) is really Windows unfriendly. I think now that Windows support is somewhat close, the standard library should become more platform-unspecific with the terms used.
I propose to simply rename it to `File::NULL` just like in Ruby. It's shorter, simple and also nicer for people who switch from Ruby to Crystal.

**Comment by j8r** [comment]
Or something like `File::VOID`, to emphasize even more the fact that the data will be sent to a black hole.
The pros of `File::NULL` is its known for those coming from Ruby, and familiar for those from UNI*X.

**Comment by r00ster91** [comment]
I went with `File::NULL` because UNIX's file null has "null" in it and Windows's file null is named after the word, just one "l" is missing.
