### ISSUE TITLE
can't restrict Nil.class to String | ::Nil

### ISSUE THREAD

**Issue by Austaras** [crystal-lang/crystal#7779]
whether
``` crystal
def func(p : String? = Nil)
  p
end

func
```
or
``` crystal
def func(p : String | Nil = Nil)
  p
end

func
```
cannot compile and get error in title.

**Comment by jhass** [comment]
That's because `nil.is_a?(Nil)`, but `Nil.is_a?(Class)` and `!Nil.is_a?(Nil)`. Use `p : String? = nil`.

**Comment by Blacksmoke16** [comment]
This is because you're assigning the class `Nil` as default argument instead of actual value of `nil`.

```crystal
def func(p : String? = Nil)
  p
end

func # => nil
```

If you want the default to be actual type `Nil` then you have to do
```crystal
def func(p : String.class | Nil.class = Nil)
  p
end

func
```
