### ISSUE TITLE
Default compiler flags (or cli options)

### ISSUE THREAD

**Issue by bcardiff** [crystal-lang/crystal#7805]
I would like to be able to run the compiler specs against some specific flags.
This would help to test some opt-in features behind flags (overflow, mt, etc).

1. I would like to agree on the scope:
  1.a) This change could be either be scoped only the compiler_specs (changing https://github.com/crystal-lang/crystal/blob/0.28.0/spec/spec_helper.cr#L160) or,
  1.b) to the whole compiler (changing https://github.com/crystal-lang/crystal/blob/0.28.0/src/compiler/crystal/compiler.cr#L198).

2. I would like to agree on the interface
  2.a) Use an env variable like `CRYSTAL_COMPILER_FLAGS` that will contain a space separated list of flags to be used.
  2.b) Use an env variable to mimic any CLI option of the compiler via an env variable like `CRYSTAL_COMPILER_OPTS`. The implementation will need to parse them (instead of just split spaces).

I would be happy with 1.b + 2.a.

**Comment by asterite** [comment]
Does this need to be in the compiler or in the spec suite? You can probably do `bin/crystal spec spec/compiler_spec.cr -Dflag1 -Dflag2`, right? And that can be simplified/manipulated in a Makefile, I think.

**Comment by bcardiff** [comment]
I want to inject the flags in the `Crystal::Compiler` instances that are created in the compiler_specs. Your snippet will affect the compiled suite, but not each test.

**Comment by asterite** [comment]
Oooh... I see.
