### ISSUE TITLE
FileUtils.cp_r missing use case

### ISSUE THREAD

**Issue by mare-imbrium** [crystal-lang/crystal#7816]
This is not the same as https://github.com/crystal-lang/crystal/issues/5983 which is asking for a directory not to be created if it exists.

It is quite common in the shell to type:
`cp -r ../adir .`
The destination is given as "." and "adir" is created in the destination given.

Similarly in ruby the following two work:
```
require "fileutils"
FileUtils.cp_r("../adir", Dir.pwd)

```
or
`FileUtils.cp_r("../adir", ".")
`
In both cases, "adir" is created in the current directory.

However, in Crystal the same gives an error of "Unable to create directory. File exists"

```
require "file_utils"
FileUtils.cp_r("../adir", Dir.current)

```
I am saying something like (untested)::
```
      if File.directory?(source) && File.exists?(target)
        target = File.join(target, File.basename(source))
      end
```
If the target directory exists, then create the source directory within the target.

Based on discussion on reddit: https://www.reddit.com/r/crystal_programming/comments/brdx5k/clarification_on_fileutilscp_r/

_crystal v0.28_

**Comment by straight-shoota** [comment]
There's no error anymore, but the behaviour doesn't seem correct either. `FileUtils.cp_r("../adir", ".")` does not copy `../adir` but the contents of `../adir`:
```cr
require "file_utils"

Dir.mkdir("adir")
Dir.mkdir("pwd")
File.write("adir/file.txt", "")

Dir.cd("pwd")
FileUtils.cp_r("../adir", Dir.current) 

File.exists?("file.txt") # => true
File.exists?("adir")     # => false
```
