### ISSUE TITLE
Allow passing any type to `map!`

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#7823]
```cr
array = [1, 2, 3]
array.map! { |number| number.to_s } # => Error!
```
This does not work because the values returned by the `map!` block are of type `String`, not `Int32` which means I would have to use `map` which will allocate a **new** array of type `String`.
But I feel like we could reuse the already existing array and just make it compatible by casting its type instead of throwing it away. So `map!` should accept any type, like `map`. Maybe `unsafe_as` is useful for this.

Doing this would make it possible to use `map!` in more places (which is always a good thing because no new array is created) where the previous state of the array is not of interest.

This works:
```cr
array = ([] of Int32).unsafe_as(Array(String))

array << "hello"

puts array # => ["hello"]
```
But it's more tricky when the array already contains something, perhaps a special language construct needs to be added.

**Comment by asterite** [comment]
Nope, it's impossible. You can't change the type of a variable.

**Comment by asterite** [comment]
Imagine someone keeps a reference to that Array. Suddenly the array changes of type! Segfault comes next, or undefined behavior.
