### ISSUE TITLE
Steal Object#present?/blank? and #presence from ActiveSupport

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#7824]
I'd like to suggest including implementation of `Object#present?`, `Object#blank?` and `Object#presence` [found](https://blog.arkency.com/2017/07/nil-empty-blank-ruby-rails-difference/) in Rails' ActiveSupport.

These are ones of the few extensions from AS I'm finding extremely handy in every-day coding - similarly to `Time::Span#ago`.

If agreed on, I'd happily open a PR.

**Comment by j8r** [comment]
This remind me `be_truthy` and `be_falsy` of spec, but with a less explicit name.

**Comment by straight-shoota** [comment]
I don't think we'll add this to the stdlib.

See https://github.com/crystal-lang/crystal/pull/2413#issuecomment-205446575 and #1299 for previous discussions.

**Comment by kostya** [comment]
https://github.com/kostya/blank
