### ISSUE TITLE
Colorize: Add support for HSL colors

### ISSUE THREAD

**Issue by alexherbo2** [crystal-lang/crystal#7842]
How about supporting [HSL colors]?

[HSL colors]: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#HSL_colors

**Comment by oprypin** [comment]
How about not?

**Comment by girng** [comment]
what do you mean "support"? can't the developer just use the   values (`hsl(120, 100%, 0%)`) in a string to create their color

**Comment by jhass** [comment]
I think they're talking about adding `Colorize::ColorHSL` akin to `Colorize::ColorRGB`.

**Comment by oprypin** [comment]
Yes, that is what everyone assumed. It just definitely has no place in the standard library.

**Comment by HertzDevil** [comment]
This is one possible implementation:

```crystal
require "colorize"

def hsl(h, s, l)
  # https://en.wikipedia.org/w/index.php?title=HSL_and_HSV&oldid=1068256614#HSL_to_RGB
  c = (1.0 - (2.0 * l - 1.0).abs) * s
  h_prime = h.to_f % 360.0 / 60.0
  x = c * (1.0 - (h_prime % 2.0 - 1).abs)
  m = l - c / 2.0

  rgb = case h_prime.floor
        when 0 then {c, x, 0}
        when 1 then {x, c, 0}
        when 2 then {0, c, x}
        when 3 then {0, x, c}
        when 4 then {x, 0, c}
        else        {c, 0, x}
        end

  Colorize::ColorRGB.new(*rgb.map { |x| ((x + m) * 255).clamp(0.0, 255.0).to_u8! })
end

(0..360).step(10) do |h|
  print "foo".colorize.fore(hsl(h, 0.8, 0.6)).back(hsl(h + 90.0, 0.3, 0.2))
end
puts
```

![Screenshot_20220129_003542](https://user-images.githubusercontent.com/1361918/151585689-03cac34b-ef8a-43d4-a40c-b81407e453f7.png)

HSL colors are not part of any standard ANSI escape sequences, so they are beyond the scope of `Colorize`.

**Comment by straight-shoota** [comment]
I suppose it wouldn't necessarily hurt to add a constructor `ColorRGB.hsl`. But I don't expect it would be used very much.
A custom conversion method is easy to implement in user code if necessary.

**Comment by oprypin** [comment]
I think it's best to close this issue. This is indeed out of scope for standard library.

Hopefully there's some shard for color spaces (otherwise just obtain something like the code snippet above) and then indeed you can just convert anything to RGB and pass that in the end.
