### ISSUE TITLE
[Documentation - Crystal Tutorial] Supported versions of LLVM?

### ISSUE THREAD

**Issue by rubyFeedback** [crystal-lang/crystal#7844]
Hello crystal developers,

The main Tutorial at: 

https://crystal-lang.org/reference/installation/from_source_repository.html

Currently mentions this:

"Make sure a supported LLVM version is present in the path. Currently, Crystal supports LLVM 3.8, 3.9, 4.0, 5.0 and 6.0. When possible, use the latest one."

I have compiled llvm 8.0.0. Could the documentation mention whether crystal presently runs on llvm 8.0.0 as well - and if not, could this also be mentioned?

Reason why I ask: I'd like to install crystal, but before I go through it I'd prefer to know whether this may work or not, as getting to install it takes some time, so this would be helpful for me to know (and perhaps to others, too). Thanks for reading!

**Comment by asterite** [comment]
It's not supported. Only the versions listed there are supported.

**Comment by ysbaddaden** [comment]
We don't support LLVM 7 and later. There are some patches to support LLVM 7 but incomplete (issues with raising exceptions).
