### ISSUE TITLE
HTTP::Client.get incorrectly strips certain bytes

### ISSUE THREAD

**Issue by robindar** [crystal-lang/crystal#7848]
Bytes 0x80 through 0xff are stripped by HTTP::Client.get .
I believe this is incorrect behavior, but correct me if I'm wrong

## Reproducing the bug

```
# foo.cr
require "http"

File.open("result", "w") do |f|
  f.print HTTP::Client.get("localhost:8080/hexdata").body
end
```

File generation, server setup, and comparison with curl :

```
$ for i in {0..255}; do printf "\\$(printf %03o "$i")"; done > hexdata
$ ruby -run -e httpd . 2>/dev/null &
$ crystal foo.cr && diff result hexdata ; echo $?
Binary files result and hexdata differ
1
$ curl -s localhost:8080/hexdata > result && diff result hexdata ; echo $?
0
```

## Version information

```
$ crystal -v
Crystal 0.28.0 (2019-04-07)

LLVM: 6.0.1
Default target: x86_64-pc-linux-gnu
```

## Full output

```
$ crystal foo.cr
$ xxd -plain -c16 hexdata
000102030405060708090a0b0c0d0e0f
101112131415161718191a1b1c1d1e1f
202122232425262728292a2b2c2d2e2f
303132333435363738393a3b3c3d3e3f
404142434445464748494a4b4c4d4e4f
505152535455565758595a5b5c5d5e5f
606162636465666768696a6b6c6d6e6f
707172737475767778797a7b7c7d7e7f
808182838485868788898a8b8c8d8e8f
909192939495969798999a9b9c9d9e9f
a0a1a2a3a4a5a6a7a8a9aaabacadaeaf
b0b1b2b3b4b5b6b7b8b9babbbcbdbebf
c0c1c2c3c4c5c6c7c8c9cacbcccdcecf
d0d1d2d3d4d5d6d7d8d9dadbdcdddedf
e0e1e2e3e4e5e6e7e8e9eaebecedeeef
f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff
$ xxd -plain -c16 result
000102030405060708090a0b0c0d0e0f
101112131415161718191a1b1c1d1e1f
202122232425262728292a2b2c2d2e2f
303132333435363738393a3b3c3d3e3f
404142434445464748494a4b4c4d4e4f
505152535455565758595a5b5c5d5e5f
606162636465666768696a6b6c6d6e6f
707172737475767778797a7b7c7d7e7f
```

**Comment by oprypin** [comment]
I'm pretty sure it's about the fact that you're forcing an invalid UTF string to appear, using `resp.body` which is `resp.body_io.gets_to_end`.

Instead try `IO.copy(resp.body_io, writeable_file_object)`

**Comment by oprypin** [comment]
Also I couldn't reproduce your example (on Arch Linux), I get result = hexdata

**Comment by robindar** [comment]
Oh sorry, ruby serves `Content-Type: applcation/octet-stream` by default, renaming `hexdata` to `hexdata.txt` sends `Content-Type: text/plain` and reproduces this behavior, I hadn't checked that header.
Anyway, your guess was correct, using body_io fixes the issue by not using an intermediate String, and this behavior of silently ignoring invalid characters when parsing as a String is actually well documented. This happened to me when parsing Ubuntu's bittorrent tracker's reponse which uses `text/plain`, but I guess it's a server-side error, so I'm closing the issue. Thanks for the help with that
