### ISSUE TITLE
OptionParser: Add support for long options with single dash

### ISSUE THREAD

**Issue by alexherbo2** [crystal-lang/crystal#7861]
**Example**

``` sh
mpv -shuffle .
```

**Comment by sudo-nice** [comment]
That would trouble stacking several short options together (possibly future feature):
`foo -a -b -c` -> `foo -abc`

**Comment by Sija** [comment]
IMO very, very, **very** bad idea. It would go against all established common idioms, and the only piece of software which does that is Java. Not sth we'd like to follow IMO.

**Comment by refi64** [comment]
In most languages that offer this, it's optional and comes with special behavior (most notably, you can type only part of the option and it'll automatically expand to the full one). Most notably, I believe Go uses this rule by default.

**Comment by straight-shoota** [comment]
I don't think we'll add this to `OptionParser`. You can always roll your own option parsing mechanism which supports single dash long options.

**Comment by girng** [comment]
just create your own parser/method to support this for your usecase, by using `ARGV`

**Comment by Sija** [comment]
Shall we close it?
