### ISSUE TITLE
Code compiling with 0.29.0 on LLVM 6.0.1 but not 3.9.1

### ISSUE THREAD

**Issue by taylorthurlow** [crystal-lang/crystal#7870]
When compiling a particular crystal program using crystal `0.29.0` available from Homebrew, there are no issues. That build uses LLVM `6.0.1`. Using the tarball provided in the GitHub release for `0.29.0`, which was compiled with LLVM `3.9.1`, I get an error. Here's a sequence of commands to illustrate the problem:

~~~
╭─taylor@cintra ~/Code/thicket Crystal system ‹develop*› 
╰─$ crystal -v
Crystal 0.29.0 (2019-06-06)

LLVM: 6.0.1
Default target: x86_64-apple-macosx

╭─taylor@cintra ~/Code/thicket Crystal system ‹develop*› 
╰─$ crystal build --release src/runner.cr -o bin/thicket

╭─taylor@cintra ~/Code/thicket Crystal system ‹develop*› 
╰─$ crenv local 0.29.0                                  

╭─taylor@cintra ~/Code/thicket Crystal 0.29.0 ‹develop*› 
╰─$ crystal -v                                          
Crystal 0.29.0 (2019-06-05)

LLVM: 3.9.1
Default target: x86_64-apple-macosx

╭─taylor@cintra ~/Code/thicket Crystal 0.29.0 ‹develop*› 
╰─$ crystal build --release src/runner.cr -o bin/thicket
Assertion failed: (cast<DISubprogram>(Scope)->describes(MF->getFunction())), function getOrCreateRegularScope, file /var/cache/omnibus/src/llvm/llvm-3.9.1.src/lib/CodeGen/LexicalScopes.cpp, line 159.
/Users/taylor/.anyenv/envs/crenv/versions/0.29.0/bin/crystal: line 103: 52413 Abort trap: 6           "$INSTALL_DIR/embedded/bin/crystal" "$@"
~~~

Is this something I'm doing wrong or not understanding?

**Comment by RX14** [comment]
We shouldn't still be using such an old llvm version.

@bcardiff maintains the OSX tarballs

**Comment by wontruefree** [comment]
Should new deployments of Crystal remove support or older llvm compilers?

**Comment by jwoertink** [comment]
I installed crystal through both brew and [asdf](https://asdf-vm.com/#/), and it locked me in to LLVM 3.9.1. 

Here's a small example showing this output:

```crystal
command = "touch app.cr && crystal build --release app.cr"
process = Process.run(command, shell: true, output: IO::Memory.new, error: STDERR)
```
> Assertion failed: (cast<DISubprogram>(Scope)->describes(MF->getFunction())), function getOrCreateRegularScope, file /var/cache/omnibus/src/llvm/llvm-3.9.1.src/lib/CodeGen/LexicalScopes.cpp, line 159.
--: line 1: 68570 Abort trap: 6           crystal build --release app.cr

I agree with the remove support for older ones. I seem to also have 4, 5, and 6 installed locally, but I'm not sure how to tell crystal to use one of those versions.

**Comment by jhass** [comment]
Did we update LLVM yet, I think so, no?

**Comment by bcardiff** [comment]
Darwin tar.gz tarballs ships llvm 6.0.1 since Crystal 0.30.0. Hombrew currently uses llvm 10

The compiler codebase still has reference and supposed support for older llvm but they are not checked by any CI.

For the record, you can't tell to a shipped crystal compiler which llvm to use, that is only available when building the compiler itself.
