### ISSUE TITLE
Duplicate syscall definitions

### ISSUE THREAD

**Issue by didactic-drunk** [crystal-lang/crystal#7880]
Many of the platform specific definitions are identical with 0 variation.
```
src/lib_c/aarch64-linux-gnu/c/unistd.cr:34:  fun getpid : PidT
src/lib_c/aarch64-linux-musl/c/unistd.cr:34:  fun getpid : PidT
src/lib_c/arm-linux-gnueabihf/c/unistd.cr:28:  fun getpid : PidT
src/lib_c/i386-linux-gnu/c/unistd.cr:34:  fun getpid : PidT
src/lib_c/i386-linux-musl/c/unistd.cr:34:  fun getpid : PidT
src/lib_c/x86_64-darwin/c/unistd.cr:34:  fun getpid : PidT
src/lib_c/x86_64-freebsd/c/unistd.cr:33:  fun getpid : PidT
src/lib_c/x86_64-linux-gnu/c/unistd.cr:34:  fun getpid : PidT
src/lib_c/x86_64-linux-musl/c/unistd.cr:34:  fun getpid : PidT
src/lib_c/x86_64-openbsd/c/unistd.cr:34:  fun getpid : PidT
```

This level of duplication is prone to error over time and a headache small headache for anyone adding/removing/COMPARING library definitions as it is not immediately obvious which API's are platform agnostic and which have local differences.

Instead of duplicating everything common include files with the most common standard functions could be used optionally with os or architecture specific files as needed.

Platforms could
```
# Whatever the chosen file structure ends up as.
require "../posix/unistd"
require "../common/unistd"
require "../linux-common/unistd"
require "../shared/freebsd-unistd"
```

Some platforms have OS specific (Linux/BSD) or architecture specific definitions (32/64).

`src/lib_c/aarch64-linux-gnu/c/foo.cr` would start to look like
```
# Made up example for complicated definitions.
require "../posix/c/foo"
require "../linux/c/foo"
require "../linux_64/c/foo"

# GNU aarch64 Linux defines follow.
lib libC
  fun foo(Int64)
end
```

I suspect for most cases there would be 1-2 requires or none at all for windows.   > 95% of unistd.cr is identical between unixalikes with superfluous argument name difference or hex vs octal defines.

`diff -ur i386-linux-musl/c/unistd.cr x86_64-unknown-freebsd/c/unistd.cr`
```
-  R_OK                =  4
+  R_OK       = 0x04
-  fun fdatasync(x0 : Int) : Int
+  fun fdatasync(fd : Int) : Int
```

Some of the other platform specific files may vary with every function and have nothing except their own definitions.  (The way it is now).

**Comment by oprypin** [comment]
The files are generated, though. Manually maintaining a "database of similarities" is only more work.

Wait, are they actually generated? Well, even if not, it still can be nicer towards any potential tooling.

**Comment by straight-shoota** [comment]
No, they're not automatically generated. But that's a possibility at some point.

Anyway, duplication is not really an issue here. Having all bindings for a platform in one place is way easier than the complexity of extracting common definitions.

**Comment by j8r** [comment]
Partially is a more appropriate word. Parts of them were made based on the output of tools like [crystal_lib](https://github.com/crystal-lang/crystal_lib), and others mostly manually.

That's why in some places there are `x0`, `x1` function arguments, and others proper words like `file`, `path`.

**Comment by asterite** [comment]
They were initially generated. I think we should continue to do that, but also it's easier to keep adding new functions without an automatic tool (though it might be error-prone).

I don't think there's nothing to be done here. It's not code duplication: each definition exists under a different flags combination so they are never redundant. And it's easier to keep the code apart instead of figuring out ways to share "common" code.

**Comment by didactic-drunk** [comment]
`unistd.cr` is almost uniform with the exception of an additional constant or 2.
-  SC_CLK_TCK
-  SC_NPROCESSORS_ONLN

If the files are going to be generated then great.  2 of my PR's so far touch on lib_c.  Should I 
1. Keep manually patching and leave the problem to someone else when they regenerate to have the correct syscalls.
2. Keep manually patching but also patch the generator configuration to include the new syscalls.
3. Autogenerate them myself so they end up in the same order/format as the generator?

Is 3 even possible or reasonable?

**Comment by asterite** [comment]
I think we used https://github.com/ysbaddaden/posix in the beginning. It might still work, not sure.

**Comment by ysbaddaden** [comment]
It used to be written manually, but it was very tedious and error prone to write new bindings. I wrote a generator, which asterite linked above (posix) to generate nice bindings automagically for supported targets.

It's kinda outdated, because setting up a solution to generate bindings for a number of architectures is quite complex. I installed targets in local VM, copied their `/usr/include` folder over to the host machine

**Comment by didactic-drunk** [comment]
Does that mean it's managed manually for the foreseeable future?

**Comment by RX14** [comment]
For the near future yes, but the idea is to have them automatically generated and reusable.

Is generating headers for macos from darwin feasible?

**Comment by ysbaddaden** [comment]
As long as you have a running VM, you can run the posix generator and it will generate bindings. It works as well for macOS as for Linux or OpenBSD, as long as you can get the posix generator compiled for the target.

The difficulty is unsupported targets, where you need some cross generation (copy `/usr/include` locally and fiddle with C environment variables).
