### ISSUE TITLE
Add compiler feature to view inlined code

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#7892]
So, as far as I know Crystal itself already does a lot of inlining of code and I propose adding a compiler feature which allows one to view the code that the original code got inlined to.
So that this:
```cr
exit(1)
```
becomes
```cr
LibC.exit(1)
```
and
```cr
array = [] of String
array << "hello"
```
perhaps becomes something like
```cr
array = Pointer(String).new
array_size = 0
array_capacity = 0

if array_size == array_capacity
  array_capacity = array_capacity == 0 ? 3 : (array_capacity * 2)
  if array
    if array_size < 0
      raise ArgumentError.new("Negative size")
    end
    array = array.realloc(array_capacity)
  else
    array_buffer = Pointer(T).malloc(array_capacity)
  end
end
(array + array_size).value = "hello"
array_size += 1
```
(or perhaps with the instance variables visible (`@size`, `@capacity`) but then the code wouldn't be executable/would have to be changed manually but that's not too important maybe)

So you can basically look through code with a magnifying glass and all the code becomes naked to the bones (the bones are often special methods like `Pointer.malloc` or C functions etc.)

This can be useful for:
- Finding perfomance bottlenecks and bugs without having to inline all the methods in your head and switch from file to file, method to method which can sometimes take quite long (maybe there should be an option to say that you only want your own methods to be inlined, not standard library methods/methods defined in `prelude.cr`, because sometimes you might still not want to go that deep)
- Learning about internals, studying
- Optimizing code

It's sometimes simply interesting to see how this and that works and then this feature could be quite handy.

**Comment by bew** [comment]
Looks similar #5821 :smiley:

**Comment by asterite** [comment]
Sorry, but I don't think this is useful:

1. Finding performance bottlenecks: you don't need this, you can use a profiler
2. Learning about internals: these are not internals. Internals are how Crystal transforms code into LLVM, and you can already see that doing `--emit llvm-ir`
3. Optimizing code: similar to 1, so it doesn't apply.

**Comment by r00ster91** [comment]
With internals I just mean what's internally inside of the method. For example if this feature presents me this code with the `array`, `array_capacity` etc. from my proposal then one could learn that apparently the array's internal buffer's size is being reallocated as more things are pushed to the array which is something not everyone knows.

Sure, you can use LLVM IR but reading through those huge 60,000 lines is not very friendly and most people don't understand what's going on there, it's very low-level, too low-level I would say. Being able to read Crystal code instead as a Crystal developer would be much nicer to read and much easier understand.

**Comment by ysbaddaden** [comment]
There is nothing magical or hidden or that many builtins. It's all written in Crystal. You can read the source code to understand how something is implemented. No need to go reading LLVM IR to understand how Array works: open `src/array.cr` and read the methods you're interested in.
