### ISSUE TITLE
Socket::Addrinfo::Error when using HTTP::Client constructor

### ISSUE THREAD

**Issue by cserb** [crystal-lang/crystal#7902]
```
Crystal 0.29.0 (2019-06-06)

LLVM: 6.0.1
Default target: x86_64-pc-linux-gnu
```

```crystal
require "http/client"

client = HTTP::Client.new("api.airbnb.com/v2", tls: true)
client.compress = false
r = client.post("/logins", body: "{}")
pp r
```

```log
Unhandled exception: No address found for api.airbnb.com/v2:443 over TCP (Socket::Addrinfo::Error)
  from /usr/lib/crystal/socket/tcp_socket.cr:124:9 in 'initialize'
  from /usr/lib/crystal/socket/tcp_socket.cr:27:3 in 'new'
  from /usr/lib/crystal/http/client.cr:736:5 in 'socket'
  from /usr/lib/crystal/http/client.cr:624:5 in 'send_request'
  ...
```

This happens so far only with `api.airbnb.com`. Executing `HTTP::Client.post(...)` works without `Socket::Addrinfo::Error` but it doesn't decompress the gzip response, which is why I tried to do it manually

**Comment by bew** [comment]
You get that error because you're trying to access a server named `api.airbnb.com/v2` which is wrong: The server name is `api.airbnb.com` without `/v2` !

Try that:
```cr
require "http/client"

client = HTTP::Client.new("api.airbnb.com", tls: true)
client.compress = false
r = client.post("/v2/logins", body: "{}")
pp r
```

Note that github is an issue tracker, please ask questions on gitter/irc or the forums first :smiley:

**Comment by cserb** [comment]
@bew thanks! In my defence, I thought it's an issue after looking for 1 hour at it and seeing the problem

**Comment by asterite** [comment]
Let's put a check on that string and raise a good runtime error instead. I think this mistake is pretty common that we should do something about it.

**Comment by asterite** [comment]
The check might slow down things, but it's not like creating the http client is the slow part of issuing an http call.

**Comment by bew** [comment]
@asterite what about adding a hint in the sockaddr exception instead? or wrap the sockaddr exception in another one if we find a `/` in the host?

**Comment by asterite** [comment]
I think the check should be done at the HTTP::Client constructor

**Comment by rodrigopinto** [comment]
I can cover it @asterite.

**Comment by asterite** [comment]
@rodrigopinto Cool! I tried looking at this but I don't know what the check would be. Validating a domain isn't trivial. So for starters maybe we can just raise if the domain has some common things we'd like to avoid: `http://`/`https://` prefix, slash, colon, stuff like that.

**Comment by rodrigopinto** [comment]
@asterite I was wondering to use the `URI.parse` and verifies if only the `host` matches and the `path`,`scheme`,`query` & `fragment` are empty. It is not trivial, but it is a way, wdyt?

**Comment by asterite** [comment]
@rodrigopinto Oh, that's a good idea, though I think that `path` will remain non-nil while all of the others will be nil.

**Comment by asterite** [comment]
Also, I don't know about punicode so that's another thing I'm hesitant about... maybe just checking the prefixes and some chars is simpler and safer.

**Comment by rodrigopinto** [comment]
I think just checking prefix and a slash is ok, for start, but looking into some examples from other languages are to parse the `URI` and call `uri.host` as a parameter, but this solution would be improving the documentation. (What is valid too)

Another solution is to create a version of the `HTTP::Client.new` that only accepts a URI instance.
What if we implement an interface for `new` to accept a URI instance. 

wdyt?

**Comment by asterite** [comment]
> Another solution is to create a version of the HTTP::Client.new that only accepts a URI instance.
What if we implement an interface for new to accept a URI instance.

That's a huge breaking change so no.

**Comment by rodrigopinto** [comment]
My mistake actually, there are already [two implementations](https://crystal-lang.org/api/0.29.0/HTTP/Client.html#new%28uri%3AURI%2Ctls%3Dnil%29-class-method) of `new` that receives a `URI` instance and one which accepts a String. 

Reading the code I find out this `[validate_host](https://github.com/crystal-lang/crystal/blob/fbfe8b62f44eca4596090b7580801bd184f73c7a/src/http/client.cr#L804-L809)`  so, my proposal now is to covert the string into a uri on the `self.new(host : String, port = nil, tls = false)` or to ignore the error and let it fail "gracefully` as it is. 

Ruby implementation and other languages raises similar socket error.

**Comment by asterite** [comment]
Don't worry, I'll implement this soon. It's one of those things that if someone else sends a PR I will never quite agree about it.

**Comment by rodrigopinto** [comment]
>  It's one of those things that if someone else sends a PR I will never quite agree about it.
Did not understand your point @asterite.

**Comment by asterite** [comment]
What I mean is, many times it happens that when we (core team, community) can't agree about how we'd implement something, someone sends a PR with one approach. Then it's a never-ending stream of comments saying "No, it should be done this way", "it should be done that way", "maybe do this", "maybe do that", and all because we are still unsure about the best way to implement it.

That results in a loss of time for the PR author and the reviewers.

For these stuff I find it much easier for me to create a PR with what I think is the best way, knowing the language and std by heart. This can lead to discussions too, but they are usually less and then it's just me losing time and I don't mind it. I don't want to put burden on someone tackling this and then me not liking it.
