### ISSUE TITLE
Unexpected byte 0xc2 at position 61, malformed UTF-8 

### ISSUE THREAD

**Issue by diegogub** [crystal-lang/crystal#7905]
Hello,

Trying to run this code:

```
    require "./spec_helper"                                                                                                                                                                                 
    apr = Crcqrs::App.new("banking","bk")?
```

Fails with this error:

Error: file './spec/test3.cr' is not a valid Crystal source file: Unexpected byte 0xc2 at position 414, malformed UTF-8

Took me a while to track that down, as It was part of a bigger code base. Of course its just the ? at the end. May be I'm missing something, but It should be a syntax error.

Is it a bug? The error message is not clear.

Crystal 0.29, on OSX.

Thanks

**Comment by jhass** [comment]
It does if you copy paste it like that: https://carc.in/#/r/73c0

The codepoint for `?` is 0x3F not 0xC2, so I guess the `?` is your editors replacement character for an invalid Unicode codepoint / broken UTF-8 encoding.

I see nothing to fix here.

**Comment by diegogub** [comment]
I see, thanks @jhass
