### ISSUE TITLE
Some HTTPS websites may trigger IO::Timeout, unable to close the socket connection

### ISSUE THREAD

**Issue by ghost** [crystal-lang/crystal#7909]
## Summary
Some HTTPS websites HTTP::Client are unable to `close` the client.

I guess he may need to meet some conditions
(e.g. `Moved Permanently` || `Content-Length: 0` || `zero body`? )

The trigger condition is difficult, 
it needs to use the China proxy server to request `https://bing.com`,
Then it will jump to `https://cn.bing.com`,
He will get the response successfully, but later trigger `IO::Timeout`.

I finally found out the source of the error through debugging:
* [crystal/src/http/client.cr#213](https://github.com/crystal-lang/crystal/blob/fbfe8b62f44eca4596090b7580801bd184f73c7a/src/http/client.cr#L213)

I set the tag information near this and found that the `client` was not closed.
..., I can't fix it...

This is similar to #7843, It takes **special conditions** to trigger.
(e.g. You need to be triggered by an invalid virtual network card).

## Example
```crystal
require "http/client"
require "openssl"

class HTTP::Client
  def self.new(uri : URI, tls = nil)
    tls = tls_flag(uri, tls)
    host = validate_host(uri)
    client = new(host, uri.port, tls)
    begin
      yield client
    ensure
      puts "#L12"
      client.close
      puts "#L14"
    end
  end
end

tls = OpenSSL::SSL::Context::Client.new
tls.verify_mode = OpenSSL::SSL::VerifyMode::NONE

puts [LibSSL::OPENSSL_VERSION]

begin
  HTTP::Client.new uri: URI.parse("https://bing.com"), tls: tls do |client|
    client.connect_timeout = 30.second
    client.read_timeout = 30.second
    client.get("/") do |y|
      puts [y]
      # puts [y.body_io.gets_to_end]
    end
  end
rescue ex : IO::Timeout
  puts [ex.message]
end
```

## Trigger
```text
$ ./bing
["1.0.2"]
[#<HTTP::Client::Response:0x10dffbf00 @version="HTTP/1.1", @status=MOVED_PERMANENTLY, @status_message="Moved Permanently", @headers=HTTP::Headers{"Location" => "https://cn.bing.com/", "Server" => "Microsoft-IIS/10.0", "X-MSEdge-Ref" => "Ref A: 2AF14F57253D4F4B8C82927487A17215 Ref B: HKGEDGE0221 Ref C: 2019-06-20T16:10:10Z", "Date" => "Thu, 20 Jun 2019 16:10:09 GMT", "Content-Length" => "0"}, @body_io=nil, @cookies=nil, @body="">]
#L12
["Read timed out"]
```

**Comment by straight-shoota** [comment]
This needs a reproducible example.

**Comment by rdp** [comment]
It hangs on the call to close?  I wonder if it's an artifact of how the server is treating your client (the client sends a message "please shutdown SSL" then waits for the acknowledgement from the server, but if it never comes...) if that's the case then...hmm wonder if there's a way to short-circuit the close mechanism...or set a tcp read timeout...

**Comment by rdp** [comment]
OK I was able to repro it by changing url to "https://bing.com" which also has a redirect.  And is IIS.

Appears to be part of "a special class" of misbehaving TLS servers (well, TBH mostly IIS LOL).

This appears to fix the issue: https://github.com/crystal-lang/crystal/issues/7136#issuecomment-550760418

**Comment by jhass** [comment]
Is this still an issue or was it just another manifestation of #7136?

**Comment by rdp** [comment]
I am no longer able to repro with 0.33.0 so appears so... (I think you can also repro with "https://old.bing.com").
