### ISSUE TITLE
Use same naming scheme for OAuth::AccessToken and OAuth2::AccessToken

### ISSUE THREAD

**Issue by watzon** [crystal-lang/crystal#7910]
Currently `OAuth::AccessToken` and `OAuth2::AccessToken` have a different method to access the actual token value, with the former being `token` and the latter being `access_token`. It would make more sense for `OAuth2::AccessToken` to also have the parameter be named `token` as it's less verbose and makes the naming more consistent.

**Comment by asterite** [comment]
I think I used the names mentioned in the RFC, but I wouldn't mind making the APIs more consistent.

**Comment by asterite** [comment]
I take it back: I don't think we need a different kind of consistency here. The current names match those in the RFCs.
