### ISSUE TITLE
[Bug] Overflow in 128-bit negative integers

### ISSUE THREAD

**Issue by akadusei** [crystal-lang/crystal#7915]
This is a bug, according to the compiler:

## Code

[[playground](https://play.crystal-lang.org/#/r/73ru)]

```crystal
-3_i128
```

## Output

```crystal
Overflow (OverflowError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from __crystal_main
  from main
  from __libc_start_main
  from _start
  from ???
Error: you've found a bug in the Crystal compiler. Please open an issue,...
```

This affects only negative integers.

The bug seems to be a regression introduced in **v0.27.2**, according to the Crystal playground. It worked fine before.

**Comment by jhass** [comment]
Trace with symbols:

```
Arithmetic overflow (OverflowError)
  from __crystal_raise_overflow
  from LLVM::Type#const_int<Int64>:LLVM::Value
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::Compiler#codegen<Crystal::Program, Crystal::ASTNode+, Array(Crystal::Compiler::Source), String>:(Tuple(Array(Crystal::Compiler::CompilationUnit), Array(String)) | Nil)
  from Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result
  from Crystal::Command#run:(Bool | Crystal::Compiler::Result | Nil)
  from main
```

**Comment by wontruefree** [comment]
I dont think 128 bit integers are fully implemented yet.  I think this is a problem [here](https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/syntax/lexer.cr#L1745). Also there is a [PR](https://github.com/crystal-lang/crystal/pull/7093) to add 128 bit support.  Most of the work was dont in another branch it is just a bit project.
