### ISSUE TITLE
String#upcase method doesn't work for some letters

### ISSUE THREAD

**Issue by miiza** [crystal-lang/crystal#7922]
String#upcase method doesn't work for 2 Czech letters "ňž". It should give "ŇŽ" but gives "ňž":

`p "ňž".upcase`

All other Czech letters work ok:
`p "áčďéěíóřšťúůý".upcase`

I have tried Fold option, although I don't know what it is, but it doesn't help anyway:
`p "ňž".upcase(Unicode::CaseOptions::Fold)`

I am on Xubuntu 18.04

Crystal 0.29.0 [fbfe8b62f] (2019-06-05)
LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu

cat /etc/issue
Ubuntu 18.04.2 LTS

**Comment by asterite** [comment]
Strange, I thought this would be automatically done by Unicode 12.0...

**Comment by asterite** [comment]
@miiza Good catch, thank you! There was a bug in the way we generated unicode ranges for processing this stuff.
