### ISSUE TITLE
Class methods can't be included from modules

### ISSUE THREAD

**Issue by malte-v** [crystal-lang/crystal#7927]
For some reason class methods can't be included from modules:
```cr
module Bar
  def self.bar
  end
end

class Foo
  include Bar
end

Foo.bar # undefined method 'bar' for Foo.class
```
Is this the desired behaviour? If so, why isn't this allowed?

**Comment by yxhuvud** [comment]
This behaviour is copied without modification (as far as I know) from Ruby. I'm not certain it is optimal though - I wouldn't really mind having module behave like Rails concerns (which is one way to handle it). 

But to actually answer your question, you can create a module like 
```
module Bar
  def self.bar
  end
end
```
and then use the `extend` keyword to add the methods as class methods.

**Comment by malte-v** [comment]
If you want to use `extend`, the module methods need to be instance methods. Class methods aren't copied over by `extend`.

**Comment by asterite** [comment]
This works exactly like in Ruby though I always wondered whether only include should exist in the language (though one use case of extend in the standard library is ENV extends Enumerable, but that could always be something like ENV = Env.new and making Env include Enumerable).

It would also simplify the language a bit.

**Comment by malte-v** [comment]
I'm in favor of removing `extend` and letting `include` copy class methods and variables. I don't think Crystal needs to be exactly like Ruby, especially when it comes to the not-so-great parts of Ruby.

**Comment by girng** [comment]
including modules inside classes to now shadow-act as a **class method** (when it's really a method from a `module`) is confusing, less explicit, and probably more prone to bugs

**Comment by malte-v** [comment]
@girng Can you clarify why this would be confusing? Modules can also have class methods and variables.

**Comment by malte-v** [comment]
One major thing to consider when removing `extend`: What about `extend self`? Maybe add a new `namespace` keyword?

**Comment by girng** [comment]
@malte-v Not sure, but off the top of my head, if a developer is looking for included methods in a class, they are going to be looking for methods under a class, not a method

**Comment by asterite** [comment]
`extend self` is just adding `self.` to each method. We have a similar thing with `private` and `protected`: you have to add those to each method. So living without `extend self` isn't a really big deal,  I think.

**Comment by asterite** [comment]
I'm going to close this because this is working as expected, at least with the current semantics. Maybe in the future we'll change them but it's independent of this issue being open.
