### ISSUE TITLE
Exit on benchmarking without release falgs

### ISSUE THREAD

**Issue by spinscale** [crystal-lang/crystal#7928]
This is more of a suggestion than an issue. Right now, when running benchmarks without `--release` a warning is printed.

As those benchmarks are meaningless, what about simply returning an error and exiting in that case to prevent people using those numbers for anything? Happy to help with a PR, if there is agreement.

**Comment by ysbaddaden** [comment]
They're not meaningless. I'm often interested to see whether a change impacts non release mode too, and how much.

**Comment by asterite** [comment]
Me too.

**Comment by spinscale** [comment]
kk, then it makes sense to close this one.
