### ISSUE TITLE
Override IO::Buffered::BUFFER_SIZE

### ISSUE THREAD

**Issue by carlhoerberg** [crystal-lang/crystal#7929]
`IO::Buffered::BUFFER_SIZE` is not (easily?) overrideable, and I feel that 8192 bytes is a bit arbitrary.

**Comment by asterite** [comment]
Yes, I agree that this should be configurable.

**Comment by carlhoerberg** [comment]
Make it a property instead of a constant? Dangerous to change it after first use though

**Comment by carlhoerberg** [comment]
Can make a PR, where it can't be changed after the buffers are allocated

**Comment by asterite** [comment]
I think we can determine and raise if we are in that dangerous situation (basically, if the buffer is empty it's fine, otherwise raise). Or even let the buffer be nilable and raise if it's not nil. I'm not sure.

**Comment by asterite** [comment]
> Can make a PR, where it can't be changed after the buffers are allocated

Sounds good!
