### ISSUE TITLE
duplicate sections in INI

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#7934]
I am parsing some INI like files and there are multiple sections with the same name.  I cannot find an exact spec and it seems like some implementations allow duplicate sections some merge all sections with the same name.  I think it would be nice to have the ability to have multiple sections but it would be a breaking change for sure.

**Comment by oprypin** [comment]
Can you specify what the current behavior is?

**Comment by j8r** [comment]
The current implementation returns `Hash(String, String)`. No duplicated keys possible.

I think having a `Serializable` (or `mapping`) for `INI` would be great, even if I also think that all this opinionated mapping stuff should belong to a framework, not the stdlib.

**Comment by asterite** [comment]
Right now sections are merged. I think this is fine? What does it mean to have multiple sections?

**Comment by oprypin** [comment]
I also think this is fine.

I'm guessing it means that it would be possible to discern between items of 1st and 2nd (and ... ) occurrence of sections with the exact same name.

But the issue doesn't specify any actual behavior whatsoever.

This would definitely be extremely unusual behavior and I don't like it. Then again, a "streaming" parser (or is it called "pull parser") would be nice to have decided, and that would be its behavior - just announce "start of section" and "assignment" as they appear.

**Comment by oprypin** [comment]
I could not have imagined that the source code is so tiny.
https://github.com/crystal-lang/crystal/blob/4f9ed8d03208dd0db33993c5a6fa6753bc1cf91e/src/ini.cr

And actually this line tells me that currently prior occurrences of a section are discarded entirely, which is also unusual.
`ini[section] = {} of String => String`

**Comment by wontruefree** [comment]
I guess merging of sessions is fine.  I was parsing wireguard files which are not technically ini files.  I was just reading some people have other implementations.
