### ISSUE TITLE
Bytes.new with NUL bytes

### ISSUE THREAD

**Issue by didactic-drunk** [crystal-lang/crystal#7939]
Bytes.new seems to always return an array filled with 0's.  Is this guaranteed in the future or the way it works now?

If the behavior may change introducing randomness could reduce future bugs similar to what [go did with it's `map` implementation.](https://nathanleclaire.com/blog/2014/04/27/a-surprising-feature-of-golang-that-colored-me-impressed/)

**Comment by asterite** [comment]
The docs say it starts with zero, so yes. And I think that's fine.
