### ISSUE TITLE
JSON::Serializable for deserialization of hash with integer keys doesn't work

### ISSUE THREAD

**Issue by miiza** [crystal-lang/crystal#7942]
JSON::Serializable for deserialization of hash with integer keys doesn't work:

```crystal
require "json"

class Building
	include JSON::Serializable
	property locations = {} of Int32 => String
#	property locations = {} of String => String

	def initialize(); end
end

b = Building.new
b.locations[2] = "Alfa"
#b.locations["2"] = "Alfa"

ser = b.to_json
p ser

y = Building.from_json(ser)
p y
```

Is it a bug or a feature?

It works for YAML serialization. And it works for string keys in JSON serialization.
But it produces awful huge error messages for integer keys - error messages that are absolutely unhelpful. 

If it is a feature then it is a rather trap for newcomer to Crystal programming. It seems to be very unnatural for me. I was rewriting a bigger piece of code to Crystal and it was difficult to spot the cause of the errors. I expected that serialization is always bidirectional if I use `include JSON::Serializable`.

Maybe it is OK. I just wanted to let you know.

I am on Xubuntu 18.04

Crystal 0.29.0 [fbfe8b6] (2019-06-05)
LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu

cat /etc/issue
Ubuntu 18.04.2 LTS

**Comment by Blacksmoke16** [comment]
The main issue here is that the JSON spec doesn't allow for numeric literal keys.  If you look at the generated JSON string, you'll notice the key is `"2"`.  This is an issue when attempting to deserialize an object from that string, with the key part of the error being: `no overload matches 'Hash(Int32, String)#[]=' with types String, String`.  

On deserialization it just needs to convert the string key to the expected type, which is doable (and probably preferable).

https://github.com/crystal-lang/crystal/blob/master/src/json/from_json.cr#L126

by replacing that line with `hash[K.new(key)] = V.new(pull)`.

**Comment by asterite** [comment]
Keys in JSON, according to the spec, are always strings, that's why I never thought of implementing this feature. It's different in YAML.

That said, we could probably support this very easily. PRs are welcome as long as other people think this is something good.

**Comment by bcardiff** [comment]
IMO, the best `JSON::Serializable` could do is to have a more descriptive message. 

I would not allow int as keys implicitly. I am not sure if the `converter` can currently support this scenario today, but that could be the way to go.

**Comment by miiza** [comment]
My use case is to have very fast data web servers that do not use database - instead I have my own data types in Crystal. Something like this:

```crystal
class Database

	property users = {} of Int64 => User
	property users_by_username = {} of String => Int64
	property users_by_email = {} of String => Int64

	property last_user_id = 0_i64

end

D = Database.new()

post "/read_users_by_username" do |env|

	usernames = Array(String).from_yaml(env.request.body.not_nil!)
	ubox = Ubox.new()

	usernames.each do |key|

		user_id = D.users_by_username[key]?

		if user_id

			user = D.users[user_id]

			ubox.by_username[key] = user
			ubox.by_id[user_id] = user
			ubox.all << user_id
		end
	end

	ubox.to_yaml
end

class Ubox
	include YAML::Serializable

	property by_wording = {} of String => User
	property by_id = {} of Int64 => User
	property all = [] of Int64

	def initialize(); end
end

# class User is deeply nested.
```

I have 3 additional notes.

1) Should I use YAML serialization? Is `YAML::Serializable` able to serialize any Crystal data types or can I expect some other problems in the future?

2) JSON::Serializable is able to serialize even nested Crystal objects so I can produce a lot of source code. But suddenly not a hash keyed by integers. It is very confusing.

3) 3rd party json web service use case:  

* I would like to read potentially very deeply nested and potentionally corrupt json to my data types in Crystal which is strongly typed - that is the Crystal advantage! So I want to define by my Crystal data types (objects) that string keys will be converted to integers - or an error will be thrown. And I can change integer types between Int64, Int32, Int16 and Int8 as I need. Will be possible to solve it easily if conversion will not be done during `.from_json()` method? How?

* If I think about that it is so natural to define conversion by defining the target data structure in Crystal. How else should it be done and why?

**Comment by kostya** [comment]
you can use msgpack, which allow any type for keys, also there is simple_rpc shard which helps to create such fast api very easily, and also can be called from any language.

**Comment by asterite** [comment]
On second thought, int will expect a pull parser to be positioned on an int, not a string, so supporting this will involve a great hack. It's better to avoid that.

YAML is a superset of JSON so you could use that. Alternatively message pack, as suggested by kostya. But in JSON, hash keys are always strings.

**Comment by asterite** [comment]
On third thought, we could suoport this by having types respond to a new method, from_json_key or something like that. We could support it for some primitive types like string, int, bool, enum and Time. I wouldn't expect other cases, but anyone is free to do so. I'll send a PR soon.

**Comment by asterite** [comment]
So I just tried this in Go: you can unmarshall a dictionary with int keys, but not with float and bools... maybe the int case is hardcoded, I don't know. In any case we can do better :-)

**Comment by girng** [comment]
```
require "json"

class Building
	include JSON::Serializable
	property locations = {} of String => String
#	property locations = {} of String => String

  def initialize(id : Int32, name : String)
    @locations[id.to_s] = name
    
  end
end

b = Building.new(2, "Alfa")

 
ser = b.to_json
p ser

y = Building.from_json(ser)
p y
```

**Comment by girng** [comment]
[Reduced](https://play.crystal-lang.org/#/r/760q):
```crystal
require "json"

class Building
	include JSON::Serializable
	property locations = {} of Int32 => String
end
y = Building.from_json(%({"locations":{2:"Alfa"}}))
pp y
```

If JSON gets `int` based key support, _then this will have to work as well:_
https://play.crystal-lang.org/#/r/760r

It's just not valid JSON. I like that Crystal is conforming to spec. Use the solution that blacksmoke gave, this seems like a specific use-case IMO. I agree with bcardiff ,    better error handling would be ideal here though.

**Comment by miiza** [comment]
@girng 
It definitely should save and load a valid json. Both variants
(a) ```... {} of String => String ...```
and 
(b) `... {} of Int32 => String ...` 
get serialized to the same string (valid json) through crystal method `.to_json`:
`{"locations":{"2":"Alfa"}}`

But deserialization of the same string `{"locations":{"2":"Alfa"}}` to the same data structure through crystal method `.from_json` succeeds only in variant (a).
And the discussion now is whether variant (b) really should fail - or it should succeed.

**Comment by girng** [comment]
@miiza Yeah,  after further discussion in gitter I understand. Sorry about that!
