### ISSUE TITLE
Possible alignment issue on Windows

### ISSUE THREAD

**Issue by cfsamson** [crystal-lang/crystal#7947]
Working on https://github.com/crystal-lang/crystal/pull/6955 I realized after a lot of debugging that there might be an alignment issue on Windows. I can't say for sure, but I'll make my case here.

## The problem
Trying to implement a context switch in Windows, I found that Crystals inline assembly caused the program to crash on Windows even though it _should_ work so I implemented the absolute minimal example I could in both Rust and Crystal to narrow it down (both using LLVM as a backend). The code is as similar as I could get them.

The code is below so the experiment can be reproduced.

Now the Rust code runs as expected on both Windows, Linux and Macos. The Crystal code works on Linux and Macos but crashes on Windows. **There is at least definately _something_ wrong that prevents this from working and might also be the problem in https://github.com/crystal-lang/crystal/pull/6955 preventing implementing a context switch for Windows.**

## Research done
So I started to test the `asm` macro when cross compiling and it compiles fine. I.e. this code runs as expected on both Linux and Win.

The issue only arises when I try to pass a pointer (or any 64 bit value) to `%rsp`. I know that Windows is very picky about the alignment so the only issue I could think of is that it fails to or from unaligned memory.

So I took a look at the LLVM IR from both Crystal and Rust using `cargo rustc -- --emit=llvm-ir` for Rust and `crystal build -D gc_none --emit llvm-ir  --cross-compile --target x86_64-pc-windows-msvc minimal_example.cr` for Crystal:

```
; Function Attrs: naked noinline uwtable
define void @.2A.swap.3C.UInt64.3E..3A.Void(i64 %data) #5 !dbg !1283 {
entry:
  call void asm sideeffect "\0A  pushq %rcx\0A  movq $0, %rsp\0A  popq %rcx\0A  ", "r"(i64 %data), !dbg !1284
  ret void, !dbg !1284
}
```
**Rust LLVM IR**
```
; rust::swap
; Function Attrs: naked noinline uwtable
define internal void @_ZN4rust4swap17ha701b2b0800c21beE(i64) unnamed_addr #1 !dbg !136 {
start:
  %data = alloca i64, align 8
  store i64 %0, i64* %data, align 8
  call void @llvm.dbg.declare(metadata i64* %data, metadata !139, metadata !DIExpression()), !dbg !140
  %1 = load i64, i64* %data, align 8, !dbg !141
  call void asm sideeffect "\0A  pushq %rcx # not needed, just to mimmic the Crystal ctx switch\0A  movq $0, %rsp\0A  popq %rcx\0A  ", "r,~{dirflag},~{fpsr},~{flags}"(i64 %1), !dbg !143, !srcloc !144
  ret void, !dbg !145
}
```
The only difference I could see that _might_ be of significance is that Rust specifically aligns `i64` to 8 while Crystal lets LLVM decide and [it defaults to](https://llvm.org/docs/LangRef.html#id205) the [ABI alignment](https://docs.microsoft.com/en-us/cpp/build/x64-software-conventions?view=vs-2019#types-and-storage) which is supposed to be 8 bytes as well, but it's the only difference I can see so it's a natural place to start investigating.

Maybe someone with more experience with LLVM and Crystal codegen can get futher than me.

## How to reproduce
Compile and run both the rust version and the Crystal version in Windows and Linux.
How to cross compile crystal: see [here](https://github.com/crystal-lang/crystal/wiki/Porting-to-Windows) and [here](https://github.com/crystal-lang/crystal/issues/7932).

## Minimal example in Crystal
```crystal
STACK_SIZE = 1024*1024*8

class Test
  property value : UInt64 = 0
  property stack = Array(UInt8).new(STACK_SIZE)
  property func : Proc(Void) = ->{}
  property rsp : UInt64 = 0

  def makecontext(proc : Proc)
    @func = proc
    s_ptr = @stack.to_unsafe
    s_start = s_ptr + (STACK_SIZE - 32)

    @rsp = (s_start - 1*8).as(Void*).address

    # Our entry
    s_start_ptr = s_start.as(UInt64*)
    s_start_ptr.value = ->start(Test).pointer.address

    # First parameter
    first_param = (s_start - 8).as(UInt64*)
    first_param.value = self.as(Void*).address
  end

  def run
    @func.call
    Process.exit(0)
  end
end

def start(f : Test)
  f.run
end

@[NoInline]
@[Naked]
def swap(data)
  {% if flag?(:win32) %}
  asm("
  pushq %rcx # not needed, just to mimmic the Crystal ctx switch
  movq $0, %rsp
  popq %rcx
  "
  :: "r"(data) :: "volatile" )
  
  {% else %}
  asm("
  pushq %rdi 
  movq $0, %rsp
  popq %rdi
  "
  :: "r"(data))
  {% end %}
end

test = Test.new
test.makecontext(->{ puts "Hello from new stack" })

swap(test.rsp)

```
## Minimal example in Rust:
```rust
#![feature(asm)]
#![feature(naked_functions)]

// # How to build this in Rust
// 1. Install Rust: https://www.rust-lang.org/tools/install
// 2. Install the nightly compiler: `rustup toolchain install nightly`
// 3. Create a new directory and run `cargo init`
// 4. Make sure you use the nightly by running `rustup override set nightly` in the project folder
// 5. Copy this code over to `main.rs`
// 6. Run the program: `cargo run`

const STACK_SIZE: isize = 1024 * 1024 * 8;

struct Test {
    stack: Vec<u8>,
    func: fn(),
    rsp: Option<u64>,
}

impl Test {
    fn new() -> Self {
        Test {
            stack: vec![0_u8; STACK_SIZE as usize],
            func: || {},
            rsp: None,
        }
    }

    fn makecontext(&mut self, proc: fn()) {
        self.func = proc;
        let s_ptr = self.stack.as_ptr();

        let mut s_start = unsafe { s_ptr.offset(STACK_SIZE - 32) as *mut u8 };
        self.rsp = Some(unsafe { s_start.offset(-1 * 8) as *const u64 as u64 });

        unsafe {
            // Our entry
            std::ptr::write(s_start as *mut u64, start as u64);

            // first parameter
            let mut first_param = s_start.offset(-8) as *mut u64;
            // this hurts to write...
            let this = Box::new(self);
            std::ptr::write(first_param, Box::into_raw(this) as u64);
        }
    }

    fn run(&self) {
        (self.func)();
    }
}

fn start(f: *const *const Test) {
    unsafe {
        (**f).run();
    }
    std::process::exit(0);
}

#[cfg(target_os = "windows")]
#[inline(never)]
#[naked]
fn swap(data: u64) {
    unsafe {
        asm!("
  pushq %rcx # not needed, just to mimmic the Crystal ctx switch
  movq $0, %rsp
  popq %rcx
  "
  :: "r"(data) :: "volatile");
    }
}

#[cfg(not(target_os = "windows"))]
#[inline(never)]
#[naked]
fn swap(data: u64) {
    unsafe {
        asm!("
  pushq %rdi
  movq $0, %rsp
  popq %rdi
  "
  :: "r"(data));
    }
}

fn main() {
    let mut test = Test::new();
    test.makecontext(|| println!("Hello from new stack"));
    swap(test.rsp.unwrap());
    println!("BEFORE: {:?}", test.rsp.unwrap());
}

```

## This works
```crystal
@[NoInline]
def swap(data)
  {% if flag?(:win32) %}
  asm("
  movq  %rsp, ($0)
  movq  ($0), %rsp
  "
  :: "r"(data))
  {% else %}
  asm("
  movq  %rsp, ($0)
  movq  ($0), %rsp
  "
  :: "r"(data))
  {% end %}
end

test = Test.new
puts "BEFORE: from: #{test.value}"
swap(pointerof(test.@value))
puts "AFTER: from: #{test.value}"
```

## Additional information
Crystal 0.29.0 [fbfe8b62f] (2019-06-05)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu

I have not tried to reproduce on master yet.

**Comment by ysbaddaden** [comment]
I'm sorry if I didn't quite understand the problem you're reporting. Here are my thought on context switch:

A context switch in Crystal is a mere function call: it saves callee registers on the stack, saves the current stack-pointer, restores a saved stack-pointer from the destination stack, restores the saved callee registers, then returns.

The current implementation assumes a System V call convention which is incompatible with Microsoft x64. See for example https://en.wikipedia.org/wiki/X86_calling_conventions#x86-64_calling_conventions

For example on Microsoft x64, the RBX, RBP, RDI, RSI, R12-R15, XMM6 and XMM7 must be saved, whereas on System V AMD64 we only save RBX, RBP, R12-R15. We additionally save RDI (1st argument for initial resume) which seems to be RCX on Win32.

Maybe the stack must also reserve 32-bytes of "shadow space" for the initial resume, too.

**Comment by cfsamson** [comment]
@ysbaddaden I'm sorry for not providing enough context. I know what you're poiting out, see https://github.com/crystal-lang/crystal/pull/6955#issuecomment-505643409. But when I started working on it I realized it didn't run as it _should_. 

First i pulled out the parts of the Fiber-design I saw you had done a lot of work on to scope down the issue. See: https://gist.github.com/cfsamson/8229407feefe91ef21a05aaa9b224729#file-crystal_fibers_asm_test-cr

But then I realized, it seemed not to have anything to do with the assembly or the code, but something seemed wrong elsewhere. So thats when I removed everything non-essential to reproduce it landing on the code above. I only switch context once here, so `%rsp` should be enough to make a jump (the rest of the `callee saved` registers are empty anyway on the initial switch). I also set up the "shadow" space which is needed even for the initial jump as you'll see in the code.

To be sure I reproduced the same code in Rust since I know it better and it also uses LLVM (i.e. the inline asm is pretty much exactly the same as in Crystal). In Rust I manage to make the CPU jump on all platforms, in Crystal it won't work on Windows).

I landed on alingment as the probable reason since it only happens whan I pass in a 64 bit value as an input in the inline asm. As you see in the last example, there is no problem writing the value out of `%rsp` and copy it back in (not suprisingly though) so there must be somthing in Crystal <=> LLVM. 

There could be a ton of reasons for this code to fail, but since the exact same code is working in Rust and not in Crystal I landed on some sort of alignment issue as the most probable one.

**Comment by ysbaddaden** [comment]
I notice some differences between the Crystal and Rust sample LLVM IR you provided (I didn't compile them myself). The Rust LLVM IR also appears to be for System V (`pushq %rdi`).

1. I doubt it, but: in Rust you have complete control over `main`, but Crystal does a bunch of things before and after executing the "user main code", maybe it's crashing after the call to `swap` (corrupted stack)? again, I doubt that's the issue.
2. more likely: in Rust, the LLVM IR is creating a local alloca so Debug Information is available for the variable, and then references the alloca to the ASM, in Crystal there isn't, and the function argument is passed directly to the ASM;
3. in Rust `swap` receives an `i64*`, but in Crystal it receives an `i64`?

The "shadow space" for Microsoft x64 is also tinkering me: shall we reserve 32-bytes on the stack for the initial resume?

The only way to solve this, thought, is to debug the actual executable assembly and follow registers' state to understand what's really happening, possibly setting expected values on the stack before the initial resume, checking whether registers are correctly populated, or not, on the initial resume (I did that a lot for ARM an AArch64). This should help to detect alignment issues.

**Comment by cfsamson** [comment]
@ysbaddaden 
Sigh, I shouldn't have written an issue like this at the end of a long day. I made the pointers into 64 bit integers in both cases to minimize differences, but copy pasted the wrong version (Rust). The correct one has been changed in the first post.

Re: LLVM IR, again, my bad, i copied the wrong one and have corrected it now.  Same as above. No change to the conclusions though.

1. Agree
2. True but it still runs as expected in `--release` where it shouldn't do this (at least not in the examples I have compared before). I tried to avoid passing references by making the addresses 64 bit integers in both cases but it seems Rust does make an allocation and pass a pointer anyway on debug.
3. See above

It would be interesting though if anyone would write the same code in C and compile it with clang and confirm:
1. That it works on Windows and Linux. 
2. Pull out the relevant LLVM IR

If it works it strengthens the assumtions that Crystal somehow deviates from the other two compilers.
Going through the assembly might be something that needs to be done in the end though.

Is there any way to get hold of the genrated assembly from the Crystal compiler?

**Comment by ysbaddaden** [comment]
I'll try to write a C version when I have some time.

You can disassemble / debug using whatever tooling you'd use for plain C (or Rust), I use `gdb` on Linux.

**Comment by cfsamson** [comment]
Oh, ok, I'll have to have a look into that though. 

Regarding shadow space: 

If I read the [reference](https://docs.microsoft.com/en-us/cpp/build/stack-usage?view=vs-2019#stack-allocation) correctly it's actually something that is allocated in a stack frame for the first four parameters (but still needs to be reserved even though there are 0 parameters). I don't think this concerns us really when setting up a stack, LLVM takes care of it later on when setting up stack frames. However, I've had some issues when not leaving som room at the bottom of the stack before, and [read a comment about it in the Fiber source code](https://github.com/straight-shoota/crystal/blob/fee31e4f29e2c36668b97fbd8bd33096f6efb730/src/fiber.cr#L80) so I just left it at a 32 byte offset. I'm not 100% sure whats right here.

**Comment by ysbaddaden** [comment]
I notice you reserve 32-bytes on the stack for the shadow space, but don't align the initial stack pointer to 16-bytes, which is required. There is no guarantee that the allocate (bwgc) will align on 16 bytes.

**Comment by bcardiff** [comment]
@cfsamson 

> Is there any way to get hold of the genrated assembly from the Crystal compiler?

the compiler has an `--emit=[asm|llvm-bc|llvm-ir|obj]` option

**Comment by cfsamson** [comment]
@ysbaddaden Hmm, I haven’t looked into that to be honest. I have manually looked at the addresses and checked if they’re a multiple of 16 and it seems so but that might be too naive? How would I go about to request aligned memory on windows?

**Comment by ysbaddaden** [comment]
```crystal
WORD_SIZE = sizeof(Void*)
STACK_SIZE = 8 * 1024 * 1024
SHADOW_SPACE_SIZE = 32

ptr = @stack.to_unsafe.as(UInt8*) + STACK_SIZE # stack grows down
ptr = Pointer(UInt8).new(stack.address & ~16)  # align stack on 16 bytes
ptr -= SHADOW_SPACE_SIZE                       # for initial resume

sp = (ptr - WORD_SIZE).as(Void*)               # last addressable pointer on the stack
```

**Comment by cfsamson** [comment]
@ysbaddaden 
Ok, so now I tried this, but no success. I haven't seen that way of aligning manually before but I changed `~16` to `~15` since 0xF is 15 and I would think that is what you meant?

If I put a print statement in the very start of the execution it isn't executed either. I would have thought that if `%rsp` was misaligned it would fail at the switch and not at the start of execution program.

**Comment by cfsamson** [comment]
OK, so I compared the assemboy output for windows/linux for both Rust and Crystal (I used Rust release build since it messes up the asm a bit in debug):

The only difference that I can see that might be of importance is the use of the `.p2align` directive used in Crystal-> Linux, Rust->Linux, Rust->Windows but not in Crystal->Windows.

[The p2 align directive](https://sourceware.org/binutils/docs/as/P2align.html#P2align):

>  The first expression (which must be absolute) is the number of low-order zero bits the location counter must have after advancement.

_A value of 3 means an alignment of 8 and a value of 4 means an alignment of 16._

### A small experiment to confirm if this might matter
So I tried to compile a short stub of assembly that works on both Windows and Linux, and looked at the assembly output and true enough while  `Lfunc_end244` had this in the first example:
```
.Lfunc_end244:
	.seh_handlerdata
	.text
```
It had this in the second example, compiling more like Rust on Windows, and same as the Linux output:
```
.Lfunc_end239:
	.def	 .2A.UInt64.3A..3A.new.3C.UInt64.3E..3A.UInt64;
	.scl	3;
	.type	32;
	.endef
	.p2align	4, 0x90
```
Does this matter? Honestly I'm not sure. I know very little about LLVM at this level of detail. I would like to have some more eyes to have a look at this before I invest more time digging down this path.

## Code and output

```asm
# ===== CRYSTAL LINUX =====
"*swap<UInt64>:Void":
.Lfunc_begin1468:
	.loc	22 50 0
	.cfi_startproc
	.loc	22 50 1 prologue_end
	#APP

	pushq	%rdi
	movq	%rdi, %rsp
	popq	%rdi

	#NO_APP
	retq
.Ltmp2789:
.Lfunc_end1468:
	.size	"*swap<UInt64>:Void", .Lfunc_end1468-"*swap<UInt64>:Void"
	.cfi_endproc

	.p2align	4, 0x90
	.type	"*UInt64::new<UInt64>:UInt64",@function
"*UInt64::new<UInt64>:UInt64":


# ===== CRYSTAL WINDOWS =====

.2A.swap.3C.UInt64.3E..3A.Void:
.Lfunc_begin244:
	.loc	11 50 0
.Lcfi851:
.seh_proc .2A.swap.3C.UInt64.3E..3A.Void
	.loc	11 50 1 prologue_end
	#APP

	pushq	%rcx	# search marker
	movq	%rcx, %rsp
	popq	%rcx

	#NO_APP
	retq
.Ltmp387:
.Lfunc_end244:
	.seh_handlerdata
	.text


==== RUST LINUX RELEASE BUILD ====
_ZN4rust4swap17he13c5e44d52e6c8eE:
	.cfi_startproc
	#APP

	pushq	%rdi
	movq	%rdi, %rsp
	popq	%rdi

	#NO_APP
	retq
.Lfunc_end8:
	.size	_ZN4rust4swap17he13c5e44d52e6c8eE, .Lfunc_end8-_ZN4rust4swap17he13c5e44d52e6c8eE
	.cfi_endproc

	.section	.rodata.cst16,"aM",@progbits,16
	.p2align	4

==== RUST WINDOWS RELEASE BUILD ====
_ZN4rust4swap17h790ea4258068be99E:
	#APP

	pushq	%rcx
	movq	%rcx, %rsp
	popq	%rcx

	#NO_APP
	retq

	.def	 _ZN4rust4main17h6231a7a2aecb2336E;
	.scl	3;
	.type	32;
	.endef
	.globl	__xmm@00000000008000000000000000800000
	.section	.rdata,"dr",discard,__xmm@00000000008000000000000000800000
	.p2align	4
__xmm@00000000008000000000000000800000:
	.quad	8388608
	.quad	8388608
	.section	.text,"xr",one_only,_ZN4rust4main17h6231a7a2aecb2336E
	.p2align	4, 0x90crs
```

## Now, if I compile this code that works on both Windows and Linux:
```crystal
class Test
  property value : UInt64 = 0
end

@[NoInline]
@[Naked]
def swap(data)
  {% if flag?(:win32) %}
  asm("
  movq  %rsp, ($0)
  movq  ($0), %rsp
  "
  :: "r"(data))
  {% else %}
  asm("
  movq  %rsp, ($0)
  movq  ($0), %rsp
  "
  :: "r"(data))
  {% end %}
end

test = Test.new
puts "BEFORE: from: #{test.value}"
swap(pointerof(test.@value))
puts "AFTER: from: #{test.value}"
```
**And look at the assembly output for Windows:**
```asm
.Lfunc_begin239:
	.loc	11 40 0 is_stmt 1
	.loc	11 40 1 prologue_end
	#APP

	movq	%rsp, (%rcx)
	movq	(%rcx), %rsp

	#NO_APP
	retq
.Ltmp380:
.Lfunc_end239:

	.def	 .2A.UInt64.3A..3A.new.3C.UInt64.3E..3A.UInt64;
	.scl	3;
	.type	32;
	.endef
	.p2align	4, 0x90
.2A.UInt64.3A..3A.new.3C.UInt64.3E..3A.UInt64:
```

**Comment by cfsamson** [comment]
So this is not the issue after all. I have trouble letting this go since I found the difference strange, so I re ran all everything today to compare and this time the output of the Crystal->Windows build was: 
```
.Lfunc_end244:

	.def	 .2A.UInt64.3A..3A.new.3C.UInt64.3E..3A.UInt64;
	.scl	3;
	.type	32;
	.endef
	.p2align	4, 0x90
```
So it's similar. How it looked differently a few days ago (or where I made a mistake) I'm not sure, but it doesn't seem to be a problem.

**Comment by cfsamson** [comment]
@ysbaddaden 
Good news! This was a wild goose chase. I looked at the disassembled asm and noticed that the context switch does indeed work. One of the registers pointed to a string "not open for writing", and I assumed that was "stdout" and found a way to make everything work as expected on Windows.

The strange behaviour was caused by `puts`. I tried to use `STDOUT` directly and everything worked as expected.

```crystal```
test.makecontext(->{ 
  STDOUT << "Hello from new stack\n"
  STDOUT.flush
 })
```
Now I assume that since @straight-shoota was using `puts` in his tests (I only saw [this file](https://github.com/straight-shoota/crystal/blob/feature/fiber-win32/fiber.cr) and assume that is the test he used), he got the same strange behaviour as I've been investigating here, so as a workaround we can use the way to print out as above but I guess that once the real reason is identified someone with better knowledge of why `puts` can cause this behaviour can fix it.

## Full working code example
```crystal
STACK_SIZE = 1024*1024*8
WORD_SIZE = sizeof(Void*)
SHADOW_SPACE_SIZE = 32

class Test
  property value : UInt64 = 0
  property stack = Array(UInt8).new(STACK_SIZE)
  property func : Proc(Void) = ->{}
  property rsp : UInt64 = 0

  def makecontext(proc : Proc)
    @func = proc

    s_ptr = @stack.to_unsafe.as(UInt8*) + STACK_SIZE # stack grows down
    s_ptr = Pointer(UInt8).new(s_ptr.address & ~15)  # align stack on 16 bytes

    # Double check the alignment to be sure
    if (s_ptr.address & 0xF) != 0
      raise Exception.new("Stack not aligned!")
    end

    s_start = s_ptr - SHADOW_SPACE_SIZE              # for initial resume

    @rsp = (s_start - WORD_SIZE).as(Void*).address   # last addressable pointer on the stack

    # Our entry
    s_start_ptr = s_start.as(UInt64*)
    s_start_ptr.value = ->start(Test).pointer.address

    # First parameter
    first_param = (s_start - 8).as(UInt64*)
    first_param.value = self.as(Void*).address
  end

  def run
    @func.call
    Process.exit(0)
  end
end

def start(f : Test)
  f.run
end

@[NoInline]
@[Naked]
def swap(data)
  {% if flag?(:win32) %}
  asm("
  pushq %rcx # search marker
  movq $0, %rsp
  popq %rcx
  "
  :: "r"(data) )
  
  {% else %}
  asm("
  pushq %rdi # search marker
  movq $0, %rsp
  popq %rdi
  "
  :: "r"(data))
  {% end %}
end

puts "start"
test = Test.new
test.makecontext(->{ 
  STDOUT << "Hello from new stack\n"
  STDOUT.flush
 })

swap(test.rsp)
```

**Comment by ysbaddaden** [comment]
:+1:

**Comment by cfsamson** [comment]
Closing this since I opened https://github.com/crystal-lang/crystal/issues/7955 which is the real reason causing this behavior.
