### ISSUE TITLE
brew man pages don't show up

### ISSUE THREAD

**Issue by rdp** [crystal-lang/crystal#7950]
on OS X
```
$ brew list
crystal	llvm...
$ man crystal
No manual entry for crystal
```

**Comment by wontruefree** [comment]
This should probably be added to
```bash
/usr/local/opt/crystal
```

some other brew formula do install to man pages. [example](https://github.com/Homebrew/homebrew-core/blob/5fb24a5c8e3be3efa85f787ed4c4e8fa96abb0b2/Formula/dasht.rb#L16)
```ruby

  def install
    bin.install Dir["bin/*"]
    man.install "man/man1"
  end
```

**Comment by RX14** [comment]
Please report this to homebrew where the formula is maintained.

**Comment by bcardiff** [comment]
@rdp brew formula includes now the manpages for crystal and shards.

**Comment by rdp** [comment]
Thanks much.
