### ISSUE TITLE
String.split on empty delimiter aka "123".split('') => ['1','2','3'] in Ruby but not in Crystal

### ISSUE THREAD

**Issue by SoldierCoder** [crystal-lang/crystal#7953]
# Submitting questions

If you have a question like "how do I do X?", this is not the right place for asking it. Please ask on the [Crystal Forum](https://forum.crystal-lang.org), on our combined [Gitter](https://gitter.im/crystal-lang/crystal)/[IRC](http://webchat.freenode.net/?channels=#crystal-lang) or on [StackOverflow](http://stackoverflow.com/questions/tagged/crystal-lang).

# Submitting bugs

Make sure to review these points before submitting issues - thank you!

- Make sure a similar issue doesn't exist yet: use the search box
- **Include reproducible code**: we should be able to paste it into an editor, compile and run it and get the same error as you. Otherwise it's impossible for us to reproduce the bug.
- Don't **only** use `play.crystal-lang.org` or `carc.in`: code might be lost and the issue will remain incomplete. Write code in the issue itself.
- Reduce code, if possible, to the minimum size that reproduces the bug.
- If all of the above is impossible due to a large project, create a branch that reproduces the bug and point us to it.
- Include Crystal compiler version (`crystal -v`) and OS. If possible, try to see if the bug still reproduces on master.

**Comment by SoldierCoder** [comment]
String.split in Ruby had a nice feature that is missing from Crystal.  "123".split('') in Ruby returns an array of those characters as strings.  That is, ['1','2','3'].  Crystal won't even let you call split with an empty delimiter.

**Comment by girng** [comment]
i think it's because `''` is a char literal in crystal, not a string


```crystal
test = "123".split("")

pp test
```

if you need them in char literals, do
```crystal
test = "123".chars

pp test
```
