### ISSUE TITLE
Markdown is displayed differently in docs

### ISSUE THREAD

**Issue by cheeze2000** [crystal-lang/crystal#7954]
I commented a method like such.
```cr
# - cat
# - dog
def animal
end
```

Using `crystal docs`, the docs generated shows that the markdown is displayed differently. This is how it looks like in the "Instance Method Summary".
![2019-07-07_09-21](https://user-images.githubusercontent.com/26966445/60762696-ada11900-a098-11e9-933f-a3db67ae5629.png) 

However, it looks like this in the "Instance Method Detail".
![2019-07-07_09-23](https://user-images.githubusercontent.com/26966445/60762714-e17c3e80-a098-11e9-8e20-810368acbe31.png)

```bash
$ crystal -v
Crystal 0.29.0 (2019-06-06)

LLVM: 6.0.1
Default target: x86_64-pc-linux-gnu
```

OS: Manjaro Linux x86_64
Kernel: 4.19.56-1-MANJARO

**Comment by girng** [comment]
so the issue is basically markdown lists are not supported in    `instance method summary` section?

is this a bug or intended?

**Comment by Blacksmoke16** [comment]
@cheeze2000 The summary only show the first line/sentence.  If anything I'd say this is an issue with the logic that does that.  However I don't think it should show the list, as the summary is only a single line.  

If anything (and arguably better) can do something like

```cr
# Returns the animal associated with `self`.
#
# - cat
# - dog
def animal
```

**Comment by cheeze2000** [comment]
You're right. There is a reason why it is called the summary. Thank you for the help.
