### ISSUE TITLE
Fiber.yield does not work

### ISSUE THREAD

**Issue by sbvitok** [crystal-lang/crystal#7961]
code
```
channel = Channel(Int32).new
spawn do
	loop do
		puts channel.receive rescue break
		sleep 2
		puts 123
	end
end
a = [1,2,3]
a.each do |b|
	channel.send(b)
end
channel.close
Fiber.yield
```
output:
```
viktor@viktor:~/classification$ crystal run src/test.cr 
1
123
2
123
3
viktor@viktor:~/classification$
```
why Fiber.yield dose not wait sleeping thread?

From offical examples, this work:
```
channel = Channel(Int32).new

spawn do
  puts "Before send"
  channel.send(1)
  puts "After send"
end

spawn do
  puts "Before receive"
  puts channel.receive
  puts "After receive"
end

puts "Before yield"
Fiber.yield
puts "After yield"
```
output:
```
viktor@viktor:~/classification$ crystal run src/test2.cr 
Before yield
Before send
Before receive
1
After receive
After send
After yield
viktor@viktor:~/classification$
```
But if I put a sleep in first spawn block, this example dose not work:

```
channel = Channel(Int32).new

spawn do
  sleep 1
  puts "Before send"
  channel.send(1)
  puts "After send"
end

spawn do
  puts "Before receive"
  puts channel.receive
  puts "After receive"
end

puts "Before yield"
Fiber.yield
puts "After yield"
```
output:
```
viktor@viktor:~/classification$ crystal run src/test2.cr 
Before yield
Before receive
After yield
viktor@viktor:~/classification$
```
Why?
I tested code from first example on multiple versions of crystal and see that a bug can be reprodusde from 0.13.0 up to 0.29.0 version

**Comment by oprypin** [comment]
> why Fiber.yield dose not wait sleeping thread?

Because that's not what it's supposed to do 👀

**Comment by oprypin** [comment]
https://crystal-lang.org/reference/guides/concurrency.html
Start from the first mention of `yield` (or just from the start...)
The example you brought up is kind of a bad one. But there is no bug here.

**Comment by ysbaddaden** [comment]
@oprypin said it all. `Fiber.yield` merely gives a chance for another fiber to run, waiting for nothing but a next chance to run.

Please ask questions on the forum, thanks!

**Comment by asterite** [comment]
Just in case:
- you can replace `Fiber.yield` with `sleep()` if you need it to wait forever
- else you must use some `channel.receive` instead of `Fiber.yield` and on the `spawn` send to that channel when your work is ready

When the main fiber exists, the entire program exits.
