### ISSUE TITLE
XML::Builder allows creating elements with invalid names

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#7963]
Noticed in https://github.com/Blacksmoke16/oq/issues/9.

```cr
require "xml"

xml = XML.build(indent: 2) do |xml|
  xml.element("1") do
    xml.text "foo"
  end
end

puts xml
<?xml version="1.0"?>
<1>foo</1>
```

```cr
require "xml"

xml = XML.build(indent: 2) do |xml|
  xml.element("a b=\"c\"") do
    xml.text "foo"
  end
end

puts xml
<?xml version="1.0"?>
<a b="c">foo</a b="c">
```

I would expect this to error since an element name cannot start with a number nor contain a space, equal sign etc as defined [here](https://www.w3.org/TR/2006/REC-xml11-20060816/#NT-Name).

**Comment by oprypin** [comment]
Might be classified as a security bug
