### ISSUE TITLE
YAML::Schema::Core.parse_scalar doesn't parse strings with tags

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#7984]
```cr
require "yaml"

YAML::Schema::Core.parse_scalar "0.5" # => 0.5
YAML::Schema::Core.parse_scalar "!!str 0.5" # => "!!str 0.5"
```

I would have expected the second to output `"0.5"`

```cr
yaml = YAML::PullParser.new("--- !!str 0.5")

yaml.read_stream_start
yaml.read_document_start

YAML::Schema::Core.parse_scalar yaml # => "0.5"
```

Example using the `YAML::PullParser` overload works correctly.

**Comment by asterite** [comment]
Yes, `parse_scalar`, when given a String, expects the string without the tag. Then it will check if it looks like a number, bool, date, etc.

When parsing with pull parser libyaml gives the tag in a separate attribute that is process apart from the content string. First the tag is processed: if it's `!!str` then it's definitely a string. If there's no tag then the other `parse_scalar` method is called which will return a `Float64` for `0.5`.

Why do you need this?

**Comment by Blacksmoke16** [comment]
For the streaming stuff `oq` was treating both variants as the number.  But I was able to just pass the pull parser in versus the string value and it works now.

But if this is expected behavior, you can go ahead and close this.

**Comment by asterite** [comment]
Yes, let's close this. Maybe eventually we can add a method that considers the tag. The docs right now say "Parses a string according to the core schema, assuming the string had a plain style". There's no mention to tags, maybe we can add that... not sure.
