### ISSUE TITLE
Formatter bug with indentation of multi-line strings in inline macros

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#7991]
The formatter adds unnecessary and unlimited indentation to multi-line strings inside an inline macro.

```cr
{% if true %}
  "
  foo"
{% end %}
```
Formatting the above code results in this:
```cr
{% if true %}
  "
    foo"
{% end %}
```
Running the formatter again, it adds another level of indentation (and keeps going).
```cr
{% if true %}
  "
      foo"
{% end %}
```
This is particularly annoying because the formatter should be idempotent and not change already formatted code again in each invocation.

This was not present in 0.29.0 since formatting inside inline macros was only enabled in #7889.

**Comment by asterite** [comment]
I'll see if I can fix it before 0.30.0
