### ISSUE TITLE
Regression with cookies

### ISSUE THREAD

**Issue by bcardiff** [crystal-lang/crystal#8020]
After #7997, when creating cookies from the server side to send to the client, the user will be obliged to use `URI.encode_www_form`. It's a bit weird as an API.

```crystal
require "http"

a = HTTP::Cookie.new(name: "a", value: "1+2")
pp! a.value # => "1 2"

b = HTTP::Cookie.new(name: "b", value: URI.encode_www_form("1+2"))
pp! b.value # => "1+2"

cookies = HTTP::Cookies.new
cookies["a"] = a
cookies["a2"] = "1+2"
cookies["b"] = b
cookies["b2"] = URI.encode_www_form("1+2")
pp! cookies.map { |c| {c.name, c.value} } # => [{"a", "1 2"}, {"a2", "1 2"}, {"b", "1+2"}, {"b2", "1+2"}]
```

Before this PR we got, this used to work this way.

```crystal
require "http"

a = HTTP::Cookie.new(name: "a", value: "1+2")
pp! a.value # => "1+2"

cookies = HTTP::Cookies.new
cookies["a"] = a
cookies["a2"] = "1+2"
pp! cookies.map { |c| {c.name, c.value} } # => [{"a", "1+2"}, {"a2", "1+2"}]
```

I discovered this while testing lucky against nightlies. There, some cookies are encrypted introducing a `+` somewhere in the cookie value.

I think `Cookie.new` should not call `URI.decode_www_form`, leaving that responsibility to the parser. Sounds good?

**Comment by straight-shoota** [comment]
Yes, the regular constructor should receive plain arguments. This was technically already wrong before #7997 but now with decoding `+` as whitespace it has become more apparent.
