### ISSUE TITLE
Default Library paths are not optional (Cross-compilation)

### ISSUE THREAD

**Issue by dburnsii** [crystal-lang/crystal#8022]
The following code includes the `/lib` and `/usr/lib` folders on Linux by default:

https://github.com/crystal-lang/crystal/blob/5330f5b4e9aa81a6438d44bcd474b74e8d92db00/src/compiler/crystal/codegen/link.cr#L107

This is unsafe for cross compilation. I'm currently using Crystal to build a project with Yocto, and using the cross-compile option still includes these paths by default, which causes QA errors. In most cases, `ls` is already configured to search these paths, otherwise it could be told to with the `--link-flags` option. My suggestion is just to remove the hardcoded paths, however I realize there could be implications for existing applications that do not explicitly add these paths because they are included by default. Is there a good way to do this that would work across the board?

**Comment by refi64** [comment]
Maybe Crystal can run the linker and grab the paths from there like
demonstrated [here](https://stackoverflow.com/a/29546339/2097780)?

**Comment by RX14** [comment]
They should be removed. I've been meaning to do this for a long time but `crystal` needs to assume a C toolchain which is set up with the correct paths by default.
