### ISSUE TITLE
Generated README is not rendered properly when rendered with `docs` command

### ISSUE THREAD

**Issue by denolfe** [crystal-lang/crystal#8023]
The default README file that is generated using `crystal init lib <name>` then `crystal docs` is not rendered properly in the browser.

## Steps to reproduce

```sh
crystal init lib my-lib
cd my-lib
crystal docs
```
- Serve the docs and open in browser

On the README page under Installation, the yaml block and number 2 are not rendered properly. I've also noticed this on other repos' documentation pages as well.

![image](https://user-images.githubusercontent.com/65888/62246315-5f3e1c00-b3b1-11e9-9397-9fa168f7f041.png)

**Comment by asterite** [comment]
Thank you for the report!

Basically a duplicate of #4613 . We have our own, broken, implementation of Markdown. Eventually we should fix it, use some other implementation, or even extract the doc generator to a separate tool that could you any markdown shard.
