### ISSUE TITLE
Should Char::Reader be optimized for ASCII-only strings?

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#8039]
Currently there are still many cases where ASCII optimizations are possible, for example in `String#lchop?`:
```cr
def lchop? : String?
  return if empty?

  reader = Char::Reader.new(self)
  unsafe_byte_slice_string(reader.current_char_width, bytesize - reader.current_char_width)
end
```
This could be:
```cr
def lchop? : String?
  return if empty?

  if ascii_only?
    unsafe_byte_slice_string(1, bytesize - 1)
  else
    reader = Char::Reader.new(self)
    unsafe_byte_slice_string(reader.current_char_width, bytesize - reader.current_char_width)
  end
end
```
And now `lchop?` is already `1.68×` faster for ASCII-only strings, because all of [this](https://github.com/crystal-lang/crystal/blob/cbf651affab414c0f8f02c5d4ed3c77fd69b744d/src/char/reader.cr#L58) code is avoided, including the `decode_current_char`.
That's just one example, there are more, like [`String#split(Char)`](https://github.com/crystal-lang/crystal/blob/b5289b6df1985364c7bbe24c7d2f9b67d6e33d3d/src/string.cr#L3173) for example.

I wonder if we should keep working around `Char::Reader`'s inability to efficiently handle ASCII strings with an `ascii_only?` branch or if we should once and for all make `Char::Reader` efficient for ASCII strings. It would possibly avoid all of [this](https://github.com/crystal-lang/crystal/blob/b5289b6df1985364c7bbe24c7d2f9b67d6e33d3d/src/string.cr#L2451), [this](https://github.com/crystal-lang/crystal/blob/b5289b6df1985364c7bbe24c7d2f9b67d6e33d3d/src/string.cr#L3772) and more code and speed up code outside of the standard library that uses `Char::Reader`, like the [lexer](https://github.com/crystal-lang/crystal/blob/b5289b6df1985364c7bbe24c7d2f9b67d6e33d3d/src/compiler/crystal/syntax/lexer.cr#L13).

**Comment by asterite** [comment]
Hey, that's a really good idea! I didn't realize we could optimize char reader for ascii only. That said, I think it'll still be faster to branch on String, but this is just a guess. I'll give it a try and benchmark it.

**Comment by r00ster91** [comment]
Well it seems there already is some kind of optimization here: https://github.com/crystal-lang/crystal/blob/cbf651affab414c0f8f02c5d4ed3c77fd69b744d/src/char/reader.cr#L189
But `Char::Reader` is still slower than `String#each_char` for ASCII strings. The problem is probably all the instance variable stuff it's doing there: [`reader.cr:252`](https://github.com/crystal-lang/crystal/blob/cbf651affab414c0f8f02c5d4ed3c77fd69b744d/src/char/reader.cr#L252) [`reader.cr:59`](https://github.com/crystal-lang/crystal/blob/cbf651affab414c0f8f02c5d4ed3c77fd69b744d/src/char/reader.cr#L59). There's probably not much to do to improve the speed.

**Comment by asterite** [comment]
@r00ster91 That's not an optimization, that's the regular decoding path. I tried optimizing it and there's a big difference. I'll send a PR later.

**Comment by asterite** [comment]
Actually, I tried a few things now and couldn't find a difference. I guess checking for that byte instead of checking for a boolean is almost the same. So we can close this...
