### ISSUE TITLE
Document JSON::PullParser

### ISSUE THREAD

**Issue by girng** [crystal-lang/crystal#8050]
I think more explicit / expressive errors for JSON::PullParser would benefit future developers.

Example code:
```
require "json"

temp_data = %q(
{"1":{"quest_rewards":"40;42","quest_exp": 0}}
)


struct Quest_Rewards
  def self.from_json(value : JSON::PullParser)
    #temp_value = value.read_string
    #temp_value.size > 0 ? temp_value.split(";").map &.to_i : Array(Int32).new
    value.read_string.size > 0 ? value.read_string.split(";").map &.to_i : Array(Int32).new
  end
end

class Quest_Schema
  JSON.mapping({
    quest_rewards:     {type: Array(Int32), converter: Quest_Rewards},
    quest_exp: Int32
  })
end

new_data = Hash(String, Quest_Schema).from_json(temp_data)
```

The exception is:
> Unhandled exception: Invalid Int32: quest_exp (ArgumentError)

That threw me off! The real **underlying** issue with my example is [read_string](https://github.com/crystal-lang/crystal/blob/fd0780c3a4ef972a6090e09abc9b09a0e39345ff/src/json/pull_parser.cr#L218) is being used twice. `read_string` calls `read_next`, thus advancing to the next key. I thought `read_string` could be used any number of times to get the value, did not know  it calls `read_next`.

 If `read_string` **is not supposed to be** called twice in `from_json`, I think an exception for that would help a lot.

**Comment by straight-shoota** [comment]
I don't think there is anything we could do here. `read_string` is supposed to be called as often as you need to read a string. If you do that wrong (i.e. call it too often) that simply means your converter is bugged. And honestly, the error message is pretty good.

**Comment by girng** [comment]
I initially thought the error message was related to `quest_exp`.  But after making a reduced example, it doesn't seem related to `quest_exp` at all.

**Comment by asterite** [comment]
I think json pull parser lacks documentation (there's none). Maybe we can rename read to next? But for me reading is advancing the pull parser.

**Comment by straight-shoota** [comment]
No, it's not related to the `quest_exp` mapping. It's an error in your converter and the stack trace should point you to the faulty location.

**Comment by girng** [comment]
Maybe just adding a bit of documentation to `read_string` is the solution here

**Comment by coopergillan** [comment]
Looks like this can be closed due to https://github.com/crystal-lang/crystal/pull/9983, correct?

**Comment by asterite** [comment]
@coopergillan Thanks. It seems not everyone knows about "Fixes #N" 🤷
