### ISSUE TITLE
[] methods are not inlined by default

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#8051]
I've noticed this:
```cr
require "benchmark"

Benchmark.ips do |bm|
  bm.report "[0]" do
    "hello"[0]
  end

  bm.report "char_at(0)" do
    "hello".char_at(0) { raise IndexError.new }
  end
end
```
Both benchmark report blocks do exactly the same thing but the second one is faster.
```
       [0] 305.23M (  3.28ns) (± 7.23%)  0.0B/op   2.01× slower
char_at(0) 612.96M (  1.63ns) (± 6.46%)  0.0B/op        fastest
```
For `[0]` an additional function call seems to be done. This is fixed by applying `@[AlwaysInline]` to https://github.com/crystal-lang/crystal/blob/cbf651affab414c0f8f02c5d4ed3c77fd69b744d/src/string.cr#L734

Is this some kind of bug? Shouldn't `[0]` be inlined by the compiler by default?
Or should we annotate every `[]` method with `@[AlwaysInline]` now?
String's `[]` is used pretty much everywhere so I think this is an important perfomance opportunity we shouldn't miss.

**Comment by ysbaddaden** [comment]
This is a micro benchmark; LLVM will only consider inlining a function after some heuristics, which is probably not met here.

**Comment by straight-shoota** [comment]
I'm not sure about the inlining semantics, but I doubt your assessment about implications for `String`. When you need optimal performance, you would work with byte indices anyway.

**Comment by r00ster91** [comment]
> This is a micro benchmark; LLVM will only consider inlining a function after some heuristics, which is probably not met here.

As far as I know Crystal by itself also does a lot of inlining so this should probably be done on Crystal's side then that some logic is added that detects this case and inlines it as well.

Also:
```cr
require "benchmark"

class String
  def method(index : Int)
    self.char_at(index) { raise IndexError.new }
  end
end

Benchmark.ips do |bm|
  bm.report "[0]" do
    "hello"[0]
  end

  bm.report "char_at(0)" do
    "hello".char_at(0) { raise IndexError.new }
  end

  bm.report "method" do
    "hello".method(0)
  end
end
```
```
       [0] 323.23M (  3.09ns) (± 6.10%)  0.0B/op   1.85× slower
char_at(0) 596.40M (  1.68ns) (± 7.00%)  0.0B/op        fastest
    method 593.89M (  1.68ns) (± 7.19%)  0.0B/op   1.00× slower
```
Here `method` is exactly the same as `[]`, the only difference is that the method `method` is named "method", not "[]". But `method` with the same code gets inlined while `[]` gets not inlined.
The compiler seems to have some problems with inlining `[]`, or it maybe ignores those methods for some reason?

**Comment by asterite** [comment]
Note that a method with a block is always inlined by the compiler because of how the language works (because you can `return` from a block). That's why you see it inlined. Now `String#[]` does a lot!: it checks for ascii only, it creates a char reader, etc. That's why probably LLVM decides not to inline it. Maybe LLVM is right, it would be too costly to inline that call every time.

We could tell it to always inline it, but with a 1ns difference I don't know if it's worth it.

**Comment by r00ster91** [comment]
> Now `String#[]` does a lot!: it checks for ascii only, it creates a char reader, etc. That's why probably LLVM decides not to inline it. 

But when I put the exactly same stuff in a different method that is not named "[]" then it does inline it (as I did above). So I don't think that's the problem.

It doesn't make much sense to me that the name I a method has decides whether the method gets inlined or not. That should rather be decided based on the content of the method. So I think we should have a talk with LLVM and tell it to inline those methods too.

**Comment by jhass** [comment]
A single usage is more likely to get inlined. Inlining always is a tradeoff between performance and the size of the generated binary. Inlining a function that's called once is pretty much a no-brainer given that operation does not increase code size.

**Comment by RX14** [comment]
This is invalid. `[]` is *not* treated any differently than other methods. LLVM does the inlining heuristics and they are tuned to work for *real programs* and not micro benchmarks.
