### ISSUE TITLE
XML#parse returning wrong results

### ISSUE THREAD

**Issue by lribeiro** [crystal-lang/crystal#8054]
I've reduce it as much I could.
The issue seems to be with the attribute format "\3-"

```
require "xml"

a = 
<<-XML
<a path="\\a\3-" last="0">
  <b size="1" ></b>
</a>
XML

xmla = XML.parse(a)
#xmla = '<?xml version="1.0"?><a path="\a"/>'
```

I would expect to get xmla equal to whatever it parsed originally.
We actually found this, because we were expecting children nodes, and xmla.children returns an empty NodeSet

this works 
```
b = 
<<-XML
<a path="\\3-" last="0">
  <b size="1" ></b>
</a>
XML

xmlb = XML.parse(b)

#xmlb = '<?xml version="1.0"?>
<a path="\3-" last="0">
  <b size="1"/>
</a>'
```

```bash
crystal -v
Crystal 0.29.0 (2019-06-06)

LLVM: 6.0.1
Default target: x86_64-apple-macosx
```

**Comment by asterite** [comment]
"\3" is character is unicode codepoint 3, which is invalid in an XML.

You can check the errors with the `errors` getter:

```crystal
require "xml"

a =
  <<-XML
<a path="\\a\3-" last="0">
  <b size="1" ></b>
</a>
XML

xmla = XML.parse(a)
p xmla.errors # => [#<XML::Error:invalid character in attribute value>, #<XML::Error:attributes construct error>, #<XML::Error:Couldn't find end of Start Tag a line 1>, #<XML::Error:Extra content at the end of the document>]
```

https://play.crystal-lang.org/#/r/7d53

Please close if you think this solves your issue.

**Comment by asterite** [comment]
That said, the docs are a bit lacking in this regard, they don't mention that `parse` is always successful but you get errors in the `errors` getter (this is done exactly like in Nokogiri because some errors might be ignored, specially when dealing with malformed but still "valid" HTML).

**Comment by lribeiro** [comment]
Thanks for the errors, tip.
