### ISSUE TITLE
More frequent failures of test_linux32 CI build

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#8057]
The `test_linux32` build on circle CI is failing more and more often. I guess we're at about every third one. Maybe even more.

This is especially bad when it hinders the nightly builds to complete (see
https://circleci.com/workflow-run/2b0bd087-abef-43f5-8c59-df88ea695166 for example). The last successful nightly build was four days ago.

We've already disabled 32-bit builds on travis-ci for the same reasons (#7263). But I wouldn't necessarily disable it entirely, having a reliable 32-bit build is great. It could be a short term solution, though until we implement a proper solution (for example https://github.com/crystal-lang/crystal/pull/7263#issuecomment-516839791)

Related: #6961

**Comment by asterite** [comment]
I wonder whether running smaller batches of specs instead of just `std_spec` and `compiler_spec` might solve the problem. I don't have time to try it right now but any help is welcome!

**Comment by straight-shoota** [comment]
There have been no nightly builds for the last days, because `test_linux32` keeps to consistently run out of memory.
Latest example: https://circleci.com/gh/crystal-lang/crystal/28939
It seems to happen while compiling an example in the compiler specs, not while compiling the specs themselves.

**Comment by wontruefree** [comment]
This is timing out at 10 minutes.  What happens if the timeout is increased?

**Comment by j8r** [comment]
Related to #9463 ? I think the issue can be closed now.
