### ISSUE TITLE
Shards version needs to be updated to latest release (0.9.0) in linux distribution package

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/crystal#8059]
I just upgraded crystal to 0.30.0 which created a `shards` binary, but it's for shards 0.8.1. In this case, [0.9.0](https://github.com/crystal-lang/shards/commit/81ea69333b0b020eccdfd6c8f6f427e9724e135a) has been out since June 12th.

```
[15:06PM] shards (master)$ /usr/local/Cellar/crystal/0.30.0_1/bin/shards --version
Shards 0.8.1 (2019-08-05)
[15:07PM] shards (master)$ /usr/local/Cellar/crystal/0.30.0_1/bin/crystal -v
Crystal 0.30.0 (2019-08-05)

LLVM: 8.0.0
Default target: x86_64-apple-macosx
```

Maybe this was just missed during the release?

**Comment by straight-shoota** [comment]
Confirmed, the shards version was not updated in https://github.com/crystal-lang/distribution-scripts

**Comment by jwoertink** [comment]
Sweet. Thanks for finding that @straight-shoota.

**Comment by ysbaddaden** [comment]
It has a critical bug that must be fixed (fills up memory and crashes) when you many shards of versions must be considered.

**Comment by straight-shoota** [comment]
Shards has long been updated.
