### ISSUE TITLE
generic metaclass overload only matches struct metaclasses but not class metaclasses

### ISSUE THREAD

**Issue by kyku** [crystal-lang/crystal#8071]
I’m doing some type dispatching based on *.class overloading. I handle all nullable types in a generic function, so that I don’t have to repeat myself. This seems to work fine both for built-in types and user-defined classes, but not with String?. Take a look at the following example:

```
def x(t : Int32.class);  puts t;  end
def x(t : String.class); puts t; end
def x(t : (T | Nil).class) forall T; puts t; end
```
The result of the above is:

> x(Int32) # => Int32
> x(Int32?) # => (Int32 | Nil)
> x(String) # => String

However; the following line yields compile time error:
```
x(String?)
```

> no overload matches ‘x’ with type (String | Nil).class
> Overloads are:
> 
> x(t : Int32.class)
> x(t : String.class)
> x(t : T | Nil.class)

**Comment by jhass** [comment]
The difference seems to be structs vs classes https://carc.in/#/r/7e3u

```cr
struct A; end
class B; end

def x(t : A.class);  puts t;  end
def x(t : B.class); puts t; end
def x(t : (T | Nil).class) forall T; puts t; end

x(B?)
```

**Comment by HertzDevil** [comment]
Reduced:

```crystal
def foo(x : T?) forall T
end

foo("" || nil)
```

```
Error: no overload matches 'foo' with type (String | Nil)

Overloads are:
 - foo(x : T | ::Nil)
Couldn't find overloads for these types:
 - foo(x : String)
```
