### ISSUE TITLE
Depreciated URI.escape warning

### ISSUE THREAD

**Issue by lebogan** [crystal-lang/crystal#8079]
Just a warning note on compile with Crystal 0.30.1 on Fedora 30 running on vagrant vm with Virtualbox 6.0 provider. Error didn't occur on Crystal 0.30.0. Also happened on  a Centos7 vm.

Ran similar test compiles on my host machine running Fedora 30. Same error with 0.30.1 but, ok on 0.30.0.
```
crystal build src/backup.cr -o bin/backup --release --warnings all --error-on-warnings
In /usr/share/crystal/src/uri/encoding.cr:175:3

 175 | def self.escape(string : String, space_to_plus = false)
       ^-----
Warning: Deprecated URI.escape. Use .encode or .encode_www_form instead

A total of 1 warnings were found.
make: *** [Makefile:21: bin/backup] Error 1
```
Thank you for this language. It is a joy to code with!

**Comment by Blacksmoke16** [comment]
This is probably more appropriate for the forums/gitter chat.  However I'm assuming the answer to your question is that in Crystal `0.30.0` that method is now `URI.encode_www_form` as per https://github.com/crystal-lang/crystal/pull/7997.

**Comment by lebogan** [comment]
Ok. Will do.
