### ISSUE TITLE
Support JSON/YAML parsing of NamedTuple with nilable field

### ISSUE THREAD

**Issue by fenicks** [crystal-lang/crystal#8089]
Actually class or struct with JSON.mapping could have nilable field.
It's really needed with NoSQL databases driver who need crystal types for adding behavior.

This feature could be used with question mark (_?_) like this : 

```crystal
alias Car = NamedTuple (
  name: String,
  type: String,
  clients: Array(String)?
)

```

**Comment by asterite** [comment]
To clarify this, when deserializing a `NamedTuple` with a nilable field from JSON/YAML, if that field is missing that you get an exception instead of it parsing correctly.

**Comment by fenicks** [comment]
Absolutely, parsing correctly even if field is missing do the trick. :ok_hand:
