### ISSUE TITLE
Add `JSON::Builder#depth`

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#8094]
`JSON::Builder` uses a private `current_indent` ivar that represents the current depth/nesting level of the builder.

I propose to expose this value as `#depth`, thus making it available within custom converters as well as direct usages of the builder; versus having to keep track of it manually.

**Comment by straight-shoota** [comment]
Could you describe a usecase for this? I'm under the assumption that contextual information should be completely irrelevant for converters.

**Comment by Blacksmoke16** [comment]
Actually I'm going to close this for now.  I think I was thinking of `JSON::PullParser`.  I can reopen it later once I remember why I needed this...
