### ISSUE TITLE
Linking to another class' initializer

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#8095]
```cr
class Foo
  # Hello
  def initialize
  end
end

class Bar < Foo
  # See `Foo.new` or `Foo#new` or `Foo#initialize` or `Foo.initialize`.
  def initialize
    super
  end
end
```

It seems trying to link to another class' initializer is missing from the generated docs tool.

![image](https://user-images.githubusercontent.com/12136995/63216614-d0960280-c105-11e9-9ae7-a82363e61408.png)

**Comment by edwinacunav** [comment]
```
class Foo
  # Hello
  def initialize
    puts "I'm Foo!"
  end
end

class Bar < Foo
  # See `Foo.new` or `Foo#new` or `Foo#initialize` or `Foo.initialize`.
  def initialize
    super
    puts "OK! OK! I'm Bar!"
  end
end

Foo.new
Bar.new
```
It's weird because I was able to compile it and run my ./foobar binary without any issues. O_O

> I'm Foo!
I'm Foo!
OK! OK! I'm Bar!

**Comment by bew** [comment]
@edwinacunav the issue is not about running the exemple, but about the generated documentation. Writting `Foo.bar` for exemple would create a link to the documentation of `Foo.bar`, and it doesn't work for `Foo.new`, hence this issue.
