### ISSUE TITLE
Cannot build crystal scripts

### ISSUE THREAD

**Issue by edwinacunav** [crystal-lang/crystal#8099]
Hi guys! I want to let you know that whenever I create a simple crystal script like the following:
puts "Hello Crystal!", Crystal::VERSION
Hello Crystal!
0.30.1
Then I run "crystal hello.cr" or "crystal run hello.cr" and everything gets printed as expected. **BUT** if I use "crystal build hello.cr" and then "crystal hello" or "crystal run hello", it just fails throwing the error found below.

In hello:1:1
 1 | ELF>�2@X�@8
     ^
Error: unknown token: '\u{7f}'

Crystal 0.30.1 [5e6a1b672] (2019-08-12)
LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu

I installed crystal on my Kubuntu Bionic distro.

Sidenote: By the way, is it normal for the executable to use over 1 MB for a single line of code?

**Comment by yxhuvud** [comment]
Not a bug. You are trying to compile the executable that is already compiled. if you just want to run it, try `./hello`

Regarding your sidenote, try adding `--release` to your arguments, ie  `crystal build hello.cr --release` and see if you still think it is too large.

**Comment by jhass** [comment]
Also about the size, please realize that this single line of code pulls in a couple hundred if not thousand lines of code since all IO in crystal goes through an event loop.

**Comment by edwinacunav** [comment]
Well, I tried the --release flag and it reduced the file size about 50% so I guess it's decent. Thank you for letting me know what was happening under the hood.
