### ISSUE TITLE
install crystal by conda ？ 

### ISSUE THREAD

**Issue by orangeSi** [crystal-lang/crystal#8102]
# Submitting questions

It is possible to install crystal by conda(https://anaconda.org/anaconda/conda） ?
because I have no root permission to install the dependence of crystal.

# Submitting bugs
not bug~

**Comment by orangeSi** [comment]
had fixed this by `conda install -c conda-forge libevent pcre -n crystal `

**Comment by bcardiff** [comment]
I'm glad you've found a workaround.

We don't use conda.
Depending on the platform you can download .tar.gz from GitHub releases and use it directly.
snapcraft.io might also be an option, but I'm not 100% sure.

Please use https://forum.crystal-lang.org to keep this thread if needed.
