### ISSUE TITLE
Tiny bugs in the Markdown library

### ISSUE THREAD

**Issue by Hentioe** [crystal-lang/crystal#8113]
# Submitting questions

When I used the Markdown library to convert Markdown text to HTML, I found a small problem.
I tried to solve this problem, but I didn't find the reason in a short time.

# Submitting bugs

Code:

``` crystal
require "markdown"

mdtext = "[[google]](https://www.google.com)"
html = Markdown.to_html mdtext

puts html # => <p><a href="https://www.google.com">[google</a></p>
```

You can see that it has one `]` missing.

Play address: https://play.crystal-lang.org/#/r/7g29

Version:
```
~ crystal version
Crystal 0.30.1 [5e6a1b672] (2019-08-12)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by straight-shoota** [comment]
The stdlib Markdown implementation has dozens of bugs and missing features. It should be considered broken, and I don't recommend using it.
I'd suggest to try https://github.com/icyleaf/markd instead, which is a solid and feature-rich Markdown implementation.

**Comment by Hentioe** [comment]
Ok, thank you for your suggestion. It seems that this standard library is still immature and the problem should be a lot. I closed this issue.
