### ISSUE TITLE
Make aliases clearer in API docs

### ISSUE THREAD

**Issue by j8r** [crystal-lang/crystal#8122]
## Description

After looking at this [PR](https://github.com/crystal-lang/crystal/pull/8121) and how aliases are mentioned in the API docs, I came to the conclusion that it would be better to show more clearly and consistently which method alias to another.

## Example

It can be inspired by `delegate` and `forward_missing_to`:
```cr
alias_method :<<, to: push
```

Or it may be possible to use annotations:
```cr
@[Aliases("first_alias", "second_alias")]
def root_method
end
```

## Proposed features
1. Adding a macro (or an annotation) expanding to methods calling the root method, and providing a way for the API docs to know to which root method it alias. It can be an annotation `@[Alias("root_method")]` or a comment `# :alias: root_method`.
2. In the API docs method comments, having an `Alias` colored block, very similar to `Deprecated`, with a link to the root method at the right.
3. I don't know if and how difficult it would be to do, mentioning the aliases in the root method can be a plus too.

**Comment by j8r** [comment]
Note: I don't really like aliases, this proposal isn't meant to encourage them, but making them clearer.
Then this will be even possible to IDE to show method aliases, when using tools like [scry](https://github.com/crystal-lang-tools/scry).

**Comment by jhass** [comment]
Somebody has a list of current aliases where this would be useful? I can see a useful distinction between pure aliases and methods with different generalized contracts that happen to do the same operation on some types.

**Comment by j8r** [comment]
Ok, so just having a standard way to say that a method in an alias to another:
```cr
@[Alias("push")]
# or
# :alias: push 
def <<
end
```
And the API docs do the rest. It would be great this can be processed by scry, to show us in the autocomplete that the method is an alias to another.

**Comment by j8r** [comment]
@Blacksmoke16 This means to parse like ``.starts_with?("Alias for `")``. Definitely doesn't look good.
I think the best is to use a documented annotation, easily usable by everyone.
Possibly, a tool can even use this (ameba?) to enforce a style.

**Comment by j8r** [comment]
For example in [ruby-docs](https://ruby-doc.org/stdlib-2.6.3/libdoc/set/rdoc/Set.html#method-i-7C), there is a useful `Also aliased as: +, union` and ` Alias for: | `.
In [set.rb](https://github.com/ruby/ruby/blob/master/lib/set.rb#L457), there is `alias + |` and `alias union |` defined.
Or we can add this manually.

**Comment by bew** [comment]
If we ever do that, I'd pick the doc keyword `:alias:`, as in:
```cr
# :alias: #foo .bar Foo.baz
def method
end
```

**Comment by straight-shoota** [comment]
CLosing. Crystal aims at avoiding aliases. Adding a feature for better alias support is both counterproductive to that goal, and plainly unnecessary.
The failure to produce meaningful real examples supports this assessment.

Methods like `Set#+` and `Set#|` are explicitly *not* aliases. The `+` and `|` operators for collections have different semantics and just happen to share the same implementation for `Set`.
