### ISSUE TITLE
Add ids to headings in generated docs

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#8127]
This feature is intended to be specific to the generated docs, but would require updates to the markdown module.  However, https://github.com/crystal-lang/crystal/pull/8115 makes that a non-issue.

I propose to:
* Add ids to the headings in the docs. 
  * Would allow linking directly to a section using the ids as targets for `#some-heading`.
* Have some easier way to link to a specific section.
  * Something like how Github does it, showing an icon you can click next to a heading that scrolls you down to that section.
  * Having the link copy the link to your clipboard would also be a nice to have.

Having this would make documenting shards directly within the API docs much much more user friendly and allow for more specific links to other sections within the docs themselves.

**Comment by absolutejam** [comment]
It'd also be awesome to provide functionality like Elixir's Hexdocs, where you can provide the full name of a symbol (eg. `Foo.Bar.baz/2` in Elixir) in documentation comments and it will automatically link to it.

**Comment by asterite** [comment]
> It'd also be awesome to provide functionality like Elixir's Hexdocs, where you can provide the full name of a symbol (eg. Foo.Bar.baz/2 in Elixir) in documentation comments and it will automatically link to it.

You can already do that. For example `Foo.bar`, `Foo#bar`, `#baz`, `#qux(x, y)`, etc.

**Comment by straight-shoota** [comment]
With overloads based on argument types it can quickly get pretty verbose. But I guess there's no way around that.

**Comment by absolutejam** [comment]
> > It'd also be awesome to provide functionality like Elixir's Hexdocs, where you can provide the full name of a symbol (eg. Foo.Bar.baz/2 in Elixir) in documentation comments and it will automatically link to it.
> 
> You can already do that. For example `Foo.bar`, `Foo#bar`, `#baz`, `#qux(x, y)`, etc.

I could have sworn I tried this before 🤦‍♂  This is awesome, thanks.
