### ISSUE TITLE
XML::Type has wrong names

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#8129]
I noticed last night that `XML::Type` member names seem to not be correct.  For example:

https://play.crystal-lang.org/#/r/7gwt

Based on https://www.gnu.org/software/dotgnu/pnetlib-doc/System/Xml/XmlNodeType.html it looks like the `DTD_NODE` should be like `SIG_WHITESPACE` and `ELEMENT_DECL` should be `END_ELEMENT`, etc.

**Comment by asterite** [comment]
Hi @Blacksmoke16 ! Could you include the source code? Play seems to be down so I can't reproduce and fix this.

**Comment by Blacksmoke16** [comment]
Oh sure sorry,

```cr
require "xml"

X = <<-XML
<person id="1">
  <firstname>Jane</firstname>
  <lastname>Doe</lastname>
</person>
XML

xml = XML::Reader.new(X)

xml.read

until xml.node_type.none?
  puts "Type: #{xml.node_type} - Value: #{xml.node_type.value}"
  xml.read
end
```

**Comment by asterite** [comment]
Hm, apparently libxml2 has two enums: one for node types, the other for reader node type. So I guess we should move `XML::Type` to `XML::Node::Type` and introduce `XML::Reader::Type`. This is the same in Nokogiri (except they don't have enums, the constants are inlined inside the respective types).
