### ISSUE TITLE
.to_yaml cannot handle special characters (utf-8 unicode related?)

### ISSUE THREAD

**Issue by mipmip** [crystal-lang/crystal#8131]
When using Object.to_yaml of YAML.dump() special characters like éü are converted to unicode strings.

Code to reproduce:

```crystal
require "yaml"
require "json"

puts "ümlaubt"            #CORRECT "ümlaubt"
puts "ümlaubt".to_json    #CORRECT ""ümlaubt"

puts "ümlaubt".to_yaml    #PROBLEM "--- \"\\xFCmlaubt\"\n"
puts YAML.dump("ümlaubt") #PROBLEM "--- \"\\xFCmlaubt\"\n"
```

Testen on:

Crystal 0.30.1 (2019-08-13)
LLVM: 8.0.1
Default target: x86_64-apple-macosx

Crystal 0.30.1 [5e6a1b672] (2019-08-12)
LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu

**Comment by asterite** [comment]
Good catch, thanks!
