### ISSUE TITLE
Calling Range(_, Nil)#size hangs in runtime

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#8151]
Code below is enough to kill the compiler:

```cr
(0..).size
```

Infinite `Iterator`s are having the same issue btw:

```cr
[1, 2, 3].cycle.size
```

**Comment by asterite** [comment]
It looks like it hangs at runtime, which I guess is expected, though we could try to detect it somehow... it's really hard, though.

**Comment by asterite** [comment]
Advice: always do `crystal build foo.cr` and then `./foo` to see whether it's a compiler bug or just hangs at runtime.

**Comment by Sija** [comment]
I guess we could overload `#size` in these 2 cases.

**Comment by asterite** [comment]
We could. It would also hang when doing map, or select or any of the other enumerable methods.

**Comment by wontruefree** [comment]
could we have another class called `InfiniteIterator` subclassed from `Iterator` for cases like this?

**Comment by RX14** [comment]
This is expected behaviour. Every language will hang if you try and perform an infinite amount of work. What would `#size` return? `Infinity` isn't an integer.

**Comment by wontruefree** [comment]
It would be nice to have an `Infinity` to return.  I think `Float` is the object that has an infinity but maybe the `Int` classes should have one for cases like this.

**Comment by Sija** [comment]
@wontruefree IMO if anything `Infinity` should be moved into the `Number` struct instead.

**Comment by straight-shoota** [comment]
@wontruefree `Int` has no concept of infinity, so it can't be a valid return value. And it's not really useful here either.
