### ISSUE TITLE
I am not getting overflow errors

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#8153]
I am not getting overflow errors where I am expecting an error.  The crystal compiler I am using is being compiled with the preview on.

```bash
CRYSTAL_CONFIG_PATH="/Users/jack/src/crystal/src" CRYSTAL_CONFIG_LIBRARY_PATH="/Users/jack/.anyenv/envs/crenv/versions/0.30.0/embedded/lib" CRYSTAL_CONFIG_BUILD_COMMIT="b6169b5af" ./bin/crystal build -D preview_overflow -D compiler_rt --link-flags="-L/usr/local/opt/llvm/lib"  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
```

I would expect this to throw and error and it does not.
```crystal
puts "#{Int64::MAX} + #{1_u64} = #{Int64::MAX + 1_u64}"
puts "#{Int64::MAX} &+ #{1_u64} = #{Int64::MAX &+ 1_u64}"
```

```bash
9223372036854775807 + 1 = -9223372036854775808
9223372036854775807 &+ 1 = -9223372036854775808
```

[here](https://github.com/crystal-lang/crystal/blob/master/spec/compiler/codegen/arithmetics_spec.cr#L87) is a test that I think should be checking this.

Also [here](https://play.crystal-lang.org/#/r/7i50) is a playground that should throw and error.

**Comment by asterite** [comment]
> The crystal compiler I am using is being compiled with the preview on.

If you do that, if an overflow happens during compilation you'll get an error.

You need to compile your program with `-D preview_overflow`.

Just run `crystal foo.cr -Dpreview_overflow` assuming `foo.cr` has the code you put above and you'll see the error.

**Comment by bcardiff** [comment]
You need to pass `-D preview_overflow` when compiling the program you want to test. The flag in the compiler itself does not affect the program you want to test.

**Comment by wontruefree** [comment]
Thanks that works for everything now.
