### ISSUE TITLE
StaticArray for Pointer

### ISSUE THREAD

**Issue by PierrePharel** [crystal-lang/crystal#8167]
I tried to initilize a StaticArray of UInt8 pointer and the compiler send me this message : 

Nil assertion failed (NilAssertionError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
**Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues**
And source code is simple : 
```crystal
static_parsed = uninitialized Pointer(UInt8)[3]
```

**Comment by asterite** [comment]
Hi! I can't reproduce it. It also compiles fine in play: https://play.crystal-lang.org/#/r/7j6u

Crystal version? OS?

**Comment by PierrePharel** [comment]
Crystal 0.30.1 for Linux Mint

**Comment by asterite** [comment]
That line is the entire program that's crashing for you?

**Comment by PierrePharel** [comment]
Yes but if I call it in no lib func it's fine

**Comment by jhass** [comment]
Can you give a minimal example that reproduces? Note since it's a compiler error the binding can be made up since it doesn't even get to the linker stage.

**Comment by PierrePharel** [comment]
```crystal
fun expr_parser = cr_expr_parser(str : UInt8*) : UInt8
	expr = String.new(str)
	parsed_array = [] of String

	if valid_expr(expr) != Expr_error::Good 
		return 1_u8
	end
	parsed_array = cutout_expr(expr)
	static_parsed = uninitialized Pointer(UInt8)[3]
	return 0_u8
end
```
the principal function of my binding C

**Comment by PierrePharel** [comment]
```crystal
static_parsed = uninitialized Pointer(UInt8)[3]
```
This line raise a very very strange Nil Unknown error...I gess

**Comment by bew** [comment]
This was not a reproducible example though, there were still lines you didn't gave (I commented out the function calls you didn't define)

_No error here_ https://carc.in/#/r/7j9p
With the following code:
```cr
fun expr_parser = cr_expr_parser(str : UInt8*) : UInt8
  expr = String.new(str)
  parsed_array = [] of String

  # if valid_expr(expr) != Expr_error::Good
  #   return 1_u8
  # end
  # parsed_array = cutout_expr(expr)
  static_parsed = uninitialized Pointer(UInt8)[3]
  p! static_parsed
  return 0_u8
end

expr_parser("hh".to_unsafe)
```
_sidenote for @asterite: would be nice to avoid having to call `String#to_unsafe` manually here_

**Comment by PierrePharel** [comment]
Thank it's fine now but I have a other probleme with StaticArray return...so can I open an other issue ?
