### ISSUE TITLE
feature request: #update on Hash (and possibly other containers)

### ISSUE THREAD

**Issue by stronny** [crystal-lang/crystal#8176]
Array#update is a very useful method to also include in other containers, notably Hash.

**Comment by asterite** [comment]
They idea would be to have:

```crystal
def update(key : K, &block : K -> V)
```

if fetches the key and updates it with the value of the block.

If no key is present but there's a default value or default block, that value is used to insert a new key.

Otherwise it raises.

The idea is that this can prevent a double hash lookup. Instead of this:

```crystal
hash = Hash(String, Int32).new(0)
hash["foo"] += 1
hash["foo"] += 2
```

we can do:

```crystal
hash = Hash(String, Int32).new(0)
hash.update("foo") { |v| v + 1 }
hash.update("foo") { |v| v + 2 }
```

just that a couple of hash lookups would be avoided.

Super low priority, though.

**Comment by stronny** [comment]
wouldn't &block be `V -> V` though?

pushing it a bit further, is it possible to allow blocks be passed to `[]=` method? To reduce the boilerplate it would be nice to type smth like `hash["foo"] = { |v| v + 1 }` imo.

**Comment by asterite** [comment]
Ah, yes, `V -> V` it is.

No blocks for `[]=`, syntax conflict.

**Comment by satyanash** [comment]
In Ruby, `Hash#update` is an alias for `Hash#merge!`. We ought to maintain that consistency?
We already have `Hash#merge!(other : Hash)` and `Hash#merge!(other: Hash, &)` in Crystal.

**Comment by glhrmv** [comment]
What's the status om this? New implementation or call to `Hash#merge!`?

**Comment by straight-shoota** [comment]
Refering to `#merge!` doesn't make much sense. It's more costly to construct a new `Hash` instance just to merge it with the existing one. Performance-wise, a double lookup would be better.
For even more performance, I think the original proposal for `#update` sounds good. Just need someone to pick it up.

**Comment by glhrmv** [comment]
I would like to try my hand at this, basing myself on the given requirements and the current implementation of [Mutable#update](https://github.com/crystal-lang/crystal/blob/6529d725a/src/indexable/mutable.cr#L54) as reference.
