### ISSUE TITLE
Hash with initial_capacity calls `resize`

### ISSUE THREAD

**Issue by jgaskins** [crystal-lang/crystal#8181]
I noticed while running the profiling for [this post](https://forum.crystal-lang.org/t/multithreaded-crystal-initial-thoughts/1089/21?u=jgaskins) that `GC#realloc` was getting invoked during calls to `Hash#resize`, made while [populating hashes that were created with an `initial_capacity`](https://github.com/jgaskins/neo4j.cr/blob/f910ec6d91865361e40999c2813989160c503d18/src/neo4j/pack_stream/unpacker.cr#L90-L93).

Here is a minimized repro:

```crystal
class MyHash < Hash(Int32, Int32)
  def resize : Nil
    puts "Resizing, current_size: #{size}"
    super
  end
end

size = 1000
hash = MyHash.new(initial_capacity: size)
size.times { |i| hash[i] = i }
# => Resizing, current_size: 512
pp hash.size
# => 1000
```

Every hash size I've tested this against on current `master` calls `resize`, but it doesn't happen in 0.30.1 so it appears to be new behavior.

**Comment by asterite** [comment]
Good catch, thanks!

**Comment by oprypin** [comment]
Perhaps there should also be a spec that resize is not immediately called like shown in this example
