### ISSUE TITLE
Allow operators/syntax literals to be used in macros

### ISSUE THREAD

**Issue by girng** [crystal-lang/crystal#8202]
For example, you can pass in an **integer** to a macro:
```
macro test(v)
    pp {{v}} + 5
end

test 1
```

However, when passing a `operator`, like `+` or `-`:
```
macro adjust_nodes(option)
  pp 10 {{option}} 5 
end

adjust_nodes(+)
```

There is an error:
> syntax error in eval:5
Error: unterminated call

Reason: Instead of having **two methods** for `+` and `-`, a developer can have one macro method, which can execute the dynamic operators.

**Comment by girng** [comment]
```
class Player
  property health = 10
end

p = Player.new


macro adjust_nodes(option, client)
  #client.health {{option}} 10
  client.health += 10
end

adjust_nodes("+=", p)


pp p
```
> Error: undefined local variable or method 'client' for top-level

I don't think this will work, as the class is not passed by referenced anymore when it's passed to a macro.

**Comment by Blacksmoke16** [comment]
This would work if you passed the `+` or `-` sign as a symbol/string.

https://play.crystal-lang.org/#/r/7lrk

If you don't then the compiler thinks you're actually trying to add two things that don't exist.

https://play.crystal-lang.org/#/r/7lrm

2nd example would work fine as well, if you use the right macro syntax.

However, I'm not sure what the benefit of using a macro for this brings vs just doing like `client.health += 10`.  It kinda just adding unneeded complexity to save like a few chars.

**Comment by girng** [comment]
@Blacksmoke16 Oh, it's already possible. Using {{client}} and  [MacroID](https://crystal-lang.org/api/0.30.1/Crystal/Macros/ASTNode.html#id:MacroId-instance-method). Thanks for the examples!



> However, I'm not sure what the benefit of using a macro for this brings vs just doing like `client.health += 10`. It kinda just adds unneeded complexity to save like a few chars.

My use case is instead of having
```
def allocate_skill_nodes(nodes, client)
  nodes.each do |sid|
    if (skill_node = TreeData[sid]?) && (main_node_type = NodeTypes[skill_node["type"]]?)
      main_node_type.modifications.each do |mod, value|
        case mod
        when "strength"
          client.strength += value
        when "increased_attack_speed"
          client.increased_attack_speed += (value / 100.00)
        when "health"
          client.health += value
        when "health_regen"
          client.health_regen += (value / 100.00)
        end
      end

      pp client.increased_attack_speed
    else
      raise "Skill tree error.. this is bad. skill id: #{sid} does not exist on the server!"
    end
  end
end
```

and a second method `allocate_skill_nodes`   (using -=). I can just have  **one macro method** instead of having to maintain two methods.

There are hundreds of mods.

**Comment by Blacksmoke16** [comment]
Np.

I suppose?  I feel like a lot of this could be avoided by a diff design, but too far into things now for that.

I guess in this case using a macro that would allow you to define the same set of code twice, just with a diff name/operator makes sense?

**Comment by girng** [comment]
Yep, IMHO this is the power of macros. I now only need to maintain one method!

**Comment by girng** [comment]
This is doesn't feel right. I'm just going to have two methods for `-=` and `+=`.
