### ISSUE TITLE
[Feature proposition] setlocale for internationalisation of crystal (like setlocale of C lang)

### ISSUE THREAD

**Issue by PierrePharel** [crystal-lang/crystal#8206]
I don't known if this follow the crystal lang logic but actually i have a project, and i'm using crystal with C code but internationalisation of some methods or function i required but i don't find it.
So it's only a proposition and i'm waiting for your opinion.
Sincerely Pierrep

**Comment by straight-shoota** [comment]
I think internationalization should not be provided by the stdlib. There are already shared available for this.

**Comment by RX14** [comment]
I agree, close?
