### ISSUE TITLE
spec assertion failures blot out stdout, such as `p`

### ISSUE THREAD

**Issue by Phlip** [crystal-lang/crystal#8212]
(I was hoping Crystal wouldn't learn automated testing tips from Python, but...)

When I put a `p variable` in a spec and run it, the output appears amid the dots .

But when the spec fails an assertion, it eats all the stdout, then displays the assertion's diagnostic. This problem does not help me diagnose why the assertion is failing!

$ crystal -v
Crystal 0.30.1 [5e6a1b672] (2019-08-12)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu

**Comment by asterite** [comment]
Hi! Could you provide some code that reproduces the issue?

**Comment by Phlip** [comment]
Nope; the problem went away. The `p` is spewing correctly.

I guess I was passive-aggressively wishing I could report this bug to Python-land, where it's really annoying.
