### ISSUE TITLE
Port MT support to upstream bdw-gc getstackbottom patch

### ISSUE THREAD

**Issue by zhangkaizhao** [crystal-lang/crystal#8213]
Hello. It is very exciting to hear that 0.31.0 was released with multi-threading preview support.
But I failed to build with preview_mt flag on Arch Linux.

file: main.cr
```crystal
def main
  channel = Channel(Int32).new(9)

  (1..10).each do |i|
    spawn do
      channel.send(i)
    end
  end

  result = [] of Int32
  9.times do
    result << channel.receive
  end

  puts result
end

main
```

It is OK to build without the `preview_mt` flag:
```shell
$ crystal build -o main main.cr
$ ./main
[1, 2, 3, 4, 5, 6, 7, 8, 9]
```
But failed to build with the `preview_mt` flag:
```shell
$ crystal build -Dpreview_mt -o main main.cr
/usr/bin/ld: G-C-.o: in function `set_stackbottom':
/usr/lib/crystal/gc/boehm.cr:202: undefined reference to `GC_set_stackbottom'
/usr/bin/ld: G-C-.o: in function `current_thread_stack_bottom':
/usr/lib/crystal/gc/boehm.cr:194: undefined reference to `GC_get_stackbottom'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/kaizhao/lab/crystal/mt/main'  -rdynamic  -lpcre -lm -lgc -lpthread /usr/lib/crystal/ext/libcrystal.a -levent_pthreads -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
```

I have read the great article [Parallelism in Crystal](https://crystal-lang.org/2019/09/06/parallelism-in-crystal.html) and I think the code should be valid. Please correct me if I made mistakes.
Just don't know or this is an issue caused by packaging in Arch Linux or crystal itself. So I create this issue.
The version of crystal which is installed via Arch Linux `pacman` package management tool:
```shell
$ crystal -v
Crystal 0.31.0 (2019-09-23)

LLVM: 8.0.1
Default target: x86_64-pc-linux-gnu
```

**Comment by yxhuvud** [comment]
As this is the GC that is failing, it would have made sense to also include the version that is used there. In particular, the missing functions you are seeing comes from very recent versions of the boehm GC (that I think @bcardiff was part of developing, for this purpose).

**Comment by oprypin** [comment]
Maybe the feature hasn't been in a release of libgc yet

https://forum.crystal-lang.org/t/bdwgc-upstream-support-for-green-threads-fibers/733
https://github.com/ivmai/bdwgc/releases

And maybe Crystal's official binaries are bundled with new libgc but Arch doesn't do that

**Comment by jhass** [comment]
This is likely a won't fix, but calling @anatol here as the package maintainer.

**Comment by asterite** [comment]
I think what @oprypin says is correct: we used a patched GC that hasn't been released. It's at least like that in the gc we use for homebrew, and I remember @bcardiff saying that for our supported linux distributions.

**Comment by bcardiff** [comment]
We use patch that is slightly different from the one merged upstream. We are expected to update it before the next bdw-gc release. 

More info at: https://forum.crystal-lang.org/t/bdwgc-upstream-support-for-green-threads-fibers/733

The patch is also used in homebrew since we ended up maintaining that aswell.

Closing, there is no actionable on our side. But we can talk regarding what is the final decision regarding Arch support of preview_mt.

**Comment by anatol** [comment]
Thank you for the information folks. I am checking what need to be done at Arch side to fix the issue.

I applied https://github.com/ivmai/bdwgc/commit/5668de71107022a316ee967162bc16c10754b9ce mentioned above and some of the crystal compilation issues fixed. Now I see following linking problem:

```
$ crystal build -Dpreview_mt -o main main.cr
/usr/bin/ld: G-C-.o: in function `current_thread_stack_bottom':
/usr/lib/crystal/gc/boehm.cr:194: undefined reference to `GC_get_stackbottom'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/anatol/tmp/crystal/main'  -rdynamic  -lpcre -lm -lgc -lpthread /usr/lib/crystal/ext/libcrystal.a -levent_pthreads -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
```

Is there a separate patch for `GC_get_stackbottom` function as well?

**Comment by jhass** [comment]
The patch you applied is what we will target latest after the next bdw-gc release, probably already with Crystal 0.32.

But it's a quite modified version of what we developed initially and target currently. Our original patch and what Crystal 0.31 targets is at https://github.com/crystal-lang/bdwgc/commit/4f0de8a45802a2ba18f664b385e82d1802cf423c

**Comment by bararchy** [comment]
@jhass only if 0.32.0 is soon, otherwise there is a broken crystal package in arch main repo, preview_mt is a very substantial part of this release and people will 100% want to experiment

**Comment by jhass** [comment]
I really don't think pointing them to the AUR package is too much to ask. We could even patch Crystal to do a quick `pacman -Qs` on `-Dpreview_mt` and point people towards it if not installed.

**Comment by anatol** [comment]
@jhass I agree it would be really great to have `-Dpreview_mt` working out of the box at Arch Linux.

We can try to bring `gc` package updates to Arch with the upstream patch https://github.com/ivmai/bdwgc/commit/5668de71107022a316ee967162bc16c10754b9ce  but it is a big no in Arch to patch with non-upstream changes like https://github.com/crystal-lang/bdwgc/commit/4f0de8a45802a2ba18f664b385e82d1802cf423c

Is there any chance you can look at upstreaming https://github.com/crystal-lang/bdwgc/commit/4f0de8a45802a2ba18f664b385e82d1802cf423c? It would make pulling the required change to the official Arch package much more likely.

**Comment by anatol** [comment]
My vote goes towards 1) or 2). `crystal` should work with upstream-blessed `gc` tree.

At the end of the day this issue is not about Arch and we want to see a solution that works for all distros. It will help to avoid using custom patches everywhere. Instead we should use the upstream version of the packages.

Is there a chance you can provide a `crystal` patch to use https://github.com/ivmai/bdwgc/commit/5668de71107022a316ee967162bc16c10754b9ce that I test locally?

**Comment by bcardiff** [comment]
Updating to the upstream patch was expected to happen in the near future. I will let you know how it goes.

**Comment by RX14** [comment]
This issue needs to be open to track using the correct API.

**Comment by RX14** [comment]
Actually, my bad, the PR for crystal's support was merged before upstream merged the different API. You can probably ignore the rest of my rant :)

**Comment by anatol** [comment]
Thank you @RX14. Once you have a crystal patch ready I'll integrate it into the Arch package.

**Comment by bararchy** [comment]
@anatol -> #8225

**Comment by zhangkaizhao** [comment]
I have just checked the crystal package in both FreeBSD ports and MacPorts. They have the same issue though they have earlier versions of crystal packages e.g. 0.28.0 in FreeBSD ports, 0.30.1 in MacPorts now. Hope all these and others with the same issue but not mentioned can be fixed soon. Thank you very much! ❤️

**Comment by anatol** [comment]
Arch binary package `crystal-0.31.0-2` with the fixes from above just been pushed to [testing] repository. Please check the package and let me know if you see any issues.

**Comment by bararchy** [comment]
@anatol , it builds and link, I don't see any issues while testing it locally.

**Comment by oprypin** [comment]
<pre>sudo pacman -U <a href="https://www.archlinux.org/packages/testing/x86_64/gc/download/">gc-8.0.4-2-x86_64.pkg.tar.xz</a> 
sudo pacman -U <a href="https://www.archlinux.org/packages/community-testing/x86_64/crystal/download/">crystal-0.31.0-2-x86_64.pkg.tar.xz</a> 
crystal eval -Dpreview_mt 'p 5'</pre>

Tried on a few programs too, seems to work.

For reference, how @anatol applied those patches in [**gc**](https://git.archlinux.org/svntogit/packages.git/commit/trunk/PKGBUILD?h=packages/gc&id=30f59b7e8773bb7c713c8c80d6179a5ba1d18fb2) and [**crystal**](
https://git.archlinux.org/svntogit/community.git/commit/trunk/PKGBUILD?h=packages/crystal&id=3354aceae25c5b81f53cf6362ce463ef3890f398).

**Comment by zhangkaizhao** [comment]
@anatol Thank you! After synchronizing and upgrading to the latest packages it works on Arch Linux now.

file: main.cr
```crystal
def main
  channel = Channel(Int32).new(9)

  (1..10).each do |i|
    spawn do
      sleep 1
      channel.send(i)
    end
  end

  result = [] of Int32
  9.times do
    result << channel.receive
  end

  puts result
end

main
```

```shell
$ crystal build -D preview_mt -o main main.cr
$ ./main
[2, 10, 6, 1, 4, 9, 8, 5, 3]
```

Nice job! :rocket: :100:
