### ISSUE TITLE
Bug dispatching enum shorthand to splat and non-splat overloads

### ISSUE THREAD

**Issue by RX14** [crystal-lang/crystal#8217]
```cr
@[Flags]
enum Mode
  A
  B
  C
end

def foo(mode : Mode)
  puts "a"
end

def foo(*modes : Mode)
  puts "b"
end

foo(Mode::A)
```

correctly prints "a", but replacing the end with

```cr
foo(:a)
```

causes the program to segfault at runtime.

The codegen is invalid:
```llvm
  br i1 false, label %current_def, label %next_def, !dbg !79

current_def:                                      ; preds = %entry
  call void @"*foo<Mode>:Nil"(i32 1), !dbg !82
  br label %exit, !dbg !82

next_def:                                         ; preds = %entry
  br i1 false, label %current_def1, label %next_def2, !dbg !82

exit:                                             ; preds = %current_def1, %current_def
  ret void, !dbg !82

current_def1:                                     ; preds = %next_def
  call void @"*foo<Mode>:Nil"(i32 1), !dbg !82
  br label %exit, !dbg !82

next_def2:                                        ; preds = %next_def
  unreachable, !dbg !82
```

Crystal 0.31.0 and 0.30.1 tested.

Discovered in #8011.

**Comment by RX14** [comment]
I've been working on this. There are two seperate issues.

One semantic:

```cr
  it "matches splat for enum (#8217)" do
    assert_type(%(
      enum Foo
        One
        Two
      end

      def foo(x : Foo)
        'a'
      end

      def foo(*x : Foo)
        1
      end

      foo(:one)
      )) { char }
  end
```

and one codegen:
```cr
  it "codegens dispatch with int autocast (#8217)" do
    run(%(
      def foo(foo : Int32, x : Int8)
        x
      end

      def foo(foo : Char, x : Int8)
        1
      end

      foo(1.as(Int32 | Char), 32)
      )).to_i.should eq(32)
  end
```

I've had a look at one method for solving the semantic issue, before discovering the codegen issue.

The codegen issue seems to be fixed just adding 

```cr

  private def match_type_id_impl(type : SymbolType, restriction : EnumType, type_id)
    llvm_true
  end

  private def match_type_id_impl(type : IntegerType, restriction : IntegerType, type_id)
    llvm_true
  end

  private def match_type_id_impl(type : IntegerType, restriction : FloatType, type_id)
    llvm_true
  end

  private def match_type_id_impl(type : FloatType, restriction : FloatType, type_id)
    llvm_true
  end
```

but I am rather unconvinced that it's not possible to construct a non-autocasting call which is broken by this change.

Wiring knowledge of whether a specific argument is an autocast through to codegen seems impractical. Ideally, autocast would replace call args with the correctly typed concrete literal (symbol -> enum etc) in the cleanup transformer. However, I'm stuck on how to even route through which arguments are autocasts and their concrete types from the `LiteralType` instances to literal AST nodes to make that easy for the cleanup transformer.

@asterite, any thoughts?

**Comment by asterite** [comment]
@RX14 Hi! I don't have much time these days. I think you are right, the autocasting should happen at the semantic phase and there should be no remainings in the codegen, but I think that's not the case right now. I was thinking that since a value can be passed to possibly multiple overloads, some overloads might need autocast and some not, and this would be needed to do in the codegen. However, I just remembered that we don't allow autocasted values to match more than one target type.

I think first I'll fix that (or if you want to do that until I can get my hands on that, please go ahead), then try to fix this issue.

**Comment by RX14** [comment]
> I think first I'll fix that (or if you want to do that until I can get my hands on that, please go ahead), then try to fix this issue.

I have a workaround in my version of #8011, so fixing this isn't super urgent to me any more. Feel free to work on this or not.



> I was thinking that since a value can be passed to possibly multiple overloads, some overloads might need autocast and some not, and this would be needed to do in the codegen.

Unfortunately though, *all* dispatches to more than one target def are broken when autocasting is involved since the type IDs don't match :(

**Comment by asterite** [comment]
Also happens in this case:

```crystal
def foo(mode : Int64, x : String)
  10
end

def foo(modes : Int64, x : Int32)
  20
end

foo(1, "x" || 1)
```

In general it happens when there's a multidispatch. It's tricky because now `1` can match both `Int32` and `Int64`, if autocasted, but it shouldn't always match `Int64` when in a multidispatch...

**Comment by RX14** [comment]
I just hit this again with

```
a = Array(UInt32).new
a.push(1)
```

this is really a terrible bug :(

**Comment by asterite** [comment]
We could at least remove the `push(*tuple)` overload... I never used that.

**Comment by asterite** [comment]
Another alternative: don't give "ambiguous match" anymore. If an autocast matches the first overload, that overload wins. That will make the logic work like everywhere else. It's probably not too bad.

Thoughts?
