### ISSUE TITLE
once.cr return sigsegv after update to 0.31

### ISSUE THREAD

**Issue by PierrePharel** [crystal-lang/crystal#8223]
```
Thread 1 "lcalculator" received signal SIGSEGV, Segmentation fault.
once () at /usr/share/crystal/src/crystal/once.cr:20
20	      if @rec.includes?(flag)
```
It's result obtained by gdb 
before update all work fine...

**Comment by asterite** [comment]
Hi! Please provide some code that reproduces this error, otherwise there's not much we can do.

**Comment by PierrePharel** [comment]
It's not easy because i'm using crystal for library for use in C code and with crystal compiler no problem  but if i try to use on function of library sigsegv

**Comment by asterite** [comment]
So, you are calling Crystal code from C code?

**Comment by PierrePharel** [comment]
Yes

**Comment by asterite** [comment]
Ah... Crystal doesn't support that use case so at least I won't try to fix this, sorry.

**Comment by asterite** [comment]
Maybe you can try using the functions in `once.cr`, but there's no guarantee that will stay like that.

**Comment by PierrePharel** [comment]
Ok no problem i wil try to fix problem myself thank you too much

**Comment by asterite** [comment]
I'm actually surprised it was working for you so far! I thought this wasn't possible, mainly because of Crystal's GC.

**Comment by PierrePharel** [comment]
It's possible siply because it's a simple library write in crystal and use in C code...I gess
