### ISSUE TITLE
warning when using getter to fulfill abstract method

### ISSUE THREAD

**Issue by carlhoerberg** [crystal-lang/crystal#8229]
The`getter` macro doesn't add the return type, so if a it's an abstract method that the getter fulfills crystal will complain since 0.31

```
abstract class A
  abstract def str : String?
end

class C < A
  @str = "s"
  getter str
end

puts C.new.str
```

output: 
```
 7 | getter str
     ^
Warning: expanding macro


There was a problem expanding macro 'getter'

Called macro defined in macro 'macro_4596379136'

 117 | macro getter(*names, &block)

Which expanded to:

    1 |
    2 |
    3 |
 >  4 |             def str
    5 |               @str
    6 |             end
    7 |
    8 |
    9 |
   10 |
Warning: this method overrides A#str() which has an explicit return type of (String | Nil).

Please add an explicit return type ((String | Nil) or a subtype of it) to this method as well.

The above warning will become an error in a future Crystal version.

A total of 1 warnings were found.
s
```

**Comment by carlhoerberg** [comment]
i haven't looked into if it's possible for the macro to know the return type, or if it's just bad coding to fulfill an abstract method with a getter... found it when compiling an existing large code base with 0.31.0

**Comment by ysbaddaden** [comment]
Isn't the following working?

```crystal
getter str : String?
```

**Comment by asterite** [comment]
When overriding abstract methods with an explicit return type you must also provide an explicit return type. The answer by @ysbaddaden fixes your code. This is a change that was introduced in 0.30.1, but in 0.31.0 warnings are now on by default.

**Comment by carlhoerberg** [comment]
thanks @ysbaddaden, you're absolutely right, forget about the explicit version of `getter`
