### ISSUE TITLE
can't infer Type of Regex

### ISSUE THREAD

**Issue by orangeSi** [crystal-lang/crystal#8241]
# Submitting questions
when use Regex in Union Type as arguements of Method, the compiler cann't infer the type of Union Type. Sorry for poor english words, see detail in code below please~

# Submitting bugs
my ```tmp.cr``` is like this
```
def test(name : String|Regex = "myth", word : String|Float32 = "hello")
	if typeof(name) == String
		puts "name is string #{name}"
	else
		puts "name is int #{name.source}" # source is a method of Regex
	end
end

test(name: "myth", word: "hello")
```
then run ``` crystal build tmp.cr``` will get this error:
```
Showing last frame. Use --error-trace for full trace.

In tmp.cr:5:28

 5 | puts "name is int #{name.source}" # source is a method of Regex
                              ^-----
Error: undefined method 'source' for String
```

```
$crystal --version
Crystal 0.30.1 [5e6a1b672] (2019-08-12)
$cat /etc/centos-release 
CentOS release 6.9 (Final)
```

**Comment by asterite** [comment]
`typeof(...)` doesn't restrict the type of the variable.

If you do:

```crystal
if name.is_a?(String)
```

it works.

https://crystal-lang.org/reference/syntax_and_semantics/if_varis_a.html

**Comment by asterite** [comment]
I also recommend asking this kind of questions in the forums: https://forum.crystal-lang.org/

**Comment by orangeSi** [comment]
> I also recommend asking this kind of questions in the forums: https://forum.crystal-lang.org/

Sorry, I thought it's a bug, so come here. Beacause when I use ```String|Int32``` with ```typeof```, the compiler can infer the Type correctly, but ```String|Regex``` not. 
I will ask my quesiton in the forums later, thanks a lot~
