### ISSUE TITLE
Add short-hand notation for Enum values that are capitalized

### ISSUE THREAD

**Issue by girng** [crystal-lang/crystal#8244]
This issue came to fruition from [this forum post](https://forum.crystal-lang.org/t/am-i-using-enums-correctly-if-so-is-there-a-performance-difference-compared-to-strings/1167)

Reduced code:
```
enum CMD
  XFER
end

case CMD.from_value(0)
when .xfer?
  pp "hi 1"
end
```

There are several issues with this code:

 - `xfer?` has to be lowercase, which is the the total opposite of `XFER`'s casing. IMO, this seems confusing, non-consistent with `Enums`'s  structure, and the opposite of brevity.
- `.xfer?` is **also not a value** of an Enum (inside the Enum it's an internal method, but the casing of it does not match the Enum's value).  
- `Enum` values _must start with a capital letter_, but when checking the value of them in a case statement using `.xfer?`, the developer is now using all lowercase letters. 

My idea:
-  The developer should be able to use a short-hand notation that matches the **Enum's actual value**.  This increases brevity and stays consistent with how Enums function. For example `.XFER?` (however, this will not work, as method names must be lowercase). I suggest and hope another alternate solution can be crafted by the lead developers.  

Thanks for reading!

**Comment by Blacksmoke16** [comment]
I vote to close.  This isn't really a problem here that needs to be solved.

**Comment by girng** [comment]
Okay, closed
