### ISSUE TITLE
Can't sort generic_types

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#8246]
https://play.crystal-lang.org/#/r/7nlu

```cr
struct Union
  def self.create
    pp {{T.sort_by { |t| t != Nil } }}
  end
end

class Klass
end

Union(Klass?).create
```
```
Showing last frame. Use --error-trace for full trace.

error in line 3
Error: can't compare true to false
```

Use case is for this my deserialization lib.  I want to include an optimization that will try cast the given value as the non `Nil` type first in order to prevent raising a `TypeCastError`.

**Comment by oprypin** [comment]
It's just that bools are not orderable, works otherwise

https://play.crystal-lang.org/#/r/7nm4
```
struct Union
  def self.create
    pp {{T.sort_by { |t| t ? 1 : 0 } }}
  end
end

class Klass
end

Union(Klass?).create
```

**Comment by Blacksmoke16** [comment]
Ahhh right.  Good call :)
