### ISSUE TITLE
BUG: trying to assign Struct <- Abstract Struct (Exception)

### ISSUE THREAD

**Issue by rebuilding-patrick** [crystal-lang/crystal#8252]
Reproducible code

```
abstract struct Parent
end

struct Child < Parent
    def initialize(@b : Bool)
    end
end

items = Hash(Int32, Parent).new
items[0] = Child.new(true)
items.delete(0)
```

Compiler fails when a child struct of an abstract parent is deleted from a hash meant for its parents. Storage and retrial works fine. The bug also occurs with other types for the child's property and the hash's key.  

uname -a
`
Linux **** 4.19.0-5-amd64 #1 SMP Debian 4.19.37-2~mx17+1 (2019-05-15) x86_64 GNU/Linux
`

crystal -v
```
Crystal 0.31.0 [8d4715a59] (2019-09-23)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by Blacksmoke16** [comment]
@rebuilding-patrick This doesn't seem to be an issue anymore in `0.31.1`.

**Comment by straight-shoota** [comment]
This has probably been fixed by #8221

**Comment by asterite** [comment]
I don't think so, there's no uninitialized in this issue. Did anyone check this really fails with a previous crystal version?

**Comment by Blacksmoke16** [comment]
@asterite Yes, https://play.crystal-lang.org/#/r/7ot5
