### ISSUE TITLE
Complicated macros are becoming a mess.

### ISSUE THREAD

**Issue by elliotize** [crystal-lang/crystal#8267]
I am working on https://github.com/Bonemind/syringe/pull/3 and want to write cleaner code for crystal macros. As features to this library are added the more complicated a single macro will get. What are your suggestions to organize the macros better. Is there any way to separate the code into methods and or classes that are accessible?

**Comment by jwoertink** [comment]
@elliotize this might be a good post for the forum https://forum.crystal-lang.org/
