### ISSUE TITLE
Homebrew version still installing old shards?

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/crystal#8274]
I completed uninstalled my crystal and shards, and just did a fresh install from homebrew, but it seems it still installed shards 0.8.1 instead of 0.9.0.

```
[19:47PM] ~$ shards --version
Shards 0.8.1 (2019-10-02)
[19:47PM] ~$ crystal -v
Crystal 0.31.1 (2019-10-02)

LLVM: 8.0.1
Default target: x86_64-apple-macosx
```

There was an issue back when 0.30.0 was released that I thought fixed that, but maybe it was reverted?

**Comment by jhass** [comment]
Homebrew has shards 0.10 now, and 0.11 soon I'm sure.
