### ISSUE TITLE
Generic type inaccessible in string interpolation in module member

### ISSUE THREAD

**Issue by obskyr** [crystal-lang/crystal#8275]
In Crystal 0.31.1, this works without problem:

```crystal
module HexadecimalFormat
  @@format = "0x%0#{UInt16::MAX.to_s.size}X"
  def text
    @@format % @value
  end
end

class X
  include HexadecimalFormat
  @value : UInt16
  def initialize(n : UInt16)
    @value = n
  end
end

puts X.new(10_u16).text
```

```
0x000A
```

But this doesn't:

```crystal
module HexadecimalFormat(T)
  @@format = "0x%0#{T::MAX.to_s.size}X"
  def text
    @@format % @value
  end
end

class X(T)
  include HexadecimalFormat(T)
  @value : T
  def initialize(n : T)
    @value = n
  end
end

puts X(UInt16).new(10_u16).text
```

```
Error: undefined constant T::MAX
```

Doing things like `@value = [] of T` or `@value = T.new` in a module works without a hitch, however. In addition, the generic type is accessible in string interpolation in class members. It seems that the generic type is inaccessible solely in string interpolation in module members.

**Comment by HertzDevil** [comment]
`@@format` is a class variable of the uninstatiated `HexadecimalFormat`, so it cannot refer to `T` in its initializer.

Related: #8861
