### ISSUE TITLE
Arithmetic overflow if dividend is higher or equal to 64 

### ISSUE THREAD

**Issue by girng** [crystal-lang/crystal#8278]
This took way too long to find and reduce, however, I'm happy I found it

```
test = 3
test += (5_i8 // 2) * 64//100

pp test
```

This cannot be reproduced on **0.30.1** and below.

**Comment by oprypin** [comment]
No, it's not a dividend, it's a multiplicand.

`(5_i8 // 2) * 64` overflows as it should. Your spacing has no effect.

So I think the issue is invalid.

I commend the effort, it just needed one extra step :s

**Comment by girng** [comment]
Doesn't happen if 64/100 though. `63` is the dividend?

**Comment by oprypin** [comment]
Why do you write "/100" there if it's irrelevant?
You can remove it from the original example as I showed and nothing will change

**Comment by oprypin** [comment]
What I should say is,
your example never actually contains "64/100".
It's `((5_i8 // 2) * 64) // 100)`
and the overflow happens without involving the 100

**Comment by girng** [comment]
I  see. Yeah, when I was tracking the error I   I was doing trial and error with the dividend, just to see when the error will NOT happen.  You are correct I should have reduced it more

**Comment by oprypin** [comment]
And this ends up being `128_i8 // 100` and 128 just doesn't fit in an int8

**Comment by girng** [comment]
Hmm, but that value is being assigned to an Int32. It should work like it did before?

**Comment by oprypin** [comment]
It's not adding anything, that operation is never reached.

The minimal failing example is literally just
```
(5_i8 // 2) * 64
```
- that's the entire program.

**Comment by girng** [comment]
Makes sense. So this is not a bug, but this error is actually protecting the developer from future possible arithmetic overflows.

**Comment by girng** [comment]
Thanks @oprypin ;)

**Comment by oprypin** [comment]
No it's an actual overflow. 2i8 * 64 == 128i8

but 128 doesn't fit in int8 (its maximal value being 2**7-1 == 127)

**Comment by girng** [comment]
How was it an 'actual overflow" when this worked just fine before?
