### ISSUE TITLE
Scheduler tries to resume dead fibers

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#8285]
Getting the following error while playing with MT
```crystal
FATAL: tried to resume a dead fiber: #<Fiber:0x7fab1fe38000>

  from /usr/share/crystal/src/thread.cr:119:5 in 'resume'

  from /usr/share/crystal/src/crystal/scheduler.cr:95:9 in 'run_loop'

  from /usr/share/crystal/src/crystal/scheduler.cr:169:3 in '->'

  from /usr/share/crystal/src/thread.cr:255:3 in '->'

  from GC_inner_start_routine

  from GC_call_with_stack_base

  from ???

  from /usr/share/crystal/src/io.cr:184:5 in 'initialize:__pull_for_json_serializable'

  from ???
```

**Comment by asterite** [comment]
Any code to reproduce this? Otherwise it will be really hard to figure out why it happens.

**Comment by bararchy** [comment]
well....here is the thing, it's from our whole solution log, as it doesn't indicate a line of code or any kind of placement I have no clue which part of our code make it happen, we have over 60k lines of crystal code, so :man_shrugging:

**Comment by bcardiff** [comment]
Maybe `IO#<<(obj) : self` can be monkey patched with some `LibC.dprintf("IO#<<(%s)\n from: \n%s\n", obj.class.name, caller.join('\n'))` to extract some context and dig a bit

```cr
class IO
  def <<(obj) : self
    LibC.dprintf("IO#<<(%s)\n from: \n%s\n", obj.class.name, caller.join('\n'))
    obj.to_s self
    self
  end
end
```

(disclaimer: not tested)

**Comment by bararchy** [comment]
This is a subset of #8375 closing
