### ISSUE TITLE
Overflow on Int#abs

### ISSUE THREAD

**Issue by Exilor** [crystal-lang/crystal#8309]
```crystal
Int8::MIN.abs
Int16::MIN.abs
Int32::MIN.abs
Int64::MIN.abs
Int128::MIN.abs
```
All of the above raise OverflowError. Maybe we need an `#abs!` method, but what would it return?

**Comment by bcardiff** [comment]
I don't think there is a need for `abs!`. If you don't need overflow check is because you trust the numbers input or you are dealing with binary data. The former will be safe safe to use `abs` with overflow and the later is unlikely to need `abs`.

**Comment by Exilor** [comment]
Okay.

**Comment by asterite** [comment]
Also worth noting that in `C` calling `abs` on a min value returns itself. So similar to overflow. But I'm not sure we need it.
