### ISSUE TITLE
Remove String#chars and friends

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#8325]
I propose removing `String#chars` and friends that just wrap little code with an array allocation. These kind of methods make it very easy to write bad, inefficient code. There is pretty much *always* a way around the `.chars` array allocation.
Just look at this:
https://github.com/crystal-lang/crystal/blob/491f26b10cf67c1131aa035c4d720b53f30eab72/src/compiler/crystal/tools/doc/markdown/doc_renderer.cr#L185
https://github.com/crystal-lang/crystal/blob/4a0ca220e8ea60c7a085fbc98815220b65a05eb9/src/compiler/crystal/exception.cr#L162
https://github.com/crystal-lang/crystal/blob/4a0ca220e8ea60c7a085fbc98815220b65a05eb9/src/compiler/crystal/exception.cr#L166
An array is allocated just to read its size and then discard it right after and do nothing else with it.
In all of these cases you can simply omit `.chars` and your code will be cleaner, run faster, allocate less memory, put less pressure on the garbage collector and do the exact same thing. There are many more examples of this.

The problem is just that `.chars` makes it so easy to write this kind of code.
You can pretty much always avoid it. If `.chars` would not be there you would have to explicitly create an array yourself (which is very little code anyway) and then nobody would do:
```cr
chars = [] of Char # Or Array(Char).new(string.size)
string.each_char { |char| chars << char }
chars.size
```
when you can just do `string.size`.
And if you *really* need the characters to be in an array you can still do that. It's only two or four lines of code. But I think making it harder for the developer to write bad code outweights that.

I think we should be more explicit about expensive allocations and potential performance bottlenecks and not hide all this stuff so much behind easy-to-use methods.

**Comment by asterite** [comment]
No.

The idea of Crystal is the other way around: have user friendly APIs that try to be as efficient as possible, but this is not always possible (like in chars). But it should be possible to. optimize things.

The cases you mention are because of inexperienced users that don't know that size already returns that value. The solution is to fix those calls, not change the language.

Plus, those calls don't happen in hot paths so it doesn't matter that they are a little expensive.

**Comment by straight-shoota** [comment]
> These kind of methods make it very easy to write bad, inefficient code.

You're talking about code efficiency. But that's not everything. Coding efficiency is also a thing, and more often than you might think, it doesn't really matter that mach if the code is as performant as it could be. For example when doing some quick prototyping, the focus is on writing the desired functionality, not execution speed.

**Comment by r00ster91** [comment]
Okay prototyping is a good point, yeah.

**Comment by jhass** [comment]
This is a good usecase for a linter, basically grep for `.chars.size` and print a warning for each match

**Comment by Blacksmoke16** [comment]
Prob a good candidate for https://github.com/crystal-ameba/ameba/tree/master/src/ameba/rule/performance

**Comment by j8r** [comment]
There was an indea in the past to have `String#chars` returning a `CharView`, that will have `#each`, `#size` and so on, because it will be an `Indexable` like `Array`.
