### ISSUE TITLE
JSON mapping with union types of same parent class

### ISSUE THREAD

**Issue by mang** [crystal-lang/crystal#8335]
The following:
```
require "json"

class A
end

class B < A
  JSON.mapping({id: Int32})
end

class C < A
  JSON.mapping({name: String})
end

class X
  JSON.mapping({b_or_c: B|C})
end

x = X.from_json(%<{"b_or_c": {"id": 1}}>)
```
throws:
```
Error: wrong number of arguments for 'A.new' (given 1, expected 0)
```
Also, the following throws the same error:
```
require "json"

class A
end

class B < A
  include JSON::Serializable
  property id : Int32
end

class C < A
  include JSON::Serializable
  property name : String
end


class X
  include JSON::Serializable
  property b_or_c : B|C
end


x = X.from_json(%<{"b_or_c": {"id": 1}}>)
```
If we instead define `A` as:
```
class A
  include JSON::Serializable
end
```
the code compiles, however, it will set `b_or_c` of `x` to an instance of `A` (where it should in this case be an instance of `B`:
```
#<X:0x5592da5dde60 @b_or_c=#<A:0x5592da5dee90>>
```
So, instead of mapping to `B` or  `C`, it maps everything to `A` when `B` and `C` are used in union and both are a child of `A`.
Seems somewhat related to #7814.

on:
```
Linux
Crystal 0.31.1 (2019-10-10)
LLVM: 7.1.0
```

**Comment by asterite** [comment]
Unfortunately this is expected behavior. The union `B | C` resolves to `A`, as explained [here](https://crystal-lang.org/reference/syntax_and_semantics/virtual_and_abstract_types.html). And there's no way to have a union of `X | Y` with both `X` and `Y` inheriting from a same type.

If `A` is abstract then #8185 might be helpful.

**Comment by mang** [comment]
Oh, yeah that makes sense. Thanks for the clarification!
