### ISSUE TITLE
Syntax error with fresh variables inside heredoc string

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#8365]
```cr
macro foo
  %foo = :foo
  pp <<-EOF
    #{%foo}
  EOF
end

foo
```

fails with error:

```
syntax error in eval:4
Error: expecting token '%}', not '}'
```

See https://carc.in/#/r/7uue

**Comment by ysbaddaden** [comment]
`{%` denotes a macro, and a macros are always processed first (before strings and interpolations). You must disamiguate with a space, for example `#{ %foo }`.

**Comment by Sija** [comment]
Shiit, sometimes the right answers are the simplest ones :P thanks and sorry for the noise!

**Comment by Sija** [comment]
actually, it doesn't work either way, this time:

```cr
macro foo
  %foo = :foo
  pp <<-EOF
    #{ %foo }
  EOF
end
 
foo
```

results in:

```
There was a problem expanding macro 'foo'

Called macro defined in eval:1:1

Which expanded to:

 > 1 | __temp_24 = :foo
 > 2 | pp <<-EOF
 > 3 |   #{ %foo }
            ^
Error: unexpected token: %
```

See https://carc.in/#/r/7uut

**Comment by ysbaddaden** [comment]
Ok, that's unexpected this time :)
