### ISSUE TITLE
Tcpsocket Timeout 

### ISSUE THREAD

**Issue by whidbey** [crystal-lang/crystal#8382]
# Submitting bugs
simple a socket client create and connect to 8888 which is not exist port,and timeout event never
happens. nor raise error and block the code forever;

client =TCPSocket.new("localhost",8888,3,3);

**Comment by whidbey** [comment]
Now I am using this to fixit

        client = Socket.tcp(Socket::Family::INET,true)   //blocking =true
        begin 
            client.connect host, port,timeout  
        rescue exception
            ...
        ensure
             client.blocking =false  

it's used for an application that served self as TCPServer service and sometimes act as client.

**Comment by rdp** [comment]
On my OS I get this:
```
$ crystal bad.cr 
Unhandled exception: Error connecting to 'localhost:8888': Connection refused (Errno)
```
Or if the server's backlog is full (does take several seconds, whatever that means):
```
crystal bad.cr 
Unhandled exception: connect timed out (IO::Timeout)
```
Do you have an example of crystal code to create a server that causes clients to block like this? What OS/crystal version?

**Comment by RX14** [comment]
Unfortunately, I cannot reproduce, same as @rdp. If you can provide extra details on how to reproduce this issue, I'll reopen.
