### ISSUE TITLE
Can add `not` instance method to `Bool` class in std library, and `all_index` to Enumerable?

### ISSUE THREAD

**Issue by excosy** [crystal-lang/crystal#8383]
1. Bool instance's`itself` method inheriting from Object, allow we select true value conveniently, with `&.itself`, but it is invalid for false value. So why don't add `not` method to Bool in std library, use ```&.not``` to select false value?

2. Since we have `select` to do `a.map.with_index{|x, i| x if x.meet_some_conditions}.compact!`, Is it need `all_index` method to do `a.map.with_index{|x, i| i if x.meet_some_conditions}.compact!`?

**Comment by straight-shoota** [comment]
1. It already exists as `Object#!`.
2. What's the usecase for this?

**Comment by yxhuvud** [comment]
1: Also there is `reject` to select false values.

**Comment by excosy** [comment]
> 1: Also there is `reject` to select false values.

Yes, it is. I mean, this opposite belongs to Bool itself, not Enumerator's method. This means, we must define opposite method with each Enumerator's method, such as {select: reject, take_while: skip_while, ...}. Is it necessary? And, There is no opposite method of `find` and `index`, even unnecessary .

**Comment by excosy** [comment]
> 1. It already exists as `Object#!`.
> 2. What's the usecase for this?

1. Object#! can't write as `count(&.!)`, with ```Error: expecting any of these tokens```. We need a word rather than a symbol method. And it is same to `~`. Furthermore, is there method defined with word of Bool or class derived from Bool, to override——we can't write `define !`, such as `and`, `xor`, `nand` etc. ?

2. There are some cases that index is significative variable——such as used to calcalute offset of another array——and value is only used by `meet_some_conditions` filter. Using array rather than hash to store it is in view of performance, since the index is finite numeric.

**Comment by straight-shoota** [comment]
1. I think that's actually just a bug. `&.!` should work. But yes, you can't reimplemt that method because its a pseudo method provided by the compiler. If you need different (overridable) behaviour, you need to define a custom method for this. But that doesn't require that method being in the stdlib.
2. So this would essentially be an extension to `Enumerable#index` which returns the index of the *first* matching element to return the indices of *all* matching elements. Sounds reasonable.

**Comment by wontruefree** [comment]
can this be closed since https://github.com/crystal-lang/crystal/pull/8445#issuecomment-554316878 is merged?

**Comment by asterite** [comment]
Closed by #8445
