### ISSUE TITLE
Use the developer's type aliases in the error messages

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#8384]
```cr
alias Type = Int32 | Bool | String

array = [] of Type

array << nil
```
```
Showing last frame. Use --error-trace for full trace.

error in line 5
Error: no overload matches 'Array(Bool | Int32 | String)#<<' with type Nil

Overloads are:
 - Array(T)#<<(value : T)
```
I think instead of `'Array(Bool | Int32 | String)#<<'` it should in this case use the type that I defined: `'Array(Type)#<<'`.
That would make the error much better easier to read, especially for longer errors with a lot of unions it helps to abstract some of the unions behind the developer's aliases.

The error for
```cr
alias Type = Int32 | Bool | String

array = [] of Int32 | Bool | String

array << nil
```
however should stay the way it is, I think. Otherwise that can get confusing.

**Comment by asterite** [comment]
It's a good idea but I'm not sure. With just showing Type you have no idea why it failed. Elm does this in some cases and if I'm not familiar with the code I have to go and find the definition of the alias type to understand what went wrong. A second reason not to do this is it's a bit hard.

**Comment by r00ster91** [comment]
> With just showing Type you have no idea why it failed. Elm does this in some cases and if I'm not familiar with the code I have to go and find the definition of the alias type to understand what went wrong. 

That's true. Maybe when a type alias is used in the error message, the definition of that alias could be displayed as well:

```
Showing last frame. Use --error-trace for full trace.

error in line 5
Error: no overload matches 'Array(Type)#<<' with type Nil

Type is defined as Int32 | Bool | String

Overloads are:
 - Array(T)#<<(value : T)
```

And for multiple aliases a dash list could be used:

```
Showing last frame. Use --error-trace for full trace.

error in line 5
Error: no overload matches 'Array(Type | AnotherType)#<<' with type Nil

 - Type is defined as Int32 | Bool | String
 - AnotherType is defined as UnixServer | Deque

Overloads are:
 - Array(T)#<<(value : T)
```

**Comment by straight-shoota** [comment]
But what happens in this case:
```cr
alias Type = Int32 | Bool | String

array = rand > 0.5 ? [] of Type : [] of Int32 | Bool | String

array << nil
```

**Comment by asterite** [comment]
Yes, this is practically impossible to. implement. An alias might resolve to a variety of types, and the alias might itself. be nested inside other types (for example Array(Alias)), and carrying that information around is very difficult.

Instead of improving alias error messages, I'd rather remove aliases. I'm not sure why we added them in the first place. We try to avoid multiple names for a same method, yet we allow multiple names for the same type.

**Comment by asterite** [comment]
Actually, aliases are useful.

Another note: Haskell has aliases but you never see them in error messages. Haskell is ancient and very sophisticated. If they didn't do it, it must mean it's very hard or it might not be that useful (I can imagine the reason being not knowing what's behind an alias... which could be solved by also expanding the alias, but it gets pretty complex with nested types).

**Comment by straight-shoota** [comment]
Closing. There is no apparent path to solving this problem. Aliases are merged with the type they alias.
