### ISSUE TITLE
Nested JSON does not parse

### ISSUE THREAD

**Issue by Daniel-Worrall** [crystal-lang/crystal#8385]
Nested JSON objects fail to parse.

Reproducible Code

```cr
require "json"

valid_json = %({"foo": "{\"bar\":\"baz\"}"})

JSON.parse(valid_json) # => Unexpected char 'b' at 1:12 (JSON::ParseException)
```
Crystal 0.31.1

This also applies for mapping and serialisable.
https://carc.in/#/r/7wen
https://carc.in/#/r/7weq
https://carc.in/#/r/7weo

**Comment by vlazar** [comment]
Not a bug.

Your example is not a nested JSON. The nested JSON is this:

```crystal
valid_json = {foo: {bar: "baz" } }.to_json
p! valid_json # => "{\"foo\":{\"bar\":\"baz\"}}"
p! JSON.parse(valid_json) # => {"foo" => {"bar" => "baz"}}
```
If you want a string instead inside a `foo` key you are missing some quotes.

**Comment by jhass** [comment]
For a literal `\` you need to write `\\`, even inside `%()`

https://carc.in/#/r/7wfv
