### ISSUE TITLE
Ditto doesn't work for constants

### ISSUE THREAD

**Issue by docelic** [crystal-lang/crystal#8388]
When documenting code, "# ditto" appears to work for methods, but not constants.

Reproducible case:

```
module Xyz

  # Description of method X
  def x; end

  # ditto
  def xdittoed; end

  # Description of constant Cons
  Cons = 1

  # ditto
  ConsDittoed = 1
end
```

After running `crystal docs` and opening `docs/index.html` in the browser, both methods and the first constant will be documented, while the second constant will just say "ditto".

**Comment by straight-shoota** [comment]
What's the use case? I can't see much sense in using an identical description for two constants.
It might still be worth changing it for consistency, though.

**Comment by docelic** [comment]
Right, but I just had a case where it felt very natural to describe two closely related constants with the same description, since the description included an explanation of what they are for and mentioned both.
