### ISSUE TITLE
nil assertion: yield in ecr template embedded in def macro

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/crystal#839]
Crystal fails to compile the following example with a `Nil assertion failed` exception. It compiles if `render` is a def, but fails once it's a def macro:

```crystal
# render.cr
require "ecr/macros"

macro def render(&block) : String
  String.build { |%str| embed_ecr "template.ecr", "%str" }
end

render { "contents" }

# template.ecr
<%= yield %>
```

```
Nil assertion failed
*raise<String>:NoReturn +70 [0]
*Nil#not_nil!<Nil>:NoReturn +13 [0]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +115108 [0]
```

**Comment by asterite** [comment]
Reduced:

```crystal
macro def foo : String
  yield
end

foo do
end
```

It seems `macro def` doesn't work with blocks.

Does it work if you make it a regular method? Blocks are always inlined so each call to a method with a block results in a new instantiation. That should work for now unless you need to defer the block's contents until the semantic phase is finished.

**Comment by ysbaddaden** [comment]
Yes it works, but I would like to generate a `render_layout` method per class, so children of Artanis::Application can each have their own layout, just like they have their own `call` method. 

I'm troubled with your "each call to a method with a block results in a new instantiation". What do you mean? That each call from different places will generate a new method? I guess that would be pretty bad, yes. All I need the block for it to be able to `yield` in the layout template.

I realize that Ruby spoiled me a lot with ERB templates (load/parse/cache/render at runtime), and I think the design translates poorly for Crystal/ECR templates (at compile time) — thought that design would work for mustache/liquid templates. I may just stick to list the ECR templates and generate a method for each. Maybe it would fit better with Crystal.

**Comment by asterite** [comment]
This is now fixed in master, though you'll have to define `render` like this:

```crystal
macro def render(&block) : String
  {% begin %}
    String.build { |%str| embed_ecr "template.ecr", "%str" }
  {% end %}
end
```

(and the `String` return type there is not needed, but can be left)
