### ISSUE TITLE
Bug in Mutex?

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#8396]
My SafeHash class: 
```crystal
class SafeHash(T)
    getter :hash

    @hash : Hash(String, T)

    def initialize
      @hash = Hash(String, T).new
      @lock = Mutex.new
    end

    def set(name : String, num : T = 0)
      @lock.synchronize do
        @hash[name] = num
      end
    end

    def add(name : String, num : T)
      @lock.synchronize do
        @hash[name] += num
      end
    end

    def get(name : String) : T
      @lock.synchronize do
        next @hash[name]
      end
    end
  end
```

I got the error: 
```crystal
Attempt to unlock a mutex which is not locked  Attempt to unlock a mutex which is not locked (Exception)
```

Is this a bug, or if one thread `synchronize` and another `synchronize` on another method it might interject?

**Comment by asterite** [comment]
@bararchy It might be a bug, but could you provide code to reproduce the issue? I wanted to reproduce it, I did some `spawn` and use that type concurrently and couldn't reproduce it.

**Comment by ysbaddaden** [comment]
The `next` inside `get` is ticking me.

Note that `synchronize` returns whatever its block returns.

**Comment by bararchy** [comment]
@ysbaddaden hm... I'll change to just the `@hash[name`, but do you think it might be the issue? or just annoying syntax ? ;)

**Comment by ysbaddaden** [comment]
Please try and let's see :)

**Comment by bararchy** [comment]
@ysbaddaden would this be safer: 
```crystal
class SafeHash(T)
    getter :hash

    @hash : Hash(String, T)

    def initialize
      @hash = Hash(String, T).new
    end

    def set(name : String, num : T = 0)
      lock = Mutex.new
      lock.synchronize do
        @hash[name] = num
      end
    end

    def add(name : String, num : T)
      lock = Mutex.new
      lock.synchronize do
        @hash[name] += num
      end
    end

    def get(name : String) : T
      lock = Mutex.new
      lock.synchronize do
        @hash[name]
      end
    end
  end
```

**Comment by lribeiro** [comment]
That's not safe at all, each thread would create it's own mutex, the mutex itself needs to be shared by all threads, since they need a common object to synchronize on.

**Comment by bararchy** [comment]
Sadly I too can't seem to reproduce it like that, I can only add that the original code ran in Docker on `ubuntu:latest`, I don't know if it matters.

**Comment by rdp** [comment]
seems to work OK here.  Though I'm a bit concerned with how much RAM fibers take I can only run 50_000 and it blows up my box with 2GB RAM free LOL.

**Comment by bararchy** [comment]
I think this was a subset of #8375 , closing.
