### ISSUE TITLE
Add tier 1 support for arm64

### ISSUE THREAD

**Issue by JunfengJia** [crystal-lang/crystal#8401]
It's tier 2 support but arm64 devices have huge numbers today.

Target | Compiler | Std | Description
-- | -- | -- | --
aarch64-linux-gnu | ✓ | ✓ | ARM 64-bit Linux (GNU, hardfloat)
aarch64-linux-musl | ✓ | ✓ | ARM 64-bit Linux (MUSL, hardfloat)

**Comment by wontruefree** [comment]
I have becoming more and more interested in arm64 support.  Would this cover the new a1 instances from AWS? It seems like it would.

https://aws.amazon.com/ec2/instance-types/a1/

**Comment by jhass** [comment]
I'm not sure we need a such general issue for this. Let's be honest, all this does is expressing a wish. 

The support tiers, as far as I understood them, don't describe intended effort by any party but rather status quo of the implementation. If you want to push this forward, look for things that are missing to get them to full support. Bugs only happening there, missing features. Then open issues for those that don't have issues yet, provide fixes for them if you're able to and help with testing if you have access to the hardware :)

**Comment by ysbaddaden** [comment]
Closing. Nothing actionable here. We don't build or distribute an AArch64 release of Crystal, that would be used by a CI to at least run std specs. Those would be the bare minimum before even thinking to move to tier 1 support.
