### ISSUE TITLE
BUG: __crystal_raise_overflow is not defined (Exception)

### ISSUE THREAD

**Issue by shdown** [crystal-lang/crystal#8437]
```
$ echo '2 + 2' > file.cr
$ crystal build --prelude=empty --emit=llvm-bc file.cr
BUG: __crystal_raise_overflow is not defined (Exception)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
$ crystal v
Crystal 0.31.1 [0e2e1d067] (2019-09-30)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by bcardiff** [comment]
It's not a bug. The only actionable is to separate the core parts from the std-lib. Ref: https://github.com/crystal-lang/crystal/issues/5215#issuecomment-506499572

With prelude empty you won't even functions related to raise exceptions.

If you only care about overflow you can use `-Ddisable_overflow` or use `&+`.

**Comment by straight-shoota** [comment]
Technically it's a bug because the compiler says it is one. This should show a more appropriate error message. It's not actually a compiler bug.

**Comment by 3n-k1** [comment]
sorry for the necro, but is there any interest in changing this error message? changing [this string](https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/codegen/codegen.cr#L2039) to something along the lines of "LLVM function __crystal_raise_overflow is not defined (are you using a prelude?)" i think would be a much more informative error
