### ISSUE TITLE
Request: Creating folders for a file if they don't exist convenience method

### ISSUE THREAD

**Issue by Daniel-Worrall** [crystal-lang/crystal#8444]
Quite a number of times it has come up where I need to write files but cannot be certain that the folder has been created, and this is usually for writing a large number of files.

This is currently solved prefacing any File write calls with `Dir.mkdir_p(path.parent.to_s)` where path is an instance of `Path` for the file. (There is also `FileUtils.mkdir_p`, but this is an alias to `Dir`)

I'd like to request a convenience method for this use-case. I'd imagine it to look something like `File.write(path, data, create_folders: true)`

**Comment by RX14** [comment]
I don't think this is common enough to have an argument to `touch` or `tee` for this behaviour. I'd say this is definitely not worth the effort.

**Comment by Daniel-Worrall** [comment]
Gotcha. It'd be a nice convenience for myself, but given the underlying lib calls, it seems I'll just have to do the checks myself.

**Comment by Daniel-Worrall** [comment]
Closing since there's been no interest in 10 days
