### ISSUE TITLE
XML xpath union operator broken

### ISSUE THREAD

**Issue by repomaa** [crystal-lang/crystal#8455]
Following xpath will fail with an `XML::Error` although it's valid xpath:

``` crystal
require "xml"
doc = XML.parse("<foobar><foo></foo><bar></bar><baz></baz></foobar>")
doc.xpath_nodes("//(foo|bar|baz)")
```

**Comment by asterite** [comment]
It doesn't work either in Ruby's Nokogiri, which uses libxml2 under the hood too. Maybe it's a bug or a limitation of libxml2.

**Comment by asterite** [comment]
Using "//foo|//bar|//baz" works, though.

**Comment by Fryguy** [comment]
The xpath pipe operator only combines full expressions, not partial expressions as in your example.  You can use `or` with other selectors inside of `[]` to achieve what you want though. See https://stackoverflow.com/questions/13013696/in-xpath-is-it-possible-to-use-the-or-operator-with-node-names for an example

**Comment by jhass** [comment]
See above, libxml2 only supports xpath 1.

**Comment by bew** [comment]
Maybe we could add a line in the doc saying that, as it's not something I'd think to look
