### ISSUE TITLE
Make each_char yield the index already

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#8457]
Why don't we change `each_char` to yield the index already, instead of having an extra method `each_char_with_index` for it? The thing is that either way, whether you use the index or not, the index **has** to be calculated. It has to keep track of what character it's at.
So we could yield the char and the index to `each_char` and then both of this will work:
```cr
"hello".each_char do |char|
  puts char
end
```
```cr
"hello".each_char do |char, index|
  puts char, index
end
```
It's so easy! We really don't need another method for it. `each_char_with_index` is so long to type as well.
I had this idea by the way while I noticed this:
```cr
require "benchmark"

io = IO::Memory.new

Benchmark.ips do |bm|
  bm.report "1" do
    "hello".each_char_with_index do |char, index|
      io << char << index
    end
    io.clear
  end

  bm.report "2" do
    index = 0
    while index < "hello".size
      char = "hello".to_unsafe[index].unsafe_chr
      io << char << index
      index += 1
    end
    io.clear
  end
end
```
```
1  11.03M ( 90.70ns) (± 8.44%)  0.0B/op   1.24× slower
2  13.63M ( 73.38ns) (±10.67%)  0.0B/op        fastest
```
`each_char_with_index` actually counts the index **twice**. That isn't efficient at all. They should have the same performance. So when we do this it should also be easy to fix this important performance regression.

We could also go even further and rename `each_char` to `each`. Like, when we do `"hello".each do` we obviously want to go through the chars, why do we have to explicitly mention that with the `_char` prefix? Similar to how you do `[1, 2, 3].each do` and not `[1, 2, 3].each_element do`.

I would be willing to implement this if any of this is accepted.

**Comment by straight-shoota** [comment]
Your benchmark is completely meaningless because it compares a generic implementation with a highly optimized special case.

> `each_char_with_index` actually counts the index **twice**.

Where is the second counter? I don't think `Char::Reader` keeps track of the char index. It only counts bytes. So apart from ASCII-only strings where both are identical, `#each_char_with_index` needs to count the characters explicitly.

However, it seems optimization removes the index counter entirely when its not used. Both `.each_char_with_index do |char|` and `.each_char do |char|` see to be equivalent.

```cr
require "benchmark"

FOO = "enemenemuhundrausbistdu!ß"

chars = 0
Benchmark.ips do |bm|
  bm.report "each_char_with_index" do
    FOO.each_char_with_index do |char|
      chars |= char.ord
    end
  end
  bm.report "each_char" do
    FOO.each_char do |char|
      chars |= char.ord
    end
  end
end
```
```
   5.21M (191.98ns) (±25.87%)  0.0B/op   1.01× slower
   5.28M (189.55ns) (±29.09%)  0.0B/op        fastest
```

So maybe we *could* actually consider merging both methods into a single one.

> why do we have to explicitly mention that with the `_char` prefix?

In contrast to an array or other enumerable, with a string you can iterate different things. Using `each_char` and `each_byte` avoids any ambiguity.

**Comment by r00ster91** [comment]
> Your benchmark is completely meaningless because it compares a generic implementation with a highly optimized special case.

Okay, I didn't handle the non-ASCII case there but now look when I make it a bit more sophisticated and handle all cases:
```cr
require "benchmark"

class String
  def new_each_char
    if ascii_only?
      index = 0
      while index < bytesize
        char = to_unsafe[index].unsafe_chr
        yield char, index
        index += 1
      end
    else
      reader = Char::Reader.new(self)
      reader.each do |char|
        yield char, reader.pos
      end
    end
  end
end

io = IO::Memory.new

Benchmark.ips do |bm|
  bm.report "Old" do
    "hello".each_char_with_index do |char, index|
      io << char << index
    end
    io.clear
  end

  bm.report "New" do
    "hello".new_each_char do |char, index|
      io << char << index
    end
    io.clear
  end
end
```
```
Old  11.88M ( 84.14ns) (± 1.40%)  0.0B/op   1.26× slower
New  15.01M ( 66.63ns) (± 2.09%)  0.0B/op        fastest
```
It isn't meaningless.

> Where is the second counter?

[`each_char`](https://github.com/crystal-lang/crystal/blob/0e2e1d067af09e7b1e4573a7258c433e3cf8fa17/src/string.cr#L3775) -> [`each_byte`](https://github.com/crystal-lang/crystal/blob/0e2e1d067af09e7b1e4573a7258c433e3cf8fa17/src/string.cr#L3884) -> [`each`](https://github.com/crystal-lang/crystal/blob/0e2e1d067af09e7b1e4573a7258c433e3cf8fa17/src/indexable.cr#L226) -> [`each_index`](https://github.com/crystal-lang/crystal/blob/0e2e1d067af09e7b1e4573a7258c433e3cf8fa17/src/indexable.cr#L265) and there you have the second counter. The other counter is in `each_char_with_index`. LLVM doesn't optimize this.

> I don't think `Char::Reader` keeps track of the char index. It only counts bytes.

It does, that's what `Char::Reader#pos` is for.

**Comment by r00ster91** [comment]
Well, it seems the benchmark results are just buggy again. Sometimes the new one is "slower".
But the main point of this issue is anyway to remove `each_char_with_index`. So let's focus on that.

> In contrast to an array or other enumerable, with a string you can iterate different things. Using `each_char` and `each_byte` avoids any ambiguity.

Hmm yeah, we should probably keep it `each_char`

**Comment by asterite** [comment]
`each_char_with_index` makes it clear that the second block argument is the index.

Is there anything we are trying to solve here? What's the problem with using `each_char` or `each_char_with_index`?

**Comment by straight-shoota** [comment]
@r00ster91 `Char::Reader#pos` is the *byte* index, not character count.

@asterite Assuming that `each_char_with_index` is equally performant as `each_char` when the index argument is not used, it would provide an option to simplify the API by using only `each_char` which yields both `char` and `index` (where the index is optional). But yeah, the expressiveness of `each_char_with_index` has its benefits as well.

**Comment by r00ster91** [comment]
@straight-shoota 
https://github.com/crystal-lang/crystal/blob/0e2e1d067af09e7b1e4573a7258c433e3cf8fa17/src/char/reader.cr#L182
https://github.com/crystal-lang/crystal/blob/0e2e1d067af09e7b1e4573a7258c433e3cf8fa17/src/char/reader.cr#L98
Whenever it's incremented, it's incremented by a specific char width, not 1, so I'm pretty sure that's the character index, not the byte index.

@asterite I think `each_char do |char, index|` is just as clear.

1. It's shorter.
2. It's simpler.
3. It's easier to add the index when you need it because you just need to add `, index|` and that's it. Currently you also have to add `_with_index`.
4. It's compatible with every index counter style. Some prefer to write it `i`, not `index`. `each_char_with_index do |char, index|` fits well. `each_char_with_index do |char, i|` doesn't fit so well. With `each_char` that problem doesn't exist.
5. One method less. I think that's always a good thing.

**Comment by straight-shoota** [comment]
No, that's exactly the byte index. It adds a number of n (`1 <= n <= 6`) per character. If it was a character index, it would add exactly 1 per character.  So, after consuming 3 unicode characters, `pos` could be anything between 3 and 18. There is no way to tell from that `pos` value how many characters have been read.

**Comment by RX14** [comment]
I've bought up that `*_with_index` is redundant before, but it seems everyone wants to keep the status quo.

**Comment by vlazar** [comment]
Instead of adding `*_with_index` counterparts for all methods method with optional second argument `index` sounds like a good idea to me.

For more than 2 arguments I would say it's not worth it, but when index is the second optional argument it's easy to remember.

**Comment by j8r** [comment]
There is also `Enumable#map_with_index`.
It can lead the way to have an optional index yielded for other existing enumerable methods, like `find`, `select`, `reject`, and so on, for free, and without changing the API.

**Comment by vlazar** [comment]
OTOH there are things like `each_with_index(offset) {|val, idx|}` with optional `offset` argument to start iteration from. It also yields 3 arguments to the block in case of named tuple `tuple.each_with_index do |key, value, index|`.

So to go "get rid of `_with_index` methods path I think all the methods with `_with_index` suffix must be reviewed and only then it'll be clear if dropping the suffix would be better.

**Comment by asterite** [comment]
So for example for Hash each would yield two objects: the key-value pair and the index. Then doing `each { |k, v|` doesn't work anymore.

**Comment by asterite** [comment]
Also the idea of each is to get each object, not necessarily with an index. Maybe an enumerator fetches data from a socket or a file, for each each_line just reads until eof, no need to count anything. So forcing the index on every method just complicates the implmentors.

**Comment by j8r** [comment]
@asterite why it won't work anymore for Hash? `Enumerable#each` isn't used, it's a custom implementation, which uses [Hash#each_entry_with_index](https://github.com/crystal-lang/crystal/blob/4559cd68e77c53a1c29bb770f9103cea7e230727/src/hash.cr#L1258).

I agree it can be cumbersome to put counters everywhere to yield an index, but at the same time having `with_index` methods are meh, too.
`_with_index` are arbitrarily only in few place because one guy needs it at some point, but we can need a counter on lots of other methods.

For what it worth, I have found a generic way by using a macro (didn't find another way):
```cr
macro with_index(call, &block)
  {{block.args[0]}} = 0
  {{call}} do |{{block.args[1]}}|
    {{block.body}}
    {{block.args[0]}} += 1
  end
end

with_index ['a', 'b', 'c'].each do |i, el| 
    puts "#{i}: #{el}"
end
```
Result:
```
0: a
1: b
2: c
```

**Comment by j8r** [comment]
@asterite why it won't work anymore for Hash? `Enumerable#each` isn't used, it's a custom implementation, which uses [Hash#each_entry_with_index](https://github.com/crystal-lang/crystal/blob/4559cd68e77c53a1c29bb770f9103cea7e230727/src/hash.cr#L1258).

I agree it can be cumbersome to put counters everywhere to yield an index, but at the same time having `with_index` methods are meh, too.
`_with_index` are arbitrarily only in few place because one guy needs it at some point, but we can need a counter on lots of other methods.

For what it worth, I have found a generic way by using a macro (didn't find another way):
```cr
macro with_index(call, &block)
  {{block.args[1]}} = 0
  {{call}} do |{{block.args[0]}}|
    {{block.body}}
    {{block.args[1]}} += 1
  end
end

with_index ['a', 'b', 'c'].each do |el, i| 
    puts "#{el}: #{i}"
end
```
Result:
```
a: 0
b: 1
c: 2
```

**Comment by j8r** [comment]
For what it worth, I have found a generic way by using a macro (didn't find another way):
```cr
macro with_index(call, &block)
  {{block.args[-1]}} = 0
  {{call}} do |{{block.args[0..-2].join(',').id}}|
    {{block.body}}
    {{block.args[-1]}} += 1
  end
end

with_index ['a', 'b', 'c'].each do |el, i| 
  puts "#{el}: #{i}"
end

with_index({"a" => 'A', "b" => 'B'}.each) do |k, v, i| 
  puts "#{k}, #{v}: #{i}"
end
```
Result:
```
a: 0
b: 1
c: 2
a, A: 0
b, B: 1
```

**Comment by straight-shoota** [comment]
Another problem for dropping `_with_index` is that omitting the index won't be free for iterator methods. It might not be a huge issue, because iterators are already quite costly in comparison, but still.
