### ISSUE TITLE
Install from scratch docs

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#8462]
I noticed readline is still in the docs to install from scratch. 
https://github.com/crystal-lang/crystal/wiki/All-required-libraries#ubuntu

Can this be removed since it was removed in this PR?
https://github.com/crystal-lang/crystal/pull/8364

also is there any cleanup that is needed in these install from scratch docs?

**Comment by wontruefree** [comment]
I think llvm can be bumped to at least version 8

**Comment by wontruefree** [comment]
Also looks like `libgc-dev` has the 7.6 patch

**Comment by straight-shoota** [comment]
Technically, readline will only be removed in 0.32.0, so the documentation is still accurate for 0.31.1. Of course compiler developers are likely working on master. But having a dependency listed that's not necessarily required is better than the other way around.

> Also looks like `libgc-dev` has the 7.6 patch

Yes, building it manually should not longer be necessary.
