### ISSUE TITLE
Class documentation not preserved over more than 1 macro

### ISSUE THREAD

**Issue by docelic** [crystal-lang/crystal#8463]
Usually, docs just above `class` get attached as documentation:

```
# Docs
class MyClass
end
```

This also works when class is defined via macro:

```
# Docs
some_macro()
```

But seems it doesn't work when macro calls another macro:

```
macro cls(nr)
  class MyClass{{nr}} end
end
 
# This is description; it gets attached to class properly.
cls(1)
 
macro cls2(nr)
  cls({{nr}})
end
 
# This is also a description; but due to double-macro it doesn't get attached to class.
cls2(2)
```

Code on play: https://play.crystal-lang.org/#/r/802x

**Comment by oprypin** [comment]
It would be interesting to see the result if one of the docs is removed.

```crystal
macro cls(nr)
  class MyClass{{nr}} end
end

cls(1)
 
macro cls2(nr)
  cls(nr)
end
 
# This a 2nd-degree description; does it get attached to class?
cls2(2)
```

If this works, then the problem likely isn't exactly with 2 macros, but with 2 comment nodes.

**Comment by docelic** [comment]
> It would be interesting to see the result if one of the docs is removed.
> If this works, then the problem likely isn't exactly with 2 macros, but with 2 comment nodes.

I just tried it and the behavior was the same, except for class 1 now not having comment of course.
