### ISSUE TITLE
Testing deprecated methods

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#8477]
Deprecated features still need to be tested to guarantee they keep working until they're finally removed.

They will trigger deprecation warnings on the spec suite. This adds unnecessary noise because when we explicitly test deprecated methods, it's obvious that they're deprecated. And it incentivizes submitting "fix warning" PRs such as #8454.

To circumvent this, we could add some kind of comment or another form of annotation for such specs that are explicitly meant to test deprecated behaviour.
This would at least prevent PRs for fixing the deprecation message.

One step further would be to automatically suppress deprecation warnings for the respective spec.

I think this could actually be very simple to implement. Because this really only affects specs and deprecated methods should only be called *directly* in the spec body, a naive static filter should be enough.

```cr
require "spec"

@[Deprecated]
def deprecated
end

it "test deprecated method" do
  deprecated
end
```
This is the warning:
```
In deprecation_spec.cr:8:3

 8 | deprecated
     ^---------
Warning: Deprecated top-level deprecated.
```

`crystal spec`, after compiling the program reports the warnings. These could simply be filtered based on file and line number. If it's in a spec file and maybe has some kind of annotation naming the deprecated method that should be suppressed.

Obviously this won't work if the deprecated method is called indirectly. But that should be avoided anyway because it would mean the deprecated method is used in some code other than specs.

This idea originally started in #8454

**Comment by RX14** [comment]
Has anyone tested just using `--exclude-warnings spec` when compiling the spec suite?

**Comment by straight-shoota** [comment]
Oh, nice. That could actually work 😃

That way there would be no comments attached to specs for deprecated features (or at least not required). But I suppose that's not really important as deprecation warnings are disabled anyway. And when the deprecated features are removed, the spec will fail and prompt to be removed.

So, yeah that sounds like a perfect solution.

I'd propose to make `--exclude-warnings spec` the default when running `crystal spec`.

**Comment by RX14** [comment]
@straight-shoota it's only really a safe default in the crystal repo itself, since crystal has no dependencies. Otherwise, spec code is just normal code and you don't want a warning for a spard's spec suite which uses a deprecated stdlib method to be supressed.

**Comment by asterite** [comment]
I think it's fine to have warnings in the compiler's test suite. After all they are just warnings and they remind us to eventually remove those methods.

**Comment by straight-shoota** [comment]
@RX14 Yeah, right. That's why I suggested to somehow annotate which deprecated methods a spec tests in order to exclude warnings for them.

@asterite Yes, it's not a big deal, but having a simple and efficient solution to this problem would be quite useful in the long run considering not only stdlib but the entire Crystal ecosystem.
