### ISSUE TITLE
HTTP::Client is missing write_timeout setting

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#8487]
It seems that HTTP::Client has all the timeouts other then write_timeout.
I'm in a situation where I need this to be configurable.

Is there a reason for this not being there or just an oversight\didn't get to it situation? 

* Note: https://docs.ruby-lang.org/en/2.6.0/Net/HTTP.html#attribute-i-write_timeout (ruby has it :) )

**Comment by asterite** [comment]
It's probably missing because we forgot to add it, or didn't think about it.
