### ISSUE TITLE
crystal "run (default)" can't take option

### ISSUE THREAD

**Issue by rdp** [crystal-lang/crystal#8492]
A bit nit picky, the help output says

`Usage: crystal [command] [switches] [program file] [--] [arguments]`

and the command is `run (default)            build and run program...`

So I thought to be able to have switches but no command:

```
$ crystal --release test.cr
Error: unknown command: --release
```

Either that or change the help to require a command for switches.  But preferably the former :) Cheers!

**Comment by rdp** [comment]
Another wishlist item:
If I get this:
```
$ crystal server
Error: file 'server' is not a valid Crystal source file: Unexpected byte 0xfa at position 1, malformed UTF-8
```
then retry with "server.cr" since that's what I meant... :) but I suppose that's a different subject altogether... :)

**Comment by asterite** [comment]
Maybe: if the first argument starts with `-` we assume it's `run` and then process the entire thing as arguments.

But I don't feel strongly about this change. I think the current state is fine.

**Comment by rdp** [comment]
Might be nice someday :)
