### ISSUE TITLE
Ensure block doesn't run on SIGING

### ISSUE THREAD

**Issue by sudo-nice** [crystal-lang/crystal#8493]
This code doesn't print "exiting" on Ctr-C, but Ruby does.

```crystal
def run
  sleep
ensure
  puts "exiting"
end

run
```

Crystal 0.31.1 [0e2e1d067] (2019-09-30)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu

**Comment by ysbaddaden** [comment]
Duplicate of other issues: `exit` doesnt throw an exception but terminates the program. If you need something to be run before exit, use `at_exit`.

**Comment by straight-shoota** [comment]
Alternatively, you can trap the signal and customize what happens when it is received.
