### ISSUE TITLE
String#delete_prefix

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#8514]
I dont like the name of the api but I like `delete_prefix` and `delete_suffix` on String.

I think we should add something like this to the api.  Maybe pass a keyword arg to delete?

**Comment by Blacksmoke16** [comment]
Thiss already exists as [lchop](https://crystal-lang.org/api/master/String.html#lchop(prefix:Char%7CString):String-instance-method) and [rchop](https://crystal-lang.org/api/master/String.html#rchop(suffix:Char%7CString):String-instance-method).
