### ISSUE TITLE
Optimize `Array#rotate!`

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#8515]
Extracted from https://forum.crystal-lang.org/t/array-rotate-can-be-faster/1404

Right now `Array#rotate!` will use a temporary array for the elements to rotate, followed by a couple of memcopies.

There are many ways we could optimize `Array#rotate!`:

- Special case for `n = 1` and `n = -1`: avoid allocating a tmp array and copy to a tmp var
- Special case for `n <= N`: we could allocate a static array with a few elements to avoid a temporary allocation on the heap
- We could use the reversal algorithm, like Ruby does: https://www.geeksforgeeks.org/program-for-array-rotation-continued-reversal-algorithm/ (though in practice it seems to be slower than allocating a temporary array, at least for big arrays)

Maybe we could start with special-casing for `n = 1` and `n = -1`, or for `n` less than a small N like 10 using a static array.

**Comment by straight-shoota** [comment]
I suppose most rotate use cases will apply a relatively small `n`, so the first two improvements would already be a good win.
