### ISSUE TITLE
Can't use an endless range to slice a string with String#[]?

### ISSUE THREAD

**Issue by sudo-nice** [crystal-lang/crystal#8539]
This will work:

```crystal
string = "foobar"
string[3..] #=> bar
```

But this won't:
```crystal
string = "foobar"
string[3..]? #=> Error: no overload matches 'String#[]?' with type Range(Int32, Nil)
```
---
Crystal 0.31.1 [0e2e1d067] (2019-09-30)
LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu

**Comment by KarthikMAM** [comment]
@straight-shoota Mind if I take a stab at this? Would love to start contributing to crystal.
