### ISSUE TITLE
Allow :ditto: along with more documentation?

### ISSUE THREAD

**Issue by docelic** [crystal-lang/crystal#8542]
Currently, due to code in `top_level_visitor.cr`:

```crystal
if stripped_doc == ":ditto:" || stripped_doc = "ditto"
  node.doc = @last_doc
end
```

It is not possible to use `:ditto:` with additional documentation.

I have a use case where it would be excellent if it was possible to use "ditto" along with more documentation. Such as:

```
# Alias for `#{{@type.methods.last.name}}`
#
# :ditto: 
```

In this particular case, this would allow the method to clearly state it was an alias, as well as include the original documentation in-place for maximum convenience.

**Comment by straight-shoota** [comment]
I don't think there is a reasonable use case for this. Documentation written for a specific method might work for another one, but only if its behaviour is exactly the same. If you need some kind of modification, it won't work and become a nuisance. I thinkyou're better off duplicating the method description to allow for modifications. In the described use case of an alias, it should simply reference the other method and don't duplicate the documentation.
