### ISSUE TITLE
BitArray#==(BitArray) is broken

### ISSUE THREAD

**Issue by felixbuenemann** [crystal-lang/crystal#8543]
The equality check in BitArray of Crystal 0.31.1 is broken.

The following code returns `true` when it should be `false`:

```crystal
require "bit_array"
a = BitArray.new(26, true)
b = BitArray.new(26, true)
b[23] = false
a == b
```

See: https://play.crystal-lang.org/#/r/84aq

This might be fixed by #8494, but I haven't tested it.

**Comment by felixbuenemann** [comment]
Yeah, looks like it is fixed by #8494, see: https://play.crystal-lang.org/#/r/84bh

**Comment by asterite** [comment]
#8494 is wrong, I'll send a different PR right now.

**Comment by asterite** [comment]
I won't, hehe, it's a bit more complex. What needs to be fixed is `==` and then `[]`. See this: https://github.com/crystal-lang/crystal/pull/8494#discussion_r352384303
