### ISSUE TITLE
Test failure: Error resolving real path of 'spec/std/data/test_file.txt'

### ISSUE THREAD

**Issue by ndbroadbent** [crystal-lang/crystal#8547]
Hello! I cloned the crystal repo (up to commit 54e68f0b3f5399c4574a673b55fd830850cf9193), and ran all of the tests with `make spec`. I got one test failure:

```
Using /usr/local/opt/llvm@8/bin/llvm-config [version=8.0.1]
.build/all_spec
...
Failures:

  1) File symlink creates a symbolic link

       Error resolving real path of 'spec/std/data/test_file.txt': No such file or directory (Errno)
         from src/crystal/system/unix/file.cr:92:5 in 'real_path'
         from src/file.cr:559:5 in 'real_path'
         from spec/std/file_spec.cr:247:22 in '->'
         from src/spec/example.cr:255:3 in 'internal_run'
         from src/spec/example.cr:35:16 in 'run'
         from src/spec/context.cr:296:23 in 'internal_run'
         from src/spec/context.cr:291:7 in 'run'
         from src/spec/context.cr:296:23 in 'internal_run'
         from src/spec/context.cr:291:7 in 'run'
         from src/spec/context.cr:48:23 in 'run'
         from src/spec/dsl.cr:270:7 in '->'
         from src/kernel.cr:255:3 in 'run'
         from src/crystal/main.cr:47:5 in 'main'
         from src/crystal/main.cr:106:3 in 'main'


Finished in 38:47 minutes
18312 examples, 0 failures, 1 errors, 17 pending

Failed examples:

crystal spec spec/std/file_spec.cr:244 # File symlink creates a symbolic link
make: *** [spec] Error 1
```

* macOS 10.15.1

```
$ .build/crystal --version
Crystal 0.32.0-dev [54e68f0b3] (2019-12-02)

LLVM: 8.0.1
Default target: x86_64-apple-macosx
```

**Comment by rdp** [comment]
related to #8431 ?  Sometimes I wonder if `crystal --version` could output more info like openssl version, OS version... :)

**Comment by ndbroadbent** [comment]
@rdp yes that looks like it!

I would like to [try this to see if it fixes the issue](https://github.com/JuliaLang/julia/issues/33545#issuecomment-541667259):

> I think this is caused by the new security features introduced in Catatonia. If you open System Preferences>Privacy>Full Disk Access, and add the Julia application to the list of ‘approved’ apps, these start to work again. Might be wrong... 😀

But I'm struggling to figure out how to run a single spec.

```
$ crystal spec spec/std/file_spec.cr:243
Showing last frame. Use --error-trace for full trace.

In spec/std/file_spec.cr:585:12

 585 | File.expand_path("~/", home: true).should eq(File.join(home, ""))
            ^----------
Error: no argument named 'home'

Matches are:
 - File.expand_path(path, dir = nil)
```

Do you know how I can just run that one spec in the Crystal test suite?

**Comment by asterite** [comment]
You need to use `bin/crystal` instead of `crystal`.

There's a bit more info here: https://github.com/crystal-lang/crystal/blob/master/CONTRIBUTING.md#the-standard-library (it might be outdated, I'm not sure)

**Comment by ndbroadbent** [comment]
Ah thanks, yes that was it! I was also able to get it running by commenting out all of the unrelated specs. I set up an alias so I don't forget that again:

```
~/code/crystal $ alias crystal="CRYSTAL_BIN=\$([ -f ./bin/crystal ] && echo ./bin/crystal || echo \$(which crystal)); \$CRYSTAL_BIN"
~/code/crystal $ crystal --version
Using compiled compiler at .build/crystal
Crystal 0.32.0-dev [54e68f0b3] (2019-12-02)

LLVM: 8.0.1
Default target: x86_64-apple-macosx
~/code/crystal $ cd ..
~/code/ $ crystal --version
Crystal 0.31.1 (2019-10-02)

LLVM: 8.0.1
Default target: x86_64-apple-macosx
```

**Comment by ndbroadbent** [comment]
I want to see if there might be an automated way to fix this, so I found out that these file permissions are managed in [/Library/Application Support/com.apple.TCC/TCC.db](https://apple.stackexchange.com/questions/362865/macos-list-apps-authorized-for-full-disk-access/372596#372596), but this file is [protected by SIP](https://hcsonline.com/images/PDFs/How_To_Edit_The_SIP_Protected_TCC.db_File_On_macOS_Sierra_10.12.2_And_Later.pdf), so it's read-only unless boot into recovery mode (even with sudo.) FWIW, I figured out the SQL query that would work if it was writable:

```
BIN_PATH="$HOME/code/crystal/.build/crystal"

sudo sqlite3 \
  "/Library/Application Support/com.apple.TCC/TCC.db" \
  "INSERT INTO access (service, client, client_type, allowed, \
    prompt_count, indirect_object_identifier, flags) VALUES(\
    'kTCCServiceSystemPolicyAllFiles', \
    '$BIN_PATH', \
    1, 1, 1, 'UNUSED', 0);"
```

Anyway, I went to System Preferences => Security & Privacy => Privacy => Full Disk Access. Then clicked the lock icon to make changes. Then I clicked "+" to add a new app, and navigated to my crystal source code folder. Then I needed to press `⌘+Shift+.` to show the hidden `.build` folder, and selected `.build/crystal`.

Unfortunately that didn't fix the spec. I tried again with the `bin/crystal` wrapper script, but that also didn't work.

**Comment by ndbroadbent** [comment]
I just saw [this comment in gitter](https://gitter.im/crystal-lang/crystal?at=594eb10bbf7e6af22c6c65d6):

> @chuanshuo crystal used to use libuv, but it then migrate to libevent. If I recall right, it was faster / lighter to use libevent that libuv. But asterite and waj are more aware of that story. I think that when using libuv inlining assembly was not an option. Today it is and the context switch is lighter also because of that. But I might be skipping some facts in the whole story.

**Comment by jwoertink** [comment]
@ndbroadbent If you want to run a single spec, you can either do
```crystal
it "does stuff", focus: true do

end
```

or run the spec file with the line number

`crystal spec spec/some_file.cr:355`
