### ISSUE TITLE
Support LLVM Berkley Packet Filter (BPF) target for blockchain smart-contracts

### ISSUE THREAD

**Issue by Tails** [crystal-lang/crystal#8564]
I am exploring several blockchain protocols to use for a project and would _love_ to use Crystal. 

[Solana is a 50k TPS chain that supports programming languages using something called the Berkley Packet Filter (BPF)](https://solana-labs.github.io/book/programs/index.html), targettable through LLVM.

> A program may be written in any programming language that can target the Berkley Packet Filter (BPF) safe execution environment. The Solana SDK offers the best support for C programs, which is compiled to BPF using the LLVM compiler infrastructure.

I have read the thread about WebAssembly support (https://github.com/crystal-lang/crystal/issues/829) so I am assuming the same roadblocks with garbage collection and the std lib apply here. 

Are there any other considerations that would make the BPF target unfeasable?

**Comment by bcardiff** [comment]
I think that the BPF is even harder to achieve than the WASM story because of the limited expressiveness a program can have.

> It's a very small and simple backend. There is no support for global variables, arbitrary function calls, floating point, varargs, exceptions, indirect jumps, arbitrary pointer arithmetic, alloca, etc. From C front-end point of view it's very restricted. It's done on purpose, since kernel rejects all programs that it cannot prove safe. It rejects programs with loops and with memory accesses via arbitrary pointers. When kernel accepts the program it is guaranteed that program will terminate and will not crash the kernel. [ref](https://www.phoronix.com/scan.php?page=news_item&px=LLVM-BPF-VM-Backend-Lands)

**Comment by bew** [comment]
I think this would be a great goal in the end, to be able to use the language with very limited features from the compiler and an alternate standard library.
The compiler currently still has a lot of things hardcoded like exceptions iirc in case of wrong type conversion (`1.as(String)`) though, so it's not for now.

**Comment by jhass** [comment]
In my opinion this more something that could be a fork or knock-off language. Think something like  what mruby is to Ruby. The goals Crystal currently has (basically least work for the programmer) seem to be quite contradictory to what kind of goals are needed here (expressive but minimal language).

**Comment by Tails** [comment]
Thank you for your insights!
