### ISSUE TITLE
non-blocking connect should check SO_ERROR ?

### ISSUE THREAD

**Issue by rdp** [crystal-lang/crystal#8565]
Based on https://stackoverflow.com/a/12079474/32453 it seems that after connect yields EINPROGRESS it should wait for writable then check the status of getsockopt SO_ERROR to see if it worked or not.
It wasn't immediately clear if crystal was doing the latter (the getsockopt part).  Probably not a big deal, because when you turn around and use the socket it would blow up with some other message but might be nice to add sometime if indeed it would be useful.

**Comment by rdp** [comment]
Maybe something like

```
diff --git a/src/lib_c/x86_64-linux-gnu/c/sys/socket.cr b/src/lib_c/x86_64-linux-gnu/c/sys/socket.cr
index 6cee17373..f20684d10 100644
--- a/src/lib_c/x86_64-linux-gnu/c/sys/socket.cr
+++ b/src/lib_c/x86_64-linux-gnu/c/sys/socket.cr
@@ -6,6 +6,7 @@ lib LibC
   SOCK_SEQPACKET =  5
   SOCK_STREAM    =  1
   SOL_SOCKET     =  1
+  SO_ERROR       =  4
   SO_BROADCAST   =  6
   SO_KEEPALIVE   =  9
   SO_LINGER      = 13
diff --git a/src/socket.cr b/src/socket.cr
index fb25d63ae..8271217c2 100644
--- a/src/socket.cr
+++ b/src/socket.cr
@@ -137,6 +137,9 @@ class Socket < IO
         wait_writable(timeout: timeout) do |error|
           return yield IO::Timeout.new("connect timed out")
         end
+        if ((ret = getsockopt(LibC::SO_ERROR, 0)) != 0)
+          return yield Errno.new("connect", ret)
+        end
       else
         return yield Errno.new("connect")
       end
```
? Is this on the right track?

**Comment by RX14** [comment]
What happens currently when a connect fails like this?

**Comment by rdp** [comment]
I will try to see if I can repro it sometime...

**Comment by yxhuvud** [comment]
https://www.xinotes.net/notes/note/1793/ seems to have all 133 (!) variants of `SO_OPTIONS`. I don't know which of those apply to this particular use case though.

**Comment by rdp** [comment]
closing till I have more time to look at it.  I believe it is wrong and probably should be fixed but also probably doesn't "really matter" since whenever one calls `read` or `write` on it it'll just blow up at that point :)
