### ISSUE TITLE
Docset for Crystal-lang

### ISSUE THREAD

**Issue by daya** [crystal-lang/crystal#8571]
Does crystal-lang has a Documentation Set that can be used in a tool like https://kapeli.com/dash

**Comment by Sija** [comment]
- that's a question more suited for the forum, not the issue tracker
- it takes far less energy to just search for it than to write this issue
- and yes, there is one:

![image](https://user-images.githubusercontent.com/988/70479261-42db8a00-1add-11ea-850c-9e1cd4138016.png)

**Comment by daya** [comment]
@bcardiff sorry but that must be Mac OS specific tool I am on Ubuntu using Zeal and I don't see that Crystal as on option
![image](https://user-images.githubusercontent.com/86925/70485328-3ee74200-1ab4-11ea-8fe7-261710b83fc1.png)

**Comment by bcardiff** [comment]
No need to say sorry, I closed since there is no actionable in this repo or another one in the organization.

@Sija might be able to help in this discussion :-)

**Comment by Sija** [comment]
Indeed, here you go: https://github.com/Kapeli/Dash-User-Contributions/raw/e0dc22fd1196280942a4654b7aaf569cb2815b6e/docsets/Crystal/Crystal.tgz :)

**Comment by daya** [comment]
Thanks @Sija

**Comment by Sija** [comment]
Btw, I've just compiled fresh docset for `v0.32.0`, available here - https://github.com/Kapeli/Dash-User-Contributions/blob/8e689e23e2aacb5ba114220e0bfb02a480fcd55b/docsets/Crystal/Crystal.tgz?raw=true
