### ISSUE TITLE
Array(T)#* of recursive type alias

### ISSUE THREAD

**Issue by lbguilherme** [crystal-lang/crystal#8607]
When updating an old project to the current Crystal release I found a case that used to work but now fails to build and looks like a compiler bug. Here is a reduced version:

```crystal
alias Type = Array(Type) | String

arr = ["aa", ["23"]] of Type

p arr # this works
p arr * 2 # this doesn't compile
```

Here is the compiler output:

```
In test.cr:6:7

 6 | p arr * 2
           ^
Error: instantiating 'Array(Type)#*(Int32)'


In /usr/share/crystal/src/array.cr:337:23

 337 | return Array(T).new(times, first)
                       ^--
Error: instantiating 'Array(Type).class#new(Int32, (Array(String) | Array(Type) | String))'


In /usr/share/crystal/src/array.cr:116:7

 116 | @buffer = Pointer(T).malloc(size, value)
       ^------
Error: instance variable '@buffer' of Array(Type) must be Pointer(Array(String) | Array(Type) | String), not Pointer(Array(String) | Array(Type) | String)
```

In particular, notice that the last line says `Pointer(Array(String) | Array(Type) | String)` is not the same as `Pointer(Array(String) | Array(Type) | String)`. But they look pretty much the same to me. Not sure what is going on.

This used to work on Crystal 0.30.1 (https://play.crystal-lang.org/#/r/88y1) but broke on Crystal 0.31.0 (https://play.crystal-lang.org/#/r/88y0)

**Comment by lbguilherme** [comment]
`arr.uniq` also fails to compile for a recursive type.

May be worth to mention: #5155

**Comment by Sija** [comment]
Possibly #8087 or #8048

**Comment by asterite** [comment]
The first snippet shouldn't compile at all because an Array(String) is inserted into Array(Type). This is a bug.

I hope someone removes recursive aliases in the future...

**Comment by HertzDevil** [comment]
The original snippet no longer compiles due to #10224.

**Comment by lbguilherme** [comment]
The original snippet now doesn't compile with a correct error message. And this example correctly compiles:

```cr
alias Type = Array(Type) | String

arr = ["aa", ["23".as Type]] of Type

p arr
p arr * 2
```
