### ISSUE TITLE
`String#sub(Hash(Char, _))` with str length 1 adds a NUL

### ISSUE THREAD

**Issue by bew** [crystal-lang/crystal#8637]
```cr
"C".sub({'C' => 'G'}) # => "G\u0000"
"C".sub({'C' => "G"}) # => "G\u0000"
```
https://carc.in/#/r/8b3o

**Comment by straight-shoota** [comment]
Not sure why this happens. But the implementation of `String#sub(Hash)` looks weird. Why is there a `if read.has_next?` which shouldn't be reachable?

**Comment by asterite** [comment]
The problem is if there's a match in the last char. The string size doesn't matter. For example:

```crystal
"helloC".sub({'C' => 'G'}) # => "helloG\u0000"
```

**Comment by mimame** [comment]
I've uploaded a pull request with the fix, I hope
