### ISSUE TITLE
what does this c++ file do

### ISSUE THREAD

**Issue by mobop** [crystal-lang/crystal#8638]
src/llvm/ext/llvm_ext.cc

**Comment by wontruefree** [comment]
I think it is the binding for the Crystal compiler to LLVM.  LLVM is written in C++ so I think you have to write a C++ interface instead of using the Crystal C binding interface.

**Comment by asterite** [comment]
@wontruefree That's almost true. LLVM provides a C API (that wraps the C++ API). However, not all of the C++ API is exposed by the LLVM C API and so we had to write these C functions that wrap the missing functions. And in fact we just copied them from the Go wrapper which needed to do the same.

But please use the [forum](https://forum.crystal-lang.org/) to ask questions. The issue tracker is meant to track issues and proposals.
