### ISSUE TITLE
String#scrub should replace the null byte

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#8684]
Title says it all. Or did I miss  something and the null byte is valid UTF-8? At least PostgreSQL doesn't think so.

**Comment by straight-shoota** [comment]
U+0000 is of course a valid Unicode value.

Postgres just doesn't allow null bytes in its text types. A typical workaround is to use bytea instead.

**Comment by jhass** [comment]
Yeah, I guess I dream too much when expecting UTF-8 to mean the same everywhere.... nvm me.
