### ISSUE TITLE
Parser errors with a {% commented in a macros

### ISSUE THREAD

**Issue by bcardiff** [crystal-lang/crystal#869]
```crystal
macro foo
  1
  # {% end %}
end

puts foo
```

Outputs
Syntax error in eval:3: expecting token 'EOF', not 'end'

http://play.crystal-lang.org/#/r/5k2

And, probably related

```crystal
macro foo
  1
  # {% 
end

puts foo
```

Outputs
Syntax error in eval:4: expecting token 'EOF', not 'end'

http://play.crystal-lang.org/#/r/5k3

**Comment by asterite** [comment]
Macro expressions and loops are active in comments so you can for example do this:

```crystal
macro getter(name)
  # Returns the {{name}}
  def {{name}}
    @{{name}}
  end
end
```

So you need to escape that with "\{%". But it still doesn't parse well, so I'll leave this open.

**Comment by waterlink** [comment]
Sounds like we need macro-comment, like `#% ... comment ...` or something.

--
Best Regards,
Alexey Fedorov,
Sr Ruby Developer, Clojure Developer, Rust Developer,
+49 15757 486 476

2015-06-27 17:50 GMT+03:00 Ary Borenszweig <notifications@github.com>:

**Comment by bcardiff** [comment]
Yes, @waterlink  it seems we do. I bumped into this while commenting/uncommenting some macro code to disable some lines.

@asterite not sure if something like this is also present in the `.ecr` files. 

And I'm not sure if it should be the other way around, leave `#` for comments of the macro and have other prefix like `#%` for comments that will be expanded in the resulting code. Otherwise leaving comments in the macros/and toying with them (cmd+`/`) does not work.

Will `{{ # Returns the {{name}}  }}` work as a syntax? Seems natural to me.

**Comment by asterite** [comment]
What should we do with this? I'd close this. I don't really see a compelling reason to introduce additional syntax for adding comments inside macros. You can use regular comments, and use:

```crystal
# \{% end %}
```

if you don't want that to be interpreted as part of the macro. In any case, if we add special syntax for this the editors will need to know they are inside a macro (maybe hard) and do something different.

**Comment by waterlink** [comment]
> the editors will need to know they are inside a macro

True. I would call closing this issue.

**Comment by keplersj** [comment]
It's been a while... Should we close the ticket?

**Comment by asterite** [comment]
Let's close it for now. Reopen if you need to do something about this (the solution above seems sufficient)
