### ISSUE TITLE
Adding a new >>> operator

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/crystal#8690]
In JavaScript, there's the [zero-fill right shift >>>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators#Unsigned_right_shift) operator. This is sort of like the `>>` operator, but returns a different result. 

```javascript
> -1 >> 7
-1
> -1 >>> 7
33554431
```

Ruby doesn't have this operator, but by looking at a [Github search](https://github.com/search?l=Ruby&q=zero-fill+right+shift&type=Code) we can see that a lot of people use it by writing their own.

I've started looking at writing some webassembly stuff with crystal just for playing around with, and I came across an example bit of code that used this operator in JS. Since Crystal doesn't have this operator, I had to find help in writing one:

```crystal
struct Int32
  # https://github.com/rjanse/demo-s3-swf-upload/blob/7acf16be7d2f75c42935aa1aa9af10b73d4376f7/vendor/plugins/s3-swf-upload-plugin/lib/patch/integer.rb#L8
  def zfrs(n : Int32)
    self >> n & (2**(32-n)-1)
  end
end
```

I don't know anything about bitwise operators, but with Crystal having access to lower level stuff, it sounds like this might be a cool method to have out of the box.

**Comment by RX14** [comment]
This is because in crystal we have both signed and unsigned integers. Javascript and ruby only have a single number type. `>>>` is just `UInt*#>>`. The same code written in crystal would just use unsigned types.

**Comment by ysbaddaden** [comment]
Just like C and Go we use ASHR (Arithmetic SHift Right) for signed integers to keep the MSB, thus the sign; but we use LSHR (Logical SHift Right) for unsigned integers where we don't need to keep the MSB.

Is LSHR on signed integers really useful? I'm not sure.

**Comment by jwoertink** [comment]
Ah! Ok, so this is just more of the fact that I have no idea what I'm doing versus Crystal needing stuff 😅  I 
 forget where I got the `-1` value for my example from, but I guess I never would have got that if I kept using a negative lol. 

Feel free to close this out. Thanks for the explanation 😄

**Comment by yxhuvud** [comment]
@ysbaddaden It can be pretty convenient when porting code from java. Code like https://github.com/HdrHistogram/HdrHistogram/blob/master/src/main/java/org/HdrHistogram/ZigZagEncoding.java#L35 can of course be translated to crystal, but it would be less error prone if the >>> operator existed.

**Comment by ysbaddaden** [comment]
@yxhuvud As per https://developers.google.com/protocol-buffers/docs/encoding, ZigZag encoding of signed integers is merely (verified):
```crystal
def zigzag(n : Int32)
  (n << 1) ^ (n >> 31)
end

def zigzag(n : Int64)
  (n << 1) ^ (n >> 63)
end
```

Then you can apply the LEB128 encoding on the resulting number. Following C/C++ or Go libraries would probably be better (as Crystal `>>` operator behaves as them), rather than following Java :)
