### ISSUE TITLE
Error: undefined method 'unsafe_shr' for BigInt

### ISSUE THREAD

**Issue by q9f** [crystal-lang/crystal#8691]
Exponentiation of an `Int32` with a `BigInt` fails. I _believe_ this is a bug even though, admittedly, I ran into this by coincidence and you usually don't want to exponentiate an `Int32` with a `BigInt`. But I also think this should be possible.

- [x] Make sure a similar issue doesn't exist yet: use the search box
- [x] **Include reproducible code**: we should be able to paste it into an editor, compile and run it and get the same error as you. Otherwise it's impossible for us to reproduce the bug.
    ```crystal
    # debug.cr
    
    require "big/big_int"
    
    pp 256 ** BigInt.new(8)
    ```
- [x] Don't **only** use `play.crystal-lang.org` or `carc.in`: code might be lost and the issue will remain incomplete. Write code in the issue itself.
- [x] Reduce code, if possible, to the minimum size that reproduces the bug.
- ~~If all of the above is impossible due to a large project, create a branch that reproduces the bug and point us to it.~~
- [x] Include Crystal compiler version (`crystal -v`) and OS. ~~If possible, try to see if the bug still reproduces on master.~~

```
~/.opt/rlp.cr master*
❯ crystal run debug.cr --verbose --error-trace
In debug.cr:3:8

 3 | pp 256 ** BigInt.new(8)
            ^-
Error: instantiating 'Int32#**(BigInt)'


In /usr/lib/crystal/int.cr:281:27

 281 | exponent = exponent.unsafe_shr(1)
                           ^---------
Error: undefined method 'unsafe_shr' for BigInt

BigInt trace:

  /usr/lib/crystal/int.cr:281

          exponent = exponent.unsafe_shr(1)


  /usr/lib/crystal/int.cr:272

      def **(exponent : Int) : self


~/.opt/rlp.cr master*
❯ crystal version
Crystal 0.32.1 (2019-12-18)

LLVM: 9.0.0
Default target: x86_64-pc-linux-gnu

~/.opt/rlp.cr master*
❯ uname -a
Linux vesta 5.4.11-arch1-1 #1 SMP PREEMPT Sun, 12 Jan 2020 12:15:27 +0000 x86_64 GNU/Linux
```

It does not happen with two `BigInt` types:

```crystal
pp BigInt.new(256) ** BigInt.new(8)
# => 18446744073709551616
```

**Comment by asterite** [comment]
I think `unsafe_shr` should be added as an alias of `>>` to `BigInt`.
