### ISSUE TITLE
JSON::PullParser numeric overflow behaviour

### ISSUE THREAD

**Issue by KimBurgess** [crystal-lang/crystal#8694]
The current implementation of `JSON::PullParser` includes a [set of `#read?` methods](https://github.com/crystal-lang/crystal/blob/42a64909fae022863e68651a3d35f3c45884efc8/src/json/pull_parser.cr#L267-L315). In the case of an overflow these will silently wrap the value to fit the target type. Usage of these within std lib is limited to [within `Union.from_json`](https://github.com/crystal-lang/crystal/blob/42a64909fae022863e68651a3d35f3c45884efc8/src/json/from_json.cr#L242).

Similarly, [methods for instantiating numeric primitives from a `PullParser`](https://github.com/crystal-lang/crystal/blob/42a64909fae022863e68651a3d35f3c45884efc8/src/json/from_json.cr#L69-L81) all silently wrap.

This can lead to some unexpected behaviour as shown [here](https://github.com/crystal-lang/crystal/pull/8689#discussion_r367175575) and [here](https://github.com/crystal-lang/crystal/pull/8686#issuecomment-573830506).

It appears that it may be more desirable to have both of this instances use conversions that raise an `OverflowError` in cases where the parsed value cannot be represented by the target type.

Happy to submit a PR for this, but opening up for discussion / approval first.

**Comment by asterite** [comment]
Yes, new! should be new and overflow errors should be wrapped in JSON::ParseError. Make sure you keep the location in the error.
