### ISSUE TITLE
Order of magnitude worse performance with linux compared to macOS

### ISSUE THREAD

**Issue by taylorthurlow** [crystal-lang/crystal#8701]
I've compiled binaries of a [program I wrote](taylorthurlow/thicket) for both macOS and Linux.

The macOS binary runs 10x faster (not exaggerating). It's compiled (with `--release`) with Crystal 0.32.1 (built on with LLVM 9.0). The Linux binary is compiled (with `--release`) with Crystal 0.32.1 (build with LLVM 8.0). The performance figure is based on macOS running the code on bare metal, and the linux code is running in Docker for Mac, on Ubuntu 18.04. I'm sure there's some virtualization overhead, but there's no host/guest disk activity in the test, just some local disc activity, but nothing significant.

I don't know enough about compiled languages in general, any idea what might be causing it?

EDIT: Just to get an idea of the code itself, the vast majority of the workload is text parsing, regex, and string manipulation.

**Comment by Blacksmoke16** [comment]
`Docker for Mac` is essentially docker running within a VM, so there's going to be some overhead for that as you said.  See https://medium.com/@dogweather/dev-environment-performance-tests-docker-vs-native-mac-vs-linux-old-vs-new-883399d05182.

Do you have an example benchmark that can be used to test this?

Also, this is something that is probably more suited for https://forum.crystal-lang.org.

**Comment by taylorthurlow** [comment]
I agree about docker for Mac, I originally realized there was an issue because of horrible performance on a laptop running Linux natively, I just didn't have statistics for how much worse it was for that case. I just don't think even a VM would be 10x worse. I'll see if I can whip up something that replicates it, and I'll post it on the crystal forum, thanks.

**Comment by RX14** [comment]
We'd greatly appreciate a more targeted performance issue but I think the best place to explore what's causing this issue is the forum for now.

**Comment by RX14** [comment]
Found out the issue, you call `tput cols` on *every single* line of output. Setting `TERM` to blank causes the execution to speed up by many times.

Either process spawning is far faster in macos for some reason (which is out of our control) or your `TERM` is set to blank in macos and you're falling down the fast path.

I'd suggest calculating `terminal_width` once at the start then caching it for the rest of the output. (bonus points for handling `SIGWINCH` to bust the cache)
