### ISSUE TITLE
Memory layout for different AST types.

### ISSUE THREAD

**Issue by skuznetsov** [crystal-lang/crystal#8726]
@asterite @straight-shoota @bcardiff @ysbaddaden @RX14 
I have a question regarding memory layout for different AST types.
I am lost a little with some of the type layouts as I can see that in most of the cases it is working just fine and in some cases it shows me type_id instead of pointer.
In which cases struct is inlined in another struct and in which cases it is keeping only pointer (I am aware of type.struct? check but it not always help.
in case of pointer is it points to type_id or to next value after type_id?
Can you guys provide some diagrams that can help me to understand that.
I am doing quite well but I want to be sure that I am not making any mistakes.

**Comment by RX14** [comment]
Structs are always embedded, never boxed

Pointer points to the type_id

**Comment by skuznetsov** [comment]
> Structs are always embedded, never boxed

Yeah, I got that part. I always look at `type.struct?` and if so I don't create the pointer.
> 
> Pointer points to the type_id
What about `(Int8|Int16|Int32|UInt64|Nil)` type? how it will be presented in LL type? `%{Int32, [i64 x 1]}` ?

**Comment by asterite** [comment]
Hi!

I think this is a question better suited for the [forums](https://forum.crystal-lang.org/).

> Structs are always embedded, never boxed

Except for abstract structs. These are also represented as `{type_id, value}`.

But please ask this in the forums and let's continue discussing there.
