### ISSUE TITLE
crystal 0.32 crashed on old ubuntu 12.04

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#8775]
crystal 0.29 works ok, but after update to 0.32 it crashed.

`cat /etc/issue`
```
Ubuntu 12.04.1 LTS \n \l
```

`/home/kostya/crystal-0.32.1-1/bin/crystal --version`
```
Crystal 0.32.1 [41bd18fbe] (2019-12-18)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```

`/home/kostya/crystal-0.32.1-1/bin/crystal eval 'p 1'`
```
/usr/bin/ld: BFD (GNU Binutils for Ubuntu) 2.22 internal error, aborting at ../../bfd/reloc.c line 443 in bfd_get_reloc_size

/usr/bin/ld: Please report this bug.
```

**Comment by oprypin** [comment]
> Ubuntu 12.04 LTS has reached the end of life on 28th April 2017

I don't think this is worth anyone's time :(

**Comment by kostya** [comment]
Yes :( But may be, this is some simple fix, who knows. Hard to update OS on production system, which works many years.

**Comment by Sija** [comment]
> Hard to update OS on production system, which works many years.

No-one likes it, but it's called _maintenance_, gotta do it once in a while...

**Comment by bcardiff** [comment]
There are some realloc issues in trusty that will be fixed on 0.33. Tomorrow nightly should have that patch and we can check if that solves this issue. Ref: #8653

**Comment by rdp** [comment]
See also #8323

**Comment by bcardiff** [comment]
Seems to be fixed on nightly already.
You can try out the binaries from https://38201-6887813-gh.circle-artifacts.com/0/dist_packages/crystal-nightly-20200211-1-linux-x86_64.tar.gz

**Comment by kostya** [comment]
Fixed, thanks.
