### ISSUE TITLE
Parser fails on short form operator calls

### ISSUE THREAD

**Issue by Daniel-Worrall** [crystal-lang/crystal#8777]
When using the `<` or similar comparisons inside a case statement using the playground, it thinks there's a syntax error. This compiles fine normally.

Minimal code
```cr
case 1
when .< 2
end
```

Returns
```
Code
case 1
  when .< 2
end
Exception
syntax error in play:2
Error: unexpected token: <
```

*Crystal 0.32.1 [41bd18fbe] (2019-12-18) LLVM: 8.0.0 Default target: x86_64-unknown-linux-gnu*

**Comment by HertzDevil** [comment]
This is not exclusive to the playground. It happens whenever the compiler prints an operator call with an implicit object:

```crystal
macro foo(x)
  {% p x %}
end

foo(case 1
when .<(0)
end)
```

```
case 1
when  < 0
end
```
