### ISSUE TITLE
Regression in `BigDecimal#to_big_i` 

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#8789]
Regression introduced in Crystal 0.31.0 (#8120)

```cr
require "big"
 
"-100.000".to_big_d.to_big_i # => -100000
```

Before: https://carc.in/#/r/8jrq
After: https://carc.in/#/r/8jro

/cc @bcardiff

**Comment by straight-shoota** [comment]
Other broken case: `"-1.1".to_big_d.to_big_i # => -10`. #8790 doesn't fix this.

**Comment by Sija** [comment]
@straight-shoota Force-pushed amended commit with the fix.

**Comment by bcardiff** [comment]
I scheduled the PR for 0.34.0. It could not review it yet.

**Comment by straight-shoota** [comment]
Would've been nice to include it in 0.33.0 since it's already fixed. But I guess it's fine.

**Comment by Sija** [comment]
@bcardiff It's been reviewed already and there are tests, so why hold it back...?

**Comment by Sija** [comment]
@straight-shoota Thanks for merging! I guess it should have the `0.34.0` milestone added too.

**Comment by straight-shoota** [comment]
Usually only PRs are milestoned (see previous ones) to keep the noise down. Both PR and issue relate to the same bug or feature and we only need to have one representation in the milestone.

**Comment by Sija** [comment]
@straight-shoota Good to know, I got mistaken by this:

![image](https://user-images.githubusercontent.com/988/74764869-d6ba9680-5282-11ea-91cf-1f9388bbd542.png)
