### ISSUE TITLE
File.expand_path broken - ~ (tilde) not replaced correctly

### ISSUE THREAD

**Issue by Kjarrigan** [crystal-lang/crystal#8797]
Instead of replacing ~ (tilde) with $HOME it appends **pwd** for example `File.expand_path("~/foo")` produces this:

```
/home/holger.arndt/Projects/crystal/~/foo
```

instead of

```
/home/holger.arndt/foo
```

I have not rebuild my binary for a while and just stumbled over this bug. I then downloaded various releases from github and found that this "changed" with `0.32.0` and is still broken in `0.32.1`
It still worked in `0.31.1`

### Test-Code
```
puts current =  File.expand_path("~/foo")
puts expected = File.join(ENV["HOME"], "foo")

raise "Wrong path" if current != expected
```

### Output
```
/home/holger.arndt/Projects/crystal/~/foo
/home/holger.arndt/foo
Unhandled exception: Wrong path (Exception)
```

### First Broken Version
```
Crystal 0.32.0 [6952aacb3] (2019-12-11)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```

### Last Working Version
```
Crystal 0.31.1 [0e2e1d067] (2019-09-30)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by jhass** [comment]
This was an intentional change, see #7903. Call `File.expand_path("~/foo", home: true)`.
