### ISSUE TITLE
0.33 formatter escape strings bug

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#8806]
Crystal 0.33.0 (2020-02-14)
formatter  replace this string `puts "#\{}"` with `puts "#{}"` which is not compiled.

**Comment by bcardiff** [comment]
This is due to #8619. I believe the expected is to use `”#\\{}”` now in this case.

**Comment by asterite** [comment]
The correct way to escape that is: `"\#{}"`.

Note that kostya wants `"#{}"` as an output, not `"#\{}"`.

**Comment by kostya** [comment]
So, if this is the only case, its ok, seems

**Comment by straight-shoota** [comment]
I'd say the formatter could apply this fix automatically. Not sure how relevant that would be in 0.34.0, though...

**Comment by Sija** [comment]
Hmm, btw why don't `"#{}"` compile? I'd say it should. fwiw it works in Ruby.

**Comment by straight-shoota** [comment]
Empty interpolation is a special case. IMO both ways to handle that are legit. The current error message for `"#{}"` could be improved though: `unexpected token: }`

**Comment by bcardiff** [comment]
I agree with @Sija. I think it would be good to handle it as `"#{nil}"`. Yet that is still a different situation from the one exposed original in this issue.

It might come handy in generated code.
