### ISSUE TITLE
gmake fails on Freebsd

### ISSUE THREAD

**Issue by devosalain** [crystal-lang/crystal#8808]
OS : FreeBSD 12.1-RELEASE-p1
Compiler : llvm v 9.0.0
Output of gmake : 
```
Using /usr/local/bin/llvm-config90 [version=9.0.0]
c++ -c  -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc -I/usr/local/llvm90/include -std=c++11   -fno-exceptions -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
cc -fPIC    -c -o src/ext/sigfault.o src/ext/sigfault.c
ar -rcs src/ext/libcrystal.a src/ext/sigfault.o
CRYSTAL_CONFIG_PATH="/home/x/Libraries/crystal/crystal/src" CRYSTAL_CONFIG_LIBRARY_PATH="" CRYSTAL_CONFIG_BUILD_COMMIT="612825a53" ./bin/crystal build  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
Error in src/compiler/crystal.cr:1: while requiring "prelude"
# This is the file that is compiled to generate the
^
in src/prelude.cr:27: while requiring "iterator"
require "iterator"
^
in src/iterator.cr:1: while requiring "./enumerable"
require "./enumerable"
^
Syntax error in src/enumerable.cr:341: unexpected token: :
def each_cons_pair(& : (T, T) -> _) : Nil
gmake: *** [Makefile:118: .build/crystal] Error 1

**Comment by straight-shoota** [comment]
What's the compiler version? `crystal --version`

**Comment by devosalain** [comment]
crystal -v   
Crystal 0.28.0 (2020-02-15)
LLVM: 6.0.1
Default target: x86_64-portbld-freebsd12.1

**Comment by Blacksmoke16** [comment]
@devosalain You'll need to use at least a `0.32.0` binary to compile the latest binary.

**Comment by devosalain** [comment]
So how do i build a 0.32.0 binary , with or without my 0.28.0 binary without,
but in order to not end up in a bootstrapping catch 22 ?

**Comment by Blacksmoke16** [comment]
Could you not just [install](https://crystal-lang.org/install), or grab it from the [releases tab](https://github.com/crystal-lang/crystal/releases)?

**Comment by devosalain** [comment]
The install gives me the 0.28.0 binary so that does not help.
Maybe i could try to compile the 0.29.0 source with my 0.28.0 binary ? and so on ...

**Comment by Blacksmoke16** [comment]
That would probably work as well, or just grab the binary/release package from the latest release and use that?

**Comment by devosalain** [comment]
There was a never binary version for freebsd available at :
http://pkg.freebsd.org/FreeBSD:12:amd64/latest/All/crystal-0.32.1.txz
I'll start with this one and check how recent i can go ...
