### ISSUE TITLE
Wrong version inside alpine images for 0.33.0

### ISSUE THREAD

**Issue by sdwolfz** [crystal-lang/crystal#8814]
:warning: The `0.33.0` alpine images report version `0.32.1` :warning: 
- `docker run --rm -it crystallang/crystal:0.33.0-alpine-build crystal --version`
```
Crystal 0.32.1 [41bd18fbe] (2019-12-18)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-musl
```
- `docker run --rm -it crystallang/crystal:0.33.0-alpine crystal --version`
```
Crystal 0.32.1 [41bd18fbe] (2019-12-18)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-musl
```

:heavy_check_mark: The non alpine one reports the right version. :heavy_check_mark: 
- `docker run --rm -it crystallang/crystal:0.33.0 crystal --version`
```
Crystal 0.33.0 [612825a53] (2020-02-14)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by bcardiff** [comment]
Thanks for reporting. I've just update the 0.33.0-alpine and latest-alpine docker images.

**Comment by straight-shoota** [comment]
Any idea why it was wrongly tagged?

**Comment by bcardiff** [comment]
Because the target in the makefile to copy the tar.gz is not phony, or because I didn’t do a make clean. :-)

I already update the release checklist with that info.

**Comment by sdwolfz** [comment]
Tried them out again and the versions are correct, thaks for the fix! 👍

**Comment by straight-shoota** [comment]
Should we add some kind of validation for this? For example verify that `crystal --version` contains the version part of the docker tag before pushing it.

**Comment by bcardiff** [comment]
The ubuntu images [have those validation](https://github.com/crystal-lang/crystal-dist/blob/master/dist.sh#L71-L72). The alpine images are new and there are no steps in the crystal-dist repo yet, so, I manually do those steps for this first version.
