### ISSUE TITLE
NULL C function pointers are mapped to a 0x0 Proc

### ISSUE THREAD

**Issue by postmodern** [crystal-lang/crystal#8820]
I stumbled across an unexpected/confusing behavior of how Crystal's C binding type system handles `NULL` function pointer variables or struct fields. Function pointer variables or struct fields which are set to `NULL` are mapped to a ` Proc` pointing to `0x0` (aka `NULL`) instead of `Nil`. Also, there's no `Proc#null?` method; although I eventually learned that `proc.pointer.null?` works. I even tried defining the struct field as `callback : Callback?`, but that just appended ` | Nil` to the type definition within the `Proc`. All of this makes it difficult to test for `NULL` function pointer values.

### foo.h

```
#include <stdint.h>

typedef int (*foo_callback)();

struct foo
{
	int32_t var;
	foo_callback *callback;
};

extern void foo_init(struct foo *foo);
extern int foo_callback1();
extern int foo_callback2();
```

### foo.c

```
#include "foo.h"

#include <stdio.h>

void foo_init(struct foo *foo)
{
	foo->var = 1;
	foo->callback = NULL;
}

int foo_callback1()
{
	puts("callback 1");
	return 1;
}

int foo_callback2()
{
	puts("callback 2");
	return 2;
}
```

### foo.cr

```
@[Link(ldflags: "-L#{__DIR__} -lfoo")]
lib LibFoo

  alias Int = LibC::Int
  alias Callback = -> Int

  struct Foo
    var : Int32
    callback : Callback
  end

  fun foo_init(foo : Foo *)
  fun foo_callback1() : Int
  fun foo_callback2() : Int
end

foo = LibFoo::Foo.new

LibFoo.foo_init(pointerof(foo))
puts "With foo.callback NULL: #{foo.callback.inspect}"

foo.callback = ->LibFoo.foo_callback1
puts "With foo.callback set: #{foo.callback.inspect}"
```

## Steps To Reproduce

    $ cc -Wall -fPIC -shared -o libfoo.so foo.c
    $ crystal build foo.cr
    $ LD_LIBRARY_PATH=$PWD ./foo

### Output

    With foo.callback NULL: #<Proc(Int32):0x0>
    With foo.callback set: #<Proc(Int32):0x7f5c76f9812a>

**Comment by asterite** [comment]
It's on purpose. Any thing that binds to C and is a pointer, including function pointers (procs), can be set to nil to specify C NULL.

It's a feature.

That said, we could consider having nilable procs in that case. But usually C bindings are hidden behind user level code where you can use nilable procs.

**Comment by postmodern** [comment]
> it's a feature.

Where is this feature documented? I had to ask in IRC to learn that `proc.pointer.null?` is how you test null-ness of a C function pointer Proc. Also seems odd that you can actually call the `#<Proc(...}:0x0>` proc and it won't raise an error; obviously not allowed in C. Not sure if that behavior was also intentional as a way to avoid having to guard against NULL function pointers?

**Comment by asterite** [comment]
> obviously not allowed in C

Can't you call that function in C? You'd get a segfault, which I think is what will happen in Crystal too.

I guess my idea when implementing this was being able to clear callbacks on the C side. I never thought about reading callbacks from C and checking if they are null.

For what library is this?

**Comment by postmodern** [comment]
@asterite ah my mistake. I didn't realize C procs are not `()` callable and that just returns the value. `.call()`ing a NULL C Proc does indeed trigger a SigSEGV. However, there should be an easy way to test for `NULL`-ness of a C Proc in order to avoid a SigSEGV.
