### ISSUE TITLE
Proc with multiple return type throwing exception when returning one of the type

### ISSUE THREAD

**Issue by ujjwalguptaofficial** [crystal-lang/crystal#8821]
Consider below code - 

```
store = {} of String => Proc(Int32, Int32 | Nil)
 
store["hi"] = -> (val : Int32){
  return nil
} 
```

Here when proc implementation return nil, then compiler throwing a cast exception. 

> Error: no overload matches 'Hash(String, Proc(Int32, (Int32 | Nil)))#[]=' with types String, Proc(Int32, Nil)

Here is link to crystal play - https://play.crystal-lang.org/#/r/8l35

**Comment by straight-shoota** [comment]
Generic type arguments must exactly match the specified type restrictions. There is currently no support for (co)variance in the type grammar.

You can explicitly cast the return type to `Int32 | Nil` to make this work:
```cr
store = {} of String => Proc(Int32, Int32 | Nil)
 
store["hi"] = -> (val : Int32){
  return nil.as(Int32 | Nil)
}
```

**Comment by asterite** [comment]
I also recommend using an `alias` for a Proc:

```crystal
alias MyProc = Proc(Int32, Int32 | Nil)

store = {} of String => MyProc

store["hi"] = MyProc.new do |val|
  return nil
end
```
