### ISSUE TITLE
JSON::PullParser can't convert `UInt64` values

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#8830]
As a result of https://github.com/crystal-lang/crystal/issues/8694, when trying to read a `UInt64` value from a JSON string, it raises an exception that it `Can't read UInt64`.

https://carc.in/#/r/8lso

```cr
require "json"

pp UInt64.from_json "11719215035155661212"
```

It seems this is caused by `JSON::PullParser` having `int_value` be typed as `Int64` which overflows, then raises an `OverflowError` when trying to convert the negative overflowed value to an unsigned int.

https://carc.in/#/r/8lsp

```cr
require "json"
 
pull = JSON::PullParser.new "11719215035155661212"
 
value = pull.read_int
 
pp value.to_u64
```

A workaround would be doing like `pull.read_raw.to_u64`.

**Comment by asterite** [comment]
Yup, it's a bug. It used to work in 0.32.0
