### ISSUE TITLE
Error message when private constant is referenced

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#8831]
The error message when referencing a private constant should be more specific, currently it only reports the constant as `undefined` which is not correct. The constant *is* defined, it's just not visible.

```cr
private class Foo::Bar
end
 
Foo::Bar # Error: undefined constant Foo::Bar
```

`Crystal::Path#raise_undefined_constant` has a branch for error message `"private constant #{private_const} referenced"` message, but it seems it doesn't apply here.

**Comment by jwoertink** [comment]
Just adding to this, since I just ran in to it; it only happens if the class is namespaced.

```crystal
private class Foo
end

Foo # this is fine even though it's private
```

**Comment by straight-shoota** [comment]
Top level private types are visible inside the file they're defined in.

**Comment by HertzDevil** [comment]
As mentioned in #13511, the constant is defined in the wrong namespace, so `Foo::Bar` is truly undefined
