### ISSUE TITLE
Array `#compact!` does not remove nil from type

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#8848]
Array compact does not remove Nil from the return type.  I don't know what would be expected here.  This means similar APIs will break because Nil could still be in the return type.  

https://play.crystal-lang.org/#/r/8mbg
```cr
source = [1, 2]
array = [nil, 3, 4, 5, nil]

source.concat(array.compact) # => 1, 2, 3
source.concat(array.compact!) # => compile fail
```

I think at least some note should be added to the docs.

**Comment by Blacksmoke16** [comment]
AFAIK this is expected since this doesn't change the type of the original array.  `compact` works since it returns a _NEW_ array without `Nil`.

**Comment by wontruefree** [comment]
If you remove the type and then call other APIs it could cause errors the other way.

I just think it might be worth pointing out in the docs.

**Comment by lbguilherme** [comment]
The documentation says:

> Removes all `nil` elements from `self´ and returns `self`.

I think it is clear already.

@wontruefree What would you change it to?
