### ISSUE TITLE
Class variable initialization is wrong for numeric literals

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#8862]
Running this code:

```crystal
class Foo
  @@foo = begin
    p "Initializing!"
    1
  end

  def self.foo
    @@foo
  end
end

p Foo.foo
```

Just prints 1, but never "Initializing!".

Used to work fine in 0.30.0.

I'm almost sure it's related to one optimization in the compiler where if a class variable is an integer literal then it doesn't need an initializer. But in this case the initializer is a bit more complex.

/cc @waj

Also, can we add a `topic:compiler:codegen` label? /cc @bcardiff

**Comment by asterite** [comment]
The problem is this line:

https://github.com/crystal-lang/crystal/blob/c4d70bc4e0742b6fafb94ab4b5b6185c9069b291/src/compiler/crystal/codegen/class_var.cr#L140

It shouldn't check for a primitive type and if it's a constant, it should check if it's a constant but also if it's a literal.

Of course this will make things like `1 + 2` stop working. That's why I think we still need to try to interpret the value and see if we can come up with a compile-time value.

**Comment by bcardiff** [comment]
> Also, can we add a topic:compiler:codegen label? /cc @bcardiff

To me it lands in topic:compiler:semantics. Why it doesn't to you?

**Comment by asterite** [comment]
Because the bug is in the codegen phase of the compiler.

Semantic to me is about types. Codegen is about how we execute code at runtime. Or maybe just to say "The bug is in the codegen section of the compiler".

**Comment by bcardiff** [comment]
For me it was about the semantic of the code. But, sure I will create that label.

**Comment by oprypin** [comment]
@bcardiff I think that's referring to the compilation stage named "semantic", not *semantics* as a general term.
