### ISSUE TITLE
Defining a generic-typed constant in a class causes a vague compiler error

### ISSUE THREAD

**Issue by postmodern** [crystal-lang/crystal#8866]
Related to issue #8861, defining a generic-typed constant in a base class (abstract or not) causes the compiler to assume the generic type is a constant. At the very minimum the compiler error could be improved.

## Example

```crystal
class Base(T)

  VAR = T.new(0)

end

class Foo < Base(Int32)
end

p Foo::VAR
```

## Error

```
Showing last frame. Use --error-trace for full trace.

In test.cr:3:9

 3 | VAR = T.new(0)
           ^
Error: undefined constant T
make: *** [Makefile:4: test] Error 1
```

**Comment by asterite** [comment]
Constants are typed immediately. It's not like each generic type instantiation has a different constant associated to it. The entire type declaration has exactly one constant, and T doesn't exist. There's no bug here.

And I doubt this will ever change.
