### ISSUE TITLE
Incomplete CSV file if writing a file with CSV module

### ISSUE THREAD

**Issue by nothratal** [crystal-lang/crystal#8875]
Hello together,

while generating some test data in a CSV file I recognized that the produced file doesn't contain all the lines it should have. I reduced the code as much as possible. As a workaround I'm able to produce a correct file by using the normal "File" module and joining my fields with ";".

```crystal
require "csv"

class Testcase
  property status
  property tool
  property comment

  def initialize(
    status = "",
    tool = "",
    comment = ""
  )
    @status = status
    @tool = tool
    @comment = comment
  end
end

testcases = Hash(String, Testcase).new

4000.times do |x|
  testcases["Testcase_#{x}"] = Testcase.new(status: "passed", tool: "selenium", comment: "some unnecessary comment #{x}")
end

puts "hash has correct size of 4000 = #{testcases.size == 4000}"

CSV.build(File.new(filename: "./generated_tests.csv", mode: "w"), separator: ';') do |csv|
  csv.row "TESTNAME", "STATUS", "TOOL", "COMMENT"
  counter = 0
  testcases.each do |tc_name, tc|
    counter += 1
    csv.row tc_name, tc.status, tc.tool, tc.comment
  end
  puts "number of hash iterations is also #{counter}, so no issue here"
end

lines = File.read_lines("./generated_tests.csv")
puts "Lines of created csv file: #{lines.size}" # => "Lines of created csv file: 3995"
```

Tested it on:
Current Ubuntu stable & Crystal 0.33.0
Windows Ubuntu WSL & Crystal 0.33.0
play.crystal-lang.org & Crystal 0.33.0: https://play.crystal-lang.org/#/r/8o8z

**Comment by asterite** [comment]
Hi!

The problem is that the file is not flushed.

If you code it like this:

```crystal
File.open(filename: "./generated_tests.csv", mode: "w") do |file|
  CSV.build(file, separator: ';') do |csv|
    # ...
  end
end
```

then it works fine. The `File.open` block version makes sure to flush the file when the block exists. Not only that, but it makes sure the file is closed. In your program you were leaking a file descriptor.

I guess `CSV.build` should call `flush` on the IO when the block exists so that would already be an improvement. I'll do that.

**Comment by asterite** [comment]
Another alternative:

```crystal
file = File.new(...)
CVS.build(file) do 
  ...
end
file.close # or file.flush
```

but you should always close files after you use them.

**Comment by nothratal** [comment]
Yeah, you're right I should close them! I missed that completely, just was surprised that with file block it's working. Thanks for the improvement suggestion => branch toilet.

**Comment by nothratal** [comment]
Yeah, you're right I should close them! I missed that completely, just was surprised that with file block it's working. Thanks for the improvement suggestion => branch toilet.
