### ISSUE TITLE
Exceptions raise in a function called from C are not rescued

### ISSUE THREAD

**Issue by ricardog** [crystal-lang/crystal#8878]
Hi --

I'm writing a binding for GDAL and have run into an issue where crystal exceptions raised from a function called by C are not rescued. 

Here is what the top-level crystal code looks like

```
  begin
    ds = LibGDAL.open("data/foo.tif", LibGDAL::Access::GaReadOnly)
    #raise GDALError.new() if ds.null?
  rescue ex : GDALError
    puts ex.message
    puts ex.code
    puts ex.type
  end
```

The function `LibGDAL.open` will callback into a crystal error handler which raises an exception if there is an error opening the file. Here is the stack trace

```
Unhandled exception: data/foo.tif: No such file or directory (GDAL::GDALError)
  from src/gdal.cr:49:15 in '->'
  from CPLErrorV
  from CPLError
  from VSIToCPLError
  from GDALOpenEx
  from src/gdal.cr:164:5 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:106:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:92:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:115:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```

`crs/gdal.cr:164` is the call to `LibGDAL.open()`.

**Comment by ricardog** [comment]
Sorry, submitted too early by mistake.

If I change the behavior of the error handler to print a message and return and raise the exception in the main code (as in the commented line above), then the exception is rescued correctly.

For now the error callback in crystal is implemented via a proc

**Comment by asterite** [comment]
When is the callback executed?

If the callback is executed when you call a particular C function, you must mark that function as `@[Raises]`

**Comment by ricardog** [comment]
Thanks @asterite . The callback is called when an error occurs. In this example it's trying to open a file that doesn't exist.

In the stack trace above would that be `GDALOpenEx` (the first C function called from crystal) or `CPLErrorV` (the C function that calls crystal)? I suspect the former but want to double check.

The GDAL API doesn't document which function can "throw" an error so it's not easy to annotate the functions with `@[Raises]`

Is there a recommended crystal pattern for an API like this one?

**Comment by asterite** [comment]
Could you try it yourself? I don't have access to your code.

**Comment by asterite** [comment]
@ricardog Did it work?

We could consider automatically marking all C functions as `Raise`... I can't remember if you do that already.

**Comment by ricardog** [comment]
@asterite -- yes, marking the C function as `@[Raises]` solves the issue. 

I thought of asking for a way to mark a Lib such that all C functions are automatically declared as `Raises`. But realized for this API that would not be enough (error handling in GDAL is complex).

I don't know what the cost of marking a C function as `Raises` is. If it's not free, then I would leave the implementation as is.

Thanks.
