### ISSUE TITLE
optimize fill(0) for integer arrays

### ISSUE THREAD

**Issue by jzakiya** [crystal-lang/crystal#8898]
Per discussion here
https://forum.crystal-lang.org/t/fastest-and-iconic-way-to-zero-an-array/1799/17

optimize ``fill(0)`` operation for integer arrays.

```
class Array(T)
  def fill(value : T)
    {% if Int::Primitive.union_types.includes?(T) %}
      if value == 0
        to_unsafe.clear(size)
      else
        fill { value }
      end
    {% else %}
      fill { value }
    {% end %}
  end
end
```

**Comment by straight-shoota** [comment]
For the implementation, checking for `value.zero?` is probably better.

**Comment by yxhuvud** [comment]
Well, we still need to decide what to do with Floats, for which there is a 0 that is not all 0s.

**Comment by jzakiya** [comment]
Dealing with floats need not prevent optimizing for integers.
If there is an accepted viable process to optimize for floats it can be added later.

**Comment by asterite** [comment]
> For the implementation, checking for value.zero? is probably better.

Why?

**Comment by straight-shoota** [comment]
I'd say `.zero?` should be recommended generally because it work for any number type. In this case it doesn't matter, but for example with complex numbers it makes a difference.

**Comment by jzakiya** [comment]
> I'd say `.zero?` should be recommended generally because it work for any number type. In this case it doesn't matter, but for example with complex numbers it makes a difference.

Thanks, I didn''t realize that, but good to know, though here we know ``value`` is an integer.

**Comment by jzakiya** [comment]
PR done here.

https://github.com/crystal-lang/crystal/pull/8903

**Comment by rdp** [comment]
I think you can close this, nice work.
