### ISSUE TITLE
getter/property for booleans that adds a question mark (?)

### ISSUE THREAD

**Issue by esotericpig** [crystal-lang/crystal#8904]
I think it'd be nice to have a getter/property for booleans that adds a question mark (?) to the method name, especially since there isn't an `alias_method` like in Ruby.

Something like this?

```crystal
class Test
  getter? :okay
  property? :cool
end

t = Test.new
t.okay?
t.cool?
t.cool = true
```

Other name ideas:
- `getter_bool & property_bool`
- `booler & boolty`

**Comment by Blacksmoke16** [comment]
This is already a thing.  See [getter?](https://crystal-lang.org/api/Object.html#getter?(*names,&block)-macro) and [property?](https://crystal-lang.org/api/master/Object.html#property?(*names,&block)-macro)

**Comment by asterite** [comment]
You can already do that, the syntax is slightly different and you need to define the default value:

```crystal
class Test
  getter? okay = false
  property? cool = false
end

t = Test.new
t.okay?
t.cool?
t.cool = true
```

**Comment by rdp** [comment]
Can you recommend any changes in the documentation to make this clearer perhaps?

**Comment by esotericpig** [comment]
Oh awesome! Thanks.

I only read about getter/property from [here](https://github.com/crystal-lang/crystal/wiki/Crystal-for-Rubyists), which is also what I found when searching google for "crystal attr_accessor." So if this document is updated, probably good for future people.
