### ISSUE TITLE
Hello i need crsytal developor for paid support

### ISSUE THREAD

**Issue by hhuseyn** [crystal-lang/crystal#8905]
Hello i need crsytal developor for paid support. Now my server have installing crystal language script.
Script source code url  https://github.com/omarroth/invidious
I install this script my server. But now i need how can php command request this script for data.

**Comment by Blacksmoke16** [comment]
This is probably better suited for the [forums](https://forum.crystal-lang.org/).

**Comment by bcardiff** [comment]
Please use the https://forum.crystal-lang.org/ or twitter mentioning http://twitter.com/CrystalLanguage to reach out for interested people.

For a start https://manas.tech/ offers consulting services.
