### ISSUE TITLE
IO.copy return length feature enhancement? (even if an exception is thrown, the length of the write will be returned)

### ISSUE THREAD

**Issue by 636f7374** [crystal-lang/crystal#8913]
# Summary

* Sometimes `IO.copy` needs to return the length, whether or not an exception is triggered.
* But for now, length is not returned after the exception is triggered.
* Sometimes, someone needs this feature. Currently, if you need it, you can implement it yourself.
* (E.g. ProxyServer, ...).

## Feature

* Just for reference (for me).

```crystal
abstract class IO
  class CopyException < Exception
    property count : UInt64?

    def initialize(@message : String? = nil, @cause : Exception? = nil, @count : UInt64? = nil)
    end
  end

  def self.copy(src, dst, cause : Bool) : UInt64
    return copy src, dst unless cause

    buffer = uninitialized UInt8[4096_i32]
    count = 0_u64

    begin
      while (len = src.read(buffer.to_slice).to_i32) > 0_i32
        dst.write buffer.to_slice[0_i32, len]

        count += len
      end
    rescue ex
      CopyException.new message: String.new, cause: ex, count: count
    end

    count
  end
end
```

## Usage

```crystal
...
        length = begin
          IO.copy client, remote, true
        rescue ex : IO::CopyException
          ex.count
        rescue
          nil
        end
...
```

**Comment by straight-shoota** [comment]
The method can either raise *or* return a value. Not both. Encapsulating the copied length in the exception works, but I'm not sure whether that's a great API. However, it might actually be fine to raise a `IO::CopyException` with a length property and cause.

**Comment by 636f7374** [comment]
@straight-shoota :)

**Comment by RX14** [comment]
It's actually impossible in general to know precisely how much data was written to an IO before erroring. `IO#write` is not atomic in crystal, it can fail and have already written half the data. So at the very least this is more general of a problem than `IO.copy`.

**Comment by 636f7374** [comment]
@RX14 Okay, but is there a better solution? (I need to use it on ProxyServer for statistics).

**Comment by RX14** [comment]
There's no better solution I think, since `LibC.write` provides no information on what was written when it returns an error.

**Comment by 636f7374** [comment]
@RX14 You may have misunderstood what I mean, this feature is the same as IO.copy returns UInt64 (even if an exception is thrown, the length is also returned (this feature)).

**Comment by 636f7374** [comment]
@RX14 (even if an exception is thrown, the length of the write will be returned) Are you sure you didn't understand what I mean?

**Comment by 636f7374** [comment]
Forget it, I want to close it. If you need it, you can implement it yourself. It is not different from IO.copy, but it also carries the successfully written count when it throws an exception.

**Comment by RX14** [comment]
@636f7374 I do understand, i'm saying it's not possible.

**Comment by 636f7374** [comment]
@RX14 Okay, thank you.
