### ISSUE TITLE
I want install crystal 0.32.0

### ISSUE THREAD

**Issue by hhuseyn** [crystal-lang/crystal#8932]
I want install crystal 0.32.0. Please help me for commands.

**Comment by straight-shoota** [comment]
Please ask such questions on the forum: https://forum.crystal-lang.org

If you expect an answer, it would be a great help if you would specify where you want to install Crystal 0.32.0. In general you can find our distribution packages at https://github.com/crystal-lang/crystal/releases/tag/0.32.0

**Comment by hhuseyn** [comment]
I want install crystal 03.2.0  ubuntu server. Please send me commonds how install 0.32.0
