### ISSUE TITLE
Unhandled exception in spawn(name: Signal Loop)

### ISSUE THREAD

**Issue by kingsleyh** [crystal-lang/crystal#8936]
When running the specs for this project: 

https://github.com/tbrand/tokoroten/blob/master/spec/tokoroten_spec.cr#L110

The following error is thrown many times. I'm unable to catch it and it seems that Signal Loop is crystal internal fibre which is having an issue.

crystal version: 0.33.0 (this problem is not there in previous crystal versions)
os: macos catalina

```
Unhandled exception in spawn(name: Signal Loop): End of file reached (IO::EOFError)
  from /Users/kings/.ball/install/c-0.33.0/src/io.cr:513:27 in 'read_fully'
  from /Users/kings/.ball/install/c-0.33.0/src/io/byte_format.cr:123:3 in 'decode'
  from /Users/kings/.ball/install/c-0.33.0/src/int.cr:613:5 in 'from_io'
  from /Users/kings/.ball/install/c-0.33.0/src/io.cr:889:5 in 'read_bytes'
  from /Users/kings/.ball/install/c-0.33.0/src/signal.cr:197:17 in '->'
  from /Users/kings/.ball/install/c-0.33.0/src/fiber.cr:255:3 in 'run'
  from /Users/kings/.ball/install/c-0.33.0/src/fiber.cr:92:34 in '->'
```

**Comment by asterite** [comment]
Reduced:

```crystal
msg = "a" * 70000

20.times do
  main_reader, main_writer = IO.pipe
  worker_reader, worker_writer = IO.pipe

  Process.fork do
    worker_reader.gets(msg.size)
    main_writer.print msg
  end

  spawn do
    worker_writer.print msg
  end

  main_reader.gets(msg.size)
end
```

In case anyone wants to debug any further (I won't because I'm not familiar with that part of the codebase).

Also, tokoroten seems to be doing `spawn { loop { ... } }` without an end to those loops, so `kill` isn't correctly implemented and the app will leak fibers.

**Comment by kingsleyh** [comment]
Hi - do you have any idea of the timeline for this bug getting fixed? If it's not going to be in the next release then I will implement a different solution. Or if it's likely to be fixed in the next release I will hold fire for that.

**Comment by asterite** [comment]
Since nobody replied, there's no expected time when this will be fixed.

**Comment by RX14** [comment]
`Process.fork` is likely to be removed before 1.0. Unless this can be reproduced without fork then it might be closed?

We should probably deprecate the method already....

**Comment by kingsleyh** [comment]
Ok thanks - if the future is to remove Process.fork then I will implement an alternative solution for my project

**Comment by kingsleyh** [comment]
In crystal 0.34 this seems to work fine!
