### ISSUE TITLE
Add prime? for integers to stdlib

### ISSUE THREAD

**Issue by jzakiya** [crystal-lang/crystal#8945]
I noticed that there is no ``prime?`` method in https://crystal-lang.org/api/0.33.0/Int.html, so I propose adding it.  This is a necessary function for doing all types of numerical processing algorithms and operations in many different fields of math and science.

The code below is for a highly optimized and deterministic (upto 25+ digits) Miller-Rabin primality test (that is part of my ``primes-utils`` rubygem).

I will submit a PR for it if acceptable.

```
require "big"

module Integer 
  module Prime

    # Returns true if +self+ is a prime number, else returns false.
    def prime?
      primes = {2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47}
      return primes.includes? self if self <= primes.last
      modp47 = 614_889_782_588_491_410.to_big_i      # => primes.product, largest < 2^64
      return false if modp47.gcd(self.to_big_i) != 1 # eliminates 86.2% of all integers
      # wits = [range, [wit_prms]] or nil
      wits = WITNESS_RANGES.find { |range, wits| range > self }
      witnesses = wits && wits[1] || primes
      miller_rabin_test(witnesses)
    end

    # Returns true if +self+ passes Miller-Rabin Test on witnesses +b+
    private def miller_rabin_test(witnesses) # list of witnesses for testing
      neg_one_mod = n = d = self - 1 # these are even as self is always odd
      d >>= d.trailing_zeros_count   # shift out factors of 2 to make d odd
      witnesses.each do |b|          # do M-R test with each witness base
        next if (b % self) == 0      # **skip base if a multiple of input**
        y = powmod(b, d, self)       # y = (b**d) mod self
        s = d
        until s == n || y == 1 || y == neg_one_mod
          y = (y * y) % self         # y = (y**2) mod self
          s <<= 1
        end
        return false unless y == neg_one_mod || s.odd?
      end
      true
    end
    
    # Best known deterministic witnesses for given range and set of bases
    # https://miller-rabin.appspot.com/
    # https://en.wikipedia.org/wiki/Miller%E2%80%93Rabin_primality_test
    private WITNESS_RANGES = {
      341_531 => {9345883071009581737},
      1_050_535_501 => {336781006125, 9639812373923155},
      350_269_456_337 => {4230279247111683200, 14694767155120705706, 16641139526367750375},
      55_245_642_489_451 => {2, 141889084524735, 1199124725622454117, 11096072698276303650},
      7_999_252_175_582_851 => {2, 4130806001517, 149795463772692060, 186635894390467037,
                                3967304179347715805},
      585_226_005_592_931_977 => {2, 123635709730000, 9233062284813009, 43835965440333360,
                                  761179012939631437, 1263739024124850375},
      18_446_744_073_709_551_615 => {2, 325, 9375, 28178, 450775, 9780504, 1795265022},
      "318665857834031151167461".to_big_i  => {2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37},
      "3317044064679887385961981".to_big_i => {2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41}
    }

    # Compute b**e mod m
    private def powmod(b, e, m)
      m = m.to_big_i
      r = 1.to_big_i; b = b.to_big_i % m
      while e > 0
        r = (r * b) % m if e.odd?
        b = (b * b) % m
        e >>= 1
      end
      r
    end
  end
end

struct Int; include Integer::Prime end
```

I have verified it against known primes upto ~300,000 digits so far.

The API for this version doesn't match Ruby's for negative integers.
Ruby returns the result of the absolute value n.
This returns ``false`` for negative integers (which is mathematically correct, all primes are positive).
Can add to first line inside ``prime?`` an ``ArgumentError`` if want to punish wayward users.
``raise ArgumentError.new "Input must be non-negative integer" if self < 0``

```
2.7.0 :253 > 0.prime?
 => false 
2.7.0 :254 > 1.prime?
 => false 
2.7.0 :255 > -1.prime?
 => false 
2.7.0 :256 > -2.prime?
 => true 
2.7.0 :257 > -3.prime?
 => true 
2.7.0 :258 > -4.prime?
 => false 
2.7.0 :259 > -5.prime?
 => true 
```

**Comment by wontruefree** [comment]
There has been some history to this.  I would check out this issue.
https://github.com/crystal-lang/crystal/issues/8845

**Comment by jzakiya** [comment]
Ruby's ``Primes`` class, as implemented in its ``primes.rb`` file is very inefficient mathematically, and is slow,, and its API isn't the most natural/useful, from a users perspective. This is why I wrote my rubgems ``primes-utils``, to have a reasonable chance doing Project Euler problems - https://projecteuler.net/

I've already ported the whole gem to Crystal, but things like a ``prime?`` method should just be in the stdlib because it's so ubiquitous in use.  I image it's used more frequently than ``gcd``, ``lcm`` and a host of other methods in stdlib, in real code.

**Comment by wontruefree** [comment]
I would not disagree with you but it seems like the core team has some thoughts on it.  And they have decided it would be better at a shard.

**Comment by jzakiya** [comment]
I understand the thinking in general, but disagree for this function in specific.
A user shouldn't have to search for and load a shard for such a universally used Integer function.

I can shard up my ``primes-utils`` code to provide this, and a host of other functionality, but I was waiting for Crystal (as with Ruby) to have its mult-threading become mature so I can employ some parallel processing techniques where useful.

Maybe since I'm locked down my coronavirus I'll take the time to get an initial version released.

But I would like the dev team to make an exception for just this function, as it would make my code base so much easier to write, maintain, and share.

**Comment by asterite** [comment]
I don't think we'll include this in the standard library.

The reasons:
1. it seems to require `BigInt` no matter what. I think all `Int` methods should work without requiring `BigInt`
2. knowing whether something is prime or not is probably useful in very specific domains. My guess is that in such domains you also need more math stuff. For example stuff that pypy, R or Julia would provide. In that case, just having `prime?` in the stdlib won't be enough because you'll still require other shards. And since that's the case, why not put that function in a shard?
3. I have no knowledge of how this works. This means that if you stop contributing to Crystal and we have to maintain this, we probably won't be able to do so.

**Comment by jzakiya** [comment]
OK, I understand from your viewpoint.

Now that it seems I'll have more time on my hands to use, I'll get around to sharding my code up.
