### ISSUE TITLE
Time::Span is missing the total_microseconds feature

### ISSUE THREAD

**Issue by 636f7374** [crystal-lang/crystal#8965]
# Summary

* `Time::Span` is missing the total_microseconds feature.

## Problem

* Code

```crystal
elapsed = Time.monotonic
(Time.monotonic - elapsed).total_microseconds
```

* Warning

```text
undefined method 'total_microseconds' for Time::Span
Did you mean 'total_milliseconds'?
```

## Solution

```crystal
struct Time::Span
  # Converts to a number of microseconds.
  def total_microseconds : Float64
    total_nanoseconds / NANOSECONDS_PER_MICROSECOND
  end
end
```

## References

* [Crystal | Time::Span](https://crystal-lang.org/api/0.33.0/Time/Span.html#total_nanoseconds:Float64-instance-method)
* [Crystal | src/time/span.cr](https://github.com/crystal-lang/crystal/blob/612825a53c831ce7d17368c8211342b199ca02ff/src/time/span.cr#L237)

**Comment by straight-shoota** [comment]
Sure, wouldn't hurt to complete the API. `#total_milliseconds` and `#total_nanoseconds` already exist, as does `#microseconds`.

**Comment by 636f7374** [comment]
@straight-shoota Okay :)

**Comment by vlazar** [comment]
Here we go :) #8966
