### ISSUE TITLE
[RFC] Add `?!` as a name suffix

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#8979]
# Context

Crystal, like Ruby, allows names to end with `?` and `!`.
Why? See, right there, I just used an `?`. We humans use them all the time.
Ruby using them makes Ruby more human. After all, Ruby is a programmer's best friend.
And we'd like Crystal to be as human and friendly as Ruby.

Be we can go a step forward.

# Enter `?!`

The `?!` symbol combination is used all the time too!

We can call it the "WTF" name suffix, but I'm open for suggestions. For example
it could be called [Interrobang](https://en.wikipedia.org/wiki/Interrobang
), and we could even allow using `‽` instead of the more verbose `?!`.

However, compared to `?` and `!`, its meaning is a bit more vague.
So here are some situations in which we can use it:

## Not understanding a piece of code

Sometimes when code reviewing we stumble upon a method we don't fully understand.
We could leave a `TODO: I don't know what this is doing` but that's too verbose.
Instead, simply add `?!` to the method name and everywhere where it's called.

```crystal
def sum?!(n,t)
  n*(1..t/n).to_a.sum
end

sum?!(...)
```

This informs everyone reading the code that it's not clear why we are doing what
we are doing.

## Being angry about code

Other times we stumble upon code we dislike. We think to ourselves "Why the heck
are we doing this?!" or "Why the heck do we need to do this?!". The `?!` suffix can be used in that situation:

```crystal
Model.fetch_from_soap_api?!
```

## Not being sure why we are doing something.

This is similar to "Not understanding a piece of code", but not quite. The former
means we are reading someone else's code and we don't understand it, or maybe our
past self wrote it and we don't understand it anymore.

But "Not being sure why we are doing something" refers to us not understanding why
we are writing the code we write, right now, at the present moment.

One such example is using `not_nil!` because a variable can be `nil` and we don't
understand why. Using `not_nil!` we are making a strong assertion, we say
"Hey, compiler, I know this is not nil. I know better than you". But sometimes
we use it without understanding why. In that case, we can use `not_nil?!`
(we will have to introduce it the version following the introduction of `?!`, or
we can use `compare_versions`, I have no preference). The implementation is really
simple:

```crystal
class Object
  # Similar to `not_nil!` but to be used in cases where one doesn't
  # quite know why they are calling `not_nil!`.
  def not_nil?!
    not_nil!
  end
end
```

## Other use cases?

I'm happy to hear other use cases you have in mind!

I think this will be a radical change in the language.
That's why I think this should be seriously considered for 1.0.

Thoughts?!

**Comment by jhass** [comment]
I feel like this limiting my freedom of expression a bit, why stop here? Let's allow arbitrary series of `?`, `!` and `¿` so I can `be_really_confused!?!¿?`, really `angry!!!!` etc.

In fact why only at the end? In German we sometimes like to be really `laut!!!!111einseinself` :)

**Comment by Sija** [comment]
> In fact why only at the end? In German we sometimes like to be really `laut!!!!111einseinself` :)

In Spanish (and some others) you also use inverted question mark (¿) and exclamation mark (¡) punctuation, used to begin interrogative and exclamatory sentences (or clauses), respectively. I'd imagine having `World#¡hola!` method ;)

**Comment by refi64** [comment]
This is an absolutely ridiculous proposal.

@jhass is right, it's far too restrictive. This should at least allow for asterisks, so a `f***this!!` method would be writable.
