### ISSUE TITLE
[RFC] Replacing introsort with a more efficient sort

### ISSUE THREAD

**Issue by Afront** [crystal-lang/crystal#8985]
# Context

Crystal uses introsort to sort its slices and arrays. However, introsort is an inefficient algorithm whose best-case performance is just O(n log n). I believe that now is the time to change the sorting algorithm while Crystal is still a young language, but what algorithm could possibly have a better best-case performance than introsort? Python's answer to this is Timsort. However, I believe we can use a sorting algorithm that is better than introsort and even Timsort. 

# Enter Crystalsort.

Just like Timsort, this sorting algorithm is a hybrid algorithm that mainly uses mergesort. Instead of using insertion sort, it uses a similarly efficient algorithm called storcht. Just like insertion sort, it has the best-case performance of O(n) and the worst-case space complexity of O(n). The biggest advantage to this sort as well is that it is very minimal. Here is a snippet of the entire sorting algorithm based on the pseudocode for mergesort on the most credible source on the Internet beside StackOverflow, Wikipedia.

```Crystal
  def self.sort(array : Array(T))
    return Storcht.sort(array) if array.size <= LIMIT
    left = [] of T
    right = [] of T

    array.each.with_index do |x, i|
      if i < (array.size)/2
        left << x
      else
        right << x
      end
    end

    merge(sort(left), sort(right))
  end
```

# Conclusion

[Here]((https://github.com/Afront/bogomerge)) is a short implementation for this sorting algorithm called Bogomerge. In this implementation, `Random.rand(3)` is used for the `LIMIT` constant to keep the algorithm's worst-case performance and  worst-case space complexity absolutely constant using randomness.

I believe that once this change has been implemented, we can go straight to v3.3 from v.0.33.
I'm curious to know your thoughts on this.

**Comment by asterite** [comment]
I liked this! :-)
