### ISSUE TITLE
New Log module documentation, IOBackend Context  issues

### ISSUE THREAD

**Issue by z64** [crystal-lang/crystal#8994]
1. `@type` in `Crystal.datum` macros emits `Crystal`. This causes some wrongly generated documentation. Some examples:

"Creates a Crystal that wraps the given Raw."
https://crystal-lang.org/api/master/Log/Context.html#new(raw:Type)-class-method

"All possible Crystal types."
https://crystal-lang.org/api/master/Log/Context/Type.html

---

2. Logging with `IOBackend` crashes if the "top level" `Context::Type` is not `Hash` or `Array`, because of [this line](https://github.com/crystal-lang/crystal/blob/ab8b04449162052a4e6375ba3c9b86766a59c6b9/src/log/io_backend.cr#L38). 

This needs to be documented for `IOBackend`, or the default formatter for `IOBackend` needs to be resilient to other `Context` types.

```cr
require "log"

backend = Log::IOBackend.new
Log.builder.bind("*", :info, backend)
Log.context = Log::Context.new(1337)
Log.for("").info { "test" }
```
```
I, [2020-04-02T22:50:05.555750000Z #1290]    INFO -- crystal-run-crash.tmp:: testUnhandled exception: Expected Array or Hash for #size, not Int32 (Exception)
```

Perhaps `datum` should add `#size?`, and then the formatter will fall back to `inspect`?

(I didn't follow the design discussions of `datum`, etc. closely, nor do I have any stake/opinion in which solution is picked.)

**Comment by bcardiff** [comment]
I would expect `Log.context=` to fail if the Context is not a hash like. Since that is also assumed in `extend_fiber_context`.

Regarding the documentation issues, I extracted that to #9099

**Comment by z64** [comment]
It looks like these items have been resolved now. Thank you! :heart:
