### ISSUE TITLE
Adding a universal comment for all programming languages

### ISSUE THREAD

**Issue by xss2bruh** [crystal-lang/crystal#8996]
I am suggesting this to more developers, maybe someone will come with the perfect solution and everyone will add it in their programming language. _Thanks_

**Comment by straight-shoota** [comment]
Thanks for sharing this idea. 

We won't keep this as an open issue in the issue tracker because it's not actionable. In case you want to start a conversion about this, please go to the forums at https://forum.crystal-lang.org/
