### ISSUE TITLE
Unexpected equality behavior between some types

### ISSUE THREAD

**Issue by vegai** [crystal-lang/crystal#9013]
```
integer=1
stringeter="1"
floateger=1.0

puts integer == stringeter # false
puts integer == floateger # true 
puts stringeter == floateger # false

#puts integer >= stringeter
#puts integer >= floateger
#puts stringeter >= floateger
```

Also here https://play.crystal-lang.org/#/r/8udm

On Crystal 0.33.0. The last three puts lines (when uncommented) are compilation errors as one might expect. The first three puts lines are not. Should they be? I think in a statically and strongly typed language, they should.

**Comment by RX14** [comment]
I'm sure there's been discussion of this before but github's issue search is useless :(

**Comment by straight-shoota** [comment]
I'm not sure if there's a dedicated thread about this. But #5829 for example touches this and should explain why equality is defined between any two types. It doesn't necessarily need to be like that, both ways could be taken. But we've come so far with the current behaviour and it's unlikely to change such a fundamental concept at this point.

**Comment by straight-shoota** [comment]
Btw. some other methods enjoy the same type flexibility: `===`, `!=`, `=~ `, `!~` (see #5829) and some collection methods (see #988, #1764). Hash lookup methods also don't have type restrictions, but that will probably change (#8893). There's also an open discussion about making `<=>` generally applicable (#8953).

**Comment by vegai** [comment]
Ok, thanks for the explanation.

**Comment by asterite** [comment]
How do you implement [1, "a"].includes?("a") if you can't freely compare any two types?

Maybe we can introduce another operator to compare types in a non type safe way. Then the general collection methods can use it, but when using == it will be type safe. Same goes for <=> and possibly others.

**Comment by asterite** [comment]
I wouldn't discard this possibility.

**Comment by RX14** [comment]
That seems worth a try, though IDK if it's worth changing the language this late

**Comment by asterite** [comment]
For the type-safety, I think it might be worth it.

**Comment by vegai** [comment]
I've been thinking about this for a longer time, but the looming 1.0 triggered me to write this issue in a bit of a hurry. I don't think it'll be done at all if it's not done before 1.0 because it's probably a rather big change for existing code.

FWIW, my experience is that enabling these comparisons causes actual bugs in a lot of existing financial code. Of course, Crystal doesn't fortunately go full crazy and have `1=="1" => true` like some not-to-be-named languages do, but `1==1.0 => true` seems like a risky one as well due to well-known properties of floats that nobody knows about :)

```
puts 6.0-0.9-0.1 == 5 # true
puts 6.0-0.8-0.1-0.1 == 5 # false
```

**Comment by girng** [comment]
To answer your question (and give my opinion) I think they should. The compiler is out great friend, more bugs it can catch, the better the developer is in the long run.

**Comment by jhass** [comment]
I'm confused what the action item or even discussion topic of this issue is at this point. Could somebody please clarify by updating the issue description to something sane? Or better yet close this off and write a proper proposal for whatever it is?
