### ISSUE TITLE
Parsing errors with no spaces after colon

### ISSUE THREAD

**Issue by waj** [crystal-lang/crystal#9027]
The following expressions fail to parse when no space is added right after the colon:

```crystal
bar(foo:"a")
bar(foo:a)
{foo:"a"}
{foo:'a'}
{foo:a}
```

**Comment by oprypin** [comment]
Maybe these shouldn't parse, just give a clearer error.
I'm guessing it's looking at this as <code>bar(foo</code><code>:a)</code>
So it has peeked far enough to know that this is definitely an arg name but then starts parsing the following as a symbol `:a`, and sure enough, after an arg name there must be a `:`, not a symbol.

**Comment by oprypin** [comment]
Relevant code:

https://github.com/crystal-lang/crystal/blob/7e2e84042a393223660a216fbc5d0d5cd6bb80a5/src/compiler/crystal/syntax/parser.cr#L1295 ^ checks that the next **character** is ":"
but the lexer has already decided that the next **token** is a symbol literal
so then there's an error `expecting token ':', not 'a'` here:
https://github.com/crystal-lang/crystal/blob/7e2e84042a393223660a216fbc5d0d5cd6bb80a5/src/compiler/crystal/syntax/parser.cr#L4476

**Comment by oprypin** [comment]
Don't know how to fix this correctly though, I'm not taking this :sweat_smile:
