### ISSUE TITLE
BUG: if does not downcast from (String|Nil)

### ISSUE THREAD

**Issue by alexmaco** [crystal-lang/crystal#9040]
Crystal version: 0.33.0 (playground) and 0.34.0 (ubuntu linux, installed with apt from crystal-lang repositories)

Code:
```crystal
require "option_parser"
file = nil

OptionParser.parse do |parser|
  parser.on("-f", "Use file") { |f| file = "abcd" }
end

puts "BEFORE " + typeof(file).to_s

if file.is_a?(Nil)
  puts "THEN " + typeof(file).to_s
else
  puts "ELSE " + typeof(file).to_s
end
```

Expected output:
```
BEFORE (String | Nil)
THEN Nil
```

Actual output:
```
BEFORE (String | Nil)
THEN (String | Nil)
```
Edit: When invoked with `-f`, the type on the else branch is the same (`(String | Nil)` instead of `String`)
Edit2: The same issue occurs when using `case`/`when Nil`/when `String` (the type of `file` is a union on both branches)

Reproduction: I did not find a smaller case with inline code. Using other methods downcasting happens correctly.

Possibly related; #8655 or #8864 , but i don't know if it's the same issue

**Comment by asterite** [comment]
file is captured in a closure block. The compiler doesn't know when the block is invoked, or if at all.

You can solve this by assigning file to another variable and then check with if.

**Comment by straight-shoota** [comment]
See https://crystal-lang.org/reference/syntax_and_semantics/closures.html for an explanation of closured variable behaviour.
