### ISSUE TITLE
Crystal lacks IDEA tool support

### ISSUE THREAD

**Issue by isled** [crystal-lang/crystal#9042]
Crystal lacks IDEA tool support, which makes crystal development very difficult, the existing tool can only be called code highlighting, official can not come up with a perfect IDEA tool, so that new people do not have to look around for code, crystal is a good language, which is lack ingested by a good IDEA support。 Thanks! I hope IDEA plugin will be introduced soon

**Comment by asterite** [comment]
Hi! There's been a lot of discussions about IDE support for Crystal. In short: it's very hard or impossible to support something like that. And this repository is about the language itself, and it's already a ton of work to do that. Maybe ask in the forums and the community can work on that. Thank you!

**Comment by j8r** [comment]
You can post an issue in https://github.com/crystal-community/crystal-libraries-needed/issues.

**Comment by straight-shoota** [comment]
@j8r I don't think this is about a library...

**Comment by asterite** [comment]
Just because I feel like saying this, my username in reddit is the-asterite

**Comment by j8r** [comment]
@straight-shoota [scry](https://github.com/crystal-lang-tools/scry) for instance is a library. Any IDE supporting LSP can benefit of completion, docs and other features.
