### ISSUE TITLE
Remove Random, Crypto, and Digest namespaces, or add a few more namespaces.

### ISSUE THREAD

**Issue by didactic-drunk** [crystal-lang/crystal#9077]
Do the justfications used in #8886 regarding the `Compress` namespace apply elsewhere?  Removing their namespaces would be consistent with the non use of a `Compress` namespace.  

The following would end up in the root namespace:
```
Addler32
CRC32
MD5
SHA1
PCG
ISAAC
RandomSecure
Bcrypt
Blowfish
Subtle?
```

An argument was made that typing `Compress` was too inconvenient.  If `MD5`,`SHA1` or other namespaced classes are used more often than `Deflate` shouldn't they be in the root namespace?

Thanks to @straight-shoota [for making this clear](https://github.com/crystal-lang/crystal/pull/8886#issuecomment-596593350).

**Comment by j8r** [comment]
This issue can probably be closed, as the decision is to use the `Compress` namespace.
