### ISSUE TITLE
Crystal docs dark theme

### ISSUE THREAD

**Issue by j8r** [crystal-lang/crystal#9084]
Some developers likes dark theme - more gentle on the eyes when codding at night :smile: 

[The CSS media prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) can be used for auto-detection o the light/dark theme user preference

> The prefers-color-scheme CSS media feature is used to detect if the user has requested the system use a light or dark color theme.

Other similar tools supporting it:
- https://devdocs.io
- https://doc.rust-lang.org/std/index.html

**Comment by straight-shoota** [comment]
Sure, sounds good enough to me.

But I would actually hold off on such non-essential features to the doc generator until we do a bigger refactor of the internal implementation.

**Comment by Blacksmoke16** [comment]
[Custom Properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*) could also be a cool future addition.  It would abstract the coloring of things to a single CSS file that could be overridden to allow for custom styling.

**Comment by oprypin** [comment]
https://github.com/oprypin/mkdocstrings-crystal is an external doc generator that exposes theme customizations, including dark mode via https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-scheme

**Comment by willhbr** [comment]
I was just about to file a duplicate of this. Would a PR adding a dark mode to the CSS be accepted?

I spent a few minutes tinkering with the styles to see what this could look like:

<img width="1347" alt="image" src="https://user-images.githubusercontent.com/710254/123794612-5e5bef00-d926-11eb-9d5c-e92de90510e9.png">

This would obviously require a bit more thought, but I think this direction would save some people's eyes at night.

**Comment by chances** [comment]
@willhbr Are your CSS sources available anywhere?

**Comment by willhbr** [comment]
I made that screenshot by tinkering directly in the browser, and didn't save them.
