### ISSUE TITLE
[RFC] Process.times on Windows

### ISSUE THREAD

**Issue by kubo** [crystal-lang/crystal#9131]
Process.times is not implemented on Windows now. This is a proposal how to implement it.

CPU usage consumed by a process can be got by [GetProcessTimes][]. It is easy to fill [Process::Tms][]#utime and #stime. Just calling `GetProcessTimes(GetCurrentProcess(), ....)`. I want to hear opinions about #cutime and #cstime.

The #cutime and #cstime values come from `getrusage()` with `RUSAGE_CHILDREN` on Unix. They include the resources used by not only direct children but also further descendants on [Linux][]. [POSIX][] just says "children of the current process" and doesn't notice whether they include the resources used by further descendants or not. The manpage of [FreeBSD][] and [macOS][] is same with that of POSIX. Does the word "children" in English include descendants in this context?

By the way I came up with two options.

1. Doesn't support #cutime and #cstime. They are zeros always.
2. Support resources about direct children, not including further descendants.
   Call `GetProcessTimes` just before [this line] and add up to a class variable of Crystal::System::Process.

I prefer the former because most users, I guess, won't care about #cutime and #cstime.
In addition the latter is similar to but not same with that on Linux.

[GetProcessTimes]: https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getprocesstimes
[Process::Tms]: https://crystal-lang.org/api/0.34.0/Process/Tms.html
[Linux]: http://man7.org/linux/man-pages/man2/getrusage.2.html
[POSIX]: https://pubs.opengroup.org/onlinepubs/9699919799/functions/getrusage.html
[macOS]: https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/getrusage.2.html
[FreeBSD]: https://www.freebsd.org/cgi/man.cgi?query=getrusage&apropos=0&sektion=2&format=html
[this line]: https://github.com/crystal-lang/crystal/blob/456b4ebdbed36380c30f858d27b638f098020b5f/src/crystal/system/win32/process.cr#L15

**Comment by kubo** [comment]
> ... most users, I guess, won't care about #cutime and #cstime.

Total CPU time printed by [BenchMark](https://crystal-lang.org/api/0.34.0/Benchmark.html) is sum of [utime, stime, cutime and cstime](https://github.com/crystal-lang/crystal/blob/4401e90f001c975838b6708cc70868f18824d1e5/src/benchmark/bm.cr#L28-L30). Is it worth to support cutime and cstime of direct children?

**Comment by oprypin** [comment]
Maybe none of this is worth supporting.

**Comment by kubo** [comment]
> Maybe none of this is worth supporting.

Does it mean "both cutime and cstime are not worth to supporting"? I'm not a native English speaker.

Both [ruby](https://github.com/ruby/ruby/blob/v2_7_1/win32/win32.c#L5926-L5943) and [python](https://github.com/python/cpython/blob/v3.8.2/Modules/posixmodule.c#L8276-L8293) set zeros to cutime and cstime on Windows. I'm leaning toward to same behaviour with ruby and python.

**Comment by asterite** [comment]
Let's do the same as Ruby and Python.

**Comment by oprypin** [comment]
Oh wow, I had no idea that Python supported this!
