### ISSUE TITLE
Compiler bug: Error renaming file - reproducible via Docker

### ISSUE THREAD

**Issue by KCErb** [crystal-lang/crystal#9168]
Hi again all, so glad to be back working with Crystal! I bumped into this bug when trying to run a `lucky` command in a Docker container just after it starts. My hunch is that the container is running its `CMD` (`lucky watch`) when the `exec` call comes into `lucky db.create`. Somehow this generates the following:

```
while requiring "./src/app" (Exception)
  from ??? x 10
Caused by: while requiring "./shards" (Exception)
  from ??? x 13
Caused by: while requiring "avram" (Exception)
  from ??? x 16
Caused by: while requiring "lucky_cli" (Exception)
  from ??? x 19
Caused by: while requiring "./lucky_cli/**" (Exception)
  from ??? x 22
Caused by: Error renaming file: '/root/.cache/crystal/foo_bar-lib-teeplate-src-lib-file_tree-macros-directory.cr/_main.o.tmp' -> '/root/.cache/crystal/foo_bar-lib-teeplate-src-lib-file_tree-macros-directory.cr/_main.o': No such file or directory (File::NotFoundError)
  from ??? x 37
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

You can reproduce this by:

1. running `docker build .` next to this `Dockerfile`
```
FROM luckyhasuradocker/lucky-crystal:l0.21.0c0.34.0
RUN lucky init.custom foo_bar --api
WORKDIR /foo_bar
RUN shards install
CMD ["lucky", "watch"]
```
2. And then spinning up a container based on that image followed immediately by `docker exec` at the container. So if the container hash were 5d7a280d9dcb then I would run

`docker run -d --name lucky_crystal_test 5d7a280d9dcb && docker exec lucky_crystal_test sh -c "lucky db.create"`

If the bottom of the error didn't say 'please open an issue' I would be talking about this to Lucky people instead of you folks :)

**Comment by jhass** [comment]
Yeah, I think this is the badly titled #7868

**Comment by KCErb** [comment]
Yup, that looks right to me. I'll close this as a duplicate. We don't need a Docker environment to run the crystal compiler in parallel with itself :)
