### ISSUE TITLE
Error including module in some generic classes

### ISSUE THREAD

**Issue by waj** [crystal-lang/crystal#9173]
I'm still unsure about the reason of this error, so the title is quite vague. This doesn't happen just with any generic class and couldn't find the exact reason yet.

```crystal
module Foo
end

class Array(T)
  include Foo
end

puts [1].as(Foo)
```

Error:
```
In /usr/local/Cellar/crystal/0.34.0/src/array.cr:1878:24

 1878 | join ", ", io, &.inspect(io)
                         ^------
Error: undefined method 'inspect' for T (compile-time type is (T | U))
```

**Comment by waj** [comment]
Apparently this is happening since Crystal 0.19.0

**Comment by HertzDevil** [comment]
The unbound `T | U` comes from here:

https://github.com/crystal-lang/crystal/blob/1db5d45650e43adbc40c16e0d25cf0be0856a418/src/iterator.cr#L813-L817

Removing this iterator type makes the code compile.

**Comment by HertzDevil** [comment]
It seems `T | U` (and generic instances that use it as an argument) is not considered an unbound type so it leaks into the list of subtypes during virtual method lookup.
