### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by TorchedSammy** [crystal-lang/crystal#9181]
This might be really trivial or small but I just want to know this this right here https://github.com/crystal-lang/crystal/blob/4401e90f001c975838b6708cc70868f18824d1e5/src/string.cr#L3703 is a typo or not
"ond" read it closely.

**Comment by TorchedSammy** [comment]
nevermind im a stupid person

**Comment by RX14** [comment]
I think this is a typo... should be "and"
