### ISSUE TITLE
IO overloads for `String#*case` methods

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#9215]
Related to #8923 but for the various `*case` methods including:
* underscore
* downcase
* upcase
* capitalize
* camelcase
* titleize #9204?

**Comment by Blacksmoke16** [comment]
I looked into this a bit.  It'll be pretty easy as all the implementations are using `String.build`, so just replace that with an `io` argument and move it to another that just passes the builder io to the current implementation.

The main question will be what where to put the argument, given they all have a `Unicode::CaseOptions` argument.  Could either make it the second argument, or a named only argument.  Also relates to #5916.

**Comment by straight-shoota** [comment]
Yes, first argument please 👍
