### ISSUE TITLE
Key name restriction inconsistency between keyword arguments and named tuple keys

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#9221]
We intend lossless conversion between keyword arguments and named tuples, otherwise we would not have the double splat (`**args`) syntax.

Yet while `{Foo: 1}` is a valid named tuple, `NamedTuple.new(Foo: 1)` is not a valid call.

We should resolve this either by disallowing the first case or allowing the second case. I don't have a strong preference either way.

**Comment by straight-shoota** [comment]
For reference: This came up in https://forum.crystal-lang.org/t/better-way-to-fetch-data-from-db-and-store-in-namedtuple/2059/5

**Comment by asterite** [comment]
Seems like a parser issue. This should be fixed, yeah.
