### ISSUE TITLE
TypeNode with generic_args as false doesn't omit populated types

### ISSUE THREAD

**Issue by icy-arctic-fox** [crystal-lang/crystal#9223]
Related to #8483 

Not sure if this is intentional or not, but when using `@type` in a macro method, the resolved type parameters still get included when `generic_args` is set to false.

```crystal
class Foo(T)
  getter foo : T

  def initialize(@foo : T)
  end

  def do_something
    puts {{@type.name(generic_args: false).stringify}}
  end
end

Foo.new(42).do_something

# Produces:
# Foo(Int32)
# instead of:
# Foo
```

Crystal v0.34

**Comment by Blacksmoke16** [comment]
Seems to be because `@type` types the generic, so it's of a different internal type than if you just did `{{Foo.name(generic_args: false)}}` outside of it.

I'll take a look.
