### ISSUE TITLE
Should `XML::Builder#cdata` escape nested `]]>`

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#9228]
Currently `XML::Builder#cdata` happily encodes `]]>` within the provided string.

https://play.crystal-lang.org/#/r/90ev

```cr
require "xml"
 
string = XML.build(indent: "  ") do |xml|
  xml.element("data") { xml.cdata "FOO]]>BAR" }
end
 
string # => <data><![CDATA[FOO]]>BAR]]></data>
```

This ultimately causes it to generate invalid XML.

The question is, should it internally handle escaping the end sequence, or leave that up to the user to handle?

**Comment by jhass** [comment]
I'd say it clearly should.
