### ISSUE TITLE
Exhaustive case demands accounting for an abstract base class

### ISSUE THREAD

**Issue by oprypin** [crystal-lang/crystal#9235]
```crystal
abstract class A
end

class B < A
end

def f
  B.new.as(A)
end

case f
when B
end
```
```
Error: case is not exhaustive.

Missing types:
 - A
```

Real failures here: [[1]](https://github.com/oprypin/crystal-chipmunk/blob/1fbf0a10365ec9751d01dc0dc88e2abcee0f6994/src/chipmunk/debug_draw.cr#L94) [[2]](https://github.com/oprypin/crystal-chipmunk/blob/1fbf0a10365ec9751d01dc0dc88e2abcee0f6994/src/chipmunk/debug_draw.cr#L115)

My code definitely has no missing cases, it is taking into account every single subclass. The type *cannot be* the abstract class.

I think this is an important situation where exhaustive case could actually be helpful but instead it is only showing you the wrong thing. If I were to add the suggested "missing" case, the code would definitely be worse off from it, and actually, adding the base class as a case would completely silence the exhaustive case checking

**Comment by asterite** [comment]
I think the error message is misleading. It should say that exhaustiveness check can't be proved for an abstract class. The reason is that anyone could extend the type. See my proposal for the Sealed annotation (I'm on mobile so I can't link it). Unfortunately the usefulness of Sealed doesn't seem to be clear, so we definitely need more examples to prove that it's needed (I think it's needed). What's your case?

**Comment by oprypin** [comment]
Well, what *is* my case. See the linked files above (also [docs show the hierarchy nicely](https://oprypin.github.io/crystal-chipmunk/CP/Shape.html)). The tool needs to take into account every single subclass. Also yes, the abstract base class as in the library is not meant to be subclassed, instead it's mostly informational, the set of subclasses is exhaustive and no more are possible as it's coming from a C library. So even if this was subclassed, that subtype could never actually appear here.

**Comment by oprypin** [comment]
I think Sealed would be nice. Also the compiler should detect exhaustiveness as if the abstract class was sealed and show you a suggestion (while still erroring) in this situation that you could resolve this by marking your class sealed

**Comment by asterite** [comment]
Yes. Another example is geojson. Probably all types are under a hierarchy, yet it's not supposed to be extended. But without Sealed there's no way you can express it. Well, you can avoid using a hierarchy and use a big union type. But that's not always wanted.

**Comment by asterite** [comment]
Duplicate of #9116

**Comment by RX14** [comment]
All the subclasses are known at compile-time, why not just cover the `case` if all subclasses which actually exist are covered? Then, if some code breaks when you add another subclass, you know that class is "natually sealed".

The error message of "the new class you just added isnt covered in this library code" is clear enough.

**Comment by asterite** [comment]
The problem is using case over a type without knowing this. You expect people to extend your type but they can't because you used a case somewhere. There's a good reason this feature exists in many other languages.

**Comment by RX14** [comment]
@asterite well they'll learn soon enough
