### ISSUE TITLE
Indexing Arrays problems using BigInt array values.

### ISSUE THREAD

**Issue by jzakiya** [crystal-lang/crystal#9261]
The following code will run:
```
def hamming(limit)
  h = Array(Int32).new
  h[0] = 1
  x2, x3, x5 = 2, 3, 5
  i, j, k = 0, 0, 0
  (1..limit).each do |n|
    h[n] = (x3 < x5 ? (x2 < x3 ? x2 : x3) : (x2 < x5 ? x2 : x5))
    x2 = 2 * h[i += 1] if x2 == h[n]
    x3 = 3 * h[j += 1] if x3 == h[n]
    x5 = 5 * h[k += 1] if x5 == h[n]
  end
  h[limit - 1]
end
```
But when I tried to do this for ``BigInt``s the compiler throws ``BigInts indexing errors``.

```
def hamming(limit)
  h = Array(BigInt).new
  h[0] = 1.to_big_i
  x2, x3, x5 = 2.to_big_i, 3.to_big_i, 5.to_big_i
  i, j, k = 0, 0, 0
  (1..limit).each do |n|
    h[n] = (x3 < x5 ? (x2 < x3 ? x2 : x3) : (x2 < x5 ? x2 : x5))
    x2 = 2 * h[i += 1] if x2 == h[n]
    x3 = 3 * h[j += 1] if x3 == h[n]
    x5 = 5 * h[k += 1] if x5 == h[n]
  end
  h[limit - 1]
end
```

The only way I could make it compile and run is by doing this.

```
def hamming(limit)
  h = Array(BigInt).new
  h << 1.to_big_i
  x2, x3, x5 = 2.to_big_i, 3.to_big_i, 5.to_big_i
  i, j, k = 0, 0, 0
  (1..limit).each do |n|
    h << (x3 < x5 ? (x2 < x3 ? x2 : x3) : (x2 < x5 ? x2 : x5))
    x2 = 2 * h[i += 1] if x2 == h[n]
    x3 = 3 * h[j += 1] if x3 == h[n]
    x5 = 5 * h[k += 1] if x5 == h[n]
  end
  h[limit - 1]
end
```

I tried multiple ways to initialize the ``Array``, but none worked when I did something like this:  ``Array(BigInt).new(limit)``.  It won't let me assign a ``BigInt`` value at an explicit array index. I can/have done this with all the other ``U|Ints``. Why the restriction? I consider this a bug.

**Comment by asterite** [comment]
> The following code will run

The first snippet doesn't run, it already throws an index error.

When you initialize an array with zero elements, doing `array[0] = 1` will fail because you are trying to **replace** a value outside the bounds of the array. If you want to insert a value you need to use `push` or `<<`.

In Ruby you can assign a value at any position and what Ruby will do is it will fill the intermediate values with `nil`.

I consider this a really bad thing in Ruby. In Python for example if you do the same you get an index error. In any language other than Ruby you will get an index error.

Can you also show what line is failing, or try to reduce the problem? Is is this?

```crystal
a = [] of Int32
a[0] = 1
```

I don't think this is related to BigInt or not.

**Comment by jzakiya** [comment]
These two initializations produce the same error:

```
def hamming(limit)
  #h = Array(BigInt).new
  h = Array.new(limit, 1.to_big_i) # or h = Array.new(limit.to_big_i, 1.to_big_i)
  h[0] = 1.to_big_i
  x2, x3, x5 = 2.to_big_i, 3.to_big_i, 5.to_big_i
  i, j, k = 0, 0, 0
  (1..limit).each do |n|
    h = Math.min(x2, Math.min(x3, x5))
    #h << (x3 < x5 ? (x2 < x3 ? x2 : x3) : (x2 < x5 ? x2 : x5))
    x2 = 2 * h[i += 1] if x2 == h[n]
    x3 = 3 * h[j += 1] if x3 == h[n]
    x5 = 5 * h[k += 1] if x5 == h[n]
  end
  h[limit - 1]
end
```

```
In hammingnumber1.cr:16:34

 16 | x2 = 2 * h[i += 1] if x2 == h[n]
                                   ^
Error: undefined method '[]' for BigInt
```
The issue seems to be the compiler only wants array indices as type ``Int32`` and for some reason when the array values are ``BigInts`` it has a fit. But you can have arrays of mixed types without this problems, so I consider this problem a bug.

**Comment by asterite** [comment]
You need to call to_i on the big integer before using it as an index.

**Comment by jzakiya** [comment]
Could you show me an example, and why should a person have to do that to use ``BigInts`` as array content values?

**Comment by Blacksmoke16** [comment]
The problem here is `h` is a `BigInt`, not an `Array`.  On line 10 you have `h = Math.min(x2, Math.min(x3, x5))`, so yea the error is correct.

**Comment by jzakiya** [comment]
Excuse me, that was a typo.
Here's the error with the corrected line.

```
def hamming(limit)
  #h = Array(BigInt).new
  h = Array.new(limit, 1.to_big_i) # or h = Array.new(limit.to_big_i, 1.to_big_i)
  h[0] = 1.to_big_i
  x2, x3, x5 = 2.to_big_i, 3.to_big_i, 5.to_big_i
  i, j, k = 0, 0, 0
  (1..limit).each do |n|
    h[n] = Math.min(x2, Math.min(x3, x5))
    #h << (x3 < x5 ? (x2 < x3 ? x2 : x3) : (x2 < x5 ? x2 : x5))
    x2 = 2 * h[i += 1] if x2 == h[n]
    x3 = 3 * h[j += 1] if x3 == h[n]
    x5 = 5 * h[k += 1] if x5 == h[n]
  end
  h[limit - 1]
end

start = Time.monotonic
print "Hamming Number (1..20): "; (1..20).each { |i| print "#{hamming(i)} " }
puts
puts "Hamming Number 1691: #{hamming 1691}"
puts "Hamming Number 1,000,000: #{hamming 1_000_000}"
puts "Elasped Time: #{(Time.monotonic - start).total_seconds} sec
```
```
Hamming Number (1..20): Unhandled exception: Index out of bounds (IndexError)
  from ???
  from /home/jzakiya/crystal/share/crystal/src/pointer.cr:117:6 in 'hamming'
  from hammingnumber1.cr:24:60 in '__crystal_main'
  from /home/jzakiya/crystal/share/crystal/src/crystal/main.cr:105:5 in 'main'
  from __libc_start_main
  from ../sysdeps/x86_64/start.S:122:0 in '_start'
  from ???
```
Why does Array indexing have any relationship to Array data?
Why does Array indexing behave differently for ``BigInt`` data?

When I ``push`` BigInt data into the Array via ``<<``, where no explicit index value is given it works.
When I try to write to an explicit index value it doesn't work, as the code demonstrates.
I appears reading from an Array index doesn't cause a problem.

The only fundamental differences between the working and non-working code using ``BigInt`` data values, is whether assignment is done via ``h << ``  or ``h[n] = ``.  You should be able to write to an explicit Array location no matter what the data types are. This is a bug.

**Comment by Blacksmoke16** [comment]
I don't think this has anything to do with `BigInt`?

Can we try to use a simpler example. 

```cr
require "big"

arr = [] of Int32

arr[0] = 1

arr2 = [] of BigInt

arr2[0] = 1.to_big_i
```

Both of these would fail because there is no element with an index of `0`.  As @asterite mentioned in https://github.com/crystal-lang/crystal/issues/9261#issuecomment-626232286 this is currently by design.

Maybe take a look at https://crystal-lang.org/api/master/Array.html#insert(index:Int,object:T)-instance-method.

**Comment by jzakiya** [comment]
You are not looking at the problem I've given you.
The Array limit is being set, it's not an empty array, each element has a value.
But in the problem I've shown you the Array elements can't be explicitly written to.
That's a bug no matter what the data types are.

**What good is an Array that you can't write data to?**

**Comment by Blacksmoke16** [comment]
> But in the problem I've shown you the Array elements can't be explicitly written to.

Right, because the index you're trying to alter doesn't exist.  Which, as mentioned previously, is currently by design.

> The Array limit is being set, it's not an empty array, each element has a value.

This isn't true.  See this simplified version of the `hamming` method.

```cr
# Creates an array with 1 element with value of `1`
h = Array.new 1, 1

h # => [1]

# Changes the value of index `0` to `2`
h[0] = 2

h # => [2]

(1..1).each do |n|
  # Fails since there is no value at index `1`.
  h[n] = 3
end
```

**Comment by asterite** [comment]
By the way

## Python

```
🍏 python
Python 2.7.16 (default, Apr 12 2019, 15:32:40)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> a = [1]
>>> a[1] = 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list assignment index out of range
```

## Java

```java
import java.util.*;

public class Main {
  public static void main(String[] args) {
    ArrayList<String> array = new ArrayList<String>(10);
    array.set(0, "hello");
  }
}
```

Output:

```
🍏 javac Main.java
🍏 java Main
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.set(ArrayList.java:472)
	at Main.main(Main.java:6)
```

**Comment by jzakiya** [comment]
Please provide a working example using ``BigInt`` data use ``h[n] = ..``

**Comment by Blacksmoke16** [comment]
```cr
require "big"

arr2 = [1.to_big_i] of BigInt

pp arr2 # => [1]

arr2[0] = 2.to_big_i

pp arr2 # => [2]
```

**Comment by asterite** [comment]
@jzakiya 

```crystal
require "big"

def hamming(limit)
  h = Array(BigInt).new
  h << 1.to_big_i
  x2, x3, x5 = 2.to_big_i, 3.to_big_i, 5.to_big_i
  i, j, k = 0, 0, 0
  (1..limit).each do |n|
    h << (x3 < x5 ? (x2 < x3 ? x2 : x3) : (x2 < x5 ? x2 : x5))
    x2 = 2 * h[i += 1] if x2 == h[n]
    x3 = 3 * h[j += 1] if x3 == h[n]
    x5 = 5 * h[k += 1] if x5 == h[n]
  end
  h[limit - 1]
end

start = Time.monotonic
print "Hamming Number (1..20): "; (1..20).each { |i| print "#{hamming(i)} " }
puts
puts "Hamming Number 1691: #{hamming 1691}"
puts "Hamming Number 1,000,000: #{hamming 1_000_000}"
puts "Elasped Time: #{(Time.monotonic - start).total_seconds} sec"
```

**Comment by jzakiya** [comment]
I figured it out the error message: ``Index out of bounds (IndexError)``
```
 Unhandled exception: Index out of bounds (IndexError)
  from ???
  from /home/jzakiya/crystal/share/crystal/src/pointer.cr:117:6 in 'hamming'
  from hammingnumber2.cr:23:60 in '__crystal_main'
  from /home/jzakiya/crystal/share/crystal/src/crystal/main.cr:105:5 in 'main'
  from __libc_start_main
  from ../sysdeps/x86_64/start.S:122:0 in '_start'
  from ???
```

This code works
```
 def hamming(limit)
  h = Array.new(limit, 1.to_big_i)
  #h[0] = 1.to_big_i
  x2, x3, x5 = 2.to_big_i, 3.to_big_i, 5.to_big_i
  i, j, k = 0, 0, 0
  (1..limit-1).each do |n|     # or (1...limit).each do |n|   <-- original (1..limit).each do |h|
    h[n] = Math.min(x2, Math.min(x3, x5))
    x2 = 2 * h[i += 1] if x2 == h[n]
    x3 = 3 * h[j += 1] if x3 == h[n]
    x5 = 5 * h[k += 1] if x5 == h[n]
  end
  h[limit - 1]
end
```
So in the original version appears to have created one more array element than the 2nd version?
So it was my screwup, not yours. But I least I figure it out.

**Comment by jzakiya** [comment]
Yes, that was it, the original version was creating ``limit + 1`` actual array elements.
The following code also works.
```
def hamming(limit)
  h = Array.new(limit+1, 1.to_big_i)
  x2, x3, x5 = 2.to_big_i, 3.to_big_i, 5.to_big_i
  i, j, k = 0, 0, 0
  (1..limit).each do |n|
    h[n] = Math.min(x2, Math.min(x3, x5))
    x2 = 2 * h[i += 1] if x2 == h[n]
    x3 = 3 * h[j += 1] if x3 == h[n]
    x5 = 5 * h[k += 1] if x5 == h[n]
  end
  h[limit - 1]
end

start = Time.monotonic
print "Hamming Number (1..20): "; (1..20).each { |i| print "#{hamming(i)} " }
puts
puts "Hamming Number 1691: #{hamming 1691}"
puts "Hamming Number 1,000,000: #{hamming 1_000_000}"
puts "Elasped Time: #{(Time.monotonic - start).total_seconds} secs"
```
Also, pre allocating array memory makes it faster, instead of pushing each element into the array.
Well, I (re)learned the lesson to actually understand what's going, and not just copy code. :-)
