### ISSUE TITLE
`TypeNode#</<=/etc` with `Class` is always `false`

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#9265]
https://play.crystal-lang.org/#/r/91eo

```cr
abstract class Parent
end

class Child < Parent
end

{{pp Child < Parent}} # => true
{{pp Child < Class}} # => false
{{pp Parent < Class}}# => false
```

I would have expected these to all return `true`.  I noticed it does work for `Struct`.

The use case is I wanted to be able to identify types that are classes/structs that don't implement a module so that they would be ignored.

**Comment by asterite** [comment]
`Child` doesn't have `Class` in its ancestors:

```crystal
abstract class Parent
end

class Child < Parent
end

{% puts Child.ancestors %}
```

Output:

```
[Parent, Reference, Object]
```

A Child instance is not a Class. The Child **class* inherits from class. But I don't think there's a way to talk about that in code because `Child.class` will return `Class`.

**Comment by Blacksmoke16** [comment]
Hm, then is it expected for structs to have `Struct` in its ancestors?

```cr
abstract struct Parent
end

struct Child < Parent
end

{% puts Child.ancestors %} # => [Parent, Struct, Value, Object]
```

**Comment by asterite** [comment]
Oh, yeah, it's a bit confusing. But `Class` represents all types. It should be called `Type` but `Class` exists before we even had structs (we copied it from Ruby).

`Struct` is the parent type of all user-defined structs. For instance, `Int32` is a struct but it inherits from `Value`, not from `Struct`. So maybe `Struct` should be called `UserDefinedStruct`.

I think the types you are looking for is `Reference` (classes) and `Value` (structs).

**Comment by Blacksmoke16** [comment]
> But `Class` represents all types.

Ahh gotcha.

> I think the types you are looking for are `Reference` (classes) and `Value` (structs).

Hm, wouldn't those also include non user defines classes/structs?  Was trying to determine if a given type is something defined by the user like `class/struct User`, or if its a primitive type or a type defined by the stdlib.

**Comment by straight-shoota** [comment]
> but just wouldn't have a way to detect user defined classes. 

I don't think there are any primitive classes (except `String` which is special in its own way), so `Reference` should be the equivalent of `Struct` in the sense you're looking for.

**Comment by Blacksmoke16** [comment]
It also includes `Array`, `Regex`, Hash`, and such.  I suppose I could say like `child of Reference, but not x | y | z`, but meh.  I'll just go to plan B.
