### ISSUE TITLE
C functions with `UInt8[x]`  arguments aren't compatible with `Slice(UInt8)`.

### ISSUE THREAD

**Issue by didactic-drunk** [crystal-lang/crystal#9271]
Generated function from libgen:
```
fun crypto_secretstream_xchacha20poly1305_init_push(state : CryptoSecretstreamXchacha20poly1305State*,
  header : UInt8[24],
  k : UInt8[32]
) : LibC::Int
```

Error:
```
 > LibSodium.crypto_secretstream_xchacha20poly1305_init_push(self, head, k.to_slice)
                                                                         ^-------
Error: argument 'k' of 'Sodium::LibSodium#crypto_secretstream_xchacha20poly1305_init_push'
must be StaticArray(UInt8, 32), not Slice(UInt8) (nor Pointer(UInt8)
returned by 'Slice(UInt8)#to_unsafe')
```

I could copy to a `StaticArray` but there are several reasons why it's inappropriate.
1. `k` is a key held in nonswappable auto clearing memory.  Copying to a `StaticArray` may leave key material in swap.  It also needs manual clearing and is easy to forget or mess up.
2. Memory (in my shards) is allocated based on c function return values to determine the size.  If  `StaticArray` is used  I need more code to support macro generated classes because the size functions aren't available in macros or header values aren't available at all.  There is greater risk of these values getting out of sync with new versions because I need to update and check them manually.
3. It's more work (both programmer and program) and seems unnecessary.

Crystal 0.34.

**Comment by jhass** [comment]
Well, you could always pretend one thing is the other `to_unsafe.as(StaticArray(UInt8, 24)*).value`. Is this safe? I'm not sure, aren't static arrays passed by value? Is that even possible for a heap allocated object like `Slice`? That's also why I'm not sure Crystal could even do what you propose. It doesn't feel safe, at least not generally.

**Comment by asterite** [comment]
Is static array a thing in C? As far as I know you should use pointer of UInt8 instead of static array in the binding, because C arrays don't know their length.

**Comment by didactic-drunk** [comment]
[Header definition](https://github.com/jedisct1/libsodium/blob/3f1586623cf23ed0e1c1211926eab7cac0bdb13e/src/libsodium/include/sodium/crypto_stream_xchacha20.h#L54)
```
void crypto_stream_xchacha20_keygen(unsigned char k[crypto_stream_xchacha20_KEYBYTES])
```

**Comment by asterite** [comment]
@didactic-drunk Take this c file:

```c
// c.c
#define crypto_stream_xchacha20_KEYBYTES 32U

void crypto_stream_xchacha20_keygen(unsigned char k[crypto_stream_xchacha20_KEYBYTES])
            __attribute__ ((nonnull)) {
}
```

Compile it with clang and output llvm ir:

```
🍏 clang -S -emit-llvm c.c
c.c:15:29: warning: GCC does not allow 'nonnull' attribute in this position on a
      function definition [-Wgcc-compat]
            __attribute__ ((nonnull)) {
                            ^
1 warning generated.
```

Look at the resulting LLVM IR:

```llvm
; ModuleID = 'c.c'
source_filename = "c.c"
target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-apple-macosx10.15.0"

; Function Attrs: noinline nounwind optnone ssp uwtable
define void @crypto_stream_xchacha20_keygen(i8* nonnull %0) #0 {
  %2 = alloca i8*, align 8
  store i8* %0, i8** %2, align 8
  ret void
}

attributes #0 = { noinline nounwind optnone ssp uwtable "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="penryn" "target-features"="+cx16,+cx8,+fxsr,+mmx,+sahf,+sse,+sse2,+sse3,+sse4.1,+ssse3,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }

!llvm.module.flags = !{!0, !1}
!llvm.ident = !{!2}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"PIC Level", i32 2}
!2 = !{!"clang version 10.0.0 "}
```

See `define void @crypto_stream_xchacha20_keygen(i8* nonnull %0)`? That a pointer to UInt8.

Static arrays don't exist at runtime in C, only at compile-time. The C compiler can probably yell if you exceed the bounds **at compile time**, but at runtime "static arrays" are just pointers. At least in functions. In structs they are still probably arrays, but their size is used for the struct layout.

libgen is wrong and it should generate pointers in that case.

**Comment by asterite** [comment]
Alternatively, we _could_ allow specifying static arrays in C bindings, and codegen them as pointers, but allowing only to pass static arrays. But the workaround of passing a pointer is good. Do you know how this works in, say, Rust? If they handle static arrays like what I say here, we might consider doing it. Super low priority, though, not gonna happen before 1.0

**Comment by didactic-drunk** [comment]
> but allowing only to pass static arrays.

I was hoping for length verified `Slices`.  With this library too large and it's ignored.  Too small may overwrite memory.

**Comment by didactic-drunk** [comment]
>  we _could_ allow specifying static arrays in C bindings, and codegen them as pointers, but allowing only to pass static arrays

That's definitievely not the correct behavior and not what's required of a c program.  `unsigned char k[crypto_stream_xchacha20_KEYBYTES]` helps the compiler verify the length when it can but also accepts `unsigned char *`. 

Also see [points 1-3](https://github.com/crystal-lang/crystal/issues/9271#issue-615466709).

**Comment by straight-shoota** [comment]
> I was hoping for length verified `Slices`.

I don't think that's feasible. It would require injecting custom validation code for calling external functions.
That's a lot to ask for a realistically niche use case. As @asterite already mentioned, even in C there's no such runtime validation of the call arg.
So it's a compile-time only validation. At runtime, you can just pass any pointer.

Such a compile-time validation can't be done in Crystal. The only container type with a fixed size at compile time is `StaticArray` and that is not really useful for this, as argued above.

IMO there is nothing actionable here. In order to validate the size of the arguments, it needs to happen at runtime to support collections with dynamic size (like `Slice`). And that should just be implemented in the code that calls the external functions.
