### ISSUE TITLE
Crystal always starts multiple threads, even when app is not multithreaded

### ISSUE THREAD

**Issue by shaicoleman** [crystal-lang/crystal#9276]
myapp.cr:
```
sleep 1000
```

```
$ nproc
8
$ crystal build --release myapp.cr
./myapp

ps -e -T | grep myapp
 9628  9628 pts/0    00:00:00 myapp
 9628  9629 pts/0    00:00:00 myapp
 9628  9630 pts/0    00:00:00 myapp
 9628  9631 pts/0    00:00:00 myapp
 9628  9632 pts/0    00:00:00 myapp
 9628  9633 pts/0    00:00:00 myapp
 9628  9634 pts/0    00:00:00 myapp
 9628  9635 pts/0    00:00:00 myapp
```

Version info:
Crystal 0.34.0 [4401e90] (2020-04-06) on Ubuntu 18.04 x64
Installed via apt, package version=0.34.0-1

**Comment by asterite** [comment]
That's the GC, which is multithreaded.

**Comment by asterite** [comment]
Also please ask things that might be bugs but you are not sure in the forums. Questions in general too.

**Comment by jhass** [comment]
If you want to watch the GC doing it's work, including spawning its threads, set `GC_PRINT_STATS=1`
