### ISSUE TITLE
XML::Node.xpath_node dose not accept XML::Namespace

### ISSUE THREAD

**Issue by 1w1g** [crystal-lang/crystal#9279]
Hi
XML::Node.xpath_node dose not accept XML::Namespace as its second argument. it only accepts Hash.

Crystal 0.34.0 [4401e90f0] (2020-04-06)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu

```
require "xml"
str_xml=<<-XML
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
  <soap:Body>
    <NumberToWordsResponse xmlns="http://www.1w1g.com/">
      <NumberToWordsResult>string</NumberToWordsResult>
    </NumberToWordsResponse>
  </soap:Body>
</soap:Envelope>
XML
x = XML.parse str_xml
puts x.xpath_node("/soap:Envelope/soap:Body",x.root.not_nil!.namespace).not_nil!.name
```

Error output:
In /usr/lib/crystal/xml/xpath_context.cr:39:16

 39 | namespaces.each do |prefix, uri|
                 ^---
Error: undefined method 'each' for XML::Namespace

**Comment by asterite** [comment]
The real thing:
- `xml.root.namespaces.not_nil!` can be passed as a second argument, but it currently fails at runtime because it has "xmlns:soap" instead of "soap" as a prefix.

Namespace **shouldn't** be accepted.

**Comment by 1w1g** [comment]
miss the "s" new code and error:
```
require "xml"
str_xml=<<-XML
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
  <soap:Body>
    <NumberToWordsResponse xmlns="http://www.1w1g.com/">
      <NumberToWordsResult>string</NumberToWordsResult>
    </NumberToWordsResponse>
  </soap:Body>
</soap:Envelope>
XML
x = XML.parse str_xml
puts x.xpath_node("/soap:Envelope/soap:Body",x.root.not_nil!.namespaces).not_nil!.name
```
Error output:
Unhandled exception: Error in '/soap:Envelope/soap:Body' expression (XML::Error)
  from /usr/lib/crystal/xml/xpath_context.cr:18:5 in 'evaluate'
  from /usr/lib/crystal/xml/node.cr:488:5 in 'xpath'
  from /usr/lib/crystal/xml/node.cr:529:5 in 'xpath_nodes'
  from /usr/lib/crystal/xml/node.cr:544:5 in 'xpath_node'
  from /usr/lib/crystal/xml/node.cr:543:3 in 'xpath_node'
  from /eval:13:3 in '__crystal_main'
  from /usr/lib/crystal/crystal/main.cr:105:5 in 'main_user_code'
  from /usr/lib/crystal/crystal/main.cr:91:7 in 'main'
  from /usr/lib/crystal/crystal/main.cr:114:3 in 'main'
  from __libc_start_main
  from _start
  from ???
