### ISSUE TITLE
Add support for `as_u64` for JSON::any

### ISSUE THREAD

**Issue by Uzay-G** [crystal-lang/crystal#9286]
To convert from `JSON::Any` to readable data, there are many methods listed [here](https://crystal-lang.org/api/0.34.0/JSON/Any.html), including `as_i64`. Unfortunately there is not a direct way to convert this to an unsigned integer. Although it is possible to call `as_64.to_u64`

**Comment by asterite** [comment]
Yes, that's the way you do it. The underlying JSON data is just the ones you can access through the `as` methods. Providing `to_u64` would be confusing because it would **overflow** if it's greater than Int64::MAX. So I think doing `as_i64.to_u64` is the most explicit way.

**Comment by Uzay-G** [comment]
Alright no problem then :+1:
