### ISSUE TITLE
Possible Error in Unix Filedescriptor from stdio

### ISSUE THREAD

**Issue by Simerax** [crystal-lang/crystal#9290]
I just browsed through the source code of the compiler and I noticed the following code inside `src/crystal/system/unix/file_descriptor.cr`
```cr
    def self.from_stdio(fd)
        # If we have a TTY for stdin/out/err, it is possibly a shared terminal.
        # We need to reopen it to use O_NONBLOCK without causing other programs to break

        # Figure out the terminal TTY name. If ttyname fails we have a non-tty, or something strange.
        # For non-tty we set flush_on_newline to true for reasons described in STDOUT and STDERR docs.
        path = uninitialized UInt8[256]
        ret = LibC.ttyname_r(fd, path, 256)
        return IO::FileDescriptor.new(fd).tap(&.flush_on_newline=(true)) unless ret == 0

        clone_fd = LibC.open(path, LibC::O_RDWR)
        return IO::FileDescriptor.new(fd).tap(&.flush_on_newline=(true)) if clone_fd == -1

        # We don't buffer output for TTY devices to see their output right away
        io = IO::FileDescriptor.new(clone_fd)
        io.close_on_exec = true
        io.sync = true
        io
    end
```
Shouldn't `return IO::FileDescriptor.new(fd).tap(&.flush_on_newline=(true)) unless ret == 0` actually be `return IO::FileDescriptor.new(fd).tap(&.flush_on_newline=(true)) if ret == 0`

the [gnu docs](https://www.gnu.org/software/libc/manual/html_mono/libc.html#index-terminal-identification) for libc state that `ttyname_r` returns 0 on success 

> The normal return value from ttyname_r is 0. Otherwise an error number is returned to indicate the error. 

Therefore the return is only done when `ttyname_r` actually failed which would be wrong.

The Problem might come from the docs of the `ttyname` function because this version actually does return null on failure

> If the file descriptor filedes is associated with a terminal device, the ttyname function returns a pointer to a statically-allocated, null-terminated string containing the file name of the terminal file. The value is a null pointer if the file descriptor isn’t associated with a terminal, or the file name cannot be determined. 

Am I missing something?

**Comment by asterite** [comment]
I think the code is fine?

If ret is 0 it means it's a tty. If it's not 0 it's not a tty. In that case we return early and don't set `sync` to true. That is, if it's not 0, not a tty, we buffer output, but output on newline.

**Comment by Simerax** [comment]
Well right the return is triggered when ret != 0 which means that `ttyname_r` failed and therefore `fd` could be invalid or not?

**Comment by asterite** [comment]
Why it would be invalid? We only pass 0, 1 and 2 to it which are STDIN, STDOUT and STDERR.

**Comment by Simerax** [comment]
i meant path sorry i see that path isn't really used.
I just thought that it was weird to return on failure there but I honestly don't know enough about libc or crystal to judge this

**Comment by RX14** [comment]
`IO::FileDescriptor.new(fd).tap(&.flush_on_newline=(true))` is the "fallback" when something fails

the normal flow of the function if there are no errors is to return `IO::FileDescriptor.new(clone_fd)
`.
