### ISSUE TITLE
Create Enumerable ".lazy_skip(count)" method

### ISSUE THREAD

**Issue by jzakiya** [crystal-lang/crystal#9337]
Currently the Enumerable ``.skip(count)`` method requires the existence of an array to operate on.
```
#skip(count : Int)

Returns an Array with the first count elements removed from the original collection.
```
It would be really nice to have a ``lazy version``,  to ``skip`` past ``count`` elements while being created, and then start the collection.  This should increase performance and reduce overall memory usage.

**Actual Use Case:**
The following code was originally created by @jhass, whose final form I used [here](https://rosettacode.org/wiki/Palindromic_gapful_numbers#Orders_of_Magnitude_Faster:_Direct_Generation_of_Numbers), is shown below.
```crystal
struct PalindromicGapfuls
  include Enumerable(UInt64)
 
  @nn : Int32
 
  def initialize(@digit : Int32)
    @nn = @digit * 11                   # digit gapful divisor: 11, 22,...88, 99
  end
 
  def each
    (2..).each do |power|
      base    = 10_u64 ** (power >> 1)  # value of middle digit position: 10..
      this_lo = base * @digit           # starting half for this digit: 10.. to  90.. 
      next_lo = base * (@digit + 1)     # starting half for next digit: 20.. to 100..
      this_lo.step(to: next_lo - 1, by: 10) do |front_half|   # d_10; d_20; d_30; ...
        if power.odd?                   # for even number of total digits: ab..ba
          front_half.upto(front_half + 9) do |upper_half|     # d_n0 to d_n9
            palindrome_half = upper_half.to_s
            palindrome = (palindrome_half + palindrome_half.reverse).to_u64
            yield palindrome if palindrome % @nn == 0
          end
        else                            # for odd number of total digits: ab..m..ba
          palindrome_half = (front_half // 10).to_s           # d_n
          palindrome = (palindrome_half + "0" + palindrome_half.reverse).to_u64
          # increase palindrome middle digit from ---0--- to ---9---
          10.times do
            yield palindrome if palindrome % @nn == 0
            palindrome += base         # increase middle digit value
          end
        end
      end
    end
  end
end
 
count, keep = 20, 20
puts "First 20 palindromic gapful numbers ending with:"
1.upto(9) { |digit| puts "#{digit} : #{PalindromicGapfuls.new(digit).first(count).last(keep)}" }
 
count, keep = 100, 15
puts "\nLast 15 of first 100 palindromic gapful numbers ending in:"
1.upto(9) { |digit| puts "#{digit} : #{PalindromicGapfuls.new(digit).first(count).last(keep)}" }
 
count, keep = 1_000, 10
puts "\nLast 10 of first 1000 palindromic gapful numbers ending in:"
1.upto(9) { |digit| puts "#{digit} : #{PalindromicGapfuls.new(digit).first(count).last(keep)}" }
 
count, keep = 100_000, 1
puts "\n100,000th palindromic gapful number ending with:"
1.upto(9) { |digit| puts "#{digit} : #{PalindromicGapfuls.new(digit).first(count).last(keep)}" }
 
count, keep = 1_000_000, 1
puts "\n1,000,000th palindromic gapful number ending with:"
1.upto(9) { |digit| puts "#{digit} : #{PalindromicGapfuls.new(digit).first(count).last(keep)}" }
 
count, keep = 10_000_000, 1
puts "\n10,000,000th palindromic gapful number ending with:"
1.upto(9) { |digit| puts "#{digit} : #{PalindromicGapfuls.new(digit).first(count).last(keep)}" }
```
Currently for the output, doing the following:
```
#{PalindromicGapfuls.new(digit).first(count).skip(count - keep).first(keep)}"
or
#{PalindromicGapfuls.new(digit).first(count).skip(count - keep).last(keep)}"
or
#{PalindromicGapfuls.new(digit).first(count).skip(count - keep)}"
```
has no performance}memory advantages over the original output statements.
In each case, an array of ``counts`` elements still must be created.

Also, doing the following will compile, but when run, hangs, requiring a hard abort.
```
#{PalindromicGapfuls.new(digit).skip(count - keep).last(keep)}"
```
What is desirable for these cases is a ``lazy_skip(count)`` which can count the elements to skip, and then create the array collection.

The desirable output statement would then be:
```
#{PalindromicGapfuls.new(digit).lazy_skip(count - keep)}"
```
Now, only one collection is created, with subsequent savings in memory use.

This should be fairly easy to implement. Basically all you have to do is count the number of ``yields`` received, and then start collecting the rest of the elements after this.

For the examples shown, this should produce a significant performance increase, with a huge memory decrease, especially for the last 3 largest ``count`` examples.

**Comment by asterite** [comment]
What you need to do here is to implement [Iterator](https://crystal-lang.org/api/0.34.0/Iterator.html) instead of `Enumerable`. `Iterator` is the lazy version. 

Implementing `Iterator` is a bit harder than `Enumerable`, but that's what we've got.

**Comment by jzakiya** [comment]
I changed ``include Enumerator(..)`` to ``include Iterator(..)``, and then ``def each`` to ``def next``,
but get this compile errors.
```
Showing last frame. Use --error-trace for full trace.

In /home/jzakiya/crystal/share/crystal/src/iterator.cr:145:16

 145 | abstract def next
                    ^---
Error: abstract `def Iterator(T)#next()` must be implemented by PalindromicGapfuls
``` 
Can you tell me what I'm doing wrong.

But besides that, I still think an Enumerable ``lazy_skip(count)`` would be good to have and give users another option to achieve desirable results.

**Comment by Blacksmoke16** [comment]
> Can you tell me what I'm doing wrong.

Hard to say without seeing the code.

**Comment by jzakiya** [comment]
The code is posted above, with the changes I outlined.

**Comment by Blacksmoke16** [comment]
You're yielding in your `next`, which makes it not what the API is expecting.  I.e. you have `def next(&)` not `def next`.

**Comment by jzakiya** [comment]
Can you please change the code so it works correctly.

**Comment by Blacksmoke16** [comment]
Sorry, I don't know enough about what it's doing to do that easily.

**Comment by asterite** [comment]
@jzakiya As I mentioned, changing an `Enumerable` to an `Iterable` is a really hard task. 

Please read the docs of Iterable to get an idea of what you'd need to do. But there's nothing else to do here.

Also, there's no way to implement `lazy_skip(count)` for an `Enumerable`. It's just impossible.

**Comment by bew** [comment]
Also, don't hesitate to come in the forum or in the gitter channel to talk about it and ask questions

**Comment by asterite** [comment]
Oh, actually, there is a way you can do it, but I recommend only defining this method in your type because `skip_and_last` is too specific. Just add this method to your class:

```crystal
  def skip_and_last(skip_count, keep_last)
    array = Array(UInt64).new(keep_last)
    skipped = 0
    each do |value|
      if skipped < skip_count
        skipped += skip_count
      else
        array << value
      end
    end
    array
  end
```

It's basically building an array by using `each`, but skipping the first values.

@jzakiya Let us know if that improves the performance a bit.

**Comment by asterite** [comment]
Well, what I sent above isn't exactly right... but you get the idea.

**Comment by asterite** [comment]
Here you go:

```crystal
struct PalindromicGapfuls
  include Enumerable(UInt64)

  @n : Int32

  def initialize(@digit : Int32)
    @n = @digit * 11 # digit gapful divisor: 11, 22,...88, 99
  end

  def each
    (2..).each do |power|
      base = 10_u64 ** (power >> 1)                         # value of middle digit position: 10..
      this_lo = base * @digit                               # starting half for this digit: 10.. to  90..
      next_lo = base * (@digit + 1)                         # starting half for next digit: 20.. to 100..
      this_lo.step(to: next_lo - 1, by: 10) do |front_half| # d_10; d_20; d_30; ...
        if power.odd?                                       # for even number of total digits: ab..ba
          front_half.upto(front_half + 9) do |upper_half|   # d_n0 to d_n9
            palindrome_half = upper_half.to_s
            palindrome = (palindrome_half + palindrome_half.reverse).to_u64
            yield palindrome if palindrome % @n == 0
          end
        else                                        # for odd number of total digits: ab..m..ba
          palindrome_half = (front_half // 10).to_s # d_n
          palindrome = (palindrome_half + "0" + palindrome_half.reverse).to_u64
          # increase palindrome middle digit from ---0--- to ---9---
          10.times do
            yield palindrome if palindrome % @n == 0
            palindrome += base # increase middle digit value
          end
        end
      end
    end
  end

  def first_last(count, keep)
    to_skip = count - keep
    skipped = 0

    array = Array(UInt64).new(keep)
    each do |value|
      if skipped < to_skip
        skipped += 1
      else
        array << value
        break if array.size == keep
      end
    end
    array
  end
end

count, keep = 20, 20
puts "First 20 palindromic gapful numbers ending with:"
1.upto(9) { |digit| puts "#{digit} : #{PalindromicGapfuls.new(digit).first_last(count, keep)}" }

count, keep = 100, 15
puts "\nLast 15 of first 100 palindromic gapful numbers ending in:"
1.upto(1) { |digit| puts "#{digit} : #{PalindromicGapfuls.new(digit).first_last(count, keep)}" }

count, keep = 1_000, 10
puts "\nLast 10 of first 1000 palindromic gapful numbers ending in:"
1.upto(9) { |digit| puts "#{digit} : #{PalindromicGapfuls.new(digit).first_last(count, keep)}" }

count, keep = 100_000, 1
puts "\n100,000th palindromic gapful number ending with:"
1.upto(9) { |digit| puts "#{digit} : #{PalindromicGapfuls.new(digit).first_last(count, keep)}" }

count, keep = 1_000_000, 1
puts "\n1,000,000th palindromic gapful number ending with:"
1.upto(9) { |digit| puts "#{digit} : #{PalindromicGapfuls.new(digit).first_last(count, keep)}" }

count, keep = 10_000_000, 1
puts "\n10,000,000th palindromic gapful number ending with:"
1.upto(9) { |digit| puts "#{digit} : #{PalindromicGapfuls.new(digit).first_last(count, keep)}" }
```

**Comment by jzakiya** [comment]
Thanks @asterite. I had actually come to the same conclusion to create a customized output method and not worry about using ``stdlib`` methods.

Your code works, after changing ``array = Array(UInt64).new(keep)`` to ``array = [] of UInt64``, because the array can't start out at the final size. And it is much faster, with the significant decrease in memory use.   I'll post some times when I get a chance. And after playing around with it, I settled on this final form of the method.

```
def keep_from(count, keep)
   skipped, to_skip = 0, (count - keep)
   kept = [] of UInt64
   each do |value|
     (skipped += 1; next) if skipped < to_skip
     kept << value
     return kept if kept.size == keep
   end
 end
```

**Comment by jzakiya** [comment]
Oh BTW, Ruby has a ``drop(n)`` Enumerable and not ``skip(n)``.

This would be easy to do in Crystal from the above code:

```
def drop(count)
   dropped, to_drop = 0, (count - keep)
   each do |value|
     (dropped += 1; next) if dropped < to_drop
    return
   end
 end
```

**Comment by HankAnderson** [comment]
Ruby's `drop` is **exactly the same** as Crystal's `skip`. It seems Crystal only has `skip` because they chose not to have aliases.

> after changing array = Array(UInt64).new(keep) to array = [] of UInt64, because the array can't start out at the final size

What do you mean with this? The argument you pass to the Array constructor is the initial capacity, not the array size. I tried the code from @asterite and compared it to the original code and they both give the same result.

**Comment by jzakiya** [comment]
Actually, the Ruby version didn't work with ``Array.new(keep)``, that was a mental typo, but I changed both to use ``[]``. I just mixed up the versions.
