### ISSUE TITLE
Symbol to enum autocasting doesn't work when the symbol originates from a macro

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#9347]
https://play.crystal-lang.org/#/r/94mb

```cr
enum Test
  One
  Two
end
 
class Parent
  def initialize(@test : Test)
  end
end
 
class Child < Parent
  def initialize
    # Changing it to a non macro `:one` works
    super {{:one}}
  end
end
 
pp Child.new
```

```
Showing last frame. Use --error-trace for full trace.

error in line 14
Error: no overload matches 'Parent#initialize' with type Symbol

Overloads are:
 - Parent#initialize(test : Test)
```

**Comment by asterite** [comment]
That's what "The argument must be a number literal or symbol literal" means.

I don't want to implement this, it broadens the rules and makes the code more complex, and I fail to see why this is needed (why can't the macro generate an enum instead?).

**Comment by Blacksmoke16** [comment]
Idea was something like: https://play.crystal-lang.org/#/r/97bt

```cr
require "http/status"
 
class HTTPException
  def initialize(@status : HTTP::Status); end
end
 
class BadRequest < HTTPException
  def initialize
    super {{@type.name.underscore.symbolize}}
  end
end
 
pp BadRequest.new
```

to use the type's name to map to an enum member.  FWIW, defining the initializer in the parent via `macro included` works: https://play.crystal-lang.org/#/r/97bs

```cr
require "http/status"

class HTTPException
  def initialize(@status : HTTP::Status); end
  
  macro inherited
    def initialize
      super {{@type.name.underscore.symbolize}}
    end
  end
end

class BadRequest < HTTPException
end

pp BadRequest.new
```

Either way, given the behavior difference I thought I'd report it.  I ended up just scrapping the macro idea and hard coded the values anyway.

**Comment by asterite** [comment]
This also works:

```crystal
require "http/status"

class HTTPException
  def initialize(@status : HTTP::Status); end
end

class BadRequest < HTTPException
  def initialize
    super {{"HTTP::Status::#{@type.name.underscore.upcase}".id}}
  end
end

pp BadRequest.new
```

I think there are now already workarounds to say that this feature might not be really needed.

**Comment by Blacksmoke16** [comment]
> I think there are now already workarounds to say that this feature might not be really needed.

I tend to agree, 👍.
