### ISSUE TITLE
Improve default settings and documentation of "log" module.

### ISSUE THREAD

**Issue by spTorin** [crystal-lang/crystal#9355]
# What in docs (pretty clear and simple):
```crystal
require "log"

Log.info { "Program started" }
```
Run this prog aaand nothing happens.

May be just use this settings as default (back: STDOUT, level: warn):
```
backend = Log::IOBackend.new
Log.builder.bind "*", :warning, backend
```

Also use by default format:
`[Time.local.rfc3339_without_nanoseconds] Log message`

90% uses not needed anymore else and if want - you can build more complex formatter.
And need example of usage formatter in docs.

**Comment by Blacksmoke16** [comment]
`0.35.0` fixes some of these issues.  See the changelog: https://github.com/bcardiff/crystal/blob/changelog/0.35.0/CHANGELOG.md#logging.

**Comment by asterite** [comment]
Can this be closed?

**Comment by spTorin** [comment]
Yes, please.
