### ISSUE TITLE
Format: failed on formatting heredoc containing only interpolation

### ISSUE THREAD

**Issue by MakeNowJust** [crystal-lang/crystal#9362]
For example, the following code is failed by `crystal tool format`:

```crystal
foo = <<-FOO
  #{__FILE__}
  FOO
# expecting DELIMITER_END, not `INTERPOLATION_START, `, at :2:3 (Exception)
```

I have [a patch for this bug](https://github.com/MakeNowJust/crystal/commit/f5ab084ec48ed7a54a442589c185cba6129c02f0). However this bug is very special corner case. For instance this bug is not invoked by this code:

```crystal
foo = <<-FOO
  #{__FILE__}: foo
  FOO
```

Perhaps, this bug does not cause problems in most cases.

I'd continue to find simpler way to fix this.

**Comment by straight-shoota** [comment]
Why isn't INTERPOLATION_START consumed while iterating `node.expressions`?

**Comment by MakeNowJust** [comment]
Because the first interpolation of string literal (`__FILE__`) consumes the first whitespaces of the heredoc and iteration exits.
