### ISSUE TITLE
Method macros seems to work differently than "normal" macros

### ISSUE THREAD

**Issue by gaku-sei** [crystal-lang/crystal#9372]
# Submitting bugs

I was playing a bit with the macros system, and tried to define a "smart" catch-all exceptions function. It works perfectly when defined in a module or at the top level:

```crystal
class MyException < Exception; end

module Works
  extend self

  macro f
    begin
      # Do something here

      {% for key, value in { MyException => "An exception!" } %}
        rescue {{key}}
          puts {{value}}
      {% end %}
      rescue e
        puts "Oops"
    end
  end
end

Works.f
```

But fails with the following error when used inside a class _as a method macro_:
```
 > 1 | 
 > 2 |         rescue MyException
               ^
Error: expecting token 'EOF', not 'rescue'
```

```crystal
class DoesntWork
  def f
    begin
      # Do something here

      {% for key, value in { MyException => "An exception!" } %}
        rescue {{key}}
          puts {{value}}
      {% end %}
      rescue e
        puts "Oops"
    end
  end
end

DoesntWork.new.f
```

(Notice that the code is exactly the same).

Not sure if that's intentional or not, and if there is any reasons to have this kind of limitations in method macros 😕 

You can find the full code here too: https://play.crystal-lang.org/#/r/961k

**Comment by bew** [comment]
Hello! You can read about this behavior in the language reference, under the section "Pitfalls" of macros docs:
https://crystal-lang.org/reference/syntax_and_semantics/macros.html#pitfalls

You'll need to add `{% begin %} {% end %}` around the whole begin/rescue/end block!

**Comment by asterite** [comment]
Just to make it clear, this is the working version:

```crystal
class MyException < Exception; end

class DoesntWork
  def f
    {% begin %}
      begin
        # Do something here

        {% for key, value in {MyException => "An exception!"} %}
          rescue {{key}}
            puts {{value}}
        {% end %}
      rescue e
        puts "Oops"
      end
    {% end %}
  end
end

DoesntWork.new.f
```

**Comment by gaku-sei** [comment]
Hello @asterite @bew , sorry for the late reply and thank you 😄 

The code above compiles 👍
