### ISSUE TITLE
Local variable considered defined even if it's only defined in a noreturn branch

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#9377]
```cr
if 1 < 0
  local_var = true
  raise "foo"
end

local_var # => nil
```
In the last line, `local_var` can't actually be defined because it's only defined in a branch that raises. The assignment in line 2 could never have happened before the variable is accessed in line 6.

Outside the if branch, it should be treated like it was never assigned in the first place:
```cr
if 1 < 0
  raise "foo"
end

local_var # Error: undefined local variable or method 'local_var' for top-level
```

It's probably not a super important feature, but it would be useful if the compiler could detect that.

This has surfaced in #9376: After extracting a noreturn branch to a separate method, the compiler complained about an undefined local variable when it wasn't defined for the main branch in the first place.

**Comment by jhass** [comment]
I guess this is because local variables are a parser level feature, while branch analysis only happens in semantic.

**Comment by asterite** [comment]
Yes, I was going to reply what jhass said.

**Comment by RX14** [comment]
i thought all local-var definitions are method-scoped

**Comment by RX14** [comment]
close?

**Comment by straight-shoota** [comment]
Why? I think this is a valid feature enhancement. It's not going to be implemented anytime soon. But it does not seem to be impossible.

**Comment by RX14** [comment]
It's a really really wide-ranging language change if we change the scoping rules for local variables... I don't see this happening but maybe others want to weigh in.

**Comment by asterite** [comment]
> Outside the if branch, it should be treated like it was never assigned in the first place

That's the current behavior: not assigned means `nil`.

I don't think there's anything to do here.

**Comment by straight-shoota** [comment]
Maybe this is something a linter like ameba could help with.

**Comment by Sija** [comment]
@straight-shoota IIRC it already does that :)
