### ISSUE TITLE
failed to require "crystal/datum"

### ISSUE THREAD

**Issue by emanzx** [crystal-lang/crystal#9381]
Compiling crystal source code that has require for crystal/datum return with cant find file. 
> $ crystal test.cr 
> Showing last frame. Use --error-trace for full trace.
> 
> In test.cr:1:1
> 
>  1 | require "crystal/datum"
>      ^
> Error: can't find file 'crystal/datum'
> 
> If you're trying to require a shard:
> - Did you remember to run `shards install`?
> - Did you make sure you're running the compiler in the same directory as your shard.yml?

```
crystal -v
Crystal 0.32.1 (2020-05-15)

LLVM: 9.0.1
Default target: x86_64-portbld-freebsd12.1
```

**Comment by j8r** [comment]
What do you want to require, a file? Then, add a leading `./` to the require path.

**Comment by asterite** [comment]
Hi! "crystal/datum" didn't exist in Crystal 0.32.1. I think it was added in 0.34.0.

And even then, it's `:nodoc:`, it's just an internal implementation detail, please don't use it.

**Comment by emanzx** [comment]
oh. noted.
