### ISSUE TITLE
[RFC] Mutex vs SpinLock API

### ISSUE THREAD

**Issue by didactic-drunk** [crystal-lang/crystal#9385]
Let`Mutex` and `Crystal::SpinLock` use the same API so use we can use them interchangeably especially in benchmarks.

* `Mutex#synchronize` -> `Mutex#sync`.
* New method `Mutex#unsync`.
* Deprecate `#synchronize`.

**Comment by asterite** [comment]
Crystal::SpinLock is internal API. Anything inside the Crystal namespace except VERSION is internal and you shouldn't use it because it might be moved, changed or completely disappear.

**Comment by didactic-drunk** [comment]
1. Is there a clear benefit to having incompatible API's?
2. I'm experimenting concurrent safe data structures.  Some of these may be included in future PR's and maybe integrated in to crystal so using `SpinLock` is appropriate.  If not accepted they'll stay in [concurrent.cr](https://github.com/didactic-drunk/concurrent.cr) still using internal API's with me maintaining them.
