### ISSUE TITLE
Conditional compilation in `src/crystal/system/unix/time.cr` doesn't work.

### ISSUE THREAD

**Issue by kubo** [crystal-lang/crystal#9394]
The least three digits of nanosecond of `Time.utc` are all zero on x86-64-linux.

```shell
$ ./bin/crystal --version
Using compiled compiler at .build/crystal
Crystal 0.35.0-dev [f584ff6] (2020-05-29)

LLVM: 8.0.0
Default target: x86_64-pc-linux-gnu
$ ./bin/crystal eval "p Time.utc"
Using compiled compiler at .build/crystal
2020-06-01 02:56:29.493280000 UTC
$ ./bin/crystal eval "p Time.utc"
Using compiled compiler at .build/crystal
2020-06-01 02:56:31.763072000 UTC
$ ./bin/crystal eval "p Time.utc"
Using compiled compiler at .build/crystal
2020-06-01 02:56:34.001279000 UTC
$ ./bin/crystal eval "p Time.utc"
Using compiled compiler at .build/crystal
2020-06-01 02:56:36.310078000 UTC
```
`Time.utc` uses [`Crystal::System::Time.compute_utc_seconds_and_nanoseconds`](https://github.com/crystal-lang/crystal/blob/0.34.0/src/crystal/system/unix/time.cr#L16-L26), which uses `clock_gettime`, whose precision is nanosecond,  if it is in `LibC`. Otherwise, `gettimeofday`, whose precision is `microsecond`. The above results imply that `Time.utc` uses `gettimeofday` even though `clock_gettime` is declared [here](https://github.com/crystal-lang/crystal/blob/0.34.0/src/lib_c/x86_64-linux-gnu/c/time.cr#L26) on x86_64-linux.

When [`{% if LibC.methods.includes?("clock_gettime".id) %}`](https://github.com/crystal-lang/crystal/blob/0.34.0/src/crystal/system/unix/time.cr#L17) is changed to `{% if true %}`, `Time.utc` uses `clock_gettime` and the least three digits of nanosecond are not zero as follows.
```shell
$ ./bin/crystal eval "p Time.utc"
Using compiled compiler at .build/crystal
2020-06-01 03:05:26.132033413 UTC
$ ./bin/crystal eval "p Time.utc"
Using compiled compiler at .build/crystal
2020-06-01 03:05:28.468147124 UTC
$ ./bin/crystal eval "p Time.utc"
Using compiled compiler at .build/crystal
2020-06-01 03:05:30.466486498 UTC
```

I guess that the conditional compilation doesn't work.

**Comment by jhass** [comment]
It seems like `LibC.methods` is empty: https://carc.in/#/r/96wg which kinda makes sense given it's not methods, at least not instance methods, but functions?  Idk. We should expose some macro method to make this query possible.

**Comment by asterite** [comment]
The easiest thing to do here is to have each `LibC` define a constant `HAS_CLOCK_GETTIME` and use that on the call site.

**Comment by asterite** [comment]
That is, until we fix the macro issue. Since it's just internal stuff, it doesn't matter. In fact, I think I prefer to use the constant because it's faster to check and it's also clearer.

**Comment by straight-shoota** [comment]
> it's also clearer.

How is an additional, not directly related constant clearer than simplified `if defined?(method); call method; else call other_method`?

**Comment by asterite** [comment]
@jhass Try doing that inside a method

**Comment by jhass** [comment]
oh, well that's quite a pitfall.

**Comment by asterite** [comment]
Yeah, I think there's a second pass in the compiler where type of things are checked, and because `fun`s are checked their type need to be there before adding them.

Maybe an improvement for later, maybe it can be done in another way.

Macros inside and outside methods usually work in a different way. If you ask for `subclasses`, inside a method you will always get the best answer, but outside a method the information might still be incomplete. Same goes for `methods`.

**Comment by asterite** [comment]
That's also why I'm hesitant about providing this information at compile-time, because it's not accurate. I prefer to remove all of this functionality if there's no way it can be fixed. That's why have `HAS_CLOCK_GETTIME` in my mind is simpler.

**Comment by bcardiff** [comment]
I'm a bit lost. So #9407 does not fix anything, right? If it does fix something the difference between `LibC.methods.includes?` / `LibC.has_method?` is disturbing at least.

**Comment by asterite** [comment]
@bcardiff `LibC.methods` returns `Array(Def)`, not `Array(String)`. That's the bug. An `Array(Def)` can never include a String.

**Comment by asterite** [comment]
Summary:
- The `methods` macro method doesn't work well outside of methods
- `LibC.methods.includes?(String)` is wrong because `LibC.methods` is `Array(Def)`
- Using `LibC.has_method?(String)` fixes the issue, and the macro also runs inside a method so it's safe

**Comment by bcardiff** [comment]
Great. Thanks for the clarification!

**Comment by asterite** [comment]
That said, I do think `LibC.methods.includes?` looks like it would work, specially because `methods` in Ruby returns an array of symbols...
