### ISSUE TITLE
RFC: INI parser yielding line number

### ISSUE THREAD

**Issue by j8r** [crystal-lang/crystal#9397]
## Context

I would like to make something similar to an hypothetical `INI::Serializable`, which will use the stdlib to parse an INI IO/String and set instance variable accordingly.

`INI.parse` returns a `Hash(String, Hash(String, String))`, which allows to do more or less what I want, except two things that can be better:
- The line number, is of course not present on a Hash. Even if there are key indexes, they don't tell the exact line where the section/key is on the INI file.
- Less an issue: an intermediate Hash is created, which is not very efficient.

The line number is useful to raise an exception to the user, with as information the invalid key and its line.

## Proposals

Yielding each section, key, value and number is not possible because empty sections can exist.

A simple pull parser can be an option, or having a `INI.parse` which can yield a `Section | Key` union object (a line can either be a section declaration or a key/value).

## Additional notes

I think `INI.build` is fine, because it accepts any object which implements `each`, with values that also implements `#each`.
One little issue is that the main object has also to implement `#[]`, to check if there is a empty section at first. It can be solved by using `is_a? Hash`.

**Comment by asterite** [comment]
My personal preference: remove `INI` from the standard library. It's an old format that isn't used a lot these days, maybe for really old projects (I can't remember using it in the last 10 years of my life).

Then shards can provide this functionality and they can add serializes, line numbers and whatnot.

**Comment by asterite** [comment]
Also note that when you parse JSON or YAML, you don't get line numbers either. Pull parsers do provide this information, so maybe there should be an INI::PullParser for this use case. But parsing INI is incredibly easy to do, so you could just do it yourself if you need that.

**Comment by jhass** [comment]
Also it might be worth to show [TOML](https://github.com/crystal-community/toml.cr) some love which is essentially a well defined superset of INI.

**Comment by asterite** [comment]
Here's what I'll do: I'll remove my comments, and instead put 👎 and 😕 to this proposal.

**Comment by j8r** [comment]
INI is very widely used for configuration, where JSON is considered not readable enough and YAML too complicated.
Examples of applications using it: Gitea, Minetest, PHP.

A **lot** of Linux applications are using it for configuration (as `.conf` or `.ini`) in `$XDG_CONFIG_HOME` and in `/etc`: VLC, Geany, Sane, LXQt.

A lot of languages have it in their stdlib.

It is ok for me to propose a `INI::PullParser` PR.

**Comment by j8r** [comment]
I will implement a custom parser in https://github.com/j8r/crystalizer to fit the needs.
