### ISSUE TITLE
Reading from IO.pipe blocks indefinitely after Process ends

### ISSUE THREAD

**Issue by DougTy** [crystal-lang/crystal#9404]
I'm trying to read the output of a process created with Process.new in realtime, but when the process ends, reading stdout from the IO.pipe Reader blocks execution indefinitely and I'm unable to handle the process exiting or anything afterwards.

Here's some minimal code that will hopefully demonstrate my issue.
Child process must be compiled first.

**parent.cr**
```crystal
reader, writer = IO.pipe read_blocking: false, write_blocking: false
process = Process.new "./child", output: writer
loop do
	puts "LOOP"
	if process.terminated?
		puts "BREAK"
		break
	end

	puts "before read"
	line = reader.gets  # locks up here
	puts "after read"
	if line == nil
		puts "BREAK"
		break
	end

	puts line
end
puts "ENDED"

```

**child.cr**
```crystal
0.upto(10) do
	sleep 100.milliseconds
	puts( " -> test" )
end

puts( " -> close" )
```

The parent process correctly prints all child process output, including "closed", and the child process exits and is no longer visible in `ps`. However, "ENDED" is never reached, and the last thing seen in the output is "before read". The parent process stays open just waiting.

This occurs regardless of the state of read_blocking and write_blocking. I've also tried this with a buffer to the same result:
```crystal
buf = Bytes.new(1000)
reader.read(buf)  # freezes here too
```
Removing any kind of `gets` or `reader.read` allows the code to continue executing after the process ends and "ENDED" is reached -- though without getting any of its output in the parent.

.
System info:
> Distro: Arch
> Crystal 0.34.0 (2020-04-12)
> LLVM: 10.0.0
> Default target: x86_64-pc-linux-gnu

Files compiled/run with:
> crystal build child.cr
> crystal run parent.cr

(no multithreading)

Perhaps I'm just misunderstanding something and there's an easy fix.
Thank you for your time.

**Comment by pebauer68** [comment]
Try to **spawn a fiber** beginning with line = reader.gets and put this code part in its own loop.

**Comment by DougTy** [comment]
Thanks, this gives me the desired effect:
```crystal
reader, writer = IO.pipe
process = Process.new "./child", output: writer

def read_thread( reader )
	loop do
		line = reader.gets
		puts line
	end
end

spawn read_thread reader
process.wait
puts "ENDED"

```
.

**However**, I've discovered some strange behaviour. If I use a `loop do` again (even without the reader at all), I can't break out of it with `if process.terminated?` unless I print it out first.

```crystal
reader, writer = IO.pipe
process = Process.new "./child", output: writer

loop do
	puts process.terminated?  # if this line is commented out, the loop never breaks
	if process.terminated?
		puts "BREAK"
		break
	end
end

puts "ENDED"
```

This also happens if I simply change the `loop do` to `until process.terminated?`
```crystal
until process.terminated? 
	puts process.terminated?  # if this line is commented out, the loop never breaks
end
```

Why is this? Is it a side effect of loop optimization?
Is there any way to work around this, or is the fiber method the only way to achieve this?

**Comment by pebauer68** [comment]
This looks like a "busy" loop. Have you tried a sleep 0.1 instead of the puts ?

**Comment by jhass** [comment]
Or `-Dpreview_mt` :) Yes, `process.terminated?` never blocks (I'm not sure it even calls `waitpid`) thus the pipe reader fiber never gets to run, thus the process is blocked on nobody reading its output.  `puts` blocks the main fiber giving the pipe reader a chance to take the stage  :)

**Comment by DougTy** [comment]
Thanks, adding `sleep 0` works, and makes sense for single threaded programs.
But I'm still a bit confused with multithreading.

```crystal
reader, writer = IO.pipe
process = Process.new "./child", output: writer

stop = false
spawn do sleep 2; stop = true end

loop do
	#sleep 0
	#if process.terminated?
	if stop
		puts "BREAK"
		break
	end
end

puts "ENDED"
```

If I turn `-Dpreview_mt` on:

With `sleep` commented out and `if stop` used as the break condition, it works.
If I use `if process.terminated?` as the break condition, I need the sleep or else it never breaks.

Is this a limitation of the multithreading scheduler, or is there something funky going on with Process when multithreading is turned on? Or am I just completely misunderstanding how it works? For comparison's sake, writing the same code in Go, I don't need to use any sleeps.

**Comment by jhass** [comment]
Mmh, it looks like `terminated?` checks whether we already got the `SIGCHILD` notification that the child process died. However this notification is processed in a separate fiber. If we never block the main fiber, this notification never gets processed I guess.

**Comment by pebauer68** [comment]
Have a look at your CPU load, would be interesting without/with the sleep 0, sleep 0.1.

**Comment by HankAnderson** [comment]
See my comment here: https://github.com/crystal-lang/crystal/issues/9405#issuecomment-637516495

You need to close the writer pipe so the reader pipe can finish.

**Comment by DougTy** [comment]
I can't use `Process.run` as I need to check output in realtime, not just once the process has ended, and I can't close the writer pipe manually on `process.terminated?` if it's hanging when I check for it. With `sleep 0` in my loop to allow me to correctly read `process.terminated?`, closing the writer pipe doesn't seem to be necessary.

@pebauer68 `sleep 0` and no sleep max out a CPU core (6% total), while `sleep 0.1` and higher makes it below 1% total usage

.
Solutions, to sum it up:
1. Spawn a fiber just for reading: https://github.com/crystal-lang/crystal/issues/9404#issuecomment-637318801 (with or without MT)
2. When not using MT, add `sleep 0` in the loop to avoid busy loop 
3. If using MT, `sleep 0` must still be added https://github.com/crystal-lang/crystal/issues/9404#issuecomment-637344174 to workaround MT quirks with Process: https://github.com/crystal-lang/crystal/issues/9404#issuecomment-637346109

**Comment by jhass** [comment]
> I can't use `Process.run` as I need to check output in realtime, not just once the process has ended

This is what the block overload of `Process.run` is for, as Hank demonstrated.

**Comment by DougTy** [comment]
> > I can't use `Process.run` as I need to check output in realtime, not just once the process has ended
> 
> This is what the block overload of `Process.run` is for, as Hank demonstrated.

Ahh, that's much simpler. My mistake, I thought that would only run once it was complete.
