### ISSUE TITLE
Documentation of RemoteAddressType for HTTP::Request#remote_address

### ISSUE THREAD

**Issue by z64** [crystal-lang/crystal#9452]
In https://github.com/crystal-lang/crystal/pull/9210, the return value of this method is now the *private* alias `RemoteAddressType`. The rendered documentation now presents an unknown, undocumented type.

![image](https://user-images.githubusercontent.com/6119032/84208638-3206d380-aa82-11ea-9488-88928be402d9.png)

Reading the PR, this doesn't look like it was a consideration. Leaking the name of the private type doesn't seem like the best situation for users discovery - can this be improved? Perhaps `RemoteAddressType` can stay private like this, but I think its platform variants should at least be enumerated in the documentation.

I think there are other precedents for this sort of platform aliases, but I can't think of them right now...

**Comment by asterite** [comment]
The solution is to avoid using an alias.

**Comment by straight-shoota** [comment]
Stdlib APIs are supposed to be platform independent. That includes return types must not be different depending on the platform. This should just return nil on win32 for now.
