### ISSUE TITLE
error: linker  OpenSSL::BIO::CRYSTAL

### ISSUE THREAD

**Issue by lodenos** [crystal-lang/crystal#9477]
Hello, since I tried to migrate to Crystal 0.35.0 I have problems popping up everywhere. I have this type of error that I have a hard time understanding, I don't know enough about the internal workings of Crystal. I uninstall crystal to reinstall, delete the cache, reinstall my dependence which bind mongodb source -> https://github.com/kalinon/mongo.cr. I know that in the release note it is written (breaking-change) Cleanup Digest and OpenSSL :: Digest. (# 8426, thanks @ didactic-drunk) I still don't know if the problem will come from there.
```
Undefined symbols for architecture x86_64:
  "_BIO_get_data", referenced from:
      _*OpenSSL::BIO::get_data<Pointer(LibCrypto::Bio)>:Pointer(Void) in O-penS-S-L-5858B-I-O-.o
  "_BIO_meth_new", referenced from:
      _~OpenSSL::BIO::CRYSTAL_BIO:init in _main.o
  "_BIO_meth_set_create", referenced from:
      _~OpenSSL::BIO::CRYSTAL_BIO:init in _main.o
  "_BIO_meth_set_ctrl", referenced from:
      _~OpenSSL::BIO::CRYSTAL_BIO:init in _main.o
  "_BIO_meth_set_destroy", referenced from:
      _~OpenSSL::BIO::CRYSTAL_BIO:init in _main.o
  "_BIO_meth_set_read_ex", referenced from:
      _~OpenSSL::BIO::CRYSTAL_BIO:init in _main.o
  "_BIO_meth_set_write_ex", referenced from:
      _~OpenSSL::BIO::CRYSTAL_BIO:init in _main.o
  "_BIO_set_data", referenced from:
      _*OpenSSL::BIO::set_data<Pointer(LibCrypto::Bio), Pointer(Void)>:Nil in O-penS-S-L-5858B-I-O-.o
  "_BIO_set_init", referenced from:
      _~procProc(Pointer(LibCrypto::Bio), Int32)@/usr/local/Cellar/crystal/0.35.0/src/openssl/bio.cr:67 in _main.o
  "_BIO_set_shutdown", referenced from:
      _~procProc(Pointer(LibCrypto::Bio), Int32)@/usr/local/Cellar/crystal/0.35.0/src/openssl/bio.cr:67 in _main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc "${@}" -o /Users/lodenos/.cache/crystal/crystal-run-main.tmp  -rdynamic -L/usr/local/Cellar/crystal/0.35.0/embedded/lib -L/usr/lib -L/usr/local/lib -lmongoc-1.0 -lbson-1.0 -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -lpcre -lgc -lpthread /usr/local/Cellar/crystal/0.35.0/src/ext/libcrystal.a -L/usr/local/Cellar/libevent/2.1.11_1/lib -levent -liconv -ldl`
```

**Comment by jhass** [comment]
I see you're on macOS. Can you try:

```
brew install openssl@1.1
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

**Comment by scriptmaster** [comment]
@jhass I see the same problem on my mac.  I am new to crystal (only an hour since I stumbled upon crystal-lang):

I tried hello_world.cr works fine. and `crystal build hello_world.cr` also created a mac exec with no errors. However, when
I tried server.cr - this gives similar run/build error on mac.

brew installed openssl@1.1, re-installed per warning below, exported PKG_CONFIG_PATH etc. Same error.

```
Warning: openssl@1.1 1.1.1g is already installed and up-to-date
To reinstall 1.1.1g, run `brew reinstall openssl@1.1`
192:crystal1 admin$ export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
192:crystal1 admin$ 
192:crystal1 admin$ crystal server.cr 
Undefined symbols for architecture x86_64:
  "_BIO_get_data", referenced from:
      _*OpenSSL::BIO::get_data<Pointer(LibCrypto::Bio)>:Pointer(Void) in O-penS-S-L-5858B-I-O-.o
  "_BIO_meth_new", referenced from:
      _~OpenSSL::BIO::CRYSTAL_BIO:init in _main.o
  "_BIO_meth_set_create", referenced from:
      _~OpenSSL::BIO::CRYSTAL_BIO:init in _main.o
  "_BIO_meth_set_ctrl", referenced from:
      _~OpenSSL::BIO::CRYSTAL_BIO:init in _main.o
  "_BIO_meth_set_destroy", referenced from:
      _~OpenSSL::BIO::CRYSTAL_BIO:init in _main.o
  "_BIO_meth_set_read_ex", referenced from:
      _~OpenSSL::BIO::CRYSTAL_BIO:init in _main.o
  "_BIO_meth_set_write_ex", referenced from:
      _~OpenSSL::BIO::CRYSTAL_BIO:init in _main.o
  "_BIO_set_data", referenced from:
      _*OpenSSL::BIO::set_data<Pointer(LibCrypto::Bio), Pointer(Void)>:Nil in O-penS-S-L-5858B-I-O-.o
  "_BIO_set_init", referenced from:
      _~procProc(Pointer(LibCrypto::Bio), Int32)@/usr/local/Cellar/crystal/0.35.1/src/openssl/bio.cr:67 in _main.o
  "_BIO_set_shutdown", referenced from:
      _~procProc(Pointer(LibCrypto::Bio), Int32)@/usr/local/Cellar/crystal/0.35.1/src/openssl/bio.cr:67 in _main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc "${@}" -o /Users/admin/.cache/crystal/crystal-run-server.tmp  -rdynamic -L/usr/local/Cellar/crystal/0.35.1/embedded/lib -L/usr/lib -L/usr/local/lib -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -lpcre -lgc -lpthread /usr/local/Cellar/crystal/0.35.1/src/ext/libcrystal.a -L/usr/local/Cellar/libevent/2.1.11_1/lib -levent -liconv -ldl`
192:crystal1 admin$ 

```

**Comment by waj** [comment]
@scriptmaster did you try uninstalling `openssl` and installing it again? You might have to uninstall more than once in case you have installed several versions. You can check with `brew info | grep openssl`.
I've seen a similar error happening because at some point Homebrew renamed some openssl formula or something like that.

Also, could you share the output of `pkg-config --libs libssl`?

**Comment by scriptmaster** [comment]
@waj will try to uninstall several times and install openssl again.

```
$ pkg-config --libs libssl
-L/usr/local/Cellar/openssl@1.1/1.1.1g/lib -lssl

$ crystal server.cr 
Undefined symbols for architecture x86_64:
  "_BIO_get_data", referenced from:
      _*OpenSSL::BIO::get_data<Pointer(LibCrypto::Bio)>:Pointer(Void) in O-penS-S-L-5858B-I-O-.o
```

**Comment by scriptmaster** [comment]
Now i installed crystal 0.34.0 with `asdf install crystal 0.34.0` https://github.com/asdf-community/asdf-crystal

crystal 0.34.0 works with no errors on ubuntu, tried on mac too - works. 0.35.1 needs more testing with kemal and openssl, imho.

**Comment by scriptmaster** [comment]
Holy!! crystal 0.34.0 built kemal server is running at 0.3% of overall Mem on a commodity server.
nginx workers at 0.5% Mem
php-fpm 1.5% Mem
C# dotnet compiled 1.1%
dotnet run dev 2.1%
node 3.0%
mysqld 5.2%
I am amazed this is lighter than dotnet-core, my present choice in production for many apps :|

This will be a big change for me in future. I am yet to run some tests and see to memory pressure over time. dotnet-core web app has been running for a while (days) and my experience in .NET overall = 14+ years. OMG !

**Comment by jhass** [comment]
Very weird, the `pkg-config` output looks correct. Maybe a version mixup somewhere? What's `pkg-config --libs libcrypto` and `echo $LIBRARY_PATH`?

**Comment by rameshkt** [comment]
Came across same problem:
brew info | grep openssl is null
pkg-config --libs libcrypto = -L/usr/local/Cellar/openssl@1.1/1.1.1g/lib -lcrypto
echo $LIBRARY_PATH is null

**Comment by asterite** [comment]
What's the output of `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` ?

**Comment by lodenos** [comment]
@asterite we have this line when I put this line on my term
`command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'`
`-L/usr/local/Cellar/openssl@1.1/1.1.1g/lib -lssl`

**Comment by s0kil** [comment]
@asterite The output from `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` is `-lssl -lcrypto`

**Comment by asterite** [comment]
Can you show the output of this command?

```bash
$ nm -gU /usr/local/Cellar/openssl@1.1/1.1.1g/lib/libcrypto.dylib | grep BIO_get_data
```

**Comment by lodenos** [comment]
@asterite yes it's `000000000002b837 T _BIO_get_data`

**Comment by s0kil** [comment]
Also getting the output `000000000002b837 T _BIO_get_data`

**Comment by asterite** [comment]
Well, the symbol is there. So I don't understand why it's not linking properly. It does work well for me on mac, using openssl@1.1 from homebrew.

**Comment by rameshkt** [comment]
-L/usr/local/Cellar/openssl@1.1/1.1.1g/lib -lssl
and
000000000002b837 T _BIO_get_data
repectively

**Comment by waj** [comment]
Interesting that all of you have the symbol located at the address `000000000002b837`. Mine is at `0000000000024cd8`. Not that it matters, but that means we probably have different macOS versions, so Homebrew is installing different binaries. I'm using the latest Catalina 10.15.5. Still don't know why that would be affecting anything, but just adding some info to bisect the problem.

**Comment by lodenos** [comment]
My version is `10.13.6 `

**Comment by asterite** [comment]
I also have it on `0000000000024cd8`

**Comment by Sija** [comment]
fwiw, I'm getting `0000000000024f68 T _BIO_get_data` on macOS `10.14.6`

**Comment by lodenos** [comment]
But it's so weird because with the 0.34.0 everything it's works and with the latest version 0.35.0 & 0.35.1 completly broken

**Comment by waj** [comment]
Just guessing, but maybe something related with https://github.com/crystal-lang/crystal/pull/8972 combined with older versions of macOS. Unfortunately all the computers I have at hand now are already upgraded to Catalina. I'm trying to build a VM with High Sierra so I can try to reproduce the issue.

**Comment by waj** [comment]
I tested on High Sierra and obtained the same error. Effectively this started to happen after #8972 because now CRYSTAL_LIBRARY_PATH has more precedence than paths obtained from `pkg-config` and High Sierra has versions of `libssl` and `libcrypto` that cannot be used for Crystal. I'm not sure that behaviour is correct, but for now we can fix it by removing `/usr/lib` from that variable. The directory is still checked by the linker anyway after any other option has failed. 

I just sent a PR to Homebrew: https://github.com/Homebrew/homebrew-core/pull/57255. In the meantime, manually removing `/usr/lib` from `/usr/local/bin/crystal` should fix the issue.

**Comment by rameshkt** [comment]
Thank you. Tested and working

**Comment by lodenos** [comment]
@waj Thx it's works just `export CRYSTAL_LIBRARY_PATH="${CRYSTAL_LIBRARY_PATH:+$CRYSTAL_LIBRARY_PATH:}#{prefix/"embedded/lib"}:/usr/local/lib"` thx for your help 😄
