### ISSUE TITLE
typeof(instance variable) should not form a closure

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#9479]
Proc literals in class / struct / module scope that contain `typeof(@ivar)`, where `@ivar` is an instance variable, are counted as closures during compile time, meaning for example those procs cannot be passed to lib funs. The code

```crystal
lib A
  fun f(x : ->) : Void
end

class B
  @y = 1

  def g
    A.f(-> { typeof(@y) })
  end
end

B.new.g
```

fails on 0.35.0 (3c48f311f) with reason

```
In test.cr:13:7

 13 | B.new.g
            ^
Error: instantiating 'B#g()'


In test.cr:9:9

 9 | A.f(-> { typeof(@y) })
         ^
Error: can't send closure to C function (closured vars: @y)
```

even though `@y`'s contents are definitely not used and the proc does not affect `@y`'s type.

`offsetof(B, @y)` on the other hand works (perhaps because `typeof` accepts any expression whereas `offsetof` requires an instance variable).

**Comment by naqvis** [comment]
Isn't this expected behavior? Reference guide clearly states this.

> Note, however, that functions passed to C can't form closures. If the compiler detects at compile-time that a closure is being passed, an error will be issued:
> y = 2
> X.callback ->(x) { x + y } # Error: can't send closure to C function

**Comment by jhass** [comment]
Well, `typeof` is entirely evaluated at compile time and replaced with the types. So there's  no runtime dependency on the instance variable and thus no reason to form a closure.

**Comment by naqvis** [comment]
Per documentation, [typeof](https://crystal-lang.org/api/0.35.0/toplevel.html#typeof(*expression):Class-class-method) just analyzes but do not evaluate.
> The expressions passed as arguments to typeof do not evaluate. The compiler only analyzes their return type.

**Comment by jhass** [comment]
The arguments are not evaluated at runtime yes. The entire expression is still evaluated (= replaced with a value), just at compile time.
