### ISSUE TITLE
Regression in 0.35.0: WebSocketHandler

### ISSUE THREAD

**Issue by jwaldrip** [crystal-lang/crystal#9484]
As of 0.35.0 there is a regression within the WebSocketHandler. It seems as though the response gets successfully upgraded but the block is never invoked which means any attempt to write or listen to the WebSocket fails. Here is some example code to run to reproduce the issue. You can see that the `puts` in the block never gets invoked, even though the response got an upgrade request. This works on 0.34.0.

```crystal
require "http"

def mock_context(verb, path, host = "example.org", *, headers = {} of String => String, io = IO::Memory.new, body = nil)
  http_headers = HTTP::Headers.new
  headers.each { |k, v| http_headers[k] = v }
  http_headers["HOST"] = host
  request = HTTP::Request.new(verb.to_s.upcase, path, http_headers)
  request.body = body
  response = HTTP::Server::Response.new io
  HTTP::Server::Context.new(request, response)
end

def test_ws(router, path, host = "example.org")
  io = IO::Memory.new
  context = mock_context("GET", path, host, headers: {
    "Upgrade"               => "websocket",
    "Connection"            => "Upgrade",
    "Sec-WebSocket-Key"     => "dGhlIHNhbXBsZSBub25jZQ==",
    "Sec-WebSocket-Version" => "13",
  }, io: io)
  begin
    router.call context
    context.response.close
  rescue IO::Error
    # Raises because the IO:: Memory is empty
  end
  io.rewind
  {io, context}
end

handler = HTTP::WebSocketHandler.new do |ws, ctx|
  puts "block invoked"
  ws.send("Match")
end

io, context = test_ws(handler, "/")

assertion = "HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=\r\n\r\n\x81\u0005Match"

response = io.to_s
puts response
raise "Invalid Response" unless response == assertion
puts "OK"
```

**Comment by HankAnderson** [comment]
Websocket works just fine if you use it as you should: create an http server, pass the handler, etc.

The handler is now called in a deferred way, check https://github.com/crystal-lang/crystal/pull/9243

So your test is broken, the stdlib code is fine. To make it work in your test you need to do something else, but I don't have time to find out exactly what.

**Comment by HankAnderson** [comment]
Relying on internal implementation details is bad, like relying on the block of code being invoked immediately. The best way to test this is to actually create a server with that handler, then pass a request and check that something happened. Black-box tests are always the best.

**Comment by jwaldrip** [comment]
What is the best way to test these methods outside of an actual HTTP call? Are there examples of how how to do this?

**Comment by HankAnderson** [comment]
The way to test a websocket interaction is by not using websockets at all. You code high-level what events you get and what responses you want, and the only untested code that remains is linking those events and responses with the actual websocket.

**Comment by jwaldrip** [comment]
I was able to use the RequestProcessor directly to test. This works for now.
