### ISSUE TITLE
`HTTP::Server` reuses same fiber on `keep-alive`, bleeding `Log::Context` between requests

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#9487]
```cr
require "http/server"
require "log"

server = HTTP::Server.new do |context|
  Log.info { "before" }
  Log.context.set foo: "bar"
  Log.info { "after" }

  context.response.content_type = "text/plain"
  context.response.print "Hello world!"
end

address = server.bind_tcp 3000
puts "Listening on http://#{address}"
server.listen

# 2020-06-16T02:14:56.872305Z   INFO - before
# 2020-06-16T02:14:56.872361Z   INFO - after -- foo: "bar"
# 2020-06-16T02:14:58.566511Z   INFO - before -- foo: "bar"
# 2020-06-16T02:14:58.566591Z   INFO - after -- foo: "bar"
```

Reusing the fiber for performance makes sense, however it has some side effects, mainly `Log::Context` will now bleed between requests since the fiber, and the underlying data, wouldn't be reset as it would with a new fiber instance.

Given I imagine this is intentional, maybe we should just clear the fiber's context after the request has been finished?  Thus the new request would have an empty context.

**Comment by waj** [comment]
Yes, I was talking with @bcardiff about this same issue last Friday. The call to the handler in `HTTP::Server::RequestProcessor` should be surrounded with `Log.with_context` so any change to the context is reverted. It's just a reference save/restore, so it shouldn't have any noticeable performance impact.

Do you want to send a PR?
