### ISSUE TITLE
CRYSTAL_OPTS parsing is too naive

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#9509]
it tokenizes into arguments just by `split`ting the value, which beaks on things like  `CRYSTAL_OPTS="--link-flags='-la -lb'"`.

**Comment by bcardiff** [comment]
> We'd need to port this from Ruby: https://ruby-doc.org/stdlib-2.5.1/libdoc/shellwords/rdoc/Shellwords.html (or do something similar)
> https://github.com/crystal-lang/crystal/pull/8900#discussion_r391925011
