### ISSUE TITLE
can't convert string to [u|i]128: "string".to_[u|i]128

### ISSUE THREAD

**Issue by jzakiya** [crystal-lang/crystal#9516]
Using 0.35.1 on Linux

Have working code that can do: ``"244434867".to_u64``
but when I do either: ``"244434867".to_u128`` or ``"244434867".to_i128`` get error such as

``Error: undefined method 'to_i128' for String``

**Comment by jhass** [comment]
Yes,  128 bit  support is not (fully) implemented,  see #8313

**Comment by BlobCodes** [comment]
Fixed by #11245
