### ISSUE TITLE
URI#relativize should relativize host-relative paths

### ISSUE THREAD

**Issue by watzon** [crystal-lang/crystal#9521]
So idk if this is expected behavior or not, but I would expect `URI#relativize` to work slightly different than it does. Take this example:

```crystal
require "uri"
uri = URI.parse("https://crystal-lang.org/blog")
uri.relativize("/assets/stylesheet.css")
```

With current behavior the URI returned by the above `relativize` is still absolute (`/assets/stylesheet.css`). I would expect, however, for it to be relative to the given URL (`../assets/stylesheet.css`).

Is it possible we could modify this behavior? Or at least add some kind of boolean parameter to the `relativize` method allowing us to achieve this behavior?

**Comment by straight-shoota** [comment]
This works as expected. `https://crystal-lang.org/blog` is an absolute URI, `/assets/stylesheet.css` is a relative URI. They can never be relativized because their different scopes make them not directly comparable.

You can get the behaviour you want by first resolving the relative URI against the base to make it absolute:
```cr
require "uri"
uri = URI.parse("https://crystal-lang.org/blog")
uri.relativize(uri.resolve("/assets/stylesheet.css")) # => "../assets/stylesheet.css"
```

**Comment by watzon** [comment]
Hmm ok, good to know that it is at least possible. Thanks @straight-shoota!

**Comment by Sija** [comment]
> This works as expected. `https://crystal-lang.org/blog` is an absolute URI, `/assets/stylesheet.css` is a relative URI.

@straight-shoota `/assets/stylesheet.css` looks pretty absolute to me, i.e. starting with `/`

**Comment by straight-shoota** [comment]
It's an absolute path, but a relative URL without scheme and authoritiy.

**Comment by Sija** [comment]
relative _url_ 🤦 , you're of course right
