### ISSUE TITLE
C ABI: accepting a struct in a callback works wrong (indirect vs byval)

### ISSUE THREAD

**Issue by oprypin** [crystal-lang/crystal#9533]
[The following `fun` definition](https://gist.github.com/61a81c133961a90b6dc9156e0f89279d#file-test-cr) generates wrong receiving code in _x86_win64_ and _aarch64_ ABI:

```crystal
lib Lib
  struct Vec
    x : Int64
    y : Int64
    z : Int64
  end

  fun ccaller((Vec) ->)
end

fun callback(v : Lib::Vec)
  LibC.printf("%lld %lld %lld\n", v.x, v.y, v.z)
end

Lib.ccaller(->callback)
```

[This C code](https://gist.github.com/61a81c133961a90b6dc9156e0f89279d#file-test-c) calls the function with the struct `{1, 2, 3}`

```c
typedef struct Vec {
    long long x, y, z;
} Vec;

void ccaller(void (*func)(Vec)) {
    Vec v1 = {1, 2, 3};
    func(v1);
}
```

but the Crystal `callback` above receives some garbage (such as `673706932728 0 0`) instead.

---

This is actually a regression from #9520 [[code]](https://github.com/crystal-lang/crystal/pull/9520/files#diff-22a2ef24d41a844f5b4c90563f546aa6R15) and #9430 [[code]](https://github.com/crystal-lang/crystal/pull/9430/files#diff-cea1709956b4bb58c11c560075af3013R139), but I suppose those changes are still preferred because they fix the much more typical case. The changes are equivalent and cause this regression in exactly the same way.

---

For [this code](https://gist.github.com/61a81c133961a90b6dc9156e0f89279d#file-test-c), C clang [generates](https://gist.github.com/61a81c133961a90b6dc9156e0f89279d#file-print_ll-cmd) the following LLVM IR on Windows:

```ll
  %2 = alloca %struct.Vec, align 8

  call void @callback(%struct.Vec* %2)
--------
; Function Attrs: noinline nounwind optnone uwtable
define dso_local void @callback(%struct.Vec* %0) #1 {
  %2 = getelementptr inbounds %struct.Vec, %struct.Vec* %0, i32 0, i32 1
  %3 = load i64, i64* %2, align 8
  %4 = getelementptr inbounds %struct.Vec, %struct.Vec* %0, i32 0, i32 0
  %5 = load i64, i64* %4, align 8
  %6 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([11 x i8], [11 x i8]* @"??_C@_0L@EGEBKBBB@?$CFlld?5?$CFlld?6?$AA@", i64 0, i64 0), i64 %5, i64 %3)
  ret void
}
```

Crystal with `LLVM::Attribute::ByVal` used to generate this (which is very very close to good but just needs to drop the `byval` part):

```ll
  %v = alloca %"struct.Lib::Vec"

  call void @callback(%"struct.Lib::Vec"* byval %v)
--------
; Function Attrs: uwtable
define void @callback(%"struct.Lib::Vec"* byval %v) #0 {
entry:
  %0 = call i8* @.2A.String.23.to_unsafe.3A.Pointer.28.UInt8.29.(%String* bitcast ({ i32, i32, i32, [11 x i8] }* @"'%lld %lld\0A'" to %String*))
  %1 = getelementptr inbounds %"struct.Lib::Vec", %"struct.Lib::Vec"* %v, i32 0, i32 0
  %2 = load i64, i64* %1
  %3 = getelementptr inbounds %"struct.Lib::Vec", %"struct.Lib::Vec"* %v, i32 0, i32 1
  %4 = load i64, i64* %3
  %5 = call i32 (i8*, ...) @printf(i8* %0, i64 %2, i64 %4)
  ret void
}
```

Crystal with `nil` now generates this (in which the 1st part is good, that was what we "fixed" in the other PRs, but the receiver part adds an extra pointer, turning it into garbage):

```ll
  %v = alloca %"struct.Lib::Vec"

  call void @callback(%"struct.Lib::Vec"* %v)
--------
; Function Attrs: uwtable
define void @callback(%"struct.Lib::Vec"* %v) #0 {
alloca:
  %v1 = alloca %"struct.Lib::Vec"
  br label %entry

entry:                                            ; preds = %alloca
  %0 = bitcast %"struct.Lib::Vec"* %v1 to %"struct.Lib::Vec"**
  store %"struct.Lib::Vec"* %v, %"struct.Lib::Vec"** %0
  %1 = call i8* @.2A.String.23.to_unsafe.3A.Pointer.28.UInt8.29.(%String* bitcast ({ i32, i32, i32, [11 x i8] }* @"'%lld %lld\0A'" to %String*))
  %2 = getelementptr inbounds %"struct.Lib::Vec", %"struct.Lib::Vec"* %v1, i32 0, i32 0
  %3 = load i64, i64* %2
  %4 = getelementptr inbounds %"struct.Lib::Vec", %"struct.Lib::Vec"* %v1, i32 0, i32 1
  %5 = load i64, i64* %4
  %6 = call i32 (i8*, ...) @printf(i8* %1, i64 %3, i64 %5)
  ret void
}
```

---

It is quite apparent that in the current state Crystal &rarr; C calls need the `ArgType.indirect(t, nil)` behavior while C &rarr; Crystal calls need the `ArgType.indirect(t, LLVM::Attribute::ByVal)` behavior, and both are seemingly not possible to satisfy, without additional changes to code, my best guess is this part (but I haven't dug much farther):
https://github.com/crystal-lang/crystal/blob/02a2e6978e53f3bbaf363c32b9b511bbd6619ef2/src/compiler/crystal/codegen/fun.cr#L541-L547

---

Actually in the current state one doesn't even need the C part to reproduce the problem, Crystal just generates receiver code which doesn't match its own caller code:

```crystal
lib Lib
  struct Vec
    x : Int64
    y : Int64
    z : Int64
  end
end

fun callback(v : Lib::Vec)
  puts "#{v.x} #{v.y} #{v.z}"
end

v = Lib::Vec.new(x: 1, y: 2, z: 3)
callback(v)
```

---

To attempt to fix this, one can just try to get the generated IR to resemble in both cases what Clang does.

Doesn't necessarily need to run on Windows or ARM64, you can get the IR like this:

```shell
crystal build --cross-compile --target x86_64-pc-windows-msvc --prelude=empty --no-debug --emit=llvm-ir test.cr
```

(drop the `puts` code to be able to take advantage of `prelude=empty`).

---

[Relevant chat with @jhass](https://gitter.im/crystal-lang/crystal?at=5ef064d2e0e5673398c929b1)

**Comment by oprypin** [comment]
#9534 can serve as another way to repro this case

**Comment by Hadeweka** [comment]
Is there any way to circumwent this bug somehow?

My shard is basically useless on Windows at the current state (if built using the MSVC dev environment), since it depends heavily on C callbacks.
Sadly my knowledge about LLVM is rather limited, so I am unable to fix the problem by myself.
