### ISSUE TITLE
RFC: namespace parent for TypeNode

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#9540]
## Problem
There is no native way to access the parent namespace for a macro.  When trying to modify the parent namespace I you can use string manipulation but it would be nice to have a more consistent way.

In Crystal you can currently use String manipulation.
```crystal
class Foo
  class Bar
    macro inherited
      def {{@type.superclass.name.split("::")[-2].id}}.{{@type.name.downcase.id}}
        "here"
      end
    end
  end
end

class Baz < Foo::Bar
end

p Foo.baz
``` 
output:
```bash
% crystal tmp.cr
here
```

Ruby you can do this using `Module#nesting`
```ruby
class Foo
  class Bar
    def self.inherited(base)
      Module.nesting[-1].class.define_method(base.to_s.downcase.to_sym) { puts "here" }
    end
  end
end

class Baz < Foo::Bar
end

puts Foo.baz
```
output:
```bash
% ruby tmp.rb 
here
```

## Solution
Have a `TypeNode` method that can access the nesting when using lifestyle hooks.  This could return the different levels of nesting that you can use in metaprogramming.

```crystal
class Foo
  class Bar
    macro inherited
      def {{@type.nesting[-2].id}}.{{@type.name.downcase.id}}
        "here"
      end
    end
  end
end

class Baz < Foo::Bar
end

puts Foo.baz
```

**Comment by Blacksmoke16** [comment]
An alternate solution would be to define like `TypeNode#path`, which would allow you to accomplish something similar via [Path#names](https://crystal-lang.org/api/Crystal/Macros/Path.html#names:ArrayLiteral(MacroId)-instance-method).
