### ISSUE TITLE
File.touch on 32 bits gives overflow error but maybe it should give a better error message

### ISSUE THREAD

**Issue by lugia-kun** [crystal-lang/crystal#9542]
`Crystal::System::File#to_timeval` raises OverflowError for the specific date on i386 system:
```crystal
File.touch "shard.lock", Time.utc(1900, 1, 1)
```
```
[momonga@elma ~/crystal i686]$ CC="gcc -fuse-ld=lld" bin/crystal eval 'File.touch "shard.lock", Time.utc(1900, 1, 1)'
Using compiled compiler at .build/crystal
Unhandled exception: Arithmetic overflow (OverflowError)
  from src/int.cr:849:11 in 'new'
  from src/crystal/system/unix/file.cr:152:16 in 'to_timeval'
  from src/crystal/system/unix/file.cr:142:19 in 'utime'
  from src/file.cr:780:5 in 'utime'
  from src/file.cr:789:5 in 'touch'
  from ../../../eval:1:1 in '__crystal_main'
  from src/crystal/main.cr:105:5 in 'main_user_code'
  from src/crystal/main.cr:91:7 in 'main'
  from src/crystal/main.cr:114:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```

## crystal -v

```
Crystal 1.0.0-dev [476486e0a] (2020-06-23)

LLVM: 10.0.0
Default target: i386-pc-linux-gnu
```

**Comment by jhass** [comment]
Maybe related to #9297 ?

**Comment by asterite** [comment]
@lugia-kun  Can you actually set a file to have that date/time in a 32 bits enviroment?

Can you try it in other languages?

**Comment by asterite** [comment]
From https://en.wikipedia.org/wiki/Unix_time#:~:text=Being%2032%20bits%20means%20that,19%20this%20representation%20will%20overflow.

> Being 32 bits means that it covers a range of about 136 years in total. The minimum representable date is Friday 1901-12-13, and the maximum representable date is Tuesday 2038-01-19. 

This is not a bug. Maybe "overflow error" is unexpected, but you'll get an error anywhere. Or maybe overflow is fine, because it actually overflows (or underflows) the minimum allowed time in 32 bits.

**Comment by kubo** [comment]
This is caused by the limitation of 32-bit unix time.

In https://en.wikipedia.org/wiki/Unix_time:
> Being 32 bits means that it covers a range of about 136 years in total. The minimum representable date is Friday 1901-12-13, and the maximum representable date is Tuesday 2038-01-19. 

`Time.utc(1900, 1, 1)` is out of the range. There are no ways to use 64-bit unix time in i386-linux programs.

It may be better to change the error message from "Arithmetic overflow" to "Out of 32-bit unix time range."

**Comment by jhass** [comment]
@asterite I feel like that's ignoring the whole LFS topic?

**Comment by asterite** [comment]
@jhass How is that related? LFS seems to be about large file support. This is about time limits in 32 bits.

**Comment by jhass** [comment]
Mh, I guess unfortunately. I was remembering some stat changes in #9478 but looks  like they don't touch any of the time members.

**Comment by lugia-kun** [comment]
> This is caused by the limitation of 32-bit unix time.
> 
> In https://en.wikipedia.org/wiki/Unix_time:
> 
> > Being 32 bits means that it covers a range of about 136 years in total. The minimum representable date is Friday 1901-12-13, and the maximum representable date is Tuesday 2038-01-19.
> 
> `Time.utc(1900, 1, 1)` is out of the range. There are no ways to use 64-bit unix time in i386-linux programs.
> 
> It may be better to change the error message from "Arithmetic overflow" to "Out of 32-bit unix time range."

I did not know that fact. I confirmed that `touch` command also rejects the dates before 13 Dec 1901.

I just encountered this error while running the spec of shards on i386 environment (but still using x86_64 kernel):
https://github.com/crystal-lang/shards/blob/3b7d490d504c54d36d218ae5ca1f92f09bf9f4fe/spec/integration/install_spec.cr#L422

**Comment by jhass** [comment]
Gladly send a PR to correct the spec there :)

**Comment by jhass** [comment]
So, actually anything left to do here?

**Comment by asterite** [comment]
No.
