### ISSUE TITLE
Provide nightlies (Was: Travis.yml for Crystal HEAD)

### ISSUE THREAD

**Issue by Codcore** [crystal-lang/crystal#956]
Is there a working example of ```travis.yml``` for Crystal HEAD? I tried next one, but it doesn't work :
```
install:
  - git clone https://github.com/manastech/crystal.git
  - cd crystal
  - make
script:
  - bin/crystal deps
  - bin/crystal spec
```

**Comment by rhysd** [comment]
I think you can refer [the .travis.yml of crystal itself](https://github.com/manastech/crystal/blob/master/.travis.yml).  You need to install the stable version of crystal at first to bootstrap the build

**Comment by Codcore** [comment]
@rhysd I tried this, [but got build errors](https://travis-ci.org/Codcore/Amethyst/builds/70202172): 
```
before_install: |
  curl http://dist.crystal-lang.org/apt/setup.sh | sudo bash
  sudo apt-get -q update
install:
  - sudo apt-get install crystal
  - crystal deps
  - git clone https://github.com/manastech/crystal.git
  - cd crystal
  - make
script:
  - bin/crystal deps
  - bin/crystal spec
```

**Comment by jhass** [comment]
Yeah, you'll need the whole LLVM downloading stuff in order to compile the compiler.

**Comment by asterite** [comment]
@Codcore What do you want this for?

**Comment by Codcore** [comment]
@asterite I create [separate branch of Amethyst](https://github.com/Codcore/Amethyst/tree/crystal-head) which using Crystal Head to test new features.

**Comment by Codcore** [comment]
@asterite @jhass @rhysd following travis.yml worked:
```
before_install: |
  curl http://dist.crystal-lang.org/apt/setup.sh | sudo bash
  sudo apt-get -q update
install:
  - sudo apt-get install libgmp3-dev crystal
  - sudo sed -i -e 's/.*LIBRARY_PATH.*/export LIBRARY_PATH=\"$INSTALL_DIR\/embedded\/lib${LIBRARY_PATH:\+:$LIBRARY_PATH}\"/' /opt/crystal/bin/crystal
  - curl "http://crystal-lang.s3.amazonaws.com/llvm/llvm-3.5.0-1-linux-x86_64.tar.gz" | tar xz -C /tmp
  - curl "http://crystal-lang.s3.amazonaws.com/pcl/libpcl-1.12-1-linux-x86_64.tar.gz" | tar xz -C /tmp
  - export LIBRARY_PATH=/opt/crystal/embedded/lib:/tmp/libpcl-1.12-1/lib
  - export PATH=/tmp/llvm-3.5.0-1/bin:$PATH
  - export CRYSTAL_CONFIG_VERSION=ci
  - export CRYSTAL_CACHE_DIR=/tmp/crystal
  - sudo apt-get install crystal
  - crystal deps
  - git clone https://github.com/manastech/crystal.git
  - cd crystal
  - make
  - cd ..
  - git clone -b crystal-head https://github.com/Codcore/Amethyst.git
  - cd Amethyst
script:
  - ../crystal/bin/crystal deps
  - ../crystal/bin/crystal spec
```

**Comment by Codcore** [comment]
Maybe add this example somewhere in wiki? I don't think that I'm only one who will need this. It is quite easy to figure out, but it took some time.

**Comment by will** [comment]
If on successful crystal builds on travis uploaded the binary to s3 (and the s3 bucket was fixed so ssl works), I think we'd be able to add crystal-head to the community travis support.

**Comment by Codcore** [comment]
@will yes, it would be cool. Anyway, we should ask @asterite what does he think.

**Comment by rhysd** [comment]
:+1:

Crystal is now on pre-alpha stage.  I think it is good practice to test apps with Crystal HEAD.
Is there any example to test apps with multiple languages on Travis?  If `crystal-head` is added, we would want to test apps with `crystal` and `crystal-head`.

If not possible to use multiple languages, it might better to add a key to specify version of crystal the same as [node.js](http://docs.travis-ci.com/user/languages/javascript-with-nodejs/).

**Comment by PragTob** [comment]
Has anyone asked travis yet to add a `crystal-head` ? :)

**Comment by jhass** [comment]
Crystal on Travis is community supported, we would "just" need to open a PR. What we would need to do this in a sane manner (that is without rebuilding crystal from head in every single build) are (official) nightly builds, ideally in a or the existing APT repository.

**Comment by jhass** [comment]
Closing this for now, will reopen if I can no longer provide the nightlies.
