### ISSUE TITLE
No auto-upcast for assignment of smaller ints to larger ones.

### ISSUE THREAD

**Issue by BrucePerens** [crystal-lang/crystal#9565]
```crystal
def i(int : Int64)
end
v = 1
i(v) # Won't compile.
i(1) # Will compile.
```
The language should probably support auto-upcast of smaller ints to larger ones. The larger type is guaranteed to hold the value of the smaller one. This results in awkward casts and constants, for example the use of `1i64` to force a constant to a width.

The same problem exists for Float64 = Float32, and for Float = Int where the exponent is large enough to contain the Int.

I think I have also seen this called _type promotion_.

**Comment by straight-shoota** [comment]
Yeah, I think this could technically work. However, it's more complicated with regard to return types. Especially considering assignment operators like `+=`. IIRC that's one reason why type promotion wasn't implemented.

**Comment by asterite** [comment]
I think this can actually be easy to implement, though it makes the language a bit more complex

**Comment by asterite** [comment]
@BrucePerens I don't think it's always safe to convert int to float. For example:

```crystal
p Int64::MAX # => 9223372036854775807
p Int64::MAX.to_f == 9223372036854775807.0 # => true
p Int64::MAX.to_f == 9223372036854775806.0 # =>  true
```

Note that the large float loses precision, and so a float value one less than Int64::MAX is also considered equal to Int6::MAX. So these implicit casts would be a bit unsound.

**Comment by BrucePerens** [comment]
From Oleh Pripin on the mailing list:

The [formula](https://fabiensanglard.net/floating_point_visually_explained/#MathJax-Element-2-Frame) for floating point numbers is

(-1)S · 2(E−127) · (1 + M ∕ 223)

1 bit S for the sign
8 bits E for the exponent
23 bits M for the mantissa

Example:
S = 0b0
E = 0b00000010 + 127 = 0b10000001
M = 0b10010010000111111011010

a = (-1)**0b0 * 2.0**(0b10000001 - 127) * (1 + 0b10010010000111111011010 / 2.0**23)

b = 0b0_10000001_10010010000111111011010_u32



p a                               # => 6.283185005187988

p pointerof(b).as(Float32*).value # => 6.283185005187988
Then, the formula for double precision floating point numbers is:

(-1)S · 2(E−1023) · (1 + M ∕ 252)

1 bit S for the sign
11 bits E for the exponent
52 bits M for the mantissa

Example:
S = 0b0
E = 0b000000000000010 + 1023 = 0b10000000001
M = 0b10010010000111111011010000000000000000000000000000000

a = (-1)**0b0 * 2.0**(0b10000000001 - 1023) * (1 + 0b1001001000011111101101000000000000000000000000000000 / 2.0**52)

b = 0b0_10000000001_1001001000011111101101000000000000000000000000000000_u64



p a                               # => 6.283185005187988

p pointerof(b).as(Float64*).value # => 6.283185005187988
Seeing as Float32 covers the ranges

S: 0..1
(E−127): -127..128
M: 0...223
and double-precision covers the ranges

S: 0..1
(E−1023): -1023..1024
M: 0...252
then everything possible within the ranges of Float32's components is representable within the ranges of Float64's components; and then every Float32 is directly representable as a Float64.

Now, there's a small gap in the reasoning because the two formulas aren't actually otherwise the same, as they have " ∕ 223" vs " ∕ 252". However, the examples, and also the non-mathematic way of showing the formula make it clearer

(-1)S × 2(E−127) × (1.M)

that is "one point M" (in binary).
For the prior examples that would be something like

1.100100100001111110110102 for Float32

and

1.10010010000111111011010000000000000000000000000000002 for Float64.

So the mantissa of Float32 is indeed always directly representable within Float64, just that you add the zeroes at the end rather than at the beginning.

Additionally worth noting that every integer in the range −253..253 is exactly representable in a Float64, so by the same logic it would be feasible to auto convert Int32 to Float64 as well. And umm... Int16 to Float32???

**Comment by BrucePerens** [comment]
Copied from the mailing list:

I am assuming nobody needs an integer proof. So, if I have this right, we can promote without loss:
* Signed integers to larger signed integers.
* Unsigned integers to larger unsigned integers.
* Unsigned integers to larger signed integers.
* Int8 and Int16, Uint8 and Uint16 to Float32 - Oleh wasn't so sure.
* Int32 and Uint32 to Float64.
* Float32 to Float64.

**Comment by BrucePerens** [comment]
Last month Asterite built patches to resolve this issue, and then removed them and some number of other patches he'd created, expressing complaints about his own coding quality. We all have such days and hopefully he's feeling better now.

I've since done a lot of Crystal coding, and my experience is that the presence of a platform-dependent Int does not solve the issue - indeed it makes it worse because its relationship to the sized-ints varies per platform. There are still a lot of reasons to use size-specified numeric data and inevitably different sizes will be used together with non-intuitive results at present.

**Comment by BrucePerens** [comment]
Can we please revisit this issue? IMO the addition of Int128 will make the problem even worse - there will be lots of need to type the width of constants, even ones like 0 that would fit in any of the types have to become 0i64 or 0i128, and constant expressions can overflow the types of the operands.

**Comment by beta-ziliani** [comment]
Hi @BrucePerens, I just want to mention that we talked about this in the Core Team meeting, and we agreed to push this issue forward. It will probably start as an opt-in flag.

**Comment by BrucePerens** [comment]
@beta-ziliani thanks very much!

**Comment by BrucePerens** [comment]
I ran into this ugly one today:
```crystal
if parameter_string
  o = parameter_string.to_i64
else
  o = 0
end
```
Type of `o` is `Int64|Int32`

What should be done for this? If anything.

**Comment by asterite** [comment]
I don't think there's anything that can be done in that case to improve the situation. You can use a type declaration for the variable, I guess.
