### ISSUE TITLE
Deprecation warnings are not show when compiler uses cached data.

### ISSUE THREAD

**Issue by hugopl** [crystal-lang/crystal#9575]
Compiler warnings about deprecated methods (probably other warnings as well) aren't show if the compiler used the cache to compile your code.

# How to reproduce
- Create a hello world using a shard full of deprecated methods like https://github.com/crystal-lang-tools/lsp/
- Compile it first time, you are going to see the warnings.
- Compile it second time, no warnings are seem.

# Why it matters
If you are trying to remove the deprecation warnings from a shard, you need to remove the `~/.cache/crystal/` on each compilation to really know if your job is done.

Another bad side is that you can think you code was no warnings, when it has.

**Comment by asterite** [comment]
I find this a bit hard to believe because the semantic and codegen pass are never reused. The only thing that's reused is compiling bc to o.

However, macro run programs are cached, so only compiled once. Could it be that lsp uses macro run?

**Comment by asterite** [comment]
Could you also provide code to reproduce this?

**Comment by hugopl** [comment]
Yes, it does, basically the deprecated JSON::Mapping.

I'm a bit busy today but I'll put here (in the next 24h) a small example to make everyone life easier.

**Comment by hugopl** [comment]
You are right, I was not abler to reproduce the issue, If I compile a library with warnings using `shards build` it doesn't show the warnings (possible by shards using `--exclude-warnings=lib`), but using `crystal build` it always show. The issue (if any) is related to shards, not crystal.

My bad, closing the issue.

**Comment by bcardiff** [comment]
@hugopl to clarify shards does not change or set `--exclude-warnings`. The `--exclude-warnings=lib` is the default value in `crystal` itself.

**Comment by hugopl** [comment]
Yeah, just noticed this... I think my confusion was because the compiler show warnings even on lib code if an error happen in some code using the lib code... anyway, next time I'll bring better/clean examples to not waste anybody time with wrong assumptions.
