### ISSUE TITLE
RFC: change default string representation in BigDecimal

### ISSUE THREAD

**Issue by stevegeek** [crystal-lang/crystal#9578]
Proposal: The default string representation for `BigDecimal`s should be in E (scientific) notation,

ie `BigDecimal.new("1E100").to_s` should output `"1E100"` rather than  `"10000...000"` (100 zeros)

the expanded version is arguably not much use and generating it can become very expensive (sort of related to #7808).

In other langs, 
* Ruby and Python output decimals as strings in E notation, 
* JS does too when Number value is large

At least if `.to_s` continues to create a representation that is expanded, it should be documented if it happens by default.

I would be happy to contribute to the implementation of this should it be agreed upon!

(originally part of #9547)

**Comment by HertzDevil** [comment]
`Float::Printer` does this for `Float32`s and `Float64`s whose base-10 exponent is not within `-4..14`:

```crystal
1e-5 # => 1.0e-5
1e-4 # => 0.0001
1e14 # => 100000000000000.0
1e15 # => 1.0e+15
```

`BigDecimal` should use the same range to make things consistent. For reference, `BigFloat` also suffers from this issue and I picked the exact same exponent range for #10632.
