### ISSUE TITLE
BUG: instance_vars does not work inside macro

### ISSUE THREAD

**Issue by kalinon** [crystal-lang/crystal#9587]
It seems that trying to use (instance_vars)[https://crystal-lang.org/api/0.35.1/Crystal/Macros/TypeNode.html#instance_vars:ArrayLiteral(MetaVar)-instance-method] inside a macro like `finished` does not work.

Using the example code, I expanded it to include 3 new methods that defined in various ways using macros. Only 1 of them works as expected:

```crystal
class Object
  def instance_vars_names
    {{ @type.instance_vars.map &.name.stringify }}
  end
end

class Person
  def initialize(@name : String, @age : Int32)
  end

  def vars
    {% for v in @type.instance_vars %}
    puts "vars: "+{{v.name.stringify}}
    {% end %}
  end

  macro finished
    def fin_vars
      {% for v in @type.instance_vars %}
      puts "fin_vars: "+{{v.name.stringify}}
      {% end %}
    end
  end

  macro def_meth
    def def_meth_vars
      {% for v in @type.instance_vars %}
      puts "def_meth: "+{{v.name.stringify}}
      {% end %}
    end
  end

  def_meth
end

person = Person.new "John", 30
puts person.instance_vars_names
person.vars
person.fin_vars
person.def_meth_vars
```

Output:
```
["name", "age"]
vars: name
vars: age
```

Expected output:
```
["name", "age"]
vars: name
vars: age
fin_vars: name
fin_vars: age
def_meth_vars: name
def_meth_vars: age
```

Crystal info:
```
crystal -v
Crystal 0.35.1 (2020-06-19)

LLVM: 10.0.0
Default target: x86_64-apple-macosx
```

**Comment by Blacksmoke16** [comment]
This is expected I think.  You need to escape the macro code within the other macros so that it runs in the correct scope.  See https://play.crystal-lang.org/#/r/9e76.

**Comment by kalinon** [comment]
> This is expected I think. You need to escape the macro code within the other macros so that it runs in the correct scope. See https://play.crystal-lang.org/#/r/9e76.
That's extremely confusing. The whole point of `finished` is:

* `finished` is invoked after instance variable types for all classes are known.

That's the exact time i would want to use `instance_vars`.

For example:

```crystal
class Object
  def instance_vars_names
    {{ @type.instance_vars.map &.name.stringify }}
  end
end

class Person
  def initialize(@name : String, @age : Int32)
  end

  macro finished
    {% puts @type.instance_vars %}
  end
end

person = Person.new "John", 30
puts person.instance_vars_names
```
Output:
```
[]
["name", "age"]
```

**Comment by kalinon** [comment]
@Blacksmoke16 thanks for pointing that out. I guess i can wrap it in `verbatim` for now. but it seems un-intuitive to me.

**Comment by jhass** [comment]
That doc is just misleading/wrong, see https://github.com/crystal-lang/crystal-book/pull/416

**Comment by asterite** [comment]
@kalinon I don't think you need `macro finished` at all in your code. It should work fine without it. And `def_meth` is not needed either. Just remove those macros and it works as you expect. Inside methods, `@type.instance_vars` will be what you expect.

Here's the working code:

```crystal
class Object
  def instance_vars_names
    {{ @type.instance_vars.map &.name.stringify }}
  end
end

class Person
  def initialize(@name : String, @age : Int32)
  end

  def vars
    {% for v in @type.instance_vars %}
    puts "vars: "+{{v.name.stringify}}
    {% end %}
  end

  def fin_vars
    {% for v in @type.instance_vars %}
      puts "fin_vars: "+{{v.name.stringify}}
    {% end %}
  end

  def def_meth_vars
    {% for v in @type.instance_vars %}
      puts "def_meth: "+{{v.name.stringify}}
      {% end %}
  end
end

person = Person.new "John", 30
puts person.instance_vars_names
person.vars
person.fin_vars
person.def_meth_vars
```

**Comment by kalinon** [comment]
Ah. @jhass i see. Yeah that's why i tried to use `finished` i wanted to ensure all instance variables were known. Since it doesnt work that way... i dont need to. Which is @asterite 's point.

I can close this as crystal-lang/crystal-book#416 fixes this misleading point.
