### ISSUE TITLE
bracket style blocks around if statments

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#9601]
Right now `if` statements only has an `if` and `end` like.
```crystal
if true
  x = foo
end
```
It would be nice to also have the option to have bracket block style arguments if statements like.
```crystal
if true {
  x = foo
}
```
This would enable a more c style structure but would be more flexible.

**Comment by lugia-kun** [comment]
I think it will conflict with the block argument to the calling method in the conditional.
```crystal
if [1, 2, 3].any? { |x| x == 1 }
  x = foo
end
```

**Comment by straight-shoota** [comment]
I don't see any benefit from that. It would just be another way to do the same thing and we try to avoid that in Crystal. It's a purely stylistical issue. So I don't suppose this is worth pushing forward.

**Comment by dscottboggs** [comment]
please don't

**Comment by asterite** [comment]
I was also going to comment about the syntax conflict. I don't think this will ever happen.
