### ISSUE TITLE
Should HTTP::Params#[]=(name, value) clear the Array?

### ISSUE THREAD

**Issue by m-o-e** [crystal-lang/crystal#9604]
Stumbled into this minor gripe while dealing with [HTTP::Params](https://crystal-lang.org/api/0.35.1/HTTP/Params.html#[]=(name,value)-instance-method):

```crystal
require "http"
 
params = HTTP::Params.new({"x" => ["1", "2"]})
puts params
# => x=1&x=2

params["x"] = "3"
puts params
# => x=3&x=2
```

Imho this is counter-intuitive because it violates the
common _set or replace_ semantics that `#[]=`
normally has almost everywhere else.

I.e. I would have expected `params["x"] = "3"`
to clear the Array, so that final output becomes: `x=3`.

Also I can't think of a case where I would want to
overwrite specifically only the first value of a param.

Is there a reason why the current behavior was chosen?

**Comment by m-o-e** [comment]
Fwiw, a clean way to fix this w/o introducing regressions might
be to provide an overload `#[]=(name : String, values : Array(String))`
that just replaces the Array.

The current method could then be flagged as deprecated and eventually be removed.

**Comment by asterite** [comment]
I think we should just fix the value. If it causes regressions then bad luck. But I don't think anyone will be relying on this strange behavior. It doesn't make sense to me.
