### ISSUE TITLE
File name too long

### ISSUE THREAD

**Issue by zolomatok** [crystal-lang/crystal#9651]
I have a 3 line long application:

```
require "http/server"

server = HTTP::Server.new do |ctx|
end
```

I'm using VSC, this [plugin](https://github.com/crystal-lang-tools/vscode-crystal-lang) and scry.
Crystal 0.35.1 (2020-06-19)
LLVM: 10.0.0
Default target: x86_64-apple-macosx
macOS 10.15.3 (19D76)

Upon opening the project in VSC, after enabling scry, I get the following error:

```
[Info  - 10:16:15 AM] Scry is looking into your code...
[Error - 10:16:17 AM] A error was found while searching diagnostics
Unexpected char 'U' at 1:1
Unable to get file info: '/Users/zolo/project/paperclips/Users/zolo/.cache/crysta/Users-zolo-project-paperclips-Users-zolo-.cache-crysta-Users-zolo-project-paperclips-Users-zolo-.cache-crysta-Users-zolo-project-paperclips-Users-zolo-.cache-crysta-Users-zolo-project-paperclips-Users-zolo-.cache-crysta-Users-zolo-project-paperclips-paperclips.cr': File name too long (File::Error)
  from raise<File::Error+>:NoReturn
  from Crystal::System::File::info?<String, Bool>:(Crystal::System::FileInfo | Nil)
  from Dir::mkdir_p<String>:Nil
  from Crystal::CacheDir#directory_for<String>:String
  from Crystal::Compiler#new_program<Array(Crystal::Compiler::Source)>:Crystal::Program
  from Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result
  from Crystal::Command#run:(Bool | Nil)
  from __crystal_main
  from main
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

**Comment by asterite** [comment]
Please report this bug in `scry`, it doesn't happen in Crystal without scry.

**Comment by zolomatok** [comment]
The reason I posted it here is because it literally says `Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues`.

So I thought you'd be able to glean something out of it, even though it's a scry thing.

**Comment by asterite** [comment]
I guess that makes sense. The "You found a bug" will be turned into "Error" without saying "bug", but it'll still be a bug if someone "fixes" this.

**Comment by zolomatok** [comment]
Moved to [here](https://github.com/crystal-lang-tools/scry/issues/176)

**Comment by bew** [comment]
@asterite that cache filename looks definitely wrong, and I don't think it's scry's fault

`
Users-zolo-project-paperclips-Users-zolo-.cache-crysta-Users-zolo-project-paperclips-Users-zolo-.cache-crysta-Users-zolo-project-paperclips-Users-zolo-.cache-crysta-Users-zolo-project-paperclips-Users-zolo-.cache-crysta-Users-zolo-project-paperclips-paperclips.cr
`
