### ISSUE TITLE
Bugs:  Buffered channels buffered error

### ISSUE THREAD

**Issue by IanVzs** [crystal-lang/crystal#9661]
# Submitting bugs

Make sure to review these points before submitting issues - thank you!
You are welcome.

I'm a beginner, learn from `GitBook`. But I found my results with different Demo.
### Demo
```
Before send 1
Before send 2
Before send 3
1
2
After send
3
```
### Me
```
Before send 1
Before send 2
Before send 3
After send
1
2
3
```
I think Buffered did not work properly. It is not multi-threaded, so I think it should have been stabilized.

- Make sure a similar issue doesn't exist yet: use the search box
<font color=green>yes</font>

- **Include reproducible code**: we should be able to paste it into an editor, compile and run it and get the same error as you. Otherwise it's impossible for us to reproduce the bug.
```
just copy from [GitBook Demo](https://crystal-lang.org/reference/guides/concurrency.html)

# A buffered channel of capacity 2
channel = Channel(Int32).new(2)

spawn do
  puts "Before send 1"
  channel.send(1)
  puts "Before send 2"
  channel.send(2)
  puts "Before send 3"
  channel.send(3)
  puts "After send"
end

3.times do |i|
  puts channel.receive
end
```
- Don't **only** use `play.crystal-lang.org` or `carc.in`: code might be lost and the issue will remain incomplete. Write code in the issue itself.
I use my PC(`WSL2`, 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux) and Server(4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux)

use `crystal run <this.cr>` and `crystal build <this.cr> --release && ./<this>`

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

and 

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```
- Reduce code, if possible, to the minimum size that reproduces the bug.
<font color=green>yes, is pretty small</font>
- If all of the above is impossible due to a large project, create a branch that reproduces the bug and point us to it.
- Include Crystal compiler version (`crystal -v`) and OS. If possible, try to see if the bug still reproduces on master.
```
Crystal 0.35.1 [5999ae29b] (2020-06-19)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by asterite** [comment]
The docs need to be updated or either say that the order of the result depends on the implementation and one shouldn't rely on it. This is not a bug.

**Comment by IanVzs** [comment]
Thanks.
