### ISSUE TITLE
Can't use named arguments with macro splat argument

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#9664]
https://play.crystal-lang.org/#/r/9i68

```cr
macro test(*tags)
  pp({{tags.empty? ? nil : tags}})
end

test(tags: "a", "b") # => Error: expecting token ':', not ')'
```

**Comment by asterite** [comment]
Not a bug. The way to use it is:

```crystal
test("a", "b")
```

`tags` is the name you use from inside the method. There's no way to refer to that name from the outside. And I don't see a need for it (plus there's no such thing in Ruby nor any other language).

**Comment by Blacksmoke16** [comment]
Full example:

```cr
macro test(name, focus = false, *tags)
 ...
end
```

Use case is to do like `test "foo", tags: "a", "b"`, so that it would use the default value for `focus` without needing to manually specify it.

**Comment by bcardiff** [comment]
tags should receive an array. There are no va_list equivalent in crystal methods.

My suggestion:

```crystal
macro test(tags = %w())
  pp({{tags.empty? ? nil : tags}})
end
 
test(tags: %w(a b))
test
```

or

```crystal
macro test(*tags)
  pp({{tags.empty? ? nil : tags}})
end
 
test(%w(a b))
test
```

**Comment by jhass** [comment]
I agree, not a bug.
