### ISSUE TITLE
Local variable inside an if block inherits the type of the previous block.

### ISSUE THREAD

**Issue by cristian-lsdb** [crystal-lang/crystal#9669]
When a condition is true before assigning the local variable:

```crystal
if x = "abc"
  pp! x          # => "abc"
  pp! typeof(x)  # => String
end
 
if true && (x = 1.1)
  pp! x          # => 1.1
  pp! typeof(x)  # => (Float64 | String)
end
 
if (x = 1.1) && true
  pp! x          # => 1.1
  pp! typeof(x)  # => Float64
end
```

https://play.crystal-lang.org/#/r/9j6y

**Comment by cristian-lsdb** [comment]
This issue can be decomposed in two parts. 

First part, when a variable is assigned in an `if`’s condition, the variable is available outside the `if` block. 

```Crystal
if x = 123
  pp! x # => 123
end
pp! x   # => 123
```

I don’t know if it’s a feature, but I expected the variable to be isolated inside the `if` block, like for the `try` block:

```Crystal
123.try do |x|
  pp! x # => 123
end 
pp! x   # => Error: undefined local variable or method 'x' for top-level
```



Second part, when a variable already exists and it is reassigned in an if’s condition, sometime the type is overwritten, sometime merged. 

Overwritten when the assignment is made in the first condition:
```Crystal
x = "abc" # => String
if (x = 123) && true
  pp! typeof(x) # => Int32
end
pp! typeof(x) # => Int32
```

And merged when the assignment is preceded by a `true` condition:
```Crystal
x = "abc" # => String
if true && (x = 123)
  pp! typeof(x) # => (Int32 | String)
end
pp! typeof(x) # => (Int32 | String)
```

Same here, I expected the variable to be perfectly isolated like in a `try` block:
```Crystal
x = "abc" # => String
123.try do |x|
  pp! typeof(x) # => Int32
end
pp! typeof(x) # => String
```

**Comment by oprypin** [comment]
I think all of this is expected behavior.
First, Crystal doesn't have block scoping; scopes of variables are limited only to the function entirely.
Second, yes, Crystal will make a union out of a variable if it could have different types in different conditions. Then there is a special case that, if it's 100% certain the assignment will overwrite anything prior, then prior types can also be thrown away.
Then you can still argue that `if true && (x = 1.1)` is "100% certain" but the optimizations just don't go that far and probably aren't intended to.

**Comment by asterite** [comment]
A variable's scope is the entire method, or a block. Never an if, while, until or unless.

That said, this is a bug: x on the second if should not have mixed types.

**Comment by cristian-lsdb** [comment]
Thank you, oprypin and asterite, for your explanations. 

I like the behavior of the `try` block, is it possible to pass several variables to it at the same time? Something like that:
```Crystal
{@x, @y, @z}.try_all do |x, y, z|
  # here x, y, z are not nil
end
```
Which would be equivalent to:
```Crystal
@x.try do |x|
  @y.try do |y|
    @z.try do |z|
      # here x, y, z are not nil
    end
  end
end
```

**Comment by cristian-lsdb** [comment]
Thanks @Blacksmoke16, I closed this issue because during the last two years I have never encountered this problem again. And the title and the description are unclear so even if someone has the same problem I doubt that he will be able to find this issue via the search.
