### ISSUE TITLE
Class#=== compares object instances, not classes.

### ISSUE THREAD

**Issue by BrucePerens** [crystal-lang/crystal#9670]
Class#=== is inherited from Object and compares object instances, not classes. Thus case statements switching on object types do not work because 'a'.class and Char are not the same instance. For example:

```
case 'a'.class
when Char
else
end
```
The else case is executed.

However, Class#== correctly compares classes. It seems non-intuitive that Class#=== would not do the same.

**Comment by Blacksmoke16** [comment]
I think you want to write your case like:

```cr
case 'a'
when Char
  pp "char"
else
 pp "not char"
end
```

or

```cr
case 'a'.class
when Char.class
  pp "char"
else
 pp "not char"
end
```

Both of these would print `char`, with the former being the more idiomatic way of writing it.

**Comment by BrucePerens** [comment]
Blacksmoke16, I am astonished that those things work and that you happened to know that they do. However, I don't see that there is any documentation that this is a language feature at all, and any guarantee that code written that way today will work tomorrow.

What I see so far in the 0.35.1 online documentation is that Class is not documented to implement its own ===, but inherits it from Object, and that object implements it by calling == (which is incorrect).

But, as you write, both of the following case and when statements work on 0.35.1:

````
case 'a'
when 'a'
```

```
case 'a'
when Char
```
Now, I looked at your suggestion that I do:

```
case 'a'.class
when Char.class
```

Astonishingly, this works, even though 'a'.class is a Char and Char.class is a Class.
In addition, while the `when` statement above works, the statement below, which should be equivalent, does not:
```
a.class === Char.class
```
That correctly returns false, but I thought that === was case match.

So, what secret text must I acquire to learn these apparently undocumented language features?

**Comment by z64** [comment]
`when Type` and other semantics is documented in the reference

https://crystal-lang.org/reference/syntax_and_semantics/case.html

**Comment by BrucePerens** [comment]
OK, so case compare is not always using ===. I'll close the bug.

**Comment by BrucePerens** [comment]
There's a better way to write what I want to do. Closing.

**Comment by jhass** [comment]
It is always using `===`, just with the `when` branch argument as receiver. So `Char === 'a'.class` is `false`, but `Char === 'a'` is `true`.

**Comment by asterite** [comment]
Ruby works the same way.

The difference is that in Crystal you can use Char.class in a when, and that has a special meaning. case works a bit differently than in Ruby to make type flow work correctly.

Meh, "type flow" sounds boring, let's call it "smart type filtering" for some buzz. Or any other ideas of a name?
