### ISSUE TITLE
Error opening file with mode 'w':

### ISSUE THREAD

**Issue by randiaz95** [crystal-lang/crystal#9680]
Hi guys, I have the error: Error opening file with mode 'w'
that occurs when an intermediate directory doesn't exist on the class method `File.write "./exists/doesnt/file.txt", "content", mode="w+"`

if mode is w+ then error should say Error opening file with mode 'w+' not w

**Comment by Blacksmoke16** [comment]
FWIW it should be `mode: "w+"` not `mode = "w+"`.  You're just assigning a local var to `"w+"`, that is probably getting passed into the third argument, not actually changing the `mode`, hence it uses the default of `"w"`.

**Comment by jhass** [comment]
Yes, not a bug :)
