### ISSUE TITLE
Crypto::Bcrypt::Password#== does not work

### ISSUE THREAD

**Issue by sugarfi** [crystal-lang/crystal#9685]
# Crypto::Bcrypt::Password#== does not work

In the [docs for `Crypto::Bcrypt::Password`](https://crystal-lang.org/api/0.20.3/Crypto/Bcrypt/Password.html), it is stated that the
`==` method of a `Password`, given a `String`, should check if that string hashes to the same value as the hash, ie. the hash is the
hash of the given string. The example code given is:
```crystal
require "crypto/bcrypt/password"

password = Crypto::Bcrypt::Password.create("super secret", cost: 10)

puts password == "wrong secret"
puts password == "super secret"
```
While this should output `false` and then `true`, as we can see [here](https://carc.in/#/r/9kdu), it outputs `false` and `false`.

**Comment by Blacksmoke16** [comment]
It has been updated to [Crypto::Bcrypt::Password#verify](https://crystal-lang.org/api/0.35.1/Crypto/Bcrypt/Password.html#verify(password:String):Bool-instance-method).  You're just looking at old API documentation.  Latest version is `0.35.1`.

**Comment by sugarfi** [comment]
Oh, my bad! Thanks for the update - will close this issue.

**Comment by Blacksmoke16** [comment]
Related: https://github.com/crystal-lang/crystal/issues/5952.
