### ISSUE TITLE
Splatting a StaticArray into singly-typed functions

### ISSUE THREAD

**Issue by shinzlet** [crystal-lang/crystal#9692]
Splatting an `Array` into a function call isn't possible, because at compile time there's no way to know the size of the array (#1096, #1464). However, a `StaticArray` has known type and size at compile time, so could presumably be splatted without runtime issues.

## Current behaviour
```crystal
def foo(a : Int32, b : Int32)
  a + b
end

foo *StaticArray[1, 2] # Error: argument to splat must be a tuple, not StaticArray(Int32, 2)
```

## Proposed behaviour
```crystal
def foo(a : Int32, b : Int32)
  a + b
end

foo *StaticArray[1, 2] # => 3
```

There is also the issue of mixed argument types:
```crystal
def foo(a : String, b : Int32)
  a + b
end

foo *StaticArray["test", 2] # Error: StaticArrays can only be splat into functions with a single parameter type
```

Using a tuple rather than a StaticArray would be the obvious choice in the simplified examples shown above, but in my use case the StaticArray is coming from a library function which can't be changed.

I'd love to hear what people think about this feature - too niche? Or useful syntactic sugar?

**Comment by asterite** [comment]
What's that library function?

**Comment by shinzlet** [comment]
> What's that library function?

It's not stdlib, my apologies for being unclear. (If you're curious: [`HSLuv#rgb_to_hsluv(r, g, b) : StaticArray(Float64, 3)`](https://github.com/shinzlet/hsluv-crystal/blob/master/src/hsluv.cr#L55))

The library that I'm using is implemented in [over twenty programming languages](https://www.hsluv.org/implementations/), and every implementation uses a common api (colors are returned as float arrays).

**Comment by asterite** [comment]
I think that given this use case is extremely rare, I don't think it's worth making the language that much complex

**Comment by bcardiff** [comment]
You can convert static array to tuples as follows:

```crystal
a = StaticArray[2, 4, 6]
pp! a # => StaticArray[2, 4, 6]

def to_t(a : StaticArray(T, N)) forall T, N
  {% begin %}Tuple.new({% for i in (0...N) %}{% if i > 0 %},{% end %} a[{{i}}]{% end %}){% end %}
end

pp! to_t(a) # => {2, 4, 6}
```

**Comment by shinzlet** [comment]
Both good points. After thinking about it for a while longer, I agree that this feature is probably too niche. I was briefly humoring the idea of trying to factor `StaticArray` out into a subclass of `Tuple` (the former seems to fundamentally be a special case of the latter), but that sounds like much more trouble than it's worth :p

Closing.
