### ISSUE TITLE
[feature] crystal doc should detect raises within methods and list them

### ISSUE THREAD

**Issue by postmodern** [crystal-lang/crystal#9696]
I think it would be greatly beneficial if the `crystal doc` generator could scan the contents of methods, noting any `raise` statements, and then list all exception classes that the method raises. This would help other developers understand which types of exceptions a method raises, without the maintainer having to manually document each exception raised by a method.

**Comment by asterite** [comment]
The compiler figures out whether something raises or not by analyzing method bodies (once you invoke them). `crystal doc` never analyzes bodies so this would be a bit impossible to do.

**Comment by Blacksmoke16** [comment]
Related: https://github.com/crystal-lang/crystal/issues/8353

**Comment by straight-shoota** [comment]
Closing as duplicate. Discussion is encouraged to continue in #8353
