### ISSUE TITLE
Copying at return from `Struct.new` can cause different behavior between `--debug` and `--release` builds

### ISSUE THREAD

**Issue by lugia-kun** [crystal-lang/crystal#9700]
I realized the fact that the content gets copied while returning from `.new`, by looking at generated LLVM IR (https://github.com/crystal-lang/crystal/issues/7771#issuecomment-494773844).

However, LLVM can optimize to let `.new` (and `#initialize`) to use the destination memory space (i.e., caller's stack region) as `self`. This makes different behavior between `--debug` and `--release` builds if we obtain the address of `self` or its member. And if possible, I would like to be this as "language's behavior." 

### Example

At first, considering this C code (to be an unoptimizable part):
```c
struct X
{
  const char *ptr;
};

void *foo(struct X *x, const char *c)
{
  x->ptr = c;
  return x;
}

const char *bar(struct X *x)
{
  return x->ptr;
}
```

Compile this to a shared object:
```
$ gcc -shared -o test.so test.c
```

Following Crystal code causes different behavior between `--debug` and `--release`:
```crystal
lib LibFoo
  struct X
    ptr : Pointer(UInt8)
  end

  fun foo(X*, UInt8*) : Void*
  fun bar(Void*) : UInt8*
end

struct A
  @data : LibFoo::X
  @ptr : Pointer(Void)
  @i : String

  def initialize(@i)
    @data = LibFoo::X.new
    @ptr = LibFoo.foo(pointerof(@data), @i)
  end

  def to_unsafe
    @ptr
  end
end

def boom
  StaticArray(UInt32, 1000).new { 0xdeadbeef_u32 }
end

a = A.new("Hello, World!")
b = boom
p String.new(LibFoo.bar(a))
```

### With `--debug`:
```
$ rm -rf ~/.cache/crystal && CC="gcc `pwd`/test.so" crystal build --debug test.cr
$ ./test
Invalid memory access (signal 11) at address 0xdeadbeef
[0x4658f6] *Exception::CallStack::print_backtrace:Int32 +118
[0x451b19] __crystal_sigfault_handler +361
[0x7fc40c60d450] ???
[0x7fc40c4373ca] ???
[0x46d5f4] *String::new<Pointer(UInt8)>:String +36
[0x4433d1] __crystal_main +56769
[0x4d1ebd] *Crystal::main_user_code<Int32, Pointer(Pointer(UInt8))>:Nil +45
[0x4d1d15] *Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32 +101
[0x44e73d] main +45
[0x7fc40c3ac023] __libc_start_main +243
[0x43555e] _start +46
[0x0] ???
```
This is not reasonable behavior but is expected. Because the resulting `@ptr` points `@data` of the temporal region only exists while executing `#initialize`.

### With `--release`:
```
$ rm -rf ~/.cache/crystal && CC="gcc `pwd`/test.so" crystal build --release  test.cr
$ ./test
"Hello, World!"
```
`#initialize` was called with memory space of `a`.

### `crystal --version`:
```
Crystal 0.35.1 ()

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```
(I built the compiler from [the source tarball](https://github.com/crystal-lang/crystal/releases/tag/0.35.1), not `git clone`)

**Comment by asterite** [comment]
A struct `new`/`initialize` returns a copy of what happens in the initializer. You shouldn't take a pointerof a member inside initialize/new.  But you probably know this.

Similar to #1685

In general, when using pointerof or Pointer the code is unsafe. That means invalid memory can happen if used incorrectly. And here it's not used correctly because it's taking a pointer to something that's not the final struct.

**Comment by asterite** [comment]
(so I think this is not a bug. Just don't use pointerof, and much less like that)

**Comment by asterite** [comment]
I think we should probably disallow taking a pointer of a local variable of a struct when inside a struct, because it will always be the wrong thing.

**Comment by bcardiff** [comment]
It's not always the wrong thing to do. But is risky. The channel send/receive uses pointer of struct of local variable in order to avoid allocating in the heap. But because the stack of the fiber will never remove that while waiting it's a safe use.

Ref: https://github.com/crystal-lang/crystal/blob/0.35.1/src/channel.cr#L224

**Comment by asterite** [comment]
Ups, sorry, I meant a pointer of an instance variable of a struct.

**Comment by lugia-kun** [comment]
Oh, I missed that issue.

What I want to achieve is the same as it. So I'll comment on #1685 and closing this issue as a duplicate.
