### ISSUE TITLE
2.try(&.*3) doesn’t work.

### ISSUE THREAD

**Issue by cristian-lsdb** [crystal-lang/crystal#9705]
When the space is missing between the operator and the number, an error is raised:
```Crystal
2.try &.* 3  #=> works fine 
2.try &.*3   #=> Error: unexpected token: 3
2.try(&.*3)  #=> Error: expecting token ')', not '3'
```
Same problem with the other mathematical operators `+` `-` `/` `**`
Intuitively, I expected it to work because `2*3` (without space) works fine.

**Comment by Blacksmoke16** [comment]
I'm actually surprised that first one works...  In this case these are method calls (like any other method) so you should/would have to do like `2.try(&.*(3))` or `2.try &.*(3)`.

**Comment by cristian-lsdb** [comment]
I thought that `2*3` was the same as `2.*3` and `2.*(3)`, but it seem that I was wrong because `2.*3` doesn't works in Crystal (it works in Ruby). 
In the end, you are right, it’s better to use parentheses, because `2 .* 3 + 4` compiles to `2 * (3 + 4)` instead of `(2 * 3) + 4` (same in Ruby).
