### ISSUE TITLE
+(-1 - 1.i) return (1 +1.i)

### ISSUE THREAD

**Issue by cristian-lsdb** [crystal-lang/crystal#9709]
Adding `+` in front of a complex number return a new complex with a positive value of the real and imaginary part.

```Crystal
require "complex"
pp! +( 1 + 1.i) # => (1.0 + 1.0i)
pp! +(-1 + 1.i) # => (1.0 + 1.0i)
pp! +( 1 - 1.i) # => (1.0 + 1.0i)
pp! +(-1 - 1.i) # => (1.0 + 1.0i)
```

This is caused by the instance method [Complex#+](https://github.com/crystal-lang/crystal/blob/5999ae29b/src/complex.cr#L228)

In Ruby, Python and C++, `+(-1 - 1i)` return `(-1 - 1i)`.

**Comment by naqvis** [comment]
`Complex.+` methods returns the absolute value of `self`. Believe you are treating or expecting it to behave like normal unary operator on other primitives. Please refer to [API documentation]( https://crystal-lang.org/api/0.35.1/Complex.html#+-instance-method)

**Comment by asterite** [comment]
@naqvis That's how it works but I think `+` should always return self. I'll fix this now.

**Comment by naqvis** [comment]
Thanks @asterite. One question after change though: shouldn't it return a copy instead of returning `self`?

**Comment by asterite** [comment]
It's a struct (a copy is naturally returned) and it's immutable so a copy is never necessary (if it were a class).

**Comment by jhass** [comment]
It looks like `Complex#+` was added by @Sija through #5440. Was there any reasoning for the current implementation?

**Comment by Sija** [comment]
@jhass Can't remember.
