### ISSUE TITLE
.includes? misbehaves with non-ascii

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#9712]
Code:
```crystal
require "random"

"#{String.new(Random.new.random_bytes)}PNG#{String.new(Random.new.random_bytes)}".includes?("PNG")
```
I would expect the above to always be true, but in most runs this comes back as false.

P.S
Same code with `.match(/PNG/)` works each time.

**Comment by jhass** [comment]
One more reason why we should've kept `String` UTF-8 only...

**Comment by bararchy** [comment]
:cry:

**Comment by asterite** [comment]
Duplicate of https://github.com/crystal-lang/crystal/issues/8785
