### ISSUE TITLE
Can't iterate through Regex::MatchData named capture groups

### ISSUE THREAD

**Issue by BrucePerens** [crystal-lang/crystal#9728]
In my program, the regular expression is provided by the user (it's a computer language). There is no information provided by the Regex::MatchData API that would allow me to iterate through the named capture groups. I need to do that to convert them to my language's native data types. I worked around the problem for now by monkey-patching the API, but this is poorly sustainable.

```crystal
struct Regex::MatchData
  def name_table
    @regex.name_table
  end
end
```

There have been a number of proposals to expand the Regex API, including #3653. They mostly haven't come with use cases.

**Comment by jhass** [comment]
Ruby offers [MatchData#names](https://rubyapi.org/2.7/o/matchdata#method-i-names) and [Regexp#names](https://rubyapi.org/2.7/o/regexp#method-i-names).

**Comment by BrucePerens** [comment]
Good point, should be looking at Ruby when I file something like this. I will name my monkey-patch that way.

**Comment by jhass** [comment]
Actually we got [Regexp::MatchData#named_captures](https://crystal-lang.org/api/0.35.1/Regex/MatchData.html#named_captures-instance-method)

**Comment by asterite** [comment]
Ugh, name table should use Int32, not UInt16, though I guess it doesn't matter that much.

**Comment by asterite** [comment]
Also from match data you can reach the regex, so you can actually do `match_data.regex.name_table`

**Comment by BrucePerens** [comment]
OK, sorry I missed that. Closing.
