### ISSUE TITLE
Suggestion: move some Complex’s instance methods into Math module

### ISSUE THREAD

**Issue by cristian-lsdb** [crystal-lang/crystal#9729]
Some Complex’s methods have the same name as Math’s methods, so the syntax of calling mathematical methods depends on the type:
```Crystal
Math.sqrt(2)           # Ok with Int
Math.sqrt(2.0)         # Ok with Float 
Math.sqrt(2.0 + 1.0.i) # Error with Complex
(2.0 + 1.0.i).sqrt     # Current syntax for Complex
```
I think it would be better to have the same namespace for all mathematical methods.

These methods have their Math counterpart: 
[Complex#exp](https://crystal-lang.org/api/0.35.1/Complex.html#exp-instance-method) => [Math#exp(value)](https://crystal-lang.org/api/0.35.1/Math.html#exp(value)-instance-method)
[Complex#log](https://crystal-lang.org/api/0.35.1/Complex.html#log-instance-method) => [Math#log(value)](https://crystal-lang.org/api/0.35.1/Math.html#log(value)-instance-method)
[Complex#log2](https://crystal-lang.org/api/0.35.1/Complex.html#log2-instance-method) => [Math#log2(value)](https://crystal-lang.org/api/0.35.1/Math.html#log2(value)-instance-method)
[Complex#log10](https://crystal-lang.org/api/0.35.1/Complex.html#log10-instance-method) => [Math#log10(value)](https://crystal-lang.org/api/0.35.1/Math.html#log10(value)-instance-method)
[Complex#sqrt](https://crystal-lang.org/api/0.35.1/Complex.html#sqrt-instance-method) => [Math#sqrt(value)](https://crystal-lang.org/api/0.35.1/Math.html#sqrt(value)-instance-method)

**Comment by bcardiff** [comment]
I think is fine to add overloads for those methods in Math module to handle complex numbers.

**Comment by cristian-lsdb** [comment]
You think it’s better to move them, which will lead to a breaking change, or to create aliases? Moving them seems more logical to me because Int and Float don’t have these instances methods.

**Comment by asterite** [comment]
I think we should copy Ruby. These methods only exist in Math so in my opinion we should do the same.

**Comment by bcardiff** [comment]
Keeping them only in the Math module is a breaking change that we can tolerate right now I think. A PR is welcome in that direction.
