### ISSUE TITLE
Type declarations use current namespace but default values do not

### ISSUE THREAD

**Issue by jgaskins** [crystal-lang/crystal#9731]
Given the following code with classes or structs nested inside a namespace:

```crystal
require "json"
require "uuid"
require "uuid/json"

struct MyRoute
  struct CreateMyResourceRequest
    include JSON::Serializable

    getter thing_a : ThingA
    getter thing_b = ThingB.new
  end

  struct ThingA
    include JSON::Serializable

    getter id : String
  end

  struct ThingB
    include JSON::Serializable

    getter id = "id"

    def initialize
    end
  end
end

MyRoute::CreateMyResourceRequest.from_json("") # the json value isn't important since it doesn't compile
```

The default value of `getter thing_b = ThingB.new` doesn't compile. It appears that it requires a fully-qualified class name in order to set a default value. It's not required for a type declaration (so `getter thing_b : ThingB = MyRoute::ThingB.new` is valid — the type declaration does not need the `MyRoute::` prefix), but it is for the default value.

When all of the resources are nested within a namespace, repeating that namespace for every default value (typically arrays of those types) gets cumbersome:

```crystal
module API
  module V2
    struct MyResources
      struct CreateMyResourceRequest
        include JSON::Serializable

        getter thing_a : NewThingA
        getter thing_b = API::V2::MyResources::NewThingB.new
        getter thing_cs = Array(API::V2::MyResources::NewThingC).new
        getter thing_ds = Array(API::V2::MyResources::NewThingD).new
      end
    end
  end
end
```

```
$ crystal -v
Crystal 0.35.1 (2020-06-19)

LLVM: 10.0.0
Default target: x86_64-apple-macosx
```

**Comment by jgaskins** [comment]
One of the interesting things about this error is that, in the first code example, if I leave off the namespace from the default value but get the constructor wrong, it detects that:

<img width="556" alt="image" src="https://user-images.githubusercontent.com/108205/92333661-56f4ed80-f055-11ea-844f-b6bfccfaa954.png">

So some part of the type resolver knows this even for default values.

**Comment by jgaskins** [comment]
After doing a bit more digging through the compiler guts and sprinkling some debug logging throughout some places that seem pertinent, it looks like these default values are actually assigned by `JSON::Serializable`, which explains why the type checks still work but the default assignment doesn't — the compiler isn't generating this code, the `JSON::Serializable` `included` macro is:

```crystal
# src/compiler/crystal/semantic/type_lookup.cr

class Crystal::Type
  private struct TypeLookup
    def lookup_type_var(node : Path)
      type_var = lookup_type_var?(node)
      return type_var if type_var

      if @raise
        pp self: self, node: node # *** debugging line here ***
        raise_undefined_constant(node)
      else
        nil
      end
    end
  end
end
```

Results in this line of output:

```
{self:
  Crystal::Type::TypeLookup(
   @allow_typeof=false,
   @find_root_generic_type_parameters=true,
   @free_vars=nil,
   @in_generic_args=0,
   @raise=true,
   @remove_alias=false,
   @root=JSON::Serializable,
   @self_type=JSON::Serializable),
 node: ThingB}
```

Going to see if I can get `JSON::Serializable` to generate default values with the right prefixes via similar type lookups without too much hassle. I imagine other `*::Serializable` things would have the same discrepancy between ivar type declarations and default assignment.

**Comment by asterite** [comment]
The problem is that the generated serialize that embeds the values is defined in the JSON::Serializable module and not on each including type.

**Comment by asterite** [comment]
It's the same problem with converters and you can't fix it by relying on default values

**Comment by jgaskins** [comment]
I think it makes sense to make people think about `JSON::Serializable` as the caller of a converter — that converter will only ever be invoked if you're converting from JSON, and never any other time.

A default value, though, is part of baseline Crystal. It doesn't depend on `JSON::Serializable` to invoke it. If I remove the `include JSON::Serializable`, or invoked any initializer other than the `JSON::PullParser` one, the default value would still be set, so I would never expect the default value to be called from within the context of `JSON::Serializable`.

In fact, I thought this was a compiler bug rather than anything having to do with stdlib before about an hour ago. 🙂

**Comment by asterite** [comment]
I think your fix is good. I didn't think about just relying on. the default initialization. Could you also add YAML in your PR.?

**Comment by jgaskins** [comment]
@asterite I've added YAML. Is there anything else needed on this one?
