### ISSUE TITLE
Overload selection fails for specific subclassing order

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#9750]
```crystal
def f(_x : A)
  puts "f(A)"
end

def f(_x : B)
  puts "f(B)"
end

class A end
class B < A end

f(A.new) # => f(A)
f(B.new) # => f(A)
```

This is supposed to print `f(A)` and then `f(B)`, however [the `A` overload is selected in both cases](https://carc.in/#/r/9pwi). This only happens if the functions are defined in this specific order. The example would work if:

* `f(B)` is defined after the first definition of `B`. If `f` happens to be an instance or class method of `A`, then `A` must be reopened or [the same happens](https://carc.in/#/r/9pws).
* [`f(A)` and `f(B)` are swapped](https://carc.in/#/r/9pwj).
* [`B` no longer inherits from `A`](https://carc.in/#/r/9pwk).

Tested on 52c750ece and 0.35.1.

**Comment by Blacksmoke16** [comment]
I think this is expected.

https://crystal-lang.org/reference/syntax_and_semantics/overloading.html

Mainly the last section:

> However, the compiler cannot always figure out the order because there isn't always a total ordering, so it's always better to put less restrictive methods at the end.

**Comment by HertzDevil** [comment]
I disagree; in this case it is the *presence* of a total ordering that breaks the overloads.

**Comment by asterite** [comment]
It works fine if you define the types **before** the overload.

**Comment by Blacksmoke16** [comment]
`B` inherits from `A`, so it's a compatible type of both `A` and `B`.  Because of this the compiler just picks the first one.  Your second point there is what the book is saying, `A` being the least restrictive type, allows it to match `B` (the more specific overload) first.  And of course if `B` doesn't inherit from `A` this is also a non issue as they no longer are both compatible.  

I don't think there is anything to do here.

**Comment by asterite** [comment]
The way it works, when the compiler finds a method it will analyze its argument types, try to resolve them, and if that's possible it will use hierarchy information to sort the methods.

But it only works if the types are defined **before** the methods are analyzed.

**Comment by asterite** [comment]
Not that this is an ideal situation, I'm just explaining how things work right now.

**Comment by HertzDevil** [comment]
Duplicate of #7579.
