### ISSUE TITLE
array#clone returns the wrong type if subclassed

### ISSUE THREAD

**Issue by BrucePerens** [crystal-lang/crystal#9753]
Array#clone calls Array(T).new, but it should be calling self.class.new . If it is subclassed, it will not return the subclass type.

```crystal
def clone
    Array(T).new(size) { |i| @buffer[i].clone.as(T) }
end
```
API version 0.35.1

**Comment by vlazar** [comment]
I've tried to adress it similar to how I did it in #9871 but as soon as I define only this:

```crystal
private class ArraySubclass(T) < Array(T)
end
```

array spec fails with
```bash
$ bin/crystal spec spec/std/array_spec.cr
Using compiled compiler at .build/crystal
Showing last frame. Use --error-trace for full trace.

In src/spec/expectations.cr:4:5

 4 | def initialize(@expected_value : T)
     ^---------
Error: no overload matches 'Spec::EqualExpectation(Array(Array(Float64 | Int32)).class)#initialize' with type Array(Array(Float64 | Int32)).class

Overloads are:
 - Spec::EqualExpectation(T)#initialize(expected_value : T)
```

I'm not sure how to fix this failure.

**Comment by asterite** [comment]
@vlazar What's the full error? And please send a diff or a PR, otherwise we can't know what to do to reach that point that you reached.

**Comment by asterite** [comment]
Oh, and the error is probably because if an Array is extended then that type changes everywhere in the compiler and compiler specs, and we have tons of bugs related to generics so that might be one such bug.

**Comment by vlazar** [comment]
@asterite 

```diff
$ git diff
diff --git a/spec/std/array_spec.cr b/spec/std/array_spec.cr
index 39a4d5cc6..ea1b2a32c 100644
--- a/spec/std/array_spec.cr
+++ b/spec/std/array_spec.cr
@@ -23,6 +23,9 @@ private class Spaceship
   end
 end

+private class ArraySubclass(T) < Array(T)
+end
+
 describe "Array" do
   describe "new" do
     it "creates with default value" do
```

<details>
  <summary>FULL ERROR</summary>
  <pre>
$ bin/crystal spec --error-trace spec/std/array_spec.cr
Using compiled compiler at .build/crystal
error in line 1
Error: while requiring "./spec/std/array_spec.cr"


In spec/std/array_spec.cr:1821:45

 1821 | typeof([[1.0], [1]].transpose).should eq(Array(Array(Int32 | Float64)))
                                              ^-
Error: instantiating 'eq(Array(Array(Float64 | Int32)).class)'


In src/spec/expectations.cr:293:30

 293 | Spec::EqualExpectation.new value
                              ^--
Error: instantiating 'Spec::EqualExpectation(T).class#new(Array(Array(Float64 | Int32)).class)'


In src/spec/expectations.cr:4:5

 4 | def initialize(@expected_value : T)
     ^---------
Error: no overload matches 'Spec::EqualExpectation(Array(Array(Float64 | Int32)).class)#initialize' with type Array(Array(Float64 | Int32)).class

Overloads are:
 - Spec::EqualExpectation(T)#initialize(expected_value : T)
  </pre>
</details>

**Comment by straight-shoota** [comment]
Closing per https://github.com/crystal-lang/crystal/issues/10328#issuecomment-769812463
