### ISSUE TITLE
Subclasses can avoid all constructors of their superclass, if the superclass constructors only have side-effects.

### ISSUE THREAD

**Issue by BrucePerens** [crystal-lang/crystal#9757]
This is a non-intuitive feature of the language. B instantiates itself as a child of A without calling any of A's constructors. And an important side-effect of A's constructor is avoided. I could contrive an abstract class to enforce this, but it's not clear to me that the language should allow it as stated here.
```crystal
def register(n)
  puts "Registered #{n.class.name}"
end

class A
  def initialize
    register(self)
  end
end


class B < A
  def initialize
  end
end

b = B.new
a = A.new
```

**Comment by asterite** [comment]
It's fine because A doesn't have any instance vars to initialize, so calling `super` is not required. This is exactly the same as in Ruby: `super` is not enforced. The difference is that for type-safety we require it, but only to initialize instance vars that are not nilable.

For example, try this:

```crystal
class A
  @x : Int32

  def initialize
    @x = 1
  end
end

class B < A
  def initialize
  end
end

b = B.new
```

Error:

```
In foo.cr:10:7

 10 | def initialize
          ^---------
Error: this 'initialize' doesn't initialize instance variable '@x' of A, with B < A, rendering it nilable
```

**Comment by straight-shoota** [comment]
> B instantiates itself as a child of A without calling any of A's constructors.

That's not necessarily unexpected. `B` defines its own constructor and overrides the one in the parent class. Seems plausible to me. If you want the super constructor to be invoked, you can call `super` explicitly.
