### ISSUE TITLE
formatter removes significant comma, leading to non-compilable code

### ISSUE THREAD

**Issue by philipp-classen** [crystal-lang/crystal#9759]
Running `crystal tool format` on

```
record Foo,
  bar : String, #
 do
  def baz
  end
end
```

gets formatted to illegal code because the comma gets removed

```
record Foo,
  bar : String #
 do
  def baz
  end
end
```

Now it gets rejected by the compiler:

```
$ crystal run example.cr 
In example.cr:3:2

 3 | do
     ^
Error: expecting token 'EOF', not 'do'
```

```
$ crystal -v
Crystal 0.35.1 (2020-06-21)

LLVM: 10.0.0
Default target: x86_64-pc-linux-gnu
```

**Comment by Blacksmoke16** [comment]
I think this is more an issue with having the `do` keyword on the next line.

https://play.crystal-lang.org/#/r/9qab

```cr
1.times
do
  puts "hi"
end
```

```
syntax error in eval:2
Error: expecting token 'EOF', not 'do'
```

Ofc the solution/more idiomatic way would be to just not do that.  But it would be nice if the formatter  could correct that for you.

**Comment by philipp-classen** [comment]
Just verified that the problems is reproducible on master, too:

```
Crystal 1.0.0-dev [135e9fbc3] (2020-09-18)

LLVM: 10.0.1
Default target: x86_64-pc-linux-gnu
```

**Comment by philipp-classen** [comment]
@asterite Thank you, just tried with the PR #9762 . That solves it. :+1:
