### ISSUE TITLE
Nested annotation issues

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#9766]
I'm working on a validation shard that is powered via annotations.  One constraint I'd like to include is `AtLeastOneOf`, which accepts `n` other constraint types and is valid if at least one of the nested constraints is valid.  Something like:

```cr
annotation AtLeastOneOf; end
annotation SomeConstraint; end
annotation AnotherConstraint; end

class User
  def initialize(@password : String); end

  @[AtLeastOneOf(
    SomeConstraint(message: "foo"),
    AnotherConstraint
  )]
  property password : String
end
```

However there are a few issues preventing this from working at the moment.  

1. It doesn't compile when there are named arguments within the inner annotations:

https://play.crystal-lang.org/#/r/9qf3

```
9 | SomeConstraint(message: "foo"),
^
Error: unexpected token: DELIMITER_START
```

2. It doesn't compile when there non numeric positional arguments:

https://play.crystal-lang.org/#/r/9qf4

```
9 | SomeConstraint("foo"),
^
Error: expecting token ':', not ')'
```

3. The positional arguments to the `AtLeastOneOf` annotation are not actually `Annotation` types.

https://play.crystal-lang.org/#/r/9qf5

```
16 | {{pp constraint.resolve.args, constraint.resolve.named_args}}
^---
Error: undefined macro method 'TypeNode#args'
```

**Comment by asterite** [comment]
That's because `SomeConstraint(...)` is not an annotation, it's a generic type instantiation.

**Comment by asterite** [comment]
You can do it like this:

```crystal
annotation AtLeastOneOf; end
annotation SomeConstraint; end
annotation AnotherConstraint; end

class User
  def initialize(@password : String); end

  @[AtLeastOneOf(
    @[SomeConstraint(message: "foo")],
    @[AnotherConstraint]
  )]
  property password : String
end
```

Which kinda makes more sense if these is referring to other annotations.

**Comment by Blacksmoke16** [comment]
Oh wow, my hero!  I didn't even think to try the `@[]` syntax.  Going to close as it seems this isn't actually an issue now.  Thanks!
