### ISSUE TITLE
Expr in nested begin..rescue doesn't update type union

### ISSUE THREAD

**Issue by z64** [crystal-lang/crystal#9769]
In the following code, there seems to be a missing type union, causing variables to be interpreted incorrectly:
```cr
int = 1
ary = [] of Int32
begin
  begin
    int = "a"
    ary.push(1)
  rescue
  end
rescue
end
p(typeof(int))
puts("ok")
puts(ary)
puts(int)
```
Output: (ran 4x)
```
Int32
ok
[1]
-1344447960

Int32
ok
[1]
-1853449688

Int32
ok
[1]
162196008

Int32
ok
[1]
-1811342808
```

This results in corrupt values or segfaults with other types.

Changes to this code that result in sound output:
- Remove one, or both `rescue` branches
- Restrict `int = 1` like `int : String | Int32`; output is correct
- Restrict `int = 1` like `int : Int32`; won't compile

---

Crystal 0.35.1 (2020-06-21)

LLVM: 10.0.0
Default target: x86_64-pc-linux-gnu

**Comment by asterite** [comment]
Thanks!

Reduced:

```crystal
int = 1
begin
  begin
    int = "a"
  rescue
  end
rescue
end
p(typeof(int))
puts(int)
```

Unless the array is needed for this?

**Comment by z64** [comment]
Nah, I just showed the array as an example of a type that isn't affected by the issue.
