### ISSUE TITLE
RFC: Hash from KVs

### ISSUE THREAD

**Issue by caspiano** [crystal-lang/crystal#9770]
I've found the snippet below to be a handy extension to `Hash`.

```crystal
class Hash(K, V)
  def self.from_key_values(kvs : Enumerable(Tuple(K, V)))
    kvs.each_with_object({} of K => V) do |(k, v), hash|
      hash[k] = v
    end
  end
end
```

I'm interested to hear if this (or something similar) is worth dropping into a PR.

**Comment by oprypin** [comment]
This is https://crystal-lang.org/api/0.35.1/Enumerable.html#to_h-instance-method

**Comment by caspiano** [comment]
Awesome!! Missed that :)
