### ISSUE TITLE
Issue about appending an element to an array that is the value of a hash

### ISSUE THREAD

**Issue by zhangkaizhao** [crystal-lang/crystal#9772]
Code:

```crystal
# not working
h1 = {} of String => Array(String)
h1["aa"] = ["11"]
h1["aa"] << "22"
h1["bb"] << "22"
# Unhandled exception: Missing hash key: "bb" (KeyError)
puts h1

# not working as expected
h2 = Hash(String, Array(String)).new(Array(String).new)
h2["aa"] = ["11"]
h2["aa"] << "22"
h2["bb"] << "22"
puts h2
# {"aa" => ["11", "22"]}

# working as expected but ugly
h3 = {} of String => Array(String)
h3["aa"] = ["11"]
h3["aa"] << "22"
_bb = h3["bb"]? || [] of String
_bb << "22"
h3["bb"] = _bb
puts h3
# {"aa" => ["11", "22"], "bb" => ["22"]}

# working as expected but not so good
# via https://forum.crystal-lang.org/t/how-to-append-to-array-that-is-the-value-of-a-hash-key/1217/4
h4 = Hash(String, Array(String)).new(Array(String).new)
h4["aa"] = ["11"]
h4["aa"] << "22"
# h4["bb"] = [] of String
h4["bb"] = Array(String).new
h4["bb"] << "22"
puts h4
# {"aa" => ["11", "22"], "bb" => ["22"]}

# working as expected but not so good
h5 = {} of String => Array(String)
h5["aa"] = ["11"]
h5["aa"] << "22"
h5["bb"] = Array(String).new
h5["bb"] << "22"
puts h5
# {"aa" => ["11", "22"], "bb" => ["22"]}
```

Can we remove the line like `h4["bb"] = Array(String).new` or `h5["bb"] = Array(String).new` and get expected in the future?

**Comment by Blacksmoke16** [comment]
To do what you want you'd need to do something like:

```cr
h2 = Hash(String, Array(String)).new { |hash, key| hash[key] = Array(String).new }
h2["aa"] = ["11"]
h2["aa"] << "22"
h2["bb"] << "22"
puts h2 # => {"aa" => ["11", "22"], "bb" => ["22"]}
```

This uses https://crystal-lang.org/api/master/Hash.html#new(initial_capacity=nil,&block:Hash(K,V),K-%3EV)-class-method to set the value of that missing key to an empty array.  I'm pretty sure all these examples are working correctly.

**Comment by bcardiff** [comment]
When the hash value is a collection or hash sometimes you want auto vivification. It's not a pattern that should be used lightly. If that is what you want, you can initialize those structures as explained in https://github.com/crystal-lang/crystal/issues/4376#issuecomment-299273442

**Comment by zhangkaizhao** [comment]
Thanks for the guides. It (creating new Hash instance with a block for handling missing keys) works but is a little complex.

The constructor detail of Hash https://crystal-lang.org/api/0.35.1/Hash.html#new(default_value:V,initial_capacity=nil)-class-method confuses me:

> ```crystal
> def self.new(default_value : V, initial_capacity = nil)
> ```
> 
> Creates a new empty Hash where the *default_value* is returned if a key is missing.
> 
> ```crystal
> inventory = Hash(String, Int32).new(0)
> inventory["socks"] = 3
> inventory["pickles"] # => 0
> ```
> 
> NOTE The default value is passed by reference:
> 
> ```crystal
> arr = [1, 2, 3]
> hash = Hash(String, Array(Int32)).new(arr)
> hash["3"][1] = 4
> arr # => [1, 4, 3]
> ```
> 
> The *initial_capacity* is useful to avoid unnecessary reallocations of the internal buffer in case of growth. If the number of elements a hash will hold is known, the hash should be initialized with that capacity for improved performance. Otherwise, the default is 8. Inputs lower than 8 are ignored.
> 

When changing the first example as follow and it works as expected:

```crystal
inventory = Hash(String, Int32).new(0)
inventory["socks"] = 3
inventory["pickles"] += 1
puts inventory # => {"socks" => 3, "pickles" => 1}
```

**Comment by zhangkaizhao** [comment]
> When the hash value is **a collection or hash** sometimes you want auto vivification. It's not a pattern that should be used lightly. If that is what you want, you can initialize those structures as explained in [#4376 (comment)](https://github.com/crystal-lang/crystal/issues/4376#issuecomment-299273442)

Oh. I didn't notice "a collection or hash". Sorry!
But the different behaviors on different types result in a inconsistency. This may not be a good design.

I am closing this issue.

**Comment by asterite** [comment]
Yeah, I think 'is passed by refetence" doesn't make any sense in the docs.
