### ISSUE TITLE
OpenSSL Compilation Error

### ISSUE THREAD

**Issue by russ** [crystal-lang/crystal#9773]
I just started getting this error today. I believe it's from a OpenSSL system upgrade I made. I'm running on Arch Linux, using asdf and Crystal 0.35.1

```
cc: internal compiler error: Segmentation fault signal terminated program cc1

In /home/russ/.asdf/installs/crystal/0.35.1/share/crystal/src/openssl/lib_crypto.cr:5:25

 5 | (`printf "#include <openssl/opensslv.h>\nLIBRESSL_VERSION_NUMBER" | ${CC:-cc} $(pkg-config --cflags --silence-errors libcrypto || true) -E -`.chomp.split('\n').last != "LIBRESSL_VERSION_NUMBER") %}
      ^
Error: error executing command: printf "#include <openssl/opensslv.h>

LIBRESSL_VERSION_NUMBER" | ${CC:-cc} $(pkg-config --cflags --silence-errors libcrypto || true) -E -, got exit status 4
```

I have this version of OpenSSL
```
OpenSSL 1.1.1g  21 Apr 2020
```

This stuff is a bit out of my knowledge base, so if there are any other details I can provide please let me know.

**Comment by naqvis** [comment]
Seems compiler unable to find the require header files. What output do you see when you run?
`pkg-config --cflags libcrypto` 

if it generates some error or you don't see the **include** path, then you have something misconfigured.

try setting the below variables before invoking crystal compiler

```SHELL
export LDFLAGS="-L/PATH_TO_OPENSSL_LIB"
export CPPFLAGS="-I/PATH_TO_OPENSSL_INCLUDE"
export PKG_CONFIG_PATH="/PATH_TO_OPENSSL_PKGCONFIG"
```

For example on my mac OpenSSL 1.1.1 installed via Homebrew I can set these as
```shell
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
```

**Comment by russ** [comment]
I actually get no output for the pkg-config command. I'll dig in to see if there is something misconfigured on my end report back.

**Comment by russ** [comment]
I reinstalled crystal and openssl just to be sure there aren't any problems there. pkg-config is now outputting for me as expected.

```
pkg-config --cflags --libs libcrypto
-I/usr/include/openssl-1.0 -L/usr/lib/openssl-1.0 -lcrypto
```

But I'm still having no luck getting stuff to compile.

```
export LDFLAGS="-L/usr/lib/openssl-1.0 -lcrypto"
export CPPFLAGS="-I/usr/include/openssl-1.0"
export PKG_CONFIG_PATH="/usr/lib/openssl-1.0/pkgconfig"

crystal build server.cr

cc: internal compiler error: Segmentation fault signal terminated program cc1
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.archlinux.org/> for instructions.
Showing last frame. Use --error-trace for full trace.

In /home/russ/.asdf/installs/crystal/0.35.1/share/crystal/src/openssl/lib_crypto.cr:5:25

 5 | (`printf "#include <openssl/opensslv.h>\nLIBRESSL_VERSION_NUMBER" | ${CC:-cc} $(pkg-config --cflags --silence-errors libcrypto || true) -E -`.chomp.split('\n').last != "LIBRESSL_VERSION_NUMBER") %}
      ^
Error: error executing command: printf "#include <openssl/opensslv.h>

LIBRESSL_VERSION_NUMBER" | ${CC:-cc} $(pkg-config --cflags --silence-errors libcrypto || true) -E -, got exit status 4
```

**Comment by russ** [comment]
@RX14 @ysbaddaden Do you think this might be related to #7245 ?

**Comment by ysbaddaden** [comment]
No idea. You may try the [`version.sh`](https://github.com/crystal-lang/crystal/pull/7245/files#diff-3b15dac1c24ada8d827a3de2d37a2f05) script and see if it passes. But I doubt it. The culprit is likely to be **your C compiler that is segfaulting**. See the error messages your reported:

```
cc: internal compiler error: Segmentation fault signal terminated program cc1
```

**Comment by russ** [comment]
I'm not sure if this is a passing result, but I do get a value for OPENSSL_VERSION_NUMBER.

```
./version.sh openssl
LIBRESSL_VERSION_NUMBER = 0x0
OPENSSL_VERSION_NUMBER = 0x1010108f
LDFLAGS = nil
```

**Comment by russ** [comment]
After doing a system update and rebooting it looks like everything is back to normal and working. I don't see anything in the system upgrade that should be affecting this, so I guess it was the reboot? lol, I have no clue.

Thanks for looking into that. Hopefully this will help someone else who might run across this issue.
