### ISSUE TITLE
Cannot find -lyaml

### ISSUE THREAD

**Issue by Nicolab** [crystal-lang/crystal#9783]
Hello,

I encountered this error:

```
/usr/bin/ld: cannot find -lyaml (this usually means you need to install the development package for libyaml)
[00] collect2: error: ld returned 1 exit status
[00] Error: execution of command failed with code: 1: `cc "${@}" -o /home/app/.cache/crystal/app-lib-i18n-src-i18n-backend-yaml_embed.cr/macro_run  -rdynamic -L/usr/bin/../lib/crystal/lib -lyaml -lpcre -lm -lgc -lpthread /usr/share/crystal/src/ext/libcrystal.a -levent -lrt -ldl`
[00] (error exit: exit status 1)
```

But `libyaml-dev` is installed.

Crystal -v:
```
Crystal 0.35.1 [5999ae29b] (2020-06-19)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```

The solution was to empty the compilation cache (`rm -rf /home/app/.cache`).

I think the cause is that at the beginning of the project I wasn't using Yaml. The cache was filled up like that. Then when I added a shard using Yaml (i18n), the cache may not have taken it into consideration.

**Comment by straight-shoota** [comment]
This error happend in the context of a macro run. Macros are cached between compiler runs. So probably related to that. Clearing the cache can often help with such issues. There is not much to do here. There have been discussions about improving cache invalidation, but no progress yet I assume.

**Comment by Nicolab** [comment]
Ok thanks
