### ISSUE TITLE
Prepare Windows GitHub Action for upcoming deprecations

### ISSUE THREAD

**Issue by bcardiff** [crystal-lang/crystal#9785]
Ref: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

`::set-env` is used https://github.com/crystal-lang/crystal/blob/master/.github/workflows/win.yml#L149-L155

**Comment by oprypin** [comment]
Oh no, that's going to break like all of the workflow files that I've ever written 😩
