### ISSUE TITLE
`make spec` raises an error from digest/md5.cr:134:25

### ISSUE THREAD

**Issue by sugarfi** [crystal-lang/crystal#9790]
When running `make spec` in the compiler source code to execute tests, the following error is thrown:
```
In /snap/crystal/current/share/crystal/src/digest/md5.cr:134:25

 134 | private def transform(in)
                             ^
Error: cannot use 'in' as an argument name
```
This prevents any tests from being run.
Input: `make spec`
Expected behavior: tests are run.
Actual behavior (full output, may vary slightly between machines):
```
Using /usr/bin/llvm-config-10 [version=10.0.0]
CRYSTAL_CONFIG_LIBRARY_PATH="/snap/crystal/397/bin/../lib/crystal/lib" CRYSTAL_CONFIG_BUILD_COMMIT="ee5813058" SOURCE_DATE_EPOCH="1601658550" ./bin/crystal build  --exclude-warnings spec/std --exclude-warnings spec/compiler -o .build/all_spec spec/all_spec.cr
Using compiled compiler at .build/crystal
In /snap/crystal/current/share/crystal/src/digest/md5.cr:134:25

 134 | private def transform(in)
                             ^
Error: cannot use 'in' as an argument name
make: *** [Makefile:110: .build/all_spec] Error 1
```

**Comment by Blacksmoke16** [comment]
What crystal version are you using?

That specific line was fixed a little while ago as part of https://github.com/crystal-lang/crystal/pull/9704.

**Comment by sugarfi** [comment]
> EDIT: Might just need a rebase on your branch, if your branch still has the in arg name.

Oh, ok. (BTW, my compiler is v0.35.1).
