### ISSUE TITLE
File#fsync, File#flock_exclusive, File#flock_shared, and File#flock_unlock belong in IO::FileDescriptor

### ISSUE THREAD

**Issue by BrucePerens** [crystal-lang/crystal#9793]
Unix-style file operations, like `File#fsync`, `File#flock_exclusive`, `File#flock_shared`, and `File#flock_unlock` belong in `IO::FileDescriptor`. On Windows these are completely different APIs, which perhaps is why they are presently in `File`. However, this is a significant handicap on Unix-like systems and makes the user want to import the API from `LibC`, which would be ugly and even less portable.

An example of how to code these APIs portably to Windows is at https://github.com/WoLpH/portalocker

Why is the user using `IO::FileDescriptor`? They are doing operations on `STDIN`, `STDOUT`, or `STDERR` (which can be legitimate files), or on a file descriptor inherited from the parent process, or passed in from a foreign library.

**Comment by asterite** [comment]
I think this was just a short sight when we added these methods. PRs are welcome to move them to IO::FileDescriptor. It should be pretty straight-forward.
