### ISSUE TITLE
Array#clone, and probably others, can't handle cycles in data.

### ISSUE THREAD

**Issue by BrucePerens** [crystal-lang/crystal#9795]
Array#clone is non-terminatingly recursive:
```crystal
alias X = Array(X)|Int32
a = Array(X).new
a << a
b = a.clone
```
One fix would be to document the behavior that it can't handle cycles in data, and leave it at that.
Another would be to add a loop detector which would properly reference an already-copied data structure rather than cloning it again. This would have a slight speed and complexity penalty.

Yes, I know that cycles are bad for garbage collection. The particular application I am working on goes to some pains to recursively clear its used data (with a loop detector), because it's real-time and shouldn't ever be stopped.

**Comment by asterite** [comment]
This is relatively simple to implement. If there's interest I can do it.
