### ISSUE TITLE
Backtick and classes

### ISSUE THREAD

**Issue by BrucePerens** [crystal-lang/crystal#9796]
This is perhaps more of an undocumented corner of the language rather than a bug. The compiler allows backtick to be overloaded, and notes that fact in error messages although it isn't otherwise documented:
```
Error: expecting any of these tokens: IDENT, CONST, `, <<, <, <=, ==, ===, !=, =~, !~, >>, >, >=, +, -, *, /, //, !, ~, %, &, |, ^, **, [], []?, []=, <=>, &+, &-, &*, &** (not '.')
```

But it doesn't do anything sensible with it. Calls to backtick in this example still go to the top-level one.

```crystal
class A
  def `(**double_splat)
    p double_splat
  end

  def call
    `testing...`
  end
end
```

**Comment by oprypin** [comment]
There's a mistake. Double splat will indeed not match positional args that the backticks use.

```crystal
class A
  def `(*double_splat)
    p double_splat
  end
 
  def call
    `testing...`
  end
end
 
A.new.call
```

This works

**Comment by asterite** [comment]
TIL you can use backtick defined on a type

**Comment by BrucePerens** [comment]
OK, this now works the way I wish, and closing the bug.
```crystal
class A
  def `(*splat)
    p splat
  end

  def interpret
    with self yield
  end
end

a = A.new
a.interpret do
  `testing...`
end
```

**Comment by asterite** [comment]
Note that backtick isn't supposed to be called as an instance method. This will most definitely change in the future so I wouldn't rely on this behavior.

The only reason why backtick is implemented as a method is so that we can change the implementation with Crystal itself

**Comment by BrucePerens** [comment]
It's not a bad feature from an expressiveness perspective, for example one can use it to access a shell on a remote server rather than the local one, or another interpretive language than the shell. Since it's free to do so, I suggest that it be kept as it is.
