### ISSUE TITLE
JSON::Any.nil? returns false

### ISSUE THREAD

**Issue by stakach** [crystal-lang/crystal#9807]
Hopefully a simple one, the work around is simple enough but thought it worth making an issue

```crystal
require "json"

test = JSON.parse("null")
test.nil?   # => false
test == nil # => true
nil.nil?    # => true
```

Maybe a special case of `.nil?` needs to be created for JSON::Any?

**Comment by Blacksmoke16** [comment]
Try `json.raw.nil?`

**Comment by stakach** [comment]
You're definitely right, `raw.nil?` is the way this should be checked.
