### ISSUE TITLE
Proc argument unpacking overwrites local variables

### ISSUE THREAD

**Issue by error256** [crystal-lang/crystal#9813]
Crystal 0.35.1
```crystal
x = 0
Proc({Int32}, Void).new{ |(x)| }.call({1})
p(x)
```
`x` becomes `1`.
This looks similar to https://github.com/crystal-lang/crystal/issues/2796. I'm not entirely sure what makes the difference, but it seems to happen only to Procs rather than any blocks now. As in the following case:
`[{1}].each.each{ |(x)| }` => just a block, `x` is `0`.
`[{1}].each.map{ |(x)| }.each{}` => `map` stores the block as `Proc`, `x` becomes `1`.

**Comment by kyku** [comment]
Also happens with the following snippet:
```
x = "good"
["bad"].each_with_index
  	.map { |(x, _)| x }
  	.each { puts x }
```
