### ISSUE TITLE
Union types with Generics causes (more) type-checking bugs

### ISSUE THREAD

**Issue by wolfgang371** [crystal-lang/crystal#9820]
The title is related to [#9797](https://github.com/crystal-lang/crystal/issues/9797), but the errors differ.
The first two one-dimensional array cases work as expected, the other one with a two-dimensional array, however does not. If you compile in both lines (A) and (B) it will not compile; if you exclude any or both, it does; in all cases `.class` and `typeof()` return what you would expect.

```crystal
# 1D array, easy
a1 = [] of Int32|Symbol
a1.push(:test)
a1[0] = :test       # compiles
a1[0] = 12          # compiles

# 1D array; see co-/contravariance in https://crystal-lang.org/reference/syntax_and_semantics/inheritance.html
a2 : Array(Int32|Symbol) = [:test] of Int32|Symbol
a2[0] = :test       # compiles
a2[0] = 12          # compiles

# 2D array
a3 = [] of Array(Int32|Symbol)
p a3.class          # -> Array(Array(Int32 | Symbol))
p typeof(a3)        # -> Array(Array(Int32 | Symbol))
a3.push([:test] of Int32|Symbol)
a3.push([:test])    # (A); compiles
p a3.class          # -> Array(Array(Int32 | Symbol))
p typeof(a3)        # -> Array(Array(Int32 | Symbol))
a3[0][0] = :test    # compiles
#~ a3[0][0] = 12    # (B); does not compile if (A) gets compiled in
```

To me it looks like a (minor?) type-checking bug in the compiler; line (A) should already lead to a compiler error to stay consistent with the one-dimensional example.
This (compiler) bug makes (user) code fixing more complicated because the compile error hints to a line that is ok; and you need to find the buggy one yourself.

**Comment by BlobCodes** [comment]
I just tested this with Crystal 1.0.0 and this seems to have been fixed.
Including (B) always works, and including (A) always gives the following error:
```
In test4.cr:17:4

 17 | a3.push([:test])    # (A); compiles
         ^---
Error: instantiating 'Array(Array(Int32 | Symbol))#push(Array(Symbol))'


In /usr/share/crystal/src/array.cr:1439:12

 1439 | @buffer[@size] = value
               ^
Error: instantiating 'Pointer(Array(Int32 | Symbol))#[]=(Int32, Array(Symbol))'


In /usr/share/crystal/src/pointer.cr:130:29

 130 | (self + offset).value = value
                               ^----
Error: type must be Array(Int32 | Symbol), not Array(Symbol)

```

Can be closed I guess.
