### ISSUE TITLE
Cannot receive datagram over unix socket

### ISSUE THREAD

**Issue by carlhoerberg** [crystal-lang/crystal#9835]
Maybe I'm doing something wrong, but this code:

```crystal
require "socket"

path = File.tempname
server = Socket.unix(Socket::Type::DGRAM)
server.bind Socket::UNIXAddress.new(path)

client = Socket.unix(Socket::Type::DGRAM)
client.connect Socket::UNIXAddress.new(path)
client.send "foo"

message, _ = server.receive
puts message
```

ends up with this exception:
```
Unhandled exception: Unsupported family type: UNSPEC (0) (Exception)
  from ../../../../usr/share/crystal/src/socket/address.cr:18:65 in 'from'
  from ../../../../usr/share/crystal/src/socket.cr:335:17 in 'receive'
  from ../../../../usr/share/crystal/src/socket.cr:331:3 in 'receive'
  from bug.cr:11:14 in '__crystal_main'
  from ../../../../usr/share/crystal/src/crystal/main.cr:105:5 in 'main_user_code'
  from ../../../../usr/share/crystal/src/crystal/main.cr:91:7 in 'main'
  from ../../../../usr/share/crystal/src/crystal/main.cr:114:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```

Error raised from here: https://github.com/crystal-lang/crystal/blob/0.35.1/src/socket/address.cr#L20

Looks like it's expected that the client address is supposed to be a `UNSPEC` for unix socket datagrams (makes sense, you can't really reply to it), so maybe just return nil, or a some sort of `UnspecifiedAddress`?

**Comment by asterite** [comment]
worksforme on mac

**Comment by j8r** [comment]
I can confirm, got the same error on Linux.

**Comment by asterite** [comment]
Then I'm almost sure the DGRAM value is incorrectly mapped for linux.

The way to solve this issue is by checking the values (you can use man, check the C source code or write a C program) and compare the values to the ones defined in Crystal.

I could do it with a VM or docker but I don't have time, so please, if someone else has time, go ahead :-)
