### ISSUE TITLE
unexpected behavior in gsub with regex for $

### ISSUE THREAD

**Issue by NIFR91** [crystal-lang/crystal#9842]
Hello I think this is a bug in `gsub` for `string`

```crystal
# Crystal 
str = <<-str
# comment
text1 # other comment

str
p str.gsub(/#.*$/,"") #=> "# comment\n" + "text1\n"
p str.gsub(/#.*/,"")  #=> "\n" + "text1\n"
```

I expected the first form to delete the comments just like the second form, i checked
in ruby and both forms return the same output. 

```ruby
# Ruby 
str = <<~str
# comment
text1 # other comment

str
p str.gsub(/#.*$/,"") #=> "\n" + "text1\n"
p str.gsub(/#.*/,"")  #=> "\n" + "text1\n"
```

Versions: 

```txt
Crystal 0.35.1 (2020-06-21)

LLVM: 10.0.0
Default target: x86_64-pc-linux-gnu
```

```txt
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
```

```txt
Linux mio 5.8.16-2-MANJARO #1 SMP PREEMPT Mon Oct 19 11:33:03 UTC 2020 x86_64 GNU/Linux
```

**Comment by NIFR91** [comment]
On a more detailed inspection I think it is the expected behavior, Ruby treats it different but I agree on crystal's.

**Comment by asterite** [comment]
Related to https://github.com/crystal-lang/crystal/issues/8062

Neither Ruby nor Crystal are correct, it seems either approach is fine depending on how you look at it.
