### ISSUE TITLE
Please add crystal.zip containing (crystal.exe and the libs) to the Release artefacts going forward

### ISSUE THREAD

**Issue by rishavs** [crystal-lang/crystal#9843]
Right now programmatically fetching the crystal exe for any release from the CI is very hard.
For using package managers like Scoop, it is very difficult to create a script for setting up Crystal on the Windows device without this first step.
Adding a direct path to the crystal exe and corresponding libs for every releases at least open windows package managers to consider having app packages for Crystal on Windows.

Even if we don't have full windows support, we should look at making the act of using Crystal on Windows as painless as possible.

Note: I know that networking is missing but at least other use cases like gamedev, shell programming etc can still be done in Crystal.

**Comment by rishavs** [comment]
The related discussion in Scoop repo is at https://github.com/lukesampson/scoop/issues/3775

**Comment by oprypin** [comment]
This is https://github.com/crystal-lang/distribution-scripts/issues/64

**Comment by jhass** [comment]
Indeed, let's focus discussion over there!

**Comment by rishavs** [comment]
This should be separate issue to easily track it. We just released 0.36 without the windows exe in the release artifacts.
It will be lost these in those discussions otherwise.
