### ISSUE TITLE
XOR and NOT logical operators

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#9862]
When looking at some logic chains I am workin with in ruby I thought it would be nice to have more tools to have for logic operation chains.  The biggest problem is chaining logical operations with `!`.

Proposal:
Add XOR and NAND logical operators.

XOR would be `!|`

example:
```crystal
true || true #=> true
true !| true #=> flase
true || false #=> true
true !| false #=> true
```

NAND would be `!&`

example:
```crystal
true && true #=> true
true !& true #=> false
true && false #=> false
true !& false #=> false
false && false #=> false
false !& false #=> true
```

This does not follow other bitwise syntax I have seen but it keeps some similar idea and adds more tools for logical operations.

**Comment by Blacksmoke16** [comment]
Pretty sure `XOR` is already a thing.  https://crystal-lang.org/reference/syntax_and_semantics/operators.html#binary

https://play.crystal-lang.org/#/r/9w8t

However `NAND` isn't a thing based on the docs at least.

**Comment by wontruefree** [comment]
I missed that in the documentation because I didn't realize it would work with bools.
This might be already mostly done.  I think that syntax will be hard to utilize on my team at work, but that is not a language problem.
