### ISSUE TITLE
Chained logical disjunction breaks type inference with #is_a?

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#9891]
It appears the `||` operator causes type inference to fail if more than one is used together and each predicate applies type restrictions to the variables used:

```crystal
def f1(x)
  x.is_a?(Int8) ? x : x[0]
end

def f2(x)
  x.is_a?(Int8) || x.is_a?(Int8) ? x : x[0]
end

def f3(x)
  x.is_a?(Int8) || x.is_a?(Int8) || x.is_a?(Int8) ? x : x[0]
end

typeof(f1("")) # => Char
typeof(f2("")) # => Char
typeof(f3("")) # => (Char | String)
```

Here Crystal seems to decide that the true branch of the ternary inside `f3("")` is reachable, and thus include `String` in its return type. Similar results can be obtained with `#responds_to?` as well.

`case` expressions with type conditions are a special case of the above; they break if 3 or more clauses follow a `when`:

```crystal
def f3_case(x)
  case x
  when Int8, Int16, Int32
    x
  else
    x[0]
  end
end

typeof(f3_case("")) # => (Char | String)
```

In contrast `&&` doesn't break like this:

```crystal
def f3_and(x)
  x.is_a?(Int8) && x.is_a?(Int8) && x.is_a?(Int8) ? x : x[0]
end
typeof(f3_and("")) # => Char
```

**Comment by asterite** [comment]
I'm pretty sure this is reported already as a different bug. The problem is that I don't know how to search for such issue.

**Comment by docelic** [comment]
@asterite Is the previous report this? https://github.com/crystal-lang/crystal/issues/8864

**Comment by asterite** [comment]
Yes, that's the one!
