### ISSUE TITLE
Topological Sort

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#9922]
Ruby has a TSort stdlib https://rubyapi.org/2.7/o/tsort. Should Crystal have a TSort as a part of the stdlib?
It seems like it could be really useful?

If we dont have one in the stdlib it might be a good candidate for the crystal community repo.

**Comment by LEoREo2247** [comment]
If we're going to implement TSort for Crystal, should we make a standalone class like Ruby to allow extending it for custom classes, or just implement few methods as a part of Hash or (perhaps) Enumerable?

**Comment by oprypin** [comment]
Can we change the issue's title to "Topological sort"

I guessed something completely different

**Comment by jhass** [comment]
Why does this need to be in the standard library vs a shard?

**Comment by wontruefree** [comment]
Since this comment I have found a shard in the community but it might be out of date.
https://github.com/namusyaka/crystal-tsort

I am no longer working on this,  I can close, someone else can close or this issue or move it to another location.  I am leaving this open for now in case other people want to discus this.

**Comment by jhass** [comment]
Let's close for now, feel free to continue discussing, we can always reopen.

**Comment by femto** [comment]
so what's the status of this one, do we need to reopen the discussion?

**Comment by Sija** [comment]
Since the last message was sent 3 yrs ago it doesn't seem like it.
