### ISSUE TITLE
Undocumented behavior of NamedTuple#to_h

### ISSUE THREAD

**Issue by BrucePerens** [crystal-lang/crystal#9923]
The behavior of `NamedTuple#to_h` with an empty tuple is not documented.
```crystal
def foo(**args)
  p args.to_h.class.name
end

foo()
```
prints:
```
"Hash(NoReturn, NoReturn)"
```

OK, this might be appropriate while we can't create Hash(Symbol, Value), but it should be documented.

**Comment by bcardiff** [comment]
It could be `Hash(Symbol, NoReturn)` at most. There is no value type to infer from it. Yet, when trying to extract any key will lead to an exception actually, because there is none.

When a given expression is known to raise the `NoReturn` is the type given to it.

This is more a consequence rather than a choice.

If which context is this causing an issue?

**Comment by BrucePerens** [comment]
This obviously won't work:
```
def foo(**args)
  args.to_h[:a] = true
end
foo()
```

But it would if `args` was something like `NamedTuple(Symbol, Value)`. Obviously the compiler isn't capable of that today. It's easy to work around.

**Comment by straight-shoota** [comment]
I don't think this could be changed to anything useful. `Hash(NoReturn, NoReturn)` matches my excectation of `NamedTuple.new.to_h` type. It should just be added to the method documentation.

**Comment by straight-shoota** [comment]
The same applies to `NamedTuple.new.to_a` and `Tuple.new.to_a` as well, btw.

**Comment by asterite** [comment]
Also remember to never use named tuples. Then you won't run into these things :-)

(I personally don't find a good use case for named tuples)

**Comment by bcardiff** [comment]
@BrucePerens I think is safer to create a named tuple with the values you want and then converted to hash.

```cr
def foo(**args)
  pp! args.merge({a: true}).to_h
end

foo()
```

If you have a hash `h` of specific type, then you should be able to `tuple.each do |key, value|` and assign `h[key] = value`. Here the hash should be of the unions of all the possible value types in the tuple.

If you have a tuple `t` with the values you want you can merge them. `args.merge(t)` (or `t.merge(args)`) will probably be enough if you are playing with forwarding named arguments with defaults.

**Comment by BrucePerens** [comment]
> Also remember to never use named tuples. Then you won't run into these things :-)
> (I personally don't find a good use case for named tuples)

If they were replaced entirely with `Hash`, and we got the same easy literal entry `{ symbol: value}` for `Hash`, I think it would be better for all concerned. Today, I use them _only_ because the literal syntax is easier to write. My code invariably converts them to `Hash` at runtime.
