### ISSUE TITLE
About Function Naming

### ISSUE THREAD

**Issue by vfuqyy** [crystal-lang/crystal#9925]
How about renaming `gets` of the TCP/UDP Socket and Server API to `get`?

**Comment by straight-shoota** [comment]
Why?

**Comment by vfuqyy** [comment]
> Why?

if sending function is `send` then why getting function is `gets`?

**Comment by jhass** [comment]
For  `UDPSocket`  the inverse of `send` is `receive`, not `gets`. `gets` is an abstraction over `read(Bytes)` coming from the `IO` module.

**Comment by HertzDevil** [comment]
`gets` comes from Ruby which ultimately comes from C. With #11896 it would hopefully be more apparent that the `s` means "string".
