### ISSUE TITLE
the api documentation for the Macro "module" wrongly claims that Macro classes inherit from Object

### ISSUE THREAD

**Issue by void-witch** [crystal-lang/crystal#9932]
the [api documentation](https://crystal-lang.org/api/0.35.1/Crystal/Macros/TypeNode.html) for Macro classes state that the classes inherit instance methods from `Object`, which is incorrect. i assume it's because Macro classes aren't actually real classes, but the documentation just assumes everything inherits from Object and Reference

it's not a huge issue, but definitely confusing trying to call `TypeNode#to_s` and having the compiler tell you that TypeNode doesn't have a to_s method

**Comment by Blacksmoke16** [comment]
@asterite I think the way to fix this would be to do https://github.com/crystal-lang/crystal/pull/9091/files#diff-bb39a22cb4b0d7bfedfc96429c070ad88e18c7723f65310f0435945a73ef688c but make the superclass of the `ASTNode` type `nil` versus `reference` would fix this yea?

**Comment by 3n-k1** [comment]
@Blacksmoke16 trying to make the superclass `nil` errors with `Error: expecting token 'CONST', not 'nil'`. trying to make it `Nil` gives `Error: Nil is not a class, it's a struct`. unless that pr changes something i'm not seeing, i don't think it'll be that easy to fix

**Comment by asterite** [comment]
I would just hardcode this rule in the doc generator.
