### ISSUE TITLE
[RFC] Allow `Iterator#zip` to take more than one `Iterator`

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#9942]
#7453 allowed `Enumerable#zip` to take multiple other iterable objects, but the PR didn't extend this to `Iterator#zip`. This means the latter may or may not consume its elements depending on the number of arguments, due to the former overloads:

```crystal
(1..5).each.zip((2..).each) # => Iterator::Zip(...)
(1..5).each.zip((2..).each, (3..).each) # => [{1, 2, 3}, {2, 3, 4}, {3, 4, 5}, {4, 5, 6}, {5, 6, 7}]
```

Contrast this to Ruby:

```ruby
(1..5).lazy.zip((2..).lazy) # => #<Enumerator::Lazy: ...>
(1..5).lazy.zip((2..).lazy, (3..).lazy) # => #<Enumerator::Lazy: ...>
```

I believe Crystal's behaviour is unintuitive and `Iterator#zip` should accept any number of `Iterator` arguments as well. (If any of the arguments is an `Indexable` or `Iterable`, or if a block is provided, then `#zip` would still fall back to `Enumerable`'s overloads.)

**Comment by asterite** [comment]
The problem is thar this requires a splat type variable for the result and this is probably not working at the moment. If someone wants to try it, go ahead, but they will probably hit some language limitations.

**Comment by straight-shoota** [comment]
If it doesn't work, we should probably still add an overload for `Iterator#zip` with mutliple `Iterator` argument and have it raise at compile time. The current behaviour is very much unexpected.

**Comment by asterite** [comment]
Oh, I found a trick for this, hehe (it might not be as performant as it should, but we could go with that until we find a better solution, and actually LLVM might optimize it because the `map` iterator is a struct):

```crystal
module Iterator(T)
  def zip(*other : *T) : Iterator forall T
    iterator = self.zip(other[0])
    {% for v, i in T %}
      {% if i != 0 %}
        iterator = iterator.zip(other[{{i}}]).map do |x|
          {
            {% for j in 0..i %}
              x[0][{{j}}],
            {% end %}
            x[1]
          }
        end
      {% end %}
    {% end %}
    iterator
  end
end
```

Feel free to send a PR with it, together with a couple of tests (I won't have time).
