### ISSUE TITLE
Replace attributes (e.g. TypeNode#has_attribute?) with annotations

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#9943]
`TypeNode#has_attribute?` was introduced in [0.6.1](https://github.com/crystal-lang/crystal/blob/fd5e53f922b63fccb2bb34cfe40c27b160cfb9c4/CHANGELOG.md#061-2015-03-04); since then, it has only ever supported `@[Flags]` and `@[Packed]`, and both cases can be checked using annotations instead, which have been present since 0.25.0:

```crystal
@[Flags]
enum E
  X
end

@[Packed]
@[Extern]
struct A
  @x = 0
end

{% p E.has_attribute?("Flags") %} # => true
{% p !E.annotation(Flags).nil? %} # => true

{% p A.has_attribute?("Packed") %} # => true
{% p !A.annotation(Packed).nil? %} # => true

# everything except `Flags` or `Packed` is unsupported
{% p A.has_attribute?("Extern") %} # => false
{% p !A.annotation(Extern).nil? %} # => true
```

Since attributes and annotations are supposed to mean the [same](https://github.com/crystal-lang/crystal/pull/6063) [thing](https://gitter.im/crystal-lang/crystal?at=5fb796432a6c794bd8f77631), I think 1.0.0 is a good time we clean up all remaining mentions of "attribute" and replace them with "annotation". This means

* Removing `TypeNode#has_attribute?`, and the internal `Crystal::Type#has_attribute?` whose sole purpose is to expose `@[Flags]` and `@[Packed]` to the macro interpreter.
* Replacing "attribute" in the docs (e.g. in [`Enum`](https://github.com/crystal-lang/crystal/blob/master/src/enum.cr#L29)) with "annotation".
* Optional: adding a `TypeNode#has_annotation?(type : TypeNode) : BoolLiteral` method which returns exactly `!annotation(type).nil?`, to make transitioning easier. Same method can be _added_ to `Crystal::Annotatable` itself as well as annotatable nodes that currently don't have `#has_attribute?`, i.e. `Def` and `MetaVar`.

**Comment by straight-shoota** [comment]
Sounds good :+1: Thanks for digging into this. I don't expect `has_attribute?` has seen much use at all (if any).

I would leave `#has_annotation?` out. If there's a particular use case for this, we can add it later. But typically you would just need `#annotation` because you don't need negated `.nil?` if you use it as a condition for example.
```cr
{% if E.annotation(Flags) %}
  {% p "true" %}
{% end %}
```
