### ISSUE TITLE
Hash: indexed or not (officially)?

### ISSUE THREAD

**Issue by j8r** [crystal-lang/crystal#9952]
This issue's goal is to clarify if the Hash is supposed to be exposed indexed or not.

The Hash implementation uses an index and preserves order, that's why it is possible to have methods related to key indexes, like `Hash#key_index(key)`, `#first_*`, `#last_*`, and hidden implementation method like `get_entry(index)`.

## Today

- The public API states an Hash is ordered
> Enumeration follows the order that the corresponding keys were inserted.
- some methods mention indexes `#key_index` and `values_at(*indexes : K)` (the former should be `keys`)
- indeed, some methods related to indexes lacks. Note that `Indexable#[index]` would conflict with the existing `Hash#[key]`

## Next

- If Hash is assumed to be indexed, maybe investigate to add methods related to indexes, maybe even including `Indexable` (:warning: conflicts)
- If Hash is not assumed to be indexed, drop `Hash#key_index`.

Anyway, `Hash#values_at(*indexes : K)` should be renamed to `Hash#values_at(*keys : K)`.

**Comment by asterite** [comment]
Hash is ordered. This is nice because when you dump it to JSON the order of insertion is preserved. But I wouldn't go as far as adding indexing methods to it.

**Comment by straight-shoota** [comment]
> Anyway, Hash#values_at(*indexes : K) should be renamed to Hash#values_at(*keys : K).

That should be fixed. Apart from that, we're fine.

**Comment by j8r** [comment]
Ok, I'm ok with that too @straight-shoota . And what about `Hash#key_index`? After asking on Gitter, some people are perplexed about its presence and purpose.

**Comment by straight-shoota** [comment]
It may be unexpected, but I don't know why it should be removed. Hash is explicitly ordered, kv paris have an index. So it's perfectly fine to reveal that.

**Comment by docelic** [comment]
We have `values_at(*keys)`.
In the context of discussion about `key_index`, how about adding related methods `keys_at_indexes(*indexes)` and possibly `values_at_indexes(*indexes)`?

(Granted, this can already be done with h.keys[idx] and/or h.values[idx] but they force converting the complete hash to an array, whereas the proposed `*_at_indexes` methods would return results similarly to how `values_at` does it.)

**Comment by asterite** [comment]
I added key_index because I needed it in the compiler.

I think we should remove that method. Also remove value_index if it's defined. key_index can be easily done in one or two lines, and I can do that in the few places used in the compiler. I'll send a PR later for this.
