### ISSUE TITLE
[RFC] Sampling without replacement in any `Indexable`

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#9954]
Currently, `#sample` is defined in two places:

* [`Indexable#sample(random = Random::DEFAULT)`](https://github.com/crystal-lang/crystal/blob/605ec43fcfa7286eae3e28ad212514bda0d3f3e3/src/indexable.cr#L568)
* [`Array#sample(n : Int, random = Random::DEFAULT)`](https://github.com/crystal-lang/crystal/blob/605ec43fcfa7286eae3e28ad212514bda0d3f3e3/src/array.cr#L1692)

`Array` has both overloads, but other `Indexable`s can only sample one element at a time. Judging from the second overload's implementation, it should be fairly easy to move that overload from `Array` into `Indexable`, so that sampling multiple elements (without replacement) from containers like `StaticArray` and `Deque` becomes possible, without the need to construct a temporary `Array`. My guess is `@buffer[i]` becomes `unsafe_fetch(i)` and `dup` becomes `map(&.itself)`.

This leads to a problem immediately: should `Slice` redefine `#sample(n)` to return a `Slice` instead of an `Array`? It also has `#shuffle!`, so it can be used as a drop-in replacement for `Array(T).new(n)` in the current implementation. (This does not apply to `StaticArray#sample(n)` because it is impossible to copy `n` to a generic type variable.) And `Slice` is allowed to do this because some other `Enumerable` methods redefined in `Slice` are also covariant, most notably `#map`, but once we go forward with this it's significantly harder to change the return type of an existing method (making `Deque#map` return a `Deque` for example).

**Comment by asterite** [comment]
I'm starting to think that we could move a lot of methods from Array into Indexable, even if those return Array.

**Comment by HertzDevil** [comment]
After some more thinking: Algorithms defined over the elements of arbitrary `Indexable`s should return `Tuple`s if the size of a container can be determined at the type level, e.g. the individual elements of the new Cartesian product methods, and `Array` otherwise. By this logic:

* `#sample` is an algorithm defined over the elements of any `Indexable`, but the size of the returned container depends on the *n* argument, so it should always return `Array`. It is unlikely making it return covariant values only for certain types would bring any substantial benefits.
* `#permutations` and friends can be safely moved to `Indexable` for a similar reason; they only depend on `#size` and `#unsafe_fetch`. They would all return arrays of arrays.
* `#<=>` can be moved too; we'd then have `#equals?` for equality and `#<=>` for lexicographical ordering between arbitrary `Indexable`s. This doesn't mean `Indexable` should include `Comparable(Indexable)`, because of issues related to hash equivalence; including types can still `include Comparable(self)` themselves.

The other methods in `Array` I'm not so sure (most importantly `#[]`, viz. #7619).
