### ISSUE TITLE
Abstract def with typeless block must be implemented

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#9958]
Against Crystal nightly:

```cr
module SomeInterface
  abstract def foo(&) : Nil
end

class Example
  include SomeInterface

  def foo(&) : Nil
    yield 1
  end
end
```

``Error: abstract `def SomeInterface#foo(&block)` must be implemented by Example``

Probably related to https://github.com/crystal-lang/crystal/pull/9585?

Updating the type of the block in the interface to `& : Int32 ->` makes it work fine.

Also somewhat related, the error message probably should say `&block` since this method does not capture the block.

EDIT:  Probably related more so to https://github.com/crystal-lang/crystal/pull/9634?  Removing the `yield 1` fixes it as well.  Doesn't the compiler to some magic stuff to auto type the block based on yielded values?  Because of that its not considering the implementation's block to be typeless.

**Comment by Blacksmoke16** [comment]
For now a workaround would be to type the block to allow anything, i.e. `& : _ -> _` or `& : _ -> Nil`.

**Comment by asterite** [comment]
This is not a bug.

In the interface you are saying the method receives a block that takes no arguments and returns nothing (that's the default behavior of a block in a type signature **that matters**). But in the implementation you provide an argument.

This works fine:

```crystal
module SomeInterface
  abstract def foo(& : Int32 -> Nil) : Nil
end

class Example
  include SomeInterface

  def foo(&) : Nil
    yield 1
  end
end
```

We yield an Int32 in the interface and in the implementation.

**Comment by asterite** [comment]
You can't represent that so don't use an abstract def. You will still be able to code it.
