### ISSUE TITLE
HTTP::Headers doesn't support multi-line headers, that's probably necessary for the Report-To header.

### ISSUE THREAD

**Issue by BrucePerens** [crystal-lang/crystal#9961]
The Content Security Policy header "Report-To" is usually multiline. Examples are [here]( https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to), one is:
```
Report-To: { "group": "csp-endpoint",
             "max_age": 10886400,
             "endpoints": [
               { "url": "https://example.com/csp-reports" }
             ] },
           { "group": "hpkp-endpoint",
             "max_age": 10886400,
             "endpoints": [
               { "url": "https://example.com/hpkp-reports" }
             ] }
Content-Security-Policy: ...; report-to csp-endpoint
```

So, I tried to code this as:

```crystal
policy = <<-END
<multi-line content>
END
request.headers.add("Report-To", policy)
```
 And I get this complaint:
```
GET /dynamic/en-US/edit/page/1?_csrf=
 ▸ Handled by Action::Edit::Page::Edit
 ▸  ArgumentError 

     Header content contains invalid character '\n'

    Backtrace 

     ../../../../../usr/share/crystal/src/http/headers.cr:337:7 in 'check_invalid_header_content'
     ../../../../../usr/share/crystal/src/http/headers.cr:122:5 in 'add'
```

For now, I can make it single-line, but it seems the convention is for HTTP headers to be readable.

**Comment by asterite** [comment]
Does this work with other http servers? For example Ruby or Go? It seems newlines in an HTTP header are [obsolete but still used](https://stackoverflow.com/questions/31237198/is-it-possible-to-include-multiple-crlfs-in-a-http-header-field/31324422).

**Comment by straight-shoota** [comment]
Line breaks in header values are obsolete. There's no reason to support them in `HTTP::Headers`. https://tools.ietf.org/html/rfc7230#section-3.2.4

The example on MDN seems to be outdated as well. The referenced [darft of the Reporting API](https://w3c.github.io/reporting/) has no mention of `Report-To` header.

**Comment by BrucePerens** [comment]
@straight-shoota That draft says the header is now named Reporting-Endpoints, and is a "dictionary structured header". See [RFC on *stuctured* headers](https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html)

Sorry that this is all a moving target.

**Comment by straight-shoota** [comment]
Sure. But the new RFC doesn't mention multiline header values either. That would be in violation to 7230. It mentions that structured headers can be split across multiple field lines, but such also include a header name. This should be supported by `HTTP::Headers`.

Do you think there is anything actionable here?

**Comment by BrucePerens** [comment]
Gosh, I don't know. I'm going to close the report rather than spend a long time working out the RFC talmud. Thanks!
