### ISSUE TITLE
Contribute a port of the ruby standard module Find

### ISSUE THREAD

**Issue by 4ndyfix** [crystal-lang/crystal#9967]
Hi,
I would like to contribute a port of the ruby standard module "Find"
(supports the top-down traversal of a set of directories).
Code, specs and docs are already available ...

**Comment by jhass** [comment]
Hey!

I'm not sure this is compelling for the standard library just yet. What do you think about publishing it as a shard at first? We can always talk about shipping very popular shards with the standard library :)

**Comment by straight-shoota** [comment]
Considering the implementation is just [40 LOC ](https://github.com/ruby/ruby/blob/7aaf6676c416e773b0b3053de2e250a73c2b2e77/lib/find.rb#L38-L73) I don't mind adding this to stdlib.

**Comment by j8r** [comment]
Having a `Find` module with single methods sounds overkill. A place could be `FileUtils.find`, or even `Dir`.

**Comment by j8r** [comment]
Having a `Find` module with a single method sounds overkill. An other place can be `FileUtils.find`, or even `Dir`.

**Comment by jhass** [comment]
Implementation size is just one of the things to consider, and pretty far down in priority on my list of things. Other considerations are implementation complexity, thus maintenance overhead, top level namespace pollution as @j8r noted, feature overlap with other parts of stdlib (avoiding the "should I use this or that" question) and finally how much user ergonomy this really adds in comparison to these costs.

I don't feel like given these additional considerations that this is a really obvious addition.

**Comment by straight-shoota** [comment]
You're right, of course. It's also worth considering that this is a generically useful feature. On the shell I use `find` quite often. But not so much have I missed it in Crystal, though. So maybe it's not even that common and useful 🤷

**Comment by asterite** [comment]
Ooooh... that's why it's called `Find`! 🤯

**Comment by 4ndyfix** [comment]
Thanks to all for reaction and discussion!
Maybe I should it publish as a shard at first.
