### ISSUE TITLE
Spec focusing doesn't work when nested

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#9989]
```cr
require "spec"
 
describe "One", focus: true do
  it "gets called" do
    pp "This shouldn't get called"
  end
  
  it "also also gets called", focus: true do
    pp "This should get called"
  end
end
 
 
describe "Two" do
  it "doesn't get called" do
    pp "This shouldn't get called"
  end
end
```

https://play.crystal-lang.org/#/r/a0i3

Sometimes I find myself working on specs for a specific type, so I add `focus: true` to the outermost describe block to only run the tests relevant to what I'm working on.  In some cases I'll want to also focus on a specific spec, such as for debugging why it's failing; so I add `focus: true` to that specific `it` block too.  However even tho a specific `it` block is focused, all the other specs in other describe block, that also is focused, will also run.  

In this example I would have expected only the one `it` block being executed.

**Comment by straight-shoota** [comment]
This works as expected. When you designate the entire `describe` block as `focus: true` all specs inside that block are focused. If you only want to run a single spec, you should only have ´focus: true` on that individual spec.

**Comment by Blacksmoke16** [comment]
@straight-shoota That seems less than ideal.  Why can't it just find the most specific `focus: true` versus needing to remove it from one thing add it to another?

**Comment by straight-shoota** [comment]
When you set `focus: true` the respective spec or group is executed. IMO that simple rule is totally fine.
You always need to remove `focus: true` if you want to focus on somthing else.

**Comment by Blacksmoke16** [comment]
@straight-shoota I agree if the additional `focus: true` would be a spec in _another_ totally different group.  However when it's within the same group you previously focused I think the better user experience would be to focus the group/spec at the lowest "level".

By focusing the `describe` block it's assumed you're only interested in those specs, so why prevent someone from also focusing on a specific spec within that `describe` block?

**Comment by asterite** [comment]
If you can write a PR for it, I think this is fine.

On the other hand, even though I implemented `focus` I never use it. I tried using it a couple of times but I find it so much easier to copy the reference to the file:line I'm working on and pass that to `crystal spec` (there's a plugin in Sublime Text 3 to do that, I think in VS Code too and probably many others).

**Comment by jwoertink** [comment]
I use `focus` all the time, and I'd say the current functionality is what I'd expect to happen. I think it should always run ALL specs that are being focused. You may have a single focus in 2 different spec files, and when running `crystal spec`, it would run both of them.

```crystal
# a_spec.cr
it "is focused", focus: true do
end

# b_spec.cr
it "is also focused", focus: true do
end
```

So if you just wanted a single spec to run, then you'd only ever place a focus on that specific one (or use the file/line as @asterite  mentioned).

On a side note, [I made this for those using ameba](https://github.com/crystal-ameba/ameba/issues/172) 😬

**Comment by straight-shoota** [comment]
I think there are reasonable arguments for this behaviour being acceptable and even preferrable over the proposed alternative.
Implementing this would add additional complexity and it's not really better. If I have two nested `focus: true` on different levels, there's no way to tell which one of them is "intended". It could be the inner as much as the outer. Keeping the current behaviour is easier in comprehension and implementation.
