### ISSUE TITLE
type-based `Log.for` for nested source scoped to top level

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#9991]
When a log source is resolved as a nested source using `Log.for(Class)`, the resulting source is not nested but bound to top level.

```cr
require "log"

module Bar
end

Log.for("foo").for("bar").info { "" } # INFO - foo.bar: x
Log.for("foo").for(Bar).info { "x" }  # INFO - bar: x
```

I'd expect the log event to be logged to `foo.bar` source in both cases.

If I want a log source for `bar`, I would use `::Log.for(Bar)` directly and don't need to scope it to `Log.for("foo")`.

**Comment by bcardiff** [comment]
My way of seeing it is that types are absolute reference. 

The fact that `Log.for` and `Log#for` behaves the same way is for ergonomics for moving code around.

I think it won't play nice in nested types:

```cr
class Foo
  Log = ::Log.for(self)

  class Bar
    def log
      Log.for(self)
    end
  end
end
```

If we follow your suggestion, `Bar#log` would return `foo.foo.bar` as a source.

**Comment by asterite** [comment]
Maybe you could check if it's already nested and then don't nest it.

**Comment by straight-shoota** [comment]
@bcardiff Yeah, that sounds fair. Probably fine to leave it like that.
`Log.for(self)` is just a shortcut anyway, so you can just use a string and it's fine.
I don't think this needs more complexity @asterite
